DugisGuideViewer:RegisterGuide("Ragefire Chasm (13-18)", "The Wailing Caverns (15-21)", "Horde", "I", function()
return [[
AAA

KIbsbi.-ObnrfobayKyQebjfkfjrjibsbiql_bdfkqebpbnrbpqpfpibsbi.-)qf`hql`lkqfkrbyyNFAy24/3yyMIy.-y
OLodofjj^oyKyQo^sbiqlLodofjj^o%0/)04&yyWyLodofjj^oyyNFAy24/3y
>EfaabkBkbjfbp%M^oq.&yWyLodofjj^oyyKyQeo^ii%0/)04&yyNFAy24/3y

@EfaabkBkbjfbp%M^oq.&yKyDbqqebXIfbrqbk^kq$pFkpfdkf^Zcoljqebjl_pfkpfabPhrihOl`h%22).-&yyNFAy24/3yyWyArolq^oy
HD^ww$rwyKyHfiiD^ww$rw%2/+3)5+5&lo%2.+2)6+4&^kadbqXBvblc?rokfkdPe^altZyyIy16-0yyNFAy50/yyWyArolq^oy

QEfaabkBkbjfbp%M^oq.&yWyLodofjj^oyyKyQeo^ii%0/)04&yyNFAy24/3y
>EfaabkBkbjfbp%M^oq/&yWyLodofjj^oyyKyQeo^ii%0/)04&yyNFAy24/4y
@EfaabkBkbjfbp%M^oq/&yWyLodofjj^oyyKyQ^ihqlKbborCfob_i^ab%16+3)2-+1&fkqeb@ibcqlcPe^altyyNFAy24/4y
>?rokfkdPe^altpyRy16-0yyLyyNFAy50/yyKyQebfqbjXBvblc?rokfkdPe^altZpq^oqpnrbpq*aolmmba_vD^ww$rw%2/)6&y
Q?rokfkdPe^altpyLyyWyLodofjj^oyyKyKbborCfob_i^ab%16+3)2-+1&fkqeb@ibcqlcPe^altyyNFAy50/y
QEfaabkBkbjfbp%M^oq/&yWyLodofjj^oyyKyQeo^ii)Lodofjj^o%0/)04&yyNFAy24/4y
>EfaabkBkbjfbp%M^oq0&yWyLodofjj^oyyKyQeo^ii)Lodofjj^o%0/)04&yyNFAy24/5y
>Pi^vfkdqeb?b^pqyWyLodofjj^oyyKyKbborCfob_i^ab%16+3)2-+1&yyNFAy243.y

eLodofjj^oyKyFkkhbbmboDovpeh^%21+.)35+1&yyWyLodofjj^oyyNFAy24//y

CQerkabo?irccyKyAlo^p%12+2)31&yyWyLodofjj^oyyNFAy24//y
>Qbpqfkd^kBkbjv$pPqobkdqeyKyO^e^rol%4.+2)0-+1&yyWyQerkabo?irccyyNFAy24/0y
>Pb^o`efkdcloqebIlpqP^q`ebiyKyO^e^rol%4.+2)0-+1&yyWyQerkabo?irccyyNFAy24//y

ELodofjj^oyRy3615yyNFAy.1023y

CQfofpc^iDi^abpyKyQ^hbqebWbmmbifk%2-+6).0+6&yyWyArolq^oyyNFAy.1023y
ORkabo`fqvyKyOrkqlqebRkabo`fqvyyWyQfofpc^iDi^abpyyNFAy.1023y
>QebMltboqlAbpqolv+++yKy?o^dlo?illacfpq%23+.)6/+.&yyNFAy.1023yyWyRkabo`fqvy

OO^dbcfob@e^pjyKyRpbqebarkdblkcfkaboqlnrbrbcloO^dbcfob@e^pjyyNFAy24/6yyFy

QPb^o`efkdcloqebIlpqP^q`ebiyKyCfkaJ^roDofjqlqbj)ebfpaltkpq^fo)q^hbqebiltbom^qeqlvlroofdeq_bclobdlfkdrmpq^foyyNFAy24//y
>ObqrokfkdqebIlpqP^q`ebiyKyJ^roDofjqlqbjyyNFAy24/1y
@Pi^vfkdqeb?b^pqyKyHfiiQ^o^d^j^kqebErkdboboyyNFAy243.y
@EfaabkBkbjfbp%M^oq0&yKyHfii?^ww^i^k%ebfplkqebrmmbocilloqebob$p^m^qebpmb`f^iivqlefj&^kaGbodlpeqebFkslhboyyNFAy24/5y
@QebMltboqlAbpqolv+++yKy?lqe_llhptfiiaolmlcPb^ofkd?i^abT^oil`hp^kaPb^ofkd?i^ab@riqfpqyyNFAy.1023y
@Qbpqfkd^kBkbjv$pPqobkdqeyKyHfii5O^dbcfobQolddp^ka5O^dbcfobPe^j^k)vlrpelria`ljmibqbqefp^rqlj^qf`iiv^pvlrorkqeolrdeqebfkpq^k`byyNFAy24/0y

ORkabo`fqvyKyBufq_^`hqlRkabo`fqv%23+.)6/+.&yyNFAy24/6yyFyyWyRkabo`fqvy

QQebMltboqlAbpqolv+++yKy?o^dlo?illacfpq%23+.)6/+.&yyNFAy.1023yyWyRkabo`fqvy

ELodofjj^oyRy3615yyNFAy24/6y

QPi^vfkdqeb?b^pqyWyLodofjj^oyyKyKbborCfob_i^ab%16+3)2-+1&yyNFAy243.y
QEfaabkBkbjfbp%M^oq0&yWyLodofjj^oyyKyQeo^ii)Lodofjj^o%0/)04&yyNFAy24/5y
>EfaabkBkbjfbp%M^oq1&yWyLodofjj^oyyKyQeo^ii)Lodofjj^o%0/)04&yyNFAy24/6y
QEfaabkBkbjfbp%M^oq1&yWyLodofjj^oyyKyKbborCfob_i^ab%16+3)2-+1&yyNFAy24/6y
>EfaabkBkbjfbp%M^oq2&yKyKbborCfob_i^ab%16+3)2-+1&yyNFAy240-yyWyLodofjj^oy
QEfaabkBkbjfbp%M^oq2&yKyQeo^ii)Lodofjj^o%0/)04&yyNFAy240-yyWyLodofjj^oy

CQerkabo?irccyKyAlo^p%12+2)31&yyNFAy24/1yyWyLodofjj^oy
QObqrokfkdqebIlpqP^q`ebiyKyO^e^rol%4-+/)/6+2&yyWyQerkabo?irccyyNFAy24/1y
QQbpqfkd^kBkbjv$pPqobkdqeyKyO^e^rol%4.+2)0-+1&yyWyQerkabo?irccyyNFAy24/0y

KDrfab@ljmibqb+@lkqfkrbQlQebT^fifkd@^sbokp%.2*/.&yKyQf`hql`lkqfkrbqlQebT^fifkd@^sbokp%.2*/.&drfab*Riqfj^qbTlTDrfab+`ljy

]]
end)
