
DugisGuideViewer:RegisterGuide("The Wailing Caverns (15-21)", "Shadowfang Keep (18-22)", "Horde", "I", function()
return [[
AAA

KIbsbi.2ObnrfobayKyVlrtfiikbbaql_b^qib^pq4-"qlibsbi.2ql_b^_ibqlmf`hrmqebnrbpqpfkqefpdrfabyyNFAy536yyMIy.2y

OQeb@olppol^apyKyQo^sbiqlqeb@olppol^ap%2.)/5+3&yyNFAy536yyWyQeb?^oobkpy
>O^mqloQefbsbpyKyD^wold%2.+6)0-+0&yyNFAy536yyWyQeb?^oobkpy
>QebClodlqqbkMllipyKyQlkd^Orkbqlqbj%2/+/)0.+6&yyNFAy54-yyWyQeb?^oobkpy
>Te^ocj^pqboAfwwvtfdyKy>mlqeb`^ovEbi_ofj%2.+2)0-+/&yyNFAy.16/yyWyQeb?^oobkpy
>Crkd^iPmlobpyKy>mlqeb`^ovEbi_ofj%2.+2)0-+/&yyNFAy515yyWyQeb?^oobkpy

@Crkd^iPmlobpyKyD^qebo1XCrkd^iPmlobpZ%12)//&yyNFAy515yyWyQeb?^oobkpy
@QebClodlqqbkMllipyKyBumilobqebt^qboplcqebClodlqqbkMllip%12)//+2&ptfjqlqeb_r__ibfkqebjfaaiblcqebmlliyyNFAy54-yyWyQeb?^oobkpy

QQebClodlqqbkMllipyKyQlkd^Orkbqlqbj%2/+/)0.+6&yyNFAy54-yyWyQeb?^oobkpy
>QebPq^dk^kqL^pfpyKyQlkd^Orkbqlqbj%2/+/)0.+6&yyNFAy544yyWyQeb?^oobkpy
QCrkd^iPmlobpyKy>mlqeb`^ovEbi_ofj%2.+2)0-+/&yyNFAy515yyWyQeb?^oobkpy
>Ilpqfk?^qqibyKyJ^khofh%2/)0.+3&yyNFAy16/.yyWyQeb?^oobkpy

OO^q`ebqyKyOrkqlO^q`ebq%3/+3)04+2&yyNFAy532yyWyQeb?^oobkpy
>O^mqloElokpyKyJb_lhJfwwvofu%3/+1)04+3&yyNFAy532yyWyQeb?^oobkpy
QTe^ocj^pqboAfwwvtfdyKyTe^ocj^pqboAfwwvtfd%30+0)05+1&yyNFAy.16/yyWyQeb?^oobkpy
eO^q`ebqyKyFkkhbbmboTfibv%3/)06+1&yyNFAy55-yyWyQeb?^oobkpy

@QebPq^dk^kqL^pfpyKyDlqlqebcfpprob^qqeb_lqqljlcqebi^hb^qqebPq^dk^kqL^pfp%22+3)1/+4&yyNFAy544yyWyQeb?^oobkpy
@O^mqloQefbsbpyKyHfiiqebO^mqlop^`olppqeb?^oobkpclo./XO^mqloEb^apZ%14)1/&)%2-)21&)%2/+3)13+.&yyNFAy536yyWyQeb?^oobkpy
@O^mqloElokpyKyD^qebo2XFkq^`qO^mqloElokpZcoljPrkp`^ibP`vqeb`i^tp%2/+/3)13+2&yyNFAy532yyWyQeb?^oobkpy
@Ilpqfk?^qqibyKyJ^khofh$pTfcb`^k_bclrkaplrqelcqeb_ofadb)fk^erqkloqelcqebol^a%16+0)2-+1&yyNFAy16/.yyWyQeb?^oobkpy

EO^`ebqyRy3615yyNFAy55-y
QO^mqloElokpyKyJb_lhJfwwvofu%3/+1)04+3&yyNFAy532yyWyQeb?^oobkpy
>Pj^oqAofkhpyKyJb_lhJfwwvofu%3/+1)04+3&yyNFAy.16.yyWyQeb?^oobkpy
cO^`ebqyKy?o^dlh%30+.)04+/&yyNFAy55-yyWyQeb?^oobkpy
CQeb@olppol^apyKy?o^dlh%30+.)04+/&yyNFAy55-yyWyQeb?^oobkpy

QO^mqloQefbsbpyKyD^wold%2.+6)0-+0&yyNFAy536yyWyQeb?^oobkpy
QIlpqfk?^qqibyKyJ^khofh%2/)0.+3&yyNFAy16/.yyWyQeb?^oobkpy
QQebPq^dk^kqL^pfpyKyQlkd^Orkbqlqbj%2/+/)0.+6&yyNFAy544yyWyQeb?^oobkpy
>>iqboba?bfkdpyKyQlkd^Orkbqlqbj%2/+/)0.+6&yyNFAy55-yyWyQeb?^oobkpy

K@ifj_RmQebEfiiEbob++yKyDlql%14)01+4&^kaqf`hqefppqbmyyNFAy.154yyWyQeb?^oobkpy
KOrkPqo^fdeqQlQefpPmlq++yKyOrkqlqebollclcqebT^fifkd@^sbok%13+-5)02+.0&^kaqf`hqefppqbmyyNFAy.154yyWyQeb?^oobkpy
KAolmqlqeb$klpb8^kabkqbo`^sbqlvlroibcqyKy%12+60)03+/0&^kaqf`hqefppqbmyyNFAy.154yyWyQeb?^oobkpy
>Absf^qbBo^af`^qflkyKyB_or%12+63)02+42&yyNFAy.154yyWyQeb?^oobkpy
>Absf^qbEfabpyKyK^im^h%12+63)02+42&yyNFAy.153yyWyQeb?^oobkpy
@>iqboba?bfkdpyKyDlqlQebIrpet^qboL^pfp)plrqetbpqlc@olppol^ap%13+6)06+4&^kahfiiqebL^pfpPk^mg^tpcloqebfoPebiipyyNFAy55-yyWyQeb?^oobkpy

Q>iqboba?bfkdpyKyQlkd^Orkbqlqbj%2/+/)0.+6&yyNFAy55-yyWyQeb?^oobkpy
>E^jrriOrkbqlqbjyKyQlkd^Orkbqlqbj%2/+/)0.+6&yyNFAy.156yyWyQeb?^oobkpy
>Jro^OrkbqlqbjyKyQlkd^Orkbqlqbj%2/+/)0.+6&yyNFAy00-.yyWyQeb?^oobkpy
>>mlqeb`^ovW^j^eyKy>mlqeb`^ovEbi_ofj%2.+2)0-+/&yyNFAy520yyWyQeb?^oobkpy

CQerkabo?irccyOyQ^robkyyKyAbso^h%2.+2)0-+0&yyNFAy63/yyWyQeb?^oobkpy
O@^jmQ^ro^glyOyLo`)Qolii)Rkab^a)?illaBicyyKyOrkql@^jmQ^ro^gl%11+3)26+/&yyNFAy63/yyWyQeb?^oobkpy
c@^jmQ^ro^glyOyLo`)Qolii)Rkab^a)?illaBicyyKyLjrp^Qerkaboelok%11+2)26+.&yyNFAy63/yyWyQeb?^oobkpy

OQerkabo?irccyOyLo`)Qolii)Rkab^a)?illaBicyyKyQ^hbqebol^atbpqfkqlJridlob)qebkkloqe^q?illaellcSfii^db%0/)34&yyWyQerkabo?irccyyNFAy63/y
Q>mlqeb`^ovW^j^eyWyQerkabo?irccyyKy>mlqeb`^ovW^j^e)`^sb_biltPmfofqOfpb%//+6)/-+6&yyNFAy520y
>Pbombkq_illjyWyQerkabo?irccyyKy>mlqeb`^ovW^j^e%//+6)/-+6&yyNFAy63/y
QE^jrriOrkbqlqbjyKy>o`eAorfaE^jrriOrkbqlqbj%45+2)/5+2&yyNFAy.156yyWyQerkabo?irccy
>K^o^Tfiaj^kbyKy>o`eAorfaE^jrriOrkbqlqbj%45+2)/5+2&yyNFAy.16-yyWyQerkabo?irccy
QK^o^Tfiaj^kbyKyK^o^Tfiaj^kb%42+5)0.+2&yyNFAy.16-yyWyQerkabo?irccy
>Ib^aboplcqebC^kdyKyK^o^Tfiaj^kb%42+5)0.+2&yyNFAy6.1yyWyQerkabo?irccy
KQo^fkvlrophfiipyKyAlk$qclodbqqlqo^fk^iivlrophfiipqlj^uo^khyyNFAy.1023y

OQebT^fifkd@^sbokpyKyRpbqebArkdblkCfkaboqlnrbrbcloT^fifkd@^sbok)_b^qib^pqibsbi.5fpob`ljjbkabayyWyQerkabo?irccyyNFAy6.1yyFy

HIloa@l_o^ekyKyHfiiIloa@l_o^ek^kadbqXDbjlc@l_o^ekZyyIy6405yyNFAy6.1y
HI^av>k^`lkao^yKyHfiiI^av>k^`lkao^^kadbqXDbjlc>k^`lkao^ZyyIy6406yyNFAy6.1y
HIloaMevq^pyKyCliiltqebdobbkifkbfkqebarkdblkj^mqlcfka^kaHfiiIloaMevq^p^kadbqXDbjlcMvqe^pZyyIy641-yyNFAy6.1y
@Ib^aboplcqebC^kdyKyHfiiIloaPbombkqfp^kadbqXDbjlcPbombkqfpZobcboqldobbkifkblkqebT^fifkd@^sbokparkdblkj^mlkeltqldbqqlIloaPbombkqfpyyNFAy6.1y
@Pj^oqAofkhpyKy@liib`q3uXT^fifkdBppbk`bpZcoljqebLlwbpfkT^fifkd@^sbokpyyNFAy.16.y
@Pbombkq_illjyKy@liib`q.-uXPbombkq_illjZcoljqebdobbkmi^kqpfkpfabT^fifkd@^sbokp)qebob^ob^iplpljbgrpqlrqpfablcqebfkpq^k`byyNFAy63/y
@Absf^qbBo^af`^qflkyKyHfiiqebobnrfobaAbsf^qbp^iiclrkafkT^fifkd@^sbokp)vlrpelriacfkfpeqefp^rqlj^qf`^iivfcvlr`ljmibqbqebfkpq^k`byyNFAy.154y
KPrjjlk^kahfiiJrq^krpyKyFcvlrhfiiba^iiclroib^aboplcqebc^kd)vlr`^kq^ihqlqebQ^robkAorfa_vqebbkqo^k`blcT^fifkd@^sbokpql_bdfkqebbsbkqcloqebcfk^i_lppJrq^krpQebAbslroboyyNFAy365.yyIy.-11.y

>QebDiltfkdPe^oayKyIllqqebdiltfkdpe^oacoljqebcfk^iJroil`_lppql^``bmqqefpnrbpqyyRy.-11.yyNFAy365.y

OQerkabo?irccyKyBufq_^`hqlQerkabo?ircc%42+5)0.+2&yyFyyWyQerkabo?irccy

QIb^aboplcqebC^kdyKyK^o^Tfiaj^kb%42+5)0.+2&yyNFAy6.1yyWyQerkabo?irccy
QPbombkq_illjyWyQerkabo?irccyyKy>mlqeb`^ovW^j^e%//+6)/-+6&yyNFAy63/y

EO^q`ebqyRy3615yyNFAy0036y
KQ^ihqlPmrqqbos^sibyKyQ^ihqlPmrqqbos^sib%30)04+/&yyNLyPmb^htfqepljblkbfkO^q`ebq^_lrqqebDiltfkdPe^oayyNFAy365.yyWyQeb?^oobkpy
QPj^oqAofkhpyKyJb_lhJfwwvofu%3/+1)04+3&yyNFAy.16.yyWyQeb?^oobkpy

CQeb@olppol^apyKy?o^dlh%30+.)04+/&yyNFAy0036yyWyQeb?^oobkpy

QQebDiltfkdPe^oayKyC^ii^P^dbtfka%15+/)0/+5&pebifsbplkqlmlcqebjlrkq^fkyyNFAy365.yyWyQeb?^oobkpy
>FkKfdeqj^obpyKyC^ii^P^dbtfka%15+/)0/+5&pebifsbplkqlmlcqebjlrkq^fkyyNFAy0036yyWyQeb?^oobkpy
QAbsf^qbBo^af`^qflkyKyB_or%12+63)02+42&yyNFAy.154yyWyQeb?^oobkpy
@Absf^qbEfabpyKy@liib`q/-uXAbsf^qbEfabpZcoljqebAbsf^qbPbombkqpfkpfabT^fifkd@^sbokp)qefpjfdeqq^hbvlr/orkplcT^fifkd@^sbokplovlr`^k`ljmibqbqefpplillrqpfabqebbkqo^k`bqlT^fifkd@^sbokp%13+/)0/+2&)%14+4)00&yyNFAy.153yyWyQeb?^oobkpy
QAbsf^qbEfabpyKyK^im^h%12+63)02+42&yyNFAy.153yyWyQeb?^oobkpy

CQerkabo?irccyKyAbso^h%2.+2)0-+0&yyWyQeb?^oobkpy
QFkKfdeqj^obpyKy>o`eAorfaE^jrriOrkbqlqbj%45+.)/6+2&yyNFAy0036yyWyQerkabo?irccy

KDrfab@ljmibqb+Qf`hQl@lkqfkrbQlPe^altc^kdHbbm%.5*//&yKyQf`hql`lkqfkrbqlPe^altc^kdHbbm%.5*//&*Riqfj^qbTlTDrfab+`ljy
]]
end)
