
DugisGuideViewer:RegisterGuide("Shadowfang Keep (18-22)", "Blackfathom Deeps (20-24)", "Horde", "I", function()
return [[
AAA

KIbsbi.5ObnrfobayKyVlrjrpq_b^qib^pqibsbi.5qlmf`hrmqebcliiltfkdnrbpqpyyNFAy.-.0yyMIy.5y
ORkabo`fqvyKyOrkqlqebRkabo`fqv%3/)4-&yyWyQfofpc^iDi^abpyyNFAy.-.0y
eRkabo`fqvyKyFkkhbbmboKloj^k%34+4)04+6&yyWyRkabo`fqvyyNFAy.-.0y
>Qeb?llhlcRoyKyHbbmbo?bi$ardro%21+3)21+/&yyWyRkabo`fqvyyNFAy.-.0y
OPbtbopyKyBufqqeolrdeqebpbtbop%13)11&yyWyRkabo`fqvyyNFAy.-.1y
OQfofpc^iDi^abpyKyBufqqeolrdeqebpbtbop%.3+2)/5+1&yyWyRkabo`fqvyyNFAy.-.1y

OQebPbmri`eboyKyQo^sbiqlPbmri`ebo%12+3)1/+3&yyWyPfisbomfkbClobpqyyNFAy.-.1y
cQebPbmri`eboyKyH^olpO^wlh%12+3)1/+3&yyWyPfisbomfkbClobpqyyNFAy.-.1y
>>ord^iJrpqAfbyKyA^i^oA^tktb^sbo%11+/)06+6&yyWyPfisbomfkbClobpqyyNFAy.-.1y
>Ab^qepq^ihbopfkPe^altc^kdyKyEfdeBub`rqloE^aob`%10+1)1-+6&yyWyPfisbomfkbClobpqyyNFAy.-65y
QJro^OrkbqlqbjyKyJro^Orkbqlqbj%1/+6)1/+-&yyNFAy00-.yyWyPfisbomfkbClobpqy

OPe^altc^kdHbbmyKyRpbqebarkdblkcfkaboqlnrbrbcloPe^altc^kdHbbm)ibsbi/-fpob`ljjbkabayyFy

QAb^qepq^ihbopfkPe^altc^kdyKyLkblcqebAb^qepq^ihbopfp_bfkdebiamofplkbo+Vlre^sbqlobib^pbefjpleb`^krkil`hqeballoql`lkqfkrbtfqeqebfkpq^k`b+Qebpb`lkaAb^qepq^ihbo`^k_bpbbkivfkdlkqeblqebopfablcqebdo^qbgrpq^pvlrbkqboqebfkpq^k`b+Vlrtfiie^sbqltlohvlrot^valtkqlefjqlcfkfpeqebnrbpq+yyWyPfisbomfkbClobpqyyNFAy.-65y
@Qeb?llhlcRoyKyQeb_llhfpfkqebolljtfqeCbkorp+Fqplkqebibcq^pvlrbkqboqebolljlkqeb_llhpebic)lk`bpljblkbdbqpqefp_llhfqafp^mmb^opclo^cbtpb`lkap+Fqtfiiobpm^tk+yyWyRkabo`fqvyyNFAy.-.0y
@>ord^iJrpqAfbyKyHfii>ord^i^ka_ofkdefpeb^a)ebfpqebcfk^i_lpp+obcboqlvlronrbpqqo^`hbo+yyWyPfisbomfkbClobpqyyNFAy.-.1y

OQebPbmri`eboyKyBufq_^`hqlqebQebPbmri`eboyyFy

Q>ord^iJrpqAfbyKyA^i^oA^tktb^sbo%11+/)06+6&yyWyPfisbomfkbClobpqyyNFAy.-.1y

ERkabo`fqvyRy3615y
QQeb?llhlcRoyKyHbbmbo?bi$ardro%21+3)21+/&yyWyRkabo`fqvyyNFAy.-.0y

CLodofjj^oyKyQ^hbqebWbmmbifkqlLodofjj^o%3-+4)25+5&yyWyQfofpc^iDi^abpy
CQeb@olppol^apyKyAlo^p%12+2)31&yyWyLodofjj^oy

KDrfab@ljmibqb+@lkqfkrbQl?i^`hc^qeljAbbmp%/-*/1&yKyQf`hql`lkqfkrbqlqebkbuqdrfab?i^`hc^qeljAbbmp%/-*/1&*Riqfj^qbTlTDrfab+`ljy
]]
end)
