
DugisGuideViewer:RegisterGuide("Blackfathom Deeps (20-24)", "Razorfen Kraul (23-28)", "Horde", "I", function()
return [[
AAA

KIbsbi/.ObnrfobayKyVlrjrpq_b^qib^pqibsbi/.qlmf`hrmqebcliiltfkdnrbpqpyyNFAy3230yyMIy/.y
O>pebks^ibyKyQo^sbiql>pebks^ib%35+0)51+1&yyWy>pebks^ibyyNFAy3230y
OPmifkqboqobbMlpqyKyQo^sbiqlPmifkqboqobbMlpq%40+/)3.+3&yyWy>pebks^ibyyNFAy3230y
cPmifkqboqobbMlpqyKySerido^%40+/)3.+3&yyWy>pebks^ibyyNFAy3230y
ePmifkqboqobbMlpqyKyFkkhbbmboH^vifpq%41)3-+3&yyWy>pebks^ibyyNFAy3230y
OWlo^j$d^oLrqmlpqyKyQo^sbiqlWlo^j$d^oLrqmlpq%./+/)00+5&yyWy>pebks^ibyyNFAy3230y
cWlo^j$d^oLrqmlpqyKy>kaorh%./+/)00+5&yyWy>pebks^ibyyNFAy3230y
>>jlkdpqqebOrfkpyKyGb$kbrP^k`ob^%..+3)01+0&yyNFAy36/.yyWy>pebks^iby

O?i^`hc^qeljAbbmpyKyRpbqebarkdblkcfkaboqlwlkbfkql?i^`hc^qeljAbbmpyyNFAy323.yyFy

>?i^`hc^qeljSfii^fkvyKy>odbkqDr^oaQe^biofa)Fkpfab?i^`hc^qeljAbbmpobcboqlqebArkdblkJ^myyNFAy323.y
@>jlkdpqqebOrfkpyKyQebC^qelj`lobfprkabot^qboclrka^p^illq^_ibfqbj`^iibaC^qeljPqlkb+obcboqlqebArkdblkJ^myyNFAy36/.yyWy>pebks^iby
H?^olk>nr^kfpyKyHfii?^olk>nr^kfp^kaillqXPqo^kdbT^qboDil_bZyyIy.345/yyNFAy36//y
>?^olk>nr^kfpyKyXPqo^kdbT^qboDil_bZ)aolmmba_vqebcfk^i_lppfk?i^`hc^qeljAbbmpyyRy.345/yyNFAy36//y
@?i^`hc^qeljSfii^fkvyKyHfiiQtfifdeqIloaHbiofp^kaillqefpeb^ayyNFAy323.y
>>iibdf^k`bqlqebLiaDlapyKy@if`hlkqebXA^jmKlqbZAolmmba_v?i^`hc^qeljpQfabMofk`bppbp)ql^``bmqqebnrbpqyyRy.346-yyNFAy3231yyLy

OWlo^j$d^oLrqmlpqyKy>kaorh%..+3)01+0&yyWy>pebks^ibyyNFAy3231yyFy

Q>iibdf^k`bqlqebLiaDlapyKyGb$kbrP^k`ob^%..+3)01+0&yyNFAy3231yyWy>pebks^ibyyLy
Q?^olk>nr^kfpyKyGb$kbrP^k`ob^%..+3)01+0&yyNFAy36//y
Q>jlkdpqqebOrfkpyKyGb$kbrP^k`ob^%..+3)01+0&yyNFAy36/.yyWy>pebks^iby

CQerkabo?irccyKy>kaorh%./+/)00+5&yyWy>pebks^ibyyNFAy323.y
Q?i^`hc^qeljSfii^fkvyKy?^pe^k^Orkbqlqbj%4-+6)00+4&yyNFAy323.yyWyQerkabo?irccy

KDrfab@ljmibqb+@lkqfkrbQlO^wlocbkHo^ri%/0*/5&yKyQf`hql`lkqfkrbqlO^wlocbkHo^ri%/2*0-&*Riqfj^qbTlTDrfab+`ljy
]]
end)
