
DugisGuideViewer:RegisterGuide("|cfff0c502Class Quest:|r Shaman / Warlock (20+)", nil, "Horde", "I", function()
return [[
AAA

KIbsbi/-Obnrfobay@yT^oil`hyyKyQefpfp^Ibsbi/-nrbpqclokbtPrjjlkPr`r__rpphfiiyyNFAy.2-4yyMIy/-y
KIbsbi/-Obnrfobay@yPe^j^kyyKyQefpfp^Ibsbi/-nrbpqcloPe^j^kpqld^fkqebfoT^qboQlqbjpyyNFAy.20-yyMIy/-y
KPe^j^k^kaT^oil`hplkivyKyVlrtlk$q_b^_ibqlpbbqebdrfabrkibppvlr$ob^Pe^j^kloT^oil`hyy@yT^ooflo)Oldrb)M^i^afk)Erkqbo)Aorfa)Mofbpq)J^db)Ab^qeHkfdeqy

OLodofjj^oy@yT^oil`hyyKyQo^sbiqlLodofjj^o%15+/)12+3&yyWyLodofjj^oyyNFAy.2-4y

>AbslrobolcPlripy@yT^oil`hyyKyD^k$ori?illabvb%15+/)12+3&yyWyLodofjj^oyyNFAy.2-4y
QAbslrobolcPlripy@yT^oil`hyyKy@^wri%14+0)13+3&yyWyLodofjj^oyyNFAy.2-4y
>?ifka@^wriy@yT^oil`hyyKy@^wri%14+0)13+3&yyWyLodofjj^oyyNFAy.2-5y
Q?ifka@^wriy@yT^oil`hyyKyW^kh^g^%04+.)26+4&yyWyLodofjj^oyyNFAy.2-5y
>KbtplcAldo^ky@yT^oil`hyyKyW^kh^g^%04+.)26+4&yyWyLodofjj^oyyNFAy.2-6y
CQeb@olppol^apy@yT^oil`hyyKyAlo^p%12+0)31&yyWyLodofjj^oyyNFAy321.y
QKbtplcAldo^ky@yT^oil`hyyKyD^wold%2.+6)0-+0&yyNFAy.2-6yyWyQeb?^oobkpy
>KbtplcAldo^k%M^oq/&y@yT^oil`hyyKyD^wold%2.+6)0-+0&yyNFAy.2.-yyWyQeb?^oobkpy

C@^jmQ^ro^gly@yT^oil`hyyKyAbso^h%2.+2)0-+0&yyWyQeb?^oobkpyyNFAy.2..y
O@^jmQ^ro^gly@yPe^j^kyyKyQo^sbiql@^jmQ^ro^gl%12+3)26&yyWyQeb?^oobkpyyNFAy.20-y
e@^jmQ^ro^gly@yT^oil`hyyKyFkkhbbmbo?vri^%12+3)26&yyWyQeb?^oobkpyyNFAy.2..y
e@^jmQ^ro^gly@yPe^j^kyyKyFkkhbbmbo?vri^%12+3)26&yyWyQeb?^oobkpyyNFAy.20-y

QKbtplcAldo^k%M^oq/&y@yT^oil`hyyKyHbk$wfdi^%40+/)62+.&yyNFAy.2.-yyWyPqlkbq^ilkJlrkq^fkpy
>Hbk$wfdi^$pAo^rdeqy@yT^oil`hyyKyHbk$wfdi^%40+/)62+.&yyNFAy.2..yyWyPqlkbq^ilkJlrkq^fkpy

E@^jmQ^ro^gly@yT^oil`hyyRy3615yyNFAy.2.2y

QHbk$wfdi^$pAo^rdeqy@yT^oil`hyyKyDorkqIldj^o%40+/)62+.&yyNFAy.2..yyWyQeb?^oobkpy
>Aldo^k$p@^mqfsfqvy@yT^oil`hyyKyDorkqIldj^o%40+/)62+.&yyNFAy.2.2yyWyQeb?^oobkpy
QAldo^k$p@^mqfsfqvy@yT^oil`hyyKyDorkqAldo^k%10+0)14+6&yyNFAy.2.2yyWyQeb?^oobkpy
>Ilsb$pDfcqy@yT^oil`hyyKyDorkqAldo^k%10+0)14+6&yyNFAy.2./yyWyQeb?^oobkpy
CLodofjj^oy@yT^oil`hyyKyLjrp^Qerkaboelok%11+2)26+.&yyNFAy.2.0yyWyQeb?^oobkpy
QIlsb$pDfcqy@yT^oil`hyyKyD^k$ori?illabvb%15+/)12+3&yyWyLodofjj^oyyNFAy.2./y
>Qeb?fkafkdy@yT^oil`hyyKyD^k$ori?illabvb%15+/)12+3&yyWyLodofjj^oyyNFAy.2.0y
@Qeb?fkafkdy@yT^oil`hyyKyRpbXAldo^k$pMbka^kqZqlprjjlk^Pr``r_rp^kahfiifqyyRy33/3yyNFAy.2.0yyWyQeb?^oobkpy
QQeb?fkafkdy@yT^oil`hyyKyD^k$ori?illabvb%15+/)12+3&yyWyLodofjj^oyyNFAy.2.0y

CO^q`ebqy@yPe^j^kyyKyLjrp^Qerkaboelok%11+2)26+.&yyNFAy.20-yyWyQeb?^oobkpy
>@^iilcT^qbo%M^oq/&y@yPe^j^kyyKyFpibkT^qbopbbo%32+5)10+5&yyNFAy.20-yyWyQeb?^oobkpy
Q@^iilcT^qbo%M^oq/&y@yPe^j^kyyKy?ofkb%10+2)44+1&yyNFAy.20-yyWyQeb?^oobkpy
>@^iilcT^qbo%M^oq0&y@yPe^j^kyyKy?ofkb%10+2)44+1&yyNFAy.202yyWyQeb?^oobkpy
@@^iilcT^qbo%M^oq0&y@yPe^j^kyyKyRpbXBjmqv?oltkT^qbophfkZlkqebtbii%11)44&yyRy4433yyNFAy.202yyWyQeb?^oobkpy
Q@^iilcT^qbo%M^oq0&y@yPe^j^kyyKy?ofkb%10+2)44+1&yyNFAy.202yyWyQeb?^oobkpy
>@^iilcT^qbo%M^oq1&y@yPe^j^kyyKy?ofkb%10+2)44+1&yyNFAy.203yyWyQeb?^oobkpy

CLodofjj^oy@yPe^j^kyyKyLjrp^Qerkaboelok%11+2)26+.&yyNFAy160yyWyQeb?^oobkpy
CQfofpc^iDi^abpy@yPe^j^kyyKyQ^hbqebwbmmbifklrqpfabLodofjj^o%2-+5).0+4&qlQfofpc^iDi^abp%Rkabo`fqv&yyWyArolq^oyyNFAy160y
ORkabo`fqvy@yPe^j^kyyKyQo^sbiqlRkabo`fqv%32+5)0+/&yyWyRkabo`fqvyyNFAy160y
CQebPbmri`eboy@yPe^j^kyyKyJf`e^biD^oobqq%30+0)15+3&yyWyRkabo`fqvyyNFAy160y
>GlrokbvqlEfiip_o^aCllqefiipy@yPe^j^kyyKy>mlqeb`^ovObkcboobi%1/+6)1-+6&yyWyPfisbomfkbClobpqyyNFAy160y
OEfiip_o^aCllqefiipy@yPe^j^kyyKyOrkaltkqeolrdePfisbomfkbqebkb^pqqlEfiip_o^aCllqefiip%4.+0)5-+2&yyWyPfisbomfkbClobpqyyNFAy161y
>QfjbQlPqofhby@yPe^j^kyyKyAb^qepq^ihboIbpe^qqebPlrqemlfkqQltbo%/-+5)14+1&yyWyEfiip_o^aCllqefiipyyNFAy161y

OQ^oobkJfiiy@yPe^j^kyyKyOrkqlQ^oobkJfii%3/+0)/-+0&yyWyEfiip_o^aCllqefiipyyNFAy.201y
cQ^oobkJfiiy@yPe^j^kyyKyW^ofpb%3-+/).5+4&yyWyEfiip_o^aCllqefiipyyNFAy.201y
QQfjbQlPqofhby@yPe^j^kyyKyEfdeBub`rqloA^oqe^if^%3/+0)/-+0&yyWyEfiip_o^aCllqefiipyyNFAy161y
QGlrokbvqlEfiip_o^aCllqefiipy@yPe^j^kyyKy>mlqeb`^ovIvalk%3.+2).6+/&yyWyEfiip_o^aCllqefiipyyNFAy160y
@@^iilcT^qbo%M^oq1&y@yPe^j^kyyKyRpbXBjmqvObaT^qbophfkZlkqebtbii%3/)/-&yyWyEfiip_o^aCllqefiipyyRy4435yyNFAy.203y
E@^jmQ^ro^gly@yPe^j^kyyRy3615yyNFAy.201y

Q@^iilcT^qbo%M^oq1&y@yPe^j^kyyKy?ofkb%10+2)44+1&yyNFAy.203yyWyQeb?^oobkpy
>@^iilcT^qbo%M^oq2&y@yPe^j^kyyKy?ofkb%10+2)44+1&yyNFAy.201yyWyQeb?^oobkpy

CQeb@olppol^apy@yPe^j^kyyKy?o^dlh%30+.)04+/&yyWyQeb?^oobkpyyNFAy//-y
QObmloqqlH^ao^hyWyQeb?^oobkpyy@yPe^j^kyyKyH^ao^h%15+.)2+1&)^qqeb>pebks^ib_loaboyyWyQeb?^oobkpyyNFAy321/y
OPmifkqboqobbMlpqy@yPe^j^kyyKyCliiltqebol^akloqe)qebkb^pq%40)32&yyWy>pebks^ibyyNFAy.-54y
cPmifkqboqobbMlpqy@yPe^j^kyyKySerido^%40+/)3.+3&yyWy>pebks^ibyyNFAy.-54y
@@^iilcT^qbo%M^oq2&y@yPe^j^kyyKyRpbXBjmqv?irbT^qbophfkZ^qqebtbii%00)34&yyWy>pebks^ibyyRy4434yyNFAy.201y
E@^jmQ^ro^glyKyLoCiv_^`hyyRy3615yyNFAy.-54yy@yPe^j^ky
Q@^iilcT^qbo%M^oq2&y@yPe^j^kyyKy?ofkb%10+2)44+1&yyWyQeb?^oobkpyyNFAy.201y
>@^iilcT^qbo%M^oq3&y@yPe^j^kyyKy?ofkb%10+2)44+1&yyWyQeb?^oobkpyyNFAy//-y
CO^q`ebqy@yPe^j^kyyKyLjrp^Qerkaboelok%11+2)26+.&yyWyQeb?^oobkpyyNFAy30y
Q@^iilcT^qbo%M^oq3&y@yPe^j^kyyKyFpibkT^qbopbbo%32+5)10+5&yyWyQeb?^oobkpyyNFAy//-y
>@^iilcT^qbo%M^oq4&y@yPe^j^kyyKyFpibkT^qbopbbo%32+5)10+5&yyWyQeb?^oobkpyyNFAy30y
CLodofjj^oy@yPe^j^kyyKy?o^dlh%30+.)04+/&yyWyQeb?^oobkpyyNFAy.--y
CQfofpc^iDi^abpy@yPe^j^kyyKyQ^hbqebwbmmbifklrqpfabLodofjj^o%2-+5).0+4&qlQfofpc^iDi^abp%Rkabo`fqv&yyWyArolq^oyyNFAy.--y
CPbmri`eboy@yPe^j^kyyKyJf`e^biD^oobqq%30+2)15+4&yyWyRkabo`fqvyyNFAy.--y
@@^iilcT^qbo%M^oq4&y@yPe^j^kyyKyDlql%05)11&_vgrjmfkdm^pqqebqobbcolj_befkaqebPbmri`ebofkk)aofkhXT^qboP^mq^Z^kahfii@loormqJ^kfcbpq^qflklcT^qboqebkmf`hrmqebX@loormqJ^kfcbpq^qflk$p?o^`bopZ^karpbfqlkqeb_o^wfboyyWyPfisbomfkbClobpqyyNFAy30yyRy45./y
Q@^iilcT^qbo%M^oq4&y@yPe^j^kyyKy?o^wfbolcBsboclrkq%05+0)11+3&yyWyPfisbomfkbClobpqyyNFAy30y
>@^iilcT^qbo%M^oq5&y@yPe^j^kyyKy?o^wfbolcBsboclrkq%05+0)11+3&yyWyPfisbomfkbClobpqyyNFAy.--y
Q@^iilcT^qbo%M^oq5&y@yPe^j^kyyKyJfkloJ^kfcbpq^qflklcT^qbo%05+4)11+3&yyWyPfisbomfkbClobpqyyNFAy.--y
>@^iilcT^qbo%M^oq6&y@yPe^j^kyyKyJfkloJ^kfcbpq^qflklcT^qbo%05+4)11+3&yyWyPfisbomfkbClobpqyyNFAy63y
K>qof`hqldbq_^`hqlFpibk+++y@yPe^j^kyyKyFcvlroEb^oqefpaltk)hbbmptfjjfkdtbpqcoljebob%1+2)1/+4&rkqfivlrafblcc^qfdrb)^kavlrtfii^mmb^ofkQeb@olppol^apdo^sbv^oa+Q^hbqebpmfofqobpprob`q^kacivqlO^q`ebqyyWyPfisbomfkbClobpqyyNFAy63y
Q@^iilcT^qbo%M^oq6&y@yPe^j^kyyKyFpibkT^qbopbbo%32+5)10+5&yyWyQeb?^oobkpyyNFAy63y

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
