
DugisGuideViewer:RegisterGuide("Razorfen Kraul (23-28)", "Gnomeregan (24-29)", "Horde", "I", function()
return [[
AAA

KIbsbi/0ObnrfobayKyVlrjrpq_b^qib^pqibsbi/0qlmf`hrmqebcliiltfkdnrbpqpyyNFAy.-.0yyMIy/0y
ORkabo`fqvyKyOrkqlqebRkabo`fqv%3/)4-&yyWyQfofpc^iDi^abpyyNFAy..-6y
eRkabo`fqvyKyFkkhbbmboKloj^k%34+4)04+6&yyWyRkabo`fqvyyNFAy..-6y
>Dlfkd)Dlfkd)Dr^klyKyJ^pqbo>mlqeb`^ovC^o^kbii%16+4)36+5&yyWyRkabo`fqvyyNFAy..-6y

CLodofjj^oyKyQ^hbqebWbmmbifkqlLodofjj^o%3-+4)25+5&yyWyQfofpc^iDi^abpyyNFAy.//.y
CO^q`ebqyKyAlo^p%12+2)31&yyWyLodofjj^oyyNFAy.//.y
>?irbib^cQr_bopyKyJb_lhJfwwvofu%3/+1)04+3&yyWyQeb?^oobkpyyNFAy.//.y
KDo^_X@o^qbTfqeElibpZyKyDbqqebX@o^qbTfqeElibpZlkqebq^_ib%3/+0)04+4&yyIy255-yyWyQeb?^oobkpyyNFAy.//.y
KDo^_XPkrccibklpb@ljj^kaPqf`hZyKyDo^_XPkrccibklpb@ljj^kaPqf`hZ%3/+0)04+4&yyIy3351yyWyQeb?^oobkpyyNFAy.//.y
KDo^_XPkrccibklpbLtkbo$pJ^kr^iZyKyDo^_XPkrccibklpbLtkbo$pJ^kr^iZ%3/+0)04+4&yyIy2564yyWyQeb?^oobkpyyNFAy.//.y

CQerkabo?irccyKy?o^dlh%30+.)04+/&yyWyQeb?^oobkpyyNFAy..-/y
>>SbkdbcriC^qbyKy>riaPqlkbpmfob%03+6)26+1&yyWyQerkabo?irccyyNFAy..-/y

OO^wlocbkHo^riyKyRpbqebarkdblkcfkaboqlnrbrbcloO^wlocbkHo^riyyNFAy..-6yyFy

@Dlfkd)Dlfkd)Dr^klyKyQebdr^klaolmplccqebHo^ri?^qp)bifqbjl_pqe^qpm^tklkivfkqeb`^sbp^qqebc^otbpqpfablcqebfkpq^k`byyNFAy..-6y
@>SbkdbcriC^qbyKyHfiiO^wloci^kh%qebcfk^i_lpp&^kaillqefpeb^oqyyNFAy..-/y

KIllqXPj^iiP`oliiZyKyJ^hbprobqlillqXPj^iiP`oliiZcoljO^wloci^khyyIy16/-2yyNFAy.102/y
>TfiifuqebFjmloqboyKyCfkaTfiifuqebFjmloqbo^ka`ljmibqbqebbp`loqnrbpqyyNFAy..11y
@TfiifuqebFjmloqboyKyCliilt^kaMolqb`qTfiifuqebFjmloqboyyNFAy..11y
QTfiifuqebFjmloqboyKyTfiifuqebFjmloqboyyNFAy..11y

R@o^qbTfqeElibpyKyRpbX@o^qbTfqeElibpZqlprjjlkvlrodlmeboyyRy255-yyNFAy.//.y
@?irbib^cQr_bopyKyHbbmrpfkdvlroXPkrccibklpb@ljj^kaPqf`hZqlebimvlrcfkaqebQorccib)eb^aqlt^oapqeb^ob^tebobvlrclrkaTfiifuqebFjmloqboyyRy3351yyNFAy.//.y

OQerkabo?irccyKyQbibmloqlrqlcqebfkpq^k`b%03+6)26+1&yyWyQerkabo?irccyyNFAy.1020yyFy

Q>SbkdbcriC^qbyKy>riaPqlkbpmfob%03+6)26+1&yyWyQerkabo?irccyyNFAy..-/y

CO^q`ebqyKyQ^i%13+5)2-+/&yyWyQerkabo?irccyyNFAy.1020y
Q?irbib^cQr_bopyKyJb_lhJfwwvofu%3/+1)04+3&yyWyQeb?^oobkpyyNFAy.//.y

ERkabo`fqvyRy3615yyNFAy.1020y
QDlfkd)Dlfkd)Dr^klyKyJ^pqbo>mlqeb`^ovC^o^kbii%16+4)36+5&yyWyRkabo`fqvyyNFAy..-6y
>Eb^oqplcWb^iyKyJ^pqbo>mlqeb`^ovC^o^kbii%16+4)36+5&yyWyRkabo`fqvyyNFAy...0y

KDrfab@ljmibqb+@lkqfkrbQlDkljbobd^k%/1*/6&yKyQf`hql`lkqfkrbqlDkljbobd^k%/1*/6&*Riqfj^qbTlTDrfab+`ljy
]]
end)
