DugisGuideViewer:RegisterGuide("Gnomeregan (24-29)", "Scarlet Monestary Graveyard / Library (27-33)", "Horde", "I", function()
return [[
AAA

KIbsbi/2ObnrfobayKyVlrjrpq_b^qib^pqibsbi/2qlmf`hrmqebcliiltfkdnrbpqpyyNFAy/51.yyMIy/2y

OLodofjj^oyKyQo^sbiqlLodofjj^o%42+1)/1+5&yyWyLodofjj^oyyNFAy/51.y
>OfdT^opyKyKldd%42+1)/1+5&yyWyLodofjj^oyyNFAy/51.y
>@efbcBkdfkbboP`llqvyKyPlsfh%42+3)/2+/&yyWyLodofjj^oyyNFAy/51/y

CO^q`ebqyKyAlo^p%12+.)30+6&yyWyLodofjj^oyyNFAy/51/y
_?llqv?^vyKyQo^sbiql?llqv?^v%30+4)05+3&yyWyQeb?^oobkpyyNFAy/51/y

Q@efbcBkdfkbboP`llqvyKyP`llqv%/4+3)44+2&yyWyPqo^kdibqelokS^ibyyNFAy/51/y
>Dkljbo*dlllllkbyKyP`llqv%/4+3)44+2&yyWyPqo^kdibqelokS^ibyyNFAy/510y
QDkljbo*dlllllkbyKyP`llqv%/4+3)44+2&yyWyPqo^kdibqelokS^ibyyNFAy/510y

ODkljbobd^kyKyAlk$qrpbP`llqvMloq^iRpbarkdblkcfkaboqlqbibmloqfkqlqebfkpq^k`byyNFAy/6-1yyFy

>>CfkbJbppyKyHbokl_bb)FkqebAlojfqlov_vqeb@ib^kOlljyyNFAy/6-1y
@>CfkbJbppyKy?ofkdHbokl_bb)qlqebcolkqbkqo^k`blcqebarkdblk)ebtfiicliiltvlryyNFAy/6-1y

>Dofjb*Bk`orpqbaOfkdyKyXDofjb*Bk`orpqbaOfkdZaolmmbacoljDkljbobd^kjl_p)qefptfiiobnrfobibsbi/5ql^``bmqlqebotfpbvlr`^kphfmhbbmqefpfkvlrofksbkqlov^ka^``bmqfqi^qboyyRy60/3yyNFAy/612y
QDofjb*Bk`orpqbaOfkdyKyQebPm^ohibj^qf`2/--)Fkqeb@ib^kWlkbyyNFAy/612y
>ObqroklcqebOfkdyKyQebPm^ohibj^qf`2/--)Fkqeb@ib^kWlkbyyNFAy/616y

HJbhdfkbboQeboj^mirddyKyHfiiJbhdfkbboQeboj^mirdd^ka`liib`qXQeboj^mirdd$pP^cb@lj_fk^qflkZyyIy6/66yyNFAy/51.y
@OfdT^opyKyLk`bvlre^sbXQeboj^mirdd$pP^cb@lj_fk^qflkZvlr`^kkltlmbkqebp^cbfkQeboj^mirddolljqldbqXOfd?irbmofkqpZyyWyLodofjj^oyyNFAy/51.y

O?llqv?^vyKyBufqlrqlcqebfkpq^k`b_^`hql?llqv?^v%12+6)16+0&yyWyPqo^kdibqelokS^ibyyNFAy/62-yyFy

Q>CfkbJbppyWyPqo^kdibqelokS^ibyyKyP`llqv%/4+3)44+2&yyNFAy/6-1yyNFAy/62-y

_O^q`ebqyKyQo^sbiqlO^q`ebq%42+1)/1+5&yyWyPqo^kdibqelokS^ibyyNFAy/62-y
CLodofjj^oyKy?o^dlh%30+.)04+/&yyWyQeb?^oobkpyyNFAy/62-y

QOfdT^opyKyKldd%42+1)/1+5&yyWyLodofjj^oyyNFAy/51.y
QObqroklcqebOfkdyWyLodofjj^oyyKyKldd%42+1)/1+5&yyNFAy/616y
>Kldd$pOfkdObalyWyLodofjj^oyyKyKldd%42+1)/1+5&yyNFAy/62-y
@Kldd$pOfkdObalyWyLodofjj^oyyKy?ofkd^XPfisbo?^oZ^kaXJlpp>d^qbZvlr`^k_rvqebjcoljqeb>r`qflkElrpbfcfqpklqqllbumbkpfsb)Kldd%42+1)/1+5&yyNFAy/62-y
QKldd$pOfkdObalyWyLodofjj^oyyKyKldd%42+1)/1+5&yyNFAy/62-y

KDrfab@ljmibqb+@lkqfkrbQlP`^oibqJlkbpq^ov%/4*00&yKyQf`hql`lkqfkrbqlP`^oibqJlkbpq^ovDo^sbv^oa,If_o^ov%/4*00&*Riqfj^qbTlTDrfab+`ljy

]]
end)

