DugisGuideViewer:RegisterGuide("Scarlet Monestary Graveyard / Library (27-33)", "Razorfen Downs (33-38)", "Horde", "I", function()
return [[
AAA

KIbsbi/4ObnrfobayKyVlrjrpq_b^qib^pqibsbi/4qlmf`hrmqebcliiltfkdnrbpqpyyNFAy.-2.yyMIy/4y

ORkabo`fqvyKyQo^sbiqlRkabo`fqv%34+4)04+6&yyWyRkabo`fqvyyNFAy.-2.y
eRkabo`fqvyKyFkkhbbmboKloj^k%34+4)04+6&yyWyRkabo`fqvyyNFAy.-2.y
KNrbrbcloP`^oibqJlkbpq^ovDo^sbv^oaRkqfiIbsbi0.yKy>qibsbi/4vlr`^knrbrbcloP`^oibqJlkbpq^ovDo^sbv^oayyNFAy.-2.yyFy
>Sloobi$pObsbkdbyKySloobiPbkdrqw)ebfpqebrkab^afkpfabqebfkpq^k`b_bfkdqloqroba)vlrtlk$qjfppefjyyNFAy.-2.y

CQebPbmri`eboyKyCivqlQebPbmri`ebo^cqbovlr`ljmibqbP`^oibqJlkbpq^ovDo^sbv^oa)Jf`e^biD^oobqq%30+0)15+3&yyWyRkabo`fqvyyNFAy.-2.y
OEfiip_o^aCllqefiipyKyQo^sbiqlEfiip_o^aCllqefiip%.2)13&yyWyEfiip_o^aCllqefiipyyNFAy.-2.y
@Sloobi$pObsbkdbyKyHfiiK^k`vSfpe^p%0.+1)0/+-&+Pebfp^00bifqb+Pebfptfqe^klqeboibsbi00bifqb)grpqt^fqcloeboql`ljblrqlkqlqebal`h^ilkb_bclobbkd^dfkdebo+yyNFAy.-2.yyWy>iqbo^`Jlrkq^fkpy
OQ^oobkJfiiyKyQo^sbiqlQ^oobkJfii%3-+.).5+3&yyWyEfiip_o^aCllqefiipyyNFAy.-2.y
cQ^oobkJfiiyKyW^ofpb%3-+.).5+3&yyWyEfiip_o^aCllqefiipyyNFAy.-2.y
QSloobi$pObsbkdbyKyJlkfh^Pbkdrqw%3/+4).6&yyWyEfiip_o^aCllqefiipyyNFAy.-2.y

KIbsbi0-ObnrfobayKyQebcliiltfkdnrbpqobnrfobpibsbi0-qlmf`hrmyyNFAy.1022yyMIy0-y
ERkabo`fqvyRy3615yyNFAy.1022y

>FkqlQebP`^oibqJlk^pqbovyKy?o^dlo?illacfpq%23+.)6/+.&yyNFAy.1022yyWyRkabo`fqvy
>GlrokbvqlqebJ^opey@yJ^dbyyKyVlr`^kmf`hrmqefpnrbpqcolj^kvJ^dbQo^fkbo)%52+2).1+.&yyNFAy.614yyWyRkabo`fqvy

CLodofjj^oyKyQ^hbqebWbmmbifkqlLodofjj^o%3-+4)25+5&yyNFAy.-16yyWyQfofpc^iDi^abpyyOyQolii)Lo`)Q^robk)?illaBicy
CQerkabo?irccyKyAlo^p%12+2)31&yyNFAy.-16yyWyLodofjj^oyyOyQolii)Lo`)Q^robk)?illaBicy
>@ljmbkafrjlcqebC^iibkyKyP^dbQorqepbbhbo%02)15&yyNFAy.-16yyWyQerkabo?irccyyOyQolii)Lo`)Q^robk)?illaBicy

C@^jmQ^ro^gly@yJ^dbyyOyRkab^ayyKyAlo^p%12+2)31&yyWyLodofjj^oyyNFAy.614y
C@^jmQ^ro^gly@yJ^dbyyOyQolii)Lo`)Q^robk)?illaBicyyKyQ^i%13+5)2-+/&yyWyQerkabo?irccyyNFAy.614y

OArpqt^iiltJ^opey@yJ^dbyyKyQo^sbiqlArpqt^iiltJ^ope%0-)14&yyWyArpqt^iiltJ^opeyyNFAy.614y
O?o^`hbkt^iiSfii^dby@yJ^dbyyKyCliiltqebol^aql?o^`hbkt^iiSfii^db%02+3)0.+6&yyWyArpqt^iiltJ^opeyyNFAy.614y
c?o^`hbkt^iiSfii^dby@yJ^dbyyKyPe^oaf%02+3)0.+6&yyWyArpqt^iiltJ^opeyyNFAy.614y
e?o^`hbkt^iiSfii^dby@yJ^dbyyKyIfqqibIldlh%03+3)0/&yyWyArpqt^iiltJ^opeyyNFAy.614y
QGlrokbvqlqebJ^opey@yJ^dbyyKyPqf`hqlqebol^a^kacfkaQ^_bqe^%13)24+.&yyNFAy.614yyWyArpqt^iiltJ^opey
>EfaabkPb`obqpy@yJ^dbyyKyQ^_bqe^%13)24+.&yyNFAy.616yyWyArpqt^iiltJ^opey
OQeb?^oobkpy@yJ^dbyyKyQo^sbiqlQeb?^oobkp%16+1)45+2&yyWyQeb?^oobkpy

OQelrp^kaKbbaibpy@yJ^dbyyKyQo^sbiqlQelrp^kaKbbaibp%0/)02&yyWyQelrp^kaKbbaibpyyNFAy.62-y
OCobbtfkaLrqmlpqy@yJ^dbyyKyQo^sbiqlCobbtfkaLrqmlpq%1.)15&yyWyQelrp^kaKbbaibpyyNFAy.62-y
cCobbtfkaLrqmlpqy@yJ^dbyyKyKvpb%12+.)16+.&yyWyQelrp^kaKbbaibpyyNFAy.62-y
OQebPefjjbofkdCi^qpy@yJ^dbyyKyQo^sbiqlQebPefjjbofkdCi^qp%4-)25&yyWyQelrp^kaKbbaibpyyNFAy.62-y
QEfaabkPb`obqpy@yJ^dbyyKyJ^drpQfoqe%45+0)42+5&yyNFAy.616yyWyQelrp^kaKbbaibpy
>DbqqebP`llmy@yJ^dbyyKyJ^drpQfoqe%45+0)42+5&yyNFAy.62-yyWyQelrp^kaKbbaibpy
K?b`hlkMir`hvy@yJ^dbyyKyCfkaMir`hv%46+3)42+4&^kaqvmb,_b`hlkqlefj^kaq^ihqlefjtebkebfpfkerj^kclojyyNLyPb`obqmeo^pbclrkayyNFAy.62-yyWyQelrp^kaKbbaibpy
QDbqqebP`llmy@yJ^dbyyKyJ^drpQfoqe%45+0)42+5&yyNFAy.62-yyWyQelrp^kaKbbaibpy
>Ofqr^iplcMltboy@yJ^dbyyKyJ^drpQfoqe%45+0)42+5&yyNFAy.62.yyWyQelrp^kaKbbaibpy

E?o^`hbkt^iiSfii^dby@yJ^dbyyRy3615y

OP`^oibqJlk^pqbovIf_o^ovyKyNrbrbcloP`^oibqJlk^pqbovIf_o^ov)^qib^pqibsbi0.fpob`ljjbkabayyNFAy.62.yyFy
HElrkaj^pqboIlhpbvyKyHfiiElrkaj^pqboIlhpbvfkqebIf_o^ov)ebfkpfabqebpj^ii^ob^_vqeb`lroqv^oayyNLyElrkaj^pqboIlhpbvpi^fkyyNFAy.1022y
@@ljmbkafrjlcqebC^iibkyKyVlrtfiicfkaqeb_llh)ofdeq^pvlrbkqboqeb>qebk^brj+Fq$pi^pq`lokbo_bclobqebe^iit^vib^appqo^fdeqfkqlqebolljtfqeqeb_lpp+%@fo`ri^oolljlkqebj^m&+>_i^`h_llhpqf`hfkdlrqlc^_llh`^pbyyNFAy.-16yyWyQerkabo?irccyyOyQolii)Lo`)Q^robk)?illaBicy
@Ofqr^iplcMltboy@yJ^dbyyKyQeb_llhfpfkqebP`^oibqJlk^pqbovIf_o^ov+Fq$pe^kdfkdlcclc^_llhpebiclk^peloqt^iifkqebi^pqe^iit^v_bclobqebcfk^i_lppyyNFAy.62.y
@Eb^oqplcWb^iyKy@liib`q/-uXEb^oqlcWb^iZaolmmba_vP`^oibqKM@fkpfabP`^oibqJlkbpq^ov)qefp`^k_b`ljmibqbafk^kvfkpq^k`byyWyRkabo`fqvyyNFAy...0y
H>o`^kfpqAl^kyKyHfii>o`^kfpqAl^k^kaillqXQebP`^oibqHbvZyyIy4.13y

OArpqt^iiltJ^opey@yJ^dbyyKyBufq_^`hqlArpqt^iiltJ^ope%13)24+.&yyNFAy.62/yyWyArpqt^iiltJ^opeyyFy
OQerkabo?irccyKyBufq_^`hqlQerkabo?irccyyWyQerkabo?irccyyOyQolii)Lo`)Q^robk)?illaBicyy@yT^ooflo)T^oil`h)M^i^afk)Mofbpq)Pe^j^k)Erkqbo)Oldrb)Ab^qeHkfdeq)AorfayyFy
ORkabo`fqvyKyBufq_^`hqlRkabo`fqv%34+4)04+6&yyWyRkabo`fqvyyOyRkab^ayy@yT^ooflo)T^oil`h)M^i^afk)Mofbpq)Pe^j^k)Erkqbo)Oldrb)Ab^qeHkfdeq)AorfayyFy

QOfqr^iplcMltboy@yJ^dbyyKyQ^_bqe^%13)24+.&yyNFAy.616yyWyArpqt^iiltJ^opey
>J^db$pT^kay@yJ^dbyyKyQ^_bqe^%13)24+.&yyNFAy.62/yyWyArpqt^iiltJ^opey
QJ^db$pT^kay@yJ^dbyyKyQ^_bqe^%13)24+.&yyNFAy.62/yyWyArpqt^iiltJ^opey

E?o^`hbkt^iiSfii^dby@yJ^dbyyRy3615y

CQerkabo?irccyKyPe^oaf%02+3)0.+6&yyWyArpqt^iiltJ^opeyyOyQolii)?illaBicyy@yJ^dby
Q@ljmbkafrjlcqebC^iibkyKyP^dbQorqepbbhbo%02)15&yyNFAy.-16yyWyQerkabo?irccyyOyQolii)Lo`)Q^robk)?illaBicy

CLodofjj^oyOyQolii)?illaBicyy@yJ^dbyyKyQ^i%13+5)2-+/&yyWyQerkabo?irccy
CQfofpc^iDi^abpyKyQ^hbqebWbmmbifk%2-+6).0+6&yyWyArolq^oyy@yJ^dby
ORkabo`fqvyKyQo^sbiqlRkabo`fqv%16+4)36+5&yyWyRkabo`fqvyy@yJ^dby
ERkabo`fqvyRy3615yyOyQolii)Lo`)Q^robk)?illaBicyy@yT^ooflo)T^oil`h)M^i^afk)Mofbpq)Pe^j^k)Erkqbo)Oldrb)Ab^qeHkfdeq)Aorfay
QEb^oqplcWb^iyKyJ^pqbo>mlqeb`^ovC^o^kbii%16+4)36+5&yyWyRkabo`fqvyyNFAy...0y

KNrbrbCloArkdblkpRkqfiIbsbi00yKyLk`bvlrefqibsbi00`lkqfkrbtfqeO^wlocbkAltkpdrfaby

]]
end)
