
DugisGuideViewer:RegisterGuide("|cfff0c502Class Quest:|r Shaman / Warlock / Warrior (30+)", nil, "Horde", "I", function()
return [[
AAA

KIbsbi0-Obnrfobay@yT^oil`hyyKyQefpfp^Ibsbi0-nrbpqclokbtPrjjlkCbierkqbophfiiyyNFAy.5-.yyMIy0-y
KIbsbi0-Obnrfobay@yPe^j^kyyKyQefpfp^Ibsbi0-nrbpqcloPe^j^kpqld^fkqebfo>foQlqbjpyyNFAy.20.yyMIy0-y
KIbsbi0-Obnrfobay@yT^oofloyyKyQefpfp^Ibsbi0-nrbpqcloT^ooflopqld^fk?bopbohboPq^k`b^kaFkqbo`bmqPhfiiyyNFAy.4.5yyMIy0-y
KPe^j^k,T^ooflo,T^oil`hplkivyKyVlrtlk$q_b^_ibqlpbbqebpbdrfabrkibppvlr$ob^Pe^j^k)T^oil`hloT^oofloyy@yOldrb)M^i^afk)Erkqbo)Aorfa)Mofbpq)J^db)Ab^qeHkfdeqy

OLodofjj^oy@yPe^j^kyyKyQo^sbiqlLodofjj^o%14)30&yyNFAy.20.yyWyLodofjj^oy
OLodofjj^oy@yT^oofloyyKyQo^sbiqlLodofjj^o%14)30&yyNFAy.4.5yyWyLodofjj^oy
>@^iilc>foy@yPe^j^kyyKyPb^okCfobt^oabo%06)04&yyWyLodfjj^oyyNFAy.20.y
CCobbtfkaMlpqy@yPe^j^kyyKyAlo^p%12+/)31&yyWyLodfjj^oyyNFAy.20.y
Q@^iilc>foy@yPe^j^kyyKyCfkaMo^qb@ilrapbbo%20+3)1/+4&rpbqebm^qeqlqeb`^sb^q%21)11&yyNFAy.20.y

>QebFpi^kaboy@yT^oofloyyKyQefpfp^Ibsbi0-nrbpqclo?bopbohboPq^k`b)Plobh%5-+/)0/+1&yyWyLodofjj^oyyNFAy.4.5y
CO^q`ebqy@yT^oofloyyKyAlo^p%12+/)31&yyWyLodfjj^oyyNFAy.4.5y

QQebFpi^kaboy@yT^oofloyyKyHi^kkl`J^`ibla%35+3)16+.&yyWyQeb?^oobkpyyNFAy.4.5y
>Qeb>cco^vy@yT^oofloyyKyHi^kkl`J^`ibla%35+3)16+.&yyWyQeb?^oobkpyyNFAy.4.6y
@Qeb>cco^vy@yT^oofloyyKyHfiiqebpbofbplcJl_p)_^ka^db^kab^qfk_bqtbbkJl_p+>pclo?fdTfii)vlr$obdfsbkqebmofsfibdbql^qq^`hefjcfopq_b`^rpbeb$pkbrqo^i)plgrpqork_^`h^ka`e^odbqebkrpbvlroObq^if^qflkclo?fdTfii%35+3)15+4&yyWyQeb?^oobkpyyNFAy.4.6y
QQeb>cco^vy@yT^oofloyyKyHi^kkl`J^`ibla%35+3)16+.&yyWyQeb?^oobkpyyNFAy.4.6y
KPhfmqebcliiltrmnrbpqy@yT^oofloy

OO^q`ebqy@yT^oil`hyyKyQo^sbiqlO^`ebq%3/+3)04+1&yyWyQeb?^oobkpyyNFAy.5-.y
eO^q`ebqy@yT^oil`hyyKyFkkhbbmboTfibv%3/)06+1&yyWyQeb?^oobkpyyNFAy.5-.y
>Qljblc@^_^i%M^oq.&y@yT^oil`hyyKyQefpfp^Ibsbi0-nrbpqqlprjjlkCbierkqboj^hbprobvlrdbqqefp)Pqo^e^aC^op^k%3/+3)02+2&yyWyQeb?^oobkpyyNFAy.5-.y

QQljblc@^_^i%M^oq.&y@yT^oil`hyyKyGlo^e>kkfplk%44)02+3&yyWyRkabo`fqvyyNFAy.5-.y
>Qljblc@^_^i%M^oq/&y@yT^oil`hyyKyGlo^e>kkfplk%44)02+3&yyWyRkabo`fqvyyNFAy.5-0y

CQ^oobkJfiiy@yT^oil`hyyKyJf`e^biD^oobqq%30+2)15+4&yyWyRkabo`fqvyyNFAy.5-2y
KDbqXJliavQljbZy@yT^oil`hyyKyMf`hrmqebXJliavQljbZcoljQljblcqeb@^_^i%/4+4)4/+5&yyIy360.yyNFAy.5-0yyWyEfiip_o^aCllqefiipy

EO^q`ebqy@yT^oil`hyyRy3615yyNFAy.5-2y
CCobbtfkaMlpqy@yT^oil`hyyKy?o^dlh%30+.)04+/&yyWyQeb?^oobkpyyNFAy.5-2y

@Qljblc@^_^i%M^oq/&y@yT^oil`hyyKyDbqqebXQ^qqbobaJ^krp`ofmqZcoljqeba^j^dba`ebpqfkpfabqeb`bkq^ro`^sb%10)0/&yyNFAy.5-0yyWyQelrp^kaKbbaibpy

CLodofjj^oy@yT^oil`hyyKyKvpb%12+.)16+.&yyWyQelrp^kaKbbaibpyyNFAy.5-2y
CQfofpc^iDi^abpy@yT^oil`hyyKyQ^hbqebwbmmbifklrqpfabLodofjj^o%2-+5).0+4&qlQfofpc^iDi^abp%Rkabo`fqv&yyWyArolq^oyyNFAy.5-2y
ORkabo`fqvy@yT^oil`hyyKyOrkqlRkabo`fqv%3.+6)35+.&yyWyQfofpc^iDi^abpyyNFAy.5-2y
QQljblc@^_^i%M^oq/&y@yT^oil`hyyKyGlo^e>kkfplk%44)02+3&yyWyRkabo`fqvyyNFAy.5-0y
>Qljblc@^_^i%M^oq0&y@yT^oil`hyyKyGlo^e>kkfplk%44)02+3&yyWyRkabo`fqvyyNFAy.5-2y
CE^jjboc^iiy@yT^oil`hyyKyJf`e^biD^oobqq%30+2)15+4&yyWyRkabo`fqvyyNFAy.462y
OTbqi^kapy@yT^oil`hyyKyOrkqlqqebTbqi^kap%12+/)63+2&yyWy>o^qefEfdei^kapyyNFAy.462y
@Qljblc@^_^i%M^oq0&y@yT^oil`hyyKyHfiiAo^dlkj^t?lkbt^oabo^kaPe^altt^oaboql`liib`q0uXOlalc@e^kkbifkdZyyWyTbqi^kapyyNFAy.5-2y
C?llqv?^vy@yT^oil`hyyKyDl_^`hqlE^jjboc^ii^kacivql?llqv?^v%40+.)0/+4&yyWy>o^qefEfdei^kapyyNFAy.462y
_O^q`ebqy@yT^oil`hyyKyQ^hbqeb_l^qqlO^q`ebq%/3)40+/&yyWyPqo^kdibqelokS^ibyyNFAy.462y
QQljblc@^_^i%M^oq0&y@yT^oil`hyyKyPqo^e^aC^op^k%3/+3)02+2&yyWyQeb?^oobkpyyNFAy.5-2y
>Qeb?fkafkdy@yT^oil`hyyKyPqo^e^aC^op^k%3/+3)02+2&yyWyQeb?^oobkpyyNFAy.462y
@Qeb?fkafkdy@yT^oil`hyyKyRpbXQljblcqeb@^_^iZqlprjjlkqebCbierkqbo^kahfiifqyyRy3666yyWyQeb?^oobkpyyNFAy.462y
QQeb?fkafkdy@yT^oil`hyyKyPqo^e^aC^op^k%3/+3)02+2&yyWyQeb?^oobkpyyNFAy.462y

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
