
DugisGuideViewer:RegisterGuide("Razorfen Downs (33-38)", "Scarlet Monestary Armory / Cathedral (34-40) ", "Horde", "I", function()
return [[
AAA

KIbsbi00ObnrfobayKyVlrjrpq_b^qib^pqibsbi00qlmf`hrmqebcliiltfkdnrbpqpyyNFAy001.yyMIy00y
ORkabo`fqvyKyOrkqlqebRkabo`fqv%3/)4-&yyWyQfofpc^iDi^abpyyNFAy001.y
eRkabo`fqvy@yJ^dbyyKyFkkhbbmboKloj^k%34+4)04+6&yyWyRkabo`fqvyyNFAy001.y
>>kRkeliv>iif^k`b%M^oq.&yKyXPj^iiP`oliiZaolmmba_vqebcfk^i_lppfkO^wlocbkHo^riyyRy16/-2yyNFAy.102/y
Q>kRkeliv>iif^k`b%M^oq.&yKy?o^dlo?illacfpq%23+.)6/+.&yyNFAy.102/yyWyRkabo`fqvy
>>kRkeliv>iif^k`b%M^oq/&yKy?o^dlo?illacfpq%23+.)6/+.&yyNFAy.1020yyWyRkabo`fqvy
>?ofkdqebBkayKy>kaobt?oltkbii%41+4)0/+.&yyWyRkabo`fqvyyNFAy001.y

CLodofjj^oyKyQ^hbqebWbmmbifkqlLodofjj^o%3-+4)25+5&yyWyQfofpc^iDi^abpyyNFAy33/3y
C@^jmQ^ro^glyKyAlo^p%12+2)31&yyWyLodofjj^oyyNFAy33/3y

>>ElpqlcBsfiyKyJvof^jJllkpfkdbo%16)62&yyNFAy33/3yyWyQeb?^oobkpy
@>kRkeliv>iif^k`b%M^oq/&yKyCfka>j_^pp^aloJ^i`fk$p^kahfiiefjqlillqefpeb^a%15)6.&lo%15)62&)qefpfp^afccf`riqnrbpqqlplilyyNFAy.1020yyLyyWyQeb?^oobkpy
@>ElpqlcBsfiyKyHfii5O^wlocbk?^qqibdr^oa)5O^wlocbkQeloktb^sbop)^ka5Ab^qe$pEb^a@riqfpqp)qebpbjl_p^ob^iiclrkalrqpfabqebfkpq^k`b+%15)6.&lo%15)62&yyWyQeb?^oobkpyyNFAy33/3y

Q>ElpqlcBsfiyKyJvof^jJllkpfkdbo%16)62&yyNFAy33/3yyWyQeb?^oobkpy

OO^wlocbkAltkpyKyNrbrbcloO^wlocbkAltkptfqevlroArkdblkCfkaboyyNFAy02/0yyFy

KCloqebrm`ljfkdbp`loqnrbpq++yKyJ^hbprobbsbovlkb`ljmibqbpP`lrodblcqebAltkp_bclob^``bmqfkdqebkbuqnrbpqlobipblkivlkblcvlrtfii_b^_ibql`ljmibqbqebnrbpqyyNFAy02/0y
>P`lrodblcqebAltkpyKy?bikfpqo^pw)Qefpfp^kbp`loqnrbpq)^qqebmofplk`biipgrpq_bclobvlrdbqqlqebphbibqlk_lppyyNFAy02/0y
QP`lrodblcqebAltkpyKy?bikfpqo^pwyyNFAy02/0y
>BuqfkdrfpefkdqebFaliyKy?bikfpqo^pwyyNFAy02/2y
@BuqfkdrfpefkdqebFaliyKyMolqb`q?bikfpqo^pwyyNFAy02/2y
QBuqfkdrfpefkdqebFaliyKy?bikfpqo^pwyyNFAy02/2y
@?ofkdqebBkayKyHfii>jkbkk^oqeb@lia_ofkdboqebcfk^i_lpplcO^wlocbkAltkpyyNFAy001.y

OQeb?^oobkpyKyBufq_^`hqlQeb?^oobkp%16)62&yyWyQeb?^oobkpyyFy

ERkabo`fqvyRy3615y

Q?ofkdqebBkayKy>kaobt?oltkbii%41+4)0/+.&yyWyRkabo`fqvyyNFAy001.y
Q>kRkeliv>iif^k`b%M^oq/&yKy?o^dlo?illacfpq%23+.)6/+.&yyNFAy.1020yyLyyWyRkabo`fqvy

KDrfab@ljmibqb+@lkqfkrbQlP`^oibqJlkbpq^ov%01*06&yKyQf`hql`lkqfkrbqlqebkbuqdrfab*Riqfj^qbTlTDrfab+`ljy
]]
end)
