DugisGuideViewer:RegisterGuide("Uldaman (39-45)", "Zul'Farrak (42-47)", "Horde", "I", function()
return [[
AAA

KIbsbi05ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi05qlmf`hrmqebcliiltfkdnrbpqpyyNFAy/01/yyMIy05y

ORkabo`fqvyKyQo^sbiqlRkabo`fqv%3/+4)15+4&yyNFAy/01/yyWyRkabo`fqvy
>Ob`i^fjbaQob^probpyKyM^qof`hD^oobqq%3/+4)15+4&yyNFAy/01/yyWyRkabo`fqvy
??rvXColpqLfiZyKyColj>r`qflkElrpb%31+1)2/+2&%3-+2)1.+5&%34+4)02+6&%4.+1)13+4&*Phfmqefpfcklq^s^fi^_ibyyIy05/6yyWyRkabo`fqvy
??rvXDvol`eolk^qljZyKyColj>r`qflkElrpb%31+1)2/+2&%3-+2)1.+5&%34+4)02+6&%4.+1)13+4&*Alk$q_rvfcvlrafak$qcfka^ColpqLfiyyIy1056yyNFAy4-4yyWyRkabo`fqvy
??rvXEb^ifkdMlqflkZyKyColj>r`qflkElrpb%31+1)2/+2&%3-+2)1.+5&%34+4)02+6&%4.+1)13+4&*Alk$q_rvfcvlrafak$qcfka^ColpqLfi^kaDvol`eolk^qljyyIy6/6yyNFAy4-4yyWyRkabo`fqvy
??rvXIbppboFksfpf_fifqvMlqflkZyKyColj>r`qflkElrpb%31+1)2/+2&%3-+2)1.+5&%34+4)02+6&%4.+1)13+4&*Alk$q_rvfcvlrafak$qcfka^ColpqLfi^kaDvol`eolk^qljyyIy05/0yyNFAy4-4yyWyRkabo`fqvy
??rv1uX?rww^oaTfkdZyKyColj>r`qflkElrpb%31+1)2/+2&%3-+2)1.+5&%34+4)02+6&%4.+1)13+4&*Phfmqefpfcklq^s^fi^_ibyyIy01-11yyWyRkabo`fqvy

CQ^oobkJfiiyKyJf`e^biD^oobqq%30+0)15+3&yyWyRkabo`fqvyyNFAy/01/y

O>o^qefEfdei^kapyKyQo^sbiql>o^qefEfdei^kap%/.)0.&yyWy>o^qefEfdei^kapyyNFAy/1.5y
OQebidbkOl`hyKyQo^sbiqlIl`eJla^kqeolrdeQebidbkOl`h%2/+1)41&yyWyTbqi^kapyyNFAy/1.5y
OIl`eJla^kyKyQo^sbiqlIl`eJla^k%/2).0&yyWyIl`eJla^kyyNFAy/1.5y
O?^ai^kapyKyQo^sbiql?^ai^kap%16)6&yyWy?^ai^kapyyNFAy/1.5y

>MltboPqlkbpyKyOfddibcrww%1/+2)20+.&yyNFAy/1.5yyWy?^ai^kapy
>?^o_b`rba?rww^oaTfkdpyKyOfddibcrww%1/+2)20+.&yyNFAy4-0yyWy?^ai^kapy
>PqravlcqebBibjbkqp7Ol`h%M^oq.&yKyIlqtfiSbof^qrp%/2+6)12+-&yyNFAy4.-yyWy?^ai^kapy
>@lli^kqEb^apMobs^fiyKyIlqtfiSbof^qrp%/2+6)12+-&yyIy05/6yyLyyNFAy4.0y
Q@lli^kqEb^apMobs^fiyKyIlqtfiSbof^qrp%/2+6)12+-&yyLyyNFAy4.0y
>Dvol+++Te^q<yKyIlqtfiSbof^qrp%/2+6)12+-&yyIy1056yyLyyNFAy4.1y
QDvol+++Te^q<yKyIlqtfiSbof^qrp%/2+6)12+-&yyLyyNFAy4.1y
>IfnrfaPqlkbyKyIr`fbkQlppbitobk`e%/2+5)11+1&yyIy05/0yyLyyNFAy4.2y
QIfnrfaPqlkbyKyIr`fbkQlppbitobk`e%/2+5)11+1&yyLyyNFAy4.2y

OH^od^qeyKyQo^sbiqlH^od^qefk?^ai^kap%1)11+5&yyWy?^ai^kapyyNFAy//25y
cH^od^qeyKyDloofh%1)11+5&yyWy?^ai^kapyyNFAy//25y

>?^ai^kapOb^dbkqOrkyKyG^oh^iJlppjbia%/+3)13+.&yyNFAy//25yyWy?^ai^kapy
>@lvlqbQefbsbpyKyKbbh^?illap`^o%3+2)14+.&yyNFAy.1.6yyWy?^ai^kapy

@?^o_b`rba?rww^oaTfkdpyKyHfiiqeb?rww^oapclo1X?rww^oaTfkdpZ^olrka%.1)3-&yyNFAy4-0yyWy?^ai^kapy
@@lvlqbQefbsbpyKyHfiiqeb@lvlqbpclo0-X@lvlqbG^t_lkbpZ^olrka%..)30&yyNFAy.1.6yyWy?^ai^kapy
@PqravlcqebBibjbkqp7Ol`h%M^oq.&yKyHfiiqebIbppboOl`hBibjbkq^ip%.5)12&clo.-XPj^iiPqlkbPe^oapZyyNFAy4.-yyWy?^ai^kapy
@?^ai^kapOb^dbkqOrkyKyHfiiOl`hBibjbkq^ip%.0)03&clo2XOl`hBibjbkq^iPe^oapZ+Hfii?rww^oap%.1)3-&clo2X?rww^oaDfww^oapZ+Hfii@lvlqbp%..)30&clo.-X@o^d@lvlqbC^kdpZyyNFAy//25yyWy?^ai^kapy

QPqravlcqebBibjbkqp7Ol`h%M^oq.&yKyIlqtfiSbof^qrp%/2+6)12+-&yyNFAy4.-yyWy?^ai^kapy
Q@lvlqbQefbsbpyKyKbbh^?illap`^o%3+2)14+.&yyNFAy.1.6yyWy?^ai^kapy
Q?^ai^kapOb^dbkqOrkyKyG^oh^iJlppjbia%/+2)13+.&yyNFAy//25yyWy?^ai^kapy
>Ria^j^kOb^dbkqOrkyKyG^oh^iJlppjbia%/+3)13+.&yyNFAy//-/yyWy?^ai^kapy
Q?^o_b`rba?rww^oaTfkdpyKyOfddibcrww%1/+1)2/+5&yyNFAy4-0yyWy?^ai^kapy

>PlirqflkqlAlljyKyQebiarofkqebIlpq%2.+2)43+5&yyNFAy4-6yyWy?^ai^kapy

ORia^j^kyKyBkqboqebRia^j^kjfkb^ob^%klqqebfkpq^k`b&%11+2)./+.3&yyWy?^ai^kapyyNFAy/1.5y

@PlirqflkqlAlljyKyCfkaqeb`ebpqfkRia^j^kmob*fkpq^k`b^ob^%06+0/).5+5.&yyNFAy4-6yyWy?^ai^kapy
@Ob`i^fjbaQob^probpyKyCfkaqebD^oobqqC^jfiv@ebpqfkRia^j^kmob*fkpq^k`b^ob^%01+.6).5+3.&yyNFAy/01/yyWy?^ai^kapy
@MltboPqlkbpyKyVlr`^k`ljmibqbqefp_vhfiifkdqebAt^osbplrqpfabRia^j^kFkpq^k`b%11+2)./+.3&yyNFAy/1.5yyWy?^ai^kapy
KDbqXPe^qqbobaKb`hi^`bZyKyHfiiqebKM@lrqpfabqebfkpq^k`brkqfivlrcfkaqebXPe^qqbobaKb`hi^`bZ%11+2)./+.3&yyIy4333yyWy?^ai^kapy

O?^ai^kapyKyOrklrqlcqebjfkbql?^ai^kap%11+5)./&yyWy?^ai^kapyyNFAy4/5y

QMltboPqlkbpyKyOfddibcrww%1/+2)20+.&yyNFAy/1.5yyWy?^ai^kapy
QPlirqflkqlAlljyKyQebiarofkqebIlpq%2.+2)43+5&yyNFAy4-6yyWy?^ai^kapy

>QlqebRkabo`fqvcloV^dvfk$pAfdbpqyKyQebiarofkqebIlpq%2.+2)43+5&yyNFAy4/5yyWy?^ai^kapy

ERkabo`fqvyRy3615yyNFAy//50y

QOb`i^fjbaQob^probpyKyM^qof`hD^oobqq%3/+4)15+4&yyNFAy/01/yyWyRkabo`fqvy
QQlqebRkabo`fqvcloV^dvfk$pAfdbpqyKyHbbmbo?bi$ardro%21+2)20+1&yyNFAy4/5yyWyRkabo`fqvy

CLodofjj^oyKyQ^hbqebWbmmbifkqlLodofjj^o%3-+4)25+5&yyWyQfofpc^iDi^abpyyNFAy//50y
eLodofjj^oyKyFkkhbbmboDvopeh^%21+.)35+1&yWyLodofjj^oyyNFAy//50y

>Kb`hi^`bOb`lsbovyKyAo^kAolccbop%26+2)03+5&yyNFAy//50yyWyLodofjj^oy
QKb`hi^`bOb`lsbovyKyAo^kAolccbop%26+2)03+5&yyNFAy//50yyWyLodofjj^oy
>Kb`hi^`bOb`lsbov)Q^hb/yKyAo^kAolccbop%26+2)03+5&yyNFAy/01-yyWyLodofjj^oy

CPqo^kdibqelokS^ibyKyQ^hbqebWbmmbifk%2-+3)./+3&yyWyArolq^oy
cPqo^kdibqelokS^ibyKyQevpq^%0/+2)/6+1&yyWyPqo^kdibqelokS^iby
CH^od^qeyKyQevpq^%0/+2)/6+1&yyWyPqo^kdibqelokS^iby

ORia^j^kyKyRpbqebArkdblkcfkabocloRia^j^kyyNFAy/0.5yyFy

QKb`hi^`bOb`lsbov)Q^hb/yKyCfkaObj^fkplc^M^i^afk)tebkvlrbkqboqebfkpq^k`b)pqf`hqlqebofdeqpfablcqebe^iip^kavlrtfiicfkaefjlkqeb/kae^iit^vyyNFAy/01-y
>Qo^kpi^qfkdqebGlrok^i%M^oq.&yKyObj^fkplc^M^i^afkyyNFAy/0.5y

OH^od^qeyKy@if`hlkqebArkdblkcfkabof`lk_vvlrojfkfj^m^kaqbibmloqlrqlcRia^j^k_^`hqltebobvlrtbobfkH^od^qeqlqrokfkqebnrbpq)qbiivlrom^oqvvlrtfii_bofdeq_^`h%/+3)13+.&yyWy?^ai^kapyyFy

QQo^kpi^qfkdqebGlrok^i%M^oq.&yKyG^oh^iJlppjbia%/+3)13+.&yyWy?^ai^kapyyNFAy/0.5y
>Qo^kpi^qfkdqebGlrok^i%M^oq/&yKyG^oh^iJlppjbia%/+3)13+.&yyWy?^ai^kapyyNFAy/005y
QQo^kpi^qfkdqebGlrok^i%M^oq/&yKyG^oh^iJlppjbia%/+3)13+.&yyWy?^ai^kapyyNFAy/005y
>CfkaqebDbjp^kaMltboPlro`byKyG^oh^iJlppjbia%/+3)13+.&yyWy?^ai^kapyyNFAy/006y

ORia^j^kyKy@if`hlkqebArkdblkcfkabof`lk_vvlrojfkfj^m^kaqbibmloq_^`hqlRia^j^k^ka`lkqfkrb^pkloj^iyyNFAy//45yyFy

KDbqXPe^qqbobaKb`hi^`bQlm^wZyKyDbqXPe^qqbobaKb`hi^`bQlm^wZfpfk^@lkpmf`rlrpRokfkqebolljtfqeqebqeobbilpqsfhfkd)%tebobvlrdbqqebDkf$hfsJba^iiflk&yyNFAy/006yyIy434.y
KDbqXPe^qqbobaKb`hi^`bOr_vZyKyDbqXPe^qqbobaKb`hi^`bOr_vZfkqebPe^altclodb`^`ebfpfkqebolljtfqeD^id^kkCfobe^jjboyyNFAy/006yyIy4336y
KDbqXPe^qqbobaKb`hi^`bP^mmefobZyKyDbqXPe^qqbobaKb`hi^`bP^mmefobZaolmmbacoljDofj$ilhyyNFAy/006yyIy434-y
KDbqXPe^qqbobaKb`hi^`bMltboPlro`bZyKyDbqXPe^qqbobaKb`hi^`bMltboPlro`bZcolj>o`e^ba^pqebcfk^i_lppfkRia^j^kyyNFAy/006yyIy434/y

>QebMi^qfkrjAfp`p%M^oq.&yKyColjQebMi^qfkrjAfp`pfkqebolljtfqe>o`e^ba^pyyNFAy//45y
KQ^ihqlPqlkbT^q`eboyKyQ^ihqlPqlkbT^q`ebokbuqqlqebafph^kaphfmqeolrde^iiefppqlovyyNFAy//45yyNLyIb^okte^qilobqe^qqebpqlkbt^q`eboe^pqllccboy
QQebMi^qfkrjAfp`p%M^oq.&yKyColjQebMi^qfkrjAfp`pfkqebolljtfqe>o`e^ba^pyyNFAy//45y
>QebMi^qfkrjAfp`p%M^oq/&yKyColjQebMi^qfkrjAfp`pfkqebolljtfqe>o`e^ba^pyyNFAy//5-y
@Ria^j^kOb^dbkqOrkyKyVlr`^kcfkaqebjrpeolljp`^qqbobaqeolrdelrqqebRia^j^kArkdblk)Fcvlralk$qcfkabklrdelkvlrocfopqqfjbqeolrde)tebkqebfkpq^k`bfpcfkfpeba)vlr`^keb^a_^`hlrqqeolrdeqebfkpq^k`b^kaqebjrpeolljptfiie^sbobpm^tkba+Grpqdlmf`hcoljqebkbtivpm^tkbaJrpeolljp^kavlr$obalkb+yyNFAy//-/yyWy?^ai^kapy

OH^od^qeyKyQo^sbiqlH^od^qefk?^ai^kap%1)11+5&yyWy?^ai^kapyyNFAy/01-yyFy

QRia^j^kOb^dbkqOrkyKyG^oh^iJlppjbia%/+3)13+.&yyNFAy//-/yyWy?^ai^kapy
QCfkaqebDbjp^kaMltboPlro`byKyG^oh^iJlppjbia%/+3)13+.&yyWy?^ai^kapyyNFAy/006y
KP^sbXObpqlo^qfsbMlqflkZyKyVlrtfiikbbaqefpfqbji^qboqlhfii^kKM@fkQebEfkqboi^kapyyNFAy/01-y
>AbifsboqebDbjpyKyG^oh^iJlppjbia%/+3)13+.&yyWy?^ai^kapyyNFAy/01-y

ELodofjj^oyRy3615yyNFAy/01.y

QAbifsboqebDbjpyKyAo^kAolccbop%26+2)03+5&yyWyLodofjj^oyyNFAy/01-y
>Kb`hi^`bOb`lsbov)Q^hb0yKyAo^kAolccbop%26+2)03+5&yyWyLodofjj^oyyNFAy/01.y

CPqo^kdibqelokS^ibyKyQ^hbqebWbmmbifk%2-+3)./+3&yyWyArolq^oyyNFAy/11-y

CH^od^qeyKyQevpq^%0/+2)/6+1&yyWyPqo^kdibqelokS^ibyyNFAy/11-y

QKb`hi^`bOb`lsbov)Q^hb0yKyG^oh^iJlppjbia%/+3)13+.&yyWy?^ai^kapyyNFAy/01.y

OQerkabo?irccyKyQo^sbiqlQerkabo?ircc%02)15&yyWyQerkabo?irccyyNFAy/11-y

QQebMi^qfkrjAfp`p%M^oq/&yKyP^dbQorqepbbhbo%02)15&yyWyQerkabo?irccyyNFAy//5-y
>QebMi^qfkrjAfp`p%M^oq0&yKyP^dbQorqepbbhbo%02)15&yyWyQerkabo?irccyyNFAy/11-y
QQebMi^qfkrjAfp`p%M^oq0&yKy?bk^Tfkqboellc%13+5)00+3&yyWyQerkabo?irccyyNFAy/11-y

KDrfab@ljmibqb+@lkqfkrbQlWri$C^oo^h%1/*14&yKyQf`hql`lkqfkrbqlWri$C^oo^h%1/*14&*Riqfj^qbTlTDrfab+`ljy

]]
end)
