DugisGuideViewer:RegisterGuide("Zul'Farrak (42-47)", "Maraudon (45-49)", "Horde", "I", function()
return [[
AAA

KIbsbi1-ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi1-qlmf`hrmqebcliiltfkdnrbpqpyyNFAy/44-yyMIy1-y

O@^jmQro^glyKyQo^sbiql@^jmQro^gl%12+3)26&yyWyQeb?^oobkpyyNFAy/44-y

OArpqt^iiltJ^opey@yJ^dbyyKyQo^sbiqlArpqt^iiltJ^ope%13)24+.&yyWyArpqt^iiltJ^opeyyNFAy/44-y
>Qf^o^lcqebAbbmy@yJ^dbyyKyQ^_bqe^%13)24+.&yyNFAy/513yyWyArpqt^iiltJ^opey
CCobbtfkaMlpqy@yJ^dbyyKyPe^oaf%02+3)0.+6&yyWyArpqt^iiltJ^opeyyNFAy/44-y

OQelrp^kaKbbaibpyKyQo^sbiqlQelrp^kaKbbaibp%0/)02&yyWyQelrp^kaKbbaibpyyNFAy.614y
OCobbtfkaMlpqyKyQo^sbiqlCobbtfkaMlpq%1.)15&yyWyQelrp^kaKbbaibpyyNFAy.614y
cCobbtfkaMlpqyKyKvpb%12+.)16+.&yyWyQelrp^kaKbbaibpyyNFAy.614y
OQebPefjjbofkdCi^qpyKyQo^sbiqlQebPefjjbofkdCi^qp%4-)25&yyWyQelrp^kaKbbaibpyyNFAy.614y

>D^ew$ofii^yKyTfwwib?o^pp_liqp%45+.)44+.&yyWyQelrp^kaKbbaibpyyNFAy/44-y

OD^adbqw^kyKyQo^sbiqlD^adbqw^k%2.+3)/2+1&yyWyQ^k^ofpyyNFAy/435y
cD^adbqw^kyKy?rihobdO^dbcfpq%2.+3)/2+1&yyWyQ^k^ofpyyNFAy/435y

>Afsfkl*j^qf`OlayKy@efbcBkdfkbbo?fidbtefwwib%2/+2)/5+2&yyWyQ^k^ofpyyNFAy/435y
>P`^o^_PebiipyKyQo^k$obh%2.+3)/3+5&yyWyQ^k^ofpyyNFAy/532y
>QoliiQbjmboyKyQobkqlkIfdeqe^jjbo%2.+2)/5+4&yyNFAy0-1/yyWyQ^k^ofpy

>P`obb`eboPmfofqpyKyVbe$hfkv^%33+6)//+1&yyNFAy02/-yyWyQ^k^ofpy

CCobbtfkaMlpqyKy?rihobdO^dbcfpq%2.+3)/2+1&yyWyQ^k^ofpyyNFAy4-34y
OCbo^i^pyKyQo^sbiqlCbo^i^p%55+1)1.+.&yyWyCbo^i^pyyNFAy4-34y
cCbo^i^pyKyPevk%42+2)11+1&yyWyCbo^i^pyyNFAy4-34y

@P`obb`eboPmfofqpyKyHfiiP`obb`ebop%24+2)20+6&)%3-)3.&^karpbXVbe$hfkv^$p?o^j_ibZlkqebab^aP`obb`ebopyyRy.-366yyNFAy02/-yyWyCbo^i^py
OAbpli^`byKyQo^sbiqlAbpli^`b%1.+1)56&yyWyAbpli^`byyNFAy4-34y
>QebM^of^e$pFkpqor`qflkpyKy@bkq^roM^of^e)ebqo^sbip_bqtbbk%10+1)51+5&)%2-+2)53+3&yyWyAbpli^`byyNFAy4-34y
OPe^altmobvSfii^dbyKyQo^sbiqlPe^altmobvSfii^db%/1+3)4.+0&yyWyAbpli^`by
cPe^altmobvSfii^dbyKyQe^ilkd%/.+3)41+/&yyWyAbpli^`by

ELodofjj^oyRy3615yyNFAy/600y

CQfofpc^iDi^abpyKyQ^hbqebWbmmbifk%2-+6).0+6&yyWyArolq^oyyNFAy/600y
CQ^oobkJfiiyKyJf`e^biD^oobqq%30+0)15+3&yyWyRkabo`fqvyyNFAy/600y
KEb^aqlEfkqboi^kapbkqo^k`byKy%51+4)0/&yyWyEfiip_o^aCllqefiipyyNFAy/600y
OQebEfkqboi^kapyKyQo^sbiqlQebEfkqboi^kap%.-)21+2&yyWyQebEfkqboi^kapyyNFAy/600y

>Sbklj?lqqibpyKySbklj?lqqib%/0)22&yyNFAy/600yyWyQebEfkqboi^kapy
QSbklj?lqqibpyKy>mlqeb`^ovIvalk%3.+2).6+/&yyNFAy/600yyWyEfiip_o^aCllqefiipy
>Rka^j^dbaSbkljP^`yKy>mlqeb`^ovIvalk%3.+2).6+/&yyNFAy/601yyWyEfiip_o^aCllqefiipy
@Rka^j^dbaSbkljP^`yKyHfiiTfqebo_^oh?olladr^oa%02)4-&rkqfivlrcfkaXRka^j^dbaSbkljP^`ZyyNFAy/601yyWyQebEfkqboi^kapy
QRka^j^dbaSbkljP^`yKy>mlqeb`^ovIvalk%3.+2).6+/&yyNFAy/601yyWyEfiip_o^aCllqefiipy
>@lkpriqJ^pqboD^aofkyKy>mlqeb`^ovIvalk%3.+2).6+/&yyNFAy/602yyWyEfiip_o^aCllqefiipy

CRkabo`fqvyKyW^ofpb%3-+.).5+3&yyWyEfiip_o^aCllqefiipyyNFAy/603y
CLodofjj^oyKyQ^hbqebWbmmbifkqlLodofjj^o%3-+4)25+5&yyWyQfofpc^iDi^abpyyNFAy/603y

Q@lkpriqJ^pqboD^aofkyKyJ^pqboD^aofk%22+6)41+5&yyNFAy/602yyWyArolq^oy
>QebPmfaboDlayKyJ^pqboD^aofk%22+6)41+5&yyNFAy/603yyWyArolq^oy

CD^adbqw^kyKyAlo^p%12+2)31&yyWyLodofjj^oyyNFAy02/4y

QP`obb`eboPmfofqpyKyVbe$hfkv^%33+6)//+1&yyNFAy02/-yyWyQ^k^ofpy
>QebMolmeb`vlcJlpe$^oryKyVbe$hfkv^%33+6)//+1&yyNFAy02/4yyWyQ^k^ofpy

OWri$C^oo^hyKyRpbqebArkdblkcfkaboqlnrbrbcloWri$C^oo^hyyNFAy0-1/yyFy

KDbqXCfopqJlpe$^orQ^_ibqZyKyQefpfpaolmmbacoljqebcfopq_lppQebh^qebJ^oqvoyyIy.-33-yyNFAy02/4y
KCfkaqebPmfaboDla$pK^jbyKyVlrtfiikbbaqlhfiiQebh^cfopqplvlr`^kob^aqebq^_ibqfkqebjfaaiblcqebp`^o^_olljyyNLyCfkaqebPmfaboDla$pK^jbyyNFAy/603y
@Afsfkl*j^qf`OlayKyQlpq^oqqebnrbpqbsbkqvlre^sbqlhfiiqebP^kacrovBub`rqflkbo^qqebqlmlcqebQbjmib^karpbqebhbvebaolmpqlcobbPbodb^kq?ivcoljefp`^db)lk`bqebbsbkqfplsbovlr`^kq^ihql?ivqlmf`h^cfdeq+Alklqq^ihql?ivrkqfibsbov_lavfpob^av)Hfiilccqebmofbpq^kail`hcfopq)qebkqeboldrb^kacfk^iiv?ivefjpbic+Illqefp_lavcloqebafsfkl*j^qf`ola^kaqebnrbpqfp`ljmibqbyyWyQ^k^ofpyyNFAy/435y
@D^ew$ofii^yKyOfkdqebdlkdqlprjjlk^kahfiiD^ew$ofii^^kaillqXD^ew$ofii^$pBib`qofcfbaP`^ibZyyWyQelrp^kaKbbaibpyyNFAy/44-y
@P`^o^_PebiipyKy@liib`q2uXP`^o^_PebiiZaolmmba_vqebp`^o^_pfkqebrkab^a^ob^yyWyQ^k^ofpyyNFAy/532y
@Qf^o^lcqebAbbmy@yJ^dbyyKyHfiiEvaolj^k`boSbio^qe^telfpfkqebp^jbollj^pD^ew$ofii^^kaillqXQf^o^lcqebAbbmZyyNFAy/513y
@QebMolmeb`vlcJlpe$^oryKyQeb/kaq^_ibqfpaolmmba_vEvaolj^k`boSbio^qe^telfpfkqebp^jbollj^pD^ew$ofii^yyNFAy02/4y
@QoliiQbjmboyKyAolmmba_v^kvqoliicoljWri$C^oo^hvlrpelriadbq/-^cqbo.orkyyNFAy0-1/yyWyQ^k^ofpy

OD^adbqw^kyKyQbibmloq_^`hqlD^adbqw^k%2.+3)/3+5&yyNFAy1454yyWyQ^k^ofpyyFy

QP`^o^_PebiipyKyQo^k$obh%2.+3)/3+5&yyWyQ^k^ofpyyNFAy/532y
QQoliiQbjmboyKyQobkqlkIfdeqe^jjbo%2.+2)/5+4&yyNFAy0-1/yyWyQ^k^ofpy
QAfsfkl*j^qf`OlayKy@efbcBkdfkbbo?fidbtefwwib%2/+2)/5+2&yyWyQ^k^ofpyyNFAy/435y

QQebMolmeb`vlcJlpe$^oryKyVbe$hfkv^%33+6)//+1&yyNFAy02/4yyWyQ^k^ofpy
>Qeb>k`fbkqBddyKyVbe$hfkv^%33+6)//+1&yyNFAy1454yyWyQ^k^ofpy

QD^ew$ofii^yKyTfwwib?o^pp_liqp%45+.)44+.&yyWyQelrp^kaKbbaibpyyNFAy/44-y

C?o^`hbkt^iiSfii^dby@yJ^dbyyKy?rihobdO^dbcfpq%2.+3)/2+1&yyWyQ^k^ofpyyNFAy/604y
QQf^o^lcqebAbbmy@yJ^dbyyKyQ^_bqe^%13)24+.&yyNFAy/513yyWyArpqt^iiltJ^opey
CLodofjj^oy@yJ^dbyyKyPe^oaf%02+3)0.+6&yyWyArpqt^iiltJ^opeyyNFAy/604y
CLodofjj^oyKy?rihobdO^dbcfpq%2.+3)/2+1&yyWyQ^k^ofpyyNFAy/604y

QQebPmfaboDlayKyJ^pqboD^aofk%22+6)41+5&yyNFAy/603yyWyArolq^oy
>PrjjlkfkdPe^ao^yKyJ^pqboD^aofk%22+6)41+5&yyNFAy/604yyWyArolq^oy

KDrfab@ljmibqb+@lkqfkrbQlJ^o^ralk%12*16&yKyQf`hql`lkqfkrbqlJ^o^ralk%12*16&*Riqfj^qbTlTDrfab+`ljy
]]
end)
