DugisGuideViewer:RegisterGuide("Maraudon (45-49)", "Sunken Temple (48-52)", "Horde", "I", function()
return [[
AAA

KIbsbi12ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi12qlmf`hrmqebcliiltfkdnrbpqpyyNFAy4-35yyMIy12y

OLodofjj^oyKyQo^sbiqlLodfjj^o%06)52+6&yyWyLodofjj^oyyNFAy4-35y
>Pe^altpe^oaCo^djbkqpyKyRqebi$k^v%06)52+6&yyWyLodofjj^oyyNFAy4-35y

CPe^altmobvSfii^dbyKyAlo^p%12+2)31&yyWyLodofjj^oyyNFAy4-/6y
ePe^altmobvSfii^dbyKyFkkhbbmboPfhbt^%/1+.)35+1&yyWyAbpli^`byyNFAy4-/6y

>Svibqlkdrb@loormqflkyKyS^oh?^qqibp`^o%/0+/)4-+/&yyWyAbpli^`byyNFAy4-/6y
>@loormqflklcB^oqe^kaPbbayKyPbibkao^%/3+6)44+4&yyWyAbpli^`byyNFAy4-31y
>QebM^of^e$pFkpqor`qflkpyKy@bkq^roM^of^e)ebqo^sbip_bqtbbk%10+1)51+5&)%2-+2)53+3&yyWyAbpli^`byyNFAy4-34y
>QtfpqbaBsfipyKyTfiilt%3/+/)06+3&yyWyAbpli^`byyNFAy4-/5y

OJ^ro^alkyKyQo^sbiqlJ^ro^alk`^sb^ob^)%/6+4)3/+2&yyWyAbpli^`byyNFAy4-11y

HQebK^jbibppMolmebqyKyHfiiQebK^jbibppMolmebq%/5+.2)31+/-&)%/5+2)30&eb$p^ibsbi1.*10bifqb)vlrpelria_b^_ibqlplilefj^qibsbi12^kadbqX>jribqlcPmfofqpZyyWyAbpli^`byyIy.4424yyNFAy4-34y
HQebCfopqH^ekyKyRpbX>jribqlcPmfofqpZlkqebH^ek%/6+34)3-+16&qebkhfiiqebCfopqH^ek^kadbqXDbjlcQebCfopqH^ekZyyRy.4424yyIy.443.yyWyAbpli^`byyNFAy4-34y
HQebPb`lkaH^ekyKyRpbX>jribqlcPmfofqpZlkqebH^ek%/5+4)24+34&qebkhfiiqebPb`lkaH^ek^kadbqXDbjlcQebPb`lkaH^ekZyyRy.4424yyIy.443/yyWyAbpli^`byyNFAy4-34y
@Pe^altpe^oaCo^djbkqpyKyHfiiPe^altpe^oaPj^pebop%/3+40)24+0&^ka`liib`q.-uXPe^altpe^oaCo^djbkqZyyWyAbpli^`byyNFAy4-35y
>IbdbkaplcJ^o^ralkyKyEb^a_^`hlrqqlt^oapqebbkqo^k`b^kapqf`hqlqebofdeqpfab^kacliiltqeblo^kdbpqlkb^ob^qlcfka@^sfkao^%0/)30+5&yyWyAbpli^`byyNFAy4-11y
R@l^qba@borib^kSf^iyKyRpbqebX@l^qba@borib^kSf^iZfkqeblo^kdbmlli%00+.)32+4&yyWyAbpli^`byyRy.4360yyIy.4430yyNFAy4-/6y
HQebQefoaH^ekyKyRpbX>jribqlcPmfofqpZlkqebH^ek%02+.1)3-+.0&qebkhfiiqebQefoaH^ek^kadbqXDbjlcQebQefoaH^ekZyyRy.4424yyIy.4430yyNFAy4-34yyWyAbpli^`by

KNrbrbcloJ^o^ralk*Mromib@ovpq^ipyKyRpbqebArkdblkcfkaboqlnrbrbcloJ^o^ralk*Mromib@ovpq^ipyyFyyNFAy4-13y
HQebClroqeH^ekyKyRpbX>jribqlcPmfofqpZlkqebH^ekfkqebMromib@ovpq^i^ob^qebkhfiiqebClroqeH^ek^kadbqXDbjlcQebClroqeH^ekZyyRy.4424yyIy.4431yyNFAy4-34y
HIloaSvibqlkdrbyKyHfiiIloaSvibqlkdrb^kadbqX@bib_of^kAf^jlkaZyyIy.44-0yyNFAy4-/6y

KIb^sb^kanrbrbcloJ^o^ralk*Lo^kdb@ovpq^ipyKyRpbqebArkdblkcfkaboqlnrbrbcloJ^o^ralk*Lo^kdb@ovpq^ipyyFyyNFAy4-13y

HQebCfcqeH^ekyKyRpbX>jribqlcPmfofqpZlkqebH^ekfkqebLo^kdb@ovpq^i^ob^qebkhfiiqebCfcqeH^ek^kadbqXDbjlcQebCfcqeH^ekZyyRy.4424yyIy.4432yyNFAy4-34y
@QebM^of^e$pFkpqor`qflkpyKy@lj_fkb^iiqebdbjpql`ob^qbX>jribqlcRkflkZyyRy.4432yyNFAy4-34y
@Svibqlkdrb@loormqflkyKyQebsfkbp^obil`^qbafkpfabqebfkpq^k`bfkqeblo^kdbm^oq+Rpbqebsf^ilkqebtfkbp%fqe^p^_lrq.-v^oao^kdb&+QtlloqeobbKluuflrpP`flkpm^tkp^kavlrkbbaqlhfii5lcqebpbfkqlq^iql`ljmibqbqebnrbpqyyRy.4363yyNFAy4-/6y
HKluuflkyKyHfiiKluuflk^kadbqX@bib_of^kOlaZyyIy.44-/yyNFAy4-11y
H@bib_o^pqeb@ropbayKyHfii@bib_o^pqeb@ropba^qqebmlfplkc^iip)hbbmdlfkd^cqbovlrhfiiqebi^pq_lpp)fkqeblo^kdbfkpq^k`b)_bdvlrodolrmqlpq^vcloqebnrbpqy
QIbdbkaplcJ^o^ralkyKy>cqbovlrhfii@bib_o^pqeb@ropba)@bib_o^pqebObabbjbatfii^mmb^oclovlrqlqrokfkqebnrbpqyyNFAy4-11y
>QebP`bmqbolc@bib_o^pyKy@bib_o^pqebObabbjbayyNFAy4-13y
@QebP`bmqbolc@bib_o^pyKyAbcbka@bib_o^pqebObabbjba^kaq^ihqlefjlk`bqebofqr^ifplsboyyNFAy4-13y
QQebP`bmqbolc@bib_o^pyKy@bib_o^pqebObabbjbayyNFAy4-13y

EPe^altmobvSfii^dbyRy3615yyNFAy4-33y
QSvibqlkdrb@loormqflkyKyS^oh?^qqibp`^o%/0+/)4-+/&yyWyAbpli^`byyNFAy4-/6y
QQebM^of^e$pFkpqor`qflkpyKy@bkq^roM^of^e)ebqo^sbip_bqtbbk%10+1)51+5&)%2-+2)53+3&yyWyAbpli^`byyNFAy4-34y
QQtfpqbaBsfipyKyTfiilt%3/+/)06+3&yyWyAbpli^`byyNFAy4-/5y

KNrbrbcloJ^o^ralk*MofpqfkbT^qbopyKyNrbrbcloJ^o^ralk*MofpqfkbT^qbopyyFyyNFAy4-33y
@@loormqflklcB^oqe^kaPbbayKyPi^vMofk`bppQebo^ao^pfkJ^o^ralk*MofpqfkbT^qbopyyWyAbpli^`byyNFAy4-31y
>PbbalcIfcbyKyW^bq^o$pPmfofq)eb^mmb^op^cqbovlrhfiiqebMofk`bppyyNFAy4-33y

OPe^altmobvSfii^dbyKyQbibmloq_^`hqlPe^altmobvSfii^dbyyFy

Q@loormqflklcB^oqe^kaPbbayKyPbibkao^%/3+6)44+4&yyWyAbpli^`byyNFAy4-31y

OJllkdi^aby@yAorfayyKyRpbvlrojllkdi^abqbibmloqpmbiiy
QPbbalcIfcby@yAorfayyKyHbbmboObjrilp%03+2)1/+.&yyNFAy4-33yyWyJllkdi^aby
CLodofjj^oy@yAorfayyKyC^rpqolk%0/+.)33+3&yyWyJllkdi^aby

CLodofjj^oyKyQe^ilkd%/.+3)41+/&yyWyAbpli^`by
QPe^altpe^oaCo^djbkqpyKyRqebi$k^v%06)52+6yyWyLodofjj^oyyNFAy4-35y

CPmifkqboqobbMlpqy@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKyAlo^p%12+2)31&yyWyLodofjj^oy
OCbitllay@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKyQo^sbiqlCbitlla%21+2)6-+3&yyWyCbitllay
cBjbo^iaP^k`qr^ovy@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKyDloofj%2.+2)5/+/&yyWyCbitllay
>Qfj_boj^t>iivy@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKyDo^wib%2.)52&yyNFAy3.0.yyWyCbitllay
@Qfj_boj^t>iivy@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKyHfii2Ab^atllaT^ooflop)2Ab^atllaM^qecfkabop)^ka2Ab^atllaD^oabkbop)qebv^ii`^k_bclrka^olrka%15)6-&yyNFAy3.0.yyWyCbitllay
QQfj_boj^t>iivy@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKyDo^wib%2.)52&yyNFAy3.0.yyWyCbitllay
O?illasbkljMlpqy@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKyQo^sbiql?illasbkljMlpq%01+1)21&yyWyCbitllay
c?illasbkljMlpqy@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKy?o^hh^o%01+1)21&yyWyCbitllay

OQfj_boj^tEliay@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKyQo^sbiqlQfj_boj^tElia%32+2)4&yyWyCbitllay
OJllkdi^aby@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKyQo^sbiqlJllkdi^ab%01+4)4-+5&yyWyCbitllay
QPbbalcIfcby@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKyHbbmboObjrilp%03+2)1/+.&yyNFAy4-33yyWyJllkdi^aby
CLodofjj^oy@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKyC^rpqolk%0/+.)33+3&yyWyJllkdi^aby

KDrfab@ljmibqb+@lkqfkrbQlPrkhbkQbjmib%15*2/&yKyQf`hql`lkqfkrbqlPrkhbkQbjmib%15*2/&*Riqfj^qbTlTDrfab+`ljy

]]
end)
