DugisGuideViewer:RegisterGuide("Sunken Temple (48-52)", "Blackrock Depths: Prison (52-55)", "Horde", "I", function()
return [[
AAA

KIbsbi15ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi15qlmf`hrmqebcliiltfkdnrbpqpyyNFAy005-yyMIy15y

O@^jmJlg^`ebyKyQo^sbiql@^jmJlg^`eb)Cbo^i^p%42+/)10+4&yyWyCbo^i^pyyNFAy0111y
>QebPrkhbkQbjmibyKyTfq`eAl`qloRwbo$f%41+2)10+1&yyWyCbo^i^pyyNFAy005-y
CD^adbqw^kyKyPevk%42+2)11+1&yyWyCbo^i^pyyNFAy0111y

QQebPrkhbkQbjmibyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyWyQ^k^ofpyyNFAy005-y
>QebPqlkb@fo`ibyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyWyQ^k^ofpyyNFAy0111y

CO^q`ebqyKy?rihobhO^dbcfpq%2.+3)/2+1&yyWyQ^k^ofpyyNFAy0111y
@QebPqlkb@fo`ibyKyDbqqebPqlkb@fo`ibcoljqeb`ebpq%3/+2)05+2&yyWyQeb?^oobkpyyNFAy0111y

CD^adbqw^kyKy?o^dlh%30+.)0/+4&yyWyQeb?^oobkpyyNFAy0111y
QQebPqlkb@fo`ibyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyWyQ^k^ofpyyNFAy0111y
>FkqlqebAbmqepyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyWyQ^k^ofpyyNFAy0113y
>Pb`obqlcqeb@fo`ibyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyWyQ^k^ofpyyNFAy0114y

CO^`ebqyKy?rihobhO^dbcfpq%2.+3)/2+1&yyWyQ^k^ofpyyNFAy.1/1y
_?llqv?^vyKyQ^hbqeb_l^qql?llqv?^v%30+4)05+3&yyWyQeb?^oobkpyyNFAy.1/1y
c?llqv?^vyKyDofkdbo%/3+6)44+.&yyWyPqo^kdibqelokS^ibyyNFAy.1/1y
CDolj$dli?^pb@^jmyKyDofkdbo%/3+6)44+.&yyWyPqo^kdibqelokS^ibyyNFAy.1/1y
OArphtllayKyQo^sbiqlArphtlla%11+1)53+1&yyWyArphtllayyNFAy.1/1y
OAb^atfkaM^ppyKyQo^sbiqlAb^atfkaM^pp%0/+2)01+.&+Qovql^slfaA^opefobyyWyAb^atfkaM^ppyyNFAy.1/1y
OPqlk^oayKyQo^sbiqlPqlk^oa%13+.)21+5&yyWyPt^jmlcPlooltpyyNFAy.1/1y
cPqlk^oayKy?obvh%13+.)21+5&yyWyPt^jmlcPlooltpyyNFAy.1/1y

>MllilcQb^opyKyCbi$wbori%14+6)22&yyWyPt^jmlcPlooltpyyNFAy.1/1y
@MllilcQb^opyKyCfka2uX>q^i$^f>oqfc^`qZ^olrkaqebpt^jm%34+2)12+6&)%33+4)2.&)%33+2)26&)%4.+2)26&)%42)2.&yyWyPt^jmlcPlooltpyyNFAy.1/1y
QMllilcQb^opyKyCbi$wbori%14+6)22&yyWyPt^jmlcPlooltpyyNFAy.1/1y

>Qeb>q^i$^fBufibyKyCbi$wbori%14+6)22&yyWyPt^jmlcPlooltpyyNFAy.1/6y
CQ^oobkJfiiyKy?obvh%13+.)21+5&yyWyPt^jmlcPlooltpyyNFAy.111y
OQebEfkqboi^kapyKyQo^sbiqlQebEfkqboi^kap%.-)21+2&yyWyQebEfkqboi^kapyyNFAy.111y
QQeb>q^i$^fBufibyKy>q^i$^fBufib%00+4)42+/&yyWyQebEfkqboi^kapyyNFAy.1/6y
>ObqrokqlCbi$WboriyKy>q^i$^fBufib%00+4)42+/&yyWyQebEfkqboi^kapyyNFAy.111y
>G^jj^i$^kqebMolmebqyKy>q^i$^fBufib%00+4)42+/&yyWyQebEfkqboi^kapyyNFAy.113y

OObs^kqrphSfii^dbyKyQo^sbiqlO^sbkqrphSfii^db%45)5-&dlqeolrdeqebm^qe^q%4.+1)32&yyWyQebEfkqboi^kapyyNFAy452-y
cObs^kqrphSfii^dbyKyDloh^p%5.+4)5.+5&yyWyQebEfkqboi^kapyyNFAy452-y

eObs^kqrphSfii^dbyKyI^oa%45+.)5.+1&yyWyQebEfkqboi^kapyyNFAy452-y
>A^ohSbppbipyKyMofj^iQlokqrph%45+/)5.+0&yyNFAy452-yyWyQebEfkqboi^kapy
>Hfak^mmbaBiaboQlokqrphyKyMofj^iQlokqrph%45+/)5.+0&yyNFAy4512yyWyQebEfkqboi^kapy
>Gl_Lmbkfkd7Dr^oa@^mq^fklcObs^kqrphSfii^dbyKy@^iiql>ojp%46)46+.&yyNFAy453/yyWyQebEfkqboi^kapy
>T^kqba7SfibMofbpqbppEbuu^kaEboJfkflkpyKy@^iiql>ojp%46)46+.&yyNFAy453.yyWyQebEfkqboi^kapy
>Pbm^o^qflk>kufbqvyKyErkqpj^kJ^ohelo%46+.)46+3&yyNFAy4516yyWyQebEfkqboi^kapy

KDolrmfkdfpob`ljjbkabayKyQebpbnrbpq^obmlppf_ibqlplil^pibsbi15(_rqqovqldolrmtfqe^qib^pqlkblqebomboplkyyNFAy4516y

KDbqXErkqpj^kJ^ohelo$pPhriiZyKyXErkqpj^kJ^ohelo$pPhriiZ%25+3)31+6&yyNFAy4516yyIy.6-36yyWyQebEfkqboi^kapy
@Pbm^o^qflk>kufbqvyKyDbqXErkqpj^kJ^ohelo$p?lkbpZ%3/+/)42+2&yyNFAy4516yyIy.6-4-yyWyQebEfkqboi^kapy
@T^kqba7SfibMofbpqbppEbuu^kaEboJfkflkpyKyRpbqebXObpqlo^qfsbMlqflkZqlebimvlrhfiiSfibMofbpqbppEbuu%26)45&)vlrpelria_b^_ibqlplileboyyNFAy453.yyWyQebEfkqboi^kapyyRy6-0-y

QHfak^mmbaBiaboQlokqrphyKyBiaboQlokqrph%25+5)46+0&yyNFAy4512yyWyQebEfkqboi^kapy
>Ob`lsboqebHbvyKyBiaboQlokqrph%25+5)46+0&yyNFAy4513yyWyQebEfkqboi^kapy
@Ob`lsboqebHbvyKyHfiiEfq^e$v^qebHbbmbo%24+2)53+4&^kadbqqebXPe^`hibHbvZyyNFAy4513yyWyQebEfkqboi^kapy
@Qeb>k`fbkqBddyKyDbqqeb>k`fbkqBdd%24+2)53+4&yyNFAy1454yyWyQebEfkqboi^kapyyLy
QOb`lsboqebHbvyKyBiaboQlokqrph%25+5)46+0&yyNFAy4513yyWyQebEfkqboi^kapy
>ObqrokqlMofj^iQlokqrphyKyBiaboQlokqrph%25+5)46+0&yyNFAy4514yyWyQebEfkqboi^kapy

@Gl_Lmbkfkd7Dr^oa@^mq^fklcObs^kqrphSfii^dbyKyHfii^iiqebobnrfobaQoliipfkGfk$>iqeloyyNFAy453/yyWyQebEfkqboi^kapy
@A^ohSbppbipyKyDbq2uXSbppbilcQ^fkqba?illaZfqfpp`^qqboba^iilsboGfk$>iqeloyyNFAy452-yyWyQebEfkqboi^kapy

EObs^kqrphSfii^dbyRy3615yyNFAy/604y

QA^ohSbppbipyKyMofj^iQlokqrph%45+/)5.+0&yyNFAy452-yyWyQebEfkqboi^kapy
QGl_Lmbkfkd7Dr^oa@^mq^fklcObs^kqrphSfii^dbyKy@^iiql>ojp%46)46+.&yyNFAy453/yyWyQebEfkqboi^kapy
QT^kqba7SfibMofbpqbppEbuu^kaEboJfkflkpyKy@^iiql>ojp%46)46+.&yyNFAy453.yyWyQebEfkqboi^kapy
QPbm^o^qflk>kufbqvyKyErkqpj^kJ^ohelo%46+.)46+3&yyNFAy4516yyWyQebEfkqboi^kapy
QObqrokqlMofj^iQlokqrphyKyMofj^iQlokqrph%45+/)5.+0&yyNFAy4514yyWyQebEfkqboi^kapy

@PrjjlkfkdPe^ao^yKyVlrtfiikbba^dolrmqlhfiiqefp_lpp^pfqfp^ibsbi22BifqbKM@%01)40&)fcvlr$ob^_ibqlhfqbtbiivlr`^kplilfq+Vlr`^klkivprjjlkqebKM@lk`btfqeqebp`olii)vlrtfiie^sbqldbq^klqebop`oliicoljLodofjj^oqlobprjjlk+Fcvlralk$qe^sb^kvebimvlrtfiigrpqe^sbql^_^kalkqefpnrbpqyyRy60/0yyNFAy/604yyWyQebEfkqboi^kapy

QPrjjlkfkdPe^ao^yKy>mlqeb`^ovIvalk%3.+2).6+/&yyWyEfiip_o^aCllqefiipyyNFAy/604y
>SbkljqlqebRkabo`fqvyKy>mlqeb`^ovIvalk%3.+2).6+/&yyWyEfiip_o^aCllqefiipyyNFAy/605y

CRkabo`fqvyKyW^ofpb%3-+.).5+3&yyWyEfiip_o^aCllqefiipyyNFAy02/5y
QSbkljqlqebRkabo`fqvyKyJ^pqbo>mlqeb`^ovC^o^kbii%16+3)35+2&yyWyRkabo`fqvyyNFAy/605y

CRkabo`fqvyKyDloh^p%5.+4)5.+5&yyWyQebEfkqboi^kapyyNFAy02/5y
CLodofjj^oyKyQ^hbqebWbmmbifkqlLodofjj^o%3-+4)25+5&yyWyQfofpc^iDi^abpyyNFAy02/5y
eLodofjj^oyKyFkkhbbmboDovpeh^%21+.)35+1&yyWyLodofjj^oy
CD^adbqw^kyKyAlo^p%12+2)31&yyWyLodofjj^oyyNFAy02/5y
QQeb>k`fbkqBddyKyVbe$hfkv^%33+6)//+1&yyNFAy1454yyWyQ^k^ofpy
>QebDlaE^hh^oyKyVbe$hfkv^%33+6)//+1&yyNFAy02/5yyWyQ^k^ofpy
CO^q`ebqyKy?rihobhO^dbcfpq%2.+3)/2+1&yyWyQ^k^ofpyyNFAy.112y
_?llqv?^vyKyQ^hbqeb_l^qql?llqv?^v%30+4)05+3&yyWyQeb?^oobkpyyNFAy.112y
CPqlk^oayKyDofkdbo%/3+6)44+.&yyWyPqo^kdibqelokS^ibyyNFAy.112y

QObqrokqlCbi$WboriyKyCbi$wbori%14+6)22&yyWyPt^jmlcPlooltpyyNFAy.111y
>QebQbjmiblc>q^i$E^hh^oyKyCbi$wbori%14+6)22&yyWyPt^jmlcPlooltpyyNFAy.112y

OPrkhbkQbjmibyKyNrbrbcloPrkhbkQbjmibyyFyyNFAy0114y
@Pb`obqlcqeb@fo`ibyKy>`qfs^qbqebpq^qrbplkqeb/kacillofkqefploaboP)K)PT)PB)KT)KB)qebkvlre^sbqldl_^`haltkqlqeb_lqqljcillo)^dllafab^fpqle^sbbsbov_lavgrjmaltklkqeb_lqqljcillobu`bmqclo.mboplktel`^k^`qfs^qbqebi^pqpq^qrb)^kahfiiqeb_lppyyNFAy0114y
QPb`obqlcqeb@fo`ibyKyFalilcE^hh^oyyWyCbo^i^pyyNFAy0114y
QFkqlqebAbmqepyKyDlqlqeb_lqqljcillo^kaqrokfkqebnrbpqyyWyCbo^i^pyyNFAy0113y
@G^jj^i$^kqebMolmebqyKyQo^sbiqlqebkloqebokm^oqlcqebPrkhbkQbjmib^kahfii3>q^i^fAbcbkaboptef`ejrpq_babcb^qbaqlobjlsbqebclo`bcfbiaqebkHfiiG^jj^i$^kqebMolmebq^kaillqefpeb^a)ebfplkqebClroqecillolkqebsbovofdeqpfablcqebolljyyWyQebEfkqboi^kapyyNFAy.113y
@QebDlaE^hh^oyKyHfiiqeb>s^q^olcE^hh^o%qlprjjlkefjrpbqebXBddlcE^hh^oZlkqebqbjmibclroqecillolkqebIbcqPfablcqebj^mtfqefkqeb`fo`ib)Vlrjrpq^asfpbqebm^oqvqlillqbsbovKM@cloqeb_illa#`if`hlkqebci^jbp+EbaolmpXBppbk`blcE^hh^oZ+Ofdeq`if`hfqfkvlrofksbkqlovqlcfiiqebbddtfqeqebBppbk`blcE^hh^o+yyRy.-132yyNFAy02/5yyWyQ^k^ofpy
HPe^ablcBo^kfhrpyKyVlrjrpqabcb^qG^jj^i$^kqebMolmebq^kaqebqtlao^hbpqe^qpm^tk^cqbot^oapfkloaboqlcfdeqBo^kfhrp)j^hbprobvlr`ib^o^iiqebao^dlkpfkqebi^odbolljcfopq^pqebvtfii^ii^dolfcvlr^qq^`hBo^kfhrp+IllqXBppbk`blcBo^kfhrpZyyIy.-121yyNFAy0040y
>QebBppbk`blcBo^kfhrpyKyQebBppbk`blcBo^kfhrpyyLyyNFAy0040y
QQebBppbk`blcBo^kfhrpyKyDlqlqeb_^`h`lokbofkqebp^jbollj^pBo^kfhrpyyLyyNFAy0040y
@QebQbjmiblc>q^i$E^hh^oyKy/-XCbqfpebplcE^hh^oZfqaolmplcKM@pfkqebPrkhbkQbjmibyyWyPt^jmlcPlooltpyyNFAy.112y

OPqlk^oayKyQbibmloq_^`hqlPqlk^oa%14+6)22&yyWyPt^jmlcPlooltpyyFy
QQebQbjmiblc>q^i$E^hh^oyKyCbi$wbori%14+6)22&yyWyPt^jmlcPlooltpyyNFAy.112y

CQ^oobkJfiiyKy?obvh%13+.)21+5&yyWyPt^jmlcPlooltpy
OQebEfkqboi^kapyKyQo^sbiqlQebEfkqboi^kap%.-)21+2&yyWyQebEfkqboi^kapy
QG^jj^i$^kqebMolmebqyKy>q^i$^fBufib%00+4)42+/&yyWyQebEfkqboi^kapyyNFAy.113y

ELodofjj^oyRy3615y
CD^adbqw^kyKyAlo^p%12+2)31&yyWyLodofjj^oyyNFAy02/5y
QQebDlaE^hh^oyKyVbe$hfkv^%33+6)//+1&yyNFAy02/5yyWyQ^k^ofpy

KDrfab@ljmibqb+@lkqfkrbQl?i^`hol`hAbmqep%2/*22&yKyQf`hql`lkqfkrbql?i^`hol`hAbmqep%2/*22&*Riqfj^qbTlTDrfab+`ljy

]]
end)
