DugisGuideViewer:RegisterGuide("Blackrock Depths: Prison (52-55)", "Scholomance / Stratholme (55-58)", "Horde", "I", function()
return [[
AAA

KIbsbi2/ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi2/qlmf`hrmqebcliiltfkdnrbpqpyyNFAy065.yyMIy2/y

OH^od^qeyKyQo^sbiqlH^od^qe%1)13&yyWy?^ai^kapyyNFAy065.y

>HFIILKPFDEQ7A^ohFolkAt^osbpyKyT>KQBA%0+5)14+2&yyWy?^ai^kapyyNFAy1-5.y
>Afpe^ojlkvlcCi^jbyKyQerkaboeb^oq%0+2)15+/&yyNFAy06-3yyWy?^ai^kapy

OQelofrjMlfkqyKyOrkqlQelofrjMlfkq%01+6)0-+5&yyWyPb^ofkdDlodbyyNFAy1-/0y
cQelofrjMlfkqyKyDofpeh^%01+6)0-+5&yyWyPb^ofkdDlodbyyNFAy1-/0y

O?i^`hol`hJlrkq^fkyKyQo^sbiql?i^`hol`hJlrkq^fk%01+55)51+5&yyWyPb^ofkdDlodbyyNFAy1-/0y
@Afpe^ojlkvlcCi^jbyKyHfiiLsboj^pqboMvolk%/3+11)46+1&)vlr`^kbfqebogrjmaltkqlqebi^s^locliiltqeb@e^fkqlqebjfaaibpqor`qrob^kaaltkqlqebjfkbpyyNFAy06-3yyWyPb^ofkdDlodby

O?rokfkdPqbmmbpyKyQo^sbiql?rokfkdPqbmmbp%0/+6)2.+5&yyWy?rokfkdPqbmmbpyyNFAy1-/0y

>>Q^pqblcCi^jb%M^oq.&yKy@vorpQebobmbkqlrp%62+-)0.+3&yyNFAy1-/0yyWy?rokfkdPqbmmbpy
@>Q^pqblcCi^jb%M^oq.&yKyPmb^hql@vorpQebobmbkqlrp%62+-)0.+3&^kaebtfiiprjjlk^ao^dlkclovlrqlabcb^q^kaillqqebX?i^`hAo^dlkcifdeqJliqZclomollcyyNFAy1-/0yyWy?rokfkdPqbmmbpy
Q>Q^pqblcCi^jb%M^oq.&yKy@vorpQebobmbkqlrp%62+-)0.+3&yyNFAy1-/0yyWy?rokfkdPqbmmbpy
>>Q^pqblcCi^jb%M^oq/&yKy@vorpQebobmbkqlrp%62+-)0.+3&yyNFAy1-/1yyWy?rokfkdPqbmmbpy

c?rokfkdPqbmmbpyKyS^edorh%32+4)/1+/&yyWy?rokfkdPqbmmbpyyNFAy06-4y
CH^od^qeyKyS^edorh%32+4)/1+/&yyWy?rokfkdPqbmmbpyyNFAy06-4y
QAfpe^ojlkvlcCi^jbyKyQerkaboeb^oq%0+2)15+/&yyNFAy06-3yyWy?^ai^kapy

>Afpe^ojlkvlcCfobyKyQerkaboeb^oq%0+2)15+/&yyNFAy06-4yyWy?^ai^kapy
>@ljj^kaboDlo$pe^hyKyD^i^j^sqebJ^ohpj^k%2+6)14+4&yyWy?^ai^kapyyNFAy065.y

KNrbrbclo?i^`hol`hAbmqep*MofplkyKyRpbqebarkdblkcfkaboqlNrbrbclo?i^`hol`hAbmqep)t^fqfkH^od^qerkqfivlrdbqqebnrbrbyyNFAy065/yyFy

HEfdeFkqboold^qloDbopq^ekyKyHfiiEfdeFkqboold^qloDbopq^ek)coljqebbkqo^k`bpebfplkqebofdeqpfabKloqeB^pq^kadbqqebhbvcoljeboyyIy...1-yyNFAy065/y

Q@ljj^kaboDlo$pe^hyKyCobb@ljj^kaboDlo$pe^h)>cqbovlrbkqbo?OA)t^ihclot^oafkqlqebj^fkollj)qebkillhqlvlroofdeq+Vlr$iipbbqeobbm^qet^vp+Qeblrqboqtlillm^olrkaqlb^`elqebofk^_fdofkd+Dlo$Pe^hfpfk^`biilkqebibcqpfab+ii)vlr$iikbbaqebhbvcoljEfdeFkqboold^qloDbopq^ek+yyNFAy065.y
>Te^qFpDlfkdLk<%M^oq.&yKy@ljj^kaboDlo$pe^hyyNFAy065/y
@Te^qFpDlfkdLk<%M^oq.&yKyBp`loq^kaabcbka@ljj^kaboDlo$pe^hyyNFAy065/y
QTe^qFpDlfkdLk<%M^oq.&yKy@ljj^kaboDlo$pe^hyyNFAy065/y
>Te^qFpDlfkdLk<%M^oq/&yKy@ljj^kaboDlo$pe^hyyNFAy1--.y
@Te^qFpDlfkdLk<%M^oq/&yKyQ^ihqlHe^o^kJfdeqe^jjbo)fkqeb`bii^`olpp^kaqlqebibcqlc@ljj^kaboDlo$pe^h$p@bii+yyNFAy1--.y
@HFIILKPFDEQ7A^ohFolkAt^osbpyKyHfii.2>ksfio^dbDr^oapjbk).->ksfio^dbT^oabkp^ka2>ksfio^dbCllqjbk+Vlrpelria_b^_ibql`ljmibqbqefpnrf`hivfkqebmofplk^ob^yyNFAy1-5.y

KIl`hmf`hfkdloPe^altclodbHbv<yKy@^k^kvlkbfkvlrodolrmlmbkqebil`hbaalloptfqeil`hmf`hfkdlope^altclodbhbv<Fckllkb`^k)ib^sbqebm^oqv^kaglfk^kbtdolrmqe^qe^sbqebhbvloil`hmf`hfkd+Vlrtlk$qdbqabpboqboab_rcc^pilkd^pEfdeFkqboold^qloDbopq^ekfpab^ayyNFAy1-5/y
OH^od^qeyKyQbiivlrom^oqvqe^qvlrtfii_bofdeq_^`hqlqrokfk^nrbpq+ofdeq`if`hlkqebarkdblkf`lklk_vvlrojfkfj^m^kaqbibmloqlrqqlH^od^qe^kanrf`hivqrokfk$HFIILKPFDEQ7A^ohFolkAt^osbp$^ka^``bmqqebkbuqnrbpq%2+5)14+2&yyWy?^ai^kapyyNFAy1-5/yyFy

QHFIILKPFDEQ7A^ohFolkAt^osbpyKyT^oiloaDlobqllqe%2+5)14+2&yyNFAy1-5.yyWy?^ai^kapy
>HFIILKPFDEQ7EfdeO^khfkdA^ohFolkLccf`f^ipyKyT^kqbaPfdk%1)14&yyNFAy1-5/yyWy?^ai^kapy

O?i^`hol`hAbmqepyKyRpbqebarkdblkcfkaboqlobglfkvlrodolrmfk?i^`hol`hAbmqepyyNFAy1-/1yyFy

H?^bi$D^oyKyFcpljblkbfkvlrom^oqv`^krkil`hqeballop)Hfii?^bi$D^o^kaillqXBk`^pbaCfbovBppbk`bZ_vrpfkdqebX>iqboba?i^`hAo^dlkcifdeqJliqZyyNFAy1-/1yyIy../0-yyRy../0.y
@>Q^pqblcCi^jb%M^oq/&yKyFcpljblkbfkvlrom^oqv`^krkil`hqeballop)Hfii?^bi$D^o^kaillqXBk`^pbaCfbovBppbk`bZ_vrpfkdqebX>iqboba?i^`hAo^dlkcifdeqJliqZyyNFAy1-/1yyIy.../3y
HIloaFk`bkafrpyKyCliiltqebi^odbe^iit^vcolj?^bi$D^opqo^fdeqqlIloaFk`bkafrp^kaillqXQ^_ibqlcHrokfv^ZyyNFAy06-4y
@HFIILKPFDEQ7EfdeO^khfkdA^ohFolkLccf`f^ipyKy>iiqebKM@obnrfoba^oblkqebt^vql?^bi$D^ovlrpelria^rqlj^qf`iv`ljmibqbqefpyyNFAy1-5/yyWy?^ai^kapy

OH^od^qeyKyQbibmloq_^`hqlH^od^qe%0+2)15+/&yyWy?^ai^kapyyFy

QAfpe^ojlkvlcCfobyKyQerkaboeb^oq%0+2)15+/&yyNFAy06-4yyWy?^ai^kapy
QHFIILKPFDEQ7EfdeO^khfkdA^ohFolkLccf`f^ipyKyT^oiloaDlobqllqe%1)14&yyNFAy1-5/yyWy?^ai^kapy

C?rokfkdPqbmmbpyKyDloofh%1)11+5&yyWy?^ai^kapy
Q>Q^pqblcCi^jb%M^oq/&yKy@vorpQebobmbkqlrp%62+-)0.+3&yyNFAy1-/1yyWy?rokfkdPqbmmbpy

ELodofjj^oyRy3615y
QTe^qFpDlfkdLk<%M^oq/&yKyQeo^ii%0.+3)04+5&+yyWyLodofjj^oyyNFAy1--.y

KDrfab@ljmibqb+@lkqfkrbQlP`elilj^k`b,Pqo^qelijb%22*25&yKyQf`hql`lkqfkrbqlP`elilj^k`b,Pqo^qelijb%22*25&*Riqfj^qbTlTDrfab+`ljy

]]
end)
