DugisGuideViewer:RegisterGuide("Hellfire Ramparts / The Blood Furnace (58-62)", "The Slave Pens / The Underbog (62-65)", "Horde", "I", function()
return [[
AAA

KIbsbi25ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi25qlmf`hrmqebcliiltfkdnrbpqpyyNFAy61-4yyMIy25y
ORkabo`fqvyKyQo^sbiqlRkabo`fqv%33)1/&yyWyRkabo`fqvyyNFAy61-4y
O?i^pqbaI^kapyKyQ^hbqebmloq^iql?i^pqbaI^kapcoljRkabo`fqv%52+0).4+.&yyWyRkabo`fqvyyNFAy61-4y

>QeolrdeqebA^ohMloq^iyKyT^oiloaA^o$qllk%25+.)22+6&yyWy?i^pqbaI^kapyyNFAy61-4y
OEbiicfobMbkfkpri^yKyOrkqeolrdeqlqebA^ohMloq^iqlEbiicfobMbkfkpri^%25+4)3-+0&yyNFAy61-4yyWy?i^pqbaI^kapy
QQeolrdeqebA^ohMloq^iyKyIfbrqbk^kqDbkbo^iLoflk%54+1)16+5&yyWyEbiicfobMbkfkpri^yyNFAy61-4y

>>oofs^ifkLrqi^kayKyIfbrqbk^kqDbkbo^iLoflk%54+1)16+5&yyWyEbiicfobMbkfkpri^yyNFAy.-./-y
Q>oofs^ifkLrqi^kayKySi^dd^Cobvcb^qebo%54+1)15+/&yyWyEbiicfobMbkfkpri^yyNFAy.-./-y

>GlrokbvqlQeo^iij^oyKySi^dd^Cobvcb^qebo%54+1)15+/&yyWyEbiicfobMbkfkpri^yyNFAy.-/56y
CQeo^iij^oyKySi^dd^Cobvcb^qebo%54+1)15+/&yyNFAy.-/56y
QGlrokbvqlQeo^iij^oyKyDbkbo^iHo^hloh%22+6)03+6&yyWyEbiicfobMbkfkpri^yyNFAy.-/56y

>ObmloqqlK^wdobiyKyDbkbo^iHo^hloh%22+6)03+6&yyWyEbiicfobMbkfkpri^yyNFAy.-/6.y
QObmloqqlK^wdobiyKyK^wdobi%22+-)03+-&yyWyEbiicfobMbkfkpri^yyNFAy.-/6.y
>Bo^af`^qbqeb?rokfkdIbdflkyKyK^wdobi%22+-)03+-&yyWyEbiicfobMbkfkpri^yyNFAy.-./.y
eQeo^iij^oyKyCilvaMfkhrp%23+0)03+2&yyNFAy.-./0y
QBo^af`^qbqeb?rokfkdIbdflkyKyPbodb^kqPe^qqbophrii%25+-)1.+0&yyWyEbiicfobMbkfkpri^yyNFAy.-./.y

>Cbipm^ohO^sfkbyKyPbodb^kqPe^qqbophrii%25+-)1.+0&yyWyEbiicfobMbkfkpri^yyNFAy.-./0y
@Cbipm^ohO^sfkbyKyHfii1Ci^jbt^hboFjmp)3Fkcbok^iT^o_ofkdbop^ka.Aob^a`^iibo^iiclrka^olrka%30)02&yyWyEbiicfobMbkfkpri^yyNFAy.-./0y
QCbipm^ohO^sfkbyKyPbodb^kqPe^qqbophrii%25+-)1.+0&yyWyEbiicfobMbkfkpri^yyNFAy.-./0y

>Clot^oa?^pb7Ob^sbo$pC^iiyKyPbodb^kqPe^qqbophrii%25+-)1.+0&yyWyEbiicfobMbkfkpri^yyNFAy.-./1y
@Clot^oa?^pb7Ob^sbo$pC^iiyKyObmloqqlClot^oa@ljj^kaboQl$^o`e^qOb^sbo$pC^ii%32+6)10+3&yyWyEbiicfobMbkfkpri^yyNFAy.-./1y
QClot^oa?^pb7Ob^sbo$pC^iiyKyClot^oa@ljj^kaboQl$^o`e%32+6)10+3&yyWyEbiicfobMbkfkpri^yyNFAy.-./1y

>AfpormqQebfoObfkclo`bjbkqpyKyClot^oa@ljj^kaboQl$^o`e%32+6)10+3&yyWyEbiicfobMbkfkpri^yyNFAy.-/-5y
@AfpormqQebfoObfkclo`bjbkqpyKy@liib`qAbjlkf`OrkbPqlkbpcfopq+Fqq^hbpclropqlkbpmbomloq^iqlabpqolvqebj+Vlr$iikbbaqlpq^kafkqebsbovjfaaiblcqebmloq^i%lkqeb_irb^ob^&^kaofdeq*`if`hfq+RpbXQl$^o`e$pMofjbopZlkMloq^iUfirp^q%4-)12&^kaMloq^iHorri^q%41)05&yyRy/5145yyWyEbiicfobMbkfkpri^yyNFAy.-/-5y
QAfpormqQebfoObfkclo`bjbkqpyKyClot^oa@ljj^kaboQl$^o`e%32+6)10+3&yyWyEbiicfobMbkfkpri^yyNFAy.-/-5y

>Jfppflk7D^qbt^vpJrohbqe^kaPe^^ao^wyKyClot^oa@ljj^kaboQl$^o`e%32+6)10+3&yyWyEbiicfobMbkfkpri^yyNFAy.-./6y
@Jfppflk7D^qbt^vpJrohbqe^kaPe^^ao^wyKyQ^ihqlTfkd@ljj^kabo?o^`h%33+.)10+5&ebqebkcifbpvlr^olrka/qltbop)grpqofdeq`if`hqeb_lj_^kaibcq`if`hrkaboqebqltboyyRy/5-05yyWyEbiicfobMbkfkpri^yyNFAy.-./6y
QJfppflk7D^qbt^vpJrohbqe^kaPe^^ao^wyKyClot^oa@ljj^kaboQl$^o`e%32+6)10+3&yyWyEbiicfobMbkfkpri^yyNFAy.-./6y

>Jfppflk7Qeb>_vpp^iPebicyKyClot^oa@ljj^kaboQl$^o`e%32+6)10+3&yyWyEbiicfobMbkfkpri^yyNFAy.-.3/y
@Jfppflk7Qeb>_vpp^iPebicyKyRpbX>ob^2/Pmb`f^iZqlhfii/-D^k$^odMblkp)2Jl$^odLsbopbbop^ka2Cbi@^kklkp+Qeb_lj_pe^sb^mobqqv_fd^ob^lcbccb`q)plfq$p_bpqql^fj^qqebLsboiloaplo@^kklkpqldbqfqalkbc^pq)qebmblkp^ob^it^vpfkqebt^v^ka^obb^pvqlefq+Vlr`^kdl_^`hclo^pb`lkaork^kacfkfpetfqeklmbk^iqvyyRy/5.0/yyWyEbiicfobMbkfkpri^yyNFAy.-.3/y
QJfppflk7Qeb>_vpp^iPebicyKyClot^oa@ljj^kaboQl$^o`e%32+6)10+3&yyWyEbiicfobMbkfkpri^yyNFAy.-.3/y

QObqrokqlQeo^iij^oyKyK^wdobi%22+-)03+-&yyNFAy.-055yyWyEbiicfobMbkfkpri^y
>Clodb@^jm7J^dbaalkyKyK^wdobi%22+-)03+-&yyNFAy.-06-yyWyEbiicfobMbkfkpri^y
>?lkb`ebtbo?illayKySroqlh>ub_ob^hbo%22+.)03+0&yyNFAy.-12-yyWyEbiicfobMbkfkpri^y
>FTloh+++CloqebEloabyKyJbdwbdKrhhib_rpq%22+/)05+5&yyNFAy.--53yyWyEbiicfobMbkfkpri^y
HO^wlop^tyKyHfiiO^wlop^t^olrka%32)0/&^kaillqX?rokfkdIbdflkJfppfsbZyyIy/6255yyNFAy.-06-yyWyEbiicfobMbkfkpri^y
@Clodb@^jm7J^dbaalkyKyHfii.-D^k$^odPbos^kqp^kaO^wlop^t%32)0/&^qClodb@^jm7J^dbaalk%31)0/&yyNFAy.-06-yyWyEbiicfobMbkfkpri^y
>SfibMi^kpyKyPq^oqpcoljX?rokfkdIbdflkJfppfsbZ)aolmmba_vO^wlop^tyyNFAy.-060yyRy/6255yyWyEbiicfobMbkfkpri^y
QSfibMi^kpyKyJ^dfpqbo?illae^th%22+.)03+-&yyNFAy.-060yyWyEbiicfobMbkfkpri^y
QClodb@^jm7J^dbaalkyKyK^wdobi%22+-)03+-&yyNFAy.-06-yyWyEbiicfobMbkfkpri^y
>@^kklkplcO^dbyKyK^wdobi%22+-)03+-&yyNFAy.-06.yyWyEbiicfobMbkfkpri^y
@@^kklkplcO^dbyKyAbpqolv0Cbi@^kklkJHFpfkClodb@^jm7O^db%25)0.&yyNFAy.-06.yyWyEbiicfobMbkfkpri^y
Q@^kklkplcO^dbyKyK^wdobi%22+-)03+-&yyNFAy.-06.yyWyEbiicfobMbkfkpri^y
>Allot^vqlqeb>_vppyKyK^wdobi%22+-)03+-&yyNFAy.-06/yyWyEbiicfobMbkfkpri^y
@Allot^vqlqeb>_vppyKyHfii>ofu$>j^i%20)/3&cloqebX?rokfkdIbdflkD^qbHbvZ)^karpbfqlkqeb?rokfkdIbdflkD^qb%20)/5&yyNFAy.-06/yyRy/6462yyWyEbiicfobMbkfkpri^y
QAllot^vqlqeb>_vppyKyK^wdobi%22+-)03+-&yyNFAy.-06/yyWyEbiicfobMbkfkpri^y

@?lkb`ebtbo?illayKyHfiiqeb?lkb`ebotboLo`pgrpqplrqelcQeo^iij^oclo./X?lkb`ebtbo?illaZ%25)13&yyNFAy.-12-yyWyEbiicfobMbkfkpri^y
@FTloh+++CloqebEloabyKyD^qebo5mfb`bplcXP^is^dbaJbq^iZ^ka5mfb`bplcXP^is^dbaTllaZ%22+/)00+5&yyNFAy.--53yyWyEbiicfobMbkfkpri^y

QFTloh+++CloqebEloabyKyJbdwbdKrhhib_rpq%22+/)05+5&yyNFAy.--53yyWyEbiicfobMbkfkpri^y
>?rokFqRm+++CloqebEloabyKyJbdwbdKrhhib_rpq%22+/)05+5&yyNFAy.--54yyWyEbiicfobMbkfkpri^y
Q?lkb`ebtbo?illayKySroqlh>ub_ob^hbo%22+.)03+0&yyNFAy.-12-yyWyEbiicfobMbkfkpri^y
@?rokFqRm+++CloqebEloabyKyRpbqebXCi^jfkdQlo`eZqlabpqolvqebqtl`^kklkplkqebplrqepfablcqebM^qelcDilov%3-+6)2/+2&%21+3)21+.&yyNFAy.--54yyRy/4146yyWyEbiicfobMbkfkpri^y
Q?rokFqRm+++CloqebEloabyKyJbdwbdKrhhib_rpq%22+/)05+5&yyNFAy.--54yyWyEbiicfobMbkfkpri^y

KIbsbi26ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi26qlmf`hrmqebcliiltfkdnrbpqpyyNFAy624/yyMIy26y
>Tb^hbkqebO^jm^oqpyKyPqlkbDr^oaPqlh$qlk%22+/)03+.&yyWyEbiicfobMbkfkpri^yyNFAy624/y
OEbiicfobO^jm^oqpyKyRpbqebarkdblkcfkaboqlnrbrbcloEbiicfob7O^jm^oqpyyNFAy624/yyFy
@Tb^hbkqebO^jm^oqpyKyHfii^ii0_lppbp^kaillqXD^odlij^o$pE^kaZ)XLjlo$pEllcZ^kaXK^w^k$pEb^aZyyNFAy624/y
HS^worabkyKyHfiiS^worabkqebcfk^i_lpplcEbiicfobO^jm^oqp^kaillqXLjfklrpIbqqboZyyIy/056/yyNFAy626-y
>A^ohQfafkdpyKyPq^oqptfqenrbpqfqbjXLjfklrpIbqqboZaolmmba_vS^worabkyyNFAy6255yyRy/056/y

OQeo^iij^oyKyQbibmloq_^`hqlQeo^iij^o%22+-)03+-&yyWyEbiicfobMbkfkpri^yyNFAy626-yyFy
QA^ohQfafkdpyKyK^wdobi%22+-)03+-&yyWyEbiicfobMbkfkpri^yyNFAy6255y
QTb^hbkqebO^jm^oqpyKy@^w^$obw%21+6)03+-&yyWyEbiicfobMbkfkpri^yyNFAy624/y
>Qeb?illafpIfcbyKy@^w^$obw%21+6)03+-&yyWyEbiicfobMbkfkpri^yyNFAy626-y
>Eb^oqlcO^dbyKy@^w^$obw%21+6)03+-&yyWyEbiicfobMbkfkpri^yyNFAy63-5y

OQeb?illaCrok^`byKyRpbqebarkdblkcfkaboqlnrbrbcloQeb?illaCrok^`byyNFAy63-5yyFy
@Eb^oqlcO^dbyKyTebkvlrt^ihfkqlqebcfk^iolljqebnrbpqfp`ljmibqba)vlralklqe^sbqlhfiiqebi^pq_lppyyWyEbiicfobMbkfkpri^yyNFAy63-5y
@Qeb?illafpIfcbyKyDbq.-XCbiLo`?illaSf^ipZ^q?illaCrok^`byyNFAy626-y

OQeo^iij^oyKyBufq_^`hqlQeo^iij^o%22+-)03+-&yyWyEbiicfobMbkfkpri^yyFy
QEb^oqlcO^dbyKyK^wdobi%22+-)03+-&yyWyEbiicfobMbkfkpri^yyNFAy63-5y
QQeb?illafpIfcbyKy@^w^$obw%21+6)03+-&yyWyEbiicfobMbkfkpri^yyNFAy626-y

KDrfab@ljmibqb+@lkqfkrbQlQebPi^sbMbkp,QebRkabo_ld%3/*32&yKyQf`hql`lkqfkrbqlQebPi^sbMbkp,QebRkabo_ld%3/*32&*Riqfj^qbTlTDrfab+`ljy

]]
end)
