DugisGuideViewer:RegisterGuide("The Slave Pens / The Underbog (62-65)", "Mana-Tombs / Auchenai Crypts (64-67)", "Horde", "I", function()
return [[
AAA

KIbsbi3.ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi3.qlmf`hrmqebcliiltfkdnrbpqpyyNFAy64-.yyMIy3.y

K@liib`qXDilt`^mpZ^pvlrnrbpq++yKyIllq^kvXDilt`^mpZvlrcfka)vlr$iikbbaqebjcloobmrq^qflkyyNFAy64-.y
>QebPmlobifkdp$MifdeqyKyC^eppk%.6)31&yyNFAy6406yyWyW^kd^oj^opey
>K^qro^iBkbjfbpyKyC^eppk%.6)31&yyNFAy6410yyWyW^kd^oj^opey
@QebPmlobifkdp$MifdeqyKyIllq.-XJ^qrobPmlobP^`pZtef`e`^k_bclrka^iilsboqebPmt^kfkdDibk%.3)3-&yyNFAy6406yyWyW^kd^oj^opey
@K^qro^iBkbjfbpyKyHfiiqeb?ldIloap^qqebPm^tkfkdDibk%.2)3-&clo3X?ldIloaQbkaofipZyyNFAy6410yyWyW^kd^oj^opey
QQebPmlobifkdp$MifdeqyKyC^eppk%.6)31&yyNFAy6406yyWyW^kd^oj^opey
QK^qro^iBkbjfbpyKyC^eppk%.6)31&yyNFAy6410yyWyW^kd^oj^opey
KKbrqo^i*Pmlobdd^oyKyQebkbuqnrbpqobnrfobpvlrql_bKbrqo^itfqePmlobdd^o)Fcvlr$obklqnrfqbKbrqo^ivbqhfiijlob?ldIloapyyNFAy66.6y
>Pmlobdd^oyKyC^eppk%.6)31&yyNFAy66.6yyWyW^kd^oj^opey
QPmlobdd^oyKyJppef$ck)fkPmlobdd^o)grpqkloqe*b^pqlcqebPm^tkfkdDibk%.6)2.&yyNFAy66.6yyWyW^kd^oj^opey

KIbsbi3/ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi3/qlmf`hrmqebcliiltfkdnrbpqpyyNFAy6405yyMIy3/y
>Dilt`^mJrpeolljpyKyJppef$ck%.6+3)2/&yyNFAy65-5yyWyW^kd^oj^opey
@Dilt`^mJrpeolljpyKyD^qebo.-XDilt`^mpZtef`e`^k_bclrka^iilsboW^kd^oj^ope)alqov%0-)02&fcvlre^sbmol_ibjpcfkafkdqebjyyNFAy65-5yyWyW^kd^oj^opey
QDilt`^mJrpeolljpyKyJppef$ck%.6+3)2/&yyNFAy65-5yyWyW^kd^oj^opey
>CboqfibPmlobpyKyDpe^cc%.6+/)16+2&yyNFAy65-3yyWyW^kd^oj^opey
QCboqfibPmlobpyKyDpe^cc%.6+/)16+2&+D^qebo3XCboqfibPmlobpZfcvlralk$qe^sbqebj^iob^av+Qebvaolmlccpmlob_^qp^kaj^opet^ihbopyyNFAy65-3yyWyW^kd^oj^opey
KCofbkaiv*Pmlobdd^oyKy@ljmibqbbsbovobmb^q^_ibvlr`^krkqfivlr$obcofbkaiv+Vlr`^kqrokfkXDilt`^mpZ)X?ldIloaQbkaofipZ^kaXJ^qrobPmlobp^`pZ+>iiqebpbobmb^qpbkalk`bvlr$obcofbkaiv)plrpbqebjtefibvlr`^kyyNFAy64/3y

>Ilpqfk>`qflkyKyT^q`eboGe^kd%2/+0)03+-&Ptfjaltkqebmfmb^q%2-+0)1-+6&yyWyW^kd^oj^opeyyNFAy6405y

OPi^sbMbkpyKyNrbrbcloPi^sbMbkptfqevlroArkdblkCfkaboyyNFAy64.2yyFy

KCfkaTbbaboDobbkqerj_yKyCfkaTbbaboDobbkqerj_)obcboqlvlronrbpqqo^`hbo)ebfprm^i^odbo^jm^cqbovlrgrjmlcc^altkt^oapilmfkdo^jmfk^mllilct^qbo^_lrq.,/t^vfkqlPi^sbMbkpyyNLyTbbaboDobbkqerj_Afp`lsbobayyNFAy6405y
KCfkaK^qro^ifpq?fqbyKyCfkaK^qro^ifpq?fqb)obcboqlvlronrbpqqo^`hbo)Eb$pfk^`^db_bclobqebi^pq_lpp)obp`rbefj^ka0KM@$ptfiipm^tkyyNLyK^qro^ifpq?fqbAfp`lsbobayyNFAy6405y

OW^kd^oj^opeyKyQbibmloq_^`hqlW^kd^oj^ope%.6+2)2-+.&yyWyW^kd^oj^opeyyFyyNFAy64.2y

KIbsbi30ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi30qlmf`hrmqebcliiltfkdnrbpqp)`ljb_^`hqlqefpi^qbofcvlr$obklqefdebklrdeyyNFAy64.2yyMIy30y
>?ofkdJb>Peor__bovyKyDwerk$qq%.6+2)2-+.&yyNFAy64.2yyWyW^kd^oj^opey
>Le)Fq$pLkyKyQ$per%.6+0)16+6&yyNFAy64.4yyWyW^kd^oj^opey
>Pq^ihqebPq^ihboyKyHek$kfu%.6+3)16+5&yyNFAy64.6yyWyW^kd^oj^opey

ORkabo_ldyKyNrbrbcloRkabo_ldtfqevlroArkdblkCfkaboyyNFAy64.4yyFy
@Le)Fq$pLkyKy>cqbovlrhfiiqebcfopq_lpp)dbq^kXRkabopmlobColkaZ+Fq$pclrkagrpq_befkaErkd^ocbk+Fqfp^sbovq^iiqeloksfkb,_rpe+B^pvqljfppyyNFAy64.4y
KCfkaB^oqe_fkaboO^vdbyKy>cqbovlrhfiiDe^w$^k)ptfj^`olppqebt^qbo+Grjmaltkqlqebdolrka_bilt+Cliiltqebol^aqlqebibcqALKLQdlaltkqlqebcfopqofdeq_rq`lkqfkrbrmqltebobqebol^apb^jpqle^sb^kbka^kaeb^afkdrmt^oap^_fq+Ebtfii_bpq^kafkdebobpqb^iqebayyNLyB^oqe_fkaboO^vdbAfp`lsbobayyNFAy6405y
KCfkaTfka`^iibo@i^tyKyTfka`^iibo@i^tfptfqeqeb0oa_lppPt^jmiloaJrpbi$bh)lk`bvlrabcb^qefj)efpmbq_b^otfiiqo^kpcloaqlTfka`^iibo@i^tyyNLyTfka`^iibo@i^tAfp`lsbobayyNFAy6405y
@Pq^ihqebPq^ihboyKyDbqqebX?o^fklcqeb?i^`hPq^ihboZfqfpqebcfk^i_lppyyNFAy64.6y
@?ofkdJb>Peor__bovyKyDbq2XP^kdrfkbEf_fp`rpZqebpbaolmlcKM@^ka^iplclrkap`^qqbobafkRkabo_ldyyNFAy64.2y

OW^kd^oj^opeyKyQbibmloq_^`hqlW^kd^oj^ope%2/+0)03+-&yyWyW^kd^oj^opeyyFy

QIlpqfk>`qflkyKyT^q`eboGe^kd%2/+0)03+-&yyWyW^kd^oj^opeyyNFAy6405y
Q?ofkdJb>Peor__bovyKyDwerk$qq%.6+2)2-+.&yyWyW^kd^oj^opeyyNFAy64.2y
QLe)Fq$pLkyKyQ$per%.6+0)16+6&yyWyW^kd^oj^opeyyNFAy64.4y
QPq^ihqebPq^ihboyKyHek$kfu%.6+3)16+5&yyWyW^kd^oj^opeyyNFAy64.6y

KDrfab@ljmibqb+@lkqfkrbQlJ^k^*Qlj_p,>r`ebk^f@ovmqp%31*34&yKyQf`hql`lkqfkrbqlJ^k^*Qlj_p,>r`ebk^f@ovmqp%31*34&*Riqfj^qbTlTDrfab+`ljy

]]
end)
