DugisGuideViewer:RegisterGuide("Mana-Tombs / Auchenai Crypts (64-67)", "Old Hillsbrad Foothills (66-68)", "Horde", "I", function()
return [[
AAA

>>$a^iyKyVlr$obillhfkdclo^E^dd^oaT^oSbqbo^k%25+2)1.&)ebpelria_bc^foivb^pvqlcfkakb^oqeb`bkqbolcqeb`fqvyyWyPe^qqo^qe@fqvyyNFAy.-/.-y
Q>$a^iyKy>$a^i%21)11+2&yyWyPe^qqo^qe@fqvyyNFAy.-/.-y
>@fqvlcIfdeqyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-/..y
Q@fqvlcIfdeqyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-/..y
K>ialoloP`ovbopyKyVlrkbbaqlmf`htef`ec^`qflkvlrtfiid^fkobmrq^qflktfqe)fkTLQIHfqalbpk$qob^iivj^qqbotef`elkbvlr`ellpb^pvlrtlk$q_brpfkdqebobmrq^qflkclo^kvqefkd)?rqFprddbpq>ialo^pqebvtfiie^sbjlobnrbpqpclobuqo^bumbofbk`b^kavlr`^k^``bppK^do^kacoljqeb>ialoqrkkbilkqebTbpqpfabyyNFAy.-6.4y

Q>iibdf^k`bqlqeb>ialoyKyHe^ad^o%21+4)11+1&yyLyyWyPe^qqo^qe@fqvyyNFAy.-22.y
>Fpe^k^eyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-221y
QFpe^k^eyKyFpe^k^e%/1+/)/6+2&yyWyPe^qqo^qe@fqvyyNFAy.-221y

Q>iibdf^k`bqlqebP`ovbopyKyHe^ad^o%21+4)11+1&yyLyyWyPe^qqo^qe@fqvyyNFAy.-22/y
>Slobk$qe^iqebPbboyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-220yyLy
QSlobk$qe^iqebPbboyKySlobk$qe^iqebPbbo%1/+4)6.+2&yyWyPe^qqo^qe@fqvyyNFAy.-220yyLy

KIbsbi31ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi31qlmf`hrmqebcliiltfkdnrbpqpyyNFAy.-//4yyMIy31y
>FPbbAb^aAo^bkbfyKyE^$ibf%02+.)32+/&yyNFAy.-//4yyWyQbolhh^oClobpqy
QFPbbAb^aAo^bkbfyKyO^jaloqebJ^a%02+.)33+/&yyNFAy.-//4yyWyQbolhh^oClobpqy
>BwbhfbiyKyO^jaloqebJ^a%02+.)33+/&yyNFAy.-//5yyWyQbolhh^oClobpqy
QBwbhfbiyWyPe^qqo^qe@fqvyyKyBwbhfbi%2-+2)01)2&%13+6)15+/&%20+5)23+5&%3.+2)16+4&%3/)1-&%23+3)00+3&t^ihfkdfk`fo`ibplkqebQboo^`blcIfdeqyyNFAy.-//5yyWyPe^qqo^qe@fqvy
>Te^q?llh<FAlk$qPbb>kv?llh+yKyBwbhfbi%2-+2)01)2&%13+6)15+/&%20+5)23+5&%3.+2)16+4&%3/)1-&%23+3)00+3&t^ihfkdfk`fo`ibplkqebQboo^`blcIfdeqyyNFAy.-/0.yyWyPe^qqo^qe@fqvy
@Te^q?llh<FAlk$qPbb>kv?llh+yKyQ^ihqlAfoqvI^oov%10+5)/5+.&^kaeb^kaefpcofbkaptfii_b`ljbelpqfib)fqfpmlppf_ibqlplil_rq`^k_bafccf`riq)qovqldbq^qib^pq.mboplkqlebimvlryyNFAy.-/0.yyWyPe^qqo^qe@fqvy
QTe^q?llh<FAlk$qPbb>kv?llh+yKyAfoqvI^oov%10+5)/5+.&yyNFAy.-/0.yyWyPe^qqo^qe@fqvy
>QebJ^pqbo$pDo^kaAbpfdk<yKyAfoqvI^oov%10+5)/5+.&yyNFAy.-/0.yyWyPe^qqo^qe@fqvy
QQebJ^pqbo$pDo^kaAbpfdk<yKyKfqofkqebIb^okba%2.+5)23+6&yyNFAy.-/2.yyWyK^do^kay
>SfpflklcqebAb^ayKyKfqofkqebIb^okba%2.+5)23+6&yyNFAy.-/2/yyWyK^do^kay
HJlrkq^fkDolkkyKyHfiiJlrkq^fkDolkk^olrka%/3+4)0-+4&cloXJlrkq^fkDolkkBvb_^iiZqebv^obbifqbp_rqb^pvqlplilyyNFAy.-/2/yyIy/5332yyWyK^do^kay
HDob^qboTfkaol`yKyHfiiDob^qboTfkaol`^olrka%0.)01&%00+3)/1&cloXCi^tibppDob^qboTfkaol`?b^hZqebv^obbifqbp_rqb^pvqlplilyyNFAy.-/2/yyIy/5334yyWyK^do^kay
H>dba@ibcqellcyKyHfii>dba@ibcqellc^olrka%0/)0/&%/5)1.+2&%0-+0)30&%03+2)30&cloX>dba@ibcqellc?ir__boZyyNFAy.-/2/yyIy/5335yyWyK^do^kay
QSfpflklcqebAb^ayKyKfqofkqebIb^okba%2.+5)23+6&yyNFAy.-/2/yyWyK^do^kay
>IbsfurpqebPlri@^iiboyKyKfqofkqebIb^okba%2.+5)23+6&yyNFAy.-/20yyWyK^do^kay
@IbsfurpqebPlri@^iiboyKyPrjjlk^kahfiiIbsfurpqebPlri@^iibo%06+3)4.+2&)qefpnrbpqfpafccf`riqqlplil)qovqldbq^qib^pq.mboplkqlebimvlryyNFAy.-/20yyWyQbolhh^oClobpqy
QIbsfurpqebPlri@^iiboyKyO^jaloqebJ^a%02+.)33+/&yyNFAy.-/20yyWyQbolhh^oClobpqy

>BsbovqefkdTfii?b>iofdeqyKyDob^qc^qebo>iaofjrp%02+.)32+/&ebfplrqpfabqebfkpq^k`bplvlre^sbillhcloefj^qqeb_lqqljyyNFAy.-.31yyWyQbolhh^oClobpqy

>P^cbqvFpGl_LkbyKy>oqfcf`boJlome^ifrp%06+2)25+2&yyWyQbolhh^oClobpqyyNFAy.-/.3y
>Rkabo`rqqfkdqeb@ljmbqfqflkyKyKburp*Mofk`bE^o^j^a%06+1)25+2&yyWyQbolhh^oClobpqyyNFAy.-.32y

OJ^k^*Qlj_pyKyNrbrbcloJ^k^*Qlj_prpfkdqebarkdblkcfkaboyyNFAy.-/.3yyFy

@P^cbqvFpGl_LkbyKyHfii.-Bqebob^i@ovmqO^fabop)2Bqebob^iPlo`bobop)2KburpPq^ihbop^ka2Bqebob^iPmbii_fkabopfkqebJ^k^Qlj_pyyNFAy.-/.3y
QP^cbqvFpGl_LkbyKy>qqebBqebob^iQo^kpmloqbo@lkqoliM^kbi%fkqebollj_bclobPe^cc^o&+@if`hqeb`r_bqebkqebpmb^h_r__ibql^`qfs^qbfqyyNFAy.-/.3y
@Rkabo`rqqfkdqeb@ljmbqfqflkyKyHfiiKburp*Mofk`bPe^cc^o^kadbqXPe^cc^o$pTo^mmfkdpZ+Ebalbpmofj^oivj^df`^ia^j^db)^kae^p^aapqe^qtfiikrhbvlr^ipl+Hfiiqeb^aapofdeq^t^v^katebkqebvpm^tkrmarofkdqebcfdeq+Vlrkbbaqlork^olrkaqlpq^vfko^kdbyyNFAy.-.32y
>PljblkbBipb$pE^oaTlohM^vpLccyKy@ovl*BkdfkbboPe^$ebbk*_vqebBqebob^iQo^kpmloqbo@lkqoliM^kbiyyNFAy.-/.5y
@PljblkbBipb$pE^oaTlohM^vpLccyKyBp`loq@ovl*BkdfkbboPe^$ebbkyyNFAy.-/.5y

OQbolhh^oClobpqyKyQbibmloq_^`hqlQbolhh^oClobpq%06+1)25+2&yyWyQbolhh^oClobpqyyFyyNFAy.-.31y

QPljblkbBipb$pE^oaTlohM^vpLccyKyKburp*Mofk`bE^o^j^a%06+1)25+2&yyWyQbolhh^oClobpqyyNFAy.-/.5y
QRkabo`rqqfkdqeb@ljmbqfqflkyKyKburp*Mofk`bE^o^j^a%06+1)25+2&yyWyQbolhh^oClobpqyyNFAy.-.32y

O>r`ebk^f@ovmqpyKyNrbrbclo>r`ebk^f@ovmqprpfkdqebarkdblkcfkaboyyNFAy.-.31yyFy
@BsbovqefkdTfii?b>iofdeqyKyHfiiqebcfk^i_lppBu^o`eJ^i^a^^oyyNFAy.-.31y

OQbolhh^oClobpqyKyQbibmloq_^`hqlQbolhh^oClobpq%02+.)32+/&yyWyQbolhh^oClobpqyyFy
QBsbovqefkdTfii?b>iofdeqyKyDob^qc^qebo>iaofjrp%02+.)32+/&ebfplrqpfabqebfkpq^k`bplvlre^sbillhcloefj^qqeb_lqqljyyNFAy.-.31yyWyQbolhh^oClobpqy

KDrfab@ljmibqb+@lkqfkrbQlLiaEfiip_o^aCllqefiip%33*35&yKyQf`hql`lkqfkrbqlLiaEfiip_o^aCllqefiip%33*35&*Riqfj^qbTlTDrfab+`ljy

]]
end)
