DugisGuideViewer:RegisterGuide("Utgarde Keep (68-70)", "The Nexus (70-72)", "Horde", "I", function()
return [[
AAA

KIbsbi35ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi35qlmf`hrmqebcliiltfkdnrbpqpyyNFAy...34yyMIy35y

CEltifkdCgloayKyDlqlQfofpc^iDi^ab^kaq^hbqebWbmmbifkqlSbkdb^k`bI^kafkdfkEltifkdCgloa%26+/)26&yyWyQfofpc^iDi^abpyyNFAy...34y

cSbkdb^k`bI^kafkdyKy?^qE^kaibo>abifkb%46+-)/6+4&yyNFAy...34yyWyEltifkdCgloay
eSbkdb^k`bI^kafkdyKyQfjlqevElii^ka%46+4)0-+5&yyNFAy...34yyWyEltifkdCgloay

>QebKbtMi^drbyKy>mlqeb`^ovIvp^kabo%45+3)/6+.&yyNFAy...34yyWyEltifkdCgloay
>IbqQebjB^q@oltyKyMlkqfrp%46+.)0.+/&yyNFAy..//4yyWyEltifkdCgloay
>T^ofpEbiiyKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyNFAy../4-yyWyEltifkdCgloay

@T^ofpEbiiyKyRpbqebX?rokfkdQlo`eZlkqeb^iif^k`b^karkclop^hbk`lompbp^olrka%42+0)0-+5&yyNFAy../4-yyRy00/45yyWyEltifkdCgloay
@IbqQebjB^q@oltyKyHfiiqebCgloa@oltp^olrka%41+4)0/+6&)`liib`qqebjb^q^kacbbaqebjb^qqlqebErkdovMi^drbelrka_vprjjlkfkdfqtfqeqebXMi^drbelrka@^dbZyyNFAy..//4yyRy..//4yyWyEltifkdCgloay

QIbqQebjB^q@oltyKyMlkqfrp%46+.)0.+/&yyNFAy..//4yyWyEltifkdCgloay
>PkfccLrqqebBkbjvyKyMlkqfrp%46+.)0.+/&yyNFAy../20yyWyEltifkdCgloay
QT^ofpEbiiyKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyNFAy../4-yyWyEltifkdCgloay
>ObmloqpcoljqebCfbiayKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyNFAy..//.yyWyEltifkdCgloay

QPkfccLrqqebBkbjvyKyAo^dlkphfkP`olii%43+-).6+5&yyNFAy../20yyRy00153yyWyEltifkdCgloay
>QebAo^dlkphfkJ^myKyAo^dlkphfkP`olii%43+-).6+5&yyNFAy../21yyWyEltifkdCgloay

QQebAo^dlkphfkJ^myKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyNFAy../21yyWyEltifkdCgloay
>QebLccbkpfsb?bdfkpyKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyNFAy../62yyWyEltifkdCgloay

@QebKbtMi^drbyKyClrka^olrkaqebpefmtob`h^q%5-+6)02+-&yyNFAy...34yyWyEltifkdCgloay

@ObmloqpcoljqebCfbiayKyQ^ihqlA^ohO^kdboIv^k^%45+4)04+.&qebkAb^qepq^ihboO^w^bi%44+3)01+4&yyNFAy..//.yyWyEltifkdCgloay

QObmloqpcoljqebCfbiayKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyNFAy..//.yyWyEltifkdCgloay
>QebTfkaorkkboCibbqyKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyNFAy..//6yyWyEltifkdCgloay
QQebKbtMi^drbyKy>mlqeb`^ovIvp^kabo%45+3)/6+.&yyNFAy...34yyWyEltifkdCgloay
>PmfhfkdqebJfuyKy>mlqeb`^ovIvp^kabo%45+3)/6+.&yyNFAy...35yyWyEltifkdCgloay

@PmfhfkdqebJfuyKyHfiiqebDf^kqQfab`o^tibop^olrka%43+1).6+4&^ka`liib`q0XDf^kqQlufkDi^kapZyyNFAy...35yyWyEltifkdCgloay

QPmfhfkdqebJfuyKy>mlqeb`^ovIvp^kabo%45+3)/6+.&yyNFAy...35yyWyEltifkdCgloay
>Qbpq^qPb^yKy>mlqeb`^ovIvp^kabo%45+3)/6+.&yyNFAy...4-yyWyEltifkdCgloay
@Qbpq^qPb^yKyQ^ihql?^qE^kaibo@^jfiib%46+-)/6+5&^kaq^hb^_^qqlfkqbo`bmqqebobfkclo`bjbkqp+RpbqebXMi^drbSf^ipZqlaolmqebfkcb`qba_lj_plkqebobfkclo`bjbkqpfkqebcolwbkpb^yyNFAy...4-yyRy00016yyWyEltifkdCgloay
QQbpq^qPb^yKy>mlqeb`^ovIvp^kabo%45+3)/6+.&yyNFAy...4-yyWyEltifkdCgloay
>Kbt>d^j^kayKy>mlqeb`^ovIvp^kabo%45+3)/6+.&yyNFAy..0-1yyWyEltifkdCgloay
QQebTfkaorkkboCibbqyKy@^mq^fkE^ohbo%51+3)03+1&+Pmb^hql?^qE^kaibo@^jfiibclo^ofabyyNFAy..//6yyWyEltifkdCgloay
>>j_rpebayKy@^mq^fkE^ohbo%51+3)03+1&yyNFAy../0-yyWyEltifkdCgloay
@>j_rpebayKyHfii.2KloqeCibbqJ^ofkbplkqeb_l^qp^olrka%51+-)03+5&yyNFAy../0-yyWyEltifkdCgloay
Q>j_rpebayKy@^mq^fkE^ohbo%51+3)03+1&yyNFAy../0-yyWyEltifkdCgloay
>DrfabLroPfdeqpyKy@^mq^fkE^ohbo%51+3)03+1&yyNFAy../0/yyWyEltifkdCgloay

@DrfabLroPfdeqpyKyRpbqebX@^kklkbbo$pPjlhbCi^obZqlj^ohqebTbpq`^kklk^q%46+-)1-+.&^kaqebB^pq`^kklk^q%5-+/)05+/&yyNFAy../0/yyRy00002yyWyEltifkdCgloay

QDrfabLroPfdeqpyKyA^ohO^kdboIv^k^%45+4)04+.&yyNFAy../0/yyWyEltifkdCgloay
>I^kafkdqebHfiifkd?iltyKyA^ohO^kdboIv^k^%45+4)04+.&yyNFAy../00yyWyEltifkdCgloay

@I^kafkdqebHfiifkd?iltyKyHfii@^mq^fkLipqbo%5.+2)10+0&)Ifbrqbk^kq@bibvkb%50+/)10+/&^kaPbodb^kqIloof`%5/+-)1.+.&yyNFAy../00yyWyEltifkdCgloay

>Qo^filcCfobyKy>mlqeb`^ovE^kbp%50+/)10+.&yyNFAy../1.yyWyEltifkdCgloay
@Qo^filcCfobyKyBp`loq>mlqeb`^ovE^kbpqlp^cbqv)qefpfpmobqqvb^pv^kaebalbpab`bkqa^j^dbyyNFAy../1.yyWyEltifkdCgloay

QI^kafkdqebHfiifkd?iltyKyA^ohO^kdboIv^k^%45+4)04+.&yyNFAy../00yyWyEltifkdCgloay
>Obmloqql>kpbijyKyA^ohO^kdboIv^k^%45+4)04+.&yyNFAy../01yyWyEltifkdCgloay

QObmloqql>kpbijyKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyNFAy../01yyWyEltifkdCgloay
QQo^filcCfobyKy>mlqeb`^ovIvp^kabo%45+3)/6+.&yyNFAy../1.yyWyEltifkdCgloay

>>P`lobqlPbqqibyKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyWyEltifkdCgloayyNFAy../4/y

ORqd^oabHbbmyKyNrbrbcloRqd^oabHbbmrpfkdqebarkdblkcfkaboyyNFAy.0/-3yyFy

>Afp^oj^jbkqyKyA^ohO^kdboJ^oo^e^olrka%35)36&+Peb$pfkpfabqebfkpq^k`b)fqj^vq^hb^jfkrqbrkqfipeb^mmb^opyyWyEltifkdCgloayyNFAy.0/-3y
>Fkds^oJrpqAfbyKyA^ohO^kdboJ^oo^e^olrka%35)36&+Peb$pfkpfabqebfkpq^k`b)fqj^vq^hb^jfkrqbrkqfipeb^mmb^opyyWyEltifkdCgloayyNFAy../3/y

@>P`lobqlPbqqibyKyHfiiMofk`bHbibpbqe+Ebfpqebcfopq_lppfkqebRqd^oabhbbmarkdblkyyWyEltifkdCgloayyNFAy../4/y
@Afp^oj^jbkqyKy@liib`q2XSovhriTb^mlkpZ+Qebv^oblko^`hpp`^qqbobaqeolrdelrqqebfkpq^k`byyNFAy.0/-3y
@Fkds^oJrpqAfbyKyHfiiFkds^oqebMirkabobo%42)02&+Ebfpqebcfk^i?lppfkRqd^oabHbbmyyWyEltifkdCgloayyNFAy../3/y

OEltifkdCgloayKyQbibmloq_^`hqlEltifkdCgloa%45+3)0.+/&yyWyEltifkdCgloayyFy

QAfp^oj^jbkqyKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyWyEltifkdCgloayyNFAy.0/-3y
QFkds^oJrpqAfbyKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyWyEltifkdCgloayyNFAy../3/y
Q>P`lobqlPbqqibyKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyWyEltifkdCgloayyNFAy../4/y

KDrfab@ljmibqb+Qf`hQl@lkqfkrbQlQebKburp%4-*4/&yKyQf`hql`lkqfkrbqlQebKburp%4-*4/&*Riqfj^qbTlTDrfab+`ljy

]]
end)
