DugisGuideViewer:RegisterGuide("The Nexus (70-72)", "Azjol-Nerub / Ahn'kahet: The Old Kingdom (72-74)", "Horde", "I", function()
return [[
AAA

KIbsbi36ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi36qlmf`hrmqebcliiltfkdnrbpqpyyNFAy..6--yyMIy36y

OArolq^oyKyQ^hbqebwbmmbifk_^`hqlQfofpc^iDi^abp^ka^wbmmbifk_^`hqlArolq^oyyNFAy..6--y
C?lob^kQrkao^yKyQo^sbiql?lob^kQrkao^%1.+0).4+4&yyWyArolq^oyyNFAy..6--y

O>j_boIbadbyKyQo^sbiql>j_boIbadb%12+1)01+2&yyWy?lob^kQrkao^yyNFAy..6--y
c>j_boIbadbyKyProofpqo^pw%12+1)01+2&yyWy?lob^kQrkao^yyNFAy..6--y
CQo^kpfpqrpPefbiayKyProofpqo^pw%12+1)01+2&yyWy?lob^kQrkao^yyNFAy..6--y

>Ob^afkdqebJbqbopyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6--yyWy?lob^kQrkao^y
>Pb`obqplcqeb>k`fbkqpyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6.-yyWy?lob^kQrkao^y
>Krqpclo?boofbpyKyIf_o^of^kPboo^e%00+2)01+1&yyNFAy..6./yyWy?lob^kQrkao^y
>?^pf`Qo^fkfkdyKyO^bilo^pw%00+0)01+2&yyNFAy..6.5yyWy?lob^kQrkao^y

O@lia^oo^yKyQ^ihqlIf_o^of^kQf^obclo^qbibmloq%00+0)01+.&yyNFAy..61.yyWy?lob^kQrkao^y

@Ob^afkdqebJbqbopyNFAy..6--yyKyCfkaqeblo_pqlob^a^qqebkloqe%0.+0)/-+0&)tbpq%//+1)/1+/&)plrqe%/5+0)01+6&)^kaaltkkb^oqebKburp%/5+0)/5+2&yyWy?lob^kQrkao^y
@Pb`obqplcqeb>k`fbkqpyNFAy..6.-yyKyHfiiJ^df`*_lrka>k`fbkq^olrka%/4+6)0/+1&^kaDi^`f^i>k`fbkq%0.+3)/1+1&^ka%/.+0)0.+6&yyWy?lob^kQrkao^y
@Krqpclo?boofbpyNFAy..6./yyKyDbq.-XColpq_boofbpZpmob^aqeolrdelrq@lia^oo^%02)/3&)`liib`qqebjtefibnrbpqfkdyyWy?lob^kQrkao^y
@?^pf`Qo^fkfkdyNFAy..6.5yyKyHfii.-@lia^oo^Pmbiitb^sbopclrka^olrka%0/+0)/5+4&yyWy?lob^kQrkao^y
>Mrwwifkd+++yNFAy..61.yyKyQebfqbjXP`fkqfii^qfkdCo^djbkqZpq^oqpnrbpq*aolmmba_v@lia^oo^Pmbii_fkabop^olrka%00)/5&yyRy02315yyWy?lob^kQrkao^y

QOb^afkdqebJbqbopyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6--yyWy?lob^kQrkao^y
>MlpqmlkfkdqebFkbsfq^_ibyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6-2yyWy?lob^kQrkao^y
QPb`obqplcqeb>k`fbkqpyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6.-yyWy?lob^kQrkao^y
QKrqpclo?boofbpyKyIf_o^of^kPboo^e%00+2)01+1&yyNFAy..6./yyWy?lob^kQrkao^y
>HbbmqebPb`obqP^cbyKyIf_o^of^kPboo^e%00+2)01+1&yyNFAy..6.1yyWy?lob^kQrkao^y
Q?^pf`Qo^fkfkdyKyO^bilo^pw%00+0)01+2&yyNFAy..6.5yyWy?lob^kQrkao^y
>E^q`efkd^Mi^kyKyO^bilo^pw%00+0)01+2&yyNFAy..603yyWy?lob^kQrkao^y
QMrwwifkd+++yKyO^bilo^pw%00+0)01+2&yyNFAy..61.yyWy?lob^kQrkao^y
>Qeb@biiyKyO^bilo^pw%00+0)01+2&yyNFAy..610yyWy?lob^kQrkao^y

@Qeb@biiyNFAy..610yyKyHfiiT^o_ofkdboDlobao^hqlqebtbpq%/1+/)/5+6&^kaDbkbo^i@borib^kqlqebkloqe%/4+2)/-+4&yyWy?lob^kQrkao^y
@E^q`efkd^Mi^kyNFAy..603yyKyHfii@lia^oo^Tvojhfkproolrkafkd@lia^oo^cloqebfoXColwbk>ubpZ)qebkrpbqebjlkqebbddpkb^oqebKburp%/5+2)/5+6&yyRy02253yyWy?lob^kQrkao^y
@HbbmqebPb`obqP^cbyNFAy..6.1yyKyHfii>o`^kbPbombkqpkb^oqebKburp%/5+2)/5+6&yyWy?lob^kQrkao^y

QE^q`efkd^Mi^kyKyO^bilo^pw%00+0)01+2&yyNFAy..603yyWy?lob^kQrkao^y
>Ao^hbErkqyKyO^bilo^pw%00+0)01+2&yyNFAy..6.6yyWy?lob^kQrkao^y
QQeb@biiyKyO^bilo^pw%00+0)01+2&yyNFAy..610yyWy?lob^kQrkao^y
>Hbofpqo^pw^yKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..613yyRy0234.yyWy?lob^kQrkao^y
QHbofpqo^pw^yKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..613yyRy0234.yyWy?lob^kQrkao^y
>?^fq^kaPtfq`eyKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..62.yyRy0234.yyWy?lob^kQrkao^y
QHbbmqebPb`obqP^cbyKyIf_o^of^kPboo^e%00+2)01+1&yyNFAy..6.1yyWy?lob^kQrkao^y

@?^fq^kaPtfq`eyNFAy..62.yyKyIllqqebmromib`ovpq^ipkb^oqebKburp%/5+2)/5+6&yyWy?lob^kQrkao^y
@Ao^hbErkqyNFAy..6.6yyRy022-3yyKyCfka^KburpAo^hbE^q`eifkdcivfkd^olrkaqlqebtbpqlcqebKburp+EfqfqtfqeXO^bilo^pw$pPmb^oZrkqfi`lkqoliibaqebkabifsboqlO^bilo^pw%00+0)01+2&tfqefk0jfkrqbpyyWy?lob^kQrkao^y

QAo^hbErkqyKyO^bilo^pw%00+0)01+2&yyNFAy..6.6yyWy?lob^kQrkao^y
>@o^`hfkdqeb@labyKyO^bilo^pw%00+0)01+2&yyNFAy..60.yyWy?lob^kQrkao^y
@@o^`hfkdqeb@labyNFAy..60.yyKyHfiiFknrfpfqlo@^ibo^pqlqebkloqe%0/+5)/4+5&+XPefjjbofkdOrkbpZaolmcoljqeb@lia^oo^Pmbii_fkabop^olrka%00)0-&yyWy?lob^kQrkao^y
Q?^fq^kaPtfq`eyKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..62.yyRy0234.yyWy?lob^kQrkao^y
>P^o^dlp^$pBkayKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..624yyRy0234.yyWy?lob^kQrkao^y

@P^o^dlp^$pBkayNFAy..624yyKyQ^ihqlHbofpqo^pw^clo^qbibmloq+RpbqebX>o`^kbMltboCl`rpZ)qebkhfiieboyyRy0236-yyWy?lob^kQrkao^y
QP^o^dlp^$pBkayKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..624yyRy0234.yyWy?lob^kQrkao^y
>JrpqbofkdqebObapyKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..634yyRy0234.yyWy?lob^kQrkao^y

QJrpqbofkdqebObapyKyO^bilo^pw%00+0)01+2&)Hbofpqo^pw^tfiimloqvlr_^`hyyNFAy..634yyWy?lob^kQrkao^y
>PmofkdfkdqebQo^myKyO^bilo^pw%00+0)01+2&yyNFAy..636yyWy?lob^kQrkao^y

Q@o^`hfkdqeb@labyKyO^bilo^pw%00+0)01+2&yyNFAy..60.yyWy?lob^kQrkao^y
@PmofkdfkdqebQo^myNFAy..636yyKyEb^aqlKloqe*Tbpqbkqo^k`blcqebKburp^q%/2+5)//+3&+RpbXO^bilo^pw$Pm^ohZ_bprobqlpq^v`ilpbqlHbofpqo^pw^yyRy024.5yyWy?lob^kQrkao^y
QPmofkdfkdqebQo^myKyO^bilo^pw%00+0)01+2&yyNFAy..636yyWy?lob^kQrkao^y

>Pb`obqplcqeb>k`fbkqpyKy>o`ej^db?bofk^ka%00+-)01+0&yyWy?lob^kQrkao^yyNFAy..6.-y
@Pb`obqplcqeb>k`fbkqpyKyDbq0XDi^`f^iPmifkqbopZcoljDi^`f^i>k`fbkqp^ka0XJ^df`*?lrkaPmifkqbopZcoljJ^df`*_lrka>k`fbkqp%/0+2)00+2&)%02)/4+6&)%0.+/)/0&)%/.+5)/4+0&?lqeaolmp^ob^olrkakburpillqbacoljqeb_fdqobbpyyNFAy..6.-y
QPb`obqplcqeb>k`fbkqpyKy>o`ej^db?bofk^ka%00+-)01+0&yyWy?lob^kQrkao^yyNFAy..6.-y

>Nrf`hbkfkdyKy>o`ej^db?bofk^ka%00+-)01+0&yyWy?lob^kQrkao^yyNFAy..6..y

>MofplkbolcT^oyKyO^bilo^pw%00+0)01+2&yyWy?lob^kQrkao^yyNFAy..640y
>E^sbQebvKlPe^jb<yKyIf_o^of^kPboo^e%00+2)01+1&yyWy?lob^kQrkao^yyNFAy.0-62y

OQebKburpyKyNrbrbcloqebQebKburptfqevlroarkdblkcfkaboyyNFAy.0-62yyFy

@E^sbQebvKlPe^jb<yKyVlr`^kcfkaqeb_llhfkqebjfaaiblcE^iilcPq^pfpfkqebibcqjfaaibpfablcqebj^myyNFAy.0-62y
@MlpqmlkfkdqebFkbsfq^_ibyKyRpbXFkqboafjbkpflk^iObc^_of`^qloZlk>klj^irpmi^qclojKloqeB^pqpfablcqebj^myyRy02146yyNFAy..6-2y
@Nrf`hbkfkdyKyDbq2X>o`^kbPmifkqbopZcolj@ovpq^iifkbMolqb`qlopfkQebPfkdfkdDolsbtfqefkQebKburpyyNFAy..6..y
@MofplkbolcT^oyKyBkqboQebKburp^kaobib^pbHbofpqo^pw^+Vlre^sbqlhfiiqebi^pq_lpplcqebkburpfkloaboql`ljmibqbqebnrbpqyyNFAy..640y

O?lob^kQrkao^yKyQbibmloq_^`hlroql?lob^kQrkao^%00+0)01+2&yyWy?lob^kQrkao^yyFy

QMofplkbolcT^oyKyO^bilo^pw%00+0)01+2&yyWy?lob^kQrkao^yyNFAy..640y
QMlpqmlkfkdqebFkbsfq^_ibyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6-2yyWy?lob^kQrkao^y
QNrf`hbkfkdyKy>o`ej^db?bofk^ka%00+-)01+0&yyWy?lob^kQrkao^yyNFAy..6..y
QE^sbQebvKlPe^jb<yKyIf_o^of^kPboo^e%00+2)01+1&yyWy?lob^kQrkao^yyNFAy.0-62y

KDrfab@ljmibqb+@lkqfkrbQl>wgli*Kbor_,>ek$h^ebq7QebLiaHfkdalj%4/*41&yKyQf`hql`lkqfkrbql>wgli*Kbor_,>ek$h^ebq7QebLiaHfkdalj%4/*41&*Riqfj^qbTlTDrfab+`ljy

]]
end)

--[[
C Have They No Shame? |N|You can find the book in the middle of Hall of Stasis in the left middle side of the map (19.1, 52.5)|  |QID|13095|
C Postponing the Inevitable |N|Use [Interdimensional Refabricator]  on Anomalus platform North East side of the map (61.7, 21.9)| |U|35479| |QID|11905|
C Quickening |N|Get 5 [Arcane Splinters] from Crystalline Protectors in The Singing Grove within The Nexus (58, 52)| |QID|11911| 
]]-- 
