DugisGuideViewer:RegisterGuide("Azjol-Nerub / Ahn'kahet: The Old Kingdom (72-74)", "Drak'Tharon Keep (74-76)", "Horde", "I", function()
return [[
AAA

KIbsbi4/ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi4/qlmf`hrmqebcliiltfkdnrbpqpyyNFAy.0.34yyMIy4/y

OAo^dlk_ifdeqyKyQo^sbiqlAo^dlk_ifdeq%/3+/)2-+4&yyWyAo^dlk_ifdeqyyNFAy.0.34y
>Ab^qeqlqebQo^fqloHfkdyKyHfifuqebRko^sbibo%/3+/)2-+4&yyWyAo^dlk_ifdeqyyNFAy.0.34y
>Alk$qClodbqqebBddpyKyHfifuqebRko^sbibo%/3+/)2-+4&yyWyAo^dlk_ifdeqyyNFAy.0.5/y

KIbsbi40ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi40qlmf`hrmqebcliiltfkdnrbpqpyyNFAy.0.54yyMIy40y
>QebC^`bibppLkbpyKyHfifuqebRko^sbibo%/3+/)2-+4&yyWyAo^dlk_ifdeqyyNFAy.0.54y

O>wgli*Kbor_yKyNrbrbclo>wgli*Kbor_tfqevlroarkdblkcfkaboyyNFAy.0.5/yyFy

@Ab^qeqlqebQo^fqloHfkdyKyHfii>kr_$^o^hqebcfk^i_lppfk>wgli*Kbor_%3.+4)15+2&+>kadbqX>kr_$^o^h$p?olhbkErphZyyWyAo^dlk_ifdeqyyNFAy.0.34y
@Alk$qClodbqqebBddpyKyBkqbo>wgli*Kbor_^kaabpqolv3Kbor_f^kP`lrodbBddpyyWyAo^dlk_ifdeqyyNFAy.0.5/y

OAo^dlk_ifdeqyKyQbibmloq_^`hqlAo^dlk_ifdeq%/3+/)2-+4&yyWyAo^dlk_ifdeqyyNFAy.0.54yyFy

QAlk$qClodbqqebBddpyKyHfifuqebRko^sbibo%/3+/)2-+4&yyWyAo^dlk_ifdeqyyNFAy.0.5/y
QAb^qeqlqebQo^fqloHfkdyKyHfifuqebRko^sbibo%/3+/)2-+4&yyWyAo^dlk_ifdeqyyNFAy.0.34y

O>ek$h^ebq7QebLiaHfkdaljyKyNrbrbclo>ek$h^ebq7QebLiaHfkdaljtfqevlroarkdblkcfkaboyyNFAy.0.54yyFy
>CrkhvCrkdfyKyQebfqbjXLlwb*`lsbobaCrkdrpZpq^oqpqebnrbpq*aolmmba_vP^s^db@^sb?b^pqpfkqebPefjjbofkd?ldyyRy102./yyWyAo^dlk_ifdeqyyNFAy.0/-1yyLy
@CrkhvCrkdfyKyDlqeolrde^qrkkbifkqlqebC^iibkQbjmiblc>ek$h^ebq)qlvlroibcqqebobp^kbkqovfkqlqebPefjjbofkd?ldtebobqebP^s^db@^sb?b^pqp^ob+Dbq3XDolqbpnrbCrkdrpZcoljqebjyyWyAo^dlk_ifdeqyyNFAy.0/-1yyLy
@QebC^`bibppLkbpyKyHfiiEbo^iaSli^wg^kaqebqeobbClodlqqbkLkbpfk>ek$h^ebq7QebLiaHfkdaljyyWyAo^dlk_ifdeqyyNFAy.0.54y

OAo^dlk_ifdeqyKyQbibmloq_^`hqlAo^dlk_ifdeq%/3+/)2-+4&yyWyAo^dlk_ifdeqyyFy

QCrkhvCrkdfyKyHfifuqebRko^sbibo%/3+/)2-+4&yyWyAo^dlk_ifdeqyyNFAy.0/-1yyLy
QQebC^`bibppLkbpyKyHfifuqebRko^sbibo%/3+/)2-+4&yyWyAo^dlk_ifdeqyyNFAy.0.54y

KDrfab@ljmibqb+@lkqfkrbQlAo^h$Qe^olkHbbm%41*43&yKyQf`hql`lkqfkrbqlAo^h$Qe^olkHbbm%41*43&*Riqfj^qbTlTDrfab+`ljy

]]
end)

--[[
C The Faceless Ones |N|Kill Herald Volazj (23.7, 50.6) and the three Forgotten Ones (34, 50) in Ahn'kahet: The Old Kingdom| |Z|Dragonblight| |QID|13187|
]]--
