DugisGuideViewer:RegisterGuide("Drak'Tharon Keep (74-76)", "The Violet Hold (75-77)", "Horde", "I", function()
return [[
AAA

KIbsbi40ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi40qlmf`hrmqebcliiltfkdnrbpqpyyNFAy./46.yyWyDofwwivEfiipyyMIy40y

O@lknrbpqEliayKyQo^sbiql@lknrbpqElia%/-+5)31+2&yyNFAy./46.yyWyDofwwivEfiipy
e@lknrbpqEliayKy?^oo^`hpJ^pqboOebhhr%/-+5)31+2&yyNFAy./46.yyWyDofwwivEfiipy
c@lknrbpqEliayKyHo^de%//+-)31+2&yyNFAy./46.yyWyDofwwivEfiipy

>QebJ^df`^iHfkdaljlcA^i^o^kyKyJ^dfpqofuMe^bifpq^%/-+4)31+0&yyNFAy./46.yyWyDofwwivEfiipy
@QebJ^df`^iHfkdaljlcA^i^o^kyKyQ^ihqlJ^dfpqofuMe^bifpq^%/-+4)31+0&qldbq^mloqqlA^i^o^kyyNFAy./46.yyWyDofwwivEfiipy

QQebJ^df`^iHfkdaljlcA^i^o^kyKy>o`ej^db@bifkao^%23+/)14+.&yyNFAy./46.yyWyA^i^o^ky
>Ib^okfkdqlIb^sb^kaObqrok7QebJ^df`^iT^vyKy>o`ej^db@bifkao^%23+/)14+.&yyNFAy./46-yyWyA^i^o^ky
@Ib^okfkdqlIb^sb^kaObqrok7QebJ^df`^iT^vyKyRpbqebQbibmloq@ovpq^iKbuqql>o`ej^db@bifkao^%23+/)14+.&)qebkrpbqeblkbvlrdbqmloqbaql)qldbq_^`hyyNFAy./46-yyWyA^i^o^ky
QIb^okfkdqlIb^sb^kaObqrok7QebJ^df`^iT^vyKy>o`ej^db@bifkao^%23+/)14+.&yyNFAy./46-yyWyA^i^o^ky
cHo^prp$I^kafkdyKy>ira^kbTefqb`ilra%4/+2)12+1&yyWyA^i^o^kyyNFAy./.43y

C@lknrbpqEliayKy>ira^kbTefqb`ilra%4/+2)12+1&yyNFAy./135yyWyDofwwivEfiipy

>Qeb@lknrbolo$pQ^phyKy@lknrboloHobkk^%/-+5)31+/&yyNFAy./135yyWyDofwwivEfiipy
QQeb@lknrbolo$pQ^phyKyPbodb^kqK^wdofj%/.+-)31+.&yyNFAy./135yyWyDofwwivEfiipy
>>PeltlcPqobkdqeyKyPbodb^kqK^wdofj%/.+-)31+.&yyNFAy.//24yyWyDofwwivEfiipy
>QebCi^jb_fkabop$Pb`obqpyKyPbodb^kqK^wdofj%/.+-)31+.&yyNFAy.//23yyWyDofwwivEfiipy

@QebCi^jb_fkabop$Pb`obqpyKyCfkaqebAo^dlkci^vboCi^jb_fkabop^qSliaorkb%/6)42&yyNFAy.//23yyWyDofwwivEfiipy
@>PeltlcPqobkdqeyKyCfkaqebAo^dlkci^vboErp`^oip^qSliaorkb%/6)42&yyNFAy.//24yyWyDofwwivEfiipy

Q>PeltlcPqobkdqeyKyPbodb^kqK^wdofj%/.+-)31+.&yyNFAy.//24yyWyDofwwivEfiipy
QQebCi^jb_fkabop$Pb`obqpyKyPbodb^kqK^wdofj%/.+-)31+.&yyNFAy.//23yyWyDofwwivEfiipy
>QebQe^kblcSliaorkbyKyPbodb^kqK^wdofj%/.+-)31+.&yyNFAy.//26yyWyDofwwivEfiipy

@QebQe^kblcSliaorkbyKyElmlkqebmolql*ao^hb%/4)45&fkSliaorkb+Qe^kbQlos^iaBofhpplkfplkqlmlcqebkb^o_vqltbo%/4+-)40+-&)_bprobqlhbbmefjpqrkkbatefipq^qq^`hfkdyyNFAy.//26yyWyDofwwivEfiipy

QQebQe^kblcSliaorkbyKyPbodb^kqK^wdofj%/.+-)31+.&yyNFAy.//26yyWyDofwwivEfiipy
>JvBkbjv$pCofbkayKy@lknrboloHobkk^%/-+5)31+/&yyNFAy./1./yyWyDofwwivEfiipy

@JvBkbjv$pCofbkayKyPlrqeb^pq^qClobpq$pBadbMlpq+Si^abhfpfkqebqltbo%03+/)34+5&+T^q`eclofqbjaolmXJfhe^fi$pGlrok^iZqlpq^oqkbuqnrbpqyyNFAy./1./yyWyDofwwivEfiipy
>Jfhe^fi$pGlrok^iyKyQebfqbjXJfhe^fi$pGlrok^iZpq^oqpnrbpq*aolmplccqebPfisbo_ollhErkqbop^kaSi^abh%03+/)34+5&yyNFAy./1/0yyRy0361-yyWyDofwwivEfiipy

QJvBkbjv$pCofbkayKy@lknrboloHobkk^%/-+5)31+/&yyNFAy./1./yyWyDofwwivEfiipy
QJfhe^fi$pGlrok^iyKy@lknrboloHobkk^%/-+5)31+/&yyNFAy./1/0yyWyDofwwivEfiipy
>Dlodlkk^yKy@lknrboloHobkk^%/-+5)31+/&yyNFAy./1/1yyWyDofwwivEfiipy
QDlodlkk^yKyDlodlkk^%/-+6)31+.&yyNFAy./1/1yyWyDofwwivEfiipy
>DllaQoliiErkqfkdyKyPbodb^kqQerohfk%//+/)31+1&yyNFAy.//-5yyWyDofwwivEfiipy

QDllaQoliiErkqfkdyKyP^jfo%.3+/)14+4&yyNFAy.//-5yyWyDofwwivEfiipy
>Cfiifkdqeb@^dbpyKyP^jfo%.3+/)14+4&yyNFAy..651yyWyDofwwivEfiipy

@Cfiifkdqeb@^dbpyKyQ^ihql?raa%.3+1)15+.&)qebkeb^aqlqebOrfkplcAo^h$Wfk%.0+4)25+3&^karpbvlrombq_^oqlpbkaefj^cqbo^qolii)qebkrpbqebX?lrkqvErkqbo$p@^dbZlk`ba^wbayyNFAy..651yyRy02403yyWyDofwwivEfiipy

QCfiifkdqeb@^dbpyKyP^jfo%.3+/)14+4&yyNFAy..651yyWyDofwwivEfiipy
>Qor`b<yKyAo^hror%.3+2)14+5&yyNFAy..656yyWyDofwwivEfiipy
@Qor`b<yKyIllqqebXArii@^osfkdHkfcbZkbuqqlqeb`^db)rpbfq)qebkq^ihqlAo^hror%.3+2)14+5&qlpe^hbefpe^kayyNFAy..656yyRy05-50yyWyDofwwivEfiipy
QQor`b<yKyAo^hror%.3+2)14+5&yyNFAy..656yyWyDofwwivEfiipy
>Sf^ilcSfpflkpyKyAo^hror%.3+2)14+5&yyNFAy..66-yyWyDofwwivEfiipy
?Fj_rbaSf^iyKyQ^ihql>jbbk^e%.3+-)14+5&^ka_rv^kFj_rbaSf^iyyIy.5/23yyNFAy..66-yyWyDofwwivEfiipy

@Sf^ilcSfpflkpyKyXT^qbotbbaColkaZfpfkqebi^hb%.2+/)1-+3&+XE^wbIb^cZfpclrka^olrka%.0+.)1.+0&^ka%.0+-)05+6&yyNFAy..66-yyWyDofwwivEfiipy

QSf^ilcSfpflkpyKyAo^hror%.3+2)14+5&yyNFAy..66-yyWyDofwwivEfiipy
>Pr_gb`qqlFkqbomobq^qflkyKyAo^hror%.3+2)14+5&yyNFAy..66.yyWyDofwwivEfiipy
>P`lrodbh^_l_yKyMofdjlk%.2+5)13+5&yyNFAy./151yyWyDofwwivEfiipy
@P`lrodbh^_l_yKyIllq^jrjjvqebkeb^aaltkqlqeb_lkcfob%.3+4)15+/&^ka_rokfqyyNFAy./151yyRy05.16yyWyDofwwivEfiipy
QP`lrodbh^_l_yKyJ^`hCb^opbk%.3+4)15+0&yyNFAy./151yyWyDofwwivEfiipy
>Pefjjbo`^mPqbtyKyMofdjlk%.2+5)13+5&yyNFAy./150yyWyDofwwivEfiipy
>Pb^obaP`lrodbyKyJ^`hCb^opbk%.3+4)15+0&yyNFAy./-/6yyWyDofwwivEfiipy

KPefjjbofkdPklt`^myKy>ilkdqebofsbo_^khplrqelcqebOrfkplcAo^h$Wfk%.-+3)30+6&yyNFAy./150yyNLyPefjjbofkdPklt`^m72,2yyWyDofwwivEfiipy
HF`bPbombkqpyKy>iilsboqebOrfkplcAo^h$Wfk%.0+4)25+3&yyNFAy./150yyNLyF`bPbombkqBvb72,2yyWyDofwwivEfiipy
HQoliipyKyFkqebOrfkplcAo^h$Wfk%.0+4)25+3&ql`liib`q2uXColwbkJlglZyyIy024662yyNFAy..66.yyWyDofwwivEfiipy
QPr_gb`qqlFkqbomobq^qflkyKyFj^dblcAo^hror%.0+0)3-+6&+RpbXAo^hror$pBifufoZ^qqeb_o^wfboyyNFAy..66.yyRy02464yyWyDofwwivEfiipy
>P^`ofcf`bpJrpq_bJ^abyKyFj^dblcAo^hror%.0+0)3-+6&yyNFAy./--4yyWyDofwwivEfiipy

@Pefjjbo`^mPqbtyKy@liib`q2uXPtbbqollqZfp^iilsboWb_$E^i^h^olrka%.1+5)04+-&yyNFAy./150yyWyDofwwivEfiipy
@P^`ofcf`bpJrpq_bJ^abyKyHfiiT^oiloaWfj$_l%.1+3)04+5&)eb^armqebwfddro^q^kaq^hbqebbvbcoljqebeb^aqebob%.4+6)03+2&yyNFAy./--4yyWyDofwwivEfiipy
QP^`ofcf`bpJrpq_bJ^abyKyFj^dblcAo^hror%.4+16)03+0-&+RpbXAo^hror$pBifufoZ^qqeb_o^wfboyyNFAy./--4yyRy02464yyWyDofwwivEfiipy
>Eb^oqlcqeb>k`fbkqpyNFAy./-1/yyKyFj^dblcAo^hror%.4+16)03+0-&yyWyDofwwivEfiipy

@Pb^obaP`lrodbyKyDlqlAo^h$qe^olkHbbm%.4+5)/4+0&+Dlrmqebpq^fop^kagrjmlkqlqebbadbplcqebpq^fo`^pb+Il_XJ^`h$pA^ohDoldZ^qqebqoliip_biltyyNFAy./-/6yyRy026-5yyWyDofwwivEfiipy

QPb^obaP`lrodbyKyJ^`hCb^opbk%.3+4)15+0&yyNFAy./-/6yyWyDofwwivEfiipy
>Pb^o`e^kaObp`rbyKyJ^`hCb^opbk%.3+4)15+/&yyWyDofwwivEfiipyyNFAy./-04y
QPefjjbo`^mPqbtyKyMofdjlk%.2+5)13+5&yyNFAy./150yyWyDofwwivEfiipy
>P^vEbiilqlJvIfqqibCofbkayKyMofdjlk%.2+5)13+5&yyNFAy./.6-yyWyDofwwivEfiipy

QEb^oqlcqeb>k`fbkqpyKyEb^oqlcqeb>k`fbkqp%04+-)0/+1&yyNFAy./-1/yyWyDofwwivEfiipy
>JvEb^oqfpfkVlroE^kapyKyEb^oqlcqeb>k`fbkqp%04+-)0/+1&yyNFAy./5-/yyWyDofwwivEfiipy
QJvEb^oqfpfkVlroE^kapyKyFj^dblcAo^hror%12+-)/5+0&+Hfiiqebproolrkafkdqoliipclo2XAbpmbo^qbJlglZyyNFAy./5-/yyWyDofwwivEfiipy
>Slf`bpColjqebArpqyKyFj^dblcAo^hror%12+-)/5+0&yyNFAy./-35yyWyDofwwivEfiipy

QP^vEbiilqlJvIfqqibCofbkayKyE^ohlo%40+5)01+.&yyNFAy./.6-yyWyDofwwivEfiipy
>Qebo^mvyKyE^ohlo%40+5)01+.&yyNFAy./..1yyWyDofwwivEfiipy
>FqQ^hbpDrqp+++yKyHo^w%40+6)01+.&yyNFAy./..3yyWyDofwwivEfiipy

@FqQ^hbpDrqp+++yKyEb^aaltkfkqlqebAo^hfi$gfkOrfkp%4.+1)/0+6&+Lmbkg^opfkqebcfopq_fdollj^ilkdqebt^iipyyNFAy./..3yyWyDofwwivEfiipy
@Slf`bpColjqebArpqyKyAbbmbofkqlqeborfkp)vlr$iicfkaqebXAo^hh^ofQ^_ibqpZfkqeb`lokbolc^pfabollj%36+1).5+.&yyNFAy./-35yyWyDofwwivEfiipy
>Ark*a^*Ark*q^eyKyE^oofplkGlkbp%36+1).4+2&yyNFAy./-5/yyWyDofwwivEfiipy
@Ark*a^*Ark*q^eyKyCliiltefjfkqlqeb`bobjlkf^i`e^j_bo)bsbkqr^iiv^kbifqbpk^hbtfiipm^tk+Ibqefjq^khfq^kahfii^kv^aapqe^qpm^tkyyNFAy./-5/yyWyDofwwivEfiipy
QSlf`bpColjqebArpqyKyKltdlqlqeb_o^wfbo^q%4.+4)/3+.&^karpbXAo^hror$pBifufoZ+Q^ihqlqebFj^dblcAo^hror%.0+0)3-+6&yyNFAy./-35yyRy02464yyWyDofwwivEfiipy
>@ib^kpfkdAo^h$Qe^olkyKyFj^dblcAo^hror%.0+0)3-+6&+Lkivq^hbqefpfcvlrmi^kqlorkqebfkpq^k`bAo^h$Qe^olkHbbmyyNFAy.//05yyWyDofwwivEfiipy
@Qebo^mvyKyHfiiqebqoliipproolrkafkdqeborfkp%4-+3)/4+0&yyNFAy./..1yyWyDofwwivEfiipy

QFqQ^hbpDrqp+++yKyHo^w%40+6)01+.&yyNFAy./..3yyWyDofwwivEfiipy
QArk*a^*Ark*q^eyKyE^ohlo%40+5)01+.&yyNFAy./-5/yyWyDofwwivEfiipy
QQebo^mvyKyE^ohlo%40+5)01+.&yyNFAy./..1yyWyDofwwivEfiipy

OAo^h$Qe^olkHbbmyKyNrbrbcloAo^h$Qe^olkHbbmtfqevlroarkdblkcfkaboyyNFAy.0./6yyFy

@Pb^o`e^kaObp`rbyKyCfkaHrowbieb$pqo^mmbafkqebpmfaboolljyyNFAy./-04y

QPb^o`e^kaObp`rbyKyHrowbi*fpfkpfabAo^h$Qe^olkfklkblcqebA^ohtb_Sf`qfj`l`llkpfkqebpmfaboollj+Vlr`^k_ob^hqebtb_ptefibklqfk^ddolo^kdbrkqfivlrcfkatef`etb_HrowbifpfkyyNFAy./-04y
>Eb^aD^jbpyKyHrowbi*clrkatfqefklkblcqebTb__baSf`qfjpfkpfabAo^h$Qe^olkyyNFAy.0./6y
@Eb^aD^jbpyKyRpbXHrowbi$p?ilrpbP`o^mZ^qqeb`lompblcKlslpqebPrjjlkbo)eb$pqebpb`lka_lppfkpfabqebfkpq^k`b+Rpbqeb`ilqeofdeq^t^v^pqeb`lompb`^kafp^mmb^onrfqbnrf`hivyyRy10/.1yyNFAy.0./6y
QEb^aD^jbpyKyJ^`hCb^opbkyyNFAy.0./6y

@@ib^kpfkdAo^h$Qe^olkyKyDbq2BkarofkdJlglcoljfkpfabAo^h$Qe^olk+Qeb_o^wfbofpfkpfabqebfkpq^k`b)altkqebpq^fop)_befkaqebi^pq_lppyyNFAy.//05y

ODofwwivEfiipyKyQbibmloq_^`hqlDofwwivEfiipyyFy

Q@ib^kpfkdAo^h$Qe^olkyKyFj^dblcAo^hror%.0+0)3-+6&*prjjlkefjrpfkdXAo^hror$pBifufoZyyRy02464yyWyDofwwivEfiipyyNFAy.//05y

KDrfab@ljmibqb+@lkqfkrbQlQebSflibqElia%42*44&yKyQf`hql`lkqfkrbqlQebSflibqElia%42*44&*Riqfj^qbTlTDrfab+`ljy

]]
end)
