DugisGuideViewer:RegisterGuide("Gundrak (76-78)", "Halls of Stone (77-79)", "Horde", "I", function()
return [[
AAA

KIbsbi41ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi41qlmf`hrmqebcliiltfkdnrbpqpyyNFAy./2-0yyMIy41y

OQeb>odbkqPq^kayKyQo^sbiqlqeb>odbkqPq^kafkWri$ao^h%1.+2)31+2&yyNFAy./2-0yyWyWri$Ao^hy

cQeb>odbkqPq^kayKyDroof`%1.+2)31+2&yyNFAy./2-0yyWyWri$Ao^hy
eQeb>odbkqPq^kayKyJ^ofpp^Bsbot^q`e%1-+5)33+0&yyNFAy./2-0yyWyWri$Ao^hy

>AbcbkaqebPq^kayKy@ljj^kaboC^ipq^^s%06+2)33+6&yyNFAy./2-0yyWyWri$Ao^hy
>M^o^`erqbpcloqeb>odbkq@orp^abyKy@ljj^kaboC^ipq^^s%06+2)33+6&yyNFAy./41-yyWyWri$Ao^hy

@M^o^`erqbpcloqeb>odbkq@orp^abyNFAy./41-yyRy063.2yyKyCfkaqeb>odbkqcfdeqboplrqfkqeb`lroqv^oa%04+4)32+6&^kaqlppqebjqebX@orp^aboM^o^`erqbpZyyWyWri$Ao^hy
@AbcbkaqebPq^kayNFAy./2-0yyKyEbimqeb>odbkqcfdeqbophfiiqebp`lrodblrqfkqeb`lroqv^oa%04+4)32+6&yyWyWri$Ao^hy

QAbcbkaqebPq^kayKy@ljj^kaboC^ipq^^s%06+2)33+6&yyNFAy./2-0yyWyWri$Ao^hy
QM^o^`erqbpcloqeb>odbkq@orp^abyKy@ljj^kaboC^ipq^^s%06+2)33+6&yyNFAy./41-yyWyWri$Ao^hy
>KbtLoabopcloPbodb^kqPq^`he^jjboyKy@ljj^kaboHrkw%1-+0)33+3&yyNFAy./2-2yyWyWri$Ao^hy
>Qolr_ib^qqeb>iq^olcPpbo^qrpyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2-3yyWyWri$Ao^hy
>Qeb?ibppfkdlcWfj$>_t^yKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./232yyWyWri$Ao^hy

QQeb?ibppfkdlcWfj$>_t^yKyWfj$>_t^%03+4)4/+2&yyNFAy./232yyIy0522..-yyLyyWyWri$Ao^hy
QKbtLoabopcloPbodb^kqPq^`he^jjboyKyPbodb^kqPq^`he^jjbo%1-+2)15+/&yyNFAy./2-2yyWyWri$Ao^hy
>>odbkq@orp^ab)Tb>obIb^sfkdyKyPbodb^kqPq^`he^jjbo%1-+2)15+/&yyNFAy./2-1yyWyWri$Ao^hy
>JlmmfkdRmyKy@lomlo^iJ^d^%1-+1)15+/&yyNFAy./2-5yyWyWri$Ao^hy
@Qolr_ib^qqeb>iq^olcPpbo^qrpyNFAy./2-3yyKyPkb^h^olrkaqebbifqb^kabkqboqeb^iq^o_befkaefj%1-+1)05+6&yyWyWri$Ao^hy
@>odbkq@orp^ab)Tb>obIb^sfkdyNFAy./2-1yyKyQ^ihqlqeb>odbkqcfdeqbop^olrka%1-+1)13+6&yyWyWri$Ao^hy
@JlmmfkdRmyNFAy./2-5yyKyHfiiqebCliiltboplcPpbo^qrp^olrka%1-+1)13+6&yyWyWri$Ao^hy
>Pqo^kdbJlglyKyQebfqbjXPqo^kdbJlglZpq^oqpnrbpq*aolmmba_vqoliip^olrkaQeb>iqbolcPpbo^qrp%1-)13&yyNFAy./2-4yyRy050/.yyWyWri$Ao^hy
Q>odbkq@orp^ab)Tb>obIb^sfkdyKyPbodb^kqPq^`he^jjbo%1-+2)15+/&yyNFAy./2-1yyWyWri$Ao^hy
QJlmmfkdRmyKy@lomlo^iJ^d^%1-+1)15+/&yyNFAy./2-5yyWyWri$Ao^hy

QQolr_ib^qqeb>iq^olcPpbo^qrpyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2-3yyWyWri$Ao^hy
QPqo^kdbJlglyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2-4yyWyWri$Ao^hy
>Mob`flrpBibjbkq^iCirfapyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2.-yyWyWri$Ao^hy
>QebAo^hh^ofAlKlqKbbaT^qboBibjbkq^ipyKyPr_*Ifbrqbk^kqG^u%1-+/)35+6&yyNFAy./23/yyWyWri$Ao^hy

@Mob`flrpBibjbkq^iCirfapyNFAy./2.-yyKyTbpq^qqebAo^h$Plqo^Cfbiap%11+.)46+3&+Dbq6XT^qboBibjbkq^iIfkhpZcolj@o^wbaT^qboPmfofqp+Qo^kpclojqebpbfkql0XQbqeboqlqebmi^kblcT^qboZ+Tfqeqelpb0fqbjpvlr`^kprjjlk0T^qboviloap)tef`eaolmqeb0XMob`flrpBibjbkq^iCirfapZyyWyWri$Ao^hy
@QebAo^hh^ofAlKlqKbbaT^qboBibjbkq^ipyNFAy./23/yyKyHfii.-Ao^hh^ofT^qbo?fkabop)tbpq^qqebAo^h$Plqo^Cfbiap%11+.)46+3&yyWyWri$Ao^hy

QQebAo^hh^ofAlKlqKbbaT^qboBibjbkq^ipyKyPr_*Ifbrqbk^kqG^u%1-+/)35+6&yyNFAy./23/yyWyWri$Ao^hy
QMob`flrpBibjbkq^iCirfapyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2.-yyWyWri$Ao^hy
>JrpeolljJfuboyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2.1yyWyWri$Ao^hy
>DirqqlklrpIrohbopyKy>mmobkqf`bMbpqibmlq%1.+0)32+.&yyNFAy./2/4yyWyWri$Ao^hy

@DirqqlklrpIrohbopyNFAy./2/4yyRy0505-yyKyMf`hrm/2XWri$Ao^hO^qpZfkqlq^i^kaqeolt2o^qp^qb^`e_^pfifphqlm^`fcvqebj^ka`liib`qqebX?^pfifph@ovpq^ipZqe^qvlrkbba%11+5)3/+4&yyWyWri$Ao^hy
@JrpeolljJfuboyNFAy./2.1yyKyClrka^ii^olrkaqebt^qbop^q%11+5)3/+4&yyWyWri$Ao^hy

QJrpeolljJfuboyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2.1yyWyWri$Ao^hy
>QllJr`elc^DllaQefkdyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2.3yyWyWri$Ao^hy
@QllJr`elc^DllaQefkdyNFAy./2.3yyRy0500/yyKyKloqe^qqeb>iq^olcPpbo^qrp%1-+3)10+5&+QeoltqebXJlafcfbaJlglZ^qqebJraaibaMolmebqlcPpbo^qrp^kahfiiyyWyWri$Ao^hy
QDirqqlklrpIrohbopyKy>i`ebjfpqCfkhibpqbfk%02+.)2/+/&yyNFAy./2/4yyWyWri$Ao^hy
QQllJr`elc^DllaQefkdyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2.3yyWyWri$Ao^hy
>QlqebTfq`eAl`qloyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./3/0yyWyWri$Ao^hy

QQlqebTfq`eAl`qloyKyTfq`eAl`qloHercr%26+2)25+-&yyNFAy./3/0yyWyWri$Ao^hy
>?ob^hfkdQeolrdeGfk$>i^fyKyTfq`eAl`qloHercr%26+2)25+-&yyNFAy./3/4yyWyWri$Ao^hy
>Qeb?ibppfkdlcWfj$Qlod^yKyTfq`eAl`qloHercr%26+2)25+-&yyNFAy./3.2yyWyWri$Ao^hy
QQeb?ibppfkdlcWfj$Qlod^yKyWfj$Qlod^%26+2)24+/&yyNFAy./3.2yyIy0522..-yyLyyWyWri$Ao^hy

cWfj$Qlod^yKyJ^^h^%3-+-)23+5&yyNFAy./3/5yyWyWri$Ao^hy
eWfj$Qlod^yKyM^k$v^%26+0)24+0&yyNFAy./3/5yyWyWri$Ao^hy

@?ob^hfkdQeolrdeGfk$>i^fyNFAy./3/4yyKyAfpqro_b^`elcqebMromib%24+2)3.+4&)Oba%25+//)3/+/&)?irb%24+/)32+0&^kaDobbk%23+/)31+/&`^riaolkpyyWyWri$Ao^hy

Q?ob^hfkdQeolrdeGfk$>i^fyKyTfq`eAl`qloHercr%26+2)25+-&yyNFAy./3/4yyWyWri$Ao^hy
>QlPmb^hTfqeE^o$hl^yKyTfq`eAl`qloHercr%26+2)25+-&yyNFAy./3/5yyWyWri$Ao^hy
>Obif`plcqebPkltIblm^oaDlaabppyKy@eolkf`iboQl$hfkf%26+6)24+6&yyNFAy./302yyWyWri$Ao^hy

QQlPmb^hTfqeE^o$hl^yKyE^o$hl^%30+4)4-+0&yyNFAy./3/5yyWyWri$Ao^hy
>?rqCfopqJvLccpmofkdyKyE^o$hl^%30+4)4-+0&yyNFAy./30/yyWyWri$Ao^hy
@?rqCfopqJvLccpmofkdyNFAy./30/yyRy05343yyKyHfiiqeb@ropbaLccpmofkdlcE^o$hl^^olrka%30+.)33+5&^karpbqebXTefphbolcE^o$hl^ZlkqebjyyWyWri$Ao^hy
@Obif`plcqebPkltIblm^oaDlaabppyNFAy./302yyKyXE^o$hl^kObif`pZ^obclrkapmob^aqeolrdelrqqeb>iq^o^olrka%30+.)33+5&yyWyWri$Ao^hy
Q?rqCfopqJvLccpmofkdyKyE^o$hl^%30+4)4-+0&yyNFAy./30/yyWyWri$Ao^hy
>PmfofqlcOerklhyKyE^o$hl^%30+4)4-+0&yyNFAy./31/yyWyWri$Ao^hy

QObif`plcqebPkltIblm^oaDlaabppyKy@eolkf`iboQl$hfkf%26+6)24+6&yyNFAy./302yyWyWri$Ao^hy

>Qeb?ibppfkdlcWfj$OerhyKyTfq`eAl`qloHercr%26+2)25+-&yyNFAy./322yyWyWri$Ao^hy
QQeb?ibppfkdlcWfj$OerhyKyWfj$Oerh%26+4)11+1&yyNFAy./322yyIy0522..-yyLyyWyWri$Ao^hy

QPmfofqlcOerklhyKyPmfofqlcOerklh%20+2)06+-&yyNFAy./31/yyWyWri$Ao^hy
>JvMolmebq)JvBkbjvyKyPmfofqlcOerklh%20+2)06+-&yyNFAy./313yyWyWri$Ao^hy
@JvMolmebq)JvBkbjvyNFAy./313yyKyHfiiMolmebqlcOerklhfkqebi^hb%21+.)14+0&yyWyWri$Ao^hy
QJvMolmebq)JvBkbjvyKyPmfofqlcOerklh%20+2)06+-&yyNFAy./313yyWyWri$Ao^hy
>>kBkaqlqebPrccbofkdyKyPmfofqlcOerklh%20+2)06+-&yyNFAy./314yyWyWri$Ao^hy
@>kBkaqlqebPrccbofkdyNFAy./314yyRy05363yyKyHfiiqebOerklh$pQlojbkqlo^q%20+2)02+5&^karpbqebXQlojbkqlo$pFk`bkpbZebaolmpqebkhfiiOerklhyyWyWri$Ao^hy
Q>kBkaqlqebPrccbofkdyKyPmfofqlcOerklh%20+2)06+-&yyNFAy./314yyWyWri$Ao^hy
>?^`hqlE^o$hl^yKyPmfofqlcOerklh%20+2)06+-&yyNFAy./320yyWyWri$Ao^hy

Q?^`hqlE^o$hl^yKyE^o$hl^%30+4)4-+0&yyNFAy./320yyWyWri$Ao^hy
>FPbkpb^Afpqro_^k`byKyE^o$hl^%30+4)4-+0&yyNFAy./332yyWyWri$Ao^hy
@FPbkpb^Afpqro_^k`byNFAy./332yyKyQ^ihqlE^o$hl^%30+4)4-+0&^kavlr$ii_bpbkqlk^peloqqofm^ka_^`hyyWyWri$Ao^hy
QFPbkpb^Afpqro_^k`byKyE^o$hl^%30+4)4-+0&yyNFAy./332yyWyWri$Ao^hy
>Mobm^o^qflkpcloqebRkabotloiayKyE^o$hl^%30+4)4-+0&yyNFAy./333yyWyWri$Ao^hy
@Mobm^o^qflkpcloqebRkabotloiayNFAy./333yyKyHfiiqoliip^olrkaqeb^iq^o%30+/)4-+4&ql`liib`q5XP^`oba>alokjbkqpZyyWyWri$Ao^hy
QMobm^o^qflkpcloqebRkabotloiayKyE^o$hl^%30+4)4-+0&yyNFAy./333yyWyWri$Ao^hy
>PbbhqebTfkaPbombkqDlaabppyKyE^o$hl^%30+4)4-+0&yyNFAy./334yyWyWri$Ao^hy
QPbbhqebTfkaPbombkqDlaabppyKyNrbqw$irk$pPmfofq%42+0)25+3&yyNFAy./334yyWyWri$Ao^hy
>PbqqfkdqebPq^dbyKyNrbqw$irk$pPmfofq%42+0)25+3&yyNFAy./34/yyWyWri$Ao^hy
@PbqqfkdqebPq^dbyNFAy./34/yyKyIllqqebcil^qfkd`ovpq^ipkb^oqeb^iqbo^olrka%40+/)25+3&yyWyWri$Ao^hy
QPbqqfkdqebPq^dbyKyNrbqw$irk$pPmfofq%42+0)25+3&yyNFAy./34/yyWyWri$Ao^hy
>Clrka^qflkcloObsbkdbyKyNrbqw$irk$pPmfofq%42+0)25+3&yyNFAy./335yyWyWri$Ao^hy
@Clrka^qflkcloObsbkdbyNFAy./335yyKyHfiiqoliipkb^oqebplriclkqp+Qebpb^ob_fdao^dlkeb^apq^qrbp^iilsbo%40+/)25+3&yyWyWri$Ao^hy
QClrka^qflkcloObsbkdbyKyNrbqw$irk$pPmfofq%42+0)25+3&yyNFAy./335yyWyWri$Ao^hy
>EbiiE^qe^CrovyKyNrbqw$irk$pPmfofq%42+0)25+3&yyNFAy./341yyWyWri$Ao^hy
@EbiiE^qe^CrovyNFAy./341yyRy06.25yyKyRpbXNrbqw$irk$pEbuufkdPqf`hZlk)qebkhfii)Qr^*Qr^%40+6)3-+/&)Jr$crkr%41+0)24+4&)^kaE^tfkkf%43+2)21+2&yyWyWri$Ao^hy
QEbiiE^qe^CrovyKyNrbqw$irk$pPmfofq%42+0)25+3&yyNFAy./341yyWyWri$Ao^hy
>LkbI^pqQefkdyKyNrbqw$irk$pPmfofq%42+0)25+3&yyNFAy./342yyWyWri$Ao^hy
QLkbI^pqQefkdyKyE^o$hl^%30+4)4-+0&yyNFAy./342yyWyWri$Ao^hy
>?illalc^Ab^aDlayKyE^o$hl^%30+4)4-+0&yyNFAy./351yyWyWri$Ao^hy
@?illalc^Ab^aDlayNFAy./351yyKyHfii?illalcJ^j$qlqe^qJ^j$qlqe@o^qbo%42+0)16+2&yyWyWri$Ao^hy
Q?illalc^Ab^aDlayKyE^o$hl^%30+4)4-+0&yyNFAy./351yyWyWri$Ao^hy
>VlrOb^mTe^qVlrPltyKyE^o$hl^%30+4)4-+0&yyNFAy./352yyWyWri$Ao^hy
@VlrOb^mTe^qVlrPltyNFAy./352yyRy06.54yyKy?^`h^qqeb>iq^olcNrbqw$irk%42+0)25+3&+RpbXNrbqw$irk$pOfqr^iZ^kahfiiqebmolmebqyyWyWri$Ao^hy

QVlrOb^mTe^qVlrPltyKyTfq`eAl`qloHercr%26+2)25+-&yyNFAy./352yyWyWri$Ao^hy
>TllivGrpqf`byKyP`^imbo>erk^b%26+/)23+0&yyNFAy./4-4yyWyWri$Ao^hy
>Bk`e^kqbaQfhfT^ooflopyKyBibjbkq*Q^jboA^dla^%26+2)23+2&yyNFAy./4-5yyWyWri$Ao^hy
>QebHbvlcT^oiloaWli$J^wyKyE^o$hl^%3-+.)24+4&yyNFAy./4./yyWyWri$Ao^hy
>Ebuba@^`ebpyKy@eolkf`iboQl$hfkf%26+6)24+6&yyNFAy./4-6yyWyWri$Ao^hy

@QebHbvlcT^oiloaWli$J^wyNFAy./4./yyRy060.1yyKyKloqeb^pq^qWli$J^wPqolkdelia+HfiiQfof%30+6)04+/&)Aobh$J^w%35+/)02+2&^kaV^o^%34+6)0/+6&cloqebfofqbjp+Qebkeb^armqlqebqlm%33+/)00+4&)rpblkblcqebfqbjpql`lj_fkbqebj)^karpbqebkbtfqbjqlpq^oqqebcfdeq+yyWyWri$Ao^hy
@Ebuba@^`ebpyNFAy./4-6yyRy060-2yyKyIllqqeb_^phbqp^olrkaWli$J^wPqolkdelia%3/+6)03+.&+?b`^robcri^_lrqqeb`ropbp+Qebqfhfpaolmfqbjpqlobjlsbqeb`ropbpyyWyWri$Ao^hy
@Bk`e^kqbaQfhfT^ooflopyNFAy./4-5yyKyHfiiqebBk`e^kqbaQfhfT^ooflop^olrkaWli$J^wPqolkdelia%3/+6)03+.&yyWyWri$Ao^hy
@TllivGrpqf`byNFAy./4-4yyRy06/35yyKyPlrqeb^pq^qqeb>iq^olcJ^j$qlqe%36+4)10+-&+RpbqebXJba^iiflklcJ^j$qlqeZlk^j^jjlqe)elmlk)^karpbqebj^jjlqeqlhfiikb^o_vqoliipyyWyWri$Ao^hy

QTllivGrpqf`byKyP`^imbo>erk^b%26+/)23+0&yyNFAy./4-4yyWyWri$Ao^hy
QBk`e^kqbaQfhfT^ooflopyKyBibjbkq*Q^jboA^dla^%26+2)23+2&yyNFAy./4-5yyWyWri$Ao^hy
QQebHbvlcT^oiloaWli$J^wyKyE^o$hl^%3-+.)24+4&yyNFAy./4./yyWyWri$Ao^hy
>O^jm^dbyKyE^o$hl^%3-+.)24+4&yyNFAy./4/.yyWyWri$Ao^hy
QEbuba@^`ebpyKy@eolkf`iboQl$hfkf%26+6)24+6&yyNFAy./4-6yyWyWri$Ao^hy
>Grpq@eb`hfk$yKy@eolkf`iboQl$hfkf%26+6)24+6&yyNFAy.0-66yyWyWri$Ao^hy

@O^jm^dbyNFAy./4/.yyKyKloqeb^pq)fkcolkqlcDrkao^h%46+-)/1+0&+Rkil`hb^`elc>h^if$p`e^fkpyyWyWri$Ao^hy
QGrpq@eb`hfk$yKy@eolkf`ibo?^e$Hfkf%4-+-)/.+-&yyNFAy.0-66yyWyWri$Ao^hy
>CloMlpqbofqvyKy@eolkf`ibo?^e$Hfkf%4-+-)/.+-&yyWyWri$Ao^hyyNFAy.0-65y
>Lkblc^HfkayKy@eolkf`ibo?^e$Hfkf%4-+-)/.+-&yyWyWri$Ao^hyyNFAy.0...y

cDrkao^hyKyO^c^b%4-+2)/0+/&yyNFAy./4/6yyWyWri$Ao^hy
CWfj$Qlod^yKyO^c^b%4-+2)/0+/&yyNFAy./4/6yyWyWri$Ao^hy

QO^jm^dbyKyTfq`eAl`qloHercr%26+2)25+-&yyNFAy./4/.yyWyWri$Ao^hy
>QebDlapE^sbPmlhbkyKyTfq`eAl`qloHercr%26+2)25+-&yyNFAy./4/6yyWyWri$Ao^hy
@QebDlapE^sbPmlhbkyKyHfiiDr^oaf^kp^q%3-)12&ql`liib`qXRk_ibjfpebaEb^oqlcqebDr^oaf^kZ^kahfiiT^oabkp^q%4/)25&ql`liib`qXDrpqvBppbk`blcqebT^oabkZvlrpelria_b^_ibqlplilqefp^pilkd^pvlrhfiiqebjlkb^q^qfjbyyNFAy./4/6yyWyWri$Ao^hy
QQebDlapE^sbPmlhbkyKyE^o$hl^%3-+.)24+4&yyNFAy./4/6yyWyWri$Ao^hy

>@lksl`^qflk^qWli$Eb_yKyE^o$hl^%3-+.)24+4&yyNFAy./40-yyWyWri$Ao^hy
@@lksl`^qflk^qWli$Eb_yKyRpbXMolmebqlc>h^if@lksl`^qflkZqlprjjlk^kahfiiqebMolmebqlc>h^if%44+3)00+3&yyNFAy./40-yyRy06233yyWyWri$Ao^hy
Q@lksl`^qflk^qWli$Eb_yKyE^o$hl^%3-+.)24+4&yyNFAy./40-yyWyWri$Ao^hy

>Rkcfkfpeba?rpfkbppyKyE^o$hl^%3-+.)24+4&yyNFAy.0-64yyWyWri$Ao^hy
QRkcfkfpeba?rpfkbppyKyQli$j^o%4-+.)//+6&yyNFAy.0-64yyWyWri$Ao^hy

>D^i$a^o^eJrpqM^vyKyQli$j^o%4-+.)//+6&yyNFAy.0-63yyWyWri$Ao^hy

ODrkao^hyKyNrbrbcloDrkao^htfqevlroarkdblkcfkaboyyNFAy.0-65yyWyWri$Ao^hyyFy

@CloMlpqbofqvyKyBkqboDrkao^h^kadbq3XAo^hh^ofEfpqlovQ^_ibqpZ+Qebq^_ibqpib^krm^d^fkpqqebt^iip)rpr^iivfk`lokbopyyNFAy.0-65y
@Lkblc^HfkayKyDbq^XAo^hh^of@lilpprpCo^djbkqZtef`eaolmplcclcqebAo^hh^ofBibjbkq^ipproolrkafkdqebAo^hh^of@lilpprp_lppyyNFAy.0...y
@D^i$a^o^eJrpqM^vyKyHfiiD^i$a^o^eqebcfk^i_lppfkDrkao^hyyNFAy.0-63y

OWri$Ao^hyKyQbibmloq_^`hqlWri$Ao^h%4-+-)/.+-&yyWyWri$Ao^hyyFy

QCloMlpqbofqvyKy@eolkf`ibo?^e$Hfkf%4-+-)/.+-&yyWyWri$Ao^hyyNFAy.0-65y
QLkblc^HfkayKy@eolkf`ibo?^e$Hfkf%4-+-)/.+-&yyWyWri$Ao^hyyNFAy.0...y
QD^i$a^o^eJrpqM^vyKyQli$j^o%4-+.)//+6&yyNFAy.0-63yyWyWri$Ao^hy

KDrfab@ljmibqb+@lkqfkrbQlE^iiplcPqlkb%44*46&yKyQf`hql`lkqfkrbqlE^iiplcPqlkb%44*46&*Riqfj^qbTlTDrfab+`ljy

]]
end)
