
DugisGuideViewer:RegisterGuide("Halls of Lightning (78-80)", nil, "Horde", "I", function()
return [[
AAA

KIbsbi44ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi44qlmf`hrmqebcliiltfkdnrbpqpyyNFAy./520yyMIy44y

OA^i^o^kyKyQo^sbiqlA^i^o^k%0.+4)2-&yyWyA^i^o^kyyNFAy./520y
>IruroflrpDbq^t^vyNFAy./520yyKyOfkArl`q^kb%0.+4)2-&yyWyA^i^o^ky
OQebPqlojMb^hpyKyQo^sbiqlQebPqlojMb^hp%1.)53+1&yyWyQebPqlojMb^hpyyNFAy./510y
QIruroflrpDbq^t^vyNFAy./520yyKyGbboPm^ohpl`hbq%1.)53+1&yyWyQebPqlojMb^hpy
>QebvQllhLroJbkyKyDobq`ebkCfwwibpm^oh%1.+.)53+.&yyNFAy./510yyWyQebPqlojMb^hpy
>BnrfmjbkqOb`lsbovyKyDobq`ebkCfwwibpm^oh%1.+.)53+.&yyNFAy./511yyWyQebPqlojMb^hpy

@QebvQllhLroJbkyNFAy./510yyKyObp`rb2Dl_ifkMofplkbop)`^dbp`^k_bclrka^olrkaqebPfcobia^oSfii^db^q%1.)4-&+Hbvpqlqeb`^dbpaolmlccqebPfcobia^oPqlojJ^fabkpyyWyQebPqlojMb^hpy
@BnrfmjbkqOb`lsbovyKyDbq5mfb`bplcXH0BnrfmjbkqZp`^qqbobalkqebdolrkafk_lubpqeolrdelrqqebsfii^db%1-)4/&yyNFAy./511yyWyQebPqlojMb^hpy

QQebvQllhLroJbkyKyDobq`ebkCfwwibpm^oh%1.+.)53+.&yyNFAy./510yyWyQebPqlojMb^hpy
>Ib^sbKlDl_ifk?befkayKyDobq`ebkCfwwibpm^oh%1.+.)53+.&yyNFAy./513yyWyQebPqlojMb^hpy
QBnrfmjbkqOb`lsbovyKyDobq`ebkCfwwibpm^oh%1.+.)53+.&yyNFAy./511yyWyQebPqlojMb^hpy

QIb^sbKlDl_ifk?befkayNFAy./513yyKyIlh$ifo^qeb@olkb%1/+5)35+6&fkpfabqebCloilokJfkbyyWyQebPqlojMb^hpy
>Qeb@olkb$p?^od^fkyKyIlh$ifo^qeb@olkb%1/+5)35+6&yyNFAy./51.yyWyQebPqlojMb^hpy
@Qeb@olkb$p?^od^fkyNFAy./51.yyKyDbqqebXOrkbplcqebVohsfkkZcoljLsbopbboPvo^telfprmqebo^jmqebafob`qflkIlh$ifo^fpc^`fkd)^kaqlqebofdeq%11+-)36+5&yyWyQebPqlojMb^hpy
QQeb@olkb$p?^od^fkyKyIlh$ifo^qeb@olkb%1/+5)35+6&yyNFAy./51.yyWyQebPqlojMb^hpy
>Jfiaobaqeb@orbiyKyIlh$ifo^qeb@olkb%1/+5)35+6&yyNFAy./6-2yyWyQebPqlojMb^hpy
QJfiaobaqeb@orbiyKyJfiaobaqeb@orbi%11+2)35+6&yyNFAy./6-2yyWyQebPqlojMb^hpy
>Afp`fmifkbyKyJfiaobaqeb@orbi%11+2)35+6&yyNFAy./6-3yyWyQebPqlojMb^hpy
@Afp`fmifkbyNFAy./6-3yyRy1/504yyKyRpbqebXAfp`fmifkfkdOlaZlk3Bue^rpqbaSovhrifkqebqrkkbip^olrka%12)4-&yyWyQebPqlojMb^hpy
QAfp`fmifkbyKyJfiaobaqeb@orbi%11+2)35+6&yyNFAy./6-3yyWyQebPqlojMb^hpy
>Bu^jmibpql_bJ^abyKyJfiaobaqeb@orbi%11+2)35+6&yyNFAy./6-4yyWyQebPqlojMb^hpy
@Bu^jmibpql_bJ^abyNFAy./6-4yyKyHfiiD^oe^ifkqebollj_befkaJfiaoba%12+2)36&yyWyQebPqlojMb^hpy
QBu^jmibpql_bJ^abyKyJfiaobaqeb@orbi%11+2)35+6&yyNFAy./6-4yyWyQebPqlojMb^hpy
>>@boq^fkMofplkboyKyJfiaobaqeb@orbi%11+2)35+6&yyNFAy./6-5yyWyQebPqlojMb^hpy
Q>@boq^fkMofplkboyKyIlh$ifo^qeb@olkb%1/+5)35+6&yyNFAy./6-5yyWyQebPqlojMb^hpy
>>@e^kdblcP`bkbovyKyIlh$ifo^qeb@olkb%1/+5)35+6&yyNFAy./6/.yyWyQebPqlojMb^hpy

Q>@e^kdblcP`bkbovyNFAy./6/.yyKyIlh$ifo^qeb@olkb%14+2)36+.&yyWyQebPqlojMb^hpy
>FpQe^qVlroDl_ifk<yNFAy./636yyKyIlh$ifo^qeb@olkb%14+2)36+.&yyWyQebPqlojMb^hpy
@FpQe^qVlroDl_ifk<yNFAy./636yyKy@e^iibkdb>dkbqq^Qvopalqq^o%15+/)36+4&^kahfiieboyyWyQebPqlojMb^hpy
QFpQe^qVlroDl_ifk<yNFAy./636yyKyIlh$ifo^qeb@olkb%14+2)36+.&yyWyQebPqlojMb^hpy
>QebEviapjbbqyNFAy./64-yyKyIlh$ifo^qeb@olkb%14+2)36+.&yyWyQebPqlojMb^hpy
@QebEviapjbbqyNFAy./64-yyKyGrpqifpqbkqlIlh$ifo^qeb@olkb%14+2)36+.&yyWyQebPqlojMb^hpy
QQebEviapjbbqyNFAy./64-yyKyIlh$ifo^qeb@olkb%14+2)36+.&yyWyQebPqlojMb^hpy
>Q^hfkdlk>ii@e^iibkdbopyKyIlh$ifo^qeb@olkb%14+2)36+.&yyNFAy./64.yyWyQebPqlojMb^hpy
@Q^hfkdlk>ii@e^iibkdbopyNFAy./64.yyKyHfii3Sf`qloflrp@e^iibkdbop^olrka%2.)33&yyWyQebPqlojMb^hpy
QQ^hfkdlk>ii@e^iibkdbopyKyIlh$ifo^qeb@olkb%14+2)36+.&yyNFAy./64.yyWyQebPqlojMb^hpy
>Vlr$iiKbba^?b^oyKyIlh$ifo^qeb@olkb%14+2)36+.&yyNFAy./64/yyWyQebPqlojMb^hpy

QVlr$iiKbba^?b^oyNFAy./64/yyKy?ofg^k^%20+/)32+5&yyWyQebPqlojMb^hpy
>Dlfkd?b^o_^`hyNFAy./52.yyKy?ofg^k^%20+/)32+5&yyWyQebPqlojMb^hpy
@Dlfkd?b^o_^`hyNFAy./52.yyKyJlrkqF`bc^kd%20+/)32+4&^kapellq4Colpqtlodp^ka.2ColpqDf^kqp+Vlre^sbkl`lkqolilsboqeb_b^olqeboqe^kpmbbafkdfqrmyyWyQebPqlojMb^hpy
QDlfkd?b^o_^`hyNFAy./52.yyKy?ofg^k^%20+/)32+5&yyWyQebPqlojMb^hpy
>@liaEb^oqbayNFAy./523yyKy?ofg^k^%20+/)32+5&yyWyQebPqlojMb^hpy
@@liaEb^oqbayNFAy./523yyKyCivqlArkKfccbibj^q%31)26&)cfka^Molql*Ao^hbqlofab^kaciv^olrkaillhfkdclo?orkkefia^oMofplkbopbk`^pbafkf`b+W^mqebjlk`btfqeqebcolpq_liqql_ob^hqebjcobb+Tebkvlre^sb0mofplkbop)civ_^`hql?orkkefia^oSfii^db+Obmb^qqefp0qfjbpyyWyQebPqlojMb^hpy
Q@liaEb^oqbayNFAy./523yyKy?ofg^k^%20+/)32+5&yyWyQebPqlojMb^hpy
>AbbjbaTloqevyNFAy.0-30yyKy?ofg^k^%20+/)32+5&yyWyQebPqlojMb^hpy

QAbbjbaTloqevyNFAy.0-30yyKy>pqofa?glokofqq^o%16+5)4.+5&yyWyQebPqlojMb^hpy
>J^hfkd^E^okbppyNFAy./6--yyKy>pqofa?glokofqq^o%16+5)4.+5&yyWyQebPqlojMb^hpy
@J^hfkd^E^okbppyNFAy./6--yyKyHfiiF`bj^kbVbqfp^olrka%15+0)41+6&qldbq0XF`bj^kbVbqfEfabpZyyWyQebPqlojMb^hpy
QJ^hfkd^E^okbppyNFAy./6--yyKy>pqofa?glokofqq^o%16+5)4.+5&yyWyQebPqlojMb^hpy
>QebI^pqlcEboHfkayNFAy./650yyKy>pqofa?glokofqq^o%16+5)4.+5&yyWyQebPqlojMb^hpy
>QebPifqebofkdA^ohkbppyNFAy./656yyKy>pqofa?glokofqq^o%16+5)4.+5&yyWyQebPqlojMb^hpy
@QebPifqebofkdA^ohkbppyNFAy./656yyKyHfii5O^sbklrpGlojrkd^ofkqebEf_bok^i@^sbok+Qebbkqo^k`bfp^q%23+-)31+0&yyWyQebPqlojMb^hpy
@QebI^pqlcEboHfkayNFAy./650yyKyObp`rb^kF`bj^tJ^qof^o`efkqebb^pqbokm^oqlcqeb`^sb%21+5)3-+1&yyWyQebPqlojMb^hpy
QQebPifqebofkdA^ohkbppyNFAy./656yyKy>pqofa?glokofqq^o%16+5)4.+5&yyWyQebPqlojMb^hpy
QQebI^pqlcEboHfkayNFAy./650yyKy>pqofa?glokofqq^o%16+5)4.+5&yyWyQebPqlojMb^hpy
>QebT^oj*RmyNFAy./663yyKy>pqofa?glokofqq^o%16+5)4.+5&yyWyQebPqlojMb^hpy
@QebT^oj*RmyNFAy./663yyRy1/15.yyKyRpbqebXObfkplcqebF`bj^tJ^qof^o`eZqlabcb^qHfod^o^^hfkpfab?orkkefia^oSfii^db`e^fkbarm^q%2-+5)34+3&yyWyQebPqlojMb^hpy
QQebT^oj*RmyNFAy./663yyKy>pqofa?glokofqq^o%16+5)4.+5&yyWyQebPqlojMb^hpy
>FkqlqebMfqyNFAy./664yyKy>pqofa?glokofqq^o%16+5)4.+5&yyWyQebPqlojMb^hpy
@FkqlqebMfqyNFAy./664yyRy1/166yyKyRpbqebXObfkplcqebF`bj^tJ^qof^o`eZ^qqebmfqfkqebjfaaiblcqebsfii^db^kaabcb^q3EviapjbbqT^o_b^op%16+3)35+.&yyWyQebPqlojMb^hpy
QFkqlqebMfqyNFAy./664yyKy>pqofa?glokofqq^o%16+5)4.+5&yyWyQebPqlojMb^hpy
>Mobm^obcloDilovyNFAy.0-3.yyKy>pqofa?glokofqq^o%16+5)4.+5&yyWyQebPqlojMb^hpy

QMobm^obcloDilovyNFAy.0-3.yyKyIlh$ifo^qeb@olkb%14+2)36+.&yyWyQebPqlojMb^hpy
>Ilh$ifo^$pM^oqfkdDfcqyNFAy.0-3/yyKyIlh$ifo^qeb@olkb%14+2)36+.&yyWyQebPqlojMb^hpy
QIlh$ifo^$pM^oqfkdDfcqyNFAy.0-3/yyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyWyQebPqlojMb^hpy
>QebAo^hhbkpovayNFAy./553yyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyWyQebPqlojMb^hpy
@QebAo^hhbkpovayNFAy./553yyRy1.-25yyKyRpbqebXEviakfoE^omllkZqlhfii.-EviapjbbqAo^hbofabop^qqebQbjmiblcPqlojp%02)3-&+Tebkvlr$obalkbrpbqebe^omllklklkblcqeb`lirjklok^jbkqpqlbufq+Afpjfppvlrombq_bclobpq^oqfkdqefpnrbpqloqebe^omllktlk$qtlohyyWyQebPqlojMb^hpy
QQebAo^hhbkpovayNFAy./553yyKyQelofj%00+2)25&yyWyQebPqlojMb^hpy
>Pf_ifkdOfs^iovyNFAy.0-31yyKyQelofj%00+2)25&yyWyQebPqlojMb^hpy
@Pf_ifkdOfs^iovyNFAy.0-31yyKyIfpqbkqlQelofj$ppqlov%00+2)25&yyWyQebPqlojMb^hpy
QPf_ifkdOfs^iovyNFAy.0-31yyKyQelofj%00+2)25&yyWyQebPqlojMb^hpy
>JbkafkdCbk`bpyNFAy./6.2yyKyQelofj%00+2)25&yyWyQebPqlojMb^hpy

@JbkafkdCbk`bpyNFAy./6.2yyKyCfka^XDo^kfqb?lriaboZlkqebdolrka%42)31&)rpbXQelofj$p@e^ojlcB^oqeZlkPqlojclodbaFolkDf^kqp+Lk`b2df^kqp^obhfiiba+Mf`hrm^klqebo_lriabo^kahfiiCglokyyRy1.2-2yyWyQebPqlojMb^hpy
>QebObcfkbo$pCfobyKyQebfqbjXPi^d@lsbobaJbq^iZpq^oqpnrbpq*aolmmba_vPqlojclodbaFolkDf^kqp^olrka%42)31&yyNFAy./6//yyRy1.223yyWyQebPqlojMb^hpy
@QebObcfkbo$pCfobyNFAy./6//yyKy@liib`q.-XCroflrpPm^ohpZcoljqebPbbqefkdObsbk^kqp^qColpqcfbiaI^hb%4-)26&yyWyQebPqlojMb^hpy
QQebObcfkbo$pCfobyNFAy./6//yyKyCglok$p>ksfi%44+.)3/+5&yyWyQebPqlojMb^hpy
>>Pm^ohlcElmbyNFAy./623yyKyCglok$p>ksfi%44+.)3/+5&yyWyQebPqlojMb^hpy

QJbkafkdCbk`bpyNFAy./6.2yyKyQelofj%00+2)25&yyWyQebPqlojMb^hpy
Q>Pm^ohlcElmbyNFAy./623yyKyQelofj%00+2)25&yyWyQebPqlojMb^hpy
>Clodfkd^k>iif^k`byNFAy./6/1yyKyQelofj%00+2)25&yyWyQebPqlojMb^hpy
>Vlr@^k$qJfppEfjyNFAy./633yyKyHfkdGlhhrj%32+2)3-+/&yyWyQebPqlojMb^hpy
QVlr@^k$qJfppEfjyNFAy./633yyKyKglojbia%42+2)30+3&yyWyQebPqlojMb^hpy
>?^qqifkdqebBibjbkqpyNFAy./634yyKyKglojbia%42+2)30+3&yyWyQebPqlojMb^hpy
@?^qqifkdqebBibjbkqpyNFAy./634yyKyJlrkqPkloof%kbuqqlnrbpqdfsbo&^kat^ihql^pklt_rjm)mf`hfqrm)q^_rkqfivlrdbq^PbbqefkdObsbk^kq+Hfii.-PbbqefkdObsbk^kqp%44)3/&yyWyQebPqlojMb^hpy
Q?^qqifkdqebBibjbkqpyNFAy./634yyKyKglojbia%42+2)30+3&yyWyQebPqlojMb^hpy

QClodfkd^k>iif^k`byNFAy./6/1yyKyKglojbia%30+0)30+/&yyWyQebPqlojMb^hpy
>>Kbt?bdfkkfkdyNFAy.0--6yyKyKglojbia%30+0)30+/&yyWyQebPqlojMb^hpy

>Glojrqq^ofpPllC^q+++yNFAy.0-..yyKyHfkdGlhhrj%32+2)3-+/&yyWyQebPqlojMb^hpy
@Glojrqq^ofpPllC^q+++yNFAy.0-..yyKyBkqboqebEf_bok^i@^sbok%22+6)31+.&^kahfiiGlojrqq^o%21+4)3-+5&+RpbqebXBsbocolpqO^wloZlk^_b^o)qebkrpbqebci^kh^qqeb`o^qbokb^otebobvlrdlqvlro_b^ob^oifboyyRy1/40/yyWyQebPqlojMb^hpy
QGlojrqq^ofpPllC^q+++yNFAy.0-..yyKyHfkdGlhhrj%32+2)3-+/&yyWyQebPqlojMb^hpy

Q>Kbt?bdfkkfkdyNFAy.0--6yyKyQelofj%00+2)25&yyWyQebPqlojMb^hpy
>Sbo^krpyNFAy.0-2-yyKyQelofj%00+2)25&yyWyQebPqlojMb^hpy
@Sbo^krpyNFAy.0-2-yyKyIllq2XPj^iiMolql*Ao^hbBddpZcoljqebkbpqpkloqetbpq%12+1)34&)%10+4)34+1&^kaplrqeb^pq%2/+1)40+/&)%20+3)41+4&lc?orkkefia^oSfii^dbyyWyQebPqlojMb^hpy
QSbo^krpyNFAy.0-2-yyKyQelofj%00+2)25&yyWyQebPqlojMb^hpy
>Qboofqlof^iQobpm^ppyNFAy.0-2.yyKyQelofj%00+2)25&yyWyQebPqlojMb^hpy
@Qboofqlof^iQobpm^ppyNFAy.0-2.yyRy1/464yyKyMi^`bqebXPqlibkMolql*Ao^dlkBddpZlkqlmlcqeb?ollajlqebo$pKbpq%05+4)32+3&yyWyQebPqlojMb^hpy
QQboofqlof^iQobpm^ppyNFAy.0-2.yyKyQelofj%00+2)25&yyWyQebPqlojMb^hpy
>Holijfo)E^jjbolcPqlojpyNFAy.0-.-yyKyQelofj%00+2)25&yyWyQebPqlojMb^hpy

@Holijfo)E^jjbolcPqlojpyNFAy.0-.-yyKyQ^ihqlHfkdGlhhrjfkArkKfccbibj%32+2)3-+/&yyWyQebPqlojMb^hpy
QHolijfo)E^jjbolcPqlojpyNFAy.0-.-yyKyQelofj%4.+1)15+5&yyWyQebPqlojMb^hpy
>QebQboo^`blcqebJ^hbopyNFAy.0-24yyKyQelofj%4.+1)15+5&yyWyQebPqlojMb^hpy

QQebQboo^`blcqebJ^hbopyNFAy.0-24yyKyQelofj%23+/)2.+1&yyWyQebPqlojMb^hpy
>QebB^oqebkL^qeyNFAy.0--2yyKyQelofj%23+/)2.+1&yyWyQebPqlojMb^hpy
>Ilhbk$pI^`hbvpyNFAy.0-02yyKyQelofj%23+/)2.+1&yyWyQebPqlojMb^hpy
@Ilhbk$pI^`hbvpyNFAy.0-02yyKyRpbqebXEloklcqebMb^hpZqlebimvlrhfii)Bfpbkc^rpqkloqefkpfabqebE^iilcqebPe^mbo%22+2)10+2&)E^ibckfoqebTfka_lokfpm^oqt^valtkqebpq^fopqlqebtbpq%15)12&)^kaArolkkqebOrkbtolrdeqfp^qqeb_lqqljlcqebpq^fop%11)04&yyRy1/51-yyWyQebPqlojMb^hpy
@QebB^oqebkL^qeyNFAy.0--2yyKyRpbqebXEloklcqebMb^hpZ^olrka%20)2.&qlprjjlkqebB^oqebkqlabcb^q/-FolkAt^osbp^ka4FolkPbkqfkbipyyRy1/51-yyWyQebPqlojMb^hpy
QQebB^oqebkL^qeyNFAy.0--2yyKyQelofj%23+/)2.+1&yyWyQebPqlojMb^hpy
QIlhbk$pI^`hbvpyNFAy.0-02yyKyQelofj%23+/)2.+1&yyWyQebPqlojMb^hpy
>QebOb`hlkfkdyNFAy.0-14yyKyQelofj%23+/)2.+1&yyWyQebPqlojMb^hpy

@QebOb`hlkfkdyNFAy.0-14yyKyJbbqQelofjkb^oqebQbjmiblcTfpalj%03)0/&yyWyQebPqlojMb^hpy
QQebOb`hlkfkdyNFAy.0-14yyKyHfkdGlhhrj%32+2)3-+/&yyWyQebPqlojMb^hpy

>Te^qbsbofqQ^hbpyKyHfkdGlhhrj%32+2)3-+/&yyNFAy.0.-5yyWyQebPqlojMb^hpy
>Af^jbqof`^iivLmmlpbayKyHfkdGlhhrj%32+2)3-+/&yyNFAy.0.-6yyWyQebPqlojMb^hpy

OE^iiplcIfdeqkfkdyKyNrbrbcloE^iiplcIfdeqkfkdrpfkdvlroarkdblkcfkaboyyNFAy.0.-5yyFy

@Af^jbqof`^iivLmmlpbayKyAbcb^qSlihe^kebqeb_lpp_vqebcrok^`byyNFAy.0.-6y
@Te^qbsbofqQ^hbpyKyHfiiIlhbkqebcfk^i_lppfkE^iiplcIfdeqkfkd^kaillqXIlhbk$pQlkdrbZyyNFAy.0.-5y

OQebPqlojMb^hpyKyQbibmloq_^`hqlQebPqlojMb^hp%32+2)3-+/&yyWyQebPqlojMb^hpyyFy

QTe^qbsbofqQ^hbpyKyHfkdGlhhrj%32+2)3-+/&yyNFAy.0.-5yyWyQebPqlojMb^hpy
QAf^jbqof`^iivLmmlpbayKyHfkdGlhhrj%32+2)3-+/&yyNFAy.0.-6yyWyQebPqlojMb^hpy

KDrfab@ljmibqb*@lkqfkrbqlRiqfj^qbTlTDrfab+`lj

]]
end)
