DugisGuideViewer:RegisterGuide("Alliance Vanguard/Valliance Expedition (2500 +Rep)", nil, "Alliance", "D", function()
return [[
AAA

OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&yyWyF`b`oltky
>@^mqrobJlobAfpm^q`ebpyKyEfde@^mq^fkGrpqfk?^oqibqqlkQebPhv_ob^hboyyNFAy.0000yyWyF`b`oltkyyAy
>?illalcqeb@elpbkyKyHkfdeq*@^mq^fkAolp`ebOfleqlkQebPhv_ob^hboyyNFAy.0003yyWyF`b`oltkyyAy

@@^mqrobJlobAfpm^q`ebpyKyRpbXA^oqDrkZql`^mqrob3Lodofj$pE^jjboAfpm^q`e^olrka%15)21&yyRy11///yyNFAy.0000yyWyF`b`oltkyyAy

>>pp^riq_vDolrkayKyPhv_ob^hboPnr^aIb^abo%3/+4)2.&yyNFAy.0/51yyWyF`b`oltkyyAy
@>pp^riq_vDolrkayKyBp`loqqebPhv_ob^hboqollmpyyNFAy.0/51yyWyF`b`oltkyyAy
@?illalcqeb@elpbkyKyHfii/-VjfoebfjSovhri^qVjfoebfj%26)21&yyNFAy.0003yyWyF`b`oltkyyAy
Q>pp^riq_vDolrkayKyDolrka@ljj^kaboHlrm%3/+3)2.+0&yyNFAy.0/51yyWyF`b`oltkyyAy

>>pp^riq_v>foyKyDolrka@ljj^kaboHlrm%3/+3)2.+0&yyNFAy.00-6yyWyF`b`oltkyyAy
@>pp^riq_v>foyKyDlql%26+3)13+-&^kajlrkqqeb>fomi^kb)j^hbprobqebob^obfkcfiqo^qlopfkqebmi^kb_bclobvlrdlyyNFAy.00-6yyWyF`b`oltkyyAy
Q>pp^riq_v>foyKyDolrka@ljj^kaboHlrm%3/+3)2.+0&yyNFAy.00-6yyWyF`b`oltkyyAy

>HfkdlcqebJlrkq^fkyKyCo^wwibDb^odofkabo%24)3/+2&yyNFAy.0/5-yyWyF`b`oltkyyAy
@HfkdlcqebJlrkq^fkyKyJlrkqQerkabo_lj_$pGrjm_lqkbuqqlvlr^kagrjmvlrot^vrmqlqebmfiblc_lkbp%21)26&yyNFAy.0/5-yyWyF`b`oltkyyAy
QHfkdlcqebJlrkq^fkyKyCo^wwibDb^odofkabo%24)3/+2&yyNFAy.0/5-yyWyF`b`oltkyyAy

OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&yyWyF`b`oltky
Q@^mqrobJlobAfpm^q`ebpyKyEfde@^mq^fkGrpqfk?^oqibqqlkQebPhv_ob^hboyyNFAy.0000yyWyF`b`oltkyyAy
Q?illalcqeb@elpbkyKyHkfdeq*@^mq^fkAolp`ebOfleqlkQebPhv_ob^hboyyNFAy.0003yyWyF`b`oltkyyAy

KCfkaCifdeqJ^pqboyKy@ilpbpqcifdeqj^pqbocoljPhv_ob^hbotlriabfqebo_bJloif^Alljtfkd%10+4)/1+2&fkPe^altS^riqloMbkrj_ofrp%46+2)4/+0&fk@orp^abo$pMfkk^`ibyyWyF`b`oltky
C>j_bomfkbIladbyKyCivql>j_bomfkbIladbfkDofwwivEfiipyyAy

>?i^`hofsboPhfojfpeyKyP`lrq@^mq^fk@^oqbo%0-)26+5&yyNFAy./111yyWyDofwwivEfiipyyAy
@?i^`hofsboPhfojfpeyKyHfii.-EloabKM@ploMi^vbopfk?i^`hofsboIlddfkd@^jm%/5+2)3/+3&yyNFAy./111yyWyDofwwivEfiipyyAy
Q?i^`hofsboPhfojfpeyKyP`lrq@^mq^fk@^oqbo%0-)26+5&yyNFAy./111yyWyDofwwivEfiipyyAy

>Hf`h$BjTefibQebv$obAltkyKyPbodb^kqE^oqpj^k%06+1)10+5&yyNFAy.//56yyWyDofwwivEfiipyyAy
>PeobaaboObm^foyKyPvkfmrp%06+2)10+3&yyNFAy.//11yyWyDofwwivEfiipyyAy
>Mfb`bpM^oqpyKyMfmqet^`h%06+3)10+1&yyNFAy.//35yyWyDofwwivEfiipyyAy
>IfcbloAb^qeyKyOeb^kk^%1-+2)1/+3&yyNFAy.//63yyWyDofwwivEfiipyyAy

@IfcbloAb^qeyKyCfkaqebTlrkabaPliafbop%02)1-&^karpbqebXObkbtfkd?^ka^dbZlkqebjyyRy04243yyNFAy.//63yyWyDofwwivEfiipyyAy
@Mfb`bpM^oqpyKy@liib`q^iiqebmfb`bp^olrka%02)1-&yyNFAy.//35yyWyDofwwivEfiipyyAy
@PeobaaboObm^foyKyMf`hrm^Peobaabo%02)1-&^ka_ofkdfq_^`hqlPvkfmrp%06+2)10+3&yyNFAy.//11yyWyDofwwivEfiipyyAy
@Hf`h$BjTefibQebv$obAltkyKyHfii.2EloabKM@ploMi^vbopfk?irbPhvIlddfkdDolrkap%02)1-&yyNFAy.//56yyWyDofwwivEfiipyyAy

QPeobaaboObm^foyKyPvkfmrp%06+2)10+3&yyNFAy.//11yyWyDofwwivEfiipyyAy
QMfb`bpM^oqpyKyMfmqet^`h%06+3)10+1&yyNFAy.//35yyWyDofwwivEfiipyyAy
QIfcbloAb^qeyKyOeb^kk^%1-+2)1/+3&yyNFAy.//63yyWyDofwwivEfiipyyAy
QHf`h$BjTefibQebv$obAltkyKyPbodb^kqE^oqpj^k%06+1)10+5&yyNFAy.//56yyWyDofwwivEfiipyyAy

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
