DugisGuideViewer:RegisterGuide("Argent Tournament (Champion Dailies)", nil, "Alliance", "D", function()
return [[
AAA

C>odbkqQlrok^jbkqDolrkapyKyCivql>odbkqQlrok^jbkqDolrkapfkF`b`oltk%4/+3)//+3&yyWyF`b`oltky

>?^qqib?bclobQeb@fq^abiyKy@olhP`lrodb_^kb%40+5).6+5&)A^fivyyNFAy.0531yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy
>Qeob^qColj>_lsbyKy@olhP`lrodb_^kb%40+5).6+5&)A^fivyyNFAy.0455yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy
>Q^hfkd?^qqibQlQebBkbjvyKyWlo$_bqeb?illaibqqbo%40+5).6+1&)A^fivyyNFAy.046.yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy
>>jlkdqeb@e^jmflkpyKyFiivofbKfdeqc^ii%40+3)/-&)A^fivyyNFAy.0460yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy

>Qeob^qColj>_lsbyKyB^aof`qebMrob%36+6)/0+1&)A^fivyyNFAy.035/yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
>?^qqib?bclobQeb@fq^abiyKyB^aof`qebMrob%36+6)/0+1&)A^fivyyNFAy.053.yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
>Q^hfkd?^qqibQlQebBkbjvyKy@biif^kA^v_ob^h%36+6)/0+2&)A^fivyyNFAy.0456yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
>>jlkdqeb@e^jmflkpyKyIrrof%36+6)/0+1&)A^fivyyNFAy.046-yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy

KMf`hrm0S^if^kqNrbpqpyKyMf`hrm0NrbpqpfkPfisbo@lsbk^kqM^sfiflk%43+/).6+3&$>S^if^kq$pCfbiaQo^fkfkd$)$QebDo^kaJbibb$)^ka$>qqebBkbjvpD^qbp$yyWyF`b`oltky
ePfisbo@lsbk^kqM^sfiflkyKyJ^hbprobvlropbqvlroeb^oqepqlkbql>odbkqQlrok^jbkqDolrkap@^ofpPrki^k`b%43+/).6+3&yyWyF`b`oltky

>>S^if^kq$pCfbiaQo^fkfkdyKyP^^kalp%43+0).6+2&)A^fivyyNFAy.0422yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyOliilProbpelq%43+0).6+2&)A^fivyyNFAy.0411yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyQf`hfkDb^opm^kkbo%43+0).6+2&)A^fivyyNFAy.0416yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyPfoJ^o`rp?^oiltb%43+0).6+2&)A^fivyyNFAy.026/yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyiibpqof^?i^abpfkdbo%43+0).6+2&)A^fivyyNFAy.043-yyLyyWyF`b`oltkyyAy

>QebDo^kaJbibbyKyO^kff%43+0).6+2&)A^fivyyNFAy.0423yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKy@i^o^Qrj_ib_obt%43+0).6+2&)A^fivyyNFAy.0412yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKyCif`hfkDb^opm^kkbo%43+0).6+2&)A^fivyyNFAy.042-yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKy@^mq^fkGlpbmeEliibv%43+0).6+2&)A^fivyyNFAy.0332yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKy>fo^bPq^opbbhbo%43+0).6+2&)A^fivyyNFAy.043.yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKyO^kff%43+0).6+2&)A^fivyyNFAy.0521yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKy@i^o^Qrj_ib_obt%43+0).6+2&)A^fivyyNFAy.052.yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKyCif`hfkDb^opm^kkbo%43+0).6+2&)A^fivyyNFAy.052/yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKy@^mq^fkGlpbmeEliibv%43+0).6+2&)A^fivyyNFAy.0514yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKy>fo^bPq^opbbhbo%43+0).6+2&)A^fivyyNFAy.0522yyLyyWyF`b`oltkyyAy

KDbqlkJlrkqyKyBnrfmX>iif^k`bI^k`bZ^kadbq^Jlrkq%42+6)/-+1&lo%4.+52)/-&yyRy13-36yyWyF`b`oltky
@QebDo^kaJbibbyKyDlqlQeb>iif^k`b$pS^if^kqOfkd%42+0).5+0&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0423yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQeb>iif^k`b$pS^if^kqOfkd%42+0).5+0&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0412yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQeb>iif^k`b$pS^if^kqOfkd%42+0).5+0&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.042-yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQeb>iif^k`b$pS^if^kqOfkd%42+0).5+0&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0332yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQeb>iif^k`b$pS^if^kqOfkd%42+0).5+0&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.043.yyLyyWyF`b`oltkyyAy
@>jlkdqeb@e^jmflkpyKyQ^ihqlPnrfobA^kkv%35+3)/.&ql_bdfkqebcfdeqyyNFAy.0460yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy
@>jlkdqeb@e^jmflkpyKyAbcb^q1@e^jmflkp^qqebOfkdlc@e^jmflkp%4.+2)/0+5&yyNFAy.046-yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy

@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolp%10+4)2-+/&yyNFAy.0422yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolp%10+4)2-+/&yyNFAy.0411yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolp%10+4)2-+/&yyNFAy.0416yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolp%10+4)2-+/&yyNFAy.026/yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolp%10+4)2-+/&yyNFAy.043-yyLyyWyF`b`oltkyyAy
@Q^hfkd?^qqibQlQebBkbjvyKyHfii^kvP`lrodb^olrka%4.+1)04+6&yyNFAy.046.yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy
@Q^hfkd?^qqibQlQebBkbjvyKyHfii^kvP`lrodb^olrka%4.+1)04+6&yyNFAy.0456yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy

@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyLyyNFAy.0521yyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyLyyNFAy.052.yyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyLyyNFAy.052/yyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyLyyNFAy.0514yyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyLyyNFAy.0522yyWyF`b`oltkyyAy

@?^qqib?bclobQeb@fq^abiyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo)rpbvlroPefbia?ob^hboqlhfiid^odlvibp+Orklsbo^kvobdri^op`lrodbphbiifbp^karpbqebrpr^iq^`qf`^d^fkpqvlrojlrkqbalmmlkbkqp+yyNFAy.0531yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy
@?^qqib?bclobQeb@fq^abiyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo)rpbvlroPefbia?ob^hboqlhfiid^odlvibp+Orklsbo^kvobdri^op`lrodbphbiifbp^karpbqebrpr^iq^`qf`^d^fkpqvlrojlrkqbalmmlkbkqp+yyNFAy.053.yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy

@Qeob^qColj>_lsbyKyHfii@efiij^t%12+3)0.+5&^ka0u@riqfpq?lj_^oafboyyNFAy.0455yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy
@Qeob^qColj>_lsbyKyHfii@efiij^t%12+3)0.+5&^ka0u@riqfpq?lj_^oafboyyNFAy.035/yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy

Q>S^if^kq$pCfbiaQo^fkfkdyKyP^^kalp%43+0).6+2&)A^fivyyNFAy.0422yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyOliilProbpelq%43+0).6+2&)A^fivyyNFAy.0411yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyQf`hfkDb^opm^kkbo%43+0).6+2&)A^fivyyNFAy.0416yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyPfoJ^o`rp?^oiltb%43+0).6+2&)A^fivyyNFAy.026/yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyiibpqof^?i^abpfkdbo%43+0).6+2&)A^fivyyNFAy.043-yyLyyWyF`b`oltkyyAy

QQebDo^kaJbibbyKyO^kff%43+0).6+2&)A^fivyyNFAy.0423yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKy@i^o^Qrj_ib_obt%43+0).6+2&)A^fivyyNFAy.0412yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKyCif`hfkDb^opm^kkbo%43+0).6+2&)A^fivyyNFAy.042-yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKy@^mq^fkGlpbmeEliibv%43+0).6+2&)A^fivyyNFAy.0332yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKy>fo^bPq^opbbhbo%43+0).6+2&)A^fivyyNFAy.043.yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKyO^kff%43+0).6+2&)A^fivyyNFAy.0521yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKy@i^o^Qrj_ib_obt%43+0).6+2&)A^fivyyNFAy.052.yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKyCif`hfkDb^opm^kkbo%43+0).6+2&)A^fivyyNFAy.052/yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKy@^mq^fkGlpbmeEliibv%43+0).6+2&)A^fivyyNFAy.0514yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKy>fo^bPq^opbbhbo%43+0).6+2&)A^fivyyNFAy.0522yyLyyWyF`b`oltkyyAy

Q?^qqib?bclobQeb@fq^abiyKy@olhP`lrodb_^kb%40+5).6+5&)A^fivyyNFAy.0531yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy
QQeob^qColj>_lsbyKy@olhP`lrodb_^kb%40+5).6+5&)A^fivyyNFAy.0455yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy
QQ^hfkd?^qqibQlQebBkbjvyKyWlo$_bqeb?illaibqqbo%40+5).6+1&)A^fivyyNFAy.046.yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy
Q>jlkdqeb@e^jmflkpyKyFiivofbKfdeqc^ii%40+3)/-&)A^fivyyNFAy.0460yy@yAb^qeHkfdeqyyWyF`b`oltkyyAy

QQeob^qColj>_lsbyKyB^aof`qebMrob%36+6)/0+1&)A^fivyyNFAy.035/yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
QQ^hfkd?^qqibQlQebBkbjvyKy@biif^kA^v_ob^h%36+6)/0+2&)A^fivyyNFAy.0456yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
Q?^qqib?bclobQeb@fq^abiyKyB^aof`qebMrob%36+6)/0+1&)A^fivyyNFAy.053.yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy
Q>jlkdqeb@e^jmflkpyKyIrrof%36+6)/0+1&)A^fivyyNFAy.046-yy@yAorfa)Erkqbo)Pe^j^k)M^i^afk)Oldrb)Mofbpq)T^oil`h)T^ooflo)J^dbyyWyF`b`oltkyyAy

KDrfab@ljmibqb
]]
end)
