DugisGuideViewer:RegisterGuide("Argent Tournament (Aspirant Dailies)", nil, "Alliance", "D", function()
return [[
AAA

C>odbkqQlrok^jbkqDolrkapyKyCivql>odbkqQlrok^jbkqDolrkapfkF`b`oltk%4/+3)//+3&yyWyF`b`oltky

KMf`hrm0A^fivNrbpqyKy>o`^kfpqQ^bifp%43+2).6+2&lccbop.lc0o^kalja^fivnrbpqpyyWyF`b`oltky
>QebBadbLcTfkqboyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.034-yyWyF`b`oltkyyAy
>>?i^abCfqClo>@e^jmflkyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.0333yyWyF`b`oltkyyAy
>>TloqevTb^mlkyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.0336yyWyF`b`oltkyyAy
>Qo^fkfkdFkQebCfbiayKy>s^obqePtfcqpqofhb%43+2).6+1&)A^fivyyNFAy.034.yyWyF`b`oltkyyAy
>Ib^okfkdQebObfkpyKyP`lrqPe^ivkaof^%43+2).6+2&)A^fivyyNFAy.03/2yyWyF`b`oltkyyAy

KDbqlkJlrkqyKyBnrfmX>iif^k`bI^k`bZ^kadbq^Jlrkq%42+6)/-+1&lo%4.+52)/-&yyRy13-36yyWyF`b`oltky
@Ib^okfkdQebObfkpyKyBnrfmqebX>iif^k`bI^k`bZ^kajlrkqqebNrbi$AlofbPqbbaclrka^q%42+6)/-+1&+RpbqebQorpq^_fifqvlk^JbibbQ^odbq2qfjbp)rpfkdAbcbka`lkpq^kqivqlhbbm0i^vboprm+ObcobpevlrojlrkqqebkrpbqebPefbia?ob^hbo^_fifqvlk^O^kdbaQ^odbqobmb^qfsbivrkqfisrikbo^_ibqebkrpbqebPefbia?ob^hbo^_fifqvlk^@e^odbQ^odbqqebkrpbqeb@e^odb^_fifqvqtf`btefibfqppefbiafpaltkyyNFAy.03/2yyRy13-4-yyAy
@Qo^fkfkdFkQebCfbiayKyHfii^kvP`lrodb^olrka%4.+1)04+6&yyNFAy.034.yyWyF`b`oltkyyAy
@>?i^abCfqClo>@e^jmflkyLyyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrka%3-+2)2.+2&fkDofwwivEfiipyyRy11653yyNFAy.0333yyWyDofwwivEfiipyyAy

KQebBadbLcTfkqboyKyPhfmqefppqbmfcvlralk$qe^sbqebnrbpq$QebBadbLcTfkqbo$CfkaIloaBsbo_i^wb^olrka%22)42+/&fk@ovpq^iplkdClobpq^kaillqefpXBsbo_rokfkdBj_boZqebkqf`hqefpl_gb`qfsbyyIy12--2yyWy@ovpq^iplkdClobpqy
@QebBadbLcTfkqboyLyyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^q%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyNFAy.034-yyWyEltifkdCgloayyAy

K>TloqevTb^mlkyKyPhfmqefppqbmfcvlralk$qe^sbqebnrbpq$>TloqevTb^mlk$@liib`q1XTfkqboEv^`fkqeZ^olrka%4.)41+2&fkF`b`oltkqebkqf`hqefpl_gb`qfsbyyIy12---1yyWyF`b`oltky
@>TloqevTb^mlkyLyyKyQ^hbqebciltbop^karpbfqtfqeqebJ^fabkclrka^q%6/+5)/2+1&fkAo^dlk_ifdeqyyRy12---yyWyAo^dlk_ifdeqyyNFAy.0336y

Q>?i^abCfqClo>@e^jmflkyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.0333yyWyF`b`oltky
QQebBadbLcTfkqboyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.034-yyWyF`b`oltky
Q>TloqevTb^mlkyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.0336yyWyF`b`oltky
QQo^fkfkdFkQebCfbiayKy>s^obqePtfcqpqofhb%43+2).6+1&)A^fivyyNFAy.034.yyWyF`b`oltky
QIb^okfkdQebObfkpyKyP`lrqPe^ivkaof^%43+2).6+2&)A^fivyyNFAy.03/2yyWyF`b`oltky

KDrfab@ljmibqb

]]
end)
