DugisGuideViewer:RegisterGuide("Argent Tournament (Valiant Dailies)", nil, "Alliance", "D", function()
return [[
AAA

C>odbkqQlrok^jbkqDolrkapyKyCivql>odbkqQlrok^jbkqDolrkapfkF`b`oltk%4/+3)//+3&yyWyF`b`oltky

KMf`hrm1NrbpqpyKyMf`hrm1NrbpqpfkPfisbo@lsbk^kqM^sfiflk%43+0).6+2&yyWyF`b`oltky
>>?i^abCfqClo>@e^jmflkyKy@lilplp%43+0).6+2&)A^fivyyNFAy.042/yyLyyWyF`b`oltkyyAy
>>?i^abCfqClo>@e^jmflkyKyI^k^Pqlrqe^jjbo%43+0).6+2&)A^fivyyNFAy.041.yyLyyWyF`b`oltkyyAy
>>?i^abCfqClo>@e^jmflkyKy>j_olpb?liqpm^oh%43+0).6+2&)A^fivyyNFAy.0413yyLyyWyF`b`oltkyyAy
>>?i^abCfqClo>@e^jmflkyKyJ^ope^iG^`l_>ibofrp%43+0).6+2&)A^fivyyNFAy.03-0yyLyyWyF`b`oltkyyAy
>>?i^abCfqClo>@e^jmflkyKyG^bivkbBsbkplkd%43+0).6+2&)A^fivyyNFAy.0424yyLyyWyF`b`oltkyyAy
>QebBadbLcTfkqboyKy@lilplp%43+0).6+2&)A^fivyyNFAy.0421yyLyyWyF`b`oltkyyAy
>QebBadbLcTfkqboyKyI^k^Pqlrqe^jjbo%43+0).6+2&)A^fivyyNFAy.0410yyLyyWyF`b`oltkyyAy
>QebBadbLcTfkqboyKy>j_olpb?liqpm^oh%43+0).6+2&)A^fivyyNFAy.0415yyLyyWyF`b`oltkyyAy
>QebBadbLcTfkqboyKyJ^ope^iG^`l_>ibofrp%43+0).6+2&)A^fivyyNFAy.03.3yyLyyWyF`b`oltkyyAy
>QebBadbLcTfkqboyKyG^bivkbBsbkplkd%43+0).6+2&)A^fivyyNFAy.0426yyLyyWyF`b`oltkyyAy
>>TloqevTb^mlkyKy@lilplp%43+0).6+2&)A^fivyyNFAy.0420yyLyyWyF`b`oltkyyAy
>>TloqevTb^mlkyKyI^k^Pqlrqe^jjbo%43+0).6+2&)A^fivyyNFAy.041/yyLyyWyF`b`oltkyyAy
>>TloqevTb^mlkyKy>j_olpb?liqpm^oh%43+0).6+2&)A^fivyyNFAy.0414yyLyyWyF`b`oltkyyAy
>>TloqevTb^mlkyKyJ^ope^iG^`l_>ibofrp%43+0).6+2&)A^fivyyNFAy.03--yyLyyWyF`b`oltkyyAy
>>TloqevTb^mlkyKyG^bivkbBsbkplkd%43+0).6+2&)A^fivyyNFAy.0425yyLyyWyF`b`oltkyyAy

>>S^if^kq$pCfbiaQo^fkfkdyKyP^^kalp%43+0).6+2&)A^fivyyNFAy.0422yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyOliilProbpelq%43+0).6+2&)A^fivyyNFAy.0411yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyQf`hfkDb^opm^kkbo%43+0).6+2&)A^fivyyNFAy.0416yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyPfoJ^o`rp?^oiltb%43+0).6+2&)A^fivyyNFAy.026/yyLyyWyF`b`oltkyyAy
>>S^if^kq$pCfbiaQo^fkfkdyKyiibpqof^?i^abpfkdbo%43+0).6+2&)A^fivyyNFAy.043-yyLyyWyF`b`oltkyyAy

>QebDo^kaJbibbyKyO^kff%43+0).6+2&)A^fivyyNFAy.0423yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKy@i^o^Qrj_ib_obt%43+0).6+2&)A^fivyyNFAy.0412yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKyCif`hfkDb^opm^kkbo%43+0).6+2&)A^fivyyNFAy.042-yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKy@^mq^fkGlpbmeEliibv%43+0).6+2&)A^fivyyNFAy.0332yyLyyWyF`b`oltkyyAy
>QebDo^kaJbibbyKy>fo^bPq^opbbhbo%43+0).6+2&)A^fivyyNFAy.043.yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKyO^kff%43+0).6+2&)A^fivyyNFAy.0521yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKy@i^o^Qrj_ib_obt%43+0).6+2&)A^fivyyNFAy.052.yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKyCif`hfkDb^opm^kkbo%43+0).6+2&)A^fivyyNFAy.052/yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKy@^mq^fkGlpbmeEliibv%43+0).6+2&)A^fivyyNFAy.0514yyLyyWyF`b`oltkyyAy
>>qQebBkbjv$pD^qbpyKy>fo^bPq^opbbhbo%43+0).6+2&)A^fivyyNFAy.0522yyLyyWyF`b`oltkyyAy

KDbqlkJlrkqyKyBnrfmX>iif^k`bI^k`bZ^kadbq^Jlrkq%42+6)/-+1&lo%4.+52)/-&yyRy13-36yyWyF`b`oltky
@QebDo^kaJbibbyKyDlqlQeb>iif^k`b$pS^if^kqOfkd%42+0).5+0&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0423yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQeb>iif^k`b$pS^if^kqOfkd%42+0).5+0&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0412yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQeb>iif^k`b$pS^if^kqOfkd%42+0).5+0&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.042-yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQeb>iif^k`b$pS^if^kqOfkd%42+0).5+0&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.0332yyLyyWyF`b`oltkyyAy
@QebDo^kaJbibbyKyDlqlQeb>iif^k`b$pS^if^kqOfkd%42+0).5+0&qebk`e^iibkdb^kaabcb^q^s^if^kqyyNFAy.043.yyLyyWyF`b`oltkyyAy

@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolbp%10+4)2-+/&yyNFAy.0422yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolbp%10+4)2-+/&yyNFAy.0411yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolbp%10+4)2-+/&yyNFAy.0416yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolbp%10+4)2-+/&yyNFAy.026/yyLyyWyF`b`oltkyyAy
@>S^if^kq$pCfbiaQo^fkfkdyKyHfii.-@lksboqbaEbolbp%10+4)2-+/&yyNFAy.043-yLyyWyF`b`oltkyyAy

@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyLyyNFAy.0521yyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyLyyNFAy.052.yyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyLyyNFAy.052/yyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyLyyNFAy.0514yyWyF`b`oltkyyAy
@>qQebBkbjv$pD^qbpyKyCivqlqeb`^jm^q%16+.)4.+.&^kajlrkqvlroPq^_iba@^jm^fdk@e^odbo^karpbfqqlhfiiqebKM@obnrfobayyLyyNFAy.0522yyWyF`b`oltkyyAy

@>?i^abCfqClo>@e^jmflkyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrka%3-+2)2.+2&fkDofwwivEfiipyyNFAy.042/yyLyyWyDofwwivEfiipyyAy
@>?i^abCfqClo>@e^jmflkyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrka%3-+2)2.+2&fkDofwwivEfiipyyNFAy.041.yyLyyWyDofwwivEfiipyyAy
@>?i^abCfqClo>@e^jmflkyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrka%3-+2)2.+2&fkDofwwivEfiipyyNFAy.0413yyLyyWyDofwwivEfiipyyAy
@>?i^abCfqClo>@e^jmflkyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrka%3-+2)2.+2&fkDofwwivEfiipyyNFAy.03-0yyLyyWyDofwwivEfiipyyAy
@>?i^abCfqClo>@e^jmflkyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrka%3-+2)2.+2&fkDofwwivEfiipyyNFAy.0424yyLyyWyDofwwivEfiipyyAy

KQebBadbLcTfkqboyKyPhfmqefppqbmfcvlralk$qe^sbqebnrbpq$QebBadbLcTfkqbo$CfkaIloaBsbo_i^wb^olrka%22)42+/&fk@ovpq^iplkdClobpq^kaillqefpXBsbo_rokfkdBj_boZqebkqf`hqefpl_gb`qfsbyyIy12--2yyWy@ovpq^iplkdClobpqy
@QebBadbLcTfkqboyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^q%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyWyEltifkdCgloayyNFAy.0421yyLyyAy
@QebBadbLcTfkqboyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^q%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyWyEltifkdCgloayyNFAy.0410yyLyyAy
@QebBadbLcTfkqboyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^q%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyWyEltifkdCgloayyNFAy.0415yyLyyAy
@QebBadbLcTfkqboyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^q%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyWyEltifkdCgloayyNFAy.03.3yyLyyAy
@QebBadbLcTfkqboyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^q%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyWyEltifkdCgloayyNFAy.0426yyLyyAy

K>TloqevTb^mlkyKyPhfmqefppqbmfcvlralk$qe^sbqebnrbpq$>TloqevTb^mlk$@liib`q1XTfkqboEv^`fkqeZ^olrka%4.)41+2&fkF`b`oltkqebkqf`hqefpl_gb`qfsbyyIy12---1yyWyF`b`oltky
@>TloqevTb^mlkyKyQ^hbqebciltbop^karpbfqtfqeqebJ^fabkclrka^q%6/+5)/2+1&fkAo^dlk_ifdeqyyRy12---yyWyAo^dlk_ifdeqyyNFAy.0420yyLyyAy
@>TloqevTb^mlkyKyQ^hbqebciltbop^karpbfqtfqeqebJ^fabkclrka^q%6/+5)/2+1&fkAo^dlk_ifdeqyyRy12---yyWyAo^dlk_ifdeqyyNFAy.041/yyLyyAy
@>TloqevTb^mlkyKyQ^hbqebciltbop^karpbfqtfqeqebJ^fabkclrka^q%6/+5)/2+1&fkAo^dlk_ifdeqyyRy12---yyWyAo^dlk_ifdeqyyNFAy.0414yyLyyAy
@>TloqevTb^mlkyKyQ^hbqebciltbop^karpbfqtfqeqebJ^fabkclrka^q%6/+5)/2+1&fkAo^dlk_ifdeqyyRy12---yyWyAo^dlk_ifdeqyyNFAy.03--yyLyyAy
@>TloqevTb^mlkyKyQ^hbqebciltbop^karpbfqtfqeqebJ^fabkclrka^q%6/+5)/2+1&fkAo^dlk_ifdeqyyRy12---yyWyAo^dlk_ifdeqyyNFAy.0425yyLyyAy

Q>?i^abCfqClo>@e^jmflkyKy@lilplp%43+0).6+2&)A^fivyyNFAy.042/yyLyyWyF`b`oltkyyAy
Q>?i^abCfqClo>@e^jmflkyKyI^k^Pqlrqe^jjbo%43+0).6+2&)A^fivyyNFAy.041.yyLyyWyF`b`oltkyyAy
Q>?i^abCfqClo>@e^jmflkyKy>j_olpb?liqpm^oh%43+0).6+2&)A^fivyyNFAy.0413yyLyyWyF`b`oltkyyAy
Q>?i^abCfqClo>@e^jmflkyKyJ^ope^iG^`l_>ibofrp%43+0).6+2&)A^fivyyNFAy.03-0yyLyyWyF`b`oltkyyAy
Q>?i^abCfqClo>@e^jmflkyKyG^bivkbBsbkplkd%43+0).6+2&)A^fivyyNFAy.0424yyLyyWyF`b`oltkyyAy
QQebBadbLcTfkqboyKy@lilplp%43+0).6+2&)A^fivyyNFAy.0421yyLyyWyF`b`oltkyyAy
QQebBadbLcTfkqboyKyI^k^Pqlrqe^jjbo%43+0).6+2&)A^fivyyNFAy.0410yyLyyWyF`b`oltkyyAy
QQebBadbLcTfkqboyKy>j_olpb?liqpm^oh%43+0).6+2&)A^fivyyNFAy.0415yyLyyWyF`b`oltkyyAy
QQebBadbLcTfkqboyKyJ^ope^iG^`l_>ibofrp%43+0).6+2&)A^fivyyNFAy.03.3yyLyyWyF`b`oltkyyAy
QQebBadbLcTfkqboyKyG^bivkbBsbkplkd%43+0).6+2&)A^fivyyNFAy.0426yyLyyWyF`b`oltkyyAy
Q>TloqevTb^mlkyKy@lilplp%43+0).6+2&)A^fivyyNFAy.0420yyLyyWyF`b`oltkyyAy
Q>TloqevTb^mlkyKyI^k^Pqlrqe^jjbo%43+0).6+2&)A^fivyyNFAy.041/yyLyyWyF`b`oltkyyAy
Q>TloqevTb^mlkyKy>j_olpb?liqpm^oh%43+0).6+2&)A^fivyyNFAy.0414yyLyyWyF`b`oltkyyAy
Q>TloqevTb^mlkyKyJ^ope^iG^`l_>ibofrp%43+0).6+2&)A^fivyyNFAy.03--yyLyyWyF`b`oltkyyAy
Q>TloqevTb^mlkyKyG^bivkbBsbkplkd%43+0).6+2&)A^fivyyNFAy.0425yyLyyWyF`b`oltkyyAy

Q>S^if^kq$pCfbiaQo^fkfkdyKyP^^kalp%43+0).6+2&)A^fivyyNFAy.0422yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyOliilProbpelq%43+0).6+2&)A^fivyyNFAy.0411yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyQf`hfkDb^opm^kkbo%43+0).6+2&)A^fivyyNFAy.0416yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyPfoJ^o`rp?^oiltb%43+0).6+2&)A^fivyyNFAy.026/yyLyyWyF`b`oltkyyAy
Q>S^if^kq$pCfbiaQo^fkfkdyKyiibpqof^?i^abpfkdbo%43+0).6+2&)A^fivyyNFAy.043-yyLyyWyF`b`oltkyyAy

QQebDo^kaJbibbyKyO^kff%43+0).6+2&)A^fivyyNFAy.0423yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKy@i^o^Qrj_ib_obt%43+0).6+2&)A^fivyyNFAy.0412yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKyCif`hfkDb^opm^kkbo%43+0).6+2&)A^fivyyNFAy.042-yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKy@^mq^fkGlpbmeEliibv%43+0).6+2&)A^fivyyNFAy.0332yyLyyWyF`b`oltkyyAy
QQebDo^kaJbibbyKy>fo^bPq^opbbhbo%43+0).6+2&)A^fivyyNFAy.043.yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKyO^kff%43+0).6+2&)A^fivyyNFAy.0521yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKy@i^o^Qrj_ib_obt%43+0).6+2&)A^fivyyNFAy.052.yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKyCif`hfkDb^opm^kkbo%43+0).6+2&)A^fivyyNFAy.052/yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKy@^mq^fkGlpbmeEliibv%43+0).6+2&)A^fivyyNFAy.0514yyLyyWyF`b`oltkyyAy
Q>qQebBkbjv$pD^qbpyKy>fo^bPq^opbbhbo%43+0).6+2&)A^fivyyNFAy.0522yyLyyWyF`b`oltkyyAy
KDrfab@ljmibqb
]]
end)
