DugisGuideViewer:RegisterGuide("Borean Tundra (72-80 Dailies)", nil, "Alliance", "D", function()
return [[
AAA

C?lob^kQrkao^yKyCivql?lob^kQrkao^%31)12+5&y
>Mobm^ofkdcloqebTlopqyKyRq^fh%31)12+5&yyNFAy..612yyAy
@Mobm^ofkdcloqebTlopqyKy@liib`q5uXH^ph^i^PrmmifbpZ^olrka%40+1)2.+6&yyNFAy..612yyAy
QMobm^ofkdcloqebTlopqyKyRq^fh%31)12+5&yyNFAy..612yyAy

CQo^kpfqrpPefbiayKyCivqlQo^kpfqrpPefbia%00+0)01+2&fk?lob^kQrkao^y
>Ao^hbErkqyKyO^bilo^pw%00+0)01+2&yyNFAy..61-yyAy
@Ao^hbErkqyKyDlqlqebs^iibv^q%/4)0-&^kaillhclo^KburpAo^hbrm^_lsbqebkrpbXO^bilo^pw$pPmb^oZyyRy022-3yyNFAy..61-yyAy
QAo^hbErkqyKyO^bilo^pw%00+0)01+2&yyNFAy..61-yyAy

>>`bpEfdeyKy@lo^pqo^pw^%/6+2)/1+5&yyNFAy.01.1yyAy
@>`bpEfdeyKyHfiiqebCbiptlokBifqbrpfkdqebAo^hb_vrpfkdqefp^_fifqv`lj_l.).).).).)2)0KLQB7Tebkvlrmobpp0vlrkbbaqlpbic*`^pqloq^odbqvlropbicyyNFAy.01.1yyAy
Q>`bpEfdeyKy@lo^pqo^pw^%/6+2)/1+5&yyNFAy.01.1yyAy

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
