DugisGuideViewer:RegisterGuide("Borean Tundra (72-80 Pre-Quests)", nil, "Alliance", "D", function()
return [[
AAA

C?lob^kQrkao^yKyCivql?lob^kQrkao^%00+0)01+2&y

>?^pf`Qo^fkfkdyKyO^bilo^pw%00+0)01+2&yyNFAy..6.5y
@?^pf`Qo^fkfkdyNFAy..6.5yyKyHfiipmbiitb^sbopclrka^olrka%0/+0)/5+4&y
Q?^pf`Qo^fkfkdyKyO^bilo^pw%00+0)01+2&yyNFAy..6.5y
>E^q`efkd^Mi^kyKyO^bilo^pw%00+0)01+2&yyNFAy..603y
@E^q`efkd^Mi^kyNFAy..603yyKyHfii@lia^oo^Tvojhfkproolrkafkd@lia^oo^cloqebfoXColwbk>ubZ)qebkrpbqebjlkqebbddpkb^oqebKburp%/5+2)/5+6&yyRy02253y
QE^q`efkd^Mi^kyKyO^bilo^pw%00+0)01+2&yyNFAy..603y

CQo^kpfqrpPefbiayKyCivqlQo^kpfqrpPefbia%00+0)01+2&fk?lob^kQrkao^y
>Ao^hbErkqyKyO^bilo^pw%00+0)01+2&yyNFAy..61-y
@Ao^hbErkqyKyDlqlqebs^iibv^q%/4)0-&^kaillhclo^KburpAo^hbrm^_lsbqebkrpbXO^bilo^pw$pPmb^oZyyRy022-3yyNFAy..61-y
QAo^hbErkqyKyO^bilo^pw%00+0)01+2&yyNFAy..61-y

>>`bpEfdeyKy@lo^pqo^pw^%/6+2)/1+5&yyNFAy.01.1y
@>`bpEfdeyKyHfiiqebCbiptlokBifqbrpfkdqebAo^hb_vrpfkdqefp^_fifqv`lj_l.).).).).)2)0KLQB7Tebkvlrmobpp0vlrkbbaqlpbic*`^pqloq^odbqvlropbicyyNFAy.01.1y
Q>`bpEfdeyKy@lo^pqo^pw^%/6+2)/1+5&yyNFAy.01.1y

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
