DugisGuideViewer:RegisterGuide("Dragonblight (72-74+ Pre-Quests)", nil, "Alliance", "D", function()
return [[
AAA

CAo^dlk_ifdeqyKyCivqlAo^dlk_ifdeq%.6+2)25&y

>>Pqo^kdbAbsf`byKyQebfqbjXDlo^jlpe$pPqo^kdbAbsf`bZpq^oqpnrbpq*aolmmba_vDlo^jlpe^q%.6+2)25&yyNFAy./-22yyRy0341/y
Q>Pqo^kdbAbsf`byKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./-22y
>Molgb`qflkp^kaMi^kpyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./-3-y
@Molgb`qflkp^kaMi^kpyNFAy./-3-yyRy03414yyKyRpbqebXProdbKbbaibQbibmloqboZ)dbq`ilpbbklrdeqldbq`obafq+Rpbfq^d^fkqldbqaltky
QMolgb`qflkp^kaMi^kpyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./-3-y
>QebCl`rplkqeb?b^`eyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./-32y
@QebCl`rplkqeb?b^`eyNFAy./-32yyKyHfii@^mq^fkBjjvJ^ifk%/3+2)31+6&)rpbqebXIbvIfkbCl`rp@lkqoliOfkdZkb^oqebcl`rpyyRy0342.y
QQebCl`rplkqeb?b^`eyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./-32y
>>qlmqebTllai^kapyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./-50y
@>qlmqebTllai^kapyNFAy./-50yyKyHfiiIfbrqbk^kqQ^$wfkkf%0/+/)4/+5&cloqebXIbvIfkbCl`rp@lkqoli>jribqZ)rpbfqlkqebcl`rpkb^o_vyyRy03446y

Q>qlmqebTllai^kapyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./-50y
>Pb^o`eFkar$ibSfii^dbyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./-65y

QPb^o`eFkar$ibSfii^dbyKyJ^db*@ljj^kaboBsbkpq^o%1-+/)33+6&yyNFAy./-65y
>QebBkalcqebIfkbyKyJ^db*@ljj^kaboBsbkpq^o%1-+/)33+6&yyNFAy./.-4y
KCl`rpyNFAy./.-4yyNLyIbvIfkbCl`rpfkcloj^qflkobqofbsba7.,.yyKyRpbqeb`lkqoliibolkqebcl`rpyyRy035.2y
@QebBkalcqebIfkbyNFAy./.-4yyKyDll_pbosbqeb>wrobAo^dlkpeofkbkloqeb^pqlcqltk%20+-)32+1&y
QQebBkalcqebIfkbyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./.-4y
>D^fkfkd^k>rafbk`byKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./..6y

eTvojobpqQbjmibyKyAbjbpqo^pw%26+5)21+0&yyNFAy./433y

QD^fkfkd^k>rafbk`byKyQ^oflipqo^pw%24+6)21+/&yyNFAy./..6y
>Pmb^htfqevlro>j_^pp^aloyKyQ^oflipqo^pw%24+6)21+/&yyNFAy./433y
QPmb^htfqevlro>j_^pp^aloyKyI^rofbiQorb_i^ab%3-+-)22+.&yyNFAy./433y
>ObmloqqlqebOr_vAo^dlkpeofkbyKyI^rofbiQorb_i^ab%3-+-)22+.&yyNFAy./13-y

QObmloqqlqebOr_vAo^dlkpeofkbyKy@bofpqo^pw%2/+0)2-+.&yyNFAy./13-y
>Eb^qba?^qqibyKy@bofpqo^pw%2/+0)2-+.&yyNFAy./1.3y
@Eb^qba?^qqibyNFAy./1.3yyKyCfkaqebKM@pfkqebo^sfkb%2/+-)13+0&+Q^djl_pqebkibqqebKM@phfiifqclovlry
QEb^qba?^qqibyKy@bofpqo^pw%2/+0)2-+.&yyNFAy./1.3y
>ObqrokqlqebB^oqeyKy@bofpqo^pw%2/+0)2-+.&yyNFAy./1.4y
@ObqrokqlqebB^oqeyNFAy./1.4yyKyRpbqebXOr_v>`lokZlkqebab^aOr_vHbbmbopclrka^olrka%14+6)15+-&yyRy044/4y
QObqrokqlqebB^oqeyKy@bofpqo^pw%2/+0)2-+.&yyNFAy./1.4y
>QeolrdeCfbiaplcCi^jbyKy@bofpqo^pw%2/+0)2-+.&yyNFAy./1.5y
@QeolrdeCfbiaplcCi^jbyNFAy./1.5yyKyHfiikb`olj^k`bop^olrka%14+6)15+-&)qebkcfkaqeb_^kpebbrkaboqebpeofkb%14+6)16+6&y
QQeolrdeCfbiaplcCi^jbyKy@bofpqo^pw%2/+0)2-+.&yyNFAy./1.5y
>QebPqbt^oalcTvojobpqQbjmibyKy@bofpqo^pw%2/+0)2-+.&yyNFAy./435y
QQebPqbt^oalcTvojobpqQbjmibyKyQ^oflipqo^pw%24+6)21+/&yyNFAy./435y
>FkclojfkdqebNrbbkyKyQ^oflipqo^pw%24+6)21+/&yyNFAy././0y
QFkclojfkdqebNrbbkyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&)civqlqlmibsbiyyNFAy././0y
>ObmloqqlIloa>co^p^pqo^pwyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyNFAy./102y
QObmloqqlIloa>co^p^pqo^pwyKyIloa>co^p^pqo^pw%26+/)21+0&)civqljfaaibibsbiyyNFAy./102y
>AbcbkafkdTvojobpqQbjmibyKyIloa>co^p^pqo^pw%26+/)21+0&yyNFAy./04/y
@AbcbkafkdTvojobpqQbjmibyNFAy./04/yyKyElmlk^ao^dlk)hfii>wrobAo^dlkp^kaAo^hbp)qebkabpq^_fifwbqeb>wrobAo^dlkpeofkb%22+6)32+6&y
QAbcbkafkdTvojobpqQbjmibyKyIloa>co^p^pqo^pw%26+/)21+0&yyNFAy./04/y

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
