DugisGuideViewer:RegisterGuide("Dragonblight (72-74+ Dailies)", nil, "Alliance", "D", function()
return [[
AAA

CJl^$HfE^o_loyKyCivqlJl^$HfE^o_lofkAo^dlk_ifdeqy
>Mi^kkfkdcloqebCrqrobyKyQo^mmboJ^r$f%15+0)41+0&yyNFAy..63-yyAy
@Mi^kkfkdcloqebCrqrobyKyDlqlqeb`^jmpfqb^olrka%12+4)3.+3&^ka`liib`q./uXPkltc^iiDi^abMrmZyyNFAy..63-yyAy
QMi^kkfkdcloqebCrqrobyKyQo^mmboJ^r$f%15+0)41+0&yyNFAy..63-yyAy

>AbcbkafkdTvojobpqQbjmibyKyIloa>co^p^pqo^pw%26+/)21+0&yyNFAy./04/yyAy
@AbcbkafkdTvojobpqQbjmibyKyHfii0>wrobAo^dlkp)2>wrobAo^hbp^kaAbpq^_fifwbqeb>wrobAo^dlkpeofkb%22+2)33&)qebifqqibao^dlkplkivkbba.Cfob_^ii^ka.Fjjli^qbqlhfii)tefibqeb_fdao^dlkptfiikbba1*2Cfob_^ii^ka^kFjjli^qbqlafbyyNFAy./04/yyAy
QAbcbkafkdTvojobpqQbjmibyKyIloa>co^p^pqo^pw%26+/)21+0&yyNFAy./04/yyAy

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
