DugisGuideViewer:RegisterGuide("Eastern Kingdom Vendor Run", nil, "Alliance", "D", function()
return [[
AAA

OJbkbqefiE^o_loyKyQo^sbiqlJbkbqefiE^o_lo%.-+2)22+2&)Tbqi^kapyyWyTbqi^kapy

?Pqr^oqCibjfkd9CfpefkdPrmmifbp;yWyTbqi^kapyyKy%5+.)25+0&>nr^avk^jf`Cfpe>qqo^`qlo%/+2PM&)Ob`fmb7JfqeofiEb^aQolrq%//PM&)Ob`fmb7O^fk_ltCfk>i_^`lob%1PM&)Ob`fmb7Ol`hp`^ib@la%//PM&y
?AbtfkPefjjboa^tk9>i`ebjvPrmmifbp;yWyTbqi^kapyyKy%5+-)23+0&Eb^ifkdMlqflk%0PM&y
?Gbkk^_fkhMltbopb^j9Q^filofkdPrmmifbp#Pmb`f^iqvDllap;yWyTbqi^kapyyKy%5+.)22+6&M^qqbok7Dob^qbo>abmq$pOl_b%5PM&)M^qqbok7ObaTllibk?^d%2PM&)S^oflrp@ilqe>ojlo%0/+5*04+2PM&y
?P^jloCbpqfsrp9Pe^avAb^ibo;yWyTbqi^kapyyKy%.-+2)3-+0&Eb^ifkdMlqflk%0PM&y
?Kb^i>iibk9BkdfkbbofkdPrmmifbp#Dbkbo^iDllap;yWyTbqi^kapyyKy%.-+4)23+5&Abpfdk7Mbka^kqlcqeb>d^qbPefbia%.2PM&)?olkwbQr_b%5PM&)Dvol`eolk^qlj%0-PM&y
?Tbkk^Pfih_b^oa9Pmb`f^iDllapAb^ibo;yWyTbqi^kapyyKy%/2+4)/2+6&M^qqbok7>wrobPfihDilsbp%.-PM&)M^qqbok7DobbkIb^qebo>ojlo%/-PM&)M^qqbok7ObaTebimDilsbp%.3PM&)S^oflrpDobbk>ojlo%01+/PM*.+2DM&y
?Co^aaPtfcqdb^o9BkdfkbbofkdPrmmifbp;yWyTbqi^kapyyKy%/3+2)/2+4&P`ebj^qf`7Ilsfkdiv@o^cqba?lljpqf`h%.-PM&)P`ebj^qf`7JfkloOb`lj_l_ri^qlo%.2PM&)?olkwbQr_b%5PM&)Dvol`eolk^qlj%0-PM&y
?Hfuuib9Mlqflkp#Ebo_p;yWyTbqi^kapyyKy%2-+.)04+5&Eb^ifkdMlqflk%0PM&)S^oflrpEbo_p%5-@M*/PM&y

OJbkbqefiE^o_loyKyQo^sbiqlJbkqefiE^o_lo%.-+2)22+2&)Tbqi^kapyyWyTbqi^kapy
CPlrqepelobyKyPebiifb?olkafo%6+2)26+4&CivqlPlrqepelob)Efiip_o^aCllqefiipyyWyTbqi^kapy

?Ifkab^O^_lkkb9CfpefkdPrmmifbp;yWyEfiip_o^aCllqefiipyyKy%2-+3)3.+-&Ob`fmb7?ofpqibTefphbo@^qcfpe%./PM&)Ob`fmb7JfqeofiEb^aQolrq%//PM&)Ob`fmb7Ol`hp`^ib@la%//PM&)>nr^avk^jf`Cfpe>qqo^`qlo%/+2PM&y
?Jf`e^V^k`b9Qo^abDllap;yWyEfiip_o^aCllqefiipyyKy%16+-)22+.&Clojri^7Bk`e^kq?o^`bo*IbppboAbcib`qflk%0-PM&)M^qqbok7Qef`hJroil`>ojlo%3+2PM&)Abpfdk7?i^wfkd@fqofkbOfkd%/-PM&)Abpfdk7Eb^svFolkHkr`hibp%.2PM&)M^qqbok7F`v@il^h%.2PM&)Ob`fmb7P^dbcfpeAbifdeq%2-PM&)Ob`fmb7PjlhbaP^dbcfpe%2PM&y
?Ol_boq>b_fp`ebo9Prmboflo>ojlopjfqe;yWyEfiip_o^aCllqefiipyyKy%2.+0)24+-&S^oflrpdobbk^ojlo%0-+10PM*.+2DM&y
?Wfufi9Jbo`e^kqPrmobjb;yWyEfiip_o^aCllqefiipyyKy%21+0)04+/%ebt^ihpqebol^akloqe^kaplrqe&&M^qqbok7B^oqebkIb^qeboPelriabop%/-PM&)M^qqbok7ObaTllibk?^d%2PM&)P`ebj^qf`7Dl_ifkGrjmbo@^_ibp%/-PM&)S^oflrpdobbkp%.-PM*5-+/PM&y
?HofpIbd^`b9CobbtebbifkdQo^abptlj^k;yWyEfiip_o^aCllqefiipyyKy%5-+.)05+5&Lrqpfabqebhbbm)S^oflrpIbqeboDllap%02+/5PM*.+1DM&y
O>iqbo^`Jlrkq^fkpyWyEfiip_o^aCllqefiipyyKyQo^sbiql>iqbo^`Jlrkq^fkp%42+2)/1+.&y
?W^kPefspmolhbq9Pmb`f^ifqvBkdfkbbo;yWy>iqbo^`Jlrkq^fkpyyKyCliiltqebm^qeKloqe%43+/)5.+6&qeolrdeqebqrkkbi%45+5)5-+6&^kadlaltkqeb_^pbjbkq%53+-)5-+.&P`ebj^qf`7Dkljfpe@il^hfkdAbsf`b%/1PM&)Dvol`eolk^qlj%0-PM&y

OEfiip_o^aCllqefiipyKyQo^sbiqlEfiip_o^aCllqefiip%45).2+0&yyWyEfiip_o^aCllqefiipy

??ol$hfk9>i`ebjvPrmmifbp;yWy>iqbo^`Jlrkq^fkpyyKyQo^sbiqeolrdeD^iiltp$@lokbo%16+3)3.+/&%05+2)05+3&Ob`fmb7ColpqLfi%/2PM&)Dob^qboEb^ifkdMlqflk%2PM&)J^k^Mlqflk%1+5PM&y
?OfwwIllpb_liq9BkdfkbbofkdPrmmifbp;yWy>iqbo^`Jlrkq^fkpyyKy%14+2)02+/&P`ebj^qf`7F`bAbcib`qlo%.5PM&)Dvol`eolk^qlj%0-PM&y

O>iaobk@ilqebo@^jmyKyQo^sbiql@efiitfka@^jm)TbpqbokMi^drbi^kap%24+2)14+0&%45+0)12+2&%10)52+0&yyWy>iqbo^`Jlrkq^fkpy

?Iblk^oaMloqbo9Ib^qebotlohfkdPrmmifbp;yWyTbpqbokMi^drbi^kapyyKyMf`hrm`lilobapefoqp)qll%10+-)51+0&M^qqbok7PqlojpeolraM^kqp%.+3DM&)M^qqbok7Tf`hbaIb^qeboD^rkqibqp%.+/DM&^iplmf`hrm`lilobapefoqp)qlly

CIfdeq$pElmb@e^mbiyWyTbpqbokMi^drbi^kapyyKy?f_fic^w%1/+6)52+.&CivqlIfdeq$pElmb@e^mbi)B^pqbokMi^drbi^kapy

?G^pbC^oi^kb9Qo^abPrmmifbp;yWyB^pqbokMi^drbi^kapyyKy%41+5)2.+5&Abpfdk7Ofkdlc?fqqboPe^altp%.DM&y

C>bofbMb^hyWyB^pqbokMi^drbi^kapyyKyH^bivkPqbbitfkd%42+5)20+1&Civql>bofbMb^h)QebEfkqboi^kapy

?QorhTfia_b^oa9?^oqbkabo;yWyQebEfkqboi^kapyyKy%.1+2)1/+4&Ob`fmb7QbkaboTlicPqb^h%.+/DM&y
?E^odd^k9?i^`hpjfqefkdPrmmifbp;yWyQebEfkqboi^kapyyKy%.0+1)11+-&Mi^kp7JfqeofiP`^ib?o^`bop%3-PM&y
?Kflj^9Ib^qebotlohfkdPrmmifbp;yWyQebEfkqboi^kapyyKy%.0+1)10+0&M^qqbok7Kfdeqp`^mbPelriabop%1-PM&y

?OrmmlWfm`lfi9BkdfkbbofkdPrmmifbp;yWyQebEfkqboi^kapyyKyCliiltqebm^qe^q%01+6)1.+4&^kacfkaOrmml%01+0)04+5&P`ebj^qf`7JfqeofiJb`e^kf`^iAo^dlkifkd%1-PM&)?olkwbQr_b%5PM&)Dvol`eolk^qlj%0-PM&y
?DfddbqWfm`lfi9Qo^abPrmmifbp;yWyQebEfkqboi^kapyyKy%01+2)05+2&M^qqbok7Folkcb^qeboPelriabop%.+1DM&y

O>bofbMb^hyKyQo^sbiql>bofbMb^h%..+.)13+.&yyWyQebEfkqboi^kapy
CObcrdbMlfkqbyKyDrqeorjQerkabocfpq%..+.)13+.&CivqlObcrdbMlfkqb)>o^qefEfdei^kapyyWyQebEfkqboi^kapy

?>kaolaC^ao^k9Ib^qebotlohfkdPrmmifbp;yWy>o^qefEfdei^kapyyKy%12+.)13+5&M^qqbok7O^mqloEfab?biq%/2PM&y
?Aolsk^oPqolkd_obt9>i`ebjvPrmmifbp;yWy>o^qefEfdei^kapyyKy%13+1)14+-&Ob`fmb7ColpqMolqb`qflkMlqflk%/-PM&)Dob^qboEb^ifkdMlqflk%2PM&)J^k^Mlqflk%1+5PM&y
?E^jjlkH^otk9PrmbofloQo^abpj^k;yWy>o^qefEfdei^kapyyKy%13+2)14+0&Abpfdk7Or_v@oltklcObpqlo^qflk%3-PM&)M^qqbok7?^o_^of`Ibddfkdp%3+2PM&)Ob`fmb7Ol^pqO^mqlo%2-PM&y
?G^kklpFolktfii9PrmbofloJ^`b`o^cqbo;yWy>o^qefEfdei^kapyyKy%13+-)14+3&Mi^kp7PlifaFolkJ^ri%0-PM&y
?K^ogAbbmpif`b9?rq`ebo;yWy>o^qefEfdei^kapyyKy%12+3)14+3&Ob`fmb7?^o_b`rba?rww^oaTfkd%.-PM&y

CQebip^j^oyKy@baofhMolpb%12+5)13+.&CivqlQebip^j^o)Il`eJla^kyyWy>o^qefEfdei^kapy

?Ao^`Olrde`rq9Qo^abpj^k;yWyIl`eJla^kyyKy%02+3)16+-&Ob`fmb7Pjlhba?b^oJb^q%/+2PM&y
?O^kkCi^jbpmfkkbo9Q^filofkdPrmmifbp;yWyIl`eJla^kyyKy%03+-)13+-&M^qqbok7Dob^qbo>abmq$pOl_b%5PM&)M^qqbok7ObaTllibk?^d%2PM&y
?>iaobk@loalk9@ilqefbo;yWyIl`eJla^kyyKy%31+6)33+-&S^oflrpDobbk>ojlo%.0+61*/4+03PM&y
?U^ka^oDlla_b^oa9Dbkbo^iPrmmifbp;yWyIl`eJla^kyyKy%5/+2)30+2&Ob`fmb7ElivMolqb`qflkMlqflk%5PM&)Ob`fmb7O^dbMlqflk%.PM&y

CPqlojtfka@fqvyKyQelodrj%00+6)2.&CivqlPqlojtfka@fqvyyWyIl`eJla^ky

OBitvkkClobpqyKyQo^sbiqlBitvkkClobpq%0/+3)2-+5&yyWyBitvkkClobpqy

?Alkkf>kqe^kf^9@o^wv@^qI^av;yWyBitvkkClobpqyyKy%11+/)20+1&@^q@^oofbo%u1&%1-PMb^`e&y
?Qe^ovkk?lrabk9Qo^abPrmmifbp;yWyBitvkkClobpqyyKy%1.+6)34+.&M^qqbok7?irbIfkbkSbpq%/PM&)Ob`fmb7?ofiif^kqPj^iicfpe%1-@M&)Ob`fmb7Ilkdg^tJraPk^mmbo%1PM&y
?A^tk?ofdeqpq^o9>o`^kbDllap;yWyBitvkkClobpqyyKy%31+6)36+0&S^oflrpPq^qP`oliip%.*/PM&)IbppboEb^ifkdMlqflk%.PM&)JfkloJ^k^Mlqflk%1-@M&y
?Ao^hbIfkadobk9Dbkbo^i#Qo^abPrmmifbp;yWyBitvkkClobpqyyKy%50+/)33+3&M^qqbok7?irbIfkbkOl_b%0PM&y

OObaofadbJlrkq^fkpyKyQo^sbiqlObaofadbJlrkq^fkp%.-+/)4/&yyWyObaofadbJlrkq^fkpy

?>jvA^sbkmloq9Qo^abptlj^k;yWyObaofadbJlrkq^fkpyyKy%/6+.)14+2&M^qqbok7?i^`hTebimQrkf`%.1PM&)M^qqbok7ObaTllibk?^d%2PM&y
?Dilof^Cbjjbi9@llhfkdPrmmifbp;yWyObaofadbJlrkq^fkpyyKy%/3+6)11+-&Ob`fmb7P^dbcfpeAbifdeq%2-PM&)Ob`fmb7PjlhbaP^dbcfpe%2PM&y
?SboklkE^ib9CfpefkdPrmmifbp;yWyObaofadbJlrkq^fkpyyKy%/4+3)14+/&>nr^avk^jf`Cfpe>qqo^`qlo%/+2PM&y

OArphtllayKyQo^sbiqlArphtlla%6-).3&yyWyArphtllay

?Hwfuu9O^obDllap;yWyArphtllayyKy%5.+6).6+6&Ob`fmb7ElivMolqb`qflkMlqflk%5PM&)P`ebj^qf`7Dl_ifkGrjmbo@^_ibp%/-PM&)Eb^ifkdMlqflk%0PM&)IbppboJ^k^Mlqflk%.+/PM&y
?A^kfbiibWfmpqfq`e9Q^filofkdPrmmifbp;yWyArphtllayyKy%42+5)12+2&M^qqbok7?ofdeqVbiiltPefoq%5PM&y
?PebofWfmpqfq`e9Q^filofkdPrmmifbp;yWyArphtllayyKy%42+4)12+2&M^qqbok7A^ohPfihPefoq%..PM&)M^qqbok7Dob^qbo>abmq$pOl_b%5PM&y

OAb^atfkaM^ppyKyQo^sbiqlAb^atfkaM^pp%02+1)01+5&yyWyAb^atfkaM^ppy
OPt^jmlcPlooltpyKyQo^sbiPt^jmlcPlooltp%3+3)3-+2&yyWyPt^jmlcPlooltpy

?J^p^qQ$^kao9PrmbofloIb^qebotlohbo;yWyPt^jmlcPlooltpyyKy%/3+4)0.+5&M^qqbok7DobbkAo^dlkp`^ib?ob^pqmi^qb%.+/DM&)?ofiif^kqOba@il^h%.+45DM&)TbiiLfiba@il^h%/+/2DM&y

O?i^pqbaI^kapyKyQo^sbiql?i^pqbaI^kap%0/+6)4/+/&yyWy?i^pqbaI^kapy

??bokfbEbfpqbk9Clla#Aofkh;yWy?i^pqbaI^kapyyKy%30+2).3+6&Kbqebod^oab?fqqbo%/-PM&y
?Kfk^Ifdeq_obt9>i`ebjvPrmmifbp;yWy?i^pqbaI^kapyyKy%33+6).5+0&Ob`fmb7BifufolcAbjlkpi^vfkd%.DM&)Dob^qboJ^k^Mlqflk%./PM&)PrmbofloEb^ifkdMlqflk%.-PM&y

CPbkqfkbiEfiiyKy>ibu^kao^@lkpq^kqfkb%32+2)/1+0&CivqlPbkqfkbiEfii)Tbpqc^iiy

?Dfk^J^`Dobdlo9Qo^abPrmmifbp;yWyTbpqc^iiyyKy%24+3)21+-&M^qqbok7?irbLsbo^iip%1PM&)M^qqbok7Jroil`P`^ib?biq%2+2PM&)M^qqbok7Jroil`P`^ib?ob^pqmi^qb%3PM&)M^qqbok7ObaIfkbk?^d%/PM&y
?Abcf^pMolcfqbbo9CobbTebbifkdJbo`e^kq;yWyTbpqc^iiyyKy%10+2)33+6&Ob`fmb7O^dbMlqflk%.PM&)>dfib?llqp%/3+10PM&)Pq^_ib?llqp%/-PM&y

OArphtllayKyQo^sbiqlArphtlla%.-+3)30+0&yyWyArphtllay

??ifwqfh9>i`ebjvPrmmifbp;yWyArphtllayyKy%.5+-)21+2&Ob`fmb7Pe^altLfi%.2PM&)IbppboJ^k^Mlqflk%.+/PM&)Eb^ifkdMlqflk%0PM&y

OPqo^kdibqelokS^ibyKyQo^sbiqlPqo^kdibqelokS^ib%1-+5)1+1&yyWyPqo^kdibqelokS^iby

?@lomlo^i?irqe9@^jmQo^abo;yWyPqo^kdibqelokS^ibyyKy%05+-)0+.&Ob`fmb7GrkdibPqbt%0-PM&)Ob`fmb7Ol^pqO^mqlo%2-PM&y
?G^nrfifk^Ao^jbq9Prmboflo>ub`o^cqbo;yWyPqo^kdibqelokS^ibyyKy%02+4).-+4&Mi^kp7J^ppfsbFolk>ub%11PM&)Jfakfdeq>ub%1+0DM&y
?Dk^w?irkaboci^jb9BkdfkbbofkdPrmmifbp;yWyPqo^kdibqelokS^ibyyKy%2.+-)02+0&P`ebj^qf`7Jb`e^kf`^iAo^dlkifkd%.DM&)Dvol`eolk^qlj%0-PM&)?olkwbQr_b%5PM&y
?Hk^w?irkaboci^jb9BkdfkbbofkdPrmmifbp;yWyPqo^kdibqelokS^ibyyKy%2.+-)02+0&P`ebj^qf`7Ab^aivP`lmb%0-PM&)Dvol`eolk^qlj%0-PM&)?olkwbQr_b%5PM&y
?@lt^oaiv@olp_v9Q^filofkdPrmmifbp;yWyPqo^kdibqelokS^ibyyKy%/4+-)5/+2&M^qqbok7>ajfo^i$pE^q%4-PM&y

O?llqv?^vyKyQo^sbiql?llqv?^v)Pqo^kdibqelokS^ib%/6+1)4/+3&yyWyPqo^kdibqelokS^iby

?UfwhDllapqfq`e9Q^filofkdPrmmifbp;yWyPqo^kdibqelokS^ibyyKy%/5+4)43+5&M^qqbok7@ofjplkPfih@il^h%./PM&)M^qqbok7Bk`e^kqbo$p@lti%.-PM&y
??ifuobwDllapqfq`e9Ib^qebotlohfkdPrmmifbp;yWyPqo^kdibqelokS^ibyyKy%/5+/)44+2&M^qqbok7Jroil`P`^ib?o^`bop%/5PM&)M^qqbok7Qef`hJroil`>ojlo%3+2PM&y
?@o^whPm^ohp9CfobtlohpJbo`e^kq;yWyPqo^kdibqelokS^ibyyKy%/5+0)43+4&P`ebj^qf`7DobbkCfobtloh%.5PM&y
?Divu?obtofdeq9>i`ebjvPrmmifbp;yWyPqo^kdibqelokS^ibyyKy%/5+.)45+-&Ob`fmb7ColpqMolqb`qflkMlqflk%/-PM&)Ob`fmb7K^qrobMolqb`qflkMlqflk%/-PM&)Dob^qboEb^ifkdMlqflk%2PM&)J^k^Mlqflk%1+5PM&y
?HbipbvV^k`b9@llh;yWyPqo^kdibqelokS^ibyyKy%/5+/)41+2&@llhfkdOb`fmfbpu5%2PM*.+3DM&y
?J^whPkfmbpelq9BkdfkbbofkdPrmmifbp;yWyPqo^kdibqelokS^ibyyKy%/5+2)42+.&P`ebj^qf`7>``ro^qbP`lmb%/-PM&)Dvol`eolk^qlj%0-PM&)?olkwbQr_b%5PM&y
?K^ohh9Mfo^qbPrmmifbp;yWyPqo^kdibqelokS^ibyyKy%/5+/)41+2&M^qqbok7?i^`hPt^pe_r`hibo$pPefoq%.2PM&)M^oolq@^dbu/%1-PMb^`e&y
?LiaJ^kEbjfkd9CfpefkdPrmmifbp;yWyPqo^kdibqelokS^ibyyKy%/4+2)44+.&>nr^avk^jf`Cfpe>qqo^`qlo%/+2PM&y
?Ofhnfw9Ib^qebotlohfkdPrmmifbp;yWyPqo^kdibqelokS^ibyyKy%/5+2)43+-&M^qqbok7Dbj*pqraabaIb^qebo?biq%0-PM&)M^qqbok7Pe^altphfkDilsbp%02PM&y

KDrfab@ljmibqb
]]
end)


