DugisGuideViewer:RegisterGuide("Fishing (70+ Dailies)", nil, "Alliance", "D", function()
return [[
AAA

CA^i^o^k
KMf`hrmA^fivNrbpqyKyMf`hrm^nrbpqcoljJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvqebkqf`hqefpl_gb`qfsb>CQBOvlrmf`hrmqebnrbpqyyWyA^i^o^ky
>?illaFpQef`hboyLyyNFAy.0500yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWyA^i^o^k@fqvyyAy
>QebDelpqcfpeyLyyNFAy.050-yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWyA^i^o^k@fqvyyAy
>Afp^ojbayLyyNFAy.0503yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWyA^i^o^k@fqvyyAy
>GbtbiLcQebPbtbopyLyyNFAy.050/yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWyA^i^o^k@fqvyyAy
>A^kdbolrpivAbif`flrpyLyyNFAy.0501yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWyA^i^o^k@fqvyyAy

@?illaFpQef`hboyLyyKyHfii^_b^pqfk?lob^kQrkao^+Qefptfiidfsb^0jfkrqbab_rcc`^iiba>kfj^i?illa+Kltgrjmfkql^klmbk^ob^lct^qbo+>Mllilc?illatfii^mmb^o)tef`evlrcfpeifhb^kvlqebomlli+.*0?illaqllqeCobkwvtfii_b`^rdeqcoljb^`e`^pq+yyNFAy.0500yyAy
@QebDelpqcfpeyLyyKyPeli^w^o?^pfk%lmbkt^qbo&+Qebnrbpqpq^qbpOfsbo$pEb^oq)_rq^kvt^qbofkPeli^w^o?^pfkpbbjpql`ljmibqbqebnrbpq+yyNFAy.050-yyAy
@Afp^ojbayLyyKy@^q`e^?il^qbaBbifkqebt^qbofkcolkqlcqebsflibqelia%31)32+1&yyWyA^i^o^kyyNFAy.0503yyAy
@GbtbiLcQebPbtbopyLyyKyA^i^o^k$pRkabo_biiv%pbtbop&+yyNFAy.050/yyAy
@A^kdbolrpivAbif`flrpyLyyKyTfkqbodo^pm+>mmolufj^qbive^iclc^ii`^q`ebptfiie^sb^Qboolocfpe^qq^`eba+yyNFAy.0501yyAy

Q?illaFpQef`hboyLyyNFAy.0500yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWyA^i^o^k@fqvyyAy
QQebDelpqcfpeyLyyNFAy.050-yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWyA^i^o^k@fqvyyAy
QAfp^ojbayLyyNFAy.0503yyKyLifp^oo^%03+50)04+..&fkA^i^o^k`fqvyyWyA^i^o^k@fqvyyAy
QGbtbiLcQebPbtbopyLyyNFAy.050/yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWyA^i^o^k@fqvyyAy
QA^kdbolrpivAbif`flrpyLyyNFAy.0501yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWyA^i^o^k@fqvyyAy

CQbolhh^oClobpq
KMf`hrmA^fivNrbpqyKyMf`hrm^nrbpqcoljLiaJ^k?^oil%05+4)./+5&fkPe^qqo^qeqf`hqefpl_gb`qfsb>CQBOvlrmf`hrmqebnrbpqyyWyQbolhh^oClobpqy
>?^fq?^kafqpyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..333yyAy
>Cbi_illaCfiibqyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..336yyAy
>Peofjmfk$>fk$qB^pvyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..335yyAy
>QebLkbQe^qDlq>t^vyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..334yyAy
>@ol`lifphpfkqeb@fqvyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..332yyAy

@?^fq?^kafqpyLyyKyQbolhh^oClobpq)022cfpefkdphfiiyyNFAy..333yyAy
@Cbi_illaCfiibqyLyyKyEbiicfobMbkfkpri^)Pe^altjllkS^iibv)/42%<&^ka05-cfpefkdphfii)obpmb`qfsbivyyNFAy..336yyAy
@Peofjmfk$>fk$qB^pvyLyyKyW^kd^oj^ope)0--cfpefkdphfii&yyNFAy..335yyAy
@QebLkbQe^qDlq>t^vyLyyKyK^do^ka)05-cfpefkdphfiiyyNFAy..334yyAy
@@ol`lifphpfkqeb@fqvyLyyKyLodofjj^o,Pqlojtfka)kljfkfjrjphfiiobnrfobayyNFAy..332yyAy

Q?^fq?^kafqpyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..333yyAy
QCbi_illaCfiibqyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..336yyAy
QPeofjmfk$>fk$qB^pvyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..335yyAy
QQebLkbQe^qDlq>t^vyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..334yyAy
Q@ol`lifphpfkqeb@fqvyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..332yyAy

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`lj
]]
end)
