DugisGuideViewer:RegisterGuide("Grizzly Hills (74+ Dailies)", nil, "Alliance", "D", function()
return [[
AAA

C>j_bomfkbIladbyKyCivql>j_bomfkbIladbfkDofwwivEfiipy

>?i^`hofsboPhfojfpeyKyP`lrq@^mq^fk@^oqbo%0-)26+5&yyNFAy./111yyAy
@?i^`hofsboPhfojfpeyKyHfii.-EloabKM@ploMi^vbopfk?i^`hofsboIlddfkd@^jm%/5+2)3/+3&yyNFAy./111yyAy
Q?i^`hofsboPhfojfpeyKyP`lrq@^mq^fk@^oqbo%0-)26+5&yyNFAy./111yyAy

>Hf`h$BjTefibQebv$obAltkyKyPbodb^kqE^oqpj^k%06+1)10+5&yyNFAy.//56yyAy
>PeobaaboObm^foyKyPvkfmrp%06+2)10+3&yyNFAy.//11yyAy
>Mfb`bpM^oqpyKyMfmqet^`h%06+3)10+1&yyNFAy.//35yyAy
>IfcbloAb^qeyKyOeb^kk^%1-+2)1/+3&yyNFAy.//63yyAy

@IfcbloAb^qeyKyCfkaqebTlrkabaPliafbop%02)1-&^karpbqebXObkbtfkd?^ka^dbZlkqebjyyRy04243yyNFAy.//63yyAy
@Mfb`bpM^oqpyKy@liib`q^iiqebmfb`bp^olrka%02)1-&yyNFAy.//35yyAy
@PeobaaboObm^foyKyMf`hrm^Peobaabo%02)1-&^ka_ofkdfq_^`hqlPvkfmrp%06+2)10+3&yyNFAy.//11yyAy
@Hf`h$BjTefibQebv$obAltkyKyHfii.2EloabKM@ploMi^vbopfk?irbPhvIlddfkdDolrkap%02)1-&yyNFAy.//56yyAy

QPeobaaboObm^foyKyPvkfmrp%06+2)10+3&yyNFAy.//11yyAy
QMfb`bpM^oqpyKyMfmqet^`h%06+3)10+1&yyNFAy.//35yyAy
QIfcbloAb^qeyKyOeb^kk^%1-+2)1/+3&yyNFAy.//63yyAy
QHf`h$BjTefibQebv$obAltkyKyPbodb^kqE^oqpj^k%06+1)10+5&yyNFAy.//56yyAy

>HbbmQebj^q?^vyKyIfbrqbk^kqPqr^oq%//+.)5.+/&yyNFAy./0.3yyAy
>Pjlhb$BjLrqyKyPbodb^kqAltkbv%//)5-+5&yyNFAy./0/0yyAy
>AltkTfqe@^mq^fkWlok^yKy?^olkCobbj^k%//+/)5.+/&yyNFAy./0.1yyAy
>PbbhfkdPlisbkqyLyyKy?^o_ibcfkh%/0)5-+/&yyNFAy./110yyAy

@Pjlhb$BjLrqyKyDlql?rkhelrpb7%.2)43&P^tjfii7%.3)43&Pq^_ibp7%.5)5-&^ka^dol^iiqebSbkqrob@ljm^kvPqo^ddibop^karpbqebXPjlhb?lj_Zqebdolrm`e^pfkdvlryyRy043/.yyNFAy./0/0yyAy
@AltkTfqe@^mq^fkWlok^yKyHfii@^mq^fkWlok^%.0+2)5-+/&yyNFAy./0.1yyAy
@HbbmQebj^q?^vyKyHfii.-EloabRkfqp%@lknrbpqElia?bopbohbop&loEloabmi^vbopfkSbkqrob?^v^ob^%.0+5)45+1&yyNFAy./0.3yyAy
@PbbhfkdPlisbkqyLyyKyDbqqebXBibjbkq..2ZfkqebDl_ifk_l^q%.3+2)5-+0&yyNFAy./110yyAy

QPbbhfkdPlisbkqyLyyKy?^o_ibcfkh%/0)5-+/&yyNFAy./110yyAy
QHbbmQebj^q?^vyKyIfbrqbk^kqPqr^oq%//+.)5.+/&yyNFAy./0.3yyAy
QPjlhb$BjLrqyKyPbodb^kqAltkbv%//)5-+5&yyNFAy./0/0yyAy
QAltkTfqe@^mq^fkWlok^yKy?^olkCobbj^k%//+/)5.+/&yyNFAy./0.1yyAy

>OfafkdqebObaOl`hbqyKy@ljj^kaboEltpbo%.1+5)53+3&yyNFAy./104yyAy
KDbqBibjbkq..2yKyDbqqebXBibjbkq..2ZfkqebDl_ifk_l^q%.3+2)5-+0&yyIy04331y
KDlqlObaOl`hbq++yKyQf`hqefppqbm_bclobvlrgrjmlkqebObaOl`hbq%.0+4)55+5&y
@OfafkdqebObaOl`hbqyKyGrjmlk^ObaOl`hbq^karpbvlrohbvpqlpqbbo^kaj^hb^_fdRqrokqlt^oapqeb>iif^k`b?l^q^ka^fjlcqebU%6+3)46+/&ao^tklkqeb_l^qyyNFAy./104yyAy
QOfafkdqebObaOl`hbqyKy@ljj^kaboEltpbo%.1+5)53+3&yyNFAy./104yyAy

>Pb^obaP`lrodbyKyJ^`hCb^opbk%.3+4)15+0&yyNFAy./-05yyAy
@Pb^obaP`lrodbyKyDlqlqebQolii^ob^%.3)/4&grpqlrqlc^dolo^kdbqeoltqebXJ^`h$pA^ohDoldZql_rokqebQoliipyyRy026-5yyNFAy./-05yyAy
QPb^obaP`lrodbyKyJ^`hCb^opbk%.3+4)15+0&yyNFAy./-05yyAy

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
