DugisGuideViewer:RegisterGuide("Grizzly Hills (74+ Pre-Quests)", nil, "Alliance", "D", function()
return [[
AAA

CDofwwivEfiipyKyCivqlDofwwivEfiip%.3+/)14+4&yyNFAy..651y

>Cfiifkdqeb@^dbpyKyP^jfo%.3+/)14+4&yyNFAy..651y
@Cfiifkdqeb@^dbpyNFAy..651yyRy02403yyKyQ^ihql?raa%.3+1)15+.&)qebkeb^aqlqebOrfkplcAo^h$Wfk%.0+4)25+3&^karpbvlrombq_^oqlpbkaefj^cqbo^qolii)qebkrpbqebX?lrkqvErkqbo$p@^dbZlk`ba^wbay
QCfiifkdqeb@^dbpyKyP^jfo%.3+/)14+4&yyNFAy..651y
>Qor`b<yKyAo^hror%.3+2)14+5&yyNFAy..656y
@Qor`b<yNFAy..656yyKyIllqqebXArii@^osfkdHkfcbZkbuqqlqeb`^db)rpbfq)qebkq^ihqlAo^hror%.3+2)14+5&qlpe^hbefpe^kayyRy05-50y
QQor`b<yKyAo^hror%.3+2)14+5&yyNFAy..656y
>Sf^ilcSfpflkpyKyAo^hror%.3+2)14+5&yyNFAy..66-y
??rvXFj_rbaSf^iZyKy?rvXFj_rbaSf^iZcolj%.3+-)14+5&yyNFAy..66-yyIy.5/23y
@Sf^ilcSfpflkpyNFAy..66-yyKyT^qbotbbafpfkqebi^hb%.2+/)1-+3&+E^wbib^cfpclrka^olrka%.0+.)1.+0&^ka%.0+-)05+6&y
QSf^ilcSfpflkpyKyAo^hror%.3+2)14+5&yyNFAy..66-y
>P`lrodbh^_l_yKyMofdjlk%.2+5)13+5&yyNFAy./151y
@P`lrodbh^_l_yNFAy./151yyKyIllq^jrjjvqebkeb^aaltkqlqeb_lkcfob%.3+4)15+/&^ka_rokfqyyRy05.16y
QP`lrodbh^_l_yKyJ^`hCb^opbk%.3+4)15+0&yyNFAy./151y
>Pb^obaP`lrodbyKyJ^`hCb^opbk%.3+4)15+0&yyNFAy./-/6y
@Pb^obaP`lrodbyNFAy./-/6yyRy026-5yyKyDlqlAo^h$qe^olkHbbm%.4+5)/4+0&+Dlrmqebpq^fop^kagrjmlkqlqebbadbplcqebpq^fo`^pb+Il_XJ^`h$pA^ohDoldZ^qqebqoliip_bilty
QPb^obaP`lrodbyKyJ^`hCb^opbk%.3+4)15+0&yyNFAy./-/6y

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
