DugisGuideViewer:RegisterGuide("Howling Fjord (71+ Dailies)", nil, "Alliance", "D", function()
return [[
AAA

CH^j^dr^yKyCivqlH^j^dr^fkEltifkdCgloay

>QebT^vqlEfpEb^oq+++yKy>krkf^n%/1+3)25+5&yyNFAy..14/yyAy
K@liib`q^CfpeyKyRpbqebX>krkf^n$pKbqZlk^p`ellilccfpe^olrka%00)4.+5&yyRy1-613yyIy01./4y
@QebT^vqlEfpEb^oq+++yKyA^j^db^?rii%0.+6)41+.&pifdeqiv%_brk^ojbafcvlrjbibb^qq^`hefqpqlle^oa&^kaj^hbqebj`e^pbvlrqlqeb@lt)lk`bvlrob^`eqeb`ltrpbXQ^pqvObbcCfpeZlkqeb?riiyyRy01./4yyNFAy..14/yyAy
QQebT^vqlEfpEb^oq+++yKy>krkf^n%/1+3)25+5&yyNFAy..14/yyAy

>?ob^hqeb?il`h^abyKy?lj_^oafboMbqols%/6)1/&yyNFAy...20yyAy
@?ob^hqeb?il`h^abyKyT^fqcloqebWbmmbifk^q%/5+.)1.+/&^ka_l^oafqtebkfq^oofsbqebkrpbqebXMbqols$p@irpqbo?lj_pZqlhfiiqebmfo^qbptefiblk_l^oaqebWbmmbifk)fcvlre^sbcivfkdjlrkqvlr`^kgrpqcivlsboqlqebMfo^qb_l^qp^kahfiiqebjj^kr^iivyyNFAy...20yyAy
Q?ob^hqeb?il`h^abyKy?lj_^oafboMbqols%/6)1/&yyNFAy...20yyAy

>PqbbiD^qbM^qoliyKyPqbbiD^qb@efbc>o`e^blildfpq%0-+5)/5+3&yyNFAy..06.yyAy
@PqbbiD^qbM^qoliyKyRpbqebCivfkdj^`efkbqlhfii5uD^odlvibp^qqebafdpfqb^ob^%0.+.)/3+1&yyNFAy..06.yyAy
QPqbbiD^qbM^qoliyKyPqbbiD^qb@efbc>o`e^blildfpq%0-+5)/5+3&yyNFAy..06.yyAy

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
