DugisGuideViewer:RegisterGuide("Howling Fjord (71+ Pre-Quests)", nil, "Alliance", "D", function()
return [[
AAA

CH^j^dr^yKyCivqlH^j^dr^%1-+0)3-+0&fkEltifkdCgloay

>QebAb^aOfpbyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2-1y
@QebAb^aOfpbyNFAy..2-1yyKyC^oqlqebplrqeb^pq^qPefbiaEfii+Sfpfqb^`edo^sbclo^`irb7Cbkdfo%24+4)44+2&)Olafk%26+/)43+6&)Fprialc%26+5)46+1&)Tfka^k%3.+6)5-+-&y
QQebAb^aOfpbyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2-1y
>Biabo>qrfh^kaH^j^dr^yKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2-4y
QBiabo>qrfh^kaH^j^dr^yKyBiabo>qrfh%/2+-)24+-&yyNFAy..2-4y
>DobwwfuPmfkaibpk^myKyBiabo>qrfh%/2+-)24+-&yyNFAy..2-5y

QDobwwfuPmfkaibpk^myKyDobwwfuPmfkaibpk^m%/0+.)3/+4&yyNFAy..2-5y
>Pqobbq@obayKyDobwwfuPmfkaibpk^m%/0+.)3/+4&yyNFAy..2-6y
QPqobbq@obayKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2-6y

>Pt^__fk$Pl^myKyP`rqqibColpqmolt%04+4)46+2&yyNFAy..136y
@Pt^__fk$Pl^myNFAy..136yyKyHfii?fdOlv)plrqetbpqlcqeblqebopb^iflkp%0.+3)44+2&y
QPt^__fk$Pl^myKyP`rqqibColpqmolt%04+4)46+2&yyNFAy..136y

>PbbqlqebLmbo^qflkpyKyLsbopbboFobk^Pqlkbj^kqib%0-+/)/5+4&yyNFAy...43y
QPbbqlqebLmbo^qflkpyKyPqbbiD^qb@efbc>o`e^blildfpq%0-+5)/5+3&yyNFAy...43y
>F$sbDlq^CivfkdJ^`efkbyKyPqbbiD^qb@efbc>o`e^blildfpq%0-+5)/5+3&yyNFAy..06-y
@F$sbDlq^CivfkdJ^`efkbyNFAy..06-yyKyJ^hbprobvlrdbqfkqebofdeqmi^kb%qebob^obqtl+++lkbtfqetb^mlkp^kalkbtfqe^do^mmifkdellh&+Qebk_bclobvlrdllccfkqlqebjfkfkdmfqqrok^olrka^kaj^hbprobqebmi^kbcivp%pljbalklqciv&+Qebkcivfkqlqebmfq)dbq`ilpbqlqebi^odb_^d^karpbqebDo^mmifkdEllhqldbqqeb_^d+Vlr`^klkiv`^oov._^d^q^qfjby
QF$sbDlq^CivfkdJ^`efkbyKyPqbbiD^qb@efbc>o`e^blildfpq%0-+5)/5+3&yyNFAy..06-y

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
