DugisGuideViewer:RegisterGuide("Icecrown (80 Dailies)", nil, "Alliance", "D", function()
return [[
AAA

OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&y
>Ao^d^kaAolmyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.00/0yyAy
>Klq^?rdyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0011yyAy
>Qe^q$p>_ljfk^_ibyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0/56yyAy
>@^mqrobJlobAfpm^q`ebpyKyEfde@^mq^fkGrpqfk?^oqibqqlkQebPhv_ob^hboyyNFAy.0000yyAy
>Pi^sbpqlP^olkfqbyKy>_p^i^kqebMflrplkQebPhv_ob^hboyyNFAy.00--yyAy
>?illalcqeb@elpbkyKyHkfdeq*@^mq^fkAolp`ebOfleqlkQebPhv_ob^hboyyNFAy.0003yyAy
>QebPlirqflkPlirqflkyKy@efbcBkdfkbbo?liqtobk`elkQebPhv_ob^hboyyNFAy.0/6/yyAy
>ObqbpqKltyKy@efbcBkdfkbbo?liqtobk`elkQebPhv_ob^hboyyNFAy.00//yyAy

@Ao^d^kaAolmyKyDlPlrqelcqeb_ofadb^olrka%20)13&)hfiiqebjl_pqebobcloqebLo_lcFiirpflknrbpqfqbjvlrkbba)qebkqeoltfq^qqebA^ohPr_grd^qlopcolj^afpq^k`btefiblrqlc`lj_^q+yyRy11/13yyNFAy.00/0yyAy

>Pq^qf`Pel`hQollmp7qeb?lj_^oajbkqyKyHf_ifHfiileboqw%21)1/+6&yyNFAy.01-1yyAy
@Pq^qf`Pel`hQollmp7qeb?lj_^oajbkqyKyJlrkqqeb_lj_bo^kahfii?lj_^oajbkqFkc^kqov)?lj_^oajbkq@^mq^fkp^kaD^odlvib>j_rpebopyyNFAy.01-1yyAy
QPq^qf`Pel`hQollmp7qeb?lj_^oajbkqyKyHf_ifHfiileboqw%21)1/+6&yyNFAy.01-1yyAy
>MrqqfkdqebEboqw7QebS^iibvlcIlpqElmbyKyHf_ifHfiileboqw%21)1/+6&yyNFAy.005/yyAy
@MrqqfkdqebEboqw7QebS^iibvlcIlpqElmbyKyJlrkqqeb_lj_bo^kahfii?lj_^oajbkqFkc^kqov)D^odlvib>j_rpebop)Colpq_ollaPbkqofbp^kaP`lrodbT^oJ^`efkbpyyNFAy.005/yyAy
QMrqqfkdqebEboqw7QebS^iibvlcIlpqElmbyKyHf_ifHfiileboqw%21)1/+6&yyNFAy.005/yyAy

RAofkhRmyKyRpbXAfirqba@riqQlkf`ZcloqebnrbpqObqbpqKltyyRy110-4y
HHfii@riqKM@pyKyHfii@riqKM@p%16)00&^ka`liib`q.-uXQ^fkqbaBppbk`bZyyIy110-..-y
R@ob^qbXTofqefkdJ^ppZyKyOfdeq`if`hlkXQ^fkqbaBppbk`bZyyRy110-.y
@ObqbpqKltyKyRpbqebXQ^fkqbaBppbk`bZql`lj_fkbaqebjfkql^XTofqefkdJ^ppZ^karpbfqlk^`^riaolk^q%16)01&)A^oh@^riaolk7>qq^`hMltbo)?irb@^riaolk7Pmbiimltbo)Dobbk@^riaolk7Pq^jfk^yyRy110-1yyNFAy.00//yyAy
HBkpi^sbaJfkflkpyKyHfiiBkpi^sbaJfkflkp%22)/6&qebkrpbXOlalcPfmelkfkdZql`liib`q2uXA^ohJ^qqboZyyRy11100yyIy111012y
@Klq^?rdyKyLk`bvlre^sb`liib`qba2uXA^ohJ^qqboZofdeq`if`hlkqebMromibPrjjlkfkdPqlkb^q%20+4)00+3&yyNFAy.0011yyAy
@@^mqrobJlobAfpm^q`ebpyKyRpbXA^oqDrkZql`^mqrob3Lodofj$pE^jjboAfpm^q`e^olrka%15)21&yyRy11///yyNFAy.0000yyAy

@Qe^q$p>_ljfk^_ibyKyHfii^Erihfkd>_ljfk^qflk%35)30&^ka`liib`q^X@efiiba>_ljfk^qflkDrqpZqebkrpbqebX>_ljfk^qflkOb^kfj^qflkHfqZqlprjjlk^k>_ljfk^qflkrpbfqql_iltrmqebdelrip+Alk$qbumilabtefibqebdelrip^obpqrkkbalobipbvlrtlk$qdbq^kv`obafq+Vlr`^k^iplqovjlrkqfkdrm^cqboprjjlkfkdqeb>_ljfk^qflkyyNFAy.0/56yyRy10635yyAy
@QebPlirqflkPlirqflkyKyMf`hrmqeb0l_gb`qpp`^qqboba^olrkaqeb^ob^%36)33&XMfiblc?lkbpZ)X>_^kalkbaEbijZ)^kaX>_^kalkba>ojloZ)dbq0lcb^`elcqebj^kaqebkrpbqebX@lmmbo`i^t$pSli^qfibLfiZnrbpqfqbj0qfjbp+yyRy103-5yyNFAy.0/6/yyAy

>>pp^riq_vDolrkayKyPhv_ob^hboPnr^aIb^abo%3/+4)2.&yyNFAy.0/51yyAy
@>pp^riq_vDolrkayKyBp`loqqebPhv_ob^hboqollmpyyNFAy.0/51yyAy
@?illalcqeb@elpbkyKyHfii/-VjfoebfjSovhri^qVjfoebfj%26)21&yyNFAy.0003yyAy
Q>pp^riq_vDolrkayKyDolrka@ljj^kaboHlrm%3/+3)2.+0&yyNFAy.0/51yyAy

>>pp^riq_v>foyKyDolrka@ljj^kaboHlrm%3/+3)2.+0&yyNFAy.00-6yyAy
@>pp^riq_v>foyKyDlql%3/+2)2-+4&^kajlrkqqeb>fomi^kb)j^hbprobqebob^obfkcfiqo^qlopfkqebmi^kb_bclobvlrdlyyNFAy.00-6yyAy
Q>pp^riq_v>foyKyDolrka@ljj^kaboHlrm%3/+3)2.+0&yyNFAy.00-6yyAy

>HfkdlcqebJlrkq^fkyKyCo^wwibDb^odofkabo%24)3/+2&yyNFAy.0/5-yyAy
@HfkdlcqebJlrkq^fkyKyJlrkqQerkabo_lj_$pGrjm_lqkbuqqlvlr^kagrjmvlrot^vrmqlqebmfiblc_lkbp%21+51)3-+.1&yyNFAy.0/5-yyAy
QHfkdlcqebJlrkq^fkyKyCo^wwibDb^odofkabo%24)3/+2&yyNFAy.0/5-yyAy
@Pi^sbpqlP^olkfqbyKyDlqlqebP^olkfqbJfkbp%23)24&)pfjmivq^ihqlqebP^olkfqbJfkbPi^sbpfkqebjfkb)vlre^sb^`e^k`bqe^qqebvtfiiorklrqlcqebjfkb^kadfsbvlrnrbpq`obafq)loqrokelpqfiblkvlryyNFAy.00--yyAy

OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&y
QAo^d^kaAolmyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.00/0yyAy
QKlq^?rdyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0011yyAy
QQe^q$p>_ljfk^_ibyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0/56yyAy
Q@^mqrobJlobAfpm^q`ebpyKyEfde@^mq^fkGrpqfk?^oqibqqlkQebPhv_ob^hboyyNFAy.0000yyAy
QPi^sbpqlP^olkfqbyKy>_p^i^kqebMflrplkQebPhv_ob^hboyyNFAy.00--yyAy
Q?illalcqeb@elpbkyKyHkfdeq*@^mq^fkAolp`ebOfleqlkQebPhv_ob^hboyyNFAy.0003yyAy
QQebPlirqflkPlirqflkyKy@efbcBkdfkbbo?liqtobk`elkQebPhv_ob^hboyyNFAy.0/6/yyAy
QObqbpqKltyKy@efbcBkdfkbbo?liqtobk`elkQebPhv_ob^hboyyNFAy.00//yyAy

OQebPe^altS^riqyKyCivqlQebPe^altS^riq%10+.)/1+/&y
>SfibIfhbCfobyKySfib%10+2)/1+2&yyNFAy.0-4.yyAy
>Pellq$BjRmyKyQebIb^mbo%10+3)/2+.&yyNFAy.0-36yyAy
>Ib^sbLroJ^ohyKy?^olkPifsbo%1/+6)/2&yyNFAy./662yyAy
@Pellq$BjRmyKyDlql%0/)/1&^ka`ellpblkblcqebe^omllkp+Vlrkbbaqlt^fqrkqfiqebao^dlkpcivsbovkb^o)fcvlrkbbajlobqe^k{2pelqp^kaqebvalk$qafbqe^qjb^kpqe^qqebv^obk$qkb^obklrde+Alkqqovqlpellqqeblkbptef`e^obc^o^t^v)vlr`^k$qhfiiqebj+yyNFAy.0-36yyAy
@Ib^sbLroJ^ohyKyHfiiqebSvhrip%0-)/5&^karpbXB_lk?i^ab?^kkboZlkqeb`lompbpyyRy1/15-yyNFAy./662yyAy
@SfibIfhbCfobyKyDlql%/4)06&^kajlrkq^Ao^hb)^ka_rokqeb_rfiafkdpfkqeb^ob^yyNFAy.0-4.yyAy
QPellq$BjRmyKyQebIb^mbo%10+3)/2+.&yyNFAy.0-36yyAy
QSfibIfhbCfobyKySfib%10+2)/1+2&yyNFAy.0-4.yyAy
QIb^sbLroJ^ohyKy?^olkPifsbo%1/+6)/2&yyNFAy./662yyAy

OAb^qe$pOfpbyKyCivqlAb^qe$pOfpb%.6+6)14+3&y
>Fkqbiifdbk`bD^qebofkdyKy>rol`epDofj_^kb%.6+6)14+3&yyNFAy./505yyAy
>KlCivWlkbyKyRwlAb^qe`^iibo%.6+4)14+6&yyNFAy./5.2yyAy
>ColjQebfo@lompbp)OfpbyKyPbq^^iA^ohjbkabo%.6+4)15+0&yyNFAy./5.0yyAy
@KlCivWlkbyKyEb^alsboqlLkpi^rdeqE^o_loqlqebtbpqlcAb^qe$pOfpb^kacfka^p^cbpmlqqli^ka)qebkrpbX?lkbDovmelkZqlelmlk+Rpb?lkb>ojlotebkbsboqeb`llialtkfpcfkfpeba+TebkcfdeqfkdqebLkpi^rdeqDovmelkOfabop)pq^oqlcctfqeMi^drbPqofhb^kapm^jColpq?ob^qerkqfiqebofabofpab^a+Hfiiqbkofabopql`ljmibqbqebnrbpq+Fcvlro?lkbDovmelk$peb^iqefpilt)cfka^p^cbpmlqqlafpjlrkq^kaob*prjjlkfq+Vlr$iielmlk^kbt?lkbDovmelktfiicriieb^iqe+yyRy1-3--yyNFAy./5.2yyAy
@ColjQebfo@lompbp)OfpbyKyHfiiP`^oibqLkpi^rdeq%4)1.&^kaillqqeb`lompbpclohbvp^karpbXA^ohjbkabo$pQfk`qrobZlkqeb`lompbpyyRy1-254yyNFAy./5.0yyAy
@Fkqbiifdbk`bD^qebofkdyKyDlqlqeb_b^`e^q%5)10&tef`efp^qqeb_^`hlcqebe^o_lo^karkil`hqeb`ebpqpqebobyyNFAy./505yyAy
QFkqbiifdbk`bD^qebofkdyKy>rol`epDofj_^kb%.6+6)14+3&yyNFAy./505yyAy
QKlCivWlkbyKyRwlAb^qe`^iibo%.6+4)14+6&yyNFAy./5.2yyAy
QColjQebfo@lompbp)OfpbyKyPbq^^iA^ohjbkabo%.6+4)15+0&yyNFAy./5.0yyAy

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
