DugisGuideViewer:RegisterGuide("Jewelcrafting (65+ Dailies)", nil, "Alliance", "D", function()
return [[
AAA

CA^i^o^k
KMf`hrmA^fivNrbpqyKyMf`hrm^nrbpqcoljQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kqf`hqefpl_gb`qfsb>CQBOvlrmf`hrmqebnrbpqyyWyA^i^o^ky
>Pefmjbkq7?illaG^ab>jribqyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./625yyWyA^i^o^kyyAy
>Pefmjbkq7?ofdeq>ojloObif`yLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./63/yyWyA^i^o^kyyAy
>Pefmjbkq7DiltfkdFslovCfdrofkbyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./626yyWyA^i^o^kyyAy
>Pefmjbkq7Fkqof`^qb?lkbCfdrofkbyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./63.yyWyA^i^o^kyyAy
>Pefmjbkq7PefcqfkdPrk@roflyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./630yyWyA^i^o^kyyAy
>Pefmjbkq7Tf`hbaPrk?oll`eyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./63-yyWyA^i^o^kyyAy

@Pefmjbkq7?illaG^ab>jribqyLyyKyHfiiPfcobia^oOrkbhbbmbo^kaPfcobia^oJ^fabkp^kacfkaqebXSovhri>jribqZ^olrka%1-)40&fkPqlojMb^hprpbfqtfqeDobbkXA^ohG^abZ^kaObaX?illapqlkbZyyRy1.656yyNFAy./625yyWyQebPqlojMb^hpyyAy
@Pefmjbkq7?ofdeq>ojloObif`yLyyKyCivqlTvojobpqQbjmib^kahfiiF`b_lrkaObsbk^kqfkAo^dlk_ifdeq%35)2-&ql`liib`qXBibjbkq^i>ojloP`o^mZ^karpbfqtfqeLo^kdbXErdb@fqofkbZ^kaObaX?illapqlkbZyyRy1/.-4yyNFAy./63/yyWyAo^dlk_ifdeqyyAy
@Pefmjbkq7DiltfkdFslovCfdrofkbyLyyKyCivqlEltifkdCgloa^kahfiiPelsbiqrphClo^dbo%/3)//&ql`liib`qXPelsbiqrphFslovZ^karpbfqtfqe?irbX@e^i`balkvZ^kaMromibXPe^alt@ovpq^iZyyRy1/.-1yyNFAy./626yyWyEltifkdCgloayyAy
@Pefmjbkq7Fkqof`^qb?lkbCfdrofkbyLyyKyCivqlH0fkQebPqlojMb^hp^kahfiiPqlojmb^hE^q`eifkd%2/+2)40+2&cloXMolqlAo^dlk?lkbZrpbfqtfqeVbiiltXPrk@ovpq^iZ^kaDobbkXA^ohG^abZyyRy1/.-3yyNFAy./63.yyWyQebPqlojMb^hpyyAy
@Pefmjbkq7PefcqfkdPrk@roflyLyyKyCiv_biltA^i^o^k^kahfiiIlpqPe^ka^o^iPmfofq%.6+3)1-+2&)%04+/)22+5&cloXP`lrodb@roflZrpbfqtfqeVbiiltXPrk@ovpq^iZ^kaMromibXPe^alt@ovpq^iZyyRy1/.-5yyNFAy./630yyWy@ovpq^iplkdClobpqyyAy
@Pefmjbkq7Tf`hbaPrk?oll`eyLyyKyHfiiPqlojclodbaIlobpbbhbo%/3)35&fkpfabqeb`^sbfkQebPqlojMb^hpcloXFolkAt^oc?oll`eZrpbfqtfqeLo^kdbXErdb@fqofkbZ^kaVbiiltXPrk@ovpq^iZyyRy1/.-2yyNFAy./63-yyWyQebPqlojMb^hpyyAy

QPefmjbkq7?illaG^ab>jribqyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./625yyWyA^i^o^kyyAy
QPefmjbkq7?ofdeq>ojloObif`yLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./63/yyWyA^i^o^kyyAy
QPefmjbkq7DiltfkdFslovCfdrofkbyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./626yyWyA^i^o^kyyAy
QPefmjbkq7Fkqof`^qb?lkbCfdrofkbyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./63.yyWyA^i^o^kyyAy
QPefmjbkq7PefcqfkdPrk@roflyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./630yyWyA^i^o^kyyAy
QPefmjbkq7Tf`hbaPrk?oll`eyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./63-yyWyA^i^o^kyyAy

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`lj
]]
end)
