DugisGuideViewer:RegisterGuide("Kalimdor Vendor Run", nil, "Alliance", "D", function()
return [[
AAA

OO^q`ebqyKyQo^sbiqlO^q`ebq%3/+5)05+/&)Qeb?^oobkpyyWyQeb?^oobkpy

?Hfiuu9Cfpeboj^k;yWyQeb?^oobkpyyKy%3/+5)05+/&Ob`fmb7?ofpqibTefphbo@^qcfpe%./PM&)Ob`fmb7O^fk_ltCfk>i_^`lob%1PM&)>nr^avk^jf`Cfpe>qqo^`qlo%/+2PM&y
?D^dpmol`hbq9BkdfkbbofkdPrmmifbp;yWyQeb?^oobkpyyKy%3/+4)03+0&P`ebj^qf`7JfkloOb`lj_l_ri^qlo%.2PM&)P`ebj^qf`7DobbkCfobtloh%.5PM&)s^oflrpprmmifbp%.3@M*0-PM&y
?Do^wifu9>ojlobo#Pefbia`o^cqbo;yWyQeb?^oobkpyyKy%3/+/)05+1&S^oflrpdobbk^ojlo%0-+10*50+/.PM&y
?Ifww^ofh9Tb^mlkAb^ibo;yWyQeb?^oobkpyyKyQo^sbip_bqtbbk%2/+1)0-+4&ql%3.+5)05+0&S^oflrpDobbkTb^mlkp%/1*4-+1PM&)IbppboEb^ifkdMlqflk%.PM&)JfkloJ^k^Mlqflk%1-@M&y
?O^kfh9Qo^abPrmmifbp;yWyQeb?^oobkpyyKy%3.+6)05+4&Abpfdk7Tf`hbaJllkpqlkbOfkd%.2PM&)M^qqbok7?irbIfkbkOl_b%0PM&)M^qqbok7Dob^qbo>abmq$pOl_b%5PM&)Ob`fmb7O^dbMlqflk%.PM&y
?Wfwwbh9CfpefkdPrmmifbp;yWyQeb?^oobkpyyKy%3/+-)06+.&>nr^avk^jf`Cfpe>qqo^`qlo%/+2PM&y
?H^iia^kCbijllk9Pmb`f^ifpqIb^qebotlohfkdPrmmifbp;yWyQeb?^oobkpyyKy%12+6)02+4&M^qqbok7Absf^qbP`^ib@il^h%2+2PM&)M^qqbok7Absf^qbP`^ibDilsbp%.2PM&y

O>pebks^ibyKyQo^sbiql>pebks^ib%35)52&yyWy>pebks^iby
OPfisbotfkaObcrdbyKyQo^sbiqlPfisbotfkaObcrdb%2-+5)34+-&yyWy>pebks^iby

?E^ohi^kJllkdolsb9>i`ebjvPrmmifbp;yWy>pebks^ibyyKy%2-+5)34+-&Ob`fmb7Pe^altMolqb`qflkMlqflk%6PM&)Eb^ifkdMlqflk%0PM&)IbppboJ^k^Mlqflk%.+/PM&y
?Riqe^^k9?rq`ebo;yWy>pebks^ibyyKy%2-+-)33+4&Ob`fmb7?fd?b^oPqb^h%.3PM&)Ob`fmb7Ib^kSbkfplk%./PM&y
?A^iof^9Qo^abDllap;yWy>pebks^ibyyKy%02+.)2/+.&Clojri^7Bk`e^kq?o^`bo*IbppboPqobkdqe%/2PM&)Clojri^7Bk`e^kq@il^h*Jfklo>dfifqv%5PM&)Abpfdk7Tf`hbaJllkpqlkbOfkd%.2PM&y
?I^oa^k9Ib^qebotlohfkdPrmmifbp;yWy>pebks^ibyyKy%01+5)16+5&M^qqbok7?^o_^of`Ibddfkdp%3+2PM&y
?E^oiltkA^ohtb^sb9Ib^qebotlohfkdPrmmifbp;yWy>pebks^ibyyKy%.5+/)3-+-&M^qqbok7Ebo_^ifpq$pDilsbp%.5PM&y

CQ^iobkafpMlfkqyKyA^bivpef^%01+1)15&CivqlQ^iobkafpMlfkq)>wpe^o^yyWy>pebks^iby

??ifjlD^adbqpmofkd9Qo^abPrmmifbp;yWy>wpe^o^yyKy%12+0)6-+6&M^qqbok7@efjbof`Dilsbp%.+/DM&)M^qqbok7?irbAo^dlkp`^ib?ob^pqmi^qb%/DM&y
?Gr_fbD^adbqpmofkd9BkdfkbbofkdPrmmifbp;yWy>wpe^o^yyKy%12+0)6-+6&P`ebj^qf`7AbbmafsbEbijbq%03PM&)s^oflrpprmmifbp%.3@M*0-PM&y

CBsboillhyKyG^oolabkrp%..+6)44+3&CivqlqlBsboillh)TfkqbopmofkdyyWy>wpe^o^y

?BsfbTefoi_obt9>i`ebjvPrmmifbp;yWyTfkqbopmofkdyyKy%3-+5)04+5&PrmbofloEb^ifkdMlqflk%.-PM&)Dob^qboJ^k^Mlqflk%./PM&y
?Efjjfh9Clla#Aofkh;yWyTfkqbopmofkdyyKy%3.+0)06+.&Ob`fmb7JlkpqboLjbibq%.+/DM&y
?Nf^9Qo^abPrmmifbp;yWyTfkqbopmofkdyyKy%3.+/)04+/&Abpfdk7Kb`hi^`blcqebAf^jlkaQltbo%.+02DM&)Clojri^7Bk`e^kq@ebpq*J^gloEb^iqe%.+3DM&)M^qqbok7Colpqp^_bo?llqp%.+3DM&)M^qqbok7Jllk`ilqe%/DM&)M^qqbok7Orkb`ilqe?^d%.+/DM&y
?UfwwboCfww_liq9BkdfkbbofkdPrmmifbp;yWyTfkqbopmofkdyyKy%3-+5)05+3&P`ebj^qf`7Abif`^qb>o`^kfqb@lksboqbo%/DM&)P`ebj^qf`7CrpbaTfofkd%.+3DM&)P`ebj^qf`7DvolcobbwbF`bObcib`qlo%.+/DM&)P`ebj^qf`7J^pqbotlohQ^odbqArjjv%.+3DM&)P`ebj^qf`7MltbocriPb^clofrj@e^odb%.+3DM&)s^oflrpprmmifbp%.3@M*0-PM&y

CQ^ilk_o^k`eDi^abyKyJ^bqeov^%3/+0)03+3&CivqlqlQ^ilk_o^k`eDi^ab)CbitllayyWyTfkqbopmofkdy

?J^ivdbk9Dbkbo^iDllap;yWyCbitllayyKy%3/+0)/2+4&Ob`fmb7@e^ooba?b^oH^_l_p%.+5DM&)Ob`fmb7Grf`v?b^o?rodbo%.+5DM&)Ob`fmb7JlkpqboLjbibq%.+/DM&y

CJllkdi^abyKyJfpebiibk^%3/+2)/1+/&CivqlqlJllkdi^abyyWyCbitllay

?A^ok^ii9Q^filofkdPrmmifbp;yWyJllkdi^abyyKy%2.+4)00+5&M^qqbok7Orkb`ilqe@il^h%.+/DM&)M^qqbok7Orkb`ilqeOl_b%.+/DM&y
?Ilobi^bTfkqboplkd9Qo^abPrmmifbp;yWyJllkdi^abyyKy%15+2)1-+3&Clojri^7Bk`e^kq@il^h*PrmbofloAbcbkpb%/DM&)Clojri^7Orkba>o`^kfqbOla%/+/DM&)M^qqbok7Cbi`ilqeM^kqp%.+3DM&y

C>r_boafkbyKyPfkao^iv%15+.)34+1&Civqlql>r_boafkbyyWyA^ohpeloby

?Ebia^kD^ibplkd9Cfpeboj^k;yWyA^ohpelobyyKy%04+-)23+0&Ob`fmb7@i^j@eltabo%5PM&)Ob`fmb7JfqeofiEb^aQolrq%//PM&)Ob`fmb7O^fk_ltCfk>i_^`lob%1PM&)Ob`fmb7Ol`hp`^ib@la%//PM&y
?I^foa9CfpeSbkalo;yWyA^ohpelobyyKy%03+5)11+0&Ob`fmb7CfiibqlcCobkwv%1PM&y
?S^ia^olk9Q^filofkdPrmmifbp;yWyA^ohpelobyyKy%05+.)1-+3&M^qqbok7?irbIfkbkSbpq%/PM&)M^qqbok7ObaIfkbk?^d%/PM&)M^qqbok7ObaTllibk?^d%2PM&y
?J^so^ivk9Ib^qebo>ojlo#Ib^qebotlohfkdPrmmifbp;yWyA^ohpelobyyKy%04+-)1.+/&M^qqbok7Jroil`P`^ib?biq%2+2PM&)M^qqbok7Jroil`P`^ib?ob^pqmi^qb%3PM&y

_>wrobjvpqFpibyKyQ^hbqeb_l^qql>wrobjvpqFpib%0-+4)1.&yyWyA^ohpeloby

?@llhfbJ`Tb^hp^r`b9@llhfkdQo^fkbo#Prmmifbp;yWy>wrobjvpqFpibyyKy%13+4)4-+2&Ob`fmb7P^dbcfpeAbifdeq%2-PM&)Ob`fmb7PjlhbaP^dbcfpe%2PM&y
?Afhqvkk^9CfpefkdQo^fkbo#Prmmifbp;yWy>wrobjvpqFpibyyKy%3.+.)21+/&>nr^avk^jf`Cfpe>qqo^`qlo%/+2PM&y
?Lqlk^j_rpf9Dbkbo^iDllap;yWy>wrobjvpqFpibyyKy%15+.)2/+.&Eb^ifkdMlqflk%0PM&)Dob^qboJ^k^Mlqflk%./PM&y

C?illaT^q`eyKyPqbme^klp%35+2)30+4&Civql?illaT^q`e)?illajvpqFpibyyWyQebBula^oy

?C^wr9Qo^abpj^k;yWy?illajvpqFpibyyKy%20+2)23+2&Ob`fmb7@ork`evPmfaboPromofpb%1PM&y

CQebBula^oyKyI^^kal%24+4)20+6&Civql_^`hqlbula^oyyWy?illajvpqFpiby

_>r_boafkbyKyQ^hbqeb_l^qqlA^ohpelob%/.)21&yyWy>wrobjvpqFpiby

CPqlkbq^ilkMb^hyKy@^vi^fpJllkcb^qebo%03+0)12+3&CivqlqlPqlkbq^ilkMb^hyyWyA^ohpeloby

?Sbbkfu9Sbkqrob@l+Jbo`e^kq;yWyPqlkbq^ilkJlrkq^fkpyyKy%25+0)2.+4&P`ebj^qf`7Dl_ifkGrjmbo@^_ibp%/-PM&)S^oflrplcc*e^ka^ka/Etb^mlkp%5-PM*.+/0DM&y

OAbpli^`byKyQo^sbiqlAbpli^`b%20+0)2+/&yyWyAbpli^`by

?'QfjbaBsbkq'Prmbo*Pbiibo35-yWyAbpli^`byyKy%1-+2)46+0&^kajlsbpql%3-+0)05+.&kloqe^ilkdol^a+QfjbaBsbkqOb`fmb7?^o_b`rba?rww^oaTfkd%.-PM&)Ob`fmb7?fd?b^oPqb^h%.3PM&)Ob`fmb7Ao^dlk_ob^qe@efif%4-PM&)Ob`fmb7ElqTlicOf_p%2-PM&)Ob`fmb7Ib^kTlicPqb^h%.3PM&)Ob`fmb7JvpqbovPqbt%0-PM&)S^oflrpPq^qP`oliip%0*1PM&y
?'QfjbaBsbkq'Sbkalo*Qolk.---yWyAbpli^`byyKy%3-+0)05+.&^kajlsbpql%1-+2)46+0&plrqe^ilkdol^a+QfjbaBsbkqOb`fmb7@^ooflkPromofpb%2-PM&)Ob`fmb7Eb^svHlalPqbt%4-PM&)Ob`fmb7ElqIflk@elmp%.5PM&)Ob`fmb7GrkdibPqbt%0-PM&)Ob`fmb7Ib^kSbkfplk%./PM&)Ob`fmb7Ol^pqO^mqlo%2-PM&)J^k^Mlqflk%1+5PM&)Dob^qboEb^ifkdMlqflk%2PM&y

OKfgbi$pMlfkqyKyQo^sbiqlKfgbi$pMlfkq%31+4).-+2&yyWyAbpli^`by

CQe^i^k^^oyKy?^ofq^k^pPhvofsbo%31+4).-+2&CivqlqlQe^i^k^^o)Cbo^i^pyyWyAbpli^`by

??ofbkk^Pq^odilt9Q^filofkdPrmmifbp;yWyCbo^i^pyyKy%56+-)12+6&M^qqbok7>wrobPfih@il^h%.2PM&y

CCb^qebojllkyKyQevppf^k^%56+2)12+6&CivqlqlCb^qebojllk)Cbo^i^pyyWyCbo^i^py

?Ild^kk^p9>i`ebjvPrmmifbp;yWyCbo^i^pyyKy%0/+3)11+-&Ob`fmb7DelpqAvb%6-PM&)Ob`fmb7K^qrobMolqb`qflkMlqflk%/-PM&)Dob^qboJ^k^Mlqflk%./PM&)PrmbofloEb^ifkdMlqflk%.-PM&y
?Mo^qqJ`Dor__bk9Ib^qebotlohfkdPrmmifbp;yWyCbo^i^pyyKy%0-+3)1/+4&M^qqbok7DobbkTebim?o^`bop%/5PM&)M^qqbok7IfsfkdPelriabop%.+1DM&)M^qqbok7QroqibP`^ibDilsbp%02PM&y
?P^s^kkb9CfpefkdPrmmifbp;yWyCbo^i^pyyKy%0.+-)13+.&>nr^avk^jf`Cfpe>qqo^`qlo%/+2PM&y
?Sfsf^kk^9Qo^abPrmmifbp;yWyCbo^i^pyyKy%0.+0)10+2&Ob`fmb7?^hbaP^ijlk%/DM&)Ob`fmb7ElqTlicOf_p%2-PM&)Ob`fmb7Il_pqboPqbt%/DM&)Ob`fmb7JfdeqcfpePqb^h%/DM&y

C@bk^oflkEliayKyCviaobk%0-+/)10+0&Civqlql@bk^oflkElia+PfifqerpyyWyCbo^i^py

?H^kf^9Bk`e^kqfkdPrmmifbp;yWyPfifqerpyyKy%2/+-)06+3&Clojri^7Clojri^7IbppboJ^k^Lfi%.DM&)Clojri^7IbppboTfw^oaLfi%1-PM&)Clojri^7JfkloJ^k^Lfi%0-PM&)Clojri^7JfkloTfw^oaLfi%2PM&)Clojri^7Tfw^oaLfi%/DM&)M^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`e%3-PM&)M^qqbok7Bk`e^kqbaOrkb`ilqe?^d%/DM&)IbppboJ^df`Bppbk`b%5PM&)Pqo^kdbArpq%5PM&y
?Jfpeq^9Qo^abPrmmifbp;yWyPfifqerpyyKy%16+6)03+2&Abpfdk7Bjbo^ia@oltklcAbpqor`qflk%.DM&y
?W^kklhEfabmfbo`bo9Ib^qebotlohfkdPrmmifbp;yWyPfifqerpyyKy%5.+6).4+5&M^qqbok7Eb^svP`lomfa?o^`bop%.+/DM&)M^qqbok7Eb^svP`lomfaEbij%/+2DM&y

ORk$Dlol@o^qboyKyQo^sbiqlRk$Dlol@o^qbo%/3)..&yyWyRk$Dlol@o^qboy

?Kbod^i9Dbkbo^iDllap;yWyRk$Dlol@o^qboyyKy%10+0)4+5&M^qqbok7Absfip^roD^rkqibqp%/+/DM&y

CD^adbqw^kyKyDovcb%12+/)2+5&CivqlqlD^adbqw^k)Q^k^ofpyyWyRk$Dlol@o^qboy

?FkkhbbmboCfwwdofj_ib9Fkkhbbmbo;yWyQ^k^ofpyyKy%2/+2)/4+6&Ob`fmb7QbkaboTlicPqb^h%.+/DM&y
?AfodbNrfh`ib^sb9?rq`ebo;yWyQ^k^ofpyyKy%2/+3)/5+.&Ob`fmb7QbkaboTlicPqb^h%.+/DM&y
?HofkhibDllapqbbi9?i^`hpjfqefkdPrmmifbp;yWyQ^k^ofpyyKy%2.+2)/5+5&Mi^kp7DliabkP`^ib@lfc%11PM&y
?Sfwwhif`h9Q^filofkdPrmmifbp;yWyQ^k^ofpyyKy%2.+.)/4+2&M^qqbok7@ofjplkPfihOl_b%2-PM&)M^qqbok7PlriMlr`e%.+/DM&y
?>i`ebjfpqMbpqibwrdd9>i`ebjvPrmmifbp;yWyQ^k^ofpyyKy%2-+6)/4+-&Ob`fmb7K^qrobMolqb`qflkMlqflk%/-PM&)Ob`fmb7Mefilplmebo$pPqlkb%5-PM&)Ob`fmb7Qo^kpjrqb>o`^kfqb%2DM&)Ob`fmb7Qo^kpjrqbFolkqlDlia%5-PM&)Ob`fmb7Qo^kpjrqbJfqeofiqlQorbpfisbo%5-PM&y
??ifwofh?r`hpelq9Drkpjfqe;yWyQ^k^ofpyyKy%2-+5)/4+3&P`ebj^qf`7BW*QeolAvk^jfqbFF%2-PM&y

OQelrp^kaKbbaibpyKyQo^sbiqlQelrp^kaKbbaibp%41+/)60+1&yyWyQelrp^kaKbbaibpy

?GfkhvQtfwwibcfuufq9BkdfkbbofkdPrmmifbp;yWyQelrp^kaKbbaibpyyKy%44+4)44+5&P`ebj^qf`7DkljfpeRkfsbop^iObjlqb%./PM&)P`ebj^qf`7Ilsfkdiv@o^cqba?lljpqf`h%.-PM&)s^oflrpprmmifbp%.3@M*0-PM&y

OQ^k^ofpyKyQo^sbiqlQ^k^ofp%2-+4)/1+/&yyWyQ^k^ofpy

?Dfhhfu9Cfpeboj^k;yWyQ^k^ofpyyKy%33+3)//+.&Ob`fmb7DofiibaPnrfa%.+3DM&)Ob`fmb7KfdeqcfkPlrm%/DM&)Ob`fmb7Ml^`ebaPrkp`^ibP^ijlk%/DM&)Ob`fmb7PmlqqbaVbiiltq^fi%.+3DM&y
?E^rdeqvJlafpqb9C^peflkAbpfdkbo;yWyQ^k^ofpyyKy%33+2)//+0&M^qqbok7AobppPelbp%2-PM&)M^qqbok7E^ifp`^kG^`hbq%2-PM&)M^qqbok7E^ifp`^kM^kq^illkp%12PM&y
?G^__bv9Dbkbo^iDllap;yWyQ^k^ofpyyKy%34+-)//+-&Ob`fmb7Rkabojfkb@i^j@eltabo%0-PM&y

CQebo^jlobFpibyKy%2.)/6+0&CivqlqlQebo^jlobFpib)Arpqt^iiltJ^opeyyWyQ^k^ofpy

?MfqboSbo^k`b9Tb^mlkpjfqe#>ojlobo;yWyArpqt^iiltJ^opeyyKy%34+2)15+.&S^oflrpDobbktb^mlkp^ka>ojlo%45+26PM*/+1DM&y
?Ebibkf^Liabk9Qo^abPrmmifbp;yWyArpqt^iiltJ^opeyyKy%33+1)2.+2&M^qqbok7Jroil`P`^ib?o^`bop%/5PM&)Abpfdk7?i^`hMb^oiM^kqebo%2-PM&)Abpfdk7Qorbpfisbo@o^_%3-PM&)Ob`fmb7Ao^dlk_ob^qe@efif%4-PM&)Ob`fmb7JvpqbovPqbt%0-PM&)Ob`fmb7Ol^pqO^mqlo%2-PM&y
?Rj^?^oqrij9Ebo_^ifpj#>i`ebjvPrmmifbp;yWyArpqt^iiltJ^opeyyKy%31+-)14+4&Ebo_Mlr`e%.-PM&)Dob^qboEb^ifkdMlqflk%2PM&)J^k^Mlqflk%1+5PM&y

KDrfab@ljmibqb
]]
end)
