DugisGuideViewer:RegisterGuide("Knights of the Ebon Blade (1500 +Rep)", nil, "Alliance", "D", function()
return [[
AAA

OQebPe^altS^riqyKyCivqlQebPe^altS^riq%10+.)/1+/&yyWyF`b`oltky
>SfibIfhbCfobyKySfib%10+2)/1+2&yyNFAy.0-4.yyWyF`b`oltkyyAy
>Pellq$BjRmyKyQebIb^mbo%10+3)/2+.&yyNFAy.0-36yyWyF`b`oltkyyAy
>Ib^sbLroJ^ohyKy?^olkPifsbo%1/+6)/2&yyNFAy./662yyWyF`b`oltkyyAy
@Pellq$BjRmyKyDlql%0/)/1&^ka`ellpblkblcqebe^omllkp+Vlrkbbaqlt^fqrkqfiqebao^dlkpcivsbovkb^o)fcvlrkbbajlobqe^k{2pelqp^kaqebvalk$qafbqe^qjb^kpqe^qqebv^obk$qkb^obklrde+Alkqqovqlpellqqeblkbptef`e^obc^o^t^v)vlr`^k$qhfiiqebj+yyNFAy.0-36yyWyF`b`oltkyyAy
@Ib^sbLroJ^ohyKyHfiiqebSvhrip%0-)/5&^karpbXB_lk?i^ab?^kkboZlkqeb`lompbpyyRy1/15-yyNFAy./662yyWyF`b`oltkyyAy
@SfibIfhbCfobyKyDlql%/4)06&^kajlrkq^Ao^hb)^ka_rokqeb_rfiafkdpfkqeb^ob^yyNFAy.0-4.yyWyF`b`oltkyyAy
QPellq$BjRmyKyQebIb^mbo%10+3)/2+.&yyNFAy.0-36yyWyF`b`oltkyyAy
QSfibIfhbCfobyKySfib%10+2)/1+2&yyNFAy.0-4.yyWyF`b`oltkyyAy
QIb^sbLroJ^ohyKy?^olkPifsbo%1/+6)/2&yyNFAy./662yyWyF`b`oltkyyAy

OAb^qe$pOfpbyKyCivqlAb^qe$pOfpb%.6+6)14+3&yyWyF`b`oltky
>Fkqbiifdbk`bD^qebofkdyKy>rol`epDofj_^kb%.6+6)14+3&yyNFAy./505yyWyF`b`oltkyyAy
>KlCivWlkbyKyRwlAb^qe`^iibo%.6+4)14+6&yyNFAy./5.2yyWyF`b`oltkyyAy
>ColjQebfo@lompbp)OfpbyKyPbq^^iA^ohjbkabo%.6+4)15+0&yyNFAy./5.0yyWyF`b`oltkyyAy
@KlCivWlkbyKyEb^alsboqlLkpi^rdeqE^o_loqlqebtbpqlcAb^qe$pOfpb^kacfka^p^cbpmlqqli^ka)qebkrpbX?lkbDovmelkZqlelmlk+Rpb?lkb>ojlotebkbsboqeb`llialtkfpcfkfpeba+TebkcfdeqfkdqebLkpi^rdeqDovmelkOfabop)pq^oqlcctfqeMi^drbPqofhb^kapm^jColpq?ob^qerkqfiqebofabofpab^a+Hfiiqbkofabopql`ljmibqbqebnrbpq+Fcvlro?lkbDovmelk$peb^iqefpilt)cfka^p^cbpmlqqlafpjlrkq^kaob*prjjlkfq+Vlr$iielmlk^kbt?lkbDovmelktfiicriieb^iqe+yyRy1-3--yyNFAy./5.2yyWyF`b`oltkyyAy
@ColjQebfo@lompbp)OfpbyKyHfiiP`^oibqLkpi^rdeq%4)1.&^kaillqqeb`lompbpclohbvp^karpbXA^ohjbkabo$pQfk`qrobZlkqeb`lompbpyyRy1-254yyNFAy./5.0yyWyF`b`oltkyyAy
@Fkqbiifdbk`bD^qebofkdyKyDlqlqeb_b^`e^q%5)10&tef`efp^qqeb_^`hlcqebe^o_lo^karkil`hqeb`ebpqpqebobyyNFAy./505yyWyF`b`oltkyyAy
QFkqbiifdbk`bD^qebofkdyKy>rol`epDofj_^kb%.6+6)14+3&yyNFAy./505yyWyF`b`oltkyyAy
QKlCivWlkbyKyRwlAb^qe`^iibo%.6+4)14+6&yyNFAy./5.2yyWyF`b`oltkyyAy
QColjQebfo@lompbp)OfpbyKyPbq^^iA^ohjbkabo%.6+4)15+0&yyNFAy./5.0yyWyF`b`oltkyyAy

KDrfab@ljmibqb
]]
end)
