DugisGuideViewer:RegisterGuide("Outland Vendor Run", nil, "Alliance", "D", function()
return [[
AAA

OPe^qqo^qe@fqvyKyQo^sbiqlPe^qqo^qe@fqv%31+-)4.+5&yyWyPe^qqo^qe@fqvy

?>^olkEliij^k9?i^`hpjfqefkdPrmmifbp;yKy%31+-)4.+5&Mi^kp7>a^j^kqfqb@ib^sbo%1DM&)Mi^kp7>a^j^kqfqbA^ddbo%1DM&)Mi^kp7>a^j^kqfqbJ^ri%1DM&)Mi^kp7>a^j^kqfqbO^mfbo%1DM&)Mi^kp7>a^j^kqfqbOla%1DM&yyWyPe^qqo^qe@fqvy
?>kaoflkA^ohpmfkkbo9Pe^altb^sbPmb`f^ifpq;yKy%33+3)35+2&M^qqbok7Pe^alt`ilqe%1DM&yyWyPe^qqo^qe@fqvy
?Bffk9Pmb`f^iqvQ^filofkdPrmmifbp;yKy%33+-)36+-&M^qqbok7?liqlcFj_rbaKbqebotb^sb%1DM&)M^qqbok7Fj_rbaKbqebotb^sb?^d%1DM&)M^qqbok7Kbqebotb^sbOl_b%1DM&)M^qqbok7Kbqebotb^sbQrkf`%1DM&yyWyPe^qqo^qe@fqvy
?DfadbPmbiitb^sbo9PmbiicfobPmb`f^ifpq;yKy%33+1)35+-&M^qqbok7Pmbii`ilqe%1DM&yyWyPe^qqo^qe@fqvy
?GfjP^iqfq9@llhfkdPrmmifbp;yKy%30+2)35+3&Ob`fmb7P^dbcfpeAbifdeq%2-PM&)Ob`fmb7PjlhbaP^dbcfpe%2PM&yyWyPe^qqo^qe@fqvy
?J^a^jbOr_v9Bk`e^kqfkdPrmmifbp;yKy%30+2)4-+3&Clojri^7Bk`e^kqPefbia*J^gloPq^jfk^%1DM&)Clojri^7I^odbMofpj^qf`Pe^oa%3DM&)Clojri^7IbppboTfw^oaLfi%1-PM&)Clojri^7JfkloJ^k^Lfi%0-PM&)Clojri^7JfkloTfw^oaLfi%2PM&)Clojri^7OrkbaBqbokfrjOla%./DM&)Clojri^7PrmbofloJ^k^Lfi%2DM&)Clojri^7PrmbofloTfw^oaLfi%4DM&)M^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`e%3-PM&yyWyPe^qqo^qe@fqvy
?K^pj^o^Jllkplkd9Jllk`ilqePmb`f^ifpq;yKy%33+2)35+4&M^qqbok7Mofj^iJllk`ilqe%1DM&yyWyPe^qqo^qe@fqvy
?Phob^e9>i`ebjvPrmmifbp;yKy%13+2)/-+2&Ob`fmb7Qo^kpjrqbMofj^iJfdeq%5DM&yyWyPe^qqo^qe@fqvy
?SfddwPefkbpm^ohba9BkdfkbbofkdPrmmifbp;yKy%31+0)36+1&P`ebj^qf`7>a^j^kqfqbOfcib%5DM&)P`ebj^qf`7CrpbaTfofkd%.+3DM&yyWyPe^qqo^qe@fqvy

OK^do^kayKyQo^sbiqlK^do^ka%23+-)40+-&yyWyK^do^kay

?Rofhr9@llhfkdPrmmifbp;yKy%23+/)40+0&Ob`fmb7DofiibaJracfpe%0DM&)Ob`fmb7Ml^`eba?irbcfpe%0DM&)Ob`fmb7Ol^pqba@ibcqellc%0DM&)Ob`fmb7Q^i_rhPqb^h%0DM&yyWyK^do^kay

OW^kd^oj^opeyKyQo^sbiqlW^kd^oj^ope%34+5)15+-&yyWyW^kd^oj^opey

?E^^iork9>i`ebjvPrmmifbp;yKy%34+5)15+-&Ob`fmb7BifufolcJ^gloAbcbkpb%2DM&)Ob`fmb7BifufolcJ^gloColpqMltbo%1DM&)Ob`fmb7PrmboJ^k^Mlqflk%2DM&yyWyW^kd^oj^opey
?Al_^9@llhfkdPrmmifbp;yKy%1/+0)/4+6&Ob`fmb7?i^`hbkbaQolrq%/DM&)Ob`fmb7Cbiq^fiAbifdeq%/DM&yyWyW^kd^oj^opey
?JreborqebTb^sbo9Q^filofkdPrmmifbp;x1-+2)/5+/&M^qqbok7Fj_rbaKbqebotb^sb?llqp%3DM&)M^qqbok7Fj_rbaKbqebotb^sbM^kqp%3DM&yyWyW^kd^oj^opey
?Illiork^9>ojlobo;yKy%35+2)2-+.&Mi^kp7>a^j^kqfqb?ob^pqmi^qb%3DM&)Mi^kp7>a^j^kqfqbMi^qb?o^`bop%3DM&)Mi^kp7>a^j^kqfqbMi^qbDilsbp%3DM&yyWyW^kd^oj^opey
?GrklArco^fk9J^pqboCfpefkdQo^fkbo;yKy%45+.)33+-&>nr^avk^jf`Cfpe>qqo^`qlo%/+2PM&)Ob`fmb7?i^`hbkbaPmlobcfpe%/DM&yyWyW^kd^oj^opey

O?i^ab$pBadbJlrkq^fkpyKyQo^sbiql?i^ab$pBadbJlrkq^fkp%3.+/)35+6&yyWy?i^ab$pBadbJlrkq^fkpy

?Ubofkqe^O^sbkl^h9Clla#Aofkh;yKy%3/+2)1-+0&Ob`fmb7@ork`evPbombkq%0DM&)Ob`fmb7Jlh$K^qe^iPeloqof_p%0DM&yyWy?i^ab$pBadbJlrkq^fkpy

OKbqebopqlojyKyQo^sbiqlKbqebopqloj%25+1)0.+1&yyWyKbqebopqlojy

?Ab^iboE^wwfk9Dbkbo^iMolsfpflkbo;yKy%25+1)0.+1&J^gloEb^ifkdMlqflk%1-PM)&J^gloJ^k^Mlqflk%3-PM&)S^oflrpPq^qp`oliip%2*3PM&yyWyKbqebopqlojy
?Ab^iboJ^ifg9Bk`e^kqfkdPrmmifbp;yKy%11+/)01+-&Clojri^7IbppboTfw^oaLfi%1-PM&)Clojri^7JfkloJ^k^Lfi%0-PM&)Clojri^7JfkloTfw^oaLfi%2PM&)M^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`e%3-PM&yyWyKbqebopqlojy
?Ab^iboK^gbb_9Pm^obM^oqp;yKy%12+-)03+2&s^oflrpbkdfkbbofkdm^oqp%/-PM*./DM&)s^oflrpjlqbp%.3PMb^`e&yyWyKbqebopqlojy
?Ab^iboO^pe^^a9Bulqf`@ob^qrobp;yKy%10+2)02+/&5afccbobkqmbqp%1-PM*.-DM&yyWyKbqebopqlojy
?Ab^iboP^a^n^q9MlqbkqMlq^_ibp;yKy%10+0)02+-&J^glo>o`^kbMolqb`qflkMlqflk%/DM&)J^gloPe^altMolqb`qflkMlqflk%/DM&)s^oflrpeb^ifkdmlqflkp%1-PM*/DM&)s^oflrpj^k^mlqflkp%3-Pm*/DM&)s^oflrpebo_p%.-*3-PM&yyWyKbqebopqlojy

OEbiicfobMbkfkpri^yKyQo^sbiqlEbiicfobMbkfkpri^%/1+2)05+5&yyWyEbiicfobMbkfkpri^y

?Slabpffk9Ob^dbkqp;yKy%/1+2)05+5&Clojri^7Orkba>a^j^kqfqbOla%.-DM&yyWyEbiicfobMbkfkpri^y
??rohl9Jbaf`;yKy%//+2)06+/&J^pqboCfopq>fa*Al`qlofkqebElrpb%2DM&yyWyEbiicfobMbkfkpri^y
?@^obdfsboLmebo^Tfkacrov9Fkkhbbmbo;yKy'@eb`hdlfkdo^qbplk>E_bclob_rvfkd_^dp'%/0+1)03+2&Ao^bkf`Ib^qeboM^`h%./DM&)s^oflrplqebomolcbppflk_^dp%.-*.1DM&)Dob^qboJ^k^Mlqflk%./PM&yyWyEbiicfobMbkfkpri^y
?Gbwb_bi?f`^k9Fkp`ofmqflkPrmmifbp;yKy%20+6)32+2&Qb`ekfnrb7DivmelcBqbok^iT^qbo%0DM&)P`of_b$pP^q`ebi%2-PM&yyWyEbiicfobMbkfkpri^y
?PfaIfj_^oaf9Fkkhbbmbo;yKy%21+0)30+2&Ob`fmb7O^s^dboAld%/DM&yyWyEbiicfobMbkfkpri^y

OQbolhh^oClobpqyKyQo^sbiqlQbolhh^oClobpq%24+4)20+2&yyWyQbolhh^oClobpqy

?C^_f^kI^kwlkbiif9Dbkbo^iDllap#?^dp;yKy'@eb`hdlfkdo^qbplk>E_bclob_rvfkd_^dp'%24+4)20+2&Ao^bkf`Ib^qeboM^`h%./DM&)s^oflrplqebomolcbppflk_^dp%.-*.1DM&yyWyQbolhh^oClobpqy
?Fkkhbbmbo?fof_f9Fkkhbbmbo;yKy%23+4)20+0&Ob`fmb7DliabkCfpePqf`hp%0DM&)Ob`fmb7Pmf`v@o^ta^a%0DM&yyWyQbolhh^oClobpqy
?IbbifIlkde^ddib9Qo^abDllap;yKy%24+4)20+2&Ob`fmb7J^gloAob^jibppPibbmMlqflk%2DM&)Ob`fmb7Pkb^hfkdMlqflk%0DM&yyWyQbolhh^oClobpqy
?PrmmivLccf`boJfiip9O^qflkp;yKy%22+5)20+.&Ob`fmb7?i^`hbkba?^pfifph%0DM&)Ob`fmb7T^om?rodbo%0DM&yyWyQbolhh^oClobpqy
?Ab^iboQ^ofn9Pe^avAb^ibo;yKy%06+2)4-+-&s^oflrpjlqbp%.3PMb^`e&yyWyQbolhh^oClobpqy

OPe^altjllkS^iibvyKyQo^sbiqlPe^altjllkS^iibv%03+5)22+.&yyWyPe^altjllkS^iibvy

?J^ofPqlkbe^ka9>ojlopjfqe;yKy%03+5)22+.&Mi^kp7BqbokfrjOla%./DM&)Mi^kp7IbppboT^oalcPefbiafkd%3DM&yyWyPe^altjllkS^iibvy
?A^ddibFolkpe^mbo9Drkp#>jjrkfqflk;yKy%03+5)21+1&P`ebj^qf`7>a^j^kqfqbP`lmb%3DM&yyWyPe^altjllkS^iibvy
?>oolka9Q^filofkdPrmmifbp;yKy%22+6)25+/&M^qqbok7Fj_rbaKbqebotb^sbOl_b%3DM&)M^qqbok7Fj_rbaKbqebotb^sbQrkf`%3DM&yyWyPe^altjllkS^iibvy

KDrfab@ljmibqb
]]
end)
