DugisGuideViewer:RegisterGuide("Sholazar Basin (77+ The Oracles Dailies)", nil, "Alliance", "D", function()
return [[
AAA

CO^fkpmb^hbo@^klmvyKyCivqlO^fkpmb^hbo@^klmv%21)22&fkPeli^w^o?^pfky

KMf`hRm0Nrbpq^qO^fkpmb^hbo@^klmvyKyMf`hrm0Nrbpq?BCLOBQf`hfkdqefppqbm%20+0)23+3&y
KDbq^@ljm^kflk++yKyDbq^`ljm^kflkcoljEfde*Lo^`ibPll*p^v%21+2)23+1&^kvlkbtfiialy
>>@ib^kpfkdPlkdyLyyKyLo^`ibPll*kbb%20+0)23+3&yyNFAy./402yyAy
>PlkdlcCb`rkafqvyLyyKyLo^`ibPll*kbb%20+0)23+3&yyNFAy./404yyAy
>PlkdlcObcib`qflkyLyyKyLo^`ibPll*kbb%20+0)23+3&yyNFAy./403yyAy
>PlkdlcTfka^kaT^qboyLyyKyLo^`ibPll*kbb%20+0)23+3&yyNFAy./4/3yyAy
>>mmb^pfkdqebDob^qO^fkPqlkbyLyyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./4-1yyAy
>J^pqbovlcqeb@ovpq^ipyLyyKyLo^`ibPll*alt%21+/)20+6&yyNFAy./43.yyAy
>MltbolcqebDob^qLkbpyLyyKyLo^`ibPll*alt%21+/)20+6&yyNFAy./43/yyAy
>TfiilcqebQfq^kpyLyyKyLo^`ibPll*alt%21+/)20+6&yyNFAy./4-2yyAy

@>mmb^pfkdqebDob^qO^fkPqlkbyLyyKyIllhclopefkv^ob^lcafoq^olrka%21+-)2-+-&plI^cll`^kafdrmXPefkvQob^probpZyyNFAy./4-1yyAy
@>@ib^kpfkdPlkdyLyyKyRpbqebX@efjblc@ib^kpfkdZ^qqebpbil`^qflkpqlpm^tk^kahfiiqebKM@p%10)1/&*Pmfofqlc>qe^)%13)41&*PmfofqlcHllpr)%16)30&*PmfofqlcE^*He^i^kyyRy0624/yyNFAy./402yyAy
@MltbolcqebDob^qLkbpyLyyKy@e^odbqebXAloj^kqMlifpeba@ovpq^iZ^q%33)26&qebkrpbfqqlebimvlrhfiiqebTlis^op^q%/2)5-&yyNFAy./43/yyAy
@PlkdlcCb`rkafqvyLyyKyMi^vpqebXEloklcCb`rkafqvZlkqebmfibplcafoq^olrkaqefpil`^qflk%/1+1)02+0&yyRy06266yyNFAy./404yyAy
@PlkdlcObcib`qflkyLyyKyCivqlqebqlmplcqebclrofkq^`qmfii^op^ka^`qfs^qbqebXAfadbofalllc@lkqbjmi^qflkZkb^oqeb`ovpq^ipfkqeb`bkqbo)QebDifjjbofkdMfii^o7%16+3)04+1&QebPrkqlr`ebaMfii^o7%00+0)2/+0&QebJlppifdeqMfii^o7%03+1)42+0&QebPhvob^`eMfii^o7%20+3)46+1&yyRy06265yyNFAy./403yyAy
@PlkdlcTfka^kaT^qboyLyyKyDlql%/2)02&^karpbqebXAorjplcqebQbjmbpqZqefptfiiqo^kpclojvlrqlE^fmellk+HfiiPqlojObsbk^kqptefibfkT^qboCloj^kahfii>nrblrpPmfofqtefibfk>foClojyyRy0624.yyNFAy./4/3yyAy
@J^pqbovlcqeb@ovpq^ipyLyyKy@liib`qqebPm^ohqlr`eba@ovpq^iAbcbkpbp%00)42&^karpbqebdbjpqlhfiiqebTlis^op^q%/1+6)5.+5&yyNFAy./43.yyAy
@TfiilcqebQfq^kpyLyyKyHfiiqebTlis^op^q%/1)5-&rkqfivlrclrkaXQ^fkqba@ovpq^iZqebkdlql%00)42&ql`e^odbfqqebkvlr`^k`ljb_^`h^karpbfqqlebimvlrhfiiqebTlis^opyyNFAy./4-2yyAy

QJ^pqbovlcqeb@ovpq^ipyLyyKyIfdeqkfkd`^iiboPll*jbq%00+2)41+5&yyNFAy./43.yyAy
QMltbolcqebDob^qLkbpyLyyKyIfdeqkfkd`^iiboPll*jbq%00+2)41+5&yyNFAy./43/yyAy
QTfiilcqebQfq^kpyLyyKyIfdeqkfkd`^iiboPll*jbq%00+2)41+5&yyNFAy./4-2yyAy
Q>@ib^kpfkdPlkdyLyyKyLo^`ibPll*kbb%20+0)23+3&yyNFAy./402yyAy
QPlkdlcCb`rkafqvyLyyKyLo^`ibPll*kbb%20+0)23+3&yyNFAy./404yyAy
QPlkdlcObcib`qflkyLyyKyLo^`ibPll*kbb%20+0)23+3&yyNFAy./403yyAy
QPlkdlcTfka^kaT^qboyLyyKyLo^`ibPll*kbb%20+0)23+3&yyNFAy./4/3yyAy
Q>mmb^pfkdqebDob^qO^fkPqlkbyLyyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./4-1yyAy

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
