DugisGuideViewer:RegisterGuide("Sholazar Basin (77+ Frenzyheart Tribe Dailies)", nil, "Alliance", "D", function()
return [[
AAA

CCobkwveb^oqEfiiyKyCivqlCobkwveb^oqEfii%23)4-&fkPeli^w^o?^pfky

KMf`hRm0Nrbpq^qCobkwveb^oqEfiiyKyMf`hrm0Nrbpq?BCLOBQf`hfkdqefppqbm%22)36&y
>>Ebol$pEb^adb^oyLyyKyObgbh%22+4)36+2&yyNFAy./425yyAy
>@ef`hbkM^oqvyLyyKyBiaboE^ohbh%22+2)36+3&yyNFAy./4-/yyAy
>H^oq^h$pO^jm^dbyLyyKySbhd^o%22+3)35+5&yyNFAy./4-0yyAy
>Obgbh7Cfopq?illayLyyKyObgbh%22+4)36+2&yyNFAy./401yyAy
>Pb`obqPqobkdqelcqebCobkwveb^oqyLyyKySbhd^o%22+3)35+5&yyNFAy./43-yyAy
>PqobkdqelcqebQbjmbpqyLyyKyObgbh%22+4)36+2&yyNFAy./41.yyAy
>QebEb^oq_illa$pPqobkdqeyLyyKyObgbh%22+4)36+2&yyNFAy./40/yyAy
>QlliplcT^oyLyyKySbhd^o%22+3)35+5&yyNFAy./426yyAy

@>Ebol$pEb^adb^oyLyyKyHfiiqebSbkqrob@lpBu`^s^qlop^kaOrccf^kp^olrka%02)11&^kahfii^Pqlojt^q`ebo%/2)01&rpbXSbkqrob@l+BumilpfsbpZlkqeb_lavyyRy0632.yyNFAy./425yyAy
@@ef`hbkM^oqvyLyyRy05356yyKyRpbqebX@ef`hbkKbqZqlnrf`hivqo^mqeb`ef`hbk)_rqalklq`e^pbqebjloqebvtfiiork)lk`bqo^mmba)illqyyNFAy./4-/yyAy
@H^oq^h$pO^jm^dbyLyyKyHfiiPm^ohqlr`ebaKM@^olrka%0-)42&qll_q^fkqeb?illaP^jmibqebkrpbfq^qH^oq^h$pElia^q%/0)50&lkqeb>iq^oqlebimvlrhfii2-lo^`ibpyyRy06/32yyNFAy./4-0yyAy
@Obgbh7Cfopq?illayLyyKyRpbXObgbh$p?i^abZlkqeb`lompbplcP^mmefobEfsbT^pm7%22)42&)E^oahkr`hib@e^odbo7%3-)4-&)Jfpqtefpmbojbj_bop7%12)02&yyRy06244yyNFAy./401yyAy
@Pb`obqPqobkdqelcqebCobkwveb^oqyLyyKy?rvXQerkabo_obt$pE^oa>ibZclojDofj_llwb^qKbpfkdt^ov$p`^jm%/3+5)3-&)qebkdlqlH^oq^h$pelia+%/1)5-&^karpbqebXTlis^o?boofbpZ^kafqpelriadfsbvlrqeb?rcckbbaqlhfii0-Pm^ohqlr`ebaDroil`pyyRy06406yyNFAy./43-yyAy
@PqobkdqelcqebQbjmbpqyLyyKyHfiiPqlojObsbk^kqpcloBppbk`blcqebPqloj^ka>nrblrpPmfofqpcloBppbk`blcqebJlkpllk%/2)02&qebkdlqlqebPeofkb^q%//+1)00+5&yyNFAy./41.yyAy
@QebEb^oq_illa$pPqobkdqeyLyyKyHfiiDlobq^ilkJ^qof^o`e)il`^qba^q%26+4)/0+6&ql`liib`qXJ^qof^o`e$pEb^oq_illaZqebkrpbXObgbh$pSf^iZtfqet^qbocoljqebPrkqlr`ebaMfii^o^q%00)2-&qebkrpbXPrkqlr`ebaT^qboZql`lj_fkbqeb_illa^kat^qboqldbqeboyyNFAy./40/yyAy
@QlliplcT^oyLyyKy@liib`qWbmfh$pQo^mPq^peil`^qba^q%/0+6)50+.&qebkrpbqebfqbjvlrdbq)qlhfiiqebDroil`p^q%0-)4-&yyNFAy./426yyAy

Q>Ebol$pEb^adb^oyLyyKyObgbh%22+4)36+2&yyNFAy./425yyAy
Q@ef`hbkM^oqvyLyyKyBiaboE^ohbh%22+2)36+3&yyNFAy./4-/yyAy
QH^oq^h$pO^jm^dbyLyyKySbhd^o%22+3)35+5&yyNFAy./4-0yyAy
QObgbh7Cfopq?illayLyyKyObgbh%22+4)36+2&yyNFAy./401yyAy
QPb`obqPqobkdqelcqebCobkwveb^oqyLyyKySbhd^o%22+3)35+5&yyNFAy./43-yyAy
QPqobkdqelcqebQbjmbpqyLyyKyObgbh%22+4)36+2&yyNFAy./41.yyAy
QQebEb^oq_illa$pPqobkdqeyLyyKyObgbh%22+4)36+2&yyNFAy./40/yyAy
QQlliplcT^oyLyyKySbhd^o%22+3)35+5&yyNFAy./426yyAy

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
