DugisGuideViewer:RegisterGuide("Sholazar Basin (76+ Pre-Quest)", nil, "Alliance", "D", function()
return [[
AAA

KQefpdrfablkiv`lkq^fkp+++yKyQefpdrfablkiv`lkq^fkp^iiqebkb`bpp^ovpqbmpql_bdfkalfkda^fivnrbpqptfqeqebLo^`ibploCobkwveb^oqQof_b+Vlr`^kcfkaqeb`ljmibqbdrfabtfqeArdf$p.*5-ibsbifkddrfaby
HHfiiMfq`eyKyEb^aqlPhvob^`eMfii^o^q%2-+2)44+-&^kaHfiiMfq`eqlpq^oqqebnrbpqtfqeQo^`hboDbhdbhy
>Mi^vfkd>ilkdyKyQo^`hboDbhdbh%2-+2)43+4&yyNFAy./2/5y

QMi^vfkd>ilkdyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./2/5y
>Qeb>mbErkqbo$pPi^sbyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./2/6y
>QlojbkqfkdqebPlcqhkr`hibpyKyRpbXDlobdbh$pPe^`hibpZqlprjjlkDlobdbhqebDlofii^ErkqboyyNFAy./20-yyRy053.6y

@Qeb>mbErkqbo$pPi^sbyNFAy./2/6yyKyDlplrqeb^pqql%33+2)40+4&Hfii5E^oahkr`hibClo^dbop^ka3@e^odbopy
@QlojbkqfkdqebPlcqhkr`hibpyNFAy./20-yyRy05134yyKyRpbqebXPlcqhkr`hibMlhboZqlqlojbkqqeb_^_vdlofii^p^q%33+2)40+4&)tef`eprjjlkp^E^oahkr`hibJ^qof^`eqlhfiiy

QQlojbkqfkdqebPlcqhkr`hibpyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./20-y
QQeb>mbErkqbo$pPi^sbyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./2/6y
>QebT^pmErkqbo$p>mmobkqf`byKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./200y
>QebP^mmefobNrbbkyKyBiaboE^ohbh%22+2)36+3&yyNFAy./201y

@QebT^pmErkqbo$p>mmobkqf`byKyEb^aqlqebP^mme^fobEfsb^q%3-+-)44+6&+Hfii6EfsbAolkbp^ka3T^pmpyyNFAy./200y
@QebP^mmefobNrbbkyNFAy./201yyKyDlfkpfabqebild^kaqlqebsbov_lqqljlcqeb`^sb^kahfiiqebP^mmefobEfsbNrbbk%24+/)46+1&^kaillqebopqfkdboy

QQebT^pmErkqbo$p>mmobkqf`byKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./200y
QQebP^mmefobNrbbkyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./201y
>Ciltkqeb@llmyKyBiaboE^ohbh%22+2)36+3&yyNFAy./20/y
@Ciltkqeb@llmyNFAy./20/yyRy05356yyKyRpbqebX@ef`hbkKbqZqlnrf`hivqo^mqeb`ef`hbk)_rqalklq`e^pbqebjloqebvtfiiork)lk`bqo^mmba)illqy
QCiltkqeb@llmyKyBiaboE^ohbh%22+2)36+3&yyNFAy./20/y
>QebRkabodolrkaJbk^`byKyBiaboE^ohbh%22+2)36+3&yyNFAy./20.y
>Jfp`efbcfkqebJ^hfkdyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./202y

@Jfp`efbcfkqebJ^hfkdyNFAy./202yyKyEb^aqlqebofsbo^q%2.+3)53+/&^kaillq5lcqebXPhvob^`e@ovpq^i@irpqbopZ^ilkdqebofsboy
@QebRkabodolrkaJbk^`byNFAy./20.yyKyCfka^kahfiiPbocbuqebOb^sbotelfprkabodolrka^p^tloj^olrka%16+3)52+2&lo%25+5)52+2&y

QJfp`efbcfkqebJ^hfkdyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./202y
QQebRkabodolrkaJbk^`byKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./20.y
>>OlrdeOfabyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./203y

@>OlrdeOfabyNFAy./203yyKyQ^ihqlqeb@^mqfsb@ol`lifph%24+0)35+1&qebobqldbq^ofabqlJfpqtefpmboObcrdby
Q>OlrdeOfabyKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`ErkqboyyNFAy./203yyRy052./y
>IfdeqkfkdAbcfkfqbivPqofhbpQtf`byKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`ErkqboyyNFAy./204yyRy052./y
>QebJfpqFpk$qIfpqbkfkdyKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`ErkqboyyNFAy./205yyRy052./y
@QebJfpqFpk$qIfpqbkfkdyKyHfii./JfpqtefpmboDloil`p^olrkaqebobcrdb^q%12+-)04+-&yyNFAy./205y
@IfdeqkfkdAbcfkfqbivPqofhbpQtf`byNFAy./204yyRy052.-yyKyRpbqebXPhvob^`e@ovpq^i@irpqbopZ^qqeb_^pblcqebPeofkb^q%12+-)04+-&qebk`if`hqeb`ovpq^iqlp^_lq^dbfqy
QIfdeqkfkdAbcfkfqbivPqofhbpQtf`byKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`Erkqbo%4/)24&yyNFAy./204yyRy052./y
QQebJfpqFpk$qIfpqbkfkdyKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`Erkqbo%4/)24&yyNFAy./205yyRy052./y
>EllcfkdFqyKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`Erkqbo%4/)24&yyNFAy./206yyRy052./y

QEllcfkdFqyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./206y
>GrpqCliiltfkdLoabopyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./21-y

QGrpqCliiltfkdLoabopyKyFkgrobaO^fkpmb^hboLo^`ib%22+4)32&)tfiipm^tk^klk*bifqb`ol`lifphyyNFAy./21-y
>Cloqrk^qbJfprkabopq^kafkdpyKyFkgrobaO^fkpmb^hboLo^`ib%22+4)32&yyNFAy./24-y

QCloqrk^qbJfprkabopq^kafkdpyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./24-y
>J^hbqeb?^aPk^hbDl>t^vyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./24.y
>DlapIfhbPefkvQefkdpyKyRpbXI^cll$p?rd?^dZqlprjjlkI^cllyyNFAy./24/yyRy053//y

@J^hbqeb?^aPk^hbDl>t^vyKyHfiiqebBjmbolo@l_o^p^olrka%21+-)2-+-&^kaSbkljqfm^q%25+0)21+4&yyNFAy./24.y
@DlapIfhbPefkvQefkdpyKyTefipqhfiifkd`l_o^pt^ih^olrkaqebpefkv^ob^lcafoq^olrka%21+-)2-+-&plI^cll`^kafdrmXPefkvQob^probpZyyNFAy./24/yyRy053//y

QJ^hbqeb?^aPk^hbDl>t^vyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./24.y
QDlapIfhbPefkvQefkdpyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./24/y
>J^hfkdMb^`byKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./240y

@J^hfkdMb^`byNFAy./240yyKyPmb^htfqePe^j^kSbhgfh%2.+0)31+4&y

QJ^hfkdMb^`byKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./240y
>?^`hPlPllk<yKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./241y

Q?^`hPlPllk<yKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./241y
>QebIlpqJfpqtefpmboQob^probyKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./242y
>Clo`baE^kayKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./243y

@Clo`baE^kayNFAy./243yyRy053/0yyKy>qqebCobkwveb^oq`^jm%1-+3)/1+0&+RpbG^illqclobuqo^AMPlkqebjl_peboby
@QebIlpqJfpqtefpmboQob^probyNFAy./242yyKyRpbqeb>iq^o^q%1.+2).6+3&qlprjjlkT^oiloaQ^oqbh^kaefpao^dlk)hfiiqebj_lqe^kaillqqebXJfpqtefpmboQob^probZy

QQebIlpqJfpqtefpmboQob^probyKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./242y
QClo`baE^kayKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./243y
>EljbQfjbyKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./244y
QEljbQfjbyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./244y
>Qeb>kdovDloil`yKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./245y

QQeb>kdovDloil`yKyQo^sbiqlJlppt^ihboSfii^db^olrka%42)2/&qebkRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyNFAy./245yyRy053/1y
>QebJlppt^ihboP^sfloyKyRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyNFAy./25-yyRy053/1y
>Ifcb_illalcqebJlppt^ihboPeofkbyKyRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyNFAy./246yyRy053/1y
@QebJlppt^ihboP^sfloyKyDl^olrkaqeb`^jm%43+-)2/+6&^kaq^ihqlqebJlppt^ihboSf`qfjp^karkqfi3^obp^sbayyNFAy./25-y

@Ifcb_illalcqebJlppt^ihboPeofkbyKy@liib`q.-XIfcb_illaPe^oapZp`^qqbobalkqebdolrka^olrka%4/+1)3.+.&yyNFAy./246y
QIfcb_illalcqebJlppt^ihboPeofkbyKyRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyNFAy./246yyRy053/1y
QQebJlppt^ihboP^sfloyKyRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyNFAy./25-yyRy053/1y

>>Ebol$p?roabkyKyRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyRy053/1yyNFAy./25.y
KLo^`ibloCobkwveb^oq+++yKyArofkdqebkbuqnrbpqvlrtfii^qq^`h>oqorfpqebEb^oqibpp%4/+/)24+1&teltfiiprjjlk/KM@^q0-"em)Fcvlrt^kqLo^`ibp7HfiiWbmf`)Fcvlrt^kqCobkwveb^oq7HfiiG^illqy
@>Ebol$p?roabkyKyHfii>oqorfpqebEb^oqibpp%4/+/)24+1&yyNFAy./25.y
Q>Ebol$p?roabkyKyRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyRy053/1yyNFAy./25.y

KMf`hrmNrbpqColjP^sbaKM@
>ObqroklcqebCofbkaivAovphfkyLyyNFAy./362y
QObqroklcqebCofbkaivAovphfkyLyyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./362y

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
