DugisGuideViewer:RegisterGuide("The Sons of Hodir (750 - 1950 +Rep)", nil, "Alliance", "D", function()
return [[
AAA

CArkKfccbibjyKyCivqlArkKfccbibj%31)3.&yyWyQebPqlojMb^hpy
KMf`hRm0*3NrbpqyKyMf`hrm0NrbpqfkArkKfccbibjfcvlr$obCofbkaiv)2Nrbpqfcvlr$obElkloba)3Nrbpqfcvlr$obObsbobaqebkqf`hqefp_lu%30+/)3/+6&)%31+/)31+1&)%31+2)26+3&)%30+2)26+5&)%32)3-+6&)%34+2)3-&yyWyQebPqlojMb^hpy
>Elq^ka@liayKyCglok$p>ksfi%30+/)3/+6&yyNFAy./65.yyWyQebPqlojMb^hpyyAy
>?iltfkdElafo$pElokyKyElafo$pElok%31+/)31+1&yNFAy./644yyWyQebPqlojMb^hpyyAy
>MlifpefkdqebEbijyKyElafo$pEbij%31+2)26+3&yyNFAy.0--3yyWyQebPqlojMb^hpyyAy
>PmvErkqboyLyyKyElklobaObmrq^qflkqlQebPlkplcElafolkiv*ColpqtlodAbkjlqebo%30+2)26+5&yyNFAy./661yyWyQebPqlojMb^hpyyAy
>QeorpqfkdElafo$pPmb^oyLyyKyElklobaObmrq^qflkqlQebPlkplcElafolkiv*Elafo$pPmb^o%32)3-+6&yyNFAy.0--0yyWyQebPqlojMb^hpyyAy
>Cbbafkd>okdofjyLyyKyObsbobaObmrq^qflkqlQebPlkplcElafolkiv*>okdofjqebFkp^qf^_ib%34+2)3-&yyNFAy.0-13yyWyQebPqlojMb^hpyyAy

@Cbbafkd>okdofjyLyyKyFcvlre^sbmbqpmrqqebjfkqlm^ppfsbjlab+DlqlqebS^iibvlc>k`fbkqTfkqbop%24)31&^karpbX>okdofj$pQllqeZlkqebOl^jfkdGlojrkd^oqebob+Lk`bqebve^sb_b`ljbafpbj_lafba)vlrjrpqcfdeqqebjrkqfiqebv^obtb^hbkbayyRy1/441yyNFAy.0-13yyWyQebPqlojMb^hpyyAy
@PmvErkqboyLyyKyDllrqql%24+/)31&^karpbXBqebob^iTlod$pC^kdZcliiltqebtlicqe^q^mmb^opqebkhfiiqebAt^osbptebkebpm^tkpqebj)fcvlrdolrmtfqelqebomi^vbopalfkdqefpnrbpqfqtfii_bJR@EC>PQBOyyRy1/146yyNFAy./661yyWyQebPqlojMb^hpyyAy
@MlifpefkdqebEbijyKyBkqboEf_bok^i@^sboktbpqlcArkKfccbibj%22+3)3/+6&^ka`liib`q2rkfqplcXSfp`lrpLfiZcoljqebSfp`lrpLfipqebob+yyNFAy.0--3yyWyQebPqlojMb^hpyyAy
@QeorpqfkdElafo$pPmb^oyRy1/436yyLyyKyFcvlr$obqovfkdqefpcloqeb.pqqfjbq^hblcc^iivlro^ojlofk`^pbvlrafb+RpbXPmb^olcElafoZlk^TfiaTvoj+Lk`bjlrkqbahbbmmobppfkd.^ka0)tebkvlrdbqqeb$`i^tt^okfkd$mobpp/qlaladbqebmobpp1+Fkqebkbuqme^pb)mobpp.rkqfivlrpq^`h^qib^pq.-$Mov$^ka^qqbjmqqlhfiifq_vmobppfkd/)fcfqc^fiphbbmmobppfkd.rkqfi/_b`ljbp^s^fi^_ib^d^fk+yyNFAy.0--0yyWyQebPqlojMb^hpyyAy
@?iltfkdElafo$pElokyKyHfii2KfccbibjClobc^qebop^ka2ObpqibppColpq_lok^qQerkaboc^ii%4.)2/&QebkrpbXElafo$pElokZlsboqebfo`lompbpyyRy1/.31yyNFAy./644yyWyQebPqlojMb^hpyyAy
HHfii?ofqqibObsbk^kqyKyHfii?ofqqibObsbk^kq^ka`liib`q3uXBppbk`blcF`bZ%4-)26&yyIy1//133yyWyQebPqlojMb^hpy
@Elq^ka@liayKyillhcloQfkv_i^`hqefkdptfqepjlhb`ljfkdrmcoljqebj%41)3/&Qebv^obb^pfboqlpmlqfkqebpklt+Dbqkb^olkb)rpb^kXBppbk`blcF`bZ)qebkofdeq*`if`hillqqebjbq^ip`o^m+Alqefprkqfivlre^sb2yyRy1//13yyNFAy./65.yyWyQebPqlojMb^hpyyAy

QElq^ka@liayKyCglok$p>ksfi%30+/)3/+6&yyNFAy./65.yyWyQebPqlojMb^hpyyAy
Q?iltfkdElafo$pElokyKyElafo$pElok%31+/)31+1&yNFAy./644yyWyQebPqlojMb^hpyyAy
QMlifpefkdqebEbijyKyElafo$pEbij%31+2)26+3&yyNFAy.0--3yyWyQebPqlojMb^hpyyAy
QPmvErkqboyLyyKyColpqtlodAbkjlqebo%30+2)26+5&yyNFAy./661yyWyQebPqlojMb^hpyyAy
QQeorpqfkdElafo$pPmb^oyLyyKyElafo$pPmb^o%32)3-+6&yyNFAy.0--0yyWyQebPqlojMb^hpyyAy
QCbbafkd>okdofjyLyyKyObsbobaObmrq^qflkqlQebPlkplcElafolkiv*>okdofjqebFkp^qf^_ib%34+2)3-&yyNFAy.0-13yyWyQebPqlojMb^hpyyAy

KTebkVlroOb^`eElklobayKyQebcliiltfkdnrbpqobnrfobpElklobaobmrq^qflkqlqebPlkplcElafo)vlrlkive^sbqlalqebpbnrbpqlk`byyNFAy.0--.y
>O^fpfkdElafo$pPmb^oyKyElklobaObmrq^qflkqlQebPlkplcElafolkiv*Qf`hqefpnrbpqfcvlre^sb^iob^avalkbfq)vlre^sbqlalqefpnrbpq_bclobob`bfsfkd^kbta^fiv^qelkloba)IlobhbbmboO^kasfo%31+5)26+.&yyNFAy.0--.yyWyQebPqlojMb^hpy
@O^fpfkdElafo$pPmb^oyKyBkqboqeb`^sb^q%22+6)31+3&^ka`liib`q0XBsbocolpqPe^oapZ%21+4)3-+4&coljqebabmqeplcEf_bok^i@^sbok^ka0XPqlf`J^jjlqeEfabpZcoljqebPqlf`J^jjlqepfkqebS^iibvlc>k`fbkqTfkqbop+yNFAy.0--.yyWyQebPqlojMb^hpy
QO^fpfkdElafo$pPmb^oyKyIlobhbbmboO^kasfo%31+5)26+.&yyNFAy.0--.yyWyQebPqlojMb^hpy

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
