DugisGuideViewer:RegisterGuide("Speed Gold Run - AT Rank:Aspirant (80 Dailies)", nil, "Alliance", "D", function()
return [[
AAA

CH0yKyCivqlH0fkQebPqlojMb^hpyyWyQebPqlojMb^hpy
>Lsbopql`hyKyOf`hbq%1-+6)52+1&yyNFAy./500yyWyQebPqlojMb^hpyyAy
@Lsbopql`hyKyRpbqebXFjmolsbaI^kaJfkbpZ^q%1/)5/&qlhfii./uD^ojFks^abopyyRy1-343yyNFAy./500yyWyQebPqlojMb^hpyyAy
QLsbopql`hyKyOf`hbq%1-+6)52+1&yyNFAy./500yyWyQebPqlojMb^hpyyAy

CArkKfccbibjyKyCivqlArkKfccbibj)rpbPhfwwibPif`hpifab%1-+4)51+3&yyWyQebPqlojMb^hpy
KMf`hRm0*3NrbpqyKyMf`hrm0NrbpqfkArkKfccbibjfcvlr$obCofbkaiv)2Nrbpqfcvlr$obElkloba)3Nrbpqfcvlr$obObsbobaqebkqf`hqefp_lu%30+/)3/+6&)%31+/)31+1&)%31+2)26+3&)%30+2)26+5&)%32)3-+6&)%34+2)3-&yyWyQebPqlojMb^hpy
>Elq^ka@liayKyCglok$p>ksfi%30+/)3/+6&yyNFAy./65.yyWyQebPqlojMb^hpyyAy
>?iltfkdElafo$pElokyKyElafo$pElok%31+/)31+1&yNFAy./644yyWyQebPqlojMb^hpyyAy
>MlifpefkdqebEbijyKyElafo$pEbij%31+2)26+3&yyNFAy.0--3yyWyQebPqlojMb^hpyyAy
>PmvErkqboyLyyKyElklobaObmrq^qflkqlQebPlkplcElafolkiv*ColpqtlodAbkjlqebo%30+2)26+5&yyNFAy./661yyWyQebPqlojMb^hpyyAy
>QeorpqfkdElafo$pPmb^oyLyyKyElklobaObmrq^qflkqlQebPlkplcElafolkiv*Elafo$pPmb^o%32)3-+6&yyNFAy.0--0yyWyQebPqlojMb^hpyyAy
>Cbbafkd>okdofjyLyyKyObsbobaObmrq^qflkqlQebPlkplcElafolkiv*>okdofjqebFkp^qf^_ib%34+2)3-&yyNFAy.0-13yyWyQebPqlojMb^hpyyAy

@Cbbafkd>okdofjyLyyKyFcvlre^sbmbqpmrqqebjfkqlm^ppfsbjlab+DlqlqebS^iibvlc>k`fbkqTfkqbop%24)31&^karpbX>okdofj$pQllqeZlkqebOl^jfkdGlojrkd^oqebob+Lk`bqebve^sb_b`ljbafpbj_lafba)vlrjrpqcfdeqqebjrkqfiqebv^obtb^hbkbayyRy1/441yyNFAy.0-13yyWyQebPqlojMb^hpyyAy
@PmvErkqboyLyyKyDllrqql%24+/)31&^karpbXBqebob^iTlod$pC^kdZcliiltqebtlicqe^q^mmb^opqebkhfiiqebAt^osbptebkebpm^tkpqebj)fcvlrdolrmtfqelqebomi^vbopalfkdqefpnrbpqfqtfii_bJR@EC>PQBOyyRy1/146yyNFAy./661yyWyQebPqlojMb^hpyyAy
@MlifpefkdqebEbijyKyBkqboEf_bok^i@^sboktbpqlcArkKfccbibj%22+3)3/+6&^ka`liib`q2rkfqplcXSfp`lrpLfiZcoljqebSfp`lrpLfipqebob+yyNFAy.0--3yyWyQebPqlojMb^hpyyAy
@QeorpqfkdElafo$pPmb^oyRy1/436yyLyyKyFcvlr$obqovfkdqefpcloqeb.pqqfjbq^hblcc^iivlro^ojlofk`^pbvlrafb+RpbXPmb^olcElafoZlk^TfiaTvoj+Lk`bjlrkqbahbbmmobppfkd.^ka0)tebkvlrdbqqeb$`i^tt^okfkd$mobpp/qlaladbqebmobpp1+Fkqebkbuqme^pb)mobpp.rkqfivlrpq^`h^qib^pq.-$Mov$^ka^qqbjmqqlhfiifq_vmobppfkd/)fcfqc^fiphbbmmobppfkd.rkqfi/_b`ljbp^s^fi^_ib^d^fk+yyNFAy.0--0yyWyQebPqlojMb^hpyyAy
@?iltfkdElafo$pElokyKyHfii2KfccbibjClobc^qebop^ka2ObpqibppColpq_lok^qQerkaboc^ii%4.)2/&QebkrpbXElafo$pElokZlsboqebfo`lompbpyyRy1/.31yyNFAy./644yyWyQebPqlojMb^hpyyAy
H?ofqqibObsbk^kqyKyHfii?ofqqibObsbk^kq^ka`liib`q3XBppbk`blcF`bZ%4-)26&yyIy1//133yyWyQebPqlojMb^hpy
@Elq^ka@liayKyillhcloQfkv_i^`hqefkdptfqepjlhb`ljfkdrmcoljqebj%41)3/&Qebv^obb^pfboqlpmlqfkqebpklt+Dbqkb^olkb)rpb^kXBppbk`blcF`bZ)qebkofdeq*`if`hillqqebjbq^ip`o^m+Alqefprkqfivlre^sb2yyRy1//13yyNFAy./65.yyWyQebPqlojMb^hpyyAy

QElq^ka@liayKyCglok$p>ksfi%30+/)3/+6&yyNFAy./65.yyWyQebPqlojMb^hpyyAy
Q?iltfkdElafo$pElokyKyElafo$pElok%31+/)31+1&yNFAy./644yyWyQebPqlojMb^hpyyAy
QMlifpefkdqebEbijyKyElafo$pEbij%31+2)26+3&yyNFAy.0--3yyWyQebPqlojMb^hpyyAy
QPmvErkqboyLyyKyColpqtlodAbkjlqebo%30+2)26+5&yyNFAy./661yyWyQebPqlojMb^hpyyAy
QQeorpqfkdElafo$pPmb^oyLyyKyElafo$pPmb^o%32)3-+6&yyNFAy.0--0yyWyQebPqlojMb^hpyyAy
QCbbafkd>okdofjyLyyKyObsbobaObmrq^qflkqlQebPlkplcElafolkiv*>okdofjqebFkp^qf^_ib%34+2)3-&yyNFAy.0-13yyWyQebPqlojMb^hpyyAy

C>odbkqQlrok^jbkqDolrkapyKyrpbE^isa^k%3/+4)3-+6&yyWyQebPqlojMb^hpy

KMf`hrm0A^fivNrbpqyKy>o`^kfpqQ^bifp%43+2).6+2&lccbop.lc0o^kalja^fivnrbpqpyyWyF`b`oltky
ePfisbo@lsbk^kqM^sfiflkyKyJ^hbprobvlropbqvlroeb^oqepqlkbql>odbkqQlrok^jbkqDolrkap@^ofpPrki^k`b%43+/).6+3&yyWyF`b`oltky

>QebBadbLcTfkqboyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.034-yyWyF`b`oltkyyAy
>>?i^abCfqClo>@e^jmflkyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.0333yyWyF`b`oltkyyAy
>>TloqevTb^mlkyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.0336yyWyF`b`oltkyyAy
>Qo^fkfkdFkQebCfbiayKy>s^obqePtfcqpqofhb%43+2).6+1&)A^fivyyNFAy.034.yyWyF`b`oltkyyAy
>Ib^okfkdQebObfkpyKyP`lrqPe^ivkaof^%43+2).6+2&)A^fivyyNFAy.03/2yyWyF`b`oltkyyAy

KDbqlkJlrkqyKyBnrfmX>iif^k`bI^k`bZ^kadbq^Jlrkq%42+6)/-+1&lo%4.+52)/-&yyRy13-36yyWyF`b`oltky
@Ib^okfkdQebObfkpyKyBnrfmqebX>iif^k`bI^k`bZ^kajlrkqqebNrbi$AlofbPqbbaclrka^q%42+6)/-+1&+RpbqebQorpq^_fifqvlk^JbibbQ^odbq2qfjbp)rpfkdAbcbka`lkpq^kqivqlhbbm0i^vboprm+ObcobpevlrojlrkqqebkrpbqebPefbia?ob^hbo^_fifqvlk^O^kdbaQ^odbqobmb^qfsbivrkqfisrikbo^_ibqebkrpbqebPefbia?ob^hbo^_fifqvlk^@e^odbQ^odbqqebkrpbqeb@e^odb^_fifqvqtf`btefibfqppefbiafpaltkyyNFAy.03/2yyRy13-4-yyAy
@Qo^fkfkdFkQebCfbiayKyHfii^kvP`lrodb^olrka%4.+1)04+6&yyNFAy.034.yyWyF`b`oltkyyAy

OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&yyWyF`b`oltky
>Ao^d^kaAolmyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.00/0yyWyF`b`oltkyyAy
>Klq^?rdyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0011yyWyF`b`oltkyyAy
>Qe^q$p>_ljfk^_ibyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0/56yyWyF`b`oltkyyAy
>@^mqrobJlobAfpm^q`ebpyKyEfde@^mq^fkGrpqfk?^oqibqqlkQebPhv_ob^hboyyNFAy.0000yyWyF`b`oltkyyAy
>Pi^sbpqlP^olkfqbyKy>_p^i^kqebMflrplkQebPhv_ob^hboyyNFAy.00--yyWyF`b`oltkyyAy
>?illalcqeb@elpbkyKyHkfdeq*@^mq^fkAolp`ebOfleqlkQebPhv_ob^hboyyNFAy.0003yyWyF`b`oltkyyAy
>QebPlirqflkPlirqflkyKy@efbcBkdfkbbo?liqtobk`elkQebPhv_ob^hboyyNFAy.0/6/yyWyF`b`oltkyyAy
>ObqbpqKltyKy@efbcBkdfkbbo?liqtobk`elkQebPhv_ob^hboyyNFAy.00//yyWyF`b`oltkyyAy

>>pp^riq_vDolrkayKyPhv_ob^hboPnr^aIb^abo%3/+4)2.&yyNFAy.0/51yyWyF`b`oltkyyAy
@>pp^riq_vDolrkayKyBp`loqqebPhv_ob^hboqollmpyyNFAy.0/51yyWyF`b`oltkyyAy
@?illalcqeb@elpbkyKyHfii/-VjfoebfjSovhri^qVjfoebfj%26)21&yyNFAy.0003yyWyF`b`oltkyyAy
Q>pp^riq_vDolrkayKyDolrka@ljj^kaboHlrm%3/+3)2.+0&yyNFAy.0/51yyWyF`b`oltkyyAy

>>pp^riq_v>foyKyDolrka@ljj^kaboHlrm%3/+3)2.+0&yyNFAy.00-6yyWyF`b`oltkyyAy
@>pp^riq_v>foyKyDlql%3/+2)2-+4&^kajlrkqqeb>fomi^kb)j^hbprobqebob^obfkcfiqo^qlopfkqebmi^kb_bclobvlrdlyyNFAy.00-6yyWyF`b`oltkyyAy
Q>pp^riq_v>foyKyDolrka@ljj^kaboHlrm%3/+3)2.+0&yyNFAy.00-6yyWyF`b`oltkyyAy

>HfkdlcqebJlrkq^fkyKyCo^wwibDb^odofkabo%24)3/+2&yyNFAy.0/5-yyWyF`b`oltkyyAy
@HfkdlcqebJlrkq^fkyKyJlrkqQerkabo_lj_$pGrjm_lqkbuqqlvlr^kagrjmvlrot^vrmqlqebmfiblc_lkbp%21+51)3-+.1&yyNFAy.0/5-yyWyF`b`oltkyyAy
QHfkdlcqebJlrkq^fkyKyCo^wwibDb^odofkabo%24)3/+2&yyNFAy.0/5-yyWyF`b`oltkyyAy
@Pi^sbpqlP^olkfqbyKyDlqlqebP^olkfqbJfkbp%23)24&)pfjmivq^ihqlqebP^olkfqbJfkbPi^sbpfkqebjfkb)vlre^sb^`e^k`bqe^qqebvtfiiorklrqlcqebjfkb^kadfsbvlrnrbpq`obafq)loqrokelpqfiblkvlryyNFAy.00--yyWyF`b`oltkyyAy

@Ao^d^kaAolmyKyDlPlrqelcqeb_ofadb^olrka%20)13&)hfiiqebjl_pqebobcloqebLo_lcFiirpflknrbpqfqbjvlrkbba)qebkqeoltfq^qqebA^ohPr_grd^qlopcolj^afpq^k`btefiblrqlc`lj_^q+yyRy11/13yyNFAy.00/0yyWyF`b`oltkyyAy

RAofkhRmyKyRpbXAfirqba@riqQlkf`ZcloqebnrbpqObqbpqKltyyRy110-4yyWyF`b`oltky
HHfii@riqKM@pyKyHfii@riqKM@p%16)00&^ka`liib`q.-uXQ^fkqbaBppbk`bZyyIy110-..-yyWyF`b`oltky
R@ob^qbXTofqefkdJ^ppZyKyOfdeq`if`hlkXQ^fkqbaBppbk`bZyyRy110-.yyWyF`b`oltky
@ObqbpqKltyKyRpbqebXQ^fkqbaBppbk`bZql`lj_fkbaqebjfkql^XTofqefkdJ^ppZ^karpbfqlk^`^riaolk^q%16)01&)A^oh@^riaolk7>qq^`hMltbo)?irb@^riaolk7Pmbiimltbo)Dobbk@^riaolk7Pq^jfk^yyRy110-1yyNFAy.00//yyWyF`b`oltkyyAy
HBkpi^sbaJfkflkpyKyHfiiBkpi^sbaJfkflkp%22)/6&qebkrpbXOlalcPfmelkfkdZql`liib`q2uXA^ohJ^qqboZyyRy11100yyIy111012yyWyF`b`oltky
@Klq^?rdyKyLk`bvlre^sb`liib`qba2uXA^ohJ^qqboZofdeq`if`hlkqebMromibPrjjlkfkdPqlkb^q%20+4)00+3&yyNFAy.0011yyWyF`b`oltkyyAy

@@^mqrobJlobAfpm^q`ebpyKyRpbXA^oqDrkZql`^mqrob3Lodofj$pE^jjboAfpm^q`e^olrka%15)21&yyRy11///yyNFAy.0000yyWyF`b`oltkyyAy

OQebPe^altS^riqyKyCivqlQebPe^altS^riq%10+.)/1+/&yyWyF`b`oltky
>SfibIfhbCfobyKySfib%10+2)/1+2&yyNFAy.0-4.yyWyF`b`oltkyyAy
>Pellq$BjRmyKyQebIb^mbo%10+3)/2+.&yyNFAy.0-36yyWyF`b`oltkyyAy
>Ib^sbLroJ^ohyKy?^olkPifsbo%1/+6)/2&yyNFAy./662yyWyF`b`oltkyyAy
@Pellq$BjRmyKyDlql%0/)/1&^ka`ellpblkblcqebe^omllkp+Vlrkbbaqlt^fqrkqfiqebao^dlkpcivsbovkb^o)fcvlrkbbajlobqe^k{2pelqp^kaqebvalk$qafbqe^qjb^kpqe^qqebv^obk$qkb^obklrde+Alkqqovqlpellqqeblkbptef`e^obc^o^t^v)vlr`^k$qhfiiqebj+yyNFAy.0-36yyWyF`b`oltkyyAy
@Ib^sbLroJ^ohyKyHfiiqebSvhrip%0-)/5&^karpbXB_lk?i^ab?^kkboZlkqeb`lompbpyyRy1/15-yyNFAy./662yyWyF`b`oltkyyAy
@SfibIfhbCfobyKyDlql%/4)06&^kajlrkq^Ao^hb)^ka_rokqeb_rfiafkdpfkqeb^ob^yyNFAy.0-4.yyWyF`b`oltkyyAy
QPellq$BjRmyKyQebIb^mbo%10+3)/2+.&yyNFAy.0-36yyWyF`b`oltkyyAy
QSfibIfhbCfobyKySfib%10+2)/1+2&yyNFAy.0-4.yyWyF`b`oltkyyAy
QIb^sbLroJ^ohyKy?^olkPifsbo%1/+6)/2&yyNFAy./662yyWyF`b`oltkyyAy

C@orp^abop$Mfkk^`ibyKyCivql@orp^abop$Mfkk^`ib)rpbJloif^Alljtfkd%10+4)/1+1&yyWyF`b`oltky

@Qe^q$p>_ljfk^_ibyKyHfii^Erihfkd>_ljfk^qflk%35)30&^ka`liib`q^X@efiiba>_ljfk^qflkDrqpZqebkrpbqebX>_ljfk^qflkOb^kfj^qflkHfqZqlprjjlk^k>_ljfk^qflkrpbfqql_iltrmqebdelrip+Alk$qbumilabtefibqebdelrip^obpqrkkbalobipbvlrtlk$qdbq^kv`obafq+Vlr`^k^iplqovjlrkqfkdrm^cqboprjjlkfkdqeb>_ljfk^qflkyyNFAy.0/56yyRy10635yyWyF`b`oltkyyAy
@QebPlirqflkPlirqflkyKyMf`hrmqeb0l_gb`qpp`^qqboba^olrkaqeb^ob^%36)33&XMfiblc?lkbpZ)X>_^kalkbaEbijZ)^kaX>_^kalkba>ojloZ)dbq0lcb^`elcqebj^kaqebkrpbqebX@lmmbo`i^t$pSli^qfibLfiZnrbpqfqbj0qfjbp+yyRy103-5yyNFAy.0/6/yyWyF`b`oltkyyAy

@>?i^abCfqClo>@e^jmflkyLyyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrka%3-+2)2.+2&fkDofwwivEfiipyyRy11653yyNFAy.0333yyWyDofwwivEfiipyyAy

KQebBadbLcTfkqboyKyPhfmqefppqbmfcvlralk$qe^sbqebnrbpq$QebBadbLcTfkqbo$CfkaIloaBsbo_i^wb^olrka%22)42+/&fk@ovpq^iplkdClobpq^kaillqefpXBsbo_rokfkdBj_boZqebkqf`hqefpl_gb`qfsbyyIy12--2yyWy@ovpq^iplkdClobpqy
@QebBadbLcTfkqboyLyyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^q%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyNFAy.034-yyWyEltifkdCgloayyAy

K>TloqevTb^mlkyKyPhfmqefppqbmfcvlralk$qe^sbqebnrbpq$>TloqevTb^mlk$@liib`q1XTfkqboEv^`fkqeZ^olrka%4.)41+2&fkF`b`oltkqebkqf`hqefpl_gb`qfsbyyIy12---1yyWyF`b`oltky
@>TloqevTb^mlkyLyyKyQ^hbqebciltbop^karpbfqtfqeqebJ^fabkclrka^q%6/+5)/2+1&fkAo^dlk_ifdeqyyRy12---yyWyAo^dlk_ifdeqyyNFAy.0336yyAy

EPfisbo@lsbk^kqM^sfiflkyRy3615y

Q>?i^abCfqClo>@e^jmflkyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.0333yyWyF`b`oltkyyAy
QQebBadbLcTfkqboyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.034-yyWyF`b`oltkyyAy
Q>TloqevTb^mlkyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.0336yyWyF`b`oltkyyAy
QQo^fkfkdFkQebCfbiayKy>s^obqePtfcqpqofhb%43+2).6+1&)A^fivyyNFAy.034.yyWyF`b`oltkyyAy
QIb^okfkdQebObfkpyKyP`lrqPe^ivkaof^%43+2).6+2&)A^fivyyNFAy.03/2yyWyF`b`oltkyyAy

OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&yyWyF`b`oltky
QAo^d^kaAolmyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.00/0yyWyF`b`oltkyyAy
QKlq^?rdyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0011yyWyF`b`oltkyyAy
QQe^q$p>_ljfk^_ibyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0/56yyWyF`b`oltkyyAy
Q@^mqrobJlobAfpm^q`ebpyKyEfde@^mq^fkGrpqfk?^oqibqqlkQebPhv_ob^hboyyNFAy.0000yyWyF`b`oltkyyAy
QPi^sbpqlP^olkfqbyKy>_p^i^kqebMflrplkQebPhv_ob^hboyyNFAy.00--yyWyF`b`oltkyyAy
Q?illalcqeb@elpbkyKyHkfdeq*@^mq^fkAolp`ebOfleqlkQebPhv_ob^hboyyNFAy.0003yyWyF`b`oltkyyAy
QQebPlirqflkPlirqflkyKy@efbcBkdfkbbo?liqtobk`elkQebPhv_ob^hboyyNFAy.0/6/yyWyF`b`oltkyyAy
QObqbpqKltyKy@efbcBkdfkbbo?liqtobk`elkQebPhv_ob^hboyyNFAy.00//yyWyF`b`oltkyyAy

KDrfab@ljmibqb
]]
end)
