DugisGuideViewer:RegisterGuide("The Storm Peaks (80 Dailies)", nil, "Alliance", "D", function()
return [[
AAA

CH0yKyCivqlH0fkQebPqlojMb^hp%1-+6)52+1&y
>Lsbopql`hyKyOf`hbq%1-+6)52+1&yyNFAy./500yyAy
@Lsbopql`hyKyRpbqebXFjmolsbaI^kaJfkbpZ^q%1/)5/&qlhfii./uD^ojFks^abopyyRy1-343yyNFAy./500yyAy
QLsbopql`hyKyOf`hbq%1-+6)52+1&yyNFAy./500yyAy

CColpqeliayKyCivqlColpqElia%/6+5)42+4&y
>MrpebaQllC^oyKyCgloifkColpq_olt%/6+5)42+4&yyNFAy./536yyAy
@MrpebaQllC^oyKyTebkvlrpq^oqqefpnrbpq)vlr$iijlrkqrmlk^Pqloj`obpqB^dib+CivqlqebCllqPqbmmbpfkqebKloqeb^pq^kaillhcloPqlojmb^hTvojp%13+2)3.+6&+Vlro_fddbpq`e^iibkdbtfii_b`^q`efkdqebqefkdp)pfk`bqebv`^kcivc^pqboqe^kvlrob^dibalbp+Qebmobcboobamobvtfii_bqebtvojptel^obbfqeboollpqbalkqebjlrkq^fkp^kaol`hplo^ob^qq^`hfkdoefklp+Fcvlrcfkalkblcqelpb)qebv$obb^pvmf`hfkdp+Qebvjbibb^kae^sb^tb^hcolpq_ob^qe^qq^`h)_rq^obklqeob^qqlvlrob^dib+Fcvlr`^k$qcfka^kvtel^obollpqbaloafpqo^`qba)vlr`^k`^q`eqebcifbop_veb^afkdqebjlcc+Qebvj^v_bc^pqbo)_rqvlr$objr`ejlobj^kbrsbo^_ib+yyNFAy./536yyAy
QMrpebaQllC^oyKyCgloifkColpq_olt%/6+5)42+4&yyNFAy./536yyAy

C?orkkefia^oSfii^dbyKyCivql?orkkefia^oSfii^db%2-+6)32+3&y
KMf`hrmNrbpqyKyMf`hrmnrbpqpcoljDobqq^qeb>o_fqbo%2-+6)32+3&y
>Qeb>_boo^qflkpJrpqAfbyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyLyyNFAy.01/2yyAy
>J^fkq^fkfkdAfp`fmifkbyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyLyyNFAy.01//yyAy
>?^`hqlqebMfqyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyLyyNFAy.01/1yyAy
>AbcbkafkdVlroQfqibyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyLyyNFAy.01/0yyAy

@Qeb>_boo^qflkpJrpqAfbyKyDlqlS^ihvoflk%/2)3-&^kal_q^fkXSf^iplcColpqLfiZcoljqebS^ihvoflk>pmfo^kqp+RpbqebXSf^ilcColpqLfiZqlabpqolv0-Mi^drbaMolql*Ao^hbBddp+yyRy1.3./yyNFAy.01/2yyLyyAy
@J^fkq^fkfkdAfp`fmifkbyKyDlfkpfabqeb`^sb^q%1/)4-&^kacfkaqebBue^rpqbaSovhri^karpbqebXAfp`fmifkfkdOlaZqldbqqebj_^`hqltlohyyRy1/504yyNFAy.01//yyLyyAy
@?^`hqlqebMfqyKyRpbXObfkplcqebF`bj^tJ^qof^o`eZ^kaabcb^qEviapjbbqT^o_b^ofkqebmfq^ob^yyRy1/166yyNFAy.01/1yyLyyAy
@AbcbkafkdVlroQfqibyKyAbcb^q3Sf`qloflrp@e^iibkdbopfk?orkkefia^oSfii^dbyyNFAy.01/0yyLyyAy

QJ^fkq^fkfkdAfp`fmifkbyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyNFAy.01//yyLyyAy
QQeb>_boo^qflkpJrpqAfbyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyNFAy.01/2yyLyyAy
Q?^`hqlqebMfqyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyNFAy.01/1yyLyyAy
QAbcbkafkdVlroQfqibyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyNFAy.01/0yyLyyAy

CArkKfccbibjyKyCivqlArkKfccbibj%31)3.&y
KMf`hRm0*3NrbpqyKyMf`hrm0NrbpqfkArkKfccbibjfcvlr$obCofbkaiv)2Nrbpqfcvlr$obElkloba)3Nrbpqfcvlr$obObsbobaqebkqf`hqefp_lu%30+/)3/+6&)%31+/)31+1&)%31+2)26+3&)%30+2)26+5&)%32)3-+6&)%34+2)3-&y
>Elq^ka@liayKyCglok$p>ksfi%30+/)3/+6&yyNFAy./65.yyAy
>?iltfkdElafo$pElokyKyElafo$pElok%31+/)31+1&yNFAy./644yyAy
>MlifpefkdqebEbijyKyElafo$pEbij%31+2)26+3&yyNFAy.0--3yyAy
>PmvErkqboyLyyKyElklobaObmrq^qflkqlQebPlkplcElafolkiv*ColpqtlodAbkjlqebo%30+2)26+5&yyNFAy./661yyAy
>QeorpqfkdElafo$pPmb^oyLyyKyElklobaObmrq^qflkqlQebPlkplcElafolkiv*Elafo$pPmb^o%32)3-+6&yyNFAy.0--0yyAy
>Cbbafkd>okdofjyLyyKyObsbobaObmrq^qflkqlQebPlkplcElafolkiv*>okdofjqebFkp^qf^_ib%34+2)3-&yyNFAy.0-13yyAy

@Cbbafkd>okdofjyLyyKyFcvlre^sbmbqpmrqqebjfkqlm^ppfsbjlab+DlqlqebS^iibvlc>k`fbkqTfkqbop%24)31&^karpbX>okdofj$pQllqeZlkqebOl^jfkdGlojrkd^oqebob+Lk`bqebve^sb_b`ljbafpbj_lafba)vlrjrpqcfdeqqebjrkqfiqebv^obtb^hbkbayyRy1/441yyNFAy.0-13yyAy
@PmvErkqboyLyyKyDllrqql%24+/)31&^karpbXBqebob^iTlod$pC^kdZcliiltqebtlicqe^q^mmb^opqebkhfiiqebAt^osbptebkebpm^tkpqebj)fcvlrdolrmtfqelqebomi^vbopalfkdqefpnrbpqfqtfii_bJR@EC>PQBOyyRy1/146yyNFAy./661yyAy
@MlifpefkdqebEbijyKyBkqboEf_bok^i@^sboktbpqlcArkKfccbibj%22+3)3/+6&^ka`liib`q2rkfqplcXSfp`lrpLfiZcoljqebSfp`lrpLfipqebob+yyNFAy.0--3yyAy
@QeorpqfkdElafo$pPmb^oyRy1/436yyLyyKyFcvlr$obqovfkdqefpcloqeb.pqqfjbq^hblcc^iivlro^ojlofk`^pbvlrafb+RpbXPmb^olcElafoZlk^TfiaTvoj+Lk`bjlrkqbahbbmmobppfkd.^ka0)tebkvlrdbqqeb$`i^tt^okfkd$mobpp/qlaladbqebmobpp1+Fkqebkbuqme^pb)mobpp.rkqfivlrpq^`h^qib^pq.-$Mov$^ka^qqbjmqqlhfiifq_vmobppfkd/)fcfqc^fiphbbmmobppfkd.rkqfi/_b`ljbp^s^fi^_ib^d^fk+yyNFAy.0--0yyAy
@?iltfkdElafo$pElokyKyHfii2KfccbibjClobc^qebop^ka2ObpqibppColpq_lok^qQerkaboc^ii%4.)2/&QebkrpbXElafo$pElokZlsboqebfo`lompbpyyRy1/.31yyNFAy./644yyAy
H?ofqqibObsbk^kqyKyHfii?ofqqibObsbk^kq^ka`liib`q3XBppbk`blcF`bZ%4-)26&yyIy1//133y
@Elq^ka@liayKyillhcloQfkv_i^`hqefkdptfqepjlhb`ljfkdrmcoljqebj%41)3/&Qebv^obb^pfboqlpmlqfkqebpklt+Dbqkb^olkb)rpb^kXBppbk`blcF`bZ)qebkofdeq*`if`hillqqebjbq^ip`o^m+Alqefprkqfivlre^sb2yyRy1//13yyNFAy./65.yyAy

QElq^ka@liayKyCglok$p>ksfi%30+/)3/+6&yyNFAy./65.yyAy
Q?iltfkdElafo$pElokyKyElafo$pElok%31+/)31+1&yNFAy./644yyAy
QMlifpefkdqebEbijyKyElafo$pEbij%31+2)26+3&yyNFAy.0--3yyAy
QPmvErkqboyLyyKyColpqtlodAbkjlqebo%30+2)26+5&yyNFAy./661yyAy
QQeorpqfkdElafo$pPmb^oyLyyKyElafo$pPmb^o%32)3-+6&yyNFAy.0--0yyAy
QCbbafkd>okdofjyLyyKyObsbobaObmrq^qflkqlQebPlkplcElafolkiv*>okdofjqebFkp^qf^_ib%34+2)3-&yyNFAy.0-13yyAy

KTebkVlroOb^`eElklobayKyQebcliiltfkdnrbpqobnrfobpElklobaobmrq^qflkqlqebPlkplcElafo)vlrlkive^sbqlalqebpbnrbpqlk`byyNFAy.0--.y
>O^fpfkdElafo$pPmb^oyKyElklobaObmrq^qflkqlQebPlkplcElafolkiv*Qf`hqefpnrbpqfcvlre^sb^iob^avalkbfq)vlre^sbqlalqefpnrbpq_bclobob`bfsfkd^kbta^fiv^qelkloba)IlobhbbmboO^kasfo%31+5)26+.&yyNFAy.0--.y
@O^fpfkdElafo$pPmb^oyKyBkqboqeb`^sb^q%22+6)31+3&^ka`liib`q0XBsbocolpqPe^oapZcoljqebabmqeplcEf_bok^i@^sbok^ka0XPqlf`J^jjlqeEfabpZcoljqebPqlf`J^jjlqepfkqebS^iibvlc>k`fbkqTfkqbop+yyNFAy.0--.y
QO^fpfkdElafo$pPmb^oyKyIlobhbbmboO^kasfo%31+5)26+.&yyNFAy.0--.y

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
