DugisGuideViewer:RegisterGuide("The Wyrmrest_Accord (750 +Rep)", nil, "Alliance", "D", function()
return [[
AAA

CQo^kpfqrpPefbiayKyCivqlQo^kpfqrpPefbiafk?lob^kQrkao^y

>Ao^hbErkqyKyO^bilo^pw%00+0)01+2&yyNFAy..61-yyWy?lob^kQrkao^yyAy
@Ao^hbErkqyKyDlqlqebs^iibv^q%/4)0-&^kaillhclo^KburpAo^hbrm^_lsbqebkrpbXO^bilo^pw$pPmb^oZyyRy022-3yyNFAy..61-yyWy?lob^kQrkao^yyAy
QAo^hbErkqyKyO^bilo^pw%00+0)01+2&yyNFAy..61-yyWy?lob^kQrkao^yyAy

>>`bpEfdeyKy@lo^pqo^pw^%/6+2)/1+5&yyNFAy.01.1yyWy?lob^kQrkao^yyAy
@>`bpEfdeyKyHfiiqebCbiptlokBifqbrpfkdqebAo^hb_vrpfkdqefp^_fifqv`lj_l.).).).).)2)0KLQB7Tebkvlrmobpp0vlrkbbaqlpbic*`^pqloq^odbqvlropbicyyNFAy.01.1yyWy?lob^kQrkao^yyAy
Q>`bpEfdeyKy@lo^pqo^pw^%/6+2)/1+5&yyNFAy.01.1yyWy?lob^kQrkao^yyAy

CTvojobpqQbjmibyKyCivqlTvojobpqQbjmibfkAo^dlk_ifdeqy
>AbcbkafkdTvojobpqQbjmibyKyIloa>co^p^pqo^pw%26+/)21+0&yyNFAy./04/yyWyAo^dlk_ifdeqyyAy
@AbcbkafkdTvojobpqQbjmibyKyHfii0>wrobAo^dlkp)2>wrobAo^hbp^kaAbpq^_fifwbqeb>wrobAo^dlkpeofkb%22+2)33&)qebifqqibao^dlkplkivkbba.Cfob_^ii^ka.Fjjli^qbqlhfii)tefibqeb_fdao^dlkptfiikbba1*2Cfob_^ii^ka^kFjjli^qbqlafbyyNFAy./04/yyWyAo^dlk_ifdeqyyAy
QAbcbkafkdTvojobpqQbjmibyKyIloa>co^p^pqo^pw%26+/)21+0&yyNFAy./04/yyWyAo^dlk_ifdeqyyAy

KDrfab@ljmibqb
]]
end)
