DugisGuideViewer:RegisterGuide("The Kalu'ak (1500 +Rep)", nil, "Alliance", "D", function()
return [[
AAA

C?lob^kQrkao^yKyCivqlQ^rkh^$ibSfii^db%Eloab&loS^if^k`bHbbm%>iif^k`b&fk?lob^kQrkao^y
>Mobm^ofkdcloqebTlopqyKyRq^fh%31)12+5&yyNFAy..612yyWy?lob^kQrkao^yyAy
@Mobm^ofkdcloqebTlopqyKy@liib`q5uXH^ph^i^PrmmifbpZ^olrka%40+1)2.+6&yyNFAy..612yyWy?lob^kQrkao^yyAy
QMobm^ofkdcloqebTlopqyKyRq^fh%31)12+5&yyNFAy..612yyWy?lob^kQrkao^yyAy

CJl^$HfE^o_loyKyCivqlJl^$HfE^o_lofkAo^dlk_ifdeqy
>Mi^kkfkdcloqebCrqrobyKyQo^mmboJ^r$f%15+0)41+0&yyNFAy..63-yyWyAo^dlk_ifdeqyyAy
@Mi^kkfkdcloqebCrqrobyKyDlqlqeb`^jmpfqb^olrka%12+4)3.+3&^ka`liib`q./uXPkltc^iiDi^abMrmZyyNFAy..63-yyWyAo^dlk_ifdeqyyAy
QMi^kkfkdcloqebCrqrobyKyQo^mmboJ^r$f%15+0)41+0&yyNFAy..63-yyWyAo^dlk_ifdeqyyAy

CH^j^dr^yKyCivqlH^j^dr^fkEltifkdCgloay
>QebT^vqlEfpEb^oq+++yKy>krkf^n%/1+3)25+5&yyNFAy..14/yyWyEltifkdCgloayyAy
K@liib`q^CfpeyKyRpbqebX>krkf^n$pKbqZlk^p`ellilccfpe^olrka%00)4.+5&yyRy1-613yyIy01./4yyWyEltifkdCgloay
@QebT^vqlEfpEb^oq+++yKyA^j^db^?rii%0.+6)41+.&pifdeqiv%_brk^ojbafcvlrjbibb^qq^`hefqpqlle^oa&^kaj^hbqebj`e^pbvlrqlqeb@lt)lk`bvlrob^`eqeb`ltrpbXQ^pqvObbcCfpeZlkqeb?riiyyRy01./4yyNFAy..14/yyWyEltifkdCgloayyAy
QQebT^vqlEfpEb^oq+++yKy>krkf^n%/1+3)25+5&yyNFAy..14/yyWyEltifkdCgloayyAy

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
