DugisGuideViewer:RegisterGuide("Zul'Drak (76+ Pre-Quests)", nil, "Alliance", "D", function()
return [[
AAA

CQeb>odbkqPq^kayKyCivqlQeb>odbkqPq^kafkWri$Ao^h%06+2)33+6&yyNFAy./41-y
>M^o^`erqbpcloqeb>odbkq@orp^abyKy@ljj^kaboC^ipq^^s%06+2)33+6&yyNFAy./41-y
@M^o^`erqbpcloqeb>odbkq@orp^abyNFAy./41-yyRy063.2yyKyCfkaqeb>odbkqcfdeqboplrqfkqeb`lroqv^oa%04+4)32+6&^kaqlppqebjX@orp^aboM^o^`erqbpZy

QM^o^`erqbpcloqeb>odbkq@orp^abyKy@ljj^kaboC^ipq^^s%06+2)33+6&yyNFAy./41-y
>M^$QoliiyKy@ljj^kaboHrkw%1-+0)33+3&yyNFAy./263y

>I^_TlohyKy>i`ebjfpqCfkhibpqbfk%02+.)2/+/&yyNFAy./224y
@I^_TlohyNFAy./224yyKyXJraavJfobJ^ddlqZ)XTfqeboba?^qtfkdZ)^kaX@efiibaPbombkqJr`rpZ^obfkqebolljqlvlroibcq^pvlr`ljbfkql>i`ebjfpqCfkhbipqbfk$pollj%02)20&+QebX>j_bopbbaZfpfkqebolljqlqebofdeq%02)2.+2&y
QI^_TlohyKy>i`ebjfpqCfkhibpqbfk%02+.)2/+/&yyNFAy./224y

>PljbqefkdcloqebM^fkyKy@^mq^fk?o^kalk%15+5)45+6&yyNFAy./264y
@PljbqefkdcloqebM^fkyNFAy./264yyKy@liib`q2XJ^qrobT^qbo*MlmmvZtbpq^qqebAo^h$Plqo^Cfbiap%11+.)46+3&y
QPljbqefkdcloqebM^fkyKy@^mq^fk?o^kalk%15+5)45+6&yyNFAy./264y

>QeoltfkdAltkyKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./265y
@QeoltfkdAltkyNFAy./265yyRy05241yyKyGrpqqlqebkloqetbpq%21+5)4.+-&+Cfkaqebifqqibpfkhelibp^kaqlppvlroXEfdeFjm^`qDobk^abZfkfqy
QQeoltfkdAltkyKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./265y

>@ob^qrob@ljcloqpyKy@^mq^fkDolkabi%15+.)30+5&yyNFAy./266y
@@ob^qrob@ljcloqpyNFAy./266yyKy@liib`q/-mfb`bplcXAb^aQeloktllaZclrka^ii^olrkaqebt^qbop^q%11+5)3/+4&y
Q@ob^qrob@ljcloqpyKy@^mq^fkDolkabi%15+.)30+5&yyNFAy./266y
QM^$QoliiyKy@ljj^kaboHrkw%1-+0)33+3&yyNFAy./263y

KDrfab@ljmibqb
]]
end)
