DugisGuideViewer:RegisterGuide("Zul'Drak (76+ Dailies)", nil, "Alliance", "D", function()
return [[
AAA

KQfjbaA^fiv+++yKyQebWri$Ao^hA^fifbp^obqfjbanrbpqp)^kbmf`civfkdjlrkqtfiiebim^ilq)_b`^rpbfcvlrcfkfpe^iiqebq^phfkqfjbvlrtfiidbq^kbuqo^.5d^kao^kaljobt^oay
CQeb>odbkqPq^kayKyCivqlQeb>odbkqPq^kafkWri$Ao^hy
>QoliiM^qoliyKy@ljj^kaboHrkw%1-+0)33+3&yyNFAy./2-.yyAy

>QoliiM^qoli7Qeb>i`ebjfpq$p>mmobkqf`byKy?bpqqlpq^oqtfqeqeb>i`ebjfpq%02+.)2/+.&q^phcfopqpfk`bfcfqq^hbvlrqllilkdql`ljmibqbvlr`^k^_^kalkqebnrbpq^kaobpq^oqqebqfjbocloqeb_lkrpobt^oayyNFAy./21.yyAy
@QoliiM^qoli7Qeb>i`ebjfpq$p>mmobkqf`byKyFqfp_bpqqlobcboqlqeb`eb^qpebbq^s^fi^_iblkifkb)vlrkbbaqlcfkaqeb`loob`qfkdobafbkq^pc^pq^pvlr`^kyyNFAy./21.yyAy
QQoliiM^qoli7Qeb>i`ebjfpq$p>mmobkqf`byKy>i`ebjfpqCfkhibpqbfk%02+.)2/+.&yyNFAy./21.yyAy

KMf`hrm@^mq^fkDolkabiQ^phyKyMf`hrm@^mq^fkDolkabi%15+.)30+5&nrbpq^kaqf`hql`lkqfkrbqlqebkbuqpqbmy
>QoliiM^qoli7@lriak$q@^obIbppyLyyKy@^mq^fkDolkabi%15+.)30+5&yyNFAy./261yyAy
>QoliiM^qoli7@ob^qrob@ljcloqpyLyyKy@^mq^fkDolkabi%15+.)30+5&yyNFAy./252yyAy
>QoliiM^qoli7Te^qav^T^kq)^Jba^i<yLyyKy@^mq^fkDolkabi%15+.)30+5&yyNFAy./2.6yyAy

@QoliiM^qoli7@lriak$q@^obIbppyLyyKyHfii4JlppvO^jm^dbopfkAo^h$>d^i%11)30+6&)%10+4)24+3&yyNFAy./261yyAy
@QoliiM^qoli7@ob^qrob@ljcloqpyLyyKy@liib`q/-uXAb^aQeloktllaZ^olrka%11)30+6&)%10+4)24+3&)%11+5)35+6&yyNFAy./252yyAy
@QoliiM^qoli7Te^qav^T^kq)^Jba^i<yLyyKy@liib`q4uXAo^hh^ofJba^iiflkZcoljqebAo^hh^of@lompbp^olrka%10)26&yyNFAy./2.6yyAy

QQoliiM^qoli7@lriak$q@^obIbppyLyyKy@^mq^fkDolkabi%15+.)30+5&yyNFAy./261yyAy
QQoliiM^qoli7@ob^qrob@ljcloqpyLyyKy@^mq^fkDolkabi%15+.)30+5&yyNFAy./252yyAy
QQoliiM^qoli7Te^qav^T^kq)^Jba^i<yLyyKy@^mq^fkDolkabi%15+.)30+5&yyNFAy./2.6yyAy

KMf`hrm@^mq^fkOrmboqQ^phyKyMf`hrm@^mq^fkOrmboq%25+.)4/+2&nrbpq^kaqf`hql`lkqfkrbqlqebkbuqpqbmy
>QoliiM^qoli7AlkbqlAb^qeyLyyKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./235yyAy
>QoliiM^qoli7QeoltfkdAltkyLyyKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./26.yyAy
>QoliiM^qoli7Fkqbpqfk^iCloqfqrabyLyyKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./2-6yyAy

@QoliiM^qoli7AlkbqlAb^qeyLyyKyRpbXFk`fkbo^qfkdLfiZlkqeb>odbkqCllqj^k@lompbp%2/)4/&yyRy05223yyNFAy./235yyAy
@QoliiM^qoli7QeoltfkdAltkyLyyKyRpbqebXEfdeFjm^`qDobk^abZlkqebKbor_f^kQrkkbip%@o^qbop&clrka^olrka%2.)34&%kbuqqlpq^fop&^ka%22)4.&yyRy05241yyNFAy./26.yyAy
@QoliiM^qoli7Fkqbpqfk^iCloqfqrabyLyyKyQ^ihql2u@orp^abOb`orfq)qebv`^k_bclrka^ii^olrka%20)40&yyNFAy./2-6yyAy

QQoliiM^qoli7AlkbqlAb^qeyLyyKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./235yyAy
QQoliiM^qoli7QeoltfkdAltkyLyyKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./26.yyAy
QQoliiM^qoli7Fkqbpqfk^iCloqfqrabyLyyKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./2-6yyAy

KMf`hrm@^mq^fk?o^kalkQ^phyKyMf`hrm@^mq^fk?o^kalk%15+5)45+6&nrbpq^kaqf`hql`lkqfkrbqlqebkbuqpqbmy
>QoliiM^qoli7@^kVlrAfdFq<yLyyKy@^mq^fk?o^kalk%15+5)45+6&yyNFAy./255yyAy
>QoliiM^qoli7EfdePq^ka^oapyLyyKy@^mq^fk?o^kalk%15+5)45+6&yyNFAy./2-/yyAy
>QoliiM^qoli7PljbqefkdcloqebM^fkyLyyKy@^mq^fk?o^kalk%15+5)45+6&yyNFAy./231yyAy

@QoliiM^qoli7@^kVlrAfdFq<yLyyKyCfkaqebAfoqJlrkap^olrka%14+2)5/+2&^karpbXPqbbiPm^abZyyRy05233yyNFAy./255yyAy
@QoliiM^qoli7EfdePq^ka^oapyLyyKyRpbqebX>odbkq@orp^ab?^kkboZ^qqebKloqe%2-+1)40+.&)B^pq%20+/)4/+0&)Plrqe%2/+2)43+3&^ob^yyRy05211yyNFAy./2-/yyAy
@QoliiM^qoli7PljbqefkdcloqebM^fkyLyyKy@liib`qqeb2uXJ^qrobT^qbo*MlmmvZ^qqebAo^h$Plqo^Cfbiap%10)43&yyNFAy./231yyAy

QQoliiM^qoli7@^kVlrAfdFq<yLyyKy@^mq^fk?o^kalk%15+5)45+6&yyNFAy./255yyAy
QQoliiM^qoli7EfdePq^ka^oapyLyyKy@^mq^fk?o^kalk%15+5)45+6&yyNFAy./2-/yyAy
QQoliiM^qoli7PljbqefkdcloqebM^fkyLyyKy@^mq^fk?o^kalk%15+5)45+6&yyNFAy./231yyAy

@QoliiM^qoliyKy@ljmibqb^ii1q^phyyNFAy./2-.yyAy
QQoliiM^qoliyKy@ljj^kaboHrkw%1-+0)33+3&yyNFAy./2-.yyAy

KDrfab@ljmibqb
]]
end)
