DugisGuideViewer:RegisterGuide("The Aldor Reputation (68+)", nil, "Horde", "E", function()
return [[
AAA

OPe^qqo^qe@fqvyKyQo^sbiqlPe^qqo^qe@fqv%25+2)1.&yyWyPe^qqo^qe@fqvyyNFAy.-/.-y
>>$a^iyKyVlr$obillhfkdclo^E^dd^oaT^oSbqbo^k%25+2)1.&)ebpelria_bc^foivb^pvqlcfkakb^oqeb`bkqbolcqeb`fqvyyWyPe^qqo^qe@fqvyyNFAy.-/.-y
Q>$a^iyKy>$a^i%21)11+2&yyWyPe^qqo^qe@fqvyyNFAy.-/.-y
>@fqvlcIfdeqyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-/..y
Q@fqvlcIfdeqyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-/..y
>>iibdf^k`bqlqeb>ialoyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-22.y
Q>iibdf^k`bqlqeb>ialoyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-22.y
>Fpe^k^eyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-221y
QFpe^k^eyKyFpe^k^e%/1+/)/6+2&yyWyPe^qqo^qe@fqvyyNFAy.-221y

>ObpqlofkdqebIfdeqyKyFpe^k^e%/1+/)/6+2&yyWyPe^qqo^qe@fqvyyNFAy.--/.y
>>@ib^kpfkdIfdeqyKyFpe^k^e%/1+/)/6+2&yyWyPe^qqo^qe@fqvyyNFAy.-1/-y
>>ppfpqBu^o`eLobifpyKySfkaf`^qloH^^k%01+6)0/+1&yyWyPe^qqo^qe@fqvyyNFAy..-05y
>>@robcloW^eif^yKyPe^$kfo%31+0).2+1&yyWyPe^qqo^qe@fqvyyNFAy.--/-y

K@liib`q^pvlrnrbpqyKyHbbm^iiqebXCbi>oj^jbkqpZ)XJ^ohlcHfi$g^babkZ)^kaXJ^ohlcP^odbo^pZcloobmqrok*fkp+y

@ObpqlofkdqebIfdeqyKyRpbqebX?ibppbaSf^iZql`ib^kpbqeb0^iq^op7Tbpq%15+.).1+2&)Kloqe%2-+3).3+2&^kaB^pq%16+/)/-+0&yyNFAy.--/.yyRy/25.4yyWyQbolhh^oClobpqy
@>@robcloW^eif^yKy?ofkdPqlkbd^wbo$p?illaqlPe^$kfofkPe^qqo^qe@fqv+%30+5)/6+1&)%36+4)0-+6&yyNFAy.--/-yyWyQbolhh^oClobpqy

QObpqlofkdqebIfdeqyKyFpe^k^e%/1+/)/6+2&yyWyPe^qqo^qe@fqvyyNFAy.--/.y
Q>@robcloW^eif^yKyPe^$kfo%31+0).2+1&yyWyPe^qqo^qe@fqvyyNFAy.--/-y

C>ob^2/yKyCivql>ob^2/%31+.)1.+.&yyNFAy.-/1.yyWyPe^qqo^qe@fqvy

Q>ppfpqBu^o`eLobifpyKyyKyBu^o`eLobifp%0/+.)31+/&yyNFAy..-05yyWyKbqebopqlojy
>Afpqo^`qflk^qJ^k^clodb?$k^^oyKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-/1.yyWyKbqebopqlojy
@Afpqo^`qflk^qJ^k^clodb?$k^^oyKyClrka^olrkaJ^k^clodb?$k^^o%/2+4)35+1&yyNFAy.-/1.yyWyKbqebopqlojy
QAfpqo^`qflk^qJ^k^clodb?$k^^oyKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-/1.yyWyKbqebopqlojy
>Jb^profkdT^omBkbodfbpyKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-0.0yyWyKbqebopqlojy
>K^^orQb`eklildvyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-/10yyWyKbqebopqlojy
>Pl`obqe^o$pPe^altyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-1-4yyWyKbqebopqlojy

@Jb^profkdT^omBkbodfbpyKyRpbqeblo_tebobqebmfmbpdlfkqlqebdolrkafkqefploabo7Kloqe%/2+6-)3-+./&)Tbpq%/.+/0)33+56&)Plrqe%/-+45)4-+366&)B^pq%/5+4-)4/+/1&yyRy/60/1yyNFAy.-0.0yyWyKbqebopqlojy
QK^^orQb`eklildvyKy?$k^^o@lkqoli@lkplib%/0+/)35+.&yyNFAy.-/10yyWyKbqebopqlojy
>?$k^^o@lkplibQo^kp`ofmqflkyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-/12yyWyKbqebopqlojy

QJb^profkdT^omBkbodfbpyKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-0.0yyWyKbqebopqlojy
Q?$k^^o@lkplibQo^kp`ofmqflkyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-/12yyWyKbqebopqlojy
>PerqqfkdAltkJ^k^clodb?$k^^oyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-/66yyWyKbqebopqlojy
@PerqqfkdAltkJ^k^clodb?$k^^oyKyHfiiLsbopbboQebobafp%/0+5)4-+2&fkpfabqebj^k^clodb)illqqebX?$k^^o>``bpp@ovpq^iZ^karpbqeb`lkplibyyIy/6033yyNFAy.-/66yyWyKbqebopqlojy
QPerqqfkdAltkJ^k^clodb?$k^^oyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-/66yyWyKbqebopqlojy
>PerqqfkdAltkJ^k^clodb@lorryKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-0/.yyWyKbqebopqlojy
>>qq^`hlkJ^k^clodb@lorryKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-/13yyWyKbqebopqlojy

@PerqqfkdAltkJ^k^clodb@lorryKyB^pqlsboqeb_ofadb%13)5.&+HfiiLsbopbboPbvi^kk^%16+-)5.+2&qebkillqqebX@lorr>``bpp@ovpq^iZ^karpbqeb`lkplibyyIy/6063yyNFAy.-0/.yyWyKbqebopqlojy
@>qq^`hlkJ^k^clodb@lorryKyHfiiqebjl_p^olrkaJ^k^clodb@lorr%15+1)5.+0&yyNFAy.-/13yyWyKbqebopqlojy

QPerqqfkdAltkJ^k^clodb@lorryKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-0/.yyWyKbqebopqlojy
>PerqqfkdAltkJ^k^clodbArolyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-0//yyWyKbqebopqlojy
Q>qq^`hlkJ^k^clodb@lorryKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-/13yyWyKbqebopqlojy
>Prkcrov?ofbcfkdpyKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-0/5yyWyKbqebopqlojy

@PerqqfkdAltkJ^k^clodbArolyKyB^pq^qJ^k^clodbArol+HfiiLsbopbbo>qe^kbi%26+6)35+0&)illqqebXArol>``bpp@ovpq^iZ^karpblk`lkplibyyIy/6064yyNFAy.-0//yyWyKbqebopqlojy
@Prkcrov?ofbcfkdpyKyHfii?ltjbk^ka@bkqroflkpcloqebJfifq^ov?ofbcfkd)@lkgrobopcloqeb>o`^kb?ofbcfkd^olrkaqebJ^k^clodb%25+-)31+-&yyNFAy.-0/5yyWyKbqebopqlojy

QPerqqfkdAltkJ^k^clodbArolyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-0//yyWyKbqebopqlojy
>PerqqfkdAltkJ^k^clodb>o^yKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-0/0yyWyKbqebopqlojy
QPrkcrov?ofbcfkdpyKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-0/5yyWyKbqebopqlojy

>Lrqpfab>ppfpq^k`byKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-10.yyWyKbqebopqlojy
QLrqpfab>ppfpq^k`byKyH^vi^^k%01+5)05+/&yyNFAy.-10.yyWyKbqebopqlojy
>>A^ohM^`qyKyH^vi^^k%01+5)05+/&yyNFAy.-05-yyWyKbqebopqlojy
@PerqqfkdAltkJ^k^clodb>o^yKyHfiiLsbopbbo>w^o^a%/3+.)06+4&)illqqebX>o^>``bpp@ovpq^iZ^karpblk`lkplibyyIy/61..yyNFAy.-0/0yyWyKbqebopqlojy
@>A^ohM^`qyKy>iiclrka^olrkaJ^k^clodb>o^%/3+2)06+3&yyNFAy.-05-yyWyKbqebopqlojy
Q>A^ohM^`qyKyH^vi^^k%01+5)05+/&yyNFAy.-05-yyWyKbqebopqlojy
>>ialoKlJlobyKyH^vi^^k%01+5)05+/&yyNFAy.-05.yyWyKbqebopqlojy

KCfopqE^iclcPl`obqe^o$pPqlkbyKyPi^vClodbj^pqboJlord%03+6)/4+3&yyIy/63/1yyNFAy.-1-4yyWyKbqebopqlojy
@Pl`obqe^o$pPe^altyKyPi^vPfiolqe%1-+6).6+0&yyNFAy.-1-4yyWyKbqebopqlojy

QPerqqfkdAltkJ^k^clodb>o^yKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-0/0yyWyKbqebopqlojy
QPl`obqe^o$pPe^altyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-1-4yyWyKbqebopqlojy
>Fpe^k^e$pEbimyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-1.-yyWyKbqebopqlojy
Q>ialoKlJlobyKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-05.yyWyKbqebopqlojy

CPe^qqo^qe@fqvyKyCivqlPe^qqo^qe@fqv%00+4)31&yyWyKbqebopqlojy

QFpe^k^e$pEbimyKyFpe^k^e%/1+/)/6+2&yyNFAy.-1.-yyWyPe^qqo^qe@fqvy
>Ab^qe_iltqlqebIbdflkyKyFpe^k^e%/1+/)/6+2&yyNFAy.-1-6yyWyPe^qqo^qe@fqvy

C>ob^2/yKyCivql>ob^2/%31+.)1.+.&yyWyPe^qqo^qe@fqvy

@Ab^qe_iltqlqebIbdflkyKyIbdflkQbibmloqbo^qqebkloqetbpqbok`lokbolcKbqebopqloj^karpbfqqlqbibmloqqlPl`obqe^o$pPb^q+Lk`bqebob)abcb^qPl`obqe^o+%/6+3).0+6&yyNFAy.-1-6yyRy/6463yyWyKbqebopqlojy
QAb^qe_iltqlqebIbdflkyKyFpe^k^e%/6+3).0+6&yyNFAy.-1-6yyWyKbqebopqlojy

CPe^altjllkS^iibvyKyCivqlPe^altjllkS^iibv%00+4)31&yyWyKbqebopqlojy
>Qeb>peqlkdrbQof_byKySfkaf`^qlo>irrjbk%3.+/)/6+/&yNFAy.-3.6yyWyPe^altjllkS^iibvy
>Q^_ibqplc?^^$ofyKy>k`elofqb@bvi^%3/+3)/5+1&yyNFAy.-235yyWyPe^altjllkS^iibvy
>H^o^_loQo^fkfkdDolrkapyKyBu^o`eLk^^i^%3.+/)/6+/&yyNFAy.-254yyWyPe^altjllkS^iibvy

@Qeb>peqlkdrbQof_byKy>qqebOrfkplc?^^$of%23+6)02+3&yyNFAy.-3.6yyWyPe^altjllkS^iibvy
@Q^_ibqplc?^^$ofyKy>qqebOrfkplc?^^$of%23+6)02+3&yyNFAy.-235yyWyPe^altjllkS^iibvy
@H^o^_loQo^fkfkdDolrkapyKyFkpfabqeb?i^`hQbjmib)q^hbqebcfopqofdeq%35+-)2-+-&+HfiiAbjlkErkqboPrmmif`^kqp^kaFkfqf^qbp)qovql`^q`eqebj^cqbo^arbitebkqebv^obiltlkEM)qebvifkhifhbj^a+>iplt^q`elrqcloqebbifqbqe^qt^kabopqeorqeb^ob^+yyNFAy.-254yyWyPe^altjllkS^iibvy

QQeb>peqlkdrbQof_byKySfkaf`^qlo>irrjbk%3.+/)/6+/&yyNFAy.-3.6yyWyPe^altjllkS^iibvy
>Ob`i^fjfkdElivDolrkapyKySfkaf`^qlo>irrjbk%3.+/)/6+/&yyNFAy.-5.3yyWyPe^altjllkS^iibvy
>LolkrqebBiaboyKy>k`elofqb@bvi^%3/+3)/5+1&yyNFAy.-24.yyWyPe^altjllkS^iibvy
QQ^_ibqplc?^^$ofyKy>k`elofqb@bvi^%3/+3)/5+1&yyNFAy.-235yyWyPe^altjllkS^iibvy
QH^o^_loQo^fkfkdDolrkapyKyBu^o`eLk^^i^%3.+/)/6+/&yyNFAy.-254yyWyPe^altjllkS^iibvy
>>Kb`bpp^ovAfpqo^`qflkyKyBu^o`eLk^^i^%3.+/)/6+/&yyNFAy.-304yyWyPe^altjllkS^iibvy

@>Kb`bpp^ovAfpqo^`qflkyKyHfiiPrjjlkbop^kaT^oil`hp^olrka%4.+.)2.+0&rkqfiqebp`oliiaolmp)qebkrpbfqlk>w^ilqe%4-+-)2.+1&+Alklqhfiiqebjl_pkb^oefj)loeb$ii`ljb^cqbovlr+yyRy0-5..yyNFAy.-304yyWyPe^altjllkS^iibvy
@Ob`i^fjfkdElivDolrkapyKyPi^v5Pe^altjllkPi^vbop)5Pe^altjllk@elpbk^ka1Pe^altjllkA^ohtb^sbop%36+/)05+/&yyNFAy.-5.3yyWyPe^altjllkS^iibvy
@LolkrqebBiaboyKyVlr`^kcfkaLolkrqebBiabo^q%24+/)00+.&fkpfabqeborfkpyyNFAy.-24.yyWyPe^altjllkS^iibvy

QLolkrqebBiaboyKy>k`elofqb@bvi^%3/+3)/5+1&yyNFAy.-24.yyWyPe^altjllkS^iibvy
>Qeb>peqlkdrb@loormqlopyKy>k`elofqb@bvi^%3/+3)/5+1&yyNFAy.-241yyWyPe^altjllkS^iibvy
QOb`i^fjfkdElivDolrkapyKySfkaf`^qlo>irrjbk%3.+/)/6+/&yyNFAy.-5.3yyWyPe^altjllkS^iibvy
Q>Kb`bpp^ovAfpqo^`qflkyKyBu^o`eLk^^i^%3.+/)/6+/&yyNFAy.-304yyWyPe^altjllkS^iibvy
>>iqorfpyKyBu^o`eLk^^i^%3.+/)/6+/&yyNFAy.-31-yyWyPe^altjllkS^iibvy

@Qeb>peqlkdrb@loormqlopyKyHfiiE^^irj%24+-)40+-&)Bvhbkbk%2.+-)2/+-&)Rvi^or%15+-)06+-&^kaI^h^^k%16+-)/0+-&yyNFAy.-241yyWyPe^altjllkS^iibvy
QQeb>peqlkdrb@loormqlopyKy>k`elofqb@bvi^%3/+3)/5+1&yyNFAy.-241yyWyPe^altjllkS^iibvy
>QebT^oabk$p@^dbyKy>k`elofqb@bvi^%3/+3)/5+1&yyNFAy.-242yyWyPe^altjllkS^iibvy
QQebT^oabk$p@^dbyKyP^klor%24+0)16+3&)fkqebelibyyNFAy.-242yyWyPe^altjllkS^iibvy

CK^do^kayKyCivqlK^do^ka%30+0)0-+1&yyNFAy.-31.yyWyPe^altjllkS^iibvy

Q>iqorfpyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-31-yyWyK^do^kay
>>d^fkpqqebIbdflkyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-31.yyWyK^do^kay
>>d^fkpqqebFiifa^ofyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-335yyWyK^do^kay
>>d^fkpq>iiLaapyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-336yyWyK^do^kay

OW^kd^oj^opeyKyQo^sbiqlW^kd^oj^ope%.3+0)1-+4&yyWyW^kd^oj^opey

@>d^fkpq>iiLaapyKyQ^hbqebFj_rbaPfisboPmb^o^karpbfq^qMloq^i@ib^ofkdkb^oJ^opeifdeqI^hb%.3+0)1-+4&^kapi^vUbibqeyyRy0-520yyNFAy.-336yyWyW^kd^oj^opey

CQebPqlojpmfobyKyCivqlQebPqlojpmfob)Kbqebopqloj%1.+0)/6&yyWyPe^altjllkS^iibvy

@>d^fkpqqebIbdflkyKyL_q^fkCobpeivAo^tk?illacolj^To^qeMofbpqbpp^qClodb?^pb7Dbebkk^)qebkpmfiifqlkqebdolrka^kapi^vqeb>s^q^olcP^qe^i+%06+/)/-+2&yyNFAy.-31.yyWyKbqebopqlojy

CPe^altjllkSfii^dbyKyCivqlPe^altjllkSfii^db%12+0)01+6&yyWyKbqebopqlojyyNFAy.-313y

@>d^fkpqqebFiifa^ofyKyPi^vIlqeolp^qFiifa^ofMlfkq%/4+4)2-+6&yyNFAy.-335yyWyPe^altjllkS^iibvy

CK^do^kayKyCivqlK^do^ka%0-+0)/6+/&yyWyPe^altjllkS^iibvy

Q>d^fkpqqebIbdflkyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-31.yyWyK^do^kay
Q>d^fkpqqebFiifa^ofyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-335yyWyK^do^kay
Q>d^fkpq>iiLaapyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-336yyWyK^do^kay
>Fiifa^k$pMrmfiyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-313yyWyK^do^kay
@Fiifa^k$pMrmfiyKyIfpqbkql>iqorfpqebPrccbobo$ppqlov%/4+1)10+.&yyNFAy.-313yyWyK^do^kay
QFiifa^k$pMrmfiyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-313yyWyK^do^kay
>Qeb?llhlcCbiK^jbpyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-316yyWyK^do^kay

OQbolhh^oClobpqyKyQo^sbiqlQbolhh^oClobpq%06+3)36+.&yyWyQbolhh^oClobpqyyNFAy.-36.y

@Qeb?llhlcCbiK^jbpyKyL_q^fkqeb?llhlcCbiK^jbpcolj?i^`heb^oqqebFk`fqbofkqebPe^altI^_vofkqe%06+0)31+1&yyNFAy.-316yyWyQbolhh^oClobpqy

OK^do^kayKyQo^sbiqlK^do^ka%/4+1)10+.&yyNFAy.-36.yyWyK^do^kay

QQeb?llhlcCbiK^jbpyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-316yyWyK^do^kay
>Obqrokqlqeb>ialoyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-32-yyWyK^do^kay

CPe^altjllkS^iibvyKyCivqlPe^altjllkS^iibv%24+/)02+0&yyNFAy.-36/yyWyK^do^kay

QObqrokqlqeb>ialoyKyBu^o`eLk^^i^%3.+/)/6+/&yyNFAy.-32-yyWyPe^altjllkS^iibvy
>S^obafpJrpq?bPqlmmbayKyBu^o`eLk^^i^%3.+/)/6+/&yyNFAy.-32.yyWyPe^altjllkS^iibvy
HS^obafpyKy%4/)20+1&+RpbqebX?llhlcCbiK^jbpZtebkebJbq^jlomelpfpyyRy0-521yyNFAy.-32.yyNLyS^obafppi^fk7.,.yyWyPe^altjllkS^iibvy
HKbqe^obiyKy%35+1)20+3&yyNFAy.-32.yyNLyKbqe^obipi^fk7.,.yyWyPe^altjllkS^iibvy
HQebo^pyKy%4/+/)15+1&yyNFAy.-32.yyNLyQebo^ppi^fk7.,.yyWyPe^altjllkS^iibvy
@S^obafpJrpq?bPqlmmbayKyPi^v>i^kafbk%36+3)20+5&yyNFAy.-32.yyWyPe^altjllkS^iibvy
QS^obafpJrpq?bPqlmmbayKyBu^o`eLk^^i^%3.+/)/6+/&yyNFAy.-32.yyWyPe^altjllkS^iibvy

Q>@ib^kpfkdIfdeqyKyFpe^k^e%/1+/)/6+2&)fcvlre^sb^XCbi>oj^jbkqZyyWyPe^qqo^qe@fqvyyNFAy.-1/-y

KQrok*fkpyKy@lkqfkrbdofkafkdjl_p^`liib`qfkdXCbi>oj^jbkqpZ)XJ^ohlcHfi$g^babkZ)^kaXJ^ohlcP^odbo^pZcmoobmqrok*fkp+Drfab@ljmibqby

]]
end)
