DugisGuideViewer:RegisterGuide("The Argent Crusade Reputation (80+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabtfiidllsbo^iiqebnrbpqpkbbabaqldbqqeb>odbkq@e^jmflk>`efbsbjbkq%Bu^iqbatfqe>odbkqA^tk^ka>odbkq@orp^ab+Lk`b^iiqebnrbpqp^obalkbclo^m^oqf`ri^oc^`qflk)qebkfpgrpqdofkafkdlrqqebobmb^q^_ibarkdblkp,qrok*fkpqldbqqlBu^iqba+Qefpdrfab^pprjbpqe^qvlr^obibsbi5-)_rqqefp`^k_balkb^qibsbi44^ptbii)fqtfiigrpqq^hbjr`eilkdboql`ljmibqb+y
KIltIbsbiNrbpqpyKyJ^hbprobvlr^obqo^hfkdiltibsbinrbpqpqlj^hbfqb^pfboqlpbbqebnrbpqpdfsbop+y

eA^i^o^kyKyJ^hbA^i^o^kvlroeljb%32+3)0/+/&Dbqqfkdql^kacoljqebpbil`^qflktfii_bb^pfbocoljA^i^o^k+yyWyA^i^o^ky

OAo^dlk_ifdeqyKyQo^sbiqlAo^dlk_ifdeq%54+/)24+1&yyNFAy./21/yyWyAo^dlk_ifdeqy
>Qeb@^iiLcQeb@orp^abyKyQfia^A^o^qe^k%54+/)24+1&yyNFAy./21/yyWyAo^dlk_ifdeqy
QQeb@^iiLcQeb@orp^abyKy@orp^aboS^irp%51+-)/3+.&yyNFAy./21/yyWyAo^dlk_ifdeqy
>Qeb@ib^kpfkdLcGfkqe^$h^i^oyKy@orp^aboS^irp%51+-)/3+.&yyNFAy./212yyWyAo^dlk_ifdeqy
@Qeb@ib^kpfkdLcGfkqe^$h^i^oyKyPi^v.2Gfkqe^$h^i^oP`lrodb%53+6)/-+4&+yyNFAy./212yyWyAo^dlk_ifdeqy
QQeb@ib^kpfkdLcGfkqe^$h^i^oyKy@orp^aboS^irp%51+-)/3+.&yyNFAy./212yyWyAo^dlk_ifdeqy

OWri$Ao^hyKyQo^sbhqlWri$Ao^h%0/+-)42+3&yyNFAy./526yyWyWri$Ao^hy
>QefpGrpqFk7CfobPqfiiElqyKyBiaboPe^j^kJlhv%0/+-)42+3&yyNFAy./526yyWyWri$Ao^hy
>FkPb^o`eLc>kptbopyKy@orp^aboIloaI^kqfkd^%0/+.)42+5&yyNFAy./6-/yyWyWri$Ao^hy
>T^kqba7O^dbj^kb$pCifmmboyKyT^kqbaPfdk%0/+/)42+4&yyNFAy./524yyWyWri$Ao^hy
QFkPb^o`eLc>kptbopyKyLoabopColjAo^hror%01+6)50+6&yyNFAy./6-/yyWyWri$Ao^hy
>LoabopColjAo^hroryKyLoabopColjAo^hror%01+6)50+6&yyNFAy./550yyWyWri$Ao^hy
@QefpGrpqFk7CfobPqfiiElqyNFAy./526yyRy1..0.yyKyRpbqebXO^db`i^tCfobBuqfkdrfpeboZqlmrqlrqqeberqp^qO^db`i^tAbk%0/+6)5/+.&yyWyWri$Ao^hy
@T^kqba7O^dbj^kb$pCifmmboyKyOb`lsboO^dbj^kb$pCifmmbo%05+4)52+.&yyNFAy./524yyWyWri$Ao^hy
QT^kqba7O^dbj^kb$pCifmmboyKy@efbcO^db`i^t%0/+/)42+4&yyNFAy./524yyWyWri$Ao^hy
QQefpGrpqFk7CfobPqfiiElqyKyBiaboPe^j^kJlhv%0/+-)42+3&yyNFAy./526yyWyWri$Ao^hy
QLoabopColjAo^hroryKy@orp^aboIloaI^kqfkd^%0/+.)42+5&yyNFAy./550yyWyWri$Ao^hy
>@orp^aboClot^oa@^jmyKy@orp^aboIloaI^kqfkd^%0/+.)42+5&yyNFAy./561yyWyWri$Ao^hy
Q@orp^aboClot^oa@^jmyKy@orp^aboJ^`Hbii^o%/2+0)31+-&yyNFAy./561yyWyWri$Ao^hy
>Qe^q$pTe^qCofbkap>obClo+++yKy@orp^aboJ^`Hbii^o%/2+0)31+-&yyNFAy./6-0yyWyWri$Ao^hy
>J^hfkdPljbqefkdLrqLcKlqefkdyKyBkdfkbboObba%/2+0)30+6&yyNFAy./6-.yyWyWri$Ao^hy
>>Dob^qPqloj>mmol^`ebpyKyDvjbo%.6+5)23+2&yyNFAy./6./yyWyWri$Ao^hy
>IfdeqTlk$qDo^kqJbSbkdb^k`byKyDboh%.4+3)24+3&yyNFAy./6-1yyWyWri$Ao^hy
KCfka?rooyNFAy./6-0yyNLy?rooclrka7.,.yyKy>_fqcroqeboqlqebtbpq%.2+3)26+2&yyWyWri$Ao^hy
@J^hfkdPljbqefkdLrqLcKlqefkdyNFAy./6-.yyKyP`^qqboba^olrkaQevoj$pBka^olrka%.4+3)3-+0&yyWyWri$Ao^hy
@Qe^q$pTe^qCofbkap>obClo+++yNFAy./6-0yyKyCfka@orp^aboA^od^qeqlqebkloqeb^pqfkqeborfkp^qA^od^qe$pAbjfpb%/1+4)2.+2&yyWyWri$Ao^hy
QQe^q$pTe^qCofbkap>obClo+++yKy@orp^aboJ^`Hbii^o%/2+0)31+-&yyNFAy./6-0yyWyWri$Ao^hy
QJ^hfkdPljbqefkdLrqLcKlqefkdyKyBkdfkbboObba%/2+0)30+6&yyNFAy./6-.yyWyWri$Ao^hy
Q>Dob^qPqloj>mmol^`ebpyKyBkdfkbboObba%/2+0)30+6&yyNFAy./6./yyWyWri$Ao^hy
>Dvjbo$pP^is^qflkyKyBkdfkbboObba%/2+0)30+6&yyNFAy./6.1yyWyWri$Ao^hy
@Dvjbo$pP^is^qflkyNFAy./6.1yyKyCfka^kahfii?^kpebbPlri`i^fjbopcil^qfkd^olrka%/0+-)3-+6&)^kaF`bqlr`ebaB^oqeo^dboptef`eproolrkaB_lkT^q`e%.1+.)40+5&yyWyWri$Ao^hy
cQebB_lkT^q`eyKy?^kbcifdeq%.1+.)40+3&yyNFAy./30-yyWyWri$Ao^hy
>Hf`hfk$K^pp^kaQ^hfk$J^kbpyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./30-yyWyWri$Ao^hy
@Hf`hfk$K^pp^kaQ^hfk$J^kbpyNFAy./30-yyRy05326yyKyHfiiqoliip^olrka%.6+5)4.+/&)qebkrpbXPqbc^k$pPqbbiQlba?llqZcloK^ppql`liib`qe^fop^jmibpyyWyWri$Ao^hy
QHf`hfk$K^pp^kaQ^hfk$J^kbpyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./30-yyWyWri$Ao^hy
>Q^hfkd^Pq^kayKy?illaolpbA^qro^%.1+0)41+-&yyNFAy./462yyWyWri$Ao^hy

QDvjbo$pP^is^qflkyKyBkdfkbboObba%/2+0)30+6&yyNFAy./6.1yyWyWri$Ao^hy
>LroLkivElmbyKyBkdfkbboObba%/2+0)30+6&yyNFAy./6.3yyWyWri$Ao^hy
@IfdeqTlk$qDo^kqJbSbkdb^k`byNFAy./6-1yyKyHfiiS^odrip^olrka%.5+2)23+6&yyWyWri$Ao^hy
QIfdeqTlk$qDo^kqJbSbkdb^k`byKyDboh%.4+3)24+3&yyNFAy./6-1yyWyWri$Ao^hy
@LroLkivElmbyNFAy./6.3yyKyRpbqebXGrj_lPb^clofrj@e^odbZlkqeb`^db%/-+-)23+3&yyRy1.2-4yyWyWri$Ao^hy
QLroLkivElmbyKyDvjbo%.6+5)23+2&yyNFAy./6.3yyWyWri$Ao^hy
>QebPqlojHfkd$pSbkdb^k`byKyDvjbo%.6+5)23+2&yyNFAy./6.6yyWyWri$Ao^hy
@QebPqlojHfkd$pSbkdb^k`byNFAy./6.6yyKyQ^ihqlDvjbo%.6+5)23+2&tebkvlr$obob^av+Eb^akloqeb^pqqlqebObifnr^ovlcM^fk%/5+3)13+5&^kahfii>id^oqeb@elpbk)qebkplrqeqlqebpq^fop%0.+3)3/+6&^kahfiiMofk`bK^s^ofrp+Qeovjtfiipm^tktebkqebmofk`bfpab^a+Fcvlrkbbaeb^iqe%vlr$iidbq^t^okfkd&cfka^pqloj`ilra)q^odbqfq)^karpbqebmf`hrm_rqqlklkvlro^`qflk_^o+Lk`bqebk^jbajl_p^obab^a)eb^aql@orp^aboClot^oa@^jm%/2+0)30+6&^kacfkfpelcc^kvp`lrodbvlrkbba+Fcvlr$obe^sfkdqolr_ibmf`hfkdrmpqloj`ilraprpbqeb^lbql`ib^oqeb^ob^cfopqyyWyWri$Ao^hy
QQebPqlojHfkd$pSbkdb^k`byKy@orp^aboJ^`Hbii^o%/2+0)31+-&yyNFAy./6.6yyWyWri$Ao^hy

QQ^hfkd^Pq^kayKy@ljj^kaboC^ipq^^s%06+2)33+6&yyNFAy./462yyWyWri$Ao^hy
>AbcbkaqebPq^kayKy@ljj^kaboC^ipq^^s%06+2)33+6&yyNFAy./2-0yyWyWri$Ao^hy
>M^o^`erqbpcloqeb>odbkq@orp^abyKy@ljj^kaboC^ipq^^s%06+2)33+6&yyNFAy./41-yyWyWri$Ao^hy

cQeb>odbkqPq^kayKyDroof`%1.+2)31+2&yyNFAy./263yyWyWri$Ao^hy

@M^o^`erqbpcloqeb>odbkq@orp^abyNFAy./41-yyRy063.2yyKyCfkaqeb>odbkqcfdeqboplrqfkqeb`lroqv^oa%04+4)32+6&^kaqlppqebjqebX@orp^aboM^o^`erqbpZyyWyWri$Ao^hy
@AbcbkaqebPq^kayNFAy./2-0yyKyEbimqeb>odbkqcfdeqbophfiiqebp`lrodblrqfkqeb`lroqv^oa%04+4)32+6&yyWyWri$Ao^hy

QAbcbkaqebPq^kayKy@ljj^kaboC^ipq^^s%06+2)33+6&yyNFAy./2-0yyWyWri$Ao^hy
QM^o^`erqbpcloqeb>odbkq@orp^abyKy@ljj^kaboC^ipq^^s%06+2)33+6&yyNFAy./41-yyWyWri$Ao^hy
>M^$QoliiyKy@ljj^kaboHrkw%1-+0)33+3&yyNFAy./263yyWyWri$Ao^hy
>KbtLoabopcloPbodb^kqPq^`he^jjboyKy@ljj^kaboHrkw%1-+0)33+3&yyNFAy./2-2yyWyWri$Ao^hy

QKbtLoabopcloPbodb^kqPq^`he^jjboyKyPbodb^kqPq^`he^jjbo%1-+2)15+/&yyNFAy./2-2yyWyWri$Ao^hy
>>odbkq@orp^ab)Tb>obIb^sfkdyKyPbodb^kqPq^`he^jjbo%1-+2)15+/&yyNFAy./2-1yyWyWri$Ao^hy
>JlmmfkdRmyKy@lomlo^iJ^d^%1-+1)15+/&yyNFAy./2-5yyWyWri$Ao^hy
@>odbkq@orp^ab)Tb>obIb^sfkdyNFAy./2-1yyKyQ^ihqlqeb>odbkqcfdeqbop^olrka%1-+1)13+6&yyWyWri$Ao^hy
@JlmmfkdRmyNFAy./2-5yyKyHfiiqebCliiltboplcPpbo^qrp^olrka%1-+1)13+6&yyWyWri$Ao^hy
Q>odbkq@orp^ab)Tb>obIb^sfkdyKyPbodb^kqPq^`he^jjbo%1-+2)15+/&yyNFAy./2-1yyWyWri$Ao^hy
QJlmmfkdRmyKy@lomlo^iJ^d^%1-+1)15+/&yyNFAy./2-5yyWyWri$Ao^hy

>I^_TlohyKy>i`ebjfpqCfkhibpqbfk%02+.)2/+/&yyNFAy./224yyWyWri$Ao^hy
@I^_TlohyNFAy./224yyKyJraavJfobJ^ddlq)Tfqeboba?^qtfkd)^ka@efiibaPbombkqJr`rp^obclrkafkqebolljqlvlroibcq^pvlr`ljbfkql>i`ebjfpqCfkhibpqbfk$pollj%02)20&+Qeb>j_bopbbafpfkqebolljqlqebofdeq%02)2.&yyWyWri$Ao^hy
QI^_TlohyKy>i`ebjfpqCfkhibpqbfk%02+.)2/+/&yyNFAy./224yyWyWri$Ao^hy
>PfmelkfkdqebPmfofqpyKy@^mq^fk>ok^qe%02+3)2/+/&yyNFAy./466yyWyWri$Ao^hy
@PfmelkfkdqebPmfofqpyNFAy./466yyKyClrka^qqebMlliplcWe^$Gfk%02+-)3-+6&+Vlr$ob^cqboqebkbrqo^ijl_pebob)klqqeb^ddobppfsblkbpyyWyWri$Ao^hy
QPfmelkfkdqebPmfofqpyKy@^mq^fk>ok^qe%02+3)2/+/&yyNFAy./466yyWyWri$Ao^hy
>Pql`hfkdqebPebisbpyKy@^mq^fk>ok^qe%02+3)2/+/&yyNFAy./3-6yyWyWri$Ao^hy
>@ifmmfkdQebfoTfkdpyKy@^mq^fk>ok^qe%02+3)2/+/&yyNFAy./3.-yyWyWri$Ao^hy
@@ifmmfkdQebfoTfkdpyNFAy./3.-yyKyHfiiWri$Ao^h?^qp^olrka%02+6)21+1&yyWyWri$Ao^hy
@Pql`hfkdqebPebisbpyNFAy./3-6yyKyHfiiQo^mallo@o^tibop^olrka%02+6)21+1&yyWyWri$Ao^hy
QPql`hfkdqebPebisbpyKy@^mq^fk>ok^qe%02+3)2/+/&yyNFAy./3-6yyWyWri$Ao^hy
Q@ifmmfkdQebfoTfkdpyKy@^mq^fk>ok^qe%02+3)2/+/&yyNFAy./3.-yyWyWri$Ao^hy

>QebAo^hh^ofAlKlqKbbaT^qboBibjbkq^ipyKyPr_*Ifbrqbk^kqG^u%1-+/)35+6&yyNFAy./23/yyWyWri$Ao^hy
>PljbqefkdcloqebM^fkyKy@^mq^fk?o^kalk%15+5)45+6&yyNFAy./264yyWyWri$Ao^hy
@QebAo^hh^ofAlKlqKbbaT^qboBibjbkq^ipyNFAy./23/yyKyHfii.-Ao^hh^ofT^qbo?fkabop)tbpq^qqebAo^h$Plqo^Cfbiap%11+.)46+3&yyWyWri$Ao^hy
@PljbqefkdcloqebM^fkyNFAy./264yyKy@liib`q2XJ^qrobT^qbo*MlmmfbpZ)tbpq^qqebAo^h$Plqo^Cfbiap%11+.)46+3&yyWyWri$Ao^hy
QPljbqefkdcloqebM^fkyKy@^mq^fk?o^kalk%15+5)45+6&yyNFAy./264yyWyWri$Ao^hy
>QeoltfkdAltkyKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./265yyWyWri$Ao^hy
>Ib^sbKlLkb?befkayKyAo+Oldbop%25+3)4/+2&yyNFAy./2./yyWyWri$Ao^hy

@QeoltfkdAltkyNFAy./265yyRy05241yyKyGrpqqlqebkloqetbpq%21+5)42+2&+Cfkaqebifqqibpfkhelibp^kaqlppvlroXEfdeFjm^`qDobk^abZfkfqyyWyWri$Ao^hy
@Ib^sbKlLkb?befkayNFAy./2./yyRy0500-yyKyCfka@orp^aboGlk^qe^k%2-+4)36+6&)@orp^aboGlpbmefkb%16+1)41+4&^ka@orp^aboI^jllc%20+3)42+-&+RpbqebX@orp^abo$p?^ka^dbZlkqebj^kaorkqebj_^`hlkb^q^qfjb)vlr`^kjlrkqrmcloqefpyyWyWri$Ao^hy
QIb^sbKlLkb?befkayKyAo+Oldbop%25+3)4/+2&yyNFAy./2./yyWyWri$Ao^hy
QQeoltfkdAltkyKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./265yyWyWri$Ao^hy
>@l`llkbayKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./3-3yyWyWri$Ao^hy
>Ab^qeqlqebKb`olj^dfyKyPbodb^kqJllkpe^oa%25+.)4/+.&yyNFAy./22/yyWyWri$Ao^hy
>PhfjjboPmfkkbobqpyKyPmb`f^ifpq@ldtebbi%25+/)4/+.&yyNFAy./220yyWyWri$Ao^hy

@@l`llkbayNFAy./3-3yyKyGrpqqlqebkloqetbpq%21+5)42+2&)^qq^`hqebKbor_f^k@l`llkpqllmbkqebj)vlrtfiidbqbfqebo^cofbkaivloelpqfibjl_yyWyWri$Ao^hy
@PhfjjboPmfkkbobqpyNFAy./220yyKyHfiiE^qe$^oPhfjjbo^qHlio^j^p%24+-)45+5&yyWyWri$Ao^hy
@Ab^qeqlqebKb`olj^dfyNFAy./22/yyKyE^qe$^oKb`olj^drp^ob_bpqclrkafkqebc^iibkwfddro^q^q%3-+/)42+2&yyWyWri$Ao^hy

Q@l`llkbayKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./3-3yyWyWri$Ao^hy
QAb^qeqlqebKb`olj^dfyKyPbodb^kqJllkpe^oa%25+.)4/+.&yyNFAy./22/yyWyWri$Ao^hy
>J^i^pqeb@loormqboyKyPbodb^kqJllkpe^oa%25+.)4/+.&yyNFAy./221yyWyWri$Ao^hy
>MrobBsfiyKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./251yyWyWri$Ao^hy
QPhfjjboPmfkkbobqpyKyPmb`f^ifpq@ldtebbi%25+/)4/+.&yyNFAy./220yyWyWri$Ao^hy
>@o^pebaPmo^vboyKyPmb`f^ifpq@ldtebbi%25+/)4/+.&yyNFAy./250yyWyWri$Ao^hy
@@o^pebaPmo^vboyNFAy./250yyKyPlrqetbpq)kb^o@^mq^fk?o^kalk$p`^jm%15+6)42+2&yyWyWri$Ao^hy
Q@o^pebaPmo^vboyKyPmb`f^ifpq@ldtebbi%25+/)4/+.&yyNFAy./250yyWyWri$Ao^hy
>>Q^kdibaPhbfkyKyPmb`f^ifpq@ldtebbi%25+/)4/+.&yyNFAy./222yyWyWri$Ao^hy
@>Q^kdibaPhbfkyNFAy./222yyRy052.2yyKyRpbqebXQ^kdibaPhbfkQeoltboZlkqebMi^drbPmo^vbop^olrka%23)5-&yyWyWri$Ao^hy
@MrobBsfiyNFAy./251yyKyFkpfabHlio^j^p%3.+0)45+4&+Illhclodobbkpqlkbp^olrkaqebcillop^kat^iipyyWyWri$Ao^hy
@J^i^pqeb@loormqboyNFAy./221yyKyI^_biba^pDolrm)_rqfpplil^_ib+Eb^armqebpq^fopkb^oqebbkqo^k`b%3-+5)5-+0&+J^i^pqeb@loormqbofp^qqebsbovqlmyyWyWri$Ao^hy

Q>Q^kdibaPhbfkyKyPmb`f^ifpq@ldtebbi%25+/)4/+.&yyNFAy./222yyWyWri$Ao^hy
QJ^i^pqeb@loormqboyKyPbodb^kqJllkpe^oa%25+.)4/+.&yyNFAy./221yyWyWri$Ao^hy

QQebAo^hh^ofAlKlqKbbaT^qboBibjbkq^ipyKyPr_*Ifbrqbk^kqG^u%1-+/)35+6&yyNFAy./23/yyWyWri$Ao^hy
QMrobBsfiyKyBfqofdd%1-+5)33+4&yyNFAy./251yyWyWri$Ao^hy
>DirqqlklrpIrohbopyKy>mmobkqf`bMbpqibmlq%1.+0)32+.&yyNFAy./2/4yyWyWri$Ao^hy
>@ob^qrob@ljcloqpyKy@^mq^fkDolkabi%15+.)30+5&yyNFAy./266yyWyWri$Ao^hy
@DirqqlklrpIrohbopyNFAy./2/4yyRy0505-yyKyMf`hrm/2XWri$Ao^hO^qpZfkqlq^i^kaqeolt2o^qp^qb^`e_^pfifphqlm^`fcvqebj^ka`liib`qqebX?^pfifph@ovpq^ipZqe^qvlrkbba%11+5)3/+4&yyWyWri$Ao^hy
@@ob^qrob@ljcloqpyNFAy./266yyKyClrka^ii^olrkaqebt^qbop^q%11+5)3/+4&yyWyWri$Ao^hy
Q@ob^qrob@ljcloqpyKy@^mq^fkDolkabi%15+.)30+5&yyNFAy./266yyWyWri$Ao^hy
QM^$QoliiyKy@ljj^kaboHrkw%1-+0)33+3&yyNFAy./263yyWyWri$Ao^hy
QDirqqlklrpIrohbopyKy>i`ebjfpqCfkhibpqbfk%02+.)2/+/&yyNFAy./2/4yyWyWri$Ao^hy

OQeb>odbkqS^kdr^oayKyCivqlQeb>odbkqS^kdr^oaFkF`b`oltk^q%54)42&yyNFAy.0-03yyWyF`b`oltky
>Elklo>_lsb>iiBipbyKyEfdeiloaQfoflkCloaofkd%54+2)42+6&yyNFAy.0-03yyWyF`b`oltky
QElklo>_lsb>iiBipbyKy@orp^ab@ljj^kaboBkq^of%54+.)42+6&yyNFAy.0-03yyWyF`b`oltky
>P`lrodbQ^`qf`pyKy@orp^ab@ljj^kaboBkq^of%54+.)42+6&yyNFAy.0--5yyWyF`b`oltky
>@rofkdQebFk`ro^_ibyKyC^qeboDrpq^s%53+6)43+3&yyNFAy.0-1-yyWyF`b`oltky
>AbcbkafkdQebS^kdr^oayKy@orp^aboIloaA^iclop%53+.)42+5&yyNFAy.0-06yyWyF`b`oltky

@AbcbkafkdQebS^kdr^oayKyHfii.2ClodlqqbkAbmqepKbor_f^kp^olrka%51+2)42+1&yyNFAy.0-06yyWyF`b`oltky
@@rofkdQebFk`ro^_ibyKy@liib`q.-uXClodlqqbkAbmqepSbkljP^`ZcoljqebPmfabop^olrka%51+2)42+1&yyNFAy.0-1-yyWyF`b`oltky
@P`lrodbQ^`qf`pyKyCobb5Tb__ba@orp^abop^olrka%50)4.&yyNFAy.0--5yyWyF`b`oltky
QP`lrodbQ^`qf`pyKy@orp^ab@ljj^kaboBkq^of%54+.)42+6&yyNFAy.0--5yyWyF`b`oltky

Q@rofkdQebFk`ro^_ibyKyC^qeboDrpq^s%53+6)43+3&yyNFAy.0-1-yyWyF`b`oltky
QAbcbkafkdQebS^kdr^oayKy@orp^aboIloaA^iclop%53+.)42+5&yyNFAy.0-06yyWyF`b`oltky
>FcQebob>obProsfslop+++yKy@orp^ab@ljj^kaboBkq^of%54+.)42+6&yyNFAy.0-11yyWyF`b`oltky
QFcQebob>obProsfslop+++yKyMbkrj_ofrp%54)46&yyNFAy.0-11yyWyF`b`oltky
>FkqlQebTfiaDobbkVlkaboyKyMbkrj_ofrp%54)46&yyNFAy.0-12yyWyF`b`oltky
@FkqlQebTfiaDobbkVlkaboyKyJlrkq^phvq^ilkfkcolkqlcvlr^kadlkloqe*tbpqqlP`lrodbelijb%46)33&^kado^_^@^mqroba@orp^abo^kaqebk_ofkdefj_^`hqlqebS^kdr^oa%^qqeb?lkcfobtebob^iiqebqbkqp^ob^q&)vlr`^klkiv`^oovlkb^q^qfjb)plvlrtfiie^sbqlj^hb0qofmp+yyNFAy.0-12yyWyF`b`oltky
QFkqlQebTfiaDobbkVlkaboyKyEfdeiloaQfoflkCloaofkd%54+2)42+6&yyNFAy.0-12yyWyF`b`oltky
>>@liaColkq>mmol^`ebpyKyEfdeiloaQfoflkCloaofkd%54+2)42+6&yyNFAy.0-4-yyWyF`b`oltky
Q>@liaColkq>mmol^`ebpyKyPfbdbj^pqboCbwwfh%52+4)43&yyNFAy.0-4-yyWyF`b`oltky
>QebI^pqIfkbLcAbcbkpbyKyPfbdbj^pqboCbwwfh%52+4)43&yyNFAy.0-53yyWyF`b`oltky
@QebI^pqIfkbLcAbcbkpbyKyCivrmqlqeb>odbkq@^kklk%52+0)42+5&^karpbfqqlhfii.--p`lrodbpyyNFAy.0-53yyWyF`b`oltky
QQebI^pqIfkbLcAbcbkpbyKyPfbdbj^pqboCbwwfh%52+4)43&yyNFAy.0-53yyWyF`b`oltky
>Lk`bJlobRkqlQeb?ob^`e)EbolyKyEfdeiloaQfoflkCloaofkd%54+2)42+6&yyNFAy.0.-1yyWyF`b`oltky

QLk`bJlobRkqlQeb?ob^`e)EbolyKyQebB_lkT^q`ebo%50+.)4/+6&yyNFAy.0.-1yyWyF`b`oltky
>QebMrodfkdLcP`lrodbelijbyKyQebB_lkT^q`ebo%50+.)4/+6&yyNFAy.0..5yyWyF`b`oltky
>QebP`lrodbpqlkbyKyQebB_lkT^q`ebo%50+.)4/+6&yyNFAy.0.//yyWyF`b`oltky
>QebPqlkbQe^qPq^oqba>ObslirqflkyKy@orp^ab>o`efqb`qPfi^p%50+.)40&yyNFAy.0.0-yyWyF`b`oltky
>Fq@lriaHfiiRp>iiyKy@orp^abBkdfkbboPmfqwm^qof`h%50)40&yyNFAy.0.02yyWyF`b`oltky
>QebObpqibppAb^ayKyC^qeboDrpq^s%5/+6)4/+5&yyNFAy.0..-yyWyF`b`oltky

O@ovpq^iplkdClobpqyKyQo^sbiql@ovpq^iplkdClobpq%32)31&yyNFAy.0./2yyWy@ovpq^iplkdClobpqy
@Fq@lriaHfiiRp>iiyKyObqofbsb5mfb`bplcX@ovpq^iifwbaBkbodvZaolmmba_vqebRk_lrkaKM@pfk@ovpq^iplkdClobpq%32)31&yyNFAy.0.02yyWy@ovpq^iplkdClobpqy
@QebPqlkbQe^qPq^oqba>ObslirqflkyKyObqofbsb.-Qorkhplc@ovpq^iifkbEb^oqtlla%32)32&^ka.-mfb`bplc>k`fbkqBisbkJ^plkov%53)3.&yyNFAy.0.0-yyWy@ovpq^iplkdClobpqy
QFq@lriaHfiiRp>iiyKy@orp^abBkdfkbboPmfqwm^qof`h%50)40&yyNFAy.0.02yyWyF`b`oltky
QQebPqlkbQe^qPq^oqba>ObslirqflkyKy@orp^ab>o`efqb`qPfi^p%50+.)40&yyNFAy.0.0-yyWyF`b`oltky

@QebMrodfkdLcP`lrodbelijbyKyHfiiqebKM@p^olrka%44)35&^ka%46)31&rpbqebXElivT^qboZlkqeb`lompbpyyRy10.20yyNFAy.0..5yyWyF`b`oltky
@QebObpqibppAb^ayKyHfiiqebOb^kfj^qba@orp^abop%44)32&^karpbqebXElivT^qboZlkqeb`lompbpyyRy10.20yyNFAy.0..-yyWyF`b`oltky
@QebP`lrodbpqlkbyKyVlr`^k`ljmibqbqefp^q@orp^aboplcSfoqrb^q%5/+5)4.+2&^kagrpqefqqebjlkpqbop^cbtqfjbp^kaibqqebKM@pebimvlrhfiiqebjqebkillqqebXP`lrodbpqlkbZyyNFAy.0.//yyWyF`b`oltky

QQebMrodfkdLcP`lrodbelijbyKyQebB_lkT^q`ebo%50+.)4/+6&yyNFAy.0..5yyWyF`b`oltky
QQebObpqibppAb^ayKyC^qeboDrpq^s%5/+6)4/+5&yyNFAy.0..-yyWyF`b`oltky
QQebP`lrodbpqlkbyKyQebB_lkT^q`ebo%50+.)4/+6&yyNFAy.0.//yyWyF`b`oltky

>Qeb>foPq^kapPqfiiyKyQebB_lkT^q`ebo%50+.)4/+6&yyNFAy.0./2yyWyF`b`oltky
@Qeb>foPq^kapPqfiiyKyCfkaqebKM@^kapq^ka^_lrq.-v^oap^t^vcoljqebj^karpbqebXT^oEloklc>`eborpZ)pq^v^ifsbrkqfiqebAb^qehkfdeq^oofsbp+P^io^k^u7%44)3.&)Rkabohfkd7%43)20&)EfdeMofbpqV^qe$^jlk7%46)3-&yyRy10/-3yyNFAy.0./2yyWyF`b`oltky

QQeb>foPq^kapPqfiiyKyQebB_lkT^q`ebo%50+.)4/+6&yyNFAy.0./2yyWyF`b`oltky
>FkqlQebColwbkEb^oqLcKloqeobkayKyC^qeboDrpq^s%5/+6)4/+5&yyNFAy.0.06yyWyF`b`oltky
QFkqlQebColwbkEb^oqLcKloqeobkayKyEfdeiloaQfoflkCloaofkd%53)42+5&yyNFAy.0.06yyWyF`b`oltky
>Qeb?^qqibClo@orp^abop$Mfkk^`ibyKyEfdeiloaQfoflkCloaofkd%53)42+5&yyNFAy.0.1.yyWyF`b`oltky
@Qeb?^qqibClo@orp^abop$Mfkk^`ibyKyDlql@orp^abop$Mfkk^`ib%5-)4/&^karpbqebX?ibppba?^kkbolcqeb@orp^abZ^qlmqebMfiblc@orp^aboPhriip+Abcbkaqeb_^kkbo^d^fkpqP`lrodb^qq^`hrkqfiqebi^ka^qlmqebmfkk^`ibfpp^k`qfcfbayyRy10/10yyNFAy.0.1.yyWyF`b`oltky
QQeb?^qqibClo@orp^abop$Mfkk^`ibyKyC^qeboDrpq^s%5/+6)4/+5&yyNFAy.0.1.yyWyF`b`oltky
>Qeb@orp^abop$Mfkk^`ibyKyC^qeboDrpq^s%5/+6)4/+5&yyNFAy.0.24yyWyF`b`oltky
QQeb@orp^abop$Mfkk^`ibyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyNFAy.0.24yyWyF`b`oltky
>>Q^iblcS^iloyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyNFAy.0-35yyWyF`b`oltky
>Lodofj$pE^jjboyKyT^oiloaElohPqolkd_olt%46+2)4/+4&yyNFAy.0//1yyWyF`b`oltky
Q>Q^iblcS^iloyKy@orp^abo?ofabk_o^a%46+5)0-+6&yyNFAy.0-35yyWyF`b`oltky
>>EbolObj^fkpyKy@orp^abo?ofabk_o^a%46+5)0-+6&yyNFAy.0-4/yyWyF`b`oltky
Q>EbolObj^fkpyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyNFAy.0-4/yyWyF`b`oltky
>QebHbbmbo$pC^sloyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyNFAy.0-40yyWyF`b`oltky
KDbqMloq^i+++yKyQ^ihql>o`eAorfaIfiif^kao^%54)44&^kaobnrbpq^Jllkdi^abmloq^iyyNFAy.0-40yyWyF`b`oltky
QQebHbbmbo$pC^sloyKyHbbmboObjrilp%03)1.+2&yyNFAy.0-40yyWyJllkdi^aby
>ElmbTfqefkqebBjbo^iaKfdeqj^obyNFAy.0-41yyKyHbbmboObjrilp%03)1.+2&yyWyJllkdi^aby
@ElmbTfqefkqebBjbo^iaKfdeqj^obyNFAy.0-41yyKyDbq0XBjbo^ia>`lokpZqebvillhifhbifqqib_oltk_^iipqe^qpm^ohib+Clrkalkqebdolrka^olrka%01)1.&yyWyJllkdi^aby
QElmbTfqefkqebBjbo^iaKfdeqj^obyNFAy.0-41yyKyOfdeq`if`hlkqebpibbmfkd_rccql^kaqrokfkqlHbbmboObjrilp%03)1.+2&yyWyJllkdi^aby
>Qeb?llklcObjrilpyNFAy.0-42yyKyHbbmboObjrilp%03)1.+2&yyWyJllkdi^aby
QQeb?llklcObjrilpyKyDlqeolrdeqebmloq^i^kadlql@orp^abo?ofabk_o^a%46+5)0-+6&yyNFAy.0-42yyWyF`b`oltky
>QfjbVbqObj^fkpyNFAy.0-43yyKy@orp^abo?ofabk_o^a%46+5)0-+6&yyWyF`b`oltky
QQfjbVbqObj^fkpyNFAy.0-43yyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyWyF`b`oltky
>QebQlr`elc^k>pmb`qyNFAy.0-44yyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyWyF`b`oltky

OTvojobpqQbjmibyKyCivqlTvojobpqQbjmibfkAo^dlk_ifdeq%26+5)21+3&yyNFAy.0-45yyWyAo^dlk_ifdeqy
QQebQlr`elc^k>pmb`qyNFAy.0-44yyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyWyAo^dlk_ifdeqy
>A^eif^$pQb^opyNFAy.0-45yyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyWyAo^dlk_ifdeqy
@A^eif^$pQb^opyNFAy.0-45yyKyT^fqqfiikb^oqebbkalcqebt^sbqebor_vt^q`ebotfiikrhbqebdolrkatfqe^ilqlccfob^kaXA^eif^$pQb^opZtfiipm^tk^olrka%2-)2/&^ka%10)2.&yyWyAo^dlk_ifdeqy
QA^eif^$pQb^opyNFAy.0-45yyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyWyAo^dlk_ifdeqy
>Qeb?llklc>ibupqo^pw^yNFAy.0-46yyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyWyAo^dlk_ifdeqy

QQeb?llklc>ibupqo^pw^yNFAy.0-46yyKy@orp^abo?ofabk_o^a%46+5)0-+6&yyWyF`b`oltky
>ElmbVbqObj^fkpyNFAy.0-5-yyKy@orp^abo?ofabk_o^a%46+5)0-+6&yyWyF`b`oltky
QElmbVbqObj^fkpyNFAy.0-5-yyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyWyF`b`oltky
>QebTfiilcqebK^^oryNFAy.0-5.yyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyWyF`b`oltky
OPe^qqo^qe@fqvyKyDlqeolrdeqebmloq^iqlPe^qqo^qe@fqvyyNFAy.0-5/yyWyF`b`oltky
QQebTfiilcqebK^^oryNFAy.0-5.yyKy>$a^i%20)12&yyWyPe^qqo^qe@fqvy
>Qeb?llklc>$a^iyNFAy.0-5/yyKy>$a^i%20)12&yyWyPe^qqo^qe@fqvy
EA^i^o^kyRy3615y
QQeb?llklc>$a^iyNFAy.0-5/yyKy@orp^abo?ofabk_o^a%46+5)0-+6&yyWyF`b`oltky
>IfdeqTfqefkqebA^ohkbppyNFAy.0-50yyKy?ofabk_o^a$pMlppbppflkp%46+5)0-+6&yyWyF`b`oltky
QIfdeqTfqefkqebA^ohkbppyNFAy.0-50yyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyWyF`b`oltky

OLodofj$pE^jjboyKyQefpfpqebEloabPefmqe^qcifbp^olrkaF`b`oltk%33)00&)%36+2)/4+1&)%34+1)2/+2&yyNFAy.0//5yyWyF`b`oltky
QLodofj$pE^jjboyKyPhv*Ob^sboHloj?i^`hp`^o*eb$p^_l^oaLodofj$pE^jjbo)lkblcqebcivfkd^fopefmpfkqebobdflkyyNFAy.0//1yyWyF`b`oltky

>G^ddbaPe^oapyKyQebfqbjXG^ddbaPe^oaZpq^oqpnrbpq*aolmmba_vPmfhbaDelrip^olrka%0/)4-&yyRy10/1/yyNFAy.0.03yyWyF`b`oltky
>F$jKlqAb^aVbqyKyC^qeboH^j^olp%0.+5)3.+5&yyNFAy.0//6yyWyF`b`oltky
@F$jKlqAb^aVbqyKyBp`loqC^qeboH^j^olpqlp^cbqvyyNFAy.0//6yyWyF`b`oltky
@G^ddbaPe^oapyNFAy.0.03yyKy@liib`q.-XG^ddbaPe^oapZaolmmba_vPmfhbaDelrip^olrka%0/)4-&+Vlrlkivkbba6jloblcqebpb)^pqebfqbjtef`epq^oqbaqebnrbpq^ipl`lrkqp^plkbyyWyF`b`oltky
QG^ddbaPe^oapyNFAy.0.03yyKy@orp^aboLi^hfkP^fkofqe%02+2)33+2&yyWyF`b`oltky

>F$jPjbiqfkd+++PjbiqfkdyNFAy.0.05yyKy@orp^aboLi^hfkP^fkofqe%02+2)33+2&yyWyF`b`oltky
>QebOrkbpjfqeplcJ^ivhofppyNFAy.0.1-yyKy@orp^aboLi^hfkP^fkofqe%02+2)33+2&yyWyF`b`oltky

@F$jPjbiqfkd+++PjbiqfkdyKyPq^kaafob`qivfkcolkqlclkblcqebcrok^`bp%25)4.&^karpbqebX?^dlcG^ddbaPe^oapZyyRy10/56yyNFAy.0.05yyWyF`b`oltky
@QebOrkbpjfqeplcJ^ivhofppyNFAy.0.1-yyKyDbq2XOrkbaP^olkfqbMi^qbpZaolmmba_vPhbibq^iOrkbpjfqep^olrka%26)40+5&yyWyF`b`oltky
QF$jPjbiqfkd+++PjbiqfkdyKy@orp^aboLi^hfkP^fkofqe%02+2)33+2&yyRy10/56yyNFAy.0.05yyWyF`b`oltky
QQebOrkbpjfqeplcJ^ivhofppyNFAy.0.1-yyKy@orp^aboLi^hfkP^fkofqe%02+2)33+2&yyWyF`b`oltky
>?vCfob?bMrodbayNFAy.0/..yyKy@orp^aboLi^hfkP^fkofqe%02+2)33+2&yyWyF`b`oltky
@?vCfob?bMrodbayNFAy.0/..yyKy?rok4Cbpqbofkd@lompbprpfkdXLi^hfk$pQlo`eZ^qqebP^k`qrjlcOb^kfj^qflk%01)36&yyRy102/1yyWyF`b`oltky
Q?vCfob?bMrodbayNFAy.0/..yyKy@orp^aboLi^hfkP^fkofqe%02+2)33+2&yyWyF`b`oltky

OLodofj$pE^jjboyKyQefpfpqebEloabPefmqe^qcifbp^olrkaF`b`oltk%33)00&)%36+2)/4+1&)%34+1)2/+2&yyNFAy.00-1yyWyF`b`oltky
QF$jKlqAb^aVbqyKy?olqeboHbiq^klkLodofj$pE^jjboyyNFAy.0//6yyWyF`b`oltky

>Qfoflk$pD^j_fqyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyNFAy.0031yyWyF`b`oltky
H@riqfpq>`livqbyKyHfii^@riqfpq>`livqb^q%12)45&qll_q^fk^X@riqfpq>`livqb$pEllaZyyIy11451yyNFAy.0031yyWyF`b`oltky
@Qfoflk$pD^j_fqyKyRpbqebX@riqfpq>`livqb$pEllaZ^kaq^ihqlQfoflk^q%11+1)43+/&^kaqebbsbkqtfiipq^oqyyRy11451yyNFAy.0031yyWyF`b`oltky
QQfoflk$pD^j_fqyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyNFAy.0031yyWyF`b`oltky

C>odbkqQlrok^jbkqyKy%41)/1&yyWyF`b`oltky
K>odbkqQlrok^jbkqyKyAlqeb>odbkqQlrok^jbkqNrbpq@e^fkclrkafkqebA^fifbppb`qflk+y
KA^fifbpyKyDofkalrqqebobpqlcqebobm_valfkd>odbkq@orp^abA^fifbp^ka>odbkqQlrok^jbkqA^fifbp+Drfab@ljmibqb+y

]]
end)
