DugisGuideViewer:RegisterGuide("The Argent Dawn Reputation (55+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabtfiidllsbo^iiqebnrbpqpkbbabaqldbqqeb>odbkq@e^jmflk>`efbsbjbkq%Bu^iqbatfqe>odbkqA^tk^ka>odbkq@orp^ab+Lk`b^iiqebnrbpqp^obalkbclo^m^oqf`ri^oc^`qflk)qebkfpgrpqdofkafkdlrqqebobmb^q^_ibarkdblkp,qrok*fkpqldbqqlBu^iqba+Qefpdrfab^pprjbpqe^qvlr^obibsbi5-)_rqqefp`^k_balkb^qibsbi44^ptbii)fqtfiigrpqq^hbjr`eilkdboql`ljmibqb+y
KIltIbsbiNrbpqpyKyJ^hbprobvlr^obqo^hfkdiltibsbinrbpqpqlj^hbfqb^pfboqlpbbqebnrbpqpdfsbop+y

eA^i^o^kyKyJ^hbA^i^o^kvlroeljb%32+3)0/+/&Dbqqfkdql^kacoljqebpbil`^qflktfii_bb^pfbocoljA^i^o^k+yyWyA^i^o^ky
OLodofjj^oyKyQ^hbmloq^i%22+/)/2+3&fkA^i^o^kqlLodofjj^oyyWyA^i^o^ky

CWlo^j$d^oLrqmlpqyKyAlo^p%12+0)31&yyWyLodofjj^oy
O?i^`hc^qeljAbbmpyKy%.1+.).1+5&yyWy>pebks^iby
>?i^`hc^qeljSfii^fkvyKy>odbkqDr^oaQe^biofa+EbfpfkqebFkpq^k`b)vlr`^kcfkaefjqlqebplrqetbpqlcDe^jll*o^yyNFAy323.y
@?i^`hc^qeljSfii^fkvyKyHfiiQtfifdeqIloaHbiofp^kaillqefpeb^a+Ebfpcroqebofkqlqebfkpq^k`b+yyNFAy323.y
OWlo^j$d^oLrqmlpqyKyOrk_^`hqlWlo^j$d^oLrqmlpq%..+4)01+2&+yyWy>pebks^iby
CQerkabo?irccyKy>kaorh%./+/)00+6&yyWy>pebks^iby
Q?i^`hc^qeljSfii^fkvyKy?^pe^k^Orkbqlqbj%4-+6)00+4&yyNFAy323.yyWyQerkabo?irccy
CPe^altmobvSfii^dbyKyQ^i%14)2-&yyWyQerkabo?irccy
>P`bmqoblcIfdeqyKy>wlob>ia^jloq%05+6)/4+/&yyNFAy241.yyWyAbpli^`by
@P`bmqoblcIfdeqyKyDbqqebP`bmqoblcIfdeqcolj^?rokfkd?i^abPbbo%22+/)0-+.&)fkqebqltbo+yyNFAy241.yyWyAbpli^`by
QP`bmqoblcIfdeqyKy>wlob>ia^jloq%05+6)/4+/&yyNFAy241.yyWyAbpli^`by
>?llhlcqeb>k`fbkqpyKy>wlob>ia^jloq%05+6)/4+/&yyNFAy3-/4yyWyAbpli^`by
@?llhlcqeb>k`fbkqpyKyRpbqebXDbjlcqebPbombkqZlkqebPbombkqPq^qrb%/5+.)3+1&lkO^k^wg^oFpib+yyNFAy3-/4yyRy.2433yyWyAbpli^`by
Q?llhlcqeb>k`fbkqpyKy>wlob>ia^jloq%05+6)/4+/&yyNFAy3-/4yyWyAbpli^`by

CBsboillhyKyQe^ilk%/.+3)41&yyWyAbpli^`by
cBsboillhyKyVrdobh%3-+2)03+1&yyWyTfkqbopmofkdy
>QebBsboillhObmloqyKyDobdloDobvpqlkb%3.+0)05+6&yyNFAy3-/6yyWyTfkqbopmofkdy
>ArhbKf`eli^pWsbobkelccyKyDobdloDobvpqlkb%3.+0)05+6&yyNFAy3-0-yyWyTfkqbopmofkdy
>PfpqboM^jbi^yKyGbppf`^Obam^qe%3.+0)05+6&yyNFAy23-.yyWyTfkqbopmofkdy

EA^i^o^kyRy3615y
ORkabo`fqvyKyQ^hbmloq^i%22+2)/0+6&fkA^i^o^kqlRkabo`fqvyyWyA^i^o^ky

CQeb?rit^ohyKyJf`e^biD^oobqq%30+2)15+4&+Orkfcvlralk$qe^sbcifdeqm^qe+yyWyRkabo`fqvy
cQeb?rit^ohyKyQfjlqev@rkkfkde^j%50+3)4-&yyWyQfofpc^iDi^abpyyNFAy2-63y
>P`^oibqAfsbopflkpyWyQfofpc^iDi^abpyyKyEfdeBub`rqloAboofkdqlk%50+.)36+-&yyNFAy2-63y
KDbq^Ci^jbfk^?lqqibyWyQfofpc^iDi^abpyyKyColjqeb?lulcFk`bkaf^ofbpyyIy./5.1yyNFAy2-63y
QQebBsboillhObmloqyWyQfofpc^iDi^abpyyKy>odbkqLccf`boD^orpe%50+.)35+3&yyNFAy3-/6y
KDbq^@ljjfppflkyWyQfofpc^iDi^abpyyKyQ^ihqlqebnr^oqboj^pqbo^kadbq^`ljjfppflk)vlrpelriae^sbqefpbnrfmmba^kvqfjbvlr^obfkqebmi^drbi^kap+P^sbp`lrodbpqlkbpcloobmqrok*fkp+yyIy./513y

R?rokqebqbkqyKy?rokqebqbkqfk^`^jmtfqeqebXCi^jbfk^?lqqibZ%1-)2.&yyRy./5.1yyNFAy2-63yyWyTbpqbokMi^drbi^kapy
@P`^oibqAfsbopflkpyKy?rokqebqbkqfk^`^jmtfqeqebXCi^jbfk^?lqqibZ%1-)2.&^kami^kqqebXP`lrodb?^kkboZ%1-)2.&yyRy./5-4yyNFAy2-63yyWyTbpqbokMi^drbi^kapy

QP`^oibqAfsbopflkpyWyQfofpc^iDi^abpyyKyEfdeBub`rqloAboofkdqlk%50+.)36+-&yyNFAy2-63y
>>ii>ilkdqebT^q`eqltbopyWyQfofpc^iDi^abpyyKyEfdeBub`rqloAboofkdqlk%50+.)36+-&yyNFAy2-65y
>QebP`lrodb@^riaolkpyWyQfofpc^iDi^abpyyKyEfdeBub`rqloAboofkdqlk%50+.)36+-&yyNFAy2//5y
QQebP`lrodb@^riaolkpyWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2//5y
>Q^odbq7CbipqlkbCfbiayWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2//6y

@Q^odbq7CbipqlkbCfbiayKyEb^ab^pqqlqebCbipqlkbCfbia%04)23&)hfii@^riaolkIloa?fibj^t)illqqebXCbipqlkbCfbia@^riaolkHbvZ^kavlrtfiiklt_b^_ibqlrpbqebXBjmqvCbipqlkbCfbia?lqqibZ_v$q^ihfkd$qlqeb`^riaolkyyNFAy2//6yyRy.0.53yyWyTbpqbokMi^drbi^kapy
QQ^odbq7CbipqlkbCfbiayKyP`lrodb@^riaolk%04)23&yyNFAy2//6yyWyTbpqbokMi^drbi^kapy
>Obqrokqlqeb?rit^oh%M^oq.&yKyP`lrodb@^riaolk%04)23&yyNFAy2/0-yyWyTbpqbokMi^drbi^kapy

QObqrokqlqeb?rit^oh%M^oq.&yWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2/0-yyWyTbpqbokMi^drbi^kapy
>Q^odbq7A^iplk$pQb^opyWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2/0.yyWyTbpqbokMi^drbi^kapy

@Q^odbq7A^iplk$pQb^opyKyEb^ab^pqqlA^iplk$pQb^op%13)2/&)hfii@^riaolkIloaJ^isfkflrp)illqqebXA^iplk$pQb^op@^riaolkHbvZ^kavlrtfiiklt_b^_ibqlrpbqebXBjmqvA^iplk$pQb^op?lqqibZ_v$q^ihfkd$qlqeb`^riaolkyyNFAy2/0.yyRy.0.54yyWyTbpqbokMi^drbi^kapy
QQ^odbq7A^iplk$pQb^opyKyP`lrodb@^riaolk%13)2/&yyNFAy2/0.yyWyTbpqbokMi^drbi^kapy
>Obqrokqlqeb?rit^oh%M^oq/&yKyP`lrodb@^riaolk%13)2/&yyNFAy2/0/yyWyTbpqbokMi^drbi^kapy

QObqrokqlqeb?rit^oh%M^oq/&yWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2/0/yyWyTbpqbokMi^drbi^kapy
>Q^odbq7TofqefkdE^rkqyWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2/00yyWyTbpqbokMi^drbi^kapy

@Q^odbq7TofqefkdE^rkqyKyEb^ab^pq^d^fkqlqebTofqefkdE^rkq%20)32&)hfii@^riaolkIloaO^w^o`e)illqqebXTofqefkdE^rkq@^riaolkHbvZ^kavlrtfiiklt_b^_ibqlrpbqebXBjmqvTofqefkdE^rkq?lqqibZ_v$q^ihfkd$qlqeb`^riaolkyyNFAy2/00yyRy.0.55yyWyTbpqbokMi^drbi^kapy
QQ^odbq7TofqefkdE^rkqyKyP`lrodb@^riaolk%20)32&yyNFAy2/00yyWyTbpqbokMi^drbi^kapy
>Obqrokqlqeb?rit^oh%M^oq0&yKyP`lrodb@^riaolk%20)32&yyNFAy2/01yyWyTbpqbokMi^drbi^kapy

QObqrokqlqeb?rit^oh%M^oq0&yWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2/01yyWyTbpqbokMi^drbi^kapy
>Q^odbq7D^eoolk$pTfqebofkdyWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2/02yyWyTbpqbokMi^drbi^kapy

@>ii>ilkdqebT^q`eqltbopyRy./5.2yyKyRpbqebX?b^`lkQlo`eZqlj^oh1qltbopfk>kaloe^i+Klqbqe^qvlrpelriarpbqebX?b^`lkQlo`eZkb^oqebbkqo^k`blcqebqltbo%14)4.&%1-)4.&%1/)33&%11)30&yyNFAy2-65yyWyTbpqbokMi^drbi^kapy

@Q^odbq7D^eoolk$pTfqebofkdyKyEb^ab^pqqlqebTofqefkdE^rkq%3/)25&)hfii@^riaolkIloaPlrito^qe)illqqebXD^eoolk$pTfqebofkd@^riaolkHbvZ^kavlrtfiiklt_b^_ibqlrpbqebXBjmqvD^eoolk$pTfqebofkd?lqqibZ_v$q^ihfkd$qlqeb`^riaolkyyNFAy2/02yyRy.0.56yyWyTbpqbokMi^drbi^kapy
QQ^odbq7D^eoolk$pTfqebofkdyKyP`lrodb@^riaolk%3/)25&yyNFAy2/02yyWyTbpqbokMi^drbi^kapy
>Obqrokqlqeb?rit^oh%M^oq1&yKyP`lrodb@^riaolk%3/)25&yyNFAy2/03yyWyTbpqbokMi^drbi^kapy

cQelkaolofiOfsboyKyCo^u?r`hbqaolm%36+/)16+4&yyWyTbpqbokMi^drbi^kapy
CQeb?rit^ohyKyCo^u?r`hbqaolm%36+/)16+4&yyWyTbpqbokMi^drbi^kapy

QObqrokqlqeb?rit^oh%M^oq1&yWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2/03y
Q>ii>ilkdqebT^q`eqltbopyWyQfofpc^iDi^abpyyKyEfdeBub`rqloAboofkdqlk%50+.)36+-&yyNFAy2-65y
>Jfppflk>``ljmifpebayKyEfdeBub`rqloAboofkdqlk%50+.)36+-&yyNFAy2/04yyWyQfofpc^iDi^abpy
>>i^p)>kaloe^iyKyEfdeBub`rqloAboofkdqlk%50+.)36+-&yyNFAy.-2yyWyQfofpc^iDi^abpy

CQelkaolofiOfsboyKyQfjlqev@rkkfkde^j%50+3)4-&yyWyQfofpc^iDi^abpy
OB^pqbokMi^drbi^kapyKyOrkqlB^pqbokMi^drbi^kap%6+0)32+5&yyNFAy221/yyWyB^pqbokMi^drbi^kapy

QPfpqboM^jbi^yKyM^jbi^Obam^qe%0/+2)50+5&yyNFAy23-.yyWyB^pqbokMi^drbi^kapy
>M^jbi^$pAliiyKyM^jbi^Obam^qe%0/+2)50+5&yyNFAy2.16yyWyB^pqbokMi^drbi^kapy
@M^jbi^$pAliiyKyCfkaXM^jbi^$pAlii$pEb^aZ)XM^jbi^$pAlii$pIbcqPfabZ^kaXM^jbi^$pAlii$pOfdeqPfabZfkqebelrpbpfkA^ooltpefob%02+2)5/+6&%02+2)52+0&%02+-)52+0&yyNFAy2.16yyWyB^pqbokMi^drbi^kapy
QM^jbi^$pAliiyKyM^jbi^Obam^qe%0/+2)50+5&yyNFAy2.16yyWyB^pqbokMi^drbi^kapy
>>rkqfbJ^oibkbyKyM^jbi^Obam^qe%0/+2)50+5&yyNFAy2.2/yyWyB^pqbokMi^drbi^kapy
>Rk`ib@^oifkyKyM^jbi^Obam^qe%0/+2)50+5&yyNFAy2/1.yyWyB^pqbokMi^drbi^kapy

OIfdeq$pElmb@e^mbiyKyQo^sbiqlIfdeq$pElmb@e^mbi%42+5)2/+/&yyWyB^pqbokMi^drbi^kapy
QRk`ib@^oifkyKy@^oifkObam^qe%42+4)20+6&yyNFAy2/1.yyWyB^pqbokMi^drbi^kapy
QArhbKf`eli^pWsbobkelccyKyArhbKf`eli^pWsbobkelcc%42+3)20+6&yyNFAy3-0-yyWyB^pqbokMi^drbi^kapy
>Qeb>o`efsfpqyKyArhbKf`eli^pWsbobkelcc%42+3)20+5&yyNFAy2/2.yyWyB^pqbokMi^drbi^kapy
>QebCibpeAlbpKlqIfbyKy?bqfk^?fddibwfkh%42+4)20+4&yyNFAy2/./yyWyB^pqbokMi^drbi^kapy
>Mi^drbaE^q`eifkdpyKy?bqfk^?fddibwfkh%42+4)20+4&yyNFAy22/6yyWyB^pqbokMi^drbi^kapy
>ElrpbplcqebElivyKyIblkfa?^oqe^iljbtqebObsboba%42+6)2/+.&yyNFAy2/10yyWyB^pqbokMi^drbi^kapy
>W^bia^ooqebLrq`^pqyKy@^obq^hbo>ibk%40+6)24+4&yyNFAy3-/.yyWyB^pqbokMi^drbi^kapy

@W^bia^ooqebLrq`^pqyKyHfiiW^bia^oo^qqebO^sbk`olcq%/0+5)44+6&^kaillqXW^bia^oo$pEb^aZyyNFAy3-/.yyWyB^pqbokMi^drbi^kapy

@Mi^drbaE^q`eifkdpyKyOrkfkqlP`elilj^k`b%36+-)40+0&^kahfiiMi^drbaE^q`eifkdp+yyNFAy22/6yyWyTbpqbokMi^drbi^kapy
OTbpqbokMi^drbi^kapyKyOrk_^`hlrqlcP`elilj^k`by
Q>rkqfbJ^oibkbyKyJ^oibkbObam^qe%16+/)45+2&yyNFAy2.2/yyWyTbpqbokMi^drbi^kapy
>>Pqo^kdbEfpqlof^kyKyJ^oibkbObam^qe%16+/)45+2&yyNFAy2.20yyWyTbpqbokMi^drbi^kapy
@>Pqo^kdbEfpqlof^kyKyDbqXGlpbme$pTbaafkdOfkdZcolj^do^sbpqlkbgrpqkloqelcqebelrpb%16+4)43+5&yyNFAy2.20yyWyTbpqbokMi^drbi^kapy
Q>Pqo^kdbEfpqlof^kyKy@eoljfb%06+2)33+5&yyNFAy2.20yyWyTbpqbokMi^drbi^kapy
>Qeb>kk^iplcA^ooltpefobyKy@eoljfb%06+2)33+5&yyNFAy2.21yyWyTbpqbokMi^drbi^kapy
@>i^p)>kaloe^iyKyPi^v>o^g%12+2)36+2&^ka_ofkd>o^g$pMevi^`qbovPe^oaqlEfdeBub`rqloAboofkdqlk^qqeb?rit^ohyyNFAy.-2yyWyTbpqbokMi^drbi^kapy
@Qeb>kk^iplcA^ooltpefobyKyDbqqeb_llhX>kk^iplcA^ooltpefobZfkqebqltke^ii%10+6)36+/&lc>kaloe^iyyNFAy2.21yyWyTbpqbokMi^drbi^kapy

QQeb>kk^iplcA^ooltpefobyKy@eoljfb%06+2)33+5&yyNFAy2.21yyWyTbpqbokMi^drbi^kapy
>?olqebo@^oifkyKy@eoljfb%06+2)33+5&yyNFAy2/.-yyWyTbpqbokMi^drbi^kapy

Q>i^p)>kaloe^iyKyEfdeBub`rqloAboofkdqlk%50+.)36+-&yyNFAy.-2yyWyQfofpc^iDi^abpy

CIfdeq$pElmb@e^mbiyKyCivqlIfdeq$pElmb@e^mbi%50+3)4-&yyNFAy2.5.yyWyQfofpc^iDi^abpy
Q?olqebo@^oifkyKy@^oifkObam^qe%42+4)20+6&yyNFAy2/.-yyWyB^pqbokMi^drbi^kapy
>Sfii^fkplcA^ooltpefobyKy@^oifkObam^qe%42+4)20+6&yyNFAy2.5.yyWyB^pqbokMi^drbi^kapy
>EbolbplcA^ooltpefobyKy@^oifkObam^qe%42+4)20+6&yyNFAy2.35yyWyB^pqbokMi^drbi^kapy
QMi^drbaE^q`eifkdpyKy?bqfk^?fddibwfkh%42+4)20+4&yyNFAy22/6yyWyB^pqbokMi^drbi^kapy
>?lkbp`vqebAfdpyKyOle^kqeb>pp^ppfk%42+4)2/+3&yyNFAy6./3yyWyB^pqbokMi^drbi^kapy
QW^bia^ooqebLrq`^pqyKy@^obq^hbo>ibk%40+4)24+4&yyNFAy3-/.yyWyB^pqbokMi^drbi^kapy

KPe^qqbobaPtloalcJ^oarhyKyObqofbsbqebPe^qqbobaPtloalcJ^oarh%16+0)26+4&yyNFAy2.5.yyIy./624yyWyB^pqbokMi^drbi^kapy
@Sfii^fkplcA^ooltpefobyKyObqofbsbPhriilcElodrp%13+1)11+1&yyNFAy2.5.yyWyB^pqbokMi^drbi^kapy

OTbpqbokMi^drbi^kapyKy%36+6)2-+0&yyWyTbpqbokMi^drbi^kapy
KEbolbplcA^ooltpefobyKyObqofbsbObam^qe$pPefbia%30+5)24+/&yyNFAy2.35yyIy./622yyWyTbpqbokMi^drbi^kapy
@EbolbplcA^ooltpefobyKyObqofbsbA^sfi$pIf_o^j%1/+1).5+6&yyNFAy2.35yyWyTbpqbokMi^drbi^kapy

OIfdeq$pElmb@e^mbiyKyQo^sbiqlIfdeq$pElmb@e^mbi%42+5)2/+/&yyWyB^pqbokMi^drbi^kapy
QSfii^fkplcA^ooltpefobyKy@^oifkObam^qe%42+4)20+6&yyNFAy2.5.yyWyB^pqbokMi^drbi^kapy
QEbolbplcA^ooltpefobyKy@^oifkObam^qe%42+4)20+6&yyNFAy2.35yyWyB^pqbokMi^drbi^kapy
>J^o^raboplcA^ooltpefobyKy@^oifkObam^qe%42+4)20+6&yyNFAy2/-3yyWyB^pqbokMi^drbi^kapy

@J^o^raboplcA^ooltpefobyKyHfiiP`lrodb@e^jmflkp%41+2)05+2&%0/+2)2-+3&^ka_ofkd2Obplk^qfkdPhriip^kaqebJvpqf`@ovpq^iql@^oifkObam^qeyyRy.0.23yyNFAy2/-3yyWyB^pqbokMi^drbi^kapy
QJ^o^raboplcA^ooltpefobyKy@^oifkObam^qe%42+4)20+6&yyNFAy2/-3yyWyB^pqbokMi^drbi^kapy
>Obqrokql@eoljfbyKy@^oifkObam^qe%42+4)20+6&yyNFAy261.yyWyB^pqbokMi^drbi^kapy
CQelkaolofiOfsboyKyDblodf^%41+2)2.+/&yyWyB^pqbokMi^drbi^kapy
QObqrokql@eoljfbyKy@eoljfb%06+2)33+5&yyNFAy261.yyWyTbpqbokMi^drbi^kapy
>Qeb?^qqiblcA^ooltpefobyKy@eoljfb%06+2)33+5&yyNFAy24/.yyWyTbpqbokMi^drbi^kapy
OA^ooltpefobyKy%02)51&yyWyB^pqbokMi^drbi^kapy
@Qeb?^qqiblcA^ooltpefobyKyRpbqebXObif`?rkaibZfkqebqltkpnr^ob+HbbmA^sfiIfdeqcfob^ifsbrkqfiElodrpafbp+Hbbm@^mq^fkObam^qe^iifsbrkqfiObam^qeqeb@loormqba^mmb^op+Abcb^qObam^qeqeb@loormqba+yyNFAy24/.yyWyB^pqbokMi^drbi^kapy
QQeb?^qqiblcA^ooltpefobyKyM^jbi^Obam^qe%0/+2)50+5&yyNFAy24/.yyWyB^pqbokMi^drbi^kapy
>EfaabkQob^probpyKyM^jbi^Obam^qe%0/+2)50+5&yyNFAy261/yyWyB^pqbokMi^drbi^kapy
QEfaabkQob^probpyKyGlpbme$p@ebpq%0/+/)50+1&yyNFAy261/yyWyB^pqbokMi^drbi^kapy

OPqo^qelijbyKyIfsbPfab%/4+4)5+2&yyWyB^pqbokMi^drbi^kapy
K@liib`q++yKyXPqo^qelijbElivT^qboZcolj`o^qbp)XMi^drbaCibpeP^jmibZcoljWlj_fbp^kaX?lkbCo^djbkqpZcoljphbibqlkp+y
@ElrpbplcqebElivyKyLmbkqeb`o^qbpp`^qqboba^olrkaPqo^qelijbp^ka`liib`q2uXPqo^qelijbElivT^qboZ^kaobjbj_boqlp^sbqebjcloqebnrbpqyyNFAy2/10y
@QebCibpeAlbpKlqIfbyKy@liib`q.-uXMi^drbaCibpeP^jmibZqebpblkivaolmlccWlj_fbKM@fkpqo^qelijb%klqPhbibqlkp)Pmb`qo^iploDelpqp&yyNFAy2/./y
H>o`efsfpqD^icloayKyHfii>o`efsfpqD^icloaebfpfkqebP`^oibq_rfiafkd`ilpbqlqebi^pq_lpp)vlrtfii^iplkbbaql_rokqeb>o`efsb_v`if`hfkdlkfqyyNFAy2/2.yyNLy>o`efsfpqD^icloaPi^fk7.,.yyWyB^pqbokMi^drbi^kapy
@>o`efsfpqD^icloayKy?rokqeb>o`efsb_v`if`hfkdlkfq+yyNFAy2/2.y

HJ^dfpqo^qb?^oqefi^pyKyHfiiJ^dfpqo^qb?^oqefi^ploqebXHbvqlqeb@fqvZ)plvlr`^kdbqfkqlqebrkab^apfablcPqo^qelijb+yyIy./05/y

OB^pqbokMi^drbi^kapyKyOrklrqlcPqo^qelijby
OIfdeq$pElmb@e^mbiyKyQo^sbiqlIfdeq$pElmb@e^mbi%42+5)2/+/&yyWyB^pqbokMi^drbi^kapy
QQeb>o`efsfpqyKyArhbKf`eli^pWsbobkelcc%42+3)20+5&yyNFAy2/2.yyWyB^pqbokMi^drbi^kapy
QQebCibpeAlbpKlqIfbyKy?bqfk^?fddibwfkh%42+4)20+4&yyNFAy2/./yyWyB^pqbokMi^drbi^kapy
>Qeb>`qfsb>dbkqyKy?bqfk^?fddibwfkh%42+4)20+4&yyNFAy2/.0yyWyB^pqbokMi^drbi^kapy
QElrpbplcqebElivyKyIblkfa?^oqe^iljbtqebObsboba%42+6)2/+.&yyNFAy2/10yyWyB^pqbokMi^drbi^kapy

OPqo^qelijbyKyIfsbPfab%/4+4)5+2&yyWyB^pqbokMi^drbi^kapy
H?^ik^ww^oyKyHfii?^ik^ww^oqebcfk^i_lppfkErj^kpfablcPqo^qelijb^kaillqXEb^alc?^ik^ww^oZyyIy.0/2-yyNFAy2/3/y
>QebQorqe@ljbp@o^pefkdAltkyKyXEb^alc?^ik^ww^oZyyRy.0/2-yyNFAy2/3/y

OB^pqbokMi^drbi^kapyKyOrklrqlcPqo^qelijby
OIfdeq$pElmb@e^mbiyKyQo^sbiqlIfdeq$pElmb@e^mbi%42+5)2/+/&yyWyB^pqbokMi^drbi^kapy

QQebQorqe@ljbp@o^pefkdAltkyKyArhbKf`eli^pWsbobkelcc%42+3)20+5&yyNFAy2/3/yyWyB^pqbokMi^drbi^kapy
>>_lsb^ka?bvlkayKyArhbKf`eli^pWsbobkelcc%42+3)20+5&yyNFAy2/30yyWyB^pqbokMi^drbi^kapy

OPqo^qelijbyKyAb^aPfab%10+2).6+2&yyWyB^pqbokMi^drbi^kapy
@Qeb>`qfsb>dbkqyKyQo^sbiqlPqo^qelijb^kapb^o`eqebwfddro^qp+Cfka^kaobqrokkbtP`lrodbA^q^ql?bqfk^?fddibwfkh+yyNFAy2/.0yyWyB^pqbokMi^drbi^kapy
@>_lsb^ka?bvlkayKyAbcb^q?^olkOfsbka^ob^kaIllqefpeb^a+yyNFAy2/30y

OB^pqbokMi^drbi^kapyKyOrklrqlcPqo^qelijby
OIfdeq$pElmb@e^mbiyKyQo^sbiqlIfdeq$pElmb@e^mbi%42+5)2/+/&yyWyB^pqbokMi^drbi^kapy

QQeb>`qfsb>dbkqyKy?bqfk^?fddibwfkh%42+4)20+4&yyNFAy2/.0yyWyB^pqbokMi^drbi^kapy
Q>_lsb^ka?bvlkayKyArhbKf`eli^pWsbobkelcc%42+3)20+5&yyNFAy2/30yyWyB^pqbokMi^drbi^kapy
>IloaJ^utbiiQvolprpyKyArhbKf`eli^pWsbobkelcc%42+3)20+5&yyNFAy2/31yyWyB^pqbokMi^drbi^kapy
QIloaJ^utbiiQvolprpyKyIloaJ^utbiiQvolprp%42+6)2/+/&yyNFAy2/31yyWyB^pqbokMi^drbi^kapy
>Qeb>odbkqEliayKyIloaJ^utbiiQvolprp%42+6)2/+/&yyNFAy2/32yyWyB^pqbokMi^drbi^kapy
QQeb>odbkqEliayKyQeb>odbkqElia%42+6)2/+/&yyNFAy2/32yyWyB^pqbokMi^drbi^kapy
@?lkbp`vqebAfdpyKyJ^hbprobvlre^sb0-X?lkbCo^djbkqpZ+Fcklq)hfiiphbibqlkpfkqebMi^drbi^kaprkqfivlral+yyNFAy6./3yyWyB^pqbokMi^drbi^kapy
Q?lkbp`vqebAfdpyKyOle^kqeb>pp^ppfk%42+4)2/+3&yyNFAy6./3yyWyB^pqbokMi^drbi^kapy

K>odbkqA^tkBu^iqbayKy@lkqfkrb`liib`qfkd^kaqrokfkdfkP`lrodbpqlkbp+Vlr`^kalPqo^qelijbork^kac^ojqeb?^olkJlrkq^qqebp^jbqfjb^kavlr`^k^iplqrokfkX?lkbCo^djbkqpZ)X@ovmqCfbkaM^oqpZ)X@loblcBibjbkqpZ)XA^ohFolkP`o^mpZ)^kaXP^s^dbColkapZ+Qebbka@^riaolknrbpqp^ob^iplobmb^q^_ibcloobm+y
KDrfab@ljmibqb

]]
end)
