DugisGuideViewer:RegisterGuide("Cenarion Expedition Reputation (70+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabtfiidllsbo^iiqebnrbpqpkbbabaqldbqqebDr^oaf^klc@bk^ofrp>`efbsbjbkq%Bu^iqbatfqe@bk^oflk@fo`ib^ka@bk^oflkBumbafqflk+Lk`b^iiqebnrbpqp^obalkbclo^m^oqf`ri^oc^`qflk)qebkfpgrpqdofkafkdlrqqebobmb^q^_ibarkdblkp,qrok*fkpqldbqqlBu^iqba+Qefpdrfab^pprjbpqe^qvlr^obibsbi5-)pljblcqebarkdblkp^obe^oaqlplilrkabo5-+y
KIltIbsbiNrbpqpyKyJ^hbprobvlr^obqo^hfkdiltibsbinrbpqpqlj^hbfqb^pfboqlpbbqebnrbpqpdfsbop+>ipl)j^hbprobvlre^sbafp`lsboaAfobJ^riqebfkpq^k`b)lovlrtlk$q_b^_ibql^``bmq^`lrmiblcnrbpqp+Grpqorkrmqebpqbm^kafk^ifqqibt^vp+y

eA^i^o^kyKyJ^hbA^i^o^kvlroeljb%32+3)0/+/&Dbqqfkdql^kacoljqebpbil`^qflktfii_bb^pfbocoljA^i^o^k+yyWyA^i^o^ky
OPe^qqo^qe@fqvyKyQ^hbmloq^i%23+0)//+1&fkA^i^o^kqlPe^qqo^qe@fqvyyWyA^i^o^ky

>JfppfkdJfppfsbyRy/0005yyNFAy6040yyKyQebfqbjXBolabaIb^qebo@^pbZpq^oqpnrbpq*DofkaJ^o^rafkd@orpq?ropqbop%14)10&rkqfifqaolmp+yyWyEbiicfobMbkfkpri^y
>Ebimfkdqeb@bk^oflkMlpqyKyC^i`lkboAobkk^Ofsbotfka%/4+4)3-+1&yyNFAy.-11/yyWyEbiicfobMbkfkpri^y
QEbimfkdqeb@bk^oflkMlpqyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy.-11/yyWyEbiicfobMbkfkpri^y
>Abjlkf`@lkq^jfk^qflkyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy604/yyWyEbiicfobMbkfkpri^y
QJfppfkdJfppfsbyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy6040yyWyEbiicfobMbkfkpri^y
>HbbmQelokc^kdEfii@ib^oyKyJ^ero^jPqlrqellc%.2+5)2/+0&yyNFAy.-.26yyWyEbiicfobMbkfkpri^y
>Qeb@bk^oflkBumbafqflkyKy>jvqefbiJfpqt^ihbo%.3+-)2/+/&yyNFAy66./yyWyEbiicfobMbkfkpri^y
>@lilpp^iJbk^`byKyQli^$qeflk%.2+/)2/+.&yyNFAy.-.0/yyWyEbiicfobMbkfkpri^y
@Abjlkf`@lkq^jfk^qflkyKyHfiiebi_l^opclo3XEbi_l^o?illaP^jmibZ^olrka%/1)25&yyNFAy604/yyWyEbiicfobMbkfkpri^y
QAbjlkf`@lkq^jfk^qflkyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy604/yyWyEbiicfobMbkfkpri^y
>Qbpqfkdqeb>kqfalqbyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy.-/22yyWyEbiicfobMbkfkpri^y
@Qbpqfkdqeb>kqfalqbyKyRpbqebX@bk^oflk>kqfalqbZlk^kb^o_vEbi_l^o%.2)2-&yyNFAy.-/22yyRy/0004yyWyEbiicfobMbkfkpri^y
QQbpqfkdqeb>kqfalqbyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy.-/22yyWyEbiicfobMbkfkpri^y
@@lilpp^iJbk^`byKyHfii2O^dfkd@lilpprp%.3)10&yyNFAy.-.0/yyWyEbiicfobMbkfkpri^y
>@ofjplk@ovpq^i@irbyKyHbbmhfiifkdO^dfkd@lilpprprkqfivlrcfkaX@ofjplk@ovpq^iPe^oaZqlpq^oqnrbpq%.3)10&yyRy/6143yyNFAy.-.01yyWyEbiicfobMbkfkpri^y
Q@lilpp^iJbk^`byKyQli^$qeflk%.2+/)2/+.&yyNFAy.-.0/yyWyEbiicfobMbkfkpri^y
Q@ofjplk@ovpq^i@irbyKyQli^$qeflk%.2+3)2/+.&yyNFAy.-.01yyWyEbiicfobMbkfkpri^y
>QebB^oqe_fkaboyKyQli^$qeflk%.2+3)2/+.&yyIy.-016yyNFAy.-016yyWyEbiicfobMbkfkpri^y
QQebB^oqe_fkaboyKyB^oqe_fkaboD^i^kaof^Kfdeq_obbwb%.2+6)2.+3&yyNFAy.-016yyWyEbiicfobMbkfkpri^y
>K^qro^iObjbafbpyKyB^oqe_fkaboD^i^kaof^Kfdeq_obbwb%.2+6)2.+3&yyNFAy.-02.yyWyEbiicfobMbkfkpri^y
@K^qro^iObjbafbpyKyPfk`bm^q`e0+-+/qefpnrbpqe^p_bbkmobqqvb^pvqlplilclojlpq`i^ppbp)vlr`^kphfmqefpnrbpqfcvlr$obrk^_ibqlalfq^ilkb)`ib^oqeb^ob^^olrka%.0)06&qebkmi^kqqebXPbbalcObsfq^ifw^qflkZlkqeboba`fo`ib+Cl`rplkhfiifkdqeb_lpp)jlob^aaptfii^mmb^o_rqvlrtfii`ljmibqbqebnrbpq^pilkd^pvlrhfiiqeb_lppyyRy/6145yyNFAy.-02.yyWyEbiicfobMbkfkpri^y
QK^qro^iObjbafbpyKyB^oqe_fkaboD^i^kaof^Kfdeq_obbwb%.2+6)2.+3&yyNFAy.-02.yyWyEbiicfobMbkfkpri^y
@HbbmQelokc^kdEfii@ib^oyKyHfii5Qelokc^kdO^s^dbop^ka5Qelokc^kdSbkljpmfqqbopqlqebtbpq)^qQelokc^kdEfiiyyNFAy.-.26yyWyEbiicfobMbkfkpri^y
QHbbmQelokc^kdEfii@ib^oyKyJ^ero^jPqlrqellc%.2+5)2/+0&yyNFAy.-.26yyWyEbiicfobMbkfkpri^y

>QebRj_o^cbkQof_byKyFhbvbk%5-+1)31+/&yyNFAy6414yyWyW^kd^oj^opey
>Mi^kqplcW^kd^oj^opeyKyI^ro^kk^Qe^o$tbii%5-+0)31+0&yyNFAy65-/yyWyW^kd^oj^opey
>QebAvfkd?^i^k`byKyIbqevkJllkcfob%45+3)30+.&yyNFAy6562yyWyW^kd^oj^opey
>Afpqro_^k`b^qRj_o^cbkI^hbyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64.3yyWyW^kd^oj^opey
>T^oabkE^jllqyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy6445yyWyW^kd^oj^opey
>Ib^abolcqebA^oh`obpqyKyT^kqbaMlpqbo%46+.)31+5&yyNFAy640-yyWyW^kd^oj^opey
>Ib^abolcqeb?illap`^ibyKyT^kqbaMlpqbo%46+.)31+5&yyNFAy65.4yyWyW^kd^oj^opey
e@bk^oflkObcrdbyKyFkkhbbmbo@lovqePqlhqolk%45+3)30&yyNFAy64/5yyWyW^kd^oj^opey
QQeb@bk^oflkBumbafqflkyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy66./yyWyW^kd^oj^opey
QT^oabkE^jllqyKyT^oabkE^jllq%46+-)32+0&yyNFAy6445yyWyW^kd^oj^opey
>>T^ojTbi`ljbyKyT^oabkE^jllq%46+-)32+0&yyNFAy64/5yyWyW^kd^oj^opey

@QebAvfkd?^i^k`byKyHfii?ldi^peplrqelc@bk^oflkObcrdb%5/)42&yyNFAy6562yyWyW^kd^oj^opey
@QebRj_o^cbkQof_byKyDlqlRj_o^cbkSfii^db%5/)50&^kapi^vH^q^or%52)6-&)5Rj_o^cbkPbbop)3Rj_o^cbkTfq`eal`qlop^ka3Rj_o^cbkLo^`ibpyyNFAy6414yyWyW^kd^oj^opey
>Bp`^mbcoljRj_o^cbkyKyH^vo^Ilkdj^kb%50+0)52+2&yyNFAy642/yyWyW^kd^oj^opey
@QebAvfkd?^i^k`byKyCfka^kahfii?ldi^petelm^qolip^olrka%5/)4/&alqefptefibbp`loqfkdH^vo^^kapebtfiiebimvlrhfii?ldi^peyyNFAy6562yyWyW^kd^oj^opey
@Bp`^mbcoljRj_o^cbkyKyBp`loqH^vo^%5.+0)43+4&yyNFAy642/yyWyW^kd^oj^opey
@Afpqro_^k`b^qRj_o^cbkI^hbyKyFksbpqfd^qbRj_o^cbkI^hb_vdlfkdkb^oqebMrjm%4-)5-&yyNFAy64.3yyWyW^kd^oj^opey
@Mi^kqplcW^kd^oj^opeyKy@liib`q.-XRkfabkqfcfbaMi^kqM^oqpZaolmmba_vj^kvhfkaplcjl_pfkW^kd^oj^ope+Bu^jmibil`^qflk%4-)5-&yyNFAy65-/yyWyW^kd^oj^opey

QQebAvfkd?^i^k`byKyIbqevkJllkcfob%45+3)30+.&yyNFAy6562yyWyW^kd^oj^opey
QAfpqro_^k`b^qRj_o^cbkI^hbyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64.3yyWyW^kd^oj^opey
QBp`^mbcoljRj_o^cbkyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy642/yyWyW^kd^oj^opey
QMi^kqplcW^kd^oj^opeyKyI^ro^kk^Qe^o$tbii%5-+0)31+0&yyNFAy65-/yyWyW^kd^oj^opey
QQebRj_o^cbkQof_byKyFhbvbk%5-+1)31+/&yyNFAy6414yyWyW^kd^oj^opey
>>A^jm)A^ohMi^`byKyFhbvbk%5-+1)31+/&yyNFAy6455yyWyW^kd^oj^opey
>P^sfkdqebPmlobilhpyKyI^ro^kk^Qe^o$tbii%5-+0)31+0&yyNFAy.--63yyWyW^kd^oj^opey
>P^cbdr^oafkdqebT^q`ebopyKyTfka`^iibo?i^`hellc%5-+1)31+4&yyNFAy6561yyWyW^kd^oj^opey
>>pqeb@oltCifbpyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64.5yyWyW^kd^oj^opey
@>pqeb@oltCifbpyKyRpbqebXPqloj`olt>jribqZyyRy/2132yyNFAy64.5yyWyW^kd^oj^opey
Q>pqeb@oltCifbpyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64.5yyWyW^kd^oj^opey
>?^i^k`bJrpq?bMobpbosbayKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64/-yyWyW^kd^oj^opey

@>A^jm)A^ohMi^`byKyXFhbvbk$p?bilkdfkdpZ%4-+3)64+6&`^k_bclrkalk^ol`hfkqeb_^`hlcqebCrkddlo@^sbok)plrqelcRj_o^cbkI^hb%41)6.&yyNFAy6455yyWyW^kd^oj^opey
@P^cbdr^oafkdqebT^q`ebopyKyHfiiIloaHi^n^qqeb_lqqljlcqebCrkddlo@^sbok%4/)61&yyNFAy6561yyWyW^kd^oj^opey
@P^sfkdqebPmlobilhpyKyPi^v.-J^opeAobadbop^ka.-J^opeIrohbop^qqebCrkddlo@^sbok%41)6.&yyNFAy.--63yyWyW^kd^oj^opey

KAfp^_ibRj_o^cbkMrjmyKyRpbqebpbbap^qqeb`lkqolipqlqebRj_o^cbkI^hbmrjm%4-)5-&yyRy/1022yyNFAy64/-yyNLyRj_o^cbkI^hb@lkqolipAfp^_iba7.,.yyWyW^kd^oj^opey
@Ib^abolcqebA^oh`obpqyKyCfka^kaHfiiO^g^eE^de^wba%32)35&^ibsbi30bifqb+Vlrpelria_b^_ibqlplilefjyyNFAy640-yyWyW^kd^oj^opey
KAfp^_ibI^dllkMrjmyKyRpbqebpbbap^qqeb`lkqolipqlqebI^dllkmrjm%31)30&yyRy/1022yyNFAy64/-yyNLyI^dllk@lkqolipAfp^_iba7.,.yyWyW^kd^oj^opey

QP^sfkdqebPmlobilhpyKyI^ro^kk^Qe^o$tbii%5-+0)31+0&yyNFAy.--63yyWyW^kd^oj^opey
Q>A^jm)A^ohMi^`byKyFhbvbk%5-+1)31+/&yyNFAy6455yyWyW^kd^oj^opey
QP^cbdr^oafkdqebT^q`ebopyKyTfka`^iibo?i^`hellc%5-+1)31+4&yyNFAy6561yyWyW^kd^oj^opey
>Te^q$pTolkd^q@bk^oflkQef`hbq<yKyIbqevkJllkcfob%45+3)30+.&yyNFAy6624yyWyW^kd^oj^opey
>T^q`eboIbbp^$leyKyIbqevkJllkcfob%45+3)30+.&yyNFAy6364yyWyW^kd^oj^opey
>?ibppfkdplcqeb>k`fbkqpyKyTfka`^iibo?i^`hellc%5-+1)31+4&yyNFAy6452yyWyW^kd^oj^opey
@?ibppfkdplcqeb>k`fbkqpyKyDbqqeb?rcccoljqebqtl_fd>k`fbkqQobbpfkqltk%5-)32&yyNFAy6452yyWyW^kd^oj^opey
Q?ibppfkdplcqeb>k`fbkqpyKyTfka`^iibo?i^`hellc%5-+1)31+4&yyNFAy6452yyWyW^kd^oj^opey

KAfp^_ibPbombkqI^hbMrjmyKyRpbqebpbbap^qqeb`lkqolipqlqebPbombkqI^hbmrjm%3.)1-&yyRy/1022yyNFAy64/-yyNLyPbombkqI^hb@lkqolipAfp^_iba7.,.yyWyW^kd^oj^opey
@Ib^abolcqeb?illap`^ibyKyPi^vO^gfpCv^peb^qPbombkqI^hb%31)1.&+yyNFAy65.4yyWyW^kd^oj^opey

QT^q`eboIbbp^$leyKyT^q`eboIbbp^$le%/0)33&yyNFAy6364yyWyW^kd^oj^opey
>L_pbosfkdqebPmlobifkdpyKyT^q`eboIbbp^$le%/0)33&yyNFAy64-.yyWyW^kd^oj^opey
@L_pbosfkdqebPmlobifkdpyKyFksbpqfd^qbqebPm^tkfkdDibkfkW^kd^oj^ope%.0)3/&yyNFAy64-.yyWyW^kd^oj^opey
QL_pbosfkdqebPmlobifkdpyKyT^q`eboIbbp^$le%/0)33&yyNFAy64-.yyWyW^kd^oj^opey
>>NrbpqflklcDirqqlkvyKyT^q`eboIbbp^$le%/0)33&yyNFAy64-/yyWyW^kd^oj^opey
@>NrbpqflklcDirqqlkvyKyIllhclo.-XAfp`^oabaKrqofjbkqZqlqebb^pq^qNr^ddOfadb%/5)30&yyNFAy64-/yyWyW^kd^oj^opey
Q>NrbpqflklcDirqqlkvyKyT^q`eboIbbp^$le%/0)33&yyNFAy64-/yyWyW^kd^oj^opey
>C^jfif^oCrkdfyKyT^q`eboIbbp^$le%/0)33&yyNFAy64-5yyWyW^kd^oj^opey

>Qeb@lrkqlcqebJ^opebpyRy/2126yyKyHfii@lrkqRkdri^fcvlrafak$q)_^`hplrqelcW^_o^$Gfk%00)26&yyNFAy66..yyWyW^kd^oj^opey

KAfp^_ibJ^opeifdeqI^hbMrjmyKyRpbqebpbbap^qqeb`lkqolipqlqebJ^opeifdeqI^hbmrjm%/2)1/&yyRy/1022yyNFAy64/-yyNLyJ^opeifdeqI^hb@lkqolipAfp^_iba7.,.yyWyW^kd^oj^opey
@>T^ojTbi`ljbyKyD^qebo0-XK^d^@i^tpZtef`elc`lropb)aolmlcqebK^d^fkW^kd^oj^ope+Bu^jmibil`^qflkp%3/)35&^ka%4/)4/&yyNFAy64/5yyWyW^kd^oj^opey
@C^jfif^oCrkdfyKy@liib`q.2XJrpeolljP^jmibpZcoljqebLdobp^qqebEbtk?ld%00)05&yyNFAy64-5yyWyW^kd^oj^opey
>Ao^fkP`ebj^qf`pyRy/100-yyKyQebfqbjXAo^fkP`ebj^qf`pZpq^oqpqefpnrbpq*aolmmba_vPqb^jMrjmLsbopbbop^ka?illap`^ibLsbopbbop^olrka%3/)1-&yyNFAy640.yyWyW^kd^oj^opey
@Ao^fkP`ebj^qf`pyKyVlrkbbaqldlqlqeb`bkqoblcPbombkqI^hb%2-)1-&yyNFAy640.yyWyW^kd^oj^opey

Q?^i^k`bJrpq?bMobpbosbayKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64/-yyWyW^kd^oj^opey
QAo^fkP`ebj^qf`pyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy640.yyWyW^kd^oj^opey
>T^okfkdqeb@bk^oflk@fo`ibyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64/1yyWyW^kd^oj^opey
Q>T^ojTbi`ljbyKyT^oabkE^jllq%46+-)32+0&yyNFAy64/5yyWyW^kd^oj^opey
QIb^abolcqeb?illap`^ibyKyT^oabkE^jllq%46+-)32+0&yyNFAy65.4yyWyW^kd^oj^opey
QIb^abolcqebA^oh`obpqyKyT^oabkE^jllq%46+-)32+0&yyNFAy640-yyWyW^kd^oj^opey

QT^okfkdqeb@bk^oflk@fo`ibyWyEbiicfobMbkfkpri^yyKy>jvqefbiJfpqt^ihbo%.3+-)2/+/&yyNFAy64/1y
>ObqrokqlqebJ^opeyWyEbiicfobMbkfkpri^yyKy>jvqefbiJfpqt^ihbo%.3+-)2/+/&yyNFAy640/y

QObqrokqlqebJ^opeyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy640/yyWyW^kd^oj^opey
>C^fibaFk`ropflkyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy6543yyWyW^kd^oj^opey
QC^fibaFk`ropflkyKyT^q`eboGe^kd%2/+0)03+-&Ptfjaltkqebmfmb^q%2-+0)1-+6&yyNFAy6543yyWyW^kd^oj^opey
>Ilpqfk>`qflkyKyT^q`eboGe^kd%2/+0)03+-&yyWyW^kd^oj^opeyyNFAy6405y

OPi^sbMbkpyKyBkqboPi^sbMbkpArkdblkyyNFAy64.2yyFy

KCfkaTbbaboDobbkqerj_yKyCfkaTbbaboDobbkqerj_)obcboqlvlronrbpqqo^`hbo)ebfprm^i^odbo^jm^cqbovlrgrjmlcc^altkt^oapilmfkdo^jmfk^mllilct^qbo^_lrq.,/t^vfkqlPi^sbMbkpyyNLyTbbaboDobbkqerj_Afp`lsbobayyNFAy6405y
KCfkaK^qro^ifpq?fqbyKyCfkaK^qro^ifpq?fqb)obcboqlvlronrbpqqo^`hbo)Eb$pfk^`^db_bclobqebi^pq_lpp)obp`rbefj^ka0KM@$ptfiipm^tkyyNLyK^qro^ifpq?fqbAfp`lsbobayyNFAy6405y

OW^kd^oj^opeyKyQo^sbi_^`hqlW^kd^oj^ope%.6+2)2-+.&yyWyW^kd^oj^opeyyNFAy64.2y

ORkabo_ldyKyBkqboRkabo_ldArkdblkyyNFAy64.4yyFy

KCfkaB^oqe_fkaboO^vdbyKy>cqbovlrhfiiDe^w$^k)ptfj^`olppqebt^qbo+Grjmaltkqlqebdolrka_bilt+Cliiltqebol^aqlqebibcqALKLQdlaltkqlqebcfopqofdeq_rq`lkqfkrbrmqltebobqebol^apb^jpqle^sb^kbka^kaeb^afkdrmt^oap^_fq+Ebtfii_bpq^kafkdebobpqb^iqebayyNLyB^oqe_fkaboO^vdbAfp`lsbobayyNFAy6405y
KCfkaTfka`^iibo@i^tyKyTfka`^iibo@i^tfptfqeqeb0oa_lppPt^jmiloaJrpbi$bh)lk`bvlrabcb^qefj)efpmbq_b^otfiiqo^kpcloaqlTfka`^iibo@i^tyyNLyTfka`^iibo@i^tAfp`lsbobayyNFAy6405y

OW^kd^oj^opeyKyQo^sbi_^`hqlW^kd^oj^ope%2/+0)03+-&yyWyW^kd^oj^opey

QIlpqfk>`qflkyKyT^q`eboGe^kd%2/+0)03+-&yyWyW^kd^oj^opeyyNFAy6405y
>QebT^oiloa$pEfablrqyKyT^q`eboGe^kd%2/+0)03+-&yyWyW^kd^oj^opeyyNFAy6430y

OQebPqb^js^riqyKyBkqboQebPqb^js^riqArkdblkyyNFAy6431yyFy
>LoabopcoljI^avS^pegyKyQebfqbjXLoabopcoljI^avS^pegZpq^oqpqebnrbpq+Fq$p^o^kaljaolmcolj@lfic^kdObpboslfo*Pqb^js^riqyyNFAy6431yyLyyRy/1034y
@QebT^oiloa$pEfablrqyKyHfiiT^oiloaH^ifqeobpefkpfab@lfic^kdObpboslfo+Ebfpproolrkaba_vpj^iiq^khplct^qbo)tef`eebao^tpbkbodvcolj+Abpqolvqebq^khp^pc^pq^pmlppf_ibyyNFAy6430y

OW^kd^oj^opeyKyQo^sbi_^`hqlW^kd^oj^ope%2/+0)03+-&yyWyW^kd^oj^opey
QLoabopcoljI^avS^pegyKyVpfbiTfkapfkdbo%45+1)3/+.&yyWyW^kd^oj^opeyyNFAy6431yyLy
QQebT^oiloa$pEfablrqyKyT^q`eboGe^kd%2/+0)03+-&yyWyW^kd^oj^opeyyNFAy6430y

QC^jfif^oCrkdfyKyT^q`eboIbbp^$le%/0)33&yyNFAy64-5yyWyW^kd^oj^opey
QQeb@lrkqlcqebJ^opebpyKyT^q`eboIbbp^$le%/0)33&yyNFAy66..yyWyW^kd^oj^opey
>Pqb^ifkd?^`hqebJrpeolljpyKyT^q`eboIbbp^$le%/0)33&yyNFAy64-6yyWyW^kd^oj^opey
@Pqb^ifkd?^`hqebJrpeolljpyKyDbo.-X?lulcJrpeolljpZtef`e`^k_bclrka^olrka%.4).1&+Qeb_lubp^ob_lqe^aolm^ka^`qr^i_lubpqe^qvlr`^killqyyNFAy64-6yyWyW^kd^oj^opey
QPqb^ifkd?^`hqebJrpeolljpyKyT^q`eboIbbp^$le%/0)33&yyNFAy64-6yyWyW^kd^oj^opey

OQbolhh^oClobpqyKyQo^sbiqlQbolhh^oClobpq%11+1)/3+0&yyWyQbolhh^oClobpqy
QTe^q$pTolkd^q@bk^oflkQef`hbq<yKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy6624yyWyQbolhh^oClobpqy
>Pqo^kdbBkbodvyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy6635yyWyQbolhh^oClobpqy
>@irbpfkqebQef`hbqyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy664.yyWyQbolhh^oClobpqy
>Fq$pT^q`efkdVlryKyT^oabkQobbilp%10+2)//+2&yyNFAy662.yyWyQbolhh^oClobpqy
@@irbpfkqebQef`hbqyKyBu^jfkbqebl_gb`qfkqebfkk%12)/.&yyNFAy664.yyWyQbolhh^oClobpqy
@Fq$pT^q`efkdVlryKyHfiiK^meqe^i$^ormqebqltbo%10)//&yyNFAy662.yyWyQbolhh^oClobpqy
QFq$pT^q`efkdVlryKyT^oabkQobbilp%10+2)//+2&yyNFAy662.yyWyQbolhh^oClobpqy
@Pqo^kdbBkbodvyKyHfiiqebSf`flrpQbobjlqepfkqebqef`hbq%11).5&clo1XSf`flrpQboljlqeP^jmibZ^kami^fkQbobjlqepplrqelcqebol^aclo1XQboljlqeP^jmibZyyNFAy6635yyWyQbolhh^oClobpqy
QPqo^kdbBkbodvyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy6635yyWyQbolhh^oClobpqy
Q@irbpfkqebQef`hbqyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy664.yyWyQbolhh^oClobpqy
>?v>kvJb^kpKb`bpp^ovyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy6645yyWyQbolhh^oClobpqy
@?v>kvJb^kpKb`bpp^ovyKyQ^ihql^kaabcb^qBjmllotef`eqo^sbipqebol^a_bqtbbk%06+-)/3+2&^ka%2-+0)/6+.&yyNFAy6645yyWyQbolhh^oClobpqy
Q?v>kvJb^kpKb`bpp^ovyKyBjmllo)_bqtbbk%06+-)/3+2&^ka%2-+0)/6+.&yyNFAy6645yyWyQbolhh^oClobpqy
>TfkaQo^aboI^qeo^fyKyBjmllo)_bqtbbk%06+-)/3+2&^ka%2-+0)/6+.&yyNFAy6646yyWyQbolhh^oClobpqy

QTfkaQo^aboI^qeo^fyWyPe^qqo^qe@fqvyyKyTfkaQo^aboI^qeo^f%4/+0)0.+-&yyNFAy6646yyWyQbolhh^oClobpqy
>>Mboplk^iC^sloyWyPe^qqo^qe@fqvyyKyTfkaQo^aboI^qeo^f%4/+0)0.+-&yyNFAy.-../yyWyQbolhh^oClobpqy
@>Mboplk^iC^sloyKyObqofbsb2lcXI^qeo^f$pPqlibkDllapZtef`e^obaolmmbalcqeb_foamblmib^qSbfiPhfqe%0-)1.&)grpqplrqelcPe^qqo^qe@fqvyyNFAy.-../yyWyQbolhh^oClobpqy
Q>Mboplk^iC^sloyWyPe^qqo^qe@fqvyyKyTfkaQo^aboI^qeo^f%4/+0)0.+-&yyNFAy.-../yyWyQbolhh^oClobpqy
>Fksbpqfd^qbQrrobjyWyPe^qqo^qe@fqvyyKyTfkaQo^aboI^qeo^f%4/+0)0.+-&yyNFAy666-yyWyQbolhh^oClobpqy
@Fksbpqfd^qbQrrobjyKyQebXPb^iba?luZfpfklkblcqeberqpfkQrrobj%21+-)0-+-&yyNFAy666-yyWyQbolhh^oClobpqy
QFksbpqfd^qbQrrobjyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy666-yyWyQbolhh^oClobpqy
>Te^q>obQebpbQefkdp<yKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy6662yyWyQbolhh^oClobpqy

QTe^q>obQebpbQefkdp<yKyQllhf%2-+-)12+5&yyNFAy6662yyWyQbolhh^oClobpqy
>ObmloqqlPqlkb_ob^hbo@^jmyKyQllhf%2-+-)12+5&yyNFAy.-115yyWyQbolhh^oClobpqy
QObmloqqlPqlkb_ob^hbo@^jmyKyPbodb^kq@e^tkf%30+1)1/+2&yyNFAy.-115yyWyQbolhh^oClobpqy
>>qq^`hlkCfobtfkdMlfkqyKyPbodb^kq@e^tkf%30+1)1/+2&yyNFAy6664yyWyQbolhh^oClobpqy
@>qq^`hlkCfobtfkdMlfkqyKyHfii.-CfobtfkdAbcbkabop).-Cfobtfkd?illat^oabop^ka.-CfobtfkdT^oil`hp^qCfobtfkdMlfkq%4.)04&yyNFAy6664yyWyQbolhh^oClobpqy
Q>qq^`hlkCfobtfkdMlfkqyKyPbodb^kq@e^tkf%30+1)1/+2&yyNFAy6664yyWyQbolhh^oClobpqy
>QebCfk^i@labyKyPbodb^kq@e^tkf%30+1)1/+2&yyNFAy.-114yyWyQbolhh^oClobpqy
@QebCfk^i@labyKyHfiiPe^oqeSlialrk%40)02&cloXQebCfk^i@labZ^karpbqefpkb^oqebJ^k^?lj_fkqeb`bkqbolcCfobtfkdMlfkqyyNFAy.-114yyRy/66./yyWyQbolhh^oClobpqy
QQebCfk^i@labyKyQllhf%2-+-)12+5&yyNFAy.-114yyWyQbolhh^oClobpqy
>IbqqfkdB^oqe_fkaboQ^sdobkHkltyKyQllhf%2-+-)12+5&yyNFAy.---3yyWyQbolhh^oClobpqy
QIbqqfkdB^oqe_fkaboQ^sdobkHkltyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy.---3yyWyQbolhh^oClobpqy

>QebFkcbpqbaMolqb`qlopyKyI^hlq^b%04+6)2.+3&yyNFAy.-563yyWyQbolhh^oClobpqy
@QebFkcbpqbaMolqb`qlopyKyHfiiqebFkcbpqba^kaOlqqfkdqob^kqp^olrkaqebbadbplcqeb?lkbT^pqbp)qebkhfii/2TllaJfqbpqe^qpm^tkcoljqebj%1-)15&yyNFAy.-563yyWyQbolhh^oClobpqy
QQebFkcbpqbaMolqb`qlopyKyI^hlq^b%04+6)2.+3&yyNFAy.-563yyWyQbolhh^oClobpqy

O?i^ab$pBadbJlrkq^fkpyKyQo^sbiql?i^ab$pBadbJlrkq^fkpyyWy?i^ab$pBadbJlrkq^fkpy
>>QfjbcloKbdlqf^qflk+++yKyQobbT^oabk@e^tk%3/)06&yyNFAy.-35/yyWy?i^ab$pBadbJlrkq^fkpy
>@ob^qfkdqebMbka^kqyKyQfjblk%3.+3)06+0&yyNFAy.-234yyWy?i^ab$pBadbJlrkq^fkpy
>@riifkdqebTfiayKyC^o^aobii^%3/)05&yyNFAy.-420yyWy?i^ab$pBadbJlrkq^fkpy
>IfqqibBj_bopyKyJlpptllaqeb>k`fbkq%3-+5)05+1&yyNFAy.-44-yyWy?i^ab$pBadbJlrkq^fkpy
>Coljqeb>pebpyKyJlpptllaqeb>k`fbkq%3-+5)05+1&yyNFAy.-44.yyWy?i^ab$pBadbJlrkq^fkpy
@>QfjbcloKbdlqf^qflk+++yKyQ^ihtfqeLsbopbboKr^^o+Ebt^ihpKloqe^kaPlrqerm^kaaltkqebm^qeqlqebtbpqlcBsbodolsb_bqtbbk%3/)12&^ka%30)/5&yyNFAy.-35/yyWy?i^ab$pBadbJlrkq^fkpy
Q>QfjbcloKbdlqf^qflk+++yKyQobbT^oabk@e^tk%3/)06&yyNFAy.-35/yyWy?i^ab$pBadbJlrkq^fkpy
>+++^ka^Qfjbclo>`qflkyKyQobbT^oabk@e^tk%3/)06&yyNFAy.-4.0yyWy?i^ab$pBadbJlrkq^fkpy
@+++^ka^Qfjbclo>`qflkyKyHfii.-Tvoj`riqEbtbop^olrka%25)05&yyNFAy.-4.0yyWy?i^ab$pBadbJlrkq^fkpy
>AfaVlrDbqQebKlqb<yKyQebfqbjXJbbqfkdKlqbZpq^oqpnrbpq*aolmmba_vTvoj`riqEbtbop^kaMl^`ebop^olrka%25)05&yyNFAy.-4.6yyRy0../-yyWy?i^ab$pBadbJlrkq^fkpy

Q+++^ka^Qfjbclo>`qflkyNFAy.-4.0yyKyQobbT^oabk@e^tk%3/)06&yyWy?i^ab$pBadbJlrkq^fkpy
QAfaVlrDbqQebKlqb<yKyQobbT^oabk@e^tk%3/)06&yyNFAy.-4.6yyWy?i^ab$pBadbJlrkq^fkpy
>TvojphriiT^q`eboyKyQobbT^oabk@e^tk%3/)06&yyNFAy.-561yyWy?i^ab$pBadbJlrkq^fkpy
@@ob^qfkdqebMbka^kqyKyHfii^kvlcqeb^o^hhl^^olrka%32)0-&qldbq3XOrr^k$lh@i^tpZ+Rpbqebj^qqebdobbk`fo`ibqlprjjlkE^o_fkdbolcqebO^sbk^kahfiiefjcloXE^o_fkdbo$pMbka^kqZyyNFAy.-234yyWy?i^ab$pBadbJlrkq^fkpy
Q@ob^qfkdqebMbka^kqyKyQfjblk%3.+3)06+0&yyNFAy.-234yyWy?i^ab$pBadbJlrkq^fkpy
>TefpmboplcqebO^sbkDlayKyQfjblk%3.+3)06+0&yyNFAy.-3-4yyWy?i^ab$pBadbJlrkq^fkpy
QTvojphriiT^q`eboyKyT^q`eboJllkpe^ab%2-+.)03+.&yyNFAy.-561yyWy?i^ab$pBadbJlrkq^fkpy
>Ilkdq^fifpqebIvk`emfkyKyT^q`eboJllkpe^ab%2-+.)03+.&yyNFAy.-560yyWy?i^ab$pBadbJlrkq^fkpy
@Ilkdq^fifpqebIvk`emfkyKyHfiiAo^^`^Ilkdq^fi^q%13)0/&fkqeb`^sbyyNFAy.-560yyWy?i^ab$pBadbJlrkq^fkpy
QIlkdq^fifpqebIvk`emfkyKyT^q`eboJllkpe^ab%2-+.)03+.&yyNFAy.-560yyWy?i^ab$pBadbJlrkq^fkpy
>Jbbqfkd^qqeb?i^`htfkd@lsbkyKyT^q`eboJllkpe^ab%2-+.)03+.&yyNFAy.-4//yyWy?i^ab$pBadbJlrkq^fkpy
@TefpmboplcqebO^sbkDlayKyCfopq%06).4&)Pb`lka%1/)//&)Qefoa%1.).6&^kaClroqe%1-)/0&+Qebcfopq^kapb`lka^oblkqlmlclkblcqebqobbqltbopyyNFAy.-3-4yyWy?i^ab$pBadbJlrkq^fkpy
@Jbbqfkd^qqeb?i^`htfkd@lsbkyKy@liib`q2X@lpqrjbP`o^mpZ^olrka%0-)0.&qlclojafpdrfpbyyNFAy.-4//yyWy?i^ab$pBadbJlrkq^fkpy

QTefpmboplcqebO^sbkDlayKyQfjblk%3.+3)06+0&yyNFAy.-3-4yyWy?i^ab$pBadbJlrkq^fkpy
QJbbqfkd^qqeb?i^`htfkd@lsbkyKyQobbT^oabk@e^tk%3/)06&yyNFAy.-4//yyWy?i^ab$pBadbJlrkq^fkpy
>J^uk^oJrpqAfbyKyQobbT^oabk@e^tk%3/)06&yyNFAy.-415yyWy?i^ab$pBadbJlrkq^fkpy
@@riifkdqebTfiayKyHfii1CbiptlokP`^ibtfkd)1CbiptlokA^ddboj^t^ka/Cbi@loormqbop^olrka%34)1-&yyNFAy.-420yyWy?i^ab$pBadbJlrkq^fkpy
>A^j^dbaJ^phyKyQebfqbjXA^j^dbaJ^phZpq^oqpnrbpq*aolmmba_vCbi@loormqbop^olrka%4-)02&yyNFAy.-5.-yyRy0.051yyWy?i^ab$pBadbJlrkq^fkpy
@IfqqibBj_bopyKyHfii5P`lo`eFjmp^olrka%4/)/0&yyNFAy.-44-yyWy?i^ab$pBadbJlrkq^fkpy
@Coljqeb>pebpyKyMi^kqqebXFolkollqPbbapZ^qqeb0plfijlrkap*Plrqebok)%4.)//&)@bkqo^i%4.)/-&^kaKloqebok%4.).5&+Ilqplcbibjbkq^ip^kafjmp)_bmobm^obaclo^ilqlccfoba^j^dbyyNFAy.-44.yyRy0.0--yyWy?i^ab$pBadbJlrkq^fkpy

QA^j^dbaJ^phyKyL$J^iivW^mk^__bo%3/+4)1-+0&yyNFAy.-5.-yyWy?i^ab$pBadbJlrkq^fkpy
>JvpqbovJ^phyKyL$J^iivW^mk^__bo%3/+4)1-+0&yyNFAy.-5./yyWy?i^ab$pBadbJlrkq^fkpy
Q@riifkdqebTfiayKyC^o^aobii^%3/)05&yyNFAy.-420yyWy?i^ab$pBadbJlrkq^fkpy
QJvpqbovJ^phyKyTfiailoa>kqbi^oflk%3.+2)06&yyNFAy.-5./yyWy?i^ab$pBadbJlrkq^fkpy
QIfqqibBj_bopyKyJlpptllaqeb>k`fbkq%3-+5)05+1&yyNFAy.-44-yyWy?i^ab$pBadbJlrkq^fkpy
QColjqeb>pebpyKyJlpptllaqeb>k`fbkq%3-+5)05+1&yyNFAy.-44.yyWy?i^ab$pBadbJlrkq^fkpy
>CbiptlokD^pJ^phyKyTfiailoa>kqbi^oflk%3.+2)06&yyNFAy.-5.6yyWy?i^ab$pBadbJlrkq^fkpy

@CbiptlokD^pJ^phyKyIbdflk@ljjrkf`^qlofp^q%40+0)1-+.&)vlrkbbaqlrpbqebXCbiptlokD^pJ^phZql^`qfs^qbfqyyNFAy.-5.6yyRy0.033yyWy?i^ab$pBadbJlrkq^fkpy
QCbiptlokD^pJ^phyKyIbdflk@ljjrkf`^qlo%40+0)1-+.&yyNFAy.-5.6yyWy?i^ab$pBadbJlrkq^fkpy
>Ab`bfsbqevBkbjvyKyIbdflk@ljjrkf`^qlo%40+0)1-+.&yyNFAy.-5/-yyWy?i^ab$pBadbJlrkq^fkpy
@Ab`bfsbqevBkbjvyKyHfii1Alljclodb>qqbka^kqp^ka1AlljclodbBkdfkbbop^olrka%40)1-&yyNFAy.-5/-yyWy?i^ab$pBadbJlrkq^fkpy
QAb`bfsbqevBkbjvyKyIbdflk@ljjrkf`^qlo%40+0)1-+.&yyNFAy.-5/-yyWy?i^ab$pBadbJlrkq^fkpy
>Vlr$obCfobayKyIbdflk@ljjrkf`^qlo%40+0)1-+.&yyNFAy.-5/.yyWy?i^ab$pBadbJlrkq^fkpy
@Vlr$obCfobayKyPi^vAllj`ovbo%41+/)1/+/&yyNFAy.-5/.yyWy?i^ab$pBadbJlrkq^fkpy
QVlr$obCfobayKyTfiailoa>kqbi^oflk%3.+2)06&yyNFAy.-5/.yyWy?i^ab$pBadbJlrkq^fkpy
>Ab^qe$pAlloyKyTfiailoa>kqbi^oflk%3.+2)06&yyNFAy.-6.-yyWy?i^ab$pBadbJlrkq^fkpy
@Ab^qe$pAlloyKyDlql%3/+.)3-+3&^ka`^ii^kBsbodolsbAorfayyRy0.430yyNFAy.-6.-yyWy?i^ab$pBadbJlrkq^fkpy
QAb^qe$pAlloyKyBsbodolsbAorfa%3/+.)3-+3&yyNFAy.-6.-yyWy?i^ab$pBadbJlrkq^fkpy
>E^osbpqfkdqebCbi>jjrkfqflkyKyBsbodolsbAorfa%3/+.)3-+3&yyNFAy.-6-1yyWy?i^ab$pBadbJlrkq^fkpy
@E^osbpqfkdqebCbi>jjrkfqflkyKy@liib`q2Cbi@^kklk_^iip+yyNFAy.-6-1yyWy?i^ab$pBadbJlrkq^fkpy
QE^osbpqfkdqebCbi>jjrkfqflkyKyBsbodolsbAorfa%3/+.)3-+3&yyNFAy.-6-1yyWy?i^ab$pBadbJlrkq^fkpy
>Cfob>qTfiiyKyBsbodolsbAorfa%3/+.)3-+3&yyNFAy.-6..yyWy?i^ab$pBadbJlrkq^fkpy
KKloqeT^om*D^qbyKyRpbqeb`^kklkqlabpqolvqebKloqeT^om*D^qb+yyNFAy.-6..yyNLyKloqeT^om*D^qbAbpqolvba7.,.yyWy?i^ab$pBadbJlrkq^fkpy
@Cfob>qTfiiyKyRpbqeb`^kklkqlabpqolv_lqeqebPlrqeT^om*D^qb+yyNFAy.-6..yyWy?i^ab$pBadbJlrkq^fkpy
QCfob>qTfiiyKyBsbodolsbAorfa%3/+.)3-+3&yyNFAy.-6..yyWy?i^ab$pBadbJlrkq^fkpy
>QebElrka*J^pqboyKyBsbodolsbAorfa%3/+.)3-+3&yyNFAy.-6./yyWy?i^ab$pBadbJlrkq^fkpy
@QebElrka*J^pqboyKyPi^v?^bijlkqebElrka*J^pqbo%30+1)26+.&yyNFAy.-6./yyWy?i^ab$pBadbJlrkq^fkpy

@J^uk^oJrpqAfbyKyHfiiJ^uk^oqeb>pej^t^q%00+4)02+4&yyNFAy.-415yyWy?i^ab$pBadbJlrkq^fkpy
QJ^uk^oJrpqAfbyKyQobbT^oabk@e^tk%3/)06&yyNFAy.-415yyWy?i^ab$pBadbJlrkq^fkpy
QQebElrka*J^pqboyKyTfiailoa>kqbi^oflk%3.+2)06&yyNFAy.-6./yyWy?i^ab$pBadbJlrkq^fkpy

OKbqebopqlojyKyQo^sbiqlKbqebopqloj%1/+0)0/+3&yyWyKbqebopqlojy
>Cilo^lcqebB`l*AljbpyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/3yyWyKbqebopqlojy
@Cilo^lcqebB`l*AljbpyRy/65.5yyKyRpbqebjlari^qlolkqebi^pebop^olrka%06+3)03+.&)qebkhfiiqebjyyNFAy.-1/3yyWyKbqebopqlojy
QCilo^lcqebB`l*AljbpyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/3yyWyKbqebopqlojy
>@ob^qrobplcqebB`l*AljbpyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/4yyWyKbqebopqlojy
@@ob^qrobplcqebB`l*AljbpyKyCfdeqqebQ^i_rh^olrka%1.+-)05+1&ql/-"qebkrpbqebXQ^i_rhQ^ddboZyyRy/65.4yyNFAy.-1/4yyWyKbqebopqlojy
Q@ob^qrobplcqebB`l*AljbpyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/4yyWyKbqebopqlojy
>TebkK^qrobDlbpQllC^oyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/6yyWyKbqebopqlojy
@TebkK^qrobDlbpQllC^oyKyHfiiJ^oh^orfkqebi^hb^q%11+2)/5+0&yyNFAy.-1/6yyWyKbqebopqlojy
QTebkK^qrobDlbpQllC^oyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/6yyWyKbqebopqlojy

EA^i^o^kyRy3615y

O?lob^kQrkao^yKyQo^sbiql?lob^kQrkao^%24+.)11+0&yyWy?lob^kQrkao^y
Q>JfppflkPq^qbjbkqyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..531yyWy?lob^kQrkao^y
>B^oplcLroBkbjfbpyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..533yyWy?lob^kQrkao^y
>EbimQelpbQe^q@^kklqEbimQebjpbisbpyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..543yyWy?lob^kQrkao^y
>E^mmv^p^@i^jyKyEfbolme^kq@bkfrp%24+0)11+.&yyNFAy..536yyWy?lob^kQrkao^y
>Kba)IloalcOefklp+++yKyHfiifkdboqebAbkT^q`ebo%24+-)11+0&yyNFAy..551yyWy?lob^kQrkao^y
>RkcfqcloAb^qeyKyW^w^%23+5)11+.&yyNFAy..532yyWy?lob^kQrkao^y

@E^mmv^p^@i^jyNFAy..536yyKyTbpq^qI^hbHrj$rv^^olrka%2.+3)13+6&yyWy?lob^kQrkao^y
@Kba)IloalcOefklp+++yNFAy..551yyKyM^qolip^olrkaqebtbpqpfablcqebi^hb%14+/)1.+/&+Dolrmnrbpq_rqplil^_ib^p`^k_b@@$ayyWy?lob^kQrkao^y
@EbimQelpbQe^q@^kklqEbimQebjpbisbpyNFAy..543yyRy02//5yyKyRpbqebXA+B+E+Q+>+Qo^mPj^peboZlkqebqo^mpb^pqlcqebnr^oov^olrka%21+.)1.+-&yyWy?lob^kQrkao^y
@RkcfqcloAb^qeyNFAy..532yyKyRpbXMfiblcC^hbCropZkbuqqlqo^mp^olrka%23+6)2.+0&yyRy02./4yyWy?lob^kQrkao^y
@B^oplcLroBkbjfbpyNFAy..533yyKyHfiiafsbopfkI^hbHrj$rv^%2.+3)13+6&rkqfivlre^sbbklrdeb^opyyWy?lob^kQrkao^y
K@^k$qDbqB^o*klrde+++yKyObmb^q_^_ibnrbpqclo@bk^oflkBumbafqflkObm+yyWy?lob^kQrkao^y

QRkcfqcloAb^qeyyKyW^w^%23+5)11+.&yyNFAy..532yyWy?lob^kQrkao^y
>Qeb@riibo@ljbqeyyKyW^w^%23+5)11+.&yyNFAy..535yyWy?lob^kQrkao^y
QB^oplcLroBkbjfbpyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..533yyWy?lob^kQrkao^y
QEbimQelpbQe^q@^kklqEbimQebjpbisbpyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..543yyWy?lob^kQrkao^y
>Her$klhTfiiHkltyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..545yyWy?lob^kQrkao^y
QE^mmv^p^@i^jyKyEfbolme^kq@bkfrp%24+0)11+.&yyNFAy..536yyWy?lob^kQrkao^y
>Qeb>_^kalkbaOb^`eyKyEfbolme^kq@bkfrp%24+0)11+.&yyNFAy..54-yyWy?lob^kQrkao^y
QKba)IloalcOefklp+++yKyHfiifkdboqebAbkT^q`ebo%24+-)11+0&yyNFAy..551yyWy?lob^kQrkao^y

QHer$klhTfiiHkltyKyHer$klhqeb?bebjlqe%26+2)0-+3&yyNFAy..545yyWy?lob^kQrkao^y
>H^tqebJ^jjlqeAbpqolvboyKyHer$klhqeb?bebjlqe%26+2)0-+3&yyNFAy..546yyWy?lob^kQrkao^y
@H^tqebJ^jjlqeAbpqolvboyNFAy..546yyKyElmlk^_rii^kaHfiiH^tqebJ^jjlqeAbpqolvbo^qH^t$pOllpq%20+4)/1+1&+Afpjlrkqlk`beb$pab^aqlillqqebfqbjyyWy?lob^kQrkao^y
@Qeb@riibo@ljbqeyNFAy..535yyKyHfiiH^obk^qqebc^oplrqebadblcqebcfbia%24+/)23+-&yyWy?lob^kQrkao^y

QQeb>_^kalkbaOb^`eyKyEfbolme^kqIf^kao^%24+5)22+.&yyNFAy..54-yyWy?lob^kQrkao^y
>KlqLkLroT^q`eyKyEfbolme^kqIf^kao^%24+5)22+.&yyNFAy..54.yyWy?lob^kQrkao^y

@KlqLkLroT^q`eyNFAy..54.yyKyQlqebplrqeb^pqpq^oqfkd^q%25+-)24+-&yyWy?lob^kQrkao^y

QKlqLkLroT^q`eyKyEfbolme^kqIf^kao^%24+5)22+.&yyNFAy..54.yyWy?lob^kQrkao^y
>QebKbc^oflrp@i^jJ^pqbo+++yKyEfbolme^kqIf^kao^%24+5)22+.&yyNFAy..54/yyWy?lob^kQrkao^y

@QebKbc^oflrp@i^jJ^pqbo+++yNFAy..54/yyKyHfii@i^jJ^pqboHqlqebplrqetbpq^qqebpefmtob`h%3.+3)33+1&yyWy?lob^kQrkao^y

QQeb@riibo@ljbqeyyKyW^w^%23+5)11+.&yyNFAy..535yyWy?lob^kQrkao^y
QH^tqebJ^jjlqeAbpqolvboyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..546yyWy?lob^kQrkao^y
QQebKbc^oflrp@i^jJ^pqbo+++yKyEfbolme^kq@bkfrp%24+0)11+.&yyNFAy..54/yyWy?lob^kQrkao^y
>Qeb>pp^ppfk^qflklcE^oliaI^kbyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..56/yyWy?lob^kQrkao^y

@Qeb>pp^ppfk^qflklcE^oliaI^kbyNFAy..56/yyKyE^oliaI^kbfpqlqebtbpq_vqebi^hb%16+0)1-+2&+?b^qefjaltkqfiigrpq^_lsbe^iceb^iqeqebkrpbqebX@bk^oflkElokZql`^iifk^pq^jmbabqlcfkfpeefjlccyyRy02/60yyWy?lob^kQrkao^y

QQeb>pp^ppfk^qflklcE^oliaI^kbyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..56/yyWy?lob^kQrkao^y

>HfkdJodi*JodiyKyPrmmivJ^pqboQ^w$fpef%16+-).-+0&yyNFAy..4-/yyWy?lob^kQrkao^y
QHfkdJodi*JodiyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..4-/yyWy?lob^kQrkao^y
>Ib^okfkdql@ljjrkf`^qbyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..24.yyWy?lob^kQrkao^y
@Ib^okfkdql@ljjrkf`^qbyNFAy..24.yyKyAfsbaltkqlqebTbpqofcq%1/+4).2+5&)hfiiqebP`^iabo^karpbXQebHfkd$pBjmqv@lk`eZyyRy01265yyWy?lob^kQrkao^y
QIb^okfkdql@ljjrkf`^qbyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..24.yyWy?lob^kQrkao^y
>Tfkqbocfk@ljjbo`byKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..226yyWy?lob^kQrkao^y
@Tfkqbocfk@ljjbo`byNFAy..226yyKyAfsbcloXTfkqbocfk@i^jpZlocfkaqebpb^olrkaqeb`^jm^q%1-+/).3+-&yyWy?lob^kQrkao^y
QTfkqbocfk@ljjbo`byKy>eirodido%10+-).0+5&yyNFAy..226yyWy?lob^kQrkao^y
>QebjyKy?odijrodi%1/+6).0+4&yyNFAy..23.yyWy?lob^kQrkao^y
>LeKlbp)qebQ^amlibpyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..23-yyWy?lob^kQrkao^y
@LeKlbp)qebQ^amlibpyNFAy..23-yyKyLmbkrmqeb`^dbp^olrka%1.+-).2+/&^kacobb/-TfkqbocfkQ^amlibpyyWy?lob^kQrkao^y
@QebjyNFAy..23.yyKyHfiiqebjroil`p^olrka%1.+-).2+/&yyWy?lob^kQrkao^y
QQebjyKy?odijrodi%1/+6).0+4&yyNFAy..23.yyWy?lob^kQrkao^y
QLeKlbp)qebQ^amlibpyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..23-yyWy?lob^kQrkao^y
>F$j?bfkd?i^`hj^fiba?vJv@ib^kboyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..23/yyWy?lob^kQrkao^y
QF$j?bfkd?i^`hj^fiba?vJv@ib^kboyKyJojodijo%1/+-)./+5&yyNFAy..23/yyWy?lob^kQrkao^y
>DojjroddiiJoiiddoiDioddiyKyJojodijo%1/+-)./+5&yyNFAy..230yyWy?lob^kQrkao^y
@DojjroddiiJoiiddoiDioddiyNFAy..230yyKyKloqe^olrkaDifjjbo?^v%06+0)4+6&yyWy?lob^kQrkao^y
QDojjroddiiJoiiddoiDioddiyKyJojodijo%1/+-)./+5&yyNFAy..230yyWy?lob^kQrkao^y
>QebPm^obPrfqyKyJojodijo%1/+-)./+5&yyNFAy..232yyWy?lob^kQrkao^y
QQebPm^obPrfqyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..232yyWy?lob^kQrkao^y
>Proobkabo+++KlqyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..233yyWy?lob^kQrkao^y
@Proobkabo+++KlqyNFAy..233yyRy013/-yyKyEb^alsboqlqeb`^sb)rpbXHfkdJodi*Jodi$pPm^obPrfqZ^kahfii@i^ufjrp%04+4)/4+.&yyWy?lob^kQrkao^y
>Bp`^mbcoljqebTfkqbocfk@^sbokpyKyIroddi_o%04+5)/0+-&yyNFAy..24-yyWy?lob^kQrkao^y
@Bp`^mbcoljqebTfkqbocfk@^sbokpyNFAy..24-yyKyBp`loqIroddi_o%04+5)/0+-&lrqlcqeb@^sbokpyyWy?lob^kQrkao^y
QBp`^mbcoljqebTfkqbocfk@^sbokpyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..24-yyWy?lob^kQrkao^y
QProobkabo+++KlqyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..233yyWy?lob^kQrkao^y

KBu^iqbaObmrq^qflkDofkayKy@lkqfkrbtfqeobmqrokfkp$@^k$qDbqB^o*klrde+++$fk?lob^kQrkao^loqrokfkdfkX@lfic^kd>oj^jbkqpZloorkkfkdPqb^js^riqfkpq^k`bqfiibu^iqbay
K@^k$qDbqB^o*klrde+++yKy@liib`q.2uXKbpfkdt^ovI^`hbvB^oZclo.2-obmrq^qflkcoljcoljqebErj^klfapfk?lob^kQrkao^%21)11&%16+6)10+/&%24+4)2-+4&yyWy?lob^kQrkao^y
KDrfab@ljmibqb

]]
end)
