DugisGuideViewer:RegisterGuide("Cenarion Circle Reputation (60+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabtfiidllsbo^iiqebnrbpqpkbbabaqldbqqebDr^oaf^klc@bk^ofrp>`efbsbjbkq%Bu^iqbatfqe@bk^oflk@fo`ib^ka@bk^oflkBumbafqflk+Lk`b^iiqebnrbpqp^obalkbclo^m^oqf`ri^oc^`qflk)qebkfpgrpqdofkafkdlrqqebobmb^q^_ibarkdblkp,qrok*fkpqldbqqlBu^iqba+Qefpdrfab^pprjbpqe^qvlr^obibsbi5-)pljblcqebarkdblkp^obe^oaqlplilrkabo5-+y
KIltIbsbiNrbpqpyKyJ^hbprobvlr^obqo^hfkdiltibsbinrbpqpqlj^hbfqb^pfboqlpbbqebnrbpqpdfsbop+>ipl)j^hbprobvlre^sbafp`lsboaAfobJ^riqebfkpq^k`b)lovlrtlk$q_b^_ibql^``bmq^`lrmiblcnrbpqp+Grpqorkrmqebpqbm^kafk^ifqqibt^vp+y

eA^i^o^kyKyJ^hbA^i^o^kvlroeljb%32+3)0/+/&+Dbqqfkdql^kacoljqebpbil`^qflktfii_bb^pfbocoljA^i^o^k+yyWyA^i^o^ky
ORkabo`fqvyKyQ^hbmloq^i%22+2)/0+5&fkA^i^o^kqlRkabo`fqvyyWyA^i^o^ky

CQeb?rit^ohyKyJf`e^biD^oobqq%30+2)15+4&yyWyRkabo`fqvy
>QebTfiaifcbPrccbopQll%M^oq.&yKyJridofpAbbmofsbo%20+4)31+4&yyNFAy1651yyWyTbpqbokMi^drbi^kapy
@QebTfiaifcbPrccbopQll%M^oq.&yKyAbpqolv5Afpb^pbaTlisbpqlqebkloqe)_bqtbbkqebCbipqlkb^kaA^iplk$pCfbiap%12)0-&yyNFAy1651yyWyTbpqbokMi^drbi^kapy
QQebTfiaifcbPrccbopQll%M^oq.&yKyJridofpAbbmofsbo%20+4)31+4&yyNFAy1651yyWyTbpqbokMi^drbi^kapy
>QebTfiaifcbPrccbopQll%M^oq/&yKyJridofpAbbmofsbo%20+4)31+4&yyNFAy1652yyWyTbpqbokMi^drbi^kapy
@QebTfiaifcbPrccbopQll%M^oq/&yKyAbpqolv5Afpb^pbaDofwwifbpqlqebb^pq%20)15&yyNFAy1652yyWyTbpqbokMi^drbi^kapy
QQebTfiaifcbPrccbopQll%M^oq/&yKyJridofpAbbmofsbo%20+4)31+4&yyNFAy1652yyWyTbpqbokMi^drbi^kapy

EA^i^o^kyRy3615y
OQerkabo?irccyKyQ^hbmloq^i%22+/)/2+3&fkA^i^o^kqlQerkabo?irccyyWyA^i^o^ky

>QebKbtColkqfboyKy?irccOrkkboTfkapqofabo%10+.)3.+/&%05+5)2.+4&%23+4)22+/&yyNFAy.---yyWyQerkabo?irccy
QQebKbtColkqfboyKy>o`eAorfaE^jrriOrkbqlqbj%45+2)/5+2&yyNFAy.---yyWyQerkabo?irccy
>O^_fkbP^qrok^yKy>o`eAorfaE^jrriOrkbqlqbj%45+2)/5+2&yyNFAy../0yyWyQerkabo?irccy

CAbpli^`byKyQ^i%13+5)16+1&yyWyQerkabo?irccy
>@loormqflklcB^oqe^kaPbbayKyPbibkao^%/3+6)44+4&yyNFAy4-31yyWyAbpli^`by
@@loormqflklcB^oqe^kaPbbayKyPi^vMofk`bppQebo^ao^p+Pebfpqebbka_lppfkJ^o^ralk7MofpqfkbT^qbop+yyNFAy4-31yyWyAbpli^`by
>PbbalcIfcbyKyW^bq^o$pPmfofq+EbfpclrkafkJ^o^ralk^cqbovlrhfiiMofk`bppQebo^ao^p+yyNFAy4-33y
Q@loormqflklcB^oqe^kaPbbayKyPbibkao^%/3+6)44+4&yyNFAy4-31yyWyAbpli^`by

C?illasbkljMlpqyKyQe^ilk%/.+3)41+-&yyWyAbpli^`by
OJllkdi^abyKyOrkqeolrdeQfj_boj^tEliaqlJllkdi^ab%2.+4)11+6&FcqebQfj_boj^t^obelpqfib)ptfq`eqlQebAfmilj^qdrfab^kadofkaobmrkqfiqebv^obRkcofbkaiv)qebkvlr`^korkqeolrdeqebqrkkbirke^ojba+yyWyJllkdi^aby

QO^_fkbP^qrok^yKyO^_fkbP^qrok^%2.+4)11+6&yyNFAy../0yyWyJllkdi^aby
>T^pqbi^kayKyO^_fkbP^qrok^%2.+4)11+6&yyNFAy../1yyWyJllkdi^aby
KQ^ihqlO^_fkbyKyFcvlre^sbafp`lsbobaAfobJ^riqebobpelria_b^af^ildrblmqflk+Hbbmq^ihfkdqlO^_fkbrkqfiebe^pqebcliiltfkdnrbpq^s^fi^_ib+y
>>Obifnr^ovlcMrofqvyKyO^_fkbP^qrok^%2.+4)11+6&yyNFAy22/4yyWyJllkdi^aby
QPbbalcIfcbyKyHbbmboObjrilp%03+2)1/+.&yyNFAy4-33yyWyJllkdi^aby

EA^i^o^kyRy3615y
O@^sbokplcQfjbyKyQ^hbMloq^ifkA^i^o^k%Sflibq@fq^abi&ql@^sboklcQfjb%/2+4)2.+/&yyWyA^i^o^ky
OD^adbqw^kyKyQo^sbiqlD^adbqw^k%2.+3)/2+2&yyWyQ^k^ofpy
C@bk^oflkEliayKy?rihobhO^dbcfpq%2.+3)/2+2&yyWyQ^k^ofpy
>>robiDliaib^cyKyErrjTfiaj^kb%15+3)04+4&yyNFAy500.yyWyPfifqerpy
>QtfifdeqDbliloapyKyErrjTfiaj^kb%15+3)04+4&yyNFAy50/-yyWyPfifqerpy
>Pb`obq@ljjrkf`^qflkyKy?loTfiaj^kb%15+3)04+4&yyNFAy50.5yyWyPfifqerpy
>>_vpp^i@lkq^`qpyKy?loTfiaj^kb%15+3)04+4&yyNFAy503.yyWyPfifqerpy
>ObmloqqlDbkbo^iHfofh^yKyP`lrq?illacfpq%15+6)03+4&yyNFAy61.3yyWyPfifqerpy
>Ab^obpqK^q^if^yKy@ljj^kaboJ^o$^ifqe%16+0)01+3&yyNFAy50-1yyWyPfifqerpy
>QebQtfifdeqJvpqbovyKyDblildfpqI^ohp_^kb%16+4)04+0&yyNFAy5/51yyWyPfifqerpy
>CfbiaArqvyKyTfka`^iiboH^ialk%2-+-)03+2&yyNFAy540.yyWyPfifqerpy
>@bk^oflk?^qqibdb^oyKyTfka`^iiboH^ialk%2-+-)03+2&yyNFAy55--yyWyPfifqerpy
>Pb`rofkdqebPrmmivIfkbpyKyTfka`^iiboMolraelok%2.+.)05+4&yyNFAy5/5-yyWyPfifqerpy
>T^kqba*Ab^qe`i^pm)QboololcqebP^kapyKyT^kqbaPfdk%2.+0)05+/&yyNFAy5/50yyWyPfifqerpy
Q@bk^oflk?^qqibdb^oyKyS^odrp%2.+0)05+6&yyNFAy55--yyWyPfifqerpy
>Ab^aivAbpboqSbkljyKy?bbqfuCf`hibpmo^dd%2.+4)05+4&yyNFAy5/44yyWyPfifqerpy
Q>robiDliaib^cyKy>robiDliaib^c%2.+6)05+-&yyNFAy500.yyWyPfifqerpy

QT^pqbi^kayKyI^vlPq^opqofhb%5.+5).5+5&yyNFAy../1yyWyPfifqerpy
>QebPmfofqplcPlrqetfkayKyI^vlPq^opqofhb%5.+5).5+5&yyNFAy../2yyWyPfifqerpy
@QebPmfofqplcPlrqetfkayKyPi^v5QloqrobaAorfap^ka5QloqrobaPbkqfkbipfkPlrqetfkaSfii^db%30+-)2-+6&+yyNFAy../2yyWyPfifqerpy
@>Obifnr^ovlcMrofqvyKyCfkaXObifnr^ovlcMrofqvZ%30+/)22+0&tfqefkqeborfkplcPlrqetfkaSfii^dbfkPfifqerp+yyNFAy22/4yyIy///-.yyWyJllkdi^aby
@Pb`rofkdqebPrmmivIfkbpyKyHfii.2AobadbPqofhbop+Clrka^iilsboKloqebokPfifqerp+yyNFAy5/5-yyWyPfifqerpy
@Ab^aivAbpboqSbkljyKyd^qebo5Pqlkbi^peP`lomfaPqfkdbop^ka5P^kaPhfqqboboC^kdp+Jl_p^obclrka^iilsbokloqebokPfifqerpyyNFAy5/44yyWyPfifqerpy
KP^sbQtfifdeqFqbjpyKyP^sbqebQtfifdeq$pE^jjbo@riqfpqp`lti)j^kqib)^kaol_bp+>iplhbbm^iiXBk`ovmqbaQtfifdeqQbuqZcloobmqrok*fkp+y
@QtfifdeqDbliloapyKyPi^v.-QtfifdeqDbliloap%06+-)10+2&%/1+1)0/+3&yyNFAy50/-yyWyPfifqerpy
@Pb`obq@ljjrkf`^qflkyKyPi^vQtfifdeq$pE^jjbo@riqfpqp%06+-)10+2&%/1+1)0/+3&clo.-XBk`ovmqbaQtfifdeqQbuqZ+yyNFAy50.5yyWyPfifqerpy
@>_vpp^i@lkq^`qpyKy@liib`qQtfifdeq@riqfpq`lti)j^kqib)^kaol_bp+MrqlkQtfifdeq@riqfpqpbq^kaprjjlk^Qbjmi^ocolj^ibppbopqlkb%05+/)13+0&%/1+2)02+6&+AbpqolvqebQbjmi^o^kaillqX>_vpp^i@obpqZ+yyNFAy503.yyWyPfifqerpy
@QebQtfifdeqJvpqbovyKy@liib`q5QtfifdeqQ^_ibqCo^djbkqp%/-).2+1&%21+.)6+5&%//+-).-+1&yyNFAy5/51yyWyPfifqerpy

QAb^aivAbpboqSbkljyKy?bbqfuCf`hibpmo^dd%2.+4)05+4&yyNFAy5/44yyWyPfifqerpy
>Klddib$pI^pqElmbyKy?bbqfuCf`hibpmo^dd%2.+4)05+4&yyNFAy5/45yyWyPfifqerpy
QPb`rofkdqebPrmmivIfkbpyKyTfka`^iiboMolraelok%2.+.)05+4&yyNFAy5/5-yyWyPfifqerpy
>PqbmmfkdRmPb`rofqvyKyTfka`^iiboMolraelok%2.+.)05+4&yyNFAy5/5.yyWyPfifqerpy
QQebQtfifdeqJvpqbovyKyDblildfpqI^ohp_^kb%16+4)04+0&yyNFAy5/51yyWyPfifqerpy
>QebAbpboqboyKyDblildfpqI^ohp_^kb%16+4)04+0&yyNFAy5/52yyWyPfifqerpy
QQtfifdeqDbliloapyKyErrjTfiaj^kb%15+3)04+4&yyNFAy50/-yyWyPfifqerpy
>Svo^iqebSfibyKyErrjTfiaj^kb%15+3)04+4&yyNFAy50/.yyWyPfifqerpy
QPb`obq@ljjrkf`^qflkyKy?loTfiaj^kb%15+3)04+4&yyNFAy50.5yyWyPfifqerpy
Q>_vpp^i@lkq^`qpyKy?loTfiaj^kb%15+3)04+4&yyNFAy503.yyWyPfifqerpy

QQebPmfofqplcPlrqetfkayKyI^vlPq^opqofhb%5.+5).5+5&yyNFAy../2yyWyPfifqerpy
>EfsbfkqebQltboyKyI^vlPq^opqofhb%5.+5).5+5&yyNFAy../3yyWyPfifqerpy
@Svo^iqebSfibyKyPi^vSvo^i%4/+3).2+1&^ka_ofkdSvo^i$pPfdkbqOfkdqlErrjTfiaj^kbfk@bk^oflkElia+yyNFAy50/.yyWyPfifqerpy
QSvo^iqebSfibyKyErrjTfiaj^kb%15+3)04+4&yyNFAy50/.yyWyPfifqerpy

@EfsbfkqebQltboyKyP`^ibqebqltbolcPlrqetfkaSfii^db%3-+0)2/+2&^kail`^qb^jb^kpqlpqfoqebpfifqefaefsbfkql^`qfsfqv+?ofkd_^`hXBk`orpqbaPfifqefaL_gb`qZ+yyNFAy../3yyWyPfifqerpy
QQebAbpboqboyKyEbojfqLoqbii%34+.)36+4&yyNFAy5/52yyWyPfifqerpy
>QebQtfifdeqIbuf`lkyKyEbojfqLoqbii%34+.)36+4&yyNFAy5/46yyWyPfifqerpy
@CfbiaArqvyKyPmb^htfqeHordPhriipmifq%2/+/)35+1&)qebbsbkqq^hbp^_lrq/*0jfkrqbpqlpq^oq+Q^ihqlefj^d^fk^cqboqebhfii^ka^``bmqeCfbiaArqvM^mbop+yyNFAy540.yyWyPfifqerpy
QObmloqqlDbkbo^iHfofh^yKyDbkbo^iHfofh^%2-+6)36+1&yyNFAy61.3yyWyPfifqerpy
>P`lrofkdqebAbpboqyKyDbkbo^iHfofh^%2-+6)36+1&yyNFAy61//yyWyPfifqerpy
KNrbpqflkCo^kh^iyKyQ^ihqlCo^kh^iPqlkb_ofadb%1-+5)55+4&yyNFAy50-1yyNLyCo^kh^iNrbpqflkba7.,.yyWyPfifqerpy
@Ab^obpqK^q^if^yKyQ^ihqlOrqd^oDivmepe^mbo%1.+0)55+1&yyNFAy50-1yyWyPfifqerpy
KQtfifdeqIbuf`lk*@e^mqbo/yKyQtfifdeqHbbmboBubqbo%.3+/)53+-&yyNFAy5/46yyNLyQtfifdeqIbuf`lk*@e^mqbo/7.,.yyWyPfifqerpy

KMSM>iboqyKyFcvlr^ob^MSBpbosbo)`liib`qfkdPfifqevpqtfiici^dvlrMSM+y
@P`lrofkdqebAbpboqyKy@liib`qPfifqevpq)qefpfpclrkafkPfifqevpqDbvpbo^iilsboPfifqerp)qebkork_^`hqlqeb`liib`qlo%2.+.)4-+/&yyNFAy61//yyWyPfifqerpy
QP`lrofkdqebAbpboqyKyDbkbo^iHfofh^%2-+6)36+1&yyNFAy61//yyWyPfifqerpy

@PqbmmfkdRmPb`rofqvyKyHfii/-Aobadb@orpebop+Qebpbjl_p^obclrkafk`bkqo^iPfifqerp+yyNFAy5/5.yyWyPfifqerpy
@Klddib$pI^pqElmbyKyD^qebo0Pqlkbi^peMfk`boPqfkdbop%03+/)24+.&)0Pqlkbi^peCi^vboPqfkdbop%00+0)41+/&^ka0Ol`hPq^ihboC^kdp%06+4)53+0&+yyNFAy5/45yyWyPfifqerpy
KQtfifdeqIbuf`lk*@e^mqbo0yKyQtfifdeqHbbmboE^srkqe%1-+5)1/+4&yyNFAy5/46yyNLyQtfifdeqIbuf`lk*@e^mqbo07.,.yyWyPfifqerpy
@QebQtfifdeqIbuf`lkyKyQtfifdeqHbbmboJ^vk^%/3+6)04+.&cloQtfifdeqIbuf`lk*@e^mqbo.yyNFAy5/46yyWyPfifqerpy
QQebQtfifdeqIbuf`lkyKyEbojfqLoqbii%34+.)36+4&yyNFAy5/46yyWyPfifqerpy
>>Qboof_ibMromlpbyKyEbojfqLoqbii%34+.)36+4&yyNFAy5/54yyWyPfifqerpy

QPqbmmfkdRmPb`rofqvyKyTfka`^iiboMolraelok%2.+.)05+4&yyNFAy5/5.yyWyPfifqerpy
QKlddib$pI^pqElmbyKy?bbqfuCf`hibpmo^dd%2.+4)05+4&yyNFAy5/45yyWyPfifqerpy
>Klddib$pIlpqP^q`ebiyKyKlddibCf`hibpmo^dd%2.+4)05+3&yNFAy5/5/yyWyPfifqerpy
QCfbiaArqvyKyTfka`^iiboH^ialk%2-+-)03+2&yyNFAy540.yyWyPfifqerpy
KCfbiaArv>d^fk++yKyCfibaArqvfpObmb^q^_ib^ka`^k_brpbaql_rfiaObm+y
QAb^obpqK^q^if^yKy@ljj^kaboJ^o$^ifqe%16+0)01+3&yyNFAy50-1yyWyPfifqerpy
>FkqlQebJ^tlcJ^akbppyKy@ljj^kaboJ^o$^ifqe%16+0)01+3&yyNFAy50-3yyWyPfifqerpy
Q>Qboof_ibMromlpbyKy@ljj^kaboJ^o$^ifqe%16+/)01+0&yyNFAy5/54yyWyPfifqerpy

>Divme@e^pfkdyKyOrqd^oDivmepe^mbo%1.+/)55+2&yNFAy50-6yyWyPfifqerpy
>?ob^hfkdqeb@labyKyCo^kh^iPqlkb_ofadb%1-+5)55+4&yNFAy50.-yyWyPfifqerpy
@T^kqba*Ab^qe`i^pm)QboololcqebP^kapyKy?ofkdAb^qe`i^pm$pMfk`bo%12+-)6.+6&qlSfpeHlwrp)@^mq^fklcqebDr^oa+yyNFAy5/50yyWyPfifqerpy
@Klddib$pIlpqP^q`ebiyKyDbqKlddib$pP^q`ebi%11+3)6.+1&yyNFAy5/5/yyWyPfifqerpy
@FkqlQebJ^tlcJ^akbppyKyAbcb^qK^q^if^)EfsbBkqbob^k`bfp^q%22+.)54+5&)Cliiltqeb`^sbpqlqebIbcq^iiqebt^vqlqebi^pqolrka`e^j_bo%2.+2).--+-&+yyNFAy50-3yyWyPfifqerpy
KEfsb$Obd^iOr__fkdyKyL_q^fkXEfsb$Obd^iOr__fkdZ+OfdeqkbuqqltebobK^q^if^t^p+yyNFAy50-6yyNLyEfsb$Obd^iOr__fkd7.,.yyWyPfifqerpy
KEfsb$Obd^iPfifqefa?o^fkyKyHfiijl_pcloXEfsb$Obd^iPfifqefa?o^fkZ%24+2)55+1&yyNFAy50.-yyNLyEfsb$Obd^iPfifqefa?o^fk7.,.yyWyPfifqerpy
KEfsb$Wlo^Or__fkdyKyEfsbBkqbo^k`b%/4+3)32+6&)L_q^fkXEfsb$Wlo^Or__fkdZ%04+0)3/+1&yyNFAy50-6yyNLyEfsb$Wlo^Or__fkd7.,.yyWyPfifqerpy
KEfsb$Wlo^Pfifqefa?o^fkyKyHfiijl_pcloXEfsb$Wlo^Pfifqefa?o^fkZ%/3+2)23+4&yyNFAy50.-yyNLyEfsb$Wlo^Pfifqefa?o^fk7.,.yyWyPfifqerpy
@Divme@e^pfkdyKyEfsbBkqbo^k`bfp^q%15+-)/1+4&)L_q^fkXEfsb$>pefOr__fkdZ%2-+5)/3+5&yyNFAy50-6yyWyPfifqerpy
@?ob^hfkdqeb@labyKyHfiijl_pcloXEfsb$>pefPfifqefa?o^fkZ%11+5)/2+6&yyNFAy50.-yyWyPfifqerpy
QFkqlQebJ^tlcJ^akbppyKy@ljj^kaboJ^o$^ifqe%16+0)01+3&yyNFAy50-3yyWyPfifqerpy
QT^kqba*Ab^qe`i^pm)QboololcqebP^kapyKySfpeHlwrp%2-+5)00+3&yyNFAy5/50yyWyPfifqerpy
QKlddib$pIlpqP^q`ebiyKyKlddibCf`hibpmo^dd%2.+4)05+3&yyNFAy5/5/yyWyPfifqerpy

QEfsbfkqebQltboyKyI^vlPq^opqofhb%5.+5).5+5&yyNFAy../3yyWyPfifqerpy
>Rj_bo)>o`efsfpqyKyI^vlPq^opqofhb%11+5)02+2&yyNFAy3511yyWyPfifqerpy
QDivme@e^pfkdyKyOrqd^oDivmepe^mbo%1.+/)55+2&yNFAy50-6yyWyPfifqerpy
Q?ob^hfkdqeb@labyKyCo^kh^iPqlkb_ofadb%1-+5)55+4&yyNFAy50.-yyWyPfifqerpy
>Rko^sbifkdqebJvpqbovyKyOrqd^oDivmepe^mbo%1.+/)55+2&yNFAy50.1yyWyPfifqerpy
QRko^sbifkdqebJvpqbovyKyDblildfpqI^ohp_^kb%16+4)04+0&yyNFAy50.1yyWyPfifqerpy
>Qeb@^iifkdyKyDblildfpqI^ohp_^kb%16+4)04+0&yyNFAy50.2yyWyPfifqerpy
@Qeb@^iifkdyKyOb`lsboqeb@ovpq^iRkil`hfkdJb`e^kfpjcoljqebNfo^gfBjfpp^ov+%14+0)22+-&yyRy/-131yyNFAy50.2yyWyPfifqerpy
QQeb@^iifkdyKyDblildfpqI^ohp_^kb%16+4)04+0&yyNFAy50.2yyWyPfifqerpy
K>oj^jbkqplcT^oyKyT^fqrkqfipebfpalkbpmb^hfkdqebk^``bmq,`ljmibqb>oj^jbkqplcT^oclovlro`i^ppy

EA^i^o^kyRy3615y
OLodofjj^oyKyQ^hbmloq^i%22+/)/2+3&fkA^i^o^kqlLodofjj^oyyWyA^i^o^ky
CJllkdi^abyKyAlo^p%12+0)31&yyWyLodofjj^oy

QRj_bo)>o`efsfpqyKyRj_bo%11+5)02+2&yyNFAy3511yyWyJllkdi^aby
>Rk`lsbofkdM^pqPb`obqpyKyRj_bo%13+1)06+1&yyNFAy3512yyWyJllkdi^aby
QRk`lsbofkdM^pqPb`obqpyKyO^_fkbP^qrok^%2.+4)11+6&yyNFAy3512yyWyJllkdi^aby
Q>Obifnr^ovlcMrofqvyKyO^_fkbP^qrok^%2.+4)11+6&yyNFAy22/4yyWyJllkdi^aby
>Pe^oaplcqebCbisfkbyKyO^_fkbP^qrok^%2.+4)11+6&yyNFAy22/3yyWyJllkdi^aby
>Rkaboqeb@efqfkT^p+++yKyRj_bo%11+5)02+2&yyNFAy..52yyWyJllkdi^aby

CCbo^i^pyKyC^rpqolk%0/+.)33+5&yyWyJllkdi^aby
OAfobJ^riyKyBkqboAfobJ^riB^pq%3-+/)0-+3&yyWyCbo^i^py
@Pe^oaplcqebCbisfkbyKyPi^v>iwwfkqebTfiape^mbo)qebi^pq_lppfkAfobJ^riB^pq)^kaillqqebCbisfkb+yyNFAy22/3y

CJllkdi^abyKyPevk%42+1)11+1&yyWyCbo^i^py
QPe^oaplcqebCbisfkbyKyO^_fkbP^qrok^%2.+4)11+6&yyNFAy22/3yyWyJllkdi^aby

KArhbplcqeb@lrk`fiyKyVlr`^kalqefpnrbpq`e^fkqe^qpq^oqp^q>robiDliaib^c%2.+6)05+-&+FqobnrfobpdofkafkdlrqQtfifdeq$pE^jjbo@riqfpqcloqebQtfifdeq@riqfpqpbq)tef`efpabpqolvbabsbovqfjb^iloafpprjjlkba)_rqlccbopdob^qobm+yyNFAy500/yyWyPfifqerpy

KBu^iqbaObmrq^qflkDofka++yKyRpbqebobmb^q^_ibnrbpqp^kaqrok*fklmqflkpfkPfifqerpqldbqqlBu^iqba+y
KDrfab@ljmibqb

]]
end)
