DugisGuideViewer:RegisterGuide("Critter Achievement (80)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob^qib^pq5-+Qeb`ofqqbopifpqba^obil`^qbafkqebdbkbo^i^ob^pifpqba+Fcvlralklqpbbqeblkbkbbaba)hfiipljblcqeblqebo`ofqqbopfkqeb^ob^)^pqebve^sb^mobqqvc^pqobpm^tko^qb+y

K>`efbsbjbkqpyKy$Ql>iiQebPnrfoobipF$sbIlsba?bclob$)$Ql>iiQebPnrfoobipTelPe^obaJvIfcb$)$Mbpq@lkqoli$)^ka$CofbkaloClti<$y

eA^i^o^kyKyJ^hbA^i^o^kvlroeljb%32+3)0/+/&Dbqqfkdql^kacoljqebpbil`^qflktfii_bb^pfbocoljA^i^o^k+yyWyA^i^o^ky

HRkabo_biivO^qyKyQebRkabo_biivfkA^i^o^kyy>FAy/223yy>@y.4y
K,ilsbPnrfoobiyKyClrkafkdo^ppv^ob^plcA^i^o^kyy>FAy./-3yy>@y.y
HPnrfoobiyKyClrkafkdo^ppv^ob^plcA^i^o^kyy>FAy/223yy>@y/y

OPe^qqo^qe@fqvyKyQ^hbqebmloq^iqlPe^qqo^qe%23+0)//+3&yyWyA^i^o^ky

K,ilsb@ef`hbkyKy%25)36&yyWyPe^qqo^qe@fqvyy>FAy./-3yy>@y2y
K,ilsbBtbyKy%25)/0&yyWyPe^qqo^qe@fqvyy>FAy./-3yy>@y6y

OW^kd^oj^opeyKyQo^sbiqlW^kd^j^ope%44)44&yyWyW^kd^oj^opey

K,ilsbColdyKyClrkaqeolrdelrqwlkbyy>FAy./-3yy>@y..y
HPk^hbyKyClrkaqeolrdelrqwlkbyy>FAy/223yy>@y.2y

OEbiicfobMbkfkpri^yKyQo^sbiqlEbiicfobMbkfkpri^%.4)15&yyWyEbiicfobMbkfkpri^y
H>aaboyKy%.4)15&yyWyEbiicfobMbkfkpri^yy>FAy/223yy>@y.y
HP`lomflkyKy%1-)35&yyWyEbiicfobMbkfkpri^yy>FAy/223yy>@y.1y

O?i^pqbaI^kapyKyDlqeolrdeqebA^ohMloq^i%56+1)2-+/&yyWyEbiicfobMbkfkpri^y

OPt^jmlcPlooltpyKyQo^sbiqlPt^jmlcPlooltp%01+/)32&yyWyPt^jmlcPlooltpy

HJl``^pfkyKy%15)12&yyWyPt^jmlcPlooltpyy>FAy/223yy>@y.-y
K,ilsbErdbQl^ayKy%12)13&yyWyPt^jmlcPlooltpyy>FAy/224yy>@y4y
CQelofrjMlfkqyKyCivqlQelofrjMlfkq)Pb^ofkdDlodb%13+.)21+5&yyWyPt^jmlcPlooltpy

HCfob?bbqibyKy%11)1-&yyWyPb^ofkdDlodbyyWyPb^ofkdDlodbyy>FAy/223yy>@y2y
K,ilsbI^s^@o^_yKy%10)02&yyWyPb^ofkdDlodbyyWyPb^ofkdDlodbyy>FAy/224yy>@y5y

EA^i^o^kyRy3615y
O@^sbokplcQfjbyKyQ^hbMloq^ifkA^i^o^k%Sflibq@fq^abi&ql@^sboklcQfjb%/2+4)2.+/&yyWyA^i^o^ky
OQeb@riifkdlcPqo^qelijbyKyWlkbfkqlQeb@riifkdlcPqo^qelijb%3.+1)3/+3&yyWyQ^k^ofpy
HO^qy>FAy/223yy>@y./y
K,ilsbC^tky>FAy./-3yy>@y.-y
K,ilsb7Abboy>FAy./-3yy>@y5y
K,ilsb7O^__fqy>FAy./-3yy>@y.2y
K,ilsb7@^qy>FAy./-3yy>@y1y
K,ilsb7Pebbmy>FAy./-3yy>@y.4y

ORk$Dlol@o^qboyKyQo^sbiqlRk$Dlol@o^qbo%2-).4&yyWyRk$Dlol@o^qboy
K,ilsbM^oolqyKyQefpfp^sbovo^ob`ofqqbo)plhfii^iiqeblqebo`ofqqbopvlr`^kcfkaqlqov^kadbqqefplkbqlpm^tk%20+6)4/+6&%21+2)30+-&%3-+6)11+5&%2/+6)0/+-&%2-+2).4+0&%13+/)/2+/&yyWyRk$Dlol@o^qboyy>FAy./-3yy>@y.1y

CQeb@olppol^apyKyCivqlQeb@olppol^ap%12+/)2+5&yyWyRk$Dlol@o^qboy

K,ilsbMo^fofbAldyKy%20+4)0-+/&%16+6)13+1&%13+.)3-+2&qeolrdelrqwlkbyyWyQeb?^oobkpyy>FAy./-3yy>@y/.y
K,ilsbD^wbiibyKy>olrka@olppol^ap%20+3)02+6&%2-+6)01+0&LO@^jmQ^rogl%11+3)30+-&%13+1)3-+2&yyWyQeb?^oobkpyy>FAy./-3yy>@y./y
K,ilsbPtfkbyKy%21)/-&yyWyQeb?^oobkpyy>FAy./-3yy>@y.6y

OArolq^oyKyQo^sbiqlArolq^o%01+6)1/+.&yyWyArolq^oy
K,ilsbE^obyKyQeolrdelrqwlkbyy>FAy./-3yy>@y.0y

CQfofpc^iDi^abpyKyQ^hbWbmmifklrqpfabLodofjj^o%2-+6).0+6&yyWyArolq^oy
CQ^oobkJfiiyKyCivqlEfiip_o^aCllqefiip%30+0)15+3&yyWyRkabo`fqvy
K,ilsb@ltyKy%04)1-&yyWyEfiip_o^aCllqefiipyy>FAy./-3yy>@y3y

CE^jjboc^iiyKyCivqlE^jjboc^ii%3-+.).5+3&yyWyEfiip_o^aCllqefiipy
OTbqi^kapyKyQo^sbiqlTbqi^kap%2-).1&yyWyTbqi^kapy
K,ilsbQl^ayKy%16)03&yyWyTbqi^kapyy>FAy./-3yy>@y/-y
K,ilsbO^jyKy%16)36&yyWyTbqi^kapyy>FAy./-3yy>@y.3y

EA^i^o^kyRy3615y
C>odbkqQlrok^jbkqDolrkapyKyCivql>odbkqQlrok^jbkqDolrkap%42)/1&yyWyF`b`oltky
K,ilsbDi^`fboMbkdrfkyKy%44)/1&yyWyF`b`oltkyy>FAy/224yy>@y2y

ORiar^oyKyQo^sbiqlRiar^o%10)/3&yyWyQebPqlojMb^hpy

HDlia?bbqibyKyE^iiplcIfdeqkfkdgrpqfkpfabbkqo^k`b%12)/.&yyWyQebPqlojMb^hpyy>FAy/223yy>@y4y

HWri$Ao^hO^qyKy>jmefqeb^qbo%11)26&yyWyWri$Ao^hy

HWri$Ao^hO^qyKy>jmefqeb^qbo%11)26&yyWyWri$Ao^hyy>FAy/223yy>@y.5y
K,ilsb>o`qf`E^obyKy%41)4-&yyWyWri$Ao^hyy>FAy/224yy>@y.y

ODofwwivEfiipyKyQo^sbiqlDofwwivEfiip%.5)40&yyWyDofwwivEfiipy

K,ilsbJlrkq^fkPhrkhyKy>_rka^kqqeolrdelrqqebwlkbyy>FAy/224yy>@y6y
K,ilsbDofwwivPnrfoobiyKy>_rka^kqqeolrdelrqqebwlkbyy>FAy/224yy>@y3y
HJlrpbyKy%.5)40&yyWyDofwwivEfiipyy>FAy/223yy>@y..y

OEltifkdCgloayKyQo^sbiqlEltifkdCgloa%03)..&yyWyEltifkdCgloay

HOl^`eyKy%03)..&yyWyEltifkdCgloayy>FAy/223yy>@y.0y
HCgloaO^qyKy%11)02&>kvmlmri^qba^ob^yyWyEltifkdCgloayy>FAy/223yy>@y3y
HAbslrofkdJ^ddlqyKyRqd^oab@^q^`lj_pBkqo^k`b%23)16&)grpqqlqebibcqlcRHbkqbo^k`b%24)22&)lkqeb_lqqljmfqtfqe^iiqebdelripyyWyEltifkdCgloayy>FAy/223yy>@y1y
K,ilsbCgloaQrohbvyKy%36)31&yyWyEltifkdCgloayy>FAy/224yy>@y0y
KLmqflk^iyKyHfii.2CgloaQrohvfk0jfkrqbpcloCofbkaloClti<>`efbsbjbkqyy>FAy./21yy>@y.y
K,ilsbPhrkhyKyClrkaqeolrdelrqwlkbyy>FAy./-3yy>@y.5y
K,ilsbCgloaMbkdrfkyKy%33)50&yyWyEltifkdCgloayy>FAy/224yy>@y0y
K,ilsbP`^i^t^dColdyKy%03)5-&yyWyEltifkdCgloayy>FAy/224yy>@y.-y

OK^uuo^j^pyKyVlrkbbaql_bfk^O^fadolrmcloK^uu)plfksfqb^cofbkaqlq^d^ilkd%54+0)2.&yyWyAo^dlk_ifdeqy

HPmfaboyKyBkqo^k`byy>FAy/223yy>@y.3y
HJ^ddlqyKyBkqo^k`byy>FAy/223yy>@y6y
HI^os^yKyClrkafkqebMi^drbTfkd+Kbbaql`ib^otfkdqldbqqefp`ofqqboebob+Lmqflk^i7DlqlDelpqi^kap%BkalcqefpDrfab&yy>FAy/223yy>@y5y

O?lob^kQrkao^yKyQo^sbiql?lob^kQrkao^%4-)/6&yyWy?lob^kQrkao^y
K,ilsb?lob^kColdyKy%4-)/6&yyWy?lob^kQrkao^yy>FAy./-3yy>@y0y
K,ilsbPqb^jColdyKy%35)1.&yyWy?lob^kQrkao^yy>FAy./-3yy>@y/y
K,ilsb?lob^kJ^ojlqyKy>_rka^kqqeolrdelrqqebwlkbyy>FAy/224yy>@y/y
H@ovpq^iPmfaboyKyKburp^olrkaHbofpqo^pw^%Orkpqo^fdeqqlHbofpq^pw^ollj)`^obcriql^slfaqebm^qolip+yyWy?lob^kQrkao^yy>FAy/223yy>@y0y
K,ilsb@o^_yKy%06).2&yyWy?lob^kQrkao^yy>FAy./-3yy>@y4y
K,ilsbQrkao^Mbkdrfk)yKy%05)6&yyWy?lob^kQrkao^yy>FAy/224yy>@y./y

OPeli^w^o?^pfkyKyQo^sbiqlPeli^w^o?^pfk%/4)3-&yyWyPeli^w^o?^pfky
K,ilsbPeli^w^oQf`h_foayKy%/4)3-&kb^oqebKbpfkdt^ov?^pb@^jmyyWyPeli^w^o?^pfkyy>FAy/224yy>@y..y

KLmqflk^iyKyFcvlrpqfiikbbaI^os^)qebk`lkqfkrb)lqebotfpbqefpdrfabfp`ljmibqb+yy>FAy/223yy>@y5y
OA^i^o^kyKyQo^sbiqlA^i^o^k%06+2)31&yyWyA^i^o^kyy>FAy/223yy>@y5y
OPfisbojllk@fqvyKyRpbMloq^ifkA^i^o^k%25+0)/.+4&yyWyA^i^o^kyy>FAy/223yy>@y5y
OQo^knrfiifbkyKyQo^sbiqlQo^knrfiifbk%13)/6&Delpqi^kapyyWyDelpqi^kapyy>FAy/223yy>@y5y
HI^os^yKy%13+4)02+4&%12+5)0-+1&O^obPm^tkEbob)hfii^iipmfabop)j^ddlqp)^kao^qpfkqeb^ob^rkqfilkbpm^tkp+yy>FAy/223yy>@y5y

KDrfab@ljmibqb

]]
end)
