DugisGuideViewer:RegisterGuide("Exploration Northrend (80)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-(tfqe^civfkdjlrkq+J^hbprobA^i^o^kfpvlrEb^oqeil`^qflk+Fcvlralk$qdbqqeb^ob^prk`lsboba^qqebil`^qflkmolsfaba)jlsb^olrka^_fqfkqe^qil`^qflk)fq$pqebob+y
K>iplyKyj^hbprobvlrpq^vfkqebil`^qflkilkdbklrdeqlafp`lsbofq+y
eA^i^o^kyKyJ^hbA^i^o^kvlroeljb%32+3)0/+/&Dbqqfkdql^kacoljqebpbil`^qflktfii_bb^pfbocoljA^i^o^k+yyWyA^i^o^ky

OCloilokTllapyKy@ovpq^iplkdClobpq%14)11&yy>FAy.124yy>@y1yyWy@ovpq^iplkdClobpqy
OQebRk_lrkaQef`hbqyKy@ovpq^iplkdClobpq%3-)3.&yy>FAy.124yy>@y5yyWy@ovpq^iplkdClobpqy
OPrkob^sbo$p@ljj^kayKy@ovpq^iplkdClobpq%43)15&yy>FAy.124yy>@y0yyWy@ovpq^iplkdClobpqy
OTfkaorkkbo$pLsboillhyKy@ovpq^iplkdClobpq%41)5-&yy>FAy.124yy>@y2yyWy@ovpq^iplkdClobpqy
OQeb>wrobColkqyKy@ovpq^iplkdClobpq%/0)24&yy>FAy.124yy>@y.yyWy@ovpq^iplkdClobpqy
OSflibqPq^kayKy@ovpq^iplkdClobpq%.2)1/&yy>FAy.124yy>@y4yyWy@ovpq^iplkdClobpqy
OQebDob^qQobbyKy@ovpq^iplkdClobpq%.1)01&yy>FAy.124yy>@y3yyWy@ovpq^iplkdClobpqy
OQebAb`obmfqCiltyKy@ovpq^iplkdClobpq%.5).2&yy>FAy.124yy>@y/yyWy@ovpq^iplkdClobpqy

OF`b`oltk@fq^abiyKyF`b`oltk%21)52&yy>FAy./4-yy>@y/yyWyF`b`oltky
O@lom$obqe^o7QebElooloD^qbyKyF`b`oltk%15)35&yy>FAy./4-yy>@y./yyWyF`b`oltky
OVjfoebfjyKyF`b`oltk%24)30&yy>FAy./4-yy>@y.-yyWyF`b`oltky
OQeb?olhbkColkqyKyF`b`oltk%34)32&yy>FAy./4-yy>@y1yyWyF`b`oltky
OP`lrodbelijbyKyF`b`oltk%45)32&yy>FAy./4-yy>@y.1yyWyF`b`oltky
OS^iibvlcB`elbpyKyF`b`oltk%50)4/&yy>FAy./4-yy>@y6yyWyF`b`oltky
OPfkao^dlp^$pC^iiyKyF`b`oltk%36)05&yy>FAy./4-yy>@y4yyWyF`b`oltky
OQeb?lj_^oajbkqyKyF`b`oltk%25)06&yy>FAy./4-yy>@y.yyWyF`b`oltky
O>iaro$qe^o7QebAbpli^qflkD^qbyKyF`b`oltk%21)05&yy>FAy./4-yy>@y3yyWyF`b`oltky
OQebPe^altS^riqyKyF`b`oltk%10)/0&yy>FAy./4-yy>@y.2yyWyF`b`oltky
OGlqrkebfjyKyF`b`oltk%02)/3&yy>FAy./4-yy>@y.0yyWyF`b`oltky
OS^ie^i^pyKyF`b`oltk%1.)/5&yy>FAy./4-yy>@y5yyWyF`b`oltky
OQeb@lkci^do^qflkyKyF`b`oltk%10)3-&yy>FAy./4-yy>@y..yyWyF`b`oltky
OQebCibpetbohpyKyF`b`oltk%01)35&yy>FAy./4-yy>@y2yyWyF`b`oltky
OLkpi^rdeqE^o_loyKyF`b`oltk%./)13&yy>FAy./4-yy>@y0yyWyF`b`oltky

OQebP^s^dbQef`hbqyKyPeli^w^o?^pfk%13)/2&yy>FAy./35yy>@y/yyWyPeli^w^o?^pfky
OQebDifjjbofkdMfii^oyKyPeli^w^o?^pfk%16)05&yy>FAy./35yy>@y.-yyWyPeli^w^o?^pfky
OQeb>s^i^k`ebyKyPeli^w^o?^pfk%40)03&yy>FAy./35yy>@y6yyWyPeli^w^o?^pfky
OJ^hbop$LsboillhyKyOfdeqlkqebIbadblcqebpqor`qrobfkqebjlrkq^fk%5-)21&yy>FAy./35yy>@y1yyWyPeli^w^o?^pfky
OQebIfcb_illaMfii^oyKyPeli^w^o?^pfk%32)26&yy>FAy./35yy>@y5yyWyPeli^w^o?^pfky
OO^fkpmb^hbo@^klmvyKyPeli^w^o?^pfk%21)23&yy>FAy./35yy>@y4yyWyPeli^w^o?^pfky
OOfsbo$pEb^oqyKyPeli^w^o?^pfk%15)30&yy>FAy./35yy>@y.yyWyPeli^w^o?^pfky
OQebPrkqlr`ebaMfii^oyKyPeli^w^o?^pfk%00)2/&yy>FAy./35yy>@y3yyWyPeli^w^o?^pfky
OQebJ^hbop$Mbo`eyKyPeli^w^o?^pfk%/6)05&yy>FAy./35yy>@y2yyWyPeli^w^o?^pfky
OQebPqlojtofdeq$pPebicyKyPeli^w^o?^pfk%/3)02&yy>FAy./35yy>@y./yyWyPeli^w^o?^pfky
OH^oq^h$pEliayKyPeli^w^o?^pfk%/2)5.&yy>FAy./35yy>@y..yyWyPeli^w^o?^pfky
OQebJlppifdeqMfii^oyKyPeli^w^o?^pfk%03)42&yy>FAy./35yy>@y0yyWyPeli^w^o?^pfky

O?lo$dlolhLrqmlpqyKy?lob^kQrkao^%2-)6&yy>FAy./31yy>@y5yyWy?lob^kQrkao^y
OPqbbig^t$p@^o^s^kyKy?lob^kQrkao^%16)/2&yy>FAy./31yy>@y/yyWy?lob^kQrkao^y
O>j_boIbadbyKy?lob^kQrkao^%12)00&yy>FAy./31yy>@y6yyWy?lob^kQrkao^y
O@lia^oo^yKy?lob^kQrkao^%/4)04&yy>FAy./31yy>@y4yyWy?lob^kQrkao^y
OD^oolpe$pI^kafkdyKy?lob^kQrkao^%0/)21&yy>FAy./31yy>@y2yyWy?lob^kQrkao^y
OT^oplkdEliayKy?lob^kQrkao^%11)23&yy>FAy./31yy>@y.-yyWy?lob^kQrkao^y
OOfmi^pePqo^kayKy?lob^kQrkao^%11)45&yy>FAy./31yy>@y0yyWy?lob^kQrkao^y
OS^if^k`bHbbmyKy?lob^kQrkao^%20)4.&yy>FAy./31yy>@y..yyWy?lob^kQrkao^y
OH^ph^i^yKy?lob^kQrkao^%31)15&yy>FAy./31yy>@y1yyWy?lob^kQrkao^y
OQebDbvpboCfbiapyKy?lob^kQrkao^%34)/1&yy>FAy./31yy>@y./yyWy?lob^kQrkao^y
OQebAbkplcAvfkdyKy?lob^kQrkao^%43).6&yy>FAy./31yy>@y.0yyWy?lob^kQrkao^y
OQbjmib@fqvlcBk$hfi^eyKy?lob^kQrkao^%5/)/1&yy>FAy./31yy>@y.yyWy?lob^kQrkao^y
OAb^qe$pPq^kayKy?lob^kQrkao^%5/)14&yy>FAy./31yy>@y3yyWy?lob^kQrkao^y

OTbpqtfkaObcrdbb@^jmyKyAo^dlk_ifdeq%.1)14&yy>FAy./32yy>@y.1yyWyAo^dlk_ifdeqy
OF`bjfpqSfii^dbyKyAo^dlk_ifdeq%/2)10&yy>FAy./32yy>@y5yyWyAo^dlk_ifdeqy
O>dj^o$pE^jjboyKyAo^dlk_ifdeq%03)13&yy>FAy./32yy>@y./yyWyAo^dlk_ifdeqy
OI^hbFkar$ibyKyAo^dlk_ifdeq%1-)34&yy>FAy./32yy>@y/yyWyAo^dlk_ifdeqy
OBjbo^iaAo^dlkpeofkbyKyAo^dlk_ifdeq%30)40&yy>FAy./32yy>@y6yyWyAo^dlk_ifdeqy
OTvojobpqQbjmibyKyAo^dlk_ifdeq%26)21&yy>FAy./32yy>@y.0yyWyAo^dlk_ifdeqy
OOr_vAo^dlkpeofkbyKyAo^dlk_ifdeq%14)15&yy>FAy./32yy>@y0yyWyAo^dlk_ifdeqy
OD^i^holka$pObpqyKyAo^dlk_ifdeq%22)01&yy>FAy./32yy>@y.yyWyAo^dlk_ifdeqy
OL_pfaf^kAo^dlkpeofkbyKyAo^dlk_ifdeq%1-)0.&yy>FAy./32yy>@y1yyWyAo^dlk_ifdeqy
O>kdo^qe^oqebTo^qed^qbyKyAo^dlk_ifdeq%04).4&yy>FAy./32yy>@y..yyWyAo^dlk_ifdeqy
O@liatfkaEbfdeqpyKyAo^dlk_ifdeq%22)/-&yy>FAy./32yy>@y.-yyWyAo^dlk_ifdeqy
OQeb@ovpq^iSf`byKyAo^dlk_ifdeq%3-)/-&yy>FAy./32yy>@y.4yyWyAo^dlk_ifdeqy
OP`^oibqMlfkqyKyAo^dlk_ifdeq%40)/2&yy>FAy./32yy>@y.5yyWyAo^dlk_ifdeqy
OIfdeq$pQorpqyKyAo^dlk_ifdeq%51)/3&yy>FAy./32yy>@y4yyWyAo^dlk_ifdeqy
OK^uuo^j^pyKyBkqboqebrkabopfablcK^uucloafp`lsbov%54)2-&yy>FAy./32yy>@y3yyWyAo^dlk_ifdeqy
OSbkljpmfqbyKyAo^dlk_ifdeq%43)3/&yy>FAy./32yy>@y.2yyWyAo^dlk_ifdeqy
OKbtEb^oqedibkyKyAo^dlk_ifdeq%4.)41&yy>FAy./32yy>@y2yyWyAo^dlk_ifdeqy
OQebClodlqqbkPelobyKyAo^dlk_ifdeq%5/)35&yy>FAy./32yy>@y.3yyWyAo^dlk_ifdeqy

OSbkqrob?^vyKyDofwwivEfiip%.1)53&yy>FAy./33yy>@y6yyWyDofwwivEfiipy
O>mlqeb`^ov@^jmyKyEltifkdCgloa%/4)/1&yy>FAy./30yy>@y1yyWyEltifkdCgloay
OPqbbiD^qbyKyEltifkdCgloa%0-)/3&yy>FAy./30yy>@y3yyWyEltifkdCgloay
OPhlokyKyEltifkdCgloa%12)02&yy>FAy./30yy>@y.3yyWyEltifkdCgloay
OTbpqdr^oaHbbmyKyEltifkdCgloa%0-)10&yy>FAy./30yy>@y.6yyWyEltifkdCgloay
OBj_bo@irq`eyKyEltifkdCgloa%06)2-&yy>FAy./30yy>@y.-yyWyEltifkdCgloay
OH^j^dr^yKyEltifkdCgloa%/2)24&yy>FAy./30yy>@y.yyWyEltifkdCgloay
OP`^i^t^dMlfkqyKyEltifkdCgloa%02)5-&yy>FAy./30yy>@y4yyWyEltifkdCgloay
OKbt>d^j^kayKyEltifkdCgloa%2/)34&yy>FAy./30yy>@y.2yyWyEltifkdCgloay
OE^idofkayKyEltifkdCgloa%2-)20&yy>FAy./30yy>@y.1yyWyEltifkdCgloay
ORqd^oabHbbmyKyEltifkdCgloa%25)13&yy>FAy./30yy>@y.5yyWyEltifkdCgloay
O@^riaolpFpibyKyEltifkdCgloa%24)03&yy>FAy./30yy>@y/yyWyEltifkdCgloay
O?^ibebfjyKyEltifkdCgloa%33)06&yy>FAy./30yy>@y/.yyWyEltifkdCgloay
OKfccibs^oyKyEltifkdCgloa%35)21&yy>FAy./30yy>@y5yyWyEltifkdCgloay
O?^bidrk$pBu`^s^qflkPfqbyKyEltifkdCgloa%4/)4.&yy>FAy./30yy>@y/-yyWyEltifkdCgloay
OFs^ia$pOrfkyKyEltifkdCgloa%44)15&yy>FAy./30yy>@y.0yyWyEltifkdCgloay
OSbkdb^k`bI^kafkdyKyEltifkdCgloa%45)0-&yy>FAy./30yy>@y2yyWyEltifkdCgloay
ODf^kqp$OrkyKyEltifkdCgloa%35)/4&yy>FAy./30yy>@y..yyWyEltifkdCgloay
OCloqTfiabos^oyKyEltifkdCgloa%3-).2&yy>FAy./30yy>@y./yyWyEltifkdCgloay
OQebQtfpqbaDi^abyKyEltifkdCgloa%20)/4&yy>FAy./30yy>@y.4yyWyEltifkdCgloay
O@^jmTfkqboellcyKyEltifkdCgloa%15).-&yy>FAy./30yy>@y0yyWyEltifkdCgloay
ODg^ibo_olkyKyEltifkdCgloa%03).-&yy>FAy./30yy>@y6yyWyEltifkdCgloay

OSliaorkbyKyDofwwivEfiip%/5)41&yy>FAy./33yy>@y.-yyWyDofwwivEfiipy
O@lknrbpqEliayKyDofwwivEfiip%/.)32&yy>FAy./33yy>@y.yyWyDofwwivEfiipy
O>j_bomfkbIladbyKyDofwwivEfiip%0.)3-&yy>FAy./33yy>@y..yyWyDofwwivEfiipy
ODo^kfqbPmofkdpyKyDofwwivEfiip%.3)14&yy>FAy./33yy>@y2yyWyDofwwivEfiipy
OAo^h$Qe^olkHbbmyKyEb^afkqlAo^h$Qe^olkHbbm^ifqqibt^vpcloafp`lsbov%.5)/2&yy>FAy./33yy>@y/yyWyDofwwivEfiipy
O?irbPhvIlddfkdDolrkapyKyDofwwivEfiip%04)03&yy>FAy./33yy>@y./yyWyDofwwivEfiipy
ODofwwibj^tyKyDofwwivEfiip%2-)1/&yy>FAy./33yy>@y3yyWyDofwwivEfiipy
OO^dbC^kdPeofkbyKyDofwwivEfiip%2-)24&yy>FAy./33yy>@y4yyWyDofwwivEfiipy
OArk>odliyKyDofwwivEfiip%43)25&yy>FAy./33yy>@y1yyWyDofwwivEfiipy
O@^jmLkbnt^eyKyDofwwivEfiip%32)14&yy>FAy./33yy>@y.0yyWyDofwwivEfiipy
OTbpqc^ii?ofd^abBk`^jmjbkqyKyDofwwivEfiip%24)0-&yy>FAy./33yy>@y.1yyWyDofwwivEfiipy
OAo^hfi$gfkOrfkpyKyDofwwivEfiip%4.)/3&yy>FAy./33yy>@y0yyWyDofwwivEfiipy
OQeloJla^kyKyDofwwivEfiip%36).2&yy>FAy./33yy>@y5yyWyDofwwivEfiipy

O>iq^olcNrbqw$irkyKyWri$Ao^h%44)26&yy>FAy./34yy>@y3yyWyWri$Ao^hy
OWfj$Qlod^yKyWri$Ao^h%26)24&yy>FAy./34yy>@y6yyWyWri$Ao^hy
O>iq^olcE^o$hl^yKyWri$Ao^h%30)4.&yy>FAy./34yy>@y5yyWyWri$Ao^hy
OHlio^j^pyKyWri$Ao^h%3.)45&yy>FAy./34yy>@y.1yyWyWri$Ao^hy
OAo^h$Plqo^CfbiapyKyWri$Ao^h%10)44&yy>FAy./34yy>@y/yyWyWri$Ao^hy
O>jmefqeb^qbolc>kdrfpeyKyWri$Ao^h%16)23&yy>FAy./34yy>@y0yyWyWri$Ao^hy
OIfdeq$p?ob^`eyKyWri$Ao^h%0/)42&yy>FAy./34yy>@y.0yyWyWri$Ao^hy
OWbo^j^pyKyCivfkqlqebrkabopfabqlafp`lsboWbo^j^p+Qelrdeqeb^ob^jlpqifhbivtfii^iiltafp`lsbov^ptbii+%/.)43&yy>FAy./34yy>@y.-yyWyWri$Ao^hy
OQeovj$pBkayKyWri$Ao^h%.4)25&yy>FAy./34yy>@y./yyWyWri$Ao^hy
OSliq^orpyKyCivfkqlqebrkabopfabqlafp`lsboSliq^orp%/5)13&yy>FAy./34yy>@y..yyWyWri$Ao^hy
O>iq^olcPpbo^qrpyKyWri$Ao^h%1-)05&yy>FAy./34yy>@y1yyWyWri$Ao^hy
O>iq^olcOerklhyKyWri$Ao^h%20)03&yy>FAy./34yy>@y2yyWyWri$Ao^hy
O>iq^olcJ^j$qlqeyKyWri$Ao^h%43)10&yy>FAy./34yy>@y4yyWyWri$Ao^hy
ODrkao^hyKyWri$Ao^h%5/)/-&yy>FAy./34yy>@y.yyWyWri$Ao^hy

OQerkaboc^iiyKyQebPqlojMb^hp%4-)16&yy>FAy./36yy>@y..yyWyQebPqlojMb^hpy
OQbjmiblcIfcbyKyQebPqlojMb^hp%33)2-&yy>FAy./36yy>@y6yyWyQebPqlojMb^hpy
OQboo^`blcqebJ^hbopyKyQebPqlojMb^hp%31)14&yy>FAy./36yy>@y3yyWyQebPqlojMb^hpy
OArkKfccbibjyKyQebPqlojMb^hp%31)26&yy>FAy./36yy>@y0yyWyQebPqlojMb^hpy
O?orkkefia^oSfii^dbyKyQebPqlojMb^hp%15)36&yy>FAy./36yy>@y.yyWyQebPqlojMb^hpy
OD^oj$p?^kbyKyQebPqlojMb^hp%10)5/&yy>FAy./36yy>@y.1yyWyQebPqlojMb^hpy
OPm^ohpl`hbqJfkbcfbiayKyJ^hbprobvlri^ka^kaafpjlrkqcloqefplkb)loqebjloq^optfiiafpjlrkqvlrfkjfa*^fo%02)53&yy>FAy./36yy>@y4yyWyQebPqlojMb^hpy
OColpqeliayKyQebPqlojMb^hp%/6)42&yy>FAy./36yy>@y.2yyWyQebPqlojMb^hpy
O?lo$p?ob^qeyKyQebPqlojMb^hp%0.)36&yy>FAy./36yy>@y1yyWyQebPqlojMb^hpy
OS^ihvoflkyKyQebPqlojMb^hp%/3)3/&yy>FAy./36yy>@y2yyWyQebPqlojMb^hpy
OKfa^sbifoyKyQebPqlojMb^hp%/2)2.&yy>FAy./36yy>@y.3yyWyQebPqlojMb^hpy
OPkltaofcqMi^fkpyKyQebPqlojMb^hp%/4)10&yy>FAy./36yy>@y.0yyWyQebPqlojMb^hpy
OK^osfo$p@o^aibyKyQebPqlojMb^hp%/6)11&yy>FAy./36yy>@y/yyWyQebPqlojMb^hpy
OQbjmiblcPqlojpyKyVlralk$qe^sbqldlqlqebqlm)grpqdbq^p`ilpbqlqebpfab^pmlppf_ib%01)23&yy>FAy./36yy>@y./yyWyQebPqlojMb^hpy
OBkdfkblcqebJ^hbopyKyQebPqlojMb^hp%1.)23&yy>FAy./36yy>@y5yyWyQebPqlojMb^hpy
ORiar^oyKyQebPqlojMb^hp%1-)/1&yy>FAy./36yy>@y.-yyWyQebPqlojMb^hpy

KDrfab@ljmibqb
]]
end)
