DugisGuideViewer:RegisterGuide("Exploration Kalimdor Achievement (60+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-(+J^hbprobA^i^o^kfpvlrEb^oqeil`^qflk+Fcvlralk$qdbqqeb^ob^prk`lsboba^qqebil`^qflkmolsfaba)jlsb^olrka^_fqfkqe^qil`^qflk)fq$pqebob+y
eA^i^o^kyKyJ^hbA^i^o^kvlroeljb%32+3)0/+/&Dbqqfkdql^kacoljqebpbil`^qflktfii_bb^pfbocoljA^i^o^k+yyWyA^i^o^ky
OLodofjj^oyKyQ^hbmloq^ifkA^i^o^kqlLodofjj^o%22+1)/2+2&yyWyA^i^o^ky
C>wpe^o^yKyCivql>wpe^o^%12+.)30+6&yyWyLodofjj^oy

KOlrqbyKyKldllaolrqbclo>wpe^o^+Qefpfpqeb_bpqF`lriacfka+Dllair`h+y
OS^ilojlhyKy>wpe^o^%/.)2.&yy>FAy52/yy>@y..yyWy>wpe^o^y
OQfj_boj^tEliayKy>wpe^o^%05)00&yy>FAy52/yy>@y.-yyWy>wpe^o^y
OOrfkplcBia^o^qeyKy>wpe^o^%0.)2-&yy>FAy52/yy>@y.1yyWy>wpe^o^y
ORopli^kyKy>wpe^o^%11)/3&yy>FAy52/yy>@y6yyWy>wpe^o^y
OQe^i^ppf^k?^pb@^jmyKy>wpe^o^%23)/6&yy>FAy52/yy>@y5yyWy>wpe^o^y
OIbd^peBk`^jmjbkqyKy>wpe^o^%2.).6&yy>FAy52/yy>@y4yyWy>wpe^o^y
OG^ddbaObbcyKy>wpe^o^%2/)./&yy>FAy52/yy>@y0yyWy>wpe^o^y
O?fqqboOb^`ebpyKy>wpe^o^%40)/.&yy>FAy52/yy>@y1yyWy>wpe^o^y
OQltbolcBia^o^yKy>wpe^o^%56)00&yy>FAy52/yy>@y2yyWy>wpe^o^y
OQbjmiblc>ohhlo^kyKy>wpe^o^%43)10&yy>FAy52/yy>@y3yyWy>wpe^o^y
O?^vlcPqlojpyKy>wpe^o^%23)26&yy>FAy52/yy>@y.yyWy>wpe^o^y
OQebPe^qqbobaPqo^kayKy>wpe^o^%12)2/&yy>FAy52/yy>@y/yyWy>wpe^o^y
OPlrqeofadb?b^`eyKy>wpe^o^%14)33&yy>FAy52/yy>@y.2yyWy>wpe^o^y
OO^sbk`obpqJlkrjbkqyKy>wpe^o^%4/)53&yy>FAy52/yy>@y.3yyWy>wpe^o^y
OQebOrfkbaOb^`ebpyKy>wpe^o^%2.)55&yy>FAy52/yy>@y.5yyWy>wpe^o^y
OI^hbJbkk^oyKy>wpe^o^%1-)5-&yy>FAy52/yy>@y.4yyWy>wpe^o^y
OCloilokOfadbyKy>wpe^o^%0-)4.&yy>FAy52/yy>@y.6yyWy>wpe^o^y
OE^ia^ooBk`^jmjbkqyKy>wpe^o^%/-)3.&yy>FAy52/yy>@y./yyWy>wpe^o^y
OPe^altplkdPeofkbyKy>wpe^o^%.1)40&yy>FAy52/yy>@y.0yyWy>wpe^o^y

O>pebks^ibyKyOrkfkql>pebks^ibyy>FAy512y
O?lrdePe^altyKy>pebks^ib%60)02&yy>FAy512yy>@y.3yyWy>pebks^iby
OP^qvok^^oyKy>pebks^ib%5-)16&yy>FAy512yy>@y.2yyWy>pebks^iby
OT^oplkdIrj_bo@^jmyKy>pebks^ib%50)24&yy>FAy512yy>@y.4yyWy>pebks^iby
OCbicfobEfiiyKy>pebks^ib%56)44&yy>FAy512yy>@y.5yyWy>pebks^iby
OQebJlo$pe^kO^jm^oqyKyQeb?^oobkp%16)2&yy>FAy42-yy>@y0yyWyQeb?^oobkpy
OC^iibkPhvI^hbyKy>pebks^ib%33)5/&yy>FAy512yy>@y.0yyWy>pebks^iby
OPmifkqboqobbMlpqyKy>pebks^ib%40)3/&yy>FAy512yy>@y.1yyWy>pebks^iby

CBsboillhyKyTfkqbopmofkdy
OBsboillhyKyTfkqbopmofkd%3.)04&yy>FAy524yy>@y3yyWyTfkqbopmofkdy
OI^hbHbi$QebofiyKyTfkqbopmofkd%20)1.&yy>FAy524yy>@y0yyWyTfkqbopmofkdy
OJ^wqelofiyKyTfkqbopmofkd%24)21&yy>FAy524yy>@y2yyWyTfkqbopmofkdy
OLtiTfkdQef`hbqyKyTfkqbopmofkd%32)3-&yy>FAy524yy>@y4yyWyTfkqbopmofkdy
OColpqtefpmboDlodbyKyTfkqbopmofkd%3.)35&yy>FAy524yy>@y./yyWyTfkqbopmofkdy
OA^ohtefpmboDlodbyKyTfkqbopmofkd%25)5-&yy>FAy524yy>@y.0yyWyTfkqbopmofkdy
OF`bQefpqibEfiipyKyTfkqbopmofkd%35)10&yy>FAy524yy>@y5yyWyTfkqbopmofkdy
OTfkqboc^iiSfii^dbyKyTfkqbopmofkd%35)03&yy>FAy524yy>@y6yyWyTfkqbopmofkdy
OQebEfaabkDolsbyKyTfkqbopmofkd%30).3&yy>FAy524yy>@y.-yyWyTfkqbopmofkdy
OColpqp^_boOl`hyKyTfkqbopmofkd%16)..&yy>FAy524yy>@y..yyWyTfkqbopmofkdy
OPq^oc^iiSfii^dbyKyTfkqbopmofkd%2-)/5&yy>FAy524yy>@y1yyWyTfkqbopmofkdy
OQfj_boj^tMlpqyKyTfkqbopmofkd%1-)1/&yy>FAy524yy>@y/yyWyTfkqbopmofkdy
OColpqcfobElqPmofkdpyKyTfkqbopmofkd%04)04&yy>FAy524yy>@y.yyWyTfkqbopmofkdy

OJllkdi^abyKyOrkqeolrde`^sbqlJllkdi^ab%02)40&yyWyJllkdi^aby
OI^hbBirkb$^o^yKyJllkdi^ab%12)25&yy>FAy522yy>@y.yyWyJllkdi^aby

OCbitllayKyOrkqeolrde`^sbqlCbitlla%32)5&yyWyCbitllay
OCbim^tSfii^dbyKyCbitlla%30).-&yy>FAy520yy>@y.yyWyCbitllay
OQ^ilk_o^k`eDi^abyKyCbitlla%30)//&yy>FAy520yy>@y/yyWyCbitllay
OG^abcfobOrkyKyCbitlla%1/).3&yy>FAy520yy>@y1yyWyCbitllay
OFolkqobbTllapyKyCbitlla%15)/0&yy>FAy520yy>@y0yyWyCbitllay
OPe^qqboP`^oS^ibyKyCbitlla%1/)1-&yy>FAy520yy>@y2yyWyCbitllay
O?illasbkljC^iipyKyCbitlla%1.)14&yy>FAy520yy>@y3yyWyCbitllay
OG^babk^oyKyCbitlla%02)3-&yy>FAy520yy>@y4yyWyCbitllay
OOrfkplc@lkpqbii^pyKyCbitlla%04)35&yy>FAy520yy>@y5yyWyCbitllay
OG^abcfobDibkyKyCbitlla%06)5/&yy>FAy520yy>@y6yyWyCbitllay
OBjbo^iaP^k`qr^ovyKyCbitlla%2.)5.&yy>FAy520yy>@y.-yyWyCbitllay
OAb^atllaSfii^dbyKyCbitlla%15)6-&yy>FAy520yy>@y..yyWyCbitllay
OJloilp$>o^kyKyCbitlla%23)54&yy>FAy520yy>@y./yyWyCbitllay

O>pebks^ibyKyOrkfkql>pebks^iby
OQebEltifkdS^ibyKy>pebks^ib%2-)05&yy>FAy512yy>@y..yyWy>pebks^iby
OO^vkbtllaObqob^qyKy>pebks^ib%3.)2.&yy>FAy512yy>@y./yyWy>pebks^iby
OJvpqo^iI^hbyKy>pebks^ib%16)36&yy>FAy512yy>@y.-yyWy>pebks^iby
OFofpI^hbyKy>pebks^ib%13)13&yy>FAy512yy>@y5yyWy>pebks^iby
O>pqo^k^^oyKy>pebks^ib%03)2-&yy>FAy512yy>@y4yyWy>pebks^iby
OQebOrfkplcPq^oarpqyKy>pebks^ib%00)34&yy>FAy512yy>@y6yyWy>pebks^iby
OCfobP`^oPeofkbyKy>pebks^ib%/3)31&yy>FAy512yy>@y3yyWy>pebks^iby
OQebPeofkblc>bppfk^yKy>pebks^ib%//)20&yy>FAy512yy>@y2yyWy>pebks^iby
OQefpqibcroSfii^dbyKy>pebks^ib%03)04&yy>FAy512yy>@y1yyWy>pebks^iby
OJ^bpqo^$pMlpqyKy>pebks^ib%/4)03&yy>FAy512yy>@y0yyWy>pebks^iby
OI^hbC^i^qefjyKy>pebks^ib%/-)1/&yy>FAy512yy>@y/yyWy>pebks^iby
OQebWlo^jPqo^kayKy>pebks^ib%.1)/0&yy>FAy512yy>@y.yyWy>pebks^iby

OA^ohpelobyKyOrkfkqlA^ohpeloby
OQebJ^pqbo$pDi^fsbyKyA^ohpelob%05)53&yy>FAy511yy>@y6yyWyA^ohpeloby
OObjqo^sbi$pBu`^s^qflkyKyA^ohpelob%02)52&yy>FAy511yy>@y5yyWyA^ohpeloby
ODolsblcqeb>k`fbkqpyKyA^ohpelob%10)44&yy>FAy511yy>@y4yyWyA^ohpeloby
O>jbqe$>o^kyKyA^ohpelob%10)24&yy>FAy511yy>@y3yyWyA^ohpeloby
O?^pe^i$>o^kyKyA^ohpelob%11)03&yy>FAy511yy>@y2yyWyA^ohpeloby
O@ifccpmofkdOfsboyKyA^ohpelob%2/)0.&yy>FAy511yy>@y1yyWyA^ohpeloby
OQltbolc>iqe^i^uuyKyA^ohpelob%23)/3&yy>FAy511yy>@y0yyWyA^ohpeloby
OOrfkplcJ^qevpqo^yKyA^ohpelob%25)/-&yy>FAy511yy>@y/yyWyA^ohpeloby
O>r_boafkbyKyA^ohpelob%03)10&yy>FAy511yy>@y.yyWyA^ohpeloby

_>wrobjvpqFpibyKyQ^hb_l^qpqo^fdeqlrqcolj>r_boafkbyyWy>wrobjvpqFpiby
OS^i^^o$p?boqeyKy>wrobjvpqFpib%/.)21&yy>FAy53-yy>@y.3yyWy>wrobjvpqFpiby
OQebBula^oyKyQebBula^o%1.)40&yy>FAy53-yy>@y.2yyWyQebBula^oy
OMla@irpqboyKy>wrobjvpqFpib%04)26&yy>FAy53-yy>@y.-yyWy>wrobjvpqFpiby
O?ofpqibifj_Sfii^dbyKy>wrobjvpqFpib%/3)33&yy>FAy53-yy>@y1yyWy>wrobjvpqFpiby
OPfisbojvpqFpibyKy>wrobjvpqFpib%.0)5-&yy>FAy53-yy>@y.0yyWy>wrobjvpqFpiby
OTo^qep`^ibMlfkqyKy>wrobjvpqFpib%0/)44&yy>FAy53-yy>@y.4yyWy>wrobjvpqFpiby
OLabpvrp$I^kafkdyKy>wrobjvpqFpib%13)4.&yy>FAy53-yy>@y6yyWy>wrobjvpqFpiby
OMlaTob`h^dbyKy>wrobjvpqFpib%20)3.&yy>FAy53-yy>@y..yyWy>wrobjvpqFpiby
ODbbwib$p@^jmyKy>wrobjvpqFpib%26)35&yy>FAy53-yy>@y4yyWy>wrobjvpqFpiby
O>jjbkCloayKy>wrobjvpqFpib%3/)21&yy>FAy53-yy>@y/yyWy>wrobjvpqFpiby
O>jjbkS^ibyKy>wrobjvpqFpib%44)10&yy>FAy53-yy>@y.yyWy>wrobjvpqFpiby
O>wrobT^q`eyKy>wrobjvpqFpib%16)2-&yy>FAy53-yy>@y0yyWy>wrobjvpqFpiby
OJllkdo^wbTllapyKy>wrobjvpqFpib%2/)1/&yy>FAy53-yy>@y5yyWy>wrobjvpqFpiby
OPqfiimfkbEliayKy>wrobjvpqFpib%12)/-&yy>FAy53-yy>@y.1yyWy>wrobjvpqFpiby
OBj_bodi^abyKy>wrobjvpqFpib%25).4&yy>FAy53-yy>@y2yyWy>wrobjvpqFpiby
OC^fo_ofadbPqo^kayKy>wrobjvpqFpib%14)2&yy>FAy53-yy>@y3yyWy>wrobjvpqFpiby
OPfiqfkdPelobyKy>wrobjvpqFpib%1.)1&yy>FAy53-yy>@y./yyWy>wrobjvpqFpiby

O?illajvpqFpibyKy?illajvpqFpib%32)60&yyWy?illajvpqFpiby
OHbppbi$p@olppfkdyKy?illajvpqFpib%3/)56&yy>FAy53.yy>@y5yyWy?illajvpqFpiby
OQebIlpqCliayKy?illajvpqFpib%24)5.&yy>FAy53.yy>@y//yyWy?illajvpqFpiby
O?ofpqibifj_Bk`i^sbyKy?illajvpqFpib%33)45&yy>FAy53.yy>@y4yyWy?illajvpqFpiby
OTo^qep`^ibI^foyKy?illajvpqFpib%36)34&yy>FAy53.yy>@y/4yyWy?illajvpqFpiby
OQeb@ofjplkOb^`eyKy?illajvpqFpib%40)4-&yy>FAy53.yy>@y.5yyWy?illajvpqFpiby
O?illa`ropbFpibyKy?illajvpqFpib%5/)2/&yy>FAy53.yy>@y2yyWy?illajvpqFpiby
OQeb?illa`ropbaObbcyKy?illajvpqFpib%5-)/3&yy>FAy53.yy>@y.3yyWy?illajvpqFpiby
OTvojp`^oFpi^kayKy?illajvpqFpib%45)/5&yy>FAy53.yy>@y/5yyWy?illajvpqFpiby
OQ^ilkPq^kayKy?illajvpqFpib%40)/-&yy>FAy53.yy>@y.1yyWy?illajvpqFpiby
OSbofaf^kMlfkqyKy?illajvpqFpib%41)6&yy>FAy53.yy>@y/2yyWy?illajvpqFpiby
OQebT^omMfpqlkyKy?illajvpqFpib%20).3&yy>FAy53.yy>@y/1yyWy?illajvpqFpiby
OO^dbcb^qeboOfadbyKy?illajvpqFpib%22)02&yy>FAy53.yy>@y./yyWy?illajvpqFpiby
OOrfkplcIlobqe$>o^kyKy?illajvpqFpib%3.)11&yy>FAy53.yy>@y.0yyWy?illajvpqFpiby
O?illaT^q`eyKy?illajvpqFpib%21)22&yy>FAy53.yy>@y3yyWy?illajvpqFpiby
O?i^abtllayKy?illajvpqFpib%13)12&yy>FAy53.yy>@y1yyWy?illajvpqFpiby
O>uu^ofbkyKy?illajvpqFpib%1.)0/&yy>FAy53.yy>@y/yyWy?illajvpqFpiby
OQeb?illat^peyKy?illajvpqFpib%05)/-&yy>FAy53.yy>@y.4yyWy?illajvpqFpiby
OQebEfaabkObbcyKy?illajvpqFpib%01)/0&yy>FAy53.yy>@y/.yyWy?illajvpqFpiby
OSfkaf`^qlo$pObpqyKy?illajvpqFpib%0-)12&yy>FAy53.yy>@y/3yyWy?illajvpqFpiby
OQebClriMlliyKy?illajvpqFpib%/6)03&yy>FAy53.yy>@y/-yyWy?illajvpqFpiby
OQbi$^qeflk$p@^jmyKy?illajvpqFpib%/2)1/&yy>FAy53.yy>@y.2yyWy?illajvpqFpiby
O>j_botb_M^ppyKy?illajvpqFpib%//)04&yy>FAy53.yy>@y.yyWy?illajvpqFpiby
OQebSb`qlo@lfiyKy?illajvpqFpib%.6)2/&yy>FAy53.yy>@y/0yyWy?illajvpqFpiby
OQeb@ovl*@lobyKy?illajvpqFpib%06)3.&yy>FAy53.yy>@y.6yyWy?illajvpqFpiby
OK^wwfsf^kyKy?illajvpqFpib%05)46&yy>FAy53.yy>@y..yyWy?illajvpqFpiby
O?i^`hpfiqPelobyKy?illajvpqFpib%0.)54&yy>FAy53.yy>@y0yyWy?illajvpqFpiby
OJvpqtllayKy?illajvpqFpib%11)51&yy>FAy53.yy>@y.-yyWy?illajvpqFpiby
OJfaabks^ibyKy?illajvpqFpib%2.)43&yy>FAy53.yy>@y6yyWy?illajvpqFpiby

_A^ohpelobyKy>wrobjvpqFpib%/.)21&yyWy>wrobjvpqFpiby
_Qbiao^ppfiyKy?l^qqlqebIbcq^pvlreb^aqlt^oa>r_boafkby
OOrq$qebo^kSfii^dbyKyQbiao^ppfi%22)6.&yy>FAy51/yy>@y..yyWyQbiao^ppfiy
OA^ok^pprpyKyQ^hbMloq^ifkqlA^ok^pprp+%/2)22&yy>FAy51/yy>@y.-yyWyQbiao^ppfiy
OQbiao^ppfiyKyOrklrqlcA^ok^pprp%05)20&yyWyQbiao^ppfiy
OQebLo^`ibDi^abyKyQbiao^ppfi%05)0-&yy>FAy51/yy>@y5yyWyQbiao^ppfiy
OTbiipmofkdI^hbyKyQbiao^ppfi%1/)1-&yy>FAy51/yy>@y6yyWyQbiao^ppfiy
O?^k$bqefiEliiltyKyQbiao^ppfi%13)2.&yy>FAy51/yy>@y/yyWyQbiao^ppfiy
OMlliplc>oifqeofbkyKyQbiao^ppfi%1-)32&yy>FAy51/yy>@y3yyWyQbiao^ppfiy
ODk^oimfkbEliayKyQbiao^ppfi%1.)44&yy>FAy51/yy>@y1yyWyQbiao^ppfiy
OI^hb>i$>jbqeyKyQbiao^ppfi%21)35&yy>FAy51/yy>@y2yyWyQbiao^ppfiy
OAli^k^^oyKyQbiao^ppfi%22)25&yy>FAy51/yy>@y0yyWyQbiao^ppfiy
OPq^o_obbwbSfii^dbyKyQbiao^ppfi%33)24&yy>FAy51/yy>@y4yyWyQbiao^ppfiy
OPe^altdibkyKyQbiao^ppfi%3-)10&yy>FAy51/yy>@y.yyWyQbiao^ppfiy

EA^i^o^kyRy3615y
OLodofjj^oyKyQ^hbmloq^ifkA^i^o^kqlLodofjj^oy

OArolq^o
OPhriiOl`hyKyArolq^o%21).-&yy>FAy4/5yy>@y.-yyWyArolq^oy
OAovdri`eO^sfkbyKyArolq^o%20)/0&yy>FAy4/5yy>@y6yyWyArolq^oy
OO^wloEfiiyKyArolq^o%20)10&yy>FAy4/5yy>@y3yyWyArolq^oy
OQfo^d^oabHbbmyKyArolq^o%24)21&yy>FAy4/5yy>@y2yyWyArolq^oy
OPbk$gfkSfii^dbyKyArolq^o%22)41&yy>FAy4/5yy>@y/yyWyArolq^oy
OB`elFpibpyKyArolq^o%3/)5.&yy>FAy4/5yy>@y1yyWyArolq^oy
OHlih^o@o^dyKyArolq^o%15)45&yy>FAy4/5yy>@y0yyWyArolq^oy
OS^iibvlcQof^ipyKyArolq^o%11)26&yy>FAy4/5yy>@y.yyWyArolq^oy
OO^wloj^kbDolrkapyKyArolq^o%1.)12&yy>FAy4/5yy>@y4yyWyArolq^oy
OC^oT^q`eMlpqyKyQeb?^oobkp%3.)/.&yy>FAy42-yy>@y6yyWyQeb?^oobkpy
OQerkaboOfadbyKyArolq^o%06)/5&yy>FAy4/5yy>@y5yyWyArolq^oy

O?lriaboIlabJfkbyKyQeb?^oobkp%3.)1&yy>FAy42-yy>@y.yyWyQeb?^oobkpy
OQebPiradbCbkyKyQeb?^oobkp%23)4&yy>FAy42-yy>@y/yyWyQeb?^oobkpy
OAob^ajfpqMb^hyKyQeb?^oobkp%13).3&yy>FAy42-yy>@y1yyWyQeb?^oobkpy
ODoli$aljC^ojyKyQeb?^oobkp%22)/-&yy>FAy42-yy>@y5yyWyQeb?^oobkpy
OQelokEfiiyKyQeb?^oobkp%20)/1&yy>FAy42-yy>@y.-yyWyQeb?^oobkpy
OQeb@olppol^apyKyQeb?^oobkp%2.)0-&yy>FAy42-yy>@y..yyWyQeb?^oobkpy
CO^q`ebqyKyOrkfcvlralk$qe^sbcifdeqm^qey
OO^q`ebqyKyQeb?^oobkp%3/)04&yy>FAy42-yy>@y.0yyWyQeb?^oobkpy
OQebJbo`e^kq@l^pqyKyQeb?^oobkp%30)10&yy>FAy42-yy>@y.1yyWyQeb?^oobkpy
OKloqet^q`eEliayKyQeb?^oobkp%3/)2.&yy>FAy42-yy>@y.2yyWyQeb?^oobkpy
OO^mqloDolrkapyKyQeb?^oobkp%24)2/&yy>FAy42-yy>@y.3yyWyQeb?^oobkpy
OQebPq^dk^kqL^pfpyKyQeb?^oobkp%22)1/&yy>FAy42-yy>@y./yyWyQeb?^oobkpy
OIrpet^qboL^pfpyKyQeb?^oobkp%13)06&yy>FAy42-yy>@y.4yyWyQeb?^oobkpy
OQebClodlqqbkMllipyKyQeb?^oobkp%12)//&yy>FAy42-yy>@y3yyWyQeb?^oobkpy
OQebAovEfiipyKyQeb?^oobkp%06).1&yy>FAy42-yy>@y2yyWyQeb?^oobkpy
OElklo$pPq^kayKyQeb?^oobkp%05)/5&yy>FAy42-yy>@y4yyWyQeb?^oobkpy

OPqlkbq^ilkJlrkq^fkp
O@^jm>m^o^gbyKyPqlkbq^ilkJlrkq^fkp%43)6/&yy>FAy514yy>@y.yyWyPqlkbq^ilkJlrkq^fkpy
OJ^i^h^$gfkyKyPqlkbq^ilkJlrkq^fkp%4/)60&yy>FAy514yy>@y0yyWyPqlkbq^ilkJlrkq^fkpy
ODofjqlqbjMlpqyKyPqlkbq^ilkJlrkq^fkp%42)53&yy>FAy514yy>@y/yyWyPqlkbq^ilkJlrkq^fkpy
OTb_tfkaboM^qeyKyPqlkbq^ilkJlrkq^fkp%36)54&)%24)33&yy>FAy514yy>@y1yyWyPqlkbq^ilkJlrkq^fkpy
O?lriabopifabO^sfkbyKyPqlkbq^ilkJlrkq^fkp%32)6.&yy>FAy514yy>@y2yyWyPqlkbq^ilkJlrkq^fkpy
OPfpefo@^kvlkyKyPqlkbq^ilkJlrkq^fkp%21)42&yy>FAy514yy>@y3yyWyPqlkbq^ilkJlrkq^fkpy
OTfkapeb^o@o^dyKyPqlkbq^ilkJlrkq^fkp%35)15&yy>FAy514yy>@y4yyWyPqlkbq^ilkJlrkq^fkpy
OPrkOl`hObqob^qyKyPqlkbq^ilkJlrkq^fkp%16)3-&yy>FAy514yy>@y5yyWyPqlkbq^ilkJlrkq^fkpy
OJfohc^iilkI^hbyKyPqlkbq^ilkJlrkq^fkp%15)1-&yy>FAy514yy>@y.-yyWyPqlkbq^ilkJlrkq^fkpy
OPqlkbq^ilkMb^hyKyPqlkbq^ilkJlrkq^fkp%03)./&yy>FAy514yy>@y..yyWyPqlkbq^ilkJlrkq^fkpy
OQeb@e^oobaS^ibyKyPqlkbq^ilkJlrkq^fkp%0/)32&yy>FAy514yy>@y6yyWyPqlkbq^ilkJlrkq^fkpy

OAbpli^`byKyAbpli^`b%2/)4&yyWyAbpli^`by
OQbqeofp>o^kyKyAbpli^`b%21).0&yy>FAy515yy>@y.yyWyAbpli^`by
OKfgbi$pMlfkqyKyAbpli^`b%30).1&yy>FAy515yy>@y/yyWyAbpli^`by
OQerkabo>ubCloqobppyKyAbpli^`b%22)/5&yy>FAy515yy>@y1yyWyAbpli^`by
OBqebiObqeloyKyAbpli^`b%05)/5&yy>FAy515yy>@y4yyWyAbpli^`by
OO^k^wg^oFpibyKyAbpli^`b%/5)6&yy>FAy515yy>@y.2yyWyAbpli^`by
OHlojbh$pErqyKyAbpli^`b%3/)06&yy>FAy515yy>@y2yyWyAbpli^`by
OP^odbolkyKyAbpli^`b%43)/.&yy>FAy515yy>@y0yyWyAbpli^`by
OHlih^oSfii^dbyKyAbpli^`b%40)15&yy>FAy515yy>@y3yyWyAbpli^`by
OJ^do^jSfii^dbyKyAbpli^`b%4/)40&yy>FAy515yy>@y.0yyWyAbpli^`by
OPe^alt_ob^hO^sfkbyKyAbpli^`b%46)44&yy>FAy515yy>@y.1yyWyAbpli^`by
OHlalDo^sbv^oayKyAbpli^`b%2-)24&yy>FAy515yy>@y6yyWyAbpli^`by
OJ^kklol`@lsbkyKyAbpli^`b%2/)43&yy>FAy515yy>@y./yyWyAbpli^`by
ODbihfpSfii^dbyKyAbpli^`b%01)53&yy>FAy515yy>@y..yyWyAbpli^`by
OS^iibvlcPmb^opyKyAbpli^`b%00)25&yy>FAy515yy>@y5yyWyAbpli^`by
OPe^altmobvSfii^dbyKyAbpli^`b%/1)4-&yy>FAy515yy>@y.-yyWyAbpli^`by

OCbo^i^pyKyCbo^i^p%11)/&yyWyCbo^i^py
OOrfkplcO^sbktfkayKyCbo^i^p%1-)./&yy>FAy516yy>@y1yyWyCbo^i^py
OAob^j?lrdeyKyCbo^i^p%2.)6&yy>FAy516yy>@y.yyWyCbo^i^py
OLkbfolpyKyCbo^i^p%21).3&yy>FAy516yy>@y0yyWyCbo^i^py
OQebQtfk@lilpp^ipyKyCbo^i^p%13).5&yy>FAy516yy>@y2yyWyCbo^i^py
OQebClodlqqbk@l^pqyKyCbo^i^p%12)16&yy>FAy516yy>@y3yyWyCbo^i^py
OP^oaloFpibyKyCbo^i^p%/6)16&yy>FAy516yy>@y.2yyWyCbo^i^py
OFpiblcAob^ayKyCbo^i^p%01)45&yy>FAy516yy>@y.3yyWyCbo^i^py
OCbo^iP`^oS^ibyKyCbo^i^p%21)23&yy>FAy516yy>@y5yyWyCbo^i^py
OCo^vcb^qeboEfdei^kapyKyCbo^i^p%21)36&yy>FAy516yy>@y6yyWyCbo^i^py
OOrfkplcFpfiafbkyKyCbo^i^p%26)36&yy>FAy516yy>@y.-yyWyCbo^i^py
OAfobJ^riyKyCbo^i^p%26)11&yy>FAy516yy>@y4yyWyCbo^i^py
ODofjqlqbj@ljmlrkayKyCbo^i^p%36)1-&yy>FAy516yy>@y.0yyWyCbo^i^py
ODloarkkfLrqmlpqyKyCbo^i^p%44)0.&yy>FAy516yy>@y.1yyWyCbo^i^py
O@^jmJlg^`ebyKyCbo^i^p%42)1/&yy>FAy516yy>@y./yyWyCbo^i^py
OIltboTfiapyKyCbo^i^p%40)20&yy>FAy516yy>@y/yyWyCbo^i^py
OQebTofqefkdAbbmyKyCbo^i^p%42)3.&yy>FAy516yy>@y..yyWyCbo^i^py

OQelrp^kaKbbaibp
O@^jmB$qelhyKyQelrp^kaKbbaibp%.5)/.&yy>FAy513yy>@y5yyWyQelrp^kaKbbaibpy
OEfdembo`eyKyQelrp^kaKbbaibp%./)01&yy>FAy513yy>@y6yyWyQelrp^kaKbbaibpy
OQebP`obb`efkd@^kvlkyKyQelrp^kaKbbaibp%/5)14&yy>FAy513yy>@y0yyWyQelrp^kaKbbaibpy
OA^oh`ilraMfkk^`ibyKyQelrp^kaKbbaibp%0/)02&yy>FAy513yy>@y/yyWyQelrp^kaKbbaibpy
OPmifqellc@o^dyKyQelrp^kaKbbaibp%1-)04&yy>FAy513yy>@y2yyWyQelrp^kaKbbaibpy
OCobbtfkaMlpqyKyQelrp^kaKbbaibp%12)2-&yy>FAy513yy>@y1yyWyQelrp^kaKbbaibpy
OTfka_ob^h@^kvlkyKyQelrp^kaKbbaibp%3-)20&yy>FAy513yy>@y3yyWyQelrp^kaKbbaibpy
OQebPefjjbofkdCi^qpyKyQelrp^kaKbbaibp%42)35&yy>FAy513yy>@y4yyWyQelrp^kaKbbaibpy

OQ^k^ofp
OD^adbqw^kyKyQ^k^ofp%2-)/5&yy>FAy52.yy>@y.yyWyQ^k^ofpy
OKllkpe^abOrfkpyKyQ^k^ofp%3-)/2&yy>FAy52.yy>@y0yyWyQ^k^ofpy
OPqb^jtebbaibMloqyKyQ^k^ofp%34)/0&yy>FAy52.yy>@y1yyWyQ^k^ofpy
OW^i^pegf$pAbkyKyQ^k^ofp%34)0/&yy>FAy52.yy>@y2yyWyQ^k^ofpy
OIlpqOfddbo@lsbyKyQ^k^ofp%40)13&yy>FAy52.yy>@y3yyWyQ^k^ofpy
OT^qbopmofkdCfbiayKyQ^k^ofp%3-)03&yy>FAy52.yy>@y4yyWyQ^k^ofpy
O?olhbkMfii^oyKyQ^k^ofp%2/)12&yy>FAy52.yy>@y6yyWyQ^k^ofpy
O@^sbokplcQfjbyKyQ^k^ofp%32)16&yy>FAy52.yy>@y/-yyWyQ^k^ofpy
OPlrqe_ob^hPelobyKyQ^k^ofp%31)3-&yy>FAy52.yy>@y./yyWyQ^k^ofpy
OI^ka$pBka?b^`eyKyQ^k^ofp%21)6/&yy>FAy52.yy>@y.2yyWyQ^k^ofpy
OQebD^mfkd@e^pjyKyQ^k^ofp%2/)34&yy>FAy52.yy>@y.0yyWyQ^k^ofpy
OB^pqjllkOrfkpyKyQ^k^ofp%14)32&yy>FAy52.yy>@y.1yyWyQ^k^ofpy
OPlrqejllkOrfkpyKyQ^k^ofp%1-)4/&yy>FAy52.yy>@y.3yyWyQ^k^ofpy
OS^iibvlcqebT^q`ebopyKyQ^k^ofp%03)44&yy>FAy52.yy>@y.4yyWyQ^k^ofpy
OQefpqibpeor_S^iibvyKyQ^k^ofp%/6)31&yy>FAy52.yy>@y.5yyWyQ^k^ofpy
OArkbj^ri@ljmlrkayKyQ^k^ofp%1-)24&yy>FAy52.yy>@y..yyWyQ^k^ofpy
OQebKluflrpI^foyKyQ^k^ofp%03)10&yy>FAy52.yy>@y.-yyWyQ^k^ofpy
O>_vpp^iP^kapyKyQ^k^ofp%12)1.&yy>FAy52.yy>@y5yyWyQ^k^ofpy
OP^kaplooltT^q`eyKyQ^k^ofp%05)/4&yy>FAy52.yy>@y/yyWyQ^k^ofpy
OWri$C^oo^hyKyQ^k^ofp%05).3&yy>FAy52.yy>@y.6yyWyQ^k^ofpy

CJ^ope^i$pObcrdbyKyRk$Dlol@o^qboy
OI^hh^ofQ^oMfqpyKyRk$Dlol@o^qbo%2-)/.&yy>FAy521yy>@y4yyWyRk$Dlol@o^qboy
OFolkpqlkbMi^qb^ryKyRk$Dlol@o^qbo%46)/4&yy>FAy521yy>@y3yyWyRk$Dlol@o^qboy
OQebJ^opei^kapyKyRk$Dlol@o^qbo%35)31&yy>FAy521yy>@y2yyWyRk$Dlol@o^qboy
OQebPifqebofkdP`^oyKyRk$Dlol@o^qbo%2-)46&yy>FAy521yy>@y1yyWyRk$Dlol@o^qboy
OQbooloOrkyKyRk$Dlol@o^qbo%0/)34&yy>FAy521yy>@y0yyWyRk$Dlol@o^qboy
ODli^hh^ElqPmofkdpyKyRk$Dlol@o^qbo%04)23&yy>FAy521yy>@y/yyWyRk$Dlol@o^qboy
OCfobMirjbOfadbyKyRk$Dlol@o^qbo%2.)14&yy>FAy521yy>@y.yyWyRk$Dlol@o^qboy

OPfifqerpyKyPfifqerp%52)./&yyWyPfifqerpy
OS^ilo$pObpqyKyPfifqerp%5.)/-&yy>FAy523yy>@y/yyWyPfifqerpy
OPq^debijMlfkqyKyPfifqerp%4-)/2&yy>FAy523yy>@y4yyWyPfifqerpy
O@bk^oflkEliayKyPfifqerp%2-)01&yy>FAy523yy>@y0yyWyPfifqerpy
OQeb@ovpq^iS^ibyKyPfifqerp%//).4&yy>FAy523yy>@y.yyWyPfifqerpy
OEfsb$Wlo^yKyPfifqerp%/3)26&yy>FAy523yy>@y1yyWyPfifqerpy
OQebP`^o^_T^iiyKyPfifqerp%/6)60&yy>FAy523yy>@y3yyWyPfifqerpy
OEfsb$Obd^iyKyPfifqerp%21)46&yy>FAy523yy>@y2yyWyPfifqerpy

EA^i^o^kyRy3615y
OQerkabo?irccyKyQ^hbmloq^ifkA^i^o^kqlQerkabo?irccy

OTfiaj^kbT^qboTbiiyKyJridlob%1/).1&yy>FAy403yy>@y.0yyWyJridloby
OTfkacrovOfadbyKyJridlob%2/)..&yy>FAy403yy>@y./yyWyJridloby
OObaOl`hpyKyJridlob%3-)/.&yy>FAy403yy>@y..yyWyJridloby
OQebDliabkMi^fkpyKyJridlob%16)02&yy>FAy403yy>@y5yyWyJridloby
OQerkaboelokT^qboTbiiyKyJridlob%11)12&yy>FAy403yy>@y6yyWyJridloby
O?^bi$arkAfdpfqbyKyJridlob%0/)15&yy>FAy403yy>@y.-yyWyJridloby
OM^ibj^kbOl`hyKyJridlob%01)3/&yy>FAy403yy>@y/yyWyJridloby
O?illaellcSfii^dbyKyJridlob%16)25&yy>FAy403yy>@y0yyWyJridloby
OOba@ilraJbp^yKyJridlob%06)5/&yy>FAy403yy>@y.yyWyJridloby
OTfkqboellcT^qboTbiiyKyJridlob%20)33&yy>FAy403yy>@y1yyWyJridloby
OO^s^dba@^o^s^kyKyJridlob%20)14&yy>FAy403yy>@y4yyWyJridloby
OQebSbkqrob@l+JfkbyKyJridlob%3/)15&yy>FAy403yy>@y3yyWyJridloby
OQebOliifkdMi^fkpyKyJridlob31)30&yy>FAy403yy>@y2yyWyJridloby

OQeb?^oobkp
O@^jmQ^ro^glyKyQeb?^oobkp%12)3-&yy>FAy42-yy>@y/-yyWyQeb?^oobkpy
O>d^j^$dloyKyQeb?^oobkp%10)15&yy>FAy42-yy>@y.5yyWyQeb?^oobkpy
O?o^j_ibp`^oyKyQeb?^oobkp%2.)21&yy>FAy42-yy>@y.6yyWyQeb?^oobkpy
OCfbialcDf^kqpyKyQeb?^oobkp%14)4-&yy>FAy42-yy>@y/.yyWyQeb?^oobkpy
O?i^`hqelokOfadbyKyQeb?^oobkp%10)46&yy>FAy42-yy>@y//yyWyQeb?^oobkpy
OO^wlocbkHo^riyKyQeb?^oobkp%1.)53&yy>FAy42-yy>@y/1yyWyQeb?^oobkpy
OQebDob^qIfcqyKyVlre^sbql_bfkQelrp^kaKbbaibpcloqefplkb)pldbq`ilpbqlqebifcq+%0.)/0&yy>FAy513yy>@y.yyWyQelrp^kaKbbaibpy
OO^wlocbkAltkpyKyQeb?^oobkp%14)6-&yy>FAy42-yy>@y/2yyWyQeb?^oobkpy
O?^biJla^kyKyQeb?^oobkp%14)51&yy>FAy42-yy>@y/0yyWyQeb?^oobkpy

OArpqt^iiltJ^ope
OQebNr^djfobyKyArpqt^iiltJ^ope%1.)2.&yy>FAy52-yy>@y1yyWyArpqt^iiltJ^opey
OQebAbklcCi^jbyKyArpqt^iiltJ^ope%05)32&yy>FAy52-yy>@y2yyWyArpqt^iiltJ^opey
OTvoj_ldyKyArpqt^iiltJ^ope%2/)40&yy>FAy52-yy>@y3yyWyArpqt^iiltJ^opey
C?o^`hbkt^iiSfii^dbyKyAvpifuPfisbodor_%10)4/&yy>FAy52-yy>@y0yyWyArpqt^iiltJ^opey
OTfq`eEfiiyKyArpqt^iiltJ^ope%2/)/4&yy>FAy52-yy>@y/yyWyArpqt^iiltJ^opey
OQebo^jlobFpibyKyArpqt^iiltJ^ope%33)11&yy>FAy52-yy>@y.yyWyArpqt^iiltJ^opey
O>i`^wFpi^kayKyArpqt^iiltJ^ope%4/).6&yy>FAy52-yy>@y4yyWyArpqt^iiltJ^opey

KDrfab@ljmibqb
]]
end)
