DugisGuideViewer:RegisterGuide("Exploration Eastern Kingdom Achievement (60+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-(+J^hbprobA^i^o^kfpvlrEb^oqeil`^qflk+Fcvlralk$qdbqqeb^ob^prk`lsboba^qqebil`^qflkmolsfaba)jlsb^olrka^_fqfkqe^qil`^qflk)fq$pqebob+J^hbprobvlrpq^vfkqebil`^qflkilkdbklrdeqlafp`lsbofq+y

eA^i^o^kyKyJ^hbA^i^o^kvlroeljb%32+3)0/+/&Dbqqfkdql^kacoljqebpbil`^qflktfii_bb^pfbocoljA^i^o^k+yyWyA^i^o^ky
OLodofjj^oyKyQ^hbmloq^ifkA^i^o^kqlLodofjj^o%22+1)/2+2&yyWyA^i^o^ky
CO^q`ebqyKyCivqlO^q`ebq%12+.)30+6&yyWyLodofjj^oy
_?llqv?^vyKyQ^hbqeb_l^qql?llqv?^v%30+4)05+3&yyWyQeb?^oobkpy

O?llqv?^vyKyPqo^kdibqelokS^ib%/4)40&yy>FAy45.yy>@y.yyWyPqo^kdibqelokS^iby
OTfiaPelobyKyPqo^kdibqelokS^ib%0/)44&yy>FAy45.yy>@y3yyWyPqo^kdibqelokS^iby
OG^drbolFpibyKyPqo^kdibqelokS^ib%05)5.&yy>FAy45.yy>@y/3yyWyPqo^kdibqelokS^iby
OJfpqs^ibS^iibvyKyPqo^kdibqelokS^ib%01)31&yy>FAy45.yy>@y5yyWyPqo^kdibqelokS^iby
OKbh$j^kfTbiipmofkdyKyPqo^kdibqelokS^ib%/5)3/&yy>FAy45.yy>@y4yyWyPqo^kdibqelokS^iby
O?illap^fi@ljmlrkayKyPqo^kdibqelokS^ib%/0)2.&yy>FAy45.yy>@y6yyWyPqo^kdibqelokS^iby
ODror_^pef>obk^yKyPqo^kdibqelokS^ib%0-)15&yy>FAy45.yy>@y.1yyWyPqo^kdibqelokS^iby
OOrfkplcGr_rt^iyKyPqo^kdibqelokS^ib%02)2.&yy>FAy45.yy>@y..yyWyPqo^kdibqelokS^iby
OOrfkplc>_lo^wyKyPqo^kdibqelokS^ib%06)25&yy>FAy45.yy>@y.-yyWyPqo^kdibqelokS^iby
O@ovpq^isbfkJfkbyKyPqo^kdibqelokS^ib%1-)2-&yy>FAy45.yy>@y./yyWyPqo^kdibqelokS^iby
OOrfkplcWri$J^jtbyKyPqo^kdibqelokS^ib%13)1.&yy>FAy45.yy>@y.2yyWyPqo^kdibqelokS^iby
OWf^q^$g^fOrfkpyKyPqo^kdibqelokS^ib%1/)03&yy>FAy45.yy>@y.0yyWyPqo^kdibqelokS^iby
O?^if^$j^eOrfkpyKyPqo^kdibqelokS^ib%13)0/&yy>FAy45.yy>@y.3yyWyPqo^kdibqelokS^iby
OJlpe$LddLdobJlrkayKyPqo^kdibqelokS^ib%15)/5&yyy>FAy45.yy>@y.5yyWyPqo^kdibqelokS^ibyv
OJfwg^eOrfkpyKyPqo^kdibqelokS^ib%03)0-&yy>FAy45.yy>@y.4yyWyPqo^kdibqelokS^iby
ODolj$dli?^pb@^jmyKyPqo^kdibqelokS^ib%0/)/5&yy>FAy45.yy>@y0yyWyPqo^kdibqelokS^iby
OH^i$^fOrfkpyKyPqo^kdibqelokS^ib%01)//&yy>FAy45.yy>@y/.yyWyPqo^kdibqelokS^iby
O?^i$i^iOrfkpyKyPqo^kdibqelokS^ib%/6).6&yy>FAy45.yy>@y//yyWyPqo^kdibqelokS^iby
OQebSfibObbcyKyPqo^kdibqelokS^ib%/2)/4&yyy>FAy45.yy>@y/0yyWyPqo^kdibqelokS^iby
OWrria^f^OrfkpyKyPqo^kdibqelokS^ib%/.).1&yy>FAy45.yy>@y/1yyWyPqo^kdibqelokS^iby
OOrfkplcWri$Hrka^yKyPqo^kdibqelokS^ib%/1)..&yy>FAy45.yy>@y/2yyWyPqo^kdibqelokS^iby
OKbpfkdt^ov$pBumbafqflkyKyPqo^kdibqelokS^ib%02).-&yy>FAy45.yy>@y/yyWyPqo^kdibqelokS^iby
OI^hbK^wcbofqfyKyPqo^kdibqelokS^ib%1-).6&yy>FAy45.yy>@y/-yyWyPqo^kdibqelokS^iby
OSbkqrob@l+?^pb@^jmyKyPqo^kdibqelokS^ib%11)/-&yy>FAy45.yy>@y.6yyWyPqo^kdibqelokS^iby
OWri$Dror_yKyPqo^kdibqelokS^ib%20).4&yy>FAy45.yy>@y/4yyWyPqo^kdibqelokS^iby
OHrowbk$p@ljmlrkayKyPqo^kdibqelokS^ib%12).-&yy>FAy45.yy>@y2yyWyPqo^kdibqelokS^iby
OOb_bi@^jmyKyPqo^kdibqelokS^ib%05)1&yy>FAy45.yy>@y1yyWyPqo^kdibqelokS^iby

OArphtllayKyOrkfkqlArphtllay
OQebVlodbkC^ojpqb^ayKyArphtlla%16)40&yy>FAy445yy>@y4yyWyArphtllay
OQebOlqqfkdLo`e^oayKyArphtlla%30)4/&yy>FAy445yy>@y6yyWyArphtllay
OQo^knrfiD^oabkp@bjbqbovyKyArphtlla%45)36&yy>FAy445yy>@y.-yyWyArphtllay
OA^ohpefobyKyArphtlla%41)13&yy>FAy445yy>@y..yyWyArphtllay
OAb^aj^k$p@olppfkdyKyAb^atfkaM^pp%1/)01&yy>FAy444yy>@y.yyWyAb^atfkaM^ppy
OJ^kloJfpqj^kqibyKyArphtlla%44)02&yy>FAy445yy>@y./yyWyArphtllay
O?ofdeqtllaDolsbyKyArphtlla%31)04&yy>FAy445yy>@y5yyWyArphtllay
OQtfifdeqDolsbyKyArphtlla%13)2-&yy>FAy445yy>@y3yyWyArphtllay
OSri$DliLdobJlrkayKyArphtlla%02)4/&yy>FAy445yy>@y2yyWyArphtllay
O>aaib$pPqb^ayKyArphtlla%/.)35&yy>FAy445yy>@y/yyWyArphtllay
OO^sbkEfiiyKyArphtlla%/-)22&yy>FAy445yy>@y0yyWyArphtllay
OO^sbkEfii@bjbqbovyKyArphtlla%/-)1/&yy>FAy445yy>@y1yyWyArphtllay
OQebErpeba?^khyKyArphtlla%6)16&yy>FAy445yy>@y.yyWyArphtllay

OPbkqfkbiEfiiyKyTbpqc^ii%24)2/&yy>FAy5-/yy>@y.yyWyTbpqc^iiy
OQebAb^a>`obyKyTbpqc^ii%3/)3-&yy>FAy5-/yy>@y5yyWyTbpqc^iiy
OQebArpqMi^fkpyKyTbpqc^ii%31)4/&yy>FAy5-/yy>@y.1yyWyTbpqc^iiy
OQebA^ddboEfiipyKyTbpqc^ii%14)45&yy>FAy5-/yy>@y.0yyWyTbpqc^iiy
OJllk_ollhyKyTbpqc^ii%10)36&yy>FAy5-/yy>@y6yyWyTbpqc^iiy
OTbpqc^iiIfdeqelrpbyKyTbpqc^ii%0-)53&yy>FAy5-/yy>@y./yyWyTbpqc^iiy
OAbjlkq$pMi^`byKyTbpqc^ii%0/)32&yy>FAy5-/yy>@y..yyWyTbpqc^iiy
O>ibupqlkC^ojpqb^ayKyTbpqc^ii%05)2/&yy>FAy5-/yy>@y.-yyWyTbpqc^iiy
ODlia@l^pqNr^oovyKyTbpqc^ii%0/)10&yy>FAy5-/yy>@y4yyWyTbpqc^iiy
OQebJlipbkC^ojyKyTbpqc^ii%11)02&yy>FAy5-/yy>@y3yyWyTbpqc^iiy
OG^kdlilabJfkbyKyTbpqc^ii%11)/2&yy>FAy5-/yy>@y2yyWyTbpqc^iiy
OCroi_olt$pMrjmhfkC^ojyKyTbpqc^ii%2.)//&yy>FAy5-/yy>@y0yyWyTbpqc^iiy
OP^iab^k$pC^ojyKyTbpqc^ii%21)0/&yy>FAy5-/yy>@y/yyWyTbpqc^iiy
OQebG^kpbkPqb^ayKyTbpqc^ii%25).4&yy>FAy5-/yy>@y1yyWyTbpqc^iiy

OBitvkkClobpqyKyOrkfkqlBitvkkClobpqy
OClobpq$pBadbyKyBitvkkClobpq%/4)44&yy>FAy443yy>@y2yyWyBitvkkClobpqy
OPqlojtfka@fqvyKyVlre^sbqlorkfkqlPlotfka@fqv)tef`etfiici^dvlrMSMlk^MSBpbosbo+%0/)15&yy>FAy443yy>@y1yyWyBitvkkClobpqy
OKloqepefobS^iibvyKyBitvkkClobpq%12)14&yy>FAy443yy>@y.yyWyBitvkkClobpqy
ODliapefobyKyBitvkkClobpq%1/)32&yy>FAy443yy>@y/yyWyBitvkkClobpqy
O@ovpq^iI^hbyKyBitvkkClobpq%2/)33&yy>FAy443yy>@y..yyWyBitvkkClobpqy
OC^odlabbmJfkbyKyBitvkkClobpq%05)5/&yy>FAy443yy>@y0yyWyBitvkkClobpqy
OGbola$pI^kafkdyKyBitvkkClobpq%15)54&yy>FAy443yy>@y3yyWyBitvkkClobpqy
OQebA^ohbkba?^khyKyArphtlla%20)./&yy>FAy445yy>@y.0yyWyArphtllay
O?o^`htbiiMrjmhfkM^q`eyKyBitvkkClobpq%36)46&yy>FAy443yy>@y5yyWyBitvkkClobpqy
OQltbolc>wlo^yKyBitvkkClobpq%31)4-&yy>FAy443yy>@y4yyWyBitvkkClobpqy
OPqlkb@^fokI^hbyKyBitvkkClobpq%40)25&yy>FAy443yy>@y./yyWyBitvkkClobpqy
OB^pqs^ibIlddfkd@^jmyKyBitvkkClobpq%5.)33&yy>FAy443yy>@y6yyWyBitvkkClobpqy
OOfadbmlfkqQltboyKyBitvkkClobpq%51)46&yy>FAy443yy>@y.-yyWyBitvkkClobpqy

OObaofadbJlrkq^fkpyKyOrkfkqlObaofadbJlrkq^fkp%6)4/&yyWyObaofadbJlrkq^fkpy
OQeobb@lokbopyKyObaofadbJlrkq^fkp%.2)4.&yy>FAy45-yy>@y0yyWyObaofadbJlrkq^fkpy
OI^hbofadbEfdet^vyKyObaofadbJlrkq^fkp%01)43&yy>FAy45-yy>@y1yyWyObaofadbJlrkq^fkpy
OObkabo$pS^iibvyKyObaofadbJlrkq^fkp%40)44&yy>FAy45-yy>@y5yyWyObaofadbJlrkq^fkpy
OPqlkbt^q`eC^iipyKyObaofadbJlrkq^fkp%40)3/&yy>FAy45-yy>@y.-yyWyObaofadbJlrkq^fkpy
OD^i^oabiiS^iibvyKyObaofadbJlrkq^fkp%46)1/&yy>FAy45-yy>@y..yyWyObaofadbJlrkq^fkpy
OPqlkbt^q`eyKyObaofadbJlrkq^fkp%33)20&yy>FAy45-yy>@y4yyWyObaofadbJlrkq^fkpy
O>iqebo$pJfiiyKyObaofadbJlrkq^fkp%20)1/&yy>FAy45-yy>@y3yyWyObaofadbJlrkq^fkpy
OI^hbBsbopqfiiyKyObaofadbJlrkq^fkp%02)20&yy>FAy45-yy>@y/yyWyObaofadbJlrkq^fkpy
OI^hbpefobyKyObaofadbJlrkq^fkp%/5)14&yy>FAy45-yy>@y.yyWyObaofadbJlrkq^fkpy
OObaofadb@^kvlkpyKyObaofadbJlrkq^fkp%00)/0&yy>FAy45-yy>@y2yyWyObaofadbJlrkq^fkpy
OObkabo$p@^jmyKyObaofadbJlrkq^fkp%1/).4&yy>FAy45-yy>@y6yyWyObaofadbJlrkq^fkpy

O?rokfkdPqbmmbpyKyOrkfkqlqeb?rokfdkPqbmmbp%45)46&yyWy?rokfkdPqbmmbpy
O?i^`hol`hM^ppyKy?rokfkdPqbmmbp%44)35&yy>FAy442yy>@y1yyWy?rokfkdPqbmmbpy
OJlod^k$pSfdfiyKy?rokfkdPqbmmbp%51)35&yy>FAy442yy>@y/yyWy?rokfkdPqbmmbpy
OQbooloTfkdM^qeyKy?rokfkdPqbmmbp%60)12&yy>FAy442yy>@y0yyWy?rokfkdPqbmmbpy
OAob^aj^riOl`hyKy?rokfkdPqbmmbp%5.)1/&yy>FAy442yy>@y.yyWy?rokfkdPqbmmbpy
OOrfkplcQe^rofpp^kyKy?rokfkdPqbmmbp%32)1-&yy>FAy442yy>@y2yyWy?rokfkdPqbmmbpy
OQebMfii^olc>peyKy?rokfkdPqbmmbp%16)22&yy>FAy442yy>@y3yyWy?rokfkdPqbmmbpy
O?i^`hol`hPqolkdeliayKy?rokfkdPqbmmbp%1-)02&yy>FAy442yy>@y4yyWy?rokfkdPqbmmbpy
OAo^`l$a^oyKy?rokfkdPqbmmbp%/0)30&yy>FAy442yy>@y5yyWy?rokfkdPqbmmbpy
O>iq^olcPqlojpyKy?rokfkdPqbmmbp%.4)/6&yy>FAy442yy>@y6yyWy?rokfkdPqbmmbpy
O?i^`hol`hJlrkq^fkyKy?rokfkdPqbmmbp%/6)04&yy>FAy442yy>@y.-yyWy?rokfkdPqbmmbpy

OPb^ofkdDlodbyKyOrkqeolrde?i^`hol`hJlrkq^fkqlPb^ofkdDlodb%01+55)51+5&yyWyPb^ofkdDlodby
O?i^`h`e^o@^sbyKyPb^ofkdDlodb%//)5-&yy>FAy441yy>@y0yyWyPb^ofkdDlodby
OQebPb^lc@fkabopyKyPb^ofkdDlodb%15)4.&yy>FAy441yy>@y1yyWyPb^ofkdDlodby
OQ^kkbo@^jmyKyPb^ofkdDlodb%30)43&yy>FAy441yy>@y2yyWyPb^ofkdDlodby
ODofjbpfiqAfdPfqbyKyPb^ofkdDlodb%32)26&yy>FAy441yy>@y3yyWyPb^ofkdDlodby
OArpqcfobS^iibvyKyPb^ofkdDlodb%4/)/4&yy>FAy441yy>@y4yyWyPb^ofkdDlodby
OQeb@^riaolkyKyPb^ofkdDlodb%24)06&yy>FAy441yy>@y/yyWyPb^ofkdDlodby
OCfobt^q`eOfadbyKyPb^ofkdDlodb%00)05&yy>FAy441yy>@y.yyWyPb^ofkdDlodby
CH^od^qeyKy?^ai^kap+Orkfcvlralk$qe^sbcifdeqm^qe+y

OH^od^qeyKy?^ai^kap%1)13&yy>FAy432yy>@y4yyWy?^ai^kapy
O>ml`ovme^k$pObpqyKy?^ai^kap%.2)3-&yy>FAy432yy>@y3yyWy?^ai^kapy
O@^jm@^ddyKy?^ai^kap%.0)42&yy>FAy432yy>@y2yyWy?^ai^kapy
OJfo^dbCi^qpyKy?^ai^kap%0-)36&yyy>FAy432yy>@y1yyWy?^ai^kapy
OQebArpq_ltiyKy?^ai^kap%02)2/&yy>FAy432yy>@y5yyWy?^ai^kapy
OS^iibvlcC^kdpyKy?^ai^kap%15)20&yy>FAy432yy>@y6yyWy?^ai^kapy
O>djlka$pBkayKy?^ai^kap%2-)3/&yy>FAy432yy>@y0yyWy?^ai^kapy
O@^jm?lccyKy?^ai^kap%3/)4/&yy>FAy432yy>@y/yyWy?^ai^kapy
OIbqeiloO^sfkbyKy?^ai^kap%36)2/&yy>FAy432yy>@y.yyWy?^ai^kapy
OArpqtfkaDri`eyKy?^ai^kap%3/)1/&yy>FAy432yy>@y..yyWy?^ai^kapy
O@^jmHlpeyKy?^ai^kap%34)/.&yy>FAy432yy>@y.1yyWy?^ai^kapy
OE^jjboqlb$pAfdpfqbyKy?^ai^kap%2/)01&yy>FAy432yy>@y./yyWy?^ai^kapy
O>kdloCloqobppyKy?^ai^kap%10)0-&yy>FAy432yy>@y.-yyWy?^ai^kapy
OQebJ^hbo$pQboo^`byKy?^ai^kap%16).0&yy>FAy432yy>@y.0yyWy?^ai^kapy

OIl`eJla^kyKyOrkqlIl`eJla^k%14)5.&yyWyIl`eJla^ky
ODofwwibm^tOfadbyKyIl`eJla^k%11)4-&yy>FAy446yy>@y5yyWyIl`eJla^ky
OQebIl`eyKyIl`eJla^k%16)33&yy>FAy446yy>@y.yyWyIl`eJla^ky
OFolk_^ka$pBu`^s^qflkPfqbyKyIl`eJla^k%35)30&yy>FAy446yy>@y4yyWyIl`eJla^ky
OQebC^opqofaboIladbyKyIl`eJla^k%5-)3/&yy>FAy446yy>@y3yyWyIl`eJla^ky
OJl$dolpePqolkdeliayKyIl`eJla^k%4-)/1&yy>FAy446yy>@y0yyWyIl`eJla^ky
OPqlkbtolrdeqA^jyKyIl`eJla^k%14).0&yy>FAy446yy>@y/yyWyIl`eJla^ky
OPfisboPqob^jJfkbyKyIl`eJla^k%01).5&yy>FAy446yy>@y1yyWyIl`eJla^ky
OKloqeD^qbM^ppyKyIl`eJla^k%/-).4&yy>FAy446yy>@y2yyWyIl`eJla^ky
OQebip^j^oyKyIl`eJla^k%01)14&yy>FAy446yy>@y6yyWyIl`eJla^ky
OPqlkbpmifkqboS^iibvyKyIl`eJla^k%01)42&yy>FAy446yy>@y.-yyWyIl`eJla^ky
OS^iibvlcHfkdpyKyIl`eJla^k%//)4-&yy>FAy446yy>@y..yyWyIl`eJla^ky

OArkJloldeyKyOrkfkqlArkJlolde%53)2&yyWyArkJloldey
OPlrqeD^qbLrqmlpqyKyArkJlolde%52)2.&yy>FAy3/4yy>@y.2yyWyArkJloldey
OKloqeD^qbLrqmlpqyKyArkJlolde%50)1.&yy>FAy3/4yy>@y.-yyWyArkJloldey
OEbij$p?baI^hbyKyArkJlolde%43)21&yy>FAy3/4yy>@y5yyWyArkJloldey
ODli$?li^oNr^oovyKyArkJlolde%35)23&yy>FAy3/4yy>@y6yyWyArkJloldey
O>j_bopqfiiO^k`eyKyArkJlolde%30)2-&yy>FAy3/4yy>@y4yyWyArkJloldey
OQebQrkaofaEfiipyKyArkJlolde%23)24&yy>FAy3/4yy>@y3yyWyArkJloldey
OJfpqvMfkbObcrdbyKyArkJlolde%25)11&yy>FAy3/4yy>@y2yyWyArkJloldey
OD^qbplcFolkclodbyKyArkJlolde%2/)02&yy>FAy3/4yy>@y.5yyWyArkJloldey
OPefjjboOfadbyKyArkJlolde%1-)05&yy>FAy3/4yy>@y0yyWyArkJloldey
OF`bciltI^hbyKyArkJlolde%03)04&yy>FAy3/4yy>@y.3yyWyArkJloldey
O?obtk^iiSfii^dbyKyArkJlolde%0-)12&yy>FAy3/4yy>@y./yyWyArkJloldey
ODkljbobd^kyKyArkJlolde%/1)1-&yy>FAy3/4yy>@y.4yyWyArkJloldey
OColpqj^kbEliayKyArkJlolde%/2)2-&yy>FAy3/4yy>@y..yyWyArkJloldey
O@efii?obbwbS^iibvyKyArkJlolde%03)2/&yy>FAy3/4yy>@y/yyWyArkJloldey
OHe^o^klpyKyArkJlolde%13)2/&yy>FAy3/4yy>@y1yyWyArkJloldey
OQebDofwwibaAbkyKyArkJlolde%1/)25&yy>FAy3/4yy>@y.1yyWyArkJloldey
O@liaofadbM^ppyKyArkJlolde%01)36&yy>FAy3/4yy>@y.yyWyArkJloldey
O>ksfij^oyKyArkJlolde%/5)34&yy>FAy3/4yy>@y.0yyWyArkJloldey
EA^i^o^kyRy3615y

OPfisbojllk@fqvyKyQ^hbmloq^ifkA^i^o^ky
OPfisbojllk@fqvyKyBsboplkdTllap%23)15&yy>FAy526yy>@y.1yyWyBsboplkdTllapy
cPfisbojllk@fqvyKyPhvJfpqobppDil^jfkd%21)2-&yyWyBsboplkdTllapy
OPqfiitefpmboMlkayKyBsboplkdTllap%22)21&yy>FAy526yy>@y5yyWyBsboplkdTllapy
OQerolk$pIfsbovyKyBsboplkdTllap%3-)21&yy>FAy526yy>@y/0yyWyBsboplkdTllapy
OArphtfqeboDolrkapyKyBsboplkdTllap%35)14&yy>FAy526yy>@y6yyWyBsboplkdTllapy
O>wrob_obbwb@l^pqyKyBsboplkdTllap%4/)10&yy>FAy526yy>@y.2yyWyBsboplkdTllapy
OC^opqofaboObqob^qyKyBsboplkdTllap%3-)3/&yy>FAy526yy>@y4yyWyBsboplkdTllapy
OBiobka^oC^iipyKyBsboplkdTllap%31)40&yy>FAy526yy>@y.3yyWyBsboplkdTllapy
OI^hbBiobka^oyKyBsboplkdTllap%32)5.&yy>FAy526yy>@y.5yyWyBsboplkdTllapy
OQlo$T^qe^yKyBsboplkdTllap%4-)42&yy>FAy526yy>@y./yyWyBsboplkdTllapy
OWb_$T^qe^yKyBsboplkdTllap%3/)46&yy>FAy526yy>@y/2yyWyBsboplkdTllapy
OQebIfsfkdTllayKyBsboplkdTllap%25)4/&yy>FAy526yy>@y..yyWyBsboplkdTllapy
OB^pqP^k`qrjyKyBsboplkdTllap%20)4-&yy>FAy526yy>@y3yyWyBsboplkdTllapy
OC^fo_obbwbSfii^dbyKyBsboplkdTllap%10)4.&yy>FAy526yy>@y.-yyWyBsboplkdTllapy
OP^iqebofi$pE^sbkyKyBsboplkdTllap%04)40&yy>FAy526yy>@y/.yyWyBsboplkdTllapy
OKloqeP^k`qrjyKyBsboplkdTllap%11)20&yy>FAy526yy>@y2yyWyBsboplkdTllapy
OOrfkplcPfisbojllkyKyBsboplkdTllap%11)03&yy>FAy526yy>@y/yyWyBsboplkdTllapy
OPrkpqofaboFpibyKyBsboplkdTllap%03)/4&yy>FAy526yy>@y.yyWyBsboplkdTllapy
OTbpqP^k`qrjyKyBsboplkdTllap%02)26&yy>FAy526yy>@y0yyWyBsboplkdTllapy
OQo^knrfiPelobyKyBsboplkdTllap%/4)3-&yy>FAy526yy>@y/1yyWyBsboplkdTllapy
OPrkp^fi>k`elo^dbyKyBsboplkdTllap%0/)36&yy>FAy526yy>@y1yyWyBsboplkdTllapy
ODliabk_lrdeM^ppyKyBsboplkdTllap%00)43&yy>FAy526yy>@y.4yyWyBsboplkdTllapy
ODliabkPqo^kayKyBsboplkdTllap%/4)50&yy>FAy526yy>@y//yyWyBsboplkdTllapy
OQebP`lo`ebaDolsbyKyBsboplkdTllap%03)52&yy>FAy526yy>@y.0yyWyBsboplkdTllapy
ODliabkjfpqSfii^dbyKyDelpqi^kap%/3).3&yy>FAy525yy>@y0yyWyDelpqi^kapy
OOrkbpqlkbC^ifqe^pyKyBsboplkdTllap%10)52&yy>FAy526yy>@y.6yyWyBsboplkdTllapy

OBiobka^o@olppfkdyKyDelpqi^kap%15)..&yy>FAy525yy>@y.2yyWyDelpqi^kapy
OPrk`oltkSfii^dbyKyDelpqi^kap%3.)./&yy>FAy525yy>@y/yyWyDelpqi^kapy
OOrkbpqlkbPe^k$aloyKyBsboplkdTllap%22)51&yy>FAy526yy>@y/-yyWyBsboplkdTllapy
OA^tkpq^oPmfobyKyDelpqi^kap%46)/.&yy>FAy525yy>@y4yyWyDelpqi^kapy
OC^opqofaboBk`i^sbyKyDelpqi^kap%4/)0/&yy>FAy525yy>@y5yyWyDelpqi^kapy
OWb_$Klt^yKyDelpqi^kap%32)3-&yy>FAy525yy>@y..yyWyDelpqi^kapy
O>j^kfM^ppyKyDelpqi^kap%36)30&yy>FAy525yy>@y./yyWyDelpqi^kapy
OP^k`qrjlcqebPrkyKyDelpqi^kap%22)15&yy>FAy525yy>@y3yyWyDelpqi^kapy
OQo^knrfiifbkyKyDelpqi^kap%13)0/&yy>FAy525yy>@y.yyWyDelpqi^kapy
OP^k`qrjlcqebJllkyKyDelpqi^kap%00)02&yy>FAy525yy>@y2yyWyDelpqi^kapy
OTfkaorkkboSfii^dbyKyDelpqi^kap%.5)10&yy>FAy525yy>@y1yyWyDelpqi^kapy
OTfkaorkkboPmfobyKyDelpqi^kap%.0)24&yy>FAy525yy>@y.0yyWyDelpqi^kapy
O?ibbafkdWfddro^qyKyDelpqi^kap%01)14&yy>FAy525yy>@y.1yyWyDelpqi^kapy
OEltifkdWfddro^qyKyDelpqi^kap%1-)16&yy>FAy525yy>@y6yyWyDelpqi^kapy
OAb^qelijbyKyDelpqi^kap%02)4/&yy>FAy525yy>@y.-yyWyDelpqi^kapy
OQe^i^ppf^kM^ppyKyDelpqi^kap%14)46&yy>FAy525yy>@y.3yyWyDelpqi^kapy

OB^pqbokMi^drbi^kapyKyCliiltqebm^qeqeormloq^iqlB^pqbokMi^dri^kap%2/)64&yyWyDelpqi^kapy
OKloqem^ppQltboyKyB^pqbokMi^drbi^kap%2.)/-&yy>FAy44.yy>@y.5yyWyB^pqbokMi^drbi^kapy
ONrbi$IfqefbkIladbyKyB^pqbokMi^drbi^kap%15).1&yy>FAy44.yy>@y.6yyWyB^pqbokMi^drbi^kapy
OMi^drbtllayKyB^pqbokMi^drbi^kap%/5)/2&yy>FAy44.yy>@y/.yyWyB^pqbokMi^drbi^kapy
OPqo^qelijbyKyB^pqbokMi^drbi^kap%/4).-&yy>FAy44.yy>@y//yyWyB^pqbokMi^drbi^kapy
OQbooloa^ibyKyB^pqbokMi^drbi^kap%.0)/5&yy>FAy44.yy>@y/-yyWyB^pqbokMi^drbi^kapy
O?i^`htllaI^hbyKyB^pqbokMi^drbi^kap%13)10&yy>FAy44.yy>@y.2yyWyB^pqbokMi^drbi^kapy
OWri$J^pe^oyKyB^pqbokMi^drbi^kap%26).5&yy>FAy44.yy>@y.4yyWyB^pqbokMi^drbi^kapy
OKloqea^ibyKyB^pqbokMi^drbi^kap%31)/4&yy>FAy44.yy>@y.3yyWyB^pqbokMi^drbi^kapy
OB^pqt^iiQltboyKyB^pqbokMi^drbi^kap%3/)1/&yy>FAy44.yy>@y.1yyWyB^pqbokMi^drbi^kapy
OQebKluflrpDi^abyKyB^pqbokMi^drbi^kap%41)05&yy>FAy44.yy>@y.0yyWyB^pqbokMi^drbi^kapy
OMbpqfibkqP`^oyKyB^pqbokMi^drbi^kap%4.)2.&yy>FAy44.yy>@y4yyWyB^pqbokMi^drbi^kapy
OIfdeq$pElmb@e^mbiyKyB^pqbokMi^drbi^kap%42)2/&yy>FAy44.yy>@y..yyWyB^pqbokMi^drbi^kapy
OQvo$pE^kayKyB^pqbokMi^drbi^kap%43)42&yy>FAy44.yy>@y.-yyWyB^pqbokMi^drbi^kapy
OOrfkplcqebP`^oibqBk`i^sbyKyB^pqbokMi^drbi^kap%52)41&yy>FAy44.yy>@y/0yyWyB^pqbokMi^drbi^kapy
OI^hbJbobia^oyKyB^pqbokMi^drbi^kap%3.)40&yy>FAy44.yy>@y6yyWyB^pqbokMi^drbi^kapy
O@lofk$p@olppfkdyKyB^pqbokMi^drbi^kap%21)3/&yy>FAy44.yy>@y5yyWyB^pqbokMi^drbi^kapy
OQebFkcb`qfpP`^oyKyB^pqbokMi^drbi^kap%15)3/&yy>FAy44.yy>@y./yyWyB^pqbokMi^drbi^kapy
OA^ooltpefobyKyB^pqbokMi^drbi^kap%01)51&yy>FAy44.yy>@y3yyWyB^pqbokMi^drbi^kapy
O@oltkDr^oaQltboyKyB^pqbokMi^drbi^kap%02)35&yy>FAy44.yy>@y1yyWyB^pqbokMi^drbi^kapy
OQebCrkd^iS^ibyKyB^pqbokMi^drbi^kap%00)2.&yy>FAy44.yy>@y2yyWyB^pqbokMi^drbi^kapy
OQebJ^oofpPqb^ayKyB^pqbokMi^drbi^kap%/0)35&yy>FAy44.yy>@y/yyWyB^pqbokMi^drbi^kapy
OQebRkabo`olcqyKyB^pqbokMi^drbi^kap%/1)45&yy>FAy44.yy>@y0yyWyB^pqbokMi^drbi^kapy
OQelkaolofiOfsboyKyB^pqbokMi^drbi^kap%5)33&yy>FAy44.yy>@y.yyWyB^pqbokMi^drbi^kapy

OQebTbbmfkd@^sbyKyTbpqbokMi^drbi^kap%32)1-&yy>FAy44-yy>@y./yyWyTbpqbokMi^drbi^kapy
OD^eoolk$pTfqebofkdyKyTbpqbokMi^drbi^kap%3/)25&yy>FAy44-yy>@y..yyWyTbpqbokMi^drbi^kapy
OA^ooltjbobI^hbyKyTbpqbokMi^drbi^kap%30)30&yy>FAy44-yy>@y.yyWyTbpqbokMi^drbi^kapy
O@^boA^ooltyKyTbpqbokMi^drbi^kap%35)45&yy>FAy44-yy>@y/yyWyTbpqbokMi^drbi^kapy
OPlooltEfiiyKyTbpqbokMi^drbi^kap%2.)45&yy>FAy44-yy>@y0yyWyTbpqbokMi^drbi^kapy
OOrfkplc>kaloe^iyKyTbpqbokMi^drbi^kap%10)36&yy>FAy44-yy>@y1yyWyTbpqbokMi^drbi^kapy
OQebTofqefkdE^rkqyKyTbpqbokMi^drbi^kap%2/)33&yy>FAy44-yy>@y5yyWyTbpqbokMi^drbi^kapy
OA^iplk$pQb^opyKyTbpqbokMi^drbi^kap%13)20&yy>FAy44-yy>@y4yyWyTbpqbokMi^drbi^kapy
OEb^oqedibkyKyTbpqbokMi^drbi^kap%11).3&yy>FAy44-yy>@y.-yyWyTbpqbokMi^drbi^kapy
OKloqeofadbIrj_bo@^jmyKyTbpqbokMi^drbi^kap%13)03&yy>FAy44-yy>@y6yyWyTbpqbokMi^drbi^kapy
OCbipqlkbCfbiayKyTbpqbokMi^drbi^kap%03)23&yy>FAy44-yy>@y3yyWyTbpqbokMi^drbi^kapy
OQeb?rit^ohyKyTbpqbokMi^drbi^kap%/4)24&yy>FAy44-yy>@y2yyWyTbpqbokMi^drbi^kapy

O?^ikfoC^ojpqb^ayKyQfofpc^iDi^abp%42)3.&yy>FAy435yy>@y.-yyWyQfofpc^iDi^abpy
O@orp^aboLrqmlpqyKyQfofpc^iDi^abp%45)22&yy>FAy435yy>@y..yyWyQfofpc^iDi^abpy
OSbkljtb_S^ibyKyQfofpc^iDi^abp%51)14&yy>FAy435yy>@y.1yyWyQfofpc^iDi^abpy
OTefpmbofkdD^oabkpyKyQfofpc^iDi^abp%5.)0/&yy>FAy435yy>@y.0yyWyQfofpc^iDi^abpy
OP`^oibqT^q`eMlpqyKyQfofpc^iDi^abp%46)/6&yy>FAy435yy>@y./yyWyQfofpc^iDi^abpy
O?ofdeqt^qboI^hbyKyQfofpc^iDi^abp%4-)03&yy>FAy435yy>@y6yyWyQfofpc^iDi^abpy
OD^oobk$pE^rkqyKyQfofpc^iDi^abp%26)02&yy>FAy435yy>@y5yyWyQfofpc^iDi^abpy
O?ofiiyKyQfofpc^iDi^abp%26)2.&yy>FAy435yy>@y4yyWyQfofpc^iDi^abpy
O@liaEb^oqeJ^kloyKyQfofpc^iDi^abp%20)24&yy>FAy435yy>@y3yyWyQfofpc^iDi^abpy
OPqfiit^qboMlkayKyQfofpc^iDi^abp%16)2/&yy>FAy435yy>@y1yyWyQfofpc^iDi^abpy
O>d^j^kaJfiipyKyQfofpc^iDi^abp%15)06&yy>FAy435yy>@y0yyWyQfofpc^iDi^abpy
OPliifabkC^ojpqb^ayKyQfofpc^iDi^abp%03)2-&yy>FAy435yy>@y/yyWyQfofpc^iDi^abpy
OAb^qehkbiiyKyQfofpc^iDi^abp%02)26&yy>FAy435yy>@y.yyWyQfofpc^iDi^abpy
OKfdeqj^obS^ibyKyQfofpc^iDi^abp%15)31&yy>FAy435yy>@y2yyWyQfofpc^iDi^abpy
ORkabo`fqvyKyRkabo`fqv%.1)02&yy>FAy435yy>@y.3yyWyRkabo`fqvy

OPfisbomfkbClobpqyKyOrkfkqlPfisbomfkbClobpq%33)3&yyWyPfisbomfkbClobpqy
OJ^iabk$pLo`e^oayKyPfisbomfkbClobpq%24).-&yy>FAy436yy>@y.yyWyPfisbomfkbClobpqy
OQebPefkfkdPqo^kayKyPfisbomfkbClobpq%26).3&yy>FAy436yy>@y/yyWyPfisbomfkbClobpqy
OCbkofpFpibyKyPfisbomfkbClobpq%33)/4&yy>FAy436yy>@y3yyWyPfisbomfkbClobpqy
OQebAb^aCfbiayKyPfisbomfkbClobpq%12)/-&yy>FAy436yy>@y0yyWyPfisbomfkbClobpqy
OQebPhfqqbofkdA^ohyKyPfisbomfkbClobpq%04).3&yy>FAy436yy>@y1yyWyPfisbomfkbClobpqy
OKloqeQfab$pEliiltyKyPfisbomfkbClobpq%06)/5&yy>FAy436yy>@y2yyWyPfisbomfkbClobpqy
OQebAb`obmfqCboovyKyPfisbomfkbClobpq%24)01&yy>FAy436yy>@y4yyWyPfisbomfkbClobpqy
OQebPbmri`eboyKyPfisbomfkbClobpq%10)1.&yy>FAy436yy>@y5yyWyPfisbomfkbClobpqy
OLipbk$pC^oqefkdyKyPfisbomfkbClobpq%14)20&yy>FAy436yy>@y.-yyWyPfisbomfkbClobpqy
OAbbmBibjJfkbyKyPfisbomfkbClobpq%22)14&yy>FAy436yy>@y6yyWyPfisbomfkbClobpqy
O>j_bojfiiyKyPfisbomfkbClobpq%3.)31&yy>FAy436yy>@y..yyWyPfisbomfkbClobpqy
OPe^altc^kdHbbmyKyPfisbomfkbClobpq%11)35&yy>FAy436yy>@y./yyWyPfisbomfkbClobpqy
OMvobtllaSfii^dbyKyPfisbomfkbClobpq%12)40&yy>FAy436yy>@y.0yyWyPfisbomfkbClobpqy
OQebDobvj^kbT^iiyKyPfisbomfkbClobpq%13)50&yy>FAy436yy>@y.1yyWyPfisbomfkbClobpqy
O?bobk$pMbofiyKyPfisbomfkbClobpq%3.)41&yy>FAy436yy>@y.2yyWyPfisbomfkbClobpqy

OPlrqemlfkqQltboyKyEfiip_o^aCllqefiip%/-)16&yy>FAy44/yy>@y..yyWyEfiip_o^aCllqefiipy
O>wrobilabJfkbyKyEfiip_o^aCllqefiip%/3)3-&yy>FAy44/yy>@y.-yyWyEfiip_o^aCllqefiipy
OTbpqbokPqo^kayKyEfiip_o^aCllqefiip%/1)32&yy>FAy44/yy>@y6yyWyEfiip_o^aCllqefiipy
OMrod^qflkFpibyKyEfiip_o^aCllqefiip%.3)46&yy>FAy44/yy>@y./yyWyEfiip_o^aCllqefiipy
OPlrqepelobyKyEfiip_o^aCllqefiip%16)23&yy>FAy44/yy>@y4yyWyEfiip_o^aCllqefiipy
OEfiip_o^aCfbiapyKyEfiip_o^aCllqefiip%00)1/&yy>FAy44/yy>@y5yyWyEfiip_o^aCllqefiipy
OA^ooltEfiiyKyEfiip_o^aCllqefiip%16)00&yy>FAy44/yy>@y.yyWyEfiip_o^aCllqefiipy
O@loo^ek$pA^ddboyKy>iqbo^`Jlrkq^fkp%15)5/&yy>FAy43-yy>@y/yyWy>iqbo^`Jlrkq^fkpy
ODoltibpp@^sbyKy>iqbo^`Jlrkq^fkp%04)36&yy>FAy43-yy>@y5yyWy>iqbo^`Jlrkq^fkpy
OQebEb^ai^kayKy>iqbo^`Jlrkq^fkp%05)54&yy>FAy43-yy>@y.1yyWy>iqbo^`Jlrkq^fkpy
OD^sfk$pK^wbyKy>iqbo^`Jlrkq^fkp%0.)50&yy>FAy43-yy>@y4yyWy>iqbo^`Jlrkq^fkpy
OIloa^jbobFkqbokjbkq@^jmyKy>iqbo^`Jlrkq^fkp%/-)52&yy>FAy43-yy>@y6yyWy>iqbo^`Jlrkq^fkpy
OA^i^o^k@o^qboyKy>iqbo^`Jlrkq^fkp%.2)32&yy>FAy43-yy>@y1yyWy>iqbo^`Jlrkq^fkpy
OJfpqvPelobyKy>iqbo^`Jlrkq^fkp%/4)10&yy>FAy43-yy>@y.-yyWy>iqbo^`Jlrkq^fkpy
OA^kaoba$pCliayKy>iqbo^`Jlrkq^fkp%1-).5&yy>FAy43-yy>@y2yyWy>iqbo^`Jlrkq^fkpy
OQebRmi^kapyKy>iqbo^`Jlrkq^fkp%25)0.&yy>FAy43-yy>@y.2yyWy>iqbo^`Jlrkq^fkpy
OPqo^ek_o^ayKy>iqbo^`Jlrkq^fkp%3/)10&yy>FAy43-yy>@y.0yyWy>iqbo^`Jlrkq^fkpy
O@orpeofadbEliayKy>iqbo^`Jlrkq^fkp%2-)12&yy>FAy43-yy>@y0yyWy>iqbo^`Jlrkq^fkpy
OOrfkplc>iqbo^`yKy>iqbo^`Jlrkq^fkp%03)21&yy>FAy43-yy>@y..yyWy>iqbo^`Jlrkq^fkpy
OD^iiltp$@lokboyKy>iqbo^`Jlrkq^fkp%16)24&yy>FAy43-yy>@y3yyWy>iqbo^`Jlrkq^fkpy
OPlcbo^$pK^wbyKy>iqbo^`Jlrkq^fkp%25)34&yy>FAy43-yy>@y./yyWy>iqbo^`Jlrkq^fkpy
O@efiitfkaMlfkqyKy>iqbo^`Jlrkq^fkp%42)33&yy>FAy43-yy>@y.yyWy>iqbo^`Jlrkq^fkpy
OQ^oobkJfiiyKyEfiip_o^aCllqefiip%3.)/0&yy>FAy44/yy>@y/yyWyEfiip_o^aCllqefiipy
OKbqe^kaboPqb^ayKyEfiip_o^aCllqefiip%31)3-&yy>FAy44/yy>@y2yyWyEfiip_o^aCllqefiipy
OB^pqbokPqo^kayKyEfiip_o^aCllqefiip%3-)4/&yy>FAy44/yy>@y3yyWyEfiip_o^aCllqefiipy
OArkD^olhyKyEfiip_o^aCllqefiip%36)43&yy>FAy44/yy>@y1yyWyEfiip_o^aCllqefiipy
OArokeliabHbbmyKyEfiip_o^aCllqefiip%43)1.&yy>FAy44/yy>@y0yyWyEfiip_o^aCllqefiipy

OQebEfkqboi^kapyKyBkqbo^k`bfp^q%50)0/&yyWyEfiip_o^aCllqefiipy
O>bofbMb^hyKy%.0)15&yy>FAy440yy>@y.yyWyQebEfkqboi^kapy
OMi^drbjfpqO^sfkbyKy%/0)1-&yy>FAy440yy>@y/yyWyQebEfkqboi^kapy
ONrbi$A^kfiIladbyKy%0.)14&yy>FAy440yy>@y1yyWyQebEfkqboi^kapy
OEfof$t^qe^yKy%0.)25&yy>FAy440yy>@y0yyWyQebEfkqboi^kapy
OPe^ao^$>iloyKy%01)4-&yy>FAy440yy>@y2yyWyQebEfkqboi^kapy
OS^ilotfkaI^hbyKy%1-)26&yy>FAy440yy>@y3yyWyQebEfkqboi^kapy
OQeb>iq^olcWriyKy%15)33&yy>FAy440yy>@y6yyWyQebEfkqboi^kapy
OQeb@obbmfkdOrfkyKy%2.)2-&yy>FAy440yy>@y5yyWyQebEfkqboi^kapy
O>dli$t^qe^yKy%14)1-&yy>FAy440yy>@y4yyWyQebEfkqboi^kapy
OPhrihOl`hyKy%24)1-&yy>FAy440yy>@y..yyWyQebEfkqboi^kapy
OPbo^a^kbyKy%30)/1&yy>FAy440yy>@y.-yyWyQebEfkqboi^kapy
OPe^li$t^qe^yKy%4/)20&yy>FAy440yy>@y./yyWyQebEfkqboi^kapy
OGfkqe^$>iloyKy%3/)4/&yy>FAy440yy>@y.0yyWyQebEfkqboi^kapy
OQebLsboillh@ifccpyKy%4/)33&yy>FAy440yy>@y.1yyWyQebEfkqboi^kapy
OObs^kqrphSfii^dbyKy%45)46&yyWyQebEfkqboi^kapy

CE^jjboc^iiyKyFk>o^qefEfdei^kapy
OE^jjboc^iiyKy>o^qefEfdei^kap%41)05&yy>FAy43.yy>@y.3yyWy>o^qefEfdei^kapy
O@fo`iblcB^pq?fkafkdyKy>o^qefEfdei^kap%33)/6&yy>FAy43.yy>@y.2yyWy>o^qefEfdei^kapy
OA^_vofb$pC^ojpqb^ayKy>o^qefEfdei^kap%22)06&yy>FAy43.yy>@y.1yyWy>o^qefEfdei^kapy
ODl$PebhC^ojyKy>o^qefEfdei^kap%3.)25&yy>FAy43.yy>@y.0yyWy>o^qefEfdei^kapy
OTfqebo_^ohSfii^dbyKy>o^qefEfdei^kap%32)35&yy>FAy43.yy>@y./yyWy>o^qefEfdei^kapy
O?lriabocfpqE^iiyKy>o^qefEfdei^kap%20)40&yy>FAy43.yy>@y6yyWy>o^qefEfdei^kapy
O@fo`iblcLrqbo?fkafkdyKy>o^qefEfdei^kap%2/)2-&yy>FAy43.yy>@y..yyWy>o^qefEfdei^kapy
OObcrdbMlfkqbyKy>o^qefEfdei^kap%12)14&yy>FAy43.yy>@y.-yyWy>o^qefEfdei^kapy
O?lriabo$dloyKy>o^qefEfdei^kap%01)10&yy>FAy43.yy>@y0yyWy>o^qefEfdei^kapy
OKloqecliaJ^kloyKy>o^qefEfdei^kap%0/)/4&yy>FAy43.yy>@y/yyWy>o^qefEfdei^kapy
O@fo`iblcTbpq?fkafkdyKy>o^qefEfdei^kap%/2)0.&yy>FAy43.yy>@y.yyWy>o^qefEfdei^kapy
OQelo^afk$pT^iiyKy>o^qefEfdei^kap%.6)0/&yy>FAy43.yy>@y1yyWy>o^qefEfdei^kapy
OPqoljd^oabHbbmyKy>o^qefEfdei^kap%/2)24&yy>FAy43.yy>@y2yyWy>o^qefEfdei^kapy
O@fo`iblcFkkbo?fkafkdyKy>o^qefEfdei^kap%02)25&yy>FAy43.yy>@y4yyWy>o^qefEfdei^kapy
OC^iafo$p@lsbyKyBkqbo^k`blc`^sb^q%/.)4-&+C^iafo$p@lsb%/1)5.&yy>FAy43.yy>@y3yyWy>o^qefEfdei^kapy
OQe^kaliPm^kyKyOrk_^`hqeor`^sbqlDbqqlQe^kaliPm^k%12)56&yy>FAy43.yy>@y5yyWy>o^qefEfdei^kapy

OArkJlaoyKyTbqi^kap%16).4&yy>FAy51.yy>@y5yyWyTbqi^kapy
OFolk_b^oa$pQlj_yKyTbqi^kap%11)/4&yy>FAy51.yy>@y4yyWyTbqi^kapy
OQebDobbk?biqyKyTbqi^kap%22)01&yy>FAy51.yy>@y..yyWyTbqi^kapy
OAfobclodbEfiiyKyTbqi^kap%3-)/4&yy>FAy51.yy>@y.0yyWyTbqi^kapy
OO^mqloOfadbyKyTbqi^kap%35)04&yy>FAy51.yy>@y.1yyWyTbqi^kapy
ODofj?^qliyKyTbqi^kap%45)41&yy>FAy51.yy>@y.2yyWyTbqi^kapy
OArk>id^wyKyTbqi^kap%2/)4/&yyy>FAy51.yy>@y.-yyWyTbqi^kapy
OJlppefabCbkyKyTbqi^kap%25)20&yy>FAy51.yy>@y./yyWyTbqi^kapy
O>kdboc^kdBk`^jmjbkqyKyTbqi^kap%14)15&yy>FAy51.yy>@y6yyWyTbqi^kapy
OTebid^o$pBu`^s^qflkPfqbyKyTbqi^kap%02)14&yy>FAy51.yy>@y1yyWyTbqi^kapy
OPrkaltkJ^opeyKyTbqi^kap%00)0.&yy>FAy51.yy>@y2yyWyTbqi^kapy
OP^iqpmo^vDibkyKyTbqi^kap%01)/-&yy>FAy51.yy>@y3yyWyTbqi^kapy
O?irbdfiiJ^opeyKyTbqi^kap%.6)04&yy>FAy51.yy>@y0yyWyTbqi^kapy
O?i^`h@e^kkbiJ^opeyKyTbqi^kap%/.)16&yy>FAy51.yy>@y/yyWyTbqi^kapy
OJbkbqefiE^o_loyKyTbqi^kap%.0)22&yy>FAy51.yy>@y.yyWyTbqi^kapy
EA^i^o^kyRy3615y

OPe^qqo^qe@fqvyKyQ^hbMloq^ifkA^i^o^ky
OFpiblcNrbi$A^k^pyKyQ^hbMloq^ifkPe^qqo^qeyy>FAy535yy>@y.y
CPfisbojllk@fqvyKyLero^%15)/2&yyWyFpiblcNrbi$A^k^py
O?i^pqbaI^kapyKyQ^hbMloq^ifkPfisbojllk@fqv%25)/-&yyWyPfisbojllk@fqvy

OQebA^ohMloq^iyKy?i^pqbaI^kap%26)23&yy>FAy433yy>@y2yyWy?i^pqbaI^kapy
OQebQ^fkqbaP`^oyKy?i^pqbaI^kap%1/)26&yy>FAy433yy>@y5yyWy?i^pqbaI^kapy
OAob^aj^riMlpqyKy?i^pqbaI^kap%15)10&yy>FAy433yy>@y4yyWy?i^pqbaI^kapy
O>iq^olcPqlojpyKy?i^pqbaI^kap%06)0/&yy>FAy433yy>@y3yyWy?i^pqbaI^kapy
OOfpblcqebAbcfiboyKy?i^pqbaI^kap%15)/4&yy>FAy433yy>@y6yyWy?i^pqbaI^kapy
OPbombkq$p@lfiyKy?i^pqbaI^kap%30)0/&yy>FAy433yy>@y1yyWy?i^pqbaI^kapy
OKbqebod^oabHbbmyKy?i^pqbaI^kap%30).6&yy>FAy433yy>@y0yyWy?i^pqbaI^kapy
OD^oofplk>ojlovyKy?i^pqbaI^kap%22).0&yy>FAy433yy>@y/yyWy?i^pqbaI^kapy
OAob^aj^riEliayKy?i^pqbaI^kap%10).0&yy>FAy433yy>@y.yyWy?i^pqbaI^kapy

OPt^jmlcPlooltp
OPqlk^oayKyPt^jmlcPlooltp%13)21&yy>FAy45/yy>@y3yyWyPt^jmlcPlooltpy
OMllilcQb^opyKyPt^jmlcPlooltp%32)21&yy>FAy45/yy>@y4yyWyPt^jmlcPlooltpy
OPq^d^i_ldyKyPt^jmlcPlooltp%40)5/&yy>FAy45/yy>@y5yyWyPt^jmlcPlooltpy
OPlooltjrohyKyPt^jmlcPlooltp%51)14&yy>FAy45/yy>@y6yyWyPt^jmlcPlooltpy
OJfpqvObbaPqo^kayKy%Pt^jmlcPlooltp61)15&yy>FAy45/yy>@y/yyWyPt^jmlcPlooltpy
OC^iiltP^k`qr^ovyKyPt^jmlcPlooltp%3/)/0&yy>FAy45/yy>@y.-yyWyPt^jmlcPlooltpy
OQebPefcqfkdJfobyKyPt^jmlcPlooltp%03)1/&yy>FAy45/yy>@y2yyWyPt^jmlcPlooltpy
OQebE^o_lo^dbyKyPt^jmlcPlooltp%/2)0.&yy>FAy45/yy>@y0yyWyPt^jmlcPlooltpy
OJfpqvS^iibvyKyPt^jmlcPlooltp%.1)03&yy>FAy45/yy>@y/yyWyPt^jmlcPlooltpy
OPmifkqbopmb^oGrk`qflkyKyPt^jmlcPlooltp%.4)2.&yy>FAy45/yy>@y1yyWyPt^jmlcPlooltpy
OFqe^ofrp$p@^sbyKyPt^jmlcPlooltp%.0)35&yy>FAy45/yy>@y.yyWyPt^jmlcPlooltpy

OAb^atfkaM^pp
OQebSf`byKyAb^atfkaM^pp%25)31&yy>FAy444yy>@y/yyWyAb^atfkaM^ppy
OH^o^we^kyKyAb^atfkaM^pp%12)40&yy>FAy444yy>@y0yyWyAb^atfkaM^ppy

KDrfab@ljmibqb
]]
end)
