DugisGuideViewer:RegisterGuide("Exploration Outland Achievement (70+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-(tfqe^civfkdjlrkq+J^hbprobA^i^o^kfpvlrEb^oqeil`^qflk+Fcvlralk$qdbqqeb^ob^prk`lsboba^qqebil`^qflkmolsfaba)jlsb^olrka^_fqfkqe^qil`^qflk)fq$pqebob+y
K>iplyKyj^hbprobvlrpq^vfkqebil`^qflkilkdbklrdeqlafp`lsbofq+y
eA^i^o^kyKyPbqvlroeb^oqeqlA^i^o^ky
O@fqvlcFolkclodbyKyQo^sbiqlFolkclodb%/5).-&yyWyFolkclodby
O?i^pqbaI^kapyKyQ^hbqebmloq^iql?i^pqbaI^ka%/5).-&yyWyFolkclodby
OEbiicfobMbkfkpri^yKyOrkqeolrdeA^ohMloq^i%25)25&yyWy?i^pqbaI^kapy

OQebPq^folcAbpqfkvyKyEbiicfobMbkfkpri^%53)2-&yy>FAy53/yy>@y.yyWyEbiicfobMbkfkpri^y
OQebIbdflkColkqyKyEbiicfobMbkfkpri^%4/)2/&yy>FAy53/yy>@y.-yyWyEbiicfobMbkfkpri^y
OSlfaOfadbyKyEbiicfobMbkfkpri^%44)4-&yy>FAy53/yy>@y.3yyWyEbiicfobMbkfkpri^y
OWbqe$DloyKyEbiicfobMbkfkpri^%34)4/&yy>FAy53/yy>@y.0yyWyEbiicfobMbkfkpri^y
OElkloEliayKyEbiicfobMbkfkpri^%22)30&yy>FAy53/yy>@y2yyWyEbiicfobMbkfkpri^y
OBumbafqflk>ojlovyKyEbiicfobMbkfkpri^%21)5.&yy>FAy53/yy>@y/yyWyEbiicfobMbkfkpri^y
OQebT^omCfbiapyKyEbiicfobMbkfkpri^%12)50&yy>FAy53/yy>@y.4yyWyEbiicfobMbkfkpri^y
OO^wloqelokPebicyKyQbolhh^oClobpq%23).6&yy>FAy534yy>@y..yyWyQbolhh^oClobpqy
OAbklcE^^i$bpeyKyEbiicfobMbkfkpri^%/3)4/&yy>FAy53/yy>@y.1yyWyEbiicfobMbkfkpri^y
OC^i`lkT^q`eyKyEbiicfobMbkfkpri^%/4)3.&yy>FAy53/yy>@y0yyWyEbiicfobMbkfkpri^y
OOrfkplcPe^$k^^oyKyEbiicfobMbkfkpri^%.2)3-&yy>FAy53/yy>@y5yyWyEbiicfobMbkfkpri^y
OC^iibkPhvOfadbyKyEbiicfobMbkfkpri^%.1)12&yy>FAy53/yy>@y.2yyWyEbiicfobMbkfkpri^y
OQbjmiblcQbie^j^qyKyEbiicfobMbkfkpri^%/0)1-&yy>FAy53/yy>@y6yyWyEbiicfobMbkfkpri^y
OJ^d$e^oMlpqyKyEbiicfobMbkfkpri^%0/)/5&yy>FAy53/yy>@y3yyWyEbiicfobMbkfkpri^y
OMlliplc>ddlk^oyKyEbiicfobMbkfkpri^%06)1-&yy>FAy53/yy>@y4yyWyEbiicfobMbkfkpri^y
OEbiicfob@fq^abiyKyEbiicfobMbkfkpri^%15)2/&yy>FAy53/yy>@y1yyWyEbiicfobMbkfkpri^y
OQeo^iij^oyKyEbiicfobMbkfkpri^%21)06&yy>FAy53/yy>@y..yyWyEbiicfobMbkfkpri^y
OClodb@^jm7J^dbaalkyKyEbiicfobMbkfkpri^%32)0.&yy>FAy53/yy>@y.5yyWyEbiicfobMbkfkpri^y
OQeolkblcHfi$g^babkyKyEbiicfobMbkfkpri^%3.).5&yy>FAy53/yy>@y./yyWyEbiicfobMbkfkpri^y

OTfw^oaOltyKyHfofk$S^oSfii^db)Kbqebopqloj%23)52&>kvm^oqlcTfw^oaOltpelriap^qfpcvqefpobnrfobjbkq+yy>FAy510yy>@y./yyWyKbqebopqlojy
OJ^k^clodb@lorryKyKbqebopqloj%15)51&yy>FAy510yy>@y0yyWyKbqebopqlojy
O>ohilkOrfkpyKyKbqebopqloj%1-)42&yy>FAy510yy>@y.-yyWyKbqebopqlojy
OPrkcrovEliayKyKbqebopqloj%23)45&yy>FAy510yy>@y.2yyWyKbqebopqlojy
OJ^k^clodbArolyKyKbqebopqloj%26)34&yy>FAy510yy>@y1yyWyKbqebopqlojy
OQbjmbpqHbbmyKyKbqebopqloj%4.)32&yy>FAy510yy>@y5yyWyKbqebopqlojy
O@bibpqf^iOfadbyKyKbqebopqloj%4/)1-&yy>FAy510yy>@y..yyWyKbqebopqlojy
OJ^k^clodbRiqofpyKyKbqebopqloj%3/)06&yy>FAy510yy>@y3yyWyKbqebopqlojy
OBqebobrjPq^dfkdDolrkapyKyKbqebopqloj%22)1/&yy>FAy510yy>@y.6yyWyKbqebopqlojy
OB`l*AljbJfaob^ijyKyKbqebopqloj%12)21&yy>FAy510yy>@y//yyWyKbqebopqlojy
OQebPqlojpmfobyKyKbqebopqloj%11)03&yy>FAy510yy>@y.3yyWyKbqebopqlojy
OOrfkplcC^o^eilkyKyKbqebopqloj%21)/2&yy>FAy510yy>@y4yyWyKbqebopqlojy
OKbqebopqlkbyKyKbqebopqloj%16).5&yy>FAy510yy>@y.0yyWyKbqebopqlojy
OB`l*AljbC^ocfbiayKyKbqebopqloj%12).0&yy>FAy510yy>@y.5yyWyKbqebopqlojy
OClodb?^pb7L_ifsflkyKyKbqebopqloj%04)/2&yy>FAy510yy>@y/.yyWyKbqebopqlojy
OPl`obqe^o$pPb^qyKyKbqebopqloj%/6).2&yy>FAy510yy>@y/-yyWyKbqebopqlojy
OJ^k^clodb>o^yKyKbqebopqloj%/3)05&yy>FAy510yy>@y2yyWyKbqebopqlojy
OOrfkplcBkh^^qyKyKbqebopqloj%0/)23&yy>FAy510yy>@y.1yyWyKbqebopqlojy
O>ob^2/yKyKbqebopqloj%00)32&yy>FAy510yy>@y.yyWyKbqebopqlojy
OQebEb^myKyKbqebopqloj%0.)43&yy>FAy510yy>@y6yyWyKbqebopqlojy
OJ^k^clodb?$k^^oyKyKbqebopqloj%//)4-&yy>FAy510yy>@y/yyWyKbqebopqlojy
ODvol*Mi^kh?ofadbyKyKbqebopqloj%//)23&yy>FAy510yy>@y.4yyWyKbqebopqlojy

O?olhbkTfiapyKy?i^ab$pBadbJlrkq^fkp%44)/1&yy>FAy532yy>@y3yyWy?i^ab$pBadbJlrkq^fkpy
OPh^iayKy?i^ab$pBadbJlrkq^fkp%4/)/0&yy>FAy532yy>@y.6yyWy?i^ab$pBadbJlrkq^fkpy
ODorri$pI^foyKy?i^ab$pBadbJlrkq^fkp%32)/1&yy>FAy532yy>@y.0yyWy?i^ab$pBadbJlrkq^fkpy
O@ovpq^iPmfkbyKy?i^ab$pBadbJlrkq^fkp%31).1&yy>FAy532yy>@y/.yyWy?i^ab$pBadbJlrkq^fkpy
O?^pe$foI^kafkdyKy?i^ab$pBadbJlrkq^fkp%2/)./&yy>FAy532yy>@y.yyWy?i^ab$pBadbJlrkq^fkpy
O?illaj^ri@^jmyKy?i^ab$pBadbJlrkq^fkp%22)/4&yy>FAy532yy>@y1yyWy?i^ab$pBadbJlrkq^fkpy
OSbfiOrr^kyKy?i^ab$pBadbJlrkq^fkp%31)0.&yy>FAy532yy>@y/1yyWy?i^ab$pBadbJlrkq^fkpy
OOrr^kTb^iayKy?i^ab$pBadbJlrkq^fkp%3/)01&yy>FAy532yy>@y.5yyWy?i^ab$pBadbJlrkq^fkpy
O?i^abaDri`eyKy?i^ab$pBadbJlrkq^fkp%4-)1/&yy>FAy532yy>@y/yyWy?i^ab$pBadbJlrkq^fkpy
OClodb@^jm7>kdboyKy?i^ab$pBadbJlrkq^fkp%40)1.&yy>FAy532yy>@y6yyWy?i^ab$pBadbJlrkq^fkpy
OO^wloOfadbyKy?i^ab$pBadbJlrkq^fkp%32)20&yy>FAy532yy>@y.4yyWy?i^ab$pBadbJlrkq^fkpy
OSbhe^^oPq^kayKy?i^ab$pBadbJlrkq^fkp%4.)3.&yy>FAy532yy>@y/2yyWy?i^ab$pBadbJlrkq^fkpy
OJlh$K^qe^iSfii^dbyKy?i^ab$pBadbJlrkq^fkp%41)3.&yy>FAy532yy>@y.2yyWy?i^ab$pBadbJlrkq^fkpy
OAb^qe$pAlloyKy?i^ab$pBadbJlrkq^fkp%31)34&yy>FAy532yy>@y5yyWy?i^ab$pBadbJlrkq^fkpy
OG^ddbaOfadbyKy?i^ab$pBadbJlrkq^fkp%16)4-&yy>FAy532yy>@y.1yyWy?i^ab$pBadbJlrkq^fkpy
OQerkaboiloaPqolkdeliayKy?i^ab$pBadbJlrkq^fkp%2/)23&yy>FAy532yy>@y//yyWy?i^ab$pBadbJlrkq^fkpy
O@fo`iblc?illayKy?i^ab$pBadbJlrkq^fkp%20)10&yy>FAy532yy>@y4yyWy?i^ab$pBadbJlrkq^fkpy
O?i^abpmfobEliayKy?i^ab$pBadbJlrkq^fkp%1-)20&yy>FAy532yy>@y0yyWy?i^ab$pBadbJlrkq^fkpy
OClodb@^jm7To^qeyKy?i^ab$pBadbJlrkq^fkp%03)06&yy>FAy532yy>@y..yyWy?i^ab$pBadbJlrkq^fkpy
ODofpek^qeyKy?i^ab$pBadbJlrkq^fkp%06)/-&yy>FAy532yy>@y./yyWy?i^ab$pBadbJlrkq^fkpy
OO^sbk$pTllayKy?i^ab$pBadbJlrkq^fkp%0.)/5&yy>FAy532yy>@y.3yyWy?i^ab$pBadbJlrkq^fkpy
OSloqbuMfkk^`ibyKy?i^ab$pBadbJlrkq^fkp%/5)15&yy>FAy532yy>@y/3yyWy?i^ab$pBadbJlrkq^fkpy
OClodb@^jm7QbooloyKy?i^ab$pBadbJlrkq^fkp%/5)5.&yy>FAy532yy>@y.-yyWy?i^ab$pBadbJlrkq^fkpy
OSbfiI^peeyKy?i^ab$pBadbJlrkq^fkp%02)43&yy>FAy532yy>@y/0yyWy?i^ab$pBadbJlrkq^fkpy
OPvis^k^^oyKy?i^ab$pBadbJlrkq^fkp%04)31&yy>FAy532yy>@y/-yyWy?i^ab$pBadbJlrkq^fkpy
O?illaj^riLrqmlpqyKy?i^ab$pBadbJlrkq^fkp%13)44&yy>FAy532yy>@y2yyWy?i^ab$pBadbJlrkq^fkpy

OLob_loE^o_lo^dbyKyW^kd^oj^ope%1/)0-&yy>FAy530yy>@y.2yyWyW^kd^oj^opey
O?illap`^ibDolrkapyKyW^kd^oj^ope%3.)1.&yy>FAy530yy>@y.1yyWyW^kd^oj^opey
OQbiobaloyKyW^kd^oj^ope%35)15&yy>FAy530yy>@y4yyWyW^kd^oj^opey
OQebAb^aJfobyKyW^kd^oj^ope%5.)05&yy>FAy530yy>@y5yyWyW^kd^oj^opey
O@bk^oflkObcrdbyKyW^kd^oj^ope%46)31&yy>FAy530yy>@y.yyWyW^kd^oj^opey
ORj_o^cbkSfii^dbyKyW^kd^oj^ope%50)5/&yy>FAy530yy>@y..yyWyW^kd^oj^opey
OA^oh`obpqPelobyKyW^kd^oj^ope%4-)5-&yy>FAy530yy>@y.5yyWyW^kd^oj^opey
OQebI^dllkyKyW^kd^oj^ope%25)3/&yy>FAy530yy>@y6yyWyW^kd^oj^opey
OQtfkPmfobOrfkpyKyW^kd^oj^ope%14)20&yy>FAy530yy>@y.-yyWyW^kd^oj^opey
OCbo^icbkSfii^dbyKyW^kd^oj^ope%13)30&yy>FAy530yy>@y0yyWyW^kd^oj^opey
ONr^ddOfadbyKyW^kd^oj^ope%/6)3.&yy>FAy530yy>@y3yyWyW^kd^oj^opey
OW^_o^$gfkyKyW^kd^oj^ope%0.)2-&yy>FAy530yy>@y.4yyWyW^kd^oj^opey
OEbtk?ldyKyW^kd^oj^ope%/6)00&yy>FAy530yy>@y1yyWyW^kd^oj^opey
O>kdl$olpeDolrkapyKyW^kd^oj^ope%.4)/0&yy>FAy530yy>@y/yyWyW^kd^oj^opey
O>kdl$olpePqolkdeliayKyW^kd^oj^ope%.5)4&yy>FAy530yy>@y.0yyWyW^kd^oj^opey
OJ^opeifdeqI^hbyKyW^kd^oj^ope%//)1-&yy>FAy530yy>@y2yyWyW^kd^oj^opey
OPmlobdd^oyKyW^kd^oj^ope%.5)2-&yy>FAy530yy>@y./yyWyW^kd^oj^opey
OQebPm^tkfkdDibkyKyW^kd^oj^ope%.1)3/&yy>FAy530yy>@y.3yyWyW^kd^oj^opey

OW^kd^oOfadbyKyK^do^ka%00).2&yy>FAy533yy>@y.6yyWyK^do^kay
OT^oj^riEfiiyKyK^do^ka%/4)/.&yy>FAy533yy>@y..yyWyK^do^kay
OI^rdefkdPhriiOrfkpyKyJ^hbprobvlr^obfkqeborfkp^kaklqlsboQebOfkdlc?illacloafp`lsbov+%13).6&yy>FAy533yy>@y2yyWyK^do^kay
OQeolkblcqebBibjbkqpyKyK^do^ka%3-)/0&yy>FAy533yy>@y.-yyWyK^do^kay
OD^o^a^oyKyK^do^ka%23)03&yy>FAy533yy>@y/yyWyK^do^kay
OPlrqetfka@ibcqyKyK^do^ka%16)22&yy>FAy533yy>@y.2yyWyK^do^kay
OE^i^^yKyK^do^ka%1/)11&yyWyK^do^kayy>FAy533yy>@y0yyWyK^do^kay
OPrkpmofkdMlpqyKyK^do^ka%0.)10&yy>FAy533yy>@y4yyWyK^do^kay
OClodb@^jm7E^qbyKyK^do^ka%/1)02&yy>FAy533yy>@y.1yyWyK^do^kay
OQebQtfifdeqOfadbyKyK^do^ka%5)10&yy>FAy533yy>@y.3yyWyK^do^kay
OClodb@^jm7Cb^oyKyK^do^ka%.6)2.&yy>FAy533yy>@y.yyWyK^do^kay
OPmfofqCfbiapyKyK^do^ka%03)4.&yy>FAy533yy>@y3yyWyK^do^kay
OQbi^^oyKyK^do^ka%20)4-&yy>FAy533yy>@y5yyWyK^do^kay
O@i^kT^q`eyKyK^do^ka%3/)30&yy>FAy533yy>@y.0yyWyK^do^kay
OHfi$plooltCloqobppyKyK^do^ka%4-)5.&yy>FAy533yy>@y1yyWyK^do^kay
O?ibbafkdEliiltOrfkpyKyQbolhh^oClobpq%.6)3/&yy>FAy534yy>@y.yyWyQbolhh^oClobpqy
O?rokfkd?i^abOrfkpyKyK^do^ka%41)33&yy>FAy533yy>@y./yyWyK^do^kay
OQebOfkdlcQof^ipyKyK^do^ka%32)23&yy>FAy533yy>@y6yyWyK^do^kay
OTfkavobbaSfii^dbyKyK^do^ka%4/)2/&yy>FAy533yy>@y.5yyWyK^do^kay
OTfkavobbaM^ppyKyK^do^ka%4/)03&yy>FAy533yy>@y.4yyWyK^do^kay

OQeb?^oofboEfiipyKyQbolhh^oClobpq%/6)./&yy>FAy534yy>@y.-yyWyQbolhh^oClobpqy
OPe^qqo^qe@fqvyKyQbolhh^oClobpq%02)0-&yy>FAy534yy>@y5yyWyQbolhh^oClobpqy
O@bk^oflkQef`hbqyKyQbolhh^oClobpq%1.)//&yy>FAy534yy>@y0yyWyQbolhh^oClobpqy
ODo^kdli$s^oSfii^dbyKyQbolhh^oClobpq%05)06&yy>FAy534yy>@y2yyWyQbolhh^oClobpqy
O@^ooflkEfiiyKyQbolhh^oClobpq%1/)2/&yy>FAy534yy>@y.1yyWyQbolhh^oClobpqy
OObcrdbb@^o^s^kyKyQbolhh^oClobpq%04)2/&yy>FAy534yy>@y.2yyWyQbolhh^oClobpqy
OPe^altQlj_yKyQbolhh^oClobpq%0.)20&yy>FAy534yy>@y.4yyWyQbolhh^oClobpqy
OSbfiOe^wbyKyQbolhh^oClobpq%/1)26&yy>FAy534yy>@y.6yyWyQbolhh^oClobpqy
OOfkdlcL_pbos^k`byKyQbolhh^oClobpq%05)31&yy>FAy534yy>@y.3yyWyQbolhh^oClobpqy
O>r`ebk^fDolrkapyKyQbolhh^oClobpq%00)36&yy>FAy534yy>@y.0yyWyQbolhh^oClobpqy
OAbobif`q@^o^s^kyKyQbolhh^oClobpq%10)43&yy>FAy534yy>@y.5yyWyQbolhh^oClobpqy
OTofqefkdJlrkayKyQbolhh^oClobpq%2-)33&yy>FAy534yy>@y/-yyWyQbolhh^oClobpqy
O>iibof^kPqolkdeliayKyQbolhh^oClobpq%22)21&yy>FAy534yy>@y/yyWyQbolhh^oClobpqy
OPqlkb_ob^hboEliayKyQbolhh^oClobpq%16)13&yy>FAy534yy>@y3yyWyQbolhh^oClobpqy
OQrrobjyKyQbolhh^oClobpq%2.)/6&yy>FAy534yy>@y4yyWyQbolhh^oClobpqy
OO^^pqlhDi^abyKyQbolhh^oClobpq%3-)1-&yy>FAy534yy>@y6yyWyQbolhh^oClobpqy
OCfobtfkdMlfkqyKyQbolhh^oClobpq%4-)04&yy>FAy534yy>@y1yyWyQbolhh^oClobpqy
O?lkb`ebtboOrfkpyKyQbolhh^oClobpq%33)20&yy>FAy534yy>@y./yyWyQbolhh^oClobpqy
OPhbqqfpyKy>kvm^oqlcPhbqqfppelriadfsbvlrqebafp`lsbov+%34)40&yy>FAy534yy>@y/.yyWyQbolhh^oClobpqy

OIbdflkEliayKyPe^altjllkS^iibv%/0)05&yy>FAy531yy>@y0yyWyPe^altjllkS^iibvy
OPe^altjllkSfii^dbyKyPe^altjllkS^iibv%/6)/5&yy>FAy531yy>@y2yyWyPe^altjllkS^iibvy
OQebAb^qeclodbyKyPe^altjllkS^iibv%1-)06&yy>FAy531yy>@y4yyWyPe^altjllkS^iibvy
OQebE^kalcDri$a^kyKyQebCbiMfqptlohp^ptbii+%2-)1/&yy>FAy531yy>@y5yyWyPe^altjllkS^iibvy
O@lfiph^oMlfkqyKyPe^altjllkS^iibv%12)/5&yy>FAy531yy>@y.yyWyPe^altjllkS^iibvy
O>iq^olcPe^$q^oyKyPe^altjllkS^iibv%3.)/6&yy>FAy531yy>@y..yyWyPe^altjllkS^iibvy
O>q^$j^iQboo^`byKy>kvmoqlcQeb?i^`hQbjmibtfii`ljmibqbqefpafp`lsbov%34)05&yy>FAy531yy>@y3yyWyPe^altjllkS^iibvy
OT^oabk$p@^dbyKyPe^altjllkS^iibv%3-)15&yy>FAy531yy>@y6yyWyPe^altjllkS^iibvy
OKbqebotfkdCfbiapyKyPe^altjllkS^iibv%31)24&yy>FAy531yy>@y.0yyWyPe^altjllkS^iibvy
OKbqebotfkdIbadbyKyPe^altjllkS^iibv%4-)52&yy>FAy531yy>@y1yyWyPe^altjllkS^iibvy
OB`ifmpbMlfkqyKyPe^altjllkS^iibv%13)35&yy>FAy531yy>@y/yyWyPe^altjllkS^iibvy
OTfiae^jjboPqolkdeliayKyPe^altjllkS^iibv%02)25&yy>FAy531yy>@y.-yyWyPe^altjllkS^iibvy
OFiifa^ofMlfkqyKyPe^altjllkS^iibv%/6)22&yy>FAy531yy>@y./yyWyPe^altjllkS^iibvy

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
