DugisGuideViewer:RegisterGuide("Hail to the Chef Meta Cooking Achievement (75+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob^qib^pqibsbi42+Qefpfpqeberdb`llhfkdjbq^^`efbsbjbkqdrfabtef`e^t^oapvlrqeb9@ebc;qfqib+Qebob^obpbsbo^i^`efbsbjbkqpobnrfobaqlalqefp)plqefpdrfabtfiiqov^kadlqeorqebjpqbm_vpqbm+Qefpdrfabtfii^iplrqfifwblqeboA^fivdrfabp^ptbii+Ibqpdbqpq^oqba+y

KCfpefkdyKyDo^kaJ^pqboCfpefkdfpklqobnrfobaql`ljmibqbqefp>`efbsbjbkq)eltbsbofqfpefdeivob`ljjbkabaqe^qvlre^sbfqqlalqebA^fivcfpefkdnrbpqfkPe^qqo^qe^kaA^i^o^kcloXOb`fmb7@^mq^fkOrjpbv$pI^dboZ+y

KDo^kaJ^pqbo@llhfkdyKyVlrjrpqe^sbDo^kaJ^pqbo@llhfkdcfopq^kaclobjlpq+Ptfq`eqlqeb@llhfkdMolcbppflkdrfab^kal_q^fkDo^kaJ^pqbofk`llhfkd+yy>FAy.451yy>@y.y

K@llhfkdA^fifbpyKyPq^oqalfkdqebA^fiv`llhfkdnrbpqpfk_lqeA^i^o^k^kaPe^qqo^qe+CloqebPe^qqo^qea^fifbpvlr^obillhfkdclo1ob`fmbp+Q^hbqeb@o^qblcJb^qrkqfivlrdbqXOb`fmb7Pmf`vElqQ^i_rhZ^kaXOb`fmb7Hf_ibo$p?fqpZ+Qebkptfq`eqlqeb?^oobilccfpecloXOb`fmb7PhriicfpePlrmZ^kaXOb`fmb7?olfiba?illacfkZ+XOb`fmb7Pqloj`elmpZ^kaXOb`fmb7Abif`flrp@el`li^qb@^hbZe^sb^`e^k`bqlaolmcolj^ii`llhfkda^fifbp)pl`lkqfkrba^fifbpfkPe^qqo^qerkqfivlre^sb_lqelcqebpb+y

KQebLrqi^kaDlrojbqyKyL_q^fk^ka`llhqebcliiltfkdob`fmbp+J^hbprobvlrp^jmib^iilcvlroafpebp+yy>FAy.451yy>@y..y
KQo^fk@llhfkdOb`fmbpyKySfpfqHvibkb%43+2)00+4&fkPe^qqo^qe@fqv^kaqo^fkCfpeboj^k$pCb^pq)Elq?rqqbobaQolrq)^kaPqbtbaQolrq+yyWyPe^qqo^qe@fqvy
?Ob`fmb7O^s^dboAldyKy@llhfbLkb*Bvb%21+3)1.+.&yyWyEbiicfobMbkfkpri^yyIy/4355y
>Pjllqe^p?rqqboyKyIbd^ppf%16+/)41+5&yyNFAy6023yyWyEbiicfobMbkfkpri^y
@Pjllqe^p?rqqboyKy?ofkd./Mirjm?rww^oaTfkdp%3-+0)36+2&qlIbd^ppf+P^sbX?rww^oaJb^qZcloob`fmb+yyNFAy6023yyWyEbiicfobMbkfkpri^y
QPjllqe^p?rqqboyKyIbd^ppf%16+/)41+5&yyNFAy6023yyWyEbiicfobMbkfkpri^y
K@llh?rww^oa?fqbpyKy.uX?rww^oaJb^qZ)jl_pclrka^olrka%3-+0)36+2&yyWyEbiicfobMbkfkpri^yy>FAy.5--yy>@y0y
K@llhO^s^dboAldyKy.uXO^s^dboCibpeZ)jl_pclrka^olrka%/0+6)35+0&yyWyEbiicfobMbkfkpri^yy>FAy.5--yy>@y3y
?Ob`fmb7Cbiq^fiAbifdeqyKyWro^f%52+/)21+4&yyWyW^kd^oj^opeyyIy/4362y
?Ob`fmb7?i^`hbkbaPmlobcfpeyKyGrklArco^fk%42+.)33+-&yyWyW^kd^oj^opeyyIy/4363y
?Ob`fmb7?i^`hbkbaQolrqyKyD^j_^ofkh^%0.+4)16+0&yyWyW^kd^oj^opeyyIy/4361y
?Ob`fmb7PmlobifkdPk^`hyKyJv`^e%.4+6)2.+/&+ObnrfobpKbrqo^itfqePmlobdd^o+yyWyW^kd^oj^opeyyIy/4356y
?Ob`fmb7@i^j?^oyKyJv`^e%.4+6)2.+/&+ObnrfobpKbrqo^itfqePmlobdd^o+yyWyW^kd^oj^opeyyIy0-.23y
K@llhCbiq^fiAbifdeqyKy.uXPmlqqbaCbiq^fiZ)cfpebafkW^kd^oj^ope+yy>FAy.5--yy>@y2yyWyW^kd^oj^opey
K@llh?i^`hbkbaQolrqyKy.uX?^o_baDfiiQolrqZ)cfpebafkW^kd^oj^ope+yy>FAy.5--yy>@y/yyWyW^kd^oj^opey
K@llhPqbtbaQolrqyKy.uX?^o_baDfiiQolrqZ)cfpebafkW^kd^oj^ope+yy>FAy.5--yy>@y/3yyWyW^kd^oj^opey
K@llh?i^`hbkbaPmlobcfpeyKy.uXW^kd^of^kPmlobcfpeZ)cfpebafkW^kd^oj^ope+yy>FAy.5--yy>@y5yyWyW^kd^oj^opey
K@llhPmlobifkdPk^`hyKy.uXPqo^kdbPmlobZcoljPmlob_^qploJ^opeT^ihbopyy>FAy.5--yy>@y6yyWyW^kd^oj^opey
K@llh@i^j?^oyKy/uXG^dd^i@i^jJb^qZ+ClrkafkXG^dd^i@i^jZ+yy>FAy.5--yy>@y1yyWyW^kd^oj^opey
?Ob`fmb7?i^`hbkba?^pfifphyKyFkkhbbmboDofih^%15+5)12+.&yyWyQbolhh^oClobpqyyIy/436-y
?Ob`fmb7T^om?rodboyKyFkkhbbmboDofih^%15+5)12+.&yyWyQbolhh^oClobpqyyIy/436/y
?Ob`fmb7DliabkCfpePqf`hpyKyOrkdlo%15+5)13+.&yyWyQbolhh^oClobpqyyIy/4366y
?Ob`fmb7Pmf`v@o^ta^ayKyOrkdlo%15+5)13+.&yyWyQbolhh^oClobpqyyIy/44--y
K@llh?i^`hbkba?^pfifphyKy.uX@erkhl$?^pfifphZ)jl_pclrka%25+3)06+0&yy>FAy.5--yy>@y.-yyWyQbolhh^oClobpqy
K@llhT^om?rodboyKy.uXT^ombaCibpeZ)jl_pclrka%25+3)06+0&yy>FAy.5--yy>@y.5yyWyQbolhh^oClobpqy
K@llhDliabkCfpePqf`hpyKy.uXDliabkA^oqboZ)cfpebafkQbolhh^oClobpq+yy>FAy.5--yy>@y.1yyWyQbolhh^oClobpqy
K@llhPmf`v@o^ta^ayKy.uXCroflrp@o^ta^aZ)cfpebafkEfdei^kaJfubaP`ellimllipfkQbolhh^oClobpq+yy>FAy.5--yy>@y/1yyWyQbolhh^oClobpqy
?Ob`fmb7@ork`evPbombkqyKyUbofkqe^O^sbkl^h%3/+2)1-+0&yyWy?i^ab$pBadbJlrkq^fkpyyIy0.341y
?Ob`fmb7Jlh$K^qe^iPeloqof_pyKyUbofkqe^O^sbkl^h%3/+2)1-+0&yyWy?i^ab$pBadbJlrkq^fkpyyIy0.342y
K@llh@ork`evPbombkqyKy.uXPbombkqCibpeZ)jl_pclrka^olrka%32+-)21+5&+yyWy?i^ab$pBadbJlrkq^fkpyy>FAy.5--yy>@y.6y
K@llhJlh$K^qe^iPeloqof_pyKy.uXO^mqloOf_pZ)jl_pclrka^olrka%32+-)21+5&+yyWy?i^ab$pBadbJlrkq^fkpyy>FAy.5--yy>@y/-y
?Ob`fmb7DofiibaJracfpeyKyKri^qeb?rq`ebo%25+.)02+4&yyWyK^do^kayyIy/4364y
?Ob`fmb7Ml^`eba?irbcfpeyKyKri^qeb?rq`ebo%25+.)02+4&yyWyK^do^kayyIy/4365y
?Ob`fmb7Ol^pqba@ibcqellcyKyKri^qeb?rq`ebo%25+.)02+4&yyWyK^do^kayyIy/436.y
?Ob`fmb7Q^i_rhPqb^hyKyKri^qeb?rq`ebo%25+.)02+4&yyWyK^do^kayyIy/4360y
K@llhCfpeboj^k$pCb^pqyKy.uXErdbPmlqqbaCbiq^fiZ)cfpebafkpm^tkbamllip^olrka%24)0/&yy>FAy.5--yy>@y/.yyWyK^do^kay
K@llhElq?rqqbobaQolrqyKy.uXBklojlrp?^o_baDfiiQolrqZ)cfpebafkpm^tkbamllip^olrka%24)0/&yy>FAy.5--yy>@y//yyWyK^do^kay
K@llhDofiibaJracfpeyKy.uXCfdirpqbo$pJracfpeZ)cfpebafkK^do^ka+yy>FAy.5--yy>@y..yyWyK^do^kay
K@llhMl^`eba?irbcfpeyKy.uXF`bcfk?irbcfpeZ)cfpebafkK^do^ka+yy>FAy.5--yy>@y./yyWyK^do^kay
K@llhOl^pqba@ibcqellcyKy.uX@ibcqellcJb^qZ)jl_pclrka^olrka%3/+3)10+5&+yy>FAy.5--yy>@y.3yyWyK^do^kay
K@llhQ^i_rhPqb^hyKy.uXQ^i_rhSbkfplkZ)jl_pclrka^olrka%3/+3)10+5&+yy>FAy.5--yy>@y.4yyWyK^do^kay
K@llhPmf`vElqQ^i_rhyKyHbbmalfkdPe^qqo^qe@llhfkdA^fiv^kamf`hqebX@o^qblcJb^qZobt^oa+.uXQ^i_rhSbkfplkZ)jl_pclrka^olrka%3/+3)10+5&+yy>FAy.5--yy>@y/2yyWyK^do^kay
K@llhHf_ibo$p?fqpyKyHbbmalfkdPe^qqo^qe@llhfkdA^fiv^kamf`hqebX@o^qblcJb^qZobt^oa+.uX?rww^oaJb^qZ)jl_pclrka^olrka%3-+0)36+2&yyWyEbiicfobMbkfkpri^yy>FAy.5--yy>@y.2y
K@llhPhriicfpePlrmyKyHbbmalfkdPe^qqo^qe@llhfkdA^fiv^kamf`hqebX?^oobilcCfpeZobt^oa+.uX@obp`bkq*Q^fiPhriicfpeZ)cfpebafkAb^atfkaM^pp+yy>FAy.5--yy>@y/0y
K@llh?olfiba?illacfkyKyHbbmalfkdPe^qqo^qe@llhfkdA^fiv^kamf`hqebX?^oobilcCfpeZobt^oa+.uX?illacfk@^qcfpeZ)cfpebafkAb^atfkaM^pp+yy>FAy.5--yy>@y.0y
K@llhPqloj`elmpyKyHbbmalfkdqeb@llhfkdA^fifbpfkPe^qqo^qe@fqv^kaA^i^o^krkqfiqefpaolmp+.uX@ibcqelccJb^qZ).uXIfdeqkfkdBbiZ+yy>FAy.5--yy>@y4y
K@llhAbif`flrp@el`li^qb@^hbyKyHbbmalfkdqeb@llhfkdA^fifbpfkPe^qqo^qe@fqv^kaA^i^o^krkqfiqefpaolmp+5uXPfjmibCilroZ)1uXF`b@liaJfihZ)1uXJfiaPmf`bZ)5uXPj^iiBddZ).uXCi^phlcMloqZ)0uXJ^dbolv^iZ+yy>FAy.5--yy>@y.y

KKloqeobkaDlrojbqyKyL_q^fk^ka`llhqebcliiltfkdob`fmbp+J^hbprobvlrp^jmib^iilcvlroafpebp+yy>FAy.451yy>@y1y
>Kloqebok@llhfkdyKyQelj^pHlif`efl%45+4)/6+2&+yyNFAy.0-56yyWyEltifkdCgloay
@Kloqebok@llhfkdyKy?ofkd1uX@efiibaJb^qZqlQelj^pHlif`efl+X@efiibaJb^qZ`^k_bclrkalk^kvKloqeobka_b^pq+yyNFAy.0-56yyWyEltifkdCgloay
QKloqebok@llhfkdyKyQelj^pHlif`efl%45+4)/6+2&+yyNFAy.0-56yyWyEltifkdCgloay
K@llhKloqebokPqbtyKy.uX@efiibaJb^qZ)aolmpcoljjl_p^iilsbokloqeobka+yy>FAy.446yy>@y./y

KKloqeobka@llhfkdQo^fkfkdyKyQebcliiltfkdob`fmbp^obQo^fk^_ibcolj>tfilIlk$dlj_^%4-+/)04+2&yyWyA^i^o^ky
K@llh?^hbaJ^kq^O^vyKy.uXFjmbof^iJ^kq^O^vZyy>FAy.446yy>@y/y
K@llhA^i^o^k@i^j@eltaboyKy/uXPr``ribkq@i^jJb^qZ+Clrkafk?ollafkdA^oht^qbo@i^jyy>FAy.446yy>@y4yyWy?lob^kQrkao^y
K@llhDob^qCb^pqyKy.uX@erkhl$J^jjlqeZ).uXPelsbiqrphCi^khZ).uXTlojJb^qZ)/uX@efiibaJb^qZ+J^hbcfsblcqebpb^kap^sbqebjcloqebAfkkboFjmlppf_ib^`efbsbjbkq+yy>FAy.446yy>@y./y
K@llhDofiiba?lkbp`^ibyKy.uX?lkbp`^ibPk^mmboZyy>FAy.446yy>@y.0y
K@llhDofiibaP`rimfkyKy.uXJrppbi_^`hP`rimfkZyy>FAy.446yy>@y.1y
K@llhJ^jjlqeJb^iyKy.uX@erkhl$J^jjlqeZyy>FAy.446yy>@y/-y
K@llhMf`hibaC^kdqllqeyKy.uXC^kdqllqeEboofkdZyy>FAy.446yy>@y/1y
K@llhMl^`ebaKbqqibcfpeyKy.uXKbqqibcfpeZyy>FAy.446yy>@y/2y
K@llhOefklAldpyKy.uXOefklJb^qZyy>FAy.446yy>@y/4y
K@llhOl^pqbaTlodyKy.uXTlodE^rk`eZyy>FAy.446yy>@y/6y
K@llhP^rqbbaDl_vyKy.uX?^oobieb^aDl_vZyy>FAy.446yy>@y0-y
K@llhPelsbiqrphPqb^hyKy.uXPelsbiqrphCi^khZyy>FAy.446yy>@y0.y
K@llhPjlhbaOl`hcfkyKy.uXOl`hcfkDolrmboZyy>FAy.446yy>@y00y
K@llhPjlhbaP^ijlkyKy.uXDi^`f^iP^ijlkZyy>FAy.446yy>@y01y
K@llhTlojAbifdeqyKy.uXTlojJb^qZyy>FAy.446yy>@y12y

KKloqeobka@llhfkdOb`fmbpyKyJfpbkpf%4-+/)/4+/&pbiip^iilcqebpbob`fmbpcloXA^i^o^k@llhfkd>t^oaZ$pyyWyA^i^o^ky
K@llh?i^`hbkbaAo^dlkcfkyKy.uXAo^dlkcfk>kdbicfpeZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y0y
K@llh@ofqqbo?fqbpyKy/uX@efiibaJb^qZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y2y
K@llhCfob`o^`hboP^ijlkyKy.uXDi^`f^iP^ijlkZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y6y
K@llhDfd^kqf`Cb^pqyKy/uXAbbmPb^Jlkpqbo_biivZ)/uX@erkhl$J^jjlqeZ)/uXOl`hcfkDolrmboZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y..y
K@llhFjmbof^iJ^kq^Pqb^hyKy.uXFjmbof^iJ^kq^O^vZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y.4y
K@llhJbd^J^jjlqeJb^iyKy/uX@erkhl$J^jjlqeZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y/.y
K@llhPk^mmboBuqobjbyKy0uX?lkbp`^ibPk^mmboZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y02y
K@llhPmf`baTloj?rodboyKy/uXTlojJb^qZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y04y
K@llhPmf`vCofbaEboofkdyKy.uXC^kdqllqeEboofkdZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y06y
K@llhQbkaboPelsbiqrphPqb^hyKy/uXPelsbiqrphCi^khZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y1.y
K@llhSbov?rokqTlodyKy.uXTlodE^rk`eZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y10y
K@llh?i^`hbkbaTlodPqb^hyKy.uXTlodE^rk`eZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y1y
K@llh@rqqibpqb^hyKy.uXJllkdilt@rqqibcfpeZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y3y
K@llhAo^dlkcfkCfibqyKy.uXAo^dlkcfk>kdbicfpeZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y5y
K@llhCfpeCb^pqyKy/uXJrppbi_^`hP`rimfkZ)/uXDi^`f^iP^ijlkZ)/uXKbqqibcfpeZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y.-y
K@llhEb^oqvOefklyKy.uXOefklJb^qZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y.3y
K@llhJfdeqvOefklAldpyKy/uXOefklJb^qZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y//y
K@llhMl^`ebaKloqebokP`rimfkyKy.uXJrppbi_^`hP`rimfkZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y/3y
K@llhOefklif`flrpTlojpqb^hyKy.uXOefklJb^qZ).uXTlojJb^qZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y/5y
K@llhPj^iiCb^pqyKy/uXOefklJb^qZ)/uXDi^`f^iP^ijlkZ)/uXKbqqibcfpeZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y0/y
K@llhPmf`baJ^jjlqeQob^qpyKy.uX@erkhl$J^jjlqeZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y03y
K@llhPmf`v?irbKbqqibcfpeyKy.uXKbqqibcfpeZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y05y
K@llhQo^`hboPk^`hpyKy.uXPelsbiqrphCi^khZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y1/y
K@llhTlodQ^oq^obyKy/uXTlodE^rk`eZ).uXKloqebokPmf`bpZyy>FAy.446yy>@y1/y

KAolmmba@llhfkdOb`fmbpyKyQebcliiltfkdob`fmbp^obtloiaaolmp+Vlrtfiijlpqifhbivcfkaqebjaolmmfkdfkebolf`arkdblkp+J^hbprob^kab^qb^`elkbcloqebPb`lkaQe^qBjlqflk>`efbsbjbkq+y
K@llh?^a@i^jpyKy.uXPr``ribkq@i^jJb^qZ).uXJlqblcPe^altZ+J^hbprob^kab^qlkb+yy>FAy.446yy>@y.y
K@llhE^rkqbaEboofkdyKy.uXC^kdqllqeEboofkdZ).uXBppbk`blcRkab^qeZ+J^hbprob^kab^qlkb+yy>FAy.446yy>@y.2y
K@llhI^pqTbbh$pJ^jjlqeyKy.uX@erkhl$J^jjlqeZ+J^hbprob^kab^qlkb+yy>FAy.446yy>@y.6y
K@llhQ^pqv@rm`^hbyKy/uXPfjmibCilroZ).uXKloqebokBddZ+J^hbprob^kab^qlkb+yy>FAy.446yy>@y1-y

KPb`lkaQe^qBjlqflkyKyB^qqebcliiltfkdbjlqflkcllap8X?^a@i^jpZ)XI^pqTbbhpJ^jjlqeZ)XE^rkqbaEboofkdZ)XQ^pqv@rm`^hbZ+yy>FAy.451yy>@y2y

K@ofqqboDfqqboyKyRpfkd@ofqqbo?fqbp)`lbo`b.-`ofqqbopql_bvlrombqtfqefk0jfkrqbploibpp+Kb^oqeb>odbkqQlrok^jbkq^ob^cil`hlcmbkdrfkp%32+4)/.+3&+Qefpfp^dllami^`bqlalqefp^`efbsbjbkq+yy>FAy.451yy>@y3yyWyF`b`oltky

KAfkkboFjmlppf_ibyKyMobpbkq^XDob^qCb^pqZfkqebcliiltfkd?^qqibdolrkap8>iqbo^`S^iibv)T^oplkdDri`e)BvblcqebPqloj)>o^qef?^pfk)Pqo^kalcqeb>k`fbkqp+Vlralk$qe^sbql`ljmibqbqeb?D$pqldbqqeb^`efbsbjbkq)grpqi^vlrqqebcb^pq)dbq`obafq^kaib^sb+yy>FAy.451yy>@y5y

KPlrp@ebcyKyVlrpelriahklt^qib^pq^erkaobpob`fmbp_vklt)_rqfcklq)efqrmqebqo^fkbofkLodofjj^o^kaj^hbprobvlre^sbqo^fkbabsbovqefkd+yy>FAy.451yy>@y6y

KPe^qqo^qeA^fivyKy@lkqfkrbalfkdqebA^fivfkPe^qqo^qe@fqvrkqfivlre^sb`ljmibqba^iiclrocloHf`hfk$FqRm^Klq`e^`efbsbjbkq+yy>FAy.451yy>@y0y
KA^i^o^kA^fivyKy@lkqfkrbalfkdqebA^fivfkA^i^o^krkqfivlre^sb`ljmibqba^iicfsbcloLroA^fiv?ob^a>`efbsbjbkq+yy>FAy.450y

K@llh@^mq^fkOrjpbv$pI^dboyKyXOb`fmb7@^mq^fkOrjpbv$pI^dboZfpl_q^fkbacoljqebCfpefkda^fiv^kacoljqebA^i^o^k@llhfkda^fiv+.uXPhfklcAt^osbkPqlrqZ).uXCi^dlklcJb^aZ+yy>FAy.451yy>@y.-y

KHrkd^illpeyKyJ^hbprobvlre^sb`ljmibqbaqebPeli^w^o?^pfkdrfabrmql^kafk`irafkdQebQ^pqbQbpqy
>Cibq`ebo$pIlpq^kaClrkayKyT^peba*RmJ^db%11+/)/2+2&)fkqebRkabo_biiv+yyWyA^i^o^ky
K@llhHrkd^illpeyKy/uXQrkao^?boofbpZ).uXP^slovPkltmirjZyy>FAy.446yy>@y.5y

KDrfab@ljmibqb+
]]
end)
