DugisGuideViewer:RegisterGuide("Hemet Nesingwary: The Collected Quests (75+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabdlbplsboqebEbjbqKbpfkdt^ovnrbpq^`efbsbjbkq+Fqtfii^pprjbqe^qvlr^ob^qib^pq42+y
KIltIbsbiNrbpqpyKyJ^hbprobvlr^obqo^hfkdiltibsbinrbpqpqlj^hbfqb^pfboqlpbbqebnrbpqpdfsbop+y
OPqo^kdibqelokS^ibyKyQo^sbiqlPqo^kdibqelok%02).-&yyNFAy250yyWyPqo^kdibqelokS^iby
OKbpfkdt^ov$pBumbafqflkyKyCliiltqebol^akloqe)illhclo^ifqqib`^jm_vqebofsbo%02).-&yyNFAy250yyWyPqo^kdibqelokS^iby

>Tbi`ljbqlqebGrkdibyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy250yyWyPqo^kdibqelokS^iby
QTbi`ljbqlqebGrkdibyKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy250yyWyPqo^kdibqelokS^iby

>QebDobbkEfiiplcPqo^kdibqelokyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy005yyWyPqo^kdibqelokS^iby
>@e^mqboFyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy006yyWyPqo^kdibqelokS^iby
>@e^mqboFFyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy01-yyWyPqo^kdibqelokS^iby
>@e^mqboFFFyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy01.yyWyPqo^kdibqelokS^iby
>@e^mqboFSyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy01/yyWyPqo^kdibqelokS^iby
KP^sb^iiM^dbpyKyP^sb^iiDobbkEfiiplcPqo^kdibqelokm^dbp+Vlrtfiikbbaqebcliiltfkdm^dbp8.)1)3)5).-)..).1).3).5)/-)/.)/1)/2)/3)/4yyNFAy.52y

>QfdboJ^pqbov%M^oq.&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.52yyWyPqo^kdibqelokS^iby
>M^kqeboJ^pqbov%M^oq.&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6-yyWyPqo^kdibqelokS^iby
>O^mqloJ^pqbov%M^oq.&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.61yyWyPqo^kdibqelokS^iby

@QfdboJ^pqbov%M^oq.&yKyHfii.-VlrkdPqo^kdibqelokQfdboppifdeqivqlqebb^pq%02).1&yyNFAy.52yyWyPqo^kdibqelokS^iby
@M^kqeboJ^pqbov%M^oq.&yKyHfii.-VlrkdM^kqebopqlqebkloqe%1.)6&yyNFAy.6-yyWyPqo^kdibqelokS^iby

QM^kqeboJ^pqbov%M^oq.&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6-yyWyPqo^kdibqelokS^iby
>M^kqeboJ^pqbov%M^oq/&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6.yyWyPqo^kdibqelokS^iby

QQfdboJ^pqbov%M^oq.&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.52yyWyPqo^kdibqelokS^iby
>QfdboJ^pqbov%M^oq/&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.53yyWyPqo^kdibqelokS^iby

@M^kqeboJ^pqbov%M^oq/&yKyHfii.-M^kqebopb^pqlcqeb`^jm%/6)..&yyNFAy.6.yyWyPqo^kdibqelokS^iby
@QfdboJ^pqbov%M^oq/&yKyHfii.-Qfdbopb^pqlcqeb`^jm%0-).2&yyNFAy.53yyWyPqo^kdibqelokS^iby
@O^mqloJ^pqbov%M^oq.&yKyHfii.-Pqo^kdibqelokO^mqlopb^pqkb^oqeborfkp%/5).1&yyNFAy.61yyWyPqo^kdibqelokS^iby

QO^mqloJ^pqbov%M^oq.&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.61yyWyPqo^kdibqelokS^iby
>O^mqloJ^pqbov%M^oq/&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.62yyWyPqo^kdibqelokS^iby

QM^kqeboJ^pqbov%M^oq/&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6.yyWyPqo^kdibqelokS^iby
>M^kqeboJ^pqbov%M^oq0&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6/yyWyPqo^kdibqelokS^iby

QQfdboJ^pqbov%M^oq/&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.53yyWyPqo^kdibqelokS^iby
>QfdboJ^pqbov%M^oq0&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.54yyWyPqo^kdibqelokS^iby

@QfdboJ^pqbov%M^oq0&yKyHfii.-BiaboPqo^kdibqelokQfdbop_bqtbbkqebqoliiorfkp^kaKbppfkdt^ov$p`^jm%01).6&yyNFAy.54yyWyPqo^kdibqelokS^iby
@O^mqloJ^pqbov%M^oq/&yKyHfii.-I^peq^fiO^mqlopkb^oDolj$dli%05)/0&yyNFAy.62yyWyPqo^kdibqelokS^iby

QQfdboJ^pqbov%M^oq0&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.54yyWyPqo^kdibqelokS^iby
>QfdboJ^pqbov%M^oq1&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.55yyWyPqo^kdibqelokS^iby
QO^mqloJ^pqbov%M^oq/&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.62yyWyPqo^kdibqelokS^iby
>O^mqloJ^pqbov%M^oq0&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.63yyWyPqo^kdibqelokS^iby

@QfdboJ^pqbov%M^oq1&yKyPfk$A^iifplkqlmlc^kb^o_vefii%0.).4&yyNFAy.55yyWyPqo^kdibqelokS^iby
@M^kqeboJ^pqbov%M^oq0&yKyHfiiPe^altj^tM^kqebop%15)/.&lo%05)04&yyNFAy.6/yyWyPqo^kdibqelokS^iby
@O^mqloJ^pqbov%M^oq0&yKyHfii.-GrkdibPq^ihbop%0.)1.&yyNFAy.63yyWyPqo^kdibqelokS^iby

QQfdboJ^pqbov%M^oq1&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.55yyWyPqo^kdibqelokS^iby
QM^kqeboJ^pqbov%M^oq0&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6/yyWyPqo^kdibqelokS^iby
>M^kqeboJ^pqbov%M^oq1&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.60yyWyPqo^kdibqelokS^iby
QO^mqloJ^pqbov%M^oq0&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.63yyWyPqo^kdibqelokS^iby
>O^mqloJ^pqbov%M^oq1&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.64yyWyPqo^kdibqelokS^iby

@M^kqeboJ^pqbov%M^oq1&yKyHfii?e^d$qebo^^kaillqqebXC^kdlc?e^d$qebo^Z%2-)/3&yyNFAy.60yyWyPqo^kdibqelokS^iby
@O^mqloJ^pqbov%M^oq1&yKyHfiiQbqefp%/5)11&yyNFAy.64yyWyPqo^kdibqelokS^iby

QM^kqeboJ^pqbov%M^oq1&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.60yyWyPqo^kdibqelokS^iby
QO^mqloJ^pqbov%M^oq1&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.64yyWyPqo^kdibqelokS^iby

>?fdD^jbErkqboyKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy/-5yyWyPqo^kdibqelokS^iby
@?fdD^jbErkqboyKyHfiiHfkd?^kd^i^pe%05)02&^kaq^hbqebXEb^alc?^kd^i^peZyyNFAy/-5yyWyPqo^kdibqelokS^iby
Q?fdD^jbErkqboyKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy/-5yyWyPqo^kdibqelokS^iby

Q@e^mqboFyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy006yyWyPqo^kdibqelokS^iby
Q@e^mqboFFyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy01-yyWyPqo^kdibqelokS^iby
Q@e^mqboFFFyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy01.yyWyPqo^kdibqelokS^iby
Q@e^mqboFSyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy01/yyWyPqo^kdibqelokS^iby

QQebDobbkEfiiplcPqo^kdibqelokyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy005yyWyPqo^kdibqelokS^iby

OK^do^kayKyQo^sbiqlK^do^kafkqebLrqi^ka%4.)1-&yyWyK^do^kayNFAy6521y
OKbpfkdt^ovP^c^ofyKyFkqebkloqeb^pq`lokbolcqebwlkb%4.)1-&yyNFAy6521yyWyK^do^kay
QQebKbpfkdt^ovP^c^ofyKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy.-..1yyWyK^do^kay
>Tfkaol`J^pqbov%M^oq.&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6521yyWyK^do^kay
>@ibcqellcJ^pqbov%M^oq.&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy6456yyWyK^do^kay
>Q^i_rhJ^pqbov%M^oq.&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6524yyWyK^do^kay

@Tfkaol`J^pqbov%M^oq.&yKyHfii0-Tfkaol`p^olrka%35)06&yyNFAy6521yyWyK^do^kay
@Q^i_rhJ^pqbov%M^oq.&yKyHfii0-Q^i_rhPq^dp^olrka%3-)1/&yyNFAy6524yyWyK^do^kay
@@ibcqellcJ^pqbov%M^oq.&yKyHfii0-@ibcqellc^olrka%32)14&yyNFAy6456yyWyK^do^kay

QTfkaol`J^pqbov%M^oq.&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6521yyWyK^do^kay
>Tfkaol`J^pqbov%M^oq/&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6522yyWyK^do^kay
Q@ibcqellcJ^pqbov%M^oq.&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy6456yyWyK^do^kay
>@ibcqellcJ^pqbov%M^oq/&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652-yyWyK^do^kay
QQ^i_rhJ^pqbov%M^oq.&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6524yyWyK^do^kay
>Q^i_rhJ^pqbov%M^oq/&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6525yyWyK^do^kay

@Q^i_rhJ^pqbov%M^oq/&yKyHfii0-Q^i_rhQelokdo^wbop^olrka%2-)/0&)_bqtbbkI^rdefkdphriiorfkp^kaQeolkblcbibjbkqp+Hbbm^kbvblrqcloarkdclo>O^ob?b^kqll*fqob^iiv_ibkapfk)_rqfq$pfkqefp^ob^yyNFAy6525yyWyK^do^kay
@@ibcqellcJ^pqbov%M^oq/&yKyHfii0-@ibcqellc?riip^olrkaqefp^ob^%2-)0-&yyNFAy652-yyWyK^do^kay
@Tfkaol`J^pqbov%M^oq/&yKyHfii0-O^sbklrpTfkaol`p^olrka%2-)3-&yyNFAy6522yyWyK^do^kay

Q@ibcqellcJ^pqbov%M^oq/&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652-yyWyK^do^kay
>@ibcqellcJ^pqbov%M^oq0&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652.yyWyK^do^kay
QQ^i_rhJ^pqbov%M^oq/&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6525yyWyK^do^kay
>Q^i_rhJ^pqbov%M^oq0&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6526yyWyK^do^kay
QTfkaol`J^pqbov%M^oq/&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6522yyWyK^do^kay
>Tfkaol`J^pqbov%M^oq0&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6523yyWyK^do^kay

@Tfkaol`J^pqbov%M^oq0&yKyVlrpelria_b^_ibqlplilqefpb^pv)vlr`^kcfkaDrqofmmbo^olrkaqebdo^pp_bclobT^oj^riEfii^olrka%00)0-&yyNFAy6523yyWyK^do^kay
@Q^i_rhJ^pqbov%M^oq0&yKyHfii?^`e$ilo^ka`liib`qefpellc)vlrpelria_b^_ibqlplilqefpnrbpq)ebm^qolip_bqtbbkqebqtlClodb@^jmp%/2)15&)%/4)05&yyNFAy6526yyWyK^do^kay
@@ibcqellcJ^pqbov%M^oq0&yKyHfii?^kqe^o^ka`liib`qefpelok)ebm^qolipfk^olrkaLper$drk%0.)2.&)%1/)3.&yyNFAy652.yyWyK^do^kay

OKbpfkdt^ovP^c^ofyKyFkqebkloqeb^pq`lokbolcqebwlkb%4.)1-&yyWyK^do^kay
QTfkaol`J^pqbov%M^oq0&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6523yyWyK^do^kay
Q@ibcqellcJ^pqbov%M^oq0&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652.yyWyK^do^kay
QQ^i_rhJ^pqbov%M^oq0&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6526yyWyK^do^kay

>QebRiqfj^qb?illapmloqyKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652/yyWyK^do^kay
@QebRiqfj^qb?illapmloqyKyHfiiQrphbo%11)32&^ka`liib`qXEb^oqlcQrphboZvlrtfiikbbaebimcloqefpnrbpqlqebotfpbphfmfqyyNFAy652/yyWyK^do^kay
QQebRiqfj^qb?illapmloqyKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652/yyWyK^do^kay

OPeli^w^o?^pfkyKyQo^sbiqlPeli^w^o?^pfkfkKloqeobka%/4+/)26+5&yyNFAy./2/1yyWyPeli^w^o?^pfky
>Sbkqrob@l+Jfp^asbkqrobyKyAb_^^o%/4+/)26+5&yyNFAy./2/1yyWyPeli^w^o?^pfky
>Kbba^kBkdfkb)Q^hb^kBkdfkbyKyTbpibuNrf`htobk`e%/2+2)25+2&yyNFAy./2//yyWyPeli^w^o?^pfky
@Kbba^kBkdfkb)Q^hb^kBkdfkbyNFAy./2//yyKyTfiadoltqeJ^kd^i%05+3)23+5&yyWyPeli^w^o?^pfky
QKbba^kBkdfkb)Q^hb^kBkdfkbyKyTbpibuNrf`htobk`e%/2+2)25+2&yyNFAy./2//yyWyPeli^w^o?^pfky
>E^sb^M^oq)Dfsb^M^oqyKyTbpibuNrf`htobk`e%/2+2)25+2&yyNFAy./2/0yyWyPeli^w^o?^pfky

@E^sb^M^oq)Dfsb^M^oqyNFAy./2/0yyKyClrka^qPtfkaibdofk$pAfd^olrka%00+6)15+2&yyWyPeli^w^o?^pfky
@Sbkqrob@l+Jfp^asbkqrobyNFAy./2/1yyKyClrka^qPtfkaibdofk$pAfd^olrka%00+6)15+2&yyWyPeli^w^o?^pfky

QSbkqrob@l+Jfp^asbkqrobyKyAb_^^o%/4+/)26+5&yyNFAy./2/1yyWyPeli^w^o?^pfky
>TfmbQe^qDofkLccEfpC^`byKyAb_^^o%/4+/)26+5&yyNFAy./2/2yyWyPeli^w^o?^pfky
QE^sb^M^oq)Dfsb^M^oqyKyTbpibuNrf`htobk`e%/2+2)25+2&yyNFAy./2/0yyWyPeli^w^o?^pfky

@TfmbQe^qDofkLccEfpC^`byNFAy./2/2yyKy?^`h^qqebafd)illhcloClobj^kPtfkaibdofk^kaJb^qmfblk^mi^qcloj^q%02+5)2-+1&yyWyPeli^w^o?^pfky

QTfmbQe^qDofkLccEfpC^`byKyAb_^^o%/4+/)26+5&yyNFAy./2/2yyWyPeli^w^o?^pfkyyWyPeli^w^o?^pfky

>Aob^ap^_boJ^pqbov7?b`ljfkd^Moba^qloyKy?r`h@^kqtbii%/3+5)26+.&yyNFAy./216yyWyPeli^w^o?^pfky
>OefklJ^pqbov7QebQbpqyKyEbjbqKbpfkdt^ov%/4+.)25+4&yyNFAy./2/-yyWyPeli^w^o?^pfky

@OefklJ^pqbov7QebQbpqyNFAy./2/-yyKyKloqetbpqlc`^jm^olrka%/4+/)2/+6&yyWyPeli^w^o?^pfky
@Aob^ap^_boJ^pqbov7?b`ljfkd^Moba^qloyNFAy./216yyKyKloqetbpqlc`^jm^ilkdqebpfabplcqebol^a^olrka%/4+/)2/+6&yyWyPeli^w^o?^pfky

QAob^ap^_boJ^pqbov7?b`ljfkd^Moba^qloyKy?r`h@^kqtbii%/3+5)26+.&yyNFAy./216yyWyPeli^w^o?^pfky
>Aob^ap^_boJ^pqbov7Pq^ihfkdqebMobvyKy?r`h@^kqtbii%/3+5)26+.&yyNFAy./22-yyWyPeli^w^o?^pfky
QOefklJ^pqbov7QebQbpqyKyEbjbqKbpfkdt^ov%/4+.)25+4&yyNFAy./2/-yyWyPeli^w^o?^pfky
>OefklJ^pqbov7Qeb@e^pbyKyEbjbqKbpfkdt^ov%/4+.)25+4&yyNFAy./2/3yyWyPeli^w^o?^pfky
>@ol`lifphJ^pqbov7QebQof^iyKyAb_^^o%/4+/)26+5&yyNFAy./22.yyWyPeli^w^o?^pfky
QOefklJ^pqbov7Qeb@e^pbyKyLo^`ibPll*o^ej%/2+3)33+1&yyNFAy./2/3yyWyPeli^w^o?^pfky
>>kLccbofkdcloPll*o^ejyKyLo^`ibPll*o^ej%/2+3)33+1&yyNFAy./210yyWyPeli^w^o?^pfky

@Aob^ap^_boJ^pqbov7Pq^ihfkdqebMobvyNFAy./22-yyKyKloqe)^ilkdqebpeloblc?fqqboqfabI^hb%04+.)1.+6&yyWyPeli^w^o?^pfky
@>kLccbofkdcloPll*o^ejyNFAy./210yyKyXFkq^`q@l_o^C^kdpZaolmlccBjmbolo@l_o^p^olrkaqebTfiadoltqeJ^kd^i%10+4)24+1&yyWyPeli^w^o?^pfky
@@ol`lifphJ^pqbov7QebQof^iyNFAy./22.yyKyHfiiJ^kd^i@ol`lifphp^olrkaqebTfiadoltqeJ^kd^i%10+4)24+1&yyWyPeli^w^o?^pfky

Q>kLccbofkdcloPll*o^ejyKyLo^`ibPll*o^ej%/2+3)33+1&yyNFAy./210yyWyPeli^w^o?^pfky
>Qeb?lkbplcKlwolkkyKyLo^`ibPll*o^ej%/2+3)33+1&yyNFAy./211yyWyPeli^w^o?^pfky

@Qeb?lkbplcKlwolkkyNFAy./211yyRy052.6yyKyArbplrqe)rpbXPll*o^ej$pFk`bkpbZ^qqeblccbofkd_ltifkcolkqlcqeb?lkbplcKlwolkk%/3+-4)4.+2-&yyWyPeli^w^o?^pfky

Q@ol`lifphJ^pqbov7QebQof^iyKyAb_^^o%/4+/)26+5&yyNFAy./22.yyWyPeli^w^o?^pfky
>@ol`lifphJ^pqbov7QebMi^kyKyAb_^^o%/4+/)26+5&yyNFAy./23-yyWyPeli^w^o?^pfky
QAob^ap^_boJ^pqbov7Pq^ihfkdqebMobvyKy?r`h@^kqtbii%/3+5)26+.&yyNFAy./22-yyWyPeli^w^o?^pfky
>Aob^ap^_boJ^pqbov7Ob^avqlMlrk`byKy?r`h@^kqtbii%/3+5)26+.&yyNFAy./225yyWyPeli^w^o?^pfky
QQeb?lkbplcKlwolkkyKyEbjbqKbpfkdt^ov%/4+.)25+4&yyNFAy./211yyWyPeli^w^o?^pfky
>OefklJ^pqbov7QebHfiiyKyEbjbqKbpfkdt^ov%/4+.)25+4&yyNFAy./223yyWyPeli^w^o?^pfky

@@ol`lifphJ^pqbov7QebMi^kyNFAy./23-yyKyD^qebo2XP^kacbokpZ^ilkdqeb_^khplcqebofsbo^kaqebOfsbo$pEb^oqi^hb^olrka%14+-)3-+6&yyWyPeli^w^o?^pfky
@OefklJ^pqbov7QebHfiiyNFAy./223yyKyHfiiC^orkkqlqebkloqe)grpqplrqelcqebDifjjbofkdMfii^o%15+/)11+3&yyWyPeli^w^o?^pfky
@Aob^ap^_boJ^pqbov7Ob^avqlMlrk`byNFAy./225yyKyHfiiPe^kdlqlqebtbpq)grpqkloqelcqebJ^hbo$pMbo`e%0/+4)02+3&yyWyPeli^w^o?^pfky

QOefklJ^pqbov7QebHfiiyKyEbjbqKbpfkdt^ov%/4+.)25+4&yyNFAy./223yyWyPeli^w^o?^pfky
QAob^ap^_boJ^pqbov7Ob^avqlMlrk`byKy?r`h@^kqtbii%/3+5)26+.&yyNFAy./225yyWyPeli^w^o?^pfky
Q@ol`lifphJ^pqbov7QebMi^kyKyAb_^^o%/4+/)26+5&yyNFAy./23-yyWyPeli^w^o?^pfky
>@ol`lifphJ^pqbov7Qeb>j_rpeyKyAb_^^o%/4+/)26+5&yyNFAy./236yyWyPeli^w^o?^pfky

@@ol`lifphJ^pqbov7Qeb>j_rpeyNFAy./236yyRy05231yyKyLkqebb^pq_^khlcOfsbo$pEb^oqi^hb)rpbqebXP^kacbokAfpdrfpbZkb^oqebc^iibkild%14+6)33+.&yyWyPeli^w^o?^pfky

Q@ol`lifphJ^pqbov7Qeb>j_rpeyKyAb_^^o%/4+/)26+5&yyNFAy./236yyWyPeli^w^o?^pfky
>FkPb^o`elc?fddboD^jbyKyEbjbqKbpfkdt^ov%/4+.)25+4&yyNFAy./262yyWyPeli^w^o?^pfky

QFkPb^o`elc?fddboD^jbyKyAlof^kAo^hbpq^ihbo%1/+1)/5+4&yyNFAy./262yyWyPeli^w^o?^pfky
>Pe^ombkfkdVlroQ^ilkpyKyAlof^kAo^hbpq^ihbo%1/+1)/5+4&yyNFAy./3-0yyWyPeli^w^o?^pfky
>Pb`rofkdqeb?^fqyKyAlof^kAo^hbpq^ihbo%1/+1)/5+4&yyNFAy./3-2yyWyPeli^w^o?^pfky

@Pb`rofkdqeb?^fqyNFAy./3-2yyKyGrpqqlqebb^pqlcqeblrqmlpqfkqebP^s^dbQef`hbq%14+.)/4+-&+>qq^`hbddp^kaillqqebXMofjloaf^iE^q`eifkdpZyyWyPeli^w^o?^pfky
@Pe^ombkfkdVlroQ^ilkpyNFAy./3-0yyKyGrpqqlqebb^pqlcqeblrqmlpqfkqebP^s^dbQef`hbq%14+.)/4+-&yyWyPeli^w^o?^pfky
QPe^ombkfkdVlroQ^ilkpyKyAlof^kAo^hbpq^ihbo%1/+1)/5+4&yyNFAy./3-0yyWyPeli^w^o?^pfky
QPb`rofkdqeb?^fqyKyAlof^kAo^hbpq^ihbo%1/+1)/5+4&yyNFAy./3-2yyWyPeli^w^o?^pfky
>>J^jjlqeRkaboq^hfkdyKyWllqcfwwib%1/+/)/5+6&yyNFAy./3-4yyWyPeli^w^o?^pfky

@>J^jjlqeRkaboq^hfkdyNFAy./3-4yyRy053/4yyKyRpbqebXJ^jjlqeE^okbppZlk^j^jjlqe^olrka%2/+/)/1+6&^ka_ofkdefj_^`hqlWllqcfwwibyyWyPeli^w^o?^pfky

Q>J^jjlqeRkaboq^hfkdyKyWllqcfwwib%1/+/)/5+6&yyNFAy./3-4yyWyPeli^w^o?^pfky
>Mlpq*m^oqrj>ddobppflkyKyAlof^kAo^hbpq^ihbo%1/+1)/5+4&yyNFAy./3.1yyWyPeli^w^o?^pfky

@Mlpq*m^oqrj>ddobppflkyNFAy./3.1yyKyCfka?ollajlqeboPifsfk^lkqebkloqebkalcqebP^s^dbQef`hbq%13+5)/.+2&yyWyPeli^w^o?^pfky

QMlpq*m^oqrj>ddobppflkyKyAlof^kAo^hbpq^ihbo%1/+1)/5+4&yyNFAy./3.1yyWyPeli^w^o?^pfky

KDrfab@ljmibqb

]]
end)
