DugisGuideViewer:RegisterGuide("The Keymaster Achievement (80+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^a+yKyPljblcqebpbhbvp^obaolmp)pljbnrbpqobt^oap^ka^`lrmibclojobmdofkap+Tb$sbalkblro_bpqqldfsb^iimlppf_ib^sbkrbpqll_q^fkqebpbhbvp+y

KJ^qbof^ipKbbabayKyJ^hbprobvlre^sbqebcliiltfkdj^qbof^ipfkvlro_^dp+Vlr`^kc^ojcloqebjlo_rvqebjcolj>r`qflkElrpb+XQelofrj?^oZu/)XCbiFolk?^oZu1)X>o`^kbArpqZu/)XJlqblcCfobZu1y
eA^i^o^kyKyPbqvlroeb^oqeqlA^i^o^k%32+2)0/+/&yyWyA^i^o^ky

OLodofjj^oyKyMloq^iqlLodofjj^o%22+1)/2+2&yyWyLodofjj^oy
>@efbcBkdfkbboP`llqvyKyPlsfh%42+3)/2+/&yyWyLodofjj^oyyNFAy/51/y

C@^jmJlg^`ebyKyQo^sbiql@^jmJlg^`eb%12+.)30+6&Cbo^i^pyyWyLodofjj^oyy>FAy..54yy>@y/y
OAfobJ^riB^pqyKyQo^sbiqlAfobJ^riB^pq%26)11&yyWyCbo^i^pyy>FAy..54yy>@y/y
KQ^ihqlMrpfiifkyKyVlre^sbqlq^ihqlefj^kacliiltefjqfiiebfp^qq^`h^_ib+yy>FAy..54yy>@y/y
HMrpfiifkyKyClrkafkAfobJ^ri)aolmpX@obp`bkqHbvZyyWyAfobJ^riyy>FAy..54yy>@y/y

EA^i^o^kyRy3615y

ORkabo`fqvyKyQ^hbMloq^ifkA^i^o^k%22+3)/0+6&yyWyA^i^o^kyy>FAy..54yy>@y5y
KJ^qbof^ipyKyJ^hbprobvlre^sb/XQelofrj?^oZyyIy./026/yy>FAy..54yy>@y5y
OP`^oibqJlk^pqbovyKyQo^sbiqlP`^oibqJlk^pqbov%51)/0&yyWyQfofpc^iDi^abpyy>FAy..54yy>@y5y
H>o`^kfpqAl^kyKy@^k_bclrkafkqebIf_o^ovTfkd)tef`efqqebcfopqfkpq^k`blkqebibcq+yyWyP`^oibqJlk^pqbovyy>FAy..54yy>@y5y
KIllqPqolkd_luyKyEfppqlkd_lue^pQebXP`^oibqHbvZyy>FAy..54yy>@y5y

OQeb?rit^ohyKyQo^sbiqlqeb?rit^oh%51)4-&yyWyQfofpc^iDi^abpy
>P`elilj^k`byKyEfdeBub`rqloAboofkdqlk%50).)36+-&yyNFAy505yyWyQfofpc^iDi^abpy
QP`elilj^k`byKy>mlqeb`^ovAfqebop%50+/)36+0&yyNFAy505yyWyQfofpc^iDi^abpy
>Phbibq^iCo^djbkqpyKy>mlqeb`^ovAfqebop%50+/)36+0&yyNFAy631yyWyQfofpc^iDi^abpy
@Phbibq^iCo^djbkqpyKy?ofkd.2XPhbibq^iCo^djbkqpZql>mlqeb`^ovAfqebop^qqeb?rit^oh%11+3)36+5&yyNFAy631yyWyTbpqbokMi^drbi^kapy
QPhbibq^iCo^djbkqpyKy>mlqeb`^ovAfqebop%50+/)36+0&yyNFAy631yyWyQfofpc^iDi^abpy
>JliaOevjbpTfqe+++yKy>mlqeb`^ovAfqebop%50+/)36+0&yyNFAy22.1yyWyQfofpc^iDi^abpy

CRkabo`fqvyKyCivqlRkabo`fqv%50+3)4-&yyWyQfofpc^iDi^abpy
CCi^jb@obpqyKyCivqlCi^jb@obpq)?rokfkdPqbmmbp%30+0)15+3&yyWyRkabo`fqvy

O?i^`hol`hJlrkq^fkyKyQo^sbiql?i^`hol`hJlrkq^fk%/5+5)/5+6&yyWy?rokfkdPqbmmbpyy>FAy..54yy>@y3y
KCo^k`ilokClodbtofdeqyKy@^k_bclrkafkqeb`bkqbofpi^ka^pvlreb^aclo?i^`hol`hAbmqep+Vlre^sbql_bab^aqlpbbefj^ka^``bmqnrbpq+yy>FAy..54yy>@y3y
>A^ohFolkIbd^`vM^oq.yKyCo^k`ilokClodbtofdeqVlrjrpq_bab^aql^``bmqqefpnrbpq%/5+5)/5+6&yyNFAy05-.yyWy?rokfkdPqbmmbpy
QA^ohFolkIbd^`vM^oq.yKyCo^k`ilokClodbtofdeqVlrjrpq_bab^aqlQrokfkqefpnrbpq%/5+5)/5+6&yyNFAy05-.yyWy?rokfkdPqbmmbpy
>A^ohFolkIbd^`vM^oq/yKyCo^k`ilokClodbtofdeqVlrjrpq_bab^aql^``bmqqefpnrbpq%/5+5)/5+6&yyyNFAy05-/yyWy?rokfkdPqbmmbpy
O?i^`hol`hAbmqepyKyWlkbfkqlqeb?i^`hol`hAbmqepfkpq^k`b%/3+5)4/+3&yyWyPb^ofkdDlodby
@A^ohFolkIbd^`vM^oq/yKyHfiiCfkblrpA^ohsfobfk?i^`hol`hAbmqep^kaillqFolkcbiyyNFAy05-/y
QA^ohFolkIbd^`vM^oq/yKyRpbFolkcbi^qJlkrjbkqlcCo^k`ilokClodbtofdeqfkpfab?i^`hol`hAbmqepyyNFAy05-/y
KPe^altclodbHbvyKyPelriaklte^sbqebXPe^altclodbHbvZyy>FAy..54yy>@y3y
O?i^`hol`hJlrkq^fkyKyOrklrqlc?OA)logrpqafb^kaobwlrqpfabqebfkpq^k`by

C?llqv?^vyKy%01+5)0-+6&?^ai^kapyyWyPb^ofkdDlodbyy>FAy..54yy>@y.-y
Q@efbcBkdfkbboP`llqvyKyP`llqv%/4+3)44+2&yyWyPqo^kdibqelokS^ibyyNFAy/51/y
>Dkljbo*dlllllkbyKyP`llqv%/4+3)44+2&yyWyPqo^kdibqelokS^ibyyNFAy/510y
QDkljbo*dlllllkbyKyP`llqv%/4+3)44+2&yyWyPqo^kdibqelokS^ibyyNFAy/510y

ODkljbobd^kyKyRpbP`llqv$pmloq^i%/3)44+2&yyWyPqo^kdibqelokS^ibyy>FAy..54yy>@y.-y
OQeb@il`htbohOrkyKyWlkbfkqlqebarkdblk%.4+4)06+.&yyWyArkJloldey
HBib`qol`rqflkbo3---yKyClrkafkDkljbobd^kfkqebi^odbolljfkqebTbpqbokpfablcqebj^m)aolmpXTlohpelmHbvZobcboqlJ^mmolsfabatfqelrodrfabyy>FAy..54yy>@y.-yyWyDkljbobd^ky

EA^i^o^kyRy3615y

K@^sbokplcQfjbyKyVlrtfiikbbaql_bElklobatfqeqebHbbmboplcQfjbqll_q^fkXHbvlcQfjbZ+Kltfp^dllaqfjbqldbqqe^qobm+>tbiidb^oba5-pelria_b^_ibqlcfkfpeqebnrbpqp^kafkpq^k`bpqe^qcliilt+Fcklq)fksfqb^`lriblccofbkapqlq^d^ilkd+y
O@^sbokplcQfjbyKyQ^hbMloq^ifkA^i^o^k%Sflibq@fq^abi&ql@^sboklcQfjb%/2+4)2.+/&yyWyA^i^o^ky
>QlQebJ^pqbo$pI^foyKyPqbt^oalcQfjb%33+-)16+4&yyNFAy.-/46yyWyQ^k^ofpy
QQlQebJ^pqbo$pI^foyKyQ^hbqebao^dlkaltkfkqlqeb@^sbokp^kacfka>kalojr%25+1)21+0&Qebhfa)klqqebsbkalo+yyNFAy.-/46yyWyQ^k^ofpy
>Qeb@^sbokplcQfjbyKy>kalojr%25+1)21+0&yyNFAy.-/44yyWyQ^k^ofpy
@Qeb@^sbokplcQfjbyKyCliiltqeb@rpqlaf^klcQfjb^ppebq^hbpvlr^olkaqeb@^sbok+yyNFAy.-/44yyWyQ^k^ofpy
QQeb@^sbokplcQfjbyKy>kalojr%25+1)21+0&yyNFAy.-/44yyWyQ^k^ofpy
>LiaEfiip_o^ayKy>kalojr%25+1)21+0&yyNFAy.-/5/yyWyQ^k^ofpy
QLiaEfiip_o^ayKy>kalojr^qqeb@^sbokplcQfjbe^p^phbaqe^qvlrsbkqrobqlLiaEfiip_o^a^kapmb^htfqeBolwflk+yyNFAy.-/5/y
>Q^obqe^$pAfsbopflkyKyBolwflkyyNFAy.-/50y
@Q^obqe^$pAfsbopflkyKyQo^sbiqlArokeliabHbbm^kapbq2fk`bkaf^ov`e^odbp^qqeb_^oobipil`^qbafkpfabb^`elcqebfkqbokjbkqiladbp+yyRy/2520yyNFAy.-/50y
QQ^obqe^$pAfsbopflkyKyQeo^iiyyNFAy.-/50y
>Bp`^mbcoljArokeliabyKyQeo^iiyyNFAy.-/51y
@Bp`^mbcoljArokeliabyKyTebkvlr^obob^avqlmol`bba)ibqQeo^iihklt+CliiltQeo^iilrqlcArokeliabHbbm^kaebimefjcobbQ^obqe^^kacricfiiefpabpqfkv+yyNFAy.-/51y
QBp`^mbcoljArokeliabyKyBolwflkyyNFAy.-/51y
>Obqrokql>kalojryKyBolwflkyyNFAy.-/52y
QObqrokql>kalojryKy>kalojr%25+1)21+0&yyNFAy.-/52yyWyQ^k^ofpy
>Qeb?i^`hJlo^ppyKy>kalojr%25+1)21+0&yyNFAy.-/63yyWyQ^k^ofpy
QQeb?i^`hJlo^ppyKyQo^sbiqeolrdeqeb@^sbokplcQfjbqlqeb?i^`hJlo^pparofkdqeblmbkfkdlcqebA^ohMloq^i^kapmb^htfqeP^$^q+yyNFAy.-/63y
>QebLmbkfkdlcqebA^ohMloq^iyKyP^$^qyyNFAy.-/64y
@QebLmbkfkdlcqebA^ohMloq^iyKyP^$^qfkpfabqeb?i^`hJlo^pplcqeb@^sbokplcQfjbe^pq^phbavlrtfqeabcbkafkdJbafserkqfiebpr``bbapfklmbkfkdqebA^ohMloq^i+yyNFAy.-/64y
QQebLmbkfkdlcqebA^ohMloq^iyKyP^$^qyyNFAy.-/64y
>Ebollcqeb?ollayKyP^$^qyyNFAy.-/65y
QEbollcqeb?ollayKy>kalojr%25+1)21+0&yyNFAy.-/65yyWyQ^k^ofpy
?HbvlcQfjbyKy?rvXHbvlcQfjbZcolj>irojf%30+3)24+3&fkqeb@^sbokplcQfjb)obnrfobpHbbmboplcQfjbElklobaobmyyWyQ^k^ofpyy>FAy..54yy>@y0y

OD^adbqw^kyKyQo^sbiqlD^adbqw^kfkQ^k^ofp%2.+2)/5+5&yyNFAy25-.yyWyQ^k^ofpy
QJliaOevjbpTfqe+++yKyQ^hb.2d^kaXFj_rbaPhbibq^iCo^djbkqpZqlHofkhibDllapqbbi%2.+2)/5+5&yyNFAy22.1yyWyQ^k^ofpy
>CfobMirjbClodbayKyHofkhibDllapqbbi%2.+2)/5+5&yyNFAy25-/yyWyQ^k^ofpy
CJ^ope^i$pObcrdbyKy%2/+3)/2+1&Rk$Dlol@o^qboyyWyQ^k^ofpy
@CfobMirjbClodbayKyRpbXPhbibqlkHbvJliaZ^qi^s^i^hb%16)13&yyRy.1311yyNFAy25-/yyWyRk$Dlol@o^qboy

EA^i^o^kyRy3615y
ORkabo`fqvyKyQ^hbmloq^iqlRkabo`fqv%22+3)/0+6&yyWyA^i^o^ky
OQeb?rit^ohyKyQo^sbiqlQeb?rit^oh%50+1)36+2&yyWyQfofpc^iDi^abpyyNFAy201.y

QCfobMirjbClodbayKy>mlqeb`^ovAfqebop%50+/)36+0&yyNFAy25-/yyWyQfofpc^iDi^abpy
>>o^g$pP`^o^_yKy>mlqeb`^ovAfqebop%50+/)36+0&yyNFAy25-1yyWyQfofpc^iDi^abpy
OTbpqbokMi^drbi^kapyKyQo^sbiqlTbpqbokMi^drbi^kap%12+2)36+/&yyNFAy22..yyWyTbpqbokMi^drbi^kapy
H>o^gqebPrjjlkboyKy%12+2)36+/&yyNFAy25-1yyWyTbpqbokMi^drbi^kapy
@>o^g$pP`^o^_yKyIllq>o^g$pMevi^`qbovcloX>o^g$pP`^o^_Z%12+2)36+/&yyNFAy25-1yyWyTbpqbokMi^drbi^kapy
Q>o^g$pP`^o^_yKy>mlqeb`^ovAfqebop%50+/)36+0&yyNFAy25-1yyWyQfofpc^iDi^abpy
>QebHbvqlP`elilj^k`byKy>mlqeb`^ovAfqebop%50+/)36+0&yyNFAy22..yyWyQfofpc^iDi^abpy
QQebHbvqlP`elilj^k`byKy>mlqeb`^ovAfqebop%50+/)36+0&yyNFAy22..yyWyQfofpc^iDi^abpy
KPhbibqlkHbvyKyXPhbibqlkHbvZ>nrfobayy>FAy..54yy>@y6y

OQeb?rit^ohyKyQo^sbiqlQeb?rit^oh%50+1)36+2&yyWyQfofpc^iDi^abpyyNFAy201.y
CIfdeq$pElmb@e^mbiyKyCivqlIfdeq$pElmb@e^mbi%50+3)4-&yyWyQfofpc^iDi^abpy
OPqo^qelijbyKy%/4).-&yyWyB^pqbokMi^drbi^kapy
HJ^dfpqo^qb?^oqefi^pyKyBkqboqebifsbpfab)qrokofdeq^kaqebkhbbmqlqebibcq^kacliilt^olrkaqlab^apfabqlcfkaJ^dfpqo^qb?^oqefi^p+EbaolmpqebXHbvqlqeb@fqvZyy>FAy..54yy>@y1y

EA^i^o^kyRy3615y

OPe^qqo^qe@fqvyKyQ^hbMloq^iFkA^i^o^k%23+0)//+3&yyWyA^i^o^ky
OPbqebhhE^iipyKyBkqboPbqebhhE^iip%1/)32+3&yyWyQbolhh^oClobpqy
HQ^ilkHfkdFhfppyKyClrkafkPbqebhhE^iipy
KIllq@lccboyKyIllqefp@lccbocloXPe^altI^_vofkqeHbvZyy>FAy..54yy>@y2y

KIltbo@fqvyKyVlr$iikbbaIltbo@fqvElklobaobmql_rvX>r`ebk^fHbvZ+FcvlrafanrbpqfkQbolhh^oClobpq)vlrpelria_b^qib^pqCofbkaiv+Vlr`^kdbq^mmolu.---obmclo`ib^ofkdPbqebhhE^iip^ka.42-obmclo`ib^ofkdPe^altI^_vofkqe+Mirpobmcoljpbsbo^inrbpqplrqpfabarkdblkp+Qefpfpqebc^pqbpq^kab^pfbpqt^vqldbqobmtfqeIltbo@fqv+>kLmqflk^it^vfpqlqrokfkX>o^hhl^Cb^qeboZu0-clo/2-obmb^`eqrok*fky

?>r`ebk^fHbvyKy?rvX>r`ebk^fHbvZcoljK^hlar%3/)36&)obnrfobpIltbo@fqvElklobaobmyyWyPe^qqo^qe@fqvyy>FAy..54yy>@y.y

OPe^altjllkS^iibvyKyQo^sbiqlPe^altjllkS^iibv%34+3)03+2&yyWyPe^altjllkS^iibvyyNFAy.-421y
HPjfqeDloirkhyKyAolmpXMofjbaHbvJliaZtef`epq^oqpnrbpq`e^fk%34+3)03+2&yyWyPe^altjllkS^iibvy
>BkqovFkqlqeb@fq^abiyKyXMofjbaHbvJliaZyyRy0./1.yyNFAy.-422y
QBkqovFkqlqeb@fq^abiyKy?ofkdqebMofjbaHbvJliaqlK^wdobi^qQeo^iij^o%22)03&yyNFAy.-422yyWyEbiicfobMbkfkpri^y
>Do^kaJ^pqboOlelhyKyK^wdobi%22)03&yyNFAy.-423yyWyEbiicfobMbkfkpri^y
QDo^kaJ^pqboOlelhyKy?ofkdqebMofjbaHbvJliaqlOlelh^qQeo^iij^o%20+/)05+/&yyNFAy.-423yyWyEbiicfobMbkfkpri^y
>Olelh$pObnrbpqyKyOlelh%20+/)05+/&yyNFAy.-424yyWyEbiicfobMbkfkpri^y
KJ^qbof^ipyKyJ^hbprobvlre^sbXCbiFolk?^oZu1)X>o`^kbArpqZu/)XJlqblcCfobZu1y
QOlelh$pObnrbpqyKy?ofkd1CbiFolk?^op)/>o`^kbArpq^ka1JlqbplcCfobqlOlelh^qQeo^iij^o%20+/)05+/&yyNFAy.-424yyWyEbiicfobMbkfkpri^y
>Elqqboqe^kEbiiyKyOlelh%20+/)05+/&yyNFAy.-425yyWyEbiicfobMbkfkpri^y
@Elqqboqe^kEbiiyKyAbpqolv^CbiOb^sbofkEbiicfobMbkfkpri^^kamirkdbqebXRkcfobaHbvJliaZfkqlfqpobj^fkp+yyRy0./2.yyNFAy.-425yyWyEbiicfobMbkfkpri^y
QElqqboqe^kEbiiyKyOlelh%20+/)05+/&yyNFAy.-425yyWyEbiicfobMbkfkpri^y
KHbv>nrfobayKyXPe^qqbobaE^iipHbvZyy>FAy..54yy>@y4y

EA^i^o^kyRy3615y

>Afp`obqflkfpHbvyKyOelkfk%0-+6)15+2&yyNFAy.0.25yyWyA^i^o^ky
QAfp`obqflkfpHbvyKyT^oabk>iqro^p%3.+2)30+2&yyNFAy.0.25yyWyA^i^o^ky
>@lkq^fkjbkqyKyT^oabk>iqro^p%3.+2)30+2&yyNFAy.0.26yyWyA^i^o^ky
KKlqbyKyXQebSflibqEliaHbvZfpmolsfabatebk^``bmqfkdqeb^_lsbnrbpq+Vlr`^kcfkfpeqebnrbpqfcvlr$aifhb)_rqfqfpklqkb`bpp^ov+yy>FAy..54yy>@y5y

KHbvj^pqboyKy@lkdo^qri^qflkplkHbvj^pqbo>`efbsbjkqDrfab@ljmibqby

]]
end)
