DugisGuideViewer:RegisterGuide("Kirin Tor Reputation (80+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabtfiidllsbo^iiqebnrbpqpqe^qdfsbobmtfqeqebHfofkQlo+Lk`b^iiqebnrbpqp^obalkb)qebkfpgrpqdofkafkdlrqqebobmb^q^_ibarkdblkp,qrok*fkpqldbqqlBu^iqba+Qefpdrfab^pprjbpqe^qvlr^obibsbi5-+y

O?lob^kQrkao^yKyQo^sbiql?lob^kQrkao^%25+2)34+5&yyNFAy..242yyWy?lob^kQrkao^y
>Qll@ilpbClo@ljcloqyKyBkalo^e%1.+5)21+4&yyNFAy..241yyWy?lob^kQrkao^y
QQll@ilpbClo@ljcloqyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..241yyWy?lob^kQrkao^y
>Mofplk?ob^hyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..254yyWy?lob^kQrkao^y
>JlkfqlofkdqebOfcq7@ibcq`ifcc>klj^ivyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy..243yyWy?lob^kQrkao^y

c>j_boIbadbyKyProofpqo^pw%12+0)01+2&yyNFAy..26-yyWy?lob^kQrkao^y

@JlkfqlofkdqebOfcq7@ibcq`ifcc>klj^ivyNFAy..243yyKyPlrqetbpq)m^pq?boviMlfkq)ptfjqlqebTbpqofcq%01+1)1/+.&^karpbqebX>o`^kljbqboZyyRy01336yyWy?lob^kQrkao^y
@Mofplk?ob^hyNFAy..254yyKy>q?boviMlfkq%1/+4)03+6&)hfiiJ^dbErkqbopcloqebhbvpyyWy?lob^kQrkao^y

QMofplk?ob^hyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..254yyWy?lob^kQrkao^y
>>_ar`qflkyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..26-yyWy?lob^kQrkao^y

QJlkfqlofkdqebOfcq7@ibcq`ifcc>klj^ivyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy..243yyWy?lob^kQrkao^y
>JlkfqlofkdqebOfcq7Prkaboba@e^pjyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy..25/yyWy?lob^kQrkao^y
@JlkfqlofkdqebOfcq7Prkaboba@e^pjyNFAy..25/yyKyPtfjkloqeb^pq)afsbaltkqlqebPrkaboba@e^pj%11+-)/5+3&)rpbqebX>o`^kljbqboZyyRy01336yyWy?lob^kQrkao^y
QJlkfqlofkdqebOfcq7Prkaboba@e^pjyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy..25/yyWy?lob^kQrkao^y
>JlkfqlofkdqebOfcq7Tfkqbocfk@^sbokyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy./4/5yyWy?lob^kQrkao^y

@>_ar`qflkyNFAy..26-yyKyDlcfka^?boviPlo`bobo)_b^qefj^_fq)qebkrpbqebX>o`^kb?fkaboZlkefjyyRy0136.yyWy?lob^kQrkao^y
Q>_ar`qflkyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..26-yyWy?lob^kQrkao^y
>Qeb?lob^kFknrfpfqflkyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..313yyWy?lob^kQrkao^y
QQeb?lob^kFknrfpfqflkyKyIf_o^of^kKloj^kqfp%13+1)0/+6&yyNFAy..313yyWy?lob^kQrkao^y
>Qeb>oqlcMbopr^pflkyKyIf_o^of^kKloj^kqfp%13+1)0/+6&yyNFAy..315yyWy?lob^kQrkao^y
@Qeb>oqlcMbopr^pflkyNFAy..315yyKyRpbqebXKbro^iKbbaiboZlkqebmofplkbofkqebqltboyyRy015..yyWy?lob^kQrkao^y
QQeb>oqlcMbopr^pflkyKyIf_o^of^kKloj^kqfp%13+1)0/+6&yyNFAy..315yyWy?lob^kQrkao^y
>Pe^ofkdFkqbiifdbk`byKyIf_o^of^kKloj^kqfp%13+1)0/+6&yyNFAy..330yyWy?lob^kQrkao^y
QPe^ofkdFkqbiifdbk`byKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..330yyWy?lob^kQrkao^y
>>O^`b>d^fkpqQfjbyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..34.yyWy?lob^kQrkao^y
@>O^`b>d^fkpqQfjbyNFAy..34.yyKyRpbqebX?boviPefbiaAbqlk^qloZlkqebi^odbolrkami^qcloj%1.+5)06+/&^kahfiiFknrfpfqloP^io^kayyRy01564yyWy?lob^kQrkao^y
Q>O^`b>d^fkpqQfjbyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..34.yyWy?lob^kQrkao^y
>ObclodfkdqebHbvyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..346yyWy?lob^kQrkao^y
QObclodfkdqebHbvyKyProofpqo^pw%12+0)01+2&yyNFAy..346yyWy?lob^kQrkao^y
>Q^hfkdTfkdyKyProofpqo^pw%12+0)01+2&yyNFAy..35-yyWy?lob^kQrkao^y
QQ^hfkdTfkdyKyT^oj^db>kwfj%13+1)04+0&yyNFAy..35-yyWy?lob^kQrkao^y
>Obp`rfkdBs^kloyKyT^oj^db>kwfj%13+1)04+0&yyNFAy..35.yyWy?lob^kQrkao^y
QObp`rfkdBs^kloyKy>o`ej^dbBs^klo%13+1)0/+2&yyNFAy..35.yyWy?lob^kQrkao^y
>Ao^dlkpmb^hyKy>o`ej^dbBs^klo%13+1)0/+2&yyNFAy..35/yyWy?lob^kQrkao^y
QAo^dlkpmb^hyKyProofpqo^pw%12+0)01+2&yyNFAy..35/yyWy?lob^kQrkao^y
>Qo^sbopfkdqebOfcqyKyProofpqo^pw%12+0)01+2&yyNFAy..400yyWy?lob^kQrkao^y

QQo^sbopfkdqebOfcqyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..400yyWy?lob^kQrkao^y
>Ob^afkdqebJbqbopyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6--yyWy?lob^kQrkao^y
>Pb`obqplcqeb>k`fbkqpyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6.-yyWy?lob^kQrkao^y
>Krqpclo?boofbpyKyIf_o^of^kPboo^e%00+2)01+1&yyNFAy..6./yyWy?lob^kQrkao^y

c@lia^oo^yKyT^oj^db>a^jf%00+/)01+2&yyNFAy..61.yyWy?lob^kQrkao^y

@Ob^afkdqebJbqbopyNFAy..6--yyKyCfkaqeblo_pqlob^a^qqebkloqe%0.+0)/-+0&)tbpq%//+1)/1+/&)plrqe%/5+0)01+6&)^kaaltkkb^oqebKburp%/5+0)/5+2&yyWy?lob^kQrkao^y
@Pb`obqplcqeb>k`fbkqpyNFAy..6.-yyKyHfiiJ^df`*_lrka>k`fbkq^olrka%/4+6)0/+1&^kaDi^`f^i>k`fbkq%0.+3)/1+1&^ka%/.+0)0.+6&yyWy?lob^kQrkao^y
@Krqpclo?boofbpyNFAy..6./yyKyPmob^aqeolrdelrq@lia^oo^)`liib`qqebjtefibnrbpqfkdyyWy?lob^kQrkao^y

QOb^afkdqebJbqbopyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6--yyWy?lob^kQrkao^y
QPb`obqplcqeb>k`fbkqpyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6.-yyWy?lob^kQrkao^y
QKrqpclo?boofbpyKyIf_o^of^kPboo^e%00+2)01+1&yyNFAy..6./yyWy?lob^kQrkao^y
>HbbmqebPb`obqP^cbyKyIf_o^of^kPboo^e%00+2)01+1&yyNFAy..6.1yyWy?lob^kQrkao^y
@HbbmqebPb`obqP^cbyNFAy..6.1yyKyHfii>o`^kbPbombkqpkb^oqebKburp%/5+2)/5+6&yyWy?lob^kQrkao^y
QHbbmqebPb`obqP^cbyKyIf_o^of^kPboo^e%00+2)01+1&yyNFAy..6.1yyWy?lob^kQrkao^y

>MlpqmlkfkdqebFkbsfq^_ibyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6-2yyWy?lob^kQrkao^y
>Nrf`hbkfkdyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6..yyWy?lob^kQrkao^y
>E^sbQebvKlPe^jb<yKyIf_o^of^kPboo^e%00+2)01+1&yyNFAy.0-61yyWy?lob^kQrkao^y
>MofplkbolcT^oyKyO^bilo^pw%00+0)01+2&yyWy?lob^kQrkao^yyNFAy..640yyWy?lob^kQrkao^y

OQebKburpyKyNrbrbcloqebQebKburptfqevlroarkdblkcfkaboyyNFAy.0-61yyFy

@E^sbQebvKlPe^jb<yKyVlr`^kcfkaqeb_llhfkqebjfaaiblcE^iilcPq^pfpfkqebibcqjfaaibpfablcqebj^myyNFAy.0-61y
@MlpqmlkfkdqebFkbsfq^_ibyKyRpbXFkqboafjbkpflk^iObc^_of`^qloZlk>klj^irpmi^qclojKloqeB^pqpfablcqebj^myyRy02146yyNFAy..6-2y
@Nrf`hbkfkdyKyDbq2X>o`^kbPmifkqbopZcolj@ovpq^iifkbMolqb`qlopfkQebPfkdfkdDolsbtfqefkQebKburpyyNFAy..6..y
@MofplkbolcT^oyKyBkqboQebKburp^kaobib^pbHbofpqo^pw^+Vlre^sbqlhfiiqebi^pq_lpplcqebkburpfkloaboql`ljmibqbqebnrbpqyyNFAy..640y

O?lob^kQrkao^yKyQbibmloq_^`hql?lob^kQrkao^%00+0)01+2&yyWy?lob^kQrkao^yyFy

QMofplkbolcT^oyKyO^bilo^pw%00+0)01+2&yyWy?lob^kQrkao^yyNFAy..640y
QMlpqmlkfkdqebFkbsfq^_ibyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6-2yyWy?lob^kQrkao^y
QNrf`hbkfkdyKy>o`ej^db?bofk^ka%00+-)01+0&yyWy?lob^kQrkao^yyNFAy..6..y
QE^sbQebvKlPe^jb<yKyIf_o^of^kPboo^e%00+2)01+1&yyWy?lob^kQrkao^yyNFAy.0-61y

@JlkfqlofkdqebOfcq7Tfkqbocfk@^sbokyNFAy./4/5yyKyEb^a^`olppqlqebTfkqbocfk@^sbokp%06+6)/-+.&)rpbqebX>o`^kljbqboZyyRy01336yyWy?lob^kQrkao^y
QJlkfqlofkdqebOfcq7Tfkqbocfk@^sbokyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy./4/5yyWy?lob^kQrkao^y

>Ofcibqeb?lafbpyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy..666yyWy?lob^kQrkao^y
@Ofcibqeb?lafbpyKyIllqqeb_lafbp^olrka%/2+/)25+6&)qebklmbkqebfqbjvlrdbqcoljqebjrkqfivlrdbqqebXJllkobpqD^oabkpMi^kpZyyNFAy..666yyWy?lob^kQrkao^y
QOfcibqeb?lafbpyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy..666yyWy?lob^kQrkao^y
>Mobsbkqqeb>``loayKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./--2yyWy?lob^kQrkao^y
@Mobsbkqqeb>``loayKyTfkaQo^aboJr$c^efplrqpfab^q%.5+1)25+3&)Dlo^jlpefpfkpfablkqebpb`lkaibsbi%.6+2)25&+T^q`eclofqbjaolmXDlo^jlpe$pPqo^kdbAbsf`bZqlpq^oqkbuqnrbpqyyNFAy./--2yyWy?lob^kQrkao^y
>>Pqo^kdbAbsf`byKyQebfqbjXDlo^jlpe$pPqo^kdbAbsf`bZpq^oqpnrbpq*aolmmba_vDlo^jlpe%.6+2)25&yyNFAy./-26yyRy03413yyWy?lob^kQrkao^y
QMobsbkqqeb>``loayKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./--2yyWy?lob^kQrkao^y
Q>Pqo^kdbAbsf`byKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-26yyWy?lob^kQrkao^y
>Molgb`qflkp^kaMi^kpyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-3.yyWy?lob^kQrkao^y
@Molgb`qflkp^kaMi^kpyKyRpbqebXProdbKbbaibQbibmloqboZ^q%//+2323+64&)dbq`ilpbbklrdeqldbq`obafq+Rpbfq^d^fkqldbqaltkyyNFAy./-3.yyRy03414yyWy?lob^kQrkao^y
QMolgb`qflkp^kaMi^kpyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-3.yyWy?lob^kQrkao^y
>QebCl`rplkqeb?b^`eyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-33yyWy?lob^kQrkao^y
@QebCl`rplkqeb?b^`eyKyHfii@^mq^fkBjjvJ^ifk^q%/3+3)32+.&qldbqqebXIbvIfkbCl`rp@lkqoliOfkdZ^karpbfqlkqebdf^kq^o`eqebobyyNFAy./-33yyRy0342.yyWy?lob^kQrkao^y
QQebCl`rplkqeb?b^`eyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-33yyWy?lob^kQrkao^y
>>qlmqebTllai^kapyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-51yyWy?lob^kQrkao^y
@>qlmqebTllai^kapyKyHfiiIfbrqbk^kqQ^$wfkkf%0/+/)4/+5&cloqebXIbvIfkbCl`rp@lkqoli>jribqZ)rpbfqlkqeb^o`eqebobyyNFAy./-51yyRy03446yyWy?lob^kQrkao^y
Q>qlmqebTllai^kapyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-51yyWy?lob^kQrkao^y
>Pb^o`eFkar$ibSfii^dbyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./.-3yyWy?lob^kQrkao^y
QPb^o`eFkar$ibSfii^dbyKyJ^db*@ljj^kaboBsbkpq^o%1-+/)33+6&yyNFAy./.-3yyWy?lob^kQrkao^y
>QebBkalcqebIfkbyKyJ^db*@ljj^kaboBsbkpq^o%1-+/)33+6&yyNFAy./..-yyWy?lob^kQrkao^y
RRpbXIbvIfkbCl`rp@lkqoliQ^ifpj^kZyKyRpbXIbvIfkbCl`rp@lkqoliQ^ifpj^kZyyRy035.2yyNFAy././/yyWy?lob^kQrkao^y
@QebBkalcqebIfkbyKyDll_pbosbqeb>wrobAo^dlkpeofkbkloqeb^pqlcqltk%20+-)32+1&yyNFAy./..-yyWy?lob^kQrkao^y
QQebBkalcqebIfkbyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./..-yyWy?lob^kQrkao^y

>QebJ^df`^iHfkdaljlcA^i^o^kyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./46.yyWy?lob^kQrkao^y
QQebJ^df`^iHfkdaljlcA^i^o^kyKy>o`ej^db@bifkao^%24+1)13+2&yyNFAy./46.yyWyA^i^o^ky
>Ib^okfkdqlIb^sb^kaObqrok7qebJ^df`^iT^vyKy>o`ej^db@bifkao^%24+1)13+2&yyNFAy./46-yyWyA^i^o^ky
@Ib^okfkdqlIb^sb^kaObqrok7qebJ^df`^iT^vyKy>o`ej^db@bifkao^^qQebSflibqD^qbfkA^i^o^kt^kqpvlrqlrpbqebQbibmloqqlSflibqPq^ka@ovpq^i^kaqebQbibmloqqlA^i^o^k@ovpq^i+yyNFAy./46-yyWyA^i^o^ky
QIb^okfkdqlIb^sb^kaObqrok7qebJ^df`^iT^vyKy>o`ej^db@bifkao^%24+1)13+2&yyNFAy./46-yyWyA^i^o^ky

KHfofkQloBu^iqbayKyAlfkdqeb@llhfkdA^fifbp)CfpefkdA^fifbp)^ka,loGbtbi`o^cqfkdA^fifbptfqefk`ob^pbobmtfqeqebHfofkQlo+QebTbbhivO^fanrbpqpdfsbobm^ptbii+>ipltb^ofkdqebfoQ^_^oatefibfkEbolf`Arkdblkptfii^iplfk`ob^pbobm+Drfab@ljmibqby
KDrfab@ljmibqb

]]
end)
