DugisGuideViewer:RegisterGuide("Knights of the Ebon Hold Reputation (80+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyJ^hbprob^ka`ljmibqbqebF`bdoltkDrfab)^pqefpdrfabfp^`lkqfkr^qflklcqebF`b`oltknrbpqp+>iilcqebpbnrbpqp^obob`ljjbkabadolrmnrbpqp)qelrde^sbovdb^oba5-jlpqifhbiv`lriaplil^iilcqebj+Fcklq)do^_^`lrmiblccofbkap+y

OWri$Ao^hyKyQo^sbiqlWri$Ao^h%0/+.)42+5&yyNFAy./6-/yyWyWri$Ao^hy
>FkPb^o`eLc>kptbopyKy@orp^aboIloaI^kqfkd^%0/+.)42+5&yyNFAy./6-/yyWyWri$Ao^hy
QFkPb^o`eLc>kptbopyKyLoabopColjAo^hror%01+6)50+6&yyNFAy./6-/yyWyWri$Ao^hy
>LoabopColjAo^hroryKyLoabopColjAo^hror%01+6)50+6&yyNFAy./550yyWyWri$Ao^hy
QLoabopColjAo^hroryKy@orp^aboIloaI^kqfkd^%0/+.)42+5&yyNFAy./550yyWyWri$Ao^hy
>QebB_lkT^q`eyKy@orp^aboIloaI^kqfkd^%0/+.)42+5&yyNFAy./551yyWyWri$Ao^hy
QQebB_lkT^q`eyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./551yyWyWri$Ao^hy

>>kFksfq^qflk)lcPloqp+++yKyQebfqbjXRkifsfkd@elhboZpq^oqpnrbpq*aolmmba_vTfqebobaQoliip^olrka%.5)4-&yyNFAy./30.yyRy0533-yyWyWri$Ao^hy
Q>kFksfq^qflk)lcPloqp+++yKyPqbc^kS^ar%.1+.)40+5&yyNFAy./30.yyWyWri$Ao^hy
>Kb^oJfppyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./304yyWyWri$Ao^hy
@Kb^oJfppyNFAy./304yyKyQ^ihql?illaolpbA^qro^%.1+0)41+-&yyWyWri$Ao^hy
QKb^oJfppyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./304yyWyWri$Ao^hy
>Vlr@^kOrk)?rqVlr@^k$qEfabyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./3/6yyWyWri$Ao^hy
@Vlr@^kOrk)?rqVlr@^k$qEfabyNFAy./3/6yyKyHfiiMrqofa>_ljfk^qflkp^kaillqqebXDllbvDelriAolliZcoljqebdolrkalcqebObifnr^ovlc>dlkv%/.+/)40+3&yyWyWri$Ao^hy
QVlr@^kOrk)?rqVlr@^k$qEfabyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./3/6yyWyWri$Ao^hy
>AobppfkdAltkyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./315yyWyWri$Ao^hy

@AobppfkdAltkyNFAy./315yyRy05366yyKyEb^aqlqebObifnr^ovlc>dlkv%/.+/)40+3&^karpbqebXBkplo`biiba@elhboZ+Q^ihqlDofpqibdrq%.6+5)42+0&ql_rvqebmi^pj^yyWyWri$Ao^hy
QAobppfkdAltkyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./315yyWyWri$Ao^hy
>Fkcfiqo^qfkdSliq^orpyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./33.yyWyWri$Ao^hy
>A^ohElofwlkyKyLsboiloaAo^hror%/4+/)13+.&+RpbqebXBkplo`biiba@elhboZ^qqebmi^qclojfkqeb`bkqboqldbqfkqlSliq^orpyyNFAy./331yyRy05366yyWyWri$Ao^hy
@A^ohElofwlkyNFAy./331yyRy05366yyKyQ^ihqlDlob_^dfkSliq^orp%/6+4)15+.&clo^ofabyyWyWri$Ao^hy
QA^ohElofwlkyKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./331yyRy05366yyWyWri$Ao^hy
QFkcfiqo^qfkdSliq^orpyKyPqbc^kS^ar%.1+.)40+5&)rpbXPqbc^k$pElokZmolsfabalrqpfabSliq^orpyyNFAy./33.yyRy1.06-yyWyWri$Ao^hy
>PlC^o)Pl?^ayKyPqbc^kS^ar%.1+.)40+5&yyNFAy./336yyWyWri$Ao^hy
>FqOliipAltkefiiyKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./340yyRy05366yyWyWri$Ao^hy
@FqOliipAltkefiiyNFAy./340yyRy06.24yyKyRpbqebXP`bmqbolcPrddbpqflkZlk^dbfpqlrqpfabSliq^orp)pbkafqqlcbq`e^`ovpq^i)obmb^q+Vlrtlk$qdbq`obafqqfiiqebdbfpqmloqprmqlSliq^orp)plalk$qdo^_^klqebolkb_bclobvlrdbq`obafq+J^hbprobvlralk$qe^sb^mbqloqebp`bmqbotlk$qtlohyyWyWri$Ao^hy
QFqOliipAltkefiiyKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./340yyRy05366yyWyWri$Ao^hy
@PlC^o)Pl?^ayNFAy./336yyRy06.21yyKyRpbqebXAfirqfkd>aafqfsbZlkqeb`^riaolkp^olrka^kvlcqebpbmlfkqp%/4+0)13+4&)%/6+/)14+.&)%0.+1)12+1&^ka%0.+3)11+/&yyWyWri$Ao^hy
QPlC^o)Pl?^ayKyPqbc^kS^ar%.1+.)40+5&yyNFAy./336yyRy1.06-yyWyWri$Ao^hy
>E^w^oalrpJ^qbof^ipyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./344yyWyWri$Ao^hy

>WbolQlibo^k`byKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./353yyRy05366yyWyWri$Ao^hy
@WbolQlibo^k`byNFAy./353yyRy06/-3yyKyRpbqebXP`bmqbolcBjmltbojbkqZlk^qoliikb^oqebmi^qcloj%0-+0)2-+5&^kae^sbqebqoliihfiiA^ojrh+Fcvlrcfdeqvlr$iiilpbvlroafpdrfpb)pllkivibqqolii^qq^`hyyWyWri$Ao^hy
QWbolQlibo^k`byKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./353yyWyWri$Ao^hy
@E^w^oalrpJ^qbof^ipyNFAy./344yyRy05366yyKyD^qebo`o^qbp^iilsboSli^qorp%/4+/)13+.&yyWyWri$Ao^hy
QE^w^oalrpJ^qbof^ipyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./344yyRy1.06-yyWyWri$Ao^hy
>P^_lq^dbyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./343yyWyWri$Ao^hy
>CrbicloqebCfobyKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./36-yyRy05366yyWyWri$Ao^hy
@CrbicloqebCfobyNFAy./36-yyRy06/05yyKyEb^aqlCofdfa?ob^`e%01+/)04+5&+RpbqebXP`bmqbolc@ljj^kaZlk^k^_ljfk^qflk+Pbkaefj^cqboqoliip)d^qeborm^pj^kv^pvlr`^k)qebk_iltefjrm)rpbqebpqljmqlhbbm^ddolyyWyWri$Ao^hy
@P^_lq^dbyNFAy./343yyRy06.32yyKyRpbqebXBumilpfsb@e^odbpZlkqebp`lrodbt^dlkp)lkqeblrqpfabp^olrkaSliq^orp%/5)12&yyWyWri$Ao^hy
QCrbicloqebCfobyKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./36-yyRy05366yyWyWri$Ao^hy
>Afp`ilprobyKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./4.-yyRy05366yyWyWri$Ao^hy
@Afp`ilprobyNFAy./4.-yyRy05366yyKyMloqrmqlqebrmmbo`e^j_borpfkdqebqbibmloq^_lsbqeblkbkloj^iivrpba)qebklmbkqeb`lccfk^kaq^hbqebqlroyyWyWri$Ao^hy
QAfp`ilprobyKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./4.-yyRy05366yyWyWri$Ao^hy
QP^_lq^dbyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./343yyRy1.06-yyWyWri$Ao^hy
>?bqo^v^iyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./4.0yyWyWri$Ao^hy
@?bqo^v^iyNFAy./4.0yyRy06331yyKyEb^arm^kaq^ihqlLsboiloaAo^hror%/4+/)13+.&qlpq^oqqefp+Fq$p^c^foivb^pv_^qqib)alk$qtloov^_lrqvlroafpdrfpbtebkfqc^fip+RpbqebXP`bmqbolcAljfk^qflkZlklkblcqeb_fdqoliip^kapbkaefj^cqboAo^hror+Tefibebcfdeqp)t^q`ecloqeb`ovpq^ipAo^hrorqeoltp^kajlsb^t^vcoljqebj^pc^pq^pvlr`^k+Fcvlroqoliiafbp)rpbqebp`bmqbo^d^fkyyWyWri$Ao^hy
RMloq_^`haltk)nrf`hivyRy10-26yyKyRpbXAo^hror$pI^pqTfpeZqlmloqaltk+Fqlkivi^pqp0jfkrqbp)pl_bnrf`h^_lrqfqyyNFAy./2-0yyWyWri$Ao^hy
Q?bqo^v^iyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./4.0yyRy1.06-yyWyWri$Ao^hy

OF`b`oltkyKyQo^sbiqlF`b`oltk%20+6)4.+2&yyNFAy.0.3.yyWyF`b`oltky
>QebOfabolcqebRkelivyKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.3.yyWyF`b`oltky
>QebOfabolcColpqyKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.3/yyWyF`b`oltky
>QebOfabolc?illayKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.30yyWyF`b`oltky
@QebOfabolcqebRkelivyKyPi^vOlhfo%22+6)5-+-&yyNFAy.0.3.yyWyF`b`oltky
@QebOfabolcColpqyKyPi^vP^mme%3.+4)35+4&yyNFAy.0.3/yyWyF`b`oltky
@QebOfabolc?illayKyPi^v?^bil`h%26+-)4.+1&yyNFAy.0.30yyWyF`b`oltky
QQebOfabolcqebRkelivyKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.3.yyWyF`b`oltky
QQebOfabolcColpqyKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.3/yyWyF`b`oltky
QQebOfabolc?illayKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.30yyWyF`b`oltky
>QebC^qblc?illa_^kbyKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.31yyWyF`b`oltky
@QebC^qblc?illa_^kbyKyPi^vLo_^w?illa_^kb%21+1)52+6&yyNFAy.0.31yyWyF`b`oltky
QQebC^qblc?illa_^kbyKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.31yyWyF`b`oltky

OLodofj$pE^jjboyKyQefpfpqebEloabPefmqe^qcifbp^olrkaF`b`oltk%33)00&)%36+2)/4+1&)%34+1)2/+2&yyWyF`b`oltky
>KlObpqCloQebTf`hbayKyHliqfo^Ab^qetb^sbolkLodofj$pE^jjboyyNFAy.0034yyWyF`b`oltky
@KlObpqCloQebTf`hbayKyPi^v>irjbqeqeb>p`bkaba%2.+6)/6+-&yyNFAy.0034yyWyF`b`oltky
OLodofj$pE^jjboyKyQefpfpqebEloabPefmqe^qcifbp^olrkaF`b`oltk%33)00&)%36+2)/4+1&)%34+1)2/+2&yyWyF`b`oltky
QKlObpqCloQebTf`hbayKyHliqfo^Ab^qetb^sbolkLodofj$pE^jjboyyNFAy.0034yyWyF`b`oltky
>QebFolkt^iiO^jm^oqyKyHliqfo^Ab^qetb^sbolkLodofj$pE^jjboyyNFAy.00./yyWyF`b`oltky
@QebFolkt^iiO^jm^oqyKyAbcb^qDofjhloqebTf`hba%12+1)13+/&yyNFAy.00./yyWyF`b`oltky
OLodofj$pE^jjboyKyQefpfpqebEloabPefmqe^qcifbp^olrkaF`b`oltk%33)00&)%36+2)/4+1&)%34+1)2/+2&yyWyF`b`oltky
QQebFolkt^iiO^jm^oqyKyHliqfo^Ab^qetb^sbolkLodofj$pE^jjboyyNFAy.00./yyWyF`b`oltky
>Pe^qqboqebPe^oapyKyHliqfo^Ab^qetb^sbolkLodofj$pE^jjboyyNFAy.00/5yyWyF`b`oltky
>QebDr^oaf^kplc@lom$obqe^oyKyHliqfo^Ab^qetb^sbolkLodofj$pE^jjboyyNFAy.00.3yyWyF`b`oltky
@Pe^qqboqebPe^oapyKy?ofkdqeb?olhbkPe^oalcEloolo)qeb?olhbkPe^oalcAbpm^fo)^kaqeb?olhbkPe^oalcPrccbofkdqlHliqfo^Ab^qetb^sbo^_l^oaLodofj$pE^jjbo+%16+4)33+3&%14+2)35+.&%15+4)36+4&yyNFAy.00/5yyWyF`b`oltky
@QebDr^oaf^kplc@lom$obqe^oyKyHfii2E^o_fkdboplcEloolo^ka2@lom$obqe^oDr^oaf^kp%16+-)34+0&yyNFAy.00.3yyWyF`b`oltky
OLodofj$pE^jjboyKyQefpfpqebEloabPefmqe^qcifbp^olrkaF`b`oltk%33)00&)%36+2)/4+1&)%34+1)2/+2&yyWyF`b`oltky
QPe^qqboqebPe^oapyKyHliqfo^Ab^qetb^sbolkLodofj$pE^jjboyyNFAy.00/5yyWyF`b`oltky
QQebDr^oaf^kplc@lom$obqe^oyKyHliqfo^Ab^qetb^sbolkLodofj$pE^jjboyyNFAy.00.3yyWyF`b`oltky

>QebDo^ka%>ajfo^i$p&Mi^kyKyQebfqbjXKlqbcoljqebDo^ka>ajfo^iZpq^oqpnrbpq*aolmmba_vLkpi^rdeqO^sbk?fpelm^kaLkpi^rdeqE^o_loDr^oap^olrka%6)10&yyRy1-333yyNFAy./506yyWyF`b`oltky
QQebDo^ka%>ajfo^i$p&Mi^kyNFAy./506yyKyIloa*@ljj^kabo>obqb%.6+3)15+.&yyWyF`b`oltky
>FkPqof`q@lkcfabk`byNFAy./51-yyKyIloa*@ljj^kabo>obqb%.6+3)15+.&yyWyF`b`oltky
@FkPqof`q@lkcfabk`byKyHfii@^mq^fkTbipfkdqlkfp^q%2+4)1.+6&^ka@^mq^fkE^oqcloafp^q%4)1.+6&lkqeb_l^qpyyNFAy./51-yyWyF`b`oltky
QFkPqof`q@lkcfabk`byNFAy./51-yyKyIloa*@ljj^kabo>obqb%.6+3)15+.&yyWyF`b`oltky
>Pb`lka@e^k`bpyKyIloa*@ljj^kabo>obqb%.6+3)15+.&+Qefpfp^dolrmnrbpq)p^sbfqfk`^pbvlrcfka^dolrmqlalqefptfqeyyNFAy./514yyWyF`b`oltky
@Pb`lka@e^k`bpyKyHfii>o`e_fpelmI^kadobk^kaqebkprjjlk>obqb$pD^qb%6+2)14+-&yyRy1-40-yyNFAy./514yyWyF`b`oltky
QPb`lka@e^k`bpyKyIloa*@ljj^kabo>obqb+Rpb>obqb$pD^qbqlq^ihqlefj+yyNFAy./514yyWyF`b`oltky
>Qeb>ajfo^iObsb^ibayKyIloa*@ljj^kabo>obqb+Rpb>obqb$pD^qbqlq^ihqlefj+yyNFAy./52/yyWyF`b`oltky
@Qeb>ajfo^iObsb^ibayKyRpbXIloa*@ljj^kabo$pKriifcfboZlkqebpefbiaqe^qDo^ka>ajfo^iTbpqtfkamrqprm+yyRy1-6.4yyNFAy./52/yyWyF`b`oltky
QQeb>ajfo^iObsb^ibayKyIloa*@ljj^kabo>obqb%.6+3)15+.&yyNFAy./52/yyWyF`b`oltky

KB_lk?i^abA^fifbpyKy@lkqfkrbtfqea^fifbprkqfibu^iqba+Drfab@ljmibqb+y
KDrfab@ljmibqb

]]
end)
