DugisGuideViewer:RegisterGuide("The Mag'har Reputation (50+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabtfiidllsbo^iiqebnrbpqpkbbabaqldbqqebAfmilj^q>`efbsbjbkq%Bu^iqbatfqeQfj_boj^t)J^d$e^o^kaPmlobdd^o+Lk`b^iiqebnrbpqp^obalkbclo^m^oqf`ri^oc^`qflk)qebkfpgrpqdofkafkdlrqqebobmb^q^_ibarkdblkp,qrok*fkpqldbqqlBu^iqba+Qefpdrfab^pprjbpqe^qvlr^obibsbi5-)_rqqefp`^k_balkb^qibsbi4-^ptbii)fqtfiigrpqq^hbjr`eilkdboql`ljmibqb+y
KIltIbsbiNrbpqpyKyJ^hbprobvlr^obqo^hfkdiltibsbinrbpqpqlj^hbfqb^pfboqlpbbqebnrbpqpdfsbop+y

OQeo^iij^oyKyQo^sbiqlQeo^iij^o%22)03&yyWyEbiicfobMbkfkpri^y
>Qeb>pp^ppfkyNFAy61--yyKyK^wdobi%22+-)03+-&yyWyEbiicfobMbkfkpri^y
QQeb>pp^ppfkyKyHorkPmfkb_ob^hbo$p`lompbqlqebkloqe%00+3)10+3&yyNFAy61--yyWyEbiicfobMbkfkpri^y
>>Pqo^kdbTb^mlkyKyCbiLo`@lompb%00+3)10+3&yyNFAy61-.yyWyEbiicfobMbkfkpri^y
Q>Pqo^kdbTb^mlkyKyK^wdobi%22+-)03+-&yyNFAy61-.yyWyEbiicfobMbkfkpri^y
>QebT^o`efbc$pJ^ka^qbyKyK^wdobi%22+-)03+-&yyNFAy61-2yyWyEbiicfobMbkfkpri^y
QQebT^o`efbc$pJ^ka^qbyKyC^oPbboObdrihrq%21+0)04+6&yyNFAy61-2yyWyEbiicfobMbkfkpri^y
>>PmfofqDrfabyKyC^oPbboObdrihrq%21+0)04+6&yyNFAy61.-yyWyEbiicfobMbkfkpri^y
@>PmfofqDrfabyKyRpbqebX>k`bpqo^iPmfofqTlicQlqbjZ^qHorkPmfkb_ob^hbo$p`lompb%00+3)10+3&)^kacliiltqebtlicyyNFAy61.-yyRy/0336yyWyEbiicfobMbkfkpri^y
Q>PmfofqDrfabyKyDloh^k?illacfpq%0/+.)/4+5&yyNFAy61.-yyWyEbiicfobMbkfkpri^y
>QebJ^d$e^oyKyDloh^k?illacfpq%0/+.)/4+5&yyNFAy61-3yyWyEbiicfobMbkfkpri^y
QQebJ^d$e^oyKyK^wdobi%22+-)03+-&yyNFAy61-3yyWyEbiicfobMbkfkpri^y
>JbppbkdboqlQeo^iiyKyK^wdobi%22+-)03+-&yyNFAy6105yyWyEbiicfobMbkfkpri^y

CPe^qqo^qe@fqvyKy%/6+2)//+6&yyWyQbolhh^oClobpqy
OLodofjj^oyKyQ^hbqebmloq^iqlLodofjj^o%2/+/)2/+6&yyWyPe^qqo^qe@fqvy
QJbppbkdboqlQeo^iiyWyLodofjj^oyyKyQeo^ii)S^iibvlcTfpalj%0/+-)04+5&yyNFAy6105y
>BkslvqlqebJ^d$e^oyWyLodofjj^oyyKyQeo^ii)S^iibvlcTfpalj%0/+-)04+5&yyNFAy611.y
EA^i^o^kyRy3615y
OPe^qqo^qe@fqvyKyQ^hbmloq^i%23+0)//+1&fkA^i^o^kqlPe^qqo^qe@fqvyyWyA^i^o^ky
OEbiicfobMbkfkpri^yKyQo^sbiqlEbiicfobMbkfkpri^%0/+.)/4+5&yyWyEbiicfobMbkfkpri^y
QBkslvqlqebJ^d$e^oyWyEbiicfobMbkfkpri^yyKyDloh^k?illacfpq%0/+.)/4+5&yyNFAy611.y
>>Ab_fifq^qfkdPf`hkbppyWyEbiicfobMbkfkpri^yyKyB^oqe`^iiboOvd^%0/+.)/5+0&yyNFAy611/y
@>Ab_fifq^qfkdPf`hkbppyWyEbiicfobMbkfkpri^yyKyDbqqebXAov`^mJrpeolljZfkqeb`^sb^qqebCfpprob%01)31&yyNFAy611/y
Q>Ab_fifq^qfkdPf`hkbppyWyEbiicfobMbkfkpri^yyKyB^oqe`^iiboOvd^%0/+.)/5+0&yyNFAy611/y
>>ajfkfpqbofkdqebP^isbyWyEbiicfobMbkfkpri^yyKyB^oqe`^iiboOvd^%0/+.)/5+0&yyNFAy6114y
@>ajfkfpqbofkdqebP^isbyWyEbiicfobMbkfkpri^yyKyRpbqebXEb^ifkdP^isbZlk.-Ab_fifq^qbaDorkqpfkJ^d$e^o%0-)0-&yyRy/0061yyNFAy6114y
Q>ajfkfpqbofkdqebP^isbyWyEbiicfobMbkfkpri^yyKyB^oqe`^iiboOvd^%0/+.)/5+0&yyNFAy6114y

OD^o^a^oyKyQo^sbiqlD^o^a^o%24+/)02+0&yyWyK^do^kay

>JfppfkdJ^d$e^ofMol`bppflkyKyJ^qolkAo^hf^%23+3)01+0&yyNFAy6611yyWyK^do^kay
>QebQeolkblcqebBibjbkqpyKyBibjbkq^ifpqV^i$e^e%22)04&yyNFAy654-yyWyK^do^kay
>QebFjmlqbkqIb^aboyKyGlofkAb^abvb%22+3)04+3&yyNFAy6555yyWyK^do^kay
>SfibFali^qovyKyC^opbboHrohrpe%21+5)06+1&yyNFAy6530yyWyK^do^kay
>QebJfppfkdT^oM^oqvyKyC^opbbo@loerh%21+5)06+5&yyNFAy6531yyWyK^do^kay
>Jroh_illaIb^abop+++yKyC^opbboJ^od^abpe%21+3)06+6&yyNFAy6534yyWyK^do^kay
>T^kqba7Dfpbia^qeb@olkbyKyD^o^a^o?riibqfk?l^oa%22+4)04+6&yyNFAy6602yyWyK^do^kay
>T^kqba7Wlo_lqeb>asfployKyD^o^a^o?riibqfk?l^oa%22+4)04+6&yyNFAy6606yyWyK^do^kay
>MolsfkdVlroPqobkdqeyKyT^oabk?riiolh%22+5)04+6&yyNFAy.-146yyWyK^do^kay
>Eb@^iibaEfjpbic>iqorfp+++yKyJ^qolk@bibpqfkb%22+/)03+/&yyNFAy6650yyWyK^do^kay

OQbolhh^oClobpqyKyDlsf^qebplrqeb^pqm^qe%50)55&yyNFAy6556yyWyK^do^kay
QQebFjmlqbkqIb^aboyKyHfio^qe%.6+5)3-+5&yyWyQbolhh^oClobpqyyNFAy6555y
>Alk$qHfiiqebC^qLkbyKyHfio^qe%.6+5)3-+5&yyWyQbolhh^oClobpqyyNFAy6556y
@Alk$qHfiiqebC^qLkbyKyHfii.-?lriabocfpqFks^abop^olrka%.6)30&^kaqebk_b^qRkhloqebOrqeibpp^q%/-)3/&yyWyQbolhh^oClobpqyyNFAy6556y
QAlk$qHfiiqebC^qLkbyKyRkhloqebOrqeibpp%/-)3/&yyWyQbolhh^oClobpqyyNFAy6556y
>Pr``bppyKyRkhloqebOrqeibpp%/-)3/&yyWyQbolhh^oClobpqyyNFAy656-y
QPr``bppyKyHfio^qe%.6+5)3-+5&yyWyQbolhh^oClobpqyyNFAy656-y
>?b`^rpbHfio^qefp^@lt^oayKyHfio^qe%.6+5)3-+5&yyWyQbolhh^oClobpqyyNFAy656.y

OD^o^a^oyKyQo^sbiqlD^o^a^o%24+/)02+0&yyWyK^do^kay
Q?b`^rpbHfio^qefp^@lt^oayKyGlofkAb^abvb%22+3)04+3&yyNFAy656.yyWyK^do^kay
>Jbpp^dbfk^?^qqibyKyGlofkAb^abvb%22+3)04+3&yyNFAy66-3yyWyK^do^kay
>Pq^ka^oap^kaMo^`qf`bpyKyBih^v$d^kqebJvpqf`%22+4)04+3&yyNFAy66.-yyWyK^do^kay

KObmrq^qflkqlhbkp+++yKyHbbm^kvXL_pfaf^kT^o_b^apZcoljqebldobpfkqebwlkb`^k_bqrokbafkcloJ^d$e^olo@lkploqfrjobmyyNFAy66-3y
@Jbpp^dbfk^?^qqibyKyHfii5?lriabocfpq@orpebop^ka5?lriabocfpqJvpqf`p^olrka%4/)36&yyNFAy66-3yyWyK^do^kay
@Pq^ka^oap^kaMo^`qf`bpyKyMvob.%4/)36&)Mvob/%41)4-&^kaMvob0%42)35&+Qebpbmvobpillhgrpqifhb_fd`^jmcfobp)mi^`bqebXJ^d$e^o?^qqibPq^ka^oaZkbuqqlqebjqldbq`obafqyyNFAy66.-yyRy/2125yyWyK^do^kay

QJbpp^dbfk^?^qqibyKyGlofkAb^abvb%22+3)04+3&yyNFAy66-3yyWyK^do^kay
QPq^ka^oap^kaMo^`qf`bpyKyBih^v$d^kqebJvpqf`%22+4)04+3&yyNFAy66.-yyWyK^do^kay
>>k>ra^`flrp>as^k`byKyGlofkAb^abvb%22+3)04+3&yyNFAy66-4yyWyK^do^kay
>?ibbafkdEliiltPrmmiv@o^qbpyKyBih^v$d^kqebJvpqf`%22+4)04+3&yyNFAy66.3yyWyK^do^kay

@>k>ra^`flrp>as^k`byKyHfii.-?lriabocfpqT^ooflop^ka.-?lriabocfpqJ^dbp^q%2-)23&lo%1-)0/&yyNFAy66-4yyWyK^do^kay
@?ibbafkdEliiltPrmmiv@o^qbpyKyOb`lsbo.-X?ibbafkdEliiltPrmmiv@o^qbpZ+Qebv$obmi^`ba^iilsboqeb`^sbpfkKloqetfka,Plrqetfka@ibcqp%1-)0-&yyNFAy66.3yyWyK^do^kay
OJ^d$e^ofMol`bppflkyKyQo^sbiqlJ^d$e^ofMol`bppflk%0/)03&yyNFAy6532yyWyK^do^kay
QQebJfppfkdT^oM^oqvyKyP^roc^kdqebVlrkdbo%0/+2)03+.&yyNFAy6531yyWyK^do^kay
>Lk`bTbobT^ooflopyKyP^roc^kdqebVlrkdbo%0/+2)03+.&yyNFAy6532yyWyK^do^kay
QJfppfkdJ^d$e^ofMol`bppflkyKyBiaboVloibv%0/+0)03+/&yyNFAy6611yyWyK^do^kay
>T^olkqebT^oj^riyKyBiaboVloibv%0/+0)03+/&yyNFAy6612yyWyK^do^kay
>CfkafkdqebProsfslopyKyBiaboRkdofw%0/+1)03+/&yyNFAy6615yyWyK^do^kay

QEb@^iibaEfjpbic>iqorfp+++yKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy6650yyWyK^do^kay
>ProsbvqebI^kayKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy666.yyWyK^do^kay
@ProsbvqebI^kayKyQ^ihql>iqorfpqebPrccbobo%/4+1)10+.&^kaq^hb^ofabtfqeqebao^dlkyyNFAy666.yyWyK^do^kay
QProsbvqebI^kayKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy666.yyWyK^do^kay
>?rvfkdQfjbyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy6666yyWyK^do^kay
@?rvfkdQfjbyKyHfii/Cbidr^oaIbdflkk^fobp)0Jl$^odBkdfkbbop^ka5D^k$^odQfkhbobop+%/0+2)05+/&%/.+6)1/+1&yyNFAy6666yyWyK^do^kay
Q?rvfkdQfjbyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy6666yyWyK^do^kay
>QebJ^pqboMi^kkboyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.---.yyWyK^do^kay
@QebJ^pqboMi^kkboyKyob`lsboqebJ^pqboMi^kkbo$p?irbmofkqp%/0+1)01+3&%.4+1)2-+/&+yyNFAy.---.yWyK^do^kay
QQebJ^pqboMi^kkboyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.---.yyWyK^do^kay
>M^qfbk`b^kaRkabopq^kafkdyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.---1yyWyK^do^kay

@CfkafkdqebProsfslopyKyCobb2J^d$e^oMofplkbop^q%/3)/1&+HfiiqebLdobpqldbq^hbvqllmbkqeb`^dbp)vlrtfiikbba^hbvclob^`e`^dbyyNFAy6615yyWyK^do^kay
@T^olkqebT^oj^riyKyHfii5T^oj^ri?orqbp^ka5T^oj^riT^oil`hp^olrka%/2)/3&yyNFAy6612yyWyK^do^kay

OD^o^a^oyKyQo^sbiqlD^o^a^o%24+/)02+0&yyWyK^do^kay
Q>k>ra^`flrp>as^k`byKyGlofkAb^abvb%22+3)04+3&yyNFAy66-4yyWyK^do^kay
Q?ibbafkdEliiltPrmmiv@o^qbpyKyBih^v$d^kqebJvpqf`%22+4)04+3&yyNFAy66.3yyWyK^do^kay
>Afmilj^qf`Jb^probpyKyGlofkAb^abvb%22+3)04+3&yyNFAy.-.-4yyWyK^do^kay

QAfmilj^qf`Jb^probpyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy.-.-4yyWyK^do^kay
>>oj^jbkqpcloAb`bmqflkyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy66/5yyWyK^do^kay
>Orqeibpp@rkkfkdyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy66/4yyWyK^do^kay

@T^kqba7Dfpbia^qeb@olkbyKyHfiiDfpbia^qeb@olkbfkpfabqebi^odb_rfiafkd%4.+1)5/+0&^ka^kv`lj_fk^qflklc.2Hfi$ploolt>dbkqp+J^hbprobqlmi^kqXT^oj^riLdob?^kkbopZlkqebjl_pvlrhfiicloqebnrbpqOrqeibpp@rkkfkdyyRy/222/yyNFAy6602yyWyK^do^kay
@>oj^jbkqpcloAb`bmqflkyKy@liib`q.-XHfi$ploolt>oj^jbkqpZtef`e^obpj^iiob`q^kdri^o_lubp+Qebobfp^qltbo^q%36)44&)dlrmqlqebqlm^kado^__lubp^ilkdqebt^v^ka_vqebqfjbvlrdbqaltkqeblkbplkqeb_lqqljpelriae^sbobpm^tkbayyRy/222/yyNFAy66/5yyWyK^do^kay
@Orqeibpp@rkkfkdyKyMi^`b.-XT^oj^riLdob?^kkbopZlk^kvab^aHfi$plooltjl_p%4-)5-&yyRy/222/yyNFAy66/4yyWyK^do^kay

QOrqeibpp@rkkfkdyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy66/4yyWyK^do^kay
Q>oj^jbkqpcloAb`bmqflkyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy66/5yyWyK^do^kay
>ObqrokfkdqebC^sloyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy660.yyWyK^do^kay
>?lavlcBsfabk`byKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy660/yyWyK^do^kay

OPe^qqo^qe@fqvyKyQo^sbiqlPe^qqo^qe@fqv%20)11&yyWyPe^qqo^qe@fqvy
QM^qfbk`b^kaRkabopq^kafkdyKyP^i$p^i^_fj%44+/)01+4&+Vlrtfiikbbaqlabcb^qefjqlqrokfknrbpq+yyNFAy.---1yyWyPe^qqo^qe@fqvy
>@o^`hfk$PljbPhriipyKyP^i$p^i^_fj%44+/)01+4&+yyNFAy.---6yyWyPe^qqo^qe@fqvy
HO^ifnqebAorkhyKyAbcb^qO^ifnqebAorkh%42+-)0.+4&cloefpab_q+yyNFAy.---6yyIy/2434yyWyPe^qqo^qe@fqvy
OQbolhh^oClobpqyKyQo^sbiqlQbolhh^oClobpq%/4+1)25+-&yyNFAy.--.-yyWyQbolhh^oClobpqy
HCillkyKyAbcb^qCillk%/4+1)25+-&cloefpab_q+yyNFAy.---6yyIy/2436yyWyQbolhh^oClobpqy
@@o^`hfk$PljbPhriipyKyAbcb^q@llpe$`llpe%5.)6.&cloefpab_q+yyNFAy.---6yyWyW^kd^oj^opey
Q@o^`hfk$PljbPhriipyKyP^i$p^i^_fj%44+/)01+4&+yyNFAy.---6yyWyPe^qqo^qe@fqvy
>Fq$pGrpqQe^qB^pv<yKyP^i$p^i^_fj%44+/)01+4&+yyNFAy.--.-yyWyPe^qqo^qe@fqvy

OD^o^a^oyKyQo^sbiqlD^o^a^o%24+/)02+0&yyWyK^do^kay
QT^kqba7Dfpbia^qeb@olkbyKyT^oabk?riiolh%22+5)04+6&yyNFAy6602yyWyK^do^kay

QQebQeolkblcqebBibjbkqpyKyBibjbkq^ifpqPe^os^h%3-+3)//+/&yyNFAy654-yyWyK^do^kay

@?lavlcBsfabk`byRy/2325yyKyRpbqebXA^jmTllibk?i^khbqZlkqebmvobfkqebI^rdefkdPhrii@lroqv^oa%14)/1&+Ldobptfiipm^tk^kaqebvtfiipq^oqmi^`fkdlo``lompbp^olrkaqebmvob)vlrjrpqmolqb`qqebjtefibqebvalfq)^kaalk$qclodbqqlpqf`h_^kkbopfkqebjl_pvlrhfiiyyNFAy660/yyWyK^do^kay
@T^kqba7Wlo_lqeb>asfployKyHfiiWlo_lqeb>asfplo^qqeb`^sb%13+1).5+1&^ka2T^oj^riPe^j^k^ka2T^oj^riOb^sbop^olrka%13)/.&+Objbj_boqlhbbmmi^kqfkd_^kkbopyyRy/2222yyNFAy6606yyWyK^do^kay
@ObqrokfkdqebC^sloyKyMi^`b.-XHfi$ploolt?^kkbopZqeolrdeqeb_lafbplcT^oj^rildobp^olrka%13).5&yyRy/2222yyNFAy660.yyWyK^do^kay

QFq$pGrpqQe^qB^pv<yKy>iqorfpqebPrccbobo%/4+1)10+.&+yyNFAy.--.-yyWyK^do^kay
>Clodb@^jm7>kkfefi^qbayKy>iqorfpqebPrccbobo%/4+1)10+.&+yyNFAy.--..yyWyK^do^kay
@Clodb@^jm7>kkfefi^qbayKyAbpqolvClodb@^jm7E^qb%/2+-)03+.&^kaAbpqolvClodb@^jm7Cb^o%.6+1)2.+-&+yyNFAy.--..yyWyK^do^kay
QClodb@^jm7>kkfefi^qbayKy>iqorfpqebPrccbobo%/4+1)10+.&+yyNFAy.--..yyWyK^do^kay

QObqrokfkdqebC^sloyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy660.yyWyK^do^kay
Q?lavlcBsfabk`byKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy660/yyWyK^do^kay
>Jbpp^dbqlD^o^a^oyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy6601yyWyK^do^kay

OD^o^a^oyKyQo^sbiqlD^o^a^o%24+/)02+0&yyWyK^do^kay
QJbpp^dbqlD^o^a^oyKyD^oolpe%22)05&yyNFAy6601yyWyK^do^kay
QT^kqba7Wlo_lqeb>asfployKyT^oabk?riiolh%22+5)04+6&yyNFAy6606yyWyK^do^kay
>T^kqba7ArokqebErkdboboyKyT^oabk?riiolh%22+5)04+6&yyNFAy6604yyWyK^do^kay

HJroh_illaFks^abopyKyHfiiJroh_illaFks^abopm^qoliifkdqebol^a_bqtbbk%1/)25+4&^ka%/5+2)24+.&qldbqfqbjXJroh_illaFks^pflkMi^kpZqlpq^oqkbtnrbpqyyIy/1226yyNFAy654.yyWyK^do^kay
>Jroh_illaFks^abopyKyRpbqebXJroh_illaFks^pflkMi^kpZql^``bmqnrbpqyyRy/1226yyNFAy654.yyWyK^do^kay

@SfibFali^qovyKyDbq/-XJroh_illaFalipZ^qPrkpmofkdMlpq%0/)12&yyNFAy6530yyWyK^do^kay
@Jroh_illaIb^abop+++yKyHfiiLoqlolcJroh_illa^q%0-)1/&fk^_fderqyyNFAy6534yyWyK^do^kay
@Lk`bTbobT^ooflopyKyHfii/-Jroh_illaP`^sbkdbop^ka/-Jroh_illaO^fabop^olrka%0.)1/&yyNFAy6532yyWyK^do^kay
@Jroh_illa@loormqbopyKyHfii2Jroh_illaMrqofcfbop^olrka%0-)1-&yyNFAy653/yyWyK^do^kay
>QebQlqbjlcH^o$a^peyKyHrobk^f@^mqfsb%00)1/&yyNFAy6535yyWyK^do^kay
@QebQlqbjlcH^o$a^peyKyBp`loqqebHrobk^f@^mqfsbyyNFAy6535yyWyK^do^kay

QT^olkqebT^oj^riyKyBiaboVloibv%0/+0)03+/&yyNFAy6612yyWyK^do^kay
>@el$t^oqebMfii^dboyKyBiaboVloibv%0/+0)03+/&yyNFAy6613yyWyK^do^kay
QCfkafkdqebProsfslopyKyBiaboRkdofw%0/+1)03+/&yyNFAy6615yyWyK^do^kay
QLk`bTbobT^ooflopyKyP^roc^kdqebVlrkdbo%0/+2)03+.&yyNFAy6532yyWyK^do^kay
>EbTfiiT^ihQebB^oqe+++yKyP^roc^kdqebVlrkdbo%0/+2)03+.&yyNFAy6533yyWyK^do^kay

@@el$t^oqebMfii^dboyKyPi^v@el$t^oqebMfii^dbo%/3+-).0+6&yyNFAy6613yyWyK^do^kay
Q@el$t^oqebMfii^dboyKyBiaboVloibv%0/+0)03+/&yyNFAy6613yyWyK^do^kay

OD^o^a^oyKyQo^sbiqlD^o^a^o%24+/)02+0&yyWyK^do^kay
QQebQlqbjlcH^o$a^peyKyD^oolpe%22)05&yyNFAy6535yyWyK^do^kay
QJroh_illaFks^abopyKyD^oolpe%22)05&yyNFAy654.yyWyK^do^kay
QSfibFali^qovyKyC^opbboHrohrpe%21+5)06+1&yyNFAy6530yyWyK^do^kay
QJroh_illaIb^abop+++yKyC^opbboJ^od^abpe%21+3)06+6&yyNFAy6534yyWyK^do^kay
QEbTfiiT^ihQebB^oqe+++yKyC^opbbo@loerh%21+5)06+5&yyNFAy6533yyWyK^do^kay

>>SfpfqTfqeqebDob^qjlqeboyKyD^oolpe%22+2)04+4&yyNFAy.--11yyWyK^do^kay
@>SfpfqTfqeqebDob^qjlqeboyKyQ^ihqlDob^qjlqeboDbv^erkqfinrbpq`ljmibqba+yyNFAy.--11yyWyK^do^kay
Q>SfpfqTfqeqebDob^qjlqeboyKyDob^qjlqeboDbv^e%23+2)01+0&yyNFAy.--11yyWyK^do^kay
>J^qbof^i@ljmlkbkqpyKyDob^qjlqeboDbv^e%23+2)01+0&yyNFAy.--12yyWyK^do^kay
KQbi^^ofColkayKyD^qeboQbi^^ofColka%3/+0)22+4&+yyIy/2531yyNFAy.--12yyWyK^do^kay
KLibj_^yKyD^qeboLibj_^%04+.)01+/&+yyIy/2530yyNFAy.--12yyWyQbolhh^oClobpqy
KAo^dlkpmfkbyKyD^qeboAo^dlkpmfkb%06+0)43+.&+yyIy/2532yyNFAy.--12yyWy?i^ab$pBadbJlrkq^fkpy
@J^qbof^i@ljmlkbkqpyKyD^qeboJ^ope_boov%/-+/)5+2&+yyIy/253/yyNFAy.--12yyWyW^kd^oj^opey
QJ^qbof^i@ljmlkbkqpyKyDob^qjlqeboDbv^e%23+2)01+0&yyNFAy.--12yyWyK^do^kay
>QlJbbqJlqeboH^peroyKyDob^qjlqeboDbv^e%23+2)01+0&yyNFAy.--5.yyWyK^do^kay
QQlJbbqJlqeboH^peroyKyJlqeboH^pero%/3+.)3-+3&yyNFAy.--5.yyWyK^do^kay
>Qeb>dfq^qba>k`bpqlopyKyJlqeboH^pero%/3+.)3-+3&yyNFAy.--5/yyWyK^do^kay
@Qeb>dfq^qba>k`bpqlopyKyMrqqlobpq5>dfq^qbaLo`Pmfofqp+%/3+.)3-+3&yyNFAy.--5/yyWyK^do^kay
QQeb>dfq^qba>k`bpqlopyKyJlqeboH^pero%/3+.)3-+3&yyNFAy.--5/yyWyK^do^kay
>>SfpfqTfqeQeb>k`bpqlopyKyJlqeboH^pero%/3+.)3-+3&yyNFAy.--52yyWyK^do^kay
KPrkpmofkdMlpqyKy%0/+.)1/+0&Pq^vilkdbklrdecloqebnrbpq@ofqbof^ql`ljmibqb+yyNFAy.--52yyNLySfpfqPrkpmofkdMlpq7.,.yyWyK^do^kay
KI^rdefkdPhriiOrfkpyKy%12+1)/0+0&Pq^vilkdbklrdecloqebnrbpq@ofqbof^ql`ljmibqb+yyNFAy.--52yyNLySfpfqI^rdefkdPhrii@i^kOrfkp7.,.yyWyK^do^kay
KD^o^a^oyKy%21+2)03+0&Pq^vilkdbklrdecloqebnrbpq@ofqbof^ql`ljmibqb+yyNFAy.--52yyNLySfpfqD^o^a^o7.,.yyWyK^do^kay
@>SfpfqTfqeQeb>k`bpqlopyKySfpfq?ibbafkdEliilt@i^kOrfkp%.6+2)31+/&Pq^vilkdbklrdecloqebnrbpq@ofqbof^ql`ljmibqb+yyNFAy.--52yyWyQbolhh^oClobpqy
Q>SfpfqTfqeQeb>k`bpqlopyKyJlqeboH^pero%/3+.)3-+3&yyNFAy.--52yyWyK^do^kay
>TebkPmfofqpPmb^hyKyJlqeboH^pero%/3+.)3-+3&yyNFAy.-.-.yyWyK^do^kay
@T^kqba7ArokqebErkdboboyKy%12+/)3/+3&%06+2)45+/&%0-+1)35+3&%0/+/)3.+5&yyNFAy6604yyWyK^do^kay
QTebkPmfofqpPmb^hyKyH$rob%02+2)44+4&VlrtfiicfkaH$robfkpfabLper$drk+yyNFAy.-.-.yyWyK^do^kay
>>Pb`obqObsb^ibayKyH$rob%02+2)44+4&yyNFAy.-.-/yyWyK^do^kay
Q>Pb`obqObsb^ibayKy>$a^i%21+3)12+-&yyNFAy.-.-/yyWyPe^qqo^qe@fqvy
>>r`efkalrk+++yKy>$a^i%21+3)12+-&yyNFAy.-.34yyWyPe^qqo^qe@fqvy
O>r`ebk^f@ovmqpyKy%02+0)32+3&yyWyQbolhh^oClobpqy
HBu^o`eJ^i^a^^oyKyPi^vBu^o`eJ^i^a^^oqlcobbqebpmfofqlcA$lob+Eb`^k_bclrkafk>r`ebk^f@ovmqp+yyNFAy.-.34yyWyQbolhh^oClobpqy
Q>r`efkalrk+++yKyA$lobyyNFAy.-.34y
>Te^qqebPlriPbbpyKyA$lobyyNFAy.-.35y
KDbq^XPlriJfooloZyKyQebpb^obmromib`ovpq^ifqbjpclrkafk>r`ebk^f@ovmqp+yyIy/5/50y
OK^do^ka
@Te^qqebPlriPbbpyKyRpb^PlriJfoololk>k`fbkqLo`>k`bpqlop%02+4)3.+1&%22+5)02+4&ql`^iicloqe^A^ohbkbaPmfofq^kapi^vqebpmfofq+Kbbaqlpi^v.2A^ohbkbaPmfofqp+yyRy/5/50yyNFAy.-.35yyWyK^do^kay
QTe^qqebPlriPbbpyKyJlqeboH^pero%/3+.)3-+3&yyNFAy.-.35yyWyK^do^kay
>ObqrokqlqebDob^qjlqeboyKyJlqeboH^pero%/3+.)3-+3&yyNFAy.-.4-yyWyK^do^kay
QT^kqba7ArokqebErkdboboyKyT^oabk?riiolh%22+5)04+6&yyNFAy6604yyWyK^do^kay
@MolsfkdVlroPqobkdqeyKyJ^hbprobvlre^sb.-uXL_pfaf^kT^o_b^apZ)qebvaolmlccqebLdob$pfkK^do^ka+yyNFAy.-146yyWyK^do^kay
QMolsfkdVlroPqobkdqeyKyT^oabk?riiolh%22+5)04+6&yyNFAy.-146yyWyK^do^kay
QObqrokqlqebDob^qjlqeboyKyDob^qjlqeboDbv^e%23+2)01+0&yyNFAy.-.4-yyWyK^do^kay
>QebFk`lkpli^_ib@efbcq^fkyKyDob^qjlqeboDbv^e%23+2)01+0&yyNFAy.-.4.yyWyK^do^kay
QQebFk`lkpli^_ib@efbcq^fkyKyD^oolpe%22+2)04+4&yyNFAy.-.4.yyWyK^do^kay
>QebobFpKlElmbyKyD^oolpe%22+2)04+4&yyNFAy.-.4/yyWyK^do^kay
@QebobFpKlElmbyKyPmb^htfqeDob^qjlqeboDbv^erkqfiqebnrbpqfp`ljmibqba+yyNFAy.-.4/yyWyK^do^kay
QQebobFpKlElmbyKyDob^qjlqeboDbv^e%23+2)01+0&yyNFAy.-.4/yyWyK^do^kay
>Qeo^ii)PlklcArolq^kyKyDob^qjlqeboDbv^e%23+2)01+0&yyNFAy.-.42yyWyK^do^kay

CPe^qqo^qe@fqvyKyQo^sbiqlPe^qqo^qe@fqv%/6+2)//+6&yyWyQbolhh^oClobpqy
OLodofjj^oyKyQ^hbqebmloq^iqlLodofjj^o%2/+/)2/+6&yyWyPe^qqo^qe@fqvy

QQeo^ii)PlklcArolq^kyKyQeo^ii%0.+6)04+5&yyNFAy.-.42yyWyLodofjj^oy
>EbollcqebJ^d$e^oyKyQeo^ii%0.+6)04+5&yyNFAy.-/./yyWyLodofjj^oy

EA^i^o^kyRy3615y
OPe^qqo^qe@fqvyKyQ^hbmloq^i%23+0)//+1&fkA^i^o^kqlPe^qqo^qe@fqvyyWyA^i^o^ky
OD^o^a^oyKyQo^sbiqlD^o^a^o%24+/)02+0&yyWyK^do^kay
QEbollcqebJ^d$e^oyKyDob^qjlqeboDbv^e%23+2)01+0&yyNFAy.-/./yyWyK^do^kay

KJ^d$e^oObmyKy@lkqfkrbHfiifkdLdob$p^kaqrokfkdfk.-uXL_pfaf^kT^o_b^apZqlT^oabk?riiolh%22+5)04+6&)qfiibu^iqba+yyWyK^do^kay

KDrfab@ljmibqb

]]
end)
