DugisGuideViewer:RegisterGuide("Netherwing Reputation (70+ Dailies)", nil, "Horde", "E", function()
return [[
AAA

CPe^altjllkS^iibvyKyCivqlpe^altjllkS^iibv^kaeb^aqlV^owfiiqebJbo`%33+-)53+2&yyWyPe^altjllkS^iibvy
>QebDob^qKbqebotfkdBddErkqyKyV^owfiiqebJbo`%33+-)53+2&yyNFAy..-16yyWyPe^altjllkS^iibvy
@QebDob^qKbqebotfkdBddErkqyKy@liib`q^KbqebotfkdBddclrkabfqebo^olrka%35+2)3.+/&loKbqebotfkaIbadb%33+6)5.+6&yyNFAy..-16yyWyPe^altjllkS^iibvy
QQebDob^qKbqebotfkdBddErkqyKyV^owfiiqebJbo`%33+-)53+2&yyNFAy..-16yyWyPe^altjllkS^iibvy

>>``bmqfkd>iiBddpyKyV^owfiiqebJbo`%33+-)53+2&yyNFAy..-2-yyWyPe^altjllkS^iibvyyAy
@>``bmqfkd>iiBddpyKy@liib`q^KbqebotfkdBddclrkabfqebo^olrka%35+2)3.+/&lo^ii^olrkaKbqebotfkaIbadb%33+6)5.+6yyNFAy..-2-yyWyPe^altjllkS^iibvyyAy
Q>``bmqfkd>iiBddpyKyV^owfiiqebJbo`%33+-)53+2&yyNFAy..-2-yyWyPe^altjllkS^iibvyyAy

KQrokFkNrbpqpyKyQebcliiltfkdqeobb^obqrokfknrbpqpcloJfkbop)Phfkkbop^kaEbo_^ifpqpyyWyPe^altjllkS^iibvy
>Kbqebo`fqbLobyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.5yyWyPe^altjllkS^iibvyyAy
@Kbqebo`fqbLobyKyJfkbqebKbqebo`fqbAbmlpfq^qKbqebotfkaIbadb%33+6)5.+6&^kad^qebo1-lobpyyNFAy..-.5yyWyPe^altjllkS^iibvyyAy
QKbqebo`fqbLobyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.5yyWyPe^altjllkS^iibvyyAy

>KbqeboarpqMliibkyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.4yyWyPe^altjllkS^iibvyyAy
@KbqeboarpqMliibkyKyD^qebobacoljKbqeboarpq?rpebp^qKbqebotfkaIbadb%33+6)5.+6&)`liib`q1-yyNFAy..-.4yyWyPe^altjllkS^iibvyyAy
QKbqeboarpqMliibkyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.4yyWyPe^altjllkS^iibvyyAy

>KbqebojfkbCi^vboEfabyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.3yyWyPe^altjllkS^iibvyyAy
@KbqebojfkbCi^vboEfabyKyPhfk^kvlcqebKbqebojfkbjl_p^qKbqebotfkaIbadb%33+6)5.+6&)`liib`q02yyNFAy..-.3yyWyPe^altjllkS^iibvyyAy
QKbqebojfkbCi^vboEfabyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.3yyWyPe^altjllkS^iibvyyAy

>Kbqebotfkd@ovpq^ipyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.2yyWyPe^altjllkS^iibvyyAy
@Kbqebotfkd@ovpq^ipyKyKbqebotfkd@ovpq^ip^obaolmmbacoljqebjl_p^qKbqebotfkaIbadb%33+6)5.+6&)`liib`q0-yyNFAy..-.2yyWyPe^altjllkS^iibvyyAy
QKbqebotfkd@ovpq^ipyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.2yyWyPe^altjllkS^iibvyyAy

>>PiltAb^qeyKyV^owfiiqebJbo`%33+-)53+2&yyNFAy..-/-yyWyPe^altjllkS^iibvyyAy
@>PiltAb^qeyKyHfiiCbi_l^oploAfbjbqo^alkpclrka^olrka%00+-)10+2&lo%24+-)10+3&^ka`liib`q./CbiDi^kap+Qo^sbiqlKbqebotfkaIbadb%33+6)5.+6&^karpbqebjrqqlk^olrka^kvlcqebMblk@^jmpyyNFAy..-/-yyRy0/2-0yyWyPe^altjllkS^iibvyyAy
Q>PiltAb^qeyKyV^owfiiqebJbo`%33+-)53+2&yyNFAy..-/-yyWyPe^altjllkS^iibvyyAy

>QebKlq*Pl*CofbkaivPhfbp+++yKyV^owfiiqebJbo`%33+-)53+2&yyNFAy..-02yyWyPe^altjllkS^iibvyyAy
@QebKlq*Pl*CofbkaivPhfbp+++yKyQo^sbiqlbfqebo%41+3)42+4&lo%4/+-)41+5&^ka^qq^`h^kvAo^dlkj^tQo^kpmloqbopqe^qcivm^pq+@liib`q.-KbqebotfkdObif`pyyNFAy..-02yyWyPe^altjllkS^iibvyyAy
QQebKlq*Pl*CofbkaivPhfbp+++yKyV^owfiiqebJbo`%33+-)53+2&yyNFAy..-02yyWyPe^altjllkS^iibvyyAy

KCofbkaivObmrq^qflkyKyQebpbnrbpqp^oblkiv^s^fi^_iblk`bCofbkaivObm+fpl_q^fkbayyWyPe^altjllkS^iibvyyNFAy..-20y
>Ofpb)LsbopbboyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-20yyWyPe^altjllkS^iibvy
@Ofpb)LsbopbboyKyPmb^htfqeLsboiloaJlo$delo%33+/)52+4&yyNFAy..-20yyWyPe^altjllkS^iibvy
QOfpb)LsbopbboyKyLsboiloaJlo$delo%33+/)52+4&yyNFAy..-20yyWyPe^altjllkS^iibvy
>QebKbqebotfkdJfkbpyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-42yyWyPe^altjllkS^iibvy
@QebKbqebotfkdJfkbpyKyPmb^htfqeqebJfpqobpplcqebJfkbp%30+-)54+5&lo%32+0)6-+-&yyNFAy..-42yyWyPe^altjllkS^iibvy
QQebKbqebotfkdJfkbpyKyJfpqobpplcqebJfkbp%30+-)54+5&lo%32+0)6-+-&yyNFAy..-42yyWyPe^altjllkS^iibvy

>Mf`hfkdRmQebMfb`bp+++yKyJfpqobpplcqebJfkbp%30+-)54+5&lo%32+0)6-+-&yyNFAy..-43yyWyPe^altjllkS^iibvyyAy
@Mf`hfkdRmQebMfb`bp+++yKy@liib`q.2Kbqebojfkb@^odlqe^q^obclrkafkqebjfkbplrqelcqeb`^jmyyNFAy..-43yyWyPe^altjllkS^iibvyyAy
QMf`hfkdRmQebMfb`bp+++yKyJfpqobpplcqebJfkbp%30+-)54+5&lo%32+0)6-+-&yyNFAy..-43yyWyPe^altjllkS^iibvyyAy

>Ao^dlkp^obqebIb^pqlcLroMol_ibjpyKyAo^dlkj^tClobj^k%31+2)54+-&yyNFAy..-44yyWyPe^altjllkS^iibvyyAy
@Ao^dlkp^obqebIb^pqlcLroMol_ibjpyKyHfii.2KbqebojfkbCi^vbop^ka2KbqebojfkbO^s^dbopclrkaqeolrdelrqKbqebotfkaIbadbjlpqiv^olrka%36+-)5.+0&yyNFAy..-44yyWyPe^altjllkS^iibvyyAy
QAo^dlkp^obqebIb^pqlcLroMol_ibjpyKyAo^dlkj^tClobj^k%31+2)54+-&yyNFAy..-44yyWyPe^altjllkS^iibvyyAy

>Lsbopbbfkd^kaVlr7J^hfkdqebOfdeq@elf`bpyKy@efbcLsbopbboJrairjm%33+5)53+.&yyNFAy..-21yyWyPe^altjllkS^iibvy
@Lsbopbbfkd^kaVlr7J^hfkdqebOfdeq@elf`bpyKyBfqebophfk.-HklqefabIb^qebolomro`e^pbcoljqeb>E+Qvo^kqrpfpclrka^olrka%12+-)6+4&fkKbqebopqlojyyNFAy..-21yyWyKbqebopqlojy
QLsbopbbfkd^kaVlr7J^hfkdqebOfdeq@elf`bpyKy@efbcLsbopbboJrairjm%33+5)53+.&&yyNFAy..-21yyWyPe^altjllkS^iibvy

>Qeb?llqbo^kd7>@robCloQeb@ljjlkTloqeibppMblkyKy@efbcLsbopbboJrairjm%33+5)53+.&yyNFAy..-22yyWyPe^altjllkS^iibvyyAy
@Qeb?llqbo^kd7>@robCloQeb@ljjlkTloqeibppMblkyKyRpbqeb?llqbo^kdlk^kvlcqebmblklkKbqebotfkaIbadb%33+6)5.+6&yyNFAy..-22yyRy0/35-yyWyPe^altjllkS^iibvyyAy
QQeb?llqbo^kd7>@robCloQeb@ljjlkTloqeibppMblkyKy@efbcLsbopbboJrairjm%33+5)53+.&yyNFAy..-22yyWyPe^altjllkS^iibvyyAy

KElklobaObmrq^qflkyKyQefpnrbpqfplkiv^s^fi^_iblk`bElklobaObm+fpl_q^fkbayyNFAy..-53y
>AfpormqfkdqebQtfifdeqMloq^iyKyLsboiloaJlo$delo%33+/)52+4&yyNFAy..-53yyWyPe^altjllkS^iibvyyAy
@AfpormqfkdqebQtfifdeqMloq^iyKyHfii/-Ab^qepe^alt>dbkqpclrka^olrkaQtfifdeqOfadb%.-+2)1-+2&fkK^do^kayyNFAy..-53yyWyK^do^kayyAy
QAfpormqfkdqebQtfifdeqMloq^iyKyLsboiloaJlo$delo%33+/)52+4&yyNFAy..-53yyWyPe^altjllkS^iibvyyAy

KObsbobaObmrq^qflkyKyQefpnrbpqfplkiv^s^fi^_iblk`bObsbobaObm+fpl_q^fkbayyNFAy..-64y
KP`ovbopyKy@ljmibqbqebcliiltfkd+Fc>ialo)fdklobyyNFAy..-64y
>QebAb^aifbpqQo^mBsboI^fayKy@ljj^kaboEl__%24+-)24+0&yyNFAy..-64yyWyPe^altjllkS^iibvyyAy
@QebAb^aifbpqQo^mBsboI^fayKyQefptfiipq^oq^_^qqib^d^fkpqqebAo^dlkj^tClo`bp+Vlr`^kibqqebKM@aljlpqlcqebq^khfkd)grpqhfii^pj^kv^pvlr`^ktfqelrqq^hfkdqlljr`ea^j^dbyyNFAy..-64yyWyPe^altjllkS^iibvyyAy
QQebAb^aifbpqQo^mBsboI^fayKyLsboiloaJlo$delo%33+/)52+4&yyNFAy..-64yyWyPe^altjllkS^iibvyyAy

K>ialoyKy@ljmibqbqebcliiltfkd+FcP`ovbop)fdklobyyNFAy...-.y
>QebAb^aifbpqQo^mBsboI^fayKy>ialo7@ljj^kabo>o`rp%3.+5)/6+1&yyNFAy...-.yyWyPe^altjllkS^iibvyyAy
@QebAb^aifbpqQo^mBsboI^fayKyQefptfiipq^oq^_^qqib^d^fkpqqebAo^dlkj^tClo`bp+Vlr`^kibqqebKM@aljlpqlcqebq^khfkd)grpqhfii^pj^kv^pvlr`^ktfqelrqq^hfkdqlljr`ea^j^dbyyNFAy...-.yyWyPe^altjllkS^iibvyyAy
QQebAb^aifbpqQo^mBsboI^fayKyLsboiloaJlo$delo%33+/)52+4&yyNFAy...-.yyWyPe^altjllkS^iibvyyAy

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
