DugisGuideViewer:RegisterGuide("Netherwing Reputation (70+)", nil, "Horde", "E", function()
return [[
AAA

CPe^altjllkS^iibvyKyCivqlpe^altjllkS^iibv^kaeb^aqlJloabk^f%3-+-)25+2&yyWyPe^altjllkS^iibvy
>HfkakbppyKyJloabk^f%3-+-)25+2&yyNFAy.-5-1yyWyPe^altjllkS^iibvy
@HfkakbppyKyHfii5Ol`hk^fiCi^vbop^olrka%3.+2)24+-&)Rpbqeb@^o`^ppbpqlCbba5Ao^dlkp+>iplj^hbprobqlqo^sbi^_fqtebki^vfkdqebjb^q)^pqebp^jbao^hbptlk$qb^qqtf`bfk^oltyyNFAy.-5-1yyRy0.04/yyWyPe^altjllkS^iibvy
QHfkakbppyKyJloabk^f%3-+-)25+2&yyNFAy.-5-1yyWyPe^altjllkS^iibvy

>PbbhLrqKbiqe^o^hryKyJloabk^f%3-+-)25+2&yyNFAy.-5..yyWyPe^altjllkS^iibvy
@PbbhLrqKbiqe^o^hryKyCivlkvlrojlrkq^kacfkaKbiqe^o^hr)eb`fo`ibp^olrkaqebKbqebotfkdCfbiap^_lsbqebelpqfibAo^dlkp+>mmolu+M^qe%24+.)22+4&)%30+-)3-+0&)%4.+5)3/+/&)%31+2)23+3&yyNFAy.-5..yyWyPe^altjllkS^iibvy
QPbbhLrqKbiqe^o^hryKyKbiqe^o^hr)@fo`ibp^olrkaqebKbqebotfkdCfbiap^_lsbqebelpqfibAo^dlkp+>mmolu+M^qe%24+.)22+4&)%30+-)3-+0&)%4.+5)3/+/&)%31+2)23+3&yyNFAy.-5..yyWyPe^altjllkS^iibvy

>Kbiqe^o^hr$pQ^ibyKyKbiqe^o^hr)@fo`ibp^olrkaqebKbqebotfkdCfbiap^_lsbqebelpqfibAo^dlkp+>mmolu+M^qe%24+.)22+4&)%30+-)3-+0&)%4.+5)3/+/&)%31+2)23+3&yyNFAy.-5.1yyWyPe^altjllkS^iibvy
@Kbiqe^o^hr$pQ^ibyKyIfpqbkqlKbiqe^o^hrpqlovyyNFAy.-5.1yyWyPe^altjllkS^iibvy
QKbiqe^o^hr$pQ^ibyKyKbiqe^o^hr)@fo`ibp^olrkaqebKbqebotfkdCfbiap^_lsbqebelpqfibAo^dlkp+>mmolu+M^qe%24+.)22+4&)%30+-)3-+0&)%4.+5)3/+/&)%31+2)23+3&yyNFAy.-5.1yyWyPe^altjllkS^iibvy

>Fkcfiqo^qfkdAo^dlkj^tCloqobppyKyKbiqe^o^hr)@fo`ibp^olrkaqebKbqebotfkdCfbiap^_lsbqebelpqfibAo^dlkp+>mmolu+M^qe%24+.)22+4&)%30+-)3-+0&)%4.+5)3/+/&)%31+2)23+3&yyNFAy.-503yyWyPe^altjllkS^iibvy
@Fkcfiqo^qfkdAo^dlkj^tCloqobppyKyHfii.2lc^kvqvmblclo`pfkqebcloqobpp^olrka%33+.)3-+-&yyNFAy.-503yyWyPe^altjllkS^iibvy
QFkcfiqo^qfkdAo^dlkj^tCloqobppyKyKbiqe^o^hr)@fo`ibp^olrkaqebKbqebotfkdCfbiap^_lsbqebelpqfibAo^dlkp+>mmolu+M^qe%24+.)22+4&)%30+-)3-+0&)%4.+5)3/+/&)%31+2)23+3&yyNFAy.-503yyWyPe^altjllkS^iibvy

>QlKbqebotfkdIbadbyKyKbiqe^o^hr)@fo`ibp^olrkaqebKbqebotfkdCfbiap^_lsbqebelpqfibAo^dlkp+>mmolu+M^qe%24+.)22+4&)%30+-)3-+0&)%4.+5)3/+/&)%31+2)23+3&yyNFAy.-504yyWyPe^altjllkS^iibvy
@QlKbqebotfkdIbadbyKyCfka./Kbqebosfkb@ovpq^icoljqebcil^qfkdfpi^kaPBlcqebj^fki^ka%34+0)5.+3&yyNFAy.-504yyWyPe^altjllkS^iibvy
QQlKbqebotfkdIbadbyKyKbiqe^o^hr)@fo`ibp^olrkaqebKbqebotfkdCfbiap^_lsbqebelpqfibAo^dlkp+>mmolu+M^qe%24+.)22+4&)%30+-)3-+0&)%4.+5)3/+/&)%31+2)23+3&yyNFAy.-504yyWyPe^altjllkS^iibvy

>QebClo`blcKbiqe^o^hryKyKbiqe^o^hr)@fo`ibp^olrkaqebKbqebotfkdCfbiap^_lsbqebelpqfibAo^dlkp+>mmolu+M^qe%24+.)22+4&)%30+-)3-+0&)%4.+5)3/+/&)%31+2)23+3&yyNFAy.-521yyWyPe^altjllkS^iibvy
@QebClo`blcKbiqe^o^hryKyCobb2Ao^dlkp^olrka%35+-)3-+4&_vrpfkdqebBk`e^kqbaKbqebosfkb@ovpq^ilkqebj)qebkhfii^kvlo`pqebv^ddolyyNFAy.-521yyRy0.32/yyWyPe^altjllkS^iibvy
QQebClo`blcKbiqe^o^hryKyKbiqe^o^hr)@fo`ibp^olrkaqebKbqebotfkdCfbiap^_lsbqebelpqfibAo^dlkp+>mmolu+M^qe%24+.)22+4&)%30+-)3-+0&)%4.+5)3/+/&)%31+2)23+3&yyNFAy.-521yyWyPe^altjllkS^iibvy

>H^ovk^hryKyKbiqe^o^hr)@fo`ibp^olrkaqebKbqebotfkdCfbiap^_lsbqebelpqfibAo^dlkp+>mmolu+M^qe%24+.)22+4&)%30+-)3-+0&)%4.+5)3/+/&)%31+2)23+3&yyNFAy.-525yyWyPe^altjllkS^iibvy
@H^ovk^hryKyCfkaH^ovk^hr%36+6)3.+1&)peb$plkqebpb`lkapqlovlcqebcloqobpp)albpklqobnrfob^dolrmyyNFAy.-525yyWyPe^altjllkS^iibvy
QH^ovk^hryKyH^ovk^hr%36+6)3.+1&yyNFAy.-525yyWyPe^altjllkS^iibvy

>WrirebaqebTe^`hbayKyH^ovk^hr%36+6)3.+1&yyNFAy.-533yyWyPe^altjllkS^iibvy
@WrirebaqebTe^`hbayKyQefpnrbpqtfiikbba^dolrmlc1lo2+Vlr$obobnrfobqlhfiiWrirebaqebTe^`hba%4.+/)3-+6&+?bprobql`ib^ojl_pfkqebproolrkafkdolljpcfopq+@lriamol_^_ivplillk`b5-yyNFAy.-533yyWyPe^altjllkS^iibvy
QWrirebaqebTe^`hbayKyH^ovk^hr%36+6)3.+1&yyNFAy.-533yyWyPe^altjllkS^iibvy

>>iivlcqebKbqebotfkdyKyH^ovk^hr%36+6)3.+1&yyNFAy.-54-yyWyPe^altjllkS^iibvy
@>iivlcqebKbqebotfkdyKyObqrokqlJloabk^f%3-+-)25+2&)vlrtfiifjjbaf^qbivd^fk1/)---obm^ka_b`ljbkbrqo^iyyNFAy.-54-yyWyPe^altjllkS^iibvy
Q>iivlcqebKbqebotfkdyKyJloabk^f%3-+-)25+2&yyNFAy.-54-yyWyPe^altjllkS^iibvy

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
