DugisGuideViewer:RegisterGuide("Ogri'la Reputation (70+)", nil, "Horde", "E", function() 
return [[
AAA

OPe^qqo^qe@fqvyKyQo^sbiqlPe^qqo^qe@fqv%31+2)35+/&yyNFAy.-650yyWyPe^qqo^qe@fqvy
>Jld$alodqebTfwbkbayKyDolh%31+2)35+/&yyNFAy.-650yyWyPe^qqo^qe@fqvy

O?i^ab$pBadbJlrkq^fkyKyCivql?i^ab$pBadbJlrkq^fk%22+2)11+6&yyNFAy.-650yyWy?i^ab$pBadbJlrkq^fkpy
QJld$alodqebTfwbkbayKyJld$alodqebTfwbkba%22+2)11+6&yyNFAy.-650yyWy?i^ab$pBadbJlrkq^fkpy

>Doriil`E^pQtlPhriipyKyJld$alodqebTfwbkba%22+2)11+6&yyNFAy.-662yyWy?i^ab$pBadbJlrkq^fkpy
>J^ddl`$pQob^prob@ebpqyKyJld$alodqebTfwbkba%22+2)11+6&yyNFAy.-663yyWy?i^ab$pBadbJlrkq^fkpy
>BsbkDolkkE^sbPq^ka^oapyKyJld$alodqebTfwbkba%22+2)11+6&yyNFAy.-664yyWy?i^ab$pBadbJlrkq^fkpy

@Doriil`E^pQtlPhriipyKyHfiiDoriil`*grpqkloqelcqeb^obk^%3.)14&yyWy?i^ab$pBadbJlrkq^fkpy
@J^ddl`$pQob^prob@ebpqyKyHfiiJ^ddl`*ebm^qoliplkqebol^a^olrkaab^qepallo%25)30&yyWy?i^ab$pBadbJlrkq^fkpy
OQbolhh^oClobpqyKyDlqlPe^qqo^qe@fqv%/-+/).3+3&yyNFAy.-664yyWyQbolhh^oClobpqy

@BsbkDolkkE^sbPq^ka^oapyKyHfiiPi^dd*fklkblcqeberqp%/-+/).3+3&yyNFAy.-664yyWyQbolhh^oClobpqy

O?i^ab$pBadbJlrkq^fkyKyCivql?i^ab$pBadbJlrkq^fk%22+2)11+6&yyNFAy.-662yyWy?i^ab$pBadbJlrkq^fkpy
QDoriil`E^pQtlPhriipyKyJld$alodqebTfwbkba%22+2)11+6&yyNFAy.-662yyWy?i^ab$pBadbJlrkq^fkpy
QJ^ddl`$pQob^prob@ebpqyKyJld$alodqebTfwbkba%22+2)11+6&yyNFAy.-663yyWy?i^ab$pBadbJlrkq^fkpy
QBsbkDolkkE^sbPq^ka^oapyKyJld$alodqebTfwbkba%22+2)11+6&yyNFAy.-664yyWy?i^ab$pBadbJlrkq^fkpy

>Dofj%lfob&?rpfkbppyKyJld$alodqebTfwbkba%22+2)11+6&yyNFAy.-665yyWy?i^ab$pBadbJlrkq^fkpy
@Dofj%lfob&?rpfkbppyKyCivql%44)0.&pq^kafkofkdlccfobqlprjjlkSfj$dli^kaHfiiSfj$dliyyNFAy.-665yyWy?i^ab$pBadbJlrkq^fkpy
QDofj%lfob&?rpfkbppyKyJld$alodqebTfwbkba%22+2)11+6&yyNFAy.-665yyWy?i^ab$pBadbJlrkq^fkpy

>FkqlqebplridofkaboyKyJld$alodqebTfwbkba%22+2)11+6&yyNFAy..---yyWy?i^ab$pBadbJlrkq^fkpy
@FkqlqebplridofkaboyKyCivql%3-)/1&RpbXSfj$dli$pDofjlfobZ)Hfiiqeb^aap^kaHfiiPhriil`yyNFAy..---yyRy0/134yyWy?i^ab$pBadbJlrkq^fkpy
QFkqlqebplridofkaboyKyJld$alodqebTfwbkba%22+2)11+6&yyNFAy..---yyWy?i^ab$pBadbJlrkq^fkpy

>LdobEb^sbkyKyJld$alodqebTfwbkba%22+2)11+6&yyNFAy..--6yyWy?i^ab$pBadbJlrkq^fkpy
QLdobEb^sbkyKy@er$^$ilo%/5+3)24+/&yyNFAy..--6yyWy?i^ab$pBadbJlrkq^fkpy

>Qeb@ovpq^ipyKy@er$^$ilo%/5+3)24+/&yyNFAy..-/2yyWy?i^ab$pBadbJlrkq^fkpy
@Qeb@ovpq^ipyKyHfii^kv>mbufpCi^vbo%0-)2/&)%/5)30&ql`liib`q2uX>mbufpPe^oaZyyNFAy..-/2yyWy?i^ab$pBadbJlrkq^fkpy
QQeb@ovpq^ipyKy@er$^$ilo%/5+3)24+/&yyNFAy..-/2yyWy?i^ab$pBadbJlrkq^fkpy

>>k>mbufpObif`yKy@er$^$ilo%/5+3)24+/&yyNFAy..-25yyWy?i^ab$pBadbJlrkq^fkpy
@>k>mbufpObif`yKyDlql^k>mbufpobif`%0.)3.&^kaalqebpfjlkp^vpd^jbyyNFAy..-25yyWy?i^ab$pBadbJlrkq^fkpy
Q>k>mbufpObif`yKy@er$^$ilo%/5+3)24+/&yyNFAy..-25yyWy?i^ab$pBadbJlrkq^fkpy

>Lro?lvT^kqpql_b^Phvdr^oaO^kdboyKyQlohrp%/5+2)24&yyNFAy..-0-yyWy?i^ab$pBadbJlrkq^fkpy
K@liib`q.-uX>mbufpPe^oaZyKyVlrtfiikbba.-uX>mbufpPe^oaZql_rvqebmlqflkyyIy0/236.-y
@Lro?lvT^kqpql_b^Phvdr^oaO^kdboyKyCivql%00)1.&^kavlrpelriapbb^_r__ifkdpq^`h)Qrokfk.-pe^oapcloqebXRkpq^_ibCi^phlcqeb?b^pqZyyNFAy..-0-yyWy?i^ab$pBadbJlrkq^fkpy
QLro?lvT^kqpql_b^Phvdr^oaO^kdboyKyQlohrp%/5+2)24&yyNFAy..-0-yyWy?i^ab$pBadbJlrkq^fkpy

>>C^qebo$pArqvyKyQlohrp%/5+2)24&yyNFAy..-3.yyWy?i^ab$pBadbJlrkq^fkpy
K@liib`q.-uX>mbufpPe^oaZyKyVlrtfiikbba^klqebo.-uX>mbufpPe^oaZql_rvqebXRkpq^_ibCi^phlcqebPlo`boboZyyIy0/236.-y
@>C^qebo$pArqvyKyCivql?^pe$fo@ovpq^iclodb%21).-&)Qrokfk.-pe^oapcloqebXRkpq^_ibCi^phlcqebPlo`boboZyyNFAy..-3.yyWy?i^ab$pBadbJlrkq^fkpy
Q>C^qebo$pArqvyKyQlohrp%/5+2)24&yyNFAy..-3.yyWy?i^ab$pBadbJlrkq^fkpy

>QebPhvdr^oaLrqmlpqyKy@er$^$ilo%/5+3)24+/&yyNFAy..-3/yyWy?i^ab$pBadbJlrkq^fkpy
QQebPhvdr^oaLrqmlpqyKyPhv@ljj^kaboHbiibo%/4+2)2/+4&yyNFAy..-3/yyWy?i^ab$pBadbJlrkq^fkpy

>?lj_fkdOrkyKyPhvPbodb^kqS^kaboifm%/4+3)2/+6&yyNFAy...-/yyWy?i^ab$pBadbJlrkq^fkpy
@?lj_fkdOrkyKyCivlsbo@^jm7To^qe_lj_fkdqeboba^ooltp%00)1-&)%03)06&)%01)10&yyNFAy...-/yyWy?i^ab$pBadbJlrkq^fkpyyRy0/123y
Q?lj_fkdOrkyKyPhvPbodb^kqS^kaboifm%/4+3)2/+6&yyNFAy...-/yyWy?i^ab$pBadbJlrkq^fkpy

KVlre^sbrkil`hba$?lj_qebj^d^fk$A^fivyKyQefpnrbpqfpkbbabacloqebtfkqbos^ib^`efbsbjbkq*C^*i^*i^*i^*Ldof$i^+y

]]
end)
