DugisGuideViewer:RegisterGuide("Oracle/Frenzyheart Reputation (80+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-)_rq`^k`ljmibqba^q44)fqfpgrpqjr`ee^oaboqlplilqebbifqb^qqebbka+Vlrjrpqalqebbkqfobnrbpq`e^fkqlrkil`hqebc^`qflkjl_+>cqbovlre^sbabcb^qbaqebbifqbif`e^kapbib`qbavlro^iibdf^k`b)qebkdbqqfkdqlbu^iqbaobnrfobpalfkdqeba^fifbpcloqe^qc^`qflk+Qlptfq`ec^`qflkp)grpqob*bkd^dbqebbifqbif`e)`ellpbqeblqeboc^`qflkqlhfii^ka^``bmqqebnrbpqcloqebkbtc^`qflk)ofkpb)obmb^q+y

OPeli^w^o?^pfkyKyQo^sbiqlPeli^w^o?^pfk%2-+2)44+-&yyWyPeli^w^o?^pfky
HMfq`eyKyEb^aqlPhvob^`eMfii^o^q%2-+2)44+-&^kaHfiiMfq`ecloqebnrbpqqllmbkrm+yyWyPeli^w^o?^pfky
>Mi^vfkd>ilkdyKyQo^`hboDbhdbh%2-+2)43+4&yyNFAy./2/5yyWyPeli^w^o?^pfky

QMi^vfkd>ilkdyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./2/5yyWyPeli^w^o?^pfky
>Qeb>mbErkqbo$pPi^sbyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./2/6yyWyPeli^w^o?^pfky
>QlojbkqfkdqebPlcqhkr`hibpyKyRpbXDlobdbh$pPe^`hibpZqlprjjlkDlobdbhqebDlofii^ErkqboyyNFAy./20-yyRy053.6yyWyPeli^w^o?^pfky

@Qeb>mbErkqbo$pPi^sbyNFAy./2/6yyKyDlplrqeb^pqql%33+2)40+4&Hfii5E^oahkr`hibClo^dbop^ka3@e^odbopyyWyPeli^w^o?^pfky
@QlojbkqfkdqebPlcqhkr`hibpyNFAy./20-yyRy05134yyKyRpbqebXPlcqhkr`hibMlhboZqlqlojbkqqeb_^_vdlofii^p^q%33+2)40+4&)tef`eprjjlkp^E^oahkr`hibJ^qof^`eqlhfiiyyWyPeli^w^o?^pfky

QQlojbkqfkdqebPlcqhkr`hibpyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./20-yyWyPeli^w^o?^pfky
QQeb>mbErkqbo$pPi^sbyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./2/6yyWyPeli^w^o?^pfky
>QebT^pmErkqbo$p>mmobkqf`byKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./200yyWyPeli^w^o?^pfky
>QebP^mmefobNrbbkyKyBiaboE^ohbh%22+2)36+3&yyNFAy./201yyWyPeli^w^o?^pfky

@QebT^pmErkqbo$p>mmobkqf`byKyEb^aqlqebP^mme^fobEfsb^q%3-+-)44+6&+Hfii6EfsbAolkbp^ka3T^pmpyyNFAy./200yyWyPeli^w^o?^pfky
@QebP^mmefobNrbbkyNFAy./201yyKyDlfkpfabqebild^kaqlqebsbov_lqqljlcqeb`^sb^kahfiiqebP^mmefobEfsbNrbbk%24+/)46+1&^kaillqebopqfkdboyyWyPeli^w^o?^pfky

QQebT^pmErkqbo$p>mmobkqf`byKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./200yyWyPeli^w^o?^pfky
QQebP^mmefobNrbbkyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./201yyWyPeli^w^o?^pfky
>Ciltkqeb@llmyKyBiaboE^ohbh%22+2)36+3&yyNFAy./20/yyWyPeli^w^o?^pfky
@Ciltkqeb@llmyNFAy./20/yyRy05356yyKyRpbqebX@ef`hbkKbqZqlnrf`hivqo^mqeb`ef`hbk)_rqalklq`e^pbqebjloqebvtfiiork)lk`bqo^mmba)illqyyWyPeli^w^o?^pfky
QCiltkqeb@llmyKyBiaboE^ohbh%22+2)36+3&yyNFAy./20/yyWyPeli^w^o?^pfky
>QebRkabodolrkaJbk^`byKyBiaboE^ohbh%22+2)36+3&yyNFAy./20.yyWyPeli^w^o?^pfky
>Jfp`efbcfkqebJ^hfkdyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./202yyWyPeli^w^o?^pfky

@Jfp`efbcfkqebJ^hfkdyNFAy./202yyKyEb^aqlqebofsbo^q%2.+3)53+/&^kaillq5lcqebXPhvob^`e@ovpq^i@irpqbopZ^ilkdqebofsboyyWyPeli^w^o?^pfky
@QebRkabodolrkaJbk^`byNFAy./20.yyKyCfka^kahfiiPbocbuqebOb^sbotelfprkabodolrka^p^tloj^olrka%16+3)52+2&lo%25+5)52+2&yyWyPeli^w^o?^pfky

QJfp`efbcfkqebJ^hfkdyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./202yyWyPeli^w^o?^pfky
QQebRkabodolrkaJbk^`byKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./20.yyWyPeli^w^o?^pfky
>>OlrdeOfabyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./203yyWyPeli^w^o?^pfky

@>OlrdeOfabyNFAy./203yyKyQ^ihqlqeb@^mqfsb@ol`lifph%24+0)35+1&qebobqldbq^ofabqlJfpqtefpmboObcrdbyyWyPeli^w^o?^pfky
Q>OlrdeOfabyKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`ErkqboyyNFAy./203yyRy052./yyWyPeli^w^o?^pfky
>IfdeqkfkdAbcfkfqbivPqofhbpQtf`byKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`ErkqboyyNFAy./204yyRy052./yyWyPeli^w^o?^pfky
>QebJfpqFpk$qIfpqbkfkdyKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`ErkqboyyNFAy./205yyRy052./yyWyPeli^w^o?^pfky
@QebJfpqFpk$qIfpqbkfkdyKyHfii./JfpqtefpmboDloil`p^olrkaqebobcrdb^q%12+-)04+-&yyNFAy./205yyWyPeli^w^o?^pfky
@IfdeqkfkdAbcfkfqbivPqofhbpQtf`byNFAy./204yyRy052.-yyKyRpbqebXPhvob^`e@ovpq^i@irpqbopZ^qqeb_^pblcqebPeofkb^q%12+-)04+-&qebk`if`hqeb`ovpq^iqlp^_lq^dbfqyyWyPeli^w^o?^pfky
QIfdeqkfkdAbcfkfqbivPqofhbpQtf`byKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`ErkqboyyNFAy./204yyRy052./yyWyPeli^w^o?^pfky
QQebJfpqFpk$qIfpqbkfkdyKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`ErkqboyyNFAy./205yyRy052./yyWyPeli^w^o?^pfky
>EllcfkdFqyKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`ErkqboyyNFAy./206yyRy052./yyWyPeli^w^o?^pfky

QEllcfkdFqyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./206yyWyPeli^w^o?^pfky
>GrpqCliiltfkdLoabopyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./21-yyWyPeli^w^o?^pfky

QGrpqCliiltfkdLoabopyKyFkgrobaO^fkpmb^hboLo^`ib%22+4)32&)tfiipm^tk^klk*bifqb`ol`lifphyyNFAy./21-yyWyPeli^w^o?^pfky
>Cloqrk^qbJfprkabopq^kafkdpyKyFkgrobaO^fkpmb^hboLo^`ib%22+4)32&yyNFAy./24-yyWyPeli^w^o?^pfky

QCloqrk^qbJfprkabopq^kafkdpyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./24-yyWyPeli^w^o?^pfky
>J^hbqeb?^aPk^hbDl>t^vyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./24.yyWyPeli^w^o?^pfky
>DlapIfhbPefkvQefkdpyKyRpbXI^cll$p?rd?^dZqlprjjlkI^cllyyNFAy./24/yyRy053//yyWyPeli^w^o?^pfky

@J^hbqeb?^aPk^hbDl>t^vyKyHfiiqebBjmbolo@l_o^p^olrka%21+-)2-+-&^kaSbkljqfm^q%25+0)21+4&yyNFAy./24.yyWyPeli^w^o?^pfky
@DlapIfhbPefkvQefkdpyKyTefipqhfiifkd`l_o^pt^ih^olrkaqebpefkv^ob^lcafoq^olrka%21+-)2-+-&plI^cll`^kafdrmXPefkvQob^probpZyyNFAy./24/yyRy053//yyWyPeli^w^o?^pfky

QJ^hbqeb?^aPk^hbDl>t^vyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./24.yyWyPeli^w^o?^pfky
QDlapIfhbPefkvQefkdpyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./24/yyWyPeli^w^o?^pfky
>J^hfkdMb^`byKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./240yyWyPeli^w^o?^pfky

@J^hfkdMb^`byNFAy./240yyKyPmb^htfqePe^j^kSbhgfh%2.+0)31+4&yyWyPeli^w^o?^pfky

QJ^hfkdMb^`byKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./240yyWyPeli^w^o?^pfky
>?^`hPlPllk<yKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./241yyWyPeli^w^o?^pfky

Q?^`hPlPllk<yKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./241yyWyPeli^w^o?^pfky
>QebIlpqJfpqtefpmboQob^probyKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./242yyWyPeli^w^o?^pfky
>Clo`baE^kayKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./243yyWyPeli^w^o?^pfky

@Clo`baE^kayNFAy./243yyRy053/0yyKy>qqebCobkwveb^oq`^jm%1-+3)/1+0&+RpbG^illqclobuqo^AMPlkqebjl_pebobyyWyPeli^w^o?^pfky
@QebIlpqJfpqtefpmboQob^probyNFAy./242yyKyRpbqeb>iq^o^q%1.+2).6+3&qlprjjlkT^oiloaQ^oqbh^kaefpao^dlk)hfiiqebj_lqe^kaillqqebXJfpqtefpmboQob^probZyyWyPeli^w^o?^pfky

QQebIlpqJfpqtefpmboQob^probyKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./242yyWyPeli^w^o?^pfky
QClo`baE^kayKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./243yyWyPeli^w^o?^pfky
>EljbQfjbyKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./244yyWyPeli^w^o?^pfky
QEljbQfjbyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./244yyWyPeli^w^o?^pfky
>Qeb>kdovDloil`yKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./245yyWyPeli^w^o?^pfky
QQeb>kdovDloil`yKyQo^sbiqlJlppt^ihboSfii^db^olrka%42)2/&qebkRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyNFAy./245yyRy053/1yyWyPeli^w^o?^pfky
>QebJlppt^ihboP^sfloyKyRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyNFAy./25-yyRy053/1yyWyPeli^w^o?^pfky
>Ifcb_illalcqebJlppt^ihboPeofkbyKyRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyNFAy./246yyRy053/1yyWyPeli^w^o?^pfky
@QebJlppt^ihboP^sfloyKyDl^olrkaqeb`^jm%43+-)2/+6&^kaq^ihqlqebJlppt^ihboSf`qfjp^karkqfi3^obp^sbayyNFAy./25-yyWyPeli^w^o?^pfky
@Ifcb_illalcqebJlppt^ihboPeofkbyKy@liib`q.-XIfcb_illaPe^oapZp`^qqbobalkqebdolrka^olrka%4/+1)3.+.&yyNFAy./246yyWyPeli^w^o?^pfky
QIfcb_illalcqebJlppt^ihboPeofkbyKyRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyNFAy./246yyRy053/1yyWyPeli^w^o?^pfky
QQebJlppt^ihboP^sfloyKyRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyNFAy./25-yyRy053/1yyWyPeli^w^o?^pfky
>>Ebol$p?roabkyKyRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyNFAy./25.yyRy053/1yyWyPeli^w^o?^pfky
KCobkwveb^oqloLo^`ibyKy>q0-">oqorfpqebEb^oqibpp_b`ljbpfjjrkbql^qq^`hp+G^illq^kaWbmfhtfiipq^oq^qq^`hfkd+Fcvlrt^kqCobkwveb^oq)hfiiG^illqlkiv+Fcvlrt^kqLo^`ibHfiiWbmfhlkiv+yyNFAy./25.yyWyPeli^w^o?^pfky
@>Ebol$p?roabkyKyPi^v>oqorfpqebEb^oqibpp%4/+/)24+0&+yyNFAy./25.yyWyPeli^w^o?^pfky
Q>Ebol$p?roabkyKy>oqorfp$pMevi^`qbov%4/+/)24+0&yyNFAy./25.yyWyPeli^w^o?^pfky

KPq^oqA^fifbpyKy>``bmqqebnrbpqclojvlroabpfobac^`qflk)^kaptfq`eqlqeba^fivnrbpqdrfabcloqe^qc^`qflk+y

KPtfq`efkdyKyQlptfq`ec^`qflkp)bkd^db>oqorfpqebEb^oqibpp^kahfiiqeblmmlpfqbkm`lcqebc^`qflkvlrt^kq+Vlrtfii_b^_ibqlpq^oq^qElklobatfqeqe^qc^`qflk+Drfab@ljmibqb+y
KDrfab@ljmibqb

]]
end)
