DugisGuideViewer:RegisterGuide("The Scryer Reputation (68+)", nil, "Horde", "E", function()
return [[
AAA

OPe^qqo^qe@fqvyKyQo^sbiqlPe^qqo^qe@fqv%25+2)1.&yyWyPe^qqo^qe@fqvyyNFAy.-/.-y
>>$a^iyKyVlr$obillhfkdclo^E^dd^oaT^oSbqbo^k%25+2)1.&)ebpelria_bc^foivb^pvqlcfkakb^oqeb`bkqbolcqeb`fqvyyWyPe^qqo^qe@fqvyyNFAy.-/.-y
Q>$a^iyKy>$a^i%21)11+2&yyWyPe^qqo^qe@fqvyyNFAy.-/.-y
>@fqvlcIfdeqyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-/..y
Q@fqvlcIfdeqyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-/..y
>>iibdf^k`bqlqebP`ovbopyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-22/y
Q>iibdf^k`bqlqebP`ovbopyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-22/y
>Slobk$qe^iqebPbboyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-220y
QSlobk$qe^iqebPbboyKySlobk$qe^iqebPbbo%1/+4)6.+2&yyWyPe^qqo^qe@fqvyyNFAy.-220y

>PvkqebpfplcMltboyKySlobk$qe^iqebPbbo%1/+4)6.+2&yyWyPe^qqo^qe@fqvyyNFAy.-1.3y
>ObmloqqlPmvj^pqboQe^ilafbkyKy>o`^kfpqP^s^k%12+.)43+1&yyWyPe^qqo^qe@fqvyyNFAy..-06y

K@liib`q^pvlrnrbpqyKyHbbm^iiqebX>o`^kbQljbZ)XCfobtfkdPfdkbqZ)^kaXPrkcrovPfdkbqZcloobmqrok*fkp+y

C>ob^2/yKyCivql>ob^2/%31+.)1.+.&yyNFAy..-06yyWyPe^qqo^qe@fqvy
QObmloqqlPmvj^pqboQe^ilafbkyKyPmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy..-06yyWyKbqebopqlojy
>J^k^clodb?$k^^oyKyPmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy.-.56yyWyKbqebopqlojy
@J^k^clodb?$k^^oyKyHfii@^mq^fk>o^qevk%/4+4)32+/&fkpfabJ^k^clodb?$k^^o^ka`libi`qqeb?$k^^oMboplkkbiOlpqboyyIy/5043yyNFAy.-.56yyWyKbqebopqlojy
QJ^k^clodb?$k^^oyKyPmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy.-.56yyWyKbqebopqlojy
>EfdeS^irbQ^odbqpyKyPmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy.-.60yyWyKbqebopqlojy
@EfdeS^irbQ^odbqpyKypi^v/PrkcrovT^om*J^pqbop)3PrkcrovT^om*Bkdfkbbop^ka5PrkcrovDblildfpqp+%/0+5)4-+1&yyNFAy.-.60yyWyKbqebopqlojy
QEfdeS^irbQ^odbqpyKyPmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy.-.60yyWyKbqebopqlojy

>PerqqfkdAltkJ^k^clodb?$k^^oyKyPmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy.-0/6yyWyKbqebopqlojy
>?illadbj@ovpq^ipyKyJ^dfpqofuI^ovkk^%0/+-)31+.&yyNFAy.-/-1yyWyKbqebopqlojy
@?illadbj@ovpq^ipyKyL_q^fk^?illadbjPe^oacolj^PrkcrovJ^dfpqbo)qebkrpbqefppe^oakb^oqebi^odbo?illadbj`ovpq^ip+yyNFAy.-/-1yyWyKbqebopqlojy
@PerqqfkdAltkJ^k^clodb?$k^^oyKyHfiiLsbopbboQebobafp%/0+5)4-+2&fkpfabqebj^k^clodb)illqqebX?$k^^o>``bpp@ovpq^iZ^karpbqeb`lkplibyyIy/6033yyNFAy.-0/6yyWyKbqebopqlojy
QPerqqfkdAltkJ^k^clodb?$k^^oyKyPmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy.-0/6yyWyKbqebopqlojy
Q?illadbj@ovpq^ipyKyJ^dfpqofuI^ovkk^%0/+-)31+.&yyNFAy.-/-1yyWyKbqebopqlojy
>Pqb^iqeCifdeqyKyPmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy.-.61yyWyKbqebopqlojy
QPqb^iqeCifdeqyKySbolkf^%00+5)31+0&yyNFAy.-.61yyWyKbqebopqlojy
>?befkaBkbjvIfkbpyKySbolkf^%00+5)31+0&yyNFAy.-32/yyWyKbqebopqlojy
Q?befkaBkbjvIfkbpyKy@^ibafp?ofdeqa^tk%15+/)53+4&yyNFAy.-32/yyWyKbqebopqlojy
>>@lksfk`fkdAfpdrfpbyKy@^ibafp?ofdeqa^tk%15+/)53+4&yyNFAy.-.64yyWyKbqebopqlojy
@>@lksfk`fkdAfpdrfpbyKyL_q^fk^pbqlcPrkcrov>o`^kfpqOl_bp)lkbm^folcPrkcrovObpb^o`eboDilsbp^ka^PrkcrovDr^oapj^kJba^iiflk%2.+1)5.+1&yyNFAy.-.64yyWyKbqebopqlojy
Q>@lksfk`fkdAfpdrfpbyKy@^ibafp?ofdeqa^tk%15+/)53+4&yyNFAy.-.64yyWyKbqebopqlojy
>Fkcloj^qflkD^qebofkdyKy@^ibafp?ofdeqa^tk%15+/)53+4&yyNFAy.-.65yyWyKbqebopqlojy
@Fkcloj^qflkD^qebofkdyKyRpbqebPrkcrovAfpdrfpb)dlfkqlJ^k^clodb@lorr^kaifpqbkqlqeb`lksbop^qflk_bqtbbk@ljj^kaboA^tkclodb^ka>o`^kfpq>oalkfp+yyRy/53-4yyNFAy.-.65yyWyKbqebopqlojy
QFkcloj^qflkD^qebofkdyKy@^ibafp?ofdeqa^tk%15+/)53+4&yyNFAy.-.65yyWyKbqebopqlojy

>PerqqfkdAltkJ^k^clodb@lorryKy@^ibafp?ofdeqa^tk%15+/)53+4&yyNFAy.-00-yyWyKbqebopqlojy
@PerqqfkdAltkJ^k^clodb@lorryKyB^pqlsboqeb_ofadb%13)5.&+HfiiLsbopbboPbvi^kk^%16+-)5.+2&qebkillqqebX@lorr>``bpp@ovpq^iZ^karpbqeb`lkplibyyIy/6063yyNFAy.-00-yyWyKbqebopqlojy
QPerqqfkdAltkJ^k^clodb@lorryKy@^ibafp?ofdeqa^tk%15+/)53+4&yyNFAy.-00-yyWyKbqebopqlojy
>ObqrokqlQe^ilafbkyKy@^ibafp?ofdeqa^tk%15+/)53+4&yyNFAy.-/--yyWyKbqebopqlojy
QObqrokqlQe^ilafbkyKyPmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy.-/--yyWyKbqebopqlojy

>PerqqfkdAltkJ^k^clodbArolyKyPmvj^pqboQe^ilafbk%0/+-)31+/&yyNFAy.-005yyWyKbqebopqlojy
>Hf`hQebjTefibQebv$obAltkyKyJ^dfpqofuI^ovkk^%0/+-)31+.&yyNFAy.-01.yyWyKbqebopqlojy

@Hf`hQebjTefibQebv$obAltkyKyPi^v5Prkcrov@lkgrobop)3Prkcrov?ltjbk^ka1Prkcrov@bkqroflkp+%26+6)35+0&yyNFAy.-01.yyWyKbqebopqlojy
@PerqqfkdAltkJ^k^clodbArolyKyB^pq^qJ^k^clodbArol+HfiiLsbopbbo>qe^kbi%26+6)35+0&)illqqebXArol>``bpp@ovpq^iZ^karpblk`lkplibyyIy/6064yyNFAy.-005yyWyKbqebopqlojyyWyKbqebopqlojy
QPerqqfkdAltkJ^k^clodbArolyKyPmvj^pqboQe^ilafbk%0/+-)31+/&yyNFAy.-005yyWyKbqebopqlojy
QHf`hQebjTefibQebv$obAltkyKyJ^dfpqofuI^ovkk^%0/+-)31+.&yyNFAy.-01.yyWyKbqebopqlojy

>PerqqfkdAltkJ^k^clodb>o^yKyPmvj^pqboQe^ilafbk%0/+-)31+/&yyNFAy.-032yyWyKbqebopqlojy
>>Abcb`qloyKyJ^dfpqofuI^ovkk^%0/+-)31+.&yyNFAy.-/-/yyWyKbqebopqlojy

Q>Abcb`qloyKyJ^dfpqboQebibalok%/3+/)1.+4&yyNFAy.-/-/yyWyKbqebopqlojy
>A^jkfkdBsfabk`byKyJ^dfpqboQebibalok%/3+/)1.+4&yyNFAy.-10/yyWyKbqebopqlojy

@A^jkfkdBsfabk`byKyL_q^fk5LoabopcoljH^bi$qe^pcoljabjlkp^qJ^k^clodb>o^yyNFAy.-10/yyWyKbqebopqlojy
@PerqqfkdAltkJ^k^clodb>o^yKyHfiiLsbopbbo>w^o^a%/3+.)06+4&)illqqebX>o^>``bpp@ovpq^iZ^karpblk`lkplibyyIy/61..yyNFAy.-032yyWyKbqebopqlojy
QPerqqfkdAltkJ^k^clodb>o^yKyPmvj^pqboQe^ilafbk%0/+-)31+/&yyNFAy.-032yyWyKbqebopqlojy
QA^jkfkdBsfabk`byKyPmvj^pqboQe^ilafbk%0/+-)31+/&yyNFAy.-10/yyWyKbqebopqlojy
>>DfcqcloSlobk$qe^iyKyPmvj^pqboQe^ilafbk%0/+-)31+/&yyNFAy.-2-5yyWyKbqebopqlojy

KCfopqE^iclcPl`obqe^o$pPqlkbyKyPi^vClodbj^pqboJlord%03+6)/4+3&yyIy/63/1yyNFAy.-2-5yyWyKbqebopqlojy
@>DfcqcloSlobk$qe^iyKyPb`lkaE^iclcPl`obqe^o$pPqlkb)Pi^vPfiolqe%1-+6).6+0&yyNFAy.-2-5yyWyKbqebopqlojy
Q>DfcqcloSlobk$qe^iyKyPmvj^pqboQe^ilafbk%0/+-)31+/&yyNFAy.-2-5yyWyKbqebopqlojy
>?lrkacloDilovyKyPmvj^pqboQe^ilafbk%0/+-)31+/&yyNFAy.-2-6yyWyKbqebopqlojy

CPe^qqo^qe@fqvyKyCivqlPe^qqo^qe@fqv%00+4)31&yyWyKbqebopqlojyyNFAy.-2-6y

Q?lrkacloDilovyKySlobk$qe^iqebPbbo%1/+4)6.+2&yyWyPe^qqo^qe@fqvyyNFAy.-2-6y
>QrokfkdMlfkqyKySlobk$qe^iqebPbbo%1/+4)6.+2&yyWyPe^qqo^qe@fqvyyNFAy.-2-4y

C>ob^2/yKyCivql>ob^2/%31+.)1.+.&yyNFAy.-2-4yyWyKbqebopqlojy

@QrokfkdMlfkqyKyIbdflkQbibmloqbo^qqebkloqetbpqbok`lokbolcKbqebopqloj^karpbfqqlqbibmloqqlPl`obqe^o$pPb^q+Lk`bqebob)abcb^qPl`obqe^orpfkdXSlobk$qe^i$pMobpbk`bZ+%/6+3).0+6&yyNFAy.-2-4yyRy0-/26yyWyKbqebopqlojy
QQrokfkdMlfkqyKySlobk$qe^iqebPbbo%/6+3).0+6&yyNFAy.-2-4yyWyKbqebopqlojy

CPe^altjllkS^iibvyKyCivqlPe^altjllkS^iibv%00+4)31&yyWyKbqebopqlojyyyNFAy.-5-4y

>Qeb>peqlkdrb?olhbkyKyS^obkqebOb`i^fjbo%21+5)25+/&yyNFAy.-5-4yyWyPe^altjllkS^iibvy
>Q^_ibqplc?^^$ofyKy>o`^kfpqQebifp%23+0)26+2&yyNFAy.-350yyWyPe^altjllkS^iibvy
>H^o^_loQo^fkfkdDolrkapyKyI^ofpp^Prkpqofhb%22+5)25+/&yyNFAy.-354yyWyPe^altjllkS^iibvy

@Qeb>peqlkdrb?olhbkyKy>qqebOrfkplc?^^$of%23+6)02+3&yyNFAy.-5-4yyWyPe^altjllkS^iibvy
@Q^_ibqplc?^^$ofyKy>qqebOrfkplc?^^$of%23+6)02+3&yyNFAy.-350yyWyPe^altjllkS^iibvy
@H^o^_loQo^fkfkdDolrkapyKyFkpfabqeb?i^`hQbjmib)q^hbqebcfopqofdeq%35+-)2-+-&+HfiiAbjlkErkqboPrmmif`^kqp^kaFkfqf^qbp)qovql`^q`eqebj^cqbo^arbitebkqebv^obiltlkEM)qebvifkhifhbj^a+>iplt^q`elrqcloqebbifqbqe^qt^kabopqeorqeb^ob^+yyNFAy.-354yyWyPe^altjllkS^iibvy

QQeb>peqlkdrb?olhbkyKyS^obkqebOb`i^fjbo%21+5)25+/&yyNFAy.-5-4yyWyPe^altjllkS^iibvy
>QebDob^qObqof_rqflkyKyS^obkqebOb`i^fjbo%21+5)25+/&yyNFAy.-5.4yyWyPe^altjllkS^iibvy
>LolkrqebBiaboyKy>o`^kfpqQebifp%23+0)26+2&yyNFAy.-351yyWyPe^altjllkS^iibvy
QQ^_ibqplc?^^$ofyKy>o`^kfpqQebifp%23+0)26+2&yyNFAy.-350yyWyPe^altjllkS^iibvy
QH^o^_loQo^fkfkdDolrkapyKyI^ofpp^Prkpqofhb%22+5)25+/&yyNFAy.-354yyWyPe^altjllkS^iibvy
>>Kb`bpp^ovAfpqo^`qflkyKyI^ofpp^Prkpqofhb%22+5)25+/&yyNFAy.-355yyWyPe^altjllkS^iibvy

@>Kb`bpp^ovAfpqo^`qflkyKyHfiiPrjjlkbop^kaT^oil`hp^olrka%4.+.)2.+0&rkqfiqebp`oliiaolmp)qebkrpbfqlk>w^ilqe%4-+-)2.+1&+Alklqhfiiqebjl_pkb^oefj)loeb$ii`ljb^cqbovlr+yyRy0-5..yyNFAy.-355yyWyPe^altjllkS^iibvy
@QebDob^qObqof_rqflkyKyPi^v5Pe^altjllkPi^vbop)5Pe^altjllk@elpbk^ka1Pe^altjllkA^ohtb^sbop%36+/)05+/&yyNFAy.-5.4yyWyPe^altjllkS^iibvy
@LolkrqebBiaboyKyVlr`^kcfkaLolkrqebBiabo^q%24+/)00+.&fkpfabqeborfkpyyNFAy.-351yyWyPe^altjllkS^iibvy
QLolkrqebBiaboyKy>o`^kfpqQebifp%23+0)26+2&yyNFAy.-351yyWyPe^altjllkS^iibvy
>Qeb>peqlkdrb@loormqlopyKy>o`^kfpqQebifp%23+0)26+2&yyNFAy.-352yyWyPe^altjllkS^iibvy
QQebDob^qObqof_rqflkyKyS^obkqebOb`i^fjbo%21+5)25+/&yyNFAy.-5.4yyWyPe^altjllkS^iibvy
Q>Kb`bpp^ovAfpqo^`qflkyKyI^ofpp^Prkpqofhb%22+5)25+/&yyNFAy.-355yyWyPe^altjllkS^iibvy
>>iqorfpyKyI^ofpp^Prkpqofhb%22+5)25+/&yyNFAy.-356yyWyPe^altjllkS^iibvy

@Qeb>peqlkdrb@loormqlopyKyHfiiE^^irj%24+-)40+-&)Bvhbkbk%2.+-)2/+-&)Rvi^or%15+-)06+-&^kaI^h^^k%16+-)/0+-&yyNFAy.-352yyWyPe^altjllkS^iibvy
QQeb>peqlkdrb@loormqlopyKy>o`^kfpqQebifp%23+0)26+2&yyNFAy.-352yyWyPe^altjllkS^iibvy
>QebT^oabk$p@^dbyKy>o`^kfpqQebifp%23+0)26+2&yyNFAy.-353yyWyPe^altjllkS^iibvy
QQebT^oabk$p@^dbyKyP^klor%24+0)16+3&)fkqebelibyyNFAy.-353yyWyPe^altjllkS^iibvy

CK^do^kayKyCivqlK^do^ka%23+0)24+5&yyNFAy.-31.yyWyPe^altjllkS^iibvy

Q>iqorfpyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-356yyWyK^do^kay
>>d^fkpqqebIbdflkyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-31.yyWyK^do^kay
>>d^fkpqqebFiifa^ofyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-335yyWyK^do^kay
>>d^fkpq>iiLaapyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-336yyWyK^do^kay

OW^kd^oj^opeyKyQo^sbiqlW^kd^oj^ope%.3+0)1-+4&yyWyW^kd^oj^opeyyNFAy.-313y

@>d^fkpq>iiLaapyKyQ^hbqebFj_rbaPfisboPmb^o^karpbfq^qMloq^i@ib^ofkdkb^oJ^opeifdeqI^hb%.3+0)1-+4&^kapi^vUbibqeyyRy0-520yyNFAy.-336yyWyW^kd^oj^opey

CQebPqlojpmfobyKyCivqlQebPqlojpmfob)Kbqebopqloj%1.+0)/6&yyWyW^kd^oj^opeyyNFAy.-313y

@>d^fkpqqebIbdflkyKyL_q^fkCobpeivAo^tk?illacolj^To^qeMofbpqbpp^qClodb?^pb7Dbebkk^)qebkpmfiifqlkqebdolrka^kapi^vqeb>s^q^olcP^qe^i+%06+/)/-+2&yyNFAy.-31.yyWyKbqebopqlojy

CPe^altjllkSfii^dbyKyCivqlPe^altjllkSfii^db%12+0)01+6&yyWyKbqebopqlojyyNFAy.-313y

@>d^fkpqqebFiifa^ofyKyPi^vIlqeolp^qFiifa^ofMlfkq%/4+4)2-+6&yyNFAy.-335yyWyPe^altjllkS^iibvy

CK^do^kayKyCivqlK^do^ka%0-+0)/6+/&yyWyPe^altjllkS^iibvy

Q>d^fkpqqebIbdflkyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-31.yyWyK^do^kay
Q>d^fkpqqebFiifa^ofyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-335yyWyK^do^kay
Q>d^fkpq>iiLaapyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-336yyWyK^do^kay
>Fiifa^k$pMrmfiyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-313yyWyK^do^kay
@Fiifa^k$pMrmfiyKyIfpqbkql>iqorfpqebPrccbobo$ppqlov%/4+1)10+.&yyNFAy.-313yyWyK^do^kay
QFiifa^k$pMrmfiyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-313yyWyK^do^kay
>Qeb?llhlcCbiK^jbpyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-316yyWyK^do^kay

OQbolhh^oClobpqyKyQo^sbiqlQbolhh^oClobpq%06+3)36+.&yyWyQbolhh^oClobpqyyNFAy.-36.y

@Qeb?llhlcCbiK^jbpyKyL_q^fkqeb?llhlcCbiK^jbpcolj?i^`heb^oqqebFk`fqbofkqebPe^altI^_vofkqe%06+0)31+1&yyNFAy.-316yyWyQbolhh^oClobpqy

OK^do^kayKyQo^sbiqlK^do^ka%/4+1)10+.&yyNFAy.-36.yyWyK^do^kay

QQeb?llhlcCbiK^jbpyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-316yyWyK^do^kay
>ObqrokqlqebP`ovbopyKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy.-36.yyWyK^do^kay

CPe^altjllkS^iibvyKyCivqlPe^altjllkS^iibv%24+/)02+0&yyNFAy.-36/yyWyK^do^kay

QObqrokqlqebP`ovbopyKyI^ofpp^Prkpqofhb%3.+/)/6+/&yyNFAy.-36.yyWyPe^altjllkS^iibvy
>S^obafpJrpq?bPqlmmbayKyI^ofpp^Prkpqofhb%3.+/)/6+/&yyNFAy.-36/yyWyPe^altjllkS^iibvy
HS^obafpyKy%4/)20+1&+RpbqebX?llhlcCbiK^jbpZtebkebJbq^jlomelpfpyyRy0-521yyNFAy.-36/yyNLyS^obafppi^fk7.,.yyWyPe^altjllkS^iibvy
HKbqe^obiyKy%35+1)20+3&yyNFAy.-36/yyNLyKbqe^obipi^fk7.,.yyWyPe^altjllkS^iibvy
HQebo^pyKy%4/+/)15+1&yyNFAy.-36/yyNLyQebo^ppi^fk7.,.yyWyPe^altjllkS^iibvy
@S^obafpJrpq?bPqlmmbayKyPi^v>i^kafbk%36+3)20+5&yyNFAy.-36/yyWyPe^altjllkS^iibvy
QS^obafpJrpq?bPqlmmbayKyI^ofpp^Prkpqofhb%3.+/)/6+/&yyNFAy.-36/yyWyPe^altjllkS^iibvy

QPvkqebpfplcMltboyKySlobk$qe^iqebPbbo%1/+4)6.+2&yyWyPe^qqo^qe@fqvyyNFAy.-1.3y

KQrok*fkpyKy@lkqfkrbdofkafkdjl_p^`liib`qfkdXCbi>oj^jbkqpZ)XJ^ohlcHfi$g^babkZ)^kaXJ^ohlcP^odbo^pZcmoobmqrok*fkp+Drfab@ljmibqby

]]
end)
