DugisGuideViewer:RegisterGuide("Sha'tari Skyguard / Ogri'la (70+ Dailies)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQebpb^obqeba^fivnrbpqcloPe^$q^of,Ld$ofi^obm+Qebob^obpbsbo^iobmb^q^_ibnrbpqfkPhbqqfpqe^q`^k_balkb^ptbii+y

OQbolhh^oClobpqyKyQo^sbiqlQbolhh^oClobpq%31+2)33+2&yyWyQbolhh^oClobpqy
KP^sbXPe^altArpqZyKyP^sb^qib^pq3uXPe^altArpqZcloobmqrok*fky
>CfobpLsboPhbqqfpyKyPhvPbodb^kqAlovk%31+2)33+2&yyNFAy..--5yyWyQbolhh^oClobpqyyAy
@CfobpLsboPhbqqfpyKyPbbhlrqJlkpqolrpH^ifofBddplkqebqlmplcPhbqqfpatbiifkdp^karpbqebPhvdr^oa?i^pqfkd@e^odbplkqebj+%33+1)46+/&yyNFAy..--5yyRy0/1-3yyWyQbolhh^oClobpqyyAy
>Bp`^mbcoljPhbqqfpyKyPhvdr^oaMofplkbo%3.+/)41+0&%36+-)41+.&%42+.)53+6&yyNFAy..-52yyWyQbolhh^oClobpqyyAy
@Bp`^mbcoljPhbqqfpyKyBp`loqqebPhvdr^oaMofplkboqlp^cbqvyyNFAy..-52yyWyQbolhh^oClobpqyyAy
QCfobpLsboPhbqqfpyKyPhvPbodb^kqAlovk%31+2)33+2&yyNFAy..--5yyWyQbolhh^oClobpqyyAy
QBp`^mbcoljPhbqqfpyKyPhvPbodb^kqAlovk%31+2)33+2&yyNFAy..-52yyWyQbolhh^oClobpqyyAy
KXBifufolcPe^altpZyKyL_q^fkXBifufolcPe^altpZcoljPbsbofk%31+.)33+5&clo3uXPe^altArpqZyyWyQbolhh^oClobpqy

O?i^ab$pBadbJlrkq^fkpyKyQo^sbiql?i^ab$pBadbJlrkq^fkp%/4+3)2/+6&yyWy?i^ab$pBadbJlrkq^fkpy
>?lj_Qebj>d^fkyKyPhvPbodb^kqS^kaboifm%/4+3)2/+6&yyNFAy..-/0yyWy?i^ab$pBadbJlrkq^fkpyyAy
>To^kdibJlob>bqeboO^vpyKyPhvdr^oaHe^qfb%/5+-)2.+1&yyNFAy..-33yyWy?i^ab$pBadbJlrkq^fkpyyAy
@?lj_Qebj>d^fkyKyCivlsbo@^jm7To^qe_lj_fkdqeboba^ooltp%00)1-&)%03)06&)%01)10&yyNFAy..-/0yyWy?i^ab$pBadbJlrkq^fkpyyRy0/123yyAy
@To^kdibJlob>bqeboO^vpyKyRpbqebTo^kdifkdOlmbql`^mqrob2>bqeboO^vp+yyNFAy..-33yyRy0/365yyWy?i^ab$pBadbJlrkq^fkpyyAy
Q?lj_Qebj>d^fkyKyPhvPbodb^kqS^kaboifm%/4+3)2/+6&yyNFAy..-/0yyWy?i^ab$pBadbJlrkq^fkpyyAy
QTo^kdibJlob>bqeboO^vpyKyPhvdr^oaHe^qfb%/5+-)2.+1&yyNFAy..-33yyWy?i^ab$pBadbJlrkq^fkpyyAy

KDrfab@ljmibqb
]]
end)
