DugisGuideViewer:RegisterGuide("Sha'tari Skyguard Reputation (70+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpqe^qvlr^obibsbi5-)qelrdefq`^k_balkb^qibsbi4-+Qebob^obpbsbo^iobmb^q_ibnrbpqp^kaa^fifbpqe^q`^k_balkbcloobm+y

OPe^qqo^qe@fqvyKyQo^sbiqlPe^qqo^qe@fqv%31+/)1/+.&yyWyPe^qqo^qe@fqvy
>Qeob^qcolj>_lsbyKyVrri^%31+/)1/+.&yyNFAy..-63yyWyPe^qqo^qe@fqvy
@Qeob^qcolj>_lsbyKyPi^v^kv/-DloarkkfLdobpfkqeb?^oofboEfiip%//+-).0+-&yyNFAy..-63yyWyQbolhh^oClobpqy
QQeob^qcolj>_lsbyKyVrri^%31+/)1/+.&yyNFAy..-63yyWyPe^qqo^qe@fqvy
>QlPhbqqfpyKyVrri^%31+/)1/+.&yyNFAy..-65yyWyPe^qqo^qe@fqvy
QQlPhbqqfpyKyPhvPbodb^kqAlovk%31+2)33+2&yyNFAy..-65yyWyQbolhh^oClobpqy
>CfobpLsboPhbqqfpyKyPhvPbodb^kqAlovk%31+2)33+2&yyNFAy..--5yyWyQbolhh^oClobpqy
>TloialcPe^altpyKyPbsbofk%31+.)33+5&yyNFAy..--1yyWyQbolhh^oClobpqy
>ErkdovKbqeboO^vpyKyPhvdr^oaE^kaiboAbbp^h%30+2)32+5&yyNFAy..-60yyWyQbolhh^oClobpqy
@CfobpLsboPhbqqfpyKyPbbhlrqJlkpqolrpH^ifofBddplkqebqlmplcPhbqqfpatbiifkdp^karpbqebPhvdr^oa?i^pqfkd@e^odbplkqebj+%33+1)46+/&yyNFAy..--5yyRy0/1-3yyWyQbolhh^oClobpqy
@TloialcPe^altpyKyObqofbsb3XPe^altArpqZcoljqeb>o^hhl^%36+6)5/+.&yyNFAy..--1yyWyQbolhh^oClobpqy
@ErkdovKbqeboO^vpyKyRpbqebKbqeboO^v@^dbfkqebtllapplrqelc?i^`htfkaI^kafkd^kapi^v?i^`htfkaT^om@e^pbop%34+/)4/+5&%31+3)52+2&yyNFAy..-60yyRy0/501yyWyQbolhh^oClobpqy
>Bp`^mbcoljPhbqqfpyKyPhvdr^oaMofplkbo%3.+/)41+0&%36+-)41+.&%42+.)53+6&yyNFAy..-52yyWyQbolhh^oClobpqy
@Bp`^mbcoljPhbqqfpyKyBp`loqqebPhvdr^oaMofplkboqlp^cbqvyyNFAy..-52yyWyQbolhh^oClobpqy
QCfobpLsboPhbqqfpyKyPhvPbodb^kqAlovk%31+2)33+2&yyNFAy..--5yyWyQbolhh^oClobpqy
QBp`^mbcoljPhbqqfpyKyPhvPbodb^kqAlovk%31+2)33+2&yyNFAy..-52yyWyQbolhh^oClobpqy
QTloialcPe^altpyKyPbsbofk%31+.)33+5&yyNFAy..--1yyWyQbolhh^oClobpqy
QErkdovKbqeboO^vpyKyPhvdr^oaE^kaiboAbbp^h%30+2)32+5&yyNFAy..-60yyWyQbolhh^oClobpqy

>Pb`obqplcqebQ^ilkmofbpqpyKyPhv@ljj^kabo>a^ofp%31+.)33+5&yyNFAy..--2yyWyQbolhh^oClobpqy
RBifufolcPe^altpyKyRpbXBifufolcPe^altpZ+L_q^fkbacoljPbsbofkcloXPe^altArpqZyyRy0/113y
HQ^ilkmofbpqWbiibhyKy%4-+-)41+1&yyNFAy..--2yyNLyQ^ilkmofbpqWbiibhpi^fk7.,.yyWyQbolhh^oClobpqy
HQ^ilkmofbpqFpe^^iyKy%36+.)45+2&yyNFAy..--2yyNLyQ^ilkmofbpqFpe^^ipi^fk7.,.yyWyQbolhh^oClobpqy
>Fpe^^i$p>ij^k^`yKyIllqcoljFpe^^iyyRy0/2/0yyNFAy..-/.y
@Pb`obqplcqebQ^ilkmofbpqpyKyPi^vQ^ilkmofbpqPhfwwfh%36+6)5/+.&yyNFAy..--2yyWyQbolhh^oClobpqy
QPb`obqplcqebQ^ilkmofbpqpyKyPhv@ljj^kabo>a^ofp%31+.)33+5&yyNFAy..--2yyWyQbolhh^oClobpqy
QFpe^^i$p>ij^k^`yKyPhv@ljj^kabo>a^ofp%31+.)33+5&yyNFAy..-/.yyWyQbolhh^oClobpqy
>>k>iivfkIltbo@fqvyKyPhv@ljj^kabo>a^ofp%31+.)33+5&yyNFAy..-/1yyWyQbolhh^oClobpqy
Q>k>iivfkIltbo@fqvyKyOfi^hqebObabbjba%2/+4)/-+6&yyNFAy..-/1yyWyPe^qqo^qe@fqvy
>@lrkqaltkqlAlljyKyOfi^hqebObabbjba%2/+4)/-+6&yyNFAy..-/5yyWyPe^qqo^qe@fqvy
Q@lrkqaltkqlAlljyKyPhv@ljj^kabo>a^ofp%31+.)33+5&yyNFAy..-/5yyWyQbolhh^oClobpqy
>E^wwfh$p?^od^fkyKyE^wwfh%31+/)33+6&yyNFAy..-23yyWyQbolhh^oClobpqy
@E^wwfh$p?^od^fkyKyL_q^fkE^wwfh$pM^`h^db^qefpatbiifkdfkb^pqbokPhbqqfp%41+5)5-+.&yyNFAy..-23yyWyQbolhh^oClobpqy
QE^wwfh$p?^od^fkyKyE^wwfh%31+/)33+6&yyNFAy..-23yyWyQbolhh^oClobpqy
>>Pe^__vAfpdrfpbyKyE^wwfh%31+/)33+6&yyNFAy..-/6yyWyQbolhh^oClobpqy
@>Pe^__vAfpdrfpbyKyRpbqebPe^__v>o^hhl^Afpdrfpbqll_q^fkqeb>asbop^of^i?illaifkbpcoljP^e^^h%34+-)46+4&yyNFAy..-/6yyRy0/41.yyWyQbolhh^oClobpqy
Q>Pe^__vAfpdrfpbyKyE^wwfh%31+/)33+6&yyNFAy..-/6yyWyQbolhh^oClobpqy
>>asbop^of^i?illayKyE^wwfh%31+/)33+6&yyNFAy..552yyWyQbolhh^oClobpqy
@>asbop^of^i?illayKyPrjjlk^kaabcb^qb^`elcqeb1abp`bka^kqp_vrpfkd.-Qfjb*IlpqP`oliipmboabp`bka^kq^qqebPhriiMfib+%3/+-)41+4&%24+.)50+4&%4-+-)50+0&%36+3)41+5&yyNFAy..552yyWyQbolhh^oClobpqy
Q>asbop^of^i?illayKyE^wwfh%31+/)33+6&yyNFAy..552yyWyQbolhh^oClobpqy
>Qbolhh$pAltkc^iiyKyPhv@ljj^kabo>a^ofp%31+.)33+5&yyNFAy..-40yyWyQbolhh^oClobpqy
KEbim++yKyVlrlkivdbqlkb`e^odblkqebXQfjb*ilpqLccbofkdZ^kavlrjfdeqkbbaebimhfiifkdQboolhh+y
@Qbolhh$pAltkc^iiyKyQ^hbqebXQfjb*IlpqLccbofkdZmobm^oba_vE^wwfhqlqebPhriiMfib^qqeb`bkqbolcPhbqqfp^kaprjjlk^kaabcb^qQbolhh+%33+/)44+1&yyNFAy..-40yyWyQbolhh^oClobpqy
QQbolhh$pAltkc^iiyKyPhv@ljj^kabo>a^ofp%31+.)33+5&yyNFAy..-40yyWyQbolhh^oClobpqy

KObmQrok*fkpyKyJlobPe^altArpq)QlhbkplcqebAbp`bka^kqp`^k_balkblsbo^kalsbocloobm+Qboolhhdfsbp2--obmmbohfii^ka`^k_bhfiibajriqfmibqfjbp+Mirpqeb`lrmiblca^fifbplccboba^qPhbqqfp+yyNFAy..-/2y

KDrfab@ljmibqbyKyQebob^ob^`lrmiblcobmb^q^_ibnrbpqpfp?i^ab$pBadbJlrkq^fkpqe^q`^k_balkba^fivcloobm+y

]]
end)
