DugisGuideViewer:RegisterGuide("Sporeggar Reputation (62+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabtfiidllsbo^iiqebnrbpqpkbbabaqldbqqebAfmilj^q>`efbsbjbkq%Bu^iqbatfqeQfj_boj^t)J^d$e^o^kaPmlobdd^o+Lk`b^iiqebnrbpqp^obalkbclo^m^oqf`ri^oc^`qflk)qebkfpgrpqdofkafkdlrqqebobmb^q^_ibarkdblkp,qrok*fkpqldbqqlBu^iqba+Qefpdrfab^pprjbpqe^qvlr^obibsbi5-)_rqqefp`^k_balkb^qibsbi4-^ptbii)fqtfiigrpqq^hbjr`eilkdboql`ljmibqb+y
KIltIbsbiNrbpqpyKyJ^hbprobvlr^obqo^hfkdiltibsbinrbpqpqlj^hbfqb^pfboqlpbbqebnrbpqpdfsbop+y

OW^kd^oj^opeyKyQo^sbiqlW^kd^oj^ope%5/)60&yyWyW^kd^oj^opey

>QebPmlobifkdp$MifdeqyKyC^eppk%.6)31&yyNFAy6406yyWyW^kd^oj^opey
>K^qro^iBkbjfbpyKyC^eppk%.6)31&yyNFAy6410yyWyW^kd^oj^opey
@QebPmlobifkdp$MifdeqyKyIllq.-XJ^qrobPmlobP^`pZtef`e`^k_bclrka^iilsboqebPmt^kfkdDibk%.3)3-&yyNFAy6406yyWyW^kd^oj^opey
@K^qro^iBkbjfbpyKyHfiiqeb?ldIloap^qqebPm^tkfkdDibk%.2)3-&clo3X?ldIloaQbkaofipZyyNFAy6410yyWyW^kd^oj^opey
QQebPmlobifkdp$MifdeqyKyC^eppk%.6)31&yyNFAy6406yyWyW^kd^oj^opey
QK^qro^iBkbjfbpyKyC^eppk%.6)31&yyNFAy6410yyWyW^kd^oj^opey
KKbrqo^itfqePmlobdd^oyKyJ^hbprobvlr^obKbrqo^itfqePmlobdd^o)lqebotfpb`lkqfkrbd^qebofkdXJ^qrobPmlobP^`pZlohfiifkd?ldIloaprkqfivlr^ob+y
>Pmlobdd^oyKyC^eppk%.6)31&yyNFAy66.6yyWyW^kd^oj^opey
QPmlobdd^oyKyJppef$ck)fkPmlobdd^o)grpqkloqe*b^pqlcqebPm^tkfkdDibk%.6)2.&yyNFAy66.6yyWyW^kd^oj^opey
>Dilt`^mJrpeolljpyKyJppef$ck%.6)2.&yyNFAy65-5yyWyW^kd^oj^opey
@Dilt`^mJrpeolljpyKyD^qebo.-XDilt`^mpZtef`e`^k_bclrka^iilsboW^kd^oj^ope)alqov%0-)02&fcvlre^sbmol_ibjpcfkafkdqebjyyNFAy65-5yyWyW^kd^oj^opey
QDilt`^mJrpeolljpyKyJppef$ck%.6)2.&yyNFAy65-5yyWyW^kd^oj^opey
>CboqfibPmlobpyKyDpe^cc%.6+/)16+2&yyNFAy65-3yyWyW^kd^oj^opey
QCboqfibPmlobpyKyDpe^cc%.6+/)16+2&+D^qebo3XCboqfibPmlobpZfcvlrafak$qe^sbqebj^iob^av+Qebvaolmlccpmlob_^qp^kaj^opet^ihbopyyNFAy65-3yyWyW^kd^oj^opey
KCofbkaiv*Pmlobdd^oyKy@ljmibqbbsbovobmb^q^_ibvlr`^krkqfivlr$obcofbkaiv+Vlr`^kqrokfkXDilt`^mpZ)X?ldIloaQbkaofipZ^kaXJ^qrobPmlobp^`pZ+>iiqebpbobmb^qpbkalk`bvlr$obcofbkaiv)plrpbqebjtefibvlr`^kyyNFAy64/3yyWyW^kd^oj^opey
>KltQe^qTb$obCofbkap+++yKyDwerk$qq%.6+2)2-+.&yyNFAy64/3yyWyW^kd^oj^opey
>?ofkdJb>Peor__bovyKyDwerk$qq%.6+2)2-+.&yyNFAy64.2yyWyW^kd^oj^opey
@KltQe^qTb$obCofbkap+++yKyHfii./?illap`^ibPi^sbaofsbop^ka3?illap`^ibBk`e^kqobppbp%/.)1.&%/4)1/&)^kaqebkobqrokqlDwerk$qq+yyNFAy64/3yyWyW^kd^oj^opey
@?ofkdJb>Peor__bovyKy@liib`q2XP^kdrfkbEf_fp`rpZ^kaobqrokqebjqlDwerk$qq^qPmlobdd^ofkW^kd^oj^ope+Qebpb^obclrkafkQebRkabo_ld%2-+0)1.+.&yyNFAy64.2yyWyW^kd^oj^opey
QKltQe^qTb$obCofbkap+++yKyDwerk$qq%.6+2)2-+.&yyNFAy64/3yyWyW^kd^oj^opey
Q?ofkdJb>Peor__bovyKyDwerk$qq%.6+2)2-+.&yyNFAy64.2yyWyW^kd^oj^opey

K@lkqfkrb++yKytfqeqebcliiltfkdobmb^q^_ibnrbpqrkqfiBu^iqba+y
>KltQe^qTb$obPqfiiCofbkap+++yKyDwerk$qq%.6+2)2-+.&yyNFAy64/4yyWyW^kd^oj^opey
>?ofkdJb>klqeboPeor__bovyKyDwerk$qq%.6+2)2-+.&yyNFAy64.1yyWyW^kd^oj^opey
>JlobCboqfibPmlobpyKyDpe^cc%.6+/)16+2&yyNFAy65-4yyWyW^kd^oj^opey

KDrfab@ljmibqb

]]
end)
