DugisGuideViewer:RegisterGuide("The Consortium Reputation (70+)", nil, "Horde", "E", function()
return [[
AAA

OK^do^kayKyQo^sbiqlK^do^ka%2.+.)36+/&yyWyK^do^kay
>Qeb@lkploqfrjKbbapVlryKy@lkploqfrjOb`orfqbo%2.+5)01+5&yyNFAy66.0yyWyK^do^kay
O>bofpI^kafkdyKyArbplrqelcPrkpmofkd%0.)24&+Cliiltqebol^atbpqqebkplrqe)loorkqeorE^i^^fcfqfpk$qltkba_vqeb^iif^k`b+T^q`elrqcloqebm^qoliplkqebj^fkol^ayyNFAy66/2yyWyK^do^kay
QQeb@lkploqfrjKbbapVlryKyDbweb%0.+1)24+4&yyNFAy66.0yyWyK^do^kay
>J^qqboplcPb`rofqvyKyWbofa%0-+5)25+/&yyNFAy66/2yyWyK^do^kay
>Pqb^ifkdcoljQefbsbpyKyDbweb%0.+1)24+4&yyNFAy655/yyWyK^do^kay
>D^s^$ufyKyWbofa%0-+5)25+/&yyNFAy66--yyWyK^do^kay
>>Eb^aCriilcFslovyKyPe^aobh%0.+4)23+5&yyNFAy66.1yyWyK^do^kay

@>Eb^aCriilcFslovyKyHfii^kvTfiaBibhhvlrpbbclo0uXM^folcFslovQrphpZyyNFAy66.1yyWyK^do^kay
@D^s^$ufyKyHfiiD^s^$uflkqlmlc^efiib^pqlcLper$drk%10)41&yyNFAy66--yyWyK^do^kay
@Pqb^ifkdcoljQefbsbpyKyDbq.-XLper$drk@ovpq^iCo^djbkqpZaolmmba_vSfo$^^kfO^fabop^ka>o`^kfpqp^olrka%01)30&+Vlr`^k^iplillqqebjlccqebdolrkafkqefp^ob^yyNFAy655/yyWyK^do^kay
@J^qqboplcPb`rofqvyKyHfii5Slfapm^tk^olrka%06)30&yyNFAy66/2yyWyK^do^kay

QJ^qqboplcPb`rofqvyKyWbofa%0-+5)25+/&yyNFAy66/2yyWyK^do^kay
QPqb^ifkdcoljQefbsbpyKyDbweb%0.+1)24+4&yyNFAy655/yyWyK^do^kay
QD^s^$ufyKyWbofa%0-+5)25+/&yyNFAy66--yyWyK^do^kay
Q>Eb^aCriilcFslovyKyPe^aobh%0.+4)23+5&yyNFAy66.1yyWyK^do^kay

KCofbkaivyKyQebCliiltfkdnrbpqfp^s^fi^_ib^qCofbkaivy
>L_pfaf^kT^o_b^apyKyDbweb%0.+1)24+4&yyNFAy6560yyWyK^do^kay
>L_pfaf^kT^o_b^apyKy@liib`q.-XL_pfaf^kT^o_b^apZcoljLdobpfkK^do^ka%2.+1)24+0&%1-+4)0.+0&yyNFAy6560yyWyK^do^kay
QL_pfaf^kT^o_b^apyKyDbweb%0.+1)24+4&yyNFAy6560yyWyK^do^kay

KK^do^kaObmb^q^_ibNrbpqpyKyJlob@ovpq^iCo^djbkqp^kaJlobEb^apCriilcFslov*rmqlcofbkaiv)^kaJlobL_pfaf^kT^o_b^ap*rmqlbu^iqba+y

O>ob^2/yKyQo^sbiql>ob^2/%/.+5)22+3&yyNFAy.-01/yyWyKbqebopqlojy

>>ppfpqfkdqeb@lkploqfrjyKyFcvlr^iob^av^``bmqba@lkploqfrj@ovpq^i@liib`qflkaolmfqql^``bmqqefp)Pmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy.-/31yyWyKbqebopqlojy
Q>ppfpqfkdqeb@lkploqfrjyKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/31yyWyKbqebopqlojy
>@lkploqfrj@ovpq^i@liib`qflkyKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/32yyWyKbqebopqlojy
@@lkploqfrj@ovpq^i@liib`qflkyKyHfiiMbkq^qe^olk^q>ohilkOrfkp%1/+2)4/+2&yyIy/55/6yyNFAy.-/32yyWyKbqebopqlojy
Q@lkploqfrj@ovpq^i@liib`qflkyKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/32yyWyKbqebopqlojy
>>Eb^mlcBqebob^ipyKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/3/yyWyKbqebopqlojy
@>Eb^mlcBqebob^ipyKyHfiiqebBqebob^ip^qqebEb^m%/4+-)46+-&yyNFAy.-/3/yyWyKbqebopqlojy
Q>Eb^mlcBqebob^ipyKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/3/yyWyKbqebopqlojy
>T^om*O^faboKbp^^ayKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/-2yyWyKbqebopqlojy
@T^om*O^faboKbp^^ayKyHfiiT^om*O^faboKbp^^a%/5+/)46+2&yyNFAy.-/-2yyWyKbqebopqlojy
>Aofgv^KbbapVlroEbimyKyD^eorg%13+4)24+-&yyNFAy.-0..yyWyKbqebopqlojy
>Ork^Af^dklpqf`yKyJbeoa^a%13+2)23+2&yyNFAy.-1.4yyWyKbqebopqlojy
>KbtLmmloqrkfqfbpyKyJbeoa^a%13+2)23+2&yyNFAy.-015yyWyKbqebopqlojy
QAofgv^KbbapVlroEbimyKyAofgv^%15+-)31+-&yyNFAy.-0..yyWyKbqebopqlojy
>P^_lq^dbqebT^om*D^qbyKyAofgv^%15+-)31+-&yyNFAy.-0.-yyWyKbqebopqlojy
@P^_lq^dbqebT^om*D^qbyKyBp`loqAofgv^qlqebt^om*d^qb^qFks^pflkMlfkq7Abpqolvbo)^kapbbqlfqqe^qebfphbmqp^cbtefibeb^qqbjmqpqlp^_lq^dbfq+yyNFAy.-0.-yyWyKbqebopqlojy
@Ork^Af^dklpqf`yKy@liib`qcoljqebAf^dklpqf`Bnrfmjbkq^q%15+/)22+-&yyNFAy.-1.4yyWyKbqebopqlojy
@KbtLmmloqrkfqfbpyKy@liib`qcoljqebFslov?bii^olrkaqebaljb%12+-)20+0&yyNFAy.-015yyWyKbqebopqlojy
QKbtLmmloqrkfqfbpyKyJbeoa^a%13+2)23+2&yyNFAy.-015yyWyKbqebopqlojy
QOrk^Af^dklpqf`yKyJbeoa^a%13+2)23+2&yyNFAy.-1.4yyWyKbqebopqlojy
>Ab^iTfqeqebP^_lqbropyKyJbeoa^a%13+2)23+2&yyNFAy.-1.5yyWyKbqebopqlojy
QT^om*O^faboKbp^^ayKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/-2yyWyKbqebopqlojy
>Obnrbpqclo>ppfpq^k`byKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/33yyWyKbqebopqlojy
QObnrbpqclo>ppfpq^k`byKyD^eorg%13+4)24+-&yyNFAy.-/33yyWyKbqebopqlojy
QP^_lq^dbqebT^om*D^qbyKyD^eorg%13+4)24+-&yyNFAy.-0.-yyWyKbqebopqlojy
>OfdeqcriObmlppbppflkyKyD^eorg%13+4)24+-&yyNFAy.-/34yyWyKbqebopqlojy

@OfdeqcriObmlppbppflkyKy@liib`qebProsbvfkdBnrfmjbkqcoljqeb_lubp^olrka%25+6)32+6&yyNFAy.-/34yyWyKbqebopqlojy

QOfdeqcriObmlppbppflkyKyD^eorg%13+4)24+-&yyNFAy.-/34yyWyKbqebopqlojy
>>k>rafbk`btfqeqebMofk`byKyD^eorg%13+4)24+-&yyNFAy.-/35yyWyKbqebopqlojy
@Ab^iTfqeqebP^_lqbropyKyHfii?^o_p`^ib@ol`lifphp^qqebi^hbfkqebB`l*Aljb%13+1)21+3&yyNFAy.-1.5yyWyKbqebopqlojy
QAb^iTfqeqebP^_lqbropyKyJbeoa^a%13+2)23+2&yyNFAy.-1.5yyWyKbqebopqlojy
>QlqebPqlojpmfobyKyJbeoa^a%13+2)23+2&yyNFAy.-1/0yyWyKbqebopqlojy

OQebPqlojpmfobyKyCliiltqebol^alrqqlqeb_fddboaljb%1.)0/&yyNFAy.-1/3yyWyKbqebopqlojy
QQlqebPqlojpmfobyKyDe^_^o%10+2)02+.&yyNFAy.-1/0yyWyKbqebopqlojy
>Af^dklpfp7@ofqf`^iyKyDe^_^o%10+2)02+.&yyNFAy.-1/1yyWyKbqebopqlojy
>ProsbvfkdqebOrfkpyKyWbmevoflk%11+4)01+6&yyNFAy.-002yyWyKbqebopqlojy
>QebJfkflkplc@rirqe^pyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-003yyWyKbqebopqlojy
>CbiOb^sbop)KlQe^khpyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-522yyWyKbqebopqlojy
>FkPb^o`elcC^o^eifqbyKyWr_bkBidbkr_f%11)03&yyNFAy.-/6-yyWyKbqebopqlojy
Q>k>rafbk`btfqeqebMofk`byKyFj^dblcKburp*Mofk`bE^o^j^a%12+5)03+-&yyNFAy.-/35yyWyKbqebopqlojy
>Qof^kdri^qflkMlfkqLkbyKyFj^dblcKburp*Mofk`bE^o^j^a%12+5)03+-&yyNFAy.-/36yyWyKbqebopqlojy

C>ob^2/yKyDobkkfh%12+0)01+6&yyNFAy.-/14yyWyKbqebopqlojy

@Af^dklpfp7@ofqf`^iyKy>qqebdbkbo^qloqlqebkloqeb^pq%14+3)/3+5&yyRy/65-0yyNFAy.-1/1yyWyKbqebopqlojy
@ProsbvfkdqebOrfkpyKy>qqeborfkpkloqeb^pq)grpqlrqpfabqebaljb+J^ohbop^ob^q%2.+-)/-+-&)%21+3)//+5&)%22+5)/-+-&yyRy/6112yyNFAy.-002yyWyKbqebopqlojy
@FkPb^o`elcC^o^eifqbyKyD^qebo1mfb`bplcO^tC^o^eifqb%12+3).6+3&yyNFAy.-/6-yyWyKbqebopqlojy
@QebJfkflkplc@rirqe^pyKyCfkaqebobnrfobajl_p^olrka%2.+1)/0+4&yyNFAy.-003yyWyKbqebopqlojy
@CbiOb^sbop)KlQe^khpyKyTbpq^qClodb@^jm7L_ifsflk%04+-)/5+-&)hfiiJbhdfkbbopclo2d^p)rpblklkblcqebob^sbop%02+-)/5+-&)%03+-)/2+-&)%04+-)/2+-&+VlrlkivkbbaqlalqefplkLKBob^sboyyNFAy.-522yyWyKbqebopqlojy

QAf^dklpfp7@ofqf`^iyKyDe^_^o%10+2)02+.&yyNFAy.-1/1yyWyKbqebopqlojy
>QbpqfkdqebMolqlqvmbyKyDe^_^o%10+2)02+.&yyNFAy.-10-yyWyKbqebopqlojy
QProsbvfkdqebOrfkpyKyWbmevoflk%11+4)01+6&yyNFAy.-002yyWyKbqebopqlojy
QQebJfkflkplc@rirqe^pyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-003yyWyKbqebopqlojy
QCbiOb^sbop)KlQe^khpyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-522yyWyKbqebopqlojy
QFkPb^o`elcC^o^eifqbyKyWr_bkBidbkr_f%11)03&yyNFAy.-/6-yyWyKbqebopqlojy
>EfqqfkdqebJlqeboilabyKyWr_bkBidbkr_f%11)03&yyNFAy.-/60yyWyKbqebopqlojy
>Qeb?bpqAbcbkpbyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-523yyWyKbqebopqlojy

@Qeb?bpqAbcbkpbyKyKloqetbpq^qClodb?^pb7Dbebkk^%06+2)/0+3&yyNFAy.-523yyWyKbqebopqlojy
@EfqqfkdqebJlqeboilabyKyPi^v@o^dph^^o%16+1).5+/&^kal_q^fk^C^o^eifqb@lob+yyNFAy.-/60yyWyKbqebopqlojy
QQbpqfkdqebMolqlqvmbyKyQ^pe^o%11+4).1+2&yyNFAy.-10-yyWyKbqebopqlojy
>>ii@ib^oyKyQ^pe^o%11+4).1+2&yyNFAy.-103yyWyKbqebopqlojy
@>ii@ib^oyKyHfiiqebO^mqlop^olrka%13+2)./+6&yyNFAy.-103yyWyKbqebopqlojy
Q>ii@ib^oyKyQ^pe^o%11+4).1+2&yyNFAy.-103yyWyKbqebopqlojy
>Pr``bppyKyQ^pe^o%11+4).1+2&yyNFAy.-11-yyWyKbqebopqlojy
QPr``bppyKyDe^_^o%10+2)02+.&yyNFAy.-11-yyWyKbqebopqlojy
QEfqqfkdqebJlqeboilabyKyWr_bkBidbkr_f%11)03&yyNFAy.-/60yyWyKbqebopqlojy
QQeb?bpqAbcbkpbyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-523yyWyKbqebopqlojy
>QbibmloqQefpyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-524yyWyKbqebopqlojy
@QbibmloqQefpyKy?^`h^qClodb?^pb7Dbebkk^)qbibmloqbop^q%06)/-&)%1.).5&)%11)/-&yyRy0.345yyNFAy.-524yyWyKbqebopqlojy
QQbibmloqQefpyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-524yyWyKbqebopqlojy

>>Klq*Pl*JlabpqMolmlp^iyKyTfkaQo^aboJ^ofa%25+5)0.+-&yyNFAy.-/4-yyWyKbqebopqlojy
>Bib`qol*Pel`hDllakbppyKyObpb^o`eboK^srra%26+0)0/+2&yyNFAy.-1..yyWyKbqebopqlojy
>QebBqebobrjyKy@ljj^kabo>jbbo%26+2)0/+0&yyNFAy.-006yyWyKbqebopqlojy
>Ob`fmbcloAbpqor`qflkyKyMolcbpploA^_fof%3-+.)0.+5&yyNFAy.-104yyWyKbqebopqlojy
>@^mq^fkQvo^ifrpyKyCibpeE^kaiboSfofafrp%3-+.)0/+2&yyNFAy.-1//yyWyKbqebopqlojy

RRpbXK^srra$p@lk`l`qflkZyRy/6404yyWyKbqebopqlojy
HSlfaT^pqbpyKy>ilkdqebofadb%22+4)10+3&yyNFAy.-1..yyNLySlfaT^pqbDil_ribpi^fk70-,0-yyNFAy.-1..yyWyKbqebopqlojy
@QebBqebobrjyKyCfkaBqebobrjjl_p^olrka%24+0)03+6&^ka@^mq^fkWls^u^q%23+5)04+0&yyNFAy.-006yyWyKbqebopqlojy
QQebBqebobrjyKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-006yyWyKbqebopqlojy
>BqebobrjA^q^yKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-051yyWyKbqebopqlojy
@BqebobrjA^q^yKyCfkaqebBqebobrjA^q^@biiqlqebPlrqe%22+5)06+6&yyNFAy.-051yyWyKbqebopqlojy
QBqebobrjA^q^yKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-051yyWyKbqebopqlojy
>Mlqbkqf^iclo?o^fkA^j^db:EfdeyKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-052yyWyKbqebopqlojy
@Mlqbkqf^iclo?o^fkA^j^db:EfdeyKyHfiiBqebobrjObi^vp^olrka%22+5)1/+0&)aofkhqebbppbk`bqebvaolm)qebkhfiiqebA^q^TvojifkdpyyRy/615/yyNFAy.-052yyWyKbqebopqlojy
QMlqbkqf^iclo?o^fkA^j^db:EfdeyKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-052yyWyKbqebopqlojy
>Bp`^mbcoljqebPq^dfkdDolrkapyKy@^mqrobaMolqb`qlo^qbS^kdr^oa%24+-)04+4&+Vlre^sbqlebimefjabcb^qqebdi^af^qlocloqebnrbpqqlpeltrm+yyNFAy.-1/2yyWyKbqebopqlojy
@Bp`^mbcoljqebPq^dfkdDolrkapyKyBp`loq@^mqrobaMolqb`qlo^qbS^kdr^oaMolqb`qlo^qbT^q`eMlpq+yyNFAy.-1/2yyWyKbqebopqlojy
QBp`^mbcoljqebPq^dfkdDolrkapyKy@ljj^kabo>jbbo%26+1)0/+0&yyNFAy.-1/2yyWyKbqebopqlojy
>P*>*?*L*Q*>*D*ByKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-1-2yyWyKbqebopqlojy
@P*>*?*L*Q*>*D*ByKyHfiiBqebobrj>o`elkp^kaBqebobrjLsboiloap^olrka%23+3)1/+4&yyNFAy.-1-2yyWyKbqebopqlojy
QP*>*?*L*Q*>*D*ByKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-1-2yyWyKbqebopqlojy
>AbifsbofkdqebJbpp^dbyKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-1-3yyWyKbqebopqlojy
@AbifsbofkdqebJbpp^dbyKy@ljmibqbqebBp`loqNrbpqyyNFAy.-1-3yyWyKbqebopqlojy
QAbifsbofkdqebJbpp^dbyKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-1-3yyWyKbqebopqlojy
>Kburp*HfkdP^ie^a^^oyKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-1-5yyWyKbqebopqlojy
@Kburp*HfkdP^ie^a^^oyKyRpbqebMolqb`qlo^qbAfpormqloql_ofkdaltkP^ie^a^^o$pclo`bcfbiap^kaqebkabpqolvKburp*HfkdP^ie^a^^o%20+4)1/+0&yyNFAy.-1-5yyWyKbqebopqlojy
>QebElooloplcMliirqflkyKyPi^v@lkdb^ibaSlfaEloolo%21+5)11+.&^kadbqqebXSf^ilcSlfaElooloLlwbZyyNFAy.-1.0yyRy/6405yyWyKbqebopqlojy
QKburp*HfkdP^ie^a^^oyKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-1-5yyWyKbqebopqlojy

@@^mq^fkQvo^ifrpyKyHfiiT^oabkF`lpel`h%21+3)1-+.&qlqebplrqetbpqcloefphbv)qebklmbkqebmofplk_befkaKburp*HfkdP^ie^a^^o%20+-)1.+-&yyNFAy.-1//yyWyKbqebopqlojy
>QebCibpeIfbp+++yKy>dbkq>o^ubp%26+1)12+.&yyNFAy.-012yyWyKbqebopqlojy
@QebCibpeIfbp+++yKyFkqebjfkb%3.+-)12+-&)>``bppPe^cqWblk+Hbbmibcq^pvlrbkqbo+Rpbqebifdeqbolkqeb`lompbp)_rqalk$qdbqqll`ilpb+yyRy/6140yyNFAy.-012yyWyKbqebopqlojy
>>o`lkrpqebFkp^qf^_ibyKy>dbkqV^*pfu%3-+6)1.+3&yyNFAy.-020yyWyKbqebopqlojy
@>Klq*Pl*JlabpqMolmlp^iyKyCfkaqebXQbibmloqboMltboM^`hZ^q%3-+6)1.+2&yyNFAy.-/4-yyWyKbqebopqlojy
@>o`lkrpqebFkp^qf^_ibyKyDl_^`hlrqqlqebbkqo^k`b)qebkeb^afkpq^vfkdofdeq+Hfii>o`lkrpfkqeb_fdollj%3-+.)1-+0&yyNFAy.-020yyWyKbqebopqlojy
QQebCibpeIfbp+++yKy>dbkq>o^ubp%26+1)12+.&yyNFAy.-012yyWyKbqebopqlojy

RRpbXK^srra$p@lk`l`qflkZyRy/6404yyNFAy.-1..yyWyKbqebopqlojy
@Bib`qol*Pel`hDllakbppyKyHfii0-PibbmfkdPiradbDil_rib^olrka%32+-)04+4&yyNFAy.-1..yyWyKbqebopqlojy
@Ob`fmbcloAbpqor`qflkyKySlfapeofbhbop^kaSlfato^fqep^olrka^kafkpfab^ka^olrkaqebj^k^clodb%3/+-)1-+2&yyNFAy.-104yyWyKbqebopqlojy
@Qof^kdri^qflkMlfkqLkbyKyRpbqebabsf`bqebkcfkaqebj^oh%33+4)00+5&yyRy/563/yyNFAy.-/36yyWyKbqebopqlojy

Q>Klq*Pl*JlabpqMolmlp^iyKyFj^dblcTfkaQo^aboJ^ofa+>qqebelildo^me%4.+/)06+-&yyNFAy.-/4-yyWyKbqebopqlojy
>DbqqfkdAltkql?rpfkbppyKyFj^dblcTfkaQo^aboJ^ofa+>qqebelildo^me%4.+/)06+-&+Vlr`^k$qalqefpnrbpqfcvlr$sbdlqefdeKbqebotfkdc^`qflkyyNFAy.-/4.yyWyKbqebopqlojy
@DbqqfkdAltkql?rpfkbppyKy@liib`qcoljKbqeboAo^dlkp^kaAo^hbp^olrka%4/+3)05+4&yyNFAy.-/4.yyWyKbqebopqlojy
QDbqqfkdAltkql?rpfkbppyKyPeolrabaCfdrob%4-+6)05+6&yyNFAy.-/4.yyWyKbqebopqlojy
>Cloj^iFkqolar`qflkpyKyPeolrabaCfdrob%4-+6)05+6&+Vlr`^k$qalqefpnrbpqfcvlr$sbdlqefdeKbqebotfkdc^`qflkyyNFAy.-/5.yyWyKbqebopqlojy
QCloj^iFkqolar`qflkpyKyQvof%4.+/)02+/&yyNFAy.-/5.yyWyKbqebopqlojy
>>MoljfpfkdPq^oqyKyQvof%4.+/)02+/&+Vlr`^k$qalqefpnrbpqfcvlr$sbdlqefdeKbqebotfkdc^`qflkyyNFAy.-/4/yyWyKbqebopqlojy
@>MoljfpfkdPq^oqyKyD^qebo.2XKbqeboAo^dlkhfkBddZcolj^olrka%4/+2)04+0&yyNFAy.-/4/yyWyKbqebopqlojy
Q>MoljfpfkdPq^oqyKyQvof%4.+/)02+/&yyNFAy.-/4/yyWyKbqebopqlojy
>Qolr_ibpljbAfpqo^`qflkpyKyQvof%4.+/)02+/&+Vlr`^k$qalqefpnrbpqfcvlr$sbdlqefdeKbqebotfkdc^`qflkyyNFAy.-/40yyWyKbqebopqlojy

QOb`fmbcloAbpqor`qflkyKyMolcbpploA^_fof%3-+.)0.+5&yyNFAy.-104yyWyKbqebopqlojy
>LkKbqebovTfkdpyKyMolcbpploA^_fof%3-+.)0.+5&yyNFAy.-105yyWyKbqebopqlojy
Q@^mq^fkQvo^ifrpyKyCibpeE^kaiboSfofafrp%3-+.)0/+2&yyNFAy.-1//yyWyKbqebopqlojy
QBib`qol*Pel`hDllakbppyKyObpb^o`eboK^srra%26+0)0/+2&yyNFAy.-1..yyWyKbqebopqlojy
QQebElooloplcMliirqflkyKyObpb^o`eboK^srra%26+0)0/+2&yyNFAy.-1.0yyWyKbqebopqlojy
Q>o`lkrpqebFkp^qf^_ibyKy@ljj^kabo>jbbo%26+2)0/+0&yyNFAy.-020yyWyKbqebopqlojy
QQof^kdri^qflkMlfkqLkbyKyAb^iboE^wwfk%25+1)0.+1&yyNFAy.-/36yyWyKbqebopqlojy
>Qof^kdri^qflkMlfkqQtlyKyAb^iboE^wwfk%25+1)0.+1&yyNFAy.-/42yyWyKbqebopqlojy

@Qolr_ibpljbAfpqo^`qflkpyKyIrobTfkaQo^aboJ^ofa%25+5)0.+-&^t^v^kahfiiefjyyNFAy.-/40yyWyKbqebopqlojy
@LkKbqebovTfkdpyKyQ^ihqlqebkbqeboao^hb^kaq^hb^ofab+Pm^jqeb_lj_tebkvlr^oblsboqebj^k^clodbyyRy/6445yyNFAy.-105yyWyKbqebopqlojy
QLkKbqebovTfkdpyKyMolcbpploA^_fof%3-+.)0.+5&yyNFAy.-105yyWyKbqebopqlojy
>Afjbkpfrpqeb>ii*AbslrofkdyKyMolcbpploA^_fof%3-+.)0.+5&yyNFAy.-106yyWyKbqebopqlojy
QQolr_ibpljbAfpqo^`qflkpyKyQvof%4.+/)02+/&yyNFAy.-/40yyWyKbqebopqlojy
KQ^ihql@^mq^fkP^bbayKy@^mq^fkP^bba%3-+0)0/+4&yyNFAy.-106yyNLyPmb^hql@^mq^fkP^bba7.,.yyWyKbqebopqlojy
@Afjbkpfrpqeb>ii*AbslrofkdyKyCliilt@^mq^fkP^bba^kaefp^ojvqlJ^k^clodbRiqofp^kahfiiAfjbkpfrpqeb>ii*AbslrofkdyyNFAy.-106yyWyKbqebopqlojy
QAfjbkpfrpqeb>ii*AbslrofkdyKyMolcbpploA^_fof%3-+.)0.+5&yyNFAy.-106yyWyKbqebopqlojy

QQolr_ibpljbAfpqo^`qflkpyKyQvof%4.+/)02+/&yyNFAy.-/40yyWyKbqebopqlojy

>Ab^ifkdtfqeqebClobj^kyKyTfkaQo^aboQrirj^k%01+3)04+6&yyNFAy.-0.4yyWyKbqebopqlojy
>Kbrqo^ifwfkdqebKbqeboj^k`bopyKyKbqebo*Pq^ihboL^wri%01+3)04+5&yyNFAy.-0.2yyWyKbqebopqlojy

QAb^ifkdtfqeqebClobj^kyKyClobj^kPrkaltk%/3+1)1/+2&yyNFAy.-0.4yyWyKbqebopqlojy
>Ab^ifkdtfqeqebLsboj^pqboyKyClobj^kPrkaltk%/3+1)1/+2&yyNFAy.-0.5yyWyKbqebopqlojy
@Ab^ifkdtfqeqebLsboj^pqboyKyHfiiLsboj^pqboDofkad^oo+Altkqebqrkkbi)ofdeqqebkibcq%/3+5)02+6&yyNFAy.-0.5yyWyKbqebopqlojy
@Kbrqo^ifwfkdqebKbqeboj^k`bopyKyHfiiqebKbqeboj^k`boplrqpfabqebjfkb^olrka%/5+5)05+2&yyNFAy.-0.2yyWyKbqebopqlojy

@Qof^kdri^qflkMlfkqQtlyKyRpbqebXQof^kdri^qflkAbsf`bZ^kacfkaqebj^ohkb^oJ^k^clodb>o^%/5+6)1.+/&yyRy/6-.5yyNFAy.-/42yyWyKbqebopqlojy
QQof^kdri^qflkMlfkqQtlyKyTfkaQo^aboQrirj^k%01+3)04+6&yyNFAy.-/42yyWyKbqebopqlojy
QAb^ifkdtfqeqebLsboj^pqboyKyTfkaQo^aboQrirj^k%01+3)04+6&yyNFAy.-0.5yyWyKbqebopqlojy
>CriiQof^kdibyKyTfkaQo^aboQrirj^k%01+3)04+6&yyNFAy.-/43yyWyKbqebopqlojy
QKbrqo^ifwfkdqebKbqeboj^k`bopyKyKbqebo*Pq^ihboL^wri%01+3)04+5&yyNFAy.-0.2yyWyKbqebopqlojy
@CriiQof^kdibyKyHfii@rirqe^p%20+1)/.+1&^kaob`lsboqeb>q^$j^i@ovpq^iyyNFAy.-/43yyWyKbqebopqlojy
QCriiQof^kdibyKyTfkaQo^aboQrirj^k%01+3)04+6&yyNFAy.-/43yyWyKbqebopqlojy

KObmrq^qflkCloBu^iqbayKyQebob^obpbsbo^iobmb^q^_ibnrbpqplovlr`^korkEbolf`J^k^Qlj_pclo^_lrq/1--obmrq^qflkmboorky
KL_pfaf^kT^o_b^apyKy.-uXL_pfaf^kT^o_b^apZaolmmbacolj^kvLdobpfkK^do^ka%13)/-&%42)32&clo/2-obm+QrokqebjfkqlDbweb%0.+1)24+4&yyWyK^do^kay
KW^uufpFkpfdkf^yKy.-uXW^uufpFkpfdkf^ZclrkacoljW^uufpob_bipfkkbqebopqloj%/6)43&clo/2-obm+QrokqebjfkqlKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyWyKbqebopqlojy
KDrfab@ljmibqb

]]
end)
