DugisGuideViewer:RegisterGuide("The Kalu'ak Reputation (80+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpqe^qvlr^ob^qib^pq5-+Qebpbnrbpqp`^k_balkb^qibppqe^k5-)_rqjfdeqq^hbilkdboqlal+y

OEltifkdCgloayKyQo^sbiqlEltifkdCgloa%0/+0)13+5&yyNFAy..240yyWyEltifkdCgloay
>QebAb^aOfpbyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2-1yyWyEltifkdCgloay
@QebAb^aOfpbyKyC^oqlqebplrqeb^pq^qPefbiaEfii+Sfpfqb^`edo^sbclo^`irb7Cbkdfo%24+4)44+2&)Olafk%26+/)43+6&)Fprialc%26+5)46+1&)Tfka^k%3.+6)5-+-&yyNFAy..2-1yyWyEltifkdCgloay
QQebAb^aOfpbyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2-1yyWyEltifkdCgloay
>Biabo>qrfh^kaH^j^dr^yKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2-4yyWyEltifkdCgloay
QBiabo>qrfh^kaH^j^dr^yKyBiabo>qrfh%/2+-)24+-&yyNFAy..2-4yyWyEltifkdCgloay
cH^j^dr^yKyHfmQo^tiphfm%/1+4)24+6&yyNFAy..2-5yyWyEltifkdCgloay
>DobwwfuPmfkaibpk^myKyBiabo>qrfh%/2+-)24+-&yyNFAy..2-5yyWyEltifkdCgloay
>CbbafkdqebProsfslopyKyBiabo>qrfh%/2+-)24+-&yyNFAy..123yyWyEltifkdCgloay
@CbbafkdqebProsfslopyNFAy..123yyKy>iilsboqebfpi^ka^olrka%0/+2)33+/&yyWyEltifkdCgloay
QCbbafkdqebProsfslopyKyBiabo>qrfh%/2+-)24+-&yyNFAy..123yyWyEltifkdCgloay
>>ojfkdH^j^dr^yKyBiabo>qrfh%/2+-)24+-&yyNFAy..124yyWyEltifkdCgloay
@>ojfkdH^j^dr^yNFAy..124yyKyIlqplkqebkloqebokm^oqlcqebfpi^ka^olrka%/3+-)34+-&yyWyEltifkdCgloay
Q>ojfkdH^j^dr^yKyBiabo>qrfh%/2+-)24+-&yyNFAy..124yyWyEltifkdCgloay
>>sbkdbFph^^iyKyBiabo>qrfh%/2+-)24+-&yyNFAy..125yyWyEltifkdCgloay
QDobwwfuPmfkaibpk^myKyDobwwfuPmfkaibpk^m%/0+.)3/+4&yyNFAy..2-5yyWyEltifkdCgloay
>Pqobbq@obayKyDobwwfuPmfkaibpk^m%/0+.)3/+4&yyNFAy..2-6yyWyEltifkdCgloay
QPqobbq@obayKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2-6yyWyEltifkdCgloay
>P`llaibpyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2.-yyWyEltifkdCgloay
@P`llaibpyNFAy..2.-yyKyGrpqlccpelobqlqebplrqe^olrka%05+-)51+-&)grpqt^fqcloeboqlptfj^olrkayyWyEltifkdCgloay
QP`llaibpyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2.-yyWyEltifkdCgloay
>QebPq^cclcPqloj$pCrovyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2..yyWyEltifkdCgloay
>QebColwbkEb^oqlcFprialcyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2./yyWyEltifkdCgloay
>QebIlpqPefbialcqeb>bpfofqbpyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2.6yyWyEltifkdCgloay
>Qeb>k`fbkq>ojlolcqebHs^iafoyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..234yyWyEltifkdCgloay
@Qeb>k`fbkq>ojlolcqebHs^iafoyNFAy..234yyKyElm^_lj_boofabkb^oqebpelob%03+-)5.+3&+Eb^aaltkfkqlqebelialcqebpefm)qebkq^hbqeb_lj_bo_^`hyyWyEltifkdCgloay
>Pt^__fk$Pl^myKyP`rqqibColpqmolt%04+4)46+2&yyNFAy..136yyWyEltifkdCgloay
@Pt^__fk$Pl^myNFAy..136yyKyHfii?fdOlv)plrqetbpqlcqeblqebopb^iflkp%0.+3)44+2&yyWyEltifkdCgloay
QQebIlpqPefbialcqeb>bpfofqbpyKy@^mq^fkBiifp%04+6)41+4&yyNFAy..2.6yyWyEltifkdCgloay
>JrqfkvlkqebJbo`vyKy@^mq^fkBiifp%04+6)41+4&yyNFAy..2/4yyWyEltifkdCgloay
@JrqfkvlkqebJbo`vyNFAy..2/4yyKyOb`lsbo2X?^oobiplc?i^pqfkdMltaboZaltkfkqebpefm$peliayyWyEltifkdCgloay
QJrqfkvlkqebJbo`vyKy@^mq^fkBiifp%04+6)41+4&yyNFAy..2/4yyWyEltifkdCgloay
>Ploilc$p?llqvyKy@^mq^fkBiifp%04+6)41+4&yyNFAy..2/6yyWyEltifkdCgloay
@Ploilc$p?llqvyNFAy..2/6yyKyTebkqebpefmdlbpkb^opelob)rpbqeb`^kklk^qqeblqebobkalcqebpefm)qebkptfjqlpelob^kado^_XPloilc$p?llqvZ^olrka%1.)40&yyWyEltifkdCgloay
QPloilc$p?llqvyKy@^mq^fkBiifp%04+6)41+4&yyNFAy..2/6yyWyEltifkdCgloay
>QebPefbialcqeb>bpfofqbpyKy@^mq^fkBiifp%04+6)41+4&yyNFAy..20-yyWyEltifkdCgloay
QPt^__fk$Pl^myKyP`rqqibColpqmolt%04+4)46+2&yyNFAy..136yyWyEltifkdCgloay
@QebColwbkEb^oqlcFprialcyNFAy..2./yyKyKb^otebobqeb_b^opm^tkp%0/+1)45+5&yyWyEltifkdCgloay
@>sbkdbFph^^iyNFAy..125yyKyLkqebb^pqpfablcqebfpi^ka%00+6)30+3&+RpbqebXEloklcH^j^dr^ZfcvlrkbbaqlyyRy03444yyWyEltifkdCgloay
@QebPq^cclcPqloj$pCrovyNFAy..2..yyKyFkqebelialcqebpefm%02+-)31+-&+Pkb^hm^pqqebbifqbtebkebeb^aplkqlqebrmmbo_ltlcqebpefmyyWyEltifkdCgloay
Q>sbkdbFph^^iyKyBiabo>qrfh%/2+-)24+-&yyNFAy..125yyWyEltifkdCgloay
>Qo^sbiqlJl^$hfE^o_loyKy>krkf^n%/1+3)25+5&yyNFAy./..5yyWyEltifkdCgloay
>QebT^vqlEfpEb^oq+++yKy>krkf^n%/1+3)25+5&yyNFAy..14/yyWyEltifkdCgloay
@QebT^vqlEfpEb^oq+++yNFAy..14/yyRy01./4yyKyCfkacfpep`ellipfkqebt^qbop_bqtbbkqebqtlfpi^kap%01+-)35+-&^karpbX>krkf^n$pKbqZlkqebj+Vlr$iimol_^_ivkbba^qib^pqqeobbp`elli$ptloqe+Q^odbq^Obbc?rii%0.+-)41+-&lkqebplrqepelob)pq^ka^pc^o^t^v^pvlr`^k^kaqlppefj^cfpe+Jlsbkloqe^kaobmb^qyyWyEltifkdCgloay
QQebT^vqlEfpEb^oq+++yKy>krkf^n%/1+3)25+5&yyNFAy..14/yyWyEltifkdCgloay
QQebPq^cclcPqloj$pCrovyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2..yyWyEltifkdCgloay
QQebColwbkEb^oqlcFprialcyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2./yyWyEltifkdCgloay
QQebPefbialcqeb>bpfofqbpyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..20-yyWyEltifkdCgloay
QQeb>k`fbkq>ojlolcqebHs^iafoyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..234yyWyEltifkdCgloay
>>ObqrokqlObpqfkdyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..235yyWyEltifkdCgloay
@>ObqrokqlObpqfkdyNFAy..235yyKy?^`haltk^qPefbiaEfii)rpbqebX?rkaiblcSovhri>oqfc^`qpZ^qb^`elcCbkdfo%24+4)44+2&)Olafk%26+/)43+6&)Fprialc%26+5)46+1&)Tfka^k%3.+6)5-+-&yyRy013/1yyWyEltifkdCgloay
Q>ObqrokqlObpqfkdyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..235yyWyEltifkdCgloay
>Obqrokql>qrfhyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..24/yyWyEltifkdCgloay
QObqrokql>qrfhyKyBiabo>qrfh%/2+-)24+-&yyNFAy..24/yyWyEltifkdCgloay

C?lob^kQrkao^yKyCivql?lob^kQrkao^%/1+4)24+5&yyWyEltifkdCgloay
>FkqlqebJfpqyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..322yyWy?lob^kQrkao^y
>Eloklcqeb>k`fbkqJ^ofkboyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..33-yyWy?lob^kQrkao^y
@Eloklcqeb>k`fbkqJ^ofkboyNFAy..33-yyKyHbbmhfiifkdHs^iafoJfpqtb^sbo$p^olrka%/6+-)2/+3&rkqfiqebXEloklcqeb>k`fbkqJ^ofkboZaolmpyyWy?lob^kQrkao^y
@FkqlqebJfpqyNFAy..322yyKyHfiiHs^iafo%/6+-)2/+3&qfiivlre^sbbklrdeXQrph^ooObif`pZyyWy?lob^kQrkao^y
QFkqlqebJfpqyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..322yyWy?lob^kQrkao^y
>?rokfkBccfdvyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..323yyWy?lob^kQrkao^y
QEloklcqeb>k`fbkqJ^ofkboyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..33-yyWy?lob^kQrkao^y
>Lo^_rpqebEbijpj^kyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..33.yyWy?lob^kQrkao^y
K?lo$pE^jjboyNFAy..323yyNLy?lo$pE^jjboabpqolvba7.,.yyKyLkqeb`l^pq%/6+4)2/+6&yyRy0150-yyWy?lob^kQrkao^y
KQebHroAo^hh^oyNFAy..323yyNLyQebHroAo^hh^oabpqolvba7.,.yyKyLkqeb`l^pq%0-+6)15+6&yyRy0150-yyWy?lob^kQrkao^y
KQebPbombkq$pJ^tyNFAy..323yyNLyQebPbombkq$pJ^tabpqolvba7.,.yyKyLkqeb`l^pq%0.+2)15+0&yyRy0150-yyWy?lob^kQrkao^y
K?lo$p>ksfiyNFAy..323yyNLy?lo$p>ksfiabpqolvba7.,.yyKyLkqeb`l^pq%0-+.)3.+3&yyRy0150-yyWy?lob^kQrkao^y
@Lo^_rpqebEbijpj^kyNFAy..33.yyKyPrjjlkLo^_rpqebEbijpj^ktfqeqebXEloklcqeb>k`fbkqJ^ofkboZ^qqebbkalccT^oplkdGbqqv%/3+3)21+3&)qebkhfiiefjyyRy01511yyWy?lob^kQrkao^y
Q?rokfkBccfdvyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..323yyWy?lob^kQrkao^y
QLo^_rpqebEbijpj^kyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..33.yyWy?lob^kQrkao^y
>PbbhLrqH^orhyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..33/yyWy?lob^kQrkao^y
QPbbhLrqH^orhyKyH^orh%14+/)42+2&yyNFAy..33/yyWy?lob^kQrkao^y
>H^orh$pL^qeyKyH^orh%14+/)42+2&yyNFAy..3.0yyWy?lob^kQrkao^y
>@orbiqvlcqebHs^iafoyKy@^mqrobaQrph^ooMofplkbo%11+/)44+6&+HfiiqebHs^iafo^olrkaqebcfdeqfkdQrph^ooqllmbkyyNFAy./14.yyWy?lob^kQrkao^y
@H^orh$pL^qeyNFAy..3.0yyKyAltklkOfmi^pePqo^ka^olrka%13+-)42+-&yyWy?lob^kQrkao^y
Q@orbiqvlcqebHs^iafoyKyH^orh%14+/)42+2&yyNFAy./14.yyWy?lob^kQrkao^y
QH^orh$pL^qeyKyH^orh%14+/)42+2&yyNFAy..3.0yyWy?lob^kQrkao^y
>D^jbiqeb@orbiyKyH^orh%14+/)42+2&yyNFAy..3.6yyWy?lob^kQrkao^y
@D^jbiqeb@orbiyNFAy..3.6yyKyFk^`^sbaltklkqeb_b^`e%13+0)45+5&yyWy?lob^kQrkao^y
QD^jbiqeb@orbiyKyH^orh%14+/)42+2&yyNFAy..3.6yyWy?lob^kQrkao^y
>>C^qebo$pTloapyKyH^orh%14+/)42+2&yyNFAy..3/-yyWy?lob^kQrkao^y
Q>C^qebo$pTloapyKySbbeg^%10+3)5-+3&yyNFAy..3/-yyWy?lob^kQrkao^y
>QebQofabkqlcK^w$g^kyKySbbeg^%10+3)5-+3&yyNFAy..3/2yyWy?lob^kQrkao^y
@QebQofabkqlcK^w$g^kyNFAy..3/2yyKyPtfjplrqeb^pqqlOfmi^peOrfkpql%2-+6)6-+2&)tlohvlrot^vrmqlqebkloqeb^pq_rfiafkd%21+6)55+5&yyWy?lob^kQrkao^y
QQebQofabkqlcK^w$g^kyKySbbeg^%10+3)5-+3&yyNFAy..3/2yyWy?lob^kQrkao^y
>QebBjfpp^ovyKySbbeg^%10+3)5-+3&yyNFAy..3/3yyWy?lob^kQrkao^y
@QebBjfpp^ovyNFAy..3/3yyKyPtfj_^`hqlqebi^odbf`b_bod^qOfmi^peOrfkp%2.+1)55+/&+Afsbaltk)rpbqebXQofabkqlcK^w$g^kZlkIbsfolqe^kahfiiefjyyRy0252-yyWy?lob^kQrkao^y
QQebBjfpp^ovyKyH^orh%14+/)42+2&yyNFAy..3/3yyWy?lob^kQrkao^y

>QebElkloba>k`bpqlopyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-2yyWy?lob^kQrkao^y
>Ob`i^fjfkdqebNr^oovyKyBq^orh%21+0)03+/&yyNFAy..3./yyWy?lob^kQrkao^y
@QebElkloba>k`bpqlopyNFAy..3-2yyKyCfkaBiaboQ^hobq%2/+0)0.+/&)BiaboP^d^kf%2/+5)01+.&^kaBiaboHbprh%2-+5)0/+1&yyWy?lob^kQrkao^y
@Ob`i^fjfkdqebNr^oovyNFAy..3./yyKyClrka^olrkaqebnr^oov^q%2/+2)00+/&yyWy?lob^kQrkao^y
QQebElkloba>k`bpqlopyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-2yyWy?lob^kQrkao^y
>QebIlpqPmfofqpyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-4yyWy?lob^kQrkao^y
QOb`i^fjfkdqebNr^oovyKyBq^orh%21+0)03+/&yyNFAy..3./yyWy?lob^kQrkao^y
>E^jmbofkdQebfoBp`^mbyKyBq^orh%21+0)03+/&yyNFAy..3.4yyWy?lob^kQrkao^y
@E^jmbofkdQebfoBp`^mbyNFAy..3.4yyKyHfii?boviOb`i^fjbopcloXDkljfpeDobk^abpZ)qebkrpbqebj^qqebqeobbcil^qfkdmi^qclojp*B^pq%2/+1)02+0&)Tbpq%2-+2)01+5&^kaKloqe%2.+6)0.+6&yyRy0144/yyWy?lob^kQrkao^y
@QebIlpqPmfofqpyNFAy..3-4yyKyHfiiqeb?boviElrkapqebkrpbqebX@lobplcJ^if`bZlkqebQrph^oofkqebnr^oov%2/+2)00+/&yyRy014..yyWy?lob^kQrkao^y
QQebIlpqPmfofqpyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-4yyWy?lob^kQrkao^y
>Mf`hfkdRmqebMfb`bpyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-6yyWy?lob^kQrkao^y
QE^jmbofkdQebfoBp`^mbyKyBq^orh%21+0)03+/&yyNFAy..3.4yyWy?lob^kQrkao^y
>>Sfpfqqlqeb@ro^qloyKyBq^orh%21+0)03+/&yyNFAy..3/0yyWy?lob^kQrkao^y
@>Sfpfqqlqeb@ro^qloyNFAy..3/0yyKyHfii@ro^qloFkpfsfrp^q%2-+.)0/+4&yyWy?lob^kQrkao^y
@Mf`hfkdRmqebMfb`bpyNFAy..3-6yyKyDbq3XQrph^ooOfqr^iL_gb`qpZ)clrka^olrkaqebnr^oov%2/+2)00+/&yyWy?lob^kQrkao^y
QMf`hfkdRmqebMfb`bpyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-6yyWy?lob^kQrkao^y
>Ib^afkdqeb>k`bpqlopEljbyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3.-yyWy?lob^kQrkao^y
Q>Sfpfqqlqeb@ro^qloyKyBq^orh%21+0)03+/&yyNFAy..3/0yyWy?lob^kQrkao^y
@Ib^afkdqeb>k`bpqlopEljbyNFAy..3.-yyKyRpbqebXQrph^ooOfqr^iL_gb`qZ^qb^`elcBiaboQ^hobq%2/+0)0.+/&)BiaboP^d^kf%2/+5)01+.&^kaBiaboHbprh%2-+5)0/+1&yyRy014.2yyWy?lob^kQrkao^y
QIb^afkdqeb>k`bpqlopEljbyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3.-yyWy?lob^kQrkao^y

>KlqTfqelrq^CfdeqyKy>q^fh^%30+5)13+.&yyNFAy..616yyWy?lob^kQrkao^y
>Mobm^ofkdcloqebTlopqyKyRq^fh31+-)12+5&yyNFAy..612yyWy?lob^kQrkao^y
@KlqTfqelrq^CfdeqyNFAy..616yyKyQebHs^iafoO^fabop`^k_bclrka^iilsboH^ph^i^%35+.)15+/&yyWy?lob^kQrkao^y
@Mobm^ofkdcloqebTlopqyNFAy..612yyKyClrka^iilsboH^ph^i^%35+.)15+/&yyWy?lob^kQrkao^y
QMobm^ofkdcloqebTlopqyKyRq^fh31+-)12+5&yyNFAy..612yyWy?lob^kQrkao^y
QKlqTfqelrq^CfdeqyKy>q^fh^%30+5)13+.&yyNFAy..616yyWy?lob^kQrkao^y
>Jr^efq$pTfpaljyKy>q^fh^%30+5)13+.&yyNFAy..62-yyWy?lob^kQrkao^y
QJr^efq$pTfpaljyKyBiaboJr^efq%34+/)21+5&yyNFAy..62-yyWy?lob^kQrkao^y
>PmfofqpT^q`eLsboRpyKyBiaboJr^efq%34+/)21+5&yyNFAy..63.yyWy?lob^kQrkao^y
@PmfofqpT^q`eLsboRpyNFAy..63.yyKyCfkaqebab^aqrph^oofkqebt^qboqlqebkloqe%34+3)2-+1&yyWy?lob^kQrkao^y
QPmfofqpT^q`eLsboRpyKyBiaboJr^efq%34+/)21+5&yyNFAy..63.yyWy?lob^kQrkao^y
>QebQfabpQrokyKyBiaboJr^efq%34+/)21+5&yyNFAy..635yyWy?lob^kQrkao^y
@QebQfabpQrokyNFAy..635yyKyLkqeblqebopfablcqebpq^qrb^q%34+-)23+-&yyWy?lob^kQrkao^y
QQebQfabpQrokyKyBiaboJr^efq%34+/)21+5&yyNFAy..635yyWy?lob^kQrkao^y

CAo^dlk_ifdeqyKyCivqlJl^$hfE^o_loAo^dlk_ifdeq%45+2)22+2&yyWyAo^dlk_ifdeqy
>Mi^kkfkdcloqebCrqrobyKyQo^mmboJ^r$f%15+0)41+0&yyNFAy..63-yyWyAo^dlk_ifdeqy
QQo^sbiqlJl^$hfE^o_loyKyBiaboHl$k^kf%15+.)41+6&yyNFAy./..5yyWyAo^dlk_ifdeqy
>IbqKlqefkdDlQlT^pqbyKyBiaboHl$k^kf%15+.)41+6&yyNFAy..625yyWyAo^dlk_ifdeqy
@IbqKlqefkdDlQlT^pqbyKyHfiijl_p^olrkaPkltc^iiDi^ab^q%12+4)3.+3&yyNFAy..625yyWyAo^dlk_ifdeqy
@Mi^kkfkdcloqebCrqrobyKyPqb^i./XPkltc^iiDi^abMrmpZkloqelcqltk^olrka%12+4)3.+3&yyNFAy..63-yyWyAo^dlk_ifdeqy
QMi^kkfkdcloqebCrqrobyKyQo^mmboJ^r$f%15+0)41+0&yyNFAy..63-yyWyAo^dlk_ifdeqy
QIbqKlqefkdDlQlT^pqbyKyBiaboHl$k^kf%15+.)41+6&yyNFAy..625yyWyAo^dlk_ifdeqy
>Pi^vIldrekyKyBiaboHl$k^kf%15+.)41+6&yyNFAy..626yyWyAo^dlk_ifdeqy
@Pi^vIldrekyKy>qqeberqlkqebkloqepfablcPkltc^iiDi^ab%13+.)26+4&+>cqbovlrhfiiefj)pjb^oefp_illayyNFAy..626yyRy02355yyWyAo^dlk_ifdeqy
QPi^vIldrekyKyBiaboHl$k^kf%15+.)41+6&yyNFAy..626yyWyAo^dlk_ifdeqy
>Pmfofqr^iFkpfdeqyKyQl^ir$rqebJvpqf`%16+.)42+4&yyNFAy./-/5yyWyAo^dlk_ifdeqy
@Pmfofqr^iFkpfdeqyKyRpbXQl^ir$r$pPmfofqr^iFk`bkpbZlkqeb_o^wfboofdeqlrqpfabqeberq%16)42&yyNFAy./-/5yyRy026-4yyWyAo^dlk_ifdeqy
QPmfofqr^iFkpfdeqyKyQl^ir$rqebJvpqf`%16+.)42+4&yyNFAy./-/5yyWyAo^dlk_ifdeqy
>BiaboJ^k^$il^yKyQl^ir$rqebJvpqf`%16+.)42+4&yyNFAy./-0-yyWyAo^dlk_ifdeqy
>Qr^$hb^$p@o^_Qo^mpyKyQr^$hb^%15+-)43+/&yyNFAy./--6yyWyAo^dlk_ifdeqy
>Pfdkplc?fdT^qbovQolr_ibyKyTob`hba@o^_Qo^m%14+4)46+6&+Afsbaltkfkqlqebt^qboyyNFAy./-..yyWyAo^dlk_ifdeqy
@Qr^$hb^$p@o^_Qo^mpyKy@liib`q5XQr^$hb^@o^_Qo^mpZclrka^olrkaqebt^qbop%15+-)46+-&+RpbXQr^$hb^$p?ob^qefkd?i^aaboZfcvlrkbbaqlyyNFAy./--6yyRy04/32yyWyAo^dlk_ifdeqy
QQr^$hb^$p@o^_Qo^mpyKyQr^$hb^%15+-)43+/&yyNFAy./--6yyWyAo^dlk_ifdeqy
QPfdkplc?fdT^qbovQolr_ibyKyQr^$hb^%15+-)43+/&yyNFAy./-..yyWyAo^dlk_ifdeqy
>Qeb?^fqyKyQr^$hb^%15+-)43+/&yyNFAy./-.3yyWyAo^dlk_ifdeqy
@Qeb?^fqyKyHfiiqeb_fd`o^_lrqlkHfif$r^$p>qliiqlqebtbpq%1/+3)5-+3&yyNFAy./-.3yyWyAo^dlk_ifdeqy
QQeb?^fqyKyQr^$hb^%15+-)43+/&yyNFAy./-.3yyWyAo^dlk_ifdeqy
>Jb^qlkqebEllhyKyQr^$hb^%15+-)43+/&yyNFAy./-.4yyWyAo^dlk_ifdeqy
@Jb^qlkqebEllhyKyCliiltqebcfpefkdifkblrqqfii%13+4)45+/&)rpbXQr$r$dt^o$p?^fqZ^kahfiiqebpe^ohyyNFAy./-.4yyRy02505yyWyAo^dlk_ifdeqy
QJb^qlkqebEllhyKyQr^$hb^%15+-)43+/&yyNFAy./-.4yyWyAo^dlk_ifdeqy
QBiaboJ^k^$il^yKyBiaboJ^k^$il^%03+5)32+/&yyNFAy./-0-yyWyAo^dlk_ifdeqy
>CobbaljcloqebIfkdbofkdyKyBiaboJ^k^$il^%03+5)32+/&yyNFAy./-0.yyWyAo^dlk_ifdeqy
@CobbaljcloqebIfkdbofkdyKyHfiijl_p^olrkaqebsfii^dbproolrkafkdBiaboJ^k^$il^%03+5)32+/&yyNFAy./-0.yyWyAo^dlk_ifdeqy
QCobbaljcloqebIfkdbofkdyKyBiaboJ^k^$il^%03+5)32+/&yyNFAy./-0.yyWyAo^dlk_ifdeqy
>@lksbopfkdTfqeqebAbmqepyKyBiaboJ^k^$il^%03+5)32+/&yyNFAy./-0/yyWyAo^dlk_ifdeqy
@@lksbopfkdTfqeqebAbmqepyKyEb^aplrqeql^kfpi^ka%01+.)51+-&+>`qfs^qbqebpeofkb)ifpqbkqlL^`e^$kl^)grjmfkqlqebt^qbotebkebqbiipvlrqlyyNFAy./-0/yyWyAo^dlk_ifdeqy
Q@lksbopfkdTfqeqebAbmqepyKyQl^ir$rqebJvpqf`%16+.)42+4&yyNFAy./-0/yyWyAo^dlk_ifdeqy

KDrfab@ljmibqb

]]
end)
