DugisGuideViewer:RegisterGuide("Timbermaw Hold Reputation (50+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabtfiidllsbo^iiqebnrbpqpkbbabaqldbqqebAfmilj^q>`efbsbjbkq%Bu^iqbatfqeQfj_boj^t)J^d$e^o^kaPmlobdd^o+Lk`b^iiqebnrbpqp^obalkbclo^m^oqf`ri^oc^`qflk)qebkfpgrpqdofkafkdlrqqebobmb^q^_ibarkdblkp,qrok*fkpqldbqqlBu^iqba+Qefpdrfab^pprjbpqe^qvlr^obibsbi5-)_rqqefp`^k_balkb^qibsbi4-^ptbii)fqtfiigrpqq^hbjr`eilkdboql`ljmibqb+y
KIltIbsbiNrbpqpyKyJ^hbprobvlr^obqo^hfkdiltibsbinrbpqpqlj^hbfqb^pfboqlpbbqebnrbpqpdfsbop+y

K0-XOrkb`ilqeZyKyVlrtfiikbba0-Orkb`ilqeclo^obmqrok*fktfqeqebQfj_boj^t)elialkqlqefprkqfivlrob^`eObsboba+yyIy.1-140-y
OCbitllayKyQo^sbiqlCbitlla%2.+-)52+-&yyWyCbitllay

KP^sbCb^qebopyKyP^sb^iiqebXAb^atllaEb^aaobppCb^qeboZqe^qaolm)alk$qqrokqebjfkrkqfivlr^obobsboba+y

>Qfj_boj^t>iivyKyDo^wib%2.+-)52+-&yyWyCbitllayyNFAy513-y
@Qfj_boj^t>iivyKyDo^wibt^kqpvlrqlmolsbvlropbic_vhfiifkd3Ab^atllaT^ooflop)3Ab^atllaM^qecfkabop)^ka3Ab^atllaD^oabkbop%14+1)6/+5&yyWyCbitllayyNFAy513-y
QQfj_boj^t>iivyKyDo^wib%2.+-)52+-&yyWyCbitllayyNFAy513-y
>Pmb^hqlK^cfbkyKyDo^wib%2.+-)52+-&yyWyCbitllayyNFAy513/y
QPmb^hqlK^cfbkyKyK^cfbk%31+5)5+/&yyWyCbitllayyNFAy513/y
>Ab^atllalcqebKloqeyKyK^cfbk%31+5)5+/&yyWyCbitllayyNFAy513.y
@Ab^atllalcqebKloqeyKyK^cfbktlriaifhbvlrqlhfii3Ab^atllaAbkT^q`ebop)3Ab^atlla>sbkdbop)^ka3Ab^atllaPe^j^kp+yyWyCbitllayyNFAy513.y
QAb^atllalcqebKloqeyKyK^cfbk%31+5)5+/&yyWyCbitllayyNFAy513.y
>Pmb^hqlP^ic^yKyK^cfbk%31+5)5+/&yyWyCbitllayyNFAy5132y

KRkcofbkaivyKyJ^hbprobvlr^ob^qib^pqRkcofbkaivtfqeQfj_boj^t)fcklq)hfiijlobAb^atllaCro_lidrkqfivlr^ob+y

OTfkqbopmofkdyKyOrkqeolrdeQfj_boj^tqrkkbiqlTfkqbopmofkd%/4+5)01+2&yyWyTfkqbopmofkdy
QPmb^hqlP^ic^yKyP^ic^%/4+5)01+2&yyWyTfkqbopmofkdyyNFAy5132y
>Tfkqboc^ii>`qfsfqvyKyP^ic^%/4+5)01+2&yyWyTfkqbopmofkdyyNFAy5131y
@Tfkqboc^ii>`qfsfqvyKyP^ic^t^kqpvlrqlhfii5Tfkqboc^iiPe^j^k)5Tfkqboc^iiAbkT^q`ebop)^ka5Tfkqboc^iiRop^+%/6+4)03+5&%06+5)1/+5&%34+/)02+0&yyWyTfkqbopmofkdyyNFAy5131y
QTfkqboc^ii>`qfsfqvyKyP^ic^%/4+5)01+2&yyWyTfkqbopmofkdyyNFAy5131y
KXTfkqboc^iiOfqr^iQlqbjZyKyHbbmhfiifkdTfkqboc^iiCro_lidprkqfiXTfkqboc^iiOfqr^iQlqbjZaolmp+yyIy/-41/y

OCbitllayKyQo^sbiqlCbitlla%33+0)3+1&yyWyCbitllay
KXAb^atllaOfqr^iQlqbjZyKyHbbmhfiifkdAb^atllaCro_lidprkqfiXTfkqboc^iiOfqr^iQlqbjZaolmp+yyIy/-41/.y
>Ab^atllaOfqr^iQlqbjyKyRpbXAb^atllaOfqr^iQlqbjZyyNFAy514-yyRy/-41.y
>Tfkqboc^iiOfqr^iQlqbjyKyRpbXTfkqboc^iiOfqr^iQlqbjZyyNFAy514.yyRy/-41/y

KQfj_boj^tObmDofkayKyHfiiAb^atllajl_prkqfiobsboba+Hbbm^iiqebcb^qeboprmql/6-+Fcvlre^sbjlobqe^k/6-qrokqebjfkcloobmmofloqlObsboba+Lk`bvlrefqObsboba)jlsblkqlqebkbuqpqbm+y

KQrokfk^iiCb^qebopyKyK^cfbk%31+5)5+/&yyWyCbitllayyNFAy5134y
QAb^atllaOfqr^iQlqbjyKyHboka^%32+0).+1&+FkpfabqebQfj_boj^tQrkkbiyyWyCbitllayyNFAy514-y
QTfkqboc^iiOfqr^iQlqbjyKyHboka^%32+0).+1&+FkpfabqebQfj_boj^tQrkkbiyyWyCbitllayyyNFAy514.y
>Orkb`ilqeyKyJbfilpe%32+4)/+6&+FkpfabqebQfj_boj^tQrkkbiyyWyCbitllayyNFAy3-0.y
QOrkb`ilqeyKyJbfilpe%32+4)/+6&+FkpfabqebQfj_boj^tQrkkbiyyWyCbitllayyNFAy3-0.y

K@lkqfkrbRkqfiBu^iqbayKy@lkqfkrbdofkafkdqlBu^iqbafcvlr^obk$q^iob^av+y
KDrfab@ljmibqb

]]
end)
