DugisGuideViewer:RegisterGuide("Well Read Achievement (70+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob^qib^pq4-+Pljblcqebpb_llhp^obfkelpqfibwlkbplofkpq^k`bp+y

eA^i^o^kyKyJ^hbA^i^o^kvlroeljb%32+3)0/+/&Dbqqfkdql^kacoljqebpbil`^qflktfii_bb^pfbocoljA^i^o^k+yyWyA^i^o^ky
RQebDr^oaf^kplcQfofpc^iyKy%33)02&Pb`lkaCillolcqebCfiqev>kfj^ifkA^io^kyy>FAy./11y>@y/4yyWyA^i^o^ky

O@^sbokplcQfjbyKyQ^hbMloq^ifkA^i^o^k%Sflibq@fq^abi&ql@^sboklcQfjb%/2+4)2.+/&yyWyA^i^o^ky
RQebH^ialobf^kaqebTbiilcBqbokfqvyKy%34+0)16+5&Orkfkqlqeb`^sbok^kavlrcfkafqfk^olljqlqebofdeq+Alk$qq^hbao^dlkfkqlqeb@^sbokp+yy>FAy./11yy>@y/6yyWyQ^k^ofpy

CQerkabo?irccyKy?rihobhO^dbcfpq%2.)/2&yyWyQ^k^ofpy
K?llhpyKy>iiQeobb?llhp^obkbuqqlb^`elqebo+y
RFolkclodb*qeb>t^hbkfkdlcqebAt^osbpyKy%0.+3)16+2&yy>FAy./11yy>@y..yyWyJridloby
RQeb?^qqiblcDofj?^qliyKy%0.+3)16+2&yy>FAy./11yy>@y//yyWyJridloby
RT^olcqebQeobbE^jjbopyKy%0.+3)16+2&yy>FAy./11yy>@y1.yyWyJridloby

CO^q`ebqyKyQ^i%14)2-&yyWyQerkabo?irccy
R@e^odblcqebAo^dlkcifdeqpyKyKb^oD^wiltb%3/+4)03+/&O^`ebqyy>FAy./11yy>@y3yyWyQeb?^oobkpy
R>o`efjlkab$pObqrok^kaqebCifdeqqlH^ifjaloyKyKb^oIfsOfwwibcfu%3/+1)05+5&O^`ebqyy>FAy./11yy>@y1yyWyQeb?^oobkpy
RBufiblcqebEfdeBisbpyKyPb`lkacillo_^i`lkvlcG^wwfh$pDbkbo^iDllapkbuqqlFkk%3.+6)05+4&O^`ebqyy>FAy./11yy>@y6yyWyQeb?^oobkpy
RP^odbo^p^kaqeb?bqo^v^iyKyQebFkk%3.+6)06+3&O^`ebqyy>FAy./11yy>@y.6yyWyQeb?^oobkpy
RJlrkqEvg^i^kaFiifa^k$pDfcqyKyQebFkk%3.+5)06+1&O^`ebqyy>FAy./11yy>@y.2yyWyQeb?^oobkpy
RIbqe^odvlcqebLo`pyKy%3.+5)22+.&Qlmlcqebcfopqqltbo^pvlrorkrmqebefiifkKloqet^q`eEliayy>FAy./11yy>@y.1yyWyQeb?^oobkpy

_?llqv?^vyKyQ^hbqeb_l^qql?llqv?^v%30)05&yyWyQeb?^oobkpy
RBjmfobp$C^iiyKy%/4+5)44+0&?llqv?^v+?llhpebiclkIbcq^pvlrbkqboollj+yy>FAy./11yy>@y5yyWyPqo^kdibqelokS^iby
RQebQtfkBjmfobpyKy%/4+5)44+0&?llqv?^v+?llhpebiclkIbcq^pvlrbkqboollj+yy>FAy./11yy>@y04yyWyPqo^kdibqelokS^iby
RTo^qelcPlrici^vboyKy%/4+5)44+0&?llqv?^v+?llhpebiclkIbcq^pvlrbkqboollj+yy>FAy./11yy>@y1/yyWyPqo^kdibqelokS^iby
RQebP`lrodblcIloa^bolkyKy%/4+4)44+.&?llqv?^v+Lk?llhpebic?lqqljCillo+yy>FAy./11yy>@y01yyWyPqo^kdibqelokS^iby
RQebPbkqfkbip^kaqebIlkdSfdfiyKy%/4+6)44+/&?llqv?^v+Qlmcillokbuqqlqeb_ba+yy>FAy./11yy>@y02yyWyPqo^kdibqelokS^iby
RPrktbii*QebC^iilcNrbi$Qe^i^pyKy%/4+.)44+4&?llqv?^v+Pb`lkacillolcfkklk^q^_ib+yy>FAy./11yy>@y/-yyWyPqo^kdibqelokS^iby
R?bvlkaqebA^ohMloq^iyKy%/3+6)44+0&?llqv?^v+Qlmcillolcfkklkq^_ibkbuqqlpqlsb+yy>FAy./11yy>@y2yyWyPqo^kdibqelokS^iby

CPqlk^oayKyCivqlPqlk^oa)Pt^jmlcPlooltp%/3+6)44+.&yyWyPt^jmlcPlooltpy
RQebA^ohMloq^i^kaqebC^iilcPqlojtfkayKy%14+4)22+-&Pqlk^oa+?lqqljCillolc_rfiafkdkbuqqlfkk+yy>FAy./11yy>@y/2yyWyPt^jmlcPlooltpy
ROfpblcqebEloabyKy%14+5)21+6&Pqlk^oa+Qlmlccillolcp^jb_rfiafkd+yy>FAy./11yy>@y.5yyWyPt^jmlcPlooltpy
RQebKbtEloabyKy%14+5)21+6&Pqlk^oa+Qlmlccillolcp^jb_rfiafkd+yy>FAy./11yy>@y0/yyWyPt^jmlcPlooltpy

KLmqflk^iyKyQebClrkafkdlcNrbi$Qe^i^p`^k^ipl_bclrkafkqebFkk^qA^ohpefob)Arphtllafkpqb^alcP`elilj^k`b+y

OTbpqc^iiyKyQo^sbiqlTbpqc^ii%34)3/&yyWyTbpqc^iiy
RQebI^pqDr^oaf^kyKy%2/+3)20+-&PbkqfkbiEfii+Lkq^_ibkbuqql_bap+yy>FAy./11yy>@y0-yyWyTbpqc^iiy

EA^i^o^kyRy3615y

OPfisbojllk@fqvyKyQ^hbMloq^ifkA^i^o^k%25+0)/.+4&yyWyA^i^o^ky
RQeb?bqo^vbo>p`bka^kqyKy%35+2)31+.&Pfisbojllk@fqv+FkpfabSbi^^kf$p>o`^kbDllap+yy>FAy./11yy>@y/0yyWyPfisbojllk@fqvy
RQeb>iif^k`blcIloa^bolkyKy%33+5)40+6&Pfisbojllk@fqv+Pb`lkacillolcT^vc^obo$pObpqlkcillokbuqql_ba+yy>FAy./11yy>@y/.yyWyPfisbojllk@fqvy

ORkabo`fqvyKyQ^hbMloq^ifkPfisbojllk@fqv%16+3).1+5&yyWyPfisbojllk@fqvy
R@fsfiT^ofkqebMi^drbi^kapyKy%34+3)04+/&Rkabo`fqv+Kb^oFkkhbbmboKloj^kyy>FAy./11yy>@y4yyWyRkabo`fqvy
RQebLiaDlap^kaqebLoabofkdlc>wbolqeyKy%23+-)2-+6&Rkabo`fqv+Lkqebq^_ib+yy>FAy./11yy>@y00yyWyRkabo`fqvy
RF`b`oltk^kaqebColwbkQeolkbyKy%23+-)2-+6&Rkabo`fqv+Lkqebq^_ib+yy>FAy./11yy>@y.-yyWyRkabo`fqvy
RHbi$Qerw^a^kaqebClojfkdlcqebP`lrodbyKy%23+-)2-+6&Rkabo`fqv+Lkqebq^_ib+yy>FAy./11yy>@y./yyWyRkabo`fqvy

O?ofiiyKyQo^sbiql?ofii%3-)2/&yyWyQfofpc^iDi^abpy
R>bdtvkk^kaqebAo^dlkErkqyKy%3.+3)2/+.&?ofii+FkqebQ^sbokpb`lkacillo)olljqlqebofdeq^pvlr`ljbrmqebpq^fop+yy>FAy./11yy>@y.yyWyQfofpc^iDi^abpy

OP`^oibqJlk^pqbovyKy%5/+2)00&yyWyQfofpc^iDi^abpy
KP`^oibqJlk^pqbovIf_o^ovyKyCfopqfkpq^k`blkqebofdeq+Qebob^objlob_llhpfkP`^oibqJlk^pqbovqebkifpqbaebobfcvlrt^kqqlcfkfpeqebfkpq^k`b^ka`liib`qqebj+Qebobpqlcqeb_llhp^obclrkafklqebomi^`bpifpqbafkqefpdrfab+y
R>cqboj^qelcqebPb`lkaT^oyKyM^pqqebD^iibovlcQob^probp)lkqebcilloqlqebibcq+yy>FAy./11yy>@y/y
RT^olcqebPmfaboyKyLqebopfabclqebolljlkqebcillo_bqtbbk_bk`ebp+yy>FAy./11yy>@y1-y
R>o^qelo^kaqebQoliiT^opyKyJlsbqlkbuq^i`lsb^kavlr$iicfkaqefplkb^qqebbkalcqebolljlkqebibcqpfablcqeballolkqebcillo+yy>FAy./11yy>@y0y
RQebTloiaQobb^kaqebBjbo^iaAob^jyKyP^jb^i`lsbofdeqpfablcallolkqebcillo+yy>FAy./11yy>@y06y
RQebT^olcqeb>k`fbkqpyKyDlqeoralloql>qebk^brj)^kaqefp_llhfplkq^_ibpqo^fdeq^eb^a+yy>FAy./11yy>@y05y

OP`elilj^k`byKyOrklrqlcP`^oibqJlk^pqbov^kaeb^aqlP`elilj^k`b+y
RQebPbsbkHfkdaljpyKy>pvlrbkqboqebObifnr^ov)dlibcqaltkqebpq^fop^kafqfplkqebq^_ib+yy>FAy./11yy>@y03y
RQeb?foqelcqebIf`eHfkdyKyPlrqeb^pq`lokbolcolljlkq^_ib+yy>FAy./11yy>@y/1y
RQebIf`eHfkdQofrjme^kqyKyLkqebq^_ibqlqebofdeqlcqebi^pq_llhyy>FAy./11yy>@y0.y
ROfpblcqeb?illaBisbpyKyLkqebq^_ibpqlqebofdeqlcqebDob^qLppr^ovalloyy>FAy./11yy>@y.4y
RLiaE^qobap*Qeb@lilkfw^qflklcH^ifjaloyKyLkqebq^_ibpqlqebofdeqlcqebDob^qLppr^ovalloyy>FAy./11yy>@y.3y
RHfi$g^babk^kaqebPe^altM^`qyKyLkqebq^_ibpqlqebofdeqlcqebDob^qLppr^ovalloyy>FAy./11yy>@y.0y
RQebFks^pflklcAo^bkloyKyKloqeb^pq@lokbolcolljmofloqlSfbtfkdolljyy>FAy./11yy>@y/5y
RQebClrkafkdlcNrbi$Qe^i^pyKyFkqebSfbtfkdOlljlkq^_ibkbuqqlJ^oarh?i^`hmlli)kbbahbvcoljO^qqibdlobqlbkqbo+yy>FAy./11yy>@y/3y

KDrfab@ljmibqb
]]
end)
