DugisGuideViewer:RegisterGuide("The Wyrmrest Accord Reputation (80+)", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpqe^qvlr^ob5-+Fcvlre^sb`ljmibqbaqebbkqfobao^dlk_ifdeqnrbpq^ob^)jlpqlcqebpbnrbpqptfii_b`ljmibqb+y

O?lob^kQrkao^yKyQo^sbiql?lob^kQrkao^%00+0)01+2&yyNFAy..6.5yyWy?lob^kQrkao^y
>?^pf`Qo^fkfkdyKyO^bilo^pw%00+0)01+2&yyNFAy..6.5yyWy?lob^kQrkao^y
@?^pf`Qo^fkfkdyNFAy..6.5yyKyHfii.-@lia^oo^Pmbiitb^sbopclrka^olrka%0/+0)/5+4&yyWy?lob^kQrkao^y
>Mrwwifkd+++yNFAy..61.yyKyQebfqbjXP`fkqfii^qfkdCo^djbkqZpq^oqpnrbpq*aolmmba_v@lia^oo^Pmbii_fkabop^olrka%00)/5&yyRy02315yyWy?lob^kQrkao^y
Q?^pf`Qo^fkfkdyKyO^bilo^pw%00+0)01+2&yyNFAy..6.5yyWy?lob^kQrkao^y
>E^q`efkd^Mi^kyKyO^bilo^pw%00+0)01+2&yyNFAy..603yyWy?lob^kQrkao^y
QMrwwifkd+++yKyO^bilo^pw%00+0)01+2&yyNFAy..61.yyWy?lob^kQrkao^y
>Qeb@biiyKyO^bilo^pw%00+0)01+2&yyNFAy..610yyWy?lob^kQrkao^y

@Qeb@biiyNFAy..610yyKyHfiiT^o_ofkdboDlobao^hqlqebtbpq%/1+/)/5+6&^kaDbkbo^i@borib^kqlqebkloqe%/4+2)/-+4&yyWy?lob^kQrkao^y
@E^q`efkd^Mi^kyNFAy..603yyKyHfii@lia^oo^Tvojhfkproolrkafkd@lia^oo^cloqebfoXColwbk>ubpZ)qebkrpbqebjlkqebbddpkb^oqebKburp%/5+2)/5+6&yyRy02253yyWy?lob^kQrkao^y

QE^q`efkd^Mi^kyKyO^bilo^pw%00+0)01+2&yyNFAy..603yyWy?lob^kQrkao^y
>Ao^hbErkqyKyO^bilo^pw%00+0)01+2&yyNFAy..6.6yyWy?lob^kQrkao^y
QQeb@biiyKyO^bilo^pw%00+0)01+2&yyNFAy..610yyWy?lob^kQrkao^y
>Hbofpqo^pw^yKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..613yyRy0234.yyWy?lob^kQrkao^y
QHbofpqo^pw^yKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..613yyRy0234.yyWy?lob^kQrkao^y
>?^fq^kaPtfq`eyKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..62.yyRy0234.yyWy?lob^kQrkao^y

@?^fq^kaPtfq`eyNFAy..62.yyKyIllqqebmromib`ovpq^ipkb^oqebKburp%/5+2)/5+6&yyWy?lob^kQrkao^y
@Ao^hbErkqyNFAy..6.6yyRy022-3yyKyCfka^KburpAo^hbE^q`eifkdcivfkd^olrkaqlqebtbpqlcqebKburp+EfqfqtfqeXO^bilo^pw$pPmb^oZrkqfi`lkqoliibaqebkabifsboqlO^bilo^pw%00+0)01+2&tfqefk0jfkrqbpyyWy?lob^kQrkao^y

QAo^hbErkqyKyO^bilo^pw%00+0)01+2&yyNFAy..6.6yyWy?lob^kQrkao^y
>@o^`hfkdqeb@labyKyO^bilo^pw%00+0)01+2&yyNFAy..60.yyWy?lob^kQrkao^y
@@o^`hfkdqeb@labyNFAy..60.yyKyHfiiFknrfpfqlo@^ibo^pqlqebkloqe%0/+5)/4+5&+XPefjjbofkdOrkbpZaolmcoljqeb@lia^oo^Pmbii_fkabop^olrka%00)0-&yyWy?lob^kQrkao^y
Q?^fq^kaPtfq`eyKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..62.yyRy0234.yyWy?lob^kQrkao^y
>P^o^dlp^$pBkayKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..624yyRy0234.yyWy?lob^kQrkao^y

@P^o^dlp^$pBkayNFAy..624yyKyQ^ihqlHbofpqo^pw^clo^qbibmloq+RpbqebX>o`^kbMltboCl`rpZ)qebkhfiieboyyRy0236-yyWy?lob^kQrkao^y
QP^o^dlp^$pBkayKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..624yyRy0234.yyWy?lob^kQrkao^y
>JrpqbofkdqebObapyKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..634yyRy0234.yyWy?lob^kQrkao^y

QJrpqbofkdqebObapyKyO^bilo^pw%00+0)01+2&)Hbofpqo^pw^tfiimloqvlr_^`hyyNFAy..634yyWy?lob^kQrkao^y
>PmofkdfkdqebQo^myKyO^bilo^pw%00+0)01+2&yyNFAy..636yyWy?lob^kQrkao^y

Q@o^`hfkdqeb@labyKyO^bilo^pw%00+0)01+2&yyNFAy..60.yyWy?lob^kQrkao^y
@PmofkdfkdqebQo^myNFAy..636yyKyEb^aqlKloqe*Tbpqbkqo^k`blcqebKburp^q%/2+5)//+3&+RpbXO^bilo^pw$Pm^ohZ_bprobqlpq^v`ilpbqlHbofpqo^pw^yyRy1162-yyWy?lob^kQrkao^y
QPmofkdfkdqebQo^myKyO^bilo^pw%00+0)01+2&yyNFAy..636yyWy?lob^kQrkao^y

>@lo^pqo^pw^yKyIf_o^of^kPboo^e%00+1)01+1&yyNFAy.01./yyWy?lob^kQrkao^y
Q@lo^pqo^pw^yKy@lo^pqo^pw^%/6+1)/1+5&+Pebfplk^cil^qfkdmi^qcloj+yyNFAy.01./yyWy?lob^kQrkao^y
>>`bpEfdeyKy@lo^pqo^pw^%/6+1)/1+5&+Pebfplk^cil^qfkdmi^qcloj+yyNFAy.01.0yyWy?lob^kQrkao^y
@>`bpEfdeyKyHfii2P`^ibptlokBifqbp+yyNFAy.01.0yyWy?lob^kQrkao^y
Q>`bpEfdeyKy@lo^pqo^pw^%/6+1)/1+5&+Pebfplk^cil^qfkdmi^qcloj+yyNFAy.01.0yyWy?lob^kQrkao^y

>MofplkbolcT^oyKyO^bilo^pw%00+0)01+2&yyNFAy..640yyWy?lob^kQrkao^y
OQebKburpyKyWlkbfkqlQebKburpArkdblkyyFy
@MofplkbolcT^oyKyBkqboqebKburp^kaobib^pbHbofpqo^pw^+%I^pq?llp&yyNFAy..640y
O?lob^kQrkao^yKyBufq_^`hql?lob^kQrkao^y
QMofplkbolcT^oyKyO^bilo^pw%00+0)01+2&yyNFAy..640yyWy?lob^kQrkao^y
>QebPqorddibMbopfpqpyKyO^bilo^pw%00+0)01+2&yyWy?lob^kQrkao^yyNFAy.0./1y

OQebL`rirpyKyNrbrbcloQebL`rirptfqevlroarkdblkcfkaboyyFy

@QebPqorddibMbopfpqpyKyBkqboQebL`rirp^kaobp`rb?bid^ofpqo^pwyyNFAy.0./1y
QQebPqorddibMbopfpqpyKy?bid^ofpqo^pw)FkpfabQebL`rirpyyNFAy.0./1y

>>RkfcfbaColkqyKy?bid^ofpqo^pw*fkpfabQebL`rirpyyNFAy.0./3y
@>RkfcfbaColkqyKyAbpqolv.-@bkqofcrdb@lkpqor`qp+QebkHfiiS^olp@ilrapqofabo+TebkS^olp@ilrapqofaboafbp)qebFj^dblc?bid^ofpqo^pw^mmb^op^qS^olp$`lompbyyNFAy.0./3y
Q>RkfcfbaColkqyKyFj^dblc?bid^ofpqo^pw)FkpfabQebL`rirpyyNFAy.0./3y

>J^db*IloaRoljyKyFj^dblc?bid^ofpqo^pw)FkpfabQebL`rirpyyNFAy.0./4y
@J^db*IloaRoljyKyHfiiJ^db*IloaRolj+Tebkvlr^mmol^`eefjebe^p^`e^k`bqlpm^tklkblcqeobbm^`hplcjl_p+++>kfj^ip7hfiiqeb`ilrapbombkqcfopq+Bibjbkq^ip7hfiiqebcfobbibjbkq^ipcfopq+Jlkpqbop7hfiiqebldobcfopqyyNFAy.0./4y
QJ^db*IloaRoljyKyFj^dblc?bid^ofpqo^pw)FkpfabQebL`rirpyyNFAy.0./4y

>>Tfkd^ka^Mo^vboyKyFj^dblc?bid^ofpqo^pw)FkpfabQebL`rirpyyNFAy.0./5y
@>Tfkd^ka^Mo^vboyKyHfiiIbv*Dr^oaf^kBobdl)qebcfk^i_lppfkQebL`rirpyyNFAy.0./5y

O@lia^oo^yKyBufq_^`hql@lia^oo^%00+0)01+2&fk?lob^kQrkao^yyWy?lob^kQrkao^yyFy
Q>Tfkd^ka^Mo^vboyWy?lob^kQrkao^yyKyO^bilo^pw%00+0)01+2&yyNFAy.0./5y

OAo^dlk_ifdeqyKyQo^sbiqlAo^dlk_ifdeq%45+6)12+0&yyNFAy./106yyWyAo^dlk_ifdeqy
>Ofcibqeb?lafbpyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy..666yyWyAo^dlk_ifdeqy
@Ofcibqeb?lafbpyKyIllqqeb_lafbp^olrka%/2+/)25+6&)qebklmbkqebfqbjvlrdbqcoljqebjrkqfivlrdbqqebXJllkobpqD^oabkpMi^kpZyyNFAy..666yyWyAo^dlk_ifdeqy
QOfcibqeb?lafbpyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy..666yyWyAo^dlk_ifdeqy

>>Pqo^kdbAbsf`byKyQebfqbjXDlo^jlpe$pPqo^kdbAbsf`bZpq^oqpnrbpq*aolmmba_vDlo^jlpe%.6+2)25&yyNFAy./-26yyRy03413yyWyAo^dlk_ifdeqy
>QebC^qblcqebOr_vAo^dlkpeofkbyKyQebfqbjXOr_v?oll`eZpq^oqpnrbpq*aolmmba_vA^eif^Prkqlr`e%14+3)16+-&yyNFAy./1.6yyRy04500yyWyAo^dlk_ifdeqy

Q>Pqo^kdbAbsf`byKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-26yyWyAo^dlk_ifdeqy
>Molgb`qflkp^kaMi^kpyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-3.yyWyAo^dlk_ifdeqy
@Molgb`qflkp^kaMi^kpyKyRpbqebXProdbKbbaibQbibmloqboZ^q%//+2323+64&)dbq`ilpbbklrdeqldbq`obafq+Rpbfq^d^fkqldbqaltkyyNFAy./-3.yyRy03414yyWyAo^dlk_ifdeqy
RRpbqebXProdbKbbaibQbibmloqboZyKyRpbqebXProdbKbbaibQbibmloqboZqldbqaltkyyRy03414yyNFAy..63-yyWyAo^dlk_ifdeqy

QMolgb`qflkp^kaMi^kpyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-3.yyWyAo^dlk_ifdeqy
>QebCl`rplkqeb?b^`eyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-33yyWyAo^dlk_ifdeqy
@QebCl`rplkqeb?b^`eyKyHfii@^mq^fkBjjvJ^ifk^q%/3+3)32+.&qldbqqebXIbvIfkbCl`rp@lkqoliOfkdZ^karpbfqlkqebdf^kq^o`eqebobyyNFAy./-33yyRy0342.yyWyAo^dlk_ifdeqy
QQebCl`rplkqeb?b^`eyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-33yyWyAo^dlk_ifdeqy
>>qlmqebTllai^kapyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-51yyWyAo^dlk_ifdeqy
@>qlmqebTllai^kapyKyHfiiIfbrqbk^kqQ^$wfkkf%0/+/)4/+5&cloqebXIbvIfkbCl`rp@lkqoli>jribqZ)rpbfqlkqeb^o`eqebobyyNFAy./-51yyRy03446yyWyAo^dlk_ifdeqy
Q>qlmqebTllai^kapyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-51yyWyAo^dlk_ifdeqy
>Pb^o`eFkar$ibSfii^dbyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./.-3yyWyAo^dlk_ifdeqy
QPb^o`eFkar$ibSfii^dbyKyJ^db*@ljj^kaboBsbkpq^o%1-+/)33+6&yyNFAy./.-3yyWyAo^dlk_ifdeqy
>QebBkalcqebIfkbyKyJ^db*@ljj^kaboBsbkpq^o%1-+/)33+6&yyNFAy./..-yyWyAo^dlk_ifdeqy
RRpbXIbvIfkbCl`rp@lkqoliQ^ifpj^kZyKyRpbXIbvIfkbCl`rp@lkqoliQ^ifpj^kZyyRy035.2yyNFAy././/yyWyAo^dlk_ifdeqy
@QebBkalcqebIfkbyKyDll_pbosbqeb>wrobAo^dlkpeofkbkloqeb^pqlcqltk%20+-)32+1&yyNFAy./..-yyWyAo^dlk_ifdeqy

cTvojobpqQbjmibyKyKbqebpqo^pw%3-+0)2.+2&yyNFAy././/yyWyAo^dlk_ifdeqy
QQebC^qblcqebOr_vAo^dlkpeofkbyKyHo^prp%26+5)21+3&yyNFAy./1.6yyWyAo^dlk_ifdeqy
QQebBkalcqebIfkbyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./..-yyWyAo^dlk_ifdeqy
>D^fkfkd^k>rafbk`byKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy././/yyWyAo^dlk_ifdeqy

QD^fkfkd^k>rafbk`byKyQ^oflipqo^pw%24+6)21+/&yyNFAy././/yyWyAo^dlk_ifdeqy
>Pmb^htfqevlro>j_^pp^aloyKyQ^oflipqo^pw%24+6)21+/&yyNFAy./434yyWyAo^dlk_ifdeqy
QPmb^htfqevlro>j_^pp^aloyKyDliir`hOl`hcfpq%25)23&yyNFAy./434yyWyAo^dlk_ifdeqy
>ObmloqqlqebOr_vAo^dlkpeofkbyKyDliir`hOl`hcfpq%25)23&yyNFAy./13.yyWyAo^dlk_ifdeqy
>QebL_pfaf^kAo^dlkpeofkbyKyK^if`b%3-+-)21+/&yyNFAy./114yyWyAo^dlk_ifdeqy
>JvpqbovlcqebFkcfkfqbyKy@eoljfb%3-+-)21+2&yyNFAy./14-yyWyAo^dlk_ifdeqy
>PbbaplcqebI^pebopyKyIloaFqe^ofrp%26+3)21+2&yyNFAy./125yyWyAo^dlk_ifdeqy

QObmloqqlqebOr_vAo^dlkpeofkbyKyS^od^pqo^pw%1/+6)2-+6&yyNFAy./13.yyWyAo^dlk_ifdeqy
>Eb^qba?^qqibyKyS^od^pqo^pw%1/+6)2-+6&yyNFAy./115yyWyAo^dlk_ifdeqy
@Eb^qba?^qqibyKyCfkaqebKM@pfkqebo^sfkb%1/+5)2.+2&+Q^djl_pqebkibqqebKM@phfiifqclovlryyNFAy./115yyWyAo^dlk_ifdeqy
QEb^qba?^qqibyKyS^od^pqo^pw%1/+6)2-+6&yyNFAy./115yyWyAo^dlk_ifdeqy
>ObqrokqlqebB^oqeyKyS^od^pqo^pw%1/+6)2-+6&yyNFAy./116yyWyAo^dlk_ifdeqy
@ObqrokqlqebB^oqeyKyRpbqebXOr_v>`lokpZlkqebab^aOr_vHbbmbopclrka^olrka%14+6)15+-&yyNFAy./116yyRy044/4yyWyAo^dlk_ifdeqy
QObqrokqlqebB^oqeyKyS^od^pqo^pw%1/+6)2-+6&yyNFAy./116yyWyAo^dlk_ifdeqy
>QeolrdeCfbiaplcCi^jbyKyS^od^pqo^pw%1/+6)2-+6&yyNFAy./12-yyWyAo^dlk_ifdeqy
@QeolrdeCfbiaplcCi^jbyKyHfii3CofdfaKb`olj^k`bop^olrka%14+6)15+-&)qebkcfkaqeb_^kpebbrkaboqebpeofkb%14+6)16+6&yyNFAy./12-yyWyAo^dlk_ifdeqy
QQeolrdeCfbiaplcCi^jbyKyS^od^pqo^pw%1/+6)2-+6&yyNFAy./12-yyWyAo^dlk_ifdeqy
>QebPqbt^oalcTvojobpqQbjmibyKyS^od^pqo^pw%1/+6)2-+6&yyNFAy./436yyWyAo^dlk_ifdeqy
QQebPqbt^oalcTvojobpqQbjmibyKyQ^oflipqo^pw%24+6)21+/&yyNFAy./436yyWyAo^dlk_ifdeqy
>FkclojfkdqebNrbbkyKyQ^oflipqo^pw%24+6)21+/&yyNFAy././1yyWyAo^dlk_ifdeqy
QFkclojfkdqebNrbbkyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&)civqlqlmibsbiyyNFAy././1yyWyAo^dlk_ifdeqy
>ObmloqqlIloa>co^p^pqo^pwyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyNFAy./102yyWyAo^dlk_ifdeqy
QObmloqqlIloa>co^p^pqo^pwyKyIloa>co^p^pqo^pw%26+/)21+0&)civqljfaaibibsbiyyNFAy./102yyWyAo^dlk_ifdeqy
>AbcbkafkdTvojobpqQbjmibyKyIloa>co^p^pqo^pw%26+/)21+0&yyNFAy./04/yyAyyWyAo^dlk_ifdeqy
@AbcbkafkdTvojobpqQbjmibyKyElmlk^ao^dlk)hfii>wrobAo^dlkp^kaAo^hbp)qebkabpq^_fifwbqeb>wrobAo^dlkpeofkb%22+6)32+6&yyNFAy./04/yyAyyWyAo^dlk_ifdeqy
QAbcbkafkdTvojobpqQbjmibyKyIloa>co^p^pqo^pw%26+/)21+0&yyNFAy./04/yyAyyWyAo^dlk_ifdeqy

QQebL_pfaf^kAo^dlkpeofkbyKyPbofk^o%02+/)0-+.&yyNFAy./114yyWyAo^dlk_ifdeqy
>KllkbqlP^sbVlryKyPbofk^o%02+/)0-+.&yyNFAy.//3/yyWyAo^dlk_ifdeqy
>KlMi^`bqlOrkyKyPbofk^o%02+/)0-+.&yyNFAy.//3.yyWyAo^dlk_ifdeqy

@KlMi^`bqlOrkyKyEb^alrqpfab)rpbqebXAbpqor`qfsbT^oapZtebobqebm^qejbbqpqebpklt%1.+0)0.+5&yyNFAy.//3.yyRy04112yyWyAo^dlk_ifdeqy
@KllkbqlP^sbVlryKyJl_p`^k_bclrkabfqebofkpfablolrqpfabqeb`^sb%04+5)00+/&yyNFAy.//3/yyWyAo^dlk_ifdeqy

QKllkbqlP^sbVlryKyPbofk^o%02+/)0-+.&yyNFAy.//3/yyWyAo^dlk_ifdeqy
QKlMi^`bqlOrkyKyPbofk^o%02+/)0-+.&yyNFAy.//3.yyWyAo^dlk_ifdeqy
>Qeb?bpqlcFkqbkqflkpyKyPbofk^o%02+/)0-+.&yyNFAy.//30yyWyAo^dlk_ifdeqy
@Qeb?bpqlcFkqbkqflkpyKyQ^hbqebm^qekloqeqlqebj^dj^tvojobproob`qflk`e^j_bo%0.+4)0-+2&yyNFAy.//30yyWyAo^dlk_ifdeqy
QQeb?bpqlcFkqbkqflkpyKyPbofk^o%02+/)0-+.&yyNFAy.//30yyWyAo^dlk_ifdeqy
>@riifkdqebA^jkbayKyPbofk^o%02+/)0-+.&yyNFAy.//31yyWyAo^dlk_ifdeqy
>AbcfifkdqebAbcfibopyKyPbofk^o%02+/)0-+.&yyNFAy.//32yyWyAo^dlk_ifdeqy
@@riifkdqebA^jkbayKyHfiijl_pcroqebofkpfabqeb`^sbp^olrka%0/+-)/5+1&yyNFAy.//31yyWyAo^dlk_ifdeqy
@AbcfifkdqebAbcfibopyKyCroqebofkpfabqeb`^sbp^olrka%0/+-)/5+1&)abpqolvqeborkb`fo`ibplkqebdolrkayyNFAy.//32yyWyAo^dlk_ifdeqy
QAbcfifkdqebAbcfibopyKyPbofk^o%02+/)0-+.&yyNFAy.//32yyWyAo^dlk_ifdeqy
Q@riifkdqebA^jkbayKyPbofk^o%02+/)0-+.&yyNFAy.//31yyWyAo^dlk_ifdeqy
>Kbqe^oflk$pCi^jbyKyPbofk^o%02+/)0-+.&yyNFAy.//34yyWyAo^dlk_ifdeqy
@Kbqe^oflk$pCi^jbyKyEb^a_^`hqlqebj^dj^tvojobproob`qflk`e^j_bo%0.+4)0.+.&)rpbXKbiqe^oflk$pCi^jbZ^kahfiiOlqefkqebAb`^vfkdyyNFAy.//34yyRy04206yyWyAo^dlk_ifdeqy
QKbqe^oflk$pCi^jbyKyPbofk^o%02+/)0-+.&yyNFAy.//34yyWyAo^dlk_ifdeqy
>Q^ibplcAbpqor`qflkyKyPbofk^o%02+/)0-+.&yyNFAy.//33yyWyAo^dlk_ifdeqy
@PbbaplcqebI^pebopyKyDlplrqeqlqebBjbo^iaAo^dlkpeofkb%30+2)4.+2&^kacfka0XI^peboPbbapZlkqebdolrkayyNFAy./125yyWyAo^dlk_ifdeqy

QQ^ibplcAbpqor`qflkyKyK^if`b%3-+-)21+/&yyNFAy.//33yyWyAo^dlk_ifdeqy
QPbbaplcqebI^pebopyKyIloaFqe^ofrp%26+3)21+2&yyNFAy./125yyWyAo^dlk_ifdeqy
>Qe^qTef`e@ob^qbp@^k>iplAbpqolvyKyIloaFqe^ofrp%26+3)21+2&yyNFAy./126yyWyAo^dlk_ifdeqy

@Qe^qTef`e@ob^qbp@^k>iplAbpqolvyKyRpbqebXPbbaplcK^qrob$pTo^qeZlkLsbopbboAb^qed^wbfkGfkqe^$h^i^o%56+1).5+6&)QrodfaqebSfibfkqeb_olhbkhbbm_biltK^uu%52+6)14+3&^ka^Ob^kfj^qbaColpqTvoj^olrkaTvojobpqQbjmib%24)13&yyNFAy./126yyRy04554yyWyAo^dlk_ifdeqy

>@v`iblcIfcbyKyKfpebo^qebD^oabkHbbmbo%3/+2)40+0&)t^kabofkdKM@yyNFAy./121yyWyAo^dlk_ifdeqy
@@v`iblcIfcbyKyHfii2Bjbo^iaPhvq^ilkpcivfkd^olrka%31+.)43+3&yyNFAy./121yyWyAo^dlk_ifdeqy
Q@v`iblcIfcbyKyKfpebo^qebD^oabkHbbmbo%3/+2)40+0&)t^kabofkdKM@yyNFAy./121yyWyAo^dlk_ifdeqy
>QebMirjblc>ivpqolpyKyKfpebo^qebD^oabkHbbmbo%3/+2)40+0&)t^kabofkdKM@yyNFAy./123yyWyAo^dlk_ifdeqy
@QebMirjblc>ivpqolpyKy>`nrfobQebMirjblc>ivpqolp+yyRy0455.yyNFAy./123yyWyAo^dlk_ifdeqy
QQebMirjblc>ivpqolpyKyKfpebo^qebD^oabkHbbmbo%3/+2)40+0&)t^kabofkdKM@yyNFAy./123yyWyAo^dlk_ifdeqy

@JvpqbovlcqebFkcfkfqbyKyRpbqebXElrodi^pplcBqbokfqvZ^qqeb?olkwbAo^dlkpeofkb%4.+/)06+6&)molqb`qfqcoljqebao^dlkpqe^qpm^tkyyNFAy./14-yyRy046/0yyWyAo^dlk_ifdeqy

QQe^qTef`e@ob^qbp@^k>iplAbpqolvyKyIloaFqe^ofrp%26+3)21+2&yyNFAy./126yyWyAo^dlk_ifdeqy
QJvpqbovlcqebFkcfkfqbyKy@eoljfb%3-+-)21+2&yyNFAy./14-yyWyAo^dlk_ifdeqy

>QebHlo$holkS^kdr^oayKyLsboiloa>dj^o%05+.)13+0&yyNFAy.///1yyWyAo^dlk_ifdeqy
>Afpqro_fkdFjmif`^qflkpyKyQebfqbjXBj_i^wlkba?^qqibElokZpq^oqpnrbpq*aolmmba_vF`bcfpq%1/)1.&yyNFAy./.14yyRy03523yyWyAo^dlk_ifdeqy

QQebHlo$holkS^kdr^oayKyP^roc^kdqebVlrkdbo%1-+5).5+-&yyNFAy.///1yyWyAo^dlk_ifdeqy
>>rafbk`btfqeqebAo^dlkNrbbkyKyP^roc^kdqebVlrkdbo%1-+5).5+-&yyNFAy./163yyWyAo^dlk_ifdeqy

QAfpqro_fkdFjmif`^qflkpyKy>ro^pqo^pw^%3-+-)22+/&yyNFAy./.14yyWyAo^dlk_ifdeqy
>Lkblc^HfkayKy>ro^pqo^pw^%3-+-)22+/&yyNFAy./.15yyWyAo^dlk_ifdeqy
Q>rafbk`btfqeqebAo^dlkNrbbkyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyNFAy./163yyWyAo^dlk_ifdeqy
>D^i^holka^kaqebP`lrodbyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyNFAy./164yyWyAo^dlk_ifdeqy
QD^i^holka^kaqebP`lrodbyKyQlo^pqo^pw^%26+3)20+2&yyNFAy./164yyWyAo^dlk_ifdeqy
>LkOr_vTfkdpyKyQlo^pqo^pw^%26+3)20+2&yyNFAy./165yyWyAo^dlk_ifdeqy
@LkOr_vTfkdpyKyRpbqebXOr_v?b^`lklcqebAo^dlkNrbbkZ)civrmqlD^i^holka$pObpq%22+3)01+2&qlcfkaqebT^pqbpP`^sbkdbopqebkhfiiQef^ppfqebIfdeqkfkd?ofkdboqlpm^tkDo^kaKb`oliloa>kqflh%21+.)0-+3&yyNFAy./165yyRy050-/yyWyAo^dlk_ifdeqy
@Lkblc^HfkayKyCfka^kahfii?lkbprkabo%2.+/)26+5&yyNFAy./.15yyWyAo^dlk_ifdeqy

QLkblc^HfkayKy>ro^pqo^pw^%3-+-)22+/&yyNFAy./.15yyWyAo^dlk_ifdeqy
>JfdeqvJ^dk^q^royKy>ro^pqo^pw^%3-+-)22+/&yyNFAy./.16yyWyAo^dlk_ifdeqy

@JfdeqvJ^dk^q^royKyCfka^kahfiiF`bpe^qqbo%34+-)2-+-&)?illacb^pq%33+-)4-+-&^kaAo^hbdlob%35+-)1/+-&yyNFAy./.16yyWyAo^dlk_ifdeqy

QJfdeqvJ^dk^q^royKy>ro^pqo^pw^%3-+-)22+/&yyNFAy./.16yyWyAo^dlk_ifdeqy
>Ob`irpfsbOrkbj^pqboyKy>ro^pqo^pw^%3-+-)22+/&yyNFAy./.2-yyWyAo^dlk_ifdeqy
QLkOr_vTfkdpyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyNFAy./165yyWyAo^dlk_ifdeqy
@Ob`irpfsbOrkbj^pqboyKyAobdj^oOrkb_o^ka%4/)2-&yyNFAy./.2-yyWyAo^dlk_ifdeqy
QOb`irpfsbOrkbj^pqboyKy>ro^pqo^pw^%3-+-)22+/&yyNFAy./.2-yyWyAo^dlk_ifdeqy
>T^kqlkT^oiloayKy>ro^pqo^pw^%3-+-)22+/&yyNFAy./.2.yyWyAo^dlk_ifdeqy
@T^kqlkT^oiloayKy?iltqebBj_i^wlkba?^qqibElok^qqebofkdlcqlo`ebp)abcb^qDolj$qe^oqebQerkabo_ofkdbo%24+-)41+6&^ka_ofkdefpeb^a_^`hql>ro^pqo^pw^^qTvojobpq+yyRy03531yyNFAy./.2.yyWyAo^dlk_ifdeqy
QT^kqlkT^oiloayKy>ro^pqo^pw^%3-+-)22+/&yyNFAy./.2.yyWyAo^dlk_ifdeqy

>JvpqbovlcqebFkcfkfqb)ObaruyNFAy.0010yyKy@eoljfb%3-)21+2&yyWyAo^dlk_ifdeqy
@JvpqbovlcqebFkcfkfqb)ObaruyKyRpbqebXElrodi^pplcBqbokfqvZ^qqeb?olkwbAo^dlkpeofkb)^q%4/)06&fkAo^dlk_ifdeqyyRy1112-yyNFAy.0010yyWyAo^dlk_ifdeqy
QJvpqbovlcqebFkcfkfqb)ObaruyNFAy.0010yyKy@eoljfb%3-)21+2&yyWyAo^dlk_ifdeqy

KTvojobpq>``loaA^fifbpyKyPtfq`eqlqebTvojobpq>``loaA^fivdrfab^ka`ljmibqbqeba^fifbprkqfibu^iqba+>iplj^hbprobvlrtb^oqebfoq^_^oabsbovqfjbvlralebolf`arkdlbkpclobsbkjlobobm+Drfab@ljmibqb+y

]]
end)
