DugisGuideViewer:RegisterGuide("Tirisfal Glades (1-12 Undead)", "The Barrens (12-20)", "Horde", "L", function()
return [[
AAA

>Orab>t^hbkfkdyKyRkaboq^hboJloal)qebdrvofdeqlrqpfablcqebpq^oqfkd`ovmq%0-+0)4.+4&yyNFAy030y
QOrab>t^hbkfkdyKyPe^altMofbpqP^osfp)ofdeqaltkqebefii%0-+6)33+/&yyNFAy030y
>QebJfkaibppLkbpyKyPe^altMofbpqP^osfp%0-+6)33+/&yyNFAy031y
@QebJfkaibppLkbpyKyHfii5JfkaibppWlj_fbp^ka5Tobq`ebaWlj_fbpofdeqlrqpfabqltk%01)33&yyNFAy031y
QQebJfkaibppLkbpyKyPe^altMofbpqP^osfp%0-+6)33+/&yyNFAy031y

>O^qqifkdqebO^qqib`^dbpyKyPe^altMofbpqP^osfp%0-+6)33+/&yyNFAy06-.y
>QebA^jkbayKyKlsf`bBiobqe%0-+6)33+.&yyNFAy043y

>Bk`ovmqbaP`oliiy@yOldrbyyKyPe^altMofbpqP^osfp%0-+6)33+/&yyNFAy0-63y
>Q^fkqbaP`oliiy@yT^oil`hyyKyPe^altMofbpqP^osfp%0-+6)33+/&yyNFAy0-66y
>PfjmibP`oliiy@yT^oofloyyKyPe^altMofbpqP^osfp%0-+6)33+/&yyNFAy0-62y
>Divmef`P`oliiy@yJ^dbyyKyPe^altMofbpqP^osfp%0-+6)33+/&yyNFAy0-65y
>E^iiltbaP`oliiy@yMofbpqyyKyPe^altMofbpqP^osfp%0-+6)33+/&yyNFAy0-64y

QBk`ovmqbaP`oliiy@yOldrbyyKyA^sfaQof^p%0/+2)32+3&yyNFAy0-63y
QQ^fkqbaP`oliiy@yT^oil`hyyKyJ^ufjfiiflk%0-+6)33+0&yyNFAy0-66y
QPfjmibP`oliiy@yT^oofloyyKyA^kk^iPqbok%0-+6)33+.&yyNFAy0-62y
QDivmef`P`oliiy@yJ^dbyyKyFp^_bii^%0-+6)33+/&yyNFAy0-65y
QE^iiltbaP`oliiy@yMofbpqyyKyA^oh@ibof`Arbpqbk%0.+.)33+.&yyNFAy0-64y

@QebA^jkbayKyHfiitlisbp^ka_^qpqlqebplrqeclo3XP`^sbkdboM^tpZ^ka3XArph_^qTfkdpZ^olrka%01)24&yyNFAy043y
@O^qqifkdqebO^qqib`^dbpyKyHfii./O^qqib`^dbPhbibqlkpplrqelcqltk%01)33&yyNFAy06-.y

QQebA^jkbayKyKlsf`bBiobqe%0-+6)33+.&yyNFAy043y
QO^qqifkdqebO^qqib`^dbpyKyPe^altMofbpqP^osfp%0-+6)33+/&yyNFAy06-.y
>J^oi^$pI^pqTfpeyKyKlsf`bBiobqe%0-+6)33+.&yyNFAy3062y
>KfdeqTb_$pEliiltyKyBub`rqlo>oobk%0/+.)33+-&yyNFAy05-y
>P`^sbkdfkdAb^qehkbiiyKyAb^qedr^oaP^iq^fk%0.+4)32+3&yyNFAy06-/y

@KfdeqTb_$pEliiltyKyHfii5VlrkdKfdeqTb_Pmfabop^ka2KfdeqTb_Pmfabopfkqeb`^sbqlqebkloqe%/4+2)25+-&yyNFAy05-y
HP^jrbiCfmmpyIy.3000yyKyQ^hbqebol^akloqe)qebkb^pq+P^jrbi$pfk^ifqqib`^jmgrpqplrqelcqebol^a%03)3/&yyNFAy05/y
@P`^sbkdfkdAb^qehkbiiyKyIllqqeb_lubp^iilsboAb^qehkbii%01)33&yyNFAy06-/y

QP`^sbkdfkdAb^qehkbiiyKyAb^qedr^oaP^iq^fk%0.+4)32+3&yyNFAy06-/y
@J^oi^$pI^pqTfpeyKy?rovXP^jrbi$pObj^fkpZ^qJ^oi^$pDo^sb%0.+.4)32+-2&yyRy.3000yyNFAy3062y
QKfdeqTb_$pEliiltyKyBub`rqlo>oobk%0/+.)33+-&yyNFAy05-y
>QebP`^oibq@orp^abyKyBub`rqlo>oobk%0/+.)33+-&yyNFAy05.y
QJ^oi^$pI^pqTfpeyKyKlsf`bBiobqe%0-+6)33+.&yyNFAy3062y

@QebP`^oibq@orp^abyKyD^qebo./XP`^oibq>oj_^kapZcoljP`^oibq@lksboqp^kaP`^oibqFkfqf^qbpfk^`^jmb^pqlcqltk%03+-)34+2&yyNFAy05.y
QQebP`^oibq@orp^abyKyBub`rqlo>oobk%0/+.)33+-&yyNFAy05.y
>QebObaJbppbkdboyKyBub`rqlo>oobk%0/+.)33+-&yyNFAy05/y
@QebObaJbppbkdboyKyHfiiJbsbkHlod^i^qqebp^jb`^jm%03+15)35+45&yyNFAy05/y
QQebObaJbppbkdboyKyBub`rqlo>oobk%0/+.)33+-&yyNFAy05/y
>Sfq^iFkqbiifdbk`byKyBub`rqlo>oobk%0/+.)33+-&yyNFAy050y
>>Oldrb$pAb^i%M^oq.&yKy@^isfkJlkq^drb)lkqebt^vlrqlcAb^qehkbii%05+/)23+5&yyNFAy5y
>CfbiaplcDofbc%M^oq.&yKyAb^qedr^oaPfjjbo%1-+6)21+/&yyNFAy032y
>Dloal$pQ^phyKyDloaltef`em^qolipqebol^aql?ofii%1/)2.&ql%22)20&yyNFAy215.y

O?ofiiyKyOrkql?ofii%25+/)2.+2&yyNFAy1-1y
>>MrqofaQ^phyKyAb^qedr^oaAfiifkdbo%25+/)2.+2&yyNFAy1-1y
QSfq^iFkqbiifdbk`byKyBub`rqloWvd^ka%3-+3)2.+5&yyNFAy050y
>>qT^oTfqeQebP`^oibq@orp^ab%M^oq.&yKyBub`rqloWvd^ka%3-+3)2.+5&yyNFAy1/4y
Q>Oldrb$pAb^i%M^oq.&yKyFkkhbbmboObkbb%3.+4)2/+.&yyNFAy5y
eD^iiltp$BkaQ^sbokyKyFkkhbbmboObkbb%3/+4)2/+.&yyNFAy034y
>>KbtMi^drb%M^oq.&yKy>mlqeb`^ovGle^^k%26+2)2/+0&yyNFAy034y

>>Oldrb$pAb^i%M^oq/&yKy@^isfkJlkq^drb)lkqebt^vqlAb^qehkbii%05+/)23+5&yyNFAy26-y
@>Oldrb$pAb^i%M^oq/&yKyAbcb^q@^isfkJlkq^drb%05+/)23+5&yyNFAy26-y
Q>Oldrb$pAb^i%M^oq/&yKy@^isfkJlkq^drb%05+/)23+5&yyNFAy26-y

@CfbiaplcDofbc%M^oq.&yKyPqb^i.-XQfofpc^iMrjmhfkpZcoljqebc^ojqlqebtbpq)grpqkloqelcAb^qehkbii%02)2-&yyNFAy032y
@>qT^oTfqeQebP`^oibq@orp^ab%M^oq.&yKyHfii.-P`^oibqT^oofloptbpqlcqebc^oj%01)15&yyNFAy1/4y
@Dloal$pQ^phyKyMf`hXDilljTbbapZ^iilsboqeb^ob^_bqtbbkAb^qehkbii^ka?ofii+Qov^olrka%1.)16&^ka%1/)2-&yyNFAy215.y
@>MrqofaQ^phyKyHfiiolqqfkdab^a^kao^s^dba`lompbptbpqlc?ofiiclo4XMrqofa@i^tpZ%2.)22&yyNFAy1-1y
@>KbtMi^drb%M^oq.&yKyHfiiA^ohelrkapclo2XA^ohelrka?illaZ^olrka%25)3-&yyNFAy034y

E?ofiiyPWyD^iiltp$BkaQ^sbokyyRy3615yyNFAy021y
>Ab^qepfkqebC^jfivyKy@libj^kC^oqefkd%3.+4)2/+0&yyNFAy021y
>QebE^rkqbaJfiipyKy@libj^kC^oqefkd%3.+4)2/+0&yyNFAy03/y
Q>qT^oTfqeQebP`^oibq@orp^ab%M^oq.&yKyBub`rqloWvd^ka%3-+3)2.+5&yyNFAy1/4y
>>qT^oTfqeQebP`^oibq@orp^ab%M^oq/&yKyBub`rqloWvd^ka%3-+3)2.+5&yyNFAy04-y
QCfbiaplcDofbc%M^oq.&yKy>mlqeb`^ovGle^^k%26+2)2/+0&yyNFAy032y
>CfbiaplcDofbc%M^oq/&yKy>mlqeb`^ovGle^^k%26+2)2/+0&yyNFAy1-4y
Q>KbtMi^drb%M^oq.&yKy>mlqeb`^ovGle^^k%26+2)2/+0&yyNFAy034y
>>KbtMi^drb%M^oq/&yKy>mlqeb`^ovGle^^k%26+2)2/+0&yyNFAy035y
Q>MrqofaQ^phyKyAb^qedr^oaAfiifkdbo%25+/)2.+2&yyNFAy1-1y
>QebJfiipLsboorkyKyAb^qedr^oaAfiifkdbo%25+/)2.+2&yyNFAy1/3y
QDloal$pQ^phyKyGrkflo>mlqeb`^ovElii^ka)T^kabofkd^olrkafkqebdo^sbv^oa%25)15&yyNFAy215.y
>AlljTbbayKyGrkflo>mlqeb`^ovElii^ka%25)15&yyNFAy215/y
>MollclcAbjfpbyKyAb^qedr^oa?rodbpp%3-+6)2/&yyNFAy041y
>Do^sbol__bopyKyJ^dfpqo^qbPbsobk%3.+2)2-+5&yyNFAy025y
>T^kqba7J^ddlqBvbyKyColjqebT^kqbapfdk%3-+4-)2.+3-&yyNFAy065y
QCfbiaplcDofbc%M^oq/&yKyQ^hbqebXI^`baMrjmhfkZqlqeb@^mqrobaP`^oibqWb^ilq%3.+6)2.+0&fkqeb`bii^olcqebfkkyyNFAy1-4y
>Qeb@efiilcAb^qeyKyDobq`ebkAbaj^o)rmpq^fopfkqebfkk%3.+56)2/+32&yyNFAy042y

?@l^opbQeob^ayKy?rvqebX@l^opbqeob^aZcolj>_fd^fiPefbifk?ofii%3.)2/+2&yyIy/0/-yyNFAy036y
@Qeb@efiiLcAb^qeyKy@liib`q3uXArph_^qMbiqpZaolmcoljqebArph_^qpgrpqlrqpfabqltk%24)23&yyNFAy042y
@>KbtMi^drb%M^oq/&yKyD^qebo2XSfibCfkP`^ibpZcoljJroil`p^ilkdqebpelob%3-)/6&yyNFAy035y
@T^kqba7J^ddlqBvbyKyHfiiefjfkqebelrpb^qqebkloqebkalcD^oobk$pE^rkq%25+4)0.+4&yyNFAy065y
@Do^sbol__bopyKyHfiiOlqEfabDo^sbol__bop^kaOlqEfabJlkdobipclo5lcqebXBj_^ijfkdF`elopZ^olrka%26)02&yyNFAy025y
@AlljTbbayKy@liib`q.-XAlljTbbaZgrpqkloqelcqeb?ofii$pDo^sbv^oa%22)1/&yyNFAy215/y

QAlljTbbayKyGrkflo>mlqeb`^ovElii^ka%25)15&yyNFAy215/y
Q>KbtMi^drb%M^oq/&yKy>mlqeb`^ovGle^^k%26+14)2/+01&yyNFAy035y
>>KbtMi^drb%M^oq0&yKy>mlqeb`^ovGle^^k%26+14)2/+01&yyNFAy036y
QT^kqba7J^ddlqBvbyKyBub`rqloWvd^ka%3-+3)2.+5&yyNFAy065y
QDo^sbol__bopyKyJ^dfpqo^qbPbsobk%3.+2)2-+5&yyNFAy025y
>Clop^hbkArqfbpyKyJ^dfpqo^qbPbsobk%3.+2)2-+5&yyNFAy026y
>QebMolafd^iIf`eyKyJ^dfpqo^qbPbsobk%3.+2)2-+5&yyNFAy1-2y
QQeb@efiilcAb^qeyKyDobq`ebkAbaj^o)rmpq^fopfkqebfkk%3.+56)2/+32&yyNFAy042y

>Pmb^htfqeAfiifkdboy@yT^oofloyyKy>rpqfiabJlk%3.+5)2/+2&yyNFAy.5.5y
QPmb^htfqeAfiifkdboy@yT^oofloyyKyAb^qedr^oaAfiifkdbo%25+/)2.+2&yyNFAy.5.5y
>Ri^dqeb@ib^sboy@yT^oofloyyKyAb^qedr^oaAfiifkdbo%25+/)2.+2&yyNFAy.5.6y
@Ri^dqeb@ib^sboy@yT^oofloyyKy>`qfs^qbqebibsbi^q%26+/)15+2&^kahfiiRi^dqeb@ib^sboyyNFAy.5.6y
QRi^dqeb@ib^sboy@yT^oofloyyKyAb^qedr^oaAfiifkdbo%25+/)2.+2&yyNFAy.5.6y
>Pmb^htfqe@libj^ky@yT^oofloyyKyAb^qedr^oaAfiifkdbo%25+/)2.+2&yyNFAy.5/-y
QPmb^htfqe@libj^ky@yT^oofloyyKy@libj^kC^oqefkd%3.+4)2/+0&yyNFAy.5/-y
>>d^j^kaEbfoilljpy@yT^oofloyyKy@libj^kC^oqefkd%3.+4)2/+0&yyNFAy.5/.y

@QebE^rkqbaJfiipyKyPi^vAbsifk>d^j^ka^kaillqefpObj^fkp%14)1-&yyNFAy03/y
HKfpp^>d^j^kayKyHfiiKfpp^>d^j^ka^kaillqeboobj^fkp%16+2)02+1&yyIy/5/5yyNFAy021y
HDobdlo>d^j^kayKyHfiiDobdlo>d^j^ka^kaillqefpobj^fkp%12)/6&yyIy/5/6yyNFAy021y
@Ab^qepfkqebC^jfivyKyHfiiQeroj^k>d^j^ka^kaillqefpobj^fkp%10)0/&yyNFAy021y
@QebJfiipLsboorkyKyHfiiqebP`lrodb^q>d^j^kaJfiip^kad^qebo2XKlq`ebaOf_pZ^ka0X?i^`hbkbaPhriipZ^olrka%13)05&yyNFAy1/3y
@>d^j^kaEbfoilljpy@yT^oofloyyKyDlfkqlqebqlj_^q%2/)/4&^ka`liib`qqeb>d^j^kaEbfoilljpyyNFAy.5/.y

E?ofiiyPWyD^iiltp$BkaQ^sbokyyRy3615yyNFAy022y
Q>d^j^kaEbfoilljpy@yT^oofloyyKy@libj^kC^oqefkd%3.+4)2/+0&yyNFAy.5/.y
QEbfoilljTb^mlky@yT^oofloyyKy@libj^kC^oqefkd%3.+4)2/+0&yyNFAy.5//y
QAb^qepfkqebC^jfivyKy@libj^kC^oqefkd%3.+4)2/+0&yyNFAy021y
QQebE^rkqbaJfiipyKy@libj^kC^oqefkd%3.+4)2/+0&yyNFAy03/y
>Pmb^htfqePbsobkyKy@libj^kC^oqefkd%3.+4)2/+0&yyNFAy022y
>>IbqqboRkabifsbobayRy/506yyLyyNFAy03.yyKyQebfqbjX>IbqqboqlVsbqqbZpq^oqpnrbpq*aolmmba^olrka%13)01&y
Q>IbqqboRkabifsbobayLyyKyVsbqqbC^oqefkd%3.+3)2/+3&yyNFAy03.y
QPmb^htfqePbsobkyKyJ^dfpqo^qbPbsobk%3.+2)2-+5&yyNFAy022y
>QebC^jfiv@ovmqyKyJ^dfpqo^qbPbsobk%3.+2)2-+5&yyNFAy1-5y
QQebJfiipLsboorkyKyAb^qedr^oaAfiifkdbo%25+/)2.+2&yyNFAy1/3y
>E^id^o$pPrjjlkpy@yT^oil`hyyOyRkab^ayyKy>dbolkH^od^i%3.+3)2/+3&yyNFAy.145y

QClop^hbkArqfbpyKyAb^qedr^oaIfkkb^)plrqeb^pqlc?ofii^qqeb`^jmcfob%32+2)3-+/&yyNFAy026y
>ObqrokqlqebJ^dfpqo^qbyKyAb^qedr^oaIfkkb^%32+2)3-+/&yyNFAy03-y
>Ob^oDr^oaM^qoliyKyAb^qedr^oaIfkkb^%32+2)3-+/&yyNFAy023y
@Ob^oDr^oaM^qoliyKyHfii5?ibbafkdEloolop^ka5T^kabofkdPmfofqp^qqebc^ojcroqebob^pqaltkqebol^a%42)3-&yyNFAy023y
QOb^oDr^oaM^qoliyKyAb^qedr^oaIfkkb^%32+2)3-+/&yyNFAy023y
QObqrokqlqebJ^dfpqo^qbyKyJ^dfpqo^qbPbsobk%3.+2)2-+5&yyNFAy03-y

ORkabo`fqvyKyOrkqlRkabo`fqv%3.+3)35+4&yyNFAy024y
QQebMolafd^iIf`eyWyRkabo`fqvyyKy?bqeloF`bpe^oa)fkqebj^df`nr^oqbo%51+0).4+2&yyNFAy1-2y
>QebIf`e$pFabkqfqvyWyRkabo`fqvyyKy?bqeloF`bpe^oa%51+0).4+2&yyNFAy024y
K>``bmqQebAb^qepq^ihbopy@yOldrbyyWyRkabo`fqvyyKyJbkkbq@^oh^a%50+0)36&)qf`hqefppqbmlk`bvlr^``bmqqebnrbpqy
>QebAb^qepq^ihbopy@yOldrbyyWyRkabo`fqvyyKyJbkkbq@^oh^a%50+0)36&yyNFAy.553yyLy
>QebAb^qepq^ihbopy@yOldrbyyWyRkabo`fqvyyKyJbkkbq@^oh^a%50+0)36&yyNFAy.11/-yyLy

QE^id^o$pPrjjlkpy@yT^oil`hyyOyRkab^ayyKy@^obkafkE^id^o%3.+3)2/+3&yyWyRkabo`fqvyyNFAy.145y
>@ob^qroblcqebSlfay@yT^oil`hyyOyRkab^ayyKy@^obkafkE^id^o%3.+3)2/+3&yyWyRkabo`fqvyyNFAy.140y

OQfofpc^iDi^abpyKyBufqqeolrdeqlqebpbtbop%.2+/)0.+1&yyWyRkabo`fqvyyNFAy04.y
@@ob^qroblcqebSlfay@yT^oil`hyyOyRkab^ayyKyDbqXBd^ifk$pDofjlfobZfkpfabMboofkb$p@ebpq%2.+.)34+3&yyWyRkabo`fqvyyNFAy.140y
@>qT^oTfqeQebP`^oibq@orp^ab%M^oq/&yKyIb^sbRkabo`fqvqeolrdeqebpbtbop^kahfii@^mq^fkMboofkb)0P`^oibqWb^ilqp^ka0P`^oibqJfppflk^ofbp%2.)34&yyNFAy04-y
@MollclcAbjfpbyKyD^qebo.-XP`^oibqFkpfdkf^OfkdpZtef`e^obaolmmba_vqebP`^oibq@orp^ab%2.)34&yyNFAy041y
@QebAb^qepq^ihbopy@yOldrbyyKyHfii>pqloE^aobk^kaq^hbefpibqqbo+Ebm^qolipqebol^acolj?ofiiqlPbmri`ebo%30)23&)%21)40&yyNFAy.553yyLy
@QebAb^qepq^ihbopy@yOldrbyyKyHfii>pqloE^aobk^kaq^hbefpibqqbo+Ebm^qolipqebol^acolj?ofiiqlPbmri`ebo%30)23&)%21)40&yyNFAy.11/-yyLy

Q>qT^oTfqeQebP`^oibq@orp^ab%M^oq/&yKyBub`rqloWvd^ka%3-+3)2.+5&yyNFAy04-y
>>qT^oTfqeQebP`^oibq@orp^ab%M^oq0&yKyBub`rqloWvd^ka%3-+3)2.+5&yyNFAy04.y
QMollclcAbjfpbyKyAb^qedr^oa?rodbpp%3-+6)2/&yyNFAy041y

@QebIf`e$pFabkqfqvyKyIllqXQebIf`e$pPmbii_llhZlkqebfpi^ka%34+60)1/+.2&yyNFAy024y
@>qT^oTfqeQebP`^oibq@orp^ab%M^oq0&yKyHfii@^mq^fkS^`elkfkpfab^qltbo`^iiba@orp^aboLrqmlpq%45)23&^ptbii^pqebp`^oibqCof^optef`e^obp`^qqbobaqeolrdelrqqefp^ob^yyNFAy04.y
@>KbtMi^drb%M^oq0&yKyHfiiqebSf`flrpKfdeqTb_Pmfabop%53)2.+2&clo1XSf`flrpKfdeqTb_PmfaboSbkljZyyNFAy036y

E?ofiiyPWyD^iiltp$BkaQ^sbokyyRy3615yyNFAy04/y
Q>qT^oTfqeQebP`^oibq@orp^ab%M^oq0&yKyBub`rqloWvd^ka%3-+3)2.+5&yyNFAy04.y
>>qT^oTfqeQebP`^oibq@orp^ab%M^oq1&yKyBub`rqloWvd^ka%3-+3)2.+5&yyNFAy04/y
Q>KbtMi^drb%M^oq0&yKy>mlqeb`^ovGle^^k%26+2)2/+0&yyNFAy036y
>>KbtMi^drb%M^oq1&yKy>mlqeb`^ovGle^^k%26+2)2/+0&yyNFAy16/y
Q>KbtMi^drb%M^oq1&yKy@^mqrobaJlrkq^fkbbo%3.+6)2.+0&fkqeb_^pbjbkqlcqebfkkyyNFAy16/y
>Jbkkbq@^oh^ay@yOldrbyyKyJ^oflk@^ii%3.+4)2/+.&yyNFAy.552y

ORkabo`fqvyKyOrkqlRkabo`fqv%3.+3)35+4&yyNFAy033y
QQebIf`e$pFabkqfqvyWyRkabo`fqvyyKy?bqeloF`bpe^oa%51+0).4+2&yyNFAy024y
>Obqrokqeb?llhyWyRkabo`fqvyyKy?bqeloF`bpe^oa%51+0).4+2&yyNFAy033y

Q@ob^qroblcqebSlfay@yT^oil`hyyOyRkab^ayyKy@^obkafkE^id^o%3.+3)2/+3&yyWyRkabo`fqvyyNFAy.140y
>Qeb?fkafkdy@yT^oil`hyyOyRkab^ayyKy@^obkafkE^id^o%3.+3)2/+3&yyWyRkabo`fqvyyNFAy.14.y
@Qeb?fkafkdy@yT^oil`hyyOyRkab^ayyKyRpbXOrkbplcPrjjlkfkdZqlprjjlk^kahfiiqebSlfat^ihboyyWyRkabo`fqvyyRy3/51yyNFAy.14.y
QQeb?fkafkdy@yT^oil`hyyOyRkab^ayyKy@^obkafkE^id^o%3.+3)2/+3&yyWyRkabo`fqvyyNFAy.14.y

QJbkkbq@^oh^ay@yOldrbyyKyJ^oflk@^ii%3.+4)2/+.&yyNFAy.552y
QQebAb^qepq^ihbopy@yOldrbyyWyRkabo`fqvyyKyJbkkbq@^oh^a%50+0)36&yyNFAy.553yyLy
QQebAb^qepq^ihbopy@yOldrbyyWyRkabo`fqvyyKyJbkkbq@^oh^a%50+0)36&yyNFAy.11/-yyLy

QObqrokqeb?llhyKyObqrokqeb_llhqlqebfpi^ka%35+.5)1.+65&yyNFAy033y
>Molsfkd>iibdf^k`byKyDrkqebo>o`^krp%35+/)1/&yyNFAy1-6y
@Molsfkd>iibdf^k`byKyDo^_^`^kaibcoljqeb`o^qb)qebkprjjlkIfiifqe^qqebq^_iblkqebfpi^kaqlqebplrqe%33+3)11+5&yyNFAy1-6y
QMolsfkd>iibdf^k`byKyDrkqebo>o`^krp%35+/)1/&yyNFAy1-6y
>QebMolafd^iIf`eObqrokpyKyDrkqebo>o`^krp%35+/)1/&yyNFAy1..y
@>qT^oTfqeQebP`^oibq@orp^ab%M^oq1&yKyHfii@^mq^fkJbio^`eb^kaefpqtl_lavdr^oap%46)/3&yyNFAy04/y

Q>qT^oTfqeQebP`^oibq@orp^ab%M^oq1&yKyBub`rqloWvd^ka%3-+3)2.+5&yyNFAy04/y
@QebC^jfiv@ovmqyKyEb^afkpfabqebC^jfiv@ovmq^q>d^j^kaJfiip%2.)/4&tebobvlrpelriahfii5T^fifkd>k`bpqlop^ka5Olqqfkd>k`bpqlop+Hfii@^mq^fkA^odli^kaq^hbefpphriiyyNFAy1-5y
QQebC^jfiv@ovmqyKyJ^dfpqo^qbPbsobk%3.+2)2-+5&yyNFAy1-5y
QQebMolafd^iIf`eObqrokpyWyRkabo`fqvyyKy?bqeloF`bpe^oa%51+0).4+2&yyNFAy1..y

KDelpqi^kap<yKyVlrj^vtfpeqlibsbirkqfi/-fkDelpqi^kapfkpqb^alcqeb?^oobkp+Qebob^obpljbsbovkf`bobt^oapcoljQo^knrfiifbkclo^ii`i^ppbp+Fcvlrtfpeqlalqefp)mloqqlPfisbojllkcoljqebLo_lcQo^kpobil`^qflk%21+6)..+0&qebkorkplrqeqlqebDelpqi^kap+Ptfq`elsboqlqebDelpqi^kapdrfab)lc`lropbyyWyRkabo`fqvy

CLodofjj^oyKyQ^hbqebwbmmbifklrqpfabRkabo`fqv)b^pqqltbo%3-+4)25+4&y
OLodofjj^oyKyOrkqlLodofjj^o%12)5&yyWyArolq^oy
cLodofjj^oyKyAlo^p)lkqlmlcqebqltbo^qqeb`bkqbolcLodfjj^o%12+0)31&yyWyLodofjj^oy
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)

--[[
A Piercing the Veil |C|Warlock| |N|Venya Marthand (31.0, 66.3)| |QID|1470| 
C Piercing the Veil |C|Warlock| |N|Kill Rattlecage Skeletons just outside town and gather 3 [Rattlecage Skulls] around (34, 66)| |QID|1470|
T Piercing the Veil |C|Warlock| |N|Venya Marthand (31.0, 66.3)| |QID|1470| 
]]
