DugisGuideViewer:RegisterGuide("Durotar (1-12 Orc & Troll)", "The Barrens (12-20)", "Horde", "L", function()
return [[
AAA

>VlroMi^`bFkQebTloiayKyH^iqrkh%10+0)35+3&yyNFAy131.y
KHfii>pVlroQo^sbi++yKyFkm^q`e0+0?ifww^oae^sbj^abfqb^pfboclokbtmi^vbopqlibsbirm_vj^hfkdqebKM@klk*^ddobpfsb)vlrtfiipqfiikbbaqlhfiiqebj^pvlrqo^sbiqlj^hbprobvlr$obibsbi2_bclobvlrib^sbqebS^iibvlcQof^ipqlPbkgfkSfii^db+T^oil`hpfkm^oqf`ri^o^objfppfkdnrbpqp^pqebobpriqlcqebobjls^ilc`lj_^qmbqnrbpqp+yyNFAy131.y
QVlroMi^`bFkQebTloiayKyDlokbh%1/+.)35+1&yyNFAy131.y
>@rqqfkdQbbqeyKyDlokbh%1/+.)35+1&yyNFAy455y
@@rqqfkdQbbqeyKyHfii5Jlqqiba?l^opfkqebS^iibvlcQof^ip%11+2)33+.&yyNFAy455y
>P^ohlqe%M^oq.&yKyE^k^$wr^)tbpqbokm^oqlcS^iibvlcQof^ip%1-+3)3/+3&yyNFAy46-y
@P^ohlqe%M^oq.&yKyHfiiP^ohfqeplrqelcqebnrbpqdfsbo%1-+3)34+.&yyNFAy46-y
QP^ohlqe%M^oq.&yKyE^k^$wr^%1-+3)3/+3&yyNFAy46-y
>P^ohlqe%M^oq/&yKyE^k^$wr^%1-+3)3/+3&yyNFAy5-1y
QP^ohlqe%M^oq/&yKyDlokbh%1/+.)35+1&yyNFAy5-1y
Q@rqqfkdQbbqeyKyDlokbh%1/+.)35+1&yyNFAy455y

>PqfkdlcqebP`lomfayKyDlokbh%1/+.)35+1&yyNFAy456y

>Bq`ebaM^o`ejbkqy@yErkqboyyOyLo`yyKyDlokbh%1/+.)35+1&yyNFAy0-54y
>Bq`ebaQ^_ibqy@yErkqboyyOyQoliiyyKyDlokbh%1/+.)35+1&yyNFAy0-5/y
>Orkb*Fkp`of_baQ^_ibqy@yPe^j^kyyOyQoliiyyKyDlokbh%1/+.)35+1&yyNFAy0-51y
>Orkb*Fkp`of_baM^o`ejbkqy@yPe^j^kyyOyLo`yyKyDlokbh%1/+.)35+1&yyNFAy0-56y
>Divmef`Q^_ibqy@yJ^dbyyKyDlokbh%1/+.)35+1&yyNFAy0-53y
>Bk`ovmqbaM^o`ejbkqy@yOldrbyyOyLo`yyKyDlokbh%1/+.)35+1&yyNFAy0-55y
>Bk`ovmqbaQ^_ibqy@yOldrbyyOyQoliiyyKyDlokbh%1/+.)35+1&yyNFAy0-50y
>E^iiltbaQ^_ibqy@yMofbpqyyKyDlokbh%1/+.)35+1&yyNFAy0-52y
>PfjmibQ^_ibqy@yT^oofloyyOyQoliiyyKyDlokbh%1/+.)35+1&yyNFAy0-32y
>PfjmibM^o`ejbkqy@yT^oofloyyOyLo`yyKyDlokbh%1/+.)35+1&yyNFAy/050y
>Q^fkqbaM^o`ejbkqy@yT^oil`hyyKyDlokbh%1/+.)35+1&yyNFAy0-6-y

QBq`ebaQ^_ibqy@yErkqboyyOyLo`yyKyGbk$pe^k%1/+5)36+0&yyNFAy0-54y
QBq`ebaQ^_ibqy@yErkqboyyOyQoliiyyKyGbk$pe^k%1/+5)36+0&yyNFAy0-5/y
QOrkb*Fkp`of_baQ^_ibqy@yPe^j^kyyOyQoliiyyKyPefhofh%1/+1)36&yyNFAy0-51y
QOrkb*Fkp`of_baM^o`ejbkqy@yPe^j^kyyOyLo`yyKyPefhofh%1/+1)36&yyNFAy0-56y
QDivmef`Q^_ibqy@yJ^dbyyKyJ^f$^e%1/+2)36&yyNFAy0-53y
QBk`ovmqbaM^o`ejbkqy@yOldrbyyOyLo`yyKyOt^d%1.+0)35+.&yyNFAy0-55y
QBk`ovmqbaQ^_ibqy@yOldrbyyOyQoliiyyKyOt^d%1.+0)35+.&yNFAy0-50y
QE^iiltbaQ^_ibqy@yMofbpqyyKyHbk$g^f%1/+1)35+5&yyNFAy0-52y
QPfjmibQ^_ibqy@yT^oofloyyOyQoliiyyKyCo^kd%1/+6)36+1&yyNFAy0-32y
QPfjmibM^o`ejbkqy@yT^oofloyyOyLo`yyKyCo^kd%1/+6)36+1&yyNFAy/050y
QQ^fkqbaM^o`ejbkqy@yT^oil`hyyKyK^oqlh%1-+3)35+1&yyNFAy0-6-y

>SfibC^jfif^opyKyWrobbqe^C^od^wb%1/+6)36+.&yyNFAy46/y
>D^id^o$p@^`qrp>mmibPromofpbyKyD^id^o%1/+4)34+0&yyNFAy11-/y
>I^wvMblkpyKyClobj^kQe^ww$ofi%11+3)35+3&yyNFAy211.y

@I^wvMblkpyKyEfqqebpibbmfkdmblkpfkqebS^iibvlcQof^ip)%12+3)32+4&)%1-)3-&)%1.)25&)%1/)24&)%10)24&)%14)24&yyRy.3..1yyNFAy211.y
@D^id^o$p@^`qrp>mmibPromofpbyKyIllq3X@^`qrp>mmibpZcoljqeb@^`qrpMi^kqpfkqebS^iibv%13)30&yyNFAy11-/y
@PqfkdlcqebP`lomfayKyDbq5XP`lomfaTlohboQ^fipZcoljqebP`lomfapfkqebS^iibv%1-+5)3/+.&yyNFAy456y
@SfibC^jfif^opyKyHfii5uSfibC^jfif^op%12)23&yyNFAy46/y

QD^id^o$p@^`qrp>mmibPromofpbyKyD^id^o%1/+4)34+0&yyNFAy11-/y
QPqfkdlcqebP`lomfayKyDlokbh%1/+.)35+1&yyNFAy456y
>@^iilcB^oqe%M^oq.&y@yPe^j^kyyKy@^k^d^B^oqe`^iibo%1/+1)36+.&yyNFAy.2.3y
QSfibC^jfif^opyKyOrw^k%1/+3)35+6&yyNFAy46/y

>?rokfkd?i^abJba^iiflkyKyWrobbqe^C^od^wb%1/+6)36+.&yyNFAy461y
QI^wvMblkpyKyClobj^kQe^ww$ofi%11+3)35+3&yyNFAy211.y
>Qe^ww$ofi$pMf`hyKyClobj^kQe^ww$ofi%11+3)35+3&yyNFAy3061y

@Qe^ww$ofi$pMf`hyKyFkqeb`^sb^qKloqebkalcS^iibvlcQof^ip+Dlpqo^fdeq^eb^a^qqebcloh%10+4)20+4&yyNFAy3061y
@?rokfkd?i^abJba^iiflkyKyDl_^`hqlqebcloh^kaq^hbqebkloqebokm^qe%1/+4)2/+6&yyNFAy461y
@@^iilcB^oqe%M^oq.&y@yPe^j^kyyKyHfiiqebCbipq^ihbop%12)21+2&cloqebfoEllsbpfkpfabqeb`^sb^ptbiiyyNFAy.2.3y

ES^iibvlcQof^ipyRy3615yyNFAy/.3.y
Q?rokfkd?i^abJba^iiflkyKyWrobbqe^C^od^wb%1/+6)36+.&yyNFAy461y
>ObmloqqlPbk$gfkSfii^dbyKyWrobbqe^C^od^wb%1/+6)36+.&yyNFAy5-2y
Q@^iilcB^oqe%M^oq.&y@yPe^j^kyyKy@^k^d^B^oqe`^iibo%1/+1)36+.&yyNFAy.2.3y
>@^iilcB^oqe%M^oq/&y@yPe^j^kyyKy@^k^d^B^oqe`^iibo%1/+1)36+.&yyNFAy.2.4y
Q@^iilcB^oqe%M^oq/&y@yPe^j^kyyKyEb^aplrqe*tbpqqlqebEfaabkM^qe%1.+3)40+/&qebkcliiltqebm^qeqlqebPmfofqOl`h%11)43+.&rpbXB^oqeP^mq^Z_vqebPqlkbyyNFAy.2.4yyRy3302y
>@^iilcB^oqe%M^oq0&y@yPe^j^kyyKyJfkloJ^kfcbpq^qflklcB^oqe%11+-)43+.&yyNFAy.2.5y
Q@^iilcB^oqe%M^oq0&y@yPe^j^kyyKy@^k^d^B^oqe`^iibo%1/+1)36+.&yyNFAy.2.5y
QQe^ww$ofi$pMf`hyKyClobj^kQe^ww$ofi%11+3)35+3&yyNFAy3061y
>>Mblk$p?roabkyKyRhlo%2/+-)35+0&)B^pqlrqlcqebS^iibvlcQof^ipyyNFAy/.3.y

OPbk$gfkSfii^dbyKyOrkqlPbk$gfkSfii^db%21+2)42&yyNFAy453y
>Qet^oqfkdHlih^o>ddobppflkyKyI^oMoltiqrph)TbpqlcPbk$gfkSfii^db%21+2)42&yyNFAy453y
QObmloqqlPbk$gfkSfii^dbyKyJ^pqboD^aofk%23)41+4&yyNFAy5-2y
>Jfkpefk^$pPhriiyKyJ^pqboD^aofk%23)41+4&yyNFAy5-5y
>@ib^krmlkFpibB+yKyJ^pqboD^aofk%23)41+4&yyNFAy/362.y
>ObmloqqlLodkfiyKyJ^pqboD^aofk%23)41+4&yyNFAy5/0y
>>PlisbkqPmfofqyKyJ^pqboSlok^i%23)41+2&yyNFAy5.5y
>Mo^`qf`^iMobvyKySbi$ofkC^kd%22+6)41&yyNFAy5.4y

KIbsbi3yKyJ^hbprobvlr$obibsbi3plvlr`^kmf`hrm^iiqebnrbpqp^qO^wloEfiiyyNFAy5/0yyMIy3y
OO^wloEfiiyKyCliiltqebol^akloqeqlO^wloEfii%2/+0)10+/&yyNFAy5-3y
QObmloqqlLodkfiyKyLodkfiPlrip`^o%2/+0)10+/&yyNFAy5/0y
>A^ohPqlojpyKyLodkfiPlrip`^o%2/+0)10+/&yyNFAy5-3y
>S^knrfpeqeb?bqo^vbopyKyD^o$Qelh%2.+6)10+2&yyNFAy451y
>Bk`ol^`ejbkqyKyD^o$Qelh%2.+6)10+2&yyNFAy504y
>?ob^h^CbtBddpyKy@llhQloh^%2.+/)1/+2&yyNFAy5.2y
Q>Mblk$p?roabkyKyFkkhbbmboDolph%2.+3)1.+4&yyNFAy/.3.y
eO^wloEfiiyKyFkkhbbmboDolph%2.+3)1.+4&yyNFAy46.y
>@^oovVlroTbfdeqyKyCroiP`lok_oltfkqebt^q`eqltbokloqetbpqlcqltk%16+6)1-+0&yyNFAy46.y

@S^knrfpeqeb?bqo^vbopyKyHfii.-p^filop)5j^ofkbp^kaqebIfbrqbk^kq%fkpfab^karmqebpq^fop&^qqebQfo^d^oabHbbm%26+1)25+0&yyNFAy451y
>Qeb>ajfo^i$pLoabop%M^oq.&yRy155.yyKyLmbkqeb_lulkqebo^jm^oqprmpq^fopcolj?bkbaf`q%26+0)24+4&yyNFAy50-y

QQeb>ajfo^i$pLoabop%M^oq.&yKyD^o$Qelh%2.+6)10+2&yyNFAy50-y
>Qeb>ajfo^i$pLoabop%M^oq/&yKyD^o$Qelh%2.+6)10+2&yyNFAy50.y
QS^knrfpeqeb?bqo^vbopyKyD^o$Qelh%2.+6)10+2&yyNFAy451y
>ColjQebTob`h^db++++yKyD^o$Qelh%2.+6)10+2&yyNFAy5/2y

@ColjQebTob`h^db++++yKy@liib`qqeb0XDkljfpeQllipZb^pqlcO^wloEfii)lccqeb`l^pq%3/+.)3-+3&)%30+/)25&)%3.+1)23+.&yyNFAy5/2y
@>PlisbkqPmfofqyKyHfiiJ^horo^p^ka@o^tibop^ilkdqebb^pqbokpelob%3.)36&yyNFAy5.5y

@?ob^h^CbtBddpyKyEb^alsboqlqebB`elFpibp^ka`liib`q0XQ^fii^peboBddpZcoljqebo^mqlokbpqp%26+3)5/+3&yyNFAy5.2y
@Mo^`qf`^iMobvyKyHfiiqebArolq^oQfdbop^kaillqqebfoCroplkqebfpi^kapb^pqlcPbk$gfkSfii^db%3-)6-&yyNFAy5.4y
@Jfkpefk^$pPhriiyKyXJfkpefk^$pPhriiZ`^k_bclrka^qqebdiltfkdofqr^i`fo`ib^_lsbW^i^w^kb%34)54&yyNFAy5-5y
@@ib^krmlkFpibB+yKyD^qebo5uXAfpbk`e^kqbaQfhfJ^phpZclrka^olrkaqeb_^pblcqobb^kaqebpqlkbt^iipproolrkafkdqeb^ob^%33+5)50+2&yyNFAy/362.y
@Qet^oqfkdHlih^o>ddobppflkyKyTbpqlcPbk$gfk)b^`eifqqib`^jme^p^kfqbjqlmf`hrm%15)46&yyNFAy453y
@@^oovVlroTbfdeqyKyQebX@^ks^pP`o^mpZ`^k_bclrkalccqebp^filop^kapliafbopfkQfo^d^oabHbbm%24)22&yyNFAy46.y

QMo^`qf`^iMobvyKySbi$ofkC^kd%22+6)41&yyNFAy5.4y
Q>PlisbkqPmfofqyKyJ^pqboSlok^i%23)41+2&yyNFAy5.5y
QJfkpefk^$pPhriiyKyJ^pqboD^aofk%23)41+4&yyNFAy5-5y
Q@ib^krmlkFpibB+yKyJ^pqboD^aofk%23)41+4&yyNFAy/362.y
KP^sbnrbpqobt^oayKyVlr$iikbbaqebXC^fkqivDiltfkdPhriiZcloi^qbonrbpq?rokfkdPe^altpyyNFAy50/y
QQet^oqfkdHlih^o>ddobppflkyKyI^oMoltiqrph)TbpqlcPbk$gfkSfii^db%21+2)42&yyNFAy453y

EO^wloEfiiyRy3615yyNFAy5.3y
QColjQebTob`h^db++++yKyD^o$Qelh%2.+6)10+2&yyNFAy5/2y
Q?ob^h^CbtBddpyKy@llhQloh^%2.+/)1/+2&yyNFAy5.2y
Q@^oovVlroTbfdeqyKyCroiP`lok_oltfkqebt^q`eqltbokloqetbpqlcqltk%16+6)1-+0&yyNFAy46.y
>D^k$ori$pPrjjlkpy@yT^oil`hyyOyLo`yyKyLmebh%21+0)1.+/&yyNFAy.2-3y

@Bk`ol^`ejbkqyKyHfii1O^wloj^kbP`lrqp)1Nrfi_l^op)1Arpqrkkbop^ka1?^qqibdr^oapfkqeb`^jmptbpqlcO^wloefii%14+3-)15+64&%10+5-)1-+22&yyNFAy504y

>Ilpq?rqKlqClodlqqbkyKyJfpe^Qlo$hobk)KloqetbpqlcO^wloEfii^qqebQlo$hobkC^oj%10+.)0-+0&yyNFAy5.3y
>TfkapfkqebAbpboqyKyObwi^h)KloqelcO^wloEfii%13+1)//+6&yyNFAy501y
@TfkapfkqebAbpboqyKyEb^afkpfabqebO^wlotfka@^kvlk%2.)0/&tebobvlrtfii_b^_ibqlcfkaqeb2XP^`hplcPrmmifbpZlkqebdolrkayyNFAy501y
QTfkapfkqebAbpboqyKyObwi^h%13+1)//+6&yyNFAy501y
>Pb`rofkdqebIfkbpyKyObwi^h%13+1)//+6&yyNFAy502y
@Pb`rofkdqebIfkbpyKyHfii./ArpqtfkaP^s^dbp^ka5ArpqtfkaPqlojTfq`ebpkb^oAovdri`eO^sfkb%20)/0&qebbkqo^k`bfp^q%2/+.)/4+2&yyNFAy502y
QPb`rofkdqebIfkbpyKyObwi^h%13+1)//+6&yyNFAy502y

>Kbbaclo^@robyKyOefk^d)plrqetbpqlcLodofjj^o%1/+.).2&yyNFAy5./y

OLodofjj^oyWyLodofjj^oyyKyOrkqlLodofjj^o%00)04&yyNFAy24/3y
QQeb>ajfo^i$pLoabop%M^oq/&yWyLodofjj^oyyKySli$gfk%00)04&yyNFAy50.y
>EfaabkBkbjfbp%M^oq.&yWyLodofjj^oyyKyQeo^ii%0/)04&yyNFAy24/3y
>Cfkafkdqeb>kqfalqbyWyLodofjj^oyyKyHlo$de^k)fkqeb@ibcqlcPe^alt%10+0)2-+2&yyNFAy5.0y

@Cfkafkdqeb>kqfalqbyKyHfiiP`lomflkpplrqetbpqlcLodofjj^oclo1XSbkljq^fiMlfplkP^`pZ%1.).4&yyNFAy5.0y
@Ilpq?rqKlqClodlqqbkyKyHfiiqeb@ol`lafibpfkqebtbpqbokofsbo%02)15&cloXHolk$p>jribqZyyNFAy5.3y

QCfkafkdqeb>kqfalqbyWyLodofjj^oyyKyHlo$de^k)fkqeb@ibcqlcPe^alt%10+0)2-+2&yyNFAy5.0y

>D^k$ori$pPrjjlkpy@yT^oil`hyyOyLo`yyLyyNFAy.2-3yyKyHlo$de^k%10+0)2-+2&y
QD^k$ori$pPrjjlkpy@yT^oil`hyyOyLo`yyKyD^k$ori?illabvb%15+/)12+3&yyLyyNFAy.2-3yyWyLodofjj^oy
>@ob^qroblcqebSlfay@yT^oil`hyyOyLo`yyKyD^k$ori?illabvb%15+/)12+3&yyNFAy.2-.yyWyLodofjj^oy

QKbbaclo^@robyKyOefk^d)plrqetbpqlcLodofjj^o%1-+6/).3+1/&yyNFAy5./y
QIlpq?rqKlqClodlqqbkyKyJfpe^Qlo$hobk)KloqetbpqlcO^wloEfii^qqebQlo$hobkC^oj%10+.)0-+0&yyNFAy5.3y

@A^ohPqlojpyKyHfiiCfwwibfkqebQerkaboOfadb%1/)/3&^kaillqefp@i^tyyNFAy5-3y

EO^wloEfiiyRy3615yyNFAy5/5y
QA^ohPqlojpyKyLodkfiPlrip`^o%2/+0)10+/&yyNFAy5-3y
>J^odlwyKyLodkfiPlrip`^o%2/+0)10+/&yyNFAy5/5y
QBk`ol^`ejbkqyKyD^o$Qelh%2.+6)10+2&yyNFAy504y

>QebErkqbo$pM^qey@yErkqboyyWyLodfjj^oyyKyPf^k$aro%34+5).4+5&yyLyyNFAy3-4-y
QQebErkqbo$pM^qey@yErkqboyyKyQelq^o%2.+6)10+2&yyLyyNFAy3-4-y
>Q^jfkdqeb?b^pq%M^oq.&y@yErkqboyyKyQelq^o%2.+6)10+2&yyNFAy3-3/y
@Q^jfkdqeb?b^pq%M^oq.&y@yErkqboyyKyRpbqebXQ^jfkdOlaZqlq^jb^kAfobJlqqiba?l^okb^oqebqltk%2/)15&yyRy.26.4yyNFAy3-3/y
QQ^jfkdqeb?b^pq%M^oq.&y@yErkqboyyKyQelq^o%2.+6)10+2&yyNFAy3-3/y
>Q^jfkdqeb?b^pq%M^oq/&y@yErkqboyyKyQelq^o%2.+6)10+2&yyNFAy3-50y
@Q^jfkdqeb?b^pq%M^oq/&y@yErkqboyyKyRpbqebXQ^jfkdOlaZlk^Proc@o^tibo%3-)0-&yyRy.26.6yyNFAy3-50y
QQ^jfkdqeb?b^pq%M^oq/&y@yErkqboyyKyQelq^o%2.+6)10+2&yyNFAy3-50y
>Q^jfkdqeb?b^pq%M^oq0&y@yErkqboyyKyQelq^o%2.+6)10+2&yyNFAy3-55y
@Q^jfkdqeb?b^pq%M^oq0&y@yErkqboyyKyRpbqebXQ^jfkdOlaZlk^>ojlobaP`lomfakb^oqebqltk%10)05&yyRy.26/-yyNFAy3-55y
QQ^jfkdqeb?b^pq%M^oq0&y@yErkqboyyKyQelq^o%2.+6)10+2&yyNFAy3-55y
>Qo^fkfkdqeb?b^pqy@yErkqboyyKyQelq^o%2.+6)10+2&yyNFAy3-5.y

QJ^odlwyKyJ^odlw)kb^oqebmlkaplrqeb^pqlcLodofjj^o%23)/-&yyNFAy5/5y
>PhriiOl`hyKyJ^odlw%23)/-&yyNFAy5/4y
@PhriiOl`hyKyHfiiqeb@riqfpqpfkPhrihOl`h%22).-&cloqebfoXPb^ofkd@lii^opZyyNFAy5/4y
@EfaabkBkbjfbp%M^oq.&yKyDbqqebXIfbrqbk^kq$pFkpfdkf^Zcoljqebjl_pfkpfabPhrihOl`h%22).-&yyNFAy24/3y
@@ob^qroblcqebSlfay@yT^oil`hyyOyLo`yyKyDbqXQ^_ibqlcSbod^Zcolj?rokfkd?i^abPq^pe%2.+3)6+4&yyNFAy.2-.y
HD^ww$rwyKyHfiiD^ww$rw%2/+3)5+5&lo%2.+2)6+4&+RpbqebXC^fkqivDiltfkdPhriiZlkefjqlebimfcvlrpqfiie^sbqefp+Phfmqefpfcvlrc^fiyyRy1612yyIy16-0yyNFAy50/y
QPhriiOl`hyKyJ^odlw%23+1)/-&yyNFAy5/4y
>KbborCfob_i^abyKyJ^odlw%23+1)/-&yyNFAy5/6y

Q@ob^qroblcqebSlfay@yT^oil`hyyOyLo`yyKyD^k$ori?illabvb%15+/)12+3&yyNFAy.2-.yyWyLodofjj^oy
>Qeb?fkafkdy@yT^oil`hyyOyLo`yyKyD^k$ori?illabvb%15+/)12+3&yyWyLodofjj^oyyNFAy.14.y
@Qeb?fkafkdy@yT^oil`hyyOyLo`yyKyRpbXOrkbplcPrjjlkfkdZqlprjjlk^kahfiiqebSlfat^ihboyyRy4131yyNFAy.14.y
QQeb?fkafkdy@yT^oil`hyyOyLo`yyKyD^k$ori?illabvb%15+/)12+3&yyWyLodofjj^oyyNFAy.14.y
QEfaabkBkbjfbp%M^oq.&yWyLodofjj^oyyKyQeo^ii%0/)04&yyNFAy24/3y
>EfaabkBkbjfbp%M^oq/&yWyLodofjj^oyyKyQeo^ii%0/)04&yyNFAy24/4y
QQo^fkfkdqeb?b^pqy@yErkqboyyWyLodofjj^oyyKyLoj^hDofjpelq%33+/).5+/&yyNFAy3-5.y
QKbborCfob_i^abyWyLodofjj^oyyKyKbborCfob_i^ab%16+3)2-+1&fkqeb@ibcqlcPe^altyyNFAy5/6y
>>h$WbilqeyWyLodofjj^oyyKyKbborCfob_i^ab%16+3)2-+1&fkqeb@ibcqlcPe^altyyNFAy5-6y
@EfaabkBkbjfbp%M^oq/&yWyLodofjj^oyyKyQ^ihqlKbborCfob_i^ab%16+3)2-+1&fkqeb@ibcqlcPe^altyyNFAy24/4y
>?rokfkdPe^altpyRy16-0yyLyyNFAy50/yyKyQebfqbjXBvblc?rokfkdPe^altZpq^oqpnrbpq*aolmmba_vD^ww$rw%2/)6&y
Q?rokfkdPe^altpyLyyWyLodofjj^oyyKyKbborCfob_i^ab%16+3)2-+1&fkqeb@ibcqlcPe^altyyNFAy50/y
QEfaabkBkbjfbp%M^oq/&yWyLodofjj^oyyKyQeo^ii)Lodofjj^o%0/)04&+Phfmqebcliilt*rmyyNFAy24/4y

EO^wloEfiiyRy3615yyNFAy51-y
>Sbqbo^kRwwbhy@yT^oofloyyKyQ^ope^tG^ddbap`^o%21+/)1/+2&yyNFAy.2-2y
>@lkp`ofmqlcqebEloabyKyQ^hofkM^qepbbhbo)grpqlrqpfabqebtbpqbokbkqo^k`blcO^wloEfii%2-+6)10+3&yyNFAy51-y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
