DugisGuideViewer:RegisterGuide("Mulgore (1-12 Tauren)", "The Barrens (12-20)", "Horde", "L", function()
return [[
AAA

>QebErkq?bdfkpyKyDoriiE^thtfka%11+6)44&yyNFAy414y
KHfii>pVlroQo^sbi++yKyFkm^q`e0+0?ifww^oae^sbj^abfqb^pfboclokbtmi^vbopqlibsbirm_vj^hfkdqebKM@klk*^ddobpfsb)vlrtfiipqfiikbbaqlhfii^kvJl_p^pvlrqo^sbilqebotfpbvlrtlk$qd^fkbklrdebumbofbk`bqlmf`hrmkbtnrbpqpyyNFAy414y
@QebErkq?bdfkpyKyD^qebo4XMi^fkpqofaboCb^qebopZ^ka4mfb`bplcXMi^fkpqofaboJb^qZqe^qaolmlcqebMi^fkpqofabop^olrka%13+6)5-+1&qlqebplrqeb^pqlcqebsfii^dbyyNFAy414y
QQebErkq?bdfkpyKyDoriiE^thtfka%11+6)44&yyNFAy414y

>Bq`ebaKlqby@yErkqboyyKyDoriiE^thtfka%11+6)44&yyNFAy0-6/y
>PfjmibKlqby@yT^oofloyyKyDoriiE^thtfka%11+6)44&yyNFAy0-6.y
>Orkb*Fkp`of_baKlqby@yPe^j^kyyKyDoriiE^thtfka%11+6)44&yyNFAy0-60y
>Sboa^kqKlqby@yAorfayyKyDoriiE^thtfka%11+6)44&yyNFAy0-61y

>QebErkq@lkqfkrbpyKyDoriiE^thtfka%11+6)44&yyNFAy42-y
>>Erj_ibQ^ph%M^oq.&yKy@efbcE^thtfka%11+/)43+.&yyNFAy42/y

QBq`ebaKlqby@yErkqboyyKyI^kh^C^opelq%11+/)42+5&yyNFAy0-6/y
QPfjmibKlqby@yT^oofloyyKyE^orqqQerkaboelok%11+.)43+.&yyNFAy0-6.y
QOrkb*Fkp`of_baKlqby@yPe^j^kyyKyJbbi^A^tkpqofabo%12+-)43+-&yyNFAy0-60y
QSboa^kqKlqby@yAorfayyKyD^oqJfpqorkkbo%12+.)43&yyNFAy0-61y

Q>Erj_ibQ^ph%M^oq.&yKyDob^qjlqeboE^thtfka%2-+-)5.+.&yyNFAy42/y
>>Erj_ibQ^ph%M^oq/&yKyDob^qjlqeboE^thtfka%2-+-)5.+.&yyNFAy420y
@>Erj_ibQ^ph%M^oq/&yKyMf`hrm^XT^qboMfq`eboZ^qqebtbii%2-)5.&yyNFAy420y
Q>Erj_ibQ^ph%M^oq/&yKy@efbcE^thtfka%11+/)43+.&yyNFAy420y
>OfqbplcqebB^oqejlqebo%M^oq.&yKy@efbcE^thtfka%11+/)43+.&yyNFAy422y
@QebErkq@lkqfkrbpyKyHfiiqebJlrkq^fk@lrd^op^ilkdqebplrqebokjlrkq^fkp%12)56&^kaillq.-lcqebfoMbiqpyyNFAy42-y
QOfqbplcqebB^oqejlqebo%M^oq.&yKyPbboDo^vqlkdrb)Plrqelc@^jmK^o^`eb%1/+26)6/+.0&yyNFAy422y
>OfqblcPqobkdqeyKyPbboDo^vqlkdrb%1/+26)6/+.0&yyNFAy424y
KIbsbi1yKyJ^hbprobvlr$obibsbi1_bclobvlrobqrok_^`hqlqebsfii^dbhfiijlob`lrd^opfcvlr$obklq+yyNFAy45-yyMIy1y
QQebErkq@lkqfkrbpyKyDoriiE^thtfka%11+6)44&yyNFAy42-y
>Qeb?^qqib_l^opyKyDoriiE^thtfka%11+6)44&yyNFAy45-y
>?ob^hPe^omqrphyKy?o^sbTfkacb^qebo%11+2)43+2&yyNFAy0043y
>@^iilcB^oqe%M^oq.&y@yPe^j^kyyKyPbboO^sbkcb^qebo%11+4)43+0&yyNFAy.2.6y

@Qeb?^qqib_l^opyKyHfiiqeb?^qqib?l^opfkqeb?o^j_ib_i^abO^sfkbqlqebb^pqclo5X?^qqib_l^oPklrqpZ^ka5X?^qqib_l^oCi^khpZ%22)51&yyNFAy45-y
@OfqblcPqobkdqeyKyHfii?ofpqib_^`hpfk?o^j_ib_i^abO^sfkb^kaillq./X?ofpqib_^`h?biqpZ%25)5.&yyNFAy424y
@?ob^hPe^omqrphyKyHfii@efbcPe^omqrphQelokj^kqibfkqeb?o^j_ib_i^abO^sfkb^kaillqefpeb^a%31)44&yyNFAy0043y
@@^iilcB^oqe%M^oq.&y@yPe^j^kyyKy@liib`q/uXOfqr^iP^isbZcolj?ofpqib_^`hpPe^j^kp%30+2)5.+4&yyNFAy.2.6y
>>qq^`hlk@^jmK^o^`ebyKyRpbqebXAfoq*pq^fkbaJ^mZql_bdfkqebnrbpq%30+0)5/+3&yyNFAy/1524y

E@^jmK^o^`ebyRy3615yyNFAy430y
QQeb?^qqib_l^opyKyDoriiE^thtfka%11+6)44&yyNFAy45-y
Q?ob^hPe^omqrphyKy?o^sbTfkacb^qebo%11+2)43+2&yyNFAy0043y
QOfqblcPqobkdqeyKy@efbcE^thtfka%11+/)43+.&yyNFAy424y
Q>qq^`hlk@^jmK^o^`ebyKy@efbcE^thtfka%11+/)43+.&yyNFAy/1524y
>OfqbplcqebB^oqejlqebo%M^oq/&yKy@efbcE^thtfka%11+/)43+.&yyNFAy430y
Q@^iilcB^oqe%M^oq.&y@yPe^j^kyyKyPbboO^sbkcb^qebo%11+4)43+0yyNFAy.2.6y
>@^iilcB^oqe%M^oq/&y@yPe^j^kyyKyPbboO^sbkcb^qebo%11+4)43+0yyNFAy.2/-y
Q@^iilcB^oqe%M^oq/&y@yPe^j^kyyKyCfkaqebHlalOl`h^q%20+4)5-+2&^kaaofkhXB^oqeP^mq^Z^kaq^ihqlqebJfkloJ^kfcbpq^qflklcB^oqeyyRy3302yyNFAy.2/-y
>@^iilcB^oqe%M^oq0&y@yPe^j^kyyKyJfkloJ^kfcbpq^qflklcB^oqe%20+4)5-+2&yyNFAy.2/.y
Q@^iilcB^oqe%M^oq0&y@yPe^j^kyyKyPbboO^sbkcb^qebo%11+4)43+0yyNFAy.2/.y
>>Q^phRkcfkfpebayKy>kqroC^iilt)lkqebol^alrqlc`^jm%05+3)5.+3&yyNFAy.323y


O?illaellcSfii^dbyKyOrkql?illaellcSfii^db%14+2)3-+/&yyNFAy412y
QOfqbplcqebB^oqejlqebo%M^oq/&yKy?^fkb?illaellc%14+2)3-+/&yyNFAy430y
>Pe^ofkdqebI^kayKy?^fkb?illaellc%14+2)3-+/&yyNFAy412y
>OfqblcSfpflk%M^oq.&yKy?^fkb?illaellc%14+2)3-+/&yyNFAy434y
Q>Q^phRkcfkfpebayKyFkkhbbmboH^rqe%13+4)3-+.&yyNFAy.323y
e?illaellcSfii^dbyKyFkkhbbmboH^rqe%13+4)3-+.&yyNFAy410y
>A^kdboplcqebTfkacrovyKyOrriB^dibq^ilk%14+1)3.+6&yyNFAy410y
>PtllmErkqfkdyKyE^ohbkTfkaqlqbj%15+4)26+1&yyNFAy43.y
>J^wwo^k^`ebyKyJ^roO^fk`^iibo%14)24+.&yyNFAy433y
>MlfplkT^qboyKyJriiQerkaboelok%15+2)3-+2&yyNFAy415y
QOfqblcSfpflk%M^oq.&yKyW^oij^kQtl*Jllkp%14+4)24+3&yyNFAy434y
>OfqblcSfpflk%M^oq/&yKyW^oij^kQtl*Jllkp%14+4)24+3&yyNFAy44.y
>Hvib$pDlkbJfppfkdyKy>e^_Teb^qellc+Kloqelcqltk)_vqeb_ofadb%15+/)20+0&yyNFAy.../6y

KHfiiPtllmp^kad^qebo>`lokp+++yKyHfii^kvPtllmpvlrpbb)^iplillq^`lokprkaboqobbp^pvlrnrbpqyyNFAy43.y
@Pe^ofkdqebI^kayKyHfii.-M^ibj^kbQ^kkbop)5M^ibj^kbPhfkkbop)^ka2M^ibj^kbMl^`ebop^qqeb`^sbqlqebtbpq%01)3/&yyNFAy412y
@MlfplkT^qboyKyHfiiMo^fofbTlisbp^kaMi^fkpqofaboptef`e`^k_bclrkabsovtebob_rqbpmb`f^iiv^olrka%03)21&clo3XMo^fofbTlicM^tpZ^ka1XMi^fkpqofaboQ^ilkpZyyNFAy415y

QPe^ofkdqebI^kayKy?^fkb?illaellc%14+2)3-+/&yyNFAy412y
QMlfplkT^qboyKyJriiQerkaboelok%15+2)3-+2&yyNFAy415y
>Tfkqboellc@ib^kpfkdyKyJriiQerkaboelok%15+2)3-+2&yyNFAy421y
@Hvib$pDlkbJfppfkdyKyCfkaqebaldorkkfkd^olrkaqebsfii^db%15)25&^kacbbaefjqebXQbkaboPqofaboJb^qZyyRy00--6yyNFAy.../6y
@Tfkqboellc@ib^kpfkdyKyRpbqebXTfkqboellc@ib^kpfkdQlqbjZ^qqebtbiiplrqelcqltk%20+3)33+1&yyRy21..yyNFAy421y
@OfqblcSfpflk%M^oq/&yKyDo^_qebtbiipqlkbp^qqebp^jbtbii%20+3)33+1&yyNFAy44.y

QTfkqboellc@ib^kpfkdyKyJriiQerkaboelok%15+2)3-+2&yyNFAy421y
>QerkaboelokQlqbjyKyJriiQerkaboelok%15+2)3-+2&yyNFAy423y
>At^osbkAfddfkdyKy?^fkb?illaellc%14+2)3-+/&yyNFAy413y
QOfqblcSfpflk%M^oq/&yKyW^oij^kQtl*Jllkp%14+4)24+3&yyNFAy44.y
>OfqblcSfpflk%M^oq0&yKyW^oij^kQtl*Jllkp%14+4)24+3&yyNFAy44/y
RAofkhrmyRy15/0yyNFAy440y
QHvib$pDlkbJfppfkdyKy>e^_Teb^qellc+Kloqelcqltk)_vqeb_ofadb%15+/)20+0&yyNFAy.../6y
QOfqblcSfpflk%M^oq0&yKyCliiltqebsfpflk)logrpqorkqlqeb`^sbtebobvlr$iicfkaPbboTfpborkkboeb$pib^afkdvlrql%0/+4)03&yyNFAy44/y
>OfqblcTfpaljyKyPbboTfpborkkbo%0/+35)03+-3&yyNFAy440y

@QerkaboelokQlqbjyKyErkqMo^fofbPq^ihbopcloqebfoXPq^ihbo@i^tpZ^kaCi^qi^ka@lrd^opcloqebfoX@lrd^o@i^tpZ^iilsboqebmi^fkpplrqelcQerkabo?ircc%03)02&yyNFAy423y
@At^osbkAfddfkdyKyHfiiqebat^osbpcloqebfoqllip)qebkcfkaqebclodb%0/)15&fkqeb`^jm^ka_ob^hqebjrpfkdXMolpmb`qlo$pMf`hZyyRy14-/yyNFAy413y
@PtllmErkqfkdyKyHfiiPtllmptef`e`^k_bclrkabsbovtebobfk`bkqo^i^kaplrqeJridlobyyNFAy43.y
@J^wwo^k^`ebyKyVlrpelriae^sb^XMo^fofbTlicEb^oqZ)^XCi^qi^ka@lrd^oCbjroZ)^XMi^fkpqofaboP`^ibZ^ka^XPtllmDfww^oaZ_vklt+Fcvlralk$qvlrpelriad^qeboqebobj^fkfkdfqbjpcoljqebjl_pfkJridlobyyNFAy433y

QQerkaboelokQlqbjyKyJriiQerkaboelok%15+2)3-+2&yyNFAy423y
QAt^osbkAfddfkdyKy?^fkb?illaellc%14+2)3-+/&yyNFAy413y
QPtllmErkqfkdyKyE^ohbkTfkaqlqbj%15+4)26+1&yyNFAy43.y
QJ^wwo^k^`ebyKyJ^roO^fk`^iibo%14)24+.&yyNFAy433y

>Qerkaboelok@ib^kpfkdyKyJriiQerkaboelok%15+2)3-+2&yyNFAy425y
@Qerkaboelok@ib^kpfkdyKyRpbqebXQerkaboelok@ib^kpfkdQlqbjZ^qqebtbii%11)12&yyRy21.2yyNFAy425y
QQerkaboelok@ib^kpfkdyKyJriiQerkaboelok%15+2)3-+2&yyNFAy425y
>Tfiaj^kbQlqbjyKyJriiQerkaboelok%15+2)3-+2&yyNFAy426y

>QebO^s^dba@^o^s^k%M^oq.&yKyJlofk@ilrapq^ihbo)m^qolipqebol^aqlqebb^pq%23)3.&yyNFAy416y
QQebO^s^dba@^o^s^k%M^oq.&yKy@ljmibqbqefp_vq^hfkdqebPb^ibaPrmmiv@o^qbqlqebkloqe%21+2)13+6&yyNFAy416y
>QebO^s^dba@^o^s^k%M^oq/&yKyDfsbktebkvlrdo^_qebPrmmiv@o^qb%21+2)13+6&yyNFAy42.y
QQebO^s^dba@^o^s^k%M^oq/&yKyJlofk@ilrapq^ihbo)m^qoliifkdqebb^pqbokol^a%23)3.&yyNFAy42.y
>QebSbkqrob@l+yKyJlofk@ilrapq^ihbo)m^qoliifkdqebb^pqbokol^a%23)3.&yyNFAy431y
>PrmbosfploCfwpmol`hbqyKyJlofk@ilrapq^ihbo)m^qoliifkdqebb^pqbokol^a%23)3.&yyNFAy432y

@A^kdboplcqebTfkacrovyKyHfiiqebE^omfbpqlqebb^pq)plrqelcqebol^a%34)4-&^kaillq5XTfkacrovQ^ilkpZyyNFAy410y
@Tfiaj^kbQlqbjyKyHfiiMo^fofbTlic>ime^p^olrka%2/)/0&clo5XMo^fofb>ime^QbbqeZyyNFAy426y

QTfiaj^kbQlqbjyKyJriiQerkaboelok%15)3-+1&yyNFAy426y
>Tfiaj^kb@ib^kpfkdyKyJriiQerkaboelok%15)3-+1&yyNFAy43-y

>QebErkqbo$pM^qey@yErkqboyyWyQerkabo?irccyyKyH^ovQerkaboelok%25+/)53+0&yyLyyNFAy3-33y
QQebErkqbo$pM^qey@yErkqboyyKyV^tPe^omj^kb%14+5)22+3&yyLyyNFAy3-33y
>Q^jfkdqeb?b^pq%M^oq.&y@yErkqboyyKyV^tPe^omj^kb%14+5)22+3&yyNFAy3-3.y
@Q^jfkdqeb?b^pq%M^oq.&y@yErkqboyyKyRpbqebXQ^jfkdOlaZqlq^jb^k>ariqMi^fkpqofabokb^oqebqltk%21)30&yyRy.26.1yyNFAy3-3.y
QQ^jfkdqeb?b^pq%M^oq.&y@yErkqboyyKyV^tPe^omj^kb%14+5)22+3&yyNFAy3-3.y
>Q^jfkdqeb?b^pq%M^oq/&y@yErkqboyyKyV^tPe^omj^kb%14+5)22+3&yyNFAy3-54y
@Q^jfkdqeb?b^pq%M^oq/&y@yErkqboyyKyRpbqebXQ^jfkdOlaZlk^Mo^fofbPq^ihbokb^oqebqltk%26)23&yyRy.26.2yyNFAy3-54y
QQ^jfkdqeb?b^pq%M^oq/&y@yErkqboyyKyV^tPe^omj^kb%14+5)22+3&yyNFAy3-54y
>Q^jfkdqeb?b^pq%M^oq0&y@yErkqboyyKyV^tPe^omj^kb%14+5)22+3&yyNFAy3-55y
@Q^jfkdqeb?b^pq%M^oq0&y@yErkqboyyKyRpbqebXQ^jfkdOlaZlk^Ptllmkb^oqebqltk%26)23&yyRy.26.3yyNFAy3-55y
QQ^jfkdqeb?b^pq%M^oq0&y@yErkqboyyKyV^tPe^omj^kb%14+5)22+3&yyNFAy3-55y

>Qo^fkfkdqeb?b^pqy@yErkqboyyKyV^tPe^omj^kb%14+5)22+3&yyNFAy3-56y
>Ebbafkdqeb@^iiy@yAorfayyKyDbkkf^Orkbqlqbj%15+2)26+3&yyNFAy26/3y
>QebErkqbo$pT^vyKyPhlokTefqb`ilra%13+5)3-+/&yyNFAy53.y

OQerkabo?irccyKyOrkqlQerkabo_ircc%04+2)/6+0&yyNFAy411y
>Mobm^o^qflkclo@bobjlkvyWyQerkabo?irccyyKyBv^ekB^dibq^ilk%04+3)3-+.&yyNFAy411y
QQo^fkfkdqeb?b^pqy@yErkqboyyWyQerkabo?irccyyKyEliqQerkaboelok%24+1)56+0&yyNFAy3-56y

QEbbafkdqeb@^iiy@yAorfayyWyQerkabo?irccyyKyQro^hOrkbqlqbj%43+0)/5+2&yyNFAy26/3y
>Jllkdi^aby@yAorfayyKyQro^hOrkbqlqbj%43+0)/5+2&yyNFAy26//y
QJllkdi^aby@yAorfayyWyJllkdi^abyyKyRpbqebpmbiiQbibmloq7Jllkdi^ab+Tebkvlr^oofsb)pmb^htfqeAbkaofqbPq^o_i^wb%23+/)0-+2&yyNFAy26//y
>Dob^q?b^oPmfofqy@yAorfayyWyJllkdi^abyyKyAbkaofqbPq^o_i^wb%23+/)0-+2&yyNFAy260-y
@Dob^q?b^oPmfofqy@yAorfayyWyJllkdi^abyyKyQ^ihqlqebDob^q?b^oPmfofqfkkloqetbpq`lokbolcJllkdi^ab%06+.2)/4+45&yyWyJllkdi^abyyNFAy260-y
QDob^q?b^oPmfofqy@yAorfayyWyJllkdi^abyyKyAbkaofqbPq^o_i^wb%23+/)0-+2&yyNFAy260-y
>?^`hqlQerkabo?irccy@yAorfayyWyJllkdi^abyyKyAbkaofqbPq^o_i^wb%23+/)0-+2&yyNFAy260/y
CQerkabo?irccyKyCifdeqJ^pqbofp^q%11+2)12+2&yyNFAy500y
Q?^`hqlQerkabo?irccy@yAorfayyWyQerkabo?irccyyKyQro^hOrkbqlqbj%43+0)/5+2&yyNFAy260/y
>?lav^kaEb^oqy@yAorfayyWyQerkabo?irccyyKyQro^hOrkbqlqbj%43+0)/5+2&yyNFAy3--/y

@?lav^kaEb^oqy@yAorfayyKyRpbqebX@bk^oflkIrk^oarpqZlkqebJllkhfkPqlkb_bqtbbkJridlob^kaqeb?^oobkpql_ofkdcloqeIrk^`i^t%1/)3-+6&+Rpbqebarpq)hfiiIrk^`i^t)^kapmb^hqlefppmfofqyyRy.24.-yyWyQeb?^oobkpyyNFAy3--/y
@Tfiaj^kb@ib^kpfkdyKyRpbqebXTfiaj^kb@ib^kpfkdQlqbjZ^qqebTfiaj^kbT^qboTbii%10).1&yyRy21.3yyNFAy43-y
@QebErkqbo$pT^vyKyD^qebo1XCi^qi^kaMoltibo@i^tpZkloqelcQerkabo?ircc%1-)..&yyNFAy53.y
>>P^`oba?rof^iyKyIlobhbbmboO^fkqlqbj)b^pqlcQerkabo?ircc^qqebObaOl`hp>jmefqeb^qob%26+50)/2+3-&yyNFAy500y
QOfqblcTfpaljyKyE^kafk^qqeb>k`bpqo^iPmfofqqlqebkloqe)fkqebjfaaiblcqebdo^sbv^oa%3.+1)/-+6&yyNFAy440y
>GlrokbvfkqlQerkabo?irccyKy>k`bpqo^iPmfofq%3.+1)/-+6&yyNFAy442y
@>P^`oba?rof^iyKyHfii5?ofpqib_^`hFkqboilmbop^qObaOl`hp%3-)/3&yyNFAy500y
Q>P^`oba?rof^iyKyIlobhbbmboO^fkqlqbj)b^pqlcQerkabo?ircc^qqebObaOl`hp>jmefqeb^qob%26+5)/2+3&yyNFAy500y
@Mobm^o^qflkclo@bobjlkvyKyHfiiqebE^omfbpkloqetbpqlcQerkabo_ircc^ka`liib`q3X>wrobCb^qebopZ^ka3X?olkwbCb^qebopZ%23).4&yyNFAy411y

OQerkabo?irccyKyOrkqlQerkabo_ircc%04+2)/6+0&yyNFAy53-y
QMobm^o^qflkclo@bobjlkvyWyQerkabo?irccyyKyBv^ekB^dibq^ilk%04+3)3-+.&yyNFAy411y
QQebErkqbo$pT^vyWyQerkabo?irccyyKyJbiloPqlkbellc%13+5)3-+/&)lkqebErkqbo$pOfpbyyNFAy53.y
Q?lav^kaEb^oqy@yAorfayyWyQerkabo?irccyyyKyQro^hOrkbqlqbj%43+0)/5+2&yyNFAy3--/y
>Pbodo^A^ohqelokyWyQerkabo?irccyyKyJbiloPqlkbellc%3.+1)5-+2&yyNFAy53-y
QGlrokbvfkqlQerkabo?irccyWyQerkabo?irccyyKy@^fokb?illaellc%3-)2.+4&yyNFAy442y
>OfqbplcqebB^oqejlqebo%M^oq0&yWyQerkabo?irccyyKy@^fokb?illaellc%3-)2.+4&yyNFAy443y

@OfqbplcqebB^oqejlqebo%M^oq0&yKyHfii^hlalk^jba>oo^$`eb^b^pqlcQerkabo?ircc+Ebpm^tkp^q%16).6&^kam^qolip`il`htfpb+Ebdlbpkloqeql%2/).-&^kaplrqeql%21)02&yyNFAy443y
QOfqbplcqebB^oqejlqebo%M^oq0&yWyQerkabo?irccyyKy@^fokb?illaellc%3-)2.+4&yyNFAy443y
>Qeb?^oobkpL^pbpyWyQerkabo?irccyyKy>o`eaorfalkqebBiaboOfpb%45+3)/5+2&yyNFAy553y

E?illaellcSfii^dbyRy3615y
>QebAbjlkP`^ooba@il^hyLyyKyQebfqbjXAbjlkP`^ooba@il^hZpq^oqpnrbpq*aolmmbalcc^o^obpm^tkk^jbaDelpqElti+Qov^olrka%16).3&lo%2/).2&yyRy1521yyNFAy44-y
QQebAbjlkP`^ooba@il^hyLyyKyPhlokTefqb`ilra%13+5)3-+/&yyNFAy44-y
>Sbqbo^kRwwbhy@yT^oofloyyKyHo^kdPqlkbellc%16+3)3-+2&yyNFAy.2-2y
QA^kdboplcqebTfkacrovyKyOrriB^dibq^ilk%14+1)3.+6&yyNFAy410y
QTfiaj^kb@ib^kpfkdyKyJriiQerkaboelok%15+2)3-+1&yyNFAy43-y

@PrmbosfploCfwpmol`hbqyKyHfiiPrmbosfploCfwpmol`hbqfkqebjfkbqlqebb^pqlcqebO^s^dba@^o^s^k%3.)14&yyNFAy432y
@QebSbkqrob@l+yKyHfii.1Sbkqrob@l+Tlohbop^ka3Sbkqrob@l+Prmbosfplop^olrka^kafkqebjfkb%3-)12&yyNFAy431y
QQebSbkqrob@l+yKyJlofk@ilrapq^ihbo)m^qoliifkdqebb^pqbokol^a%23)3.&yyNFAy431y
QPrmbosfploCfwpmol`hbqyKyJlofk@ilrapq^ihbo)m^qoliifkdqebb^pqbokol^a%23)3.&yyNFAy432y
]]
end)
