
DugisGuideViewer:RegisterGuide("The Barrens (12-20)", "Stonetalon Mountains (20-22)", "Horde", "L", function()
return [[
AAA

OO^wloEfiiyOyRkab^ayyKyOrkPlrqeqlO^wloEfii%2-+6)10+3&yyNFAy511y
>@lkp`ofmqlcqebEloabyOyRkab^ayyWyArolq^oyyKyQ^hofkM^qepbbhbo%2-+6)10+3&)O^wloEfiiyyNFAy51-y

O@^jmQ^ro^glyOyQ^robkyyKyOrkb^pqql@^jmQ^ro^gl%11+6)25+4&yyNFAy521y
>Glrokbvqlqeb@olppol^apyOyQ^robkyyKyHfodbPqbokelok%11+6)25+4&yyNFAy521y

OQeb@olppol^apyKyQ^hbqebol^akloqe%2/)0-&yyOyQ^robkyyNFAy303.y
QQeb?^oobkpL^pbpyLyyKyQlkd^Orkbqlqbj%2/+/)0.+6&yyNFAy553y
QGlrokbvqlqeb@olppol^apyOyQ^robkyyKyQeloh%2.+2)0-+5&yyNFAy521y
QPbodo^A^ohqelokyLyyKyPbodo^A^ohqelok%2/+/)0.+-&yyNFAy53-y

>>?rkaiblcEfabpyOyQ^robkyyKyG^e^kE^thtfkd%2.+/)/6+.&yyNFAy303.y
Q>?rkaiblcEfabpyOyQ^robkyyKyAbso^h%2.+2)0-+0&yyNFAy303.y
>OfabqlQerkabo?irccyOyQ^robkyyKyAbso^h%2.+2)0-+0&yyNFAy303/y
eQeb@olppol^apyOyQ^robkyyKyFkkhbbmbo?llo^kaMi^fkptfka%2/+-)/6+6&yyNFAy3030y

Q@lkp`ofmqlcqebEloabyOyLo`)Qolii)Rkab^ayyKyH^od^i?^qqibp`^o%3/+0).6+1&+Grpqlsboqeb_ofadbcoljArolq^oqlQeb?^oobkpyyNFAy51-yyLy
>@olppol^ap@lkp`ofmqflkyOyLo`)Qolii)Rkab^ayyKyH^od^i?^qqibp`^o%3/+0).6+1&yyNFAy51/y
Q>h$WbilqeyOyLo`)QoliiyyKy>h$Wbilqe%3/+1)/-+.&)phfmqebcliilt*rmyyNFAy5-6y

QSbqbo^kRwwbhy@yT^oofloyyOyQ^robk)Lo`yyKyRwwbh%3.+1)/.+.&yyNFAy.2-2y
>M^qelcAbcbkpby@yT^oofloyyOyQ^robk)Lo`yyKyRwwbh%3.+1)/.+.&yyNFAy.165y
@M^qelcAbcbkpby@yT^oofloyyOyQ^robk)Lo`yyKyDlqlQeb?^oobkp^kahfiiQerkaboIfw^oap%1-+5)/3+1&ql`liib`q2uXPfkdbaP`^ibpZyyNFAy.165yyWyArolq^oy
QM^qelcAbcbkpby@yT^oofloyyOyQ^robk)Lo`yyKyRwwbh%3.+1)/.+.&yyNFAy.165y
>Qerk$dofjCfobd^wby@yT^oofloyyOyQ^robk)Lo`yyKyRwwbh%3.+1)/.+.&yyNFAy.2-/y
QQerk$dofjCfobd^wby@yT^oofloyyOyQ^robk)Lo`yyKyQerk$dofjCfobd^wb%24+/)0-+0&yyNFAy.2-/y
>ClodbaPqbbiy@yT^oofloyyOyQ^robk)Lo`yyKyQerk$dofjCfobd^wb%24+/)0-+0&yyNFAy.2-0y
@ClodbaPqbbiy@yT^oofloyyOyQ^robk)Lo`yyKyDbqqebXClodbaPqbbi?^opZcoljqebPqlibkFolk@ebpq%22)/3+3&yyNFAy.2-0y
QClodbaPqbbiy@yT^oofloyyOyQ^robk)Lo`yyKyQerk$dofjCfobd^wb%24+/)0-+0&yyNFAy.2-0y

CQerkabo?irccyOyQ^robkyyKyAbso^h%2.+2)0-+0&yyNFAy3030y
QOfabqlQerkabo?irccyOyQ^robkyyWyQerkabo?irccyyKyCivqlQerkabo?ircc+>e^kr%12+3)22+6&yyNFAy303/y
>Q^iqebTfkaOfaboJ^pqboyOyQ^robkyyWyQerkabo?irccyyKy>e^kr%12+3)22+6&yyNFAy3030y
QQ^iqebTfkaOfaboJ^pqboyOyQ^robkyyWyQerkabo?irccyyKyQ^i%13+5)2-+/&yyNFAy3030y
>ObqrokqlG^e^kyOyQ^robkyyWyQerkabo?irccyyKyQ^i%13+5)2-+/&yyNFAy3031y
CQeb@olppol^apyOyQ^robkyyWyQerkabo?irccyyKyQ^i%13+5)2-+/&yyNFAy511y
QObqrokqlG^e^kyOyQ^robkyyKyG^e^kE^thtfkd%2.+/)/6+.&yyNFAy3031y

OQeb@olppol^apyOyLo`)Qolii)Rkab^ayyKyCliiltqebol^a)q^hfkd^ibcqqrokqlqeb@olppol^ap%2/)0-&yyNFAy511y
Q@olppol^ap@lkp`ofmqflkyOyLo`)Qolii)Rkab^ayyKyPbodo^A^ohqelok%2/+/)0.+-&yyNFAy51/y
>Mi^fkpqofaboJbk^`byKyPbodo^A^ohqelok%2/+/)0.+-&yyNFAy511y

>Jb^qpqlLodofjj^oyOyLo`)QoliiyyKyW^ode%2/+3)/6+6&yyNFAy3032y
QJb^qpqlLodofjj^oyOyLo`)QoliiyyKyAbso^h%2.+2)0-+0&yyNFAy3032y
>OfabqlLodofjj^oyOyLo`)QoliiyyKyAbso^h%2.+2)0-+0&yyNFAy3051y
CLodofjj^oyOyLo`)QoliiyyKyAbso^h%2.+2)0-+0&yyNFAy3052y
QOfabqlLodofjj^oyOyLo`)QoliiyyWyLodofjj^oyyKyFkkhbbmboDovpeh^%21+.)35+3&yyNFAy3051y
>Alo^pqebTfkaOfaboJ^pqboyOyLo`)QoliiyyWyLodofjj^oyyKyFkkhbbmboDovpeh^%21+.)35+3&yyNFAy3052y
QAlo^pqebTfkaOfaboJ^pqboyOyLo`)QoliiyyWyLodofjj^oyyKyAlo^p%12+0)31&yyNFAy3052y

>Obqrokqlqeb@olppol^ap+yOyLo`)QoliiyyWyLodofjj^oyyKyAlo^p%12+0)31&yyNFAy3053y
CQeb@olppol^apyOyLo`)QoliiyyKyAlo^p%12+0)31&yyWyLodofjj^oyyNFAy511y
QObqrokqlqeb@olppol^ap+yOyLo`)QoliiyyKyW^ode%2/+3)/6+6&yyNFAy3053y

>O^mqloQefbsbpyKyD^wold%2.+6)0-+0&yyNFAy536y
eQeb@olppol^apyKyFkkhbbmbo?llo^kaMi^fkptfka%2/+-)/6+6&yyNFAy54.y
>Afpormqqeb>qq^`hpyKyQeloh%2.+2)0-+5&yyNFAy54.y

KHfiiO^mqlop^kaMi^fkpqofabop^pvlrnrbpq++yKyHfii^kvo^mqlopvlr`ljb^`olppcloO^mqloQefbsbp^kami^fkpqofabopcloMi^fkpqofaboJbk^`byyNFAy511y
@Afpormqqeb>qq^`hpyKyHfii5T^qboPbbhbop)5Qeloktb^sbop^ka0Erkqbopb^pqlcqeb@olppol^ap)kloqelcqebjlrkq^fk%21)/3&yyNFAy54.y
QAfpormqqeb>qq^`hpyKyQeloh%2.+2)0-+5&yyNFAy54.y
>QebAfpormqflkBkapyKyQeloh%2.+2)0-+5&yyNFAy54/y
>Prmmifbpcloqeb@olppol^apyKyQeloh%2.+2)0-+5&yyNFAy2-1.y
>Te^ocj^pqboAfwwvtfdyKy>mlqeb`^ovEbi_ofj%2.+2)0-+/&yyNFAy.16/y
@QebAfpormqflkBkapyKyHfii5O^wloj^kbDblj^k`bop)5O^wloj^kbAbcbkabop)^kaHobbkfdPk^oipklrqb^pqlcqeb@olppol^ap)kloqelcqebjlrkq^fk%25+4)/3+1&yyNFAy54/y
@Prmmifbpcloqeb@olppol^apyKyIllqqebX@olppol^ap$Prmmiv@o^qbpZ%25)/2&yyNFAy2-1.y
@Mi^fkpqofaboJbk^`byKyHfiiqebobj^fkfkdMi^fkpqofabopcloqebfoXMi^fkpqofabo?b^hpZ%20)0/&yyNFAy511y

OO^q`ebqyKyOrkqlO^q`ebq%3/+3)04+2&yyNFAy562y
>@ebk$pBjmqvHbdyRy16/3yyLyyNFAy5//yyKyQefpfp^klmqflk^inrbpqfcvlrpqrj_iblk@ebk$pBjmqvHbd%23+2)13+0&)%12)3/+/&)%21+4)04+/&)%22+4)/4+0&)%22+5)/-+-&)%24+.)6&)%10+5)1/+/&)%04+6).3+.&y
Q@ebk$pBjmqvHbdyLyyKy?obtj^pqboAolek%3/+0)05+1&yyNFAy5//y
cO^q`ebqyKy?o^dlh%30+.)04+/&yyNFAy562y
>T>KQBA7?^olkIlkdpelobyKyColjqebpfdklrqpfabqeb_^kh%3/+3)04+2&yyNFAy562y
>O^mqloElokpyKyJb_lhJfwwvofu%3/+1)04+3&yyNFAy532y
>P^jlmei^kdb%M^oq.&yKyPmrqqbos^isb%30+-)04+/&yyNFAy561y
>Plrqepb^Cobb_llqbopyKyD^wiltb%3/+4)03+0&yyNFAy554y
QTe^ocj^pqboAfwwvtfdyKyTe^ocj^pqboAfwwvtfd%30+0)05+1&yyNFAy.16/y
>Jfkbo$pCloqrkbyKyTe^ocj^pqboAfwwvtfd%30+0)05+1&yyNFAy563y

@T>KQBA7?^olkIlkdpelobyKyHfii?^olkIlkdpelob^kaillqefpeb^a%31+/)14+/&lo%3/+4)16+5&yyNFAy562y
@Plrqepb^Cobb_llqbopyKyHfii./Plrqepb^?ofd^kap^ka3Plrqepb^@^kklkbbop^ilkdqebplrqebok`l^pq%31)12&yyNFAy554y

QPlrqepb^Cobb_llqbopyKyD^wiltb%3/+4)03+0&yyNFAy554y
>QebJfppfkdPefmjbkq%M^oq.&yKyD^wiltb%3/+4)03+0&yyNFAy56-y
QT>KQBA7?^olkIlkdpelobyKyD^wiltb%3/+4)03+0&yyNFAy562y
QQebJfppfkdPefmjbkq%M^oq.&yKyTe^ocj^pqboAfwwvtfd%30+0)05+1&yyNFAy56-y
>QebJfppfkdPefmjbkq%M^oq/&yKyTe^ocj^pqboAfwwvtfd%30+0)05+1&yyNFAy56/y
QQebJfppfkdPefmjbkq%M^oq/&yKyD^wiltb%3/+4)03+0&yyNFAy56/y
>Pqlibk?llqvyKyD^wiltb%3/+4)03+0&yyNFAy555y
@Pqlibk?llqvyKyD^qeboqebXPefmjbkqlc?llqpZ%30)2-&^kaXQbibp`lmf`IbkpZ%31)16&^qqebmfo^qb`^jmpyyNFAy555y

EQeb@olppol^apyRy3615yyNFAy512y
QPrmmifbpcloqeb@olppol^apyKyQeloh%2.+2)0-+5&yyNFAy2-1.y
QQebAfpormqflkBkapyKyQeloh%2.+2)0-+5&yyNFAy54/y
QMi^fkpqofaboJbk^`byKyPbodo^A^ohqelok%2/+/)0.+-&yyNFAy511y
>QebWebso^yKyPbodo^A^ohqelok%2/+/)0.+-&yyNFAy512y
>QebClodlqqbkMllipyKyQlkd^Orkbqlqbj%2/+/)0.+6&yyNFAy54-y
>E^omvO^fabopyKyA^oplhPtfcqa^ddbo%2.+3)0-+6&yyNFAy534y
>Crkd^iPmlobpyKy>mlqeb`^ovEbi_ofj%2.+2)0-+/&yyNFAy515y

KHfiiWebso^^pvlrnrbpqp++yKyHfii^kvWebso^$pvlr`ljb^`olppcloQebWebso^yyNFAy512y

>Hlih^oIb^abopyKyObdqe^oAb^qed^qb%12+1)/5+1&yyNFAy52-y
>@bkq^ro?o^`bopyKyObdqe^oAb^qed^qb%12+1)/5+1&yyNFAy522y

@Hlih^oIb^abopyKyHfii?^o^hHlal_^kb^kaq^hbefpeb^a%10)/0&yyNFAy52-y
@Crkd^iPmlobpyKyD^qebo1XCrkd^iPmlobpZ%12)//&yyNFAy515y
@QebClodlqqbkMllipyKyBumilobqebt^qboplcqebClodlqqbkMllip%12)//+2&ptfjqlqeb_r__ibfkqebjfaaiblcqebmlliyyNFAy54-y
@E^omvO^fabopyKy@liib`q5XTfq`etfkdq^ilkpZfkqebkloqetbpq`lokbolcqeb?^oobkp%05).4&yyNFAy534y

QHlih^oIb^abopyKyObdqe^oAb^qed^qb%12+1)/5+1&yyNFAy52-y
>SboldqebAbosfpeyKyObdqe^oAb^qed^qb%12+1)/5+1&yyNFAy52.y

@@bkq^ro?o^`bopyKyD^qebo.2X@bkq^ro?o^`bopZkb^oqebClodlqqbkMllip%11)/0&yyNFAy522y
@QebWebso^yKyHfiiqebobj^fkfkdWebso^$pcloqebfoEllsbp%13)/4&yyNFAy512y

QQebWebso^yKyPbodo^A^ohqelok%2/+/)0.+-&yyNFAy512y
>Moltiboplcqeb?^oobkpyKyPbodo^A^ohqelok%2/+/)0.+-&yyNFAy6-0y
QQebClodlqqbkMllipyKyQlkd^Orkbqlqbj%2/+/)0.+6&yyNFAy54-y
>QebPq^dk^kqL^pfpyKyQlkd^Orkbqlqbj%2/+/)0.+6&yyNFAy544y
QCrkd^iPmlobpyKy>mlqeb`^ovEbi_ofj%2.+2)0-+/&yyNFAy515y
>>mlqeb`^ovW^j^eyKy>mlqeb`^ovEbi_ofj%2.+2)0-+/&yyNFAy520y

O@^jmQ^ro^glyKyOrkql@^jmQ^ro^gl%11+3)26+/&yyNFAy545y
c@^jmQ^ro^glyOyLo`)Qolii)Rkab^ayyKyLjrp^Qerkaboelok%11+2)26+.&yyNFAy545y
>Qof_bp^qT^oyKyJ^kdibqllqe%11+3)26+/&yyNFAy545y

OQerkabo?irccyOyLo`)Qolii)Rkab^ayyKyQ^hbqebol^atbpqfkqlJridlob)qebkkloqe^q?illaellcSfii^db%0/)34&yyWyQerkabo?irccyyNFAy544y
CQerkabo?irccyOyQ^robkyyKyLjrp^Qerkaboelok%11+2)26+.&yyNFAy544y
Q>mlqeb`^ovW^j^eyWyQerkabo?irccyyKy>mlqeb`^ovW^j^e)`^sb_biltPmfofqOfpb%//+6)/-+6&yyNFAy520y

cQerkabo?irccyKyQ^i%13+5)2-+/&yyWyQerkabo?irccyyNFAy544y
CQeb@olppol^apyKyQ^i%13+5)2-+/&yyWyQerkabo?irccyyNFAy544y
>QebPq^dk^kqL^pfpyKyQlkd^Orkbqlqbj%2/+/)0.+6&yyNFAy544y
QE^omvO^fabopyKyA^oplhPtfcqa^ddbo%2.+3)0-+6&yyNFAy534y
>E^omvIfbrqbk^kqpyKyA^oplhPtfcqa^ddbo%2.+3)0-+6&yyNFAy542y

@Moltiboplcqeb?^oobkpyKy@liib`q4XMoltibo@i^tpZcoljP^s^kk^eMoltibop%1-+6)/0+1&yyNFAy6-0y
@E^omvIfbrqbk^kqpyKyHfiiTfq`etfkdPi^vbo$pfkqebkloqetbpqm^oqlcqeb?^oobkp%05).1&yyNFAy542y
QP^jlmei^kdb%M^oq.&yKy@lkqoli@lkplib%2/+2)..+4&yyNFAy561y
>P^jlmei^kdb%M^oq/&yKy@lkqoli@lkplib%2/+2)..+4&yyNFAy6--y
KQroklccqeb`lkqolis^isbyKyPtfq`elcc^ii0`lkqolis^isbp%2/+0)..+3&yyNFAy6--y
QP^jlmei^kdb%M^oq/&yKy@lkqoli@lkplib%2/+2)..+4&yyNFAy6--y
>P^jlmei^kdb%M^oq0&yKy@lkqoli@lkplib%2/+2)..+4&yyNFAy6-.y
@P^jlmei^kdb%M^oq0&yKyHfiiQfkhbobofkqeberqlkqebefii%2/+6).-+3&yyNFAy6-.y
QP^jlmei^kdb%M^oq0&yKy@lkqoli@lkplib%2/+2)..+4&yyNFAy6-.y
>P^jlmei^kdb%M^oq1&yKy@lkqoli@lkplib%2/+2)..+4&yyNFAy6-/y

>FdkfqflkyKyTfwwib`o^kh$pPeobaabo%23+2)4+2&yyNFAy525y
@FdkfqflkyKyDlrmqebo^jmlcqeb_fdpqor`qrobfkqebt^qbo)hfiiPrmbosfploIrdtfwwib^kadbqefphbv%23+0)5+/&yyNFAy525y
QFdkfqflkyKyTfwwib`o^kh$pPeobaabo%23+2)4+2&yyNFAy525y
>QebBp`^mbyKyTfwwib`o^kh$pPeobaabo%23+2)4+2&yyNFAy530y
@QebBp`^mbyKyMolqb`qTfwwib`o^kh^kaqebpqlibkdl_ifkpeobaabo%23+2)4+2&yyNFAy530y
@Jfkbo$pCloqrkbyKyObqofbsbqebX@^qpBvbBjbo^iaZcoljlkblcqebSbkqrob@l+LsbopbboploBkclo`bop%3.+2)3+/&yyNFAy563y

EQeb@olppol^apyKyEb^oqeloork_^`hql@olppol^apyyRy3615yyNFAy55.y
QMoltiboplcqeb?^oobkpyKyPbodo^A^ohqelok%2/+/)0.+-&yyNFAy6-0y
>B`ebv^hbbyKyPbodo^A^ohqelok%2/+/)0.+-&yyNFAy55.y
QE^omvIfbrqbk^kqpyKyA^oplhPtfcqa^ddbo%2.+3)0-+6&yyNFAy542y
>Pbobk^?illacb^qeboyKyA^oplhPtfcqa^ddbo%2.+3)0-+6&yyNFAy543y
Q@bkq^ro?o^`bopyKyObdqe^oAb^qed^qb%12+1)/5+1&yyNFAy522y

@QebPq^dk^kqL^pfpyKyDlqlqebcfpprob^qqeb_lqqljlcqebi^hb^qqebPq^dk^kqL^pfp%22+3)1/+4&yyNFAy544y
@SboldqebAbosfpeyKyVlre^sbqlhfiiqeblqebo@bkq^rop^olrkaqeb`ljj^kaqbkq%2/+45)1.+46&rkqfiSboldtfiipm^tk+HfiiSboldtebkeb^mmb^op^kaillqefpeb^ayyNFAy52.y

OO^q`ebqyKyOrkqlO^q`ebq%3/+3)04+2&yyNFAy56.y
QPqlibk?llqvyKyD^wiltb%3/+4)03+0&yyNFAy555y
QQebBp`^mbyKyPmrqqbos^isb%30)04+/&yyNFAy530y
QJfkbo$pCloqrkbyKyTe^ocj^pqboAfwwvtfd%30+0)05+1&yyNFAy563y
QP^jlmei^kdb%M^oq1&yKyPmrqqbos^isb%30)04+/&yyNFAy6-/y
>QebDrkplcKloqet^q`eyKy@^mq^fkQe^il$qe^p?ofdeqprk%3/+0)06&yyNFAy56.y

CQeb@olppol^apyKy?o^dlh%30+.)04+/&yyNFAy55-y
QQebPq^dk^kqL^pfpyKyQlkd^Orkbqlqbj%2/+/)0.+6&yyNFAy544y
>>iqboba?bfkdpyKyQlkd^Orkbqlqbj%2/+/)0.+6&yyNFAy55-y
QSboldqebAbosfpeyKyObdqe^oAb^qed^qb%12+1)/5+1&yyNFAy52.y
>Ebwori?illaj^ohyKyObdqe^oAb^qed^qb%12+1)/5+1&yyNFAy52/y
@Ebwori?illaj^ohyKyHfiiEbwori?illaj^oh_vqebl^pfp^q%13+/)05+5&^ka`liib`qefpeb^a)ebm^qolip^olrkaqebl^pfp`il`htfpbplork`lrkqbo`il`htfpbqlcfkaefj+Ebe^pqtlm^qolitfqeefj)grpqcl`rplkhfiifkdefjcfopqql`ljmibqbqebnrbpqqebdo^sbv^oafpsbov`ilpbfcvlrafbyyNFAy52/y
QEbwori?illaj^ohyKyObdqe^oAb^qed^qb%12+1)/5+1&*phfmcliiltrmyyNFAy52/y

@Pbobk^?illacb^qeboyKyHfiiPbobk^?illacb^qebofkqebkloqetbpqm^oqlcqeb?^oobkp%06+/)./+3&yyNFAy543y
@B`ebv^hbbyKyDlqlB`ebv^hbb$pi^fo%22+5).4+-3&)hfiiqebIflk^kaillqqebMbiqyyNFAy55.y
@O^mqloQefbsbpyKyHfiiqebO^mqlop^`olppqeb?^oobkpclo./XO^mqloEb^apZ%2/+14)13+2&)%2/+2)13+.&)%2/+-2)13+13&yyNFAy536y

EQeb@olppol^apyRy3615yyNFAy0/5.y
QO^mqloQefbsbpyKyD^wold%2.+6)0-+0&yyNFAy536y
>PqlibkPfisboyKyD^wold%2.+6)0-+0&yyNFAy0/5.y
QB`ebv^hbbyKyPbodo^A^ohqelok%2/+/)0.+-&yyNFAy55.y
>Qeb>kdovP`vqeb`i^tpyKyPbodo^A^ohqelok%2/+/)0.+-&yyNFAy6-2y
QPbobk^?illacb^qeboyKyA^oplhPtfcqa^ddbo%2.+3)0-+6&yyNFAy543y
>IbqqboqlGfk$WfiyKyA^oplhPtfcqa^ddbo%2.+3)0-+6&yyNFAy.-3-y
>@lkprjba_vE^qobayKyJ^khofh%2/)0.+3&yyNFAy566y
>Ilpqfk?^qqibyKyJ^khofh%2/)0.+3&yyNFAy16/.y

@>iqboba?bfkdpyKyDlqlQebIrpet^qboL^pfp)plrqetbpqlc@olppol^ap%22)1/&^kahfiiqebL^pfpPk^mg^tpcloqebfoPebiipyyNFAy55-y
@Qeb>kdovP`vqeb`i^tpyKyHfiiPrkp`^ibo^mqlop^ka`liib`qXPrkp`^ibCb^qeboZ+Rpbqebcb^qeboplkqeb0P`vqeb`i^tkbpqp*VbiiltKbpqfp^q%2/)13&+QebObaKbpqfp^q%2/)14&+Qeb?irbKbpqfp^q%20)13&yyRy2.32yyNFAy6-2y
@Ilpqfk?^qqibyKyJ^khofh$pTfcb`^k_bclrkaplrqelcqeb_ofadb)fk^erqkloqelcqebol^a%16+0)2-+1&yyNFAy16/.y
@Qof_bp^qT^oyKyHfii3?ofpqib_^`hT^qboPbbhbop)./?ofpqib_^`hQeloktb^sbop^ka./?ofpqib_^`hDblj^k`bop%2-)24&yyNFAy545y
@@lkprjba_vE^qobayKyHfii?ofpqib_^`hNrfi_l^opclo3-X?ofpqib_^`hNrfi_l^oQrphpZ^olrka%2.)21&yyNFAy566y
@PqlibkPfisboyKyObqofbsbqebXPqlibkPfisboZcoljqebO^mqloDolrkap%25)20+5&yyNFAy0/5.y
@O^mqloElokpyKyD^qebo2XFkq^`qO^mqloElokpZcoljPrkp`^ibP`vqeb`i^tp^qqebO^mqloDolrkap%25)20+5&yyNFAy532y
@QebDrkplcKloqet^q`eyKy@liib`q.-XQebo^jlobJba^ipZ^kapi^v@^mq^fkC^fojlrkq%3/)22&)@^kklkbboTebpp^k%30)24&^ka@^kklkbboPjvqeb%3-)22&yyNFAy56.y
>CobbColjqebEliayKyDfiqe^obpCfob_lrde%3.+6)21+6&yyNFAy565y
@CobbColjqebEliayKyBp`loqDfiqe^obpqlO^q`ebq%3.+6)21+6&yyNFAy565y

QQebDrkplcKloqet^q`eyKy@^mq^fkQe^il$qe^p?ofdeqprk%3/+0)06&yyNFAy56.y
QCobbColjqebEliayKy@^mq^fkQe^il$qe^p?ofdeqprk%3/+0)06&yyNFAy565y
QO^mqloElokpyKyJb_lhJfwwvofu%3/+1)04+3&yyNFAy532y
>AbbmjlppPmfaboBddpyKyJb_lhJfwwvofu%3/+1)04+3&yyNFAy.-36y
>WfwCfwwfhpyKyPmrqqbos^isb%30+-)04+/&yyNFAy.150y

CQeb@olppol^apyKy?o^dlh%30+.)04+/&yyNFAy.2.-y
QPqlibkPfisboyKyD^wold%2.+6)0-+0&yyNFAy0/5.y
>ObmloqqlH^ao^hyKyQeloh%2.+2)0-+5&yyNFAy321.y
QQeb>kdovP`vqeb`i^tpyKyPbodo^A^ohqelok%2/+/)0.+-&yyNFAy6-2y
>GlokPhvpbboyKyPbodo^A^ohqelok%2/+/)0.+-&yyNFAy0/3.y
QIlpqfk?^qqibyKyJ^khofh%2/)0.+3&yyNFAy16/.y
Q@lkprjba_vE^qobayKyJ^khofh%2/)0.+3&yyNFAy566y
Q>iqboba?bfkdpyKyQlkd^Orkbqlqbj%2/+/)0.+6&yyNFAy55-y
>BddErkqyKyHloo^k%2.+.)/6+3&yyNFAy535y

C@^jmQ^ro^glyKyAbso^h%2.+2)0-+0&yyNFAy2-2/y
QQof_bp^qT^oyKyJ^kdibqllqe%11+3)26+/&yyNFAy545y
>?illaPe^oaplc>d^j^dd^kyKyJ^kdibqllqe%11+3)26+/&yyNFAy2-2/y
Q?illaPe^oaplc>d^j^dd^kyKyJ^kdibqllqe%11+3)26+/&yyNFAy2-2/y
>?bqo^v^icoljTfqefk%M^oq.&yKyJ^kdibqllqe%11+3)26+/&yyNFAy546y
QGlokPhvpbboyKyPbodo^A^ohqelok%2/+/)0.+-&yyNFAy0/3.y
>JbiloPbkapTloayKyGlokPhvpbbo%11+5)26+.&yyNFAy..0-y

CQerkabo?irccyKyLjrp^Qerkaboelok%11+2)26+.&yyNFAy..62y
>QebP^`obaCi^jb%M^oq.&yWyQerkabo?irccyyKyW^kdbkPqlkbellc%21+3)2.+2&)lkqebqefoaibsbilcqebj^fkofpbyyNFAy..62y

CQeb@olppol^apyOyQ^robkyyKyQ^i%13+5)2-+/&yyWyQerkabo?irccy
OO^wloEfiiyOyQ^robkyyKyOrkB^pqqlO^wloEfii%2-+6)10+3&yyWyArolq^oy
OLodofjj^oyOyQ^robkyyKyOrkKloqeqlLodofjj^o%12+1)./+1&yyWyArolq^oy
cLodofjj^oyOyQ^robkyyKyAlo^p%12+0)31&yyWyLodofjj^oy

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
