DugisGuideViewer:RegisterGuide("Ghostlands (13-20 Blood Elf)", "The Barrens (20 Blood Elf)", "Horde", "L", function()
return [[
AAA

>JfppfkdfkqebDelpqi^kapyWyBsboplkdTllapyyOyLo`)Qolii)Q^robk)Rkab^ayyKyJ^dfpqofuI^kao^A^tkpqofabo%11+--)4-+4.&yyNFAy6.11y
QJfppfkdfkqebDelpqi^kapyWyBsboplkdTllapyyOyLo`)Qolii)Q^robk)Rkab^ayyKy@lrofboA^tkpqofabo%16+-)56+-&yyNFAy6.11y
>QebC^iibk@lrofboyWyBsboplkdTllapyyOyLo`)Qolii)Q^robk)Rkab^ayyKy>mlqeb`^ovQebao^%16+-)56+-&yyNFAy6.14y
@QebC^iibk@lrofboyOyLo`)Qolii)Q^robk)Rkab^ayyKyD^qebo1XMi^drba?illaP^jmibpZcolj_b^pqpgrpqplrqefkqebDelpqi^kap%//).2&yyNFAy6.14y
QQebC^iibk@lrofboyWyBsboplkdTllapyyOyLo`)Qolii)Q^robk)Rkab^ayyKy>mlqeb`^ovQebao^%16+-)56+-&yyNFAy6.14y
>AbifsbovqlQo^knrfiifbkyWyBsboplkdTllapyyOyLo`)Qolii)Q^robk)Rkab^ayyKy@lrofboA^tkpqofabo%16+-)56+-&yyNFAy6.15y

OQo^knrfiifbkyKyCliiltqebol^aplrqeqlQo^knrfiifbk%13+/)/5+1&yyNFAy60/6y
QAbifsbovqlQo^knrfiifbkyKy>o`^kfpqS^kaofi%13+/)/5+1&yyNFAy6.15y
>QebClop^hbkyKy>o`^kfpqS^kaofi%13+/)/5+1&yyNFAy60/4yyOy?illaBicy
QQebClop^hbkyKyEfdeBub`rqloJ^sobk%11+6)0/+1&yyNFAy60/4yyOy?illaBicy
>QebClop^hbkyKy>o`^kfpqS^kaofi%13+/)/5+1&yyNFAy60/6yyOyLo`)Qolii)Q^robk)Dl_ifk)Rkab^ay
QQebClop^hbkyKyEfdeBub`rqloJ^sobk%11+6)0/+1&yyNFAy60/6yyOyLo`)Qolii)Q^robk)Dl_ifk)Rkab^ay
>Obqrokql>o`^kfpqS^kaofiyKyEfdeBub`rqloJ^sobk%11+6)0/+1&yyNFAy6425y
QObqrokql>o`^kfpqS^kaofiyKy>o`^kfpqS^kaofi%13+/)/5+1&yyNFAy6425y
>Prk`oltkSfii^dbyKy>o`^kfpqS^kaofi%13+/)/5+1&yyNFAy6.05y
>Qlj_bo$pPrmmifbpyKyO^qefpQlj_bo%14+/)/5+4&yyNFAy6.2/y
>DllapcoljPfisbojllk@fqvyOy?illaBicyyKyNr^oqboj^pqboIvjbi%14+0)/6+.&yyNFAy6.0-y
eQo^knrfiifbkyKyFkkhbbmboH^i^ofk%15+5)0/+0&yyNFAy6.16y
>QebMi^drba@l^pqyKy>mlqeb`^ovObkwfqebk%14+2)01+4&yyNFAy6.16y

QDllapcoljPfisbojllk@fqvyOy?illaBicyyKyPhvj^pqboPrktfkd%12+2)0-+2&yyNFAy6.0-y
>CivqlPfisbojllk@fqvyOy?illaBicyyKyPhvj^pqboPrktfkd%12+2)0-+2&yyNFAy6.00y
CPfisbojllk@fqvyOy?illaBicyyKyPhvj^pqboPrktfkd%12+2)0-+2&yyNFAy6.00yyNFAy6.01y
QCivqlPfisbojllk@fqvyWyPfisbojllk@fqvyyOy?illaBicyyKyP^qeobk>wroba^tk%21+-)4-+3&yyNFAy6.00y
>QebCfopqQof^iy@yM^i^afkyyKyHkfdeq*Iloa?illas^ilo%56+.)03+/&yyNFAy6345yyWyPfisbojllk@fqvy

>PhvjfpqobppDil^jfkdyOy?illaBicyyWyPfisbojllk@fqvyyKyP^qeobk>wroba^tk%21+-)4-+3&yyNFAy6.01y
QPhvjfpqobppDil^jfkdyOy?illaBicyyKyPhvjfpqobppDil^jfkd%21+1)2-+5&yyNFAy6.01yyWyBsboplkdTllapy
>ObqrokqlNr^oqboj^pqboIvjbiyOy?illaBicyyKyPhvjfpqobppDil^jfkd%21+1)2-+5&yyNFAy6.02yyWyBsboplkdTllapy
CQo^knrfiifbkyOy?illaBicyyKyPhvjfpqobppDil^jfkd%21+1)2-+5&yyNFAy60.2yyWyBsboplkdTllapy
QObqrokqlNr^oqboj^pqboIvjbiyOy?illaBicyyKyNr^oqboj^pqboIvjbi%14+0)/6+.&yyNFAy6.02y

>>klh$prqbkyKyAvfkd?illaBic%24+3).1+0&yyNFAy60.2y
@QebCfopqQof^iy@yM^i^afkyyKyIfdeqqeb_o^wfbo^q%35)4&^kahfiiqeb?illaHkfdeqP^kdof^pPqfii_i^abyyNFAy6345y
@Prk`oltkSfii^dbyKyPi^v.-Kbor_fpDr^oapfkPrk`oltkSfii^db%25).2&yyNFAy6.05y
@>klh$prqbkyKyPi^v>klh$prqbkfkPrk`oltkSfii^db%26)..&yyNFAy60.2y
>Ab^ifkdtfqeWb_$Plo^yKyO^kdboS^i^kk^%36+1).2+.&yyNFAy6.10y
>ClodlqqbkOfqr^ipyKyDbo^kfpTefqbjloklkqebfpi^kaqlqebb^pq%4/+0).6&yyNFAy6.24y

OC^opqofaboBk`i^sbyKyQlqebplrqe%4/)0/&yyNFAy6.25y
>?b^oboplcqebMi^drbyKyC^opqofaboPbafk^%4/+2)0/+-&yyNFAy6.25y
>PmfofqplcqebAoltkbayKyO^kdboHobkk$^k%4/+/)/6+6&yyNFAy6/41y

@Ab^ifkdtfqeWb_$Plo^yKy@liib`q3XWb_$Plo^QoliiB^opZb^pqpfablcqebi^hb%40)./&+TlohlkPmfofqplcqebAoltkba^kaClodlqqbkOfqr^ip^pvlrptfjlsboyyNFAy6.10y
QAb^ifkdtfqeWb_$Plo^yKyO^kdboS^i^kk^%36+1).2+.&yyNFAy6.10y
>Obmloqql@^mq^fkEbiflpyKyO^kdboS^i^kk^%36+1).2+.&yyNFAy6.13y
@ClodlqqbkOfqr^ipyKyD^qebo5XT^sbcolkqJba^iiflkpZcoljqebi^hb%40)/.&yyNFAy6.24y
QClodlqqbkOfqr^ipyKyDbo^kfpTefqbjlok%4/+0).6&yyNFAy6.24y
>S^knrfpefkd>nr^kqflkyKyDbo^kfpTefqbjlok%4/+0).6&yyNFAy6.41y
@S^knrfpefkd>nr^kqflkyKyRpbX?rkaiblcJba^iiflkpZlkqeb>iq^olcQfa^iJ^pqbov%4.+0).1+6&+Pi^vqebbibjbkq^ihkltk^p>nr^kqflk%4.).1&yyNFAy6.41yyRy//342y
QS^knrfpefkd>nr^kqflkyKyDbo^kfpTefqbjlok%4/+0).6&yyNFAy6.41y
@PmfofqplcqebAoltkbayKyHfii5Sbkdbcri>mm^ofqflkp^ka5O^sbkfkd>mm^ofqflkpfkqebi^hb%40)//&yyNFAy6/41y
@?b^oboplcqebMi^drbyKyPi^v.-Delpq`i^tIvkubp%44+/)/5+0&%41+1)05+1&%34)11&yyNFAy6.25y

Q?b^oboplcqebMi^drbyKyC^opqofaboPbafk^%4/+2)0/+-&yyNFAy6.25y
>@ro_fkdqebMi^drbyKyC^opqofaboPbafk^%4/+2)0/+-&yyNFAy6.26y
QObmloqql@^mq^fkEbiflpyKy@^mq^fkEbiflp%4/+0)/6+4&yyNFAy6.13y
QPmfofqplcqebAoltkbayKyO^kdboHobkk$^k%4/+/)/6+6&yyNFAy6/41y

EQo^knrfiifbkyRy3615yyNFAy6.4.y
CPfisbojllk@fqvy@yM^i^afkyyKyPhvj^pqboPrktfkd%12+2)0-+2&yyNFAy635.y
QQebCfopqQof^iy@yM^i^afkyyKyHkfdeq*Iloa?illas^ilo%56+.)03+/&yyNFAy6345yyWyPfisbojllk@fqvy
>>PqravfkMltboy@yM^i^afkyyKyHkfdeq*Iloa?illas^ilo%56+.)03+/&yyNFAy635.yyWyPfisbojllk@fqvy
Q>PqravfkMltboy@yM^i^afkyyKyJ^dfpqbo>pq^ilo?illaptlok%6.+2)03)2&yyNFAy635.yyWyPfisbojllk@fqvy
>@i^fjfkdqebIfdeqy@yM^i^afkyyKyJ^dfpqbo>pq^ilo?illaptlok%6.+2)03)2&yyNFAy6351yyWyPfisbojllk@fqvy
@@i^fjfkdqebIfdeqy@yM^i^afkyyKyRpbXPefjjbofkdSbppbiZlk?illaBicJ^dfpqbop^olrka%6.)03&yyRy/1.24yyNFAy6351yyWyPfisbojllk@fqvy
Q@i^fjfkdqebIfdeqy@yM^i^afkyyKyHkfdeq*Iloa?illas^ilo%56+.)03+/&yyNFAy6351yyWyPfisbojllk@fqvy
>ObabbjfkdqebAb^ay@yM^i^afkyyKyHkfdeq*Iloa?illas^ilo%56+.)03+/&yyNFAy6352yyWyPfisbojllk@fqvy
@ObabbjfkdqebAb^ay@yM^i^afkyyKyDlqlqeb/kacillolcqebFkk%5-)25&^karpbqebXCfiibaPefjjbofkdSbppbiZqlobpprob`qP^kdof^pPqfii_i^abyyRy/1.51yyNFAy6352yyWyPfisbojllk@fqvy
QObabbjfkdqebAb^ay@yM^i^afkyyKyHkfdeq*Iloa?illas^ilo%56+.)03+/&yyNFAy6352yyWyPfisbojllk@fqvy
CQo^knrfiifbky@yM^i^afkyyKyPhvjfpqobppDil^jfkd%21+1)2-+5&yyNFAy6.4.y

>@rifk^ov@ork`eyKyJ^pqbo@ebcJlriafbo%15+0)0-+6&yyNFAy6.4.y
>P^is^dfkdqebM^pqyKyJ^dfpqboA^obkfp%13+.)0.+6&yyNFAy6.2-y
>AltkqebAb^aP`^oyKyAb^qepq^ihboO^qefbi%13)00+1&yyNFAy6.22y
>Fksbpqfd^qb>k$a^olqeyKyA^jb>rofcbolrp%11+6)0/+2&yyNFAy6.3-y
>Qolr_ib^qqebRkaboifdeqJfkbpyKyAb^qepq^ihboJ^iqbkafp%11+5)0/+0&yyNFAy6.6/y
>QoliiGrgryKyAb^qepq^ihboJ^iqbkafp%11+5)0/+0&yyNFAy6.66y
>Fksbpqfd^qbqeb>j^kf@^q^`lj_pyKy>asfploS^itvk%11+6)0/+2&yyNFAy6.60y
QPrk`oltkSfii^dbyKy>o`^kfpqS^kaofi%13+/)/5+1&yyNFAy6.05y
>DliabkjfpqSfii^dbyKy>o`^kfpqS^kaofi%13+/)/5+1&yyNFAy6.06y
Q>klh$prqbkyKy>o`^kfpqS^kaofi%13+/)/5+1&yyNFAy60.2y

@AltkqebAb^aP`^oyKyPi^v.-OfpbkErkdbobop^ka.-D^kdiba@^kkf_^iplkqebAb^aP`^o%1-)/5&yyNFAy6.22y
@P^is^dfkdqebM^pqyKyD^qebo5X@ovpq^iifwbaJ^k^Bppbk`bpZcoljqeb>o`^kbAbslrobop^kaJ^k^Pefcqbop^qqebP^k`qrjlcqebJllk%03)0-&yyNFAy6.2-y
@Qlj_bo$pPrmmifbpyKyObqofbsbXO^qefpQlj_bo$pPrmmifbpZ%00+3)/3+2&yyNFAy6.2/y
@Fksbpqfd^qb>k$a^olqeyKyFksbpqfd^qbqeb^ob^^q>k$a^olqe^kahfii./PbkqfkbiPmfbp%04).2&yyNFAy6.3-y
@DliabkjfpqSfii^dbyKyAbcb^q3Nrbi$alobfDelpqp^ka1Nrbi$alobfTo^fqep^qDliabkjfpqSfii^db%/4+4).4+6&yyNFAy6.06y
@QebMi^drba@l^pqyKyHfiiqebJroil`plkqeb`l^pqclo3XMi^drbaJroil`PmfkbpZ%.6)//&yyNFAy6.16y
@@ro_fkdqebMi^drbyKyPi^v5Pmfkaibtb_Irohbop^ka.-S^jmfof`Jfpq_^qp%/1)05&yyNFAy6.26y
@@rifk^ov@ork`eyKy@liib`qjlobX@ork`evPmfaboIbdpZfcvlrafak$qe^sbbklrde^iob^av%/1)05&yyNFAy6.4.y

>RkaboifdeqLobP^jmibpyKy>mmobkqf`bPe^qe^of^%0.+2)15+/&yyNFAy6/-4y
@Qolr_ib^qqebRkaboifdeqJfkbpyKyPi^v5?i^`hm^tDkliip)3?i^`hm^tP`^sbkdbop^ka1?i^`hm^tPe^j^k^qqebRkaboifdeqJfkbp%0-)14&yyNFAy6.6/y
@RkaboifdeqLobP^jmibpyKyD^qeboqebXRkaboifdeqLobpZ^cqbohfiifkdPe^jvp^kaP`^sbkdbop^qqebRkaboifdeqJfkbp%0-)14&yyNFAy6/-4y

EQo^knrfiifbkyRy3615yyNFAy6.1-y
Q@rifk^ov@ork`eyKyJ^pqbo@ebcJlriafbo%15+0)0-+6&yyNFAy6.4.y
>Pmfk^iArpqyKyJ^dfpqofu>jfkbi%15+6)0.+1&yyNFAy6/.5y
>OlqqfkdEb^oqpyKyJ^dfpqofu>jfkbi%15+6)0.+1&yyNFAy6/.3y
QQlj_bo$pPrmmifbpyKyO^qefpQlj_bo%14+/)/5+4&yyNFAy6.2/y
QDliabkjfpqSfii^dbyKy>o`^kfpqS^kaofi%13+/)/5+1&yyNFAy6.06y
>TfkaorkkboSfii^dbyKy>o`^kfpqS^kaofi%13+/)/5+1&yyNFAy6.1-y
QP^is^dfkdqebM^pqyKyJ^dfpqboA^obkfp%13+.)0.+6&yyNFAy6.2-y
QFksbpqfd^qb>k$a^olqeyKyA^jb>rofcbolrp%11+6)0/+2&yyNFAy6.3-y
>FkqlL``rmfbaQboofqlovyKyA^jb>rofcbolrp%11+6)0/+2&yyNFAy6.30y
QQolr_ib^qqebRkaboifdeqJfkbpyKyAb^qepq^ihboJ^iqbkafp%11+5)0/+0&yyNFAy6.6/y
>Obq^hfkdTfkaorkkboPmfobyKyEfdeBub`rqloJ^sobk%11+6)0/+1&yyNFAy6.40y
QAltkqebAb^aP`^oyKyAb^qepq^ihboO^qefbi%13)00+1&yyNFAy6.22y
QQebMi^drba@l^pqyKy>mlqeb`^ovObkwfqebk%14+2)01+4&yyNFAy6.16y

@FkqlL``rmfbaQboofqlovyKy@liib`qXKfdeqBicMi^kp7>k$a^olqeZfkqebqbkq%.0)/3&*XKfdeqBicMi^kp7P`ovfkdlkqebPfk$alobfZlkqeb_l^q%.-)//&*XKfdeqBicMi^kp7>k$ltvkZfk^qbkq%./)/0&yyNFAy6.30y
@TfkaorkkboSfii^dbyKyD^qebo3XMe^kq^pj^iPr_pq^k`bZ^ka1XD^odlvibCo^djbkqpZqe^qaolmcoljpe^abp^kad^odlvibplkqebj^fki^ka)plrqelcqeb`obbh%.5)2-&yyNFAy6.1-y
@Obq^hfkdTfkaorkkboPmfobyKyPi^v5Ab^qelijb>`livqbp^ka.-C^iibkO^kdbop^qqebTfkaorkkboPmfob%.3+4)24+4&yyNFAy6.40y

EQo^knrfiifbkyRy3615yyNFAy6.1-y
>QebP^k`qrjlcqebPrkyKyJ^dfpqboA^obkfp%13+.)0.+6&yyNFAy6.2.yyLy
QObq^hfkdTfkaorkkboPmfobyKyEfdeBub`rqloJ^sobk%11+6)0/+1&yyNFAy6.40y
QFkqlL``rmfbaQboofqlovyKyA^jb>rofcbolrp%11+6)0/+2&yyNFAy6.30y
>QebI^av$pKb`hi^`byRy//264yyKyQebfqbjXQebI^av$pKb`hi^`bZpq^oqpnrbpq*aolmmba_vC^iibkO^kdbo^kaAb^qelijb>`livqb^olrka%./)24&yyNFAy6.42y
QQebI^av$pKb`hi^`byKyEfdeBub`rqloJ^sobk%11+6)0/+1&yyNFAy6.42y
>GlrokbvqlRkabo`fqvyKyEfdeBub`rqloJ^sobk%11+6)0/+1&yyNFAy6.5-y
QTfkaorkkboSfii^dbyKy>o`^kfpqS^kaofi%13+/)/5+1&yyNFAy6.1-y
>AbifsboqebMi^kpql>k$qbi^pyKyA^jb>rofcbolrp%11+6)0/+2&yyNFAy6.33y

OP^k`qrjlcqebPrkyKyOrkqlP^k`qrjlcqebPrkqlqebplrqeb^pq%22)15&yyNFAy6/5/y
>QebC^opqofaboBk`i^sbyKyJ^dfpqboH^bkaofp%22+-)15+6&yyNFAy6/5/y
QRkaboifdeqLobP^jmibpyKyJ^dfpqboNr^iibpqfp%22+-)15+4&yyNFAy6/-4y
QQebP^k`qrjlcqebPrkyKyJ^dfpqboFalkfp%21+6)15+1&yyNFAy6.2.yyLy
>T^olkAb^qelijbyKyJ^dfpqboFalkfp%21+6)15+2&yyNFAy6//-y

QAbifsboqebMi^kpql>k$qbi^pyKyJ^dfpqboPvi^pqlo%3-+0)02+5&yyNFAy6.33y
>Ab^`qfs^qb>k$ltvkyKyJ^dfpqboPvi^pqlo%3-+0)02+5&yyNFAy6.36y

Q@ro_fkdqebMi^drbyKyC^opqofaboPbafk^%4/+2)0/+-&yyNFAy6.26y
>>qq^`hlkWb_$Qbi^yKyC^opqofaboPli^kk^%4/+/)0.+0&yyNFAy6/43y
>Pe^altmfkbTb^mlkovyKy@^mq^fkEbiflp%4/+0)/6+4&yyNFAy6/.1y
>>IfqqibA^pelcPb^plkfkdyKy>mlqeb`^ovSbkrpqrp%4/+4)0.+2&yyNFAy6/42y
QQebC^opqofaboBk`i^sbyKyO^kdboSvkk^%4.+6)0/+3&yyNFAy6/5/y
>QebQo^fqlo$pPe^altyKyO^kdboSvkk^%4.+6)0/+3&yyNFAy6.3.y

QQebQo^fqlo$pPe^altyKyArpqvGlrok^i^qA^tkpq^oPmfob)fkqeb_rfiafkd^qqebqlmlcqebo^jm%5-).5&yyNFAy6.3.y
>EfkqplcqebM^pqyKyArpqvGlrok^i^qA^tkpq^oPmfob%5-).5&yyNFAy6.3/y
@>qq^`hlkWb_$Qbi^yKyHfii5Pe^altmfkbPe^alt`^pqbop^ka5Pe^altmfkbEb^aerkqboparbb^pqlcC^opqofaboBk`i^sb%46)03&yyNFAy6/43y
K@liib`q>ubp^kaJ^`bpyKyHbbmhfiifkdqelpbqoliipEb^aerkqbopcloqebXEb^aerkqbo>ubZ^kaPe^alt`^pqbopcloXPe^alt`^pqboJ^`bZyyNFAy6/.1yyNLyEb^aerkqbo>ub70,0y
K@liib`qJ^`bpyKyHbbmhfiifkdPe^alt`^pqbopcloXPe^alt`^pqboJ^`bZyyNFAy6/.1yyNLyPe^alt`^pqboJ^`b70,0y
Q>qq^`hlkWb_$Qbi^yKyC^opqofaboPli^kk^%4/+/)0.+0&yyNFAy6/43y
>>pp^riqlkWb_$Klt^yKyC^opqofaboPli^kk^%4/+/)0.+0&yyNFAy6/44y
QEfkqplcqebM^pqyKyO^kdboSvkk^%4.+6)0/+3&yyNFAy6.3/y
>ObmloqqlJ^dfpqboH^bkaofpyKyO^kdboSvkk^%4.+6)0/+3&yyNFAy6.4/y

@Fksbpqfd^qbqeb>j^kf@^q^`lj_pyKyOrkqeolrdeqeb>j^kf@^q^`lj_pql`ljmibqbqefpnrbpq%3/+54)0.+43&yyNFAy6.60y
@QoliiGrgryKy@liib`q5XQoliiGrgrZqe^qaolmcoljqebjl_pfkqeb>j^kf`^q^`lj_p)tbpqlcqebbk`i^sb%33)/6&yyNFAy6.66y
>Bp`^mbcoljqeb@^q^`lj_pyKyO^kdboIfi^qe^%3/)02&yyNFAy6/./y
@Bp`^mbcoljqeb@^q^`lj_pyKyBp`loqqebO^kdbo_^`hql`^jm%3/)02&yyNFAy6/./y
QBp`^mbcoljqeb@^q^`lj_pyKy@^mq^fkEbiflp%4/+0)/6+4&yyNFAy6/./y

@>IfqqibA^pelcPb^plkfkdyKyRpbqebX>mlqeb`^ov$pMlfplkZlkqebCobpeCfpeO^`h%35)25&)qebPjlhbaJb^qO^`h%30)42&)^kaqebplrqeO^tJb^qO^`h%32)34&^qWb_$Klt^yyRy//463yyNFAy6/42y
@Pe^altmfkbTb^mlkovyKy@liib`q0X@^qiloa@i^tpZ^ka0XEbuuboPq^sbpZ^qWb_$Klt^%34)2-&yyNFAy6/.1y
@>pp^riqlkWb_$Klt^yKyHfii.-Pe^altmfkb@^qiloap^ka.-Pe^altmfkbEbuubop^qWb_$Klt^%34)2-&yyNFAy6/44y
@Ab^`qfs^qb>k$ltvkyKyDbqqebX@ovpq^i@lkqoliifkdLo_Zcolj^PbkqfkbiFkcfiqo^qloqe^q`^k_bclrka^olrkaqebKfdeqBicJllk@ovpq^itef`evlrkbbaqlab^`qfs^qbtfqeqebX@ovpq^i@lkqoliifkdLo_Z%25+0)31+4&yyNFAy6.36yyRy/0.6.y

Q>pp^riqlkWb_$Klt^yKyC^opqofaboPli^kk^%4/+/)0.+0&yyNFAy6/44y
QPe^altmfkbTb^mlkovyKy@^mq^fkEbiflp%4/+0)/6+4&yyNFAy6/.1y
Q>IfqqibA^pelcPb^plkfkdyKy>mlqeb`^ovSbkrpqrp%4/+4)0.+2&yyNFAy6/42y
QAb^`qfs^qb>k$ltvkyKyJ^dfpqboPvi^pqlo%3/)1.+3&%3-+0)02+5&yyNFAy6.36y

QObmloqqlJ^dfpqboH^bkaofpyKyJ^dfpqboH^bkaofp%22+-)15+6&yyNFAy6.4/y
>QebQtfkWfddro^qpyKyJ^dfpqboH^bkaofp%22+-)15+6&yyNFAy6.43y
>@ib^ofkdqebT^vyKy>mmobkqf`bSlo$bi%13+2)23+/&yyNFAy6/5.y
@@ib^ofkdqebT^vyKyPi^v.-Dob^qboPmfkaibtb_p^ka.-Delpq`i^tO^s^dbopqlqebplrqe%2.)3/&yyNFAy6/5.y
Q@ib^ofkdqebT^vyKy>mmobkqf`bSlo$bi%13+2)23+/&yyNFAy6/5.y

@QebQtfkWfddro^qpyKyQo^sbiqlqeb?ibbafkdWfddro^q^kaqebEltifkdWfddro^q^kaob`lsboqebXPqlkblcIfdeqZ%1-+0)16+5&^kaqebXPqlkblcCi^jbZ%01+0)14+5&yyNFAy6.43y
@T^olkAb^qelijbyKyPi^v2BvbplcA^o$he^k)3Kbor_fp@bkqroflkp^ka3T^fibopfkAb^qelijb%03)40&yyNFAy6//-y
@Pmfk^iArpqyKyD^qebo.-XPmfk^iArpqpZcoljqebphbibqlkp^qqebAb^aP`^ob%05)3-&yyNFAy6/.5y
@OlqqfkdEb^oqpyKyD^qebo.-XOlqqfkdEb^oqpZcoljqebwlj_fbp^qqebAb^aP`^ob%05)3-&yyNFAy6/.3y

EQo^knrfiifbkyRy3615yyNFAy6.4-y
QOlqqfkdEb^oqpyKyJ^dfpqofu>jfkbi%15+6)0.+1&yyNFAy6/.3y
QPmfk^iArpqyKyJ^dfpqofu>jfkbi%15+6)0.+1&yyNFAy6/.5y
QQoliiGrgryKyAb^qepq^ihboJ^iqbkafp%11+5)0/+0&yyNFAy6.66y
QFksbpqfd^qbqeb>j^kf@^q^`lj_pyKy>asfploS^itvk%11+6)0/+2&yyNFAy6.60y

QT^olkAb^qelijbyKyJ^dfpqboFalkfp%21+6)15+2&yyNFAy6//-y
QQebQtfkWfddro^qpyKyJ^dfpqboH^bkaofp%22+-)15+6&yyNFAy6.43y
>A^o$He^k$pIfbrqbk^kqpyKyJ^dfpqboFalkfp%21+6)15+2&yyNFAy6.4-y
>>Obpqlo^qfsbAo^rdeqyKy>o`^kfpqG^kba^%21+6)15+1&yyNFAy6544y

Q>Obpqlo^qfsbAo^rdeqyKy>mlqeb`^ovObkwfqebk%14+2)01+4&yyNFAy6544y
>@^mqfsbp^qAb^qelijbyKy>mlqeb`^ovObkwfqebk%14+2)01+4&yyNFAy6.31y

OAb^qelijbyKyOrkqlAb^qelijb%02)42&y
RAofkhrmyRy//446y
RAofkhrmyRy//445y
@@^mqfsbp^qAb^qelijbyKyRpbXObkwfqebk$pObpqlo^qfsbAo^rdeqZqlobp`rbBkfqefkqeb`ovmq%0/)40&)S^okfp%1-)50&)^kaSbalo^k%0/)56&yyNFAy6.31yyRy//3/5y
@A^o$He^k$pIfbrqbk^kqpyKySbkqrobfkqlAb^qelijbqlpi^vGroflkfkqeb`ovmq%0/)40&)?lodlqe%1-)50&)J^plmebq%03)55&)^kaJfoalo^k%04)46&yyNFAy6.4-y

QA^o$He^k$pIfbrqbk^kqpyKyJ^dfpqboFalkfp%21+6)15+2&yyNFAy6.4-y
Q@^mqfsbp^qAb^qelijbyKy>o`^kfpqG^kba^%21+6)15+1&yyNFAy6.31y

CPfisbojllk@fqvyKyPhvj^pqboPrktfkd%12+2)0-+2&y
>QebPb`lkaQof^iy@yM^i^afkyyKyHkfdeq*Iloa?illas^ilo%56+.)03+/&yyWyPfisbojllk@fqvyyNFAy636-y
QQebPb`lkaQof^iy@yM^i^afkyyKyJ^pqboHbibork?illajlrok%56+.)03+/&yyWyBsboplkdTllapyyNFAy636-y
>QebPb`lkaQof^i%M^oq/&y@yM^i^afkyyKyJ^pqboHbibork?illajlrok%1/+6)/5+4&yyWyBsboplkdTllapyyNFAy6353y
@QebPb`lkaQof^i%M^oq/&y@yM^i^afkyyKy@if`hlkqeb@ovpq^iql_bdfkQebPb`lkaQof^i%1/)/5&^kaabcb^qqebclrot^sbplcJl_pyyWyBsboplkdTllapyyNFAy6353y
QQebPb`lkaQof^i%M^oq/&y@yM^i^afkyyKyJ^pqboHbibork?illajlrok%1/+6)/5+4&yyWyBsboplkdTllapyyNFAy6353y
>ObqrokqlPfisbojllky@yM^i^afkyyKyJ^pqboHbibork?illajlrok%1/+6)/5+4&yyWyBsboplkdTllapyyNFAy636.y
QObqrokqlPfisbojllky@yM^i^afkyyKyHkfdeq*Iloa?illas^ilo%56+.)03+/&yyWyPfisbojllk@fqvyyNFAy636.y
KPhfmqebcliiltrmnrbpqy@yM^i^afky

ORkabo`fqvyWyPfisbojllk@fqvyyKyQbibmloq^qqebprkpmfobfkPfisbojllk@fqv%16).1&y
QGlrokbvqlRkabo`fqvyLyyWyRkabo`fqvyyKyI^avPvis^k^pTfkaorkkbofkqebOlv^iNr^oqbo%24+3)6.+3&yyNFAy6.5-y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
