
DugisGuideViewer:RegisterGuide("Stonetalon Mountains (20-22)", "The Barrens (22-23)", "Horde", "L", function()
return [[
AAA

OElklo$pPq^kayKyQ^hbqebol^atbpqlrqlcqeb@olppol^apqlqebbadblcPqlkbq^ilkJlrkq^fkp%06+3)/6+6&yyNFAy.-3/y
>Dl_ifkFks^abopyWyQeb?^oobkpyyKyPbbobqePqlkb_ob^h%02+0)/4+6&yyNFAy.-3/y
>>sbkdbJvSfii^dbyWyQeb?^oobkpyyKyJ^h^_^Ci^qellc%02+/)/4+5&yyNFAy3215y
@>sbkdbJvSfii^dbyKyHfii5DofjqlqbjOrccf^kp^ka3DofjqlqbjJbo`bk^ofbpfkqebDob^qtllaS^ib%5.)6.&yyNFAy3215y
Q>sbkdbJvSfii^dbyWyQeb?^oobkpyyKyJ^h^_^Ci^qellc%02+/)/4+5&yyNFAy3215y
>HfiiDorkafdA^oh`ilrayWyQeb?^oobkpyyKyJ^h^_^Ci^qellc%02+/)/4+5&yyNFAy33/6y
@HfiiDorkafdA^oh`ilrayKyHfiiDorkafdA^oh`ilra^ka3Dofjqlqbj?orqbp^qqebDofjqlqbjMlpq%40+3)53+.&yyNFAy33/6y
>Molqb`qH^v^yKyH^v^Ci^qellc%40+2)52+4&yyNFAy32/0y
@Molqb`qH^v^yKyBp`loqH^v^Ci^qellcrkqfil_gb`qfsbfp`ljmibqbyyNFAy32/0y

>?illaCbbabopyKyUbk$Wfii^^qJ^i^h^$Gfk%4.+0)61+6&yyNFAy313.y
QIbqqboqlGfk$WfiyLyyKyTfq`eAl`qloGfk$Wfi%41+2)64+5&yyNFAy.-3-y
>Gfk$Wfi$pClobpqJ^df`yKyTfq`eAl`qloGfk$Wfi%41+2)64+5&yyNFAy.-25y

>>o^`eklmel_f^yKyT^kqbaMlpqbo7?bppbibqe%26+.)42+5&yyNFAy3/51y
@>o^`eklmel_f^yKyHfii?bppbibqe^kaq^hbX?bppbibqe$pC^kdZfkPfpefo@^kvlk%2/+/-)40+6-&yyNFAy3/51y
@?illaCbbabopyKyHfii.-Abbmjlpp@obbmbop^ka4AbbmjlppSbkljpmfqqbopfkPfpefo@^kvlk%25)4-&yyNFAy313.y
@AbbmjlppPmfaboBddpyLyyKyD^qeboqebXAbbmjlppBddZfkPfpefo@^kvlk%25)4-&yyNFAy.-36y

QWfwCfwwfhpyKyWfwCfwwfhp`^k_bclrkafk^erq^qTfkapeb^o@o^d%26)3/+3&yyNFAy.150y
>PrmboOb^mbo3---yKyWfwCfwwfhp%26)3/+2&yyNFAy.-60y

@PrmboOb^mbo3---yKyHfiilmbo^qlopcloqebXPrmboOb^mbo3---?irbmofkqpZ%3/)20&yyNFAy.-60y
@Dl_ifkFks^abopyKyHfii.2Sbkqrob@l+IlddbopfkqebTfkapeb^o@o^d%31)22&yyNFAy.-3/y

QPrmboOb^mbo3---yKyWfwCfwwfhp%26)3/+2&yyNFAy.-60y
>CroqeboFkpqor`qflkp%M^oq.&yKyWfwCfwwfhp%26)3/+2&yyNFAy.-61y

cPrkol`hObqob^qyKyQe^oj%12+/)26+6&yyNFAy31/.y
Q>o^`eklmel_f^yKyJ^ddo^kB^oqe_fkabo%14+/)3.+.&yyNFAy3/51y
>?lriabopifabO^sfkbyKyJlo$old^i%14+/)31+.&yyNFAy31/.y

@?lriabopifabO^sfkbyKyBumilobabbmfkqlqeb`^sb^q?lriabopifabO^sfkb^ka_ofkd_^`h.-XObplkfqb@ovpq^ipZ%3.)6.&yyNFAy31/.y

Q?illaCbbabopyKyUbk$Wfii^^qJ^i^h^$Gfk%4.+0)61+6&yyNFAy313.y
QMolqb`qH^v^yKyJ^h^_^Ci^qellc%02+/)/4+5&yyNFAy32/0yyWyQeb?^oobkpy
>H^v^$p>ifsbyKyJ^h^_^Ci^qellc%02+/)/4+5&yyNFAy31-.yyWyQeb?^oobkpy
QHfiiDorkafdA^oh`ilrayWyQeb?^oobkpyyKyJ^h^_^Ci^qellc%02+/)/4+5&yyNFAy33/6y
QDl_ifkFks^abopyWyQeb?^oobkpyyKyPbbobqePqlkb_ob^h%02+0)/4+6&yyNFAy.-3/y
>QebBiabo@olkbyWyQeb?^oobkpyyKyPbbobqePqlkb_ob^h%02+0)/4+6&yyNFAy.-30y
>PeobaafkdJ^`efkbpyWyQeb?^oobkpyyKyPbbobqePqlkb_ob^h%02+0)/4+6&yyNFAy.-35y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)

