
DugisGuideViewer:RegisterGuide("The Barrens (20 Blood Elf)", "Stonetalon Mountains (20-22)", "Horde", "L", function()
return [[
AAA

CLodofjj^oyKyQ^hbqebwbmmbifklrqpfabRkabo`fqv)b^pqqltbo%3-+4)25+4&yyWyQfofpc^iDi^abpyyNFAy/02y
OLodofjj^oyKyOrkqlLodofjj^o%12)5&yyWyArolq^oyyNFAy/02y
cLodofjj^oyKyAlo^p)lkqlmlcqebqltbo^qqeb`bkqbolcLodfjj^o%12+0)31&yyWyLodofjj^oyyNFAy/02y
>Qeb>pebks^ibErkq%M^oq.&yKyT^o`^iiboDloi^`e)m^qolipbkqfobLodofjj^o%16+3)31&)%13+3)03+2&yyWyLodofjj^oyyNFAy/02yyLy

OQeb@olppol^apyKyOrkqlQeb@olppol^ap%2.+6)0-+0&yyNFAy566y
cQeb@olppol^apyKyAbso^h%2.+2)0-+0&yyNFAy566y
>@lkprjba_vE^qobayKyJ^khofh%2/)0.+3&yyNFAy566y
>Ilpqfk?^qqibyKyJ^khofh%2/)0.+3&yyNFAy16/.y

@Ilpqfk?^qqibyOy?illaBic)Qolii)Rkab^a)Lo`yyKyJ^khofh$pTfcb`^k_bclrkaplrqelcqeb_ofadb)fk^erqtbpqlcqebol^a%16+0)2-+1&yyNFAy16/.y

O@^jmQ^ro^glyKyOrkql@^jmQ^ro^gl%11+2)26+.&yyNFAy..62y
c@^jmQ^ro^glyKyLjrp^Qerkaboelok%11+2)26+.&yyNFAy..62y
e@^jmQ^ro^glyKyFkkhbbmbo?vri^%12+3)26&yyNFAy..62y

OQerkabo?irccyOy?illaBic)Qolii)Rkab^a)Lo`yyKyQ^hbqebol^atbpqfkqlJridlob)qebkkloqe^q?illaellcSfii^db%0/)34&yyWyQerkabo?irccyyNFAy..62y
CQerkabo?irccyOyQ^robkyyKyLjrp^Qerkaboelok%11+2)26+.&yyNFAy..62y
>QebP^`obaCi^jb%M^oq.&yWyQerkabo?irccyyKyW^kdbkPqlkbellc)lkqebqefoaibsbilcqebj^fkofpb%22+.)20+.&yyNFAy..62y

C@^jmQ^ro^glyKyQ^i%13+5)2-+/&yyWyQerkabo?irccyyNFAy..0-y
>JbiloPbkapTloayKyGlokPhvpbbo%11+5)26+.&yyNFAy..0-y
>Qof_bp^qT^oyKyJ^kdibqllqe%11+3)26+/&yyNFAy545y
@Ilpqfk?^qqibyOyQ^robkyyKyJ^khofh$pTfcb`^k_bclrkaplrqelcqeb_ofadb)fk^erqtbpqlcqebol^a%16+0)2-+1&yyNFAy16/.yyOyQ^robky
@@lkprjba_vE^qobayKyHfii?ofpqib_^`hNrfi_l^opclo3-X?ofpqib_^`hNrfi_l^oQrphpZ%2.)21&yyNFAy566y
@Qof_bp^qT^oyKyHfii3?ofpqib_^`hT^qboPbbhbop)./?ofpqib_^`hQeloktb^sbop^ka./?ofpqib_^`hDblj^k`bop%2-)24&yyNFAy545y

QQof_bp^qT^oyKyJ^kdibqllqe%11+3)26+/&yyNFAy545y
>?illaPe^oaplc>d^j^dd^kyKyJ^kdibqllqe%11+3)26+/&yyNFAy2-2/y
Q?illaPe^oaplc>d^j^dd^kyKyJ^kdibqllqe%11+3)26+/&yyNFAy2-2/y
>?bqo^v^icoljTfqefk%M^oq.&yKyJ^kdibqllqe%11+3)26+/&yyNFAy546y

CQeb@olppol^apyKyLjrp^Qerkaboelok%11+2)26+.&yyNFAy535y
Q@lkprjba_vE^qobayKyJ^khofh%2/)0.+3&yyNFAy566y
QIlpqfk?^qqibyKyJ^khofh%2/)0.+3&yyNFAy16/.y
>BddErkqyKyHloo^k%2.+.)/6+3&yyNFAy535y
>ObmloqqlH^ao^hyKyQeloh%2.+2)0-+5&yyNFAy321.y

OO^q`ebqyKyOrkqlO^q`ebq%30+-)04+/&yyNFAy.150y
cO^q`ebqyKy?o^dlh%30+.)04+/&yyNFAy.150y
>WfwCfwwfhpyKyPmrqqbos^isb%30+-)04+/&yyNFAy.150y

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)

