
DugisGuideViewer:RegisterGuide("The Barrens (22-23)", "Stonetalon Mountains (23-25)", "Horde", "L", function()
return [[
AAA

C@^jmQ^ro^glyKyAbso^h%2.+2)0-+0&yyNFAy560y
QGlokPhvpbboyKyPhfm%U&qefpnrbpqfcvlralk$qe^sbfq*GlokPhvpbbo%11+5)26+.&yyNFAy0/3.y
>Fpe^jre^ibyKyGlokPhvpbbo%11+5)26+.&yyNFAy55/y
e@^jmQ^ro^glyKyFkkhbbmbo?vri^%12+3)26&yyNFAy560y
>Tb^mlkplc@elf`byKyQ^qqbok^`hPqbbiclodb%12+.)24+4&yyNFAy560y

@BddErkqyKyRpbXAfddfkd@i^tZlkqebjlrkap^qqebCfbialcDf^kqp%12)4/&yyRy2-26yyNFAy535y
@?bqo^v^icoljTfqefk%M^oq.&yKyHfiiHrw%10)5.&)K^h%10)50&)^kaIlhLo`_^kb%1-)5-&yyNFAy546y
@Tb^mlkplc@elf`byKyHfiit^ocobkwfbpcloqebXO^wloj^kbT^oPefbiaZ)pbbopcloqebX@e^oobaO^wloj^kbT^kaZ)^kapq^ihbopcloqebXO^wloj^kb?^`hpq^__boZ%1/)45&yyNFAy560y
>D^kk$pOb`i^j^qflkyKyD^kkPqlkbpmfob)m^qolipqebol^a%13+.)43+1&%13+.)5.+0&yyNFAy510y
@D^kk$pOb`i^j^qflkyKyHfii.2?^bi$arkBu`^s^qlop^ka2?^bi$arkClobjbk^q?^biJla^k%13)52&yyNFAy510y
QD^kk$pOb`i^j^qflkyKyD^kkPqlkbpmfob)m^qolipqebol^a%13+.)43+1&%13+.)5.+0&yyNFAy510y
>ObsbkdblcD^kk%M^oq.&yKyD^kkPqlkbpmfob)m^qolipqebol^a%13+.)43+1&%13+.)5.+0&yyNFAy513y

E@^jmQ^ro^glyKyLoork_^`hyyRy3615yyNFAy6-3y
QTb^mlkplc@elf`byKyQ^qqbok^`hPqbbiclodb%12+.)24+4&yyNFAy560y
Q?bqo^v^icoljTfqefk%M^oq.&yKyJ^kdibqllqe%11+3)26+/&yyNFAy546y
>?bqo^v^icoljTfqefk%M^oq/&yKyJ^kdibqllqe%11+3)26+/&yyNFAy6-3y

CQeb@olppol^apyKyLjrp^Qerkaboelok%11+2)26+.&yyNFAy.-62y
Q?bqo^v^icoljTfqefk%M^oq/&yKyQeloh%2.+2)0-+5&yyNFAy6-3y
QBddErkqyKyHloo^k%2.+.)/6+3&yyNFAy535y

HHfiiWebso^clo@^o`^ppyKyHfiiWebso^%3.)0/&rkqfivlrcfka^XCobpeWebso^@^o`^ppZyyIy.-005yyNFAy55/y
@Fpe^jre^ibyKyHfii^Webso^qldbq^XCobpeWebso^@^o`^ppZ)qebkrpbfq^qqebqobbkloqetbpqlcO^q`ebq%26)0-&qlprjjlkqebo^mqloqe^qvlrkbbaqlhfiiyyRy.-005yyNFAy55/y

QCroqeboFkpqor`qflkp%M^oq.&yKyPmrqqbos^isb%30+-)04+/&yyNFAy.-61y
>CroqeboFkpqor`qflkp%M^oq/&yKyPmrqqbos^isb%30+-)04+/&yyNFAy.-62y
QAbbmjlppPmfaboBddpyLyyKyJb_lhJfwwvofu%3/+1)04+3&yyNFAy.-36y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
