DugisGuideViewer:RegisterGuide("Stonetalon Mountains (23-25)", "The Barrens (25)", "Horde", "L", function()
return [[
AAA

OPmifkqboqobbMlpqyKyCliiltqebol^akloqe)qebkb^pq%40)32&yyWy>pebks^ibyyNFAy.-54y
cPmifkqboqobbMlpqyKySerido^%40+/)3.+3&yyWy>pebks^ibyyNFAy.-54y
E@^jmQ^ro^glyKyLoCiv_^`hyyRy3615yyNFAy.-54y

CPrkOl`hObqob^qyKy?o^dlh%30+.)04+/&yyWyQeb?^oobkpyyNFAy.-54y
>@bk^ofrp$Ibd^`vyKy?o^bivkCfobe^ka%13+-)3-+1&yyNFAy.-54y
Q?lriabopifabO^sfkbyKyJlo$old^i%14+/)31+.&yyNFAy31/.y
>Bibjbkq^iT^oyKyQprk^j^k%14+0)31+0&yyNFAy3060y
>E^omfbpQeob^qbkyKyJ^ddo^kB^oqe_fkabo%14+/)3.+.&yyNFAy3/5/y
ePrkOl`hObqob^qyKyFkkhbbmboG^vh^%14+2)3/+.&yyNFAy30-.y
QH^v^$p>ifsbyKyQ^jjo^Tfkacfbia%14+2)25+2&yyNFAy31-.y
>@v`iblcOb_foqeyKyQ^jjo^Tfkacfbia%14+2)25+2&yyNFAy30-.y
@@v`iblcOb_foqeyKyMf`hrmqebXD^b^PbbaZ^olrkaJfohc^iilkI^hb%15)1.&yyNFAy30-.y
@Gfk$Wfi$pClobpqJ^df`yKyQebpbjl_p`^k_bclrkafkPqlkbq^ilkMb^h%0/).-&+HfiiP^m?b^pqpcloqeb2XPqlkbq^ilkP^mpZ)QtfifdeqOrkkbopcloqeb2XQtfifdeqTefphbopZ)>kqiboba@lropbocloqeb0-X@lropbBvbpZ)^kaCbvAo^dlkpcloqebXCbvAo^dlkP`^ibZyyNFAy.-25y
@@bk^ofrp$Ibd^`vyKyHfii1Plkplc@bk^ofrp)1A^rdeqboplc@bk^ofrp^ka1@bk^oflk?lq^kfpqpfkqeb`bkqbolcPqlkbq^ilkMb^h%04).2&yyNFAy.-54y
Q@v`iblcOb_foqeyKyQ^jjo^Tfkacfbia%14+2)25+2&yyNFAy30-.y
>KbtIfcbyKyQ^jjo^Tfkacfbia%14+2)25+2&yyNFAy305.y
Q@bk^ofrp$Ibd^`vyKy?o^bivkCfobe^ka%13+-)3-+1&yyNFAy.-54y
>Loa^krpyKy?o^bivkCfobe^ka%13+-)3-+1&yyNFAy.-55y

QCroqeboFkpqor`qflkp%M^oq/&yKyWfwCfwwfhp%26+-)3/+2&yyNFAy.-62y
>DbobkwlTobk`etefpqibyKyWfwCfwwfhp%26+-)3/+2&yyNFAy.-63y
@DbobkwlTobk`etefpqibyKyHfiiDbobkwl%31)06&^qqeb@o^dmlliI^hbfkqebT^qboTebbi^kaq^hbXDbobkwl$pJb`e^kf`^i>ojZyyNFAy.-63y
@PeobaafkdJ^`efkbpyKyHfiiqebpeobaabopUQ71^kaUQ76qe^qol^j^olrkafkqebTfkapeb^o@o^d%34)2-&yyNFAy.-35y
QDbobkwlTobk`etefpqibyKyWfwCfwwfhp%26+-)3/+2&yyNFAy.-63y
QGfk$Wfi$pClobpqJ^df`yKyTfq`eAl`qloGfk$Wfi%41+2)64+5&yyNFAy.-25y
QPeobaafkdJ^`efkbpyWyQeb?^oobkpyyKyPbbobqePqlkb_ob^h%02+0)/4+6&yyNFAy.-35y

EPrkOl`hObqob^qyRy3615yyNFAy255.y
@KbtIfcbyKyMi^kq.-XD^b^PbbapZfkD^b^AfoqJlrkaptbpqfkqeb@e^oobaS^ib%0/)34&yyNFAy305.y
@Bibjbkq^iT^oyKyHfiiqebCfobBibjbkq^ipfkqeb@e^oobaS^ibclo.-XFk`bkaofqbpZ%0/)34&yyNFAy3060y
@E^omfbpQeob^qbkyKyPi^v4?illacrovE^omfbp)4?illacrov>j_rpebop)4?illacrovPi^vbop^ka4?illacrovOldrbcb^qebopfkqeb@e^oobaS^ib%0/)43&yyNFAy3/5/y
QKbtIfcbyKyQ^jjo^Tfkacfbia%14+2)25+2&yyNFAy305.y
QBibjbkq^iT^oyKyQprk^j^k%14+0)31+0&yyNFAy3060y
QE^omfbpQeob^qbkyKyJ^ddo^kB^oqe_fkabo%14+/)3.+.&yyNFAy3/5/y
>@^iifkdfkqebObpbosbpyKyJ^ddo^kB^oqe_fkabo%14+/)3.+.&yyNFAy255.y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
