DugisGuideViewer:RegisterGuide("Thousand Needles (25-26)", "Ashenvale (26-27)", "Horde", "L", function()
return [[
AAA

OCobbtfkaMlpqyKyOrkqlCobbtfkaMlpqrpbqebBibs^qlo^q%14)15+/&yyNFAy151.y
QJbpp^dbqlCobbtfkaMlpqyLyyKy@ifcct^q`eboIlkdelok%12+4)2-+4&yyNFAy121/y
>M^`fcvqeb@bkq^royKy@ifcct^q`eboIlkdelok%12+4)2-+4&yyNFAy151.y
>T^kqba*>ok^hDofjqlqbjyKyT^kqbaMlpqbo*>ok^hDofjqlqbj%13+-)2-+5&yyNFAy2.14y
>>ifbkBddyKyE^d^oIfdeqkfkdellc%11+4)2-+0&yyNFAy15/.y
>TfkaOfaboyKyBir%11+6)16+-&yyNFAy1434y
cCobbtfkaMlpqyKyKvpb%12+.)16+/&yyNFAy..16y

@M^`fcvqeb@bkq^royKyHfii./D^i^hP`lrqp).-D^i^hTo^kdibop)^ka3D^i^hTfka`e^pbopgrpqkloqelcCobbtfka%15)10&yyNFAy151.y
>QbpqlcC^fqeyKyAlokMi^fkpq^ihbo%20+6)1.+3&yyNFAy..16y
@QbpqlcC^fqeyKyOrklccqebmi^qcloj%21)1.&yyNFAy..16y
QQbpqlcC^fqeyKyAlokMi^fkpq^ihbo%20+6)1.+3&+Alklqq^hbqebcliilt*rmyyNFAy..16y
@>KbtLobP^jmibyKyCfka^kXRkobcfkbaLobP^jmibZlk^Do^sbipklrqAfddboloProsbvlo%3/)12&yyNFAy..20y
@>ifbkBddyKyQebX>ifbkBddZ`^kpm^tk^olrka0mlppf_ibpmlqp%2/)23&)%12)30&lo%1.)3-&yyNFAy15/.y

OCobbtfkaMlpqyKyOrkqlCobbtfkaMlpqrpbqebBibs^qlo^q%14)15+/&yyNFAy2-31y
QM^`fcvqeb@bkq^royKy@ifcct^q`eboIlkdelok%12+4)2-+4&yyNFAy151.y
>DofjqlqbjPmvfkdyKy@ifcct^q`eboIlkdelok%12+4)2-+4&yyNFAy2-31y
Q>ifbkBddyKyE^d^oIfdeqkfkdellc%11+4)2-+0&yyNFAy15/.y
>PbombkqTfiayKyE^d^oIfdeqkfkdellc%11+4)2-+0&yyNFAy1532y

E@^jmQ^ro^glyRy3615yyNFAy..0.y
>T^peqbM^tkbyKyQebfqbjXT^peqbM^tkb$pCb^qeboZpq^oqpnrbpq*aolmmba_vT^peqbM^tkb^olrka%12)41&^ka%11)46&yyRy2.-0yyLyyNFAy552y
QT^peqbM^tkbyWyQeb?^oobkpyyRy2.-0yyLyyKyGlokPhvpbbo%11+5)26+.&yyNFAy552y
QBko^dbaQerkaboIfw^oapyWyQeb?^oobkpyyLyyKyGlokPhvpbbo%11+5)26+.&yyNFAy6-4y
>@ovlcqebQerkaboe^thyWyQeb?^oobkpyyLyyKyGlokPhvpbbo%11+5)26+.&yyNFAy6.0y
Q>KbtLobP^jmibyWyQeb?^oobkpyyKyQ^qqbok^`hPqbbiclodb%12+.)24+4&yyNFAy..20y
@@ovlcqebQerkaboe^thyLyyKyCfka^kapi^v^Qerkaboe^th%14)3-&yyNFAy6.0y
Q@ovlcqebQerkaboe^thyLyyKyGlokPhvpbbo%11+5)26+.&+Phfmqebcliilt*rmyyNFAy6.0y

CQerkabo?irccyKyLjrp^Qerkaboelok%11+2)26+.&yyWyQeb?^oobkpyyNFAy..0.y
QJbiloPbkapTloayWyQerkabo?irccyyKyJbiloPqlkbellc)lkqebErkqbo$pOfpb%3.)5-&yyNFAy..0-y
>Pqbbipk^myWyQerkabo?irccyyKyJbiloPqlkbellc%3.)5-&yyNFAy..0.y
QQebBiabo@olkbyKyJ^d^qe^Dofjqlqbj)lkqebBiabo$pOfpb%4-+.)0-+5&yyNFAy.-30yyWyQerkabo?irccy
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
