DugisGuideViewer:RegisterGuide("The Barrens (25)", "Thousand Needles (25-26)", "Horde", "L", function()
return [[
AAA

C@^jmQ^ro^glyKyQe^oj%12+/)26+6&yyWyPqlkbq^ilkJlrkq^fkpyyNFAy..20y
QFpe^jre^ibyLyyKyGlokPhvpbbo%12+5)26+.&yyNFAy55/y
>Bko^dbaQerkaboIfw^oapyLyyKyGlokPhvpbbo%12+5)26+.&yyNFAy6-4y
e@^jmQ^ro^glyKyFkkhbbmbo?vri^%12+3)26&yyNFAy..20y
>>KbtLobP^jmibyKyQ^qqbok^`hPqbbiclodb%12+.)24+4&yyNFAy..20y
@Bko^dbaQerkaboIfw^oapyLyyKyHfiiqebQerkaboIfw^oapclo0XQerkaboIfw^oa?illaZ%2-)3-&yyNFAy6-4y
@ObsbkdblcD^kk%M^oq.&yKyHfiiqebat^osbp^q?^biArkHbbm%16)51&clo3sf^iplcXKfqoldiv`bofkZ)3_rkaibplcXTllaMrimZ^ka3p^jmibplcXPlafrjKfqo^qbZyyNFAy513y
QObsbkdblcD^kk%M^oq.&yKyD^kkPqlkbpmfob)m^qoliifkdqebol^a%13)42&%13)5.&yyNFAy513y
>ObsbkdblcD^kk%M^oq/&yKyD^kkPqlkbpmfob)m^qoliifkdqebol^a%13)42&%13)5.&yyNFAy516y
@ObsbkdblcD^kk%M^oq/&yKyRpbXBumilpfsbPqf`hlcD^kkZql_iltrmqebCivfkdJ^`efkb%14)52&yyRy2-/.yyNFAy516y
QObsbkdblcD^kk%M^oq/&yKyD^kkPqlkbpmfob)m^qoliifkdqebol^a%13)42&%13)5.&yyNFAy516y
OQebDob^qIfcqyKyOrkqlQebDob^qIfcq%11+-)6/+-&yyNFAy121/y
Q@^iifkdfkqebObpbosbpyKyDofpeIlkdorkkbo)^iiqebt^vplrqe%11+-)6/+-&yyNFAy255.y
>Jbpp^dbqlCobbtfkaMlpqyKy?o^sbJllkelok%0/+/)//+.&yyNFAy121/yyWyQelrp^kaKbbaibpy
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)

