DugisGuideViewer:RegisterGuide("Ashenvale (26-27)", "Stonetalon Mountains (27)", "Horde", "L", function()
return [[
AAA

CQeb@olppol^apyKyKvpb%12+.)16+/&yyWyQelrp^kaKbbaibpyyNFAy/2y
QObmloqqlH^ao^hyWyQeb?^oobkpyyKyH^ao^h%15+.)2+1&)^qqeb>pebks^ib_loaboyyNFAy321/y
OPmifkqboqobbMlpqyKyCliiltqebol^akloqe)qebkb^pq%40)32&yyNFAy/2y
cPmifkqboqobbMlpqyKySerido^%40+/)3.+3&yyNFAy/2y
ePmifkqboqobbMlpqyKyFkkhbbmboH^vifph%41)3-+4&yyNFAy/2y
>Pqlkbq^ilkPq^kapqfiiyKyJ^pqlhTofibefpp%40+3)3-+-&yyNFAy/2y
>P^qvoElokpyKyMfubi%40+.)3.+2&yyNFAy311.y
>Qeb>pebks^ibErkq%M^oq/&yKyPbk^kfQerkaboeb^oq%40+4)3.+2&yyNFAy3050y
QQeb>pebks^ibErkq%M^oq/&yKyPbk^kfQerkaboeb^oq%40+4)3.+2&yyNFAy3050y
>>pebks^ibLrqorkkbopyKyHro^v$_fk%4.+.)35+/&yyNFAy32-0y

HPe^omq^ilkyIy.30-2yyKyPlrqelcPmifkqboqobbMlpq%41)4.&+Eb$pibsbi0.)plqovirofkdefjqlqebdr^oap^qqebkb^o_vlrqmlpqyyNFAy/y
@>pebks^ibLrqorkkbopyKyHfii6>pebks^ibLrqorkkbopplrqelcPmifkqboqobbMlpq%4-)43&yyNFAy32-0y
Q>pebks^ibLrqorkkbopyKyHro^v$_fk%4.+.)35+/&yyNFAy32-0y

>Qlobh$p>pp^riqyKyQlobh%35)42&yyNFAy3211y
@Qlobh$p>pp^riqyKyBp`loqQlobh)ibqQlobh^kaefp_lavdr^oaaljlpqlcqebcfdeqfkdtebkvlralqefpnrbpq%35)42&yyNFAy3211y
@Pqlkbq^ilkPq^kapqfiiyKyAfpm^q`e./?bclribaT^qboBibjbkq^ip^qJvpqo^iI^hb^kaafp`lsboqebd^wb_llkqebfpi^ka%15+6)36+1&yyNFAy/2y
HQfabobppyIy.31-5yyKyCfkaefjm^qoliifkdqeb_lqqljlcJvpqo^iI^hb^kal``^pflk^iivlkqebfpi^kafkqeb`bkqob%16)36&yyNFAy.6.5y
HRop^kdlrpyIy.30-0yyKyCfkaefjm^qoliifkdqeb^ob^kloqetbpqlcJvpqo^iI^hb)^olrka%1/+.)33+/&yyNFAy/0y
HPe^arj_o^yIy.30-1yyKyCfkaefjm^qoliifkdqeb^ob^_bqtbbkqebm^qeqlt^oap>pqo^k^^o^kaqebm^qeqlt^oapCbitlla%23+.)24+1&%30+.)15+3&yyNFAy/1y
HI^rdefkdPfpqbopyKyKb^oqebO^vkbtllaObqob^q%3.)2.&)illhfkdcloXBq`ebaMef^iZyyIy2534yyNFAy..62y
@QebP^`obaCi^jb%M^oq.&yKyRpbqebXCfiibaBq`ebaMef^iZ^qqebjllktbii%3-+/)4/+6&yyRy2534yyNFAy..62y

EPmifkqboqobbMlpqyRy3615yyNFAy5/1y
QPqlkbq^ilkPq^kapqfiiyKyJ^pqlhTofibefpp%40+3)3-+-&yyNFAy/2y
>Qeb?bclribaBibjbkqyKyQebfqbjX?bclribaT^qboDil_bZpq^oqpnrbpq*aolmmba_vQfabobpp^olrka%16)36&yyRy.31-5yyLyyNFAy.6.5y
QQeb?bclribaBibjbkqyKyJ^pqlhTofibefpp%40+3)3-+-&yyLyyNFAy.6.5y
>Gb$kbrlcqebB^oqebkOfkdyKyJ^pqlhTofibefpp%40+3)3-+-&yyNFAy5/1y
QQlobh$p>pp^riqyKyBoqldO^dbqrph%40+.)3/+2&yyNFAy3211y
>Pe^omq^ilk$p@i^tyKyQebfqbjXPe^omq^ilk$p@i^tZpq^oqpnrbpq*aolmmba_vPe^omq^ilk^olrka%41)4.&yyRy.30-2yyLyyNFAy/y
>Rop^kdlrp$pM^tyKyQebfqbjXRop^kdlrp$pM^tZpq^oqpnrbpq*aolmmba_vRop^kdlrp^olrka%1/)33&yyRy.30-0yyLyyNFAy/0y
>Pe^arj_o^$pEb^ayKyQebfqbjXPe^arj_o^$pEb^aZpq^oqpnrbpq*aolmmba_vPe^arj_o^telm^qolip_bqtbbk%23)24&^ka%30)15&yyRy.30-1yyLyyNFAy/1y
QPe^omq^ilk$p@i^tyKyPbk^kfQerkaboeb^oq%40+5)3.+2&yyLyyNFAy/y
QRop^kdlrp$pM^tyKyPbk^kfQerkaboeb^oq%40+5)3.+2&yyLyyNFAy/0y
QPe^arj_o^$pEb^ayKyPbk^kfQerkaboeb^oq%40+5)3.+2&yyLyyNFAy/1y
>QebErkq@ljmibqbayKyPbk^kfQerkaboeb^oq%40+5)3.+2&yyNFAy/14y
QQebErkq@ljmibqbayKyPbk^kfQerkaboeb^oq%40+5)3.+2&yyNFAy/14y

OQebWlo^jPqo^kayKyCliiltqebj^fkol^atbpq^pc^o^pvlr`^k)qebk_ob^hlcc^kaorkqlqeb`l^pq%.0)0.&+Alk$qdbqqll`ilpbqlqeb^iivqltkpyyNFAy331.y
cQebWlo^jPqo^kayKy>kaorh%./+/)00+6&yyNFAy331.y
QGb$kbrlcqebB^oqebkOfkdyKyGb$kbrP^k`ob^%..+3)01+0&yyNFAy5/1y
>Slope^qebI^peboyKyJrdi^pe%./+-)01+3&yyNFAy331.y
>K^d^^qqebWlo^jPqo^kayKyJ^orh^f%..+4)01+5&yyNFAy311/y
@Slope^qebI^peboyKyCliiltJrdi^pe^kaabcb^qSlope^lkqebfpi^ka%6+3)/4+4&yyNFAy331.y
@K^d^^qqebWlo^jPqo^kayKyHfiiqebK^d^pcloqeb/-XTo^qeq^fiEb^apZ%.-)/5&yyNFAy311/y
QK^d^^qqebWlo^jPqo^kayKyJ^orh^f%..+4)01+5&yyNFAy311/y
QSlope^qebI^peboyKyT^oplkdOrkkbo%./+/)01+/&yyNFAy331.y
>?bqtbbk^Ol`h^ka^QefpqibcroyKyH^o^kd>j^hh^o%..+6)01+2&yyNFAy/.3y
>Qolii@e^ojyKyJfqprt^%..+4)01+5&yyNFAy313/y

@?bqtbbk^Ol`h^ka^QefpqibcroyKyHfii5Qefpqibcro>sbkdbop^ka5QefpqibcroPe^j^k^qqebQefpqibcro`^jmtbpqlc>pqo^k^^o%0.+.)12+0&yyNFAy/.3y
@Qolii@e^ojyKyD^qebo5XQolii@e^ojpZfkqeb`^sb^qqeb_^`hlcqebQefpqibcro`^jm%05)0-&yyNFAy313/y
>CobbaljqlOrriyKyOrriPkltellc%1.+2)01+3&yyNFAy315/y
@CobbaljqlOrriyKyBp`loqOrri)phfmfcfq$pqle^oa%1.+2)01+3&yyNFAy315/y
Q?bqtbbk^Ol`h^ka^QefpqibcroyKyH^o^kd>j^hh^o%..+6)01+2&yyNFAy/.3y
QQolii@e^ojyKyJfqprt^%..+4)01+5&yyNFAy313/y

EPmifkqboqobbMlpqyRy3615yyNFAy6201y

QCobbaljqlOrriyKyV^j^Pkltellc%41+.)3-+6&yyNFAy315/y
>AbpqolvqebIbdflkyKyS^irpe^%40+0)3-+2&yyNFAy6201y
@Loa^krpyKyCfdeqqlqebqlmlcqebqltbo%3/)2.&^kahfiiLoa^krp)qebkillqqebeb^a^kagrjmlrqlcqebobyyNFAy.-55y
@P^qvoElokpyKy@liib`q.3XP^qvoElokpZcoljqebP^qvop%5-)2/&yyNFAy311.y
@AbpqolvqebIbdflkyKyPi^v3J^kklol`I^pebop)3Cbidr^oap^ka3Pb^ofkdFkcbok^ip%5/)36&+T^q`eclofqbjaolmXAf^_lif`^iMi^kpZqlpq^oqkbuqnrbpqyyNFAy6201y

QP^qvoElokpyKyMfubi%40+.)3.+2&yyNFAy311.y
QAbpqolvqebIbdflkyKyS^irpe^%40+0)3-+2&yyNFAy6201y
>Af^_lif`^iMi^kpyKyQebfqbjXAf^_lif`^iMi^kpZpq^oqpnrbpq*aolmmba_vI^pebop)Cbidr^oap^kaFkcbok^ip^olrka%5/)36&yyRy/0464yyLyyNFAy6202y
QAf^_lif`^iMi^kpyLyyKyS^irpe^%40+0)3-+2&yyNFAy6202y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)

