DugisGuideViewer:RegisterGuide("Thousand Needles (27-29)", "Hillsbrad Foothills (29-30)", "Horde", "L", function()
return [[
AAA

CQelrp^kaKbbaibpyKyKvpb%12+.)16+.&yyWy>pebks^ibyyNFAy..64y
eCobbtfkaMlpqyKyFkkhbbmbo>_bnt^%13+.)2.+2&yyNFAy..64y
QQebP^`obaCi^jb%M^oq/&yKyO^r@ifccorkkbo%13+.)2.+3&yyNFAy..63y
>QebP^`obaCi^jb%M^oq0&yKyO^r@ifccorkkbo%13+.)2.+3&yyNFAy..64y
>>Afccbobkq>mmol^`eyKyJ^dfpqofuBilp^f%13+/)2-+1&yyNFAy610.y

@QebP^`obaCi^jb%M^oq0&yKyDlfkqlqeb`^sb%11)04&^ka`e^odbqeb_o^wfbo%1/)0.+2&yyNFAy..64y

>Evmbo`^m^`fqloDfwjlyKyTfwil?b^ofkdpefkbo%/.+2)0.+2&yyNFAy2.2.y
QPbombkqTfiayKyJlqbd^Cfobj^kb%/.+3)0/+0&yyNFAy1532y
>P^`obaCfobyKyJlqbd^Cfobj^kb%/.+3)0/+0&yyNFAy2-3/y

@P^`obaCfobyKyD^qebo.-_rpebiplcXFk`bkaf^>d^sbZ^qQeb?lfifkdMlli%02)03&yyNFAy2-3/y
@TfkaOfaboyKyD^qebo.-XEfdembo`eTvsbokBddpZ^olrka%..)03&yyNFAy1434y
>Eljbt^oa?lrkayKyM^l$h^Ptfcqjlrkq^fk)bp`loqpq^oqp^q%.5+-)1-+2&yyNFAy144-y
@Eljbt^oa?lrkayKyBp`loqM^l$h^yyNFAy144-y
@Pqbbipk^myKyHfiiPqbbipk^m^kaillqXPqbbipk^m$pOf_Z+Ebjlsbp^olrka%.3)/2&yyNFAy..0.y
@>Afccbobkq>mmol^`eyKyD^qebo/e^kacriplcXMrofcvfkdB^oqeZcoljQerkabofkd?lriabohfk%./).4&yyNFAy610.y

ECobbtfkaMlpqyRy3615yyNFAy..03y
CQerkabo?irccyKyKvpb%12+.)16+/&yyNFAy..03y
QPqbbipk^myWyQerkabo?irccyyKyJbiloPqlkbellc)Erkqbo$pOfpb%3.+1)5-+2&yyNFAy..0.y
>Colpqj^tyWyQerkabo?irccyyKyJbiloPqlkbellc)Erkqbo$pOfpb%3.+1)5-+2&yyNFAy..03y
QP^`obaCfobyWyQerkabo?irccyyKyJ^d^qe^Dofjqlqbj)BiaboOfpb%4-+.)0-+5&yyNFAy2-3/y
>>ofh^o^yWyQerkabo?irccyyKyJ^d^qe^Dofjqlqbj)BiaboOfpb%4-+.)0-+5&yyNFAy2-55y

CCobbtfkaMlpqyKyQ^i%13+5)2-+/&yyWyQerkabo?irccyyNFAy16-1y
QQebP^`obaCi^jb%M^oq0&yKyO^r@ifccorkkbo%13+.)2.+3&yyNFAy..64y
QTfkaOfaboyKyBir%11+6)16+-&yyNFAy1434y

@DofjqlqbjPmvfkdyKyQ^hbqebm^qerm%0.)03&^kaqebkq^hbqebklqbpcoljqeb_lubp+XPb`obqKlqb .Z^q%0.)0/&+XPb`obqKlqb /Z^q%00)06&+XPb`obqKlqb 0Z^q%06)1.&yyNFAy2-31y
@>ofh^o^yKyHfii>ofh^o^%04)02&yyNFAy2-55y
@T^kqba*>ok^hDofjqlqbjyKyHfii>ok^hDofjqlqbjqlqebkloqe)lkqebbadblcqebwlkb%05)/4&yyNFAy2.14y
>Cobb^qI^pqyKyI^hlq^Tfkaplkd%05+-)/3+2&yyNFAy16-1y
@Cobb^qI^pqyKyBp`loqI^hlq^yyNFAy16-1y

Q>ofh^o^yKyJlqbd^Cfobj^kb%/.+3)0/+0&yyNFAy2-55y
QEljbt^oa?lrkayKyJlqbd^Cfobj^kb%/.+3)0/+0&yyNFAy144-y
Q>Afccbobkq>mmol^`eyKyTfwil?b^ofkdpefkbo%/.+2)0/+2&yyNFAy610.y
>>AfmfkqebJllktbiiyKyTfwil?b^ofkdpefkbo%/.+2)0/+2&yyNFAy6100y

@>AfmfkqebJllktbiiyKy>`qfs^qbqebXOl_lqolk@lkqoliRkfqZlkqebtbpqbadblcqebwlkbkb^oQe^i^k^^o%6).5&yyNFAy6100yyRy/0342y
@Evmbo`^m^`fqloDfwjlyKyCfkaqeb`^db^qqebtob`hba`^o^s^kkloqelcTefqbob^`eMlpq^karpbqebXM^kqebo@^dbHbvZqllmbkfq+Pi^vqebm^kqebo^kaq^hbqebXEvmbo`^m^`fqloDfwjlZ%//)/1&yyNFAy2.2.yyRy./61/y
HD^i^hJbppbkdboyKyCfka^kahfiiqebm^qolifkdD^i^hJbppbkdbo%05+3)0.+2&)%/6+2)01+3&)%.5+6)/4+.&qlpq^oqkbtnrbpqyyIy./231yyNFAy155.y

>>pp^ppfk^qflkMilqyKyRpbX>pp^ppfk^qflkKlqbZql_bdfknrbpqyyRy./231yyNFAy155.y
Q>pp^ppfk^qflkMilqyKyH^k^qfDobv`ilra%/.+0)0/+-&yyNFAy155.y
QEvmbo`^m^`fqloDfwjlyKyTfwil?b^ofkdpefkbo%/.+2)0.+2&yyNFAy2.2.y
Q>AfmfkqebJllktbiiyKyTfwil?b^ofkdpefkbo%/.+2)0.+2&yyNFAy6100y
>QbpqfkdqebQlkf`yKyTfwil?b^ofkdpefkbo%/.+2)0.+2&yyNFAy6101y
>Molqb`qH^k^qfDobv`ilrayKyH^k^qfDobv`ilra%/.+0)0/+-&yyNFAy1633y
@Molqb`qH^k^qfDobv`ilrayKyMolqb`qH^k^qfDobv`ilracoljqeb`bkq^ro^qq^`h%/.)0/&yyNFAy1633y
QMolqb`qH^k^qfDobv`ilrayKyH^k^qfDobv`ilra%/.+0)0/+-&yyNFAy1633y

ECobbtfkaMlpqyRy3615y
QCobb^qI^pqyKyQe^if^>j_boefab%13+-)2.+2&yyNFAy16-1y
QT^kqba*>ok^hDofjqlqbjyKy@ifcct^q`eboIlkdelok%12+4)2-+4&yyNFAy2.14y
QDofjqlqbjPmvfkdyKy@ifcct^q`eboIlkdelok%12+4)2-+4&yyNFAy2-31y
QQbpqfkdqebQlkf`yKyJ^dfpqofuBilp^f%13+/)2-+1&yyNFAy6101y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
