DugisGuideViewer:RegisterGuide("Stonetalon Mountains (27)", "Thousand Needles (27-29)", "Horde", "L", function()
return [[
AAA

CPrkOl`hObqob^qyKySerido^%40+/)3.+3&yyWy>pebks^ibyyNFAy3/50y
QLoa^krpyKy?o^bivkCfobe^ka%13+-)3-+1&yyNFAy.-55y
ePrkOl`hObqob^qyKyFkkhbbmboG^vh^%14+2)3/+.&yyNFAy3/50y
>?illacrov?illaifkbyKyJ^ddo^kB^oqe_fkabo%14+/)3.+.&yyNFAy3/50y

@?illacrov?illaifkbyKyHfii?illacrovOfmmbo%0-)30&^kadbqX?illacrovOfmmbo$pObj^fkpZyyNFAy3/50y

EPrkOl`hObqob^qyRy3615yyNFAy..63y
Q?illacrov?illaifkbyKyJ^ddo^kB^oqe_fkabo%14+/)3.+.&yyNFAy3/50y

CQerkabo?irccyKyQe^oj%12+/)26+6&yyNFAy..63y
QQebP^`obaCi^jb%M^oq.&yWyQerkabo?irccyyKyW^kdbkPqlkbellc%21+3)2.+2&yyNFAy..62y
>QebP^`obaCi^jb%M^oq/&yWyQerkabo?irccyyKyW^kdbkPqlkbellc%21+3)2.+2&yyNFAy..63y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)

