DugisGuideViewer:RegisterGuide("Hillsbrad Foothills (29-30)", "Arathi Highlands (30)", "Horde", "L", function()
return [[
AAA

CLodofjj^oyKyCivqlLodofjj^oyyNFAy.03.y
eLodofjj^oyKyFkkhbbmboDovpeh^%21+.)35+3&yyWyLodofjj^oyyNFAy.03.y

CQfofpc^iDi^abpyKyQ^hbqebwbmmbifklrqpfabLodofjj^o%2-+5).0+4&qlQfofpc^iDi^abp%Rkabo`fqv&yyWyArolq^oyyNFAy.03.y

ORkabo`fqvyKyOrkqlRkabo`fqv%3.+6)35+.&yyWyQfofpc^iDi^abpyyNFAy.03.y
cRkabo`fqvyOyLo`)Qolii)Q^robkyyKyJf`e^biD^oobqq%30+2)15+4&yyWyRkabo`fqvyyNFAy.03.y

OQfofpc^iDi^abpyKyBufqqeolrdeqebpbtbop%.2+/)0/+1&yyWyRkabo`fqvyyNFAy.03.y

OPfisbomfkbClobpqyKyOrkqlPfisbomfkbClobpq%2-)46+0&yyWyQfofpc^iDi^abpyyNFAy160y
>GlrokbvqlEfiip_o^aCllqefiipyKy>mlqeb`^ovObkcboobi%1/+6)1-+6&yyWyPfisbomfkbClobpqyyNFAy160y
OEfiip_o^aCllqefiipyKyOrkaltkqeolrdePfisbomfkbqebkb^pqqlEfiip_o^aCllqefiip%4.+0)5-+2&yyWyPfisbomfkbClobpqyyNFAy161y
>QfjbQlPqofhbyKyAb^qepq^ihboIbpe^qqebPlrqemlfkqQltbo%/-+5)14+1&yyNFAy161yyKLAB?RDy

OQ^oobkJfiiyKyOrkqlQ^oobkJfii%3/+0)/-+0&yyNFAy.03.y
QQfjbQlPqofhbyKyEfdeBub`rqloA^oqe^if^%3/+0)/-+0&yyNFAy161yyKLAB?RDy
QGlrokbvqlEfiip_o^aCllqefiipyKy>mlqeb`^ovIvalk%3.+2).6+/&yyNFAy160y
cQ^oobkJfiiyKyW^ofpb%3-+/).5+4&yyNFAy.03.y
>Obdqe^oAb^qed^qbyKyHorph%30+/)/-+4&yyNFAy.03.y
>QebE^jjboJ^vC^iiyKyQ^iilt%3.+6).6+4&yyNFAy343y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
