DugisGuideViewer:RegisterGuide("Stranglethorn Vale (30-31)", "Thousand Needles (31-32)", "Horde", "L", function()
return [[
AAA

ELodofjj^oyRy3615yyNFAy250y
CDolj$dli?^pb@^jmyKyEb^oqeqlLodofjj^o^kaofabwbmmbifkqlDolj$Dli%2-+3)./+3&yyWyArolq^oyyNFAy250y
cDolj$dli?^pb@^jmyKyQevpq^%0/+2)/6+0&yyNFAy250y

OKbpfkdt^ov$pBumbafqflkyKyCliiltqebol^akloqe)illhclo^ifqqib`^jm_vqebofsbo%02).-&yyNFAy250y
>Tbi`ljbqlqebGrkdibyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy250y
QTbi`ljbqlqebGrkdibyKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy250y

>QfdboJ^pqbov%M^oq.&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.52y
>M^kqeboJ^pqbov%M^oq.&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6-y
>O^mqloJ^pqbov%M^oq.&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.61y

@QfdboJ^pqbov%M^oq.&yKyHfii.-VlrkdPqo^kdibqelokQfdboppifdeqivqlqebb^pq%02).1&yyNFAy.52y
@M^kqeboJ^pqbov%M^oq.&yKyHfii.-VlrkdM^kqebopqlqebkloqe%1.)6&yyNFAy.6-y

QM^kqeboJ^pqbov%M^oq.&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6-y
>M^kqeboJ^pqbov%M^oq/&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6.y

QQfdboJ^pqbov%M^oq.&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.52y
>QfdboJ^pqbov%M^oq/&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.53y

@M^kqeboJ^pqbov%M^oq/&yKyHfii.-M^kqebopb^pqlcqeb`^jm%/6)..&yyNFAy.6.y
@QfdboJ^pqbov%M^oq/&yKyHfii.-Qfdbopb^pqlcqeb`^jm%0-).2&yyNFAy.53y
@O^mqloJ^pqbov%M^oq.&yKyHfii.-Pqo^kdibqelokO^mqlopb^pqkb^oqeborfkp%/5).1&yyNFAy.61y

QO^mqloJ^pqbov%M^oq.&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.61y
>O^mqloJ^pqbov%M^oq/&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.62y

QM^kqeboJ^pqbov%M^oq/&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6.y
>M^kqeboJ^pqbov%M^oq0&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6/y

QQfdboJ^pqbov%M^oq/&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.53y
>QfdboJ^pqbov%M^oq0&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.54y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
