DugisGuideViewer:RegisterGuide("Arathi Highlands (30)", "Stranglethorn Vale (30-31)", "Horde", "L", function()
return [[
AAA

O>o^qefEfdei^kapyKyOrkql>o^qefEfdei^kap%53+0)26+5&yyWyEfiip_o^aCllqefiipyyNFAy322y
OE^jjboc^iiyKyOrkqlE^jjboc^iiKloqeb^pq`lokbolcwlkb%40)03&yyNFAy322y
>E^jjboc^iiyKyDlo$jri%4/+4)01+-&yyNFAy322y
QE^jjboc^iiyKyQlo$d^k%41+4)03+0&yyNFAy322y
>O^fpfkdPmfofqp%M^oq.&yKyQlo$d^k%41+4)03+0&yyNFAy34/y
cE^jjboc^iiyKyRoa^%40+.)0/+4&yyNFAy341y

@O^fpfkdPmfofqp%M^oq.&yKy>`nrfob.-XEfdei^kaO^mqloBvbpZtbpqlcE^jjboc^ii%31)04&yyNFAy34/y

QO^fpfkdPmfofqp%M^oq.&yKyQlo$d^k%41+4)03+0&yyNFAy34/y
>O^fpfkdPmfofqp%M^oq/&yKyQlo$d^k%41+4)03+0&yyNFAy341y
QO^fpfkdPmfofqp%M^oq/&yKyDlo$jri%4/+4)01+-&yyNFAy341y
>O^fpfkdPmfofqp%M^oq0&yKyDlo$jri%4/+4)01+-&yyNFAy342y
QO^fpfkdPmfofqp%M^oq0&yKyQlo$d^k%41+4)03+0&+Phfmqebcliilt*rmyyNFAy342y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
