DugisGuideViewer:RegisterGuide("Thousand Needles (31-32)", "Desolace (32-34)", "Horde", "L", function()
return [[
AAA

ELodofjj^oyRy3615yyNFAy..12y
CQeb@olppol^apyKyAlo^p%12+0)31&yyWyLodofjj^oyyNFAy..12y
>QebPt^ojDoltp%M^oq.&yWyQeb?^oobkpyyKyHloo^k)tbpqlcqebtfkaofabo%2.+.)/6+3&yyNFAy..12y
QObdqe^oAb^qed^qbyWyQeb?^oobkpyyKyObdqe^oAb^qed^qb)tbpqlcqeb@olppol^ap%12+0)/5+1&yyNFAy.03.y
>QebHlih^olcAbpli^`byWyQeb?^oobkpyyKyObdqe^oAb^qed^qb)tbpqlcqeb@olppol^ap%12+0)/5+1&yyNFAy.03/y

CCobbtfkaMlpqyKyAbso^h%2.+2)0-+0&yyWyQeb?^oobkpyyNFAy243/y
OPefjjbofkdCi^qpyKyOrkb^pqqlqebPefjjbofkdCi^qp%44+5)44+/&yyNFAy243/y
>EbjbqKbpfkdt^ovGo+yKyHo^sbiHl^i_b^oa%44+5)44+/&yyNFAy243/y
>Te^ocj^pqboAfwwvtfdyKyHo^sbiHl^i_b^oa%44+5)44+/&yyNFAy....y
>>?rjmfkqebOl^ayKyQo^`hj^pqboWebofk%5.+3)44+6&yyNFAy..42y
>E^oabkbaPebiipyKyTfwwib?o^pp_liqp%45+.)44+.&yyNFAy..-2y
>Il^aIfdeqbkfkdyKyMlwwfh%5-+.)42+6&yyNFAy..43y
>Ol`hbq@^oM^oqpyKyHo^sbiHl^i_b^oa%44+5)44+/&yyNFAy...-y
>P^iqCi^qSbkljyKyCfwwib?o^pp_liqp%45+.)44+-&yyNFAy..-1y

@>?rjmfkqebOl^ayKyHfii.-P^iqpqlkb?^pfifphp).-P^iqpqlkb@ovpq^iefabp^ka3P^iqpqlkbD^wbop^olrka%43)54&^ka%40)26&yyNFAy..42y
@E^oabkbaPebiipyKyHfiiqebQroqibpfkQelrp^kaKbbaibpclo6XE^oabkbaQloqlfpbPebiipZ^olrka%5/)21&yyNFAy..-2y
@Il^aIfdeqbkfkdyKyHfiisriqrobpclo.-XEliiltSriqrob?lkbpZ^olrka%54)33&yyNFAy..43y
@Ol`hbq@^oM^oqpyKyD^qeboqebXOl`hbq@^oM^oqpZqeolrdelrqqebPefjjbofkdCi^qp%55)42&yyNFAy...-y
@P^iqCi^qSbkljyKyHfiiP`lomflkpfkqebPefjjbofkdCi^qpclo3XP^iqvP`lomfaSbkljpZ^olrka%4/)42&yyNFAy..-1y

Q>?rjmfkqebOl^ayKyQo^`hj^pqboWebofk%5.+3)44+6&yyNFAy..42y
QE^oabkbaPebiipyKyTfwwib?o^pp_liqp%45+.)44+.&yyNFAy..-2y
QIl^aIfdeqbkfkdyKyMlwwfh%5-+.)42+6&yyNFAy..43y
>Dl_ifkPmlkplopefm%M^oq.&yKyMlwwfh%5-+.)42+6&yyNFAy..45y
QOl`hbq@^oM^oqpyKyHo^sbiHl^i_b^oa%44+5)44+/&yyNFAy...-y
QP^iqCi^qSbkljyKyCfwwib?o^pp_liqp%45+.)44+-&+Phfmqebcliilt*rmyyNFAy..-1y
>J^oqbhqebBufibayKyCfwwib?o^pp_liqp%45+.)44+-&yyNFAy..-3y
>Bk`orpqbaQ^fiCfkpyKyTfwwib?o^pp_liqp%45+.)44+.&yyNFAy..-4y

OD^adbqw^kyKyOrkPlrqeqlD^adbqw^k%2.+3)/2+2&yyWyQ^k^ofpy
cD^adbqw^kyKy?rihobhO^dbcfpq%2.+3)/2+2&yyWyQ^k^ofpy
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
