DugisGuideViewer:RegisterGuide("Desolace (32-34)", "Stranglethorn Vale (34-36)", "Horde", "L", function()
return [[
AAA

ELodofjj^oyRy3615yyNFAy..13y
QQebPt^ojDoltp%M^oq.&yWyLodofjj^oyyKy?bidoljOl`hj^ri)S^iibvlcElklo%42)01&yyNFAy..12y
>QebPt^ojDoltp%M^oq/&yWyLodofjj^oyyKy?bidoljOl`hj^ri%42)01&yyNFAy..13y
>>iif^k`bObi^qflkp%M^oq.&yWyLodofjj^oyyKy@o^sbkAolh)@ibcqlcPe^alt%2-)14&yyNFAy.10.y
Q>iif^k`bObi^qflkp%M^oq.&yWyLodofjj^oyyKyHbiao^k)tbpqd^qblcLodfjj^o%//)21&yyNFAy.10.y
>>iif^k`bObi^qflkp%M^oq/&yWyLodofjj^oyyKyHbiao^k)tbpqd^qblcLodfjj^o%//)21&yyNFAy.10/y

CPrkOl`hObqob^qyKyAlo^p%12+0)31&yyWyLodofjj^oyyNFAy.15-y
OAbpli^`byKyOrkplrqeqeolrdeQeb@e^oobaS^ibqlAbpli^`b%/4+/)52+5&yyWyPqlkbq^ilkJlrkq^fkpyyNFAy.15-y

OQerkabo>ubCloqobppyKyTbpqlcqebol^a%22)/1&yyNFAy.15-y
HHfii?rokfkd?i^abpyKyHfiiqeb?rokfkd?i^abKM@rkqfivlrcfkaXCi^vbaAbjlkPhfkZ%23+/)/5+.&yyIy/-0.-yyNFAy.15-y
>Qeb@loormqbo%M^oq.&yKyRpbXCi^vbaAbjlkPhfkZql_bdfknrbpqyyRy/-0.-yyNFAy.15-y
>HlalOlrkarmyKyPjbbaP`o^__ibp`obt%3-+5)3.+6&yyNFAy223.y

ODelpqT^ihboMlpqyKyCliiltqebol^akloqetbpqcoljP`o^__ibp`obt$perq%23)26&yyNFAy.032y
QQebHlih^olcAbpli^`byKyCbidroQtl`rqp%23+/)26+2&yyNFAy.03/y
>He^kAbw$ebm^eyKyCbidroQtl`rqp%23+/)26+2&yyNFAy.032y
>Dbihfp>iif^k`byKyDroa^Tfiaj^kb%23+0)26+3&+PhfmJ^do^j>iif^k`byyNFAy.035y
Q>iif^k`bObi^qflkp%M^oq/&yKyQ^h^q^Pqbbi_i^ab%2/+3)21+0&yyNFAy.10/y
>>iif^k`bObi^qflkp%M^oq0&yKyQ^h^q^Pqbbi_i^ab%2/+3)21+0&yyNFAy.100y
>?bclriba_vP^qvoyKyQ^h^q^Pqbbi_i^ab%2/+3)21+0&yyNFAy.101y
QQeb@loormqbo%M^oq.&yKyJ^rofk?lkbpmifqqbo%2/+2)20+2&yyNFAy.15-y
>Qeb@loormqbo%M^oq/&yKyJ^rofk?lkbpmifqqbo%2/+2)20+2&yyNFAy.15.y
Q>iif^k`bObi^qflkp%M^oq0&yKyJ^rofk?lkbpmifqqbo%2/+2)20+2&yyNFAy.100y
>Qeb?rokfkdlcPmfofqpyKyJ^rofk?lkbpmifqqbo%2/+2)20+2&yyNFAy.102y

@?bclriba_vP^qvoyKyPi^v4E^qbcrovOldrbp)4E^qbcrovCbiptlok)4E^qbcrov?bqo^vbop)^ka4E^qbcrovEbii`^iibop^qPbodbolk%42)//&yyNFAy.101y
@Qeb@loormqbo%M^oq/&yKyXPe^altpq^ihboP`^imZfpl_q^fkbacolj^E^qbcrovPe^altpq^ihbo%4.)/-&yyNFAy.15.y
@He^kAbw$ebm^eyKyHfiiHe^kAbw$ebm^efkqebJ^do^jsfii^db%40)15&yyNFAy.032y
@Dbihfp>iif^k`byKyHfiiJ^do^j`bkq^roprkqfivlrd^fkDbihfp%Cofbkaiv&%40+2)40+2&yyNFAy.035y
@HlalOlrkarmyKyRpbqebXHlalHlj_l_ri^qloZlkqebHlalpfkqebDo^sbv^oa%2.)26&^kaqebkbp`loqqebjqlPjbbaP`o^__ibp`obt%3-+5)3.+6&yyRy.056/yyNFAy223.y
QHlalOlrkarmyKyPjbbaP`o^__ibp`obt%3-+5)3.+6&yyNFAy223.y

QHe^kAbw$ebm^eyKyCbidroQtl`rqp%23+/)26+2&yyNFAy.032y
>@bkq^ro?lrkqvyKyCbidroQtl`rqp%23+/)26+2&yyNFAy.033y
Q?bclriba_vP^qvoyKyQ^h^q^Pqbbi_i^ab%2/+3)21+0&yyNFAy.101y
QQeb@loormqbo%M^oq/&yKyJ^rofk?lkbpmifqqbo%2/+2)20+2&yyNFAy.15.y
>Qeb@loormqbo%M^oq0&yKyJ^rofk?lkbpmifqqbo%2/+2)20+2&yyNFAy.15/y
QDbihfp>iif^k`byKyRqebhqebTfpb%03+0)46+/&yyNFAy.035y
>Pqb^ifkdPrmmifbpyKyRqebhqebTfpb%03+0)46+/&yyNFAy.04-y

OPe^altmobvSfii^dbyKyCliiltqebol^atbpq)altklkqebpelob%/1)4.&yyNFAy2430y
>ErkqfkdfkPqo^kdibqelokyKyOllkTfiaj^kb%/2+.)4/+0&yyNFAy2430y
>E^kalcForulpyKyQ^fd^Tfpbj^kb%/2+5)35+/&yyNFAy205.y
ePe^altmobvSfii^dbyKyFkkhbbmboPfhbt^%/1+.)35+/&yyNFAy3.10y
>LqeboCfpeqlCovyKyAoriwbd^oPho^dellh%/0+0)4/+5&yyNFAy3.10y
>@i^j?^fqyKyJ^f$I^eff%//+4)4/+.&yyNFAy3.1/y
cPe^altmobvSfii^dbyKyQe^ilk%/.+3)41&yyNFAy241.y

K@liib`q@i^jJb^q^pvlrqo^sbiyKyQo^sbikloqefkqebt^qbo`liib`qfkd.-XPlcq*pebiiba@i^jJb^qZcoljqeb`i^jplkqeb_lqqljyyIy.26/1.-yyNFAy3.1/y
>P`bmqoblcIfdeqyKy>wlob>ia^jloq)lkqebefii%05+6)/4+.&yyNFAy241.y

@Qeb?rokfkdlcPmfofqpyKyRpbqebX?rokfkdDbjZlkqeberj^klfap^cqbovlra^j^dbqebjfkqebQerkabo>ubCloqobpp%21)/6&yyRy3103yyNFAy.102y
@P`bmqoblcIfdeqyKyDlqlqebcfopqt^q`eqltbolkqebibcqrmlkbkqbofkdQerkabo>ubCloqobpp+Tlohvlrot^vrm)hfiiqeb?rokfkd?i^abPbbo%22+/)0-+.&^kaq^hbqebXP`bmqoblcIfdeqZyyNFAy241.y
@E^kalcForulpyKyEb^afkqlqeb_fddbpq_rfiafkd%23)/6&fkQerkabo>ubCloqobpp+@ib^oqebj^fkollj)rpbqebXAbjlkMf`hZlkqeb@ovpq^ifkqeb`bkqbolcqebollj)pi^vqebabjlkqe^q^mmb^op^kaillqqeb_luyyRy.12/0yyNFAy205.y

QP`bmqoblcIfdeqyKy>wlob>ia^jloq)lkqebefii%05+6)/4+.&yyNFAy241.y
>?llhlcqeb>k`fbkqpyKy>wlob>ia^jloq%05+6)/4+.&yyNFAy3-/4y
>@i^fjO^`hjlob$pQob^probyKyO^`hjlob$pIld%03+.)0-+2&)clrka^ilkdqebpelobyyNFAy3.3.y

@LqeboCfpeqlCovyKyPi^v4Pifqebo_i^abJvojfalk)4Pifqebo_i^abK^d^)^ka2Pifqebo_i^abPlo`bobppbp%0/)/1&yyNFAy3.10y
@@i^j?^fqyKyCfka.-mfb`bplcXPlcq*pebiiba@i^jJb^qZrkabot^qbo%02)/2&yyNFAy3.1/y
@Qeb@loormqbo%M^oq0&yKy@liib`q^kXLo^`ib@ovpq^iZcolj^Pifqebo_i^abLo^`ib%00)//&yyNFAy.15/y
@@i^fjO^`hjlob$pQob^probyKyHfiiAovpk^mMfk`bop^ka@o^tibop%0/)0-&cloqebXO^`hjlob$pPfisboHbvZ+HfiiPifqebo_i^abK^d^%0/)//&cloqebXO^`hjlob$pDliabkHbvZyyNFAy3.3.y

Q@i^fjO^`hjlob$pQob^probyKyO^`hjlob$p@ebpq%0-+-)5+4&)_befka^qobblkO^k^wg^oFpibyyNFAy3.3.y
@?llhlcqeb>k`fbkqpyKy@ib^oqeb^ob^^olrkaqebpq^qrb)qebkq^ihqlfq^kahfiiqebk^d^qe^qpm^tkp^kaillqqeb_llh%/5)4&yyNFAy3-/4y
Q?llhlcqeb>k`fbkqpyKy>wlob>ia^jloq)lkqebefii%05+6)/4+.&yyNFAy3-/4y

>?lkb@liib`qloyKy?f__ivC$rqw_r`hib^qHlojbh$pErq%3/+-06+-&yyNFAy22-.y

QQeb?rokfkdlcPmfofqpyKyJ^rofk?lkbpmifqqbo%2/+2)20+2&yyNFAy.102y
>>iif^k`bObi^qflkp%M^oq1&yKyQ^h^q^Pqbbi_i^ab%2/+3)21+0&yyNFAy.103y
QQeb@loormqbo%M^oq0&yKyJ^rofk?lkbpmifqqbo%2/+2)20+2&yyNFAy.15/y
>Qeb@loormqbo%M^oq1&yKyJ^rofk?lkbpmifqqbo%2/+2)20+2&yyNFAy.151y
QQeb@loormqbo%M^oq1&yKyQ^h^q^Pqbbi_i^ab%2/+3)21+0&+Phfmi^pqcliilt*rmyyNFAy.151y

@?lkb@liib`qloyKyHfiiHlalpfkqebHlalDo^sbv^oa%23)25&clo.-XHlal?lkbpZyyNFAy22-.y
@Pqb^ifkdPrmmifbpyKyD^qebo3_^dplcX@orabivAofbaJb^qZfkqebJ^do^jsfii^db%33+2)5-+2&)%36+/)44+/&)%40+3)41+1&yyNFAy.04-y
@@bkq^ro?lrkqvyKyHfiiqeb@bkq^ropfkqebJ^do^jSfii^dbclo.2X@bkq^roB^opZ^olrka%4-)41&yyNFAy.033y

Q@bkq^ro?lrkqvyKyCbidroQtl`rqp%23+/)26+2&yyNFAy.033y
Q?lkb@liib`qloyKy?f__ivC$rqw_r`hib^qHlojbh$pErq%3/)05&yyNFAy22-.y

EPe^altmobvSfii^dbyRy3615yyNFAy./35y
QE^kalcForulpyKyQ^fd^Tfpbj^kb%/2+5)35+/&yyNFAy205.y
QLqeboCfpeqlCovyKyAoriwbd^oPho^dellh%/0+0)4/+5&yyNFAy3.10y
Q@i^j?^fqyKyJ^f$I^eff%//+4)4/+.&yyNFAy3.1/y
QPqb^ifkdPrmmifbpyKyRqebhqebTfpb%03+0)46+/&^qqebDbihfpsfii^db+Phfmqebcliilt*rmyyNFAy.04-y

C@^jmQ^ro^glyKyQe^ilk%/.+3)41&yyNFAy./35y
OArpqt^iiltJ^opeyKyOrkb^pqqlArpqt^iiltJ^ope%/6+4)14+4&yyWyArpqt^iiltJ^opeyyNFAy./35y

>Prpmf`flrpEllcmofkqpyWyArpqt^iiltJ^opeyyKy@if`hlkellcmofkqplrqpfabqebfkklkqebdolrka%/6+4)14+4&yyNFAy./35y
>Ifbrqbk^kqM^s^iObbqebyWyArpqt^iiltJ^opeyyKyQebo^jlobDr^oa?^adb%/6+5)15+/&+I^vfkdlkqebmi^khplkqebdolrkayyNFAy./36y
>Qeb?i^`hPefbia%M^oq.&yWyArpqt^iiltJ^opeyyKy?i^`hPefbia%/6+5)15+.&)e^kdp^_lsbqebcfobmi^`byyNFAy./2.y

O?o^`hbkt^iiSfii^dbyWyArpqt^iiltJ^opeyyKyKloqe^ilkdqebol^a%02)/6&yyNFAy.0/.y
QPrpmf`flrpEllcmofkqpyWyArpqt^iiltJ^opeyyKyHold%03+0)0.+5&yyNFAy./35y
QIfbrqbk^kqM^s^iObbqebyWyArpqt^iiltJ^opeyyKyHold%03+0)0.+5&yyNFAy./36y
QQeb?i^`hPefbia%M^oq.&yWyArpqt^iiltJ^opeyyKyHold%03+0)0.+5&yyNFAy./2.y
>Qeb?i^`hPefbia%M^oq/&yWyArpqt^iiltJ^opeyyKyHold%03+0)0.+5&yyNFAy.0/.y
QQeb?i^`hPefbia%M^oq/&yWyArpqt^iiltJ^opeyyKyAl$dli%03+2)0-+6&+Phfmqebcliilt*rmyyNFAy.0/.y

CO^q`ebqyKyPe^oaf%02+3)0.+5&yyWyArpqt^iiltJ^opeyyNFAy..5-y
QDl_ifkPmlkplopefm%M^oq.&yWyQeb?^oobkpyyKyD^wiltb%3/+4)03+0&yyNFAy..45y
>Dl_ifkPmlkplopefm%M^oq/&yWyQeb?^oobkpyyKyD^wiltb%3/+4)03+0&yyNFAy..5-y
QTe^ocj^pqboAfwwvtfdyWyQeb?^oobkpyyKyTe^ocj^pqboAfwwvtfd%30+0)05+1&yyNFAy....y
>M^oqpcloHo^sbiyWyQeb?^oobkpyyKyTe^ocj^pqboAfwwvtfd%30+0)05+1&yyNFAy.../y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
