DugisGuideViewer:RegisterGuide("Stranglethorn Vale (34-36)", "Arathi Highlands (36-37)", "Horde", "L", function()
return [[
AAA

_?llqv?^vyKyQ^hbqeb_l^qql?llqv?^v%35+/)05+3&yyWyQeb?^oobkpyyNFAy..5.y
QDl_ifkPmlkplopefm%M^oq/&yKyTe^ocj^pqboIlwdfi%/3+0)40+2&yyNFAy..5-y
>Dl_ifkPmlkplopefm%M^oq0&yKyTe^ocj^pqboIlwdfi%/3+0)40+2&yyNFAy..5.y
e?llqv?^vyKyFkkhbbmboPhfkaib%/4+.)44+0&yyNFAy3-2y
>Pfkdfkd?irbPe^oapyKy@o^khCfwwib_r_%/4+.)44+0&yyNFAy3-2y
>?illap`^imB^opyKyHb_lh%/4+-)44+/&yyNFAy.56y
>ElpqfibQ^hblsboyKyHb_lh%/4+-)44+/&yyNFAy/.0y
>Fksbpqfd^qbqeb@^jmyKyHo^wbh%/4+-)44+/&yyNFAy/-.y
QDl_ifkPmlkplopefm%M^oq0&yKy?^olkObsfid^w)0oacillolcqebfkk%/4+/)43+6&yyNFAy..5.y
>Dl_ifkPmlkplopefm%M^oq1&yKy?^olkObsfid^w%/4+/)43+6&yyNFAy..5/y

CDolj$dli?^pb@^jmyKyDofkdbo%/3+6)44&yyNFAy235y
>QebAbcbkpblcDolj$dli%M^oq.&yKy@ljj^kabo>ddol$dlpe%0/+/)/5+5&yyNFAy235y
>Jlh$qe^oafk$pBk`e^kqjbkq%M^oq.&yKyC^oPbboJlh$qe^oafk%0/+.)/6+/&yyNFAy24-y
>?illap`^imFkpfdeqyKyKbjbqeE^thbvb%0/+-)/5+4&yyNFAy6103y
>ErkqcloVbkkfhryKyKfj_lv^%0/+/)/4+5&yyNFAy25.y
>Qolii_^kbyKyKfj_lv^%0/+/)/4+5&yyNFAy305y
>?illav?lkbKb`hi^`bpyKyHfk$tbbi^v%0/+/)/4+4&yyNFAy263y
>QebSfibObbcyKyHfk$tbbi^v%0/+/)/4+4&yyNFAy3/6y

KP^sb^iiM^dbpyKyP^sb^iiDobbkEfiiplcPqo^kdibqelokm^dbpyyNFAy3-2y
@Pfkdfkd?irbPe^oapyKyD^qeboqebXPfkdfkd@ovpq^iPe^oapZqe^qaolmcolj?^pfifphlkqeb`l^pqc^oqlqebkloqe%/2).6&yyNFAy3-2y
@QfdboJ^pqbov%M^oq0&yKyHfii.-BiaboPqo^kdibqelokQfdbop_bqtbbkqebqoliiorfkp^kaKbppfkdt^ov$p`^jm%01).6&yyNFAy.54y
@?illap`^imB^opyKyHfiiqebQoliipclo.2X?illap`^imB^opZ^olrka%/6)/-&yyNFAy.56y
@?illap`^imFkpfdeqyKyDbqqebX?illap`^imQlqbjZcolj^?illap`^imPe^j^k%/6)/-&yyNFAy6103y
@ErkqcloVbkkfhryKyD^qebo6X?illap`^imQrphpZqe^qaolmcoljqeb?illap`^imQoliip%/6)/-&yyNFAy25.y
@O^mqloJ^pqbov%M^oq/&yKyHfii.-I^peq^fiO^mqlopkb^oDolj$dli%05)/0&yyNFAy.62y
@QebAbcbkpblcDolj$dli%M^oq.&yKyHfii2jlobI^peq^fiO^mqlopql`ljmibqbqefpnrbpq^ptbii%05)/0&yyNFAy235y

QErkqcloVbkkfhryKyKfj_lv^%0/+/)/4+5&yyNFAy25.y
>Eb^aerkqfkdyKyKfj_lv^%0/+/)/4+5&yyNFAy25/y
QQebAbcbkpblcDolj$dli%M^oq.&yKy@ljj^kabo>ddol$dlpe%0/+/)/5+5&yyNFAy235y
>QebAbcbkpblcDolj$dli%M^oq/&yKy@ljj^kabo>ddol$dlpe%0/+/)/5+5&yyNFAy236y
Q?illap`^imFkpfdeqyKyKbjbqeE^thbvb%0/+-)/5+4&yyNFAy6103y
>>kRkrpr^iM^qolkyKyKbjbqeE^thbvb%0/+-)/5+4&yyNFAy6124y

@Eb^aerkqfkdyKyHfii?illap`^imEb^aerkqbop^qqebWrria^f^Orfkp%.6).1&clo/-XPeorkhbkEb^apZyyNFAy25/y
@?illav?lkbKb`hi^`bpyKyD^qeboX?illav?lkbKb`hi^`bpZ^cqbohfiifkdqebQoliipfkqebWrria^f^Orfkp%.6).1&yyNFAy263y
@>kRkrpr^iM^qolkyKyRpbqebXDfcqlcK^f^pZ^qqeb>iq^otef`efplkqebfpi^kalct^qbobibjbkq^ip%.6)//&qlprjjlkK^f^p)abcb^qefj^kaillqqebXEb^oqlcK^f^pZyyRy/035-yyNFAy6124y
@QebSfibObbcyKyIllqqebXQ^_ibqPe^oaZ^qqebrkabot^qbo`fqv%/1)/1&yyNFAy3/6y
@Bk`orpqbaQ^fiCfkpyKyHfiiqebJroil`pcloqebfoXBk`orpqbaQ^fiCfkpZ^olrka%/1)/1&yyNFAy..-4y

QQfdboJ^pqbov%M^oq0&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.54y
>QfdboJ^pqbov%M^oq1&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.55y
QO^mqloJ^pqbov%M^oq/&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.62y
>O^mqloJ^pqbov%M^oq0&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.63y
@QfdboJ^pqbov%M^oq1&yKyPfk$A^iifplkqlmlc^kb^o_vefii%0.).4&yyNFAy.55y
QQfdboJ^pqbov%M^oq1&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.55y
QEbjbqKbpfkdt^ovGo+yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy243/y
QErkqfkdfkPqo^kdibqelokyKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy2430y

@ElpqfibQ^hblsboyKyHfiiqebSbkqrob@l+dblildfpqpkb^oI^hbK^wcbofqfcloqebXQrj_iba@ovpq^ipZ^olrka%11).6&yyNFAy/.0y
@Dl_ifkPmlkplopefm%M^oq1&yKyHfiiClobj^k@lwwib%1/).5&^karpbefphbvqllmbkqebcllqil`hbo%10)/-&yyNFAy..5/y
@M^kqeboJ^pqbov%M^oq0&yKyHfiiPe^altj^tM^kqebop%15)/.&lo%05)04&yyNFAy.6/y
@Jlh$qe^oafk$pBk`e^kqjbkq%M^oq.&yKyD^qebo5XPe^altj^t@i^tpZ%15)/.&^ka^XMofpqfkbQfdobppC^kdZcoljPqo^kdibqelokQfdobppyyNFAy24-y
@QebAbcbkpblcDolj$dli%M^oq/&yKyHfii.-Jlpe$Ldd?orqbp^ka2Jlpe$LddTfq`eAl`qlopplrqeb^pqlcDolj$dli^qqebJfwg^eOrfkp%03)0-&yyNFAy236y

QM^kqeboJ^pqbov%M^oq0&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6/y
>M^kqeboJ^pqbov%M^oq1&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.60y

E?llqv?^vyRy3615yyNFAy..50y
QPfkdfkd?irbPe^oapyKy@o^khCfwwib_r_%/4+.)44+0&yyNFAy3-2y
QElpqfibQ^hblsboyKyHb_lh%/4+-)44+/&yyNFAy/.0y
Q?illap`^imB^opyKyHb_lh%/4+-)44+/&yyNFAy.56y
QFksbpqfd^qbqeb@^jmyKyHo^wbh%/4+-)44+/&yyNFAy/-.y
QDl_ifkPmlkplopefm%M^oq1&yKy?^olkObsfid^w)0oacillolcqebfkk%/4+/)43+6&yyNFAy..5/y
>Dl_ifkPmlkplopefm%M^oq2&yKy?^olkObsfid^w%/4+/)43+6&yyNFAy..50y

CDolj$dli?^pb@^jmyKyDofkdbo%/3+6)44&yyNFAy24/y
QQebAbcbkpblcDolj$dli%M^oq/&yKy@ljj^kabo>ddol$dlpe)Dolj$dli%0/+/)/5+5&yyNFAy236y
Q>kRkrpr^iM^qolkyKyKbjbqeE^thbvb%0/+-)/5+4&yyNFAy6124y
QJlh$qe^oafk$pBk`e^kqjbkq%M^oq.&yKyC^oPbboJlh$qe^oafk%0/+.)/6+/&yyNFAy24-y
>Jlh$qe^oafk$pBk`e^kqjbkq%M^oq/&yKyC^oPbboJlh$qe^oafk%0/+.)/6+/&yyNFAy24/y
QEb^aerkqfkdyKyKfj_lv^%0/+/)/4+5&yyNFAy25/y
Q?illav?lkbKb`hi^`bpyKyHfk$tbbi^v%0/+/)/4+4&yyNFAy263y
QQebSfibObbcyKyHfk$tbbi^v%0/+/)/4+4&yyNFAy3/6y

CRkabo`fqvyKyQ^hbWbmmbifkqlQfofpc^iDi^abp^kaorkqlRkabo`fqv%0.+2)/6+1&yyNFAy..31y
>QlPqb^iColjQefbsbpyWyRkabo`fqvyyKyDbk^sfb@^iilt)fkqeb`bkqbolcRkabo`fqv%31+/)16+1&yyNFAy..31y
>>Alk^qflklcPfihyWyRkabo`fqvyyKyO^ipqlkC^okpibv%4.+5)/6+.&yyNFAy45.1y
Q>Alk^qflklcPfihyWyRkabo`fqvyyKyO^ipqlkC^okpibv%4.+5)/6+.&yyNFAy45.1y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
