DugisGuideViewer:RegisterGuide("Arathi Highlands (36-37)", "Alterac Mountains (37)", "Horde", "L", function()
return [[
AAA

CE^jjboc^iiyKyJf`e^biD^oobqq%30+2)15+4&yyWyRkabo`fqvyyNFAy34.y
eE^jjboc^iiyKyFkkhbbmbo>abdt^%40+5)0/+3&yyNFAy34.y
QQolii_^kbyKyWbkdr%40+5)00+6&+Phfmqebcliilt*rmyyNFAy305y
>ClriJ^df`pyKyQlo$d^k%41+4)03+0&yyNFAy34.y
>DrfiblcqebO^mqlo%M^oq.&yKyQlo$d^k%41+4)03+0&yyNFAy4-.y
>QebMofk`bppQo^mmbayKy>qqebPe^oaplcJvwo^bitbpqlcE^jjboc^ii%3/+2)00+5&yyNFAy31/y
@QebMofk`bppQo^mmbayKyD^qebo./XJlqbplcJvwo^biZfkqeb`^sbplrqeb^pqlcE^jjboc^ii%45)04&yyNFAy31/y
QQebMofk`bppQo^mmbayKyFofabp`bkqPe^oap)fkqeb_^`hlcqeb`^sb%51+0)0-+6&yyNFAy31/y
>Pqlkbplc?fkafkdyKyFofabp`bkqPe^oap%51+0)0-+6&yyNFAy32.y

KDbq@obpqfkdHbvyKyColjPqlkblcB^pq?fkafkd%33)/6&yyNFAy32.yyNLy@obpqfkdHbv7.,.y
@QlPqb^iColjQefbsbpyKyHfiiHbk^q^%23)03&)C^babi%21)04&^kaJ^o`bi%20)06&^qqebA^_vofbC^ojpqb^ayyNFAy..31y
KDbqQerkabofkdHbvyKyColjPqlkblcLrqbo?fkafkd%2/)2-&yyNFAy32.yyNLyQerkabofkdHbv7.,.y

@DrfiblcqebO^mqlo%M^oq.&yKyHfiiEfdei^kaCibpepq^ihbopclo./XO^mqloEb^oqpZ^olrka%20)4-&yyNFAy4-.y
@QebE^jjboJ^vC^iiyKyHfii5?lriabocfpqLdobp^ka.-?lriabocfpqBkclo`bop%01)12&yyNFAy343y

@ClriJ^df`pyKyHfiiqebPvkaf`^qb^qKloqecliaJ^klo%0.)/5&clo.-X?illapqlkb>jribqpZyyNFAy34.y
@Pqlkbplc?fkafkdyKyDbqqebX?rokfkdHbvZcoljqebPqlkblcTbpq?fkafkd%/2)0.&yyNFAy32.y
QPqlkbplc?fkafkdyKy>qPqlkblcFkkbo?fkafkd%03+/)24+2&yyNFAy32.y

EE^jjboc^iiyRy3615yyNFAy4-/y
QClriJ^df`pyKyQlo$d^k%41+4)03+0&yyNFAy34.y
QQebE^jjboJ^vC^iiyKyAorjCbi%41+/)00+5&yyNFAy343y
QDrfiblcqebO^mqlo%M^oq.&yKyQlo$d^k%41+4)03+0&yyNFAy4-.y
>DrfiblcqebO^mqlo%M^oq/&yKyQlo$d^k%41+4)03+0&yyNFAy4-/y
QDrfiblcqebO^mqlo%M^oq/&yKyDlo$jri%4/+4)01+-&yyNFAy4-/y
>DrfiblcqebO^mqlo%M^oq0&yKyDlo$jri%4/+4)01+-&yyNFAy514y
QDrfiblcqebO^mqlo%M^oq0&yKyQlo$d^k%41+4)03+0&yyNFAy514y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
