DugisGuideViewer:RegisterGuide("Dustwallow Marsh (37-38)", "Stranglethorn Vale (39-40)", "Horde", "L", function()
return [[
AAA

CQerkabo?irccyKyAbso^h%2.+2)0-+0&yyWyQeb?^oobkpyyNFAy./-2y
QColpqj^tyWyQerkabo?irccyyKyJbiloPqlkbellc)Erkqbo$pOfpb%3.)5-&yyNFAy..03y
>Ab^ajfobyWyQerkabo?irccyyKyJbiloPqlkbellc%3.)5-&yyNFAy./-2y

CArpqt^iiltJ^opeyKyQ^i%13+5)2-+/&yyWyQerkabo?irccyyNFAy./-.y
e?o^`hbkt^iiSfii^dbyKyIfqqibIldlh%03+3)0/&yyNFAy./-.y
>Qebo^jlobPmfbpyKyK^wbbo?illamfhb%02+0)0-+4&yyNFAy./-.y
>@eb`hRmlkQ^_bqe^yKyK^wbbo?illamfhb%02+0)0-+4&yyNFAy../.0y
>Qeb?i^`hPefbia%M^oq0&yKyAl$dli%03+2)05+-&yyNFAy.0//y
>QtfifdeqlcqebA^tkOrkkboyKy?^i^ka^o?ofdeqpq^o%02+5)0.+3&yyNFAy6104y
>QebEbojfqlcTfq`eEfiiyKyAo^w$Wfi_%04+.)00+-&yyNFAy..//2y
>ErkdovyKyJra`orpeAroqcbbq)plrqelc?o^`hbkt^ii%02+.)05+/&yyNFAy..44y

@QtfifdeqlcqebA^tkOrkkboyKyDbqqebXA^tkOrkkbo@^odlZlkqebqlmlcqebKloqemlfkqQltbo%13)/0&yyIy/0324yyNFAy6104y

>QebIlpqObmloqyKyAfoqmfibkb^oG^oi$perq%22+1)/3+-&yyNFAy./05y
QQebEbojfqlcTfq`eEfiiyKyPt^jmBvbG^oi%22+1)/3+0&yyNFAy..//2y

>J^opeColdIbdpyKyPt^jmBvbG^oi%22+1)/3+0&yyNFAy./.5y
>Te^q$pE^rkqfkdTfq`eEfii<yKyJloa^kqDofjp_v%22+3)/3+0&yyNFAy...5-y
@J^opeColdIbdpyKyHfiiqebDf^kqJ^opeColdpkb^o_v%22)/6&yyNFAy./.5y
@Te^q$pE^rkqfkdTfq`eEfii<yKyHfii.-Delpqpfkqeb^ob^%22)/2&yyNFAy...5-y

QJ^opeColdIbdpyKyPt^jmBvbG^oi%22+1)/3+0&yyNFAy./.5y
>G^oiKbbapBvbpyKyPt^jmBvbG^oi%22+1)/3+0&yyNFAy./-3y

QTe^q$pE^rkqfkdTfq`eEfii<yKyJloa^kqDofjp_v%22+3)/3+0&yyNFAy...5-y
>QebTfq`e$p?^kbyKyJloa^kqDofjp_v%22+3)/3+0&yyNFAy...5.y

@QebTfq`e$p?^kbyKyD^qeboqebmi^kqpfkqebt^qbo%22)/2&yyNFAy...5.y
@ErkdovyKyHfiiqebJroil`plkqebmbkfkpri^%25).2&clo5XJfobcfkEb^apZyyNFAy..44y

QQebTfq`e$p?^kbyKyJloa^kqDofjp_v%22+3)/3+0&yyNFAy...5.y
>@ib^kpfkdTfq`eEfiiyKyJloa^kqDofjp_v%22+3)/3+0&yyNFAy...50y
@@ib^kpfkdTfq`eEfiiyKyMi^kqqebXTfq`e_^kbQlo`eZ^qqebbkalcqebal`h^kahfiiqeb_^q%22+2)/2+4&yyRy00..0yyNFAy...50y
Q@ib^kpfkdTfq`eEfiiyKyJloa^kqDofjp_v%22+3)/3+0&yyNFAy...50y

>Pqfkhv$pBp`^mbyKyPqfkhvFdk^qw)kloqelcqebqltbo%13+4).4+-&yyNFAy./4-y
@Pqfkhv$pBp`^mbyKyBp`loqPqfkhvFdk^qw%13+4).4+-&yyNFAy./4-y

@G^oiKbbapBvbpyKyHfiipmfabopkloqelc?o^`hbkt^iiSfii^db^qqebA^ohjfpq@^sbok%02)/.&clo/-XRkmlmmbaA^ohjfpqBvbpZyyNFAy./-3y
@Qeb?i^`hPefbia%M^oq0&yKyD^qebo2X>`faf`SbkljP^`pZcoljqebpmfabop^qqebA^ohjfpq@^sbok%02)/.&yyNFAy.0//y
@Qebo^jlobPmfbpyKyHfii6Qebo^jlobFkcfiqo^qlop)pqb^iqebajl_p^olrka?o^`hbkt^iiSfii^db%10)0-&yyNFAy./-.y

QQebo^jlobPmfbpyKyK^wbbo?illamfhb%02+0)0-+4&yyNFAy./-.y
>QebQebo^jlobAl`hpyKyK^wbbo?illamfhb%02+0)0-+4&yyNFAy./-/y
QQebIlpqObmloqyKyK^wbbo?illamfhb%02+0)0-+4&yyNFAy./05y
>EbimJrapmol`hbqyKyK^wbbo?illamfhb%02+0)0-+4&yyNFAy../.2y
QQeb?i^`hPefbia%M^oq0&yKyAl$dli%03+2)0-+6&yyNFAy.0//y
>Qeb?i^`hPefbia%M^oq1&yKyAl$dli%03+2)0-+6&yyNFAy.0/0y
QQeb?i^`hPefbia%M^oq1&yKyHold%03+1)0.+5&yyNFAy.0/0y
>Fkpmb`qfkdqebOrfkpyKyHold%03+1)0.+5&yyNFAy.../1y
QQtfifdeqlcqebA^tkOrkkboyKy?^i^ka^o?ofdeqpq^o%02+5)0.+3&yyNFAy6104y

QErkdovyKyPlrqetbpq^qJra`orpeAroqcbbq%02)05&yyNFAy..44y
QFkpmb`qfkdqebOrfkpyKyFkpmb`qloQ^obj%/6+3)14+2&yyNFAy.../1y

Q@eb`hRmlkQ^_bqe^yKyQ^_bqe^)cliiltqebol^aplrqe)qebkb^pqqlQ^_bqe^$pC^oj%13+-)24+.&yyNFAy../.0y
>QebDofjqlqbjTb^mlkyKy>mmobkqf`bD^oflk%13+-)24+/&yyNFAy...36y
>QebOb^dbkqQefbcyKy>mmobkqf`bD^oflk%13+-)24+/&yyNFAy...40y
>AfobelokO^fabopyKy>mmobkqf`bJloi^kk%13+.)24+2&yyNFAy...23y
>QebWbmmbifk@o^peyKy>mmobkqf`bJloi^kk%13+.)24+2&yyNFAy...4/y

@QebDofjqlqbjTb^mlkyKyRpbvlroX@^mqrobaQlqbjZkb^oqeb@ol`p%12+5)23+6&qlqebkloqe^kahfiiqebjyyRy00.-.yyNFAy...36y
@QebOb^dbkqQefbcyKyHfiiPmfabop^kaPeobaabopkb^oQ^_bqe^$pErq%1.)2.&yyNFAy...40y

@AfobelokO^fabopyKyHfiiDofjqlqbjpkloqelcqeberq%13+3)14+0&yyNFAy...23y
H>mlqeb`^ov@vii^yKyHfii>mlqeb`^ov@vii^%13+4)14+/&aolmp^XPb^ibaIbqqboZyyIy00..2yyNFAy...53y
>PfdkplcQob^`ebov<yKyQebfqbjXPb^ibaIbqqboZpq^oqpnrbpqyyRy00..2yyNFAy...53y

QAfobelokO^fabopyKy>mmobkqf`bJloi^kk%13+.)24+2&yyNFAy...23y
QQebDofjqlqbjTb^mlkyKy>mmobkqf`bD^oflk%13+-)24+/&yyNFAy...36y
QQebOb^dbkqQefbcyKy>mmobkqf`bD^oflk%13+-)24+/&yyNFAy...40y

@Ab^ajfobyKyHfiiAb^ajfob)ol^jp^olrka%14)24&yyNFAy./-2y

QQebWbmmbifk@o^peyKyJlufbPqbbidofiib)qlqebb^pq^q?bbwfi$pTob`h%20+2)24+-&yyNFAy...4/y
>@loolpflkMobsbkqflkyKyJlufbPqbbidofiib%20+2)24+-&yyNFAy...41y
>Pb`robqeb@^odlyKyJlufbPqbbidofiib%20+2)24+-&yyNFAy../-4y

@@loolpflkMobsbkqflkyRy00.-5yyKyDlqlqeb`o^pepfqb%20+.)23+2&J^hbprobvlre^sbqebBkbodfwba_rcc^karpbqebXLlwb?rpqboZlkqebpifjbpyyNFAy...41y
@Pb`robqeb@^odlyKyOb`lsbo5mfb`bplcXWbmmbifk@^odlZ^olrkaqeb`o^pepfqb%2/)24&yyNFAy../-4y
@O^wwbof`$pQtb^hfkdyKyIllqqeb_lu%21)23&ofdeq_befkaqebwbmmbifkyyNFAy..54y

Q@loolpflkMobsbkqflkyKyJlufbPqbbidofiib%20+2)24+-&yyNFAy...41y
QPb`robqeb@^odlyKyJlufbPqbbidofiib%20+2)24+-&yyNFAy../-4y
>AbifsbovcloAo^wwfqyKyJlufbPqbbidofiib%20+2)24+-&yyNFAy../-5y

QAbifsbovcloAo^wwfqyKyAo^wwfqAofms^isb)^qJrapmol`hbq%1/+0)4/+6&yyNFAy../-5y
QEbimJrapmol`hbqyKyAo^wwfqAofms^isb%1/+0)4/+6&yyNFAy../.2y

C?o^`hbkt^iiSfii^dbyKyAvpifuPfisbodor_%1/+6)4/+2&yyNFAy./06y
>QebPbsbobaEb^ayKyIllpbAfoq^qG^oi$p`^_fk%22+2)/3+-&yyNFAy./06y
QG^oiKbbapBvbpyKyPt^jmBvbG^oi%22+1)/3+0&yyNFAy./-3y
>G^oiKbbap^?i^abyKyPt^jmBvbG^oi%22+1)/3+0&yyNFAy./-0y
@G^oiKbbap^?i^abyKyHfiiO^wlopmfkbqlqebkloqe%25+.).4+5&yyNFAy./-0y
QG^oiKbbap^?i^abyKyPt^jmBvbG^oi%22+1)/3+0&yyNFAy./-0y

@QebQebo^jlobAl`hpyKyDbqqebX@^mq^fk$pAl`rjbkqpZcoljrkaboqebb^pqbokmfbo^qQebo^jlob%4.)2.&+T^q`elrqcloqebpe^ohyyNFAy./-/y

E?o^`hbkt^iiSfii^dbyRy3615yyNFAy./1-y
QQebQebo^jlobAl`hpyKyK^wbbo?illamfhb%02+0)0-+4&yyNFAy./-/y
QPfdkplcQob^`ebov<yKyK^wbbo?illamfhb%02+0)0-+4&yyNFAy...53y
QQebPbsbobaEb^ayKyK^wbbo?illamfhb%02+0)0-+4&yyNFAy./06y
>QebQoliiTfq`eal`qloyKyK^wbbo?illamfhb%02+0)0-+4&yyNFAy./1-y

CQerkabo?irccyKyPe^oaf%02+3)0.+5&y
QAb^ajfobyWyQerkabo?irccyyKyJbiloPqlkbellc)Erkqbo$pOfpb%3.)5-&yyNFAy./-2y

CO^q`ebqyKyQ^i%13+5)2-+/&yyWyQerkabo?irccy
QPqfkhv$pBp`^mbyWyQeb?^oobkpyyKyJb_lhJfwwvofu%3/+1)04+3&yyNFAy./4-y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)

