DugisGuideViewer:RegisterGuide("Alterac Mountains (37)", "Thousand Needles (37)", "Horde", "L", function()
return [[
AAA

CQ^oobkJfiiyKyRoa^%40+.)0/+4&yyWy>o^qefEfdei^kapyyNFAy211y
>Mofplk?ob^hFkyWyEfiip_o^aCllqefiipyyKyJ^drpTloabbkSlfadi^ob%3.+3)/-+5&yyNFAy211y
>PqlkbQlhbkpyWyEfiip_o^aCllqefiipyyKyHbbmbo?bi$s^ofi%3.+2)/-+5&yyNFAy223y
>Qeb@oltklcTfiiyWyEfiip_o^aCllqefiipyyKyJbifp^o^%3/+3)/-+3&yyNFAy2.5y
@Colpqj^tyKyHfiiColpqj^t%04)36&rmkloqefkqeb>iqbo^`Jlrkq^fkpyyNFAy..03y
@Qeb@oltklcTfiiyKyHfii.-@orpeofadbJ^ribop^qqebOrfkplc>iqbo^`%1-)2-&yyNFAy2.5y

@PqlkbQlhbkpyKyHfiiqebjl_p^qqebIloa^jbobFkqbokjbkq@^jm%/.)50&^kaq^hbqebXTlokPqlkbQlhbkpZyyNFAy223y
@Mofplk?ob^hFkyKyHfiiOf`qbo%.6)51&)>ifk^%/-)53&)Abojlq%.6)52&^kaHbd^kA^ohj^o%.4)50&^qqebIloa^jbobFkqbokjbkq@^jm%/.)50&yyNFAy211y
QMofplk?ob^hFkyWyEfiip_o^aCllqefiipyyKyJ^drpTloabbkSlfadi^ob%3.+3)/-+5&yyNFAy211y
QPqlkbQlhbkpyWyEfiip_o^aCllqefiipyyKyHbbmbo?bi$s^ofi%3.+2)/-+5&yyNFAy223y
QQeb@oltklcTfiiyWyEfiip_o^aCllqefiipyyKyJbifp^o^%3/+3)/-+3&)phfmm^oq/yyNFAy2.5y

CRkabo`fqvyKyW^ofpb%3-+/).5+4&yyWyEfiip_o^aCllqefiipy
QQlPqb^iColjQefbsbpyWyRkabo`fqvyyKyDbk^sfb@^iilt%31+/)16+1&yyNFAy..31y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
