DugisGuideViewer:RegisterGuide("Thousand Needles (37)", "Dustwallow Marsh (37-38)", "Horde", "L", function()
return [[
AAA

CLodofjj^oyKyQ^hbqebwbmmbifklrqpfabRkabo`fqv)b^pqqltbo%3-+4)25+4&yyWyQfofpc^iDi^abpyyNFAy..14y
Q>iif^k`bObi^qflkp%M^oq1&yWyLodofjj^oyyKyHbiao^k)fkqebS^iibvlcPmfofqp%/.)20&yyNFAy.103y
CQeb@olppol^apyKyAlo^p%12+0)31&yyWyLodofjj^oyyNFAy..14y
eQeb@olppol^apyKyFkkhbbmbo?llo^kaMi^fkptfka%2/)/6+6&yyWyQeb?^oobkpyyNFAy..14y
CCobbtfkaMlpqyKyAbso^h%2.+2)0-+0&yyWyQeb?^oobkpyyNFAy..14y

QQebPt^ojDoltp%M^oq/&yKyJlhq^oHofk)fkQebPefjjbofkdCi^qp%34+3)31+-&yyNFAy..13y
>QebPt^ojDoltp%M^oq0&yKyJlhq^oHofk%34+3)31+-&yyNFAy..14y

QM^oqpcloHo^sbiyKyHo^sbi)^qqebJfo^dbO^`bt^v%44+5)44+/&yyNFAy.../y
>AbifsbovqlqebDkljbpyKyHo^sbi%44+5)44+/&yyNFAy...1y
QAbifsbovqlqebDkljbpyKyCfwwib?o^pp_liqp%45+-)44+.&yyNFAy...1y
QDl_ifkPmlkplopefm%M^oq2&yKyMlwwfh%5-+.)42+6&yyNFAy..50y

>QebBfdeqbbkqeMfilqyKyMlwwfh%5-+.)42+6&yyNFAy..53y
QQebBfdeqbbkqeMfilqyKyO^wwbof`%5-+0)43+.&yyNFAy..53y

>O^wwbof`$pQtb^hfkdyKyO^wwbof`%5-+0)43+.&yyNFAy..54y
QBk`orpqbaQ^fiCfkpyKyTfwwib?o^pp_liqp%45+.)44+.&yyNFAy..-4y
>QebOrjlojlkdboyKyHo^sbi%44+5)44+/&yyNFAy...2y

>M^oqplcqebPt^oj%M^oq.&yRy2544yyKyHfiipfifqefapqlqebplrqe%35)5-&rkqfiqebfqbjX@o^`hbaPfifqefa@^o^m^`bZaolmptef`epq^oqpqefpnrbpqyyNFAy..15yyLy
@QebPt^ojDoltp%M^oq0&yKyHfii2PfifqefaPb^o`ebop)2PfifqefaEfsbAolkbp)^ka2PfifqefaFks^abop%36)52&yyNFAy..14y
@M^oqplcqebPt^oj%M^oq.&yKyD^qebo.XPfifqefaEb^oqZ)2XPfifqefaQ^ilkpZ^ka0XFkq^`qPfifqefa@^o^m^`bpZtef`eaolmcoljqebPfifqefajl_p%36)52&yyNFAy..15yyLy
QQebPt^ojDoltp%M^oq0&yKyJlhq^oHofk%34+3)31+-&yyNFAy..14y

EQeb@olppol^apyRy3615yyNFAy..51y
QM^oqplcqebPt^oj%M^oq.&yWyQeb?^oobkpyyKyHloo^k%2.+.)/6+3&yyNFAy..15yyLy
>M^oqplcqebPt^oj%M^oq/&yWyQeb?^oobkpyyKyHloo^k%2.+.)/6+3&yyNFAy..51y
]]
end)
