DugisGuideViewer:RegisterGuide("Stranglethorn Vale (39-40)", "Badlands (40-41)", "Horde", "L", function()
return [[
AAA

_?llqv?^vyKyQ^hbqeb_l^qql?llqv?^v%35+/)05+3&yyWyQeb?^oobkpyyNFAy262y
>Qeb?illap^fi?r``^kbbop%M^oq.&yKyCfopqJ^qb@o^ww%/5+.)43+/&yyNFAy262y
>P`^ofkdPe^hvyKyPb^TlicJ^`Hfkibv%/4+5)44+.&yyNFAy3-3y
e?llqv?^vyKyFkkhbbmboPhfkaib%/4+.)44+0&yyNFAy...3y
QQebOrjlojlkdboyKyHo^wbh%/4+-)44+/&yyNFAy...2y
>Aob^jArpqfkqebPt^jmyKyHo^wbh%/4+-)44+/&yyNFAy...3y

CDolj$dli?^pb@^jmyKyDofkdbo%/3+6)44&yyNFAy./3.y
QQebQoliiTfq`eal`qloyKyHfk$tbbi^v%0/+/)/4+4&yyNFAy./1-y
>J^odPmb^hpyKy?r__ifkd@^riaolk%0/+/)/4+4&yyNFAy./3.y

@O^mqloJ^pqbov%M^oq0&yKyHfii.-GrkdibPq^ihbop%0.)1.&yyNFAy.63y
@Jlh$qe^oafk$pBk`e^kqjbkq%M^oq/&yKyHfiiGrkdibPq^ihbopclo.-XGrkdibPq^ihboCb^qebopZ^olrka%0.)1.&yyNFAy24/y

QJlh$qe^oafk$pBk`e^kqjbkq%M^oq/&yKyC^oPbboJlh$qe^oafk%0/+.)/6+/&yyNFAy24/y
>Jlh$qe^oafk$pBk`e^kqjbkq%M^oq0&yKyC^oPbboJlh$qe^oafk%0/+.)/6+/&yyNFAy24.y

@M^kqeboJ^pqbov%M^oq1&yKyHfii?e^d$qebo^^kaillqqebXC^kdlc?e^d$qebo^Z%2-)/3&yyNFAy.60y

QM^kqeboJ^pqbov%M^oq1&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.60y
QO^mqloJ^pqbov%M^oq0&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.63y
>O^mqloJ^pqbov%M^oq1&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.64y

E?llqv?^vyRy3615yyNFAy264y
QQeb?illap^fi?r``^kbbop%M^oq.&yKy>klqblk^`o^qbKTlc??^q%/4)36&yyNFAy262y
>Qeb?illap^fi?r``^kbbop%M^oq/&yKy>klqblk^`o^qbKTlc??^q%/4)36&yyNFAy264y

@P`^ofkdPe^hvyKyHfiiqebBiaboJfpqs^ibDlofii^$pfkqebJfpqs^ibS^iibvclo2XJfpqs^ibDf_ibqpZ^olrka%01)31&yyNFAy3-3y
@Jlh$qe^oafk$pBk`e^kqjbkq%M^oq0&yKyQebDlofii^pfkqebJfpqs^ibS^iibv^iplaolmqebX>dbaDlofii^PfkbtZ%01)31&+Klqb7P^sb^iiqebXDlofii^C^kdpZvlrcfkaclo^i^qbonrbpqyyNFAy24.y

QP`^ofkdPe^hvyKyPe^hvMefiifmb%/3+5)40+3&yyNFAy3-3y
>ObqrokqlJ^`HfkibvyKyPe^hvMefiifmb%/3+5)40+3&yyNFAy3-4y
QQeb?illap^fi?r``^kbbop%M^oq/&yKyCfopqJ^qb@o^ww%/5+.)43+/&yyNFAy264y
>Qeb?illap^fi?r``^kbbop%M^oq0&yKyCfopqJ^qb@o^ww%/5+.)43+/&yyNFAy266y
QObqrokqlJ^`HfkibvyKyPb^TlicJ^`Hfkibv%/4+5)44+.&yyNFAy3-4y
QQeb?illap^fi?r``^kbbop%M^oq0&yKyCibbqJ^pqboPb^elok%/4+.)44+-&yyNFAy266y

CDolj$dli?^pb@^jmyKyDofkdbo%/3+6)44&yyNFAy240y
QJlh$qe^oafk$pBk`e^kqjbkq%M^oq0&yKyC^oPbboJlh$qe^oafk%0/+.)/6+/&yyNFAy24.y
>Jlh$qe^oafk$pBk`e^kqjbkq%M^oq1&yKyC^oPbboJlh$qe^oafk%0/+.)/6+/&yyNFAy240y
eDolj$dli?^pb@^jmyKyFkkhbbmboQeri_bh%0.+2)/6+4&y

CQfofpc^iDi^abpyKyQ^hbqebWbmmbifkqlQfofpc^iDi^abp%0.+2)/6+1&y
CE^jjboc^iiyKyJf`e^biD^oobqq%30+2)15+4&yyWyRkabo`fqvy
OTbqi^kapyKyOrkqlTbqi^kap%12+1)63+3&yyWy>o^qefEfdei^kapy
OIl`eJla^kyKyOrkqlIl`eJla^k%22)62&qeolrdeqebqrkkbi^q%20+4)4/+/&yyWyTbqi^kapy
O?^ai^kapyKyOrkql?^ai^kap%14+/)61+6&yyWyIl`eJla^ky
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
