DugisGuideViewer:RegisterGuide("Badlands (40-41)", "Swamp of Sorrows (41-42)", "Horde", "L", function()
return [[
AAA

QJ^oqbhqebBufibayKyJ^oqbhqebBufiba%1/+0)2/+3&yyNFAy..-3y
>FkarofrjyKyJ^oqbhqebBufiba%1/+0)2/+3&yyNFAy..-5y
>?^o_b`rba?rww^oaTfkdpyKyOfddibcrww%1/+1)2/+5&yyNFAy4-0y
@FkarofrjyKyHfiiQolddp^q>djlka$pBka%2-)35&clo.-XFkarofrjCi^hbpZyyNFAy..-5y
QFkarofrjyKyJ^oqbhqebBufiba%1/+0)2/+3&yyNFAy..-5y
>KbtpcloCfwwibyKyJ^oqbhqebBufiba%1/+0)2/+3&yyNFAy..04y
>PqravlcqebBibjbkqp7Ol`h%M^oq.&yKyIlqtfiSbof^qrp%/2+6)12+-&yyNFAy4.-y

OH^od^qeyKyOrkqlH^od^qe%1)11+6&yyNFAy6106y
cH^od^qeyKyDloofh%1)11+6&yyNFAy6106y
>@lvlqbQefbsbpyKyKbbh^?illap`^o%3+2)14+.&yyNFAy.1.6y
>ObmloqqlEbidorjyKyKbbh^?illap`^o%3+2)14+.&yyNFAy.1/-y
>?olhbk>iif^k`bpyKyDlok%/+6)12+5&yyNFAy45/y
>?^ai^kapOb^dbkqOrkyKyG^oh^iJlppjbia%/+2)13+.&yyNFAy//25y

@?^o_b`rba?rww^oaTfkdpyKyHfiiqeb?rww^oapclo1X?rww^oaTfkdpZ^olrka%.1)3-&yyNFAy4-0y
@@lvlqbQefbsbpyKyHfiiqeb@lvlqbpclo0-X@lvlqbG^t_lkbpZ^olrka%..)30&yyNFAy.1.6y
@?^ai^kapOb^dbkqOrkyKyHfiiOl`hBibjbkq^ip%.0)03&clo2XOl`hBibjbkq^iPe^oapZ+Hfii?rww^oap%.1)3-&clo2X?rww^oaDfww^oapZ+Hfii@lvlqbp%..)30&clo.-X@o^d@lvlqbC^kdpZyyNFAy//25y
@PqravlcqebBibjbkqp7Ol`h%M^oq.&yKyHfiiqebIbppboOl`hBibjbkq^ip%.5)12&clo.-XPj^iiPqlkbPe^oapZyyNFAy4.-y
@?olhbk>iif^k`bpyKyHfii?lppQel$dork)ebm^qolip^olrka?^ai^kap%..)4/&)%.5)46+4&)%26)36&)%15)2.&)%/6+2)26&)%/0)2/&^ka_ofkdqebXPfdklcqebB^oqeZqlDlokfkH^od^qe+yyNFAy45/y

QPqravlcqebBibjbkqp7Ol`h%M^oq.&yKyIlqtfiSbof^qrp%/2+6)12+-&yyNFAy4.-y
>PqravlcqebBibjbkqp7Ol`h%M^oq/&yKyIlqtfiSbof^qrp%/2+6)12+-&yyNFAy4..y
@PqravlcqebBibjbkqp7Ol`h%M^oq/&yKyHfiiOl`hBibjbkq^ipclo0XI^odbPqlkbPi^_pZ^olrka%01)41&yyNFAy4..y

QPqravlcqebBibjbkqp7Ol`h%M^oq/&yKyIlqtfiSbof^qrp%/2+6)12+-&+Phfmqebcliilt*rmyyNFAy4..y
Q@lvlqbQefbsbpyKyKbbh^?illap`^o%3+2)14+.&yyNFAy.1.6y
Q?olhbk>iif^k`bpyKyDlok%/+6)12+5&yyNFAy45/y
Q?^ai^kapOb^dbkqOrkyKyG^oh^iJlppjbia%/+2)13+.&yyNFAy//25y
Q?^o_b`rba?rww^oaTfkdpyKyOfddibcrww%1/+1)2/+5&yyNFAy4-0y

EDolj$dli?^pb@^jmyRy3615yyNFAy.04/y
QQebDobbkEfiiplcPqo^kdibqelokyWyPqo^kdibqelokS^ibyyKy?^okfiPqlkbmlq%02+4).-+2&yyLyyNFAy005y
>Klqefkd?rqQebQorqe%M^oq.&yWyArphtllayyKy>mlqeb`^ovC^rpqfk%54+-)03+1&yyNFAy.04/y
QKlqefkd?rqQebQorqe%M^oq.&yWyArphtllayyKyAb^qepq^ihboWo^barp%54+4)02+4&yyNFAy.04/y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
