DugisGuideViewer:RegisterGuide("Swamp of Sorrows (41-42)", "Stranglethorn Vale (42-43)", "Horde", "L", function()
return [[
AAA

OArphtllayKyOrkkloqeqlArphtlla%1.+4)-+0&yyWyPqo^kdibqelokS^ibyyNFAy.04/y
>Klqefkd?rqQebQorqe%M^oq.&yKyAb^qepq^ihboWo^barp%54+4)02+4&yyWyArphtllayyNFAy.04/y
QKlqefkd?rqQebQorqe%M^oq.&yKy>mlqeb`^ovC^rpqfk%54+2)02+1&yyWyArphtllayyNFAy.04/y
OPt^jmlcPlooltpyKyOrkb^pqqeolrdeAb^atfkaM^ppqlPt^jmlcPlooltp%30+5)1-+4&yyWyAb^atfkaM^ppyyNFAy.06/y
K@ib^oTebimp^olrkaqebpj^iii^hbyKy@liib`qXPmb`hlcAob^jArpqZcoljqebtebimp)qefpe^p^iltaolmo^qb^kavlr`^kalpljbjlobi^qbo%.1)26&yyNFAy...3y
HKl_lorqeb@radbiyKyKl_lorqeb@radbitfiim^qoliql%10+2)04&^kaebpm^tkp^q%22+5)01+1&yyIy3.63yyNFAy.06/y
>Kl_lorqeb@radbiyRy3.63yyKyRpbXKl_lor$p@radbiZql_bdfkqebnrbpqyyNFAy.06/y
QKl_lorqeb@radbiyKyJ^dqllo%/3+-)0.+2&yyNFAy.06/y
>Ao^bkbqevpq@ovpq^ipyKyJ^dqllo%/3+-)0.+2&yyNFAy.056y

OPqlk^oayKyOrkqlPqlk^oa%13)21+4&yyNFAy365y
cPqlk^oayKy?obvh%13)21+4&yyNFAy365y
ePqlk^oayKyFkkhbbmboH^o^hri%12+.)23+2&yyNFAy365y
>I^`hlcPromirpyKyA^o%11+5)24+-&yyNFAy365y
>IfqqibJlopbipyKy@bopbfArphpfkdbo%14+4)21+5&yyNFAy611-y
QObmloqqlEbidorjyKyEbidorjqebPtfcq%14+6)22+.&yyNFAy.1/-y
>MllilcQb^opyKyCbi$wbori%14+6)21+6&yyNFAy.1/1y

@I^`hlcPromirpyKyHfiiP^tqllqe@ol`lifphpclo5XRkmobm^obaP^tqllqeCi^khZ^olrka%45).5&yyNFAy365y
@MllilcQb^opyKyD^qebo2X>q^i$^f>oqfc^`qZfk^ka^olrkaqeb_fdi^hb%34)30&yyNFAy.1/1y

QI^`hlcPromirpyKyQlh$H^o%5.+1)5-+6&yyNFAy365y
>I^`hlcPromirp%M^oq/&yKyQlh$H^o%5.+1)5-+6&yyNFAy366y
@I^`hlcPromirp%M^oq/&yKy@liib`q3XP^tqllqePk^mmbo@i^tpZcoljP^tqllqePk^mmbo^olrka%5/+2)33&yyNFAy366y
QI^`hlcPromirp%M^oq/&yKyQlh$H^o%5.+1)5-+6&yyNFAy366y
>Qeob^qColjqebPb^yKyQlh$H^o%5.+1)5-+6&yyNFAy.1//y
QQeob^qColjqebPb^yKyH^q^o%50+4)5-+2&yyNFAy.1//y
>Qeob^qColjqebPb^%M^oq/&yKyH^q^o%50+4)5-+2&yyNFAy.1/3y
@Qeob^qColjqebPb^%M^oq/&yKyHfiiqebobnrfobaJroil`pclrka^ilkdqebB^pq`l^pq%51)54+0&)%6-)40&)%61)24&yyNFAy.1/3y
QQeob^qColjqebPb^%M^oq/&yKyH^q^o%50+4)5-+2&yyNFAy.1/3y
>Qeob^qColjqebPb^%M^oq0&yKyH^q^o%50+4)5-+2&yyNFAy.1/4y
QQeob^qColjqebPb^%M^oq0&yKyQlh$H^o%5.+1)5-+6&yyNFAy.1/4y

@Aob^jArpqfkqebPt^jmyKyHfiiqebTebimp^ilkdqebb^pq^kakloqebokpelobplcqeb_fdi^hbclo.-XPmb`hlcAob^jArpqZ^olrka%.3)12&yyNFAy...3y
@IfqqibJlopbipyKyRpbqebXCbi*Q^fkqbaJlopbipZqlcbbaqebQ^o^kqri^%3/)/0&)G^dr^o%32)//&)^ka@ol`lifph%3-)//&^qqebC^iiltP^k`qr^ovyyRy/0326yyNFAy611-y
@Ao^bkbqevpq@ovpq^ipyKyIllq3XAo^bkbqevpq@ovpq^ipZtef`e^obp`^qqboba^olrkaqebC^iiltP^k`qr^ov%3/)/1&yyNFAy.056y

QAo^bkbqevpq@ovpq^ipyKyJ^dqllo%/3+-)0.+2&yyNFAy.056y

EPqlk^oayRy3615yyNFAy.1/6y
QIfqqibJlopbipyKy@bopbfArphpfkdbo%14+4)21+5&yyNFAy611-y
QMllilcQb^opyKyCbi$wbori%14+6)21+6&yyNFAy.1/1y
>Qeb>q^i$^fBufibyKyCbi$wbori%14+6)21+6&yyNFAy.1/6y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
