DugisGuideViewer:RegisterGuide("Stranglethorn Vale (42-43)", "Dustwallow Marsh (43-44)", "Horde", "L", function()
return [[
AAA

C?llqv?^vyKy?obvh%13)21+4&yyWyPt^jmlcPlooltpyyNFAy/531y
QAob^jArpqfkqebPt^jmyKyHo^wbh%/4+-)44+/&yyNFAy...3y
>Qo^k$obhyKyHo^wbh%/4+-)44+/&yyNFAy/531y
>OrjlopcloHo^sbiyKyHo^wbh%/4+-)44+/&yyNFAy...4y
>Qeb?illap^fi?r``^kbbop%M^oq1&yKyCibbqJ^pqboPb^elok%/4+.)44+-&yyNFAy3-1y
>RmqlPkrccyKyAbbd%/4+-)44+0&yyNFAy254y
e?llqv?^vyKyFkkhbbmboPhfkaib%/4+.)44+0&yyNFAy3--y
>Sbkqrob@ljm^kvJfkfkdyKy@o^khCfwwib_r_%/4+.)44+0&yyNFAy3--y
>W^kwfi$pPb`obqyKy@o^khCfwwib_r_%/4+.)44+0&yyNFAy3/.y
>>hfofp_vqeb?rkaibyKyMofs^qbbo?il^ap%/3+4)43+1&yyNFAy3.4y
>SllallArbpyKyPb^TlicJ^`Hfkibv%/4+5)44+.&yyNFAy3-6y
>Pqlibv$pAb_qyKyPb^TlicJ^`Hfkibv%/4+5)44+.&yyNFAy/54/y
>Hbbm>kBvbLrqyKyAfwwvLkb*Bvb%/5+3)42+5&yyNFAy243y

@Qeb?illap^fi?r``^kbbop%M^oq0&yKyHfii.-?illap^fiPt^pe_r`hibop^ilkdqebplrqebokpeloblcPqo^kdibqelokS^ib%0.)5-&^kaobqofbsbqebX?illap^fi@e^oqpZ^kaqebX?illap^fiLoabopZtef`epm^tk^q%/5)50&)%/4)50&lo%0-)5-&yyNFAy3-1y
@RmqlPkrccyKyD^qebo.2XPkrccZlkqebplrqe`l^pqtef`eaolmpcoljqeb?illap^fimfo^qbp%0-)5-&yyNFAy254y
@Hbbm>kBvbLrqyKyQebMfo^qbppelriae^sbaolmmbaXAfwwv$pBvbZ_vklt)lobipbhbbmhfiifkdmfo^qbprkqfivlrcfkalkb%0-)5-&yyNFAy243y

@>hfofp_vqeb?rkaibyKyHfiiqebK^d^^qqebKbh$j^kfTbiipmofkd%/2)30&clo.-X>hfofpObbaZyyNFAy3.4y
@Jlh$qe^oafk$pBk`e^kqjbkq%M^oq1&yKyHfii.-K^d^Bumilobop^qqebKbh$j^kfTbiipmofkd%/2)30&+Q^hbqebXElivPmofkdT^qboZcoljqebtbii%/6)3/&yyNFAy240y

@O^mqloJ^pqbov%M^oq1&yKyHfiiQbqefp%/5)11&yyNFAy.64y
@SllallArbpyKyXJ^rov$p@ir__baCllqZ^kaXGlk*Glk$pPmvdi^ppZ^ob_lqeclrkafkqebOrfkplcGr_rt^i%02)2-&+X@er`hv$pErdbOfkdZ`^k_bclrkafkqebOrfkplc>_lo^w%1-)25&yyNFAy3-6y
@W^kwfi$pPb`obqyKyHfiiW^kwfijl_p^qqebOrfkplc>_lo^wclo./XW^kwfi$pJfuqrobZyyNFAy3/.y
@Sbkqrob@ljm^kvJfkfkdyKyHfiiqebDl_ifkp%1.)1.&clo.-XPfkdfkd?irb@ovpq^ipZyyNFAy3--y

QO^mqloJ^pqbov%M^oq1&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.64y
>?fdD^jbErkqboyKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy/-5y

QJlh$qe^oafk$pBk`e^kqjbkq%M^oq1&yKyC^oPbboJlh$qe^oafk%0/+.)/6+/&yyNFAy240y
@?fdD^jbErkqboyKyHfiiHfkd?^kd^i^pe%05)02&^kaq^hbqebXEb^alc?^kd^i^peZyyNFAy/-5y
Q?fdD^jbErkqboyKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy/-5y

E?llqv?^vyRy3615y
QSbkqrob@ljm^kvJfkfkdyKy@o^khCfwwib_r_%/4+.)44+0&yyNFAy3--y
QW^kwfi$pPb`obqyKy@o^khCfwwib_r_%/4+.)44+0&yyNFAy3/.y
QRmqlPkrccyKyAbbd%/4+-)44+0&yyNFAy254y
QQeb?illap^fi?r``^kbbop%M^oq1&yKyCibbqJ^pqboPb^elok%/4+.)44+-&yyNFAy3-1y
Q>hfofp_vqeb?rkaibyKyMofs^qbbo?il^ap%/3+4)43+1&yyNFAy3.4y
QSllallArbpyKyPb^TlicJ^`Hfkibv%/4+5)44+.&yyNFAy3-6y
QHbbm>kBvbLrqyKyAfwwvLkb*Bvb%/5+3)42+5&yyNFAy243y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
