DugisGuideViewer:RegisterGuide("Dustwallow Marsh (43-44)", "Tanaris (44-45)", "Horde", "L", function()
return [[
AAA

_O^q`ebqyKyQ^hbqeb_l^qqlO^q`ebq%/3)40+/&yyWyPqo^kdibqelokS^ibyyNFAy..33y
C?o^`hbkt^iiSfii^dbyKy?o^dlh%30+.)04+/&yyWyQeb?^oobkpyyNFAy..33y
>LsboiloaJlh$Jlolhh$p@lk`bokyKyLsboiloaJlh$Jlolhh%03+0)0.+2&yyNFAy..33y
>Fabkqfcvfkdqeb?ollayKyAo^w$Wfi_%04+.)00+-&yyNFAy..36y
>>ojvlcqeb?i^`hAo^dlkyKyQe^od%04+0)0.+1&yyNFAy..35y
>NrbpqflkfkdObbqebyKyLdolk%1-+6)03+4&yyNFAy./40y
@NrbpqflkfkdObbqebyKyCliiltLodolk%1-+6)03+4&yyNFAy./40y
QNrbpqflkfkdObbqebyKyHold%03+1)0.+5&yyNFAy./40y

CJrapmol`hbqyKyPe^oaf%02+3)0.+5&yyNFAy...25y
>?illacbkCb^qebopyKy?oldd%1.+5)40+4&yyNFAy...25y
>T>KQBA7Dlob`i^tqebO^sbklrpyKyT^kqbaMlpqbo%1.+5)40+.&yyNFAy...51y
>@^q`e^Ao^dlk_vqebQ^fiyKyDfwwfuDofjbdrodib%1.+2)40+-&yyNFAy../.4y

@?illacbkCb^qebopyKyHfiiqebO^mqlop^qqeb?illacbk?rooltclo2X?illacbkCb^qebopZ^olrka%0/)33&yyNFAy...25y
@T>KQBA7Dlob`i^tqebO^sbklrpyKyHfiiDlob`i^tqebO^sbklrp%0/+1)33+0&yyNFAy...51y

QT>KQBA7Dlob`i^tqebO^sbklrpyKyAo^wwfqAofms^isb%1.+6)4/+2&yyNFAy...51y
Q?illacbkCb^qebopyKy?oldd%1.+5)40+4&yyNFAy...25y
>?^kkbolcqebPqlkbj^riyKy?oldd%1.+5)40+4&yyNFAy...3-y
>QebBppbk`blcBkjfqvyKy?oldd%1.+5)40+4&yyNFAy...3.y

KMf`hrmqebDoldyKy>qqebAbklcCi^jb%05+4)32+3&+J^hbprobvlrrpbqebqlqbjlk^kvao^dlkhfk^cqbovlrhfiiqebjcloQebBppbk`blcBkjfqvyyNFAy..33yyNLyJlh$Jlolhh$pDold7.,.yyRy00-55y
KMf`hrmqebPqolkd_luyKyFkpfabqeb`^sb%%03+3)36+2&yyNFAy..33yyNLyJlh$Jlolhh$pPqolkd_lu7.,.yyRy00-55y
@?^kkbolcqebPqlkbj^riyKyObqofbsbqebXPqlkbj^ri?^kkboZtef`efpfkqebp^jb`^sb^pqebPqolkd_lu%05+.)36+2&yyNFAy...3-yyRy00-55y
@LsboiloaJlh$Jlolhh$p@lk`bokyKy@liib`qqebXJlh$Jlolhh$pPkrccZfkqebPqlkbj^riOrfkp%11+2)33+.&yyNFAy..33yyRy00-55y

@J^odPmb^hpyKyHfiiJrohpebiijl_prkqfiqebvaolmqebXGbtbibaMbka^kqZ%22)3/&yyNFAy./3.y

@QebBppbk`blcBkjfqvyRy00-55yyKyFcvlre^sbk$q^iob^av)`ljmibqbqefpnrbpq_^`h^qqebAbklcCi^jb_vrpfkdX?oldd$pQlqbjZlkqeb`lompbplcqebCfobj^kbjl_p%06)32&yyNFAy...3.yyRy00-55y
@>ojvlcqeb?i^`hAo^dlkyKyHfii.-Cfobj^kbP`lrqp).-Cfobj^kb>peQ^fip)^ka2Cfobj^kbP`^ib_^kbp^qqebAbklcCi^jbp%06)32&yyNFAy..35y

OJrapmol`hbqyKyOrkqlJrapmol`qba%1.+5)40+4&yyNFAy...26y
Q?^kkbolcqebPqlkbj^riyKy?oldd%1.+5)40+4&yyNFAy...3-y
QQebBppbk`blcBkjfqvyKy?oldd%1.+5)40+4&yyNFAy...3.y
>PmfofqplcPqlkbj^riEliayKy?oldd%1.+5)40+4&yyNFAy...26y

@PmfofqplcPqlkbj^riEliayKyRpbqebXBkbodfwbaQlqbjZkb^oqeb_lkbpkloqe^qqebPqlkbj^riOrfkp^kahfii.-lcqebpmfofqpqe^q^mmb^oyyRy00-6.yyNFAy...26y

QPmfofqplcPqlkbj^riEliayKy?oldd%1.+5)40+4&yyNFAy...26y
>@e^iibkdbqlqeb?i^`hCifdeqyKy?oldd%1.+5)40+4&yyNFAy...3/y

@@e^iibkdbqlqeb?i^`hCifdeqyKyMi^kqqebXPqlkbj^ri?^kkboZ^kahfiiqebao^dlkgrpqlrqpfabqebbkqo^k`bqlqebLkvuf^$pI^fo%2/+.)42+4&yyRy00-62yyNFAy...3/y
@@^q`e^Ao^dlk_vqebQ^fiyKyD^qebo5XTvojq^fiZclrka_bqtbbkLkvuf^$pI^fo^kaJrapmol`hbq%13)5-&yyNFAy../.4y
@Fabkqfcvfkdqeb?ollayKyHfiiTebimp^olrka%1/)45&clo4XPb^ofkdQlkdrbZ^ka4XPb^ofkdEb^oqZyyNFAy..36y

Q@e^iibkdbqlqeb?i^`hCifdeqyKy?oldd%1.+5)40+4&yyNFAy...3/y
Q@^q`e^Ao^dlk_vqebQ^fiyKyDfwwfuDofjbdrodib%1.+2)40+-&yyNFAy../.4y

C?o^`hbkt^iiSfii^dbyKyAvpifuPfisbodor_%1/+6)4/+2&yyNFAy./3/y
QJ^odPmb^hpyKyK^wbbo?illamfhb%02+0)0-+4&yyNFAy./3.y
>ObmloqqlWloyKyK^wbbo?illamfhb%02+0)0-+4&yyNFAy./3/y
QLsboiloaJlh$Jlolhh$p@lk`bokyKyLsboiloaJlh$Jlolhh%03+0)0.+2&yyNFAy..33y
Q>ojvlcqeb?i^`hAo^dlkyKyQe^od%04+0)0.+1&yyNFAy..35y
QFabkqfcvfkdqeb?ollayKyAo^w$Wfi_%04+.)00+-&yyNFAy..36y
>Qeb?ollalcLkvuf^%M^oq.&yKyAo^w$Wfi_%04+.)00+-&yyNFAy..4-y
QQeb?ollalcLkvuf^%M^oq.&yKyLsboiloaJlh$Jlolhh%03+0)0.+2&yyNFAy..4-y
>Qeb?ollalcLkvuf^%M^oq/&yKyLsboiloaJlh$Jlolhh%03+0)0.+2&yyNFAy..4.y
QQeb?ollalcLkvuf^%M^oq/&yKyAo^w$Wfi_%04+.)00+-&yyNFAy..4.y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
