DugisGuideViewer:RegisterGuide("Tanaris (44-45)", "Feralas (45-46)", "Horde", "L", function()
return [[
AAA

CD^adbqw^kyKyPe^oaf%02+3)0.+5&yyWyArpqt^iiltJ^opeyyNFAy/45.y
>T>KQBA7@^ifmeP`lomfapqfkdyKyT^kqbaMlpqbo%2/+-)/4+-&yyNFAy/45.y
>T>KQBA7>kaobCfob_b^oayKyT^kqbaMlpqbo%2/+-)/4+-&yyNFAy/542y
QQo^k$obhyKyQo^k$obh%2.+3)/3+5&yyNFAy/531y
>D^adbqw^kT^qboProsbvyKyPbkfloProsbvloCfwwibaltpbo%2-+/)/4+2&yyNFAy66/y
>T^pqbt^kaboGrpqf`byKy@efbcBkdfkbbo?fidbtefwwib%2/+1)/5+2&yyNFAy.36-y
>T^qboMlr`e?lrkqvyKyPmfdlqLmbo^qloIrdirkhbq%2/+1)/5+2&yyNFAy.545y
eD^adbqw^kyKyFkkhbbmboCfwwdofj_ib%2/+2)/4+6&yyNFAy..55y

OJfo^dbO^`bt^vyKyFkqebPefjjbofkdCi^qp%44+5)44+0&yyWyQelrp^kaKbbaibpyyNFAy..55y
QOrjlopcloHo^sbiyWyQelrp^kaKbbaibpyyKyHo^sbiHl^i_b^oa%44+5)44+/&yyNFAy...4y
QKbtpcloCfwwibyWyQelrp^kaKbbaibpyyKyCfwwib?o^pp_liqp%45+-)44+.&yyNFAy..04y
QO^wwbof`$pQtb^hfkdyWyQelrp^kaKbbaibpyyKyO^wwbof`%5-+0)43+.&yyNFAy..54y
>P^cbqvCfopqyWyQelrp^kaKbbaibpyyKyO^wwbof`%5-+0)43+.&yyNFAy..55y
>HbbmfkdM^`byWyQelrp^kaKbbaibpyyKyMlwwfh%5-+.)42+6&yyNFAy..6-y
QHbbmfkdM^`byWyQelrp^kaKbbaibpyyKyOfwwib$pRkdr^oabaMi^kp%44+0)44+2&yyNFAy..6-y
>Ofwwib$pP`ebj^qf`pyWyQelrp^kaKbbaibpyyKyOfwwib$pRkdr^oabaMi^kp%44+0)44+2&yyNFAy..61y
>?^`hql?llqv?^vyWyQelrp^kaKbbaibpyyKyHo^sbiHl^i_b^oa%44+5)44+/&yyNFAy...5y
QOfwwib$pP`ebj^qf`pyWyQelrp^kaKbbaibpyyKyMlwwfh%5-+.)42+6&yyNFAy..61y

OD^adbqw^kyKyOrk_^`hqlD^adbqw^k%2.+-)/4+/&yyNFAy..56y
QP^cbqvCfopqyKyPeobbs%2.+-)/4+/&yyNFAy..55y
>P^cbqvCfopq%M^oq/&yKyPeobbs%2.+-)/4+/&yyNFAy..56y
QP^cbqvCfopq%M^oq/&yWyQelrp^kaKbbaibpyyKyO^wwbof`%5-+0)43+.&yyNFAy..56y
ED^adbqw^kyRy3615yyNFAy5032y

OPqb^jtebbaibMloqyKyOrkqlPqb^jtebbaibMloq%33+2)//+0&yyNFAy5032y
>Mfo^qbE^qp>elvyKyE^rdeqvJlafpqb%33+2)//+0&yyNFAy5032y
>P`obb`eboPmfofqpyKyVbe$hfkv^%33+6)//+1&yyNFAy02/-y
>Plrqepb^Pe^hbaltkyKyPb`rofqv@efbc?fidbtefwwib%34+-)/0+6&yyNFAy5033y
QPqlibv$pAb_qyKyPqlibv%34+.)/0+6&yyNFAy/54/y
>Pqlibv$pPefmjbkqyKyPqlibv%34+.)/0+6&yyNFAy/540y

HT^pqbt^kabopyKyHfiiqebT^pqbt^kabojl_p%3/)02&clo2XT^pqbt^kaboT^qboMlr`eZyyNFAy.545yyIy51502y
@T^pqbt^kaboGrpqf`byKyQ^hbaltk.-T^pqbt^kabo?^kafqp^kaQefbsbpplrqelcPqb^jtebbaibMloq%3/)02&yyNFAy.36-y

@T>KQBA7>kaobCfob_b^oayKyHfii>kaobCfob_b^oa^qqebIlpqOfddbo@lsb^kaq^hbXCfob_b^oa$pEb^aZ%40+1)14+.&yyNFAy/542y
@Pqlibv$pPefmjbkqyKyDbqXPqlibv$pPefmjbkqZcoljrmpq^fopfkqebkloqebok_rfiafkd%4/+.)13+4&yyNFAy/540y
@Mfo^qbE^qp>elvyKyHfiiqebMfo^qbp%4-)12&^kad^qebo/-XPlrqepb^Mfo^qbE^qpZyyNFAy5032y
@Plrqepb^Pe^hbaltkyKyHfii.-Plrqepb^Mfo^qbp).-Plrqepb^Cobb_llqbop).-Plrqepb^Al`hTlohbop^ka.-Plrqepb^Pt^pe_r`hibop%4-)12&+T^q`eclofqbjaolmXPefmP`ebaribZqlpq^oqi^qbonrbpqyyNFAy5033y

ED^adbqw^kyRy3615yyKyEb^oqeloork_^`hyyNFAy.36.y
QT^qboMlr`e?lrkqvyKyPmfdlqLmbo^qloIrdirkhbq%2/+1)/5+2&yyNFAy.545y
QT^pqbt^kaboGrpqf`byKy@efbcBkdfkbbo?fidbtefwwib%2/+1)/5+2&yyNFAy.36-y
>JlobT^pqbt^kaboGrpqf`byKy@efbcBkdfkbbo?fidbtefwwib%2/+1)/5+2&yyNFAy.36.y
@D^adbqw^kT^qboProsbvyKyRpbqebXRkq^mmbaAltpfkdTfadbqZ^qqebt^qbomllikb^oqebP^kaplooltT^q`eql`liib`qqebP^jmib%05)/6&yyRy5251yyNFAy66/y
QD^adbqw^kT^qboProsbvyKyPbkfloProsbvloCfwwibaltpbo%2-+/)/4+2&yyNFAy66/y

QMfo^qbE^qp>elvyKyE^rdeqvJlafpqb%33+2)//+0&yyNFAy5032y
QPqlibv$pPefmjbkqyKyPqlibv^q%34+-)/1+-&yyNFAy/540y
QPlrqepb^Pe^hbaltkyKyPb`rofqv@efbc?fidbtefwwib%34+-)/0+6&yyNFAy5033y
>AbifsboqlJ^`HfkibvyKyPqlibv%34+.)/0+6&yyNFAy/541y
QT>KQBA7>kaobCfob_b^oayKyPb`rofqv@efbc?fidbtefwwib%34+-)/0+6&yyNFAy/542y
>PefmP`ebaribpyRy6/2-yyLyyNFAy/543yyKyQebfqbjXPefmP`ebaribZpq^oqpnrbpq*aolmmba_vMfo^qbpfkIlpqOfddbo`lsb%40)14&y
QPefmP`ebaribpyLyyKyPb`rofqv@efbc?fidbtefwwib%34+-)/0+6&yyNFAy/543y

@JlobT^pqbt^kaboGrpqf`byKyQ^hbaltk.-T^pqbt^kaboPe^altJ^dbp)5T^pqbt^kaboOldrbp^ka3T^pqbt^kabo>pp^ppfkp%26)04&yyNFAy.36.y
@T>KQBA7@^ifmeP`lomfapqfkdyKyHfii@^ifmeP`lomfapqfkdteljm^qolipkb^oqebt^qboqltbop%3/)03&yyNFAy/45.y

ED^adbqw^kyRy3615yyKyEb^oqeloork_^`hy
QJlobT^pqbt^kaboGrpqf`byKy@efbcBkdfkbbo?fidbtefwwib%2/+1)/5+2&yyNFAy.36.y
KP^sb^iiT^pqbt^kaboT^qboMlr`ebpyNFAy/45.y
QT>KQBA7@^ifmeP`lomfapqfkdyKy@efbcBkdfkbbo?fidbtefwwib%2/+1)/5+2&yyNFAy/45.y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
