DugisGuideViewer:RegisterGuide("Feralas (45-46)", "Azshara (46-47)", "Horde", "L", function()
return [[
AAA

CCobbtfkaMlpqyKy?rihobhO^dbcfpq^q%2.+3)/2+2&yyWyQ^k^ofpyyNFAy/640y
O@^jmJlg^`ebyKyOrkql@^jmJlg^`eb%43+-)1/+5&tbpqlcCbo^i^pyyNFAy/640y
>>Kbt@il^h$pPebbkyKyHorbdPhriipmifqqbo%43+-)1/+5&yyNFAy/640y
>QebLdobplcCbo^i^p%M^oq.&yKy'T^kabofkdKM@'OlhLoe^k%42+2)10+4&%40+0)11+5&yyNFAy/642y
>Dloarkkf@l_^iqyKyLotfkDfwwjf`h%42+4)10+0&yyNFAy/654y
>T^olkqebTllam^tyKyE^alhbkPtfcqpqofabo%41+6)1/+2&yyNFAy/53/y
>QebJ^ohlcNr^ifqvyKyG^kdaloPtfcqpqofabo%41+2)1/+6&yyNFAy/5//y
>>Pqo^kdbObnrbpqyKyTfq`eAl`qloRwbo$f%41+2)10+1&yyNFAy0./.y
e@^jmJlg^`ebyKyFkkhbbmboDobri%41+5)12+.&yyNFAy/645y

@T^olkqebTllam^tyKyHfiiqebTllam^tkloqelc@^jmJlg^`eb%4.)04&clo.-XTllam^tDkliiJ^kbZyyNFAy/53/y
@Dloarkkf@l_^iqyKyRpbXLotfk$pPelsbiZkb^oqebjlrkapfkqebkloqe^kamf`hrm./XDloarkkf@l_^iqZ^olrka%42)0.&yyRy6133yyNFAy/654y
@QebLdobplcCbo^i^p%M^oq.&yKyHfii.-DloarkkfLdobp).-DloarkkfLdob*J^df)^ka2Dloarkkf?orqbp%42)0-&yyNFAy/642y
>QebDloarkkfP`oliiyKyColj^p`oliiivfkdlkqebcillo%5-)01&)%41)/4&lo%42)/5&yyRy604-yyNFAy/645y
@>Kbt@il^h$pPebbkyKyHfiiqebPmofqbA^oqboptbpqlc@^jmJlg^`eb%35)15&clo.-XFofabp`bkqPmofqbA^oqboTfkdZyyNFAy/640y

QT^olkqebTllam^tyKyE^alhbkPtfcqpqofabo%41+6)1/+2&yyNFAy/53/y
>>ime^PqofhbyKyE^alhbkPtfcqpqofabo%41+6)1/+2&yyNFAy/530y
QDloarkkf@l_^iqyKyLotfkDfwwjf`h%42+4)10+0&yyNFAy/654y
QQebLdobplcCbo^i^p%M^oq.&yKyOlhLoe^k%42+2)10+4&yyNFAy/642y
>QebLdobplcCbo^i^p%M^oq/&yKyOlhLoe^k%42+2)10+4&yyNFAy/65-y
QQebDloarkkfP`oliiyKyOlhLoe^k%42+2)10+4&yyNFAy/645y
>A^oh@bobjlkvyKyOlhLoe^k%42+2)10+4&yyNFAy/646y
Q>Kbt@il^h$pPebbkyKyHorbdPhriipmifqqbo%43+-)1/+5&yyNFAy/640y
>>DofjAfp`lsbov%M^oq.&yKyHorbdPhriipmifqqbo%43+-)1/+5&yyNFAy/641y

@>ime^PqofhbyKyHfii2Tllam^t>ime^pplrqetbpqlc@^jmJlg^`eb%4/)23&yyNFAy/530y
Q>ime^PqofhbyKyE^alhbkPtfcqpqofabo%41+6)1/+2&yyNFAy/530y
>Tllam^tFksbpqfd^qflkyKyE^alhbkPtfcqpqofabo%41+6)1/+2&yyNFAy/6-/y
@Tllam^tFksbpqfd^qflkyKyCfkaqebdklii_^qqibmi^kplk^`o^qb%4.+3)22+6&yyNFAy/6-/y
QTllam^tFksbpqfd^qflkyKyTllam^t?^qqibJ^m%4.+3)22+6&yyNFAy/6-/y
>Qeb?^qqibMi^kpyKyTllam^t?^qqibJ^m%4.+3)22+6&yyNFAy/6-0y

@>DofjAfp`lsbov%M^oq.&yKyHfiiqebDofjqlqbjpKloqetbpqlc@^jmJlg^`ebclo/-XDofjqlqbjElokpZ%33)05&yyNFAy/641y

E@^jmJlg^`ebyRy3615yyNFAy440-y
QQeb?^qqibMi^kpyKyE^alhbkPtfcqpqofabo%41+6)1/+2&yyNFAy/6-0y
>Wrhh$^peFkcbpq^qflkyKyE^alhbkPtfcqpqofabo%41+6)1/+2&yyNFAy440-y
>Pqfkdi^peboyKyE^alhbkPtfcqpqofabo%41+6)1/+2&yyNFAy440.y
Q>DofjAfp`lsbov%M^oq.&yKyHorbdPhriipmifqqbo%43+-)1/+5&yyNFAy/641y
>>DofjAfp`lsbov%M^oq/&yKyHorbdPhriipmifqqbo%43+-)1/+5&yyNFAy/643y

@Pqfkdi^peboyKyAbcb^qPqfkdi^pebofkqebTofqefkdAbbm^kaq^hbefpXPqfkdi^pebo$pDi^kapZ%41)3/&yyNFAy440.y
@Wrhh$^peFkcbpq^qflkyKyHfiiqebWrhh$^peT^pmp^qqebTofqefkdAbbmclo/-XWrhh$^pe@^o^m^`bZ%41)3/&yyNFAy440-y
@P`obb`eboPmfofqpyKyHfiiqebP`obb`ebopplrqelcAfobJ^ri%23)2-&^karpbqebXVbe$hfkv^$p?o^j_ibZlkqebfo`lompbpql`liib`q0lcqebfopmfofqpyyRy.-366yyNFAy02/-y
@QebLdobplcCbo^i^p%M^oq/&yKyHfii.-DloarkkfPe^j^k).-DloarkkfT^oil`hp^ka2DloarkkfJ^ribopplrqelcAfobJ^ri%26)35&yyNFAy/65-y
@A^oh@bobjlkvyKyHfiiDloarkkfJ^dbpcloqebXDloarkkfLo_Z%26)35&yyNFAy/646y
KMf`hrm^EfmmldovmeBddyKy>olrka%22)43&fkkbpqpyyIy5231yyNFAy/5//y
@QebJ^ohlcNr^ifqvyKyHfiiVbqfpplrqetbpqlcAfobJ^riclo.-XQef`hVbqfEfabpZ%22)23&yyNFAy/5//y

QQebJ^ohlcNr^ifqvyKyG^kdaloPtfcqpqofabo%41+2)1/+6&yyNFAy/5//y
>QebPrkhbkQbjmibyKyTfq`eAl`qloRwbo$f%41+2)10+1&yyNFAy005-y
QPqfkdi^peboyKyE^alhbkPtfcqpqofabo%41+6)1/+2&yyNFAy440.y
QWrhh$^peFkcbpq^qflkyKyE^alhbkPtfcqpqofabo%41+6)1/+2&yyNFAy440-y
>Wrhh$^peObmloqyKyE^alhbkPtfcqpqofabo%41+6)1/+2&yyNFAy440/y
QQebLdobplcCbo^i^p%M^oq/&yKyOlhLoe^k%42+2)10+4&yyNFAy/65-y
QA^oh@bobjlkvyKyOlhLoe^k%42+2)10+4&yyNFAy/646y
>QebDloarkkfLo_yKyOlhLoe^k%42+2)10+4&yyNFAy0--/y

CLodofjj^oyKyPevk%42+2)11+0&yyNFAy316y
eLodofjj^oyKyFkkhbbmboDovpeh^%21+.)35+3&yyWyLodofjj^oyyNFAy316y
QWrhh$^peObmloqyWyLodofjj^oyyKyWfiwf_fkAorjilob)fkQebAo^d%23+2)13+2&yyNFAy440/y
>OfmmibOb`lsbov%M^oq.&yWyLodofjj^oyyKyAo^kAolccbop%26+1)03+6&yyNFAy316y
QOfmmibOb`lsbov%M^oq.&yWyLodofjj^oyyKyJ^iqlkAolccbop%26+1)03+6&yyNFAy316y
>OfmmibOb`lsbov%M^oq/&yWyLodofjj^oyyKyJ^iqlkAolccbop%26+1)03+6&yyNFAy32-y
QM^oqplcqebPt^ojyWyLodofjj^oyyKy?bidoljOl`hj^ri)fkqebS^iibvlcElklo%42)01&yyNFAy..51y
Q>DofjAfp`lsbov%M^oq/&yWyLodofjj^oyyKy?bidoljOl`hj^ri%42)01&yyNFAy/643y
>?bqo^vbayWyLodofjj^oyyKy?bidoljOl`hj^ri%42)01&yyNFAy02-1y
Q>Pqo^kdbObnrbpqyWyLodofjj^oyyKyKbborCfob_i^ab)fkqeb@ibcqlcPe^alt%16+3)2-+3&yyNFAy0./.y
QObmloqqlWloyWyLodofjj^oyyKyWloIlkbqobb)fkqebS^iibvlcTfpalj%05+6)05+1&yyNFAy./3/y
>Pbosf`bqlqebEloabyWyLodofjj^oyyKyWloIlkbqobb)fkqebS^iibvlcTfpalj%05+6)05+1&yyNFAy421.y
QPbosf`bqlqebEloabyWyLodofjj^oyyKyWloIlkbqobb%05+6)05+1&yyNFAy421.y
QQebDloarkkfLo_yWyLodofjj^oyyKyRqebi$k^v)fkqebS^iibvlcPmfofqp%06+.)53+-&yyNFAy0--/y

>>Alk^qflklcPfih%A^ohpmb^oQoliip&yWyLodofjj^oyyKySbebk^%05+-)53+1&yyNFAy4501y
Q>Alk^qflklcPfih%A^ohpmb^oQoliip&yWyLodofjj^oyyKySbebk^%05+-)53+1&yyNFAy4501y
>>Alk^qflklcJ^dbtb^sb%A^ohpmb^oQoliip&yWyLodofjj^oyyKySbebk^%05+-)53+1&yyNFAy4502y
Q>Alk^qflklcJ^dbtb^sb%A^ohpmb^oQoliip&yWyLodofjj^oyyKySbebk^%05+-)53+1&yyNFAy4502y

>>Alk^qflklcPfih%Lodofjj^o&yWyLodofjj^oyyKyO^pelk^Pqo^di^pe%30+1)2.+.&yyNFAy45/4y
Q>Alk^qflklcPfih%Lodofjj^o&yWyLodofjj^oyyKyO^pelk^Pqo^di^pe%30+1)2.+.&yyNFAy45/4y
>>Alk^qflklcJ^dbtb^sb%Lodofjj^o&yWyLodofjj^oyyKyO^pelk^Pqo^di^pe%30+1)2.+.&yyNFAy450.y
Q>Alk^qflklcJ^dbtb^sb%Lodofjj^o&yWyLodofjj^oyyKyO^pelk^Pqo^di^pe%30+1)2.+.&yyNFAy450.y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
