DugisGuideViewer:RegisterGuide("Azshara (46-47)", "Stranglethorn Vale (47)", "Horde", "L", function()
return [[
AAA

CPmifkqboqobbMlpqyKyCivql>pebks^ib)Alo^p%12+/)31&yyWyLodofjj^oyyNFAy2202y
O>wpe^o^yKyOrkb^pqql>wpe^o^%..+1)45+/&yyNFAy2202y

>Pmfofqr^iRkobpqyKyIle$^qr%..+1)45+/&yyNFAy2202y
>>I^kaCfiibatfqeE^qobayKyIle$^qr%..+1)45+/&yyNFAy2203y
@Pmfofqr^iRkobpqyKyAbpqolv3Efde_lokb>mm^ofqflkp^ka3Efde_lokbIf`eifkdp^qqebPe^altplkdPeofkb%.4)33&yyNFAy2202y
@>I^kaCfiibatfqeE^qobayKyHfii3E^ia^ooP^qvo)/E^ia^ooQof`hpqbop^ka/E^ia^ooCbiptlok^_fqjlobkloqe%/-)32&yyNFAy2203y
QPmfofqr^iRkobpqyKyIle$^qr%..+1)45+/&yyNFAy2202y
Q>I^kaCfiibatfqeE^qobayKyIle$^qr%..+1)45+/&yyNFAy2203y

OS^ilojlhyKyKloqelcqebol^a)lkqebjlrkq^fk$pbadb%/.)2/&yyNFAy0235y
Q?bqo^vbayKy>d$qlo?illacfpq%//+0)2.+2&yyNFAy02-1y

ELodofjj^oyRy3615yyNFAy0235y
CQfofpc^iDi^abpyKyQ^hbqebwbmmbifklrqpfabLodofjj^o%2-+5).0+4&qlQfofpc^iDi^abp%Rkabo`fqv&yyWyArolq^oyyNFAy0235y
ORkabo`fqvyKyOrkqlRkabo`fqv%3.+6)35+.&yyWyQfofpc^iDi^abpyyNFAy0235y
>Pbbmfkd@loormqflk%M^oq.&yWyRkabo`fqvyyKy@ebjfpq@rbiv)>mlqeb`^ofrjNr^oqbo%15+1)4.+5&yyNFAy0235y
>Boo^kaclo>mlqeb`^ovWfkdb%M^oq.&yWyRkabo`fqvyyKy>mlqeb`^ovWfkdb%16+6)35+1&yyNFAy/0/y
QBoo^kaclo>mlqeb`^ovWfkdb%M^oq.&yWyRkabo`fqvyyKy>ibpp^kaolIr`^%24+1)23+6&yyNFAy/0/y
>Boo^kaclo>mlqeb`^ovWfkdb%M^oq/&yWyRkabo`fqvyyKy>ibpp^kaolIr`^%24+1)23+6&yyNFAy/05y
QBoo^kaclo>mlqeb`^ovWfkdb%M^oq/&yWyRkabo`fqvyyKy>mlqeb`^ovWfkdb%16+6)35+1&yyNFAy/05y
>FkqlqebCfbiayWyRkabo`fqvyyKy>mlqeb`^ovWfkdb%16+6)35+1&yyNFAy/10y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
