DugisGuideViewer:RegisterGuide("Searing Gorge (47-48)", "Swamp of Sorrows (48-49)", "Horde", "L", function()
return [[
AAA

CH^od^qeyKyCivql?^ai^kap)Dofkdbo%/3+6)44&yyWyPqo^kdibqelokS^ibyyNFAy1116y
OPb^ofkdDlodbyKyOrktbpqqlPb^ofkdDlodb%.)3/&yyWy?^ai^kapyyNFAy1116y
>@^rdeqyKyTllabkLrqelrpb%32)3/&yyNFAy1116y
Q@^rdeqyKyTllabkLrqelrpb%32)3/&yyNFAy1116y
>IbadbocoljQ^k^ofpyKyTllabkLrqelrpb%32)3/&yyNFAy112-y
KIllqqebibadboyNFAy112-yyNLyDllapqbbiIbadbo7.,.y
KHfiiDi^pptb_PmfabopyNFAy112-yyNLyPlifa@ovpq^iIbdPe^cq7/-,/-y
>AfsfkbObqof_rqflkyKyH^i^o^kTfka_i^ab%06+-)05+6&yyNFAy011.y
QAfsfkbObqof_rqflkyKyH^i^o^kTfka_i^ab%06+-)05+6&yyNFAy011.y
>QebCi^tibppCi^jbyKyH^i^o^kTfka_i^ab%06+-)05+6&yyNFAy011/y
OQelofrjMlfkqyKyOrkqlQelofrjMlfkq%01+6)0-+5&yyNFAy44/5y
>PQLIBK7PjfqefkdQrvbob^kaIllhlrq$pPmvdi^ppyKyT^kqba,Jfppfkd,Ilpq#Clrka%04+3)/3+3&yyNFAy44/5y
>GL?LMMLOQRKFQV7@riifkdqeb@ljmbqfqflkyKyT^kqba,Jfppfkd,Ilpq#Clrka%04+3)/3+3&yyNFAy44/6y
>@ropbQebpbC^qCfkdbopyKyE^kpbiEb^sve^ka%05+2)/4+6&yyNFAy44/0y
>CfbovJbk^`byKyE^kpbiEb^sve^ka%05+2)/4+6&yyNFAy44/1y
>Fk`bkalp^rop<Te^qbsbolp^rofpJlobIfhbFqyKyE^kpbiEb^sve^ka%05+2)/4+6&yyNFAy44/4y

@CfbovJbk^`byKyHfii/-Dob^qboI^s^Pmfabop%/5)21&yyNFAy44/1y
@@ropbQebpbC^qCfkdbopyKyHfii/-Eb^svT^oDlibjp)grpqplrqelcQelofrjMlfkq%1/)10&yyNFAy44/0y
@PQLIBK7PjfqefkdQrvbob^kaIllhlrq$pPmvdi^ppyKyHfiiA^ohFolkPqb^jpjfqepqlqebplrqe%06)16&cloqebXPjfqefkdQrvbobZ+>kahfiiA^ohFolkIllhlrqp^qqebqltbop%00)20&)%03)26&)%11)3.&)%16)22&cloqebXIllhlrq$pPmvdi^ppZyyNFAy44/5y
@QebCi^tibppCi^jbyKyHfiiJ^dj^Bibjbkq^ip)CfobBibjbkq^ip^kaEb^svT^oDlibjpclo1XEb^oqlcCi^jbZ^ka1XDlibjLfiZyyNFAy011/y

QQebCi^tibppCi^jbyKyH^i^o^kTfka_i^ab%06+-)05+6&yyNFAy011/y
>ClodfkdqebPe^cqyKyH^i^o^kTfka_i^ab%06+-)05+6&yyNFAy0110y

>QebHbvqlCobbaljyLyyRy..5.5yyKyRpbXDofjbpfiqLrqelrpbHbvZyyNFAy112.y
QQebHbvqlCobbaljyLyyKyTllabkLrqelrpb%32)3/&yyNFAy112.y

@GL?LMMLOQRKFQV7@riifkdqeb@ljmbqfqflkyKyPi^v.2A^ohFolkQ^phj^pqbop^ka.2A^ohFolkPi^sbopplrqelcQelofrjMlfkq^kafkpfabqeb@^riaolk%11)11&yyNFAy44/6y
@ClodfkdqebPe^cqyKyHfii^kvhfkalcA^ohFolkjl_pclo5XQelofrjMi^qbaA^ddbopZ^olrka%11)11&yyNFAy0110y
@Fk`bkalp^rop<Te^qbsbolp^rofpJlobIfhbFqyKyGrjmaltk^q%14)13&)dlfkqlqeb`^sb^kahfii/-Fk`bkalp^ropyyNFAy44/4y

QClodfkdqebPe^cqyKyH^i^o^kTfka_i^ab%06+-)05+6&yyNFAy0110y
>QebCi^jb$p@^pfkdyKyH^i^o^kTfka_i^ab%06+-)05+6&yyNFAy012/y
@QebCi^jb$p@^pfkdyKyHfiiqebQtfifdeqjl_p^olrka%/1)03&^kaillq^XPvj_lilcO^dk^olpZyyNFAy012/y
QQebCi^jb$p@^pfkdyKyH^i^o^kTfka_i^ab%06+-)05+6&yyNFAy012/y
>QebQlo`elcObqof_rqflk%M^oq.&yKyH^i^o^kTfka_i^ab%06+-)05+6&yyNFAy0120y
@QebQlo`elcObqof_rqflk%M^oq.&yKy>cqbomf`hfkdrmqefpnrbpq)pq^vkb^oH^i^o^kTfka_i^ab%06+-)05+6&+Eb`ob^qbpqebqlo`etfqefk^jfkrqbyyNFAy0120y
QQebQlo`elcObqof_rqflk%M^oq.&yKyH^i^o^kTfka_i^ab%06+-)05+6&yyNFAy0120y
>QebQlo`elcObqof_rqflk%M^oq/&yKyH^i^o^kTfka_i^ab%06+-)05+6&yyNFAy0121y
@QebQlo`elcObqof_rqflk%M^oq/&yKyMf`hrmqebqlo`elkqebdolrka%06)05&yyNFAy0121y
QQebQlo`elcObqof_rqflk%M^oq/&yKyH^i^o^kTfka_i^ab%06+-)05+6&yyNFAy0121y
>PnrfobJ^iqo^hbyKyH^i^o^kTfka_i^ab%06+-)05+6&yyNFAy013/y
QPnrfobJ^iqo^hbyKyPnrfobJ^iqo^hb%06+.)06+.&yyNFAy013/y
>PbqQebj>_i^wbyKyPnrfobJ^iqo^hb%06+.)06+.&yyNFAy0130y
@PbqQebj>_i^wbyKyPbqqebclro_o^wfboplkqlmlcqebqltboplkcfob7kloqe:%00)21&plrqe:%11)3.&b^pq:%2-)21&tbpq:%02)3-&yyNFAy0130y
QPbqQebj>_i^wbyKyPnrfobJ^iqo^hb%06+.)06+.&yyNFAy0130y
>Qofkhbqp+++yKyEl^oalcqeb?i^`hAo^dlkcifdeq%05+6)05+6&yyNFAy015.y
QQofkhbqp+++yKyEl^oalcqeb?i^`hAo^dlkcifdeq%05+6)05+6&yyNFAy015.y
KHbbmqebX?i^`hAo^dlkcifdeqJliqZfkvlrofksbkqlov^pvlrtfiikbbafqclo^i^qbonrbpq
HDi^pptb_PmfaboyKyHfiiDi^pptb_Pmfabo^olrka%30)2.&^ka%33)04&^kaj^hbprobvlre^sb/-XPlifa@ovpq^iIbdPe^cqZyyIy..4/2/-yyNFAy112-y

OQelofrjMlfkqyKyOrkqlQelofrjMlfkq%01+6)0-+5&y
QCfbovJbk^`byKyE^kpbiEb^sve^ka%05+2)/4+6&yyNFAy44/1y
Q@ropbQebpbC^qCfkdbopyKyE^kpbiEb^sve^ka%05+2)/4+6&yyNFAy44/0y
QPQLIBK7PjfqefkdQrvbob^kaIllhlrq$pPmvdi^ppyKyQ^phj^pqboP`o^kdb%05+6)/4+4&yyNFAy44/5y
QGL?LMMLOQRKFQV7@riifkdqeb@ljmbqfqflkyKyQ^phj^pqboP`o^kdb%05+6)/4+4&yyNFAy44/6y
QFk`bkalp^rop<Te^qbsbolp^rofpJlobIfhbFqyKyE^kpbiEb^sve^ka%05+2)/4+6&yyNFAy44/4y

O?rokfkdPqbmmbpyKyVlre^sbqldlqeolrde?i^`hOl`hJlrkq^fk%01+4)6-&^kahbbmorkkfkdplrqey
cCi^jb@obpqyKyS^edorh%32+3)/1+.&yyWy?rokfkdPqbmmbpy
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
