DugisGuideViewer:RegisterGuide("Stranglethorn Vale (47)", "Searing Gorge (47-48)", "Horde", "L", function()
return [[
AAA

CDolj$dliyKyQ^hbqebWbmmbifkqlDolj$dli%3.+5)26+.&yyWyQfofpc^iDi^abpyyNFAy3-5y
C?llqv?^vyKyQevpq^%0/+2)/6+0&yyNFAy3-5y
>Qeb?illap^fi?r``^kbbop%M^oq2&yKyCibbqJ^pqboPb^elok%/4+.)44+-&yyNFAy3-5y
>TefphbvPifj$pIlpqDoldyKyTefphbvPifj%/4+.)44+2&yyNFAy25-y
e?llqv?^vyKyFkkhbbmboPhfkaib%/4+.)44+0&yyNFAy3.1y
Q?^`hql?llqv?^vyKy@o^khCfwwib_r_%/4+.)44+0&yyNFAy...5y
QAbifsboqlJ^`HfkibvyKyPb^TlicJ^`Hfkibv%/4+5)44+.&yyNFAy/541y
>Qeb@^mq^fk$p@ebpqyKy@^mq^fkEb`hib_rovPjlqqp%/3+4)40+3&yyNFAy3.1y

@Qeb@^mq^fk$p@ebpqyKyHfiiDloi^pelkqebb^pqbok_b^`e^kaillqXPjlqqp$@ebpqZ%03+0)36+4&yyNFAy3.1y
KIllqqeb_lqqibplkqeb_b^`eyIy1-65yyKyVlrkbbaqlcfkaX@^obcriivCliabaKlqbZcoljqeb_lqqibqlpq^oqkbtnrbpq+FkOrfkplc>_lo^w^olrka%1-)3-&yyNFAy261y
>Jbpp^dbfk^?lqqib%M^oq.&yRy1-65yyKyQebfqbjX@^obcriivCliabaKlqbZpq^oqpnrbpqyyNFAy261y
QJbpp^dbfk^?lqqib%M^oq.&yKyMofk`bppMll_^e)lkqebi^odbfpi^kab^pqlc?llqv?^v%05+2)5-+3&yyNFAy261y
>Jbpp^dbfk^?lqqib%M^oq/&yKyMofk`bppMll_^e%05+2)5-+3&yyNFAy30-y
@Jbpp^dbfk^?lqqib%M^oq/&yKyPi^vHfkdJrhi^lkqebplrqe*b^pqpfablcqebfpi^ka%1-+1)5/+4&^kaq^hbqebXPe^`hibHbvZyyNFAy30-y
QJbpp^dbfk^?lqqib%M^oq/&yKyMofk`bppMll_^e%05+2)5-+3&yyNFAy30-y
@Qeb?illap^fi?r``^kbbop%M^oq2&yKyHfiiqeb/@^mq^fkp^kaqebCibbqJ^pqbolkqeb_l^qpplrqeb^pqlc?llqv?^v*@^mq^fkPqfiit^qbo%00)55+0&)@^mq^fkHbbie^ri%0-+3)6-+3&^kaCibbqJ^pqboCfo^iilk%0-+3)6-+3&yyNFAy3-5y
>@loqbiil$pOfaaib%M^oq.&yKy@eb`haltkpq^fopfkqeb0pefmp%/6+/)55+3&)%0-+4)56+4&)%00+3)55+0&+X@loqbiil$pOfaaibZ`^krpr^iiv_bclrkafkqebjfaaibpefmyyRy1-23yyNFAy3/1y

E?llqv?^vyRy3615y
QQeb?illap^fi?r``^kbbop%M^oq2&yKyCibbqJ^pqboPb^elok%/4+.)44+-&yyNFAy3-5y
QQeb@^mq^fk$p@ebpqyKy@^mq^fkEb`hib_rovPjlqqp%/3+4)40+3&yyNFAy3.1y
K?bclobvlrib^sb+++yKyJ^hbprobvlre^sb^pq^`hlc3-XPfih@ilqeZclo^i^qbonrbpq)lovlr`^k_rvfqcoljqeb>r`qflkElrpbi^qboy
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
