DugisGuideViewer:RegisterGuide("Swamp of Sorrows (48-49)", "Tanaris (49-50)", "Horde", "L", function()
return [[
AAA

CPqlk^oayKyCivqlPt^jmlcPlooltp)S^edorh%32+3)/1+.&yyWy?rokfkdPqbmmbpyyNFAy/451y
>C^iiColjDo^`byKyC^iibkEbollcqebEloab%01+/)33+-&yyNFAy/451y
QC^iiColjDo^`byKyC^iibkEbollcqebEloab%01+/)33+-&yyNFAy/451y
>QebAfpdo^`baLkbyKyC^iibkEbollcqebEloab%01+/)33+-&yyNFAy/3/.y
Q@loqbiil$pOfaaib%M^oq.&yKy>PlddvP`olii)rkaboqeb_ofadb%//)15&yyNFAy3/1y
>@loqbiil$pOfaaib%M^oq/&yKy>PlddvP`olii%//)15&yyNFAy3/2y

QQebAfpdo^`baLkbyKyAfpm^q`e@ljj^kaboOr^d%14+6)22+-&yyNFAy/3/.y
>QebJfppfkdLoabopyKyAfpm^q`e@ljj^kaboOr^d%14+6)22+-&yyNFAy/3//y
QQebJfppfkdLoabopyKy?bkdlo%12+/)23+.&yyNFAy/3//y
>QebPt^jmQ^ihboyKy?bkdlo%12+/)23+.&yyNFAy/3/0y

@QebPt^jmQ^ihboyKyBkqboqebJroil``^sb^q%33)42&)hfiiPt^jmQ^ihbofkqeb_^`hlcfq^kaillqqebXT^o`efbc$pLoabopZyyNFAy/3/0y
HG^onrf^yKy>q^olrka%61)2-&lo%6/)32&yyNFAy/3/0y

QQebPt^jmQ^ihboyKyC^iibkEbollcqebeloab%01+/)33+-&yyNFAy/3/0y
>>Q^iblcPlooltyKyC^iibkEbollcqebeloab%01+/)33+-&yyNFAy/5-.y
Q>Q^iblcPlooltyKyC^iibkEbollcqebeloab%01+/)33+-&yyNFAy/5-.y

EQebP^iqvP^filoQ^sbokyKy?llqv?^vyyRy3615yyNFAy..4/y
_O^q`ebqyKyQ^hbqeb_l^qqlO^q`ebq%/3+.)40+0&yyNFAy..4/y
C?o^`hbkt^iiSfii^dbyKy?o^dlh%30+.)14+/&yyNFAy..4/y
>Qeb?ollalcLkvuf^yWyArpqt^iiltJ^opeyyKyAo^w$Wfi_%04+.)00+-&yyNFAy..4/y

KDbqXLsboarbM^`h^dbZyKyColjqebwbmmbifk`o^pe%21)22&cloIbadbocoljQ^k^ofpyyWyArpqt^iiltJ^opeyyIy..4/1yyNFAy..4/y
@Qeb?ollalcLkvuf^yWyArpqt^iiltJ^opeyyKyAbpqolv2BddplcLkvuf^^olrka%20)4/&^ka%15)42&yyNFAy..4/y
Q@loqbiil$pOfaaib%M^oq/&yWyArpqt^iiltJ^opeyyKyJrpqvP`olii%0.+.)33+.&yyNFAy3/2y
>@loqbiil$pOfaaib%M^oq0&yWyArpqt^iiltJ^opeyyKyJrpqvP`olii%0.+.)33+.&yyNFAy3/3y

QQeb?ollalcLkvuf^yWyArpqt^iiltJ^opeyyKyAo^w$Wfi_%04+.)00+-&yyNFAy..4/y
>@e^iibkdbLsboiloaJlh$JlolhhyKyLsboiloaJlh$Jlolhh%03+0)0.+2&yyNFAy..40yyWyArpqt^iiltJ^opey
@@e^iibkdbLsboiloaJlh$JlolhhyKyHfiiLsboiloaJlh$Jlolhh%03+0)0.+2&yyNFAy..40yyWyArpqt^iiltJ^opey
Q@e^iibkdbLsboiloaJlh$JlolhhyKyAo^w$Wfi_%04+.)00+-&yyNFAy..40yyWyArpqt^iiltJ^opey
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
