DugisGuideViewer:RegisterGuide("Tanaris (49-50)", "Azshara (50)", "Horde", "L", function()
return [[
AAA

CD^adbqw^kyKyCivqlQ^k^ofp)Pe^oaf%02+3)0.+5&yyWyArpqt^iiltJ^opeyyNFAy5560y
>QebPrmboBdd*L*J^qf`yKyBdd*L*J^qf`%2/+1)/4+-&yyNFAy5560y
QQebPrmboBdd*L*J^qf`yKyBdd*L*J^qf`%2/+1)/4+-&yyNFAy5560y
eD^adbqw^kyKyFkkhbbmboCfwwdofj_ib%2/+2)/4+6&yyNFAy046y
QIbadbocoljQ^k^ofpyKyHofkhibDllapqbbi%2.+2)/5+5&yyNFAy112-y
QFkqlqebCfbiayKy@efbcBkdfkbbo?fidbtefwwib%2/+1)/5+2&yyNFAy/10y
>Pi^hbQe^qQefopqyKy@efbcBkdfkbbo?fidbtefwwib%2/+1)/5+2&yyNFAy046y
QPi^hbQe^qQefopqyKy@efbcBkdfkbbo?fidbtefwwib%2/+1)/5+2&yyNFAy046y
>QebQefopqvDl_ifkyKyJ^ofkKlddbkclddbo%2.+5)/5+3&yyNFAy/3-2y
>KluflrpI^foFksbpqfd^qflkyKyPbkfloProsbvloCfwwibaltpbo%2-+/)/4+2&yyNFAy5/y
>PrmboPqf`hvyKyQo^k$obh%2.+3)/3+5&yyNFAy12-1y
>Qefpqibpeor_S^iibvyKyQo^k$obh%2.+3)/3+5&yyNFAy003/y
>QebArkbj^ri@ljmlrkayKy>kafIvkk%2/+5)/4+1&yyNFAy2530y
QQebPrkhbkQbjmibyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyNFAy005-y
>QebPqlkb@fo`ibyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyNFAy0111y
>D^ew$ofaf^kyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyNFAy0.3.y

@QebArkbj^ri@ljmlrkayKyHfii.-Arkbj^ri?orqbp).-Arkbj^riBkclo`bop^kaDlo$j^olhqebO^s^dbo%1-)25&yyNFAy2530y
@D^ew$ofaf^kyKyBnrfmqebXD^ew$ofaf^kAbqb`qloZqlcfka0-XD^ew$ofaf^kLok^jbkqpZ^iilsboQ^k^ofp^kabpmb`f^iivkb^oqebB^pqjllkOrfkp%1-)40&yyNFAy0.3.yyRy6645y
@KluflrpI^foFksbpqfd^qflkyKyDlqlqebKluflrpI^fo%01)14&^kahfiiqeb_rdpclo2X@bkqfm^^oFkpb`qM^oqpZyyNFAy5/y
@Qefpqibpeor_S^iibvyKyHfii5Dk^oibaQefpqibpeor_p^ka5Qefpqibpeor_Ollqpe^mbop^qqebQefpqibpeor_S^iibv%/5)32&yyNFAy003/y
@QebQefopqvDl_ifkyKyHfiiqebQefpqibpeor_Abt@liib`qlop%/5)32&clo^XI^abkAbtDi^kaZyyNFAy/3-2y

>Qlld^$pNrbpqyKy'T^kabofkdKM@'Qlld^%0/)4/&%/6+1)41+/&yyNFAy.23-y
@Qlld^$pNrbpqyKyBp`loqQlld^%33+2)/2+4&yyNFAy.23-y
QQlld^$pNrbpqyKyQloq^%33+2)/2+4&yyNFAy.23-y
QP`obb`eboPmfofqpyKyVbe$hfkv^%33+6)//+1&yyNFAy02/-y

QQebQefopqvDl_ifkyKyJ^ofkKlddbkclddbo%2.+5)/5+3&yyNFAy/3-2y
>FkDllaQ^pqbyKyJ^ofkKlddbkclddbo%2.+5)/5+3&yyNFAy/3-3y
QFkDllaQ^pqbyKyPmofkhib%2.+.)/3+6&yyNFAy/3-3y
>Pmofkhib$pPb`obqFkdobafbkqyKyPmofkhib%2.+.)/3+6&yyNFAy/31.y
QKluflrpI^foFksbpqfd^qflkyKy>i`ebjfpqMbpqibwrdd%2-+6)/4+-&yyNFAy5/y
>QebP`ofjpe^khObabjmqflkyKyPbkfloProsbvloCfwwibaltpbo%2-+/)/4+2&yyNFAy.-y
QQefpqibpeor_S^iibvyKyQo^k$obh%2.+3)/3+5&yyNFAy003/y
QQebArkbj^ri@ljmlrkayKy>kafIvkk%2/+5)/4+1&yyNFAy2530y

QD^ew$ofaf^kyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyNFAy0.3.y
@QebP`ofjpe^khObabjmqflkyKyDlqebqebD^mfkd@e^pj)bkqboqeb`^sb%22)4-&)dlpqo^fdeqqeolrdeqebqrkkbirkqfivlrob^`e^i^odb_rqqbociv*pe^mbaolljtebobvlr`^killqXP`ofjpe^kh$pProsbvfkdDb^oZ%23)4.&yyNFAy.-y
>CfkaLLU*.4,QKyRy53/0yyLyyKyQebfqbjXLLU*.4,QKAfpqobpp?b^`lkZpq^oqpnrbpqyyNFAy02.y
QCfkaLLU*.4,QKyLyyKyEljfkdOl_lqLLU*.4,QK+QefpOl_lq`^k_bclrka^q%3-+/)31+4&+Phfmqebcliilt*rmyyNFAy02.y

ED^adbqw^kyRy3615yyNFAy..-y
QQebP`ofjpe^khObabjmqflkyKyPbkfloProsbvloCfwwibaltpbo%2-+/)/4+2&yyNFAy.-y
>Fkpb`qM^oq>k^ivpfp%M^oq.&yKyPbkfloProsbvloCfwwibaltpbo%2-+/)/4+2&yyNFAy..-y
QFkpb`qM^oq>k^ivpfp%M^oq.&yKy>i`ebjfpqMbpqibwrdd%2-+6)/4+-&yyNFAy..-y
>Fkpb`qM^oq>k^ivpfp%M^oq/&yKy>i`ebjfpqMbpqibwrdd%2-+6)/4+-&yyNFAy..0y
QFkpb`qM^oq>k^ivpfp%M^oq/&yKyPbkfloProsbvloCfwwibaltpbo%2-+/)/4+2&yyNFAy..0y
>OfpblcqebPfifqefayKyPbkfloProsbvloCfwwibaltpbo%2-+/)/4+2&yyNFAy0/y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
