
DugisGuideViewer:RegisterGuide("The Hinterlands (50-51)", "Un'Goro Crater (51-53)", "Horde", "L", function()
return [[
AAA

CQ^oobkJfiiyNFAy45.2y
OQebEfkqboi^kapyWyEfiip_o^aCllqefiipyyKyBkqo^k`b^q%53)0-&yyNFAy45.2y
QOfmmibOb`lsbovyKyDfisbo^afkPrk`e^pbo%/3+4)15+2&+Phfmqebcliilt*rmyyNFAy32-y
QQeb>q^i$^fBufibyKy>q^i$^fBufib%00+4)42+/&+Phfmcliilt*rmyyNFAy.1/6y
@Pmofkhib$pPb`obqFkdobafbkqyKyDlqebS^ilotfkaI^hb%1-)3-&^kaq^hbqebXSflibqQo^d^kZcoljqeb_lqqljlcqebi^hbyyNFAy/31.y

OObs^kqrphSfii^dbyKy%44)46&yyNFAy45.2y
>Pk^mg^tp)JlkyKyH^qlljqeb>kdibo%5-+1)5.+2&yyNFAy45.2y
>D^jjbofq^)JlkyKyH^qlljqeb>kdibo%5-+1)5.+2&yyNFAy45.3y
>I^oaIlpqEfpIrk`eyKyI^oa%45+/)5.+0&yyNFAy451-y

@Pk^mg^tp)JlkyKyHfii.-P^iqt^qboPk^mg^tqroqibpkloqelcqltk%45)4.&yyNFAy45.2y
@D^jjbofq^)JlkyKyHfiiD^jjbofq^%5-)24&^kaillqXH^qllj$p?bpqIrobZyyNFAy45.3y
@TefphbvPifj$pIlpqDoldyKyD^qebo./XMrmbiivsbo_lpMloqZ^ilkdqebb^pqbokpelob%45)43&yyNFAy25-y
Q@loqbiil$pOfaaibyKy@loqbiil$pQob^prob%5-+5)13+5&yyNFAy3/3y
@I^oaIlpqEfpIrk`eyKyDbqXI^oa$pIrk`eZlclkblcqebQoliipqe^qpm^tkplkqebfpi^kaqlqebkloqe%51)1/&yyNFAy451-y
QPk^mg^tp)JlkyKyH^qlljqeb>kdibo%5-+1)5.+2&yyNFAy45.2y
QD^jjbofq^)JlkyKyH^qlljqeb>kdibo%5-+1)5.+2&yyNFAy45.3y
QI^oaIlpqEfpIrk`eyKyI^oa%45+/)5.+0&yyNFAy451-y

ELodofjj^oyNFAy12-/y
?XJfqeofi@^pfkdZyKyColjqeb>E)locfka^kBkdfkbboqefpfpcloqeb$@e^pfkd>*Jb-.$nrbpqfkRk$Dlol@o^qboyyNFAy12-/yyIy.-23.y
C>wpe^o^yKyAlo^p%12+.)30+6&yyNFAy12-/yyWyLodofjj^oy
QJ^d^qe^$pM^vjbkqqlGbafd^yWy>wpe^o^yyKyGbafd^%//+2)2.+1&yyNFAy023/y
QGbp$ofjlk$pM^vjbkqqlGbafd^yWy>wpe^o^yyKyGbafd^%//+2)2.+1&yyNFAy0230y
Q>kaolk$pM^vjbkqqlGbafd^yWy>wpe^o^yyKyGbafd^%//+2)2.+1&yyNFAy0231y

CO^q`ebqyKyHo^rj%//)16+3&yyNFAy12-/yyWy>wpe^o^y
@QebPqlkb@fo`ibyWyQeb?^oobkpyyKyQ^hbqebXPqlkb@fo`ibZcolj^`ebpq%3/+2)05+2&yyNFAy0111y
>Sli`^kf`>`qfsfqvyWyQeb?^oobkpyyKyIfsOfwwibcfu%3/+2)05+4&yyNFAy12-/y

CQerkabo?irccyKy?o^dlh%30+.)04+/&yyNFAy/33.yyWyQeb?^oobkpy
eQerkabo?irccyKyFkkhbbmboM^i^%12+5)31+4&yyNFAy/33.yyWyQerkabo?irccy

CQ^k^ofpyKyQ^i%14)16+5&yyWyQerkabo?irccyyNFAy/33.y
QPmofkhib$pPb`obqFkdobafbkqyWyQ^k^ofpyyKyPmofkhib%2.+.)/3+6&yyNFAy/31.y
>AbifsbovcloJ^ofkyWyQ^k^ofpyyKyPmofkhib%2.+.)/3+6&yyNFAy/33.y
QJ^o`elcqebPfifqefayWyQ^k^ofpyyKy>i`ebjfpqMbpqibwrdd%2-+6)/4+-&yyNFAy1161y
>?rkdibfkqebGrkdibyWyQ^k^ofpyyKy>i`ebjfpqMbpqibwrdd%2-+6)/4+-&yyNFAy1163y
QAbifsbovcloJ^ofkyWyQ^k^ofpyyKyJ^ofkKlddbkclddbo%2.+5)/5+3&yyNFAy/33.y
>KlddbkclddboBifufoyWyQ^k^ofpyyKyJ^ofkKlddbkclddbo%2.+5)/5+3&yyNFAy/33/y
QKlddbkclddboBifufoyWyQ^k^ofpyyKyJ^ofkKlddbkclddbo%2.+5)/5+3&yyNFAy/33/y
QQebPqlkb@fo`ibyWyQ^k^ofpyyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyNFAy0111y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
