
DugisGuideViewer:RegisterGuide("Azshara (50)", "The Hinterlands (50-51)", "Horde", "L", function()
return [[
AAA

CLodofjj^oyKy?rihobhO^dbcfpq%2.+3)/2+2&yyNFAy02.4y
eLodofjj^oyKyFkkhbbmboDovpeh^%21+.)35+3&yyNFAy02.4y

C>wpe^o^yKyAlo^p%12+0)31&yyNFAy02.4y
>Pqb^ifkdHkltibadbyKyGbafd^%//+2)2.+1&yyNFAy02.4y
@Pqb^ifkdHkltibadbyKyCfkaqebXQ^_ibqlc?bqe$>j^o^Z)qebXQ^_ibqlcGfk$v^biZ)qebXQ^_ibqlcJ^ohofZ^kaqebXQ^_ibqlcP^bi$e^fZlko^kaljpmlqp^qqebOrfkplcBia^o^qe%03)21&yyNFAy02.4y
RX?lulcBjmqvSf^ipZyKyLmbkqeb_luqldbqqebsf^ipyyRy.-362yyNFAy023.y
KCfiiSf^i .yKyRpbXBjmqvSf^iI^_biba .Z^qqebmlli%15+.)3-&yyRy.-354yyNFAy0235y
KCfiiSf^i /yKyRpbXBjmqvSf^iI^_biba /Z^qqebmlli%14)2.&yyRy.-355yyNFAy0235y
KCfiiSf^i 0yKyRpbXBjmqvSf^iI^_biba 0Z^qqebmlli%15+.)15+.&yyRy.-356yyNFAy0235y
@Pbbmfkd@loormqflk%M^oq.&yKyRpbqebXBjmqvSf^iI^_biba 1Z^qqebi^pqmlli%14)3-&yyRy.-36-yyNFAy0235y
QPqb^ifkdHkltibadbyKyGbafd^%//+2)2.+1&yyNFAy02.4y
>Abifsbovql>o`ej^dbUvibjyKyGbafd^%//+2)2.+1&yyNFAy023.y
>AbifsbovqlJ^d^qe^yKyGbafd^%//+2)2.+1&yyNFAy02.5y
>AbifsbovqlGbp$ofjlkyKyGbafd^%//+2)2.+1&yyNFAy021.y
>Abifsbovql>kaolkD^kqyKyGbafd^%//+2)2.+1&yyNFAy021/y
QAbifsbovql>o`ej^dbUvibjyKyQ^hbqbibmloqbo^q%/5)2-&qebke^kafk^q>o`ej^dbUvibj%/6+0)1-+/&yyNFAy023.y
>Uvibj$pM^vjbkqqlGbafd^yKy>o`ej^dbUvibj%/6+0)1-+/&yyNFAy0232y
QUvibj$pM^vjbkqqlGbafd^yKyGbafd^%//+2)2.+1&yyNFAy0232y

CQerkabo?irccyKyHolrj%//)16+4&yyNFAy023/y
QAbifsbovqlJ^d^qe^yWyQerkabo?irccyyKyJ^d^qe^Dofjqlqbj)BiaboOfpb%4-+.)0-+5&yyNFAy02.5y
>J^d^qe^$pM^vjbkqqlGbafd^yWyQerkabo?irccyyKyJ^d^qe^Dofjqlqbj)BiaboOfpb%4-+.)0-+5&yyNFAy023/y

ELodofjj^oyRy3615yyNFAy1161y
QOfpblcqebPfifqefayWyLodofjj^oyyKyWfiwf_fkAorjilob%23+2)13+2&yyNFAy0/y
>J^o`elcqebPfifqefayWyLodofjj^oyyKyWfiwf_fkAorjilob%23+2)13+2&yyNFAy1161y
QAbifsbovqlGbp$ofjlkyWyLodofjj^oyyKyGbp$ofjlk%22+3)01+.&yyNFAy021.y
>Gbp$ofjlk$pM^vjbkqqlGbafd^yWyLodofjj^oyyKyGbp$ofjlk%22+3)01+.&yyNFAy0230y
>?lkb*?i^abaTb^mlkpyWyLodofjj^oyyKyGbp$ofjlk%22+3)01+.&yyNFAy10--y

CQfofpc^iDi^abpyKyQ^hbqebwbmmbifklrqpfabLodofjj^o%2-+5).0+4&qlQfofpc^iDi^abp%Rkabo`fqv&yyWyArolq^oyyNFAy0231y
ORkabo`fqvyKyOrkqlRkabo`fqv%3.+6)35+.&yyWyQfofpc^iDi^abpyyNFAy0231y
QAbifsbovql>kaolkD^kqyWyRkabo`fqvyyKy>kaolkD^kq)>mlqeb`^ofrjNr^oqbo%21+5)42+1&yyNFAy021/y
>>kaolk$pM^vjbkqqlGbafd^yWyRkabo`fqvyyKy>kaolkD^kq%21+5)42+1&yyNFAy0231y
QPbbmfkd@loormqflk%M^oq.&yWyRkabo`fqvyyKy@ebjfpq@rbiv%15+1)4.+5&yyNFAy0235y
>Sfsf^kI^do^sbyWyRkabo`fqvyyKy>mlqeb`^ovWfkdb%16+6)35+1&yyNFAy1.00y
>Pbbmfkd@loormqflk%M^oq/&yWyRkabo`fqvyyKy@ebjfpq@rbiv%15+1)4.+5&yyNFAy0236y
QPbbmfkd@loormqflk%M^oq/&yWyRkabo`fqvyyKyQebop^Tfkaplkd%15+-)36+/&yyNFAy0236y

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
