
DugisGuideViewer:RegisterGuide("Un'Goro Crater (51-53)", "Burning Steppes (53-54)", "Horde", "L", function()
return [[
AAA

ORk$Dlol@o^qboyKyPlrqebtbpq`lokbolcqebwlkb%/3)2/&yyWyQ^k^ofpyyNFAy1/56y
KIllhcloillq+++yKyQebob^obj^kvillqklabpp`^qqboba^`olppqefpwlkb+Vlr$iikbba4lcb^`e`lilolcmltbo`ovpq^ip+>iplillq^kvafoqmfibplopmolrqpvlrcfkayyNFAy1/51y

>Qeb>mbplcRk$DlolyKyQlot^M^qecfkabo%4.+3)43+-&yyNFAy1/56y
>QebC^oblcI^o$hlotfyKyQlot^M^qecfkabo%4.+3)43+-&yyNFAy1/6-y

>Fq$p^Pb`obqqlBsbov_lav%M^oq.&yKy>Tob`hbaO^cq%30+.)35+2&yyNFAy0511y
QFq$p^Pb`obqqlBsbov_lav%M^oq.&yKy>Pj^iiM^`h)grpqrkabot^qbokb^o_v%30+.)36+-&yyNFAy0511y
>Fq$p^Pb`obqqlBsbov_lav%M^oq/&yKy>Pj^iiM^`h%30+.)36+-&yyNFAy0512y
RLmbk>Pj^iiM^`hyRy...-4yyNFAy1/6.y
@QebC^oblcI^o$hlotfyKyDbqqebXMfb`blcQeobpe^alk@^o`^ppZlcqeb@^o`^pp%35+5)23+4&yyNFAy1/6-y

QQebC^oblcI^o$hlotfyKyQlot^M^qecfkabo%4.+3)43+-&yyNFAy1/6-y
>QebP`bkqlcI^o$hlotfyKyQlot^M^qecfkabo%4.+3)43+-&yyNFAy1/6.y
@QebP`bkqlcI^o$hlotfyKyCfkaqebbddkbpqp^kapq^kalkqebjpl^O^sbplroJ^qbtfii^mmb^otef`evlrkbbaqlhfiiclo/XO^s^p^roMeboljlkbDi^kapZ+Il`^qflkp7%3-)4/&)%3/)32&)%30)44&)%34)40&)%34)34&)%25)45&^ka%4-)3.&yyNFAy1/6.y
QQebP`bkqlcI^o$hlotfyKyQlot^M^qecfkabo%4.+3)43+-&yyNFAy1/6.y
>Qeb?^fqcloI^o$hlotfyKyQlot^M^qecfkabo%4.+3)43+-&yyNFAy1/6/y
>Tfiifabk$pGlrok^iyRy....3yyKyHfiio^mqlop%3.+1)43+1&rkqfiqebX>J^kdibaGlrok^iZaolmptef`epq^oqpqefpnrbpqyyNFAy0551y

KCfka4XObamltbo`ovpq^ipZyIy...534yyNFAy1/51y
KCfka4XVbiiltmltbo`ovpq^ipZyIy...554yyNFAy1/51y
KCfka4XDobbkmltbo`ovpq^ipZyIy...524yyNFAy1/51y
KCfka4X?irbmltbo`ovpq^ipZyIy...514yyNFAy1/51y

>@e^pfkd>*Jb-.%M^oq.&yKyH^ok^Objqo^sbi%13+2).0+1&yyNFAy1/10y
>Pefwwib$pCivboyKyPefwwib%11+/)..+2&yyNFAy12-0y
>IlpqyKyPmo^ddibCol`h%10+4)5+2&yyNFAy116/y
>?bt^oblcMqbooloa^uyKy>pfdk7?bt^oblcMqbooloa^u%10+3)5+2&yyNFAy12-.y
>Oliiqeb?lkbpyKyPm^ohKfijfkbo%10+2)4+2&yyNFAy055/y
>>ifbkB`lildvyKyEli$^kvbbJ^ope^i%10+6)4+0&yyNFAy0550y
QTfiifabk$pGlrok^iyKyTfiifabkJ^ope^i%10+6)4+/&yyNFAy0551y
>BumbafqflkP^is^qflkyKyTfiifabkJ^ope^i%10+6)4+/&yyNFAy055.y
QFq$p^Pb`obqqlBsbov_lav%M^oq/&yKyIfkhbk%11+4)5+/&yyNFAy0512y
>Fq$p^Pb`obqqlBsbov_lav%M^oq0&yKyIfkhbk%11+4)5+/&yyNFAy06-5y
>I^oflk^kaJrfdfkyKyI^oflk%12+3)5+3&yyNFAy1.12y
cJ^ope^i$pObcrdbyKyDovcb%1/+2)2+6&Rmlkqebefii)b^pvqljfppyyNFAy1/51y
>@ovpq^iplcMltboyKyG+A+@liifb%1.+6)/+3&yyNFAy1/51y
Q@ovpq^iplcMltboyKyG+A+@liifb%1.+6)/+3&yyNFAy1/51y
>QebKloqebokMvilkyKyG+A+@liifb%1.+6)/+3&yyNFAy1/52y
>QebB^pqbokMvilkyKyG+A+@liifb%1.+6)/+3&yyNFAy1/54y
>QebTbpqbokMvilkyKyG+A+@liifb%1.+6)/+3&yyNFAy1/55y

KHfii^pvlrnrbpq+++yKyHfii^kv_illambq^ip)af^jbqo^alkp)^kamqbooloa^ubpvlr`ljb^`olppyyNFAy1.12y

@QebKloqebokMvilkyKyAfp`lsboqebKlqebokMvilk%23)./&yyNFAy1/52y
Q@e^pfkd>*Jb-.%M^oq.&yKy>*Jb-.)fkqebdlofii^`^sb%34+3).3+5&+Phfmqebcliilt*rmfcvlralk$qe^sbXJfqeofi@^pfkdZyyNFAy1/10y
>@e^pfkd>*Jb-.%M^oq/&yKy>*Jb-.)fkqebdlofii^`^sb%34+3).3+5&yyLyyIy.-23.yyNFAy1/11y
Q@e^pfkd>*Jb-.%M^oq/&yKy>*Jb-.)fkqebdlofii^`^sb%34+3).3+5&yyLyyNFAy1/11y
>@e^pfkd>*Jb-.%M^oq0&yKy>*Jb-.)fkqebdlofii^`^sb%34+3).3+5&yyLyyNFAy1/12y
@@e^pfkd>*Jb-.%M^oq0&yKyBp`loq>*Jb-.yyLyyNFAy1/12y
@Qeb>mbplcRk$DlolyKyHfiiqeb^mbpfkqebdlofii^`^sb%33).5&clo/XRk$DlolDlofii^MbiqpZ)/XRk$DlolPqljmboMbiqpZ^ka/XRk$DlolQerkaboboMbiqpZyyNFAy1/56y
@PrmboPqf`hvyKy@liib`q./p^jmibplcXPrmboPqf`hvQ^oZ^qqebq^omfqpfkqebkloqe%13)00&yyNFAy12-1y
KCfkaX@o^qblcCllapqrccpZyKy>qqeb^_^kalkba`^jmfkqebb^pqpfablcqebwlkb%35+2/)03+26&yyIy....0yyNFAy055.y
@I^oflk^kaJrfdfkyKyErkq2?illambq^iI^pebop%36)02&)2?illambq^iQeobpebop%36)02&)2?illambq^iCi^vbop%11)/2&^ka2?illambq^iQo^mmbop%03)36&yyNFAy1.12y
@QebB^pqbokMvilkyKyAfp`lsboqebB^pqbokMvilk%43)2.&yyNFAy1/54y
RXQlot^$pMlr`eZyKyLmbkXQlot^$pMlr`eZ^kamf`hrmqebjb^q^kajfuqrobyyRy..235yyNFAy641y
RXMobpbosbaQeobpe^alkJb^qZyKyMi^`bqebXMobpbosbaQeobpe^alkJb^qZlkqebol`h%46+6)16+6&yyRy..236yyNFAy641y
@Qeb?^fqcloI^o$hlotfyKyLmbkXQlot^$pMlr`eZ^karpbqebjb^q^kajfuqrob^qqebci^qol`h_befkaqebb^pqbokmvilk%46+6)16+6&yyRy..24-yyNFAy1/6/y
QQeb?^fqcloI^o$hlotfyKyQlot^M^qecfkabo%4.+3)43+-&yyNFAy1/6/y
QQeb>mbplcRk$DlolyKyQlot^M^qecfkabo%4.+3)43+-&yyNFAy1/56y

@>ifbkB`lildvyKyDlplrqeqlt^oapqebPifqebofkdP`^o%2-)44&tebobvlrjrpqrpbqebXRkrpbaP`o^mfkdSf^iZfkpfab^qqeb_fdollj%15+3)52+0&yyRy...0/yyNFAy0550y
KHfii_rdpcloXDlofpefP`bkqDi^kaZyIy..504yyNFAy055.y
@BumbafqflkP^is^qflkyKyDbqqebXObpb^o`eBnrfmjbkqZ%05+2)34&yyNFAy055.y
@QebTbpqbokMvilkyKyAfp`lsboqebTbpqbokMvilk%/0)26&yyNFAy1/55y
>CfkafkdqebPlro`byKyHo^hib%0-+6)2-+2&yyNFAy641y
@?lkb*?i^abaTb^mlkpyKyHfiiO^s^p^rop%35)16&clo5XTefqbO^s^p^ro@i^tpZyyNFAy10--y

@Oliiqeb?lkbpyKyVlr`^kbfqebocfkaqebXAfklp^ro?lkbpZ%0-)44&lkqebdolrka_rqqebv^iplaolmcolj^iiqebafklp^rof`jl_pfkRk$DlolyyNFAy055/y
@?bt^oblcMqbooloa^uyKyHfii.-Mqbooloa^u^ka.2CobkwfbaMqbooloa^u+Qebkloj^iMqbooloa^u`^k_bclrka^qqebKloqebokMvilk%24).1&^kaplrqelcqebPifqebofkdP`^o%24)53&^kaqebCobkwfbaMqboola^u`^k_bclrkatbpqlcqebofsbo%05)0/&yyNFAy12-.y
@Pefwwib$pCivboyKyHfiiAfbjbqo^alkp%1-)0-&^kaMqbooloa^u%24).1&)%24)53&)%05)0/&^kad^qebo5XTb__baAfbjbqo^alkP`^ibZ^ka5XTb__baMqbooloa^uP`^ibZyyNFAy12-0y

@CfkafkdqebPlro`byKyRpbXHo^hib$pQebojljbqboZ^qqebqlmlcqebsli`^kl%16)12&yyRy./14/yyNFAy641y
@Sli`^kf`>`qfsfqvyKyHfiibibjbkq^ip^iilsboqebsli`^kl%2-)12&clo6XRk$Dlol>peZyyNFAy12-/y
QIlpqyKyOfkdl%2.+6)16+6&yyNFAy116/y
>>IfqqibEbimColjJvCofbkapyKyOfkdl%2.+6)16+6&yyNFAy116.y
@>IfqqibEbimColjJvCofbkapyKyBp`loqOfkdl^karpbXPmo^ddib$p@^kqbbkZlkefjfcebc^fkqp%10+4)5+1&yyRy..5-1yyNFAy116.y
Q>IfqqibEbimColjJvCofbkapyKyPmo^ddibCol`h%10+4)5+2&yyNFAy116.y
Q?bt^oblcMqbooloa^uyKyPmo^ddibCol`h%10+4)5+2&yyNFAy12-.y
QPefwwib$pCivboyKyPefwwib%11+/)..+2&yyNFAy12-0y
QOliiqeb?lkbpyKyPm^ohKfijfkbo%10+2)4+2&yyNFAy055/y
Q>ifbkB`lildvyKyEli$^kvbbJ^ope^i%10+6)4+0&yyNFAy0550y
QBumbafqflkP^is^qflkyKyTfiifabkJ^ope^i%10+6)4+/&yyNFAy055.y
QI^oflk^kaJrfdfkyKyI^oflk%12+3)5+3&yyNFAy1.12y
Q@e^pfkd>*Jb-.%M^oq0&yKyH^ok^Objqo^sbi%13+2).0+1&yyLyyNFAy1/12y
>J^oslk$pTlohpelmyKyI^oflk%12+3)5+3&yyNFAy1.14y
QQebKloqebokMvilkyKyG+A+@liifb%1.+6)/+3&yyNFAy1/52y
QQebB^pqbokMvilkyKyG+A+@liifb%1.+6)/+3&yyNFAy1/54y
QQebTbpqbokMvilkyKyG+A+@liifb%1.+6)/+3&yyNFAy1/55y
>J^hfkdPbkpblcFqyKyG+A+@liifb%1.+6)/+3&yyNFAy10/.y
QJ^hfkdPbkpblcFqyKyG+A+@liifb%1.+6)/+3&yyNFAy10/.y

QCfkafkdqebPlro`byKyHo^hib%0-+6)2-+2&yyNFAy641y
>QebKbtPmofkdpyKyHo^hib%0-+6)2-+2&yyNFAy65-y

OPfifqerpyKyQ^hbqebm^qermlrqlcqeb`o^qbofkqebkloqetbpq`lokbolcqebwlkb%/6)//&yyNFAy043.y
O@bk^oflkEliayKyCliiltqebol^aql@bk^oflkElia%15+5)03+4&yyWyPfifqerpyyNFAy043.y
CD^adbqw^kyKyOrkhTfkaq^jbo%15+5)03+4&yyWyPfifqerpyyNFAy043.y
Q?rkdibfkqebGrkdibyWyQ^k^ofpyyKy>i`ebjfpqMbpqibwrdd%2-+6)/4+-&yyNFAy1163y
QPrmboPqf`hvyWyQ^k^ofpyyKyQo^k$obh%2.+3)/3+5&yyNFAy12-1y

EQerkabo?irccyRy3615yyNFAy043.y
>Rk$DlolPlfiyWyQerkabo?irccyyKy>o`eAorfaE^jrriOrkbqlqbjlkBiaboOfpb%45+1)/5+2&yyNFAy043.y
QRk$DlolPlfiyWyQerkabo?irccyyKyDebab%43+2)/0+6&yyNFAy043.y
>Jlooltdo^fkObpb^o`eyWyQerkabo?irccyyKy>o`eAorfaE^jrriOrkbqlqbjlkBiaboOfpb%45+1)/5+2&yyNFAy0453y
QJlooltdo^fkObpb^o`eyWyQerkabo?irccyyKy?^pe^k^Orkbqlqbj%4-+6)00+5&yyNFAy0453y

CLodofjj^oyKyQ^i%13+5)2-+/&yyWyQerkabo?irccyyNFAy05/.y
eLodofjj^oyKyFkkhbbmboDovpeh^%21+.)35+1&yyWyLodofjj^oyyNFAy05/.y

CO^q`ebqyKyAlo^p%12+.)30+6&yyWyLodofjj^oyyNFAy05/.y
QSli`^kf`>`qfsfqvyWyQeb?^oobkpyyKyIfsOfwwibcfu%3/+2)05+4&yyNFAy12-/y
QJ^oslk$pTlohpelmyWyQeb?^oobkpyyKyIfsOfwwibcfu%3/+2)05+4&yyNFAy1.14y

_?llqv?^vyKyQ^hbqeb_l^qql?llqv?^v%35+/)05+3&yyWyQeb?^oobkpyyNFAy05/.y
QTefphbvPifj$pIlpqDoldyWyPqo^kdibqelokS^ibyyKyTefphbvPifj%/4+.)44+2&yyNFAy25-y

CH^od^qeyKyDofkdbo%/3+6)44&yyNFAy05/.y
QSfsf^kI^do^sbyKyPe^altj^dbSfsf^kI^do^sb%0+-)14+4&yyNFAy1.00y
>Aob^aj^riOl`hyKyQe^i$qo^hMolraqrph%0+1)15+.&yyNFAy05/.y
>QebOfpblcqebJ^`efkbp%M^oq.&yKyEfbolme^kqQeblalo^Jris^a^kf^%0+.)14+5&yyNFAy1-3.y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
