DugisGuideViewer:RegisterGuide("Burning Steppes (53-54)", "Felwood (54)", "Horde", "L", function()
return [[
AAA

C?rokfkdPqbmmbpyKyDloofh%1)11+6&yyWy?^ai^kapyyNFAy14/3y
>?ollaifkdBppbk`byKyQfkhbbPqb^j_lfi%32+0)/0+6&yyNFAy14/3y
>Q^_ibqlcqebPbsbkyKyJ^utloqR_bodifkq%32+/)/0+5&yyNFAy1/63y

@?ollaifkdBppbk`byKyRpbqebXAo^`l*Fk`^o`fk^qofu6--Zlkqebao^dlktebimp%6-)0/&)hfiiqebj^kaobqofbsbqebX?ollaifkdBppbk`bZyyRy.//51yyNFAy14/3y

>>Q^pqblcCi^jbyKy@vorpQebobmbkqlrp%62+-)0.+3&yyNFAy1-//y
Q>Q^pqblcCi^jbyKy@vorpQebobmbkqlrp%62+-)0.+3&yyNFAy1-//y
QAob^aj^riOl`hyKyPe^$kfMolraqrph%46+6)12+1&yyNFAy05/.y
>Holj$DoriyKyPe^$kfMolraqrph%46+6)12+1&yyNFAy05//y

@Holj$DoriyKyOb`lsboXPe^$kf$pKlpb*OfkdZtef`eaolmpcoljHolj$doritef`e`^k_bclrkafkAob^ajlriOl`h%45)1.&yyNFAy05//y
@QebOfpblcqebJ^`efkbp%M^oq.&yKyHfiiT^oOb^sbop^kaqebDob^qboOl`hBibjbkq^ip^kad^qebo.-XCo^`qrobaBibjbkq^iPe^oaZ%34)03&yyNFAy1-3.y
@Q^_ibqlcqebPbsbkyKyDbqqebXQ^_ibqQo^kp`ofmqZfkqebqebOrfkplcQe^rofpp^k%21)1-&yyNFAy1/63y

QQ^_ibqlcqebPbsbkyKyJ^utloqR_bodifkq%32+/)/0+5&yyNFAy1/63y
Q?ollaifkdBppbk`byKyQfkhbbPqb^j_lfi%32+0)/0+6&yyNFAy14/3y
>CbiklhPqbbipmofkdyKyQfkhbbPqb^j_lfi%32+0)/0+6&yyNFAy15-5y

CH^od^qeyKyS^edorh%32+3)/1+.&yyNFAy1-3/y
QHolj$DoriyWy?^ai^kapyyKyQe^i$qo^hMolraqrph%0+1)15+.&yyNFAy05//y
QQebOfpblcqebJ^`efkbp%M^oq.&yWy?^ai^kapyyKyEfbolme^kqQeblalo^Jris^a^kf^%0+.)14+5&yyNFAy1-3.y
>QebOfpblcqebJ^`efkbp%M^oq/&yWy?^ai^kapyyKyEfbolme^kqQeblalo^Jris^a^kf^%0+.)14+5&yyNFAy1-3/y
@QebOfpblcqebJ^`efkbp%M^oq/&yWy?^ai^kapyyKyQ^hbqebXBibjbkq^iPe^oaP^jmibZqlIlqtfiSbof^qrp%/3)12&yyNFAy1-3/y
QQebOfpblcqebJ^`efkbp%M^oq/&yWy?^ai^kapyyKyIlqtfiSbof^qrp%/3)12&yyNFAy1-3/y

ELodofjj^oyRy3615y
Q?lkb*?i^abaTb^mlkpyWyLodofjj^oyyKyGbp$ofjlk%22+3)01+.&yyNFAy10--y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
