DugisGuideViewer:RegisterGuide("Winterspring (54-55)", "Western Plaguelands (56)", "Horde", "L", function()
return [[
AAA

OBsboillhyKyOrkqlBsboillhCliiltqebol^ab^pq%3-+2)03+1&yyNFAy0450y
cBsboillhyKyVrdobh%3-+2)03+1&yyNFAy0450y
>>obTbQebob)Vbqf<%M^oq.&yKyRjfOrjmibpkf`hbo%3-+6)04+4&yyNFAy0450y
>QebBsboillhObmloqyKyDobdloDobvpqlkb%3.+0)05+6&yyNFAy3-/6y
>ArhbKf`eli^pWsbobkelccyKyDobdloDobvpqlkb%3.+0)05+6&yyNFAy3-0-y
>PfpqboM^jbi^yKyGbppf`^Obam^qe%3.+0)05+6&yyNFAy23-.y
>RopfrplcqebPe^oaqllqeyKyPqlojPe^altellc%3.+6)05+1&yyNFAy2-21y
QCbiklhPqbbipmofkdyKyCbiklhPqbbipmofkd%3.+3)05+3&yyNFAy15-5y
>@efiitfkaElokpyKyCbiklhPqbbipmofkd%3.+3)05+3&yyNFAy15-6y
eBsboillhyKyFkkhbbmboSfwwfb%3.+0)05+6&yyNFAy2-22y

@RopfrplcqebPe^oaqllqeyKyHfiiRopfrp)^_b^o)kloqelcBsboillhebpm^tkp^q%23+1)0/+1&lo^p^cbomi^`bql`^jmfp^q%30)0-&yyNFAy2-21y
QRopfrplcqebPe^oaqllqeyKyPqlojPe^altellc%3.+6)05+1&yyNFAy2-21y
>?orjbo^klcqeb@efiitfkayKyPqlojPe^altellc%3.+6)05+1&yyNFAy2-22y
@?orjbo^klcqeb@efiitfkayKyHfii?orjbo^k%3/)24&yyNFAy2-22y

@Pqo^kdbPlro`bpyKyQ^hbqebol^aplrqe^kabumilobA^ohtefpmboDlodb%26)40&yyNFAy151/y

EBsboillhyRy3615yyNFAy2-50y
Q?orjbo^klcqeb@efiitfkayKyPqlojPe^altellc%3.+6)05+1&yyNFAy2-22y
@>obTbQebob)Vbqf<%M^oq.&yKyHfiiqebVbqfp%32)12&clo.-XQef`hVbqfCroZyyNFAy0450y
@Qeob^qlcqebTfkqboc^iiyKyHfii5Tfkqboc^iiM^qecfkabop)5Tfkqboc^iiAbkT^q`ebop)^ka5Tfkqboc^iiQlqbjf`p%0-)02&yyNFAy2-5/y
@TfiaDr^oaf^kpyKyHfii.2O^dfkdLti_b^pqp%25)01&^ka.2O^ddbaLti_b^pqp%04)02&yyNFAy12/.y
@@efiitfkaElokpyKyHfii@efj^bo^^olrka%33)/6&clo5XRk`o^`hba@efiitfkaElokpZyyNFAy15-6y

QQeob^qlcqebTfkqboc^iiyKyAlkls^Pkltabk%0.+0)12+/&yyNFAy2-5/y
QPqo^kdbPlro`bpyKyAlkls^Pkltabk%0.+0)12+/&yyNFAy151/y
>Tfkqboc^iiCfobt^qboyRy./44.yyNFAy2-50yyKyQebfqbjXBjmqvCfobt^qboCi^phZpq^oqpnrbpqy
QTfkqboc^iiCfobt^qboyKyAlkls^Pkltabk%0.+0)12+/&yyNFAy2-50y
>C^iifkdql@loormqflkyKyAlkls^Pkltabk%0.+0)12+/&yyNFAy2-51y

Q>obTbQebob)Vbqf<%M^oq.&yKyRjfOrjmibpkf`hbo%3-+6)04+4&yyNFAy0450y
>>obTbQebob)Vbqf<%M^oq/&yKyRjfOrjmibpkf`hbo%3-+6)04+4&yyNFAy644y
Q@efiitfkaElokpyKyCbiklhPqbbipmofkd%3.+3)05+3&yyNFAy15-6y

@Tfkqboc^ii>`qfsfqvyKyHfii5Tfkqboc^iiPe^j^k)5Tfkqboc^iiAbkT^q`ebop^ka5Tfkqboc^iiRop^^qqebTfkqboc^iiSfii^db%34)04&yyNFAy5131y
@>obTbQebob)Vbqf<%M^oq/&yKyHfiiqebVbqfM^qof^o`ebpfkqebF`bQefpqib@^sbclo/XMofpqfkbVbqfElokpZ%33)10&yyNFAy644y

EBsboillhyRy3615yyNFAy12-3y
Q>obTbQebob)Vbqf<%M^oq/&yKyRjfOrjmibpkf`hbo%3-+6)04+4&yyNFAy644y

C?illasbkljMlpqyKyVrdobh%3-+2)03+1&yyNFAy12-3y
QTfiaDr^oaf^kpyWyCbitllayyKyQoriiC^fi_^kb%01+4)2/+4&+Phfmqebcliilt*rmyyNFAy12/.y

Q>Erp_^ka$pI^pq?^qqibyWyCbitllayyKyAobh^$Pro%01+5)2/+4&yyNFAy3.3/y
QTbiilc@loormqflkyWyCbitllayyKyTfkk^E^ww^oa%01+/)2/+0&yyNFAy12-2y
>@loormqbaP^_bopyWyCbitllayyKyTfkk^E^ww^oa%01+/)2/+0&yyNFAy12-3y

CBjbo^iaP^k`qr^ovyKy?o^hh^o%01+1)20+6&yyNFAy2-52y
Q@liib`qflklcqeb@loormqT^qboyWyCbitllayyKyDobq^Jlppellc%2.+/)5/+.&yyNFAy2.24y
QSbofcvfkdqeb@loormqflkyWyCbitllayyKyQ^olkkObacb^qebo%2-+6)5.+4&yyNFAy2.23y
Q@ib^kpfkdCbitllayWyCbitllayyKyJ^v_bppOfsbo_obbwb%13+5)50+.&yyNFAy1.-/y

@@loormqbaP^_bopyWyCbitllayyKyRpbXTfkk^$pHfqqbk@^oofboZ^qqeb@loormqbaJllktbii%0/)33&yyRy./232yyNFAy12-3y
Q@loormqbaP^_bopyWyCbitllayyKyTfkk^E^ww^oa%01+/)2/+0&+Cfopqq^ihqlqeb`^qyyNFAy12-3y

QC^iifkdql@loormqflkyWyCbitllayyKyAb^atlla@^riaolk%3-+/)2+6&yyNFAy2-51y
>JvpqbovDllyWyCbitllayyKyAb^atlla@^riaolk%3-+/)2+6&yyNFAy2-52y
>Ab^atllaOfqr^iQlqbjyWyCbitllayyLyyRy/-41.yyNFAy514-y
>Tfkqboc^iiOfqr^iQlqbjyLyyRy/-41/yyNFAy514.y
QAb^atllaOfqr^iQlqbjyWyCbitllayyLyyKyHboka^fkqebqrkkbi^qQfj_boj^tElia%32+1)/+4&yyNFAy514-y
QTfkqboc^iiOfqr^iQlqbjyWyCbitllayyLyyKyHboka^fkqebqrkkbi^qQfj_boj^tElia%32+1)/+4&yyNFAy514.y
>Orkb`ilqeyLyyKyJbfilpe%32+4)/+6&yyIy.1-140-yyNFAy3-0.y
QOrkb`ilqeyLyyKyJbfilpe%32+4)/+6&yyNFAy3-0.y

OTfkqbopmofkdyKyOrkqeolrdeqeb`^sb%/6)04&yyWyTfkqbopmofkdy
QTfkqboc^ii>`qfsfqvyKyP^ic^%/4+5)01+2&yyNFAy5131y
QJvpqbovDllyKyAlkls^Pkltabk%0.+0)12+/&+Phfmqebcliilt*rmyyNFAy2-52y

EBsboillhyRy3615y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
