
DugisGuideViewer:RegisterGuide("Felwood (54)", "Winterspring (54-55)", "Horde", "L", function()
return [[
AAA

CPmifkqboqobbMlpqyKyAlo^p%12+0)31&yyWyLodofjj^oyyNFAy2.22y

OCbitllayKyEb^atbpqlrqlcqltk+>qqebclohkb^oqebobqob^qeb^akloqelrqlcqebwlkb%22+42)/6+2-&yyWy>pebks^ibyyNFAy2.22y

OBjbo^iaP^k`qr^ovyKyGrpq^eb^a)kloqelcqebol^a%2.)5.&yyNFAy2.22y
>Clo`bplcG^babk^oyKyDobq^Jlppellc%2.+/)5/+.&yyNFAy2.22y
>Sbofcvfkdqeb@loormqflkyKyQ^olkkObacb^qebo%2-+6)5.+4&yyNFAy2.23y

>Qfj_boj^t>iivyKyDo^wib%2.+-)52+-&yyNFAy513-y
@Qfj_boj^t>iivyKyHfii3Ab^atllaT^ooflop)3Ab^atllaM^qecfkabop^ka3Ab^atllaD^oabkbopqlqebtbpq%15)6-&yyNFAy513-y
QQfj_boj^t>iivyKyDo^wib%2.+-)52+-&yyNFAy513-y
>Pmb^hqlK^cfbkyKyDo^wib%2.+-)52+-&yyNFAy513/y

>@ib^kpfkdCbitllayKyJ^v_bppOfsbo_obbwb%13+5)50+.&yyNFAy1.-/y

O?illasbkljMlpqyKyOrkql?illasbkljMlpq%01)2/&yyNFAy12-2y
>Tbiilc@loormqflkyKyTfkk^E^ww^oa%01+/)2/+0&yyNFAy12-2y
>>Erp_^ka$pI^pq?^qqibyKyAobh^$Pro%01+5)2/+4&yyNFAy3.3/y
>TfiaDr^oaf^kpyKyQoriiC^fi_^kb%01+4)2/+4&yyNFAy12/.y

@Tbiilc@loormqflkyKyRpbqebXE^oabkbaCi^phbqZ^qqebG^abcfobP^qvop$jllktbii%0/)33&yyRy./233yyNFAy12-2y
@Clo`bplcG^babk^oyKyDlqlG^babk^o%04)26&^kapi^v1G^babk^oElrkap)1G^babk^oDr^oapjbk)3G^babk^o>abmqp^ka3G^babk^o@riqfpqpyyNFAy2.22y

QClo`bplcG^babk^oyKyDobq^Jlppellc%2.+/)5/+.&yyNFAy2.22y
>@liib`qflklcqeb@loormqT^qboyKyDobq^Jlppellc%2.+/)5/+.&yyNFAy2.24y

@>Erp_^ka$pI^pq?^qqibyKyHfiiLsboiloaOlo%15)61&yyNFAy3.3/y

@@liib`qflklcqeb@loormqT^qboyKyRpbqebXBjmqv@^kqbbkZ^qqebjllktbiifkG^babk^o%02+/)26+4&yyRy./6//yyNFAy2.24y
@Sbofcvfkdqeb@loormqflkyKyAbpqolv/Bkqolmf`?b^pqp^ka/Bkqolmf`Eloolop^kabumilobPe^qqboP`^oS^ib%1-+2)1.+4&yyNFAy2.23y
@@ib^kpfkdCbitllayKyHfiiBibjbkq^ip^qFolkqobb@^sbokclo.2X?illa>j_boZ^olrka%22).4&yyNFAy1.-/y

QPmb^hqlK^cfbkyKyK^cfbk%31+5)5+/&yyNFAy513/y
>Ab^atllalcqebKloqeyKyK^cfbk%31+5)5+/&yyNFAy513.y
@Ab^atllalcqebKloqeyKyHfii3Ab^atllaAbkT^q`ebop)3Ab^atlla>sbkdbop^ka3Ab^atllaPe^j^kpqlqebtbpq%3-)5&yyNFAy513.y
QAb^atllalcqebKloqeyKyK^cfbk%31+5)5+/&yyNFAy513.y
>Pmb^hqlP^ic^yKyK^cfbk%31+5)5+/&yyNFAy5132y

OTfkqbopmofkdyKyOrkqeolrdeqeb`^sb%/6)04&yyWyTfkqbopmofkdyyNFAy5131y
QPmb^hqlP^ic^yWyTfkqbopmofkdyyKyP^ic^%/4+5)01+2&yyNFAy5132y
>Tfkqboc^ii>`qfsfqvyWyTfkqbopmofkdyyKyP^ic^%/4+5)01+2&yyNFAy5131y
QQebKbtPmofkdpyWyTfkqbopmofkdyyKyAlkls^Pkltabk%0.+0)12+/&yyNFAy65-y
>Pqo^kdbPlro`bpyWyTfkqbopmofkdyyKyAlkls^Pkltabk%0.+0)12+/&yyNFAy151/y
QFq$p^Pb`obqqlBsbov_lav%M^oq0&yWyTfkqbopmofkdyyKyAlkls^Pkltabk%0.+0)12+/&yyNFAy06-5y
>Qeob^qlcqebTfkqboc^iiyWyTfkqbopmofkdyyKyAlkls^Pkltabk%0.+0)12+/&yyNFAy2-5/y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)

