DugisGuideViewer:RegisterGuide("The Scarlet Enclave (55-58 Death Knight)", "Hellfire Peninsula (60-62)", "Horde", "L", function()
return [[
AAA

KT^vmlfkq^ooltalbpk$qtlohebob+++yKyQebP`^oibqBk`i^sbfp`lkpfaboba^_^qqibdolrkafkpq^k`b^kaqeb^aalk`^k$qmi^`b^t^vmlfkq)tbpqfii^aaba`lloafk^qbpqlqebklqbpfcvlre^sbmol_ibjpcfkafkdqefkdpyyNFAy./260y
>FkPbosf`bLcQebIf`eHfkdyKyOrkclot^oa^kaq^ihqlQebIf`eHfkd)vlrpq^oqfk%2.+0)02+.&yyNFAy./260y

QFkPbosf`bLcQebIf`eHfkdyKyQrok^olrka^kamol`bbafkqlqebEb^oqlc>o`eborp%14)/6&yyNFAy./260y
>QebBj_i^wlkbaOrkb_i^abyKyFkpqor`qloO^wrsflrp%14+3)/5+2&yyNFAy./3.6y

@QebBj_i^wlkbaOrkb_i^abyKyDlqlqebOrkbclodb^kamf`hrm?^qqib*tlokPtloa%14)/4&+Ofdeq*`if`hqebptloakb^oqebOrkbclodbqe^q$pfkvlrofksbkqlovyyNFAy./3.6y

QQebBj_i^wlkbaOrkb_i^abyKyFkpqor`qloO^wrsflrp%14+3)/5+2&yyNFAy./3.6y
>Orkbclodfkd7Mobm^o^qflkClo?^qqibyKyFkpqor`qloO^wrsflrp%14+3)/5+2&yyNFAy./51/y
@Orkbclodfkd7Mobm^o^qflkClo?^qqibyKyDl_^`hqlqebOrkbclodb^ka`ellpbtef`eorkbvlrt^kqqlbkdo^sblkvlrotb^mlkyyNFAy./51/y
QOrkbclodfkd7Mobm^o^qflkClo?^qqibyKyFkpqor`qloO^wrsflrp%14+3)/5+2&yyNFAy./51/y
>QebBkaibppErkdboyKyFkpqor`qloO^wrsflrp%14+3)/5+2&yyNFAy./515y
@QebBkaibppErkdboyKyEb^aqlqeb`bkqbolcqebollj^karpbX>`eborpPe^`hibHbvZqlcobb^kRktloqevFkfqf^qb^kahfiifq%15+5)/6+5&yyRy1-40/yyNFAy./515y
QQebBkaibppErkdboyKyFkpqor`qloO^wrsflrp%14+3)/5+2&yyNFAy./515y
>QebBvblc>`eborpyKyFkpqor`qloO^wrsflrp%14+3)/5+2&yyNFAy./303y

QQebBvblc>`eborpyKyObqrokqlQebIf`eHfkd%2.+0)02+.&yyNFAy./303y
>Ab^qe@ljbpColjLkEfdeyKyQebIf`eHfkd%2.+0)02+.&yyNFAy./31.y

@Ab^qe@ljbpColjLkEfdeyKyMol`bbaql^kBvblc>o`eborp%2.)03+0&@lkqoliJb`e^kfpj^kapq^oqqebjfkf*d^jb+Eb^aqlP`^oibqElia^ka^k^ivwbfq)pelria_blkvlroibcq+C^`fkdP`^oibqElia)dlibcq^ka^k^ivwbqebKbt>s^ilkClodb+ColjqebKbt>s^ilkClodbeb^aqlt^oapqebKbt>s^ilkQltkE^ii^ka^k^ivwbfq+QebKbt>s^ilkQltkE^iie^p^`il`hqltbolkqebcolkq+Eb^aibcqc^`fkdqebKbt>s^ilkQltkE^ii)^kaeb^alsboqlqeb`ero`efkqebafpq^k`b)@ofjplkCi^jbqebk^k^ivwbfq+@^k`biqebjfkf*d^jbvlrpelria_b_^`hfkB_lkEliayyNFAy./31.y

QAb^qe@ljbpColjLkEfdeyKyObqrokqlQebIf`eHfkd%2.+0)02+.&yyNFAy./31.y
>QebJfdeqLcQebP`lrodbyKyQebIf`eHfkd%2.+0)02+.&yyNFAy./324y
QQebJfdeqLcQebP`lrodbyKyQrok^olrka^kagrjmfkqlqebmfkhdiltfkdmloq^i^qqeb_^pblcqebpq^fop%2-+2)00&Eb^aqlqeb`bkqbolcE^iilc@ljj^ka^kapmb^htfqeEfdeiloaA^oflkJldo^fkb%15+6)/6+5&yyNFAy./324y
>ObmloqQlP`lrodb@ljj^kaboQe^i^kloyKyEfdeiloaA^oflkJldo^fkb%15+6)/6+5&yyNFAy./52-y
>QebMltboLc?illa)Colpq>kaRkelivyKyIloaQelos^i%14+2)/3+3&yyNFAy./516y
QObmloqQlP`lrodb@ljj^kaboQe^i^kloyKyEb^a_^`hrmqebpq^foprpfkdqebmfkhmloq^i^kapmb^htfqeP`lrodb@ljj^kaboQe^i^klo%2-)02&yyNFAy./52-y
>QebP`^oibqE^osbpqyKyP`lrodb@ljj^kaboQe^i^klo%2-+6)02+0&yyNFAy./34-y

QQebP`^oibqE^osbpqyKyMol`bbaqlqebP`lrodbDovmelk^kaq^hb^ofabaltkqlAb^qe$p?ob^`e+Eb^alsboqlMofk`bS^i^k^o%2/+1)01+.&yyNFAy./34-y
>Fc@e^lpAofsbp)IbqPrccbofkdEliaQebObfkpyKyMofk`bS^i^k^o%2/+1)01+.&yyNFAy./345y
>Do^kaQebcqM^iljfklyKyP^i^k^oqebElopbj^k%20+.)00+3&yyNFAy./35-y
>Ab^qe$p@e^iibkdbyKyLiorkqeb?^qqib`^iibo%12+5)00+5&yyNFAy./400y
@Ab^qe$p@e^iibkdbyKyArbiAb^qeHkfdeqFkfqf^qbpfkqeb^ob^ql`ljmibqbqebnrbpqyyNFAy./400y
QAb^qe$p@e^iibkdbyKyLiorkqeb?^qqib`^iibo%12+5)00+5&yyNFAy./400y
>QlkfdeqTbAfkbFkE^sbkpefobyKyLofqelpqebPhvA^ohbkbo%2/+3)04+2&yyNFAy./346y

QDo^kaQebcqM^iljfklyKyDlplrqe^kahfii^kvmb^p^kqp^ilkdt^vqlqebpq^_ibp%23)1-&elmlkql^elopb^ka_^`hqlP^i^k^oqebElopbj^k^q%2/)01&yyNFAy./35-y
>FkqlqebOb^ijlcPe^altpyKyP^i^k^oqebElopbj^k%20+.)00+3&yyNFAy./354y

@FkqlqebOb^ijlcPe^altpyKyQo^sbikloqeb^pq^kahfii^A^ohOfabo^olrka%21)1.&q^hbefpelopb^kadl_^`hql%20)00&^karpbqeb`^iiyyNFAy./354y
QFkqlqebOb^ijlcPe^altpyKyP^i^k^oqebElopbj^k%20+.)00+3&yyNFAy./354y

@QlkfdeqTbAfkbFkE^sbkpefobyKyEb^aplrqe%21)15&^kapq^oqmf`hfkdrmXP^olkfqb>ooltpZyyNFAy./346y
@Fc@e^lpAofsbp)IbqPrccbofkdEliaQebObfkpyKyHfiiqeb@fqfwbkplcE^sbkpefob^olrka%23)2-&yyNFAy./345y

QQlkfdeqTbAfkbFkE^sbkpefobyKyLofqelpqebPhvA^ohbkbo%2/+3)04+2&yyNFAy./346y
QFc@e^lpAofsbp)IbqPrccbofkdEliaQebObfkpyKyMofk`bS^i^k^o%2/+1)01+.&yyNFAy./345y

>DlqefhqebE^osbpqboyKyMofk`bS^i^k^o%2/+1)01+.&yyNFAy./364y

QDlqefhqebE^osbpqboyKyDlqefhqebE^osbpqbo%21+/)02+-&yyNFAy./364y
>QebDfcqQe^qHbbmpLkDfsfkdyKyDlqefhqebE^osbpqbo%21+/)02+-&yyNFAy./365y

@QebDfcqQe^qHbbmpLkDfsfkdyKyEb^ab^pq^karpbqebfqbjXDfcqlcqebE^osbpqboZlkqebjfkbop^q%25)00&yyNFAy./365yyRy06/20y

QQebDfcqQe^qHbbmpLkDfsfkdyKyDlqefhqebE^osbpqbo%21+/)02+-&yyNFAy./365y
>>k>qq^`hLcLmmloqrkfqvyKyDlqefhqebE^osbpqbo%21+/)02+-&yyNFAy./4--y
Q>k>qq^`hLcLmmloqrkfqvyKyMofk`bS^i^k^o%2/+1)01+.&yyNFAy./4--y
>J^pp^`ob>qIfdeq$pMlfkqyKyMofk`bS^i^k^o%2/+1)01+.&yyNFAy./4-.y

@J^pp^`ob>qIfdeq$pMlfkqyKyEb^ab^pqqlt^oapqebjfkb^d^fk^ka`if`hlkqebFk`lkpmf`rlrpJfkb`^oq^q%25)00&Ofabfqqlqebpefm^kaqebkhfii^iiqebqollmptel^mmol^`eqebpefmqe^qvlr^oblk+Qebkrpbqebbp`^mbdovmelkqldlqlp^cbqv+yyNFAy./4-.y

QJ^pp^`ob>qIfdeq$pMlfkqyKyMofk`bS^i^k^o%2/+1)01+.&yyNFAy./4-.y
>Sf`qlov>qAb^qe$p?ob^`eyKyMofk`bS^i^k^o%2/+1)01+.&yyNFAy./4-3y
QSf`qlov>qAb^qe$p?ob^`eyKyEfdeiloaA^oflkJldo^fkb%15+6)/6+5&fkB_lkEliavlrjrpqq^hbqebdovmelkq^uf_^`hrmyyNFAy./4-3y
>QebTfiiLcQebIf`eHfkdyKyEfdeiloaA^oflkJldo^fkb%15+6)/6+5&yyNFAy./4.1y
QQebTfiiLcQebIf`eHfkdyKyObqrokqlAb^qe$p?ob^`eMofk`bS^i^k^o%2/+1)01+.&yyNFAy./4.1y
>Qeb@ovmqlcObjbj_o^k`byKyMofk`bS^i^k^o%2/+1)01+.&yyNFAy./4.2y

>QebMi^drb_ofkdbo$pObnrbpqyKyEb^aplrqeqlt^oapqeb@ovmqlcObjbj_o^k`b%21)25&Lkqebt^vmf`hqefprmcoljKlqeqebMi^drb_ofkdbo%22+6)2/+2&yyNFAy./4.3y
QQeb@ovmqlcObjbj_o^k`byKyMofk`bHbibpbqe%21+0)24+1&yyNFAy./4.2y
>KltebobQlOrk>kaKltebobQlEfabyKyMofk`bHbibpbqe%21+0)24+1&yyNFAy./4.6y
>I^j_pQlQebPi^rdeqboyKy?^olkOfsbka^ob%12+3)24+2&yyNFAy./4//y

@I^j_pQlQebPi^rdeqboyKyEb^aql%24)31&^kahfii^kv@fqfwbkplcKbt>s^ilkqe^qvlrpbb+Objbj_boqlillqqebX@orp^aboPhriipZqe^qaolmlccqebjl_pyyNFAy./4//y

@QebMi^drb_ofkdbo$pObnrbpqyKyEb^aqlqeb_^`h^kadlaltkqebpq^fopqlmf`hrm^kXBjmqv@^riaolkZ+Dl_^`hlrqpfab^kaeb^aql%3.)3-&Qebobfp^kXFolk@e^fkZlkqebt^iiqe^qvlrkbbaqldo^_yyNFAy./4.3y
@KltebobQlOrk>kaKltebobQlEfabyKyKlteb^aqlqebKbt>s^ilkQltkE^ii^kahfiiJ^vloNrfj_v+>kaq^hbqebXKbt>s^ilkObdfpqovZcoljqebq^_ib%20)4-&yyNFAy./4.6y

QKltebobQlOrk>kaKltebobQlEfabyKyMofk`bHbibpbqe%21+0)24+5&yyNFAy./4.6y
QI^j_pQlQebPi^rdeqboyKy?^olkOfsbka^ob%12+3)24+2&yyNFAy./4//y
>EltQlTfkCofbkap>kaFkcirbk`bBkbjfbpyKyMofk`bHbibpbqe%21+0)24+5&yyNFAy./4/-y

QQebMi^drb_ofkdbo$pObnrbpqyKyKlqeqebMi^drb_ofkdbo%22+6)2/&yyNFAy./4.3y
>Klqe$pPmb`f^i?obtyKyKlqeqebMi^drb_ofkdbo%22+6)2/&yyNFAy./4.4y
@Klqe$pPmb`f^i?obtyKyQ^ihqlqeb`^riaolk)kltqefp_b`ljbp^obmb^q^_ibnrbpqtebkvlre^sb/-X@orp^aboPhriipZyyNFAy./4.4y

@EltQlTfkCofbkap>kaFkcirbk`bBkbjfbpyKyEb^aql%22)31&^kabnrfm_lqeptloap^kaefqqebkb^obpqP`^oibqfkqeb^ob^yyNFAy./4/-y
QEltQlTfkCofbkap>kaFkcirbk`bBkbjfbpyKyMofk`bHbibpbqe%21+0)24+5&yyNFAy./4/-y
>?befkaP`^oibqIfkbpyKyMofk`bHbibpbqe%21+0)24+1&yyNFAy./4/0y

Q?befkaP`^oibqIfkbpyKyLo_^w?illa_^kb%23+0)46+6&^qqebP`^oibqQ^sbokyyNFAy./4/0y
>QebM^qeLcQebOfdeqblrp@orp^aboyKyLo_^w?illa_^kb%23+0)46+6&yyNFAy./4/1y
>?olqebopFkAb^qeyKyQe^pp^of^k%23+0)5-+.&yyNFAy./4/2y

@QebM^qeLcQebOfdeqblrp@orp^aboyKyEb^akloqeqlqebP`^oibqElia%3-)35&Lk`bfkpfabeb^aibcqqebk^ofdeq^karkqfivlrpbb^pq^ofo`^pb+Cliiltqe^qrm)j^hb^ibcqqebk^klqeboofdeq+Qebobpelria_bXKbt>s^ilkM^qoliP`ebaribZlkqebq^_ibfkqeb_^`hlcqebolljyyNFAy./4/1y

Q?olqebopFkAb^qeyKyEb^a_^`haltkqebt^vvlr`^jb)j^hb^ibcq^kaqebob^obpq^fopeb^afkdaltk+Q^ihqlHliqfo^Ab^qetb^sbo^q%30+-)35+.&yyNFAy./4/2y
>?illav?ob^hlrqyKyHliqfo^Ab^qetb^sbo%30+-)35+.&yyNFAy./4/4y
@?illav?ob^hlrqyKyPq^oqqebbsbkqhfiiqebfkqorabop^kapi^vEfdeFknrfpfqloS^iolqeyyNFAy./4/4y

Q?illav?ob^hlrqyKyEb^a_^`hql%23)5-&qlqebP`^oibqQ^sbokyyNFAy./4/4y
>>@ovCloSbkdb^k`byKyQe^pp^of^k%23+0)5-+.&yyNFAy./405y
QQebM^qeLcQebOfdeqblrp@orp^aboyKyLo_^w?illa_^kb%23+0)46+6&yyNFAy./4/1y

Q>@ovCloSbkdb^k`byKyEb^aplrqetbpqqlqeb@e^mbilcqeb@ofjplkCi^jb%20+-)5.+5&Q^ihqlHkfdeq@ljj^kaboMi^drbcfpqyyNFAy./405y
>>Pmb`f^iPromofpbyKyHkfdeq@ljj^kaboMi^drbcfpq%20+-)5.+5&yyNFAy./406yyOyQ^robky
>>Pmb`f^iPromofpbyKyHkfdeq@ljj^kaboMi^drbcfpq%20+-)5.+5&yyNFAy./414yyOy?illaBicy
>>Pmb`f^iPromofpbyKyHkfdeq@ljj^kaboMi^drbcfpq%20+-)5.+5&yyNFAy./415yyOyLo`y
>>Pmb`f^iPromofpbyKyHkfdeq@ljj^kaboMi^drbcfpq%20+-)5.+5&yyNFAy./416yyOyQoliiy
>>Pmb`f^iPromofpbyKyHkfdeq@ljj^kaboMi^drbcfpq%20+-)5.+5&yyNFAy./42-yyOyRkab^ay
@>Pmb`f^iPromofpbyKyBub`rqb^k>odbkqA^tkmofplkbo%12)50&fkpfabqebkb^o_vmofplkelrpb)t^fqrkqfiebcfkfpeq^ihfkdqebkhfiiefjyyNFAy./406yyOyQ^robky
@>Pmb`f^iPromofpbyKyBub`rqb^k>odbkqA^tkmofplkbo%12)50&fkpfabqebkb^o_vmofplkelrpb)t^fqrkqfiebcfkfpeq^ihfkdqebkhfiiefjyyNFAy./414yyOy?illaBicy
@>Pmb`f^iPromofpbyKyBub`rqb^k>odbkqA^tkmofplkbo%12)50&fkpfabqebkb^o_vmofplkelrpb)t^fqrkqfiebcfkfpeq^ihfkdqebkhfiiefjyyNFAy./415yyOyLo`y
@>Pmb`f^iPromofpbyKyBub`rqb^k>odbkqA^tkmofplkbo%12)50&fkpfabqebkb^o_vmofplkelrpb)t^fqrkqfiebcfkfpeq^ihfkdqebkhfiiefjyyNFAy./416yyOyQoliiy
@>Pmb`f^iPromofpbyKyBub`rqb^k>odbkqA^tkmofplkbo%12)50&fkpfabqebkb^o_vmofplkelrpb)t^fqrkqfiebcfkfpeq^ihfkdqebkhfiiefjyyNFAy./42-yyOyRkab^ay
Q>Pmb`f^iPromofpbyKyHkfdeq@ljj^kaboMi^drbcfpq%20+-)5.+5&yyNFAy./406yyOyQ^robky
Q>Pmb`f^iPromofpbyKyHkfdeq@ljj^kaboMi^drbcfpq%20+-)5.+5&yyNFAy./414yyOy?illaBicy
Q>Pmb`f^iPromofpbyKyHkfdeq@ljj^kaboMi^drbcfpq%20+-)5.+5&yyNFAy./415yyOyLo`y
Q>Pmb`f^iPromofpbyKyHkfdeq@ljj^kaboMi^drbcfpq%20+-)5.+5&yyNFAy./416yyOyQoliiy
Q>Pmb`f^iPromofpbyKyHkfdeq@ljj^kaboMi^drbcfpq%20+-)5.+5&yyNFAy./42-yyOyRkab^ay
>>PloqLcEljb`ljfkdyKyHkfdeq@ljj^kaboMi^drbcfpq%20+-)5.+5&yyNFAy./42.y
Q>PloqLcEljb`ljfkdyKyObqrokqlQe^pp^of^kfkqebP`^oibqQ^sbok^q%23)5-&yyNFAy./42.y
>>j_rpe>qQebLsboillhyKyLo_^w?illa_^kb%23+0)46+6&yyNFAy./421y

@>j_rpe>qQebLsboillhyKyEb^ab^pqql%32)42&^karpbXJ^hbpefcq@lsboZ+T^fqclo^kahfiiqebP`^oibq@lrofbo^kamf`hrmefp?bilkdfkdp^kaJbpp^dbyyRy06312yyNFAy./421y

Q>j_rpe>qQebLsboillhyKyObqrokqlLo_^w?illa_^kb%23+0)46+6&qebP`^oibqQ^sbokyyNFAy./421y
>>JbbqfkdTfqeC^qbyKyLo_^w?illa_^kb%23+0)46+6&yyNFAy./422y
Q>JbbqfkdTfqeC^qbyKyEb^aplrqeb^pqqlEfdeDbkbo^i>__bkafp%32+3)50+6&yyNFAy./422y
>QebP`^oibqLkpi^rdeqBjbodbpyKyEfdeDbkbo^i>__bkafp%32+3)50+6&yyNFAy./445y

QQebP`^oibqLkpi^rdeqBjbodbpyKyObqrokqlLo_^w?illa_^kb%23)5-&qebP`^oibqQ^sbokyyNFAy./445y
>P`^oibq>ojfbp>mmol^`e+++yKyLo_^w?illa_^kb%23+0)46+6&yyNFAy./424y

QP`^oibq>ojfbp>mmol^`e+++yKyQ^hbqebmloq^i_^`hqlB_lkElia+Qrok^olrka^kadlqlEfdeiloaA^oflkJldo^fkb%15+6)/6+5&yyNFAy./424y
>QebP`^oibq>ml`^ivmpbyKyEfdeiloaA^oflkJldo^fkb%15+6)/6+5&yyNFAy./445y

QQebP`^oibq>ml`^ivmpbyKyEb^a_^`hqlpq^fop^kaq^hbqebP`lrodbDovmelkqlAb^qe$p?ob^`e%2-)03&yyNFAy./445y
>>kBkaQl>iiQefkdp+++yKyQebIf`eHfkd%2.+0)02+.&yyNFAy./446y

@>kBkaQl>iiQefkdp+++yKyRpbqebXEloklcqebColpq_ollaZ^kaabpqolv.-?^iifpq^^ka.2-P`^oibqPliafbop%22)3.&yyRy064--yyNFAy./446y
Q>kBkaQl>iiQefkdp+++yKyQebIf`eHfkd%2.+0)02+.&yyNFAy./446y
>QebIf`eHfkd$p@ljj^kayKyQebIf`eHfkd%2.+0)02+.&yyNFAy./5--y

QQebIf`eHfkd$p@ljj^kayKyEb^akloqetbpqqeolrdeqeb`^sb%16)/5&Qebkeb^aql?oltj^kJfii^q%01)0-&yyNFAy./5--y
>QebIfdeqlcA^tkyKyT^fqcloqebbsbkqqlpq^oqyyNFAy./5-.y

QQebIfdeqlcA^tkyKyTebkqebbsbkqbkappmb^htfqeEfdeiloaA^oflkJldo^fkb%15+6)/6+5&yyNFAy./5-.y
>Q^hfkd?^`h>`eborpyNFAy.0.32y
QQ^hfkd?^`h>`eborpyKyRpbAb^qeD^qbqldl_^`hqlB_lkeliayyNFAy.0.32y
>Qeb?^qqibCloQebB_lkEliayNFAy.0.33y
@Qeb?^qqibCloQebB_lkEliayKyHfii.-p`lrodb^kapi^vM^q`etbohfkpfabB_lkEliayyNFAy.0.33y

QQeb?^qqibCloQebB_lkEliayKyEb^a_^`hqlEfdeiloaA^oflkJldo^fkb%15+6)/6+5&yyNFAy.0.33y

>T^o`efbc$p?ibppfkdyKyEfdeiloaA^oflkJldo^fkb%15+6)/6+5&yyNFAy.0.56y

QT^o`efbc$p?ibppfkdyKyQ^hbqebmloq^i^kaq^ihqlQeo^ii)eb$pil`^qbafkQebS^iibvlcTfpalj%0/)04+5&*Vlr`^k$qrpbvlrojlrkqvlre^sbqlorkqlefjyyWyLodofjj^oyyNFAy.0.56y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
