
DugisGuideViewer:RegisterGuide("Eastern Plaguelands (56-57)", "Western Plaguelands (57-59)", "Horde", "L", function()
return [[
AAA

OB^pqbokMi^drbi^kapyKyOrkqlB^pqbokMi^drbi^kap%6+0)32+5&yyNFAy221/y
>AbjlkAldpyKyQfoflkCloaofkd%1+4)05+2&yyNFAy221/y
>?illaQfkdbaPhfbpyKyQfoflkCloaofkd%1+4)05+2&yyNFAy2210y
>@^ooflkDor__^dbyKyQfoflkCloaofkd%1+4)05+2&yyNFAy2211y

KHfii^pvlrnrbpq+++yKyHfii^kvmi^drbelrkap)`^ooflktlojp)^kami^drb_^qpvlrbk`lrkqbofkB^pqbokMi^drbi^kapclob^`eobpmb`qfsbnrbpqyyNFAy3-//y
>QlHfiiTfqeMromlpbyKyK^qe^klp?ifdeq`^iibo%/0+-)35+/&yyNFAy3-//y
>Rk*Ifcb$pIfqqib>kklv^k`bpyKyK^qe^klp?ifdeq`^iibo%/0+-)35+/&yyNFAy3-1/y

QPfpqboM^jbi^yKyM^jbi^Obam^qe%0/+2)50+5&yyNFAy23-.y
>M^jbi^$pAliiyKyM^jbi^Obam^qe%0/+2)50+5&yyNFAy2.16y
@M^jbi^$pAliiyKyCfkaXM^jbi^$pAlii$pEb^aZ)XM^jbi^$pAlii$pIbcqPfabZ^kaXM^jbi^$pAlii$pOfdeqPfabZfkqebelrpbpfkA^ooltpefob%02+2)5/+6&%02+2)52+0&%02+-)52+0&yyNFAy2.16y
QM^jbi^$pAliiyKyM^jbi^Obam^qe%0/+2)50+5&yyNFAy2.16y
>>rkqfbJ^oibkbyKyM^jbi^Obam^qe%0/+2)50+5&yyNFAy2.2/y
>Rk`ib@^oifkyKyM^jbi^Obam^qe%0/+2)50+5&yyNFAy2/1.y

HMi^drbelrkapyNFAy221/yyNLyMi^drbelrkaOrkqpi^fk7/-,/-yyKy>iilsboqebplrqetbpqbokpb`qflklcqebwlkby
@?illaQfkdbaPhfbpyKyPi^v0-Mi^drb_^qp+>dlla^ob^fp%22)43&bsbkqelrdevlr`^kcfkaqebj^`olppqebbkqfobPlrqetbpqm^oqlcqebwlkbyyNFAy2210y

QRk`ib@^oifkyKy@^oifkObam^qe%42+4)20+6&yyNFAy2/1.y
>AbcbkaboplcA^ooltpefobyKy@^oifkObam^qe%42+4)20+6&yyNFAy2/..y
QArhbKf`eli^pWsbobkelccyKyArhbKf`eli^pWsbobkelcc%42+3)20+6&yyNFAy3-0-y
>QebObpqibppPlripyKy@^obq^hbo>ibk%40+6)24+4&yyNFAy2/5.y
>W^bia^ooqebLrq`^pqyKy@^obq^hbo>ibk%40+6)24+4&yyNFAy3-/.y

KCobbPmfofqp+++yKyHfii^kv`^kkf_^idelrip)df__bofkddelrip^kaafpb^pbaci^vbopvlr`ljb^`olpp+Pmb^hql^kvdelpqpqe^qpm^tkcloAbcbkaboplcA^ooltpefobyyNFAy2/..y
@AbjlkAldpyKyPi^v/-Mi^drbelrkaOrkqp%04)33&)2Mi^drbelrkap%13)21&^ka2CobkwfbaMi^drbelrkap%16)0/&yyNFAy221/y
@>Mi^drbRmlkQebb%M^oq.&yKyRpbqebXBjmqvQbojfqbG^oZlkqbojfqbjlrkap^ii^`olppqebkloqebokm^oqlcqebwlkb%05)01&yyRy.2-1/yyNFAy26-.y

@QlHfiiTfqeMromlpbyKyHfiiqebP`lrodb^q@lofk$p@olppfkd%22)31&^kaq^hb4XIfsfkdOlqZtfqefk.-jfkrqbp+RpbqebXJloq^o^kaMbpqibZqldofkaqebjb^qfkqlX@l^dri^qbaOlqZyyRy.2121yyNFAy3-//y
@AbcbkaboplcA^ooltpefobyKyCobb.2A^ooltpefobPmfofqp_vq^ihfkdqlqebPmfofqpqe^qpq^v_befka^cqbovlrhfiiqebDelrip^q@lofk$p@olppfkd%22)31&%4.)12&lolqeboDelrip%3-)0-&fkqebwlkbyyNFAy2/..y
@@^ooflkDor__^dbyKyHfii@^ooflkDor_p^kaAbslrobop^iilsboqebB^pqbokMi^drbi^ka%25)1/&clo.2XPi^_lc@^ooflkTlojJb^qZyyNFAy2211y
@Rk*Ifcb$pIfqqib>kklv^k`bpyKyPi^v/-KluflrpMi^drb_^qp%22)2-&^ka.-JlkpqolrpMi^drb_^qp%26+0)04&yyNFAy3-1/y

>>rdrpqrp$Ob`bfmq?llhyKy>rdrpqrpqebQlr`eba%..+1)/5+4&yyNFAy3.31y
@>rdrpqrp$Ob`bfmq?llhyKyQ^hbX>rdrpqrp$Ob`bfmq?llhZrmpq^fopfkqebQbooloa^ibfkk%.1+/)/3+1&yyNFAy3.31y
QQebObpqibppPlripyKyBd^k%..+1)/5+5&yyNFAy2/5.y
Q>rdrpqrp$Ob`bfmq?llhyKy>rdrpqrpqebQlr`eba%..+1)/5+4&yyNFAy3.31y

QAbjlkAldpyKyQfoflkCloaofkd%1+4)05+2&yyNFAy221/y
Q?illaQfkdbaPhfbpyKyQfoflkCloaofkd%1+4)05+2&yyNFAy2210y
Q@^ooflkDor__^dbyKyQfoflkCloaofkd%1+4)05+2&yyNFAy2211y
>ObabjmqflkyKyQfoflkCloaofkd%1+4)05+2&yyNFAy241/y
@ObabjmqflkyKyHbbmq^ihfkdqlQfoflk%1+4)05+2&yyNFAy241/y
QObabjmqflkyKyQfoflkCloaofkd%1+4)05+2&yyNFAy241/y
>LcClodlqqbkJbjlofbpyKyQfoflkCloaofkd%1+4)05+2&yyNFAy245.y

QQlHfiiTfqeMromlpbyKyK^qe^klp?ifdeq`^iibo%/0+-)35+/&yyNFAy3-//y
QRk*Ifcb$pIfqqib>kklv^k`bpyKyK^qe^klp?ifdeq`^iibo%/0+-)35+/&yyNFAy3-1/y

@LcClodlqqbkJbjlofbpyKyEb^aplrqeqlt^oapqebRkabo`olcq%/1+/)46+2&)lmbkqebdo^sb)hfiiJbo`rqfl)illqXQ^bi^k$pE^jjboZ^kadbqlrq_bclobqeb^aapdbqvlryyNFAy245.y
@W^bia^ooqebLrq`^pqyKyHfiiW^bia^oo^qqebO^sbk`olcq%/0+6)45+0&^kaillqXW^bia^oo$pEb^aZyyNFAy3-/.y

QLcClodlqqbkJbjlofbpyKyQfoflkCloaofkd%1+4)05+2&yyNFAy245.y

ERkabo`fqvyRy3615yyNFAy2-16y
Q?bqqboI^qbQe^kKbsboyWyRkabo`fqvyyKyOlv^iLsbopbbo?^re^rp%36+3)10+2&yyNFAy2-/0y
>QebGbobjf^e?irbpyWyRkabo`fqvyyKyOlv^iLsbopbbo?^re^rp%36+3)10+2&yyNFAy2-16y
QQebGbobjf^e?irbpyWyRkabo`fqvyyKyGbobjf^eM^vplk%34+2)11+3&yyNFAy2-16y
>DllaIr`h@e^ojyWyRkabo`fqvyyKyGbobjf^eM^vplk%34+2)11+3&yyNFAy2-2-y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
