DugisGuideViewer:RegisterGuide("Western Plaguelands (56)", "Eastern Plaguelands (56-57)", "Horde", "L", function()
return [[
AAA

ORkabo`fqvyKyDlqlRkabo`fqvyyNFAy2-61y
>>@^iiql>ojp7QebMi^drbi^kapyWyRkabo`fqvyyKyE^o_fkdbo?^iqe^w^a)ebm^qolip^olrkaqeb`bkqbo^kajfaaibofkdplcqeb`fqvyyNFAy2-61y
eRkabo`fqvyKyFkkhbbmboKloj^k%34+4)05+/&yyWyRkabo`fqvyyNFAy2-63y

OQeb?rit^ohyKyOrkqlQeb?rit^ohfkQfofpc^iDi^abp%50+.)36+-&yyWyQfofpc^iDi^abpyyNFAy2-63y
cQeb?rit^ohyKyQfjlqev@rkkfkde^j%50+3)4-&yyWyQfofpc^iDi^abpyyNFAy2-63y
Q>@^iiql>ojp7QebMi^drbi^kapyWyQfofpc^iDi^abpyyKyEfdeBub`rqloAboofkdqlk%50+.)36+-&yyNFAy2-61y
>P`^oibqAfsbopflkpyWyQfofpc^iDi^abpyyKyEfdeBub`rqloAboofkdqlk%50+.)36+-&yyNFAy2-63y
KDbq^Ci^jbfk^?lqqibyWyQfofpc^iDi^abpyyKyColjqeb?lulcFk`bkaf^ofbpyyIy./5.1yyNFAy2-63y
QQebBsboillhObmloqyWyQfofpc^iDi^abpyyKy>odbkqLccf`boD^orpe%50+.)35+3&yyNFAy3-/6y
KDbq^@ljjfppflkyWyQfofpc^iDi^abpyyKyQ^ihql>odbkqLccf`boD^orpe%50+/)35+2&^kadbq^`ljjfppflk)vlrpelriae^sbqefpbnrfmmba^kvqfjbvlr^obfkqebmi^drbi^kap+Qrokfk^kvp`lrodbpqlkbpvlrdbqtebkvlr^obfkqltkfcvlre^sb^criipq^`hyyIy./513yyNFAy6110y
>QebPl*@^iibaJ^ohlcqebIfdeq_ofkdboyWyQfofpc^iDi^abpyyKyJbei^oA^tk_i^ab%50+/)4.+0&yyNFAy6110y
>>Mi^drbRmlkQebb%M^oq.&yKyJf`hbvIbsfkb%50+/)4/+1&yyNFAy26-.yyWyQfofpc^iDi^abpy

R?rokqebqbkqyKy?rokqebqbkqfk^`^jmtfqeqebXCi^jbfk^?lqqibZ%1-)2.&yyRy./5.1yyNFAy2-65y
@P`^oibqAfsbopflkpyKy?rokqebqbkqfk^`^jmtfqeqebXCi^jbfk^?lqqibZ%1-)2.&^kami^kqqebXP`lrodb?^kkboZ%1-)2.&yyRy./5-4yyNFAy2-63y

QP`^oibqAfsbopflkpyWyQfofpc^iDi^abpyyKyEfdeBub`rqloAboofkdqlk%50+.)36+-&yyNFAy2-63y
>>ii>ilkdqebT^q`eqltbopyWyQfofpc^iDi^abpyyKyEfdeBub`rqloAboofkdqlk%50+.)36+-&yyNFAy2-65y
>QebP`lrodb@^riaolkpyWyQfofpc^iDi^abpyyKyEfdeBub`rqloAboofkdqlk%50+.)36+-&yyNFAy2//5y
QQebP`lrodb@^riaolkpyWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2//5y
>Q^odbq7CbipqlkbCfbiayWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2//6y

@Q^odbq7CbipqlkbCfbiayKyEb^ab^pqqlqebCbipqlkbCfbia%04)23&)hfii@^riaolkIloa?fibj^t)illqqebXCbipqlkbCfbia@^riaolkHbvZ^kavlrtfiiklt_b^_ibqlrpbqebXBjmqvCbipqlkbCfbia?lqqibZ_v$q^ihfkd$qlqeb`^riaolkyyNFAy2//6yyRy.0.53y
QQ^odbq7CbipqlkbCfbiayKyP`lrodb@^riaolk%04)23&yyNFAy2//6y
>Obqrokqlqeb?rit^oh%M^oq.&yKyP`lrodb@^riaolk%04)23&yyNFAy2/0-y

>?bqqboI^qbQe^kKbsbo%M^oq.&yKyG^kf`bCbipqlkb%05+1)21+.&yyNFAy2-/.y
Q?bqqboI^qbQe^kKbsbo%M^oq.&yKyG^kf`b$pM^o`bi%05+5)21+6&yyNFAy2-/.y
>?bqqboI^qbQe^kKbsbo%M^oq/&yKyG^kf`b$pM^o`bi%05+5)21+6&yyNFAy2-/0y

QObqrokqlqeb?rit^oh%M^oq.&yWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2/0-y
>Q^odbq7A^iplk$pQb^opyWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2/0.y

@Q^odbq7A^iplk$pQb^opyKyEb^ab^pqqlA^iplk$pQb^op%13)2/&)hfii@^riaolkIloaJ^isfkflrp)illqqebXA^iplk$pQb^op@^riaolkHbvZ^kavlrtfiiklt_b^_ibqlrpbqebXBjmqvA^iplk$pQb^op?lqqibZ_v$q^ihfkd$qlqeb`^riaolkyyNFAy2/0.yyRy.0.54y
QQ^odbq7A^iplk$pQb^opyKyP`lrodb@^riaolk%13)2/&yyNFAy2/0.y
>Obqrokqlqeb?rit^oh%M^oq/&yKyP`lrodb@^riaolk%13)2/&yyNFAy2/0/y

KOb^aJop+A^iplk$pAf^ovyKyLkqebcillofkqeb_^ok%14+5)2-+4&+Klqefkdql^``bmq)grpqob^aqeb_llhyyNFAy2/0/y
HT^kabofkdPhbibqlkyKyM^qolip^olrkaqebelrpb^ka_^ok)vlr^obillhfkdcloqeblrqelrpbhbv+P`^oibqpjfdeqhfiiqefpjl_yyIy./405yyNFAy2/0/y
HC^ojboA^iplkyKyLmbkqeblrqelrpb)dbqefphbvyyIy./406yyNFAy2/0/y
KLmbk`^_fkbqyKyIl`hba`^_fkbqrmpq^fopfkqebelrpbyyNFAy2/0/y

QObqrokqlqeb?rit^oh%M^oq/&yWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2/0/y
>Q^odbq7TofqefkdE^rkqyWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2/00y

@Q^odbq7TofqefkdE^rkqyKyEb^ab^pq^d^fkqlqebTofqefkdE^rkq%20)32&)hfii@^riaolkIloaO^w^o`e)illqqebXTofqefkdE^rkq@^riaolkHbvZ^kavlrtfiiklt_b^_ibqlrpbqebXBjmqvTofqefkdE^rkq?lqqibZ_v$q^ihfkd$qlqeb`^riaolkyyNFAy2/00yyRy.0.55y
QQ^odbq7TofqefkdE^rkqyKyP`lrodb@^riaolk%20)32&yyNFAy2/00y
>Obqrokqlqeb?rit^oh%M^oq0&yKyP`lrodb@^riaolk%20)32&yyNFAy2/01y

>QebTfiaifcbPrccbopQll%M^oq.&yKyJridofpAbbmofsbo%20+4)31+4&yyNFAy1651y
@QebTfiaifcbPrccbopQll%M^oq.&yKyAbpqolv5Afpb^pbaTlisbpqlqebkloqe)_bqtbbkqebCbipqlkb^kaA^iplk$pCfbiap%12)0-&yyNFAy1651y

QObqrokqlqeb?rit^oh%M^oq0&yWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2/01y
>Q^odbq7D^eoolk$pTfqebofkdyWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2/02y

@>ii>ilkdqebT^q`eqltbopyRy./5.2yyKyRpbqebX?b^`lkQlo`eZqlj^oh1qltbopfk>kaloe^i+Klqbqe^qvlrpelriarpbqebX?b^`lkQlo`eZkb^oqebbkqo^k`blcqebqltbo%14)4.&%1-)4.&%1/)33&%11)30&yyNFAy2-65y

QQebTfiaifcbPrccbopQll%M^oq.&yKyJridofpAbbmofsbo%20+4)31+4&yyNFAy1651y
>QebTfiaifcbPrccbopQll%M^oq/&yKyJridofpAbbmofsbo%20+4)31+4&yyNFAy1652y
@QebTfiaifcbPrccbopQll%M^oq/&yKyAbpqolv5Afpb^pbaDofwwifbpqlqebb^pq%20)15&yyNFAy1652y

@Q^odbq7D^eoolk$pTfqebofkdyKyEb^ab^pqqlqebTofqefkdE^rkq%3/)25&)hfii@^riaolkIloaPlrito^qe)illqqebXD^eoolk$pTfqebofkd@^riaolkHbvZ^kavlrtfiiklt_b^_ibqlrpbqebXBjmqvD^eoolk$pTfqebofkd?lqqibZ_v$q^ihfkd$qlqeb`^riaolkyyNFAy2/02yyRy.0.56y
QQ^odbq7D^eoolk$pTfqebofkdyKyP`lrodb@^riaolk%3/)25&yyNFAy2/02y
>Obqrokqlqeb?rit^oh%M^oq1&yKyP`lrodb@^riaolk%3/)25&yyNFAy2/03y

QQebTfiaifcbPrccbopQll%M^oq/&yKyJridofpAbbmofsbo%20+4)31+4&yyNFAy1652y

Q>ii>ilkdqebT^q`eqltbopyWyQfofpc^iDi^abpyyKyEfdeBub`rqloAboofkdqlk%50+.)36+-&yyNFAy2-65y
QObqrokqlqeb?rit^oh%M^oq1&yWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2/03y
>P`elilj^k`byWyQfofpc^iDi^abpyyKyEfdeBub`rqloAboofkdqlk%50+.)36+-&yyNFAy505y
QP`elilj^k`byWyQfofpc^iDi^abpyyKy>mlqeb`^ovAfqebop%50+/)36+0&yyNFAy505y
>Phbibq^iCo^djbkqpyWyQfofpc^iDi^abpyyKy>mlqeb`^ovAfqebop%50+/)36+0&yyNFAy631y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
