
DugisGuideViewer:RegisterGuide("Western Plaguelands (57-59)", "Hellfire Peninsula (60-62)", "Horde", "L", function()
return [[
AAA

CQeb?rit^ohyKyCivqlQeb?rit^ohfkQfofpc^iDi^abp%30+3)15+4&yyWyQfofpc^iDi^abpyyNFAy26-/y
QObqrokqlqeb?rit^oh%M^oq1&yWyQfofpc^iDi^abpyyKyPe^altMofbpqbppS^kafp%50+-)4.+6&yyNFAy2/03y
Q>Mi^drbRmlkQebb%M^oq.&yWyQfofpc^iDi^abpyyKyJf`hbvIbsfkb%50+/)4/+1&yyNFAy26-.y
>>Mi^drbRmlkQebb%M^oq/&yWyQfofpc^iDi^abpyyKyJf`hbvIbsfkb%50+/)4/+1&yyNFAy26-/y
>Jfppflk>``ljmifpebayKyEfdeBub`rqloAboofkdqlk%5/+6)35&yyWyQfofpc^iDi^abpyyNFAy2/04y
QJfppflk>``ljmifpebayKyEfdeBub`rqloAboofkdqlk%5/+6)35&yyWyQfofpc^iDi^abpyyNFAy2/04y

QDllaIr`h@e^ojyKyG^kf`bCbipqlkb%05+1)21+.&yyNFAy2-2-y
>QtlE^isbp?b`ljbLkbyKyG^kf`bCbipqlkb%05+1)21+.&yyNFAy2-2.y
HG^__bofkdDelriyKyHfiiqebG^__bofkdDelri^olrka%05)23+0&^kaillqqebXDllaIr`hLqebo*E^ic*@e^ojZyyIy./4//yyNFAy2-2.y
@QtlE^isbp?b`ljbLkbyKyRpbXDllaIr`hLqebo*E^ic*@e^ojZql`lj_fkbqeb/mfb`bpyyRy./4//yyNFAy2-2.y
QQtlE^isbp?b`ljbLkbyKyG^kf`bCbipqlkb%05+1)21+.&yyNFAy2-2.y

Q>Mi^drbRmlkQebb%M^oq/&yKyQbojfqb?^oobi%15+1)0.+6&yyNFAy26-/y
>>Mi^drbRmlkQebb%M^oq0&yKyQbojfqb?^oobi%15+1)0.+6&yyNFAy306-y

>Rkcfkfpeba?rpfkbpp%M^oq.&yKyHfopq^Abbmpe^alt%2.+6)/5+.&yyNFAy3--1y

@Rkcfkfpeba?rpfkbpp%M^oq.&yKyHfii/P`^oibqJbaf`p)/P`^oibqErkqbop)/P`^oibqJ^df^ka/P`^oibqHkfdeqp^qEb^oqedibk%2-)1/&%2.+2)11&yyNFAy3--1y
QRkcfkfpeba?rpfkbpp%M^oq.&yKyHfopq^Abbmpe^alt%2.+6)/5+.&yyNFAy3--1y
>Rkcfkfpeba?rpfkbpp%M^oq/&yKyHfopq^Abbmpe^alt%2.+6)/5+.&yyNFAy3-/0y

@Rkcfkfpeba?rpfkbpp%M^oq/&yKyHfiiErkqpj^kO^aibv%24+3)03&^ka@^s^ifboArodbk%22)/0&yyNFAy3-/0y
@QebPl*@^iibaJ^ohlcqebIfdeq_ofkdboyKyDbqqebXJ^ohlcqebIfdeq_ofkdboZcolj^`ebpq^qqebqlmlcqebqltbo%21)/0&yyNFAy6110y
QRkcfkfpeba?rpfkbpp%M^oq/&yKyHfopq^Abbmpe^alt%2.+6)/5+.&yyNFAy3-/0y
>Rkcfkfpeba?rpfkbpp%M^oq0&yKyHfopq^Abbmpe^alt%2.+6)/5+.&yyNFAy3-/2y
@Rkcfkfpeba?rpfkbpp%M^oq0&yKyDlqlqlmlcqebqltbo^q%12).5&yyNFAy3-/2y
QRkcfkfpeba?rpfkbpp%M^oq0&yKyHfopq^Abbmpe^alt%2.+6)/5+.&yyNFAy3-/2y

Q>rkqfbJ^oibkbyKyJ^oibkbObam^qe%16+/)45+2&yyNFAy2.2/y
>>Pqo^kdbEfpqlof^kyKyJ^oibkbObam^qe%16+/)45+2&yyNFAy2.20y
@>Pqo^kdbEfpqlof^kyKyDbqXGlpbme$pTbaafkdOfkdZcolj^do^sbpqlkbgrpqkloqelcqebelrpb%16+4)43+6&yyNFAy2.20y
Q>Pqo^kdbEfpqlof^kyKy@eoljfb%06+2)33+5&yyNFAy2.20y
>Qeb>kk^iplcA^ooltpefobyKy@eoljfb%06+2)33+5&yyNFAy2.21y
>>J^qqbolcQfjbyKy@eoljfb%06+2)33+5&yyNFAy164.y

@>J^qqbolcQfjbyKyCfkaqeb_irbdiltvpfilp^qqebbadbplc>kaloe^i%12+-)3/+4&^karpbqebXQbjmlo^iAfpmi^`boZqliroblrqqebtlojp+Hfii.-lcqebjyyRy./3/4yyNFAy164.y
@Qeb>kk^iplcA^ooltpefobyKyDbqqeb_llhX>kk^iplcA^ooltpefobZfkqebqltke^ii%10+6)36+/&lc>kaloe^iyyNFAy2.21y

Q>J^qqbolcQfjbyKy@eoljfb%06+2)33+5&yyNFAy164.y
>@lrkqfkdLrqQfjbyKy@eoljfb%06+2)33+5&yyNFAy164/y
QQeb>kk^iplcA^ooltpefobyKy@eoljfb%06+2)33+5&yyNFAy2.21y
>?olqebo@^oifkyKy@eoljfb%06+2)33+5&yyNFAy2/.-y

@@lrkqfkdLrqQfjbyKyCfka2irk`e_lubpfkqebelrpbp^ii^olrka>kaloe^i%1-)34&^kaillq2X>kaloe^iT^q`eZyyNFAy164/y
@Phbibq^iCo^djbkqpyKyHfiiP`lrodb^iilsbo>kaloe^i%1-)34&^kaillq.2XPhbibq^iCo^djbkqpZyyNFAy631y

Q@lrkqfkdLrqQfjbyKy@eoljfb%06+2)33+5&yyNFAy164/y

Q>Mi^drbRmlkQebb%M^oq0&yWyQfofpc^iDi^abpyyKyJf`hbvIbsfkb%50+/)4/+1&yyNFAy306-y
QPhbibq^iCo^djbkqpyWyQfofpc^iDi^abpyyKy>mlqeb`^ovAfqebop%50+/)36+0&yyNFAy631y
QQebPl*@^iibaJ^ohlcqebIfdeq_ofkdboyWyQfofpc^iDi^abpyyKyJbei^oA^tk_i^ab%50+/)4.+0&yyNFAy6110y
>AbcfifkdRqebo$pQlj_yWyQfofpc^iDi^abpyyKyJbei^oA^tk_i^ab%50+/)4.+0&yyNFAy6111y
@AbcfifkdRqebo$pQlj_yKyBnrfm^karpbX@loormqbaJ^ohlcqebIfdeq_ofkdboZ^qRqebo$pQlj_%2/+.2)50+24&yyRy/036.yyNFAy6111y
QAbcfifkdRqebo$pQlj_yWyQfofpc^iDi^abpyyKyJbei^oA^tk_i^ab%50+/)4.+0&yyNFAy6111y

CIfdeq$pElmb@e^mbiyKyQfjlqev@rkkfkde^j%50+3)4-&yyWyQfofpc^iDi^abpyyNFAy6./3y
QAbcbkaboplcA^ooltpefobyKy@^oifkObam^qe%42+4)20+6&yyNFAy2/..yyWyB^pqbokMi^drbi^kapy
Q?olqebo@^oifkyKy@^oifkObam^qe%42+4)20+6&yyNFAy2/.-yyWyB^pqbokMi^drbi^kapy
>?lkbp`vqebAfdpyKyOle^kqeb>pp^ppfk%42+4)2/+3&yyNFAy6./3yyWyB^pqbokMi^drbi^kapy
Q?lkbp`vqebAfdpyKyOle^kqeb>pp^ppfk%42+4)2/+3&yyNFAy6./3yyWyB^pqbokMi^drbi^kapy
QW^bia^ooqebLrq`^pqyKy@^obq^hbo>ibk%40+4)24+4&yyNFAy3-/.yyWyB^pqbokMi^drbi^kapy
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
