
DugisGuideViewer:RegisterGuide("Hellfire Peninsula (60-62)", "Zangarmarsh (61-64)", "Horde", "L", function()
return [[
AAA

ORkabo`fqvyKyQo^sbiqlRkabo`fqv%33)1/&yyWyRkabo`fqvy
O?i^pqbaI^kapyKyQ^hbqebmloq^iql?i^pqbaI^kapcoljRkabo`fqv%52+0).4+.&yyWyRkabo`fqvy
>QeolrdeqebA^ohMloq^iyWy?i^pqbaI^kapyyKyT^oiloaA^o$qllk%25+-)22+6&yyNFAy61-4y
OEbiicfobMbkfkpri^yKyOrkqeolrdeqlqebA^ohMloq^iqlEbiicfobMbkfkpri^%25+4)3-+0&yyNFAy61-4yyWy?i^pqbaI^kapy
QQeolrdeqebA^ohMloq^iyKyIfbrqbk^kqDbkbo^iLoflk%54+1)16+5&yyNFAy61-4y
>>oofs^ifkLrqi^kayKyIfbrqbk^kqDbkbo^iLoflk%54+1)16+5&yyNFAy.-./-y
Q>oofs^ifkLrqi^kayKySi^dd^Cobvcb^qebo%54+1)15+/&yyNFAy.-./-y
>GlrokbvqlQeo^iij^oyKySi^dd^Cobvcb^qebo%54+1)15+/&yyNFAy.-/56y
CQeo^iij^oyKySi^dd^Cobvcb^qebo%54+1)15+/&yyNFAy.-/56y
QGlrokbvqlQeo^iij^oyKyDbkbo^iHo^hloh%22+6)03+4&yyNFAy.-/56y
>ObmloqqlK^wdobiyKyDbkbo^iHo^hloh%22+6)03+4&yyNFAy.-/6.y
QObmloqqlK^wdobiyKyK^wdobi%22+-)03+-&yyNFAy.-/6.y
>Bo^af`^qbqeb?rokfkdIbdflkyKyK^wdobi%22+-)03+-&yyNFAy.-./.y
eQeo^iij^oyKyCilvaMfkhrp%23+0)03+2&yyNFAy.-./0y

QBo^af`^qbqeb?rokfkdIbdflkyKyPbodb^kqPe^qqbophrii%25+.)1.+0&yyNFAy.-./.y
>Cbipm^ohO^sfkbyKyPbodb^kqPe^qqbophrii%25+.)1.+0&yyNFAy.-./0y
@Cbipm^ohO^sfkbyKyHfii1Ci^jbt^hboFjmp)3Fkcbok^iT^o_ofkdbop^ka.Aob^a`^iibob^pq^qqebCbipm^ohO^sfkb%30)02&yyNFAy.-./0y
QCbipm^ohO^sfkbyKyPbodb^kqPe^qqbophrii%25+.)1.+0&yyNFAy.-./0y
>Clot^oa?^pb7Ob^sbo$pC^iiyKyPbodb^kqPe^qqbophrii%25+.)1.+0&yyNFAy.-./1y
QClot^oa?^pb7Ob^sbo$pC^iiyKyClot^oa@ljj^kaboQl$^o`e%32+6)10+4&yyNFAy.-./1y
>AfpormqQebfoObfkclo`bjbkqpyKyClot^oa@ljj^kaboQl$^o`e%32+6)10+4&yyNFAy.-/-5y
@AfpormqQebfoObfkclo`bjbkqpyKyAbcb^qbkbjfbp^olrkaMloq^iUfirp^kaMloq^iHorriqld^qebo5XAbjlkf`OrkbPqlkbZ^kaqebkrpbXQl$^o`e$pMofjbopZql_iltrmMloq^iHorri%40+6)06+.&^kaMloq^iUfirp%4-+6)12+/&yyRy/5145yyNFAy.-/-5y
QAfpormqQebfoObfkclo`bjbkqpyKyClot^oa@ljj^kaboQl$^o`e%32+6)10+4&yyNFAy.-/-5y
>Jfppflk7D^qbt^vpJrohbqe^kaPe^^ao^wyKyClot^oa@ljj^kaboQl$^o`e%32+6)10+4&yyNFAy.-./6y
@Jfppflk7D^qbt^vpJrohbqe^kaPe^^ao^wyKyQ^ihqlqebTfkd@ljj^kabo%32+5)10+2&^karpbqebXPb^clofrjMR*03BumilpfsbKbqeboJlari^qloZql_lj_qeb/D^qbt^vpyyNFAy.-./6yyRy/5-05y
QJfppflk7D^qbt^vpJrohbqe^kaPe^^ao^wyKyClot^oa@ljj^kaboQl$^o`e%32+6)10+4&yyNFAy.-./6y
>Jfppflk7Qeb>_vpp^iPebicyKyClot^oa@ljj^kaboQl$^o`e%32+6)10+4&yyNFAy.-.3/y
>ObqrokqlQeo^iij^oyKyClot^oa@ljj^kaboQl$^o`e%32+6)10+4&yyNFAy.-055y
@Jfppflk7Qeb>_vpp^iPebicyKyDbqlkqebTvsbok^kakltrpbqebX>ob^2/Pmb`f^iZql_lj_/-D^k$^odMblkp)2Jl$^odLsbopbbop^ka2Cbi@^kklkpyyNFAy.-.3/yyRy/5.0/y
QJfppflk7Qeb>_vpp^iPebicyKyClot^oa@ljj^kaboQl$^o`e%32+6)10+4&yyNFAy.-.3/y

QObqrokqlQeo^iij^oyKyK^wdobi%22+-)03+-&yyNFAy.-055y
>Clodb@^jm7J^dbaalkyKyK^wdobi%22+-)03+-&yyNFAy.-06-y
>?lkb`ebtbo?illayKySroqlh>ub_ob^hbo%22+.)03+0&yyNFAy.-12-y
>FTloh+++CloqebEloabyKyJbdwbdKrhhib_rpq%22+/)05+5&yyNFAy.--53y

@Clodb@^jm7J^dbaalkyKyHfii.-D^k$^odPbos^kqp^kaO^wlop^t%32)0/&^qClodb@^jm7J^dbaalk%31)0/&yyNFAy.-06-y
>SfibMi^kpyKyPq^oqpcoljX?rokfkdIbdflkJfppfsbZ)aolmmba_vO^wlop^tyyNFAy.-060yyRy/6255y
QSfibMi^kpyKyJ^dfpqbo?illae^th%22+.)03+-&yyNFAy.-060y
QClodb@^jm7J^dbaalkyKyK^wdobi%22+-)03+-&yyNFAy.-06-y
>@^kklkplcO^dbyKyK^wdobi%22+-)03+-&yyNFAy.-06.y
@@^kklkplcO^dbyKyAbpqolv0Cbi@^kklkJHFpfkClodb@^jm7O^db%25)0.&yyNFAy.-06.y
Q@^kklkplcO^dbyKyK^wdobi%22+-)03+-&yyNFAy.-06.y
>Allot^vqlqeb>_vppyKyK^wdobi%22+-)03+-&yyNFAy.-06/y
@Allot^vqlqeb>_vppyKyHfii>ofu$>j^i%20)/3&cloqebX?rokfkdIbdflkD^qbHbvZ)^karpbfqlkqeb?rokfkdIbdflkD^qb%20)/5&yyNFAy.-06/yyRy/6462y
QAllot^vqlqeb>_vppyKyK^wdobi%22+-)03+-&yyNFAy.-06/y
>Qeb>dlkv^kaqebA^ohkbppyKyJ^dfpqbo?illae^th%22+.)03+-&yyNFAy.-056y
@?lkb`ebtbo?illayKyHfiiqeb?lkb`ebotboLo`pgrpqplrqelcQeo^iij^oclo./X?lkb`ebtbo?illaZ%25)13&yyNFAy.-12-y
@FTloh+++CloqebEloabyKyD^qebo5mfb`bplcXP^is^dbaJbq^iZ^ka5mfb`bplcXP^is^dbaTllaZ%22+/)00+5&yyNFAy.--53y

QFTloh+++CloqebEloabyKyJbdwbdKrhhib_rpq%22+/)05+5&yyNFAy.--53y
>?rokFqRm+++CloqebEloabyKyJbdwbdKrhhib_rpq%22+/)05+5&yyNFAy.--54y
Q?lkb`ebtbo?illayKySroqlh>ub_ob^hbo%22+.)03+0&yyNFAy.-12-y
>>mlqeb`^ovWbi^k^yKySroqlh>ub_ob^hbo%22+.)03+0&yyNFAy.-116y

@?rokFqRm+++CloqebEloabyKyRpbqebXCi^jfkdQlo`eZqlabpqolvqebqtl`^kklkplkqebplrqepfablcqebM^qelcDilov%3-+6)2/+2&%21+3)21+.&yyNFAy.--54yyRy/4146y

Q>mlqeb`^ovWbi^k^yKy>mlqeb`^ovWbi^k^%33+.)1/+-&yyNFAy.-116y
>Pmfkb_ob^hboMlpqyKy>mlqeb`^ovWbi^k^%33+.)1/+-&yyNFAy.-/1/y

CPmfkb_ob^hboMlpqyKyQ^ihqlTfkd@ljj^kabo?o^`h%33+.)10+5&qlcivqlPmfkb_ob^hboMlpqyyNFAy.-205y
QPmfkb_ob^hboMlpqyKy>mlqeb`^ov>i_ob`h%3.+/)5.+4&yyNFAy.-/1/y
>?lfifkd?illayKy>mlqeb`^ov>i_ob`h%3.+/)5.+4&yyNFAy.-205y
>Mobm^ofkdqebP^isbyKyDobi^d%3.+-)5.+3&yyNFAy6012y
>QebT^omOfcqpyKyLd^qeqebJ^a%3.+5)5.+2&yyNFAy.-/45y
>J^hbQebjIfpqbkyKyBjfpp^ovJloaf_^%3.+4)5.+4&yyNFAy.-//-y
>T^kqba7TlodJ^pqboHorrpeyKyT^kqbaMlpqbo%3.+/)5-+3&yyNFAy.-5-6y

@J^hbQebjIfpqbkyKyHfii./RkvfbiafkdCllqjbk)5RkvfbiafkdHkfdeqp^ka3RkvfbiafkdPlo`bobop^qqebBumbafqflk>ojlov%24)46&qlqebtbpqlcPmfkb_ob^hboMlpqyyNFAy.-//-y

>Ab`fmeboqebQljbyKyQebfqbjX>JvpqboflrpQljbZpq^oqpnrbpqyyRy/522/yyNFAy.-//6y

QJ^hbQebjIfpqbkyKyBjfpp^ovJloaf_^%3.+4)5.+4&yyNFAy.-//-y
QAb`fmeboqebQljbyKy>iqebkqebEfpqlof^k%3.+4)5.+4&yyNFAy.-//6y
>Qeb?^qqibElokyKy>iqebkqebEfpqlof^k%3.+4)5.+4&yyNFAy.-/0-y
@Qeb?^qqibElokyKyHfiiIfbrqbk^kq@ljj^kaboQe^islp^qqebplrqebkalcqebBumbafqflk>ojlov%21+3)50+2&^kaq^hbqebXRkvfbiafkd?^qqibElokZyyNFAy.-/0-y
QQeb?^qqibElokyKy>iqebkqebEfpqlof^k%3.+4)5.+4&yyNFAy.-/0-y
>?illavSbkdb^k`byKy>iqebkqebEfpqlof^k%3.+4)5.+4&yyNFAy.-/2-y

@?illavSbkdb^k`byKy?iltqebXRkvfbiafkd?^qqibElokZqlqebb^pq^qqeb^iif^k`b_^kkbo%30+4)44+0&^kahfiiRoqo^hyyNFAy.-/2-yyRy/532.y
@T^kqba7TlodJ^pqboHorrpeyKyHfiiTlodJ^pqboHorrpe^qWbqe$dlo%35+2)40+3&^kaq^hbqebXTlodJ^pqbo$pEb^aZyyNFAy.-5-6y

QT^kqba7TlodJ^pqboHorrpeyKy@^mq^fkA^ohelti%3-+5)5.+-&yyNFAy.-5-6y
>Wbqe$DloJrpq?rokyKy@^mq^fkA^ohelti%3-+5)5.+-&yyNFAy.-46/y
>QebBvbplcDofiilhyKyWbww^h%3.+3)5.+5&yyNFAy.-5.0y
Q?illavSbkdb^k`byKy>iqebkqebEfpqlof^k%3.+4)5.+4&yyNFAy.-/2-y
>ElkloqebC^iibkyKy>iqebkqebEfpqlof^k%3.+4)5.+4&yyNFAy.-/25y

@Wbqe$DloJrpq?rokyKyHfiimblkpqldbqX?rokfkd?ibbafkdEliiltQlo`ebpZ)ifdeqqebj^qqebclodb%36)36&)qebk_rokqebB^pqbokElsbi%36+.)36+5&)Pq^_ib%35+.)40+0&)TbpqbokElsbi%34+.)42+5&^ka?^oo^`hp%35+6)42+5&yyNFAy.-46/yyRy0.013y
@Mobm^ofkdqebP^isbyKyD^qebo./XEbiicfobPmfkbib^cZ^qqebS^iibvlcqeb?lkbp%3-)4.&yyNFAy6012y
@QebBvbplcDofiilhyKyRpbXWbww^h$pPe^oaZlk^kBvblcDofiilh%34)41&yyNFAy.-5.0yyRy0.130y

QWbqe$DloJrpq?rokyKy@^mq^fkA^ohelti%3-+5)5.+-&yyNFAy.-46/y
QQebBvbplcDofiilhyKyWbww^h%3.+3)5.+5&yyNFAy.-5.0y
>DofiilhA^ohbvbyKyWbww^h%3.+3)5.+5&yyNFAy.-501y
QMobm^ofkdqebP^isbyKyDobi^d%3.+-)5.+3&yyNFAy6012y
>Fksbpqfd^qbqeb@o^peyKyDobi^d%3.+-)5.+3&yyNFAy.-/.0y

QElkloqebC^iibkyKy@ljj^kaboEld^oqe%23+6)44+1&yyNFAy.-/25y

QFksbpqfd^qbqeb@o^peyKyP`ob^jfkdP`obbaIr`hebba%16+.)41+5&yyNFAy.-/.0y
>Fk@^pblcBjbodbk`v+++yKyP`ob^jfkdP`obbaIr`hebba%16+.)41+5&yyNFAy.-.3.y
>O^s^dboBddOlrkarmyKyIbd^ppf%16+/)41+5&yyNFAy6016y
@O^s^dboBddOlrkarmyKyObqofbsb./XO^s^dboBddpZcoljqebO^wloqelokQo^fiqlqebplrqetbpq%1/)52&yyNFAy6016y
QO^s^dboBddOlrkarmyKyIbd^ppf%16+/)41+5&yyNFAy6016y
>Ebi_l^o)qebLqeboTefqbJb^qyKyIbd^ppf%16+/)41+5&yyNFAy603.y

@Ebi_l^o)qebLqeboTefqbJb^qyKyHfiiEbi_l^opcloqebfoq^fkqbajb^q^kaqebkrpbqebXMrofcf`^qflkJfuqrobZqlmrofcvqebjb^qyyRy/0/35yyNFAy603.y
@Fk@^pblcBjbodbk`v+++yKy@liib`q0-XWbmmbifkAb_ofpZ^olrka%3-)4.&yyNFAy.-.3.y
QEbi_l^o)qebLqeboTefqbJb^qyKyIbd^ppf%16+/)41+5&yyNFAy603.y
QFk@^pblcBjbodbk`v+++yKyP`ob^jfkdP`obbaIr`hebba%16+.)41+5&yyNFAy.-.3.y
>Slfat^ihbopDlkbTfiayKyP`ob^jfkdP`obbaIr`hebba%16+.)41+5&yyNFAy602.y
@QebT^omOfcqpyKyRpbqebXRkpq^_ibT^omOfcqDbkbo^qloZfkqebT^omCfbiap%13+2)5.+2&)hfiiqebRkpq^_ibSlfat^ihbopqe^q`ljbqeolrde^ka`liib`q0XT^omKbqeboZyyNFAy.-/45yyRy/6-/4y
@Slfat^ihbopDlkbTfiayKyHfiiqebSlfap^qqebT^omCfbiapclo.-X@lkabkpbaSlfat^ihboBppbk`bZ^olrka%13+2)5.+2&yyNFAy602.y
QSlfat^ihbopDlkbTfiayKyP`ob^jfkdP`obbaIr`hebba%16+.)41+5&yyNFAy602.y

QQebT^omOfcqpyKyLd^qeqebJ^a%3.+5)5.+2&yyNFAy.-/45y
>SlfaOfadbyKyLd^qeqebJ^a%3.+5)5.+2&yyNFAy.-/61y

@DofiilhA^ohbvbyKyHfiiDofiilhfkqeb`^sb_biltWbqe$Dlo%33+0)4.+/&^kaq^hbXDofiilh$pBvbm^q`eZ^pmollcyyNFAy.-501y
@?lfifkd?illayKyHfiilo`pfcvlralk$qe^sb./X?ibbafkdEliilt?illaZ)qebk$q^ih$qlqeb`^riaolklrqpfabqeb`^sbqlob`bfsb./X?lfiba?illaZ%32+.)4.+/&yyNFAy.-205y

@SlfaOfadbyKyDlqlSlfaOfadb%43)32&^kahfiiqebSlfat^ihbopclo1-XSlfaOfadbPlriPe^oaZyyNFAy.-/61y

Q?lfifkd?illayKy>mlqeb`^ov>i_ob`h%3.+/)5.+4&yyNFAy.-205y
>>mlqeb`^ov>kqlkfsf`eyKy>mlqeb`^ov>i_ob`h%3.+/)5.+4&yyNFAy.-502y
QDofiilhA^ohbvbyKyWbww^h%3.+3)5.+5&yyNFAy.-501y
QSlfaOfadbyKyLd^qeqebJ^a%3.+5)5.+2&yyNFAy.-/61y
>Coljqeb>_vppyKyLd^qeqebJ^a%3.+5)5.+2&yyNFAy.-/62y
@Coljqeb>_vppyKyRpbqebXT^omOfcqDbkbo^qloZ^qqebmromib`ovpq^ip^qqebplrqebkalcSlfaOfadb%5-+5)45+4&^kapi^vSlfa?^olkD^i^ufp+Q^hbXD^i^ufpPlriPe^oaZyyNFAy.-/62yyRy/6//3y
QColjqeb>_vppyKyLd^qeqebJ^a%3.+5)5.+2&yyNFAy.-/62y

Q?rokFqRm+++CloqebEloabyKyJbdwbdKrhhib_rpq%22+/)05+5&yyNFAy.--54y
Q>mlqeb`^ov>kqlkfsf`eyKy>mlqeb`^ov>kqlkfsf`e%2/+1)03+2&yyNFAy.-502y
>>?roabklcPlripyKy>mlqeb`^ov>kqlkfsf`e%2/+1)03+2&yyNFAy.-531y

>Lrqi^kaPr`hpyKyClobj^kO^wbi`o^w%2.+0)0-+3&yyNFAy.-/03y
@Lrqi^kaPr`hpyKyDbqqebXPeobaaboPm^obM^oqpZplrqetbpqfkqebo^sfkb%15+0)1-&yyNFAy.-/03y
>JfppfkdJfppfsbyRy/0005yyNFAy6040yyLyyKyQebfqbjXBolabaIb^qebo@^pbZpq^oqpnrbpq*aolmmba_vJ^o^rafkd@orpq?ropqbop^olrka%14)10&y
QLrqi^kaPr`hpyKyClobj^kO^wbi`o^w%2.+0)0-+3&yyNFAy.-/03y
>EltqlPbosbDl_ifkpyKyClobj^kO^wbi`o^w%2.+0)0-+3&yyNFAy.-/05y
@EltqlPbosbDl_ifkpyKyObp`rbqebdl_ifkpJ^kkf%12+-)1-+6&)Jle%13+2)12+-&^kaG^hh%14+2)13+2&yyNFAy.-/05y
@>?roabklcPlripyKyHfii/-Pe^qqbobaE^kalo`p%12)12&yyNFAy.-531y
QEltqlPbosbDl_ifkpyKyClobj^kO^wbi`o^w%2.+0)0-+3&yyNFAy.-/05y
>PefwwTlohyKyClobj^kO^wbi`o^w%2.+0)0-+3&yyNFAy.-3/6y
@PefwwTlohyRy0-5-0yyKyRpbqebXCbielrkaTefpqibZqlprjjlk^CbiDr^oaElrka)hfiiqebebi_l^op%2-)0-&^kaillqqebXPeobaaboHbvpZcoljqebCbielrkamllmyyRy0-5-0yyNFAy.-3/6y
QPefwwTlohyKyClobj^kO^wbi`o^w%2.+0)0-+3&yyNFAy.-3/6y
>?bkb^qeQeo^iij^oyKyClobj^kO^wbi`o^w%2.+0)0-+3&yyNFAy.-30-y
@?bkb^qeQeo^iij^oyKyHfiiRod^wfkqebjfkbofdeqkbuqqlqebnrbpqdfsbo%2.+3)0.+4&yyNFAy.-30-y
Q?bkb^qeQeo^iij^oyKyClobj^kO^wbi`o^w%2.+0)0-+3&yyNFAy.-30-y

Q>?roabklcPlripyKy>mlqeb`^ov>kqlkfsf`e%2/+1)03+2&yyNFAy.-531y
>Qeb>pp^ppfkyNFAy61--yyKyK^wdobi%22+-)03+-&)qefpnrbpqobnrfobpibsbi3-y
>C^i`lkT^q`eyNFAy6165yyKyJ^oqfhQlo$pbialof%22+/)06+-&)qefpnrbpqobnrfobpibsbi3-yyOyLo`)Q^robk)Rkab^a)Qolii)Dl_ifky
>C^i`lkT^q`eyNFAy6166yyKyJ^oqfhQlo$pbialof%22+/)06+-&)qefpnrbpqobnrfobpibsbi3-yyOy?illaBicy
>QebAbjlkf^`P`ovboyKy>mlqeb`^ov>kqlkfsf`e%2/+1)03+2&yyNFAy.-505y
@QebAbjlkf^`P`ovboyKyRpbqebXAbjlkf^`P`ovboZfkqebEbiicfob?^pfk)grpqqlqebtbpqlcEbiicfob@fq^abi%11+1)2.+3&^kaabcbkafqtefibfq^qqrkbp)qebkq^ihqlfqtebkfqfp`ljmibqbqlob`bfsbqebXAbjlkf^`P`ovboOb^afkdZyyNFAy.-505yyRy0.3-3y

OC^i`lkT^q`eyKyTbpqqlqebol^a)qebkplrqe%/4)3-&yyNFAy6064y
>?foaplc^Cb^qeboyKyC^i`lkboAobkk^Ofsbotfka%/4+4)3-+1&yyNFAy6064y
QC^i`lkT^q`eyKyO^kdbo@^mq^fkSbkk$obk%/5+2)3-+/&yyNFAy6165yyOyLo`)Q^robk)Rkab^a)Qolii)Dl_ifky
QC^i`lkT^q`eyKyO^kdbo@^mq^fkSbkk$obk%/5+2)3-+/&yyNFAy6166yyOy?illaBicy
>QebDob^qCfpprobyKyO^kdbo@^mq^fkSbkk$obk%/5+2)3-+/&yyNFAy601-y
>J^df`lcqeb>o^hhl^yKy>o`^kfpq@^ibpqeofpA^tkpq^o%/4+-)26+5&yyNFAy6063y

@QebDob^qCfpprobyKyPi^v5Pqlkbp`vqebTebimp^ka0Pqlkbp`vqeb>ime^p^qqebDob^qCfpprobqlqebb^pq%/6)26&yyNFAy601-y
@?foaplc^Cb^qeboyKyRpbqebXBjmqv?foa`^dbZlk^Cbj^ibH^ifofE^q`eifkd^qqebAbklcE^^i$bpe%/4)5-&yyNFAy6064yyRy/0152y
H>sorryIy/025-yyKyEbm^qolip^olrkaqebibadb^_lsbqebjfaaiblcqebs^iibv%/2)42&yyNFAy61.5y
>>sorr$pLo_yRy/025-yyKyQebfqbjX>sorr$pLo_Zpq^oqpnrbpq*aolmmba_v>sorr%/2)42&yyNFAy61.5y
@>sorr$pLo_yKyQ^hbqeblo_qlqeb^iq^o^_fqplrqe%/6)5.&yyNFAy61.5y
Q>sorr$pLo_yKy>bo^k^p%/5+6)5.+2&yyNFAy61.5y
@J^df`lcqeb>o^hhl^yKyHfiiqeb>o^hhl^clo1XE^^i$bpefP`oliiZyyNFAy6063y
>QebOl^aqlC^i`lkT^q`eyKyTlrkaba?illaBicMfidofj%/1+3)43+-&+Obnrfobpibsbi3.yyNFAy6042y

QQebOl^aqlC^i`lkT^q`eyKyQ^ibofpA^tkd^wbo%/3+1)3.+5&yyNFAy6042y
>>Mfidofj$pMifdeqyKyQ^ibofpA^tkd^wbo%/3+1)3.+5&yyNFAy6043y
QQebDob^qCfpprobyKyO^kdbo@^mq^fkSbkk$obk%/5+2)3-+/&yyNFAy601-y
>J^ohfkdqebM^qeyKyO^kdbo@^mq^fkSbkk$obk%/5+2)3-+/&yyNFAy606.y
QJ^df`lcqeb>o^hhl^yKy>o`^kfpq@^ibpqeofpA^tkpq^o%/4+-)26+5&yyNFAy6063y
Q?foaplc^Cb^qeboyKyC^i`lkboAobkk^Ofsbotfka%/4+4)3-+1&yyNFAy6064y

@>Mfidofj$pMifdeqyKyCfkaXQlokMfidofj$pM^`hZqlqebtbpq^q^`^jmpfqbfkArpqnrfiiO^sfkb%//+.)35+1&yyNFAy6043y
@J^ohfkdqebM^qeyKyRpbqebXIfqQlo`eZqlifdeqqebqeobb_b^`lkpaltkfkqebDob^qCfpprob+Tbpq%/6)3-&)@bkqo^i%01)3-&)Plrqebok%03)32&yyNFAy606.yyRy/015-y

QJ^ohfkdqebM^qeyKyO^kdbo@^mq^fkSbkk$obk%/5+2)3-+/&yyNFAy606.y
Q>Mfidofj$pMifdeqyKyQ^ibofpA^tkd^wbo%/3+1)3.+5&yyNFAy6043y
>Ebimfkdqeb@bk^oflkMlpqyKyC^i`lkboAobkk^Ofsbotfka%/4+4)3-+1&yyNFAy.-11/y
>>obiflk$pGlrok^iyKyJ^dfpqofu@^ofka^%/3+1)3-+1&yyNFAy6041y
>Plro`blcqeb@loormqflkyKy>mlqeb`^ov>wbqebk%/3+5)26+5&yyNFAy6054y
>FkKbbalcCbi_illayKyOv^qebkqebPlj_bo%/4+-)26+3&yyNFAy6033y
>Qorbcifdeq>ooltpyKyC^i`lkboAobkk^Ofsbotfka%/4+4)3-+1&yyNFAy605.y
>ObmloqqlWro^fyKyO^kdbo@^mq^fkSbkk$obk%/5+2)3-+/&yyNFAy.-.-0y

@Qorbcifdeq>ooltpyKyD^qebo5X?lkbpqofmmboQ^fiCb^qeboZcolj?lkbpqofmmboSriqrobparbkloqelcC^i`lk@obpq%/3)14&yyNFAy605.y

QQeb>pp^ppfkyKyHorkPmfkb_ob^hbo$p`lompbqlqebkloqe%00+3)10+3&yyNFAy61--y
>>Pqo^kdbTb^mlkyKyCbiLo`@lompb%00+3)10+3&yyNFAy61-.y

@>obiflk$pGlrok^iyKyDbqX>obiflk$pGlrok^iZfkqebMlliplc>ddlk^o)e^kdfkdcolj^qobbifj_%1-+-)04+0&yyNFAy6041y
@FkKbbalcCbi_illayKyD^qebo3XCbi_illaP^jmibpZcoljqebQboolocfbkapqe^qfke^_fqqebMlliplc>ddlk^o%06)1-&yyNFAy6033y
@Qeb>dlkv^kaqebA^ohkbppyKyHfii.-QboolocfbkapfkqebMlliplc>ddlk^o%06)1-&yyNFAy.-056y

QQebAbjlkf^`P`ovboyKy>mlqeb`^ov>kqlkfsf`e%2/+1)03+2&yyNFAy.-505y
>ObmloqqlK^wdobiyKy>mlqeb`^ov>kqlkfsf`e%2/+1)03+2&yyNFAy.-542y
QObmloqqlK^wdobiyKyK^wdobi%22+-)03+-&+Phfmcliilt*rmyyNFAy.-542y
Q>Pqo^kdbTb^mlkyKyK^wdobi%22+-)03+-&yyNFAy61-.y
>QebT^o`efbc$pJ^ka^qbyKyK^wdobi%22+-)03+-&yyNFAy61-2y
QQeb>dlkv^kaqebA^ohkbppyKyJ^dfpqbo?illae^th%22+.)03+-&yyNFAy.-056y
QQebT^o`efbc$pJ^ka^qbyKyC^oPbboObdrihrq%21+0)04+6&yyNFAy61-2y
>>PmfofqDrfabyKyC^oPbboObdrihrq%21+0)04+6&yyNFAy61.-y

@>PmfofqDrfabyKyRpbqebX>k`bpqo^iPmfofqTlicQlqbjZ^qHorkPmfkb_ob^hbo$p`lompb%00+3)10+3&)^kacliiltqebtlicyyNFAy61.-yyRy/0336y
Q>PmfofqDrfabyKyDloh^k?illacfpq%0/+.)/4+5&yyNFAy61.-y
>QebJ^d$e^oyKyDloh^k?illacfpq%0/+.)/4+5&yyNFAy61-3y

QQebJ^d$e^oyKyK^wdobi%22+-)03+-&yyNFAy61-3y
>JbppbkdboqlQeo^iiyKyK^wdobi%22+-)03+-&yyNFAy6105y

QQorbcifdeq>ooltpyKyC^i`lkboAobkk^Ofsbotfka%/4+4)3-+1&yyNFAy605.y
Q>obiflk$pGlrok^iyKyJ^dfpqofu@^ofka^%/3+1)3-+1&yyNFAy6041y
>>obiflk$pPb`obqyKyJ^dfpqofu@^ofka^%/3+1)3-+1&yyNFAy.-/53y
QFkKbbalcCbi_illayKyOv^qebkqebPlj_bo%/4+-)26+3&yyNFAy6033y
>Qeb@ib^kpfkdJrpq?bPqlmmbayKyOv^qebkqebPlj_bo%/4+-)26+3&yyNFAy604-y

@Qeb@ib^kpfkdJrpq?bPqlmmbayKyRpbqebXPfdk^ifkdDbjZ^qqeb>iq^olc>ddlk^o%06)1-&^kaabcb^qqebAo^bkbf>k`elofqbpyyRy/0025yyNFAy604-y

>K^i^aryKyJlolaqebTfkapqfoobo%.0+.)3.+-&yyNFAy.-1-0y
QK^i^aryKyK^i^ar)rmqebpq^fop)fk^erqqlqebplrqeb^pq%.3+/)32+-&yyNFAy.-1-0y
>>Qo^fqlo>jlkdRpyKyK^i^ar%.3+/)32+-&yyNFAy.-034y
@>Qo^fqlo>jlkdRpyKyDbqqebXPe^$k^^oHbvZfkqeberq_^`h^qqebqlmlcqebpq^fop%.1+0)30+1&yyNFAy.-034y
Q>Qo^fqlo>jlkdRpyKyK^i^ar%.3+/)32+-&yyNFAy.-034y
>QebAobdellaBiabopyKyK^i^ar%.3+/)32+-&yyNFAy.-035y
@QebAobdellaBiabopyKyCobbqebbiabop)Jlola%.0+.)3.+-&^ka>vi^^k%.0+-)25+1&qlqebtbpq)^ka>hlor%.2+2)25+4&qlqebb^pqyyNFAy.-035y
QQebAobdellaBiabopyKyK^i^ar%.3+/)32+-&yyNFAy.-035y
>>owbqe$pAbjfpbyKyK^i^ar%.3+/)32+-&yyNFAy.-036y
@>owbqe$pAbjfpbyRy/62.0yyKyRpbqebXPq^cclcAobdellaBiabopZlk>owbqeqebJbo`fibpp^kapi^vefj^cqboeb$pilpqefpmltbop%.2)25&yyNFAy.-036y
Q>owbqe$pAbjfpbyKyK^i^ar%.3+/)32+-&yyNFAy.-036y
@Plro`blcqeb@loormqflkyKyL_q^fk2XAbjlkf`Bppbk`bpZcoljqebFiifa^ofQ^phj^pqbop%.2)3-&yyNFAy6054y

QEbimfkdqeb@bk^oflkMlpqyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy.-11/y
>Abjlkf`@lkq^jfk^qflkyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy604/y
Q>obiflk$pPb`obqyKyJ^dfpqbo>ibafpqo^sbipcoljC^i`lkT^q`e%/2+-)30+.&qlW^kd^oj^ope%1+3)2-+4&yyNFAy.-/53y
>QebJfpqobppObsb^ibayKyJ^dfpqbo>ibafpqo^sbipcoljC^i`lkT^q`e%/2+-)30+.&qlW^kd^oj^ope%1+3)2-+4&yyNFAy.-/54y
QJfppfkdJfppfsbyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy6040yyLy
>HbbmQelokc^kdEfii@ib^oyKyJ^ero^jPqlrqellc%.2+5)2/+0&yyNFAy.-.26y
>Qeb@bk^oflkBumbafqflkyKy>jvqefbiJfpqt^ihbo%.3+-)2/+/&yyNFAy66./y
>@lilpp^iJbk^`byKyQli^$qeflk%.2+/)2/+.&yyNFAy.-.0/y
@Abjlkf`@lkq^jfk^qflkyKyHfiiebi_l^opclo3XEbi_l^o?illaP^jmibZ^olrka%/1)25&yyNFAy604/y
QAbjlkf`@lkq^jfk^qflkyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy604/y
>Qbpqfkdqeb>kqfalqbyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy.-/22y
@Qbpqfkdqeb>kqfalqbyKyRpbqebX@bk^oflk>kqfalqbZlk^kb^o_vEbi_l^o%.2)2-&yyNFAy.-/22yyRy/0004y
QQbpqfkdqeb>kqfalqbyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy.-/22y
@@lilpp^iJbk^`byKyHfii2O^dfkd@lilpprp%.3)10&yyNFAy.-.0/y
>@ofjplk@ovpq^i@irbyKyHbbmhfiifkdO^dfkd@lilpprprkqfivlrcfkaX@ofjplk@ovpq^iPe^oaZqlpq^oqnrbpq%.3)10&yyRy/6143yyNFAy.-.01y
Q@lilpp^iJbk^`byKyQli^$qeflk%.2+/)2/+.&yyNFAy.-.0/y
Q@ofjplk@ovpq^i@irbyKyQli^$qeflk%.2+3)2/+.&yyNFAy.-.01y
>QebB^oqe_fkaboyKyQli^$qeflk%.2+3)2/+.&yyIy.-016yyNFAy.-016y
QQebB^oqe_fkaboyKyB^oqe_fkaboD^i^kaof^Kfdeq_obbwb%.2+6)2.+3&yyNFAy.-016y
>K^qro^iObjbafbpyKyB^oqe_fkaboD^i^kaof^Kfdeq_obbwb%.2+6)2.+3&yyNFAy.-02.y
@K^qro^iObjbafbpyKyPfk`bm^q`e0+-+/qefpnrbpqe^p_bbkmobqqvb^pvqlplilclojlpq`i^ppbp)vlr`^kphfmqefpnrbpqfcvlr$obrk^_ibqlalfq^ilkb)`ib^oqeb^ob^^olrka%.0)06&qebkmi^kqqebXPbbalcObsfq^ifw^qflkZlkqeboba`fo`ib+Cl`rplkhfiifkdqeb_lpp)jlob^aaptfii^mmb^o_rqvlrtfii`ljmibqbqebnrbpq^pilkd^pvlrhfiiqeb_lppyyRy/6145yyNFAy.-02.y
QK^qro^iObjbafbpyKyB^oqe_fkaboD^i^kaof^Kfdeq_obbwb%.2+6)2.+3&yyNFAy.-02.y

@HbbmQelokc^kdEfii@ib^oyKyHfii5Qelokc^kdO^s^dbop^ka5Qelokc^kdSbkljpmfqqbopqlqebtbpq)^qQelokc^kdEfiiyyNFAy.-.26y
QHbbmQelokc^kdEfii@ib^oyKyJ^ero^jPqlrqellc%.2+5)2/+0&yyNFAy.-.26y

QPlro`blcqeb@loormqflkyKy>mlqeb`^ov>wbqebk%/3+5)26+5&yyNFAy6054y
QQebJfpqobppObsb^ibayKyJ^dfpqofu@^ofka^%/3+1)3-+1&yyNFAy.-/54y
>>obiflk$pJfpqobppyKyJ^dfpqofu@^ofka^%/3+1)3-+1&yyNFAy614/y
QQeb@ib^kpfkdJrpq?bPqlmmbayKyOv^qebkqebPlj_bo%/4+-)26+3&yyNFAy604-y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
