DugisGuideViewer:RegisterGuide("Zangarmarsh (61-64)", "Terokkar Forest (63-65)", "Horde", "L", function()
return [[
AAA

O@bk^oflkObcrdbyKyOrkql@bk^oflkObcrdb%45)31&yyNFAy6414y
>QebRj_o^cbkQof_byKyFhbvbk%5-+1)31+/&yyNFAy6414y
>Mi^kqplcW^kd^oj^opeyKyI^ro^kk^Qe^o$tbii%5-+0)31+0&yyNFAy65-/y
>QebAvfkd?^i^k`byKyIbqevkJllkcfob%45+3)30+.&yyNFAy6562y
>Afpqro_^k`b^qRj_o^cbkI^hbyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64.3y
>T^oabkE^jllqyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy6445y
>Ib^abolcqebA^oh`obpqyKyT^kqbaMlpqbo%46+.)31+5&yyNFAy640-y
>Ib^abolcqeb?illap`^ibyKyT^kqbaMlpqbo%46+.)31+5&yyNFAy65.4y
e@bk^oflkObcrdbyKyFkkhbbmbo@lovqePqlhqolk%45+3)30&yyNFAy64/5y
QQeb@bk^oflkBumbafqflkyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy66./y
QT^oabkE^jllqyKyT^oabkE^jllq%46+-)32+0&yyNFAy6445y
>>T^ojTbi`ljbyKyT^oabkE^jllq%46+-)32+0&yyNFAy64/5y
?X@bk^oflkPmfofqpZyKy?rvX@bk^oflkPmfofqpZcoljFkkhbbmbo@lovqePqlhqolk%45+3)30&cloqebnrbpq>obiflk$pJfpqobppi^qboyyNFAy611.y

OPe^qqo^qe@fqvyKyOrkplrqealtkqebol^a%50+4)66+.&yyNFAy611.y
OLodofjj^oyKyQ^hbqebmloq^iqlLodofjj^o%2/+/)2/+6&yyWyPe^qqo^qe@fqvyyNFAy611.y
QJbppbkdboqlQeo^iiyWyLodofjj^oyyKyQeo^ii)S^iibvlcTfpalj%0/+-)04+5&yyNFAy6105y
>BkslvqlqebJ^d$e^oyWyLodofjj^oyyKyQeo^ii)S^iibvlcTfpalj%0/+-)04+5&yyNFAy611.y
E@bk^oflkObcrdbyRy3615yyNFAy6441y

OPt^jmo^qMlpqyKyOrkqlPt^jmo^qMlpq%52)21&yyNFAy6441y
QObmloqqlWro^fyKyWro^f%52+/)21+4&yyNFAy.-.-0y
>Qef`hEvao^P`^ibpyKyWro^f%52+/)21+4&yyNFAy6441y
>Jbk^`fkdJ^opec^kdpyKyOb^sfg%52+-)21+.&yyNFAy644-y
>Qebob$pKlBumi^k^qflkcloC^peflkyKyJ^d^pe^%51+2)22+1&yyNFAy6436y
>KlJlobJrpeolljpyKyJ^d^pe^%51+2)22+1&yyNFAy6440y

@QebRj_o^cbkQof_byKyDlqlRj_o^cbkSfii^db%5/)50&^kapi^vH^q^or%52)6-&)5Rj_o^cbkPbbop)3Rj_o^cbkTfq`eal`qlop^ka3Rj_o^cbkLo^`ibpyyNFAy6414y
>Bp`^mbcoljRj_o^cbkyKyH^vo^Ilkdj^kb%50+0)52+2&yyNFAy642/y
@QebAvfkd?^i^k`byKyCfka^kahfii?ldi^petelm^qolip^olrka%5/)4/&alqefptefibbp`loqfkdH^vo^^kapebtfiiebimvlrhfii?ldi^peyyNFAy6562y
@Bp`^mbcoljRj_o^cbkyKyBp`loqH^vo^%5.+0)43+4&yyNFAy642/y
@Qebob$pKlBumi^k^qflkcloC^peflkyKyHfiiqebCfobcifbp%4/)26&^kaillq5lcqebfoXAf^me^klrpTfkdZyyNFAy6436y
@Jbk^`fkdJ^opec^kdpyKyHfii.-J^opec^kdOfmmbop%51)2-&yyNFAy644-y
@KlJlobJrpeolljpyKyD^qebo5XBbiCfibqZcoljRj_o^cbkBbipfkqebi^hbplrqetbpqlcqebobcrdb%42)40&yyNFAy6440y
@Qef`hEvao^P`^ibpyKyHfiiEvao^$p^olrkaqebbadblcqebi^hb%44)4-&clo./XQef`hEvao^P`^ibZyyNFAy6441y
@Afpqro_^k`b^qRj_o^cbkI^hbyKyFksbpqfd^qbRj_o^cbkI^hb_vdlfkdkb^oqebMrjm%4-)5-&yyNFAy64.3y
@Mi^kqplcW^kd^oj^opeyKy@liib`q.-XRkfabkqfcfbaMi^kqM^oqpZaolmmba_vj^kvhfkaplcjl_pfkW^kd^oj^ope+Bu^jmibil`^qflk%4-)5-&yyNFAy65-/y

QQebAvfkd?^i^k`byKyIbqevkJllkcfob%45+3)30+.&yyNFAy6562y
QAfpqro_^k`b^qRj_o^cbkI^hbyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64.3y
QBp`^mbcoljRj_o^cbkyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy642/y
QMi^kqplcW^kd^oj^opeyKyI^ro^kk^Qe^o$tbii%5-+0)31+0&yyNFAy65-/y
QQebRj_o^cbkQof_byKyFhbvbk%5-+1)31+/&yyNFAy6414y
>>A^jm)A^ohMi^`byKyFhbvbk%5-+1)31+/&yyNFAy6455y
>P^sfkdqebPmlobilhpyKyI^ro^kk^Qe^o$tbii%5-+0)31+0&yyNFAy.--63y
>P^cbdr^oafkdqebT^q`ebopyKyTfka`^iibo?i^`hellc%5-+1)31+4&yyNFAy6561y
>>pqeb@oltCifbpyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64.5y
@>pqeb@oltCifbpyKyRpbqebXPqloj`olt>jribqZ%45+1)3/+-&yyRy/2132yyNFAy64.5y
Q>pqeb@oltCifbpyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64.5y
>?^i^k`bJrpq?bMobpbosbayKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64/-y

@>A^jm)A^ohMi^`byKyPlrqelcRj_o^cbkI^hb%41)6.&XFhbvbk$p?bilkdfkdpZ%4-+3)64+6&`^k_bclrkalk^ol`hfkqeb_^`hlcqebCrkddlo@^sbok)yyNFAy6455y
@P^cbdr^oafkdqebT^q`ebopyKyHfiiIloaHi^n^qqeb_lqqljlcqebCrkddlo@^sbok%4/)61&yyNFAy6561y
@P^sfkdqebPmlobilhpyKyPi^v.-J^opeAobadbop^ka.-J^opeIrohbop^qqebCrkddlo@^sbok%41)6.&yyNFAy.--63y

KAfp^_ibRj_o^cbkMrjmyKyRpbqebpbbap^qqeb`lkqolipqlqebRj_o^cbkI^hbmrjm%4-)5-&yyRy/1022yyNFAy64/-yyNLyRj_o^cbkI^hb@lkqolipAfp^_iba7.,.y
@Ib^abolcqebA^oh`obpqyKyCfka^kaHfiiO^g^eE^de^wba%32)35&^ibsbi30bifqb+Vlrpelria_b^_ibqlplilefjyyNFAy640-y
KAfp^_ibI^dllkMrjmyKyRpbqebpbbap^qqeb`lkqolipqlqebI^dllkmrjm%31)30&yyRy/1022yyNFAy64/-yyNLyI^dllk@lkqolipAfp^_iba7.,.y

E@bk^oflkObcrdbyRy3615yyNFAy6624y
QP^sfkdqebPmlobilhpyKyI^ro^kk^Qe^o$tbii%5-+0)31+0&yyNFAy.--63y
Q>A^jm)A^ohMi^`byKyFhbvbk%5-+1)31+/&yyNFAy6455y
QP^cbdr^oafkdqebT^q`ebopyKyTfka`^iibo?i^`hellc%5-+1)31+4&yyNFAy6561y
>Te^q$pTolkd^q@bk^oflkQef`hbq<yKyIbqevkJllkcfob%45+3)30+.&yyNFAy6624y
>T^q`eboIbbp^$leyKyIbqevkJllkcfob%45+3)30+.&yyNFAy6364y
>?ibppfkdplcqeb>k`fbkqpyKyTfka`^iibo?i^`hellc%5-+1)31+4&yyNFAy6452y
@?ibppfkdplcqeb>k`fbkqpyKyDbqqeb?rcccoljqebqtl_fd>k`fbkqQobbpfkqltk%5-)32&yyNFAy6452y
Q?ibppfkdplcqeb>k`fbkqpyKyTfka`^iibo?i^`hellc%5-+1)31+4&yyNFAy6452y

QQef`hEvao^P`^ibpyKyWro^f%52+/)21+4&yyNFAy6441y
QJbk^`fkdJ^opec^kdpyKyOb^sfg%52+-)21+.&yyNFAy644-y
QQebob$pKlBumi^k^qflkcloC^peflkyKyJ^d^pe^%51+2)22+1&yyNFAy6436y
QKlJlobJrpeolljpyKyJ^d^pe^%51+2)22+1&yyNFAy6440y
>>Gl_RkalkbyKyJ^d^pe^%51+2)22+1&yyNFAy6566y
>Klqefk$P^vpIlsfk$Ifhb^?fdPqfkdboyKyOb^sfg%52+-)21+.&yyNFAy6565y
>ObmloqqlPe^altErkqboAbkg^fyKyWro^f%52+/)21+4&yyNFAy6442y
>Pb^o`efkdcloP`lrqGvl_^yKyWro^f%52+/)21+4&yyNFAy644.y
>KbtpcoljW^kd^oj^opeyKyWro^f%52+/)21+4&yyNFAy6463y
@>Gl_RkalkbyKyHfiiPmlobtfkd%45)12&yyNFAy6566y
QPb^o`efkdcloP`lrqGvl_^yKyP`lrqGvl_^%5-+4)03+1&yyNFAy644.y
>Gvl_^$pObmloqyKyDbqXP`lrqGvl_^$pObmloqZcoljqebTfqebobaDf^kqpqe^q`^k_bclrkakb^oqeb`lompblcGvl_^%5.)04&yyNFAy644/y
>Tfqeboba?^pfafrjyKyPq^oqpcoljXTfqeboba?^pfafrjZtef`efpaolmmba_vTfqebobaDf^kqp^olrka%5/)03&yyNFAy65/5yyRy/1150y
KAfp^_ibPbombkqI^hbMrjmyKyRpbqebpbbap^qqeb`lkqolipqlqebPbombkqI^hbmrjm%3.)1-&yyRy/1022yyNFAy64/-yyNLyPbombkqI^hb@lkqolipAfp^_iba7.,.y
@Ib^abolcqeb?illap`^ibyKyPi^vO^gfpCv^peb^qPbombkqI^hb%31)1.&+Fqfpmlppf_ibqe^qvlrkbbapljbebimyyNFAy65.4y

OW^_o^$gfkyKyOrkqlW^_o^$gfk%0.)2.&yyNFAy651.y
QObmloqqlPe^altErkqboAbkg^fyKyPe^altErkqboAbkg^f%0-+4)2-+6&yyNFAy6442y
>PqfkdfkdqebPqfkdbopyKyD^j_^ofkh^%0.+4)16+0&yyNFAy651.y
>>kdifkdql?b^qqeb@ljmbqfqflkyKyWrog^v^%0/+0)16+3&yyNFAy6512y
>T>KQBA7?lppDold$^hyKyT^kqbaMlpqbo%0/+-)16+2&yyNFAy65/-y
>T^kqba7@efbcq^fkJrjj^hfyKyT^kqbaMlpqbo%0/+-)16+2&yyNFAy.-..4y
>PmfofqplcqebCbo^icbkyKyPbboG^kfaf%0/+1)2.+6&yyNFAy6513y
>?ropq`^mJrpeolljp)JlkyKyTfq`eAl`qloQlo$d^pe%0/+6)15+6&yyNFAy65.1y

K@liib`qXDilt`^mpZ^pvlrnrbpq++yKyIllq^kvXDilt`^mpZvlrcfka)vlr$iikbbaqebjclonrbpqp^kaobmrq^qflkobt^oayyNFAy65-5y
@PmfofqplcqebCbo^icbkyKyHfiiCbo^icbkjvpqf`p)erkqbop^kaaorfapclo.-XCbo^icbkMolqb`qflkQlqbjZ^olrka%13)3/&yyNFAy6513y
@Klqefk$P^vpIlsfk$Ifhb^?fdPqfkdboyKyHfii?i^`hpqfkdgrpqkloqelcCbo^icbkSfii^db^kaillqX?i^`hpqfkd$pPqfkdboZ%16)26&yyNFAy6565y

QT^q`eboIbbp^$leyKyT^q`eboIbbp^$le%/0)33&yyNFAy6364y
>L_pbosfkdqebPmlobifkdpyKyT^q`eboIbbp^$le%/0)33&yyNFAy64-.y

>QebPmlobifkdp$MifdeqyKyC^eppk%.6)31&yyNFAy6406y
>K^qro^iBkbjfbpyKyC^eppk%.6)31&yyNFAy6410y
@L_pbosfkdqebPmlobifkdpyKyFksbpqfd^qbqebPm^tkfkdDibkfkW^kd^oj^ope%.0)3/&yyNFAy64-.y
@QebPmlobifkdp$MifdeqyKyIllq.-XJ^qrobPmlobP^`pZtef`e`^k_bclrka^iilsboqebPmt^kfkdDibk%.3)3-&yyNFAy6406y
@K^qro^iBkbjfbpyKyHfiiqeb?ldIloap^qqebPm^tkfkdDibk%.2)3-&loPq^osfkdCrkd^iDf^kq^olrka%.6)3/&clo3X?ldIloaQbkaofipZyyNFAy6410y
QQebPmlobifkdp$MifdeqyKyC^eppk%.6)31&yyNFAy6406y
QK^qro^iBkbjfbpyKyC^eppk%.6)31&yyNFAy6410y
>Pmlobdd^oyKyC^eppk%.6)31&yyNFAy66.6y
QPmlobdd^oyKyJppef$ck)fkPmlobdd^o)grpqkloqe*b^pqlcqebPm^tkfkdDibk%.6+3)2/&yyNFAy66.6y
>Dilt`^mJrpeolljpyKyJppef$ck%.6+3)2/&yyNFAy65-5y
@Dilt`^mJrpeolljpyKyD^qebo.-XDilt`^mpZtef`e`^k_bclrka^iilsboW^kd^oj^ope)alqov%0-)02&fcvlre^sbmol_ibjpcfkafkdqebjyyNFAy65-5y
QDilt`^mJrpeolljpyKyJppef$ck%.6+3)2/&yyNFAy65-5y
>CboqfibPmlobpyKyDpe^cc%.6+/)16+2&yyNFAy65-3y
QCboqfibPmlobpyKyDpe^cc%.6+/)16+2&+D^qebo3XCboqfibPmlobpZfcvlrafak$qe^sbqebj^iob^av+Qebvaolmlccpmlob_^qp^kaj^opet^ihbopyyNFAy65-3y
KCofbkaiv*Pmlobdd^oyKy@ljmibqbbsbovobmb^q^_ibvlr`^krkqfivlr$obcofbkaiv+Vlr`^kqrokfkXDilt`^mpZ)X?ldIloaQbkaofipZ^kaXJ^qrobPmlobp^`pZ+>iiqebpbobmb^qpbkalk`bvlr$obcofbkaiv)plrpbqebjtefibvlr`^kyyNFAy64/3y
>KltQe^qTb$obCofbkap+++yKyDwerk$qq%.6+2)2-+.&yyNFAy64/3y

QL_pbosfkdqebPmlobifkdpyKyT^q`eboIbbp^$le%/0)33&yyNFAy64-.y
>>NrbpqflklcDirqqlkvyKyT^q`eboIbbp^$le%/0)33&yyNFAy64-/y
@>NrbpqflklcDirqqlkvyKyIllhclo.-XAfp`^oabaKrqofjbkqZqlqebb^pq^qNr^ddOfadb%/5)30&yyNFAy64-/y
Q>NrbpqflklcDirqqlkvyKyT^q`eboIbbp^$le%/0)33&yyNFAy64-/y
>C^jfif^oCrkdfyKyT^q`eboIbbp^$le%/0)33&yyNFAy64-5y

@PqfkdfkdqebPqfkdbopyKyHfii5J^opeifdeq?ibbabop>olrkaPmlobdd^o%/2)2-&yyNFAy651.y
@?ropq`^mJrpeolljp)JlkyKyD^qebo3X?ropq`^mJrpeolljZ^qW^_o^$gfk%/4)2/&yyNFAy65.1y

QPqfkdfkdqebPqfkdbopyKyD^j_^ofkh^%0.+4)16+0&yyNFAy651.y
QPmfofqplcqebCbo^icbkyKyPbboG^kfaf%0/+1)2.+6&yyNFAy6513y
Q?ropq`^mJrpeolljp)JlkyKyTfq`eAl`qloQlo$d^pe%0/+6)15+6&yyNFAy65.1y
>QebPe^ombpq?i^abpyKyD^j_^ofkh^%0.+4)16+0&yyNFAy651/y
>E^sbVlrBsboPbbkLkblcQebpb<yKyTfq`eAl`qloQlo$d^pe%0/+6)15+6&yyNFAy65.3y
>>Pmfofq>iiv<yKyPbboG^kfaf%0/+1)2.+6&yyNFAy6514y
@>Pmfofq>iiv<yKyMi^kqqebXCbo^icbkQlqbjZlkqebpq^fop^qqeb?le^$jrOrfkp%11)33&^kahfiiqebPbombkqqe^q`ljbpyyNFAy6514yyRy/1165y
Q>Pmfofq>iiv<yKyPbboG^kfaf%0/+1)2.+6&yyNFAy6514y

@QebPe^ombpq?i^abpyKyJ^opec^kdPif`bop^obplrqelcW^_o^$Gfk%0/)25&+Hfiiqebjclo.-XJ^opec^kdPif`bo?i^abZyyNFAy651/y
>Qeb@lrkqlcqebJ^opebpyRy/2126yyKyHfii@lrkqRkdri^fcvlrafak$q)_^`hplrqelcW^_o^$Gfk%00)26&yyNFAy66..y

KAfp^_ibJ^opeifdeqI^hbMrjmyKyRpbqebpbbap^qqeb`lkqolipqlqebJ^opeifdeqI^hbmrjm%/2)1/&yyRy/1022yyNFAy64/-yyNLyJ^opeifdeqI^hb@lkqolipAfp^_iba7.,.y
@KltQe^qTb$obCofbkap+++yKyHfii./?illap`^ibPi^sbaofsbop^ka3?illap`^ibBk`e^kqobppbp^qqeb?illap`^ibBk`i^sbqlqebkloqeb^pq%/2)03&yyNFAy64/3y
@>T^ojTbi`ljbyKyD^qebo0-XK^d^@i^tpZtef`elc`lropb)aolmlcqebK^d^fkW^kd^oj^ope+Bu^jmibil`^qflkp%3/)35&^ka%4/)4/&yyNFAy64/5y
@T>KQBA7?lppDold$^hyKyHfii?lppDold$^h^kaq^hbX?lppDold$^h$pEb^aZ%01)01&yyNFAy65/-y
@C^jfif^oCrkdfyKy@liib`q.2XJrpeolljP^jmibpZcoljqebLdobp^qqebEbtk?ld%00)05&yyNFAy64-5y
>Ao^fkP`ebj^qf`pyRy/100-yyKyQebfqbjXAo^fkP`ebj^qf`pZpq^oqpqefpnrbpq*aolmmba_vPqb^jMrjmLsbopbbop^ka?illap`^ibLsbopbbop^olrka%3/)1-&yyNFAy640.y
@Ao^fkP`ebj^qf`pyKyVlrkbbaqldlqlqeb`bkqoblcPbombkqI^hb%2-)1-&yyNFAy640.y
@>kdifkdql?b^qqeb@ljmbqfqflkyKyHfii.-Cbk`i^tQeo^pebop^olrkaqebmfmbpfkqeb`bkqbolcPbombkqI^hb%2-)1-&yyNFAy6512y

E@bk^oflkObcrdbyRy3615yyNFAy611/y
Q?^i^k`bJrpq?bMobpbosbayKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64/-y
QAo^fkP`ebj^qf`pyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy640.y
>T^okfkdqeb@bk^oflk@fo`ibyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64/1y
Q>T^ojTbi`ljbyKyT^oabkE^jllq%46+-)32+0&yyNFAy64/5y
QIb^abolcqeb?illap`^ibyKyT^oabkE^jllq%46+-)32+0&yyNFAy65.4y
QIb^abolcqebA^oh`obpqyKyT^oabkE^jllq%46+-)32+0&yyNFAy640-y

QT^okfkdqeb@bk^oflk@fo`ibyWyEbiicfobMbkfkpri^yyKy>jvqefbiJfpqt^ihbo%.3+-)2/+/&yyNFAy64/1y
>ObqrokqlqebJ^opeyWyEbiicfobMbkfkpri^yyKy>jvqefbiJfpqt^ihbo%.3+-)2/+/&yyNFAy640/y
QBkslvqlqebJ^d$e^oyWyEbiicfobMbkfkpri^yyKyDloh^k?illacfpq%0/+.)/4+5&yyNFAy611.y
>>Ab_fifq^qfkdPf`hkbppyWyEbiicfobMbkfkpri^yyKyB^oqe`^iiboOvd^%0/+.)/5+0&yyNFAy611/y
@>Ab_fifq^qfkdPf`hkbppyWyEbiicfobMbkfkpri^yyKyDbqqebXAov`^mJrpeolljZfkqeb`^sb^qqebCfpprob%01)31&yyNFAy611/y
Q>Ab_fifq^qfkdPf`hkbppyWyEbiicfobMbkfkpri^yyKyB^oqe`^iiboOvd^%0/+.)/5+0&yyNFAy611/y
>>ajfkfpqbofkdqebP^isbyWyEbiicfobMbkfkpri^yyKyB^oqe`^iiboOvd^%0/+.)/5+0&yyNFAy6114y
@>ajfkfpqbofkdqebP^isbyWyEbiicfobMbkfkpri^yyKyRpbqebXEb^ifkdP^isbZlk.-Ab_fifq^qbaDorkqpfkJ^d$e^o%01+/)0/+2&yyRy/0061yyNFAy6114y
Q>ajfkfpqbofkdqebP^isbyWyEbiicfobMbkfkpri^yyKyB^oqe`^iiboOvd^%0/+.)/5+0&yyNFAy6114y
@>obiflk$pJfpqobppyWyEbiicfobMbkfkpri^yyKyDfsbqebX@bk^oflkPmfofqpZqlSfbo^Prktefpmbo%/4)3/&qlirobebo^t^vcoljqebpbqqibjbkq^kaqebkrpbX@^ofka^$pP`oliilcObqof_rqflkZlkeboyyRy/0360yyNFAy614/y
Q>obiflk$pJfpqobppyWyEbiicfobMbkfkpri^yyKyJ^dfpqofu@^ofka^%/3+1)3-+1&yyNFAy614/y
CPt^jmo^qMlpqyKyFkk^if^%/4+5)3-+.&yyWyEbiicfobMbkfkpri^yyNFAy66-0y

Q>Gl_RkalkbyKyJ^d^pe^%51+1)21+02&yyNFAy6566y
QTfqeboba?^pfafrjyKyOb^sfg%52+-)21+.&yyNFAy65/5y
QKlqefk$P^vpIlsfk$Ifhb^?fdPqfkdboyKyOb^sfg%52+-)21+.&yyNFAy6565y
QGvl_^$pObmloqyKyWro^f%52+/)21+4&yyNFAy644/y

QObqrokqlqebJ^opeyLyyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy640/y

CW^_o^$gfkyKyAr$d^%51+5)22&yyNFAy66-0y
eW^_o^$gfkyKyJbo^gfq%0-+4)2-+6&yyNFAy66-0y
Q>kdifkdql?b^qqeb@ljmbqfqflkyKyWrog^v^%0/+0)16+3&yyNFAy6512y
QQebPe^ombpq?i^abpyKyD^j_^ofkh^%0.+4)16+0&yyNFAy651/y
>Qeb?fddbpqlcQebj>iiyKyWrog^v^%0/+0)16+3&yyNFAy66-0y
>MroprfkdQboolo`i^tyKyWrog^v^%0/+0)16+3&yyNFAy66-1y
QT>KQBA7?lppDold$^hyKyPe^altErkqboAbkg^f%0-+4)2-+6&yyNFAy65/-y
>Fjmbkafkd>qq^`hyKyPe^altErkqboAbkg^f%0-+4)2-+6&yyNFAy65//y

O@bk^oflkT^q`emlpqyKyOrkql@bk^oflkT^q`emlpq%/0)33&yyNFAy64-6y
QC^jfif^oCrkdfyKyT^q`eboIbbp^$le%/0)33&yyNFAy64-5y
QQeb@lrkqlcqebJ^opebpyKyT^q`eboIbbp^$le%/0)33&yyNFAy66..y
>Pqb^ifkd?^`hqebJrpeolljpyKyT^q`eboIbbp^$le%/0)33&yyNFAy64-6y
@Qeb?fddbpqlcQebj>iiyKyHfiiJo^dbpe%1/)1.&yyNFAy66-0y
@MroprfkdQboolo`i^tyKyHfiiQboolo`i^tlkqebplrqebok*jlpqfpi^kafkqebJ^opeifdeqI^hb%//)12&yyNFAy66-1y
@Fjmbkafkd>qq^`hyKyDbqqebX>kdl$olpe>qq^`hMi^kpZcolj>kdl$olpeDolrkap^qqebqlmlcqebqltbo%.6+5)/4+.&yyNFAy65//y
@T^kqba7@efbcq^fkJrjj^hfyKyHfii@efbcq^fkJrjj^hf^qqebA^ddbocbkSfii^db%/1)/3&^kaq^hbX@efbcq^fkJrjj^hf$pQlqbjZyyNFAy.-..4y
@E^sbVlrBsboPbbkLkblcQebpb<yKyRpbqebXJroil`@^dbZlk^ci^qol`hfkqebA^ddbocbkSfii^db%/3+5)//+3&yyNFAy65.3yyRy/114-y

QQeb?fddbpqlcQebj>iiyKyWrog^v^%0/+0)16+3&yyNFAy66-0y
QMroprfkdQboolo`i^tyKyWrog^v^%0/+0)16+3&yyNFAy66-1y
QE^sbVlrBsboPbbkLkblcQebpb<yKyTfq`eAl`qloQlo$d^pe%0/+6)15+6&yyNFAy65.3y
QFjmbkafkd>qq^`hyKyPe^altErkqboAbkg^f%0-+4)2-+6&yyNFAy65//y
QT^kqba7@efbcq^fkJrjj^hfyKyPe^altErkqboAbkg^f%0-+4)2-+6&yyNFAy.-..4y
>RploQebjyKyPe^altErkqboAbkg^f%0-+4)2-+6&yyNFAy65/0y
>Jbpp^dbqlqebA^ddbocbkyKyPe^altErkqboAbkg^f%0-+4)2-+6&yyNFAy.-..5y

OPmlobdd^oyKyOrkqlPmlobdd^o%.6)2/&yyNFAy6464y
QKltQe^qTb$obCofbkap+++yKyDwerk$qq%.6+2)2-+.&yyNFAy64/3y
@Jbpp^dbqlqebA^ddbocbkyKyPi^v0A^ddbocbk>pp^ppfkp^ka.2A^ddbocbkJr`hatbiibop^qqebA^ddbocbkSfii^db%/1)/1&yyNFAy.-..5y
@RploQebjyKyHfiiLsboiloaDlobcfpq%.5)5&).->kdl$olpeJ^ribop^ka.->kdl$olpePlrib^qbopc^okloqetbpqlcqebwlkb)qebifqqibfpi^katfqe^_ofadbqlfq%.5)6&yyNFAy65/0y
@Pqb^ifkd?^`hqebJrpeolljpyKyDbo.-X?lulcJrpeolljpZtef`e`^k_bclrka^olrka%.4).1&+Qeb_lubp^ob_lqe^aolm^ka^`qr^i_lubpqe^qvlr`^killqyyNFAy64-6y

EW^_o^$gfkyRy3615yyNFAy6464y
QJbpp^dbqlqebA^ddbocbkyKyPe^altErkqboAbkg^f%0-+4)2-+6&yyNFAy.-..5y
QRploQebjyKyPe^altErkqboAbkg^f%0-+4)2-+6&yyNFAy65/0y
QPqb^ifkd?^`hqebJrpeolljpyKyT^q`eboIbbp^$le%/0)33&yyNFAy64-6y
>Obfkclo`bjbkqpcloD^o^a^oyKyJbppbkdboD^wdofdd%0/)2-+1&yyNFAy6464y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
