DugisGuideViewer:RegisterGuide("Terokkar Forest (63-65)", "Nagrand (65-67)", "Horde", "L", function()
return [[
AAA

OPe^qqo^qe@fqvyKyQo^sbiqlPe^qqo^qe@fqv%21)11+2&yyyWyPe^qqo^qe@fqvyyNFAy.-/.-y
>>$a^iyKyVlr$obillhfkdclo^E^dd^oaT^oSbqbo^k%25+2)1.&)ebpelria_bc^foivb^pvqlcfkakb^oqeb`bkqbolcqeb`fqvyyWyPe^qqo^qe@fqvyyNFAy.-/.-y
Q>$a^iyKy>$a^i%21)11+2&yyWyPe^qqo^qe@fqvyyNFAy.-/.-y
>@fqvlcIfdeqyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-/..y
>O^qebo?bCfpefk$yKyVlr`^k^``bmqqefp^kaqebkbuqtefibalfkdqebt^ih*^olrkaclo@fqvlcIfdeq+Pbqefp^qqeborfkbafkcfoj^ov%30+62).2+2-&yyWyPe^qqo^qe@fqvyyNFAy.--04y
Q@fqvlcIfdeqyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-/..y
K>ialoloP`ovbopyKyVlrkbbaqlmf`htef`ec^`qflkvlrtfiid^fkobmrq^qflktfqe)fkTLQIHfqalbpk$qob^iivj^qqbotef`elkbvlr`ellpb^pvlrtlk$q_brpfkdqebobmrq^qflkclo^kvqefkd)?rqFprddbpq>ialo^pqebvtfiie^sbjlobnrbpqclobuqo^bumbofbk`b^kavlr`^k^``bppK^do^kacoljqeb>ialoqrkkbilkqebTbpqpfabyyNFAy.-6.4y

Q>iibdf^k`bqlqeb>ialoyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-22.y
>Fpe^k^eyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-221y
QFpe^k^eyKyFpe^k^e%/1+/)/6+2&yyWyPe^qqo^qe@fqvyyNFAy.-221y
>ObpqlofkdqebIfdeqyKyFpe^k^e%/1+/)/6+2&yyWyPe^qqo^qe@fqvyyNFAy.--/.y

Q>iibdf^k`bqlqebP`ovbopyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-22/yyLy
>Slobk$qe^iqebPbboyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-220yyLy
QSlobk$qe^iqebPbboyKySlobk$qe^iqebPbbo%1/+4)6.+2&yyWyPe^qqo^qe@fqvyyNFAy.-220yyLy

ePe^qqo^qe@fqvyKyFkkp^oblk>ialo%/5+/)16&loP`ovbo%2/+/)5.+3&qfbopyyWyPe^qqo^qe@fqvyyNFAy.-6.4y

>QebLrq`^pq$pMifdeqyKySbh^u%15).5+2&yyWyPe^qqo^qe@fqvyyNFAy.-6.4y

@O^qebo?bCfpefk$yWyPe^qqo^qe@fqvyyKyHfiiqebBbipfkPfijvoI^hb%06+3).-+5&)kloqeb^pqlcPe^qqo^qeclo5XMofpqfkbPefjjbop`^ibBbiZyyNFAy.--04y
QTe^q$pTolkd^q@bk^oflkQef`hbq<yKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy6624y
>Pqo^kdbBkbodvyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy6635y
>@irbpfkqebQef`hbqyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy664.y
>Fq$pT^q`efkdVlryKyT^oabkQobbilp%10+2)//+2&yyNFAy662.y
@@irbpfkqebQef`hbqyKyBu^jfkbqebl_gb`qfkqebfkk%12+.)/.)+5&yyNFAy664.y
@Fq$pT^q`efkdVlryKyHfiiK^meqe^i$^ormqebqltbo%10)//&yyNFAy662.y
QFq$pT^q`efkdVlryKyT^oabkQobbilp%10+2)//+2&yyNFAy662.y
@Pqo^kdbBkbodvyKyHfiiqebSf`flrpQbobjlqepfkqebqef`hbq%11).5&clo1XSf`flrpQboljlqeP^jmibZ^kami^fkQbobjlqepplrqelcqebol^aclo1XQboljlqeP^jmibZyyNFAy6635y
QPqo^kdbBkbodvyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy6635y
Q@irbpfkqebQef`hbqyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy664.y
>?v>kvJb^kpKb`bpp^ovyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy6645y
@?v>kvJb^kpKb`bpp^ovyKyQ^ihql^kaabcb^qBjmllotef`eqo^sbipqebol^a_bqtbbk%06+-)/3+2&^ka%2-+0)/6+.&yyNFAy6645y
Q?v>kvJb^kpKb`bpp^ovyKyBjmllo)_bqtbbk%06+-)/3+2&^ka%2-+0)/6+.&yyNFAy6645y
>TfkaQo^aboI^qeo^fyKyBjmllo)_bqtbbk%06+-)/3+2&^ka%2-+0)/6+.&yyNFAy6646y

OPqlkb_ob^hboEliayKyOrkqlPqlkb_ob^hboElia%15)12&yyNFAy6654y
QKbtpcoljW^kd^oj^opeyKyJlh^p^%16+4)10+1&yyNFAy6463y
>Pqvjvfkdqeb>o^hhl^yKyOlh^d%15+6)11+4&yyNFAy6654y
>ProobkaboqlqebEloabyKyOlh^d%15+6)11+4&Qefpnrbpqtlk$q_b^s^fi^_ibfcQebBvbplcPhbqqfpfpfkvlronrbpq_llh)^_^kalk$QebBvbplcPhbqqfp$^ka^``bmqqefpnrbpqtloqe.-)1--umyyNFAy.-53/y
>Pmb^htfqeP`lrqKbcqfpyKy>asfploC^fi^%15+6)11+4&yyNFAy.--06y
>>o^hhl^T^oM^qeyKy>asfploC^fi^%15+6)11+4&yyNFAy.-535y
>>kRktbi`ljbMobpbk`byKyHrod^qlh%15+5)12+3&yyNFAy.----y
>J^df`^iAfpqro_^k`bpyKyHrod^qlh%15+5)12+3&yyNFAy.--/4y
>Libj_^PbbaLfiyKyO^hlof^%2-+.)11+6&yyNFAy6660y
>SbpqjbkqplcqebTlicPmfofqyKyJ^irh^w%2-+.)13+1&yyNFAy.--.5y
>T^kqba7?lkbi^pebopAb^ayKyT^kqbaMlpqbo%16+5)12+/&yyNFAy.--01y

CPe^qqo^qe@fqvyKyHbok^%16+/)10+2&yyNFAy.-514y
QProobkaboqlqebEloabyWyPe^qqo^qe@fqvyyKyOfi^hqebObabbjba%2.+-)/-+3&yyNFAy.-53/y
>QebBvbplcPhbqqfpyWyPe^qqo^qe@fqvyyKyOfi^hqebObabbjba%2.+-)/-+3&yyNFAy.-514y
QTfkaQo^aboI^qeo^fyWyPe^qqo^qe@fqvyyKyTfkaQo^aboI^qeo^f%4/+0)0.+-&yyNFAy6646y
>>Mboplk^iC^sloyWyPe^qqo^qe@fqvyyKyTfkaQo^aboI^qeo^f%4/+0)0.+-&yyNFAy.-../y

K@liib`qflkNrbpqp+++yKyTefibvlr$oborkkfkd^olrka)hbbm^kbvblrqcloLibj_^@lkbp%_ofdeq_irbqefkdplkqebdolrka&+>iplhfiiT^omPq^ihbop^kaQfj_boTlodp^pvlrork^`olppqebj+>kai^pqiv)p^sb^kvX>o^hhl^Cb^qebopZvlrdbq)vlr$iikbbaqebjclo^nrbpqi^qbocloIltbo@fqvobmyyNFAy6660y

HRoa^hyKyEb^aplrqelrqlcPe^qqo^qeqlSbfiPhfqe+HfiiRoa^hrmfkqebqobbp%0.+5)1/+0&cloPqvjvfkdqeb>o^hhl^yyNFAy6654yyNLyRoa^hpi^fk7.,.y
@>Mboplk^iC^sloyKyObqofbsb2lcXI^qeo^f$pPqlibkDllapZtef`e^obaolmmbalcqeb_foamblmib^qSbfiPhfqe%0-)1.&)grpqplrqelcPe^qqo^qe@fqvyyNFAy.-../y

H>peh^wyKyHfii>peh^w^qSbfiObphhcloPqvjvfkdqeb>o^hhl^*eb$pfkqebqobbelrpbkb^oqebkloqe^iq^o%16).3&yyNFAy6654yyNLy>peh^wpi^fk7.,.y
@QebBvbplcPhbqqfpyKyDbqqebXBvblcSbfiObphhZrmfkqebqobbelrpbkb^oqebkloqe^iq^o^qSbfiObphh%2-+.).6+1&^kaqebXBvblcSbfiPefbkloZcoljqebqobbelrpbfkSbfiPefbklo%24+6)/0+.&yyNFAy.-514y
@ObpqlofkdqebIfdeqyLyyKyRpbqebX?ibppbaSf^iZql`ib^kpbqeb0^iq^op7Tbpq%15+.).1+2&)Kloqe%2-+3).3+2&^kaB^pq%16+/)/-+0&yyNFAy.--/.yyRy/25.4y
@>o^hhl^T^oM^qeyKyHfii.1PefbkloQ^ilkfqbp^ka3PefbkloPlo`bobop^qqebSbfi$p%16).3&yyNFAy.-535y

EPe^qqo^qe@fqvyRy3615yyNFAy.-516y
QObpqlofkdqebIfdeqyLyyWyPe^qqo^qe@fqvyyKyFpe^k^e%/1+/)/6+2&yyNFAy.--/.y
QQebBvbplcPhbqqfpyWyPe^qqo^qe@fqvyyKyOfi^hqebObabbjba%2.+-)/-+3&yyNFAy.-514y
>PbbhLrqHfoofhyWyPe^qqo^qe@fqvyyKyOfi^hqebObabbjba%2.+-)/-+3&yyNFAy.-516y
QO^qebo?bCfpefk$yWyPe^qqo^qe@fqvyyKyPbqe%31+-).2+5&+Phfmqebcliilt*rmyyNFAy.--04y
Q>Mboplk^iC^sloyWyPe^qqo^qe@fqvyyKyTfkaQo^aboI^qeo^f%4/+0)0.+-&yyNFAy.-../y
>Fksbpqfd^qbQrrobjyWyPe^qqo^qe@fqvyyKyTfkaQo^aboI^qeo^f%4/+0)0.+-&yyNFAy666-y

CPqlkb_ob^hboEliayKyKrqo^i%31)1.+/&yyNFAy.---0yyWyPe^qqo^qe@fqvy
ePqlkb_ob^hboEliayKyFkkhbbmboDofih^%15+5)12+.&yyNFAy.---0y
@>kRktbi`ljbMobpbk`byKyHfii./T^ombaMblkpb^pq^qqeb?lkb`ebtboOrfkp%33)20&yyNFAy.----y
@J^df`^iAfpqro_^k`bpyKyHfii.-T^omPq^ihbop%31)04&yyNFAy.--/4y
@SbpqjbkqplcqebTlicPmfofqyKyHfiiQfj_boTlodpclo./XQfj_boTlodMbiqZyyNFAy.--.5y

Q>kRktbi`ljbMobpbk`byKyPe^altpq^ihboH^fab%30+1)1/+4&yyNFAy.----y
>QebCfobtfkdIf^fplkyKyPe^altpq^ihboH^fab%30+1)1/+4&yyNFAy.---0y
>Te^qE^mmbkpfkQbolhh^oPq^vpfkQbolhh^oyKyPe^altpq^ihboH^fab%30+1)1/+4&yyNFAy.---5y
@QebCfobtfkdIf^fplkyKyIl`^qb^kapi^vIfp^fibCfobtb^sbofkpfabqeblkiv_rfiafkdfkqeborfkpqe^qe^p^ollc%34+5)20+0&yyNFAy.---0y
>>kRkpbbkE^kayKyQ^hbqefpnrbpqcoljqebXCbiLo`Mi^kpZlkqebdolrkafkpfabqebp^jb_rfiafkd%34)20&yyNFAy.--.0y
@Te^qE^mmbkpfkQbolhh^oPq^vpfkQbolhh^oyKyHfii.-?lkb`ebtboAbs^pq^qlop^ka3?lkb`ebtbo?^`h_ob^hbop^qqeb?lkb`ebtboOrfkp%34)20&yyNFAy.---5y
QQebCfobtfkdIf^fplkyKyPe^altpq^ihboH^fab%30+1)1/+4&yyNFAy.---0y
QTe^qE^mmbkpfkQbolhh^oPq^vpfkQbolhh^oyKyPe^altpq^ihboH^fab%30+1)1/+4&yyNFAy.---5y

H>vfqyKyHfii>vfq^qSbfiPefbklocloPqvjvfkdqeb>o^hhl^*eb$pfk^mromiberqlkqebdolrkaibsbi%26+1-)/0+20&yyNFAy6654yyNLy>vfqpi^fk7.,.y
@Fksbpqfd^qbQrrobjyKyQebXPb^iba?luZfpfklkblcqeberqpfkQrrobj%21+-)0-+-&yyNFAy666-y
QFksbpqfd^qbQrrobjyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy666-y
>Te^q>obQebpbQefkdp<yKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy6662y

@Libj_^PbbaLfiyKyD^qebo0-XLibj_^PbbaZkb^oqebqobbpfkQboolh^oCloobpq%21)1/&yyNFAy6660y

QPmb^htfqeP`lrqKbcqfpyKyP`lrqKbcqfp%06+-)10+6&yyNFAy.--06y
>Tel>obQebv<yKyP`lrqKbcqfp%06+-)10+6&yyNFAy.--1.y
@Tel>obQebv<yKyQ^ihqlqebFkfqf^qb%06+-)06+3&)I^_lobo%05+-)1.+-&)^ka>asfplo%1-+/)06+-&fkpfabqeb_rfiafkdtefibvlre^sbvlroafpdrfpblk+?bt^obcloqebErkqboptef`e`^kpbbqeolrdeqebafpdrfpbyyNFAy.--1.y
QTel>obQebv<yKyP`lrqKbcqfp%06+-)10+6&yyNFAy.--1.y
>HfiiqebPe^alt@lrk`fiyKyP`lrqKbcqfp%06+-)10+6&yyNFAy.--10y
@HfiiqebPe^alt@lrk`fiyKyHfiiPe^altj^pqboDofbsbfkqebj^fk_rfiafkd%1-+-)05+5&yyNFAy.--10y

EPqlkb_ob^hboEliayRy3615yyNFAy.-115y
QTe^q>obQebpbQefkdp<yKyQllhf%2-+-)12+5&yyNFAy6662y
>ObmloqqlPqlkb_ob^hbo@^jmyKyQllhf%2-+-)12+5&yyNFAy.-115y
QPqvjvfkdqeb>o^hhl^yKyOlh^d%15+6)11+4&yyNFAy6654y
QHfiiqebPe^alt@lrk`fiyKy>asfploC^fi^%15+6)11+4&yyNFAy.--10y
Q>o^hhl^T^oM^qeyKy>asfploC^fi^%15+6)11+4&yyNFAy.-535y
QJ^df`^iAfpqro_^k`bpyKyHrod^qlh%15+5)12+3&yyNFAy.--/4y
Q>kRkpbbkE^kayKyOlh^d%15+6)11+4&yyNFAy.--.0y
QLibj_^PbbaLfiyKyO^hlof^%2-+.)11+6&yyNFAy6660y
>>kaKlt)qebJljbkqlcQorqeyKyO^hlof^%2-+.)11+6&yyNFAy.-/-.y
@>kaKlt)qebJljbkqlcQorqeyKyDobhfpkbuqqlT^kqbaMlpqbo%16+6)12+0&yyNFAy.-/-.y
Q>kaKlt)qebJljbkqlcQorqeyKyO^hlof^%2-+.)11+6&yyNFAy.-/-.y
QSbpqjbkqplcqebTlicPmfofqyKyJ^irh^w%2-+.)13+1&yyNFAy.--.5y
>M^qof^o`eFolkg^tyKyJ^irh^w%2-+.)13+1&yyNFAy.--/0y

QObmloqqlPqlkb_ob^hbo@^jmyKyPbodb^kq@e^tkf%30+1)1/+2&yyNFAy.-115y
>>qq^`hlkCfobtfkdMlfkqyKyPbodb^kq@e^tkf%30+1)1/+2&yyNFAy6664y
@M^qof^o`eFolkg^tyKyHfiiFolkg^t^kaq^hbXFolkg^t$pMbiqZ%34)02&yyNFAy.--/0y
>Bp`^mbcoljCfobtfkdMlfkqyKyFpi^Pq^oj^kb%40+6)02+/&yyNFAy.--2/y
@Bp`^mbcoljCfobtfkdMlfkqyKyBp`loqFpi^Pq^oj^kbcoljfkpfabqebj^fk_rfiafkd^qCfobtfkdMlfkq%40+6)02+/&yyNFAy.--2/y
@>qq^`hlkCfobtfkdMlfkqyKyHfii.-CfobtfkdAbcbkabop).-Cfobtfkd?illat^oabop^ka.-CfobtfkdT^oil`hp^qCfobtfkdMlfkq%4.)04&yyNFAy6664y

Q>qq^`hlkCfobtfkdMlfkqyKyPbodb^kq@e^tkf%30+1)1/+2&yyNFAy6664y
>QebCfk^i@labyKyPbodb^kq@e^tkf%30+1)1/+2&yyNFAy.-114y
@QebCfk^i@labyKyHfiiPe^oqeSlialrk%40+6)02+5&cloXQebCfk^i@labZ^karpbqefpkb^oqebJ^k^?lj_fkqeb`bkqbolcCfobtfkdMlfkqyyNFAy.-114yyRy/66./y

QQebCfk^i@labyKyQllhf%2-+-)12+5&yyNFAy.-114y
>IbqqfkdB^oqe_fkaboQ^sdobkHkltyKyQllhf%2-+-)12+5&yyNFAy.---3y
QBp`^mbcoljCfobtfkdMlfkqyKy>asfploC^fi^%15+6)11+4&yyNFAy.--2/y
QM^qof^o`eFolkg^tyKyJ^irh^w%2-+.)13+1&yyNFAy.--/0y
>Tbi`ljfkdqebTlicPmfofqyKyJ^irh^w%2-+.)13+1&yyNFAy.-46.y
@Tbi`ljfkdqebTlicPmfofqyKyRpbqebX@bobjlkf^iFk`bkpbZkb^oqeb`^kaibpfkJ^irh^wErq%2-)13&yyRy0.011yyNFAy.-46.y
QTbi`ljfkdqebTlicPmfofqyKyJ^irh^w%2-+.)13+1&yyNFAy.-46.y

CPe^qqo^qe@fqvyKyHbok^%16+/)10+2&yyNFAy.-545y
QIbqqfkdB^oqe_fkaboQ^sdobkHkltyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy.---3y
>?bclobA^ohkbppC^iipyKyJbhba^%04+2)2.+.&yyNFAy.-545y
@?bclobA^ohkbppC^iipyKyHfii5@^_^iPhfojfpebop)1@^_^iPmbii*Tb^sbop^ka/@^_^iFkfqf^qbpplrqe^olrkaqebPe^altPq^fo%06+3)23+/&yyNFAy.-545y
>@^_^iLoabopyKyQebfqbjX@^_^iLoabopZpq^oqpnrbpq*aolmpcolj@^_^iPhfojfpebop)Pmbii*tb^sbop^kaFkfqf^qbp%06+3)23+/&+HbbmhfiifkdqebjrkqfivlrdbqfqyyRy0.4-4yyNFAy.-55-y
Q@^_^iLoabopyKyJbhba^%04+2)2.+.&yyNFAy.-55-y
Q?bclobA^ohkbppC^iipyKyJbhba^%04+2)2.+.&yyNFAy.-545y
>QebPe^altQlj_yKyJbhba^%04+2)2.+.&yyNFAy.-55.y
QPbbhLrqHfoofhyKyHfoofhqeb>t^hbkba%04+/)2.+-&yyNFAy.-516y
>QebFkcbpqbaMolqb`qlopyKyI^hlq^b%04+6)2.+3&yyNFAy.-563y
>JfppfkdCofbkapyKyBqe^k%04+3)2.+0&yyNFAy.-52/y
>SbfiPhfqe7A^ohpqlkblcQbolhhyKyHfoofhqeb>t^hbkba%04+/)2.+-&yyNFAy.-506y

@SbfiPhfqe7A^ohpqlkblcQbolhhyKyRpbqebXOlalcMrofcf`^qflkZlkqebA^ohpqlkblcQbolhhfkSbfiPhfqee%0-+4)1/+-&yyRy0.3.-yyNFAy.-506y
@JfppfkdCofbkapyKyHfiiqeb_foamblmib^qSbfiPhfqe%0-)1.&cloXSbfiPhfqeMofplkHbvZ^karpbfqqlcobb./@efiaobkyyNFAy.-52/y
@QebFkcbpqbaMolqb`qlopyKyHfiiqebFkcbpqba^kaOlqqfkdqob^kqp^olrkaqebbadbplcqeb?lkbT^pqbp)qebkhfii/2TllaJfqbpqe^qpm^tkcoljqebj%1-)15&yyNFAy.-563y
@QebPe^altQlj_yKyBkqboqebPe^altQlj_%0.)2/&^kaq^hbqebXAo^mblc>orrkbkZ%0/)2.&)XD^sbilcH$^ibkZ%/6)2.&)^kaXP`oliilc>q^iloZ%0.)13&yyNFAy.-55.y

>Bp`^mfkdqebQlj_yKy>hrkl%0-)2.&yyNFAy.-554y
@Bp`^mfkdqebQlj_yKyBp`loq>hrkl%0-)2.&yyNFAy.-554y

QBp`^mfkdqebQlj_yKyJbhba^%04+2)2.+.&yyNFAy.-554y
QQebFkcbpqbaMolqb`qlopyKyI^hlq^b%04+6)2.+3&yyNFAy.-563y
QSbfiPhfqe7A^ohpqlkblcQbolhhyKyHfoofhqeb>t^hbkba%04+/)2.+-&yyNFAy.-506y
>SbfiOe^wb7RkifsfkdBsfiyKyHfoofhqeb>t^hbkba%04+/)2.+-&yyNFAy.-515y
QQebPe^altQlj_yKyJbhba^%04+2)2.+.&yyNFAy.-55.y
QJfppfkdCofbkapyKyBqe^k%04+3)2.+0&yyNFAy.-52/y
>QebQlj_lcIfdeqpyKyEfdeMofbpqLodirj%04+1)2-+5&yyNFAy.-51-y

@QebQlj_lcIfdeqpyKyDlqlqebQlj_lcIfdeqp^kahfii.-Bqebob^iKbqeboj^k`bop^ka.-Bqebob^iMirkabobop%14)21&yyNFAy.-51-y
@T^kqba7?lkbi^pebopAb^ayKyHfii/-?lkbi^pebop%1/)2-&yyNFAy.--01y

QQebQlj_lcIfdeqpyKyEfdeMofbpqLodirj%04+1)2-+5&yyNFAy.-51-y
>Ob`lsboqeb?lkbpyKyPlli^sbbk%03+4)16+3&yyNFAy.--0-y
KDbq_lkba+++yKy@liib`q^kv_lkbpvlr`ljb^`olppcloOb`lsboqeb?lkbpyyNFAy.--0-y

@SbfiOe^wb7RkifsfkdBsfiyKyHfii1Ab^qeq^ilkPmfofqp)1P`obb`efkdPmfofqp^ka/PmfofqO^sbkp^qSbfiOe^wb%/3)20&yyNFAy.-515y

QSbfiOe^wb7RkifsfkdBsfiyKyHfoofhqeb>t^hbkba%04+/)2.+-&yyNFAy.-515y
>SbfiIfqef`7MobbjmqfsbPqofhbyKyHfoofhqeb>t^hbkba%04+/)2.+-&yyNFAy.-53.y
@Ob`lsboqeb?lkbpyKy@liib`q.-XObpqibpp?lkbpZpmob^a^iilsboqebdolrkafkqeb?lkbT^pqbp+Vlr`^kqov^olrka%02)25&yyNFAy.--0-y
QOb`lsboqeb?lkbpyKyO^jaloqebJ^a%02+.)33+/&yyNFAy.--0-y
>EbimfkdqebIlpqCfkaQebfoT^vyKyO^jaloqebJ^a%02+.)33+/&yyNFAy.--0.y
KDbqilpq+++yKyHfii^kvphbibqlkpvlr`ljb^`olppcloEbimfkdqebIlpqCfkaQebfoT^vyyNFAy.--0.y

@SbfiIfqef`7MobbjmqfsbPqofhbyKy?ob^hqeb`ropbabddpfkSbfiIfqef`%/0)4.&+Obabbj0E^q`eifkdp^kapi^v0J^ibslibkqE^q`eifkdpyyNFAy.-53.y
>QebAob^aObif`yKyL^hrk%0.+.)43+2&yyNFAy.-544y
>>kFjmolmbo?rof^iyKy@ljj^kaboO^$s^g%0-+2)42+5&yyNFAy.-6.0y
>Q^hbkfkqebKfdeqyKyP`lrqK^sofk%0.+2)42+3&yyNFAy.-540y
>AfddfkdQeolrde?lkbpyKy@efbc>o`e^blildfpqIbqlii%0-+6)43+/&yyNFAy.-6//y
@AfddfkdQeolrde?lkbpyKyBp`loqIbqlii^kaefp`obt^kamolqb`qqebjtefibqebvj^hbqebfoafdyyNFAy.-6//y
QAfddfkdQeolrde?lkbpyKyAt^ocltfqw%0-+6)42+4&yyNFAy.-6//y
>CrjmfkdyKyAt^ocltfqw%0-+6)42+4&yyNFAy.-6/6y

@>kFjmolmbo?rof^iyKyRpbqebXPe^$q^ofQlo`eZql_rok5Pi^fk>r`ebk^fT^ooflop^ka5Pi^fkPe^$q^oSfkaf`^qlopyyRy0.436yyNFAy.-6.0y
@QebAob^aObif`yKyRpbqebXAbobif`q@^o^s^k@ebpqHbvZqlq^hbqebXAob^aObif`Z^qqebAbobif`q@^o^s^kb^pqlcqeb`^jm%10+6)43+2&yyNFAy.-544y
@CrjmfkdyKyRpbqebXCrjmboZ^q%15)40&^kahfiiqebTlojpqe^q`ljbrmclo5XJ^qrob?lkbPfcqbo@^o`^ppZyyRy0.5.-yyNFAy.-6/6y

>CloqebC^iibkyKySfkaf`^qloE^vibk%16+4)43+.&yyNFAy.-6/-y
@Q^hbkfkqebKfdeqyKyDlqlKbqebotb_Ofadb%2/)45&^kacobb3Tb__baPe^$q^oT^ooflopyyNFAy.-540y
@CloqebC^iibkyKyPi^v/-Aob^ac^kdTfaltp^qqebKbqebotb_Ofadb%2/)45&yyNFAy.-6/-y
QCloqebC^iibkyKySfkaf`^qloE^vibk%16+4)43+.&yyNFAy.-6/-y

QQ^hbkfkqebKfdeqyKyP`lrqK^sofk%0.+2)42+3&yyNFAy.-540y
QCrjmfkdyKyAt^ocltfqw%0-+6)42+4&yyNFAy.-6/6y
QQebAob^aObif`yKyL^hrk%0.+.)43+2&yyNFAy.-544y
Q>kFjmolmbo?rof^iyKy@ljj^kaboO^$s^g%0-+2)42+5&yyNFAy.-6.0y
>>EbolFpKbbabayKy@ljj^kaboO^$s^g%0-+2)42+5&yyNFAy.-6.1y
@>EbolFpKbbabayKyPi^v./>r`ebk^fFkfqf^qbp^ka2>r`ebk^fAlljp^vbop%03)42&yyNFAy.-6.1y
Q>EbolFpKbbabayKy@ljj^kaboO^$s^g%0-+2)42+5&yyNFAy.-6.1y
>QebC^iibkBu^o`eyKy@ljj^kaboO^$s^g%0-+2)42+5&yyNFAy.-6.2y
@QebC^iibkBu^o`eyKyAbpqolvqeb`lkqbkqplcqeb>r`ebk^f@lccfkqlqebtbpqpfablc>r`efkalrk%02)33&yyNFAy.-6.2y
>FPbbAb^aAo^bkbfyKyE^$ibf%02+.)32+/&yyNFAy.-//4y
QFPbbAb^aAo^bkbfyKyO^jaloqebJ^a%02+.)33+/&yyNFAy.-//4y
>BwbhfbiyKyO^jaloqebJ^a%02+.)33+/&yyNFAy.-//5y
QQebC^iibkBu^o`eyKy@ljj^kaboO^$s^g%0-+2)42+5&yyNFAy.-6.2y

QSbfiIfqef`7MobbjmqfsbPqofhbyKyHfoofhqeb>t^hbkba%04+/)2.+-&yyNFAy.-53.y
>SbfiPe^i^p7Pfdk^iCfobpyKyHfoofhqeb>t^hbkba%04+/)2.+-&yyNFAy.-541y
>PhvtfkdyKyPhvtfkd%21)4/&yyNFAy.-565y
@PhvtfkdyKyBp`loqPhvtfkd%21)4/&yyNFAy.-565y
@SbfiPe^i^p7Pfdk^iCfobpyKyBuqfkdrfpeqebP^mmefobCfob%24)32&)Bjbo^iaCfob%24)4/&)?illapqlkbCfob%23)40&^kaSflibqCfob%23)40&^qSbfiPe^i^p)lkqebplrqeb^pqpfablcqeb_lkbt^pqbp%22)33&yyNFAy.-541y
@EbimfkdqebIlpqCfkaQebfoT^vyKyAbpqolv.-IlpqPmfofqp^ka.-?olhbkPhbibqlkp^qqebb^pqpfablcQeb?lkbt^pqbp%1-)45&yyNFAy.--0.y

QEbimfkdqebIlpqCfkaQebfoT^vyKyPlli^sbbk%03+4)16+3&yyNFAy.--0.y
QSbfiPe^i^p7Pfdk^iCfobpyKyHfoofhqeb>t^hbkba%04+/)2.+-&yyNFAy.-541y
>ObqrokqlPe^qqo^qeyKyHfoofhqeb>t^hbkba%04+/)2.+-&yyNFAy.-556y

QBwbhfbiyWyPe^qqo^qe@fqvyyKyBwbhfbi)t^ihfkdfk`fo`ibplkqebQboo^`blcIfdeq+Phfmqebcliilt*rmyyNFAy.-//5y
QObqrokqlPe^qqo^qeyWyPe^qqo^qe@fqvyyKyOfi^hqebObabbjba%2.+-)/-+3&yyNFAy.-556y
QPhvtfkdyWyPe^qqo^qe@fqvyyKyOfi^hqebObabbjba%2.+-)/-+3&yyNFAy.-565y
>QebPhbqqfpLccbkpfsbyWyPe^qqo^qe@fqvyyKyAbcbkaboDo^pek^%2.+-)/.+3&yyNFAy.-546y
@QebPhbqqfpLccbkpfsbyWyPe^qqo^qe@fqvyyKyElialcqeb^qq^`hfkd?foap%2.+-)/.+3&yyNFAy.-546y
QQebPhbqqfpLccbkpfsbyWyPe^qqo^qe@fqvyyKyOfi^hqebObabbjba%2.+-)/-+3&yyNFAy.-546y
QT^kqba7?lkbi^pebopAb^ayWyPe^qqo^qe@fqvyyKyJ^tdDofjpelq%16+0)12+6&yyNFAy.--01y

OK^do^kayWyPe^qqo^qe@fqvyyKyBufqtbpqqlK^do^kafcvlr$ob>ialovlr`^krpbqebbufq^q%.-)25&yyWyPe^qqo^qe@fqvy
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
