
DugisGuideViewer:RegisterGuide("Nagrand (65-67)", "Blade's Edge Mountains (67-69)", "Horde", "L", function()
return [[
AAA

OD^o^a^oyKyOrkqlD^o^a^o24+/)02+0&yyNFAy6611y
cD^o^a^oyKyDrope^%24+/)02+0&yyNFAy6611y
eD^o^a^oyKyJ^qolkQfhhfq%23+4)01+3&yyNFAy6611y
QObfkclo`bjbkqpcloD^o^a^oyKy@^mq^fkHolde^k%22+1)04+2&yyNFAy6464y
>JfppfkdJ^d$e^ofMol`bppflkyKyJ^qolkAo^hf^%23+3)01+0&yyNFAy6611y
>QebQeolkblcqebBibjbkqpyKyBibjbkq^ifpqV^i$e^e%22)04&yyNFAy654-y
>QebFjmlqbkqIb^aboyKyGlofkAb^abvb%22+3)04+3&yyNFAy6555y
>SfibFali^qovyKyC^opbboHrohrpe%21+5)06+1&yyNFAy6530y
>QebJfppfkdT^oM^oqvyKyC^opbbo@loerh%21+5)06+5&yyNFAy6531y
>Jroh_illaIb^abop+++yKyC^opbboJ^od^abpe%21+3)06+6&yyNFAy6534y
>T^kqba7Dfpbia^qeb@olkbyKyD^o^a^o?riibqfk?l^oa%22+4)04+6&yyNFAy6602y
>T^kqba7Wlo_lqeb>asfployKyD^o^a^o?riibqfk?l^oa%22+4)04+6&yyNFAy6606y
>Eb@^iibaEfjpbic>iqorfp+++yKyJ^qolk@bibpqfkb%22+/)03+/&yyNFAy6650y
>QebKbpfkdt^ovP^c^ofyKyLeilokC^opqofabo%22+1)04+1&yyNFAy.-..1y
>Qeb@lkploqfrjKbbapVlryKy@lkploqfrjOb`orfqbo%2.+5)01+5&yyNFAy66.0y

OQbolhh^oClobpqyKyDlsf^qebplrqeb^pqm^qe%50)55&yyNFAy6556y
QQebFjmlqbkqIb^aboyKyHfio^qe%.6+5)3-+5&yyWyQbolhh^oClobpqyyNFAy6555y
>Alk$qHfiiqebC^qLkbyKyHfio^qe%.6+5)3-+5&yyWyQbolhh^oClobpqyyNFAy6556y
@Alk$qHfiiqebC^qLkbyKyHfii.-?lriabocfpqFks^abop^olrka%.6)30&^kaqebk_b^qRkhloqebOrqeibpp^q%/-)3/&yyWyQbolhh^oClobpqyyNFAy6556y
QAlk$qHfiiqebC^qLkbyKyRkhloqebOrqeibpp%/-)3/&yyWyQbolhh^oClobpqyyNFAy6556y
>Pr``bppyKyRkhloqebOrqeibpp%/-)3/&yyWyQbolhh^oClobpqyyNFAy656-y
QPr``bppyKyHfio^qe%.6+5)3-+5&yyWyQbolhh^oClobpqyyNFAy656-y
>?b`^rpbHfio^qefp^@lt^oayKyHfio^qe%.6+5)3-+5&yyWyQbolhh^oClobpqyyNFAy656.y

ED^o^a^oyRy3615yyNFAy66-3y
Q?b`^rpbHfio^qefp^@lt^oayKyGlofkAb^abvb%22+3)04+3&yyNFAy656.y
>Jbpp^dbfk^?^qqibyKyGlofkAb^abvb%22+3)04+3&yyNFAy66-3y
>Pq^ka^oap^kaMo^`qf`bpyKyBih^v$d^kqebJvpqf`%22+4)04+3&yyNFAy66.-y

KObmrq^qflkqlhbkp+++yKyHbbm^kvLper$drk@ovpq^iMltabovlrcfkacloobt^oapi^qbo+XL_pfaf^kT^o_b^apZcoljqebldobpfkqebwlkb`^k_bqrokbafkcloHrobk^flo@lkploqfrjobmyyNFAy66-3y
@Jbpp^dbfk^?^qqibyKyHfii5?lriabocfpq@orpebop^ka5?lriabocfpqJvpqf`p^olrka%4/)36&yyNFAy66-3y
@Pq^ka^oap^kaMo^`qf`bpyKyMvob.%4/)36&)Mvob/%41)4-&^kaMvob0%42)35&+Qebpbmvobpillhgrpqifhb_fd`^jmcfobp)mi^`bqebXJ^d$e^o?^qqibPq^ka^oaZkbuqqlqebjqldbq`obafqyyNFAy66.-yyRy/2125y

QJbpp^dbfk^?^qqibyKyGlofkAb^abvb%22+3)04+3&yyNFAy66-3y
QPq^ka^oap^kaMo^`qf`bpyKyBih^v$d^kqebJvpqf`%22+4)04+3&yyNFAy66.-y
>>k>ra^`flrp>as^k`byKyGlofkAb^abvb%22+3)04+3&yyNFAy66-4y
>?ibbafkdEliiltPrmmiv@o^qbpyKyBih^v$d^kqebJvpqf`%22+4)04+3&yyNFAy66.3y

@>k>ra^`flrp>as^k`byKyHfii.-?lriabocfpqT^ooflop^ka.-?lriabocfpqJ^dbp^q%2-)23&lo%1-)0/&yyNFAy66-4y
@?ibbafkdEliiltPrmmiv@o^qbpyKyOb`lsbo.-X?ibbafkdEliiltPrmmiv@o^qbpZ+Qebv$obmi^`ba^iilsboqeb`^sbpfkKloqetfka,Plrqetfka@ibcqp%1-)0-&yyNFAy66.3y
OJ^d$e^ofMol`bppflkyKyOrkqlJ^d$e^ofMol`bppflk%0/)03&yyNFAy6532y
QQebJfppfkdT^oM^oqvyKyP^roc^kdqebVlrkdbo%0/+2)03+.&yyNFAy6531y
>Lk`bTbobT^ooflopyKyP^roc^kdqebVlrkdbo%0/+2)03+.&yyNFAy6532y
QJfppfkdJ^d$e^ofMol`bppflkyKyBiaboVloibv%0/+0)03+/&yyNFAy6611y
>T^olkqebT^oj^riyKyBiaboVloibv%0/+0)03+/&yyNFAy6612y
>CfkafkdqebProsfslopyKyBiaboRkdofw%0/+1)03+/&yyNFAy6615y

QEb@^iibaEfjpbic>iqorfp+++yKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy6650y
>ProsbvqebI^kayKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy666.y
@ProsbvqebI^kayKyQ^ihql>iqorfpqebPrccbobo%/4+1)10+.&^kaq^hb^ofabtfqeqebao^dlkyyNFAy666.y
QProsbvqebI^kayKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy666.y

@CfkafkdqebProsfslopyKyCobb2J^d$e^oMofplkbop^q%/3)/1&+HfiiqebLdobpqldbq^hbvqllmbkqeb`^dbp)vlrtfiikbba^hbvclob^`e`^dbyyNFAy6615y
@T^olkqebT^oj^riyKyHfii5T^oj^ri?orqbp^ka5T^oj^riT^oil`hp^olrka%/2)/3&yyNFAy6612y

ED^o^a^oyRy3615yyNFAy.-.-4y
Q>k>ra^`flrp>as^k`byKyGlofkAb^abvb%22+3)04+3&yyNFAy66-4y
Q?ibbafkdEliiltPrmmiv@o^qbpyKyBih^v$d^kqebJvpqf`%22+4)04+3&yyNFAy66.3y
>Afmilj^qf`Jb^probpyKyGlofkAb^abvb%22+3)04+3&yyNFAy.-.-4y

QAfmilj^qf`Jb^probpyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy.-.-4y
>>oj^jbkqpcloAb`bmqflkyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy66/5y
>Orqeibpp@rkkfkdyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy66/4y

@T^kqba7Dfpbia^qeb@olkbyKyHfiiDfpbia^qeb@olkbfkpfabqebi^odb_rfiafkd%4.+1)5/+0&^ka^kv`lj_fk^qflklc.2Hfi$ploolt>dbkqp+J^hbprobqlmi^kqXT^oj^riLdob?^kkbopZlkqebjl_pvlrhfiicloqebnrbpqOrqeibpp@rkkfkdyyRy/222/yyNFAy6602y
@>oj^jbkqpcloAb`bmqflkyKy@liib`q.-XHfi$ploolt>oj^jbkqpZtef`e^obpj^iiob`q^kdri^o_lubp+Qebobfp^qltbo^q%36)44&)dlrmqlqebqlm^kado^__lubp^ilkdqebt^v^ka_vqebqfjbvlrdbqaltkqeblkbplkqeb_lqqljpelriae^sbobpm^tkbayyRy/222/yyNFAy66/5y
@Orqeibpp@rkkfkdyKyMi^`b.-XT^oj^riLdob?^kkbopZlk^kvab^aHfi$plooltjl_p%4-)5-&yyRy/222/yyNFAy66/4y

QOrqeibpp@rkkfkdyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy66/4y
Q>oj^jbkqpcloAb`bmqflkyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy66/5y
>ObqrokfkdqebC^sloyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy660.y
>?lavlcBsfabk`byKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy660/y

>FJrpqE^sbQebjyKyT^w^q%3.+4)34&yyNFAy.-.-6y

OKbpfkdt^ovP^c^ofyKyFkqebkloqeb^pq`lokbolcqebwlkb%4.)1-&yyNFAy6521y
QQebKbpfkdt^ovP^c^ofyKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy.-..1y
>Tfkaol`J^pqbov%M^oq.&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6521y
>@ibcqellcJ^pqbov%M^oq.&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy6456y
>Q^i_rhJ^pqbov%M^oq.&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6524y

@Tfkaol`J^pqbov%M^oq.&yKyHfii./Tfkaol`p^olrka%35)06&yyNFAy6521y
@Q^i_rhJ^pqbov%M^oq.&yKyHfii./Q^i_rhPq^dp^olrka%3-)1/&yyNFAy6524y
@@ibcqellcJ^pqbov%M^oq.&yKyHfii./@ibcqellc^olrka%32)14&yyNFAy6456y

@FJrpqE^sbQebjyKyHfiiArpqEltibop^olrka%4-)1/&clo0uX>foBibjbkq^iD^pZyyNFAy.-.-6y
>QebEltifkdTfkayRy/12-1yyKyQebfqbjXEltifkdTfkaZpq^oqpnrbpq*aolmmba_vArpqEltibop^olrka%4-)1/&yyNFAy653.y

QTfkaol`J^pqbov%M^oq.&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6521y
>Tfkaol`J^pqbov%M^oq/&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6522y
Q@ibcqellcJ^pqbov%M^oq.&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy6456y
>@ibcqellcJ^pqbov%M^oq/&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652-y
QQ^i_rhJ^pqbov%M^oq.&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6524y
>Q^i_rhJ^pqbov%M^oq/&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6525y

OD^o^a^oyKyOrkqlD^o^a^o%23+4)01+3&yyNFAy653/y
QT^kqba7Dfpbia^qeb@olkbyKyT^oabk?riiolh%22+5)04+6&yyNFAy6602y

QQebQeolkblcqebBibjbkqpyKyBibjbkq^ifpqPe^os^h%3-+3)//+/&yyNFAy654-y
QQebEltifkdTfkayKyBibjbkq^ifpqJlode%3-+2)//+1&yyNFAy653.y
>Jroh_illa@loormqbopyKyBibjbkq^ifpqJlode%3-+2)//+1&yyNFAy653/y
>QebRkabokb^qeyKyBibjbkq^ifpqRkqo^d%3-+4)//+2&yyNFAy65.5y
>>O^ob?b^kyKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65--y
>Jr`hAfsfkdyKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65.2y
QQebRkabokb^qeyKyDloa^td%3-)/1&*jlsbp^olrkaqefp^ob^yyNFAy65.5y
>QebQloqrobaB^oqeyKyDloa^td%3-)/1&*jlsbp^olrkaqefp^ob^yyNFAy65.6y

@Q^i_rhJ^pqbov%M^oq/&yKyHfii./Q^i_rhQelokdo^wbop^olrka%2-)/0&)_bqtbbkI^rdefkdphriiorfkp^kaQeolkblcbibjbkqp+Hbbm^kbvblrqcloarkdclo>O^ob?b^kqll*fqob^iiv_ibkapfk)_rqfq$pfkqefp^ob^yyNFAy6525y
@@ibcqellcJ^pqbov%M^oq/&yKyHfii./@ibcqellc?riip^olrkaqefp^ob^%2-)0-&yyNFAy652-y
@>O^ob?b^kyKyDbq5XAfdbpqba@^o^`lifZ^olrka%2.)/5&+Illhclopj^iiarjmplkqebdolrkayyNFAy65--y

Q>O^ob?b^kyKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65--y
>>dfq^qbaPmfofqplcPhvplkdyKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65-1y

@>dfq^qbaPmfofqplcPhvplkdyKyAfsbfkqlPhvplkdI^hbqlhfii./I^hbPmfofqp^olrka%25)/4&yyNFAy65-1y
@QebQloqrobaB^oqeyKyHfii.-QloqrobaB^oqePmfofqpil`^qba^iilsboqebb^pqbokm^oqlcqebwlkb+Dllail`^qflkfpgrpqb^pqlcD^o^a^o^olrka%34)0/&yyNFAy65.6y

QQebQloqrobaB^oqeyKyDloa^td%3-)/1&*jlsbp^olrkaqefp^ob^yyNFAy65.6y
>B^qfkdA^jk^qflkyKyDloa^td%3-)/1&*jlsbp^olrkaqefp^ob^yyNFAy65/.y
Q>dfq^qbaPmfofqplcPhvplkdyKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65-1y
>?ibppfkdlcFk`fkbo^qrpyKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65-2y

@B^qfkdA^jk^qflkyKyDbq.-XBko^dba@orpebo@lobpZaolmmba_vBko^dba@orpebop+Grpqork^ilkdqebjlrkq^fko^kdbbuqbkafkdcoljqebQeolkblcqebBibjbkqpqlI^rdefkdPhriiOrfkp%2/)/.&)%22+2).5+2&yyNFAy65/.y
QB^qfkdA^jk^qflkyKyDloa^td%3-)/1&*jlsbp^olrkaqefp^ob^yyNFAy65/.y
>Pe^qqbofkdqebSbfiyKyDloa^td%3-)/1&*jlsbp^olrkaqefp^ob^yyNFAy6516y

@?lavlcBsfabk`byRy/2325yyKyRpbqebXA^jmTllibk?i^khbqZlkqebmvobfkqebI^rdefkdPhrii@lroqv^oa%14)/1&+Ldobptfiipm^tk^kaqebvtfiipq^oqmi^`fkdlo``lompbp^olrkaqebmvob)vlrjrpqmolqb`qqebjtefibqebvalfq)^kaalk$qclodbqqlpqf`h_^kkbopfkqebjl_pvlrhfiiyyNFAy660/y
@T^kqba7Wlo_lqeb>asfployKyHfiiWlo_lqeb>asfplo^qqeb`^sb%13+1).5+1&^ka2T^oj^riPe^j^k^ka2T^oj^riOb^sbop^olrka%13)/.&+Objbj_boqlhbbmmi^kqfkd_^kkbopyyRy/2222yyNFAy6606y
@ObqrokfkdqebC^sloyKyMi^`b.-XHfi$ploolt?^kkbopZqeolrdeqeb_lafbplcT^oj^rildobp^olrka%13).5&yyRy/2222yyNFAy660.y

@?ibppfkdlcFk`fkbo^qrpyKyRpbqebXIfsfkdCfobZqlabpqolvqeberqp+I^odberq%4.+5)16+2&)Tbpqbokerq%4.+0)2-+5&)Plrqebokerq%4.+2)20&^kaB^pqbokerq%40)21+2&+Qlpbqcfobqlqeb_fderqvlrkbbaql_b`ilpbqlfq$p`bkqbomlibyyRy/1134yyNFAy65-2y

Q@ibcqellcJ^pqbov%M^oq/&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652-y
>@ibcqellcJ^pqbov%M^oq0&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652.y
QQ^i_rhJ^pqbov%M^oq/&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6525y
>Q^i_rhJ^pqbov%M^oq0&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6526y

QObqrokfkdqebC^sloyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy660.y
Q?lavlcBsfabk`byKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy660/y
>Jbpp^dbqlD^o^a^oyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy6601y

ED^o^a^oyRy3615yyNFAy.-...y
QJbpp^dbqlD^o^a^oyKyD^oolpe%22)05&yyNFAy6601y
QT^kqba7Wlo_lqeb>asfployKyT^oabk?riiolh%22+5)04+6&yyNFAy6606y

QFJrpqE^sbQebjyKyT^w^q%3.+4)34&yyNFAy.-.-6y
KLmqflk^iNrbpqyKyQebkbuqnrbpq?ofkdJbQebBddfpb^pfivalkbplil)qebe^oam^oqfpdbqqfkdqlqebbddtef`efpsbovqof`hvyyNFAy.-...y
>?ofkdJbQebBddyKyT^w^q%3.+4)34&yyNFAy.-...y
@?ofkdJbQebBddyKyAlqefpk^hbaplvlralk$qilpb^kvaro^_fifqvfcvlrafb+RpbqebGrjm*^*qolk1---kbuqqlT^w^q%3.+4)34&qli^rk`evlropbicfkqlqeb^fo+Vlrkbbaqlofdeq`if`hqeb$Grjm^Qolk$_rcc^qqebofdeqqfjbqli^kalkqebkbpq+Fcvlr$obe^sfkdqolr_ibdlqlvlrqr_b+`ljqlt^q`e^sfabllkfq+>cqbovlrillqqebbddt^fq0-pb`cloqebJ^qof^`eql^mmb^oqlhfiifqyyNFAy.-...y
Q?ofkdJbQebBddyKyT^w^q%3.+4)34&yyNFAy.-...y
@Tfkaol`J^pqbov%M^oq/&yKyHfii./O^sbklrpTfkaol`p^olrka%2-)3-&yyNFAy6522y
HJroh_illaFks^abopyKyHfiiJroh_illaFks^abopm^qoliifkdqebol^a_bqtbbk%1/)25+4&^ka%/5+2)24+.&qldbqfqbjXJroh_illaFks^pflkMi^kpZqlpq^oqkbtnrbpqyyIy/1226yyNFAy654.y
>Jroh_illaFks^abopyKyRpbqebXJroh_illaFks^pflkMi^kpZql^``bmqnrbpqyyRy/1226yyNFAy654.y

O>bofpI^kafkdyKyArbplrqelcPrkpmofkd%0.)24&+Cliiltqebol^atbpqqebkplrqe)loorkqeorE^i^^fcfqfpk$qltkba_vqeb^iif^k`b+T^q`elrqcloqebm^qoliplkqebj^fkol^ayyNFAy66/2y
QQeb@lkploqfrjKbbapVlryKyDbweb%0.+1)24+4&yyNFAy66.0y
>J^qqboplcPb`rofqvyKyWbofa%0-+5)25+/&yyNFAy66/2y
>Pqb^ifkdcoljQefbsbpyKyDbweb%0.+1)24+4&yyNFAy655/y
>D^s^$ufyKyWbofa%0-+5)25+/&yyNFAy66--y
>>Eb^aCriilcFslovyKyPe^aobh%0.+4)23+5&yyNFAy66.1y

@Jr`hAfsfkdyKyObqofbsb2XJr`h*ofaabk@lobpZfkqebt^qbo^olrkaE^i^^%11)15&yyNFAy65.2y

QJr`hAfsfkdyKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65.2y
Q?ibppfkdlcFk`fkbo^qrpyKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65-2y
>QebPmfofqMliirqbayKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65.-y

QTfkaol`J^pqbov%M^oq/&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6522y
>Tfkaol`J^pqbov%M^oq0&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6523y

@QebPmfofqMliirqbayKyAbpqolvT^qllprk$pMliirqbaBppbk`b^ka5I^hbProdbop^q%00)2-&yyNFAy65.-y
@SfibFali^qovyKyDbq/-XJroh_illaFalipZ^qPrkpmofkdMlpq%0/)12&yyNFAy6530y
@Jroh_illaIb^abop+++yKyHfiiLoqlolcJroh_illa^q%0-)1/&fk^_fderqyyNFAy6534y
@Lk`bTbobT^ooflopyKyHfii/-Jroh_illaP`^sbkdbop^ka/-Jroh_illaO^fabop^olrka%0.)1/&yyNFAy6532y
@Jroh_illa@loormqbopyKyHfii2Jroh_illaMrqofcfbop^olrka%0-)1-&yyNFAy653/y
>QebQlqbjlcH^o$a^peyKyHrobk^f@^mqfsb%00)1/&yyNFAy6535y
@QebQlqbjlcH^o$a^peyKyBp`loqqebHrobk^f@^mqfsbyyNFAy6535y

QT^olkqebT^oj^riyKyBiaboVloibv%0/+0)03+/&yyNFAy6612y
QCfkafkdqebProsfslopyKyBiaboRkdofw%0/+1)03+/&yyNFAy6615y
QLk`bTbobT^ooflopyKyP^roc^kdqebVlrkdbo%0/+2)03+.&yyNFAy6532y
>EbTfiiT^ihQebB^oqe+++yKyP^roc^kdqebVlrkdbo%0/+2)03+.&yyNFAy6533y

@Tfkaol`J^pqbov%M^oq0&yKyVlrpelria_b^_ibqlplilqefpb^pv)vlr`^kcfkaDrqofmmbo^olrkaqebdo^pp_bclobT^oj^riEfii^olrka%00)0-&yyNFAy6523y
@Q^i_rhJ^pqbov%M^oq0&yKyHfii?^`e$ilo^ka`liib`qefpellc)vlrpelria_b^_ibqlplilqefpnrbpq)ebm^qolip_bqtbbkqebqtlClodb@^jmp%/2)15&)%/4)05&yyNFAy6526y

QJroh_illa@loormqbopyKyBibjbkq^ifpqJlode%3-+2)//+1&yyNFAy653/y

@Pe^qqbofkdqebSbfiyKyRpbXDloa^td$p?lriaboZqlpe^qqboqebPe^qqbobaOrj_ibop^kaqebJfkflkplcDrolhtfiipm^tk+Hfii0-^olrka%05)5.&yyRy/12-.yyNFAy6516y
@>Eb^aCriilcFslovyKyHfii^kvTfiaBibhhvlrpbbclo0uXM^folcFslovQrphpZyyNFAy66.1y
@D^s^$ufyKyHfiiD^s^$uflkqlmlc^efiib^pqlcLper$drk%10)41&yyNFAy66--y
@Pqb^ifkdcoljQefbsbpyKyDbq.-XLper$drk@ovpq^iCo^djbkqpZaolmmba_vSfo$^^kfO^fabop^ka>o`^kfpqp^olrka%01)30&+Vlr`^k^iplillqqebjlccqebdolrkafkqefp^ob^yyNFAy655/y
@J^qqboplcPb`rofqvyKyHfii5Slfapm^tk^olrka%06)30&yyNFAy66/2y
@@ibcqellcJ^pqbov%M^oq0&yKyHfii?^kqe^o^ka`liib`qefpelok)ebm^qolipfk^olrkaLper$drk%0.)2.&)%1/)3.&yyNFAy652.y

QJ^qqboplcPb`rofqvyKyWbofa%0-+5)25+/&yyNFAy66/2y
QPqb^ifkdcoljQefbsbpyKyDbweb%0.+1)24+4&yyNFAy655/y
QD^s^$ufyKyWbofa%0-+5)25+/&yyNFAy66--y
Q>Eb^aCriilcFslovyKyPe^aobh%0.+4)23+5&yyNFAy66.1y

ED^o^a^oyRy3615y
QQebQlqbjlcH^o$a^peyKyD^oolpe%22)05&yyNFAy6535y
QSfibFali^qovyKyC^opbboHrohrpe%21+5)06+1&yyNFAy6530y
QJroh_illaIb^abop+++yKyC^opbboJ^od^abpe%21+3)06+6&yyNFAy6534y
QEbTfiiT^ihQebB^oqe+++yKyC^opbbo@loerh%21+5)06+5&yyNFAy6533y

QQebPmfofqMliirqbayKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65.-y
QPe^qqbofkdqebSbfiyKyDloa^td%3-)/1&*jlsbp^olrkaqefp^ob^yyNFAy6516y

OKbpfkdt^ovP^c^ofyKyFkqebkloqeb^pq`lokbolcqebwlkb%4.)1-&y
QTfkaol`J^pqbov%M^oq0&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6523y
Q@ibcqellcJ^pqbov%M^oq0&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652.y
QQ^i_rhJ^pqbov%M^oq0&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6526y
KLmqflk^iNrbpqyKyQebRiqfj^qb?illapmloqfptloqealfkd_rqvlrkbbaebimcolj^qib^pq.jlobmi^vbolqebotfpbphfmqlkbuqdrfabyyNFAy652/y
>QebRiqfj^qb?illapmloqyKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652/yyLy
@QebRiqfj^qb?illapmloqyLyyKyHfiiQrphbo%11)32&^ka`liib`qXEb^oqlcQrphboZvlrtfiikbbaebimcloqefpnrbpqlqebotfpbphfmfqyyNFAy652/y
QQebRiqfj^qb?illapmloqyKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652/yyLy
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
