
DugisGuideViewer:RegisterGuide("Blade's Edge Mountains (67-69)", "Howling Fjord (68-71)", "Horde", "L", function()
return [[
AAA

CPt^jmo^qMlpqyKyDrope^%24+/)02+0&yyWyK^do^kayyNFAy.-6/5y
O?i^abp$OrkyKyOrkql?i^ab$pork%35)0/&yyWyW^kd^oj^opeyyNFAy.-6/5y
>Hfiifkdqeb@o^tibopyKyDorkqDo^eh%2/+6)63+/&yyNFAy.-6/5y
@Hfiifkdqeb@o^tibopyKyHfii3@^sbok@o^tiboptef`e`^k_bclrkafkqebqrkkbikb^oqebnrbpqdfsbo^olrka%2/)62&yyNFAy.-6/5y

OQerkaboiloaPqolkdeliayKyOrkqlQerkaboiloaPqolkdelia%2.)25&yyNFAy.-2-0y
QHfiifkdqeb@o^tibopyKyQlo$`erkhQtl`i^tp%2.+6)25+1&yyNFAy.-6/5y
>Qeb?i^abpmfobQeob^qyKyQlo$`erkhQtl`i^tp%2.+6)25+1&yyNFAy.-2-0y
>QebBk`ol^`efkdTfiabokbppyKyDlo$aobh%2/+0)24+6&yyNFAy.-153y
>Cbiifkd^k>k`fbkqQobbyKyT^kqbaMlpqbo%2/)24+4&yyNFAy.-156y
eQerkaboiloaPqolkdeliayKyDeli^e%20+0)22+1&yyNFAy.-21/y

@QebBk`ol^`efkdTfiabokbppyKyHfii./?i^abtfkd?illaibqqbop)qebvciv^ii^olrka%2.)31&yyNFAy.-153y
@Cbiifkd^k>k`fbkqQobbyKyDbqXPqolkdifj_Abbmollq$pQorkhZ+HfiiPqolkdifj_Abbmollq%04+2)46+.-&ebm^qolipqebKloqe*Plrqem^qeofdeq_biltPvis^kk^^oyyNFAy.-156y

O?illaj^riO^sfkbyKyOrkql?illaj^riO^sfkb%11)4/&yyNFAy.-21/y
>QebvPqlibJbEllh^e^kaJb?obtpyKyQ$`e^ifqebTfq`eAl`qlo%12)4/&yyNFAy.-21/y
@QebvPqlibJbEllh^e^kaJb?obtpyKyDbqXQ$`e^if$pEllh^eZkbuqqlqebcfobmi^`b^q%1/+.)5.+0&^ka.-X?illaj^ri?orqb_^kb?obtpZaolmmba_v?obtj^pqbop)_rq`^k^ipl_bclrkafk_^oobip^olrka%13)44&yyNFAy.-21/y
QQebvPqlibJbEllh^e^kaJb?obtpyKyQ$`e^ifqebTfq`eAl`qlo%12)4/&yyNFAy.-21/y
>?i^abpmfobHbddboyKyQ$`e^ifqebTfq`eAl`qlo%12)4/&yyNFAy.-212y
@Qeb?i^abpmfobQeob^qyKyHfii^kv0-?i^abpmfobLdobp^ka.-?i^abpmfobO^mqlop^olrka%1.)2.&+?i^abpmfobO^mqlopaolmqebfqbjXQerkaboiloa@i^k>oqfc^`qZqlpq^oqkbuqnrbpqyyNFAy.-2-0y
@?i^abpmfobHbddboyKyRpbqebX?illaj^ri?orqb_^kbHbdZqldbq2?i^abpmfobLdobpaorkh%10)2/&yyNFAy.-212yyRy0-020y
>Qerkaboiloa@i^k>oqfc^`qpyKyQebfqbjXQerkaboiloa@i^k>oqfc^`qZpq^oqpnrbpq*aolmmba^olrka%1/)21&_v?i^abpmfobO^mqlopyyNFAy.-2/1yyRy0-10.y
@Qerkaboiloa@i^k>oqfc^`qpyKyCfkaqeb>oolt%1.+2)2/+4&)Aorj%1-+/)25+0&^kaQ^_ibq%1.+/)13+2&yyNFAy.-2/1y

Q?i^abpmfobHbddboyKyQ$`e^ifqebTfq`eAl`qlo%12)4/&yyNFAy.-212y
>Dofjklh^kaHlod^^e)F>jCloVlryKyQ$`e^ifqebTfq`eAl`qlo%12)4/&yyNFAy.-210y
@Dofjklh^kaHlod^^e)F>jCloVlryKyHfiiDofjklh?^qqib_lok^q%12)5.&^kaHlod^^e^q%1/+2)14&)rpb^jrdlc_obtqlpfkdibHlod^^elrqyyNFAy.-210y

QDofjklh^kaHlod^^e)F>jCloVlryKyQ$`e^ifqebTfq`eAl`qlo%12)4/&yyNFAy.-210y
>>@ropbRmlk?lqelcVlro@i^kpyKyQ$`e^ifqebTfq`eAl`qlo%12)4/&yyNFAy.-211y
@>@ropbRmlk?lqelcVlro@i^kpyKyRpbXTf`hbaPqolkdCbqfpeZ^ka^kbsfipmfofqtfii^mmb^o)hfiifq^kavlr$sb`ropbaqeberq,_rfiafkd+Vlr`^krpbqebcbqfpelkqebp^jb_rfiafkdjlobqe^klk`b+%13)44&^ka%1/)16&^obb^pverqpql^``ljmifpeqefpnrbpqyyNFAy.-211yyRy0-146y

Q>@ropbRmlk?lqelcVlro@i^kpyKyQ$`e^ifqebTfq`eAl`qlo%12)4/&yyNFAy.-211y
EQerkaboiloaPqolkdeliayRy3615yyNFAy.-2-2y
QCbiifkd^k>k`fbkqQobbyKyQlo$`erkhQtl`i^tp%2.+4)24+4&yyNFAy.-156y
QQeb?i^abpmfobQeob^qyKyQlo$`erkhQtl`i^tp%2.+4)24+4&yyNFAy.-2-0y
QQebBk`ol^`efkdTfiabokbppyKyDlo$aobh%2/+0)24+6&yyNFAy.-153y
QQerkaboiloa@i^k>oqfc^`qpyKyOlhd^e?illadofm%2/+5)25+6&yyNFAy.-2/1y
>Qeb?illaj^riLdobpyKyQlo$`erkhQtl`i^tp%2.+4)24+4&yyNFAy.-2-2y
>ArpqcoljqebAo^hbpyKyDlo$aobh%2/+0)24+6&yyNFAy.-154y
>SfpflkDrfabyKyOlhd^e?illadofm%2/+5)25+6&yyNFAy.-2/2y
@SfpflkDrfabyKyRpbqebXCfbovPlriCo^djbkqZfkqebcolkqlcqebnrbpqdfsbo%2/)26&^kavlr$ii_b`ljb^tfpm^kadl^rqlmfilq^qqebmi^`bvlre^sbqldlyyNFAy.-2/2yyRy0-15.y
QSfpflkDrfabyKyOlhd^e?illadofm%2/+5)25+6&yyNFAy.-2/2y
>QebQerkabopmfhbyKyOlhd^e?illadofm%2/+5)25+6&yyNFAy.-2/3y
@ArpqcoljqebAo^hbpyKyHfiiCbvAo^hbp^olrka%06)35&qldbq1XArpqplcqebCbvAo^hbZyyNFAy.-154y
@QebQerkabopmfhbyKyHfiiDloDofjdrqqldbqXQebQerkabopmfhbZ^qbkalcqeb`^sb%06)52&yyNFAy.-2/3y
@Qeb?illaj^riLdobpyKyHfii^kv0-?illaj^riLdobp^olrka%11)4/&yyNFAy.-2-2y

EQerkaboiloaPqolkdeliayKyEb^oqeloork_^`hyyRy3615yyNFAy.-155y
QQeb?illaj^riLdobpyKyQlo$`erkhQtl`i^tp%2.+4)24+4&yyNFAy.-2-2y
QQebQerkabopmfhbyKyOlhd^e?illadofm%2/+5)25+6&yyNFAy.-2/3y
QArpqcoljqebAo^hbpyKyDlo$aobh%2/+0)24+6&yyNFAy.-154y
>Molqb`qfkdLroLtkyKyDlo$aobh%2/+0)24+6&yyNFAy.-155y
>QebPmfofqpE^sbSlf`bpyKyD^ojTlic_olqebo%2/+3)26&yyNFAy.-4.5y
QQebPmfofqpE^sbSlf`bpyKyObuu^o%2.+5)25+2&yyNFAy.-4.5y
>TefpmboplkqebTfkayKyObuu^o%2.+5)25+2&yyNFAy.-3.1y
@Molqb`qfkdLroLtkyKyRpbXDlo$aobh$pLfkqjbkqZlk2QerkaboiloaAfobTlisbpclrkaafob`qivplrqelcQerkaboiloaPqolkdelia%2.)3/&yyNFAy.-155yyRy0-.42y
QMolqb`qfkdLroLtkyKyDlo$aobh%2/+0)24+6&yyNFAy.-155y

OBsbodolsbyKyOrkqlBsbodolsb%3.)06&yyNFAy.-35/y
>>QfjbcloKbdlqf^qflk+++yKyQobbT^oabk@e^tk%3/)06&yyNFAy.-35/y
>@ob^qfkdqebMbka^kqyKyQfjblk%3.+3)06+0&yyNFAy.-234y
>@riifkdqebTfiayKyC^o^aobii^%3/)05&yyNFAy.-420y
>IfqqibBj_bopyKyJlpptllaqeb>k`fbkq%3-+5)05+1&yyNFAy.-44-y
>Coljqeb>pebpyKyJlpptllaqeb>k`fbkq%3-+5)05+1&yyNFAy.-44.y
@>QfjbcloKbdlqf^qflk+++yKyQ^ihtfqeLsbopbboKr^^o+Ebt^ihpKloqe^kaPlrqerm^kaaltkqebm^qeqlqebtbpqlcBsbodolsb_bqtbbk%3/)12&^ka%30)/5&yyNFAy.-35/y
Q>QfjbcloKbdlqf^qflk+++yKyQobbT^oabk@e^tk%3/)06&yyNFAy.-35/y
>+++^ka^Qfjbclo>`qflkyKyQobbT^oabk@e^tk%3/)06&yyNFAy.-4.0y
>Ml^`efkdcoljMl^`ebopyKyP^jf^Fkhifkd%3.+6)06+2&yyNFAy.-4.4y
@+++^ka^Qfjbclo>`qflkyKyHfii.-Tvoj`riqEbtbop^olrka%25)05&yyNFAy.-4.0y
@Ml^`efkdcoljMl^`ebopyKyDbq2XTvoj`riqKbqpZaolmmba_vTvoj`riqMl^`ebop^olrka%26)03&+>iplaolmpfqbjXJbbqfkdKlqbZclokbuqnrbpqyyNFAy.-4.4y
>AfaVlrDbqQebKlqb<yKyQebfqbjXJbbqfkdKlqbZpq^oqpnrbpq*aolmmba_vTvoj`riqEbtbop^kaMl^`ebop^olrka%25)05&yyNFAy.-4.6yyRy0../-y

Q+++^ka^Qfjbclo>`qflkyNFAy.-4.0yyKyQobbT^oabk@e^tk%3/)06&y
QAfaVlrDbqQebKlqb<yKyQobbT^oabk@e^tk%3/)06&yyNFAy.-4.6y
>TvojphriiT^q`eboyKyQobbT^oabk@e^tk%3/)06&yyNFAy.-561y
QMl^`efkdcoljMl^`ebopyKyP^jf^Fkhifkd%3.+6)06+2&yyNFAy.-4.4y
>TebimplcqebTvoj`riqyKyP^jf^Fkhifkd%3.+6)06+2&yyNFAy.-414y
@@ob^qfkdqebMbka^kqyKyHfii^kvlcqeb^o^hhl^^olrka%32)0-&qldbq3XOrr^k$lh@i^tpZ+Rpbqebj^qqebdobbk`fo`ibqlprjjlkE^o_fkdbolcqebO^sbk^kahfiiefjcloXE^o_fkdbo$pMbka^kqZyyNFAy.-234y
Q@ob^qfkdqebMbka^kqyKyQfjblk%3.+3)06+0&yyNFAy.-234y
>TefpmboplcqebO^sbkDlayKyQfjblk%3.+3)06+0&yyNFAy.-3-4y
QTvojphriiT^q`eboyKyT^q`eboJllkpe^ab%2-+.)03+.&yyNFAy.-561y
>Ilkdq^fifpqebIvk`emfkyKyT^q`eboJllkpe^ab%2-+.)03+.&yyNFAy.-560y
@Ilkdq^fifpqebIvk`emfkyKyHfiiAo^^`^Ilkdq^fi^q%13)0/&fkqeb`^sbyyNFAy.-560y
QIlkdq^fifpqebIvk`emfkyKyT^q`eboJllkpe^ab%2-+.)03+.&yyNFAy.-560y
>Jbbqfkd^qqeb?i^`htfkd@lsbkyKyT^q`eboJllkpe^ab%2-+.)03+.&yyNFAy.-4//y
@TefpmboplcqebO^sbkDlayKyCfopq%06).4&)Pb`lka%1/)//&)Qefoa%1.).6&^kaClroqe%1-)/0&+Qebcfopq^kapb`lka^oblkqlmlclkblcqebqobbqltbopyyNFAy.-3-4y
>QebQorqeRklo_bayKyQebfqbjXLo_lcqebDofpek^Zpq^oqpnrbpq*aolmmba_v^kvlcqebDofpek^^o^hhl^p^olrka%1-)/.&yyNFAy.-5/2yyRy0.156y
@TebimplcqebTvoj`riqyKyRpbqebX?i^`htebimKbqZql`^mqrob.-Tvoj`riq?i^`htebimpclrkafkqeb`^sb^q%0.)0/&+Vlr`^kqob^alkqebbddpqlpm^tkjlobyyNFAy.-414yyRy0../6y
@Jbbqfkd^qqeb?i^`htfkd@lsbkyKy@liib`q2X@lpqrjbP`o^mpZ^olrka%0-)0.&qlclojafpdrfpbyyNFAy.-4//y

EQerkaboiloaPqolkdeliayRy3615yyNFAy.-415y
CBsbodolsbyKyRklhbQbkaboellc%2/+.)21+/&yyNFAy.-415y
QTefpmboplcqebO^sbkDlayKyQfjblk%3.+3)06+0&yyNFAy.-3-4y
QTebimplcqebTvoj`riqyKyP^jf^Fkhifkd%3.+6)06+2&yyNFAy.-414y
QQebQorqeRklo_bayKyQobbT^oabk@e^tk%3/)06&yyNFAy.-5/2y
QJbbqfkd^qqeb?i^`htfkd@lsbkyKyQobbT^oabk@e^tk%3/)06&yyNFAy.-4//y
>J^uk^oJrpqAfbyKyQobbT^oabk@e^tk%3/)06&yyNFAy.-415y
>Qobb_libJrpqHkltyKyQobbT^oabk@e^tk%3/)06&yyNFAy.-5/6y
@@riifkdqebTfiayKyHfii1CbiptlokP`^ibtfkd)1CbiptlokA^ddboj^t^ka/Cbi@loormqbop^olrka%4-)01&yyNFAy.-420y
>A^j^dbaJ^phyKyQebfqbjXA^j^dbaJ^phZpq^oqpnrbpq*aolmmba_vCbi@loormqbop^olrka%4-)02&yyNFAy.-5.-yyRy0.051y
@IfqqibBj_bopyKyHfii5P`lo`eFjmp^olrka%4/)/0&yyNFAy.-44-y
@Coljqeb>pebpyKyMi^kqqebXFolkollqPbbapZ^qqeb0plfijlrkap*Plrqebok)%4.)//&)@bkqo^i%4.)/-&^kaKloqebok%4.).5&+Ilqplcbibjbkq^ip^kafjmp)_bmobm^obaclo^ilqlccfoba^j^dbyyNFAy.-44.yyRy0.0--y

OJlh$K^qe^iSfii^dbyKyOrkqlJlh$K^qe^iSfii^db%41)30&yyNFAy.-4-6y
eJlh$K^qe^iSfii^dbyKyJ^qolkS^o^e%43+.)3-+0&yyNFAy.-4-6y
QTefpmboplkqebTfkayKyIbloluu%42+.)3.&yyNFAy.-3.1y
>ObrkflkyKyIbloluu%42+.)3.&yyNFAy.-4-6y
>QebPqlkbplcSbhe$kfoyKyAboqolh%42+.)3/&yyNFAy.-232y
>QebPlcqbpqTfkdpyKyPfij^o^%42+5)3.+2&yyNFAy.-3.5y
>Pfihtfkd@l`llkpyKyQ^bobh%42+5)3.+2&yyNFAy.-3.4y
>Jlh$K^qe^iQob^qpyKyJ^qolkS^o^e%43+.)3-+0&yyNFAy.-53-y
@Pfihtfkd@l`llkpyKyDbq5XPfihtfkd@l`llkpZcoljPfihtfkdI^os^^olrka%41)33&yyNFAy.-3.4y
@QebPlcqbpqTfkdpyKy@liib`q./XFofabp`bkqTfkdpZ^olrka%42)36&yyNFAy.-3.5y
@QebPqlkbplcSbhe$kfoyKy@liib`q^XSbhe$kfo@ovpq^iZcoljkb^o_vjl_p)qebk`e^odbfq^qqebpmbii`fo`ib^q%45)42&yyNFAy.-232y

QQebPqlkbplcSbhe$kfoyKyAboqolh%42+.)3/&yyNFAy.-232y
QQebPlcqbpqTfkdpyKyPfij^o^%42+5)3.+2&yyNFAy.-3.5y
QPfihtfkd@l`llkpyKyQ^bobh%42+5)3.+2&yyNFAy.-3.4y
>Rkabopq^kafkdqebJlh$K^qe^iyKyIbloluu%42+.)3.&yyNFAy.-513y
>Qof^i^kaBooloyKyAboqolh%42+.)3/&yyNFAy.-233y
@Qof^i^kaBooloyKyCfkaqeb`vopq^ip^ka>o^hhl^LdobPi^sbp^q%4/)41&yyNFAy.-233y
@Rkabopq^kafkdqebJlh$K^qe^iyKyHfiiSbhefkqeb`^sb^q%36+1)4/+0&yyNFAy.-513y

QRkabopq^kafkdqebJlh$K^qe^iyKyIbloluu%42+.)3.&yyNFAy.-513y
QQof^i^kaBooloyKyAboqolh%42+.)3/&yyNFAy.-233y
>Orr^kTb^iayKyAboqolh%42+.)3/&yyNFAy.-3.2y
>Pfk`bQfjbClodlqqbk+++yKyIbloluu%42+.)3.&yyNFAy.-510y
>QebQlqbjplcJvBkbjvyKyPmfofq`^iiboAled^o%41+2)3-+6&yyNFAy.-52.y
KDofkakloqeql%24)23&tefibtlohfkdlkQob^qpyNFAy.-510y
@Pfk`bQfjbClodlqqbk+++yKyHfiiDklpe?oldk^q%24+0)21+/&yyNFAy.-510y
@QebQlqbjplcJvBkbjvyKyDbq2X?i^abpmfobQlqbjpZaolmmba_v?i^abpmfob@orpebop^kaJvpqf`p^olrka%24)24&yyNFAy.-52.y

EJlh$K^qe^iSfii^dbyRy3615yyNFAy.-512y
QPfk`bQfjbClodlqqbk+++yKyIbloluu%42+.)3.&yyNFAy.-510y
QQebQlqbjplcJvBkbjvyKyPmfofq`^iiboAled^o%41+2)3-+6&yyNFAy.-52.y
>Pi^vqeb?ollaJlqeboyKyIbloluu%42+.)3.&yyNFAy.-512y
>Pmfofq@^iifkdyKyPmfofq`^iiboAled^o%41+2)3-+6&yyNFAy.-520y
@Jlh$K^qe^iQob^qpyKyHfiiP`^ibtfkdPbombkqp^kaA^ddboj^tI^peq^fi$p^olrka%32)25&qldbq0XO^mqloOf_pZ^ka0XPbombkqCibpeZyyNFAy.-53-y
@Pi^vqeb?ollaJlqeboyKyHfiiAob^atfkdtelol^jp^olrka%32)45&yyNFAy.-512y
@Pmfofq@^iifkdyKyIbppboKbqeboAo^hbp^ob^olrka%3-)43&)rpbqebXPmfofq@^iifkdQlqbjpZtfpbivqldbq^ii5pmfofqpyyNFAy.-520yyRy0.330y

QJlh$K^qe^iQob^qpyKyJ^qolkS^o^e%43+.)3-+0&yyNFAy.-53-y
QPi^vqeb?ollaJlqeboyKyIbloluu%42+.)3.&yyNFAy.-512y
QPmfofq@^iifkdyKyPmfofq`^iiboAled^o%41+2)3-+6&yyNFAy.-520y
>D^qeboqebLo_pyKyPmfofq`^iiboAled^o%41+2)3-+6&yyNFAy.-526y
@D^qeboqebLo_pyKyRpbqebXLo_@liib`qfkdQlqbjZql`liib`q.2O^w^^kfIfdeqLo_p%33+5)1/+/&+Qebv^obpj^ii^kamfkhcivfkd^olrka+Grpqmrqvlroqlqbjaltk^kaqebv$iicivfkqlfqyyNFAy.-526yyRy0.335y

QD^qeboqebLo_pyKyPmfofq`^iiboAled^o%41+2)3-+6&yyNFAy.-526y
>FkclojIbloluuyKyPmfofq`^iiboAled^o%41+2)3-+6&yyNFAy.-532y
QFkclojIbloluuyKyIbloluu%42+.)3.&yyNFAy.-532y
>Qebob@^k?bLkivLkbObpmlkpbyKyIbloluu%42+.)3.&yyNFAy.-534y
@Qebob@^k?bLkivLkbObpmlkpbyKyDbqqebX@liib`qflklcPlripZ^q%33)11&yyNFAy.-534y

EJlh$K^qe^iSfii^dbyKyEb^oqeloork_^`hqlJlh$K^qe^iSfii^dbyyRy3615yyNFAy.-5./y
QQebob@^k?bLkivLkbObpmlkpbyKyPmfofq`^iiboAled^o%41+2)3-+6&yyNFAy.-534y

CQerkaboiloaPqolkdeliayKyPhv*J^pqboJ^uulo%43)32+1&yyNFAy.-5./y
eQerkaboiloaPqolkdeliayKyDeli^e%20+0)22+1&yyNFAy.-5./y
QObrkflkyKyObuu^o%2.+5)25+2&yyNFAy.-4-6y
>LkPmfofq$pTfkdpyKyObuu^o%2.+5)25+2&yyNFAy.-4.1y

CBsbodolsbyKyRklhbQbkaboellc%2/+.)21+/&yyNFAy.-5./y
QA^j^dbaJ^phyKyL$J^iivW^mk^__bo%3/+4)1-+0&yyNFAy.-5.-y
>JvpqbovJ^phyKyL$J^iivW^mk^__bo%3/+4)1-+0&yyNFAy.-5./y
QOrr^kTb^iayKyQfjblk%3.+3)06+0&yyNFAy.-3.2y
Q@riifkdqebTfiayKyC^o^aobii^%3/)05&yyNFAy.-420y
QJvpqbovJ^phyKyTfiailoa>kqbi^oflk%3.+2)06&yyNFAy.-5./y
QIfqqibBj_bopyKyJlpptllaqeb>k`fbkq%3-+5)05+1&yyNFAy.-44-y
QColjqeb>pebpyKyJlpptllaqeb>k`fbkq%3-+5)05+1&yyNFAy.-44.y
>CbiptlokD^pJ^phyKyTfiailoa>kqbi^oflk%3.+2)06&yyNFAy.-5.6y
@LkPmfofq$pTfkdpyKyCfkaq^ihfkdldobp^olrka%25)00&^karpbXObuu^o$pTefpqibZlkqebjyyNFAy.-4.1yyRy0../5y

CQerkaboiloaPqolkdeliayKyCevkIb^cpe^alt%3.+3)06+3&yyNFAy.-450y
QLkPmfofq$pTfkdpyKyObuu^o%2.+5)25+2&yyNFAy.-4.1y
>?^olkP^_ibj^kbyKyObuu^o%2.+5)25+2&yyNFAy.-450y
Q?^olkP^_ibj^kbyKy?^olkP^_ibj^kb%20+.)1.&yyNFAy.-450y
>Fkqlqeb@erokfkdDri`eyKy?^olkP^_ibj^kb%20+.)1.&yyNFAy.-4.2y
@Fkqlqeb@erokfkdDri`eyKyDbq4X@orpq?ropqboSbkljDi^kapZ^olrka%15)11&aolmmba_vDob^qbo^kaVlrkdbo@orpq?ropqbopyyNFAy.-4.2y
QFkqlqeb@erokfkdDri`eyKy?^olkP^_ibj^kb%20+.)1.&yyNFAy.-4.2y
>?^olkP^_ibj^kb$pMlfplkyKy?^olkP^_ibj^kb%20+.)1.&yyNFAy.-416y

Q?^olkP^_ibj^kb$pMlfplkyKyObuu^o%2.+5)25+2&yyNFAy.-416y
>QebPj^iibpq@ob^qrobpyKyObuu^o%2.+5)25+2&yyNFAy.-4/-y
>@orpeqeb?illaj^ri@^jmyKyQlo$`erkhQtl`i^tp%2.+4)24+4&yyNFAy.-451y

CBsbodolsbyKyRklhbQbkaboellc%2/+.)21+/&yyNFAy.-4/.y
@QebPj^iibpq@ob^qrobpyKyRpbqebXHlalefabAorjZ^qqebj^ojlq`^sb^q%23+2)/6+0&+QebHbdpvlrkbbaqlmlfplk^obfkqeb`^jmgrpqqlqebofdeq%22+0)/5+/&%22+0)/2+62&%22+63)/0+.&yyNFAy.-4/-yyRy0..1.y
@@orpeqeb?illaj^ri@^jmyKyHfii.-?illaj^riJ^ribop^ka2?illaj^riT^oil`hp^olrka%23)/4&yyNFAy.-451y

CQerkaboiloaPqolkdeliayKyCevkIb^cpe^alt%3.+3)06+3&yyNFAy.-4/.y
QQebPj^iibpq@ob^qrobpyKyObuu^o%2.+5)25+2&yyNFAy.-4/-y
Q@orpeqeb?illaj^ri@^jmyKyQlo$`erkhQtl`i^tp%2.+4)24+4&yyNFAy.-451y
>>?l^ofkdQfjbcloDoriil`yKyObuu^o%2.+5)25+2&yyNFAy.-4/.y

CBsbodolsbyKyRklhbQbkaboellc%2/+.)21+/&yyNFAy.-452y
@>?l^ofkdQfjbcloDoriil`yKyRpbXErccbo$pTefpqibZqldbqXDoriil`$pP^`hZ^q%3-+5)14+5&yyNFAy.-4/.yyRy0.02-y
Q>?l^ofkdQfjbcloDoriil`yKy?^olkP^_ibj^kb%20+.)1.&yyNFAy.-4/.y
>Fq$p^Qo^myKy?^olkP^_ibj^kb%20+.)1.&yyNFAy.-452y
OQerkaboiloaPqolkdeliayKyOrkqlQerkaboiloaPqolkdelia%2.)25&yyNFAy.-4/0y
QFq$p^Qo^myKyObuu^o%2.+5)25+2&yyNFAy.-452y
>DlodoljqebAo^dlk*B^qboyKyObuu^o%2.+5)25+2&yyNFAy.-4/0y
>Pi^rdeqbo^q?lriabo$jlhyKyQlo$`erkhQtl`i^tp%2.+4)24+4&yyNFAy.-453y

CBsbodolsbyKyRklhbQbkaboellc%2/+.)21+/&yyNFAy.-5/-y
@CbiptlokD^pJ^phyKyIbdflk@ljjrkf`^qlofp^q%40+0)1-+.&)vlrkbbaqlrpbqebXCbiptlokD^pJ^phZql^`qfs^qbfqyyNFAy.-5.6yyRy0.033y
QCbiptlokD^pJ^phyKyIbdflk@ljjrkf`^qlo%40+0)1-+.&yyNFAy.-5.6y
>Ab`bfsbqevBkbjvyKyIbdflk@ljjrkf`^qlo%40+0)1-+.&yyNFAy.-5/-y
@Ab`bfsbqevBkbjvyKyHfii1Alljclodb>qqbka^kqp^ka1AlljclodbBkdfkbbop^olrka%40)1-&yyNFAy.-5/-y
QAb`bfsbqevBkbjvyKyIbdflk@ljjrkf`^qlo%40+0)1-+.&yyNFAy.-5/-y
QQobb_libJrpqHkltyKyQobb_lib%03)//&yyNFAy.-5/6y
>Bulo`fpfkdqebQobbpyKyQobb_lib%03)//&yyNFAy.-50-y
@Bulo`fpfkdqebQobbpyKyDbq2XDofpek^qeLo_pZ^olrka%1.)/.&^kahfiiAfobO^sbkp^olrka%06)/5&qldbq2XAfobMfkcb^qebopZ+@lj_fkbqebpbfkqlXBulo`fpjCb^qebopZ+Rpbqebcb^qeboplk^O^sbk$pTllaIb^c_b^oaqlpm^tk^Hlf*HlfPmfofq+HfiiqebPmfofq%klqIb^c_b^oa&^kaqebIb^c_b^oatfiiqrokcofbkaiv+Hfii2uHlf*HlfpyyNFAy.-50-yyRy0.2.5y
QBulo`fpfkdqebQobbpyKyQobb_lib%03)//&yyNFAy.-50-y
@DlodoljqebAo^dlk*B^qboyKy@liib`q0XDofpivQlqbjpZcoljqeb?lriabo$jlhldobp+RpbXP^_ibj^kb$pQo^mZ^qqeb^iq^o%0-)//&qlprjjlk^kahfiiDlodolj+Mi^`bqebqlqbjpkb^oefp`lompbyyNFAy.-4/0yyRy0.42/y
@Pi^rdeqbo^q?lriabo$jlhyKyHfii2?lriabo$jlh?orqbp^ka0?lriabo$jlhPe^j^k^olrka%0-)/1&yyNFAy.-453y
@J^uk^oJrpqAfbyKyHfiiJ^uk^oqeb>pej^t^q%00+4)02+4&yyNFAy.-415y

EQerkaboiloaPqolkdeliayRy3615yyNFAy.-4/1y
QDlodoljqebAo^dlk*B^qboyKyObuu^o%2.+5)25+2&yyNFAy.-4/0y
QPi^rdeqbo^q?lriabo$jlhyKyQlo$`erkhQtl`i^tp%2.+4)24+4&yyNFAy.-453y
>Mofplkbolcqeb?i^abpmfobyKyObuu^o%2.+5)25+2&yyNFAy.-4/1y

CBsbodolsbyKyRklhbQbkaboellc%2/+.)21+/&yyNFAy.-41/y
QJ^uk^oJrpqAfbyKyQobbT^oabk@e^tk%3/)06&yyNFAy.-415y
@Mofplkbolcqeb?i^abpmfobyKyHfii?i^abpmfobldobpqldbqqebXTvsbok@^dbHbvZ+Dlqlqeb`^db^q%32+4)/-+.&^karpbqebXPmfofq$pTefpqibZqlprjjlkPmfofqqllmbkqeb`^dbyyNFAy.-4/1yyRy0..11y
QMofplkbolcqeb?i^abpmfobyKyObuu^o%2.+5)25+2&yyNFAy.-4/1y
>PeltaltkyKyObuu^o%2.+5)25+2&yyNFAy.-41/y
@PeltaltkyKyVlrkbbaql_b^_ibqlab^isbovefdea^j^dbob`ljjbkabatfqe^qib^pq/mi^vbop)_rqfqfpmlppf_ibqlplilclopljbmi^vbop)Phfmqefpnrbpqfcvlr$obrk^_ibqlalfq+RpbXObuu^o$p?^qqibElokZ^qqeb^iq^o%31).5&)qebkhfiiDl`yyNFAy.-41/yyRy0..13y
QPeltaltkyKyObuu^o%2.+5)25+2&yyNFAy.-41/y

CPe^qqo^qe@fqvyKyCevkIb^cpe^alt%2/+-2)21+.&y
ORkabo`fqvyKyQ^hbqebmloq^iqlRkabo`fqv%2/+/)2/+6&yyWyPe^qqo^qe@fqvy
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
