DugisGuideViewer:RegisterGuide("Shadowmoon Valley (68-70 |cfff0c502Optional|r)", nil, "Horde", "L", function()
return [[
AAA

OPe^altjllkS^iibvyKyQo^sbiqlPe^altjllkS^iibv%/0)/4+6&yyNFAy.-262y
OPe^altjllkSfii^dbyKyQo^sbiqlPe^altjllkSfii^db%0-)0/&yyNFAy.-262y

>?bpfbdbayKy?illaDr^oaDrijlh%0-+2)0/+2&yyNFAy.-262y
@?bpfbdbayKyHfii.-Fkcbok^i>qq^`hbop^olrka%0-+3)02+2&yyNFAy.-262y
Q?bpfbdbayKy?illaDr^oaDrijlh%0-+2)0/+2&yyNFAy.-262y
>QlIbdflkEliayKy?illaDr^oaDrijlh%0-+2)0/+2&yyNFAy.-263y
>QebPhbqe$ilkTob`h^dbyKyPbodb^kqH^odori%0.+-)/6+6&yyNFAy.-43-y
>Te^qPqo^kdb@ob^qrobp+++yKyObpb^o`eboQflorp%0-+-)/5+0&yyNFAy.-33-y
>QebE^kalcDri$a^kyKyB^oqejbkaboPmifkqellc%/5+2)/3+2&yyNFAy.-35.y
>>E^rkqbaEfpqlovyKy@efbc>mlqeb`^ovEfia^d^oa%/6+6)/4+4&yyNFAy.-3/1y
>>Dorkq$pTloh+++yKyLsboiloaLo$_^olhe%/5+2)/3+2&yyNFAy.-4-/y
ePe^altjllkSfii^dbyKyFkkhbbmboA^od?illa`i^t%0-+/)/4+5&yNFAy.-125y

KHfii^pvlrnrbpq++yKyHfii^kvCbi_l^op)Sfibtfkd@efj^bo^p^kaP`lo`epebiiMfk`bop^olrkavlr`ljb^`olppcloMrqLkVboHkbbm^ap+++%0/)1.&+>iplillq^kvXBsbo*_rokfkd>peZvlrpbb)^kahfiiAfbjbqo^alkpcloPmibbkafa%0.)06&yyNFAy.-4-0y
QQebE^kalcDri$a^kyKyB^oqejbkaboQloilh%1/+/)12+-&yyNFAy.-35.y
>Bko^dbaPmfofqplcCfob^kaB^oqeyKyB^oqejbkaboQloilh%1/+/)12+-&yyNFAy.-125y
@Bko^dbaPmfofqplcCfob^kaB^oqeyKyRpbqebqlqbj)qebkhfiiqebbibjbkq^ipkb^ofqyyRy0--61yyNFAy.-125y
QBko^dbaPmfofqplcCfob^kaB^oqeyKyB^oqejbkaboQloilh%1/+/)12+-&yyNFAy.-125y
>Bko^dbaPmfofqplcT^qboyKyB^oqejbkaboQloilh%1/+/)12+-&yyNFAy.-15-y
@Bko^dbaPmfofqplcT^qboyKyHfiit^qbobibjbkq^ipqlqebkloqeb^pq^q@lfiph^oMlfkq%14+-)//+-&+Rpbqebqlqbj)p^jb^p_bclob+yyRy0--61yyNFAy.-15-y

@QebPhbqe$ilkTob`h^dbyKyKloqeb^pq^qqebPhbqe$ilkTob`h^db%04+/)0-+2&yyNFAy.-43-y
@Te^qPqo^kdb@ob^qrobp+++yKy>qqebdobbki^s^i^hbfkcolkqlcIbdflkElia%0.+-)05+2&yyNFAy.-33-y
@>E^rkqbaEfpqlovyKyP^jbi^hb^pTe^qPqo^kdb@ob^qrobp++++Vlr`^k^iplcfkapljbqlqebb^pq^q^i^s^i`obs^pb%03+3)06+6&yyNFAy.-3/1y

@QlIbdflkEliayKyKloqetbpq^qIbdflkElia%/0+3)03+6&+CfkaqebIbdflk@ljjrkf`^qflkAbsf`brmfkqeb_rfiafkd^karpbvlroafpdrfpb+yyRy0-305yyNFAy.-263y

Q>E^rkqbaEfpqlovyKy@efbc>mlqeb`^ovEfia^d^oa%/6+6)/4+4&yyNFAy.-3/1y
>Pmb`qob`ibpyKy@efbc>mlqeb`^ovEfia^d^oa%/6+6)/4+4&yyNFAy.-3/2y
QTe^qPqo^kdb@ob^qrobp+++yKyObpb^o`eboQflorp%0-+-)/5+0&yyNFAy.-33-y
>Co^khiv)FqJ^hbpKlPbkpb+++yKyObpb^o`eboQflorp%0-+-)/5+0&yyNFAy.-34/y

RRpbXPmb`qob`ibpZyRy0-4.6yyNFAy.-3/2y
@Pmb`qob`ibpyKyTb^oqebXPmb`qob`ibpZplvlr`^kpbbqebpe^altjllkpmfofqp%03)22&+Hfii./Pe^altjllkE^o_fkdbop+Vlralk$qe^sbqlib^sbqebpqolkdeliayyyRy0-4.6yyNFAy.-3/2y
QPmb`qob`ibpyKy@efbc>mlqeb`^ovEfia^d^oa%/6+6)/4+4&yyNFAy.-3/2y
>QbolkDlobcfbka*Ilob^kaIbdbkayKy@efbc>mlqeb`^ovEfia^d^oa%/6+6)/4+4&yyNFAy.-300y
QQebPhbqe$ilkTob`h^dbyKyPbodb^kqH^odori%0.+-)/6+6&yyNFAy.-43-y
>CfkaqebAbpboqboyKyPbodb^kqH^odori%0.+-)/6+6&yyNFAy.-43.y
QQlIbdflkEliayKy?illaDr^oaDrijlh%0-+2)0/+2&yyNFAy.-263y
>PbqqfkdRmqeb?lj_yKy?illaDr^oaDrijlh%0-+2)0/+2&yyNFAy.-264y

QBko^dbaPmfofqplcT^qboyKyB^oqejbkaboQloilh%1/+/)12+-&yyNFAy.-15-y
>Bko^dbaPmfofqplc>foyKyB^oqejbkaboQloilh%1/+/)12+-&yyNFAy.-15.y

@Co^khiv)FqJ^hbpKlPbkpb+++yKyQeb@lkqoliRkfqfp^q%3.+6)1-+-&^_aqebDob^qboCbicfobAfbjbqo^alkp^obclrka^olrka%25+2)1.+4&yyNFAy.-34/y

QCfkaqebAbpboqboyKyM^ope^e%02+0)05+6&)T^kabofkdKM@yyNFAy.-43.y
>>pde^o$pQlqbjyKyM^ope^e%02+0)05+6&)T^kabofkdKM@yyNFAy.-444y
@>pde^o$pQlqbjyKyHfii>pde^o^qqebPhbqe$ilkTob`h^db^olrka%1-+2)0-+.&yyNFAy.-444y

Q>pde^o$pQlqbjyKyM^ope^e%02+0)05+6&)T^kabofkdKM@yyNFAy.-444y
>QebOlalcIf^kqebyKyM^ope^e%02+0)05+6&)T^kabofkdKM@yyNFAy.-445y

HLsbopbboOfmp^tyKy?^`h^qIbdflkElia+Kb^oqebcbiob^sbo%//+3)03+3&)illqqebXFiifa^of*?^kbPe^oaZyyIy0-423yyNFAy.-3/0y
@PbqqfkdRmqeb?lj_yKy>ojloMi^qfkdfpkb^oqebcbiob^sbo%//+/)02+3&)Mltbo@lobfprkabot^qbo^qqebCbqfaMlli%/3+0)1.+/&+yyNFAy.-264y

QPbqqfkdRmqeb?lj_yKy?illaDr^oaDrijlh%0-+2)0/+2&yyNFAy.-264y
>?i^pqqebFkcbok^ipyKy?illaDr^oaDrijlh%0-+2)0/+2&yyNFAy.-265y
QCo^khiv)FqJ^hbpKlPbkpb+++yKyObpb^o`eboQflorp%0-+-)/5+0&yyNFAy.-34/y
>CbipmfkbqebDob^qboyKyObpb^o`eboQflorp%0-+-)/5+0&yyNFAy.-340y
>Fiifa^of*?^kbPe^oayKyPq^oqpcoljFiifa^of*?^kbPe^oa)aolmmba_vLsbopbboOfmp^tyyRy0-423yyNFAy.-3/0y
QFiifa^of*?^kbPe^oayKyDolhljAb^qebvb%/6+5)0.+0&yyNFAy.-3/0y

@?i^pqqebFkcbok^ipyKy>d^fk^qIbdflkElia+Cfkaqebdobbk`fo`ibkb^oqebfkcbok^io^khp%//+3)06+6&)rpbqeb_lj_+yyRy0-3.1yyNFAy.-265y

Q?i^pqqebFkcbok^ipyKy?illaDr^oaDrijlh%0-+2)0/+2&yyNFAy.-265y
>QebAb^qeclodbyKy?illaDr^oaDrijlh%0-+2)0/+2&yyNFAy.-266y

@QebOlalcIf^kqebyKyHfii?illaBisbp^qB`ifmpbMlfkqqlqebplrqeb^pqcloqebhbv+Pqolkd_lufpb^pqlcqebbifqb%14+2)4.+4&yyNFAy.-445y
@Bko^dbaPmfofqplc>foyKyQ^hbqebol^ab^pqqlqebKbqebotfkdCfbiap%3/+5)3.+3&)aolmqlqbj)hfii^fobibjbkq^ip+Tlohvlrot^vplrqecoljqebcfbiapqlt^oapqeb>iq^olcPe^altp+yyRy0--61yyNFAy.-15.y

QQbolkDlobcfbka*Ilob^kaIbdbkayKy>k`fbkqPe^altjllkPmfofq%25+/)4-+5&yyNFAy.-300y
>Afsfk^qflk7Dlobcfbka$p@il^hyKy>k`fbkqPe^altjllkPmfofq%25+/)4-+5&yyNFAy.-302y
>Afsfk^qflk7Dlobcfbka$pQork`eblkyKy>k`fbkqPe^altjllkPmfofq%25+/)4-+5&yyNFAy.-303y

>Qeb>peqlkdrbQof_byKy>ialolkiv)qf`hqefppqbmfcqefpnrbpqfpklq^s^fi^_ibqlvlr+Sfkaf`^qlo>irrjbk%3.+/)/6+/&yNFAy.-3.6y
>Qeb>peqlkdrb?olhbkyKyP`ovbolkiv)qf`hqefppqbmfcqefpnrbpqfpklq^s^fi^_ibqlvlr+S^obkqebOb`i^fjbo%21+5)25+/&yyNFAy.-5-4y
>Q^_ibqplc?^^$ofyKy>o`^kfpqQebifp%23+0)26+2&LO>k`elofqb@bvi^%3/+3)/5+1&yyNFAy.-350y
>H^o^_loQo^fkfkdDolrkapyKyI^ofpp^Prkpqofhb%22+5)25+/&LOBu^o`eLk^^i^%3.+/)/6+/&yyNFAy.-354y

@CbipmfkbqebDob^qboyKyHfiiCbipmfkbqebDob^qbokloqelcqebT^oabk$p@^db%23+0)1/+.&yyNFAy.-340y
RRpbXPmb`qob`ibpZyRy0-4.6yyNFAy.-302y
KIllhclo++yKyT^q`eqebj^fkol^a^olrkaqebE^kalcDri$a^kcloDelpqofabolcH^o^_lo+Qebvm^qoliqebolrqb`lrkqbo`il`htfpb+FcvlrpbbqebjhfiilkbcloAfsfk^qflk7Dlobcfbka$pQork`eblk+VlrkbbavlroXPmb`qob`ibpZqlpbbqebjyyNFAy.-303yyIy0-5--y
@Afsfk^qflk7Dlobcfbka$p@il^hyKyHfii@ibof`plcH^o^_lo%31+.)11+/&fkcolkqlcqeb?i^`hQbjmibyyNFAy.-302y

@Qeb>peqlkdrbQof_byKy>qqebOrfkplc?^^$of%23+6)02+3&yyNFAy.-3.6yyLy
@Qeb>peqlkdrb?olhbkyKy>qqebOrfkplc?^^$of%23+6)02+3&yyNFAy.-5-4yyLy
@Q^_ibqplc?^^$ofyKy>qqebOrfkplc?^^$of%23+6)02+3&yyNFAy.-350y
@H^o^_loQo^fkfkdDolrkapyKyFkpfabqeb?i^`hQbjmib)q^hbqebcfopqofdeq%35+-)2-+-&+HfiiAbjlkErkqboPrmmif`^kqp^kaFkfqf^qbp)qovql`^q`eqebj^cqbo^arbitebkqebv^obiltlkEM)qebvifkhifhbj^a+>iplt^q`elrqcloqebbifqbqe^qt^kabopqeorqeb^ob^+yyNFAy.-354y

QQeb>peqlkdrbQof_byKySfkaf`^qlo>irrjbk%3.+/)/6+/&)>ialoyyNFAy.-3.6yyLy
QQeb>peqlkdrb?olhbkyKyS^obkqebOb`i^fjbo%21+5)25+/&)P`ovboyyNFAy.-5-4yyLy
>LolkrqebBiaboyKy>o`^kfpqQebifp%23+0)26+2&LO>k`elofqb@bvi^%3/+3)/5+1&yyNFAy.-351y
QQ^_ibqplc?^^$ofyKy>o`^kfpqQebifp%23+0)26+2&LO>k`elofqb@bvi^%3/+3)/5+1&yyNFAy.-350y
QH^o^_loQo^fkfkdDolrkapyKyI^ofpp^Prkpqofhb%22+5)25+/&LOBu^o`eLk^^i^%3.+/)/6+/&yyNFAy.-354y
>>Kb`bpp^ovAfpqo^`qflkyKyI^ofpp^Prkpqofhb%22+5)25+/&LOBu^o`eLk^^i^%3.+/)/6+/&yyNFAy.-355y

QCbipmfkbqebDob^qboyKyObpb^o`eboQflorp%0-+-)/5+0&yyNFAy.-340y
QBko^dbaPmfofqplc>foyKyB^oqejbkaboQloilh%1/+/)12+-&yyNFAy.-15.y
>LolklhQlok*eb^oqyKyB^oqejbkaboQloilh%1/+/)12+-&yyNFAy.-2.0y

QLolklhQlok*eb^oqyKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2.0y
>FT^p>IlqLcQefkdp+++yKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2.1y
@FT^p>IlqLcQefkdp+++yKyCfkaqr_bojlrkap^olrkaqeb^ob^qlqebkloqe%20+2).3+4&)rpbqebtefpqib+Vlre^sbql`ib^oqebci^vbopfkqeb^ob^^kahbbmqebjcolj^qq^`hfkdqeb_l^op+Fq$p_bpqqlgrpqhbbm^pj^ii^ob^`ib^o+yyRy0-13/yyNFAy.-2.1y
QFT^p>IlqLcQefkdp+++yKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2.1y
>>IbpplkIb^okbayKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2.2y
@>IbpplkIb^okbayKyCfkaqebO^sbklrpCi^vboBddp^olrka%24+1).5+5&yyNFAy.-2.2y
Q>IbpplkIb^okbayKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2.2y
>Qeb@fmebolcA^jk^qflk*Qorqe^kaEfpqlovyKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2.6y
@Qeb@fmebolcA^jk^qflk*Qorqe^kaEfpqlovyKyIfpqbkqlLolklhQlok*eb^oq$ppqlovyyNFAy.-2.6y
QQeb@fmebolcA^jk^qflk*Qorqe^kaEfpqlovyKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2.6y
>Dolj$qlo)PlklcLolklhyKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2/.y
>>o$qlo)PlklcLolklhyKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2/4y
>?lo^h)PlklcLolklhyKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-213y

QQebOlalcIf^kqebyKyM^ope^e%02+0)05+6&)T^kabofkdKM@yyNFAy.-445y
>Phbqe$ilkCb^qebopyKyM^ope^e%02+0)05+6&)T^kabofkdKM@yyNFAy.-45-y

QQebAb^qeclodbyKyP`lrqW^do^k%05+2)05+/&yyNFAy.-266y
>JfkflkplcqebPe^alt@lrk`fiyKyP`lrqW^do^k%05+2)05+/&yyNFAy.-3--y
@JfkflkplcqebPe^alt@lrk`fiyKyEb^aaltkfkqlqebAb^qeclodb%06+-)1.+-&yyNFAy.-3--y
QJfkflkplcqebPe^alt@lrk`fiyKyP`lrqW^do^k%05+2)05+/&yyNFAy.-3--y
>QebPrjjlkfkd@e^j_boyKyP`lrqW^do^k%05+2)05+/&yyNFAy.-3-/y
>QebC^qblcH^dolpeyKyP`lrqW^do^k%05+2)05+/&yyNFAy.-3-.y
@QebC^qblcH^dolpeyKyQ^hbqebkloqebkqo^k`b%1-+-)05+-&)cfdeqvlrot^vqlqebab^alo`t^v^qqeb_^`hlcqeb`^sb%02+/)1-+/&yyNFAy.-3-.y
HQfkhbobop^kaPjfqepyKyIllhfkdclo^kBibjbkq^iAfpmi^`boyyIy0-34/y
@QebPrjjlkfkd@e^j_boyKyColjqeb_ofadb)grjmaltkqlqebkloqetbpq%`^obcriiv&)hfiiPrjjlkboPh^oq^u%04+4)05+2&)rpbqebafpmi^`bo)^kahfiiFkcbok^iLsboplri%04+5)05+5&yyRy0-34/yyNFAy.-3-/y
QQebPrjjlkfkd@e^j_boyKyP`lrqW^do^k%05+2)05+/&yyNFAy.-3-/y
QQebC^qblcH^dolpeyKyP`lrqW^do^k%05+2)05+/&yyNFAy.-3-.y
>?ofkdAltkqebT^o_ofkdboyKyP`lrqW^do^k%05+2)05+/&yyNFAy.-3-0y
@?ofkdAltkqebT^o_ofkdboyKyQ^hbqebkloqebkqo^k`b^d^fk%1-+-)05+-&)lsboqeb_ofadb)cfkaqeballolkqebibcqqlhfiiT^o_ofkdboO^wrrk%06+-)13+3&yyNFAy.-3-0y
Q?ofkdAltkqebT^o_ofkdboyKy?illaDr^oaDrijlh%0-+2)0/+2&yyNFAy.-3-0y
>D^fkfkd>``bppyKy?illaDr^oaDrijlh%0-+2)0/+2&yyNFAy.-3-1y

@D^fkfkd>``bppyKyHfiiJl$^odTb^mlkpjfqe^olrka%//+2)00+/&yyNFAy.-3-1y

Q>o$qlo)PlklcLolklhyKy>o$qlo)PlklcLolklh%/6+3)2-+2&yyNFAy.-2/4y
>Abjlkf`@ovpq^iMofplkpyKy>o$qlo)PlklcLolklh%/6+3)2-+2&yyNFAy.-2/5y
@Abjlkf`@ovpq^iMofplkpyKyHfiiM^fkjfpqobppD^_ofpp^%/5+.)14+5&yyNFAy.-2/5y
QAbjlkf`@ovpq^iMofplkpyKy>o$qlo)PlklcLolklh%/6+3)2-+2&yyNFAy.-2/5y
>Ilek$dlolk)?ltlcqebQlok*eb^oqyKyPmfofqlc>o$qlo%/6+3)2-+2&yyNFAy.-204y
@Ilek$dlolk)?ltlcqebQlok*eb^oqyKyHfiiqebFiifa^ofjl_p^olrka%/6+6)16+2&yyNFAy.-204y
QIlek$dlolk)?ltlcqebQlok*eb^oqyKyPmfofqlc>o$qlo%/6+3)2-+2&yyNFAy.-204y
>Qeb@fmebolcA^jk^qflk*>o$qlo$p@e^odbyKyPmfofqlc>o$qlo%/6+3)2-+2&yyNFAy.-21-y
@Qeb@fmebolcA^jk^qflk*>o$qlo$p@e^odbyKyHfiiSbkbo^qrpqebJ^kvclrka^olrka%/6+.)24+/&yyNFAy.-21-y
QQeb@fmebolcA^jk^qflk*>o$qlo$p@e^odbyKyPmfofqlc>o$qlo%/6+3)2-+2&yyNFAy.-21-y
>Qeb@fmebolcA^jk^qflk*QebPb`lkaCo^djbkqOb`lsbobayKyPmfofqlc>o$qlo%/6+3)2-+2&yyNFAy.-21.y

QD^fkfkd>``bppyKy?illaDr^oaDrijlh%0-+2)0/+2&yyNFAy.-3-1y
>Fks^pflkMlfkq7@^q^`ivpjyKy?illaDr^oaDrijlh%0-+2)0/+2&yyNFAy.-434y
QFks^pflkMlfkq7@^q^`ivpjyKyK^h^kpf)Q^hbqebqbibmloqbo%/2+2)03+0&yyNFAy.-434y
>Qeb>oqlcCbiOb^sboJ^fkqbk^k`byKyK^h^kpf%/4+2)/.+/&yyNFAy.-3..y

QDolj$qlo)PlklcLolklhyKyDolj$qlo)PlklcLolklh%11+3)/0+4&yyNFAy.-2/.y
>Qeb@fmebolcA^jk^qflk*Dolj$qlo$p@e^odbyKyDolj$qlo)PlklcLolklh%11+3)/0+4&yyNFAy.-2//y
@Qeb@fmebolcA^jk^qflk*Dolj$qlo$p@e^odbyKyHfiiqeb@lfiph^ojl_p^olrka%12+4)/6+2&yyKyyNFAy.-2//y
QQeb@fmebolcA^jk^qflk*Dolj$qlo$p@e^odbyKyDolj$qlo)PlklcLolklh%11+3)/0+4&yyNFAy.-2//y
>Qeb@fmebolcA^jk^qflk*QebCfopqCo^djbkqOb`lsbobayKyDolj$qlo)PlklcLolklh%11+3)/0+4&yyNFAy.-2/0y

@Qeb>oqlcCbiOb^sboJ^fkqbk^k`byKyRpbhbvlkqebPqolkd_lu%06+2).6+2&yyNFAy.-3..y
QQeb>oqlcCbiOb^sboJ^fkqbk^k`byKyK^h^kpf%/4+2)/.+/&yyNFAy.-3..y
>QebCbi^kaqebCroflrpyKyK^h^kpf%/4+2)/.+/&yyNFAy.-3.0y
@QebCbi^kaqebCroflrpyKyRpb^CbiOb^sbo@lkqoli@lkplibqlq^hb`lkqolilc^CbiOb^sboPbkqfkbi+Abpqolv3-Ab^qeclodbaFkcbok^ip^olrka%//+6)1-+2&yyNFAy.-3.0y
QQebCbi^kaqebCroflrpyKyK^h^kpf%/4+2)/.+/&yyNFAy.-3.0y
>KbtplcSf`qlovyKyK^h^kpf%/4+2)/.+/&yyNFAy.-412y
QKbtplcSf`qlovyKyLsboiloaLo$_^olhe%/5+2)/3+2&)qeolrdeqbibmloqboyyNFAy.-412y

Q?lo^h)PlklcLolklhyKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-213y
>LcQefpqibeb^ap^kaBddp+++yKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-214y
@LcQefpqibeb^ap^kaBddp+++yKyCfkaqebBddp^olrka%11+5)25+/&yyNFAy.-214y

CPe^qqo^qe@fqvyKy>ifbpelo%23+0)24+6&LOJ^aafu%30+0)0-+2&yyNFAy.-22-y
QLcQefpqibeb^ap^kaBddp+++yKyQl_f^pqebCfiqeDlodbo%31+2)26+5&yyNFAy.-214yyWyPe^qqo^qe@fqvy
>Qeb?rkaiblc?illaqefpqibyKyQl_f^pqebCfiqeDlodbo%31+2)26+5&yyNFAy.-22-yyWyPe^qqo^qe@fqvy

EPe^altjllkSfii^dbyRy3615yyNFAy.-24-y
QQeb?rkaiblc?illaqefpqibyKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-22-y
>Ql@^q`e>Qefpqibeb^ayKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-24-y
@Ql@^q`e>Qefpqibeb^ayKyI^vqebX?rkaiblc?illaqefpqibZ^qqebbkalcqeb_ofadb%15)24&+Jlsb^t^v%vlr`^k$q_bqll`ilpb&^kat^fqcloqebbic^kaefpjlrkqba_lavdr^oaql^mmb^o+>cqbo^kbu`e^kdbqeb_lavdr^oatfiis^kfpe^katebkqebbicdlbpcloqeb_illaqefpqib)dbqefjyyRy0-3.3yyNFAy.-24-y
QQl@^q`e>Qefpqibeb^ayKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-24-y
>QebPe^altjllkPerccibyKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-243y
@QebPe^altjllkPerccibyKy@liib`qqeb>ojlocoljB`ifmpflkjl_p^olrka%13+/)35+5&yyNFAy.-243y
QQebPe^altjllkPerccibyKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-243y
>Te^qFiifa^kT^kqp)Fiifa^kDbqp+++yKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-244y
@Te^qFiifa^kT^kqp)Fiifa^kDbqp+++yKyRpbqebAfpdrfpb^kacfkaDo^ka@ljj^kaboOrrph%13+2)4.+5&yyRy0-306yyNFAy.-244y
QTe^qFiifa^kT^kqp)Fiifa^kDbqp+++yKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-244y

@Phbqe$ilkCb^qebopyKyCfkaqebcb^qebopp`^qqboba^olrka%10+4)24+2&yyNFAy.-45-y
QPhbqe$ilkCb^qebopyKyM^ope^e%02+0)05+6&)T^kabofkdKM@yyNFAy.-45-y
>Fj_rfkdqebEb^amfb`byKyM^ope^e%02+0)05+6&)T^kabofkdKM@yyNFAy.-45/y
@Fj_rfkdqebEb^amfb`byKyRpbnrbpqfqbj^q%10+-)11+-&+Bnrfmfq_bclobdbqqfkdqebob+yyNFAy.-45/y
QFj_rfkdqebEb^amfb`byKyM^ope^e%02+0)05+6&)T^kabofkdKM@yyNFAy.-45/y
>Qet^oqqebA^oh@lk`i^sbyKyM^ope^e%02+0)05+6&)T^kabofkdKM@yyNFAy.-5-5y
@Qet^oqqebA^oh@lk`i^sbyKyRpbnrbpqfqbj^q%1.+-)3-+-&^cqbo`ib^ofkdlrq^iiqebbkbjfbp+yyNFAy.-5-5y
QQet^oqqebA^oh@lk`i^sbyKyM^ope^e%02+0)05+6&)T^kabofkdKM@yyNFAy.-5-5y

@>Kb`bpp^ovAfpqo^`qflkyKyHfiiPrjjlkbop^kaT^oil`hp^olrka%4.+.)2.+0&rkqfiqebp`oliiaolmp)qebkrpbfqlk>w^ilqe%4-+-)2.+1&+Alklqhfiiqebjl_pkb^oefj)loeb$ii`ljb^cqbovlr+yyRy0-5..yyNFAy.-355y

@LolkrqebBiaboyKyVlr`^kcfkaLolkrqebBiabo^q%24+/)00+.&fkpfabqeborfkpyyNFAy.-351y
QLolkrqebBiaboyKy>o`^kfpqQebifp%23+0)26+2&LO>k`elofqb@bvi^%3/+3)/5+1&yyNFAy.-351y
>Qeb>peqlkdrb@loormqlopyKy>o`^kfpqQebifp%23+0)26+2&LO>k`elofqb@bvi^%3/+3)/5+1&yyNFAy.-352y
@Qeb>peqlkdrb@loormqlopyKyHfiiE^^irj%24+-)40+-&)Bvhbkbk%2.+-)2/+-&)Rvi^or%15+-)06+-&^kaI^h^^k%16+-)/0+-&yyNFAy.-352y
QQeb>peqlkdrb@loormqlopyKy>o`^kfpqQebifp%23+0)26+2&LO>k`elofqb@bvi^%3/+3)/5+1&yyNFAy.-352y
>QebT^oabk$p@^dbyKy>o`^kfpqQebifp%23+0)26+2&LO>k`elofqb@bvi^%3/+3)/5+1&yyNFAy.-353y
QQebT^oabk$p@^dbyKyP^klor%24+0)16+3&)fkqebelibyyNFAy.-353y
>Mollclc>iibdf^k`byKyP^klor%24+0)16+3&yyNFAy.-3//y
@Mollclc>iibdf^k`byKyMriiW^kao^p%25+-)16+3&altk^kahfiiefjyyNFAy.-3//y
QMollclc>iibdf^k`byKyP^klor%24+0)16+3&yyNFAy.-3//y
>>h^j^yKyP^klor%24+0)16+3&yyNFAy.-3/5y
Q>h^j^yKy>h^j^%25+.)15+0&)altkfkqebt^qboyyNFAy.-3/5y

@>Dorkq$pTloh+++yKyFc`ob^qrobp^obpqfiikbbaba`lkqfkrbqlhfii^olrka%01+-)06+3&yyNFAy.-4-/y
@Afsfk^qflk7Dlobcfbka$pQork`eblkyKyObjbj_boqltb^oqebXPmb`qob`ibpZ+HfiiDelpqofaboplcH^o^_lo`fo`ifkdQebE^kalcDri$a^kqldbqXDlobcfbka$pQork`eblkZ+?bpqqldl`il`htfpb^ilkdqebj^glool^a)^pqebvqo^sbi`lrkqbo`il`htfpb%02+1)01+5&)%01+0)14+3&)%14)24+1&)%3/+5)2/+2&)%3/+4)0/+3&)%13+0)/1+/&yyNFAy.-303yyRy0-4.6y

Q>Dorkq$pTloh+++yKyLsboiloaLo$_^olhe%/5+2)/3+2&yyNFAy.-4-/y
QQeb@fmebolcA^jk^qflk*QebCfopqCo^djbkqOb`lsbobayKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2/0y
QQeb@fmebolcA^jk^qflk*QebPb`lkaCo^djbkqOb`lsbobayKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-21.y
Q>Kb`bpp^ovAfpqo^`qflkyKyI^ofpp^Prkpqofhb%22+5)25+/&LOBu^o`eLk^^i^%3.+/)/6+/&yyNFAy.-355y
QAfsfk^qflk7Dlobcfbka$pQork`eblkyKy>k`fbkqPe^altjllkPmfofq%25+/)4-+5&yyNFAy.-303y
QAfsfk^qflk7Dlobcfbka$p@il^hyKy>k`fbkqPe^altjllkPmfofq%25+/)4-+5&yyNFAy.-302y
]]
end)
