DugisGuideViewer:RegisterGuide("Howling Fjord (68-71)", "Borean Tundra (71-73)", "Horde", "L", function()
return [[
AAA

KFcVlr?bdfk>qIbsbi35+++yKy?lqe?lob^kQrkao^^kaEltifkdCgloa`lkq^fkpibsbi35nrbpqpfcvlr_bdfk^ppllk^pvlrefq35vlrjfdeqklq_b^_ibqlob^`eibsbi4-qlmf`hrmkbtnrbpq)fcqefpe^mmbkpPhfmql?lob^kQrkao^Drfab^ka`ljmibqbfqqebkobqrok_^`hqlEltifkdCgloayyNFAy...34y
CEltifkdCgloayKyDlqlQfofpc^iDi^ab^kaq^hbqebWbmmbifkqlSbkdb^k`bI^kafkdfkEltifkdCgloa%26+/)26&yyWyQfofpc^iDi^abpyyNFAy...34y

cSbkdb^k`bI^kafkdyKy?^qE^kaibo>abifkb%46+-)/6+4&yyNFAy...34y
eSbkdb^k`bI^kafkdyKyQfjlqevElii^ka%46+4)0-+5&yyNFAy...34y

>QebKbtMi^drbyKy>mlqeb`^ovIvp^kabo%45+3)/6+.&yyNFAy...34y
>IbqQebjB^q@oltyKyMlkqfrp%46+.)0.+/&yyNFAy..//4y
>T^ofpEbiiyKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyNFAy../4-y

@T^ofpEbiiyKyRpbqebX?rokfkdQlo`eZlkqeb^iif^k`b^karkclop^hbk`lompbp^olrka%42+0)0-+5&yyNFAy../4-yyRy00/45y
@IbqQebjB^q@oltyKyHfiiqebCgloa@oltp^olrka%41+4)0/+6&)`liib`qqebjb^q^kacbbaqebjb^qqlqebErkdovMi^drbelrka_vprjjlkfkdfqtfqeqebXMi^drbelrka@^dbZyyNFAy..//4yyRy..//4y

QIbqQebjB^q@oltyKyMlkqfrp%46+.)0.+/&yyNFAy..//4y
>PkfccLrqqebBkbjvyKyMlkqfrp%46+.)0.+/&yyNFAy../20y
QT^ofpEbiiyKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyNFAy../4-y
>ObmloqpcoljqebCfbiayKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyNFAy..//.y

QPkfccLrqqebBkbjvyKyAo^dlkphfkP`olii%43+-).6+5&yyNFAy../20yyRy00153y
>QebAo^dlkphfkJ^myKyAo^dlkphfkP`olii%43+-).6+5&yyNFAy../21y

QQebAo^dlkphfkJ^myKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyNFAy../21y
>QebLccbkpfsb?bdfkpyKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyNFAy../62y

@QebKbtMi^drbyKyClrka^olrkaqebpefmtob`h^q%5-+6)02+-&yyNFAy...34y

@ObmloqpcoljqebCfbiayKyQ^ihqlA^ohO^kdboIv^k^%45)404+.&qebkAb^qepq^ihboO^w^bi%44+3)01+4&yyNFAy..//.y

QObmloqpcoljqebCfbiayKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyNFAy..//.y
>QebTfkaorkkboCibbqyKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyNFAy..//6y
QQebKbtMi^drbyKy>mlqeb`^ovIvp^kabo%45+3)/6+.&yyNFAy...34y
>PmfhfkdqebJfuyKy>mlqeb`^ovIvp^kabo%45+3)/6+.&yyNFAy...35y

@PmfhfkdqebJfuyKyHfiiqebDf^kqQfab`o^tibop^olrka%43+1).6+4&^ka`liib`q0XDf^kqQlufkDi^kapZyyNFAy...35y

QPmfhfkdqebJfuyKy>mlqeb`^ovIvp^kabo%45+3)/6+.&yyNFAy...35y
>Qbpq^qPb^yKy>mlqeb`^ovIvp^kabo%45+3)/6+.&yyNFAy...4-y
@Qbpq^qPb^yKyQ^ihql?^qE^kaibo@^jfiib%46+-)/6+5&^kaq^hb^_^qqlfkqbo`bmqqebobfkclo`bjbkqp+RpbqebXMi^drbSf^ipZqlaolmqebfkcb`qba_lj_plkqebobfkclo`bjbkqpfkqebcolwbkpb^yyNFAy...4-yyRy00016y
QQbpq^qPb^yKy>mlqeb`^ovIvp^kabo%45+3)/6+.&yyNFAy...4-y
>Kbt>d^j^kayKy>mlqeb`^ovIvp^kabo%45+3)/6+.&yyNFAy..0-1y
QQebTfkaorkkboCibbqyKy@^mq^fkE^ohbo%51+3)03+1&+Pmb^hql?^qE^kaibo@^jfiibclo^ofabyyNFAy..//6y
>>j_rpebayKy@^mq^fkE^ohbo%51+3)03+1&yyNFAy../0-y
@>j_rpebayKyHfii.2KloqeCibbqJ^ofkbplkqeb_l^qp^olrka%51+-)03+5&yyNFAy../0-y
Q>j_rpebayKy@^mq^fkE^ohbo%51+3)03+1&yyNFAy../0-y
>DrfabLroPfdeqpyKy@^mq^fkE^ohbo%51+3)03+1&yyNFAy../0/y

@DrfabLroPfdeqpyKyRpbqebX@^kklkbbo$pPjlhbCi^obZqlj^ohqebTbpq`^kklk^q%46+-)1-+.&^kaqebB^pq`^kklk^q%5-+/)05+/&yyNFAy../0/yyRy00002y

QDrfabLroPfdeqpyKyA^ohO^kdboIv^k^%45)404+.&yyNFAy../0/y
>I^kafkdqebHfiifkd?iltyKyA^ohO^kdboIv^k^%45)404+.&yyNFAy../00y

@I^kafkdqebHfiifkd?iltyKyHfii@^mq^fkLipqbo%5.+2)10+0&)Ifbrqbk^kq@bibvkb%50+/)10+/&^kaPbodb^kqIloof`%5/+-)1.+.&yyNFAy../00y

>Qo^filcCfobyKy>mlqeb`^ovE^kbp%50+/)10+.&yyNFAy../1.y
@Qo^filcCfobyKyBp`loq>mlqeb`^ovE^kbpqlp^cbqv)qefpfpmobqqvb^pv^kaebalbpab`bkqa^j^dbyyNFAy../1.y

QI^kafkdqebHfiifkd?iltyKyA^ohO^kdboIv^k^%45)404+.&yyNFAy../00y
>Obmloqql>kpbijyKyA^ohO^kdboIv^k^%45)404+.&yyNFAy../01y

QObmloqql>kpbijyKyEfdeBub`rqlo>kpbij%45+3)0.+/&yyNFAy../01y
QQo^filcCfobyKy>mlqeb`^ovIvp^kabo%45+3)/6+.&yyNFAy../1.y

QQebLccbkpfsb?bdfkpyKyPbodb^kqDloqe%4.+.)06+.&yyNFAy../62y
>>IbpplkfkCb^oyKyPbodb^kqDloqe%4.+.)06+.&yyNFAy../5/y
>Ebimclo@^jmTfkqboellcyKyIlkdorkkboK^kfh%4.+1)06+/&yyNFAy./233y
@>IbpplkfkCb^oyKyMi^`bqebXClop^hbk?^kkboZ^qqeb`bkqbolcqltkfk?^ibebfj%36)06&)qfiiqeb0sovhri`ljb^ka^qq^`hyyNFAy../5/yyRy00230y
Q>IbpplkfkCb^oyKyPbodb^kqDloqe%4.+.)06+.&yyNFAy../5/y
>?^ibebfj?lav`lrkqyKyPbodb^kqDloqe%4.+.)06+.&yyNFAy../50y
>?^ibebfjJrpq?rokyKyPbodb^kqDloqe%4.+.)06+.&yyNFAy../52y

@?^ibebfjJrpq?rokyKyRpbXDloqe$pQlo`eZql_rokqebQltbo%34+0)06+/&)?ofadb%33+.)1-+-&)?^oo^`hp%30+4)1-+4&^kaAtbiifkd%31+5)1-+4&fk?^ibebfjyyNFAy../52yyRy0014/y
@?^ibebfj?lav`lrkqyKyHfiiTfkqbophlokjl_pfk?^ibebfj^olrka%30+6)1-+.&yyNFAy../50y

Q?^ibebfj?lav`lrkqyKyPbodb^kqDloqe%4.+.)06+.&yyNFAy../50y
Q?^ibebfjJrpq?rokyKyPbodb^kqDloqe%4.+.)06+.&yyNFAy../52y
>Qeb>j_rpeyKyPbodb^kqDloqe%4.+.)06+.&yyNFAy..0-0y

QQeb>j_rpeyKyIvabii%32+6)03+4&yyNFAy..0-0y
>>aafkdFkgrovqlFkpriqyKyIvabii%32+6)03+4&yyNFAy./15.y

@>aafkdFkgrovqlFkpriqyKyRpbqebXSovhriFkpriqZlk?glokE^idroapplk%31+.)06+1&)qebkorkofdeq_^`hqlqebnrbpqdfsboteltfiiebimhfiiefjyyNFAy./15.yyRy0025.y
Q>aafkdFkgrovqlFkpriqyKyIvabii%32+6)03+4&yyNFAy./15.y

c@^jmTfkqboellcyKy@bib^Colwbkj^kb%16+2)..+3&yyNFAy../42y
e@^jmTfkqboellcyKy?lofTfkqboqlqbj%16+2).-+5&yyNFAy../42y

>J^hfkdqebElokyKyKlhlj^Pkltpbbo%16+0)..+6&yyNFAy../42y
>PrmmobppfkdqebBibjbkqpyKyTfkaQ^jboH^d^k%16+-)./+-&yyNFAy..0..y
>E^pqvMobm^o^qflkpyKy>elq^Tefqbcolpq%15+1)..+-&yyNFAy../4.y
QEbimclo@^jmTfkqboellcyKy@efbcq^fk>peqlqbj%15+.).-+5&yyNFAy./233y

@J^hfkdqebElokyKyHfiiqebColpqelokO^jp^olrka%22+-).0+-&^ka`liib`q3XRka^j^dbaO^jElokpZyyNFAy../42y
@E^pqvMobm^o^qflkpyKy@liib`qqebcb^qebop^olrka%22+-).0+-&yyNFAy../4.y

@PrmmobppfkdqebBibjbkqpyKyHfiiqebOl`hBibjbkq^ipclrkapq^oqfkdcolj%25+0).0+.&yyNFAy..0..y

QE^pqvMobm^o^qflkpyKy>elq^Tefqbcolpq%15+1)..+-&yyNFAy../4.y
>J^o`elcqebDf^kqpyKyP^dbBa^k%15+.).-+2&yyNFAy..032y
>HbbmfkdT^q`elkqebFkqboilmbopyKyGrk^qqebT^kabobo%15+2).-+2&yyNFAy../64y
QJ^hfkdqebElokyKyKlhlj^Pkltpbbo%16+0)..+6&yyNFAy../42y
>Jfjf`hfkdK^qrob$p@^iiyKyKlhlj^Pkltpbbo%16+0)..+6&yyNFAy../5.y
>QebColwbkDi^abyKyKlhlj^Pkltpbbo%16+0)..+6&yyNFAy..0./y
QPrmmobppfkdqebBibjbkqpyKyTfkaQ^jboH^d^k%16+-)./+-&yyNFAy..0..y
>Qeb?llhlcOrkbpyKyIlkdorkkboMbj_b%16+/)./+/&yyNFAy..02-y

@Jfjf`hfkdK^qrob$p@^iiyKyRpbqebX@^osbaElokZ^qqebcolwbkt^qboc^ii%2/+.)0+-&qebkhfiiColpqdlobyyNFAy../5.yyRy0012-y

QQebColwbkDi^abyKyIrofbiib%3.+2)//+5&yyNFAy..0./y
>PmfofqplcqebF`byKyIrofbiib%3.+2)//+5&yyNFAy..0.0y
@PmfofqplcqebF`byKy>ii^olrkaqebColwbkDi^ab%3.+2)//+5&yyNFAy..0.0y
QPmfofqplcqebF`byKyIrofbiib%3.+2)//+5&yyNFAy..0.0y
>QebC^iibkPfpqbopyKyIrofbiib%3.+2)//+5&yyNFAy..0.1y
>TfiaSfkbpyKyIrofbiib%3.+2)//+5&yyNFAy..0.2y

@QebC^iibkPfpqbopyKyIl`^qbafkQebSf_o^kqDi^ab^q%2.+5)/5+6&+>qq^`h@efiiKvjmeprkqfitb^h)qebkrpbXIrofbiib$pMbka^kqZlkqebj+?bprobqlt^q`eAlQa^j^dbyyNFAy..0.1yyRy003-3y
@TfiaSfkbpyKyHfii5P`^oibqFsvclrkafkQebSf_o^kqDi^ab^q%2.+5)/5+6&yyNFAy..0.2y

QQebC^iibkPfpqbopyKyIrofbiib%3.+2)//+5&yyNFAy..0.1y
QTfiaSfkbpyKyIrofbiib%3.+2)//+5&yyNFAy..0.2y
>Pm^tklcqebQtfpqbaDi^abyKyIrofbiib%3.+2)//+5&yyNFAy..0.3y
>Pbbaplcqeb?i^`hplribaHbbmbopyKyIrofbiib%3.+2)//+5&yyNFAy..0.6y

@?llhlcOrkbpyKyHfiiFolkOrkbPqlkb`^iibop,?fkabopqlqebb^pq^qDf^kqp$Ork%4/+-)/1+-&clo`e^mqbop)qebk`lj_fkbqebjql`ob^qbXQeb?llhlcOrkbpZyyNFAy..02-yyRy00445y

E@^jmTfkqboellcyKy?lofTfkqboqlqbj%16+2).-+5&yyNFAy..02.y
QJfjf`hfkdK^qrob$p@^iiyKyKlhlj^Pkltpbbo%16+0)..+6&yyNFAy../5.y
QQeb?llhlcOrkbpyKyIlkdorkkboMbj_b%16+/)./+/&yyNFAy..02-y
>J^pqbofkdqebOrkbpyKyIlkdorkkboMbj_b%16+/)./+/&yyNFAy..02.y
>PhlokJrpqC^iiyKy@efbcq^fk>peqlqbj%15+.).-+5&yyNFAy../23y

@Pm^tklcqebQtfpqbaDi^abyKyClrkaKloqetbpq^qqebQtfpqbaDi^ab%21+/).3+4&yyNFAy..0.3y
@Pbbaplcqeb?i^`hplribaHbbmbopyKyKloqetbpq^qqebQtfpqbaDi^ab%21+/).3+4&+HfiiqebPmlobp)qebkrpbqebXBk`e^kqbaF`b@lobZlkqebjyyNFAy..0.6yyRy003-4y

QPhlokJrpqC^iiyKyPrjjlkTfkqboellc?o^sbtfqeqebXTfkqboellcBj_ibjZ+Vlrjrpq_bfkPhlok%11+0)/3+2&yyNFAy../23yyRy0001-y
>Dorbpljb)?rqKb`bpp^ovyKyTfkqboellc?o^sbyyNFAy../24yyRy0001-y
>?rokPhlok)?rokyKyTfkqboellc?o^sbyyNFAy../25yyRy0001-y
>Qltboplc@boq^fkAlljyKyTfkqboellc?o^sbyyNFAy../26yyRy0001-y
@Dorbpljb)?rqKb`bpp^ovyKyHfiisovhri^olrkaPhlok%11+0)/3+2&^karpbXQebPbodb^kq$pJ^`ebqbZlkb^`elkbyyNFAy../24yyRy000.-y
>Pqlmqeb>p`bkpflkyKyQebfqbjXSovhriP`oliilc>p`bkpflkZpq^oqpnrbpq*aolmplccjl_pfkPhlokyyNFAy../3-yyRy000.1y
@Qltboplc@boq^fkAlljyKyRpbX?o^sb$pCi^obZlkqebKloqetbpqQltbo%11+4)0-+-&)B^pqQltbo%12+5)0/+.&)PlrqetbpqQltbo%10+4)01+1&^kaPlrqeb^pq%13+0)03+0&yyNFAy../26yyRy000/0y
@?rokPhlok)?rokyKyRpbX?o^sb$pQlo`eZql_rokqebKloqeb^pqIlkdelrpb%13+2)/5+.&)?^oo^`hp%12+6)0-+4&^kaKloqetbpqIlkdelrpb%10+4)/5+4&yyNFAy../25yyRy000/.y
@Pqlmqeb>p`bkpflkyKyRpbqebXSovhriP`oliilc>p`bkpflkZ^qQe^kb$pMvob%11+3)02+0&+HfiiE^ica^kqebF`b*Eb^oqbayyNFAy../3-yyRy00006y
QDorbpljb)?rqKb`bpp^ovyKyPrjjlkTfkqboellc?o^sbtfqeqebXTfkqboellcBj_ibjZ+Vlrjrpq_bfkPhlok%11+0)/3+2&yyNFAy../24yyRy0001-y
Q?rokPhlok)?rokyKyTfkqboellc?o^sbyyNFAy../25yyRy0001-y
QQltboplc@boq^fkAlljyKyTfkqboellc?o^sbyyNFAy../26yyRy0001-y
>Qeb@lknrbololcPhlokyKyTfkqboellc?o^sbyyNFAy../3.yyRy0001-y

QPm^tklcqebQtfpqbaDi^abyKyIrofbiib%3.+2)//+5&yyNFAy..0.3y
QPbbaplcqeb?i^`hplribaHbbmbopyKyIrofbiib%3.+2)//+5&yyNFAy..0.6y
>HbbmboTfqeboib^cyKyIrofbiib%3.+2)//+5&yyNFAy..1/5y

@J^pqbofkdqebOrkbpyKyCfkaqebXFolkOrkb@^osfkdQllipZfkqebqbkqp^olrkaDf^kqp$Ork^q^kvlcqebcliiltfkdil`^qflkp%36+.)//+5&%34+2)/0+1&%34+2)/6+/&%4.+/)/5+4&%40+1)/2+-&%4/+1).4+5&yyNFAy..02.y

E@^jmTfkqboellcyKy?lofTfkqboqlqbj%16+2).-+5&yyNFAy..02/y
QJ^pqbofkdqebOrkbpyKyIlkdorkkboMbj_b%16+/)./+/&yyNFAy..02.y
>QebOrkblc@ljj^kayKyIlkdorkkboMbj_b%16+/)./+/&yyNFAy..02/y
QPqlmqeb>p`bkpflkyKyDob^qjlqebo>khe^%15+.).-+4&yyNFAy../3-y
QQeb@lknrbololcPhlokyKy@efbcq^fk>peqlqbj%15+.).-+5&yyNFAy../3.y
>Ab^ifkdTfqeDg^ibo_olkyKy@efbcq^fk>peqlqbj%15+.).-+5&yyNFAy../30y
>CfkaP^dbJfpqt^ihboyKyDob^qjlqebo>khe^%15+.).-+4&yyNFAy../54y
>LcHbvp^ka@^dbpyKyDob^qjlqebo>khe^%15+.).-+4&yyNFAy../32y

@HbbmboTfqeboib^cyKyClrka^qQebQtfpqbaDi^ab^olrka%21+-).5+6&yyNFAy..1/5y

QHbbmboTfqeboib^cyKyIrofbiib%3.+2)//+5&yyNFAy..1/5y

@QebOrkblc@ljj^kayKyRpbqebXOrkblc@ljj^kaZlk^kloj^idf^kqkb^o?fkaboJroafp%4.+5)/1+0&qebkhfiiefjyyNFAy..02/yyRy00463y
QQebOrkblc@ljj^kayKyIlkdorkkboMbj_b%16+/)./+/&yyNFAy..02/y

>Ofsbktlla@^mqfsbpyKyIlkdorkkboPhv`ilra%0.+0)/1+1&yyNFAy../63y
QCfkaP^dbJfpqt^ihboyKyP^dbJfpqt^ihbo%0.+/)/1+2&yyNFAy../54y
>Qeb>oqfc^`qplcPqbbiD^qbyKyP^dbJfpqt^ihbo%0.+/)/1+2&yyNFAy../53y

@Qeb>oqfc^`qplcPqbbiD^qbyKyCliiltqebo^jmaltkfkqlqebjfkfkd^ob^plrqe^q%0.+1)/3+.&+@liib`qqebXPqbbiD^qb>oqfc^`qpZebobyyNFAy../53y

QQeb>oqfc^`qplcPqbbiD^qbyKyP^dbJfpqt^ihbo%0.+/)/1+2&yyNFAy../53y
>Qeb@ib^kpfkdyKyP^dbJfpqt^ihbo%0.+/)/1+2&yyNFAy..0.4y

@Ofsbktlla@^mqfsbpyKy>qq^`hqebOfsbkTfalt@l`llkp^olrkaOfsbktlla%01+-).6+2&rkqfivlre^sbcobba4TfkqboellcIlkdorkkbopyyNFAy../63y

@Ab^ifkdTfqeDg^ibo_olkyKyHfiiSovhriqlqebkloqe^qDg^ibo_olk%02+-).5&yyNFAy../30y
@LcHbvp^ka@^dbpyKyHfiiSovhriqlqebkloqe^qDg^ibo_olk%02+-)./+/&qlillqqebhbvpvlrkbbaqllmbk`^dbp+FcvlrdbqqebXI^odbDg^ibo_olk@^dbHbvZ)rpb^qqeb`^db^q%02+5)..+2&yyNFAy../32y
>Dg^ibo_olk>qq^`hMi^kpyKyRpbqebXDg^ibo_olk>qq^`hMi^kpZ+Fcvlrafak$qdbqqebj)hbbmhfiifkdSovhriyyNFAy../33yyRy00/56y

QHbbmfkdT^q`elkqebFkqboilmbopyKy>mlqeb`^ovJ^iqerp%/3+1)/1+2&yyNFAy../64y
>Te^q$pfkQe^q?obt<yKy>mlqeb`^ovJ^iqerp%/3+1)/1+2&yyNFAy../65y
>?o^fkp?o^fkp?o^fkpyKy>mlqeb`^ovDof`h%/3+-)/1+2&yyNFAy..0-.y
>>kaVlrQelrdeqJroil`pPjbiiba?^ayKy>mlqeb`^ov>k^pq^pf^%/3+.)/1+3&yyNFAy..064y

c>mlqeb`^ov@^jmyKyIfiibqeO^abp`r%/3+-)/2+-&yyNFAy..065y

@>kaVlrQelrdeqJroil`pPjbiiba?^ayKyHfiiP`lrodblkqeb`l^pq^olrka%/.+5)//+2&yyNFAy..064y
>Fq$p^P`lrodbAbsf`byKyQebfqbjXP`lrodbAbsf`bZpq^oqpnrbpq*Fcvlrafak$qdbqfq)hbbmhfiifkdP`lrodbyyNFAy..065yyRy0063/y

@?o^fkp?o^fkp?o^fkpyKyBkqo^k`bqlTefpmboDri`efp^q%00+.)01+-&afob`qivkloqeb^pq^ka^`olppqeb_ofadbcoljTbpqdr^oaHbbm)hfiibumilobopqebkrpbXDof`h$p?lkbp^tZyyNFAy..0-.yyRy00221y
@Te^q$pfkQe^q?obt<yKy@liib`q2XAt^osbkHbdpZfkTefpmboDri`e%00+.)01+-&yyNFAy../65y

QTe^q$pfkQe^q?obt<yKy>mlqeb`^ovJ^iqerp%/3+1)/1+2&yyNFAy../65y
Q?o^fkp?o^fkp?o^fkpyKy>mlqeb`^ovDof`h%/3+-)/1+2&yyNFAy..0-.y
Q>kaVlrQelrdeqJroil`pPjbiiba?^ayKy>mlqeb`^ov>k^pq^pf^%/3+.)/1+3&yyNFAy..064y
QFq$p^P`lrodbAbsf`byKy>mlqeb`^ov>k^pq^pf^%/3+.)/1+3&yyNFAy..065y
>?ofkdAltkQelpbPefbiapyKy>mlqeb`^ov>k^pq^pf^%/3+.)/1+3&yyNFAy..066y

C@^jmTfkqboellcyKyIfiibqeO^abp`r%/3+-)/2+-&yyNFAy../34y
QDg^ibo_olk>qq^`hMi^kpyKy@bib^Colwbkj^kb%16+2)..+3&yyNFAy../33y
>QebColpqTvoj^kafqpJ^pqboyKy@bib^Colwbkj^kb%16+2)..+3&yyNFAy../34y
QAb^ifkdTfqeDg^ibo_olkyKy@efbcq^fk>peqlqbj%15+.).-+5&yyNFAy../30y
>Kb`olLsboiloaJbwebkyKy@efbcq^fk>peqlqbj%15+.).-+5&yyNFAy../31y
QLcHbvp^ka@^dbpyKyDob^qjlqebo>khe^%15+.).-+4&yyNFAy../32y
>QebT^ihfkdAb^ayKyDob^qjlqebo>khe^%15+.).-+4&yyNFAy../35y
>PibbmfkdDf^kqpyKy>elq^Tefqbcolpq%15+1)..+-&yyNFAy..100y

@Qeb@ib^kpfkdyKyEb^armqebjlrkq^fkm^qe%20+3)5+-&qlqebpeofkb%3.+0).+3&+Rpbqebpeofkbqebkhfiiqebbsfivlr^kaqebkpiltc^iialtkqlqebColwbkDi^abyyNFAy..0.4y

C>mlqeb`^ov@^jmyKy@bib^Colwbkj^kb%16+2)..+3&yyNFAy..0/0y

QOfsbktlla@^mqfsbpyKyIlkdorkkboPhv`ilra%0.+0)/1+1&yyNFAy../63y
QQeb@ib^kpfkdyKyP^dbJfpqt^ihbo%0.+/)/1+2&yyNFAy..0.4y
>FkTlod$p@ilqefkdyKyP^dbJfpqt^ihbo%0.+/)/1+2&yyNFAy..0/0y

HMrqofaTfdeqyKyOrkpqo^fdeqkloqe_^`hfkqlDg^ibo_olk^kahfiiqebAb^qeibppT^q`ebop^kaMrqofaTfdeqplkqebmi^qclojp%03+.)4+/&^ka%05+-).0+1&yyNLyMrqofaTfdeq72,2yyNFAy../35y
@Kb`olLsboiloaJbwebkyKyEb^armqlqebpb`lkaibsbi)qebkrmqlqebmi^qclojqlqebb^pq%05+3).0+.&yyNFAy../31y
>QebPirj_bofkdHfkdyKyQebfqbjXJbwebk$pTofqfkdpZpq^oqpnrbpq*aolmmba_vKb`olLsboiloaJbwebk%05+3).0+.&yyNFAy..120yyRy01-6.y

@QebPirj_bofkdHfkdyKyHfiiNrbbk>kdbo_la^^qqebc^obkalcDg^ibo_olk%1.+-)3+0&yyNFAy..120y

@QebQebColpqTvoj^kafqpJ^pqboyKyHfiiTvoj`^iiboSfib%03+2)4+0&)qebkillqqebXTvoj`^iibo$pElokZ^karpbfq+HfiiDi^`flk+Tvoj`^iiboSfibe^p^peloqobpm^tkqfjb+Qefpfp^dolrmnrbpq)_rqb^pfivplil^_ibyyNFAy../34yyRy00/5/y

@QebT^ihfkdAb^ayKyHfiiqebCb^opljbEloolopaltkfkqebT^hfkdE^iip_bkb^qeDg^ibo_olk%01+-).0+-&yyNFAy../35y
@PibbmfkdDf^kqpyKyAltkfkqebT^hfkdE^iip_bkb^qeDg^ibo_olk%01+-).0+-&+HfiiKb`oliloapclo^kX>t^hbkfkdOlaZ)rpbfqlkqebAloj^kqSovhrifkqeb`e^j_bopyyNFAy..100yyRy01-50y

QFkTlod$p@ilqefkdyKyRic^kd%/6+4)2+4&yyNFAy..0/0yyRy003.5y
>?olqebo?bqo^vbopyKyRic^kd%/6+4)2+4&yyNFAy..1.2yyRy003.5y

@?ofkdAltkQelpbPefbiapyKyRpbqebXP`lrodfkd@ovpq^i@lkqoliiboZql_ofkdaltkqebpefbiap)qebk_ob^hqebP`lrodfkd@ovpq^iplkqeb`l^pq^olrka%/.+5)//+2&yyNFAy..066yyRy0063-y

Q?ofkdAltkQelpbPefbiapyKy>mlqeb`^ov>k^pq^pf^%/3+.)/1+3&yyNFAy..066y

@?olqebo?bqo^vbopyKyHfii?gljlicqlqebplrqetbpq^olrkaqeb>mlqeb`^ov@^jm%/6+.)/.+4&+S^odfpplrqeb^pqlcPqbbiD^qb%02+1)0.+/&+FcvlrrpbqebXTlodAfpdrfpbZvlr$iie^sb^kb^pfboqfjbpmlqqfkdqebjyyNFAy..1.2yyRy003.5y

Q?olqebo?bqo^vbopyKyRic^kd%/6+4)2+4&yyNFAy..1.2yyRy003.5y
>BvbplcqebB^dibyKyRic^kd%/6+4)2+4&yyNFAy..1.4yyRy003.5y

@BvbplcqebB^dibyKyPlrqetbpqlcPhlok^qqeb_^pblcqeb_fdt^qboc^ii%1.+1)04+3&+Do^_qebbdd)qebkhfiiqebb^dibyyNFAy..1.4y

QBvbplcqebB^dibyKyRic^kd%/6+4)2+4&yyNFAy..1.4yyRy003.5y
>>ime^TlodyKyRic^kd%/6+4)2+4&yyNFAy..0/1yyRy003.5y

@>ime^TlodyKyPm^tkpgrpqplrqelcqeb`^sb%/4+1)5+/&yyNFAy..0/1y

E@^jmTfkqboellcyKy?lofTfkqboqlqbj%16+2).-+5&yyNFAy../46y
QQebColpqTvoj^kafqpJ^pqboyKy@bib^Colwbkj^kb%16+2)..+3&yyNFAy../34y
QKb`olLsboiloaJbwebkyKy@efbcq^fk>peqlqbj%15+.).-+5&yyNFAy../31y
QQebPirj_bofkdHfkdyKy@efbcq^fk>peqlqbj%15+.).-+5&yyNFAy..120y
QQebT^ihfkdAb^ayKyDob^qjlqebo>khe^%15+.).-+4&yyNFAy../35y
QPibbmfkdDf^kqpyKy>elq^Tefqbcolpq%15+1)..+-&yyNFAy..100y

C>mlqeb`^ov@^jmyKy@bib^Colwbkj^kb%16+2)..+3&yyNFAy../46y

Q>ime^TlodyKyP^dbJfpqt^ihbo%0.+/)/1+2&yyNFAy..0/1y

>DobbkBddp^kaTebimpyKyMi^drb_ofkdboQfiifkde^pq%20+.)33+6&yyNFAy../46y
QKbt>d^j^kayKy@efbcMi^drb_ofkdboE^oofp%20+3)33+1&yyNFAy..0-1y
>>Q^filo*J^abClojri^yKy@efbcMi^drb_ofkdboE^oofp%20+3)33+1&yyNFAy..0-2y
>PefbiaEfiiyKyE^`hp^tGbkkv%20+4)32+0&yyNFAy..1/1y

cKbt>d^j^kayKyQl_f^pP^ohelcc%2/+-)34+2&yyNFAy..0-3y
eKbt>d^j^kayKy?^pfiLpdlla%2/+/)33+2&yyNFAy..0-3y

@>Q^filo*J^abClojri^yKyHfiiQelos^ia^q%13+5)34+6&^kadbqqebXAo^dlkci^vboM^qof^o`e$p?illaZyyNFAy..0-2y

@PefbiaEfiiyKyHfiiqebOfpbkSvhori>k`bpqlop^olrka%25+6)43+2&^ka`liib`q2X>k`fbkqSvhori?lkbpZyyNFAy..1/1y

Q>Q^filo*J^abClojri^yKy@efbcMi^drb_ofkdboE^oofp%20+3)33+1&yyNFAy..0-2y
>>mmivEb^q^kaPqfoyKy@efbcMi^drb_ofkdboE^oofp%20+3)33+1&yyNFAy..0-3y
@>mmivEb^q^kaPqfoyKyRpbqebXBjmqv>mlqeb`^ovCi^phZ^qqeb`^riaolkofdeqkbuqqlE^oofpqlcfiifq)qebkjfuqebcfiibaci^ph^qqebq^_iblkefplqebopfab+Hbbmalfkdqefprkqfivlrdbq^X?^i^k`ba@lk`l`qflkZyyNFAy..0-3yyRy01-/0y
Q>mmivEb^q^kaPqfoyKy@efbcMi^drb_ofkdboE^oofp%20+3)33+1&yyNFAy..0-3y
>CfbiaQbpqyKy@efbcMi^drb_ofkdboE^oofp%20+3)33+1&yyNFAy..0-4y
QPefbiaEfiiyKyE^`hp^tGbkkv%20+4)32+0&yyNFAy..1/1y

@CfbiaQbpqyKyOrkkloqeqlE^idofka^q%2-+-)23+.&+RpbqebXMi^drbPmo^vZlkqebMi^drbaSvhoriebobyyNFAy..0-4yyRy003/.y

@DobbkBddp^kaTebimpyKyOrkkloqetbpqqlBj_bo@irq`e^q%1.+0)2.+1&+RpbXQfiifkde^pq$pMi^drb@^kfpqboZlkqebMolql*TebimBddpebob)qe^qtfiipm^tk^Mi^drbaMolql*Tebim+Hfiifq^kaillqqebjb^qyyNFAy../46yyRy001.5y
>Ollq@^rpbpyKyBj_bo@irq`e>k`fbkq%04+3)2.+3&yyNFAy...5/y
@Ollq@^rpbpyKyHfiiPhbiaAo^hbplkfkqeb_rfiafkdlkqebplrqeb^pqbadblcqeb@irq`e%1.+0)20+/&^kaAo^dlkci^vboE^kaibopfkqebproolrkafkdpyyNFAy...5/y
QOllq@^rpbpyKyBj_bo@irq`e>k`fbkq%04+3)2.+3&yyNFAy...5/y

>QebAb^aOfpbyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2-1y

QDobbkBddp^kaTebimpyKyMi^drb_ofkdboQfiifkde^pq%20+.)33+6&yyNFAy../46y
>Ao^`lkfpD^pqofqfpyKyMi^drb_ofkdboQfiifkde^pq%20+.)33+6&yyNFAy../5-y
QCfbiaQbpqyKy@efbcMi^drb_ofkdboE^oofp%20+3)33+1&yyNFAy..0-4y
>Qfjbclo@ib^krmyKy@efbcMi^drb_ofkdboE^oofp%20+3)33+1&yyNFAy..0-5y
QQfjbclo@ib^krmyKyE^`hp^tGbkkv%20+4)32+0&yyNFAy..0-5y
>M^oqpcloqebGl_yKyE^`hp^tGbkkv%20+4)32+0&yyNFAy..0-6y

@M^oqpcloqebGl_yKyHfiiqebpelsbiqrph^olrka%16+/)4-+6&^ka`liib`q3XPelsbiqrphIfd^jbkqpZ+Cfka>kqlkt^ihfkdcolj%2/+/)40+3&ql%12+6)36+2&^ka_rv^XCobpeMlrkalcCibpeZcoljefjyyNFAy..0-6y

@QebAb^aOfpbyKyC^oqlqebplrqeb^pq^qPefbiaEfii+Sfpfqb^`edo^sbclo^`irb7Cbkdfo%24+4)44+2&)Olafk%26+/)43+6&)Fprialc%26+5)46+1&)Tfka^k%3.+6)5-+-&yyNFAy..2-1y

QM^oqpcloqebGl_yKyE^`hp^tGbkkv%20+4)32+0&yyNFAy..0-6y
>T^okfkd7Pljb>ppbj_ivObnrfobayKyE^`hp^tGbkkv%20+4)32+0&yyNFAy..0.-y

@T^okfkd7Pljb>ppbj_ivObnrfobayKy?^`h^qE^idofka%2-+-)23+.&+RpbqebX>_ljfk^qflk>ppbj_ivHfqZqlprjjlk^Jfkaibpp>_ljfk^qflk)olrkarm^_rk`elcSvhori^kaabqlk^qbfq)qebkobmb^qyyNFAy..0.-yyRy003.0y

@Ao^`lkfpD^pqofqfpyKyDl_^`hqlBj_bo@irq`e^q%1.+0)2.+1&+Illhrmfkqeb^fo^kacfka^Molql*Ao^hbqebkmi^`bXQfiifkde^pq$pMi^drbaJb^qZlkqebdolrkaqlprjjlkfqaltkqebkhfiifqyyNFAy../5-yyRy0011.y

QQebAb^aOfpbyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2-1y
>Biabo>qrfh^kaH^j^dr^yKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2-4y
QBiabo>qrfh^kaH^j^dr^yKyBiabo>qrfh%/2+-)24+-&yyNFAy..2-4y

cH^j^dr^yKyHfmQo^tiphfm%/1+4)24+6&yyNFAy..2-5y

>DobwwfuPmfkaibpk^myKyBiabo>qrfh%/2+-)24+-&yyNFAy..2-5y
>CbbafkdqebProsfslopyKyBiabo>qrfh%/2+-)24+-&yyNFAy..123y

@CbbafkdqebProsfslopyNFAy..123yyKy>iilsboqebfpi^ka^olrka%0/+2)33+/&y
QCbbafkdqebProsfslopyKyBiabo>qrfh%/2+-)24+-&yyNFAy..123y
>>ojfkdH^j^dr^yKyBiabo>qrfh%/2+-)24+-&yyNFAy..124y
@>ojfkdH^j^dr^yNFAy..124yyKyIlqplkqebkloqebokm^oqlcqebfpi^ka^olrka%/3+-)34+-&y
Q>ojfkdH^j^dr^yKyBiabo>qrfh%/2+-)24+-&yyNFAy..124y
>>sbkdbFph^^iyKyBiabo>qrfh%/2+-)24+-&yyNFAy..125y

QDobwwfuPmfkaibpk^myKyDobwwfuPmfkaibpk^m%/0+.)3/+4&yyNFAy..2-5y
>Pqobbq@obayKyDobwwfuPmfkaibpk^m%/0+.)3/+4&yyNFAy..2-6y

QPqobbq@obayKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2-6y
>P`llaibpyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2.-y
>ClodlqqbkQob^probyKyE^kapljbQboov%02+3)5-+0&yyNFAy..101y

@P`llaibpyNFAy..2.-yyKyGrpqlccpelobqlqebplrqe^olrka%05+-)51+-&)grpqt^fqcloeboqlptfj^olrkay
@ClodlqqbkQob^probyNFAy..101yyRy01-43yyKyAfsbaltkqlqebtob`h^db+RpbqebXCfpe?i^aaboZfcvlrkbba+CfkaqebXB^dibCfdrofkbZfklkb_l^q%04+5)51+3&^kaqebX>j^kfS^pbZfkqeblqebo%04+/)52+3&y

QClodlqqbkQob^probyKyE^kapljbQboov%02+3)5-+0&yyNFAy..101y
>QebCo^do^k`blcJlkbvyKyE^kapljbQboov%02+3)5-+0&yyNFAy..122y
QP`llaibpyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2.-y
>QebPq^cclcPqloj$pCrovyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2..y
>QebColwbkEb^oqlcFprialcyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2./y
>QebIlpqPefbialcqeb>bpfofqbpyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2.6y
>Qeb>k`fbkq>ojlolcqebHs^iafoyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..234y
>D^j_ifkdAb_qyKyQ^orh%03+0)5-+2&yyNFAy..131y
@D^j_ifkdAb_qyNFAy..131yyKyPmb^htfqePfisbojllkE^oov%02+-)5.+-&^ka_b^qefjqfiiebdfsbpqebab_qy
QD^j_ifkdAb_qyKyQ^orh%03+0)5-+2&yyNFAy..131y
>G^`hIfhbpEfpAofkhyKyQ^orh%03+0)5-+2&yyNFAy..133y
@G^`hIfhbpEfpAofkhyNFAy..133yyKyFkpfabqeb_rfiafkd)lkqebpb`lkaibsbi%02+2)46+1&+Q^ihqlqeb_^oj^faLid^)qebkmf`hefpml`hbqtebkebm^ppbplrqy
QG^`hIfhbpEfpAofkhyKyQ^orh%03+0)5-+2&yyNFAy..133y
>Ab^aJ^k$pAb_qyKyQ^orh%03+0)5-+2&yyNFAy..134y

@Qeb>k`fbkq>ojlolcqebHs^iafoyNFAy..234yyKyElm^_lj_boofabkb^oqebpelob%03+-)5.+3&+Eb^aaltkfkqlqebelialcqebpefm)qebkq^hbqeb_lj_bo_^`hy

>Pt^__fk$Pl^myKyP`rqqibColpqmolt%04+4)46+2&yyNFAy..136y
@Pt^__fk$Pl^myNFAy..136yyKyHfii?fdOlv)plrqetbpqlcqeblqebopb^iflkp%0.+3)44+2&y
@QebCo^do^k`blcJlkbvyNFAy..122yyKyHfiiO^_fa?oltk?b^op^olrka%00+-)46+-&^ka`liib`q1X?b^oJrphpZy

QQebIlpqPefbialcqeb>bpfofqbpyKy@^mq^fkBiifp%04+6)41+4&yyNFAy..2.6y
>JrqfkvlkqebJbo`vyKy@^mq^fkBiifp%04+6)41+4&yyNFAy..2/4y
@JrqfkvlkqebJbo`vyNFAy..2/4yyKyOb`lsbo2X?^oobiplc?i^pqfkdMltaboZaltkfkqebpefm$peliay
QJrqfkvlkqebJbo`vyKy@^mq^fkBiifp%04+6)41+4&yyNFAy..2/4y
>Ploilc$p?llqvyKy@^mq^fkBiifp%04+6)41+4&yyNFAy..2/6y
@Ploilc$p?llqvyNFAy..2/6yyKyTebkqebpefmdlbpkb^opelob)rpbqeb`^kklk^qqeblqebobkalcqebpefm)qebkptfjqlpelob^kado^_XPloilc$p?llqvZ^olrka%1.)40&y
QPloilc$p?llqvyKy@^mq^fkBiifp%04+6)41+4&yyNFAy..2/6y
>QebPefbialcqeb>bpfofqbpyKy@^mq^fkBiifp%04+6)41+4&yyNFAy..20-y

QPt^__fk$Pl^myKyP`rqqibColpqmolt%04+4)46+2&yyNFAy..136y
QQebCo^do^k`blcJlkbvyKyE^kapljbQboov%02+3)5-+0&yyNFAy..122y
>>Qo^fqlo>jlkdRpyKyE^kapljbQboov%02+3)5-+0&yyNFAy..140y
Q>Qo^fqlo>jlkdRpyKyWbe$dbek%02+3)5-+3&yyNFAy..140y
>Wbe$dbekPbwyKyWbe$dbek%02+3)5-+3&yyNFAy..126y
QWbe$dbekPbwyKyE^kapljbQboov%02+3)5-+0&yyNFAy..126y
>>@^osbo^ka^@ol^hboyKyE^kapljbQboov%02+3)5-+0&yyNFAy..143y
?XPefkvHkfcbZyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..146yyIy025.0y
@>@^osbo^ka^@ol^hboyNFAy..143yyKy@^mqrob^XP`^i^t^dColdZclrka^olrkaqeb`^jmpfqb%02)5-&y
Q>@^osbo^ka^@ol^hboyKyWbe$dbek%02+3)5-+3&yyNFAy..143y
>@oltibdA^kyKyWbe$dbek%02+3)5-+3&yyNFAy..146y
@@oltibdA^kyNFAy..146yyKyHfii@oltibdA^klkqebpefm^q%02+6)50+3&y
Q@oltibdA^kyKyE^kapljbQboov%02+3)5-+0&yyNFAy..146y
>JbbqKrj_boQtlyKyE^kapljbQboov%02+3)5-+0&yyNFAy..15-y
QJbbqKrj_boQtlyKy>kkfb?lkk%02+2)46+2&yyNFAy..15-y
>QebGfdfpRmyKy>kkfb?lkk%02+2)46+2&yyNFAy..14.y
@QebGfdfpRmyNFAy..14.yyKyEb^aqlqeb_b^o`^sblkqebkloqepfablcqebfpi^ka%00+3)42+3&+Dlfk)_b^qaltkGlk^e)qebkqeb_b^oqe^qb^qpefj+Dolrmnrbpq)_rqplil^_iby
@QebColwbkEb^oqlcFprialcyNFAy..2./yyKyKb^otebobqeb_b^opm^tkp%0/+1)45+5&y

@Ab^aJ^k$pAb_qyNFAy..134yyKyLkqebkloqefpi^ka)rmlklkblcqebofpbprkaboqebifcq%0/+4)3-+0&y

@>sbkdbFph^^iyNFAy..125yyKyLkqebb^pqpfablcqebfpi^ka%00+6)30+3&+RpbqebXEloklcH^j^dr^ZfcvlrkbbaqlyyRy03444y
@QebPq^cclcPqloj$pCrovyNFAy..2..yyKyFkqebelialcqebpefm%02+-)31+-&+Pkb^hm^pqqebbifqbtebkebeb^aplkqlqebrmmbo_ltlcqebpefmy

Q>sbkdbFph^^iyKyBiabo>qrfh%/2+-)24+-&yyNFAy..125y
>Qo^sbiqlJl^$hfE^o_loyKy>krkf^n%/1+3)25+5&yyNFAy./..5y
>QebT^vqlEfpEb^oq+++yKy>krkf^n%/1+3)25+5&yyNFAy..14/y
KDbq^_lrq2uXQ^pqvObbcCfpeZyKyCfkacfpep`ellipfkqebt^qbop_bqtbbkqebqtlfpi^kap%01+-)35+-&^karpbX>krkf^n$pKbqZlkqebj+Vlr$iimol_^_ivkbba^qib^pqqeobbp`elli$ptloqe+yyRy1-613yyIy01./42y
@QebT^vqlEfpEb^oq+++yNFAy..14/yyRy01./4yyKyQ^odbq^_rii%0.+-)41+-&lkqebplrqepelob)pq^ka^pc^o^t^v^pvlr`^k^kaqlppefj^cfpe+Jlsbkloqe^kaobmb^qy

QQebGfdfpRmyKy>kkfb?lkk%02+2)46+2&yyNFAy..14.y
QAb^aJ^k$pAb_qyKyQ^orh%03+0)5-+2&yyNFAy..134y

EKbt>d^j^kayKy?^pfiLpdlla%2/+/)33+2&yyNFAy..235y
QAo^`lkfpD^pqofqfpyKyMi^drb_ofkdboQfiifkde^pq%20+.)33+6&yyNFAy../5-y
QT^okfkd7Pljb>ppbj_ivObnrfobayKyE^`hp^tGbkkv%20+4)32+0&yyNFAy..0.-y

CH^j^dr^yKyQl_f^pP^ohelcc%2/)34+1&yyNFAy..235y

QQebT^vqlEfpEb^oq+++yKy>krkf^n%/1+3)25+5&yyNFAy..14/y
QQebPq^cclcPqloj$pCrovyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2..y
QQebColwbkEb^oqlcFprialcyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2./y
QQebPefbialcqeb>bpfofqbpyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..20-y
QQeb>k`fbkq>ojlolcqebHs^iafoyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..234y
>>ObqrokqlObpqfkdyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..235y
@>ObqrokqlObpqfkdyNFAy..235yyKy?^`haltk^qPefbiaEfii)rpbqebX?rkaiblcSovhri>oqfc^`qpZ^qb^`elcCbkdfo%24+4)44+2&)Olafk%26+/)43+6&)Fprialc%26+5)46+1&)Tfka^k%3.+6)5-+-&yyRy013/1y
Q>ObqrokqlObpqfkdyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..235y
>Obqrokql>qrfhyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..24/y
QObqrokql>qrfhyKyBiabo>qrfh%/2+-)24+-&yyNFAy..24/y

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
