DugisGuideViewer:RegisterGuide("Netherstorm (68-70 |cfff0c502Optional|r)", "Shadowmoon Valley (68-70 |cfff0c502Optional|r)", "Horde", "L", function()
return [[
AAA

OKbqebopqlojyKyQo^sbiqlKbqebopqloj%/1+/)22+/&yyNFAy.-.50y
>LccQl>ob^2/yKyKbqebolildfpq@lmmbokf`hbip%/.+5)22+3&yyNFAy.-.50y

O>ob^2/yKyQo^sbiql>ob^2/%/.+5)22+3&yyNFAy.-01/y
>Pb`rofkdqebPe^ibphfkPe^ibyKy?llqp%0/+0)30+6&+Vlrj^ve^sbqlt^fqcloefjqlobpm^tkyyNFAy.-01/y
QLccQl>ob^2/yKyOl`hbq*@efbcCrpbi^db%0/+4)31+6&yyNFAy.-.50y
>Vlr$obEfobayKyOl`hbq*@efbcCrpbi^db%0/+4)31+6&yyNFAy.-.53y
e>ob^2/yKyFkkhbbmboObjfAlalpl%0/+-)31+1&yyNFAy.-.56y
>J^k^clodb?$k^^oyKyP`ovbolkiv)qf`hqefppqbmfcqefpnrbpqfpklq^s^fi^_ibqlvlr+Pmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy.-.56y
>Afpqo^`qflk^qJ^k^clodb?$k^^oyKy>ialolkiv)qf`hqefppqbmfcqefpnrbpqfpklq^s^fi^_ibqlvlr+Bu^o`eLobifp%0/+.)31+/&yyNFAy.-/1.y
>Qeb>o`ej^db$pPq^ccyKyO^s^katvo%0.+1)33+/&yyNFAy.-.40y

>Ob`e^odfkdqeb?^qqbofbpyKy?lq*Pmb`f^ifpq>iibv%0.+2)23+3&yyNFAy.-.6-y
>J^ohSfp>ifsbyKyJ^uu>+JfiiflkJh+S%0.+2)23+3&yyNFAy.-.6.y
@J^ohSfp>ifsbyKy@ljmibqbqebbp`loqnrbpqyyNFAy.-.6.y
@Vlr$obEfobayKy@liib`q.-XBqeboifqefrjJ^qofu@ovpq^ipZ^olrkaqebOrfkplcBkh^^q%00+2)22+-&yNFAy.-.53y
@Ob`e^odfkdqeb?^qqbofbpyKyClrka^ilkdqebofadb%/5+4)2/+5&+Q^hbme^pberkqbopaltkql^_lrq/2"ifcb)rpbqebX?^qqbovOb`e^odfkd?i^pqboZlkqebj)qebkhfiiqebjyyRy/5036yyNFAy.-.6-y
QJ^ohSfp>ifsbyKy?lq*Pmb`f^ifpq>iibv%0.+2)23+3&yyNFAy.-.6.y
QOb`e^odfkdqeb?^qqbofbpyKy?lq*Pmb`f^ifpq>iibv%0.+2)23+3&yyNFAy.-.6-y
@Pb`rofkdqebPe^ibphfkPe^ibyKyIllqcoljqebPe^ibphfkCi^vbop^olrka%/4+1)3-+/&yyNFAy.-01/y

QPb`rofkdqebPe^ibphfkPe^ibyKy?llqp%0/+0)30+6&yyNFAy.-01/y
>Qe^qIfqqibBuqo^Hf`hyKy?llqp%0/+0)30+6&yyNFAy.-.66y
QVlr$obEfobayKyOl`hbq*@efbcCrpbi^db%0/+4)31+6&yyNFAy.-.53y
>Fks^ir^_ib>ppbqW^mmfkdyKyOl`hbq*@efbcCrpbi^db%0/+4)31+6&yyNFAy.-/-0y
>ObmloqqlBkdfkbbofkdyKyOl`hbq*@efbcCrpbi^db%0/+4)31+6&yyNFAy.-//2y
QObmloqqlBkdfkbbofkdyKy@efbcBkdfkbboQobm%0/+2)33+4&yyNFAy.-//2y
>Bppbk`bcloqebBkdfkbpyKy@efbcBkdfkbboQobm%0/+2)33+4&yyNFAy.-//1y

@Bppbk`bcloqebBkdfkbpyKy@liib`qqebbppbk`bpcoljqebJ^k^To^fqe^olrka%03+1)26+5&yyNFAy.-//1y
@Qe^qIfqqibBuqo^Hf`hyKy@liib`qcoljqebKbqeboO^vp^olrka%/4+/)26+1&yyNFAy.-.66y

QQe^qIfqqibBuqo^Hf`hyKy?llqp%0/+0)30+6&yyNFAy.-.66y
QBppbk`bcloqebBkdfkbpyKy@efbcBkdfkbboQobm%0/+2)33+4&yyNFAy.-//1y
>Bibjbkq^iMltboBuqo^`qflkyKy@efbcBkdfkbboQobm%0/+2)33+4&yyNFAy.-//3y

@J^k^clodb?$k^^oyKyHfii@^mq^fk>o^qevk%/4+4)32+/&fkpfabJ^k^clodb?$k^^o^ka`libi`qqeb?$k^^oMboplkkbiOlpqboyyIy/5043yyNFAy.-.56y
@Afpqo^`qflk^qJ^k^clodb?$k^^oyKyClrka^olrkaJ^k^clodb?$k^^o%/2+4)35+1&yyNFAy.-/1.y
@Bibjbkq^iMltboBuqo^`qflkyKyPlrqe^qqeb@orj_ifkdT^pqb%0/+1)45+3&+RpbqebXBibjbkq^iMltboBuqo^`qloZlkqebPrkabobaorj_ibop^kat^om^_boo^qflkpqebkhfiiqebj+yyNFAy.-//3y
@Fks^ir^_ib>ppbqW^mmfkdyKyKloqeb^pq^qqeb>ohilkOrfkp%1.+-0)40+4.&)%1.+1/)4.+5/&)%1-+/4)4/+6.&)%1/+2/)4/+./&yyNFAy.-/-0y
@Qeb>o`ej^db$pPq^ccyKyRpbqebX@lkgrofkdMltaboZlkqebclrkq^fkfkqeb`bkqbolcqeborfkp^kahfiiBhhlo^peqebFknrfpfqlo%1-+5)4/+1&yyRy/6/-4yyNFAy.-.40y

QFks^ir^_ib>ppbqW^mmfkdyKyIb^aP^mmbo?i^pqcfwwib%01+.)35+.&yyNFAy.-/-0y
>Ao+?lljyKyIb^aP^mmbo?i^pqcfwwib%01+.)35+.&yyNFAy.-//.y
QBibjbkq^iMltboBuqo^`qflkyKy@efbcBkdfkbboQobm%0/+2)33+4&yyNFAy.-//3y
QQeb>o`ej^db$pPq^ccyKyO^s^katvo%0.+1)33+/&yyNFAy.-.40y
>Ob_rfiafkdqebPq^ccyKyO^s^katvo%0.+1)33+/&yyNFAy.-0--y
QAfpqo^`qflk^qJ^k^clodb?$k^^oyKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-/1.y
QJ^k^clodb?$k^^oyKyPmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy.-.56y
>Jb^profkdT^omBkbodfbpyKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-0.0y
>>ppfpqfkdqeb@lkploqfrjyKyFcvlr^iob^av^``bmqba@lkploqfrj@ovpq^i@liib`qflkaolmfqql^``bmqqefp)Pmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy.-/31y
>K^^orQb`eklildvyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-/10y
Q>ppfpqfkdqeb@lkploqfrjyKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/31y
>@lkploqfrj@ovpq^i@liib`qflkyKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/32y

@Ao+?lljyKyKloqeb^pqlcqltk^q@^jmlc?llj%02+-)26+5&+Orkfk)_lj_efj)^kaorklrq+Obmb^qqfiiab^a+yyRy/61/6yyNFAy.-//.y
@Ob_rfiafkdqebPq^ccyKyHfiiqebAfpbj_lafbajl_p^olrkaqebOrfkplcBkh^^q%00+.)20+0&yyNFAy.-0--y

QOb_rfiafkdqebPq^ccyKyO^s^katvo%0.+1)33+/&yyNFAy.-0--y
>@ropblcqebSflibqQltboyKyO^s^katvo%0.+1)33+/&yyNFAy.-.41y
QAo+?lljyKyIb^aP^mmbo?i^pqcfwwib%01+.)35+.&yyNFAy.-//.y

@Jb^profkdT^omBkbodfbpyKyRpbqeblo_tebobqebmfmbpdlfkqlqebdolrkafkqefploabo7Kloqe%/2+6-)3-+./&)Tbpq%/.+/0)33+56&)Plrqe%/-+45)4-+366&)B^pq%/5+4-)4/+/1&yyRy/60/1yyNFAy.-0.0y
QK^^orQb`eklildvyKy?$k^^o@lkqoli@lkplib%/0+/)35+.&yyNFAy.-/10y
>?$k^^o@lkplibQo^kp`ofmqflkyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-/12y
@@lkploqfrj@ovpq^i@liib`qflkyKyHfiiMbkq^qe^olk^q>ohilkOrfkp%1/+2)4/+2&yyIy/55/6yyNFAy.-/32y

>KbbapJlob@lt_biiyKyQe^abii%24+4)52+-&yyNFAy.-001y
>Fkafpmbkp^_ibQllipyKy>mmobkqf`b>kaobqe^k%24+4)52+/&yyNFAy.-00.y
>J^ibslibkqObjk^kqpyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-.51y
Q@ropblcqebSflibqQltboyKyRpbX>o`ej^dbS^odlqe$pPq^ccZyyRy/5122yyNFAy.-.41y
>QebPfdfilcHo^prpyKyFj^dblc>o`ej^dbS^odlqe)PrjjlkbayyRy/5122yyNFAy.-.55y
>QebRkbkafkdFks^pflkyKyIfbrqbk^kq*Plo`boboJloo^k%24+2)53+0&yyNFAy.-010y
>>C^qbTlopbQe^kAb^qeyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-.52y

H>_grofpq?bij^o^yKyPlrqelcqebqltbo%25+6)55+-&yyIy/6/01yyNFAy.-0-2y
>>_grofpq?bij^o^yKyColjX?bij^o^$pQljbZyyRy/6/01yyNFAy.-0-2y
H?^qqib*J^dbA^qeof`yKyFkpfabqebqltke^ii%3-+1)55+-&yyIy/6/00yyNFAy.-.5/y
>?^qqib*J^dbA^qeof`yKyColjXA^qeof`$p?i^abZyyRy/6/00yyNFAy.-.5/y
@Fkafpmbkp^_ibQllipyKyHfiiqeb^mmobkqf`bp^qqeb_i^`hpjfqeelrpb%3.+0)52+-&yyNFAy.-00.y
H@lkgroboIrjfko^qeyKyClrka^olrka%3-+-)52+0&yyIy/6/02yyNFAy.-0-3y
>@lkgroboIrjfko^qeyKyColjXIrjfko^qe$pJ^kqibZyyRy/6/02yyNFAy.-0-3y
H@leifbkColpqtb^sboyKyT^kabop^olrka%26+5)54+.&yyIy/6/03yyNFAy.-0-4y
>@leifbkColpqtb^sboyKyColjX@leifbk$p@^mZyyRy/6/03yyNFAy.-0-4y

QKbbapJlob@lt_biiyKy@ib^oqebm^qelsboqeb_ofadblkvlrot^vql?bppv%26+.)46+2&yyNFAy.-001y
>Tebkqeb@ltp@ljbEljbyKy?bppv%26+.)46+2&yyNFAy.-004y
@Tebkqeb@ltp@ljbEljbyKyPq^v_^`h^kaibq?bppvdbqefqcfopqb^`eqfjb)plqe^qpebpqlmp^kadfsbpvlrqfjbqlhfiiqefkdpyyNFAy.-004y
QTebkqeb@ltp@ljbEljbyKyQe^abii%24+4)52+-&yyNFAy.-004y
QFkafpmbkp^_ibQllipyKy>mmobkqf`b>kaobqe^k%24+4)52+/&yyNFAy.-00.y
>J^pqboPjfqeOelkprpyKy>mmobkqf`b>kaobqe^k%24+4)52+/&yyNFAy.-00/y

@?^qqib*J^dbA^qeof`yKyQlqebtbpq)cfopqelrpblkqebibcq%23+6)53+6&+Rpbqeb_i^ab+yyRy/502.yyNFAy.-.5/y
@@lkgroboIrjfko^qeyKyQtlelrpbprm)^_olhbkelrpblkqebibcq%23+1)54+5&+Rpbqebj^kqib+yyRy/502/yyNFAy.-0-3y
@@leifbkColpqtb^sboyKyQtljlobelrpbprmlkqebofdeq%22+.)54+2&+Rpbqebe^q+yyRy/5020yyNFAy.-0-4y
@QebRkbkafkdFks^pflkyKyCo^djbkqfpofdeqfkcolkqlcqebelrpb%22+3)54+/&yyNFAy.-010y
@>_grofpq?bij^o^yKyRpbqeb_llhpebicfkqebelrpbqlqebkloqe%22+2)53+2&+Rpbqebqljb+yyRy/5003yyNFAy.-0-2y
@>C^qbTlopbQe^kAb^qeyKyHfiiqebjl_pclrka^olrka%23+1)54+4&yyNFAy.-.52y
@J^ibslibkqObjk^kqpyKyHfiiqebPbsbobaPmfofqp^olrka%26+4)55+6&yyNFAy.-.51y

QQebRkbkafkdFks^pflkyKyIfbrqbk^kq*Plo`boboJloo^k%24+2)53+0&yyNFAy.-010y
>Mlqbkqf^iBkbodvPlro`byKyIfbrqbk^kq*Plo`boboJloo^k%24+2)53+0&yyNFAy.-/06y
Q>C^qbTlopbQe^kAb^qeyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-.52y
QJ^ibslibkqObjk^kqpyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-.51y
>Qeb>kk^iplcHfofk$S^oyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-0./y
Q?^qqib*J^dbA^qeof`yKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-.5/y
Q@lkgroboIrjfko^qeyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-0-3y
Q@leifbkColpqtb^sboyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-0-4y
Q>_grofpq?bij^o^yKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-0-2y

@Qeb>kk^iplcHfofk$S^oyKyHfii?^qqib*J^dbA^qeof`^d^fkfkqebqltke^ii%3-+1)55+-&yyNFAy.-0./y
@J^pqboPjfqeOelkprpyKyHfiiOelkprpt^kabofkd^olrka%3.+2)52+2&yyNFAy.-00/y

QQeb>kk^iplcHfofk$S^oyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-0./y
>Pb^o`efkdcloBsfabk`byKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-0.3y
QJ^pqboPjfqeOelkprpyKy>mmobkqf`b>kaobqe^k%24+4)52+/&yyNFAy.-00/y
QPb^o`efkdcloBsfabk`byKyKb`olj^kqf`Cl`rp%3-+0)45+-&yyNFAy.-0.3y
>>IfkdbofkdPrpmf`flkyKyKb`olj^kqf`Cl`rp%3-+0)45+-&yyNFAy.-0.1y
@>IfkdbofkdPrpmf`flkyKyHfiidelpqpfkqeb@e^mbiV^oa^olrka%3-+5)5.+1&yyNFAy.-0.1y
Q>IfkdbofkdPrpmf`flkyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-0.1y
>@^mqrofkdqebMevi^`qbovyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-0.6y
@@^mqrofkdqebMevi^`qbovyKy>`olppcoljqeb_^okfkqeb@e^mbiV^oa)coljqebPrpmf`flrpLrqelrpb%26+6)5-+2&yyNFAy.-0.6y
Q@^mqrofkdqebMevi^`qbovyKy@rpqlaf^kAfbtloqe%24+2)53+0&)Phfmqebcliilt*rmyyNFAy.-0.6y

@Mlqbkqf^iBkbodvPlro`byKyTbpq^qJ^k^clodb@lorr%2/+-)5/+3&yyNFAy.-/06y
@QebPfdfilcHo^prpyKyPmbii_fkaboJ^ov^k^)t^kabofkd^olrkalrqpfab%2.+5)5.+/&yyNFAy.-.55y
QQebPfdfilcHo^prpyKyRpbX>o`ej^dbS^odlqe$pPq^ccZyyRy/5122yyNFAy.-.55y
>Ho^prp$p@ljmbkafrjyKyFj^dblc>o`ej^dbS^odlqe)PrjjlkbayyRy/5122yyNFAy.-.6/y

QMlqbkqf^iBkbodvPlro`byKyIfbrqbk^kq*Plo`boboJloo^k%24+2)53+0&yyNFAy.-/06y
>?rfiafkd^MbofjbqboyKyIfbrqbk^kq*Plo`boboJloo^k%24+2)53+0&yyNFAy.-/1-y
@Ho^prp$p@ljmbkafrjyKy@e^mqbo0fkqebelrpbplrqelcqebqltbo%25+5)54+6&)@e^mqbo.fkqebelrpblkqeblqebopfab%25+3)56+/&)@e^mqbo/fkqebelrpb/allopaltk%24+2)56+3&yyNFAy.-.6/y
QHo^prp$p@ljmbkafrjyKyRpbX>o`ej^dbS^odlqe$pPq^ccZyyRy/5122yyNFAy.-.6/y
>Rkil`hfkdqeb@ljmbkafrjyKyFj^dblc>o`ej^dbS^odlqe)PrjjlkbayyRy/5122yyNFAy.-0-.y

@?rfiafkd^MbofjbqboyKyRpbqeborkb^`qfs^qlo^qqeb0orkbp7b^pqlcqebqltbofkpljbab_ofp%26+/)52+0&)rmqeb_fdefiikloqelcqeb_ofadb%24+1)5/+5&^katbpq^ilkdqebol^aqlqebj^k^clodb%21+0)53+.&yyRy/54/2yyNFAy.-/1-y
Q?rfiafkd^MbofjbqboyKyIfbrqbk^kq*Plo`boboJloo^k%24+2)53+0&yyNFAy.-/1-y
>Qlo`efkdPrkcrovEliayKyIfbrqbk^kq*Plo`boboJloo^k%24+2)53+0&yyNFAy.-/00y
>QebPrkcrovD^oofplkyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-///y

@Qlo`efkdPrkcrovEliayKyKloqe^qPrkcrovElia%23)5&+Hfiici^jbhbbmbopqldbq^qlo`e)qebkqlo`eqbpqp^ka_^iifpq^p+Vlr`^kqlo`eqebp^jbqbkq^ka_^iifpq^j^kvqfjbp)qebvobpm^tkc^pq+yyRy/522-yyNFAy.-/00y
@QebPrkcrovD^oofplkyKyHfiiqebPrkcrov>o`ebop^olrka%23+2)5-+2&yyNFAy.-///y
@Rkil`hfkdqeb@ljmbkafrjyKyHfiiPmbiitb^sboJ^o^qebiib^olrkaqebiltbpqmi^qcloj%23+4)46+-&yyNFAy.-0-.y
QRkil`hfkdqeb@ljmbkafrjyKyRpbX>o`ej^dbS^odlqe$pPq^ccZyyRy/5122yyNFAy.-0-.y
>PrjjlkboH^kqefk$pMofwbyKyFj^dblc>o`ej^dbS^odlqe)PrjjlkbayyRy/5122yyNFAy.-/-6y

QQlo`efkdPrkcrovEliayKyIfbrqbk^kq*Plo`boboJloo^k%24+2)53+0&yyNFAy.-/00y
QQebPrkcrovD^oofplkyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-///y
>AltkTfqeA^biifpyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-//0y

E>ob^2/yRy3615yyNFAy.-/-3y
>Mf`hVlroM^oqyKyM^m^Tebbibo%0/+6)31+4&yyNFAy.-/-3y
Q@lkploqfrj@ovpq^i@liib`qflkyKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/32y
>>Eb^mlcBqebob^ipyKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/3/y
QJb^profkdT^omBkbodfbpyKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-0.0y
Q?$k^^o@lkplibQo^kp`ofmqflkyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-/12y
>PerqqfkdAltkJ^k^clodb?$k^^oyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-0/6y

@PerqqfkdAltkJ^k^clodb?$k^^oyKyHfiiLsbopbboQebobafp%/0+5)4-+2&fkpfabqebj^k^clodb)illqqebX?$k^^o>``bpp@ovpq^iZ^karpbqeb`lkplibyyIy/6033yyNFAy.-0/6y
@Mf`hVlroM^oqyKyPlrqelc>ob^2/^qqebEb^m%/4+-)46+-&yyNFAy.-/-3y
@>Eb^mlcBqebob^ipyKyHfiiqebBqebob^ip^qqebEb^m%/4+-)46+-&yyNFAy.-/3/y

QMf`hVlroM^oqyKyM^m^Tebbibo%0/+6)31+4&yyNFAy.-/-3y
>Fk>P`o^mTfqeQebIbdflkyKyM^m^Tebbibo%0/+6)31+4&yyNFAy.-/0/y
>EbimJ^j^TebbiboyKyM^m^Tebbibo%0/+6)31+4&yyNFAy.-000y
Q>Eb^mlcBqebob^ipyKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/3/y
>T^om*O^faboKbp^^ayKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/-2y
QPerqqfkdAltkJ^k^clodb?$k^^oyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-0/6y
>PerqqfkdAltkJ^k^clodb@lorryKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-00-y
>>qq^`hlkJ^k^clodb@lorryKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-/13y

@T^om*O^faboKbp^^ayKyHfiiT^om*O^faboKbp^^a%/5+/)46+2&yyNFAy.-/-2y
@PerqqfkdAltkJ^k^clodb@lorryKyB^pqlsboqeb_ofadb%13)5.&+HfiiLsbopbboPbvi^kk^%16+-)5.+2&qebkillqqebX@lorr>``bpp@ovpq^iZ^karpbqeb`lkplibyyIy/6063yyNFAy.-00-y
@>qq^`hlkJ^k^clodb@lorryKyHfiiqebjl_p^olrkaJ^k^clodb@lorr%15+1)5.+0&yyNFAy.-/13y

>Aofgv^KbbapVlroEbimyKyD^eorg%13+4)24+-&yyNFAy.-0..y
QEbimJ^j^TebbiboyKyJ^j^Tebbibo%13+3)23+3&yyNFAy.-000y
>LkbAbjlk$pQo^pe+++yKyJ^j^Tebbibo%13+3)23+3&yyNFAy.-/01y
>Ork^Af^dklpqf`yKyJbeoa^a%13+2)23+2&yyNFAy.-1.4y
>KbtLmmloqrkfqfbpyKyJbeoa^a%13+2)23+2&yyNFAy.-015y
>HbbmfkdRm>mmb^o^k`bpyKyPe^rivMlob%13+2)23+.&yyNFAy.-100y
QAofgv^KbbapVlroEbimyKyAofgv^%15+-)31+-&)phfmefpbp`loqnrbpqrkibppvlre^sbebimyyNFAy.-0..y

@LkbAbjlk$pQo^pe+++yKyKloqe^qQebP`o^mCfbia%2-+-)24+.&yyNFAy.-/01y
@Fk>P`o^mTfqeQebIbdflkyKyHfiijl_p^olrakQebP`o^mCfbia%2-+-)24+.&yyNFAy.-/0/y
@Ork^Af^dklpqf`yKy@liib`qcoljqebAf^dklpqf`Bnrfmjbkq^q%15+/)22+-&yyNFAy.-1.4y
@HbbmfkdRm>mmb^o^k`bpyKyHfiiqebOfmc^kdIvku$p^olrkaqebaljb%12+-)20+0&yyNFAy.-100y
@KbtLmmloqrkfqfbpyKy@liib`qcoljqebFslov?bii^olrkaqebaljb%12+-)20+0&yyNFAy.-015y

QLkbAbjlk$pQo^pe+++yKyJ^j^Tebbibo%13+3)23+3&yyNFAy.-/01y
>Ab`i^tfkdAllj`i^tyKyJ^j^Tebbibo%13+3)23+3&yyNFAy.-/02y
QKbtLmmloqrkfqfbpyKyJbeoa^a%13+2)23+2&yyNFAy.-015y
QOrk^Af^dklpqf`yKyJbeoa^a%13+2)23+2&yyNFAy.-1.4y
>Ab^iTfqeqebP^_lqbropyKyJbeoa^a%13+2)23+2&yyNFAy.-1.5y
QHbbmfkdRm>mmb^o^k`bpyKyPe^rivMlob%13+2)23+.&yyNFAy.-100y
>QebAvk^jf`ArlyKyPe^rivMlob%13+2)23+.&yyNFAy.-101y

QFk>P`o^mTfqeQebIbdflkyKyM^m^Tebbibo%0/+6)31+4&yyNFAy.-/0/y
QT^om*O^faboKbp^^ayKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/-2y
>Obnrbpqclo>ppfpq^k`byKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/33y
QPerqqfkdAltkJ^k^clodb@lorryKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-00-y
>PerqqfkdAltkJ^k^clodbArolyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-005y
Q>qq^`hlkJ^k^clodb@lorryKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-/13y
>Prkcrov?ofbcfkdpyKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-0/5y

QObnrbpqclo>ppfpq^k`byKyD^eorg%13+4)24+-&yyNFAy.-/33y
>OfdeqcriObmlppbppflkyKyD^eorg%13+4)24+-&yyNFAy.-/34y

@Ab`i^tfkdAllj`i^tyKyHfiiAllj`i^tqlqebB^pq^q%2-+4)24+2&yyNFAy.-/02y
@PerqqfkdAltkJ^k^clodbArolyKyB^pq^qJ^k^clodbArol+HfiiLsbopbbo>qe^kbi%26+6)35+0&)illqqebXArol>``bpp@ovpq^iZ^karpblk`lkplibyyIy/6064yyNFAy.-005y
@OfdeqcriObmlppbppflkyKy@liib`qebProsbvfkdBnrfmjbkqcoljqeb_lubp^olrka%25+6)32+6&yyNFAy.-/34y
@Prkcrov?ofbcfkdpyKyHfii?ltjbk^ka@bkqroflkpcloqebJfifq^ov?ofbcfkd)@lkgrobopcloqeb>o`^kb?ofbcfkd^olrkaqebJ^k^clodb%25+-)31+-&yyNFAy.-0/5y
@AltkTfqeA^biifpyKyLkqebofadbtbpqlcqebj^k^clodb)orkp_^`h^kacloqe^jlkdpqqeb^o`ebop+yyNFAy.-//0y
@PrjjlkboH^kqefk$pMofwbyKyM^qolip^olrka%23+.)33+1&)illhcloqebt^qbobibjbkq^i+yyNFAy.-/-6y

QPrjjlkboH^kqefk$pMofwbyKyRpbX>o`ej^dbS^odlqe$pPq^ccZyyRy/5122yyNFAy.-/-6y
>>o$hbilpqebDr^oaf^kyKyFj^dblc>o`ej^dbS^odlqe)PrjjlkbayyRy/5122yyNFAy.-.43y

O@lpjltobk`eyKyB^pqlcJ^k^clodbArol%32)33&yyNFAy.-6/1y
>?illavFjm*lppf_ibyKyP^_$^lqe%33+1)34+/&yyNFAy.-6/1y
@?illavFjm*lppf_ibyKyPrjjlkqebfjm^kahfiit^om`e^pbop+Vlrjrpq_bfkjbibbo^kdbtebkqebvafb+yyRy0.5.2yyNFAy.-6/1y
Q?illavFjm*lppf_ibyKyP^_$^lqe%33+1)34+/&yyNFAy.-6/1y

QOfdeqcriObmlppbppflkyKyD^eorg%13+4)24+-&yyNFAy.-/34y
>>k>rafbk`btfqeqebMofk`byKyD^eorg%13+4)24+-&yyNFAy.-/35y
QAb`i^tfkdAllj`i^tyKyJ^j^Tebbibo%13+3)23+3&yyNFAy.-/02y
>T^ok>ob^2/yKyJ^j^Tebbibo%13+3)23+3&yyNFAy.-/04y

@Ab^iTfqeqebP^_lqbropyKyHfii?^o_p`^ib@ol`lifphp^qqebi^hbfkqebB`l*Aljb%13+1)21+3&yyNFAy.-1.5y

QAb^iTfqeqebP^_lqbropyKyJbeoa^a%13+2)23+2&yyNFAy.-1.5y
>QlqebPqlojpmfobyKyJbeoa^a%13+2)23+2&yyNFAy.-1/0y

OQebPqlojpmfobyKyCliiltqebol^alrqqlqeb_fddboaljb%1.)0/&yyNFAy.-1/3y
>Cilo^lcqebB`l*AljbpyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/3y
QQlqebPqlojpmfobyKyDe^_^o%10+2)02+.&yyNFAy.-1/0y
>Af^dklpfp7@ofqf`^iyKyDe^_^o%10+2)02+.&yyNFAy.-1/1y
eQebPqlojpmfobyKyBvlkfu%10+2)03+-&yyNFAy.-002y
>ProsbvfkdqebOrfkpyKyWbmevoflk%11+4)01+6&yyNFAy.-002y
>QebJfkflkplc@rirqe^pyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-003y
>CbiOb^sbop)KlQe^khpyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-522y
QQebAvk^jf`ArlyKy>rafqebKbbaib%11+5)03+4&yyNFAy.-101y
>ObqofbsfkdqebDllapyKy>rafqebKbbaib%11+5)03+4&yyNFAy.-102y
Q>k>rafbk`btfqeqebMofk`byKyFj^dblcKburp*Mofk`bE^o^j^a%12+5)03+-&yyNFAy.-/35y
>Qof^kdri^qflkMlfkqLkbyKyFj^dblcKburp*Mofk`bE^o^j^a%12+5)03+-&yyNFAy.-/36y

C>ob^2/yKyDobkkfh%12+0)01+6&yyNFAy.-/14y
QT^ok>ob^2/yKyOl`hbq*@efbcCrpbi^db%0/+4)31+6&yyNFAy.-/04y
>Al`qloSljfp^)Me+Q+yKyOl`hbq*@efbcCrpbi^db%0/+4)31+6&yyNFAy.-/14y
QPerqqfkdAltkJ^k^clodbArolyKy>k`elofqbH^og^%0/+-)31+/&)Phfmqebcliilt*rmyyNFAy.-005y
QPrkcrov?ofbcfkdpyKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-0/5y
>Lrqpfab>ppfpq^k`byKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-10.y
QAl`qloSljfp^)Me+Q+yKyAl`qloSljfp^)Me+Q+%04+0)30+5&+Phfmqebcliilt*rmyyNFAy.-/14y

QAltkTfqeA^biifpyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-//0y
@>o$hbilpqebDr^oaf^kyKyHfii>o$hbilp%25+.)53+2&yyNFAy.-.43y
Q>o$hbilpqebDr^oaf^kyKy>o`ej^dbS^odlqe%25+1)53+2&+Phfmqebcliilt*rmyyNFAy.-.43y

EQebPqlojpmfobyRy3615yyNFAy.-10-y
@Cilo^lcqebB`l*AljbpyRy/65.5yyKyRpbqebjlari^qlolkqebi^pebop^olrka%06+3)03+.&)qebkhfiiqebjyyNFAy.-1/3y
@Af^dklpfp7@ofqf`^iyKy>qqebdbkbo^qloqlqebkloqeb^pq%14+3)/3+5&yyRy/65-0yyNFAy.-1/1y
@ProsbvfkdqebOrfkpyKy>qqeborfkpkloqeb^pq)grpqlrqpfabqebaljb+J^ohbop^ob^q%2.+-)/-+-&)%21+3)//+5&)%22+5)/-+-&yyRy/6112yyNFAy.-002y
@QebJfkflkplc@rirqe^pyKyCfkaqebobnrfobajl_p^olrka%2.+1)/0+4&yyNFAy.-003y
@CbiOb^sbop)KlQe^khpyKyTbpq^qClodb@^jm7L_ifsflk%04+-)/5+-&)hfiiJbhdfkbbopclo2d^p)rpblklkblcqebob^sbop%02+-)/5+-&)%03+-)/2+-&)%04+-)/2+-&+VlrlkivkbbaqlalqefplkLKBob^sboyyNFAy.-522y

QAf^dklpfp7@ofqf`^iyKyDe^_^o%10+2)02+.&yyNFAy.-1/1y
>QbpqfkdqebMolqlqvmbyKyDe^_^o%10+2)02+.&yyNFAy.-10-y
QProsbvfkdqebOrfkpyKyWbmevoflk%11+4)01+6&yyNFAy.-002y
QQebJfkflkplc@rirqe^pyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-003y
QCbiOb^sbop)KlQe^khpyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-522y
>Qeb?bpqAbcbkpbyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-523y
QCilo^lcqebB`l*AljbpyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/3y
>@ob^qrobplcqebB`l*AljbpyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/4y

@@ob^qrobplcqebB`l*AljbpyKyCfdeqqebQ^i_rh^olrka%1.+-)05+1&ql/-"qebkrpbqebXQ^i_rhQ^ddboZyyRy/65.4yyNFAy.-1/4y
Q@ob^qrobplcqebB`l*AljbpyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/4y
>TebkK^qrobDlbpQllC^oyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/6y
@TebkK^qrobDlbpQllC^oyKyHfiiJ^oh^orfkqebi^hb^q%11+2)/5+0&yyNFAy.-1/6y
QTebkK^qrobDlbpQllC^oyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/6y

@Qeb?bpqAbcbkpbyKyKloqetbpq^qClodb?^pb7Dbebkk^%06+2)/0+3&yyNFAy.-523y
QQbpqfkdqebMolqlqvmbyKyQ^pe^o%11+4).1+2&yyNFAy.-10-y
>>ii@ib^oyKyQ^pe^o%11+4).1+2&yyNFAy.-103y
@>ii@ib^oyKyHfiiqebO^mqlop^olrka%13+2)./+6&yyNFAy.-103y
@ObqofbsfkdqebDllapyKy@liib`qqebXAljbDbkbo^qloPbdjbkqpZ^olrka%12+5)..+5&yyNFAy.-102y
Q>ii@ib^oyKyQ^pe^o%11+4).1+2&yyNFAy.-103y
>Pr``bppyKyQ^pe^o%11+4).1+2&yyNFAy.-11-y
QPr``bppyKyDe^_^o%10+2)02+.&yyNFAy.-11-y
QQeb?bpqAbcbkpbyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-523y
>QbibmloqQefpyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-524y
QObqofbsfkdqebDllapyKy>rafqebKbbaib%11+5)03+4&yyNFAy.-102y

@QbibmloqQefpyKy?^`h^qClodb?^pb7Dbebkk^)qbibmloqbop^q%06)/-&)%1.).5&)%11)/-&yyRy0.345yyNFAy.-524y

QQbibmloqQefpyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-524y

KIbsbi4-ObnrfobayKyQebcliiltfkdnrbpqobnrfobpibsbi4-qlmf`hrmyyNFAy.-2-yyNFAy.-/4-yyMIy4-y
>>Klq*Pl*JlabpqMolmlp^iyKyTfkaQo^aboJ^ofa%25+5)0.+-&yyNFAy.-/4-y
>Bib`qol*Pel`hDllakbppyKyObpb^o`eboK^srra%26+0)0/+2&yyNFAy.-1..y
>QebBqebobrjyKy@ljj^kabo>jbbo%26+2)0/+0&yyNFAy.-006y
>Ob`fmbcloAbpqor`qflkyKyMolcbpploA^_fof%3-+.)0.+5&yyNFAy.-104y
>@^mq^fkQvo^ifrpyKyCibpeE^kaiboSfofafrp%3-+.)0/+2&yyNFAy.-1//y

RRpbXK^srra$p@lk`l`qflkZyRy/6404y
HSlfaT^pqbpyKy>ilkdqebofadb%22+4)10+3&yyNFAy.-1..yyNLySlfaT^pqbDil_ribpi^fk70-,0-yyNFAy.-1..y
@QebBqebobrjyKyCfkaBqebobrjjl_p^olrka%24+0)03+6&^ka@^mq^fkWls^u^q%23+5)04+0&yyNFAy.-006y
QQebBqebobrjyKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-006y
>BqebobrjA^q^yKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-051y
@BqebobrjA^q^yKyCfkaqebBqebobrjA^q^@biiqlqebPlrqe%22+5)06+6&yyNFAy.-051y
QBqebobrjA^q^yKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-051y
>Mlqbkqf^iclo?o^fkA^j^db:EfdeyKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-052y
@Mlqbkqf^iclo?o^fkA^j^db:EfdeyKyHfiiBqebobrjObi^vp^olrka%22+5)1/+0&)aofkhqebbppbk`bqebvaolm)qebkhfiiqebA^q^TvojifkdpyyRy/615/yyNFAy.-052y
QMlqbkqf^iclo?o^fkA^j^db:EfdeyKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-052y
>P*>*?*L*Q*>*D*ByKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-1-2y
@P*>*?*L*Q*>*D*ByKyHfiiBqebobrj>o`elkp^kaBqebobrjLsboiloap^olrka%23+3)1/+4&yyNFAy.-1-2y
QP*>*?*L*Q*>*D*ByKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-1-2y
>AbifsbofkdqebJbpp^dbyKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&yyNFAy.-1-3y
@AbifsbofkdqebJbpp^dbyKy@ljmibqbqebBp`loqNrbpqyyNFAy.-1-3y
QAbifsbofkdqebJbpp^dbyKyFj^dblc@ljj^kabo>jbbo)^qqebQo^kpmlkabo%23+5)05+4&+Phfmqebcliilt*rmyyNFAy.-1-3y

@@^mq^fkQvo^ifrpyKyHfiiT^oabkF`lpel`h%21+3)1-+.&qlqebplrqetbpqcloefphbv)qebklmbkqebmofplk_befkaKburp*HfkdP^ie^a^^o%20+-)1.+-&yyNFAy.-1//y
>QebCibpeIfbp+++yKy>dbkq>o^ubp%26+1)12+.&yyNFAy.-012y
@QebCibpeIfbp+++yKyFkqebjfkb%3.+-)12+-&)>``bppPe^cqWblk+Hbbmibcq^pvlrbkqbo+Rpbqebifdeqbolkqeb`lompbp)_rqalk$qdbqqll`ilpb+yyRy/6140yyNFAy.-012y
>>o`lkrpqebFkp^qf^_ibyKy>dbkqV^*pfu%3-+6)1.+3&yyNFAy.-020y
@>Klq*Pl*JlabpqMolmlp^iyKyCfkaqebXQbibmloqboMltboM^`hZ^q%3-+6)1.+2&yyNFAy.-/4-y
@>o`lkrpqebFkp^qf^_ibyKyDl_^`hlrqqlqebbkqo^k`b)qebkeb^afkpq^vfkdofdeq+Hfii>o`lkrpfkqeb_fdollj%3-+.)1-+0&yyNFAy.-020y
QQebCibpeIfbp+++yKy>dbkq>o^ubp%26+1)12+.&yyNFAy.-012y

RRpbXK^srra$p@lk`l`qflkZyRy/6404yyNFAy.-1..y
@Bib`qol*Pel`hDllakbppyKyHfii0-PibbmfkdPiradbDil_rib^olrka%32+-)04+4&yyNFAy.-1..y
@Ob`fmbcloAbpqor`qflkyKySlfapeofbhbop^kaSlfato^fqep^olrka^kafkpfab^ka^olrkaqebj^k^clodb%3/+-)1-+2&yyNFAy.-104y
@Qof^kdri^qflkMlfkqLkbyKyRpbqebabsf`bqebkcfkaqebj^oh%33+4)00+5&yyRy/563/yyNFAy.-/36y

Q>Klq*Pl*JlabpqMolmlp^iyKyFj^dblcTfkaQo^aboJ^ofa+>qqebelildo^me%4.+/)06+-&yyNFAy.-/4-y
>DbqqfkdAltkql?rpfkbppyKyFj^dblcTfkaQo^aboJ^ofa+>qqebelildo^me%4.+/)06+-&+Vlr`^k$qalqefpnrbpqfcvlr$sbdlqefdeKbqebotfkdc^`qflkyyNFAy.-/4.y
@DbqqfkdAltkql?rpfkbppyKy@liib`qcoljKbqeboAo^dlkp^kaAo^hbp^olrka%4/+3)05+4&yyNFAy.-/4.y
QDbqqfkdAltkql?rpfkbppyKyPeolrabaCfdrob%4-+6)05+6&yyNFAy.-/4.y
>Cloj^iFkqolar`qflkpyKyPeolrabaCfdrob%4-+6)05+6&+Vlr`^k$qalqefpnrbpqfcvlr$sbdlqefdeKbqebotfkdc^`qflkyyNFAy.-/5.y
QCloj^iFkqolar`qflkpyKyQvof%4.+/)02+/&yyNFAy.-/5.y
>>MoljfpfkdPq^oqyKyQvof%4.+/)02+/&+Vlr`^k$qalqefpnrbpqfcvlr$sbdlqefdeKbqebotfkdc^`qflkyyNFAy.-/4/y
@>MoljfpfkdPq^oqyKyD^qebo.2XKbqeboAo^dlkhfkBddZcolj^olrka%4/+2)04+0&yyNFAy.-/4/y
Q>MoljfpfkdPq^oqyKyQvof%4.+/)02+/&yyNFAy.-/4/y
>Qolr_ibpljbAfpqo^`qflkpyKyQvof%4.+/)02+/&+Vlr`^k$qalqefpnrbpqfcvlr$sbdlqefdeKbqebotfkdc^`qflkyyNFAy.-/40y

QOb`fmbcloAbpqor`qflkyKyMolcbpploA^_fof%3-+.)0.+5&yyNFAy.-104y
>LkKbqebovTfkdpyKyMolcbpploA^_fof%3-+.)0.+5&yyNFAy.-105y
Q@^mq^fkQvo^ifrpyKyCibpeE^kaiboSfofafrp%3-+.)0/+2&yyNFAy.-1//y
QBib`qol*Pel`hDllakbppyKyObpb^o`eboK^srra%26+0)0/+2&yyNFAy.-1..y
Q>o`lkrpqebFkp^qf^_ibyKy@ljj^kabo>jbbo%26+2)0/+0&yyNFAy.-020y
QQof^kdri^qflkMlfkqLkbyKyAb^iboE^wwfk%25+1)0.+1&yyNFAy.-/36y
>Qof^kdri^qflkMlfkqQtlyKyAb^iboE^wwfk%25+1)0.+1&yyNFAy.-/42y

@Qolr_ibpljbAfpqo^`qflkpyKyIrobTfkaQo^aboJ^ofa%25+5)0.+-&^t^v^kahfiiefjyyNFAy.-/40y
@LkKbqebovTfkdpyKyQ^ihqlqebkbqeboao^hb^kaq^hb^ofab+Pm^jqeb_lj_tebkvlr^oblsboqebj^k^clodbyyRy/6445yyNFAy.-105y
QLkKbqebovTfkdpyKyMolcbpploA^_fof%3-+.)0.+5&+Phfmqebcliilt*rmyyNFAy.-105y

QQolr_ibpljbAfpqo^`qflkpyKyQvof%4.+/)02+/&+Phfmqebcliilt*rmyyNFAy.-/40y

EQebPqlojpmfobyRy/6404yyNFAy.-0.4y
QLrqpfab>ppfpq^k`byKyH^vi^^k%01+5)05+/&yyNFAy.-10.y
>>A^ohM^`qyKyH^vi^^k%01+5)05+/&yyNFAy.-05-y
>Ab^ifkdtfqeqebClobj^kyKyTfkaQo^aboQrirj^k%01+3)04+6&yyNFAy.-0.4y
>Kbrqo^ifwfkdqebKbqeboj^k`bopyKyKbqebo*Pq^ihboL^wri%01+3)04+5&yyNFAy.-0.2y

QAb^ifkdtfqeqebClobj^kyKyClobj^kPrkaltk%/3+1)1/+2&yyNFAy.-0.4y
>Ab^ifkdtfqeqebLsboj^pqboyKyClobj^kPrkaltk%/3+1)1/+2&yyNFAy.-0.5y
@Ab^ifkdtfqeqebLsboj^pqboyKyHfiiLsboj^pqboDofkad^oo+Altkqebqrkkbi)ofdeqqebkibcq%/3+5)02+6&yyNFAy.-0.5y
@Kbrqo^ifwfkdqebKbqeboj^k`bopyKyHfiiqebKbqeboj^k`boplrqpfabqebjfkb^olrka%/5+5)05+2&yyNFAy.-0.2y
@>A^ohM^`qyKy>iiclrka^olrkaJ^k^clodb>o^%/3+2)06+3&yyNFAy.-05-y

@Qof^kdri^qflkMlfkqQtlyKyRpbqebXQof^kdri^qflkAbsf`bZ^kacfkaqebj^ohkb^oJ^k^clodb>o^%/5+6)1.+/&yyRy/6-.5yyNFAy.-/42y
Q>A^ohM^`qyKyH^vi^^k%01+5)05+/&yyNFAy.-05-y
QQof^kdri^qflkMlfkqQtlyKyTfkaQo^aboQrirj^k%01+3)04+6&+Phfmqebcliilt*rmyyNFAy.-/42y
QAb^ifkdtfqeqebLsboj^pqboyKyTfkaQo^aboQrirj^k%01+3)04+6&yyNFAy.-0.5y
QKbrqo^ifwfkdqebKbqeboj^k`bopyKyKbqebo*Pq^ihboL^wri%01+3)04+5&yyNFAy.-0.2y

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
