DugisGuideViewer:RegisterGuide("Borean Tundra (71-73)", "Dragonblight (73-75)", "Horde", "L", function()
return [[
AAA

C?lob^kQrkao^yKyQ^hbqebWbmmbifkcoljArolq^oql?lob^kQrkao^%1.+1).5&yyWyArolq^oyyNFAy..252y

cT^oplkdEliayKyQrofa^@liatfka%1-+1)2.+2&yyNFAy..252y
eT^oplkdEliayKyTfiif^jplk%1.+6)21+2&yyNFAy..252y

>Ebiip`ob^j$pSfdfiyKyT^oplkdOb`orfqjbkqLccf`bo%1.+3)20+6&yyNFAy..252y
QEbiip`ob^j$pSfdfiyKyD^oolpeEbiip`ob^j%1.+1)20+3&yyNFAy..252y
>QebAbcbkpblcT^oplkdEliayKyEfdeLsboiloaP^roc^kd%1.+1)20+4&yyNFAy..263y
QQebAbcbkpblcT^oplkdEliayKyLsboiloaO^wdlo%10+/)22+-&yyNFAy..263y
>Q^hfkd?^`hJfdeqpqlkbNr^oovyKyLsboiloaO^wdlo%10+/)22+-&yyNFAy..265y
>M^qfbk`bfp^Sfoqrbqe^qTbAlk$qKbbayKyNr^oqboj^pqboElidlqe%10+1)22+1&yyNFAy..3-3y
>Q^hbk_vqebP`lrodbyKyClobj^kJloqrrp%1/+/)23+/&yyNFAy..3..y

@Q^hbk_vqebP`lrodbyNFAy..3..yyKy?ob^hlmbkqebp^`p^olrka%1.+-)2/+-&qfiivlre^sb2cobbaT^oplkdMblkpy
@M^qfbk`bfp^Sfoqrbqe^qTbAlk$qKbbayNFAy..3-3yyKy@liib`qXT^oplkdJrkfqflkpZproolrkafkdqeb^ob^lc%1.+-)2/+-&y
@Q^hfkd?^`hJfdeqpqlkbNr^oovyNFAy..265yyKyCfkaqebjl_pfkqebNr^oov^olrka%1.+-)2/+-&y

QQ^hbk_vqebP`lrodbyKyClobj^kJloqrrp%1/+/)23+/&yyNFAy..3..y
QM^qfbk`bfp^Sfoqrbqe^qTbAlk$qKbbayKyNr^oqboj^pqboElidlqe%10+1)22+1&yyNFAy..3-3y
>?rovQelpb@l`hol^`ebpyKyNr^oqboj^pqboElidlqe%10+1)22+1&yyNFAy..3-5y
QQ^hfkd?^`hJfdeqpqlkbNr^oovyKyLsboiloaO^wdlo%10+/)22+-&yyNFAy..265y
>@rqqfkdLccqebPlro`byKyLsboiloaO^wdlo%10+/)22+-&yyNFAy..3-/y
>RkqliaQorqepyKyPe^altpq^ihbo?^oqerp%10+0)22+.&yyNFAy..3.1y

KKloqePfkhelibyNFAy..3-5yyNLyKloqeKbor_$^oPfkhelibAbpqolvba7.,.yyKyKloqebokJfdeqpqlkbNr^oov%1.+5)2-+4&yyRy014.-y
QRkqliaQorqepyKyPe^altpq^ihboIrqebo%1-+-)2/+.&yyNFAy..3.1y
>Kbor_$^oPb`obqpyKyPe^altpq^ihboIrqebo%1-+-)2/+.&yyNFAy..3.2y
KTbpqPfkhelibyNFAy..3-5yyNLyTbpqKbor_$^oPfkhelibAbpqolvba7.,.yyKyTbpqbokJfdeqpqlkbNr^oov%06+2)2/+5&yyRy014.-y
KPlrqePfkhelibyNFAy..3-5yyNLyPlrqeKbor_$^oPfkhelibAbpqolvba7.,.yyKyPlrqebokJfdeqpqlkbNr^oov%1.+5)25+5&yyRy014.-y
KB^pqPfkhelibyNFAy..3-5yyNLyB^pqKbor_$^oPfkhelibAbpqolvba7.,.yyKyB^pqbokJfdeqpqlkbNr^oov%11+.)24+0&yyRy014.-y
@?rovQelpb@l`hol^`ebpyKyMi^kqqebXPb^clofrjAbmqe@e^odb?rkaibpZfkqebdo^velibp^olrkaqebnr^oov+Kloqe%1.)2-&)B^pq%11)23&)Tbpq%06)2/&^kaPlrqe%1.)25&yyNFAy..3-5yyRy014.-y
@@rqqfkdLccqebPlro`byNFAy..3-/yyKyAbpqolv.-Kbor_$^oBddP^`pclrka^olrka%10+5)26+/&y

Q?rovQelpb@l`hol^`ebpyKyNr^oqboj^pqboElidlqe%10+1)22+1&yyNFAy..3-5y
QKbor_$^oPb`obqpyKyPe^altpq^ihbo?^oqerp%10+0)22+.&yyNFAy..3.2y
>Jbpp^dbqlEbiip`ob^jyKyPe^altpq^ihbo?^oqerp%10+0)22+.&yyNFAy..3.3y
Q@rqqfkdLccqebPlro`byKyLsboiloaO^wdlo%10+/)22+-&yyNFAy..3-/y
>TfkaJ^pqboQl$_loyKyLsboiloaO^wdlo%10+/)22+-&yyNFAy..301y
>Qll@ilpbClo@ljcloqyKyBkalo^e%1.+5)21+4&yyNFAy..241y
>OfabqlQ^rkh^$ibSfii^dbyKy>j_^pp^aloQ^ilkd^%1.+4)21+3&yyNFAy..555y
QJbpp^dbqlEbiip`ob^jyKyD^oolpeEbiip`ob^j%1.+1)20+3&yyNFAy..3.3y
>Obfkclo`bjbkqpFk`ljfkd+++yKyD^oolpeEbiip`ob^j%1.+1)20+3&yyNFAy..3.5y
>Ql?lo$dlolhLrqmlpq)Nrf`hivyKyP^ro^klhqebJvpqf`%1.+3)20+2&yyNFAy./153y
QTfkaJ^pqboQl$_loyKyTfkaJ^pqboQl$_lo%1/+3)22+2&)rpbqebbibs^qloyyNFAy..301y
>J^df`@^ombqOfabyKyTfkaJ^pqboQl$_lo%1/+3)22+2&yyNFAy..303y

QJ^df`@^ombqOfabyKyDlodbqeb@lompbdofkabo%0/+0)21+.&yyNFAy..303y
>Q^kh>fk$qDlkk^CfuFqpbicyKyDlodbqeb@lompbdofkabo%0/+0)21+.&yyNFAy..31/y
QQ^kh>fk$qDlkk^CfuFqpbicyKyJl_r%0/+.)21+0&yyNFAy..31/y
>Jl_r$pMkbrj^qf`Q^khQo^kpgfd^j^ofdyKyJl_r%0/+.)21+0&yyNFAy..310y
>PrmboPqolkdJbq^iMi^qbpyKyJl_r%0/+.)21+0&yyNFAy..311y
>FkqlqebJfpqyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..322y
>Eloklcqeb>k`fbkqJ^ofkboyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..33-y

@Jl_r$pMkbrj^qf`Q^khQo^kpgfd^j^ofdyNFAy..310yyKyCfkaqebXMkbrj^qf`Q^khQo^kpgfd^j^ofdZ^q%0/+1)16+.&y
>Bp`^mfkdqebJfpqyKyJllqllqebVlrkdbo%0.+6)2/+2&yyNFAy..331y
@PrmboPqolkdJbq^iMi^qbpyNFAy..311yyKy@liib`q.-XPrmboPqolkdJbq^iMi^qbpZclrka^iilsboqeb_b^`e^q%/6+-)2/+3&y
@Eloklcqeb>k`fbkqJ^ofkboyNFAy..33-yyKyHbbmhfiifkdHs^iafoJfpqtb^sbo$p^olrka%/6+-)2/+3&rkqfiqebXEloklcqeb>k`fbkqJ^ofkboZaolmpy
@FkqlqebJfpqyNFAy..322yyKyHfiiHs^iafo%/6+-)2/+3&qfiivlre^sbbklrdeXQrph^ooObif`pZy

QBp`^mfkdqebJfpqyKyBiaboJllqll%0.+4)21+1&yyNFAy..331y
QJl_r$pMkbrj^qf`Q^khQo^kpgfd^j^ofdyKyJl_r%0/+.)21+0&yyNFAy..310y
QPrmboPqolkdJbq^iMi^qbpyKyJl_r%0/+.)21+0&yyNFAy..311y
>Q^khp^ilq+++yKyJl_r%0/+.)21+0&yyNFAy..32.y
QFkqlqebJfpqyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..322y
>?rokfkBccfdvyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..323y
QEloklcqeb>k`fbkqJ^ofkboyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..33-y
>Lo^_rpqebEbijpj^kyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..33.y
QQ^khp^ilq+++yKyDlodbqeb@lompbdofkabo%0/+0)21+.&yyNFAy..32.y
>QebMi^fkplcK^p^jyKyDlodbqeb@lompbdofkabo%0/+0)21+.&yyNFAy..32/y

K?lo$pE^jjboyNFAy..323yyNLy?lo$pE^jjboabpqolvba7.,.yyKyLkqeb`l^pq%/6+4)2/+6&yyRy0150-y
KQebHroAo^hh^oyNFAy..323yyNLyQebHroAo^hh^oabpqolvba7.,.yyKyLkqeb`l^pq%0-+6)15+6&yyRy0150-y
KQebPbombkq$pJ^tyNFAy..323yyNLyQebPbombkq$pJ^tabpqolvba7.,.yyKyLkqeb`l^pq%0.+2)15+0&yyRy0150-y
K?lo$p>ksfiyNFAy..323yyNLy?lo$p>ksfiabpqolvba7.,.yyKyLkqeb`l^pq%0-+.)3.+3&yyRy0150-y
@Lo^_rpqebEbijpj^kyNFAy..33.yyKyPrjjlkLo^_rpqebEbijpj^ktfqeqebXEloklcqeb>k`fbkqJ^ofkboZ^qqebbkalccT^oplkdGbqqv%/3+3)21+3&)qebkhfiiefjyyRy01511y

Q?rokfkBccfdvyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..323y
QLo^_rpqebEbijpj^kyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..33.y
>PbbhLrqH^orhyKyT^iqlolcM^i$b^%0/+0)21+0&yyNFAy..33/y

@QebMi^fkplcK^p^jyNFAy..32/yyKyElmfk^pfbdbq^kh^q%0.+3)22+2&^kaeb^aplrqe*b^pqql%03+3)3.+.&)hfiiqebP`lrodbproolrkafkdqeb^ob^^kap^sbfkgrobajl_py

QObfkclo`bjbkqpFk`ljfkd+++yKyPe^altpq^ihboF`hlofp%05+.)2/+2&yyNFAy..3.5y
>QebT^oplkdC^ojpyKyPe^altpq^ihboF`hlofp%05+.)2/+2&yyNFAy..353y
>Jbo`fcriCobbaljyKyPe^altpq^ihbo@^k^ofrp%05+-)2/+3&yyNFAy..343y
>A^jkbaCfiqevPtfkbyKyC^ojboQlom%04+6)2/+1&yyNFAy..355y

@QebT^oplkdC^ojpyNFAy..353yyKyP`lrqQlom$pC^oj%03+4)2/+3&)T^oplkdDo^k^ov%01+6)21+6&^kaqebT^oplkdPi^rdeqboelrpb%06+/)14+2&y
@Jbo`fcriCobbaljyNFAy..343yyKyHfiiBk$hfi^eKb`oliloa$p^kaT^oplkd>_boo^qflk$p^olrka%04+/)2-+2&clohbvpqlrkil`hqebP`lrodbMofplkbopy
@A^jkbaCfiqevPtfkbyNFAy..355yyKy.-RkifsfkdPtfkb^olrka%03+.)26+.&y

QQebT^oplkdC^ojpyKyPe^altpq^ihboF`hlofp%05+.)2/+2&yyNFAy..353y
>DbqqlDbqovyKyPe^altpq^ihboF`hlofp%05+.)2/+2&yyNFAy..4-0y
QJbo`fcriCobbaljyKyPe^altpq^ihbo@^k^ofrp%05+-)2/+3&yyNFAy..343y
QA^jkbaCfiqevPtfkbyKyC^ojboQlom%04+6)2/+1&yyNFAy..355y
>?ofkd$Bj?^`h>ifsbyKyC^ojboQlom%04+6)2/+1&yyNFAy..36-y

@?ofkd$Bj?^`h>ifsbyNFAy..36-yyRy01621yyKyRpbXQlom$pHlalPk^ccibZlk5Fkcb`qbaHlal?b^pqp^olrka%03+.)26+.&y

Q?ofkd$Bj?^`h>ifsbyKyC^ojboQlom%04+6)2/+1&yyNFAy..36-y

QDbqqlDbqovyKyPe^altpq^ihboDbqov%01+3)13+1&yyNFAy..4-0y
>CllifpeBkab^slopyKyPe^altpq^ihboDbqov%01+3)13+1&yyNFAy..4-2y

@CllifpeBkab^slopyNFAy..4-2yyKy>qq^`hS^ofarpqebCibkpbo%01+5)13&)_rqEfdeLsboiloaP^roc^kdalbpjlpqlcqebtlohclovlr)grpq^ppfpqy

QQebMi^fkplcK^p^jyKyD^oolpeEbiip`ob^j%1.+1)20+3&yyNFAy..32/y
QCllifpeBkab^slopyKyD^oolpeEbiip`ob^j%1.+1)20+3&yyNFAy..4-2y
>Kloh?illacobkwv$p@e^odbyKyD^oolpeEbiip`ob^j%1.+1)20+3&yyNFAy..4-6y
QKloh?illacobkwv$p@e^odbyKyT^oabkKloh?illacobkwv%10+4)21+2&yyNFAy..4-6y
>@lt^oaAbifsbov+++Rkabo0-Jfkrqbplofq$pCobbyKyT^oabkKloh?illacobkwv%10+4)21+2&yyNFAy..4..y

@@lt^oaAbifsbov+++Rkabo0-Jfkrqbplofq$pCobbyNFAy..4..yyKy>qqeb`olppol^apkloqe*b^pqlcT^oplkdElia%22+0)2-+6&+RpbqebXT^oplkdCi^obDrkZyyRy0164.y

Q@lt^oaAbifsbov+++Rkabo0-Jfkrqbplofq$pCobbyKyP`lrqQrkdlh%2/+2)2.+3&yyNFAy..4..y
>SbojfkBuqbojfk^qflkyKyP`lrqQrkdlh%2/+2)2.+3&yyNFAy..4.1y
>QebTlkaolrp?illapmlobyKy?illaj^dbI^rofqe%2/+.)2/+2&yyNFAy..4.3y

@QebTlkaolrp?illapmlobyNFAy..4.3yyKy@liib`q.-X?illapmlob@^ombipZlkqebmi^kqp^olrka%2.+.)2.+-&y
@SbojfkBuqbojfk^qflkyNFAy..4.1yyKyCfkaqebjl_pproolrkafkd%2.+.)2.+-&y

QQebTlkaolrp?illapmlobyKy?illaj^dbI^rofqe%2/+.)2/+2&yyNFAy..4.3y
>MliibkcoljqebPlro`byKy?illaj^dbI^rofqe%2/+.)2/+2&yyNFAy..4.4y

QSbojfkBuqbojfk^qflkyKyP`lrqQrkdlh%2/+2)2.+3&yyNFAy..4.1y

>J^ppfsbJlqeLjbibq<yKyJ^ppfsbDiltfkdBdd%15+2)26+.&yyNFAy..4/1y

@MliibkcoljqebPlro`byNFAy..4.4yyKyHfiijlqep^olrka%2/+2)2/+/&ql`liib`q2X?illapmlobJlqeMliibkZy

QJ^ppfsbJlqeLjbibq<yKy?illaj^dbI^rofqe%2/+.)2/+2&yyNFAy..4/1y
QMliibkcoljqebPlro`byKy?illaj^dbI^rofqe%2/+.)2/+2&yyNFAy..4.4y
>>Prfq^_ibQbpqPr_gb`qyKy?illaj^dbI^rofqe%2/+.)2/+2&yyNFAy..4.6y
@>Prfq^_ibQbpqPr_gb`qyNFAy..4.6yyRy01645yyKyRpbqebdfsbkXMliifk^qba?illapmlobCiltboZ^q%2/)2/&y
Q>Prfq^_ibQbpqPr_gb`qyKy?illaj^dbI^rofqe%2/+.)2/+2&yyNFAy..4.6y
>QebFks^pflklcD^jjlqeyKy?illaj^dbI^rofqe%2/+.)2/+2&yyNFAy..4/-y
QQebFks^pflklcD^jjlqeyKyMofj^iJfdeqelok%2/+/)2/+5&yyNFAy..4/-y
>D^jjlqeo^qebQlojbkqloyKyMofj^iJfdeqelok%2/+/)2/+5&yyNFAy..4/.y

@D^jjlqeo^qebQlojbkqloyNFAy..4/.yyRy01646yyKyPlrqetbpqfkqlqeb`^sb%12+6)3.+2&+D^jjlqeo^qebQlojbkqlofpofdeq^qqeb_lqqlj+RpbqebXMlr`elc@orpeba?illapmlobZlk^kvlcqebbifqbpy

QD^jjlqeo^qebQlojbkqloyKyMofj^iJfdeqelok%2/+/)2/+5&yyNFAy..4/.y
>QolmefbplcD^jjlqeyKyMofj^iJfdeqelok%2/+/)2/+5&yyNFAy..4//y

QQolmefbplcD^jjlqeyKyD^oolpeEbiip`ob^j%1.+1)20+3&yyNFAy..4//y
>Ebiip`ob^j$p@e^jmflkyKyD^oolpeEbiip`ob^j%1.+1)20+3&yyNFAy..6.3y

QPbbhLrqH^orhyKyH^orh%14+/)42+2&yyNFAy..33/y
>H^orh$pL^qeyKyH^orh%14+/)42+2&yyNFAy..3.0y
>@orbiqvlcqebHs^iafoyKy@^mqrobaQrph^ooMofplkbo%11+/)44+6&+HfiiqebHs^iafo^olrkaqebcfdeqfkdQrph^ooqllmbkyyNFAy./14.y

@H^orh$pL^qeyNFAy..3.0yyKyAltklkOfmi^pePqo^ka^olrka%13+-)42+-&y

Q@orbiqvlcqebHs^iafoyKyH^orh%14+/)42+2&yyNFAy./14.y
QH^orh$pL^qeyKyH^orh%14+/)42+2&yyNFAy..3.0y
>D^jbiqeb@orbiyKyH^orh%14+/)42+2&yyNFAy..3.6y

@D^jbiqeb@orbiyNFAy..3.6yyKyFk^`^sbaltklkqeb_b^`e%13+0)45+5&y
QD^jbiqeb@orbiyKyH^orh%14+/)42+2&yyNFAy..3.6y

>>C^qebo$pTloapyKyH^orh%14+/)42+2&yyNFAy..3/-y

Q>C^qebo$pTloapyKySbbeg^%10+3)5-+3&yyNFAy..3/-y
>QebQofabkqlcK^w$g^kyKySbbeg^%10+3)5-+3&yyNFAy..3/2y

@QebQofabkqlcK^w$g^kyNFAy..3/2yyKyPtfjplrqeb^pqqlOfmi^peOrfkpql%2-+6)6-+2&)tlohvlrot^vrmqlqebkloqeb^pq_rfiafkd%21+6)55+5&y

QQebQofabkqlcK^w$g^kyKySbbeg^%10+3)5-+3&yyNFAy..3/2y
>QebBjfpp^ovyKySbbeg^%10+3)5-+3&yyNFAy..3/3y

@QebBjfpp^ovyNFAy..3/3yyKyPtfj_^`hqlqebi^odbf`b_bod^qOfmi^peOrfkp%2.+1)55+/&+Afsbaltk)rpbqebXQofabkqlcK^w$g^kZlkIbsfolqe^kahfiiefjyyRy0252-y

QQebBjfpp^ovyKyH^orh%14+/)42+2&yyNFAy..3/3y

Q>JfppflkPq^qbjbkqyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..531y
>B^oplcLroBkbjfbpyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..533y
>EbimQelpbQe^q@^kklqEbimQebjpbisbpyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..543y
>E^mmv^p^@i^jyKyEfbolme^kq@bkfrp%24+0)11+.&yyNFAy..536y
>Kba)IloalcOefklp+++yKyHfiifkdboqebAbkT^q`ebo%24+-)11+0&yyNFAy..551y
>RkcfqcloAb^qeyKyW^w^%23+5)11+.&yyNFAy..532y

@E^mmv^p^@i^jyNFAy..536yyKyTbpq^qI^hbHrj$rv^^olrka%2.+3)13+6&y
@Kba)IloalcOefklp+++yNFAy..551yyKyM^qolip^olrkaqebtbpqpfablcqebi^hb%14+/)1.+/&+Dolrmnrbpq_rqplil^_ib^p`^k_b@@$ay
@EbimQelpbQe^q@^kklqEbimQebjpbisbpyNFAy..543yyRy02//5yyKyRpbqebXA+B+E+Q+>+Qo^mPj^peboZlkqebqo^mpb^pqlcqebnr^oov^olrka%21+.)1.+-&y
@RkcfqcloAb^qeyNFAy..532yyKyRpbXMfiblcC^hbCropZkbuqqlqo^mp^olrka%23+6)2.+0&yyRy02./4y
@B^oplcLroBkbjfbpyNFAy..533yyKyHfiiafsbopfkI^hbHrj$rv^%2.+3)13+6&rkqfivlre^sbbklrdeb^opy

QRkcfqcloAb^qeyyKyW^w^%23+5)11+.&yyNFAy..532y
>Qeb@riibo@ljbqeyyKyW^w^%23+5)11+.&yyNFAy..535y
QB^oplcLroBkbjfbpyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..533y
QEbimQelpbQe^q@^kklqEbimQebjpbisbpyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..543y
>Her$klhTfiiHkltyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..545y
QE^mmv^p^@i^jyKyEfbolme^kq@bkfrp%24+0)11+.&yyNFAy..536y
>Qeb>_^kalkbaOb^`eyKyEfbolme^kq@bkfrp%24+0)11+.&yyNFAy..54-y
QKba)IloalcOefklp+++yKyHfiifkdboqebAbkT^q`ebo%24+-)11+0&yyNFAy..551y

QHer$klhTfiiHkltyKyHer$klhqeb?bebjlqe%26+2)0-+3&yyNFAy..545y
>H^tqebJ^jjlqeAbpqolvboyKyHer$klhqeb?bebjlqe%26+2)0-+3&yyNFAy..546y

@H^tqebJ^jjlqeAbpqolvboyNFAy..546yyKyElmlk^_rii^kaHfiiH^tqebJ^jjlqeAbpqolvbo^qH^t$pOllpq%20+4)/1+1&+Afpjlrkqlk`beb$pab^aqlillqqebfqbjy
@Qeb@riibo@ljbqeyNFAy..535yyKyHfiiH^obk^qqebc^oplrqebadblcqebcfbia%24+/)23+-&y

QQeb>_^kalkbaOb^`eyKyEfbolme^kqIf^kao^%24+5)22+.&yyNFAy..54-y
>KlqLkLroT^q`eyKyEfbolme^kqIf^kao^%24+5)22+.&yyNFAy..54.y

@KlqLkLroT^q`eyNFAy..54.yyKyQlqebplrqeb^pqpq^oqfkd^q%25+-)24+-&y

QKlqLkLroT^q`eyKyEfbolme^kqIf^kao^%24+5)22+.&yyNFAy..54.y
>QebKbc^oflrp@i^jJ^pqbo+++yKyEfbolme^kqIf^kao^%24+5)22+.&yyNFAy..54/y

@QebKbc^oflrp@i^jJ^pqbo+++yNFAy..54/yyKyHfii@i^jJ^pqboHqlqebplrqetbpq^qqebpefmtob`h%3.+3)33+1&y

QQeb@riibo@ljbqeyyKyW^w^%23+5)11+.&yyNFAy..535y
QH^tqebJ^jjlqeAbpqolvboyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..546y
QQebKbc^oflrp@i^jJ^pqbo+++yKyEfbolme^kq@bkfrp%24+0)11+.&yyNFAy..54/y
>Qeb>pp^ppfk^qflklcE^oliaI^kbyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..56/y

@Qeb>pp^ppfk^qflklcE^oliaI^kbyNFAy..56/yyKyE^oliaI^kbfpqlqebtbpq_vqebi^hb%16+0)1-+2&+?b^qefjaltkqfiigrpq^_lsbe^iceb^iqeqebkrpbqebX@bk^oflkElokZql`^iifk^pq^jmbabqlcfkfpeefjlccyyRy02/60y

QQeb>pp^ppfk^qflklcE^oliaI^kbyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..56/y

>QebElkloba>k`bpqlopyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-2y
>Ob`i^fjfkdqebNr^oovyKyBq^orh%21+0)03+/&yyNFAy..3./y

@QebElkloba>k`bpqlopyNFAy..3-2yyKyCfkaBiaboQ^hobq%2/+0)0.+/&)BiaboP^d^kf%2/+5)01+.&^kaBiaboHbprh%2-+5)0/+1&y
@Ob`i^fjfkdqebNr^oovyNFAy..3./yyKyClrka^olrkaqebnr^oov^q%2/+2)00+/&y

QQebElkloba>k`bpqlopyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-2y
>QebIlpqPmfofqpyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-4y
QOb`i^fjfkdqebNr^oovyKyBq^orh%21+0)03+/&yyNFAy..3./y
>E^jmbofkdQebfoBp`^mbyKyBq^orh%21+0)03+/&yyNFAy..3.4y

@E^jmbofkdQebfoBp`^mbyNFAy..3.4yyKyHfii?boviOb`i^fjbopcloXDkljfpeDobk^abpZ)qebkrpbqebj^qqebqeobbcil^qfkdmi^qclojp*B^pq%2/+1)02+0&)Tbpq%2-+2)01+5&^kaKloqe%2.+6)0.+6&yyRy0144/y
@QebIlpqPmfofqpyNFAy..3-4yyKyHfiiqeb?boviElrkapqebkrpbqebX@lobplcJ^if`bZlkqebQrph^oofkqebnr^oov%2/+2)00+/&yyRy014..y

QQebIlpqPmfofqpyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-4y
>Mf`hfkdRmqebMfb`bpyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-6y
QE^jmbofkdQebfoBp`^mbyKyBq^orh%21+0)03+/&yyNFAy..3.4y
>>Sfpfqqlqeb@ro^qloyKyBq^orh%21+0)03+/&yyNFAy..3/0y

@>Sfpfqqlqeb@ro^qloyNFAy..3/0yyKyHfii@ro^qloFkpfsfrp^q%2-+.)0/+4&y
@Mf`hfkdRmqebMfb`bpyNFAy..3-6yyKyDbq3XQrph^ooOfqr^iL_gb`qpZ)clrka^olrkaqebnr^oov%2/+2)00+/&y

QMf`hfkdRmqebMfb`bpyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-6y
>Ib^afkdqeb>k`bpqlopEljbyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3.-y
Q>Sfpfqqlqeb@ro^qloyKyBq^orh%21+0)03+/&yyNFAy..3/0y

@Ib^afkdqeb>k`bpqlopEljbyNFAy..3.-yyKyRpbqebXQrph^ooOfqr^iL_gb`qZ^qb^`elcBiaboQ^hobq%2/+0)0.+/&)BiaboP^d^kf%2/+5)01+.&^kaBiaboHbprh%2-+5)0/+1&yyRy014.2y

QIb^afkdqeb>k`bpqlopEljbyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3.-y

QQll@ilpbClo@ljcloqyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..241y

c>j_boIbadbyKyProofpqo^pw%12+0)01+2&yyNFAy..254y

>Mofplk?ob^hyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..254y
>JlkfqlofkdqebOfcq7@ibcq`ifcc>klj^ivyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy..243y

@JlkfqlofkdqebOfcq7@ibcq`ifcc>klj^ivyNFAy..243yyKyPlrqetbpq)m^pq?boviMlfkq)ptfjqlqebTbpqofcq%01+1)1/+.&^karpbqebX>o`^kljbqboZyyRy01336y
@Mofplk?ob^hyNFAy..254yyKy>q?boviMlfkq%1/+4)03+6&)hfii?boviJ^dbErkqbopcloqebhbvpy

QJlkfqlofkdqebOfcq7@ibcq`ifcc>klj^ivyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy..243y
>JlkfqlofkdqebOfcq7Prkaboba@e^pjyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy..25/y
QMofplk?ob^hyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..254y
>>_ar`qflkyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..26-y

@>_ar`qflkyNFAy..26-yyKyDlcfka^?boviPlo`bobo%1/+3)05+1&)_b^qefj^_fq)qebkrpbqebX>o`^kb?fkaboZlkefjyyRy0136.y

Q>_ar`qflkyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..26-y
>Qeb?lob^kFknrfpfqflkyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..313y
QQeb?lob^kFknrfpfqflkyKyIf_o^of^kKloj^kqfp%13+1)0/+6&yyNFAy..313y
>Qeb>oqlcMbopr^pflkyKyIf_o^of^kKloj^kqfp%13+1)0/+6&yyNFAy..315y
@Qeb>oqlcMbopr^pflkyNFAy..315yyKyRpbqebXKbro^iKbbaiboZlkqebmofplkbofkqebqltboyyRy015..y
QQeb>oqlcMbopr^pflkyKyIf_o^of^kKloj^kqfp%13+1)0/+6&yyNFAy..315y
>Pe^ofkdFkqbiifdbk`byKyIf_o^of^kKloj^kqfp%13+1)0/+6&yyNFAy..330y
QPe^ofkdFkqbiifdbk`byKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..330y
>>O^`b>d^fkpqQfjbyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..34.y

@JlkfqlofkdqebOfcq7Prkaboba@e^pjyNFAy..25/yyKyPtfjkloqeb^pq)afsbaltkqlqebPrkaboba@e^pj%11+-)/5+3&)rpbqebX>o`^kljbqboZyyRy01336y
@>O^`b>d^fkpqQfjbyNFAy..34.yyKyRpbqebX?boviPefbiaAbqlk^qloZlkqebi^odbolrkami^qcloj%1.+5)06+/&^kahfiiFknrfpfqloP^io^kayyRy01564y

QJlkfqlofkdqebOfcq7Prkaboba@e^pjyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy..25/y
>JlkfqlofkdqebOfcq7Tfkqbocfk@^sbokyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy./4/5y
Q>O^`b>d^fkpqQfjbyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..34.y
>ObclodfkdqebHbvyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..346y
QObclodfkdqebHbvyKyProofpqo^pw%12+0)01+2&yyNFAy..346y
>Q^hfkdTfkdyKyProofpqo^pw%12+0)01+2&yyNFAy..35-y
QQ^hfkdTfkdyKyT^oj^db>kwfj%13+1)04+0&yyNFAy..35-y
>Obp`rfkdBs^kloyKyT^oj^db>kwfj%13+1)04+0&yyNFAy..35.y
QObp`rfkdBs^kloyKy>o`ej^dbBs^klo%13+1)0/+2&yyNFAy..35.y
>Ao^dlkpmb^hyKy>o`ej^dbBs^klo%13+1)0/+2&yyNFAy..35/y
QAo^dlkpmb^hyKyProofpqo^pw%12+0)01+2&yyNFAy..35/y
>Qo^sbopfkdqebOfcqyKyProofpqo^pw%12+0)01+2&yyNFAy..400y

CQo^kpfpqrpPefbiayKyProofpqo^pw%12+1)01+2&yyWy?lob^kQrkao^yyNFAy..400y

QQo^sbopfkdqebOfcqyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..400y
>Ob^afkdqebJbqbopyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6--y
>Pb`obqplcqeb>k`fbkqpyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6.-y
>Krqpclo?boofbpyKyIf_o^of^kPboo^e%00+2)01+1&yyNFAy..6./y
>?^pf`Qo^fkfkdyKyO^bilo^pw%00+0)01+2&yyNFAy..6.5y

O@lia^oo^yKyQ^ihqlIf_o^of^kQf^obclo^qbibmloq%00+0)01+.&yyNFAy..61.y

@Ob^afkdqebJbqbopyNFAy..6--yyKyCfkaqeblo_pqlob^a^qqebkloqe%0.+0)/-+0&)tbpq%//+1)/1+/&)plrqe%/5+0)01+6&)^kaaltkkb^oqebKburp%/5+0)/5+2&y
@Pb`obqplcqeb>k`fbkqpyNFAy..6.-yyKyHfiiJ^df`*_lrka>k`fbkq^olrka%/4+6)0/+1&^kaDi^`f^i>k`fbkq%0.+3)/1+1&^ka%/.+0)0.+6&y
@Krqpclo?boofbpyNFAy..6./yyKyDbq.-XColpq_boofbpZpmob^aqeolrdelrq@lia^oo^%02)/3&)`liib`qqebjtefibnrbpqfkdy
@?^pf`Qo^fkfkdyNFAy..6.5yyKyHfii.-@lia^oo^Pmbiitb^sbopclrka^olrka%0/+0)/5+4&y
>Mrwwifkd+++yNFAy..61.yyKyQebfqbjXP`fkqfii^qfkdCo^djbkqZpq^oqpnrbpq*aolmmba_v@lia^oo^Pmbii_fkabop^olrka%00)/5&yyRy02315y

QOb^afkdqebJbqbopyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6--y
QPb`obqplcqeb>k`fbkqpyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6.-y
QKrqpclo?boofbpyKyIf_o^of^kPboo^e%00+2)01+1&yyNFAy..6./y
>HbbmqebPb`obqP^cbyKyIf_o^of^kPboo^e%00+2)01+1&yyNFAy..6.1y
Q?^pf`Qo^fkfkdyKyO^bilo^pw%00+0)01+2&yyNFAy..6.5y
>E^q`efkd^Mi^kyKyO^bilo^pw%00+0)01+2&yyNFAy..603y
QMrwwifkd+++yKyO^bilo^pw%00+0)01+2&yyNFAy..61.y
>Qeb@biiyKyO^bilo^pw%00+0)01+2&yyNFAy..610y

@Qeb@biiyNFAy..610yyKyHfiiT^o_ofkdboDlobao^hqlqebtbpq%/1+/)/5+6&^kaDbkbo^i@borib^kqlqebkloqe%/4+2)/-+4&y
@E^q`efkd^Mi^kyNFAy..603yyKyHfii@lia^oo^Tvojhfkproolrkafkd@lia^oo^cloqebfoXColwbk>ubpZ)qebkrpbqebjlkqebbddpkb^oqebKburp%/5+2)/5+6&yyRy02253y
@HbbmqebPb`obqP^cbyNFAy..6.1yyKyHfii>o`^kbPbombkqpkb^oqebKburp%/5+2)/5+6&y

QE^q`efkd^Mi^kyKyO^bilo^pw%00+0)01+2&yyNFAy..603y
>Ao^hbErkqyKyO^bilo^pw%00+0)01+2&yyNFAy..6.6y
QQeb@biiyKyO^bilo^pw%00+0)01+2&yyNFAy..610y
>Hbofpqo^pw^yKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..613yyRy0234.y
QHbofpqo^pw^yKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..613yyRy0234.y
>?^fq^kaPtfq`eyKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..62.yyRy0234.y
QHbbmqebPb`obqP^cbyKyIf_o^of^kPboo^e%00+2)01+1&yyNFAy..6.1y

@?^fq^kaPtfq`eyNFAy..62.yyKyIllqqebmromib`ovpq^ipkb^oqebKburp%/5+2)/5+6&y
@Ao^hbErkqyNFAy..6.6yyRy022-3yyKyCfka^KburpAo^hbE^q`eifkdcivfkd^olrkaqlqebtbpqlcqebKburp+EfqfqtfqeXO^bilo^pw$pPmb^oZrkqfi`lkqoliibaqebkabifsboqlO^bilo^pw%00+0)01+2&tfqefk0jfkrqbpy

QAo^hbErkqyKyO^bilo^pw%00+0)01+2&yyNFAy..6.6y
>@o^`hfkdqeb@labyKyO^bilo^pw%00+0)01+2&yyNFAy..60.y
@@o^`hfkdqeb@labyNFAy..60.yyKyHfiiFknrfpfqlo@^ibo^pqlqebkloqe%0/+5)/4+5&+XPefjjbofkdOrkbpZaolmcoljqeb@lia^oo^Pmbii_fkabop^olrka%00)0-&y
Q?^fq^kaPtfq`eyKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..62.yyRy0234.y
>P^o^dlp^$pBkayKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..624yyRy0234.y

@P^o^dlp^$pBkayNFAy..624yyKyQ^ihqlHbofpqo^pw^clo^qbibmloq+RpbqebX>o`^kbMltboCl`rpZ)qebkhfiieboyyRy0236-y
QP^o^dlp^$pBkayKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..624yyRy0234.y
>JrpqbofkdqebObapyKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZqlprjjlkeboyyNFAy..634yyRy0234.y

QJrpqbofkdqebObapyKyO^bilo^pw%00+0)01+2&)Hbofpqo^pw^tfiimloqvlr_^`hyyNFAy..634y
>PmofkdfkdqebQo^myKyO^bilo^pw%00+0)01+2&yyNFAy..636y

Q@o^`hfkdqeb@labyKyO^bilo^pw%00+0)01+2&yyNFAy..60.y
@PmofkdfkdqebQo^myNFAy..636yyKyEb^aqlKloqe*Tbpqbkqo^k`blcqebKburp^q%/2+5)//+3&+RpbXO^bilo^pw$Pm^ohZ_bprobqlpq^v`ilpbqlHbofpqo^pw^yyRy1162-y
QPmofkdfkdqebQo^myKyO^bilo^pw%00+0)01+2&yyNFAy..636y

QQl?lo$dlolhLrqmlpq)Nrf`hivyKyPmfofqQ^ihboPk^oic^kd%2-+0)6+5&yyNFAy./153y

c?lo$dlolhLrqmlpqyKyHfj_fw^%16+3)..+-&yyNFAy..3/1y

>QebPhvTfiiHkltyKyPmfofqQ^ihboPk^oic^kd%2-+0)6+5&yyNFAy..3/1y
>ObmloqqlPqbbig^t$p@^o^s^kyKyLsboiloa?lo$dlolh%16+3).-+4&yyNFAy..26.y
>HfkdJodi*JodiyKyPrmmivJ^pqboQ^w$fpef%16+-).-+0&yyNFAy..4-/y

QQebPhvTfiiHkltyKyFjmbob^k%13+3)6+1&yyNFAy..3/1y
>?lfifkdMlfkqyKyFjmbob^k%13+3)6+1&yyNFAy..3/4y

@?lfifkdMlfkqyNFAy..3/4yyKy@erokfpclrka^q%12+6)./+0&^kaPfjjbofpqlqebb^pqlc@erok^q%2-+3).1+6&y

Q?lfifkdMlfkqyKyFjmbob^k%13+3)6+1&yyNFAy..3/4y
>JlqbplcqebBko^dbayKyFjmbob^k%13+3)6+1&yyNFAy..316y

@JlqbplcqebBko^dbayNFAy..316yyKyHfiiqebBko^dbaQbjmbpqp^olrka%10+5)6+.&ql`liib`q2XQbjmbpqJlqbpZy

QJlqbplcqebBko^dbayKyFjmbob^k%13+3)6+1&yyNFAy..316y
>ObqrokqlqebPmfofqQ^ihboyKyFjmbob^k%13+3)6+1&yyNFAy..3/6y

QHfkdJodi*JodiyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..4-/y
>Ib^okfkdql@ljjrkf`^qbyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..24.y

@Ib^okfkdql@ljjrkf`^qbyNFAy..24.yyKyAfsbaltkqlqebTbpqofcq%1/+4).2+5&)hfiiqebP`^iabo^karpbXQebHfkd$pBjmqv@lk`eZyyRy01265y

QIb^okfkdql@ljjrkf`^qbyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..24.y
>Tfkqbocfk@ljjbo`byKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..226y

@Tfkqbocfk@ljjbo`byNFAy..226yyKyAfsbcloXTfkqbocfk@i^jpZlocfkaqebpb^olrkaqeb`^jm^q%1-+/).3+-&y

QTfkqbocfk@ljjbo`byKy>eirodido%10+-).0+5&yyNFAy..226y
>QebjyKy?odijrodi%1/+6).0+4&yyNFAy..23.y
>LeKlbp)qebQ^amlibpyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..23-y

@LeKlbp)qebQ^amlibpyNFAy..23-yyKyLmbkrmqeb`^dbp^olrka%1.+-).2+/&^kacobb/-TfkqbocfkQ^amlibpy
@JlkfqlofkdqebOfcq7Tfkqbocfk@^sbokyNFAy./4/5yyKyEb^a^`olppqlqebTfkqbocfk@^sbokp%06+6)/-+.&)rpbqebX>o`^kljbqboZyyRy01336y
@QebjyNFAy..23.yyKyHfiiqebjroil`p^olrka%1.+-).2+/&y

QQebjyKy?odijrodi%1/+6).0+4&yyNFAy..23.y
QLeKlbp)qebQ^amlibpyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..23-y
>F$j?bfkd?i^`hj^fiba?vJv@ib^kboyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..23/y
QF$j?bfkd?i^`hj^fiba?vJv@ib^kboyKyJojodijo%1/+-)./+5&yyNFAy..23/y
>DojjroddiiJoiiddoiDioddiyKyJojodijo%1/+-)./+5&yyNFAy..230y
>Pr``ribkqLo`^PqbtyKy@ib^sbo?jrodi_oj%1/+-).0+.&yyNFAy..231y

@DojjroddiiJoiiddoiDioddiyNFAy..230yyKyKloqe^olrkaDifjjbo?^v%06+0)4+6&y
@Pr``ribkqLo`^PqbtyNFAy..231yyKyHfiiqeblo`^p^olrkaDifjjbo?^v%1-)..&)clo4XPr``ribkqLo`^?ir__boZy

QDojjroddiiJoiiddoiDioddiyKyJojodijo%1/+-)./+5&yyNFAy..230y
>QebPm^obPrfqyKyJojodijo%1/+-)./+5&yyNFAy..232y
QPr``ribkqLo`^PqbtyKy@ib^sbo?jrodi_oj%1/+-).0+.&yyNFAy..231y
QQebPm^obPrfqyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..232y
>Proobkabo+++KlqyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..233y

>Hbvj^pqboRojdodiyKyDiodiodio%04+5)/0+.&yyNFAy..236y

@Hbvj^pqboRojdodiyNFAy..236yyKyEb^acroqeboaltk)hfiiHbvj^pqboRojdodi%06+0)/0+2&y
@Proobkabo+++KlqyNFAy..233yyRy013/-yyKyEb^alsboqlqeb`^sb)rpbXHfkdJodi*Jodi$pPm^obPrfqZ^kahfii@i^ufjrp%04+4)/4+.&y

QHbvj^pqboRojdodiyKyDiodiodio%04+5)/0+.&yyNFAy..236y
>Bp`^mbcoljqebTfkqbocfk@^sbokpyKyIroddi_o%04+5)/0+-&yyNFAy..24-y

@Bp`^mbcoljqebTfkqbocfk@^sbokpyNFAy..24-yyKyBp`loqIroddi_o%04+5)/0+-&lrqlcqeb@^sbokpy

QBp`^mbcoljqebTfkqbocfk@^sbokpyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..24-y
QProobkabo+++KlqyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..233y

QObmloqqlPqbbig^t$p@^o^s^kyKyDorkqO^dbcfpq%15+2).6+1&yyNFAy..26.y
>QebElklobaAb^ayKyDorkqO^dbcfpq%15+2).6+1&yyNFAy..260y
>MrqQebjqlObpqyKyDorkqO^dbcfpq%15+2).6+1&yyNFAy..261y
>TbPqofhbyNFAy..26/yyKyIlkdorkkboMolraellc%15+1).6+4&y

@QebElklobaAb^ayNFAy..260yyRy0136/yyKyRpbXO^dbcfpq$pQlo`eZlkqeb_lafbp^olrka%2-+1)/1+1&y
@TbPqofhbyNFAy..26/yyKy>ppfpqIlkdorkkboMolraellc%15+1).6+4&tefibebmoldobppbplkefp^pp^riqy
@MrqQebjqlObpqyNFAy..261yyKy>e^kacrilcjl_ppelriae^sb_bbkhfiibatefibalfkdqebnrbpqTbPqofhb)hfiiobj^fkfkdjl_p^olrka%2-+1)/1+1&fckbbabay

QQebElklobaAb^ayKyDorkqO^dbcfpq%15+2).6+1&yyNFAy..260y
QMrqQebjqlObpqyKyDorkqO^dbcfpq%15+2).6+1&yyNFAy..261y

QTbPqofhbyKyLsboiloa?lo$dlolh%16+3).-+4&yyNFAy..26/y
QObqrokqlqebPmfofqQ^ihboyKyPmfofqQ^ihboPk^oic^kd%2-+0)6+5&yyNFAy..3/6y
>Sfpflklc>foyKyPmfofqQ^ihboPk^oic^kd%2-+0)6+5&yyNFAy..30.y
@Sfpflklc>foyNFAy..30.yyRy01446yyKyRpbXFjmbob^k$pMofj^iZ^qqebqlqbjkb^o_vqebnrbpqdfsbo%2-).-&y
QSfpflklc>foyKyPmfofqQ^ihboPk^oic^kd%2-+0)6+5&yyNFAy..30.y
>C^opbboDofjt^ihbo$pPmfofqyKyPmfofqQ^ihboPk^oic^kd%2-+0)6+5&yyNFAy..302y
>ObsbkdbRmlkJ^djlqeyKyLoqolpe%16+6).-+.&yyNFAy..306y

QC^opbboDofjt^ihbo$pPmfofqyKyC^opbboDofjt^ihbo$pPmfofq%23+/)6+/&yyNFAy..302y
>H^d^kfperyKyC^opbboDofjt^ihbo$pPmfofq%23+/)6+/&yyNFAy..304y
HH^d^kfperyNFAy..304yyKyHfiiH^d^kfper%23+0)./+3&yyNLyH^d^kfper$pCbqfpe7.,.y
@H^d^kfperyNFAy..304yyRy0145.yyRyRpbXH^d^kfper$pCbqfpeZ^qC^opbboDofjt^ihbo$pPmfofq%23+/)6+/&y
QH^d^kfperyKyC^opbboDofjt^ihbo$pPmfofq%23+/)6+/&yyNFAy..304y
>ObqrokJvObj^fkpyKyC^opbboDofjt^ihbo$pPmfofq%23+/)6+/&yyNFAy..305y
@ObqrokJvObj^fkpyNFAy..305yyKyMf`hrmqebobj^fkpC^opbboDofjt^ihbo$pPmfofq%23+/)6+/&ib^sbp_befkay
@ObsbkdbRmlkJ^djlqeyNFAy..306yyKy>iijl_p^obclrkafkqeb`^sb^olrka%20+5).0+2&y

QObqrokJvObj^fkpyKyPmfofqQ^ihboPk^oic^kd%2-+0)6+5&yyNFAy..305y
QObsbkdbRmlkJ^djlqeyKyLoqolpe%16+6).-+.&yyNFAy..306y

C>j_boIbadbyKyHfj_fw^%16+3)..+.&yyNFAy..616y

QJlkfqlofkdqebOfcq7Tfkqbocfk@^sbokyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy./4/5y

>KlqTfqelrq^CfdeqyKy>q^fh^%30+5)13+.&yyNFAy..616y
>Mobm^ofkdcloqebTlopqyKyRq^fh31+-)12+5&yyNFAy..612y

@KlqTfqelrq^CfdeqyNFAy..616yyKyQebHs^iafoO^fabop`^k_bclrka^iilsboH^ph^i^%35+.)15+/&y
@Mobm^ofkdcloqebTlopqyNFAy..612yyKyClrka^iilsboH^ph^i^%35+.)15+/&y

QMobm^ofkdcloqebTlopqyKyRq^fh31+-)12+5&yyNFAy..612y
QKlqTfqelrq^CfdeqyKy>q^fh^%30+5)13+.&yyNFAy..616y
>Jr^efq$pTfpaljyKy>q^fh^%30+5)13+.&yyNFAy..62-y
QJr^efq$pTfpaljyKyBiaboJr^efq%34+/)21+5&yyNFAy..62-y
>PmfofqpT^q`eLsboRpyKyBiaboJr^efq%34+/)21+5&yyNFAy..63.y

@PmfofqpT^q`eLsboRpyNFAy..63.yyKyCfkaqebab^aqrph^oofkqebt^qboqlqebkloqe%34+3)2-+1&y

QPmfofqpT^q`eLsboRpyKyBiaboJr^efq%34+/)21+5&yyNFAy..63.y
>QebQfabpQrokyKyBiaboJr^efq%34+/)21+5&yyNFAy..635y
@QebQfabpQrokyNFAy..635yyKyLkqeblqebopfablcqebpq^qrb^q%34+-)23+-&y
QQebQfabpQrokyKyBiaboJr^efq%34+/)21+5&yyNFAy..635y

QOfabqlQ^rkh^$ibSfii^dbyKyP^dbB^oqe^kaPhv%44+0)05+1&yyNFAy..555y

cQ^rkh^$ibSfii^dbyKyLjrPmfofq_obbwb%44+4)04+5&yyNFAy..56-y
eQ^rkh^$ibSfii^dbyKyM^erColpqellc%43+0)04+/&yyNFAy..56-y

>Te^q>obQebvRmQl<yKyP^dbB^oqe^kaPhv%44+0)05+1&yyNFAy..56-y
>P`lrqfkdqebPfkhelibpyKyDob^qc^qeboJ^e^k%44+.)04+5&yyNFAy..351y
>Il^a$boRmyKyCbwwfuDb^oqtfpq%44+2)04+-&yyNFAy..55.y
>P^dbEfdejbp^fpJfppfkdyKyDob^qjlqeboQ^fd^%44+0)03+6&yyNFAy..341y
QEbiip`ob^j$p@e^jmflkyKy@efbcq^fkTfkqbod^ib%43+-)04+0&yyNFAy..6.3y

@P`lrqfkdqebPfkhelibpyNFAy..351yyRy016/-yyKyRpbqebXJ^mlcqebDbvpboCfbiapZ^qqebKloqetbpq%33+/)0/+/&)Kloqeb^pq%36+4)0/+.&^kaPlrqePfkhelib%4-+/)03+0&y
@Te^q>obQebvRmQl<yNFAy..56-yyKyQo^sbi^olrka%32+-)/.+.&qlp`lrqqebpq^qflky

>Bjbodbk`vPrmmifbpyKy@o^pebaOb`lkMfilq%31+-)02+5&yyNFAy..554y
@Bjbodbk`vPrmmifbpyNFAy..554yyKy@liib`q4XDkljfpeBjbodbk`vQllihfqpZcoljqebdkljbp^olrka%30+/)02+6&y
@Il^a$boRmyNFAy..55.yyRy02/4/yyKyPrjjlkGbkkvtfqeXGbkkv$pTefpqibZ^qqeb`o^pe^olrka%31)04&^ka^slfa^iijl_ptefibvlreb^a_^`hqlCbwwfuDb^oqtfpq%44+2)04+-&y

QIl^a$boRmyKyCbwwfuDb^oqtfpq%44+2)04+-&yyNFAy..55.y
QBjbodbk`vPrmmifbpyKyCbwwfuDb^oqtfpq%44+2)04+-&yyNFAy..554y
>QebMltbolcqebBibjbkqpyKyAlo^fkColpqellc%44+3)04+-&yyNFAy..560y
QP`lrqfkdqebPfkhelibpyKyDob^qc^qeboJ^e^k%44+.)04+5&yyNFAy..351y
>QebEb^oqlcqebBibjbkqpyKyDob^qc^qeboJ^e^k%44+.)04+5&yyNFAy..352y
QTe^q>obQebvRmQl<yKyP^dbB^oqe^kaPhv%44+0)05+1&yyNFAy..56-y
>J^pqboqebPqlojyKyP^dbB^oqe^kaPhv%44+0)05+1&yyNFAy..562y
@J^pqboqebPqlojyNFAy..562yyKyRpbqebqlbjfkqeberq^q%44+.+05+4&^kahfiiqebklk*bifqbpm^tky
QJ^pqboqebPqlojyKyP^dbB^oqe^kaPhv%44+0)05+1&yyNFAy..562y
>Tb^hkbppqlIfdeqkfkdyKyP^dbB^oqe^kaPhv%44+0)05+1&yyNFAy..563y
>@ib^kfkdRmqebMllipyKyFolkBvbp%44+-)04+3&yyNFAy..6-3y
>PlriplcqebAb`ropbayKyDob^qjlqeboQ^fd^%44+0)03+6&yyNFAy..566y

@QebMltbolcqebBibjbkqpyNFAy..560yyRy02/5.yyKyAolmqebXTfkaplriQlqbjZ^olrkaqebmllip^q%4.+-)/3+/&^kahfiiPqb^jO^dbop`ilpbqlfqy
@Tb^hkbppqlIfdeqkfkdyNFAy..563yyRy0202/yyKyRpbXP^db$pIfdeqkfkdOlaZlkqebol_lqpclrka^olrkaqebMrjmfkdPq^qflk^q%33+.)/0+2&y
@PlriplcqebAb`ropbayNFAy..566yyRy021-.yyKyRpbXQebDob^qjlqebo$pPlri`^q`eboZlkdkljbpclrka^olrkaqebMrjmfkdPq^qflk^q%33+.)/0+2&y
@@ib^kfkdRmqebMllipyNFAy..6-3yyKy@liib`q.2XCfww`o^khPm^obM^oqpZ^olrkaqebMrjmfkdPq^qflk^q%33+.)/0+2&y

@QebEb^oqlcqebBibjbkqpyNFAy..352yyKyDbq2XBibjbkq^iEb^oqpZaolmmbacoljqebColwbkBibjbkq^ip^olrka%52+0)10+4&y

QTb^hkbppqlIfdeqkfkdyKyP^dbB^oqe^kaPhv%44+0)05+1&yyNFAy..563y
>QebPr_*@efbcq^fkpyKyP^dbB^oqe^kaPhv%44+0)05+1&yyNFAy..6-4y
QQebMltbolcqebBibjbkqpyKyAlo^fkColpqellc%44+3)04+-&yyNFAy..560y
>M^q`efkdRmyKyCbwwfuDb^oqtfpq%44+2)04+-&yyNFAy..561y
QPlriplcqebAb`ropbayKyDob^qjlqeboQ^fd^%44+0)03+6&yyNFAy..566y
>Abcb^qqebDb^oj^pqboyKyDob^qjlqeboQ^fd^%44+0)03+6&yyNFAy..6-6y
Q@ib^kfkdRmqebMllipyKyFolkBvbp%44+-)04+3&yyNFAy..6-3y
QQebEb^oqlcqebBibjbkqpyKyTfkaQ^jbo?^o^e%42+3)02+5&yyNFAy..352y
>QebEloklcBibjbkq^iCrovyKyTfkaQ^jbo?^o^e%42+3)02+5&yyNFAy..362y

@QebEloklcBibjbkq^iCrovyNFAy..362yyKyDrodib_lddib$pIltboe^icfpclrka^q%46+/)/5+.&^ka?ro_ibdl__ib$pRmmboe^ic^q%35+-)1-+0&y

QQebEloklcBibjbkq^iCrovyKyTfkaQ^jbo?^o^e%42+3)02+5&yyNFAy..362y
>Qeb@lii^mpbyKyTfkaQ^jbo?^o^e%42+3)02+5&yyNFAy..4-3y

@Qeb@lii^mpbyNFAy..4-3yyRy01635yyKyRpbXQebEloklcBibjbkq^iCrovZ^qplrqeqrkkbifkdbvpbocfbiap%4-+0)03+2&y

@M^q`efkdRmyNFAy..561yyRy02/55yyKyHfiiJ^ope@^of_lr^olrka%44+1)02+0&qldbqXRk`roba@^of_lrEfabpZqebkdlql%42+3)01+.&ql`robqebefabpy

@QebPr_*@efbcq^fkpyNFAy..6-4yyKyRpbqeb`lkqolip^qb^`epq^qflkqlprjjlkQtlkhv%3-+/)/-+1&)BA*/.-%32+2).4+2&)J^u?i^pql%30+4)//+1&^kaQebDofkabo%32+/)/5+5&y
@Abcb^qqebDb^oj^pqboyNFAy..6-6yyKyEb^armqlqeb_rfiafkdlkqebMrjmfkdPq^qflk%31+2)/0+1&+Ob^aqebj^kr^i)hfiiDb^oj^pqboJb`e^wlay

QQeb@lii^mpbyKyTfkaQ^jbo?^o^e%42+3)02+5&yyNFAy..4-3y
QM^q`efkdRmyKyCbwwfuDb^oqtfpq%44+2)04+-&yyNFAy..561y
QAbcb^qqebDb^oj^pqboyKyDob^qjlqeboQ^fd^%44+0)03+6&yyNFAy..6-6y
QQebPr_*@efbcq^fkpyKyP^dbB^oqe^kaPhv%44+0)05+1&yyNFAy..6-4y
>PeolraplcqebP`lrodbyKy@efbcq^fkTfkqbod^ib%43+-)04+0&yyNFAy..3/5y

QP^dbEfdejbp^fpJfppfkdyKyP^dbEfdejbp^%41+4)/0+3&yyNFAy..341y
>>MolmboAb^qeyKyP^dbEfdejbp^%41+4)/0+3&yyNFAy..342y

@>MolmboAb^qeyNFAy..342yyKyHfii.-Mi^drbaJ^dk^q^ro%43+-).5+-&fkqebAbklcqebavfkdy
@PeolraplcqebP`lrodbyNFAy..3/5yyKyHfiiP`lrodbaJ^jjlqep^olrka%5/+0)0-+1&y

Q>MolmboAb^qeyKyP^dbEfdejbp^%41+4)/0+3&yyNFAy..342y
>PqlmqebMi^drbyKyP^dbEfdejbp^%41+4)/0+3&yyNFAy..344y

QPeolraplcqebP`lrodbyKy@efbcq^fkTfkqbod^ib%43+-)04+0&yyNFAy..3/5y
>Qeb?^aB^oqeyKy@efbcq^fkTfkqbod^ib%43+-)04+0&yyNFAy..30-y

@PqlmqebMi^drbyNFAy..344yyRy016.0yyKyRpbXEfdejbp^$p@ib^kpfkdPbbapZ^qqebAbklcavfkd^olrka%41+-).1+-&y

QPqlmqebMi^drbyKyP^dbEfdejbp^%41+4)/0+3&yyNFAy..344y
>Cfka?ofpqibelokyKyP^dbEfdejbp^%41+4)/0+3&yyNFAy..345y
>C^iibkKb`olmlifpyKyP^dbEfdejbp^%41+4)/0+3&yyNFAy..350y

QCfka?ofpqibelokyKyIlkdorkkbo?ofpqibelok%36+5)./+4&yyNFAy..345y
>QebAl`qlo^kaqebIf`e*IloayKyIlkdorkkbo?ofpqibelok%36+5)./+4&yyNFAy..354y

@QebAl`qlo^kaqebIf`e*IloayNFAy..354yyKyDlqlQ^io^j^p%35+6).0+-&^kahfiiAl`qloO^wlodofk%36+2).0+.&^kaIf`e*Iloa@efiitfkqbo%36+2).0+5&y
@C^iibkKb`olmlifpyNFAy..350yyKyJl_p^obclrka^ii^olrkaQ^io^j^p%35+6).0+-&y

QQebAl`qlo^kaqebIf`e*IloayKyP^dbEfdejbp^%41+4)/0+3&yyNFAy..354y
>Obqroktfqeqeb?^aKbtpyKyP^dbEfdejbp^%41+4)/0+3&yyNFAy..356y
QC^iibkKb`olmlifpyKyP^dbEfdejbp^%41+4)/0+3&yyNFAy..350y

@Qeb?^aB^oqeyNFAy..30-yyKy@liib`qXP`lrodbaB^oqeZcoljqebjlrkap^olrka%46+2)/6+.&y

QQeb?^aB^oqeyKy@efbcq^fkTfkqbod^ib%43+-)04+0&yyNFAy..30-y
>?ibkafkdFkyKy@efbcq^fkTfkqbod^ib%43+-)04+0&yyNFAy..300y
QObqroktfqeqeb?^aKbtpyKyDob^qjlqeboQ^fd^%44+0)03+6&yyNFAy..356y

@?ibkafkdFkyNFAy..300yyRy0145/yyKyRpbqebXFj_rbaP`lrodbPeolraZ%J^hbprobvlralk$qbnrfmqebfqbjqfii>CQBOvlr^ob^iob^avfkqeb`fqv+Fcvlrbnrfmqeb`il^h)^kaqebkdlfk)vlr$iidbqklqefkd+Bkqboqeb`fqvcriiv)QEBKbnrfmqeb`il^h^kavlrpelria_bdllaqldl+&qlp`lrqqebPmfoblc?illa%55+.)/-+6&)PmfoblcAb`^v%50+6)/-+4&^kaPmfoblcM^fk%56+-)/5+3&+?bprobklqql^ddol^k^_ljfk^qflky

Q?ibkafkdFkyKy@efbcq^fkTfkqbod^ib%43+-)04+0&yyNFAy..300y
>TloaplcMltboyKy@efbcq^fkTfkqbod^ib%43+-)04+0&yyNFAy..31-y
>>@lro^dblrpPqofhbyKyArojF`befab%43+-)03+0&yyNFAy..31.y
>Kbrqo^ifwfkdqeb@^riaolkpyKyP^db>bfob%43+-)04+0&yyNFAy..314y

>QebPmfoblc?illayKyQebfqbjXSf^ilcCobpe?illaZpq^oqpnrbpq*aolmmba_vA^ohc^iibk?illa_b^obo%54)/-&yyNFAy..321yyRy015.2yyLy
QQebPmfoblc?illayKyPkltQo^`hboDorjj%54+1)/-+3&yyNFAy..321yyLy
>Pe^qqboqebLo_pyKyPkltQo^`hboDorjj%54+1)/-+3&yyNFAy..326yyLy
@Pe^qqboqebLo_pyNFAy..326yyLyyKyAbpqolvqeb?illaDil_bpproolrkafkdPkltQo^`hboDorjj%54+1)/-+3&y

@Kbrqo^ifwfkdqeb@^riaolkpyNFAy..314yyRy015-3yyKyRpbXP^db>bfob$pQlqbjZlkqebTbpq%52+0)/-+-&)B^pq%54+6)/6+6&^ka@bkqo^i%53+.)//+0&@^riaolkpy
@TloaplcMltboyNFAy..31-yyKyHfiiEfdeMofbpqQ^ibq*He^%56+1)/5+6&)EfdeMofbpq>kalo^qe%54+5)/-+4&^kaEfdeMofbpqK^cbopbq%50+6)/-+2&+QlhfiiEfdeMofbpqK^cbopbq)hfiiqebjl_p^olrkaefjcfopqy
@>@lro^dblrpPqofhbyNFAy..31.yyKy?lqejl_p`^k_bclrka^qQbjmib@fqvlcBk$Hfi^etfqe^kbkqo^k`blc%50+/)/3+4&

QPe^qqboqebLo_pyKyPkltQo^`hboGrkbh%43+5)04+6&yyNFAy..326y
QKbrqo^ifwfkdqeb@^riaolkpyKyP^db>bfob%43+-)04+0&yyNFAy..314y
Q>@lro^dblrpPqofhbyKyArojF`befab%43+-)03+0&yyNFAy..31.y
QTloaplcMltboyKy@efbcq^fkTfkqbod^ib%43+-)04+0&yyNFAy..31-y
>?ob^hfkdQeolrdeyKy@efbcq^fkTfkqbod^ib%43+-)04+0&yyNFAy..565y

@?ob^hfkdQeolrdeyNFAy..565yyKyDolrmnrbpq_rq`^k_bplil$a)rpbqeb_irbmloq^i^qqebofdeq*jlpq^ob^lcqebQbjmib@fqvlcBk$Hfi^e)lk`bfkpfabhfiiMofk`bS^i^k^o%53+0)/5+3&)IrqeflkQebSfib%54+-)/6+2&^kaS^kqeovkqebJbo`fibpp%52+4)/4+1&y

Q?ob^hfkdQeolrdeyKy@efbcq^fkTfkqbod^ib%43+-)04+0&yyNFAy..565y
>QebC^iilcQ^rkh^$ibSfii^dbyKy@efbcq^fkTfkqbod^ib%43+-)04+0&yyNFAy..6/6y
QQebC^iilcQ^rkh^$ibSfii^dbyKyJlqeboQ^ro^kllh%45+1)05+-&yyNFAy..6/6y
>>`olppQo^kp_lob^yKyJlqeboQ^ro^kllh%45+1)05+-&yyNFAy..60-y

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
