DugisGuideViewer:RegisterGuide("Dragonblight (73-75)", "Grizzly Hills (75-76)", "Horde", "L", function()
return [[
AAA

Q>`olppQo^kp_lob^yKyT^oqllhF`b_lok%./+5)2.+3&yyNFAy..60-y
>>Q^robk>jlkdQ^rkh^yKyT^oqllhF`b_lok%./+5)2.+3&yyNFAy..644y

Q>Q^robk>jlkdQ^rkh^yKyBjfpp^ov?ofdeqellc%.0+5)16+3&yyNFAy..644y
>FkqlqebCliayKyBjfpp^ov?ofdeqellc%.0+5)16+3&yyNFAy..645y
>MofablcqebEloabyKy?illaDr^oaOle$hfii%.1+/)16+6&yyNFAy..65-y

@MofablcqebEloabyKyHfii.2>kr_^o>j_rpebop^olrka%.4+6)16+6&yyNFAy..65-y
@FkqlqebCliayKy@liib`q.-XEloab>oj^jbkqpZclrka^olrka%.4+6)16+6&yyNFAy..645y

QMofablcqebEloabyKy?illaDr^oaOle$hfii%.1+/)16+6&yyNFAy..65-y

QFkqlqebCliayKyBjfpp^ov?ofdeqellc%.0+5)16+3&yyNFAy..645y
>?illaL^qelcqebEloabyKyBjfpp^ov?ofdeqellc%.0+5)16+3&yyNFAy..650y
@?illaL^qelcqebEloabyKyQ^ihqlqeb`ljjlkQ^rkh^^olrkaqltk^kadbqqebjqlglfkqebeloabyyNFAy..650yyRy02451y
Q?illaL^qelcqebEloabyKyBjfpp^ov?ofdeqellc%.0+5)16+3&yyNFAy..650y
>>dj^o$pE^jjboyKyBjfpp^ov?ofdeqellc%.0+5)16+3&yyNFAy./--5y

c>dj^o$pE^jjboyKyK^owrkPhv_ob^hbo%04+2)12+4&yyNFAy./-56y
e>dj^o$pE^jjboyKy?^oo^`hpJ^pqboE^od^%05+/)13+-&yyNFAy./-56y

>T^kqba7J^dfpqboHbialkrpyKyT^kqba%04+3)13+2&yyNFAy./-56y
>T^kqba7Dfd^kq^royKyT^kqba%04+3)13+2&yyNFAy./-6-y
>T^kqba7Aob^aq^ilkyKyT^kqba%04+3)13+2&yyNFAy./-6.y
Q>dj^o$pE^jjboyKyLsboiloa>dj^o%05+.)13+0&yyNFAy./--5y
>Sf`qlovKb^op+++yKyLsboiloa>dj^o%05+.)13+0&yyNFAy./-01y
>Ofcibqeb?lafbpyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy..666y
QSf`qlovKb^op+++yKyPbkfloPbodb^kqGrhqlh%03+4)13+3&yyNFAy./-01y
>ColjqebAbmqeplc>wgli*Kbor_yKyPbkfloPbodb^kqGrhqlh%03+4)13+3&yyNFAy./-03y
>?i^`h?illalcVldd*P^olkyKy?lorpFolk_bkabo%03+3)14+.&yyNFAy./-06y
>Fj_b`fibp>_lrkayKyAl`qloPfkq^oJ^ibcflrp%03+.)15+5&yyNFAy./.56y
>J^ohbacloAb^qe7Efde@riqfpqW^kdrpyKy@^mq^fkDloq%02+5)15+1&yyNFAy./-23y
>@lkq^fkfkdqebOlqyKyPl^oE^thcrov%04+.)15+3&yyNFAy./.--y

@@lkq^fkfkdqebOlqyKyHfiiqebO^_faDofwwivp^ka?ifdeqbaBihpclrka^olrka%0-+/)14+0&)qebXOlqObpfpq^kqLod^kZtfiimol_^_ivaolm^cqbo^ii.2^obhfiibayyNFAy./.--y

@?i^`h?illalcVldd*P^olkyKy@liib`q.-X?i^`h?illalcVldd*P^olkP^jmibpZfkqebjfkb)qebbkqo^k`bfp^q%/3+6)2-+1&yyNFAy./-06y
>>kBkbjvfk>oqe^pyKyHfifuqebRko^sbibo%/3+/)2-+4&yyNFAy./-1-y
@>kBkbjvfk>oqe^pyKyHfii3>kr_$^oRkaboiloaptef`e^obclrkaproolrkafkdqebnrbpqdfsbo%/3+/)2-+4&yyNFAy./-1-y
@J^ohbacloAb^qe7Efde@riqfpqW^kdrpyKyHfiiEfde@riqfpqW^kdrptelpm^tkp^q%/5+6)16+4&yyNFAy./-23y
Q>kBkbjvfk>oqe^pyKyHfifuqebRko^sbibo%/3+/)2-+4&yyNFAy./-1-y
>QebIlpqBjmfobyKyHfifuqebRko^sbibo%/3+/)2-+4&yyNFAy./-1.y

>>sbkdbqefp>qol`fqvyKyBqebkf^iJllkpe^alt%/1+/)3-+.&yyNFAy./--3y
@Ofcibqeb?lafbpyKyIllqqeb_lafbp^olrka%/2+/)25+6&)qebklmbkqebfqbjvlrdbqcoljqebjrkqfivlrdbqqebXJllkobpqD^oabkpMi^kpZyyNFAy..666y

@>sbkdbqefp>qol`fqvyKyHfii?irbAo^dlkcifdeqclo`bp^olrka%/.+6)3/+-&yyNFAy./--3y

Q>sbkdbqefp>qol`fqvyKyBqebkf^iJllkpe^alt%/1+/)3-+.&yyNFAy./--3y
>Bka>o`^kfjrpyKyBqebkf^iJllkpe^alt%/1+/)3-+.&yyNFAy./-.0y

@Bka>o`^kfjrpyKyHfii>o`^kfjrpfkqebmfq_biltqebprodbkbbaib%/-+-)26+2&yyNFAy./-.0y

QBka>o`^kfjrpyKyBqebkf^iJllkpe^alt%/1+/)3-+.&yyNFAy./-.0y

E>dj^o$pE^jjboyKy?^oo^`hpJ^pqboE^od^%05+/)13+-&yyNFAy./--2y
QQebIlpqBjmfobyKyLsboiloa>dj^o%05+.)13+0&yyNFAy./-1.y
QOfcibqeb?lafbpyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy..666y
>Mobsbkqqeb>``loayKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./--2y
QColjqebAbmqeplc>wgli*Kbor_yKyPbkfloPbodb^kqGrhqlh%03+4)13+3&yyNFAy./-03y
>QebJfdeqlcqebEloabyKyPbkfloPbodb^kqGrhqlh%03+4)13+3&yyNFAy./-20y
>PqobkdqelcF`bjfpqyKyDob^qjlqeboF`bjfpq%02+5)13+-&yyNFAy./-30y
Q?i^`h?illalcVldd*P^olkyKy?lorpFolk_bkabo%03+3)14+.&yyNFAy./-06y
>P`lrodb>oj^jbkqpyKy?lorpFolk_bkabo%03+3)14+.&yyNFAy./-15y
QJ^ohbacloAb^qe7Efde@riqfpqW^kdrpyKy@^mq^fkDloq%02+5)15+1&yyNFAy./-23y
Q@lkq^fkfkdqebOlqyKyPl^oE^thcrov%04+.)15+3&yyNFAy./.--y
>QebDllaAl`qlo+++yKyPl^oE^thcrov%04+.)15+3&yyNFAy./.-.y
QQebDllaAl`qlo+++yKyAl`qloPfkq^oJ^ibcflrp%03+.)15+5&yyNFAy./.-.y
>FkPb^o`elcqebOr_vIfi^`yKyAl`qloPfkq^oJ^ibcflrp%03+.)15+5&yyNFAy./.-/y
>QebCibpe*?lrkaQljbyKyCibpe*_lrkaQljbaolmmba_vKM@pfkF`bjfpqSfii^dbyyNFAy./-24yyLyyRy03411y

@P`lrodb>oj^jbkqpyKyHfii^kvlcqeb>kr_$^ojl_p^qF`bjfpqSfii^db%/3+0)1/+1&ql`liib`q5XP`lrodb>oj^jbkqpZ+T^q`eclofqbjaolmXCibpe*_lrkaQljbZqlpq^oqkbuqnrbpqyyNFAy./-15y
@QebJfdeqlcqebEloabyKyMi^`bqebXT^oplkd?^qqibPq^ka^oaZaltk^q%/1+5)06+3&^kaabcbkacoljqebt^sbplc^qq^`hpyyNFAy./-20yyRy03405y

QPqobkdqelcF`bjfpqyKy?^kqelhF`bjfpq%//+3)1.+5&yyNFAy./-30y
>@e^fkplcqeb>kr_$^oyKy?^kqelhF`bjfpq%//+3)1.+5&yyNFAy./-31y

@@e^fkplcqeb>kr_$^oyKyHfiiQfs^uqeb?ob^hbo%/0+5)06+/&)>klh$o^qebJ^kfmri^qlo%/1+6)10+6&^kaPfklhqebPe^alto^dbo%/2+4)11+/&yyNFAy./-31y

Q@e^fkplcqeb>kr_$^oyKy?^kqelhF`bjfpq%//+3)1.+5&yyNFAy./-31y
>ObqroklcqebEfde@efbcyKy?^kqelhF`bjfpq%//+3)1.+5&yyNFAy./-36y

@ObqroklcqebEfde@efbcyKyRpbqebX>kr_$^oMofplkHbvZqlcobbqebEfde@efbc%/3+0)1/+1&^kaqebkcfdeqRkabo*Hfkd>kr_$bq$h^k)tebkebfpab^aillq^mfb`blcefp^ojloyyNFAy./-36yyRy0343-y

@Mobsbkqqeb>``loayKyTfkaQo^aboJr$c^efplrqpfab^q%.5+1)25+3&)Dlo^jlpefpfkpfablkqebpb`lkaibsbi%.6+2)25&+T^q`eclofqbjaolmXDlo^jlpe$pPqo^kdbAbsf`bZqlpq^oqkbuqnrbpqyyNFAy./--2y
>>Pqo^kdbAbsf`byKyQebfqbjXDlo^jlpe$pPqo^kdbAbsf`bZpq^oqpnrbpq*aolmmba_vDlo^jlpe%.6+2)25&yyNFAy./-26yyRy03413y

>QebC^qblcqebOr_vAo^dlkpeofkbyKyQebfqbjXOr_v?oll`eZpq^oqpnrbpq*aolmmba_vA^eif^Prkqlr`e%14+3)16+-&yyNFAy./1.6yyRy04500y
@FkPb^o`elcqebOr_vIfi^`yKyIllqqebXOr_vIfi^`Z^q%14+3)16+-&yyNFAy./.-/y

E>dj^o$pE^jjboyKy?^oo^`hpJ^pqboE^od^%05+/)13+-&yyNFAy./-3.y
QMobsbkqqeb>``loayKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./--2y
Q>Pqo^kdbAbsf`byKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-26y
>Molgb`qflkp^kaMi^kpyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-3.y
QObqroklcqebEfde@efbcyKyLsboiloa>dj^o%05+.)13+0&yyNFAy./-36y
>>iiE^fiOl^k^rhyKyLsboiloa>dj^o%05+.)13+0&yyNFAy./.1-y
@>iiE^fiOl^k^rhyKyQ^ihtfqeOl^k^rhF`bjfpqlk%03+0)12+2&yyNFAy./.1-y
Q>iiE^fiOl^k^rhyKyLsboiloa>dj^o%05+.)13+0&yyNFAy./.1-y
QP`lrodb>oj^jbkqpyKy?lorpFolk_bkabo%03+3)14+.&yyNFAy./-15y
QFkPb^o`elcqebOr_vIfi^`yKyAl`qloPfkq^oJ^ibcflrp%03+.)15+5&yyNFAy./.-/y
>ObqrokqlPl^oyKyAl`qloPfkq^oJ^ibcflrp%03+.)15+5&yyNFAy./.-1y
QQebCibpe*?lrkaQljbyKy@^mq^fkDloq%02+5)15+1&yyNFAy./-24yyLy
>Hliqfo^^kaqebI^kdr^dblcAb^qeyKy@^mq^fkDloq%02+5)15+1&yyNFAy./..2y
QQebJfdeqlcqebEloabyKyPbkfloPbodb^kqGrhqlh%03+4)13+3&yyNFAy./-20y
>>qq^`h_v>foyKyPbkfloPbodb^kqGrhqlh%03+4)13+3&yyNFAy./-4.y
QHliqfo^^kaqebI^kdr^dblcAb^qeyKyHliqfo^Ab^qetb^sbo%03+2)13+1&yyNFAy./..2y
>FkPbosf`blc?illayKyHliqfo^Ab^qetb^sbo%03+2)13+1&yyNFAy././2y
>FkPbosf`blcqebRkelivyKyHliqfo^Ab^qetb^sbo%03+2)13+1&yyNFAy././3y
>FkPbosf`blcColpqyKyHliqfo^Ab^qetb^sbo%03+2)13+1&yyNFAy././4y
QObqrokqlPl^oyKyPl^oE^thcrov%04+.)15+3&yyNFAy./.-2y
>TebobqebTfiaQefkdpOl^jyKyPl^oE^thcrov%04+.)15+3&yyNFAy./...y
Q>qq^`h_v>foyKyS^iklhTfkao^dbo%04+/)12+5&yyNFAy./-4.y
>?ifdeq_b^pqp?bA^jkbayKyS^iklhTfkao^dbo%04+/)12+5&yyNFAy./-4/y

@TebobqebTfiaQefkdpOl^jyKyRpbqebXM^`hlcS^``fkbZlkqeb>oqf`Dofwwifbp^kaPkltc^iiBihp^olrka%1.+-)16+5&yyNFAy./...yyRy035.5y

@?ifdeq_b^pqp?bA^jkbayKyEb^aqlF`bjfpqSfii^db%/3+0)1/+1&+RpbXS^iklh$pCi^obDrkZ^karpbqebHlo$holkT^oOfaboqlciv^olrka^kahfiiqeb>kr_$^o?ifdeq_b^pqp^olrkaqeb_ofadbpyyNFAy./-4/yyRy03441y

@Molgb`qflkp^kaMi^kpyKyRpbqebXProdbKbbaibQbibmloqboZ^q%//+2323+64&)dbq`ilpbbklrdeqldbq`obafq+Rpbfq^d^fkqldbqaltkyyNFAy./-3.yyRy03414y
RRpbqebXProdbKbbaibQbibmloqboZyKyRpbqebXProdbKbbaibQbibmloqboZqldbqaltkyyRy03414yyNFAy..63-y

@FkPbosf`blc?illayKyDlqlRkar$ibSfii^db%06+2)35+6&)cfka^Abo^kdbaFkar$ibSfii^dbodbqqebj_bilt/2"eb^iqe)qebkrpbqebX?illaDbjZyyNFAy././2yyRy035/4y

cJl^$hfE^o_loyKy@faCilrkabocfu%15+2)41+1&yyNFAy..63-y

>Mi^kkfkdcloqebCrqrobyKyQo^mmboJ^r$f%15+0)41+0&yyNFAy..63-y
QQo^sbiqlJl^$hfE^o_loyKyBiaboHl$k^kf%15+.)41+6&yyNFAy./..5y
>IbqKlqefkdDlQlT^pqbyKyBiaboHl$k^kf%15+.)41+6&yyNFAy..625y

@IbqKlqefkdDlQlT^pqbyKyHfiijl_p^olrkaPkltc^iiDi^ab^q%12+4)3.+3&yyNFAy..625y
@Mi^kkfkdcloqebCrqrobyKyPqb^i./XPkltc^iiDi^abMrmpZkloqelcqltk^olrka%12+4)3.+3&yyNFAy..63-y

QMi^kkfkdcloqebCrqrobyKyQo^mmboJ^r$f%15+0)41+0&yyNFAy..63-y
QIbqKlqefkdDlQlT^pqbyKyBiaboHl$k^kf%15+.)41+6&yyNFAy..625y
>Pi^vIldrekyKyBiaboHl$k^kf%15+.)41+6&yyNFAy..626y

@Pi^vIldrekyKy>qqeberqlkqebkloqepfablcPkltc^iiDi^ab%13+.)26+4&+>cqbovlrhfiiefj)pjb^oefp_illayyNFAy..626yyRy02355y

QPi^vIldrekyKyBiaboHl$k^kf%15+.)41+6&yyNFAy..626y
>Pmfofqr^iFkpfdeqyKyQl^ir$rqebJvpqf`%16+.)42+4&yyNFAy./-/5y
@Pmfofqr^iFkpfdeqyKyRpbXQl^ir$r$pPmfofqr^iFk`bkpbZlkqeb_o^wfboofdeqlrqpfabqeberq%16)42&yyNFAy./-/5yyRy026-4y
QPmfofqr^iFkpfdeqyKyQl^ir$rqebJvpqf`%16+.)42+4&yyNFAy./-/5y
>BiaboJ^k^$il^yKyQl^ir$rqebJvpqf`%16+.)42+4&yyNFAy./-0-y
>Qr^$hb^$p@o^_Qo^mpyKyQr^$hb^%15+-)43+/&yyNFAy./--6y

>Pfdkplc?fdT^qbovQolr_ibyKyTob`hba@o^_Qo^m%14+4)46+6&+Afsbaltkfkqlqebt^qboyyNFAy./-..y
@Qr^$hb^$p@o^_Qo^mpyKy@liib`q5XQr^$hb^@o^_Qo^mpZclrka^olrkaqebt^qbop%15+-)46+-&+RpbXQr^$hb^$p?ob^qefkd?i^aaboZfcvlrkbbaqlyyNFAy./--6yyRy04/32y

QQr^$hb^$p@o^_Qo^mpyKyQr^$hb^%15+-)43+/&yyNFAy./--6y
QPfdkplc?fdT^qbovQolr_ibyKyQr^$hb^%15+-)43+/&yyNFAy./-..y
>Qeb?^fqyKyQr^$hb^%15+-)43+/&yyNFAy./-.3y

@Qeb?^fqyKyHfiiqeb_fd`o^_lrqlkHfif$r^$p>qliiqlqebtbpq%1/+3)5-+3&yyNFAy./-.3y

QQeb?^fqyKyQr^$hb^%15+-)43+/&yyNFAy./-.3y
>Jb^qlkqebEllhyKyQr^$hb^%15+-)43+/&yyNFAy./-.4y

@Jb^qlkqebEllhyKyCliiltqebcfpefkdifkblrqqfii%13+4)45+/&)rpbXQr$r$dt^o$p?^fqZ^kahfiiqebpe^ohyyNFAy./-.4yyRy02505y

QJb^qlkqebEllhyKyQr^$hb^%15+-)43+/&yyNFAy./-.4y

QBiaboJ^k^$il^yKyBiaboJ^k^$il^%03+5)32+/&yyNFAy./-0-y
>CobbaljcloqebIfkdbofkdyKyBiaboJ^k^$il^%03+5)32+/&yyNFAy./-0.y
@CobbaljcloqebIfkdbofkdyKyHfiijl_p^olrkaqebsfii^dbproolrkafkdBiaboJ^k^$il^%03+5)32+/&yyNFAy./-0.y
QCobbaljcloqebIfkdbofkdyKyBiaboJ^k^$il^%03+5)32+/&yyNFAy./-0.y
>@lksbopfkdTfqeqebAbmqepyKyBiaboJ^k^$il^%03+5)32+/&yyNFAy./-0/y

@@lksbopfkdTfqeqebAbmqepyKyEb^aplrqeql^kfpi^ka%01+.)51+-&+>`qfs^qbqebpeofkb)ifpqbkqlL^`e^$kl^)grjmfkqlqebt^qbotebkebqbiipvlrqlyyNFAy./-0/y

Q@lksbopfkdTfqeqebAbmqepyKyQl^ir$rqebJvpqf`%16+.)42+4&yyNFAy./-0/y

@FkPbosf`blcqebRkelivyKyCfkaArhbS^iibke^i%14+4)2/+-&^kaq^hbefj_bilt02"eb^iqe)qebkrpbqebXRkelivDbjZlkefjyyNFAy././3yyRy03502y

E>dj^o$pE^jjboyKy?^oo^`hpJ^pqboE^od^%05+/)13+-&yyNFAy./-33y
Q?ifdeq_b^pqp?bA^jkbayKyS^iklhTfkao^dbo%04+/)12+5&yyNFAy./-4/y
QFkPbosf`blc?illayKyHliqfo^Ab^qetb^sbo%03+2)13+1&yyNFAy././2y
QFkPbosf`blcqebRkelivyKyHliqfo^Ab^qetb^sbo%03+2)13+1&yyNFAy././3y
QTebobqebTfiaQefkdpOl^jyKyPl^oE^thcrov%04+.)15+3&yyNFAy./...y
QMolgb`qflkp^kaMi^kpyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-3.y
>QebCl`rplkqeb?b^`eyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-33y

@QebCl`rplkqeb?b^`eyKyHfii@^mq^fkBjjvJ^ifk^q%/3+3)32+.&qldbqqebXIbvIfkbCl`rp@lkqoliOfkdZ^karpbfqlkqebdf^kq^o`eqebobyyNFAy./-33yyRy0342.y

QQebCl`rplkqeb?b^`eyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-33y
>>qlmqebTllai^kapyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-51y
>Pqobkdqebkqeb>k`fbkqpyKyB^oqet^oabkDofcb%03+2)14+5&yyNFAy./-63y

@>qlmqebTllai^kapyKyHfiiIfbrqbk^kqQ^$wfkkf%0/+/)4/+5&cloqebXIbvIfkbCl`rp@lkqoli>jribqZ)rpbfqlkqeb^o`eqebobyyNFAy./-51yyRy03446y
>>IbqqbocloEljbyKyQebfqbjXIfbrqbk^kqQ^$wfkkf$pIbqqboZpq^oqpnrbpq*aolmmba_vIfbrqbk^kqQ^$wfkkf%0/+/)4/+5&yyNFAy./-52yyRy0345-y
@Pqobkdqebkqeb>k`fbkqpyKyEb^aqlIlqe^iloTllai^kap%0.+5)3/+1&+Q^ihqlqebTllai^kapT^ihbocloX?^ohlcqebT^ihbopZ)qebkrpbfqlkqebIlqe^ilo>k`fbkqyyNFAy./-63yyRy03453y

Q>qlmqebTllai^kapyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./-51y
>Pb^o`eFkar$ibSfii^dbyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./.-3y
Q>IbqqbocloEljbyKyLsboiloa>dj^o%05+.)13+0&yyNFAy./-52y
QPqobkdqebkqeb>k`fbkqpyKyB^oqet^oabkDofcb%03+2)14+5&yyNFAy./-63y

QPb^o`eFkar$ibSfii^dbyKyJ^db*@ljj^kaboBsbkpq^o%1-+/)33+6&yyNFAy./.-3y
>QebBkalcqebIfkbyKyJ^db*@ljj^kaboBsbkpq^o%1-+/)33+6&yyNFAy./..-y

RRpbXIbvIfkbCl`rp@lkqoliQ^ifpj^kZyKyRpbXIbvIfkbCl`rp@lkqoliQ^ifpj^kZyyRy035.2yyNFAy././/y
@QebBkalcqebIfkbyKyDll_pbosbqeb>wrobAo^dlkpeofkbkloqeb^pqlcqltk%20+-)32+1&yyNFAy./..-y

cTvojobpqQbjmibyKyKbqebpqo^pw%3-+0)2.+2&yyNFAy././/y
QQebC^qblcqebOr_vAo^dlkpeofkbyKyHo^prp%26+5)21+3&yyNFAy./1.6y

C>dj^o$pE^jjboyKyKbqebpqo^pw%3-+0)2.+2&yyNFAy././/y
QQebBkalcqebIfkbyKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy./..-y
>D^fkfkd^k>rafbk`byKyFj^dblc>o`ej^db>bqe^pPrkob^sbo%05+-)13+0&yyNFAy././/y
KQefpfp^dllaqfjbql++++yKyQefpfp^dllaqfjbql`ljmibqbqeb0bifqbnrbpqp7T^kqba7J^dfpqboHbialkrp)T^kqba7Dfd^kq^ro)T^kqba7Aob^aq^ilk+Vlr`^k`lkqfkrbtfqeqebkbuqpqbmptefibvlrillhclo^dolrmcloqebpbyyNFAy./-62y
>QlAo^dlk$pC^iiyKy@^mq^fkDloq%02+5)15+1&yyNFAy./-62y

CTvojobpqQbjmibyKyK^owrkPhv_ob^hbo%04+2)12+4&yyNFAy./434y
eTvojobpqQbjmibyKyAbjbpqo^pw%26+5)21+0&yyNFAy./434y

QD^fkfkd^k>rafbk`byKyQ^oflipqo^pw%24+6)21+/&yyNFAy././/y
>Pmb^htfqevlro>j_^pp^aloyKyQ^oflipqo^pw%24+6)21+/&yyNFAy./434y
QPmb^htfqevlro>j_^pp^aloyKyDliir`hOl`hcfpq%25)23&yyNFAy./434y
>ObmloqqlqebOr_vAo^dlkpeofkbyKyDliir`hOl`hcfpq%25)23&yyNFAy./13.y
>QebL_pfaf^kAo^dlkpeofkbyKyK^if`b%3-+-)21+/&yyNFAy./114y
>JvpqbovlcqebFkcfkfqbyKy@eoljfb%3-+-)21+2&yyNFAy./14-y
>PbbaplcqebI^pebopyKyIloaFqe^ofrp%26+3)21+2&yyNFAy./125y

QObmloqqlqebOr_vAo^dlkpeofkbyKyS^od^pqo^pw%1/+6)2-+6&yyNFAy./13.y
>Eb^qba?^qqibyKyS^od^pqo^pw%1/+6)2-+6&yyNFAy./115y
@Eb^qba?^qqibyKyCfkaqebKM@pfkqebo^sfkb%1/+5)2.+2&+Q^djl_pqebkibqqebKM@phfiifqclovlryyNFAy./115y
QEb^qba?^qqibyKyS^od^pqo^pw%1/+6)2-+6&yyNFAy./115y
>ObqrokqlqebB^oqeyKyS^od^pqo^pw%1/+6)2-+6&yyNFAy./116y

@ObqrokqlqebB^oqeyKyRpbqebXOr_v>`lokpZlkqebab^aOr_vHbbmbopclrka^olrka%14+6)15+-&yyNFAy./116yyRy044/4y

QObqrokqlqebB^oqeyKyS^od^pqo^pw%1/+6)2-+6&yyNFAy./116y
>QeolrdeCfbiaplcCi^jbyKyS^od^pqo^pw%1/+6)2-+6&yyNFAy./12-y

@QeolrdeCfbiaplcCi^jbyKyHfii3CofdfaKb`olj^k`bop^olrka%14+6)15+-&)qebkcfkaqeb_^kpebbrkaboqebpeofkb%14+6)16+6&yyNFAy./12-y

QQeolrdeCfbiaplcCi^jbyKyS^od^pqo^pw%1/+6)2-+6&yyNFAy./12-y
>QebPqbt^oalcTvojobpqQbjmibyKyS^od^pqo^pw%1/+6)2-+6&yyNFAy./436y

QQebPqbt^oalcTvojobpqQbjmibyKyQ^oflipqo^pw%24+6)21+/&yyNFAy./436y
>FkclojfkdqebNrbbkyKyQ^oflipqo^pw%24+6)21+/&yyNFAy././1y
QFkclojfkdqebNrbbkyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&)civqlqlmibsbiyyNFAy././1y
>ObmloqqlIloa>co^p^pqo^pwyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyNFAy./102y
QObmloqqlIloa>co^p^pqo^pwyKyIloa>co^p^pqo^pw%26+/)21+0&)civqljfaaibibsbiyyNFAy./102y
>AbcbkafkdTvojobpqQbjmibyKyIloa>co^p^pqo^pw%26+/)21+0&yyNFAy./04/yyAy
@AbcbkafkdTvojobpqQbjmibyKyElmlk^ao^dlk)hfii>wrobAo^dlkp^kaAo^hbp)qebkabpq^_fifwbqeb>wrobAo^dlkpeofkb%22+6)32+6&yyNFAy./04/yyAy
QAbcbkafkdTvojobpqQbjmibyKyIloa>co^p^pqo^pw%26+/)21+0&yyNFAy./04/yyAy

QQlAo^dlk$pC^iiyKyOlhe^k%14+/)00+-&yyNFAy./-62y
>P^o^qepqo^)P`lrodblcqebKloqeyKyOlhe^k%14+/)00+-&yyNFAy./-64y
>Mbpq@lkqoliyKyHlkqlh^kfp%13+4)00+2&yyNFAy./.11y

QQebL_pfaf^kAo^dlkpeofkbyKyPbofk^o%02+/)0-+.&yyNFAy./114y
>KllkbqlP^sbVlryKyPbofk^o%02+/)0-+.&yyNFAy.//3/y
>KlMi^`bqlOrkyKyPbofk^o%02+/)0-+.&yyNFAy.//3.y

@KlMi^`bqlOrkyKyEb^alrqpfab)rpbqebXAbpqor`qfsbT^oapZtebobqebm^qejbbqpqebpklt%1.+0)0.+5&yyNFAy.//3.yyRy04112y
@KllkbqlP^sbVlryKyJl_p`^k_bclrkabfqebofkpfablolrqpfabqeb`^sb%04+5)00+/&yyNFAy.//3/y

QKllkbqlP^sbVlryKyPbofk^o%02+/)0-+.&yyNFAy.//3/y
QKlMi^`bqlOrkyKyPbofk^o%02+/)0-+.&yyNFAy.//3.y
>Qeb?bpqlcFkqbkqflkpyKyPbofk^o%02+/)0-+.&yyNFAy.//30y
@Qeb?bpqlcFkqbkqflkpyKyQ^hbqebm^qekloqeqlqebj^dj^tvojobproob`qflk`e^j_bo%0.+4)0-+2&yyNFAy.//30y
QQeb?bpqlcFkqbkqflkpyKyPbofk^o%02+/)0-+.&yyNFAy.//30y
>@riifkdqebA^jkbayKyPbofk^o%02+/)0-+.&yyNFAy.//31y
>AbcfifkdqebAbcfibopyKyPbofk^o%02+/)0-+.&yyNFAy.//32y
@@riifkdqebA^jkbayKyHfiijl_pcroqebofkpfabqeb`^sbp^olrka%0/+-)/5+1&yyNFAy.//31y
@AbcfifkdqebAbcfibopyKyCroqebofkpfabqeb`^sbp^olrka%0/+-)/5+1&)abpqolvqeborkb`fo`ibplkqebdolrkayyNFAy.//32y
QAbcfifkdqebAbcfibopyKyPbofk^o%02+/)0-+.&yyNFAy.//32y
Q@riifkdqebA^jkbayKyPbofk^o%02+/)0-+.&yyNFAy.//31y
>Kbqe^oflk$pCi^jbyKyPbofk^o%02+/)0-+.&yyNFAy.//34y
@Kbqe^oflk$pCi^jbyKyEb^a_^`hqlqebj^dj^tvojobproob`qflk`e^j_bo%0.+4)0.+.&)rpbXKbiqe^oflk$pCi^jbZ^kahfiiOlqefkqebAb`^vfkdyyNFAy.//34yyRy04206y
QKbqe^oflk$pCi^jbyKyPbofk^o%02+/)0-+.&yyNFAy.//34y
>Q^ibplcAbpqor`qflkyKyPbofk^o%02+/)0-+.&yyNFAy.//33y

QObqrokqlPbkaboyKyUfkh%22+-)/0+2&yyNFAy./136yyLy
>Pql`hfkdRmyKyUfkh%22+-)/0+2&yyNFAy./-11y
>Pe^sbaF`byKyWfsifu%21+4)/0+0&yyNFAy./-12y
>KlwwiborpqAbcbkpbyKyK^oc%21+2)/0+3&yyNFAy./-10y

@Pe^sbaF`byKy@ovpq^iifkbF`bBibj^kq^ip`^k_bclrka^ilkdqebofadb^q%21+/).5+6&yyNFAy./-12y

QPe^sbaF`byKyWfsifu%21+4)/0+0&yyNFAy./-12y
>PlcqM^`h^dfkdyKyWfsifu%21+4)/0+0&yyNFAy./-13y

@PlcqM^`h^dfkdyKyHfiiGlojrkd^oQrkkbibop^kaAo^dlk_lkb@lkalop^olrka%20+0)/2+.&yyNFAy./-13y

QPlcqM^`h^dfkdyKyWfsifu%21+4)/0+0&yyNFAy./-13y
>PljbqefkdQe^qAlbpk$qJbiqyKyWfsifu%21+4)/0+0&yyNFAy./-14y
>E^oaqlPt^iiltyKyUfkh%22+-)/0+2&yyNFAy./-16y

@KlwwiborpqAbcbkpbyKyHfiijl_p^qbfqebolcqebcolpqtvojafdp%23+.)/4+6&lo%2.+6)0-+5&yyNFAy./-10y
@Pql`hfkdRmyKyD^qebo5_rkaibplcX@ljmlpfqbLobZ^qbfqebolcqebcolpqtvojafdp%23+.)/4+6&lo%2.+6)0-+5&yyNFAy./-11y

@PljbqefkdQe^qAlbpk$qJbiqyKyCfka./XPmifkqboba?lkb@erkhpZ^olrkaqebao^dlk_lkbp%26+4)/3+3&)%20+0)/2+/&)%2.+2)/3+/&yyNFAy./-14y
@E^oaqlPt^iiltyKy>qq^`hqebbifqbp^olrka%26+4)/3+3&rkqfiqebvlmbkqebfojlrqepqebkrpbqebXMlqbkqBumilpfsb@e^odbpZmolsfabayyNFAy./-16yyRy0340/y

QPljbqefkdQe^qAlbpk$qJbiqyKyWfsifu%21+4)/0+0&yy./-14y
QE^oaqlPt^iiltyKyUfkh%22+-)/0+2&yyNFAy./-16y
QPql`hfkdRmyKyUfkh%22+-)/0+2&yyNFAy./-11y
>Irj_boE^`hyKyUfkh%22+-)/0+2&yyNFAy./-2-y
QKlwwiborpqAbcbkpbyKyK^oc%21+2)/0+3&yyNFAy./-10y
>E^omlkQefpyKyK^oc%21+2)/0+3&yyNFAy./-2/y

@E^omlkQefpyKyGrpqkloqe^q@liatfkaEbfdeqp%2/+6).6+4&+RpbXUfkh$pPeobaabo@lkqoliAbsf`bZ^kahfiiqebJfpqobpplcqeb@liatfka%12+0)..+3&yyNFAy./-2/yyRy03401y
@Irj_boE^`hyKyRpbXUfkh$pPeobaabo@lkqoliAbsf`bZql`elmj^ohbaqobbp^q^q@liatfkaEbfdeqp%2/+6).6+4&yyNFAy./-2-yyRy03401y

QIrj_boE^`hyKyUfkh%22+-)/0+2&yyNFAy./-2-y
QE^omlkQefpyKyK^oc%21+2)/0+3&yyNFAy./-2/y
>PqfccKbdlqf^qflkpyKyK^oc%21+2)/0+3&yyNFAy./../y

QPqfccKbdlqf^qflkpyKyWloq%26+2).5+.&yyNFAy./../y
>PifjMf`hfkdpyKyWloq%26+2).5+.&yyNFAy./-42y

@PifjMf`hfkdpyKyDbq^XP^jmiblcOl`hcibpeZ)grpqfkpfabqebF`bEb^oq@^sbok%23+.)./+-&yyNFAy./-42y

QPifjMf`hfkdpyKyWloq%26+2).5+.&yyNFAy./-42y
>Jbppv?rpfkbppyKyWloq%26+2).5+.&yyNFAy./-43y
>PqljmfkdDolrkapyKyHl$`e^oqebRk_ob^h^_ib%26+.).4+6&yyNFAy./-46y

@Jbppv?rpfkbppyKyHfiiGlojrkd^opfkpfabqebF`bEb^oq@^sbok%23+.)./+-&+RpbXWloq$pP`o^mboZtebkvlr$obpm^qlkyyNFAy./-43yyRy03442y
@PqljmfkdDolrkapyKyF`bEb^oqGlojrkd^oCbbabop^obclrkafkpfabqebF`bEb^oq@^sbok%23+.)./+-&yyNFAy./-46y

QJbppv?rpfkbppyKyWloq%26+2).5+.&yyNFAy./-43y
>>mmivQefpQtf`b>A^vyKyWloq%26+2).5+.&yyNFAy./-44y
QPqljmfkdDolrkapyKyHl$`e^oqebRk_ob^h^_ib%26+.).4+6&yyNFAy./-46y
Q>mmivQefpQtf`b>A^vyKyHl$`e^oqebRk_ob^h^_ib%26+.).4+6&yyNFAy./-44y
>Ob^iiv?fdTlojyKyHl$`e^oqebRk_ob^h^_ib%26+.).4+6&yyNFAy./-5-y
>TlojTo^kdiboyKyWloq%26+2).5+.&yyNFAy./-45y

@TlojTo^kdiboyKyCfkaGlojrkd^oPm^tkfkpfabqebF`bEb^oq@^sbok%23+.)./+-&+RpbqebXPqroav@o^qbpZqebkillqyyNFAy./-45yyRy0344.y

QTlojTo^kdiboyKyWloq%26+2).5+.&yyNFAy./-45y
QOb^iiv?fdTlojyKyHl$`e^oqebRk_ob^h^_ib%26+.).4+6&yyNFAy./-5-y

ETvojobpqQbjmibyKyAbjbpqo^pw%26+5)21+0&yyNFAy./126y

@Mbpq@lkqoliyKyHfiiAo^dlk_ifdeqJ^dk^q^rop^kaPkltmi^fkPkl_liap^q^kvlcqebfo`^jmpkb^o_v%22+/)1-+-&)%36+6)0.+.&)%32+2)2-+.&)%31+-)1/+5&yyNFAy./.11y

@FkPbosf`blcColpqyKyEb^aqlJfoololcqebA^tk^q%34+-)2/+2&+CfdeqqebF`bObsbk^kq)lk`b_bilt02"rpbqebXColpqDbjZyyNFAy././4yyRy03514y

@PbbaplcqebI^pebopyKyDlplrqeqlqebBjbo^iaAo^dlkpeofkb%30+2)4.+2&^kacfka0XI^peboPbbapZlkqebdolrkayyNFAy./125y

QQ^ibplcAbpqor`qflkyKyK^if`b%3-+-)21+/&yyNFAy.//33y
QPbbaplcqebI^pebopyKyIloaFqe^ofrp%26+3)21+2&yyNFAy./125y
>Qe^qTef`e@ob^qbp@^k>iplAbpqolvyKyIloaFqe^ofrp%26+3)21+2&yyNFAy./126y

@Qe^qTef`e@ob^qbp@^k>iplAbpqolvyKyRpbqebXPbbaplcK^qrob$pTo^qeZlkLsbopbboAb^qed^wbfkGfkqe^$h^i^o%56+1).5+6&)QrodfaqebSfibfkqeb_olhbkhbbm_biltK^uu%52+6)14+3&^ka^Ob^kfj^qbaColpqTvoj^olrkaTvojobpqQbjmib%24)13&yyNFAy./126yyRy04554y

>CrkafkdqebT^oBccloqyKyNr^oqboj^pqbo?^oqibqq%43+-)30+/&yyNFAy./0-0y
>J^qbofbiMirkaboyKyNr^oqboj^pqbo?^oqibqq%43+-)30+/&yyNFAy.//-6y

cSbkljpmfqbyKyGrkqboTbfpp%43+2)3/+0&yyNFAy.//-3y

>?ifdeqbaI^pqOfqbpyKy>mlqeb`^ovSf`hvIbsfkb%44+-)3/+6&yyNFAy.//-3y
>T^kqba7QebP`^oibqLkpi^rdeqyKyT^kqbaMlpqbo%43+6)3/+6&yyNFAy.//-2y
QFj_b`fibp>_lrkayKy@efbcMi^drb_ofkdboJfaaibqlk%44+4)3/+4&yyNFAy./.56y
>QebClop^hbk?ifdeq^kaVlr7EltKlqqlAfbyKy@efbcMi^drb_ofkdboJfaaibqlk%44+4)3/+4&yyNFAy./.55y

@?ifdeqbaI^pqOfqbpyKyRpbqebXCi^phlc?ifdeqZlkqebP`^oibqLkpi^rdeqMofplkbogrpqlrqpfab%44+.)3/+3&fkqeb`^dbyyNFAy.//-3yyRy04./6y
Q?ifdeqbaI^pqOfqbpyKy>mlqeb`^ovSf`hvIbsfkb%44+-)3/+6&yyNFAy.//-3y
>IbqQebjKlqOfpbyKy>mlqeb`^ovSf`hvIbsfkb%44+-)3/+6&yyNFAy.//..y

@T^kqba7QebP`^oibqLkpi^rdeqyKyDlqlKbtEb^oqedibk^ob^^olrka%4.+.)4.+/&^kahfiiqebp`^oibqjl_pebobyyNFAy.//-2y
@J^qbofbiMirkaboyKyIllqqebXP`^oibqLkpi^rdeq>ojloZ^kaXP`^oibqLkpi^rdeqTb^mlkpZp`^qqbobaqeolrdelrqqebp`^oibq`^jm%4.+.)4.+/&yyNFAy.//-6y
@IbqQebjKlqOfpbyKyRpbqebX@lkq^fkbolcO^qpZlkqeb`lompbplcqebp`^oibqjl_p%4.+.)4.+/&yyNFAy.//..yyRy04.54y

>?b^`ecolkqMolmboqvyKyProsbvloE^kpbk%46+1)32+.&yyNFAy./0-1y

@?b^`ecolkqMolmboqvyKyDlplrqeb^pqqlqeb_b^`e^q%50+/)4-+-&^kahfiiqeb>iif^k`bDelpqpebobyyNFAy./0-1y
@QebClop^hbk?ifdeq^kaVlr7EltKlqqlAfbyKyIllqB`qlmi^pjf`Obpfarbcoljqebdelpqp^olrka%50+/)4-+-&yyNFAy./.55y
@CrkafkdqebT^oBccloqyKyIllqqebClodlqqbkQob^probp`^qqboba^olrkaqeb_b^`e%50+/)4-+-&yyNFAy./0-0y

Q?b^`ecolkqMolmboqvyKyProsbvloE^kpbk%46+1)32+.&yyNFAy./0-1y

QJ^qbofbiMirkaboyKyNr^oqboj^pqbo?^oqibqq%43+-)30+/&yyNFAy.//-6y
QCrkafkdqebT^oBccloqyKyNr^oqboj^pqbo?^oqibqq%43+-)30+/&yyNFAy./0-0y
>CobpeObjlrkqpyKyE^kpbi?^rbo%43+-)3/+-&yyNFAy.//.1y
QT^kqba7P`^oibqLkpi^rdeqyKyEfdeBub`rqloTolqe%43+5)30+/&yyNFAy.//-2y

>KlJbo`vcloqeb@^mqrobayKyPmvJfpqobppObmfkb%43+5)30+.&yyNFAy.//12y
QIbqQebjKlqOfpbyKy>mlqeb`^ovSf`hvIbsfkb%44+-)3/+6&yyNFAy.//..y
>Pqb^ifkdcoljqebPfbdbpjfqepyKyAb^qedr^oaJliabo%43+2)3/+3&yyNFAy.//0-y
QQebClop^hbk?ifdeq^kaVlr7EltKlqqlAfbyKy@efbcMi^drb_ofkdboJfaaibqlk%44+4)3/+4&yyNFAy./.55y
>Bjbo^iaAo^dlkQb^opyKy@efbcMi^drb_ofkdboJfaaibqlk%44+4)3/+4&yyNFAy.//--y

@CobpeObjlrkqpyKyHfiiqebjlrkqbaP`^oibqHkfdeqp^olrka%4.+.)4.+/&^kaillqqebfoofafkd`olmp+QebkrpbqebXLkpi^rdeqOfafkd@olmZlkqebLkpi^rdeqT^oelopbqljlrkqfq+Ofabfq_^`hqlE^kpbi?^rbo%43)3/&+Vlroqlli_^otfiie^sb^phfiiqlobqrokqebelopbyyNFAy.//.1yyRy04/-/y
@KlJbo`vcloqeb@^mqrobayKyHfiiAb^qedr^oaP`ekbfabo%4.+2)4/+/&)@e^k`biilo>j^f%4/+3)4/+2&)Bkdfkbbo?rohb%4/+4)41+2&^kaPbkfloP`ofsbkbo?^oofd^%36+2)41+2&yyNFAy.//12y

QCobpeObjlrkqpyKyE^kpbi?^rbo%43+-)3/+-&yyNFAy.//.1y
QKlJbo`vcloqeb@^mqrobayKyEfdeBub`rqloTolqe%43+5)30+/&yyNFAy.//12y
>QloqrobqebQloqroboyKyEfdeBub`rqloTolqe%43+5)30+/&yyNFAy.//2/y

@QloqrobqebQloqroboyKyBkd^dbQloqroboIb@o^cq%36+4)4.+6&^karpbqebXEfdeBub`rqlo$p?o^kafkdFolkZlkefj2qfjbp)qebkhfiiefjyyNFAy.//2/yyRy040.1y
>QebOlalc@ljmripflkyKyQebfqbjXQloqrobo$pOlaZpq^oqpnrbpq*aolmmba_vQloqroboIb@o^cq%36+4)4.+6&yyNFAy.//4.yyRy0410/y

QQebOlalc@ljmripflkyKyEfdeBub`rqloTolqe%43+5)30+/&yyNFAy.//4.y
>QebAbklrk`bjbkqyKyEfdeBub`rqloTolqe%43+5)30+/&yyNFAy.//40y
QQloqrobqebQloqroboyKyEfdeBub`rqloTolqe%43+5)30+/&yyNFAy.//2/y

@QebAbklrk`bjbkqyKyRpbqebXOlalc@ljmripflkZlk?i^`hpjfqeDllaj^k%4-+6)4-+2&)@ljj^kaboGloa^kfp^qqebqlmlcqeb_^oo^`hp^q%36+6)4.+5&*Bkqbodlofdeq)ibcq)ibcq)ofdeqrmqebpq^fop)ibcq)qebkofdeq)rmqebo^jm)qebk^klqeboofdeq*)Pq^_ibJ^pqboJbo`bo%35+-)42+4&^kaIb^a@^kklkbboWfboerq%40+2)44+0&yyNFAy.//40yyRy04105y

QQebAbklrk`bjbkqyKyEfdeBub`rqloTolqe%43+5)30+/&yyNFAy.//40y

@Pqb^ifkdcoljqebPfbdbpjfqepyKyClrkakloqe^q@^ooflkCfbiap%54+6)2.+.&+HfiiqebPfbdbpjfqepeboblo`liib`q3XPfbdbpjfqe?lj_pZcoljqebdolrka^olrkaqebjyyNFAy.//0-y
@Qe^qTef`e@ob^qbp@^kAbpqolvyKyDlfkpfabqeb_rfiafkd^q%53+-)14+2&+RpbqebXPbbaplcK^qrob$pTo^qeZlkQrodfaqebSfibqebkhfiiefj*rkibppvlr^iob^av`ljmibqbaqefpnrbpqyyNFAy./126yyRy04554y

QPqb^ifkdcoljqebPfbdbpjfqepyKyAb^qedr^oaJliabo%43+2)3/+3&yyNFAy.//0-y
>?lj_^oaqeb?^iifpq^byKyAb^qedr^oaJliabo%43+2)3/+3&yyNFAy.//0/y
>>Jb^kpql^kBkayKy>mlqeb`^ovSf`hvIbsfkb%44+-)3/+6&yyNFAy.//1-y
>KbbaqlHkltyKyPmvJfpqobppObmfkb%43+5)30+.&yyNFAy.//01y

@KbbaqlHkltyKyQeb?^oo^`hp^ob^q%36+5)4.+6&)bkqboqebkdlofdeq)ibcq)ibcq)loabop^obclrkalkqebq^_ibkb^oqebpq^fop+Qeb>__bvfp^q%40+2)4/+3&)bkqboqebkdlibcq)pqo^fdeq)fkqlqebif_o^ovlkvlroibcq)dlqeolrdeqebofdeqallot^v^kaqebloabop^oblkqebq^_ib+Qeb?b^`eloabop^ob^q%4.+3)5-+1&yyNFAy.//01y
@?lj_^oaqeb?^iifpq^byKyRpbXPfbdbpjfqe?lj_pZql_iltrmqeb?^iifpq^$p^olrkaKbtEb^oqedibk%4.+.)4.+/&yyNFAy.//0/yyRy04/26y

@>Jb^kpql^kBkayKyDlqlqebJfiifkKbtEb^oqedibk^q%35+-)41+.&+RpbqebXIbsfkbC^jfivQbojfqbpZqlprjjlkClobj^kH^ibfhf^kahfiiefjyyNFAy.//1-yyRy040--y

Q>Jb^kpql^kBkayKy>mlqeb`^ovSf`hvIbsfkb%44+-)3/+6&yyNFAy.//1-y
>CfobRmlkqebT^qbopyKy>mlqeb`^ovSf`hvIbsfkb%44+-)3/+6&yyNFAy.//10y
QKbbaqlHkltyKyPmvJfpqobppObmfkb%43+5)30+.&yyNFAy.//01y
>QebPmvfkKbtEb^oqedibkyKyPmvJfpqobppObmfkb%43+5)30+.&yyNFAy.//06y
Q?lj_^oaqeb?^iifpq^byKyAb^qedr^oaJliabo%43+2)3/+3&yyNFAy.//0/y

QQebPmvfkKbtEb^oqedibkyKy>dbkqPhriiv%40+3)40+3&yyNFAy.//06y
>Tfqelrq^Mo^vboyKy>dbkqPhriiv%40+3)40+3&yyNFAy.//21y

@Tfqelrq^Mo^vboyKyHfii?fpelmPqobbq^q%36+/)43+3&^kaillqefpmo^vbo_llhyyNFAy.//21y

QTfqelrq^Mo^vboyKy>dbkqPhriiv%40+3)40+3&yyNFAy.//21y
>QebMbocb`qAfppbj_i^k`byKy>dbkqPhriiv%40+3)40+3&yyNFAy.//3-y
@QebMbocb`qAfppbj_i^k`byKyDlcfka^kLkpi^rdeqO^sbkMofbpq%4/)40&^karpbX?^kpebb$pJ^df`JfooloZlkqebjqlpqb^iqebfoobpbj_i^k`byyNFAy.//3-yyRy0405.y
QQebMbocb`qAfppbj_i^k`byKy>dbkqPhriiv%40+3)40+3&yyNFAy.//3-y
>>C^iiColjDo^`byKy>dbkqPhriiv%40+3)40+3&yyNFAy.//41y

@>C^iiColjDo^`byKyFkpfabqeb>__bvbkqbo^kadlofdeqqebkeb^apqo^fdeq^karmqebpmfo^ipq^fo`^pbqlofkdqeb_bii+Dl_^`haltkqlqeb_lqqlj^kaq^ihqlqebEfde>__lqq%40+2)41+0&yyNFAy.//41y

Q>C^iiColjDo^`byKy>dbkqPhriiv%40+3)40+3&yyNFAy.//41y
>QebQorqeTfiiLrqyKy>dbkqPhriiv%40+3)40+3&yyNFAy.//50y

@CfobRmlkqebT^qbopyKyEb^aqlqeb_l^q^q%4/+.)5/+6&+RpbqebX>mlqeb`^ov$p?rokfkdT^qboZlkqebp^filcqebpefm)qebknrf`hivorkm^pqqebab`he^kap^kafkqlqeb`^_fk+Hfii@^mq^fkPebiv^kaillqefpOrqqbopyyNFAy.//10yyRy040-1y

@QebQorqeTfiiLrqyKyCfkaXQebAf^ovlcEfdeDbkbo^i>__bkafpZlkqebqlmcillolcqebelrpb^q%35+0)43+6&fkKbtEb^oqedibkyyNFAy.//50y

QCfobRmlkqebT^qbopyKy>mlqeb`^ovSf`hvIbsfkb%44+-)3/+6&yyNFAy.//10y
QQebQorqeTfiiLrqyKyEfdeBub`rqloTolqe%43+5)30+/&yyNFAy.//50y
>AlRkqlLqebopyKyEfdeBub`rqloTolqe%43+5)30+/&yyNFAy.//52y

@Bjbo^iaAo^dlkQb^opyKyDlqlqebBjbo^iaAo^dlkpeofkb^q%30+4)4-+0&^ka`liib`qqebdobbkdbjplkqebdolrkayyNFAy.//--y

>@v`iblcIfcbyKyKfpebo^qebD^oabkHbbmbo%3/+2)40+0&)t^kabofkdKM@yyNFAy./121y
@@v`iblcIfcbyKyHfii2Bjbo^iaPhvq^ilkpcivfkd^olrka%31+.)43+3&yyNFAy./121y
Q@v`iblcIfcbyKyKfpebo^qebD^oabkHbbmbo%3/+2)40+0&)t^kabofkdKM@yyNFAy./121y
>QebMirjblc>ivpqolpyKyKfpebo^qebD^oabkHbbmbo%3/+2)40+0&)t^kabofkdKM@yyNFAy./123y

QBjbo^iaAo^dlkQb^opyKy@efbcMi^drb_ofkdboJfaaibqlk%44+4)3/+4&yyNFAy.//--y
>Pmob^aqebDllaTloayKy@efbcMi^drb_ofkdboJfaaibqlk%44+4)3/+4&yyNFAy.//.5y

@Pmob^aqebDllaTloayKyQebClop^hbk?ifdeqPmob^abo$p^ob^qqebb^pqd^qblcSbkljpmfqb+M^ohrm^q%53+-)23+5&^kahfii0-jl_pyyNFAy.//.5y
QPmob^aqebDllaTloayKy@efbcMi^drb_ofkdboJfaaibqlk%44+4)3/+4&yyNFAy.//.5y
>Clop^hbk?ifdeqyKy@efbcMi^drb_ofkdboJfaaibqlk%44+4)3/+4&yyNFAy.///.y
>Ql@lknrbpqElia)?rq?b@^obcriyKyEfdeBub`rqloTolqe%43+5)30+/&yyNFAy./154y

@JvpqbovlcqebFkcfkfqbyKyRpbqebXElrodi^pplcBqbokfqvZ^qqeb?olkwbAo^dlkpeofkb%4.+/)06+6&)molqb`qfqcoljqebao^dlkpqe^qpm^tkyyNFAy./14-yyRy046/0y

@Qe^qTef`e@ob^qbp@^k>iplAbpqolvyKyRpbqebXPbbaplcK^qrob$pTo^qeZlkLsbopbboAb^qed^wb^qGfkqe^$h^i^o%56+1).5+6&^kahfiiefj*rkibpp^iob^av`ljmibqbayyNFAy./126yyRy04554y

ETovjobpqQbjmibyKyAbjbpqo^pw%26+5)21+0&yyNFAy./.0/y
QQe^qTef`e@ob^qbp@^k>iplAbpqolvyKyIloaFqe^ofrp%26+3)21+2&yyNFAy./126y
QJvpqbovlcqebFkcfkfqbyKy@eoljfb%3-+-)21+2&yyNFAy./14-y

C>dj^o$pE^jjboyKyKbqebpqo^pw%3-+0)2.+2&yyNFAy./.0/y
QFkPbosf`blcColpqyKyHliqfo^Ab^qetb^sbo%03+2)13+1&yyNFAy././4y
>QebMltboqlAbpqolvyKyHliqfo^Ab^qetb^sbo%03+2)13+1&yyNFAy./.0/y
@QebMltboqlAbpqolvyKy>``bmqfkdqefptfiipbkavlrfkqlqebob^ijlcpe^altp+Hfii3Pe^altvQlojbkqlop^olrkavlr%03)13&yyNFAy./.0/y
QQebMltboqlAbpqolvyKyHliqfo^Ab^qetb^sbo%03+2)13+1&)ofdeq`if`hqeb_rccqlobjlsbyyNFAy./.0/y
>QebQo^kpmi^kqbaQljbyKyHliqfo^Ab^qetb^sbo%03+2)13+1&yyNFAy./.03y
QQebQo^kpmi^kqbaQljbyKy@^mq^fkDloq%02+5)15+1&yyNFAy./.03y
QClop^hbk?ifdeqyKyAl`qloPfkq^oJ^ibcflrp%03+.)15+5&yyNFAy.///.y
>QebHlo$holkS^kdr^oayKyLsboiloa>dj^o%05+.)13+0&yyNFAy.///1y

QMbpq@lkqoliyKyHlkqlh^kfp%13+4)00+2&yyNFAy./.11y
>@^kvlk@e^pbyKyHlkqlh^kfp%13+4)00+2&yyNFAy./.12y

@@^kvlk@e^pbyKy@e^pbqebPkl_liaaltkqeb`^kvlk)qfii%1/+5)1.+-&^kahfiiF`bcfpqebob+T^q`eclofqbjaolmXBj_i^wlkba?^qqibElokZqlpq^oqkbuqnrbpqyyNFAy./.12y
>Afpqro_fkdFjmif`^qflkpyKyQebfqbjXBj_i^wlkba?^qqibElokZpq^oqpnrbpq*aolmmba_vF`bcfpq%1/)1.&yyNFAy./.14yyRy03523y

Q@^kvlk@e^pbyKyHlkqlh^kfp%13+4)00+2&yyNFAy./.12y

QQebHlo$holkS^kdr^oayKyP^roc^kdqebVlrkdbo%1-+5).5+-&yyNFAy.///1y
>>rafbk`btfqeqebAo^dlkNrbbkyKyP^roc^kdqebVlrkdbo%1-+5).5+-&yyNFAy./163y
cHlo$horkS^kdr^oayKyKrjlPmfofq_obbwb%10+6).3+6&yyNFAy./.15y

CTvojobpqQbjmibyKyKrjlPmfofq_obbwb%10+6).3+6&yyNFAy./.15y
QAfpqro_fkdFjmif`^qflkpyKy>ro^pqo^pw^%3-+-)22+/&yyNFAy./.14y
>Lkblc^HfkayKy>ro^pqo^pw^%3-+-)22+/&yyNFAy./.15y
Q>rafbk`btfqeqebAo^dlkNrbbkyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyNFAy./163y
>D^i^holka^kaqebP`lrodbyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyNFAy./164y
QD^i^holka^kaqebP`lrodbyKyQlo^pqo^pw^%26+3)20+2&yyNFAy./164y
>LkOr_vTfkdpyKyQlo^pqo^pw^%26+3)20+2&yyNFAy./165y
@LkOr_vTfkdpyKyRpbqebXOr_v?b^`lklcqebAo^dlkNrbbkZ)civrmqlD^i^holka$pObpq%22+3)01+2&qlcfkaqebT^pqbpP`^sbkdbopqebkhfiiQef^ppfqebIfdeqkfkd?ofkdboqlpm^tkDo^kaKb`oliloa>kqflh%21+.)0-+3&yyNFAy./165yyRy050-/y

QLkblc^HfkayKy>ro^pqo^pw^%3-+-)22+/&yyNFAy./.15y
>JfdeqvJ^dk^q^royKy>ro^pqo^pw^%3-+-)22+/&yyNFAy./.16y

@JfdeqvJ^dk^q^royKyCfka^kahfiiF`bpe^qqbo%34+-)2-+-&)?illacb^pq%33+-)4-+-&^kaAo^hbdlob%35+-)1/+-&yyNFAy./.16y

QJfdeqvJ^dk^q^royKy>ro^pqo^pw^%3-+-)22+/&yyNFAy./.16y
>Ob`irpfsbOrkbj^pqboyKy>ro^pqo^pw^%3-+-)22+/&yyNFAy./.2-y
QLkOr_vTfkdpyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyNFAy./165y
>Obqrokql>kdo^qe^oyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyNFAy./2--y

CHlo$holkS^kdr^oayKyKbqebpqo^pw%3-+0)2.+2&y
QObqrokql>kdo^qe^oyKyP^roc^kdqebVlrkdbo%1-+5).5+-&yyNFAy./2--y

>A^ohkbppPqfopyKy>ibupqo^pw^qebIfcb*?fkabo%05+2).6+0&yyNFAy.0/1/y
@A^ohkbppPqfopyKy@liib`qXP^roc^kd?^qqib>ojloZ%05+.3).5+4.&yyNFAy.0/1/y
CT^oplkdEliayKyKrjlPmfofq_obbwb%10+6).3+6&yyNFAy.0/24y
QA^ohkbppPqfopyKyEfdeLsboiloaP^roc^kd%1.+1)20+4&yyNFAy.0/1/yyWy?lob^kQrkao^y
>Ebo^ialcT^oyKyEfdeLsboiloaP^roc^kd%1.+1)20+4&yyNFAy.0/24yyWy?lob^kQrkao^y
CArolq^oyKyQ^hbqebWbmmbifk_^`hqlArolq^oyyWy?lob^kQrkao^y
OLodofjj^oyKyQo^sbiqlLodofjj^oyyWyLodofjj^oy
QEbo^ialcT^oyKyQeo^ii%0/)04+6&yyNFAy.0/24yyWyLodofjj^oy
>>IfcbTfqelrqObdobqyKyQeo^ii%0/)04+6&yyNFAy.0/33yyWyLodofjj^oy
OQfofpc^iDi^abpyKyQ^hbqebmloq^iqlQfofpc^iDi^abpyyWyLodofjj^oy
Q>IfcbTfqelrqObdobqyKySli$gfk%3.+5)3/+3&yyNFAy.0/33yyWyQfofpc^iDi^abpy
>Qeb?^qqibcloqebRkabo`fqvyKySli$gfk%3.+5)3/+3&yyNFAy.0/34yyWyQfofpc^iDi^abpy
@Qeb?^qqibcloqebRkabo`fqvyKyT^fqlrqpfabrkabo`fqvrkqfiqebbsbkqobpbqp+Vlr`^kpbbte^qm^oqlcqebbsbkqfpq^hfkdmi^`b_vob^afkdqebqbuqfkaf`^qlop^qqebqlmjfaaiblcvlrop`obbk+Tebkqebbsbkqobpbqp)Qeo^ii^kaPvis^k^ptfiiob^mmb^olrqpfabRkabo`fqvyyNFAy.0/34yyWyQfofpc^iDi^abpy
OLodofjj^oyKyQ^hbqebmloq^iqlLodofjj^oy
QQeb?^qqibcloqebRkabo`fqvyKyQeo^ii%0/)04+6&yyNFAy.0/34yyWyLodofjj^oy

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)

