DugisGuideViewer:RegisterGuide("Grizzly Hills (75-76)", "Zul'Drak (76-78)", "Horde", "L", function()
return [[
AAA

O@lknrbpqEliayKyQo^sbiql@lknrbpqElia%/-+5)31+2&yyNFAy./.42y
e@lknrbpqEliayKy?^oo^`hpJ^pqboOebhhr%/-+5)31+2&yyNFAy./.42y
c@lknrbpqEliayKyHo^de%//+-)31+2&yyNFAy./.42y

>Do^vTlodEfabpyKyEfabqo^aboGrk$fh%//+-)32+.&yyNFAy./.42y
>Prmmibjbkq^iFk`ljbyKyMolsfpflkboIloho^k%//+3)33+.&yyNFAy./103y
QQl@lknrbpqElia_rq_b@^obcriyKy@lknrboloHobkk^%/-+5)31+/&yyNFAy./154y
>Qeb@lknrbolo$pQ^phyKy@lknrboloHobkk^%/-+5)31+/&yyNFAy./135y
>QebJ^df`^iHfkdaljlcA^i^o^kyKyJ^dfpqofuMe^bifpq^%/-+4)31+0&yyNFAy./46.y
QQeb@lknrbolo$pQ^phyKyPbodb^kqK^wdofj%/.+-)31+.&yyNFAy./135y
>>PeltlcPqobkdqeyKyPbodb^kqK^wdofj%/.+-)31+.&yyNFAy.//24y
>QebCi^jb_fkabop$Pb`obqpyKyPbodb^kqK^wdofj%/.+-)31+.&yyNFAy.//23y

QQebJ^df`^iHfkdaljlcA^i^o^kyKyQ^ihqlJ^dfpqofuMe^bifpq^qldbq^mloqqlA^i^o^k)>o`ej^db@bifkao^%23+/)14+.&yyNFAy./46.yyWyA^i^o^ky
>Ib^okfkdqlIb^sb^kaObqrok7QebJ^df`^iT^vyKy>o`ej^db@bifkao^%23+/)14+.&yyNFAy./46-yyWyA^i^o^ky
@Ib^okfkdqlIb^sb^kaObqrok7QebJ^df`^iT^vyKyRpbqebQbibmloq@ovpq^iKbuqql>o`ej^db@bifkao^%23+/)14+.&)qebkrpbqeblkbvlrdbqmloqbaql)qldbq_^`hyyNFAy./46-yyWyA^i^o^ky
QIb^okfkdqlIb^sb^kaObqrok7QebJ^df`^iT^vyKy>o`ej^db@bifkao^%23+/)14+.&yyNFAy./46-yyWyA^i^o^ky
cHo^prp$I^kafkdyKy>ira^kbTefqb`ilra%4/+2)12+1&yyWyA^i^o^kyyNFAy./.43y

C@lknrbpqEliayKy>ira^kbTefqb`ilra%4/+2)12+1&yyNFAy./.43y

@Prmmibjbkq^iFk`ljbyKyHfiiqebQ^iielokPq^dp^olrka%/.)4/&clo2XPr``ribkqSbkfplkZyyNFAy./103y
@Do^vTlodEfabpyKyHfiiqebDo^vjfpqErkqbop^olrka%/2)4-&clo0XDo^vTlodEfabpZyyNFAy./.42y

@QebCi^jb_fkabop$Pb`obqpyKyCfkaqebAo^dlkci^vboCi^jb_fkabop^qSliaorkb%/6)42&yyNFAy.//23y
@>PeltlcPqobkdqeyKyCfkaqebAo^dlkci^vboErp`^oip^qSliaorkb%/6)42&yyNFAy.//24y

QDo^vTlodEfabpyKyEfabqo^aboGrk$fh%//+-)32+.&yyNFAy./.42y
>>JfkloPr_pqfqrqflkyKyEfabqo^aboGrk$fh%//+-)32+.&yyNFAy./.43y
QPrmmibjbkq^iFk`ljbyKyMolsfpflkboIloho^k%//+3)33+.&yyNFAy./103y
Q>PeltlcPqobkdqeyKyPbodb^kqK^wdofj%/.+-)31+.&yyNFAy.//24y
QQebCi^jb_fkabop$Pb`obqpyKyPbodb^kqK^wdofj%/.+-)31+.&yyNFAy.//23y
>QebQe^kblcSliaorkbyKyPbodb^kqK^wdofj%/.+-)31+.&yyNFAy.//26y

@>JfkloPr_pqfqrqflkyKyHfiiDofwwiv?b^opproolrkafkd%02+0)41+/&clo3XDofwwivEfabpZyyNFAy./.43y

@QebQe^kblcSliaorkbyKyElmlkqebmolql*ao^hb%/4)45&fkSliaorkb+Qe^kbQlos^iaBofhpplkfplkqlmlcqebkb^o_vqltbo%/4+-)40+-&)_bprobqlhbbmefjpqrkkbatefipq^qq^`hfkdyyNFAy.//26y

Q>JfkloPr_pqfqrqflkyKyEfabqo^aboGrk$fh%//+-)32+.&yyNFAy./.43y
>Grk$fh$p@lsbormyKyEfabqo^aboGrk$fh%//+-)32+.&yyNFAy./.44y
QQebQe^kblcSliaorkbyKyPbodb^kqK^wdofj%/.+-)31+.&yyNFAy.//26y
>Lkt^oaql@^jmLkbnt^eyKyPbodb^kqK^wdofj%/.+-)31+.&yyNFAy./12.y
>JvBkbjv$pCofbkayKy@lknrboloHobkk^%/-+5)31+/&yyNFAy./1./y
@Grk$fh$p@lsbormyKyMolsfpflkboIloho^k%//+3)32+6&pbiipqebPfjmibCilro^kaPjfqeMofdh^%/0+/)30+/&cloqeb`l^iyyNFAy./.44y
QGrk$fh$p@lsbormyKyEfabqo^aboGrk$fh%//+-)32+.&yyNFAy./.44y
>AbifsbovqlHobkk^yKyEfabqo^aboGrk$fh%//+-)32+.&yyNFAy./.45y
QAbifsbovqlHobkk^yKy@lknrboloHobkk^%/-+5)31+/&yyNFAy./.45y

@JvBkbjv$pCofbkayKyPlrqeb^pq^qClobpq$pBadbMlpq+Si^abhfpfkqebqltbo%03+/)34+5&+T^q`eclofqbjaolmXJfhe^fi$pGlrok^iZqlpq^oqkbuqnrbpqyyNFAy./1./y
>Jfhe^fi$pGlrok^iyKyQebfqbjXJfhe^fi$pGlrok^iZpq^oqpnrbpq*aolmplccqebPfisbo_ollhErkqbop^kaSi^abh%03+/)34+5&yyNFAy./1/0yyRy0361-y

QJvBkbjv$pCofbkayKy@lknrboloHobkk^%/-+5)31+/&yyNFAy./1./y
QJfhe^fi$pGlrok^iyKy@lknrboloHobkk^%/-+5)31+/&yyNFAy./1/0y
>Dlodlkk^yKy@lknrboloHobkk^%/-+5)31+/&yyNFAy./1/1y
>>qq^`hlkPfisbo_ollhyKy@lknrboloHobkk^%/-+5)31+/&yyNFAy./1.0y
QDlodlkk^yKyDlodlkk^%/-+6)31+.&yyNFAy./1/1y
>Q^`qf`^i@ibjbk`vyKyDlodlkk^%/-+6)31+.&yyNFAy./1//y
>DllaQoliiErkqfkdyKyPbodb^kqQerohfk%//+/)31+1&yyNFAy.//-5y
>Bvbp>_lsbyKyTfkapbboDo^velok%//+2)3/+6&yyNFAy./120y

QDllaQoliiErkqfkdyKyP^jfo%.3+/)14+4&yyNFAy.//-5y
>Cfiifkdqeb@^dbpyKyP^jfo%.3+/)14+4&yyNFAy..651y

@Cfiifkdqeb@^dbpyKyQ^ihql?raa%.3+1)15+.&)qebkeb^aqlqebOrfkplcAo^h$Wfk%.0+4)25+3&^karpbvlrombq_^oqlpbkaefj^cqbo^qolii)qebkrpbqebX?lrkqvErkqbo$p@^dbZlk`ba^wbayyNFAy..651yyRy02403y

QCfiifkdqeb@^dbpyKyP^jfo%.3+/)14+4&yyNFAy..651y
>Qor`b<yKyAo^hror%.3+2)14+5&yyNFAy..656y
@Qor`b<yKyIllqqebXArii@^osfkdHkfcbZkbuqqlqeb`^db)rpbfq)qebkq^ihqlAo^hror%.3+2)14+5&qlpe^hbefpe^kayyNFAy..656yyRy05-50y
QQor`b<yKyAo^hror%.3+2)14+5&yyNFAy..656y
>Sf^ilcSfpflkpyKyAo^hror%.3+2)14+5&yyNFAy..66-y
?Fj_rbaSf^iyKyQ^ihql>jbbk^e%.3+-)14+5&^ka_rv^kFj_rbaSf^iyyIy.5/23yyNFAy..66.y

@Sf^ilcSfpflkpyKyXT^qbotbbaColkaZfpfkqebi^hb%.2+/)1-+3&+XE^wbIb^cZfpclrka^olrka%.0+.)1.+0&^ka%.0+-)05+6&yyNFAy..66-y

QQ^`qf`^i@ibjbk`vyKy@^mqrobaQo^mmbo%/.+6)0-+-&yyNFAy./1//y

@>qq^`hlkPfisbo_ollhyKyHfii5Pfisbo_ollhAbcbkabop^q%/1+3)00+0&yyNFAy./1.0y

QSf^ilcSfpflkpyKyAo^hror%.3+2)14+5&yyNFAy..66-y
>Pr_gb`qqlFkqbomobq^qflkyKyAo^hror%.3+2)14+5&yyNFAy..66.y
>P`lrodbh^_l_yKyMofdjlk%.2+5)13+5&yyNFAy./151y
@P`lrodbh^_l_yKyIllq^jrjjvqebkeb^aaltkqlqeb_lkcfob%.3+4)15+/&^ka_rokfqyyNFAy./151yyRy05.16y
QP`lrodbh^_l_yKyJ^`hCb^opbk%.3+4)15+0&yyNFAy./151y
>Pefjjbo`^mPqbtyKyMofdjlk%.2+5)13+5&yyNFAy./150y
>Pb^obaP`lrodbyKyJ^`hCb^opbk%.3+4)15+0&yyNFAy./-/6y

KPefjjbofkdPklt`^myKy>ilkdqebofsbo_^khplrqelcqebOrfkplcAo^h$Wfk%.-+3)30+6&yyNFAy./150yyNLyPefjjbofkdPklt`^m72,2y
HF`bPbombkqpyKy>iilsboqebOrfkplcAo^h$Wfk%.0+4)25+3&yyNFAy./150yyNLyF`bPbombkqBvb72,2y
HQoliipyKyFkqebOrfkplcAo^h$Wfk%.0+4)25+3&ql`liib`q2uXColwbkJlglZyyIy024662yyNFAy..66.y
QPr_gb`qqlFkqbomobq^qflkyKyFj^dblcAo^hror%.0+0)3-+6&+RpbXAo^hror$pBifufoZ^qqeb_o^wfboyyNFAy..66.yyRy02464y
>P^`ofcf`bpJrpq_bJ^abyKyFj^dblcAo^hror%.0+0)3-+6&yyNFAy./--4y

@Pefjjbo`^mPqbtyKy@liib`q2uXPtbbqollqZfp^iilsboWb_$E^i^h^olrka%.1+5)04+-&yyNFAy./150y
@P^`ofcf`bpJrpq_bJ^abyKyHfiiT^oiloaWfj$_l%.1+3)04+5&)eb^armqebwfddro^q^kaq^hbqebbvbcoljqebeb^aqebob%.4+6)03+2&yyNFAy./--4y
QP^`ofcf`bpJrpq_bJ^abyKyFj^dblcAo^hror%.4+16)03+0-&+RpbXAo^hror$pBifufoZ^qqeb_o^wfboyyNFAy./--4yyRy02464y
>Eb^oqlcqeb>k`fbkqpyNFAy./-1/yyKyFj^dblcAo^hror%.4+16)03+0-&y

@Pb^obaP`lrodbyKyDlqlAo^h$qe^olkHbbm%.4+5)/4+0&+Dlrmqebpq^fop^kagrjmlkqlqebbadbplcqebpq^fo`^pb+Il_XJ^`h$pA^ohDoldZ^qqebqoliip_biltyyNFAy./-/6yyRy026-5y

QEb^oqlcqeb>k`fbkqpyKyEb^oqlcqeb>k`fbkqp%04+-)0/+1&yyNFAy./-1/y
>JvEb^oqfpfkVlroE^kapyKyEb^oqlcqeb>k`fbkqp%04+-)0/+1&yyNFAy./5-/y

QJvEb^oqfpfkVlroE^kapyKyFj^dblcAo^hror%12+-)/5+0&+Hfiiqebproolrkafkdqoliipclo2XAbpmbo^qbJlglZyyNFAy./5-/y
>Slf`bpColjqebArpqyKyFj^dblcAo^hror%12+-)/5+0&yyNFAy./-35y

>CfkaHrorkyKyC^iibkB^oqebkT^ooflo%30+3)/0+/&yyNFAy..65.y

QCfkaHrorkyKyHrork%32+4).4+4&yyNFAy..65.y
>O^fkfkdAltkAbpqor`qflkyKyHrork%32+4).4+4&yyNFAy..65/y

@O^fkfkdAltkAbpqor`qflkyKyVlr`^kcfkaX?lriabopZ^q%34+-)./+.&)qeoltqebpbaltk_bilt^qqebat^osbp^q%36+.).1+2&yyNFAy..65/yyRy02401y

QO^fkfkdAltkAbpqor`qflkyKyHrork%32+4).4+4&yyNFAy..65/y
>O^iivfkdqebQollmpyKyHrork%32+4).4+4&yyNFAy./-4-y

@O^iivfkdqebQollmpyKyRpbqebXPe^oalcqebB^oqeZlklkblcqebcfdeqfkddf^kqp%4-+.)4+2&)qebkhfiiqebat^ocqe^qpm^tkpyyNFAy./-4-yyRy03431y

QO^iivfkdqebQollmpyKyHrork%32+4).4+4&yyNFAy./-4-y
>Fkqlqeb?ob^`eyKyHrork%32+4).4+4&yyNFAy..652y

>QebA^j^dbaGlrok^iyKy?^qqbobaGlrok^i%31+0).6+5&yyNFAy./-/3y
@QebA^j^dbaGlrok^iyKy@liib`qglrok^im^dbp^olrka%31+0).6+5&+Tebkvlre^sb5)`lj_fkbqebjtfqeqebXFk`ljmibqbGlrok^iZyyNFAy./-/3yyRy02406y

>FqQ^hbpDrqp+++yKyHo^w%40+6)01+.&yyNFAy./..3y
>Kf`bqlJb^qVlryKyE^ohlo%40+5)01+.&yyNFAy./..0y
>Qebo^mvyKyE^ohlo%40+5)01+.&yyNFAy./..1y

@Kf`bqlJb^qVlryKyHfiiArpheltiMoltibopbfqebo^qqeb`^sb%32+3)1/+2&lo^olrka%34+-)0-+4&^kaIlkdellcDo^wbop^q^_lrq%42+1)10+.&yyNFAy./..0yyRy03463y

>>?b^olc^k>mmbqfqbyKyErdeDi^pp%36+.)1-+.&yyNFAy.//46y

@FqQ^hbpDrqp+++yKyEb^aaltkfkqlqebAo^hfi$gfkOrfkp%4.+1)/0+6&+Lmbkg^opfkqebcfopq_fdollj^ilkdqebt^iipyyNFAy./..3y
@Slf`bpColjqebArpqyKyAbbmbofkqlqeborfkp)vlr$iicfkaqebXAo^hh^ofQ^_ibqpZfkqeb`lokbolc^pfabollj%36+1).5+.&yyNFAy./-35y
@Qebo^mvyKyHfiiqebqoliipproolrkafkdqeborfkp%4-+3)/4+0&yyNFAy./..1y
>Ark*a^*Ark*q^eyKyE^oofplkGlkbp%36+1).4+2&yyNFAy./-5/y
@Ark*a^*Ark*q^eyKyCliiltefjfkqlqeb`bobjlkf^i`e^j_bo)bsbkqr^iiv^kbifqbpk^hbtfiipm^tk+Ibqefjq^khfq^kahfii^kv^aapqe^qpm^tkyyNFAy./-5/y
QSlf`bpColjqebArpqyKyKltdlqlqeb_o^wfbo^q%4.+4)/3+.&^karpbXAo^hror$pBifufoZ+Q^ihqlqebFj^dblcAo^hror%.0+0)3-+6&yyNFAy./-35yyRy02464y
>@ib^kpfkdAo^h$Qe^olkyKyFj^dblcAo^hror%.0+0)3-+6&+Lkivq^hbqefpfcvlrmi^kqlorkqebfkpq^k`bAo^h$Qe^olkHbbmyyNFAy.//05y

QFqQ^hbpDrqp+++yKyHo^w%40+6)01+.&yyNFAy./..3y
>Ao^h$^drri$pJ^iibqyKyHo^w%40+6)01+.&yyNFAy././-y
QKf`bqlJb^qVlryKyE^ohlo%40+5)01+.&yyNFAy./..0y
QArk*a^*Ark*q^eyKyE^ohlo%40+5)01+.&yyNFAy./-5/y
QQebo^mvyKyE^ohlo%40+5)01+.&yyNFAy./..1y

@>?b^olc^k>mmbqfqbyKyRpbqebXCfpefkdKbqZlkqebp`elliplccfpe^olrkaqebOrfkplcQbqevp%45+1)03+2&yyNFAy.//46yyRy0421/y

@Ao^h$^drri$pJ^iibqyKyHfiiAo^h$^drri)ebm^qolipplrqelcqeborfkp%4/+5)0-+.&yyNFAy././-y

QAo^h$^drri$pJ^iibqyKyHo^w%40+6)01+.&yyNFAy././-y
>PbbVlrlkqebLqeboPfabyKyHo^w%40+6)01+.&yyNFAy././.y

@PbbVlrlkqebLqeboPfabyNFAy././.yyKyRpbqebX@e^odbaAo^hfi$gfkJ^iibqZ^qqebdlkdfkcolkqlcqebbkqo^k`bqlqeborfkp%4.+3)/1+3&yyRy03501y
QPbbVlrlkqebLqeboPfabyKyD^k$gl%36+2).6+2&yyNFAy././.y
>@efiiLrq)JlkyKyD^k$gl%36+2).6+2&yyNFAy./.04y
@@efiiLrq)JlkyKyLmbkqeb`ebpqqldbqqebXPkltlcBqbok^iPirj_boZ)qebkq^ihqlD^k$gl%36+2).6+2&clo^obw+Rpbqebpkltqlcobbwbqebqoliip^kaillqqeb`lompbqebvorkqlyyNFAy./.04yyRy03526y

Q@efiiLrq)JlkyKyHo^w%40+6)01+.&yyNFAy./.04y
>Gfk$>oo^h$pBkayKyHo^w%40+6)01+.&yyNFAy./.2/y

@Gfk$>oo^h$pBkayKyCfkaqeblccbofkdfkqebcfopqolljlcqeborfkp%4.+/.).6+32&+RpbqebXAo^hh^ofPmfofqArpqZlkfq)qebkeb^alrqpfabqlqebdlkd^kami^`bqeblccbofkdyyNFAy./.2/yyRy04-30y

QGfk$>oo^h$pBkayKyHo^w%40+6)01+.&yyNFAy./.2/y

Q>?b^olc^k>mmbqfqbyKyErdeDi^pp%36+.)1-+.&yyNFAy.//46y

QQebA^j^dbaGlrok^iyKyP^dbM^irk^%32+/)14+5&yyNFAy./-/3y
>Ab`fmebofkdqebGlrok^iyKyP^dbM^irk^%32+/)14+5&yyNFAy./-21y
QLkt^oaql@^jmLkbnt^eyKyP`lrqSlo$q^he%32+.)14+4&yyNFAy./12.y
>PefcqfkdMoflofqfbpyKyP`lrqSlo$q^he%32+.)14+4&yyNFAy./430y
>QebElopbEliiboboyKyPlrilhPqlojcrov%32+-)14+5&yyNFAy./1.2y
>QebRkbumb`qbaDrbpqyKyQloj^hqebP`^ooba%32+/)14+2&yyNFAy./.62y

c@^jmLkbnt^eyKyJ^hhfTfkqbod^ib%31+6)13+6&yyNFAy./-40y

@Ab`fmebofkdqebGlrok^iyKyCfka^kahfiiDorj_^iaLkb*Bvb%33+3)25+5&yyNFAy./-21y

@QebRkbumb`qbaDrbpqyKyHfiiqebPfisboelokPq^dp^olrka%34+-)13+4&yyNFAy./.62y

QAb`fmebofkdqebGlrok^iyKyP^dbM^irk^%32+/)14+5&yyNFAy./-21y
>MlrkafkdqebFolkyKyP`lrqSlo$q^he%32+.)14+4&yyNFAy./-40y
>QebOrkf`Molmeb`fbpyKyP^dbM^irk^%32+/)14+5&yyNFAy./-25y
QQebRkbumb`qbaDrbpqyKyQloj^hqebP`^ooba%32+/)14+2&yyNFAy./.62y
>>kFkqofdrfkdMi^kyKyQloj^hqebP`^ooba%32+/)14+2&yyNFAy./.32y

@QebElopbEliiboboyKyDlkloqeql%3/+-)0/+0&+RpbqebXCi^pe_^kdDobk^abZqlp`^obqebEfdei^kaJrpq^kdpyyNFAy./1.2yyRy044.3y

@MlrkafkdqebFolkyKyHfii^kvFolkAt^osbpfkpfabQeloJla^k^olrka%33+2).4+/&yyNFAy./-40y
@QebOrkf`Molmeb`fbpyKyOb^ab^`elcqeborkf`mi^qbp+Qefoa%35+2).3+/&)Cfopq%35+6).1+2&)Pb`lka%4-+/).1+4&yyNFAy./-25y
@Fkqlqeb?ob^`eyKyHfiiFolkQe^kb>odorj^qqebb^pqbkalcQeloJla^k%4-+2)./+6&yyNFAy..652y

QFkqlqeb?ob^`eyKyHrork%32+4).4+4&yyNFAy..652y
>D^sol`hyKyHrork%32+4).4+4&yyNFAy./-5.y

E@lknrbpqEliayKy?^oo^`hpJ^pqboOebhhr%/-+5)31+2&yyNFAy./1/2y
Q>qq^`hlkPfisbo_ollhyKy@lknrboloHobkk^%/-+5)31+/&yyNFAy./1.0y
>Orrk^qeb?ifkayKyDlodlkk^%/-+6)31+.&yyNFAy./1/2y
>Sloao^ppfi$pC^iiyKyTfkapbboDo^velok%//+2)3/+6&yyNFAy.//-4y
>QebA^ohkbpp?bkb^qeyKyTfkapbboDo^velok%//+2)3/+6&yyNFAy.//.0y

@Bvbp>_lsbyKyRpbqebXPfisboCb^qeboZlkqebFjmbof^iB^dibp_bqtbbk>pmbkDolsbMlpq^ka>j_bomfkbIladb%01+3)26+/&yyRy04544yyNFAy./120y

@Sloao^ppfi$pC^iiyKyHfiiBkqolmf`Llwbp^olrkaSloao^ppfi$pQb^op%/5+3)12+.&)Sloao^ppfi$pIfj_%00+/)15+0&loSloao^ppfi$pEb^oq%1-+5)2/+.&clo3XPifjbP^jmibpZyyNFAy.//-4y
KQebA^ohkbpp?bkb^qeyKySfpfqSloao^ppfi$pQb^op%/5+3)12+.&)Sloao^ppfi$pIfj_%00+/)15+0&^kaSloao^ppfi$pEb^oq%1-+5)2/+.&+Eb^aaltkqlqeb_lqqljlcb^`e^karpbqebXDblj^k`bo$pLo_ZyyNFAy.//.0yyRy04.40y

QPb^obaP`lrodbyKyJ^`hCb^opbk%.3+4)15+0&yyNFAy./-/6y
QPefjjbo`^mPqbtyKyMofdjlk%.2+5)13+5&yyNFAy./150y
>P^vEbiilqlJvIfqqibCofbkayKyMofdjlk%.2+5)13+5&yyNFAy./.6-y

QSloao^ppfi$pC^iiyKyTfkapbboDo^velok%//+2)3/+6&yyNFAy.//-4y
QBvbp>_lsbyKyTfkapbboDo^velok%//+2)3/+6&yyNFAy./120y
QQebA^ohkbpp?bkb^qeyKyTfkapbboDo^velok%//+2)3/+6&yyNFAy.//.0y
>>Mlppf_ibIfkhyKyTfkapbboDo^velok%//+2)3/+6&yyNFAy.///6y
>Qeb?b^oDla$pLccpmofkdyKyTfkapbboDo^velok%//+2)3/+6&yyNFAy.//0.y

C@^jmLkbnt^eyKyHo^de%//+-)31+2&yyNFAy.//-1y
QMlrkafkdqebFolkyKyP`lrqSlo$q^he%32+.)14+4&yyNFAy./-40y
QQebOrkf`Molmeb`fbpyKyP^dbM^irk^%32+/)14+5&yyNFAy./-25y
QQebElopbEliiboboyKyPlrilhPqlojcrov%32+-)14+5&yyNFAy./1.2y
>FkqebK^jblcIlhbkyKyP`lrqSlo$q^he%32+.)14+4&yyNFAy.//-1y

KFkqebK^jblcIlhbkyKyQ^ihqlErdeDi^pp%36+.)1-+.&yyNFAy.//-1y

QP^vEbiilqlJvIfqqibCofbkayKyE^ohlo%40+5)01+.&yyNFAy./.6-y

QD^sol`hyKyD^sol`h%46+4)00+4&yyNFAy./-5.y
>Orkbplc@ljmripflkyKyD^sol`h%46+4)00+4&yyNFAy./-60y
@FkqebK^jblcIlhbkyKyQ^ihqlD^sol`h%46+4)00+4&yyNFAy.//-1y

@Orkbplc@ljmripflkyKyHfii^iiclroat^osbpproolrkafkdqeborkbqlprjjlk?orklk%46+/)10+0&)Il`eif%41+6)03+6&)Hlod^k%4/+-)01+0&)Aros^i%34+4)/6+/&yyNFAy./-60y

QOrkbplc@ljmripflkyKyD^sol`h%46+4)00+4&yyNFAy./-60y
>I^qbkqMltboyKyD^sol`h%46+4)00+4&yyNFAy./-61y

@I^qbkqMltboyKyRpbqebXPe^oalcD^sol`hZ^qb^`elcqeb^k`fbkqpqlkbp)B^pq%45+5)06+6&)Plrqe%41+.)11+/&^kaKloqe%4.+/)06+4&yyNFAy./-61yyRy03454y

QI^qbkqMltboyKyD^sol`h%46+4)00+4&yyNFAy./-61y
>Cobb^qI^pqyKyD^sol`h%46+4)00+4&yyNFAy./-66y

@Cobb^qI^pqyKyRpbXD^sol`h$pOrkb_ob^hboZlkqebOrkbaDf^kqp^olrka%34)./&yyNFAy./-66yyRy03463y

QCobb^qI^pqyKyD^sol`h%46+4)00+4&yyNFAy./-66y

@>kFkqofdrfkdMi^kyKyHfiiFolkOrkb*Pjfqep^olrkaArk>odli%43+0)25+4&+Lk`bvlre^sb^iiqeobb`e^mqbop)rpblkbql`lj_fkbqebjyyNFAy./.32yyRy03516y

Q>kFkqofdrfkdMi^kyKyMolpmb`qloOlh^o%32+.)14+0&yyNFAy./.32y
>ColjqebDolrkaRmyKyMolpmb`qloOlh^o%32+.)14+0&yyNFAy./.63y
QFkqebK^jblcIlhbkyKyP`lrqSlo$q^he%32+.)14+4&yyNFAy.//-1y
>QebLsbopbbo$pPe^altyKyP`lrqSlo$q^he%32+.)14+4&yyNFAy.//-.y

@QebLsbopbbo$pPe^altyKyHfii^kFolkOrkbLsbopbbo^olrkaArk>odli%43+0)25+4&clo^kXLsbopbbo$pRkfclojZyyNFAy.//-.y
@ColjqebDolrkaRmyKyCfka5XT^oDlibjM^oqpZ^olrkaArk>odli%43+0)25+4&yyNFAy./.63y

QColjqebDolrkaRmyKyMolpmb`qloOlh^o%32+.)14+0&yyNFAy./.63y
>TbE^sbqebMltboyKyMolpmb`qloOlh^o%32+.)14+0&yyNFAy./.64y
QQebLsbopbbo$pPe^altyKyP`lrqSlo$q^he%32+.)14+4&yyNFAy.//-.y
>@riqfs^qfkd^kFj^dbyKyP`lrqSlo$q^he%32+.)14+4&yyNFAy.//-/y

@@riqfs^qfkd^kFj^dbyKyHfii5FolkAt^osbp^olrkaArk>odli%43+0)25+4&^karpbXOlh^o$p@^jbo^Zqlq^hbqebfomf`qrobpyyNFAy.//-/yyRy04-12y
@TbE^sbqebMltboyKyHfiiAro^o%42+-)24+-&^kaH^qelok%43+5)26+0&fkqebqtl_rfiafkdpqebobyyNFAy./.64yyRy04-12y

QTbE^sbqebMltboyKyMolpmb`qloOlh^o%32+.)14+0&yyNFAy./.64y
>+++LoJ^v_bTbAlk$qyKyMolpmb`qloOlh^o%32+.)14+0&yyNFAy./.65y
Q@riqfs^qfkd^kFj^dbyKyP`lrqSlo$q^he%32+.)14+4&yyNFAy.//-/y
>Ilhbk$pLoabopyKyP`lrqSlo$q^he%32+.)14+4&yyNFAy.//-0y

@+++LoJ^v_bTbAlk$qyKyPrjjlkqebdlibjrpfkdqebXDlibj@lkqoliRkfqZ^kahfiibibjbkq^ipgrpqlrqpfablcArk>odli^olrka%40+2)3.+.&yyNFAy./.65yyRy04-4.y
@Ilhbk$pLoabopyKyEb^aqlqebc^o_rfiafkdlkqebpb`lkaibsbi%5.+2)3-+0&^karpbqebXLsbopbboAfpdrfpbHfqZqlq^ihqlIlhbkyyNFAy.//-0yyRy03603y

Q+++LoJ^v_bTbAlk$qyKyMolpmb`qloOlh^o%32+.)14+0&yyNFAy./.65y
QIlhbk$pLoabopyKyP`lrqSlo$q^he%32+.)14+4&yyNFAy.//-0y
>?ofkdfkdAltkqebFolkQe^kbyKyP`lrqSlo$q^he%32+.)14+4&yyNFAy./.66y

@?ofkdfkdAltkqebFolkQe^kbyKyBkqboqeb_rfiafkd^q%42+5)3/+.&+Dlaltkpq^fop^karpbqebXDlibj@lkqoliRkfqZqlprjjlkqebdlibjql^qq^`hFolkQe^kbCrove^jjbo%43+1)30+4&+RpbqebBJMphfiicfopqqlafpormqqebpefbiayyNFAy./.66yyRy03532y

KQeb?b^oDla$pLccpmofkdyKyQ^ihqlHlaf^k%33+6)3/+0&yyNFAy.//0.y

Q?ofkdfkdAltkqebFolkQe^kbyKyQloj^hqebP`^ooba%32+/)14+2&yyNFAy./.66y

@>Mlppf_ibIfkhyKyHfiicro_ildp^olrkaqebO^dbC^kdPeofkb%15+-)25+5&^kaEb^oq$p?illaPeofkb%33+6)3/+3&yyNFAy.///6y

@Qeb?b^oDla$pLccpmofkdyKyQ^ihqlLoplkk%15+.)26+/&yyNFAy.//0.y

E@lknrbpqEliayKy?^oo^`hpJ^pqboOebhhr%/-+5)31+2&yyNFAy.//1.y
Q>Mlppf_ibIfkhyKyTfkapbboDo^velok%//+2)3/+6&yyNFAy.///6y
QQeb?b^oDla$pLccpmofkdyKyTfkapbboDo^velok%//+2)3/+6&yyNFAy.//0.y
>AbpqolvqebP^mifkdyKyTfkapbboDo^velok%//+2)3/+6&yyNFAy.//1.y
>Sloao^ppfi$pPbbapyKyTfkapbboDo^velok%//+2)3/+6&yyNFAy.//1/y

C@^jmLkbnt^eyKyHo^de%//+-)31+2&yyNFAy./0/5y

@AbpqolvqebP^mifkdyKyB^pq^qDofwwibj^t%2-+2)12+5&)grjmaltkfkqlqeb`bkqbo+RpbqebXSboa^kqQlo`eZlkqebp^mifkdyyNFAy.//1.yyRy040-3y
@Sloao^ppfi$pPbbapyKyCfka5XSloao^ppfi$pPbbapZ^olrka%2.)1.&+FkpfabSloao^ppfi$ppfabolljp)lolrqpfab^olrkaqebbadblcqebqorkh+Kloqepfablcqebqobbpbbjpifhb^dob^q^ob^yyNFAy.//1/y

QOrrk^qeb?ifkayKyOrrk^qeb?ifka%11+.)15+-&yyNFAy./1/2y
>Orrk^$pObnrbpqyKyOrrk^qeb?ifka%11+.)15+-&yyNFAy./0/5y

@Orrk^$pObnrbpqyKyCfkaqebCbokCbbaboJlqep^olrka%14+/)04+5&lo%2/+4)/5+/&yyNFAy./0/5y

QOrrk^$pObnrbpqyKyOrrk^qeb?ifka%11+.)15+-&yyNFAy./0/5y
>Lrqlc?lavBumbofbk`byKyOrrk^qeb?ifka%11+.)15+-&yyNFAy./0/4y
@Lrqlc?lavBumbofbk`byKyRpbqebXDlpp^jboMlqflkZpebd^sbvlryyNFAy./0/4yyRy0433.y
QLrqlc?lavBumbofbk`byKyOrrk^qeb?ifka%11+.)15+-&yyNFAy./0/4y
>C^qb^ka@lfk`fabk`byKyOrrk^qeb?ifka%11+.)15+-&yyNFAy./0/6y

QC^qb^ka@lfk`fabk`byKyP^pe^24+2)1.+/&yyNFAy./0/6y
>P^pe^$pErkqyKyP^pe^24+2)1.+/&yyNFAy./.01y
>>k^qlivTfiiQ^ihyKyP^pe^24+2)1.+/&yyNFAy./00-y

@P^pe^$pErkqyKyHfii./Plipqf`bErkqbop^olrka%3/)1/yyNFAy./.01y
@>k^qlivTfiiQ^ihyKyRpbqebXQo^knrfifwboA^oqZlkQ^qg^k^%3/)1/&tefibpeb$plkeboelopb)qebkelmlkqebelopbyyNFAy./00-yyRy04332y
Q>k^qlivTfiiQ^ihyKyP^pe^24+2)1.+/&yyNFAy./00-y
QP^pe^$pErkqyKyP^pe^24+2)1.+/&yyNFAy./.01y
>>Pfpqbo$pMibadbyKyP^pe^24+2)1.+/&yyNFAy./1..y

Q>Pfpqbo$pMibadbyKy>kv^%31+6)10+2&yyNFAy./1..y
>ElrolcqebTlodyKyP^pe^24+2)1.+/&yyNFAy./.31y

C@lknrbpqEliayKyJ^hhfTfkqbod^ib%31+6)13+6&yyNFAy.//03y
QAbpqolvqebP^mifkdyKyTfkapbboDo^velok%//+2)3/+6&yyNFAy.//1.y
QSloao^ppfi$pPbbapyKyTfkapbboDo^velok%//+2)3/+6&yyNFAy.//1/y
>Ropl`)Qeb?b^oDlayKyTfkapbboDo^velok%//+2)3/+6&yyNFAy.//03y

C@^jmLkbnt^eyKyHo^de%//+-)31+2&y
CWri$ao^hyKyQ^ihqlqebcifdeqj^pqbo^kaelm^cobbcifdeqqlIfdeq$p?ob^`efkWri$ao^hy
QPefcqfkdMoflofqfbpyKyPbodb^kqOf^kk^e%0/+.)41+2&yyNFAy./430yyWyWri$Ao^hy

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
