
DugisGuideViewer:RegisterGuide("Sholazar Basin (78-80)", "Sholazar Basin (78-80)", "Horde", "L", function()
return [[
AAA

CA^i^o^kyKyJ^^h^%3-+-)23+5&fkWri$Ao^hyyWyWri$Ao^hyyNFAy./2/.y
KCivfkdJlrkqQo^fkfkdyKyEfo^Pklta^tk%4-)12+2&`^kqo^fkvlrclo^iivlrocivfkdjlrkqqo^fkfkd)vlrtfiikbbaqldbq@liaTb^qeboQo^fkfkd^ptbiiqlcivfkKloqebokyyNFAy./2/.y
>TebobfkqebTloiafpEbjbqKbpfkdt^ov<yKy>o`ej^dbMbkq^orp%35+4)1/+2&yyNFAy./2/.yyWyA^i^o^ky

QTebobfkqebTloiafpEbjbqKbpfkdt^ov<yKyJlkqbJrwwibpelq%06+4)25+3&)Q^ihql>o`ej^dbMbkq^orpclo^cifdeq*mloq^iyyNFAy./2/.y
>Tbi`ljbqlPeli^w^o?^pfkyKyJlkqbJrwwibpelq%06+4)25+3&yyNFAy./156y

cKbpfkdt^ov?^pb@^jmyKyQebPmfofqlcDkljbobd^k%/2+0)25+2&yyNFAy./3/1y
eKbpfkdt^ov?^pb@^jmyKyMropbo?lrif^k%/3+5)26+/&yyNFAy./3/1y

QTbi`ljbqlPeli^w^o?^pfkyKyEbjbqKbpfkdt^ov%/4+.)25+4&yyNFAy./156y
>Fq@lria?b>kvtebobyKy@e^a%/3+6)26+-&yyNFAy./3/1y
>Sbkqrob@l+Jfp^asbkqrobyKyAb_^^o%/4+/)26+5&yyNFAy./2/1y
>Kbba^kBkdfkb)Q^hb^kBkdfkbyKyTbpibuNrf`htobk`e%/2+2)25+2&yyNFAy./2//y
@Kbba^kBkdfkb)Q^hb^kBkdfkbyNFAy./2//yyKy?^`haltkkb^otebobvlrm^o^`erqbafkqlqebTfiadoltqeJ^kd^i%05+3)23+5&y
QKbba^kBkdfkb)Q^hb^kBkdfkbyKyTbpibuNrf`htobk`e%/2+2)25+2&yyNFAy./2//y
>E^sb^M^oq)Dfsb^M^oqyKyTbpibuNrf`htobk`e%/2+2)25+2&yyNFAy./2/0y

>Bkdfkbbofkd^Afp^pqboyKyBkdfkbboEbif`b%02+3)14+0&yyNFAy./355y
@Bkdfkbbofkd^Afp^pqboyNFAy./355yyKyB^pvbp`loqnrbpqobnrfofkdvlrql_ofkdBkdfkbboEbif`blrqlcqeb^ob^p^cbivy
@E^sb^M^oq)Dfsb^M^oqyNFAy./2/0yyKyClrka^qPtfkaibdofk$pAfd^olrka%00+6)15+2&y
@Sbkqrob@l+Jfp^asbkqrobyNFAy./2/1yyKyClrka^qPtfkaibdofk$pAfd^olrka%00+6)15+2&y

QBkdfkbbofkd^Afp^pqboyKyEbjbqKbpfkdt^ov%/4+.)25+4&yyNFAy./355y
QSbkqrob@l+Jfp^asbkqrobyKyAb_^^o%/4+/)26+5&yyNFAy./2/1y
>TfmbQe^qDofkLccEfpC^`byKyAb_^^o%/4+/)26+5&yyNFAy./2/2y
QE^sb^M^oq)Dfsb^M^oqyKyTbpibuNrf`htobk`e%/2+2)25+2&yyNFAy./2/0y
>>bof^iProsbfii^k`byKyMolcbpplo@^isboq%/2+2)25+2&yyNFAy./363y

@TfmbQe^qDofkLccEfpC^`byNFAy./2/2yyKy?^`h^qqebafd)illhcloClobj^kPtfkaibdofk^kaJb^qmfblk^mi^qcloj^q%02+5)2-+1&y

QTfmbQe^qDofkLccEfpC^`byKyAb_^^o%/4+/)26+5&yyNFAy./2/2y
>Hf`h)Te^qHf`h<yKyAolpq^k%/4+.)26+6&yyNFAy./256y
@Hf`h)Te^qHf`h<yNFAy./256yyRy05240yyKyBnrfmqebXOGO*DbtbeoZ)e^sb^ifqqibq^odbqmo^`qf`by
QHf`h)Te^qHf`h<yKyAolpq^k%/4+.)26+6&yyNFAy./256y
>QebDob^qErkqbo$p@e^iibkdbyKyAolpq^k%/4+.)26+6&yyNFAy./26/y
>Aob^ap^_boJ^pqbov7?b`ljfkd^Moba^qloyKy?r`h@^kqtbii%/3+5)26+.&yyNFAy./216y
>OefklJ^pqbov7QebQbpqyKyEbjbqKbpfkdt^ov%/4+.)25+4&yyNFAy./2/-y

@OefklJ^pqbov7QebQbpqyNFAy./2/-yyKyKloqetbpqlc`^jm^olrka%/4+/)2/+6&y
@Aob^ap^_boJ^pqbov7?b`ljfkd^Moba^qloyNFAy./216yyKyKloqetbpqlc`^jm^ilkdqebpfabplcqebol^a^olrka%/4+/)2/+6&y

QAob^ap^_boJ^pqbov7?b`ljfkd^Moba^qloyKy?r`h@^kqtbii%/3+5)26+.&yyNFAy./216y
>Aob^ap^_boJ^pqbov7Pq^ihfkdqebMobvyKy?r`h@^kqtbii%/3+5)26+.&yyNFAy./22-y
QOefklJ^pqbov7QebQbpqyKyEbjbqKbpfkdt^ov%/4+.)25+4&yyNFAy./2/-y
>OefklJ^pqbov7Qeb@e^pbyKyEbjbqKbpfkdt^ov%/4+.)25+4&yyNFAy./2/3y
>>Pqb^hCfqclo^ErkqboyKyHlodqeb@ib^sbo%/3+5)26+3&yyNFAy./5-1y
>PljbJ^hbIbjlk^ab)PljbJ^hbIfnrloyKyDofj_llwbQerkabo_obt%/3+5)3-+-&yyNFAy./301y
>@ol`lifphJ^pqbov7QebQof^iyKyAb_^^o%/4+/)26+5&yyNFAy./22.y

QOefklJ^pqbov7Qeb@e^pbyKyLo^`ibPll*o^ej%/2+3)33+1&yyNFAy./2/3y
>>kLccbofkdcloPll*o^ejyKyLo^`ibPll*o^ej%/2+3)33+1&yyNFAy./210y

@Aob^ap^_boJ^pqbov7Pq^ihfkdqebMobvyNFAy./22-yyKyKloqe)^ilkdqebpeloblc?fqqboqfabI^hb%04+.)1.+6&y

@PljbJ^hbIbjlk^ab)PljbJ^hbIfnrloyNFAy./301yyKyPlrqeb^pqfkqebTfiadoltqeJ^kd^i%10+4)24+1&+Ork^olrkamriifkdsfkbp)qfiivlrdbqqebkbbabacorfqpy
@>kLccbofkdcloPll*o^ejyNFAy./210yyKyXFkq^`q@l_o^C^kdpZaolmlccBjmbolo@l_o^p^olrkaqebTfiadoltqeJ^kd^i%10+4)24+1&y
@@ol`lifphJ^pqbov7QebQof^iyNFAy./22.yyKyHfiiJ^kd^i@ol`lifphp^olrkaqebTfiadoltqeJ^kd^i%10+4)24+1&y

Q>kLccbofkdcloPll*o^ejyKyLo^`ibPll*o^ej%/2+3)33+1&yyNFAy./210y
>Qeb?lkbplcKlwolkkyKyLo^`ibPll*o^ej%/2+3)33+1&yyNFAy./211y
@Qeb?lkbplcKlwolkkyNFAy./211yyRy052.6yyKyArbplrqe)rpbXPll*o^ej$pFk`bkpbZ^qqeblccbofkd_ltifkcolkqlcqeb?lkbplcKlwolkk%/3+-4)4.+2-&y

@>Pqb^hCfqclo^ErkqboyNFAy./5-1yyKyHfiiilkdkb`hpdo^wbop^olrka%/5+.)33+-&y

QPljbJ^hbIbjlk^ab)PljbJ^hbIfnrloyKyDofj_llwbQerkabo_obt%/3+5)3-+-&yyNFAy./301y
>Pqfii>qFqyKyDofj_llwbQerkabo_obt%/3+5)3-+-&yyNFAy./311y
@Pqfii>qFqyNFAy./311yyKyMlpfqflkvlropbictfqefkob^`elc^iiqebj^qbof^ip_vqebpqfii%/3+4)26+5&+Q^ihqlQfmpvqlpq^oqqebafpqfiibo)qebkt^q`evlro`e^qclofkpqor`qflkp+y
QPqfii>qFqyKyDofj_llwbQerkabo_obt%/3+5)3-+-&yyNFAy./311y
>QebQ^pqbQbpqyKyDofj_llwbQerkabo_obt%/3+5)3-+-&yyNFAy./312y
Q>Pqb^hCfqclo^ErkqboyKyHlodqeb@ib^sbo%/3+5)26+3&yyNFAy./5-1y
QQebDob^qErkqbo$p@e^iibkdbyKyAolpq^k%/4+.)26+6&yyNFAy./26/y
Q@ol`lifphJ^pqbov7QebQof^iyKyAb_^^o%/4+/)26+5&yyNFAy./22.y
>@ol`lifphJ^pqbov7QebMi^kyKyAb_^^o%/4+/)26+5&yyNFAy./23-y
QAob^ap^_boJ^pqbov7Pq^ihfkdqebMobvyKy?r`h@^kqtbii%/3+5)26+.&yyNFAy./22-y
>Aob^ap^_boJ^pqbov7Ob^avqlMlrk`byKy?r`h@^kqtbii%/3+5)26+.&yyNFAy./225y
QQeb?lkbplcKlwolkkyKyEbjbqKbpfkdt^ov%/4+.)25+4&yyNFAy./211y
>OefklJ^pqbov7QebHfiiyKyEbjbqKbpfkdt^ov%/4+.)25+4&yyNFAy./223y
KEbjbq$pq^pqbqbpqyNFAy./312yyNLyEbjbq$pq^pqbqbpq7.,.yyRy05364yyKyRpbqebGrkdibMrk`ekb^oKbppv%/4+.)25+4&qle^sbefjq^pqbqbpqfq+y
KE^aofrp$q^pqbqbpqyNFAy./312yyNLyE^aofrp$q^pqbqbpq7.,.yyRy05364yyKyE^sbE^aofrpqbpqqll)eb$pgrpqlmmlpfqbEbjbq%/4+0)26+1&y

@@ol`lifphJ^pqbov7QebMi^kyNFAy./23-yyKyD^qebo2XP^kacbokpZ^ilkdqeb_^khplcqebofsbo^kaqebOfsbo$pEb^oqi^hb^olrka%14+-)3-+6&y

cOfsbo$pEb^oqyKyJ^osfkTl__ibpmol`hbq%2-+.)3.+2&yyNFAy./366y

Q>bof^iProsbfii^k`byKyMfilqSf`%2-+-)3.+3&yyNFAy./363y
>>kBj_^o^ppfkdFk`fabkqyKyMfilqSf`%2-+-)3.+3&yyNFAy./366y
>Clo`blcK^qrobyKyMfilqSf`%2-+-)3.+3&yyNFAy./5-0y
>QebM^oq*qfjbErkqboyKyQ^j^o^Tl__ibpmol`hbq%2-+2)3/+.&yyNFAy./321y
@QebQ^pqbQbpqyRy05364yyKyRpbqebXGrkdibMrk`eP^jmibZ^kadbqvlroi^pqq^pqbqbpqcoljQ^j^o^Tl__ibpmol`hbq%2-+2)3/+.&yyNFAy./312y
@>kBj_^o^ppfkdFk`fabkqyNFAy./366yyRy1-06-yyKyFkqebi^hb%15+3)30+6&)illhqeolrdeqebmfibplcafoq+RpbXSf`$pBjbodbk`v>foQ^khZfcvlrkbbaqly
Q>kBj_^o^ppfkdFk`fabkqyKyMfilqSf`%2-+-)3.+3&yyNFAy./366y
>Ob`lkk^fpp^k`bCifdeqyKyMfilqSf`%2-+-)3.+3&yyNFAy./34.y
@Ob`lkk^fpp^k`bCifdeqyNFAy./34.yyKyQebcfopqe^iclcqebcifdeqfplk^rql*mfilqlk`bvlrob^`eqeb^s^i^k`eb^ob^vlr$ii_b^qq^`hba_v_^qp)lk`bvlre^sb`lkqoliciv_^`hqlOfsbo$pEb^oq%2-+-)3.+3&y
QOb`lkk^fpp^k`bCifdeqyKyMfilqSf`%2-+-)3.+3&yyNFAy./34.y

@OefklJ^pqbov7QebHfiiyNFAy./223yyKyHfiiC^orkkqlqebkloqe)grpqplrqelcqebDifjjbofkdMfii^o%15+/)11+3&y
@Aob^ap^_boJ^pqbov7Ob^avqlMlrk`byNFAy./225yyKyHfiiPe^kdlqlqebtbpq)grpqkloqelcqebJ^hbo$pMbo`e%0/+4)02+3&y

@QebM^oq*qfjbErkqboyNFAy./321yyKyEb^aqlPhvob^`eMfii^o^q%2-+2)44+-&+HfiiMfq`e^kaillqefpobj^fkpy
>Mi^vfkd>ilkdyKyQo^`hboDbhdbh%2-+2)43+4&yyNFAy./2/5y

QMi^vfkd>ilkdyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./2/5y
>Qeb>mbErkqbo$pPi^sbyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./2/6y
>QlojbkqfkdqebPlcqhkr`hibpyKyRpbXDlobdbh$pPe^`hibpZqlprjjlkDlobdbhqebDlofii^ErkqboyyNFAy./20-yyRy053.6y

@Qeb>mbErkqbo$pPi^sbyNFAy./2/6yyKyDlplrqeb^pqql%33+2)40+4&Hfii5E^oahkr`hibClo^dbop^ka3@e^odbopy
@QlojbkqfkdqebPlcqhkr`hibpyNFAy./20-yyRy05134yyKyRpbqebXPlcqhkr`hibMlhboZqlqlojbkqqeb_^_vdlofii^p^q%33+2)40+4&)tef`eprjjlkp^E^oahkr`hibJ^qof^`eqlhfiiy

QQlojbkqfkdqebPlcqhkr`hibpyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./20-y
QQeb>mbErkqbo$pPi^sbyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./2/6y
>QebT^pmErkqbo$p>mmobkqf`byKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./200y
>QebP^mmefobNrbbkyKyBiaboE^ohbh%22+2)36+3&yyNFAy./201y

@QebT^pmErkqbo$p>mmobkqf`byKyEb^aqlqebP^mme^fobEfsb^q%3-+-)44+6&+Hfii6EfsbAolkbp^ka3T^pmpyyNFAy./200y
@QebP^mmefobNrbbkyNFAy./201yyKyDlfkpfabqebild^kaqlqebsbov_lqqljlcqeb`^sb^kahfiiqebP^mmefobEfsbNrbbk%24+/)46+1&^kaillqebopqfkdboy

QQebT^pmErkqbo$p>mmobkqf`byKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./200y
QQebP^mmefobNrbbkyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./201y
>Ciltkqeb@llmyKyBiaboE^ohbh%22+2)36+3&yyNFAy./20/y
@Ciltkqeb@llmyNFAy./20/yyRy05356yyKyRpbqebX@ef`hbkKbqZqlnrf`hivqo^mqeb`ef`hbk)_rqalklq`e^pbqebjloqebvtfiiork)lk`bqo^mmba)illqy
QCiltkqeb@llmyKyBiaboE^ohbh%22+2)36+3&yyNFAy./20/y
>QebRkabodolrkaJbk^`byKyBiaboE^ohbh%22+2)36+3&yyNFAy./20.y
>Jfp`efbcfkqebJ^hfkdyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./202y

@Jfp`efbcfkqebJ^hfkdyNFAy./202yyKyEb^aqlqebofsbo^q%2.+3)53+/&^kaillq5lcqebXPhvob^`e@ovpq^i@irpqbopZ^ilkdqebofsboy
@QebRkabodolrkaJbk^`byNFAy./20.yyKyCfka^kahfiiPbocbuqebOb^sbotelfprkabodolrka^p^tloj^olrka%16+3)52+2&lo%25+5)52+2&y

QJfp`efbcfkqebJ^hfkdyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./202y
QQebRkabodolrkaJbk^`byKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./20.y
>>OlrdeOfabyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./203y

@>OlrdeOfabyNFAy./203yyKyQ^ihqlqeb@^mqfsb@ol`lifph%24+0)35+1&qebobqldbq^ofabqlJfpqtefpmboObcrdby
Q>OlrdeOfabyKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`ErkqboyyNFAy./203yyRy052./y
>IfdeqkfkdAbcfkfqbivPqofhbpQtf`byKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`ErkqboyyNFAy./204yyRy052./y
>QebJfpqFpk$qIfpqbkfkdyKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`ErkqboyyNFAy./205yyRy052./y
@QebJfpqFpk$qIfpqbkfkdyKyHfii./JfpqtefpmboDloil`p^olrkaqebobcrdb^q%12+-)04+-&yyNFAy./205y
@IfdeqkfkdAbcfkfqbivPqofhbpQtf`byNFAy./204yyRy052.-yyKyRpbqebXPhvob^`e@ovpq^i@irpqbopZ^qqeb_^pblcqebPeofkb^q%12+-)04+-&qebk`if`hqeb`ovpq^iqlp^_lq^dbfqy
QIfdeqkfkdAbcfkfqbivPqofhbpQtf`byKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`ErkqboyyNFAy./204yyRy052./y
QQebJfpqFpk$qIfpqbkfkdyKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`ErkqboyyNFAy./205yyRy052./y
>EllcfkdFqyKyRpbXWbmfh$pErkqfkdElokZqlprjjlkWbmfhqebDloil`ErkqboyyNFAy./206yyRy052./y

QEllcfkdFqyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./206y
>GrpqCliiltfkdLoabopyKyEfde*Pe^j^kO^hg^h%22+.)36+/&yyNFAy./21-y

QGrpqCliiltfkdLoabopyKyFkgrobaO^fkpmb^hboLo^`ib%22+4)32&)tfiipm^tk^klk*bifqb`ol`lifphyyNFAy./21-y
>Cloqrk^qbJfprkabopq^kafkdpyKyFkgrobaO^fkpmb^hboLo^`ib%22+4)32&yyNFAy./24-y

QCloqrk^qbJfprkabopq^kafkdpyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./24-y
>J^hbqeb?^aPk^hbDl>t^vyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./24.y
>DlapIfhbPefkvQefkdpyKyRpbXI^cll$p?rd?^dZqlprjjlkI^cllyyNFAy./24/yyRy053//y

@J^hbqeb?^aPk^hbDl>t^vyKyHfiiqebBjmbolo@l_o^p^olrka%21+-)2-+-&^kaSbkljqfm^q%25+0)21+4&yyNFAy./24.y
@DlapIfhbPefkvQefkdpyKyTefipqhfiifkd`l_o^pt^ih^olrkaqebpefkv^ob^lcafoq^olrka%21+-)2-+-&plI^cll`^kafdrmXPefkvQob^probpZyyNFAy./24/yyRy053//y

QJ^hbqeb?^aPk^hbDl>t^vyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./24.y
QDlapIfhbPefkvQefkdpyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./24/y
>J^hfkdMb^`byKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./240y

@J^hfkdMb^`byNFAy./240yyKyPmb^htfqePe^j^kSbhgfh%2.+0)31+4&y

QJ^hfkdMb^`byKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./240y
>?^`hPlPllk<yKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./241y

QOefklJ^pqbov7QebHfiiyKyEbjbqKbpfkdt^ov%/4+.)25+4&yyNFAy./223y
QAob^ap^_boJ^pqbov7Ob^avqlMlrk`byKy?r`h@^kqtbii%/3+5)26+.&yyNFAy./225y
Q@ol`lifphJ^pqbov7QebMi^kyKyAb_^^o%/4+/)26+5&yyNFAy./23-y
>@ol`lifphJ^pqbov7Qeb>j_rpeyKyAb_^^o%/4+/)26+5&yyNFAy./236y
QQebQ^pqbQbpqyKyDofj_llwbQerkabo_obt%/3+5)3-+-&yyNFAy./312y
@@ol`lifphJ^pqbov7Qeb>j_rpeyNFAy./236yyRy05231yyKyLkqebb^pq_^khlcOfsbo$pEb^oqi^hb)rpbqebXP^kacbokAfpdrfpbZkb^oqebc^iibkild%14+6)33+.&y
Q@ol`lifphJ^pqbov7Qeb>j_rpeyKyAb_^^o%/4+/)26+5&yyNFAy./236y
QFq@lria?b>kvtebobyKy@e^a%/3+6)26+-&yyNFAy./3/1y
>FkPb^o`elc?fddboD^jbyKyEbjbqKbpfkdt^ov%/4+.)25+4&yyNFAy./262y

Q?^`hPlPllk<yKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./241y
>QebIlpqJfpqtefpmboQob^probyKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./242y
>Clo`baE^kayKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./243y

QFkPb^o`elc?fddboD^jbyKyAlof^kAo^hbpq^ihbo%1/+1)/5+4&yyNFAy./262y
>Pe^ombkfkdVlroQ^ilkpyKyAlof^kAo^hbpq^ihbo%1/+1)/5+4&yyNFAy./3-0y
>Pb`rofkdqeb?^fqyKyAlof^kAo^hbpq^ihbo%1/+1)/5+4&yyNFAy./3-2y
>?rokfkdqlEbimyKy@lisfkKloofkdqlk%1/+.)/5+3&yyNFAy./350y

@?rokfkdqlEbimyNFAy./350yyRy06.31yyKyPlrqefkqebi^hb)^qq^`h?fqqboqfabEvao^p^olrka%1-+4)1.+.&)tebkefqtfqemlfplkrpbqebXP^jmib@lkq^fkboZy
@Pb`rofkdqeb?^fqyNFAy./3-2yyKyGrpqqlqebb^pqlcqeblrqmlpqfkqebP^s^dbQef`hbq%14+.)/4+-&+>qq^`hbddp^kaillqqebXMofjloaf^iE^q`eifkdpZy
@Pe^ombkfkdVlroQ^ilkpyNFAy./3-0yyKyGrpqqlqebb^pqlcqeblrqmlpqfkqebP^s^dbQef`hbq%14+.)/4+-&y

QPe^ombkfkdVlroQ^ilkpyKyAlof^kAo^hbpq^ihbo%1/+1)/5+4&yyNFAy./3-0y
QPb`rofkdqeb?^fqyKyAlof^kAo^hbpq^ihbo%1/+1)/5+4&yyNFAy./3-2y
>Ob^dbkq>dbkqyKy@lisfkKloofkdqlk%1/+.)/5+3&yyNFAy./35.y
Q?rokfkdqlEbimyKy@lisfkKloofkdqlk%1/+.)/5+3&yyNFAy./350y
>>J^jjlqeRkaboq^hfkdyKyWllqcfwwib%1/+/)/5+6&yyNFAy./3-4y
>JvMbqOl`yKyWllqcfwwib%1/+/)/5+6&yyNFAy./325y
@>J^jjlqeRkaboq^hfkdyNFAy./3-4yyRy053/4yyKyRpbqebXJ^jjlqeE^okbppZlk^j^jjlqe^olrka%2/+/)/1+6&^ka_ofkdefj_^`hqlWllqcfwwiby
Q>J^jjlqeRkaboq^hfkdyKyWllqcfwwib%1/+/)/5+6&yyNFAy./3-4y
>Mlpq*m^oqrj>ddobppflkyKyAlof^kAo^hbpq^ihbo%1/+1)/5+4&yyNFAy./3.1y

@Mlpq*m^oqrj>ddobppflkyNFAy./3.1yyKyCfka?ollajlqeboPifsfk^lkqebkloqebkalcqebP^s^dbQef`hbq%13+5)/.+2&y
@Ob^dbkq>dbkqyNFAy./35.yyKy@liib`q2XQtfpqbaOl`Q^ilkpZcoljjl_p^qqeb?lkbcfbiap%22+5)/2+-&y
@JvMbqOl`yNFAy./325yyKy@liib`q4XOl`BddpZtbpq^qqeb?lkbcfbiap%22+5)/2+-&y

QMlpq*m^oqrj>ddobppflkyKyAlof^kAo^hbpq^ihbo%1/+1)/5+4&yyNFAy./3.1y
QOb^dbkq>dbkqyKy@lisfkKloofkdqlk%1/+.)/5+3&yyNFAy./35.y
QJvMbqOl`yKyWllqcfwwib%1/+/)/5+6&yyNFAy./325y

@Clo`baE^kayNFAy./243yyRy053/0yyKy>qqebCobkwveb^oq`^jm%1-+3)/1+0&+RpbG^illqclobuqo^AMPlkqebjl_peboby
@QebIlpqJfpqtefpmboQob^probyNFAy./242yyKyRpbqeb>iq^o^q%1.+2).6+3&qlprjjlkT^oiloaQ^oqbh^kaefpao^dlk)hfiiqebj_lqe^kaillqqebXJfpqtefpmboQob^probZy

QQebIlpqJfpqtefpmboQob^probyKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./242y
QClo`baE^kayKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./243y
>EljbQfjbyKyJfpq`^iiboPll*d^k%1/+/)05+3&yyNFAy./244y
QEljbQfjbyKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./244y
>Qeb>kdovDloil`yKyEfde*Lo^`ibPll*p^v%21+2)23+1&yyNFAy./245y
QQebM^oq*qfjbErkqboyKyQ^j^o^Tl__ibpmol`hbq%2-+2)3/+.&yyNFAy./321y

QClo`blcK^qrobyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./5-0y
>>kFpprblcQorpqyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./23.y
@>kFpprblcQorpqyNFAy./23.yyKy?lqejl_p`^k_bclrka^olrka%4/+6)26+/&y
Q>kFpprblcQorpqyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./23.y
>ObqrokbaPbsbkcliayKy>s^q^olcCobv^%31+3)15+3&yyNFAy./3..y
@ObqrokbaPbsbkcliayNFAy./3..yyRy05324yyKyHfiiQe^ido^k?ifdeq_ofkdbogrpqqlqebkloqe%33+4)11+0&+Tebkebpq^oqp`^pqfkdAb^qe_liqrpbXCobv^$pT^oaZy
QObqrokbaPbsbkcliayKy>s^q^olcCobv^%31+3)15+3&yyNFAy./3..y
>QebC^iibkMfii^oyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./3./y
>P^is^dfkdIfcb$pPqobkdqeyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./5-2y

QQebC^iibkMfii^oyKy@riqfpq@lompb%32+.)3-+2&yyNFAy./3./y
>@riqfpqFk`ropflkyKy@riqfpq@lompb%32+.)3-+2&yyNFAy./3-5y
@P^is^dfkdIfcb$pPqobkdqeyNFAy./5-2yyRy1-064yyKyHfiibibjbkq^ip^olrka4.+/)26+6^karpbqebXIfcb_illaDbjZlkqebjy

Q@riqfpqFk`ropflkyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./3-5y
QP^is^dfkdIfcb$pPqobkdqeyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./5-2y
>Buqbojfk^qbqebFkqorabopyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./3.4y
>Tb^mlkplcAbpqor`qflkyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./33-y

@Tb^mlkplcAbpqor`qflkyNFAy./33-yyKyBumilpfsbp^obp`^qqbobakloqetbpq^qqebAb^qe$pE^kaBk`^jmjbkq%22+1)1.+0&y
@Buqbojfk^qbqebFkqorabopyNFAy./3.4yyKyJl_pclrka^olrkaAb^qe$pE^kaBk`^jmjbkq%22+1)1.+0&y

QBuqbojfk^qbqebFkqorabopyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./3.4y
QTb^mlkplcAbpqor`qflkyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./33-y
>QebIfcbt^oabk$pTo^qeyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./3/-y
@QebIfcbt^oabk$pTo^qeyNFAy./3/-yyRy05351yyKyCivqlqebqlmlcqebDifjjbofkdMfii^o%16+2)03+4&^karpbXCobv^$pElokZy
QQebIfcbt^oabk$pTo^qeyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./3/-y
>Cobv^$pM^`qyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./3/.y
@Cobv^$pM^`qyNFAy./3/.yyKyQ^ihql>s^q^olcCobv^%31+3)15+3&^kaifpqbkqlebopqlovy
QCobv^$pM^`qyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./3/.y
>MltbofkdqebT^vd^qb*QebJ^hbo$pMbo`eyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./226y

@MltbofkdqebT^vd^qb*QebJ^hbo$pMbo`eyNFAy./226yyKyJ^hbvlrot^vfkpfabJ^hbo$pMbo`eql%/3+0)02+2&qlcfkaqebptfq`ey

QMltbofkdqebT^vd^qb*QebJ^hbo$pMbo`eyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./226y
>MltbofkdqebT^vd^qb*QebJ^hbo$pLsboillhyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./3.0y

>>Qfjbtlok@lccboyKyQfjbtlok@lccbo%5-+2)22+6&yyNFAy./36.y

@MltbofkdqebT^vd^qb*QebJ^hbo$pLsboillhyNFAy./3.0yyKyJ^hbvlrot^vqeolrdeJ^hbo$pLsboillh)pkb^hm^pqqebbifqbqlqebptfq`e^q%55+.)2/+-&y
@>Qfjbtlok@lccboyNFAy./36.yyKyHfiiPeli^w^oDr^oaf^kpfkqebJ^hbo$pLsboillh%5.+-)21+1&qfiiqebXErdbPqlkbHbvZaolmpy
Q>Qfjbtlok@lccboyKyQfjbtlok@lccbo%5-+2)22+6&yyNFAy./36.y

QQeb>kdovDloil`yKyQo^sbiqlJlppt^ihboSfii^db^olrka%42)2/&qebkRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyNFAy./245yyRy053/1y
>QebJlppt^ihboP^sfloyKyRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyNFAy./25-yyRy053/1y
>Ifcb_illalcqebJlppt^ihboPeofkbyKyRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyNFAy./246yyRy053/1y
@QebJlppt^ihboP^sfloyKyDl^olrkaqeb`^jm%43+-)2/+6&^kaq^ihqlqebJlppt^ihboSf`qfjp^karkqfi3^obp^sbayyNFAy./25-y

@Ifcb_illalcqebJlppt^ihboPeofkbyKy@liib`q.-XIfcb_illaPe^oapZp`^qqbobalkqebdolrka^olrka%4/+1)3.+.&yyNFAy./246y
QIfcb_illalcqebJlppt^ihboPeofkbyKyRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyNFAy./246yyRy053/1y
QQebJlppt^ihboP^sfloyKyRpbXJllaib$pPqobpp?^iiZqlprjjlkJllaibyyNFAy./25-yyRy053/1y

QMltbofkdqebT^vd^qb*QebJ^hbo$pLsboillhyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./3.0y
>QebBqvjfaf^kyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./215y

KQebBqvjfaf^kyKyEb^aqeolrdeqebt^vd^qb^qqebplrqebokbkalcqebwlkb%1-+1)50+.&yyNFAy./215y
QQebBqvjfaf^kyKyQebBqvjfaf^k%14+2)6+/&yyNFAy./215yyWyRk$Dlol@o^qboy
>Qeb>`qfs^qflkOrkbyKyQebBqvjfaf^k%14+2)6+/&yyNFAy./214yyWyRk$Dlol@o^qboy
@Qeb>`qfs^qflkOrkbyNFAy./214yyWyRk$Dlol@o^qboyyKyHfiiEfde@riqfpqEbobkkfkpfabqebE^iilcObmlpb%15+/)/+5&y
QQeb>`qfs^qflkOrkbyKyQebBqvjfaf^k%14+2)6+/&yyNFAy./214yyWyRk$Dlol@o^qboy
>?^`hQeolrdeqebT^vd^qbyKyQebBqvjfaf^k%14+2)6+/&yyNFAy./464yyWyRk$Dlol@o^qboy
Q?^`hQeolrdeqebT^vd^qbyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./464y
>Ob`i^j^qflkyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./213y
@Ob`i^j^qflkyNFAy./213yyRy054-6yyKyEb^akloqeqlqeb_lqqljlcqeb>s^i^k`eb^karpbqebXLjbd^OrkbZ+Cfopqhfii?vqefrpqebCibpe*Pe^mbo%4/+4)1-+6&)pm^j`ib^sbtfqe^ii0jl_pfkcolkq^kaeb^ifckbbaba+QebkRodobqelcqebQelrp^kaQlj_p%4-+2)04+0&)j^hbprobvlrjlsb^t^vtebkebpq^oqpqlrpbefp>lB^kaq^hbqebqfjbqleb^iarofkdfq+I^pqiv)E^fip`lok%4-+0)01+.&pqo^fdeqclot^oacfdeqgrpqp^sbvlro>lBclotebkebprjjlkp^dolrmlcrkab^ay
QOb`i^j^qflkyKy>s^q^olcCobv^%31+3)15+3&yyNFAy./213y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
