
DugisGuideViewer:RegisterGuide("The Storm Peaks (78-80)", "Icecrown (78-80)", "Horde", "L", function()
return [[
AAA

>IruroflrpDbq^t^vyNFAy./520yyKyOfkArl`q^kb%0.+4)2-&yyWyA^i^o^ky

QIruroflrpDbq^t^vyNFAy./520yyKyGbboPm^ohpl`hbq%1.)53+1&y
>@ib^kRmyKyGbboPm^ohpl`hbq%1.)53+1&yyNFAy./5.5y
>Ob`i^fjbaO^qflkpyKyOf`hbq%1-+6)52+1&yyNFAy./5/4y
>BumobppflklcDo^qfqrabyKyOf`hbq%1-+6)52+1&yyNFAy./503y
>QebvQllhLroJbkyKyDobq`ebkCfwwibpm^oh%1.+.)53+.&yyNFAy./510y
>BnrfmjbkqOb`lsbovyKyDobq`ebkCfwwibpm^oh%1.+.)53+.&yyNFAy./511y

@@ib^kRmyNFAy./5.5yyKyDbq.-mfb`bplcX@e^oobaTob`h^dbZ^olrka%06)53&y
@BumobppflklcDo^qfqrabyNFAy./503yyKyHfiiDk^oiefab%0-+2)52+4&y
@Ob`i^fjbaO^qflkpyNFAy./5/4yyKyVlr`^khfiidkliipcloqebXAofbaDkliiO^qflkpZ)_rqfq$pc^pqboqlmf`hqebjrmcoljqeb`o^qbpfkqeb`^jmp^olrka%01)51&y
@QebvQllhLroJbkyNFAy./510yyKyObp`rb2Dl_ifkMofplkbop)`^dbp`^k_bclrka^olrkaqebPfcobia^oSfii^db^q%1.)4-&+Hbvpqlqeb`^dbpaolmlccqebPfcobia^oPqlojJ^fabkpy
@BnrfmjbkqOb`lsbovyKyDbq5mfb`bplcXH0BnrfmjbkqZp`^qqbobalkqebdolrkafk_lubpqeolrdelrqqebsfii^db%1-)4/&yyNFAy./511y

QOb`i^fjbaO^qflkpyNFAy./5/4yyKyOf`hbq%1-+6)52+1&y
QBumobppflklcDo^qfqrabyKyOf`hbq%1-+6)52+1&yyNFAy./503y
>>jmibFkpmfo^qflkyKyOf`hbq%1-+6)52+1&yyNFAy./5/5y
Q@ib^kRmyKyGbboPm^ohpl`hbq%1.)53+1&yyNFAy./5.5y
>Grpq>olrkaqeb@lokboyKyGbboPm^ohpl`hbq%1.)53+1&yyNFAy./5.6y
QQebvQllhLroJbkyKyDobq`ebkCfwwibpm^oh%1.+.)53+.&yyNFAy./510y
>Ib^sbKlDl_ifk?befkayKyDobq`ebkCfwwibpm^oh%1.+.)53+.&yyNFAy./513y
QBnrfmjbkqOb`lsbovyKyDobq`ebkCfwwibpm^oh%1.+.)53+.&yyNFAy./511y

@Grpq>olrkaqeb@lokboyNFAy./5.6yyKyDbqXPm^ohpl`hbq$pQllipZ^q%02+.)54+4&+Cfkaqeb`ib^om^qetebobqebob^obkljfkbp)fqdlbp^olrkapljbqobbpcfopq^kaqebkfkqlqebjfkbcfbiay
QGrpq>olrkaqeb@lokboyNFAy./5.6yyKyGbboPm^ohpl`hbq%1.)53+1&y
>PifdeqivRkpq^_ibyKyGbboPm^ohpl`hbq%1.)53+1&yyNFAy./5/3y
QPifdeqivRkpq^_ibyKyOf`hbq%1-+6)52+1&yyNFAy./5/3y
>>Abif`^qbQlr`eyKyOf`hbq%1-+6)52+1&yyNFAy./5/-y
@>Abif`^qbQlr`eyNFAy./5/-yyRy1-343yyKyD^oj$p?^kbpq^oqp^q%1/)5.&^kadlbpb^pq+MrqaltkqlkplcXFjmolsbaI^kaJfkbpZ`ilpbqldbqebo)_b`^rpbfqq^hbp/qlhfii^kvlcqebfks^abopy

>JlsfkdFkyNFAy./5/6yyKyQlobOrj_ibtobk`e%1.+4)5-+.&y
>LobObmlppbppflkyKyQlobOrj_ibtobk`e%1.+4)5-+.&yyNFAy./50-y
@>jmibFkpmfo^qflkyNFAy./5/5yyRy1-353yyKyQ^hb^XR+A+B+A+Zclrka^q%1.+3)5-+.&^kanrf`hivcfka^j^jjlqeqlil_fq^qy

@LobObmlppbppflkyNFAy./50-yyKyHfiiPklt_ifkaAfddbopqldbq2p^jmibplcXFjmrobP^olkfqbLobZ+Qeb`^sbbkqo^k`bfp^q%1-)45&y
>LkivM^oqivClodlqqbkyNFAy./50.yyKyFkgrobaDl_ifkJfkbo%1/)41&+Altkfkpfab@ovpq^itb_@^sbok)bkqo^k`b^q%1-+0)45&y
@JlsfkdFkyKyHfii./@ovpq^itb_Pmfabop+Qeb`^sbbkqo^k`bfp^q%1-)45&yyNFAy./5/6y
@LkivM^oqivClodlqqbkyNFAy./50.yyKyDbq^kXF`bqfmSbkljP^`ZcoljF`bqfm@o^tibopfkqeb_^`hlcqeb`^sb^olrka%14)4.&y

QLkivM^oqivClodlqqbkyNFAy./50.yyKyFkgrobaDl_ifkJfkbo%1/)41&+Altkfkpfab@ovpq^itb_@^sboky
>?fqqboAbm^oqrobyKyFkgrobaDl_ifkJfkbo%1/)41&yyNFAy./50/y
@?fqqboAbm^oqrobyKyBp`loqqebFkgrobaDl_ifkJfkbo%1/)41&lrqlc@ovpq^itb_@^sbokyyNFAy./50/y

Q?fqqboAbm^oqrobyKyOf`hbq%1-+6)52+1&yyNFAy./50/y
QJlsfkdFkyNFAy./5/6yyKyQlobOrj_ibtobk`e%1.+4)5-+.&y
QLobObmlppbppflkyKyQlobOrj_ibtobk`e%1.+4)5-+.&yyNFAy./50-y
Q>Abif`^qbQlr`eyNFAy./5/-yyKyOf`hbq%1-+6)52+1&y

>Lmbkfkdqeb?^`halloyNFAy./5/.yyKyOf`hbq%1-+6)52+1&y
@Lmbkfkdqeb?^`halloyNFAy./5/.yyRy1-40.yyKyCfkaqebXQo^kpmloqboMltbo@biiZ^q%12+.5/+0&)qebkrpbfq^qqebqbibmloqbom^a^q%2-+4)5.+6&y
QLmbkfkdqeb?^`halloyNFAy./5/.yyKyOf`hbq%1-+6)52+1&+Vlrpelriae^sbdlqqbk^cobbqbibmloqqlH0y
>HkltKlCb^oyKyOf`hbq%1-+6)52+1&yyNFAy./5//y
>>Ci^tibppMi^kyNFAy./5/0yyKyDfkl%2-+2)5.+4&+QbibmloqqlD^oj$pOfpby
@>Ci^tibppMi^kyNFAy./5/0yyRy1.10.yyKyMi^kqqebXE^oam^`hbaBumilpfsb?rkaibZkb^oqeb^iq^o^qqebqlmlcqeb`^sb%2-)44&+QebkhfiiQloj^oColpqdrqy
@HkltKlCb^oyNFAy./5//yyKyHfii3D^ojT^q`ebop^ka5Pklt_ifkaAbslqbbplkvlrot^vlrqlcqeb`^sb%2-)45&y
Q>Ci^tibppMi^kyNFAy./5/0yyKyDfkl%2-+2)5.+4&y
>AbjlifqflkfpqBuqo^loafk^fobyKyDfkl%2-+2)5.+4&yyNFAy./5/1y
QHkltKlCb^oyNFAy./5//yyKyOf`hbq%1-+6)52+1&y
QAbjlifqflkfpqBuqo^loafk^fobyKyOf`hbq%1-+6)52+1&yyNFAy./5/1y

QIb^sbKlDl_ifk?befkayNFAy./513yyKyIlh$ifo^qeb@olkb%1/+5)35+6&fkpfabqebCloilokJfkby
>Qeb@olkb$p?^od^fkyKyIlh$ifo^qeb@olkb%1/+5)35+6&yyNFAy./51.y
@Qeb@olkb$p?^od^fkyNFAy./51.yyKyDbqqebXOrkbplcqebVohsfkkZcoljLsbopbboPvo^telfprmqebo^jmqebafob`qflkIlh$ifo^fpc^`fkd)^kaqlqebofdeq%11+-)36+5&y
QQeb@olkb$p?^od^fkyKyIlh$ifo^qeb@olkb%1/+5)35+6&yyNFAy./51.y
>Jfiaobaqeb@orbiyKyIlh$ifo^qeb@olkb%1/+5)35+6&yyNFAy./6-2y
QJfiaobaqeb@orbiyKyJfiaobaqeb@orbi%11+2)35+6&yyNFAy./6-2y
>Afp`fmifkbyKyJfiaobaqeb@orbi%11+2)35+6&yyNFAy./6-3y
@Afp`fmifkbyNFAy./6-3yyRy1/504yyKyRpbqebXAfp`fmifkfkdOlaZlk3Bue^rpqbaSovhrifkqebqrkkbip^olrka%12)4-&y
QAfp`fmifkbyKyJfiaobaqeb@orbi%11+2)35+6&yyNFAy./6-3y
>Bu^jmibpql_bJ^abyKyJfiaobaqeb@orbi%11+2)35+6&yyNFAy./6-4y
@Bu^jmibpql_bJ^abyNFAy./6-4yyKyHfiiD^oe^ifkqebollj_befkaJfiaoba%12+2)36&y
QBu^jmibpql_bJ^abyKyJfiaobaqeb@orbi%11+2)35+6&yyNFAy./6-4y
>>@boq^fkMofplkboyKyJfiaobaqeb@orbi%11+2)35+6&yyNFAy./6-5y
Q>@boq^fkMofplkboyKyIlh$ifo^qeb@olkb%1/+5)35+6&yyNFAy./6-5y
>>@e^kdblcP`bkbovyKyIlh$ifo^qeb@olkb%1/+5)35+6&yyNFAy./6/.y

Q>@e^kdblcP`bkbovyNFAy./6/.yyKyIlh$ifo^qeb@olkb%14+2)36+.&y
>FpQe^qVlroDl_ifk<yNFAy./636yyKyIlh$ifo^qeb@olkb%14+2)36+.&y
@FpQe^qVlroDl_ifk<yNFAy./636yyKy@e^iibkdb>dkbqq^Qvopalqq^o%14+2)36+.&^kahfiieboy
QFpQe^qVlroDl_ifk<yNFAy./636yyKyIlh$ifo^qeb@olkb%14+2)36+.&y
>QebEviapjbbqyNFAy./64-yyKyIlh$ifo^qeb@olkb%14+2)36+.&y
@QebEviapjbbqyNFAy./64-yyKyGrpqifpqbkqlIlh$ifo^qeb@olkb%14+2)36+.&y
QQebEviapjbbqyNFAy./64-yyKyIlh$ifo^qeb@olkb%14+2)36+.&y
>Q^hfkdlk>ii@e^iibkdbopyKyIlh$ifo^qeb@olkb%14+2)36+.&yyNFAy./64.y
@Q^hfkdlk>ii@e^iibkdbopyNFAy./64.yyKyHfii3Sf`qloflrp@e^iibkdbop^olrka%2.)33&y
QQ^hfkdlk>ii@e^iibkdbopyKyIlh$ifo^qeb@olkb%14+2)36+.&yyNFAy./64.y
>Vlr$iiKbba^?b^oyKyIlh$ifo^qeb@olkb%14+2)36+.&yyNFAy./64/y

>>_boo^qflkpyNFAy./6/2yyKyQevo^Hsfkkpe^i%15+2)4/+.&y
>LccTfqeQebfo?i^`hTfkdpyNFAy./61/yyKyFs^qebSbkdbcri%15+1)4/+.&y
>Vria^$pCliivyNFAy./635yyKyFs^qebSbkdbcri%15+1)4/+.&y

QVlr$iiKbba^?b^oyNFAy./64/yyKy?ofg^k^%20+/)32+5&y
>Dlfkd?b^o_^`hyNFAy./52.yyKy?ofg^k^%20+/)32+5&y
@Dlfkd?b^o_^`hyNFAy./52.yyKyJlrkqF`bc^kd%20+/)32+4&^kapellq4Colpqtlodp^ka.2ColpqDf^kqp+Vlre^sbkl`lkqolilsboqeb_b^olqeboqe^kpmbbafkdfqrmy
QDlfkd?b^o_^`hyNFAy./52.yyKy?ofg^k^%20+/)32+5&y
>@liaEb^oqbayNFAy./523yyKy?ofg^k^%20+/)32+5&y
@@liaEb^oqbayNFAy./523yyKyCivqlArkKfccbibj^q%31)26&)cfka^Molql*Ao^hbqlofab^kaciv^olrkaillhfkdclo?orkkefia^oMofplkbopbk`^pbafkf`b+W^mqebjlk`btfqeqebcolpq_liqql_ob^hqebjcobb+Tebkvlre^sb0mofplkbop)civ_^`hql?orkkefia^oSfii^db+Obmb^qqefp0qfjbpy
Q@liaEb^oqbayNFAy./523yyKy?ofg^k^%20+/)32+5&y
>AbbjbaTloqevyNFAy.0-30yyKy?ofg^k^%20+/)32+5&y

QAbbjbaTloqevyNFAy.0-30yyKy>pqofa?glokofqq^o%16+5)4.+5&y
>J^hfkd^E^okbppyNFAy./6--yyKy>pqofa?glokofqq^o%16+5)4.+5&y
@J^hfkd^E^okbppyNFAy./6--yyKyHfiiF`bj^kbVbqfp^olrka%15+0)41+6&qldbq0XF`bj^kbVbqfEfabpZy
QJ^hfkd^E^okbppyNFAy./6--yyKy>pqofa?glokofqq^o%16+5)4.+5&y
>QebI^pqlcEboHfkayNFAy./650yyKy>pqofa?glokofqq^o%16+5)4.+5&y
>QebPifqebofkdA^ohkbppyNFAy./656yyKy>pqofa?glokofqq^o%16+5)4.+5&y
@QebPifqebofkdA^ohkbppyNFAy./656yyKyHfii5O^sbklrpGlojrkd^ofkqebEf_bok^i@^sbok+Qebbkqo^k`bfp^q%23+-)31+0&y
@QebI^pqlcEboHfkayNFAy./650yyKyObp`rb^kF`bj^tJ^qof^o`efkqebb^pqbokm^oqlcqeb`^sb%21+5)3-+1&y
QQebPifqebofkdA^ohkbppyNFAy./656yyKy>pqofa?glokofqq^o%16+5)4.+5&y
QQebI^pqlcEboHfkayNFAy./650yyKy>pqofa?glokofqq^o%16+5)4.+5&y
>QebT^oj*rmyNFAy./663yyKy>pqofa?glokofqq^o%16+5)4.+5&y
@QebT^oj*rmyNFAy./663yyRy1/15.yyKyRpbqebXObfkplcqebF`bj^tJ^qof^o`eZqlabcb^qHfod^o^^hfkpfab?orkkefia^oSfii^db`e^fkbarm^q%2-+5)34+3&y
QQebT^oj*rmyNFAy./663yyKy>pqofa?glokofqq^o%16+5)4.+5&y
>FkqlqebMfqyNFAy./664yyKy>pqofa?glokofqq^o%16+5)4.+5&y
@FkqlqebMfqyNFAy./664yyRy1/166yyKyRpbqebXObfkplcqebF`bj^tJ^qof^o`eZ^qqebmfqfkqebjfaaiblcqebsfii^db^kaabcb^q3EviapjbbqT^o_b^op%16+3)35+.&y
QFkqlqebMfqyNFAy./664yyKy>pqofa?glokofqq^o%16+5)4.+5&y
>Mobm^obcloDilovyNFAy.0-3.yyKy>pqofa?glokofqq^o%16+5)4.+5&y

QMobm^obcloDilovyNFAy.0-3.yyKyIlh$ifo^qeb@olkb%14+2)36+.&y
>Ilh$ifo^$pM^oqfkdDfcqyNFAy.0-3/yyKyIlh$ifo^qeb@olkb%14+2)36+.&y
QIlh$ifo^$pM^oqfkdDfcqyNFAy.0-3/yyKyDobqq^qeb>o_fqbo%2-+6)32+3&y
>QebAo^hhbkpovayNFAy./553yyKyDobqq^qeb>o_fqbo%2-+6)32+3&y
@QebAo^hhbkpovayNFAy./553yyRy1.-25yyKyRpbqebXEviakfoE^omllkZqlhfii.-EviapjbbqAo^hbofabop^qqebQbjmiblcPqlojp%02)3-&+Tebkvlr$obalkbrpbqebe^omllklklkblcqeb`lirjklok^jbkqpqlbufq+Afpjfppvlrombq_bclobpq^oqfkdqefpnrbpqloqebe^omllktlk$qtlohy
QQebAo^hhbkpovayNFAy./553yyKyQelofj%00+2)25&y
>Pf_ifkdOfs^iovyNFAy.0-31yyKyQelofj%00+2)25&y
@Pf_ifkdOfs^iovyNFAy.0-31yyKyIfpqbkqlQelofj$ppqlov%00+2)25&y
QPf_ifkdOfs^iovyNFAy.0-31yyKyQelofj%00+2)25&y
>JbkafkdCbk`bpyNFAy./6.2yyKyQelofj%00+2)25&y

@Vria^$pCliivyNFAy./635yyKyHfiiVria^qebPqlojpmb^hbo%/1)3.+4&fkpfabqeb_fd_rfiafkdy
>S^ihvoflkJrpq?rokyNFAy./620yyKyE^omllk@o^qb%/1)3.+4&y
@LccTfqeQebfo?i^`hTfkdpyNFAy./61/yyKyHfii./K^p`bkqS^i$ihvo)clrkacivfkd^olrka%/2)3-&y
@>_boo^qflkpyNFAy./6/2yyKyHfiiqebS^ihvoflk>pmfo^kqpcloXSf^iplcColpqLfiZ^olrka%/2)3-&)qebkrpbfqlkqebbddpfkqeb?ifdeqbaMlli%//+6)25+1&+Qovqlefq^crii_^q`e%^_lrq2bddp&tfqeb^`elkbyyRy1.3./y
@S^ihvoflkJrpq?rokyNFAy./620yyKyRpbqebE^omllkDrkp%/4)3-&ql_rok3AovE^vpq^`hpy

QS^ihvoflkJrpq?rokyNFAy./620yyKyFs^qebSbkdbcri%15+1)4/+.&y
QLccTfqeQebfo?i^`hTfkdpyNFAy./61/yyKyFs^qebSbkdbcri%15+1)4/+.&y
QVria^$pCliivyNFAy./635yyKyFs^qebSbkdbcri%15+1)4/+.&y
Q>_boo^qflkpyNFAy./6/2yyKyQevo^Hsfkkpe^i%15+2)4/+.&y

@JbkafkdCbk`bpyNFAy./6.2yyKyCfka^XDo^kfqb?lriaboZlkqebdolrka%42)31&)rpbXQelofj$p@e^ojlcB^oqeZlkPqlojclodbaFolkDf^kqp+Lk`b2df^kqp^obhfiiba+Mf`hrm^klqebo_lriabo^kahfiiCglokyyRy1.2-2y
>QebObcfkbo$pCfobyKyQebfqbjXPi^d@lsbobaJbq^iZpq^oqpnrbpq*aolmmba_vPqlojclodbaFolkDf^kqp^olrka%42)31&yyNFAy./6//yyRy1.223y
@QebObcfkbo$pCfobyNFAy./6//yyKy@liib`q.-XCroflrpPm^ohpZcoljqebPbbqefkdObsbk^kqp^qColpqcfbiaI^hb%4-)26&y
QQebObcfkbo$pCfobyNFAy./6//yyKyCglok$p>ksfi%44+.)3/+5&y
>>Pm^ohlcElmbyNFAy./623yyKyCglok$p>ksfi%44+.)3/+5&y

>Tebk>iiBipbC^fipyKyOf`hbq%1-+6)52+1&yyNFAy.0-3-y
QTebk>iiBipbC^fipyNFAy.0-3-yyKyLirq>ibdrq%04+-)16+3&y

>>k`fbkqObif`pyKyLirq>ibdrq%04+-)16+3&yyNFAy./55/y
>QebJfppfkd?olkwb_b^oayKy?lhq^o?illacrov%04+0)16+4&yyNFAy./562y
>QebJfppfkdQo^`hboyKy?illadr^oaIlod^%03+2)16+.&yyNFAy.0-21y
>Bjbodbk`vJb^probpyKy?illadr^oaIlod^%03+2)16+.&yyNFAy.0---y

@QebJfppfkd?olkwb_b^oayKyCfkaqebX?roi^m*To^mmbaKlqbZ^q%03+.)31+.&fkqebafpqro_bapkltyyNFAy./562y
QJbkafkdCbk`bpyNFAy./6.2yyKyQelofj%00+2)25&y
Q>Pm^ohlcElmbyNFAy./623yyKyQelofj%00+2)25&y
>Clodfkd^k>iif^k`byNFAy./6/1yyKyQelofj%00+2)25&y

QQebJfppfkd?olkwb_b^oayKy?lhq^o?illacrov%04+0)16+4&yyNFAy./562y
>QebKlpbHkltpyKy?lhq^o?illacrov%04+0)16+4&yyNFAy./6-6y

QQebKlpbHkltpyKyHe^iffpf%1-+5)2.+/&yyNFAy./6-6y
>PkfccfkdLrqqebMbombqo^qloyKyHe^iffpf%1-+5)2.+/&yyNFAy./6.-y
@PkfccfkdLrqqebMbombqo^qloyNFAy./6.-yyKyOfabColpq_fqbteltfiiq^hbvlrqlqeb`^sbok%15)3.&)dlfk^kahfiiQo^`hboQerifk^kaillqX?o^kk$p@ljjrkf`^qloZy
QPkfccfkdLrqqebMbombqo^qloyNFAy./6.-yyKy?o^kk?olkwb_b^oa*prjjlktfqeX?o^kk$p@ljjrkf`^qloZyyRy1-64.y
>Pmb^hLo`fpe)J^kyNFAy./6.0yyKy?o^kk?olkwb_b^oa*prjjlktfqeX?o^kk$p@ljjrkf`^qloZyyRy1-64.y

QQebJfppfkdQo^`hboyKyQo^`hboS^i$wfg%15+2)21+0&yyNFAy.0-21y
>@^sbJbaf`fkbyKyQo^`hboS^i$wfg%15+2)21+0&yyNFAy.0-22y

@@^sbJbaf`fkbyKy@liib`qqebjrpeolljpqe^qproolrkaqeb`^sb%13+6)21+6&^kahfiiGlojrkd^opcloqebXQlufkDi^kaZyyNFAy.0-22y
Q@^sbJbaf`fkbyKyQo^`hboS^i$wfg%15+2)21+0&yyNFAy.0-22y
>Qebob$p>it^vpQfjbcloObsbkdbyKyQo^`hboS^i$wfg%15+2)21+0&yyNFAy.0-23y
@Qebob$p>it^vpQfjbcloObsbkdbyKyCfka^kapi^vDfjlo^h^olrka%16+.)13+6&fkpfabqeb`^sbyyNFAy.0-23y
@Bjbodbk`vJb^probpyKyHfiitlodpfkqeb`^sb^q%13+6)21+6&ql`liib`qqebfocroyyNFAy.0---y
QQebob$p>it^vpQfjbcloObsbkdbyKyQo^`hboS^i$wfg%15+2)21+0&yyNFAy.0-23y

QBjbodbk`vJb^probpyKy?illadr^oaIlod^%03+2)16+.&yyNFAy.0---y
QPmb^hLo`fpe)J^kyKyJlqbe^Tfka_lok%04+0)16+4&yyNFAy./6.0y
>Pmb^hfkdtfqeqebTfka$pSlf`byKyJlqbe^Tfka_lok%04+0)16+4&yyNFAy./6.4y
@Pmb^hfkdtfqeqebTfka$pSlf`byKyHfiiPqlojofabop^olrka%0.+5)16+.&yyNFAy./6.4y
QPmb^hfkdtfqeqebTfka$pSlf`byKyJlqbe^Tfka_lok%04+0)16+4&yyNFAy./6.4y
>@^q`efkdrmtfqe?o^kkyKy?lhq^o?illacrov%04+0)16+4&yyNFAy./6/-y
@@^q`efkdrmtfqe?o^kkyKyPrjjlktfqe?o^kk?olkwb_b^oaX?o^kk$p@ljjrkf`^qloZ^kaq^ihqlefjyRy1-64.yyNFAy./6/-y
Q@^q`efkdrmtfqe?o^kkyKy?lhq^o?illacrov%04+0)16+4&yyNFAy./6/-y

>Mfb`bpqlqebMrwwibyNFAy./6/3yyKy?lhq^o?illacrov%04+0)16+4&y
@Mfb`bpqlqebMrwwibyNFAy./6/3yyKyQebIf_o^ovfp^q%05)10&)grpqhfiiqebdkljbpfkqebob^ka`lj_fkbqeb3fksbkqlo$pafphco^djbkqpqe^qaolmqldbqXQebFksbkqlo$pAfphZyyRy1..0-y
QMfb`bpqlqebMrwwibyNFAy./6/3yyKy?o^kk?olkwb_b^oa*prjjlktfqeX?o^kk$p@ljjrkf`^qloZyyRy1-64.y
>A^q^JfkfkdyNFAy./53-yyKy?o^kk?olkwb_b^oa*prjjlktfqeX?o^kk$p@ljjrkf`^qloZyyRy1-64.y
@A^q^JfkfkdyNFAy./53-yyRy1..46yyKyRpbXQebFksbkqlo$pAfphZlkqebA^q^_^khp^olrkaqebif_o^ov%1-)1-&y
QA^q^JfkfkdyNFAy./53-yyKy?o^kk?olkwb_b^oa*prjjlktfqeX?o^kk$p@ljjrkf`^qloZyyRy1-64.y
>QebIf_o^ov@lkplibyNFAy.01.2yyKy?o^kk?olkwb_b^oa*prjjlktfqeX?o^kk$p@ljjrkf`^qloZyyRy1-64.y
QQebIf_o^ov@lkplibyNFAy.01.2yyKyFksbkqlo$pIf_o^ov@lkplib%04+2)13+5&)fkpfabqebif_o^ovy
>Klod^kklk$pPebiiyNFAy./54/yyKyFksbkqlo$pIf_o^ov@lkplib%04+2)13+5&y
@Klod^kklk$pPebiiyNFAy./54/yyRy114-1yyKyRpbqebX@e^odbaAfphZfkqebif_o^ov)qlprjjlk>o`efsfpqJb`e^qlk%04+2)13+3&)qebkhfiiefjqldbqXKlod^kklk$pPebiiZy
QKlod^kklk$pPebiiyNFAy./54/yyKy?o^kk?olkwb_b^oa*prjjlktfqeX?o^kk$p@ljjrkf`^qloZyyRy1-64.y

>QebB^oqebklcRiar^oyNFAy./6/6yyKy?o^kk?olkwb_b^oa*prjjlktfqeX?o^kk$p@ljjrkf`^qloZyyRy1-64.y
>Dlfkd>cqboqeb@lobyNFAy.0/40yyKy?o^kk?olkwb_b^oa*prjjlktfqeX?o^kk$p@ljjrkf`^qloZyyRy1-64.y
@Dlfkd>cqboqeb@lobyNFAy.0/40yyKyDo^_Holek^$pklqb%26+5)2/+3&kbuqql^ifqqibqbkq^kaPlobk$pklqb%26+/)2.+2&ofdeqkbuqqlqeb_lkcfob&y
QDlfkd>cqboqeb@lobyNFAy.0/40yyKy?o^kk?olkwb_b^oa*prjjlktfqeX?o^kk$p@ljjrkf`^qloZyyRy1-64.y
>Qeb@lob$pHbbmboyNFAy.0/41yyKy?o^kk?olkwb_b^oa*prjjlktfqeX?o^kk$p@ljjrkf`^qloZyyRy1-64.y
@Qeb@lob$pHbbmboyNFAy.0/41yyKyCivqeolrdeqebqrkkbiqlcfka^kahfii>qe^k%23+1)25+3&y
QQeb@lob$pHbbmboyNFAy.0/41yyKy?o^kk?olkwb_b^oa*prjjlktfqeX?o^kk$p@ljjrkf`^qloZyyRy1-64.y
>ClodfkdqebHbvpqlkbyNFAy.0/52yyKy?o^kk?olkwb_b^oa*prjjlktfqeX?o^kk$p@ljjrkf`^qloZyyRy1-64.y
@ClodfkdqebHbvpqlkbyNFAy.0/52yyKyCfka?o^kk?olkwb_b^oa^q%12+2)16+2&^kaq^ihqlefjy
QClodfkdqebHbvpqlkbyKy?lhq^o?illacrov%04+0)16+4&yyNFAy.0/52y
>U^o^kq^ro)qebTfqkbppyNFAy.01/3yyKy?lhq^o?illacrov%04+0)16+4&y
Q>k`fbkqObif`pyKyLirq>ibdrq%04+-)16+3&yyNFAy./55/y

>Vlr@^k$qJfppEfjyNFAy./633yyKyHfkdGlhhrj%32+2)3-+/&y
QVlr@^k$qJfppEfjyNFAy./633yyKyKglojbia%42+2)30+3&y
>?^qqifkdqebBibjbkqpyNFAy./634yyKyKglojbia%42+2)30+3&y
@?^qqifkdqebBibjbkqpyNFAy./634yyKyJlrkqPkloof%kbuqqlnrbpqdfsbo&^kat^ihql^pklt_rjm)mf`hfqrm)q^_rkqfivlrdbq^PbbqefkdObsbk^kq+Hfii.-PbbqefkdObsbk^kqp%44)3/&y
Q?^qqifkdqebBibjbkqpyNFAy./634yyKyKglojbia%42+2)30+3&y
QClodfkd^k>iif^k`byNFAy./6/1yyKyKglojbia%30+0)30+/&y
>>Kbt?bdfkkfkdyNFAy.0--6yyKyKglojbia%30+0)30+/&y
>Elq^ka@liayNFAy./65.yyKyCglok$p>ksfi%30+/)3/+6&y
>FkJbjlof^jyNFAy./642yyKyHfkdGlhhrj%32+2)3-+/&y

@Elq^ka@liayNFAy./65.yyKyDbq2XBppbk`blcF`bZcolj?ofqqibObsbk^kqp^qColpqcfbiaI^hb%4.)3.&)qebkrpbqebjlkqebPjliabofkdP`o^mp^qCglok$p>ksfiyyRy1//13y
@FkJbjlof^jyNFAy./642yyKyIllq5XElokCo^djbkqpZqlqebkloqe^qQerkaboc^ii%4/)14&+Qebv^obpj^ii)dobvmfb`bpqe^q`^k_be^oaqlpbby
QFkJbjlof^jyNFAy./642yyKyHfkdGlhhrj%32+2)3-+/&y

>>JlkrjbkqqlqebC^iibkyNFAy./643yyKyHfkdGlhhrj%32+2)3-+/&y
Q>JlkrjbkqqlqebC^iibkyNFAy./643yyKyKglojbia%30+0)30+/&y
QElq^ka@liayNFAy./65.yyKyCglok$p>ksfi%30+/)3/+6&y
KCofbkaivObmrq^qflkObnrfobayKyVlrtfiikbbaqldbqCofbkaivObmrq^qflktfqePlkplcElafo_bclobvlr$ob^_ibql`lkqfkrb)alpljba^fivnrbpqpfkArkKfccbibjtfqeqebPqlojMb^hpA^fivNrbpqDrfabyyNFAy./652y
>Clodfkd^Eb^ayNFAy./652yyKyKglojbia%30+0)30+/&y
>Glojrqq^ofpPllC^q+++yNFAy.0-..yyKyHfkdGlhhrj%32+2)3-+/&y
@Clodfkd^Eb^ayNFAy./652yyKyCfkaAb^aFolkDf^kqp^olrkaqebi^hb%4-)3-&+RpbvlroXAf^jlkaQfmmbaMf`hZlkqebj^ka0Pqlojclodba>j_rpeboptfii^mmb^o^kaaolm^XPqlojclodbaBvbZyyRy1/1/1y
QClodfkd^Eb^ayNFAy./652yyKyKglojbia%30+0)30+/&y
>JlrkqfkdElafo$pEbijyNFAy./654yyKyKglojbia%30+0)30+/&y
@JlrkqfkdElafo$pEbijyNFAy./654yyKyCivqlqebqfmlcqebkloqebokf`bpmfhbfkArkKfccbibj%31+0)26+0&^karpbqebXQ^_ibqplcMolklrk`bjbkqZ+Qebpmfhbfppj^ii^kavlralk$qkbbaqli^kalkfqql`ljmibqbqebnrbpqyyRy1/11/y
QJlrkqfkdElafo$pEbijyNFAy./654yyKyKglojbia%30+0)30+/&y
>MlifpefkdqebEbijyNFAy.0--3yyKyElafo$pEbij%31+2)26+3&y
@Glojrqq^ofpPllC^q+++yNFAy.0-..yyKyBkqboqebEf_bok^i@^sbok%22+6)31+.&^kahfiiGlojrqq^o%21+4)3-+5&+RpbqebXBsbocolpqO^wloZlk^_b^o)qebkrpbqebci^kh^qqeb`o^qbokb^otebobvlrdlqvlro_b^ob^oifboyyRy1/40/y
@MlifpefkdqebEbijyNFAy.0--3yyKyHfiiSfp`lrpLfi^iilsboqeb`^sb%22)3/&)ql`liib`q2rkfqplcXSfp`lrpLfiZy
QGlojrqq^ofpPllC^q+++yNFAy.0-..yyKyHfkdGlhhrj%32+2)3-+/&y
QMlifpefkdqebEbijyNFAy.0--3yyKyElafo$pEbij%31+2)26+3&y

QU^o^kq^ro)qebTfqkbppyNFAy.01/3yyKyU^o^kq^ro%32+4)2.+2&y
>QebTfqkbpp^kaqebEbolyNFAy.0-01yyKyU^o^kq^ro%32+4)2.+2&y
@QebTfqkbpp^kaqebEbolyNFAy.0-01yyKyQo^sbiqlqeb`^jmqlcfkaqebCfopqP`olii%32+5)2-+1&)Pb`lkaP`olii%33+6)2-+.&^kaQefoaP`olii%34+2)2-+3&y
QQebTfqkbpp^kaqebEbolyNFAy.0-01yyKyU^o^kq^ro%32+4)2.+2&y
>JbjlofbplcPqlojellcyNFAy.0-04yyKyU^o^kq^ro%32+4)2.+2&y
@JbjlofbplcPqlojellcyNFAy.0-04yyKyBkqboqeb`^sb^q%3/+1)1.+4&Pmb^htfqe@ebfcq^kPtfcqpmb^o%3.+/)06&y
>AfpqloqflkpfkQfjbyNFAy.0-05yyKy@ebfcq^kPtfcqpmb^o%3.+/)06&y
@AfpqloqflkpfkQfjbyNFAy.0-05yyKyRpbqebXQeb@efbcq^fk$pQlqbjZlkqebofcqpfkpfabqeb`^sbyyRy1/45.y
QJbjlofbplcPqlojellcyNFAy.0-04yyKyU^o^kq^ro%32+4)2.+2&y
QAfpqloqflkpfkQfjbyNFAy.0-05yyKyU^o^kq^ro%32+4)2.+2&y

>TebobQfjbTbkqTolkdyNFAy.0-15yyKyU^o^kq^ro%32+4)2.+2&y
>QebEbol$p>ojpyNFAy.0-16yyKyU^o^kq^ro%32+4)2.+2&y
@TebobQfjbTbkqTolkdyNFAy.0-15yyKyRpbXQebIlobe^jjboZlkqebobif`pclrkafkqeb`^sb^q%33+6)12+.&yyRy1/506y
@QebEbol$p>ojpyNFAy.0-16yyKyHfiiP`flklcPqlojfkqeb`^sb^q%33+6)12+.&qfii_lqefqbjpaolmy
QTebobQfjbTbkqTolkdyNFAy.0-15yyKyU^o^kq^ro%32+4)2.+2&y
QQebEbol$p>ojpyNFAy.0-16yyKyU^o^kq^ro%32+4)2.+2&y
>@e^kdfkdqebTfka$p@lropbyNFAy.0-25yyKyU^o^kq^ro%32+4)2.+2&y
@@e^kdfkdqebTfka$p@lropbyNFAy.0-25yyKyRpbXQebIlobe^jjboZ^qqebQbjmiblcIfcb^q%31+.)12+6&^karpbPqlojella$p^_fifqfbpql_b^qaltkQebKloqeTfkayyRy1/6.5y
Q@e^kdfkdqebTfka$p@lropbyNFAy.0-25yyKyU^o^kq^ro%32+4)2.+2&y

Q>Kbt?bdfkkfkdyNFAy.0--6yyKyQelofj%00+2)25&y
>Sbo^krpyNFAy.0-2-yyKyQelofj%00+2)25&y
@Sbo^krpyNFAy.0-2-yyKyIllq2XPj^iiMolql*Ao^hbBddpZcoljqebkbpqpkloqetbpq%12+1)34&)%10+4)34+1&^kaplrqeb^pq%2/+1)40+/&)%20+3)41+4&lc?orkkefia^oSfii^dby
QSbo^krpyNFAy.0-2-yyKyQelofj%00+2)25&y
>Qboofqlof^iQobpm^ppyNFAy.0-2.yyKyQelofj%00+2)25&y
@Qboofqlof^iQobpm^ppyNFAy.0-2.yyRy1/464yyKyMi^`bqebXPqlibkMolql*Ao^dlkBddpZlkqlmlcqeb?ollajlqebo$pKbpq%05+4)32+3&y
QQboofqlof^iQobpm^ppyNFAy.0-2.yyKyQelofj%00+2)25&y
>Holijfo)E^jjbolcPqlojpyNFAy.0-.-yyKyQelofj%00+2)25&y

@Holijfo)E^jjbolcPqlojpyNFAy.0-.-yyKyQ^ihqlHfkdGlhhrjfkArkKfccbibj%32+2)3-+/&y
QHolijfo)E^jjbolcPqlojpyNFAy.0-.-yyKyQelofj%4.+1)15+5&y
>QebQboo^`blcqebJ^hbopyNFAy.0-24yyKyQelofj%4.+1)15+5&y

QQebQboo^`blcqebJ^hbopyNFAy.0-24yyKyQelofj%23+/)2.+1&y
>QebB^oqebkL^qeyNFAy.0--2yyKyQelofj%23+/)2.+1&y
>Ilhbk$pI^`hbvpyNFAy.0-02yyKyQelofj%23+/)2.+1&y
@Ilhbk$pI^`hbvpyNFAy.0-02yyKyRpbqebXEloklcqebMb^hpZqlebimvlrhfii)Bfpbkc^rpqkloqefkpfabqebE^iilcqebPe^mbo%22+2)10+2&)E^ibckfoqebTfka_lokfpm^oqt^valtkqebpq^fopqlqebtbpq%15)12&)^kaArolkkqebOrkbtolrdeqfp^qqeb_lqqljlcqebpq^fop%11)04&yyRy1/51-y
@QebB^oqebkL^qeyNFAy.0--2yyKyRpbqebXEloklcqebMb^hpZ^olrka%20)2.&qlprjjlkqebB^oqebkqlabcb^q/-FolkAt^osbp^ka4FolkPbkqfkbipyyRy1/51-y
QQebB^oqebkL^qeyNFAy.0--2yyKyQelofj%23+/)2.+1&y
QIlhbk$pI^`hbvpyNFAy.0-02yyKyQelofj%23+/)2.+1&y
>QebOb`hlkfkdyNFAy.0-14yyKyQelofj%23+/)2.+1&y

@QebOb`hlkfkdyNFAy.0-14yyKyJbbqQelofjkb^oqebQbjmiblcTfpalj%03)0/&y
QQebOb`hlkfkdyNFAy.0-14yyKyHfkdGlhhrj%32+2)3-+/&y

QQebB^oqebklcRiar^oyNFAy./6/6yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
>O^obB^oqeyNFAy./60-yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
@O^obB^oqeyNFAy./60-yyKyRpbqebXB^oqebkJfkfkdMf`hZqljfkb4`irjmplcXBk`e^kqbaB^oqeZclrka^ii^ilkdqeb`ifccc^`bqlqebkloqetbpq%/4)00&+DbqXColpqtb^sb@ilqeZcoljqebPqlojclodbaO^fabop^olrka%/5)05&yyRy1.3.2y
QO^obB^oqeyNFAy./60-yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
>Cfdeqfkd?^`hyNFAy./60.yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
>ObifbccloqebC^iibkyNFAy./604yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y

@ObifbccloqebC^iibkyNFAy./604yyRy1.655yyKyRpbqebXQbiirof`Mlriqf`bZqleb^i5C^iibkB^oqebkAbcbkabop^olrka%/4)04&y
@Cfdeqfkd?^`hyNFAy./60.yyKyHfiibfqeboPqlojclodbaO^faboploPqlojclodbaOb^sbop^olrka%/4)03&y

QCfdeqfkd?^`hyNFAy./60.yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
QObifbccloqebC^iibkyNFAy./604yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
>Pi^sbplcqebPqlojclodbayNFAy./624yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
>QebA^ohLobyNFAy./631yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y

@Pi^sbplcqebPqlojclodbayNFAy./624yyKyCobb@^mqfsbJb`e^dkljbp^kahfii0PqlojclodbaQ^phj^pqbop+Qebjfkbbkqo^k`bfp^q%/4+04)16+42&y
@QebA^ohLobyNFAy./631yyKyDbq2XA^ohLobP^jmibpZcoljqeb`^oqpfkqebjfkb%/5)2-&y

QPi^sbplcqebPqlojclodbayNFAy./624yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
QQebA^ohLobyNFAy./631yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
>QebDfcqplcIlhbkyNFAy./632yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
>C^`fkdqebPqlojyNFAy./645yyKy?orloFolk_^kb%0.+0)05+.&y
>>ojlolcA^ohkbppyNFAy./646yyKyQebfqbjXA^oh>ojloMi^qbZpq^oqpnrbpq*aolmmba_vPqlojclodbaT^oDlibjp^olrka%0.)10&yyRy1//-0y

@QebDfcqplcIlhbkyNFAy./632yyKyQebdfcqp^obil`^qbafkpfabqeb0_rfiafkdpqlqebtbpq+Ilhbk$pCrov%/1)1/&)Ilhbk$pMltbo%/3+/)14+4&^kaIlhbk$pC^slo%/1+3)15+2&y
@>ojlolcA^ohkbppyNFAy./646yyKyDbq1XA^oh>ojloP^jmibpZaolmmba_vPqlojclodbaT^oDlibjp^olrka%0.)10&y
@C^`fkdqebPqlojyNFAy./645yyKyHfiiPqlojclodba@e^jmflkp)PqlojclodbaJ^df)loPqlojclodbaT^oDlibjp^olrka%/3)14&y

QC^`fkdqebPqlojyNFAy./645yyKy?orloFolk_^kb%0.+0)05+.&y
Q>ojlolcA^ohkbppyNFAy./646yyKy?orloFolk_^kb%0.+0)05+.&y
>Qeb>ojlo$pPb`obqpyNFAy./65-yyKy?orloFolk_^kb%0.+0)05+.&y
QQebDfcqplcIlhbkyNFAy./632yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
@Qeb>ojlo$pPb`obqpyNFAy./65-yyKyBkqo^k`bqlJfjfo$pTlohpelmfp^q%00)06&+Pmb^hql>qqbka^kqQl`htelfpfkpfabqlt^oapqeb_^`hlkqebofdeqy
QQeb>ojlo$pPb`obqpyNFAy./65-yyKy?orloFolk_^kb%0.+0)05+.&y
>S^iaro^kqebPqloj_lokyNFAy./651yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y

@S^iaro^kqebPqloj_lokyNFAy./651yyKyDbq`ilpbqlS^iaro^kqebPqloj_lokfkpfabqeb_rfiafkd^q%/1+1)2/+.&^karpbX?lriabo`o^d$pT^oElokZyyRy1/1.6y

QS^iaro^kqebPqloj_lokyNFAy./651yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
>AbpqolvqebClodbpyNFAy./655yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
>EfqQebjTebobfqEroqpyNFAy./66.yyKy?orloFolk_^kb%0.+0)05+.&y

@AbpqolvqebClodbpyNFAy./655yyRy1/11.yyKyRpbX?lriabo`o^d$p?lj_Zlkqeb0clodbp+KloqeIfdeqkfkdClodb%/6)12+5&)@bkqo^iIfdeqkfkdClodb%/6+2)12+6&^kaPlrqeIfdeqkfkdClodb%0-+0)13+.&y
@EfqQebjTebobfqEroqpyNFAy./66.yyKyHfii.-Pqlojclodba>oqfcf`bop^olrka%0-)12&y

QEfqQebjTebobfqEroqpyNFAy./66.yyKy?orloFolk_^kb%0.+0)05+.&y
QAbpqolvqebClodbpyNFAy./655yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
>>@lilpp^iQeob^qyNFAy./660yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
@>@lilpp^iQeob^qyNFAy./660yyKyObqofbsbqebX@lilpprp>qq^`hPmb`pZ^q%/5+6)11+.&^kaX@lilpprpAbcbkpbPmb`pZ^q%/6+6)12+5&y
Q>@lilpp^iQeob^qyNFAy./660yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
>QebEb^oqlcqebPqlojyNFAy./665yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y

@QebEb^oqlcqebPqlojyNFAy./665yyKyDlqlqeb`^sb^q%0/+1)30+3&^kacfkaqebEb^oqlcPqloj%03+.)3-+6&y
QQebEb^oqlcqebPqlojyNFAy./665yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
>QebFolk@lilpprpyNFAy.0--4yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y
@QebFolk@lilpprpyNFAy.0--4yyKyRpb^Q^jbaGlojrkd^o%/4)03&qlhfiiqebFolk@lilpprp+Hbbmqeb^`fapmfqpq^`hprm^kaj^hbprobvlrdlrkabodolrka^kaork^t^vtebkebdolrkapi^jp^kafqfp^mobqqvb^pvcfdeqy
QQebFolk@lilpprpyNFAy.0--4yyKy?lriabo`o^dqebOl`hpe^mbo%0.+1)05+.&y

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby

]]
end)
