--Localization.enUS.lua

DugisLocals = {
	PART_TEXT = "Part",
	PART_MATCH = "%s%(Part (%d+)%)",
}

setmetatable(DugisLocals, {__index=function(t,k) rawset(t, k, k); return k; end})

	--[[
	["Accept Quest"] = "",
	["Accept Daily"] = "",
	["Ach/Prof"] = "",
	["Achievements and Professions Guides"] = "",	
	["Automatic Waypoints"] = "", 
	["Boat to"] = "",
	["Buy Item"] = "",
	["Complete"] = "",
	["Complete Quest"] = "",
	["Configuration Settings for DugisGuideViewer"] = "",
	["Current Guide"] = "",
	["Dailies/Events"] = "",
	["Dailies and Events Guides"] = "",	
	["Desecrate this Fire!"] = "",
	["Display Quest Level"] = "",
	["Dungeons"] = "",	
	["Dungeon Guides"] = "",	
	["Dungeon Maps"] = "",
	["Fly to"] = "",
	["Get Flight Point"] = "",
	["Honor the Flame"] = "",
	["Item Button"] = "",
	["Kill NPC"] = "",
	["Leveling"] = "",
	["Leveling Guides"] = "",	
	["Lock Large Frame"] = "",
	["Lock Small Frame"] = "",
	["Lock small frame into place"] = "",
	["Lock large frame into place"] = "",
	["Manual Mode"] = "",
	["Maps"] = "",
	["Map each destination with TomTom"] = "",
	["No Guide Loaded"] = "",
	["No Guide Loaded. Right Click Here To Select One"] = "",
	["Note"] = "",
	["Optional"] = "",
	["Quest accepted: (.*)"] = "",	
	["Reload"] = "",	
	["Reset"] = "",
	["Reset Frames Position"] = "",
	["Select a Dungeon Map"] = "",	
	["Select a leveling guide closest to your current level"] = "",
	["Set Hearthstone"] = "",
	["Settings"] = "",
	["Settings for Dugis Guide Viewer"] = "",
	["Shows a small window to click when an item is needed for a quest"] = "",
	["Show Small Frame"] = "",
	["Show the quest level on the large and small frames"] = "",
	["This mode lets the user individually complete or skip quests. When unchecked, the guide will skip all quests in the quest sequence"] = 
	"",
	["Too High Level"] = "",
	["Travel to"] = "",
	["Turn in Daily"] = "",
	["Turn in Quest"] = "",
	["Use Dungeon Finder"] = "",
	["Use Hearthstone"] = "",	
	["Use Item"] = "",

	
	--]]