if ( GetLocale() == "frFR" ) then

DugisLocals = {
	PART_TEXT = "Partie",
	["|cffff4500This quest is not listed in your current guide"] = "|cffff4500Cette qu\195\170te n'est pas list\195\169e dans votre guide actuel",
	["(.*) is now your home."] = "(.*) est maintenant votre foyer.",
	["^You .*Hitem:(%d+).*(%[.+%])"] = "^Vous .*Hitem:(%d+).*(%[.+%])",
	

	["Accept quest"] = "Acceptez la qu\195\170te",
	["Accept Daily"] = "Acceptez tous les jours",
--	["Ach/Prof"] = "?",
--	["Achievements and Professions Guides"] = "?",	
	["Automatic Waypoints"] = "Destinations Automatiques",
	["Boat to"] = "Prenez le bateau pour",
	["Buy Item"] = "Achetz l'objet",
	["Complete"] = "Complet",
	["Complete quest"] = "Terminez la qu\195\170te",
	["Configuration Settings for DugisGuideViewer"] = "Paramètres de Configuration",
	["Current Guide"] = "Guide Actif",
	["Dailies/Events"] = "Journ/Évèn",
	["Dailies and Events Guides"] = "Guides des journalières et évènements",	
	["Desecrate this Fire!"] = "Désacralisez ce feu !",
	["Display Quest Level"] = "Afficher Le Niveau Des Quêtes",
	["Dungeons"] = "Dongeons",
	["Dungeon Guides"] = "Guides des Donjons",
--	["Dungeon Maps"] = "?",
	["Fly to"] = "Envolez-vous \195\160",
	["Get flight point"] = "Apprenez une destination",	
	["Honor the Flame"] = "Honorer la flamme",
	["Item Button"] = "Bouton d'Objet",
	["Kill NPC"] = "Tuez la cr\195\169ature",
	["Leveling"] = "Turbo-Leveling",
	["Leveling Guides"] = "Guide de montée en niveau",
	["Lock Large Frame"] = "Figer La Grande Fenêtre",
	["Lock Small Frame"] = "Figer La Petite Fenêtre",
	["Lock small frame into place"] = "Fige la petite fenêtre",
	["Lock large frame into place"] = "Fige la grande fenêtre",
	["Manual Mode"] = "Mode Manuel",
--	["Maps"] = "?",
	["Map each destination with TomTom"] = "Place automatiquement une destination dans Tomtom",
	["No Guide Loaded"] = "Aucun guide charg\195\169",
	["No Guide Loaded. Right Click Here To Select One"] = "Aucun guide chargé. Cliquez ici pour en choisir un",
	["Note"] = "Note",
	["Optional"] = "Facultatif",
	["Quest accepted: (.*)"] = "Qu\195\170te accept\195\169e..:.(.*)",
	["Reload"] = "Recharge",	
	["Reset"] = "Remise",
	["Reset Frames Position"] = "Réinitialiser La Position Des Fenêtres",
	["Select a Dungeon Map"] = "Sélectionnez la carte d'un dongeon",
	["Select a leveling guide closest to your current level"] = "Sélectionnez un guide correspondant à votre niveau actuel",
	["Set Hearthstone"] = "Fixez votre foyer",
	["Settings"] = "Réglages",
	["Settings for Dugis Guide Viewer"] = "",
	["Shows a small window to click when an item is needed for a quest"] = "Montre une petite icône sur laquelle cliquer quand un objet doit être utilisé",
	["Show Small Frame"] = "Montrer La Petite Fenêtre",
	["Show the quest level on the large and small frames"] = "Montre le niveau des quêtes dans la petite et la grande fenêtre",
	["This mode lets the user individually complete or skip quests. When unchecked, the guide will skip all quests in the quest sequence"] = "Ce mode permet à l'utilisateur de finir ou passer les quêtes. Quand la case n'est pas cochée, le guide passera toutes les quêtes de la séquence",
	["Too High Level"] = "",
	["Travel to"] = "",
	["Turn in Daily"] = "",
	["Turn in quest"] = "Validez la qu\195\170te",
--	["Use Dungeon Finder"] = "",
	["Use Hearthstone"] = "Utilisez votre pierre de foyer",	
	["Use Item"] = "Utilisez l'objet",



	}
setmetatable(DugisLocals, {__index=function(t,k) rawset(t, k, k); return k; end})	
end