DugisGuideViewer:RegisterGuide("Elwynn Forest (1-12 Human)", "Darkshore (12-17)", "Alliance", "L", function()
return [[
AAA

>>Qeob^qTfqefkyKyAbmrqvTfiibj%15)10+2&yyNFAy450y
Q>Qeob^qTfqefkyKyJ^ope^iJ`?ofab%15+6)1.+3&yyNFAy450y
>Hl_lia@^jm@ib^krmyKyJ^ope^iJ`?ofab%15+6)1.+3&yyNFAy4y
>B^d^kMbiqphfkkboyKyAbmrqvTfiibj%15)10+2&yyNFAy2/3.y
QB^d^kMbiqphfkkboyKyB^d^kMbiqphfkkbo%15+6)1-+.&yyNFAy2/3.y
>Tlisbp>`olppqeb?loaboyKyB^d^kMbiqphfkkbo%15+6)1-+.&yyNFAy00y

@Hl_lia@^jm@ib^krmyKyHfii5Hl_liaSbojfktef`e`^k_bclrka^olrkaqebjfkbqlqebKloqelcJ^ope^iJ`?ofab^olrka%16)02&yyNFAy4y
@Tlisbp>`olppqeb?loaboyKyHfiiqebVlrkdTlisbp^olrka%14)05&^kaQfj_boTlisbp^olrka%13)02&qebv^obclrkafkqeb^ob^qlqebkloqelcB^d^kMbiqphfkkboyyNFAy00y

QTlisbp>`olppqeb?loaboyKyB^d^kMbiqphfkkbo%15+6)1-+.&yyNFAy00y
QHl_lia@^jm@ib^krmyKyJ^ope^iJ`?ofab%15+6)1.+3&yyNFAy4y

>@lkpb`o^qbaIbqqboy@yM^i^afkyyKyJ^ope^iJ`?ofab%15+6)1.+3&yyNFAy0.-.y
>Divmef`Ibqqboy@yJ^dbyyKyJ^ope^iJ`?ofab%15+6)1.+3&yyNFAy0.-1y
>Bk`ovmqbaIbqqboy@yOldrbyyKyJ^ope^iJ`?ofab%15+6)1.+3&yyNFAy0.-/y
>PfjmibIbqqboy@yT^oofloyyKyJ^ope^iJ`?ofab%15+6)1.+3&yyNFAy0.--y
>E^iiltbaIbqqboy@yMofbpqyyKyJ^ope^iJ`?ofab%15+6)1.+3&yyNFAy0.-0y
>Q^fkqbaIbqqboy@yT^oil`hyyKyJ^ope^iJ`?ofab%15+6)1.+3&yyNFAy0.-2y

>Fksbpqfd^qbB`elOfadbyKyJ^ope^iJ`?ofab%15+6)1.+3&yyNFAy.2y
>?olqeboellalcQefbsbpyKyAbmrqvTfiibj%15)10+2&yyNFAy.5y

Q@lkpb`o^qbaIbqqboy@yM^i^afkyyKy?olqeboP^jjrbi%2-+1)1/+.&yyNFAy0.-.y
QDivmef`Ibqqboy@yJ^dbyyKyHebiabk?objbk%16+3)06+2&yyNFAy0.-1y
QBk`ovmqbaIbqqboy@yOldrbyyKyGlofhHboofa^k%2-+1)06+6&yyNFAy0.-/y
QPfjmibIbqqboy@yT^oofloyyKyIi^kb?bpebob%2-+/)1/+/&yyNFAy0.--y
QE^iiltbaIbqqboy@yMofbpqyyKyMofbpqbpp>kbqq^%16+5)06+3&yyNFAy0.-0y
QQ^fkqbaIbqqboy@yT^oil`hyyKyAorpfii^I^P^iib%16+6)1/+4&yyNFAy0.-2y

@Fksbpqfd^qbB`elOfadbyKyHfii5Hl_liaTlohboptef`e`^k_bclrkafkqebjfkbqlqebKloqelcJ^ope^iJ`?ofab^olrka%2-)01&yyNFAy.2y
@?olqeboellalcQefbsbpyKyHfiiqebAbcf^pQerdptef`eproolrkaqeb^ob^qlqebPlrqeb^pq^`olppqebofsbo^olrka%21)12&ql`liib`q5XOba?roi^m?^ka^k^pZyyNFAy.5y

Q?olqeboellalcQefbsbpyKyAbmrqvTfiibj%15)10+2&yyNFAy.5y
>JfiivLptloqeyKyAbmrqvTfiibj%15)10+2&yyNFAy06-0y
>?lrkqvlkD^oof`hM^acllqyKyAbmrqvTfiibj%15)10+2&yyNFAy3y
QFksbpqfd^qbB`elOfadbyKyJ^ope^iJ`?ofab%15+6)1.+3&yyNFAy.2y
>Phfojfpe^qB`elOfadbyKyJ^ope^iJ`?ofab%15+6)1.+3&yyNFAy/.y
QJfiivLptloqeyKyJfiivLptloqe%2-+4)06+1&yyNFAy06-0y
>Jfiiv$pE^osbpqyKyJfiivLptloqe%2-+4)06+1&yyNFAy06-1y

@Phfojfpe^qB`elOfadbyKyHfii5Hl_liaI^_loboptef`e`^k_bclrka^olrkaqebjfkbqlqebKloqelcJ^ope^iJ`?ofab^olrka%15)/6&yyNFAy/.y
@Jfiiv$pE^osbpqyKyQo^sbi^`olppqebofsboqlqebPlrqetebobvlrtfiicfkaqebdo^mbsfkbpproolrkaba_vAbcf^pjl_p+@ib^oqeb^ob^^olrkab^`e`o^qbql`liib`q5`o^qbplcXJfiiv$pE^osbpqZaolmmba_vAbcf^pQerd^olrka%22)14&yyNFAy06-1y
@?lrkqvlkD^oof`hM^acllqyKyCfka^kahfiiD^oof`hM^acllq^q%24)15&ql`liib`qefpeb^a+Ebfpproolrka_vqtldr^oap_rq_lqe`^k_bmriibapbmbo^qbivb^pfivyyNFAy3y

QJfiiv$pE^osbpqyKyJfiivLptloqe%2-+4)06+1&yyNFAy06-1y
>Do^mbJ^kfcbpqyKyJfiivLptloqe%2-+4)06+1&yyNFAy06-2y
QPhfojfpe^qB`elOfadbyKyJ^ope^iJ`?ofab%15+6)1.+3&yyNFAy/.y
>ObmloqqlDliapefobyKyJ^ope^iJ`?ofab%15+6)1.+3&yyNFAy21y
QDo^mbJ^kfcbpqyKy?olqeboKb^ip%16+2)1.+2&yyNFAy06-2y
Q?lrkqvlkD^oof`hM^acllqyKyAbmrqvTfiibj%15)10+2&yyNFAy3y
>FkC^slolcqebIfdeqy@yMofbpqyyKyMofbpqbpp>kbqq^%16+5)06+3&yyNFAy23/0y
>Obpq^kaObi^u^qflkyKyC^ihe^^kFpbkpqofabo%12+3)14+5&yyNFAy/.25y

QObmloqqlDliapefobyKyJ^ope^iArde^k%1/+.)32+6&yyNFAy21y
>QebC^odlabbmJfkbyKyJ^ope^iArde^k%1/+.)32+6&yyNFAy3/y
>DliaArpqBu`e^kdbyKyObjvQtlQfjbp%1/+.)34+/&yyNFAy14y
QObpq^kaObi^u^qflkyKyFkkhbbmboC^oibv%10+5)32+6&yyNFAy/.25y
eDliapefobyKyFkkhbbmboC^oibv%10+5)32+6&yyNFAy3-y
>Hl_lia@^kaibpyKyTfiif^jMbpqib%10+0)32+5&yyNFAy3-y
QFkC^slolcqebIfdeqy@yMofbpqyyKyMofbpqbpp>kbqq^%16+5)06+3&yyNFAy23/0y
>D^ojbkqplcqebIfdeqy@yMofbpqyyKyMofbpqbpp>kbqq^%16+5)06+3&yyNFAy23/1y
@D^ojbkqplcqebIfdeqy@yMofbpqyyKyCfkaDr^oaOl_boqp%15+/)35+-&^kaeb^iefptlrkaprpfkdIbppboEb^i%O^kh/&+>cqbot^oap)do^kqefjMltboTloa7CloqfqrabyyNFAy23/1y
QD^ojbkqplcqebIfdeqy@yMofbpqyyKyMofbpqbpp>kbqq^%16+5)06+3&yyNFAy23/1y

>IlpqKb`hi^`byKy>rkqfb?bokf`bPqlkbcfbia%01+2)51+0&yyNFAy52y
QIlpqKb`hi^`byKy?fiivJ^`irob%10+.)52+5&yyNFAy52y
>Mfbclo?fiivyKy?fiivJ^`irob%10+.)52+5&yyNFAy53y

>VlrkdIlsbopyKyJ^v_biiJ^`irob%10+.)56+3&yyNFAy.-3y
@Mfbclo?fiivyKyHfii^kvlcqebproolrka_l^opproolrkafkdBivtkkClobpqql`liib`qqebjb^q+Ol`hefab?l^o^obb^pfivclrka^olrka%14)5.&qlqebplrqelcDliapefob^kae^sb^ob^plk^_ibaolmo^qbyyNFAy53y
QMfbclo?fiivyKy>rkqfb?bokf`bPqlkbcfbia%01+2)51+0&yyNFAy53y
>?^`hql?fiivyKy>rkqfb?bokf`bPqlkbcfbia%01+2)51+0&yyNFAy51y
>Mofk`bppJrpqAfbyKyJ^Pqlkbcfbia%01+3)51+1&yyNFAy55y
QVlrkdIlsbopyKyQljjvGlbPqlkbcfbia%/6+6)53&yyNFAy.-3y
>Pmb^htfqeDo^jj^yKyQljjvGlbPqlkbcfbia%/6+6)53&yyNFAy...y
QPmb^htfqeDo^jj^yKyDo^jj^Pqlkbcfbia%01+6)50+6&yyNFAy...y
>KlqbqlTfiif^jyKyDo^jj^Pqlkbcfbia%01+6)50+6&yyNFAy.-4y

Q?^`hql?fiivyKy?fiivJ^`irob%10+.)52+5&yyNFAy51y
>DliaqllqeyKy?fiivJ^`irob%10+.)52+5&yyNFAy54y

@DliaqllqeyKyHfiiDliaqllqe%1.+3)45+5&^kadbqX?bokf`b$pKb`hi^`bZyyNFAy54y
@DliaArpqBu`e^kdbyKyQebXDliaArpqZkbbaba`^k_bclrkacoljqebHl_liaptef`eproolrkaqebC^odlabbmJfkb^olrka%06)5-&yyNFAy14y
@Hl_lia@^kaibpyKyQebXI^odb@^kaibpZkbbaba`^k_bclrkacoljqebHl_liaptef`eproolrkaqebC^odlabbmJfkb^olrka%06)5-&yyNFAy3-y
@QebC^odlabbmJfkbyKyQo^sbifkpfabQebC^odlabbmJfkb^q%06)5-&qle^sbfqfksbpqfd^qbayyNFAy3/y

EDliapefobyRy3615yyNFAy../y
QKlqbqlTfiif^jyKyTfiif^jMbpqib%10+0)32+5&yyNFAy.-4y
>@liib`qfkdHbimyKyTfiif^jMbpqib%10+0)32+5&yyNFAy../y
QDliaArpqBu`e^kdbyKyObjvQtlQfjbp%1/+.)34+/&yyNFAy14y
QQebC^odlabbmJfkbyKyJ^ope^iArde^k%1/+.)32+6&yyNFAy3/y
>QebG^pmboilabJfkbyKyJ^ope^iArde^k%1/+.)32+6&yyNFAy43y
QHl_lia@^kaibpyKyTfiif^jMbpqib%10+0)32+5&yyNFAy3-y
>>CfpevMbofiyKyObjvQtlQfjbp%1/+.)34+/&yyNFAy1-y
Q>CfpevMbofiyKyJ^ope^iArde^k%1/+.)32+6&yyNFAy1-y
>Croqebo@lk`bokpyKyJ^ope^iArde^k%1/+.)32+6&yyNFAy02y
>PefmjbkqqlPqlojtfkayKyTfiif^jMbpqib%10+0)32+5&yyNFAy3.y

@@liib`qfkdHbimyKy@liib`q1X@ovpq^iHbimColkapZtef`e`^k_bclrkafkqebi^hb^q%21)33&^ka^iplillqbacoljqebJroil`ptef`eproolrkaqebi^hbyyNFAy../y

QCroqebo@lk`bokpyKyDr^oaQelj^p%40+6)4/+/&yyNFAy02y
>CfkaqebIlpqDr^oapyKyDr^oaQelj^p%40+6)4/+/&yyNFAy04y
>Molqb`qqebColkqfboyKyDr^oaQelj^p%40+6)4/+/&yyNFAy2/y

>ObaIfkbkDllapyKyP^o^Qfj_boi^fk%46)35&yyNFAy50y
>>?rkaiblcQolr_ibyKyPrmbosfploO^bibk%5.+1)33+.&yyNFAy2212y

KHfii^kv_b^op^pvlrnrbpqyNFAy2/y
@QebG^pmboilabJfkbyKyCfkaqebG^pmboilabJfkb^q%3/)21&qebkqo^sbifkpfabqlfksbpqfd^qbfqyyNFAy43y

QCfkaqebIlpqDr^oapyKy>E^ic*b^qbk?lav%4/+4)3-+2&yyNFAy04y
>Afp`lsboOlic$pC^qbyKy>E^ic*b^qbk?lav%4/+4)3-+2&yyNFAy12y
QAfp`lsboOlic$pC^qbyKyOlic$p`lompb%46+5)22+3&yyNFAy12y
>ObmloqqlQelj^pyKyOlic$p`lompb%46+5)22+3&yyNFAy4.y

@>?rkaiblcQolr_ibyKyQo^sbiKloqecoljPrmbosfploO^bibk^ka`liib`q5X?rkaibplcTllaZ^olrka%46)3-&yyNFAy2212y
@Molqb`qqebColkqfboyKyHfii5Moltibop^ka2VlrkdClobpq?b^optef`e`^k_lqe_bclrkaqlqebb^pq^olrkaB^pqs^ibIlddfkd@^jm%5.)3/&^ptbii^pqlqebplrqebok^ob^^`olppqeb_ofadb^olrka%50)45&yyNFAy2/y

Q>?rkaiblcQolr_ibyKyPrmbosfploO^bibk%5.+1)33+.&yyNFAy2212y
QObmloqqlQelj^pyKyDr^oaQelj^p%40+6)4/+/&yyNFAy4.y
>AbifsboQelj^p$ObmloqyKyDr^oaQelj^p%40+6)4/+/&yyNFAy06y
QMolqb`qqebColkqfboyKyDr^oaQelj^p%40+6)4/+/&yyNFAy2/y

@Mofk`bppJrpqAfbyKyMofk`bppfp^ibsbi6jl_telfpproolrkaba_vqtldr^oaptef`e^obibsbi4pldolrmfkdtfqe^klqebofpob`ljjbkaba+Pebm^qolipqeb^ob^^olrka%36)45&yyNFAy55y
@ObaIfkbkDllapyKyQo^sbiql?o^`htbiiMrjmhfkM^q`e^olrka%35)45&lo%0.)32&^olrkaqebi^hbqlqebPlrqelcPqlojtfka@fqv^kahfiiqebAbcf^pjl_pproolrkafkdqeb^ob^ql`liib`q3XObaIfkbk?^ka^k^pZyyNFAy50y

QObaIfkbkDllapyKyP^o^Qfj_boi^fk%46)35&yyNFAy50y

EDliapefobyRy3615yyNFAy..1y
>Pmb^htfqeGbkkb^y@yJ^dbyyKyW^iafj^oTbcebiiq%10+0)33+/&yyNFAy.53-y
>PbbhlrqPF74y@yOldrbyyKyHbovkPvisfrp%10+5)32+6&yyNFAy//-2y
>D^hfk$pPrjjlkpy@yT^oil`hyyKyObjbkJ^o`lq%11+2)33+.&yyNFAy.352y
Q@liib`qfkdHbimyKyTfiif^jMbpqib%10+0)32+5&yyNFAy../y
>QebBp`^mbyKyTfiif^jMbpqib%10+0)32+5&yyNFAy..1y
QAbifsboQelj^p$ObmloqyKyJ^ope^iArde^k%1/+.)32+6&yyNFAy06y
QQebG^pmboilabJfkbyKyJ^ope^iArde^k%1/+.)32+6&yyNFAy43y
>Tbpq_ollhD^oofplkKbbapEbimyKyJ^ope^iArde^k%1/+.)32+6&yyNFAy/06y
>Bijlob$pQ^phyKyPjfqe>odrp%1.+4)32+3&yyNFAy.-64y
>>T^ooflo$pQo^fkfkdy@yT^oofloyyKyIvof^ArI^`%1.+.)32+5&yyNFAy.305y

QQebBp`^mbyKyJ^v_biiJ^`irob%10+.)56+3&yyNFAy..1y
QDliaqllqeyKy>rkqfb?bokf`bPqlkbcfbia%01+2)51+0&yyNFAy54y
QMofk`bppJrpqAfbyKyJ^Pqlkbcfbia%01+3)51+1&yyNFAy55y

QTbpq_ollhD^oofplkKbbapEbimyKyAbmrqvO^fkbo%/1+0)41+3&yyNFAy/06y
>Ofsbom^tDklii?lrkqvyKyAbmrqvO^fkbo%/1+0)41+3&yyNFAy..y
@Ofsbom^tDklii?lrkqvyKy@liib`q5XM^fkqbaDklii>oj_^kapZcoljqebOfsbom^tOrkqp^kaLrqorkkboptef`e`^k_bclrkaqlqebPlrqe^olrka%/2)53&yyNFAy..y
QOfsbom^tDklii?lrkqvyKyAbmrqvO^fkbo%/1+0)41+3&yyNFAy..y

>Croi_olt$pAbbayKyQebfqbjXTbpqc^iiAbbaZpq^oqpqefpnrbpq*aolmmba_vAbcf^p?^kafq%36)45&yyRy.64/yyLyyNFAy.51y
OTbpqc^iiyKyDlTbpq%3-).6&yyWyTbpqc^iiyyNFAy.-6y
QCroi_olt$pAbbayKyC^ojboCroi_olt%26+6).6+1&yyLyyWyTbpqc^iiyyNFAy.51y
>ObmloqqlDov^kPqlrqj^kqibyKyC^ojboCroi_olt%26+6).6+1&yyWyTbpqc^iiyyNFAy.-6y
>QebClodlqqbkEbfoilljyKyC^ojboCroi_olt%26+6).6+1&yyWyTbpqc^iiyyNFAy31y
>Tbpqc^iiPqbt%M^oq.&yKySbok^Croi_olt%26+6).6+1&yyWyTbpqc^iiyyNFAy03y
>MlloLia?i^k`evyKySbok^Croi_olt%26+6).6+1&yyWyTbpqc^iiyyNFAy.2.y
QTbpqc^iiPqbt%M^oq.&yKyP^ij^P^iab^k%23+1)0-+3&yyWyTbpqc^iiyyNFAy03y
QObmloqqlDov^kPqlrqj^kqibyKyDov^kPqlrqj^kqib%23+0)14+3&yyWyTbpqc^iiyyNFAy.-6y
>>PtfcqJbpp^dbyKyNr^oqboj^pqboIbtfp%23+6)14+/&yyOyErj^kyyWyTbpqc^iiyyNFAy3.5.y
Q>PtfcqJbpp^dbyKyQelo%23+2)2/+3&yyOyErj^kyyWyTbpqc^iiyyNFAy3.5.y
>@lkqfkrbqlPqlojtfkayKyQelo%23+2)2/+3&yyOyErj^kyyWyTbpqc^iiyyNFAy3/5.y

CPqlojtfka@fqvyKyQelo%23+2)2/+3&yyWyTbpqc^iiyyNFAy00/y
QPefmjbkqqlPqlojtfkayKyJlod^kMbpqib%30+.)41+3&yyWyPqlojtfka@fqvyyNFAy3.y
>TfkbPelm>asboqyKyObk^qlD^iifk^%30+6)40+3&yyWyPqlojtfka@fqvyyNFAy00/y
>E^oi^kKbbap^ObprmmivyKyE^oi^k?^dibv%3/+2)34+5&yyWyPqlojtfka@fqvyyNFAy000y
ePqlojtfka@fqvyKyFkkhbbmbo>iifplk%3-+2)42+/&yyWyPqlojtfka@fqvyyNFAy001y
QTfkbPelm>asboqyKyPrwbqq^D^iifk^%3-+/)43+5&yyWyPqlojtfka@fqvyyNFAy00/y
QE^oi^kKbbap^ObprmmivyKyObj^P`ekbfabo%25)34+2&yyWyPqlojtfka@fqvyyNFAy000y
>M^`h^dbcloQeroj^kyKyObj^P`ekbfabo%25)34+2&yyWyPqlojtfka@fqvyyNFAy001y
QM^`h^dbcloQeroj^kyKyQeroj^kP`ekbfabo%2/+2)50+3&yyWyPqlojtfka@fqvyyNFAy001y

QBijlob$pQ^phyKyDofj^kaBijlob%26+4)01&yyWyPqlojtfka@fqvyyNFAy.-64y
>Pqlojmfhb$pAbifsbovyKyDofj^kaBijlob%26+4)01&yyWyPqlojtfka@fqvyyNFAy020y
OAbbmorkQo^jyKyFkqebAt^osbkAfpqof`q%4-+0)/6+2&yyWyPqlojtfka@fqvyyNFAy333.y
KQ^hbqebqo^jqlFolkclodbyNFAy333.y
>AbbmorkO^qOlrkarmyKyJlkqvyyNFAy333.y
@AbbmorkO^qOlrkarmyKy@^mqrob2AbbmorkO^qp_vrpfkdqebXO^q@^q`ebo$pCirqbZ+Ib^aqebo^qp_^`hqlJlkqv+Alk$qclodbqqlqrokfkqebcirqbtebkvlr$obcfkfpebayyRy.4..4yyNFAy333.y
QAbbmorkO^qOlrkarmyKyJlkqvyyNFAy333.y

O@fqvlcFolkclodbyNFAy100y
C@fqvlcFolkclodbyKyFkqeb`bkqbolcqltk^qqebClodb%22+22)14+43&yyWyFolkclodbyyNFAy100y

OArkJloldeyKyOrkqlArkJlolde%.1)53&yyWyArkJloldeyyNFAy100y
>QebMr_if`Pbos^kqyKyPbk^qloJbeoPqlkbe^iilt%35+3)22+6&yyWyArkJloldeyyNFAy100y
>Qelpb?i^pqbaQolddpyKyClobj^kPqlkb_olt^qDli$?li^oNr^oov%36+.)23+0&yyWyArkJloldeyyNFAy10/y
@QebMr_if`Pbos^kqyKyHfii.-Ol`hg^t?lkbpk^mmbop^olrka%4.)2.&^qqebDli$?li^onr^oovyyWyArkJloldeyyNFAy100y
@Qelpb?i^pqbaQolddpyKyHfii3Ol`hg^tPhriiqerjmbop^olrkaqebDli$?li^onr^oov^q%36)26&yyWyArkJloldeyyNFAy10/y
QQebMr_if`Pbos^kqyKyPbk^qloJbeoPqlkbe^iilt%35+3)22+6&yyWyArkJloldeyyNFAy100y
QQelpb?i^pqbaQolddpyKyClobj^kPqlkb_olt%36+.)23+0&yyWyArkJloldeyyNFAy10/y

OIl`eJla^kyKyQ^hbqebol^ab^pq)qebkplrqe%5-+-)2/+2&qeolrdeqebqrkkbiyyWyArkJloldeyyNFAy//1y
>FkAbcbkpblcqebHfkd$pI^kapyKyJlrkq^fkbbo@l__ibcifkq%//+.)40+3&yyWyIl`eJla^kyyNFAy//1y
>QebQolddQeob^qyKy@^mq^fkOrdbicrpp%/0+/)40+4&yyWyIl`eJla^kyyNFAy/34y
@FkAbcbkpblcqebHfkd$pI^kapyKyHfii.-PqlkbpmifkqboQoldd^ka.-PqlkbpmifkqboP`lrq^olrka%0.)4-+2&)%/5)20&yyWyIl`eJla^kyyNFAy//1y
@QebQolddQeob^qyKy@liib`q5XQolddPqlkbQbbqeZclrka^olrka%00)4/&yyWyIl`eJla^kyyNFAy/34y
QQebQolddQeob^qyKy@^mq^fkOrdbicrpp%/0+/)40+4&yyWyIl`eJla^kyyNFAy/34y
QFkAbcbkpblcqebHfkd$pI^kapyKyJlrkq^fkbbo@l__ibcifkq%//+.)40+3&yyWyIl`eJla^kyyNFAy//1y

>O^q@^q`efkdyWyIl`eJla^kyyKyJlrkq^fkbboH^aobii%03)13&yyNFAy1.3y
>Jlrkq^fkbboPqlojmfhb$pQ^phyWyIl`eJla^kyyKyJlrkq^fkbboH^aobii%03)13&yyNFAy.006y
cQebip^j^oyKyQelodorj?loobiplk%00+6)2-+6&yyWyIl`eJla^ky
@O^q@^q`efkdyWyIl`eJla^kyyKyHfii^kvlcqebQrkkbiO^qjl_ptef`e`^k_bclrkaqlqebKloqelctebobvlrhfiibaqebQolddp^olrka%/6)10&ql`liib`q./XQrkkbiO^qB^opZyyNFAy1.3y
Q>O^q@^q`efkdyWyIl`eJla^kyyKyJlrkq^fkbboH^aobii%03)13&yyNFAy1.3y

QPqlojmfhb$pAbifsbovyKyJlrkq^fkbboPqlojmfhb%/1+4).5+0&yyWyIl`eJla^kyyNFAy020y
QJlrkq^fkbboPqlojmfhb$pQ^phyWyIl`eJla^kyyKyJlrkq^fkbboPqlojmfhb%/1+4).5+0&yyNFAy.006y
>Pqlojmfhb$pLoaboyWyIl`eJla^kyyKyJlrkq^fkbboPqlojmfhb%/1+4).5+0&yyNFAy.005y

EPqlojtfka@fqvyRy3615y
QPqlojmfhb$pLoaboyWyPqlojtfka@fqvyyKyCrobkIlkd_b^oa%31+4)04+2&yyNFAy.005y

QPmb^htfqeGbkkb^y@yJ^dbyyKyGbkkb^@^kklk%16+3)53+2&yyWyPqlojtfka@fqvyyNFAy.53-y
>JfooloI^hbyKyGbkkb^@^kklk%16+3)53+2&yy@yJ^dbyyWyPqlojtfka@fqvyyNFAy.53.y

QD^hfk$pPrjjlkpy@yT^oil`hyyKyD^hfkqebA^oh_fkabo%06+0)52+/&yyWyPqlojtfka@fqvyyNFAy.352y
>Probk^@^ibalkyKyD^hfkqebA^oh_fkabo%06+0)52+/&yy@yT^oil`hyyWyPqlojtfka@fqvyyNFAy.355y

Q@lkqfkrbqlPqlojtfkayKyLpof`Pqo^kd%44+.)3.+/&yyWyPqlojtfka@fqvyyOyErj^kyyNFAy3/5.y
>Arkd^oIlkdaofkhyKyLpof`Pqo^kd%44+.)3.+/&yyWyPqlojtfka@fqvyyOyErj^kyyNFAy3/3.y

QPbbhlrqPF74y@yOldrbyyKyJ^pqboJ^qef^pPe^t%45+2)4-+4&yyWyPqlojtfka@fqvyyNFAy//-2y
>Pk^q`e^kaDo^_y@yOldrbyyKyJ^pqboJ^qef^pPe^t%45+2)4-+4&yyWyPqlojtfka@fqvyyNFAy//-3y

Q>T^ooflo$pQo^fkfkdyKyE^oov?roidr^oa%44)20+0&yy@yT^oofloyyWyPqlojtfka@fqvyyNFAy.305y
>?^oqib_vqebAorkhyKyE^oov?roidr^oa%44)20+0&yy@yT^oofloyyWyPqlojtfka@fqvyyNFAy.306y
Q?^oqib_vqebAorkhyKy?^oqib_v%43+5)2/+5&yy@yT^oofloyyWyPqlojtfka@fqvyyNFAy.306y
>?b^q?^oqib_vyKy?^oqib_v%43+5)2/+5&yy@yT^oofloyyWyPqlojtfka@fqvyyNFAy.31-y
Q?b^q?^oqib_vyKy?^oqib_v%43+5)2/+5&yy@yT^oofloyyWyPqlojtfka@fqvyyNFAy.31-y
>?^oqib_v$pJrdyKy?^oqib_v%43+5)2/+5&yy@yT^oofloyyWyPqlojtfka@fqvyyNFAy.332y
Q?^oqib_v$pJrdyKyE^oov?roidr^oa%44)20+0&yy@yT^oofloyyWyPqlojtfka@fqvyyNFAy.332y
>J^ope^iE^dd^oayKyE^oov?roidr^oa%44)20+0&yy@yT^oofloyyWyPqlojtfka@fqvyyNFAy.333y

KDbq^QljblcAfsfkfqvyIy3442yyKyDlpbbArqelof^kO^ii%2-+3)14+2&fkqeb@^qebao^ilcIfdeqyy@yM^i^afkyyWyPqlojtfka@fqvyyNFAy.31/y
>QebQljblcAfsfkfqv%M^oq.&y@yM^i^afkyyRy3442yyNFAy.31/yyWyPqlojtfka@fqvy
QQebQljblcAfsfkfqv%M^oq.&yKyArqelof^kO^ii%2-+3)14+2&yy@yM^i^afkyyNFAy.31/yyWyPqlojtfka@fqvy
>QebQljblcAfsfkfqv%M^oq/&yKyArqelof^kO^ii%2-+3)14+2&yy@yM^i^afkyyNFAy.310yyWyPqlojtfka@fqvy
QQebQljblcAfsfkfqv%M^oq/&yKyPqbme^kfbQrokbo%30+5)4/+0&yy@yM^i^afkyyNFAy.310yyWyPqlojtfka@fqvy
>QebQljblcAfsfkfqv%M^oq0&yKyPqbme^kfbQrokbo%30+5)4/+0&yy@yM^i^afkyyNFAy.311yyWyPqlojtfka@fqvy
QQebQljblcAfsfkfqv%M^oq0&yKyPqbme^kfbQrokbo%30+5)4/+0&yy@yM^i^afkyyNFAy.311yyWyPqlojtfka@fqvy
>QebQljblcAfsfkfqv%M^oq1&yKyPqbme^kfbQrokbo%30+5)4/+0&yy@yM^i^afkyyNFAy.45-yyWyPqlojtfka@fqvy
QQebQljblcAfsfkfqv%M^oq1&yKyArqelof^kO^ii%2-+3)14+2&yy@yM^i^afkyyNFAy.45-yyWyPqlojtfka@fqvy
>QebQljblcAfsfkfqv%M^oq2&yKyArqelof^kO^ii%2-+3)14+2&yy@yM^i^afkyyNFAy.45.yyWyPqlojtfka@fqvy
QQebQljblcAfsfkfqv%M^oq2&yKyD^wfkQbkloj%16+4)12+.&yy@yM^i^afkyyNFAy.45.yyWyPqlojtfka@fqvy
>QebQljblcAfsfkfqv%M^oq3&yKyD^wfkQbkloj%16+4)12+.&yy@yM^i^afkyyNFAy.453yyWyPqlojtfka@fqvy

QArkd^oIlkdaofkhyKyArkd^oIlkdaofkh%4-+6)4/+4&yyOyErj^kyyWyPqlojtfka@fqvyyNFAy3/3.y
>ObqrokqlIbtfpyKyArkd^oIlkdaofkh%4-+6)4/+4&yyOyErj^kyyWyPqlojtfka@fqvyyNFAy3/52y
CPbkqfkbiEfiiyOyErj^kyyKyArkd^oIlkdaofkh%4-+6)4/+4&yyWyPqlojtfka@fqvyyNFAy020y
QObqrokqlIbtfpyKyNr^oqboj^pqboIbtfp%23+6)14+/&yyOyErj^kyyWyTbpqc^iiyyNFAy3/52y
CPqlojtfka@fqvyOyErj^kyyKyQelo%23+2)2/+3&yyWyTbpqc^iiyyNFAy020y

>Qeb@liib`qloyKyQebfqbjXDliaMf`hrmP`ebaribZpq^oqpnrbpq*aolmmba_vOfsbom^tLrqorkkbo^kaDorccPtfcq_fqb%/4)55&yyRy.0-4yyLyyNFAy./0y
QQeb@liib`qloyLyyKyJ^ope^iArde^k%1/+.)32+6&yyNFAy./0y

@JfooloI^hbyKy?ofkd^XJfooloI^hbT^qboP^jmibZqlGbkkb^@^kklk%/5+3)35+2&fkPqlojtfkayyRy4/-4yy@yJ^dbyyNFAy.53.y
@Pk^q`e^kaDo^_yKyCfkaqebAbcf^pAl`hj^pqbo%15+.)54+.&^kaob`lsboqebXPefmmfkdP`ebaribZyy@yOldrbyyNFAy//-3y
@Probk^@^ibalkyKyObqofbsbXProbk^$p@elhboZaolmmba_vProbk^@^ibalk%4.)5-+3&yy@yT^oil`hyyNFAy.355y

QJ^ope^iE^dd^oayKyJ^ope^iE^dd^oa%51+3)36+1&yy@yT^oofloyyNFAy.333y
>Ab^a*qllqeG^`hyKyJ^ope^iE^dd^oa%51+3)36+1&yy@yT^oofloyyNFAy.334y
@Ab^a*qllqeG^`hyKyObqofbsbXJ^ope^iE^dd^oa$p?^adbZ%56+1)45+6&coljAb^a*qllqeG^`h$p`^jmyy@yT^oofloyyNFAy.334y
QAb^a*qllqeG^`hyKyJ^ope^iE^dd^oa%51+3)36+1&yy@yT^oofloyyNFAy.334y

QQebQljblcAfsfkfqv%M^oq3&yKyEbkwbC^rih%4/+3)2.+2&yyRy3533yy@yM^i^afkyyNFAy.453y
>QebQljblcAfsfkfqv%M^oq4&yKyEbkwbC^rih%4/+3)2.+2&yy@yM^i^afkyyNFAy.454y
@QebQljblcAfsfkfqv%M^oq4&yKyHfiiAbcf^pOldrbTfw^oap^olrkaqebfpi^kafkPqlkb`^fobI^hbfkBitvkkClobpqyy@yM^i^afkyyNFAy.454y

EPqlojtfka@fqvyRy3615yyNFAy020y
QJfooloI^hbyKyGbkkb^@^kklk%16+3)53+2&yy@yJ^dbyyWyPqlojtfka@fqvyyNFAy.53.y
QPk^q`e^kaDo^_yKyJ^pqboJ^qef^pPe^t%45+2)4-+4&yy@yOldrbyyWyPqlojtfka@fqvyyNFAy//-3y
QProbk^@^ibalkyKyD^hfkqebA^oh_fkabo%06+0)52+/&yy@yT^oil`hyyWyPqlojtfka@fqvyyNFAy.355y
>Qeb?fkafkdyKyD^hfkqebA^oh_fkabo%06+0)52+/&yy@yT^oil`hyyWyPqlojtfka@fqvyyNFAy.356y
@Qeb?fkafkdy@yT^oil`hyyKyRpfkdqebX?illapqlkb@elhboZ)prjjlk^kapr_arb^slfat^ihboyyRy36/5yyWyPqlojtfka@fqvyyNFAy.356y
QQeb?fkafkdyKyD^hfkqebA^oh_fkabo%06+0)52+/&yy@yT^oil`hyyWyPqlojtfka@fqvyyNFAy.356y

QQebQljblcAfsfkfqv%M^oq4&yKyD^wfkQbkloj%16+4)12+.&yy@yM^i^afkyyNFAy.454yyWyPqlojtfka@fqvy
>QebQljblcAfsfkfqv%M^oq5&yKyD^wfkQbkloj%16+4)12+.&yy@yM^i^afkyyNFAy.455yyWyPqlojtfka@fqvy
QQebQljblcAfsfkfqv%M^oq5&yKyArqelof^kO^ii%2-+3)14+2&yy@yM^i^afkyyNFAy.455yyWyPqlojtfka@fqvy

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
