DugisGuideViewer:RegisterGuide("Teldrassil (1-12 Night Elf)", "Darkshore (12-17)", "Alliance", "L", function()
return [[
AAA

>Qeb?^i^k`blcK^qrob%M^oq.&yKy@lkpbos^qloFiqe^i^fkb%25+4)11+0&yyNFAy123y
@Qeb?^i^k`blcK^qrob%M^oq.&yKyHfii1VlrkdKfdeqp^_bopil`^qba^olrka%3.)10&^ka1VlrkdQefpqib?l^opil`^qba^olrka%3-)12&yyNFAy123y
QQeb?^i^k`blcK^qrob%M^oq.&yKy@lkpbos^qloFiqe^i^fkb%25+4)11+0&yyNFAy123y
>Qeb?^i^k`blcK^qrob%M^oq/&yKy@lkpbos^qloFiqe^i^fkb%25+4)11+0&yyNFAy124y

>Bk`ovmqbaPfdfiyKy@lkpbos^qloFiqe^i^fkb%25+4)11+0&yy@yOldrbyyNFAy0..5y
>Bq`ebaPfdfiyKy@lkpbos^qloFiqe^i^fkb%25+4)11+0&yy@yErkqboyyNFAy0..4y
>E^iiltbaPfdfiyKy@lkpbos^qloFiqe^i^fkb%25+4)11+0&yy@yMofbpqyyNFAy0..6y
>PfjmibPfdfiyKy@lkpbos^qloFiqe^i^fkb%25+4)11+0&yy@yT^oofloyyNFAy0..3y
>Sboa^kqPfdfiyKy@lkpbos^qloFiqe^i^fkb%25+4)11+0&yy@yAorfayyNFAy0./-y

>QebTllai^kaMolqb`qlo%M^oq.&yKyJbifqe^oPq^debij%26+6)1/+2&yyNFAy125y
>>DllaCofbkayKyAfo^kf^Pfisbopefkb%3-+6)1/&yyNFAy1162y
QQebTllai^kaMolqb`qlo%M^oq.&yKyQ^ofkaobii^%24+4)12+/&yyNFAy125y
>QebTllai^kaMolqb`qlo%M^oq/&yKyQ^ofkaobii^%24+4)12+/&yyNFAy126y
@QebTllai^kaMolqb`qlo%M^oq/&yKyHfiiDobii%obafjmp&il`^qbafkqeobbpmlqp%23)12+6&)%3.+/)12+6&^ka%23+1)1.+3&^ka`liib`q5XCbiJlppZyyNFAy126y
QQebTllai^kaMolqb`qlo%M^oq/&yKyQ^ofkaobii^%24+4)12+/&yyNFAy126y
>Tb_tllaSbkljyKyDfipe^i^kTfkat^ihbo%24+5)1.+4&yyNFAy6.3y

QBk`ovmqbaPfdfiyKyCo^erkPe^abtefpmbo%26+3)05+4&yy@yOldrbyyNFAy0..5y
QBq`ebaPfdfiy@yErkqboyyKy>v^kk^Bsbopqofab%25+3)1-+2&yyNFAy0..4y
QE^iiltbaPfdfiyKyPe^ka^%26+/)1-+2&yy@yMofbpqyyNFAy0..6y
QPfjmibPfdfiyKy>ivfppf^%26+3)05+2&yy@yT^oofloyyNFAy0..3y
QSboa^kqPfdfiyKyJ^oa^kqPqolkdl^h%25+3)1-+1&yy@yAorfayyNFAy0./-y

@Qeb?^i^k`blcK^qrob%M^oq/&yKyHfii4J^kdvKfdeqp^_bop%3-)03&^ka4Qefpqib?l^op%3-)04&yyNFAy124y
@Tb_tllaSbkljyKyDlKloqe%24)01&^kahfiiTb_tllaPmfabo^ka`liib`q.-XTb_tllaSbkljP^`pZyyNFAy6.3y
Q>DllaCofbkayKyFsboolk%21+3)00&yyNFAy1162y
>>CofbkafkKbbayKyFsboolk%21+3)00&yyNFAy02.6y
QTb_tllaSbkljyKyDfipe^i^kTfkat^ihbo%24+5)1.+4&yyNFAy6.3y
>Tb_tllaBddyKyDfipe^i^kTfkat^ihbo%24+5)1.+4&yyNFAy6.4y

QQeb?^i^k`blcK^qrob%M^oq/&yKy@lkpbos^qloFiqe^i^fkb%25+4)11+0&yyNFAy124y
Q>CofbkafkKbbayKyAfo^kf^Pfisbopefkb%3-+6)1/&yyNFAy02.6y
>Fsboolk$p>kqfalqb%M^oq.&yKyAfo^kf^Pfisbopefkb%3-+6)1/&yyNFAy02/.y

@Fsboolk$p>kqfalqb%M^oq.&yKy@liib`q4XEv^`fkqeJrpeolljpZpmob^a^olrka%24)03&+Dbq1XJllkmbq^iIfifbpZil`^qba^q%24)04&+QebXTb_tllaF`eloZfpil`^qba^q%23)0/&aolmmba_vTb_tllapmfabopyyNFAy02/.y
@Tb_tllaBddyKyDlfkpfabqeb`^sb^kaeb^aql%24)/3&`liib`qXTb_tllaBddZdr^oaba_v^ibsbi2pmfaboyyNFAy6.4y
QTb_tllaBddyKyDfipe^i^kTfkat^ihbo%24+5)1.+4&yyNFAy6.4y
>Qbk^olk$pPrjjlkpyKyDfipe^i^kTfkat^ihbo%24+5)1.+4&yyNFAy6/-y
QQbk^olk$pPrjjlkpyKyQbk^olkPqlojdofm%26+.)06+1&yyNFAy6/-y
>@oltklcqebB^oqe%M^oq.&yKyQbk^olkPqlojdofm%26+.)06+1&yyNFAy6/.y
QFsboolk$p>kqfalqb%M^oq.&yKyAfo^kf^Pfisbopefkb%3-+6)1/&yyNFAy02/.y
>Fsboolk$p>kqfalqb%M^oq/&yKyAfo^kf^Pfisbopefkb%3-+6)1/&yyNFAy02//y
@@oltklcqebB^oqe%M^oq.&yKyCfiiqebX@ovpq^iMef^iZ^qqebjllktbii%26)00&^ka_ofkdfq_^`hqlQbk^olkPqlojdofm^qlm>iao^ppfiyyRy2.52yyNFAy6/.y
QFsboolk$p>kqfalqb%M^oq/&yKyFsboolk%21+3)00&yyNFAy02//y
Q@oltklcqebB^oqe%M^oq.&yKyQbk^olkPqlojdofm%26+.)06+1&yyNFAy6/.y
>@oltklcqebB^oqe%M^oq/&yKyQbk^olkPqlojdofm%26+.)06+1&yyNFAy6/5y

>Ali^k^^oAbifsbovyKyMloqe^kkfrp%3.+/)14+3&yyNFAy/.26y
>Wbkk$p?faafkdyKyWbkkClriellc%3-+2)23+0&yyNFAy155y

OAli^k^^oyKyOrkqlAli^k^^o%22+4)26+5&yyNFAy6/6y
QAli^k^^oAbifsbovyKyFkkhbbmboHbia^jvo%22+4)26+5&yyNFAy/.26y
eAli^k^^oyKyFkkhbbmboHbia^jvo%22+4)26+5&yyNFAy6/6y
Q@oltklcqebB^oqe%M^oq/&yKy@lofqeo^pJllko^db%23+/)3.+4&yyNFAy6/5y
>@oltklcqebB^oqe%M^oq0&yKy@lofqeo^pJllko^db%23+/)3.+4&yyNFAy6/6y
>Abk^i^k$pB^oqeyKyPvo^i?i^abib^c%23+.)24+4&yyNFAy664y
>>Qolr_ifkd?obbwbyKy>qeofa^p?b^oj^kqib%22+6)24+0&yyNFAy142y
>QebBjbo^iaAob^j`^q`eboyKyQ^iilkh^fPtfcqollq%22+2)23+6&yyNFAy/105y
>QtfpqbaE^qobayKyQ^iilkh^fPtfcqollq%22+2)23+6&yyNFAy60/y

@Wbkk$p?faafkdyKy@liib`q0XKfdeqp^_boC^kdpZaolmmba_vKfdeqp^_boil`^qba^olrka%3-)25&^ka%2.)26&+0XPqofdfaLtiCb^qebopZaolmmba_vPqofdfaLtiil`^qba^olrka%21)26&^ka%31)2.&+0pt^q`ebplcXTb_tllaPmfaboPfihZaolmmba_vTb_tllaIrohboil`^qba^olrka%3-)25&^ka%2/)31&yyNFAy155y
@@oltklcqebB^oqe%M^oq0&yKyDlqlqebjllktbii%30)25&+CfiiqebXG^abMef^iZ^ka_ofkdfq_^`hql@lofqeo^pJllko^dbfkAli^k^^oyyRy23.6yyNFAy6/6y
Q>Qolr_ifkd?obbwbyKyD^boli^pQ^isbqeobk%33+0)25+3&yyNFAy142y
>Dk^oimfkb@loormqflkyKyD^boli^pQ^isbqeobk%33+0)25+3&yyNFAy143y
@QebBjbo^iaAob^j`^q`eboyKyDbqqebXBjbo^iaAob^j`^q`eboZ%35+-)26+3&yyNFAy/105y
QWbkk$p?faafkdyKyWbkkClriellc%3-+2)23+0&yyNFAy155y
>PbbhObabjmqflkyKyPvo^i?i^abib^c%23+.)24+4&yyNFAy156y
KHbbm^kbvblrqcloCbi@lkbpyKyKbbabacloPbbhObabjmqflk+Clrka^qqeb_^pblcqobbpyyNFAy156y

QAbk^i^k$pB^oqeyKyAbk^i^k%3-+6)35+2&yyNFAy664y
>Qfj_boifkdPbbapyKyAbk^i^k%3-+6)35+2&yyNFAy6.5y
>Qfj_boifkdPmolrqpyKyAbk^i^k%3-+6)35+2&yyNFAy6.6y
@Qfj_boifkdPbbapyKy@liib`q5XQfj_boifkdPbbapZaolmmba_vQfj_boifkd^olrkaqebi^hbfk^ob^p%26)4/&lo%23)32&yyNFAy6.5y
@Qfj_boifkdPmolrqpyKy@liib`q./XQfj_boifkdPmolrqpZpmob^a^olrka%26)4.&yyNFAy6.6y
QQfj_boifkdPbbapyKyAbk^i^k%3-+6)35+2&yyNFAy6.5y
>Obiif^kDobbkpmvobyKyAbk^i^k%3-+6)35+2&yyNFAy6//y
QQfj_boifkdPmolrqpyKyAbk^i^k%3-+6)35+2&yyNFAy6.6y

Q@oltklcqebB^oqe%M^oq0&yKy@lofqeo^pJllko^db%23+/)3.+4&yyNFAy6/6y
>@oltklcqebB^oqe%M^oq1&yKy@lofqeo^pJllko^db%23+/)3.+4&yyNFAy600y
QDk^oimfkb@loormqflkyKy>qeofa^p?b^oj^kqib%22+6)24+0&yyNFAy143y
>QebObif`plcT^hbkfkdyKy>qeofa^p?b^oj^kqib%22+6)24+0&yyNFAy150y
QQebBjbo^iaAob^j`^q`eboyKyQ^iilkh^fPtfcqollq%22+2)23+6&yyNFAy/105y
>Cbol`fq^pqebAob^jB^qboyKyQ^iilkh^fPtfcqollq%22+2)23+6&yyNFAy/126y

@PbbhObabjmqflkyKy@liib`q0XCbi@lkbpZp`^qqboba^olrka%24)30&yyNFAy156y
QPbbhObabjmqflkyKyWbkkClriellc%3-+2)23+0&yyNFAy156y
@Cbol`fq^pqebAob^jB^qboyKyHfii4Dk^oimfkbJvpqf`p%36)21&^kahfiiCbol`fq^pqebAob^jB^qbo%35+5)20+3&cloqebjfppfkdgbtbi%36)2/&yyRy5-16yyNFAy/126y

@QtfpqbaE^qobayKyHfiiIloaJbibk^p%2/)16&^ka_ofkdefpeb^aqlQ^iilkh^fPtfcqollqyyNFAy60/y
QCbol`fq^pqebAob^jB^qboyKyQ^iilkh^fPtfcqollq%22+2)23+6&yyNFAy/126y
QQtfpqbaE^qobayKyQ^iilkh^fPtfcqollq%22+2)23+6&yyNFAy60/y

>QebOl^aqlA^ok^pprpyKyJllkMofbpqbpp>j^o^il`^qba_bqtbbk%2-)21&^ka%22)25&yyNFAy154y
@QebOl^aqlA^ok^pprpyKyHfii3Dk^oimfkb>j_rpebop%15)21&yyNFAy154y

KDbqOrkblcKbpqfkdyKyEb^aaltkfkqlqeb?^k$bqefi?^ooltAbk%11+1.)24+54&+>qqebcfopqpbqlc_ofadbpq^hbqebibcq_ofadb%11+1-)3-+34&yyNFAy150yyNLyOrkblcKbpqfkd7.,.y
KDbq?i^`hCb^qeboNrfiiyKy>`olppqeblqebo_ofadb%10+4-)3.+//&yyNFAy150yyNLy?i^`hCb^qeboNrfii7.,.y
>QebPibbmfkdAorfayKyL_bkO^db`i^t%11+6)3.+2&yyNFAy/21.y
KDbqP^mmefoblcPhvyKyGrjmaltk^kadlplrqe%11+4-)3/+11&yyNFAy150yyNLyP^mmefoblcPhv7.,.y
@QebObif`plcT^hbkfkdyKyDlql?^k$bqefi?^ooltAbkbkqo^k`b%10)25&+X?i^`hCb^qeboNrfiiZ%10+5)3.+/&fk^pj^iiollj^`olpp^_ofadb+XOrkblcKbpqfkdZ%11+2)3-+3&fk^pj^iiollj^`olpp^afccbobkq_ofadb+P^jb`e^j_bo^pqebNrfii+XP^mmefoblcPhvZ%11+4)3/+2&fk^pj^iiollj^qqebsbov_lqqljlcqeb`e^j_bo+XO^sbk@i^tQ^ifpj^kZ%12+4)24+1&+Dbqqebob_vq^hfkdqebb^pqbok_ofadbfkqe^q`e^j_bo+@ib^oqebpj^iiollj^kaq^hbqebqrkkbilkqebibcq+Fqib^apqlqeb_^i`lkvqe^qqeb`ebpqfplkyyNFAy150y
@QebPibbmfkdAorfayKyHfiiDk^oimfkbPe^j^k%11)26&rkqfivlrcfka^XPe^j^kSllall@e^ojZyyNFAy/21.y
QQebPibbmfkdAorfayKyL_bkO^db`i^t%11+6)3.+2&yyNFAy/21.y
>Aorfalcqeb@i^tyKyL_bkO^db`i^t%11+6)3.+2&yyNFAy/23.y
@Aorfalcqeb@i^tyKyHfiiL_bkO^db`i^tplriibpp_lav%11+6)3.+2&^kaqebkrpbqebXSllall@e^ojZlkqeb_lavyyRy5.16yyNFAy/23.y
QAorfalcqeb@i^tyKyL_bkO^db`i^t%11+6)3.+2&yyNFAy/23.y

@@oltklcqebB^oqe%M^oq1&yKyDlqlqebjllktbii%1/)33&^kacfiiqebXQlroj^ifkbMef^iZyyRy23/.yyNFAy600y

Q@oltklcqebB^oqe%M^oq1&yKy@lofqeo^pJllko^db%23+/)3.+4&yyNFAy600y
>@oltklcqebB^oqe%M^oq2&yKy@lofqeo^pJllko^db%23+/)3.+4&yyNFAy4050y
QQebObif`plcT^hbkfkdyKy>qeofa^p?b^oj^kqib%22+6)24+0&yyNFAy150y
>Rop^iqebJ^riboyKy>qeofa^p?b^oj^kqib%22+6)24+0&yyNFAy153y
QQebOl^aqlA^ok^pprpyKyJllkMofbpqbpp>j^o^il`^qba_bqtbbk%2-)21&^ka%22)25&yyNFAy154y

>Ebbafkdqeb@^iiyKyH^i%23+.)3-+6&yy@yAorfayyNFAy26/0y

OA^ok^pprpyKyOrkqlA^ok^pprp%/4)22&yyNFAy6/0y
QObiif^kDobbkpmvobyKyObiif^kDobbkpmvob%05+1)/.+5&yyWyA^ok^pprpyyNFAy6//y
>QrjlopyKyObiif^kDobbkpmvob%05+1)/.+5&yyWyA^ok^pprpyyNFAy6/0y

QEbbafkdqeb@^iiy@yAorfayyKyJ^qeobkdvi?b^ot^ihbo%02+/)5+.&yyWyA^ok^pprpyyNFAy26/0y
>Jllkdi^abyKyJ^qeobkdvi?b^ot^ihbo%02+/)5+.&yy@yAorfayyWyA^ok^pprpyyNFAy26/.y
OJllkdi^abyKy@^pqQbibmloq7Jllkdi^abPmbiiyy@yAorfayyNFAy26/.y
QJllkdi^abyKyAbkaofqbPq^o_i^wb%23+/)0-+2&yy@yAorfayyWyJllkdi^abyyNFAy26/.y
>Dob^q?b^oPmfofqyKyAbkaofqbPq^o_i^wb%23+/)0-+2&yy@yAorfayyWyJllkdi^abyyNFAy26/6y
@Dob^q?b^oPmfofqy@yAorfayyKyPbbhlrqqebDob^q?b^oPmfofq%06)/4&fkkloqetbpqbokJllkdi^ab^kaib^okte^qfqe^pqlpe^obtfqevlr^_lrqqebk^qroblcqeb_b^oyyWyJllkdi^abyyNFAy26/6y
QDob^q?b^oPmfofqyKyAbkaofqbPq^o_i^wb%23+/)0-+2&yy@yAorfayyWyJllkdi^abyyNFAy26/6y
>?^`hqlA^ok^pprpyKyAbkaofqbPq^o_i^wb%23+/)0-+2&yy@yAorfayyWyJllkdi^abyyNFAy260.y
CA^ok^pprpy@yAorfayyKyPfis^Cfi$k^sbqe%11)12&yyNFAy3--.yyWyJllkdi^aby
Q?^`hqlA^ok^pprpy@yAorfayyKyJ^qeobkdvi?b^ot^ihbo%02+/)5+.&yyWyA^ok^pprpyyNFAy260.y
>?lav^kaEb^oqy@yAorfayyKyJ^qeobkdvi?b^ot^ihbo%02+/)5+.&yyWyA^ok^pprpyyNFAy3--.y
OOrq$qebo^kSfii^dbyKyQebmloq^itbpqlcqeb_^kh%0-+2)1.+1&yyWyA^ok^pprpyy@yAorfayyNFAy/2.6y
C>r_boafkbyKySbpmovpqrp%25+1)61+-&yy@yAorfayyNFAy/2.6y
@?lav^kaEb^oqyKyRpbqebX@bk^oflkJllkarpqZlkqebJllkhfkPqlkblc>r_boafkbql_ofkdcloqeIrk^`i^t%10)13&+Coljqebob)vlrjrpqc^`bIrk^`i^t^kab^okqebpqobkdqelc_lav^kaeb^oqfqmlppbppbpyyRy.2/-5yy@yAorfayyWyA^ohpelobyyNFAy3--.y
CA^ok^pprpy@yAorfayyKy%03+1)12+2&yyWyA^ohpelobyyNFAy/2.6y
Q?lav^kaEb^oqy@yAorfayyKyJ^qeobkdvi?b^ot^ihbo%02+/)5+.&yyWyA^ok^pprpyyNFAy3--.y

>QebQbjmiblcqebJllkyKyPfpqbo>nrfkkb%/6)12+2&yyWyA^ok^pprpyyNFAy/2.6y
QQebQbjmiblcqebJllkyKyMofbpqbpp>$jllo^%03+1)53&yyWyA^ok^pprpyyNFAy/2.6y
>Qb^oplcqebJllkyKyMofbpqbpp>$jllo^%03+1)53&yyWyA^ok^pprpyyNFAy/2.5y

>Kbpp^Pe^altplkdyKyJvao^kkri%4-+2)10+5&yyOyKfdeqBicyyWyA^ok^pprpyyNFAy3011y

>QebDiltfkdCorfqyKyPqo^kdbCorfqbaMi^kq%1/+3)42+6&yyNFAy60-y
@Rop^iqebJ^riboyKyHfiiRop^iqebJ^ribo%06)5-&yyNFAy153y

@QrjlopyKy@liib`q2XJlppvQrjlopZ^olrka%10)1-&yyNFAy6/0y
@@oltklcqebB^oqe%M^oq2&yKyDlqlqebjllktbii%05)01&^kacfiiqebX>jbqevpqMef^iZyyRy.5.2/yyNFAy4050y
>QebBk`e^kqbaDi^abyKyPbkqfkbi>ovkf^@ilrap_ob^h%05+0)01+1&yyNFAy604y

>JfpqyKyJfpq*qtlil`^qflkp^q%0.+2)0.+3&^ka%05+/)01+1&yyNFAy605y
>QebPefjjbofkdColkayKyPqo^kdbColkabaMi^kq%01+5)/5+6&yyNFAy60.y
@QebBk`e^kqbaDi^abyKyHfii?illacb^qebop%02)05&^ka`liib`q3X?illacb^qebo?biqpZyyNFAy604y
@JfpqyKyBp`loqJfpqqlPbkqfkbi>ovkf^@ilrap_ob^h%05+0)01+1&^qqebjllktbiikb^oqebLo^`ibQobbyyNFAy605y

QJfpqyKyPbkqfkbi>ovkf^@ilrap_ob^h%05+0)01+1&yyNFAy605y
QQebBk`e^kqbaDi^abyKyPbkqfkbi>ovkf^@ilrap_ob^h%05+0)01+1&yyNFAy604y
>Qbiao^ppfiyKyPbkqfkbi>ovkf^@ilrap_ob^h%05+0)01+1&yyNFAy61-y

@Qb^oplcqebJllkyKy?ofkdMofbpqbpp>$jllo^eboXPfisbovPmfkkbobqpZ)tef`e^obaolmmba_vI^avP^qeo^e^q%14)/3&)%1.+3)/2+/&^ka%06)/2&yyNFAy/2.5y

QQrjlopyKyObiif^kDobbkpmvob%05+1)/.+5&yyWyA^ok^pprpyyNFAy6/0y
>ObqrokqlAbk^i^kyKyObiif^kDobbkpmvob%05+1)/.+5&yyWyA^ok^pprpyyNFAy/165y
QQb^oplcqebJllkyKyMofbpqbpp>$jllo^%03+1)53&yyWyA^ok^pprpyyNFAy/2.5y
>P^qeo^e$pP^`ofcf`byKyMofbpqbpp>$jllo^%03+1)53&yyWyA^ok^pprpyyNFAy/2/-y
@P^qeo^e$pP^`ofcf`byKyMi^`bI^avP^qeo^e$ppfisbovpmfkkbobqp^qqebclrkq^fkfkpfabqebqbjmib%06)53+2&yyRy5.22yyNFAy/2/-y
QP^qeo^e$pP^`ofcf`byKyMofbpqbpp>$jllo^%03+1)53&yyWyA^ok^pprpyyNFAy/2/-y
QBi^k^of^y@yT^oofloyyKyBi^k^of^%24+2)02&yyLyyWyA^ok^pprpyyNFAy.351y
>QebPe^ablcBiro^y@yT^oofloyyKyBi^k^of^%24+2)02&yyWyA^ok^pprpyyNFAy.353y
>SloirpSfibellcy@yT^oofloyyKyBi^k^of^%24+2)02&yyWyA^ok^pprpyyNFAy.350y

EAli^k^^oyRy3615yyNFAy602y
QRop^iqebJ^riboyKy>qeofa^p?b^oj^kqib%22+6)24+0&yyNFAy153y
Q@oltklcqebB^oqe%M^oq2&yKy@lofqeo^pJllko^db%23+/)3.+4&yyNFAy4050y
>@oltklcqebB^oqe%M^oq3&yKy@lofqeo^pJllko^db%23+/)3.+4&yyNFAy602y
>Q^jfkdqeb?b^pq%M^oq.&yKyA^w^i^o%23+4)26+2&yy@yErkqboyyNFAy3-30y
@Q^jfkdqeb?b^pq%M^oq.&y@yErkqboyyKyRpbqebXQ^jfkdOlaZqlq^jb^Tb_tllaIrohbo^olrka%3-)23&yyRy.26/.yyNFAy3-30y
QQ^jfkdqeb?b^pq%M^oq.&yKyA^w^i^o%23+4)26+2&yy@yErkqboyyNFAy3-30y
>Q^jfkdqeb?b^pq%M^oq/&yKyA^w^i^o%23+4)26+2&yy@yErkqboyyNFAy3.-.y
@Q^jfkdqeb?b^pq%M^oq/&y@yErkqboyyKyRpbqebXQ^jfkdOlaZqlq^jb^Kfdeqp^_boPq^ihbo^olrka%21)4/&yyRy.26//yyNFAy3.-.y
QQ^jfkdqeb?b^pq%M^oq/&yKyA^w^i^o%23+4)26+2&yy@yErkqboyyNFAy3.-.y
>Q^jfkdqeb?b^pq%M^oq0&yKyA^w^i^o%23+4)26+2&yy@yErkqboyyNFAy3.-/y
@Q^jfkdqeb?b^pq%M^oq0&y@yErkqboyyKyRpbqebXQ^jfkdOlaZqlq^jb^PqofdfaP`obb`ebo^olrka%10)35&yyRy.26/0yyNFAy3.-/y
QQ^jfkdqeb?b^pq%M^oq0&yKyA^w^i^o%23+4)26+2&yy@yErkqboyyNFAy3.-/y

QObqrokqlAbk^i^kyKyAbk^i^k%3-+6)35+2&yyNFAy/165y
>L^hbkp`ltiyKyAbk^i^k%3-+6)35+2&yyNFAy/166y
QQebDiltfkdCorfqyKyAbk^i^k%3-+6)35+2&yyNFAy60-y
QQebPefjjbofkdColkayKyAbk^i^k%3-+6)35+2&yyNFAy60.y
>QebJlpp*qtfkbaEb^oqyKyQebfqbjXJlpp*qtfkbaEb^oqZpq^oqpnrbpq*aolmmba_v?i^`hjlppqebCbqfail`^qba_bqtbbk%1/+4)03+5&^ka%1/+2)/3&yyLyyRy6/4yyNFAy6/4y
QQebJlpp*qtfkbaEb^oqyKyAbk^i^k%3-+6)35+2&yyLyyNFAy6/4y

@SloirpSfibellcy@yT^oofloyyKyDlqlqebbkqo^k`b%16)26&^kahfiiSloirpSfibellc%14+0)30+3&^ka`liib`qefpelokyyNFAy.350y
@L^hbkp`ltiyKyHfiiL^hbkp`lti%20)42&^ka`liib`qXD^od^kqr^kQrjloZyyNFAy/166y
QL^hbkp`ltiyKyAbk^i^k%3-+6)35+2&yyNFAy/166y

OA^ok^pprpyKyOrkqlA^ok^pprp%/4)22&yyNFAy62/y
QQo^fkfkdqeb?b^pqy@yErkqboyyKyGl`^pqb%1-)6&yyWyA^ok^pprpyyNFAy3.-0y
Q@oltklcqebB^oqe%M^oq3&yKy>o`eAorfaC^kao^iPq^debij%01+5)5+4&yyWyA^ok^pprpyyNFAy602y
QQbiao^ppfiyKy>o`eAorfaC^kao^iPq^debij%01+5)5+4&yyWyA^ok^pprpyyNFAy61-y
QSloirpSfibellcy@yT^oofloyyKyBi^k^of^%24+2)02&yyWyA^ok^pprpyyNFAy.350y
>Dolsblcqeb>k`fbkqpyKy>o`eAorfaC^kao^iPq^debij%01+5)5+4&yyWyA^ok^pprpyyNFAy62/y

OOrq$qebo^kSfii^dbyKyOrkqeorqebmloq^itbpqlcqeb_^kh%0-+2)1.+1&yyWyA^ok^pprpyyOyKfdeqBicyyNFAy301.y
QKbpp^Pe^altplkdyKyKbpp^Pe^altplkd%23+0)6/+1&yyOyKfdeqBicyyNFAy3011y
>Qeb?lrkqvlcQbiao^ppfiyKyKbpp^Pe^altplkd%23+0)6/+1&yyOyKfdeqBicyyNFAy301.y
QQeb?lrkqvlcQbiao^ppfiyKySbpmovpqrp%25+1)61&yyOyKfdeqBicyyNFAy301.y
>Cifdeqql>r_boafkbyKySbpmovpqrp%25+1)61&yyOyKfdeqBicyyNFAy301/y

C>r_boafkbyKySbpmovpqrp%25+1)61&y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)

