DugisGuideViewer:RegisterGuide("Azuremyst Isle (1-12 Draenei)", "Bloodmyst Isle (12-20 Draenei)", "Alliance", "L", function()
return [[
AAA

>VlrProsfsbayKyJbdbilk%50)10+5&yyNFAy6/46y
QVlrProsfsbayKyMolbkfqrp%5-+2)12+6&yyNFAy6/46y
>ObmibkfpefkdqebEb^ifkd@ovpq^ipyKyMolbkfqrp%5-+2)12+6&yyNFAy6/5-yyOyAo^bkbfy
>Sli^qfibJrq^qflkpyKy?lq^kfpqQ^bofu%46+/)13+2&yyNFAy.-0-/y

@Sli^qfibJrq^qflkpyKyHfii5Sli^qfibJrq^qflkp^olrka%45)10&clrka^olrkaqeb`ovpq^iptef`eproolrka>jjbkS^ibyyNFAy.-0-/y
@ObmibkfpefkdqebEb^ifkd@ovpq^ipyKy@liib`q5XSf^iplcJlqe?illaZtef`e^obaolmmbacoljqebJlqepproolrkafkd>jjbkS^ibil`^qba^olrka%45)1/&yyNFAy6/5-yyOyAo^bkbfy

QSli^qfibJrq^qflkpyKy?lq^kfpqQ^bofu%46+/)13+2&yyNFAy.-0-/y
>Te^qJrpq?bAlkb+++yKy?lq^kfpqQ^bofu%46+/)13+2&yyNFAy6/60y
>?lq^kf`^iIbdtlohyKy>mmobkqf`bSfpe^bi%46+.)13+2&yyNFAy6466y
QObmibkfpefkdqebEb^ifkd@ovpq^ipyKyMolbkfqrp%5-+2)12+6&yyNFAy6/5-yyOyAo^bkbfy
>RodbkqAbifsbovyKyMolbkfqrp%5-+2)12+6&yyNFAy61-6y
QRodbkqAbifsbovyKyW^iarrk%5-)16+/&yyNFAy61-6y
>Obp`rbqebProsfslopyKyW^iarrk%5-)16+/&yyNFAy6/50y

>Pe^j^kQo^fkfkdy@yPe^j^kyyKyCfoj^ks^^o%46+1)16+/&yyNFAy61/.y
>J^dbQo^fkfkdy@yJ^dbyyKyS^i^^qr%46+3)15+5&yyNFAy6/6-y
>MofbpqQo^fkfkdy@yMofbpqyyKyW^iarrk%5-)16+/&yyNFAy6/6.y
>M^i^afkQo^fkfkdy@yM^i^afkyyKy>robilk%46+4)15+0&yyNFAy6/54y
>T^oofloQo^fkfkdy@yT^oofloyyKyHlob%46+3)16+1&yyNFAy6/56y

QPe^j^kQo^fkfkdy@yPe^j^kyyKyCfoj^ks^^o%46+1)16+/&yyNFAy61/.y
QJ^dbQo^fkfkdy@yJ^dbyyKyS^i^^qr%46+3)15+5&yyNFAy6/6-y
QMofbpqQo^fkfkdy@yMofbpqyyKyW^iarrk%5-)16+/&yyNFAy6/6.y
QM^i^afkQo^fkfkdy@yM^i^afkyyKy>robilk%46+4)15+0&yyNFAy6/54y
QT^oofloQo^fkfkdy@yT^oofloyyKyHlob%46+3)16+1&yyNFAy6/56y

>Pm^obM^oqpyKyQb`ekf`f^kWe^k^^%46+1)2.+0&yyNFAy60-2y
>Fkl`ri^qflkyKySfkaf`^qlo>ia^o%46+2)2.+3&yyNFAy60-0y

@Obp`rbqebProsfslopyKyCfka^Ao^bkbfProsfslo%40+0/)2-+55&^karpbvlropmbiiDfcqlcqebK^^orlkefjyyNFAy6/50y
@?lq^kf`^iIbdtlohyKy@liib`q0X@loormqbaCiltbopZaolmmba_v@loormqbaCiltboptef`eproolrkaqebcfbiap^q%40+3)16+4&yyNFAy6466y
@Te^qJrpq?bAlkb+++yKyD^qebo.-XI^peboP^jmibpZtef`e`^k_b`liib`qbacoljqebJrq^qbaOllqI^peboptef`eproolrkaqebcfbiap^olrka%40)16&yyNFAy6/60y

Q?lq^kf`^iIbdtlohyKy>mmobkqf`bSfpe^bi%46+.)13+2&yyNFAy6466y
QTe^qJrpq?bAlkb+++yKy?lq^kfpqQ^bofu%46+/)13+2&yyNFAy6/60y
>Eb^ifkdqebI^hbyKy?lq^kfpqQ^bofu%46+/)13+2&yyNFAy6/61y
QObp`rbqebProsfslopyKyW^iarrk%5-)16+/&yyNFAy6/50y

@Eb^ifkdqebI^hbyKyCfkaqeb@ovpq^iil`^qbafkqeb`bkqbolcqebi^hb^olrka%44)25&^karpbqebXKbrqo^ifwfkd>dbkqZrkqfinrbpqq^phfp`ljmibqbyyRy//622yyNFAy6/61y
@Fkl`ri^qflkyKyQo^sbiql%46)26&tebobvlrtfiicfkaqebkbbabaKbpqibtllaLtihfk+RpbqebXFkl`ri^qfkd@ovpq^iZlkqebklk*^ddolJllkhfkyyRy//63/yyNFAy60-0y
@Pm^obM^oqpyKyCfkaqebXBjfqqboPm^obM^oqpZqeolrde^`^sblkKbpqibTllaEfiip^olrka%52)32&yyNFAy60-2y

E>jjbkS^ibyRy3615yyNFAy60-6y
QEb^ifkdqebI^hbyKy?lq^kfpqQ^bofu%46+/)13+2&yyNFAy6/61y
>@^iilcB^oqe%M^oq.&y@yPe^j^kyyKyCfoj^ks^^o%46+1)16+/&yyNFAy6116y
QPm^obM^oqpyKyQb`ekf`f^kWe^k^^%46+1)2.+0&yyNFAy60-2y
QFkl`ri^qflkyKySfkaf`^qlo>ia^o%46+2)2.+3&yyNFAy60-0y
>QebJfppfkdP`lrqyKySfkaf`^qlo>ia^o%46+2)2.+3&yyNFAy60-6y
Q@^iilcB^oqe%M^oq.&yKyPmfofqlcqebS^ib)kloqetbpqlcqeb@o^pePfqb%4.+1)06+0&yy@yPe^j^kyyNFAy6116y
>@^iilcB^oqe%M^oq/&yKyPmfofqlcqebS^ib%4.+1)06+0&yy@yPe^j^kyyNFAy612-y
@@^iilcB^oqe%M^oq/&yKyPi^v1ObpqibppBibjbkqplcB^oqe%4-)03&yy@yPe^j^kyyNFAy612-y
Q@^iilcB^oqe%M^oq/&yKyPmfofqlcqebS^ib%4.+1)06+0&yy@yPe^j^kyyNFAy612-y
>@^iilcB^oqe%M^oq0&yKyPmfofqlcqebS^ib%4.+1)06+0&yy@yPe^j^kyyNFAy612.y
Q@^iilcB^oqe%M^oq0&yKyCfoj^ks^^o%46+1)16+/&yy@yPe^j^kyyNFAy612.y

QQebJfppfkdP`lrqyKyQli^^k%4/)3-+5&yyNFAy60-6y
>Qeb?illaBisbpyKyQli^^k%4/)3-+5&yyNFAy.-0-0y
@Qeb?illaBisbpyKyHfii.-?illaBicP`lrqptef`e^ob`^jmba^olrka%36)3/&yyNFAy.-0-0y
QQeb?illaBisbpyKyQli^^k%4/)3-+5&yyNFAy.-0-0y
>?illaBicPmvyKyQli^^k%4/)3-+5&yyNFAy60..y
@?illaBicPmvyKyHfiiProsbvlo@^kaobpp)rmqebefiikb^oqebmfkh`ovpq^i%36+/-)32+4-&yyNFAy60..y
>?illaBicMi^kpyKyQebfqbjX?illaBicMi^kpZpq^oqpqebnrbpq*aolmpcoljProsbvlo@^kaobpp%36+/)32+4&yyNFAy6465yyRy/11.1y

Q?illaBicPmvyKySfkaf`^qlo>ia^o%46+2)2.+3&yyNFAy60..y
Q?illaBicMi^kpyKySfkaf`^qlo>ia^o%46+2)2.+3&yyNFAy6465y
>QebBjfqqboyKySfkaf`^qlo>ia^o%46+2)2.+3&yyNFAy60./y
QQebBjfqqboyKyQb`ekf`f^kWe^k^^%46+1)2.+0&yyNFAy60./y
>Qo^sbiql>wrobT^q`eyKyQb`ekf`f^kWe^k^^%46+1)2.+0&yyNFAy60.0y

>Tloacolj>wrobT^q`eyKyOrklrqlc>jjbkS^ibqlqebtbpq)>brk%31+4)21+.&yyNFAy60.1y
>ObaPk^mmbo*SbovQ^pqvyKyAfhqvkk^altk_vqebofsbo%3.+.)21+/&yyNFAy612/y
@ObaPk^mmbo*SbovQ^pqvyNFAy612/yyRy/0321yyKyPtfj^olrkaqebkb^o_vOfsbo_bqtbbk%3.)31&^ka%3.)10&cfkafkd^kv`^jmplcXObaPk^mmboZ^karpbqebXAo^bkbfCfpefkdKbqZy
QObaPk^mmbo*SbovQ^pqvyKyAfhqvkk^%3.+.)21+/&yyNFAy612/y
>Cfka>`qblkyKyAfhqvkk^%3.+.)21+/&yyNFAy6120y

QCfka>`qblkyKy>`qblk%16+5)2.+6&yyNFAy6120y
>QebDob^qJllkdo^wbErkq%M^oq.&yKy>`qblk%16+5)2.+6&yyNFAy6121y
>Jbaf`fk^iMromlpbyKy>k`elofqbC^qbbj^%15+2)2.+5&yyNFAy6130y
QQo^sbiql>wrobT^q`eyKyQb`ekf`f^kAvsrrk%15+4)2-+0&yyNFAy60.0y
QTloacolj>wrobT^q`eyKy@^obdfsbo@ebii^k%15+1)16+/&yyNFAy60.1y
e>wrobT^q`eyKyPbq>wrobT^q`e^pvlrokbteljbtfqe@^obdfsbo@ebii^k%15+2)16+/&yyNFAy62./y

>@llhfb$pGrj_lDrj_lyKy@llhfbJ`Tb^hp^r`b%13+4)4-+2&yyNFAy62./y
>>Pj^iiPq^oqyKy>ajfo^iLabpvrp%14)4-+/&yyNFAy62-3y
@@llhfb$pGrj_lDrj_lyKyHfiiqebPhfqqbofkd@o^tiboptef`eproolrkaqebplrqebok`l^pqifkb_bqtbbk%12)41&^ka%22)36&rkqfivlr$sb`liib`qba3XPhfqqbofkd@o^tiboJb^qZyyNFAy62./y
@>Pj^iiPq^oqyKyOb`lsboqebXK^rqf`^i@ljm^ppZ%26+2)34+3&il`^qbalkqlmlc^`ebpq^kaqebXK^rqf`^iJ^mZ%25+3)33+2&kb^o_v^`^jmcfob^qqebdl_ifk`^jmpyyNFAy62-3y

Q>Pj^iiPq^oqyKy>ajfo^iLabpvrp%14)4-+/&yyNFAy62-3y
>F$sbDlq^Mi^kqyKy>ajfo^iLabpvrp%14)4-+/&yyNFAy620-y
Q@llhfb$pGrj_lDrj_lyKy@llhfbJ`Tb^hp^r`b%13+4)4-+2&yyNFAy62./y
>Ob`i^fjfkdqebOrfkpyKyMofbpqbppHvibbkFi$afk^ob%14+.)4-+0&yyNFAy62.0y
>Mob`flrp^kaCo^dfibQefkdpKbbaPmb`f^iE^kaifkdyKy>o`e^blildfpq>a^j^kqFolkeb^oq%14+/)4-+.&yyNFAy62/0y

@F$sbDlq^Mi^kqyKyD^qeboqebXMfibplcIb^sbpZtef`eproolrkaqebirj_bo`^jmpqlqebb^pq%2.)31&^katbpq%10)32&lcLabpvrp$I^kafkd^ka`liib`q^XEliiltbaLrqQobbZ^q%16)30&yyNFAy620-y
@QebDob^qJllkdo^wbErkq%M^oq.&yKy@liib`q3Jllkdo^wbPq^dQbkaboilfkptef`e`^k_bobqofbsba_vhfiifkdqebJllkdo^wbPq^dplo?r`hpqlqebPlrqelc>wrobT^q`e^olrka%20)3-&yyNFAy6121y
@Jbaf`fk^iMromlpbyKy@liib`q5XOllqQo^mmboSfkbpZtef`e`^k_b`liib`qbacoljqebOllqQo^mmboptef`eproolrkaqeb^ob^^olrka%20)3-&yyNFAy6130y
@Ob`i^fjfkdqebOrfkpyKyHfii2To^qep`^ibJvojfalkp)2To^qep`^ibK^d^^ka2To^qep`^ibPfobkptef`eproolrkaqeborfkp^olrka%0-)46&yyNFAy62.0y
@Mob`flrp^kaCo^dfibQefkdpKbbaPmb`f^iE^kaifkdyKy@liib`q5X>k`fbkqObif`pZclrka^olrkaqebK^d^@^jmp^q%0-)46&yyNFAy62/0y

>Orkb@lsbobaQ^_ibqyRy/0426yyKyHfiijlobk^d^p%0-)46&fcvlralk$qe^sbqefpfqbjvbqyyNFAy62.1y

QF$sbDlq^Mi^kqyKy>ajfo^iLabpvrp%14)4-+/&yyNFAy620-y
>Qobb$p@ljm^kvyKy>ajfo^iLabpvrp%14)4-+/&yyNFAy620.y
QOrkb@lsbobaQ^_ibqyKyMofbpqbppHvibbkFi$afk^ob%14+.)4-+0&yyNFAy62.1y
>T^oiloaPofpp$qfwyKyMofbpqbppHvibbkFi$afk^ob%14+.)4-+0&yyNFAy62.2y
QOb`i^fjfkdqebOrfkpyKyMofbpqbppHvibbkFi$afk^ob%14+.)4-+0&yyNFAy62.0y
QMob`flrp^kaCo^dfibQefkdpKbbaPmb`f^iE^kaifkdyKy>o`e^blildfpq>a^j^kqFolkeb^oq%14+/)4-+.&yyNFAy62/0y

QJbaf`fk^iMromlpbyKy>k`elofqbC^qbbj^%15+2)2.+5&yyNFAy6130y
>>k>iqbok^qfsb>iqbok^qfsbyKyA^ba^i%15+1)2.+2&yyNFAy6140y
QQebDob^qJllkdo^wbErkq%M^oq.&yKy>`qblk%16+5)2.+6&yyNFAy6121y
>QebDob^qJllkdo^wbErkq%M^oq/&yKy>`qblk%16+5)2.+6&yyNFAy.-0/1y

HFkcb`qbaKfdeqpq^ihboOrkqpyKyKloqetbpqlc>wrobT^q`e^olrka%12)1-&)illhfkdcloXC^fkqivDiltfkd@ovpq^iZyyIy/0345yyNFAy6122y
>Pqo^kdbCfkafkdpyRy/0345yyKyQebfqbjXC^fkqivDiltfkd@ovpq^iZpq^oqpnrbpq*aolmmba_vFkcb`qbaKfdeqpq^ihboOrkq%12)1-&yyNFAy6122y

>QebJfppfkdCfpeboj^kyKyArisf%15+6)2.+.&yyNFAy.-1/5y
>EbimQ^s^o^y@yMofbpqyyKyDrs^k%15+/)16+1&yyNFAy6253y
>Ib^okfkdqebI^kdr^dbyKy@ovmqldo^mebo>roobk%16+1)2.+.&yyNFAy6205y
@Ib^okfkdqebI^kdr^dbyKyOb^aqeb_llhXPqfiimfkbCro_lidI^kdr^dbMofjboZfkvlrofksbkqlovyyNFAy6205yyRy/05.5y
QIb^okfkdqebI^kdr^dbyKyQlqbjlc>hfa^%16+2)2-&yyNFAy6205y
>Qlqbjlc@llyKyQlqbjlc>hfa^%16+2)2-&yyNFAy6206y
QPqo^kdbCfkafkdpyKyBu^o`eJbkbi^lrp%14+/)2-+3&yyNFAy6122y
>Kfdeqpq^ihbo@ib^kRm)Fpib/+++yKyBu^o`eJbkbi^lrp%14+/)2-+3&yyNFAy6123y

@QebDob^qJllkdo^wbErkq%M^oq/&yKy@liib`q3XJllkdo^wb?r`hEfabpZtef`e`^k_bobqofbsba_vhfiifkd^kvlcqebJllkdo^wb?r`hpclrkaqlqebKloqelc>wrobT^q`e^olrka%2.)01&yyNFAy.-0/1y
@Kfdeqpq^ihbo@ib^kRm)Fpib/+++yKyHfii5Fkcb`qbaKfdeqpq^ihboOrkqptef`e`^k_bclrkafkqeb^ob^qlqebKloqelc>wrobT^q`e^olrka%16)04&yyNFAy6123y

QQlqbjlc@llyKyQlqbjlc@ll%22+/)1.+4&+Lkqlmqebqeb`ifccpkloqelc>wrobT^q`eyyNFAy6206y
>QlqbjlcQfhqfyKyQlqbjlc@ll%22+/)1.+4&yyNFAy621-y
@EbimQ^s^o^yKyGrjmlcqeb`ifccqlqebplrqe^kaeb^iQ^s^o^%22+6)14+6&yy@yMofbpqyyNFAy6253y
QQlqbjlcQfhqfyKyQlqbjlcQfhqf%31+1)06+5&yyNFAy621-y
>QlqbjlcVloyKyQlqbjlcQfhqf%31+1)06+5&yyNFAy621.y
QQlqbjlcVloyKyQlqbjlcVlo%30+.)34+4&yyNFAy621.y
>QlqbjlcS^ohyKyQlqbjlcVlo%30+.)34+4&yyNFAy621/y
QQlqbjlcS^ohyKyCliiltqebKM@)fcvlrilpbefjqebnrbpqbkap^qQlqbjlcS^oh%/5+/)3/+1&yyNFAy621/y
>QebMolmeb`vlc>hfa^yKyQlqbjlcS^oh%/5+/)3/+1&yyNFAy6211y

@QebMolmeb`vlc>hfa^yKyHfiiqebcro_ild^olrkaqeb`^jmql`liib`qqebhbvpqllmbkqeb`^dbpqlcobb5Pqfiimfkb@^mqfsbpcolj`^dbpclrkafk?ofpqibifj_Sfii^db%/4)33&yyNFAy6211y

@T^oiloaPofpp$qfwyKyPlrqetbpqfkqeb`^sb^qQfabp$Eliilt)lkqebiltboibsbi%/0+5)41+5&+Qebob$p^e^kavifqqibelibvlr`^kaolmaltkqldbqkb^oefj)qebkvlralk$qe^sbqlcfdeqvlrot^vfk^kalrqyyNFAy62.2y

@Qobb$p@ljm^kvyKyRpbqebXQobbAfpdrfpbHfqZkb^oqebci^d^qQo^fqlo$p@lsblkPfisbojvpqFpib%.5+1/)51+00&^kat^fqcloqeb`lksbop^qflkqlcfkfpeyyRy/046/yyNFAy620.y
QQebJfppfkdCfpeboj^kyKy@ltibk%.3+.)60+3&yyNFAy.-1/5y
>>iiQe^qObj^fkpyKy@ltibk%.3+.)60+3&yyNFAy62/4y
@>iiQe^qObj^fkpyKyQlcfkaqebXObj^fkplc@ltibk$pC^jfivZvlrjrpqhfiiqeblti_b^pqtef`eproolrkaqebfpi^kail`^qba^olrka%.0)54&yyNFAy62/4y
Q>iiQe^qObj^fkpyKy@ltibk%.3+.)60+3&yyNFAy62/4y

E>wrobT^q`eyKyRpbvlroEb^oqepqlkbqldl_^`hql>wrobT^q`eyyRy3615yyNFAy6226y
@>k>iqbok^qfsb>iqbok^qfsbyKyQebX>wrobPk^mao^dlk?ri_pZ^obil`^qba^olrkaqeblrqphfoqplc>wrobt^q`e)`liib`qqebpb^pvlralqeberkqfkdnrbpqp+>dlla^ob^qlcfkaqebjfp^olrka%13)24&yyNFAy6140y
QEbimQ^s^o^y@yMofbpqyyKyDrs^k%15+/)16+1&yyNFAy6253y
Q>k>iqbok^qfsb>iqbok^qfsbyKyA^ba^i%15+1)2.+2&yyNFAy6140y
QQebMolmeb`vlc>hfa^yKy>ordlllcqebPqfiimfkb%16+1)2.+.&yyNFAy6211y
>PqfiimfkbEliayKy>ordlllcqebPqfiimfkb%16+1)2.+.&yyNFAy6226y
QQebDob^qJllkdo^wbErkq%M^oq/&yKy>`qblk%16+5)2.+6&yyNFAy.-0/1y
QKfdeqpq^ihbo@ib^kRm)Fpib/+++yKyBu^o`eJbkbi^lrp%14+/)2-+3&yyNFAy6123y

QQobb$p@ljm^kvyKy>ajfo^iLabpvrp%14)4-+/&yyNFAy620.y
>PeltDkljbo`vyKy>ajfo^iLabpvrp%14)4-+/&yyNFAy6204y
QT^oiloaPofpp$qfwyKyMofbpqbppHvibbkFi$afk^ob%14+.)4-+0&yyNFAy62.2y
@PeltDkljbo`vyKyQ^ihqlBkdfkbboPm^ohLsbodofkat^kabofkd^olrkaqeb_b^`e%15)4/&yyNFAy6204y
QPeltDkljbo`vyKy>ajfo^iLabpvrp%14)4-+/&yyNFAy6204y
>AbifsboQebjColjBsfi+++yKy>ajfo^iLabpvrp%14)4-+/&yyNFAy63-/y

QAbifsboQebjColjBsfi+++yKyBu^o`eJbkbi^lrp%14+/)2-+3&yyNFAy63-/y
>@ljfkdlc>dbyKyBu^o`eJbkbi^lrp%14+/)2-+3&)Vlrjrpq_bIbsbi.-ql^``bmqqefpyyNFAy63/0y
>PqobkdqelcLkby@yT^oofloyyKyOr^a^%16+4)2.+.&yyNFAy625/y
>@^iilcCfob%M^oq.&yKyQrirrk%15+.)2-+2&yy@yPe^j^kyyNFAy6131y
>@lkqoliy@yJ^dbyyKyPbjfa%16+2)2-+/&yyNFAy6262y
>PbbhErkqobppHbii^Kfdeq_lty@yErkqboyyKy>`qblk%16+5)2.+6&yyNFAy6424y
QPbbhErkqobppHbii^Kfdeq_lty@yErkqboyyKyErkqobppHbii^Kfdeq_lt%/1+/)21+/&yyNFAy6424y
>Q^jfkdqeb?b^pq%M^oq.&y@yErkqboyyKyErkqobppHbii^Kfdeq_lt%/1+/)21+/&yyNFAy626.y
@Q^jfkdqeb?b^pq%M^oq.&y@yErkqboyyRy/0563yyKyQ^jb^?^o_ba@o^tibo%//+2)4/+4&yyNFAy626.y
QQ^jfkdqeb?b^pq%M^oq.&y@yErkqboyyKyErkqobppHbii^Kfdeq_lt%/1+/)21+/&yyNFAy626.y
>Q^jfkdqeb?b^pq%M^oq/&y@yErkqboyyKyErkqobppHbii^Kfdeq_lt%/1+/)21+/&yyNFAy626/y
@Q^jfkdqeb?b^pq%M^oq/&y@yErkqboyyRy/0564yyKyQ^jb^Dob^qboQfj_bopqofabo%04+3)02&yyNFAy626/y
QQ^jfkdqeb?b^pq%M^oq/&y@yErkqboyyKyErkqobppHbii^Kfdeq_lt%/1+/)21+/&yyNFAy626/y
>Q^jfkdqeb?b^pq%M^oq0&y@yErkqboyyKyErkqobppHbii^Kfdeq_lt%/1+/)21+/&yyNFAy6260y
@Q^jfkdqeb?b^pq%M^oq0&y@yErkqboyyRy/0565yyKyQ^jb^Kfdeqpq^ihbo%04+3)02&yyNFAy6260y
QQ^jfkdqeb?b^pq%M^oq0&y@yErkqboyyKyErkqobppHbii^Kfdeq_lt%/1+/)21+/&yyNFAy6260y
>?b^pqQo^fkfkdy@yErkqboyyKyErkqobppHbii^Kfdeq_lt%/1+/)21+/&yyNFAy6342y

OQebBula^oyKyDlqlQebBula^o%00+2)10+0&yyNFAy63/2y
Q?b^pqQo^fkfkdy@yErkqboyyWyQebBula^oyyKyD^k^^o%11)53+4&yyNFAy6342y
Q@ljfkdlc>dbyWyQebBula^oyyKyQlo^iifrpqebM^`hE^kaibo%5.+2)2/&yyNFAy63/0y
>Bibhhp>obPboflrp?rpfkbppyWyQebBula^oyyKyQlo^iifrpqebM^`hE^kaibo%5.+2)2/&yyNFAy63/2y

OPqfiimfkbEliayKyCliiltqebol^akloqelc>wrobT^q`e%12+5)/1+5&yyNFAy623-y
>?b^pqplcqeb>ml`^ivmpbyKyJlloal%11+5)/0+5&yyNFAy623-y
>Jroil`p+++TevEbob<TevKlt<yKyDroc%11+4)/0+2&yyNFAy623/y
QPqfiimfkbEliayKyEfde@efbcPqfiimfkb%13+4)/-+5&yyNFAy6226y

@PqobkdqelcLkby@yT^oofloyyKyCfkaqeb`^db^q%20)6&^karpbqebXO^s^dbo@^dbHbvZyyRy/06/2yyNFAy625/y
@?b^pqplcqeb>ml`^ivmpbyKyHfiiqebO^s^dboPmb`fjbkptef`e^obclrkaqlqebb^pq^olrka%21).5&)rkqfivlre^sb`liib`qba5XO^s^dboEfabpZyyNFAy623-y
Q@^iilcCfob%M^oq.&y@yPe^j^kyyKyQbjmbo%26+2).4+.&yyNFAy6131y
>@^iilcCfob%M^oq/&y@yPe^j^kyyKyQbjmbo%26+2).4+.&yyNFAy6132y

Q?b^pqplcqeb>ml`^ivmpbyKyJlloal%11+5)/0+5&yyNFAy623-y
>@efbcq^fkLljllollyKyPqfiimfkbqebVlrkdbo%13+5)/.+.&yyNFAy6240y
>Pb^o`ePqfiimfkbEliayKyEfde@efbcPqfiimfkb%13+4)/-+5&yyNFAy6232y

@@efbcq^fkLljllollyKyBkqboqeb`^sb^qpqfiimfkbelia^kahfii6lcqeb@o^wbaTfiahfktfqefk^ptbii^p@efbcq^fkLljllolltel`^k_bclrka^q%14).2&fkpfabqeb`^sbyyNFAy6240y
QPb^o`ePqfiimfkbEliayKyDlqlqeb`^sbbkqo^k`b^q%12)/-&^kacfkaqeb?illa@ovpq^iabbmfkpfabqebelia%2-+2)..+4&yyNFAy6232y
>?illa@ovpq^ipyKy?illa@ovpq^i%2-+2)..+3&yyNFAy6233y
Q?illa@ovpq^ipyKyEfde@efbcPqfiimfkb%13+4)/-+5&yyNFAy6233y
Q@efbcq^fkLljllollyKyPqfiimfkbqebVlrkdbo%13+5)/.+.&yyNFAy6240y
>QebHrohbkfpIrohfk$yKyHrowqebObsbi^qlo%13+6)//+/&yyNFAy624-y
@QebHrohbkfpIrohfk$yKyQo^sbiqlqeb_^`hlcqeb@^sb^qPqfiimfkbEfabtebobvlrclrkaqeb?illa@ovpq^i%2-)./&^kahfiiHrohbkqebIrohbkql`liib`qefpefabyyNFAy624-y
H@o^wbaTfiahfky@yPe^j^kyyKy>ka`liib`qXOfqr^iQlo`eZ%15)./&yyIy/0400yyNFAy6132y
QQebHrohbkfpIrohfk$yKyHrowqebObsbi^qlo%13+6)//+/&yyNFAy624-y
>QebHrohbk$pEfabyKyHrowqebObsbi^qlo%13+6)//+/&yyNFAy624.y
QQebHrohbk$pEfabyKyJlloal%11+5)/0+5&yyNFAy624.y
Q@^iilcCfob%M^oq/&y@yPe^j^kyyKyQbjmbo%26+2).4+.&yyNFAy6132y
>@^iilcCfob%M^oq0&y@yPe^j^kyyKyQbjmbo%26+2).4+.&yyNFAy6134y

@Jroil`p+++TevEbob<TevKlt<yKy@liib`qqebXPqfiimfkbDo^fkZcolj^kvlcqebjroil`jl_ptef`eproolrkaqebTbpqbok`l^pqifkb^q^_lrq%00).2&yyNFAy623/y
@@lkqoliyKyHbbmhfiifkdjroil`prkqfi^Nrbi$alobfJ^dbto^fqe^mmb^opyy@yJ^dbyyNFAy6262y
HJrodrodri^yIy/052-yyKyHfiiJrodrodri^il`^qba_bqtbbk%00)/3&^ka%01)./&qlillqXDroc$pAfdkfqvZyyNFAy6231y

QJroil`p+++TevEbob<TevKlt<yKyDroc%11+4)/0+2&yyNFAy623/y
>Droc$pAfdkfqvyRy/052-yyKyRpbqebfqbjXDroc$pAfdkfqvZql_bdfknrbpqyyNFAy6231y
QDroc$pAfdkfqvyKyDroc%11+4)/0+2&yyNFAy6231y
>T^okVlroMblmibyKyEfde@efbcPqfiimfkb%13+4)/-+5&yyNFAy63//y

@@^iilcCfob%M^oq0&yKyEb^aaltkqlPfisbojvpqFpib)cfkaqebTf`hboj^kBccfdv%..)5/&)vlr`^kcfkaqebqlo`efkpfabqebXCfobmollcP^q`ebiZmolsfabayy@yPe^j^kyyNFAy6134y
RLo_lcObqrokfkdy@yPe^j^kyyKyRpbLo_lcObqrokfkdyyRy/1002y
Q@^iilcCfob%M^oq0&y@yPe^j^kyyKyQbjmbo%26+2).4+.&yyNFAy6134y
>@^iilcCfob%M^oq1&y@yPe^j^kyyKyQbjmbo%26+2).4+.&yyNFAy6135y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
