DugisGuideViewer:RegisterGuide("Dun Morogh (1-12 Dwarf & Gnome)", "Darkshore (12-17)", "Alliance", "L", function()
return [[
AAA

>At^osbkLrqcfqqbopyKyPqbkPqlrq^oj%/6+6)4.+0&yyNFAy.46y
@At^osbkLrqcfqqbopyKy@liib`q5mfb`bplcXQlrdeTlicJb^qZaolmmba_vo^ddbatlisbp^olrka%0-)40&yyNFAy.46y
QAt^osbkLrqcfqqbopyKyPqbkPqlrq^oj%/6+6)4.+0&yyNFAy.46y

>Bk`ovmqbaOrkby@yOldrbyyOyAt^ocyyKyPqbkPqlrq^oj%/6+6)4.+0&yyNFAy0.-6y
>Bq`ebaOrkby@yErkqboyyOyAt^ocyyKyPqbkPqlrq^oj%/6+6)4.+0&yyNFAy0.-5y
>E^iiltbaOrkby@yMofbpqyyOyAt^ocyyKyPqbkPqlrq^oj%/6+6)4.+0&yyNFAy0..-y
>PfjmibOrkby@yT^oofloyyOyAt^ocyyKyPqbkPqlrq^oj%/6+6)4.+0&yyNFAy0.-3y
>@lkpb`o^qbaOrkby@yM^i^afkyyOyAt^ocyyKyPqbkPqlrq^oj%/6+6)4.+0&yyNFAy0.-4y

>Q^fkqbaJbjlo^karjy@yT^oil`hyyOyDkljbyyKyPqbkPqlrq^oj%/6+6)4.+0&yyNFAy0..2y
>Divmef`Jbjlo^karjy@yJ^dbyyOyDkljbyyKyPqbkPqlrq^oj%/6+6)4.+0&yyNFAy0..1y
>Bk`ovmqbaJbjlo^karjy@yOldrbyyOyDkljbyyKyPqbkPqlrq^oj%/6+6)4.+0&yyNFAy0..0y
>PfjmibJbjlo^karjy@yT^oofloyyOyDkljbyyKyPqbkPqlrq^oj%/6+6)4.+0&yyNFAy0../y

>@liaofadbS^iibvJ^fiAbifsbov%M^oq.&yKyPqbkPqlrq^oj%/6+6)4.+0&yyNFAy/00y
>>KbtQeob^qyKy?^ifoColpqe^jjbo%/6+4)4.+0&yyNFAy.4-y
@>KbtQeob^qyKyHfii3Ol`hg^tQolddp%0.)41&^ka3?roivOl`hg^tQolddp%0-)41&yyNFAy.4-y
Q>KbtQeob^qyKy?^ifoColpqe^jjbo%/6+4)4.+0&yyNFAy.4-y

QBk`ovmqbaOrkby@yOldrbyyOyAt^ocyyKyPlijE^odofk%/5+1)35+2&yyNFAy0.-6y
QBq`ebaOrkby@yErkqboyyOyAt^ocyyKyQelod^pDofjplk%/6+.)34+2&yyNFAy0.-5y
QE^iiltbaOrkby@yMofbpqyyOyAt^ocyyKy?o^kpql`hHe^iabo%/5+3)33+1&yyNFAy0..-y
QPfjmibOrkby@yT^oofloyyOyAt^ocyyKyQeo^kHeloj^k%/5+5)34+0&yyNFAy0.-3y
Q@lkpb`o^qbaOrkby@yM^i^afkyyOyAt^ocyyKy?oljlpDorjjkbo%/5+5)35+0&yyNFAy0.-4y

QQ^fkqbaJbjlo^karjy@yT^oil`hyyOyDkljbyyKy>i^j^oDofjj%/5+4)33+/&yyNFAy0..2y
QDivmef`Jbjlo^karjy@yJ^dbyyOyDkljbyyKyJ^oovhKroof_fq%/5+4)33+1&yyNFAy0..1y
QBk`ovmqbaJbjlo^karjy@yOldrbyyOyDkljbyyKyPlijE^odofk%/5+1)35+2&yyNFAy0..0y
QPfjmibJbjlo^karjy@yT^oofloyyOyDkljbyyKyQeo^kHeloj^k%/5+5)34+0&yyNFAy0../y

>>Obcrdbb$pNr^ka^ovyKyCbifuTefkaib_liq%/5+2)34+4&yyNFAy003.y

Q@liaofadbS^iibvJ^fiAbifsbov%M^oq.&yKyQ^ifkHbbkbvb%//+3)4.+1&yyNFAy/00y
>@liaofadbS^iibvJ^fiAbifsbov%M^oq/&yKyQ^ifkHbbkbvb%//+3)4.+1&yyNFAy/01y
>Qeb?l^oErkqboyKyQ^ifkHbbkbvb%//+3)4.+1&yyNFAy.50y
@Qeb?l^oErkqboyKyHfii./Pj^ii@o^d?l^op^olrka%/.)4/&yyNFAy.50y
QQeb?l^oErkqboyKyQ^ifkHbbkbvb%//+3)4.+1&yyNFAy.50y

Q@liaofadbS^iibvJ^fiAbifsbov%M^oq/&yKyDobifkTefqb_b^oa%/2+.)42+5&yyNFAy/01y
>QebQolii@^sbyKyDobifkTefqb_b^oa%/2+.)42+5&yyNFAy.5/y
>P`^iafkdJlok_obtAbifsbovyKyKlofMofabaofcq%/2)42+6&yyNFAy0031y
QP`^iafkdJlok_obtAbifsbovyKyArok^kCro`rqqbo%/5+5)33+1&yyNFAy0031y
>?ofkd?^`hqebJrdyKyArok^kCro`rqqbo%/5+5)33+1&yyNFAy0032y

Q?ofkd?^`hqebJrdyKyKlofMofabaofcq%/2)42+6&yyNFAy0032y
@>Obcrdbb$pNr^ka^ovyKy>qqebqolii`^jmpqlqebplrqetbpq+?r`hbq%/3+0)46+0&)@ebpq%//+5)46+6&)?lu%/-+6)43+.&yyNFAy003.y
@QebQolii@^sbyKyHfii.1Colpqj^kbQoliiTebimp^olrka%/3)45&yyNFAy.5/y
QQebQolii@^sbyKyDobifkTefqb_b^oa%/2+.)42+5&yyNFAy.5/y
>QebPqlibkGlrok^iyKyDobifkTefqb_b^oa%/2+.)42+5&yyNFAy/.5y
@QebPqlibkGlrok^iyKyDlqlqeb`^sb^q%/3+4)46+3&+HfiiDofh$kfoqeb@lia%0-+2)5-+/&^kaobqofbsbXDobifkTefqb_b^oa$pGlrok^iZyyNFAy/.5y
QQebPqlibkGlrok^iyKyDobifkTefqb_b^oa%/2+.)42+5&yyNFAy/.5y
>Pbkfo$pL_pbos^qflkp%M^oq.&yKyDobifkTefqb_b^oa%/2+.)42+5&yyNFAy/5/y

Q>Obcrdbb$pNr^ka^ovyKyCbifuTefkaib_liq%/5+2)34+4&yyNFAy003.y
QPbkfo$pL_pbos^qflkp%M^oq.&yKyJlrkq^fkbboQe^ilp%00+2)4.+6&yyNFAy/5/y
>Pbkfo$pL_pbos^qflkp%M^oq/&yKyJlrkq^fkbboQe^ilp%00+2)4.+6&yyNFAy1/-y
>PrmmifbpqlQ^kklhyKyE^kapPmofkdpmol`hbq%00+5)4/+/&yyNFAy/.3-y
>FkC^slolcqebIfdeqy@yMofbpqyyKy?o^kpql`hHe^iabo%/5+3)33+1&yyNFAy23/3y

OHe^o^klpyKyEb^afkqlqeb`^sb^q%01)4.&^kacliiltqebol^aqlHe^o^klp%13+4)20+5&yyNFAy051y
QPbkfo$pL_pbos^qflkp%M^oq/&yKyPbkfoTefqb_b^oa%13+4)20+5&yyNFAy1/-y
>?bbo?^pqba?l^oOf_pyKyO^dk^oQerkabo_obt%13+5)2/+1&yyNFAy051y
QPrmmifbpqlQ^kklhyKyQ^kklhColpqe^jjbo%14+/)2/+/&yyNFAy/.3-y
eQerkabo_obtAfpqfiibovyKyQ^ihqlFkkhbbmbo?bij%14+1)2/+2&^kapbqQerkabo_obtAfpqfiibov^pvlrokbteljbyyNFAy1--y
>QllipcloPqbbidofiiyKyQe^obh?i^`hpqlkb%13)2.+4&yyNFAy1--y

QFkC^slolcqebIfdeqy@yMofbpqyyKyJ^u^k>ksli%14+0)2/+/&yyNFAy23/3y
>D^ojbkqplcqebIfdeqy@yMofbpqyyKyJ^u^k>ksli%14+0)2/+/&yyNFAy23/2y
@D^ojbkqplcqebIfdeqyKyCfkaJlrkq^fkbboAlic%12+5)21+3&^kaeb^iefptlrkaprpfkdIbppboEb^i%O^kh/&+>cqbot^oap)do^kqefjMltboTloa7Cloqfqrabyy@yMofbpqyyNFAy23/2y
QD^ojbkqplcqebIfdeqy@yMofbpqyyKyJ^u^k>ksli%14+0)2/+/&yyNFAy23/2y

QQllipcloPqbbidofiiyKy?biafkPqbbidofii%2-+1)16+.&yyNFAy1--y
>>jjlcloOrj_ibpelqyKyIlpiloOradb%2-+.)16+1&yyNFAy221.y
>QebDofwwibaAbkyKyMfilqPqlkbdb^o%16+3)15+2&yyNFAy0.0y
>Pql`hfkdGbqpqb^jyKyMfilq?biiltcfw%16+2)15+1&yyNFAy0.4y

@>jjlcloOrj_ibpelqyKyLmbkqeb`o^qb%11+.)23+6&^ka`liib`qXOrj_ibpelq$p>jjlZyyNFAy221.y
@QebDofwwibaAbkyKyDlql%1/)21&^kahfiiTbkafdlpqld^qebo5uXTbkafdlJ^kbpZyyNFAy0.0y
Q>jjlcloOrj_ibpelqyKyEbdk^oOrj_ibpelq%1-+4)32+.&yyNFAy221.y

O?obtk^iiSfii^dbyKyDlkloqetbpq)kb^oqebcolwbki^hb%0-+0)13+0&yyNFAy0.2y
>QebMbocb`qPqlrqyKyObglia?^oibv_obt%0-+/)12+4&yyNFAy0.2y
>?fqqboOfs^ipyKyJ^oibqe?^oibv_obt%0-+/)12+2&yyNFAy0.-y
@QebMbocb`qPqlrqyKyDlql%1-)10&^ka`liib`q3uXPefjjbotbbaZaolmmba_vColpqj^kbPbbo^kacoljqeb_^phbqpfkqeb^ob^yyNFAy0.2y

@Pql`hfkdGbqpqb^jyKyHfii?b^op^olrka%2-)2/&ql`liib`q1uX@erkhlc?l^oJb^qZ^ka/uXQef`h?b^oCroZyyNFAy0.4y
HHfii^kv?l^opyKyCloX@o^d?l^oOf_Zu3yyIy/5533yyNFAy051y

QQebDofwwibaAbkyKyMfilqPqlkbdb^o%16+3)15+2&yyNFAy0.0y
QPql`hfkdGbqpqb^jyKyMfilq?biiltcfw%16+2)15+1&yyNFAy0.4y
>BsbopefkbyKyMfilq?biiltcfw%16+2)15+1&yyNFAy0.5y

??rvXOe^mplavJ^iqZyKyColjfkkhbbmbo%14+1)2/+2&lodbkbo^iprmmifbofkHe^o^klp$pfkkyyIy/561yyNFAy0..y
??rvXQerkabo>ibZyKyColjfkkhbbmbo%14+1)2/+2&yyIy/353yyNFAy0..y
Q?fqqboOfs^ipyKyDfsbqebXQerkabo>ibZqlG^osbkaltkpq^fop)qebkq^ihqlqeb_^oobi%14+4)2/+4&yyNFAy0.-y
>ObqrokqlJ^oibqeyKyRkdr^oabaQerkabo>ib?^oobi%14+4)2/+4&yyNFAy0..y
Q?bbo?^pqba?l^oOf_pyKyO^dk^oQerkabo_obt%13+5)2/+1&yyNFAy051y
>Colpqj^kbEliayKyPbkfoTefqb_b^oa%13+4)20+5&yyNFAy/54y
>Lmbo^qflkOb`lj_l_ri^qflkyKyO^wwibPmovpmol`hbq%12+6)16+0&yyNFAy1./y

QBsbopefkbyKyObglia?^oibv_obt%0-+/)12+4&yyNFAy0.5y
>>C^slocloBsbopefkbyKyObglia?^oibv_obt%0-+/)12+4&yyNFAy0.6y
QQebMbocb`qPqlrqyKyObglia?^oibv_obt%0-+/)12+4&yyNFAy0.2y
>PefjjboPqlrqyKyObglia?^oibv_obt%0-+/)12+4&yyNFAy1.0y
QObqrokqlJ^oibqeyKyJ^oibqe?^oibv_obt%0-+/)12+2&yyNFAy0..y

@Colpqj^kbEliayKyDlql%/.)2.&qlbumilob^kahfii2Colpqj^kbEb^aerkqbopyyNFAy/54y
@Lmbo^qflkOb`lj_l_ri^qflkyKyDlql%/2)1/&^kahfiiIbmboDkljbp^ka`liib`q5XObpq^_fifw^qflk@ldpZ^ka5XDvoljb`e^kf`Db^opZyyNFAy1./y
@>C^slocloBsbopefkbyKy>_fqtbpqlc?obtk^iiSfii^db%/5)15+2&yyNFAy0.6y
Q>C^slocloBsbopefkbyKyObglia?^oibv_obt%0-+/)12+4&yyNFAy0.6y
>Obqrokql?biiltcfwyKyObglia?^oibv_obt%0-+/)12+4&yyNFAy0/-y

>Qrkao^J^`Do^kk$pPqlibkPq^peyKyQrkao^J^`Do^kk)ob^`eefjcoljqebplrqebokm^oqlcqebefii%01+3)2.+3&yyNFAy0./y
@Qrkao^J^`Do^kk$pPqlibkPq^peyKyDlql%05)21&^kacfkaqeb`ebpqfkqeb`^sbdr^oaba_vLiaF`b_b^oa+T^fqrkqfiLiaF`b_b^oam^qoliplrq^t^vcoljqeb`ebpq^kanrf`hivorkfk^kaillqqeb`ebpq^kaork_^`hlrqyyNFAy0./y
QQrkao^J^`Do^kk$pPqlibkPq^peyKyQrkao^J^`Do^kk%01+3)2.+3&yyNFAy0./y

EHe^o^klpyRy3615yyNFAy/6.y
QColpqj^kbEliayKyPbkfoTefqb_b^oa%13+4)20+5&yyNFAy/54y
>QebObmloqpyKyPbkfoTefqb_b^oa%13+4)20+5&yyNFAy/6.y
QLmbo^qflkOb`lj_l_ri^qflkyKyO^wwibPmovpmol`hbq%12+6)16+0&yyNFAy1./y
QObqrokql?biiltcfwyKyMfilq?biiltcfw%16+2)15+1&yyNFAy0/-y

>Q^jfkdqeb?b^pq%M^oq.&y@yErkqboyyKyDofcTfiaeb^oq%12+5)20&yyNFAy3-31y
@Q^jfkdqeb?b^pq%M^oq.&y@yErkqboyyRy.26..yyKyQ^jb^I^odb?l^o@o^d%16)22&yyNFAy3-31y
QQ^jfkdqeb?b^pq%M^oq.&y@yErkqboyyKyDofcTfiaeb^oq%12+5)20&yyNFAy3-31y
>Q^jfkdqeb?b^pq%M^oq/&y@yErkqboyyKyDofcTfiaeb^oq%12+5)20&yyNFAy3-51y
@Q^jfkdqeb?b^pq%M^oq/&y@yErkqboyyRy.26.0yyKyQ^jb^PkltIblm^oa%16)22&yyNFAy3-51y
QQ^jfkdqeb?b^pq%M^oq/&y@yErkqboyyKyDofcTfiaeb^oq%12+5)20&yyNFAy3-51y
>Q^jfkdqeb?b^pq%M^oq0&y@yErkqboyyKyDofcTfiaeb^oq%12+5)20&yyNFAy3-52y
@Q^jfkdqeb?b^pq%M^oq0&y@yErkqboyyRy.26-5yyKyQ^jb^kF`b@i^t?b^o%16)22&yyNFAy3-52y
QQ^jfkdqeb?b^pq%M^oq0&y@yErkqboyyKyDofcTfiaeb^oq%12+5)20&yyNFAy3-52y
>Qo^fkfkdqeb?b^pqy@yErkqboyyKyDofcTfiaeb^oq%12+5)20&yyNFAy3.-0y

>Pmb^htfqe?fkhy@yJ^dbyyKyJ^dfpPm^ohj^kqib%14+2)2/&yyNFAy.546y
>Ol^aqlP^is^qflky@yOldrbyyKyEldo^i?^hh^k%14+3)2/+3&yyNFAy//.5y
>JrobkPqlojmfhby@yT^oofloyyKyDo^kfpPtfcq^ub%14+0)2/+3&yyNFAy.346y

QJrobkPqlojmfhby@yT^oofloyyWyFolkclodbyyKyJrobkPqlojmfhb%4-+4)56+.&yyNFAy.346y
>Sbgobhy@yT^oofloyyWyFolkclodbyyKyJrobkPqlojmfhb%4-+4)56+.&yyNFAy.345y
OArkJloldey@yT^oofloyyKyOrk_^`hqlArkJlolde%.1)53&yyNFAy10/y
@SbgobhyKyHfiiSbgobh%/4+4)24+4&^ka`liib`qefpeb^ayy@yT^oofloyyNFAy.345y
QSbgobhy@yT^oofloyyWyFolkclodbyyKyJrobkPqlojmfhb%4-+4)56+.&yyNFAy.345y
>QlojrpAbbmclodby@yT^oofloyyWyFolkclodbyyKyJrobkPqlojmfhb%4-+4)56+.&yyNFAy.35-y
QQlojrpAbbmclodby@yT^oofloyyWyFolkclodbyyKyQlojrpAbbmclodb%16+3)1/+3&yyNFAy.35-y
>Folk_^ka$p@ljmlrkay@yT^oofloyyWyFolkclodbyyKyQlojrpAbbmclodb%16+3)1/+3&yyNFAy.35.y
OArkJloldey@yT^oofloyyKyOrk_^`hqlArkJlolde%.1)53&yyNFAy10/y

>Qelpb?i^pqbaQolddpyKyClobj^kPqlkb_olt^qDli$?li^oNr^oov%36+.)23+0&yyNFAy10/y
>QebMr_if`Pbos^kqyKyPbk^qloJbeoPqlkbe^iilt%35+3)22+6&yyNFAy100y
@QebMr_if`Pbos^kqyKyHfii.-Ol`hg^t?lkbpk^mmbopproolrkafkdqebi^hb^olrka%44)3-&yyNFAy100y
@Folk_^ka$p@ljmlrkayKy@liib`qXRj_o^iLobZ%44+6)3/+/&yy@yT^oofloyyNFAy.35.y
@Qelpb?i^pqbaQolddpyKyHfii3Ol`hg^tPhriiqerjmbop^olrkaqebDli$?li^onr^oov^q%36)26&yyNFAy10/y
QQelpb?i^pqbaQolddpyKyClobj^kPqlkb_olt%36+.)23+0&yyNFAy10/y
QQebMr_if`Pbos^kqyKyPbk^qloJbeoPqlkbe^iilt%35+3)22+6&yyNFAy100y

>QebIlpqMfilqyKyMfilqE^jjbocllq%50+5)06+/&yyNFAy1.6y
QQebIlpqMfilqyKy>_fqkloqetbpq)q^ihqlqeb`lompb%46+4)03+/&yyNFAy1.6y
>>Mfilq$pObsbkdbyKy>At^osbk@lompb%46+4)03+/&yyNFAy1.4y
@>Mfilq$pObsbkdbyKyHfiiJ^kdb`i^t^ka`liib`qXJ^kdv@i^tZ%45+2)04+3&yyNFAy1.4y
Q>Mfilq$pObsbkdbyKyMfilqE^jjbocllq%50+5)06+/&yyNFAy1.4y

QPefjjboPqlrqyKyCfkaJlrkq^fkbbo?^oibv_obtPlrqetbpqqeolrde^qrkkbi%53+0)15+6&yyNFAy1.0y
>PqlrqqlH^aobiiyKyJlrkq^fkbbo?^oibv_obt%53+0)15+6&yyNFAy1.1y

>FkAbcbkpblcqebHfkd$pI^kapyWyIl`eJla^kyyKyJlrkq^fkbbo@l__ibcifkq%//+.)40&yyNFAy//1y
>QebQolddQeob^qyWyIl`eJla^kyyKy@^mq^fkOrdbicrpp%/0+/)40+4&yyNFAy/34y
@FkAbcbkpblcqebHfkd$pI^kapyWyIl`eJla^kyyKyHfii.-PqlkbpmifkqboQolddp^ka.-PqlkbpmifkqboP`lrqptef`e`^k_bclrkafkqeb^ob^tbpqlcQebip^jj^o^olrka%/6)20&yyNFAy//1y
@QebQolddQeob^qyWyIl`eJla^kyyKyHfiiPqlkbpmifkqboQolddp^kaP`lrqptef`e`^k_bclrkafkqeb^ob^tbpqlcQebip^jj^o^olrka%/6)20&ql`liib`q5XQolddPqlkbQbbqeZyyNFAy/34y
QQebQolddQeob^qyWyIl`eJla^kyyKy@^mq^fkOrdbicrpp%/0+/)40+4&yyNFAy/34y
QFkAbcbkpblcqebHfkd$pI^kapyWyIl`eJla^kyyKyJlrkq^fkbbo@l__ibcifkq%//)40&yyNFAy//1y

QPqlrqqlH^aobiiyWyIl`eJla^kyyKyJlrkq^fkbboH^aobii%00+3)14+.&yyNFAy1.1y
>O^q@^q`efkdyWyIl`eJla^kyyKyJlrkq^fkbboH^aobii%03)13&yyNFAy1.3y
cQebip^j^oyWyIl`eJla^kyyKyQelodorj?loobiplk%00+6)2-+6&yyNFAy.006y

>Jlrkq^fkbboPqlojmfhb$pQ^phyWyIl`eJla^kyyKyJlrkq^fkbboH^aobii%03)13&yyNFAy.006y
QJlrkq^fkbboPqlojmfhb$pQ^phyWyIl`eJla^kyyKyJlrkq^fkbboPqlojmfhb%/1+4).5+0&yyNFAy.006y
>Pqlojmfhb$pLoaboyWyIl`eJla^kyyKyJlrkq^fkbboPqlojmfhb%/1+4).5+0&yyNFAy.005y

OQebip^j^oyWyIl`eJla^kyyKyQelodorj?loobiplk%00+6)2-+6&yyNFAy333.y
C@fqvlcFolkclodbyWyIl`eJla^kyyKyQelodorj?loobiplk%00+6)2-+6&yyNFAy333.y

QQebObmloqpyWyFolkclodbyyKyPbk^qlo?^ofkObapqlkb%06+3)24+.&yyNFAy/6.y

QQo^fkfkdqeb?b^pqy@yErkqboyyWyFolkclodbyyKy?bif^Qerkabodo^kfqb%4-+5)52+1&yyNFAy3-53y

QPmb^htfqe?fkhy@yJ^dbyyWyFolkclodbyyKy?fkh%/4)5+/&yyNFAy.546y
>J^db*q^pqf`Dfwjlkfqloy@yJ^dbyyWyFolkclodbyyKy?fkh%/4)5+/&yyNFAy.55-y
OArkJloldey@yJ^dbyyKyOrk_^`hqlArkJlolde%.1)53&yyNFAy333.y
@J^db*q^pqf`Dfwjlkfqloy@yJ^dbyyKy@liib`qXJ^db*q^pqf`DfwjlkfqloZ%/4+4)03+1&yyNFAy.55-y
O@fqvlcFolkclodby@yJ^dbyyKyDlqlFolkclodb%22+4)0.+5&yyNFAy333.y
QJ^db*q^pqf`Dfwjlkfqloy@yJ^dbyyWyFolkclodbyyKy?fkh%/4)5+/&yyNFAy.55-y

QOl^aqlP^is^qflky@yOldrbyyWyFolkclodbyyKyErica^k?i^`h_b^oa%2.+4).1+4&yyNFAy//.5y
>PfjmibPr_qbocrdfk$y@yOldrbyyWyFolkclodbyyKyErica^k?i^`h_b^oa%2.+4).1+4&yyNFAy//05y
OArkJloldey@yOldrbyyKyOrk_^`hqlArkJlolde%.1)53&yyNFAy333.y
QPfjmibPr_qbocrdfk$y@yOldrbyyKyLkfkJ^`E^jj^o%/2+/)11+1&yyNFAy//05y
>Lkfk$pObmloqy@yOldrbyyKyLkfkJ^`E^jj^o%/2+/)11+1&yyNFAy//06y
O@fqvlcFolkclodby@yOldrbyyKyDlqlFolkclodb%22+4)0.+5&yyNFAy333.y
QLkfk$pObmloqy@yOldrbyyWyFolkclodbyyKyErica^k?i^`h_b^oa%2.+4).1+4&yyNFAy//06y

KDbq^QljblcAfsfkfqvyIy3442yyKyDlpbbQfw^?^qqibclodb%/4+2)..+.&yy@yM^i^afkyyWyFolkclodbyyNFAy.31/y
>QebQljblcAfsfkfqv%M^oq.&y@yM^i^afkyyRy3442yyNFAy.313yyWyFolkclodby
QQebQljblcAfsfkfqv%M^oq.&yKyQfw^?^qqibclodb%/4+2)..+.&yy@yM^i^afkyyNFAy.313yyWyFolkclodby
>QebQljblcAfsfkfqv%M^oq/&yKyQfw^?^qqibclodb%/4+2)..+.&yy@yM^i^afkyyNFAy.314yyWyFolkclodby
QQebQljblcAfsfkfqv%M^oq/&yKyGlekQrokbo)T^ihp^olrkaQeb@ljjlkp_bqtbbk%10+2)51+2&^ka%/.+0)16+3&yy@yM^i^afkyyNFAy.314yyWyFolkclodby
>QebQljblcAfsfkfqv%M^oq0&yKyGlekQrokbo)T^ihp^olrkaQeb@ljjlkp_bqtbbk%10+2)51+2&^ka%/.+0)16+3&yy@yM^i^afkyyNFAy.315yyWyFolkclodby
QQebQljblcAfsfkfqv%M^oq0&yKyGlekQrokbo)T^ihp^olrkaQeb@ljjlkp_bqtbbk%10+2)51+2&^ka%/.+0)16+3&yy@yM^i^afkyyNFAy.315yyWyFolkclodby
>QebQljblcAfsfkfqv%M^oq1&yKyGlekQrokbo)T^ihp^olrkaQeb@ljjlkp_bqtbbk%10+2)51+2&^ka%/.+0)16+3&yy@yM^i^afkyyNFAy.445yyWyFolkclodby
QQebQljblcAfsfkfqv%M^oq1&yKyQfw^?^qqibclodb%/4+2)..+.&yy@yM^i^afkyyNFAy.445yyWyFolkclodby
>QebQljblcAfsfkfqv%M^oq2&yKyQfw^?^qqibclodb%/4+2)..+.&&yy@yM^i^afkyyNFAy.446yyWyFolkclodby
QQebQljblcAfsfkfqv%M^oq2&yKyJrfobalk?^qqibclodb%/0+4)6+-&yy@yM^i^afkyyNFAy.446yyWyFolkclodby
>QebQljblcAfsfkfqv%M^oq3&yKyJrfobalk?^qqibclodb%/0+4)6+-&yy@yM^i^afkyyNFAy.450yyWyFolkclodby

QQebQljblcAfsfkfqv%M^oq3&yKyK^ojC^rih%45+0)25+.&yyRy3533yy@yM^i^afkyyNFAy.450y
>QebQljblcAfsfkfqv%M^oq4&yKyK^ojC^rih%45+0)25+.&yy@yM^i^afkyyNFAy.451y
@QebQljblcAfsfkfqv%M^oq4&yKyHfiiA^ohFolkPmfbp^olrka%44+.)26+.&qlobqofbsbqebA^ohFolkP`ofmqyy@yM^i^afkyyNFAy.451y
QQebQljblcAfsfkfqv%M^oq4&yKyJrfobalk?^qqibclodb%/0+4)6+-&yy@yM^i^afkyyNFAy.451yyWyFolkclodby
>QebQljblcAfsfkfqv%M^oq5&yKyJrfobalk?^qqibclodb%/0+4)6+-&yyy@yM^i^afkyyNFAy.452yyWyFolkclodby
QQebQljblcAfsfkfqv%M^oq5&yKyQfw^?^qqibclodb%/4+2)..+.&yy@yM^i^afkyyNFAy..452yyWyFolkclodby

QFolk_^ka$p@ljmlrkay@yT^oofloyyWyFolkclodbyyKyQlojrpAbbmclodb%16+3)1/+3&yyNFAy.35.y
QDobvFolkTb^mlkpy@yT^oofloyyWyFolkclodbyyKyQlojrpAbbmclodb%16+3)1/+3&yyNFAy.35/y

OAbbmorkQo^jyWyFolkclodbyyKy%51)2/&yyNFAy333.y
>AbbmorkO^qOlrkarmyKyQ^ihqlJlkqvyyNFAy333.y
@AbbmorkO^qOlrkarmyRy.4..4yyKy@^mqrob2AbbmorkO^qp_vrpfkdqebXO^q@^q`ebo$pCirqbZ+Ib^aqebo^qp_^`hqlJlkqvyyNFAy333.y
QAbbmorkO^qOlrkarmyNFAy333.y
>Jb?olqebo)KfmpvyNFAy333/y
KDbqlkqebqo^jqlPqlojtfka@fqvyNFAy333/y
QJb?olqebo)KfmpvyNFAy333/y
OPqlojtfka@fqvyNFAy020y
QPqlojmfhb$pLoaboyWyPqlojtfka@fqvyyKyCrobkIlkd_b^oa%31+4)04+2&yyNFAy.005y
>Pqlojmfhb$pAbifsbovyKyDofj^kaBijlob%26+4)01&yyWyPqlojtfka@fqvyyNFAy020y
cPqlojtfka@fqvyKyArkd^oIlkdaofkh%4.)4/+3&yyWyPqlojtfka@fqvy
_>r_boafkbyWyPqlojtfka@fqvyyKyQ^hbqeb_l^qcoljPqlojtfka%/0)22+2&ql>r_boafkby
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby

]]
end)
