DugisGuideViewer:RegisterGuide("Darkshore (12-17)", "Loch Modan (17-18)", "Alliance", "L", function()
return [[
AAA

_>r_boafkbyKyQ^hbqeb_l^qcoljPqlojtfkalocivcoljQbiao^ppfiyyNFAy02/1y

c>r_boafkbyKy@^vi^fpJllkcb^qebo%03+1)12+2&yyNFAy02/1y

>T^peba>pelob%M^oq.&yKyDtbkkvqe?iv$Ibddlkab%03+3)12+2&yyNFAy02/1y
QCifdeqql>r_boafkbyKyI^foa%03+5)11+0&yyOyKfdeqBicyyNFAy301/y
>ObqrokqlKbpp^yKyI^foa%03+5)11+0&yyOyKfdeqBicyyNFAy3010y
e>r_boafkbyKyFkkhbbmboPe^rppfv%04)11+.&yyNFAy630y

COrq$qebo^kSfii^dbyOyKfdeqBicyyKy@^vi^fpJllkcb^qebo%03+1)12+2&yyNFAy630y
QObqrokqlKbpp^yKyKbpp^Pe^altplkd%23+0)6/+1&yyOyKfdeqBicyyWyQbiao^ppfiyyNFAy3010y
C>r_boafkbyOyKfdeqBicyyKySbpmovpqrp%25+1)61&yyWyQbiao^ppfiyyNFAy630y

>CloIlsbBqbok^iyKy@bobiib^kTefqb`i^t%02+5)10+4&yyNFAy630y
>?rww_lu5/4yKyTfw_^kd@o^khqlddib%04)11+.&yyNFAy650y
>?^pe^i$>o^k%M^oq.&yKyQerkaofpTfkatb^sbo%04+1)1-+/&yyNFAy621y
>QlliplcqebEfde_lokbyKyQerkaofpTfkatb^sbo%04+1)1-+/&yyNFAy625y
>Mi^drbaI^kapyKyQe^ok^ofrkQobbqbkabo%05+5)10+1&yyNFAy/..5y
>Elt?fd^Qeob^q<%M^oq.&yKyQbobkqefp%06+0)10+2&yyNFAy651y

@QebPe^ablcBiro^y@yT^oofloyyOyKfdeqBicyyKyCfkaqebPefm%0.)11&^ka`liib`qXBirkfqbLobZcoljfkpfabqeb`o^qb^kahfiiPe^ablcBiro^%0.+3)11+6&ql`liib`qXBiro^$pJba^iiflkZyyNFAy.353y
COrq$qebo^kSfii^dby@yT^oofloyyOyKfdeqBicyyKy@^vi^fpJllkcb^qebo%03+1)12+2&yyNFAy.353y
OA^ok^pprpy@yT^oofloyyOyKfdeqBicyyKyOrkqeolrdeqebmloq^iqlA^ok^pprp%22+6)56+3&yyWyQbiao^ppfiyyNFAy.353y
QQebPe^ablcBiro^y@yT^oofloyyOyKfdeqBicyyKyBi^k^of^%24+2)02&yyWyA^ok^pprpyyNFAy.353y
>PjfqeJ^qefbiy@yT^oofloyyOyKfdeqBicyyKyBi^k^of^%24+2)02&yyWyA^ok^pprpyyNFAy.36/y
QPjfqeJ^qefbiy@yT^oofloyyOyKfdeqBicyyKyJ^qefbi%26+0)12+0&yyWyA^ok^pprpyyNFAy.36/y
QTb^mlkplcBirkfqby@yT^oofloyyOyKfdeqBicyyKyJ^qefbi%26+0)12+0&yyWyA^ok^pprpyyNFAy.360y
OOrq$qebo^kSfii^dby@yT^oofloyyOyKfdeqBicyyKyOrkqeorqebmloq^itbpqlcqeb_^kh%0-+2)1.+1&yyWyA^ok^pprpyyNFAy.--.y
C>r_boafkby@yT^oofloyyOyKfdeqBicyyKySbpmovpqrp%25+1)61&yyNFAy.--.y

@T^peba>pelob%M^oq.&yKyCfkaqebPb^@ob^qrob^kaillqfqpobj^fkp^q%03)2-&yyNFAy02/1y
@?rww_lu5/4yKyHfii^kvlcqeb@o^tiboptef`e^obpmob^a^olrkaqeb`l^pqplcA^ohpelob%03)11&ql`liib`q3X@o^tiboIbdpZ^kaqebkmi^`bqebjfkql?rww_lu5/4%03+3)13+0&yyNFAy650y
Q?rww_lu5/4yKy?rww_lu5/4%03+3)13+0&yyNFAy650y
>?rww_lu1..yKy?rww_lu5/4%03+3)13+0&yyNFAy.--.y
QT^peba>pelob%M^oq.&yKyDtbkkvqe?iv$Ibddlkab%03+3)12+2&yyNFAy02/1y
>T^peba>pelob%M^oq/&yKyDtbkkvqe?iv$Ibddlkab%03+3)12+2&yyNFAy135.y
>QebOba@ovpq^iyKyPbkqfkbiDivka^K^i$Peb^%04+4)10+1&yyNFAy15..y
@T^peba>pelob%M^oq/&yNFAy135.yyKyCfkaqebPb^Qroqib$p_lavfkqebt^qbopqlt^oapqeb_l^qp^q%0.)13&^kaillqfqpobj^fkpy
@?rww_lu1..yKyPtfjfkqlqebpb^^olrkaA^ohpelobtebobvlrtfiicfkaqebQeobpebop%03)/6&hfiiqebjql`liib`q0XQeobpeboBvbpZ)qebkmrqfk?rww_lu1..%1/)/5+4&yyNFAy.--.y
QT^peba>pelob%M^oq/&yKyDtbkkvqe?iv$Ibddlkab%03+3)12+2&yyNFAy135.y
Q?rww_lu1..yKy?rww_lu1..%1/)/5+4&yyNFAy.--.y
>?rww_lu0/0yKy?rww_lu1..%1/)/5+4&yyNFAy.--/y

>?b^`ebaPb^@ob^qrob%M^oq.&yNFAy14/0yyKy?b^`ebaPb^@ob^qrob%1/+-0)0.+34&*^iplil`^qbafklqebo^ob^p^ilkdqeb`l^pqy

Q?^pe^i$>o^k%M^oq.&yKy>pqboflk%11+/)03+0&yyNFAy621y
>?^pe^i$>o^k%M^oq/&yKy>pqboflk%11+/)03+0&yyNFAy622y
@?^pe^i$>o^k%M^oq/&yKyHfiibklrdelcqebDobiifk?^pe^i$>o^k^olrka%14)05&ql`liib`q5XDobiiB^oofkdpZyyNFAy622y
Q?^pe^i$>o^k%M^oq/&yKy>pqboflk%11+/)03+0&yyNFAy622y
>?^pe^i$>o^k%M^oq0&yKy>pqboflk%11+/)03+0&yyNFAy623y
@?^pe^i$>o^k%M^oq0&yKyHfii^kvlcqebAbqe$oviiP^qvoil`^qba^olrka%14)04&rkqfivlrdbqqebX>k`fbkqJllkpqlkbPb^iZyyNFAy623y
Q?^pe^i$>o^k%M^oq0&yKy>pqboflk%11+/)03+0&yyNFAy623y
>?^pe^i$>o^k%M^oq1&yKy>pqboflk%11+/)03+0&yyNFAy624y
@QebOba@ovpq^iyKyCfkaqebOba@ovpq^iqlqebb^pqlc>r_boafkblkqebJlrkq^fk$p_loabo^olrka%15)15&yyNFAy15..y
@Elt?fd^Qeob^q<%M^oq.&yKyQo^sbiqlqebCro_ild`^jmp^q%1-+0)20+2&^kadlfkc^obklrdeqle^sbqebnrbpq`ljmibqbayyNFAy651y

>QebC^iilc>jbqe$>o^kyKyPbkqfkbiQvpe^Jllk_i^ab%1-+0)26+4&yyNFAy620y
@QebC^iilc>jbqe$>o^kyKyQo^sbiql>jbqe$>o^kqlcfkaQebI^vlc>jbqe$>o^k^q%10+0)25+4&^kaQebC^iilc>jbqe$>o^k^q%1/+3)30+.&yyNFAy620y
@CloIlsbBqbok^iyKyCfka^kahfii>k^v^A^tkorkkbo%1/)26&telt^ihp^olrkaqeb>jbqe$>o^kql`liib`qebombka^kq+Pebfp^kbrqo^ijl__rqtfiiqrok^dobppfsblk`bvlr^qq^`heboyyNFAy630y
@?^pe^i$>o^k%M^oq1&yKyQo^sbiql>jbqe$>o^k^kaq^hbqebX>k`fbkqJllkpqlkbPb^iZqlqeb^k`fbkqci^jbil`^qba^q%1/+1)3.+5&yyNFAy624yyRy2005y
@QlliplcqebEfde_lokbyKyHfii^kvlcqebEfde_lokbjl_p^olrka%10)3-&fk>jbqe$>o^kql`liib`q4XEfde_lokbObif`pZyyNFAy625y
@Mi^drbaI^kapyKyO^_faQefpqib?b^op`^k_bclrkapmob^aqeolrdelrqqeb^ob^m^pq?^pe^i$>o^k^olrka%15)0-&loqeb^ob^m^pq>jbqe$>o^k^olrka%06)33&+RpbXQe^ok^ofrk$pElmbZlkqeb_b^oql`^mqrobfqqebkork_^`htfqelrqrpfkd^kvpmbbabk`e^k`fkd^_fifqfbpyyRy4253yyNFAy/..5y
QQebC^iilc>jbqe$>o^kyKyPbkqfkbiQvpe^Jllk_i^ab%1-+0)26+4&yyNFAy620y

E>r_boafkbyRy3615yyNFAy/.05y
QMi^drbaI^kapyKyQe^ok^ofrkQobbqbkabo%05+5)10+1&yyNFAy/..5y
>@ib^kpfkdlcqebFkcb`qbayKyQe^ok^ofrkQobbqbkabo%05+5)10+1&yyNFAy/.05y
QElt?fd^Qeob^q<%M^oq.&yKyQbobkqefp%06+0)10+2&yyNFAy651y
>Elt?fd^Qeob^q<%M^oq/&yKyQbobkqefp%06+0)10+2&yyNFAy652y
>QerkaofpTfkatb^sboyKyQbobkqefp%06+0)10+2&yyNFAy143.y
>QebQltbolc>iqe^i^uu%M^oq.&yKyPbkqfkbiBifpp^Pq^o_obbwb%06+.)10+2&yyNFAy632y
QQlliplcqebEfde_lokbyKyQerkaofpTfkatb^sbo%04+1)1-+/&yyNFAy625y
QQerkaofpTfkatb^sboyKyQerkaofpTfkatb^sbo%04+1)1-+/&yyNFAy143.y
>Qeb@ifccpmofkdOfsboyKyQerkaofpTfkatb^sbo%04+1)1-+/&yyNFAy143/y
QQebOba@ovpq^iyKyPbkqfkbiDivka^K^i$Peb^%04+4)10+1&yyNFAy15..y
>>pT^qbo@^p`^abpyKyPbkqfkbiDivka^K^i$Peb^%04+4)10+1&yyNFAy15./y
KCfiiqebXBjmqvT^qboQr_bZfkqebJllktbiiyKy%04+5)11+-&yyRy.1005yyIy.1006yyNFAy15./y
>@^sbJrpeolljpyKy?^ofqeo^pJllkpe^ab%04+0)10+4&yyNFAy614y
QCloIlsbBqbok^iyKy@bobiib^kTefqb`i^t%02+5)10+4&yyNFAy630y
Q?b^`ebaPb^@ob^qrob%M^oq.&yKyDtbkkvqe?iv$Ibddlkab%03+3)12+2&yyNFAy14/0y

Q?^pe^i$>o^k%M^oq1&yKy>pqboflk%11+/)03+0&yyNFAy624y
@@ib^kpfkdlcqebFkcb`qbayKyHfii/-O^_faQefpqib?b^optef`e^obpmob^aqeolrdelrqqeb^ob^m^pq?^pe^i$>o^k^olrka%15)0-&lo^obm^pq>jbqe$>o^k^olrka%06)33&yyNFAy/.05y
>?b^`ebaPb^Qroqib%M^oq.&yKy?b^`ebaPb^Qroqib%11+.5)/-+3/&*^iplil`^qbafklqebo^ob^p^ilkdqeb`l^pqyyNFAy14/2y
@?rww_lu0/0yKyHfii^kvlcqebJllkpq^ihbo^olrkaA^ohpelobil`^qba^olrka%16)/4&^ka%1-)34&ql`liib`q3XJllkpq^ihboC^kdpZqebkmrqqebjfk?rww_lu0/0%2.+0)/1+3&yyNFAy.--/y

@Qeb@ifccpmofkdOfsboyKyQo^sbiqlqeb@ifccpmofkdOfsboT^qboc^ii^q%2-+51)/2+3-&^kacfiiqebXBjmqvP^jmifkdQr_bZyyRy./02-yyNFAy143/y
Q?rww_lu0/0yKy?rww_lu0/0%2.+0)/1+3&yyNFAy.--/y
>?rww_lu2/2yKy?rww_lu0/0%2.+0)/1+3&yyNFAy.--0y
@@^sbJrpeolljpyKyQo^sbiqlqeb`^sbbkqbo^k`b^q%22)02&+Qefpmi^`bfpproolrkaba_vK^d^b^`emi^`banrfqb`ilpbql^klqebopl^ddolqljlobqe^qlkbK^d^fpsbovb^pvqlj^hb_v^``fabkqpl_b`^obcrilcqebt^vvlrmrii+HfiiqebK^d^fkqeb`^sb^kadlqlqebjrpeolljppmob^aqeolrdelrqqeb^ob^rkqfivlr`liib`q2XP`^_boPq^ihpZ%22)01&^ka.XAb^qe@^mZ%23)02&+Qeb^ob^qlqebofdeqpelria_bqebb^pfbom^qeqlqo^sbialtkyyNFAy614y
Q>pT^qbo@^p`^abpyKyJvpqboflrpOba@ovpq^i%14+0)15+4&yyNFAy15./y
>QebCo^djbkqpTfqefkyKyJvpqboflrpOba@ovpq^i%14+0)15+4&yyNFAy15.0y
@Elt?fd^Qeob^q<%M^oq/&yKyQo^sbi_^`hqlqebp^jbCro_ild`^jm^pM^oq.lcqeb`e^fk^q^kahfii5?i^`htllaM^qecfkabop%06)21&^ka2Tfkaq^ihbop%06)2/&yyNFAy652y
>?b^`ebaPb^Qroqib%M^oq/&yKy?b^`ebaPb^Qroqib%04+/)3/+.&*^iplil`^qbafklqebo^ob^p^ilkdqeb`l^pqyyNFAy14//y
>?b^`ebaPb^@ob^qrob%M^oq/&yKy?b^`ebaPb^@ob^qrob%03+.)4-+4&*^iplil`^qbafklqebo^ob^p^ilkdqeb`l^pqyyNFAy14/5y

QDolsblcqeb>k`fbkqpyKyLkr%10+2)43+0&yyOyKfdeqBicyyNFAy62/y
@?rww_lu2/2yKyHfiiqebDofwwibaQefpqib?b^op)tef`e^obclrkafkqebPlrqebok^ob^lcA^ohpelob^olrka%1/)50&ql`liib`q1XDofwwibaP`^impZqlmrqfkql?rww_lu2/2%1.+1)5-+3&yyNFAy.--0y
Q?rww_lu2/2yKy?rww_lu2/2%1.+1)5-+3&yyNFAy.--0y
>?b^`ebaPb^@ob^qrob%M^oq0&yKy?b^`ebaPb^@ob^qrob%00)5.+.&*^iplil`^qbafklqebo^ob^p^ilkdqeb`l^pqyyNFAy140-y

E>r_boafkbyRy3615yyNFAy..05y
Q?b^`ebaPb^@ob^qrob%M^oq/&yKyDtbkkvqe?iv$Ibddlkab%03+3)12+2&yyNFAy14/5y
Q?b^`ebaPb^@ob^qrob%M^oq0&yKyDtbkkvqe?iv$Ibddlkab%03+3)12+2&yyNFAy140-y
Q?b^`ebaPb^Qroqib%M^oq.&yKyDtbkkvqe?iv$Ibddlkab%03+3)12+2&yyNFAy14/2y
Q?b^`ebaPb^Qroqib%M^oq/&yKyDtbkkvqe?iv$Ibddlkab%03+3)12+2&yyNFAy14//y
>CorfqlcqebPb^yKyDr__bo?irjm%03+.)11+6&yyNFAy..05y
>T>KQBA7JrohabbmyKyT>KQBA7Jrohabbm%04+/)11+/&yyNFAy141-y
Q@^sbJrpeolljpyKy?^ofqeo^pJllkpe^ab%04+0)10+4&yyNFAy614y
>LkryKy?^ofqeo^pJllkpe^ab%04+0)10+4&yyNFAy615y
QQebCo^djbkqpTfqefkyKyPbkqfkbiDivka^K^i$Peb^%04+4)10+1&yyNFAy15.0y
>Qeb>_pbkqJfkabaMolpmb`qloyKy>o`e^blildfpqEliibb%04+2)1.+5&yyNFAy4/6y
QQeb@ifccpmofkdOfsboyKyQerkaofpTfkatb^sbo%04+1)1-+/&yyNFAy143/y
>Qeb?i^`htlla@loormqbayKyQerkaofpTfkatb^sbo%04+1)1-+/&yyNFAy1430y
Q@ib^kpfkdlcqebFkcb`qbayKyQe^ok^ofrkQobbqbkabo%05+5)10+1&yyNFAy/.05y
>Qe^ok^ofrk$pElmbyKyQe^ok^ofrkQobbqbkabo%05+5)10+1&yyNFAy/.06y
QElt?fd^Qeob^q<%M^oq/&yKyQbobkqefp%06+0)10+2&yyNFAy652y
KCfiiqebXBjmqv@ib^kpfkd?ltiZfkqebJllktbiiyKy%04)10&yyRy./013yyNFAy1430y

@Qeb?i^`htlla@loormqbayKy@liib`qqebp^jmiblcDo^fk%2-)02&)Corfq%2/)00&^kaKrqp%2.)00&+Lk`b^ii`liib`qbarpbqebXBjmqv@ib^kpfkd?ltiZlkqeb_lkcfob^q%2/)0/&+>_rk`elcCro_ildptfii`ljborkkfkdqlt^oapvlr_rqtfiiklq^qq^`h+Qefptfii^iplpm^tkU^_o^uufp^Ibsbi.6P^qvotellk`bhfiibatfiiaolm^_^dtef`evlrjrpqlmbkqlillqqebXQ^ifpj^klc@loormqflkZyyRy./014yyNFAy1430y
@Qe^ok^ofrk$pElmbyKyQo^sbiqlqeb`^sb^q%2/+1-)02)55&)%2.+3-)04+05&tebobvlrtfiicfkaqebAbkJlqebo%Ibsbi.6&tfqeclroIbsbi6*.-@r_p+B^`ejl_fpifkhbatfqeqeblqebopl`^kklq_bmriibapbmbo^qbiv)qeb_bpqt^vqldbqqefpalkbfpqlm^formtfqepljblqebopyyNFAy/.06y
QQebQltbolc>iqe^i^uu%M^oq.&yKy?^iqeribPe^altpqofhb%21+6)/1+6&yyNFAy632y
>QebQltbolc>iqe^i^uu%M^oq/&yKy?^iqeribPe^altpqofhb%21+6)/1+6&yyNFAy633y
@QebQltbolc>iqe^i^uu%M^oq/&yKy@liib`q1XTlokM^o`ejbkqpZtef`e^obaolmmbacoljqebA^ohPqo^kaC^k^qf`tef`eproolrkaQebQltbolc>iqe^i^uu^olrka%24)/4&yyNFAy633y
QQebQltbolc>iqe^i^uu%M^oq/&yKy?^iqeribPe^altpqofhb%21+6)/1+6&yyNFAy633y
>QebQltbolc>iqe^i^uu%M^oq0&yKy?^iqeribPe^altpqofhb%21+6)/1+6&yyNFAy634y
>?b^`ebaPb^Qroqib%M^oq0&yKy?b^`ebaPb^Qroqib%20+.).5+/&*^iplil`^qbafklqebo^ob^p^ilkdqeb`l^pqyyNFAy14/4y
@CorfqlcqebPb^yKyDbq3XCfkb@o^_@erkhpZtef`e^obaolmmbacljObbc@o^tibop^kaBk`orpqbaQfab@o^tibopclrkakb^oqeb_ofadb`olppfkdqeb@ifccpmofkdOfsbo^olrka%2.)//&yyNFAy..05y

E>r_boafkbyRy3615y
Q?b^`ebaPb^Qroqib%M^oq0&yKyDtbkkvqe?iv$Ibddlkab%03+3)12+2&yyNFAy14/4y
QCorfqlcqebPb^yKyDr__bo?irjm%03+.)11+6&yyNFAy..05y
QQeb?i^`htlla@loormqbayKyQerkaofpTfkatb^sbo%04+1)1-+/&yyNFAy1430y
QQe^ok^ofrk$pElmbyKyQe^ok^ofrkQobbqbkabo%05+5)10+1&yyNFAy/.06y

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
