DugisGuideViewer:RegisterGuide("Bloodmyst Isle (12-20 Draenei)", "Darkshore (20-22 Draenei)", "Alliance", "L", function()
return [[
AAA

OHbppbi$p@olppfkdyKyLk?illajvpqFpibqlqebkloqe%30+.)54+3&yyNFAy6330y
QBibhhp>obPboflrp?rpfkbppyKySlohe^kqebBibhhEboabo%30+.)54+6&yyNFAy63/2y
>QebHbppbiOrkyKyHbppbi%30+.)54+3&+Qfjbanrbpq).2jfkrqbp+Abifsbotloaql0mi^`bpyyNFAy6330y

KT^okPqfiimfkbEliayNFAy6330yyNLyEfde@efbcPqfiimfkbT^okba7.,.yyKyEfde@efbcPqfiimfkb%13+4)/-+5&yyWy>wrobjvpqFpiby
KT^ok>wrobT^q`eyNFAy6330yyNLyBu^o`eJbkbi^lrpT^okba7.,.yyKyBu^o`eJbkbi^lrp%14+/)2-+3&fplkqebefii^qqebtbpqbadblcqebt^q`eyyWy>wrobjvpqFpiby
QT^okVlroMblmibyWy>wrobjvpqFpibyyKyBu^o`eJbkbi^lrp%14+/)2-+3&yyNFAy63//y
Q@^iilcCfob%M^oq1&yWy>wrobjvpqFpibyy@yPe^j^kyyKyQrirrk%15+.)2-+2&yyNFAy6135y
>@^iilcCfob%M^oq2&yWy>wrobjvpqFpibyy@yPe^j^kyyKyQrirrk%15+.)2-+2&yyNFAy613.y
QPqobkdqelcLkby@yT^oofloyyWy>wrobjvpqFpibyyKyOr^a^%16+2)2-+0&yyNFAy625/y
>?belj^qy@yT^oofloyyWy>wrobjvpqFpibyyKyOr^a^%16+2)2-+0&yyNFAy.-02-y

KT^okLabpvrp$I^kafkdyWy>wrobjvpqFpibyyNFAy6330yyNLy>ajfo^iLabpvrpT^okba7.,.yyKy>ajfo^iLabpvrp%14)4-+/&)fkLabpvrp$i^kafkdy

QQebHbppbiOrkyKyHbppbi%30+.)54+3&yyNFAy6330y
>Ab`i^o^qflklcMltboyKyHbppbi%30+.)54+3&yyNFAy6333y
>>ifbkMoba^qlopyKySlohe^kqebBibhhEboabo%30+.)54+6&yyNFAy6301y
>>C^slofqbQob^qyKy>lk^o%30+2)55+4&yyNFAy63/1y

KP^kaMb^opyKyDo^_^kvXP^kaMb^opZvlr`ljb^`olppclo>C^slofqbQob^qyyNFAy63/1y

@>ifbkMoba^qlopyKyHfii.-?illajvpqE^q`eifkdpclrka^olrkaqebHbppbi@olppfkd^q%25)54&yyNFAy6301y

Q>ifbkMoba^qlopyKySlohe^kqebBibhhEboabo%30+.)54+6&yyNFAy6301y
>P^sfkdMofk`bppPqfiimfkbyKyCfkaMofk`bppPqfiimfkb%35+.)5.+.&il`hbafk^`^dbfkqeb?ofpqibifj_@^jmyyNFAy6334y
HEfde`efbc?ofpqibifj_yKyDlqlqebkloqebok*jlpq`^jm%32)42&^kahfii5?ofpqibifj_Cro_lidpqlprjjlkEfde`efbc?ofpqibifj_yyIy/1-66yyNFAy6334y
@P^sfkdMofk`bppPqfiimfkbyKyObib^pb^kaMolqb`qMofk`bppPqfiimfkb%35)5.&yyNFAy6334y
@Ab`i^o^qflklcMltboyKyEb^akloqeqlqebTo^qep`^ibI^fo^kahfiiIloaUfw%35+2)35&+Alk$qclodbqqlmi^kqqebXAo^bkbf?^kkboZyyRy/1-51yyNFAy6333y
@>C^slofqbQob^qyKy@liib`q.-XP^kaMb^opZtef`e`^k_bclrkap`^qqboba^olrkaqebHbppbi@olppfkd^kakb^o_v`^jmp^q%34)42&yyNFAy63/1y

QAb`i^o^qflklcMltboyKyHbppbi%30+.)54+3&yyNFAy6333y
>ObmloqqlBu^o`e>ajbqfrpyKyHbppbi%30+.)54+3&yyNFAy6335y
Q>C^slofqbQob^qyKy>lk^o%30+2)55+4&yyNFAy63/1y

>?bap)?^ka^dbp)^ka?bvlkayKyFkqebfkk)@^obdfsboQlmeboIl^^i%22+5)26+4&yyNFAy63-0y
e?illaT^q`eyKyPbq?illaT^q`e^pvlrokbtEljb@^obdfsboQlmeboIl^^i%22+5)26+4&yyNFAy6234y
>HkltQefkbBkbjvyKySfkaf`^qlo>^ibpf^%22+.)25+/&yyNFAy6234y
>@^q`e^kaObib^pbyKyJlo^b%20+0)24+4&yyNFAy63/6y
>J^`$>obbJrpeolljJbk^dbofbyKyGbppbo^lcJ^`$>obb%23+0)23+4&yyNFAy6315y

Q?bap)?^ka^dbp)^ka?bvlkayKyI^^kal%24+3)21&yyNFAy63-0y
>LkqebTfkdplc^EfmmldovmeyKyI^^kal%24+3)21&yyNFAy63-1y
CQebBula^oyKyI^^kal%24+3)21&yyNFAy63-2y
>Obabjmqflk%M^oq.&yOyAo^bkbfyy@yM^i^afkyyKyGli%05+-)5/+-&yyNFAy6265yyWyQebBula^oy
QObabjmqflk%M^oq.&yOyAo^bkbfyy@yM^i^afkyyKyOb^aqeb_llhXQljblcAfsfkfqvZqebkpmb^hqlGli%05)5/&yyNFAy6265yyRy/06/3yyWyQebBula^oy
>Obabjmqflk%M^oq/&yOyAo^bkbfyy@yM^i^afkyyKyGli%05+-)5/+-&yyNFAy63--yyWyQebBula^oy

QLkqebTfkdplc^EfmmldovmeyKyKrodrkf%24)16&yyWyQebBula^oyyNFAy63-1y
>EfmmldovmeJ^pqboPqbme^klpyKyKrodrkf%24)16&yyWyQebBula^oyyNFAy63-2y
Q@lkqoliyKy?^qf%13)30&yy@yJ^dbyyWyQebBula^oyyNFAy6262y
Q@^iilcCfob%M^oq2&y@yPe^j^kyyWyQebBula^oyyKyMolmebqSbibk%0/+4)21+2&yyNFAy613.y
>@^iilcCfob%M^oq3&y@yPe^j^kyyWyQebBula^oyyKyMolmebqSbibk%0/+4)21+2&yyNFAy6222y
Q@^iilcCfob%M^oq3&y@yPe^j^kyyWyQebBula^oyyKyC^opbboKl_rkal%0-)0-&yyNFAy6222y
Q?belj^qy@yT^oofloyyWyQebBula^oyyKy?belj^q%22)5/&yyNFAy.-02-y
QEfmmldovmeJ^pqboPqbme^klpyKyPqbme^klp%35+3)30+0&yyWyQebBula^oyyNFAy63-2y
>ObqrokqlQlmeboIl^^iyKyPqbme^klp%35+3)30+0&yyWyQebBula^oyyNFAy63-3y
C?illaT^q`eyKyPqbme^klp%35+3)30+0&yyWyQebBula^oyyNFAy6360y
QObqrokqlQlmeboIl^^iyKy@^obdfsboQlmeboIl^^i%22+5)26+4&yyNFAy63-3y

QObmloqqlBu^o`e>ajbqfrpyKyBu^o`e>ajbqfrp%2/+4)20+0&yyNFAy6335y
>Te^q>odrpJb^kpqlJbyKyBu^o`e>ajbqfrp%2/+4)20+0&yyNFAy6360y
>Ib^okfkdcoljqeb@ovpq^ipyKyE^o_fkdboJfhli^^p%2/+4)20+0&yyNFAy625.y
QP^sfkdMofk`bppPqfiimfkbyKyPqfiimfkb>j_^pp^aloCo^p^_ll%22+/)23+/&yyNFAy6334y
QTe^q>odrpJb^kpqlJbyKySfkaf`^qlo?lolp%22+1)22+0&yyNFAy6360y
>?illaT^q`eyKySfkaf`^qlo?lolp%22+1)22+0&yyNFAy6361y

@?illaT^q`eyKyPi^v.-Prke^thPmfbptef`e`^k_bclrkaqlqebKloqelc?illaT^q`e^olrka%16)15&yyNFAy6361y

Q?illaT^q`eyKySfkaf`^qlo?lolp%22+1)22+0&yyNFAy6361y
>Fkqbo`bmqfkdqebJbpp^dbyKySfkaf`^qlo?lolp%22+1)22+0&yyNFAy6446y

@Obabjmqflk%M^oq/&yOyAo^bkbfyy@yM^i^afkyyKyRpbqebXPvj_lilcIfcbZqlobproob`qVlrkdCro_lidPe^j^k%32+/)44+3&yyNFAy63--yyRy3533y
KCfka^kX>nr^qf`PqfkhelokZyKy?bqtbbk%23+3)46+0&^ka%31+2)3/+1&+Eb^aplrqeb^pqqlqebpqob^j+Qebcfpeaolmfq^iplyyIy/1-1.yyNFAy6315y
@Ib^okfkdcoljqeb@ovpq^ipyKyRpbqebX@ovpq^iJfkfkdMf`hZqld^qeboqebp^jmibcoljqeb@ovpq^i^olrka%25)50&yyRy/0542yyNFAy625.y
@@^q`e^kaObib^pbyKyCfka^kvlcqeb?i^`hpfiqP`lrqplkqebPlrqebok@l^pq^olrka%2-)6.&^karpbqebXJroil`Q^ddboZrkqfinrbpqfp`ljmibqbyyRy/0662yyNFAy63/6y

Q@^q`e^kaObib^pbyKyJlo^b%20+0)24+4&yyNFAy63/6y
>Sf`qfjplc@loormqflkyKyJlo^b%20+0)24+4&yyNFAy6241y
>@orbicfk$pKb`hi^`byKyQebfqbjXOba@ovpq^iMbka^kqZpq^oqpnrbpq*aolmmba_v@orbicfkil`^qba_bqtbbk%01)6/&^ka%16)60&yyLyyRy/054-yyNFAy6243y
Q@orbicfk$pKb`hi^`byKyJlo^b%20+0)24+4&yyLyyNFAy6243y
QIb^okfkdcoljqeb@ovpq^ipyKyE^o_fkdboJfhli^^p%2/+4)20+0&yyNFAy625.y
>QebJfppfkdProsbvQb^jyKyE^o_fkdboJfhli^^p%2/+4)20+0&yyNFAy63/-y

KMf`hrmJrpeolljp^pvlrnrbpqyKyHbbm^kbvblrqcloqebjrpeolljpkbbabacloJ^`$>obbJrpeolljJbk^dbofbyyNFAy6315y

HQwbo^hyKyEb^aqlK^wwfsf^kqlqebplrqetbpq^kaillhclo^prjjlkfkd`fo`ib%05+10)5/+-.&+Fcebfpk$qqebobillhqlqebkloqe)eb$pobprjjlkba2jfkrqbp^cqboeb$phfiiba)^kaeb$iivbiitebkebfpprjjlkbayyIy/06--yyNFAy6261y
>PfdkplcqebIbdflkyRy/06--yyKyQebfqbjXQwbo^h$p>ojloMi^qbZpq^oqpnrbpq*aolmmba_vQwbo^hteljlsbp_bqtbbk%04)4-&^ka%04)5/&yyNFAy6261y
@HkltQefkbBkbjvyKyCfkaqebK^wwfsrpJlkrjbkq^kaobqofbsb^XK^wwfsrpJlkrjbkqDivmeZclrka^q%03)4.&+HfiiQwbo^hteldr^oapqebDivmefkloaboqldbqqebnrbpqPfdkplcqebIbdflkyyNFAy6234y
@PfdkplcqebIbdflkyKyHfii5K^wwfsrpP^qvo^kaCbiptlok^iiclrka^olrka%04)45&kb^o_vK^ww^sf^kyyNFAy6261y

KCfka^XCbi@lkbCrkdrpZyKy>olrkaK^wwfsf^kyyIy/1-10yyNFAy6315y

@Sf`qfjplc@loormqflkyKy@liib`q3mfb`bplcX@ovpq^iifwba?^ohZcoljqebQob^kqpproolrkafkdqeb^ob^qlqebPlrqelc?illaT^q`e^olrka%16)4-&yyNFAy6241y

QSf`qfjplc@loormqflkyKyJlo^b%20+0)24+4&yyNFAy6241y
QHkltQefkbBkbjvyKySfkaf`^qlo>^ibpf^%22+.)25+/&yyNFAy6234y
QPfdkplcqebIbdflkyKySfkaf`^qlo>^ibpf^%22+.)25+/&yyNFAy6261y
>@lkq^fkfkdqebQeob^qyKySfkaf`^qlo>^ibpf^%22+.)25+/&yyNFAy6236y

QQebJfppfkdProsbvQb^jyKyAo^bkbf@^oqldo^mebo%3-+1)15+3&yyNFAy63/-y
>P^is^dfkdqebA^q^yKyAo^bkbf@^oqldo^mebo%3-+1)15+3&yyNFAy63/5y
@P^is^dfkdqebA^q^yKyDbqqebXProsbvA^q^@ovpq^iZcoljqebTo^qep`^ibkb^oqebab^a`^oqldo^mebop)fqfpaolmmba_vTo^qep`^ibPlo`bobpp^olrka%3.)10&yyNFAy63/5y

KCfka^XOrfklrpMlivpmlobZyKy>olrkap^jb^ob^%3.)10&yyIy/1-1/yyNFAy6315y
KCfka^X?illaJrpeolljZyKy>iilsbo_bqtbbkqebOrfkplcIlobqe$>o^k%3/+5)26+5&^kaK^wwfsf^k%13+4)43+4&yyIy/1-1-yyNFAy6315y

QP^is^dfkdqebA^q^yKyE^o_fkdboJfhli^^p%2/+4)20+0&yyNFAy63/5y
>QebPb`lkaP^jmibyKyE^o_fkdboJfhli^^p%2/+4)20+0&yyNFAy6251y
QJ^`$>obbJrpeolljJbk^dbofbyKyGbppbo^lcJ^`$>obb%23+0)23+4&yyNFAy6315y
>Vpbo^$pQb^opyKyGbppbo^lcJ^`$>obb%23+0)23+4&yyNFAy6316y
>@lkpqof`qloSfkbpyKyQo^`hboIv`blk%22+5)24&yyNFAy6310y
>Qeb?b^oKb`bppfqfbpyKyQo^`hboIv`blk%22)24&yyNFAy625-y

@QebPb`lkaP^jmibyKyRpbqebX@ovpq^iJfkfkdMf`hZqld^qebo^p^jmibcoljqeb@ovpq^i^q%12)14&^olrkaqebPrke^th@^jmpyyRy/0543yyNFAy6251y
@Fkqbo`bmqfkdqebJbpp^dbyKyDbqqebXPrke^thJfppfsbZtef`eaolmpcoljqebPrke^thJl_p^olrka%15)15&yyNFAy6446y

QFkqbo`bmqfkdqebJbpp^dbyKySfkaf`^qlo?lolp%22+1)22+0&yyNFAy6446y
>Qo^kpi^qflkp+++yKySfkaf`^qlo?lolp%22+1)22+0&yyNFAy6363y
QQo^kpi^qflkp+++yKyFkqboold^qloBivpf^%21+2)21+2&yyNFAy6363y
>>rafbk`btfqeqebMolmebqyKyFkqboold^qloBivpf^%21+2)21+2&yyNFAy6365y
CQebBula^oyKyI^^kal%24+3)21&yyNFAy6366y
QObabjmqflk%M^oq/&yOyAo^bkbfyy@yM^i^afkyyKyGli%05+-)5/+-&yyNFAy63--yyWyQebBula^oy
Q>rafbk`btfqeqebMolmebqyKyMolmebqSbibk%0/+4)21+2&yyWyQebBula^oyyNFAy6365y
>QorqeloCf`qflkyKyMolmebqSbibk%0/+4)21+2&yyWyQebBula^oyyNFAy6366y
C?illaT^q`eyKyPqbme^klp%35+3)30+0&yyNFAy64--y
QQorqeloCf`qflkyKySfkaf`^qlo?lolp%22+1)22+0&yyNFAy6366y
>FPellqJ^df`FkqlqebA^ohkbppyKySfkaf`^qlo?lolp%22+1)22+0&yyNFAy64--y

QQebPb`lkaP^jmibyKyE^o_fkdboJfhli^^p%2/+4)20+0&yyNFAy6251y
>QebCfk^iP^jmibyKyE^o_fkdboJfhli^^p%2/+4)20+0&yyNFAy6252y
>T>KQBA7Ab^qe`i^tyKyT^kqbaMlpqbo%22+/)26+.&yyNFAy6313y

>QebJfppfkdBumbafqflkyKy>`ebirp%20+0)24&yyNFAy6336y
KRodbkqAbifsbovyKyQ^ihqlJbppbkdboEbojbpfrp)ebt^kabop^_lrq?illaT^q`e+Qebk`eb`hvlroj^ficlo^nrbpq*pq^oqfkdfqbj+Vlr`^kklqdbqqefpnrbpqfcvlrafaklqal>ajfo^iLabpvrp$nrbpqpfk>wrobjvpqyyIy/1.0/yyNFAy.--30y
>Qeb?illa`ropbIbd^`vyKyMf`hrmX>Ibqqbocoljqeb>ajfo^iZqlpq^oqnrbpqyyRy/1.0/yyLyyNFAy634/y
>Bumilobop$Ib^drb)FpQe^qPljbqefkdcloDkljbp<yKyMolpmb`qloK^`ei^k%23+0)21+0&yyNFAy.--30y

KHfii^pvlrqo^sbi++yKyHfii^kvBiabo?oltk?b^op^kaJrq^qba@lkpqof`qlopvlr`ljb^`olppcloQeb?b^oKb`bppfqfbp^ka@lkpqof`qloSfkbpyyNFAy625-y

QBumilobop$Ib^drb)FpQe^qPljbqefkdcloDkljbp<yKy@ilmmboTfw_^kd%1/)/.+.&yyNFAy.--30y
>MficbobaBnrfmjbkqyKy@ilmmboTfw_^kd%1/)/.+.&yyNFAy6215y
>>oqfc^`qplcqeb?i^`hpfiqyKy@ilmmboTfw_^kd%1/)/.+.&yyNFAy6216y
@MficbobaBnrfmjbkqyKyD^qeboX@ilmmbo$pBnrfmjbkqZ^olrka%1-)/-&^ka%13)/-&fq`^k_bclrka^q^kvo^kaljjroil`erqp^olrkaqeb`l^pqyyNFAy6215y
@>oqfc^`qplcqeb?i^`hpfiqyKy?ofkd0X@orabJroil`FalipZ^ka3X@orabJroil`HkfsbpZtef`e`^k_bd^qebobacoljqebJroil`p^ilkdqeb_b^`e^q%06)/.&yyNFAy6216y
QMficbobaBnrfmjbkqyKy@ilmmboTfw_^kd%1/)/.+.&yyNFAy6215y
Q>oqfc^`qplcqeb?i^`hpfiqyKy@ilmmboTfw_^kd%1/)/.+.&yyNFAy6216y
>>J^mqlTebob<yKyMf`hrmXTb^qebobaQob^probJ^mZqlpq^oqnrbpqyyRy/0504yyNFAy622-y

@Qeb?b^oKb`bppfqfbpyKyD^qebo5XBiabo?oltk?b^oCi^khpZcoljqeb_b^opgrpqKloqelcqeb@vol@lob^olrka%03)16&yyNFAy625-y
@@lkpqof`qloSfkbpyKyD^qebo3XQelokv@lkpqof`qloSfkbpZtef`e`^k_billqbacoljqebJrq^qba@lkpqof`qloptef`eproolrkaqebcfbiap^olrkaqeb@vol@lob^q^_lrq%04)2-&yyNFAy6310y

@FPellqJ^df`FkqlqebA^ohkbppyKyPi^v2Slfa>klj^ifbpclrka^olrkaqebT^omMfpqlk^q%2.)/1&yyNFAy64--y

>ObpqlofkdP^k`qfqvyKyMofk`bQlobqe%41)01&yyNFAy6354y

@ObpqlofkdP^k`qfqvyKyOb`lsbo5XAo^dlk?lkbpZclrka^olrkaqebTfiahfk`^jmp^q%22)02&yyNFAy6354y
Q>J^mqlTebob<yKy?^qqboba>k`fbkq?llh%3.+/)1.+5&yyNFAy622-y
>Ab`fmebofkdqeb?llhyKy?^qqboba>k`fbkq?llh%3.+/)1.+5&yyNFAy6224y

QAb`fmebofkdqeb?llhyKy>k`elofqbM^bqebrp%21+4)21&yyNFAy6224y
>Klih^f$pTloapyKy>k`elofqbM^bqebrp%21+4)21&yyNFAy623.y
QFPellqJ^df`FkqlqebA^ohkbppyKySfkaf`^qlo?lolp%22+1)22+0&yyNFAy64--y
>Qeb@ovl*@lobyKySfkaf`^qloHrolp%22+3)22+1&yyNFAy64-0y
QQeb?b^oKb`bppfqfbpyKyQo^`hboIv`blk%22)24&yyNFAy625-y
Q@lkpqof`qloSfkbpyKyQo^`hboIv`blk%22)24&yyNFAy6310y
>@riifkdqebCirqqbobopyKyQo^`hboIv`blk%22)24&yyNFAy6314y
>Pb^o`efkdcloD^i^bkyKyJlo^b%20+0)24+4&yyNFAy6245y

KHfiicirqqbo_vp^pvlrnrbpqyKyHfii^kvOlv^i?irbCirqqbobopvlr`ljb^`olppclo@riifkdqebCirqqbobopyyNFAy6314y

QPb^o`efkdcloD^i^bkyKyD^i^bk$p@lompb%04+2)3.+0&yyNFAy6245y
>D^i^bk$pC^qbyKyD^i^bk$p@lompb%04+2)3.+0&yyNFAy6246y
>D^i^bk$pGlrok^i*QebC^qblcSfkaf`^qloP^or^kyKyD^i^bk$pGlrok^i%04+2)3.+1&yyNFAy64-3y
@D^i^bk$pC^qbyKyQebPrke^thOb`i^fjboptef`eproolrkaqeb@vol@lob%04)3-&tfiiaolmXD^i^bk$p>jribqZ+Aolmo^qbfpobi^qfsbivilt_rqhfiipdfsbab`bkqUMcoljdofkafkdyyNFAy6246y
@Qeb@ovl*@lobyKyD^qebo./_lubplcXJbaf`^iPrmmifbpZtef`eproolrkaqeb@vol@lob%03)3-&loillqqebjcoljqebkb^o_vPrke^thjl_pyyNFAy64-0y

QD^i^bk$pC^qbyKyJlo^b%20+0)24+4&yyNFAy6246y
QQeb@ovl*@lobyKySfkaf`^qloHrolp%22+3)22+1&yyNFAy64-0y
QD^i^bk$pGlrok^i*QebC^qblcSfkaf`^qloP^or^kyKySfkaf`^qloHrolp%22+3)22+1&yyNFAy64-3y
>J^qfpqeb@orbiyKySfkaf`^qloHrolp%22+3)22+1&yyNFAy64..y
>Alk$qAofkhqebT^qboyKySfkaf`^qlo>bplj%22)22&yyNFAy6415y
>Te^qTbHklt+++yKySfkaf`^qlo>bplj%22)22&yyOyAo^bkbfyyNFAy6420y
QTe^qTbHklt+++yKyBu^o`e>ajbqfrp%2/+4)20+0&yyOyAo^bkbfyyNFAy6420y
>Te^qTbAlk$qHklt+++yKyBu^o`e>ajbqfrp%2/+4)20+0&yyOyAo^bkbfyyNFAy6423y
@Te^qTbAlk$qHklt+++yOyAo^bkbfyyKyPmb^hql^@^mqrobaPrke^th>dbkq%21)21&fkpfab^@^db^q?illaT^q`eyyNFAy6423y
QTe^qTbAlk$qHklt+++yKyBu^o`e>ajbqfrp%2/+4)20+0&yyOyAo^bkbfyyNFAy6423y
>Sfkaf`^qlo$pObpqyKyBu^o`e>ajbqfrp%2/+4)20+0&yyOyAo^bkbfyyNFAy643-y
>Q^ihqlqebE^kayKyE^o_fkdboJfhli^^p%2/+4)20+0&yyNFAy.--31y
>ClribaT^qboPmfofqpyKyAbcbkabo>aofbiib%2.)2/&yyNFAy.--34y
>Le)qebQ^kdibaTb_pQebvTb^sbyKyAbcbkaboPloif%22+2)2/+0&yyNFAy.--33y

@QebCfk^iP^jmibyKyRpbqebX@ovpq^iJfkfkdMf`hZqld^qeboqebp^jmibcoljqeb`ovpq^i^q%1.)/6&_befka>uu^of^kyyRy/0544yyNFAy6252y
@@lkq^fkfkdqebQeob^qyKyHfii2>uu^ofbkPe^altpq^ihbop^ka2>uu^ofbkEbii`^iibop^olrka%04)03&tfqefk>uu^ofbk+>iplhfiiWbso^uil`^qbafkcolkqlc^pj^iimvo^jfa^q%1.+3)/6+5&yyNFAy6236y

@J^qfpqeb@orbiyKyQefpfp^kb^pvdolrmnrbpqtebobvlrjrpqlkivbkd^dbtfqeJ^qfpqeb@orbitelm^qolip^ilkdqebm^qeqlSb`qlo@lfi_bqtbbk%//)20&^ka%1.)11&+RpbqebXCi^obDrkZql`ljmibqbqebnrbpqyyRy/1/45yyNFAy64..y

QQ^ihqlqebE^kayKyP`lrqGloif%0-+/)12+5&yyNFAy.--31y
>@rqqfkd^M^qeyKyP`lrqGloif%0-+/)12+5&yyNFAy.--32y
>@ofqqboplcqebSlfayKyP`lrqIlovf%0-+0)13&yyNFAy641.y
QSfkaf`^qlo$pObpqyOyAo^bkbfyyKySfkaf`^qlo@lofk%0-+/)13+6&yyNFAy643-y

KHfii^pvlrqo^sbiyKyHfii^kvJrq^qbaQ^kdibop^kaBko^dbaO^s^dbopvlr`ljb^`olppcloLe)qebQ^kdibaTb_pQebvTb^sb^ka@rqqfkd^M^qeyyNFAy.--33y

>Qebv$ob>ifsbJ^v_b+++yKyObpb^o`ebo@lokbifrp%/1)01&yyNFAy634-y
@Qebv$ob>ifsbJ^v_b+++yKyCobb2BumbafqflkObpb^o`ebop^olrka%/.)02&yyNFAy634-y
@QebJfppfkdBumbafqflkyKyHfii5JvpqPmfkkbop^kaIbb`ebop^iiclrkaqeolrdelrqqeb>j_botb_M^pp^olrka%//)04&+W^o^hefp^qqebqlmlcqebM^pp^olrka%.5)04&yyNFAy6336y
QQebv$ob>ifsbJ^v_b+++yKyObpb^o`ebo@lokbifrp%/1)01&yyNFAy634-y

@ClribaT^qboPmfofqpyKyHfii3ClribaT^qboPmfofqp^olrka%0-)06&yyNFAy.--34y
@Alk$qAofkhqebT^qboyKyQo^sbiqlqeb_lqqljlcqebt^qboc^ii^q%01+1)00+2&fkloaboqlcfiiqebXT^qboP^jmibCi^phZyyRy/10.5yyNFAy6415y
@T>KQBA7Ab^qe`i^tyKyCfka^kahfiiAb^qe`i^tTbpqlcqebKloqebokjroil``^jmp^olrka%04)0-&yyNFAy6313y

QKlih^f$pTloapyKyJlrkalcAfoq%3.+/)16+1&yyNFAy623.y

QObpqlofkdP^k`qfqvyKyMofk`bQlobqe%41)01&yyNFAy6354y
>FkqlqebAob^jyKyMofk`bQlobqe%41)01&yyNFAy6355y
KJlobpeolljp+++yKyHbbm^kbvblrqlkTvojp`^oFpi^kacloVpbo^$pQb^opyyNFAy6316y
@FkqlqebAob^jyKyHfii2Sbofaf^kTebimp^ka?ollaifkdpclrkaqeolrdelrqTvojp`^oFpi^ka^olrka%40)0-&yyNFAy6355y
QQeb?illa`ropbIbd^`vyKy@^mq^fkBat^oaE^kbp%46+.)//+4&yyNFAy634/y
>Qeb?illa`ropbaK^d^yKy@^mq^fkBat^oaE^kbp%46+.)//+4&yyNFAy6341y
@Qeb?illa`ropbaK^d^yKyHfii.-?illa`ropbaK^d^^olrka%5.)/1&b^pqlcTvojp`^oFpi^kayyLyyNFAy6341y
QQeb?illa`ropbaK^d^yKy@^mq^fkBat^oaE^kbp%46+.)//+4&yyNFAy6341y
>QebElmbibppLkbp+++yKy@^mq^fkBat^oaE^kbp%46+.)//+4&yyNFAy635/y
@QebElmbibppLkbp+++yKyOb`lsbo1?illa`ropbaPlripcoljqeb?illa`ropbjl_pm^pqqebK^d^^olrka%53).1&yyNFAy635/y
KObcobpeQeb@^mq^fk$pHfppyKyQ^ihqlqebqrokfkKM@^kae^sbefjob`^pqqebpmbiilkvlr)fq$iiebimcloqo^sbifkdqlqebkbuqm^oqyyNFAy6355y
QQebElmbibppLkbp+++yKy@^mq^fkBat^oaE^kbp%46+.)//+4&yyNFAy635/y
>Bkafkdqeb?illa`ropbyKy@^mq^fkBat^oaE^kbp%46+.)//+4&yyNFAy6350y
QFkqlqebAob^jyKyMofk`bQlobqe%41)01&yyNFAy6355y
@Bkafkdqeb?illa`ropbyKy?^peqebpq^qrblkqlmlcqebefiilkqebfpi^ka^q%52)21&fkloaboqlpm^tk>qlmeqeb?illa`ropbatelvlrjrpqhfiiyyNFAy6350y
QBkafkdqeb?illa`ropbyKy@^mq^fkBat^oaE^kbp%46+.)//+4&yyNFAy6350y

@Vpbo^$pQb^opyKyD^qebo/XVpbo^$pQb^opZtef`e`^k_bclrkapmob^aqeolrdelrqTvojp`^oFpi^ka^olrka%42).6&^ka%43)/1&yyNFAy6316y

E?illaT^q`eyRy3615yyNFAy6413y
Q@lkq^fkfkdqebQeob^qyKySfkaf`^qlo>^ibpf^%22+.)25+/&yyNFAy6236y
QQebJfppfkdBumbafqflkyKy>`ebirp%20+0)24&yyNFAy6336y
QT>KQBA7Ab^qe`i^tyKyE^o_fkdboJfhli^^p%2/+4)20+0&yyNFAy6313y
QQebCfk^iP^jmibyKyE^o_fkdboJfhli^^p%2/+4)20+0&yyNFAy6252y
QAlk$qAofkhqebT^qboyKySfkaf`^qlo>bplj%22)22&yyNFAy6415y
>IfjfqplcMevpf`^iBue^rpqflkyKySfkaf`^qlo>bplj%22)22&yyNFAy6413y
QJ^qfpqeb@orbiyKySfkaf`^qloHrolp%22+3)22+1&yyNFAy64..y
QVpbo^$pQb^opyKyGbppbo^lcJ^`$>obb%23+0)23+4&yyNFAy6316y

@IfjfqplcMevpf`^iBue^rpqflkyKyPi^v.-Prke^thMvolj^k`bop^kaAbcbkabopclrka^olrkaqebSb`qlo@lfi^q^_lrq%//)3.&yyNFAy6413y

QIfjfqplcMevpf`^iBue^rpqflkyKySfkaf`^qlo>bplj%22)22&yyNFAy6413y
>QebPrkD^qbyKySfkaf`^qlo>bplj%22)22&yyNFAy641-y

@QebPrkD^qbyKyCfkaqebmlliqlqebPlrqelcSb`qlo@lfi^olrka%/-)3/&^kaabpqolvqebPrkD^qbyyNFAy641-y
@@ofqqboplcqebSlfayKySlfa@ofqqbop`^k_bclrkapm^tkfkd^olrka^pj^iimlka^q%.5)30&yyNFAy641.y

@Le)qebQ^kdibaTb_pQebvTb^sbyKyHfii5Jrq^qbaQ^kdibop^olrka%0-)24&grpqlrqpfabqebSb`qlo@lfiyyNFAy.--33y
@@rqqfkd^M^qeyKyHfii.-Bko^dbaO^s^dbopclrkalrqpfabqebSb`qlo@lfi^olrka%0-)24&yyNFAy.--32y

QLe)qebQ^kdibaTb_pQebvTb^sbyKySfkaf`^qlo@lofk%0-+/)13+6&yyNFAy.--33y
Q@rqqfkd^M^qeyKyP`lrqGloif%0-+/)12+5&yyNFAy.--32y
QClribaT^qboPmfofqpyKySfkaf`^qlo@lofk%0-+/)13+6&yyNFAy.--34y

KQovql`ljmibqbBkaqebfotloiayKyFq$ptloqeqovfkdqefpnrbpqlk`b)fcvlrc^figrpq^_^kalkfq+J^hbprobvlrdo^_@ib^ofkdqebT^vcfopq)^pvlr$iiifhbiv`ljmibqbfq^ilkdqebt^v+Fcvlr$ob^eb^ifkd`i^ppqovqlibqefjq^khjl_p^kaeb^iefjfckbbabayyNFAy6314y

@@riifkdqebCirqqbobopyKyHfii.-Olv^i?irbCirqqbobopproolrkaqebcfbiap^olrkaqeb@vol@lob^q^_lrq%04)2-&yyNFAy6314y

QQebPrkD^qbyKySfkaf`^qlo>bplj%22)22&yyNFAy641-y
Q@ofqqboplcqebSlfayKySfkaf`^qlo>bplj%22)22&yyNFAy641.y
Q@riifkdqebCirqqbobopyKyQo^`hboIv`blk%22)24&yyNFAy6314y
>Kbtclrka>iifbpyKy>k`elofqbM^bqebrp%21+4)21&yyNFAy630/y

CQebBula^oyKyI^^kal%24+3)21&yyNFAy6300y

QKbtclrka>iifbpyKyErkqobppHbii^Kfdeq_lt%/1+/)21+/&yyWy>wrobjvpqFpibyyNFAy630/y
>QebT^vql>r_boafkbyKyErkqobppHbii^Kfdeq_lt%/1+/)21+/&yyWy>wrobjvpqFpibyyNFAy6300y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
