DugisGuideViewer:RegisterGuide("Loch Modan (17-18)", "Redridge Mountains (18-20)", "Alliance", "L", function()
return [[
AAA

_Pqlojtfka@fqvyKyQ^hbqeb?l^qqlPqlojtfka@fqv%0/+1)10+3&yyWyA^ohpelobyyNFAy0-4y
cPqlojtfka@fqvyKyArkd^oIlkdaofkh%4.)4/+3&yyWyPqlojtfka@fqvyyNFAy0-4y
CIl`eJla^kyKyArkd^oIlkdaofkh%4.)4/+3&yyOyErj^k)At^oc)DkljbyyWyPqlojtfka@fqvyyNFAy0-4y
>Pqlojmfhb$pAbifsbovyKyDofj^kaBijlob%26+4)01&yyWyPqlojtfka@fqvyyOyKfdeqBic)Ao^bkbfyyNFAy020y
OAbbmorkQo^jyKyFkqebAt^osbkAfpqof`q%4-+0)/6+2&yyOyKfdeqBic)Ao^bkbfyyWyPqlojtfka@fqvyyNFAy0-4y
KQ^hbqebqo^jqlFolkclodbyNFAy0-4yyOyKfdeqBic)Ao^bkbfy
O@fqvlcFolkclodbyNFAy0-4yyOyKfdeqBic)Ao^bkbfy
C@fqvlcFolkclodbyKyFkqeb`bkqbolcqltk^qqebClodb%22+22)14+43&yyWyFolkclodbyyOyKfdeqBic)Ao^bkbfyyNFAy0-4y
OArkJloldeyKyOrkqlArkJlolde%.1)53&yyWyArkJloldeyyOyKfdeqBic)Ao^bkbfyyNFAy0-4y
OIl`eJla^kyKyQ^hbqebol^ab^pq)qebkkloqe%51+4)/6+3&qeolrdeqebqrkkbiyyWyArkJloldeyyOyKfdeqBic)Ao^bkbfyyNFAy0-4y
QPqlojmfhb$pAbifsbovyKyJlrkq^fkbboPqlojmfhb%/1+4).5+0&yyNFAy020yyOyAt^oc)Dkljb)KfdeqBic)Ao^bkbfy

>CfiqevM^tpyKyJlrkq^fkbboPqlojmfhb%/1+4).5+0&yyNFAy0-4y
>Pqlojmfhb$pLoaboyKyJlrkq^fkbboPqlojmfhb%/1+4).5+0&yyNFAy.005y
@CfiqevM^tpyKyQo^sbiqlqeb`^sbbkqo^k`b^q%02)/-&^kaqebkdlfkpfabqeb`^sbqllmbkqeb`o^qbppmob^aqeolrdelrqql`liib`q1il^aplcXJfkbop$Db^oZ%03)/1&yyNFAy0-4y
QCfiqevM^tpyKyJlrkq^fkbboPqlojmfhb%/1+4).5+0&yyNFAy0-4y
OQebip^j^oyKyQelodorj?loobiplk%00+6)2-+6&yyNFAy103y
cQebip^j^oyKyQelodorj?loobiplk%00+6)2-+6&yyOyKfdeqBic)Ao^bkbfyyNFAy103y
>Folk_^ka$pBu`^s^qflkyKyGbokElokebij%04+/)14+2&yyNFAy103y

QFolk_^ka$pBu`^s^qflkyKyJ^dj^oCbiiebt%31+6)33+3&yyNFAy103y
>D^qebofkdFalipyKyJ^dj^oCbiiebt%31+6)33+3&yyNFAy/64y
>Bu`^s^qflkMoldobppObmloqyKyMolpmb`qloFolk_^ka%32+5)32+3&yyNFAy/65y
@D^qebofkdFalipyKyQo^sbiqlqebBu`^s^qflkPfqb^q%35)30&^kahfii^kvlcqebQolddloPqlkbpmifqqbojl_pqebobql`liib`q5X@^osbaPqlkbFalipZyyNFAy/64y
QD^qebofkdFalipyKyJ^dj^oCbiiebt%31+6)33+3&yyNFAy/64y

OQebC^opqofaboIladbyKyB^pqlcBu`^s^qflkpfqb%50+5)3/+1&yyNFAy052y
>@ol`lifphErkqfkdyKyJ^obhFolkeb^oq%5.+5)3.+4&yyNFAy052y
>>Erkqbo$p?l^pqyKyA^oviqebVlrkdifkd%50+1)32+0&yyNFAy/24y
@>Erkqbo$p?l^pqyKyQebJlrkq^fk?rww^oapobnrfoba`^k_bclrkapmob^a^ilkdqebPlrqeb^pq`lokbolcIl`eJla^k^olrka%43)4/&+Hfii3ql`ljmibqbqebnrbpqyyNFAy/24y
Q>Erkqbo$p?l^pqyKyA^oviqebVlrkdifkd%50+1)32+0&yyNFAy/24y
>>Erkqbo$p@e^iibkdbyKyA^oviqebVlrkdifkd%50+1)32+0&yyNFAy/25y
@>Erkqbo$p@e^iibkdbyKyHfii2BiaboJlrkq^fk?l^optef`e^obclrkapmob^aqeolrdelrqqeb`bkqo^ib^pqbok^ob^^olrka%32)06&yyNFAy/25y
Q>Erkqbo$p@e^iibkdbyKyA^oviqebVlrkdifkd%50+1)32+0&yyNFAy/25y
>Svofk$pObsbkdb%M^oq.&yKySvofkPtfcqtfka%5.+5)31+.&yyNFAy/4.y
>?fkdibp$JfppfkdPrmmifbpyKy?fkdibp?i^pqbkebfjbo%30+2)14+6&yyNFAy/-05y
@@ol`lifphErkqfkdyKyHfiiIl`e@ol`lifphpclrkafkqebqebi^hb^olrka%24)05&rkqfivlr$sb`liib`qba2mfb`bplcX@ol`lifphJb^qZ^ka3X@ol`lifphPhfkpZyyNFAy052y
@?fkdibp$JfppfkdPrmmifbpyKyCfka^ka`liib`qX?fkdibp$Tobk`eZ%16)0-&)X?fkdibp$P`obtaofsboZ%15)/-&)X?fkdibp$E^jjboZ%2/)/1&^kaX?fkdibp$?i^pqbk`^mmboZ%21)/4&yyNFAy/-05y

>>A^ohQeob^qIlljp%M^oq.&yKy@efbcBkdfkbboEfkabotbfoSFF%13).0+4&yyNFAy/2-y
Q>A^ohQeob^qIlljp%M^oq.&yKyPrpmf`flrp?^oobi%23+.).0+/&yyNFAy/2-y
>>A^ohQeob^qIlljp%M^oq/&yKyPrpmf`flrp?^oobi%23+.).0+/&yyNFAy.66y
Q>A^ohQeob^qIlljp%M^oq/&yKy@efbcBkdfkbboEfkabotbfoSFF%13).0+4&yyNFAy.66y

QBu`^s^qflkMoldobppObmloqyKyGbokElokebij%04+/)14+2&yyNFAy/65y
>ObmloqqlFolkclodbyKyGbokElokebij%04+/)14+2&yyNFAy0-.y
@Svofk$pObsbkdb%M^oq.&yKyQo^sbiqlqebpq^oqlcqebJlrkq^fkm^qe^q%1-)35&qebkqlqebqlmrkqfivlrob^`eqeb`^sb^q%04)3/&tebobvlr$iicfkaLi$Pkllqvtelvlrjrpqhfiiqlillqefpeb^a+Qb^jfkdrmtfqe^klqebopelriaebimj^hbqefpnrbpqb^pfboyyNFAy/4.y

Q@ol`lifphErkqfkdyKyJ^obhFolkeb^oq%5.+5)3.+4&yyNFAy052y
QSvofk$pObsbkdb%M^oq.&yKyA^oviqebVlrkdifkd%50+1)32+0&yyNFAy/4.y
>Svofk$pObsbkdb%M^oq/&yKyA^oviqebVlrkdifkd%50+1)32+0&yyNFAy20.y
QSvofk$pObsbkdb%M^oq/&yKySvofkPtfcqtfka%5.+5)31+.&yyNFAy20.y
Q?fkdibp$JfppfkdPrmmifbpyKy?fkdibp?i^pqbkebfjbo%30+2)14+6&yyNFAy/-05y

C@fqvlcFolkclodbyKyQelodorj?loobiplk%00+6)2-+6&y
QObmloqqlFolkclodbyKyMolpmb`qloPqlojmfhb%41+2)./+.&yyWyFolkclodbyyNFAy0-.y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
