DugisGuideViewer:RegisterGuide("Darkshore (20-22)", "Ashenvale (22-25)", "Alliance", "L", function()
return [[
AAA

E>r_boafkbyRy3615yyNFAy..00y
>Lkt^oaql>pebks^ibyKyQerkaofpTfkatb^sbo%04+1)1-+/&yyNFAy.-42/y
QLkryKyLkr%10+2)43+0&yyNFAy615y
>QebJ^pqbo$pDi^fsbyKyLkr%10+2)43+0&yyNFAy611y
@QebJ^pqbo$pDi^fsbyKyQo^sbiplrqecoljqebDolsblc>k`fbkqpfkqlQebJ^pqbo$pDi^fsb^olrka%1-)53&rkqfivlr$sb`ljmibqbaqebnrbpqqebkrpbqebmolsfabaXMef^ilcP`ovfkdZyyRy2/2.yyNFAy611y
QQebJ^pqbo$pDi^fsbyKyP`ovfkd?lti%06)51&yyRy2/2.yyNFAy611y
>QebQtfifdeq@^jmyKyP`ovfkd?lti%06)51&yyNFAy616y
QQebQtfifdeq@^jmyKyQtfifdeqQljb%05+3)53+.&yyNFAy616y
>ObqrokqlLkryKyQtfifdeqQljb%05+3)53+.&yyNFAy62-y
>Qebovirkb$pBp`^mbyKyQebovirkb%05+4)54+1&yyNFAy612y
@Qebovirkb$pBp`^mbyKyBp`loqQebovirkbql%//+4)2.+6&yyNFAy612y

QQeb>_pbkqJfkabaMolpmb`qlo%M^oq.&yKyMolpmb`qloObjqo^sbi%02+40)50+36&yyNFAy4/6y
>Qeb>_pbkqJfkabaMolpmb`qlo%M^oq/&yKyMolpmb`qloObjqo^sbi%03)53&yyNFAy40.yy
@Qeb>_pbkqJfkabaMolpmb`qlo%M^oq/&yKyMolqb`qMolpmb`qloObjqo^sbi%03)53&^pebpb^o`ebpcloqebjvpqboflrpclppfiyyNFAy40.y
@T>KQBA7JrohabbmyKyCfka^kapi^vqebjroil`hkltk^pJrohabbm%03+22)43+20&yyNFAy141-y

QQeb>_pbkqJfkabaMolpmb`qlo%M^oq/&yKy>o`e^blildfpqEliib%04+2)1.+6&yyNFAy40.y
QT>KQBA7JrohabbmyKyPbkqfkbiDivka^K^i$Peb^%04+4)10+2&yyNFAy141-y
QObqrokqlLkryKyLkr%10+2)43+0&yyNFAy62-y
>QebPibbmboE^p>t^hbkbayKyHboilkf^kBsbope^ab%11+04)43+12&yyNFAy20/.y
KDbqefpelokyKyFkqeb_lukb^otebobebt^ppibbmfkd%11+3)43+1&yyIy.0203yyNFAy20/.y
@QebPibbmboE^p>t^hbkbayKyQefpfp^kbp`loqnrbpqtebobvlrbp`loqHboilkf^kBsbope^abqlJ^bpqo^$pMlpq%/4)03&fk>pebks^ib+Vlrj^ve^sbqlrpbqebXEloklc>t^hbkfkdZqlt^hbefjrmyyRy.0203yyWy>pebks^ibyyNFAy20/.y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
