DugisGuideViewer:RegisterGuide("Darkshore (20-22 Draenei)", "Ashenvale (22-25)", "Alliance", "L", function()
return [[
AAA

_A^ohpelobyKyQ^hbqeb?l^qql>r_boafkb%/.+3)21&yyWy>wrobjvpqFpibyyNFAy..00y

e>r_boafkbyKyFkkhbbmboPe^rppfv%04)11+.&yyNFAy02/1y
>T^peba>pelob%M^oq.&yKyDtbkkvqe?iv$Ibddlkab%03+3)12+2&yyNFAy02/1y
>CorfqlcqebPb^yKyDr__bo?irjm%03+.)11+6&yyNFAy..05y
>@^sbJrpeolljpyKy?^ofqeo^pJllkpe^ab%04+0)10+4&yyNFAy614y
QQebT^vql>r_boafkbyKyQerkaofpTfkatb^sbo%04+1)1-+/&yyNFAy6300y
>QebQltbolc>iqe^i^uu%M^oq.&yKyPbkqfkbiBifpp^Pq^o_obbwb%06+.)10+2&yyNFAy632y

@T^peba>pelob%M^oq.&yKyCfkaqebPb^@ob^qrob^kaillqfqpobj^fkp^q%03)2-&yyNFAy02/1y
QT^peba>pelob%M^oq.&yKyDtbkkvqe?iv$Ibddlkab%03+3)12+2&yyNFAy02/1y
>T^peba>pelob%M^oq/&yKyDtbkkvqe?iv$Ibddlkab%03+3)12+2&yyNFAy135.y
@T^peba>pelob%M^oq/&yKyCfkaqebPb^Qroqib$p_lavfkqebt^qbopqlt^oapqeb_l^qp^q%0.)13&^kaillqfqpobj^fkpyyNFAy135.y
QT^peba>pelob%M^oq/&yKyDtbkkvqe?iv$Ibddlkab%03+3)12+2&yyNFAy135.y

@@^sbJrpeolljpyKyQo^sbiqlqeb`^sblkqebb^pqbokpfablcqeb@ifccpmofkdOfsboqlqeb`^sbbkqbo^k`b^q%22)02&+Qefpmi^`bfpproolrkaba_vK^d^b^`emi^`banrfqb`ilpbql^klqebopl^ddolqljlobqe^qlkbK^d^fpsbovb^pvqlj^hb_v^``fabkqpl_b`^obcrilcqebt^vvlrmrii+HfiiqebK^d^fkqeb`^sb^kadlqlqebjrpeolljppmob^aqeolrdelrqqeb^ob^rkqfivlr`liib`q2XP`^_boPq^ihpZ%22)01&^ka.XAb^qe@^mZ%23)02&+Qeb^ob^qlqebofdeqpelria_bqebb^pfbom^qeqlqo^sbialtkyyNFAy614y

QQebQltbolc>iqe^i^uu%M^oq.&yKy?^iqeribPe^altpqofhb%21+6)/1+6&yyNFAy632y
>QebQltbolc>iqe^i^uu%M^oq/&yKy?^iqeribPe^altpqofhb%21+6)/1+6&yyNFAy633y
@QebQltbolc>iqe^i^uu%M^oq/&yKy@liib`q1XTlokM^o`ejbkqpZtef`e^obaolmmbacoljqebA^ohPqo^kaC^k^qf`tef`eproolrkaQebQltbolc>iqe^i^uu^olrka%24)/4&yyNFAy633y
QQebQltbolc>iqe^i^uu%M^oq/&yKy?^iqeribPe^altpqofhb%21+6)/1+6&yyNFAy633y
>QebQltbolc>iqe^i^uu%M^oq0&yKy?^iqeribPe^altpqofhb%21+6)/1+6&yyNFAy634y
>?b^`ebaPb^Qroqib%M^oq.&yKy?b^`ebaPb^Qroqib%20+.3).5+.1&*^iplil`^qbafklqebo^ob^p^ilkdqeb`l^pqyyNFAy14/4y
@CorfqlcqebPb^yKyDbq3XCfkb@o^_@erkhpZtef`e^obaolmmbacljObbc@o^tibop^kaBk`orpqbaQfab@o^tibopclrkakb^oqeb_ofadb`olppfkdqeb@ifccpmofkdOfsbo^olrka%2.)//&yyNFAy..05y

>?b^`ebaPb^Qroqib%M^oq/&yKy?b^`ebaPb^Qroqib%11+.6)/-+33&*^iplil`^qbafklqebo^ob^p^ilkdqeb`l^pqyyNFAy14/2y
>?b^`ebaPb^@ob^qrobyKy?b^`ebaPb^@ob^qrob%1/)0/&*^iplil`^qbafklqebo^ob^p^ilkdqeb`l^pqyyNFAy14/0y

QCorfqlcqebPb^yKyDr__bo?irjm%03+.)11+6&yyNFAy..05y
Q@^sbJrpeolljpyKy?^ofqeo^pJllkpe^ab%04+0)10+4&yyNFAy614y
Q?b^`ebaPb^@ob^qrobyKyDtbkkvqe?iv$Ibddlkab%03+3)12+2&yyNFAy14/0y
Q?b^`ebaPb^Qroqib%M^oq.&yKyDtbkkvqe?iv$Ibddlkab%03+3)12+2&yyNFAy14/4y
Q?b^`ebaPb^Qroqib%M^oq/&yKyDtbkkvqe?iv$Ibddlkab%03+3)12+2&yyNFAy14/2y
>LkryKy?^ofqeo^pJllkpe^ab%04+0)10+4&yyNFAy615y
>T>KQBA7JrohabbmyKyT>KQBA7Jrohabbm%04+/)11+/&yyNFAy141-y
>Qeb>_pbkqJfkabaMolpmb`qlo%M^oq.&yKy>o`e^blildfpqEliibb%04+2)1.+5&yyNFAy4/6y
>Lkt^oaql>pebks^ibyKyQerkaofpTfkatb^sbo%04+1)1-+/&yyNFAy.-42/y

QLkryKyLkr%10+2)43+0&yyNFAy615y
>QebJ^pqbo$pDi^fsbyKyLkr%10+2)43+0&yyNFAy611y
@QebJ^pqbo$pDi^fsbyKyQo^sbiplrqecoljqebDolsblc>k`fbkqpfkqlQebJ^pqbo$pDi^fsb^olrka%1-)53&rkqfivlr$sb`ljmibqbaqebnrbpqqebkrpbqebmolsfabaXMef^ilcP`ovfkdZyyNFAy611yyRy2/2.y
QQebJ^pqbo$pDi^fsbyKyP`ovfkd?lti%06)51&yyRy2/2.yyNFAy611y
>QebQtfifdeq@^jmyKyP`ovfkd?lti%06)51&yyNFAy616y
QQebQtfifdeq@^jmyKyQtfifdeqQljb%05+3)53+.&yyNFAy616y
>ObqrokqlLkryKyQtfifdeqQljb%05+3)53+.&yyNFAy62-y
>Qebovirkb$pBp`^mbyKyQebovirkb%05+4)54+0&yyNFAy612y
@Qebovirkb$pBp`^mbyKyBp`loqQebovirkb%05+4)54+0&qebkpmb^htfqeQebovpfi%//+4)2.+6&^qqebPeofkblc>bppfk^yyNFAy612y

QQeb>_pbkqJfkabaMolpmb`qlo%M^oq.&yKyMolpmb`qloObjqo^sbi%02+4)50+4&yyNFAy4/6y
>Qeb>_pbkqJfkabaMolpmb`qlo%M^oq/&yKyMolpmb`qloObjqo^sbi%02+4)50+4&yyNFAy40.y
@Qeb>_pbkqJfkabaMolpmb`qlo%M^oq/&yKyMolqb`qMolpmb`qloObjqo^sbi%03)53&^pebpb^o`ebpcloqebjvpqboflrpclppfiyyNFAy40.y
@T>KQBA7JrohabbmyKyEb^aqlqeb`^jmcfobil`^qba^q%03+1)44+.&^kahfiiqebjroil`p+Jlobjroil`ptfiipm^tk+Hbbmhfiifkdjroil`prkqfiJrohabbm^mmb^op+HfiiJrohabbmql`ljmibqbqebnrbpqyyNFAy141-y

QObqrokqlLkryKyLkr%10+2)43+0&yyNFAy62-y
>QebPibbmboE^p>t^hbkbayKyHboilkf^kBsbope^ab%11)43&yyNFAy20/.y
KDbqefpelokyKyFkqeb_lukb^otebobebt^ppibbmfkd%11+3)43+1&yyIy.0203yyNFAy20/.y
@QebPibbmboE^p>t^hbkbayKyQefpfp^kbp`loqnrbpqtebobvlrbp`loqHboilkf^kBsbope^abqlJ^bpqo^$pMlpq%/4)03&fk>pebks^ib+Vlrj^ve^sbqlrpbqebXEloklc>t^hbkfkdZqlt^hbefjrmyyRy.0203yyWy>pebks^ibyyNFAy20/.y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
