DugisGuideViewer:RegisterGuide("Ashenvale (22-25)", "Wetlands (25-27)", "Alliance", "L", function()
return [[
AAA

QQebPibbmboE^p>t^hbkbayKyIfi^aofpJllkofsbo%/4+/)02+4&yyNFAy20/.y
QQebQltbolc>iqe^i^uu%M^oq0&yKyAbidobkqebMrofcfbo%/3+/)05+4&yyNFAy634y
>QebQltbolc>iqe^i^uu%M^oq1&yKyAbidobkqebMrofcfbo%/3+/)05+4&yyNFAy64-y
>?^qeo^k$pE^foyKyLobkafi?ol^aib^c%/3+1)05+3&yyNFAy.-.-y

@QebQltbolc>iqe^i^uu%M^oq1&yKy@liib`q^XDiltfkdPlriDbjZcolj^jbj_bolcQebA^ohPqo^ka)^olrka%0/)0-&yyNFAy64-y
@?^qeo^k$pE^foyKyDbq2lcX?^qeo^k$pE^foZclrkafkqebMi^kq?rkaibpfkqeb`^jmil`^qba^q%0.)//&yyNFAy.-.-y

QQebQltbolc>iqe^i^uu%M^oq1&yKyAbidobkqebMrofcfbo%/3+/)05+4&yyNFAy64-y
>QebQltbolc>iqe^i^uu%M^oq2&yKyAbidobkqebMrofcfbo%/3+/)05+4&yyNFAy640y
Q?^qeo^k$pE^foyKyLobkafi?ol^aib^c%/3+1)05+3&yyNFAy.-.-y
>Lobkafi$p@robyKyLobkafi?ol^aib^c%/3+1)05+3&yyNFAy.-/-y
QQebovirkb$pBp`^mbyKyQebovpfi%//+4)2.+6&yyNFAy612y

O>pqo^k^^oyKyCliiltqebol^ab^pq%04)16+0&yyNFAy.--5y
c>pqo^k^^oyKyA^bivpef^%01+2)15&yyNFAy.--5y
>QebWlo^jPqo^kayKyPefkaobiiPtfcqcfob%01+4)15+6&yyNFAy.--5y
QLkt^oaql>pebks^ibyKyO^bkbTlicorkkbo%03+3)16+3&yyNFAy.-42/y
>O^bkb$p@ib^kpfkd%M^oq.&yKyO^bkbTlicorkkbo%03+3)16+3&yyNFAy66.y
e>pqo^k^^oyKyFkkhbbmboHfjiv^%04)16+0&yyNFAy.-00y
QLobkafi$p@robyKyMbiqro^pTefqbjllk%04+0)2.+5&yyNFAy.-/-y
>Birkb$pQb^oyKyMbiqro^pTefqbjllk%04+0)2.+5&yyNFAy.-00y
>Qeb>k`fbkqPq^qrbqqbyKyQ^ibk%.1+5)0.+/&yyNFAy.--4y

@Qeb>k`fbkqPq^qrbqqbyKyCfkaqebX>k`fbkqPq^qrbqqbZlkqebWlo^jPqo^ka^q%.1+/)/-+3&yyNFAy.--4y
QQeb>k`fbkqPq^qrbqqbyKyQ^ibk%.1+5)0.+/&yyNFAy.--4y
>OrrwbiyKyQ^ibk%.1+5)0.+/&yyNFAy.--6y
@OrrwbiyKyHfiiI^avSbpmf^fkpqb^alcOrrwbifcvlr`^kcfkaebo+Peb$p^olrkaqebpb^ob^p%6).2&)%./).5&^ka%..)/6&^kaalbpk$qe^sbdr^oap_rq^iplaolmpqebofkd+Pebfpbifqb_rqfptb^hpl^kb^pvhfii+Fcklqcfka^kahfiiOrrwbitele^pqtldr^oap^ka`fo`ri^qbpqebfpi^ka^q%4).1&^ka`liib`qqebXOfkdlcWlo^jZyyNFAy.--6y
@QebWlo^jPqo^kayKyHfii^kvlcqebTo^qeq^fijl_ptef`eproolrkaQebWlo^jPqo^ka^q%.2)/1&rkqfivlr$sb`liib`qba/-XTo^qeq^fiEb^apZyyNFAy.--5y
QOrrwbiyKyQ^ibk%.1+5)0.+/&yyNFAy.--6y
QO^bkb$p@ib^kpfkd%M^oq.&yKyQbolkfp$@lompb%/-+0)1/+1&yyNFAy66.y
>O^bkb$p@ib^kpfkd%M^oq/&yKyQbolkfp$@lompb%/-+0)1/+1&yyNFAy.-/0y
@O^bkb$p@ib^kpfkd%M^oq/&yKyHfiiqebP^iqpmfqqibJroil`p^qqebkb^o_vi^hb^olrka%.6)10&rkqfivlr$sb`liib`qbaqebXDiltfkdDbjZyyNFAy.-/0y

E>pqo^k^^oyRy3615yyNFAy.-/1y
QO^bkb$p@ib^kpfkd%M^oq/&yKyO^bkbTlicorkkbo%03+3)16+3&yyNFAy.-/0y
>O^bkb$p@ib^kpfkd%M^oq0&yKyO^bkbTlicorkkbo%03+3)16+3&yyNFAy.-/1y
>>k>ddobppfsbAbcbkpbyKyO^bkbTlicorkkbo%03+3)16+3&yyNFAy.-/2y
QQebWlo^jPqo^kayKyPefkaobiiPtfcqcfob%01+4)15+6&yyNFAy.--5y
@Birkb$pQb^oyKyCfka^kaobqofsbXBirkb$pQb^oZkb^oqebi^hbil`^qba^q%13)13&yyNFAy.-00y
QO^bkb$p@ib^kpfkd%M^oq0&yKyPe^bi$aovk%20+2)13+0&yyNFAy.-/1y
>O^bkb$p@ib^kpfkd%M^oq1&yKyPe^bi$aovk%20+2)13+0&yyNFAy.-/3y

@>k>ddobppfsbAbcbkpbyKyHfii.AbkT^q`ebo)/Rop^p).-Qlqbjf`p)^ka./T^oofloplcqebClritb^iaqof_btef`e`^k_bclrkafkqeb`^jm^olrka%2.)3-&yyNFAy.-/2y

>Bibjbkq^i?o^`bopyKyPbkqfkbiSbibkbPq^opqofhb%16+5)34+/&yyNFAy.-.3y
H?bclribaT^qboBibjbkq^iyKyFkqebi^hbplrqelcPfisbotfkaObcrdb%16+1)4.+.&KbbaXFkq^`qBibjbkq^i?o^`bopZu2cloBibjbkq^i?o^`bopyyIy.///-2yyNFAy.-.3y
@Bibjbkq^i?o^`bopyKyHfiiqeb?bclribaT^qboBibjbkq^iptef`eproolrkaqebi^hb^q%16)4-&rkqfivlr$sb`liib`qba2XFkq^`qBibjbkq^i?o^`bopZtef`evlrqebkrpbtfqeqebXAfsfkfkdP`oliiZyyRy2123yyNFAy.-.3y
QBibjbkq^i?o^`bopyKyPbkqfkbiSbibkbPq^opqofhb%16+5)34+/&yyNFAy.-.3y

QBirkb$pQb^oyKyMbiqro^pTefqbjllk%04+0)2.+5&yyNFAy.-00y
>QebOrfkplcPq^oarpqyKyMbiqro^pTefqbjllk%04+0)2.+5&yyNFAy.-01y
Q>k>ddobppfsbAbcbkpbyKyO^bkbTlicorkkbo%03+3)16+3&yyNFAy.-/2y

@QebOrfkplcPq^oarpqyKy@liib`q2XE^kacriplcPq^oarpqZtef`e^obclrkafkPq^oarpq@lsboba?rpebptef`e^obfkqebOrfkplcPq^oarpq%01)34&yyNFAy.-01y

QQebOrfkplcPq^oarpqyKyMbiqro^pTefqbjllk%04+0)2.+5&yyNFAy.-01y
>C^iibkPhvI^hbyKyMbiqro^pTefqbjllk%04+0)2.+5&yyNFAy.-02y
>@riifkdqebQeob^qyKyO^bkbTlicorkkbo%03+3)16+3&yyNFAy.-21y

@QebQltbolc>iqe^i^uu%M^oq2&yKyDbqXFihoraJ^dqeorii$pQljbZaolmmba_vFihoraJ^dqeorii^q%/2)3.&yyNFAy640y
@@riifkdqebQeob^qyKyCfka^kahfiiA^i?illa`i^tm^qoliifkd^olrka%04)02&+Fcvlr`^kmriiefjplilfqtfii_b^kb^pvnrbpqyyNFAy.-21y

QQebQltbolc>iqe^i^uu%M^oq2&yKyAbidobkqebMrofcfbo%/3+/)05+4&yyNFAy640y
>QebQltbolc>iqe^i^uu%M^oq3&yKyAbidobkqebMrofcfbo%/3+/)05+4&yyNFAy..1-y

>Prmmifbpql>r_boafkbyKyCbbolFolke^ka%/3+/)05+5&yyNFAy643y
@Prmmifbpql>r_boafkbyKyQefpnrbpqfkslisbpbp`loqfkdCbbolFolke^ka^qkloj^imi^vboorkkfkd*pmbba^ilkdqebol^acoljJ^bpqo^$pMlpqfk>pebks^ib%/3)05&qlgrpqlsboqeb_loabolcA^ohpelob%10)61&+Cbbolfp^j_rpebaqeobbqfjbp_vdolrmplcpmb`f^iiv*pm^tkfkdnrbpqjl_p)_rqtfii^iplpqlm^ilkdqebt^vql^qq^`h^kvtfiaifcbqe^qt^kabopfkqlefp^ddolo^kdb+Cliiltfkdb^`e^qq^`h)Cbbolorkp_^`hqlqebpmlqebt^ppq^kafkdgrpq_bclobqeb^j_rpe^kap^vp^ifkb+>cqbo^cbtpb`lkapebpq^oqporkkfkd^d^fk*b^qfkd)aofkhfkd)illqfkdbq`cloqllilkdtfiiobkabovlrrk^_ibql`^q`eefjrmtfqelrqpmbbafk`ob^pfkd^_fifqfbpyyNFAy643y
QPrmmifbpql>r_boafkbyKyAbidobkqebMrofcfbo%/3+/)05+4&yyNFAy643y

Q@riifkdqebQeob^qyKyO^bkbTlicorkkbo%03+3)16+3&yyNFAy.-21y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
