DugisGuideViewer:RegisterGuide("Wetlands (25-27)", "Redridge Mountains (27-28)", "Alliance", "L", function()
return [[
AAA

C>r_boafkbyKyA^bivpef^%01+1)15&yyWy>pebks^ibyyNFAy41.y
QT>KQBA7JrohabbmyKyPbkqfkbiDivka^K^i$Peb^%04+4)10+1&yyWyA^ohpelobyyNFAy141-y
QQeb>_pbkqJfkabaMolpmb`qlo%M^oq/&yKy>o`e^blildfpqEliibb%04+2)1.+5&yyWyA^ohpelobyyNFAy40.y
>Qeb>_pbkqJfkabaMolpmb`qlo%M^oq0&yKy>o`e^blildfpqEliibb%04+2)1.+5&yyWyA^ohpelobyyNFAy41.y
QQeb>_pbkqJfkabaMolpmb`qlo%M^oq0&yKy@efbc>o`e^blildfpqDobvtefphbofkA^ok^pprp%0-)51&yyWyA^ok^pprpyyNFAy41.y
>Qeb>_pbkqJfkabaMolpmb`qlo%M^oq1&yKy@efbc>o`e^blildfpqDobvtefphbo%0-)51&yyWyA^ok^pprpyyNFAy61/y

_Pqlojtfka@fqvyKyQ^hbqeb?l^qqlPqlojtfka@fqv%0/+1)10+3&yyWyA^ohpelobyyNFAy/46y
cPqlojtfka@fqvyOyAo^bkbfyyKyArkd^oIlkdaofkh%4.)4/+3&yyWyPqlojtfka@fqvyyNFAy020y
>Pqlojmfhb$pAbifsbovyKyDofj^kaBijlob%26+4)01&yyWyPqlojtfka@fqvyyOyAo^bkbfyyNFAy020y
OAbbmorkQo^jyKyFkqebAt^osbkAfpqof`q%4-+0)/6+2&yyOyAo^bkbfyyWyPqlojtfka@fqvyyNFAy/46y
KQ^hbqebqo^jqlFolkclodbyKyQ^hbqebqo^jqlFolkclodbyyOyAo^bkbfyyNFAy/46y
O@fqvlcFolkclodbyOyAo^bkbfyyKyDlqeolrdeqebmloq^iyyNFAy/46y
C@fqvlcFolkclodbyKyFkqeb`bkqbolcqltk^qqebClodb%22+2)14+5&yyWyFolkclodbyyOyAo^bkbfyyNFAy/46y
OArkJloldeyKyOrkqlArkJlolde%.1)53&yyWyArkJloldeyyOyAo^bkbfyyNFAy/46y
OIl`eJla^kyKyQ^hbqebol^ab^pq)qebkkloqe%51+4)/6+3&qeolrdeqebqrkkbiyyWyArkJloldeyyOyAo^bkbfyyNFAy/46y
QPqlojmfhb$pAbifsbovyKyJlrkq^fkbboPqlojmfhb%/1+4).5+0&yyNFAy020yyOyAo^bkbfyyWyIl`eJla^ky
cQebip^j^oyKyQelodorj?loobiplk%00+6)2-+6&yyOyAo^bkbfyyWyIl`eJla^kyyNFAy/46y

CIl`eJla^kyOyErj^k)At^oc)Dkljb)KfdeqBicyyKyArkd^oIlkdaofkh%4.)4/+3&yyWyPqlojtfka@fqvyyNFAy/46y
OTbqi^kapyKyOrkKloqeqeolrdeqebQrkkbi%/2+1)4+3&yyWyIl`eJla^kyyNFAy/46y
OJbkbqefiE^o_loyKyOrkqlJbkbqefiE^o_lo%5+1)25+3&yyNFAy/46y

>@i^tpcoljqebAbbmyKyH^oi?lo^k%5)25&yyNFAy/46y
>Vlrkd@ol`lifphPhfkpyKyG^jbpE^iilo^k%5+3)22+4&yyNFAy151y
>T^o?^kkbopyKy@^mq^fkPqlrqcfpq%6+6)24+1&yyNFAy131y
>AfddfkdQeolrdeqebLlwbyKyPfa^%..+5)25&yyNFAy14-y
>QebQefoaCibbqyKyCfopqJ^qbCfqwpfjjlkp%.-+6)26+3&yyNFAy/55y
>QebDobbkt^oabkyKyCfopqJ^qbCfqwpfjjlkp%.-+6)26+3&yyNFAy130y
eAbbmt^qboQ^sbokyKyFkkhbbmboEbi_obh%.-+4)3-+6&yyNFAy610y
??rvXCi^dlklcJb^aZyKy?rvCfopqJ^qbCfqwpfjjlkp^Ci^dlklcJb^atef`e`^k_bmro`e^pbacoljFkkhbbmboEbi_obh%.-+4)3-+6&clo.2pfisboyyNFAy610yyIy/261y
QQeb>_pbkqJfkabaMolpmb`qlo%M^oq1&yKy>o`e^blildfpqCi^dlkdrq%.-+5)3-+1&yyNFAy61/y
>Qeb>_pbkqJfkabaMolpmb`qlo%M^oq2&yKy>o`e^blildfpqCi^dlkdrq%.-+5)3-+1&yyNFAy610y
QQebQefoaCibbqyKyCfopqJ^qbCfqwpfjjlkp%.-+6)26+3&yyNFAy/55y
>Qeb@ropba@obtyKyCfopqJ^qbCfqwpfjjlkp%.-+6)26+3&yyNFAy/56y
>FkPb^o`elcQebBu`^s^qflkQb^j%M^oq.&yKyQ^oobiOl`htb^sbo%..+2)2/+/&yyNFAy0-2y

KHfiiVlrkd@ol`p^pvlrqo^sbiyKyHfii^kvVlrkd@ol`lifphpvlr`ljb^`olppcloVlrkd@ol`lifphPhfkpyyNFAy151y
@@i^tpcoljqebAbbmyKyHfii./?irbdfiiJroil`pclrka^olrkaqeb?irbdfiiJ^opegrpqlrqpfabJbkbqefiE^o_lo^olrka%.2)05&+Dl__ibom^qolipqeb^ob^^olrka%.4)1-&^kavlrjrpqhfiiefjqlobqofsbefpeb^ayyNFAy/46y

QFkPb^o`elcQebBu`^s^qflkQb^j%M^oq.&yKyJboofkOl`htb^sbo%05+5)2/+0&yyNFAy0-2y
>FkPb^o`elcQebBu`^s^qflkQb^j%M^oq/&yKyJboofkOl`htb^sbo%05+5)2/+0&yyNFAy0-3y
>Lojbo$pObsbkdb%M^oq.&yKyLojboFolk_o^fa%05)2.&yyNFAy/61y
KDbqqebXCi^dlkdrq$pClppfiZyIy2/01yyKy%05+5)2/+/&CloQeb>_pbkqJfkabaMolpmb`qlo%M^oq2&yyNFAy610y

@Lojbo$pObsbkdb%M^oq.&yKyHfii.-JlqqibaP`obb`ebop^kaJlqqibaO^mqloptef`e^obclrka^olrkaqebPlrqetbpqjlrkq^fkpfab^olrka%/3)12&yyNFAy/61y
QLojbo$pObsbkdb%M^oq.&yKyLojboFolk_o^fa%05)2.&yyNFAy/61y
>Lojbo$pObsbkdb%M^oq/&yKyLojboFolk_o^fa%05)2.&yyNFAy/62y
>Rk`lsbofkdqebM^pqyKyMolpmb`qloTebid^o%05+5)2/+0&yyNFAy/66y
KHbbm^kbvblrqcloobif`pyNFAy/62y
@Lojbo$pObsbkdb%M^oq/&yKyHfii.-JlqqibaP`vqeb`i^t^kaJlqqibaO^wloj^to^mqloptef`e^obclrkafkpfabTebid^o$pBu`^s^qflkPfqb%01)1/&yyNFAy/62y
QLojbo$pObsbkdb%M^oq/&yKyLojboFolk_o^fa%05)2.&yyNFAy/62y
>Lojbo$pObsbkdb%M^oq0&yKyLojboFolk_o^fa%05)2.&yyNFAy/63y
@Rk`lsbofkdqebM^pqyKyPb^o`eqebbu`^s^qflkpfqb%02)15&cloqeb1jfppfkdq^_ibqco^djbkqp7>alp)Jlao^kaDlij^ob^ii`lkq^fkbafko^kaljivmi^`bas^pbp^ka^pqlkb`ebpq+>kaKborfp`lkq^fkbafkillpbplfiyyNFAy/66y
@Lojbo$pObsbkdb%M^oq0&yKyCfka^kahfiiP^oiqllqetelfpclrkalkqlmlcqebefiifkqebBu`^s^qflkPfqb^olrka%0.)2-&ql`liib`qefpq^ilkyyNFAy/63y
QRk`lsbofkdqebM^pqyKyMolpmb`qloTebid^o%05+5)2/+0&yyNFAy/66y
QLojbo$pObsbkdb%M^oq0&yKyLojboFolk_o^fa%05)2.&yyNFAy/63y

@Qeb>_pbkqJfkabaMolpmb`qlo%M^oq2&yKyDbqqebXPqlkblcObirZaolmmba_vJlqqibaO^mqlo^olrka%04)15&^kaXCi^dlkdrq$pClppfiZ^q%05+5)2/+/&yyNFAy610y

@T^o?^kkbopyKyDbq5XAo^dlkj^tT^o?^kkbopZtef`e^obaolmmbacolj^kvlcqebAo^dlkj^tjl_ptef`eproolrkaqebbk`^jmjbkq^q%11)11&yyNFAy131y
>A^fivAbifsbovyKyBfk^oPqlkbdofm%16+6)06+1&yyNFAy136y
QQebDobbkt^oabkyKyObqefbiqebDobbkt^oabk^q%23+0)1-+0&yyNFAy130y
>Qo^jmfkdM^tpyKyObqefbiqebDobbkt^oabk^q%23+0)1-+0&yyNFAy/43y
@Qo^jmfkdM^tpyKyHfii.2JlppefabDkliip^ka.-JlppefabJlkdobiptef`e^obclrkaqlqebPlrqe^olrka%3/)33&yyNFAy/43y
QQo^jmfkdM^tpyKyObqefbiqebDobbkt^oabk^q%23+0)1-+0&yyNFAy/43y
>CfobQ^_llyKyObqefbiqebDobbkt^oabk^q%23+0)1-+0&yyNFAy/44y
@CfobQ^_llyKy@liib`q6X@orabCifkqpZtef`e`^k_bclrkacoljqebJlppefabjl_p^olrka%05)0.&yyNFAy/44y
@Vlrkd@ol`lifphPhfkpyKyQebpbphfkp^obillqbacoljVlrkdTbqi^kap@ol`lifphplkivtef`e`^k_bclrkafkqebplrqebokt^qbopgrpqlrqlcJbkbqefiE^o_lo^olrka%.3)2-&+Hfiibklrderkqfivlre^sb`liib`qba1XVlrkd@ol`lifphPhfkpZyyNFAy151y
QCfobQ^_llyKyObqefbiqebDobbkt^oabk^q%23+0)1-+0&yyNFAy/44y
>?ifpqboplkQebI^kayKyObqefbiqebDobbkt^oabk^q%23+0)1-+0&yyNFAy/42y

EJbkbqefiE^o_loyRy3615yyNFAy/5.y
QQeb>_pbkqJfkabaMolpmb`qlo%M^oq2&yKy>o`e^blildfpqCi^dlkdrq%.-+5)3-+1&yyNFAy610y
Q@i^tpcoljqebAbbmyKyH^oi?lo^k%5)25&yyNFAy/46y
>Ob`i^fjfkdDllapyKyH^oi?lo^k%5)25&yyNFAy/5.y
QVlrkd@ol`lifphPhfkpyKyG^jbpE^iilo^k%5+3)22+4&yyNFAy151y
QA^fivAbifsbovyKyG^jbpE^iilo^k%5+3)22+4&yyNFAy136y
>>mmobkqf`b$pArqfbpyKyG^jbpE^iilo^k%5+3)22+4&yyNFAy14.y
QT^o?^kkbopyKy@^mq^fkPqlrqcfpq%6+6)24+1&yyNFAy131y
>Kbh$olpe$pD^j_fqyKy@^mq^fkPqlrqcfpq%6+6)24+1&yyNFAy132y
QFkPb^o`elcQebBu`^s^qflkQb^j%M^oq/&yKyQ^oobiOl`htb^sbo%..+2)2/+/&yyNFAy0-3y

KHfiipqb^iqebibjbkq^ip+++yKyHfii^kvCbk@obbmbop%/4)04&)%//+2)/.&vlr`ljb^`olppclo?ifpqboplkQebI^ka+Qebvpqb^iqe^kacliiltqebpe^iiltt^qbopfkqebtbpqe^iclcqebwlkbyyNFAy/42y

QOb`i^fjfkdDllapyKyA^j^dba@o^qb%.0+3)1.+2&yyNFAy/5.y
>QebPb^o`e@lkqfkrbpyKyA^j^dba@o^qb%.0+3)1.+2&yyNFAy/51y
QQebPb^o`e@lkqfkrbpyKyPb^iba?^oobi%.0+3)05+.&yyNFAy/51y
>Pb^o`eJlobElsbipyKyPb^iba?^oobi%.0+3)05+.&yyNFAy/52y
QPb^o`eJlobElsbipyKyE^ic*_rofba?^oobi%.0+6)01+6&yyNFAy/52y
>ObqrokqebPq^qrbqqbyKyE^ic*_rofba?^oobi%.0+6)01+6&yyNFAy/53y

@Qeb@ropba@obtyKyHfii.0@ropbaP^filop^ka2@ropbaJ^ofkbptef`e^obclrka^olrkaqebpefmtob`h^olrka%.0)/4&+Qebkcfka^kahfiiCfopqJ^qbPkbiifdtelfplkqebpefm^q%.1)0-&lkqebiltbpqab`hql`liib`qXPkbiifd$pPkrcc_luZyyNFAy/56y
@>mmobkqf`b$pArqfbpyKy@liib`q3XDf^kq@ol`lifphPhfkpZaolmmba_vDf^kqTbqi^kap@ol`lifphclrkajlpqiv^olrkaqeb`l^pqlcqebJ^opebp^q%.6)//&loqebfkqebt^qbop^olrka%.4)3-&yyNFAy14.y
@?ifpqboplkQebI^kayKyHfii5Cbk@obbmboptef`e`^k_bclrkat^ihfkd^olrkaqebt^qbopfkqebJ^opebp^olrka%/.)/5&+Qebpb^obpqb^iqebaplfqj^vq^hbpljborkkfkd^olrkaqlcfkaqebjyyNFAy/42y
@AfddfkdQeolrdeqebLlwbyKyHfii^kvlcqebLlwbjl_ptef`eproolrkaFolk_b^oa$pQlj_^q%11)/2&rkqfivlr$sb`liib`qbaXPfa^$p?^dZyyNFAy14-y

Q?ifpqboplkQebI^kayKyObqefbiqebDobbkt^oabk^q%23+0)1-+0&yyNFAy/42y

EJbkbqefiE^o_loyRy3615yyNFAy/6-y
QQeb@ropba@obtyKyCfopqJ^qbCfqwpfjjlkp%.-+6)26+3&yyNFAy/56y
>Ifcqfkdqeb@ropbyKyCfopqJ^qbCfqwpfjjlkp%.-+6)26+3&yyNFAy/6-y
QAfddfkdQeolrdeqebLlwbyKyPfa^%..+5)25&yyNFAy14-y
Q>mmobkqf`b$pArqfbpyKyG^jbpE^iilo^k%5+3)22+4&yyNFAy14.y
QObqrokqebPq^qrbqqbyKyH^oi?lo^k%5)25&yyNFAy/53y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
