DugisGuideViewer:RegisterGuide("Redridge Mountains (27-28)", "Duskwood (28-29)", "Alliance", "L", function()
return [[
AAA

CPqlojtfka@fqvyKyPebiibf?olkafo%6+2)22+4&yyOyAo^bkbfyyWyTbqi^kapyyNFAy./5y
OBitvkkClobpqyKyQo^sbiqlBitvkkClobpq%00)2.&yyNFAy./5yyOyAo^bkbfyyWyBitvkkClobpqy
OObaofadbJlrkq^fkpyKyQo^sbiqlObaofadbJlrkq^fkp%.-)4/&yyNFAy./5yyOyAo^bkbfy
CObaofadbJlrkq^fkpyKyPebiibf?olkafo%6+2)22+4&yyWyTbqi^kapyyNFAy./5y
>?i^`hol`h?lrkqvyKyDr^oaEltb%0.)25&yyNFAy./5y
>?i^`hol`hJbk^`byKyJ^ope^iJ^oofp%00+1)15+6&yyNFAy/-y
QJbppbkdboqlPqlojtfka%M^oq/&yKyJ^dfpqo^qbPliljlk%0-)11&yyLyyNFAy./.y
>Pliljlk$pI^tyKy?^fifcc@lk^`ebo%/6+3)11+0&yyNFAy6.y
>T^kqba7Ifbrqbk^kqC^kdlobyKyT^kqba7Ifbrqbk^kqC^kdlob%/3+4)13+2&yyNFAy.5-y
eI^hbpefobyKyFkkhbbmbo?of^kk^%/4)12&yyNFAy01y

>>kRktbi`ljbDrbpqyKyJ^oqfbG^fkolpb%//)13+0&yyNFAy01y
@>kRktbi`ljbDrbpqyKyQo^sbiTbpqcoljqebciltbopelmql%.4)15&tebobvlr`^kcfka?biivdor_)hfiiefjqlillqefpQrphyyNFAy01y
Q>kRktbi`ljbDrbpqyKyJ^oqfbG^fkolpb%//)13+0&yyNFAy01y

@?i^`hol`hJbk^`byKyDbq.-X?^qqibtlok>ubpZtef`eaolmcolj^kvlcqeb?i^`hol`hjl_pclrka^ilkdqebKloqebokol^alo^qqebfobk`^jmjbkq^q%0.).1&yyNFAy/-y
@?i^`hol`h?lrkqvyKyHfii.2?i^`hol`h@e^jmflkptef`e^obclrkaqlqebKloqe^olrka%0.).1&yyNFAy./5y
>JfppfkdFk>`qflkyKy@lomlo^iHbbpe^k%/5)./&*jlsbp^olrkaqefp^ob^yyNFAy/.6y
@JfppfkdFk>`qflkyKyQefpfp^kbp`loqnrbpqtebobvlrjrpqmolqb`q@lomlo^iHbbpe^k%/5)./&qeolrdeqeb`^sb+Ebfp^pqolkdKM@telvlrpelriaibqq^kh_rq^ipl_bprobqlmriiqebjl_pqlefjfkpqb^alcefj`e^odfkdfkqlqebjqlmobsbkq^kvrkt^kqba^aap+Ebfp^kbifqbt^ooflopltfiiebimq^rkq^kvjl_plccvlryyNFAy/.6y

QJfppfkdFk>`qflkyKyJ^ope^iJ^oofp%00+1)15+6&yyNFAy/.6y
Q?i^`hol`hJbk^`byKyJ^ope^iJ^oofp%00+1)15+6&yyNFAy/-y
Q?i^`hol`h?lrkqvyKyDr^oaEltb%0.)25&yyNFAy./5y

@T^kqba7Ifbrqbk^kqC^kdlobyKyIfbrqbk^kqC^kdlobfp^Ibsbi/3klk*bifqb_rqfpproolrkaba^jlkdpqqeblqebojl_p^olrka%5-)1-&pl_bprobql`ib^o^kvjl_p_bclob^qq^`hfkdefjyyNFAy.5-y
@Pliljlk$pI^tyKy@liib`q.-XPe^altefabMbka^kqpZtef`e`^k_billqbacolj^kvlcqebPe^altefabjl_pclrka^olrka%41)14&qlqebKloqeb^pqlcPqlkbt^q`eHbbmyyNFAy6.y

EI^hbpefobyRy3615y
QPliljlk$pI^tyKy?^fifcc@lk^`ebo%/6+3)11+0&yyNFAy6.y
QT^kqba7Ifbrqbk^kqC^kdlobyKyJ^dfpqo^qbPliljlk%0-)11&yyNFAy.5-y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
