DugisGuideViewer:RegisterGuide("Duskwood (28-29)", "Ashenvale (29-30)", "Alliance", "L", function()
return [[
AAA

CPqlojtfka@fqvyKy>ofbk^Pqlojcb^qebo%0-+4)26+0&yyWyObaofadbJlrkq^fkpyyNFAy./41y
>QebJfppfkdAfmilj^q%M^oq.&yKyQelj^p%2.)14&*jlsbp^olrkaqefp^ob^yyWyPqlojtfka@fqvyyNFAy./41y
QQebJfppfkdAfmilj^q%M^oq.&yKy?fpelmAbI^sbv%5-+/)10+6&yyWyPqlojtfka@fqvyyNFAy./41y
>QebJfppfkdAfmilj^q%M^oq/&yKy?fpelmAbI^sbv%5-+/)10+6&yyWyPqlojtfka@fqvyyNFAy./1.y
QQebJfppfkdAfmilj^q%M^oq/&yKyGlodbk%43+/)52+0&yyWyPqlojtfka@fqvyyNFAy./1.y
>QebJfppfkdAfmilj^q%M^oq0&yKyGlodbk%43+/)52+0&yyWyPqlojtfka@fqvyyNFAy./1/y
QQebJfppfkdAfmilj^q%M^oq0&yKyBiifkdQof^p%33+.)41+/&yyWyPqlojtfka@fqvyyNFAy./1/y
>QebJfppfkdAfmilj^q%M^oq1&yKyBiifkdQof^p%33+.)41+/&yyWyPqlojtfka@fqvyyNFAy./10y

??rvX?olkwbQr_bZyKyBkdfkbbofkdsbkalo?fiif_r_@ldpmfkkbo%3/+2)0-+.&pbiipqefppljbqfjbp)lqebotfpb_rvcoljqeb^r`qflkelrpbyyIy104.yyWyPqlojtfka@fqvyyNFAy./11y

CObaofadbJlrkq^fkpyKyArkd^oIlkdaofkh%4-+6)4/+4&yyWyPqlojtfka@fqvyyNFAy./11y
OA^ohpefobyKyQ^hbqebol^aplrqetbpq%1)6.+2&yyNFAy./11y
QQebJfppfkdAfmilj^q%M^oq1&yKyT^q`ebo?^`hrp*t^ihp^ilkdqebol^a_bqtbbk%41)10&^ka%4/)0/&yyNFAy./10y
>QebJfppfkdAfmilj^q%M^oq2&yKyT^q`ebo?^`hrp*t^ihp^ilkdqebol^a_bqtbbk%41)10&^ka%4/)0/&yyNFAy./11y
cA^ohpefobyKyCbif`f^J^ifkb%44+2)11+1&yyNFAy33y
>QebIbdbkalcPq^is^k%M^oq.&yKyJ^a^jbBs^%42+5)12+0&yyNFAy33y
>QebQlqbjlcFkcif`qflkyKyJ^a^jbBs^%42+5)12+0&yyNFAy.-.y
eA^ohpefobyKyFkkhbbmboQobi^vkb%40+6)11+1&yyNFAy23y
>QebKfdeqT^q`e%M^oq.&yKy@ljj^kabo>iqeb^B_lkil`hb%40+3)13+5&yyNFAy23y
QQebIbdbkalcPq^is^k%M^oq.&yKy@ibohA^iqov%4/+3)13+6&yyNFAy33y
>TlodbkfkqebTllap%M^oq.&yKy@^ilo%42+0)14+6&yyNFAy.40y
>O^sbkEfiiyKyBi^fkb@^obsfk%42+0)15+3&yyNFAy.30y
>QebEbojfqyKyBi^fkb@^obsfk%42+0)15+3&yyNFAy.32y
>AbifsbofbpqlPsbkyKyBi^fkb@^obsfk%42+0)15+3&yyNFAy.31y
>IllhQlQebPq^op%M^oq.&yKySfhqlofMofpj$>kqo^p%46+5)14+6&yyNFAy.41y
@IllhQlQebPq^op%M^oq.&yKy?rv^X?olkwbQr_bZcoljEbo_ib?^r__ibqrjm%45)15&fkArphtlla+Ebalbplkive^sb^ifjfqbaprmmivlcqebpb^kavlrj^ve^sbqlt^fqcloefjqlpql`hrm+Fcebalbpklqe^sb^kvvlr`^kb^pfivcivqlPqlojtfkatebobvlr`^k_rvqebpbcolj?fiif_r_@ldpmfkkbofkqebAt^osbkAfpqof`qyyNFAy.41y
QIllhQlQebPq^op%M^oq.&yKySfhqlofMofpj$>kqo^p%46+5)14+6&yyNFAy.41y
>IllhQlQebPq^op%M^oq/&yKySfhqlofMofpj$>kqo^p%46+5)14+6&yyNFAy.42y

@TlodbkfkqebTllap%M^oq.&yKyHfii3Kfdeq_^kbPe^altTb^sbotef`e`^k_bclrkafkqebOlqqfkdLo`e^oa%30)4-&PlrqetbpqlcqebqltklcA^ohpefobyyNFAy.40y

QTlodbkfkqebTllap%M^oq.&yKy@^ilo%42+0)14+6&yyNFAy.40y
>TlodbkfkqebTllap%M^oq/&yKy@^ilo%42+0)14+6&yyNFAy//.y

@TlodbkfkqebTllap%M^oq/&yKyHfii./Kfdeq_^kbA^ohOrkkboptef`e`^k_bclrkafkqebOlqqfkdLo`e^oa%30)4-&PlrqetbpqlcqebqltklcA^ohpefobyyNFAy//.y

QTlodbkfkqebTllap%M^oq/&yKy@^ilo%42+0)14+6&yyNFAy//.y
>TlodbkfkqebTllap%M^oq0&yKy@^ilo%42+0)14+6&yyNFAy///y
QIllhQlQebPq^op%M^oq/&yKy?ifkaJ^ov%5.+5)26+0&yyNFAy.42y
>IllhQlQebPq^op%M^oq0&yKy?ifkaJ^ov%5.+5)26+0&yyNFAy.44y

@IllhQlQebPq^op%M^oq0&yKyCfka^kahfiiqebFkp^kbDelritef`e`^k_bclrkam^qoliifkdqebQo^knrfiD^oabkp@bjbq^ov^olrka%45)4-&^kaobqofbsbXJ^ov$pIllhfkdDi^ppZyyNFAy.44y
@QebKfdeqT^q`e%M^oq.&yKyQo^sbiqlqebQo^knrfiD^oabkp@bjbq^ov^olrka%45)4-&^kahfii5Phbibq^iT^ooflop^ka3Phbibq^iJ^dbpyyNFAy23y

EA^ohpefobyRy3615yyNFAy24y
QQebKfdeqT^q`e%M^oq.&yKy@ljj^kabo>iqeb^B_lkil`hb%40+3)13+5&yyNFAy23y
>QebKfdeqT^q`e%M^oq/&yKy@ljj^kabo>iqeb^B_lkil`hb%40+3)13+5&yyNFAy24y

QIllhQlQebPq^op%M^oq0&yKySfhqlofMofpj$>kqo^p%46+5)14+6&yyNFAy.44y
>IllhQlQebPq^op%M^oq1&yKySfhqlofMofpj$>kqo^p%46+5)14+6&yyNFAy.5.y

@IllhQlQebPq^op%M^oq1&yKyCfka^kahfiiWw^o`$Sritelfpclrkafkqeb`^sb^q%03)50&^ka`liib`qqebXLdob$pJlkl`ibZyyNFAy.5.y
@QebJfppfkdAfmilj^q%M^oq2&yKyCfkaqebXAbcf^pAl`hbqZ`lkq^fkbafkAbcf^pPqolkd_lu^q%/1)4/&yyNFAy./11yyNFAy./11y

QO^sbkEfiiyKyGfqqbop%.5+0)23+1&yyNFAy.30y
@QebKfdeqT^q`e%M^oq/&yKyQo^sbiKloqelcO^sbkEfiiql%/-)12&^kahfii.2Phbibq^iCfbkap^ka.2Phbibq^iEloolopyyNFAy24y
QQebEbojfqyKy>_bo`olj_fb%/5)0.+2&yyNFAy.32y
>PrmmifbpcoljA^ohpefobyKy>_bo`olj_fb%/5)0.+2&yyNFAy.15y
>QebTb^qebobaDo^sbyKy>Tb^qebobaDo^sb%.4+4)/6+/&yyNFAy//2y
QAbifsbofbpqlPsbkyKyPsbkVlodbk%4+5)01+.&yyNFAy.31y
>Psbk$pObsbkdbyKyPsbkVlodbk%4+5)01+.&yyNFAy62y

EA^ohpefobyRy3615yyNFAy25y
QQebKfdeqT^q`e%M^oq/&yKy@ljj^kabo>iqeb^B_lkil`hb%40+3)13+5&yyNFAy24y
>QebKfdeqT^q`e%M^oq0&yKy@ljj^kabo>iqeb^B_lkil`hb%40+3)13+5&yyNFAy25y
QQebTb^qebobaDo^sbyKyPfoo^Slk$Fkaf%4/+3)14+3&yyNFAy//2y
>Jlod^kI^afjlobyKyPfoo^Slk$Fkaf%4/+3)14+3&yyNFAy//4y
QJlod^kI^afjlobyKy@ljj^kabo>iqeb^B_lkil`hb%40+3)13+5&yyNFAy//4y
QPrmmifbpcoljA^ohpefobyKyJ^a^jbBs^%42+5)12+0&yyNFAy.15y
>DelpqE^foQeob^ayKyJ^a^jbBs^%42+5)12+0&yyNFAy.16y
QQebJfppfkdAfmilj^q%M^oq2&yKyT^q`ebo?^`hrp*t^ihp^ilkdqebol^a_bqtbbk%41)10&^ka%4/)0/&yyNFAy./11yyNFAy./11y
>QebJfppfkdAfmilj^q%M^oq3&yKyT^q`ebo?^`hrp*t^ihp^ilkdqebol^a_bqtbbk%41)10&^ka%4/)0/&yyNFAy./12y
QIllhQlQebPq^op%M^oq1&yKySfhqlofMofpj$>kqo^p%46+5)14+6&yyNFAy.5.y

QDelpqE^foQeob^ayKy?ifkaJ^ov%5.+5)26+0&yyNFAy.16y
>Obqrokqeb@lj_yKy?ifkaJ^ov%5.+5)26+0&yyNFAy.21y

QObqrokqeb@lj_yKyJ^a^jbBs^%42+5)12+0&yyNFAy.21y
>AbifsboqebQeob^ayKyJ^a^jbBs^%42+5)12+0&yyNFAy.24y

QPsbk$pObsbkdbyKyJlrkalcillpbafoq%2-)44+5&yyNFAy62y
>Psbk$p@^jmyKyJlrkalcillpbafoq%2-)44+5&yyNFAy/0-y

QAbifsboqebQeob^ayKy>_bo`olj_fb%/5)0.+2&yyNFAy.24y
>Wlj_fbGrf`byKy>_bo`olj_fb%/5)0.+2&yyNFAy.25y

@QebKfdeqT^q`e%M^oq0&yKyQo^sbicroqebokloqecoljtebobvlrafaM^oq/lcqefpnrbpqql^olrka%/1+..)01+.-&^kahfii/-Mi^drbPmob^abopyyNFAy25y

@QebQlqbjlcFkcif`qflkyKyDbq.-XPhbibqlkCfkdbopZaolmmba_vPhbibq^iEloolo^olrka%//)10&+Dbq2XSf^iplcPmfaboSbkljZaolmmba_v@^ooflkOb`irpb^olrka%/-)05&+Dbq.-XDelriC^kdpZaolmmba_vCibpeB^qbopfkO^sbkEfii^olrka%/1)02&+Qeb`liib`qflklcqebpbfqbjp`^kdbkbo^iiv_b`liib`qbatefipqnrbpqfkdfklqebonrbpqpyyNFAy.-.y

QPsbk$p@^jmyKyPsbkVlodbk%4+5)01+.&yyNFAy/0-y
>QebPe^altvCfdrobyKyPsbkVlodbk%4+5)01+.&yyNFAy/3/y

OPqo^kdibqelokS^ibyKyQ^hbqebol^ab^pqqlt^oapA^ohpefob)_rqeb^aplrqe^qqebclohfkqeb`bkqbolcqebwlkb%11+2)56+/&yyNFAy/32y
CA^ohpefobyKyQebobfp^cifdeqmlfkq^qqebOb_bi@^jm^ilkdqebkloqebadblcPQS%05+.)0+5&yyWyPqo^kdibqelokS^ibyyNFAy/32y
QQebQlqbjlcFkcif`qflkyKyJ^a^jbBs^%42+5)12+0&yyNFAy.-.y
QQebPe^altvCfdrobyKyJ^a^jbBs^%42+5)12+0&yyNFAy/3/y
>QebPe^altvPb^o`e@lkqfkrbpyKyJ^a^jbBs^%42+5)12+0&yyNFAy/32y
QQebKfdeqT^q`e%M^oq0&yKy@ljj^kabo>iqeb^B_lkil`hb%40+3)13+5&yyNFAy25y
QQebPe^altvPb^o`e@lkqfkrbpyKy@ibohA^iqov%4/+3)13+6&yyNFAy/32y
>Fknrfob^qqebFkkyKy@ibohA^iqov%4/+3)13+6&yyNFAy/33y
QFknrfob^qqebFkkyKyQ^sbokhbbmPjfqqp%40+5)11+1&yyNFAy/33y
QWlj_fbGrf`byKyQ^sbokhbbmPjfqqp%40+5)11+1&yyNFAy.25y

@TlodbkfkqebTllap%M^oq0&yKyHfii5Kfdeq_^kbSfibC^kd^ka5Kfdeq_^kbQ^fkqbatef`e`^k_bclrkalkqebTbpqbokbadblcqebQo^knrfiD^oabkp@bjbq^ov^olrka%41)34&+Q^fkqbaLkbp^obclrkacroqeboPlrqecoljqefp^ob^^olrka%41)41&yyNFAy///y
QTlodbkfkqebTllap%M^oq0&yKy@^ilo%42+0)14+6&yyNFAy///y
>TlodbkfkqebTllap%M^oq1&yKy@^ilo%42+0)14+6&yyNFAy//0y
QTlodbkfkqebTllap%M^oq1&yKyGlk^qe^k@^obsfk%42+0)15+6&yyNFAy//0y

CPqlojtfka@fqvyKyCbif`f^J^ifkb%44+2)11+1&yyNFAy./13y
QQebJfppfkdAfmilj^q%M^oq3&yKyBiifkdQof^p%33+.)41+/&yyWyPqlojtfka@fqvyyNFAy./12y
>QebJfppfkdAfmilj^q%M^oq4&yKyBiifkdQof^p%33+.)41+/&yyWyPqlojtfka@fqvyyNFAy./13y
QQebJfppfkdAfmilj^q%M^oq4&yKyA^pebiPqlkbcfpq%41+.)26+/&yyWyPqlojtfka@fqvyyNFAy./13y
>QebJfppfkdAfmilj^q%M^oq5&yKyA^pebiPqlkbcfpq%41+.)26+/&yyWyPqlojtfka@fqvyyNFAy.114y
@QebJfppfkdAfmilj^q%M^oq5&yKyAbcb^qA^pebiPqlkbcfpq%41+.)26+/&yyWyPqlojtfka@fqvyyNFAy.114y
QQebJfppfkdAfmilj^q%M^oq5&yKyA^pebiPqlkbcfpq%41+.)26+/&yyWyPqlojtfka@fqvyyNFAy.114y
>QebJfppfkdAfmilj^q%M^oq6&yKyA^pebiPqlkbcfpq%41+.)26+/&yyWyPqlojtfka@fqvyyNFAy./14y
>>kLiaEfpqlov?llhyKyX>kLiaEfpqlov?llhZ*qefpfqbjpq^oqpqebnrbpq^kafpaolmmba^olrka%46)36&_vPhbibq^iT^ooflo^kaPhbibq^iJ^dbyyRy/461yyLyyNFAy004y
Q>kLiaEfpqlov?llhyKyJfiqlkPeb^c%44)0-+2&yyLyyWyPqlojtfka@fqvyyNFAy004y
>PlrqepelobyLyyKyJfiqlkPeb^c%44)0-+2&yyWyPqlojtfka@fqvyyNFAy205y
QQebJfppfkdAfmilj^q%M^oq6&yKyBiifkdQof^p%33+.)41+/&yyWyPqlojtfka@fqvyyNFAy./14y
>QebJfppfkdAfmilj^q%M^oq.-&yKyBiifkdQof^p%33+.)41+/&yyWyPqlojtfka@fqvyyNFAy./15y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
