DugisGuideViewer:RegisterGuide("Ashenvale (29-30)", "Wetlands (30-31)", "Alliance", "L", function()
return [[
AAA

CJbkbqefiE^o_loyKy>ofbk^Pqlojcb^qebo%0-+4)26+0&yyWyObaofadbJlrkq^fkpyyNFAy./16y
QQebJfppfkdAfmilj^q%M^oq.-&yKyJfhe^fi%.-+3)3-+4&yyWyTbqi^kapyyNFAy./15y
>QebJfppfkdAfmilj^q%M^oq..&yKyJfhe^fi%.-+3)3-+4&yyWyTbqi^kapyyNFAy./16y
@QebJfppfkdAfmilj^q%M^oq..&yKyPr_arbQ^mlhbG^ek%.-)3-&_bclobebbp`^mbpyyWyTbqi^kapyyNFAy./16y
QQebJfppfkdAfmilj^q%M^oq..&yKyJfhe^fi%.-+3)3-+4&yyWyTbqi^kapyyNFAy./16y
>QebJfppfkdAfmilj^q%M^oq./&yKyQ^mlhbPifjG^ek%.-)3-&yyWyTbqi^kapyyNFAy./2-y
QQebJfppfkdAfmilj^q%M^oq./&yKyJfhe^fi%.-+3)3-+4&yyWyTbqi^kapyyNFAy./2-y
>QebJfppfkdAfmilj^q%M^oq.0&yKyJfhe^fi%.-+3)3-+4&yyWyTbqi^kapyyNFAy./31y
CPqlojtfka@fqvyKyPebiibf?olkafo%6+2)26+4&yyNFAy125.y

_>r_boafkbyWyPqlojtfka@fqvyyKyQ^hbqeb_l^qcoljPqlojtfka%/0)22+2&ql>r_boafkbyyNFAy125.y
C>pqo^k^^oyKyQ^hbqeb_l^qql>r_boafkbqebkcivaltkyyNFAy125.y
>H^vkbqePqfiitfkayKyPefkaobiiPtfcqcfob%01+4)15+6&yyNFAy125.y
>>EbimfkdE^kayKySfkaf`^qloM^i^k^^o%01+6)16+4&yyNFAy6200y
e>pqo^k^^oyKyFkkhbbmboHfjiv^%04)16+0&yyNFAy.-/.y

OClobpqPlkdyKyB^pqbokjlpqm^oqlc>pebks^ib)Kloqeb^pqcoljP^qvok^^oyyNFAy.-/.y
>SfibP^qvoAov^apfkA^kdboyKyFiifv^k^%54)10+2&yyNFAy.-/.y
cClobpqPlkdyKyPro^i^fpC^otfka%52+.)10+1&yyNFAy.-0.y

QSfibP^qvoAov^apfkA^kdboyKy>kfif^%45+0)11+6&yyNFAy.-/.y
>Qeb?o^k`elc@bk^ofrpyKy>kfif^%45+0)11+6&yyNFAy.-0.y

@Qeb?o^k`elc@bk^ofrpyKyHfiiDbiqe^ofp%45)1/+2&^kaobqrokqebX?o^k`elc@bk^ofrpZqlFiifv^k^^qClobpqPlkdyyNFAy.-0.y

QQeb?o^k`elc@bk^ofrpyKyFiifv^k^%54)10+2&yyNFAy.-0.y
>P^qvoPi^vfkdyKyFiifv^k^%54)10+2&yyNFAy.-0/y
QH^vkbqePqfiitfkayKyH^vkbqePqfiitfka%52+0)11+4&yyNFAy125.y
>QebIlpq@e^if`byKyH^vkbqePqfiitfka%52+0)11+4&yyNFAy62.6y
>Clop^hbkAfpb^pbpyKyH^vkbqePqfiitfka%52+0)11+4&yyNFAy.-..y
>QebEltifkdS^ibyKyPbkqfkbiJbivof^Colpqpe^alt%53+.)11+.&yyNFAy.-//y
>>dbkqplcAbpqor`qflkyKyPbkqfkbiIr`fbiPq^otefpmbo%53+.)11+1&yyNFAy62.5y
Q>EbimfkdE^kayKy>o`efqb`qKbjlp%53+5)11+5&yyNFAy6200y
>>Pe^jbcriT^pqbyKy>o`efqb`qKbjlp%53+5)11+5&yyNFAy62.4y
>AbpqolvqebIbdflkyKySfkaf`^qloSba^^o%53+2)10+4&yyNFAy62.3y
>Ob`i^fjfkdCbicfobEfiiyKyDk^oi%54)12&*jlsbp^olrkaqefp^ob^yyNFAy62/3y

@QebIlpq@e^if`byKy@liib`qqebX@e^if`blcBirkbZ^q%5.+2)15+6&fkP^qvok^^oyyNFAy62.6y
KCobbqebEfde_lokbplriyNFAy..1-yyNLyCobbqebEfde_lokbplrifkP^qvok^^o7.,.yyKyCfkaqeb`ovpq^i_befkaqebpqor`qrobtebobvlrclrkaqeb`e^if`b%5.+25)15+25&y
KDbqtllayKy@liib`q2XP^qvok^^oCbiTllaZyyIy/1-5.2yyNFAy62.4y

@>dbkqplcAbpqor`qflkyKyQebkbbabajl_p^obclrka^olrkaqebT^oplkdIrj_bo@^jm^olrka%54)24&+Vlr`^kcfkaLsbopbboDloqe^hfkqeb_rfiafkd^q%56)3-&+@liib`qtllacoljqebIrj_boMfibpclo>Pe^jbcriT^pqbyyNFAy62.5y
@>Pe^jbcriT^pqbyKyXT^oplkdIrj_boZ^ob`liib`qbacoljqebIrj_boMfibpfkqebT^oplkdIrj_bo@^jm^olrka%54)24&+XP^qvok^^oCbiTllaZ`^k_bclrkacoljQ^fkqbaTllaMfibp^olrka%5/)2-&fkP^qvok^^oyyNFAy62.4y
@Ob`i^fjfkdCbicfobEfiiyKyMi^kqqebXQobbPbbaifkdpZlkqebCboqfibAfoqJlrka^qCbicfobEfii^olrka%5/)32&yyRy/0455yyNFAy62/3y
HHfiifkcbok^ipyKyHfiifkcbok^ip)i^pebop^kacbidr^oap^olrka%5/)36&rkqfivlrdbqqebXAf^_lif`^iMi^kpZ+Alk$qtloov^_lrq`ljmibqfkdAbpqolvqebIbdflkofdeqklt)vlr$ii_b_^`hyyIy/0444yyNFAy62/-y

@Clop^hbkAfpb^pbpyKyQebX?lqqiblcAfpb^pbZ`^k_bclrkalk^q^_ib^q%42+0)4/+0&kb^oqebAlo$A^kfi?^ooltAbkyyNFAy.-..y
@C^iibkPhvI^hbyKyObqofbsb^XC^iibkJllkpqlkbZtef`efpaolmmba_vqebPe^abqef`hbqLo^`ib%33+4)5/+.&lkqebfpi^kalkqeb`bkqbolcqebi^hbyyNFAy.-02y

@QebQltbolc>iqe^i^uu%M^oq3&yKyCobbqebqo^mmbaEfde_lokbplripfkKfdeqOrk%33)23&^kaP^qvok^^o%5.)16&yyNFAy..1-y
@P^qvoPi^vfkdyKyDbq.3XP^qvoElokpZ^olrka%5.)16&yyNFAy.-0/y
@O^bkb$p@ib^kpfkd%M^oq1&yKyQo^sbiql%21)02&^kahfiiqebproolrkafkdQob^kqprkqfivlr$sb`liib`qbaqebhbvqebklmbkqeb`ebpqkb^o_vyyNFAy.-/3y
@QebEltifkdS^ibyKyQo^sbiqlqeb`^sb^q%20)04&tef`evlrjrpqqo^sbiqeolrderkqfivlrob^`eqebQljb$pil`^qflk^q%2-+2)06+.&tef`evlrjrpqob^ayyNFAy.-//y

E>pqo^k^^oyRy3615yyNFAy62/-y
QC^iibkPhvI^hbyKyMbiqro^pTefqbjllk%04+0)2.+5&yyNFAy.-02y

QQebQltbolc>iqe^i^uu%M^oq3&yKyAbidobkqebMrofcfbo%/3+/)05+4&yyNFAy..1-y
QO^bkb$p@ib^kpfkd%M^oq1&yKyPe^bi$aovk%20+2)13+0&yyNFAy.-/3y

CClobpqPlkdyKyOrkql>pqo^k^^oqebkciv)A^bivpef^%01+2)15&yyNFAy62/-y
QClop^hbkAfpb^pbpyKyH^vkbqePqfiitfka%52+0)11+4&yyNFAy.-..y
QQebIlpq@e^if`byKyH^vkbqePqfiitfka%52+0)11+4&yyNFAy62.6y
Q>Pe^jbcriT^pqbyKyDk^oi%54)12&*jlsbp^olrkaqefp^ob^yyNFAy62.4y
QOb`i^fjfkdCbicfobEfiiyKyDk^oi%54)12&*jlsbp^olrkaqefp^ob^yyNFAy62/3y
QQebEltifkdS^ibyKyPbkqfkbiJbivof^Colpqpe^alt%53+.)11+.&yyNFAy.-//y
Q>dbkqplcAbpqor`qflkyKyPbkqfkbiIr`fbiPq^otefpmbo%53+.)11+1&yyNFAy62.5y
>Af^_lif`^iMi^kpyKyQebfqbjXAf^_lif`^iMi^kpZpq^oqpnrbpq*aolmmba_vfkcbok^ip)i^pebop^kacbidr^oap^olrka%5/)36&yyRy/0444yyNFAy62/-y
QAf^_lif`^iMi^kpyKySfkaf`^qloSba^^o%53+2)10+4&yyNFAy62/-y
>Kbsbo>d^fkyKySfkaf`^qloSba^^o%53+2)10+4&yyNFAy62//y
QP^qvoPi^vfkdyKyFiifv^k^%54)10+2&yyNFAy.-0/y

@Kbsbo>d^fkyKyHfiiDlod^kklk%55+2)44+.&^kaAf^qelorpqebPbbhboteljlsbp^olrka%45)51&yyNFAy62//y
@AbpqolvqebIbdflkyKyPi^v3J^kklol`I^pebop)3Cbidr^oap^ka3Pb^ofkdFkcbok^iptef`e`^k_bclrkafkCbicfobEfii%5/)32&^kaAbjlkC^ii@^kvlk^kaAbjlkC^iiOfadb^olrka%51)44&yyNFAy62.3y
QKbsbo>d^fkyKySfkaf`^qloSba^^o%53+2)10+4&yyNFAy62//y
QAbpqolvqebIbdflkyKySfkaf`^qloSba^^o%53+2)10+4&yyNFAy62.3y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
