DugisGuideViewer:RegisterGuide("Wetlands (30-31)", "Hillsbrad Foothills (31-33)", "Alliance", "L", function()
return [[
AAA

C>r_boafkbyKyPro^i^fpC^otfka%51+4)10+5&yyWy>pebks^ibyyNFAy14/y

_Pqlojtfka@fqvyKyQ^hbqeb?l^qqlPqlojtfka@fqvyyWyA^ohpelobyyNFAy14/y

CJbkbqefiE^o_loyKyArkd^oIlkdaofkh%4-+6)4/+4&yyWyPqlojtfka@fqvyyNFAy14/y
>C^iilcArkJlaoyKyE^oil?^ok^_v%.-+6)22+6&yyNFAy14/y

@Ifcqfkdqeb@ropbyKyHfiiqeb@^mq^fkcloqebXFkqobmfaPqolkd_luHbvZ)t^ihrmqeboraaboqlob^`eefj%.2+2)/0+2&yyNFAy/6-y
QIfcqfkdqeb@ropbyKyFkqobmfa$pIl`hbaPqolkd_lu%.1+2)/1+.&+Lmbkqeb_lulk_lqqljcillolcqeb_l^q)fq$prkabot^qboyyNFAy/6-y
>QebBvblcM^ibqeyKyFkqobmfa$pIl`hbaPqolkd_lu%.1+2)/1+.&yyNFAy/6/y
QKbh$olpe$pD^j_fqyKyAo^dlkj^t@^q^mriq%14+2)13+6&+Phfmqebcliilt*rmyyNFAy132y

QC^iilcArkJlaoyKyIlkd_o^faqebDofj%16+5).5+0&yyNFAy14/y
>QebA^ohFolkT^oyKyJlqibvD^oj^plk%16+4).5+0&yyNFAy0-0y
>>DofjQ^phyKyIlkd_o^faqebDofj%16+5).5+0&yyNFAy0-1y

>QebQe^kaliPm^k%M^oq.&yKyOe^dD^oj^plk%16+6).5+0&yyNFAy30.y
QQebQe^kaliPm^k%M^oq.&yKyB_bkbwboOrpqil`hb$p@lompb*Eb^alrqqlqebjfaaiblcQe^kaliPm^k)eb^aaltkqebpq^fopqlqebofdeq%2.+/)5+-&yyNFAy30.y
>QebQe^kaliPm^k%M^oq/&yKyB_bkbwboOrpqil`hb$p@lompb%2.+/)5+-&yyNFAy30/y
QQebQe^kaliPm^k%M^oq/&yKyOe^dD^oj^plk%16+6).5+0&yyNFAy30/y
>QebQe^kaliPm^k%M^oq0&yKyOe^dD^oj^plk%16+6).5+0&yyNFAy300y

@>DofjQ^phyKyHfii?^id^o^pqebClriqldbqefpb^o+@eb`h^qqeb`^jmqlqebb^pq%3-)/4&yyNFAy0-1y
@QebA^ohFolkT^oyKyVlr`^kcfkaqebjfk_lqe`^jmp%14+5).4+0&^ka%3-+4)/.+4&yyNFAy0-0y

Q>DofjQ^phyKyIlkd_o^faqebDofj%16+5).5+0&yyNFAy0-1y
QQebA^ohFolkT^oyKyJlqibvD^oj^plk%16+4).5+0&yyNFAy0-0y

@QebQe^kaliPm^k%M^oq0&yWy>o^qefEfdei^kapyyKy>`olppQe^kaliPm^k)qebk^`olppqebpj^ii_ofadbqlqebb^pq%15)55&yyNFAy300y
QQebQe^kaliPm^k%M^oq0&yKyOe^dD^oj^plk%16+6).5+0&yyNFAy300y
>Mib^QlQeb>iif^k`byKyOe^dD^oj^plk%16+6).5+0&yyNFAy301y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
