DugisGuideViewer:RegisterGuide("Hillsbrad Foothills (31-33)", "Desolace (33-35)", "Alliance", "L", function()
return [[
AAA

OObcrdbMlfkqbyKyFk>o^qefEfdei^kap%11+2)16+0&yyWy>o^qefEfdei^kapyyNFAy6102y
QMib^QlQeb>iif^k`byKy@^mq^fkKf^ip%12+5)14+2&yyWy>o^qefEfdei^kapyyNFAy301y

OPlrqepelobyKyFkEfiip_o^aCllqefiip%2-+5)2.+/&yyNFAy6102y
QPlrqepelobyKyIlobj^pqboAf__p%2-)24&yyLyyNFAy205y
ePlrqepelobyKyFkkhbbmbo>kaboplk%2.+.)25+6&yyNFAy6102y
>Jfppfkd@ovpq^ipyKyEro^^k%2.)25+4&yyNFAy6102y
>Altkqeb@l^pqyKyIfbrqbk^kqC^oobkLofkbiib%2.+1)25+2&yyNFAy203y
>PllqefkdQroqib?fpnrbyKy@ebcGbppbk%2.+5)25+4&yyNFAy222y
>?^oqlil$pVbqfCro@il^hyKy?^oqlilDfkpbqqf%16+2)22+3&yyNFAy232y
>@lpqivJbk^`byKyA^oobkJ^isbt%2/+1)23&yyNFAy231y
>Pvkaf`^qb>pp^ppfkpyKyJ^dfpqo^qbEbkovJ^ib_%15+/)26+/&yyNFAy2-2y

@Altkqeb@l^pqyKyHfii.-QlokCfkQfaberkqbop^ka.-QlokCfkLo^`ibptef`e`^k_bclrkaaltkqeb`l^pqqlqebPlrqetbpq^olrka%11)34&yyNFAy203y
QAltkqeb@l^pqyKyIfbrqbk^kqC^oobkLofkbiib%2.+1)25+2&yyNFAy203y
>C^oobk$pMollc%M^oq.&yKyIfbrqbk^kqC^oobkLofkbiib%2.+1)25+2&yyNFAy226y
@C^oobk$pMollc%M^oq.&yKy@liib`q.-XJroil`Eb^apZcoljqebjroil`pclrkalkqebTbpqbokPqo^kaqlqebPlrqetbpq^olrka%11)34&yyNFAy226y
QC^oobk$pMollc%M^oq.&yKyIfbrqbk^kqC^oobkLofkbiib%2.+1)25+2&yyNFAy226y
>C^oobk$pMollc%M^oq/&yKyIfbrqbk^kqC^oobkLofkbiib%2.+1)25+2&yyNFAy23-y
QC^oobk$pMollc%M^oq/&yKyJ^ope^iObam^qe%16+2)25+4&yyNFAy23-y
>C^oobk$pMollc%M^oq0&yKyJ^ope^iObam^qe%16+2)25+4&yyNFAy23.y
QC^oobk$pMollc%M^oq0&yKyIfbrqbk^kqC^oobkLofkbiib%2.+1)25+2&yyNFAy23.y
>PqlojtfkaElyKyIfbrqbk^kqC^oobkLofkbiib%2.+1)25+2&yyNFAy23/y
@PqlojtfkaElyKyHfii.-A^ddbopmfkbPeloberkqbop^ka.-A^ddbopmfkbPfobkptef`e^obclrkaqlqebPlrqeb^pq^`olpp^kakb^oqebofsbo^q%23)32&yyNFAy23/y
QPqlojtfkaElyKyIfbrqbk^kqC^oobkLofkbiib%2.+1)25+2&yyNFAy23/y
>Ob^ppfdkjbkqyKyIfbrqbk^kqC^oobkLofkbiib%2.+1)25+2&yyNFAy230y

KHfiiqroqibpyKy>ii^ilkdqeb`obbh+KbbaXQroqibJb^qZu.-cloPllqefkdQroqib?fpnrbyyIy04./.-yyNFAy222y
@Jfppfkd@ovpq^ipyKyObqofbsbqebXPefmjbkqlcO^ob@ovpq^ipZ%22+2)02+.&coljqebClop^hbkyyNFAy6102y

>Bk`ovmqbaIbqqboyKyPvkaf`^qbAl`rjbkqp%25+0)34+5&yyWy>iqbo^`Jlrkq^fkpyyNFAy2..y
>Clob_lafkdMi^kpyKyPvkaf`^qbAl`rjbkqp%25+0)34+5&yyWy>iqbo^`Jlrkq^fkpyyNFAy2.-y
@Pvkaf`^qb>pp^ppfkpyKyHfii./Pvkaf`^qbCllqm^ap^ka5Pvkaf`^qbQefbsbptef`e`^k_bclrka^qqeb@^jmpqlqebB^pq%24)33&^kaTbpq%15)44&_bclobbkqbofkd>iqbo^`Jlrkq^fkpyyWy>iqbo^`Jlrkq^fkpyyNFAy2-2y
@@lpqivJbk^`byKyHfii5Jlrkq^fkIflkp^ka.-ErihfkdJlrkq^fkIflkptef`e^obclrka`ljjlkivqlqebTbpqlcqebbkq^k`bql>iqbo^`Jlrkq^fkp^olrka%10)5-&yyWy>iqbo^`Jlrkq^fkpyyNFAy231y

HHfiivbqfpyKyFkqebvbqf`^sb%12+25)0.+1-&+KbbaXVbqfCroZu.-clo?^oqlil$pVbqfCro@il^hyyIy04/-.-yyNFAy232y

?CfkbQeob^ayIy/0/.yyKyColjJf`e^V^k`bfkPlrqepelob%16+-)22+.&yyNFAy2.1y
QBk`ovmqbaIbqqboyKyIlobj^pqboAf__p%2-)24&yyNFAy2..y
>IbqqboqlPqlojmfhbyKyIlobj^pqboAf__p%2-)24&yyNFAy2.1y
QPvkaf`^qb>pp^ppfkpyKyJ^dfpqo^qbEbkovJ^ib_%15+/)26+/&yyNFAy2-2y
QClob_lafkdMi^kpyKyJ^dfpqo^qbEbkovJ^ib_%15+/)26+/&yyNFAy2.-y
QPllqefkdQroqib?fpnrbyKy@ebcGbppbk%2.+5)25+4&yyNFAy222y
QJfppfkd@ovpq^ipyKyEro^^k%2.)25+4&yNFAy6102y
Q@lpqivJbk^`byKyA^oobkJ^isbt%2/+1)23&yyNFAy231y

CJbkbqefiE^o_loyKyA^oi^E^oofp%16+1)2/+0&yyNFAy/60y
QQebBvblcM^ibqeyKyDilofkPqbbi_olt%.-+3)3-+2&yyWyTbqi^kapyyNFAy/6/y
>@ib^kpfkdqebBvbyKyDilofkPqbbi_olt%.-+3)3-+2&yyWyTbqi^kapyyNFAy/60y

C@fqvlcFolkclodbyKyPebiibf?olkafo%6+2)22+4&yyWyTbqi^kapyyNFAy2/2y
QIbqqboqlPqlojmfhbyKyMolpmb`qloPqlojmfhb%42)./&yyWyFolkclodbyyNFAy2.1y
>CroqeboJvpqbofbpyKyMolpmb`qloPqlojmfhb%42)./&yyWyFolkclodbyyNFAy2/2y
>Ob`i^fjbop$?rpfkbppfkAbpli^`byKyOlbqqbkPqlkbe^jjbo%36)/-&*t^ihp^olrkaqefp^ob^yyWyFolkclodbyyNFAy.120y

CPqlojtfka@fqvyKyFkqeb`bkqbolcqltk^qqebClodb%22+22)14+43&yyNFAy3.1yyWyFolkclodby
QOb^ppfdkjbkqyKyJ^gloP^jrbiplk%42+6)03+5&yyWyPqlojtfka@fqvyyNFAy230y
Q@ib^kpfkdqebBvbyKy>o`e_fpelm?bkbaf`qrp%2-+0)12+4&yyWyPqlojtfka@fqvyyNFAy/60y
>?olqebo>kqlkyKyQefpobnrfobpibsbi01ql^``bmq)grpqphfmfqfcvlr$obklqibsbi01vbq+?olqebo@oltibv%2/+2)10+2&yyWyPqlojtfka@fqvyyNFAy3.1.y
??liqlcTllibk@ilqeyIy/664yyKy?rvcolj^r`qflklo^q^filoy
?Efiij^k$p@il^hyIy04.6yyKy?rvcolj^r`qflklo^ib^qebotlohboy

EPlrqepelobyRy3615y
Q?^oqlil$pVbqfCro@il^hyKy?^oqlilDfkpbqqf%16+2)22+3&yyNFAy232y
QCroqeboJvpqbofbpyKyJ^dfpqo^qbEbkovJ^ib_%15+/)26+/&yyNFAy2/2y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
