DugisGuideViewer:RegisterGuide("Desolace (33-35)", "Stranglethorn Vale (36-37)", "Alliance", "L", function()
return [[
AAA

CJbkbqefiE^o_loyKyA^oi^E^oofp%16+1)2/+0&yyWyEfiip_o^aCllqefiipyyNFAy.104y
_Qebo^jlobFpibyKyQ^hbqeb_l^qlkqebplrqebokmfboyyNFAy.104y
C>pqo^k^^oyKy?^iaor`%34+2)2.+0&yyWyArpqt^iiltJ^opeyyNFAy.104y
KOrkQeolrdeQ^ilkabbmM^qeyKyDlqeolrdeqebqrkkbi%1/+5)40&yyWy>pebks^ibyyNFAy.104y
OAbpli^`byKyOrkPlrqeqlAbpli^`b%/4)52+6&yyWyPqlkbq^ilkJlrkq^fkpyyNFAy.104y
OKfgbi$pMlfkqyKyKfgbi$pMlfkqfp^ilkdqebkloqebokbadblcAbpli^`b%31).-&yyNFAy.104y

>S^ei^oofbi$pPb^o`e%M^oq.&yKyS^ei^oofbiAbjlkpi^vbo%33+2)..+5&yyNFAy.104y
>@bkq^ro?lrkqvyKy@lomlo^iJbihfkp%33+4).-+6&yyNFAy.054y
QOb`i^fjbop$?rpfkbppfkAbpli^`byKyHobiafdRkdlo%33+/)6+4&yyNFAy.120y
>Ob^dbkqpcloOb`i^fjbopFk`+%M^oq.&yKyHobiafdRkdlo%33+/)6+4&yyNFAy.125y
>QebH^okfqliPefmtob`h%M^oq.&yKyHobiafdRkdlo%33+/)6+4&yyNFAy.121y
eKfgbi$pMlfkqyKyFkkhbbmboIvpe^bov^%33+0)3+4&yyNFAy.132y
Q?olqebo>kqlkyKy?olqebo>kqlk%33+2)4+5&yyNFAy3.1.y

QS^ei^oofbi$pPb^o`e%M^oq.&yKyJ^ibj@ebpq%23+3).4+5&yyNFAy.104y
>S^ei^oofbi$pPb^o`e%M^oq/&yKyJ^ibj@ebpq%23+3).4+5&yyNFAy.132y
@Ob^dbkqpcloOb`i^fjbopFk`+%M^oq.&yKyHfiiE^qbcrovp^qvopqlqebb^pq^qP^odbolk%42)/-&yyNFAy.125y

QS^ei^oofbi$pPb^o`e%M^oq/&yKyS^ei^oofbiAbjlkpi^vbo%33+2)..+5&yyNFAy.132y
>S^ei^oofbi$pPb^o`e%M^oq0&yKyS^ei^oofbiAbjlkpi^vbo%33+2)..+5&yyNFAy.105y
QOb^dbkqpcloOb`i^fjbopFk`+%M^oq.&yKyHobiafdRkdlo%33+/)6+4&yyNFAy.125y
>Ob^dbkqpcloOb`i^fjbopFk`+%M^oq/&yKyHobiafdRkdlo%33+/)6+4&yyNFAy.126y

KHfiiP`lom^pef^ka>dbaHlal^pvlrnrbpqyNFAy.126y
>?lkb@liib`qloyKy?f__ivC$rqw_r`hib%3/+0)05+6&yyNFAy22-.y
@@bkq^ro?lrkqvyKy@liib`q.2uX@bkq^roB^opZ^qqebHlih^oSfii^db%4/)12&yyNFAy.054y
>HlalOlrkarmyKyPjbbaP`o^__ibp`obt%3-+5)3.+6&yyNFAy223.y
@HlalOlrkarmyRy.056/yyKyRpbqebXHlalHlj_l_ri^qloZlkHlalfkqebdo^sbv^oa%2.)26&qebkq^hbqebhlal_^`hqlP`o^__ibp`obtyyNFAy223.y
QHlalOlrkarmyKyPjbbaP`o^__ibp`obt%3-+5)3.+6&yyNFAy223.y
@?lkb@liib`qloyKyIllqqebXHlal?lkbpZivfkd^olrkaqebdo^sbv^oa%2.)26&yyNFAy22-.y

>P`bmqoblcIfdeqyKy>wlob>ia^jloq%05+6)/4+/&yyNFAy241.y
QS^ei^oofbi$pPb^o`e%M^oq0&yKyA^ifka^J^ibj%21)/3&+Qebj^fk_rfiafkd^qqeb`bkqbolcQerkabo>ubCloqobppyyNFAy.105y
>Pb^o`ecloQvo^kfpyKyA^ifka^J^ibj%21)/3&yyNFAy.106y
@P`bmqoblcIfdeqyKyHfiiqeb?rokfkd?i^abPbbo^qqebqlmlcqebt^q`eqltbogrpqlrqpfab%22+/0)0-+.0&yyNFAy241.y
@Pb^o`ecloQvo^kfpyKyClrkafkpfabqeb_rfiafkdtbpq%20+-)/6+-&yyNFAy.106y
QPb^o`ecloQvo^kfpyKyA^ifka^J^ibj%21+6)/3+/&&Cliilt*rmfp^kbp`loqpl_bob^avyyNFAy.106y
>ObqrokqlS^ei^oofbiyKyA^ifka^J^ibj%21)/3&yyNFAy.11-y
@ObqrokqlS^ei^oofbiyKyBp`loqA^ifka^+Pebj^vfdklobjl_p)plalk$q^qq^`h^kvqefkdrkibpppeb^qq^`hplofp^qq^`hbayyNFAy.11-y

Q?lkb@liib`qloyKy?f__ivC$rqw_r`hib%3/+0)05+6&yyNFAy22-.y
QP`bmqoblcIfdeqyKy>wlob>ia^jloq%05+6)/4+/&yyNFAy241.y
>?llhlcqeb>k`fbkqpyKy>wlob>ia^jloq%05+6)/4+/&yyNFAy3-/4y
QQebH^okfqliPefmtob`h%M^oq.&yKy>qqebpefmtob`hlkqeb`l^pq%03+.)0-+1&yyNFAy.121y
>QebH^okfqliPefmtob`h%M^oq/&yKyH^okfqli$p@ebpq%03+.)0-+1&yyNFAy.122y
>@i^fjO^`hjlob$pQob^probyKyO^`hjlob$pIld%03+.)0-+2&+Clrkalk^_^oobi_bpfabqebH^okfqli@ebpqyyNFAy3.3.y
@@i^fjO^`hjlob$pQob^probyKyHfiiAovpk^mMfk`bop^ka@o^tibopcloXO^`hjlob$pPfisboHbvZ^q%0/)/6&rkabot^qbo+HfiiPifqebo_i^abK^d^cloXO^`hjlob$pDliabkHbvZ^q%0/)//&yyNFAy3.3.y

Q@i^fjO^`hjlob$pQob^probyKyO^`hjlob$p@ebpq%0-+-)5+4&+?befka^qobblkO^k^wg^oFpibyyNFAy3.3.y
@?llhlcqeb>k`fbkqpyKy@ib^oqeb^ob^^olrkaqebpq^qrb%/5)4&qebkq^ihqlfq^kahfiiqebk^d^qe^qpm^tkpyyNFAy3-/4y
Q?llhlcqeb>k`fbkqpyKy>wlob>ia^jloq%05+6)/4+/&yyNFAy3-/4y

@Ob^dbkqpcloOb`i^fjbopFk`+%M^oq/&yKyDbqqebi^pqcbtob^dbkqpvlrkbba%32)/2&vlrpelriae^sbjlpq_vkltyyNFAy.126y

EKfgbi$pMlfkqyRy3615y
QOb^dbkqpcloOb`i^fjbopFk`+%M^oq/&yKyHobiafdRkdlo%33+/)6+4&Phfmqebcliilt*rmyyNFAy.126y
QQebH^okfqliPefmtob`h%M^oq/&yKyHobiafdRkdlo%33+/)6+4&Phfmqebcliilt*rmyyNFAy.122y
Q@bkq^ro?lrkqvyKy@lomlo^iJbihfkp%33+4).-+6&yyNFAy.054y
QObqrokqlS^ei^oofbiyKyS^ei^oofbiAbjlkpi^vbo%33+2)..+5&yyNFAy.11-y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
