DugisGuideViewer:RegisterGuide("Stranglethorn Vale (36-37)", "Dustwallow Marsh (37-38)", "Alliance", "L", function()
return [[
AAA

CQebo^jlobFpibyKy?^ofq^k^pPhvofsbo%31+4).-+2&yyWyAbpli^`byyNFAy.65y
OO^q`ebqyKyOrkrmqeb`l^pqqlO^q`ebq%3.+6)03+2&+T^q`elrqcloqebjroil``^jm^ilkdqebt^v+Fhkltfq$p^kklvfkd)_rqfq$p`boq^fkiv^kf`boorkqe^kqeblkbcoljqebkloqebkalcPQSyyWyQeb?^oobkpyyNFAy.65y
_?llqv?^vyKyQ^hbqeb_l^qcoljO^q`ebqql?llqv?^vyyNFAy.65y
>PrmmifbpqlMofs^qbQelopbkyKyHo^wbh%/4)44+/&yyNFAy.65y
>Fksbpqfd^qbqeb@^jmyKyHo^wbh%/4)44+/&yyNFAy/-.y
>ElpqfibQ^hblsboyKyHb_lh%/4)44+/&yyNFAy/.0y
>Prmmiv^kaAbj^kayKyAofwwifh%/5+0)44+2&yyNFAy242y

COb_bi@^jmyKyDvii%/4+2)44+4&yyNFAy/-0y
QPrmmifbpqlMofs^qbQelopbkyKyMofs^qbQelopbk*jlsbp_bqtbbk%05)0&^ka%1-)5&yyNFAy.65y
>QebPb`lkaOb_biiflkyKyPbodb^kqVlet^%05)0+1&yyNFAy/-0y
>?^aJbaf`fkbyKyPbodb^kqVlet^%05)0+1&yyNFAy/-1y

@Fksbpqfd^qbqeb@^jmyKyCfkaqeberkqbop$`^jm%02+4).-+5&^kaobmloqfqpil`^qflkqlHo^wbhyyNFAy/-.y
>Tbi`ljbqlqebGrkdibyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy250y
QTbi`ljbqlqebGrkdibyKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy250y

>QfdboJ^pqbov%M^oq.&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.52y
>M^kqeboJ^pqbov%M^oq.&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6-y
>O^mqloJ^pqbov%M^oq.&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.61y

@QfdboJ^pqbov%M^oq.&yKyHfii.-VlrkdPqo^kdibqelokQfdbopclrka^olrka%01).0&yyNFAy.52y
@Prmmiv^kaAbj^kayKyHfiiqebOfsbo@ol`lifphclrka^olrka%02)./&rkqfivlr$sb`liib`qba/XI^odbOfsbo@ol`lifphPhfkpZyyNFAy242y
@M^kqeboJ^pqbov%M^oq.&yKyHfii.-VlrkdM^kqeboptef`e`^k_bclrkaqlqebKloqe^olrka%06)6&yyNFAy.6-y

QM^kqeboJ^pqbov%M^oq.&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6-y
>M^kqeboJ^pqbov%M^oq/&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6.y

QQfdboJ^pqbov%M^oq.&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.52y
>QfdboJ^pqbov%M^oq/&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.53y

@QfdboJ^pqbov%M^oq/&yKyHfii.-Pqo^kdibqelokQfdbopqlqebPlrqelcqeb`^jm^olrka%/6+5.)6+13&yyNFAy.53y
@M^kqeboJ^pqbov%M^oq/&yKyHfii.-M^kqebopclrkaqlqebTbpq^olrka%0-).0&yyNFAy.6.y
@O^mqloJ^pqbov%M^oq.&yKyHfii.-Pqo^kdibqelokO^mqloptef`e^obclrkaqlqebTbpq^olrka%/4).5&yyNFAy.61y

QQfdboJ^pqbov%M^oq/&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.53y
>QfdboJ^pqbov%M^oq0&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.54y
QO^mqloJ^pqbov%M^oq.&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.61y
>O^mqloJ^pqbov%M^oq/&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.62y
QM^kqeboJ^pqbov%M^oq/&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6.y
>M^kqeboJ^pqbov%M^oq0&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6/y

@ElpqfibQ^hblsboyKy@liib`q5XQrj_iba@ovpq^ipZcoljqebDblildfpqpclrka^qqebSbkqrob@l+@^jm^q%12)/-&yyNFAy/.0y

@?^aJbaf`fkbyKyHfii^kvlcqebHrowbkTfq`eAl`qlop)Jbaf`fkbJbkloEb^apeofkhbopclrkafkqebHrowbk@ljmlrka^olrka%12)4&cloqebXGrkdibObjbafbpZ+QebXSbkljCbokBuqo^`qZ`^k_bclrkacoljqebHrowbkPrmmifbp^q%11+2)6+5&yyNFAy/-1y
@QebPb`lkaOb_biiflkyKyHfii.2HrowbkGrkdibCfdeqboptef`e^obclrkafkqeb@^jmqlqebb^pq^olrka%1/)..&yyNFAy/-0y

QQebPb`lkaOb_biiflkyKyPbodb^kqVlet^%05)0+1&yyNFAy/-0y
Q?^aJbaf`fkbyKyPbodb^kqVlet^%05)0+1&yyNFAy/-1y
>Ho^wbh$p@llhbovyKy@lomlo^iH^ib_%04+5)0+0&yyNFAy/.-y

C?llqv?^vyKyKfwwib%05+.)0+5&yyNFAy244y
QElpqfibQ^hblsboyKyHb_lh%/4)44+/&yyNFAy/.0y
QFksbpqfd^qbqeb@^jmyKyHo^wbh%/4)44+/&yyNFAy/-.y
QHo^wbh$p@llhbovyKyHo^wbh%/4)44+/&yyNFAy/.-y
QPrmmiv^kaAbj^kayKyAofwwifh%/5+0)44+2&yyNFAy242y
>Pljb>ppbj_ivObnrfobayKyAofwwifh%/5+0)44+2&yyNFAy244y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby

]]
end)
