DugisGuideViewer:RegisterGuide("Dustwallow Marsh (37-38)", "Stranglethorn Vale (38-40)", "Alliance", "L", function()
return [[
AAA

_O^q`ebqyKyQ^hbqeb_l^qqlO^q`ebqyyNFAy...6.y
CQebo^jlobFpibyKy?o^dlh%30+.)04+/&yyWyQeb?^oobkpyyNFAy...6.y
>QefpLiaIfdeqelrpbyKyPbodb^kq>jbivk%34+6)2.+3&yyNFAy...6.y
QQefpLiaIfdeqelrpbyKy?^_pCfwwibqlonrb%4/)14+.&yyNFAy...6.y
>QeobpeboLfiyKy?^_pCfwwibqlonrb%4/)14+.&yyNFAy...6/y
@QeobpeboLfiyKyDbq1`lkq^fkboplcXQeobpeboLfiZaolmmba_vVlrkdJrohQeobpebo^olrka%4/)2.&yyNFAy...6/y
QQeobpeboLfiyKy?^_pCfwwibqlonrb%4/)14+.&yyNFAy...6/y
>A^pq^oaivAbkfwbkplcqebAbbmyKy?^_pCfwwibqlonrb%4/)14+.&yyNFAy...60y
QA^pq^oaivAbkfwbkplcqebAbbmyKyAfoqvJf`e^bi@oltb%36+.)2/+.&yyNFAy...60y
>FpfqOb^i<yKyAfoqvJf`e^bi@oltb%36+.)2/+.&yyNFAy...61y

>Qo^fqlop>jlkdRpyKy@^if^E^pqfkdp%35+.)2.+.&yyNFAy.../3y
@Qo^fqlop>jlkdRpyKy@lkcolkq2Abpboqbo>dfq^qlop^olrka%34)2.&yyNFAy.../3y
QQo^fqlop>jlkdRpyKy@^if^E^pqfkdp%35+.)2.+.&yyNFAy.../3y
>Molm^d^ka^T^oyKy@^if^E^pqfkdp%35+.)2.+.&yyNFAy.../5y
@Molm^d^ka^T^oyKyDbqqebXAbpboqboMolm^d^ka^Z%34+6)25+4&yyNFAy.../5y
QMolm^d^ka^T^oyKy@^if^E^pqfkdp%35+.)2.+.&yyNFAy.../5y
>Afp`obafqfkdqebAbpboqbopyKy@^if^E^pqfkdp%35+.)2.+.&yyNFAy...00y
@Afp`obafqfkdqebAbpboqbopyKyAfpqof_rqbqebX>iqbobaIb^cibqpZql3Qebo^jlobDr^oap^olrka%31)14&yyNFAy...00yyRy00-.2y
QAfp`obafqfkdqebAbpboqbopyKy@^if^E^pqfkdp%35+.)2.+.&yyNFAy...00y
>QebBkalcqebAbpboqbopyKy@^if^E^pqfkdp%35+.)2.+.&yyNFAy...01y
@QebBkalcqebAbpboqbopyKy@^mqrobD^sfpDobvpefbia%43+/)24&yyNFAy...01y
QQebBkalcqebAbpboqbopyKy@^if^E^pqfkdp%35+.)2.+.&yyNFAy...01y

eQebo^jlobFpibyKyFkkhbbmboG^kbkb%33+3)12+0&yyNFAy./5/y
>Qebv@^iiEfjPjfifkdGfjyKyDr^oa?volk%33+/)13+.&yyNFAy./5/y
>Q^_bqe^$pC^ojyKyDr^oa?volk%33+/)13+.&yyNFAy.././y
QQebv@^iiEfjPjfifkdGfjyKy@^mq^fkD^oo^kSfjbp%35+/)15+2&yyNFAy./5/y
>Fkpmb`qfkdqebOrfkpyKy@^mq^fkD^oo^kSfjbp%35+/)15+2&yyNFAy.../0y
QQebJfppfkdAfmilj^q%M^oq.0&yKy@ljj^kaboP^j^ri%35)15+3&yyNFAy./31y
>QebJfppfkdAfmilj^q%M^oq.1&yKy@ljj^kaboP^j^ri%35)15+3&yyNFAy./32y
>>Afpqro_fkdAbsbilmjbkqyKyIfbrqbk^kq>abk%32+.)14+.&yyNFAy...03y

@QebJfppfkdAfmilj^q%M^oq.1&yKyBumilobqebPbkqovMlfkq^q%26)1/&yyNFAy./32y
QQebJfppfkdAfmilj^q%M^oq.1&yKy>o`ej^dbQboslpe%33+1)16+0&*il`^qbafkqebqltbo_rqalbpjlsb^olrkayyNFAy./32y
>QebJfppfkdAfmilj^q%M^oq.2&yKy>o`ej^dbQboslpe%33+1)16+0&*il`^qbafkqebqltbo_rqalbpjlsb^olrkayyNFAy./33y
Q>Afpqro_fkdAbsbilmjbkqyKy@^mq^fkTvjlo%26+5)1.+.&yyNFAy...03y
>Abcf^pfkArpqt^iilt<yKy@^mq^fkTvjlo%26+5)1.+.&yyNFAy...04y
@Abcf^pfkArpqt^iilt<yKyDbqqebXAbcf^pLoabopZcoljD^okJ^qebop%31)/5&yyNFAy...04y
QAbcf^pfkArpqt^iilt<yKy@^mq^fkTvjlo%26+5)1.+.&yyNFAy...04y
>ObkkJ`DfiiyKy@^mq^fkTvjlo%26+5)1.+.&yyNFAy...05y

>J^opeColdIbdpyKyPt^jmBvbG^oi%22+1)/3+0&yyNFAy./.5y
>Te^q$pE^rkqfkdTfq`eEfii<yKyJloa^kqDofjp_v%22+3)/3+0&yyNFAy...5-y
>QebLo`ObmloqyKyIllpbAfoq%22+2)/3&yyNFAy./.6y

@J^opeColdIbdpyKyDbq.-XJ^opeColdIbdpZaolmmba_vDf^kqJ^opeCold^olrka%23)/5&yyNFAy./.5y
@Te^q$pE^rkqfkdTfq`eEfii<yKyD^qebofkcloj^qflkcolj.-OfpbkErphp^olrka%21)/0&loOfpbkPmfofqp^olrka%24)/4&yyNFAy...5-y

QJ^opeColdIbdpyKyPt^jmBvbG^oi%22+1)/3+0&yyNFAy./.5y
>G^oiKbbapBvbpyKyPt^jmBvbG^oi%22+1)/3+0&yyNFAy./-3y

QTe^q$pE^rkqfkdTfq`eEfii<yKyJloa^kqDofjp_v%22+3)/3+0&yyNFAy...5-y
>QebTfq`e$p?^kbyKyJloa^kqDofjp_v%22+3)/3+0&yyNFAy...5.y
@QebTfq`e$p?^kbyKyDbq6pmofdplcXTfq`e_^kbZ^olrka%23)/4&yyNFAy...5.y
QQebTfq`e$p?^kbyKyJloa^kqDofjp_v%22+3)/3+0&yyNFAy...5.y
>@ib^kpfkdTfq`eEfiiyKyJloa^kqDofjp_v%22+3)/3+0&yyNFAy...50y
@@ib^kpfkdTfq`eEfiiyKyMi^kqqebXTfq`e_^kbQlo`eZ^qqebbkalcqebal`h%22+/)/3+3&^kahfiiqeb_^q`ob^qrobqe^q^mmb^opyyRy00..0yyNFAy...50y
Q@ib^kpfkdTfq`eEfiiyKyJloa^kqDofjp_v%22+3)/3+0&yyNFAy...50y

>O^mqlo@^mqloyKyPbodb^kqIrh^p%13+2)//+3&yyNFAy...13y
QQebJfppfkdAfmilj^q%M^oq.2&yKyMofs^qbEbkabi%12+/)/1+3&yyNFAy./33y
>QebJfppfkdAfmilj^q%M^oq.3&yKyMofs^qbEbkabi%12+/)/1+3&yyNFAy.0/1y
@QebJfppfkdAfmilj^q%M^oq.3&yKyAbcb^qMofs^qbEbkabi%12+/)/1+3&yyNFAy.0/1y
QQebJfppfkdAfmilj^q%M^oq.3&yKy>o`ej^dbQboslpe%33+1)16+0&*il`^qbafkqebqltbo_rqalbpjlsb^olrkayyNFAy.0/1y

@O^mqlo@^mqloyRy00-36yyKyRpbqebXPqroavOlmbZql`^mqrob3o^mqlop+Vlr`^k`^mqrobbfqebo?illacbkO^mqlop^olrka%15).5&lo?illacbkP`obb`ebop^olrka%15).4&yyNFAy...13y

>Pqfkhv$pBp`^mbyKyPqfkhvFdk^qw%13+6).4+2&yyNFAy.///y
@Pqfkhv$pBp`^mbyKyQefpfp^kbp`loqnrbpqtebobvlrjrpqmolqb`qefjrkqfieb$pclrka?ld_b^kIb^sbp+Vlrlkive^sbql^qq^`hqebjl_pfkefpm^qeplkldolrmpm^tkpl``roqeolrdeqefpyyNFAy.///y

QO^mqlo@^mqloyKyPbodb^kqIrh^p%13+2)//+3&yyNFAy...13y
>MofplkboplcqebDofjqlqbjpyKyPbodb^kqIrh^p%13+2)//+3&yyNFAy...12y
>Rkib^peqebO^mqlopyKyPbodb^kqIrh^p%13+2)//+3&yyNFAy...14y

@MofplkboplcqebDofjqlqbjpyKyCobb2Qebo^jlobMofplkbop%1/)./&+Hfiidofjqlqbjjl_pqldbqqebhbvpyyNFAy...12y
@Rkib^peqebO^mqlopyRy00-4-yyKyMi^`bqebXO^mqlo?^fqZkb^oqebtfkajfii%1.)..&fk?i^`hellcSfii^dbyyNFAy...14y

@G^oiKbbapBvbpyKyQebA^ohjfpqpmfabop`^k_bclrka^olrka%01)/0&qlqebTbpqfkqebA^ohjfpq@^sbokyyNFAy./-3y

QMofplkboplcqebDofjqlqbjpyKyPbodb^kqIrh^p%13+2)//+3&yyNFAy...12y
QRkib^peqebO^mqlopyKyPbodb^kqIrh^p%13+2)//+3&yyNFAy...14y

>ErkdovyKyJra`orpeAroqcbbq%02+.)05+/&yyNFAy..44y
QFkpmb`qfkdqebOrfkpyKyFkpmb`qloQ^obj%/6+3)14+2&yyNFAy.../0y
>Prpmf`flrpEllcmofkqpyKyEllcmofkqp%/6+4)14+4&yyNFAy./51y
>Ifbrqbk^kqM^s^iObbqeb%M^oq.&yKyQebo^jlobDr^oa?^adb%/6+5)15+/&yyNFAy./2/y
>Qeb?i^`hPefbia%M^oq.&yKy?i^`hPefbia%/6+3)15+3&yyNFAy./20y

>AfobelokO^fabopyKy>mmobkqf`bJloi^kk%13+.)24+2&yyNFAy...23y
>QebWbmmbifk@o^peyKy>mmobkqf`bJloi^kk%13+.)24+2&yyNFAy...4/y
QQ^_bqe^$pC^ojyKyQ^_bqe^%13)24+.&yyNFAy.././y
>QebDofjqlqbjTb^mlkyKy>mmobkqf`bD^oflk%13)24+/&yyNFAy...36y
>QebOb^dbkqQefbcyKy>mmobkqf`bD^oflk%13)24+/&yyNFAy...40y

@QebDofjqlqbjTb^mlkyKyQbpqqebX@^mqrobaQlqbjZlk.-JlqqibaAovt^iilt@ol`lifphp^olrka%1/)21&loAovt^iiltA^ddboj^tp^olrka%15)23&yyRy00.-.yyNFAy...36y
@QebOb^dbkqQefbcyKyDbq3sf^iplcXJ^opeSbkljZaolmmba_vKluflrpPeobaabo^kaA^ohc^kd@obbmbo^olrka%1/)2-&yyNFAy...40y

@AfobelokO^fabopyKyHfii./AfobelokDofjqlqbjp^olrka%13+3)14+0&yyNFAy...23y
H>mlqeb`^ov@vii^%13+4)14+/&yIy00..1yyNFAy...52y
>Qeb>mlqeb`^ov$pIbqqboyKyQebfqbjXPb^ibaIbqqboZpq^oqpqebnrbpq*aolmmba_v>mlqeb`^ov@vii^%13+4)14+/&yyRy00..1yyNFAy...52y

QAfobelokO^fabopyKy>mmobkqf`bJloi^kk%13+.)24+2&yyNFAy...23y
QQebDofjqlqbjTb^mlkyKy>mmobkqf`bD^oflk%13)24+/&yyNFAy...36y
QQebOb^dbkqQefbcyKy>mmobkqf`bD^oflk%13)24+/&yyNFAy...40y
QQeb>mlqeb`^ov$pIbqqboyKy>kabiilMloqbo%12+2)24+4&yyNFAy...52y

QQebWbmmbifk@o^peyKyJlufbPqbbidofiib%20+2)24&yyNFAy...4/y
>@loolpflkMobsbkqflkyKyJlufbPqbbidofiib%20+2)24&yyNFAy...41y
>Pb`robqeb@^odlyKyJlufbPqbbidofiib%20+2)24&yyNFAy../-4y

@@loolpflkMobsbkqflkyRy00.-5yyKyAfpplisb.-llwbp^olrka%20+.)23+2&rpfkdvlroXLlwb?rpqboZyyNFAy...41y
@Pb`robqeb@^odlyKyOb`lsbo5mfb`bplcXWbmmbifk@^odlZ^olrkaqeb^ob^%21)22&yyNFAy../-4y

Q@loolpflkMobsbkqflkyKyJlufbPqbbidofiib%20+2)24&yyNFAy...41y
QPb`robqeb@^odlyKyJlufbPqbbidofiib%20+2)24&yyNFAy../-4y
>AbifsbovcloAo^wwfqyKyJlufbPqbbidofiib%20+2)24&yyNFAy../-5y

QFpfqOb^i<yKyK^qM^dib%25+2)3-&yyNFAy...61y
>K^q$p?^od^fkyKyK^qM^dib%25+2)3-&yyNFAy../-6y
@K^q$p?^od^fkyKyQbpqXM^dib$pCfpeM^pqb)Buqo^PqobkdqeZ^qqebtob`hbapefm^q%24)3/&+>mmivqebm^pqb^qK^q$pI^kafkd^kaqebkptfjqlqebpefm+Hfiiqebpe^ohqe^q^qq^`hpvlryyRy00.33yyNFAy../-6y
QK^q$p?^od^fkyKyK^qM^dib%25+2)3-&yyNFAy../-6y
>Le)Fq$pOb^iyKyK^qM^dib%25+2)3-&yyNFAy../.-y

OJrapmol`hbqyKy?^`hlkqebj^fki^ka)cliiltqebol^aplrqetbpq%1/+0.)4/+61&yyNFAy...51y
QAbifsbovcloAo^wwfqyKyAo^wwfqAofms^isb%1/)40&yyNFAy../-5y
>T>KQBA7Dlob`i^tqebO^sbklrpyKyT^kqbaMlpqbo%1.+5)40+.&yyNFAy...51y
>@^q`e^Ao^dlk_vqebQ^fiyKyDfwwfuDofjbdrodib%1.+2)40&yyNFAy../.4y
>?illacbkCb^qebopyKy?oldd%1.+5)40+4&yyNFAy...25y

@T>KQBA7Dlob`i^tqebO^sbklrpyKyHfiiDlob`i^tqebO^sbklrp%0.)33&yyNFAy...51y
@?illacbkCb^qebopyKyDbq2X?illacbkCb^qebopZaolmmba_vo^mqlop^olrka%00)35&yyNFAy...25y

QT>KQBA7Dlob`i^tqebO^sbklrpyKyAo^wwfqAofms^isb%1/)40&yyNFAy...51y
Q?illacbkCb^qebopyKy?oldd%1.+5)40+4&yyNFAy...25y
>?^kkbolcqebPqlkbj^riyKy?oldd%1.+5)40+4&yyNFAy...3-y
>QebBppbk`blcBkjfqvyKy?oldd%1.+5)40+4&yyNFAy...3.y

@?^kkbolcqebPqlkbj^riyKyDlqlqeb`^sbbkqo^k`b^q%05)32&^kaobqofbsbqebXPqlkbj^ri?^kkboZcoljfkpfab^q%05+.)36+0&yyNFAy...3-y
@QebBppbk`blcBkjfqvyRy00-55yyKyDbq.-X?i^`hAo^dlkhfkBppbk`bpZ+Hfiiqebao^dlkhfk^q%05)33&^ka%12)33&^karpbX?oldd$pQlqbjZlkqebfo`lompbpqldbq^kbppbk`byyRy00-55yyNFAy...3.y

Q?^kkbolcqebPqlkbj^riyKy?oldd%1.+5)40+4&yyNFAy...3-y
QQebBppbk`blcBkjfqvyKy?oldd%1.+5)40+4&yyNFAy...3.y
>PmfofqplcPqlkbj^riEliayKy?oldd%1.+5)40+4&yyNFAy...26y

@PmfofqplcPqlkbj^riEliayKyMrq.-Pqlkbj^riPmfofqpqlobpqclrka^olrka%11)33&yyNFAy...26y

QPmfofqplcPqlkbj^riEliayKy?oldd%1.+5)40+4&yyNFAy...26y
>@e^iibkdbqlqeb?i^`hCifdeqyKy?oldd%1.+5)40+4&yyNFAy...3/y

@@e^iibkdbqlqeb?i^`hCifdeqyKyMi^kqqebXPqlkbj^ri?^kkboZkb^oqebbkqo^k`bqlLkvuf^$pI^fo%2/+5)43+/&^kat^fqcloLkvuf^$pobpmlkpbyyRy00-62yyNFAy...3/y
@@^q`e^Ao^dlk_vqebQ^fiyKyDbq5XTvojq^fiZclrka^olrka%13)44&yyNFAy../.4y

Q@e^iibkdbqlqeb?i^`hCifdeqyKy?oldd%1.+5)40+4&yyNFAy...3/y
Q@^q`e^Ao^dlk_vqebQ^fiyKyDfwwfuDofjbdrodib%1.+2)40&yyNFAy../.4y

EQebo^jlobFpibyRy3615yyNFAy...65y

QLe)Fq$pOb^iyKyJ^gloJfiip%36+3)2.+5&yyNFAy../.-y
>Q^hbAltkQbqevoyKyJ^gloJfiip%36+3)2.+5&yyNFAy...65y
@Q^hbAltkQbqevoyKyHfiiQbqevo^q%4-)2.&yyNFAy...65y
QQ^hbAltkQbqevoyKyJ^gloJfiip%36+3)2.+5&yyNFAy...65y
QPrpmf`flrpEllcmofkqpyKy@^mq^fkD^oo^kSfjbp%35+/)15+2&yyNFAy./51y
QIfbrqbk^kqM^s^iObbqeb%M^oq.&yKy@^mq^fkD^oo^kSfjbp%35+/)15+2&yyNFAy./2/y
>Ifbrqbk^kqM^s^iObbqeb%M^oq/&yKy@^mq^fkD^oo^kSfjbp%35+/)15+2&yyNFAy./26y
QQeb?i^`hPefbia%M^oq.&yKy@^mq^fkD^oo^kSfjbp%35+/)15+2&yyNFAy./20y
>Qeb?i^`hPefbia%M^oq/&yKy@^mq^fkD^oo^kSfjbp%35+/)15+2&yyNFAy.0.6y
QIfbrqbk^kqM^s^iObbqeb%M^oq/&yKy>agrq^kqQbplo^k%35)15+/&yyNFAy./26y
>A^bifk$pJbkyKy>agrq^kqQbplo^k%35)15+/&yyNFAy./52y
QA^bifk$pJbkyKy@^mq^fkD^oo^kSfjbp%35+/)15+2&yyNFAy./52y
>QebAbpboqbop%M^oq.&yKy@^mq^fkD^oo^kSfjbp%35+/)15+2&yyNFAy./53y
QPqfkhv$pBp`^mbyKyJlod^kPqbok%33+1)12+1&yyNFAy.///y
QQebLo`ObmloqyKyIfbrqbk^kq>abk%32+.)14+.&yyNFAy./.6y
>@^mq^fkSfjbpyKyIfbrqbk^kq>abk%32+.)14+.&yyNFAy.//-y
>JfppflkqlJrapmol`hbqyKyIfbrqbk^kq>abk%32+.)14+.&yyNFAy../.1y
QQeb?i^`hPefbia%M^oq/&yKy@^wQtlpmol`hbq%31+4)2-+1&yyNFAy.0.6y
>Qeb?i^`hPefbia%M^oq0&yKy@^wQtlpmol`hbq%31+4)2-+1&yyNFAy.0/-y
QQeb?i^`hPefbia%M^oq0&yKy@^mq^fkD^oo^kSfjbp%35+/)15+2&yyNFAy.0/-y
Q@^mq^fkSfjbpyKy@^mq^fkD^oo^kSfjbp%35+/)15+2&yyNFAy.//-y

QG^oiKbbapBvbpyKyPt^jmBvbG^oi%22+1)/3+0&yyNFAy./-3y
>G^oiKbbap^?i^abyKyPt^jmBvbG^oi%22+1)/3+0&yyNFAy./-0y

@G^oiKbbap^?i^abyKyDbqXO^wlopmfkb$pPtloaZaolmmba_vO^wlopmfkb^olrka%24).6&yyNFAy./-0y

@ErkdovyKyHfii^kvlcqebJfobcfkjroil`pclrka^olrka%25+.1).2+15&rkqfivlr$sb`liib`qba./XJfobcfkEb^apZyyNFAy..44y

QObkkJ`DfiiyKyObkkJ`Dfii%30+4).4+.&yyNFAy...05y
>Pb`lkae^kaAfsfkdDb^oyKyObkkJ`Dfii%30+4).4+.&yyNFAy...06y
@Pb`lkae^kaAfsfkdDb^oyKyDbqqebXQlliHfqZ^q%30).5+3&^kaXA^j^dbaAfsfkdDb^oZ^q%3/).5&yyNFAy...06y
QPb`lkae^kaAfsfkdDb^oyKyObkkJ`Dfii%30+4).4+.&yyNFAy...06y
>Ob`lsboqeb@^odlyKyObkkJ`Dfii%30+4).4+.&yyNFAy...1-y
RLmbkqebprmmifbpyRy00-12yyNFAy...1.y
RMrqlkqebAfsfkdDb^oyRy00-1-yyNFAy...1.y
@Ob`lsboqeb@^odlyKyDbq3XP^is^dbaPqolkd_lubpZclrka^olrkaqeb^ob^%31)/.&+Qebv^ob_bilt_rokfkdtob`h^dblkqebt^qbo$pproc^`b)afsb_bilt^karpbqebXP^is^dbHfqZlkqebab_ofpyyRy00-11yyNFAy...1-y
QOb`lsboqeb@^odlyKyObkkJ`Dfii%30+4).4+.&yyNFAy...1-y
>G^fk^JrpqHkltyKyObkkJ`Dfii%30+4).4+.&yyNFAy...1.y

QG^oiKbbap^?i^abyKyPt^jmBvbG^oi%22+1)/3+0&yyNFAy./-0y
QErkdovyKyJra`orpeAroqcbbq%02+.)05+/&yyNFAy..44y
QQebAbpboqbop%M^oq.&yKy?^ilpG^`hbk%03)21&yyNFAy./53y
>QebAbpboqbop%M^oq/&yKy?^ilpG^`hbk%03)21&yyNFAy./54y

EQebo^jlobFpibyRy3615yyNFAy...1/y
QG^fk^JrpqHkltyKyI^avG^fk^Molrajllob%33+0)16+.&yyNFAy...1.y
>Prosbv>i`^wFpi^kayKyI^avG^fk^Molrajllob%33+0)16+.&yyNFAy...1/y
QQebAbpboqbop%M^oq/&yKy@^mq^fkD^oo^kSfjbp%35+/)15+2&yyNFAy./54y
>>Dofj@lkkb`qflkyKy@^mq^fkD^oo^kSfjbp%35+/)15+2&yyNFAy...10y
@Prosbv>i`^wFpi^kayKyPmb^hql@^pp^@ofjplktfkd%34+0)2.&^karpblkblcebodovmelkpqlprosbv>i`^wFpi^kayyNFAy...1/y
QProsbv>i`^wFpi^kayKyI^avG^fk^Molrajllob%33+0)16+.&yyNFAy...1/y

Q>Dofj@lkkb`qflkyKy@^mq^fkA^ofii%13+3)/1+4&yyNFAy...10y
>@lkcfojfkdqebPrpmf`flkyKy@^mq^fkA^ofii%13+3)/1+4&yyNFAy...11y
>>ojplcqebDofjqlqbjpyKy@^mq^fkA^ofii%13+3)/1+4&yyNFAy...15y

@>ojplcqebDofjqlqbjpyKyDbq4X?i^`hellc>oj^jbkqpZ^olrka%1/).1&yyNFAy...15y
@@lkcfojfkdqebPrpmf`flkyKyHfiiDofjqlqbjBiabop%1/+1).0+4&ql`liib`q1XDofjqlqbjklqbpZ)`lj_fkbqebklqbpql`ob^qbqebXDofjqlqbj?^qqibmi^kZyyRy00-2-yyNFAy...11y

Q@lkcfojfkdqebPrpmf`flkyKy@^mq^fkA^ofii%13+3)/1+4&yyNFAy...11y
Q>ojplcqebDofjqlqbjpyKy@^mq^fkA^ofii%13+3)/1+4&yyNFAy...15y
>Q^_bqe^$p>ppfpq^k`byKy@^mq^fkA^ofii%13+3)/1+4&yyNFAy...16y

QQ^_bqe^$p>ppfpq^k`byKyQ^_bqe^%13)24+.&yyNFAy...16y
>O^wbAfobelokMlpqyKyQ^_bqe^%13)24+.&yyNFAy...2-y
@O^wbAfobelokMlpqyKy?rokqebKloqeQbkq%13)12&)B^pqQbkq%14)14&)^kaqebKloqeb^pqQbkq%14)13&^qAfobelokMlpqyyRy00-4/yyNFAy...2-y
QO^wbAfobelokMlpqyKyQ^_bqe^%13)24+.&yyNFAy...2-y
>Grpqf`bcloqebEv^ipyKyQ^_bqe^%13)24+.&yyNFAy...2.y

QJfppflkqlJrapmol`hbqyKyAo^wwfqAofms^isb%1/)40&yyNFAy../.1y

EQebo^jlobFpibyRy3615yyNFAy...2/y

QGrpqf`bcloqebEv^ipyKy@^mq^fkD^oo^kSfjbp%35+/)15+2&yyNFAy...2.y
>Mb^`b^qI^pqyKy@^mq^fkD^oo^kSfjbp%35+/)15+2&yyNFAy...2/y
@Mb^`b^qI^pqyKyI^vqebXTob^qeZ^qqebEv^iC^jfivJlkrjbkq)il`^qbafkqebdo^sbv^oagrpqlrqpfabQebo^jlob%30+4)1/+6&yyRy00-5/yyNFAy...2/y
QMb^`b^qI^pqyKy@^mq^fkD^oo^kSfjbp%35+/)15+2&yyNFAy...2/y

CO^q`ebqyKy?^iaor`%34+2)2.+0&y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
