DugisGuideViewer:RegisterGuide("Stranglethorn Vale (38-40)", "Badlands (40-41)", "Alliance", "L", function()
return [[
AAA

_?llqv?^vyNFAy3-2y
>Pfkdfkd?irbPe^oapyKy@o^khCfwwib_r_%/4+.)44+0&yyNFAy3-2y
>?illap`^imB^opyKyHb_lh%/4)44+/&yyNFAy.56y

>QebE^rkqbaFpibyKyHo^wbh%/4)44+/&yyNFAy3.3y
QQebE^rkqbaFpibyKy?^olkObsfid^w%/4+/)43+6&yyNFAy3.3y
>QebPqlkblcqebQfabpyKy?^olkObsfid^w%/4+/)43+6&yyNFAy245y

COb_bi@^jmyKyDvii%/4+2)44+4&yyNFAy241y
>Pmb`f^iClo`bpyKyPbodb^kqVlet^%05)0+1&yyNFAy241y
>Hrowbk$pJvpqbovyKy?olqeboKfjbqw%04+6)0+3&yyNFAy/-4y

@Pfkdfkd?irbPe^oapyKyQebXPfkdfkd@ovpq^iPe^oapZ`^k_billqbacolj^kvlcqeb?^pfifphp^olrkapqo^kdibqelok_rq^ob`ljjbkabapmlqfplkqeb`l^pq^q%/2).4&tfqeqeb@ovpq^iPmfkb?^pfifphpyyNFAy3-2y
@QebPqlkblcqebQfabpyKyQo^sbiqlqebFpi^ka^q%.6)//&fkqebSfibObbcyyNFAy245y

@Hrowbk$pJvpqbovyKyCfkaqeb1q^_ibqp^ka_ofkdqebfoibdbkap_^`hql?olqeboKfjbqw+Cfopqibdbkafplk^q^_ibqk^jbaJllkLsboqebS^ib^q%/6+2).6+.&+Pb`lkafpDofibhqebT^kabobo^q%/1+5)//+5&+QefoafpC^iilcDror_^pef^q%/0)./&+ClroqefpQebBjmbolo$pQlj_^q%/1+4)6&yyNFAy/-4y
@?illap`^imB^opyKyHfii^kvlcqeb?illap`^imjl_pqldbq.2X?illap`^imB^opZtef`e`^k_bclrkafkqeb?^i$i^iOrfkp^olrka%0/).2&yyNFAy.56y

@QfdboJ^pqbov%M^oq0&yKyHfiii-BiaboPqo^kdibqelokQfdboptef`e^obclrka^q%0/)/-&qlqebtbpqlcqeb`^jmyyNFAy.54y
@O^mqloJ^pqbov%M^oq/&yKyHfii.-I^peq^fiO^mqloptef`e`^k_bclrka^olrka%0.)/3&yyNFAy.62y
@Pljb>ppbj_ivObnrfobayKyHfiiqebPk^mg^t@ol`lifphptef`e`^k_bclrka^ilkdqebofsboil`^qba^q%06)/2&+Hfiibklrderkqfivlr$sb`liib`qba2XPk^mg^t@ol`lifphpPhfkpZyyNFAy244y
@Pmb`f^iClo`bpyKyHfii.-Hrowbk@ljj^kalbp^ka3HrowbkEb^apeofkhbopclrka^qqebfo`^jm%12)5&yyNFAy241y

QQfdboJ^pqbov%M^oq0&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.54y
>QfdboJ^pqbov%M^oq1&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.55y
QO^mqloJ^pqbov%M^oq/&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.62y
>O^mqloJ^pqbov%M^oq0&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.63y

QPmb`f^iClo`bpyKyIfbrqbk^kqAlobk%05)0+.&yyNFAy241y
>@lilkbiHrowbkyKyIfbrqbk^kqAlobk%05)0+.&yyNFAy/-/y
QHrowbk$pJvpqbovyKy?olqeboKfjbqw%04+6)0+3&yyNFAy/-4y
>QoliiTfq`ebovyKy?olqeboKfjbqw%04+6)0+3&yyNFAy/-2y

@@lilkbiHrowbkyKyHfii3HrowbkBifqbp%16)4&)1HrowbkPr_`efbcp%16)1&^kadbqXHrowbk$pEb^aZ%16)1&yyNFAy/-/y
@QfdboJ^pqbov%M^oq1&yKyHfiiPfk$A^iitel`^k_bclrkam^qoliifkd^olrka%0/).4&^kaillqfqpm^tyyNFAy.55y

QQfdboJ^pqbov%M^oq1&yKy>gb`hOlr^`h%02+3).-+3&yyNFAy.55y
>QebDobbkEfiiplcPqo^kdibqelokyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy005y
>@e^mqboFyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy006y
>@e^mqboFFyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy01-y
>@e^mqboFFFyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy01.y
>@e^mqboFSyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy01/y

Q@lilkbiHrowbkyKyIfbrqbk^kqAlobk%05)0+.&yyNFAy/-/y
C?llqv?^vyKyKfwwib%05+/)1&yyNFAy/-6y

Q?illap`^imB^opyKyHb_lh%/4)44+/&yyNFAy.56y
>PhriipmifqqboQrphpyKyHb_lh%/4)44+/&yyNFAy/-6y
QQebPqlkblcqebQfabpyKy?^olkObsfid^w%/4+/)43+6&yyNFAy245y
>T^qboBibjbkq^ipyKy?^olkObsfid^w%/4+/)43+6&yyNFAy3-.y
QPfkdfkd?irbPe^oapyKy@o^khCfwwib_r_%/4+.)44+0&yyNFAy3-2y
>Sbkqrob@ljm^kvJfkfkdyKy@o^khCfwwib_r_%/4+.)44+0&yyNFAy3--y

@@e^mqboFyKyDbqm^dbp.)1)3)^ka5lcKbpfkdt^ov$pQebDobbkEfiiplcPqo^kdibqelok+Qebm^dbp^obpmob^aqeolrdelrqPqo^kdibqelok)vlr`lriaqov%13+6)2+5&tebobPbodb^kqJ^iqerpaolmpqebm^dbplo%12)5&tebob?llhfbEbolaaolmpqebm^dbp+?rv^kvm^dbpvlr`^k$qcfka^qqeb>E)qebv^ob_bqtbbk.-*/2pfisbob^`eyyNFAy006y
@@e^mqboFFyKyDbqm^dbp.-)..).1^ka.3lcKbpfkdt^ov$pQebDobbkEfiiplcPqo^kdibqelok+Qebm^dbp^obpmob^aqeolrdelrqPqo^kdibqelok)vlr`lriaqov%13+6)2+5&tebobPbodb^kqJ^iqerpaolmpqebm^dbplo%12)5&tebob?llhfbEbolaaolmpqebm^dbp+?rv^kvm^dbpvlr`^k$qcfka^qqeb>E)qebv^ob_bqtbbk.-*/2pfisbob^`eyyNFAy01-y
@@e^mqboFFFyKyDbqm^dbp.5)/-)/.^ka/1lcKbpfkdt^ov$pQebDobbkEfiiplcPqo^kdibqelok+Qebm^dbp^obpmob^aqeolrdelrqPqo^kdibqelok)vlr`lriaqov%13+6)2+5&tebobPbodb^kqJ^iqerpaolmpqebm^dbplo%12)5&tebob?llhfbEbolaaolmpqebm^dbp+?rv^kvm^dbpvlr`^k$qcfka^qqeb>E)qebv^ob_bqtbbk.-*/2pfisbob^`eyyNFAy01.y
@@e^mqboFSyKyDbqm^dbp/2)/3)^ka/4lcKbpfkdt^ov$pQebDobbkEfiiplcPqo^kdibqelok+Qebm^dbp^obpmob^aqeolrdelrqPqo^kdibqelok)vlr`lriaqov%13+6)2+5&tebobPbodb^kqJ^iqerpaolmpqebm^dbplo%12)5&tebob?llhfbEbolaaolmpqebm^dbp+?rv^kvm^dbpvlr`^k$qcfka^qqeb>E)qebv^ob_bqtbbk.-*/2pfisbob^`eyyNFAy01/y

QPljb>ppbj_ivObnrfobayKyAofwwifh%/5+0)44+2&yyNFAy244y
>Bu`bipfloyKyAofwwifh%/5+0)44+2&yyNFAy3/5y

@Sbkqrob@ljm^kvJfkfkdyKyHfii^kvlcqebSbkqrob@l+jl_p^qqebfo`^jm^q%1-)10&rkqfivlr$sb`liib`qba.-XPfkdfkd?irb@ovpq^ipZyyNFAy3--y
@PhriipmifqqboQrphpyKyHfii^kvlcqebPhriipmifqqbojl_pclrka^olrka%12)05&^qqebOrfkplcWri$J^jtbrkqfivlr$sb`liib`qba.5XPhriipmifqqboQrphpZyyNFAy/-6y
@QoliiTfq`ebovyKyDbq1XPhriipmifqqboCbqfpebpZaolmmba_vPhriipmifqqboJvpqf`^olrka%10)03&yyNFAy/-2y
@O^mqloJ^pqbov%M^oq0&yKyHfii.-GrkdibPq^ihbopclrka^olrka%00)06&yyNFAy.63y
@M^kqeboJ^pqbov%M^oq0&yKyHfii.-Pe^altj^tM^kqeboptef`e^obpqb^iqebajl_pclrka^olrka%05)04&^ka%14)/1&yyNFAy.6/y
@Bu`bipfloyKyHfii^kBiaboP^iqt^qbo@ol`lifphtef`efp^plil^_ib05Bifqb+Qebb^pfbpqt^vqlcfkalkbfpqlork^ilkdqebTbpq`l^pqpq^oqfkd%00)0/&rmql%/.).2&yyNFAy3/5y
@T^qboBibjbkq^ipyKyQo^sbiqlqebFpi^ka^q%.6)//&fkqebSfibObbc^kahfiiqebIbppboT^qboBibjbkq^iprkqfivlr$sb`liib`qba3XT^qboBibjbkq^i?o^`bopZyyNFAy3-.y

QM^kqeboJ^pqbov%M^oq0&yKyPfoP+G+Boid^afk%02+3).-+3&yyNFAy.6/y
QO^mqloJ^pqbov%M^oq0&yKyEbjbqKbpfkdt^ovGo+%02+4).-+5&yyNFAy.63y
Q@e^mqboFyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy006y
Q@e^mqboFFyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy01-y
Q@e^mqboFFFyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy01.y
Q@e^mqboFSyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy01/y
QQebDobbkEfiiplcPqo^kdibqelokyKy?^okfiPqlkbmlq%02+4).-+2&yyNFAy005y

QQoliiTfq`ebovyKy?olqeboKfjbqw%04+6)0+3&yyNFAy/-2y
C?llqv?^vyKyKfwwib%05+/)1&y

QT^qboBibjbkq^ipyKy?^olkObsfid^w%/4+/)43+6&yyNFAy3-.y
QSbkqrob@ljm^kvJfkfkdyKy@o^khCfwwib_r_%/4+.)44+0&yyNFAy3--y
QPhriipmifqqboQrphpyKyHb_lh%/4)44+/&yyNFAy/-6y
QBu`bipfloyKyAofwwifh%/5+0)44+2&yyNFAy3/5y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
