DugisGuideViewer:RegisterGuide("Badlands (40-41)", "Stranglethorn Vale (41-42)", "Alliance", "L", function()
return [[
AAA

C@fqvlcFolkclodbyNFAy4-4y
??rvXColpqLfiZyKyColj>r`qflkElrpb%/1)4-&*Phfmqefpfcklq^s^fi^_ibyyIy05/6yyNFAy4-4yyWyFolkclodby
??rvXDvol`eolk^qljZyKyColj>r`qflkElrpb%/1)4-&*Alk$q_rvfcvlrafak$qcfka^ColpqLfiyyIy1056yyNFAy4-4yyWyFolkclodby
??rvXEb^ifkdMlqflkZyKyColj>r`qflkElrpb%/1)4-&*Alk$q_rvfcvlrafak$qcfka^ColpqLfi^kaDvol`eolk^qljyyIy6/6yyNFAy4-4yyWyFolkclodby
??rvXIbppboFksfpf_fifqvMlqflkZyKyColj>r`qflkElrpb%/1)4-&*Alk$q_rvfcvlrafak$qcfka^ColpqLfi^kaDvol`eolk^qljyyIy05/0yyNFAy4-4yyWyFolkclodby
??rv1uX?rww^oaTfkdZyKyColj>r`qflkElrpb%/1)4-&*Phfmqefpfcklq^s^fi^_ibyyIy01-11yyWyFolkclodby
>Folk_^kaT^kqpVlryKyMolpmb`qloPqlojmfhb%41+2)./&yyWyFolkclodbyyNFAy4-4y

CIl`eJla^kyKyDovqeQeroabk%22+4)15&yyWyFolkclodbyyNFAy/2--y
>?^ai^kapOb^dbkqOrkyKyDe^hEb^iqlr`e%04)16+/&yyWyIl`eJla^kyyNFAy/2--y
QFolk_^kaT^kqpVlryKyMolpmb`qloFolk_^ka%32+5)32+3&yyWyIl`eJla^kyyNFAy4-4y
>Cfka>djlkayKyMolpmb`qloFolk_^ka%32+5)32+3&yyWyIl`eJla^kyyNFAy405y

O?^ai^kapyKyPlrqetbpqlcFolk_^ka$p%13)43&yyWyIl`eJla^kyyNFAy4-3y
>Cfbov?i^wbBk`e^kqjbkqpyKyPfdorkFolkebt%20+4)10+0&yyNFAy4-3y
>Jfo^dbpyKyPfdorkFolkebt%20+4)10+0&yyNFAy4.5y
>>At^oc^kaEfpQllipyKyMolpmb`qloOvbali%20+1)10+0&yyNFAy4.6y
>?^o_b`rba?rww^oaTfkdpyKyOfddibcrww%1/+1)2/+5&yyNFAy4-0y

KHfii^kv_rww^oapvlrpbbyKyClo?^o_b`rba?rww^oaTfkdp^ka?^ai^kapOb^dbkqOrkyyNFAy4-0y

@Jfo^dbpyKyCfkaqebXPrmmiv@o^qbZ^q%33)//&^qqebBu`^s^qflkPfqbyyNFAy4.5y
>>PfdklcElmb%M^oq.&yKy@orjmibaJ^m%20)01+.&yyNFAy4/-y
@>At^oc^kaEfpQllipyKyXOvbali$pIr`hvMf`hZ`^k_bclrkacoljqebPe^altclodbjl_pil`^qbaqlqebB^pqlc>kdloCloqobpp^olrka%2.)0.&yyNFAy4.6y

QJfo^dbpyKyPfdorkFolkebt%20+4)10+0&yyNFAy4.5y
>P`olrkdfkdyKyPfdorkFolkebt%20+4)10+0&yyNFAy400y
Q>At^oc^kaEfpQllipyKyMolpmb`qloOvbali%20+1)10+0&yyNFAy4.6y
Q>PfdklcElmb%M^oq.&yKyMolpmb`qloOvbali%20+1)10+0&yyNFAy4/-y

>QobjloplcqebB^oqe%M^oq.&yKyD^obh%3.)21&yyNFAy40/y
KHbbm^kbvblrqcloqebldobm^`hyKyQebvpm^tkqlqebplrqelcqebnrbpqdfsbo%3/)4-&+Qebvm^qolialtkqlqebplrqetbpqpfablcqebwlkb^ka_^`hfk^`fo`ib+Vlrpelria_b^_ibqlmf`h?lppQel$dorklccqeb_^`hlcqebm^`hb^pfivyyNFAy40/y

QCfka>djlkayKy?^qqbobaAt^osbkPhbibqlk%2.)3/+2&yyNFAy405y
>Jroa^il`yKy?^qqbobaAt^osbkPhbibqlk%2.)3/+2&yyNFAy406y
@Jroa^il`yKyJroa^il`fp^m^qoliifkdjl_clrka^ilkdtfqeqeblqebokbbabaPqlkbs^riq?lkbpk^mmbop^q>djlka$pBka^olrka%2-)4-&yyNFAy406y

@?^o_b`rba?rww^oaTfkdpyKyX?rww^oaTfkdpZ^obrpr^iivifpqbalkqeb>r`qflkelrpb^q^obibqfsbiviltmof`btef`etlriaj^hbqefpnrbpq^kb^pv`ljmibqflkfcklqhfiiDf^kq?rww^oap^olrka%.3+2)3-&tele^sb^ab`bkqaolmo^qbyyNFAy4-0y

Q?^o_b`rba?rww^oaTfkdpyKyOfddibcrww%1/+1)2/+5&yyNFAy4-0y

>PqravlcqebBibjbkqp7Ol`h%M^oq.&yKyIlqtfiSbof^qrp%/2+6)12+-&yyNFAy4.-y
>@lli^kqEb^apMobs^fiyKyIlqtfiSbof^qrp%/2+6)12+-&yyIy05/6yyLyyNFAy4.0y
Q@lli^kqEb^apMobs^fiyKyIlqtfiSbof^qrp%/2+6)12+-&yyLyyNFAy4.0y
>Dvol+++Te^q<yKyIlqtfiSbof^qrp%/2+6)12+-&yyIy1056yyLyyNFAy4.1y
QDvol+++Te^q<yKyIlqtfiSbof^qrp%/2+6)12+-&yyLyyNFAy4.1y
>IfnrfaPqlkbyKyIr`fbkQlppbitobk`e%/2+5)11+1&yyIy05/0yyLyyNFAy4.2y
QIfnrfaPqlkbyKyIr`fbkQlppbitobk`e%/2+5)11+1&yyLyyNFAy4.2y

@PqravlcqebBibjbkqp7Ol`h%M^oq.&yKyHfiiqebIbppboOl`hBibjbkq^ip^olrka%/0)2.&rkqfivlr$sb`liib`qba.-XPj^iiPqlkbPe^oapZyyNFAy4.-y
QPqravlcqebBibjbkqp7Ol`h%M^oq.&yKyIlqtfiSbof^qrp%/2+6)12+-&yyNFAy4.-y
>PqravlcqebBibjbkqp7Ol`h%M^oq/&yKyIlqtfiSbof^qrp%/2+6)12+-&yyNFAy4..y
@PqravlcqebBibjbkqp7Ol`h%M^oq/&yKyXI^odbPqlkbPi^_pZaolmcoljqebOl`hBibjbkq^ipclrkabfqebocroqeboTbpqcoljtebobvlrhfiibaqebIbppboOl`hBibjbkq^ip^olrka%.1)05&loqlqebPlrqelc?^ai^kap^olrka%06)44&yyNFAy4..y
QPqravlcqebBibjbkqp7Ol`h%M^oq/&yKyIlqtfiSbof^qrp%/2+6)12+-&yyNFAy4..y
>PqravlcqebBibjbkqp7Ol`h%M^oq0&yKyIlqtfiSbof^qrp%/2+6)12+-&yyNFAy4./y

@?^ai^kapOb^dbkqOrkyKyQebjl_p^obpmob^aqeolrdelrq_^ai^kap_rq^dlla^ob^qlalqefpnrbpqtlria_b^olrka%/0)2.&tebob^iiqeobbkbbaba?rww^oap)@lvlqbp^kaOl`hBibjbkq^ip`^k_bclrka+Hfiibklrdeqfiivlrd^fkqebobnrfoba^jlrkqlcb^`eob^dbkqyyNFAy/2--y
@P`olrkdfkdyKyQebXP`o^mJbq^iZ`^k_bclrkacoljqebArpq_bi`ebojl_pproorlkafkdArpq_bi`eDolqql^olrka%./)45&yyNFAy400y
@PqravlcqebBibjbkqp7Ol`h%M^oq0&yKyHfiiqebDob^qboOl`hBibjbkq^ipfkqebPlrqetbpq`lokbo^qArpq_bi`eDolqql^olrka%2)5-&qfiivlr$sb`liib`qba2X?o^`boplcOl`h?fkafkdZyyNFAy4./y

QPqravlcqebBibjbkqp7Ol`h%M^oq0&yKyIlqtfiSbof^qrp%/2+6)12+-&yyNFAy4./y
>QefpFpDlfkdql?bE^oa%M^oq.&yKyIlqtfiSbof^qrp%/2+6)12+-&yyLyyNFAy401y
QQefpFpDlfkdql?bE^oa%M^oq.&yKyIr`fbkQlppbitobk`e%/2+5)11+1&yyLyyNFAy401y
>QefpFpDlfkdql?bE^oa%M^oq/&yKyIr`fbkQlppbitobk`e%/2+5)11+1&yyLyyNFAy444y
QQefpFpDlfkdql?bE^oa%M^oq/&yKyIlqtfiSbof^qrp%/2+6)12+-&yyLyyNFAy444y
>QefpFpDlfkdql?bE^oa%M^oq0&yKyIlqtfiSbof^qrp%/2+6)12+-&yyLyyNFAy445y
@QefpFpDlfkdql?bE^oa%M^oq0&yLyyKyCfka^kahfiiqebC^j$obqloDr^oaf^k`ilpb_vqlqebTbpqm^qoliifkd^olrka%/3)13&^ka`liib`qXIlqtfi$pPe^`hibplcBibjbkq^i?fkafkdZyyNFAy445y
QQefpFpDlfkdql?bE^oa%M^oq0&yKyIlqtfiSbof^qrp%/2+6)12+-&yyLyyNFAy445y

QP`olrkdfkdyKyPfdorkFolkebt%20+4)10+0&yyNFAy400y
QQobjloplcqebB^oqe%M^oq.&yKyD^obh%3.)21&yyNFAy40/y
@Cfbov?i^wbBk`e^kqjbkqpyKyQefpnrbpqfpj^ohba^pDolrmarbqlqebbifqbao^dlkptef`eproolrkaqeb^ob^_rqqebvalklqe^sbql_bhfiibafkloaboqldbqX?i^`hAo^hb$pEb^oqZ+Qebfqbjfqpbic`^k_b^`nrfobacoljqebP`^iafkdTebimp^olrkaqebS^iibv^q%41)3/&+Qebaolmo^qbfpilt_rqfqfp^dllaqfjbqldofka+Fcfqq^hbpqllilkd)phfmqebnrbpqyyNFAy4-3y
QCfbov?i^wbBk`e^kqjbkqpyKyPfdorkFolkebt%20+4)10+0&yyNFAy4-3y

QJroa^il`yKyMolpmb`qloFolk_^ka%32+5)32+3&yyWyIl`eJla^kyyNFAy406y
Q?^ai^kapOb^dbkqOrkyKyDe^hEb^iqlr`e%04)16+/&yyWyIl`eJla^kyyNFAy/2--y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)

