DugisGuideViewer:RegisterGuide("Stranglethorn Vale (41-42)", "Tanaris (43)", "Alliance", "L", function()
return [[
AAA

C?llqv?^vyKyDloofh%1+-)11+6&yyWy?^ai^kapyyNFAy/531y
>Qo^k$obhyKyColjHo^wbhfkqebFkk%/kaCillo&%/4)44+/&yyNFAy/531y
>W^kwfi$pPb`obqyKyColj@o^khCfwwib_r_fkqebFkk%/4+.)44+0&yyNFAy3/.y
e?llqv_^vyKyFkkhbbmboPhfkaib%/4+.)44+0&yyNFAy3.4y
>>hfofp_vqeb?rkaib%M^oq.&yKyColjMofs^qbbo?il^apkbuqqlqeb?^kh%/3+4)43+1&yyNFAy3.4y
>Pqo^kdibqelokCbsboyKyCfkCfwo^`hbq%/4+4)43+4&yyNFAy015y
>P`^ofkdPe^hvyKyPb^TlicJ^`Hfkibv%/4+5)44+.&yyNFAy3-3y
>Qeb?illap^fi?r``^kbbop%M^oq.&yKyColjCfopqJ^qb@o^ww%/5+.)43+/&grpqm^pqqebLiaMloq>rqelofqv_rfiafkd%Cfopq_fd_rfiafkdtebkdbqqfkdlccqeb?l^q&yyNFAy262y

QQeb?illap^fi?r``^kbbop%M^oq.&yKy?illap^fi@loobpmlkabk`b)lkqlmlclkblcqeb_^oobip%/4+0)36+2&yyNFAy262y
>Qeb?illap^fi?r``^kbbop%M^oq/&yKy?illap^fi@loobpmlkabk`b%/4+0)36+2&yyNFAy264y
@>hfofp_vqeb?rkaib%M^oq.&yKyDbq.-?rkaibplcX>hfofpObbaZ^olrka%/1)32&yyNFAy3.4y

@P`^ofkdPe^hvyKyHfiiBiaboJfpqs^ibDlofii^%00+3/)31+0.&clo.-uXJfpqs^ibDf_ibqpZyyNFAy3-3y
@Pqo^kdibqelokCbsboyKyHfiidlofii^pclo^c^kd)q^hbfqqlqebqoliifkqeb`^sbqlqebkloqe%02)3-&+Abcbkaefj)qebi^pqdloofi^tfiiaolmqebXEb^oqlcJlhhZyyNFAy015y

QP`^ofkdPe^hvyKyPe^hvMefiifmb%/3+6)40+3&yyNFAy3-3y
>ObqrokqlJ^`HfkibvyKyPe^hvMefiifmb%/3+6)40+3&yyNFAy3-4y
QQeb?illap^fi?r``^kbbop%M^oq/&yKyCfopqJ^qb@o^ww%/5+.)43+/&yyNFAy264y
>Qeb?illap^fi?r``^kbbop%M^oq0&yKyCfopqJ^qb@o^ww%/5+.)43+/&yyNFAy266y
QPqo^kdibqelokCbsboyKyCfkCfwo^`hbq%/4+4)43+4&yyNFAy015y
Q>hfofp_vqeb?rkaib%M^oq.&yKyMofs^qbbo?il^ap%/3+4)43+1&yyNFAy3.4y
>>hfofp_vqeb?rkaib%M^oq/&yKyMofs^qbbo?il^ap%/3+4)43+1&yyNFAy3/0y
>RmqlPkrccyKyColjAbbd%/3+62)44+0/&lkqeb/kacillolcqebFkkyyNFAy254y
QQeb?illap^fi?r``^kbbop%M^oq0&yKy>qCibbqJ^pqboPb^elok%/4+.)44&lkqeb/kaCillolcqebFkkyyNFAy266y
>Qeb?illap^fi?r``^kbbop%M^oq1&yKy>qCibbqJ^pqboPb^elok%/4+.)44&yyNFAy3-1y
QObqrokqlJ^`HfkibvyKyPb^TlicJ^`Hfkibv%/4+5)44+.&yyNFAy3-4y
>SllallArbpyKyPb^TlicJ^`Hfkibv%/4+5)44+.&yyNFAy3-6y
>Hbbm>kBvbLrqyKyAfwwvLkb*Bvb%/5+3)42+5&yyNFAy243y

KCfka^P`oliitefibvlr$obfkqeb_l^qpyKyCfka^p`oliiqlpq^oqqebnrbpq@loqbiil$pOfaaib)fq`^k^mmb^ofk^kvlclcqeb0?illap^fip_l^qpyyNFAy3/1y
@Qeb?illap^fi?r``^kbbop%M^oq1&yKyColjqeb?llqv?^vbufqeb^ab^pqqlqeb`l^pq)qebkplrqe+Fqbjp`^k_bclrka^qqebqtl`^jmp%0-)5.&)%/4)50&^kafk^olt_l^q%/5)50&yyNFAy3-1y
@Hbbm>kBvbLrqyKyHfii?illap^fiplo?orqrp%00)55+/&qldbqXAfwwv$pBvbZyyNFAy243y
@RmqlPkrccyKyHfii?illap^fip%0-)55&clo.2XPkrccZyyNFAy254y
>@loqbiil$pOfaaibyKyQebfqbjX@loqbiil$pOfaaibZpq^oqpqebnrbpq)qefpp`olii`^k^mmb^ofk^kvlclcqeb0?illap^fip_l^qpyyNFAy3/1yyRy1-23y

@SllallArbpyKyOrkkloqeqlOrfkplcGr_rt^i%01+65)2/+.2&)hfiiGlk*Glkqeb@olt^kaJ^rov@ir_CllqTfihfkp+Orkplrqe^q^a%02+/0)2.+.6&^kaqebkb^pqqlOrfkplc>_lo^w%1-)24&)hfii@er`hvQbkQerj_pyyNFAy3-6y
@W^kwfi$pPb`obqyKyHfiiqebqoliip%1.)25&clo./p^jmibplcXW^kwfi$pJfuqrobZ)_rq^slfaW^kwfiyyNFAy3/.y

E?llqv?^vyRy3615yyNFAy25-y
QW^kwfi$pPb`obqyKy@o^khCfwwib_r_%/4+.)44+/&yyNFAy3/.y
>TefphbvPifj$pIlpqDoldyKyTefphbvPifj%/4+.)44+1&yyNFAy25-y
QRmqlPkrccyKyColjAbbd%/3+62)44+0/&lkqeb/kacillolcqebFkkyyNFAy254y
QQeb?illap^fi?r``^kbbop%M^oq1&yKy>qCibbqJ^pqboPb^elok%/4+.)44&lkqeb/kaCillolcqebFkkyyNFAy3-1y
QSllallArbpyKyPb^TlicJ^`Hfkibv%/4+5)44+.&*Phfmqebcliilt*rmyyNFAy3-6y
>Pqlibv$pAb_qyKyPb^TlicJ^`Hfkibv%/4+5)44+.&yyNFAy/54/y
QHbbm>kBvbLrqyKyAfwwvLkb*Bvb%/5+3)42+5&yyNFAy243y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
