DugisGuideViewer:RegisterGuide("Feralas (43-45)", "The Hinterlands (46-47)", "Alliance", "L", function()
return [[
AAA

CAbpli^`byKy?bo^Pqlkbe^jjbo%2.)/6+0&yyWyQ^k^ofpyyNFAy/5/.y
OCbo^i^pyKyOrkplrqetbpqfkqlCbo^i^p%11)66&+Cliiltqebol^aqlqebm^qealtkqlqebal`hpyyWyAbpli^`byyNFAy/5/.y
OCb^qebojllkPqolkdeliayKyQ^hbqeb_l^qfcfq$pqebob)lobipbptfjtbpq%0/)14&yyNFAy/5/.y

>QebJ^ohlcNr^ifqvyKyMo^qqJ`Dor__bk%0-+3)1/+4&yyNFAy/5/.y
eCb^qebojllkPqolkdeliayKyFkkhbbmboPevof^%0.)10+2&yyNFAy/533y
>QebOrfkplcPli^op^iyKyPe^kaofpCb^qebojllk%0-+0)13+.&yyNFAy/533y
>QebJfppfkd@lrofbo%M^oq.&yKyI^qolkf`rpJllkpmb^o%0-+1)13+.&yyNFAy1./1y
>QebEfdeTfiabokbppyKy>kdbi^pJllk_obbwb%0.+6)12+3&yyNFAy/65/y
>FkPb^o`elcHkltibadbyKyQolv^pJllk_obbwb%0.+5)12+2&yyNFAy/606y
QQebJfppfkd@lrofbo%M^oq.&yKyDfkolEb^oqehfkaib%0.+6)12+/&yyNFAy1./1y
>QebJfppfkd@lrofbo%M^oq/&yKyDfkolEb^oqehfkaib%0.+6)12+/&yyNFAy1./2y

QQebOrfkplcPli^op^iyKyPli^op^iD^wb_l%/3+0)2/+0&yyNFAy/533y
>ObqrokqlCb^qebojllkPqolkdeliayKyPli^op^iD^wb_l%/3+0)2/+0&yyNFAy/534y
QObqrokqlCb^qebojllkPqolkdeliayKyPe^kaofpCb^qebojllk%0-+0)13+.&yyNFAy/534y
>>d^fkpqqebE^qb`obpq%M^oq.&yKyPe^kaofpCb^qebojllk%0-+0)13+.&yyNFAy0.0-y
Q>d^fkpqqebE^qb`obpq%M^oq.&yKyI^qolkf`rpJllkpmb^o%0-+1)13+.&yyNFAy0.0-y
>>d^fkpqqebE^qb`obpq%M^oq/&yKyI^qolkf`rpJllkpmb^o%0-+1)13+.&yyNFAy/536y
@>d^fkpqqebE^qb`obpq%M^oq/&yKyHfiik^d^_^`h^qqeborfkp%/3)31&clo.-XE^qb`obpqK^d^P`^ibZyyNFAy/536y
Q>d^fkpqqebE^qb`obpq%M^oq/&yKyI^qolkf`rpJllkpmb^o%0-+1)13+.&yyNFAy/536y
>>d^fkpqIloaPe^iw^oryKyI^qolkf`rpJllkpmb^o%0-+1)13+.&yyNFAy/54-y
@>d^fkpqIloaPe^iw^oryKyPlrqeqeorqeborfkp)^`olppqebt^qbo)fk^`^sb%/3)34&+Ebfpibsbi14)plebjfdeq_be^oaqlplilyyNFAy/54-y

OCb^qebojllkPqolkdeliayKy%0/)14&Loafb^kaobwqebobyyNFAy/54.y
Q>d^fkpqIloaPe^iw^oryKyI^qolkf`rpJllkpmb^o%0-+1)13+.&yyNFAy/54-y
>AbifsbofkdqebObif`yKyI^qolkf`rpJllkpmb^o%0-+1)13+.&yyNFAy/54.y
QAbifsbofkdqebObif`yKySbpqf^Jllkpmb^o%0-+.)12+.&yyNFAy/54.y

@P`obb`eboPmfofqpyKy?^`hlkqebj^fkpelob%13)06&^slfabibjbkq^ip^kadf^kqptefibhfiifkdOldrbS^ibP`obb`ebop+RpbXVbe$Hfkv^$p?o^j_ibZlkqebfo`lompbp^kaq^ihqlqebpmfofqp+Tlohvlrot^vplrqeyyRy.-366yyNFAy02/-y
QQebJfppfkd@lrofbo%M^oq/&yKyTob`hbaOlt?l^q%12+20)31+65&yyNFAy1./2y
>?l^qTob`h^dbyKyTob`hbaOlt?l^q%12+20)31+65&yyNFAy1./4y

Q?l^qTob`h^dbyKyDfkolEb^oqehfkaib%0.+6)12+/&yyNFAy1./4y
>QebHkfcbObsb^ibayKyDfkolEb^oqehfkaib%0.+6)12+/&yyNFAy1./6y
QQebHkfcbObsb^ibayKyNrfkqfpGlkbpmvob%0/+2)10+5&yyNFAy1./6y
>Mpv`eljbqof`Ob^afkdyKyNrfkqfpGlkbpmvob%0/+2)10+5&yyNFAy1.0-y
QMpv`eljbqof`Ob^afkdyKyDfkolEb^oqehfkaib%0.+6)12+/&yyNFAy1.0-y
>QebTllam^tDkliipyKyDfkolEb^oqehfkaib%0.+6)12+/&yyNFAy1.0.y

>CfkaLLU*//,CByKyRpbXLLU*//,CBAfpqobpp?b^`lkZyyLyyRy54-2yyNFAy/433y
@QebJ^ohlcNr^ifqvyKyHfiiVbqfcoljqeb`^sb%23)23&^ka`liib`q.-uXQef`hVbqfEfabZyyNFAy/5/.y
QCfkaLLU*//,CByLyyKy>qqeb_^`hlcqebvbqf`^sb%2/)24&+Alk$q^``bmqqebbp`loqyyNFAy/433y
@QebEfdeTfiabokbppyKyPe^j^kp^obqlqebplrqe^qqebqbjmib%26)40&+?orqbp^qOrfkplcFpfiafbk%3/)21&+T^oil`hp^ob^olrka%3.)23&yyNFAy/65/y
>Cobbaljclo>ii@ob^qrobpyKy@ib^o^olrkaqeb`^dbfkqeb`^jm)qebkq^ihqlHfka^iJllktb^sbo%32+6)12+4&yyNFAy/636y
@Cobbaljclo>ii@ob^qrobpyKyIb^aHfka^iJllktb^sboaltkqlqeb`^db)lmbkfq)^kamolqb`qqebPmofqbA^oqbop^pqebvbp`^mbyyNFAy/636y
QCobbaljclo>ii@ob^qrobpyKyHfka^iJllktb^sbo%32+6)12+4&yyNFAy/636y
>AlifkdGrpqf`b%M^oq.&yKyGbo$h^fJllktb^sbo%32+6)12+3&yyNFAy/64-y
@AlifkdGrpqf`b%M^oq.&yKyHfii^iiqebDofjqlqbjp^olrka%34)13&yyNFAy/64-y
QAlifkdGrpqf`b%M^oq.&yKyGbo$h^fJllktb^sbo%32+6)12+3&yyNFAy/64-y
>AlifkdGrpqf`b%M^oq/&yKyGbo$h^fJllktb^sbo%32+6)12+3&yyNFAy/64/y

QQebTllam^tDkliipyKyI^odbIb^qebo?^`hm^`hp%40+0)23+0&+Illhclo^_^`hm^`he^kdfkdlk^qobbfklkblcqebdklii`^jmpyyNFAy1.0.y
>QebTofqefkdAbbmyKyI^odbIb^qebo?^`hm^`hp%40+0)23+0&yyNFAy1.02y
>Qe^i^k^^oAbifsbovyKyRpbXRkabifsbobaM^o`biZqe^qvlrgrpqmf`hbarmyyRy..130yyNFAy1/5.y
QQebTofqefkdAbbmyKyWrhh$^peMlafkqebefsbqlqebplrqe%4/+.)30+5&+>qqeb_lqqlj)q^hbqebplrqebokqrkkbi^kapq^vofdeqyyNFAy1.02y
>CobbacoljqebEfsbyKyWrhh$^peMla%4/+.)30+5&yyNFAy1/32y
QQe^i^k^^oAbifsbovyKyC^icfkabiT^vt^oabo%56+3)13+2&yyNFAy1/5.y

CCb^qebojllkPqolkdeliayKyQevppf^k^%56+2)12+6&yyNFAy4400y
QQebJ^ohlcNr^ifqvyKyMo^qqJ`Dor__bk%0-+3)1/+4&yyNFAy/5/.y
>FjmolsbaNr^ifqvyKyMo^qqJ`Dor__bk%0-+3)1/+4&yyNFAy4400y
QQebEfdeTfiabokbppyKy>kdbi^pJllk_obbwb%0.+6)12+3&yyNFAy/65/y
QCobbacoljqebEfsbyKyDfkolEb^oqehfkaib%0.+6)12+/&yyNFAy1/32y
>>Ebol$pTbi`ljbyKyDfkolEb^oqehfkaib%0.+6)12+/&yyNFAy1/33y
Q>Ebol$pTbi`ljbyKyPe^kaofpCb^qebojllk%0-+0)13+.&yyNFAy1/33y
>OfpblcqebPfifqefayKyPe^kaofpCb^qebojllk%0-+0)13+.&yyNFAy1/34y

COrq$qebo^kSfii^dbyKyCviaobkJllkcb^qebo%0-+0)10+0&yyNFAy033.y
QE^kaibTfqe@^obyKyBobi^p>j_bophv%22+2)6/+.&yyWyQbiao^ppfiyyNFAy0-//y
>C^slobalcBirkb<yKyBobi^p>j_bophv%22+2)6/+.&yyWyQbiao^ppfiyyNFAy033.y
QFkPb^o`elcHkltibadbyKyA^ovkIfdeqtfka%22+1)6/+/&yyWyQbiao^ppfiyyNFAy/606y
>Cbo^i^p7>EfpqlovyKyCbo^i^p7>Efpqlov%22+0)6.+2&yyWyQbiao^ppfiyyNFAy/61-y
QCbo^i^p7>EfpqlovyKyA^ovkIfdeqtfka%22+1)6/+/&yyWyQbiao^ppfiyyNFAy/61-y
>Qeb?looltboyKyA^ovkIfdeqtfka%22+1)6/+/&yyWyQbiao^ppfiyyNFAy/61.y

OA^ok^pprpyKyOrkqeolrdeqlqebmloq^iqlA^ok^pprp%22+6)56+3&yyWyQbiao^ppfiyyNFAy/611y

QOfpblcqebPfifqefayKyDo^`fk^Pmfofqjfdeq%1/)53&yyWyA^ok^pprpyyNFAy1/34y
QAlifkdGrpqf`b%M^oq/&yKyQvo^kabTefpmbotfka%06)5.&yyWyA^ok^pprpyyNFAy/64/y

ECb^qebojllkPqolkdeliayRy3615yyNFAy/611y
CD^adbqw^kyKyCviaobkJllkcb^qebo%0-+0)10+0&yyNFAy/611y
QQeb?looltboyKy@rodib@o^khibelm%2/+0)/3+6&yyWyQ^k^ofpyyNFAy/61.y
>QebPrmboPk^mmboCUyKy@rodib@o^khibelm%2/+0)/3+6&yyWyQ^k^ofpyyNFAy/611y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
