DugisGuideViewer:RegisterGuide("Tanaris (43)", "Feralas (43-45)", "Alliance", "L", function()
return [[
AAA

_O^q`ebqyKyQ^hbqeb_l^qqlO^q`ebqyyNFAy.36-y
OQelrp^kaKbbaibpyKyOrkPlrqeqlQelrp^kapKbbaibp%11)60+2&yyWyQeb?^oobkpyyNFAy.36-y
OQ^k^ofpyKyOrkqlQ^k^ofp%42+/)65&yyWyQelrp^kaKbbaibpyyNFAy.36-y
OD^adbqw^kyKyDlqlD^adbqw^k%2-+3)/5&yyNFAy.36-y

>T^pqbt^kaboGrpqf`byKy@efbcBkdfkbbo?fidbtefwwib%2/+1)/5+2&yyNFAy.36-y
>T^qboMlr`e?lrkqvyKyPmfdlqLmbo^qloIrdirkhbq%2/+1)/5+1&yyNFAy.4-4y
eD^adbqw^kyKyFkkhbbmboCfwwdofj_ib%2/+2)/4+6&yyNFAy/542y
>T>KQBA7>kaobCfob_b^oayKyT^kqbaMlpqbo%2.+6)/4&yyNFAy/542y
>T>KQBA7@^ifmeP`lomfapqfkdyKyT^kqbaMlpqbo%2.+6)/4&yyNFAy/45.y
QQo^k$obhyKyQo^k$obh%2.+3)/3+5&yyNFAy/531y
>D^adbqw^kT^qboProsbvyKyPbkfloProsbvloCfwwibaltpbo%2-+/)/4+2&yyNFAy66/y

OPqb^jtebbaibMloqyKy%33+2)//+2&yyNFAy/45.y
QPqlibv$pAb_qyKyPqlibv%34+.)/0+6&yyNFAy/54/y
>Pqlibv$pPefmjbkqyKyPqlibv%34+.)/0+6&yyNFAy/540y
>Plrqepb^Pe^hbaltkyKyPb`rofqv@efbc?fidbtefwwib%34)/0+6&yyNFAy5033y
>Mfo^qbE^qp>elvyKyE^rdeqvJlafpqb%33+2)//+0&yyNFAy5032y
>P`obb`eboPmfofqpyKyVbe$hfkv^%33+6)//+1&yyNFAy02/-y

@T^pqbt^kaboGrpqf`byKyQebkbbabajl_p^obclrkagrpqTbpqlrqpfabPqbbjtbbaibMloq^olrka%30+30)0.+30&+Hfii.-T^pqbt^kabo?^kafqp^kaQefbsbpyyNFAy.36-y
@T^qboMlr`e?lrkqvyKyHfiiqebjl_p^olrkaT^qbopmofkdCfbia^olrka%3.)03&^ka`liib`q2XT^pqbt^kaboT^qboMlr`ebpZyyNFAy.4-4yyIy5150y
@T>KQBA7>kaobCfob_b^oayKyHfii>kaobCfob_b^oa%40+1)14+.&clrkafkqeb`bkqbolcqebSfii^dbfkIlpqOfddbo$p@lsbyyNFAy/542y
@Pqlibv$pPefmjbkqyKyXPqlibv$pPefmjbkqZ`^k_billqbacoljqebPqlibk@^odl^q%4/+/)13+5&fkpfabqebqlmcillolcqeb_rfiafkdyyNFAy/540y
@Plrqepb^Pe^hbaltkyKy>iiqebkbbabajl_p`^k_bclrkafkIlpqOfddbo$p@lsbqlqebPlrqelcPqbbjtbbaibMloq^olrka%4.)13&yyNFAy5033y
@Mfo^qbE^qp>elvyKyHfiiqebPlrqepb^Mfo^qbjl_ptef`eproolrkaqeb@lsb^olrka%4.)13&rkqfivlr$sb`liib`qba/-XPlrqepb^Mfo^qbE^qpZyyNFAy5032y

ED^adbqw^kyRy3615yyNFAy.36.y
QT^qboMlr`e?lrkqvyKyPmfdlqLmbo^qloIrdirkhbq%2/+1)/5+1&yyNFAy.4-4y
QT^pqbt^kaboGrpqf`byKy@efbcBkdfkbbo?fidbtefwwib%2/+1)/5+2&yyNFAy.36-y
>JlobT^pqbt^kaboGrpqf`byKy@efbcBkdfkbbo?fidbtefwwib%2/+1)/5+2&yyNFAy.36.y

@D^adbqw^kT^qboProsbvyKyRpbqebXRkq^mmbaAltpfkdTfadbqZ^qqebt^qbopqlqebPlrqelcWri$C^oo^h^olrka%06)0.&+Lk`liib`qflkqtl_rdpj^vpm^tkyyRy5251yyNFAy66/y
QD^adbqw^kT^qboProsbvyKyPbkfloProsbvloCfwwibaltpbo%2-+/)/4+2&yyNFAy66/y
>KluflrpI^foFksbpqfd^qflkyKyPbkfloProsbvloCfwwibaltpbo%2-+/)/4+2&yyNFAy5/y
@JlobT^pqbt^kaboGrpqf`byKyQebT^pqbt^kabojl_pkbbaba`^k_bclrkaqlqebB^pq^qqebfo`^jm^olrka%3.)03&yyNFAy.36.y
@T>KQBA7@^ifmeP`lomfapqfkdyKy@^ifmeP`lomfapqfkdfpclrkam^qoliifkdqebT^qbopmofkdCfbia^olrka%3.)03&tfqeqtloldrbp_vefppfabtef`e^obpqb^iqebayyNFAy/45.y

QPqlibv$pPefmjbkqyKyPqlibv%34+.)/0+6&yyNFAy/540y
>AbifsboqlJ^`HfkibvyKyPqlibv%34+.)/0+6&yyNFAy/541y
>PefmP`ebaribpyKyQebfqbjXPefmP`ebaribZpq^oqpqefpnrbpq*`lkq^fkbafkMfo^qb$pCllqil`hbo^olrka%4/)11&yyLyyRy6/2-yyNFAy/543y
QPefmP`ebaribpyKyPb`rofqv@efbc?fidbtefwwib%34)/0+6&yyLyyNFAy/543y
QT>KQBA7>kaobCfob_b^oayKyPb`rofqv@efbc?fidbtefwwib%34)/0+6&yyNFAy/542y
QPlrqepb^Pe^hbaltkyKyPb`rofqv@efbc?fidbtefwwib%34)/0+6&yyNFAy5033y
QMfo^qbE^qp>elvyKyE^rdeqvJlafpqb%33+2)//+0&yyNFAy5032y

ED^adbqw^kyRy3615yyNFAy0-//y
QJlobT^pqbt^kaboGrpqf`byKy@efbcBkdfkbbo?fidbtefwwib%2/+1)/5+2&yyNFAy.36.y
QT>KQBA7@^ifmeP`lomfapqfkdyKy@efbcBkdfkbbo?fidbtefwwib%2/+1)/5+2&yyNFAy/45.y
>E^kaibTfqe@^obyKy@rodib@o^khibelm%2/+0)/3+6&yyNFAy0-//y
>Pmofkhib$pPb`obqFkdobafbkqyKyPmofkhib%2.+.)/3+6&qefpobnrfobpibsbi11ql^``bmqyyNFAy/31.yyLy
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby

]]
end)
