DugisGuideViewer:RegisterGuide("The Hinterlands (46-47)", "Feralas (47)", "Alliance", "L", function()
return [[
AAA

CQebo^jlobFpibyKy?bo^Pqlkbe^jjbo%2.)/6+0&yyWyQ^k^ofpyyNFAy/655y
Q>hfofp_vqeb?rkaibyKyMofs^qbboDolv%35)20&yyWyArpqt^iiltJ^opeyyNFAy3/0y
_JbkbqefiE^o_loyKyQ^hbqeb_l^qJbk^qefiE^o_loyyNFAy/655y
CPlrqepelobyKyPebiibf?olkafo%6+2)26+4&yyWyTbqi^kapyyNFAy/655y
OQebEfkqboi^kapyKyM^qefp_befkaArokeliabHbbm%54)0-&illhcloqtldovmelkpyyWyEfiip_o^aCllqefiipyyNFAy/655y

>Tfqebo_^oh@^dbpyKyDovmelkJ^pqboQ^ilk^ub%6+5)11+2&yyNFAy/655y
>Cb^qebo_b^oa$pBkalopbjbkqyKy>j_^pp^aloOr^ibqe%.2+.)14+0&yyNFAy6136y
>>DbpqroblcDllatfiiyKy>j_^pp^aloOr^ibqe%.2+.)14+0&yyNFAy614-y
>MobvfkdlkqebMoba^qlopyKy>j_^pp^aloOr^ibqe%.2+.)14+0&yyNFAy614.y
>PhrihOl`h@ib^k*rmyKyCo^dd^oQerkaboj^kqib%.1+5)11+2&yyNFAy/544y
>QoliiKb`hi^`b?lrkqvyKyCo^dd^oQerkaboj^kqib%.1+5)11+2&yyNFAy/55-y
eTfiae^jjboHbbmyKyFkkhbbmboQerico^j%.0+/)1.+6&yyNFAy6143y
QCb^qebo_b^oa$pBkalopbjbkqyKyCb^qebo_b^oa$pGlrok^i%.0+1)22+/&yyNFAy6136y
>FkMroprfqlcCb^qebo_b^oayKyCb^qebo_b^oa$pGlrok^i%.0+1)22+/&yyNFAy6143y

HJ^kdvPfisboj^kTlisbpyKy^olrka%.6)2/&yyNFAy614.yyNLyJ^kdvPfisboj^kbpi^fk7.-,.-y
K@eb`hCfopq@^dbyNFAy/655yyNLy@eb`hCfopq@^db7.,.yyKy>qqebqolii`^jm%/0)25&y
K@eb`hPb`lka@^dbyNFAy/655yyNLy@eb`hPb`lka@^db7.,.yyKy>qqebqolii`^jm%/0)25&y
@>DbpqroblcDllatfiiyKyHfiiTfq`eAl`qloJ^f$gfk^kaefpmbqpmfaboQ`e^$h^w^q%/2)33&yyNFAy614-y
@Tfqebo_^oh@^dbpyKyDbqqebQefoaTfqebo_^oh@^dbfkqebEfof$T^qe^orfkp^olrka%0.)24&yyNFAy/655y
@MobvfkdlkqebMoba^qlopyKyHfii2Pfisboj^kbTlisbp^olrka%/4)3/&yyNFAy614.y
@QoliiKb`hi^`b?lrkqvyKyQebXQoliiKb`hi^`bpZ`^k_billqbacoljqebTfqebo_^ohjl_p^olrkaqebefiipfablcqebEfkqboi^kap^olrka%/1)24&yyNFAy/55-y
@PhrihOl`h@ib^k*rmyKyHfii.-DobbkPiradbp^kaG^abLlwbpclrka^qPhrihOl`h^olrka%24)1.&yyNFAy/544y
@QebPrmboPk^mmboCUyKyD^jjbofq^fp^qroqibm^qoliifkdlkqeb_b^`e^olrka%45)30&+Vlralk$qe^sbqlhfiifqgrpqdbq`ilpbbklrdeqlrpbqebXPrmboPk^mmboCUZ^kaq^hb^pelqlcfq)^mf`qroblcqebAb^aQroqibtfii^ipltlohyyRy60/5yyNFAy/611y
@TefphbvPifj$pIlpqDoldyKyQo^sbiqlqebB^pq`l^pqlcqebEfkqboi^kap^olrka%46)30&tef`efpproolrkaba_vKbrqo^iqroqibp^ka`liib`q./XMrmbiivsbo_lpMloqZyyNFAy25-y

E>bofbMb^hyRy3615yyNFAy/656y
QPhrihOl`h@ib^k*rmyKyCo^dd^oQerkaboj^kqib%.1+5)11+2&yyNFAy/544y
QQoliiKb`hi^`b?lrkqvyKyCo^dd^oQerkaboj^kqib%.1+5)11+2&yyNFAy/55-y
Q>DbpqroblcDllatfiiyKy>j_^pp^aloOr^ibqe%.2+.)14+0&yyNFAy614-y
QMobvfkdlkqebMoba^qlopyKy>j_^pp^aloOr^ibqe%.2+.)14+0&yyNFAy614.y
QTfqebo_^oh@^dbpyKyDovmelkJ^pqboQ^ilk^ub%6+5)11+2&yyNFAy/655y
>Qeb>iq^olcWriyKyDovmelkJ^pqboQ^ilk^ub%6+5)11+2&yyNFAy/656y
QFkMroprfqlcCb^qebo_b^oayKyCb^qebo_b^oa$pObj^fkp%04+.)4.+2&yyNFAy6143y
>Ob`i^fjfkdqebBddpyKyCb^qebo_b^oa$pObj^fkp%04+.)4.+2&yyNFAy6142y

@Ob`i^fjfkdqebBddpyKyD^qebo2XDovmelkBddpZ^olrka%01)4/&yyNFAy6142y
@Pmofkhib$pPb`obqFkdobafbkqyLyyKyDlqebS^ilotfkaI^hb%1-)3-&^kaq^hbqebXSflibqQo^d^kZcoljqeb_lqqljlcqebi^hbyyNFAy/31.yyWyQebEfkqboi^kapy
@Qeb>iq^olcWriyKyOrkqlqebqlmlcqeb>iq^olcWri^q%16)35&yyNFAy/656y
@C^slobalcBirkb<yKy@liib`q.2XTfiahfkCb^qebopZtef`e^obclrkapmob^aqeolrdelrqqebEfkqboi^kap+>ilqpbbjqlaolm^olrkaNrbi$A^kfiIladb^olrka%00)14&yyNFAy033.y

>CfkaLLU*-6,EIyKyQebfqbjXLLU*-6,EIAfpqobpp?b^`lkZpq^oqpqefpnrbpqyyRy54-1yyLyyNFAy152y
QCfkaLLU*-6,EIyLyyKyEljfkdOl_lqLLU*-6,EI%16)1-&yyNFAy152y
>Obp`rbLLU*-6,EIyLyyKyEljfkdOl_lqLLU*-6,EI%16)1-&yyNFAy503y
@Obp`rbLLU*-6,EIyLyyKyBp`loqLLU*-6,EIqlqebpelobifkb%45)35&_bvlkaLsboillh@ifccyyNFAy503y

E>bofbMb^hyRy3615yyNFAy/66-y
QOb`i^fjfkdqebBddpyKy>j_^pp^aloOr^ibqe%.2+.)14+0&yyNFAy6142y
QQeb>iq^olcWriyKyDovmelkJ^pqboQ^ilk^ub%6+5)11+2&yyNFAy/656y
>Qe^afrpDofjpe^abyKyDovmelkJ^pqboQ^ilk^ub%6+5)11+2&yyNFAy/66-y

CJbkbqefiE^o_loyKyDrqeorjQerkabocfpq%..+.)13+.&yyWyQebEfkqboi^kapyyNFAy/610y
_Qebo^jlobFpibyKy?l^qqlQebo^jlobFpib%2)30+2yyWyTbqi^kapyyNFAy/610y
COrq$qebo^kSfii^dbyKy?^iaor`%34+2)2.+0&yyWyArpqt^iiltJ^opeyyNFAy/610y
QC^slobalcBirkb<yKyBobi^p>j_bophv%22+2)6/+.&yyWyQbiao^ppfiyyNFAy033.y
QQebPrmboPk^mmboCUyKyA^ovkIfdeqtfka%22+1)6/+/&yyWyQbiao^ppfiyyNFAy/611y
>ObqrokqlQolv^pyKyA^ovkIfdeqtfka%22+1)6/+/&yyWyQbiao^ppfiyyNFAy/610y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
