DugisGuideViewer:RegisterGuide("Tanaris (47-48)", "Blasted Lands (49-50)", "Alliance", "L", function()
return [[
AAA

CD^adbqw^kyKyCviaobkJllkcb^qebo%0-+0)10+0&yyWyCbo^i^pyyNFAy/3-2y
>QebQefopqvDl_ifkyKyJ^ofkKlddbkclddbo%2.+5)/5+3&yyNFAy/3-2y
eD^adbqw^kyKyFkkhbbmboCfwwdofj_ib%2/+2)/4+6&yyNFAy2530y
>QebArkbj^ri@ljmlrkayKy>kafIvkk%2/+5)/4+1&yyNFAy2530y
>Qefpqibpeor_S^iibvyKyQo^k$obh%2.+3)/3+5&yyNFAy003/y
QQebPrkhbkQbjmibyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyNFAy0112y
>QebPqlkb@fo`ibyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyNFAy0111y
>D^ew$ofaf^kyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyNFAy0.3.y

RMrqlkqebebijbqyRy6645yyNFAy10/1y
@QebArkbj^ri@ljmlrkayKyHfii.-Arkbj^ri?orqbp^ka.-Arkbj^riBkclo`bop^olrka%1-)20&+HfiiDlo$j^olhqebO^s^dbo^q%1.+2)24+5&yyNFAy2530y
@D^ew$ofaf^kyKy@liib`q0-XD^ew$ofaf^kLok^jbkqpZ^olrka%14)30&^ka%1-)40&yyNFAy0.3.y

@Qefpqibpeor_S^iibvyKyHfii5Dk^oibaQefpqibpeor_p^olrka%0-)34&^ka5Qefpqibpeor_Ollqpe^mbop^olrka%/5)31&yyNFAy003/y
@QebQefopqvDl_ifkyKy@liib`q^XI^abkAbtDi^kaZaolmmba_vQefpqibpeor_Abt@liib`qlop^olrka%/6)30&yyNFAy/3-2y

KFcvlrcfkaQlld^+++yKy%/6+1)41+/&>``bmqqefpnrbpq+Eb$iicliiltvlr)plvlr`^k`ljmibqbKluflrpI^foFksbpqfd^qflktfqeefjlkvlroq^fi+Grpqj^hbprobvlrib^sbqebobtfqe^qib^pq.-jfkrqbpibcqlkefpqfjboyyNFAy5/y
@KluflrpI^foFksbpqfd^qflkyKyDbq2X@bkqfm^^ofkpb`qM^oqpZcoljqebKluflrpI^fo^olrka%03)1-&ql%0/)2.&yyNFAy5/y
QQlld^$pNrbpqyLyyKyQloq^%33+2)/2+4&yyNFAy.23-y
>Vrh^P`obtpmfdlqyKyVlo_^P`obtpmfdlq%34)/0+6&yyNFAy10/1y
QP`obb`eboPmfofqpyKyVbe$hfkv^%33+6)//+1&yyNFAy02/-y

QQebQefopqvDl_ifkyNFAy/3-2yyKyJ^ofkKlddbkclddbo%2.+5)/5+3&y
>FkDllaQ^pqbyKyJ^ofkKlddbkclddbo%2.+5)/5+3&yyNFAy/3-3y
QQebArkbj^ri@ljmlrkayKy>kafIvkk%2/+5)/4+1&yyNFAy2530y
QQefpqibpeor_S^iibvyKyQo^k$obh%2.+3)/3+5&yyNFAy003/y
QFkDllaQ^pqbyKyPmofkhib%2.+.)/3+6&yyNFAy/3-3y
>Pmofkhib$pPb`obqFkdobafbkqyKyPmofkhib%2.+.)/3+6&yyNFAy/31.y
QKluflrpI^foFksbpqfd^qflkyKy>i`ebjfpqMbpqibwrdd%2-+6)/4&yyNFAy5/y
>QebP`ofjpe^khObabjmqflkyKyPbkfloProsbvloCfwwibaltpbo%2-+/)/4+2&yyNFAy.-y
QD^ew$ofaf^kyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyNFAy0.3.y

@QebP`ofjpe^khObabjmqflkyKyDbqXP`ofjpe^kh$pProsbvfkdDb^oZ_vq^hfkdqebqrkkbi^q%22)4-&qebbnrfmjbkqfp^q%23)4.+/&yyNFAy.-y

ED^adbqw^kyRy3615yyNFAy..-y
QQebP`ofjpe^khObabjmqflkyKyPbkfloProsbvloCfwwibaltpbo%2-+/)/4+2&yyNFAy.-y
>Fkpb`qM^oq>k^ivpfp%M^oq.&yKyPbkfloProsbvloCfwwibaltpbo%2-+/)/4+2&yyNFAy..-y
QFkpb`qM^oq>k^ivpfp%M^oq.&yKy>i`ebjfpqMbpqibwrdd%2-+6)/4&yyNFAy..-y
>Fkpb`qM^oq>k^ivpfp%M^oq/&yKy>i`ebjfpqMbpqibwrdd%2-+6)/4&yyNFAy..0y
QFkpb`qM^oq>k^ivpfp%M^oq/&yKyPbkfloProsbvloCfwwibaltpbo%2-+/)/4+2&yyNFAy..0y
>OfpblcqebPfifqefayKyPe^kaofpCb^qebojllk%0-+0)13+.&yyWyCbo^i^pyyNFAy1/34y

CO^q`ebqyKy?bo^Pqlkbe^jjbo%2.)/6+0&y
_?llqv?^vyKyQ^hbqeb_l^qql?llqv?^v%30+4)05+3&yyWyQeb?^oobkpy
QTefphbvPifj$pIlpqDoldyKyTefphbvPifj%/4+.)44+1&yyWyPqo^kdibqelokS^ibyyNFAy25-y
QAbifsboqlJ^`HfkibvyKyPb^TlicJ^`Hfkibv%/4+5)44+.&yyWyPqo^kdibqelokS^ibyyNFAy/541y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
