DugisGuideViewer:RegisterGuide("Feralas (47)", "Tanaris (47-48)", "Alliance", "L", function()
return [[
AAA

CCb^qebojllkPqolkdeliayKySbpmovpqrp%25+1)61&yyWyQbiao^ppfiyyNFAy/546y
eCb^qebojllkPqolkdeliayKyFkkhbbmboPevof^%0.)10+2&yyNFAy/546y
QObqrokqlQolv^pyKyQolv^pJllk_obbwb%0.+5)12+2&yyNFAy/610y
>QebPq^sblcBnrfkbuyKyQolv^pJllk_obbwb%0.+5)12+2&yyNFAy/546y
>QebPrkhbkQbjmibyKy>kdbi^pJllk_obbwb%0.+6)12+3&yyNFAy0112y
>W^mmbaDf^kqpyKyWlo_fkC^ka^wwib%11+5)10+1&Lkqebj^fki^ka^qqebal`hyyNFAy4--0y
>CrbicloqebW^mmfkdyKyWlo_fkC^ka^wwib%11+5)10+1&yyNFAy44/.y

@W^mmbaDf^kqpyKyRpbXWlo_fk$pRiqo^*PeofkhboZqlw^mdf^kqpclrkafk%06)/.&yyRy.56-1yyNFAy4--0y
@CrbicloqebW^mmfkdyKy@liib`q.-XT^qboBibjbkq^i@lobpZcoljqebPb^Bibjbkq^ip^kaPb^Pmo^vp^ilkdqebClodlqqbk@l^pqlcCbo^i^p%13)2/&yyNFAy44/.y
QW^mmbaDf^kqpyKyWlo_fkC^ka^wwib%11+5)10+1&yyNFAy4--0y
QCrbicloqebW^mmfkdyKyWlo_fkC^ka^wwib%11+5)10+1&yyNFAy44/.y

@FjmolsbaNr^ifqvyKyDbq.-XO^dbP`^oVbqfEfabpZ)kloqe^qO^dbP`^oElia%2/+32)0.+42&yyNFAy4400y

>QebDf^kqDr^oaf^kyKyOl`h_fqbo%1/+1)//&kloqekb^oqebqtfk`lilpp^ipyyNFAy/511y
@QebPq^sblcBnrfkbuyKyKloqetbpq^qqebOrfkplcO^sbktfka+Cfkaqebbppbk`bp%05+2/).2+46&)%1-+22)./+31&)%06+60)6+13&)%04+43)./+.2&+RpbXQolv^p$Pq^sbZ^qqebjlklifqe%05+5).0+.&yyRy6030yyNFAy/546y
QQebPq^sblcBnrfkbuyKyBnrfkbuJlklifqe%05+5).0+.&yyNFAy/546y
>QebJlooltPqlkbyKyBnrfkbuJlklifqe%05+5).0+.&yyNFAy/61/y
QQebDf^kqDr^oaf^kyKyPe^vIb^corkkbo%05+/).-+0&)_^`hkb^oqebi^pqci^jbyyNFAy/511y
>T^kabofkdPe^vyKyPe^vIb^corkkbo%05+/).-+0&yyNFAy/512y
KDbqXPe^v$p?biiZyKyDo^_XPe^v$p?biiZcoljPe^v$p@ebpq^q%05+/).-+0&)rpbfqfcpebt^kabop^t^vyyIy6.56yyNFAy/512y
@T^kabofkdPe^vyKyQ^hbPe^vqlOl`h_fqb%1/+1)//&yyRy6.56yyNFAy/512y
QT^kabofkdPe^vyKyOl`h_fqbo%1/+1)//&yyNFAy/512y

ECb^qebojllkPqolkdeliayRy3615y
QFjmolsbaNr^ifqvyKyMo^qqJ`Dor__bk%0-+3)1/+4&yyNFAy4400y
>MofpqfkbVbqfEfabyKyRpbXMofpqfkbVbqfEfabZql_bdfkqebnrbpqyyLyyRy.5636yyNFAy4402y
QMofpqfkbVbqfEfabyKyMo^qqJ`Dor__bk%0-+3)1/+4&yyLyyNFAy4402y
QQebJlooltPqlkbyKyQolv^pJllk_obbwb%0.+5)12+2&yyNFAy/61/y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
