DugisGuideViewer:RegisterGuide("Blasted Lands (49-50)", "Searing Gorge (50-51)", "Alliance", "L", function()
return [[
AAA

CA^ohpefobyKyFkArphtllayyNFAy/3-.y
OAb^atfkaM^ppyKyDlb^pq%62+1)1.+0&qeolrdeAb^atfkaM^ppqlPt^jmlcPlooltpyyWyArphtllayyNFAy/3-.y
OPt^jmlcPlooltpyKyHbbmdlfkdqlPt^jmlcPlooltp%3/+5)1.+6&yyWyAb^atfkaM^ppyyNFAy/3-.y
Q@loqbiil$pOfaaib%M^oq.&yLyyKy>PlddvP`olii%//+6)15+2&yyWyPt^jmlcPlooltpyyNFAy3/1y

O?i^pqbaI^kapyKyOrkb^pqfkqlPt^jmlcPlooltp)qebkplrqe%00+5)46+/&yyWyPt^jmlcPlooltpyyNFAy/3-.y

cKbqebod^oabyKy>ibu^kao^@lkpq^kqfkb%32+2)/1+2&yyNFAy/3-.y
>Qeb?^pfifph$p?fqbyKy?illaj^dbIvkklob%2-+4).1+0&yyNFAy/3-.y
>Sriqrob$pSfdloyKy?illaj^dbIvkklob%2-+4).1+0&yyNFAy/3-0y
>Pkf`hboc^kdGltipyKy?illaj^dbAo^wf^i%2-+3).1+/&yyNFAy/25.y
>>?l^o$pSfq^ifqvyKy?illaj^dbAo^wf^i%2-+3).1+/&yyNFAy/250y
>QebAb`fpfsbPqofhboyKy?illaj^dbAo^wf^i%2-+3).1+/&yyNFAy/252y

K@liib`q.1XSriqrobDfww^oapZyIy5063.1yyKyB^pqlcqebol^a%20)05&)%26)/4&yyNFAy02-/y
K@liib`q..X?^pfifph?o^fkpZyIy5061..yyKyB^pqlcqebol^a%3-)1-&)%24)0.&yyNFAy02-/y
K@liib`q3X?i^pqba?l^oIrkdpZyIy506/3yyKyB^pqlcqebol^a%2/+2)21&)%24)0.&yyNFAy02-/y
K@liib`q3XP`lomlhMfk`bopZyIy50603yyKyTbpqlcqebol^a%14)/-&yyNFAy02-/y
K@liib`q2XPkf`hboc^kdGltipZyIy506.2yyKyTbpqlcqebol^a%14)/-&)%2-)05&yyNFAy02-/y

>Bsbovqefkd@lrkqpFkI^odb>jlrkqpyLyyIy.-260yyKyHrj$fpe^qeb@liib`qlo%2.+5)02+3&yyNFAy02-.y
QBsbovqefkd@lrkqpFkI^odb>jlrkqpyLyyKyHrj$fpe^qeb@liib`qlo%2.+5)02+3&yyNFAy02-.y
>LkbAo^bkbf$pGrkh+++yLyyIy.-260yyKyHrj$fpe^qeb@liib`qlo%2.+5)02+3&yyNFAy02-/y
QLkbAo^bkbf$pGrkh+++yLyyKyHrj$fpe^qeb@liib`qlo%2.+5)02+3&yyNFAy02-/y

K@ellpbvlroqrokfkloabo+++yKyQebi^pq/qrokfktfiidfsbvlr^_rcc)plp^sbvlrojlpqabpfo^_ibqtl_rcccloi^pqyyNFAy/3-.y
QQeb?^pfifph$p?fqbyKy?illaj^dbIvkklob%2-+4).1+0&yyNFAy/3-.y
QSriqrob$pSfdloyKy?illaj^dbIvkklob%2-+4).1+0&yyNFAy/3-0y
QPkf`hboc^kdGltipyKy?illaj^dbAo^wf^i%2-+3).1+/&yyNFAy/25.y
Q>?l^o$pSfq^ifqvyKy?illaj^dbAo^wf^i%2-+3).1+/&yyNFAy/250y
QQebAb`fpfsbPqofhboyKy?illaj^dbAo^wf^i%2-+3).1+/&yyNFAy/252y

QQe^afrpDofjpe^abyKyQe^afrpDofjpe^ab%34).6+1&yyNFAy/66-y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)

