DugisGuideViewer:RegisterGuide("Searing Gorge (50-51)", "Un'Goro Crater (51-52)", "Alliance", "L", function()
return [[
AAA

O@fqvlcFolkclodbyKyQo^sbiql@fqvlcFolkclodb%.5+3)2.+2&yyWyFolkclodbyyNFAy046-y
eFolkclodbyKyFkkhbbmboCfob_obt%.5+3)2.+2&yyWyFolkclodbyyNFAy046-y
>>ppfpqfkd>o`eAorfaPq^debijyKyFkkhbbmboCfob_obt%.5+3)2.+2&yyWyFolkclodbyyNFAy046-y
?.2Pfih@ilqeyIy10-3.2yyKyFcvlralk$q^iob^ave^sbqebj)qe^qfpyyNFAy1116y

CQebip^j^oyKyDovqeQeroabk%22+4)15&yyNFAy1116y
O?^ai^kapyKyOrkplrqeql?^ai^kap%15)60&yyWyIl`eJla^kyyNFAy1116y
OPb^ofkdDlodbyKyTbpqbadblcqebwlkb%.)3/&yyWy?^ai^kapyyNFAy1116y

>@^rdeqyKyTllabkLrqelrpb%32+2)3/+2&yyNFAy1116y
>Prkq^o^Pqlkbp%M^oq.&yKyAlofrpPqlkbqbkabo%30+5)3-+6&yyNFAy0034y
QPrkq^o^Pqlkbp%M^oq.&yKyPfkdbaIbqqbo%41+2).6+2&yyNFAy0034y
>Prkq^o^Pqlkbp%M^oq/&yKyPfkdbaIbqqbo%41+2).6+2&yyNFAy0035y

@@^rdeqyKyHfiiqebA^ohFolkDblildfpq^olrka%3-)3-&yyNFAy1116y

Q@^rdeqyKyTllabkLrqelrpb%32+2)3/+2&yyNFAy1116y
HHfiiJ^odliqebO^dboyKyT^kabop^olrkaplrqeb^pqlcqeblrqelrpb%40)42&yyIy.----yyNFAy0.5.y
>QebEloklcqeb?b^pqyRy.----yyKyRpbXJ^odli$pElokZql_bdfkqebnrbpq*aolmmba_vJ^odliqebO^dbotelt^kabop^olrka%40)42&yyNFAy0.5.y

>AfsfkbObqof_rqflkyKyH^i^o^kTfka_i^ab%06)06&yyNFAy011.y
@AfsfkbObqof_rqflkyKyIfpqbkqlH^i^o^kTfka_i^ab%06)06&qbiiefppqlovyyNFAy011.y
QAfsfkbObqof_rqflkyKyH^i^o^kTfka_i^ab%06)06&yyNFAy011.y
>QebCi^tibppCi^jbyKyH^i^o^kTfka_i^ab%06)06&yyNFAy011/y

OQelofrjMlfkqyKyQ^hbqebm^qeqlqebtbpq%0/)00&yyNFAy44/5y
>PQLIBK7PjfqefkdQrvbob^kaIllhlrq$pPmvdi^ppyKyT^kqba,Jfppfkd,Ilpq#Clrka%04+3)/3+3&yyNFAy44/5y
>GL?LMMLOQRKFQV7@riifkdqeb@ljmbqfqflkyKyT^kqba,Jfppfkd,Ilpq#Clrka%04+3)/3+3&yyNFAy44/6y
>@ropbQebpbC^qCfkdbopyKyE^kpbiEb^sve^kap%05+2)/4+6&yyNFAy44/0y
>CfbovJbk^`byKyE^kpbiEb^sve^kap%05+2)/4+6&yyNFAy44/1y
>Fk`bkalp^rop<Te^qbsbolp^rofpJlobIfhbFqyKyE^kpbiEb^sve^kap%05+2)/4+6&yyNFAy44/4y

C@fqvlcFolkclodbyKyI^kfbObba%04+6)0-+4&yyNFAy004.y
QPrkq^o^Pqlkbp%M^oq/&yKy@ro^qloQelofrp*jlsbp^olrkaE^iilcBumilobop_bqtbbk%43)/1&^ka%31)1&yyWyFolkclodbyyNFAy0035y
>At^osbkGrpqf`byKy@ro^qloQelofrp*jlsbp^olrkaE^iilcBumilobop_bqtbbk%43)/1&^ka%31)1&yyWyFolkclodbyyNFAy004.y

CQebip^j^oyKyDovqeQeroabk%22+2)15&yyWyFolkclodbyyNFAy0.5/y
QQebEloklcqeb?b^pqyKyJlrkq^fkbboMb__ib_fqqv%.5+/)50+6&yyWyIl`eJla^kyyNFAy0.5.y
>MollclcAbbayKyJlrkq^fkbboMb__ib_fqqv%.5+/)50+6&yyWyIl`eJla^kyyNFAy0.5/y

EFolkclodbyRy3615yyNFAy0/-.y
QMollclcAbbayKy@ro^qloQelofrp*jlsbp^olrkaE^iilcBumilobop_bqtbbk%43)/1&^ka%31)1&yyWyFolkclodbyyNFAy0.5/y
>>qI^pqyKy@ro^qloQelofrp*jlsbp^olrkaE^iilcBumilobop_bqtbbk%43)/1&^ka%31)1&yyWyFolkclodbyyNFAy0/-.y
>>IfqqibPifjbDlbp^IlkdT^vyKyI^ofpDb^oa^taib%42+2)/0&yyWyFolkclodbyyNFAy12./y

CQebip^j^oyKyDovqeQeroabk%22+2)15&yyWyFolkclodbyyNFAy0110y
Q>qI^pqyKyJlrkq^fkbboMb__ib_fqqv%.5+/)50+6&yyWyIl`eJla^kyyNFAy0/-.y

CPb^ofkdDlodbyKyOrk_^`hrmqlQebip^j^o)Qelodorj?loobiplk%00+6)2-+6&yyWyIl`eJla^kyyNFAy0110y
@PQLIBK7PjfqefkdQrvbob^kaIllhlrq$pPmvdi^ppyKyDbqqebXPjfqefkdQrvbobZaolmmba_vA^ohFolkPqb^jpjfqe^olrka%06)16&^kaXIllhlrq$pPmvdi^ppZaolmmba_vA^ohFolkIllhlrq^olrka%00)20&yyNFAy44/5y
@@ropbQebpbC^qCfkdbopyKyHfii/-Eb^svT^oDlibjpclrkafkqeb`^riaolk^ka^iilsboqebmi^`bkb^oQelofrjMlfkq%04)1/&yyNFAy44/0y
@QebCi^tibppCi^jbyKy@liib`q1XEb^oqplcCi^jbZ^ka1dil_bplcXDlibjLfiZpmob^a^olrkaPb^ofkdDlodb+J^dj^Bibjbkq^ipaolm_lqe^olrka%06)05&yyNFAy011/y
@CfbovJbk^`byKyHfii/-Dob^qboI^s^Pmfabop)tef`e^obpmob^a^ilkdqebTbpqlcPb^ofkdDlodb^olrka%0/)06&rkqfiqebbkqo^k`bql?i^`hol`hJlrkq^fkyyNFAy44/1y

QQebCi^tibppCi^jbyKyH^i^o^kTfka_i^ab%06)06&yyNFAy011/y
>ClodfkdqebPe^cqyKyH^i^o^kTfka_i^ab%06)06&yyNFAy0110y

>QebHbvqlCobbaljyLyyKyQebfqbjXDofjbpfiqLrqelrpbHbvZpq^oqpnrbpq*aolmmba_v^kvA^ohFolkat^ocyyRy..5.5yyNFAy112.y
QQebHbvqlCobbaljyLyyKyTllabkLrqelrpb%32+2)3/+2&yyNFAy112.y

QAt^osbkGrpqf`byKyAolmfkqebelib%02+3)1/+3&lkqlqebmi^qclojebia_v^`e^fk)qebkcfkaqebAvfkd>o`e^blildfpq%1.+/)/2+4&yyNFAy004.y
>Obib^pbQebjyKyAvfkd>o`e^blildfpq%1.+/)/2+4&yyNFAy004/y
@GL?LMMLOQRKFQV7@riifkdqeb@ljmbqfqflkyKyHfii.2A^ohFolkQ^phj^pqbop^ka.2A^ohFolkPi^sbop^olrka%10)/4&yyNFAy44/6y
@ClodfkdqebPe^cqyKyDbq5XQelofrjMi^qbaA^ddbopZtef`eaolmcolj^iilcqebA^ohFolkjl_p)qov^olrka%10)/4&yyNFAy0110y
@Fk`bkalp^rop<Te^qbsbolp^rofpJlobIfhbFqyKyGrjmaltk^q%13)14&tef`epelriamrqvlrkb^o^`^sbbkqo^k`btef`evlrbkqbo^kaj^hb^ofdeqq^hfkdvlrqlqebFk`bkalp^rop+Hfii/-yyNFAy44/4y

Q@ropbQebpbC^qCfkdbopyKyE^kpbiEb^sve^kap%05+2)/4+6&yyNFAy44/0y
QCfbovJbk^`byKyE^kpbiEb^sve^kap%05+2)/4+6&yyNFAy44/1y
QFk`bkalp^rop<Te^qbsbolp^rofpJlobIfhbFqyKyE^kpbiEb^sve^kap%05+2)/4+6&yyNFAy44/4y
QPQLIBK7PjfqefkdQrvbob^kaIllhlrq$pPmvdi^ppyKyQ^phj^pqboP`o^kdb%05+6)/4+4&yyNFAy44/5y
QGL?LMMLOQRKFQV7@riifkdqeb@ljmbqfqflkyKyQ^phj^pqboP`o^kdb%05+6)/4+4&yyNFAy44/6y

QClodfkdqebPe^cqyKyH^i^o^kTfka_i^ab%06)06&yyNFAy0110y
>QebCi^jb$p@^pfkdyKyH^i^o^kTfka_i^ab%06)06&yyNFAy012/y

@Obib^pbQebjyKyDbqqebXJvpqboflrp>oqfc^`qZ%/6+/)/2+6&+Qeb^oqfc^`qfpfkqebi^s^mlli^qqebqtfifdeqe^jjbo`^jm+Cliiltqebm^qeqlqebrmmbo`^jm^kacliiltfqqlqebofdeq+Qlillqqeb^oqfc^`qvlre^sbqlgrjmfkqlqebi^s^^kapq^kalkfqyyNFAy004/y
>Mo^vboqlBirkb%M^oq.&yKyW^j^biIrkqefpqib%/6+2)/3+2&yyNFAy0044y
QMo^vboqlBirkb%M^oq.&yKyW^j^biIrkqefpqib%/6+2)/3+2&yyNFAy0044y
>Mo^vboqlBirkb%M^oq/&yKyW^j^biIrkqefpqib%/6+2)/3+2&yyNFAy0045y
@Mo^vboqlBirkb%M^oq/&yKyCfkaqebXMo^vboqlBirkbZaolmmba_vjl_p^olrka%/2)02&yyNFAy0045y
@QebCi^jb$p@^pfkdyKyHfii14*2.bifqbjl_ptef`ee^sb^`e^k`bfkaolmmfkdqebXPvj_lilcO^dk^olpZ+Qebpb^obclrka^olrka%/2)03&yyNFAy012/y

QQebCi^jb$p@^pfkdyKyH^i^o^kTfka_i^ab%06)06&yyNFAy012/y
>QebQlo`elcObqof_rqflk%M^oq.&yKyH^i^o^kTfka_i^ab%06)06&yyNFAy0120y
QQebQlo`elcObqof_rqflk%M^oq.&yKyH^i^o^kTfka_i^ab%06)06&yyNFAy0120y
>QebQlo`elcObqof_rqflk%M^oq/&yKyH^i^o^kTfka_i^ab%06)06&yyNFAy0121y
QQebQlo`elcObqof_rqflk%M^oq/&yKyQlo`elcObqof_rqflk%06)06+.&yyNFAy0121y
>PnrfobJ^iqo^hbyKyH^i^o^kTfka_i^ab%06)06&yyNFAy013/y
QPnrfobJ^iqo^hbyKyPnrfobJ^iqo^hb%06)06&yyNFAy013/y
>PbqQebj>_i^wbyKyPnrfobJ^iqo^hb%06)06&yyNFAy0130y
QObib^pbQebjyKyAolmfkqebelib%02+3)1/+3&lkqlqebmi^qclojebia_v^`e^fkqebkcfka>iq^olcPrkq^o^%1.+1)/2+1&yyNFAy004/y
@PbqQebj>_i^wbyKyPbqqebPbkqovQltboplkcfobrpfkdqebXQlo`elcObqof_rqflkZ+KloqeQltbo%2-)21&)PlrqeQltbo%00)21&)B^pqQltbo%11)3.&^kaTbpqQltbo%02)3-&yyRy.-2.2yyNFAy0130y

QPbqQebj>_i^wbyKyPnrfobJ^iqo^hb%06)06&yyNFAy0130y
>Qofkhbqp+++yKyEl^oalcqeb?i^`hAo^dlkcifdeq%05+6)05+6&yyNFAy015.y
QQofkhbqp+++yKyEl^oalcqeb?i^`hAo^dlkcifdeq%05+6)05+6&yyNFAy015.y
KP^sbqebX?i^`hAo^dlkcifdeqJliqZyKyVlr$iikbbafqi^qboyyNFAy0045y

C>bofbMb^hyKyDlqlQelofrjMlfkq^kaCivql>bofbMb^h^qqebEfkqboi^kap%04+6)0-+6&yyNFAy/31.y
@Pmofkhib$pPb`obqFkdobafbkqyKyDlqebS^ilotfkaI^hb%1-)3-&^kaq^hbqebXSflibqQo^d^kZcoljqeb_lqqljlcqebi^hbyyNFAy/31.yyWyQebEfkqboi^kapy

EFolkclodbyRy3615yyNFAy1160y

CPqlojtfka@fqvyKyDovqeQeroabk%22+2)15&yyNFAy1160yyWy@fqvlcFolkclodby
_>r_boafkbyKyQ^hbqeb_l^qql>r_boafkb%//+32)22+42&yyNFAy1160yyWyPqlojtfka@fqvy
COrq$qebo^kSfii^dbyKy@^vi^fpJllkcb^qebo%03+1)12+3&yyNFAy1160yyWyA^ohpeloby
OA^ok^pprpyKyQo^sbiqlA^ok^pprp%22+6)56+5&yyNFAy1160yyWyQbiao^ppfiy
QMo^vboqlBirkb%M^oq/&yKy>pq^offPq^opbbhbo%05+/)5-+5&rmpq^fopfkqebQbjmiblcqebJllkyyWyA^ok^pprpyyNFAy0045y
QOfpblcqebPfifqefayKyDo^`fk^Pmfofqjfdeq%1/)52+5&yyWyA^ok^pprpyyNFAy1/34y
>J^o`elcqebPfifqefayKyDo^`fk^Pmfofqjfdeq%1/)52+5&yyWyA^ok^pprpyyNFAy1160y
Q>ppfpqfkd>o`eAorfaPq^debijyKy>o`eAorfaC^kao^iPq^debij%01+5)5+4&yyWyA^ok^pprpyyNFAy046-y
>Rk$DlolPlfiyKy>o`eAorfaC^kao^iPq^debij%01+5)5+4&yyWyA^ok^pprpyyNFAy0431y
e@o^cqpjbk$pQboo^`byKyQebfkkfpfkqeb@o^cqpj^k$pQboo^`b%34+/).2+4&yyWyA^ok^pprpyyNFAy12-/y
?Jfqeofi@^pfkdyIy.-23.yyKyColjqeb>r`qflkElrpb%23+1)2/+5&locfka^kbkdfkbboyyWyA^ok^pprpyyNFAy12-/y

OOrq$qebo^kSfii^dbyKyQ^hbqebmloq^iqlOrq$qebo^kSfii^db%0-+5)1.+1&yyWyA^ok^pprpyyNFAy12-/y
CO^q`ebqyKySbpmvorp%25+1)61&yyWyQbiao^ppfiyyNFAy12-/y
>Sli`^kf`>`qfsfqvyKyIfsOfwwibcfu%3/+2)05+4&yyWyQeb?^oobkpyyNFAy12-/y
@QebPqlkb@fo`ibyKyDbqqebXPqlkb@fo`ibZcoljJ^oslk$p@ebpqlrqpfabqeberq%3/+2)05+2&yyWyQeb?^oobkpyyNFAy0111y

_?llqv?^vyKyQ^hbqeb_l^qql?llqv?^v%30+4)05+3&yyNFAy/33.yyWyQeb?^oobkpy
QObp`rbLLU*-6,EIyLyyKyLdibqelombL_klqf`rp%/5+0)43+0&+Qebpb`lkaibsbilcqebal`hp+Rmqebo^jmkbuqqlqebe^kdfkdpe^oh)fkqebcfopqelrpb^cqboqebpj^ii_ofadbyyWyPqo^kdibqelokS^ibyyNFAy503y
QObp`rbLLU*.4,QKyLyyKyLdibqelombL_klqf`rp%/5+0)43+0&yyWyPqo^kdibqelokS^ibyyNFAy315y
QObp`rbLLU*//,CByLyyKyLdibqelombL_klqf`rp%/5+0)43+0&yyWyPqo^kdibqelokS^ibyyNFAy/434y

_O^q`ebqyKyQ^hbqeb_l^qqlO^q`ebq%/3)40+/&yyNFAy/33.yyWyPqo^kdibqelokS^iby
CD^adbqw^kyKy?o^dlh%30+.)14+/&yyNFAy/33.yyWyQeb?^oobkpy
QPmofkhib$pPb`obqFkdobafbkqyKyPmofkhib%2.+.)/3+6&yyWyQ^k^ofpyyNFAy/31.y
>AbifsbovcloJ^ofkyKyPmofkhib%2.+.)/3+6&yyWyQ^k^ofpyyNFAy/33.y
QAbifsbovcloJ^ofkyKyJ^ofkKlddbkclddbo%2.+5)/5+3&yyWyQ^k^ofpyyNFAy/33.y
>KlddbkclddboBifufoyKyJ^ofkKlddbkclddbo%2.+5)/5+3&yyWyQ^k^ofpyyNFAy/33/y
QKlddbkclddboBifufoyKyJ^ofkKlddbkclddbo%2.+5)/5+3&yyWyQ^k^ofpyyNFAy/33/y
>PrmboPqf`hvyWyQ^k^ofpyyKyQo^k$obh%2.+3)/3+5&yyNFAy12-1y
QJ^o`elcqebPfifqefayKy>i`ebjfpqMbpqibwrdd%2-+6)/4&yyWyQ^k^ofpyyNFAy1160y
>?rkdibfkqebGrkdibyKy>i`ebjfpqMbpqibwrdd%2-+6)/4&yyWyQ^k^ofpyyNFAy1163y

QQebPqlkb@fo`ibyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&+PlrqelcD^adbq^qqeborfkpyyWyQ^k^ofpyyNFAy0111y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
