DugisGuideViewer:RegisterGuide("Un'Goro Crater (51-52)", "Azshara (52-53)", "Alliance", "L", function()
return [[
AAA

ORk$Dlol@o^qboyKyPlrqebtbpq`lokbolcqebwlkb%/3)2/&yyWyQ^k^ofpyyNFAy1/56y
KIllq@ovpq^ip)Afoqmfibp^kaPmolrqpyKyQebob^obj^kvillqklabpp`^qqboba^`olppqefpwlkb+Vlr$iikbba4lcb^`e`lilolcmltbo`ovpq^ip+>iplillq^kvafoqmfibplopmolrqpvlrcfkayyNFAy1/51y
KVlrtfiikbba/2Rk$DlolPlfiyKy@liib`q^qib^pq/2Rk$DlolPlfi)/-uclo^nrbpqfkRk$Dlol@o^qbo^ka2uclo^klqebonrbpqi^qboyyNFAy1163y

>Qeb>mbplcRk$DlolyKyQlot^M^qecfkabo%4.+3)43&yyNFAy1/56y
>QebC^oblcI^o$hlotfyKyQlot^M^qecfkabo%4.+3)43&yyNFAy1/6-y

>Fq$p^Pb`obqqlBsbov_lav%M^oq.&yKy>Tob`hbaO^cq%30+.)35+2&yyNFAy0511y
QFq$p^Pb`obqqlBsbov_lav%M^oq.&yKy>Pj^iiM^`h%30+.)36&yyNFAy0511y
>Fq$p^Pb`obqqlBsbov_lav%M^oq/&yKy>Pj^iiM^`h%30+.)36&yyNFAy0512y
@QebC^oblcI^o$hlotfyKyCfkaqebXQeobpe^alk@^o`^ppZ%35+5)23+4&^jlkdpqqebo^mqlopyyNFAy1/6-y

QQebC^oblcI^o$hlotfyKyQlot^M^qecfkabo%4.+3)43&yyNFAy1/6-y
>QebP`bkqlcI^o$hlotfyKyQlot^M^qecfkabo%4.+3)43&yyNFAy1/6.y
@QebP`bkqlcI^o$hlotfyKyHfiiqebI^o$hlotfJ^qbp^olrka%31)31&ql`liib`q/XO^s^p^roMeboljlkbDi^kapZyyNFAy1/6.y
QQebP`bkqlcI^o$hlotfyKyQlot^M^qecfkabo%4.+3)43&yyNFAy1/6.y
>Qeb?^fqcloI^o$hlotfyKyQlot^M^qecfkabo%4.+3)43&yyNFAy1/6/y
>Tfiifabk$pGlrok^iyRy....3yyKy?bdfkpcoljX>J^kdibaGlrok^iZ*aolmmba_vo^mqlop^olrka%33)4-&yyNFAy0551y

KCfka4Obamltbo`ovpq^ipyIy...534yyNFAy1/51y
KCfka4Vbiiltmltbo`ovpq^ipyIy...554yyNFAy1/51y
KCfka4Dobbkmltbo`ovpq^ipyIy...524yyNFAy1/51y
KCfka4?irbmltbo`ovpq^ipyIy...514yyNFAy1/51y

>@e^pfkd>*Jb-.yKyH^ok^Objqo^sbi%13+2).0+1&yyNFAy1/10y
>Pefwwib$pCivboyKyPefwwib%11+/)..+2&yyNFAy12-0y
>Jrfdfk^kaI^oflkyKyJrfdfk%10)6+3&yyNFAy1.1.y
>IlpqyKyPmo^ddibCol`h%10+3)5+1&yyNFAy116/y
>?bt^oblcMqbooloa^uyKy?bt^oblcMqbooloa^u%10+3)5+2&yyNFAy12-.y
>Oliiqeb?lkbpyKyPm^ohKfijfkbo%10+2)4+2&yyNFAy055/y
>>ifbkB`lildvyKyEli$^kvbbJ^ope^i%10+6)4+0&yyNFAy0550y
QTfiifabk$pGlrok^iyKyTfiifabkJ^ope^i%10+6)4+/&yyNFAy0551y
>BumbafqflkP^is^qflkyKyTfiifabkJ^ope^i%10+6)4+/&yyNFAy055.y
@Fq$p^Pb`obqqlBsbov_lav%M^oq/&yKyCfka^kaabifsboqebm^`hqlIfkhbk%11+4)5+/&yyRy...-4yyNFAy0512y
QFq$p^Pb`obqqlBsbov_lav%M^oq/&yKyIfkhbk%11+4)5+/&yyNFAy0512y
>Fq$p^Pb`obqqlBsbov_lav%M^oq0&yKyIfkhbk%11+4)5+/&yyNFAy06-5y
cJ^ope^i$pObcrdbyKyDovcb%12+/)2+6&yyNFAy1/51y
>@ovpq^iplcMltboyKyG+A+@liifb%1.+6)/+3&yyNFAy1/51y
Q@ovpq^iplcMltboyKyG+A+@liifb%1.+6)/+3&yyNFAy1/51y
>QebKloqebokMvilkyKyG+A+@liifb%1.+6)/+3&yyNFAy1/52y
>QebB^pqbokMvilkyKyG+A+@liifb%1.+6)/+3&yyNFAy1/54y
>QebTbpqbokMvilkyKyG+A+@liifb%1.+6)/+3&yyNFAy1/55y

KHfii^kv?illambq^ip)Afbjbqo^alk)Mqbooloa^uyKyHfii^kv?illambq^ip)Afbjbqo^alk)^kaMqbooloa^uvlr`ljb^`olppyyNFAy1.1.y

@QebKloqebokMvilkyKyQebKloqebok@ovpq^iMvilkfpil`^qba^q%23+2)./+1&yyNFAy1/52y
Q@e^pfkd>*Jb-.yKy>*Jb-.%34+4).3+5&yyNFAy1/10y
@Qeb>mbplcRk$DlolyKy>iiqebkbbaba^mbp`^k_bclrkakb^o_vqeb`^sb^q%30).5&+Hfiibklrderkqfivlre^sbqtllcb^`embiqyyNFAy1/56y
@PrmboPqf`hvyKy@liib`q./XPrmboPqf`hvQ^opZcoljqebjl_pproolrkafkdqebQ^omfqp^olrka%2-)/0&yyNFAy12-1y
KCfkaX@o^qblcCllapqrccpZyKy>qqeb^_^kalkba`^jmfkqebb^pqpfablcqebwlkb%35+2/)03+26&yyIy....0yyNFAy055.y
@Jrfdfk^kaI^oflkyKy@liib`q.2X?illambq^ipZaolmmba_v?illambq^iQeobpebop^kaI^pebop^olrka%34)/5&yyNFAy1.1.y
@QebB^pqbokMvilkyKyQebil`^qflklcqebB^pqbok@ovpq^iMvilkfp^q%44+/)2-&yyNFAy1/54y
RLmbkQlot^$pMlr`eyRy..235yyNFAy641y
RMi^`bqebjb^qyRy..236yyKy>qqebci^qol`h_befkaqebb^pqmvilk%46+6)16+6&yyNFAy641y
@Qeb?^fqcloI^o$hlotfyRy..24-yyNFAy1/6/yyKyQo^sbiqlqebol`h^q%5-)2-&qebkrpbXQlot^$pMlr`eZqlprjjlkI^o$Hlotf^ibsbi23klk*bifqby
QQeb>mbplcRk$DlolyKyQlot^M^qecfkabo%4.+3)43&yyNFAy1/56y
QQeb?^fqcloI^o$hlotfyKyQlot^M^qecfkabo%4.+3)43&yyNFAy1/6/y

@>ifbkB`lildvyKyQo^sbiqlqebefsbp^olrka%2.)5-&qebkeb^aqlqebolljfkpfabqeb`^sbqlqebibcq^q%16)52&rpbqebXRkrpbaP`o^mfkdSf^iZql`liib`qqebp^jmibyyRy...0/yyNFAy0550y
@?rkdibfkqebGrkdibyKyRk$dlolPlfi`^k_b`liib`qba^iilsboqeb^ob^^kafpdbkbo^iiv^olrkaqebqobbpqrjmp+QebDlofpefjl_p^obil`^qbafk^ka^olrkaqebefsbp^q%2.)5-&tef`etfiiaolmqebXDlofpefP`bkqDi^kaZyyNFAy1163y
@BumbafqflkP^is^qflkyKyCfkaqebX@o^qblcCllapqrccpZ^q%35+2)03+3&qebkcfkaqebXObpb^o`eBnrfmjbkqZ^q%05+2)33&yyNFAy055.y
@QebTbpqbokMvilkyKyQebil`^qflklcqebTbpqbok@ovpq^iMvilkfp^q%/0+5)26+.&yyNFAy1/55y
>CfkafkdqebPlro`byKyHo^hib%0-+6)2-+1&yyNFAy641y

@Oliiqeb?lkbpyKyXAfklp^ro?lkbpZ`^k_billqbacoljqebAfbjbqo^alkptef`eproolrka%34)/6&^ka%2.)31&yyNFAy055/y
@?bt^oblcMqbooloa^uyKyMqbooloa^u^obclrkaqlqebPlrqelcRk$dlol@o^qbo^olrka%20)30&^kaqebCobkwfbaMqbooloa^u^obclrkalkqebTbpqpfab^olrka%00)05&yyNFAy12-.y
@Pefwwib$pCivboyKyQebXTb__baAfbjbqo^alkP`^ibpZ^obaolmmbacolj^kvlcqebAfbjbqo^alkpmob^aqeolrdelrqRk$dlol)vlr`^kqov^olrka%24)22&^ptbii^pqebXTb__baMqbooloa^uP`^ibpZcolj^kvMqbooloa^u%11)56&yyNFAy12-0y

@CfkafkdqebPlro`byKyQebelqqbpqpmlqfplkqebqlmlcqebsli`^kl^q%16+42)12+52&yyRy./14/yyNFAy641y
@Sli`^kf`>`qfsfqvyKyDbq6p^jmibplcXRk$Dlol>peZtef`eaolmcoljqebCfobBibjbkq^ip^qqebSli`^kl^olrka%2-)16&yyNFAy12-/y
QIlpqyKyOfkdl%2.+6)16+6&yyNFAy116/y
>>IfqqibEbimColjJvCofbkapyKyOfkdl%2.+6)16+6&yyNFAy116.y
@>IfqqibEbimColjJvCofbkapyKyQefpfp^kb^pvbp`loqnrbpqtebobvlrib^aOfkdlqlJ^ope^i$pObcrdb%10+3)5+1&+Fcebc^fkqprpbXPmo^ddib$p@^kqbbkZ+Vlrjrpq`ljmibqbqefpnrbpqtfqefk/2JfkrqbpyyRy..5-1yyNFAy116.y
Q>IfqqibEbimColjJvCofbkapyKyPmo^ddibCol`h%10+3)5+1&yyNFAy116.y
Q?bt^oblcMqbooloa^uyKyPmo^ddibCol`h%10+3)5+1&yyNFAy12-.y
QPefwwib$pCivboyKyPefwwib%11+/)..+2&yyNFAy12-0y
QJrfdfk^kaI^oflkyKyJrfdfk%10)6+3&yyNFAy1.1.y
QOliiqeb?lkbpyKyPm^ohKfijfkbo%10+2)4+2&yyNFAy055/y
Q>ifbkB`lildvyKyEli$^kvbbJ^ope^i%10+6)4+0&yyNFAy0550y
QBumbafqflkP^is^qflkyKyTfiifabkJ^ope^i%10+6)4+/&yyNFAy055.y
QQebKloqebokMvilkyKyG+A+@liifb%1.+6)/+3&yyNFAy1/52y
QQebB^pqbokMvilkyKyG+A+@liifb%1.+6)/+3&yyNFAy1/54y
QQebTbpqbokMvilkyKyG+A+@liifb%1.+6)/+3&yyNFAy1/55y
>J^hfkdPbkpblcFqyKyG+A+@liifb%1.+6)/+3&yyNFAy10/.y
QJ^hfkdPbkpblcFqyKyG+A+@liifb%1.+6)/+3&yyNFAy10/.y

QCfkafkdqebPlro`byKyHo^hib%0-+6)2-+1&yyNFAy641y
>QebKbtPmofkdpyKyHo^hib%0-+6)2-+1&yyNFAy65-y

OPfifqerpyKyQ^hbqebm^qermlrqlcqeb`o^qbofkqebkloqetbpq`lokbolcqebwlkb%/6)//&y
O@bk^oflkEliayKyCliiltqebol^a%2.+2)03+5&yyWyPfifqerpy
CD^adbqw^kyKy@ilraPhva^k`bo%2-+3)01+2&cifdeqmlfkqfprmqeb_fdefiiyyWyPfifqerpy
Q?rkdibfkqebGrkdibyKy>i`ebjfpqMbpqibwrdd%2-+6)/4&yyWyQ^k^ofpyyNFAy1163y
QPrmboPqf`hvyKyQo^k$obh%2.+3)/3+5&yyWyQ^k^ofpyyNFAy12-1y

CO^q`ebqyKy?bo^Pqlkbe^jjbo%2.)/6+0&yyWyQ^k^ofpy
QSli`^kf`>`qfsfqvyKyIfsOfwwibcfu%3/+2)05+4&yyWyQeb?^oobkpyyNFAy12-/y
_?llqv?^vyKyQ^hbqeb_l^qql?llqv?^v%30+4)05+3&yyNFAy/33.yyWyQeb?^oobkpy
C@fqvlcFolkclodbyKyCivql@fqvlcFolkclodb%/4+2)44+5&yyWyPqo^kdibqelokS^iby

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
