DugisGuideViewer:RegisterGuide("Azshara (52-53)", "Felwood (53-54)", "Alliance", "L", function()
return [[
AAA

O@fqvlcFolkclodbyKyQo^sbiql@fqvlcFolkclodb%44).-+3&yyNFAy0115yyWyFolkclodby
>M^ppfkdqeb?roabkyKyEfpqlof^kH^okfh%44).-+3&yyWyFolkclodbyyNFAy0115y
QM^ppfkdqeb?roabkyKyQvjlo%0.+/)1+4&yyWyFolkclodbyyNFAy0115y
>>o`^kbOrkbpyKyQvjlo%0.+/)1+4&yyWyFolkclodbyyNFAy0116y

>>kB^pvMf`hrmyKyQvjlo%0.+/)1+4&yyWyFolkclodbyyNFAy012-y
Q>kB^pvMf`hrmyKyUfddpCrpbifdeqbo%4.)61+/&yyWyFolkclodbyyNFAy012-y

>Pfdk^icloMf`hrmyKyUfddpCrpbifdeqbo%4.)61+/&yyWyFolkclodbyyNFAy012.y
QPfdk^icloMf`hrmyKyUfddpCrpbifdeqbo%4.)61+/&yyWyFolkclodbyyNFAy012.y

>QebErkqbo$p@e^ojyKyLijfk?rokfkd_b^oa%4-)50&yyWyFolkclodbyyNFAy5.2.yy@yErkqboy

>@bk^oflk>fayKyEfdeMofbpqOle^k%/1)5&yyWyFolkclodbyyNFAy5/21yy@yMofbpqy

>>PfjmibObnrbpqyKyErica^k?i^`h_b^oa%2.+4).1+4&yyWyFolkclodbyyNFAy5/00yy@yOldrby

CPlrqepelobyKyDovqeQeroabk%22+6)12+/&yy@yOldrbyyNFAy5/01yyWyFolkclodby
KDlqlJ^kloBkqo^k`byKyQebbkqo^k`bfp^q%41+4)/.+2&yyWyEfii_o^aCllqefiipyy@yOldrbyyNFAy5/00y
Q>PfjmibObnrbpqyKyIloaGlo^`eO^sbkeliaq%53)46&yyWy>iqbo^`Jlrkq^fkpyyNFAy5/00yy@yOldrby
>Pb^iba>wrob?^dyKyIloaGlo^`eO^sbkeliaq%53)46&yyWy>iqbo^`Jlrkq^fkpyyNFAy5/01yy@yOldrby
OPlrqepelobyKyQo^sbiqlPlrqepelob%16+0)2/+0&yyWyEfiip_o^aCllqefiipyy@yOldrbyyNFAy2202y
CJbkbqefiE^o_loyKyA^oi^E^oofp%16+0)2/+0&yy@yOldrbyyWyEfiip_o^aCllqefiipyyNFAy2202y
CJbkbqefiE^o_loyKyDovqeQeroabk%22+6)12+/&yyWyFolkclodby
_Qebo^jlobFpibyKyQ^hbqeb_l^qqlQebo^jlobFpib%2)30+2&yyNFAy2202yyWyTbqi^kapy

CClobpqPlkdyKyCivqlClobpqPlkd%34+2)2.+0&yyNFAy2202yyWyArpqt^iiltJ^opey

O>wpe^o^yKybufqb^pqlcqebj^m%64+/)16+4&yyWy>pebks^ibyyNFAy2202y

>Pmfofqr^iRkobpqyKyIle$^qr%..+1)45+.&yyNFAy2202y
>>I^kaCfiibatfqeE^qobayKyIle$^qr%..+1)45+.&yyNFAy2203y
@Pmfofqr^iRkobpqyNFAy2202yyKyQo^sbiqlqebPe^altplkdPeofkbqlqebKloqeb^pq%.3)35&^kahfii3b^`elcqebEfde_lokb>mm^ofqflkp^kaIf`eifkdpy
@>I^kaCfiibatfqeE^qobayNFAy2203yyKyHfii3E^ia^ooP^qvo)/E^ia^ooQof`hpqbop^ka/E^ia^ooCbiptlok^iiclrkaqlqebKloqeb^pq^olrka%.6)3.&y
QPmfofqr^iRkobpqyKyIle$^qr%..+1)45+.&yyNFAy2202y
Q>I^kaCfiibatfqeE^qobayKyIle$^qr%..+1)45+.&yyNFAy2203y

O>wpe^o^Qltboy@yJ^dbyyKyQ^ihqlP^k^qeIfj*vlqlqebkloqe%/5+.)2-+.&clo^cobbqbibyyNFAy5/2.y
>J^df`ArpqyKy>o`ej^dbUvibj%/6+0)1-+/&yyNFAy5/2.yy@yJ^dby

KDbq?bqe$>j^o^Or__fkdyKyFkqebOrfkplcBia^o^qe%03+53)20+/-&yyIy.-230yyNFAy0116y
KDbqJ^ohofOr__fkdyKyFkqebQbjmiblcWfk*J^ilo%06+/5)22+2.&yyIy.-232yyNFAy0116y
KDbqGfk$v^biOr__fkdyKyFkqebQbjmiblcWfk*J^ilo%06+22)2-+-6&yyIy.-231yyNFAy0116y

QQebErkqbo$p@e^ojyKyLdqfk`%1/+1)1/+4&yyNFAy5.2.yy@yErkqboy
>@lropbo>kqibopyKyLdqfk`%1/+1)1/+4&yyNFAy5.20yy@yErkqboy

Q@bk^oflk>fayKyLdqfk`%1/+1)1/+4&yyNFAy5/21yy@yMofbpqy
>Lc@lropbopTbHkltyKyLdqfk`%1/+1)1/+4&yyNFAy5/22yy@yMofbpqy

@Pb^iba>wrob?^dyNFAy5/01yy@yOldrbyyKyVlr`^kmf`hml`hbqqebXPb^iba>wrob?^dZcoljqebQfj_boj^tPe^j^kfk>wpe^o^%11)/2&y

>Hfj$g^biFkabbayNFAy03-.yyKyHfj$g^bi%20+1)/.+5&y
@Hfj$g^biFkabbayNFAy03-.yyKyQo^sbiqlqeb?illabic`^jmqlqebPlrqeb^pq^olrka%25)/6&+Ebobvlr$iicfkapbsbo^i`o^qbplcHfj$g^bi$pBnrfmjbkq+Lmbkbklrdeqfiivlr$sb`liib`qbaqeb@ljm^pp)P`lmb)Pqrccba@ef`hbk^kaTfwwibdll_boy
@J^df`ArpqyNFAy5/2.yy@yJ^dbyyKyDbq.-XDifqqbofkdArpqZaolmmba_v?illaBisbp^olrka%22)/3&y
QHfj$g^biFkabbayKyHfj$g^bi%20+1)/.+5&yyNFAy03-.y
>Hfj$g^bi$pJfppfkdBnrfmjbkqyKyHfj$g^bi%20+1)/.+5&yyNFAy2201y

QPb^iba>wrob?^dyKy>o`ej^dbUvibj%/6+0)1-+/&yyNFAy5/01yy@yOldrby
>Bk`labaCo^djbkqpyKy>o`ej^dbUvibj%/6+0)1-+/&yyNFAy5/02yy@yOldrby

QJ^df`ArpqyKy>o`ej^dbUvibj%/6+0)1-+/&yy@yJ^dbyyNFAy5/2.y
>QebPfobk$p@lo^iyKy>o`ej^dbUvibj%/6+0)1-+/&yyNFAy5/2/yy@yJ^dby

@@lropbo>kqibopyKyDbq^m^folcXMbocb`q@lropbo>kqibopZaolmmba_vJlppellc@lropbofkqebkloqebok%2.)/3&^kaplrqebokobdflk%04)36&lc>wpe^o^yyNFAy5.20yy@yErkqboy
Q@lropbo>kqibopyKyLdqfk`%1/+1)1/+4&yyNFAy5.20yy@yErkqboy
>T^sbqeo^pefkdyKyLdqfk`%1/+1)1/+4&yyNFAy5/0.yy@yErkqboy
@T^sbqeo^pefkdyNFAy5/0.yy@yErkqboyyKyDbq3XT^sbqeo^peboP`^ibpZ^olrka%54)/3&yy@yErkqboy
QT^sbqeo^pefkdyNFAy5/0.yy@yErkqboyyKyLdqfk`%1/+1)1/+4&y

@Lc@lropbopTbHkltyKyDbq1XEb^iqev@lropboDi^kapZaolmmba_vJlppellc@lropbofkqebkloqebok%2.)/3&^kaplrqebokobdflk%04)36&lc>wpe^o^yyNFAy5/22yy@yMofbpqy
QLc@lropbopTbHkltyKyLdqfk`%1/+1)1/+4&yyNFAy5/22yy@yMofbpqy
>QebF`elolcRkab^qeyKyLdqfk`%1/+1)1/+4&yyNFAy5/23yy@yMofbpqy
QQebF`elolcRkab^qeyNFAy5/23yy@yMofbpqyyKyLdqfk`%1/+1)1/+4&y

@Hfj$g^bi$pJfppfkdBnrfmjbkqyNFAy2201yyKyCfkaXPljbOrkbZqe^qqebk^d^e^sbfkqebfomlppbppflkfkqebOrfkplcBia^o^qe+Fq`^k_baolmmbacoljqebPmfqbi^pejl_pproolrkafkdqeb^ob^%04)2/&+Aolmo^qbfpilt_rqfq$p^dlla`e^k`bclo^dlla^jlrkqlcdofkafkdy
@QebPfobk$p@lo^iyNFAy5/2/yy@yJ^dbyyKyDbq3XBk`e^kqba@lo^iZaolmmba_vPmfqbi^pePfobkppmob^a^olrka%05)2.&y

QHfj$g^bi$pJfppfkdBnrfmjbkqyKyHfj$g^bi%20+1)/.+5&yyNFAy2201y
QQebPfobk$p@lo^iyNFAy5/2/yy@yJ^dbyyKy>o`ej^dbUvibj%/6+0)1-+/&y
QBk`labaCo^djbkqpyNFAy5/02yy@yOldrbyyKy>o`ej^dbUvibj%/6+0)1-+/&y

@>o`^kbOrkbpyNFAy0116yyKyDbqcfk^iP^bi$e^f%1/)31&or__fkdy
Q>o`^kbOrkbpyNFAy0116yyKyMfilqUfddpCrpbifdeqbo%44+5)6.+1&y
>ObqrokqlQvjloyKyMfilqUfddpCrpbifdeqbo%44+5)6.+1&yyNFAy013.y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
