DugisGuideViewer:RegisterGuide("Felwood (53-54)", "Winterspring (54-55)", "Alliance", "L", function()
return [[
AAA

EA^ok^pprpyRy3615yyNFAy045.y
QRk$DlolPlfiyKyGbk^i%0.+2)5+2&?befkaqebaorfap$qobbelrpbyyWyA^ok^pprpyyNFAy0431y
>Jlooltdo^fkObpb^o`e%M^oq.&yKy>o`eAorfaC^kao^iPq^debij%01+5)5+4&Rmpq^fopyyWyA^ok^pprpyyNFAy045.y
QJlooltdo^fkObpb^o`e%M^oq.&yKyJ^qeobkdvi?b^ot^ihbo%02+/)5+.&Altkpq^fopyyWyA^ok^pprpyyNFAy045.y
>Jlooltdo^fkObpb^o`e%M^oq/&yKyJ^qeobkdvi?b^ot^ihbo%02+/)5+.&yyWyA^ok^pprpyyNFAy0452y
KRpbqebBsbodobbkMlr`eyKyRpbqebBsbodobbkMlr`etebkbsbofq$p`llialtkfprmrkqfivlrdbq^iivlroJlooltdo^fkyyNFAy645y
>Jllkqlr`ebaTfiahfkyKyBobi^p>j_bophv%22+2)6/+.&AltkfkOrq$qebo^kSfii^dbyyWyQbiao^ppfiyyNFAy645y

C>pqo^k^^oyKySbpmovpqrp%25+1)61&yyWyQbiao^ppfiyyNFAy1.-.y
e>pqo^k^^oyKyFkkhbbmboHfjiv^%04)16+0&yyWy>pebks^ibyyNFAy1.-.y

OCbitllayKyEb^ab^pqlrqlcqltk+>qqebclohkb^oqebobqob^qeb^akloqelrqlcqebwlkb%22+42)/6+2-&yyWy>pebks^ibyyNFAy1.-.y
>@ib^kpfkdCbitllayKy>o^qe^kaofpPfisbophv%21+.)53+5&lkqebkloqepfablcqebol^ayyNFAy1.-.y

OBjbo^iaP^k`qr^ovyKyGrpq^eb^a)kloqelcqebol^a%2.)5.&yyNFAy2.22y
cBjbo^iaP^k`qr^ovyKyDloofj%2.+.)5/&yyNFAy2.22y
>Clo`bplcG^babk^oyKyDobq^Jlppellc%2.+/)5/+.&yyNFAy2.22y
>Qeb@loormqflklcqebG^abcfobyKyBofa^k?irbtfka%2.+0)5.+3&yyNFAy11/.y
>Sbofcvfkdqeb@loormqflkyKyQ^olkkObacb^qebo%2-+6)5.+4&yyNFAy2.23y

>Qfj_boj^t>iivyKyDo^wib%2.)52&yyNFAy513-y
@Qfj_boj^t>iivyKyHfiiAb^atllap%15)6-&plrqetbpqyyNFAy513-y
QQfj_boj^t>iivyKyDo^wib%2.)52&yyNFAy513-y
>Pmb^hqlK^cfbkyKyDo^wib%2.)52&yyNFAy513/y

RLmbkvlrollwb`lkq^fkbopyRy..6./yyNFAy2.24y
H@ropbaLlwbpyKyCliiltqebol^akloqeqlqebOrfkplc@lkpqbii^p%1-)36&+Rpbqebsf^ip^cqbovlrhfii^kaillqyyRy..6.1yyNFAy12./yyNLyCfiiba@ropbaLlwbG^o73,3y
@Qeb@loormqflklcqebG^abcfobyKyHfiicbiptlokpqlqebtbpq%06)5/&)oldrbp^kape^altpq^ihbop^ob^qqeb`^jm^q%04)36&+U^s^qeo^p`^k_bclrka^qqebc^otbpqbkalcqeborfkp%0/)34&yyNFAy11/.y
@>IfqqibPifjbDlbp^IlkdT^v%M^oq.&yKy>qqebkbuqpbqlcmlkapkloqe^ilkdqebol^a%1-)26&yyRy..615yyNFAy12./y
@Clo`bplcG^babk^oyKyHfiiG^babk^opqlqebtbpq)lrqpfabqeb`^sbp%04)26&yyNFAy2.22y

QClo`bplcG^babk^oyKyDobq^Jlppellc%2.+/)5/+.&yyNFAy2.22y
>@liib`qflklcqeb@loormqT^qboyKyDobq^Jlppellc%2.+/)5/+.&yyNFAy2.24y
QQeb@loormqflklcqebG^abcfobyKyBofa^k?irbtfka%2.+0)5.+3&yyNFAy11/.y
>Croqebo@loormqflkyKyBofa^k?irbtfka%2.+0)5.+3&yyNFAy16-3y

@@liib`qflklcqeb@loormqT^qboyKyCfiiqebXBjmqv@^kqbbkZ^qqeb`loormqbajllktbiifkG^babk^o%02+/2)26+42&yyRy./6//yyNFAy2.24y
@Sbofcvfkdqeb@loormqflkyKyKloqe^qPe^qqboP`^oS^ib%1.+0)10+2&+T^q`elrqcloqebbifqbfkcbok^ipyyNFAy2.23y
HHfiiU^s^of`yIy..335yyKy>kamf`hrmqebXCirqblcU^s^of`ZKloqefkG^abcfobOrk%06+.)//+0&yyNFAy606y
>CirqblcU^s^of`yKyQebfqbjXCirqblcU^s^of`Zpq^oqpnrbpq*aolmmba_vU^s^of`%06+.)//+0&yyRy..335yyNFAy606y
@Croqebo@loormqflkyKyDlqlqebbkqo^k`b^q%10)..&vlr`^kcfka^iiqebG^abcfobfkqefp^ob^)j^hbprobvlrhfiiU^s^of`cfopqqlpq^oqkbtnrbpqyyNFAy16-3y
@CirqblcU^s^of`yKy@liib`q2uXG^abcfobCbi_fkaZcoljqebG^abcfobp%10)..&yyNFAy606y
@@ib^kpfkdCbitllayKyHfiibibjbkq^ip^qFolkqobb@^sbok%22).4&`liib`q.2uX?illa>j_boZyyNFAy1.-.y

OQ^ilk_o^k`eDi^abyKy>qqebkloqeb^pqbadblcqebwlkb)plrqelcqebol^a%3/)/1&yyNFAy2/16y
cQ^ilk_o^k`eDi^abyKyJfpebiibk^%3/+2)/1+/&yyNFAy2/16y
CBjbo^iaP^k`qr^ovyKyJfpebiibk^%3/+2)/1+/&yyNFAy2/16y
Q@liib`qflklcqeb@loormqT^qboyKyDobq^Jlppellc%2.+/)5/+.&yyNFAy2.24y
QCroqebo@loormqflkyKyBofa^k?irbtfka%2.+0)5.+3&yyNFAy16-3y
QCirqblcU^s^of`yKyBofa^k?irbtfka%2.+0)5.+3&yyNFAy606y
QSbofcvfkdqeb@loormqflkyKyQ^olkkObacb^qebo%2-+6)5.)4&yyNFAy2.23y
Q@ib^kpfkdCbitllayKy>o^qe^kaofpPfisbophv%21+.)53+5&yyNFAy1.-.y
>QlTfkqbopmofkdyKyFsvIb^corkkbo%2-+6)5.+4&yyNFAy2/16y

CQ^ilk_o^k`eDi^abyKyDloofj%2.+.)5/&yyNFAy513.y
QPmb^hqlK^cfbkyKyK^cfbk%31+5)5+/&yyNFAy513/y
>Ab^atllalcqebKloqeyKyK^cfbk%31+5)5+/&yyNFAy513.y
@Ab^atllalcqebKloqeyKyHfiiAb^atlla^olrka%3/+2).-&yyNFAy513.y
QAb^atllalcqebKloqeyKyK^cfbk%31+5)5+/&yyNFAy513.y
>Pmb^hqlP^ic^yKyK^cfbk%31+5)5+/&yyNFAy5132y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)

