DugisGuideViewer:RegisterGuide("Winterspring (54-55)", "Burning Steppes (55-56)", "Alliance", "L", function()
return [[
AAA

OTfkqbopmofkdyKyBufqCbitllakloqeqeolrdeqeb`^sbyyNFAy5131y
QPmb^hqlP^ic^yKyP^ic^%/4+5)01+2&yyNFAy5132y
>Tfkqboc^ii>`qfsfqvyKyP^ic^%/4+5)01+2&yyNFAy5131y
KDo^_cb^qebopvlrpbbyKyCloJllkqlr`ebaTfiahfkyyNFAy645y
QQebKbtPmofkdpyKyAlkls^Pkltabk%0.+0)12+/&yyNFAy65-y
>Pqo^kdbPlro`bpyKyAlkls^Pkltabk%0.+0)12+/&yyNFAy151/y
QFq$p^Pb`obqqlBsbov_lav%M^oq0&yNFAy06-5yyKyAlkls^Pkltabk%0.+0)12+/&y
>Qeob^qlcqebTfkqboc^iiyKyAlkls^Pkltabk%0.+0)12+/&yyNFAy2-5/y

OBsboillhyKyCliiltqebol^ab^pq%3-)04&yyNFAy33-1y
>Bko^dbaTfiahfk%M^oq.&yKyE^oilTfddibptloqe%3.+.)05+1&yyNFAy33-1y
eBsboillhyKyFkkhbbmboSfwwfb%3.+0)05+6&yyNFAy3-/5y
>QebBsboillhObmloqyKyDobdloDobvpqlkb%3.+0)05+6&yyNFAy3-/5y
>ArhbKf`eli^pWsbobkelccyKyDobdloDobvpqlkb%3.+0)05+6&yyNFAy3-0-y
>PfpqboM^jbi^yKyGbppf`^Obam^qe%3.+0)05+6&yyNFAy23-.y
>>obTbQebob)Vbqf<%M^oq.&yKyRjfOrjmibpkf`hbo%3-+6)04+4&yyNFAy0450y
>RopfrplcqebPe^oaqllqeyKyPqlojPe^altellc%3.+6)05+1&yyNFAy2-21y

@RopfrplcqebPe^oaqllqeyKyHfiiRopfrp)^_b^o)kloqelcBsboillhebpm^tkp^q%23+1)0/+1&lo^p^cbomi^`bql`^jmfp^q%30)0-&yyNFAy2-21y
QRopfrplcqebPe^oaqllqeyKyPqlojPe^altellc%3.+6)05+1&yyNFAy2-21y
>?orjbo^klcqeb@efiitfkayKyPqlojPe^altellc%3.+6)05+1&yyNFAy2-22y
@?orjbo^klcqeb@efiitfkayKyHfii?orjbo^k%3.)23+0&yyNFAy2-22y

@Pqo^kdbPlro`bpyKyCliiltAlkls^Pkltabk$pfkpqor`qflkp)grpqcliiltqebol^aplrqelrqlcBsboillhql%3-)40&yyNFAy151/y

EBsboillhyRy3615yyNFAy644y
Q?orjbo^klcqeb@efiitfkayKyPqlojPe^altellc%3.+6)05+1&yyNFAy2-22y
@>obTbQebob)Vbqf<%M^oq.&yKyDbq.-XQef`hVbqfCropZaolmmba_vF`bQefpqibVbqf^olrka%33+2)12+/&yyNFAy0450y
Q>obTbQebob)Vbqf<%M^oq.&yKyRjfOrjmibpkf`hbo%3-+6)04+4&yyNFAy0450y
>>obTbQebob)Vbqf<%M^oq/&yKyRjfOrjmibpkf`hbo%3-+6)04+4&yyNFAy644y
@>obTbQebob)Vbqf<%M^oq/&yKyDbq/XMofpqfkbVbqfElokpZcoljqeb`^sb^q%34)1.&yyNFAy644y
Q>obTbQebob)Vbqf<%M^oq/&yKyRjfOrjmibpkf`hbo%3-+6)04+4&yyNFAy644y
>>obTbQebob)Vbqf<%M^oq0&yKyRjfOrjmibpkf`hbo%3-+6)04+4&yyNFAy2.30y
KP`^obIbd^`hfyKyB^pqlcqebfkk)rpbqebVbqfyyRy./6/5yyNFAy2.30yyNLyP`^obIbd^`hf7.,.y

@Tfkqboc^ii>`qfsfqvyKyHfii5Tfkqboc^iiPe^j^k^olrka%35)04&)5Tfkqboc^iiAbkT^q`ebop^olrka%34)01&)^ka5Tfkqboc^iiRop^^olrka%34)03&yyNFAy5131y
QQlTfkqbopmofkdyKyTvkaKfdeq`e^pbo%2/)0-+0&yyNFAy2/16y
>QebOrfkplcHbi$QebofiyKyTvkaKfdeq`e^pbo%2/)0-+0&yyNFAy2/11y
QBko^dbaTfiahfk%M^oq.&yKyG^olkPqlkbpe^mbo%2/+.)0-+1&yyNFAy33-1y
QQebOrfkplcHbi$QebofiyKyG^olkPqlkbpe^mbo%2/+.)0-+1&yyNFAy2/11y
>Qolr_ibaPmfofqplcHbi$QebofiyKyG^olkPqlkbpe^mbo%2/+.)0-+1&yyNFAy2/12y

@Qolr_ibaPmfofqplcHbi$QebofiyKyRpbXG^olk$pMf`hZqlcfkaqebclroEfde_lokbObif`Co^djbkqp^olrkaI^hbHbi$Qebofi+CfopqObif`Co^djbkq%22)10&)Pb`lka%2.)1/&)Qefoa%20)1/&^kaClroqe%2/)1/&yyNFAy2/12yyRy./56.y
@Qeob^qlcqebTfkqboc^iiyKyHfii5Tfkqboc^iiM^qecfkabop)5Tfkqboc^iiAbkT^q`ebop)^ka5Tfkqboc^iiQlqbjf`p^olrka%0-)02&yyNFAy2-5/y
@Jllkqlr`ebaTfiahfkyKyDbq.-XJllkqlr`ebaCb^qebopZ)qebpb_irbcb^qebop^obpmob^a^olrkaTfkqbopmofkd)vlr`^kqov^olrka%12)10&yyNFAy645y
>Tfkqboc^iiCfobt^qboyRy./44.yyKyQebfqbjXBjmqvCfobt^qboCi^phZpq^oqpnrbpq*aolmmba_vTfkqboc^iiAbkT^q`ebo^kaTfkqboc^iiM^qecfkabo^olrka%1-)1/&yyNFAy2-50y
QPqo^kdbPlro`bpyKyAlkls^Pkltabk%0.+0)12+/&yyNFAy151/y
QQeob^qlcqebTfkqboc^iiyKyAlkls^Pkltabk%0.+0)12+/&yyNFAy2-5/y
QTfkqboc^iiCfobt^qboyKyAlkls^Pkltabk%0.+0)12+/&yyNFAy2-50y
>C^iifkdql@loormqflkyKyAlkls^Pkltabk%0.+0)12+/&yyNFAy2-51y
QTfkqboc^ii>`qfsfqvyKyP^ic^%/4+5)01+2&yyNFAy5131y

OCbitllayKyQeolrdeqebqrkkbi%.6)04&yyNFAy2-52y
QC^iifkdql@loormqflkyKyAb^atlla@^riaolk%3-+/)2+6&yyWyCbitllayyNFAy2-51y
>JvpqbovDllyKyAb^atlla@^riaolk%3-+/)2+6&yyWyCbitllayyNFAy2-52y
QJvpqbovDllyKyAlkls^Pkltabk%0.+0)12+/&yyNFAy2-52y

EBsboillhyRy3615yyNFAy.-14y
COrq$qebo^kSfii^dbyKyJ^bqeov^%3/+0)03+3&yyNFAy.-14y
QJllkqlr`ebaTfiahfkyKyBobi^p>j_bophv%22+2)6/+.&yyWyQbiao^ppfiyyNFAy645y
OA^ok^pprpyKyRpbqebmloq^i^q%22+6)56+5&yyWyQbiao^ppfiyyNFAy.-14y

>QebKbtColkqfbo%M^oq.&yKyEbo^iaJllkpq^ihbo*pebt^kabop^olrkaqltk^ka^`olppqeb_ofadbyyWyA^ok^pprpyyNFAy.-14y
QQebKbtColkqfbo%M^oq.&yKy>o`eAorfaC^kao^iPq^debij%01+5)5+4&yyWyA^ok^pprpyyNFAy.-14y
>QebKbtColkqfbo%M^oq/&yKy>o`eAorfaC^kao^iPq^debij%01+5)5+4&yyWyA^ok^pprpyyNFAy343.y
QQebKbtColkqfbo%M^oq/&yKyJ^qeobkdvi?b^ot^ihbo%02+/)5+.&yyWyA^ok^pprpyyNFAy343.y
>O^_fkbP^qrok^yKyJ^qeobkdvi?b^ot^ihbo%02+/)5+.&yyWyA^ok^pprpyyNFAy343/y

CJllkdi^abyKyFcvlralk$qe^sbqebcifdeqmlfkq)civqlQ^ilk_o^k`eDi^ab^kaorkkloqeqeorQfj_boj^tElia)Aorfap`^kgrpqqbibmloqqebobyyNFAy../1y
QO^_fkbP^qrok^yKyO^_fkbP^qrok^%2.+4)11+6&yyWyJllkdi^abyyNFAy343/y
>T^pqbi^kayKyO^_fkbP^qrok^%2.+4)11+6&yyWyJllkdi^abyyNFAy../1y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)

