DugisGuideViewer:RegisterGuide("Burning Steppes (55-56)", "Silithus (56)", "Alliance", "L", function()
return [[
AAA

C@fqvlcFolkclodbyNFAy04-/y
eFolkclodbyKyFkkhbbmboCfob_obt%.5+3).2+2&yyWyFolkclodbyyNFAy04-/y
Q>IfqqibPifjbDlbp^IlkdT^vyKyI^ofpDb^oa^taib%42+2)/0&FkqebE^iilcBumilobop*PHFMqebcliilt*rmyyWyFolkclodbyyNFAy12./y
>QebPjliabofkdOrfkplcQe^rofpp^k%M^oq.&yKyOlv^iEfpqlof^k>o`ebplkrp%05+4)22+2&yyWyFolkclodbyyNFAy04-/y
QQebPjliabofkdOrfkplcQe^rofpp^k%M^oq.&yKyOlv^iEfpqlof^k>o`ebplkrp%05+4)22+2&yyWyFolkclodbyyNFAy04-/y
>QebPjliabofkdOrfkplcQe^rofpp^k%M^oq/&yKyOlv^iEfpqlof^k>o`ebplkrp%05+4)22+2&yyWyFolkclodbyyNFAy04-.y
>Q^hfkd?^`hPfifqerpyKy@bk^oflkBjfpp^ovG^abjllk%24)16&yyWyFolkclodbyyNFAy5/42y

CI^hbpefobyKyObaofadbJlrkq^fkp*DovqeQeroabk%22+2)14+0&yyWyFolkclodbyyNFAy05/0y
O?rokfkdPqbmmbpyKyCliiltqebol^akloqe%13)3&yyWyObaofadbJlrkq^fkpyyNFAy05/0y
cJlod^k$pSfdfiyKy?lodrpPqlrq^oj%51+1)35+0&yyNFAy05/0y
>BuqfkdrfpeqebCfobdrqyKyLo^ifrp%51+3)35+3&yyNFAy05/0y
>CFCQVVBMyKyLo^ifrp%51+3)35+3&yyNFAy1/50y

@BuqfkdrfpeqebCfobdrqyKyHfiildobpaltk^qqebjlrkq^fk%5/)21&+Jlpqlcqebj^dbp`^k_bclrkafkqeb`^sblkqebkloqebokc^`b%50)06&yyNFAy05/0y
QBuqfkdrfpeqebCfobdrqyKyLo^ifrp%51+3)35+3&yyNFAy05/0y
>Dlo$qbpeqeb?orqbIloayKyLo^ifrp%51+3)35+3&yyNFAy05/1y

QVrh^P`obtpmfdlqyKyVrh^P`obtpmfdlq`^k_bclrkafkqeb`^sbrmkloqe^qCi^jb@obpq%33)//&*PHFMqebcliilt*rmyyNFAy10/1y
>Q^_ibqlcqebPbsbkyKyJ^utloqR_bodifkq%32+/)/0+5&yyNFAy1/63y
>?ollaifkdBppbk`byKyQfkhbbPqb^j_lfi%32)/1&yyNFAy14/3y

@Q^_ibqlcqebPbsbkyKyQ^ihqlqebalocpq^qrb%21)1-&yyNFAy1/63y
@QebPjliabofkdOrfkplcQe^rofpp^k%M^oq/&yKySbkqrobqlqeborfkp%22)1-&^kaillqqebmfii^opyyNFAy04-.y
@Dlo$qbpeqeb?orqbIloayKyHfiiDlo$qbpe^qMfii^olc>pe%1-)22&^kaqebkq^hbXDlo$qbpe$pIlmmbaLccEb^aZyyNFAy05/1y
@CFCQVVBMyKyHfiilo`p^q?i^`hol`hPqolkdelia%10)03&loMfii^olc>pe%16)22&yyNFAy1/50y

@?ollaifkdBppbk`byKyCfkaAo^dlkpqlqebkloqeb^pq%52)26&%6-+2)13+6&RpbqebXAo^`l*Fk`^o`fk^qofu6--Zlkqebj)qebkhfiiqebj+Dbqebimfcvlr`^kyyRy.//51yyNFAy14/3y

>>Q^pqblcCi^jbyKy@vorpQebobmbkqlrpfkqeb`^sb%62)0.+3&yyNFAy1-//y
Q>Q^pqblcCi^jbyKy@vorpQebobmbkqlrp%62)0.+3&*PHFMqebcliilt*rmyyNFAy1-//y

QCFCQVVBMyKyLo^ifrp%51+3)35+3&yyNFAy1/50y
QDlo$qbpeqeb?orqbIloayKyLo^ifrp%51+3)35+3&yyNFAy05/1y
>LdobEb^aLk>Pqf`h:M^oqvyKyLo^ifrp%51+3)35+3&yyNFAy05/2y

@LdobEb^aLk>Pqf`h:M^oqvyKyRmlkqebldobjlrkq^fk%5.+-)13+5&yyRy..-46yyNFAy05/2y
QLdobEb^aLk>Pqf`h:M^oqvyKyLo^ifrp%51+3)35+3&yyNFAy05/2y

QQ^_ibqlcqebPbsbkyKyJ^utloqR_bodifkq%32+/)/0+5&yyNFAy1/63y
Q?ollaifkdBppbk`byKyQfkhbbPqb^j_lfi%32)/1&yyNFAy14/3y

EFolkclodbyRy3615y
QQebPjliabofkdOrfkplcQe^rofpp^k%M^oq/&yKyOlv^iEfpqlof^k>o`ebplkrp%05+4)22+2&yyWyFolkclodbyyNFAy04-.y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
