DugisGuideViewer:RegisterGuide("Western Plaguelands (56-57)", "Eastern Plaguelands (57-58)", "Alliance", "L", function()
return [[
AAA

OPqlojtfka@fqvyKyQo^sbiqlPqlojtfka@fqvyyNFAy2-33y
ePqlojtfka@fqvyKyFkkhbbmbo>iifplk%3-+2)42+/&yyWyPqlojtfka@fqvyyNFAy2-33y
KIllhclo@ofboDllaj^kfkqeb@fqvyKyEbm^qolip^iilsboqeb`fqv)ofab^olrkab^`eafpqof`q^kavlrpelriacfkaefjyyNFAy2-33y
>>@^iiql>ojp7QebMi^drbi^kapyKyColj@ofboDllaj^k)ebm^qolip^iilsboqeb`fqvyyNFAy2-33y

C@fqvlcFolkclodbyNFAy26-0y
QObqrokqlQvjloyNFAy013.yyLyyKyQvjlo%0.+/)1+4&FkFolkclodbyyWyFolkclodby

CPlrqepelobyNFAy26-0y
OTbpqbokMi^drbi^kapyKyCliiltqebol^akloqelrqlcqebwlkb%5-)/6&)b^pqqeor>iqbo^`rkqfivlr`ljbql@efiitfka@^jmyyWy>iqbo^`Jlrkq^fkpyyNFAy26-0y
QQebBsboillhObmloqyKy>odbkqLccf`boMrobeb^oq%10)50+3&yyNFAy3-/5y
c@efiitfka@^jmyKy?f_fic^wCb^qebotefpqib%1/+6)52&yyNFAy26-0y
>>Mi^drbRmlkQebb%M^oq.&yKyK^qe^kfbiArj^e%10+2)51+5&yyNFAy26-0y
>QebJ^ohlcqebIfdeq_ofkdboyKyColj>k`elofqbQorrbk%1/+6)51+2&+Ebj^vklq_bfkqeb`^jmfceb$plrqalfkdqebbp`loqnrbpqyyNFAy6141y
Q>@^iiql>ojp7QebMi^drbi^kapyKy@ljj^kabo>pei^jS^ilocfpq%1/+4)51&yyNFAy2-33y
>@ib^oqebT^vyKy@ljj^kabo>pei^jS^ilocfpq%1/+4)51&yyNFAy2-6/y
KDbq^@ljjfppflkyKyQ^ihqlqebnr^oqboj^pqbo^kadbq^`ljjfppflk)vlrpelriae^sbqefpbnrfmmba^kvqfjbvlr^obfkqebmi^drbi^kap+Qrokfk^kvp`lrodbpqlkbpvlrdbqtebkvlr^obfkqltkfcvlre^sb^criipq^`hyyIy./513yyNFAy2-6/y

@@ib^oqebT^vyKyHfiiqebRkab^apqlqebkloqeb^pq^qPlooltEfii%2-)5-&yyNFAy2-6/y
Q@ib^oqebT^vyKy@ljj^kabo>pei^jS^ilocfpq%1/+4)51&yyNFAy2-6/y
>>ii>ilkdqebT^q`eqltbopyKy@ljj^kabo>pei^jS^ilocfpq%1/+4)51&yyNFAy2-64y
>QebP`lrodb@^riaolkpyKy@ljj^kabo>pei^jS^ilocfpq%1/+4)51&yyNFAy2/.2y
QQebP`lrodb@^riaolkpyKyEfdeMofbpqbppJ^`Alkkbii%1/+6)51+1&yyNFAy2/.2y
>Q^odbq7CbipqlkbCfbiayKyEfdeMofbpqbppJ^`Alkkbii%1/+6)51+1&yyNFAy2/.3y

@>ii>ilkdqebT^q`eqltbopyRy./5.2yyKyRpbqebX?b^`lkQlo`eZqlj^ohb^`eqltbofk>kaloe^i)vlr`^kdbq`ilpbbklrdeqlj^ohtfqelrq^ddolfkdjl_pfkpfabfcvlr^ob`^obcri+%14)4.&%1-)4.&%1/)33&%11)30&yyNFAy2-64y
@Q^odbq7CbipqlkbCfbiayKyQlqebkloqetbpq^qCbipqlkbCfbia%04)23&+Hfii@^riaolkIloa?fibj^tcloqebXCbipqlkbCfbia@^riaolkHbvZ)qebkofdeq*`if`hlkqeb`^riaolkyyNFAy2/.3y
QQ^odbq7CbipqlkbCfbiayKyP`lrodb@^riaolk%04+/)23+6&yyNFAy2/.3y
>Obqrokql@efiitfka@^jm%M^oq.&yKyP`lrodb@^riaolk%04+/)23+6&yyNFAy2/.4y

>?bqqboI^qbQe^kKbsbo%M^oq.&yKyG^kf`bCbipqlkb)Fkqebelrpblkqebkloqeb^pqpfablcqebcfbia%05+1)21+.&)rmpq^fopyyNFAy2-/.y
Q?bqqboI^qbQe^kKbsbo%M^oq.&yKyG^kf`b$pM^o`bi%05+5)22+/&yyNFAy2-/.y
>?bqqboI^qbQe^kKbsbo%M^oq/&yKyG^kf`b$pM^o`bi%05+5)22+/&yyNFAy2-//y

Q>ii>ilkdqebT^q`eqltbopyKy@ljj^kabo>pei^jS^ilocfpq%1/+4)51&yyNFAy2-64y
>P`elilj^k`byKy@ljj^kabo>pei^jS^ilocfpq%1/+4)51&yyNFAy2200y
QP`elilj^k`byKy>i`ebjfpq>o_fkdqlk%1/+4)50+5&yyNFAy2200y
>Phbibq^iCo^djbkqpyKy>i`ebjfpq>o_fkdqlk%1/+4)50+5&yyNFAy2204y
QObqrokql@efiitfka@^jm%M^oq.&yKyEfdeMofbpqbppJ^`Alkkbii%1/+6)51+1&yyNFAy2/.4y
>Q^odbq7A^iplk$pQb^opyKyEfdeMofbpqbppJ^`Alkkbii%1/+6)51+1&yyNFAy2/.6y

@Q^odbq7A^iplk$pQb^opyKyQlqebkloqe^qA^iplk$pQb^op%13)2/&+Hfii@^riaolkIloaJ^isfkflrpcloqebXA^iplk$pQb^op@^riaolkHbvZ)qebkofdeq*`if`hlk`^riaolkyyNFAy2/.6y
QQ^odbq7A^iplk$pQb^opyKyP`lrodb@^riaolk%13+/)2/+.&yyNFAy2/.6y
>Obqrokql@efiitfka@^jm%M^oq/&yKyP`lrodb@^riaolk%13+/)2/+.&yyNFAy2//-y

KOb^aJop+A^iplk$pAf^ovyKyLkqebcillofkqeb_^ok%14+5)2-+4&+Klqefkdql^``bmq)grpqob^aqeb_llhyyNFAy2//-y
HT^kabofkdPhbibqlkyKyM^qolip^olrkaqebelrpb^ka_^ok%14+3)2.+3&)vlr^obillhfkdcloqeblrqelrpbhbv+P`^oibqpjfdeqhfiiqefpjl_yyIy./405yyNFAy2//-y
HC^ojboA^iplkyKyHfiiC^ojboA^iplk%15+/)16+0&lmbkqeblrqelrpb)dbqefphbvyyIy./406yyNFAy2//-y
KLmbk`^_fkbqyKyIl`hba`^_fkbqrmpq^fopfkqebelrpbyyIy.0142yyNFAy2//-y

QObqrokql@efiitfka@^jm%M^oq/&yKyEfdeMofbpqbppJ^`Alkkbii%1/+6)51+1&yyNFAy2//-y
>Q^odbq7TofqefkdE^rkqyKyEfdeMofbpqbppJ^`Alkkbii%1/+6)51+1&yyNFAy2///y

EPqlojtfka@fqvyRy3615yyNFAy2-15y
Q?bqqboI^qbQe^kKbsbo%M^oq/&yKyOlv^iC^`qlo?^qeofilo%24+0)15+/&yyWyPqlojtfka@fqvyyNFAy2-//y
>DllaK^qrobaBjj^yKyOlv^iC^`qlo?^qeofilo%24+0)15+/&yyWyPqlojtfka@fqvyyNFAy2-15y
QDllaK^qrobaBjj^yKyLi$Bjj^)Pebm^qolip_bqtbbkqeb`^qebao^i%3-+0)23+6&^kaqo^abafpqof`q%33+/)4-+6&yyWyPqlojtfka@fqvyyNFAy2-15y
>DllaIr`h@e^ojyKyLi$Bjj^)Pebm^qolip_bqtbbkqeb`^qebao^i%3-+0)23+6&^kaqo^abafpqof`q%33+/)4-+6&yyWyPqlojtfka@fqvyyNFAy2-2-y
>QebCfopq^kaqebI^pqyKyHfkdS^of^kTovkk%46+6)05+3&FkPqlojtfkaHbbmyyWyPqlojtfka@fqvyyNFAy3.5/y
QQebCfopq^kaqebI^pqyKyJ^pqboJ^qef^pPe^t%45+2)4-+4&FkLiaQltkyyWyPqlojtfka@fqvyyNFAy3.5/y
>ElkloqebAb^ayKyJ^pqboJ^qef^pPe^t%45+2)4-+4&yyWyPqlojtfka@fqvyyNFAy3.50y
QElkloqebAb^ayKyJ^pqboJ^qef^pPe^t%45+2)4-+4&yyWyPqlojtfka@fqvyyNFAy3.50y
>CifkqPe^altjlobyKyJ^pqboJ^qef^pPe^t%45+2)4-+4&yyWyPqlojtfka@fqvyyNFAy3.51y

CTbpqbokMi^drbi^kapyNFAy3.52y
QCifkqPe^altjlobyKyCifkqPe^altjlob%10+3)51+2&yyNFAy3.51y
>QebB^pqbokMi^drbpyKyCifkqPe^altjlob%10+3)51+2&yyNFAy3.52y

QDllaIr`h@e^ojyKyG^kf`bCbipqlkb)Fkqebelrpblkqebkloqeb^pqpfablcqebcfbia%05+1)21+.&)rmpq^fopyyNFAy2-2-y
>QtlE^isbp?b`ljbLkbyKyG^kf`bCbipqlkb%05+1)21+.&yyNFAy2-2.y
@QtlE^isbp?b`ljbLkbyKyDllrqfkqebcfbia^kahfiiqebG^__bofkdDelri%04)22+4&%lkivlkbtfqe^mfq`ecloh&)qebk`lj_fkbqebmfb`bpyyNFAy2-2.yyRy./4//y
QQtlE^isbp?b`ljbLkbyKyG^kf`bCbipqlkb%05+1)21+.&yyNFAy2-2.y

@Q^odbq7TofqefkdE^rkqyKyQlqebplrqeb^pq^qTofqefkdE^rkq%20)32&Hfii@^riaolkIloaO^w^o`ecloqebXTofqefkdE^rkq@^riaolkHbvZ)qebkofdeq*`if`hlk`^riaolkyyNFAy2///y
QQ^odbq7TofqefkdE^rkqyKyP`lrodb@^iaolk%20)32&yyNFAy2///y
>Obqrokql@efiitfka@^jm%M^oq0&yKyP`lrodb@^iaolk%20)32&yyNFAy2//0y

>QebTfiaifcbPrccbopQll%M^oq.&yKyJridofpAbbmofsbo%20+4-)31+4&yyNFAy1651y
@QebTfiaifcbPrccbopQll%M^oq.&yKyHfii5uAfpb^pbaTlisbp%12)12&)_bqtbbkqebCbipqlkb^kaA^iplk$pCfbiapyyNFAy1651y
QQebTfiaifcbPrccbopQll%M^oq.&yKyJridofpAbbmofsbo%20+4-)31+4&yyNFAy1651y
>QebTfiaifcbPrccbopQll%M^oq/&yKyJridofpAbbmofsbo%20+4-)31+4&yyNFAy1652y

QObqrokql@efiitfka@^jm%M^oq0&yKyEfdeMofbpqbppJ^`Alkkbii%1/+6)51+1&yyNFAy2//0y
>Q^odbq7D^eoolk$pTfqebofkdyKyEfdeMofbpqbppJ^`Alkkbii%1/+6)51+1&yyNFAy2//2y

@QebTfiaifcbPrccbopQll%M^oq/&yKyB^pq)_bqtbbkTofqefkdE^rkq%25)3/&^kaD^eoolk$pTfqebofkd%3.)20&yyNFAy1652y

@Q^odbq7D^eoolk$pTfqebofkdyKyQlqebb^pq^qTofqefkdE^rkq%3/)25&+Hfii@^riaolkIloaPlrito^qecloXD^eoolk$pTfqebofkd@^riaolkHbvZ)qebkofdeq*`if`hlk`^riaolkyyNFAy2//2y
QQ^odbq7D^eoolk$pTfqebofkdyKyP`lrodb@^iaolk%3/)25&yyNFAy2//2y
>Obqrokql@efiitfka@^jm%M^oq1&yKyP`lrodb@^iaolk%3/)25&yyNFAy2//3y

QQebTfiaifcbPrccbopQll%M^oq/&yKyJridofpAbbmofsbo%20+4-)31+4&yyNFAy1652y

QObqrokql@efiitfka@^jm%M^oq1&yKyEfdeMofbpqbppJ^`Alkkbii%1/+6)51+1&yyNFAy2//3y
KJfppflk>``ljmifpebayKy@ljj^kabo>pei^jS^ilocfpq%1/+4)51&y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
