DugisGuideViewer:RegisterGuide("Silithus (56)", "Western Plaguelands (56-57)", "Alliance", "L", function()
return [[
AAA

OD^adbqw^kyKyQo^sbiqlD^adbqw^kyyNFAy5/51y
KP`^obPmofkhibyKyCfkaPmofkhib%2.+.)/3+6&Kloqetbpqpfablcqltk)rpbqebVbqfyyRy./6/5yyNFAy2.30yyNLyP`^obPmofkhib7.,.yyWyQ^k^ofpy

CRk$Dlol@o^qboyNFAy5/51y
KP`^obNrfuufiyKyCfkaNrfuufi%10+4)6+1&^karpbqebVbqfyyRy./6/5yyNFAy2.30yyNLyP`^obNrfuufi7.,.yyWyRk$Dlol@o^qboy

CPfifqerpyNFAy5/51y
>QebQtfifdeqJvpqbovyKyDblildfpqI^ohp_^kb%16+4)04+0&yyNFAy5/51y
QQ^hfkd?^`hPfifqerpyKyTfka`^iiboMolraelok%2.+.)05+/&yyNFAy5/42y
>Pb`rofkdqebPrmmivIfkbpyKyTfka`^iiboMolraelok%2.+.)05+/&yyNFAy5/5-y
e@bk^oflkEliayKy@^i^kao^qe%2.+6)06+.&yyNFAy5/44y
>Ab^aivAbpboqSbkljyKy?bbqfuCf`hibpmo^dd%2.+4)05+3&yyNFAy5/44y

@QebQtfifdeqJvpqbovyKyDbq5XQtfifdeqQ^_ibqCo^djbkqpZclrkafkqebkloqe*tbpq^olrka%/.).-&yyNFAy5/51y
@Ab^aivAbpboqSbkljyKyDbq5XPqlkbi^peP`lomfaPqfkdbopZaolmmba_vPqlkbi^peP`lomfap^ka5XP^kaPhfqqboboC^kdpZaolmmba_vP^kaPhfqqbobop+?lqe^obclrkakloqe*b^pqlc`bk^oflkelia^olrka%24)/4&yyNFAy5/44y
@Pb`rofkdqebPrmmivIfkbpyKyHfii.2AobadbPqofhbopclrkakloqe*b^pqlc`bk^oflkelia^olrka%23)/5&yyNFAy5/5-y

E@bk^oflkEliayRy3615yyNFAy5/45y
QAb^aivAbpboqSbkljyKy?bbqfuCf`hibpmo^dd%2.+4)05+3&yyNFAy5/44y
>Klddib$pI^pqElmbyKy?bbqfuCf`hibpmo^dd%2.+4)05+3&yyNFAy5/45y
QPb`rofkdqebPrmmivIfkbpyKyTfka`^iiboMolraelok%2.+.)05+/&yyNFAy5/5-y
>PqbmmfkdRmPb`rofqvyKyTfka`^iiboMolraelok%2.+.)05+/&yyNFAy5/5.y
QQebQtfifdeqJvpqbovyKyDblildfpqI^ohp_^kb%16+4)04+0&yyNFAy5/51y
>QebAbpboqboyKyDblildfpqI^ohp_^kb%16+4)04+0&yyNFAy5/52y

QT^pqbi^kayKyI^vlPq^opqofhb%5.+5).5+5&yyNFAy../1y
>QebPmfofqplcPlrqetfkayKyI^vlPq^opqofhb%5.+5).5+5&yyNFAy../2y
@QebPmfofqplcPlrqetfkayKyQo^sbifkqlPlrqetfkaSfii^db^q%3.)2.&^kahfii5b^`elcqebQloqrobaAorfap^kaPbkqfkbipyyNFAy../2y
QQebAbpboqboyKyEbojfqLoqbii%34+.)36+4&yyNFAy5/52y
>QebQtfifdeqIbuf`lkyKyEbojfqLoqbii%34+.)36+4&yyNFAy5/46y
@Klddib$pI^pqElmbyKyDbq0XPqlkbi^peMfk`boPqfkdbopZ)0XPqlkbi^peCi^vboPqfkdbopZ^ka0XOl`hPq^ihboC^kdpZ^olrka%15)35&yyNFAy5/45y
@PqbmmfkdRmPb`rofqvyKyHfii/-Aobadb@orpebopclrkaPlrqetbpq^olrka%06)21&yyNFAy5/5.y

E@bk^oflkEliayKyLoab^qemloqyyRy3615yyNFAy5/5/y
QKlddib$pI^pqElmbyKy?bbqfuCf`hibpmo^dd%2.+4)05+3&yyNFAy5/45y
>Klddib$pIlpqP^q`ebiyKyKlddibCf`hibpmo^dd%2.+4)05+3&yyNFAy5/5/y
QPqbmmfkdRmPb`rofqvyKyTfka`^iiboMolraelok%2.+.)05+/&yyNFAy5/5.y

HQtfifdeqHbbmboJ^vk^yKyC^otbpq^qqebQtfifdeqMlpq%/4)02&+M^qolip^ilkdqebb^pqpfab+Mriiebo_^`hplvlralk$qdbqifkhpfcpebcb^opyyIy/-061yyNFAy5/46y
HQtfifdeqHbbmboE^srkqeyKyB^pq^qQtfifdeq?^pb@^jm%1-)1/&+M^qolip^ilkdqebkloqeb^pqpfabyyIy/-063yyNFAy5/46y
@Klddib$pIlpqP^q`ebiyKyCfka^ka`liib`qXKlddib$pP^q`ebiZ^q%11+3)6.+0&+?b`^obcrilcAb^qe`i^pm^kbifqbjl_tfqeqtldr^oapyyNFAy5/5/y
HQtfifdeqHbbmboBubqboyKyPlrqetbpqpfablcQtfifdeqLrqmlpq%.3)54&+Cliiltqebjlrkq^fkp^ilkdqebplrqebadblcqeb`^jmql^slfa^ddolyyIy/-062yyNFAy5/46y

QQebQtfifdeqIbuf`lkyKyEbojfqLoqbii%34+.)36+4&yyNFAy5/46y
>>Qboof_ibMromlpbyKyEbojfqLoqbii%34+.)36+4&yyNFAy5/54y

QQebPmfofqplcPlrqetfkayKyI^vlPq^opqofhb%5.+5).5+5&yyNFAy../2y
>EfsbfkqebQltboyKyI^vlPq^opqofhb%5.+5).5+5&yyNFAy../3y
@EfsbfkqebQltboyKyLmbk^kaillqqebdllcoljqebqebmlalkqlmlcqebqltbo^q%3-)20&)tef`etfii`ob^qbqtlpm^tkp)te`fejrpq_bhfiibaqldbqebotfqefk.-pb`lkaplcb^`elqebo+Pliltboqebeb^iqelclkbqebkhfiiqeblqeboqebkqebcfopqlkbtfiiaolmqebXBk`orpqbaPfifqefaL_gb`qZyyNFAy../3y
QEfsbfkqebQltboyKyI^vlPq^opqofhb%5.+5).5+5&yyNFAy../3y
>Rj_bo)>o`efsfpqyKyI^vlPq^opqofhb%5.+5).5+5&yyNFAy3511y

E@bk^oflkEliayRy3615yyNFAy3512y
QKlddib$pIlpqP^q`ebiyKyKlddibCf`hibpmo^dd%2.+4)05+3&yyNFAy5/5/y
Q>Qboof_ibMromlpbyKy@ljj^kaboJ^o$^ifqe%16+/)01+0&yyNFAy5/54y

CJllkdi^abyKy@ilraPhva^k`bo%2-+3)01+2&yyNFAy3512y
QRj_bo)>o`efsfpqyKyRj_bo%11)05&yyWyJllkdi^abyyNFAy3511y
>Rk`lsbofkdM^pqPb`obqpyKyRj_bo%11)05&yyWyJllkdi^abyyNFAy3512y
QRk`lsbofkdM^pqPb`obqpyKyO^_fkbP^qrok^%2.+4)11+6&yyWyJllkdi^abyyNFAy3512y

CBsboillhyKyPfkao^vi%15+.)34+0&yyWyJllkdi^aby
Q>obTbQebob)Vbqf<%M^oq0&yKyRjfOrjmibpkf`hbo%3-+6)04+4&yyNFAy2.30yyWyTfkqbopmfkdy

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
