DugisGuideViewer:RegisterGuide("Eastern Plaguelands (57-58)", "Western Plaguelands (58)", "Alliance", "L", function()
return [[
AAA

OB^pqbokMi^drbi^kapyKyDlb^pq%46+4)2-+1&yyWyTbpqbokMi^drbi^kapyyNFAy221/y
>AbjlkAldpyKyQfoflkCloaofkd%1+4)05+2&yyNFAy221/y
>?illaQfkdbaPhfbpyKyQfoflkCloaofkd%1+4)05+2&yyNFAy2210y
>@^ooflkDor__^dbyKyQfoflkCloaofkd%1+4)05+2&yyNFAy2211y

KHfii^pvlrnrbpq+++yKyHfii^kvmi^drbelrkap)`^ooflktlojp)^kami^drb_^qpvlrbk`lrkqbofkBMIclob^`eobpmb`qfsbnrbpqpyyNFAy3.52y
@QebB^pqbokMi^drbpyKyCfkaqebPF74Fkpfdkf^pcoljqebJ^kdibaErj^kObj^fkp+Orqdbofp^q%/2+..)40+.0&)Cobal%/0+20)35+13&^kaQrovbk%/2+./)35+02&yyNFAy3.52y

QPfpqboM^jbi^yKyM^jbi^Obam^qe%0/+2)50+5&yyNFAy23-.y
>M^jbi^$pAliiyKyM^jbi^Obam^qe%0/+2)50+5&yyNFAy2.16y
@M^jbi^$pAliiyKyCfkaqeobbm^oqptef`eo^kaljivpm^tkfkqebil`^qflkplc%06)6-&)%06)6/&^ka%05)6/&fkqebelrpbplcA^ooltpefob+Lkqebillqfkdlcqebpbl_gb`qp^jl_j^vpm^tktef`ee^rkqpqebaliiyyNFAy2.16y
QM^jbi^$pAliiyKyM^jbi^Obam^qe%0/+2)50+5&yyNFAy2.16y
>>rkqfbJ^oibkbyKyM^jbi^Obam^qe%0/+2)50+5&yyNFAy2.2/y
>Rk`ib@^oifkyKyM^jbi^Obam^qe%0/+2)50+5&yyNFAy2/1.y

HMi^drbelrkaOrkqpyNFAy221/yyNLyMi^drbelrkaOrkqpi^fk7/-,/-yyKy>iilsboqebplrqetbpqbokpb`qflklcqebwlkby
@?illaQfkdbaPhfbpyKyPi^v0-Mi^drb_^qppmob^aqeolrdelrqqebPlrqebokbkalcB^pqbokMi^drbi^kap^olrka%00)44&yyNFAy2210y

QRk`ib@^oifkyKy@^oifkObam^qe%42+4)20+6&yyNFAy2/1.y
>AbcbkaboplcA^ooltpefobyKy@^oifkObam^qe%42+4)20+6&yyNFAy2/..y
QArhbKf`eli^pWsbobkelccyKyArhbKf`eli^pWsbobkelcc%42+3)20+6&yyNFAy3-0-y
>W^bia^ooqebLrq`^pqyKy@^obq^hbo>ibk%40+6)24+4&yyNFAy3-/.y

KCobbPmfofqp+++yKyHfii^kv`^kkf_^idelrip)df__bofkddelrip^kaafpb^pbaci^vbopvlr`ljb^`olpp+Pmb^hql^kvdelpqpqe^qpm^tkcloAbcbkaboplcA^ooltpefobyyNFAy2/..y
@AbjlkAldpyKyHfii/-Mi^drbelrkaOrkqp^olrka%00)44&)2Mi^drbelrkap^olrka%41)46&^ka2CobkwfbaMi^drbelrkap^olrka%2-)12&yyNFAy221/y
@>Mi^drbRmlkQebb%M^oq.&yKyQebQbojfqbJlrkap`^k_bclrkapmob^aqeolrdelrqMi^drbtlla+RpbqebXBjmqvQbojfqbG^oZql`liib`qqebpb+Bu^jmibil`^qflkp^ob%0/)00&^ka%/2)/3&yyNFAy26-0yyRy.2-1/y
@@^ooflkDor__^dbyKyDbq.2XPi^_plc@^ooflkTlojJb^qZaolmmba_v@^ooflkAbslrobop^olrka%25)0/&yyNFAy2211y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
