DugisGuideViewer:RegisterGuide("Western Plaguelands (58-59)", "Hellfire Peninsula (60-62)", "Alliance", "L", function()
return [[
AAA

CTbpqbokMi^drbi^kapyKyHe^bivkPqbbitfkd%42+5)20+2&yyWyB^pqbokMi^drbi^kapyyNFAy26-1y
Q>Mi^drbRmlkQebb%M^oq.&yKyK^qe^kfbiArj^e%10)52&yyNFAy26-0y
>>Mi^drbRmlkQebb%M^oq/&yKyK^qe^kfbiArj^e%10)52&yyNFAy26-1y
QPhbibq^iCo^djbkqpyKy>i`ebjfpq>o_fkdqlk%1/+4)50+5&yyNFAy2204y

>Rkcfkfpeba?rpfkbpp%M^oq.&yKyHfopq^Abbmpe^alt%2.+6)/5+.&yyNFAy3--1y

@>Mi^drbRmlkQebb%M^oq/&yKyMi^`bqeb`liib`qbaQbojfqbp^qqeb`o^qbfkqebIrj_bojfii^q%15)0.&yyNFAy26-1y
Q>Mi^drbRmlkQebb%M^oq/&yKyQbojfqb?^oobi%15+1)0.+6&yyNFAy26-1y
>>Mi^drbRmlkQebb%M^oq0&yKyQbojfqb?^oobi%15+1)0.+6&yyNFAy3056y
@Rkcfkfpeba?rpfkbpp%M^oq.&yKyHfii/P`^oibqJbaf`p)Erkqbop)^kaHkfdeqpclrka^olrkaqebIrj_boJfii%14)23&^ka/P`^oibqJ^db^qqebD^qbp^q%2/)06&yyNFAy3--1y
QRkcfkfpeba?rpfkbpp%M^oq.&yKyHfopq^Abbmpe^alt%2.+6)/5+.&yyNFAy3--1y
>Rkcfkfpeba?rpfkbpp%M^oq/&yKyHfopq^Abbmpe^alt%2.+6)/5+.&yyNFAy3-/0y

@Rkcfkfpeba?rpfkbpp%M^oq/&yNFAy3-/0yyKyHfiiErkqpj^kO^aibv^q%24)03&^ka@^s^ifboArodbk^q%22+.)/0+2&y
@QebJ^ohlcqebIfdeq_ofkdboyKyCfkaqebXJ^ohlcqebIfdeq_ofkdboZ`lkq^fkbafkqebEliv@lccbo^q%22+/)/0+1&yyNFAy6141y

QRkcfkfpeba?rpfkbpp%M^oq/&yKyHfopq^Abbmpe^alt%2.+6)/5+.&yyNFAy3-/0y
>Rkcfkfpeba?rpfkbpp%M^oq0&yKyHfopq^Abbmpe^alt%2.+6)/5+.&yyNFAy3-/2y
@Rkcfkfpeba?rpfkbpp%M^oq0&yNFAy3-/2yyKyBkqboEb^oqedibk^kaqo^sbiqlqebqltbo^q%12).5&+Qefpnrbpqfpb^pfivplil^_ib^kajlpqjl_p^ob^slfa^_iby
QRkcfkfpeba?rpfkbpp%M^oq0&yKyHfopq^Abbmpe^alt%2.+6)/5+.&yyNFAy3-/2y

QLcIlpqElkloyKyQfoflkCloaofkd%1+4)05+2&yyWyB^pqbokMi^drbi^kapyyNFAy2512y
>LcIlsb^kaC^jfiv%M^oq.&yKyQfoflkCloaofkd%1+4)05+2&yyWyB^pqbokMi^drbi^kapyyNFAy2513y
QLcIlsb^kaC^jfiv%M^oq.&yKy>oqfpqObkco^v%32+4)42+1&yyNFAy2513y

Q>Mi^drbRmlkQebb%M^oq0&yKyK^qe^kfbiArj^e%10)52&yyNFAy3056y
QQebJ^ohlcqebIfdeq_ofkdboyKy>k`elofqbQorrbk%10)5.&*jlsbp^olrkaqefp^ob^yyNFAy6141y
>Qlj_lcqebIfdeq_ofkdboyKy>k`elofqbQorrbk%10)5.&*jlsbp^olrkaqefp^ob^yyNFAy6113y
@Qlj_lcqebIfdeq_ofkdboyKyQefpfp^kb^pfivplil$abp`loqnrbpqtebobvlrjrpqp^cbqivbp`loq>k`elofqbQorrbk%10)5/&qlRqebo$pQlj_fkPlooltEfiiyyNFAy6113y
QQlj_lcqebIfdeq_ofkdboyKyEfdeMofbpqbppJ^`Alkkbii%1/+6)51+1&yyNFAy6113y

Q>obTbQebob)Vbqf<%M^oq0&yKyRjfOrjmibpkf`hbo%3-+6)04+4&yyWyTfkqbopmofkdyyNFAy2.30y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
