DugisGuideViewer:RegisterGuide("Eastern Plaguelands (58)", "Western Plaguelands (58-59)", "Alliance", "L", function()
return [[
AAA

QAbjlkAldpyKyQfoflkCloaofkd%1+4)05+2&yyNFAy221/y
Q?illaQfkdbaPhfbpyKyQfoflkCloaofkd%1+4)05+2&yyNFAy2210y
Q@^ooflkDor__^dbyKyQfoflkCloaofkd%1+4)05+2&yyNFAy2211y
>ObabjmqflkyKyQfoflkCloaofkd%1+4)05+2&yyNFAy241/y
@ObabjmqflkyKyIfpqbkqlte^qQfoflkCloaofkd%1+4)05+2&e^pqlp^vyyNFAy241/y
QObabjmqflkyKyQfoflkCloaofkd%1+4)05+2&yyNFAy241/y
>LcClodlqqbkJbjlofbpyKyQfoflkCloaofkd%1+4)05+2&yyNFAy245.y

@LcClodlqqbkJbjlofbpyKyXQ^bi^k$pE^jjboZfpaolmmba_vJbo`rqflCfiqedlodbotelm^qolip^olrka%/5)52&yyNFAy245.y
@W^bia^ooqebLrq`^pqyKyHfiiW^bia^ooqebLrq`^pqfkqebqlj_^q%/0+6)45+0&yyNFAy3-/.y

QLcClodlqqbkJbjlofbpyKyQfoflkCloaofkd%1+4)05+2&yyNFAy245.y
>LcIlpqElkloyKyQfoflkCloaofkd%1+4)05+2&yyNFAy2512y

Q?olqebo@^oifkyKy@^oifkObam^qe%42+4)20+6&yyNFAy2/.-y
>Sfii^fkplcA^ooltpefobyKy@^oifkObam^qe%42+4)20+6&yyNFAy2.5.y
QW^bia^ooqebLrq`^pqyKy@^obq^hbo>ibk%40+6)24+4&yyNFAy3-/.y

@Sfii^fkplcA^ooltpefobyKyCfkaqebXPhriilcElodrpZ^q%13+3)11+2&^kaqebXPe^qqbobaPtloalcJ^oarhZ^q%16+/)26+3&yyNFAy2.5.y
@LcIlpqElkloyKyQo^sbiqlKloqea^ib^ka`liib`qqebXPvj_lilcIlpqElkloZfkqebt^qbop^q%32+6)/5+6&yyNFAy2512y

QQolr_ibaPmfofqplcHbi$QebofiyKy>rolo^Phv`^iibo%15+6).4+3&yyNFAy2/12y
@AbcbkaboplcA^ooltpefobyKyVlr`^kcfkaqebdelrip^olrka7%06)2.&)%3-)35&)%5/)1.&)%35)1.&^ka%.3)0-&+Lk`bhfiiba^pmfofqtfiipm^tk)telvlrjrpqpmb^htfqeqlcobbfqyyNFAy2/..y

QAbcbkaboplcA^ooltpefobyKy@^oifkObam^qe%42+4)20+6&yyNFAy2/..y
QSfii^fkplcA^ooltpefobyKy@^oifkObam^qe%42+4)20+6&yyNFAy2.5.y

EPqlojtfka@fqvyRy3615y
QQeb?ifdeq`^iibo@ljbqeyKyHfkdS^of^kTovkk%46+6)05+3&yyWyPqlojtfka@fqvyyNFAy3.53y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)

