DugisGuideViewer:RegisterGuide("Western Plaguelands (58)", "Eastern Plaguelands (58)", "Alliance", "L", function()
return [[
AAA

C@efiitfkaMlfkqyKyHe^bivkPqbbitfkd%42+5)20+2&yyWyB^pqbokMi^drbi^kapyyNFAy3.53y
QQebB^pqbokMi^drbpyKyCifkqPe^altjlob%10+3)51+2&yyNFAy3.52y
>Qeb?ifdeq`^iibo@ljbqeyKyCifkqPe^altjlob%10+3)51+2&yyNFAy3.53y

Q>rkqfbJ^oibkbyKyJ^oibkbObam^qe%16+/)45+2&yyNFAy2.2/y
>>Pqo^kdbEfpqlof^kyKyJ^oibkbObam^qe%16+/)45+2&yyNFAy2.20y
@>Pqo^kdbEfpqlof^kyKyDo^sbpqlkbgrpqkloqelcqebelrpb%16+3)43+4&yyNFAy2.20y
Q>Pqo^kdbEfpqlof^kyKy@eoljfb%06+1)33+5&yyNFAy2.20y
>Qeb>kk^iplcA^ooltpefobyKy@eoljfb%06+1)33+5&yyNFAy2.21y
>>J^qqbolcQfjbyKy@eoljfb%06+1)33+5&yyNFAy164.y

@>J^qqbolcQfjbyKyCfkaqeb_irbdiltvpfilp^olrkaqebbadbplc>kaloe^i%12+-2)3/+40&+RpbqebXQbjmlo^iAfpmi^`boZyyRy./3/4yyNFAy164.y
@Qeb>kk^iplcA^ooltpefobyKyFkqebqltke^ii%10+6.)36+//&+Illq_llhpqfiivlrcfkaX>kk^iplcA^ooltpefobZyyNFAy2.21y

Q>J^qqbolcQfjbyKy@eoljfb%06+1)33+5&yyNFAy164.y
>@lrkqfkdLrqQfjbyKy@eoljfb%06+1)33+5&yyNFAy1640y
QQeb>kk^iplcA^ooltpefobyKy@eoljfb%06+1)33+5&yyNFAy2.21y
>?olqebo@^oifkyKy@eoljfb%06+1)33+5&yyNFAy2/.-y

@@lrkqfkdLrqQfjbyKyDbq2X>kaloe^iT^q`ebpZclrkafkil`h_lubpfkqebelrpbp^ii^olrka>kaloe^i%1.)4-&yyNFAy1640y
@Phbibq^iCo^djbkqpyKyHfiirkab^a^iilsbo>kaloe^i%1.)4-&yyNFAy2204y

Q@lrkqfkdLrqQfjbyKy@eoljfb%06+1)33+5&yyNFAy1640y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
