DugisGuideViewer:RegisterGuide("Hellfire Peninsula (60-62)", "Zangarmarsh (61-64)", "Alliance", "L", function()
return [[
AAA

CKbqebod^oabHbbmyKyFk?i^pqbaI^kayyNFAy.-..6y
?XKbqebod^oab?fqqboZyKyColj?bokfbEbfpqbk%30+2/).3+62&yyIy/0515yyWy?i^pqbaI^kapyyNFAy.-..6y

>QeolrdeqebA^ohMloq^iyKyT^q`e@ljj^kaboObiqelokKbqebot^kb%25+1)22+5&yyWy?i^pqbaI^kapyyNFAy.-..6y

OEbiicfobMbkfkpri^yKyDlqeolrdeqebmloq^i%25+2)26+5&yyWy?i^pqbaI^kapyyNFAy.-/55y
QQeolrdeqebA^ohMloq^iyKy@ljj^kaboArolk%54+1)2-+4&yyNFAy.-..6y
>>oofs^ifkLrqi^kayKy@ljj^kaboArolk%54+1)2-+4&yyNFAy.-/55y
Q>oofs^ifkLrqi^kayKy>jfpeTfiae^jjbo%54+1)2/+1&yyNFAy.-/55y
>GlrokbvqlElkloEliayKy>jfpeTfiae^jjbo%54+1)2/+1&yyNFAy.-.1-y

CElkloEliayKy>jfpeTfiae^jjbo%54+1)2/+1&yyNFAy.-/21y
QGlrokbvqlElkloEliayKyJ^ope^iFpfialo%21+2)3/+4&yyNFAy.-.1-y
>Clo`b@ljj^kaboA^k^qeyKyJ^ope^iFpfialo%21+2)3/+4&yyNFAy.-/21y
eElkloEliayKyPfaIfj_^oaf%21+0)30+3&yyNFAy.-.1.y
QClo`b@ljj^kaboA^k^qeyKyClo`b@ljj^kaboA^k^qeQolii_^kb%23+3)33+3&yyNFAy.-/21y
>QebIbdflkOb_lokyKyClo`b@ljj^kaboA^k^qeQolii_^kb%23+3)33+3&yyNFAy.-.1.y
>HkltvlroBkbjvyKyClo`b@ljj^kaboA^k^qeQolii_^kb%23+3)33+3&yyNFAy.-.3-y

QHkltvlroBkbjvyKyIfbrqbk^kq>j^af%2.)3-+/&yyNFAy.-.3-y
>CbiLo`P`^sbkdbopyKyIfbrqbk^kq>j^af%2.)3-+/&yyNFAy.-15/y
>T^pqbKlq)T^kqKlqyKyArjmeov%2.+0)3-+/&yyNFAy.--22y

QQebIbdflkOb_lokyKyPbodb^kq>iqrjrp%3.+4)3-+5&yyNFAy.-.1.y
>QebM^qelc>kdrfpeyKyPbodb^kq>iqrjrp%3.+4)3-+5&yyNFAy.-.1/y

@T^pqbKlq)T^kqKlqyKyDbq5mfb`bplcXP^is^dbaJbq^iZ^ka5mfb`bplcXP^is^dbaTllaZaolmmba_v?lkb`ebtboBslhbop^kaP`^sbkdbop^olrka%3.)2-&yyNFAy.--22y
@CbiLo`P`^sbkdbopyKyHfii/-?lkb`ebtboLo`p^olrka%3-)21&+Vlralk$qe^sbqlillhclo_lkb`ebtboLO@P^kvlo`plcqeb_lkb`ebtbo`i^ktfiitloh%f+b+pe^j^kp)t^ooflopbq`&yyNFAy.-15/y
@QebM^qelc>kdrfpeyKyHfii1Ci^jbt^hboFjmp)3Fkcbok^iT^o_ofkdbop^ka.Aob^a`^iibo^olrka%33)26&yyNFAy.-.1/y

QQebM^qelc>kdrfpeyKyPbodb^kq>iqrjrp%3.+4)3-+5&yyNFAy.-.1/y
>BumbafqflkMlfkqyKyPbodb^kq>iqrjrp%3.+4)3-+5&yyNFAy.-.10y
QBumbafqflkMlfkqyKyClot^oa@ljj^kaboHfkdpqlk%4.+1)3/+4&yyNFAy.-.10y
>AfpormqQebfoObfkclo`bjbkqpyKyClot^oa@ljj^kaboHfkdpqlk%4.+1)3/+4&yyNFAy.-.11y
@AfpormqQebfoObfkclo`bjbkqpyKyHfiijl_p^olrkaMloq^iDofje%4.)22&^kaMloq^iH^^ibw%40)25&^kadbq1Abjlkf`OrkbPqlkbpclob^`emloq^iyyNFAy.-.11y
QAfpormqQebfoObfkclo`bjbkqpyKyClot^oa@ljj^kaboHfkdpqlk%4.+1)3/+4&yyNFAy.-.11y
>Jfppflk7QebJrohbqe^kaPe^^ao^wD^qbt^vpyKyClot^oa@ljj^kaboHfkdpqlk%4.+1)3/+4&yyNFAy.-.13y
@Jfppflk7QebJrohbqe^kaPe^^ao^wD^qbt^vpyKyPmb^htfqeTfkd@ljj^kaboA^_fo$bb%4.+1)3/+2&)qebk_lj_D^qbt^vJrohbqe%42)12&^kaD^qbt^vPe^^ao^w%42)2.&yyRy/5-05yyNFAy.-.13y
QJfppflk7QebJrohbqe^kaPe^^ao^wD^qbt^vpyKyClot^oa@ljj^kaboHfkdpqlk%4.+1)3/+4&yyNFAy.-.13y
>Pe^qqboMlfkqyKyClot^oa@ljj^kaboHfkdpqlk%4.+1)3/+4&yyNFAy.-01-y

CPe^qqboMlfkqyKyQ^ihqlTfkd@ljj^kaboA^_fo$bb%4.+1)3/+2&yyNFAy.-011y
QPe^qqboMlfkqyKyOrkbqldTfiae^jjbo%45+2)02&yyNFAy.-01-y
>Tfkd@ljj^kaboDovmelkd^oyKyOrkbqldTfiae^jjbo%45+2)02&yyNFAy.-011y
QTfkd@ljj^kaboDovmelkd^oyKyTfkd@ljj^kaboDovmelkd^o%46+0)00+6&yyNFAy.-011y
>Jfppflk7Qeb>_vpp^iPebicyKyTfkd@ljj^kaboDovmelkd^o%46+0)00+6&yyNFAy.-.30y

@Jfppflk7Qeb>_vpp^iPebicyKyQ^ihqlDovmelkbboTfka_biilt%45+/2)01+1&^kae^sbebopbkavlrqlqeb>_vpp^iPebic^karpbX>ob^2/Pmb`f^iZqlabpqolv/-D^k$^odMblkp)2Jl$^odLsbopbbop^ka2Cbi@^kklkp^olrka%4/).6&yyRy/5.0/yyNFAy.-.30y
QJfppflk7Qeb>_vpp^iPebicyKyTfkd@ljj^kaboDovmelkd^o%46+0)00+6&yyNFAy.-.30y
>DlqlqebColkqyKyTfkd@ljj^kaboDovmelkd^o%46+0)00+6&yyNFAy.-05/y

QDlqlqebColkqyKyFkloaboqlqrokfkqebnrbpq)vlrjrpqq^ihqlDovmelkbboTfka_biilt%45+/2)01+1&^kae^sbebopbkavlrqlElkloMlfkq^kaqrokfkqlCfbiaJ^ope^i?ol`h%35+0)/5+2&yyNFAy.-05/y
>Afpormqflk*Clodb@^jm7J^dbaalkyKyCfbiaJ^ope^i?ol`h%35+0)/5+2&yyNFAy.-061y
@Afpormqflk*Clodb@^jm7J^dbaalkyKyEb^atbpqqlClodb@^jm7J^dbaalk%31)0/&^kahfiiqebobnrfobajl_p+O^wlop^ttfii_bm^qoliifkdqeb^ob^yyNFAy.-061y
QAfpormqflk*Clodb@^jm7J^dbaalkyKyCfbiaJ^ope^i?ol`h%35+0)/5+2&yyNFAy.-061y
>BkbjvlcjvBkbjv+++yKyCfbiaJ^ope^i?ol`h%35+0)/5+2&yyNFAy.-063y
@BkbjvlcjvBkbjv+++yKyEb^acroqebotbpqm^pqClodb@^jm7J^dbaalkqlClodb@^jm7O^db%26)0/&^kaabpqolv0Cbi@^kklkJHFyyNFAy.-063y
QBkbjvlcjvBkbjv+++yKyCfbiaJ^ope^i?ol`h%35+0)/5+2&yyNFAy.-063y
>Fks^pflkMlfkq7>kkfefi^qloyKyCfbiaJ^ope^i?ol`h%35+0)/5+2&yyNFAy.-064y
HT^o_ofkdbo>ofu$>j^iyKyHfiiT^o_ofkdbo>ofu$>j^i%20)/4&^ka`liib`qqebd^qbhbvyyIy/6462yyNFAy.-062y
>QebA^ohJfppfsbyKyRpbX?rokfkdIbdflkJfppfsbZql_bdfknrbpqvlrpelriadbqqefpfqbjcoljT^o_ofkdbo>ofu$>j^i%20)/4&yyRy/6255yyNFAy.-062y
@Fks^pflkMlfkq7>kkfefi^qloyKyDlqlqebOrkblcPmfqb%20)/4&qlabpqolvqebd^qbyyNFAy.-064y
QFks^pflkMlfkq7>kkfefi^qloyKyCfbiaJ^ope^i?ol`h%35+0)/5+2&yyNFAy.-064y

>Lrqi^kaPr`hpyKyClobj^kO^wbi`o^w%2.+0)0-+3&yyNFAy.-/03y
@Lrqi^kaPr`hpyKyQo^sbiqlqebO^sfkb%15+1)1-&il`^qbaplrqetbpqcoljClobj^kO^wbi`o^w^kalmbkqeb_lubpproolrkafkdqeb^ob^ql`liib`q3XPeobaaboPm^obM^oqpZyyNFAy.-/03y
QLrqi^kaPr`hpyKyClobj^kO^wbi`o^w%2.+0)0-+3&yyNFAy.-/03y
>EltqlPbosbDl_ifkpyKyClobj^kO^wbi`o^w%2.+0)0-+3&yyNFAy.-/05y
@EltqlPbosbDl_ifkpyKyCobbb^`elcClobj^kO^wbi`o^wmblk$p+J^kkffpil`^qba^q%12)1.&Jle^q%13+2)12+.2&^kaG^hh^q%14+2)13+22&yyNFAy.-/05y
QEltqlPbosbDl_ifkpyKyClobj^kO^wbi`o^w%2.+0)0-+3&yyNFAy.-/05y
>PefwwTlohyKyClobj^kO^wbi`o^w%2.+0)0-+3&yyNFAy.-3/6y
@PefwwTlohyKyRpbqebXCbielrkaTefpqibZ_bpfabClobj^kO^wbi`o^wqlprjjlk^CbiDr^oaElrkaqebkhfiiqebkb^o_vAbo^kdbaEbi_l^op^kat^fqcloqebelrkaqlb^q^kaj^hbpljbaolmmfkdptef`evlrjrpqpb^o`eqeolrde+@lkqfkrbqlalqefprkqfivlrob`fbsbqebXPeobaaboHbvpZyyRy0-5-0yyNFAy.-3/6y
QPefwwTlohyKyClobj^kO^wbi`o^w%2.+0)0-+3&yyNFAy.-3/6y
>?bkb^qeQeo^iij^oyKyClobj^kO^wbi`o^w%2.+0)0-+3&yyNFAy.-30-y
@?bkb^qeQeo^iij^oyKyQo^sbiplrqeb^pqfkpfabqeb`^sbrkqfivlrcfka^kahfiiRod^$ww%20+6)0.+3&yyNFAy.-30-y
Q?bkb^qeQeo^iij^oyKyClobj^kO^wbi`o^w%2.+0)0-+3&yyNFAy.-30-y

EElkloEliayRy3615yyNFAy.--25y
>>kLiaDfcqyKyC^qeboJ^idloAbsfaf`rp%21+0)30+3&yyNFAy.--25y
QQebA^ohJfppfsbyKyT^om*P`ovboHovs%23+3)33+3&yyNFAy.-062y
>QebM^qelcDilovyKyT^om*P`ovboHovs%23+3)33+2&yyNFAy.--14y
>QebEb^oqlcA^ohkbppyKyT^om*P`ovboHovs%23+3)33+3&yyNFAy.-066y
>LsboiloayKyClo`b@ljj^kaboA^k^qeQolii_^kb%23+3)33+3&yyNFAy.-1--y
QCbiLo`P`^sbkdbopyKyIfbrqbk^kq>j^af%2.)3-+/&yyNFAy.-15/y
>FiiLjbkpyKyIfbrqbk^kq>j^af%2.)3-+/&yyNFAy.-150y
>RkvfbiafkdPlripyKyElkloDr^oaTbpfilt%2-+6)3-+0&yyNFAy.--2-y
QT^pqbKlq)T^kqKlqyKyArjmeov%2.+0)3-+/&yyNFAy.--22y
>I^vfkdT^pqbqlqebRkt^kqbayKyArjmeov%2.+0)3-+/&yyNFAy.--45y

@QebM^qelcDilovyKy@ib^kpb5Qo^jmibaPhbibqlkp%31+6)2-&lkqebM^qelcDilovtfqeAo^bkbfElivT^qboyyNFAy.--14y
@I^vfkdT^pqbqlqebRkt^kqbayKyRpbqebXCi^jfkdQlo`eZql_rokqebEloab?i^abQeoltbop+@bkqo^ib^pqbokqeoltbo%23)13&)B^pqbokqeoltbo%26)14&)@bkqo^itbpqbokqeoltbo%21)15&^kaTbpqbokqeoltbo%20)15&yyRy/3--/yyNFAy.--45y
QQebM^qelcDilovyKyT^om*P`ovboHovs%23+3)33+2&yyNFAy.--14y
>QebQbjmiblcQbie^j^qyKyT^om*P`ovboHovs%23+3)33+2&yyNFAy.--60y
QI^vfkdT^pqbqlqebRkt^kqbayKyArjmeov%2.+0)3-+/&yyNFAy.--45y

@RkvfbiafkdPlripyKyAbcb^q./RkvfbiafkdCllqjbk).-RkvfbiafkdPlo`bobop)^ka2RkvfbiafkdHkfdeqp^qqebBumbafqflk>ojlov^olrka%22)42&yyNFAy.--2-y
@>kLiaDfcqyKyObqofbsbJvpqbofbplcqebIfdeq%21+6)53+5&yyNFAy.--25y
Q>kLiaDfcqyKyC^qeboJ^idloAbsfaf`rp%21+0)30+3&yyNFAy.--25y
QRkvfbiafkdPlripyKyElkloDr^oaTbpfilt%2-+6)3-+0&yyNFAy.--2-y
>IllhfkdqlqebIb^abopefmyKyElkloDr^oaTbpfilt%2-+6)3-+0&yyNFAy.--24y

>>Gl_clo^kFkqbiifdbkqJ^kyNFAy6022yyKyClobj^k?fddrjp%2/)3/+2&y
>TebkQefpJfkb$p^*Ol`hfk$yKyClobj^k?fddrjp%2/)3/+2&yyNFAy.--46y
@TebkQefpJfkb$p^*Ol`hfk$yKyHfii./D^k$^odP^mmbopfkqebjfkb^q%2/)3/&yyNFAy.--46y
QTebkQefpJfkb$p^*Ol`hfk$yKyClobj^k?fddrjp%2/)3/+2&yyNFAy.--46y
>QebJ^pqbojfkayKyClobj^k?fddrjp%2/)3/+2&yyNFAy.--66y
@QebJ^pqbojfkayKyHfiiW$ho^i%23+/)3.+2&fkqebjfkbp_bkb^qeElkloEliayyNFAy.--66y
QQebJ^pqbojfkayKyClobj^k?fddrjp%2/)3/+2&yyNFAy.--66y

@>Gl_clo^kFkqbiifdbkqJ^kyKyHfii.2J^o^rafkd@orpq?ropqbop^olrka%13)31&yyNFAy6022y
Q>Gl_clo^kFkqbiifdbkqJ^kyKyClobj^k?fddrjp%2/)3/+2&yyNFAy6022y

>O^s^dboBddOlrkarmyKyIbd^ppf%16+/)41+5&yyNFAy6016y
>Fk@^pblcBjbodbk`v+++yKyP`ob^jfkdP`obbaIr`hebba%16+.)41+5&yyNFAy.-.3.y
@Fk@^pblcBjbodbk`v+++yKy@liib`q0-mfb`bplcXWbmmbifkAb_ofpZ^olrka%3-)4-&yyNFAy.-.3.y
QFk@^pblcBjbodbk`v+++yKyP`ob^jfkdP`obbaIr`hebba%16+.)41+5&yyNFAy.-.3.y

@IllhfkdqlqebIb^abopefmyKyHfii>o`eJ^dbUfkqlo%20)5.&^kaIfbrqbk^kq@ljj^kaboQe^islp%21+5)50+3&fkqebBumbafqflk>ojlovyyNFAy.--24y
@FiiLjbkpyKyDbq.X@ropbaQ^ifpj^kZaolmmbacoljlo`pfkWbqe$dlo^olrka%34)42&yyNFAy.-150y

QFiiLjbkpyKy@lomlo^iFolkofadb%4.)30+2&yyNFAy.-150y
>@ropbaQ^ifpj^kpyKy@lomlo^iFolkofadb%4.)30+2&yyNFAy.-151y
>Wbqe$DloJrpq?rokyNFAy.-562yyKyTfkd@ljj^kaboA^_fo$bb%4.+1)3/+2&y
KKloqebokQltboyNFAy.-562yyNLyKloqebokQltboJ^ohba7.,.yyRy0.406yyKyQlqebplrqetbpqfkcolkqlcWbqe$Dlo%35)34&y
KClodbQltboyNFAy.-562yyNLyClodbQltboJ^ohba7.,.yyRy0.406yyKy%4-)36&y
KCllqefiiQltboyNFAy.-562yyNLyCllqefiiQltboJ^ohba7.,.yyKyLkqebefii^_lsbqebclodb%4-+62)4.+./&yyRy0.406y
@Wbqe$DloJrpq?rokyKyRpbqebXPjlhb?b^`lkZ^qPlrqebokQltbo%33+12)43+2&yyRy0.406yyNFAy.-562y
@@ropbaQ^ifpj^kpyKyDbq./X@ropbaQ^ifpj^kpZaolmmbacoljlo`pfkWbqe$dlo^olrka%34)42&yyNFAy.-151y
Q@ropbaQ^ifpj^kpyKy@lomlo^iFolkofadb%4.)30+2&yyNFAy.-151y
QWbqe$DloJrpq?rokyKyTfkd@ljj^kaboA^_fo$bb%4.+1)3/+2&yyNFAy.-562y
>T^oiloalcqeb?ibbafkdEliiltyKy@lomlo^iFolkofadb%4.)30+2&yyNFAy.-152y
@T^oiloalcqeb?ibbafkdEliiltyKyDbqXJlohe$pPe^qqboba>ojloZaolmmba_vT^oiloaJlohe%4-)44&+Qebbkqo^k`blcqeb_rfiafkdfp^q%36)42&yyNFAy.-152y
QT^oiloalcqeb?ibbafkdEliiltyKy@lomlo^iFolkofadb%4.)30+2&yyNFAy.-152y
>ObqrokqlElkloEliayKy@lomlo^iFolkofadb%4.)30+2&yyNFAy.-6-0y

OElkloEliayKyloEb^oqeyyNFAy.-6-6y
QObqrokqlElkloEliayKy>ppfpq^kqHi^qr%21+/)30+3&yyNFAy.-6-0y

>CbiPmfofqpyKy>ppfpq^kqHi^qr%21+/)30+3&yyNFAy.-6-6y
>AfddfkdcloMo^vbo?b^apyKy>ppfpq^kqHi^qr%21+/)30+3&yyNFAy.-6.3y
@AfddfkdcloMo^vbo?b^apyKyCfkaqebXAo^bkbfMo^vbo?b^apZ^qqeb_^`hlcqebfkk^q%21+.)30+0&fk^afoqmfibyyNFAy.-6.3y
QAfddfkdcloMo^vbo?b^apyKy>ppfpq^kqHi^qr%21+/)30+3&yyNFAy.-6.3y
QIllhfkdqlqebIb^abopefmyKyElkloDr^oaTbpfilt%2-+6)3-+0&yyNFAy.--24y

OQbjmiblcQbie^j^qyKyCliiltqebol^ab^pq)qebkq^hbqebclohkloqe%/0)1-&yyNFAy6050y
QQebQbjmiblcQbie^j^qyKy>j^^kqebTfpb%/0+1)03+3&yyNFAy.--60y
>>k>j_fqflrpMi^kyNFAy6050yyKyBip^^k^%/0+0)03+4&y
>FkPb^o`elcPba^fyKy>k`elofqbL_^abf%/0)1-+1&yyNFAy606-y
>@orbiQ^phj^pqbopyKyFh^k%/0+.)1-+0&yyNFAy6066y
>QebMlliplc>ddlk^oyKy>j^^kqebTfpb%/0+1)03+3&yyNFAy61/3y
eQbjmiblcQbie^j^qyKy@^obdfsboLmebo^Tfkacrov%/0+1)03+2&yyNFAy61/0y

QFkPb^o`elcPba^fyKyPba^f$p@lompb%/3+6)04+2&yyNFAy606-y
>ObqrokqlL_^abfyKyPba^f$p@lompb%/3+6)04+2&yyNFAy61/0y
@QebMlliplc>ddlk^oyKyPi^v3Qboolocfbkap^ka3?ifpqbofkdOlqp^olrka%1-)02&yyNFAy61/3y
@Eb^oqlcA^ohkbppyKyDlqlqebMlliplc>ddlk^o%0-)/0&^kahfii.-uQboolocfbkayyNFAy.-066y
KLsboiloafplmqflk^iyKyQefpnrbpq`^k_bafccf`riqqlplilabmbkafkdlkvlro`i^pp)b^pfivalkbtfqe/mi^vbop)Hfii>o^wwfrpqeb@orbi%10)0.&yyNFAy.-1--y

QQebMlliplc>ddlk^oyKy>j^^kqebTfpb%/0+1)03+3&yyNFAy61/3y
QObqrokqlL_^abfyKy>k`elofqbL_^abf%/0)1-+1&yyNFAy61/0y
>J^hror$pSbkdb^k`byKyJ^hror%/0+/)1-+/&yyNFAy61/1y
@J^hror$pSbkdb^k`byKyDbq.-XJ^d$e^o>k`bpqo^i?b^apZaolmmba_vdorkqp+Pq^oqvlrohfiifkd^q%0/)0/&qebkeb^armqebefiiyyNFAy61/1y
QJ^hror$pSbkdb^k`byKyJ^hror%/0+/)1-+/&yyNFAy61/1y

>>qlkbjbkqyKy>k`elofqbL_^abf%/0)1-+1&yyNFAy6210y
Q>qlkbjbkqyKy>j^^kqebTfpb%/0+1)03+3&yyNFAy6210y
>Pe^$k^^oObif`pyKy>j^^kqebTfpb%/0+1)03+3&yyNFAy610-y
>@ib^kpfkdqebT^qbopyKy>j^^kqebTfpb%/0+1)03+3&yyNFAy61/4y

@@ib^kpfkdqebT^qbopyKyRpbqebX@ib^kpfkdSf^iZ^q>ddlk^o$p`lompb%1-+.)0.yyRy/003.yyNFAy61/4y
Q@ib^kpfkdqebT^qbopyKy>j^^kqebTfpb%/0+1)03+3&yyNFAy61/4y

>Ab^aivMoba^qlopyKyP`lrqS^kro^%T^kabop^olrkaqltk&%/0)04&yyNFAy6065y
>QebOl`hCi^vboJ^qof^o`eyKyFh^k%/0+.)1-+0&yyNFAy616-y
@QebOl`hCi^vboJ^qof^o`eyKyVlrpelria_b^_ibqlplilqefpnrbpq)Qo^sbiqlqeb@^sb%01)30&fkqebDob^qCfpprob^kaeb^afkpfabqlhfii?i^`hq^ilk^kaillqefp`i^tyyNFAy616-y
@Ab^aivMoba^qlopyKyPi^v5Pqlkbp`vqebTebimp^ka1Pqlkbp`vqeb>ime^^olrka%00)3/&yyNFAy6065y
>JfppfkdJfppfsbyKyRpbXBolabaIb^qebo@^pbZ*aolmmba_vJ^o^rafkd@orpq?ropqbo^olrka%15)33&^ka%15)1-&yyRy/0005yyNFAy6040y

QJfppfkdJfppfsbyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy6040y
@@orbiQ^phj^pqbopyKyHfii1Fiifa^ofQ^phj^pqbopclrka^q@bk^oflkMlpq^olrka%.2)21&yyNFAy6066y
@Pe^$k^^oObif`pyKyObqofbsb.-XPe^$k^^oObif`pZaolmmba_vFiifa^ofQ^phj^pqbo^olrka%.0)3-&yyNFAy610-y
>K^i^aryKy>hlorqebCfob`^iibo%.2+3)25+4&yyNFAy.-1-0y
QK^i^aryKyK^i^ar%.3+/)32&yyNFAy.-1-0y
>>Qo^fqlo>jlkdRpyKyK^i^ar%.3+/)32&yyNFAy.-034y
@>Qo^fqlo>jlkdRpyKyDbqqebXPe^$k^^oHbvZfkpfabqeberq^q%.1+0)30+2&yyNFAy.-034y
Q>Qo^fqlo>jlkdRpyKyK^i^ar%.3+/)32&yyNFAy.-034y
>QebAobdellaBiabopyKyK^i^ar%.3+/)32&yyNFAy.-035y
@QebAobdellaBiabopyKyCobbJlolaqebTfkapqfoobo%.0+.)3.&)>hlorqebCfob`^iibo%.2+3)25+4&^ka>vi^^kqebT^qbot^hbo%.0)25+3&^qqebOrfkplcPe^$k^^oyyNFAy.-035y
QQebAobdellaBiabopyKyK^i^ar%.3+/)32&yyNFAy.-035y
>>owbqe$pAbjfpbyKyK^i^ar%.3+/)32&yyNFAy.-036y
@>owbqe$pAbjfpbyRy/62.0yyKyRpbqebXPq^cclcAobdellaBiabopZlk>owbqeqebJbo`fibpp%.0)26&^kahfiiefj^cqboeb$pilpqefpmltbopyyNFAy.-036y
Q>owbqe$pAbjfpbyKyK^i^ar%.3+/)32&yyNFAy.-036y

EQbjmiblcQbie^j^qyRy3615yyNFAy6212y
QPe^$k^^oObif`pyKy>j^^kqebTfpb%/0+1)03+3&yyNFAy610-y
QAb^aivMoba^qlopyKyP`lrqS^kro^%/0)04&yyNFAy6065y
Q@orbiQ^phj^pqbopyKyFh^k%/0+.)1-+0&yyNFAy6066y
QQebOl`hCi^vboJ^qof^o`eyKyFh^k%/0+.)1-+0&yyNFAy616-y
>QebPbbo$pObif`yKy>j^^kqebTfpb%/0+1)03+3&yyNFAy6212y
@QebPbbo$pObif`yKyDlqlPba^f$p`lompb%/3+6)04+2&^karpbXPbbo$pObif`ZlkfqyyRy/0312yyNFAy6212y
QQebPbbo$pObif`yKy>j^^kqebTfpb%/0+1)03+3&yyNFAy6212y
>Ebimfkdqeb@bk^oflkMlpqyKy>j^^kqebTfpb%/0+1)03+3&yyNFAy.-110y

@CbiPmfofqpyKyPi^vPe^qqbobaE^ka?bopbohbopkb^oqebX>k`elofqbObif`Z^kaqebkpi^v.-obib^pbaCbiPmfofqp+Dlo$d^wLrqmlpqfp^q%12)43&yyRy0.44/yyNFAy.-6-6y
@O^s^dboBddOlrkarmyKyHfiiO^sbkdbopqldbq./XO^s^dboBddpZplrqe*tbpqlcqeb`o^pebawbmmbifk^olrka%1/)52&yyNFAy6016y
QO^s^dboBddOlrkarmyKyIbd^ppf%16+/)41+5&yyNFAy6016y
>Ebi_l^o)qebLqeboTefqbJb^qyKyIbd^ppf%16+/)41+5&yyNFAy603.y
@Ebi_l^o)qebLqeboTefqbJb^qyKyHfiiqebAbo^kdbaEbi_l^op^q%0/)16&qldbq5XMrofcfbaEbi_l^oJb^qZ+RpbqebXMrofcf`^qflkJfuqrobZqlmrofcvqebjb^qyyRy/0/35yyNFAy603.y
QEbi_l^o)qebLqeboTefqbJb^qyKyIbd^ppf%16+/)41+5&yyNFAy603.y
>Pjllqe^p?rqqboyKyIbd^ppf%16+/)41+5&yyNFAy6023y
@Pjllqe^p?rqqboyKyHfiiqeb?rww^oaptef`eproolrkaqeb_lkbpclrka^qQebS^iibvlcqeb?lkbp%26)4-&yyNFAy6023y

QCbiPmfofqpyKy>ppfpq^kqHi^qr%21+/)30+3&yyNFAy.-6-6y
>QebBulo`fpjlc@lilkbiGribpyKy>ppfpq^kqHi^qr%21+/)30+3&yyNFAy.-602y
>QebIlkd_b^oapyKyPfaIfj_^oaf%21+0)30+3&yyNFAy6225y
@QebBulo`fpjlc@lilkbiGribpyKyPmb^htfqe>k`elofqb?^o^a^%21)30+2&+RpbqebXOfqr^iMo^vbo?b^apZqlebimtfqeqebofqr^i^kaqebkpmb^htfqe@lilkbiGribp%21)30+2&yyRy0.5/5yyNFAy.-602y
QQebBulo`fpjlc@lilkbiGribpyKy>ppfpq^kqHi^qr%21+/)30+3&yyNFAy.-602y
>Qolii_^kbfpIllhfkdcloVlryKy>ppfpq^kqHi^qr%21+/)30+3&yyNFAy.-603y
QQolii_^kbfpIllhfkdcloVlryKyClo`b@ljj^kaboA^k^qeQolii_^kb%23+3)33+3&yyNFAy.-603y
>AofiiqebAofiij^pqboyKyClo`b@ljj^kaboA^k^qeQolii_^kb%23+3)33+3&yyNFAy.-604y

QPjllqe^p?rqqboyKyIbd^ppf%16+/)41+5&yyNFAy6023y
>Slfat^ihbopDlkbTfiayKyP`ob^jfkdP`obbaIr`hebba%16+.)41+5&yyNFAy602.y
@>k>j_fqflrpMi^kyKyRpbqebXP^k`qfcfba@ovpq^iZ^d^fkpq^tlrkabaRk`lkqoliibaSlfat^ihbo^olrka%12)5.&+Qeb`ovpq^i`^klkiv_brpbatebkqebRk`lkqoliibaSlfat^ihboe^p^mmolufj^qbiv.2"lcfqpEMibcqyyRy/01.4yyNFAy6050y
@Slfat^ihbopDlkbTfiayKyDbq.-X@lkabkpbaSlfat^ihboBppbk`bpZaolmmba_vslfat^ihbop^olrka%15)5/&yyNFAy602.y

QSlfat^ihbopDlkbTfiayKyP`ob^jfkdP`obbaIr`hebba%16+.)41+5&yyNFAy602.y
KAofiiqebAofiij^pqbofplmqflk^iyKyHfiiAofiij^pqboWrolh%14+52)23+/2&telfp^3/Bifqb)lsbomltboba`i^ppbptfii_b^_ibqlplilfq)dolrmfkdrmtfqe^klqebomboplkfpob`ljjbkabayyNFAy.-604y
QAofiiqebAofiij^pqboyKyClo`b@ljj^kaboA^k^qeQolii_^kb%23+3)33+3&yyNFAy.-604y
EQbjmiblcQbie^j^qyRy3615yyNFAy61.4y
Q>k>j_fqflrpMi^kyNFAy6050yyKyBip^^k^%/0+0)03+4&y

QQebIlkd_b^oapyKyDobjkfIlkd_b^oa%/0+6)4/+.&yyNFAy6225y
>Qeb>o^hhl^Qeob^qyKyDobjkfIlkd_b^oa%/0+6)4/+.&yyNFAy61.4y
>O^jm^dfkdO^s^dbopyKyDobjkfIlkd_b^oa%/0+6)4/+.&yyNFAy6052y
>D^fkfkdJfoobk$pQorpqyKyJfoobkIlkd_b^oa%/1)4/+0&yyNFAy6230y
QD^fkfkdJfoobk$pQorpqyKyJfoobkIlkd_b^oa%/1)4/+0&yyNFAy6230y
>QebCfkbpqAltkyKyJfoobkIlkd_b^oa%/1)4/+0&yyNFAy61/-y

@QebCfkbpqAltkyKyDbq5XH^ifofCb^qebopZaolmmbalccltip^olrka%/2)43&yyNFAy61/-y
@Qeb>o^hhl^Qeob^qyKyHfii1E^^i$bpefTfkat^ihbop^ka3E^^i$bpefQ^ilkdr^oap^olrka%/2)41&yyNFAy61.4y
H>sorryIy/025-yyKyQlqebplrqeb^pqlcqebIlkd_b^oap%/2)43&+Ebm^qolip^olrkaqebibadb^_lsbqebjfaaiblcqebs^iibvyyNFAy61.5y
>>sorr$pLo_yKyX>sorr$pLo_Z*aolmmba_v>sorr%/2)43&yyRy/025-yyNFAy61.5y
@>sorr$pLo_yKyQ^hbX>sorr$pLo_ZqlqebE^^i$bpef>iq^o%/6)5.&plrqeb^pqlcqebAbklcE^^i$bpe+Tebk>bo^k^p%30Bibjbkq^i&pm^tkpvlre^sbqlcfdeqefjaltkql^_lrq0-"yyNFAy61.5y
Q>sorr$pLo_yKy>bo^k^p%/5+6)5.+1&yyNFAy61.5y
QQebCfkbpqAltkyKyJfoobkIlkd_b^oa%/1)4/+0&yyNFAy61/-y
QQeb>o^hhl^Qeob^qyKyDobjkfIlkd_b^oa%/0+6)4/+.&yyNFAy61.4y

@O^jm^dfkdO^s^dbopyKyHfii.-Nrfiic^kdO^s^dbop^olrka%//)32&yyNFAy6052y
QO^jm^dfkdO^s^dbopyKyDobjkfIlkd_b^oa%/0+6)4/+.&yyNFAy6052y

QEbimfkdqeb@bk^oflkMlpqyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy.-110y
>Qeb@bk^oflkBumbafqflkyKy>jvqefbiJfpqt^ihbo%.3)2/+/&yyNFAy66./y
>HbbmQelokc^kdEfii@ib^oyKyJ^ero^jPqlrqellc%.2+5)2/+0&yyNFAy.-.26y
>Abjlkf`@lkq^jfk^qflkyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy604/y
>@lilpp^iJbk^`byKyQli^$qeflk%.2+/)2/+.&yyNFAy.-.0/y
@Abjlkf`@lkq^jfk^qflkyKyDbq3XEbi_l^o?illaP^jmibpZcoljErihfkdEbi_l^op^olrka%/1)25&^ka%/3)1-&yyNFAy604/y
QAbjlkf`@lkq^jfk^qflkyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy604/y
>Qbpqfkdqeb>kqfalqbyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy.-/22y
@Qbpqfkdqeb>kqfalqbyKyRpbX@bk^oflk>kqfalqbZlk^Ebi_l^oil`^qba^olrka%/1)25&^ka%/3)1-&)qebkhfiifqyyRy/0004yyNFAy.-/22y
QQbpqfkdqeb>kqfalqbyKyQef^eObaj^kb%.2+4)2/+/&yyNFAy.-/22y
@@lilpp^iJbk^`byKyHfii2O^dfkd@lilpprp%.3)10&yyNFAy.-.0/y
>@ofjplk@ovpq^i@irbyKyHbbmhfiifkdO^dfkd@lilpprprkqfivlrcfkaX@ofjplk@ovpq^iPe^oaZqlpq^oqpnrbpq%.3)10&yyRy/6143yyNFAy.-.01y
Q@lilpp^iJbk^`byKyQli^$qeflk%.2+/)2/+.&yyNFAy.-.0/y
Q@ofjplk@ovpq^i@irbyKyQli^$qeflk%.2+3)2/+.&yyNFAy.-.01y
>QebB^oqe_fkaboyKyQli^$qeflk%.2+3)2/+.&yyIy.-016yyNFAy.-016y
QQebB^oqe_fkaboyKyB^oqe_fkaboD^i^kaof^Kfdeq_obbwb%.2+6)2.+3&yyNFAy.-016y
>K^qro^iObjbafbpyKyB^oqe_fkaboD^i^kaof^Kfdeq_obbwb%.2+6)2.+3&yyNFAy.-02.y
@K^qro^iObjbafbpyKyPfk`bm^q`e0+-+/qefpnrbpqe^p_bbkmobqqvb^pvqlplilclojlpq`i^ppbp)vlr`^kphfmqefpnrbpqfcvlr$obrk^_ibqlalfq^ilkb)`ib^oqeb^ob^^olrka%.0+32)06+.&qebkmi^kqqebXPbbalcObsfq^ifw^qflkZlkqeboba`fo`ib+Cl`rplkhfiifkdqeb_lpp)jlob^aaptfii^mmb^o_rqvlrtfii`ljmibqbqebnrbpq^pilkd^pvlrhfiiqeb_lppyyRy/6145yyNFAy.-02.y
QK^qro^iObjbafbpyKyB^oqe_fkaboD^i^kaof^Kfdeq_obbwb%.2+6)2.+3&yyNFAy.-02.y

@HbbmQelokc^kdEfii@ib^oyKyHfii5Qelokc^kdO^s^dbop^ka5Qelokc^kdSbkljpmfqqbop^olrka%6)2-&yyNFAy.-.26y
QHbbmQelokc^kdEfii@ib^oyKyJ^ero^jPqlrqellc%.2+5)2/+0&yyNFAy.-.26y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
