DugisGuideViewer:RegisterGuide("Zangarmarsh (61-64)", "Terokkar Forest (63-65)", "Alliance", "L", function()
return [[
AAA

O@bk^oflkObcrdbyKyDltbpqqeolrdeQelokc^kdO^sfkb%/+2)2-+2&yyWyEbiicfobMbkfkpri^yyNFAy6414y
>QebRj_o^cbkQof_byKyFhbvbk%5-+1)31+/&yyNFAy6414y
>QebAvfkd?^i^k`byKyIbqevkJllkcfob%45+3)30+.&yyNFAy6562y
e@bk^oflkObcrdbyKyFkkhbbmbo@lovqePqlhqolk%45+3)31&yyNFAy64.3y
QQeb@bk^oflkBumbafqflkyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy66./y
>Afpqro_^k`b^qRj_o^cbkI^hbyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64.3y
>T^oabkE^jllqyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy6445y
QT^oabkE^jllqyKyT^oabkE^jllq%46)32+0&yyNFAy6445y
>>T^ojTbi`ljbyKyT^oabkE^jllq%46)32+0&yyNFAy64/5y
>Ib^abolcqebA^oh`obpqyKyT^kqbaMlpqbo%46+.)31+5&yyNFAy640-y
>Ib^abolcqeb?illap`^ibyKyT^kqbaMlpqbo%46+.)31+5&yyNFAy65.4y

KHbbmmi^kqfqbjpyKyHbbm^kvXCboqfibPmlobpZ^kaXRkfabkqfcfbaMi^kqM^oqpZvlrcfka+Qrokqebmi^kqm^oqpfkqlqebkfdeqbicfkqebObcrdbbsbov`e^k`bvlrdbq)qebvlkivi^pqqfiielkloba+Fcvlrdbq^kvRk`^q^ildrbaPmb`fbpvlrpelriaelialkqlqebjrkqfi^cqbovlrob^`eelklobayyNFAy6562y
@QebRj_o^cbkQof_byKyHfiiH^q^or%52+0)6-+6&^qqebqlmlcqebqltbo+Hfii5Rj_o^cbkPbbop)3Rj_o^cbkTfq`eal`qlop^ka3Rj_o^cbkLo^`ibp^qRj_o^cbkSfii^db^olrka%50)50&yyNFAy6414y
>Bp`^mbcoljRj_o^cbkyKyH^vo^Ilkdj^kb%50)52&yyNFAy642/y
@QebAvfkd?^i^k`byKyCfka^kahfii?ldi^petelm^qolip^olrka%5/)4/&alqefptefibbp`loqfkdH^vo^^kapebtfiiebimvlrhfii?ldi^peyyNFAy6562y

QQebRj_o^cbkQof_byKyFhbvbk%5-+1)31+/&yyNFAy6414y
>>A^jm)A^ohMi^`byKyFhbvbk%5-+1)31+/&yyNFAy6455y
>P^sfkdqebPmlobilhpyKyI^ro^kk^Qe^o$tbii%5-+0)31+0&yyNFAy.--63y
>P^cbdr^oafkdqebT^q`ebopyKyTfka`^iibo?i^`hellc%5-+1)31+4&yyNFAy6561y
QQebAvfkd?^i^k`byKyIbqevkJllkcfob%45+3)30+.&yyNFAy6562y
QBp`^mbcoljRj_o^cbkyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy642/y

@Afpqro_^k`b^qRj_o^cbkI^hbyKyQo^sbiqlqebplrqe*tbpqm^oqlcRj_o^cbkI^hbtebobqebobfp^j^`efkbtfqemfmbp%4-)46&yyNFAy64.3y
@P^cbdr^oafkdqebT^q`ebopyKyHfiiIloaHi^n%4/+1)61&+Fq$pi^_biba^dolrmnrbpq)_rqHi^nfpplil^_ibyyNFAy6561y
@>A^jm)A^ohMi^`byKyPlrqelcRj_o^cbkI^hb%41)6.&XFhbvbk$p?bilkdfkdpZ%4-+3)64+6&`^k_bclrkalk^ol`hfkqeb_^`hlcqebCrkddlo@^sbok)yyNFAy6455y
@P^sfkdqebPmlobilhpyKyPi^v.-J^opeAobadbop^ka.-J^opeIrohbop)vlr`^khfiiilqplcqebpbjl_pfkqeb`^sb^q%41)6.&yyNFAy.--63y

E@bk^oflkObcrdbyRy3615yyNFAy64.5y
QAfpqro_^k`b^qRj_o^cbkI^hbyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64.3y
>>pqeb@oltCifbpyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64.5y
@>pqeb@oltCifbpyKyQebXPqloj`olt>jribqZtfiiqrokvlrfkql^`olt^kavlrtlk$q_b^_ibql`lkqolivlro`e^o^`qboarofkd^cifdeqclo/^ka^e^icjfkrqbp+KltlohobnrfobayyRy/2132yyNFAy64.5y
Q>pqeb@oltCifbpyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64.5y
>?^i^k`bJrpq?bMobpbosbayKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64/-y
QP^cbdr^oafkdqebT^q`ebopyKyTfka`^iibo?i^`hellc%5-+1)31+4&yyNFAy6561y
Q>A^jm)A^ohMi^`byKyFhbvbk%5-+1)31+/&yyNFAy6455y
QP^sfkdqebPmlobilhpyKyI^ro^kk^Qe^o$tbii%5-+0)31+0&yyNFAy.--63y

KAfp^_ibRj_o^cbkMrjmyKyRpbqebpbbap^qqeb`lkqolipqlqebRj_o^cbkI^hbmrjm%4-)5-&yyRy/1022yyNFAy64/-yyNLyRj_o^cbkI^hb@lkqolipAfp^_iba7.,.y
@Ib^abolcqebA^oh`obpqyKyCfka^kaHfiiO^g^eE^de^wba%32)35&^ibsbi30bifqb+Vlrpelria_b^_ibqlplilefjyyNFAy640-y
KAfp^_ibI^dllkMrjmyKyRpbqebpbbap^qqeb`lkqolipqlqebI^dllkmrjm%31)30&yyRy/1022yyNFAy64/-yyNLyI^dllk@lkqolipAfp^_iba7.,.y

OQbiobaloyKyKloqetbpqlcqebObcrdb)grpqcliiltqebol^a%34+6)2.+1&Qebbibs^qlofprmlkqebb^pqpfabyyNFAy645/y
>QebAb^aJfobyKySfkaf`^qloFa^^o%35+0)2-&yyNFAy645/y
>Qeb?le^$jrOrfkpyKy>k`elofqb>errok%35+0)16+1&yyNFAy6453y
>Rkcfkfpeba?rpfkbppyKyMolpmb`qlo@lk^ii%35+2)16+1&yyNFAy66-.y
>CridloPmlobpyKyOr^j%35+3)15+5&yyNFAy6444y
>Jbk^`fkdJ^opec^kdpyKyKlo^^kf%34+4)14+6&yyNFAy646.y
>QllJ^kvJlrqepqlCbbayKyE^^iork%34+5)15&yyNFAy645.y
cQbiobaloyKyJrk`f%34+6)2.+1&yyNFAy6563y
eQbiobaloyKy@^obdfsbo>_fa^^o%34+/)16+0&yyNFAy6563y

K@liib`qJrpeolljp^kahfiiOfmmbopyKyTefibkb^oQbiobalo)hbbm^kbvblrqcloXCridloPmlobpZ)_ofdeqdobbkjrpeolljp+>ipl)hfii^kvJ^opec^kdOfmmbopvlr`ljb^`olppyyNFAy6444y
@QebAb^aJfobyKyDbq^XAb^aJfobPlfiP^jmibZcolj^jlrkalcafoq^olrka%50)10&yyNFAy645/y
@Rkcfkfpeba?rpfkbppyKyHfiiPmlobtfkd%44)12&yyNFAy66-.y
@CridloPmlobpyKyDbq3XCridloPmlobpZ^olrka%4-)2-&)qebv$obdobbkifqqibjrpeolljpyyNFAy6444y
@Jbk^`fkdJ^opec^kdpyKyHfii.-J^opec^kdOfmmbopil`^qbajlpqivkloqe^kab^pqcoljbibs^qlo+Bu^jmibil`^qflk%4/)12&yyNFAy646.y

QCridloPmlobpyKyOr^j%35+3)15+5&yyNFAy6444y
QRkcfkfpeba?rpfkbppyKyMolpmb`qlo@lk^ii%35+2)16+1&yyNFAy66-.y
>?i^`hpqfkd$p?^kbyKyMolpmb`qlo@lk^ii%35+2)16+1&yyNFAy6563y
QQebAb^aJfobyKySfkaf`^qloFa^^o%35+0)2-&yyNFAy645/y
>>kRkk^qro^iAolrdeqyKySfkaf`^qloFa^^o%35+0)2-&yyNFAy6450y
QJbk^`fkdJ^opec^kdpyKyKlo^^kf%34+4)14+6&yyNFAy646.y

>Rj_o^cbkBbiCfibqpyKyKlo^^kf%34+4)14+6&yyNFAy645-y
@QllJ^kvJlrqepqlCbbayKyHfii.-JfobEvao^^olrkaqebbadbplcRj_o^cbkI^hb%45)33&yyRy/2206yyNFAy645.y
@Rj_o^cbkBbiCfibqpyKyDbq5XBbiCfibqpZaolmmba_vRj_o^cbkBbi^qRj_o^cbkI^hb%42)34&+RpbqebXMlqflklcT^qbo?ob^qefkdZ+Qebaolmo^qbfpilt^olrka0-"yyNFAy645-yyRy/2206y

>T^q`eboIbbp^$leyNFAy6364yyKyIbqevkJllkcfob%45+3)30+.&y
>?ibppfkdplcqeb>k`fbkqpyKyTfka`^iibo?i^`hellc%5-+1)31+4&yyNFAy6452y
@?ibppfkdplcqeb>k`fbkqpyKyDbq_ibppfkdpcoljqeb^k`fbkqp^q@bk^oflkObcrdb+>pevbkfp^q%5.+.)31&^kaHbibqefp^olrka%5-)31&yyNFAy6452y
Q?ibppfkdplcqeb>k`fbkqpyKyTfka`^iibo?i^`hellc%5-+1)31+4&yyNFAy6452y
@>kRkk^qro^iAolrdeqyKyHfii./TfqebobaDf^kqp^qqebab^ajfob^olrka%5-)05&yyNFAy6450y
>Tfqeboba?^pfafrjyRy/1150yyKyQebfqbjXTfqeboba?^pfafrjZpq^oqpnrbpq*aolmmba_vTfqebobaDf^kqp^qqebAb^aJfob^olrka%5-)05&yyNFAy65/4y
KP^sb?ldIloaQbkaofipyKyVlr$iikbbaqebji^qbocloobmrq^qflkyyNFAy6410y

Q>kRkk^qro^iAolrdeqyKySfkaf`^qloFa^^o%35+0)2-&yyNFAy6450y
QTfqeboba?^pfafrjyKyOr^j%35+3)15+5&yyNFAy65/4y
>TfqebobaCibpeyKyOr^j%35+3)15+5&yyNFAy.-022y
QRj_o^cbkBbiCfibqpyKyKlo^^kf%34+4)14+6&yyNFAy645-y
QQllJ^kvJlrqepqlCbbayKyE^^iork%34+5)15&yyNFAy645.y
>Af^me^klrpTfkdpyKyE^^iork%34+5)15&yyNFAy646-y
>QebLob_loE^o_lo^dbyNFAy6443yyKy>k`elofqb>errok%35+0)16+1&y

K@liib`q^kvXDilt`^mpZ^pvlrnrbpqyKyIllq^kvXDilt`^mpZvlrcfka)vlr$iikbbaqebjclonrbpqp^kaobmrq^qflkobt^oapyyNFAy65-5y
KAfp^_ibPbombkqI^hbMrjmyKyRpbqebpbbap^qqeb`lkqolipqlqebPbombkqI^hbmrjm%3.)1-&yyRy/1022yyNFAy64/-yyNLyPbombkqI^hb@lkqolipAfp^_iba7.,.y
@Ib^abolcqeb?illap`^ibyKyCfka^kaHfiiO^gfpCv^peb%32)1-&^30bifqb+Pebtfiiprjjlk1bibjbkq^ip`^k_b^_fqqlrdeyyNFAy65.4y
>Ao^fkP`ebj^qf`pyRy/100-yyKyQebfqbjXAo^fkP`ebj^qf`pZpq^oqpqefpnrbpq*aolmmba_vPqb^jMrjmLsbopbbop^ka?illap`^ibLsbopbbop^olrka%3/)1-&yyNFAy640.y
@?i^`hpqfkd$p?^kbyKyDbqX?i^`hpqfkd$pPqfkdboZcolj?i^`hpqfkd^q%16)26&yyNFAy6563y
@Qeb?le^$jrOrfkpyKyQo^sbiqlqeb?le^$jrOrfkpplrqelcCbo^icbkSfii^db%12)33&+Qebnrbpq`ljmibqbplk`bvlrbkqboqebqbjmib*ifhberqlkc^opfablcqeborfkpyyNFAy6453y

QT^q`eboIbbp^$leyKyT^q`eboIbbp^$le%/1)33&yyNFAy6364y
>L_pbosfkdqebPmlobifkdpyKyT^q`eboIbbp^$le%/1)33&yyNFAy64-.y

>QebPmlobifkdp$MifdeqyKyC^eppk%.6)30&yyNFAy6406y
>K^qro^iBkbjfbpyKyC^eppk%.6)30&yyNFAy6410y
@L_pbosfkdqebPmlobifkdpyKyPfjmivorkfkqlqebPm^tkfkdDibk%.2)3/&yyNFAy64-.y
@QebPmlobifkdp$MifdeqyKyDbq.-XJ^qrobPmlobP^`pZ^qqebPmt^kfkdDibk^olrka%.3)3-&yyNFAy6406y
@K^qro^iBkbjfbpyKyHfiiqeb?ldIloap^qqebPm^tkfkdDibk%.2)3-&loPq^osfkdCrkd^iDf^kq^olrka%.6)3/&clo3X?ldIloaQbkaofipZyyNFAy6410y
QQebPmlobifkdp$MifdeqyKyC^eppk%.6)30&yyNFAy6406y
QK^qro^iBkbjfbpyKyC^eppk%.6)30&yyNFAy6410y
>Pmlobdd^oyKyC^eppk%.6)30&yyNFAy66.6y
QPmlobdd^oyKyJppef$ck%.6+3)2/&yyNFAy66.6y
>Dilt`^mJrpeolljpyKyJppef$ck%.6+3)2/&yyNFAy65-5y
@Dilt`^mJrpeolljpyKyDbq.-XDilt`^mpZaolmmba_v>kdl$olpeLdob^olrka%00)0.&yyNFAy65-5y
QDilt`^mJrpeolljpyKyJppef$ck%.6+3)2/&yyNFAy65-5y
>CboqfibPmlobpyKyDpe^cc%.6+/)16+2&yyNFAy65-3y
@CboqfibPmlobpyKyVlrpelriae^sbbklrdedilt`^mp_vkltlqebotfpb)`liib`q3lcqebjyyNFAy65-3y
QCboqfibPmlobpyKyDpe^cc%.6+/)16+2&yyNFAy65-3y
KCofbkaiv*Pmlobdd^oyKy@ljmibqbbsbovobmb^q^_ibvlr`^krkqfivlr$obcofbkaiv+Vlr`^kqrokfkXDilt`^mpZ)X?ldIloaQbkaofipZ^kaXJ^qrobPmlobp^`pZ+>iiqebpbobmb^qpbkalk`bvlr$obcofbkaiv)plrpbqebjtefibvlr`^kyyNFAy64/3y
>KltQe^qTb$obCofbkap+++yKyDwerk$qq%.6+2)2-+.&yyNFAy64/3y

QL_pbosfkdqebPmlobifkdpyKyT^q`eboIbbp^$le%/1)33&yyNFAy64-.y
>>NrbpqflklcDirqqlkvyKyT^q`eboIbbp^$le%/1)33&yyNFAy64-/y
@>NrbpqflklcDirqqlkvyKy@liib`q.-mfb`bplcXAfp`^oabaKrqofjbkqZaolmmba_vCrkd^iDf^kqp^ka?ldIloap^olrka%/5)3/&yyNFAy64-/y
Q>NrbpqflklcDirqqlkvyKyT^q`eboIbbp^$le%/1)33&yyNFAy64-/y
>C^jfif^oCrkdfyKyT^q`eboIbbp^$le%/1)33&yyNFAy64-5y
KAfp^_ibJ^opeifdeqI^hbMrjmyKyRpbqebpbbap^qqeb`lkqolipqlqebJ^opeifdeqI^hbmrjm%/2)1/&yyRy/1022yyNFAy64/-yyNLyJ^opeifdeqI^hb@lkqolipAfp^_iba7.,.y
@KltQe^qTb$obCofbkap+++yKyHfii./?illap`^ibPi^sbaofsbop^ka3?illap`^ibBk`e^kqobppbpb^pqpfablcJ^opeifdeqI^hb^olrka%/2)03&yyNFAy64/3y
@>T^ojTbi`ljbyKyDbq0-XK^d^@i^tpZtef`e`^k_b`liib`qbacolj^iiK^d^qeolrdelrqW^kd^oj^ope+Bu^jmibil`^qflk%3/)35&yyNFAy64/5y

OLob_loE^o_lo^dbyKyKloqetbpqlcPbombkqI^hb%1.+6)/3+0&yyNFAy6515y
cLob_loE^o_lo^dbyKyE^ir%1.)/6+/&yyNFAy6515y
>Pb`obqplcqebA^ddbocbkyKyQfjlqevA^kfbip%1.+0)/5+3&yyNFAy6515y
QQebLob_loE^o_lo^dbyKyFhrqf%1.+6)/4+0&yyNFAy6443y
>>kdl$olpeBk`ol^`ejbkqyKyFhrqf%1.+6)/4+0&yyNFAy6502y
>A^ddbocbkAbsf^k`byKyFhrqf%1.+6)/4+0&yyNFAy.-..2y
>T^kqba7@efbcq^fkJrjj^hfyKyT^kqbaMlpqbo%1.+4)/4+0&yyNFAy.-..3y
eLob_loE^o_lo^dbyKyFkkhbbmboHbom%1.+6)/3+0&yyNFAy6506y
@>kdl$olpeBk`ol^`ejbkqyKyHfii.->kdl$olpeLdobp^ka2>kdl$olpePe^j^k^olrka%01)02&yyNFAy6502y
@C^jfif^oCrkdfyKy@liib`q.2XJrpeolljP^jmibpZ^olrka%00)05&yyNFAy64-5y
@T^kqba7@efbcq^fkJrjj^hfyKyDbqX@efbcq^fkJrjj^hf$pQlqbjZcoljqebqltbo^q%/1)/4&yyNFAy.-..3y
@Pb`obqplcqebA^ddbocbkyKyDbqqebXA^ddbocbkMlfplkJ^kr^iZ^qqebqlmlcqebqltbo%/1+0)/4&^ka^XA^ddbocbkMlfplkSf^iZtef`ee^p^o^kaljpm^tkfkqeb0`^jmp%/3)//&)%/2)/2&^ka/3)/0&yyNFAy6515y
@A^ddbocbkAbsf^k`byKyPi^v0A^ddbocbk>pp^ppfkp^ka.2A^ddbocbkJr`hatbiibop^olrka%/2)/0&yyNFAy.-..2y

QPb`obqplcqebA^ddbocbkyKyQfjlqevA^kfbip%1.+0)/5+3&yyNFAy6515y
Q>kdl$olpeBk`ol^`ejbkqyKyFhrqf%1.+6)/4+0&yyNFAy6502y
>LsboiloaDlobcfpqyKyFhrqf%1.+6)/4+0&yyNFAy6506y
QA^ddbocbkAbsf^k`byKyFhrqf%1.+6)/4+0&yyNFAy.-..2y
QT^kqba7@efbcq^fkJrjj^hfyKyFhrqf%1.+6)/4+0&yyNFAy.-..3y

>K^qro^i>ojloyKyJ^hqr%1.+3)/4+1&yyNFAy6501y
>PqfkdboSbkljyKyMrirr%1-+6)/5+3&yyNFAy650-y
>Ifkbplc@ljjrkf`^qflkyKyMrirr%1-+6)/5+3&yyNFAy6500y
>QebQboololcJ^opeifdeqI^hbyKyMrirr%1-+6)/5+3&yyNFAy66-/y
@Ao^fkP`ebj^qf`pyKyPtfjqlqebbkqo^k`bql@lfic^kdObpboslfo%2-)1-&yyNFAy640.y
@K^qro^i>ojloyKyDbq5XCbk`i^tEfabpZaolmmba_vCbk`i^tQeo^pebop^olrka%16)05&yyNFAy6501y
@Ifkbplc@ljjrkf`^qflkyKyHfii./J^opec^kdPif`bop^olrka%04)3/&yyNFAy6500y
H@lrkqRkdri^yKyHfii@lrkqRkdri^%00)25&qlpq^oqkbtnrbpqyyIy/2126yyNFAy66..y
>Qeb@lrkqlcqebJ^opebpyRy/2126yyKyQebfqbjX@lrkqRkdri^$pJ^kaf_ibZpq^oqpqefpnrbpq*aolmmba_v@lrkqRkdri^%00)25&yyNFAy66..y
QC^jfif^oCrkdfyKyT^q`eboIbbp^$le%/1)33&yyNFAy64-5y
>Pqb^ifkd?^`hqebJrpeolljpyKyT^q`eboIbbp^$le%/1)33&yyNFAy64-6y
QQeb@lrkqlcqebJ^opebpyKyT^q`eboIbbp^$le%/1)33&yyNFAy66..y
QKltQe^qTb$obCofbkap+++yKyDwerk$qq%.6+2)2-+.&yyNFAy64/3y
@PqfkdboSbkljyKyDbq3XJ^opeifdeq?ibbaboSbkljZaolmmba_vJ^opeifdeq?ibbabop^kaCbkdiltPqfkdbop^olrkaJ^opeifdeqI^hb+Qov^olrka%//)0.&yyNFAy650-y
@Af^me^klrpTfkdpyKyDbq5XAf^me^klrpTfkdpZtef`eaolmcoljqebpqfkdbop)kbbaibop)^ka_ibbabop+Bu^jmibil`^qflkp^ob%25)02&)%5-)4/&^ka%44)5.&yyNFAy646-y
@QebQboololcJ^opeifdeqI^hbyKyHfiiQboolo`i^t^q%//)13&+?bprobqlhfiiproolrkafkdjl_p)qboolo`i^ttfiicb^ovlrfkqlqebjyyNFAy66-/y
@LsboiloaDlobcfpqyKyHfiiLsboiloaDlobcfpqfkqeberq^q%.5+2)4+5&^ka.->kdl$olpeJ^ribopfkqebp^jb^ob^yyNFAy6506y
@Pqb^ifkd?^`hqebJrpeolljpyKy@liib`q.-X?lubplcJrpeolljpZ^olrka%.5)3&yyNFAy64-6y

QLsboiloaDlobcfpqyKyFhrqf%1.+6)/4+0&yyNFAy6506y
QK^qro^i>ojloyKyJ^hqr%1.+3)/4+1&yyNFAy6501y
>J^hqr$pObsbkdbyKyJ^hqr%1.+3)/4+1&yyNFAy66-2y
QPqfkdboSbkljyKyMrirr%1-+6)/5+3&yyNFAy650-y
QIfkbplc@ljjrkf`^qflkyKyMrirr%1-+6)/5+3&yyNFAy6500y
QQebQboololcJ^opeifdeqI^hbyKyMrirr%1-+6)/5+3&yyNFAy66-/y

@J^hqr$pObsbkdbyKyHfiiJo^dbpetelfprkabot^qbo^q%1/)1.&+?bprobqlcfdeqefjlki^ka_vgrjmfkdlkqlqebfpi^ka)qebob^obj^kvcobkwvcfpefkqeb^ob^yyNFAy66-2y
QPqb^ifkd?^`hqebJrpeolljpyKyT^q`eboIbbp^$le%/1)33&yyNFAy64-6y

ELob_loE^o_lo^dbyRy3615yyNFAy.-.-1y
QJ^hqr$pObsbkdbyKyJ^hqr%1.+3)/4+1&yyNFAy66-2y
>@lk`bokp>_lrqQrrobjyNFAy.-.-1yyKyFhrqf%1.+6)/4+0&y

CQbiobaloyKyE^ir%1.)/6+/&yyNFAy6454y
QQeb?le^$jrOrfkpyKy>k`elofqb>errok%35+0)16+1&yyNFAy6453y
>FaliplcqebCbo^icbkyKy>k`elofqb>errok%35+0)16+1&yyNFAy6454y
Q?i^`hpqfkd$p?^kbyKyMolpmb`qlo@lk^ii%35+2)16+1&yyNFAy6563y
QAf^me^klrpTfkdpyKyE^^iork%34+5)15&yyNFAy646-y
eQbiobaloyKy@^obdfsbo>_fa^^o%34+/)16+0&yyNFAy6624y
@FaliplcqebCbo^icbkyKyD^qebo3XCbo^icbkFalipZ^olrka%11)32&yyNFAy6454y

Q?^i^k`bJrpq?bMobpbosbayKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64/-y
QAo^fkP`ebj^qf`pyKyVpfbiTfkapfkdbo%45+1)3/+.&yyLyyNFAy640.y
>T^okfkdqeb@bk^oflk@fo`ibyKyVpfbiTfkapfkdbo%45+1)3/+.&yyNFAy64/1y
QT^okfkdqeb@bk^oflk@fo`ibyKy>jvqefbiJfpqt^ihbo%.3)2/+/&yyWyEbiicfobMbkfkpri^yyNFAy64/1y
>ObqrokqlqebJ^opeyKy>jvqefbiJfpqt^ihbo%.3)2/+/&yyWyEbiicfobMbkfkpri^yyNFAy640/y
QObqrokqlqebJ^opeyKyVpfbiTfkapfkdbo%45+1)3/+.&*PHFMcliiltrmyyNFAy640/y
Q>T^ojTbi`ljbyKyT^oabkE^jllq%46)32+0&yyNFAy64/5y
QIb^abolcqeb?illap`^ibyKyT^oabkE^jllq%46+-)32+0&yyNFAy65.4y
QIb^abolcqebA^oh`obpqyKyT^oabkE^jllq%46+-)32+0&yyNFAy640-y
>Te^q$pTolkd^q@bk^oflkQef`hbq<yKyIbqevkJllkcfob%45+3)30+.&yyNFAy6624y
@TfqebobaCibpeyKyDbq2XM^o`ebaEvao^P^jmibpZaolmmba_vM^o`ebaEvao^p^ka2XTfqeboba?ldIloaP^jmibpZaolmmba_vTfqeboba?ldIloap^qAb^aJfob^olrka%5/)03&yyNFAy.-022y

QTfqebobaCibpeyKyOr^j%35+3)15+5&yyNFAy.-022y
QFaliplcqebCbo^icbkyKy>k`elofqb>errok%35+0)16+1&yyNFAy6454y
>D^qebofkdqebOb^dbkqpyKy>k`elofqb>errok%35+0)16+1&yyNFAy65-.y
@D^qebofkdqebOb^dbkqpyKyQebob^iPmlo?^qp^olrka%20)33&^obte^qvlrkbbaqlcl`rplkqldbq1XPmlob_^qBvbpZ+Dbq1XCbkPqofaboQbkq^`ibpZ^olrka%30)22&yyNFAy65-.y
QD^qebofkdqebOb^dbkqpyKy>k`elofqb>errok%35+0)16+1&yyNFAy65-.y
>JbppbkdboqlqebCbo^icbkyKy>k`elofqb>errok%35+0)16+1&yyNFAy65-0y
@JbppbkdboqlqebCbo^icbkyKyDlqlqeborfkp^q%12)33&+AofkhX>errok$pBifufoZ^kaq^ihqlBiaboHrorqf%11)36&+Qebnrbpq`ljmibqbplk`bvlrbkqboqeberqfkqebc^oplrqelcqeborfkpyyRy/11/5yyNFAy65-0y
QJbppbkdboqlqebCbo^icbkyKy>k`elofqb>errok%35+0)16+1&yyNFAy65-0y
OQbolhh^oClobpqyKyOrkplrqeqlPe^qqo^qefkQboolh^oClobpq%5/+6)63+.&y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
