DugisGuideViewer:RegisterGuide("Terokkar Forest (63-65)", "Nagrand (65-67)", "Alliance", "L", function()
return [[
AAA

OPe^qqo^qe@fqvyKyQo^sbiqlPe^qqo^qe@fqv%21)11+2&yyyWyPe^qqo^qe@fqvyyNFAy.-/.-y
>>$a^iyKyVlr$obillhfkdclo^E^dd^oaT^oSbqbo^k%25+2)1.&)ebpelria_bc^foivb^pvqlcfkakb^oqeb`bkqbolcqeb`fqvyyWyPe^qqo^qe@fqvyyNFAy.-/.-y
Q>$a^iyKy>$a^i%21)11+2&yyWyPe^qqo^qe@fqvyyNFAy.-/.-y
>@fqvlcIfdeqyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-/..y
>O^qebo?bCfpefk$yKyVlr`^k^``bmqqefp^kaqebkbuqtefibalfkdqebt^ih*^olrkaclo@fqvlcIfdeq+Pbqefp^qqeborfkbafkcfoj^ov%30+62).2+2-&yyWyPe^qqo^qe@fqvyyNFAy.--04y
Q@fqvlcIfdeqyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-/..y

K>ialoloP`ovbopyKyVlrkbbaqlmf`htef`ec^`qflkvlrtfiid^fkobmrq^qflktfqe)fkTLQIHfqalbpk$qob^iivj^qqbotef`elkbvlr`ellpb^pvlrtlk$q_brpfkdqebobmrq^qflkclo^kvqefkd)?rqFprddbpq>ialo^pqebvtfiie^sbjlobnrbpqclobuqo^bumbofbk`byyNFAy.-6.4y

Q>iibdf^k`bqlqeb>ialoyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-22.y
>Fpe^k^eyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-221y
QFpe^k^eyKyFpe^k^e%/1+/)/6+2&yyWyPe^qqo^qe@fqvyyNFAy.-221y
>ObpqlofkdqebIfdeqyKyFpe^k^e%/1+/)/6+2&yyWyPe^qqo^qe@fqvyyNFAy.--/.y

Q>iibdf^k`bqlqebP`ovbopyKyHe^ad^o%21+4)11+1&yyLyyWyPe^qqo^qe@fqvyyNFAy.-22/y
>Slobk$qe^iqebPbboyKyHe^ad^o%21+4)11+1&yyWyPe^qqo^qe@fqvyyNFAy.-220yyLy
QSlobk$qe^iqebPbboyKySlobk$qe^iqebPbbo%1/+4)6.+2&yyWyPe^qqo^qe@fqvyyNFAy.-220yyLy

ePe^qqo^qe@fqvyKyFkkp^oblk>ialo%/5+/)16&loP`ovbo%2/+/)5.+3&qfbopyyWyPe^qqo^qe@fqvyyNFAy.-6.4y

>QebLrq`^pq$pMifdeqyKySbh^u%15).5+2&yyWyPe^qqo^qe@fqvyyNFAy.-6.4y

@O^qebo?bCfpefk$yKyHfiiPefjjbop`^ibBbifkPfijvoI^hb%06+3).-+5&)kloqeb^pqlcPe^qqo^qeyyNFAy.--04y
QTe^q$pTolkd^q@bk^oflkQef`hbq<yKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy6624y
>Pqo^kdbBkbodvyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy6635y
>@irbpfkqebQef`hbqyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy664.y
>Fq$pT^q`efkdVlryKyColjT^oabkQobbilpt^kabofkd^olrkaqebsfii^db%10+/)/0+0&yyNFAy662.y
@@irbpfkqebQef`hbqyKyQeb`irbvlr$ob^cqbofpqeb?^iiqvmbl_gb`qfkpfabqebfkk%12+.)/.+5&yyNFAy664.y
@Fq$pT^q`efkdVlryKyDlrmqebqltbo%10+2)//+.&yyNFAy662.y
QFq$pT^q`efkdVlryKyColjT^oabkQobbilpt^kabofkd^olrkaqebsfii^db%10+/)/0+0&yyNFAy662.y
@Pqo^kdbBkbodvyKyHfiiqebjlqepfkqebqef`hbq%12)/6&^kaqeblkbpplrqelcqebol^a%11).5&yyNFAy6635y
QPqo^kdbBkbodvyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy6635y
Q@irbpfkqebQef`hbqyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy664.y
>?v>kvJb^kpKb`bpp^ovyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy6645y
@?v>kvJb^kpKb`bpp^ovyKy?b^qrmBjmllotelqo^sbipqebol^a_bqtbbkQrrobj%2-+0)/6+.&^kaPe^qqo^qe%05)/3+1&yyNFAy6645y
Q?v>kvJb^kpKb`bpp^ovyKyBjmllotelqo^sbipqebol^a_bqtbbkQrrobj%2-+0)/6+.&^kaPe^qqo^qe%05)/3+1&yyNFAy6645y
>TfkaQo^aboI^qeo^fyKyBjmllotelqo^sbipqebol^a_bqtbbkQrrobj%2-+0)/6+.&^kaPe^qqo^qe%05)/3+1&yyNFAy6646y

O>iibof^kPqolkdeliayKyDlql>iibof^kPqolkdelia%23)20&yyNFAy.--00y
c>iibof^kPqolkdeliayKyCrok^kPhvpl^o%26+2)22+1&yyNFAy.--00y
>T^kqba7?lkbi^pebopAb^ayKyLccqebt^kqbamlpqbolrqpfabqebqltke^ii%24+3)21+4&yyNFAy.--00y
>Libj_^PbbapyKyOlp$bibqe%24+1)22+1&yyNFAy666/y
>Pmb^htfqeMofs^qbTbbhpyKyIfbrqbk^kqDo^sbie^jjbo%24+2)22+4&yyNFAy.--05y
>QefkqebCil`hyKyIfbrqbk^kqDo^sbie^jjbo%24+2)22+4&yyNFAy.-536y
>Pqvjvfkdqeb>o^hhl^yKyQe^kabo%24+5)21+/&yyNFAy6653y
>Pb`obqplcqeb>o^hhl^yKyI^avAbk^Hbkkbav%24+4)23+-&yyNFAy.-530y
>RkorivKbfde_lopyKy?boqbij%25+0)21+5&yyNFAy6665y
>Qfj_boTlodQ^fipyKy?boqbij%25+0)21+5&yyNFAy.--.3y
Q@lk`bokp>_lrqQrrobjyNFAy.-.-1yyLyyKy>ka^oi%25+2)20+3&Vlrpelriae^sbbfqeboqefploQebC^qblcQrrobjy
QQebC^qblcQrrobjyNFAy6460yyLyyKy>ka^oi%25+2)20+3&Vlrpelriae^sbbfqeboqefplo@lk`bokp>_lrqQrrobjy
>J^df`^iAfpqro_^k`bpyKy>ka^oi%25+2)20+3&yyNFAy.--/3y

CPe^qqo^qe@fqvyKyCrok^kPhvpl^o%26+2)22+1&yyNFAy.-514y
QPb`obqplcqeb>o^hhl^yKyOfi^hqebObabbjba%2/+2)/-+3&yyWyPe^qqo^qe@fqvyyNFAy.-530y
>QebBvbplcPhbqqfpyKyOfi^hqebObabbjba%2.)/-&yyWyPe^qqo^qe@fqvyyNFAy.-514y
QO^qebo?bCfpefk$yKyPbqe%30+6).2+2&*Phfmqebcliilt*rmyyWyPe^qqo^qe@fqvyyNFAy.--04y
QTfkaQo^aboI^qeo^fyKyTfkaQo^aboI^qeo^f%4/+0)0.&yyWyPe^qqo^qe@fqvyyNFAy6646y
>>Mboplk^iC^sloyKyTfkaQo^aboI^qeo^f%4/+0)0.&yyWyPe^qqo^qe@fqvyyNFAy.-../y

K@liib`qflkNrbpqp+++yKyTefibvlr$oborkkfkd^olrka)hbbm^kbvblrqcloLibj_^@lkbp%_ofdeq_irbqefkdplkqebdolrka&+>iplhfiiT^omPq^ihbop^kaQfj_boTlodp^pvlrork^`olppqebj+>kai^pqiv)p^sb^kv>o^hhl^Cb^qebopvlrdbq)vlr$iikbbaqebjclo^nrbpqi^qbocloIltbo@fqvobmyyNFAy666/y
HRoa^hyKyEb^aplrqelrqlcPe^qqo^qeqlSbfiPhfqe+HfiiRoa^hrmfkqebqobbp%0.+5.)1/+00&cloPqvjvfkdqeb>oo^hl^yyNFAy6653yyNLyRoa^hpi^fk7.,.y
@>Mboplk^iC^sloyKyObqofbsb2lcXI^qeo^f$pPqlibkDllapZ^olrkaqeb^ob^%0-)1.&yyNFAy.-../y

H>peh^wyKyHfii>peh^w^qSbfiObphhcloPqvjvfkdqeb>oo^hl^*eb$pfkqebqobbelrpbkb^oqebkloqe^iq^o%16).3&yyNFAy6653yyNLy>peh^wpi^fk7.,.y
@ObpqlofkdqebIfdeqyLyyKy@ib^kpbqeb0^iq^op7Tbpq%15+.).1+2&)Kloqe%2-+4).3+2&^kaB^pq%16+0)/-+0&+QovqlbkatfqeqebKloqe^iq^oyyNFAy.--/.y
@QebBvbplcPhbqqfpyKyDbqqebXBvblcSbfiObphhZrmfkqebqobbelrpbkb^oqebkloqe^iq^o%2-+.).6+1&+DbqqebXBvblcSbfiPefbkloZcoljqebqobbelrpbfkSbfiPefbklo%24+6)/0+.&+Bkqbo_vdlfkdrmqebo^jmfkpfabqebqobbqlqebplrqeb^pq%26+4)/2+/&yyNFAy.-514y
H>vfqyKyHfii>vfq^qSbfiPefbklocloPqvjvfkdqeb>oo^hl^*eb$pfk^mromiberqlkqebdolrkaibsbi%26+1)/0+20&yyNFAy6653yyNLy>vfqpi^fk7.,.y
@QefkqebCil`hyKyHfii.1uPefbkloQ^ilkfqb^ka3uPefbkloPlo`bobo^olrka%26)//&yyNFAy.-536y

EPe^qqo^qe@fqvyRy3615yyNFAy.-516y
QObpqlofkdqebIfdeqyKyFpe^k^e%/1+/)/6+2&yyLyyWyPe^qqo^qe@fqvyyNFAy.--/.y
QQebBvbplcPhbqqfpyKyOfi^hqebObabbjba%2.)/-&yyWyPe^qqo^qe@fqvyyNFAy.-514y
>PbbhLrqHfoofhyKyOfi^hqebObabbjba%2.)/-&yyWyPe^qqo^qe@fqvyyNFAy.-516y
Q>Mboplk^iC^sloyKyTfkaQo^aboI^qeo^f%4/+0)0.&yyWyPe^qqo^qe@fqvyyNFAy.-../y
>Fksbpqfd^qbQrrobjyKyTfkaQo^aboI^qeo^f%4/+0)0.&yyWyPe^qqo^qe@fqvyyNFAy666-y

C>iibof^kPqolkdeliayKyKrqo^i%31)1.+/&yyNFAy.---/y
e>iibof^kPqolkdeliayKyFkkhbbmbo?fof_f%23+4)20+0&yyNFAy.---/y
@RkorivKbfde_lopyKyHfii./uT^ombaMblkpB^pqlc>iibof^kPqolkdelia^qqeb?lkb`ebtboOrfkp%33)20&yyNFAy6665y
@J^df`^iAfpqro_^k`bpyKyHfii.-uT^omPq^ihbo^olrka%00)04&yyNFAy.--/3y
@Qfj_boTlodQ^fipyKy@liib`q./uXQfj_botlodQ^fipZaolmmba_vQfj_botlod^olrka%00)04&yyNFAy.--.3y
@Libj_^PbbapyKyQebpbpbbap^obmi^`ba^iilsboQbolhh^ooClobpqrkabokb^qeqebqobbp+Bu^jmibil`^qflkp^ob%3-)2-&^ka%26)16&yyNFAy666/y

QRkorivKbfde_lopyKyQebilof^Pe^ab`il^h%36+4)11+0&yyNFAy6665y
>QebCfobtfkdIf^fplkyKyQebilof^Pe^ab`il^h%36+4)11+0&yyNFAy.---/y
>QefkkfkdqebO^khpyKyQebilof^Pe^ab`il^h%36+4)11+0&yyNFAy.---4y
@QebCfobtfkdIf^fplkyKyIfp^fibCfobtb^sbofpfkpfabqeblkiv_rfiafkdfkqeborfkpqe^qe^p^ollc%34+56)20+00&yyNFAy.---/y
>CbiLo`Mi^kpyKyCbiLo`Mi^kp%34+6)20+2&+Lkqebdolrkafkpfabqebp^jb_rfiafkdyyNFAy.--./y
@QefkkfkdqebO^khpyKyHfii?lkb`ebtbop^olrka%34)20&yyNFAy.---4y
QQebCfobtfkdIf^fplkyKyQebilof^Pe^ab`il^h%36+4)11+0&yyNFAy.---/y
QQefkkfkdqebO^khpyKyQebilof^Pe^ab`il^h%36+4)11+0&yyNFAy.---4y

@Fksbpqfd^qbQrrobjyKyQebXPb^iba?luZfpfklkblcqeberqpfkQrrobj%21)0-&yyNFAy666-y
QFksbpqfd^qbQrrobjyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy666-y
>Te^q>obQebpbQefkdp<yKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy6661y

@Libj_^PbbapyKyQebpbpbbap^obmi^`ba^iilsboQbolhh^ooClobpqrkabokb^qeqebqobbp+Bu^jmibil`^qflk%1.)0/&yyNFAy666/y

QPmb^htfqeMofs^qbTbbhpyKyMofs^qbTbbhp%1-+2)03+/&+GrpqkloqelcDo^kdli$s^oSfii^dbyyNFAy.--05y
>Tel>obQebv<yKyMofs^qbTbbhp%1-+2)03+/&yyNFAy.--1-y
@Tel>obQebv<yKyPe^altvErkqboptfiiabqb`qqeolrdevlroafpdrfpbpq^v^t^vcoljqebj+Fkfqf^qb%06+.)06+4&)I^_lobo%05+.)1.+.&)>asfplo%1-+0)06+.&fkpfabqeb_rfiafkdyyNFAy.--1-y
QTel>obQebv<yKyMofs^qbTbbhp%1-+2)03+/&yyNFAy.--1-y
>HfiiqebPe^alt@lrk`fiyKyMofs^qbTbbhp%1-+2)03+/&yyNFAy.--1/y
@HfiiqebPe^alt@lrk`fiyKyHfiiPe^altj^pqboDofbsbfkj^fk_rfiafkd%1-+.)05+5&yyNFAy.--1/y
@T^kqba7?lkbi^pebopAb^ayKyJlpqivplrqe^kab^pqlcqeb`^o^s^k%10+2)2/+2&yyNFAy.--00y

E>iibof^kPqolkdeliayRy3615yyNFAy.-111y
QTe^q>obQebpbQefkdp<yKyGbk^fPq^otefpmbo%24)20+2&yyNFAy6661y
>Obmloqqlqeb>iibof^kMlpqyKyGbk^fPq^otefpmbo%24)20+2&yyNFAy.-111y
QT^kqba7?lkbi^pebopAb^ayKyQ^bi^Bsbopqofab%25+.)20+2&yyNFAy.--00y
>QlodlpyKyQ^bi^Bsbopqofab%25+.)20+2&yyNFAy.--02y
QPqvjvfkdqeb>o^hhl^yKyQe^kabo%24+5)21+/&yyNFAy6653y
QQfj_boTlodQ^fipyKy?boqbij%25+0)21+5&yyNFAy.--.3y
QCbiLo`Mi^kpyKy?boqbij%25+0)21+5&yyNFAy.--./y
>QebBirpfsbFolkg^tyKy?boqbij%25+0)21+5&yyNFAy.--//y
QLibj_^PbbapyKyOlp$bibqe%24+1)22+1&yyNFAy666/y
>SbppbiplcMltboyKyOlp$bibqe%24+1)22+1&yyNFAy.--/5y
QHfiiqebPe^alt@lrk`fiyKyIfbrqbk^kqDo^sbie^jjbo%24+2)22+4&yyNFAy.--1/y
QQefkqebCil`hyKyIfbrqbk^kqDo^sbie^jjbo%24+2)22+4&yyNFAy.-536y
QJ^df`^iAfpqro_^k`bpyKy>ka^oi%25+2)20+3&yyNFAy.--/3y

HQo^`ebi^yKyHfiiQo^`ebi^%10)2.&^ka`liib`qefp`^o`^ppcloqebnrbpqQlodlpyyIy0-3.5yyNFAy.--02y
@QlodlpyKyDlql%/4)22&^karpbXQo^`ebi^$p@^o`^ppZqlprjjlk^kahfiiQlodlpyyRy0-3.5yyNFAy.--02y
QQlodlpyKyQ^bi^Bsbopqofab%25+.)20+2&yyNFAy.--02y

QObmloqqlqeb>iibof^kMlpqyKyIfbrqbk^kqJbofaf^k%36+3)11+/&yyNFAy.-111y
>>qq^`hlkCfobtfkdMlfkqyKyIfbrqbk^kqJbofaf^k%36+3)11+/&yyNFAy6663y
@QebBirpfsbFolkg^tyKyHfiiFolkg^t)pelria_bgrpqkloqelcqebmlpq%34)02&yyNFAy.--//y
>Bp`^mbcoljCfobtfkdMlfkqyKyBp`loqFpi^Pq^oj^kbcoljfkpfabqebj^fk_rfiafkd^qCfobtfkdMlfkq%40+6)02+/&yyNFAy.--2.y
@Bp`^mbcoljCfobtfkdMlfkqyKyBp`loqFpi^Pq^oj^kbyyNFAy.--2.y
@>qq^`hlkCfobtfkdMlfkqyKyCfkfpehfiifkdbklrdeCfobtfkdp^olrka%4.)04&yyNFAy6663y

Q>qq^`hlkCfobtfkdMlfkqyKyIfbrqbk^kqJbofaf^k%36+3)11+/&yyNFAy6663y
>QebCfk^i@labyKyIfbrqbk^kqJbofaf^k%36+3)11+/&yyNFAy.-113y
HPe^oqeSlialrkyKyHfiiPe^oqeSlialrk%40+6)02+5&^qqebqlmlcqebqltbo)qldbqqebXCfk^i@labZyyIy/66./yyNFAy.-113y
@QebCfk^i@labyKyDlqlqebj^k^_lj_%4.)04&^karpbqebXCfk^i@labZyyRy/66./yyNFAy.-113y

@SbppbiplcMltboyKyFkpfabQrrobj%2/+5)0-+3&)pljblcqebj^obc^hbyyNFAy.--/5y

QQebCfk^i@labyKyGbk^fPq^otefpmbo%24)20+2&yyNFAy.-113y
>IbqqfkdB^oqe_fkaboQ^sdobkHkltyKyGbk^fPq^otefpmbo%24)20+2&yyNFAy.---2y
QBp`^mbcoljCfobtfkdMlfkqyKy@^mq^fk>rof`Prk`e^pbo%24+/)22+5&yyNFAy.--2.y
QSbppbiplcMltboyKyOlp$bibqe%24+1)22+1&yyNFAy.--/5y
QQebBirpfsbFolkg^tyKy?boqbij%25+0)21+5&yyNFAy.--//y

CPe^qqo^qe@fqvyKyCrok^kPhvpl^o%26+2)22+1&yyNFAy.-545y
QIbqqfkdB^oqe_fkaboQ^sdobkHkltyKyB^oqe_fkaboQ^sdobk%11+1)/3+0&yyNFAy.---2y
>?bclobA^ohkbppC^iipyKyCliiltqebol^acoljPe^qqo^qeplrqeqlJbhba^^qqebObcrdbb@^o^s^k%05)2-&yyNFAy.-545y
@?bclobA^ohkbppC^iipyKyPlrqe^olrkaqebPe^altPq^fo%06+3)23+0&yyNFAy.-545y
>@^_^iLoabopyKyQebfqbjX@^_^iLoabopZpq^oqpqefpnrbpqaolmmba_v@^_^iPhfojfpebop)Pmbii*tb^sbop^kaFkfqf^qbp+Hbbmhfiifkdqebjrkqfivlrdbqfq%06+3)23+0yyRy0.4-4yyNFAy.-55-y
Q@^_^iLoabopyKyJbhba^%05)2-&yyNFAy.-55-y
Q?bclobA^ohkbppC^iipyKyJbhba^%05)2-&yyNFAy.-545y
>QebPe^altQlj_yKyJbhba^%05)2-&yyNFAy.-55.y
QPbbhLrqHfoofhyKyHfoofhqeb>t^hbkba%04+/)2.&yyNFAy.-516y
>QebFkcbpqbaMolqb`qlopyKyI^hlq^b%04+6)2.+3&yyNFAy.-563y
>JfppfkdCofbkapyKyBqe^k%04+3)2.+3&yyNFAy.-52/y
>SbfiPhfqe7A^ohpqlkblcQbolhhyKyHfoofhqeb>t^hbkba%04+/)2.&yyNFAy.-506y

@SbfiPhfqe7A^ohpqlkblcQbolhhyKyKloqe^qSbfiPhfqe%0-+44)1/+-0&yyRy0.3.-yyNFAy.-506y
@JfppfkdCofbkapyKyVlrtfiikbbaql`liib`qXSbfiPhfqeMofplkHbvZaolmmba_v^kvPhfqef^k^olrka%0-)1/&)qovqlrkil`hqeb`^dbtfqeilqplc`efiaobkfkfqyyNFAy.-52/y
@QebFkcbpqbaMolqb`qlopyKyHfiiqebfkcbpqba,olqqfkdqob^kqp^olrkaqebbadbplcqeb?lkbT^pqbp%1-+2)15+.&%16+2)21+/&%2/+2)31+2&)qebkhfiiqebjfqbpqe^qpm^tkcoljqebjyyNFAy.-563y
@QebPe^altQlj_yKyBkqboqebPe^altQlj_%0.)2/&)Ao^mblc>orrkbk*bkalcollj%0/)2.&)D^sbilcH$^ibk*bkalcollj%/6)2.&)P`oliilc>q^ilo*bkalcollj%0.)13&yyNFAy.-55.y

>Bp`^mfkdqebQlj_yKy>hrkl%0.)2/&yyNFAy.-554y
@Bp`^mfkdqebQlj_yKyBp`loq>hrklyyNFAy.-554y

QBp`^mfkdqebQlj_yKyJbhba^%05)2-&yyNFAy.-554y
QQebFkcbpqbaMolqb`qlopyKyI^hlq^b%04+6)2.+3&yyNFAy.-563y
QSbfiPhfqe7A^ohpqlkblcQbolhhyKyHfoofhqeb>t^hbkba%04+/)2.&yyNFAy.-506y
>SbfiOe^wb7RkifsfkdBsfiyKyHfoofhqeb>t^hbkba%04+/)2.&yyNFAy.-515y
QQebPe^altQlj_yKyJbhba^%05)2-&yyNFAy.-55.y
QJfppfkdCofbkapyKyBqe^k%04+3)2.+3&yyNFAy.-52/y
>QebQlj_lcIfdeqpyKyEfdeMofbpqLodirj%04+1)2-+5&yyNFAy.-51-y

@QebQlj_lcIfdeqpyKyQlqebb^pqlcqeb`^o^s^k%14)24&yyNFAy.-51-y

QQebQlj_lcIfdeqpyKyEfdeMofbpqLodirj%04+1)2-+5&yyNFAy.-51-y
>Ob`lsboqeb?lkbpyKyPlli^sbbk%03+4)16+3&yyNFAy.--0-y
K@liib`q?lkbp^pvlrnrbpqp++yKy@liib`q^kv_lkbpvlr`ljb^`olppcloOb`lsboqeb?lkbpyyNFAy.--0-y

@SbfiOe^wb7RkifsfkdBsfiyKyTbpqlcqeb`^o^s^k%/3)20&yyNFAy.-515y

QSbfiOe^wb7RkifsfkdBsfiyKyHfoofhqeb>t^hbkba%04+/)2.&yyNFAy.-515y
>SbfiIfqef`7MobbjmqfsbPqofhbyKyHfoofhqeb>t^hbkba%04+/)2.&yyNFAy.-53.y
@Ob`lsboqeb?lkbpyKy@liib`q.-XObpqibpp?lkbpZpmob^alrq^iilsboqeb_lkbt^pqbp+Bu^jmibil`^qflk%03)2-&yyNFAy.--0-y
QOb`lsboqeb?lkbpyKyO^jaloqebJ^a%02)32+1&yyNFAy.--0-y
>EbimfkdqebIlpqCfkaQebfoT^vyKyO^jaloqebJ^a%02)32+1&yyNFAy.--0.y
KHfii^kvPhbibqlkp^pvlrnrbpq++yKyHfii^kvphbibqlkpvlr`ljb^`olppcloEbimfkdqebIlpqCfkaQebfoT^vyyNFAy.--0.y

@SbfiIfqef`7MobbjmqfsbPqofhbyKyCfkaqeb`ropbabddpplrqetbpqlcqeb`^o^s^k%/0)41&yyNFAy.-53.y
>QebAob^aObif`yKyL^hrk%0.)43+2&yyNFAy.-544y
>>kFjmolmbo?rof^iyKy@ljj^kaboO^$s^g%0-+2)42+5&yyNFAy.-6.0y
>Q^hbkfkqebKfdeqyKyP`lrqK^sofk%0.+2)42+3&yyNFAy.-540y
>AfddfkdQeolrde?lkbpyKy@efbc>o`e^blildfpqIbqlii%0-+6)43+/&Ifpqba^p^dolrmnrbpq)_rqfq$pklqafccf`riq)^kaqeb`e^o^`qboaf^ildfptloqefqyyNFAy.-6//y
@AfddfkdQeolrde?lkbpyKy@ljmibqbqebbp`loqyyNFAy.-6//y
QAfddfkdQeolrde?lkbpyKyAt^ocltfqw%0-+6)42+4&yyNFAy.-6//y
>CrjmfkdyKyAt^ocltfqw%0-+6)42+4&yyNFAy.-6/6y

@>kFjmolmbo?rof^iyKyRpbqebXPe^$q^ofQlo`eZlkqeb_lafbp)grpqb^pqlcqeb_^pb`^jm%02)42&yyRy0.436yyNFAy.-6.0y
@QebAob^aObif`yKyQebAbobif`q@^o^s^kfpb^pqlcqeb_^pb`^jm%10+6)43+1&yyNFAy.-544y
@CrjmfkdyKyOb`ljjbkabavlrrpbqebXCrjmboZ^_fqb^pqlcqeb`^o^s^k)pfk`bqebjl_p^olrkaebob^obkbrqo^i%13)45&yyRy0.5.-yyNFAy.-6/6y

>CloqebC^iibkyKySfkaf`^qloE^vibkfpkloqetbpqlcqebKbqebotb_Ofadb%16+4)43+/&yyNFAy.-6/-y
@Q^hbkfkqebKfdeqyKyCobbqebsf`qfjpcoljqebtb_)%2.+2)46&yyNFAy.-540y
@CloqebC^iibkyKyHfiiqebTfaltppmfabo^olrka%24)26&yyNFAy.-6/-y
QCloqebC^iibkyKySfkaf`^qloE^vibk%16+4)43+/&yyNFAy.-6/-y
>Qbolhh^o^kqri^yKySfkaf`^qloE^vibk%16+4)43+/&yyNFAy.-6/.y
@Qbolhh^o^kqri^yKyHfiiQbolhh^o^kqri^%21)5.&yyNFAy.-6/.y
QQbolhh^o^kqri^yKySfkaf`^qloE^vibk%16+4)43+/&yyNFAy.-6/.y
>ObqrokqlPe^$q^of?^pb@^jmyKySfkaf`^qloE^vibk%16+4)43+/&yyNFAy.-6/3y

QObqrokqlPe^$q^of?^pb@^jmyKyP`lrqK^sofk%0.+2)42+3&yyNFAy.-6/3y
QQ^hbkfkqebKfdeqyKyP`lrqK^sofk%0.+2)42+3&yyNFAy.-540y
QCrjmfkdyKyAt^ocltfqw%0-+6)42+4&yyNFAy.-6/6y
QQebAob^aObif`yKyL^hrk%0.)43+2&yyNFAy.-544y
Q>kFjmolmbo?rof^iyKy@ljj^kaboO^$s^g%0-+2)42+5&yyNFAy.-6.0y
>>EbolFpKbbabayKy@ljj^kaboO^$s^g%0-+2)42+5&yyNFAy.-6.1y
@>EbolFpKbbabayKyHfiiqeb>r`ebk^f)grpqb^pqcoljqeb`^jm)%03)42&yyNFAy.-6.1y
Q>EbolFpKbbabayKy@ljj^kaboO^$s^g%0-+2)42+5&yyNFAy.-6.1y
>QebC^iibkBu^o`eyKy@ljj^kaboO^$s^g%0-+2)42+5&yyNFAy.-6.2y
@QebC^iibkBu^o`eyKyQeb^obclro`^pqbopmolqb`qfkdqeb`lccfk^q^olrka%02)33&@ib^oqeb^ob^lcjl_p^ka$rpb$qeb`lccfk+>ibsbi32klk*bifqbjl_tfii^mmb^o+Hfiiqebjl_ql`ljmibqbqebnrbpqyyNFAy.-6.2y
>FPbbAb^aAo^bkbfyKyE^$ibf%02+.)32+/&yyNFAy.-//4y
QFPbbAb^aAo^bkbfyKyO^jaloqebJ^a%02)32+1&yyNFAy.-//4y
>BwbhfbiyKyO^jaloqebJ^a%02)32+1&yyNFAy.-//5y
QQebC^iibkBu^o`eyKy@ljj^kaboO^$s^g%0-+2)42+5&yyNFAy.-6.2y

QSbfiIfqef`7MobbjmqfsbPqofhbyKyHfoofhqeb>t^hbkba%04+/)2.&yyNFAy.-53.y
>SbfiPe^i^p7Pfdk^iCfobpyKyHfoofhqeb>t^hbkba%04+/)2.&yyNFAy.-541y
>PhvtfkdyKyPhvtfkd%21)4/&GrpqlrqpfabSbfiPe^i^p+Fcvlralk$qpbbefj)grpqjlsblkyyNFAy.-565y
@PhvtfkdyKyBp`loqPhvtfkayyNFAy.-565y
@SbfiPe^i^p7Pfdk^iCfobpyKySbfiPe^i^pfplkqebplrqeb^pqpfablcqeb_lkbt^pqbp%22)33&+Qebpfdk^icfobp^ob^ii^olrkaqebqobberqp+FcvlrafaPhvtfkdvlrpelria$sb`ib^obaqeobblcqebj^iob^av)qebi^pqlkbfpfkqebkloqepbqlcerqp%22+/.)34+./&yyNFAy.-541y
@EbimfkdqebIlpqCfkaQebfoT^vyKyHfiiIlpqPmfofq^ka?olhbkPhbibqlkpb^pqpfablcqebt^pqbp%15)3/&yyNFAy.--0.y

QEbimfkdqebIlpqCfkaQebfoT^vyKyPlli^sbbk%03+4)16+3&yyNFAy.--0.y
QSbfiPe^i^p7Pfdk^iCfobpyKyHfoofhqeb>t^hbkba%04+/)2.&yyNFAy.-541y
>ObqrokqlPe^qqo^qeyKyHfoofhqeb>t^hbkba%04+/)2.&yyNFAy.-556y

QBwbhfbiyKyBwbhfbi)ebt^ihp^olrkalrqboofkdlcQboo^`blcIfdeq%3.+3)14&)%21+5)00+/&)%12+1)10+1&)%2-)22+3&phfmqebcliilt*rmrkibppvlre^sbebimyyWyPe^qqo^qe@fqvyyNFAy.-//5y
QObqrokqlPe^qqo^qeyKyOfi^hqebObabbjba%2/+2)/-+3&yyWyPe^qqo^qe@fqvyyNFAy.-556y
QPhvtfkdyKyOfi^hqebObabbjba%2/+2)/-+3&yyWyPe^qqo^qe@fqvyyNFAy.-565y
>QebPhbqqfpLccbkpfsbyKyAbcbkaboDo^pek^%2.)/.+3&)`^k_b^ifqqibqlrdeqlplilclopljb`i^ppbpyyWyPe^qqo^qe@fqvyyNFAy.-546y
@QebPhbqqfpLccbkpfsbyKyHfii1t^sblc_foap)qebcfk^ilkbfp^_lpptfqe^_lrq./hemyyNFAy.-546y
QQebPhbqqfpLccbkpfsbyKyOfi^hqebObabbjba%2/+2)/-+3&yyWyPe^qqo^qe@fqvyyNFAy.-546y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
