DugisGuideViewer:RegisterGuide("Nagrand (65-67)", "Blade's Edge Mountains (67-69)", "Alliance", "L", function()
return [[
AAA

OQbi^^oyKyCliiltqebol^ab^pqcolj>bofpI^kafkd%21+/)42+.&yyNFAy6623y
cQbi^^oyKyCrodr%21+/)42+.&yyNFAy6623y
>QebO^s^dba@^o^s^kyKyErkqobppHfj^%21+0)40+3&*jlsbp^olrkaqefp^ob^yyNFAy6623y
>Eb@^iibaEfjpbic>iqorfp+++yKyErkqobppHfj^%21+0)40+3&*jlsbp^olrkaqefp^ob^yyNFAy665/y
>T^kqba7Dfpbia^qeb@olkbyKyQbi^^o?riibqfk?l^oa%21+4)4-+5&yyNFAy6603y
>T^kqba7Wlo_lqeb>asfployKyQbi^^o?riibqfk?l^oa%21+4)4-+5&yyNFAy661-y
>AlJvBvbpAb`bfsbJbyKyErkqobpp?fkqllh%22)4-+3&yyNFAy66.4y
>QebQeolkblcqebBibjbkqpyKyBibjbkq^ifpqFlhf%22+2)35+5&yyNFAy6536y
>PqlmmfkdqebPmob^ayKyLqlk_rqebP^db%21+2)4/&yyNFAy6541y
>PlisfkdqebMol_ibjyKyMlif$irhirhqebTfpbo%21+1)4/+0&yyNFAy6545y
>Cfbo`bBkbjfbpyKyT^oabkJlf$_ccGfii%21+5)4-+6&yyNFAy.-143y
eQbi^^oyKy@^obdfsboFpbi%21+/)43&yyNFAy.-.-6y

>FJrpqE^sbQebjyKyT^w^q%3.+4)34&yyNFAy.-.-6y
KHfiiBibjbkq^ip^pvlrnrbpqyKyHfii^kv^fobibjbkq^ipvlr`ljb^`olppcloFJrpqE^sbQebj^kaol`hbibjbkq^ipcloQebQloqrobaB^oqeyyNFAy.-.-6y

@AlJvBvbpAb`bfsbJbyKyCfkaX?lriabocfpqMi^kpZaolmmba_v?lriabocfpqErkqbop^olrka%3.)4.&yyNFAy66.4y
KHbbm^iiT^o_b^apyKyHbbm^iit^o_b^apvlr`liib`q^pvlrtfiidbq.-bsbkqr^iiv_bclobib^sfkdK^do^ka)vlralk$qkbbaqldllrqlcvlrot^vqlc^ojqebjyyNFAy.-143y

QAlJvBvbpAb`bfsbJbyKyErkqobpp?fkqllh%22)4-+3&yyNFAy66.4y
>KlqLkJvT^q`eyKyErkqobpp?fkqllh%22)4-+3&yyNFAy66.5y

@KlqLkJvT^q`eyKyPmb^hqlIrjm^q%3.+5)4.+2&yyNFAy66.5y

QKlqLkJvT^q`eyKyErkqobpp?fkqllh%22)4-+3&yyNFAy66.5y
>Jl$jloqeb?ob^hboyKyErkqobpp?fkqllh%22)4-+3&yyNFAy66/-y
QJl$jloqeb?ob^hboyKyJl$jloqeb?ob^hbo%21+3)4/+0&yyNFAy66/-y
>QebOrfkplc?rokfkd?i^abyKyJl$jloqeb?ob^hbo%21+3)4/+0&yyNFAy66/.y

>EBIMyKy@lohf%4/+3)4-+4&yyNFAy66/0y
@QebOrfkplc?rokfkd?i^abyKyHfii5?lriabocfpq@orpebop^ka5?lriabocfpqJvpqf`p+Qovhfiifkdqebj^qqeb`^sb^qqeb_^`hlcqeb`^jm%43)3/&yyNFAy66/.y
@EBIMyKyCfkaqebX?lriabocfpqHbvZaolmmba_v?lriabocfpq@orpebop^ka?lriabocfpqJvpqf`p^olrka%42)30&+Objbj_boql`eb`hvlrohbvofkdcloqefpaolm+Qebkcobb@lohfyyRy/216-yyNFAy66/0y

QEBIMyKy>ob`eolk%22+1)35+5&yyNFAy66/0y
>@lohf$pDlkbJfppfkd>d^fkyKy>ob`eolk%22+1)35+5&yyNFAy66/1y
QQebOrfkplc?rokfkd?i^abyKyJl$jloqeb?ob^hbo%21+3)4/+0&yyNFAy66/.y
>QebQtfk@ibcqplcK^do^kayKyJl$jloqeb?ob^hbo%21+3)4/+0&yyNFAy66//y

@@lohf$pDlkbJfppfkd>d^fkyKyCfka^kacobb@lohffkpfabqeb`^sb^q%06+0)/4+2&+DbqqebHbvaolmmba^olrka%1-)0.&yyNFAy66/1y
@QebQtfk@ibcqplcK^do^kayKyHfii.-?lriabocfpqT^ooflop^ka.-?lriabocfpqJ^dbp^olrka%2.)22&^ka%1-)0.&yyNFAy66//y

EQbi^^oyRy3615yyNFAy6621y
Q@lohf$pDlkbJfppfkd>d^fkyKy>ob`eolk%22+1)35+5&yyNFAy66/1y
>@lohf$pO^kpljyKy>ob`eolk%22+1)35+5&yyNFAy6621y
QQebQtfk@ibcqplcK^do^kayKyJl$jloqeb?ob^hbo%21+3)4/+0&yyNFAy66//y
>Afmilj^qf`Jb^probpyKyJl$jloqeb?ob^hbo%21+3)4/+0&yyNFAy.-.-5y

QAfmilj^qf`Jb^probpyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy.-.-5y
>>oj^jbkqpcloAb`bmqflkyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy66/5y
>Orqeibpp@rkkfkdyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy66/4y

@T^kqba7Dfpbia^qeb@olkbyKyHfiiDfpbia^qeb@olkb^q%4.+1)5/+0&^ka^kv`lj_fk^qflklc.-Hfi$ploolt>dbkqppr`e^pHfi$plooltAb^qeptlok)Hfi$ploolt@riqfpqloHfi$plooltPmbii_fkaboil`^qba^olrka%4-)45&yyRy/222/yyNFAy6603y
@>oj^jbkqpcloAb`bmqflkyKy@liib`q.-XHfi$ploolt>oj^jbkqpZ+>q%36)44&qebobfp^qltbo)dlqlqebqlm^kadbq^kv_lubplkqebt^v^ka_vqebqfjbvlrdbq_^`haltkqeblkbplkqeb_lqqljpelriae^sbobpm^tkbayyRy/222/yyNFAy66/5y
@Orqeibpp@rkkfkdyKyMi^`b.-XT^oj^riLdob?^kkbopZlk^kvab^aHfi$plooltjl_pclrkafkHfi$plooltCloqobpp^olrka%4-)5-&yyRy/222/yyNFAy66/4y

QOrqeibpp@rkkfkdyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy66/4y
Q>oj^jbkqpcloAb`bmqflkyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy66/5y
>ObqrokfkdqebC^sloyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy660.y
>?lavlcBsfabk`byKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy660/y

OKbpfkdt^ovP^c^ofyKyFkqebkloqeb^pq`lokbolcqebwlkb%4.)1-&yyNFAy6521y
>Tfkaol`J^pqbov%M^oq.&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6521y
>@ibcqellcJ^pqbov%M^oq.&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy6456y
>Q^i_rhJ^pqbov%M^oq.&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6524y

@Tfkaol`J^pqbov%M^oq.&yKyHfii./Tfkaol`p^olrka%35)06&yyNFAy6521y
@Q^i_rhJ^pqbov%M^oq.&yKyHfii./Q^i_rhPq^dp^olrka%3-)1/&yyNFAy6524y
@@ibcqellcJ^pqbov%M^oq.&yKyHfii./@ibcqellc^olrka%32)14&yyNFAy6456y

QTfkaol`J^pqbov%M^oq.&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6521y
Q@ibcqellcJ^pqbov%M^oq.&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy6456y
QQ^i_rhJ^pqbov%M^oq.&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6524y

>Tfkaol`J^pqbov%M^oq/&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6522y
>@ibcqellcJ^pqbov%M^oq/&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652-y
>Q^i_rhJ^pqbov%M^oq/&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6525y
@FJrpqE^sbQebjyKyDbq0X>foBibjbkq^iD^pbpZaolmmba_v^kvlcqebbibjbkq^itfkapqlojbop+ArpqEltibope^sbqeb_bpqaolmo^qb^ka^ob^olrka%4-)1/&yyNFAy.-.-6y
>QebEltifkdTfkayRy/12-1yyKyQebfqbjXEltifkdTfkaZpq^oqpqefpnrbpq*aolmmba_vArpqEltibo^olrka%4-)10&yyNFAy653.y

@@ibcqellcJ^pqbov%M^oq/&yKyHfii0-@ibcqellc?riip^olrka%2.)0-&yyNFAy652-y
@Q^i_rhJ^pqbov%M^oq/&yKyHfii0-Q^i_rhQelokdo^wbop^olrka%2-)/0&yyNFAy6525y

QQebEltifkdTfkayKyBibjbkq^ifpqJlode%3-+2)//+1&yyNFAy653.y
QQebQeolkblcqebBibjbkqpyKyBibjbkq^ifpqPe^os^h%3-+3)//+/&yyNFAy6536y

>Jroh_illa@loormqbopyKyBibjbkq^ifpqJlode%3-+2)//+1&yyNFAy653/y
>QebRkabokb^qeyKyBibjbkq^ifpqRkqo^d%3-+4)//+2&yyNFAy65.5y
>>O^ob?b^kyKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65--y
>Jr`hAfsfkdyKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65.2y
QQebRkabokb^qeyKyDloa^td%3-)/1&yyNFAy65.5y
>QebQloqrobaB^oqeyKyDloa^td%3-)/1&yyNFAy65.6y

@>O^ob?b^kyKyDbq5XAfdbpqba@^o^`lifZclrkafkpfabqeb$Arkd$il`^qbatbpqlcqebQeolkblcqebBibjbkqp^olrka%2.)/5&yyNFAy65--y
Q>O^ob?b^kyKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65--y
>>dfq^qbaPmfofqplcPhvplkdyKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65-1y

@>dfq^qbaPmfofqplcPhvplkdyKyAbpqolv5I^hbPmfofqp^olrkaqebkloqebokm^oqlcphvplkdi^hb%25)/4&yyNFAy65-1y
@QebQloqrobaB^oqeyKyHfii.-QloqrobaB^oqePmfofqp+Prddbpqbail`^qflkp^ob^olrka%31)4-&^ka%34)0/&yyNFAy65.6y

Q>dfq^qbaPmfofqplcPhvplkdyKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65-1y
>?ibppfkdlcFk`fkbo^qrpyKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65-2y
QQebQloqrobaB^oqeyKyDloa^td%3-)/1&yyNFAy65.6y
>B^qfkdA^jk^qflkyKyDloa^td%3-)/1&yyNFAy65/.y

KHfiiBko^dba@orpebop^pvlrnrbpqyKyGrpqhbbm^kbvblrqcloBko^dba@orpebopql`ljmibqbB^qfkdA^jk^qflkfqpe^oaqlcfka^ilqlcqebjfklkbil`^qflkyyNFAy65/.y
>Lper$drk@ovpq^iMltaboyKy@efbcObpb^o`eboH^oqlp%1.+/)11+0&)vlr`^klkiv^``bmqqefpnrbpqfcE^i^^fprkabo>iif^k`b@lkqoliyyNFAy.--43yyLyyIy/3-10/-y
QLper$drk@ovpq^iMltaboyKy@efbcObpb^o`eboH^oqlp%1.+/)11+0&yyNFAy.--43yyLy

@?lavlcBsfabk`byRy/2325yyKyRpbqebXA^jmTllibk?i^khbqZlkqebmvobfkqebI^rdefkdPhrii@lroqv^oa%14)/1&+Qtlldobptfiipm^tk)^kaqebvtfiipq^oqmi^`fkdlo``lompbp^olrkaqebmvob)vlrjrpqmolqb`qqebjtefibqebvalfqyyNFAy660/y
@T^kqba7Wlo_lqeb>asfployKyHfiiWlo_lqeb>asfplo^q%13+1).5+1&).-T^oj^riPe^j^k^olrka%14)/0&^ka.-T^oj^riOb^sbop^olrka%12)//&yyRy/2222yyNFAy661-y
@ObqrokfkdqebC^sloyKyMi^`b.-XHfi$ploolt?^kkbopZqeolrdeqeb_lafbplcT^oj^rildobp^qqebI^rdefkdPhriiOrfkp^olrka%13).5&yyRy/2222yyNFAy660.y

@?ibppfkdlcFk`fkbo^qrpyKyRpbqebXIfsfkdCfobZqlabpqolvqebI^odbErq%4/+1)2-+0-&)qebTbpqbokErq%4-+42)2.+.2&)qebPlrqebokErq%4.+/2)20+/-&^kaqebB^pqbokErq%4/+42)21+4-&^qTfkavobbaSfii^dbyyRy/1134yyNFAy65-2y

QObqrokfkdqebC^sloyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy660.y
Q?lavlcBsfabk`byKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy660/y
>Jbpp^dbqlQbi^^oyKyI^kqobplolcqeb?i^ab%40+5)3/+3&yyNFAy6600y
QJbpp^dbqlQbi^^oyKy>ob`eolk%22+1)35+5&yyNFAy6600y
QT^kqba7Dfpbia^qeb@olkbyKyT^oabkJlf$_ccGfii%21+5)4-+6&yyNFAy6603y
QT^kqba7Wlo_lqeb>asfployKyT^oabkJlf$_ccGfii%21+5)4-+6&yyNFAy661-y
>Qeb@lkploqfrjKbbapVlryKy@lkploqfrjOb`orfqbo%2.+.2)36+42&yyNFAy66.0y

QFJrpqE^sbQebjyKyT^w^q%3.+4)34&yyNFAy.-.-6y
KLmqflk^iNrbpqyKyQebkbuqnrbpq?ofkdJbQebBddfpb^pfivalkbplil)qebe^oam^oqfpdbqqfkdqlqebbddtef`efpsbovqof`hvyyNFAy.-...y
>?ofkdJbQebBddyKyT^w^q%3.+4)34&yyNFAy.-...y
@?ofkdJbQebBddyKyCfopqj^hbprobqlalqefpk^hbaplvlralk$qilpb^kvaro^_fifqvfcvlrafb)kbuqpq^kalkqebobaqo^jmlifkb^karpbfq+kltvlrkbbaqlofdeq`if`hlkqeb$Grjm^Qolk$_rccqlqrokfqlcc^qqebofdeqqfjbqli^kalkqebkbpq)fcvlr$obe^sfkdqolr_ibdlqlvlrqr_b+`lj^kaqvmbfk?ofkdjbqebbdd^kavlrpelria_b^_ibqlt^q`e^dllasfabllkeltqldbqlkqebkbuq+>cqbovlrillqqebbddt^fq0-pb`cloqebJ^qof^`eql^mmb^oqlhfiifqyyNFAy.-...y
Q?ofkdJbQebBddyKyT^w^q%3.+4)34&yyNFAy.-...y

@Tfkaol`J^pqbov%M^oq/&yKyHfii./O^sbklrpTfkaol`p^olrka%2-)3-&yyNFAy6522y
HJroh_illaFks^abopyKyHfiiJroh_illaFks^abopm^qoliifkdqebol^a_bqtbbk%1/)25+4&^ka%/5+2)24+.&qldbqfqbjXJroh_illaFks^pflkMi^kpZqlpq^oqkbtnrbpqyyIy/1226yyNFAy654.y
>Jroh_illaFks^abopyKyRpbqebXJroh_illaFks^pflkMi^kpZql^``bmqnrbpqyyRy/1226yyNFAy654.y

O>bofpI^kafkdyKyArbplrqelcPrkpmofkd%0.)24&yyNFAy66/2y
>J^qqboplcPb`rofqvyKyWbofa%0-+5)25+/&yyNFAy66/2y
QQeb@lkploqfrjKbbapVlryKyDbweb%0.+1)24+4&yyNFAy66.0y
>Pqb^ifkdcoljQefbsbpyKyDbweb%0.+1)24+4&yyNFAy655/y
>D^s^$ufyKyWbofa%0-+5)25+/&yyNFAy66--y
>>Eb^aCriilcFslovyKyPe^aobh%0.+4)23+5&yyNFAy66.1y

QEb@^iibaEfjpbic>iqorfp+++yKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy665/y
>ProsbvqebI^kayKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy666.y
@ProsbvqebI^kayKyQ^ihql>iqorfpqebPrccbobo%/4+1)10+.&^kaq^hb^ofabtfqeqebao^dlkyyNFAy666.y
QProsbvqebI^kayKy>iqorfpqebPrccbobo%/4+1)10+.&yyNFAy666.y
KPhfm?rvfkdQfjbyNFAy65.2y

@Jr`hAfsfkdyKyObqofbsb2XJr`h*ofaabk@lobpZaolmmba_vJr`hPm^tk^olrka%11)15&yyNFAy65.2y
@B^qfkdA^jk^qflkyKyCfkfpeqefpnrbpqklt)hfiiBko^dba@orpebopqldbq.-XBko^dba@orpebo@lobpZ)qebob$p^_rk`e^q%10)2/&^ka%23)2/&yyNFAy65/.y

QJroh_illaFks^abopyKy>ob`eolk%22+2)35+5&yyNFAy654.y
>LoqloJvLiaCofbka+++yKy>ob`eolk%22+2)35+5&yyNFAy6540y

OKbpfkdt^ovP^c^ofyKyFkqebkloqeb^pq`lokbolcqebwlkb%4.)1-&yyNFAy6523y
QTfkaol`J^pqbov%M^oq/&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6522y
>Tfkaol`J^pqbov%M^oq0&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6523y
Q@ibcqellcJ^pqbov%M^oq/&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652-y
>@ibcqellcJ^pqbov%M^oq0&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652.y
QQ^i_rhJ^pqbov%M^oq/&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6525y
>Q^i_rhJ^pqbov%M^oq0&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6526y

QB^qfkdA^jk^qflkyKyDloa^td%3-)/1&yyNFAy65/.y
>Pe^qqbofkdqebSbfiyKyDloa^td%3-)/1&yyNFAy6516y
Q?ibppfkdlcFk`fkbo^qrpyKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65-2y
>QebPmfofqMliirqbayKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65.-y

@QebPmfofqMliirqbayKyAbpqolvT^qllprk$pMliirqbaBppbk`b^ka5I^hbProdbop^q%00)2-&yyNFAy65.-y
@LoqloJvLiaCofbka+++yKyHfiiLoqlolcJroh_illa%0-+1)1/+5&yyNFAy6540y
@PqlmmfkdqebPmob^ayKyRpbqebXQlo`elcIfnrfaCfobZqlabpqolv.-PrkpmofkdSfii^dbo`lompbp^olrka%0.)10&+Qeb`lompbp^obfkpfabqebelrpbpyyRy/123-yyNFAy6541y
@Jroh_illa@loormqbopyKyHfii2Jroh_illaMrqofcfbop^olrka%0-)1-&yyNFAy653/y
@PlisfkdqebMol_ibjyKyHfii.-Jroh_illaP`^sbkdbop^ka2Jroh_illaO^fabop^olrka%0.)1/&yyNFAy6545y
>QebQlqbjlcH^o$a^peyKyHrobk^f@^mqfsb%00)1/&yyNFAy6546y
@QebQlqbjlcH^o$a^peyKyBp`loqqebHrobk^f@^mqfsbyyNFAy6546y

@QebO^s^dba@^o^s^kyKyDbq.-XQbi^^oPrmmiv@o^qbpZ^olrka%/0)/5&+Qebob^obqtlibsbi33Bifqbpol^jfkd^olrkaqebbkqo^k`bqlqebefii+Fcvlrt^fqcloqebjqlm^qe)qebvtfiibkd^dbqebT^oj^riLdobp+Vlr`^kbfqebom^ppqebjlodbqqeb`o^qbplkqebm^qeyyNFAy6623y
@@lohf$pO^kpljyKyDlqlqeb`^sb%/4)/0&^kaq^ihql@lohf%0-)/3&vlralk$qe^sbqlhfiiqebBifqbDr^oa)vlr`^kgrpq@@tfqecb^o)pqrkbq`^kaq^ihql@lohfql`ljmibqbnrbpqyyNFAy6621y
@Tfkaol`J^pqbov%M^oq0&yKyVlrpelria_b^_ibqlplilqefpb^pv)vlr`^kcfkaDrqofmmbo^olrkaqebdo^pp_bclobT^oj^riEfii^olrka%00)0-&yyNFAy6523y
@Q^i_rhJ^pqbov%M^oq0&yKyHfii?^`e$ilo^ka`liib`qefpellc)vlrpelria_b^_ibqlplilqefpnrbpq)ebm^qolip_bqtbbkqebqtlClodb@^jmp%/2)15&)%/4)05&yyNFAy6526y

@Pe^qqbofkdqebSbfiyKyRpbXDloa^td$p?lriaboZqlhfii0-JfkflkplcDrolh^olrka%05)5.&yyRy/12-.yyNFAy6516y
@D^s^$ufyKyHfiiD^s^$uf^q%10)41&lkqlmlc^pj^iiefiikb^oqeb`ovpq^iyyNFAy66--y
@Pqb^ifkdcoljQefbsbpyKyDbq.-XLper$drk@ovpq^iCo^djbkqpZaolmmba_vSfo$^^kfO^fabop^ka>o`^kfpqp+Vlr`^k^iplillqqebjlccqebdolrka+Dllail`^qflkfp^olrka%01)30&yyNFAy655/y
@J^qqboplcPb`rofqvyKyHfii5Slfapm^tkkb^oLper$drk^olrka%06)30&yyNFAy66/2y
@>Eb^aCriilcFslovyKyHfiiTfiaBibhhpclo0uXFslovQrphZ%12)42&)%03)25&)%1/)22&yyNFAy66.1y
@@ibcqellcJ^pqbov%M^oq0&yKyHfii?^kqe^o^ka`liib`qefpelok)ebm^qolipfk^olrkaLper$drk%0.)2.&)%1/)3.&yyNFAy652.y

QJ^qqboplcPb`rofqvyKyWbofa%0-+5)25+/&yyNFAy66/2y
QPqb^ifkdcoljQefbsbpyKyDbweb%0.+1)24+4&yyNFAy655/y
QD^s^$ufyKyWbofa%0-+5)25+/&yyNFAy66--y
Q>Eb^aCriilcFslovyKyPe^aobh%0.+4)23+5&yyNFAy66.1y

OQbi^^oyKyOrkqlQbi^^o%21+/)42+.&y
QPlisfkdqebMol_ibjyKyMlif$irhirhqebTfpbo%21+1)4/+0&yyNFAy6545y
QPqlmmfkdqebPmob^ayKyLqlk_rqebP^db%21+2)4/&yyNFAy6541y
QQebO^s^dba@^o^s^kyKyErkqobppHfj^%21+0)40+3&*jlsbp^olrkaqefp^ob^yyNFAy6623y
QCfbo`bBkbjfbpyKyT^oabkJlf$_ccGfii%21+5)4-+6&yyNFAy.-143yyLy

OKbpfkdt^ovP^c^ofyKyFkqebkloqeb^pq`lokbolcqebwlkb%4.)1-&y
QTfkaol`J^pqbov%M^oq0&yKyPe^al$Cfqw$C^opqofabo%4.+3)1-+3&yyNFAy6523y
Q@ibcqellcJ^pqbov%M^oq0&yKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652.y
QQ^i_rhJ^pqbov%M^oq0&yKyE^oliaI^kb%4.+1)1-+3&yyNFAy6526y
KLmqflk^iNrbpqyKyQebRiqfj^qb?illapmloqfptloqealfkd_rqvlrkbbaebimcolj^qib^pq.jlobmi^vboyyNFAy652/y
>QebRiqfj^qb?illapmloqyKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652/yyLy

QJroh_illa@loormqbopyKyBibjbkq^ifpqJlode%3-+2)//+1&yyNFAy653/y
QQebPmfofqMliirqbayKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65.-y
QPe^qqbofkdqebSbfiyKyDloa^td%3-)/1&yyNFAy6516y
QJr`hAfsfkdyKyBibjbkq^ifpqIl$^m%3-+4)//+1&yyNFAy65.2y

EQbi^^oyRy3615y
@QebRiqfj^qb?illapmloqyLyyKyHfiiQrphbo%11)32&^ka`liib`qXEb^oqlcQrphboZvlrtfiikbbaebimcloqefpnrbpqlqebotfpbphfmfqyyNFAy652/y
QQebRiqfj^qb?illapmloqyKyEbjbqKbpfkdt^ov%4.+2)1-+5&yyNFAy652/yyLy
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
