DugisGuideViewer:RegisterGuide("Blade's Edge Mountains (67-69)", "Borean Tundra (68-71)", "Alliance", "L", function()
return [[
AAA

KFcvlrob^`eibsbi36+++yKyFcvlrob^`eibsbi36_bclobcfkfpefkd?i^ab$pBadbvlr`^kphfmqebobpqlc?i^ab$pBadbJlrkq^fkpnrbpq^kadlpqo^fdeqql?lob^kQrkao^clojlobUM^ka_bqqboobt^oapyyNFAy6461y
CLob_loE^o_lo^dbyKyCrodr%21+/)42+.&yyWyK^do^kayyNFAy6461y
>KlQfjbclo@roflpfqvyKyQfjlqevA^kfbip%1.+0)/5+3&yyNFAy6461yyWyW^kd^j^opey
>Hfiifkdqeb@o^tibopyKyPbkqfkbiJllktefpmbo)rmqebpq^foplrqpfabqeb`^sb%0/+.)6.+/&yyNFAy.-6/4y
@Hfiifkdqeb@o^tibopyKyHfiiqebpmfabopfkpfabqeb`^sb%00)55&yyNFAy.-6/4y

OPvis^k^^oyKyKloqelrqlcqeb`^sb%04)32&yyNFAy.-36-y
>QebAbkJlqeboyKyT^kqbaMlpqbo%03+3)34+0&yyNFAy.-36-y
QKlQfjbclo@roflpfqvyKyHf^ilkKfdeq_i^ab%03)34+5&cfopq_rfiafkdlkqebibcqyyNFAy6461y
>QebBk`ol^`efkdTfiabokbppyKyOfk^Jllkpmofkd%03+0)34+/&yyNFAy.-122y
QHfiifkdqeb@o^tibopyKy@ljj^kaboPhvpe^alt%03+1)33+0&kbuq_rfiafkdqlqebKloqeyyNFAy.-6/4y
>Qeb?illaj^riLdobpyKy@ljj^kaboPhvpe^alt%03+1)33+0&yyNFAy.-2-/y
>J^i^fpbyKyA^o^kbiib%04)32+3&yyNFAy.-222y
>FkqlqebAo^bkbqevpqJfkbyKy?olktvkPqlrqe^jjbo%04+1)32&yyNFAy.-2.-y
>Pqo^kdb?obtyKy?lodofjPqlrqe^jjbo%04+1)31+5&yyNFAy.-2..y
ePvis^k^^oyKyFkkhbbmboPe^rkbppv%02+5)30+5&yyNFAy.-223y

@QebBk`ol^`efkdTfiabokbppyKyHfii./Dolsbpq^ihboIvkubp^olrka%06)4-&yyNFAy.-122y
@J^i^fpbyKy@liib`q.5XMir`hbaI^pee$^kCb^qebopZtef`eaolmcoljjl_pfkSbfiI^pe+Qebbkqo^k`bfp^olrka%02)40&yyNFAy.-222y
QJ^i^fpbyKyI^pee$^kQljb%02)46&yyNFAy.-222y
>P`o^q`ebpyKyI^pee$^kQljb%02)46&yyNFAy.-223y
@P`o^q`ebpyKyRpbqebXCfpqcrilcCb^qebopZlkqebI^pee$^kPmbii@fo`ib^q%02)44&)qebkobqrokqlA^o^kbiib%04)32+3&tfqefk.-jfkrqbpyyRy0-20-yyNFAy.-223y

QQebBk`ol^`efkdTfiabokbppyKyOfk^Jllkpmofkd%03+0)34+/&yyNFAy.-122y
>J^o^rafkdTlisbpyKyOfk^Jllkpmofkd%03+0)34+/&yyNFAy.-123y
QP`o^q`ebpyKyA^o^kbiib%04)32+3&yyNFAy.-223y

@FkqlqebAo^bkbqevpqJfkbyKy@liib`q2XAo^bkbqevpqJfkb@ovpq^ipZlccqebldobpfkqeb`^sb)locoljqebi^odb`ovpq^icloj^qflkp+Qebjfkbbkqo^k`bfp^q%1/)51&yyNFAy.-2.-y
@Pqo^kdb?obtyKyMol`rob..?illaj^ri?orqb_^kb?obtpaolmmba_vldobp^ka^iplclrkafkpfab?orqb_^kbhbdp^olrka%13)44&yyNFAy.-2..y
@Qeb?illaj^riLdobpyKyHfii^kv?illaj^riLdobpfkqebfo`^jm%11)44&yyNFAy.-2-/y

QQeb?illaj^riLdobpyKy@ljj^kaboPhvpe^alt%03+1)33+0&yyNFAy.-2-/y
>Qeb?i^abpmfobLdobpyKy@ljj^kaboPhvpe^alt%03+1)33+0&yyNFAy.-2-1y
QPqo^kdb?obtyKy?lodofjPqlrqe^jjbo%04+1)31+5&yyNFAy.-2..y
>Dbqqfkdqeb?i^abpmfobQ^khbayKy?lodofjPqlrqe^jjbo%04+1)31+5&yyNFAy.-2./y
QFkqlqebAo^bkbqevpqJfkbyKy?olktvkPqlrqe^jjbo%04+1)32&yyNFAy.-2.-y

@J^o^rafkdTlisbpyKyDbq1XQerkaboiloaAfobTlicQ^fipZaolmmba_vQerkaboiloaAfobTlisbp^olrka%2.)32&yyNFAy.-123y
@QebAbkJlqeboyKyHfiiObj^fkqeb`^sb^q%2/)42&yyNFAy.-36-y

OQlpeibv$pPq^qflkyKyRmqebefiiqlqebb^pq%3-)36&yyNFAy.-3-5y
>@ovpq^i@ib^oyKyKf`htfkhibqebJbqol*Dkljb%3-+0)36&yyNFAy.-3-5y
>Mf`hfkdRmPljbMltbo@lksboqbopyKyQlpeibv%3-+2)36&yyNFAy.-251y
>QbpqCifdeq7QebWbmevofrj@^m^`fqlofrjyKyQ^iivW^mk^__bo%3-+0)35+1&yyNFAy.-224y
@QbpqCifdeq7QebWbmevofrj@^m^`fqlofrjyKyPmb^htfqeO^iivW^mk^__bo%3-+/)35+5&^kaebtfiipbkavlrpl^ofkd_^`haltkqebefiiqlO*0ALyyNFAy.-224y
QQbpqCifdeq7QebWbmevofrj@^m^`fqlofrjyKyQ^iivW^mk^__bo%3-+0)35+1&yyNFAy.-224y
>QbpqCifdeq7QebPfkdfkdOfadbyKyQ^iivW^mk^__bo%3-+0)35+1&yyNFAy.-4.-y

@Mf`hfkdRmPljbMltbo@lksboqbopyKyDbq2Bib`qoljbkq^ipclrkalkqebdolrkafkqebbk`^jmjbkq^olrka%24)24&+Lmbkqebmltbo`lksboqbo)rpbqebXMolqlsliq^f`J^dkbql@liib`qloZlkfq)qebkhfiifqyyRy0-323yyNFAy.-251y

QMf`hfkdRmPljbMltbo@lksboqbopyKyQlpeibv%3-+2)36&yyNFAy.-251y
>OfabqebIfdeqkfkdyKyQlpeibv%3-+2)36&yyNFAy.-324y
>OfadbpmfkbJbk^`byKyAfwwvAfk^%3-+/)35+5&yyNFAy.-3/-y
>@rqqfkdVlroQbbqeyKyO^w^hFolkpfabp%3-)35&yyNFAy.-30/y
>Te^q@^jbCfopq)qebAo^hbloqebBdd<yKyCfwfqAl`@il`hql`h%3-+6)35+/&yyNFAy.-3-6y

@QbpqCifdeq7QebPfkdfkdOfadbyKyPfdkXQ^iiv$pT^fsboZqebkpmb^htfqeO^iivW^mk^__bo^q%3-+/)35+5&yyRy0-21-yyNFAy.-4.-y
@OfabqebIfdeqkfkdyKyRpbXObmli^ofwbaJ^dkbqlPmebobZql^_plo_/2ifdeqkfkdpqofhbpcoljqebP`^ibtfkdPbombkqpclrka^olrka%34)40&^kamf`hrm2XP`^ibtfkdIfdeqkfkdDi^kapZyyRy0-5.5yyNFAy.-324y
@OfadbpmfkbJbk^`byKyHfii.-OfadbpmfkbPq^ihbop)qebpbpqb^iqebapmfabop^obefafkd^olrkaO^wloOfadb)pq^oq^q%34)40&^katlohvlrot^vkloqeyyNFAy.-3/-y
@@rqqfkdVlroQbbqeyKyDbq2XBuqo^Pe^omA^ddboj^tQbbqeZaolmmba_vA^ddboj^tI^peq^fi^olrka%31)22&^ka%35)33&yyNFAy.-30/y

@Te^q@^jbCfopq)qebAo^hbloqebBdd<yKyDbqqeb0qvmbplcAo^hbbppbk`b^olrka%30)43&+@if`hlkqebkbqeboao^hbbdd)qebkrpbqebXQbjmlo^iMe^pbJlari^qloZqldbqbfqeboMolql*KbqeboAo^hblo>alibp`bkqKbqeboAo^hb+Qldbqlkblcqebpbrkbbaqlrpbqebjlari^qloqtf`b+J^qrobKbqeboAo^hb*^o`^kb_i^pqfpob^iivab^aiv)plt^q`elrqyyRy0-41/yyNFAy.-3-6y
@@ovpq^i@ib^oyKyHfii.-@ovpq^iCi^vbop^olrka%30)43&yyNFAy.-3-5y

Q@ovpq^i@ib^oyKyKf`htfkhibqebJbqol*Dkljb%3-+0)36&yyNFAy.-3-5y
QOfabqebIfdeqkfkdyKyQlpeibv%3-+2)36&yyNFAy.-324y
>Qo^mmfkdqebIfdeqC^kq^pqf`yKyQlpeibv%3-+2)36&yyNFAy.-341y
>D^rdfkdqebObplk^kqCobnrbk`vyKyKf`htfkhibqebJbqol*Dkljb%3-+0)36&yyNFAy.-261y
QQbpqCifdeq7QebPfkdfkdOfadbyKyQ^iivW^mk^__bo%3-+0)35+1&yyNFAy.-4.-y
QOfadbpmfkbJbk^`byKyAfwwvAfk^%3-+/)35+5&yyNFAy.-3/-y
>Jlobqe^k^MlrkalcCibpeyKyAfwwvAfk^%3-+/)35+5&yyNFAy.-34.y
Q@rqqfkdVlroQbbqeyKyO^w^hFolkpfabp%3-)35&yyNFAy.-30/y
QTe^q@^jbCfopq)qebAo^hbloqebBdd<yKyCfwfqAl`@il`hql`h%3-+6)35+/&yyNFAy.-3-6y

@D^rdfkdqebObplk^kqCobnrbk`vyKy@ib^o^i^odb^ob^^olrka%3-)43&qebkpq^oqaolmmfkdXLp`fii^qfkdCobnrbk`vP`^kkbopZtebobsbovlr`^k+Tlohnrf`hiv^pqebve^sb^peloqqfjblrqyyRy0-4-.yyNFAy.-261y
QD^rdfkdqebObplk^kqCobnrbk`vyKyKf`htfkhibqebJbqol*Dkljb%3-+0)36&yyNFAy.-261y

>QbpqCifdeq7O^w^^k$pI^kafkdyKyQ^iivW^mk^__bo%3-+0)35+1&yyNFAy.-4..y
@QbpqCifdeq7O^w^^k$pI^kafkdyNFAy.-4..yyKyPmb^htfqeO^iivW^mk^__bo%3-+/)35+5&qlrpbqebWbmevofrj@^m^`fqlofrjy
KHfiicibpe_b^pqp+++yKyHfii^kvCfbkaifkdCibpe?b^pqpvlr`ljb^`olppcloJlobqe^k^MlrkalcCibpeyyNFAy.-34.y
@Qo^mmfkdqebIfdeqC^kq^pqf`yKyRpbqebXJriqf*Pmb`qorjIfdeqQo^mZql`^q`e.2O^w^^kfIfdeqLo_p^q%34)10&+Grpqmi^`bqebqo^mrkaboqebifdeqpcivfkdfkqeb^foyyRy0-52/yyNFAy.-341y
QQo^mmfkdqebIfdeqC^kq^pqf`yKyQlpeibv%3-+2)36&yyNFAy.-341y
>PeltQebjDkljbJbo`vyKyQlpeibv%3-+2)36&yyNFAy.-342y
QQbpqCifdeq7O^w^^k$pI^kafkdyKyQ^iivW^mk^__bo%3-+0)35+1&yyNFAy.-4..y

@PeltQebjDkljbJbo`vyKyHfii^cbtjl_p^olrka%33)10&)qebkKburp*Mofk`bO^w^^kpm^tkp^ka^cqbovlrhfiiefjqebX@liib`qflklcPlripZ^mmb^oplsboefp_lavyyNFAy.-342y
@Jlobqe^k^MlrkalcCibpeyKyDbq2XBqebo*BkbodfwbaCibpeZaolmmba_vCfbkaifkdCibpe?b^pqp^olrka%34)11&yyNFAy.-34.y

QPeltQebjDkljbJbo`vyKyQlpeibv%3-+2)36&yyNFAy.-342y
QJlobqe^k^MlrkalcCibpeyKyAfwwvAfk^%3-+/)35+5&yyNFAy.-34.y

CPvis^k^^oyKyOfmMba^ipi^j%3.+.)4-+2&yyNFAy.-124y
QQebAbkJlqeboyKy@ljj^kaboPhvpe^alt%03+1)33+0&yyNFAy.-36-y
QJ^o^rafkdTlisbpyKyOfk^Jllkpmofkd%03+0)34+/&yyNFAy.-123y
>Molqb`qfkdLroLtkyKyOfk^Jllkpmofkd%03+0)34+/&yyNFAy.-124y
@Molqb`qfkdLroLtkyKyPlrqelcqltk)illhclodolsbpbbaifkdplkqebdolrka^karpbXOfk^$p?lrdeZlkqebj%03+6)4.+1&yyRy/662/yyNFAy.-124y
QMolqb`qfkdLroLtkyKyOfk^Jllkpmofkd%03+0)34+/&yyNFAy.-124y
>>AfobPfqr^qflkyKyOfk^Jllkpmofkd%03+0)34+/&yyNFAy.-2-3y

@>AfobPfqr^qflkyKyPlrqefkqeb_illaj^rio^sfkb)rpbXOfk^$pAfjfkrqflkMltaboZlkqeb_illaj^ritlisbp%12)42&yyRy0-/2.yyNFAy.-2-3y

>QebQo^mmfkdplc^Sfkaf`^qloyKySfkaf`^qloSrribbk%11)2.+6&yyNFAy.-2.3y
@QebQo^mmfkdplc^Sfkaf`^qloyKyDbqXSfkaf`^qloSrribbk$p?i^abZaolmmba_vAoldd^j^q%06)2/&^kaXSfkaf`^qloSrribbk$pPefbiaZaolmmba_vJrdalod^q%1/)25&yyRy0-020yyNFAy.-2.3y
QQebQo^mmfkdplc^Sfkaf`^qloyKySfkaf`^qloSrribbk%11)2.+6&yyNFAy.-2.3y
>Dloo$Afj)VlroQfjbE^p@ljb+++yKySfkaf`^qloSrribbk%11)2.+6&yyNFAy.-2.4y
@Dloo$Afj)VlroQfjbE^p@ljb+++yKyHfiiDloo$Afjfkqeb_fd_rfiafkd^q%06+1)16+/&yyRy0-020yyNFAy.-2.4y
@Dbqqfkdqeb?i^abpmfobQ^khbayKyRpbqebX?illaj^ri?orqb_^kbHbdZqldbq2?i^abpmfobLdobpaorkh^olrka%12)2-&yyRy0-020yyNFAy.-2./y
@Qeb?i^abpmfobLdobpyKyHfii^kv0-?i^abpmfobLdobp^olrka%16)16&yyNFAy.-2-1y
QDloo$Afj)VlroQfjbE^p@ljb+++yKySfkaf`^qloSrribbk%11)2.+6&yyNFAy.-2.4y
>Mi^kqfkdqeb?^kkboyKySfkaf`^qloSrribbk%11)2.+6&yyNFAy.-2.5y
H?i^abpmfob@e^jmflkyKyHfii^?i^abpmfob@e^jmflk%1.)13&lo%1-)24&rkqfivlr`liib`qX?i^abpmfob@i^k?^kkboZyyIy0-1.3yyNFAy.-2.5y
@Mi^kqfkdqeb?^kkboyKyEb^aqlqebqltbo^karpbqebX?i^abpmfob@i^k?^kkboZ%13)41&Vlrtfiidbq0t^sbplcldobpfkdolrmplc/*1mbot^sbtfqeqeb^cfk^iclroqet^sbtebobDrokDor_klpepm^tkpyyRy0-1.3yyNFAy.-2.5y

EPvis^k^^oyRy3615yyNFAy.-4./y
QMi^kqfkdqeb?^kkboyKy@ljj^kaboPhvpe^alt%03+1)33+0&yyNFAy.-2.5y
QDbqqfkdqeb?i^abpmfobQ^khbayKy?lodofjPqlrqe^jjbo%04+1)31+5&yyNFAy.-2./y
QQeb?i^abpmfobLdobpyKy@ljj^kaboPhvpe^alt%03+1)33+0&yyNFAy.-2-1y
Q>AfobPfqr^qflkyKyOfk^Jllkpmofkd%03+0)34+/&yyNFAy.-2-3y

>QbpqCifdeq7Orr^kTb^iayKyQ^iivW^mk^__bo%3-+0)35+1&yyNFAy.-4./y
@QbpqCifdeq7Orr^kTb^iayKyPmb^htfqeO^iivW^mk^__bo^q%3-+/)35+5&+Objbj_boql`if`hlkqebXKbqebo*tb^qeboS^kbZtebkcivfkdyyRy0../1yyNFAy.-4./y
>>QfjbcloKbdlqf^qflk+++yKyQobbT^oabk@e^tk%3.+2)06+/&yyNFAy.-35/y
>@ob^qfkdqebMbka^kqyKyQfjblk%3.+3)06+0&yyNFAy.-234y
QQbpqCifdeq7Orr^kTb^iayKyL$J^iivW^mk^__bo%3/+4)1-+0&yyNFAy.-4./y
>@riifkdqebTfiayKyC^o^aobii^%3/+.)04+6&yyNFAy.-420y
eBsbodolsbyKyFkkhbbmbo>bibov^%3/+5)05+0&yyNFAy.-462y
>>A^qbtfqeAlodlhyKy@ljj^kaboE^bmerpPqlkbt^ii%3.+3)05+1&yyNFAy.-462y
>@orpeqeb?illaj^ri@^jmyKyIfbrqbk^kqC^fotb^qebo%3/)05&yyNFAy.-463y
>IfqqibBj_bopyKyJlpptllaqeb>k`fbkq%3-+5)05+1&yyNFAy.-44-y
>Coljqeb>pebpyKyJlpptllaqeb>k`fbkq%3-+5)05+1&yyNFAy.-44.y

@@ob^qfkdqebMbka^kqyKyKloqeb^pqfkSbfiOrr^k)hfii^kvlcqeb^o^hhl^clo3`i^tp)dlqlqebdobbkprjjlkfkd`fo`ib%31)00&)rpbqeb`i^tp)hfiiqebo^sbkyyRy0-4-1yyNFAy.-234y
@>QfjbcloKbdlqf^qflk+++yKyKbdlqf^qbtfqeLsbopbboKr^^o)ebt^ihprm^kaaltkqebm^qeqlqebtbpqlcBsbodolsbjlsfkd_bqtbbkqebpbmlfkqp%3/)12&^ka%30)/5&yyNFAy.-35/y
@@riifkdqebTfiayKyHfii1CbiptlokP`^ibtfkd)1CbiptlokA^ddboj^t)^ka/Cbi@loormqbop^olrka%4-)04&yyNFAy.-420y
@Coljqeb>pebpyKyMi^kqqebpbbapfk0afccbobkqjlrkap+PlrqebokPlfi%4.)//&)@bkqo^iPlfi%4.)/-&^kaKloqebokPlfi%4.).5&yyNFAy.-44.y
@IfqqibBj_bopyKyHfii5P`lo`eFjmp^olrka%4/)/0&yyNFAy.-44-y
>A^j^dbaJ^phyKyQebfqbjXA^j^dbaJ^phZpq^oqpqefpnrbpq*aolmmba_vCbi@loormqbo^olrka%36)00&yyRy0.051yyNFAy.-5.-y

QA^j^dbaJ^phyKyL$J^iivW^mk^__bo%3/+4)1-+0&yyNFAy.-5.-y
>JvpqbovJ^phyKyL$J^iivW^mk^__bo%3/+4)1-+0&yyNFAy.-5./y
QJvpqbovJ^phyKyTfiailoa>kqbi^oflk%3.+2)06&yyNFAy.-5./y
>CbiptlokD^pJ^phyKyTfiailoa>kqbi^oflk%3.+2)06&yyNFAy.-5.6y
Q>QfjbcloKbdlqf^qflk+++yKyQobbT^oabk@e^tk%3.+2)06+/&yyNFAy.-35/y
>+++^ka^Qfjbclo>`qflkyKyQobbT^oabk@e^tk%3.+2)06+/&yyNFAy.-4.0y
>Ml^`efkdcoljMl^`ebopyKyP^jf^Fkhifkd%3.+6)06+2&yyNFAy.-4.4y
Q@ob^qfkdqebMbka^kqyKyQfjblk%3.+3)06+0&yyNFAy.-234y
>TefpmboplcqebO^sbkDlayKyQfjblk%3.+3)06+0&yyNFAy.-3-4y
Q@riifkdqebTfiayKyC^o^aobii^%3/+.)04+6&yyNFAy.-420y
QIfqqibBj_bopyKyJlpptllaqeb>k`fbkq%3-+5)05+1&yyNFAy.-44-y
QColjqeb>pebpyKyJlpptllaqeb>k`fbkq%3-+5)05+1&yyNFAy.-44.y

QCbiptlokD^pJ^phyKyIbdflk@ljjrkf`^qlo%40+0)1-+.&yyRy0.033yyNFAy.-5.6y
>Ab`bfsbqevBkbjvyKyIbdflk@ljjrkf`^qlo%40+0)1-+.&yyNFAy.-5/-y
@Ab`bfsbqevBkbjvyKyHfii1Alljclodb>qqbka^kqp^ka1AlljclodbBkdfkbbop^olrka%40)1-&yyNFAy.-5/-y
QAb`bfsbqevBkbjvyKyIbdflk@ljjrkf`^qlo%40+0)1-+.&yyNFAy.-5/-y
>Vlr$obCfobayKyIbdflk@ljjrkf`^qlo%40+0)1-+.&yyNFAy.-5/.y
H>kdboDr^oayKyHfii>kdboDr^oa%40+2)1-+3&rkqfivlr`liib`q2uX@^jm>kdboHbvZyyIy0.2032yyNFAy.-5/.y
@Vlr$obCfobayKyRpbqeb2hbvpqlnrf`hivrkil`h^ii2L_bifph%40+2)1-+3&^qlk`b)^kahfiiqebAllj`ovbotebkfq^mmb^opyyNFAy.-5/.y

QVlr$obCfobayKyTfiailoa>kqbi^oflk%3.+2)06+2&yyNFAy.-5/.y
>Ab^qe$pAlloyKyTfiailoa>kqbi^oflk%3.+2)06+2&yyNFAy.-6.-y
@Ab^qe$pAlloyKyDlqeolrdeqeb`^sbbkqo^k`bil`^qba^q%21)3/&hbbmdlfkdrkqfivlrob^`eAb^qe$pallo%32)4-&^kalk`bqebobrpbqebXAorfaPfdk^iZyyRy0.430yyNFAy.-6.-y
QAb^qe$pAlloyKyBsbodolsbAorfayyNFAy.-6.-y
>E^osbpqfkdqebCbi>jjrkfqflkyKyBsbodolsbAorfayyNFAy.-6-1y
@E^osbpqfkdqebCbi>jjrkfqflkyKy@liib`q2uXCbi@^kklk_^iiZcolj^kvKM@fkAb^qe$pAllo%30+1)33+4&yyNFAy.-6-1y
QE^osbpqfkdqebCbi>jjrkfqflkyKyRpbqebAorfapfdk^iql`^iiBsbodolsbAorfayyRy0.430yyNFAy.-6-1y
>Cfob>qTfiiyKyBsbodolsbAorfayyNFAy.-6..y
@Cfob>qTfiiyKyRpbqebKloqebok@^kklk%3.)3-&Plrqebok@^kklk%32)35&qlabpqolvqebd^qbpyyNFAy.-6..y
QCfob>qTfiiyKyRpbqebXAorfaPfdk^iZcloBsbodolsbAorfayyRy0.430yyNFAy.-6..y
>QebElrka*J^pqboyKyBsbodolsbAorfayyNFAy.-6./y
@QebElrka*J^pqboyKyRpbXBsbodolsbT^kaZqlebimvlrhfiiqebElrkaj^pqbo%3/)3.&yyRy0.5-6yyNFAy.-6./y

QQebElrka*J^pqboyKyTfiailoa>kqbi^oflk%3.+2)06+2&yyNFAy.-6./y
@Ml^`efkdcoljMl^`ebopyKyDbq2XTvoj`riqKbqpZaolmmba_vTvoj`riqMl^`ebop^olrka%26)03&yyNFAy.-4.4y
@+++^ka^Qfjbclo>`qflkyKyHfii.-Tvoj`riqEbtbop^olrka%26)03&yyNFAy.-4.0y
>AfaVlrDbqQebKlqb<yKyQebfqbjXJbbqfkdKlqbZpq^oqpqefpnrbpq*aolmmba^olrka%3-)04&yyRy0../-yyNFAy.-4.6y

@>A^qbtfqeAlodlhyKyHfiiAlodlhlkqebpb`lkacillolcqeb_rfiafkd^q%21+4)/1+3&yyNFAy.-462y
@@orpeqeb?illaj^ri@^jmyKyHfii.-?illaj^riJ^ribop^ka2?illaj^riT^oil`hp^q%23)/2&^olrkaqeb`^jmyyNFAy.-463y

Q>A^qbtfqeAlodlhyKy@ljj^kaboE^bmerpPqlkbt^ii%3.+3)05+1&yyNFAy.-462y
>C^slolcqebDolkkyKyQebfqbjXDlodolj$pC^sloZpq^oqpqebnrbpq*aolmmba_vAlodlh^q%21+4)/1+3&yyRy0.030yyNFAy.-464y
QC^slolcqebDolkkyKy@ljj^kaboE^bmerpPqlkbt^ii%3.+3)05+1&yyNFAy.-464y
>M^vqeb?^olk^SfpfqyKy@ljj^kaboE^bmerpPqlkbt^ii%3.+3)05+1&yyNFAy.-465y
Q@orpeqeb?illaj^ri@^jmyKyIfbrqbk^kqC^fotb^qebo%3/)05&yyNFAy.-463y
Q+++^ka^Qfjbclo>`qflkyKyQobbT^oabk@e^tk%3.+2)06+/&yyNFAy.-4.0y
QAfaVlrDbqQebKlqb<yKyQobbT^oabk@e^tk%3.+2)06+/&yyNFAy.-4.6y
>TvojphriiT^q`eboyKyQobbT^oabk@e^tk%3.+2)06+/&yyNFAy.-561y
QMl^`efkdcoljMl^`ebopyKyP^jf^Fkhifkd%3.+6)06+2&yyNFAy.-4.4y
>TebimplcqebTvoj`riqyKyP^jf^Fkhifkd%3.+6)06+2&yyNFAy.-414y

QM^vqeb?^olk^SfpfqyKy?^olkP^_ibj^kb%20+.)1.&yyNFAy.-465y
>Fkqlqeb@erokfkdDri`eyKy?^olkP^_ibj^kb%20+.)1.&yyNFAy.-466y
@Fkqlqeb@erokfkdDri`eyKyDbq4X@orpq?ropqboSbkljDi^kapZ^olrka%15)10&yyNFAy.-466y
QFkqlqeb@erokfkdDri`eyKy?^olkP^_ibj^kb%20+.)1.&yyNFAy.-466y
>Dllakfdeq)DolkkyKy?^olkP^_ibj^kb%20+.)1.&yyNFAy.-5--y
@Dllakfdeq)DolkkyKyPqb^iXDoriil`$pP^`hZ^q%3-+5)14+5&+RpbXP^_ibj^kb$pPibbmfkdMltaboZlkefj)do^_qebp^`h^kaorkyyRy0.1-0yyNFAy.-5--y
QDllakfdeq)DolkkyKy?^olkP^_ibj^kb%20+.)1.&yyNFAy.-5--y
>Fq$p^Qo^myKy?^olkP^_ibj^kb%20+.)1.&yyNFAy.-5-.y

QFq$p^Qo^myKy@ljj^kaboE^bmerpPqlkbt^ii%3.+3)05+1&yyNFAy.-5-.y
>DlodoljqebAo^dlk*B^qboyKy@ljj^kaboE^bmerpPqlkbt^ii%3.+3)05+1&yyNFAy.-5-/y
>Pi^rdeqbo^q?lriabo$jlhyKyIfbrqbk^kqC^fotb^qebo%3/)05&yyNFAy.-5-0y

QTvojphriiT^q`eboyKyT^q`eboJllkpe^ab%2-+.)03+.&yyNFAy.-561y
>Ilkdq^fifpqebIvk`emfkyKyT^q`eboJllkpe^ab%2-+.)03+.&yyNFAy.-560y
@Ilkdq^fifpqebIvk`emfkyKyHfiiAo^^`^Ilkdq^fi^q%13)0/&fkqeb`^sbyyNFAy.-560y
QIlkdq^fifpqebIvk`emfkyKyT^q`eboJllkpe^ab%2-+.)03+.&yyNFAy.-560y
>Jbbqfkd^qqeb?i^`htfkd@lsbkyKyT^q`eboJllkpe^ab%2-+.)03+.&yyNFAy.-4//y

@TefpmboplcqebO^sbkDlayKyHfiiDofpek^^o^hhl^^q%3.+2)06+2&)qebkcfkaqebpeofkbp+CfopqMolmeb`v%1-).4&)Pb`lkaMolmeb`v%1/)//&)QefoaMolmeb`v%1.).6&^kaClroqeMolmeb`v%1-)/0&+Qebcfopq^kapb`lkamolmeb`v$p^oblkqlmlclkblcqebqobbqltbopyyNFAy.-3-4y
>QebQorqeRklo_bayRy0.156yyKyQebfqbjXLo_lcqebDofpek^Zpq^oqpqefpnrbpq*aolmmba_v^kvlcqebDofpek^^o^hhl^p^olrka%1-)/.&yyNFAy.-5/2y
@Pi^rdeqbo^q?lriabo$jlhyKyHfii2?lriabo$jlh?orqbp^ka0?lriabo$jlhPe^j^k^olrka%/6)/1&yyNFAy.-5-0y
@DlodoljqebAo^dlk*B^qboyKy@liib`q0qlqbjp^olrka%0-)//&^kadlqlqeb^iqbo^q%0-)//&+Mi^`bXP^_ibj^kb$pQo^mZ)Dlodoljtfii^mmb^ofkqebi^odb`ib^ofkd)t^ihqlfq^kadbqhfiiba_vqebqo^m+Qebkmi^`bqebqlqbjpfkqebqo^myyRy0.421yyNFAy.-5-/y

@TebimplcqebTvoj`riqyKyRpbqebX?i^`htebimKbqZql`^mqrob.-XTvoj`riq?i^`htebimpZclrkafkqeb`^sb^q%0.)0/&+Vlr`^kqob^alkqebbddpqlpm^tkjlobyyRy0../6yyNFAy.-414y
HTvoj`riqclo@lpqrjbyKyHfiiTvoj`riqrkqfivlrdbq2uX@lpqrjbP`o^mpZ%0-)0.&yyIy0../2yyNFAy.-4//y
KFjmloq^kqKlqbyKy@lpqrjbafpdrfpbtfii_ob^hfcvlr?ifkh%J^db&loqovqlal^kvJfkfkdfkpfabyyNFAy.-4//y
@Jbbqfkd^qqeb?i^`htfkd@lsbkyKyRpbqebX@lpqrjbP`o^mpZorkfkqlqeb`^sb^kahbbmofdeqql%0/)04&Hlimefpfpfk^kllhlkqebofdeqkb^oqebbkalcqeb`^sbyyRy0../.yyNFAy.-4//y

EBsbodolsbyRy3615yyNFAy.-5/6y
QJbbqfkd^qqeb?i^`htfkd@lsbkyKyQobbT^oabk@e^tk%3/)06+2&yyNFAy.-4//y
QTebimplcqebTvoj`riqyKyP^jf^Fkhifkd%3.+6)06+2&yyNFAy.-414y
QQebQorqeRklo_bayKyQobbT^oabk@e^tk%3.+2)06+/&yyNFAy.-5/2y
>Qobb_libJrpqHkltyKyQobbT^oabk@e^tk%3.+2)06+/&yyNFAy.-5/6y
QTefpmboplcqebO^sbkDlayKyQfjblk%3.+3)06+0&yyNFAy.-3-4y
QDlodoljqebAo^dlk*B^qboyKy@ljj^kaboE^bmerpPqlkbt^ii%3.+3)05+1&yyNFAy.-5-/y
>?^olkP^_ibj^kbE^pObnrbpqbaVlroMobpbk`byKy@ljj^kaboE^bmerpPqlkbt^ii%3.+3)05+1&yyNFAy.-5.5y
QPi^rdeqbo^q?lriabo$jlhyKyIfbrqbk^kqC^fotb^qebo%3/)05&yyNFAy.-5-0y

QQobb_libJrpqHkltyKyQobb_lib%03)//&yyNFAy.-5/6y
>Bulo`fpfkdqebQobbpyKyQobb_lib%03)//&yyNFAy.-50-y
@Bulo`fpfkdqebQobbpyKy@liib`q2XDofpek^qeLo_pZ^olrka%1.)/.&^ka2XAfobMfkcb^qebopZaolmmba_vAfobO^sbkp^olrka%06)/5&+@lj_fkbqebfqbjp)dbqfko^kdblc^Ib^c_b^oa^karpblkb+Hfii2Hlf*HlfPmfofqp)alk$qhfiiqebib^c_b^oayyRy0.2.5yyNFAy.-50-y
QBulo`fpfkdqebQobbpyKyQobb_lib%03)//&yyNFAy.-50-y
Q?^olkP^_ibj^kbE^pObnrbpqbaVlroMobpbk`byKy?^olkP^_ibj^kb%20+.)1.&yyNFAy.-5.5y
KLmqflk^iNrbpqyKyJ^pp^`ob^qDorri$pI^fofplmqflk^i)vlr`^k`ljmibqbqefpplilclo^qlklcUM_rqfqtfiiq^hbvlr^tefib)Peltaltkfpqebcliiltrm^kadfsbp^kf`bobt^oa_rqvlrtfiikbba^qib^pq.lqebomi^vboqlebimvlrtfqeAMPyyNFAy.-5-2y
>J^pp^`ob^qDorri$pI^foyKy?^olkP^_ibj^kb%20+.)1.&yyNFAy.-5-2y
@J^pp^`ob^qDorri$pI^foyKy>iijl_pcloqefpnrbpq^obbifqbpplm^fofkdrmtfqe^cbtlqebopfp^dllafab^+Qebkbbaba^ob^fpqlqebkloqeb^pq^qDorri$pI^fo+Hfiiqebkbbabajl_p^olrka%3/)//&^kaqebkcfkaCfkdoljfkpfab^qltbo^q%33).6&y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
