DugisGuideViewer:RegisterGuide("Netherstorm (68-70 |cfff0c502Optional|r)", "Shadowmoon Valley (68-70 |cfff0c502Optional|r)", "Alliance", "L", function()
return [[
AAA

OKbqebopqlojyKyColjBsbodolsbq^hbqebm^qeb^pqrmqlm)qebkdlkloqe^kacliiltqebm^qeyyNFAy.-.50y
>LccQl>ob^2/yKyKbqebolildfpq@lmmbokf`hbip%/.+5)22+3&yyNFAy.-.50y

O>ob^2/yKy?^`haltkqebol^a%0/)3/&yyNFAy.-01/y
>Pb`rofkdqebPe^ibphfkPe^ibyKy?llqp%0/+0)30+6&yyNFAy.-01/y
QLccQl>ob^2/yKyOl`hbq*@efbcCrpbi^db%0/+4)31+6&yyNFAy.-.50y
>Vlr$obEfobayKyOl`hbq*@efbcCrpbi^db%0/+4)31+6&yyNFAy.-.53y
e>ob^2/yKyFkkhbbmboObjfAlalpl%0/+/)31+1&yyNFAy.-.40y
>J^k^clodb?$k^^oyKyP`ovbolkiv)qf`hqefppqbmfcqefpnrbpqfpklq^s^fi^_ibqlvlr+Pmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy.-.56y
>Afpqo^`qflk^qJ^k^clodb?$k^^oyKy>ialolkiv)qf`hqefppqbmfcqefpnrbpqfpklq^s^fi^_ibqlvlr+Bu^o`eLobifp%0/+.)31+/&yyNFAy.-/1.y
>Qeb>o`ej^db$pPq^ccyKyO^s^katvo%0.+1)33+/&yyNFAy.-.40y

>Ob`e^odfkdqeb?^qqbofbpyKy?lq*Pmb`f^ifpq>iibv%0.+2)23+3&yyNFAy.-.6-y
>J^ohSfp>ifsbyKyJ^uu>+JfiiflkJh+S%0/+.)21+.&yyNFAy.-.6.y
@J^ohSfp>ifsbyKyB^pvqlplil)bp`loqJ^ohStefibq^hfkdaltkqebdelpqpqe^q^ob^iob^avfkqeb`fqv%0.)23&yyNFAy.-.6.y
@Vlr$obEfobayKy@liib`q.-XBqeboifqefrjJ^qofu@ovpq^ipZ^olrka%0/)21&+Qebv^oboba^kadiltfkdyyNFAy.-.53y
@Ob`e^odfkdqeb?^qqbofbpyKyCfkame^pberkqbop^olrka%/5)2.&^ka_ofkdqebjaltkql^_lrq/2")qebkrpbqebX?^qqbovOb`e^odfkd?i^pqboZrkqfiqebjl_$pk^jb`e^kdbpqlao^fkbame^pberkqbo+Vlrtlk$qdbq`obafqcloqebhfiirkqfiqebk^jb`e^kdbpyyRy/5036yyNFAy.-.6-y
QJ^ohSfp>ifsbyKy?lq*Pmb`f^ifpq>iibv%0.+2)23+3&yyNFAy.-.6.y
QOb`e^odfkdqeb?^qqbofbpyKy?lq*Pmb`f^ifpq>iibv%0.+2)23+3&yyNFAy.-.6-y
@Pb`rofkdqebPe^ibphfkPe^ibyKyDbq2XPe^ibphfkPe^ibZaolmmba_vPe^ibphfkCi^vbop^olrka%/6)32&yyNFAy.-01/y

QPb`rofkdqebPe^ibphfkPe^ibyKy?llqp%0/+0)30+6&yyNFAy.-01/y
>Qe^qIfqqibBuqo^Hf`hyKy?llqp%0/+0)30+6&yyNFAy.-.66y
QVlr$obEfobayKyOl`hbq*@efbcCrpbi^db%0/+4)31+6&yyNFAy.-.53y
>Fks^ir^_ib>ppbqW^mmfkdyKyOl`hbq*@efbcCrpbi^db%0/+4)31+6&yyNFAy.-/-0y
>ObmloqqlBkdfkbbofkdyKyOl`hbq*@efbcCrpbi^db%0/+4)31+6&yyNFAy.-//2y
QObmloqqlBkdfkbbofkdyKy@efbcBkdfkbboQobm%0/+2)33+4&yyNFAy.-//2y
>Bppbk`bcloqebBkdfkbpyKy@efbcBkdfkbboQobm%0/+2)33+4&yyNFAy.-//1y

@Bppbk`bcloqebBkdfkbpyKyHfiiqebJ^k^To^fqepqldbq4XJ^k^To^fqeBppbk`bpZ^olrka%04)26&yyNFAy.-//1y
@Qe^qIfqqibBuqo^Hf`hyKyDbq2XKbqeboO^vPqfkdbopZaolmmba_vKbqeboO^vp^olrka%12)4/&yyNFAy.-.66y

QQe^qIfqqibBuqo^Hf`hyKy?llqp%0/+0)30+6&yyNFAy.-.66y
QBppbk`bcloqebBkdfkbpyKy@efbcBkdfkbboQobm%0/+2)33+4&yyNFAy.-//1y
>Bibjbkq^iMltboBuqo^`qflkyKy@efbcBkdfkbboQobm%0/+2)33+4&yyNFAy.-//3y

@J^k^clodb?$k^^oyKyDbqqebX?$k^^oMboplkkbiOlpqboZcolj@^mq^fk>o^qevk%/4+4)32+/&yyNFAy.-.56y
@Afpqo^`qflk^qJ^k^clodb?$k^^oyKyHfii5PrkcrovJ^dfpqbop^ka5Prkcrov?illat^oabop^olrka%/2)4-&yyNFAy.-/1.y
@Bibjbkq^iMltboBuqo^`qflkyKyDbq2XBibjbkq^iMltbopZrpfkdqebXBibjbkq^iMltboBuqo^`qloZlkPrkabobaOrj_iboploT^om>__bo^qflkp^olrka%0/)44&+Lk`bhfiiba)illhcloqeb_irb`vpq^ilkqebdolrkayyNFAy.-//3y
@Fks^ir^_ib>ppbqW^mmfkdyKyRpbqebXRiqo^Ab`lkplila^qflkW^mmboZlkqeb1jb`e^kf`^i`lkqo^mqflkp)^qqebpbil`^qflkp7%1.+-0)40+4.&)%1.+1/)4.+5/&)%1-+/4)4/+6.&)%1/+2/)4/+./&yyNFAy.-/-0y
@Qeb>o`ej^db$pPq^ccyKyPm^tkp^olrka%1-)4/&+GrpqrpbqebX@lkgrofkdMltaboZqlprjjlkefjfkqeb`bkqbolcqeb`fo`ibyyRy/6/-4yyNFAy.-.40y

QFks^ir^_ib>ppbqW^mmfkdyKyIb^aP^mmbo?i^pqcfwwib%01+.)35+.&yyNFAy.-/-0y
>Ao+?lljyKyIb^aP^mmbo?i^pqcfwwib%01+.)35+.&yyNFAy.-//.y
QBibjbkq^iMltboBuqo^`qflkyKy@efbcBkdfkbboQobm%0/+2)33+4&yyNFAy.-//3y
QQeb>o`ej^db$pPq^ccyKyO^s^katvo%0.+1)33+/&yyNFAy.-.40y
>Ob_rfiafkdqebPq^ccyKyO^s^katvo%0.+1)33+/&yyNFAy.-0--y
QAfpqo^`qflk^qJ^k^clodb?$k^^oyKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-/1.y
>Jb^profkdT^omBkbodfbpyKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-0.0y
QJ^k^clodb?$k^^oyKyPmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy.-.56y
>>ppfpqfkdqeb@lkploqfrjyKyPmvj^pqboQe^ilafbk%0/+-)31+.&+Fcvlr$sb^iob^av^``bmqba@lkploqfrj@ovpq^i@liib`qflkaolmfqql^``bmqqefpyyNFAy.-/31y
>K^^orQb`eklildvyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-/10y
Q>ppfpqfkdqeb@lkploqfrjyKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/31y
>@lkploqfrj@ovpq^i@liib`qflkyKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/32y

@Ao+?lljyKyHfiiAo+?llj^q%02+-)26+5&+Vlr`^k_lj_efjrpfkdX?llj$pAlljZcoljlkqlmlcqeb_^oobiptfqelrqdbqqfkdefqlo^ddol$ayyRy/61/6yyNFAy.-//.y
@Ob_rfiafkdqebPq^ccyKyDbq1XCi^tibpp@ovpq^iPe^oapZcoljAfpbj_lafbaSfkaf`^qlop)Bu^o`ep^kaMolqb`qlop^qqebBkh^^qOrfkp%00)20&yyNFAy.-0--y

QOb_rfiafkdqebPq^ccyKyO^s^katvo%0.+1)33+/&yyNFAy.-0--y
>@ropblcqebSflibqQltboyKyO^s^katvo%0.+1)33+/&yyNFAy.-.41y
QAo+?lljyKyIb^aP^mmbo?i^pqcfwwib%01+.)35+.&yyNFAy.-//.y

@Jb^profkdT^omBkbodfbpyKyRpbqebXT^om*>qqrkbaLo_Ztebobqebmfmbpdlfkqlqebdolrkafkqefploabo7Kloqe%/2)3-&)Tbpq%/-)34&)Plrqe%/-)4.&^kaB^pq%/5)4.&yyRy/60/1yyNFAy.-0.0y
QK^^orQb`eklildvyKy?$k^^o@lkqoli@lkplib%/0+/)35+.&fkpfabqeb_rfiafkdyyNFAy.-/10y
>?$k^^o@lkplibQo^kp`ofmqflkyKy?$k^^o@lkqoli@lkplib%/0+/)35+.&yyNFAy.-/12y
@@lkploqfrj@ovpq^i@liib`qflkyKyHfiiMbkq^qe^olk^q>ohilkOrfkp%1/)40&qldbq^kX>ohilk@ovpq^i>oqfc^`qZyyNFAy.-/32y

>KbbapJlob@lt_biiyKyQe^abii%24+4)52+-&yyNFAy.-001y
>Fkafpmbkp^_ibQllipyKy>mmobkqf`b>kaobqe^k%24+4)52+/&yyNFAy.-00.y
>J^ibslibkqObjk^kqpyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-.51y
Q@ropblcqebSflibqQltboyKyRpbX>o`ej^dbS^odlqe$pPq^ccZqlprjjlkFj^dblc>o`ej^dbS^odlqe*`^k_bcolj^kvil`^qflkyyRy/5122yyNFAy.-.41y
>QebPfdfilcHo^prpyKyRpbX>o`ej^dbS^odlqe$pPq^ccZqlprjjlkFj^dblc>o`ej^dbS^odlqe*`^k_bcolj^kvil`^qflkyyNFAy.-.55y
>QebRkbkafkdFks^pflkyKyIfbrqbk^kq*Plo`boboJloo^k%24+2)53+0&yyNFAy.-010y
>>C^qbTlopbQe^kAb^qeyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-.52y

H>_grofpq?bij^o^yKyPlrqelcqebqltbo%22)53&yyIy/6/01yyNFAy.-0-2y
>>_grofpq?bij^o^yKyPq^oqpcoljX?bij^o^$pQljbZaolmmba_v>_grofpq?bij^o^%22)53&yyRy/6/01yyNFAy.-0-2y
H?^qqib*J^dbA^qeof`yKyFkpfabqebqltke^ii%3-+2)54+5&yyIy/6/00yyNFAy.-.5/y
>?^qqib*J^dbA^qeof`yKyPq^oqpcoljXA^qeof`$p?i^abZaolmmba_v?^qqib*J^dbA^qeof`%3-+2)54+5&yyRy/6/00yyNFAy.-.5/y
@Fkafpmbkp^_ibQllipyKyHfiiHfofk$S^o>mmobkqf`b$p^olrka%3-)51&qldbqqebXPjfqefkdE^jjboZyyNFAy.-00.y
H@lkgroboIrjfko^qeyKyClrka^q%3-+-)52+0&yyIy/6/02yyNFAy.-0-3y
>@lkgroboIrjfko^qeyKyPq^oqpcoljXIrjfko^qe$pJ^kqibZaolmmba_v@lkgroboIrjfko^qe%3-+-)52+0&yyRy/6/02yyNFAy.-0-3y
H@leifbkColpqtb^sboyKyIl`^qba^q%26)53&yyIy/6/03yyNFAy.-0-4y
>@leifbkColpqtb^sboyKyPq^oqpcoljX@leifbk$p@^mZaolmmba_v@leifbkColpqtb^sbo%26)53&yyRy/6/03yyNFAy.-0-4y

QKbbapJlob@lt_biiyKy?bppv)clrka^olrka%26)45&yyNFAy.-001y
>Tebkqeb@ltp@ljbEljbyKy?bppv)clrka^olrka%26)45&yyNFAy.-004y
@Tebkqeb@ltp@ljbEljbyKyBp`loq?bppv%26)45&+Peb`^kq^hb^ilqlcefqpyyNFAy.-004y
QTebkqeb@ltp@ljbEljbyKyQe^abii%24+4)52+-&yyNFAy.-004y
QFkafpmbkp^_ibQllipyKy>mmobkqf`b>kaobqe^k%24+4)52+/&yyNFAy.-00.y
>J^pqboPjfqeOelkprpyKy>mmobkqf`b>kaobqe^k%24+4)52+/&yyNFAy.-00/y

@?^qqib*J^dbA^qeof`yKyObqrokXA^qeof`$p?i^abZqlefptb^mlko^`h)cfopqelrpblkqebibcq%23+6)53+5&yyRy/502.yyNFAy.-.5/y
@@lkgroboIrjfko^qeyKyObqrokXIrjfko^qe$pJ^kqibZqlefpAobppbo+Il`^qbaqtlelrpbprm)^_olhbkelrpblkqebibcq%23+1)54+5&yyRy/502/yyNFAy.-0-3y
@@leifbkColpqtb^sboyKyObqrokX@leifbk$p@^mZqlqebCllqil`hbo+QebelrpbfpIpe^mba^kaqebcllqil`hbofpfkqebkloqebok`lokbo^jlkdpqqe^qgrkh%22)54&yyRy/5020yyNFAy.-0-4y
@QebRkbkafkdFks^pflkyKyCfka^XJ^k^?lj_Co^djbkqZofdeqfkcolkqlcqebelrpb%22)54&+Fqillhpifhb^_fdolrka_ri_yyNFAy.-010y
@>_grofpq?bij^o^yKyObqrokqeb_llhqlfqp?llhpebicfkqeb_olhbkelrpbqlqebkloqe%22+2)53+2&+RpbX?bij^o^$pQljbZyyRy/5003yyNFAy.-0-2y
@>C^qbTlopbQe^kAb^qeyKyHfii.-J^dbpi^vbop^ka.-J^k^Pbbhbop^olrka%24)52&yyNFAy.-.52y
@J^ibslibkqObjk^kqpyKyHfii/-PbsbobaPmfofqpfkqeb_rfiafkdp^olrka%24)6-&yyNFAy.-.51y

QQebRkbkafkdFks^pflkyKyIfbrqbk^kq*Plo`boboJloo^k%24+2)53+0&yyNFAy.-010y
>Mlqbkqf^iBkbodvPlro`byKyIfbrqbk^kq*Plo`boboJloo^k%24+2)53+0&yyNFAy.-/06y
Q>C^qbTlopbQe^kAb^qeyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-.52y
QJ^ibslibkqObjk^kqpyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-.51y
>Qeb>kk^iplcHfofk$S^oyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-0./y
Q?^qqib*J^dbA^qeof`yKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-.5/y
Q@lkgroboIrjfko^qeyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-0-3y
Q@leifbkColpqtb^sboyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-0-4y
Q>_grofpq?bij^o^yKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-0-2y

@Qeb>kk^iplcHfofk$S^oyKyHfii?^qqib*J^dbA^qeof`%3-)55&qldbqqebX>kk^iplcHfofk$S^oZcoljqebqltke^iiyyNFAy.-0./y
@J^pqboPjfqeOelkprpyKyHfiiOelkprpteljol^jp^olrka%3-)52&+Sbovnrf`hob*pm^tkqfjboyyNFAy.-00/y

QQeb>kk^iplcHfofk$S^oyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-0./y
>Pb^o`efkdcloBsfabk`byKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-0.3y
QJ^pqboPjfqeOelkprpyKy>mmobkqf`b>kaobqe^k%24+4)52+/&yyNFAy.-00/y
QPb^o`efkdcloBsfabk`byKyKb`olj^kqf`Cl`rp%3-+0)45+-&yyNFAy.-0.3y
>>IfkdbofkdPrpmf`flkyKyKb`olj^kqf`Cl`rp%3-+0)45+-&yyNFAy.-0.1y
@>IfkdbofkdPrpmf`flkyKyDbq.-XIl^qepljbObjk^kqpZ+>ddolQlojbkqbaPlriploQlojbkqba@fqfwbkp%3-)5.&qldbqqebjqlqo^kpclojfkqlHfofk$S^oDelpqploHfofk$S^oPmb`qobp*aolmo^qbfp_bqqbotfqeqebdelpqpyyNFAy.-0.1y
Q>IfkdbofkdPrpmf`flkyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-0.1y
>@^mqrofkdqebMevi^`qbovyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-0.6y
@@^mqrofkdqebMevi^`qbovyKyDbqXK^_bofrp$pMevi^`qbovZfkqebjfaaiblrqelrpb%26+6)5-+1&yyNFAy.-0.6y
Q@^mqrofkdqebMevi^`qbovyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-0.6y

@Mlqbkqf^iBkbodvPlro`byKyDbq.-XBkbodvFpli^qflk@r_bpZ^olrka%2/)5/&yyNFAy.-/06y
@QebPfdfilcHo^prpyKyDbqqebXPfdfilcHo^prpZcoljPmbii_fkaboJ^ov^k^^q%2.)5/&+Vlr$iipbbebot^ihfkd^olrkaqebqbkqpyyNFAy.-.55y
QQebPfdfilcHo^prpyKyRpbX>o`ej^dbS^odlqe$pPq^ccZqlprjjlkFj^dblc>o`ej^dbS^odlqe*`^k_bcolj^kvil`^qflkyyRy/5122yyNFAy.-.55y
>Ho^prp$p@ljmbkafrjyKyRpbX>o`ej^dbS^odlqe$pPq^ccZqlprjjlkFj^dblc>o`ej^dbS^odlqe*`^k_bcolj^kvil`^qflkyyNFAy.-.6/y

QMlqbkqf^iBkbodvPlro`byKyIfbrqbk^kq*Plo`boboJloo^k%24+2)53+0&yyNFAy.-/06y
>?rfiafkd^MbofjbqboyKyIfbrqbk^kq*Plo`boboJloo^k%24+2)53+0&yyNFAy.-/1-y
@Ho^prp$p@ljmbkafrjyKyDbqHo^prp$p@ljmbkafrj@e^mqbop+@e^mqbo.*%25+3)56+/&+@e^mqbo/*%24+2)56+3&+@e^mqbo0*%25+5)54+6&+Qebv^ob^iifklkbolljelrpbpyyNFAy.-.6/y
QHo^prp$p@ljmbkafrjyKyRpbX>o`ej^dbS^odlqe$pPq^ccZqlprjjlkFj^dblc>o`ej^dbS^odlqe*`^k_bcolj^kvil`^qflkyyRy/5122yyNFAy.-.6/y
>Rkil`hfkdqeb@ljmbkafrjyKyRpbX>o`ej^dbS^odlqe$pPq^ccZqlprjjlkFj^dblc>o`ej^dbS^odlqe*`^k_bcolj^kvil`^qflkyyNFAy.-0-.y

@?rfiafkd^MbofjbqboyKyRpbqebXOrkb>`qfs^qflkAbsf`bZ^qqeb0orkbp7B^pq%26+/)52+0&+KloqeB^pqrmqeb_fdefii%24+1)5/+6&^kaTbpq%21+0)53+.&+Vlr^obillhfkdclo_irb)pbjf*qo^kpm^obkq)`lfk*illhfkdqefkdpqe^qe^kdfkqeb^foyyRy/54/2yyNFAy.-/1-y
Q?rfiafkd^MbofjbqboyKyIfbrqbk^kq*Plo`boboJloo^k%24+2)53+0&yyNFAy.-/1-y
>Qlo`efkdPrkcrovEliayKyIfbrqbk^kq*Plo`boboJloo^k%24+2)53+0&yyNFAy.-/00y
>QebPrkcrovD^oofplkyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-///y

@Qlo`efkdPrkcrovEliayKyAbpqolv1Prkcrov?^iifpq^p^ka1PrkcrovQbkqp%23)5-&+Vlrlkivkbbalkbqlo`etef`eaolmpcoljqebPrkcrovCi^jbhbbmbop+Vlr`^kqlo`eqebp^jbqbkq^ka_^iifpq^j^kvqfjbp)qebvobpm^tkc^pqyyRy/522-yyNFAy.-/00y
@QebPrkcrovD^oofplkyKyHfii.-Prkcrov>o`ebop^olrka%22)45&yyNFAy.-///y
@Rkil`hfkdqeb@ljmbkafrjyKyHfiiPmbiiob^sboJ^o^qebiib^olrka%23)45&qldbqqebXEbiflqolmbL`rirpZyyNFAy.-0-.y
QRkil`hfkdqeb@ljmbkafrjyKyRpbX>o`ej^dbS^odlqe$pPq^ccZqlprjjlkFj^dblc>o`ej^dbS^odlqe*`^k_bcolj^kvil`^qflkyyRy/5122yyNFAy.-0-.y
>PrjjlkboH^kqefk$pMofwbyKyRpbX>o`ej^dbS^odlqe$pPq^ccZqlprjjlkFj^dblc>o`ej^dbS^odlqe*`^k_bcolj^kvil`^qflkyyRy/5122yyNFAy.-/-6y

QQlo`efkdPrkcrovEliayKyIfbrqbk^kq*Plo`boboJloo^k%24+2)53+0&yyNFAy.-/00y
QQebPrkcrovD^oofplkyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-///y
>AltkTfqeA^biifpyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-//0y

E>ob^2/yNFAy.-/-3y
>Mf`hVlroM^oqyKyM^m^Tebbibo%0/+6)31+4&yyNFAy.-/-3y
Q@lkploqfrj@ovpq^i@liib`qflkyKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/32y
>>Eb^mlcBqebob^ipyKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/3/y
QJb^profkdT^omBkbodfbpyKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-0.0y
Q?$k^^o@lkplibQo^kp`ofmqflkyKy>k`elofqbH^og^%0/+-)31+/&yyNFAy.-/12y
>PerqqfkdAltkJ^k^clodb?$k^^oyKyPmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy.-0/6y

@PerqqfkdAltkJ^k^clodb?$k^^oyKyHfiiLsbopbboQebobafp%/0+5)4-+2&qldbqqebX?$k^^o>``bpp@ovpq^iZ+Rpbqeb`ovpq^i^qqeb?$k^^o@lkqoli@lkplib%/0+/)35+.&yyNFAy.-0/6y
@Mf`hVlroM^oqyKyDbq.-mfb`bplcXBqebob^iQb`eklildvZ^qqeb`^jmtfqeqebW^uufpjl_p+Illhclo`vifkabop^ka_lubplkqebdolrka^olrka%0.)42&yyNFAy.-/-3y
@>Eb^mlcBqebob^ipyKyDbq.-XW^uufpFkpfdkf^pZ^olrka%0-)42&yyNFAy.-/3/y

QMf`hVlroM^oqyKyM^m^Tebbibo%0/+6)31+4&yyNFAy.-/-3y
>Fk>P`o^mTfqeQebIbdflkyKyM^m^Tebbibo%0/+6)31+4&yyNFAy.-/0/y
>EbimJ^j^TebbiboyKyM^m^Tebbibo%0/+6)31+4&yyNFAy.-000y
Q>Eb^mlcBqebob^ipyKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/3/y
>T^om*O^faboKbp^^ayKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/-2y
QPerqqfkdAltkJ^k^clodb?$k^^oyKyPmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy.-0/6y
>PerqqfkdAltkJ^k^clodb@lorryKy@^ibafp?ofdeqa^tk%15+/)53+4&yyNFAy.-00-y
>>qq^`hlkJ^k^clodb@lorryKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-/13y

@T^om*O^faboKbp^^ayKyHfiiT^om*O^faboKbp^^a^q%/5)5-&+Ebe^p/dr^oap)fcvlrdbq_befkaefj^kamriiqebibcqdr^oa)lkiveb^kaqebibcqdr^oatfii`ljbyyNFAy.-/-2y
@PerqqfkdAltkJ^k^clodb@lorryKyHfiiLsbopbboPbvi^kk^%16)5.&qldbqqebX@lorr>``bpp@ovpq^iZ+Qebkrpbfq^qqeb@lorr@lkqoli@lkplibyyNFAy.-00-y
@>qq^`hlkJ^k^clodb@lorryKyHfii5Prkcrov>o`^kfpqp^ka2PrkcrovObpb^o`ebop+>o`^kfpqp^oblrqpfab%15)50&lkqebplrqebokfpi^ka+Obpb^o`ebop^obfkpfabyyNFAy.-/13y

>Aofgv^KbbapVlroEbimyKyD^eorg%13+4)24+-&fkpfabqebaljbyyNFAy.-0..y
QEbimJ^j^TebbiboyKyJ^j^Tebbibo%13+3)23+3&yyNFAy.-000y
>LkbAbjlk$pQo^pe+++yKyJ^j^Tebbibo%13+3)23+3&yyNFAy.-/01y
>Ork^Af^dklpqf`yKyJbeoa^a%13+2)23+2&yyNFAy.-1.4y
>KbtLmmloqrkfqfbpyKyJbeoa^a%13+2)23+2&yyNFAy.-015y
>HbbmfkdRm>mmb^o^k`bpyKyPe^rivMlob%13+2)23+.&yyNFAy.-100y
QAofgv^KbbapVlroEbimyKyAofgv^clrka^olrka%15)31&yyNFAy.-0..y

@LkbAbjlk$pQo^pe+++yKyDbq.-XCbiOb^sboM^oqpZclrkalkqebdolrkakb^o^iilcqeb_olhbkaltkcbi_lqp%2.)21&+QebvalKLQaolmcoljjl_pyyNFAy.-/01y
@Fk>P`o^mTfqeQebIbdflkyKyHfii2Jl$^odAlljpjfqep^ka.2D^k$^odBkdfkbbop^olrka%16)26&yyNFAy.-/0/y
@Ork^Af^dklpqf`yKyDbqqebXAf^dklpqf`ObpriqpZ^q%15+/)22+-&yyNFAy.-1.4y
@HbbmfkdRm>mmb^o^k`bpyKyHfiiOfmc^kdIvkup^olrka%11)23&qldbq.-XOfmc^kdIvkuMbiqpZyyNFAy.-100y
@KbtLmmloqrkfqfbpyKyDbq.2XFslov?biipZclrka^ii^olrka^q%12)2/&^qB`lAljbJfaob^ijyyNFAy.-015y

QLkbAbjlk$pQo^pe+++yKyJ^j^Tebbibo%13+3)23+3&yyNFAy.-/01y
>Ab`i^tfkdAllj`i^tyKyJ^j^Tebbibo%13+3)23+3&yyNFAy.-/02y
QKbtLmmloqrkfqfbpyKyJbeoa^a%13+2)23+2&yyNFAy.-015y
QOrk^Af^dklpqf`yKyJbeoa^a%13+2)23+2&yyNFAy.-1.4y
>Ab^iTfqeqebP^_lqbropyKyJbeoa^a%13+2)23+2&yyNFAy.-1.5y
QHbbmfkdRm>mmb^o^k`bpyKyPe^rivMlob%13+2)23+.&yyNFAy.-100y
>QebAvk^jf`ArlyKyPe^rivMlob%13+2)23+.&yyNFAy.-101y

QFk>P`o^mTfqeQebIbdflkyKyM^m^Tebbibo%0/+6)31+4&yyNFAy.-/0/y
QT^om*O^faboKbp^^ayKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/-2y
>Obnrbpqclo>ppfpq^k`byKyKbqebo*Pq^ihboHe^v$gf%0/+2)31+0&yyNFAy.-/33y
QPerqqfkdAltkJ^k^clodb@lorryKy@^ibafp?ofdeqa^tk%15+/)53+4&yyNFAy.-00-y
>PerqqfkdAltkJ^k^clodbArolyKyPmvj^pqboQe^ilafbk%0/+-)31+.&yyNFAy.-005y
Q>qq^`hlkJ^k^clodb@lorryKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-/13y
>Prkcrov?ofbcfkdpyKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-0/5y

QObnrbpqclo>ppfpq^k`byKyD^eorg%13+4)24+-&yyNFAy.-/33y
>OfdeqcriObmlppbppflkyKyD^eorg%13+4)24+-&yyNFAy.-/34y

@Ab`i^tfkdAllj`i^tyKyHfiiAllj`i^til`^qba_vqeb_fdbkbodvqr_b%2-)24&qldbqXAllj`i^t$pE^kaZ+?bpq^mmol^`efpcoljqebb^pq)plvlralk$qe^sbqlcfdeq^kvjl_p^kavlr$iie^sb^_fdbjmqvpm^`bqlalqebhfiifkdyyNFAy.-/02y
@PerqqfkdAltkJ^k^clodbArolyKyHfiiLsbopbbo>qe^kbifkqebPlrqeB^pqtfkd%26+6)35+0&)qldbqqebXArol>``bpp@ovpq^iZ+RpbfqlkqebArol@lkqoli@lkplibyyNFAy.-005y
@OfdeqcriObmlppbppflkyKyDbq.-X?lubplcProsbvfkdBnrfmjbkqZclrka^qJ^k^clodbArol%24)35&+Fkpfab^ilkdqebt^iipfk_lubpyyNFAy.-/34y
@Prkcrov?ofbcfkdpyKyHfiiPrkcrov?ltjbk^ka@bkqroflkpcloqebXPrkcrovJfifq^ov?ofbcfkdZ)Prkcrov@lkgrobopcloqebXPrkcrov>o`^kb?ofbcfkdZ+>iiqeobb^obil`^qbalrqpfablcJ^k^clodbArol%3-)35&+Qeb_ofbcfkdpe^sbnrfqb^iltaolmo^qbyyNFAy.-0/5y
@AltkTfqeA^biifpyKyHfiiJ^pqboA^biifpA^tkpqofhb^q%23)33&+Eborkp^olrka_^`h^kacloqe)_rqsbovb^pvqlpmlqyyNFAy.-//0y
@PrjjlkboH^kqefk$pMofwbyKyHfiiPrjjlkboH^kqefkqldbqqebXPqlkblcDi^`frpZ+Ebpm^tkp^q%24)32&qebkm^qolipqeblrqbombofjbqboyyNFAy.-/-6y

QPrjjlkboH^kqefk$pMofwbyKyRpbX>o`ej^dbS^odlqe$pPq^ccZqlprjjlkFj^dblc>o`ej^dbS^odlqe*`^k_bcolj^kvil`^qflkyyRy/5122yyNFAy.-/-6y
>>o$hbilpqebDr^oaf^kyKyRpbX>o`ej^dbS^odlqe$pPq^ccZqlprjjlkFj^dblc>o`ej^dbS^odlqe*`^k_bcolj^kvil`^qflkyyRy/5122yyNFAy.-.43y

O@lpjltobk`eyKyB^pqlcJ^k^clodbArol%32)33&yyNFAy.-6/1y
>?illavFjm*lppf_ibyKyP^_$^lqe%33+1)34+/&yyNFAy.-6/1y
@?illavFjm*lppf_ibyKyPrjjlkWbmmfqrpfkdXWbmmfq$p@ovpq^iZ^kahfiiqebT^om@e^pbop%32)31&)qldbq5sf^iplcXT^om@e^pbo?illaZ+Vlrjrpq_b`ilpbqlqebT^om@e^pbopcloqebfjmql`liib`qqeb_illayyRy0.5.2yyNFAy.-6/1y
Q?illavFjm*lppf_ibyKyP^_$^lqe%33+1)34+/&yyNFAy.-6/1y

QOfdeqcriObmlppbppflkyKyD^eorg%13+4)24+-&yyNFAy.-/34y
>>k>rafbk`btfqeqebMofk`byKyD^eorg%13+4)24+-&yyNFAy.-/35y
QAb`i^tfkdAllj`i^tyKyJ^j^Tebbibo%13+3)23+3&yyNFAy.-/02y
>T^ok>ob^2/yKyJ^j^Tebbibo%13+3)23+3&yyNFAy.-/04y

@Ab^iTfqeqebP^_lqbropyKyHfii5?^o_p`^ib@ol`lifphp^qqebi^hbfkqebB`l*Aljb%13)21&yyNFAy.-1.5y

QAb^iTfqeqebP^_lqbropyKyJbeoa^a%13+2)23+2&yyNFAy.-1.5y
>QlqebPqlojpmfobyKyJbeoa^a%13+2)23+2&yyNFAy.-1/0y

OQebPqlojpmfobyKyCliiltqebol^alrqqlqeb_fddboaljb%1.)0/&yyNFAy.-1/3y
>Cilo^lcqebB`l*AljbpyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/3y
QQlqebPqlojpmfobyKyDe^_^o%10+2)02+.&yyNFAy.-1/0y
>Af^dklpfp7@ofqf`^iyKyDe^_^o%10+2)02+.&yyNFAy.-1/1y
eQebPqlojpmfobyNFAy.-002y
>ProsbvfkdqebOrfkpyKyWbmevoflk%11+4)01+6&yyNFAy.-002y
>QebJfkflkplc@rirqe^pyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-003y
>CbiOb^sbop)KlQe^khpyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-522y
QQebAvk^jf`ArlyKy>rafqebKbbaib%11+5)03+4&yyNFAy.-101y
>ObqofbsfkdqebDllapyKy>rafqebKbbaib%11+5)03+4&yyNFAy.-102y
Q>k>rafbk`btfqeqebMofk`byKyFj^dblcKburp*Mofk`bE^o^j^a%12+5)03&yyNFAy.-/35y
>Qof^kdri^qflkMlfkqLkbyKyFj^dblcKburp*Mofk`bE^o^j^a%12+5)03&yyNFAy.-/36y

C>ob^2/yNFAy.-/14y
QT^ok>ob^2/yKyOl`hbq*@efbcCrpbi^db%0/+4)31+6&yyNFAy.-/04y
>Al`qloSljfp^)Me+Q+yKyOl`hbq*@efbcCrpbi^db%0/+4)31+6&yyNFAy.-/14y
QPerqqfkdAltkJ^k^clodbArolyKyPmvj^pqboQe^ilafbk%0/+-)31+.&+Phfmqebcliilt*rmyyNFAy.-005y
QPrkcrov?ofbcfkdpyKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-0/5y
>Lrqpfab>ppfpq^k`byKyBu^o`eLobifp%0/+.)31+/&yyNFAy.-10.y
QAl`qloSljfp^)Me+Q+yKyAl`qloSljfp^)Me+Q+%04+0)30+5&^q^ifqqibqbkq+Phfmqebcliilt*rmyyNFAy.-/14y

QAltkTfqeA^biifpyKy@rpqlaf^kAfbtloqe%24+2)53+0&yyNFAy.-//0y
@>o$hbilpqebDr^oaf^kyKyHfii>o$hbilp^qqebqltbobkqo^k`b%25+.)53+2&yyNFAy.-.43y
Q>o$hbilpqebDr^oaf^kyKy>o`ej^dbS^odlqe^qqebqlmlcqebqltbo%25+1)53+2&+Phfmqebcliilt*rmyyNFAy.-.43y

EQebPqlojpmfobyNFAy.-10-y
@Cilo^lcqebB`l*AljbpyRy/65.5yyKyRpbqebXBkbodvCfbiaJlari^qloZlkC^o^eilkI^pebop%1/)05&+Qebifqqibdr^oaf^kpqe^qpm^tk`^k$qjlsb)plgrpqjlsb^t^v^kavlralk$qe^sbqlhfiiqebjyyNFAy.-1/3y
@Af^dklpfp7@ofqf`^iyKyRpbqebXAf^dklpqf`Absf`bZ^qqebB`l*AljbPrqebolkDbkbo^qlo%13+4)/3+5&yyRy/65-0yyNFAy.-1/1y
@ProsbvfkdqebOrfkpyKyProsbvfkdJ^ohboLkb%2.+4)/-+2&+ProsbvfkdJ^ohboQtl%21+3)//+5&+ProsbvfkdJ^ohboQeobb%22+5).6+6&+Illhcloifqqibmromibdiltfkdplkqebdolrka^qb^`eil`^qflkyyRy/6112yyNFAy.-002y
@QebJfkflkplc@rirqe^pyKyHfii.-Elrkaplc@rirqe^p^ka2Bvbplc@rirqe^pk^olrka%21)//&yyNFAy.-003y
@CbiOb^sbop)KlQe^khpyKyHfiiD^k$^odJbhdfkbbopqldbq2X@lkabkpbaKbqeboD^pZ^olrka%04)/5&+RpblklkblcqebCbiOb^sbop%02)/5&)%03)/2&)%04)/2&+VlrlkivkbbaqlalqefplkLKBob^sboyyNFAy.-522y

QAf^dklpfp7@ofqf`^iyKyDe^_^o%10+2)02+.&yyNFAy.-1/1y
>QbpqfkdqebMolqlqvmbyKyDe^_^o%10+2)02+.&yyNFAy.-10-y
QProsbvfkdqebOrfkpyKyWbmevoflk%11+4)01+6&yyNFAy.-002y
QQebJfkflkplc@rirqe^pyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-003y
QCbiOb^sbop)KlQe^khpyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-522y
>Qeb?bpqAbcbkpbyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-523y
QCilo^lcqebB`l*AljbpyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/3y
>@ob^qrobplcqebB`l*AljbpyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/4y

@@ob^qrobplcqebB`l*AljbpyKyRpbqebXQ^i_rhQ^ddboZqlq^d./Q^i_rhp^olrka%1-)02&+Cfdeqqebjaltkql/-")qebkq^dqebjyyRy/65.4yyNFAy.-1/4y
Q@ob^qrobplcqebB`l*AljbpyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/4y
>TebkK^qrobDlbpQllC^oyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/6y
@TebkK^qrobDlbpQllC^oyKyDbq^XErihfkdEvao^Eb^oqZaolmmba_vJ^oh^or^qqebi^hb%11+2)/5+0&yyNFAy.-1/6y
QTebkK^qrobDlbpQllC^oyKy>rofkbJllk_i^wb%1/+0)0/+3&yyNFAy.-1/6y

@Qeb?bpqAbcbkpbyKyHfii./To^qe_ofkdbop^q%1.)/1&yyNFAy.-523y
QQbpqfkdqebMolqlqvmbyKyQ^pe^o%11+4).1+2&yyNFAy.-10-y
>>ii@ib^oyKyQ^pe^o%11+4).1+2&yyNFAy.-103y
@>ii@ib^oyKyHfii./P`vqebqllqeO^mqlop^olrka%12)..&yyNFAy.-103y
@ObqofbsfkdqebDllapyKyDbq.-XAljbDbkbo^qloPbdjbkqpZ^olrka%11).1&+Qebv^ob$efaabk$fkqebo^mqlobddkbpqpfkpfabB`l*AljbC^ocfbiayyNFAy.-102y
Q>ii@ib^oyKyQ^pe^o%11+4).1+2&yyNFAy.-103y
>Pr``bppyKyQ^pe^o%11+4).1+2&yyNFAy.-11-y
QPr``bppyKyDe^_^o%10+2)02+.&yyNFAy.-11-y
QQeb?bpqAbcbkpbyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-523y
>QbibmloqQefpyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-524y
QObqofbsfkdqebDllapyKy>rafqebKbbaib%11+5)03+4&yyNFAy.-102y

@QbibmloqQefpyKyRpbqebXJbkq^iFkqbocbobk`bOlaZqlJfka@lkqolilkblcqeb@v_bo*O^dbClodbiloap^karpbqebfoAbqlk^qb^_fifqvtefibpq^kafkdkbuqqlfq+Qebqbibmloqbop^ob^q%1/+0)/.+.&)%1.+.).6+1&)%06+/)/-+1&+Vlrkbbaqlpq^ka`ilpbqlqebqbibmloqbo+Fcvlr^ob^mbq`i^pp)afpjfpptef`ebsbombqvlr^obrpfkd_bclob^qqbjmqfkdqljfka`lkqoliyyRy0.345yyNFAy.-524y

QQbibmloqQefpyKyKbqebo*Pq^ihboK^rqefp%11+4)01+6&yyNFAy.-524y

>>Klq*Pl*JlabpqMolmlp^iyKyTfkaQo^aboJ^ofa%25+5)0.&+Vlrkbbaql_b4-ql^``bmqqefp)^kajlpqlcqebnrbpqpqlcliilt+Fcvlr^obk$qvbq4-)phfm^eb^aqlqebPe^altjllkdrfab^ka`ljb_^`hqlqefptebkvlr$ob4-yyNFAy.-/4-y
>Bib`qol*Pel`hDllakbppyKyObpb^o`eboK^srra%26+0)0/+2&yyNFAy.-1..y
>QebBqebobrjyKy@ljj^kabo>jbbo%26+2)0/+0&yyNFAy.-006y
>Ob`fmbcloAbpqor`qflkyKyMolcbpploA^_fof%3-+.)0.+5&yyNFAy.-104y
>@^mq^fkQvo^ifrpyKyCibpeE^kaiboSfofafrpclrka^olrka%3-)0/&yyNFAy.-1//y

RAofkhqeb`lk`l`qflkyRy/6404yyNFAy.-051y
HSlfaT^pqbpyKyClrka^olrka%22)05&yyNFAy.-1..yyNLySlfaT^pqbDil_ribpi^fk70-,0-y
@QebBqebobrjyKyBkqboqeb`^jm^q%24)0/&^kahfii2Bqebobrj>pp^ppfkp)2BqebobrjPel`hqollmbop)/BqebobrjObpb^o`ebop^ka@^mq^fkWls^u+QebQo^kpmlkabofpil`^qba^q%23)05&yyNFAy.-006y
QQebBqebobrjyKyFj^dblc@ljj^kabo>jbbo%23+5)05+4&yyNFAy.-006y
>BqebobrjA^q^yKyFj^dblc@ljj^kabo>jbbo%23+5)05+4&yyNFAy.-051y
@BqebobrjA^q^yKyDbqqebXBqebobrjA^q^@biZ^q%22+5)06+6&yyNFAy.-051y
QBqebobrjA^q^yKyFj^dblc@ljj^kabo>jbbo%23+5)05+4&yyNFAy.-051y
>Mlqbkqf^iclo?o^fkA^j^db:EfdeyKyFj^dblc@ljj^kabo>jbbo%23+5)05+4&yyNFAy.-052y
@Mlqbkqf^iclo?o^fkA^j^db:EfdeyKyHfiiBqebobrjp%23)03&)qebkaofkhqebXBqebobrjBppbk`bZqebvaolmql^iiltvlrqlpbbqebBqebobrjObi^vp%23)05&+Hfiiqelpbqldbq.2mfb`bplcXBqebobrjObi^vA^q^ZyyRy/615/yyNFAy.-052y
QMlqbkqf^iclo?o^fkA^j^db:EfdeyKyFj^dblc@ljj^kabo>jbbo%23+5)05+4&yyNFAy.-052y
>P*>*?*L*Q*>*D*ByKyFj^dblc@ljj^kabo>jbbo%23+5)05+4&yyNFAy.-1-2y
@P*>*?*L*Q*>*D*ByKyHfiiBqebobrj>o`elkp^kaBqebobrjLsboiloap^olrka%23)13&qldbq.XMobm^obaBqebobrjTo^mmfkdZyyNFAy.-1-2y
QP*>*?*L*Q*>*D*ByKyFj^dblc@ljj^kabo>jbbo%23+5)05+4&yyNFAy.-1-2y
>AbifsbofkdqebJbpp^dbyKyFj^dblc@ljj^kabo>jbbo%23+5)05+4&yyNFAy.-1-3y
@AbifsbofkdqebJbpp^dbyKyBp`loqMolqb`qlo^qbAbjlifqflkfpq%23)05&yyNFAy.-1-3y
QAbifsbofkdqebJbpp^dbyKyFj^dblc@ljj^kabo>jbbo%23+5)05+4&+Phfmqebcliilt*rmyyNFAy.-1-3y

@@^mq^fkQvo^ifrpyKyDbqqebhbv_vhfiifkdT^oabkF`lpel`h)kb^oqebmfkhpmebobppb`qflk%22)1-&+Qebkrpbqebhbvqlcobb@^mq^fkQvo^ifrpcoljMofplk^q%20)1.&yyNFAy.-1//y
>QebCibpeIfbp+++yKy>dbkq>o^ubp%26+1)12+.&yyNFAy.-012y
@QebCibpeIfbp+++yKyBkqboqebpe^cq^q%3.)12&+RpbqebXMolqb`qlo^qbFdkfqboZlk./Tfqeboba@lompbp+Rpbqebfdkfqbo_bclobvlrob^`eqeb`lompb)lofqtfiiqo^kpclojfkql^jlkpqbo%fcvlrt^ihlkfq&yyRy/6140yyNFAy.-012y
>>o`lkrpqebFkp^qf^_ibyKy>dbkqV^*pfu%3-+6)1.+3&yyNFAy.-020y
@>Klq*Pl*JlabpqMolmlp^iyKyQebXQbibmloqboMltboM^`hZfpfkqeb`^sbrkaboJ^k^clodbRiqofp%3.)1/&+Cliiltqebdobbk`ovpq^ipqlcfkafq+Rpbvlromltbom^`h^q%4.)06&)_vqebqrokfknrbpqdfsboyyNFAy.-/4-y
@>o`lkrpqebFkp^qf^_ibyKyObqrokqlqeb`^sbbkqo^k`b)qebkeb^afkpq^vfkdofdeq+Hfii>o`lkrpqebFkp^qf^_ibfkqeb_fdollj%3-+.)1-+0&yyNFAy.-020y
QQebCibpeIfbp+++yKy>dbkq>o^ubp%26+1)12+.&yyNFAy.-012y

RAofkhqeb`lk`l`qflkyRy/6404yyNFAy.-/4.y
@Bib`qol*Pel`hDllakbppyKyHfii0-SlfaT^pqbDil_ribp%24)12&)aofkhXK^srra$p@lk`l`qflkZ^kaqebslfat^pqbdil_rib`ljb^cqbo^k^qq^`h+Hfii0-PbbmfkdPiradbDil_ribp%31)13&qebkaofkh^d^fk^kapbbmfkdpiradbdil_ribp`ljblrqyyNFAy.-1..yyRy/6404y
@Ob`fmbcloAbpqor`qflkyKyHfiiSlfapeofbhbop^kaRkpq^_ibSlfato^fqepfk^ka^olrkaJ^k^clodb7Riqofp%3/)1/&)qldbq5XCo^djbkqplcAfjbkpfrpZyyNFAy.-104y
@Qof^kdri^qflkMlfkqLkbyKyRpbqebXQof^kdri^qflkAbsf`bZqebkcfkaqebj^oh%33+4)00+5&+Tebkrpfkdqebabsf`balk$qpq^kafkqeb`loob`qil`^qflkql_bdfktfqe%fb733+4)00+5&+Pq^kagrpqlrqpfabqeb^ob^^karpbfq+Tebkqebj^oh`ljbprm)t^ihqlfqcloqebnrbpqql`ljmibqbyyRy/563/yyNFAy.-/36y

Q>Klq*Pl*JlabpqMolmlp^iyKyFj^dblcTfkaQo^aboJ^ofa%4.+/)06+-&yyNFAy.-/4-y
>DbqqfkdAltkql?rpfkbppyKyFj^dblcTfkaQo^aboJ^ofa%4.+/)06+-&+Vlr`^k$qalqefpnrbpqfcvlr$sbdlqefdeKbqebotfkdc^`qflkyyNFAy.-/4.y
@DbqqfkdAltkql?rpfkbppyKyDbq5XKbqeboAo^dlkBppbk`bpZcoljKbqeboAo^dlkploKbqeboAo^hbp^olrka%4/)05&yyNFAy.-/4.y
QDbqqfkdAltkql?rpfkbppyKyPeolrabaCfdrob%4-+6)05+6&_befkaqebqbibmloqm^ayyNFAy.-/4.y
>Cloj^iFkqolar`qflkpyKyPeolrabaCfdrob%4-+6)05+6&_befkaqebqbibmloqm^a+Vlr`^k$qalqefpnrbpqfcvlr$sbdlqefdeKbqebotfkdc^`qflkyyNFAy.-/5.y
QCloj^iFkqolar`qflkpyKyQvof%4.+/)02+/&yyNFAy.-/5.y
>>MoljfpfkdPq^oqyKyQvof%4.+/)02+/&+Vlr`^k$qalqefpnrbpqfcvlr$sbdlqefdeKbqebotfkdc^`qflkyyNFAy.-/4/y
@>MoljfpfkdPq^oqyKyDbq.2XKbqeboAo^dlkhfkBddpZp`^qqboba^olrka%40)02&yyNFAy.-/4/y
Q>MoljfpfkdPq^oqyKyQvof%4.+/)02+/&yyNFAy.-/4/y
>Qolr_ibpljbAfpqo^`qflkpyKyQvof%4.+/)02+/&+Vlr`^k$qalqefpnrbpqfcvlr$sbdlqefdeKbqebotfkdc^`qflkyyNFAy.-/40y

QOb`fmbcloAbpqor`qflkyKyMolcbpploA^_fof%3-+.)0.+5&yyNFAy.-104y
>LkKbqebovTfkdpyKyMolcbpploA^_fof%3-+.)0.+5&yyNFAy.-105y
Q@^mq^fkQvo^ifrpyKyCibpeE^kaiboSfofafrpclrka^olrka%3-)0/&yyNFAy.-1//y
QBib`qol*Pel`hDllakbppyKyObpb^o`eboK^srra%26+0)0/+2&yyNFAy.-1..y
Q>o`lkrpqebFkp^qf^_ibyKy@ljj^kabo>jbbo%26+2)0/+0&yyNFAy.-020y
QQof^kdri^qflkMlfkqLkbyKyAb^iboE^wwfk%25+1)0.+1&yyNFAy.-/36y
>Qof^kdri^qflkMlfkqQtlyKyAb^iboE^wwfk%25+1)0.+1&yyNFAy.-/42y

@Qolr_ibpljbAfpqo^`qflkpyKyPq^oqaf^ildrbtfqeTfkaQo^aboJ^ofa^q%25)0.&+EbPm^tkp/35kbqebo*pq^ihbop)qebkebefjpbic%isi36&qrokpelpqfibyyNFAy.-/40y
@LkKbqebovTfkdpyKyQ^ihqlqebkbqeboao^hb%3-)0.&^kaq^hb^ofab+Pq^oqpm^j`if`hfkdqebXMe^pbAfpormqloZfkvlro_^dlk`bvlr$ob`ilpbqlJ^k^clodb7RiqofpyyRy/6445yyNFAy.-105y
QLkKbqebovTfkdpyKyMolcbpploA^_fof%3-+.)0.+5&+Phfmqebcliilt*rmyyNFAy.-105y

QQolr_ibpljbAfpqo^`qflkpyKyQvof%4.+/)02+/&+Phfmqebcliilt*rmyyNFAy.-/40y

EQebPqlojpmfobyNFAy.-0.4y
QLrqpfab>ppfpq^k`byKyH^vi^^k%01+5)05+/&yyNFAy.-10.y
>>A^ohM^`qyKyH^vi^^k%01+5)05+/&yyNFAy.-05-y
>Ab^ifkdtfqeqebClobj^kyKyTfkaQo^aboQrirj^k%01+3)04+6&yyNFAy.-0.4y
>Kbrqo^ifwfkdqebKbqeboj^k`bopyKyKbqebo*Pq^ihboL^wri%01+3)04+5&yyNFAy.-0.2y

QAb^ifkdtfqeqebClobj^kyKyClobj^kPrkaltk%/3+1)1/+2&+FkqebQobiibrjJfkbyyNFAy.-0.4y
>Ab^ifkdtfqeqebLsboj^pqboyKyClobj^kPrkaltk%/3+1)1/+2&+FkqebQobiibrjJfkbyyNFAy.-0.5y
@Ab^ifkdtfqeqebLsboj^pqboyKyHfiiLsboj^pqboDofkad^oo+Ebfpfkqebjfkb_biltqebJ^kclodb>o^+Bkqboqebjfkb^q%/3)11&)q^hbvlrocfopqofdeq)qebkdlpqo^fdeqqfiiqebbka+Eb$p_befkaqtlqbkqp%/3+5)03+.&yyNFAy.-0.5y
@Kbrqo^ifwfkdqebKbqeboj^k`bopyKyHfii.2PrkcrovKbqeboj^k`bop%0-)05&+LrqpfabqebjfkbyyNFAy.-0.2y
@>A^ohM^`qyKyBkqboqeb`^sb^q%/3)10&qlhfii3D^k$^odT^om*Qfkhbop^ka0Jl$^odT^om*J^pqbop+Hfii0A^rdeqboplcAbpqfkvtef`epm^tk^qqebpbmlfkqp7%0.)1.&)%/6)10&^ka%/6)1.&yyNFAy.-05-y

@Qof^kdri^qflkMlfkqQtlyKyRpbqebXQof^kdri^qflkAbsf`bZ^kacfkaqebj^ohkb^oJ^k^clodb>o^%/5+6)1.+/&yyRy/6-.5yyNFAy.-/42y
Q>A^ohM^`qyKyH^vi^^k%01+5)05+/&yyNFAy.-05-y
QQof^kdri^qflkMlfkqQtlyKyTfkaQo^aboQrirj^k%01+3)04+6&+Phfmqebcliilt*rmyyNFAy.-/42y
QAb^ifkdtfqeqebLsboj^pqboyKyTfkaQo^aboQrirj^k%01+3)04+6&yyNFAy.-0.5y
QKbrqo^ifwfkdqebKbqeboj^k`bopyKyKbqebo*Pq^ihboL^wri%01+3)04+5&yyNFAy.-0.2y
]]
end)
