DugisGuideViewer:RegisterGuide("Shadowmoon Valley (68-70 |cfff0c502Optional|r)", nil, "Alliance", "L", function()
return [[
AAA

OPe^altjllkS^iibvyKyQo^sbiqlPe^altjllkS^iibv%/0)/4+6&yyNFAy.-23/y
OTfiae^jjboPqolkdeliayKyQo^sbiqlTfiae^jjboPqolkdelia%06)20&yyNFAy.-23/y

>?bpfbdbayKyTfkd@ljj^kaboKr^fkk%06+2)20+4&yyNFAy.-23/y
@?bpfbdbayKyHfii.-Fkcbok^i>qq^`hbop^olrka%1-)2/&yyNFAy.-23/y
Q?bpfbdbayKyTfkd@ljj^kaboKr^fkk%06+2)20+4&yyNFAy.-23/y
>QlIbdflkEliayKyTfkd@ljj^kaboKr^fkk%06+2)20+4&yyNFAy.-230y
>QebPhbqe$ilkTob`h^dbyKyDovmelkofaboHfbo^k%05+4)21+/&yyNFAy.-236y
>>DelpqfkqebJ^`efkbyKyWlorpqebGraf`^qlo*clrka^olrka%04)23&yyNFAy.-31/y
eTfiae^jjboPqolkdeliayKyAobd@ilraptbbmbo%04+.)25+0&yyNFAy.-35-y
>QebE^kalcDri$a^kyKyB^oqejbkaboPlmerorp%03+2)23+5&yyNFAy.-35-y
>MrqLkVboHkbbm^ap+++yKyQe^kbVlobd^o%03+0)23+6&yyNFAy.-4-0y
>PmibbkafayKyDkljrp%03+3)22+/&yyNFAy.-33.y

KHfii^pvlrnrbpq++yKyHfii^kvCbi_l^op)Sfibtfkd@efj^bo^p^kaP`lo`epebiiMfk`bop^olrkavlr`ljb^`olppcloMrqLkVboHkbbm^ap+++%0/)1.&+>iplillq^kvXBsbo*_rokfkd>peZvlrpbb)^kahfiiAfbjbqo^alkpcloPmibbkafa%0.)06&yyNFAy.-4-0y
QQebE^kalcDri$a^kyKyB^oqejbkaboQloilh%1/+/)12+-&yyNFAy.-35-y
>Bko^dbaPmfofqplcCfob^kaB^oqeyKyB^oqejbkaboQloilh%1/+/)12+-&yyNFAy.-125y
@Bko^dbaPmfofqplcCfob^kaB^oqeyKyRpbqebXQlqbjlcPmfofqpZlkqebBko^dbaCfob^kaB^oqepmfofqpil`^qba^q$QebCbiMfqp$%12)12&yyRy0--61yyNFAy.-125y
QBko^dbaPmfofqplcCfob^kaB^oqeyKyB^oqejbkaboQloilh%1/+/)12+-&yyNFAy.-125y
>Bko^dbaPmfofqplcT^qboyKyB^oqejbkaboQloilh%1/+/)12+-&yyNFAy.-15-y
@Bko^dbaPmfofqplcT^qboyKyHfiit^qbobibjbkq^ipil`^qba^olrka%14)//&^karpbqebXQlqbjlcPmfofqpZql`^mqrob2T^qbovPlripyyRy0--61yyNFAy.-15-y

@QebPhbqe$ilkTob`h^dbyKyGlrok^im^dbpaolmlcc^kvlcqeb^o^hhl^^qqebTob`h^db%04)0/&yyNFAy.-236y
@PmibbkafayKyDbq5CbicfobPmibbkpaolmmba_vCbicfobAfbjbqo^alk+Qebv$ob^qqebdobbki^s^i^hbfkcolkqlcIbdflkElia%0.)06&yyNFAy.-33.y
@>DelpqfkqebJ^`efkbyKyDbq.2Bsbo*_rokfkd>pep^jmibp^olrka%1-)25&+Grpqmf`hqebjrmlccqebdolrkayyNFAy.-31/y

@QlIbdflkEliayKyQeb@ljjrkf`^qflkAbsf`bfplk^_^i`lkbv^qIbdflkElia%/0)03&+RpbqebX?lul$Qof`hpZqlqrokfkql^_lu)qebkqebobfp.jfkrqblcaf^ildrb^kaqebnrbpqtfii`ljmibqbyyRy0-305yyNFAy.-230y

Q>DelpqfkqebJ^`efkbyKyWlorpqebGraf`^qlo*clrka^olrka%04)23&yyNFAy.-31/y
>E^o_fkdboplcPe^altjllkyKyWlorpqebGraf`^qlo*clrka^olrka%04)23&yyNFAy.-310y
QPmibbkafayKyDkljrp%03+3)22+/&yyNFAy.-33.y
>QebPb`lka@lropb+++yKyDkljrp%03+3)22+/&yyNFAy.-344y

RRpbXPmb`qob`ibpZyRy0-4.6yyNFAy.-310y
@E^o_fkdboplcPe^altjllkyKyTb^oqebXPmb`qob`ibpZplvlr`^kpbbqebpe^altjllkpmfofqp%03)22&+Hfii./Pe^altjllkE^o_fkdbop+Vlralk$qe^sbqlib^sbqebpqolkdeliayyRy0-4.6yyNFAy.-310y
QE^o_fkdboplcPe^altjllkyKyWlorpqebGraf`^qlo*clrka^olrka%04)23&yyNFAy.-310y
>QbolkDlobcfbka*Ilob^kaIbdbkayKyWlorpqebGraf`^qlo*clrka^olrka%04)23&yyNFAy.-311y
QQebPhbqe$ilkTob`h^dbyKyDovmelkofaboHfbo^k%05+4)21+/&yyNFAy.-236y
>CfkaqebAbpboqboyKyDovmelkofaboHfbo^k%05+4)21+/&yyNFAy.-426y
QQlIbdflkEliayKyTfkd@ljj^kaboKr^fkk%06+2)20+4&yyNFAy.-230y
>PbqqfkdRmqeb?lj_yKyTfkd@ljj^kaboKr^fkk%06+2)20+4&yyNFAy.-24/y

QBko^dbaPmfofqplcT^qboyKyB^oqejbkaboQloilh%1/+/)12+-&yyNFAy.-15-y
>Bko^dbaPmfofqplc>foyKyB^oqejbkaboQloilh%1/+/)12+-&yyNFAy.-15.y

@QebPb`lka@lropb+++yKyDbq.XLsboabsbilmbaCbicfobDfww^oaZaolmmba_vDob^qboCbicfobAfbjbqo^alkp^olrka%23)2/&kb^oqebi^hbyyNFAy.-344y

QCfkaqebAbpboqboyKyM^ope^e*m^qolip^ilkdqebol^a%02)06&yyNFAy.-426y
>>pde^o$pQlqbjyKyM^ope^e*m^qolip^ilkdqebol^a%02)06&yyNFAy.-444y
@>pde^o$pQlqbjyKyHfii>pde^o^qqebPhbqe$ilkTob`h^dbebt^ihp^olrkaqeb^ob^%06)/6&+DbqqebXPhbqe$ilkT^oQlqbjZlcefjyyNFAy.-444y

Q>pde^o$pQlqbjyKyM^ope^e*m^qolip^ilkdqebol^a%02)06&yyNFAy.-444y
>QebOlalcIf^kqebyKyM^ope^e*m^qolip^ilkdqebol^a%02)06&yyNFAy.-445y

HLsbopbboOfmp^tyKy?^`h^qIbdflkElia+Kb^oqebcbiob^sbo^olrka%/0)03&qldbqqebfqbjXFiifa^of*?^kbPe^oaZyyIy0-423yyNFAy.-3/.y
@PbqqfkdRmqeb?lj_yKyQebXCbiOb^sbo>ojloMi^qbZfpkb^oqebcbiob^sbo%//+0)02+2&+QebXCbiOb^sboMltbo@lobZfprkabot^qbo^qqebCbqfaMlli%/3+0)1.+.&yyNFAy.-24/y

QPbqqfkdRmqeb?lj_yKyTfkd@ljj^kaboKr^fkk%06+2)20+4&yyNFAy.-24/y
>?i^pqqebFkcbok^ipyKyTfkd@ljj^kaboKr^fkk%06+2)20+4&yyNFAy.-231y
QQebPb`lka@lropb+++yKyDkljrp%03+3)22+/&yyNFAy.-344y
>QebJ^fk@lropbyKyDkljrp%03+3)22+/&yyNFAy.-345y
>Fiifa^of*?^kbPe^oayKyPq^oqptfqeqebfqbjXFiifa^of*?^kbPe^oaZaolmmba_vLsbopbboOfmp^t^olrka%/0)03&yyRy0-423yyNFAy.-3/.y
QFiifa^of*?^kbPe^oayKyLoafkkQerkabocfpq%03+5)21+5&yyNFAy.-3/.y

@?i^pqqebFkcbok^ipyKyRpbqebXCbi?lj_Ztefibpq^kafkdlkqebdobbkdivmefkIbdflkElia%//+3)06+6&yyRy0-3.1yyNFAy.-231y

Q?i^pqqebFkcbok^ipyKyTfkd@ljj^kaboKr^fkk%06+2)20+4&yyNFAy.-231y
>QebAb^qeclodbyKyTfkd@ljj^kaboKr^fkk%06+2)20+4&yyNFAy.-240y

@QebOlalcIf^kqebyKyHfii?illaBisbp^qB`ifmpbMlfkq%12)31&qldbqXIf^kqeb$pHbvZ+RpbqebhbvqllmbkIf^kqeb$pPqolkd_lu^q%14+2)4.+3&^kadbqqebXOlalcIf^kqebZcoljfkpfabyyNFAy.-445y
@Bko^dbaPmfofqplc>foyKyQ^hbqebol^ab^pqqlqebKbqebotfkdCfbiap+HfiiqebBko^dba>foPmfofqp^olrka%3/)22&^karpbqebXQlqbjlcPmfofqpZql`^mqrob.-plripyyRy0--61yyNFAy.-15.y

QQbolkDlobcfbka*Ilob^kaIbdbkayKy>k`fbkqPe^altjllkPmfofq*^qqeb>iq^olcPe^altp%25+/)4-+5&yyNFAy.-311y
>Afsfk^qflk7Dlobcfbka$p@il^hyKy>k`fbkqPe^altjllkPmfofq*^qqeb>iq^olcPe^altp%25+/)4-+5&yyNFAy.-302y
>Afsfk^qflk7Dlobcfbka$pQork`eblkyKy>k`fbkqPe^altjllkPmfofq*^qqeb>iq^olcPe^altp%25+/)4-+5&yyNFAy.-303y

>Qeb>peqlkdrbQof_byKy>ialolkiv)qf`hqefppqbmfcqefpnrbpqfpklq^s^fi^_ibqlvlr+Sfkaf`^qlo>irrjbk%3.+/)/6+/&yyNFAy.-3.6y
>Qeb>peqlkdrb?olhbkyKyP`ovbolkiv)qf`hqefppqbmfcqefpnrbpqfpklq^s^fi^_ibqlvlr+S^obkqebOb`i^fjbo%21+5)25+/&yyNFAy.-5-4y
>Q^_ibqplc?^^$ofyKy>o`^kfpqQebifp%23+0)26+2&yyNFAy.-350y
>H^o^_loQo^fkfkdDolrkapyKyI^ofpp^Prkpqofhb%22+5)25+/&yyNFAy.-354y

@QebJ^fk@lropbyKyHfiiCbipmfkbqebDob^qbokloqelcqebT^oabk$p@^db^q%23+.)11+3&^kadbqefpefabyyNFAy.-345y
RMrqlkvlroPmb`qob`ibpyRy0-4/.yyNFAy.-351y
KIllhclo++yKyT^q`eqebj^fkol^a^olrkaqebE^kalcDri$a^kcloDelpqofabolcH^o^_lo+Qebvm^qoliqebolrqb`lrkqbo`il`htfpb+FcvlrpbbqebjhfiilkbcloAfsfk^qflk7Dlobcfbka$pQork`eblk+VlrkbbavlroXPmb`qob`ibpZqlpbbqebjyyNFAy.-303yyIy0-5--y
@Afsfk^qflk7Dlobcfbka$p@il^hyKyHfii@ibof`plcH^o^_lofkcolkqlcqeb?i^`hQbjmib^olrka%31)15&)qldbqXDlobcfbka$p@il^hZyyNFAy.-302y

@Qeb>peqlkdrbQof_byLyyKy>qqebOrfkplc?^^$of+Hfii0>peqlkdrbE^kaibop)1>peqlkdrbT^ooflop^ka3>peqlkdrbPe^j^k^olrka%26)03&yyNFAy.-3.6y
@Qeb>peqlkdrb?olhbkyLyyKy>qqebOrfkplc?^^$of+Hfii0>peqlkdrbE^kaibop)1>peqlkdrbT^ooflop^ka3>peqlkdrbPe^j^k^olrka%26)03&yyNFAy.-5-4y
@Q^_ibqplc?^^$ofyKyDbq./X?^^$ofQ^_ibqpZ^olrka%25)03&+Qebv^oblkqebdolrkatfqeilqplcm^qolifkdjl_p^olrkayyNFAy.-350y
@H^o^_loQo^fkfkdDolrkapyKyFkpfabqeb?i^`hQbjmib)bkqboqeolrdeqebj^fkd^qb^kadlofdeq%4-)2-&+HfiiAbjlkErkqboPrmmif`^kqp^kaFkfqf^qbp*qebfkfqf^qbpqbkaqle^sb^_bqqboaolmo^qbpl_bpqqldlcloqebj+Vlrkbbaqldbq5XPrkcrovDi^fsbpZ+>iplt^q`elrqcloqeb4-bifqbqe^qm^qolipqeb^ob^yyNFAy.-354y

QQeb>peqlkdrbQof_byLyyKySfkaf`^qlo>irrjbk%3.+/)/6+/&yyNFAy.-3.6y
QQeb>peqlkdrb?olhbkyLyyKyS^obkqebOb`i^fjbo%21+5)25+/&yyNFAy.-5-4y
>LolkrqebBiaboyKy>o`^kfpqQebifp%23+0)26+2&yyNFAy.-351y
QQ^_ibqplc?^^$ofyKy>o`^kfpqQebifp%23+0)26+2&yyNFAy.-350y
QH^o^_loQo^fkfkdDolrkapyKyI^ofpp^Prkpqofhb%22+5)25+/&yyNFAy.-354y
>>Kb`bpp^ovAfpqo^`qflkyKyI^ofpp^Prkpqofhb%22+5)25+/&yyNFAy.-355y

QQebJ^fk@lropbyKyDkljrp%03+3)22+/&yyNFAy.-345y
QBko^dbaPmfofqplc>foyKyB^oqejbkaboQloilh%1/+/)12+-&yyNFAy.-15.y
>LolklhQlok*eb^oqyKyB^oqejbkaboQloilh%1/+/)12+-&yyNFAy.-2.0y

QLolklhQlok*eb^oqyKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2.0y
>FT^p>IlqLcQefkdp+++yKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2.1y
@FT^p>IlqLcQefkdp+++yKyDbq.-XPe^altjllkQr_bopZ^olrka%2/).2&+Vlrkbbaqlcfkaqr_bojlrkap*^qlliqfmtfiimlmrmtebkvlrelsbolsbofq+RpbXLolklh$p?l^oTefpqibZtebk^_l^ofpkb^o_v^kaqeb_l^otfii`ljbafdrmqebqr_bo)qebk^illq^_ibPe^altjllkQr_bo^mmb^op+Vlr`^killqjriqfmibqr_bo$pmbojlrkafcvlr`^kdbqqtl%lojlob&_l^opql`ljblsbopfjriq^kblrpiv+>iplfq$p_bpqqlhbbm^pj^ii^ob^`ib^olcci^vbopqlpqlmqebj^qq^`hfkdqeb_l^opyyRy0-13/yyNFAy.-2.1y
QFT^p>IlqLcQefkdp+++yKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2.1y
>>IbpplkIb^okbayKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2.2y
@>IbpplkIb^okbayKyAbpqolv.-XO^sbklrpCi^vboBddpZlkqebdolrka^olrka%24)/-&+T^q`ecloqebibsbi4-bifqbqe^qt^kabopqeb^ob^yyNFAy.-2.2y
Q>IbpplkIb^okbayKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2.2y
>Qeb@fmebolcA^jk^qflk*Qorqe^kaEfpqlovyKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2.6y
@Qeb@fmebolcA^jk^qflk*Qorqe^kaEfpqlovyKyPmb^hqlLolklh%20+6)/0+2&^kaifpqbkqlefppqlovyyNFAy.-2.6y
QQeb@fmebolcA^jk^qflk*Qorqe^kaEfpqlovyKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2.6y
>Dolj$qlo)PlklcLolklhyKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2/.y
>>o$qlo)PlklcLolklhyKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2/4y
>?lo^h)PlklcLolklhyKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-213y

QQebOlalcIf^kqebyKyM^ope^e*m^qolip^ilkdqebol^a%02)06&yyNFAy.-445y
>Phbqe$ilkCb^qebopyKyM^ope^e*m^qolip^ilkdqebol^a%02)06&yyNFAy.-45-y

QQebAb^qeclodbyKyPqlojboBt^kTfiatfkd%1-+2)1.+0&yyNFAy.-240y
>JfkflkplcqebPe^alt@lrk`fiyKyPqlojboBt^kTfiatfkd%1-+2)1.+0&yyNFAy.-25/y
@JfkflkplcqebPe^alt@lrk`fiyKyHfii.-Ab^qeclodbDr^oaf^kp^ka2Ab^qeclodbPrjjlkbop+Eb^aaltkfkqlqebAb^qeclodb+Qebbkqo^k`bfpkloqelcqebqltbo%05)02&yyNFAy.-25/y
QJfkflkplcqebPe^alt@lrk`fiyKyPqlojboBt^kTfiatfkd%1-+2)1.+0&yyNFAy.-25/y
>QebPrjjlkfkd@e^j_boyKyPqlojboBt^kTfiatfkd%1-+2)1.+0&yyNFAy.-252y
>QebC^qblcCi^kfpyKyPqlojboBt^kTfiatfkd%1-+2)1.+0&yyNFAy.-250y
@QebC^qblcCi^kfpyKyBkqboqeb`^sb^q%1-)05&^kacfdeqvlrot^vofdeqqlqeb_^`h+Ci^kfpPtfcqtfkdfp^q%01+4)06+6&+DbqXCi^kfp$pM^`hZyyNFAy.-250y
HQfkhbobop^kaPjfqepyKyIllhfkdclo^kBibjbkq^iAfpmi^`bo^olrka%05)1-&yyIy0-34/yyNFAy.-252y
@QebPrjjlkfkd@e^j_boyKy>pvlrdlaltkqebo^jmqlt^oapqeb`^sbp)q^hbqebcfopqlkbqlvlroofdeq+Hfiiqebabjlkp%klqqeblo`p&cloqebafpmi^`bo+Dllrqpfab^kaeb^aqlqebkbuq`^sb)qebbkqo^k`bfp^q%1-+1)06+2&+RpbqebXBibjbkq^iAfpmi^`boZ^kahfiiPrjjlkboPh^oq^u^kaFkcbok^iLsboplriyyRy0-34/yyNFAy.-252y
QQebPrjjlkfkd@e^j_boyKyPqlojboBt^kTfiatfkd%1-+2)1.+0&yyNFAy.-252y
QQebC^qblcCi^kfpyKyPqlojboBt^kTfiatfkd%1-+2)1.+0&yyNFAy.-250y
>?ofkdAltkqebT^o_ofkdboyKyPqlojboBt^kTfiatfkd%1-+2)1.+0&yyNFAy.-253y
@?ofkdAltkqebT^o_ofkdboyKyDlqlqebcfopq`^sbbkqo^k`b%06)1-&tebobvlrclrkaCi^kqf$pm^`h+Dllsboqebi^odb_ofadb^kalkqebibcqpfabvlr$iipbb^d^qbtebobvlr`^krpbqebAb^qeclodbhbv+T^o_ofkdboO^wrrkfp^qqebbkalcqebpj^iibo`^sb_befkaqebd^qb%06+-)13+3&yyNFAy.-253y
Q?ofkdAltkqebT^o_ofkdboyKyTfkd@ljj^kaboKr^fkk%06+2)20+4&yyNFAy.-253y
>D^fkfkd>``bppyKyTfkd@ljj^kaboKr^fkk%06+2)20+4&yyNFAy.-256y

@D^fkfkd>``bppyKyDbq^XIbdflkQbibmloqbo@lkqoliZaolmmba_vJl$^odTb^mlkpjfqep^olrka%/2)02&yyNFAy.-256y

Q>o$qlo)PlklcLolklhyKy>o$qlo)PlklcLolklh%/6+3)2-+2&yyNFAy.-2/4y
>Abjlkf`@ovpq^iMofplkpyKy>o$qlo)PlklcLolklh%/6+3)2-+2&yyNFAy.-2/5y
@Abjlkf`@ovpq^iMofplkpyKyHfiiM^fkjfpqobppD^_ofpp^^qFiifa^ofMlfkq%/5+.)14+5&^kadbqqebX@ovpq^iifkbHbvZyyNFAy.-2/5y
QAbjlkf`@ovpq^iMofplkpyKy>o$qlo)PlklcLolklh%/6+3)2-+2&yyNFAy.-2/5y
>Ilek$dlolk)?ltlcqebQlok*eb^oqyKyPmfofqlc>o$qlo%/6+3)2-+2&yyNFAy.-204y
@Ilek$dlolk)?ltlcqebQlok*eb^oqyKyDbqXIlek$dlolk)?ltlcqebQlok*eb^oqZ)aolmpcolj^iiqebabjlkpfkqeb^ob^%/6)16&yyNFAy.-204y
QIlek$dlolk)?ltlcqebQlok*eb^oqyKyPmfofqlc>o$qlo%/6+3)2-+2&yyNFAy.-204y
>Qeb@fmebolcA^jk^qflk*>o$qlo$p@e^odbyKyPmfofqlc>o$qlo%/6+3)2-+2&yyNFAy.-21-y
@Qeb@fmebolcA^jk^qflk*>o$qlo$p@e^odbyKyHfiiSbkbo^qrpqebJ^kv%0-)24&qldbqqebXPb`lkaCo^djbkqlcqeb@fmebolcA^jk^qflkZ+Lk^``bmqfkdqefpnrbpq)vlrdbq^pmfofqerkqboteltfii^``ljm^kvvlrqlqebil`^qflktebobebtfiiprjjlkSbofq^pyyNFAy.-21-y
QQeb@fmebolcA^jk^qflk*>o$qlo$p@e^odbyKyPmfofqlc>o$qlo%/6+3)2-+2&yyNFAy.-21-y
>Qeb@fmebolcA^jk^qflk*QebPb`lkaCo^djbkqOb`lsbobayKyPmfofqlc>o$qlo%/6+3)2-+2&yyNFAy.-21.y

QD^fkfkd>``bppyKyTfkd@ljj^kaboKr^fkk%06+2)20+4&yyNFAy.-256y
>Fks^pflkMlfkq7@^q^`ivpjyKyTfkd@ljj^kaboKr^fkk%06+2)20+4&yyNFAy.-433y
QFks^pflkMlfkq7@^q^`ivpjyKyQ^hbqebqbibmloqbo%/2+2)03+0&qlpbbMibuf^q%1-+6)//+0&yyNFAy.-433y
>Qeb>oqlcCbiOb^sboJ^fkqbk^k`byKyMibuf%1-+6)//+0&yyNFAy.-3-3y

QDolj$qlo)PlklcLolklhyKyDolj$qlo)PlklcLolklh%11+3)/0+4&yyNFAy.-2/.y
>Qeb@fmebolcA^jk^qflk*Dolj$qlo$p@e^odbyKyDolj$qlo)PlklcLolklh%11+3)/0+4&yyNFAy.-2//y
@Qeb@fmebolcA^jk^qflk*Dolj$qlo$p@e^odbyKyHfiiqebK^d^p^ii^olrka`lfiph^omlfkq%12)/4&)qebvtfiiaolmhbvptef`elmbkqeb`lfiph^o`ebpqpi^vfkd^_lrq+CfkaqebXCfopqCo^djbkqlcqeb@fmebolcA^jk^qflkZfkpfab^`ebpqyyNFAy.-2//y
QQeb@fmebolcA^jk^qflk*Dolj$qlo$p@e^odbyKyDolj$qlo)PlklcLolklh%11+3)/0+4&yyNFAy.-2//y
>Qeb@fmebolcA^jk^qflk*QebCfopqCo^djbkqOb`lsbobayKyDolj$qlo)PlklcLolklh%11+3)/0+4&yyNFAy.-2/0y

@Qeb>oqlcCbiOb^sboJ^fkqbk^k`byKyHfiiAl`qloDrqof`h%06+2).6+2&)dbqqebAl`qlo$pHbv+RpbqebhbvqllmbkqebPqolkd_lu_bpfabDrqof`h^kaillqqebXQeb>oqlcCbiOb^sboJ^fkqbk^k`bZyyNFAy.-3-3y
QQeb>oqlcCbiOb^sboJ^fkqbk^k`byKyMibuf%1-+6)//+0&yyNFAy.-3-3y
>QebCbi^kaqebCroflrpyKyMibuf%1-+6)//+0&yyNFAy.-3./y
@QebCbi^kaqebCroflrpyKyHfii3-Ab^qeclodbaFkcbok^iprpfkdqebCbiOb^sbo@lkqoli@lkplib+Qebv^obqebifqqib_lubp^_lrq.-cqaltkqebo^jmcoljqebnrbpqdfsbo%1-)//&+Vlrrpbqebmbq_^oql`ljj^kaqeb`lkplib)plvlr`^k$qe^sbvlrombqcloqebm^kbiqltloh+Vlre^sbql`ljmibqbqebnrbpq^kaobqrokqlqebnrbpqdfsbotfqefk2jfkrqbp+Fcqebnrbpqdfsbofpkqqebobqlqrokfqfk)orkaltkqebpilmbqlqebmlfkqtebkqebphvqrokpmromib^kaork_^`hrm+Qebv$ii_bqebobyyNFAy.-3./y
QQebCbi^kaqebCroflrpyKyMibuf%1-+6)//+0&yyNFAy.-3./y
>KbtplcSf`qlovyKyMibuf%1-+6)//+0&yyNFAy.-411y
QKbtplcSf`qlovyKyHroao^kTfiae^jjbo%02+5)24+4&yyNFAy.-411y

Q?lo^h)PlklcLolklhyKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-213y
>LcQefpqibeb^ap^kaBddp+++yKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-214y
@LcQefpqibeb^ap^kaBddp+++yKyCfka^XOlqqbk>o^hhl^BddZ^olrka%1/)22&yyNFAy.-214y

CPe^qqo^qe@fqvyNFAy.-22-y
QLcQefpqibeb^ap^kaBddp+++yKyQl_f^pqebCfiqeDlodboclrka^olrka%31)4-&fkPe^qqo^qe@fqvyyWyPe^qqo^qe@fqvyyNFAy.-214y
>Qeb?rkaiblc?illaqefpqibyKyQl_f^pqebCfiqeDlodboclrka^olrka%31)4-&fkPe^qqo^qe@fqvyyWyPe^qqo^qe@fqvyyNFAy.-22-y

ETfiae^jjboPqolkdeliayNFAy.-24-y
QQeb?rkaiblc?illaqefpqibyKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-22-y
>Ql@^q`e>Qefpqibeb^ayKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-24-y
@Ql@^q`e>Qefpqibeb^ayKyI^vqebX?rkaiblc?illaqefpqibZ^qqebbkalcqeb_ofadb%15)24&+Jlsb^t^v%vlr`^k$q_bqll`ilpb&^kat^fqcloqebbic^kaefpjlrkqba_lavdr^oaql^mmb^o+>cqbo^kbu`e^kdbqeb_lavdr^oatfiis^kfpe^katebkqebbicdlbpcloqeb_illaqefpqib)dbqefjyyRy0-3.3yyNFAy.-24-y
QQl@^q`e>Qefpqibeb^ayKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-24-y
>QebPe^altjllkPerccibyKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-243y
@QebPe^altjllkPerccibyKyDbq3mfb`bplcXB`ifmpflk>ojloZaolmmba_v^kvlcqebB`ifmpflk_illabisbp^olrkaB`ifmpbMlfkq%11)32&yyNFAy.-243y
QQebPe^altjllkPerccibyKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-243y
>Te^qFiifa^kT^kqp)Fiifa^kDbqp+++yKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-244y
@Te^qFiifa^kT^kqp)Fiifa^kDbqp+++yKyMrqlkX?illaBicAfpdrfpbZ)t^ihqlDo^ka@ljj^kaboOrrph%13+2)4.+5&)pmb^hqlefj)t^ih^t^v+Locivfk)grpqalk$qi^kaqll`ilpb*_b^_lrq/-jbqobp^t^v+Grpqalk$qal^kvqefkdtefibafpdrfpbayyRy0-306yyNFAy.-244y
QTe^qFiifa^kT^kqp)Fiifa^kDbqp+++yKy?lo^h)PlklcLolklh%14+2)24+/&yyNFAy.-244y

@Phbqe$ilkCb^qebopyKyDbq5XPhbqe$ilkCb^qebopZlkqebdolrka^olrka%10)24&yyNFAy.-45-y
QPhbqe$ilkCb^qebopyKyM^ope^e*m^qolip^ilkdqebol^a%02)06&yyNFAy.-45-y
>Fj_rfkdqebEb^amfb`byKyM^ope^e*m^qolip^ilkdqebol^a%02)06&yyNFAy.-45/y
@Fj_rfkdqebEb^amfb`byKyRpbqebXRkcfkfpebaEb^amfb`bZ^q%10)11&+Bnrfmfq_bclobdbqqfkdqebobyyRy0.03-yyNFAy.-45/y
QFj_rfkdqebEb^amfb`byKyM^ope^e*m^qolip^ilkdqebol^a%02)06&yyNFAy.-45/y
>Qet^oqqebA^oh@lk`i^sbyKyM^ope^e*m^qolip^ilkdqebol^a%02)06&yyNFAy.-5-5y
@Qet^oqqebA^oh@lk`i^sbyKyRpbqebXPq^cclcM^ope^eZ^q%1.)3-&^cqbo`ib^ofkdlrq^iiqebbkbjfbpyyRy0.053yyNFAy.-5-5y
QQet^oqqebA^oh@lk`i^sbyKyM^ope^e*m^qolip^ilkdqebol^a%02)06&yyNFAy.-5-5y

@>Kb`bpp^ovAfpqo^`qflkyKyHfiiPrkcrovT^oil`hp^kaPrjjlkbop^olrka%4/)16&rkqfiqebXP`oliilcAbjlkf`Rk_^kfpefkdZaolmp+?bpqklqhfiiqebjl_pkb^oefj)loeb$ii`ljb^cqbovlrRpbqebp`oliilk>w^ilqeil`^qba^q%4-+-)2.+1&+Lk`bebfpcobb)orknrf`hiv_b`^rpbebtfii^qq^`hvlryyRy0-5..yyNFAy.-355y

@LolkrqebBiaboyKyHfiiLolkrqebBiabo%24+/)00+.&eb$plkqeb_^i`lkv^kadbqXLoabopColj>h^j^ZyyNFAy.-351y
QLolkrqebBiaboyKy>o`^kfpqQebifp%23+0)26+2&yyNFAy.-351y
>Qeb>peqlkdrb@loormqlopyKy>o`^kfpqQebifp%23+0)26+2&yyNFAy.-352y
@Qeb>peqlkdrb@loormqlopyKyB^`e`loormqbofpproolrkaba_v0qlqbjp+Vlre^sbqlhfiiqebqlqbjp_bclobvlr`^k^qq^`hqeb`loormqbo+E^^irj7%23)40&Bvhbkbk7%2.)2/&Rvi^or7%15)05&I^h^^k7%16)/0&yyNFAy.-352y
QQeb>peqlkdrb@loormqlopyKy>o`^kfpqQebifp%23+0)26+2&yyNFAy.-352y
>QebT^oabk$p@^dbyKy>o`^kfpqQebifp%23+0)26+2&yyNFAy.-353y
QQebT^oabk$p@^dbyKyP^klor%24+0)16+3&+FkqebelibyyNFAy.-353y
>Mollclc>iibdf^k`byKyP^klor%24+0)16+3&+FkqebelibyyNFAy.-3//y
@Mollclc>iibdf^k`byKyHfiiW^kao^p)ebfprmpq^fopt^ihfkd^olrkaqebmbofjbqbolkqlmlcqebt^iip%24)16&yyNFAy.-3//y
QMollclc>iibdf^k`byKyP^klor%24+0)16+3&+FkqebelibyyNFAy.-3//y
>>h^j^yKyP^klor%24+0)16+3&+FkqebelibyyNFAy.-3/5y
Q>h^j^yKy>h^j^%25+.)15+0&*dlaltkqebpq^fop^kaptfjrkabo^t^iiqldbqqlefjyyNFAy.-3/5y

@MrqLkVboHkbbm^ap+++yKyVlrgrpqe^sbqlhfiicbi_l^op)clrka^olrka%0/)1.&yyNFAy.-4-0y
@Afsfk^qflk7Dlobcfbka$pQork`eblkyKyObjbj_boqltb^oqebXPmb`qob`ibpZ+HfiiDelpqofaboplcH^o^_lo`fo`ifkdQebE^kalcDri$a^kqldbqXDlobcfbka$pQork`eblkZ+?bpqqldl`il`htfpb^ilkdqebj^glool^a)^pqebvqo^sbi`lrkqbo`il`htfpb%02+1)01+5&)%01+0)14+3&)%14)24+1&)%3/+5)2/+2&)%3/+4)0/+3&)%13+0)/1+/&yyNFAy.-303yyRy0-4.6y

QMrqLkVboHkbbm^ap+++yKyQe^kbVlobd^o%03+0)23+6&yyNFAy.-4-0y
QAfsfk^qflk7Dlobcfbka$pQork`eblkyKy>k`fbkqPe^altjllkPmfofq*^qqeb>iq^olcPe^altp%25+/)4-+5&yyNFAy.-303y
QAfsfk^qflk7Dlobcfbka$p@il^hyKy>k`fbkqPe^altjllkPmfofq*^qqeb>iq^olcPe^altp%25+/)4-+5&yyNFAy.-302y
Q>Kb`bpp^ovAfpqo^`qflkyKyI^ofpp^Prkpqofhb%22+5)25+/&yyNFAy.-355y
QQeb@fmebolcA^jk^qflk*QebCfopqCo^djbkqOb`lsbobayKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-2/0y
QQeb@fmebolcA^jk^qflk*QebPb`lkaCo^djbkqOb`lsbobayKyLolklhQlok*eb^oq%20+6)/0+2&yyNFAy.-21.y
]]
end)
