DugisGuideViewer:RegisterGuide("Borean Tundra (68-71)", "Howling Fjord (71-73)", "Alliance", "L", function()
return [[
AAA

?Lsbo`e^odba@^m^`fqloyKyCfka^kbkdfkbbolosfpfqqeb>EyyIy0635/yyNFAy..34/y

OPqlojtfka@fqvyKyQo^sbiqlPqlojtfk@fqv%.5+.)/2+5&yyWyPqlojtfka@fqvy
_?lob^kQrkao^yKyQ^hbqeb_l^qql?lob^kQrkao^%.5+.)/2+5&yyWyPqlojtfka@fqvy

eS^if^k`bHbbmyKyG^jbpAb^`lk%25+0)35+.&yyNFAy..34/y
cS^if^k`bHbbmyKyQlj^pOfsbotbii%25+6)35+0&yyNFAy..34/y

>BkifpqjbkqA^vyKyOb`orfqjbkqLccf`bo?ivqeb%24+5)34+4&yyNFAy..34/y
QBkifpqjbkqA^vyKyDbkbo^i>oilp%23+4)4/+3&yyNFAy..34/y
>>QfjbcloEbolbpyKyDbkbo^i>oilp%23+4)4/+3&yyNFAy..4/4y
Q>QfjbcloEbolbpyKyPbodb^kqE^jjboefii%23+1)36+3&yyNFAy..4/4y
>QebPfbdbyKyPbodb^kqE^jjboefii%23+1)36+3&yyNFAy..464y
>>PliafbofkKbbayKyJbaf`E^tqelok%22+-)35+6&yyNFAy..456y

@QebPfbdbyNFAy..464yyKyHfii@ovmq@o^tibopclrkagrpqlrqpfab^olrka%21+.)34+3&y

QQebPfbdbyKyPbodb^kqE^jjboefii%23+1)36+3&yyNFAy..464y
>Ab^qeColj>_lsbyKyPbodb^kqE^jjboefii%23+1)36+3&yyNFAy..556y

@>PliafbofkKbbayNFAy..456yyKyAltkpq^fopfkqebelialcqeb_l^q^qqeb`bkqbolcqltk%24+2)36+/&y
>@riqfpqp>jlkdRpyKy@riqfpqPeofkb%24+2)36+/&yyNFAy..6/-y
Q@riqfpqp>jlkdRpyKy@^mq^fkIbcqvIrdp^fi%24+5)36+/&yyNFAy..6/-y
>Klqfcv>oilpyKy>ajfo^i@^kqib_obb%24+5)36+/&yyNFAy..46.y
QKlqfcv>oilpyKyDbkbo^i>oilp%23+4)4/+3&yyNFAy..46.y
>>Afmilj^qf`JfppflkyKy@lrkpbiloQ^i_lq%23+4)4/+3&yyNFAy./.1.y
>BkbjfbplcqebIfdeqyKyE^o_fkdboSrobkk%23+3)4/+2&yyNFAy..46/y
Q>PliafbofkKbbayKyJbaf`E^tqelok%22+-)35+6&yyNFAy..456y

@Ab^qeColj>_lsbyNFAy..556yyRy02/45yyKyRpbqebXObfkclo`baKbqZlkqebP`lrodbaCi^jbpmfqqboplrqpfabqltk%22+-)4-+2&ql_ofkdqebjaltkfkql_^pefkdo^kdby
QAb^qeColj>_lsbyKyPbodb^kqE^jjboefii%23+1)36+3&yyNFAy..556y
>MirdqebPfkhelibpyKyPbodb^kqE^jjboefii%23+1)36+3&yyNFAy..564y
@MirdqebPfkhelibpyNFAy..564yyKyRpbqebXFk`bkaf^ovBumilpfsbpZlk^pfkhelibqlqebplrqe%2-+3)4.+1&^kakloqe%21+0)30+6&yyRy024-1y
QMirdqebPfkhelibpyKyPbodb^kqE^jjboefii%23+1)36+3&yyNFAy..564y
>C^opefobyKyPbodb^kqE^jjboefii%23+1)36+3&yyNFAy..6/5y
>TloalkqebPqobbqyKyJ^ohE^kbp%23+4)36+2&yyNFAy..6/4y
>Kf`hlcQfjbyKyJfadb%25+2)34+5&yyNFAy..242y
QTloalkqebPqobbqyKyIbovpp^%25+4)35+0&yyNFAy..6/4y
>Qe^pp^of^k)Jv?olqeboyKyIbovpp^%25+4)35+0&yyNFAy..266y
>Afpqobpp@^iiyKy>foj^kPhvelmmbo%25+5)35+4&yyNFAy..4-4y

QC^opefobyKyDbo^iaDobbk%25+/)3/+5&yyNFAy..6/5y
>Jfifq^ov<Te^qJfifq^ov<yKyDbo^iaDobbk%25+/)3/+5&yyNFAy..6-.y

QJfifq^ov<Te^qJfifq^ov<yKyMi^drbaDo^fk%23+5)22+3&yyNFAy..6-.y
>Mbokf`flrpBsfabk`byKyMi^drbaDo^fk%23+5)22+3&yyNFAy..6-/y
QQe^pp^of^k)Jv?olqeboyKyTfiif^j>iiboqlk%23+.)22+1&yyNFAy..266y
>QebI^qbTfiif^j>iiboqlkyKyTfiif^j>iiboqlk%23+.)22+1&yyNFAy..3--y
QMbokf`flrpBsfabk`byKyDbo^iaDobbk%25+/)3/+5&yyNFAy..6-/y
>Fq$pQfjbclo>`qflkyKyDbo^iaDobbk%25+/)3/+5&yyNFAy..6-0y
>Q^hbKl@e^k`bpyKyTbkavA^oobk%25+0)3/+5&yyNFAy..6.0y
>Obcbobk`bJ^qbof^iyKyGbobjf^eE^tkfkd%25+/)3/+6&yyNFAy..6-5y

@Q^hbKl@e^k`bpyNFAy..6.0yyKyRpbXTbkav$pQlo`eZql_rok^kvdo^fkvlrcfka^olrka%22+.)26+-&yyRy0216.y
@Obcbobk`bJ^qbof^iyNFAy..6-5yyKyCfkaqeb_llhXCfbiap)C^`qlofbp^kaTlohpelmpZfkqeb_rokfkd_rfiafkdkb^oqebjfkb%22+5)25+1&y
@Fq$pQfjbclo>`qflkyNFAy..6-0yyKyHfiiP`^sbkdbopkb^oC^opefob^olrka%22+4)3.+2&y

QQ^hbKl@e^k`bpyKyTbkavA^oobk%25+0)3/+5&yyNFAy..6.0y
QFq$pQfjbclo>`qflkyKyDbo^iaDobbk%25+/)3/+5&yyNFAy..6-0y
>CorfqplcLroI^_loyKyDbo^iaDobbk%25+/)3/+5&yyNFAy..6-1y
QObcbobk`bJ^qbof^iyKyGbobjf^eE^tkfkd%25+/)3/+6&yyNFAy..6-5y
>ObmromlpbaQb`eklildvyKyGbobjf^eE^tkfkd%25+/)3/+6&yyNFAy./-02y

@ObmromlpbaQb`eklildvyNFAy./-02yyKyHfiie^osbpqbop^karpbXGbobjf^e$pQllipZlkqebj^olrka%25+/)3.+.&yyRy02610y
@CorfqplcLroI^_loyNFAy..6-1yyKyHfii@^mq^fkG^`l_pfkqebjfkb^kaobib^pbqeb`^oq%24+.)21+4&y
@BkbjfbplcqebIfdeqyNFAy..46/yyKyHfii`riqfpqp^qqebprjjlkfkd`fo`ibp%22+/)30+1&%21+/)3/+1&y

QCorfqplcLroI^_loyKyDbo^iaDobbk%25+/)3/+5&yyNFAy..6-1y
>LkbI^pqAbifsbovyKyDbo^iaDobbk%25+/)3/+5&yyNFAy..63/y
QObmromlpbaQb`eklildvyKyGbobjf^eE^tkfkd%25+/)3/+6&yyNFAy./-02y
QLkbI^pqAbifsbovyKyEfia^Pqlkbclodb%24+0)33+3&yyNFAy..63/y
>Tb^mlkpcloC^opefobyKyEfia^Pqlkbclodb%24+0)33+3&yyNFAy..630y
QTb^mlkpcloC^opefobyKyDbo^iaDobbk%25+/)3/+5&yyNFAy..630y
>@^iiql>ojpyKyDbo^iaDobbk%25+/)3/+5&yyNFAy..632y
@@^iiql>ojpyNFAy..632yyKyOfkdqeb_biirmpq^fopfkqebqltke^ii%24+1)26+0&y
Q@^iiql>ojpyKyDbo^iaDobbk%25+/)3/+5&yyNFAy..632y

QQebI^qbTfiif^j>iiboqlkyKyIbovpp^%25+4)35+0&yyNFAy..3--y
>Ilpq^kaClrkayKyIbovpp^%25+4)35+0&yyNFAy..3-.y
QIlpq^kaClrkayKyG^jbpAb^`lk%25+0)35+.&yyNFAy..3-.y
>FkTfkb)QorqeyKyG^jbpAb^`lk%25+0)35+.&yyNFAy..3-0y
@FkTfkb)QorqeyNFAy..3-0yyKyPtfjkloqeb^pqcoljqltk)cfkaqeb`ebpqfkqebtob`h^db%3.+5)32+4&y
QFkTfkb)QorqeyKyLiaJ^k@li_rok%25+2)35+.&yyNFAy..3-0y
>>AbpboqboyKyLiaJ^k@li_rok%25+2)35+.&yyNFAy..3-1y
Q>AbpboqboyKyMofs^qb?o^r%23+4)4.+2&yyNFAy..3-1y
>@lt^oap^kaCllipyKyMofs^qb?o^r%23+4)4.+2&yyNFAy..60/y
QBkbjfbplcqebIfdeqyKyE^o_fkdboSrobkk%23+3)4/+2&yyNFAy..46/y
>CroqeboFksbpqfd^qflkyKyE^o_fkdboSrobkk%23+3)4/+2&yyNFAy..460y
QCroqeboFksbpqfd^qflkyKySfkaf`^qloV^^i^%25+2)34+1&yyNFAy..460y
>QebErkqfpLkyKySfkaf`^qloV^^i^%25+2)34+1&yyNFAy..461y
@QebErkqfpLkyNFAy..461yyRy02./2yyKyRpbqebXL`rirplcqebBulo`fpqZfkqebhbbm$pg^fi%23+34)4.+43&^kafkqebhfq`ebk%25+3/)34+.-&)^qqebiltboal`h%26+.5)35+23&^kahfiiqeb`riqfpqpy
QQebErkqfpLkyKySfkaf`^qloV^^i^%25+2)34+1&yyNFAy..461y

Q>Afmilj^qf`JfppflkyKyH^orh%14+/)42+2&yyNFAy./.1.y
>H^orh$pL^qeyKyH^orh%14+/)42+2&yyNFAy..3.0y
@H^orh$pL^qeyNFAy..3.0yyKyAltklkOfmi^pePqo^ka^olrka%13+1)44+0&y
QH^orh$pL^qeyKyH^orh%14+/)42+2&yyNFAy..3.0y
>D^jbiqeb@orbiyKyH^orh%14+/)42+2&yyNFAy..3.6y
@D^jbiqeb@orbiyNFAy..3.6yyKyFk^`^sbaltklkqeb_b^`e%13+0)45+5&y
QD^jbiqeb@orbiyKyH^orh%14+/)42+2&yyNFAy..3.6y
>>C^qebo$pTloapyKyH^orh%14+/)42+2&yyNFAy..3/-y
Q>C^qebo$pTloapyKySbbeg^%10+3)5-+3&yyNFAy..3/-y
>QebQofabkqlcK^w$g^kyKySbbeg^%10+3)5-+3&yyNFAy..3/2y
@QebQofabkqlcK^w$g^kyNFAy..3/2yyKyPtfjplrqeb^pqqlOfmi^peOrfkpql%2-+6)6-+2&)tlohvlrot^vrmqlqebkloqeb^pq_rfiafkd%21+6)55+5&y
QQebQofabkqlcK^w$g^kyKySbbeg^%10+3)5-+3&yyNFAy..3/2y
>QebBjfpp^ovyKySbbeg^%10+3)5-+3&yyNFAy..3/3y
@QebBjfpp^ovyNFAy..3/3yyRy0252-yyKyPtfj_^`hqlqebi^odbf`b_bod^qOfmi^peOrfkp%2.+1)55+/&+Afsbaltk)rpbqebXQofabkqlcK^w$g^kZlkIbsfolqe^kahfiiefjy
QQebBjfpp^ovyKyH^orh%14+/)42+2&yyNFAy..3/3y

>QebElkloba>k`bpqlopyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-2y
>Ob`i^fjfkdqebNr^oovyKyBq^orh%21+0)03+/&yyNFAy..3./y
@QebElkloba>k`bpqlopyNFAy..3-2yyKyCfkaBiaboQ^hobq%2/+0)0.+/&)BiaboP^d^kf%2/+5)01+.&^kaBiaboHbprh%2-+5)0/+1&y
@Ob`i^fjfkdqebNr^oovyNFAy..3./yyKyClrka^olrkaqebnr^oov^q%2/+2)00+/&y
QQebElkloba>k`bpqlopyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-2y
>QebIlpqPmfofqpyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-4y
QOb`i^fjfkdqebNr^oovyKyBq^orh%21+0)03+/&yyNFAy..3./y
>E^jmbofkdQebfoBp`^mbyKyBq^orh%21+0)03+/&yyNFAy..3.4y
@E^jmbofkdQebfoBp`^mbyNFAy..3.4yyKyHfiiqebOb`i^fjbopcloXDkljfpeDobk^abpZ)qebkrpb^qqebqeobbcil^qfkdmi^qclojpB^pq%2/+1)02+0&)Tbpq%2-+2)01+5&^kaKloqe%2.+6)0.+6&yyRy0144/y
@QebIlpqPmfofqpyNFAy..3-4yyKyHfiiqebElrkapqebkrpbqebX@lobplcJ^if`bZlkqebQrph^oofkqebnr^oov%2/+2)00+/&yyRy014..y
QQebIlpqPmfofqpyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-4y
>Mf`hfkdRmqebMfb`bpyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-6y
QE^jmbofkdQebfoBp`^mbyKyBq^orh%21+0)03+/&yyNFAy..3.4y
>>Sfpfqqlqeb@ro^qloyKyBq^orh%21+0)03+/&yyNFAy..3/0y
@>Sfpfqqlqeb@ro^qloyNFAy..3/0yyKyHfii@ro^qloFkpfsfrp^q%2-+.)0/+4&y
@Mf`hfkdRmqebMfb`bpyNFAy..3-6yyKyClrka^olrkaqebnr^oov%2/+2)00+/&y
QMf`hfkdRmqebMfb`bpyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3-6y
>Ib^afkdqeb>k`bpqlopEljbyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3.-y
Q>Sfpfqqlqeb@ro^qloyKyBq^orh%21+0)03+/&yyNFAy..3/0y
@Ib^afkdqeb>k`bpqlopEljbyNFAy..3.-yyKyRpbqebXQrph^ooOfqr^iL_gb`qZ^qb^`elcBiaboQ^hobq%2/+0)0.+/&)BiaboP^d^kf%2/+5)01+.&^kaBiaboHbprh%2-+5)0/+1&yyRy014.2y
QIb^afkdqeb>k`bpqlopEljbyKyBiabo>qh^klh%21+4)02+4&yyNFAy..3.-y

Q>JfppflkPq^qbjbkqyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..531y
>B^oplcLroBkbjfbpyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..533y
>EbimQelpbQe^q@^kklqEbimQebjpbisbpyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..543y
>E^mmv^p^@i^jyKyEfbolme^kq@bkfrp%24+0)11+.&yyNFAy..536y
>Kba)IloalcOefklp+++yKyHfiifkdboqebAbkT^q`ebo%24+-)11+0&yyNFAy..551y
>RkcfqcloAb^qeyKyW^w^%23+5)11+.&yyNFAy..532y

@RkcfqcloAb^qeyNFAy..532yyKyRpbXMfiblcC^hbCropZkbuqqlqo^mp^olrka%23+6)2.+0&yyRy02./4y
@E^mmv^p^@i^jyNFAy..536yyKyTbpq^qI^hbHrj$rv^^olrka%2.+3)13+6&y
@B^oplcLroBkbjfbpyNFAy..533yyKyHfiiafsbopfkI^hbHrj$rv^%2.+3)13+6&rkqfivlre^sb.2XKbpfkdt^ovI^`hbvB^opZy
@Kba)IloalcOefklp+++yNFAy..551yyKyM^qolip^olrkaqebtbpqpfablcqebi^hb%14+/)1.+/&+Dolrmnrbpq_rqplil^_ib^p`^k_b@@$ay

QRkcfqcloAb^qeyKyW^w^%23+5)11+.&yyNFAy..532y
>Qeb@riibo@ljbqeyKyW^w^%23+5)11+.&yyNFAy..535y
QE^mmv^p^@i^jyKyEfbolme^kq@bkfrp%24+0)11+.&yyNFAy..536y
>Qeb>_^kalkbaOb^`eyKyEfbolme^kq@bkfrp%24+0)11+.&yyNFAy..54-y
QKba)IloalcOefklp+++yKyHfiifkdboqebAbkT^q`ebo%24+-)11+0&yyNFAy..551y

@Qeb@riibo@ljbqeyNFAy..535yyKyHfiiH^obk^qqebc^oplrqebadblcqebcfbia%24+/)23+-&y

QQeb>_^kalkbaOb^`eyKyEfbolme^kqIf^kao^%24+5)22+.&yyNFAy..54-y
>KlqLkLroT^q`eyKyEfbolme^kqIf^kao^%24+5)22+.&yyNFAy..54.y
@KlqLkLroT^q`eyNFAy..54.yyKyQlqebplrqeb^pqpq^oqfkd^q%25+-)24+-&y
QKlqLkLroT^q`eyKyEfbolme^kqIf^kao^%24+5)22+.&yyNFAy..54.y
>QebKbc^oflrp@i^jJ^pqbo+++yKyEfbolme^kqIf^kao^%24+5)22+.&yyNFAy..54/y
@QebKbc^oflrp@i^jJ^pqbo+++yNFAy..54/yyKyHfii@i^jJ^pqboHqlqebplrqetbpq^qqebpefmtob`h%3.+3)33+1&y

QQeb@riibo@ljbqeyKyW^w^%23+5)11+.&yyNFAy..535y
QQebKbc^oflrp@i^jJ^pqbo+++yKyEfbolme^kq@bkfrp%24+0)11+.&yyNFAy..54/y

@EbimQelpbQe^q@^kklqEbimQebjpbisbpyNFAy..543yyKyRpbqebXA+B+E+Q+>+Qo^mPj^peboZlkqebqo^mpb^pqlcqebnr^oov^olrka%21+.)1.+-&yyRy02//5y

QEbimQelpbQe^q@^kklqEbimQebjpbisbpyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..543y
>Her$klhTfiiHkltyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..545y
QB^oplcLroBkbjfbpyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..533y
QHer$klhTfiiHkltyKyHer$klhqeb?bebjlqe%26+2)0-+3&yyNFAy..545y
>H^tqebJ^jjlqeAbpqolvboyKyHer$klhqeb?bebjlqe%26+2)0-+3&yyNFAy..546y
@H^tqebJ^jjlqeAbpqolvboyNFAy..546yyKyElmlk^_rii^kaHfiiH^t^qH^t$pOllpq%20+4)/1+1&+Afpjlrkqlk`beb$pab^aqlillqqebfqbjy

OCfww`o^kh>fopqofmyKyEb^aqlt^oapqebcifdeqj^pqbo^q%23+3)/-+.&yyNFAy..56/y
cCfww`o^kh>fopqofmyKyH^o^Qeof`bpq^o%23+3)/-+.&yyNFAy..56/y

QH^tqebJ^jjlqeAbpqolvboyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..546y
>Qeb>pp^ppfk^qflklcE^oliaI^kbyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..56/y
@Qeb>pp^ppfk^qflklcE^oliaI^kbyNFAy..56/yyKyQlqebtbpq_vqebi^hb%16+0)1-+2&+?b^qefjaltkqfiigrpq^_lsbe^iceb^iqeqebkrpbqebX@bk^oflkElokZql`^iifk^pq^jmbabqlcfkfpeefjlccyyRy02/60y

QKf`hlcQfjbyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..242y
>Mofplk?ob^hyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..254y
>JlkfqlofkdqebOfcq7@ibcq`ifcc>klj^ivyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy..243y

c>j_boIbadbyKyProofpqo^pw%12+0)01+2&yyNFAy..26-y

@JlkfqlofkdqebOfcq7@ibcq`ifcc>klj^ivyNFAy..243yyKyPlrqetbpq)m^pq?boviMlfkq)ptfjqlqebTbpqofcq%01+1)1/+.&^karpbqebX>o`^kljbqboZyyRy01336y
@Mofplk?ob^hyNFAy..254yyKy>q?boviMlfkq%1/+4)03+6&)hfiiJ^dbErkqbopcloqebhbvpy

QMofplk?ob^hyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..254y
>>_ar`qflkyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..26-y

QJlkfqlofkdqebOfcq7@ibcq`ifcc>klj^ivyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy..243y
>JlkfqlofkdqebOfcq7Prkaboba@e^pjyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy..25/y
@JlkfqlofkdqebOfcq7Prkaboba@e^pjyNFAy..25/yyKyPtfjkloqeb^pq)afsbaltkqlqebPrkaboba@e^pj%11+-)/5+3&)rpbqebX>o`^kljbqboZyyRy01336y
QJlkfqlofkdqebOfcq7Prkaboba@e^pjyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy..25/y
>JlkfqlofkdqebOfcq7Tfkqbocfk@^sbokyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy./4/5y

@>_ar`qflkyNFAy..26-yyKyDlcfka^?boviPlo`bobo)_b^qefj^_fq)qebkrpbqebX>o`^kb?fkaboZlkefjyyRy0136.y
Q>_ar`qflkyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..26-y
>Qeb?lob^kFknrfpfqflkyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..313y
QQeb?lob^kFknrfpfqflkyKyIf_o^of^kKloj^kqfp%13+1)0/+6&yyNFAy..313y
>Qeb>oqlcMbopr^pflkyKyIf_o^of^kKloj^kqfp%13+1)0/+6&yyNFAy..315y
@Qeb>oqlcMbopr^pflkyNFAy..315yyKyRpbqebXKbro^iKbbaiboZlkqebmofplkbofkqebqltboyyRy015..y
QQeb>oqlcMbopr^pflkyKyIf_o^of^kKloj^kqfp%13+1)0/+6&yyNFAy..315y
>Pe^ofkdFkqbiifdbk`byKyIf_o^of^kKloj^kqfp%13+1)0/+6&yyNFAy..330y
QPe^ofkdFkqbiifdbk`byKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..330y
>>O^`b>d^fkpqQfjbyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..34.y
@>O^`b>d^fkpqQfjbyNFAy..34.yyKyRpbqebX?boviPefbiaAbqlk^qloZlkqebi^odbolrkami^qcloj%1.+5)06+/&^kahfiiFknrfpfqloP^io^kayyRy01564y
Q>O^`b>d^fkpqQfjbyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..34.y
>ObclodfkdqebHbvyKyIf_o^of^kAlk^qe^k%12+0)00+2&yyNFAy..346y
QObclodfkdqebHbvyKyProofpqo^pw%12+0)01+2&yyNFAy..346y
>Q^hfkdTfkdyKyProofpqo^pw%12+0)01+2&yyNFAy..35-y
QQ^hfkdTfkdyKyT^oj^db>kwfj%13+1)04+0&yyNFAy..35-y
>Obp`rfkdBs^kloyKyT^oj^db>kwfj%13+1)04+0&yyNFAy..35.y
QObp`rfkdBs^kloyKy>o`ej^dbBs^klo%13+1)0/+2&yyNFAy..35.y
>Ao^dlkpmb^hyKy>o`ej^dbBs^klo%13+1)0/+2&yyNFAy..35/y
QAo^dlkpmb^hyKyProofpqo^pw%12+0)01+2&yyNFAy..35/y
>Qo^sbopfkdqebOfcqyKyProofpqo^pw%12+0)01+2&yyNFAy..400y

QQo^sbopfkdqebOfcqyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..400y
>Ob^afkdqebJbqbopyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6--y
>Pb`obqplcqeb>k`fbkqpyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6.-y
>Krqpclo?boofbpyKyIf_o^of^kPboo^e%00+2)01+1&yyNFAy..6./y
>?^pf`Qo^fkfkdyKyO^bilo^pw%00+0)01+2&yyNFAy..6.5y

c@lia^oo^yKyT^oj^db>a^jf%00+/)01+2&yyNFAy..61.y

@Ob^afkdqebJbqbopyNFAy..6--yyKyCfkaqeblo_pqlob^a^qqebkloqe%0.+0)/-+0&)tbpq%//+1)/1+/&)plrqe%/5+0)01+6&)^kaaltkkb^oqebKburp%/5+0)/5+2&y
@Pb`obqplcqeb>k`fbkqpyNFAy..6.-yyKyHfiiJ^df`*_lrka>k`fbkq^olrka%/4+6)0/+1&^kaDi^`f^i>k`fbkq%0.+3)/1+1&^ka%/.+0)0.+6&y
@Krqpclo?boofbpyNFAy..6./yyKyPmob^aqeolrdelrq@lia^oo^)`liib`qqebjtefibnrbpqfkdy
@?^pf`Qo^fkfkdyNFAy..6.5yyKyHfiipmbiitb^sbopclrka^olrka%0/+0)/5+4&y
>Mrwwifkd+++yNFAy..61.yyKyQebfqbjXP`fkqfii^qfkdCo^djbkqZpq^oqpnrbpq*aolmmba_v@lia^o^Pmbii_fkabo^olrka%00)0-&yyRy02315y

QOb^afkdqebJbqbopyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6--y
QPb`obqplcqeb>k`fbkqpyKy>o`ej^db?bofk^ka%00+-)01+0&yyNFAy..6.-y
QKrqpclo?boofbpyKyIf_o^of^kPboo^e%00+2)01+1&yyNFAy..6./y
>HbbmqebPb`obqP^cbyKyIf_o^of^kPboo^e%00+2)01+1&yyNFAy..6.1y
Q?^pf`Qo^fkfkdyKyO^bilo^pw%00+0)01+2&yyNFAy..6.5y
>E^q`efkd^Mi^kyKyO^bilo^pw%00+0)01+2&yyNFAy..603y
QMrwwifkd+++yKyO^bilo^pw%00+0)01+2&yyNFAy..61.y
>Qeb@biiyKyO^bilo^pw%00+0)01+2&yyNFAy..610y

@Qeb@biiyNFAy..610yyKyHfiiT^o_ofkdboDlobao^hqlqebtbpq%/1+/)/5+6&^kaDbkbo^i@borib^kqlqebkloqe%/4+2)/-+4&y
@E^q`efkd^Mi^kyNFAy..603yyKyHfii@lia^oo^Tvojhfkproolrkafkd@lia^oo^cloqebfoXColwbk>ubZ)qebkrpbqebjlkqebbddpkb^oqebKburp%/5+2)/5+6&yyRy02253y
@HbbmqebPb`obqP^cbyNFAy..6.1yyKyHfii>o`^kbPbombkqpkb^oqebKburp%/5+2)/5+6&y

QE^q`efkd^Mi^kyKyO^bilo^pw%00+0)01+2&yyNFAy..603y
>Ao^hbErkqyKyO^bilo^pw%00+0)01+2&yyNFAy..6.6y
QQeb@biiyKyO^bilo^pw%00+0)01+2&yyNFAy..610y
>Hbofpqo^pw^yKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZyyNFAy..613yyRy0234.y
QHbofpqo^pw^yKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZyyNFAy..613yyRy0234.y
>?^fq^kaPtfq`eyKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZyyNFAy..62.yyRy0234.y
QHbbmqebPb`obqP^cbyKyIf_o^of^kPboo^e%00+2)01+1&yyNFAy..6.1y

@?^fq^kaPtfq`eyNFAy..62.yyKyIllqqebmromib`ovpq^ipkb^oqebKburp%/5+2)/5+6&y
@Ao^hbErkqyNFAy..6.6yyRy022-3yyKyCfka^KburpAo^hbE^q`eifkdcivfkd^olrkaqlqebtbpqlcqebKburp+EfqfqtfqeXO^bilo^pw$pPmb^oZrkqfi`lkqoliibaqebkabifsboqlO^bilo^pw%00+0)01+2&y
QAo^hbErkqyKyO^bilo^pw%00+0)01+2&yyNFAy..6.6y
>@o^`hfkdqeb@labyKyO^bilo^pw%00+0)01+2&yyNFAy..60.y
@@o^`hfkdqeb@labyNFAy..60.yyKyHfiiFknrfpfqlo@^ibo^pqlqebkloqe%0/+5)/4+5&+XPefjjbofkdOrkbpZaolmcoljqebPmbii_fkabop^olrkaefjy

Q?^fq^kaPtfq`eyKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZyyNFAy..62.yyRy0234.y
>P^o^dlp^$pBkayKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZyyNFAy..624yyRy0234.y
@P^o^dlp^$pBkayNFAy..624yyKyQ^ihqlHbofpqo^pw^clo^qbibmloq+RpbqebX>o`^kbMltboCl`rpZ)qebkhfiieboyyRy0236-y
QP^o^dlp^$pBkayKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZyyNFAy..624yyRy0234.y
>JrpqbofkdqebObapyKyHbofpqo^pw^*RpbqebX>rdjbkqba>o`^kbMofplkZyyNFAy..634yyRy0234.y
QJrpqbofkdqebObapyKyO^bilo^pw%00+0)01+2&)Hbofpqo^pw^tfiimloqvlr_^`hyyNFAy..634y
>PmofkdfkdqebQo^myKyO^bilo^pw%00+0)01+2&yyNFAy..636y
Q@o^`hfkdqeb@labyKyO^bilo^pw%00+0)01+2&yyNFAy..60.y
@PmofkdfkdqebQo^myNFAy..636yyKyEb^aqlKloqe*Tbpqbkqo^k`blcqebKburp^q%/2+5)//+3&+RpbXO^bilo^pw$Pm^ohZ_bprobqlpq^v`ilpbqlHbofpqo^pw^yyRy1162-y
QPmofkdfkdqebQo^myKyO^bilo^pw%00+0)01+2&yyNFAy..636y

QQeb>pp^ppfk^qflklcE^oliaI^kbyKy>o`eAorfaI^qelofrp%24+.)11+0&yyNFAy..56/y

Q@lt^oap^kaCllipyKy>q^fh^%30+5)13+.&yyNFAy..60/y
>QebPlklcH^ohrqyKy>q^fh^%30+5)13+.&yyNFAy./-53y
>KlqTfqelrq^CfdeqyKy>q^fh^%30+5)13+.&yyNFAy..616y
>Mobm^ofkdcloqebTlopqyKyRq^fh%31+-)12+5&yyNFAy..612y

@KlqTfqelrq^CfdeqyNFAy..616yyKyQebo^fabop`^k_bclrka^iilsboH^ph^i^%35+.)15+/&y
@Mobm^ofkdcloqebTlopqyNFAy..612yyKyClrka^iilsboH^ph^i^%35+.)15+/&y

QKlqTfqelrq^CfdeqyKy>q^fh^%30+5)13+.&yyNFAy..616y
>Jr^efq$pTfpaljyKy>q^fh^%30+5)13+.&yyNFAy..62-y
QMobm^ofkdcloqebTlopqyKyRq^fh%31+-)12+5&yyNFAy..612y

QJr^efq$pTfpaljyKyBiaboJr^efq%34+/)21+5&yyNFAy..62-y
>PmfofqpT^q`eLsboRpyKyBiaboJr^efq%34+/)21+5&yyNFAy..63.y
@PmfofqpT^q`eLsboRpyNFAy..63.yyKyEfp_lav`^k_bclrkafkqebt^qbo^q%34+3)2-+1&y
QPmfofqpT^q`eLsboRpyKyBiaboJr^efq%34+/)21+5&yyNFAy..63.y
>QebQfabpQrokyKyBiaboJr^efq%34+/)21+5&yyNFAy..635y
@QebQfabpQrokyNFAy..635yyKyLkqeblqebopfablcqebpq^qrb^q%34+-)23+-&y
QQebQfabpQrokyKyBiaboJr^efq%34+/)21+5&yyNFAy..635y

ORkr$mbyKyQlqebb^pq%45+2)2.+2&yyNFAy..4-5y
cRkr$mbyKy?fihlAofcqpm^oh%45+2)2.+2&yyNFAy..4-5y
CCfww`o^kh>fopqofmyKyProofpqo^pw%12+.2)01+/&ql?fihlAofcqpm^oh%45+2)2.+2&yyNFAy..4-5y
eCfww`o^kh>fopqofmyKy@e^oifbKloqeqlm%24+.).5+5&yyNFAy..4-5y

QAfpqobpp@^iiyKyCfww`o^khCriiqeolqqib%24+-).5+4&yyNFAy..4-4y
>QebJb`e^dkljbpyKyCfww`o^khCriiqeolqqib%24+-).5+4&yyNFAy..4-5y
@QebJb`e^dkljbpyNFAy..4-5yyKyIfpqbkqlCfww`o^khCriiqeolqqib%24+-).5+4&y
QQebJb`e^dkljbpyKyGfkhvTfkdkrq%24+2).5+5&yyNFAy..4-5y
>Ob*@ropfsbyKyGfkhvTfkdkrq%24+2).5+5&yyNFAy..4./y
>Te^q$pqebJ^qqbotfqeqebQo^kpj^qqbo<yKyJloaib@ldpmfkkbo%24+2).5+4&yyNFAy..4.-y
>Afoqv)Pqfkhfk$Pkl_liapyKy@o^cqvTl__ibpmol`hbq%25+/).5+1&yyNFAy..312y

@Afoqv)Pqfkhfk$Pkl_liapyNFAy..312yyKy@o^qbpp`^qqboba^olrka%22+2).1+/&y

QAfoqv)Pqfkhfk$Pkl_liapyKy@o^cqvTl__ibpmol`hbq%25+/).5+1&yyNFAy..312y
>Grpq^CbtJlobQefkdp+++yKy@o^cqvTl__ibpmol`hbq%25+/).5+1&)PhfmqefpfcvlrafaklqdbqqebLsbo`e^odba@^m^`fqloyyNFAy..32-yyLyyIy0635/y

@Ob*@ropfsbyNFAy..4./yyRy01640yyKyDlhfiijb`e^dkljbpqlqebb^pq%30+1)//+4&^karpbqebXOb*@ropfsbQo^kpj^qqboFkgb`qflkZlkqebjy

>QebRiqo^plkf`P`obtaofsboyNFAy..4/6yyKyQebfqbjXQebRiqo^plkf`P`obtaofsboZpq^oqpqefpnrbpq+Hfiiol_lqp^olrka%31)//&qfiivlrdbqfqyyRy01651y
QQebRiqo^plkf`P`obtaofsboyKy@o^cqvTl__ibpmol`hbq%25+/).5+1&yyNFAy..4/6y
>J^pqbo^kaPbos^kqyKy@o^cqvTl__ibpmol`hbq%25+/).5+1&yyNFAy..40-y
QOb*@ropfsbyKyGfkhvTfkdkrq%24+2).5+5&yyNFAy..4./y
>IbcqvIllpbv)OfdeqvQfdeqvyKyGfkhvTfkdkrq%24+2).5+5&yyNFAy..455y

KQebRiqo^plkf`P`obtaofsboyKyRpbXQebRiqo^plkf`P`obtaofsboZlk^kv_lqpvlrhfiicloJ^pqbo^kaPbos^kqyyNFAy..40-y
@IbcqvIllpbv)OfdeqvQfdeqvyNFAy..455yyRy02..3yyKyRpbqeb`lkqolip^qb^`epq^qflkqlprjjlkQtlkhv%3-+/)/-+1&)BA*/.-%32+2).4+2&)J^u?i^pql%30+4)//+1&^kaQebDofkabo%32+/)/5+5&y
@J^pqbo^kaPbos^kqyNFAy..40-yyRy02..3yyKyRpbXQebRiqo^plkf`P`obtaofsboZlk_lqphfiiba^olrka%3/+.)//+2&y

QIbcqvIllpbv)OfdeqvQfdeqvyKyGfkhvTfkdkrq%24+2).5+5&yyNFAy..455y
>QebDb^oj^pqboyKyGfkhvTfkdkrq%24+2).5+5&yyNFAy..465y
QJ^pqbo^kaPbos^kqyKy@o^cqvTl__ibpmol`hbq%25+/).5+1&yyNFAy..40-y
>CfkafkdMfilqQ^fipmfkyKyCfww`o^khCriiqeolqqib%24+-).5+4&yyNFAy..4/2y

KDbq@o^cqv$pQllipyNFAy..32-yyNLy@o^cqv$pQllip7.,.yyKy?biltqebCfww`o^khMrjmfkdPq^qflk%31+1)/0+.&+Phfmqefpfcvlrafak$qdbqqeb`^m^`fqloy
@QebDb^oj^pqboyNFAy..465yyKyEb^armqlqeb_rfiafkdlkqebMrjmfkdPq^qflk%31+2)/0+1&+Ob^aqebj^kr^i)hfiiJb`e^wlay
@Te^q$pqebJ^qqbotfqeqebQo^kpj^qqbo<yNFAy..4.-yyKyDbqqebXCfww`o^khPm^obM^oqpZp`^qqboba^olrka%3/+.)//+2&y

QCfkafkdMfilqQ^fipmfkyKyFddvQ^fipmfk@ldqlddib%3.+4)02+5&yyNFAy..4/2y
>>Ifqqib?fqlcPmf`byKyFddvQ^fipmfk@ldqlddib%3.+4)02+5&yyNFAy..4/3y

@>Ifqqib?fqlcPmf`byNFAy..4/3yyKyHfiiDloil`pqlqebplrqefkqebCillaMi^fkp%32+/)06+4&y

QQebPlklcH^ohrqyKy@lomlo^iSbkk%5/+-)13+2&yyNFAy./-53y
>ProolrkabayKy@lomlo^iSbkk%5/+-)13+2&yyNFAy..611y
>QebIlpq@lrofboyKyMofs^qb@^pbv%5/+.)13+2&yyNFAy./.24y
@Grpq^CbtJlobQefkdp+++yNFAy..32-yyKyHfiiOl`hk^o%5.+/)1/+4&yyLy
@ProolrkabayNFAy..611yyKyHfiiWfddro^qAbcbkabop^olrka%5/+3)10+.&y
QProolrkabayKy@lomlo^iSbkk%5/+-)13+2&yyNFAy..611y
>Qe^pp^of^k)qebAb^qeHkfdeqyKy@lomlo^iSbkk%5/+-)13+2&yyNFAy./-55y
QQe^pp^of^k)qebAb^qeHkfdeqyKyQe^pp^of^k%51+5)1.+3&yyNFAy./-55y
>CfkafkdqebMevi^`qbovyKyQe^pp^of^k%51+5)1.+3&yyNFAy..623y
@CfkafkdqebMevi^`qbovyNFAy..623yyKyEb^a_^`hqlAb^qe$pPq^ka%5/+-)13+2&^kaelmlkqebelopby
QCfkafkdqebMevi^`qbovyKyQe^pp^of^k%51+5)1.+3&yyNFAy..623y
>?rvfkdPljbQfjbyKyQe^pp^of^k%51+5)1.+3&yyNFAy..605y
@?rvfkdPljbQfjbyNFAy..605yyKyClrkafkqebQbjmib@fqvlcBk$hfi^e%50+6)0.+2&y
Q?rvfkdPljbQfjbyKyQe^pp^of^k%51+5)1.+3&yyNFAy..605y
>TloaplcMltboyKyQe^pp^of^k%51+5)1.+3&yyNFAy..61/y
@TloaplcMltboyNFAy..61/yyKyHfiiEfdeMofbpqQ^ibq*He^fk%56+1)/5+6&)EfdeMofbpq>kalo^qe%54+5)/-+4&^kaEfdeMofbpqK^cbopbq%50+6)/-+2&+QlhfiiEfdeMofbpqK^cbopbq)hfiiqebjl_p^olrkaefjcfopqy
QTloaplcMltboyKyQe^pp^of^k%51+5)1.+3&yyNFAy..61/y
>I^pqOfqbpyKyQe^pp^of^k%51+5)1.+3&yyNFAy./-.6y
@I^pqOfqbpyNFAy./-.6yyKyDolrmnrbpq)_rqvlr$iie^sbQe^pp^of^k$pebim+Q^hbqebmloq^irmqlK^uu^k^o%53+2)/5+2&+Qebkq^hbqebmloq^iafob`qiv^_lsbvlr+Phfmfcc^fibay
QI^pqOfqbpyKyQe^pp^of^k%51+5)1.+3&yyNFAy./-.6y

Q>Ifqqib?fqlcPmf`byKyFddvQ^fipmfk@ldqlddib%3.+4)02+5&yyNFAy..4/3y
>IrmrpMrmrpyKyFddvQ^fipmfk@ldqlddib%3.+4)02+5&yyNFAy..4/5y
@IrmrpMrmrpyNFAy..4/5yyRy02./.yyKyRpbqebXTlic?^fqZlkqebtlisbpproolrkafkdFddvQ^fipmfk@ldqlddib%3.+4)02+5&^kaillqqebmllmy
QIrmrpMrmrpyKyFddvQ^fipmfk@ldqlddib%3.+4)02+5&yyNFAy..4/5y
>Bjbodbk`vMolql`li7Pb`qflk5+/)M^o^do^me@yKyFddvQ^fipmfk@ldqlddib%3.+4)02+5&yyNFAy..462y
@Bjbodbk`vMolql`li7Pb`qflk5+/)M^o^do^me@yNFAy..462yyKyIllhcloab^adkljbpp`^qqbobaproolrkafkdFddvQ^fipmfk@ldqlddib%3.+4)02+5&y
QBjbodbk`vMolql`li7Pb`qflk5+/)M^o^do^me@yKyFddvQ^fipmfk@ldqlddib%3.+4)02+5&yyNFAy..462y
>Bjbodbk`vMolql`li7Pb`qflk5+/)M^o^do^meAyKyFddvQ^fipmfk@ldqlddib%3.+4)02+5&yyNFAy..463y
@Bjbodbk`vMolql`li7Pb`qflk5+/)M^o^do^meAyNFAy..463yyRy02//1yyKyRpbqebXBjbodbk`vQlo`eZlkqebPlrqebok%3.+.)06+6&)Kloqetbpqbok%3-+6)00+4&^kaB^pqbokTob`h%30+1)03+6&y
QBjbodbk`vMolql`li7Pb`qflk5+/)M^o^do^meAyKyFddvQ^fipmfk@ldqlddib%3.+4)02+5&yyNFAy..463y
>DfsbCfww`o^khqebKbtpyKyFddvQ^fipmfk@ldqlddib%3.+4)02+5&yyNFAy..540y

>P`lrqfkdqebPfkhelibpyKy>_kboCfwwibqlonrb%24+.)/-+.&yyNFAy..4.0y
@P`lrqfkdqebPfkhelibpyNFAy..4.0yyRy016/-yyKyRpbqebXJ^mlcqebDbvpboCfbiapZ^qqebKloqetbpq%33+/)0/+/&)Kloqeb^pq%36+4)0/+.&^kaPlrqePfkhelib%4-+/)03+0&y
QP`lrqfkdqebPfkhelibpyKy>_kboCfwwibqlonrb%24+.)/-+.&yyNFAy..4.0y
>CrbifkdqebMolgb`qyKy>_kboCfwwibqlonrb%24+.)/-+.&yyNFAy..4.2y
@CrbifkdqebMolgb`qyNFAy..4.2yyRy01642yyKyRpbqebXMloq^_ibLfi@liib`qloZlkqeblfipmlrqpfkqebmllipafob`qivplrqelcqltk%24+6)/1+.&y
QCrbifkdqebMolgb`qyKy>_kboCfwwibqlonrb%24+.)/-+.&yyNFAy..4.2y
>>?lqfkJ^jjlqe$p@ilqefkdyKy>_kboCfwwibqlonrb%24+.)/-+.&yyNFAy..4.5y
QDfsbCfww`o^khqebKbtpyKyCfww`o^khCriiqeolqqib%24+-).5+4&yyNFAy..540y
QQebDb^oj^pqboyKyCfww`o^khCriiqeolqqib%24+-).5+4&yyNFAy..465y
QTe^q$pqebJ^qqbotfqeqebQo^kpj^qqbo<yKyJloaib@ldpmfkkbo%24+2).5+4&yyNFAy..4.-y
>@eb`hfkTfqe?fufbyKyJloaib@ldpmfkkbo%24+2).5+4&yyNFAy..36/y
>HfkdJodi*JodiyKyJloaib@ldpmfkkbo%24+2).5+4&yyNFAy..4-1y
QGrpq^CbtJlobQefkdp+++yKy@o^cqvTl__ibpmol`hbq%25+/).5+1&yyNFAy..32-y
>E^e+++Vlr$obKlqPl?fdKltyKy@o^cqvTl__ibpmol`hbq%25+/).5+1&yyNFAy..320y
@E^e+++Vlr$obKlqPl?fdKltyNFAy..320yyLyyRy015./yyKyRpbX@o^cqv$pRiqo^*>as^k`baMolql*Qvmf`^iPeloqbkfkd?i^pqboZlkJ^djlqe@orpeboploJ^qbplcJ^djlqeobd^o^olrka%22)./&y
QE^e+++Vlr$obKlqPl?fdKltyKy@o^cqvTl__ibpmol`hbq%25+/).5+1&yyNFAy..320yyLy
>Mi^k?yKy@o^cqvTl__ibpmol`hbq%25+/).5+1&yyNFAy..325y

@Mi^k?yNFAy..325yyKyTbpq^qPqbbig^t$p@^o^s^k%16+3)/3+3&yyLy

QHfkdJodi*JodiyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..4-1y
>Ib^okfkdql@ljjrkf`^qbyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..24.y
@Ib^okfkdql@ljjrkf`^qbyNFAy..24.yyKyAfsbaltkqlqebTbpqofcq%1/+4).2+5&)hfiiqebP`^iabo^karpbXQebHfkd$pBjmqv@lk`eZyyRy01265y
QIb^okfkdql@ljjrkf`^qbyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..24.y
>Tfkqbocfk@ljjbo`byKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..226y
@Tfkqbocfk@ljjbo`byNFAy..226yyKyAfsbcloXTfkqbocfk@i^jpZlocfkaqebpb^olrkaqeb`^jm^q%1-+/).3+-&y
QTfkqbocfk@ljjbo`byKy>eirodido%10+-).0+5&yyNFAy..226y
>QebjyKy?odijrodi%1/+6).0+4&yyNFAy..23.y
>LeKlbp)qebQ^amlibpyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..23-y

@JlkfqlofkdqebOfcq7Tfkqbocfk@^sbokyNFAy./4/5yyKyEb^a^`olppqlqebTfkqbocfk@^sbokp%06+6)/-+.&)rpbqebX>o`^kljbqboZyyRy01336y
>Hbvj^pqboRojdodiyKyDiodiodio%04+5)/0+.&yyNFAy..236y
@Hbvj^pqboRojdodiyNFAy..236yyKyEb^acroqeboaltk)hfiiHbvj^pqboRojdodi%06+0)/0+2&y
QHbvj^pqboRojdodiyKyDiodiodio%04+5)/0+.&yyNFAy..236y
>Bp`^mbcoljqebTfkqbocfk@^sbokpyKyIroddi_o%04+5)/0+-&yyNFAy..24-y
@Bp`^mbcoljqebTfkqbocfk@^sbokpyNFAy..24-yyKyBp`loqIroddi_o%04+5)/0+-&lrqlcqeb@^sbokpy
@LeKlbp)qebQ^amlibpyNFAy..23-yyKyLmbkrmqeb`^dbp^olrka%1.+-).2+/&^kacobbqebq^amlibpy
@QebjyNFAy..23.yyKyHfiiqebjroil`p^olrka%1.+-).2+/&y

QQebjyKy?odijrodi%1/+6).0+4&yyNFAy..23.y
QLeKlbp)qebQ^amlibpyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..23-y
>F$j?bfkd?i^`hj^fiba?vJv@ib^kboyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..23/y
QBp`^mbcoljqebTfkqbocfk@^sbokpyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..24-y
QF$j?bfkd?i^`hj^fiba?vJv@ib^kboyKyJojodijo%1/+-)./+5&yyNFAy..23/y
>DojjroddiiJoiiddoiDioddiyKyJojodijo%1/+-)./+5&yyNFAy..230y
>Pr``ribkqLo`^PqbtyKy@ib^sbo?jrodi_oj%1/+-).0+.&yyNFAy..231y

@DojjroddiiJoiiddoiDioddiyNFAy..230yyKyKloqe^olrkaDifjjbo?^v%06+0)4+6&y
@Pr``ribkqLo`^PqbtyNFAy..231yyKyHfiiqeblo`^ptef`eproolrkaDifjjbo?^v^olrka%1-)..&y

QPr``ribkqLo`^PqbtyKy@ib^sbo?jrodi_oj%1/+-).0+.&yyNFAy..231y
QDojjroddiiJoiiddoiDioddiyKyJojodijo%1/+-)./+5&yyNFAy..230y
>QebPm^obPrfqyKyJojodijo%1/+-)./+5&yyNFAy..232y
QQebPm^obPrfqyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..232y
>Proobkabo+++KlqyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..233y
@Proobkabo+++KlqyNFAy..233yyRy013/-yyKyEb^alsboqlqeb`^sb)rpbXHfkdJodi*Jodi$pPm^obPrfqZ^kahfii@i^ufjrp%04+4)/4+.&y
QProobkabo+++KlqyKyHfkdJodi*Jodi%10+2).1+-&yyNFAy..233y

@>?lqfkJ^jjlqe$p@ilqefkdyNFAy..4.5yyKyHfiij^jjlqeplkvlrot^v_^`hqlqeb^fopqofm^olrka%25+-)0/+-&+Qeb_^_fbpaolmqebefabpqlly

Q>?lqfkJ^jjlqe$p@ilqefkdyKy>_kboCfwwibqlonrb%24+.)/-+.&yyNFAy..4.5y
>AbmilvqebPe^hb*k*Nr^hbyKy>_kboCfwwibqlonrb%24+.)/-+.&yyNFAy..4/0y
QMi^k?yKy@o^cqvTl__ibpmol`hbq%25+/).5+1&yyNFAy..325y
>FqT^pQebLo`p)ElkbpqyKy@o^cqvTl__ibpmol`hbq%25+/).5+1&yyNFAy..34-y

@FqT^pQebLo`p)ElkbpqyNFAy..34-yyKyEb^aqlqeb`^sbfkJ^djlqe%21+.).0+0&)lmbkX@o^cqv$pP^`hZ)mrqlkqebXT^oplkdLo`AfpdrfpbZ)hfiiJ^djlqeobd^o^kami^kqqeb_^kkbofkefp`lompbyyRy01536yyLy
>DbqJbLrq^EbobyKy?lkhboQlddibsliq%22+3)./+3&yyNFAy..340y
@DbqJbLrq^EbobyNFAy..340yyLyyKyBp`loq?lkhboQlddibsliq%22+3)./+3&rkqfip^cby

QDbqJbLrq^EbobyKyCfww`o^khCriiqeolqqib%24+-).5+4&yyNFAy..340yyLy
QFqT^pQebLo`p)ElkbpqyKy@o^cqvTl__ibpmol`hbq%25+/).5+1&yyNFAy..34-yyLy

Q@eb`hfkTfqe?fufbyKy?fufbTobk`epe^khbo%40+2).5+6&yyNFAy..36/y
>LeDob^q+++Mi^drbaJ^dk^q^royKy?fufbTobk`epe^khbo%40+2).5+6&yyNFAy..360y
@LeDob^q+++Mi^drbaJ^dk^q^royNFAy..360yyKy%43+-).5+-&fkqebAbklcqebavfkdy
QLeDob^q+++Mi^drbaJ^dk^q^royKy?fufbTobk`epe^khbo%40+2).5+6&yyNFAy..360y
>Qebob$pPljbqefkdDlfkdLkFkQelpb@^sbpyKy?fufbTobk`epe^khbo%40+2).5+6&yyNFAy..361y
@Qebob$pPljbqefkdDlfkdLkFkQelpb@^sbpyNFAy..361yyRy016.2yyKyEb^armqlqeb`^sb%41+5).1+/&^karpbX?fufb$pFkef_fqfkdMltaboZlkqeb`^riaolky
QQebob$pPljbqefkdDlfkdLkFkQelpb@^sbpyKy?fufbTobk`epe^khbo%40+2).5+6&yyNFAy..361y
>O^qp)QfkhvTbkqfkqlqebKb`olmlifpyKy?fufbTobk`epe^khbo%40+2).5+6&yyNFAy..364y
>Jfdeq>pTbiiTfmbLrqqebP`lrodbyKy?fufbTobk`epe^khbo%40+2).5+6&yyNFAy..365y
QO^qp)QfkhvTbkqfkqlqebKb`olmlifpyKyQfkhvTf`htefpqib%36+6).1+4&yyNFAy..364y
>F$jPqr`hfkqefpA^jkba@^db+++?rqKlqCloIlkdyKyQfkhvTf`htefpqib%36+6).1+4&yyNFAy..366y
@F$jPqr`hfkqefpA^jkba@^db+++?rqKlqCloIlkdyNFAy..366yyKyQ^hbqebo^jm^_lsbQfkhv%36+2).2+4&rmqlqebqlm+HfiiAl`qloO^wlodofkcloqebXJ^df`^iDvolp`lmbZ)If`e*Iloa@efiitfkqbocloqebXMfilqfkdP`lrodbpqlkbZ)^kaCbpqbofkdDelripcloqebXBkdfkb*@lob@ovpq^iZy
QF$jPqr`hfkqefpA^jkba@^db+++?rqKlqCloIlkdyKyQfkhvTf`htefpqib%36+6).1+4&yyNFAy..366y
>Ibq?fufbHkltyKyQfkhvTf`htefpqib%36+6).1+4&yyNFAy..4--y
@Jfdeq>pTbiiTfmbLrqqebP`lrodbyNFAy..365yyKyHfiiP`lrodbproolrkafkd%32+5).2+-&y
QJfdeq>pTbiiTfmbLrqqebP`lrodbyKy?fufbTobk`epe^khbo%40+2).5+6&yyNFAy..365y
QIbq?fufbHkltyKy?fufbTobk`epe^khbo%40+2).5+6&yyNFAy..4--y
>?^`hqlqeb>fopqofmyKy?fufbTobk`epe^khbo%40+2).5+6&yyNFAy..4-.y

@AbmilvqebPe^hb*k*Nr^hbyNFAy..4/0yyRy0165.yyKyEb^aaltkqlqebplrqepfkhelib%4-+-)04+.&^karpbqebXPe^hb*k*Nr^hb2---@lkqoliRkfqZy

Q?^`hqlqeb>fopqofmyKyCfww`o^khCriiqeolqqib%24+-).5+4&yyNFAy..4-.y

QAbmilvqebPe^hb*k*Nr^hbyKy>_kboCfwwibqlonrb%24+.)/-+.&yyNFAy..4/0y
QJlkfqlofkdqebOfcq7Tfkqbocfk@^sbokyKyIf_o^of^kD^oobk%12+-)00+2&yyNFAy./4/5y

CRkr$mbyKyH^o^Qeof`bpq^o%23+3)/-+.&ql?fihlAofcqpm^oh%45+2)2.+2&yyNFAy./.4.y
OAo^dlk_ifdeqyKyQlcfka@lrofboI^kplk%/5+6)23+.&yyWyAo^dlk_ifdeqyyNFAy./.4.y
QQebIlpq@lrofboyKy@lrofboI^kplk%/5+6)23+.&yyNFAy./.24yyWyAo^dlk_ifdeqy
>LcQo^fqlop^kaQob^plkyKy@lrofboI^kplk%/5+6)23+.&yyNFAy./.4.yyWyAo^dlk_ifdeqy
QLcQo^fqlop^kaQob^plkyKyM^ibk^Pfisbo`ilra%/6+/)22+1&yyNFAy./.4.yyWyAo^dlk_ifdeqy
>Efde@ljj^kaboE^icloaTvoj_^kbyKyM^ibk^Pfisbo`ilra%/6+/)22+1&yyNFAy./.41yyWyAo^dlk_ifdeqy
QEfde@ljj^kaboE^icloaTvoj_^kbyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy./.41yyWyAo^dlk_ifdeqy
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
