DugisGuideViewer:RegisterGuide("Howling Fjord (71-73)", "Dragonblight (73-75)", "Alliance", "L", function()
return [[
AAA

eS^id^oabyKyFkkhbbmboE^wbiI^do^p%25+1)3/+2&yyNFAy..//5y
cS^id^oabyKyMof`fii^Tfkqbotfka%26+4)30+0&yyNFAy..//5y

>EbiiE^pColwbkLsbo+++yKyJ^`^iolv%3-+5)3/+2&yyNFAy..//5y
QEbiiE^pColwbkLsbo+++yKySf`b>ajfo^iHbiibo%3-+2)3.+/&yyNFAy..//5y
>FcS^id^oabC^iip+++yKySf`b>ajfo^iHbiibo%3-+2)3.+/&yyNFAy../10y

@FcS^id^oabC^iip+++yNFAy../10yyKyHfiiAo^dlkci^vboFks^abop%25+5)26+1&lkqebkloqebadblcqltky

QFcS^id^oabC^iip+++yKySf`b>ajfo^iHbiibo%3-+2)3.+/&yyNFAy../10y
>Obp`rfkdqebObp`rbopyKySf`b>ajfo^iHbiibo%3-+2)3.+/&yyNFAy../11y

@Obp`rfkdqebObp`rbopyNFAy../11yyKyKloqe^`olppqebpqob^j%25+3)24+/&y

QObp`rfkdqebObp`rbopyKySf`b>ajfo^iHbiibo%3-+2)3.+/&yyNFAy../11y
>MofplkboplcTvojphriiyKySf`b>ajfo^iHbiibo%3-+2)3.+/&yyNFAy../22y
>QebErj^kIb^drbyKy?biqo^kaJ`Ploc%3-+/)3.+-&yyNFAy../40y
>QebM^qeqlM^v_^`hyKyDr^oa@^mq^fkWlobh%3-+.)3/+1&yyNFAy..1/-y
>FkqlqebTloialcPmfofqpyKyQelo^ifrpqebTfpb%26+5)3.+2&yyNFAy..000y

>A^ddbo`^mAfsfk$yKyE^oliaI^do^p%3/+5)26+-&yyNFAy..110y
RMrqlkqebXAfsfkdEbijZyRy01-5/yyNFAy../41y
@FkqlqebTloialcPmfofqpyNFAy..000yyKyLkqebab`hlcqebkloqebok_l^q%3/+.)24+4&y
@A^ddbo`^mAfsfk$yNFAy..110yyKyClrka^olrkaqebt^qbo^q%3/+2)24+6&y
QA^ddbo`^mAfsfk$yKyE^oliaI^do^p%3/+5)26+-&yyNFAy..110y

QQebErj^kIb^drbyKyMriolvqeb>o`e^blildfpq%26+.)21+2&yyNFAy../40y
>Wbaa$pMol_^_ivAb^ayKyMriolvqeb>o`e^blildfpq%26+.)21+2&yyNFAy../41y
QWbaa$pMol_^_ivAb^ayKyWbaa%23+3)2/+2&yyNFAy../41y
>>kaQebkQebobTbobQtl+++yKyWbaa%23+3)2/+2&yyNFAy../43y

Q>kaQebkQebobTbobQtl+++yKyQ^hbqeb_ofadblsboqebtlodmfq%24+-)20+-&^kaeb^aaltkfkqlqebRqd^oab@^q^`lj_p^kaq^ihqlDilobkcbia%23+6)20+5&yyNFAy../43y
>QebAbmqeplcAbmo^sfqvyKyDilobkcbia%23+6)20+5&yyNFAy../44y
>QebPefkfkdIfdeqyKy>obpqebL^qe_lrka%26+0)22+2&yyNFAy../55y
@QebPefkfkdIfdeqyNFAy../55yyKy?^`haltkqebe^ii)altkqebpq^fop)t^abqeor^_rk`elcrkab^a%23+-)20+-&+Qebobfp^.-jfkqfjboy
QQebPefkfkdIfdeqyKy>obpqebL^qe_lrka%26+0)22+2&yyNFAy../55y
>Drfaba_vElkloyKy>obpqebL^qe_lrka%26+0)22+2&yyNFAy../56y
@QebM^qeqlM^v_^`hyKyQebXE^omllkLmbo^qflkJ^kr^iZfpfkqeb`^q^`lj_p^q%26+/)22+1&yyNFAy..1/-y
@QebAbmqeplcAbmo^sfqvyKyXTvojphriiQ^_ibqpZ^obp`^qqboba^iilsboqeb`^q^`lj_p%26+/)22+1&yyNFAy../44y
QQebAbmqeplcAbmo^sfqvyKyDilobkcbia%23+6)20+5&yyNFAy../44y
>QebOfkdlcGradbjbkqyKyDilobkcbia%23+6)20+5&yyNFAy../66y
QQebOfkdlcGradbjbkqyKyA^bd^ok%22+4)24+0&yyNFAy../66y
>PqrkkfkdAbcb^q^qqebOfkdyKyA^bd^ok%22+4)24+0&yyNFAy..0--y
@PqrkkfkdAbcb^q^qqebOfkdyNFAy..0--yyKyAltkpq^fopfkqeb`^q^`lj_^q%21+-)24+-&)Hfiik^jbajl_prkqfiX>k`fbkq@fmeboZaolmpy
QPqrkkfkdAbcb^q^qqebOfkdyKyDilobkcbia%23+6)20+5&yyNFAy..0--y
>ObqrokqlS^id^oabyKyDilobkcbia%23+6)20+5&yyNFAy../45y
@MofplkboplcTvojphriiyKyHfiisovhri^olrka%25+3)21+0&^karkil`h`^dbpqlobib^pb@^mqrobaS^id^oabpyyNFAy../22y

QObqrokqlS^id^oabyKy?biqo^kaJ`Ploc%3-+/)3.+-&yyNFAy../45y
>QebBumilobop$Ib^drbLrqmlpqyKy?biqo^kaJ`Ploc%3-+/)3.+-&yyNFAy..115y
QMofplkboplcTvojphriiyKySf`b>ajfo^iHbiibo%3-+2)3.+/&yyNFAy../22y
>Ao^dlkci^vbo?^qqibMi^kpyKySf`b>ajfo^iHbiibo%3-+2)3.+/&yyNFAy../6-y
QQebM^qeqlM^v_^`hyKyDr^oa@^mq^fkWlobh%3-+.)3/+1&yyNFAy..1/-y
>Il`^qfkdqebJb`e^kfpjyKyDr^oa@^mq^fkWlobh%3-+.)3/+1&yyNFAy..1/3y
QDrfaba_vElkloyKyIloaForilkQorb_i^ab%26+5)3/+1&yyNFAy../56y
QFkqlqebTloialcPmfofqpyKyQelo^ifrpqebTfpb%26+5)3.+2&yyNFAy..000y
>QebB`ellcVjfolkyKyQelo^ifrpqebTfpb%26+5)3.+2&yyNFAy..010y

>CobpeIbdpyKyP`lrqS^ilov%23+-)22+5&yyNFAy../2.y
@Ao^dlkci^vbo?^qqibMi^kpyNFAy../6-yyKyFk^`^sblkqebbadblcqebtlodmfq%22+4)2/+3&y
@QebB`ellcVjfolkyNFAy..010yyRy00304yyKyRpbqebXFk`bkpb?rokboZ)dlfkqeb_rfiafkdkb^oqebe^omllkbop%3-+0)2.+2&y
@Il`^qfkdqebJb`e^kfpjyKyHfiiAo^dlkci^vboE^omllkbop^olrka%3-+-)2.+-&cloXE^omllk@lkqoliJb`e^kfpjZyyNFAy..1/3y
QCobpeIbdpyKyAbcbkaboJloark%26+2)15+6&*Phfmqebcliilt*rmrkibppvlrmi^klkalfkdRqd^oabHbbmyyNFAy../2.y

QAo^dlkci^vbo?^qqibMi^kpyKySf`b>ajfo^iHbiibo%3-+2)3.+/&yyNFAy../6-y
>QlTbpqdr^oaHbbmyKySf`b>ajfo^iHbiibo%3-+2)3.+/&yyNFAy../6.y
QQebB`ellcVjfolkyKyQelo^ifrpqebTfpb%26+5)3.+2&yyNFAy..010y
>>kdrfpelcKfccibs^oyKyQelo^ifrpqebTfpb%26+5)3.+2&yyNFAy..011y
QIl`^qfkdqebJb`e^kfpjyKyDr^oa@^mq^fkWlobh%3-+.)3/+1&yyNFAy..1/3y
>JbbqIfbrqbk^kqF`be^jjbo+++yKyDr^oa@^mq^fkWlobh%3-+.)3/+1&yyNFAy..1/4y

QJbbqIfbrqbk^kqF`be^jjbo+++yKyIfbrqbk^kqF`be^jjbo%31+2)13+6&yyNFAy..1/4y
>AolmFqqebkOl`hFqyKyIfbrqbk^kqF`be^jjbo%31+2)13+6&yyNFAy..1/6y
@AolmFqqebkOl`hFqyNFAy..1/6yyKyMi^`bqebX>iif^k`b?^kkboZ^qqeb`bkqbolcqltkfk?^ibebfj%31+6)06+5&)0sovhritfii`ljb^ka^qq^`hyyRy01-2.y
QAolmFqqebkOl`hFqyKyIfbrqbk^kqF`be^jjbo%31+2)13+6&yyNFAy..1/6y
>E^omllkJ^pqboV^srpyKyIfbrqbk^kqF`be^jjbo%31+2)13+6&yyNFAy..10-y

@E^omllkJ^pqboV^srpyNFAy..10-yyKyHfiiE^omllkJ^pqboV^srpfkqebplrqebok_rfiafkd^qKfccibs^o%32+0)23+2&y
@>kdrfpelcKfccibs^oyNFAy..011yyKyRpbqebXFk`bkpb?rokboZ^kat^q`eqebci^pe_^`h+Fqpbbjpvlrkbbaql_bkb^oHfkdVjfolk%36+.)21+5&qldbq`obafqyyRy00441y

QE^omllkJ^pqboV^srpyKyIfbrqbk^kqF`be^jjbo%31+2)13+6&yyNFAy..10-y
>FqDlbpql..+++yKyIfbrqbk^kqF`be^jjbo%31+2)13+6&yyNFAy..1/.y
@FqDlbpql..+++yNFAy..1/.yyRy01-0/yyKyRpbqebXE^omllk@lkqoliJb`e^kfpjZ^qlkblcqebqtle^ollkpfkKfccibs^o%31+5)2/+4&%31+3)21+0&+Q^odbqqebabcbkabopqlpellq^qqebjy
QFqDlbpql..+++yKyIfbrqbk^kqF`be^jjbo%31+2)13+6&yyNFAy..1/.y
>Ibq$pDlProcfkdKltyKyIfbrqbk^kqF`be^jjbo%31+2)13+6&yyNFAy..103y
@Ibq$pDlProcfkdKltyNFAy..103yyKyMriiqebibsbo^qqebe^omllk^q%32+0)24+/&y

QIbq$pDlProcfkdKltyKyDr^oa@^mq^fkWlobh%3-+.)3/+1&yyNFAy..103y
Q>kdrfpelcKfccibs^oyKyQelo^ifrpqebTfpb%26+5)3.+2&yyNFAy..011y

CBumilobop$Ib^drbLrqmlpqyKyJ`Dlvsbo%3-+4)3.+2&yyNFAy..141y
QQebBumilobop$Ib^drbLrqmlpqyKyPq^kt^a%41+6)32+2&yyNFAy..115y
>Mol_ibjplkqebEfde?irccyKyPq^kt^a%41+6)32+2&yyNFAy..141y
QMol_ibjplkqebEfde?irccyKyT^iq%42+-)32+2&yyNFAy..141y
>QllipqlDbqqebGl_AlkbyKyT^iq%42+-)32+2&yyNFAy..142y
>QorpqfpB^okbayKyEfa^idlqebJ^pqboC^i`lkbo%42+0)32+-&yyNFAy..13-y

>LrqlcJvBibjbkq<yKyAlkkv%45+5)15+6&yyNFAy..144y
@QllipqlDbqqebGl_AlkbyNFAy..142yyKyQebX?rfiafkdQllipZ^obfk^_r`hbqlk^mi^qclojfkqebafd%46+-)14+3&y
@LrqlcJvBibjbkq<yNFAy..144yyKyAbpqolvbop^ob^olrkaqeblrqpfab^_lsbqebafd%45+4)13+4&y
QLrqlcJvBibjbkq<yKyAlkkv%45+5)15+6&yyNFAy..144y

KCfka^XCgloaDor_ZyKyRkaboillpbol`hp^olrka%4/+-)32+0&yyIy01.-/yyNFAy..13-y
@QorpqfpB^okbayNFAy..13-yyKy?^`h^qqebBumilobop$Ib^drbLrqmlpq%42+0)31+6&+CbbaqebXCgloaDor_Zqlqebcli`lkfkqeb`^dby
QQorpqfpB^okbayKyEfa^idlqebJ^pqboC^i`lkbo%42+0)32+-&yyNFAy..13-y
>QebO^kp^`hba@^o^s^kyKyEfa^idlqebJ^pqboC^i`lkbo%42+0)32+-&yyNFAy..132y
QQllipqlDbqqebGl_AlkbyKyT^iq%42+-)32+2&yyNFAy..142y
>Tb@^kOb_rfiaFqyKyT^iq%42+-)32+2&yyNFAy..150y
>TbE^sbqebQb`eklildvyKyT^iq%42+-)32+2&yyNFAy..151y

@QebO^kp^`hba@^o^s^kyNFAy..132yyKyCfkajlobXCgloaDor_pZ%4/+-)32+0&)qebkibqqebc^i`lkillpblkqrohbvp^olrka%36+-)32+-&yyRy01...y

HPelsbiqrphpyKyHfiiPelsbiqrph%36)32&rkqfivlrdbq^XMofpqfkbPelsbiqrphEfabZyyNFAy..151yyNLyMofpqfkbPelsbiqrphEfab7.,.y
KFkarpqof^iPqobkdqeOlmbyNFAy..150yyNLyFkarpqof^iPqobkdqeOlmb7.,.yyKyKloqefk?^ibebfj%31+5)1-+6&y
KI^odb?^oobiyNFAy..150yyNLyI^odb?^oobi7.,.yyKyPlrqefkKfccibs^o%34+1)23+1&y
@TbE^sbqebQb`eklildvyNFAy..151yyKyHfiisovhri^olrka%30+-)1-+-&qfiivlrmf`hrmqebXPqbbiOf__fkdZy
@Tb@^kOb_rfiaFqyNFAy..150yyKyQ^hbqebbumobppe^omllkaltkqlS^id^oab+DbqqebfkdlqpcoljJ`Dlvsbo%3-+5)3.+2&)qebkq^hbpefpcifdeq_^`hqlqebBumilobop$Ib^drbLrqmlpq+y

QQebO^kp^`hba@^o^s^kyKyEfa^idlqebJ^pqboC^i`lkbo%42+0)32+-&yyNFAy..132y
>C^i`lkSboprpE^thyKyEfa^idlqebJ^pqboC^i`lkbo%42+0)32+-&yyNFAy..135y
QTb@^kOb_rfiaFqyKyT^iq%42+-)32+2&yyNFAy..150y
QTbE^sbqebQb`eklildvyKyT^iq%42+-)32+2&yyNFAy..151y
>FolkOrkb@lkpqor`qp^kaVlr7Ol`hbqGrjmfkdyKyT^iq%42+-)32+2&yyNFAy..152y
@FolkOrkb@lkpqor`qp^kaVlr7Ol`hbqGrjmfkdyNFAy..152yyKyOfdeq`if`hlkqebbjmqvtloh_bk`e_befkaqebnrbpqdfsbo%4-+-)32+2&)qebk^`qfs^qbqebol`hbqgrjm^_fifqvy
QFolkOrkb@lkpqor`qp^kaVlr7Ol`hbqGrjmfkdyKyT^iq%42+-)32+2&yyNFAy..152y
>FolkOrkb@lkpqor`qp^kaVlr7@liib`qfkdA^q^yKyT^iq%42+-)32+2&yyNFAy..156y
@FolkOrkb@lkpqor`qp^kaVlr7@liib`qfkdA^q^yNFAy..156yyKyDbqqebprfqcoljqebtloh_bk`e_befkaqebnrbpqdfsbo)^karpb^qqebt^dlk^q%41+-)32+-&y
QFolkOrkb@lkpqor`qp^kaVlr7@liib`qfkdA^q^yKyT^iq%42+-)32+2&yyNFAy..156y
>FolkOrkb@lkpqor`qp^kaVlr7Qeb?irccyKyT^iq%42+-)32+2&yyNFAy..16.y
@FolkOrkb@lkpqor`qp^kaVlr7Qeb?irccyNFAy..16.yyKyT^ihlsboqlIb_olkphf%41+5)32+0&pq^kalkqebord^kat^fqcloefjqlpmb^hqebkmrpeqeb_ircc_rqqlkrkqfi`ljmibqbay
QFolkOrkb@lkpqor`qp^kaVlr7Qeb?irccyKyT^iq%42+-)32+2&yyNFAy..16.y
>IfdeqkfkdFkcrpbaObif`pyKyT^iq%42+-)32+2&yyNFAy..161y
>QebAbif`^qbPlrkalcQerkaboyKyT^iq%42+-)32+2&yyNFAy..162y

@QebAbif`^qbPlrkalcQerkaboyNFAy..162yyKyPlrqe^q?^bidrk$pBu`^s^qflkPfqb+Q^hbqeb`bkqboorkb%4/+.)4-+1&)eb^armfkqlqeb`^sbql%4.+3)36+5&+?bprobqlrpbqebfolkorkb`lkpqor`qy
@IfdeqkfkdFkcrpbaObif`pyNFAy..161yyKyRpbqebfolkorkb`lkpqor`qprfq^kat^ihlsboql^olrka%40+-)35+-&^katlohvlrot^valtk+@liib`qa^q^^kafclkblcqebFolkOrkbpnrbpqflkvlrrpbvlro_irccphfiiy
@C^i`lkSboprpE^thyNFAy..135yyKyCfkador_p)pbkaqebXQo^fkbaOl`hC^i`lkZ^cqboe^thp^olrka%36+2)35+2&yyRy01./.y

QIfdeqkfkdFkcrpbaObif`pyKyT^iq%42+-)32+2&yyNFAy..161y
QQebAbif`^qbPlrkalcQerkaboyKyT^iq%42+-)32+2&yyNFAy..162y
>KbtpColjqebB^pqyKyT^iq%42+-)32+2&yyNFAy..2-.y
QC^i`lkSboprpE^thyKyEfa^idlqebJ^pqboC^i`lkbo%42+0)32+-&yyNFAy..135y
>QebobBufpqpKlElklo>jlkd?foapyKyEfa^idlqebJ^pqboC^i`lkbo%42+0)32+-&yyNFAy..14-y
@QebobBufpqpKlElklo>jlkd?foapyNFAy..14-yyKyCfkaqebsovhrie^thollpqkb^oqebPqlkbt^iiIfcq%43+5)34+3&)rpbqebXQo^fkbaOl`hC^i`lkZ)`liib`qbddplkqeb`ifccp_biltyyRy01./1y
QQebobBufpqpKlElklo>jlkd?foapyKyEfa^idlqebJ^pqboC^i`lkbo%42+0)32+-&yyNFAy..14-y

CTbpqdr^oaHbbmyKyQ^ihqlT^iq%42+-)32+2&^kaq^hbqebcifdeqqlTbpqdr^oaHbbmyyNFAy...24y
eTbpqdr^oaFkkyKyFkkhbbmbo@bibpqbDllaerq`e%0-+6)1.+2&yyNFAy...24y
cTbpqdr^oaHbbmyKyDobboLobe^jjbo%0.+0)11+-&yyNFAy...24y
>Qeb@irq`ebplcBsfiyKy@^mq^fk>a^jp%/5+6)11+/&yyNFAy...24y
QQlTbpqdr^oaHbbmyKy@^mq^fk>a^jp%/5+6)11+/&yyNFAy../6.y
QKbtpColjqebB^pqyKy@^mq^fk>a^jp%/5+6)11+/&yyNFAy..2-.y
>PelsbiqrphPlrm>d^fk<yKy@ebcHbqqib_i^`h%0.+/)1-+6&yyNFAy...22y
>LkbPfwbAlbpKlqCfq>iiyKy@^kklkbboBiv%01+-)10+5&yyNFAy...6-y
KJb^q^ka_^iipyKyHfii^kvpelsbiqrphpvlr`ljb^`olppcloPelsbiqrphPlrm>d^fk<^ka`liib`q^kv`^kklk_^iipvlrpbbcloLkbPfwbAlbpKlqCfq>iib^`e^olrka%03+4)12+2&yyNFAy...22y

>Ollq@^rpbpyKyBj_bo@irq`e>k`fbkq%04+3)2.+3&*M^qolip^olrkaqebBj_bo@irq`eyyNFAy...5/y
@Ollq@^rpbpyKyHfiiPhbiaAo^hbplkfkqeb_rfiafkdlkqebplrqeb^pqbadblcqeb@irq`e%1.+0)20+/&^kae^kaibopfkqebproolrkafkdpyyNFAy...5/y
@Qeb@irq`ebplcBsfiyNFAy...24yyKy?lqejl_p^obclrka^olrka%06+.)16+3&y
QOllq@^rpbpyKyBj_bo@irq`e>k`fbkq%04+3)2.+3&*M^qolip^olrkaqebBj_bo@irq`eyyNFAy...5/y

QQeb@irq`ebplcBsfiyKy@^mq^fk>a^jp%/5+6)11+/&yyNFAy...24y
>J^db*Ifbrqbk^kqJ^ifpqboyKy@^mq^fk>a^jp%/5+6)11+/&yyNFAy...54y
QJ^db*Ifbrqbk^kqJ^ifpqboyKyJ^db*Ifbrqbk^kqJ^ifpqbo%/6+-)11+/&yyNFAy...54y
>QtlTolkdp+++yKyJ^db*Ifbrqbk^kqJ^ifpqbo%/6+-)11+/&yyNFAy...55y
@QtlTolkdp+++yNFAy...55yyKy?^`h^qqebBj_bo@irq`e%06+.)16+3&)rpbXJ^ifpqbo$pColpqT^kaZlkqebcivfkdMolql*Ao^hbp^kahfiiyyRy00..6y
QQtlTolkdp+++yKyJ^db*Ifbrqbk^kqJ^ifpqbo%/6+-)11+/&yyNFAy...55y
>ObmloqqlP`lrqHkltibpyKy@^mq^fk>a^jp%/5+6)11+/&yyNFAy...66y
>LocrplcH^j^dr^yKyIrkh*qrph%0/+0)13+5&yyNFAy..240y

QObmloqqlP`lrqHkltibpyKyP`lrqHkltibp%11+2)24+4&yyNFAy...66y
>Jfppflk7Bqbok^iCi^jbyKyP`lrqHkltibp%11+2)24+4&yyNFAy../-/y
@Jfppflk7Bqbok^iCi^jbyNFAy../-/yyRy00.31yyKyRpbqebXBsbo*_rokfkdQlo`ebpZqlqebkloqeb^pqqlabpqolvqebmi^drbq^khpproolrkafkdE^idofka%15+1)22+6&)%2.+1)24+5&)%2.+1)16+6&)%15+.)2/+6&y
QJfppflk7Bqbok^iCi^jbyKyP`lrqHkltibp%11+2)24+4&yyNFAy../-/y
>Jfppflk7M^`h^dbObqofbs^iyKyP`lrqHkltibp%11+2)24+4&yyNFAy..0/4y
@Jfppflk7M^`h^dbObqofbs^iyNFAy..0/4yyKyCfkaqebX>mlqeb`^ov$pM^`h^dbZaltkfkpfabE^idofka%2-+5)20+6&y
QJfppflk7M^`h^dbObqofbs^iyKyP`lrqHkltibp%11+2)24+4&yyNFAy..0/4y
>Jfppflk7Clop^hbkFkqbiyKyP`lrqHkltibp%11+2)24+4&yyNFAy..0/5y

QLocrplcH^j^dr^yKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..240y
>QebAb^aOfpbyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2-1y
@QebAb^aOfpbyNFAy..2-1yyKyC^oqlqebplrqeb^pq^qPefbiaEfii+Sfpfqb^`edo^sbclo^`irb7Cbkdfo%24+4)44+2&)Olafk%26+/)43+6&)Fprialc%26+5)46+1&)Tfka^k%3.+6)5-+-&y
QQebAb^aOfpbyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2-1y
>Biabo>qrfh^kaH^j^dr^yKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2-4y
QBiabo>qrfh^kaH^j^dr^yKyBiabo>qrfh%/2+-)24+-&yyNFAy..2-4y
eH^j^dr^yKy@^obdfsboFnkfn%/2+1)26+5&yyNFAy..2-5y
cH^j^dr^yKyHfmQo^tiphfm%/1+4)24+6&yyNFAy..2-5y
>DobwwfuPmfkaibpk^myKyBiabo>qrfh%/2+-)24+-&yyNFAy..2-5y
>CbbafkdqebProsfslopyKyBiabo>qrfh%/2+-)24+-&yyNFAy..123y

@CbbafkdqebProsfslopyNFAy..123yyKy>iilsboqebfpi^ka^olrka%0/+2)33+/&y
QCbbafkdqebProsfslopyKyBiabo>qrfh%/2+-)24+-&yyNFAy..123y
>>ojfkdH^j^dr^yKyBiabo>qrfh%/2+-)24+-&yyNFAy..124y
@>ojfkdH^j^dr^yNFAy..124yyKyIlqplkqebkloqebokm^oqlcqebfpi^ka^olrka%/3+-)34+-&y
Q>ojfkdH^j^dr^yKyBiabo>qrfh%/2+-)24+-&yyNFAy..124y
>>sbkdbFph^^iyKyBiabo>qrfh%/2+-)24+-&yyNFAy..125y

QDobwwfuPmfkaibpk^myKyDobwwfuPmfkaibpk^m%/0+.)3/+4&yyNFAy..2-5y
>Pqobbq@obayKyDobwwfuPmfkaibpk^m%/0+.)3/+4&yyNFAy..2-6y

QPqobbq@obayKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2-6y
>P`llaibpyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2.-y
>ClodlqqbkQob^probyKyE^kapljbQboov%02+3)5-+0&yyNFAy..101y

@P`llaibpyNFAy..2.-yyKyGrpqlccpelobqlqebplrqe^olrka%05+-)51+-&)grpqt^fqcloeboqlptfj^olrkay
@ClodlqqbkQob^probyNFAy..101yyRy01-43yyKyAfsbaltkqlqebtob`h^db+RpbqebXCfpe?i^aaboZfcvlrkbba+CfkaqebXB^dibCfdrofkbZfklkb_l^q%04+5)51+3&^kaqebX>j^kfS^pbZfkqeblqebo%04+/)52+3&y

QClodlqqbkQob^probyKyE^kapljbQboov%02+3)5-+0&yyNFAy..101y
>QebCo^do^k`blcJlkbvyKyE^kapljbQboov%02+3)5-+0&yyNFAy..122y
QP`llaibpyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2.-y
>QebPq^cclcPqloj$pCrovyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2..y
>QebColwbkEb^oqlcFprialcyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2./y
>QebIlpqPefbialcqeb>bpfofqbpyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..2.6y
>Qeb>k`fbkq>ojlolcqebHs^iafoyKyPfisbojllkE^oov%02+-)5.+-&yyNFAy..234y
>D^j_ifkdAb_qyKyQ^orh%03+0)5-+2&yyNFAy..131y
@D^j_ifkdAb_qyNFAy..131yyKyPmb^htfqePfisbojllkE^oov%02+-)5.+-&^ka_b^qefjqfiiebdfsbpqebab_qy
QD^j_ifkdAb_qyKyQ^orh%03+0)5-+2&yyNFAy..131y
>G^`hIfhbpEfpAofkhyKyQ^orh%03+0)5-+2&yyNFAy..133y
@G^`hIfhbpEfpAofkhyNFAy..133yyKyFkpfabqeb_rfiafkd)lkqebpb`lkaibsbi%02+2)46+1&+Q^ihqlqeb_^oj^faLid^)qebkmf`hefpml`hbqtebkebm^ppbplrqy
QG^`hIfhbpEfpAofkhyKyQ^orh%03+0)5-+2&yyNFAy..133y
>Ab^aJ^k$pAb_qyKyQ^orh%03+0)5-+2&yyNFAy..134y

@Qeb>k`fbkq>ojlolcqebHs^iafoyNFAy..234yyKyElm^_lj_boofabkb^oqebpelob%03+-)5.+3&Eb^aaltkfkqlqebelialcqebpefm)qebkq^hbqeb_lj_bo_^`hy

>Pt^__fk$Pl^myKyP`rqqibColpqmolt%04+4)46+2&yyNFAy..136y
@Pt^__fk$Pl^myNFAy..136yyKyHfii?fdOlv)plrqetbpqlcqeblqebopb^iflkp%0.+3)44+2&y
@QebCo^do^k`blcJlkbvyNFAy..122yyKyHfiiO^_fa?oltk?b^op^olrka%00+-)46+-&^ka`liib`q1X?b^oJrphpZy

QQebIlpqPefbialcqeb>bpfofqbpyKyT^fqcloqebpefm^q%04+6)41+4&ql_l^oa^kaq^ihql@^mq^fkBiifpyyNFAy..2.6y
>JrqfkvlkqebJbo`vyKyT^fqcloqebpefm^q%04+6)41+4&ql_l^oa^kaq^ihql@^mq^fkBiifpyyNFAy..2/4y
@JrqfkvlkqebJbo`vyNFAy..2/4yyKyAltkfkqebpefm$peliay
QJrqfkvlkqebJbo`vyKyT^fqcloqebpefm^q%04+6)41+4&ql_l^oa^kaq^ihql@^mq^fkBiifpyyNFAy..2/4y
>Ploilc$p?llqvyKyT^fqcloqebpefm^q%04+6)41+4&ql_l^oa^kaq^ihql@^mq^fkBiifpyyNFAy..2/6y
@Ploilc$p?llqvyNFAy..2/6yyKyTebkqebpefmdlbpkb^opelob)rpbqeb`^kklk^qqeblqebobkalcqebpefm)qebkptfjqlpelob^kado^_a^illqpy
QPloilc$p?llqvyKyT^fqcloqebpefm^q%04+6)41+4&ql_l^oa^kaq^ihql@^mq^fkBiifpyyNFAy..2/6y
>QebPefbialcqeb>bpfofqbpyKyT^fqcloqebpefm^q%04+6)41+4&ql_l^oa^kaq^ihql@^mq^fkBiifpyyNFAy..20-y

QPt^__fk$Pl^myKyP`rqqibColpqmolt%04+4)46+2&yyNFAy..136y
QQebCo^do^k`blcJlkbvyKyE^kapljbQboov%02+3)5-+0&yyNFAy..122y
>>Qo^fqlo>jlkdRpyKyE^kapljbQboov%02+3)5-+0&yyNFAy..140y
Q>Qo^fqlo>jlkdRpyKyWbe$dbek%02+3)5-+3&yyNFAy..140y
>Wbe$dbekPbwyKyWbe$dbek%02+3)5-+3&yyNFAy..126y
QWbe$dbekPbwyKyE^kapljbQboov%02+3)5-+0&yyNFAy..126y
>>@^osbo^ka^@ol^hboyKyE^kapljbQboov%02+3)5-+0&yyNFAy..143y
?XPefkvHkfcbZyKyPfisbojllkE^oov%02+-)5.+-&yyIy025.0yyNFAy..146y
@>@^osbo^ka^@ol^hboyNFAy..143yyKy@^mqrob^coldclrka^olrkaqeb`^jmpfqb%03)45&y
Q>@^osbo^ka^@ol^hboyKyWbe$dbek%02+3)5-+3&yyNFAy..143y
>@oltibdA^kyKyWbe$dbek%02+3)5-+3&yyNFAy..146y
@@oltibdA^kyNFAy..146yyKyHfii@oltibdA^klkqebpefm^q%02+6)50+3&y
Q@oltibdA^kyKyE^kapljbQboov%02+3)5-+0&yyNFAy..146y
>JbbqKrj_boQtlyKyE^kapljbQboov%02+3)5-+0&yyNFAy..15-y
QJbbqKrj_boQtlyKy>kkfb?lkk%02+2)46+2&yyNFAy..15-y
>QebGfdfpRmyKy>kkfb?lkk%02+2)46+2&yyNFAy..14.y
@QebGfdfpRmyNFAy..14.yyKyEb^aqlqeb_b^o`^sblkqebkloqepfablcqebfpi^ka%00+3)42+3&+Dlfk)_b^qaltkGlk^e+qebkqeb_b^oqe^qb^qpefj+Dolrmnrbpq)_rqplil^_iby
@QebColwbkEb^oqlcFprialcyNFAy..2./yyKyKb^otebobqeb_b^opm^tkp%0/+1)45+5&y

@Ab^aJ^k$pAb_qyNFAy..134yyKyLkqebkloqefpi^ka)rmlklkblcqebofpbprkaboqebifcq%0/+4)3-+0&y

@>sbkdbFph^^iyNFAy..125yyKyLkqebb^pqpfablcqebfpi^ka%00+6)30+3&+RpbqebXEloklcH^j^dr^Zfckb`bpp^ovyyRy03444y
@QebPq^cclcPqloj$pCrovyNFAy..2..yyKyFkqebelialcqebpefm%02+-)31+-&Pkb^hm^pqqebbifqbtebkebeb^aplkqlqebrmmbo_ltlcqebpefmy

Q>sbkdbFph^^iyKyBiabo>qrfh%/2+-)24+-&yyNFAy..125y
>Qo^sbiqlJl^$hfE^o_loyKy>krkf^n%/1+3)25+5&yyNFAy./..5y
>QebT^vqlEfpEb^oq+++yKy>krkf^n%/1+3)25+5&yyNFAy..14/y
KDbq^_lrq2uXQ^pqvObbcCfpeZyKyCfkacfpep`ellipfkqebt^qbop_bqtbbkqebqtlfpi^kap%01+-)35+-&^karpbX>krkf^n$pKbqZlkqebj+Vlr$iimol_^_ivkbba^qib^pqqeobbp`elli$ptloqe+yyRy1-613yyIy01./42y
@QebT^vqlEfpEb^oq+++yNFAy..14/yyRy01./4yyKyQ^odbq^_rii%0.+-)41+-&lkqebplrqepelob)pq^ka^pc^o^t^v^pvlr`^k^kaqlppefj^cfpe+Jlsbkloqe^kaobmb^qy

QQebGfdfpRmyKy>kkfb?lkk%02+2)46+2&yyNFAy..14.y
QAb^aJ^k$pAb_qyKyQ^orh%03+0)5-+2&yyNFAy..134y

QQebT^vqlEfpEb^oq+++yKy>krkf^n%/1+3)25+5&yyNFAy..14/y
QQebPq^cclcPqloj$pCrovyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2..y
QQebColwbkEb^oqlcFprialcyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..2./y
QQebPefbialcqeb>bpfofqbpyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..20-y
QQeb>k`fbkq>ojlolcqebHs^iafoyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..234y
>>ObqrokqlObpqfkdyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..235y
@>ObqrokqlObpqfkdyNFAy..235yyKy?^`haltk^qPefbiaEfii)rpbqebX?rkaiblcSovhri>oqfc^`qpZ^qb^`elcCbkdfo%24+4)44+2&)Olafk%26+/)43+6&)Fprialc%26+5)46+1&)Tfka^k%3.+6)5-+-&yyRy013/1y
Q>ObqrokqlObpqfkdyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..235y
>Obqrokql>qrfhyKyLocrplcH^j^dr^%1-+0)3-+0&yyNFAy..24/y
QObqrokql>qrfhyKyBiabo>qrfh%/2+-)24+-&yyNFAy..24/y

QJfppflk7Clop^hbkFkqbiyKyMbmmvTolkdklwwib%0-+5)1.+3&yyNFAy..0/5y
>>_pelirqbiv+++QefpeTfiiTlohyKyMbmmvTolkdklwwib%0-+5)1.+3&yyNFAy..00-y
@>_pelirqbiv+++QefpeTfiiTlohyNFAy..00-yyKyRpbXMbmmv$pPmb`f^iJfuZlkqebmofplkbofkpfabqebhbbm%/6+1)10+1&yyRy003/4y
Q>_pelirqbiv+++QefpeTfiiTlohyKyMbmmvTolkdklwwib%0-+5)1.+3&yyNFAy..00-y
>VlrQbiiEfj+++Ef`yKyMbmmvTolkdklwwib%0-+5)1.+3&yyNFAy..00.y
QVlrQbiiEfj+++Ef`yKy@^mq^fk>a^jp%/5+6)11+/&yyNFAy..00.y
>Jfppflk7Mi^drbQefpyKy@^mq^fk>a^jp%/5+6)11+/&yyNFAy..00/y
@Jfppflk7Mi^drbQefpyNFAy..00/yyKyQ^ihqlqebcifdeqj^pqboDobboLobe^jjbo%0.+0)11+-&clopljb_lj_p^ka^cifdeqqebk_iltqebq^khp^olrkaKbt>d^j^kayyRy00301y
QJfppflk7Mi^drbQefpyKy@^mq^fk>a^jp%/5+6)11+/&yyNFAy..00/y
>Lmbo^qflk7PhlokcriTo^qeyKy@^mq^fk>a^jp%/5+6)11+/&yyNFAy../15y

@PelsbiqrphPlrm>d^fk<yNFAy...22yyKyFcvlr$sbklqvbq`ljmibqbahfii^kvpelsbiqrphp^olrka%03+4)12+2&y
@LkbPfwbAlbpKlqCfq>iiyNFAy...6-yyKyFcvlr$sbklqvbq`ljmibqba`liib`q^kv`^kklk_^iip^olrka%03+4)12+2&y

QLkbPfwbAlbpKlqCfq>iiyKy@^kklkbboBiv%01+-)10+5&yyNFAy...6-y
QPelsbiqrphPlrm>d^fk<yKy@ebcHbqqib_i^`h%0.+/)1-+6&yyNFAy...22y
>A^kdboBumilpfsbpyKyP^mmboPqbbiofkd%/6+.)1.+6&yyNFAy../.5y
>PbkaQebjM^`hfkdyKyBumilobo>_fd^fi%0.+3)1.+2&yyNFAy..//1y
@A^kdboBumilpfsbpyNFAy../.5yyKyBufqqebhbbmcolj_befkaqebpq^_ibp)tlohvlrot^vkloqeqlqebdri`ebkqo^k`b%00+5)00+4&+RpbXPqbbiofkd$pCllimollcAvk^jfqbZql_iltrmqebjfkfkdklabp^kamf`hrmqebmfb`bpyyRy00.6-y
@PbkaQebjM^`hfkdyNFAy..//1yyKyQ^odbqqebjribp^kaqvmb,o^fpb+Dri`ebkqo^k`bfp^q%00+5)00+4&y
QPbkaQebjM^`hfkdyKyBumilobo>_fd^fi%0.+3)1.+2&yyNFAy..//1y
QA^kdboBumilpfsbpyKyP^mmboPqbbiofkd%/6+.)1.+6&yyNFAy../.5y
>Ib^abolcqebAbo^kdbayKyP^mmboPqbbiofkd%/6+.)1.+6&yyNFAy../1-y
@Ib^abolcqebAbo^kdbayNFAy../1-yyKy?^`hqlqebdri`ebkqo^k`b%00+5)00+4&)dlofdeq^kaeb^atbpqqlqeb`^sb%0.+4)01+5&y
QIb^abolcqebAbo^kdbayKyP^mmboPqbbiofkd%/6+.)1.+6&yyNFAy../1-y
>BsbovqefkdJrpq?bOb^avyKyNr^oqboj^pqbo?obsfk%0-+4)1/+5&yyNFAy..1-3y
>JvA^rdeqboyKyLiaJ^kPqlkbj^kqib%0.+4)1/+-&yyNFAy...42y

QJvA^rdeqboyKyLsbopbboFobk^Pqlkbj^kqib%0-+/)/5+4&yyNFAy...42y
>PbbqlqebLmbo^qflkpyKyLsbopbboFobk^Pqlkbj^kqib%0-+/)/5+4&yyNFAy...43y
>TebobfpBumiloboG^obk<yKyLsbopbboFobk^Pqlkbj^kqib%0-+/)/5+4&yyNFAy..060y
>Qeb@ib^kpfkdyKyT^q`eboJllkib^c%0-+.)/5+4&yyNFAy..0//y
>P`^obqebDr^klLrqlcQebjyKyBkdfkbboCbhkrq%0-+/)/5+5&yyNFAy...21y
QPbbqlqebLmbo^qflkpyKyPqbbiD^qb@efbc>o`e^blildfpq%0-+5)/5+3&yyNFAy...43y
>F$sbDlq^CivfkdJ^`efkbyKyPqbbiD^qb@efbc>o`e^blildfpq%0-+5)/5+3&yyNFAy..06-y
@F$sbDlq^CivfkdJ^`efkbyNFAy..06-yyKyJ^hbprobvlrdbqfkqebofdeqmi^kb%qebob^obqtl+++lkbtfqetb^mlkp^kalkbtfqe^do^mmifkdellh&+Qebk_bclobvlrdllccfkqlqebjfkfkdmfqqrok^olrka^kaj^hbprobqebmi^kbcivp%pljbalklqciv&+Qebkcivfkqlqebmfq)dbq`ilpbqlqebi^odb_^d^karpbqebDo^mmifkdEllhqldbqqeb_^d+Vlr`^klkiv`^oov._^d^q^qfjby
QF$sbDlq^CivfkdJ^`efkbyKyPqbbiD^qb@efbc>o`e^blildfpq%0-+5)/5+3&yyNFAy..06-y
>PqbbiD^qbM^qoliyKyPqbbiD^qb@efbc>o`e^blildfpq%0-+5)/5+3&yyNFAy..06.y
@PqbbiD^qbM^qoliyNFAy..06.yyKyCiv^olrka^ka_iltrmqebd^odlvibp^olrka%0-+3)/1+3&y
QPqbbiD^qbM^qoliyKyPqbbiD^qb@efbc>o`e^blildfpq%0-+5)/5+3&yyNFAy..06.y

QTebobfpBumiloboG^obk<yKyBumiloboG^obk%/1+/)0/+2&yyNFAy..060y
>>kaVlrQelrdeqJroil`pPjbiiba?^ayKyBumiloboG^obk%/1+/)0/+2&yyNFAy..061y
HP`lrodbyKyHfiiqebP`lrodbp^ilkdqeb`l^pq%//+3)0-+2&)%//+4).3+3&rkqfivlrcfkaqebXP`lrodbAbsf`bZyyIy0063.yyNFAy..062y
>Fq$p^P`lrodbAbsf`byKyQebfqbjXP`lrodbAbsf`bZpq^oqpnrbpq*HfiiqebP`lrodbp^ilkdqeb`l^pq%//+3)0-+2&)%//+4).3+3&qldbqfqyyNFAy..062yyRy0063.y
QFq$p^P`lrodbAbsf`byKyBumiloboG^obk%/1+/)0/+2&yyNFAy..062y
>?ofkdAltkQelpbPefbiapyKyBumiloboG^obk%/1+/)0/+2&yyNFAy..063y
@?ofkdAltkQelpbPefbiapyNFAy..063yyRy0063-yyKyRpbqebXP`lrodfkd@ovpq^i@lkqoliiboZql_ofkdaltkqebpefbiap)qebk_ob^hqeb`ovpq^iplkqeb`l^pq^olrka%/.+5)//+2&y
@>kaVlrQelrdeqJroil`pPjbiiba?^ayNFAy..061yyKyHfiiP`lrodblkqeb`l^pq^olrka%/.+5)//+2&y
Q>kaVlrQelrdeqJroil`pPjbiiba?^ayKyBumiloboG^obk%/1+/)0/+2&yyNFAy..061y
Q?ofkdAltkQelpbPefbiapyKyBumiloboG^obk%/1+/)0/+2&yyNFAy..063y

QLmbo^qflk7PhlokcriTo^qeyKyEb^ab^pqqlPhlok%11+0)/3+2&)rpbqebXTbpqdr^oa@ljj^kaFkpfdkf^ZyyNFAy../15yyRy000..y
>Qltboplc@boq^fkAlljyKyTbpqdr^oaPbodb^kqyyNFAy../12yyRy000..y
>Dorbpljb)?rqKb`bpp^ovyKyTbpqdr^oaPbodb^kqyyNFAy../13yyRy000..y
>?rokPhlok)?rokyKyTbpqdr^oaPbodb^kqyyNFAy../14yyRy000..y
KRpbqebJ^`ebqblk^kvSovhrivlrhfiiyKyRpbXQebPbodb^kq$pJ^`ebqbZyyRy000.-yyNFAy../13y

@?rokPhlok)?rokyNFAy../14yyRy000/.yyKyRpbqebXPbodb^kq$pQlo`eZql_rokqebKloqeb^pqIlkdelrpb%13+2)/5+.&)?^oo^`hp%12+6)0-+4&)^kaKloqetbpqIlkdelrpb%10+4)/5+4&y
@Qltboplc@boq^fkAlljyNFAy../12yyRy000/0yyKyRpbqebXPbodb^kq$pCi^obZlkqebKloqetbpqQltbo%11+4)0-+-&)B^pqQltbo%12+5)0/+.&)PlrqetbpqQltbo%10+4)01+1&^kaPlrqeb^pq%13+0)03+0&y

>Pqlmqeb>p`bkpflkyNFAy../16yyLyyKyQebfqbjXSovhriP`oliilc>p`bkpflkZpq^oqpnrbpq*aolmmba^olrka%12)0-&yyRy000.1y
@Pqlmqeb>p`bkpflkyNFAy../16yyLyyKyRpbqebXSovhriP`oliilc>p`bkpflkZ^qQe^kb$pMvob%11+3)02+0&)hfiiE^ica^kyyRy00006y

@Dorbpljb)?rqKb`bpp^ovyNFAy../13yyRy000.-yyKyHfiisovhri^olrkaPhlok%11+0)/3+2&)^karpbXQebPbodb^kq$pJ^`ebqbZlkb^`elkbyyRy000.-y

QQltboplc@boq^fkAlljyKyTbpqdr^oaPbodb^kq)rpbqebXTbpqdr^oa@ljj^kaFkpfdkf^ZyyNFAy../12yyRy000..y
QDorbpljb)?rqKb`bpp^ovyKyTbpqdr^oaPbodb^kqyyNFAy../13yyRy000..y
Q?rokPhlok)?rokyKyTbpqdr^oaPbodb^kqyyNFAy../14yyRy000..y
>>iiE^fiqeb@lknrbololcPhlokyKyTbpqdr^oaPbodb^kqyyNFAy../2-yyRy000..y

OCloqTfiabos^oyKyQ^hbqebol^alrqlcqltk)eb^akloqeqebkb^pqm^pqPhlok%3-+/).5+4&yyNFAy..0/6y
eCloqTfiabos^oyKy@eofpqfk^A^kfbip%3-+2).2+6&yyNFAy..0/6y
cCloqTfiabos^oyKyG^jbpLojp_v%3-+.).3+.&yyNFAy..0/6y
>F$iiQov>kvqefkdyKy@eofpqlmeboPil^k%3-+0).5+4&yyNFAy..0/6y
@F$iiQov>kvqefkdyNFAy..0/6yyKyLmbkmi^kqprkabot^qbo^olrka%3/+0).6+5&^kahfiiqebobnrfoba^jlrkqlc?^o_cfpey
QF$iiQov>kvqefkdyKy@eofpqlmeboPil^k%3-+0).5+4&yyNFAy..0/6y
>QebLkbQe^qDlq>t^vyKy@eofpqlmeboPil^k%3-+0).5+4&yyNFAy..1.-y
@QebLkbQe^qDlq>t^vyNFAy..1.-yyRy01-.0yyKyAfsbaltkqlqeb_l^q%30+5).6+1&^karpbqebXCobpe?^o_cfpe?^fqZy
QQebLkbQe^qDlq>t^vyKy@eofpqlmeboPil^k%3-+0).5+4&yyNFAy..1.-y

>QebBkfdj^qf`ColpqKvjmepyKyIfbrqbk^kqJ^bsb%3.+5).4+/&yyNFAy..0-/y
>Qeb?llhlcOrkbpyKyMolpmb`qlo?bis^o%3/+0).4+/&yyNFAy..013y
QBsbovqefkdJrpq?bOb^avyKyDfiDofpboq%3/+3).3+5&yyNFAy..1-3y
>AltkqlqebTfobyKyDfiDofpboq%3/+3).3+5&yyNFAy../36y
>MobvfkdRmlkqebTb^hyKyQo^mmboGbqe^k%3/+3).3+5&yyNFAy../6/y
>QebVbqfKbuqAlloyKyClobj^k@li_bv%3-+/).2+4&yyNFAy../51y

KQo^mp)cb^qebop^kao^jpyKyLmbk^kvqo^mpvlr`ljb^`olppcloMobvfkdRmlkqebTb^h)`liib`qcb^qebopvlrpbbcloAltkqlqebTfob^kahfiio^jpcloQebVbqfKbuqAllob^`e^olrka%22+-).0+-&yyNFAy../6/y

QQebBkfdj^qf`ColpqKvjmepyKyIrofbiib%3.+2)//+5&yyNFAy..0-/y
>PmfofqplcqebF`byKyIrofbiib%3.+2)//+5&yyNFAy..0.0y
@PmfofqplcqebF`byNFAy..0.0yyKy>ii^olrkaqebColwbkDi^ab%3.+2)//+5&y
QPmfofqplcqebF`byKyIrofbiib%3.+2)//+5&yyNFAy..0.0y
>QebC^iibkPfpqbopyKyIrofbiib%3.+2)//+5&yyNFAy..0.1y
>TfiaSfkbpyKyIrofbiib%3.+2)//+5&yyNFAy..0.2y

@QebC^iibkPfpqbopyNFAy..0.1yyKyIl`^qbafkQebSf_o^kqDi^ab^q%2.+5)/5+6&+>qq^`hkvjmeprkqfitb^h)qebkrpbXIrofbiib$pMbka^kqZlkqebj+?bprobqlt^q`eAlQa^j^dbyyRy003-3y
@TfiaSfkbpyNFAy..0.2yyKyHfiiSfkbpclrkafkQebSf_o^kqDi^ab^q%2.+5)/5+6&y

QQebC^iibkPfpqbopyKyIrofbiib%3.+2)//+5&yyNFAy..0.1y
QTfiaSfkbpyKyIrofbiib%3.+2)//+5&yyNFAy..0.2y
>Pm^tklcqebQtfpqbaDi^abyKyIrofbiib%3.+2)//+5&yyNFAy..0.3y
>Pbbaplcqeb?i^`hplribaHbbmbopyKyIrofbiib%3.+2)//+5&yyNFAy..0.6y

@Pbbaplcqeb?i^`hplribaHbbmbopyNFAy..0.6yyKyKloqetbpq^qqebQtfpqbaDi^ab%21+/).3+4&+Hfiiqebpmlobp)qebkrpbqebXBk`e^kqbaF`b@lobZlkqebjyyRy003-4y
@Pm^tklcqebQtfpqbaDi^abyNFAy..0.3yyKyClrkaKloqetbpq^qqebQtfpqbaDi^ab%21+/).3+4&y

QPm^tklcqebQtfpqbaDi^abyKyIrofbiib%3.+2)//+5&yyNFAy..0.3y
>HbbmboTfqeboib^cyKyIrofbiib%3.+2)//+5&yyNFAy..1/5y
QPbbaplcqeb?i^`hplribaHbbmbopyKyIrofbiib%3.+2)//+5&yyNFAy..0.6y

@HbbmboTfqeboib^cyNFAy..1/5yyKyClrka^qQebQtfpqbaDi^ab^olrka%21+-).5+6&y
HO^jpyKyKbba1o^jjb^qcloQebVbqfKbuqAllo^olrka%22+-).0+-&fcklq^iob^av`liib`qbayyIy0002/1yyNFAy../51y
@Qeb@ib^kpfkdyNFAy..0//yyKyEb^armqebjlrkq^fkm^qe%20+3)5+-&qlqebpeofkb%3.+0).+3&+Rpbqebpeofkbqebkhfiiqebbsfivlr^kaqebkpiltc^iialtkqlqebColwbkDi^aby

QHbbmboTfqeboib^cyKyIrofbiib%3.+2)//+5&yyNFAy..1/5y

@Qeb?llhlcOrkbpyNFAy..013yyKyHfiiFolkOrkbPqlkb`^iibop,?fkabopqlqebb^pq^qDf^kqp$Ork%4/+-)/1+-&clo`e^mqbop)qebk`lj_fkbqebjql`ob^qbqeb_llhyyRy00445y

QQeb?llhlcOrkbpyKyMolpmb`qlo?bis^o%3/+0).4+/&yyNFAy..013y
>J^pqbofkdqebOrkbpyKyMolpmb`qlo?bis^o%3/+0).4+/&yyNFAy..016y

@QebVbqfKbuqAlloyNFAy../51yyKyEb^aaltkfkqlqebjfkbqlqebpibbmfkdvbqf%3-+1)./+-&+@lj_fkbqebo^jjb^q)rpbqebvbqfjb^iqlprjjlk^kahfiiqebvbqf+yyRy00144y
QQebVbqfKbuqAlloyKyClobj^k@li_bv%3-+/).2+4&yyNFAy../51y

@J^pqbofkdqebOrkbpyNFAy..016yyKyCfkaqebXFolkOrkb@^osfkdQllipZfkqebqbkqp^olrkaDf^kqp$Ork^q^kvlcqebcliiltfkdil`^qflkp%36+.)//+5&%34+2)/0+1&%34+2)/6+/&%4.+/)/5+4&%40+1)/2+-&%4/+1).4+5&y

QJ^pqbofkdqebOrkbpyKyMolpmb`qlo?bis^o%3/+0).4+/&yyNFAy..016y
>QebOrkblc@ljj^kayKyMolpmb`qlo?bis^o%3/+0).4+/&yyNFAy..015y

@QebOrkblc@ljj^kayNFAy..015yyRy00463yyKyRpbqebXOrkblc@ljj^kaZlk^kloj^idf^kqkb^o?fkaboJroafp%4.+5)/1+0&qebkhfiiefjy

@AltkqlqebTfobyNFAy../36yyKy@liib`qqebcb^qebopfcklq^iob^av`ljmibqb^olrka%22+-).0+-&y
@MobvfkdRmlkqebTb^hyNFAy../6/yyKyLmbkqo^mp^olrka%22+-).0+-&fcklq^iob^av`ljmibqby

QQebOrkblc@ljj^kayKyMolpmb`qlo?bis^o%3/+0).4+/&yyNFAy..015y
QMobvfkdRmlkqebTb^hyKyQo^mmboGbqe^k%3/+3).3+5&yyNFAy../6/y
QAltkqlqebTfobyKyDfiDofpboq%3/+3).3+5&yyNFAy../36y
>Tb@^iiEfjPqbbicb^qeboyKyDfiDofpboq%3/+3).3+5&yyNFAy..1.5y
@Tb@^iiEfjPqbbicb^qeboyNFAy..1.5yyKyQ^odbqPqbbicb^qebo^karpbqebXCb^qeboba@e^ojZmolsfabayyRy01-/3y
QTb@^iiEfjPqbbicb^qeboyKyDfiDofpboq%3/+3).3+5&yyNFAy..1.5y

CTbpqdr^oabHbbmyKyG^jbpLojp_v%3-+.).3+.&yyNFAy../02y

Q>iiE^fiqeb@lknrbololcPhlokyKy@^mq^fk>a^jp%/5+6)11+/&yyNFAy../2-y
>Ab^ifkdTfqeDg^ibo_olkyKy@^mq^fk>a^jp%/5+6)11+/&yyNFAy../02y
QPqlmqeb>p`bkpflkyKyC^qeboIbs^ofli%/5+6)11+-&yyNFAy../16yyLy
>LcHbvp^ka@^dbpyKyC^qeboIbs^ofli%/5+6)11+-&yyNFAy../0.y

QQeb@ib^kpfkdyKyT^q`eboJllkib^c%0-+.)/5+4&yyNFAy..0//y
>FkTlod$p@ilqefkdyKyT^q`eboJllkib^c%0-+.)/5+4&yyNFAy..0/2y
QFkTlod$p@ilqefkdyKyRic^kd%/6+4)2+4&yyNFAy..0/2yyRy003.5y
>?olqebo?bqo^vbopyKyRic^kd%/6+4)2+4&yyNFAy..1.1y
@?olqebo?bqo^vbopyNFAy..1.1yyKyHfii?gljlicqlqebplrqetbpq^olrkaqeb>mlqeb`^ov@^jm%/6+.)/.+4&+S^odfpplrqeb^pqlcPqbbiD^qb%02+1)0.+/&+FcvlrrpbqebXTlodAfpdrfpbZvlr$iie^sb^kb^pfboqfjbpmlqqfkdqebjyyRy003.5y
Q?olqebo?bqo^vbopyKyRic^kd%/6+4)2+4&yyNFAy..1.1yyRy003.5y
>BvbplcqebB^dibyKyRic^kd%/6+4)2+4&yyNFAy..1.3y
@BvbplcqebB^dibyNFAy..1.3yyKyPlrqetbpqlcPhlok^qqeb_^pblcqeb_fdt^qboc^ii%1.+1)04+3&+Do^_qebbdd)qebkhfiiqebb^dib+y
QBvbplcqebB^dibyKyRic^kd%/6+4)2+4&yyNFAy..1.3yyRy003.5y
>>ime^TlodyKyRic^kd%/6+4)2+4&yyNFAy..0/3y
@>ime^TlodyNFAy..0/3yyKyPm^tkpgrpqplrqelcqeb`^sb%/4+1)5+/&y
Q>ime^TlodyKyT^q`eboJllkib^c%0-+.)/5+4&yyNFAy..0/3y

@P`^obqebDr^klLrqlcQebjyNFAy...21yyRy00./6yyKyRpbXCbhkrq$pCfob`o^`hbopZ_biltqeb_^qpqe^qciv^olrkaqebqobbpfkOfsbktlla%01+-).6+2&y

@LcHbvp^ka@^dbpyNFAy../0.yyKyHfiiSovhriqlqebkloqe^qDg^ibo_olk%02+-)./+/&qlillqqebhbvpvlrkbbaqllmbk`^dbp+Fcvlrdbqqebi^odb`^dbhbv)rpb^qqeb`^db^q%02+5)..+2&y
@Ab^ifkdTfqeDg^ibo_olkyNFAy../02yyKyHfiiSovhriqlqebkloqe^qDg^ibo_olk%02+-)./+/&y
>Dg^ibo_olk>qq^`hMi^kpyNFAy../04yyKyRpbqebXDg^ibo_olk>qq^`hMi^kpZ+Fcvlrafak$qdbqqebj)hbbmhfiifkdSovhriyyRy00/56y

QLcHbvp^ka@^dbpyKyC^qeboIbs^ofli%/5+6)11+-&yyNFAy../0.y
>FkPbosf`bqlqebIfdeqyKyC^qeboIbs^ofli%/5+6)11+-&yyNFAy../06y
QAb^ifkdTfqeDg^ibo_olkyKy@^mq^fk>a^jp%/5+6)11+/&yyNFAy../02y
>Kb`olLsboiloaJbwebkyKy@^mq^fk>a^jp%/5+6)11+/&yyNFAy../03y
QDg^ibo_olk>qq^`hMi^kpyKyJ^db*Ifbrqbk^kqJ^ifpqbo%/6+-)11+/&yyNFAy../04y
>QebColpqTvoj^kafqpJ^pqboyKyJ^db*Ifbrqbk^kqJ^ifpqbo%/6+-)11+/&yyNFAy../05y
>PibbmfkdDf^kqpyKyJ^db*Ifbrqbk^kqJ^ifpqbo%/6+-)11+/&yyNFAy..10/y

QP`^obqebDr^klLrqlcQebjyKyBkdfkbboCbhkrq%0-+/)/5+5&yyNFAy...21y

@PibbmfkdDf^kqpyNFAy..10/yyKyAltkfkqebT^hfkdE^iip_bkb^qeDg^ibo_olk%01+-).0+-&+HfiiKb`oliloapclo^kX>t^hbkfkdOlaZ)rpbfqlkqebAloj^kqSovhrifkqeb`e^j_bopyyRy01-50y
HCb^opljbEloolopyNFAy../06yyNLyCb^opljbEloolopi^fk71,1yyKyAltkfkqebT^hfkdE^iip_bkb^qeDg^ibo_olk%01+-).0+-&y
@Kb`olLsboiloaJbwebkyNFAy../03yyKyEb^armqlqebpb`lkaibsbi)qebkrmqlqebmi^qclojqlqebb^pq%05+3)./+1&y
>QebPirj_bofkdHfkdyKyQebfqbjXJbwebk$pTofqfkdpZpq^oqpnrbpq*aolmmba_vKb`olLsboiloaJbwebk%05+5).0&yyNFAy..12/yyRy01-6-y
@QebPirj_bofkdHfkdyNFAy..12/yyKyHfiiNrbbk>kdbo_la^^qqebc^obkalcDg^ibo_olk%1.+-)3+0&y
@QebColpqTvoj^kafqpJ^pqboyNFAy../05yyRy00/5/yyKyHfiiTvoj`^iiboSfib%03+2)4+0&)qebkillqqebXTvoj`^iibo$pElokZ^karpbfq+HfiiDi^`flk+Tvoj`^iiboSfibe^p^peloqobpm^tkqfjb+Qefpfp^dolrmnrbpq)_rqb^pfivplil^_iby
@FkPbosf`bqlqebIfdeqyNFAy../06yyKyHfiiqebobj^fkfkdAb^qeibppT^q`ebop^kaMrqofaTfdeqpclrkalkqebmi^qclojp%03+.)4+/&^ka%05+-).0+1&y

QPibbmfkdDf^kqpyKyJ^db*Ifbrqbk^kqJ^ifpqbo%/6+-)11+/&yyNFAy..10/y
QQebColpqTvoj^kafqpJ^pqboyKyJ^db*Ifbrqbk^kqJ^ifpqbo%/6+-)11+/&yyNFAy../05y
QQebPirj_bofkdHfkdyKy@^mq^fk>a^jp%/5+6)11+/&yyNFAy..12/y
QKb`olLsboiloaJbwebkyKy@^mq^fk>a^jp%/5+6)11+/&yyNFAy../03y
QFkPbosf`bqlqebIfdeqyKyC^qeboIbs^ofli%/5+6)11+-&yyNFAy../06y
>LcQo^fqlop^kaQob^plkyKy@^mq^fk>a^jp%/5+6)11+/&yyNFAy.//64y
QLcQo^fqlop^kaQob^plkyKyDobboLobe^jjbo%0.+0)11+-&yyNFAy.//64y
>Efde@ljj^kaboE^icloaTvoj_^kbyKyDobboLobe^jjbo%0.+0)11+-&yyNFAy.//65y
QEfde@ljj^kaboE^icloaTvoj_^kbyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy.//65yyWyAo^dlk_ifdeqy
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
