DugisGuideViewer:RegisterGuide("Dragonblight (73-75)", "Grizzly Hills (75-76)", "Alliance", "L", function()
return [[
AAA

cTfkqbod^oabHbbmyKyOlakbvTbiip%44+-)16+5&yyNFAy.//02y

>K^uuo^j^p^kaqebC^iilcTfkqbod^oabyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy.//02y
QK^uuo^j^p^kaqebC^iilcTfkqbod^oabyNFAy.//02yyKyDovmelk@ljj^kaboRofh%44+.)2-+.&y
>CifdeqlcqebTfkqbod^oabAbcbkaboyKyDovmelk@ljj^kaboRofh%44+.)2-+.&yyNFAy.//04y
@CifdeqlcqebTfkqbod^oabAbcbkaboyNFAy.//04yyRy04/54yyKyRpbqebXTfkqbod^oabDovmelkTefpqibZ+Ebimibppsfii^dbopork^_lrq^ii^olrkaqeb@^ooflkcfbiap^olrka%51+.)16+-&+Vlre^sbqlq^hbqebj_^`hlkb^q^qfjby
QCifdeqlcqebTfkqbod^oabAbcbkaboyKyDovmelk@ljj^kaboRofh%44+.)2-+.&yyNFAy.//04y
>ObqrokqlqebEfde@ljj^kaboyKyDovmelk@ljj^kaboRofh%44+.)2-+.&yyNFAy.//2.y
QObqrokqlqebEfde@ljj^kaboyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy.//2.y
>Obp`rbcoljQltkPnr^obyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy.//20y
>QebC^qblcqebAb^ayKy@ljj^kaboIvklobTfkapqovhb%45+3)15+/&yyNFAy.//25y
eTfkqbod^oabHbbmyKyFiirpf^Irkb%44+2)2.+2&yyNFAy./0-6y

@Obp`rbcoljQltkPnr^obyNFAy.//20yyKyEb^aPlrqeql%46+.)16+5&^kacobbqebsfii^dbopqeboby
@QebC^qblcqebAb^ayNFAy.//25yyKyEb^aPlrqeql%46+.)16+5&tebobvlr$iicfkaqebkbbabajl_py

QQebC^qblcqebAb^ayKy@ljj^kaboIvklobTfkapqovhb%45+3)15+/&yyNFAy.//25y
QObp`rbcoljQltkPnr^obyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy.//20y
>CfkaArohlkyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy./0-6y
>QebAbjl*dkljbyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy.//42y

QQebAbjl*dkljbyKyPfbdbBkdfkbboNr^oqboci^pe%44+5)2-+0&yyNFAy.//42y
>QebPb^o`ecloPifkhfkyKyPfbdbBkdfkbboNr^oqboci^pe%44+5)2-+0&yyNFAy.//43y
>Qeb?ibbafkdLobyKyPfbdbBkdfkbboNr^oqboci^pe%44+5)2-+0&yyNFAy.//4/y
>KlqFkLroJfkbyKyEfdeiloaIblof`SlkWbiafd%44+4)2-+/&yyNFAy.//36y

QQebPb^o`ecloPifkhfkyKyPifkhfkqebAbjl*dkljb%5.+2)1/+/&yyNFAy.//43yyRy04126y
>Ib^sbKlqefkdql@e^k`byKyPifkhfkqebAbjl*dkljb%5.+2)1/+/&yyNFAy.//44y

KDbq^_lj_yKy>olrkaqeb`lokbocoljPifkhfk%5-+4)1.+1&yyIy04132yyNFAy.//44y
@Qeb?ibbafkdLobyNFAy.//4/yyKyClrkafkqebjfkbtfqe^kbkqo^k`b^q%5-+0)12+5&y
@KlqFkLroJfkbyNFAy.//36yyKyClrkafkqebjfkbtfqe^kbkqo^k`b^q%5-+0)12+5&y
@Ib^sbKlqefkdql@e^k`byNFAy.//44yyRy04132yyKyLkvlrot^vlrqlcqebjfkb)rpb^XTfkqbod^oabJfkb?lj_Zql_iltrmqebRmmbo%5-+2)12+0&^kaIltbo%5-+/)11+.&bkqo^k`bpy

QIb^sbKlqefkdql@e^k`byKyPfbdbBkdfkbboNr^oqboci^pe%44+5)2-+0&yyNFAy.//44y
QQeb?ibbafkdLobyKyPfbdbBkdfkbboNr^oqboci^pe%44+5)2-+0&yyNFAy.//4/y
>Rkabopq^kafkdqebP`lrodbT^oJ^`efkbyKyPfbdbBkdfkbboNr^oqboci^pe%44+5)2-+0&yyNFAy.//5.y
QKlqFkLroJfkbyKyEfdeiloaIblof`SlkWbiafd%44+4)2-+/&yyNFAy.//36y
QRkabopq^kafkdqebP`lrodbT^oJ^`efkbyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy.//5.y
>FjmofkqplkqebM^pqyKyWbifdqebSfpflk^ov%46+.)14+/&yyNFAy.//5/y

@FjmofkqplkqebM^pqyNFAy.//5/yyKyAltkfkqltk)rmpq^fopfkqebqltke^ii%45+6)2-+6&y

QCfkaArohlkyKy@^s^ifboArohlk%46+.)20+/&yyNFAy./0-6y
>QebKl_ib$p@ovmqyKy@^s^ifboArohlk%46+.)20+/&yyNFAy./0..y
@QebKl_ib$p@ovmqyNFAy./0..yyKyEb^aaltkqebelib^kapi^vKb`oliloa>j^oflk%45+3)2/+4&y
>Pb`obqplcqebP`lrodbyKyCibpe*_lrkaQljb%45+3)2/+0&yyNFAy./0./y
QQebKl_ib$p@ovmqyKy@^s^ifboArohlk%46+.)20+/&yyNFAy./0..y
QPb`obqplcqebP`lrodbyKy@^s^ifboArohlk%46+.)20+/&yyNFAy./0./y
>JvpqbovlcqebQljbyKy@^s^ifboArohlk%46+.)20+/&yyNFAy./0.6y

QJvpqbovlcqebQljbyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy./0.6y
>Rkabopq^kafkdqebI^kdr^dblcAb^qeyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy./0/-y
QFjmofkqplkqebM^pqyKyWbifdqebSfpflk^ov%46+.)14+/&yyNFAy.//5/y
>LofhQorbeb^oq^kaqebClodlqqbkPelobyKyWbifdqebSfpflk^ov%46+.)14+/&yyNFAy.//54y
QRkabopq^kafkdqebI^kdr^dblcAb^qeyKyFknrfpfqloE^ii^oa%43+4)14+2&yyNFAy./0/-y
>>OfdeqblrpPbojlkyKyFknrfpfqloE^ii^oa%43+4)14+2&yyNFAy./0/.y
@>OfdeqblrpPbojlkyNFAy./0/.yyKyIfpqbkqlFknrfpfqloE^ii^oa%43+4)14+2&pmb^hy
Q>OfdeqblrpPbojlkyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy./0/.y
>FkqlElpqfibQboofqlovyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy./0/2y

QFkqlElpqfibQboofqlovyKyArhb>rdrpqClbe^jjbo%56+4)13+2&Rpbqebdovmelkkb^oqebcifdeqj^pqboyyNFAy./0/2y
>Pqb^jq^khPromofpbyKyArhb>rdrpqClbe^jjbo%56+4)13+2&yyNFAy./0/3y
@Pqb^jq^khPromofpbyNFAy./0/3yyKyObib^pbqebdkljbkb^oqebmi^drbt^dlkpfkqeb@^ooflkCfbiap)qebkeb^aqlqebj^rplibrjbkqo^k`b%52+1)16+6&^kaaolmlccqebpliafbopy
QPqb^jq^khPromofpbyKy>j_l@^pe%53+-)2-+5&yyNFAy./0/3y
>P`^qqbobaQlQebTfkayKy>j_l@^pe%53+-)2-+5&yyNFAy./122y
@P`^qqbobaQlQebTfkayNFAy./122yyKyCfka_lubplc^jjl^olrka%55+-)2.+-&y
QP`^qqbobaQlQebTfkayKy>j_l@^pe%53+-)2-+5&yyNFAy./122y
>Qeb@e^fkDrk>kaVlryKy>j_l@^pe%53+-)2-+5&yyNFAy./124y
@Qeb@e^fkDrk>kaVlryNFAy./124yyKyP^sb55Fkgroba4qeIbdflkPliafbop^q%52+4)2-+3&+Rpbqebdrkkb^oqebnrbpqdfsbo)`^ii^pliafbo^kacfoby
QQeb@e^fkDrk>kaVlryKy>j_l@^pe%53+-)2-+5&yyNFAy./124y
>Mirkabo_b^oaJrpq?bClrkayKy>j_l@^pe%53+-)2-+5&yyNFAy./130y
>?ob^hfkdLcc>Mfb`byKyVloa@^i^jfqvF`b_b^oa%52+6)2.+-&yyNFAy./13/y
@?ob^hfkdLcc>Mfb`byNFAy./13/yyKyEb^aaltkqebpq^fop)^kahfiiKb`oliloaU$^sfrp%51+2)2.+.&)Kb`oliloaElorp^qqeblmmlpfqbpfablcqebe^ii%53+2)2/+5&^ka.2K^uuo^j^pP`lrodb%50+.)21+4&y

QMirkabo_b^oaJrpq?bClrkayKyMirkabo_b^oa%51+/)21+3&yyNFAy./130y
>Mirkabo_b^oa$pGlrok^iyKyMirkabo_b^oa%51+/)21+3&yyNFAy./132y
@Mirkabo_b^oa$pGlrok^iyNFAy./132yyKyEb^aqeolrdeqebqrkkbi^kahfiip`lrodblkqeblqebopfab%50+.)21+4&rkqfim^dbp1*4`liib`qbay
Q?ob^hfkdLcc>Mfb`byKyVloa@^i^jfqvF`b_b^oa%52+6)2.+-&yyNFAy./13/y
QMirkabo_b^oa$pGlrok^iyKy>j_l@^pe%53+-)2-+5&yyNFAy./132y
>@e^pfkdF`bpqloj7Qeb4qeIbdflkColkqyKy>j_l@^pe%53+-)2-+5&yyNFAy./133y

QLofhQorbeb^oq^kaqebClodlqqbkPelobyKyLofhQorbeb^oq%54+/)24+2&yyNFAy.//54y
>QebJrohtbbaBifufoyKyLofhQorbeb^oq%54+/)24+2&yyNFAy.//6-y
@QebJrohtbbaBifufoyNFAy.//6-yyKyQlqebplrqeb^pq^qBiaofq`eEbfdeqp%6-+-)31+2&y
QQebJrohtbbaBifufoyKyLofhQorbeb^oq%54+/)24+2&yyNFAy.//6-y
>QebClodlqqbkQ^ibyKyLofhQorbeb^oq%54+/)24+2&yyNFAy.//6.y
@QebClodlqqbkQ^ibyNFAy.//6.yyKyEb^aaltkqlqebClodlqqbkPelob%53+-)31+/&qebkrpbqebXJrohtbbaBifufoZ^kaq^ihqlqebdelpqpyyRy0424-y
QQebClodlqqbkQ^ibyKyLofhQorbeb^oq%54+/)24+2&y
>QebQorqePe^iiPbqRpCobbyKyLofhQorbeb^oq%54+/)24+2&yyNFAy./0-.y
@QebQorqePe^iiPbqRpCobbyNFAy./0-.yyKyEb^a_^`haltkqlqebClodlqqbkPelob%53+-)31+/&)rpbqebXLofh$p@ovpq^iifkbLo_Zfkqeb`bkqbolcqltk%53+5)33+/&yyRy04244y
QQebQorqePe^iiPbqRpCobbyKyLofhQorbeb^oq%54+/)24+2&yyNFAy./0-.y
>M^oqfkdQelrdeqpyKyLofhQorbeb^oq%54+/)24+2&yyNFAy./0-2y

QM^oqfkdQelrdeqpyKyWbifdqebSfpflk^ov%46+.)14+/&yyNFAy./0-2y
>Te^qPb`obqpJbkEfabyKyWbifdqebSfpflk^ov%46+.)14+/&yyNFAy./142y
>QebObqroklcqeb@orp^ab<yKy@ljj^kaboIvklobTfkapqovhb%45+3)15+/&yyNFAy./143y
>QebM^qelcObabjmqflkyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy./144y
@Te^qPb`obqpJbkEfabyNFAy./142yyKyCfkaqebXLkpi^rdeqJ^mZ^q%54+25)05+-3&lkqebq^_ibfkpfabqebe^iccfkfpebaqltbofkqebP`^oibqLkpi^rdeq`^jmy
@QebM^qelcObabjmqflkyNFAy./144yyKyHfiiP`^oibqLkpi^rdeqp^olrka%50+/)06+6&rkqfi_llhfpaolmmbay
@QebObqroklcqeb@orp^ab<yNFAy./143yyKyHfiiP`^oibqLkpi^rdeqp^olrka%50+/)06+6&y

QQebM^qelcObabjmqflkyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy./144y
QQebObqroklcqeb@orp^ab<yKy@ljj^kaboIvklobTfkapqovhb%45+3)15+/&yyNFAy./143y
QTe^qPb`obqpJbkEfabyKyWbifdqebSfpflk^ov%46+.)14+/&yyNFAy./142y
>Colpqjlrokb@^sbokyKyWbifdqebSfpflk^ov%46+.)14+/&yyNFAy./145y

@Colpqjlrokb@^sbokyNFAy./145yyKyEb^aqlqebColpqjlrokb@^sbok%42+.)/-+/&^karpbXWbifd$pP`ovfkdLo_ZyyRy04600y

Q@e^pfkdF`bpqloj7Qeb4qeIbdflkColkqyKyIbdflk@ljj^kaboQvo^iflk%31+4)/4+6&yyNFAy./133y
>@e^pfkdF`bpqloj7Qebi$w^k$pMevi^`qbovyKyIbdflk@ljj^kaboQvo^iflk%31+4)/4+6&yyNFAy./134y
@@e^pfkdF`bpqloj7Qebi$w^k$pMevi^`qbovyNFAy./134yyKyQ^ihqlTvoj_^fq%31+1)/4+5&kb^o_vIbdflk@ljj^kaboQvo^iflk)pmb^htfqeefj^kaeb$iidbq^kBifqbPhbibq^iAo^dlk)Km`$ptfiimolsfab^ppfpq^k`by
>Mbpq@lkqoliyKyAr^kb%31+2)/3+2&yyNFAy./.1/y

>Pql`hfkdRmyKyUfkh%22+-)/0+2&yyNFAy./-11y
>Pe^sbaF`byKyWfsifu%21+4)/0+0&yyNFAy./-12y
>KlwwiborpqAbcbkpbyKyK^oc%21+2)/0+3&yyNFAy./-10y

@Pql`hfkdRmyNFAy./-11yyKyD^qebo5_rkaibplcX@ljmlpfqbLobZ^qbfqebolcqebcolpqtvojafdp%23+.)/4+6&lo%2.+6)0-+5&y
@KlwwiborpqAbcbkpbyNFAy./-10yyKyHfiijl_p^qbfqebolcqebcolpqtvojafdp%23+.)/4+6&lo%2.+6)0-+5&y

QKlwwiborpqAbcbkpbyKyK^oc%21+2)/0+3&yyNFAy./-10y
QPql`hfkdRmyKyUfkh%22+-)/0+2&yyNFAy./-11y

@Pe^sbaF`byNFAy./-12yyKy@ovpq^iifkbF`bBibj^kq^ip`^k_bclrka^ilkdqebofadb^q%21+/).5+6&y
QPe^sbaF`byKyWfsifu%21+4)/0+0&yyNFAy./-12y
>PlcqM^`h^dfkdyKyWfsifu%21+4)/0+0&yyNFAy./-13y
@PlcqM^`h^dfkdyNFAy./-13yyKyHfiiglojrkd^oqrkkbibop^ka`lkalop^olrka%20+0)/2+.&y
@Mbpq@lkqoliyNFAy./.1/yyKyHfiij^dk^q^ro^kapkl_liap^q^kvlcqebfo`^jmpkb^o_v%22+/)1-+-&%36+6)0.+.&%32+2)2-+.&%31+-)1/+5&y

QPlcqM^`h^dfkdyKyWfsifu%21+4)/0+0&yyNFAy./-13y
>PljbqefkdQe^qAlbpk$qJbiqyKyWfsifu%21+4)/0+0&yyNFAy./-14y
>E^oaqlPt^iiltyKyUfkh%22+-)/0+2&yyNFAy./-16y
@E^oaqlPt^iiltyNFAy./-16yyKy>qq^`hqebbifqbp^olrka%26+4)/3+3&rkqfiqebvlmbkqebfojlrqepqebkrpbqebXMlqbkqBumilpfsb@e^odbpZmolsfabayyRy0340/y

@PljbqefkdQe^qAlbpk$qJbiqyNFAy./-14yyKyCfka./XPmifkqboba?lkb@erkhpZ^olrkaqebao^dlk_lkbp%26+4)/3+3&%20+0)/2+/&%2.+2)/3+/&y

QMbpq@lkqoliyKyAr^kb%31+2)/3+2&yyNFAy./.1/y
>@^kvlk@e^pbyKyAr^kb%31+2)/3+2&yyNFAy./.10y
@@^kvlk@e^pbyNFAy./.10yyKyCliiltqebpkl_liapb^pqaltkqeb`^kvlkql@efiiqrph%4/+1)/5+5&y
>Afpqro_fkdFjmif`^qflkpyKyQebfqbjXBj_i^wlkba?^qqibElokZpq^oqpnrbpq*aolmmba_v@efiiqrph^olrka%4/)/5&yyNFAy./.13yyRy03522y
Q@^kvlk@e^pbyKyAr^kb%31+2)/3+2&yyNFAy./.10y

QPljbqefkdQe^qAlbpk$qJbiqyKyWfsifu%21+4)/0+0&yyNFAy./-14y
QE^oaqlPt^iiltyKyUfkh%22+-)/0+2&yyNFAy./-16y
>Irj_boE^`hyKyUfkh%22+-)/0+2&yyNFAy./-2-y
>E^omlkQefpyKyK^oc%21+2)/0+3&yyNFAy./-2/y
@E^omlkQefpyNFAy./-2/yyRy03401yyKyGrpqkloqe^q@liatfkaEbfdeqp%2/+6).6+4&+RpbXUfkh$pPeobaabo@lkqoliAbsf`bZ^kahfiiqebJfpqobpplcqeb@liatfka%12+0)..+3&y
@Irj_boE^`hyNFAy./-2-yyRy03401yyKyRpbXUfkh$pPeobaabo@lkqoliAbsf`bZ+@elmj^ohbaqobbp^q^q@liatfkaEbfdeqp%2/+6).6+4&y
QE^omlkQefpyKyK^oc%21+2)/0+3&yyNFAy./-2/y
QIrj_boE^`hyKyUfkh%22+-)/0+2&yyNFAy./-2-y
>PqfccKbdlqf^qflkpyKyK^oc%21+2)/0+3&yyNFAy./../y

QPqfccKbdlqf^qflkpyKyWloq%26+2).5+.&yyNFAy./../y
>PifjMf`hfkdpyKyWloq%26+2).5+.&yyNFAy./-42y
@PifjMf`hfkdpyNFAy./-42yyKyArbkloqe)grpqfkpfabqebF`bEb^oq@^sbok%23+.)./+-&y
QPifjMf`hfkdpyKyWloq%26+2).5+.&yyNFAy./-42y
>Jbppv?rpfkbppyKyWloq%26+2).5+.&yyNFAy./-43y
>PqljmfkdDolrkapyKyHl$`e^oqebRk_ob^h^_ib%26+.).4+6&yyNFAy./-46y
@Jbppv?rpfkbppyNFAy./-43yyKyHfiiGlojrkd^opfkpfabqebF`bEb^oq@^sbok%23+.)./+-&+RpbXWloq$pP`o^mboZtebkvlr$obpmfqlkyyRy03442y
@PqljmfkdDolrkapyNFAy./-46yyKyF`bEb^oqGlojrkd^oCbbabop^obclrkafkpfabqebF`bEb^oq@^sbok%23+.)./+-&y
QJbppv?rpfkbppyKyWloq%26+2).5+.&yyNFAy./-43y
>>mmivQefpQtf`b>A^vyKyWloq%26+2).5+.&yyNFAy./-44y
Q>mmivQefpQtf`b>A^vyKyHl$`e^oqebRk_ob^h^_ib%26+.).4+6&yyNFAy./-44y
QPqljmfkdDolrkapyKyHl$`e^oqebRk_ob^h^_ib%26+.).4+6&yyNFAy./-46y
>TlojTo^kdiboyKyWloq%26+2).5+.&yyNFAy./-45y
@TlojTo^kdiboyNFAy./-45yyKyCfkaGlojrkd^opm^tkfkpfabqebF`bEb^oq@^sbok%23+.)./+-&+RpbqebXPqroav@o^qbpZqebkillqyyRy0344.y
QTlojTo^kdiboyKyWloq%26+2).5+.&yyNFAy./-45y

OCloao^dlkEliayKyQlqebtbpq%06+3)/2+6&yyNFAy./14/y
cCloao^dlkEliayKyAbobhO^jjbi%06+3)/2+6&yyNFAy./14/y
CTfkqbod^oabHbbmyKyAbobhO^jjbi%06+3)/2+6&qlOlakbvTbiip%44+-)16+5&yyNFAy./14/y
Q@e^pfkdF`bpqloj7Qebi$w^k$pMevi^`qbovyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy./134y
>Cfk^ifqvyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy./14/y
QColpqjlrokb@^sbokyKyWbifdqebSfpflk^ov%46+.)14+/&yyNFAy./145y
QCfk^ifqvyKyIbdflk@ljj^kaboVlofh%5.+/)2-+4&yyNFAy./14/y
>>kBka>ka>?bdfkkfkdyKyIbdflk@ljj^kaboVlofh%5.+/)2-+4&yyNFAy./140y
@>kBka>ka>?bdfkkfkdyNFAy./140yyKyQefptfiipq^oq^kbsbkq)ebim^qq^`hqebkhfiiQebi$w^kqebArph_ofkdbolk`bpm^tkbay
Q>kBka>ka>?bdfkkfkdyKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy./140y
>QlCloao^dlkEliayKyEfde@ljj^kaboE^icloaTvoj_^kb%45+3)15+/&yyNFAy./141y

>>Afpqro_^k`bFkQebTbpqyKyS^pqebRkpq^_ib%45+6)12+0&yyNFAy./106y
Q>Afpqro_^k`bFkQebTbpqyKyOlakbvTbiip%44+-)16+5&yyNFAy./106y
>QlPq^op$ObpqyKyOlakbvTbiip%44+-)16+5&yyNFAy./11-y

cPq^op$ObpqyKyM^ibk^Pfisbo`ilra%/6+/)22+1&yyNFAy./---y
ePq^op$ObpqyKyK^le^fk%/5+6)23+.&yyNFAy./---y

QQlPq^op$ObpqyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./11-y
>Ofcibqeb?lafbpyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./---y

>QebIfnrfaCfoblcBirkbyKyT^oabkGlafJllkplkd%/6+/)22+3&yyNFAy./.33y
@QebIfnrfaCfoblcBirkbyNFAy./.33yyKyHfii_ifdeqbabih^kao^_fadofwwifbp^olrka%/1+6)2.+2&+RpbqebXIfnrfaCfoblcBirkbZlkqebfo`lompbpyyRy03623y
QQebIfnrfaCfoblcBirkbyKyT^oabkGlafJllkplkd%/6+/)22+3&yyNFAy./.33y
>Hfiiqeb@riqfpqpyKyT^oabkGlafJllkplkd%/6+/)22+3&yyNFAy./.34y
@Hfiiqeb@riqfpqpyNFAy./.34yyKyEb^armqlF`bjfpqSfii^db%/2+3)13+/&^kahfii`riqfpqpy
>QebC^slolcW^kdrpyKyQebfqbjXQebC^slolcW^kdrpZpq^oqpnrbpq*aolmmba_v>kr_$^o@riqfpqp^olrka%/3)11&yyNFAy./.35yyRy03625y
QHfiiqeb@riqfpqpyKyT^oabkGlafJllkplkd%/6+/)22+3&yyNFAy./.34y
QQebC^slolcW^kdrpyKyT^oabkGlafJllkplkd%/6+/)22+3&yyNFAy./.35y
>QebEfde@riqfpqyKyT^oabkGlafJllkplkd%/6+/)22+3&yyNFAy./.36y
@QebEfde@riqfpqyNFAy./.36yyKyEb^aaltkqlqebMfqlcK^ogrk%/3+6)2-+1&+Eb^aofdeq^katlohvlrot^v_^`hqlW^kdrp%/5+5)16+4&y
QQebEfde@riqfpqyKyT^oabkGlafJllkplkd%/6+/)22+3&yyNFAy./.36y

>>sbkdbqefp>qol`fqvyKyBqebkf^iJllkpe^alt%/1+/)3-+.&yyNFAy./--3y
@Ofcibqeb?lafbpyNFAy./---yyRy0246/yyKyIllqqeb_lafbp^olrka%/2+/)25+6&)qebklmbkqebfqbjvlrdbqcoljqebjrkqfivlrdbqqebXJllkobpqD^oabkpMi^kpZy
QOfcibqeb?lafbpyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./---y
>Mobsbkqqeb>``loayKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./--1y
@Mobsbkqqeb>``loayNFAy./--1yyKyJr$c^efplrqpfab^q%.5+1)25+3&)Dlo^jlpefpfkpfablkqebpb`lkaibsbi%.6+2)25+-&y
>>Pqo^kdbAbsf`byKyQebfqbjXDlo^jlpe$pPqo^kdbAbsf`bZpq^oqpnrbpq*aolmmba_vDlo^jlpe^q%.6+2)25&yyNFAy./-22yyRy0341/y
@>sbkdbqefp>qol`fqvyNFAy./--3yyKyHfii?irbAo^dlkcifdeqclo`bp^olrka%/.+6)3/+-&y
QMobsbkqqeb>``loayKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./--1y
Q>Pqo^kdbAbsf`byKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./-22y
>Molgb`qflkp^kaMi^kpyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./-3-y
Q>sbkdbqefp>qol`fqvyKyBqebkf^iJllkpe^alt%/1+/)3-+.&yyNFAy./--3y
>Bka>o`^kfjrpyKyBqebkf^iJllkpe^alt%/1+/)3-+.&yyNFAy./-.0y
@Molgb`qflkp^kaMi^kpyNFAy./-3-yyRy03414yyKyRpbqebXProdbKbbaibQbibmloqboZ)dbq`ilpbbklrdeqldbq`obafq+Rpbfq^d^fkqldbqaltky
@Bka>o`^kfjrpyNFAy./-.0yyKyFkqebmfq_biltqebprodbkbbaib%/-+-)26+2&y
QBka>o`^kfjrpyKyBqebkf^iJllkpe^alt%/1+/)3-+.&yyNFAy./-.0y
QMolgb`qflkp^kaMi^kpyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./-3-y
>QebCl`rplkqeb?b^`eyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./-32y
@QebCl`rplkqeb?b^`eyNFAy./-32yyKyHfii@^mq^fkBjjvJ^ifk%/3+2)31+6&)rpbqebXIbvIfkbCl`rp@lkqoliOfkdZkb^oqebcl`rpyyRy0342.y
>>IbqqbocloEljbyKyQebfqbjX@^mq^fkJ^ifk$pIbqqboZpq^oqpnrbpq*aolmmba_v@^mq^fkBjjvJ^ifk%/3+2)31+6&yyNFAy./-34yyRy03423y
QQebCl`rplkqeb?b^`eyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./-32y
>>qlmqebTllai^kapyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./-50y
Q>IbqqbocloEljbyKy@ljj^kaboP^f^>wrobpqbbi%/6+-)22+2&yyNFAy./-34y
>Pqobkdqebkqeb>k`fbkqpyKyP^obkaov^k^%/5+5)24+.&yyNFAy./-6/y
@Pqobkdqebkqeb>k`fbkqpyNFAy./-6/yyKyEb^aqlIlqe^iloTllai^kap%0.+5)3/+1&+Q^ihqlqebTllai^kapT^ihboclo_^oh)qebkrpbqebX?^ohlcqebT^ihbopZlkqebIlqe^ilo>k`fbkqyyRy03453y
@>qlmqebTllai^kapyNFAy./-50yyKyHfiiIfbrqbk^kqQ^$wfkkf%0/+/)4/+5&cloqebXIbvIfkbCl`rp@lkqoli>jribqZ)rpbfqlkqebcl`rpkb^o_vyyRy03446y

QPqobkdqebkqeb>k`fbkqpyKyP^obkaov^k^%/5+5)24+.&yyNFAy./-6/y
Q>qlmqebTllai^kapyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./-50y
>Pb^o`eFkar$ibSfii^dbyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./-65y

cJl^$hfE^o_loyKy@faCilrkabocfu%15+2)41+1&yyNFAy..625y
eJl^$hfE^o_loyKy@^obdfsboJrjfh%15+/)41+4&yyNFAy..625y

QQo^sbiqlJl^$hfE^o_loyKyBiaboHl$k^kf%15+.)41+6&yyNFAy./..5y
>IbqKlqefkdDlQlT^pqbyKyBiaboHl$k^kf%15+.)41+6&yyNFAy..625y
>Mi^kkfkdcloqebCrqrobyKyQo^mmboJ^r$f%15+0)41+0&yyNFAy..63-y
@Mi^kkfkdcloqebCrqrobyNFAy..63-yyKyPqb^iPkltc^iiDi^abMrmpkloqelcqltk^olrka%12+4)3.+3&y
@IbqKlqefkdDlQlT^pqbyNFAy..625yyKyHfiijl_p^olrkaPkltc^iiDi^ab^q%12+4)3.+3&y
QMi^kkfkdcloqebCrqrobyKyQo^mmboJ^r$f%15+0)41+0&yyNFAy..63-y
QIbqKlqefkdDlQlT^pqbyKyBiaboHl$k^kf%15+.)41+6&yyNFAy..625y
>Pi^vIldrekyKyBiaboHl$k^kf%15+.)41+6&yyNFAy..626y
@Pi^vIldrekyNFAy..626yyKy>qqeberqlkqebkloqepfablcPkltc^iiDi^ab%13+.)26+4&+>cqbovlrhfiiefj)pjb^oefp_illa+yyRy02355y
QPi^vIldrekyKyBiaboHl$k^kf%15+.)41+6&yyNFAy..626y

>Pmfofqr^iFkpfdeqyKyQl^ir$rqebJvpqf`%16+.)42+4&yyNFAy./-/5y
@Pmfofqr^iFkpfdeqyNFAy./-/5yyKyPmb^htfqeQl^ir$rqebJvpqf`%16+.)42+4&^karpbXQl^ir$r$pPmfofqr^iFk`bkpbZlkqeb_o^wfboofdeqlrqpfabqeberqyyRy026-4y
QPmfofqr^iFkpfdeqyKyQl^ir$rqebJvpqf`%16+.)42+4&yyNFAy./-/5y
>BiaboJ^k^$il^yKyQl^ir$rqebJvpqf`%16+.)42+4&yyNFAy./-0-y

>Qr^$hb^$p@o^_Qo^mpyKyQr^$hb^%15+-)43+/&yyNFAy./--6y
>Pfdkplc?fdT^qbovQolr_ibyKyTob`hba@o^_Qo^m%14+4)46+6&)Afsbaltkfkqlqebt^qboyyNFAy./-..y
QPfdkplc?fdT^qbovQolr_ibyKyQr^$hb^%15+-)43+/&yyNFAy./-..y
>Qeb?^fqyKyQr^$hb^%15+-)43+/&yyNFAy./-.3y
@Qeb?^fqyNFAy./-.3yyKyHfiiqeb_fd`o^_lrqlkHfif$r^$p>qliiqlqebtbpq%1/+3)5-+3&y
@Qr^$hb^$p@o^_Qo^mpyNFAy./--6yyKyXQr^$hb^@o^_Qo^mpZ^obclrka^olrkaqebt^qbop%15+-)46+-&+RpbXQr^$hb^$p?ob^qefkd?i^aaboZfcvlrkbbayyRy04/32y
QQr^$hb^$p@o^_Qo^mpyKyQr^$hb^%15+-)43+/&yyNFAy./--6y
QQeb?^fqyKyQr^$hb^%15+-)43+/&yyNFAy./-.3y
>Jb^qlkqebEllhyKyQr^$hb^%15+-)43+/&yyNFAy./-.4y
@Jb^qlkqebEllhyNFAy./-.4yyKyCliiltqebcfpefkdifkblrqqfii%13+4)45+/&)rpbXQr$r$dt^o$p?^fqZ^kahfiiqebpe^ohyyRy02505y
QJb^qlkqebEllhyKyQr^$hb^%15+-)43+/&yyNFAy./-.4y
QBiaboJ^k^$il^yKyBiaboJ^k^$il^%03+5)32+/&yyNFAy./-0-y
>CobbaljcloqebIfkdbofkdyKyBiaboJ^k^$il^%03+5)32+/&yyNFAy./-0.y
QPb^o`eFkar$ibSfii^dbyKyJ^db*@ljj^kaboBsbkpq^o%1-+/)33+6&yyNFAy./-65y
>QebBkalcqebIfkbyKyJ^db*@ljj^kaboBsbkpq^o%1-+/)33+6&yyNFAy./.-4y
KCl`rpyNFAy./.-4yyNLyIbvIfkbCl`rpfkcloj^qflkobqofbsba7.,.yyKyRpbqeb`lkqoliibolkqebcl`rpyyRy035.2y
@CobbaljcloqebIfkdbofkdyNFAy./-0.yyKyHfiijl_p^olrkaqebsfii^dbproolrkafkdBiaboJ^k^$il^%03+5)32+/&y
QCobbaljcloqebIfkdbofkdyKyBiaboJ^k^$il^%03+5)32+/&yyNFAy./-0.y
>@lksbopfkdTfqeqebAbmqepyKyBiaboJ^k^$il^%03+5)32+/&yyNFAy./-0/y
@@lksbopfkdTfqeqebAbmqepyNFAy./-0/yyKyEb^aplrqeql^kfpi^ka%01+.)51+-&+>`qfs^qbqebpeofkb)ifpqbkqlL^`e^$kl^)grjmfkqlqebt^qbotebkebqbiipvlrqly
Q@lksbopfkdTfqeqebAbmqepyKyQl^ir$rqebJvpqf`%16+.)42+4&yyNFAy./-0/y

@QebBkalcqebIfkbyNFAy./.-4yyKyDll_pbosbqeb>wrobAo^dlkpeofkbkloqeb^pqlcqltk%20+-)32+1&y
QQebBkalcqebIfkbyKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./.-4y
>D^fkfkd^k>rafbk`byKyFj^dblc>o`ej^dbJlabo^%/6+-)22+2&yyNFAy./..6y

cTvojobpqQbjmibyKyKbqebpqo^pw%3-+0)2.+2&yyNFAy./433y
eTvojobpqQbjmibyKyAbjbpqo^pw%26+5)21+0&yyNFAy./433y

QD^fkfkd^k>rafbk`byKyQ^oflipqo^pw%24+6)21+/&yyNFAy./..6y
>Pmb^htfqevlro>j_^pp^aloyKyQ^oflipqo^pw%24+6)21+/&yyNFAy./433y
QPmb^htfqevlro>j_^pp^aloyKyI^rofbiQorb_i^ab%3-+-)22+.&yyNFAy./433y
QAfpqro_fkdFjmif`^qflkpyKy>ro^pqo^pw^%3-+-)22+/&yyNFAy./.13y
>ObmloqqlqebOr_vAo^dlkpeofkbyKyI^rofbiQorb_i^ab%3-+-)22+.&yyNFAy./13-y

QObmloqqlqebOr_vAo^dlkpeofkbyKy@bofpqo^pw%2/+0)2-+.&yyNFAy./13-y
>Eb^qba?^qqibyKy@bofpqo^pw%2/+0)2-+.&yyNFAy./1.3y
@Eb^qba?^qqibyNFAy./1.3yyKyCfkaqebKM@pfkqebo^sfkb%2/+-)13+0&+Q^djl_pqebkibqqebKM@phfiifqclovlry
QEb^qba?^qqibyKy@bofpqo^pw%2/+0)2-+.&yyNFAy./1.3y
>ObqrokqlqebB^oqeyKy@bofpqo^pw%2/+0)2-+.&yyNFAy./1.4y
@ObqrokqlqebB^oqeyNFAy./1.4yyKyRpbqebXOr_v>`lokZlkqebab^aOr_vHbbmbopclrka^olrka%14+6)15+-&yyRy044/4y
QObqrokqlqebB^oqeyKy@bofpqo^pw%2/+0)2-+.&yyNFAy./1.4y
>QeolrdeCfbiaplcCi^jbyKy@bofpqo^pw%2/+0)2-+.&yyNFAy./1.5y
@QeolrdeCfbiaplcCi^jbyNFAy./1.5yyKyHfiikb`olj^k`bop^olrka%14+6)15+-&)qebkcfkaqeb_^kpebbrkaboqebpeofkb%14+6)16+6&y
>QebC^qblcqebOr_vAo^dlkpeofkbyKyQebfqbjXOr_v?oll`eZpq^oqpnrbpq*aolmmba_vA^eif^Prkqlr`e%14+3)16&yyNFAy./1.6yyRy04500y
QQeolrdeCfbiaplcCi^jbyKy@bofpqo^pw%2/+0)2-+.&yyNFAy./1.5y
>QebPqbt^oalcTvojobpqQbjmibyKy@bofpqo^pw%2/+0)2-+.&yyNFAy./435y
QQebPqbt^oalcTvojobpqQbjmibyKyQ^oflipqo^pw%24+6)21+/&yyNFAy./435y
>FkclojfkdqebNrbbkyKyQ^oflipqo^pw%24+6)21+/&yyNFAy././0y
QFkclojfkdqebNrbbkyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&)civqlqlmibsbiyyNFAy././0y
>ObmloqqlIloa>co^p^pqo^pwyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyNFAy./102y
QQebC^qblcqebOr_vAo^dlkpeofkbyKyHo^prp%26+5)21+3&yyNFAy./1.6y
>PbbaplcqebI^pebopyKyIloaFqe^ofrp%26+3)21+2&yyNFAy./125y
QObmloqqlIloa>co^p^pqo^pwyKyIloa>co^p^pqo^pw%26+/)21+0&)civqljfaaibibsbiyyNFAy./102y
>AbcbkafkdTvojobpqQbjmibyKyIloa>co^p^pqo^pw%26+/)21+0&yyNFAy./04/y
@AbcbkafkdTvojobpqQbjmibyNFAy./04/yyKyElmlk^ao^dlk)hfii>wrobAo^dlkp^kaAo^hbp)qebkabpq^_fifwbqeb>wrobAo^dlkpeofkb%22+6)32+6&y
QAbcbkafkdTvojobpqQbjmibyKyIloa>co^p^pqo^pw%26+/)21+0&yyNFAy./04/y

>@v`iblcIfcbyKyKfpebo^qebD^oabkHbbmbo%3/+2)40+0&)t^kabofkdKM@yyNFAy./121y
@@v`iblcIfcbyNFAy./121yyKyHfiiBjbo^iaPhvq^ilkpcivfkd^olrka%31+.)43+3&y
@PbbaplcqebI^pebopyNFAy./125yyKyXI^peboPbbapZclrka^olrka%30+2)4.+2&lkqebdolrkay
Q@v`iblcIfcbyKyKfpebo^qebD^oabkHbbmbo%3/+2)40+0&)t^kabofkdKM@yyNFAy./121y

QPbbaplcqebI^pebopyKyIloaFqe^ofrp%26+3)21+2&yyNFAy./125y
>Qe^qTef`e@ob^qbp@^k>iplAbpqolvyKyIloaFqe^ofrp%26+3)21+2&yyNFAy./126y
>JvpqbovlcqebFkcfkfqbyKy@eoljfb%3-+-)21+2&yyNFAy./14-y
>QebL_pfaf^kAo^dlkpeofkbyKyK^if`b%3-+-)21+/&yyNFAy./114y

QQlCloao^dlkEliayKyEfdeiloa?lis^oCloao^dlk%04+5)/0+2&yyNFAy./141y
>>rafbk`bTfqeQebAo^dlkNrbbkyKyEfdeiloa?lis^oCloao^dlk%04+5)/0+2&yyNFAy./162y

QQebL_pfaf^kAo^dlkpeofkbyKyPbofk^o%02+/)0-+.&yyNFAy./114y
>KlLkbqlP^sbVlryKyPbofk^o%02+/)0-+.&yyNFAy.//3/y
>KlMi^`bqlOrkyKyPbofk^o%02+/)0-+.&yyNFAy.//3.y
@KlMi^`bqlOrkyNFAy.//3.yyRy04112yyKyEb^alrqpfab)rpbqebXAbpqor`qfsbT^oapZtebobqebm^qejbbqpqebpklt%1.+0)0.+5&y
@KlLkbqlP^sbVlryNFAy.//3/yyKyJl_p`^k_bclrkabfqebofkpfablolrqpfabqeb`^sb%04+5)00+/&y
QKlLkbqlP^sbVlryKyPbofk^o%02+/)0-+.&yyNFAy.//3/y
QKlMi^`bqlOrkyKyPbofk^o%02+/)0-+.&yyNFAy.//3.y
>Qeb?bpqlcFkqbkqflkpyKyPbofk^o%02+/)0-+.&yyNFAy.//30y
@Qeb?bpqlcFkqbkqflkpyNFAy.//30yyKyQ^hbqebm^qekloqeqlqebj^dj^tvojobproob`qflk`e^j_bo%0.+4)0-+2&y
QQeb?bpqlcFkqbkqflkpyKyPbofk^o%02+/)0-+.&yyNFAy.//30y
>@riifkdqebA^jkbayKyPbofk^o%02+/)0-+.&yyNFAy.//31y
>AbcfifkdqebAbcfibopyKyPbofk^o%02+/)0-+.&yyNFAy.//32y
@AbcfifkdqebAbcfibopyNFAy.//32yyKyCroqebofkpfabqeb`^sbp^olrka%0/+-)/5+1&)abpqolvqeborkb`fo`ibplkqebdolrkay
@@riifkdqebA^jkbayNFAy.//31yyKyHfiijl_pcroqebofkpfabqeb`^sbp^olrka%0/+-)/5+1&y
Q@riifkdqebA^jkbayKyPbofk^o%02+/)0-+.&yyNFAy.//31y
QAbcfifkdqebAbcfibopyKyPbofk^o%02+/)0-+.&yyNFAy.//32y
>Kbiqe^oflk$pCi^jbyKyPbofk^o%02+/)0-+.&yyNFAy.//34y
@Kbiqe^oflk$pCi^jbyNFAy.//34yyKyEb^a_^`hqlqebj^dj^tvojobproob`qflk`e^j_bo%0.+4)0.+.&)rpbXKbiqe^oflk$pCi^jbZ^kahfiiOlqefkyyRy04206y
QKbiqe^oflk$pCi^jbyKyPbofk^o%02+/)0-+.&yyNFAy.//34y
>Q^ibplcAbpqor`qflkyKyPbofk^o%02+/)0-+.&yyNFAy.//33y

HTb^hbkbaOb^kfj^qbaColpqTvojyNFAy./126yyNLyTb^hbkbaOb^kfj^qbaColpqTvojpi^fk7.,.yyKyRpbqebXPbbaplcK^qrob$pTo^qeZlk^colpqtvoj^kahfiifq+Cfkaqebjkb^oD^i^holka$pObpq%21+-)05+.&yyRy04554y
@JvpqbovlcqebFkcfkfqbyNFAy./14-yyKyRpbqebXElrodi^pplcBqbokfqvZ^qqeb?olkwbAo^dlkpeofkb%4.+/)06+6&)molqb`qfqcoljqebao^dlkpqe^qpm^tkyyRy046/0y
@Qe^qTef`e@ob^qbp@^k>iplAbpqolvyNFAy./126yyRy04554yyKyLsbopbboAb^qed^wbfpfkGfkqe^$h^i^o%56+1).5+6&+QrodfaqebSfibfpfkqeb_olhbkhbbm_biltK^uu%52+6)14+3&y

ETvojobpqQbjmibyRy3615yyNFAy./164y
QQ^ibplcAbpqor`qflkyKyK^if`b%3-+-)21+/&yyNFAy.//33y
QJvpqbovlcqebFkcfkfqbyKy@eoljfb%3-+-)21+2&yyNFAy./14-y
QQe^qTef`e@ob^qbp@^k>iplAbpqolvyKyIloaFqe^ofrp%26+3)21+2&yyNFAy./126y
Q>rafbk`bTfqeQebAo^dlkNrbbkyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyNFAy./162y
>D^i^holka^kaqebP`lrodbyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyNFAy./164y
QD^i^holka^kaqebP`lrodbyKyQlo^pqo^pw^%26+3)20+2&yyNFAy./164y
>LkOr_vTfkdpyKyQlo^pqo^pw^%26+3)20+2&yyNFAy./165y
@LkOr_vTfkdpyNFAy./165yyRy050-/yyKyRpbqebXOr_v?b^`lklcqebAo^dlkNrbbkZ)civrmqlD^i^holka$pObpq%22+3)01+2&qlcfkaqebP`^sbkdbopqebkhfiiDo^kaKb`oliloa>kqflh%21+.)0-+3&y
QLkOr_vTfkdpyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyNFAy./165y
>ObqrokQl>kdo^qe^oyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyNFAy./166y

CCloao^dlkEliayKyKbqebpqo^pw%3-+0)2.+2&qlAbobhO^jjbi%06+3)/2+6&yyNFAy.0014y
QObqrokQl>kdo^qe^oyKyEfdeiloa?lis^oCloao^dlk%04+5)/0+2&yyNFAy./166y
>Ob_lokColjQeb>pebpyKy>ibupqo^pw^qebIfcb*?fkabo%05+2).6+0&yyNFAy.0014y
@Ob_lokColjQeb>pebpyNFAy.0014yyKyCfkaXCloao^dlk$pPefbiaZkb^o_v%05+.).6+3&y

CS^if^k`bHbbmyKyAbobhO^jjbi%06+22)/3&yyNFAy.0036y
_Pqlojtfka@fqvyKyQ^hbqeb_l^qqlPqlojtfka@fqv%26+32)36+02&yyNFAy.0036y
QOb_lokColjQeb>pebpyKyHfkdS^of^kTovkk%46+6)05+3&yyNFAy.0014yyWyPqlojtfka@fqvy
>C^qb)Rm>d^fkpqVlroTfiiyKyHfkdS^of^kTovkk%46+6)05+3&yyNFAy.0036yyWyPqlojtfka@fqvy
QC^qb)Rm>d^fkpqVlroTfiiyKyQeo^ii%0/+4)04+6&yyNFAy.0036yyWyLodofjj^oy
OLodofjj^oyKyQ^hbqebmloq^iqlLodofjj^oy
>>Olv^i@lrmyKyQeo^ii%0/+4)04+6&yyNFAy.004-yyWyLodofjj^oy
OPqlojtfka@fqvyKyQ^hbqebmloq^iqlPqlojtfka@fqvy
Q>Olv^i@lrmyKyHfkdS^of^kTovkk%46+6)05+3&)q^hbqebmloq^iyyNFAy.004-yyWyPqlojtfka@fqvy
>QebHfiifkdQfjbyKyHfkdS^of^kTovkk%46+6)05+3&yyNFAy.004.yyWyPqlojtfka@fqvy
QQebHfiifkdQfjbyKy?olii?b^oj^kqib%2-+.)35+2&)q^hbqebmloq^iyyNFAy.004.yyWyPqlojtfka@fqvy
OQfofpc^iDi^abpyKyQ^hbqebmloq^iqlQfofpc^iDi^abpy
>Qeb?^qqibCloQebRkabo`fqvyKy?olii?b^oj^kqib%2-+.)35+2&yyNFAy.0044yyWyQfofpc^iDi^aby
@Qeb?^qqibCloQebRkabo`fqvyNFAy.0044yyKyT^fqcloqebqfjboqebkpmb^htfqeHfkdS^of^kTovkk^kaglfkfkqeb_^qqiby
OPqlojtfka@fqvyKyQ^hbqebmloq^iqlPqlojtfka@fqvy
QQeb?^qqibCloQebRkabo`fqvyKyHfkdS^of^kTovkk%46+6)05+3&yyNFAy.0044yyWyPqlojtfka@fqvy

ETvojobpqQbjmibyRy3615yyNFAy./2..y
CTfkqbod^oabHbbmyKyKbqebpqo^pw%3-+0)2.+2&qlFiirpf^Irkb%44+2)2.+2&yyNFAy./2..y
>QebEfiipE^sbRpyKyDovmelk@ljj^kaboRofh%44+.)2-+.&yyNFAy./2..y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
