DugisGuideViewer:RegisterGuide("Grizzly Hills (75-76)", "Zul'Drak (76-78)", "Alliance", "L", function()
return [[
AAA

O>j_bomfkbIladbyKyQo^sbiql>j_bomfkbIladb%0/+-)3-+/&yyNFAy.///2y
e>j_bomfkbIladbyKyGbkkfcbo?bii%0/+-)3-+/&yyNFAy.///2y
c>j_bomfkbIladbyKyS^k^Dobv%0.+0)26+/&yyNFAy.///2y

>Jjj+++>j_bopbbapyKy>j_bopbba%0.+5)26+3&yyNFAy.///2y
QJjj+++>j_bopbbapyKyJ^pqboTllapj^k>kaboeli%0/+.)3-+-&yyNFAy.///2y
>GrpqM^ppfkdQeolrdeyKyJ^pqboTllapj^k>kaboeli%0/+.)3-+-&yyNFAy.///3y
>ObmibkfpefkdqebPqlobelrpbyKyJ^pqboTllapj^k>kaboeli%0/+.)3-+-&yyNFAy.//./y
>QebjloRpyKyJ^pqboTllapj^k>kaboeli%0/+.)3-+-&yyNFAy.//.2y
QQebEfiipE^sbRpyKyIfbrqbk^kqArjlkq%0.+6)3-+/&yyNFAy./2..y
>Il`^iPrmmloqyKyIfbrqbk^kqArjlkq%0.+6)3-+/&yyNFAy.//6/y
>QebJ^df`^iHfkdaljlcA^i^o^kyKyJ^dfpqofuE^bibk^f%0/)26+6&yyNFAy./461y

QQebJ^df`^iHfkdaljlcA^i^o^kyKyQ^ihqlJ^dfpqofuE^bibk^qldbq^mloqqlA^i^o^k)>o`ej^db@bifkao^%23+/)14+.&yyNFAy./461yyWyA^i^o^ky
>Ib^okfkdqlIb^sb^kaObqrok7qebJ^df`^iT^vyKy>o`ej^db@bifkao^%23+/)14+.&yyNFAy./46-yyWyA^i^o^ky
@Ib^okfkdqlIb^sb^kaObqrok7qebJ^df`^iT^vyKyRpbqebQbibmloq@ovpq^iKbuqql>o`ej^db@bifkao^%23+/)14+.&)qebkrpbqeblkbvlrdbqmloqbaql)qldbq_^`hyyNFAy./46-yyWyA^i^o^ky
QIb^okfkdqlIb^sb^kaObqrok7qebJ^df`^iT^vyKy>o`ej^db@bifkao^%23+/)14+.&yyNFAy./46-yyWyA^i^o^ky
cHo^prp$I^kafkdyKy>ira^kbTefqb`ilra%4/+2)12+1&yyWyA^i^o^kyyNFAy.//6/y
C>j_bomfkbIladbyKy>ira^kbTefqb`ilra%4/+2)12+1&yyWyA^i^o^kyyNFAy.//6/y

@Il`^iPrmmloqyNFAy.//6/yyKyQebX@ba^o@ebpqZfpfkqebqltbo^qBsbodobbkQo^afkdMlpq%.2+6)32+0&y
@QebjloRpyNFAy.//.2yyKyDo^vjfpqErkqbopclrka^q%/2+4)4-+.&)lkqebTbpqpfablcqebofsboy
@ObmibkfpefkdqebPqlobelrpbyNFAy.//./yyKyClrka^olrka%0.+3)22+3&^ka%0/+5)32+2&y

QIl`^iPrmmloqyKyIfbrqbk^kqArjlkq%0.+6)3-+/&yyNFAy.//6/y
>@ilpbqebAb^iyKyIfbrqbk^kqArjlkq%0.+6)3-+/&yyNFAy.//60y
QObmibkfpefkdqebPqlobelrpbyKyJ^pqboTllapj^k>kaboeli%0/+.)3-+-&yyNFAy.//./y
>Q^hbQebfoOb^oyKyJ^pqboTllapj^k>kaboeli%0/+.)3-+-&yyNFAy.//.3y
QQebjloRpyKyJ^pqboTllapj^k>kaboeli%0/+.)3-+-&yyNFAy.//.2y
>B^dibBvbpyKyJ^pqboTllapj^k>kaboeli%0/+.)3-+-&yyNFAy.//.4y
>QoliiPb^plkyKyIfbrqbk^kqArjlkq%0.+6)3-+/&yyNFAy.//.-y

@GrpqM^ppfkdQeolrdeyNFAy.///3yyKyX?i^`hollqPq^ihpZclrka^olrkaqebofsbo%/6+3)22+0&y
@Q^hbQebfoOb^oyNFAy.//.3yyKyVlr`^kcfkaqeb_b^op^ii^ilkdqebofsbo%/6+1)2/+5&y
Q@ilpbqebAb^iyKyFs^k%01+5)22+3&yyNFAy.//60y
>>Qbkq^qfsbM^`qyKyFs^k%01+5)22+3&yyNFAy.//61y
@B^dibBvbpyNFAy.//.4yyKyHfiib^dibp_bqtbbk>pmbkDolsbMlpq^ka>j_bomfkbIladb%01+3)26+/&y

Q>Qbkq^qfsbM^`qyKyIfbrqbk^kqArjlkq%0.+6)3-+/&yyNFAy.//61y
>>kBubo`fpbfkAfmilj^`vyKyIfbrqbk^kqArjlkq%0.+6)3-+/&yyNFAy.//62y
QQ^hbQebfoOb^oyKyJ^pqboTllapj^k>kaboeli%0/+.)3-+-&yyNFAy.//.3y
QGrpqM^ppfkdQeolrdeyKyJ^pqboTllapj^k>kaboeli%0/+.)3-+-&yyNFAy.///3y
>AlfkdVlroArqvyKyJ^pqboTllapj^k>kaboeli%0/+.)3-+-&yyNFAy.///4y
QB^dibBvbpyKyJ^pqboTllapj^k>kaboeli%0/+.)3-+-&yyNFAy.//.4y
@AlfkdVlroArqvyNFAy.///4yyKyCfkaqeblrqelrpb^q%0/+/)25+6&y
>Pb`obqplcqebCi^jb_fkabopyKyTllapj^kAo^hb%0/+2)3-+-&yyNFAy.////y
>QefkkfkdqebO^khpyKyTllapj^kAo^hb%0/+2)3-+-&yyNFAy.///0y
QAlfkdVlroArqvyKyJ^pqboTllapj^k>kaboeli%0/+.)3-+-&yyNFAy.///4y

@Pb`obqplcqebCi^jb_fkabopyNFAy.////yyKyCfkaqebCi^jb_fkabop^qSliaorkb%/6+-)42+-&y
@QefkkfkdqebO^khpyNFAy.///0yyKyCfkaqebAo^dlkci^vboErp`^oip^qSliaorkb%/6+-)42+-&y
QPb`obqplcqebCi^jb_fkabopyKyTllapj^kAo^hb%0/+2)3-+-&yyNFAy.////y
QQefkkfkdqebO^khpyKyTllapj^kAo^hb%0/+2)3-+-&yyNFAy.///0y
>QebQe^kblcSliaorkbyKyTllapj^kAo^hb%0/+2)3-+-&yyNFAy.//22y
@QebQe^kblcSliaorkbyNFAy.//22yyKyElmlkqebmolql*ao^hb%/4)45&fkSliaorkb)Qe^kbQlos^iaBofhpplkfpqlmlcqebkb^o_vqltbo%/4+-)40+-&)_bprobqlhbbmefjpqrkkbatefipq^qq^`hfkdy
QQebQe^kblcSliaorkbyKyTllapj^kAo^hb%0/+2)3-+-&yyNFAy.//22y

QQoliiPb^plkyKyP^jfo%.3+/)14+4&yyNFAy.//.-y
>Cfiifkdqeb@^dbpyKyP^jfo%.3+/)14+4&yyNFAy..651y
@Cfiifkdqeb@^dbpyNFAy..651yyRy02403yyKyQ^ihql?raa%.3+1)15+.&)qebkeb^aqlqebOrfkplcAo^h$Wfk%.0+4)25+3&^karpbvlrombq_^oqlpbkaefj^cqbo^qolii)qebkrpbqebX?lrkqvErkqbo$p@^dbZlk`ba^wbay
QCfiifkdqeb@^dbpyKyP^jfo%.3+/)14+4&yyNFAy..651y
>Qor`b<yKyAo^hror%.3+2)14+5&yyNFAy..656y
@Qor`b<yNFAy..656yyKyIllqqebXArii@^osfkdHkfcbZkbuqqlqeb`^db)rpbfq)qebkq^ihqlAo^hror%.3+2)14+5&qlpe^hbefpe^kayyRy05-50y
QQor`b<yKyAo^hror%.3+2)14+5&yyNFAy..656y
>Sf^ilcSfpflkpyKyAo^hror%.3+2)14+5&yyNFAy..66-y
??rvXFj_rbaSf^iZyKy?rvXFj_rbaSf^iZcolj%.3+-)14+5&yyNFAy..66-yyIy.5/23y
@Sf^ilcSfpflkpyNFAy..66-yyKyT^qbotbbafpfkqebi^hb%.2+/)1-+3&+E^wbib^cfpclrka^olrka%.0+.)1.+0&^ka%.0+-)05+6&y
QSf^ilcSfpflkpyKyAo^hror%.3+2)14+5&yyNFAy..66-y
>Pr_gb`qqlFkqbomobq^qflkyKyAo^hror%.3+2)14+5&yyNFAy..66.y
>P`lrodbh^_l_yKyMofdjlk%.2+5)13+5&yyNFAy./151y
@P`lrodbh^_l_yNFAy./151yyKyIllq^jrjjvqebkeb^aaltkqlqeb_lkcfob%.3+4)15+/&^ka_rokfqyyRy05.16y
QP`lrodbh^_l_yKyJ^`hCb^opbk%.3+4)15+0&yyNFAy./151y
>Pb^obaP`lrodbyKyJ^`hCb^opbk%.3+4)15+0&yyNFAy./-/6y
>Pefjjbo`^mPqbtyKyMofdjlk%.2+5)13+5&yyNFAy./150y
KPefjjbofkdPklt`^myKy>ilkdqebofsbo_^khplrqelcqebOrfkplcAo^h$Wfk%.-+3)30+6&yyNFAy./150yyNLyPefjjbofkdPklt`^m72,2y
HF`bPbombkqpyKy>iilsboqebOrfkplcAo^h$Wfk%.0+4)25+3&yyNFAy./150yyNLyF`bPbombkqBvb72,2y
HQoliipyKyFkqebOrfkplcAo^h$Wfk%.0+4)25+3&ql`liib`q2ColwbkJlglyyIy024662yyNFAy..66.y
QPr_gb`qqlFkqbomobq^qflkyKyFj^dblcAo^hror%.0+0)3-+6&+RpbXAo^hror$pBifufoZ^qqeb_o^wfboyyNFAy..66.yyRy02464y
>P^`ofcf`bpJrpq_bJ^abyKyFj^dblcAo^hror%.0+0)3-+6&yyNFAy./--4y
@P^`ofcf`bpJrpq_bJ^abyNFAy./--4yyKyHfiiT^oiloaWfj$_l%.1+3)04+5&)eb^armqebwfddro^q^kaq^hbqebbvbcoljqebeb^aqebob%.4+6)03+2&y
QP^`ofcf`bpJrpq_bJ^abyNFAy./--4yyKyFj^dblcAo^hror%.4+16)03+0-&+RpbXAo^hror$pBifufoZ^qqeb_o^wfboyyRy02464y
>Eb^oqlcqeb>k`fbkqpyKyFj^dblcAo^hror%.4+16)03+0-&yyNFAy./-1/y
@Pefjjbo`^mPqbtyNFAy./150yyKyXPtbbqollqZfp^iilsboWb_$E^i^h^olrka%.1+5)04+-&y

Q>kBubo`fpbfkAfmilj^`vyKyBkslvAr`^i%/3+2)02+5&yyNFAy.//62y
>KloqebokElpmfq^ifqvyKyPbodbf%/3+2)02+5&yyNFAy.//66y
>Tlicp_^kbOllqyKyH^qg^%/2+3)00+1&yyNFAy./0-4y
@KloqebokElpmfq^ifqvyNFAy.//66yyKy>ilkdqebkloqetbpqpfablcqebsfii^db^olrka%/1+.)03+-&y
@Tlicp_^kbOllqyNFAy./0-4yyKyVlr`^kcfka^ilq^olrka%/5+2)05+2&y
QKloqebokElpmfq^ifqvyKyPbodbf%/3+2)02+5&yyNFAy.//66y
QTlicp_^kbOllqyKyH^qg^%/2+3)00+1&yyNFAy./0-4y
>QbpqlcJbqqibyKyPbodbf%/3+2)02+5&yyNFAy./0--y
@QbpqlcJbqqibyNFAy./0--yyKyCfkaPbodb^kq?lkbpk^m^q?lkbpk^m$p@^jm%/.+6)/6+6&y
QQbpqlcJbqqibyKy@^mqrobaQo^mmbo%/.+6)0-+-&yyNFAy./0--y
>TloaplcT^okfkdyKy@^mqrobaQo^mmbo%/.+6)0-+-&yyNFAy./0-/y

@Pb^obaP`lrodbyNFAy./-/6yyRy026-5yyKyDlqlAo^h$qe^olkHbbm%.4+5)/4+0&+Dlrmqebpq^fop^kagrjmlkqlqebbadbplcqebpq^fo`^pb+Il_XJ^`h$pA^ohDoldZ^qqebqoliip_bilty

QPefjjbo`^mPqbtyKyMofdjlk%.2+5)13+5&yyNFAy./150y
>P^vEbiilqlJvIfqqibCofbkayKyMofdjlk%.2+5)13+5&yyNFAy./.6-y
QPb^obaP`lrodbyKyJ^`hCb^opbk%.3+4)15+0&yyNFAy./-/6y

QTloaplcT^okfkdyKy@^dbaMofplkbo%/3+2)0.+5&yyNFAy./0-/y
>Bp`^mbcoljPfisbo_ollhyKy@^dbaMofplkbo%/3+2)0.+5&yyNFAy./0-5y
@Bp`^mbcoljPfisbo_ollhyNFAy./0-5yyKyQebKM@tfiiaofsbclovlr)vlrgrpqkbbaqlcfdeqlccqebjl_pqe^q^qq^`h+Rpbb^`ephfiilkvlrosbef`ib_^o^plcqbk^pvlr`^ky
QBp`^mbcoljPfisbo_ollhyKyIfbrqbk^kqArjlkq%0.+6)3-+/&yyNFAy./0-5y
>>PtfcqObpmlkpbyKyIfbrqbk^kqArjlkq%0.+6)3-+/&yyNFAy./0.-y
@>PtfcqObpmlkpbyNFAy./0.-yyKyPlrqeb^pq^qClobpq$pBadbMlpq+Si^abhfpfkqebqltbo%03+/)34+5&y
>Abp`bkqfkqlA^ohkbppyNFAy./.-2yyRy0361-yyKyQebfqbjXJfhe^fi$pGlrok^iZpq^oqpnrbpq*aolmmba_vSi^abh%03+/)34+5&^kaPfisbo_ollhErkqbop%04)35&y
Q>PtfcqObpmlkpbyKyIfbrqbk^kqArjlkq%0.+6)3-+/&yyNFAy./0.-y
QAbp`bkqfkqlA^ohkbppyKyIfbrqbk^kqArjlkq%0.+6)3-+/&yyNFAy./.-2y
>ObmloqqlDov^kPqlrqj^kqib+++>d^fkyKyIfbrqbk^kqArjlkq%0.+6)3-+/&yyNFAy./.-6y

>QebC^fibaTloiaQobbyKyEfbolme^kqQe^vobbk%0.+/)26+2&yyNFAy.//.6y
>>A^ohFkcirbk`byKyEfbolme^kqQe^vobbk%0.+/)26+2&yyNFAy.///-y
@>A^ohFkcirbk`byNFAy.///-yyRy04.40yyKySfpfqSloao^ppfi$pQb^op%/5+3)12+.&)Sloao^ppfi$pIfj_%00+/)15+0&^kaSloao^ppfi$pEb^oq%1-+5)2/+.&+Eb^aaltkqlqeb_lqqljlcb^`e^karpbXDblj^k`bo$pLo_Zy
@QebC^fibaTloiaQobbyNFAy.//.6yyKyHfiiBkqolmf`Llwbp^olrkaSloao^ppfi$pQb^op%/5+3)12+.&)Sloao^ppfi$pIfj_%00+/)15+0&^kaSloao^ppfi$pEb^oq%1-+5)2/+.&y
QQebC^fibaTloiaQobbyKyEfbolme^kqQe^vobbk%0.+/)26+2&yyNFAy.//.6y
Q>A^ohFkcirbk`byKyEfbolme^kqQe^vobbk%0.+/)26+2&yyNFAy.///-y
>>Mlppf_ibIfkhyKyEfbolme^kqQe^vobbk%0.+/)26+2&yyNFAy.//13y
>@efiaobklcRopl`yKyEfbolme^kqQe^vobbk%0.+/)26+2&yyNFAy.//14y
@@efiaobklcRopl`yNFAy.//14yyKyQ^ihqlLoplkkfkqeb`^sb^qO^dbC^kdPeofkb%15+-)25+5&^kaHlaf^kfkqeb`^sb^qEb^oq$p?illaPeofkb%33+6)3/+3&y
@>Mlppf_ibIfkhyNFAy.//13yyKyHfiicro_ildp^olrkaqebO^dbC^kdPeofkb%15+-)25+5&^kaEb^oq$p?illaPeofkb%33+6)3/+3&y
Q>Mlppf_ibIfkhyKyEfbolme^kqQe^vobbk%0.+/)26+2&yyNFAy.//13y
Q@efiaobklcRopl`yKyEfbolme^kqQe^vobbk%0.+/)26+2&yyNFAy.//14y
>Sloao^ppfi$pP^mifkdyKyEfbolme^kqQe^vobbk%0.+/)26+2&yyNFAy.//15y
>Sloao^ppfi$pPbbapyKyEfbolme^kqQe^vobbk%0.+/)26+2&yyNFAy.//2-y

@Sloao^ppfi$pP^mifkdyNFAy.//15yyKyB^pq^qDofwwibj^t%2-+2)12+5&)grjmaltkfkqlqeb`bkqbo+RpbqebXSboa^kqQlo`eZlkqebp^mifkdyyRy040-3y
@Sloao^ppfi$pPbbapyNFAy.//2-yyKyFkpfabSloao^ppfi$ppfabolljp%2-)04&lolrqpfab^olrkaqebbadblcqebqorkh+Kloqepfablcqebqobbpbbjpifhb^dob^q^ob^y
>Jo+Cilmmv$pMbofilrp>asbkqrobyKyBjfiv%16+/)01+.&yyNFAy./-/4y
@Jo+Cilmmv$pMbofilrp>asbkqrobyNFAy./-/4yyKyBp`loqBjfivlrqp^cbiv)_bprobqlhfiiqebi^pqtlicfk^afccbobkqmlpfqflkcoljtebobebmf`hprmqeb_rkkvy

QJo+Cilmmv$pMbofilrp>asbkqrobyKyPnrfobT^iqbo%26+.)/3+2&yyNFAy./-/4y
cTbpqc^ii?ofd^abBk`^jmjbkqyKyP^jrbi@ib^o_llh%26+6)/3+4&yyNFAy./.25y
C>j_bomfkbIladbyKyP^jrbi@ib^o_llh%26+6)/3+4&yyNFAy./.25y
QSloao^ppfi$pP^mifkdyKyEfbolme^kqQe^vobbk%0.+/)26+2&yyNFAy.//15y
QSloao^ppfi$pPbbapyKyEfbolme^kqQe^vobbk%0.+/)26+2&yyNFAy.//2-y

CTbpqc^ii?ofd^abBk`^jmjbkqyKyS^k^Dobv%0.+0)26+/&yyNFAy./.25y
eTbpqc^ii?ofd^abBk`^jmjbkqyKyNr^oqboj^pqboJ`@^oqv%26+2)/3+0&yyNFAy./.25y
QObmloqqlDov^kPqlrqj^kqib+++>d^fkyKy@^mq^fkDov^kPqlrqj^kqib%26+2)/3+.&yyNFAy./.-6y
>EliiltpqlkbJfkbyKy@^mq^fkDov^kPqlrqj^kqib%26+2)/3+.&yyNFAy./.25y
>Plcqbkfkdqeb?iltyKy@^mq^fkDov^kPqlrqj^kqib%26+2)/3+.&yyNFAy..665y
>JlrkqfkdRmyKyPnrfobMbo`v%26+.)/3+3&yyNFAy./1.1y

@JlrkqfkdRmyNFAy./1.1yyRy044-5yyKyCfkaqebeboalcelopbpqlqebtbpq%22+5)0.+4&+BnrfmqebXPqf`hZ)cfka^cbt`^oolqp)q^odbq^elopb)rpbqebXPqf`hZ+Q^hbqebelopb_^`hqlqeb`^jm)obmb^qy
QJlrkqfkdRmyKyPnrfobMbo`v%26+.)/3+3&yyNFAy./1.1y

QEb^oqlcqeb>k`fbkqpyKyEb^oqlcqeb>k`fbkqp%04+-)0/+1&yyNFAy./-1/y
>JvEb^oqfpfkVlroE^kapyKyEb^oqlcqeb>k`fbkqp%04+-)0/+1&yyNFAy./5-/y
QJvEb^oqfpfkVlroE^kapyKyFj^dblcAo^hror%12+-)/5+0&+Hfiiqebproolrkafkdqoliipclo2XAbpmbo^qbJlglZyyNFAy./5-/y
>Slf`bpColjqebArpqyKyFj^dblcAo^hror%12+-)/5+0&yyNFAy./-35y

QEliiltpqlkbJfkbyKyMbqols%22+/)/0+2&yyNFAy./.25y
>Plrip^qRkobpqyKyMbqols%22+/)/0+2&yyNFAy./.26y
@Plrip^qRkobpqyNFAy./.26yyRy0460/yyKyHfiirkab^ap^ka_rokqebjrpfkdqebXJfkbo$pI^kqbokZfkqebp^jb`^sb^pMbqols%22+/)/0+2&y
QPlrip^qRkobpqyKyMbqols%22+/)/0+2&yyNFAy./.26y
>>K^jbcoljqebM^pqyKyMbqols%22+/)/0+2&yyNFAy./.3-y
Q>K^jbcoljqebM^pqyKy@^mq^fkDov^kPqlrqj^kqib%26+2)/3+.&yyNFAy./.3-y
>Orrk^qeb?ifkayKyMofs^qb>ork%26+/)/3+/&yyNFAy./.3.y
QOrrk^qeb?ifkayKyOrrk^qeb?ifka%11+.)15+-&yyNFAy./.3.y
>Orrk^$pObnrbpqyKyOrrk^qeb?ifka%11+.)15+-&yyNFAy./0/5y
@Orrk^$pObnrbpqyNFAy./0/5yyKyCfkaqebCbokCbbaboJlqep^olrka%14+/)04+5&lo%2/+4)/5+/&y
QOrrk^$pObnrbpqyKyOrrk^qeb?ifka%11+.)15+-&yyNFAy./0/5y
>Lrqlc?lavBumbofbk`byKyOrrk^qeb?ifka%11+.)15+-&yyNFAy./0/4y
@Lrqlc?lavBumbofbk`byNFAy./0/4yyRy0433.yyKyRpbqebXDlpp^jboMlqflkZpebd^sbvlry
QLrqlc?lavBumbofbk`byKyOrrk^qeb?ifka%11+.)15+-&yyNFAy./0/4y
>C^qb^ka@lfk`fabk`byKyOrrk^qeb?ifka%11+.)15+-&yyNFAy./0/6y
QC^qb^ka@lfk`fabk`byKyP^pe^%24+2)1.+/&yyNFAy./0/6y
>P^pe^$pErkqyKyP^pe^%24+2)1.+/&yyNFAy./.01y
>>k^qlivTfiiQ^ihyKyP^pe^%24+2)1.+/&yyNFAy./00-y
@P^pe^$pErkqyNFAy./.01yyKyPlipqf`bErkqbopclrkafkPliqf`bSfii^db^olrka%3.+5)1/+-&y
@>k^qlivTfiiQ^ihyNFAy./00-yyRy04332yyKyCfkaQ^qg^k^%3/+3-)1.+40&)lkeboelopb+RpbqebXQo^knrfifwboA^oqZlkebo)qebkelmlkqebelopby
QP^pe^$pErkqyKyP^pe^%24+2)1.+/&yyNFAy./.01y
Q>k^qlivTfiiQ^ihyKyP^pe^%24+2)1.+/&yyNFAy./00-y
>>Pfpqbo$pMibadbyKyP^pe^%24+2)1.+/&yyNFAy./1..y
Q>Pfpqbo$pMibadbyKy>kv^%31+6)10+2&yyNFAy./1..y
>ElrolcqebTlodyKyP^pe^%24+2)1.+/&yyNFAy./.31y

>>?b^olc^k>mmbqfqbyKyErdeDi^pp%36+.)1-+.&yyNFAy.//46y
@Plcqbkfkdqeb?iltyNFAy..665yyKy?rv^XEltifk$DllaJllkpefkbZcoljErdeDi^pp%36+.)1-+.y

QPlcqbkfkdqeb?iltyKy?ord^oPqlkbpeb^o%26+5)/4+3&yyNFAy..665y
>?olqebopfk?^qqibyKy?ord^oPqlkbpeb^o%26+5)/4+3&yyNFAy./--/y

>CfkaHrorkyKyC^iibkB^oqebkT^ooflo%30+3)/0+/&yyNFAy..65.y
>QebA^j^dbaGlrok^iyKy?^qqbobaGlrok^i%31+0).6+5&yyNFAy..653y
@QebA^j^dbaGlrok^iyNFAy..653yyKy@liib`qglrok^im^dbplkqebdolrka^olrka%31)/.&+Tebkvlre^sb5)`lj_fkbtfqeqebXFk`ljmibqbGlrok^iZyyRy02406y
@?olqebopfk?^qqibyNFAy./--/yyKyCfka^kahfiiqebOrkf`?^qqibDlibjp^olrka%31+3).6+6&y

QCfkaHrorkyKyHrork%32+4).4+4&yyNFAy..65.y
>O^fkfkdAltkAbpqor`qflkyKyHrork%32+4).4+4&yyNFAy..65/y
@O^fkfkdAltkAbpqor`qflkyNFAy..65/yyKyVlr`^kcfka_lriabop^q%34+-)./+.&)qeoltqebpbaltk_bilt^qqebat^osbp^q%36+.).1+2&yyRy02401y
QO^fkfkdAltkAbpqor`qflkyKyHrork%32+4).4+4&yyNFAy..65/y
>O^iivfkdqebQollmpyKyHrork%32+4).4+4&yyNFAy./-4-y
@O^iivfkdqebQollmpyNFAy./-4-yyKyRpbqebXPe^oalcqebB^oqeZlklkblcqebDofwwivEfiipDf^kqp%4-+.)4+2&)qebkhfiiqebat^ocqe^qpm^tkpyyRy03431y
QO^iivfkdqebQollmpyKyHrork%32+4).4+4&yyNFAy./-4-y
>Fkqlqeb?ob^`eyKyHrork%32+4).4+4&yyNFAy..652y

QQebA^j^dbaGlrok^iyKyQloqebkAbbmafd%26+5)/4+2&yyNFAy..653y
>QebOrkf`HbvpqlkbyKyQloqebkAbbmafd%26+5)/4+2&yyNFAy..655y
Q?olqebopfk?^qqibyKy?ord^oPqlkbpeb^o%26+5)/4+3&yyNFAy./--/y
>Rk`lsbofkdqebQrkkbipyKy?ord^oPqlkbpeb^o%26+5)/4+3&yyNFAy./--0y
@Rk`lsbofkdqebQrkkbipyNFAy./--0yyKy@eb`hb^`e_rfiafkdlrqpfabQeloJla^k+Kloqe%3/+4)/-+6&)Plrqe%30+2)/5+/&)B^pq%33+3)/1+0&y
@QebOrkf`HbvpqlkbyNFAy..655yyKyHfiifolkat^ocpfkpfabQeloJla^k^olrka%33+2).4+/&cloXOrkf`HbvpqlkbCo^djbkqpZy
QQebOrkf`HbvpqlkbyKyQloqebkAbbmafd%26+5)/4+2&yyNFAy..655y
>QebOrkf`Molmeb`fbpyKyQloqebkAbbmafd%26+5)/4+2&yyNFAy..660y
QRk`lsbofkdqebQrkkbipyKy?ord^oPqlkbpeb^o%26+5)/4+3&yyNFAy./--0y
>QebC^qblcLoilkayKy?ord^oPqlkbpeb^o%26+5)/4+3&yyNFAy./-.-y
QQebC^qblcLoilkayKyProsbvloLoilka%34+2).2+/&yyNFAy./-.-y
>Pqb^av^p^Ol`h<yKyProsbvloLoilka%34+2).2+/&yyNFAy./-.1y
HQeobpebopyNFAy./-.1yyNLyMloq^_ibPbfpjldo^me7.,.yyKyElmfkqebt^qbo^kahfiiqeobpebop%35+-).2+/&y
@QebOrkf`Molmeb`fbpyNFAy..660yyKyOb^ab^`elcqeborkf`mi^qbp+Qefoa%35+2).3+/&)Cfopq%35+6).1+2&)Pb`lka%4-+/).1+4&y
@Fkqlqeb?ob^`eyNFAy..652yyKyHfiiFolkQe^kb>odorj^qqebb^pqbkalcQeloJla^k%4-+2)./+6&y
@Pqb^av^p^Ol`h<yNFAy./-.1yyKyRpbqebXMloq^_ibPbfpjldo^meZofdeq^`olppqeb_ofadbcoljtebobvlrhfiiba>odorj%4-+4).0+1&)qebkq^ihqlqeb`lkplibqldbq^ob^afkdyyRy02504y

QFkqlqeb?ob^`eyNFAy..652yyKyHrork%32+4).4+4&y
>D^sol`hyKyHrork%32+4).4+4&yyNFAy./-5.y

QPqb^av^p^Ol`h<yKy?ord^oPqlkbpeb^o%26+5)/4+3&yyNFAy./-.1y
>@eb`hRmlkO^bd^oyKy?ord^oPqlkbpeb^o%26+5)/4+3&yyNFAy././5y
QQebOrkf`Molmeb`fbpyKyQloqebkAbbmafd%26+5)/4+2&yyNFAy..660y

QP^vEbiilqlJvIfqqibCofbkayKyE^ohlo%40+5)01+.&yyNFAy./.6-y
>Kf`bqlJb^qVlryKyE^ohlo%40+5)01+.&yyNFAy./..0y
>Qebo^mvyKyE^ohlo%40+5)01+.&yyNFAy./..1y
>FqQ^hbpDrqp++++yKyHo^w%40+6)01+.&yyNFAy./..3y

QD^sol`hyKyD^sol`h%46+4)00+4&yyNFAy./-5.y
>Orkbplc@ljmripflkyKyD^sol`h%46+4)00+4&yyNFAy./-60y
@>?b^olc^k>mmbqfqbyNFAy.//46yyKyRpbqebXCfpefkdKbqZlkqebXKloqebokP^ijlkZ^olrkaqebOrfkplcQbqevp%45+1)03+2&yyRy0421/y

@Orkbplc@ljmripflkyNFAy./-60yyKyHfii^iiclroat^ocpproolrkafkdqeborkbqlprjjlk?orklk%46+/)10+0&)Il`eif%41+6)03+6&)Hlod^k%4/+-)01+0&)Aros^i%34+4)/6+/&y
@FqQ^hbpDrqp++++yNFAy./..3yyKyEb^aaltkfkqlqebAo^hfi$gfkOrfkp%4.+1)/0+6&+Lmbkg^opfkqebcfopq_fdollj^ilkdqebt^iipy
@Slf`bpColjqebArpqyNFAy./-35yyKyAbbmbofkqlqeborfkp)vlr$iicfkaqebXAo^hh^ofQ^_ibqpZfkqeb`lokbolc^pfabollj%36+1).5+.&y
>Ark*a^*Ark*q^eyKyE^oofplkGlkbp%36+1).4+2&yyNFAy./-5/y

QArk*a^*Ark*q^eyKyE^ohlo%40+5)01+.&yyNFAy./-5/y
QFqQ^hbpDrqp++++yKyHo^w%40+6)01+.&yyNFAy./..3y
>Ao^h$^drri$pJ^iibqyKyHo^w%40+6)01+.&yyNFAy././-y

QOrkbplc@ljmripflkyKyD^sol`h%46+4)00+4&yyNFAy./-60y
>I^qbkqMltboyKyD^sol`h%46+4)00+4&yyNFAy./-61y

@I^qbkqMltboyNFAy./-61yyRy03454yyKyRpbqebXPe^oalcD^sol`hZ^qb^`elcqeb^k`fbkqpqlkbp)B^pq%45+5)06+6&)Plrqe%41+.)11+/&^kaKloqe%4.+/)06+4&y
Q>?b^olc^k>mmbqfqbyKyErdeDi^pp%36+.)1-+.&yyNFAy.//46y
@Ao^h$^drri$pJ^iibqyNFAy././-yyKyHfiiAo^h$^drri)ebm^qolipplrqelcqeborfkp%4/+5)0-+.&y

QAo^h$^drri$pJ^iibqyKyHo^w%40+6)01+.&yyNFAy././-y
>PbbVlrlkqebLqeboPfabyKyHo^w%40+6)01+.&yyNFAy././.y

QI^qbkqMltboyKyD^sol`h%46+4)00+4&yyNFAy./-61y
>Cobb^qI^pqyKyD^sol`h%46+4)00+4&yyNFAy./-66y
KDf^kqpyKyRpbXD^sol`h$pOrkb_ob^hboZlk^kvdf^kqpvlr`ljb^`olpp)fqtfiibfqeboj^hbqebjcofbkaivloklk*bifqbyyNFAy./-66y

@PbbVlrlkqebLqeboPfabyNFAy././.yyKyRpbqebX@e^odbaAo^hfi$gfkJ^iibqZ^qqebdlkdfkcolkqlcqebbkqo^k`bqlqeborfkp%4.+3)/1+3&yyRy03501y
QPbbVlrlkqebLqeboPfabyKyD^k$gl%36+2).6+2&yyNFAy././.y
>@efiiLrq)JlkyKyD^k$gl%36+2).6+2&yyNFAy./.04y
@@efiiLrq)JlkyNFAy./.04yyKyLmbkqeb`ebpqqldbqqebXPkltlcBqbok^iPirj_boZ)qebkq^ihD^k$gl%36+2).6+2&clo^obw+Rpbqebpkltqlcobbwbqebqoliip^kaillqqeb`lompbqebvorkqlyyRy03526y

Q@efiiLrq)JlkyKyHo^w%40+6)01+.&yyNFAy./.04y
>Gfk$^oo^h$pBkayKyHo^w%40+6)01+.&yyNFAy./.2/y
@Gfk$^oo^h$pBkayNFAy./.2/yyKyCfkaqeblccbofkdfkqebcfopqolljlcqeborfkp%4.+/.).6+32&+RpbqebXAo^hh^ofPmfofqArpqZlkfq)qebkeb^alrqpfabqlqebdlkd^kami^`bqeblccbofkdyyRy04-30y

@Qebo^mvyNFAy./..1yyKyHfiiqebqoliipproolrkafkdqeborfkp%4-+3)/4+0&y
@Slf`bpColjqebArpqyNFAy./-35yyKyQo^sbialtkqeborfkp^kado^_XAo^hh^ofQ^_ibqpZ^q%36+1).5+.&y
QSlf`bpColjqebArpqyNFAy./-35yyKyFj^dblcA^h^or%4.+4)/3+/&+Hfiiproolrkafkdqoliipqfiivlre^sb2XP^`obaJlglZy

@Kf`bqlJb^qVlryNFAy./..0yyRy03463yyKyHfiiArpheltiMoltibopbfqebo^qqeb`^sb%32+3)1/+2&lo^olrka%34+-)0-+4&^kaIlkdellcDo^wbop^q^_lrq%42+1)10+.&y
@Cobb^qI^pqyNFAy./-66yyRy03463yyKyRpbXD^sol`h$pOrkb_ob^hboZlkqebOrkbaDf^kqp^olrka%34)./&y

QQebo^mvyKyE^ohlo%40+5)01+.&yyNFAy./..1y
QKf`bqlJb^qVlryKyE^ohlo%40+5)01+.&yyNFAy./..0y
QGfk$^oo^h$pBkayKyHo^w%40+6)01+.&yyNFAy./.2/y
QCobb^qI^pqyKyD^sol`h%46+4)00+4&yyNFAy./-66y

Q@eb`hRmlkO^bd^oyKyO^bd^o?ob^h_olt%44+.)15+4&yyNFAy././5y
>QebMbocb`qMi^kyKyO^bd^o?ob^h_olt%44+.)15+4&yyNFAy././6y
>Qeb@^mqfsbMolpmb`qlopyKyJlrkq^fkbboHfif^k%44+-)15+2&yyNFAy./.5-y

@Qeb@^mqfsbMolpmb`qlopyNFAy./.5-yyKyHfiijl_p^qArk>odliclohbvp)qebklmbkb^`e`^db+D^kk%43+2)22+/&)Qlod^k%43+0)25+2&^jaS^o^k^%42+6)3.+.&y
@QebMbocb`qMi^kyNFAy././6yyRy03516yyKyHfiiFolkOrkb*Pjfqep^olrkaArk>odli%43+0)25+4&+Lk`bvlre^sb^iiqeobb`e^mqbop)rpblkbql`lj_fkbqebj+y

QQeb@^mqfsbMolpmb`qlopyKyJlrkq^fkbboHfif^k%44+-)15+2&yyNFAy./.5-y
>IllhfkdqebM^oqyKyJlrkq^fkbboHfif^k%44+-)15+2&yyNFAy./.50y
QQebMbocb`qMi^kyKyO^bd^o?ob^h_olt%44+.)15+4&yyNFAy././6y
>TevC^_of`^qbTebkVlr@^k>mmolmof^qb<yKyO^bd^o?ob^h_olt%44+.)15+4&yyNFAy./.0-y

@TevC^_of`^qbTebkVlr@^k>mmolmof^qb<yNFAy./.0-yyKyCfkaXT^oDlibjM^oqpZ^olrkaArk>odli%43+0)25+4&y
@IllhfkdqebM^oqyNFAy./.50yyKyHfii^kFolkOrkbLsbopbbo^olrkaArk>odli%43+0)25+4&y

QIllhfkdqebM^oqyKyJlrkq^fkbboHfif^k%44+-)15+2&yyNFAy./.50y
>@riqfs^qfkd^kFj^dbyKyJlrkq^fkbboHfif^k%44+-)15+2&yyNFAy./.51y
QTevC^_of`^qbTebkVlr@^k>mmolmof^qb<yKyO^bd^o?ob^h_olt%44+.)15+4&yyNFAy./.0-y
>TbE^sbqebMltboyKyO^bd^o?ob^h_olt%44+.)15+4&yyNFAy./.0.y

@TbE^sbqebMltboyNFAy./.0.yyKyHfiiOrkb*PjfqeAro^o%42+-)24+-&^kaOrkb*PjfqeH^qelok%43+5)26+0&fkqebqtl_rfiafkdpqebobyyRy04-12y
@@riqfs^qfkd^kFj^dbyNFAy./.51yyRy04-12yyKyHfiiat^ocp^olrkaArk>odli%43+0)25+4&^kaq^hbqebfomf`qrobprpfkdXHfif^k$p@^jbo^Zy

Q@riqfs^qfkd^kFj^dbyKyJlrkq^fkbboHfif^k%44+-)15+2&yyNFAy./.51y
>MrqlkVlro?bpqC^`bcloIlhbkyKyJlrkq^fkbboHfif^k%44+-)15+2&yyNFAy./.52y
QTbE^sbqebMltboyKyO^bd^o?ob^h_olt%44+.)15+4&yyNFAy./.0.y
>+++LoJ^v_bTbAlk$qyKyO^bd^o?ob^h_olt%44+.)15+4&yyNFAy./.05y

@MrqlkVlro?bpqC^`bcloIlhbkyNFAy./.52yyRy03603yyKyEb^aqlqebc^o_rfiafkdlkqebpb`lkaibsbi%5.+2)3-+0&^karpbqebXLsbopbboAfpdrfpbHfqZqlq^ihqlIlhbky
@+++LoJ^v_bTbAlk$qyNFAy./.05yyRy03603yyKyRpbqebXDlibj@lkqoliRkfqZ)prjjlkqebdlibj^kahfiibibjbkq^ipgrpqlrqpfablcArk>odli^olrka%40+2)3.+.&y

QMrqlkVlro?bpqC^`bcloIlhbkyKyJlrkq^fkbboHfif^k%44+-)15+2&yyNFAy./.52y
Q+++LoJ^v_bTbAlk$qyKyO^bd^o?ob^h_olt%44+.)15+4&yyNFAy./.05y
>QebFolkQe^kb^kaEfp>ksfiyKyO^bd^o?ob^h_olt%44+.)15+4&yyNFAy./.20y
>?i^`hlrqyKyO^bd^o?ob^h_olt%44+.)15+4&yyNFAy./.21y

@QebFolkQe^kb^kaEfp>ksfiyNFAy./.20yyRy03532yyKyBkqboqeb_rfiafkd^q%42+5)3/+.&+Dlaltkpq^fop^kaprjjlkqebdlibjql^qq^`hFolkQe^kbCrove^jjbo%43+1)30+4&+RpbqebBJMphfiicfopqqlafpormqqebpefbiay
@?i^`hlrqyNFAy./.21yyRy03602yyKyRpbXO^bd^o$pBumilpfsbpZlkqebmltbo`lobfkqeb`bkqboollj%43+/)30+2&lcqeb_rfiafkd^q%42+5)3/+.&y

QQebFolkQe^kb^kaEfp>ksfiyKyO^bd^o?ob^h_olt%44+.)15+4&yyNFAy./.20y
Q?i^`hlrqyKyO^bd^o?ob^h_olt%44+.)15+4&yyNFAy./.21y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
