DugisGuideViewer:RegisterGuide("Zul'Drak (76-78)", "Sholazar Basin (78-80)", "Alliance", "L", function()
return [[
AAA

>Ob^iil`^qfkdObplro`bpyKy@^mq^fkDov^kPqlrqj^kqib%26+2)/3+.&yyNFAy./44-yyWyDofwwivEfiipy
QOb^iil`^qfkdObplro`bpyKyPbodb^kqOf^kk^e%0/+.)41+2&yyNFAy./44-y

cIfdeq$p?ob^`eyKyA^kf`^P^fkq%0/+/)41+2&yyNFAy./526y

>QefpGrpqFk7CfobPqfiiElqyKyBiaboPe^j^kJlhv%0/+-)42+3&yyNFAy./526y
>QoliipFpDlkb@o^wvyKy@efbcO^db`i^t%0/+/)42+4&yyNFAy./53.y
>FkPb^o`eLc>kptbopyKy@orp^aboIloaI^kqfkd^%0/+.)42+5&yyNFAy./6-/y

QFkPb^o`eLc>kptbopyKyLoabopColjAo^hror%01+6)50+6&yyNFAy./6-/y
>LoabopColjAo^hroryKyLoabopColjAo^hror%01+6)50+6&yyNFAy./550y
@QefpGrpqFk7CfobPqfiiElqyNFAy./526yyRy1..0.yyKyRpbqebXO^db`i^tCfobBuqfkdrfpeboZqlmrqlrqqeberqp^qO^db`i^tAbk%0/+6)5/+.&y
@QoliipFpDlkb@o^wvyNFAy./53.yyRy1..3.yyKyQo^sbiqlO^db`i^tAbk%0/+6)5/+.&^kahfiiqebjl_pqldbqqebXAo^hrorIl`hLmbkboZkbbabaqlcobbqeb@^mqrobaO^db`i^ty

QQefpGrpqFk7CfobPqfiiElqyKyBiaboPe^j^kJlhv%0/+-)42+3&yyNFAy./526y
QQoliipFpDlkb@o^wvyKy@efbcO^db`i^t%0/+/)42+4&yyNFAy./53.y
QLoabopColjAo^hroryKy@orp^aboIloaI^kqfkd^%0/+.)42+5&yyNFAy./550y
>QebB_lkT^q`eyKy@orp^aboIloaI^kqfkd^%0/+.)42+5&yyNFAy./551y
>@orp^aboClot^oa@^jmyKy@orp^aboIloaI^kqfkd^%0/+.)42+5&yyNFAy./561y

Q@orp^aboClot^oa@^jmyKy@orp^aboJ^`Hbii^o%/2+0)31+-&yyNFAy./561y
>Qe^q$pTe^qCofbkap>obClo+++yKy@orp^aboJ^`Hbii^o%/2+0)31+-&yyNFAy./6-0y
>J^hfkdPljbqefkdLrqLcKlqefkdyKyBkdfkbboObba%/2+0)30+6&yyNFAy./6-.y

>>Dob^qPqloj>mmol^`ebpyKyDvjbo%.6+5)23+2&yyNFAy./6./y
>IfdeqTlk$qDo^kqJbSbkdb^k`byKyDboh%.4+3)24+3&yyNFAy./6-1y
KCfka?rooyNFAy./6-0yyNLy?rooclrka7.,.yyKy>_fqcroqeboqlqebtbpq%.2+3)26+2&y
@J^hfkdPljbqefkdLrqLcKlqefkdyNFAy./6-.yyKyQebXP`lrodbP`o^mJbq^iZfpp`^qqboba^olrkaQevoj$pBka^olrka%.4+3)3-+0&y
@Qe^q$pTe^qCofbkap>obClo+++yNFAy./6-0yyKyCfka@orp^aboA^od^qeqlqebkloqeb^pqfkqeborfkp^qA^od^qe$pAbjfpb%/1+4)2.+2&y

QQe^q$pTe^qCofbkap>obClo+++yKy@orp^aboJ^`Hbii^o%/2+0)31+-&yyNFAy./6-0y
QJ^hfkdPljbqefkdLrqLcKlqefkdyKyBkdfkbboObba%/2+0)30+6&yyNFAy./6-.y
Q>Dob^qPqloj>mmol^`ebpyKyBkdfkbboObba%/2+0)30+6&yyNFAy./6./y
>Dvjbo$pP^is^qflkyKyBkdfkbboObba%/2+0)30+6&yyNFAy./6.1y

@Dvjbo$pP^is^qflkyNFAy./6.1yyKyCfka^kahfii?^kpebbPlri`i^fjbopcil^qfkd^olrka%/0+-)3-+6&)^kaF`bqlr`ebaB^oqeo^dboptef`eproolrkaB_lkT^q`e%.1+.)40+5&y

QQebB_lkT^q`eyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./551y
cQebB_lkT^q`eyKy?^kbcifdeq%.1+.)40+3&yyNFAy./30-y
>Hf`hfk$K^pp^kaQ^hfk$J^kbpyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./30-y
@Hf`hfk$K^pp^kaQ^hfk$J^kbpyNFAy./30-yyRy05326yyKyHfiiTfqebobaQoliip^olrka%.6+5)4.+/&)qebkrpbXPqbc^k$pPqbbiQlba?llqZcloK^ppql`liib`qe^fop^jmibpy

>>kFksfq^qflk)lcPloqp+++yKyQefpfqbjXRkifsfkd@elhboZpq^oqpnrbpq*aolmmba_vTfqebobaQoliip^olrka%.5)4-&fcvlrob`bfsbaXTofqefkd@elhboZabibqbqebfqbj^kahfiiqoliiprkqfivlrdbqXRkifsfkd@elhboZyyNFAy./30.yyRy0533-y

QHf`hfk$K^pp^kaQ^hfk$J^kbpyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./30-y
Q>kFksfq^qflk)lcPloqp+++yKyPqbc^kS^ar%.1+.)40+5&yyNFAy./30.y
>Kb^oJfppyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./304y
@Kb^oJfppyNFAy./304yyKyQ^ihql?illaolpbA^qro^%.1+0)41+-&y
>Q^hfkd^Pq^kayKy?illaolpbA^qro^%.1+0)41+-&yyNFAy./462y
QKb^oJfppyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./304y
>Vlr@^kOrk)?rqVlr@^k$qEfabyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./3/6y
@Vlr@^kOrk)?rqVlr@^k$qEfabyNFAy./3/6yyKyHfiiMrqofa>_ljfk^qflkp^kaillqqebXDllbvDelriAolliZcoljqebdolrkalcqebObifnr^ovlc>dlkv%/.+/)40+3&y
QVlr@^kOrk)?rqVlr@^k$qEfabyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./3/6y
>AobppfkdAltkyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./315y

@AobppfkdAltkyNFAy./315yyRy05366yyKyEb^aqlqebObifnr^ovlc>dlkv%/.+/)40+3&^karpbqebXBkplo`biiba@elhboZ+Q^ihqlDofpqibdrq%.6+5)42+0&ql_rvqeb?fqqboMi^pj^y
>Cbbafk$A^DlliwyKyDofpqibdrq%.6+5)42+0&yyNFAy./32/yyRy05366y
@Cbbafk$A^DlliwyNFAy./32/yyRy054-.yyKyRpbqebX?ltbip^ka?o^fkp?ltiZkb^oqebAb`^vfkdDelripfkqebObifnr^ovlc>dlkv%/.+/)40+3&qlcbbaqebj+T^q`elrqcloqeb_ifdeqdr^oapy
QCbbafk$A^DlliwyKyDofpqibdrq%.6+5)42+0&yyNFAy./32/yyRy05366y

QAobppfkdAltkyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./315y
>Fkcfiqo^qfkdSliq^orpyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./33.y

QDvjbo$pP^is^qflkyKyBkdfkbboObba%/2+0)30+6&yyNFAy./6.1y
>LroLkivElmbyKyBkdfkbboObba%/2+0)30+6&yyNFAy./6.3y
@IfdeqTlk$qDo^kqJbSbkdb^k`byNFAy./6-1yyKyHfiiS^odrip^olrka%.5+2)23+6&y
QIfdeqTlk$qDo^kqJbSbkdb^k`byKyDboh%.4+3)24+3&yyNFAy./6-1y
@LroLkivElmbyNFAy./6.3yyKyRpbqebXGrj_lPb^clofrj@e^odbZlkqeb`^db%/-+-)23+3&yyRy1.2-4y
QLroLkivElmbyKyDvjbo%.6+5)23+2&yyNFAy./6.3y
>QebPqlojHfkd$pSbkdb^k`byKyDvjbo%.6+5)23+2&yyNFAy./6.6y
@QebPqlojHfkd$pSbkdb^k`byNFAy./6.6yyKyQ^ihqlDvjbo%.6+5)23+2&tebkvlr$obob^av+Eb^akloqeb^pqqlqebObifnr^ovlcM^fk%/5+3)13+5&^kahfii>id^oqeb@elpbk)qebkplrqeqlqebpq^fop%0.+3)3/+6&^kahfiiMofk`bK^s^ofrp+Qeovjtfiipm^tktebkqebmofk`bfpab^a+Fcvlrkbbaeb^iqe%vlr$iidbq^t^okfkd&cfka^pqloj`ilra)q^odbqfq)^karpbqebmf`hrm_rqqlklkvlro^`qflk_^o+Lk`bqebk^jbajl_p^obab^a)eb^aql@orp^aboClot^oa@^jm%/2+0)30+6&^kacfkfpelcc^kvp`lrodbvlrkbba+Fcvlr$obe^sfkdqolr_ibmf`hfkdrmpqloj`ilraprpbqeb^lbql`ib^oqeb^ob^cfopqy
QQebPqlojHfkd$pSbkdb^k`byKy@orp^aboJ^`Hbii^o%/2+0)31+-&yyNFAy./6.6y

>A^ohElofwlkyKyLsboiloaAo^hror%/4+/)13+.&+RpbqebXBkplo`biiba@elhboZ^qqebmi^qclojfkqeb`bkqboqldbqfkqlSliq^orpyyNFAy./331yyRy05366y
@A^ohElofwlkyNFAy./331yyRy05366yyKyQ^ihqlDlob_^dfkSliq^orp%/6+4)15+.&clo^ofaby
QA^ohElofwlkyKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./331yyRy05366y
QFkcfiqo^qfkdSliq^orpyKyPqbc^kS^ar%.1+.)40+5&)rpbXPqbc^k$pElokZlrqpfabSliq^orpyyNFAy./33.yyRy1.06-y
>PlC^o)Pl?^ayKyPqbc^kS^ar%.1+.)40+5&yyNFAy./336y
>FqOliipAltkefiiyKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./340yyRy05366y
@FqOliipAltkefiiyNFAy./340yyRy06.24yyKyRpbqebXP`bmqbolcPrddbpqflkZlk^?ifdeqDbfpqlrqpfabSliq^orp)pbkafqqlcbq`e^X?ifdeq@ovpq^iZ)obmb^q+Vlrtlk$qdbq`obafqqfiiqebdbfpqmloqprmqlSliq^orp)plalk$qdo^_^klqebolkb_bclobvlrdbq`obafq+J^hbprobvlralk$qe^sb^mbqloqebp`bmqbotlk$qtlohy
QFqOliipAltkefiiyKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./340yyRy05366y
@PlC^o)Pl?^ayNFAy./336yyRy06.21yyKyRpbqebXAfirqfkd>aafqfsbZlkqeb`^riaolkp^olrka^kvlcqebpbmlfkqp%/4+0)13+4&)%/6+/)14+.&)%0.+1)12+1&^ka%0.+3)11+/&y
QPlC^o)Pl?^ayKyPqbc^kS^ar%.1+.)40+5&yyNFAy./336yyRy1.06-y
>E^w^oalrpJ^qbof^ipyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./344y

>WbolQlibo^k`byKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./353yyRy05366y
@WbolQlibo^k`byNFAy./353yyRy06/-3yyKyRpbqebXP`bmqbolcBjmltbojbkqZlk^Pbos^kqlcAo^hrorkb^oqebmi^qcloj%0-+0)2-+5&^kae^sbqebqoliihfiiA^ojrh+Fcvlrcfdeqvlr$iiilpbvlroafpdrfpb)pllkivibqqebqolii^qq^`hy
QWbolQlibo^k`byKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./353y
@E^w^oalrpJ^qbof^ipyNFAy./344yyRy05366yyKyD^qebo`o^qbp^iilsboSli^qorp%/4+/)13+.&y
QE^w^oalrpJ^qbof^ipyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./344yyRy1.06-y
>P^_lq^dbyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./343y
>CrbicloqebCfobyKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./36-yyRy05366y
@CrbicloqebCfobyNFAy./36-yyRy06/05yyKyEb^aqlCofdfa?ob^`e%01+/)04+5&+RpbqebXP`bmqbolc@ljj^kaZlk^?il^qba>_ljfk^qflk+Pbkaefj^cqboqoliip)d^qeborm^pj^kv^pvlr`^k)qebk_iltefjrm)rpbqebpqljmqlhbbm^ddoly
@P^_lq^dbyNFAy./343yyRy06.32yyKyRpbqebXBumilpfsb@e^odbpZlkqebp`lrodbt^dlkp)qebpb^obqebpj^iibo`^oqplkqeblrqpfabp^olrkaSliq^orp%/4)13&y
QCrbicloqebCfobyKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./36-yyRy05366y
>Afp`ilprobyKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./4.-yyRy05366y
@Afp`ilprobyNFAy./4.-yyRy05366yyKyMloqrmqlqebrmmbo`e^j_borpfkdqebqbibmloq^_lsbqeblkbkloj^iivrpba)qebklmbkqeb`lccfk^kaq^hbqebqlroy
QAfp`ilprobyKyLsboiloaAo^hror%/4+/)13+.&yyNFAy./4.-yyRy05366y
QP^_lq^dbyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./343yyRy1.06-y
>?bqo^v^iyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./4.0y
@?bqo^v^iyNFAy./4.0yyRy06331yyKyEb^arm^kaq^ihqlLsboiloaAo^hror%/4+/)13+.&qlpq^oqqefp+Fq$p^c^foivb^pv_^qqib)alk$qtloov^_lrqvlroafpdrfpbtebkfqc^fip+RpbqebXP`bmqbolcAljfk^qflkZlklkblcqeb_fdqoliip^kapbkaefj^cqboAo^hror+Tefibebcfdeqp)t^q`ecloqeb`ovpq^ipAo^hrorqeoltp^kajlsb^t^vcoljqebj^pc^pq^pvlr`^k+Fcvlroqoliiafbp)rpbqebp`bmqbo^d^fky
RMloq_^`haltk)nrf`hivyRy10-26yyKyRpbXAo^hror$pI^pqTfpeZqlmloqaltk+Fqlkivi^pqp0jfkrqbp)pl_bnrf`h^_lrqfqyyNFAy./2-0y
Q?bqo^v^iyKyPqbc^kS^ar%.1+.)40+5&yyNFAy./4.0yyRy1.06-y

QQ^hfkd^Pq^kayKy@ljj^kaboC^ipq^^s%06+2)33+6&yyNFAy./462y
>AbcbkaqebPq^kayKy@ljj^kaboC^ipq^^s%06+2)33+6&yyNFAy./2-0y
>M^o^`erqbpcloqeb>odbkq@orp^abyKy@ljj^kaboC^ipq^^s%06+2)33+6&yyNFAy./41-y

cQeb>odbkqPq^kayKyDroof`%1.+2)31+2&yyNFAy./263y
eQeb>odbkqPq^kayKyJ^ofpp^Bsbot^q`e%1-+5)33+0&yyNFAy./263y

@M^o^`erqbpcloqeb>odbkq@orp^abyNFAy./41-yyRy063.2yyKyCfkaqeb>odbkqcfdeqboplrqfkqeb`lroqv^oa%04+4)32+6&^kaqlppqebjX@orp^aboM^o^`erqbpZy
@AbcbkaqebPq^kayNFAy./2-0yyKyEbimqeb>odbkqcfdeqbophfiiqebp`lrodblrqfkqeb`lroqv^oa%04+4)32+6&y

QAbcbkaqebPq^kayKy@ljj^kaboC^ipq^^s%06+2)33+6&yyNFAy./2-0y
QM^o^`erqbpcloqeb>odbkq@orp^abyKy@ljj^kaboC^ipq^^s%06+2)33+6&yyNFAy./41-y
>M^$QoliiyKy@ljj^kaboHrkw%1-+0)33+3&yyNFAy./263y
>KbtLoabopcloPbodb^kqPq^`he^jjboyKy@ljj^kaboHrkw%1-+0)33+3&yyNFAy./2-2y
>Qolr_ib^qqeb>iq^olcPpbo^qrpyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2-3y
>Qeb?ibppfkdlcWfj$>_t^yKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./232y

QQeb?ibppfkdlcWfj$>_t^yKyWfj$>_t^%03+4)4/+2&yyNFAy./232yyIy0522..-yyLy
QKbtLoabopcloPbodb^kqPq^`he^jjboyKyPbodb^kqPq^`he^jjbo%1-+2)15+/&yyNFAy./2-2y
>>odbkq@orp^ab)Tb>obIb^sfkdyKyPbodb^kqPq^`he^jjbo%1-+2)15+/&yyNFAy./2-1y
>JlmmfkdRmyKy@lomlo^iJ^d^%1-+1)15+/&yyNFAy./2-5y
@Qolr_ib^qqeb>iq^olcPpbo^qrpyNFAy./2-3yyKyPkb^h^olrkaqebbifqb^kabkqboqeb^iq^o_befkaefj%1-+1)05+6&y
@>odbkq@orp^ab)Tb>obIb^sfkdyNFAy./2-1yyKyQ^ihql.->odbkqPliafbop^olrka%1-+1)13+6&y
@JlmmfkdRmyNFAy./2-5yyKyHfiiqebCliiltboplcPpbo^qrp^olrka%1-+1)13+6&y
>Pqo^kdbJlglyKyQebfqbjXPqo^kdbJlglZpq^oqpnrbpq*aolmmba_vqoliip^olrka%1-)12&yyNFAy./2-4yyRy050/.y
Q>odbkq@orp^ab)Tb>obIb^sfkdyKyPbodb^kqPq^`he^jjbo%1-+2)15+/&yyNFAy./2-1y
QJlmmfkdRmyKy@lomlo^iJ^d^%1-+1)15+/&yyNFAy./2-5y

>I^_TlohyKy>i`ebjfpqCfkhibpqbfk%02+.)2/+/&yyNFAy./224y
@I^_TlohyNFAy./224yyKyXJraavJfobJ^ddlqZ)XTfqeboba?^qtfkdZ)^kaX@efiibaPbombkqJr`rpZ^obfkqebolljqlvlroibcq^pvlr`ljbfkql>i`ebjfpqCfkhbipqbfk$pollj%02)20&+QebX>j_bopbbaZfpfkqebolljqlqebofdeq%02)2.+2&y
QI^_TlohyKy>i`ebjfpqCfkhibpqbfk%02+.)2/+/&yyNFAy./224y
>PfmelkfkdqebPmfofqpyKy@^mq^fk>ok^qe%02+3)2/+/&yyNFAy./466y
@PfmelkfkdqebPmfofqpyNFAy./466yyKyIlpqAo^hh^ofPmfofqpclrka^qqebMlliplcWe^$Gfk%02+-)3-+6&+Vlr$ob^cqboqebkbrqo^ijl_pebob)klqqeb^ddobppfsblkbpy
QPfmelkfkdqebPmfofqpyKy@^mq^fk>ok^qe%02+3)2/+/&yyNFAy./466y
>Pql`hfkdqebPebisbpyKy@^mq^fk>ok^qe%02+3)2/+/&yyNFAy./3-6y
>@ifmmfkdQebfoTfkdpyKy@^mq^fk>ok^qe%02+3)2/+/&yyNFAy./3.-y
@@ifmmfkdQebfoTfkdpyNFAy./3.-yyKyHfiiWri$Ao^h?^qp^olrka%02+6)21+1&y
@Pql`hfkdqebPebisbpyNFAy./3-6yyKyHfiiQo^mallo@o^tibop^olrka%02+6)21+1&y
QPql`hfkdqebPebisbpyKy@^mq^fk>ok^qe%02+3)2/+/&yyNFAy./3-6y
Q@ifmmfkdQebfoTfkdpyKy@^mq^fk>ok^qe%02+3)2/+/&yyNFAy./3.-y

QQolr_ib^qqeb>iq^olcPpbo^qrpyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2-3y
QPqo^kdbJlglyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2-4y
>Mob`flrpBibjbkq^iCirfapyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2.-y
>QebAo^hh^ofAlKlqKbbaT^qboBibjbkq^ipyKyPr_*Ifbrqbk^kqG^u%1-+/)35+6&yyNFAy./23/y

>PljbqefkdcloqebM^fkyKy@^mq^fk?o^kalk%15+5)45+6&yyNFAy./264y

@Mob`flrpBibjbkq^iCirfapyNFAy./2.-yyKyTbpq^qqebAo^h$Plqo^Cfbiap%11+.)46+3&+Hfiibibjbkq^ip)tebkvlrdbq0ifkhprpbfqqlj^hb^qbqebo)qebkrpbqebqbqeboqlprjjlk^kbibjbkq^iqlhfiiy
@QebAo^hh^ofAlKlqKbbaT^qboBibjbkq^ipyNFAy./23/yyKyAo^hh^ofT^qbo?fkabop^obtbpq^qqebAo^h$Plqo^Cfbiap%11+.)46+3&y
@PljbqefkdcloqebM^fkyNFAy./264yyKy@liib`q2XJ^qrobT^qbo*MlmmvZtbpq^qqebAo^h$Plqo^Cfbiap%11+.)46+3&y

QPljbqefkdcloqebM^fkyKy@^mq^fk?o^kalk%15+5)45+6&yyNFAy./264y

>QeoltfkdAltkyKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./265y
>Ib^sbKlLkb?befkayKyAo+Oldbop%25+3)4/+2&yyNFAy./2./y

@QeoltfkdAltkyNFAy./265yyRy05241yyKyGrpqqlqebkloqetbpq%21+5)4.+-&+Cfkaqebifqqibpfkhelibp^kaqlppvlroXEfdeFjm^`qDobk^abZfkfqy
@Ib^sbKlLkb?befkayNFAy./2./yyRy0500-yyKyCfka@orp^aboGlk^qe^k%2-+4)36+6&)@orp^aboGlpbmefkb%16+1)41+4&^ka@orp^aboI^jllc%20+3)42+-&+RpbqebX@orp^abo$p?^ka^dbZlkqebj^kaq^hbqebj_^`hlkb^q^qfjb)vlr`^kjlrkqrmcloqefpy
QIb^sbKlLkb?befkayKyAo+Oldbop%25+3)4/+2&yyNFAy./2./y
QQeoltfkdAltkyKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./265y
>@l`llkbayKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./3-3y
>Ab^qeqlqebKb`olj^dfyKyPbodb^kqJllkpe^oa%25+.)4/+.&yyNFAy./22/y
>PhfjjboPmfkkbobqpyKyPmb`f^ifpq@ldtebbi%25+/)4/+.&yyNFAy./220y

@@l`llkbayNFAy./3-3yyKyGrpqqlqebkloqetbpq%21+5)42+2&)^qq^`hqebKbor_f^k@l`llkpqllmbkqebj)vlrtfiidbqbfqebo^cofbkaivloelpqfibjl_y
@PhfjjboPmfkkbobqpyNFAy./220yyKyHfiiE^qe$^oPhfjjbo^qHlio^j^p%24+-)45+5&y
@Ab^qeqlqebKb`olj^dfyNFAy./22/yyKyE^qe$^oKb`olj^drp^ob_bpqclrkafkqebc^iibkwfddro^q^q%3-+/)42+2&y

Q@l`llkbayKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./3-3y
QAb^qeqlqebKb`olj^dfyKyPbodb^kqJllkpe^oa%25+.)4/+.&yyNFAy./22/y
>J^i^pqeb@loormqboyKyPbodb^kqJllkpe^oa%25+.)4/+.&yyNFAy./221y
>MrobBsfiyKy@^mq^fkOrmboq%25+.)4/+2&yyNFAy./251y
QPhfjjboPmfkkbobqpyKyPmb`f^ifpq@ldtebbi%25+/)4/+.&yyNFAy./220y
>@o^pebaPmo^vboyKyPmb`f^ifpq@ldtebbi%25+/)4/+.&yyNFAy./250y
@@o^pebaPmo^vboyNFAy./250yyKyPlrqetbpq)kb^o@^mq^fk?o^kalk$p`^jm%15+6)42+2&y
Q@o^pebaPmo^vboyKyPmb`f^ifpq@ldtebbi%25+/)4/+.&yyNFAy./250y
>>Q^kdibaPhbfkyKyPmb`f^ifpq@ldtebbi%25+/)4/+.&yyNFAy./222y
@>Q^kdibaPhbfkyNFAy./222yyRy052.2yyKyRpbqebXQ^kdibaPhbfkQeoltboZlkqebMi^drbPmo^vbop^olrka%23)5-&y
@MrobBsfiyNFAy./251yyKyFkpfabHlio^j^p%3.+0)45+4&+Illhclodobbkpqlkbp^olrkaqebcillop^kat^iipy
@J^i^pqeb@loormqboyNFAy./221yyKyI^_biba^pDolrm)_rqfpplil^_ib+Eb^armqebpq^opkb^oqebbkqo^k`b%3-+5)5-+0&)J^i^pqeb@loormqbofp^qqebsbovqlmy

Q>Q^kdibaPhbfkyKyPmb`f^ifpq@ldtebbi%25+/)4/+.&yyNFAy./222y
QJ^i^pqeb@loormqboyKyPbodb^kqJllkpe^oa%25+.)4/+.&yyNFAy./221y

QQebAo^hh^ofAlKlqKbbaT^qboBibjbkq^ipyKyPr_*Ifbrqbk^kqG^u%1-+/)35+6&yyNFAy./23/y
QMrobBsfiyKyBfqofdd%1-+5)33+4&yyNFAy./251y
QMob`flrpBibjbkq^iCirfapyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2.-y
>JrpeolljJfuboyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2.1y
>DirqqlklrpIrohbopyKy>mmobkqf`bMbpqibmlq%1.+0)32+.&yyNFAy./2/4y

>@ob^qrob@ljcloqpyKy@^mq^fkDolkabi%15+.)30+5&yyNFAy./266y
@DirqqlklrpIrohbopyNFAy./2/4yyRy0505-yyKyMf`hrm/2XWri$Ao^hO^qpZ)qeolt2o^qp^qb^`e_^pfifphqlm^`fcvqebj^ka`liib`qqebX?^pfifph@ovpq^ipZqe^qvlrkbba%11)3/&y
@JrpeolljJfuboyNFAy./2.1yyKy@liib`q.-XJraaib`^mCrkdrpZclrka^ii^olrkaqebt^qbop^q%11+5)3/+4&y
@@ob^qrob@ljcloqpyNFAy./266yyKy@liib`q/-mfb`bplcXAb^aQeloktllaZclrka^ii^olrkaqebt^qbop^q%11+5)3/+4&y
Q@ob^qrob@ljcloqpyKy@^mq^fkDolkabi%15+.)30+5&yyNFAy./266y

QJrpeolljJfuboyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2.1y
>QllJr`elc^DllaQefkdyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2.3y
QM^$QoliiyKy@ljj^kaboHrkw%1-+0)33+3&yyNFAy./263y
@QllJr`elc^DllaQefkdyNFAy./2.3yyRy0500/yyKyKloqe^qqeb>iq^olcPpbo^qrp%1-+3)10+5&+QeoltqebXJlafcfbaJlglZ^qqebMolmebqlcPpbo^qrp^kahfiiJraaibaMolmebqlcPpbo^qrpy
QDirqqlklrpIrohbopyKy>i`ebjfpqCfkhibpqbfk%02+.)2/+/&yyNFAy./2/4y
QQllJr`elc^DllaQefkdyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./2.3y
>QlqebTfq`eAl`qloyKyEbuuboR_rkdl%1-+3)32+3&yyNFAy./3/0y

QQlqebTfq`eAl`qloyKyTfq`eAl`qloHercr%26+2)25+-&yyNFAy./3/0y
>?ob^hfkdQeolrdeGfk$>i^fyKyTfq`eAl`qloHercr%26+2)25+-&yyNFAy./3/4y
>Qeb?ibppfkdlcWfj$Qlod^yKyTfq`eAl`qloHercr%26+2)25+-&yyNFAy./3.2y
QQeb?ibppfkdlcWfj$Qlod^yKyWfj$Qlod^%26+2)24+/&yyNFAy./3.2y
>QebIb^abop^qGfk$>i^fyKyP`^imbo>erk^b%26+/)23+0&yyNFAy./3//y

cWfj$Qlod^yKyJ^^h^%3-+-)23+5&yyNFAy./3/5y
eWfj$Qlod^yKyM^k$v^%26+0)24+0&yyNFAy./3/5y

@?ob^hfkdQeolrdeGfk$>i^fyNFAy./3/4yyKyAfpqro_b^`elcqebMromib%24+2)3.+4&)Oba%25+//)3/+/&)?irb%24+/)32+0&^kaDobbk%23+/)31+/&`^riaolkpy
@QebIb^abop^qGfk$>i^fyNFAy./3//yyKyHfiiqoliip^olrkaqeb^ob^qlpm^tk@eril%23+3)32+0&)D^t^kfi%25+/)3/+.&^kaHrqr_b$p^%24+0)30+2&y

Q?ob^hfkdQeolrdeGfk$>i^fyKyTfq`eAl`qloHercr%26+2)25+-&yyNFAy./3/4y
>QlPmb^hTfqeE^o$hl^yKyTfq`eAl`qloHercr%26+2)25+-&yyNFAy./3/5y
>Obif`plcqebPkltIblm^oaDlaabppyKy@eolkf`iboQl$hfkf%26+6)24+6&yyNFAy./302y
QQebIb^abop^qGfk$>i^fyKyP`^imbo>erk^b%26+/)23+0&yyNFAy./3//y

QQlPmb^hTfqeE^o$hl^yKyE^o$hl^%30+4)4-+0&yyNFAy./3/5y
>?rqCfopqJvLccpmofkdyKyE^o$hl^%30+4)4-+0&yyNFAy./30/y
@?rqCfopqJvLccpmofkdyNFAy./30/yyRy05343yyKyHfiiqeb@ropbaLccpmofkdlcE^o$hl^^olrka%30+.)33+5&^karpbqebXTefphbolcE^o$hl^Zlkqebjy
@Obif`plcqebPkltIblm^oaDlaabppyNFAy./302yyKyXE^o$hl^kObif`Z^obclrkapmob^aqeolrdelrqqeb>iq^o^olrka%30+.)33+5&y
Q?rqCfopqJvLccpmofkdyKyE^o$hl^%30+4)4-+0&yyNFAy./30/y
>PmfofqlcOerklhyKyE^o$hl^%30+4)4-+0&yyNFAy./31/y

QObif`plcqebPkltIblm^oaDlaabppyKy@eolkf`iboQl$hfkf%26+6)24+6&yyNFAy./302y
>MirkabofkdQebfoLtkyKy@eolkf`iboQl$hfkf%26+6)24+6&yyNFAy./32-y
>Pb^ifkdqebOfcqpyKyP`^imbo>erk^b%26+/)23+0&yyNFAy./31-y
>QebColwbkB^oqeyKyBibjbkq*Q^jboA^dla^%26+2)23+2&yyNFAy./306y
>Qeb?ibppfkdlcWfj$OerhyKyTfq`eAl`qloHercr%26+2)25+-&yyNFAy./322y

QQeb?ibppfkdlcWfj$OerhyKyWfj$Oerh%26+4)11+1&yyNFAy./322y

QPmfofqlcOerklhyKyPmfofqlcOerklh%20+2)06+-&yyNFAy./31/y
>JvMolmebq)JvBkbjvyKyPmfofqlcOerklh%20+2)06+-&yyNFAy./313y
@JvMolmebq)JvBkbjvyNFAy./313yyKyHfiiMolmebqlcOerklhfkqebi^hb%21+.)14+0&y
QJvMolmebq)JvBkbjvyKyPmfofqlcOerklh%20+2)06+-&yyNFAy./313y
>>kBkaqlqebPrccbofkdyKyPmfofqlcOerklh%20+2)06+-&yyNFAy./314y
@>kBkaqlqebPrccbofkdyNFAy./314yyRy05363yyKyHfiiOerklh$pQlojbkqlo^q%20+2)02+5&)rpbqebXQlojbkqlo$pFk`bkpbZebaolmpqebkhfiiOerklhy
Q>kBkaqlqebPrccbofkdyKyPmfofqlcOerklh%20+2)06+-&yyNFAy./314y
>?^`hqlE^o$hl^yKyPmfofqlcOerklh%20+2)06+-&yyNFAy./320y

@MirkabofkdQebfoLtkyNFAy./32-yyKyHfiiMofbpqlcOerklh^olrka%20+3)06+/&y
@Pb^ifkdqebOfcqpyNFAy./31-yyKy>qq^`hqebofcqpqlqebplrqe%2.+-)11+6&y
@QebColwbkB^oqeyNFAy./306yyKyHfiiColwbkB^oqe^olrkaqebi^hb^q%2.+-)11+6&ql`liib`q4XBppbk`bplcqebColwbkB^oqeZy

QMirkabofkdQebfoLtkyKy@eolkf`iboQl$hfkf%26+6)24+6&yyNFAy./32-y
QQebColwbkB^oqeyKyBibjbkq*Q^jboA^dla^%26+2)23+2&yyNFAy./306y
QPb^ifkdqebOfcqpyKyP`^imbo>erk^b%26+/)23+0&yyNFAy./31-y
>P`^impyKyP`^imbo>erk^b%26+/)23+0&yyNFAy./326y
>?ofkdfkdAltkEb_$GfkyKyBibjbkq*Q^jboA^dla^%26+2)23+2&yyNFAy./33/y

Q?^`hqlE^o$hl^yKyE^o$hl^%30+4)4-+0&yyNFAy./320y
>FPbkpb^Afpqro_^k`byKyE^o$hl^%30+4)4-+0&yyNFAy./332y
@FPbkpb^Afpqro_^k`byNFAy./332yyKyQ^ihqlE^o$hl^%30+4)4-+0&^kavlr$ii_bpbkqlk^peloqqofm^ka_^`hy
QFPbkpb^Afpqro_^k`byKyE^o$hl^%30+4)4-+0&yyNFAy./332y
>Mobm^o^qflkpcloqebRkabotloiayKyE^o$hl^%30+4)4-+0&yyNFAy./333y
@Mobm^o^qflkpcloqebRkabotloiayNFAy./333yyKyHfiiqoliip^olrkaqeb^iq^o%30+/)4-+4&y
QMobm^o^qflkpcloqebRkabotloiayKyE^o$hl^%30+4)4-+0&yyNFAy./333y
>PbbhqebTfkaPbombkqDlaabppyKyE^o$hl^%30+4)4-+0&yyNFAy./334y
QPbbhqebTfkaPbombkqDlaabppyKyNrbqw$irk$pPmfofq%42+0)25+3&yyNFAy./334y
>PbqqfkdqebPq^dbyKyNrbqw$irk$pPmfofq%42+0)25+3&yyNFAy./34/y
@PbqqfkdqebPq^dbyNFAy./34/yyKyIllqqebcil^qfkd`ovpq^ipkb^oqeb^iqbo^olrka%40)25&y
QPbqqfkdqebPq^dbyKyNrbqw$irk$pPmfofq%42+0)25+3&yyNFAy./34/y
>Clrka^qflkcloObsbkdbyKyNrbqw$irk$pPmfofq%42+0)25+3&yyNFAy./335y
@Clrka^qflkcloObsbkdbyNFAy./335yyKyHfiiqoliipkb^oqebplriclkqp+Qebpb^ob_fdao^dlkeb^apq^qrbp^iilsbo%40+/)25+3&y
QClrka^qflkcloObsbkdbyKyNrbqw$irk$pPmfofq%42+0)25+3&yyNFAy./335y
>EbiiE^qe^CrovyKyNrbqw$irk$pPmfofq%42+0)25+3&yyNFAy./341y
@EbiiE^qe^CrovyNFAy./341yyRy06.25yyKyRpbXNrbqw$irk$pEbuufkdPqf`hZlk)qebkhfii)Qr^*Qr^%40+6)3-+/&)Jr$crkr%41+0)24+4&)^kaE^tfkkf%43+2)21+2&y
QEbiiE^qe^CrovyKyNrbqw$irk$pPmfofq%42+0)25+3&yyNFAy./341y
>LkbI^pqQefkdyKyNrbqw$irk$pPmfofq%42+0)25+3&yyNFAy./342y
QLkbI^pqQefkdyKyE^o$hl^%30+4)4-+0&yyNFAy./342y
>?illalc^Ab^aDlayKyE^o$hl^%30+4)4-+0&yyNFAy./351y
@P`^impyNFAy./326yyRy0540.yyKyKloqe^qEb_$Ao^hh^o%31+.)2/+6&+HfiiqoliipqebkrpbX>erk^b$pHkfcbZy
@?ofkdfkdAltkEb_$GfkyNFAy./33/yyRy06-1.yyKyLsbo^qqeb_rfiafkd%31+.)2/+6&)_b^qlkqebaorj+Tebkebi^kap)rpbqebX?^qKbqZlkefp_^qcfopq)qebkhfiiefjy
@?illalc^Ab^aDlayNFAy./351yyKyHfii?illalcJ^j$qlqe^qJ^j$qlqe@o^qbo%42+0)16+2&y
Q?illalc^Ab^aDlayKyE^o$hl^%30+4)4-+0&yyNFAy./351y
>VlrOb^mTe^qVlrPltyKyE^o$hl^%30+4)4-+0&yyNFAy./352y
@VlrOb^mTe^qVlrPltyNFAy./352yyRy06.54yyKy?^`h^qqeb>iq^olcNrbqw$irk%42+0)25+3&+RpbXNrbqw$irk$pOfqr^iZ^kahfiiqebmolmebqy

QVlrOb^mTe^qVlrPltyKyTfq`eAl`qloHercr%26+2)25+-&yyNFAy./352y
Q?ofkdfkdAltkEb_$GfkyKyBibjbkq*Q^jboA^dla^%26+2)23+2&yyNFAy./33/y
QP`^impyKyP`^imbo>erk^b%26+/)23+0&yyNFAy./326y
>TllivGrpqf`byKyP`^imbo>erk^b%26+/)23+0&yyNFAy./4-4y
>Bk`e^kqbaQfhfT^ooflopyKyBibjbkq*Q^jboA^dla^%26+2)23+2&yyNFAy./4-5y
>QebHbvlcT^oiloaWli$J^wyKyE^o$hl^%3-+.)24+4&yyNFAy./4./y
>Ebuba@^`ebpyKy@eolkf`iboQl$hfkf%26+6)24+6&yyNFAy./4-6y

@QebHbvlcT^oiloaWli$J^wyNFAy./4./yyRy060.1yyKyKloqeb^pq^qWli$J^wPqolkdelia+HfiiQfof%30+6)04+/&)Aobh$J^w%35+/)02+2&^kaV^o^%34+6)0/+6&cloqebfofqbjp+Qebkeb^armqlqebqlm%33+/)00+4&)rpblkblcqebfqbjpql`lj_fkbqebj)^karpbqebkbtfqbjqlpq^oqqebcfdeq+y
@Ebuba@^`ebpyNFAy./4-6yyRy060-2yyKyIllqqeb_^phbqp^olrkaWli$J^wPqolkdelia%3/+6)03+.&+?b`^robcri^_lrqqeb`ropbp+Qebqfhfpaolmfqbjpqlobjlsbqeb`ropbpy
@Bk`e^kqbaQfhfT^ooflopyNFAy./4-5yyKyHfiiqebBk`e^kqbaQfhfT^ooflop^olrkaWli$J^wPqolkdelia%3/+6)03+.&y
@TllivGrpqf`byNFAy./4-4yyRy06/35yyKyPlrqeb^pq^qqeb>iq^olcJ^j$qlqe%36+4)10+-&+RpbqebXJba^iiflklcJ^j$qlqeZlk^j^jjlqe)elmlk)^karpbqebj^jjlqeqlhfiikb^o_vqoliipy

QTllivGrpqf`byKyP`^imbo>erk^b%26+/)23+0&yyNFAy./4-4y
QBk`e^kqbaQfhfT^ooflopyKyBibjbkq*Q^jboA^dla^%26+2)23+2&yyNFAy./4-5y
QQebHbvlcT^oiloaWli$J^wyKyE^o$hl^%3-+.)24+4&yyNFAy./4./y
>O^jm^dbyKyE^o$hl^%3-+.)24+4&yyNFAy./4/.y
QEbuba@^`ebpyKy@eolkf`iboQl$hfkf%26+6)24+6&yyNFAy./4-6y
>Grpq@eb`hfk$yKy@eolkf`iboQl$hfkf%26+6)24+6&yyNFAy.0-66y

@O^jm^dbyNFAy./4/.yyKyKloqeb^pq)fkcolkqlcDrkao^h%46+-)/1+0&+RpbqebXHbvlcT^oiloaWli$J^wZqlrkil`hb^`elc>h^if$p`e^fkpyyRy06101y
QGrpq@eb`hfk$yKy@eolkf`ibo?^e$Hfkf%4-+-)/.+-&yyNFAy.0-66y

cDrkao^hyKyO^c^b%4-+2)/0+/&y
CWfj$Qlod^yKyO^c^b%4-+2)/0+/&qlJ^^h^%3-+-)23+5&y

QO^jm^dbyKyTfq`eAl`qloHercr%26+2)25+-&yyNFAy./4/.y
KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
