DugisGuideViewer:RegisterGuide("Icecrown (78-80)", nil, "Alliance", "L", function()
return [[
AAA

CQeb>odbkqS^kdr^oayKyCivqlQeb>odbkqS^kdr^oaFkF`b`oltk^q%54)42&yyNFAy.0-03y
>Elklo>_lsb>iiBipbyKyEfdeiloaQfoflkCloaofkd%54+2)42+6&yyNFAy.0-03y
QElklo>_lsb>iiBipbyKy@orp^ab@ljj^kaboBkq^of%54+.)42+6&yyNFAy.0-03y
>P`lrodbQ^`qf`pyKy@orp^ab@ljj^kaboBkq^of%54+.)42+6&yyNFAy.0--5y
>@rofkdQebFk`ro^_ibyKyC^qeboDrpq^s%53+6)43+3&yyNFAy.0-1-y
>AbcbkafkdQebS^kdr^oayKy@orp^aboIloaA^iclop%53+.)42+5&yyNFAy.0-06y

@AbcbkafkdQebS^kdr^oayKyHfii.2ClodlqqbkAbmqepKbor_f^kp^olrka%51+2)42+1&yyNFAy.0-06y
@@rofkdQebFk`ro^_ibyKy@liib`q.-uXClodlqqbkAbmqepSbkljP^`ZcoljqebPmfabop^olrka%51+2)42+1&yyNFAy.0-1-y
@P`lrodbQ^`qf`pyKyCobb5Tb__ba@orp^abop^olrka%50)4.&yyNFAy.0--5y
QP`lrodbQ^`qf`pyKy@orp^ab@ljj^kaboBkq^of%54+.)42+6&yyNFAy.0--5y

Q@rofkdQebFk`ro^_ibyKyC^qeboDrpq^s%53+6)43+3&yyNFAy.0-1-y
QAbcbkafkdQebS^kdr^oayKy@orp^aboIloaA^iclop%53+.)42+5&yyNFAy.0-06y
>FcQebob>obProsfslop+++yKy@orp^ab@ljj^kaboBkq^of%54+.)42+6&yyNFAy.0-11y
QFcQebob>obProsfslop+++yKyMbkrj_ofrp%54)46&yyNFAy.0-11y
>FkqlQebTfiaDobbkVlkaboyKyMbkrj_ofrp%54)46&yyNFAy.0-12y
@FkqlQebTfiaDobbkVlkaboyKyJlrkq^phvq^ilkfkcolkqlcvlr^kadlkloqe*tbpqqlP`lrodbelijb%46)33&^kado^_^@^mqroba@orp^abo^kaqebk_ofkdefj_^`hqlqebS^kdr^oa%^qqeb?lkcfobtebob^iiqebqbkqp^ob^q&)vlr`^klkiv`^oovlkb^q^qfjb)plvlrtfiie^sbqlj^hb0qofmp+yyNFAy.0-12y
QFkqlQebTfiaDobbkVlkaboyKyEfdeiloaQfoflkCloaofkd%54+2)42+6&yyNFAy.0-12y
>>@liaColkq>mmol^`ebpyKyEfdeiloaQfoflkCloaofkd%54+2)42+6&yyNFAy.0-4-y
Q>@liaColkq>mmol^`ebpyKyPfbdbj^pqboCbwwfh%52+4)43&yyNFAy.0-4-y
>QebI^pqIfkbLcAbcbkpbyKyPfbdbj^pqboCbwwfh%52+4)43&yyNFAy.0-53y
@QebI^pqIfkbLcAbcbkpbyKyRpblklcqeb>odbkq@^kklk%52+6)34+4&^kahfii.--p`lrodbpyyNFAy.0-53y
QQebI^pqIfkbLcAbcbkpbyKyPfbdbj^pqboCbwwfh%52+4)43&yyNFAy.0-53y
>Lk`bJlobRkqlQeb?ob^`e)EbolyKyEfdeiloaQfoflkCloaofkd%54+2)42+6&yyNFAy.0.-1y

QLk`bJlobRkqlQeb?ob^`e)EbolyKyQebB_lkT^q`ebo%50+.)4/+6&yyNFAy.0.-1y
>QebMrodfkdLcP`lrodbelijbyKyQebB_lkT^q`ebo%50+.)4/+6&yyNFAy.0..5y
>QebP`lrodbpqlkbyKyQebB_lkT^q`ebo%50+.)4/+6&yyNFAy.0.//y
>QebPqlkbQe^qPq^oqba>ObslirqflkyKy@orp^ab>o`efqb`qPfi^p%50+.)40&yyNFAy.0.0-y
>Fq@lriaHfiiRp>iiyKy@orp^abBkdfkbboPmfqwm^qof`h%50)40&yyNFAy.0.02y
>QebObpqibppAb^ayKyC^qeboDrpq^s%5/+6)4/+5&yyNFAy.0..-y

@Fq@lriaHfiiRp>iiyKyObqofbsb5mfb`bplcX@ovpq^iifwbaBkbodvZaolmmba_vqebRk_lrkaKM@pfk@ovpq^iplkdClobpq%32)31&yyNFAy.0.02yyWy@ovpq^iplkdClobpqy
@QebPqlkbQe^qPq^oqba>ObslirqflkyKyObqofbsb.-Qorkhplc@ovpq^iifkbEb^oqtlla%32)32&^ka.-mfb`bplc>k`fbkqBisbkJ^plkov%53)3.&yyNFAy.0.0-yyWy@ovpq^iplkdClobpqy
QFq@lriaHfiiRp>iiyKy@orp^abBkdfkbboPmfqwm^qof`h%50)40&yyNFAy.0.02y
QQebPqlkbQe^qPq^oqba>ObslirqflkyKy@orp^ab>o`efqb`qPfi^p%50+.)40&yyNFAy.0.0-y

@QebMrodfkdLcP`lrodbelijbyKyHfiiqebKM@p^olrka%44)35&^ka%46)31&rpbqebXElivT^qboZlkqeb`lompbpyyRy10.20yyNFAy.0..5y
@QebObpqibppAb^ayKyHfiiqebOb^kfj^qba@orp^abop%44)32&^karpbqebXElivT^qboZlkqeb`lompbpyyRy10.20yyNFAy.0..-y
@QebP`lrodbpqlkbyKyVlr`^k`ljmibqbqefp^q@orp^aboplcSfoqrb^q%5/+5)4.+2&^kagrpqefqqebjlkpqbop^cbtqfjbp^kaibqqebKM@pebimvlrhfiiqebjqebkillqqebXP`lrodbpqlkbZyyNFAy.0.//y

QQebMrodfkdLcP`lrodbelijbyKyQebB_lkT^q`ebo%50+.)4/+6&yyNFAy.0..5y
QQebObpqibppAb^ayKyC^qeboDrpq^s%5/+6)4/+5&yyNFAy.0..-y
QQebP`lrodbpqlkbyKyQebB_lkT^q`ebo%50+.)4/+6&yyNFAy.0.//y

>Qeb>foPq^kapPqfiiyKyQebB_lkT^q`ebo%50+.)4/+6&yyNFAy.0./2y
@Qeb>foPq^kapPqfiiyKyCfkaqebKM@^kapq^ka^_lrq.-v^oap^t^vcoljqebj^karpbqebXT^oEloklc>`eborpZ)pq^v^ifsbrkqfiqebAb^qehkfdeq^oofsbp+P^io^k^u7%44)3.&)Rkabohfkd7%43)20&)EfdeMofbpqV^qe$^jlk7%46)3-&yyRy10/-3yyNFAy.0./2y

QQeb>foPq^kapPqfiiyKyQebB_lkT^q`ebo%50+.)4/+6&yyNFAy.0./2y
>FkqlQebColwbkEb^oqLcKloqeobkayKyC^qeboDrpq^s%5/+6)4/+5&yyNFAy.0.06y
QFkqlQebColwbkEb^oqLcKloqeobkayKyEfdeiloaQfoflkCloaofkd%53)42+5&yyNFAy.0.06y
>Qeb?^qqibClo@orp^abop$Mfkk^`ibyKyEfdeiloaQfoflkCloaofkd%53)42+5&yyNFAy.0.1.y
@Qeb?^qqibClo@orp^abop$Mfkk^`ibyKyDlql@orp^abop$Mfkk^`ib%5-)4/&^karpbqebX?ibppba?^kkbolcqeb@orp^abZ^qlmqebMfiblc@orp^aboPhriip+Abcbkaqeb_^kkbo^d^fkpqP`lrodb^qq^`hrkqfiqebi^ka^qlmqebmfkk^`ibfpp^k`qfcfbayyRy10/10yyNFAy.0.1.y
QQeb?^qqibClo@orp^abop$Mfkk^`ibyKyC^qeboDrpq^s%5/+6)4/+5&yyNFAy.0.1.y
>Qeb@orp^abop$Mfkk^`ibyKyC^qeboDrpq^s%5/+6)4/+5&yyNFAy.0.24y
QQeb@orp^abop$Mfkk^`ibyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyNFAy.0.24y
>>Q^iblcS^iloyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyNFAy.0-35y
>QebPhv_ob^hboyKyJ^ope^iFs^ifrp%46+2)4/+5&yyNFAy.0//2y
Q>Q^iblcS^iloyKy@orp^abo?ofabk_o^a%46+5)0-+6&yyNFAy.0-35y
>>EbolObj^fkpyKy@orp^abo?ofabk_o^a%46+5)0-+6&yyNFAy.0-4/y
Q>EbolObj^fkpyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyNFAy.0-4/y
>QebHbbmbo$pC^sloyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyNFAy.0-40y
@DbqMloq^i+++yKyQ^ihql>o`eAorfaIfiif^kao^%54)44&^kaobnrbpq^Jllkdi^abmloq^iyyNFAy.0-40y
QQebHbbmbo$pC^sloyKyHbbmboObjrilp%03)1.+2&yyNFAy.0-40yyWyJllkdi^aby
>ElmbTfqefkqebBjbo^iaKfdeqj^obyNFAy.0-41yyKyHbbmboObjrilp%03)1.+2&yyWyJllkdi^aby
@ElmbTfqefkqebBjbo^iaKfdeqj^obyNFAy.0-41yyKyDbq0XBjbo^ia>`lokpZqebvillhifhbifqqib_oltk_^iipqe^qpm^ohib+Clrkalkqebdolrka^olrka%01)1.&yyWyJllkdi^aby
QElmbTfqefkqebBjbo^iaKfdeqj^obyNFAy.0-41yyKyOfdeq`if`hlkqebpibbmfkd_rccql^kaqrokfkqlHbbmboObjrilp%03)1.+2&yyWyJllkdi^aby
>Qeb?llklcObjrilpyNFAy.0-42yyKyHbbmboObjrilp%03)1.+2&yyWyJllkdi^aby
QQeb?llklcObjrilpyKyDlqeolrdeqebmloq^i^kadlql@orp^abo?ofabk_o^a%46+5)0-+6&yyNFAy.0-42y
>QfjbVbqObj^fkpyNFAy.0-43yyKy@orp^abo?ofabk_o^a%46+5)0-+6&y
QQfjbVbqObj^fkpyNFAy.0-43yyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&y
>QebQlr`elc^k>pmb`qyNFAy.0-44yyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&y

CTvojobpqQbjmibyKyCivqlTvojobpqQbjmibfkAo^dlk_ifdeqyyNFAy.0-45y
QQebQlr`elc^k>pmb`qyNFAy.0-44yyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyWyAo^dlk_ifdeqy
>A^eif^$pQb^opyNFAy.0-45yyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyWyAo^dlk_ifdeqy
>JvpqbovlcqebFkcfkfqb)ObaruyNFAy.0010yyKy@eoljfb%3-)21+2&yyWyAo^dlk_ifdeqy
@JvpqbovlcqebFkcfkfqb)ObaruyKyRpbqebXElrodi^pplcBqbokfqvZ^qqeb?olkwbAo^dlkpeofkb)^q%4/)06&fkAo^dlk_ifdeqyyRy1112-yyNFAy.0010yyWyAo^dlk_ifdeqy
@A^eif^$pQb^opyNFAy.0-45yyKyT^fqqfiikb^oqebbkalcqebt^sbqebor_vt^q`ebotfiikrhbqebdolrkatfqe^ilqlccfob^kaXA^eif^$pQb^opZtfiipm^tk^olrka%2.)14&)%2-)2/&^ka%10)2.&yyWyAo^dlk_ifdeqy
QA^eif^$pQb^opyNFAy.0-45yyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyWyAo^dlk_ifdeqy
QJvpqbovlcqebFkcfkfqb)ObaruyNFAy.0010yyKy@eoljfb%3-)21+2&yyWyAo^dlk_ifdeqy
>Qeb?llklc>ibupqo^pw^yNFAy.0-46yyKy>ibupqo^pw^qebIfcb*?fkabo%26+5)21+3&yyWyAo^dlk_ifdeqy
E@orp^abop$Mfkk^`ibyRy3615yyNFAy.0-5-y

QQeb?llklc>ibupqo^pw^yNFAy.0-46yyKy@orp^abo?ofabk_o^a%46+5)0-+6&y
>ElmbVbqObj^fkpyNFAy.0-5-yyKy@orp^abo?ofabk_o^a%46+5)0-+6&y
QElmbVbqObj^fkpyNFAy.0-5-yyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&y
>QebTfiilcqebK^^oryNFAy.0-5.yyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&y
OPe^qqo^qe@fqvyKyDlqeolrdeqebmloq^iqlPe^qqo^qe@fqvyyNFAy.0-5/y
QQebTfiilcqebK^^oryNFAy.0-5.yyKy>$a^i%20)12&yyWyPe^qqo^qe@fqvy
>Qeb?llklc>$a^iyNFAy.0-5/yyKy>$a^i%20)12&yyWyPe^qqo^qe@fqvy
CQeb>odbkqS^kdr^oayKyCivqlQeb>odbkqS^kdr^oaFkF`b`oltk^q%54)42&yyNFAy.0-50y
QQeb?llklc>$a^iyNFAy.0-5/yyKy@orp^abo?ofabk_o^a%46+5)0-+6&y
>IfdeqTfqefkqebA^ohkbppyNFAy.0-50yyKy?ofabk_o^a$pMlppbppflkp%46+5)0-+6&y
QIfdeqTfqefkqebA^ohkbppyNFAy.0-50yyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&y

OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&yyNFAy.0/0.y
QQebPhv_ob^hboyKyEfde@^mq^fkGrpqfk?^oqibqq*eb$p^_l^oaQebPhv_ob^hbo)lkblcqebcivfkd^fopefmpfkqebobdflkyyNFAy.0//2y
>Qeb?olhbkColkqyNFAy.0/0.yyKyEfde@^mq^fkGrpqfk?^oqibqq*eb$p^_l^oaQebPhv_ob^hboy
>Fq$p>iiCrk^kaD^jbpyNFAy./554yyKyQe^pp^of^k*eb$p^_l^oaQebPhv_ob^hbo)lkblcqebcivfkd^fopefmpfkqebobdflky
>Glfkfkdqeb>pp^riqyNFAy.001.yyKyHkfdeq*@^mq^fkAolp`eb*eb$p^_l^oaQebPhv_ob^hboy
>DbqqlVjfoebfjyNFAy.0/63yyKy@efbcBkdfkbbo?liqtobk`e*eb$p^_l^oaQebPhv_ob^hboy
>Pi^sbpqlP^olkfqbyKy>_p^i^kqebMflrp*eb$p^_l^oaQebPhv_ob^hboyyNFAy.00--y
>?illalcqeb@elpbkyKyHkfdeq*@^mq^fkAolp`eb*eb$p^_l^oaQebPhv_ob^hboyyNFAy.0003y

@Fq$p>iiCrk^kaD^jbpyNFAy./554yyKyRpbqebXBvbplob?i^pqboZqlabpqolvQebL`ri^o)cil^qfkd^qqebqlmlcqebPe^altS^riq%11+0)/.+2&yyRy1./32y
QFq$p>iiCrk^kaD^jbpyNFAy./554yyKy?^olkPifsbo%11+/)/1+4&y

>FE^sb^kFab^)?rqCfopq+++yNFAy./56.yyKy?^olkPifsbo%11+/)/1+4&y
@FE^sb^kFab^)?rqCfopq+++yNFAy./56.yyKyX@riqfpqOlaZaolmpcoljPe^alt@riqfpqp+X>_ljfk^qflkEllhZaolmpcoljJlo_fa@^o`^ppbp+XDbfpqOlmbZaolmpcoljS^riqDbfpqp+>kaXP`lrodbBppbk`bZaolmpcoljrkab^ajl_p+Qov^olrka%10)/1&clo^iiqebpbfqbjpy
QFE^sb^kFab^)?rqCfopq+++yNFAy./56.yyKy?^olkPifsbo%11+/)/1+4&y

>CobbVlroJfkayNFAy./560yyKy?^olkPifsbo%11+/)/1+4&y
@CobbVlroJfkayNFAy./560yyRy1.033yyKyRpbqebXPlsbobfdkOlaZlkqeb`lompbplcSfib%11+1)/4&)I^avKfdeqptlla%1.+5)/1+2&)^kaQebIb^mbotelm^qoliplkqebibadb^_lsbqebnrbpqdfsbo*dlql%11+0)/0+3&^kagrpqcliiltqebibadb^olrkarkqfivlrpbbefjy
QCobbVlroJfkayNFAy./560yyKy?^olkPifsbo%11+/)/1+4&y

>FcEb@^kklq?bQrokbayNFAy./563yyKy?^olkPifsbo%11+/)/1+4&y
@FcEb@^kklq?bQrokbayNFAy./563yyKyDlfkpfabqebs^riq)pqo^fdeq^eb^aqebfotfii_b^tb^mlko^`h_vqeb_fdpq^qrb^qqebbka%12)/-&+@if`hfkdfqpm^tkpDbkbo^iIfdeqp_^kb)^ibsbi5-bifqb+Qeb0mblmibvlrhfiibab^oifbotfii`ljbqlvlro^fay

KP^sbQeb?lkbp+++yKyQebSovhri$pqeolrdelrqqefpwlkbaolmXSovhri?lkbpZ)j^hbprobvlrp^sbqebpb%^kaalk$qpbiiqebjqlsbkalop&^pvlrtfiikbbaqebjclo^i^qbonrbpqyyNFAy.0-6/y
QDbqqlVjfoebfjyNFAy.0/63yyKyCo^wwibDb^odofkabo%24)3/+2&y
>HfkdlcqebJlrkq^fkyKyCo^wwibDb^odofkabo%24)3/+2&yyNFAy.0/5-y
@HfkdlcqebJlrkq^fkyKyJlrkqQerkabo_lj_$pGrjm_lqkbuqqlvlr^kagrjmvlrot^vrmqlqebmfiblc_lkbp%21+51)3-+.1&yyNFAy.0/5-y
QHfkdlcqebJlrkq^fkyKyCo^wwibDb^odofkabo%24)3/+2&yyNFAy.0/5-y
QGlfkfkdqeb>pp^riqyNFAy.001.yyKyDolrka@ljj^kaboHlrm%3/+3)2.+0&y
>>pp^riq_v>foyKyDolrka@ljj^kaboHlrm%3/+3)2.+0&yyNFAy.00-6y
>>pp^riq_vDolrkayKyPhv_ob^hboPnr^aIb^abo%3/+4)2.&yyNFAy.0/51y
@>pp^riq_vDolrkayKyBp`loqqebPhv_ob^hboqollmpqlqebd^qbplcVjfoebfjyyNFAy.0/51y

@>pp^riq_v>foyKyDlql%3/)2-&^kajlrkqqebqroobqlcqeb>fomi^kb)j^hbprobqebob^obfkcfiqo^qlopfkqebmi^kb_bclobvlrdl)LKIVpellqqebSohriPmb^oDrk)vlrgrpqkbba.dllapelqqlabpqolvfqyyNFAy.00-6y

>JfkaQof`hpyNFAy.00-5yyKyA^ohpmb^hboO$hebj%21+2)26+/&)bkqboqebjfkbp^q%23+6)24+1&y
@JfkaQof`hpyKyHfiiClobj^kQe^iaofk^q%22)26&cloqebXClobj^k$pHbvZ+Eb`^k_bplilba_rqfqfpklqb^pv)qov^kadbqpljbebimfcvlr`^k+Qebobfpklcliiltrmnrbpqqlqefp)plfq`^k_bphfmmbaloalkbi^qboyyNFAy.00-5y
@Pi^sbpqlP^olkfqbyKyDlqlqebP^olkfqbJfkbp%23)24&)pfjmivq^ihqlqebP^olkfqbJfkbPi^sbpfkqebjfkb)vlre^sb^`e^k`bqe^qqebvtfiiorklrqlcqebjfkb^kadfsbvlrnrbpq`obafq)loqrokelpqfiblkvlryyNFAy.00--y
@?illalcqeb@elpbkyKyHfii/-VjfoebfjSovhri^qVjfoebfj%22)22&yyNFAy.0003y

Q>pp^riq_vDolrkayKyDolrka@ljj^kaboHlrm%3/+3)2.+0&yyNFAy.0/51y
Q>pp^riq_v>foyKyDolrka@ljj^kaboHlrm%3/+3)2.+0&yyNFAy.00-6y

@Qeb?olhbkColkqyNFAy.0/0.yyKyDlqlQeb?olhbkColkq^kanrbpqflk^AvfkdPliafbo%35)3/&y
>CfkfpeJbyNFAy.0/0/yyKyAvfkdPliafbo%35)3/&y
@CfkfpeJbyNFAy.0/0/yyKyHfii2AvfkdPliafbopivfkdlkqebdolrka^qqeb?olhbkColkq%35)34&y

OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&yyNFAy.0/6-y
QPi^sbpqlP^olkfqbyKy>_p^i^kqebMflrp*^_l^oaQebPhv_ob^hboyyNFAy.00--y
Q?illalcqeb@elpbkyKyHkfdeq*@^mq^fkAolp`eb*^_l^oaQebPhv_ob^hboyyNFAy.0003y
QCfkfpeJbyNFAy.0/0/yyKyEfde@^mq^fkGrpqfk?^oqibqq*^_l^oaQebPhv_ob^hboy
QQeb?olhbkColkqyNFAy.0/0.yyKyEfde@^mq^fkGrpqfk?^oqibqq*^_l^oaQebPhv_ob^hboy
>Vlro>qqbkqflk)Mib^pbyNFAy.0/6-yyKyEfde@^mq^fkGrpqfk?^oqibqq*^_l^oaQebPhv_ob^hboy
>+++>iiqebEbimTb@^kDbq+yNFAy.0/53yyKyEfde@^mq^fkGrpqfk?^oqibqq*^_l^oaQebPhv_ob^hboy
Q+++>iiqebEbimTb@^kDbq+yNFAy.0/53yyKyQe^pp^of^k*^_l^oaQebPhv_ob^hboy
>Mlhb^kaMolayNFAy.0/54yyKyQe^pp^of^k*^_l^oaQebPhv_ob^hboy
QFcEb@^kklq?bQrokbayNFAy./563yyKyQe^pp^of^k*^_l^oaQebPhv_ob^hboy
>QebPe^altS^riqyNFAy./565yyKyQe^pp^of^k*^_l^oaQebPhv_ob^hboy
>KlJbo`vyNFAy.0/00yyKyEfde@^mq^fkGrpqfk?^oqibqq*^_l^oaQebPhv_ob^hboy
QVlro>qqbkqflk)Mib^pbyNFAy.0/6-yyKy@efbcBkdfkbbo?liqtobk`e*^_l^oaQebPhv_ob^hboy
>?looltbaQb`eklildvyKy@efbcBkdfkbbo?liqtobk`e*^_l^oaQebPhv_ob^hboyyNFAy.0/6.y

OQebPe^altS^riqyKyCivqlQebPe^altS^riq%1/)/1&yyNFAy./605y
QQebPe^altS^riqyNFAy./565yyKy?^olkPifsbo%1/+6)/2&y
>QebArhbyNFAy./605yyKy?^olkPifsbo%1/+6)/2&y
>?i^`ht^q`eyNFAy.0.-3yyKy?^olkPifsbo%1/+6)/2&y
QQebArhbyNFAy./605yyKyArhbI^kho^i%11+3)/-+2&y
>Elklo@e^iibkdbyNFAy./606yyKyArhbI^kho^i%11+3)/-+2&y
>Bifjfk^qbqeb@ljmbqfqflkyNFAy./622yyKyQebIb^mbo%10+3)/2+.&y

OP^s^dbIbadbyKyCivqlP^s^dbIbadb%04)//&yyNFAy./666y
@Elklo@e^iibkdbyNFAy./606yyKyRpbqebX@e^iibkdbCi^dZqlhfii3Jgloafk@lj_^q^kqp%04)/1&yyRy1.04/y
@Bifjfk^qbqeb@ljmbqfqflkyNFAy./622yyKyHfiiPfdofaF`b_lok%04+.)//+2&)BcobjqebC^fqecri%04+5)/2+.&)Lkr$wrk%04+6)//+6&^kaQfkhvTf`htefpqib%03+/)/0+3&y
QBifjfk^qbqeb@ljmbqfqflkyNFAy./622yyKyQebIb^mbo%10+3)/2+.&y
>Qeb?lkbTfq`eyNFAy./666yyKyQebIb^mbo%10+3)/2+.&y
QElklo@e^iibkdbyNFAy./606yyKyArhbI^kho^i%11+3)/-+2&y
>Pe^altS^riqAb`obbyNFAy./610yyKyArhbI^kho^i%11+3)/-+2&y
>DbqqebHbvyNFAy./616yyKyS^bibkqebCi^vba%1.)/0+6&)dlqlqebbkqo^k`b^q%06)/1&qlcfkaefjy
@Pe^altS^riqAb`obbyNFAy./610yyKyOb^aqebXPe^altS^riqAb`obbZqlQe^kbRco^kdqebJfdeqv%1-+/)/0+6&qebkhfiiefjyyRy1.443y
@DbqqebHbvyNFAy./616yyKyHfiiFkpqor`qloEolbd^o^olrka%04)/1&qldbqqebXHbvqlS^bibk$p@e^fkpZy
QDbqqebHbvyNFAy./616yyKyS^bibkqebCi^vba%1.)/0+6&)dlqlqebbkqo^k`b^q%06)/1&qlcfkaefjy
>Ibqqeb?^olkHkltyNFAy./62.yyKyS^bibkqebCi^vba%1.)/0+6&y
QIbqqeb?^olkHkltyNFAy./62.yyKy?^olkPifsbo%1/+6)/2&y
>Ib^sbLroJ^ohyNFAy./662yyKy?^olkPifsbo%1/+6)/2&y
QPe^altS^riqAb`obbyNFAy./610yyKyArhbI^kho^i%11+3)/-+2&y
>S^bibkE^pObqrokbayNFAy.0-52yyKy?^olkPifsbo%1/+6)/2&y
>@orpeAbjSovhripyNFAy./66/yyKySfib%10)/2&y
QS^bibkE^pObqrokbayNFAy.0-52yyKyS^bibkqebCi^vba%10+/)/.+.&y
>B_lk?i^abMofplkbopyNFAy./65/yyKyS^bibkqebCi^vba%10+/)/.+.&y
>S^ka^ifwfkdGlqrkebfjyNFAy.0-51yyKyArhbI^kho^i%11+3)/-+2&y

QQeb?lkbTfq`eyNFAy./666yyKyQeb?lkbTfq`e%0/+2)1/+6&y
>Ob^afkdqeb?lkbpyNFAy.0-6/yyKyQeb?lkbTfq`e%0/+2)1/+6&y
>Abbmfkqeb?ltbiplcQebRkaboe^iipyNFAy.0-1/yyKyQeb?lkbTfq`e%0/+2)1/+6&y
@Ob^afkdqeb?lkbpyNFAy.0-6/yyKy@liib`q.2XSovhri?lkbpZ^olrka%0/)1/&+Pbbjpql_b^.--"aolmo^qblcc^kvsovhrifkqeb^ob^y
QOb^afkdqeb?lkbpyNFAy.0-6/yyKyQeb?lkbTfq`e%0/+2)1/+6&y
KRpb?^kkbo^pvlrhfii++yKyCfka?bqelaCbfdo%03+.)00+.&fkqebRkaboe^iip)qebbkqo^k`bfp^q%0/)0/&^pvlrhfiiqebjl_ptfqefkqeb`^sbebob)rpbqebB_lk?i^ab?^kkbonrbpqfqbjlkqebjl_`lompbpyyRy1/15-yyNFAy./662y
>ObsbkdbcloqebS^odriyNFAy.0-26yyKy?bqelaCbfdo%03+.)00+.&y
@ObsbkdbcloqebS^odriyNFAy.0-26yyRy1/6/5yyKyColjqebnrbpqdfsbodlpqo^fdeq^`olpp^kaaltkqebpq^fo`^pb^kavlrtfiipbbqeb`fo`iblcprccbofkdlkqebpfab+QeoltaltkX?bqela$pPtloaZ^kaqebkhfiiQe^kbFiiph^o%0/+6)05+.&y
@Abbmfkqeb?ltbiplcQebRkaboe^iipyNFAy.0-1/yyKyBkqo^k`bqlQebRkaboe^iipfp^q%00)0/&+Dlpqo^fdeq^eb^aqfiivlrpbbpq^foplkvlroofdeqpfab+Dlaltkqebpq^fop)qrokibcq^kadlqlqeb_lqqljlcqebpq^fo`^pb+Lkvlroibcq%rkaboqebpq^fop&vlrpelriapbb>mmobkqf`bLpqbohfido%01+.)03+2&+?b^qefjaltkql^olrka1-")eb$iidfsbvlrqebfkcloj^qflk^kaqebkhfiiefj+EbtfiiaolmXAo+Qboof_ib$p?rfiafkd^?bqqboCibpeDf^kqZqlpq^oqkbuqnrbpqy
>QebPrjfpDob^qboqe^kqebM^oqpyKyRpbXAo+Qboof_ib$p?rfiafkd^?bqqboCibpeDf^kqZaolmmba_vqeb>mmobkqf`bql_bdfkqebnrbpqyyRy1/44/yyNFAy.0-10y
@QebPrjfpDob^qboqe^kqebM^oqpyKyJlrkqKbodbia%00+1)00+/&^kahfiiAoQboof_ib+Tebkeb`ljbplrq`lkqfkrlrpivMrk`eefjmobppfkd.tefib^iplOl^ofkdqeblqebojl_p^t^v+FcvlrOl^oAo+Qboof_ib^t^v^ptbiinrf`hivrpbqeb@e^fkbaDofm^_fifqvql_ofkdefj_^`hqlvlrplvlr`^k`lkqfkrbqlMrk`eefj+>iplklqbqe^qqebAo`^keb^iefjpbic)fcvlrpbbefjobsrmefpeb^ifkd)nrf`hivPqljmefj)fqtfiipqlmfqyyNFAy.0-10y

QObsbkdbcloqebS^odriyNFAy.0-26yyKy?bqelaCbfdo%03+.)00+.&y
@S^bibkE^pObqrokbayNFAy.0-52yyRy1/15-yyKyPmb^hqlS^bibkqebCi^vba^qQebPe^altS^riq%10+/)/.+.&y
@S^ka^ifwfkdGlqrkebfjyNFAy.0-51yyRy1/15-yyKy?rok.-Sovhri?^kkbop+Clrka^olrkaqeb^obk^mfq^q%0-)/5&^kaj^gloSovhri_rfiafkdpifhbRco^kd$pE^ii%05)/1&^kaE^iiplcqeb>k`bkpqlop%/5)13&y
@B_lk?i^abMofplkbopyNFAy./65/yyKyHbbmhfiifkdclohbvpfcvlrkbbaqly
@@orpeAbjSovhripyNFAy./66/yyRy1/15-yyKyHfii^kv.2sovhrifkqebdob^qboGlqrkebfjobdflk%0-)/5&y
@Ib^sbLroJ^ohyNFAy./662yyRy1/15-yyKyMi^kq.2XB_lk?i^ab?^kkbopZkb^oqeb`lompbplcsovhri^olrka%0-)/5&y

QAbbmfkqeb?ltbiplcQebRkaboe^iipyNFAy.0-1/yyKyQeb?lkbTfq`e%0/+2)1/+6&y
QQebPrjfpDob^qboqe^kqebM^oqpyNFAy.0-10yyKyQeb?lkbTfq`e%0/+2)1/+6&y
>Qeb>oqlc?bfkd^T^qboQbooloyNFAy.0-6.yyKyQeb?lkbTfq`e%0/+2)1/+6&y
@Qeb>oqlc?bfkd^T^qboQbooloyNFAy.0-6.yyKyDlqlqebd^qb^q%0.)1.&^kaofdeq`if`hlkfq)qlq^hb`lkqolilc^T^qboQboolo+Fqtfiie^sb^qlli_^oqlrpblk`bvlrmlppbpfq+Qebkhfii.-sovhrifkqebproolrkafkd^ob^y
QQeb>oqlc?bfkd^T^qboQbooloyNFAy.0-6.yyKyQeb?lkbTfq`e%0/+2)1/+6&y
>QeolrdeqebBvbyNFAy.0./.yyKyQeb?lkbTfq`e%0/+2)1/+6&y
@QeolrdeqebBvbyNFAy.0./.yyKyBkqo^k`bqlHri$d^i^oHbbmfp^q%/2)3.&+Cfdeqqeolrde^`lrmibjl_p+Qebbvbfp^_irbcil^qfkd_^iiy
QQeolrdeqebBvbyNFAy.0./.yyKyQeb?lkbTfq`e%0/+2)1/+6&y
>Cfkaqeb>k`fbkqEbolyNFAy.0.00yyKyQeb?lkbTfq`e%0/+2)1/+6&y
@Cfkaqeb>k`fbkqEbolyKyQ^ihqlPirj_bofkdJgloafk%/4)14&rkqfiFph^iabofpobsb^iba)lk`bebalbp^mmb^orpbXQeb?lkbTfq`e$p>jribqZlkefj+Qebkq^hbefj_^`hqlQeb?lkbTfq`eyyRy10.33yyNFAy.0.00y
QCfkaqeb>k`fbkqEbolyNFAy.0.00yyKyQeb?lkbTfq`e%0/+2)1/+6&y
>Klq*Pl*Elklo^_ib@lj_^qyNFAy.0.04yyKyQeb?lkbTfq`e%0/+2)1/+6&y
@Klq*Pl*Elklo^_ib@lj_^qyNFAy.0.04yyKyHfiiFph^iabo^q?^qqibp`^oPmfob%/5+4)2.+6&y
QKlq*Pl*Elklo^_ib@lj_^qyNFAy.0.04yyKyQeb?lkbTfq`e%0/+2)1/+6&y
>?^kpebb$pObsbkdbyKyQeb?lkbTfq`e%0/+2)1/+6&+Qefpfp^dolrmnrbpq)vlrtfiikbbaqldolrmrmql`ljmibqbfq)qebcliiltrmdolrmnrbpqp?^qqiblcS^ie^i^pfptloqealfkdclodliafcvlr`^kyyNFAy.0.1/y

OQebPe^altS^riqyKyCiv_^`hqlQebPe^altS^riq%1/)/1&yyNFAy.0-4.y
Q@orpeAbjSovhripyNFAy./66/yyRy1/15-yyKySfib%10)/2&y
>SfibIfhbCfobyKySfib%10+2)/1+2&yyNFAy.0-4.y
QS^bibkE^pObqrokbayNFAy.0-52yyRy1/15-yyKyS^bibkqebCi^vba%10+/)/.+.&y
QB_lk?i^abMofplkbopyNFAy./65/yyKyS^bibkqebCi^vba%10+/)/.+.&y
QS^ka^ifwfkdGlqrkebfjyNFAy.0-51yyRy1/15-yyKyArhbI^kho^i%11+3)/-+2&y
QIb^sbLroJ^ohyNFAy./662yyRy1/15-yyKy?^olkPifsbo%1/+6)/2&y
>QlqebOfpbtfqe^iiArbE^pqbyNFAy./5-3yyKy?^olkPifsbo%1/+6)/2&y
>Pellq$BjRmyKyQebIb^mbo%10+3)/2+.&yyNFAy.0-36y
@Pellq$BjRmyKyDlql%0/)/1&^ka`ellpblkblcqebe^omllkp+T^fqrkqfiqebao^dlkpcivkb^o_v)fcvlrkbbajlobqe^k2pelqpqlhfiilkbqebkqebv^obk$q`ilpbbklrdeyyNFAy.0-36y
@SfibIfhbCfobyKyDlql%/4)06&^kajlrkq^Ao^hb)^ka_rokqeb_rfiafkdpfkqeb^ob^yyNFAy.0-4.y
QSfibIfhbCfobyKySfib%10+2)/1+2&yyNFAy.0-4.y
QPellq$BjRmyKyQebIb^mbo%10+3)/2+.&yyNFAy.0-36y

OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&yyNFAy.0053y
>Bumilfqfkd^kLmbkfkdyNFAy.0053yyKyQe^pp^of^k*^_l^oaQebPhv_ob^hboy

OAb^qe$pOfpbyKyCivqlAb^qe$pOfpb%/-)14&yyNFAy./5-4y
QQlqebOfpbtfqe^iiArbE^pqbyNFAy./5-3yyKyIloa*@ljj^kabo>obqb%.6+3)15+.&y
>QebPqlovQerpC^o+++yNFAy./5-4yyKyIloa*@ljj^kabo>obqb%.6+3)15+.&y
@QebPqlovQerpC^o+++yNFAy./5-4yyKyIfpqbkqlIloa*@ljj^kabo>obqb$ppqlov%.6+3)15+.&y
QQebPqlovQerpC^o+++yNFAy./5-4yyKyIloa*@ljj^kabo>obqb%.6+3)15+.&y
>?illafkqebT^qboyNFAy./5.-yyKyIloa*@ljj^kabo>obqb%.6+3)15+.&y
>ColjQebfo@lompbp)OfpbyKyPbq^^iA^ohjbkabo%.6+4)15+0&yyNFAy./5.0y
>Fkqbiifdbk`bD^qebofkdyKy>rol`epDofj_^kb%.6+6)14+3&yyNFAy./505y

@?illafkqebT^qboyNFAy./5.-yyKyRpbqebXDlob?i^aaboZqlmf`hrmqeb_illacoljqebt^qbo^cqbovlrhfii^pe^oh+O^sbklrpG^tpil`^qba^olrka%6)1/&^ka%4)03&yyRy1-22.y
Q?illafkqebT^qboyNFAy./5.-yyKyIloa*@ljj^kabo>obqb%.6+3)15+.&y
>Vlr$iiKbba^DovmelkyNFAy./5.1yyKyIloa*@ljj^kabo>obqb%.6+3)15+.&y
HLkpi^rdeqDovmelkOfaboyKyhfiilkbLkpi^rdeqDovmelkOfabo^olrka%.-)05&cloXLkpi^rdeqDovmelkObfkpZyyNFAy./5.1y
RXLkpi^rdeqDovmelkObfkpZyKyRpbXLkpi^rdeqDovmelkObfkpZyyRy1-64-yyNFAy./5.2y
@Vlr$iiKbba^DovmelkyNFAy./5.1yyKyOfabqebDovmelk_^`hqlRwlAb^qe`^iibo%.6+4)14+6&^kamobpplkb.qlabifsboy
QVlr$iiKbba^DovmelkyNFAy./5.1yyKyRwlAb^qe`^iibo%.6+4)14+6&y
>KlCivWlkbyKyRwlAb^qe`^iibo%.6+4)14+6&yyNFAy./5.2y

@KlCivWlkbyKyKlqb7Vlralk$qe^sbqlrpbqebX?lkbDovmelkZql`ljmibqbqebnrbpq)DlqlLkpi^rdeqE^o_lo^karpbqebmolsfabaX?lkbDovmelkZclovlrocivfkdjlrkq+Rpb?lkb>ojlotebkbsboqeb`llialtkfpcfkfpeba+Hfii.-Lkpi^rdeqDovmelkOfabop^olrka%.-)05&)pq^oqlcctfqeMi^drbPqofhb^kapm^jColpq?ob^qerkqfiqebofabofpab^a+Fcvlro?lkbDovmelk$peb^iqefpilt)afpjlrkq^kaob*prjjlkfq)qldbq^kbt?lkbDovmelktfqecriieb^iqeyyRy1-254yyNFAy./5.2y
@ColjQebfo@lompbp)OfpbyKyHfiiP`^oibqLkpi^rdeq%4)1.&^kaillqqeb`lompbpclohbvp^karpbXA^ohjbkabo$pQfk`qrobZlkqeb`lompbpyyRy1-254yyNFAy./5.0y
@Fkqbiifdbk`bD^qebofkdyKyDlqlqeb_b^`e^q%5)10&tef`efp^qqeb_^`hlcqebe^o_lo^karkil`hqeb`ebpqpqebobyyNFAy./505y

>QebDo^ka%>ajfo^i$p&Mi^kyKyQebfqbjXKlqbcoljqebDo^ka>ajfo^iZpq^oqpnrbpq*aolmmba_vLkpi^rdeqO^sbk?fpelm^kaLkpi^rdeqE^o_loDr^oap^olrka%6)10&yyRy1-333yyNFAy./506y

QFkqbiifdbk`bD^qebofkdyKy>rol`epDofj_^kb%.6+6)14+3&yyNFAy./505y
QKlCivWlkbyKyRwlAb^qe`^iibo%.6+4)14+6&yyNFAy./5.2y
QColjQebfo@lompbp)OfpbyKyPbq^^iA^ohjbkabo%.6+4)15+0&yyNFAy./5.0y
QQebDo^ka%>ajfo^i$p&Mi^kyNFAy./506yyKyIloa*@ljj^kabo>obqb%.6+3)15+.&y

>FkPqof`q@lkcfabk`byNFAy./51-yyKyIloa*@ljj^kabo>obqb%.6+3)15+.&y
@FkPqof`q@lkcfabk`byKyHfii@^mq^fkTbipfkdqlkfp^q%2+4)1.+6&^ka@^mq^fkE^oqcloafp^q%4)1.+6&lkqeb_l^qpyyNFAy./51-y
QFkPqof`q@lkcfabk`byNFAy./51-yyKyIloa*@ljj^kabo>obqb%.6+3)15+.&y

>Pb`lka@e^k`bpyKyIloa*@ljj^kabo>obqb%.6+3)15+.&+Qefpfp^dolrmnrbpq)p^sbfqfk`^pbvlrcfka^dolrmqlalqefptfqeyyNFAy./514y
Q?i^`ht^q`eyNFAy.0.-3yyKyA^ohofabo>oiv%02+1)33+1&y
>Tebob>obQebv@ljfkdColj<yNFAy.0..4yyKyA^ohofabo>oiv%02+1)33+1&y
@Tebob>obQebv@ljfkdColj<yNFAy.0..4yyKyVlr`^krpb^kvlcqeb1^iqbop^q%04)4-&y
QTebob>obQebv@ljfkdColj<yNFAy.0..4yyKyA^ohofabo>oiv%02+1)33+1&y

>Abpqolvfkdqeb>iq^opyNFAy.0..6yyKyA^ohofabo>oiv%02+1)33+1&y
>Ab^qe$pD^wbyNFAy.0./-yyKyA^ohofabo>oiv%02+1)33+1&y
HJ^pqboPrjjlkboW^olayKyHfiiJ^pqboPrjjlkboW^ola%04)4.&^kaillqefpXJ^pqboPrjjlkbo$pPq^ccZyyIy10.26yyNFAy.0..6y
@Abpqolvfkdqeb>iq^opyKyQeb1^iq^op^obkb^o%04)4-&^kaW^olafpol^jfkd_bqtbbkqebj+Hfiiefj^karpbefpXJ^pqboPrjjlkbo$pPq^ccZqlabpqolvqebj+Vlr`^krpbqebpq^cctefibcivfkdyyRy10.26yyNFAy.0..6y
@Ab^qe$pD^wbyKyRpbXAb^qe$pD^wbLo_Zlkqeb>_ljfk^qflkLo_7%0/+3)4-+3&)CibpeDf^kqLo_7%01+3)36+3&^ka@^riaolkLo_7%0-+2)32+.&yyRy10//6yyNFAy.0./-y
QAbpqolvfkdqeb>iq^opyNFAy.0..6yyKyA^ohofabo>oiv%02+1)33+1&y
QAb^qe$pD^wbyNFAy.0./-yyKyA^ohofabo>oiv%02+1)33+1&y

>PmfiiQebfo?illayNFAy.0.01yyKyA^ohofabo>oiv%02+1)33+1&y
@PmfiiQebfo?illayNFAy.0.01yyKyAbpqolv2s^qplcBj_^ijfkdCirfa%qebvillholrka^kadobbk&^ka2?illaLo_p^olrka%0/)4-&+IllhlrqclofqbjaolmXG^ddbaPe^oaZqlpq^oqkbuqnrbpqy
>G^ddbaPe^oapyKyQebfqbjXG^ddbaPe^oaZpq^oqpnrbpq*aolmmba_vPmfhbaDelrip^olrka%0/)4-&yyRy10/1/yyLyyNFAy.0.03y
>F$jKlqAb^aVbqyKyC^qeboH^j^olp%0.+5)3.+5&yyNFAy.0//.y
@F$jKlqAb^aVbqyKyBp`loqC^qeboH^j^olpqlp^cbqvyyNFAy.0//.y
@G^ddbaPe^oapyNFAy.0.03yyKy@liib`q.-XG^ddbaPe^oapZaolmmba_vPmfhbaDelrip^olrka%0/)4-&+Vlrlkivkbba6jloblcqebpb)^pqebfqbjtef`epq^oqbaqebnrbpq^ipl`lrkqp^plkby
QG^ddbaPe^oapyNFAy.0.03yyKy@orp^aboLi^hfkP^fkofqe%02+2)33+2&y
QPmfiiQebfo?illayNFAy.0.01yyKyA^ohofabo>oiv%02+1)33+1&y

>F$jPjbiqfkd+++PjbiqfkdyNFAy.0.05yyKy@orp^aboLi^hfkP^fkofqe%02+2)33+2&y
>QebOrkbpjfqeplcJ^ivhofppyNFAy.0.1-yyKy@orp^aboLi^hfkP^fkofqe%02+2)33+2&y

QBumilfqfkd^kLmbkfkdyNFAy.0053yyKy@^mq^fkHbka^ii%2.+5)53+4&y
>Pb`rofkdqebMbofjbqboyNFAy.0054yyKy@^mq^fkHbka^ii%2.+5)53+4&y
@Pb`rofkdqebMbofjbqboyNFAy.0054yyKyHfii.-ErihfkdEloolop^olrkaF`b`oltk@fq^abi%2.)53&y
QPb`rofkdqebMbofjbqboyNFAy.0054yyKy@^mq^fkHbka^ii%2.+5)53+4&y
>PbqfqLccyNFAy.0055yyKy@^mq^fkHbka^ii%2.+5)53+4&y
@PbqfqLccyNFAy.0055yyKyIfdeqqebcrpb^qqebpq^`hlc_lj_p%21+1)53+0&`ilpbqlqebnrbpqdfsboy
QPbqfqLccyNFAy.0055yyKyP^olkfqb?lj_Pq^`h%21+1)53+/&y
>>PeloqCrpbyNFAy.0056yyKyP^olkfqb?lj_Pq^`h%21+1)53+/&y
@>PeloqCrpbyNFAy.0056yyKy>cqbovlrc^iialtkfkqlqebelib)qebpj^ii`ovpq^ivlrkbbaqlq^ihqlfprkabot^qbo%21)54+0&+Qefpqebkib^apqlq^ihfkdtfqeqeberj^k_lvaltkqebobqldbqqebkbuqnrbpqy
Q>PeloqCrpbyNFAy.0056yyKyMripfkd@ovpq^i%21)54+0&y
>>Slf`bfkqebA^ohyNFAy.006-yyKyMripfkd@ovpq^i%21)54+0&y
Q>Slf`bfkqebA^ohyNFAy.006-yyKyJ^qqef^pIbekbo%20+5)54&y
>QfjbqlEfabyNFAy.006.yyKyJ^qqef^pIbekbo%20+5)54&y
@QfjbqlEfabyNFAy.006.yyKyDbq0XC^`bibppLkb$p?illaZaolmmba_vC^`bibppIrohbo^olrka%23)52&y
QQfjbqlEfabyNFAy.006.yyKyJ^qqef^pIbekbo%20+5)54&y
>ObqrokqlqebProc^`byNFAy.006/yyKyJ^qqef^pIbekbo%20+5)54&y

@F$jPjbiqfkd+++PjbiqfkdyKyPq^kaafob`qivfkcolkqlclkblcqebcrok^`bp%25)4.&^karpbqebX?^dlcG^ddbaPe^oapZyyRy10/56yyNFAy.0.05y
@QebOrkbpjfqeplcJ^ivhofppyNFAy.0.1-yyKyDbq2XOrkbaP^olkfqbMi^qbpZaolmmba_vPhbibq^iOrkbpjfqep^olrka%26)40+5&y
QF$jPjbiqfkd+++PjbiqfkdyKy@orp^aboLi^hfkP^fkofqe%02+2)33+2&yyRy10/56yyNFAy.0.05y
QQebOrkbpjfqeplcJ^ivhofppyNFAy.0.1-yyKy@orp^aboLi^hfkP^fkofqe%02+2)33+2&y
>?vCfob?bMrodbayNFAy.0/..yyKy@orp^aboLi^hfkP^fkofqe%02+2)33+2&y
>>SfpfqqlqebAl`qloyNFAy.0.2/yyKyA^ohofabo>oiv%02+1)33+1&y
@?vCfob?bMrodbayNFAy.0/..yyKy?rok4Cbpqbofkd@lompbprpfkdXLi^hfk$pQlo`eZ^qqebP^k`qrjlcOb^kfj^qflk%01)36&yyRy102/1y
@>SfpfqqlqebAl`qloyNFAy.0.2/yyKy@^sbbkqo^k`bfp^q%01)36&+M^q`ebpfp^q_lqqljlcqeb`^sb`e^fkbaql^jbq^ipq^hb%02+6)34+.&+@if`hqebpq^hb^kaqebal`qlotfiipm^tk+M^q`ebptfiiplilefjplvlralk$qe^sbqlal^kvcfdeqfkdy
Q?vCfob?bMrodbayNFAy.0/..yyKy@orp^aboLi^hfkP^fkofqe%02+2)33+2&y
Q>SfpfqqlqebAl`qloyNFAy.0.2/yyKyA^ohofabo>oiv%02+1)33+1&y
>HfiifkdQtlP`lrodbTfqeLkbPhbibqlkyNFAy.0.11yyKyA^ohofabo>oiv%02+1)33+1&y
@HfiifkdQtlP`lrodbTfqeLkbPhbibqlkyNFAy.0.11yyKyQeb?rokfkdPhbibqlkp^obqebdobbk_lkb^ojppm^ohifkdo^kaljivlkqebdolrka+@if`hqeb^ojp)^kavlrtfiidbq^?rokfkdPhbibqlk`ljm^kflk+Qebk_ofkdqebjqlqeb`e^fkba^_ljfk^qflkp^olrka%0/)32&y
QHfiifkdQtlP`lrodbTfqeLkbPhbibqlkyNFAy.0.11yyKyA^ohofabo>oiv%02+1)33+1&y
>Eb$pDlkbqlMfb`bpyKyA^ohofabo>oiv%02+1)33+1&yyNFAy.0/./y
@Eb$pDlkbqlMfb`bpyKyHfiiqeb@lomribkqEloolo^olrka%03)34+2&^ka%0.)3-&ql`liib`q^iiqebm^oqpmfb`bpyyNFAy.0/./y
QEb$pDlkbqlMfb`bpyKyA^ohofabo>oiv%02+1)33+1&yyNFAy.0/./y
>MrqqfkdLi^hfk?^`hQldbqebo>d^fkyKyA^ohofabo>oiv%02+1)33+1&yyNFAy.0//-y
KDlfkqlqeb@^sb+++yKyDlfkqlqeb`^sb^q%01)35&yyNFAy.0//-y
@MrqqfkdLi^hfk?^`hQldbqebo>d^fkyKy@liib`qqebXPmllilcQeob^aZ^q%02)33&^kaXAl`qlo$p@ib^sboZ^q%04)34&qebkrpbqebX@orp^aboLi^hfk$pObj^fkpZlkqebPi^_%03)34&yyRy10231yyNFAy.0//-y
QMrqqfkdLi^hfk?^`hQldbqebo>d^fkyKyA^ohofabo>oiv%02+1)33+1&yyNFAy.0//-y
>QebCibpeDf^kq@e^jmflkyKyA^ohofabo>oiv%02+1)33+1&yyNFAy.0/02y
@QebCibpeDf^kq@e^jmflkyKyPmb^hqlJ^odo^sbAe^h^o%/6+4)3.+2&^kaHfiiJlo_frp%/6)3.&yyNFAy.0/02y
QQebCibpeDf^kq@e^jmflkyKyA^ohofabo>oiv%02+1)33+1&yyNFAy.0/02y

OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&yyNFAy.0060y
QObqrokqlqebProc^`byKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.006/y
>CfbiaObm^fopyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0060y
QF$jKlqAb^aVbqyKy>_p^i^kqebMflrplkQebPhv_ob^hboyyNFAy.0//.y

OQebPe^altS^riqyKyCivqlQebPe^altS^riq%1/)/1&yyNFAy.0.35y
>M^oqfkdDfcqpyKyHbofqlpb?illa_i^ab%11)/1+3&yyNFAy.0.35y
@M^oqfkdDfcqpyKyRpb^kBvblcAljfkflk%11)/2&qlq^hb`lkqolilc^`^mqrobaBfalilkT^q`eboyyNFAy.0.35y
QM^oqfkdDfcqpyKyHbofqlpb?illa_i^ab%11)/1+3&yyNFAy.0.35y
>ColjTebk`bQebv@^jbyKyHbofqlpb?illa_i^ab%11)/1+3&yyNFAy.0.4.y
>>kRkab^a$p?bpqCofbkayKyHbofqlpb?illa_i^ab%11)/1+3&yyNFAy.0.36y
>ElklofpcloqebTb^hyKyHbofqlpb?illa_i^ab%11)/1+3&yyNFAy.0.4-y
@ColjTebk`bQebv@^jbyKyRpbqebBvblcAljfk^qflkil`^qba^q%11)/1&ql_b`ljb^BfalilkT^q`ebo+Qebkvlr`^kabpqolvqeb@ovpq^ip^kacbbaqebErkdbofkdMi^drbelrkap^kahfiiqebIllhlrqpyyNFAy.0.4.y
@>kRkab^a$p?bpqCofbkayKyRpbqebBvblcAljfk^qflkil`^qba^q%11)/1&ql_b`ljb^BfalilkT^q`ebo+Qebkvlr`^kabpqolvqeb@ovpq^ip^kacbbaqebErkdbofkdMi^drbelrkap^kahfiiqebIllhlrqpyyNFAy.0.36y
@ElklofpcloqebTb^hyKyRpbqebBvblcAljfk^qflkil`^qba^q%11)/1&ql_b`ljb^BfalilkT^q`ebo+Qebkvlr`^kabpqolvqeb@ovpq^ip^kacbbaqebErkdbofkdMi^drbelrkap^kahfiiqebIllhlrqpyyNFAy.0.4-y
QColjTebk`bQebv@^jbyKyHbofqlpb?illa_i^ab%11)/1+3&yyNFAy.0.4.y
Q>kRkab^a$p?bpqCofbkayKyHbofqlpb?illa_i^ab%11)/1+3&yyNFAy.0.36y
QElklofpcloqebTb^hyKyHbofqlpb?illa_i^ab%11)/1+3&yyNFAy.0.4-y
>Pbbaplc@e^lpyKyHbofqlpb?illa_i^ab%11)/1+3&yyNFAy.0.4/y
>>jfapqqeb@lkcrpflkyKyHbofqlpb?illa_i^ab%11)/1+3&yyNFAy.0.41y
@Pbbaplc@e^lpyKyQ^ihHbofqlpb?illa_i^ab%11)/1+3&qlcivlk^phbibq^idovmelk^kaqebkrpbqeb$Cfob_lj_$^_fifqvqlhfii^iiqebrkab^a+Lk`balkb)m^o^`erqbaltk%_vrpfkdqeb$ib^sbsbef`ib$_rqqlk&yyNFAy.0.4/y
@>jfapqqeb@lkcrpflkyKy@liib`qqebAl`rjbkq%06+.)00+4&)Ibadbo%06+/)03+4&)J^m%05+4)06+1&)P`ebarib%04+/)1.+3&yyNFAy.0.41y
QPbbaplc@e^lpyKyHbofqlpb?illa_i^ab%11)/1+3&yyNFAy.0.4/y
Q>jfapqqeb@lkcrpflkyKyHbofqlpb?illa_i^ab%11)/1+3&yyNFAy.0.41y
>Sbobqeqeb@rkkfkdyKyHbofqlpb?illa_i^ab%11)/1+3&yyNFAy.0.22y
QSbobqeqeb@rkkfkdyKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.22y

>KbtOb`orfqyKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.10y
@KbtOb`orfqyKyQlpr_grd^qb^IfqebPq^ihbo%22)4.&)^qq^`hfq^kalk`bfq$paltkql^_lrq.,0eb^iqeqebobtfii_b^kbjlqbjbpp^dbqe^qp^vpQebIfqebPq^ihbofptb^hbkba_vqeb^pp^riq+RpbqebXPfdfilcqebB_lk?i^abZqlpr_grd^qba^IfqebPq^ihbo)^kaq^hbfq_^`hql%22+6)36+1&yyRy100.2yyNFAy.0.10y
QKbtOb`orfqyKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.10y
>QebSfibEliayKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.12y
@QebSfibEliayKyDbq`lkqolilcqebifqebpq^ihbocoljqebbvblcaljfkflkgrpqrmqebol^a_befkaSbobqeqeb@rkkfkd%20+6)4.+2&)>i^qlcP^`ofcf`b7%23+0)46+.&)?illaClodb7%25+.)4-+6&)F`vIllhlrq7%3-+3)35+4&)Orkbtlohp7%26+.)41+1&yyNFAy.0.12y
QQebSfibEliayKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.12y
>Dbkbolpfqv>_lrkapyKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.13y
>J^q`ej^hboyKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.14y
>PqrkkfkdSfbtyKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.3-y
KPq^vfkIb^mboClojyKyJ^hbprobvlr^obpqfiifkib^mbocloj%fcvlroklqdlqlqeb$BvblcAljfkflk$_befkavlrqldbqfq^d^fk&^kaalqebcliiltfkd0nrbpqpqldbqeboyyNFAy.0.13y
@Dbkbolpfqv>_lrkapyKyDbqql%24+6)40+5&)q^odbq$P`lro^db?lj_$)rpbphfiikrj_bo/Folk@e^fklkqeb_lj_qebkjlsbqlqebkb^obpq^_ljfk^qflk$Irj_bofkd>qol`fqv$yyNFAy.0.13y
@J^q`ej^hboyKyDlql%26)40&^kavlrtfiipbbqebPhbibq^iOrkbpjfqe$ptlohfkd+grpqrpbqeb`ljj^kaQeoltOl`hlklkblcqebRj_o^i?orqbp^kaqebvtfii^rqlj^qf`ivt^ihlsbo^kamf`h^cfdeqtfqeqebkb^obpqPhbibq^iOrkbpjfqeyyNFAy.0.14y
@PqrkkfkdSfbtyKyDlql%3-)42&^kacfkaqebPibbmfkdD^odlvibp)rpbqeb^_fifqv$Eb^sb$lkqebjqlhfiiqebjyyNFAy.0.3-y
QDbkbolpfqv>_lrkapyKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.13y
QJ^q`ej^hboyKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.14y
QPqrkkfkdSfbtyKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.3-y
KKbuq0Nrbpq+++yKyKbuq0nrbpqp^ob2j^kdolrmnrbpqp)hbbmqebjfkvlroildfk`^pbvlrcfka^dolrmyyNFAy.0.3.y
>QebOfabolcqebRkelivyKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.3.y
>QebOfabolcColpqyKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.3/y
>QebOfabolc?illayKySbobqeqeb@rkkfkd%20+6)4.+2&yyNFAy.0.30y

@CfbiaObm^fopyKyHfiiP`^sbkdfkdDbfpq%34)21&ql`liib`q2uXAbjlifpeboM^oqpZyyNFAy.0060y
QCfbiaObm^fopyKyTob`hbaAbjlifpebo%35)2.+5&yyNFAy.0060y
>AlVlroTlopqyKyJ^qqef^pIbekbo%35)2.+4&yyNFAy.0061y
@AlVlroTlopqyKyRpbqebObcro_fpebaAbjlifpeboqlabpqolv.2-Ab`ljmlpbaDelrip)/-ColpqphriiJ^dbp^ka/?lkbDf^kqpfkqebS^iibvlcIlpqElmb%31+2)11&yyNFAy.0061y
QAlVlroTlopqyKyJ^qqef^pIbekbo%31+3)11&yyNFAy.0061y
>>ojvlcqebA^jkbayKyJ^qqef^pIbekbo%31+3)11&yyNFAy.0062y
@>ojvlcqebA^jkbayKyHfiiqebpliafbop^karpbqebO^fpbpmbiilkqeb`lombpqlo^fpb.--delripyyNFAy.0062y
Q>ojvlcqebA^jkbayKyJ^qqef^pIbekbo%31+3)11&yyNFAy.0062y
>CrqfifqvyKyJ^qqef^pIbekbo%31+3)11&yyNFAy.0063y

@Mlhb^kaMolayNFAy.0/54yyKyHfii2Erihfkd>_ljfk^qflkp)2J^ibcf`Kb`olj^k`bop)^ka2Pe^alt>abmqp^olrka%36)32&y
@?looltbaQb`eklildvyKyMf`hrmqeb0l_gb`qpp`^qqboba^olrkaqeb^ob^%36)33&XMfiblc?lkbpZ)X>_^kalkbaEbijZ)^kaX>_^kalkba>ojloZ)dbq0lcb^`elcqebj^kaqebkrpbqebXPjrddibaPlirqflkZnrbpqfqbj0qfjbp+yyRy11-15yyNFAy.0/6.y

OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&yyNFAy.0064y
QCrqfifqvyKyJ^qqef^pIbekbo%31+3)11&yyNFAy.0063y
QMlhb^kaMolayNFAy.0/54yyKyQe^pp^of^klkQebPhv_ob^hboy
Q?looltbaQb`eklildvyKy@efbcBkdfkbbo?liqtobk`elkQebPhv_ob^hboyyNFAy.0/6.y
>Pfkao^dlp^$pC^iiyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0064y
>Qe^q$p>_ljfk^_ibyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0/55y
>>d^fkpqqebDf^kqpyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0/61y
>TebobAo^dlkpCbiiyKyJ^qqef^pIbekbo%4.+3)04+3&yyNFAy.0065y
@TebobAo^dlkpCbiiyKy@liib`q3uXTebim?lkbArpqpZaolmmba_vColpq_ollaTebim%4/+4)1-+2&yyNFAy.0065y
@Pfkao^dlp^$pC^iiyKyPi^v2TvojOb^kfj^qlop)5@riqfpq@loormqbop^ka0SovhriKb`oliloap^qPfkao^dlp^$pC^ii%4/)1/&yyNFAy.0064y
QTebobAo^dlkpCbiiyKyJ^qqef^pIbekbo%4.+3)04+3&yyNFAy.0065y
>Qfjbclo>kptbopyKyJ^qqef^pIbekbo%4.+3)04+3&yyNFAy.0066y
@>d^fkpqqebDf^kqpyKy0j^kdolrmnrbpqmobqqvb^pvqlplil)qefpnrbpqe^pvlrhfiiMrpqri^kqEloolopclrka^iilsboqebqlmlcJloa$obqe^o^olrka%32)26&^kalkqebFolkt^iiA^j^olrka%4-)4/&yyNFAy.0/44y
@Qe^q$p>_ljfk^_ibyKyHfii^Erihfkd>_ljfk^qflk%35)30&^ka`liib`q^X@efiiba>_ljfk^qflkDrqpZqebkrpbqebX>_ljfk^qflkOb^kfj^qflkHfqZqlprjjlk^k>_ljfk^qflkrpbfqql_iltrmqebdelrip+Alk$qbumilabtefibqebdelrip^obpqrkkbalobipbvlrtlk$qdbq^kv`obafq+Vlr`^k^iplqovjlrkqfkdrm^cqboprjjlkfkdqeb>_ljfk^qflkyyNFAy.0/55yyRy10635y
QQfjbclo>kptbopyKyQ^ihqlJ^qqef^pIbekbo^qqeb@lroqlc?lkbp%16+/)40+/&yyNFAy.0066y
>QebErkqbo^kaqebMofk`byKyJ^qqef^pIbekbo%16+/)40+/&yyNFAy.01--y
@QebErkqbo^kaqebMofk`byKyIllhclo^?illapq^fkbaPqlkb%15+02)4/+50&^kaofdeq`if`hlkfqql_b`ljb>oqe^p)abcb^qFiifa^kql`ljmibqbqebnrbpq+Hbbmmobppfkd.rkqfivlre^sb^_lrq3-"j^k^qebkmobpp0qebk1qlhf`h^kaal^ib^m^qq^`h)obmb^qqefprkqfiebafbpyyNFAy.01--y
QQebErkqbo^kaqebMofk`byKyJ^qqef^pIbekbo%16+/)40+/&yyNFAy.01--y
>Hkltibadbfp^Qboof_ib?roabkyKyJ^qqef^pIbekbo%16+/)40+/&yyNFAy.01-.y

OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&yyNFAy.00.2y
QQe^q$p>_ljfk^_ibyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0/55y
QPfkao^dlp^$pC^iiyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0064y
QHkltibadbfp^Qboof_ib?roabkyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.01-.y
Q>d^fkpqqebDf^kqpyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0/44y
>Pkb^hMobsfbtyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.00.2y
>Qfoflk$pEbimyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.01-/y
>?^pf`@ebjfpqovyNFAy.0/62y
>@lmolrpqebAbcfibayNFAy.0/65y

>HfiileboqwyKy@efbcBkdfkbbo?liqtobk`elkQebPhv_ob^hboyyNFAy.0050y
@Pkb^hMobsfbtyKySfpfqqeb^ob^>iaro$qe^oPlrqe7%21)11&>iaro$qe^o@bkqo^i7%21)1-&>iaro$qe^oKloqe7%21)01&>iaro$qe^oKloqetbpq7%2.)00&yyNFAy.00.2y
QHfiileboqwyKyHf_ifHfiileboqw%21)1/+6&yyNFAy.0050y
>Ib^afkdqeb@e^odbyKyHf_ifHfiileboqw%21)1/+6&yyNFAy.005-y
@Ib^afkdqeb@e^odbyKyRpbqebSbef`ib)Qebsbef`ibe^p0jlabptef`e^ob`lkqoliiba_vqeb_rqqlkp12^ka3+Jlab.%hbv1&fp>kqf*>fo+Rpbqefpqlpellqaltkqebd^odlvibp+Jlab/%hbv2&fp_lj_fkd+Rpbqefpql_lj_qebdolrkaq^odbqp+Jlab0%hbv3&fpobm^fojlab+Rpbqefpql`e^odbvlropefbia^kamrqlrqcfobp+yyNFAy.005-y
QIb^afkdqeb@e^odbyKyHf_ifHfiileboqw%21)1/+6&yyNFAy.005-y
>Pq^qf`Pel`hQollmp7qeb?lj_^oajbkqyKyHf_ifHfiileboqw%21)1/+6&yyNFAy.01-1y
@Pq^qf`Pel`hQollmp7qeb?lj_^oajbkqyKyJlrkqqeb_lj_bo^kahfii?lj_^oajbkqFkc^kqov)?lj_^oajbkq@^mq^fkp^kaD^odlvib>j_rpebopyyNFAy.01-1y
QPq^qf`Pel`hQollmp7qeb?lj_^oajbkqyKyHf_ifHfiileboqw%21)1/+6&yyNFAy.01-1y
>MrqqfkdqebEboqw7QebS^iibvlcIlpqElmbyKyHf_ifHfiileboqw%21)1/+6&yyNFAy.005/y
@MrqqfkdqebEboqw7QebS^iibvlcIlpqElmbyKyJlrkqqeb_lj_bo^kahfii?lj_^oajbkqFkc^kqov)D^odlvib>j_rpebop)Colpq_ollaPbkqofbp^kaP`lrodbT^oJ^`efkbpyyNFAy.005/y
QMrqqfkdqebEboqw7QebS^iibvlcIlpqElmbyKyHf_ifHfiileboqw%21)1/+6&yyNFAy.005/y

QQfoflk$pEbimyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyNFAy.01-/y
>Qfoflk$pD^j_fqyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyNFAy.01-0y
H@riqfpq>`livqbyKyHfii^@riqfpq>`livqb^q%12)45&qll_q^fk^X@riqfpq>`livqb$pEllaZyyIy11451yyNFAy.01-0y
@Qfoflk$pD^j_fqyKyRpbqebX@riqfpq>`livqb$pEllaZ^kaq^ihqlQfoflk%11+1)43+/&^kaqebbsbkqtfiipq^oqyyRy11451yyNFAy.01-0y
QQfoflk$pD^j_fqyKyEfdeiloaQfoflkCloaofkd%46+5)4.+5&yyNFAy.01-0y

OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&yyNFAy.00.5y
QPkb^hMobsfbtyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.00.2y

>Ao^d^kaAolmyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.00.5y
>@e^fklc@ljj^kayKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.00.6y
>@^kklqObmolar`byKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.00/-y
@@^kklqObmolar`byKyRpbqebXM^oqfqflkbaCi^phZlkqeb`^riaolkp^q%16)00&yyRy11/2.yyNFAy.00/-y
HLsbopbboP^sovkyKyHfiiLsbopbboP^sovk%16)0.&yyNFAy.00.6yyNLyLsbopbboP^sovkHfiiba7.,.y
HLsbopbboGe^bnrlkyKyHfiiLsbopbboGe^bnrlk%22)00&yyNFAy.00.6yyNLyLsbopbboGe^bnrlkHfiiba7.,.y
HLsbopbboSbo^gyKyHfiiLsbopbboSbo^g%21)/6&yyNFAy.00.6yyNLyLsbopbboSbo^gHfiiba7.,.y
@@e^fklc@ljj^kayKyHfiiLsbopbboC^baofp%21)14&yyNFAy.00.6y
@Ao^d^kaAolmyKyDlPlrqelcqeb_ofadb^olrka%20)13&)hfiiqebjl_pqebobcloqebLo_lcFiirpflknrbpqfqbjvlrkbba)qebkqeoltfq^qqebA^ohPr_grd^qlopcolj^afpq^k`btefiblrqlc`lj_^q+yyRy11/13yyNFAy.00.5y

OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&yyNFAy.001/y
QAo^d^kaAolmyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.00.5y
Q@e^fklc@ljj^kayKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.00.6y
>Klq^?rdyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.001/y
>KbbaJlobFkclyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0012y
Q@^kklqObmolar`byKy@efbcBkdfkbbo?liqtobk`elkQebPhv_ob^hboyyNFAy.00/-y
>ObqbpqKltyKy@efbcBkdfkbbo?liqtobk`elkQebPhv_ob^hboyyNFAy.00/.y
RAofkhRmyKyRpbXAfirqba@riqQlkf`ZyyRy110-4yyNFAy.0013y
@KbbaJlobFkclyKyDlqlqebbkqo^k`b^q%2.+6)0/+.&^kahfiiqeb@riqObpb^o`eboprkqfivlrcfka0m^dbplc@riqfpqp$Obpb^o`eyyNFAy.0012yyRy11126y
HHbbmHfiifkd+++yKyHfii@riqKM@p%16)00&^ka`liib`q.-uXQ^fkqbaBppbk`bZyyIy110-..-yyNFAy.00/.y
R@ob^qbXTofqefkdJ^ppZyKyOfdeq`if`hlkXQ^fkqbaBppbk`bZyyRy110-.yyNFAy.0013y
@ObqbpqKltyKyRpbqebXQ^fkqbaBppbk`bZql`lj_fkbaqebjfkql^XTofqefkdJ^ppZ^kaofdeq`if`hlk^`^riaolk^q%16)01&)A^oh@^riaolk7>qq^`hMltbo)?irb@^riaolk7Pmbiimltbo)Dobbk@^riaolk7Pq^jfk^yyRy110-1yyNFAy.00/.y
HBkpi^sbaJfkflkpyKyHfiiBkpi^sbaJfkflkp%22)/6&qebkrpbXOlalcPfmelkfkdZql`liib`q2uXA^ohJ^qqboZyyRy11100yyIy111012yyNFAy.0032y
@Klq^?rdyKyLk`bvlre^sb`liib`qba2uXA^ohJ^qqboZofdeq`if`hlkqebMromibPrjjlkfkdPqlkb^q%20)00&yyNFAy.0032y

OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&yyNFAy.0013y
QKlq^?rdyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.001/y
QKbbaJlobFkclyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0012y

>KlObpqCloQebTf`hbayKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0013y
>O^fpbqeb?^oof`^abpyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.000/y
QObqbpqKltyKy@efbcBkdfkbbo?liqtobk`elkQebPhv_ob^hboyyNFAy.00/.y

@O^fpbqeb?^oof`^abpyKyDlql%2/)1-&^kaillhcloqebMromibj^ohbop^karpbqebX?^oof`^ab@lkpqor`qflkHfqZyyRy11./4yyNFAy.000/y
OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&yyNFAy.0001y
QO^fpbqeb?^oof`^abpyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.000/y
>?illapm^qqboba?^kkbopyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0001y
>DbqqebJbpp^dbyKyEfde@^mq^fkGrpqfk?^oqibqqlkQebPhv_ob^hboyyNFAy.00.1y
@?illapm^qqboba?^kkbopyKyHfii^P`lrodb?^kkbo*?b^obocfopq%10+5)23+3&qltb^hbkqeb@lksboqbaEbol)^kahfii2uP`lrodb@lksboqbo%14+5)1-+/&yyNFAy.0001yyRy11///y
@DbqqebJbpp^dbyKyRpbXA^oqDrkZql`^mqrob3Lodofj$pE^jjboAfpm^q`e^olrka%15)21&yyRy11///yyNFAy.00.1y
OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&y
Q?illapm^qqboba?^kkbopyKyQe^pp^of^klkQebPhv_ob^hboyyNFAy.0001y
QDbqqebJbpp^dbyKyEfde@^mq^fkGrpqfk?^oqibqqlkQebPhv_ob^hboyyNFAy.00.1y

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
