DugisGuideViewer:RegisterGuide("Cooking (65+ Dailies)", nil, "Horde", "D", function()
return [[
AAA

KMf`hrmA^fivNrbpqyKyMf`hrm^nrbpqcolj>tfilIlk$dlj_^%4-)05+3&fkA^i^o^kqf`hqefpl_gb`qfsb>CQBOvlrmf`hrmqebnrbpqyyWyA^i^o^ky

>PbtboPqbtyLyyKy>tfilIlk$dlj_^%4-)05+3&yyNFAy.0..1yyWyA^i^o^kyyAy
>@ebbpbcloDiltbodliayLyyKy>tfilIlk$dlj_^%4-)05+3&yyNFAy.0..2yyWyA^i^o^kyyAy
>@lksbkqflk^qqebIbdboabj^fkyLyyKy>tfilIlk$dlj_^%4-)05+3&yyNFAy.0..0yyWyA^i^o^kyyAy
>FkcrpbaJrpeolljJb^qil^cyLyyKy>tfilIlk$dlj_^%4-)05+3&yyNFAy.0../yyWyA^i^o^kyyAy
>Jrpq^oaAldpyLyyKy>tfilIlk$dlj_^%4-)05+3&yyNFAy.0..3yyWyA^i^o^kyyAy

@PbtboPqbtyLyyKy@liib`q1uX@ovpq^iplkd@^oolqZrkaboA^i^o^k)^q%0-+1)05+0&^karpbqebXPqbt@llhmlqZfqtfqe1X@efiibaJb^qZyyRy10.14yyNFAy.0..1yyWy@ovpq^iplkdClobpqyyAy
@@ebbpbcloDiltbodliayLyyKy@liib`q3uXE^icCriiDi^pplcTfkbZ%16)06&)%36+2)01+0&)%10)31&^kaXA^i^o^kIfj_bodboZ%20+2)0/+2&^olrkaA^i^o^kyyRy10.06yyNFAy.0..2yyWyA^i^o^kyyAy
@@lksbkqflk^qqebIbdboabj^fkyLyyKyDbqqebXCriiGrdlcTfkbZfkA^i^o^k%10+2)0/+4&^kaj^hblo_rv1uXKloqebokPqbtZtfqe1uX@efiibaJb^qZyyNFAy.0..0yyWyA^i^o^kyyAy
@FkcrpbaJrpeolljJb^qil^cyLyyKyCfkaqebXFkcrpbaJrpeolljZ^olrkaA^i^o^kPbtbop^karpbXJb^qil^cM^kZtfqe/uX@efiibaJb^qZyyRy10.-.yyNFAy.0../yyWyA^i^o^kyyAy
@Jrpq^oaAldpyLyyKyCfkaqebXTfiaJrpq^oaZ^olrkaA^i^o^kdo^pp^ob^%02)21&)%03)1/&)%16+1)14&)%14).3&)%35)12+3&^ka`ob^qblo_rv1uXOefklAldpZyyRy10.1/yyNFAy.0..3yyWyA^i^o^kyyAy

QPbtboPqbtyLyyKy>g^vDobbk%02+6)24+2&yyNFAy.0..1yyWyA^i^o^kyyAy
Q@ebbpbcloDiltbodliayLyyKyO^kfaDiltbodlia%03+2)/5+2&yyNFAy.0..2yyWyA^i^o^kyyAy
Q@lksbkqflk^qqebIbdboabj^fkyLyyKy>ofiib>wrobd^wb%15+2)05+.&yyNFAy.0..0yyWyA^i^o^kyyAy
QFkcrpbaJrpeolljJb^qil^cyLyyKyLoqlk?bkkbq%2/+.)22+2&yyNFAy.0../yyWyA^i^o^kyyAy
QJrpq^oaAldpyLyyKy>o`ej^dbMbkq^orp%35+2)1/+2&yyNFAy.0..3yyWyA^i^o^kyyAy

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
