DugisGuideViewer:RegisterGuide("Alchemy 1-450", nil, "Alliance", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-+Eltbsbo)vlr`^kpqfiirpbqefpdrfab^qiltboibsbip)vlr$iigrpqe^sbqlj^hbprobvlr^obefdebklrdeibsbiqljlsblkqlqebkbuqpqbm+y
KQo^fkbopyKyQebqo^fkbopifpqba^obqeblkbpfkPqlojtfka@fqv)EbiicfobMbkfkpri^^kaA^i^o^k+L_sflrpivvlr`^krpblqebop^pvlrpbbcfq+y

KQo^fk>mmobkqf`b>i`ebjvyKyIfivppf^Kfdeq_obbwb%22+3)52+6&+yyWyPqlojtfka@fqvyyMJy>i`ebjvy42y

K.*3-XJfkloEb^ifkdMlqflkZyKy3-uXMb^`b_illjZ)3-uXPfisboib^cZ)3-uXBjmqvSf^iZ+yyMy>i`ebjv3-y

KQo^fkGlrokbvj^k>i`ebjvyKIfivppf^Kfdeq_obbwb%22+3)52+6&+yyWyPqlojtfka@fqvyyMJy>i`ebjvy.2-y

K3-*6-XIbppboEb^ifkdMlqflkZyKy0-uXJfkloEb^ifkdMlqflkZ)0-uX?of^oqelokZ+yyMy>i`ebjv6-y
K6-*..-XBifufolcTfpaljZyKy/-uXJ^dbolv^i)1-uX?of^oqelokZ)/-uXBjmqvSf^iZ+yyMy>i`ebjv..-y

K..-*.1-XEb^ifkdMlqflkZyKy00-uX?orfpbtbbaZ)0-uX?of^oqelokZ)0-uXIb^abaSf^iZ+yyMy>i`ebjv.1-y
K.1-*.2-XIbppboJ^k^MlqflkZyKy.-uXJ^dbolv^iZ).-uXPqo^kdibhbimZ).-uXBjmqvSf^iZ+yyMy>i`ebjv.2-y

KQo^fkBumboq>i`ebjvyKyIfivppf^Kfdeq_obbwb%22+3)52+6&+yyWyPqlojtfka@fqvyyMJy>i`ebjvy//2y

K.2-*.22XPqolkdQolii$p?illaMlqflkZyKy.-uX?orfpbtbbaZ).-uX?of^oqelokZ)2uXIb^abaSf^iZ+yyMy>i`ebjv.22y
K.22*.5-XDob^qboEb^ifkdMlqflkZyKy.2uXIfcbollqZ).2uXHfkdp_illaZ).2uXIb^abaSf^iZ+yyMy>i`ebjv.5-y
K.5-*.52XJ^k^MlqflkZyKy2uXPqo^kdibhbimZ)2uXHfkdp_illaZ)2uXIb^abaSf^iZ+yyMy>i`ebjv.52y
K.52*/-2XBifufolc>dfifqvZyKy/-uXPqo^kdibhbimZ)/-uXDliaqelokZ)/-uXIb^abaSf^iZ+yyMy>i`ebjv/-2y
K/-2*/.2XBifufolcDob^qboAbcbkpbZyKy.-uXTfiaPqbbi_illjZ).-uXDliaqelokZ).-uXIb^abaSf^iZ+yyMy>i`ebjv/.2y

KQo^fk>oqfp^k>i`ebjvyKyIfivppf^Kfdeq_obbwb%22+3)52+6&+yyWyPqlojtfka@fqvyyMJy>i`ebjvy0--y

K/.2*/0-XPrmbofloEb^ifkdMlqflkZyKy.2uXPrkdo^ppZ).2uXHe^ad^o$pTefphboZ).2uX@ovpq^iSf^iZ+yyMy>i`ebjv/0-y
K/0-*/2-XBifufolcAbqb`qRkab^aZyKy/-uX>oqe^p$Qb^opZ)/-uX@ovpq^iSf^iZ+yyMy>i`ebjv/2-y
K/2-*/3-XBifufolcDob^qbo>dfifqvZyKy.-uXPrkdo^ppZ).-uXDliaqelokZ).-uX@ovpq^iSf^iZ+yyMy>i`ebjv/3-y
K/3-*/32XBifufolcAbqb`qAbjlkZyKy.-uXDoljp_illaZ)2uX@ovpq^iSf^iZ+yyMy>i`ebjv/32y
K/32*/42XPrmbofloJ^k^MlqflkZyKy/-uXPrkdo^ppZ)/-uX?ifkatbbaZ).-uX@ovpq^iSf^iZ+yyMy>i`ebjv/42y
K/42*0--XJ^gloEb^ifkdMlqflkZyKy0-uXDliabkP^kp^jZ).2uXJlrkq^fkPfisbop^dbZ).2uX@ovpq^iSf^iZ+yyMy>i`ebjv0--y

KQo^fkJ^pqbo>i`ebjvyKy>i`ebjfpqDof__ib%06+5)15+0&+yyWyEbiicfobMbkfkpri^yyMJy>i`ebjvy042y

K0--*0.2XSli^qfibEb^ifkdMlqflkZyKy.2uXDliabkP^kp^jZ).2uXCbitbbaZ).2uXFj_rbaSf^iZ+yyMy>i`ebjv0.2y
K0.2*0/2XBifufolcEb^ifkdMltboZyKy.-uXDliabkP^kp^jZ).-uXAob^jfkdDilovZ).-uXFj_rbaSf^iZ+yyMy>i`ebjv0/2y
K0/2*002XJ^a>i`ebjfpq$pMlqflkZyKy/-uXO^dsbfiZ).-uX@ovpq^iSf^iZ+yyMy>i`ebjv002y
K002*01-XPrmboEb^ifkdMlqflkZyKy.-uXKbqebo_illjZ)2uXCbitbbaZ)2uXFj_rbaSf^iZ+yyMy>i`ebjv01-y

?XOb`fmb7PrmboJ^k^MlqflkZyKyE^^iork%34+5)15+-&+yyWyW^kd^oj^opeyyIy//6-4yyMy>i`ebjv02-y

K01-*02-XPrmboJ^k^MlqflkZyKy/-uXAob^jfkdDilovZ).-uXCbitbbaZ).-uXFj_rbaSf^iZ+yyMy>i`ebjv02-y

OEltifkdCgloa
KQo^fkJ^pqbo>i`ebjvyKyI^klifpAbtaolm%25+1)3/+0&+yyWyEltifkdCgloayyMJy>i`ebjvy12-y

K02-*03-XObprodbkqEb^ifkdMlqflkZyKy/-uXDlia`ilsboZ).-uXFj_rbaSf^iZ+yyMy>i`ebjv03-y
K03-*032XTo^qeBifufoZyKy.-uXAb^akbqqibZ)2uXDlia`ilsboZ)2uXFj_rbaSf^iZ+yyMy>i`ebjv032y
K032*042XPmbiimltboBifufoZyKy/-uXDlia`ilsboZ).-uXQfdboIfivZ).-uXFj_rbaSf^iZ+yyMy>i`ebjv042y
K042*05-XMvdjvLfiZyKy2uXMvdjvPr`hbocfpeZ+yyMy>i`ebjv05-y
K05-*052XMlqflklcKfdeqj^obpZyKy2uXDlia`ilsboZ).-uXQ^i^kao^$pOlpbZ)2uXFj_rbaSf^iZ+yyMy>i`ebjv052y
K052*06-XBifufolcJfdeqvPqobkdqeZyKy.-uXQfdboIfivZ)2uXFj_rbaSf^iZ+yyMy>i`ebjv06-y
K06-*062XBifufolcJfdeqvCloqfqrabZyKy/-uXDlia`ilsboZ)2uXFj_rbaSf^iZ+yyMy>i`ebjv062y
K062*1--XFkabpqor`qf_ibMlqflkZyKy.-uXF`bqelokZ)2uXFj_rbaSf^iZ+yyMy>i`ebjv1--y

KQo^fkKloqeobka>i`ebjvObpb^o`eyKy^karpbfqqlafp`lsbokbtob`fmbpbsbov/a^vp/-elrop+y

K1--*1.2XFkabpqor`qf_ibMlqflkZyKy0-uXF`bqelokZ).2uXFj_rbaSf^iZ+yyMy>i`ebjv1.2y

K1.2*1.3X>i`ebjfpqPqlkbZyKyJ^hb.Fkabpqor`qf_ib)Jbo`rof^i)LOJfdeqv>i`ebjfpqPqlkb+Hbbmqefp)^pfq`lrkqp^p^qo^kpjrqbpqlkb+yyMy>i`ebjv1.3y

K1.3*1/2Vlro@elf`byKyJ^hb^kvmlqflklobifufoqe^qfpvbiiltyyMy>i`ebjv1/2y
K1/2*102XQo^kpjrqb7B^oqepfbdbAf^jlkaZyKy.-uXA^ohg^abZ).-uXErdb@fqofkbZ).-uXBqbok^iCfobZ+yyMy>i`ebjv102y
K102*12-Ci^phpyKyJ^hbCi^phpqlibsbi12-+Qebpb`^k_bpliafkqeb>E+yyMy>i`ebjv12-y

KDrfab@ljmibqb
]]
end)
