DugisGuideViewer:RegisterGuide("Cooking 1-450", nil, "Alliance", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-+Eltbsbo)vlr`^kpqfiirpbqefpdrfab^qiltboibsbip)vlr$iigrpqe^sbqlj^hbprobvlr^obefdebklrdeibsbiqljlsblkqlqebkbuqpqbm+y
KQo^fkbopyKyQebqo^fkbopifpqba^obqeblkbpfkPqlojtfka@fqv)EbiicfobMbkfkpri^^kaA^i^o^k+L_sflrpivvlr`^krpblqebop^pvlrpbbcfq+y
KKlqbyKyVlrklilkdbokbbapfjmibtllalocifkqqlpq^oq^cfob+Fcvlr^obfk^`fqvlosfii^db)^ilqlcqfjbpqebcfobpqe^qqebve^sb_rokfkdtfiiprccf`bclo`llhfkdvlrojb^q)lqebotfpbrpbvlropq^oqcfobphfiiql_rfia^`llhfkdcfob+y

OPqlojtfka@fqvyKyPq^oqfkPqlojtfka+yyMy@llhfkd02y
KQo^fk>mmobkqf`b@llhfkdyKyPqbmebkOv_^`h%45+.)20+/&yyWyPqlojtfka@fqvyyMJy@llhfkdy42y

K.*02XPmf`b?ob^aZyKy1-uXPfjmibCilroZ)1-uXJfiaPmf`bZ+yyMy@llhfkd02y
K02*2-XPmf`baTlicJb^qZyKy.2uXPqofkdvTlicJb^qZ+yyMy@llhfkd2-y
K2-*42XPjlhba?b^oJb^qZloXOl^pqbaHlalJb^qZyKy/2uX?b^oJb^qZlo/2uXHlalJb^qZ+yyMy@llhfkd42y

KQo^fkGlrokbvj^k@llhfkdyKyPqbmebkOv_^`h%45+.)20+/&yyWyPqlojtfka@fqvyyMJy@llhfkdy.2-y

K42*.-2X?lfiba@i^jpZyKy0-uX@i^jJb^qZ)0-uXObcobpefkdPmofkdT^qboZ+yyMy@llhfkd.-2y
K.-2*.0-X@o^_@^hbZyKy/2uX@o^tiboJb^qZ+yyMy@llhfkd.0-y

KQo^fkBumboq@llhfkdyKyPqbmebkOv_^`h%45+.)20+/&yyWyPqlojtfka@fqvyyMJy@llhfkdy//2y

?XOb`fmb7@roflrpivQ^pqvLjbibqZyKyHbkaloH^_lkh^%44+2)20+2&+yyWyPqlojtfka@fqvyyIy035/yyMy@llhfkd.42y
O>o^qefEfdei^kapyMy@llhfkd//2y
?XOb`fmb7Ol^pqO^mqloZyKyE^jjlkH^otk%13+2)14+0&+yyWy>o^qefEfdei^kapyyIy.///5yyMy@llhfkd//2y

K.0-*.42X@roflrpivQ^pqvLjbibqZyKy12uXO^mqloBddZ+yyMy@llhfkd.42y
K.42*//2XOl^pqO^mqloZyKy2-uXO^mqloCibpeZ+yyMy@llhfkd//2y

KQo^fk>oqfp^k@llhfkdyKyPqbmebkOv_^`h%45+.)20+/&yyWyPqlojtfka@fqvyyMJy@llhfkdy0--y

OCbitllayMy@llhfkd/52y
?XOb`fmb7JlkpqboLjbibqZyKyJ^ivdbk%3/+0)/2+4&+yyWyCbitllayyIy.3..-yyMy@llhfkd/2-y
?XOb`fmb7Grf`v?b^o?rodboZyKyJ^ivdbk%3/+0)/2+4&+yyWyCbitllayyIy02233yyMy@llhfkd/52y

K//2*/2-XJlkpqboLjbibqZyKy/2uXDf^kqBddZ+yyMy@llhfkd/2-y
K/2-*/52XGrf`v?b^o?rodboZyKy02uX?b^oCi^khZ+yyMy@llhfkd/52y

C@bk^oflkEliayKyCivloorkql@bk^oflkElia%2-+-)02+0&+yyWyPfifqerpyyMy@llhfkd0--y
>AbpboqOb`fmbyKy@^i^kao^qe%2.+6)06+.&+yyNFAy50-4yyWyPfifqerpy
QAbpboqOb`fmbyKyP^kav@llh_llh%05+-)12+0&+yyNFAy50-4yyWyPfifqerpy
>Pe^ofkdqebHkltibadbyKyP^kav@llh_llh%05+-)12+0&+yyNFAy50.0yyWyPfifqerpy
QPe^ofkdqebHkltibadbyKy?ofkdqebQlokOb`fmbM^dbql@^i^kao^qe^qqebfkkfk@bk^oflkElia+%05+-)12+0&+yyNFAy50.0yyWyPfifqerpy

K/52*0--XPjlhbaAbpboqArjmifkdZyKy.2uXP^katlojJb^qZ+yyMy@llhfkd0--y

OEbiicfobMbkfkpri^yMy@llhfkd0/2y
KQo^fkJ^pqbo@llhfkdyKyD^pqlk%21+.)30+2&+yyWyEbiicfobMbkfkpri^yyMJy@llhfkdy042y
?XOb`fmb7O^s^dboAldZyKyPfaIfj_^oaf%21+0)30+2&+yyWyEbiicfobMbkfkpri^yyIy/4355yyMy@llhfkd0/2y
K0--*0/2XO^s^dboAldZyKy/2uXO^s^dboCibpeZ+yyMy@llhfkd0/2y

OK^do^kayMy@llhfkd02-y
?XOb`fmb7Ol^pqba@ibcqellcZyKyRofhr%23+/)40+0&+yyWyK^do^kayyIy/436.yyMy@llhfkd02-y
K0/2*02-XOl^pqba@ibcqellcZyKy/2uX@ibcqellcJb^qZ+yyMy@llhfkd02-y

OEltifkdCgloayMy@llhfkd1--y
KQo^fkDo^kaJ^pqbo@llhfkdyKy?olj?obt_^pqbo%25+/)3/+.&+yyWyEltifkdCgloayyMJy@llhfkdy12-y

>Kloqebok@llhfkdyKy?olj?obt_^pqbo%25+/)3/+.&+yyNFAy.0-54yyWyEltifkdCgloay
@Kloqebok@llhfkdyKy?ofkdclroX@efiibaJb^qZql?olj?obt_^pqbo+X@efiibaJb^qZ`^k_bclrkalk^kvKloqeobka_b^pq+yyNFAy.0-54yyWyEltifkdCgloay
QKloqebok@llhfkdyKy?olj?obt_^pqbo%25+/)3/+.&+yyNFAy.0-54yyWyEltifkdCgloay

K02-*032XKloqebokPqbtZyKy.2uX@efiibaJb^qZ+yyMy@llhfkd032y
K032*042XOefklAldpZyKy.-uXOefklJb^qZ+yyMy@llhfkd042y
K042*1--XDob^qCb^pqZyKy/2uX@erkhl$J^jjlqeZ)/2uXPelsbiqrphCi^khZ)/2uXTlojJb^qZ)2-uX@efiibaJb^qZ+yyMy@llhfkd1--y

K1--*12-Mi^vbo$p@elf`byKyRmql12-)ob`fmbp^ob_lrdeqrpfkdXA^i^o^k@llhfkdObt^oaZptef`evlrdbqcolj`ljmibqfkdqeb@llhfkdA^fifbp+?rvob`fmbpqe^q^ob^qib^pqvbiiltphfiiibsbi+yyMy@llhfkd12-y
KDrfab@ljmibqb

]]
end)
