DugisGuideViewer:RegisterGuide("Engineering 1-450", nil, "Alliance", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-+Eltbsbo)vlr`^kpqfiirpbqefpdrfab^qiltboibsbip8vlr$iigrpqe^sbqlj^hbprobvlr^obefdebklrdeibsbiqljlsblkqlqebkbuqpqbm+y
KQo^fkbopyKyQebqo^fkbopifpqba^obqeblkbpfkPqlojtfka@fqv)EbiicfobMbkfkpri^^kaA^i^o^k+L_sflrpivvlr`^krpblqebop^pvlrpbbcfq+y

KQo^fk>mmobkqf`bBkdfkbbofkdyKyIfiif^jPm^ohpmfkaib%3/+/)0-+1&+yyWyPqlojtfka@fqvyyMJyBkdfkbbofkdy42y

?X?i^`hpjfqeE^jjboZyKyX?i^`hpjfqeE^jjboZplia^qKM@kb^oqo^fkbo+yyIy2623y
K.*/-XOlrde?i^pqfkdMltaboZyKy/-uXOlrdePqlkbZ+Hbbmqebpb+yyMyBkdfkbbofkd/-y
K/-*0-XOlrdeAvk^jfqbZyKy/-uXOlrde?i^pqfkdMltaboZ)/-uXIfkbk@ilqeZ+yyMyBkdfkbbofkd0-y
K0-*2-XE^kacrilc@lmmbo?liqpZyKy.uX@lmmbo?^oZ+Hbbmqebpb+yyMyBkdfkbbofkd2-y
K2-*2.X>o`ifdeqPm^kkboZyKy3uX@lmmbo?^oZ+Hbbmqefp+yyMyBkdfkbbofkd2.y
K2.*42X@lmmboQr_bZyKy15uX@lmmbo?^oZ)/1uXTb^hCiruZ+Vlr`^kpbiiqebpblorpbqebjqlj^hbXAb^aiv?irkabo_rppZ)tef`efpkbbabaclo^Eloabnrbpqfk>pebks^ib+yyMyBkdfkbbofkd42y

KQo^fkGlrokbvj^kBkdfkbbofkdyKyIfiif^jPm^ohpmfkaib%3/+/)0-+1&+yyWyPqlojtfka@fqvyyMJyBkdfkbbofkdy.2-y

K42*52X@l^opb?i^pqfkdMltaboZyKy.2uX@l^opbPqlkbZ+Hbbmqebpb+yyMyBkdfkbbofkd52y
K52*6-X@l^opbAvk^jfqbZyKy.2uX@l^opb?i^pqfkdMltaboZ)2uXIfkbk@ilqeZ+yyMyBkdfkbbofkd6-y
K6-*.--X@lmmboJlari^qloZyKy.-uX@lmmbo?^oZ)/-uXE^kacrilc@lmmbo?liqpZ)/-uXIfkbk@ilqeZ+yyMyBkdfkbbofkd.--y
K.--*.-2XMo^`qf`bIl`hZyKy2uX?olkwb?^oZ).-uXE^kacrilc@lmmbo?liqpZ)2uXTb^hCiruZ+yyMyBkdfkbbofkd.-2y
K.-2*./-X?olkwbQr_bZyKy0-uX?olkwb?^oZ).2uXTb^hCiruZ+Hbbm2lcqebpb+yyMyBkdfkbbofkd./-y
K./-*./2XPq^ka^oaP`lmbZyKy2uX?olkwbQr_bZ)2uXJlpp>d^qbZ+yyMyBkdfkbbofkd./2y
K./2*.1-XEb^sv?i^pqfkdMltaboZyKy.uXEb^svPqlkbZ+Hbbmqebpb)vlr^obdlfkdqlkbba1-i^qbo+yyMyBkdfkbbofkd.1-y
K.1-*.2-XTefoofkd?olkwbDfwjlZyKy/-uX?olkwb?^oZ).-uXTlli@ilqeZ+Hbbmqebpb)vlr^obdlfkdqlkbba/-i^qbo+yyMyBkdfkbbofkd.2-y

KQo^fkBumboqBkdfkbbofkdyKyIfiif^jPm^ohpmfkaib%3/+/)0-+1&+yyWyPqlojtfka@fqvyyMJyBkdfkbbofkdy//2y

K.2-*.22X?olkwbCo^jbtlohZyKy.-uX?olkwb?^oZ)2uXJbafrjIb^qeboZ)2uXTlli@ilqeZ+yyMyBkdfkbbofkd.22y
K.22*.4-XBumilpfsbPebbmZyKy/-uX?olkwbCo^jbtlohZ)/-uXTefoofkd?olkwbDfwjlZ)1-uXEb^sv?i^pqfkdMltaboZ)1-uXTlli@ilqeZ+yyMyBkdfkbbofkd.4-y
K.4-*.42XDvol`eolk^qljZyKy2uXFolk?^oZ)2uXDliaMltbo@lobZ+Hbbmqebpb+yyMyBkdfkbbofkd.42y
K.42*.43XDvolj^qf`Jf`ol*>agrpqloZyKy1uXPqbbi?^oZ+Lkivkbbalkb+Hbbmqefp+yyMyBkdfkbbofkd.43y
K.43*.62XPlifa?i^pqfkdMltaboZyKy1-uXPlifaPqlkbZ+Hbbmqebpb+yyMyBkdfkbbofkd.62y
K.62*/--XJfqeofiQr_bZyKy.-uXJfqeofi?^oZ+yyMyBkdfkbbofkd/--y
K/--*/.-XRkpq^_ibQofddboZyKy.-uXJfqeofi?^oZ).-uXJ^dbtb^sb@ilqeZ).-uXPlifa?i^pqfkdMltaboZ+Hbbmqebpb+yyMyBkdfkbbofkd/.-y
K/.-*//-XDl_ifkI^kaJfkbZyKy/-uXFolk?^oZ)0-uXPlifa?i^pqfkdMltaboZ).-uXDvol`eolk^qljZ+yyMyBkdfkbbofkd//-y

KQo^fk>oqfp^kBkdfkbbofkdyKyIfiif^jPm^ohpmfkaib%3/+/)0-+1&+yyWyPqlojtfka@fqvyyMJyBkdfkbbofkdy0--y

K//-*/02XJfqeofi@^pfkdZyKy3-uXJfqeofi?^oZ+yyMyBkdfkbbofkd/02y
K/02*/2-XEf*Bumilpfsb?lj_ZyKy/-uXJfqeofi@^pfkdZ).-uXRkpq^_ibQofddboZ)/-uXPlifa?i^pqfkdMltaboZ+yyMyBkdfkbbofkd/2-y
K/2-*/3-XAbkpb?i^pqfkdMltaboZyKy1-uXAbkpbPqlkbZ+yyMyBkdfkbbofkd/3-y
K/3-*/52XQelofrjTfadbqZyKy42uXQelofrj?^oZ)/2uXOrkb`ilqeZ+yyMyBkdfkbbofkd/52y
K/52*0--XQelofrjQr_bZyKy6-uXQelofrj?^oZ+yyMyBkdfkbbofkd0--y

KQo^fkJ^pqboBkdfkbbofkdyKyIb_ltphf%22+4)32+2&+yyWyEbiicfobMbkfkpri^yyMJyBkdfkbbofkdy042y

K0--*0.-XE^kacrilcCbiFolk?liqpZyKy.-uXCbiFolk?^oZ+yyMyBkdfkbbofkd0.-y
K0.-*0.2XBibjbkq^i?i^pqfkdMltaboZyKy2uXJlqblcCfobZ).-uXJlqblcB^oqeZ+yyMyBkdfkbbofkd0.2y
K0.2*0/-XCbiFolk@^pfkdZyKy.2uXCbiFolk?^oZ+yyMyBkdfkbbofkd0/-y
K0/-*0/2XCbiFolkJrphbqZyKy0-uXE^kacrilcCbiFolk?liqpZ).2uXCbiFolk@^pfkdZ)2uXEb^svPql`hZ+yyMyBkdfkbbofkd0/2y
K0/2*002X>a^j^kqfqbDobk^abZyKy1-uX>a^j^kqfqb?^oZ)/-uXE^kacrilcCbiFolk?liqpZ).-uXBibjbkq^i?i^pqfkdMltaboZ+yyMyBkdfkbbofkd002y
?XP`ebj^qf`7TefqbPjlhbCi^obZyKy?rvcoljTfkaQo^aboI^qeo^f%4/+2)0-+3&clo3dliafkPe^qqo^qe+yyIy/05..yyWyPe^qqo^qe@fqvyyMyBkdfkbbofkd01-y
K002*01-XTefqbPjlhbCi^obZyKy2uXBibjbkq^i?i^pqfkdMltaboZ)2uXKbqebotb^sb@ilqeZ+yyMyBkdfkbbofkd01-y
K01-*02-XCbipqbbiPq^_fifwboZyKy/-uXCbipqbbi?^oZ+yyMyBkdfkbbofkd02-y

KQo^fkDo^kaJ^pqboBkdfkbbofkdyKyQfjlcbvLpebkhl%05+6)/2+1&+yyWyA^i^o^kyyMJyBkdfkbbofkdy12-y

K02-*04-XE^kacrilc@l_^iq?liqpZyKy1-uX@l_^iq?^oZ+yyMyBkdfkbbofkd04-y
K04-*042XSli^qfib?i^pqfkdQofddboZyKy.2uX@l_^iq?^oZ)2uX@ovpq^iifwbaT^qboZ+yyMyBkdfkbbofkd042y
K042*052XLsbo`e^odba@^m^`fqloZyKy1-uX@l_^iq?^oZ).-uX@ovpq^iifwbaB^oqeZ+yyMyBkdfkbbofkd052y
K052*06-XBumilpfsbAb`lvZyKy.2uXSli^qfib?i^pqfkdQofddboZ)2uXColpqtb^sb@ilqeZ+yyMyBkdfkbbofkd06-y
K06-*1--XColpqpqbbiQr_bZyKy5-uX@l_^iq?^oZ).-uX@ovpq^iffwbaT^qboZ+yyMyBkdfkbbofkd1--y
K1--*1-2XAf^jlka*`rqObco^`qloP`lmbZyKy2uXColpqpqbbiQr_bZ).-uXE^kacrilc@l_^iq?liqpZ+yyMyBkdfkbbofkd1-2y
K1-2*1.2X?lulc?lj_pZyKy3-uXP^olkfqb?^oZ)./uXSli^qfib?i^pqfkdQofddboZ+yyMyBkdfkbbofkd1.2y
K1.2*1/2XJ^k^Fkgb`qloHfqZyKy.23uXP^olkfqb?^oZ)/3uX@ovpq^iifwbaT^qboZ+yyMyBkdfkbbofkd1/2y
K1/2*10-XJb`e^kfwbaPkltDlddibpZyKy1-uXP^olkfqb?^oZ).-uX?lob^kIb^qeboZ)2uXBqbok^iPe^altZ+yyMyBkdfkbbofkd10-y
K10-*102XKlfpbJ^`efkbZyKy.-uXColpqpqbbiQr_bZ).-uXLsbo`e^odba@^m^`fqloZ)1-uXE^kacrilc@l_^iq?liqpZ+Vlr`^k^iplj^hbXPlkf`?llpqboZfkpqb^afcvlrtlriaifhb+yyMyBkdfkbbofkd102y

KBkdfkbbofkd102*12-yKyVlrpelriaklt_befdebklrdeqlpq^oqj^hfkdpljblcqebcrkBkdfkbbofkdfqbjp^kabmf`p+Vlr`^kj^hbXDkljfpe>ojvHkfcbZql12-lojfu^kaj^q`eql12-+Drfab@ljmibqb+y
KDrfab@ljmibqb

]]
end)
