DugisGuideViewer:RegisterGuide("Fishing 1-450", nil, "Alliance", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-+Eltbsbo)vlr`^kpqfiirpbqefpdrfab^qiltboibsbip)vlr$iigrpqe^sbqlj^hbprobvlr^obefdebklrdeibsbiqljlsblkqlqebkbuqpqbm+y
KKlqbyKyQebobfpklilkdbo^kvCfpefkdWlkbp+Vlr`^kcfpe^kvtebobvlrifhbbsbk^qiltboibsbip)grpqbumb`qql`^q`e^ilqlcQo^pe)qelrdeqebqo^pealbp`lrkqqlt^oapibsbifkd+Fe^sbfk`irabami^`bpql`^q`eqebcfpekbbabaclo`llhfkd)lqebotfpbmf`h^`ljcloq^_ibcfpefkdelib^kacfpeqfiivlroeb^oqfp`lkqbkq+y

KQo^fk>mmobkqf`bCfpefkdyKy>okliaIbi^ka%22+.)36+2&yyWyPqlojtfka@fqvyyMJyCfpefkdy42y

?XCfpefkdMlibZyKy@^k_b_lrdeqcoljqebsbkalokbuqqlqebqo^fkbo+yyIy3/23y
?XPefkv?^r_ibZyKy@^k_b_lrdeqcoljqebsbkalokbuqqlqebqo^fkbo+Pq^oqtfqe/lcqebpb^ka_rvjlob^pkbbabarmqlcfpefkdibsbi2-+yyIy320//yyMyCfpefkd2-y
?XKfdeq`o^tibopZyKy@^k_b_lrdeqcoljqebsbkalokbuqqlqebqo^fkbo+Pq^oqtfqe2lcqebpb^ka_rvjlob^pkbbabarmqlcfpefkdibsbi.--+yyIy320-2yyMyCfpefkd.2-y

K.*42CfpefkdyKy>qq^`e^irobqlvlromlib^kapq^oqcfpefkd+Vlr`^k_bdfkcfpefkdtebobvlrqo^fkba+yyMyCfpefkd42y

KQo^fkGlrokbvj^kCfpefkdyKy>okliaIbi^ka%22+.)36+2&yyWyPqlojtfka@fqvyyMJyCfpefkdy.2-y

K42*.2-XO^t?ofpqibTefphbo@^qcfpeZyKy>pebks^ibloArphtlla+yyMyCfpefkd.2-y

KQo^fkBumboqCfpefkdyKy>okliaIbi^ka%22+.)36+2&yyWyPqlojtfka@fqvyyMJyCfpefkdy//2y

K.2-*//2XO^tJfqeofiEb^aQolrqZyKy>o^qefEfdeikaploArpqt^iiltJ^ope+yyMyCfpefkd//2y

KQo^fk>oqfp^kCfpefkdyKy>okliaIbi^ka%22+.)36+2&yyWyPqlojtfka@fqvyyMJyCfpefkdy0--y

K//2*0--Tbpqbok^kaB^pqbokMi^drbi^kapyKyCfpelmbkt^qbofkqebMi^drbi^kap+yyMyCfpefkd0--y

KQo^fkJ^pqboCfpefkdyKyGrklArco^fk%45+.)33+-&+yyWyW^kd^oj^opeyyMJyCfpefkdy042y

K0--*042W^kd^oj^opeyKyCfpeofdeqtebobvlrqo^fkba+yyMyCfpefkd042y

KQo^fkDo^kaJ^pqboCfpefkdyKyJ^o`f^@e^pb%2/+4)32+2&+yyWyA^i^o^kyyMJyCfpefkdy12-y

K042*12-KloqeobkayKyCfpe^kvtebobfkKloqeobkaqldbqql12-+yyMyCfpefkd12-y

KDrfab@ljmibqb

]]
end)
