DugisGuideViewer:RegisterGuide("Inscription 1-450", nil, "Alliance", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-+Eltbsbo)vlr`^kpqfiirpbqefpdrfab^qiltboibsbip)vlr$iigrpqe^sbqlj^hbprobvlr^obefdebklrdeibsbiqljlsblkqlqebkbuqpqbm+y
KQo^fkbopyKyQebqo^fkbopifpqba^obqeblkbpfkPqlojtfka@fqv)EbiicfobMbkfkpri^^kaA^i^o^k+L_sflrpivvlr`^krpblqebop^pvlrpbbcfq+y

KQo^fk>mmobkqf`bFkp`ofmqflkyKy@^q^ofk^Pq^kcloa%16+5)41+.&+yyWyPqlojtfka@fqvyyMJyFkp`ofmqflky42y

K.*/-XFslovFkhZyKy/-uX>i^_^pqboMfdjbkqZ+yyMyFkp`ofmqflk/-y
K/-*02XP`oliilcFkqbiib`qZyKy.2uXFslovFkhZ).2uXIfdeqM^o`ejbkqZ+yyMyFkp`ofmqflk02y
K02*12XJllkdiltFkhZyKy/-uX>i^_^pqboMfdjbkqZ+yyMyFkp`ofmqflk12y
K12*42XBk`e^kqfkdSbiirjZyKy0-uXJllkdiltFkhZ)3-uXIfdeqM^o`ejbkqZ+yyMyFkp`ofmqflk42y

KQo^fkGlrokbvj^kFkp`ofmqflkyKy@^q^ofk^Pq^kcloa%16+5)41+.&+yyWyPqlojtfka@fqvyyMJyFkp`ofmqflky.2-y

KFkp`ofmqflkIbsbifkdyKyVlrtfii_bj^hfkdfqbjpqe^q^objlpqivlo^kdbcoljeboblklrqrkqfivlrob^`e05-+Vlrtfiikbbaqlqo^fkbsbov2*.-ibsbip+Qeblkivob`fmbpqe^qtfii_bvbiilt,dobbkqlvlrpelria_bqebfkhp+Fcvlre^sbkllo^kdbob`fmbpfkvlroqo^abphfiitfkalt)qebkdlqo^fk+y

K42*5-XJfakfdeqFkhZyKy.-uXArpqvMfdjbkqZ+yyMyFkp`ofmqflk5-y
K5-*.--Dvimet,XJfakfdeqFkhZyKyJ^hb^kvDivmepqe^q^oblo^kdb^kaobnrfobpXJfakfdeqFkhZ+yyMyFkp`ofmqflk.--y
K.--*.-2XIflk$pFkhZyKy.-uXDliabkMfdjbkqZ+yyMyFkp`ofmqflk.-2y
K.-2*./2Dvimet,XIflk$pFkhZyKyJ^hb^kvDivmepqe^q^oblo^kdb^kaobnrfobpXIflk$pFkhZ+yyMyFkp`ofmqflk./2y
K./2*.0-XA^tkpq^oFkhZyKy.-uX?rokqMfdjbkqZ+Vlrtfiikbbaqlj^hb^qib^pq.-lcqebpb+P^sbqebj+yyMyFkp`ofmqflk.0-y
K.0-*.12Dvimet,XIflk$pFkhZyKyJ^hb^kvDivmepqe^q^oblo^kdb^kaobnrfobpXIflk$pFkhZ+yyMyFkp`ofmqflk.12y
K.12*.2-XPqo^kdbQ^olqZyKy2uXIflk$pFkhZ)2uX@ljjlkM^o`ejbkqZ).-uXA^tkpq^oFkhZ+yyMyFkp`ofmqflk.2-y

KQo^fkBumboqFkp`ofmqflkyKy@^q^ofk^Pq^kcloa%16+5)41+.&+yyWyPqlojtfka@fqvyyMJyFkp`ofmqflky//2y

K.2-*.22XG^abcfobFkhZyKy/-uXBjbo^iaMfdjbkqZ+yyMyFkp`ofmqflk.22y
K.22*.42Dvimet,XG^abcfobFkhZyKyJ^hb^kvDivmep,P`oliipqe^q^oblo^kdb^kaobnrfobpXG^abcfobFkhZ+yyMyFkp`ofmqflk.42y
K.42*.43XOlv^iFkhZyKy.-uXFkafdlMfdjbkqZ+Vlrtfiikbbaqlj^hb^qib^pq.-lcqebpb+P^sbqebj+yyMyFkp`ofmqflk.43y
K.43*.62Dvimet,XG^abcfobFkhZyKyJ^hb^kvDivmep,P`oliipqe^q^oblo^kdb^kaobnrfobpXG^abcfobFkhZ+yyMyFkp`ofmqflk.62y
K.62*/--X>o`^kbQ^olqZyKy2uXG^abcfobFkhZ)2uX@ljjlkM^o`ejbkqZ).-uXOlv^iFkhZ+yyMyFkp`ofmqflk/--y
K/--*/-2X@bibpqf^iFkhZyKy/-uXSflibqMfdjbkqZ+yyMyFkp`ofmqflk/-2y
K/-2*//2Dvimet,X@bibpqf^iFkhZyKyJ^hb^kvDivmep,P`oliipqe^q^oblo^kdb^kaobnrfobpX@bibpqf^iFkhZ+yyMyFkp`ofmqflk//2y

KQo^fk>oqfp^kFkp`ofmqflkyKy@^q^ofk^Pq^kcloa%16+5)41+.&+yyWyPqlojtfka@fqvyyMJyFkp`ofmqflky0--y

K//2*//3XCfbovFkhZyKy2uXOr_vMfdjbkqZ+Vlrtfiikbbaqlj^hb^qib^pq2lcqebpb+P^sbqebj+yyMyFkp`ofmqflk//3y
K//3*/2-Dvimet,X@bibpqf^iFkhZyKyJ^hb^kvDivmep,P`oliipqe^q^oblo^kdb,vbiilt^kaobnrfobpX@bibpqf^iFkhZ+yyMyFkp`ofmqflk/2-y
K/2-*/22XPefjjbofkdFkhZyKy/-uXPfisbovMfdjbkqZ+yyMyFkp`ofmqflk/22y
K/22*/6-Dvimet,XPefjjbofkdFkhZyKyJ^hb^kvDivmep,P`oliipqe^q^oblo^kdb^kaobnrfobpXPefjjbofkdFkhZ+yyMyFkp`ofmqflk/6-y

KQo^fkJ^pqboFkp`ofmqflkyKyJf`e^biP`et^k%20+6)32+2&+yyWyEbiicfobMbkfkpri^yyMJyFkp`ofmqflky042y

K/6-*0--XBqebob^iFkhZyKy1-uXKbqeboMfdjbkqZ+yyMyFkp`ofmqflk0--y
K0--*02-Dvimet,XBqebob^iFkhZyKyJ^hb^kvDivmep,P`oliipqe^q^oblo^kdb^kaobnrfobpXBqebob^iFkhZ+yyMyFkp`ofmqflk02-y

KQo^fkDo^kaJ^pqboFkp`ofmqflkyKyMolcbpploM^iifk%1/+3)05+.&+yyWyA^i^o^kyyMJyFkp`ofmqflky12-y

K02-*022XFkhlcqebPb^ZyKy/-uX>wrobMfdjbkqZ+yyMyFkp`ofmqflk022y
K022*042Dvimet,XFkhlcqebPb^ZyKyJ^hb^kvDivmep,P`oliipqe^q^oblo^kdb^kaobnrfobpXFkhlcqebPb^Z+yyMyFkp`ofmqflk042y
K042*05-XPkltc^iiFkhZyKy/-uXF`vMfdjbkqZ+yyMyFkp`ofmqflk05-y
K05-*052Dvimet,XFkhlcqebPb^ZyKyJ^hb^kvDivmep,P`oliipqe^q^obVBIILT^kaobnrfobpXFkhlcqebPb^Z+yyMyFkp`ofmqflk052y
K052*053KloqeobkaFkp`ofmqflkObpb^o`eyKy0uXFkhlcqebPb^Z).uXPkltc^iiFkhZ)2uXObpfifbkqM^o`ejbkqZ+yyMyFkp`ofmqflk053y
K053*1--Dvimet,XFkhlcqebPb^ZyKyJ^hb^kvAfp`lsbobaDivmepqe^q^oblo^kdb,vbiilt^kaobnrfobpXFkhlcqebPb^Z+yyMyFkp`ofmqflk1--y
K1--*1-2XP`oliilcPq^jfk^SFFFZyKy2uXFkhlcqebPb^Z).-uXObpfifbkqM^o`ejbkqZ+yyMyFkp`ofmqflk1-2y
K1-2*1.-XP`oliilcPmfofqSFFFZyKy2uXFkhlcqebPb^Z).-uXObpfifbkqM^o`ejbkqZ+yyMyFkp`ofmqflk1.-y
K1.-*1.2XP`oliilcFkqbiib`qSFFFZyKy2uXFkhlcqebPb^Z).-uXObpfifbkqM^o`ejbkqZ+yyMyFkp`ofmqflk1.2y
K1.2*1/-XP`oliilcPqobkdqeSFFFZyKy2uXFkhlcqebPb^Z).-uXObpfifbkqM^o`ejbkqZ+yyMyFkp`ofmqflk1/-y
K1/-*1/2XP`oliilc>dfifqvSFFFZyKy2uXFkhlcqebPb^Z).-uXObpfifbkqM^o`ejbkqZ+yyMyFkp`ofmqflk1/2y

KKloqeobkaFkp`ofmqflkObpb^o`eyKy@lkqfkrbalfkdObpb^o`erkqfi12-+Qebob^ob`ilpbql.--afp`lsboba^kaib^okbadvmeob`fmbp)plalfkdobpb^o`ebsbova^vtfiiebimcfkaqelpb+Vlrtfii^iplib^okJfkloFkp`ofmqflkObpb^o`e^qisi42)j^hbprobqlalqebpb^ptbii+Drfab`ljmibqb+y
KDrfab@ljmibqb

]]
end)
