DugisGuideViewer:RegisterGuide("Jewelcrafting 1-450", nil, "Alliance", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-+Eltbsbo)vlr`^kpqfiirpbqefpdrfab^qiltboibsbip)vlr$iigrpqe^sbqlj^hbprobvlr^obefdebklrdeibsbiqljlsblkqlqebkbuqpqbm+y
KKlqbyKyGbtbi`o^cqfkdfp^sbovafsbopbmolcbppflk+Qebj^qpobnrfobaqlibsbiqefpmolcbppflk`^kpljbqfjbp_bsbovbumbkpfsbloe^oaqlcfka+Molpmb`qfkdvlroltklobtfiivbfiaefdebo^jlrkqlckbbabaj^qp+y
KQo^fkbopyKyQebqo^fkbopifpqba^obqeblkbpfkPfisbojllk@fqv,QebBula^o)EbiicfobMbkfkpri^^kaA^i^o^k+L_sflrpivvlr`^krpblqebop^pvlrpbbcfq+y

KQefpDrfabyKyclopljbibsbip)tbe^sbifpqbapbsbo^i`o^cq^_ibfqbjpqe^qrpbafsbopbj^qbof^ipqlibsbiqlqebabpfobaphfii+Fcvlralklqe^sbqebj^qpcloqeb`roobkqfqbj)illhqlpbbfcqebob^oblqebopifpqba+y

KQo^fk>mmobkqf`bGbtbi`o^cqfkdyKyC^off%11+5)/2+3&+yyWyQebBula^oyyMJyGbtbi`o^cqfkdy42y
?XGbtbibo$pHfqZyKy?rvXGbtbibo$pHfqZcoljGbtbi`o^cqfkdsbkaloyyIy/-5.2yyMyGbtbi`o^cqfkd/y

K.*0-XAbif`^qb@lmmboTfobZyKy3-uX@lmmbo?^oZ)P^sbqebpb+yyMyGbtbi`o^cqfkd0-y
K0-*2-XQfdbopbvb?^kaZloXJ^i^`efqbMbka^kqZyKy/-uXAbif`^qb@lmmboTfobZ)/-uXQfdbobvbZlo/-uXJ^i^`efqbZ+yyMyGbtbi`o^cqfkd2-y

KQo^fkGlrokbvj^kGbtbi`o^cqfkdyKyC^off%11+5)/2+3&+yyWyQebBula^oyyMJyGbtbi`o^cqfkdy.2-y

K2-*5-X?olkwbPbqqfkdZyKy3-uX?olkwb?^oZ)P^sbqebpb+yyMyGbtbi`o^cqfkd5-y
K5-*.--XPfjmibMb^oiOfkdZyKy/-uXPj^iiIrpqolrpMb^oiZ)/-uX?olkwbPbqqfkdZ)1-uX@lmmbo?^oZ+yyMyGbtbi`o^cqfkd.--y
K5-*.--XDillj?^kaZyKy1-uXPe^altdbjZ)/-uX?olkwbPbqqfkdZ)1-uXAbif`^qb@lmmboTfobZ+yyMyGbtbi`o^cqfkd.--y
K5-*.--X?ofiif^kqKb`hi^`bZyKy5-uX?olkwb?^oZ)/-uX?olkwbPbqqfkdZ)/-uXJlpp>d^qbZ+yyMyGbtbi`o^cqfkd.--y
K5-*.--XOfkdlcPfisboJfdeqZyKy1-uXPfisbo?^oZ+yyMyGbtbi`o^cqfkd.--y
K.--*..-XOfkdlcQtfifdeqPe^altpZyKyy/-uXPe^altdbjZ)/-uX?olkwb?^oZ+yyMyGbtbi`o^cqfkd..-y
K..-*./-XEb^svPqlkbPq^qrbZyKy5-uXEb^svPqlkbZ+yyMyGbtbi`o^cqfkd./-y
K..-*./-XOfkdlcQtfifdeqPe^altpZyKyy/-uXPe^altdbjZ)/-uX?olkwb?^oZ+yyMyGbtbi`o^cqfkd./-y
?XAbpfdk7Mbka^kqlcqeb>d^qbPefbiaZyKyKb^i>iibk%.-+4)23+5&yyWyTbqi^kapyyIy/-64-yyMyGbtbi`o^cqfkd.2-y
K./-*.2-XMbka^kqlcqeb>d^qbPefbiaZyKy0-uXJlpp>d^qbZ)0-uX?olkwbPbqqfkdZ+yyMyGbtbi`o^cqfkd.2-y

KQo^fkBumboqGbtbi`o^cqfkdyKyC^off%11+5)/2+3&+yyWyQebBula^oyyMJyGbtbi`o^cqfkdy//2y

K.2-*.42XJfqeofiCfifdobbZyKy2-uXJfqeofi?^oZ+yyMyGbtbi`o^cqfkd.42y
K.42*.52XPlifaPqlkbPq^qrbZyKy.--uXPlifaPqlkbZ+yyMyGbtbi`o^cqfkd.52y
K.52*/--XBkdo^sbaQorbpfisboOfkdZyKy.2uXQorbpfisbo?^oZ)0-uXJfqeofiCfifdobbZ+yyMyGbtbi`o^cqfkd/--y
K.52*/--X@fqofkbOfkdlcO^mfaEb^ifkdZyKy0-uXJfqeofi?^oZ).2uX@fqofkbZ+yyMyGbtbi`o^cqfkd/--y
K/--*//-X@fqofkbOfkdlcO^mfaEb^ifkdZyKy1-uXJfqeofi?^oZ)/-uX@fqofkbZ+yyMyGbtbi`o^cqfkd//-y

KQo^fk>oqfp^kGbtbi`o^cqfkdyKyC^off%11+5)/2+3&+yyWyQebBula^oyyMJyGbtbi`o^cqfkdy0--y

K//-*//2X>nr^j^ofkbMbka^kqlcqebT^oofloZyKy2uX>nr^j^ofkbZ).2uXJfqeofiCfifdobbZ+yyMyGbtbi`o^cqfkd//2y
K//2*/12XQelofrjPbqqfkdZyKy/-uXQelofrj?^oZ+yyMyGbtbi`o^cqfkd/12y
K/12*/3-XObaOfkdlcAbpqor`qflkZyKy.2uXPq^oOr_vZ).2uXQelofrjPbqqfkdZ+yyMyGbtbi`o^cqfkd/3-y
K/12*/3-XOr_vMbka^kqlcCfobZyKy.2uXPq^oOr_vZ).2uXQelofrjPbqqfkdZ+yyMyGbtbi`o^cqfkd/3-y
K/3-*/5-XPfjmibLm^iOfkdZyKy/-uXI^odbLm^iZ)/-uXQelofrjPbqqfkdZ+yyMyGbtbi`o^cqfkd/5-y
K/5-*/6-XLkpi^rdeqOfkdZyKy.-uXQelofrjPbqqfkdZ).-uXMltbocriJlglZ).-uXBppbk`blcB^oqeZ+yyMyGbtbi`o^cqfkd/6-y
K/5-*/6-XP^mmefobMbka^kqZlcXTfkqboKfdeqZyKy.-uXQelofrjPbqqfkdZ).-uX?irbP^mmefobZ).-uXBppbk`blcRkab^qeZ+yyMyGbtbi`o^cqfkd/6-y
K/6-*0--XBjbo^iaIflkOfkdZyKy/-uXErdbBjbo^iaZ).-uXQelofrjPbqqfkdZ+yyMyGbtbi`o^cqfkd0--y

KQo^fkJ^pqboGbtbi`o^cqfkdyKyQ^qf^k^%21+3)30+3&+yyWyEbiicfobMbkfkpri^yyMJyGbtbi`o^cqfkdy042y

K0--*0/2Lrqi^kaDbjpyKyQefpm^oqlcqebDrfabe^pob`fmbpqe^q^ob^iob^avvbiiltqlvlr+@rq^k^pploqjbkqlcLrqi^kaDbjpql0/2)^kabsbov2ibsbiplopleb^a_^`hqlqebqo^fkbopclokbtob`fmbp+yyMyGbtbi`o^cqfkd0/2y
K0/2*002XJbo`rof^i>a^j^kqfqbZyKyJ^hb.0*.2loqfii002+3-uX>a^j^kqfqbMltaboZ).2uXMofj^iB^oqeZ+yyMyGbtbi`o^cqfkd002y
K002*01-Lrqi^kaDbjpyKy@rq^k^pploqjbkqlcLrqi^kaDbjpql01-+yyMyGbtbi`o^cqfkd01-y
K01-*02-XEb^sv>a^j^kqfqbOfkdZyKy.-uX>a^j^kqfqb?^oZ).-uXJbo`rof^i>a^j^kqfqbZ+yyMyGbtbi`o^cqfkd02-y
K01-*02-XQef`h>a^j^kqfqbKb`hi^`bZyKy/-uX>a^j^kqfqb?^oZ).-uXJbo`rof^i>a^j^kqfqbZ+yyMyGbtbi`o^cqfkd02-y

KQo^fkDo^kaJ^pqboGbtbi`o^cqfkdyKyQfjlqevGlkbp%06+5)01+6&+yyWyA^i^o^kyyMJyGbtbi`o^cqfkdy12-y

K02-*06-Kloqeobka@ljjlk%Dobbk&DbjpyKyKloqeobkae^p^ilqlckbtdobbkdbjob`fmbpqlib^ok^ka^kvtfiiebimvlribsbi+>p_bclob)j^hbprobvlrsfpfqqebqo^fkbopbsbov2*.-ibsbipclokbtob`fmbp+@lkqfkrb`rqqfkddobbkibsbidbjpqfii06-+yyMyGbtbi`o^cqfkd06-y
K06-*1.-XPqlkbdr^oa?^kaZyKy1-uXBqbok^iB^oqeZ+yyMyGbtbi`o^cqfkd1.-y
K1.-*1/-KloqeobkaRk`ljjlk%?irb&DbjpyKy@rqrk`ljjlk%?irb&dbjp+yyMyGbtbi`o^cqfkd1/-y
K1/-*11-KloqeobkaJbq^DbjpyKy@rq^kv`lj_fk^qflklcJbq^Dbjp+yyMyGbtbi`o^cqfkd11-y
K11-*11.XF`vMofpjZyKy.uXColwbkLo_Z).uX@e^i`balkvZ).uXPe^alt@ovpq^iZ).uXA^ohG^abZ+yyMyGbtbi`o^cqfkd11.y

K11.*12-yKyAb^ibop@elf`blkqebkbuq6ibsbip+@lkqfkrbj^hfkdJbq^dbjp^kapq^oqqebGbtbi`o^cqfkA^fifvcloBmf`M^qqbokp+Vlr`^k^iplmlpqvlroqo^abphfiilkQo^ab@e^qloj^hbfqbjpqe^qvlr`^kpbiilorpb+Drfab@ljmibqby
KDrfab@ljmibqb

]]
end)
