DugisGuideViewer:RegisterGuide("Mining by Smelting 1-375", nil, "Alliance", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-+Eltbsbo)vlr`^kpqfiirpbqefpdrfab^qiltboibsbip)vlr$iigrpqe^sbqlj^hbprobvlr^obefdebklrdeibsbiqljlsblkqlqebkbuqpqbm+y
KKlqbyKyQefpfp^k^iqbok^qfsbt^vqlibsbivlrojfkfkdphfiitfqelrq^`qr^iive^sfkdqljfkb^kvqefkd+Mib^pb_b^t^obqe^qvlrtfiie^sbql_rvqeblobqlalqefp+Qefpdrfablkivdlbpql042)^pqebobfpklpjbiqfkdqe^qtfiio^fpbvlroqo^abphfiilsbo042+y
KQo^fkbopyKyQebqo^fkbopifpqba^obqeblkbpfkPqlojtfka@fqv)EbiicfobMbkfkpri^^kaA^i^o^k+L_sflrpivvlr`^krpblqebop^pvlrpbbcfq+y

KQo^fk>mmobkqf`bJfkfkdyKyDbij^kPqlkbe^ka%26+/)04+4&+yyWyPqlojtfka@fqvyyMJyJfkfkdy42y

K.*32Pjbiq@lmmboyKy32uX@lmmboLobZ+yyMyJfkfkd32y

KQo^fkGlrokbvj^kJfkfkdyKyDbij^kPqlkbe^ka%26+/)04+4&+yyWyPqlojtfka@fqvyyMJyJfkfkdy.2-y

K32*42PjbiqQfkyKy.2uXQfkLobZ+yyMyJfkfkd42y
K42*..-Pjbiq?olkwbyKy1-uXQfkLobZ)1-uX@lmmboLobZ+yyMyJfkfkd..-y
K..-*./2PjbiqPfisboyKy/-uXPfisboLobZ+yyMyJfkfkd./2y

KQo^fkBumboqJfkfkdyKyDbij^kPqlkbe^ka%26+/)04+4&+yyWyPqlojtfka@fqvyyMJyJfkfkdy//2y

K./2*.3-PjbiqFolkyKy2-uXFolkLobZ+yyMyJfkfkd.3-y
K.3-*.42PjbiqDliayKy/-uXDliaLobZ+yyMyJfkfkd.42y
K.42*//2PjbiqJfqeofiyKy3-uXJfqeofiLobZ+yyMyJfkfkd//2y

KQo^fk>oqfp^kJfkfkdyKyDbij^kPqlkbe^ka%26+/)04+4&+yyWyPqlojtfka@fqvyyMJyJfkfkdy0--y

K//2*/0-PjbiqJfqeofiyKy.-uXJfqeofiLobZ+yyMyJfkfkd/0-y
K/0-*/42PjbiqQelofrjyKy32uXQelofrjLobZ+yyMyJfkfkd/42y

KQo^fkJ^pqboJfkfkdyKyErok^hDofjjloa%23+4)30+5&+yyWyEbiicfobMbkfkpri^yyMJyJfkfkdy042y

K/42*0/2PjbiqCbiFolkyKy./-uXCbiFolkLobZ+yyMyJfkfkd0/2y
K0/2*01-Pjbiq>a^j^kqfqbyKy2-uX>a^j^kqfqbLobZ+yyMyJfkfkd01-y

K01-*02-yKyVlr`^kJfkbql02-lovlr`^kPjbiqBqbokfrj^kaBibjbkqfrjql02-+yyMyJfkfkd02-y

K02-*042Pjbiq@l_^iqyKy1-uX@l_^iqLobZ+yyMyJfkfkd042y

KQo^fkDo^kaJ^pqboJfkfkdyKyGbafaf^eE^kabop%1.+2)/3+-&+yyWyA^i^o^kyyMJyJfkfkdy12-y

KDrfab@ljmibqb

]]
end)
