DugisGuideViewer:RegisterGuide("Blacksmithing 1-450", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-+Eltbsbo)vlr`^kpqfiirpbqefpdrfab^qiltboibsbip)vlr$iigrpqe^sbqlj^hbprobvlr^obefdebklrdeibsbiqljlsblkqlqebkbuqpqbm+y
KQo^fkbopyKyQebqo^fkbopifpqba^obqeblkbpfkLodofjj^o)EbiicfobMbkfkpri^^kaA^i^o^k+L_sflrpivvlr`^krpblqebop^pvlrpbbcfq+y

KQo^fk>mmobkqf`b?i^`hpjfqefkdyKyP^orPqbbicrov%5/+1)/0+3&+yyWyLodofjj^oyyMJy?i^`hpjfqefkdy42y
?X?i^`hpjfqeE^jjboZyKy?rvcoljsbkalokb^oqo^fkbo+yyIy2623yyWyLodofjj^oyyMy?i^`hpjfqefkd2.y

K.*/2XOlrdePe^ombkfkdPqlkbZyKy/2uXOlrdePqlkbZ+yyMy?i^`hpjfqefkd/2y
K/2*2-XOlrdeDofkafkdPqlkbZyKy2-uXOlrdePqlkbZ+P^sb.-cloi^qbo+yyMy?i^`hpjfqefkd2-y
K2-*42X@lmmbo@e^fk?biqZyKy.2-uX@lmmbo?^oZ+yyMy?i^`hpjfqefkd42y

KQo^fkGlrokbvj^k?i^`hpjfqefkdyKyP^orPqbbicrov%5/+1)/0+3&+yyWyLodofjj^oyyMJy?i^`hpjfqefkdy.2-y

K42*52X@l^opbDofkafkdPqlkbZyKy0-uX@l^opbPqlkbZ+P^sbqebpbcloi^qbo+yyMy?i^`hpjfqefkd52y
K52*.--XOrkba@lmmbo?biqZyKy.2-uX@lmmbo?^oZ+yyMy?i^`hpjfqefkd.--y
K.--*.-2XPfisboOlaZyKy2uXPfisbo?^oZ).-uXOlrdeDofkafkdPqlkbZ+yyMy?i^`hpjfqefkd.-2y
K.-2*./2XOlrde?olkwbIbddfkdpZyKy./-uX?olkwb?^oZ+yyMy?i^`hpjfqefkd./2y
K./2*.04XEb^svDofkafkdPqlkbZyKy.-2uXEb^svPqlkbZ+Hbbm02cloi^qbo+yyMy?i^`hpjfqefkd.04y
K.04*.2-XM^qqboba?olkwb?o^`bopZyKy32uX?olkwb?^oZ)/3uX@l^opbDofkafkdPqlkbZ+yyMy?i^`hpjfqefkd.2-y

KQo^fkBumboq?i^`hpjfqefkdyKyP^orPqbbicrov%5/+1)/0+3&+yyWyLodofjj^oyyMJy?i^`hpjfqefkdy//2y

K.2-*.22XDliabkOlaZyKy2uXDlia?^oZ).-uX@l^opbDofkafkdPqlkbZ+yyMy?i^`hpjfqefkd.22y
?XDobbkAvbZyKyVlrtfiikbba.uXDobbkAvbZcloqebkbuqqtlfqbjp+?rv^qib^pq1-+yyMy?i^`hpjfqefkd.62y
K.22*.32XDobbkFolkIbddfkdpZyKy5-uXFolk?^oZ).-uXEb^svDofkafkdPqlkbZ).-uXDobbkAvbZ+yyMy?i^`hpjfqefkd.32y
K.32*.62XDobbkFolk?o^`bopZyKy.5-uXFolk?^oZ)0-uXDobbkAvbZ+yyMy?i^`hpjfqefkd.62y
K.62*/--XDliabkP`^ib?o^`bopZyKy/2uXPqbbi?^oZ).-uXEb^svDofkafkdPqlkbZ+yyMy?i^`hpjfqefkd/--y

K?i^`hpjfqePmb`f^iqfbpyKy>qphfiiibsbi/--^ka`e^o^`qboibsbi1-)?i^`hpjfqep`^k`ellpbqlpmb`f^ifwb^p^k>ojlopjfqelo^Tb^mlkpjfqe+Tb^mlkpjfqep`^ki^qbocroqebopmb`f^ifwbfkqlE^jjbo*)>ub*loPtloapjfqep+>iipmb`f^ifwba^ojlo^katb^mlkp^ob?fkalkMf`hrm^ka`^klkiv_brpba_vqeb_i^`hpjfqeqe^qj^abqebj+Jlpqpmb`f^ifw^qflkob`fmbpobnrfobafccf`riq`ljmlkbkqp)pr`e^pMofj^iJfdeqp)Mofj^iKbqebop)^kaKbqeboSloqbubp+yyMy?i^`hpjfqefkd0--y

KQo^fk>oqfp^k?i^`hpjfqefkdyKyP^orPqbbicrov%5/+1)/0+3&+yyWyLodofjj^oyyMJy?i^`hpjfqefkdy0--y

K/--*/-2XQorbpfisboOlaZyKy2uXQorbpfisbo?^oZ)2uXEb^svDofkaPqlkbZ+yyMy?i^`hpjfqefkd/-2y
K/-2*/.-XDliabkP`^ib?o^`bopZyKy/2uXPqbbi?^oZ).-uXEb^svDofkafkdPqlkbZ+yyMy?i^`hpjfqefkd/.-y
K/.-*/0-XEb^svJfqeofiD^rkqibqZyKy./-uXJfqeofi?^oZ)5-uXJ^dbtb^sb@ilqeZ+yyMy?i^`hpjfqefkd/0-y
K/0-*/02XJfqeofiPefbiaPmfhbZyKy/-uXJfqeofi?^oZ).-uXQorbpfisbo?^oZ)/-uXPlifaDofkafkdPqlkbZ+yyMy?i^`hpjfqefkd/02y
K/02*/2-XJfqeofi@lfcZyKy.2-uXJfqeofi?^oZ)6-uXJ^dbtb^sb@ilqeZ+yyMy?i^`hpjfqefkd/2-y
K/2-*/24XAbkpbDofkafkdPqlkbZyKy1-uXAbkpbPqlkbZ+yyMy?i^`hpjfqefkd/24y
K/24*/5-XQelofrj?o^`bopZyKy.51uXQelofrj?^oZ+yyMy?i^`hpjfqefkd/5-y
K/5-*0--XQelofrj?llqpZloXQelofrjEbijZyKy/1-uXQelofrj?^oZ).3-uXOrddbaIb^qeboZLO/-uXPq^oOr_vZ+yyMy?i^`hpjfqefkd0--y

KQo^fkJ^pqbo?i^`hpjfqefkdyKyOlelh%20+/)05+/&+yyWyEbiicfobMbkfkpri^yyMJy?i^`hpjfqefkdy042y

?XMi^kp7IbppboT^oalcPefbiafkdZyKyOlelh%20+/)/5+/&)P^sbcloi^qbo+yyWyEbiicfobMbkfkpri^yyMy?i^`hpjfqefkd02-y
K0--*0.-XCbiFolkMi^qbDilsbpZyKy1-uXCbiFolk?^oZ+yyMy?i^`hpjfqefkd0.-y
K0.-*0.2XCbiFolkMi^qb?biqZyKy/-uXCbiFolk?^oZ+yyMy?i^`hpjfqefkd0.2y
K0.2*0/-XCbiFolk@e^fkDilsbpZyKy/2uXCbiFolk?^oZ+yyMy?i^`hpjfqefkd0/-y
K0/-*0/2XCbiFolkMi^qb?llKZyKy0-uXCbiFolk?^oZ+yyMy?i^`hpjfqefkd0/2y
K0/2*00-XIbppboOrkblcT^oafkdZyKy2uX>a^j^kqfqb?^oZ+yyMy?i^`hpjfqefkd00-y
K00-*002XCbiFolk?ob^pqmi^qbZyKy2-uXCbiFolk?^oZ+yyMy?i^`hpjfqefkd002y
?XMi^kp7>a^j^kqfqb@ib^sboZyKy>^olkEliij^k%31+.)4.+0&yyWyPe^qqo^qe@fqvyyMy?i^`hpjfqefkd01-y
K002*01-X>a^j^kqfqb@ib^sboZyKy1-uX>a^j^kqfqb?^oZ+yyMy?i^`hpjfqefkd01-y
K01-*02-XIbppboT^oalcPefbiafkdZyKy.-uX>a^jk^kqfqb?^oZ+yyMy?i^`hpjfqefkd02-y

KQo^fkDo^kaJ^pqbo?i^`hpjfqefkdyKy>i^oaP`ejfba%12+1)/5+.&+yyWyA^i^o^kyyMJy?i^`hpjfqefkdy12-y

K02-*03-X@l_^iq?biqZyKy1-uX@l_^iq?^oZ+yyMy?i^`hpjfqefkd03-y
K03-*04-X@l_^iq?o^`bopZyKy1-uX@l_^iq?^oZ+yyMy?i^`hpjfqefkd04-y
K04-*05-X@l_^iqD^rkqibqpZyKy2-uX@l_^iq?^oZ+yyMy?i^`hpjfqefkd05-y
K05-*052XPmfhba@l_^iq?llqpZyKy02uX@l_^iq?^oZ+yyMy?i^`hpjfqefkd052y
K052*06-XProb*cfobPerofhbkZyKy02uX@l_^iq?^oZ+yyMy?i^`hpjfqefkd06-y
K06-*062XKlq`eba@l_^iqT^o>ubZyKy2-uX@l_^iq?^oZ+yyMy?i^`hpjfqefkd062y
K062*1--X?ofiif^kqP^olkfqb?biqZyKy0-uX@l_^iq?^oZ)/2uXP^olkfqb?^oZ+yyMy?i^`hpjfqefkd1--y
K1--*1-2XElokba@l_^iqEbijZyKy1-uX@l_^iq?^oZ+yyMy?i^`hpjfqefkd1-2y
K1-2*1.2XAb^aivP^olkfqbAfohZyKy4-uXP^olkfqb?^oZ)/-uX@ovpq^iifwba>foZ+yyMy?i^`hpjfqefkd1.2y
K1.2*1/2XBqbok^i?biq?r`hibZyKy4-uXP^olkfqb?^oZ).-uXBqbok^iB^oqeZ).-uXBqbok^iT^qboZ).-uXBqbok^iPe^altZ+Pbiiqebpbfkqeb>ElofkQo^ab`e^q+yyMy?i^`hpjfqefkd1/2y
K1/2*11-XA^rkqfkdIbdmi^qbpZyKy/.-uXP^olkfqb?^oZ).2uXBqbok^iB^oqeZ+yyMy?i^`hpjfqefkd11-y

K11-*12-yKyAb^ibop@elf`blkqebkbuq.-ibsbip+Vlr`^kkltj^hbqeb^iiqebqo^fk^_ibbmf`m^qqbokp+Vlr`^kbfqebomlpqvlroqo^abphfiilkQo^ab@e^qloj^hbfqbjpqe^qvlr`^kpbiilotb^o+Drfab@ljmibqby
KDrfab@ljmibqb

]]
end)
