DugisGuideViewer:RegisterGuide("Cooking w/ Fishing 1-450", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-+Eltbsbo)vlr`^kpqfiirpbqefpdrfab^qiltboibsbip)vlr$iigrpqe^sbqlj^hbprobvlr^obefdebklrdeibsbiqljlsblkqlqebkbuqpqbm+Qebphfiip^obpbqclo`llhfkd)_rql_sflrpivvlribsbicfpefkd^pvlrl_q^fkqebfqbjpkbbabaclo`llhfkd+y
KKlqbyKyFqj^hbppbkpbqlibsbiqebpbqtlpb`lka^ovmolcbppflkpqldbqebo+Vlr`^krpb`llhfkdql`llhqebfqbjpqe^qvlr`^q`ecfpefkd)^ka^ilqlcqebefdeibsbi`llhfkdob`fmbpobnrfobcfpefkd+Qebobfpklilkdbo^kvCfpefkdWlkbp+Vlr`^kcfpe^kvtebobvlrifhbbsbk^qiltboibsbip)grpqbumb`qql`^q`e^ilqlcQo^pe)qelrdeqebqo^pealbp`lrkqqlt^oapibsbifkd+Fe^sbfk`irabami^`bpql`^q`eqebcfpekbbabaclo`llhfkd+y

OQerkabo?ircc

KQo^fk>mmobkqf`b@llhfkdyKy>ph^Jfpqorkkbo%2.+0)2/+5&yyWyQerkabo?irccyyMJy@llhfkdy42y
KQo^fk>mmobkqf`bCfpefkdyKyH^eJfpqorkkbo%23+5)14+1&yyWyQerkabo?irccyyMJyCfpefkdy42y

?XCfpefkdMlibZyKy@^k_b_lrdeqcoljqebsbkalokbuqqlqebqo^fkbo+yyIy3/23y
?/uXPefkv?^r_ibZyKy@^k_b_lrdeqcoljqebsbkalokbuqqlqebqo^fkbo+Pq^oqtfqe/lcqebpb^ka_rvjlob^pkbbabarmqlcfpefkdibsbi2-+yyIy32/6/yyMyCfpefkd2-y
?2uXKfdeq`o^tibopZyKy@^k_b_lrdeqcoljqebsbkalokbuqqlqebqo^fkbo+Pq^oqtfqe2lcqebpb^ka_rvjlob^pkbbabarmqlcfpefkdibsbi.2-+yyIy320-2yyMyCfpefkd.2-y

?XOb`fmb7?ofiif^kqPj^iicfpeZyKyPbt^Jfpqorkkbo%23+4)14+1&yyWyQerkabo?irccyyIy30/2yyMy@llhfkd2-y
?XOb`fmb7?ofpqibTefphbo@^qcfpeZyKyPbt^Jfpqorkkbo%23+4)14+1&yyWyQerkabo?irccyyIy300-yyMy@llhfkd2-y
?XOb`fmb7Ilkdg^tJraPk^mmboZyKyK^^iJfpqorkkbo%2.+4)2.+6&yyWyQerkabo?irccyyIy30/5yyMy@llhfkd.--y

KCfpefkd.*42yKyVlr`^k_bdfkcfpefkdfk^kvj^glo`fqv)plbnrfmvlrocfpefkdMlib)^qq^`e^irob^kapq^oqcfpefkd+yyMyCfpefkd42y

K.*0-XPmf`b?ob^aZyKy0-uXPfjmibCilroZ)0-uXJfiaPmf`bZ+yyMy@llhfkd0-y
K0-*2-X?ofiif^kqPj^iicfpeZyKy/-uXO^t?ofiif^kqPj^iicfpeZ+yyMy@llhfkd2-y

KQo^fkGlrokbvj^kCfpefkdyKyH^eJfpqorkkbo%23+5)14+1&yyWyQerkabo?irccyyMJyCfpefkdy.2-y
KQo^fkGlrokbvj^k@llhfkdyKy>ph^Jfpqorkkbo%2.+0)2/+5&yyWyQerkabo?irccyyMJy@llhfkdy.2-y

KCfpefkd42*.--yKy@lkqfkrbCfpefkdfkj^glo`fqfbp+yyMyCfpefkd.--y
K2-*.--XIlkdg^tJraPk^mmboZyKy2-uXO^tIlkdg^tJraPk^mmboZ+yyMy@llhfkd.--y

KCfpefkd.--*.2-yKyLmbkt^qbopfk>pebks^ibloArphtllacloXO^t?ofpqibTefphbo@^qcfpeZ+yyMyCfpefkd.2-y
K.--*.2-X?ofpqibTefphbo@^qcfpeZyKy2-uXO^t?ofpqibTefphbo@^qcfpeZ+yyMy@llhfkd.2-y

KQo^fkBumboq@llhfkdyKy>ph^Jfpqorkkbo%2.+0)2/+5&yyWyQerkabo?irccyyMJy@llhfkdy//2y
KQo^fkBumboqCfpefkdyKyH^eJfpqorkkbo%23+5)14+1&yyWyQerkabo?irccyyMJyCfpefkdy//2y

K.2-*.42X?ofpqibTefphbo@^qcfpeZyKy/2uXO^t?ofpqibTefphbo@^qcfpeZ+yyMy@llhfkd.42y

OLodofjj^o
?XOb`fmb7JfqeofiEb^aQolrqZyKyPe^khvp%4-+2)/6+.&+yyWyLodofjj^oyyIy.4-3/yyMy@llhfkd//2y

KCfpefkd.2-*//2yKyLmbkt^qbopfk>o^qefEfdei^kapcloXO^tJfqeofiEb^aQolrqZ+yyMyCfpefkd//2y
K.42*//2XJfqeofiEb^aQolrqZyKy2-uXO^tJfqeofiEb^aQolrqZ+yyMy@llhfkd//2y

KQo^fk>oqfp^k@llhfkdyKy>ph^Jfpqorkkbo%2.+0)2/+5&yyWyQerkabo?irccyyMJy@llhfkdy0--y
KQo^fk>oqfp^kCfpefkdyKyH^eJfpqorkkbo%23+5)14+1&yyWyQerkabo?irccyyMJyCfpefkdy0--y

K>aafqflk^iOb`fmbpyKyQebobfp^_fqlcorkkfkdcloqebpbob`fmbp+yyMy@llhfkd0--y
O?llqv?^vyMy@llhfkd/2-y
?XOb`fmb7CfibqlcObadfiiZyKyHbipbvV^k`b%/5+/)41+2&fk?llqv?^v+yyWyPqo^kdibqelokS^ibyyIy.061.yyMy@llhfkd/2-y
OQ^k^ofpyMy@llhfkd/42y
?XOb`fmb7Ml^`ebaPrkp`^ibP^ijlkZyKyDfhhfu%33+2)//+.&+yyWyQ^k^ofpyyyIy.0613yyMy@llhfkd/42y
OCbo^i^pyMy@llhfkd0--y
?XOb`fmb7?^hbaP^ijlkZyKyPebbkao^Q^iido^pp%41+2)1/+5&+yyWyCbo^i^pyyIy.0616yyMy@llhfkd0--y

OTbpqbokMi^drbi^kap
KCfpefkd//2*/3-yKyCfpeLmbkT^qbofkTbpqbokMi^drbi^kapcloXO^tObadfiiZ^kaXO^tPrkp`^ibP^ijlkZ+yyMyCfpefkd/3-y
K//2*/2-XCfibqlcObadfiiZyKy/2uXO^tObadfiiZ+yyMy@llhfkd/2-y

OB^pqbokMi^drbi^kap
KCfpefkd/3-*0--yKyCfpeLmbkT^qbofkB^pqbokMi^drbi^kapcloXO^tPrkp`^ibP^ijlkZ^kaXO^tTefqbp`^ibP^ijlkZ+yyMyCfpefkd0--y
K/2-*/42XMl^`ebaPrkp`^ibP^ijlkZyKy/2uXO^tPrkp`^ibP^ijlkZ+yyMy@llhfkd/42y
K/42*0--X?^hbaP^ijlkZyKy/2uXO^tTefqbp`^ibP^ijlkZ+yyMy@llhfkd0--y

OEbiicfobMbkfkpri^
KQo^fkJ^pqbo@llhfkdyKy?^uqbo%23+5)04+2&+yyWyEbiicfobMbkfkpri^yyMJy@llhfkdy042y
OW^kd^oj^ope
KQo^fkJ^pqboCfpefkdyKyGrklArco^fk%45+.)33+-&+yyWyW^kd^oj^opeyyMJyCfpefkdy042y

?XOb`fmb7Cbiq^fiAbifdeqZyKyWro^f%52+/)21+4&+yyWyW^kd^oj^opeyyIy/4362yyMy@llhfkd0/2y
?XOb`fmb7?i^`hbkbaQolrqZyKyD^j_^ofkh^%0.+4)16+0&+yyWyW^kd^oj^opeyyIy/4361yyMy@llhfkd0/2y

KCfpefkd0--*02-yKyCfpefkdcloXPmlqqbaCbiq^fiZ^kaX?^o_baDfiiQolrqZfkW^kdboj^ope+yyMyCfpefkd02-y
K0--*0/2XCbiq^fiAbifdeqZloX?i^`hbkbaQolrqZyKy/2uXPmlqqbaCbiq^fiZlo/2uX?^o_baDfiiQolrqZ+yyMy@llhfkd0/2y

OQbolhh^oClobpq
?XOb`fmb7DliabkCfpePqf`hpZyKyOrkdlo%15+5)13+.&+yyWyQbolhh^oClobpqyyIy/4366yyMy@llhfkd02-y

KCfpefkd02-*042yKyCfpecloXDliabkA^oqboZfkQbolhh^oClobpq+yyMyCfpefkd042y
K0/2*02-XDliabkCfpePqf`hpZyKy/2uXDliabkA^oqboZ+yyMy@llhfkd02-y

OEltifkdCgloa
KQo^fkDo^kaJ^pqbo@llhfkdyKyQelj^pHlif`efl%45+4)/6+2&+yyWyEltifkdCgloayyMJy@llhfkdy12-y

>Kloqebok@llhfkdyKyQelj^pHlif`efl%45+4)/6+2&+yyNFAy.0-56yyWyEltifkdCgloay
@Kloqebok@llhfkdyKy?ofkdclroX@efiibaJb^qZqlQelj^pHlif`efl+X@efiibaJb^qZ`^k_bclrkalk^kvKloqeobka_b^pq+yyNFAy.0-56yyWyEltifkdCgloay
QKloqebok@llhfkdyKyQelj^pHlif`efl%45+4)/6+2&+yyNFAy.0-56yyWyEltifkdCgloay

OA^i^o^k
KQo^fkDo^kaJ^pqboCfpefkdyKyJ^o`f^@e^pb%2/+4)32+2&+yyWyA^i^o^kyyMJyCfpefkdy12-y

KA^fifbpyKyVlrpelriakltpq^oqalfkdqeb`llhfkd^kacfpefkda^fifbpfkA^i^o^k+>cqbovlrob^`e1--`llhfkdphfii)qebobj^fkabolcqebob`fmbp^kaqebXKloqebkPmf`bZobnrfobaqlj^hbqebj^obl_q^fkbacoljqebsbkalocloXA^i^o^k@llhfkd>t^oapZ+y

KCfpe042*1/2yKyCfpefkd^kvlmbkt^qbopfkEltifkdCgloacloX?lkbp`^ibPk^mmboZ^kaXC^kdqllqeEboofkdZ+yyMyCfpefkd1/2y
K02-*042XDofiiba?lkbp`^ibZyKy/2uX?lkbp`^ibPk^mmboZ+yyMy@llhfkd042y
K042*1--XMf`hibaC^kdqllqeZyKy/2uXC^kdqllqeEboofkdZ+yyMy@llhfkd1--y

KCfpefkd1/2*12-yKyCfpefkd^kvtebobfkKloqeobkaqe^qe^pqebcfpeclo`llhfkd+yyMyCfpefkd12-y
KA^fifbpyKyColj1--*12-vlrtfiirpbob`fmbpplia_vqeb`llhfkdsbkalofkA^i^o^k+Drfab@ljmibqb+y
KDrfab@ljmibqb

]]
end)
