DugisGuideViewer:RegisterGuide("Enchanting 1-450", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-+Eltbsbo)vlr`^kpqfiirpbqefpdrfab^qiltboibsbip)vlr$iigrpqe^sbqlj^hbprobvlr^obefdebklrdeibsbiqljlsblkqlqebkbuqpqbm+y
KKlqbyKyBk`e^kqfkd`^k_b^sbovbumbkpfsbqo^abphfiiqlibsbi+Fcvlr^obefdeibsbi)qov^ka_rvdobbkfqbjplccqeb^r`qflkelrpbqe^q^obob^iiv`eb^mqlafpbk`e^kq+Fcvlr^obiltibsbi)hbbm^iilcvlrodobbk^ka_irbafp`^oabafqbjpqlafpbk`e^kq+Vlr`^k^iplibsbiq^filofkd^kaafpbk`e^kqqelpbfqbjp^ptbii+Tfqe>ojlo^kaTb^mlkSbiirjp^s^fi^_ib)vlr`^kj^hbp`oliiplcvlrobk`e^kqp^kapbiiqelpblkqeb>r`qflkElrpb+y
KQo^fkbopyKyQebqo^fkbopifpqba^obqeblkbpfkLodofjj^o)EbiicfobMbkfkpri^^kaA^i^o^k+L_sflrpivvlr`^krpblqebop^pvlrpbbcfq+y

KQo^fk>mmobkqf`bBk`e^kqfkdyKyDla^k%20+5)05+2&+yyWyLodofjj^oyyMJyBk`e^kqfkdy42y

?X@lmmboOlaZyKy?rv^X@lmmboOlaZcolj^kbk`e^kqprmmivsbkalo+yyIy3/.4yyMyBk`e^kqfkd/y
K.*/XOrkba@lmmboOlaZyKy.uX@lmmboOlaZ).uXPqo^kdbArpqZ).uXIbppboJ^df`Bppbk`bZ+yyMyBk`e^kqfkd/y
K/*3-Afpbk`e^kqfkdyKyAfpbk`e^kqfkdfqbjptfiiibsbivlrql^j^ufrjrjlc3-+yyMyBk`e^kqfkd3-y
K/*4-XBk`e^kq?o^`bo*JfkloEb^iqeZyKy.-uXPqo^kdbArpqZ+yyMyBk`e^kqfkd4-y

KQo^fkGlrokbvj^kBk`e^kqfkdyKyDla^k%20+5)05+2&+yyWyLodofjj^oyyMJyBk`e^kqfkdy.2-y

K4-*.--XBk`e^kq?o^`bo*JfkloPq^jfk^ZyKy6-uXPqo^kdbArpqZ+yyMyBk`e^kqfkd.--y
K.--*.-.XOrkbaPfisboOlaZyKy.uXPfisboOlaZ)3uXPq^o_dbArpqZ)0uXDob^qboJ^df`Bppbk`bZ).uXOrkba@lmmboOlaZ+yyMyBk`e^kqfkd.-.y
K.-.*..-XDob^qboJ^df`T^kaZyKy6uXPfjmibTllaZ)6uXDob^qboJ^df`Bppbk`bZ+yyMyBk`e^kqfkd..-y
?XBk`e^kq@il^h*Jfklo>dfifqvZyKyHritf^%12+2)26+2&yyWyPqlkbq^ilkJlrkq^fkpyyMyBk`e^kqfkd.0-y
?XBk`e^kq?o^`bo*IbppboPqobkdqeZyKyHritf^%12+2)26+2&yyWyPqlkbq^ilkJlrkq^fkpyyMyBk`e^kqfkd/--y
K..-*.0-XBk`e^kq@il^h*Jfklo>dfifqvZyKy/-uXIbppbo>pqo^iBppbk`bZ+yyMyBk`e^kqfkd.0-y

KQo^fkBumboqBk`e^kqfkdyKyDla^k%20+5)05+2&+yyWyLodofjj^oyyMJyBk`e^kqfkdy//2y

K.0-*.22XBk`e^kq?o^`bo*IbppboPq^jfk^ZyKy2-uXPlriArpqZ+yyMyBk`e^kqfkd.22y
K.22*.23XOrkbaDliabkOlaZyKy.uXDliabkOlaZ).uXFofabp`bkqMb^oiZ)/uXDob^qbo>pqo^iBppbk`bZ)/uXPlriArpqZ.uXOrkbaPfisboOlaZ+yyMyBk`e^kqfkd.23y
K.23*.32XBk`e^kq?o^`bo*IbppboPqobkdqeZyKy/-uXPlriArpqZ+yyMyBk`e^kqfkd.32y
K.32*.5-XBk`e^kq@ebpq*Dob^qboEb^iqeZyKy12uXPlriArpqZ+yyMyBk`e^kqfkd.5-y
K.5-*/--XBk`e^kq?o^`bo*PqobkdqeZyKy/-uXSfpflkArpqZ+yyMyBk`e^kqfkd/--y

KQo^fk>oqfp^kBk`e^kqfkdyKyDla^k%20+5)05+2&+yyWyLodofjj^oyyMJyBk`e^kqfkdy0--y

K/--*/-.XOrkbaQorbpfisboOlaZyKy.uXQorbpfisboOlaZ).uX?i^`hMb^oiZ)/uXDob^qboJvpqf`Bppbk`bZ)/uXSfpflkArpqZ).uXOrkbaDliabkOlaZ+yyMyBk`e^kqfkd/-.y
K/-.*/-2XBk`e^kq?o^`bo*PqobkdqeZyKy2uXSfpflkArpqZ+yyMyBk`e^kqfkd/-2y
K/-2*//2XBk`e^kq@il^h*Dob^qboAbcbkpbZyKy3-uXSfpflkArpqZ+yyMyBk`e^kqfkd//2y
K//2*/0-XBk`e^kqDilsbp*>dfifqvZyKy2uXSfpflkArpqZ)2uXIbppboKbqeboBppbk`bZ+yyMyBk`e^kqfkd/0-y
K/0-*/02XBk`e^kq?llqp*Pq^jfk^ZyKy/2uXSfpflkArpqZ+yyMyBk`e^kqfkd/02y
K/02*/1-XBk`e^kq@ebpq*PrmbofloEb^iqeZyKy0-uXSfpflkArpqZ+yyMyBk`e^kqfkd/1-y
K/1-*/12XBk`e^kq?llqp*Ibppbo>``ro^`vZyKy/-uXSfpflkArpqZ)2uXIbppboKbqeboBppbk`bZ+yyMyBk`e^kqfkd/12y
K/12*/2-XBk`e^kq?o^`bo*Dob^qboPqobkdqeZyKy.-uXSfpflkArpqZ)2uXDob^qboKbqeboBppbk`bZ+yyMyBk`e^kqfkd/2-y
?XClojri^7IbppboJ^k^LfiZyKyPlia_vH^kf^fkPfifqerp%2/+-)06+3&yyWyPfifqerpyyIy/-421yyMyBk`e^kqfkd/3-y
K/2-*/3-XIbppboJ^k^LfiZyKy0-uXAob^jArpqZ)/-uXMromibIlqrpZ).-uX@ovpq^iSf^iZ+yyMyBk`e^kqfkd/3-y
K/3-*/32XBk`e^kq?o^`bo*Dob^qboFkqbiib`qZyKy.2uXIbppboBqbok^iBppbk`bZ+yyMyBk`e^kqfkd/32y
?XBk`e^kqPefbia*Dob^qboPq^jfk^ZyKyA^kfbi?^oqibqq%31+6)05+0&+Qefpfp^?lMob`fmb+yyWyRkabo`fqvyyIy.3/.4yyMyBk`e^kqfkd/52y
K/32*/52XBk`e^kqPefbia*Dob^qboPq^jfk^ZyKy.--uXAob^jArpqZ+yyMyBk`e^kqfkd/52y
K/52*/6-XBk`e^kqDilsbp*Dob^qbo>dfifqvZyKy.2uXFiirpflkArpqZ).-uXIbppboBqbok^iBppbk`bZ+yyMyBk`e^kqfkd/6-y
K/6-*/66XBk`e^kq@ebpq*J^gloJ^k^ZyKy5-uXFiirpflkArpqZ+yyMyBk`e^kqfkd/66y
?XClojri^7Orkba>o`^kfqbOlaZyKyIlobi^bTfkqboplkd%15+2)06+3&)fkJllkdi^ab+yyIy.3/10yyWyJllkdi^abyyMyBk`e^kqfkdy0-.
K/66*0--XOrkba>o`^kfqbOlaZyKy.uX>o`^kfqbOlaZ).uXDliabkMb^oiZ).-uXFiirpflkArpqZ)1uXDob^qboBqbok^iBppbk`bZ).uXOrkbaQorbpfisboOlaZ)/uXI^odb?ofiif^kqPe^oaZ+yyMyBk`e^kqfkd0--y

KQo^fkJ^pqboBk`e^kqfkdyKyCbi^kkf^%2/+0)03+-&+yyWyEbiicfobMbkfkpri^yyMJyBk`e^kqfkdy042y

K0--*0-.XOrkbaCbiFolkOlaZyKy.uXCbiFolkOlaZ)1uXDob^qboBqbok^iBppbk`bZ)3uXI^odb?ofiif^kqPe^oaZ).uXOrkba>o`^kfqbOlaZ+yyMyBk`e^kqfkd0-.y
K0-.*0.-XBk`e^kq?o^`bo*>pp^riqZyKy3-uX>o`^kbArpqZ+yyMyBk`e^kqfkd0.-y
K0.-*0.2XBk`e^kq?o^`bo*?o^tkZyKy0-uX>o`^kbArpqZ+yyMyBk`e^kqfkd0.2y
K0.2*0/2XBk`e^kqDilsbp*>pp^riqZyKy5-uX>o`^kbArpqZ+yyMyBk`e^kqfkd0/2y
?XClojri^7Bk`e^kqPefbia*J^gloPq^jfk^ZyKy?lrdeqcoljJ^a^jbOr_v%30+3)4-+-&yyWyPe^qqo^qe@fqvyyIy/5/5/yyMyBk`e^kqfkd002y
?XClojri^7PrmbofloTfw^oaLfiZyKy?lrdeqcoljJ^a^jbOr_v%30+3)4-+-&yyWyPe^qqo^qe@fqvyyIy//230yyMyBk`e^kqfkd02-y
K0/2*002XBk`e^kqPefbia*J^gloPq^jfk^ZyKy.2-uX>o`^kbArpqZ+yyMyBk`e^kqfkd002y
K002*01-XBk`e^kqPefbia*Obpfifbk`bZyKy2uXI^odbMofpj^qf`Pe^oaZ)/-uXIbppboMi^k^oBppbk`bZ+yyMyBk`e^kqfkd01-y
K01-*02-XPrmbofloTfw^oaLfiZyKy0-uX>o`^kbArpqZ).-uXKfdeqj^obSfkbZ).-uXFj_rbaSf^iZ+yyMyBk`e^kqfkd02-y
K02-*02.XOrkba>a^j^kqfqbOlaZyKy.uX>a^j^kqfqbOlaZ)5uXDob^qboMi^k^oBppbk`bZ)5uXI^odbMofpj^qf`Pe^oaZ).uXMofj^iJfdeqZ).uXOrkbaCbiFolkOlaZ+yyMyBk`e^kqfkd02.y

KQo^fkDo^kaJ^pqboBk`e^kqfkdyKyBk`e^kqboK^iqe^kfp%06+1)1-+5&+yyWyA^i^o^kyyMJyBk`e^kqfkdy1/2y

K02.*03-XBk`e^kq@il^h*PmbbaZyKy3-uXFkcfkfqbArpqZ+yyMyBk`e^kqfkd03-y
K03-*04-XBk`e^kq?o^`bop*PqofhfkdZyKy3-uXFkcfkfqbArpqZ+yyMyBk`e^kqfkd04-y
K04-*042XBk`e^kq@ebpq*PrmboPq^qpZyKy/-uXFkcfkfqbArpqZ).-uXIbppbo@lpjf`Bppbk`bZ+yyMyBk`e^kqfkd042y
K042*043XOrkbaBqbokfrjOlaZyKy.uXBqbokfrjOlaZ)3uXDob^qboMi^k^oBppbk`bZ)3uX>o`^kbArpqZ).uXOrkba>a^j^kqfqbOlaZ+yyMyBk`e^kqfkd043y
K043*052XBk`e^kq?o^`bop*Bu`bmqflk^iFkqbiib`qZyKy.--uXfkcfkfqbArpqZ+yyMyBk`e^kqfkd052y
K052*062XBk`e^kq?llqp*F`bt^ihboZyKy5-uXfkcfkfqbArpqZ).-uX@ovpq^iifwbaT^qboZ+yyMyBk`e^kqfkd062y
K062*1--XBk`e^kq?o^`bop*Dob^qboPmbiimltboZyKy1-uFkcfkfqbArpq)/-uXIbppbo@lpjf`Bppbk`b+yyMyBk`e^kqfkd1--y
K1--*1-2XBk`e^kq@il^h*Prmboflo>dfifqvZyKy1-uXfkcfkfqbArpqZ+yyMyBk`e^kqfkd1-2y
K1-2*1.2XBk`e^kqDilsbp*BumboqfpbZyKy./-uXfkcfkfqbArpqZ+yyMyBk`e^kqfkd1.2y
K1.2*1/-XBk`e^kq?llqp*Dob^qboPmfofqZyKy2-uFkcfkfqbArpq)2uXDob^qbo@lpjf`Bppbk`bZ+yyMyBk`e^kqfkd1/-y
K1/-*1/2XBk`e^kqPefbia*AbcbkpbZyKy0-uFkcfkfqbArpq)0-uXBqbok^iB^oqeZ+yyMyBk`e^kqfkd1/2y
K1/2*1/3XOrkbaQfq^kfrjOlaZyKy.uXQfq^kfrjOlaZ)1-uXFkcfkfqbArpqZ)./uXDob^qbo@lpjf`Bppbk`bZ)5uXAob^jPe^oaZ).uXOrkbaBqbokfrjOlaZ+yyMyBk`e^kqfkd1/3y
K1/3*10-XBk`e^kqPefbia*AbcbkpbZyKy/1uFkcfkfqbArpq)/1uXBqbok^iB^oqeZ+yyMyBk`e^kqfkd10-y
?XClojri^7Bk`e^kq@il^h*Jfdeqv>ojloZyKyPlia_vS^kbpp^PbiibopfkA^i^o^k%05+6)1-+0&clo1uXAob^jPe^oaZ+yyWyA^i^o^kyyIy1114.yyMyBk`e^kqfkd102y
?XClojri^7Bk`e^kqDilsbp*>ojpj^kZyKyPlia_vS^kbpp^PbiibopfkA^i^o^k%05+6)1-+0&clo1uXAob^jPe^oaZ+yyWyA^i^o^kyyIy11152yyMyBk`e^kqfkd112y
K10-*102XBk`e^kq@il^h*Jfdeqv>ojloZyKy32uXFkcfkfqbArpqZ).-uXDob^qbo@lpjf`Bppbk`bZ+yyMyBk`e^kqfkd102y
K102*112XBk`e^kqDilsbp*>ojpj^kZyKy/-uXAob^jPe^oaZ)5-uXBqbok^iB^oqeZ+yyMyBk`e^kqfkd112y

K112*12-yKyQebob^ob^cbtlqeboob`fmbpvlr`^k_rvcoljS^kbpp^Pbiibopqe^qvlr`^kpbiilsboqo^abqldbqvlrophfiirmp+Drfab@ljmibqb+y
KDrfab@ljmibqb

]]
end)
