DugisGuideViewer:RegisterGuide("First Aid 1-450", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-+Eltbsbo)vlr`^kpqfiirpbqefpdrfab^qiltboibsbip)vlr$iigrpqe^sbqlj^hbprobvlr^obefdebklrdeibsbiqljlsblkqlqebkbuqpqbm+y
KQo^fkbopyKyQebqo^fkbopifpqba^obqeblkbpfkLodofjj^o)EbiicfobMbkfkpri^^kaA^i^o^k+L_sflrpivvlr`^krpblqebop^pvlrpbbcfq+y

KQo^fk>mmobkqf`bCfopq>fayKy>oklh%01+.)51+1&+yyWyLodofjj^oyyMJyCfopq>fay42y

K.*1-XIfkbk?^ka^dbZyKy3-uXIfkbk@ilqeZ+yyMyCfopq>fa1-y
K1-*42XEb^svIfkbk?^ka^dbZyKy5-uXIfkbk@ilqeZ+yyMyCfopq>fa42y

KQo^fkGlrokbvj^kCfopq>fayKy>oklh%01+.)51+1&+yyWyLodofjj^oyyMJyCfopq>fay.2-y

K42*5-XEb^svIfkbk?^ka^dbZyKy/-uXIfkbk@ilqeZ+yyMyCfopq>fa5-y
K5-*..2XTlli?^ka^dbZyKy2-uXTlli@ilqeZ+yyMyCfopq>fa..2y
K..2*.2-XEb^svTlli?^ka^dbZyKy.--uXTlli@ilqeZ+yyMyCfopq>fa.2-y

KQo^fkBumboqCfopq>fayKy>oklh%01+.)51+1&+yyWyLodofjj^oyyMJyCfopq>fay//2y

K.2-*.5-XPfih?^ka^dbZyKy1-uXPfih@ilqeZ+yyMyCfopq>fa.5-y
K.5-*/.-XEb^svPfih?^ka^dbZyKy5-uXPfih@ilqeZ+yyMyCfopq>fa/.-y

KQo^fk>oqfp^kCfopq>fayKy>oklh%01+.)51+1&+yyWyLodofjj^oyyMJyCfopq>fay0--y

K/.-*/1-XJ^dbtb^sb?^ka^dbZyKy1-uXJ^dbtb^sb@ilqeZ+yyMyCfopq>fa/1-y
K/1-*/3-XEb^svJ^dbtb^sb?^ka^dbZyKy5-uXJ^dbtb^sb@ilqeZ+yyMyCfopq>fa/3-y
K/3-*/6-XOrkb`ilqe?^ka^dbZyKy1-uXOrkb`ilqe@ilqeZ+yyMyCfopq>fa/6-y

KQo^fkJ^pqboCfopq>fayKy>obpbii^%/3+0)3/+-&+yyWyEbiicfobMbkfkpri^yyMJyCfopq>fay042y

K/6-*00-XEb^svOrkb`ilqe?^ka^dbZyKy./-uXOrkb`ilqe@ilqeZ+yyMyCfopq>fa00-y
K00-*02-XKbqebotb^sb?^ka^dbZyKy1-uXKbqebotb^sb@ilqeZ+yyMyCfopq>fa02-y

KQo^fkDo^kaJ^pqboCfopq>fayKyLifp^oo^qebHfka%04+2)03+4&+yyWyA^i^o^kyyMJyCfopq>fay12-y

K02-*1--XColpqtb^sb?^ka^dbZyKy3-uXColpqtb^sb@ilqeZ+yyMyCfopq>fa1--y
KXJ^kr^i7Eb^svColpqtb^sb?^ka^dbZyKyQefp_llhfp^tloiaaolm+y
K1--*12-XEb^svColpqtb^sb?^ka^dbZyKy.1-uXColpqtb^sb@ilqeZ+yyMyCfopq>fa12-y

KDrfab@ljmibqb+
]]
end)
