DugisGuideViewer:RegisterGuide("Leatherworking 1-450", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-+Eltbsbo)vlr`^kpqfiirpbqefpdrfab^qiltboibsbip)vlr$iigrpqe^sbqlj^hbprobvlr^obefdebklrdeibsbiqljlsblkqlqebkbuqpqbm+y
KQo^fkbopyKyQebqo^fkbopifpqba^obqeblkbpfkLodofjj^o)EbiicfobMbkfkpri^^kaA^i^o^k+L_sflrpivvlr`^krpblqebop^pvlrpbbcfq+y

KQo^fk>mmobkqf`bIb^qebotlohfkdyKyH^olibh%3/+5)11+2&+yyWyLodofjj^oyyMJyIb^qebotlohfkdy42y

K.*0-XIfdeq>ojloHfqZyKy0-uXIfdeqIb^qeboZ+yyMyIb^qebotlohfkd0-y
K0-*12XE^kapqfq`ebaIb^qebo?llqpZyKy0-uXIfdeqIb^qeboZ).2uX@l^opbQeob^aZ+yyMyIb^qebotlohfkd12y
K12*22XOrddbaIb^qeboM^kqpZyKy2-uXIfdeqIb^qeboZ)2-uX@l^opbQeob^aZ+yyMyIb^qebotlohfkd22y

KQo^fkGlrokbvj^kIb^qebotlohfkdyKyH^olibh%3/+5)11+2&+yyWyLodofjj^oyyMJyIb^qebotlohfkdy.2-y

K22*52XBj_lppbaIb^qeboDilsbpZyKy6-uXIfdeqIb^qeboZ)3-uX@l^opbQeob^aZ+yyMyIb^qebotlohfkd52y
K5-*.--XCfkbIb^qebo?biqZyKy./-uXIfdeqIb^qeboZ)1-uX@l^opbQeob^aZ+Hbbmqebpb+yyMyIb^qebotlohfkd.--y
K.--*..2X@robaJbafrjEfabZyKy.2uXJbafrjEfabZ).2uXP^iqZ+Hbbmqebpb+yyMyIb^qebotlohfkd..2y
K..2*./2XA^ohIb^qebo?llqpZyKy1-uXJbafrjIb^qeboZ)/-uXCfkbQeob^aZ).-uXDo^vAvbZ+yyMyIb^qebotlohfkd./2y
K./2*.0-XA^ohIb^qebo@il^hZyKy1-uXJbafrjIb^qeboZ)2uXCfkbQeob^aZ)2uXDo^vAvbZ+yyMyIb^qebotlohfkd.0-y
K.0-*.12XA^ohIb^qebo?biqZyKy.2uXCfkbIb^qebo?biqZ).2uX@robaJbafrjEfabZ)0-uXCfkbQeob^aZ).2uXDo^vAvbZ+yyMyIb^qebotlohfkd.12y

KQo^fkBumboqIb^qebotlohfkdyKyH^olibh%3/+5)11+2&+yyWyLodofjj^oyyMJyIb^qebotlohfkdy//2y

K.12*.2-XEfiij^k$pIb^qeboDilsbpZyKy4-uXJbafrjIb^qeboZ)/-uXCfkbQeob^aZ+yyMyIb^qebotlohfkd.2-y
K.2-*.3-X@robaEb^svEfabZyKy.-uXEb^svEfabZ)0-uXP^iqZ+P^sbqebpb)vlr$iikbba^qib^pq/-clocrqrobob`fmbp+yyMyIb^qebotlohfkd.3-y
K.3-*.42XEb^sv>ojloHfqZyKy42uXEb^svIb^qeboZ).2uXCfkbQeob^aZ+yyMyIb^qebotlohfkd.42y
K.42*.5-XDr^oaf^kM^kqpZyKy3-uXEb^svIb^qeboZ).-uXCfkbQeob^aZ).-uX?liqlcPfih@ilqeZ+yyMyIb^qebotlohfkd.5-y
K.5-*.6-X?^o_^of`PelriabopZyKy5-uXEb^svIb^qeboZ).-uXCfkbQeob^aZ).-uX@robaEb^svEfabZ+yyMyIb^qebotlohfkd.6-y
K.6-*/--XDr^oaf^kDilsbpZyKy1-uXEb^svIb^qeboZ).-uXPfihbkQeob^aZ).-uX@robaEb^svEfabZ+yyMyIb^qebotlohfkd/--y
K/--*//-XQef`h>ojloHfqZyKy.--uXQef`hIb^qeboZ)/-uXPfihbkQeob^aZ+yyMyIb^qebotlohfkd//-y

KQo^fk>oqfp^kIb^qebotlohfkdyKyH^olibh%3/+5)11+2&+yyWyLodofjj^oyyMJyIb^qebotlohfkdy0--y

K//-*/0-XKfdeqp`^mbEb^a_^kaZyKy2-uXQef`hIb^qeboZ)/-uXPfihbkQeob^aZ+yyMyIb^qebotlohfkd/0-y
K/0-*/2-XKfdeqp`^mbM^kqpZyKy/5-uXQef`hIb^qeboZ)5-uXPfihbkQeob^aZ+yyMyIb^qebotlohfkd/2-y
K/2-*/3-XOrddba>ojloHfqZyKy2-uXOrddbaIb^qeboZ+yyMyIb^qebotlohfkd/3-y
K/3-*/5-XTf`hbaIb^qeboD^rkqibqpZyKy.3-uXOrddbaIb^qeboZ)/-uXOrkbQeob^aZ)/-uX?i^`hAvbZ+yyMyIb^qebotlohfkd/5-y
K/5-*/52XTf`hbaIb^qebo?o^`bopZyKy1-uXOrddbaIb^qeboZ)2uXOrkbQeob^aZ)2uX?i^`hAvbZ+yyMyIb^qebotlohfkd/52y
K/52*0--XTf`hbaIb^qeboEb^a_^kaZyKy.5-uXOrddbaIb^qeboZ).2uXOrkbQeob^aZ).2uX?i^`hAvbZ+yyMyIb^qebotlohfkd0--y

KQo^fkJ^pqboIb^qebotlohfkdyKy?^ofjPmfiqellc%23+/)05+3&+yyWyEbiicfobMbkfkpri^yyMJyIb^qebotlohfkdy042y

K0--*0.2XHklqefab>ojloHfqZyXKy3-uXHklqefabIb^qeboZ+yyMyIb^qebotlohfkd0.2y
K0.2*0/-XTfiaAo^bkfpeDilsbpZyKy12uXHklqefabIb^qeboZ).2uXOrkbQeob^aZ+yyMyIb^qebotlohfkd0/-y
K0/-*0/2XQef`hAo^bkf`M^kqpZyKy2-uXHklqefabIb^qeboZ).-uXOrkbQeob^aZ+yyMyIb^qebotlohfkd0/2y
K0/2*00-XEb^svHklqefabIb^qeboZyKy/2uXHklqefabIb^qeboZ+yyMyIb^qebotlohfkd00-y
K00-*01-XQef`hAo^bkf`SbpqZloXTfiaAo^bkfpeSbpqZyKy0-uXEb^svHklqefabIb^qeboZ)0-uXOrkbQeob^aZ+yyMyIb^qebotlohfkd01-y
K01-*02-XP`^ibaAo^bkf`?llqpZyKy/-uXEb^svHklqefabIb^qeboZ)0-uXOrkbQeob^aZ)/-uXCbiP`^ibpZ+yyMyIb^qebotlohfkd02-y

KQo^fkDo^kaJ^pqboIb^qebotlohfkdyKyAf^kb@^kkfkdp%01+1)/6+2&+yyWyA^i^o^kyyMJyIb^qebotlohfkdy12-y

K02-*042X?lob^k>ojloHfqZyKy.--uX?lob^kIb^qeboZ+yyMyIb^qebotlohfkd042y
K042*06-X>o`qf`DilsbpZyKy.2-uX?lob^kIb^qeboZ+yyMyIb^qebotlohfkd06-y
K06-*062XEb^sv?lob^kIb^qeboZyKy0-uX?lob^kIb^qeboZ+yyMyIb^qebotlohfkd062y
K062*1--XEb^sv?lob^k>ojloHfqZyKy/-uXEb^sv?lob^kIb^qeboZ+yyMyIb^qebotlohfkd1--y
K1--*1.2XA^ohColpqp`^ibIbddfkdpZyKy3-uXEb^sv?lob^kIb^qeboZ)42uX@ovpq^iifwbaT^qboZ+yyMyIb^qebotlohfkd1.2y
K1.2*1/-XM^`hlcBkaibppMl`hbqpZyKy1-uXEb^sv?lob^kIb^qeboZ+yyMyIb^qebotlohfkd1/-y
?XM^qqbok7Lsbo`^pq?o^`bopZyKy?o^bdPqlrq_b^oa%04+3)/6+2&@lpq70uXEb^sv?lob^kIb^qeboZ+yyWyA^i^o^kyyMyIb^qebotlohfkd1/2y
?XM^qqbok7Lsbo`^pqE^kato^mpZyKy?o^bdPqlrq_b^oa%04+3)/6+2&@lpq70uXEb^sv?lob^kIb^qeboZ+yyWyA^i^o^kyyMyIb^qebotlohfkd10-y
K1/-*1/2XLsbo`^pq?o^`bopZyKy1-uXEb^sv?lob^kIb^qeboZ)2uXBqbok^iT^qboZ+yyMyIb^qebotlohfkd1/2y
K1/2*10-XLsbo`^pqE^kato^mpZyKy2-uXEb^sv?lob^kIb^qeboZ)2uXBqbok^iT^qboZ+yyMyIb^qebotlohfkd10-y
K10-*11-XIbd>ojlopZyKyJ^hb^k^pploqjbkqlcIbd>ojloHfqp+/-uX>o`qf`CroZ).-uXColwbkLo_Z)/-uXKbor_f^k@efqfkZlo/-uXF`vAo^dlkp`^ibZ+yyMyIb^qebotlohfkd11-y

K11-*12-yKyAb^ibop@elf`blkqebkbuq.-ibsbip+Vlr`^kkltj^hbqeb^iiqebqo^fk^_ibbmf`m^qqbokp+Vlr`^kbfqebomlpqvlroqo^abphfiilkQo^ab@e^qloj^hbfqbjpqe^qvlr`^kpbiilotb^o+Drfab@ljmibqby
KDrfab@ljmibqb

]]
end)
