DugisGuideViewer:RegisterGuide("Lockpicking 1-400", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyIl`hmf`hfkdfpib^okbacoljqebOldrbQo^fkbop^kafpibsbibatfqevlro`roobkqibsbi+Qlcfkavlroj^uIl`hmf`hfkdPhfii)q^hbvlro`roobkqibsbijriqfmifba_v2+Qefpdrfabtfiidllsboil`h_lubp)vlr`^k^iplibsbi_vmf`hml`hbqfkderj^klfajl_p^kamf`hfkdqebfogrkh_lubp+y

K.*.--Eloab?r``^kbbo$pPqolkd_luyKyMf`hX?r``^kbbo$pPqolkd_luZclrkafkqebpefmkb^oO^`ebq%32+-)12+2&yyWyQeb?^oobkpyyMyIl`hmf`hfkd.--y

K.--*.3-?^qqboaCllqil`hboyKyX?^qqboaCllqil`hboZfkTfkapeb^o@o^d%31)24&+yyWyPqlkbq^ilkJlrkq^fkpyyMyIl`hmf`hfkd.3-y

K.3-*//2?^qqboaCllqil`hboyKyX?^qqboaCllqil`hboZ%.2-&^kaXAbkqbaCllqil`hboZ%.42&fk>kdloCloqobpp%1/)/6&+yyWy?^ai^kapyyMyIl`hmf`hfkd//2y

K//2*/2-AbkqbaCllqil`hboyKyXAbkqbaCllqil`hboZ+Qebpb^obclrkafkqeb`^sbpvpqbj^ka`^jmp+%06)15&+yyWyPb^ofkdDlodbyyMyIl`hmf`hfkd/2-y

K/2-*0--P`^oibqCllqil`hboyKyDlqlQvo$pE^ka%42)04&)^kamf`hml`hbqerj^kflajl_pclogrkh_lubp^kamf`hXP`^oibqCllqil`hboZ+yyWyB^pqbokM^idrbi^kapyyMyIl`hmf`hfkd0--y

K0--*0/2Tf`hbo@ebpqyKy%11)3.&+@^k^iplmf`hml`hbqXPqolkdGrkh_luZcoljjl_p+yyWyW^kd^oj^opeyyMyIl`hmf`hfkd0/2y

K0/2*042AbkqbaCllqil`hboyKy%4.)5-&yyWyK^do^kayyMyIl`hmf`hfkd042y

K042*1--Obfkclo`baGrkh_lubpyKyMf`hml`hbqErj^klfajl_pfkKloqeobka+yyMyIl`hmf`hfkd1--y

KDrfab@ljmibqb

]]
end)
