DugisGuideViewer:RegisterGuide("Tailoring 1-450", nil, "Horde", "E", function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob5-+Eltbsbo)vlr`^kpqfiirpbqefpdrfab^qiltboibsbip)vlr$iigrpqe^sbqlj^hbprobvlr^obefdebklrdeibsbiqljlsblkqlqebkbuqpqbm+y
KQo^fkbopyKyQebqo^fkbopifpqba^obqeblkbpfkLodofjj^o)EbiicfobMbkfkpri^^kaA^i^o^k+L_sflrpivvlr`^krpblqebop^pvlrpbbcfq+y

KQo^fk>mmobkqf`bQ^filoyKyJ^d^o%30+1)2-+-&+yyWyLodofjj^oyyMJyQ^filofkdy42y

K.*/2X?liqlcIfkbk@ilqeZyKy2-uXIfkbk@ilqeZ+yyMyQ^filofkd/2y
K/2*2-XIfkbk?biqZyKy/2uX?liqlcIfkbk@ilqeZ)/2uX@l^opbQeob^aZ+yyMyQ^filofkd2-y
K2-*42XObfkclo`baIfkbk@^mbZyKy2-uX?liqlcIfkbk@ilqeZ)42uX@l^opbQeob^aZ+yyMyQ^filofkd42y

KQo^fkGlrokbvj^kQ^filoyKyJ^d^o%30+1)2-+-&+yyWyLodofjj^oyyMJyQ^filofkdy.2-y

K42*6-X?liqlcTllibk@ilqeZyKy.2uXTlli@ilqeZ+yyMyQ^filofkd6-y
K6-*.--XDobbkTllibkSbpqZyKy/-uX?liqlcTllibk@ilqeZ)/-uXCfkbQeob^aZ).-uXDobbkAvbZ+yyMyQ^filofkd.--y
K.--*..-XDo^vTllibkPefoqZyKy/-uX?liqlcTllibk@ilqeZ).-uXCfkbQeob^aZ).-uXDo^vAvbZ+yyMyQ^filofkd..-y
K..-*./2XAlr_ib*pqfq`ebaTllibkPelriabopZyKy12uX?liqlcTllibk@ilqeZ)0-uXCfkbQeob^aZ+yyMyQ^filofkd./2y
K./2*.1-X?liqlcPfih@ilqeZyKy3-uXPfih@ilqeZ+yyMyQ^filofkd.1-y
K.1-*.12X>wrobPfihM^kqpZyKy/-uX?liqlcPfih@ilqeZ).2uXCfkbQeob^aZ).-uX?irbAvbZ+yyMyQ^filofkd.12y

KQo^fkBumboqQ^filoyKyJ^d^o%30+1)2-+-&+yyWyLodofjj^oyyMJyQ^filofkdy//2y

K.12*.3-X>wrobPfihEllaZyKy0-uX?liqlcPfih@ilqeZ).2uXCfkbQeob^aZ)0-uX?irbAvbZ+yyMyQ^filofkd.3-y
K.3-*.4-XPfihEb^a_^kaZyKy0-uX?liqlcPfih@ilqeZ)/-uXCfkbQeob^aZ+yyMyQ^filofkd.4-y
K.4-*.42XCloj^iTefqbPefoqZyKy.2uX?liqlcPfih@ilqeZ)2uXCfkbQeob^aZ).-uX?ib^`eZ+yyMyQ^filofkd.42y
K.42*.5/X?liqlcJ^dbtb^sbZyKy1-uXJ^dbtb^sbZ+yyMyQ^filofkd.5/y
K.5/*.52XObaPt^pe_r`hibo$pPefoqZyKy6uX?liqlcPfih@ilqeZ)0uXPfihbkQeob^aZ)3uXObaAvbZ+yyMyQ^filofkd.52y
K.52*/-2X@ofjplkPfihSbpqZyKy5-uX?liqlcPfih@ilqeZ)1-uXCfkbQeob^aZ)1-uXObaAvbZ+yyMyQ^filofkd/-2y
K/-2*//-X?i^`hJ^dbtb^sbIbddfkdpZyKy12uX?liqlcJ^dbtb^sbZ)12uXPfihbkQeob^aZ+yyMyQ^filofkd//-y

KQo^fk>oqfp^kQ^filoyKyJ^d^o%30+1)2-+-&+yyWyLodofjj^oyyMJyQ^filofkdy0--y

K//-*/0-X?i^`hJ^dbtb^sbDilsbpZyKy/-uX?liqlcJ^dbtb^sbZ)/-uXEb^svPfihbkQeob^aZ+yyMyQ^filofkd/0-y
K/0-*/2-X?i^`hJ^dbtb^sbEb^a_^kaZyKy3-uX?liqlcJ^dbtb^sbZ)1-uXEb^svPfihbkQeob^aZ+yyMyQ^filofkd/2-y
K/2-*/24X?liqlcOrkb`ilqeZyKy1-uXOrkb`ilqeZ+yyMyQ^filofkd/24y
K/24*/42XOrkb`ilqe?biqZyKy21uX?liqlcOrkb`ilqeZ).5uXOrkbQeob^aZ+yyMyQ^filofkd/42y
K/42*/62XOrkb`ilqeDilsbpZyKy.--uX?liqlcOrkb`ilqeZ)1-uXOrkbQeob^aZ+yyMyQ^filofkd/62y
K/62*0--XOrkb`ilqeEb^a_^kaZyKy0-uX?liqlcOrkb`ilqeZ).-uXOrkbQeob^aZ+yyMyQ^filofkd0--y

KQo^fkJ^pqboQ^filoyKyA^ifkk^%23+3)04+/&+yyWyEbiicfobMbkfkpri^yyMJyQ^filofkdy042y

K0--*0.2X?liqlcKbqebotb^sbZyKy42uXKbqebotb^sb@ilqeZ+yyMyQ^filofkd0.2y
K0.2*0/-XKbqebotb^sb?biqZyKy.2uX?liqlcKbqebotb^sbZ)2uXOrkbQeob^aZ+yyMyQ^filofkd0/-y
K0/-*0/2XKbqebotb^sbDilsbpZyKy/-uX?liqlcKbqebotb^sbZ)2uXOrkbQeob^aZ).-uXHklqefabIb^qeboZ+yyMyQ^filofkd0/2y
K0/2*002XKbqebotb^sbM^kqpZyKy3-uX?liqlcKbqebotb^sbZ).-uXOrkbQeob^aZ+yyMyQ^filofkd002y
K002*012XKbqebotb^sb?llqpZyKy3-uX?liqlcKbqebotb^sbZ).-uXOrkbQeob^aZ)/-uXHklqefabIb^qeboZ+yyMyQ^filofkd012y
?XM^qqbok7Kbqebotb^sbQrkf`ZyKyBffk%33+4)35+1&)fkPe^qqo^qe@fqv+yyIy/.564yyWyPe^qqo^qe@fqvyyMyQ^filofkd02-y
K012*02-XKbqebotb^sbQrkf`ZyKy1-uX?liqlcKbqebotb^sbZ).-uXOrkbQeob^aZ+yyMyQ^filofkd02-y

KQo^fkDo^kaJ^pqboQ^filoyKy@e^oibpTloqe%04+-)00+1&+yyWyA^i^o^kyyMJyQ^filofkdy12-y

K02-*042X?liqlcColpqtb^sbZyKy./2uXColpqtb^sb@ilqeZ+yyMyQ^filofkd042y
K042*05-XColpqtlsbk?biqZyKy.2uX?liqlcColpqtb^sbZ)2uXBqbokfrjQeob^aZ+yyMyQ^filofkd05-y
K05-*052XColpqtlsbk?llqpZyKy/-uX?liqlcColpqtb^sbZ)2uXBqbokfrjQeob^aZ+yyMyQ^filofkd052y
K052*062XColpqtlsbk@ltiZyKy2-uX?liqlcColpqtb^sbZ).-uXBqbokfrjQeob^aZ+yyMyQ^filofkd062y
K062*1--XArphtb^sb?biqZyKy02uX?liqlcColpqtb^sbZ)2uXBqbokfrjQeob^aZ+yyMyQ^filofkd1--y
KXFj_rbaColpqtb^sbZyKyVlr`^kj^hbqebFj_rbaColpqtb^sbql1-2)lophfmqlqebArphtb^sbTofpqto^mp+y
K1--*1-2X?liqlcFj_rbaColpqtb^sbZyKy.-uX?liqlcColpqtb^sbZ).-uXFkcfkfqbArpqZyyMyQ^filofkd1-2y
K1-2*1.-XArphtb^sbTofpqto^mpZyKy1-uX?liqlcColpqtb^sbZ)2uXBqbokfrjQeob^aZ+yyMyQ^filofkd1.-y
K1.-*1.2XArphtb^sbDilsbpZyKy12uX?liqlcColpqtb^sbZ)2uXBqbokfrjQeob^aZ+yyMyQ^filofkd1.2y
K1.2*1/2XArphtb^sb?llqpZyKy.--uX?liqlcColpqtb^sbZ).-uXBqbokfrjQeob^aZ+yyMyQ^filofkd1/2y
KXColpqtb^sb?^dpZyKyVlr`^kj^hbColpqtb^sb_^dpql11-)lovlr`^kj^hbqebColpqP^s^dbfqbjpqebkqebpmb`f^iqvtb^sbfqbjpql11-+y
K1/2*11-XColpqtb^sb?^dZyKy6-uX?liqlcFj_rbaColpqtb^sbZ)0-uXBqbokfrjQeob^aZ+yyMyQ^filofkd11-y

K11-*12-yKyAb^ibop@elf`blkqebkbuq.-ibsbip+Vlr`^kkltj^hb^iiqebqo^fk^_ibbmf`m^qqbokp+Vlr`^kbfqebomlpqvlroqo^abphfiilkQo^ab@e^qloj^hbfqbjpqe^qvlr`^kpbiilotb^o+Drfab@ljmibqby
KDrfab@ljmibqb

]]
end)
