
DugisGuideViewer:RegisterGuide("The Wailing Caverns (15-21)", "Blackfathom Deeps (20-24)", "Alliance", "I", function()
return [[
AAA

KIbsbi.2ObnrfobayKyVlrjrpq_b^qib^pqibsbi.2qlmf`hrmqebcliiltfkdnrbpqpyyNFAy532yyMIy.2y

OPqlojtfka@fqvyKyQo^sbiqlPqlojtfka@fqv%//+1)23&yyWyPqlojtfka@fqvyyNFAy532y
_A^ohpelobyKyQo^sbiql>r_boafkb%//+1)23&yyWyPqlojtfka@fqvyyNFAy532y
e>r_boafkbyKyFkkhbbmboP^rppfv%04)11+.&yyWyA^ohpelobyyNFAy532y
c>r_boafkbyKy@^vi^fpJllkcb^qebo%03+0)12+3&yyWyA^ohpelobyyNFAy532y
>Lkt^oaql>pebks^ibyKyQefpfp^ibsbi.5nrbpqQerkaofpTfkatb^sbo%04+1)1-+/&yyWyA^ohpelobyyNFAy.-42/y
O>pebks^ibyKyQo^sbiql>pebks^ib%/6).2&yyWy>pebks^ibyyNFAy532y
O>pqo^k^^oyKyQo^sbiql>pqo^k^^o%01+1)15&yyWy>pebks^ibyyNFAy532y
c>pqo^k^^oyKyA^bivpef^%01+1)15&yyWy>pebks^ibyyNFAy532y
QLkt^oaql>pebks^ibyKyO^bkbTlicorkkbo%03+3)16+3&yyWy>pebks^ibyyNFAy.-42/y
OQeb?^oobkpyKyQo^sbiqlQeb?^oobkp%15+6)1+4&yyNFAy532yyWyQeb?^oobkpy

OO^q`ebqyKyQo^sbiqlO^q`ebq%3/+3)04+2&yyNFAy532yyWyQeb?^oobkpy
cO^`ebqyKy?o^dlh%30+.)04+/&yyNFAy532yyWyQeb?^oobkpy

>O^mqloElokpyKyJb_lhJfwwvofu%3/+1)04+3&yyNFAy532yyWyQeb?^oobkpy
@O^mqloElokpyKyD^qebo2XFkq^`qO^mqloElokpZcoljPrkp`^ibP`vqeb`i^tp%2/+/3)13+2&yyNFAy532yyWyQeb?^oobkpy
QO^mqloElokpyKyJb_lhJfwwvofu%3/+1)04+3&yyNFAy532yyWyQeb?^oobkpy
>Pj^oqAofkhpyKyJb_lhJfwwvofu%3/+1)04+3&yyNFAy.16.yyWyQeb?^oobkpy

K@ifj_RmQebEfiiEbob++yKyDlql%14)01+4&^kaqf`hqefppqbmyyNFAy.154yyWyQeb?^oobkpy
KOrkPqo^fdeqQlQefpPmlq++yKyOrkqlqebollclcqebT^fifkd@^sbok%13+-5)02+.0&^kaqf`hqefppqbmyyNFAy.154yyWyQeb?^oobkpy
KAolmqlqeb$klpb8^kabkqbo`^sbqlvlroibcqyKy%12+60)03+/0&^kaqf`hqefppqbmyyNFAy.154yyWyQeb?^oobkpy
>Absf^qbBo^af`^qflkyKyB_or%12+63)02+42&yyNFAy.154yyWyQeb?^oobkpy
>Absf^qbEfabpyKyK^im^h%12+63)02+42&yyNFAy.153yyWyQeb?^oobkpy

OQebT^fifkd@^sbokpyKyRpbqebArkdblkCfkaboqlnrbrbcloT^fifkd@^sbok)_b^qib^pqibsbi.5fpob`ljjbkabayyWyQerkabo?irccyyNFAy6.1yyFy

KDl^i7Hfii1Ib^aboplcqebC^kdyKyVlrodl^iebobfpqlhfii^ii1ib^aboplcqebc^kdplqe^qvlr`^kprjjlkJrq^krpqebAbslrobo^qqebbka^kadbq^kbuqo^nrbpq+Qeb_bpqloabofpIloa@l_o^ek;I^av>k^`lkao^;IloaMevq^p;IloaPbombkqfp%cliiltqebdobbkifkbqlob^`eMevq^p^kaPbombkqfp&yyNFAy365.y

@Pj^oqAofkhpyKy@liib`q3uXT^fifkdBppbk`bpZcoljqebLlwbpfkT^fifkd@^sbokpyyNFAy.16.y
@Absf^qbBo^af`^qflkyKyHfiiqebobnrfobaAbsf^qbp^iiclrkafkT^fifkd@^sbokp)vlrpelriacfkfpeqefp^rqlj^qf`^iivfcvlr`ljmibqbqebfkpq^k`byyNFAy.154y

KPrjjlk^kahfiiJrq^krpyKyFcvlrhfiiba^iiclroib^aboplcqebc^kd)vlr`^kq^ihqlqebQ^robkAorfa_vqebbkqo^k`blcT^fifkd@^sbokpql_bdfkqebbsbkqcloqebcfk^i_lppyyNFAy365.yyIy.-11.y

>QebDiltfkdPe^oayKyIllqqebdiltfkdpe^oacoljqebcfk^iJroil`_lppql^``bmqqefpnrbpqyyRy.-11.yyNFAy365.y

OQeb?^oobkpyKyQbibmloq_^`hlrqqlQeb?^oobkpyyNFAy365.yyFy
OO^q`ebqyKyQo^sbiqlO^q`ebq%3/+3)04+2&yyWyQeb?^oobkpyyNFAy365.y
KQ^ihqlPmrqqbos^sibyKyQ^ihqlPmrqqbos^sib%30)04+/&yyNLyPmb^htfqepljblkbfkO^q`ebq^_lrqqebDiltfkdPe^oayyNFAy365.yyWyQeb?^oobkpy
QPj^oqAofkhpyKyJb_lhJfwwvofu%3/+1)04+3&yyNFAy.16.yyWyQeb?^oobkpy

QQebDiltfkdPe^oayKyC^ii^P^dbtfka%15+/)0/+5&pebifsbplkqlmlcqebjlrkq^fkyyNFAy365.yyWyQeb?^oobkpy
>FkKfdeqj^obpyKyC^ii^P^dbtfka%15+/)0/+5&pebifsbplkqlmlcqebjlrkq^fkyyNFAy004-yyWyQeb?^oobkpy
QAbsf^qbBo^af`^qflkyKyB_or%12+63)02+42&yyNFAy.154yyWyQeb?^oobkpy
@Absf^qbEfabpyKy@liib`q/-uXAbsf^qbEfabpZcoljqebAbsf^qbPbombkqpfkpfabT^fifkd@^sbokp)qefpjfdeqq^hbvlr/orkplcT^fifkd@^sbokplovlr`^k`ljmibqbqefpplillrqpfabqebbkqo^k`bqlT^fifkd@^sbokp%13+/)0/+2&)%14+4)00&yyNFAy.153yyWyQeb?^oobkpy
QAbsf^qbEfabpyKyK^im^h%12+63)02+42&yyNFAy.153yyWyQeb?^oobkpy

E>r_boafkbyRy3615yyNFAy004-y
_Qbiao^ppfiyKyQo^sbiqlQbiao^ppfi%00+/)1-+.&yyWyA^ohpelobyyNFAy004-y
OA^ok^pprpyKyRpbqebmloq^i^q%22+6)56+5&yyWyQbiao^ppfiyyNFAy004-y
QFkKfdeqj^obpyKyJ^qeobkdvi?b^ot^ihbo%02+//)5+-&yyNFAy004-yyWyA^ok^pprpy

KDrfab@ljmibqb+Qf`hQl@lkqfkrbQl?i^`hc^qeljAbbmp%/-*/4&yKyQf`hql`lkqfkrbql?i^`hc^qeljAbbmp%/-*/4&*Riqfj^qbTlTDrfab+`ljy
]]
end)
