DugisGuideViewer:RegisterGuide("The Deadmines (15-20)", "The Wailing Caverns (15-21)", "Alliance", "I", function()
return [[
AAA

KIbsbi.1ObnrfobayKyQebjfkfjrjibsbiql_bdfkqebpbnrbpqfpibsbi.1)qf`hql`lkqfkrbyyNFAy32yyMIy.1y

OPbkqfkbiEfiiyKyQo^sbiqlPbkqfkbiEfii%23+0)14+3&yyWyTbpqc^iiyyNFAy32y
>QebAbcf^p?olqeboella%M^oq.&yWyTbpqc^iiyyKyDov^kPqlrqj^kqib%23+0)14+3&yyNFAy32y

OArphtllayKyQo^sbiqlArphtlla%..+2)30&yyWyArphtllayyNFAy32y
OA^ohpefobyKyQo^sbiqlA^ohpefob%40+4)13+.&yyWyArphtllayyNFAy32y
cA^ohpefobyKyCbif`f^Jbifkb%44+2)11+0&yyWyArphtllayyNFAy32y
OObaofadbJlrkq^fkpyKyQo^sbiqlObaofadbJlrkq^fkp%6+3)54+1&yyWyObaofadbJlrkq^fkpyyNFAy32y
>Bk`ol^`efkdDkliipyKyDr^oaM^ohbo%.2+2)4.+.&yyWyObaofadbJlrkq^fkpyyNFAy/11y
cObaofadbJlrkq^fkpyWyObaofadbJlrkq^fkpyyKy>ofbk^Pqlojcb^qebo%0-+6)26+5&yyNFAy32y
QBk`ol^`efkdDkliipyKyAbmrqvCbialk%0-+5)3-+.&yyWyObaofadbJlrkq^fkpyyNFAy/11y
QQebAbcf^p?olqeboella%M^oq.&yWyObaofadbJlrkq^fkpyyKyTfibvqeb?i^`h%/3+3)12+0&yyNFAy32y
>QebAbcf^p?olqeboella%M^oq/&yWyObaofadbJlrkq^fkpyyKyTfibvqeb?i^`h%/3+3)12+0&yyNFAy.0/y

CPbkqfkbiEfiiyWyObaofadbJlrkq^fkpyyKy>ofbk^Pqlojcb^qebo%0-+6)26+5&yyNFAy.0/y

QQebAbcf^p?olqeboella%M^oq/&yWyTbpqc^iiyyKyDov^kPqlrqj^kqib%23+0)14+3&yyNFAy.0/y

>QebAbcf^p?olqeboella%M^oq0&yWyTbpqc^iiyyKyDov^kPqlrqj^kqib%23+0)14+3&yyNFAy.02y

CPqlojtfka@fqvyWyTbpqc^iiyyKyQelo%23+2)2/+3&yyNFAy/-1-y

ePqlojtfka@fqvyKyFkkhbbmbo>iifplk%3-+2)42+/&yyWyPqlojtfka@fqvyyNFAy/-1-y
>Rkabodolrka>pp^riqyWyPqlojtfka@fqvyyKyPelkfqebPefibkq%3/+4)01+2&yyNFAy/-1-y
>Le?olqebo+++yWyPqlojtfka@fqvyyKyTfiaboQefpqibkbqqib%4-+/)1-+6&yyNFAy.34y
>@liib`qfkdJbjlofbpyWyPqlojtfka@fqvyyKyTfiaboQefpqibkbqqib%4-+/)1-+6&yyNFAy.35y

QQebAbcf^p?olqeboella%M^oq0&yWyPqlojtfka@fqvyyKyJ^pqboJ^qef^pPe^t%45+2)4-+4&yyNFAy.02y
>QebAbcf^p?olqeboella%M^oq1&yWyPqlojtfka@fqvyyKyJ^pqboJ^qef^pPe^t%45+2)4-+4&yyNFAy.1.y

CPbkqfkbiEfiiyWyPqlojtfka@fqvyyKyArkd^oIlkdaofkh%4-+6)4/+4&yyNFAy.1.y

QQebAbcf^p?olqeboella%M^oq1&yWyTbpqc^iiyyKyDov^kPqlrqj^kqib%23+0)14+3&yyNFAy.1.y
>QebAbcf^p?olqeboella%M^oq2&yWyTbpqc^iiyyKyDov^kPqlrqj^kqib%23+0)14+3&yyNFAy.1/y

@QebAbcf^p?olqeboella%M^oq2&yWyTbpqc^iiyyKyCfkaqebJbppbkdbotelt^ihpcoljJllk_ollh%11+2)36+3&qlqebDlia@l^pqNr^oov%/6+5)13+2&^karmqlqebG^kdlIllbJfkb%11+6)/0+.&yyNFAy.1/y
QQebAbcf^p?olqeboella%M^oq2&yWyTbpqc^iiyyKyDov^kPqlrqj^kqib%23+0)14+3&yyNFAy.1/y

>QebAbcf^p?olqeboella%M^oq3&yWyTbpqc^iiyyKyQebAbcf^pQo^fqlo%22+4)14+3&yyNFAy.22y
@QebAbcf^p?olqeboella%M^oq3&yWyTbpqc^iiyyKyBp`loqQebAbcf^pQo^fqloqlJllk_ollhyyNFAy.22y
@Le?olqebo+++yKyQo^sbialtkqlqebAb^ajfkbMob*Fkpq^k`b^ob^^kahfiiClobj^kQefpqibkbqqibfkQebAb^ajfkbp^olrka%1.+-)5.+-&lrqpfablcqebfkpq^k`byyNFAy.34y
@@liib`qfkdJbjlofbpyKyHfiiqebPhbibqlkp^kaWlj_fbp^olrkaQebAb^ajfkbplrqpfabqebfkpq^k`b^ka`liib`q1Jfkbop$Rkflk@^oapyyNFAy.35y

EPqlojtfka@fqvyRy3615yyNFAy.33y
QLe?olqebo+++yWyPqlojtfka@fqvyyKyTfiaboQefpqibkbqqib%4-+/)1-+6&yyNFAy.34y
Q@liib`qfkdJbjlofbpyWyPqlojtfka@fqvyyKyTfiaboQefpqibkbqqib%4-+/)1-+6&yyNFAy.35y

CPbkqfkbiEfiiyWyPqlojtfka@fqvyyKyArkd^oIlkdaofkh%4-+6)4/+4&yyNFAy.33y

QQebAbcf^p?olqeboella%M^oq3&yWyTbpqc^iiyyKyDov^kPqlrqj^kqib%23+0)14+3&yyNFAy.22y

>QebAbcf^p?olqeboella%M^oq4&yWyTbpqc^iiyyKyDov^kPqlrqj^kqib%23+0)14+3&yyNFAy.33y
>ObaPfih?^ka^k^pyWyTbpqc^iiyyKyP`lrqOfbii%23+4)14+1&yyNFAy/.1y

OQebAb^ajfkbpyKyNrbrbcloqebAb^ajfkbprpfkdqebarkdblkcfkaboyyNFAy040yyFy

@Rkabodolrka>pp^riqyKyHfiiPkbba^ka`liib`qqebXDkl^jPmb`hibpmol`hbqZcoljqebPeobaabo$p`lompbyyNFAy/-1-y
@QebAbcf^p?olqeboella%M^oq4&yKyHfiiBatfkS^k@ibbc)qebcfk^i_lpplcQebAb^ajfkbpyyNFAy.33y
@ObaPfih?^ka^k^pyKy@liib`qqebpbcoljqebjl_pfkpfabqebfkpq^k`byyNFAy/.1y
>QebRkpbkqIbqqboyKyXQebRkpbkqIbqqboZaolmmba_vBatfkS^k@ibbcfkQebAb^ajfkbpyyRy/541yyNFAy040y

OTbpqc^iiyKyQbibmloq_^`hqlTbpqc^ii%23+0)14+3&yyWyTbpqc^iiyyFy

QQebAbcf^p?olqeboella%M^oq4&yWyTbpqc^iiyyKyDov^kPqlrqj^kqib%23+0)14+3&yyNFAy.33y
QObaPfih?^ka^k^pyWyTbpqc^iiyyKyP`lrqOfbii%23+4)14+1&yyNFAy/.1y

EPqlojtfka@fqvyRy3615y

QRkabodolrka>pp^riqyWyPqlojtfka@fqvyyKyPelkfqebPefibkq%3/+4)01+2&yyNFAy/-1-y

KDrfab@ljmibqb+Qf`hQl@lkqfkrbQlQebT^fifkd@^sbokp%.2*/.&yKyQf`hql`lkqfkrbqlQebT^fifkd@^sbokp%.2*/.&*Riqfj^qbTlTDrfab+`ljy

]]
end)
