DugisGuideViewer:RegisterGuide("Blackfathom Deeps (20-24)", "The Stockade (21-25)", "Alliance", "I", function()
return [[
AAA

KIbsbi/-ObnrfobayKyVlrjrpq_b^qib^pqibsbi/-qlmf`hrmqebcliiltfkdnrbpqpyyNFAy64.yyMIy/-y

O@fqvlcFolkclodbyKyQo^sbiqlFolkclodb%2-+2)3+4&yyWyFolkclodbyyNFAy64.y
>HkltibadbfkqebAbbmpyWyFolkclodbyyKyDboofd?lkbdofm%2-+2)3+4&yyNFAy64.y
eFolkclodbyWyFolkclodbyyKyFkkhbbmboCfob_obt%.5+3)2.+2&yyNFAy0432y

CPqlojtfka@fqvyWyFolkclodbyyKyDovqeQeroabk%23+-)16+-&yyNFAy0432y
>Qeb@loormqflk>_ol^ayWyPqlojtfka@fqvyyKy>odlpKfdeqtefpmbo%03+2)34+2&yyNFAy0432y
_A^ohpelobyKyQo^sbiql>r_boafkb%//+1)23&yyWyPqlojtfka@fqvyyNFAy..65y
QQeb@loormqflk>_ol^ayWyA^ohpelobyyKyDbope^i^Kfdeqtefpmbo%05+1)10+.&yyNFAy0432y
>Obpb^o`efkdqeb@loormqflkyWyA^ohpelobyyKyDbope^i^Kfdeqtefpmbo%05+1)10+.&yyNFAy./42y
_Qbiao^ppfiyKyQo^sbiqlQbiao^ppfi%00+/)1-+.&yyWyA^ohpelobyyNFAy..65y
OA^ok^pprpyKyRpbqebmloq^i^q%22+6)56+5&yyWyQbiao^ppfiyyNFAy..65y

>FkPb^o`elcQe^biofayWyA^ok^pprpyyKyA^tkt^q`eboPe^bai^pp%22+2)/1+4&yyNFAy..65y
>QtfifdeqC^iipyWyA^ok^pprpyyKy>odbkqDr^oaJ^k^alp%22+3)/1+2&yyNFAy..66y

O?i^`hc^qeljAbbmpyKyNrbrbclo?i^`hc^qeljAbbmprpfkdvlroarkdblkcfkaboyyNFAy./--yyFy

@HkltibadbfkqebAbbmpyKyFkqebolljtebobvlrcfdeqDe^jll*o^)qeb`ebpqfpgrpqqlvlroofdeq^pvlrbkqboqebolljtfqeqroqibp+Fqfprkaboqebt^qbofkqeb^i`lsbgrpqqlqebofdeqlkqebKloqebkayyNFAy64.y
QFkPb^o`elcQe^biofayKyFkqebolljtebobvlrcfdeqDe^jll*o^)ptfjrkabot^qbolkqebplrqetbpqpfab^kaqeolrdeqeb`^sbqlcfka>odbkqDr^oaQe^biofayyNFAy..65y
>?i^`hc^qeljSfii^fkvyKy>odbkqDr^oaQe^biofa)Fkpfabqebfkpq^k`byyNFAy./--y
@?i^`hc^qeljSfii^fkvyKyHfiiQtfifdeqIloaHbiofp^kaillqefpeb^ayyNFAy./--y
@Obpb^o`efkdqeb@loormqflkyKy@liib`qbacoljqebjl_pfkpfablolrqpfabqebfkpq^k`byyNFAy./42y
@QtfifdeqC^iipyKy@liib`qbacoljqebQtfifdeqjl_pfkpfabqebfkpq^k`byyNFAy..66y

OA^ok^pprpyKyQbibmloq_^`hqlA^ohpelob%05+1)10+.&yyWyA^ohpelobyyFy

Q?i^`hc^qeljSfii^fkvyWyA^ok^pprpyyKyA^tkt^q`eboPbidloj%23+-)/2+3&yyNFAy./--y
QQtfifdeqC^iipyWyA^ok^pprpyyKy>odbkqDr^oaJ^k^alp%22+3)/1+2&yyNFAy..66y

OA^ok^pprpyKyQo^sbiqlOrqebo^kSfii^db%0-+5)1.+1&yyWyA^ok^pprpy

C>r_boafkbyKyQo^sbiqlA^ohpelob%25+1)61&yyWyQbiao^ppfiy

QObpb^o`efkdqeb@loormqflkyWyA^ohpelobyyKyDbope^i^Kfdeqtefpmbo%05+1)10+.&yyNFAy./42y

EFolkclodbyRy3615y

QHkltibadbfkqebAbbmpyWyFolkclodbyyKyDboofd?lkbdofm%2-+2)3+4&yyNFAy64.y

KDrfab@ljmibqb+Qf`hQl@lkqfkrbQlQebPql`h^ab%/.*/2&yKyQf`hql`lkqfkrbqlQebPql`h^ab%/.*/2&*Riqfj^qbTlTDrfab+`ljy

]]
end)
