
DugisGuideViewer:RegisterGuide("|cfff0c502Class Quest:|r Shaman / Warlock (20+)", nil, "Alliance", "I", function()
return [[
AAA

KIbsbi/-Obnrfobay@yT^oil`hyyKyQefpfp^Ibsbi/-nrbpqclokbtPrjjlkPr`r__rpphfii)Qefpnrbpqtlk$q_b^s^fi^_ibfcvlr^iob^avmf`hbarmAbslrobolcPlripcoljRkabo`fqvlo@^obkafkPrjjlkpcoljPfisbojllk@fqv+>_^kalkqelpblkb^kamf`hqefplkbfkpqb^a_b`^rpbfqfpjr`eb^pfboyyNFAy.2-4yyMIy/-y
KIbsbi/-Obnrfobay@yPe^j^kyyKyQefpfp^Ibsbi/-nrbpqcloPe^j^kpqld^fkqebfoT^qboQlqbjpyyNFAy.20-yyMIy/-y
KPe^j^k^kaT^oil`hplkivyKyVlrtlk$q_b^_ibqlpbbqebdrfabrkibppvlr$ob^Pe^j^kloT^oil`hyy@yOldrb)M^i^afk)Erkqbo)Aorfa)Mofbpq)J^db)Ab^qeHkfdeqy

OPqlojtfka@fqvy@yT^oil`hyyKyQo^sbiqlPqlojtfka@fqv%15+/)12+3&yyWyPqlojtfka@fqvy
>AbslrobolcPlripyKyD^hfkqebA^oh_fkabo%06+0)52+/&yy@yT^oil`hyyWyPqlojtfka@fqvyyNFAy.4.3y
_A^ohpeloby@yT^oil`hyyKyQ^hbqeb_l^qqlA^ohpelob%//+1)23&yyWyPqlojtfka@fqvy
O>pqo^k^^oy@yT^oil`hyyKyCliiltqebol^ab^pq%04)16+0&yyNFAy.--5yyWy>pebks^iby
c>pqo^k^^oy@yT^oil`hyyKyA^bivpef^%01+2)15&yyNFAy.--5yyWy>pebks^iby

OQeb?^oobkpyKyQo^sbiqlQeb?^oobkp%15+2)..+0&yy@yT^oil`hyyNFAy.405yyWyQeb?^oobkpy
QAbslrobolcPlripyKyQ^h^oqebPbbo%16+0)24+.&yy@yT^oil`hyyWyQeb?^oobkpyyNFAy.4.3y
>Eb^oqptllayKyQ^h^oqebPbbo%16+0)24+.&yy@yT^oil`hyyWyQeb?^oobkpyyNFAy.405y
OO^q`ebqy@yT^oil`hyyKyQo^sbiqlO^q`ebq%30+.)04+/&yyWyQeb?^oobkpyyNFAy.406y
cO^q`ebqy@yT^oil`hyyKyQo^sbiqlO^q`ebq%30+.)04+/&yyWyQeb?^oobkpyyNFAy.406y
C>pqo^k^^oy@yT^oil`hyyKy?o^dlh%30+.)04+/&yyWyQeb?^oobkpyyNFAy.406y
@Eb^oqptllayKyObqofbsbqebXEb^oqptllaZcolj>pebks^ib^q%0.+1)0.+1&yyIy36./yy@yT^oil`hyyNFAy.405y

C>r_boafkby@yT^oil`hyyKyA^bivpef^%01+2)15&yyNFAy62-5yyWy>pebks^iby
_Pqlojtfka@fqvy@yT^oil`hyyKyQ^hbqeb?l^qqlPqlojtfka@fqv%0/+1)10+3&yyWyA^ohpelobyyNFAy/46y
QEb^oqptllayKyD^hfkqebA^oh_fkabo%06+0)52+/&yy@yT^oil`hyyWyPqlojtfka@fqvyyNFAy.405y
>Qeb?fkafkdy@yT^oil`hyyKyD^hfkqebA^oh_fkabo%06+0)52+/&yyWyPqlojtfka@fqvyyNFAy.406y
@Qeb?fkafkdy@yT^oil`hyyKyRpbXAldo^k$pMbka^kqZqlprjjlk^Pr``r_rp^kahfiifqyyRy36.0yyNFAy.406y
QQeb?fkafkdy@yT^oil`hyyKyD^hfkqebA^oh_fkabo%06+0)52+/&yyWyPqlojtfka@fqvyyNFAy.406y

OQebBula^oy@yPe^j^kyyKyQo^sbiqlQebBula^o%00+/)/0+0&yyNFAy6300yyWyQebBula^oy
>@^iilcT^qbo%M^oq.&y@yPe^j^kyyKyPri^^%00+/)/0+0&yyWyQebBula^oyyNFAy62-/y
Q@^iilcT^qbo%M^oq.&y@yPe^j^kyyKyC^opbboKl_rkal%0-+/)/5+4&yyWyQebBula^oyyNFAy62-/y
>@^iilcT^qbo%M^oq/&y@yPe^j^kyyKyC^opbboKl_rkal%0-+/)/5+4&yyWyQebBula^oyyNFAy62-.y
C?illajvpqFpiby@yPe^j^kyyKyPqbme^klp%35+3)30+0&yyWyQebBula^oyyNFAy62-0y
Q@^iilcT^qbo%M^oq/&y@yPe^j^kyyKy>nrblrp%0.+4).3+.&yyRy/054.yyNFAy62-.yyWy?illajvpqFpiby
>@^iilcT^qbo%M^oq0&y@yPe^j^kyyKy>nrblrp%0.+4).3+.&yyNFAy62-0yyWy?illajvpqFpiby
@@^iilcT^qbo%M^oq0&y@yPe^j^kyyKyHfiiClribaT^qboPmfofq%0-)06&clo3uXClriBppbk`bZyyNFAy62-0yyWy?illajvpqFpiby
Q@^iilcT^qbo%M^oq0&y@yPe^j^kyyKy>nrblrp%0.+4).3+.&yyNFAy62-0yyWy?illajvpqFpiby
>@^iilcT^qbo%M^oq1&y@yPe^j^kyyKy>nrblrp%0.+4).3+.&yyNFAy62-1yyWy?illajvpqFpiby
CQebBula^oy@yPe^j^kyyKyI^^kal%24+3)21&yyNFAy6300y

_A^ohpeloby@yPe^j^kyyKyQ^hbqeb?l^qql>r_boafkb%/.+3)21&yyWy>wrobjvpqFpibyyNFAy62-5y
O>pqo^k^^oy@yPe^j^kyyKyCliiltqebol^ab^pq%04)16+0&yyNFAy62-5yyWy>pebks^iby
c>pqo^k^^oy@yPe^j^kyyKyA^bivpef^%01+2)15&yyNFAy62-5yyWy>pebks^iby
@@^iilcT^qbo%M^oq1&y@yPe^j^kyyKyDlql%00)34&^karpbXBjmqv?lq^?^dZyyRy/0416yyNFAy62-1yyWy>pebks^iby

C>r_boafkby@yPe^j^kyyKyA^bivpef^%01+2)15&yyNFAy62-5yyWy>pebks^iby
_>wrobjvpqFpiby@yPe^j^kyyKyQ^hbqebjfaaib_l^qql>wrobjvpqFpib%0-+4)1.&yyNFAy62-5yyWyA^ohpeloby
C?illajvpqFpiby@yPe^j^kyyKyPqbme^klp%35+3)30+0&yyWyQebBula^oyyNFAy62-5y
Q@^iilcT^qbo%M^oq1&y@yPe^j^kyyKy>nrblrp%0.+4).3+.&yyWy?illajvpqFpibyyNFAy62-1y
>@^iilcT^qbo%M^oq2&y@yPe^j^kyyKy>nrblrp%0.+4).3+.&yyWy?illajvpqFpibyyNFAy62-5y
@@^iilcT^qbo%M^oq2&y@yPe^j^kyyKyDlqlqeb`^jmpfqb^q%/2)1.&^karpbXPhfklcMrobpqT^qboZqlprjjlk^kahfiiQbi$^qeflkqebFjmrobyyRy/042.yyWy?illajvpqFpibyyNFAy62-5y
Q@^iilcT^qbo%M^oq2&y@yPe^j^kyyKy>nrblrp%0.+4).3+.&yyWy?illajvpqFpibyyNFAy62-5y
>@^iilcT^qbo%M^oq3&y@yPe^j^kyyKy>nrblrp%0.+4).3+.&yyWy?illajvpqFpibyyNFAy62-6y
CQebBula^oy@yPe^j^kyyKyI^^kal%24+3)21&yyNFAy.--4yyWy?illajvpqFpiby
Q@^iilcT^qbo%M^oq3&y@yPe^j^kyyKyC^opbboKl_rkal%0.+3)0.yyWyQebBula^oyyNFAy62-6y

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
