DugisGuideViewer:RegisterGuide("The Stockade (21-25)", "Razorfen Kraul (23-28)", "Alliance", "I", function()
return [[
AAA

KIbsbi//ObnrfobayKyQebjfkfjrjibsbiql_bdfkqebpbnrbpqfpibsbi//)qf`hql`lkqfkrbyyNFAy056yyMIy//y

OPqlojtfka@fqvyKyQo^sbiqlPqlojtfka@fqv%24+3)14+5&yyWyPqlojtfka@fqvyyNFAy056y
QQebRkpbkqIbqqboyWyPqlojtfka@fqvyyKyQefpnrbpqfp^`e^fkpq^oqfkdcoljQebAb^ajfkbpdrfab)?^olp>ibupqlk%24+3)14+5&yyNFAy040y

>?^wfiQeobaayWyPqlojtfka@fqvyyKy?^olp>ibupqlk%24+3)14+5&yyNFAy056y
Q?^wfiQeobaayWyPqlojtfka@fqvyyKyT^oabkQebit^qbo%2.+3)36+2&yyNFAy056y

>QebPql`h^abOflqpyWyPqlojtfka@fqvyyKyT^oabkQebit^qbo%2.+3)36+2&yyNFAy06.y
>NrbiiQebRmofpfkdyWyPqlojtfka@fqvyyKyT^oabkQebit^qbo%2.+3)36+2&yyNFAy054y
>Qeb@lilolc?illayWyPqlojtfka@fqvyyKyKfhls^O^phli%43+0)30+2&)T^kabofkdKM@yyNFAy055y

CObaofadbJlrkq^fkpyWyPqlojtfkayyKyArkd^oIlkdaofkh%4-+6)4/+4&yyNFAy053y

>Te^q@ljbp>olrka+++yWyObaofadbJlrkq^fkpyyKyDr^oa?boqlk%/3+3)13+.&yyNFAy053y

CA^ohpefobyWyObaofadbJlrkq^fkpyyKy>ofbk^Pqlojcb^qebo%0-+6)26+5&yyNFAy044y
>@ofjb^kaMrkfpejbkqyWyArphtllayyKy@lrk`fij^kJfiipqfmb%4/+-)14+5&yyNFAy044y

CIl`eJla^kyWyArphtllayyKyCbif`f^J^ifkb%44+2)11+2&yyNFAy0-0y
OTbqi^kapyWyTbqi^kapyyKyQo^sbiqlTbqi^kap%22+/)1-+4&rpfkdqebKloqeD^qbM^ppqrkkbiyyNFAy0-0y

OJbkbqefiE^o_loyWyTbqi^kapyyKyOrkqlJbkbqefiE^o_lo%6+2)26+4&yyNFAy045y
cJbkbqefiE^o_loyKyPebiibf?olkafo%6+2)26+4&yyWyTbqi^kapyyNFAy045y
CPqlojtfka@fqvyWyTbqi^kapyyKyPebiibf?olkafo%6+2)26+4&yyNFAy045y

OQebPql`h^abyKyNrbrbcloQebPql`h^abrpfkdvlroarkdblkcfkaboyyNFAy053yyFy

@Te^q@ljbp>olrka+++yKyHfiiQ^odlooqebAob^afklkblcqebolljpfkqeb`bkqoblcqebfkpq^k`b^kaillqefpeb^ayyNFAy053y
@@ofjb^kaMrkfpejbkqyKyHfiiAbuqobkT^oafkqebibcqpfab`e^j_bolcqebfkpq^k`b^kaillqefpe^kayyNFAy044y
@QebPql`h^abOflqpyKyHfii?^wfiQeobaa)qebcfk^i_lppfkqebofdeqpfab`e^j_bolcqebfkpq^k`b^kaillqefpeb^ayyNFAy06.y
@NrbiiQebRmofpfkdyKyHfiibklrdelcb^`ejl_fkpfabqebfkpq^k`byyNFAy054y
@Qeb@lilolc?illayKy@liib`q_^ka^k^pcoljqebjl_pfkpfabqebfkpq^k`byyNFAy055y

OPqlojtfka@fqvyKyQbibmloq_^`hqlPqlojtfka@fqv%43+0)30+2&yyWyPqlojtfka@fqvyyNFAy06/yyFy

QQeb@lilolc?illayWyPqlojtfka@fqvyyKyKfhls^O^phli%43+0)30+2&)T^kabofkdKM@yyNFAy055y
QQebPql`h^abOflqpyWyPqlojtfka@fqvyyKyT^oabkQebit^qbo%2.+3)36+2&yyNFAy06.y
QNrbiiQebRmofpfkdyWyPqlojtfka@fqvyyKyT^oabkQebit^qbo%2.+3)36+2&yyNFAy054y

>Qeb@roflrpSfpfqloyWyPqlojtfka@fqvyyKyT^oabkQebit^qbo%2.+3)36+2&yyNFAy06/y
QQeb@roflrpSfpfqloyWyPqlojtfka@fqvyyKy?^olp>ibupqlk%24+3)14+5&yyNFAy06/y

>Pe^altlcqebM^pqyWyPqlojtfka@fqvyyKy?^olp>ibupqlk%24+3)14+5&yyNFAy060y
QPe^altlcqebM^pqyWyPqlojtfka@fqvyyKyJ^pqboJ^qef^pPe^t%45+1)4-+4&yyNFAy060y

>Illhql^kLiaCofbkayWyPqlojtfka@fqvyyKyJ^pqboJ^qef^pPe^t%45+1)4-+4&yyNFAy02-y
QIllhql^kLiaCofbkayWyPqlojtfka@fqvyyKyBiifkdQof^p%33+.)41+/&yyNFAy02-y

>Fkcfiqo^qfkdqeb@^pqibyWyPqlojtfka@fqvyyKyBiifkdQof^p%33+.)41+/&yyNFAy/412y
QFkcfiqo^qfkdqeb@^pqibyWyPqlojtfka@fqvyyKyQvoflk%40+/)02+5&yyNFAy/412y

>FqbjplcPljb@lkpbnrbk`byWyPqlojtfka@fqvyyKyQvoflk%40+/)02+5&yyNFAy/413y
@FqbjplcPljb@lkpbnrbk`byWyBitvkkClobpqyyKyObqofsb/^mmibpcolj@i^o^@e^oibp$elrpb^q%01+.)24+/&^kad^qebo0Pfih@ilqepyyNFAy/413y
QFqbjplcPljb@lkpbnrbk`byWyPqlojtfka@fqvyyKyQvoflk%40+/)02+5&yyNFAy/413y

KIbsbi/4ObnrfobayKyQebjfkfjrjibsbiql`lkqfkrbqefpdrfabfpibsbi/4arbqlafccf`riqv)qf`hql`lkqfkrbyyNFAy101yyMIy/4y

>Qeb>qq^`hyWyPqlojtfka@fqvyyKyQvoflk%40+/)02+5&yyNFAy101y
@Qeb>qq^`hyWyPqlojtfka@fqvyyKyDlql%4/+2)02+-&qlcfkaIloaDobdloIbp`ls^o^kaJ^owlkqebPfibkq?i^ab)t^fqcloqeb`lksbop^qflkqlbkaqebkhfiiqebj_lqeyyNFAy101y
QQeb>qq^`hyWyPqlojtfka@fqvyyKyBiifkdQof^p%33+.)41+/&&yyNFAy101y

>QebEb^alcqeb?b^pqyWyPqlojtfka@fqvyyKyBiifkdQof^p%33+.)41+/&yyNFAy061y
QQebEb^alcqeb?b^pqyWyPqlojtfka@fqvyyKyJ^pqboJ^qef^pPe^t%45+1)4-+4&yyNFAy061y

>?olqeboella$pBkayWyPqlojtfka@fqvyyKyJ^pqboJ^qef^pPe^t%45+1)4-+4&yyNFAy062y
Q?olqeboella$pBkayWyPqlojtfka@fqvyyKy?^olp>ibupqlk%24+3)14+5&yyNFAy062y

>>k>rafbk`btfqeqebHfkdyWyPqlojtfka@fqvyyKy?^olp>ibupqlk%24+3)14+5&yyNFAy063y
Q>k>rafbk`btfqeqebHfkdyWyPqlojtfka@fqvyyKyHfkdTovkk%46+6)05+2&yyNFAy063y

CObaofadbJlrkq^fkpyWyPqlojtfkayyKyArkd^oIlkdaofkh%4-+6)4/+4&yyNFAy053y
QTe^q@ljbp>olrka+++yWyObaofadbJlrkq^fkpyyKyDr^oa?boqlk%/3+3)13+.&yyNFAy053y

CA^ohpefobyWyObaofadbJlrkq^fkpyyKy>ofbk^Pqlojcb^qebo%0-+6)26+5&yyNFAy044y
Q@ofjb^kaMrkfpejbkqyWyArphtllayyKy@lrk`fij^kJfiipqfmb%4/+-)14+5&yyNFAy044y

KDrfab@ljmibqb+Qf`hQl@lkqfkrbQlO^wlocbkHo^ri%/0*/5&yKyQf`hql`lkqfkrbqlO^wlocbkHo^ri%/0*/5&*Riqfj^qbTlTDrfab+`ljy

]]
end)
