
DugisGuideViewer:RegisterGuide("Razorfen Kraul (23-28)", "Gnomeregan (24-29)", "Alliance", "I", function()
return [[
AAA

KIbsbi/1+2ObnrfobayKyVlrjrpq_b^qib^pqibsbi/2qlmf`hrmqebcfk^inrbpq^cqboqeb_lpp)vlrpelriaefqibsbi/2_vqebbkalcqebfkpq^k`byyNFAy.//.yyMIy/2y

OJbkbqefiE^o_loyKyQo^sbiqlA^ohpelob%04)11&yyWyTbqi^kapyyNFAy.//.y
_Arpqt^iiltJ^opeyKyQo^sbiqlArpqt^iiltJ^ope%2)30+2&yyWyTbqi^kapyyNFAy.//.y
cQebo^jlobFpibyKy?^iaor`%34+2)2.+0&yyWyArpqt^iiltJ^opeyyNFAy.//.y
CO^q`ebqyKy?^iaor`%34+2)2.+0&yyWyArpqt^iiltJ^opeyyWyCbo^i^pyyNFAy.//.y
>?irbib^cQr_bopyKyJb_lhJfwwvofu%3/+1)04+3&yyWyQeb?^oobkpyyNFAy.//.y
KDo^_X@o^qbTfqeElibpZyKyDbqqebX@o^qbTfqeElibpZlkqebq^_ib%3/+0)04+4&yyIy255-yyWyQeb?^oobkpyyNFAy.//.y
KDo^_XPkrccibklpb@ljj^kaPqf`hZyKyDo^_XPkrccibklpb@ljj^kaPqf`hZ%3/+0)04+4&yyIy3351yyWyQeb?^oobkpyyNFAy.//.y
KDo^_XPkrccibklpbLtkbo$pJ^kr^iZyKyDo^_XPkrccibklpbLtkbo$pJ^kr^iZ%3/+0)04+4&yyIy2564yyWyQeb?^oobkpyyNFAy.//.y

OQelrp^kaKbbaibpyKyQo^sbiqlQelrp^kaKbbaibp%0.+6)/1+.&yyWyQelrp^kaKbbaibpyyNFAy..--y

KDbqXEbkofdIlkb_olt$pGlrok^iZyKyMf`hrmXEbkofdIlkb_olt$pGlrok^iZ%0-+4)/1+2&yyWyQelrp^kaKbbaibpyyNFAy..--yyIy246.y
>Ilkb_olt$pGlrok^iyKyOb^aXEbkofdIlkb_olt$pGlrok^iZ%0-+4)/1+2&yyRy246.yyNFAy..--yyWyQelrp^kaKbbaibpy
OCbo^i^pyKyQo^sbiqlCbo^i^p%55+6)1.+/&yyWyCbo^i^pyyNFAy..--y
cQe^i^k^^oyKyQevppf^k^%56+2)12+6&yyWyCbo^i^pyyNFAy..--y
QIlkb_olt$pGlrok^iyKyC^icfkabiT^vt^oabo%56+3)13+3&yyWyCbo^i^pyyNFAy..--y
>Qeb@olkblcqebHo^riyKyC^icfkabiT^vt^oabo%56+3)13+3&yyNFAy..-.yyWyCbo^i^py

OO^wlocbkHo^riyKyRpbqebarkdblkcfkaboqlnrbrbcloO^wlocbkHo^riyyNFAy..1/yyFy

@Qeb@olkblcqebHo^riyKyHfii@e^oid^O^wloci^kh^kaillqXO^wloci^kh$pJba^iiflkZyyNFAy..-.y
>Jloq^ifqvT^kbpyKyEbo^i^qeC^iilt_ollh)ebfpil`^qba_befkaqebj^fk_lppfkqebqbkqkbuqqlTfiifuqebFjmloqboyyNFAy..1/y

>TfiifuqebFjmloqboyKyCfkaTfiifuqebFjmloqbo^ka`ljmibqbqebbp`loqnrbpqyyNFAy..11y
@TfiifuqebFjmloqboyKyCliilt^kaMolqb`qTfiifuqebFjmloqboyyNFAy..11y
QTfiifuqebFjmloqboyKyTfiifuqebFjmloqboyyNFAy..11y

R@o^qbTfqeElibpyKyRpbX@o^qbTfqeElibpZqlprjjlkvlrodlmeboyyRy255-yyNFAy.//.y
@?irbib^cQr_bopyKyHbbmrpfkdvlroXPkrccibklpb@ljj^kaPqf`hZqlebimvlrcfkaqebQorccib)eb^aqlt^oapqeb^ob^tebobvlrclrkaTfiifuqebFjmloqboyyRy3351yyNFAy.//.y
@Jloq^ifqvT^kbpyKyHbbmhfiifkdqebBifqbKM@pfkpfabqebfkpq^k`brkqfivlrcfkaXQobpe^i^$pMbka^kqZyyNFAy..1/y

OQe^i^k^^oyKyQbibmloq_^`hqlQe^i^k^^o%56+3)13+3&yyWyCbo^i^pyyFy
QQeb@olkblcqebHo^riyKyC^icfkabiT^vt^oabo%56+3)13+3&yyWyCbo^i^pyyNFAy..-.y

CO^q`ebqyKyQevppf^k^%56+2)12+6&yyWyCbo^i^pyyNFAy.//.y
Q?irbib^cQr_bopyKyJb_lhJfwwvofu%3/+1)04+3&yyWyQeb?^oobkpyyNFAy.//.y

C>r_boafkbyKy?o^dlh%30+.)04+/&yyWyQeb?^oobkpy
_Qbiao^ppfiyKyQo^sbiqlQbiao^ppfi%00+/)1-+.&yyWyA^ohpelobyyNFAy64.y
OA^ok^pprpyKyRpbqebmloq^i^q%22+6)56+5&yyWyQbiao^ppfiyyNFAy64.y
QJloq^ifqvT^kbpyKyQobpe^i^C^iilt_ollh%36+2)34+2&yyWyA^ok^pprpyyNFAy..1/y

KDrfab@ljmibqb+@lkqfkrbQlDkljbobd^k%/1*/6&yKyQf`hql`lkqfkrbqlDkljbobd^k%/1*/6&*Riqfj^qbTlTDrfab+`ljy
]]
end)
