DugisGuideViewer:RegisterGuide("Gnomeregan (24-29)", "Scarlet Monestary Graveyard / Library (27-33)", "Alliance", "I", function()
return [[
AAA

KIbsbi/2ObnrfobayKyVlrjrpq_b^qib^pqibsbi/2qlmf`hrmqebcliiltfkdnrbpqpyyNFAy/6/5yyMIy/2y

OPqlojtfka@fqvyKyQo^sbiqlPqlojtfka@fqv%3/+4)01+2&yyWyPqlojtfka@fqvyyNFAy/6/5y
>Dvolaofiij^qf`Bu`^s^qflk^qlopyWyPqlojtfka@fqvyyKyPelkfqebPefibkq%3/+4)01+2&yyNFAy/6/5y
>Qfkhj^pqboLsbopm^ohyWyPqlojtfka@fqvyyKy?olqeboP^okl%2.+3)15+4&yyNFAy/6/0y

OAbbmorkQo^jyKyQ^hbqebAbbmorkQo^jqlFolkclodb%33+1)01+.&yyNFAy/6/0yyWyPqlojtfka@fqvy
O@fqvlcFolkclodbyKyBufqqlFolkclodbyyNFAy/6/0y
eFolkclodbyWyFolkclodbyyKyFkkhbbmboCfob_obt%.5+3)2.+2&yyNFAy/6/0y

QQfkhj^pqboLsbopm^ohyWyFolkclodbyyKyQfkhj^pqboLsbopm^oh%36+6)13+1&yyNFAy/6/0y

>P^sbQb`e_lq$p?o^fkyWyFolkclodbyyKyQfkhj^pqboLsbopm^oh%36+6)13+1&yyNFAy/6//y
>QebA^v>cqboyWyFolkclodbyyKyDkl^ok%36+6)16+1&yyNFAy/6/4y
>Bppbkqf^i>oqfcf`f^ipyWyFolkclodbyyKyHil`hjloqPm^kkbopm^k%35+3)12+0&yyNFAy/6/1y
>A^q^Obp`rbyWyFolkclodbyyKyJ^pqboJb`e^kf`@^pqmfmbk%4-+.)15+0&yyNFAy/60-y
>QebDo^ka?bqo^v^iyWyFolkclodbyyKyEfdeQfkhboJbhh^qlonrb%36+1)16+2&yyNFAy/6/6y

QQebA^v>cqboyWyArkJloldeyyKyLwwfbQlddibsliq%12+6)16+0&yyNFAy/6/4y
>Dkld^fkbyWyArkJloldeyyKyLwwfbQlddibsliq%12+6)16+0&yyNFAy/6/3y

H>aaibaIbmboyKyHfii>aaibaIbmborkqfivlrcfkaXTefqbMrk`e@^oaZ%//)06&yyWyArkJloldeyyIy6/46yyNFAy/60-y
OQo^fkAbmlqyKyDlaltkqebbibs^qloqlqebQo^fkAbmlqfkDkljbobd^k%//)03+6&yyWyArkJloldeyyNFAy/63/y
KDbqXVbiiltMrk`e@^oaZyKyRpbqebqebJ^qofu>j^`efkbfkqebQo^fkAbmlqqldbqqebXVbiiltMrk`e@^oaZ%//)0/+2&yyWyArkJloldeyyIy6/5-yyNFAy/60-y
@P^sbQb`e_lq$p?o^fkyKyIl`^qbafkqebkloqem^oqlcDkljbobd^kfkqebil^afkdollj%/-+.)0/&)lrqpfabqebfkpq^k`b+Hfiiefj^kaillqQb`e_lq$pJbjlov@lobyyNFAy/6//yyWyArkJloldey

KObqrokqlLwwfbQlddibsliqyKyPq^kakbuqLwwfbQlddibsliq%12+6)16+0&_bclobnrbrfkdcloDkljbobd^kplvlr`^kalnrf`hqrok*fk^kaqbibmloq_^`hqlDkljbobd^klk`bvlr`ljmibqbDkld^fkbyyWyArkJloldeyyNFAy/6/3y

ODkljbobd^kyKyNrbrbcloDkljbobd^krpfkdvlroarkdblkcfkaboyyNFAy/6/3yyFy

@Dkld^fkbyKyRpbqebXBjmqvIb^abk@liib`qflkMef^iZlkFoo^af^qbaFks^aboploFoo^af^qbaMfii^dbopfkpfabqebfkpq^k`b)rpbqebfqbjtebkqebfoe^kap^obdiltfkddobbkyyRy6/50yyNFAy/6/3y

OArkJloldeyKyQbibmloqlrqlcqebarkdblk_^`hqlLwwfbQlddibsliq%12+6)16+0&clonrf`hqrokfk)ofdeq`if`hlkvlroarkdblkcfkabo_vvlrojfkfj^myyNFAy/6-1yyFyyWyArkJloldey
QDkld^fkbyWyArkJloldeyyKyLwwfbQlddibsliq%12+6)16+0&yyNFAy/6/3y
>QebLkiv@robfpJlobDobbkDiltyWyArkJloldeyyKyLwwfbQlddibsliq%12+6)16+0&yyNFAy/63/y
ODkljbobd^kyKyRpbarkdblkcfkaboqlqbibmloq_^`hfkqlqebfkpq^k`byyNFAy/6-1yyFy

KDbqX?irbMrk`e@^oaZyKyRpbqebqebJ^qofu?j^`efkbkb^oqeb@ib^kOlljyyIy6/5/yyNFAy/60-y
>>CfkbJbppyKyHbokl_bb)FkqebAlojfqlov_vqeb@ib^kOlljyyNFAy/6-1y
@>CfkbJbppyKy?ofkdHbokl_bb)qlqebcolkqbkqo^k`blcqebarkdblk)ebtfiicliiltvlryyNFAy/6-1y
@QebLkiv@robfpJlobDobbkDiltyKyRpbXEb^svIb^abk@liib`qflkMef^iZlk^ifsb@loolpfsbIrohbo+Qebfqbje^p^/elroqfjbo)fcvlrqefkhvlr$obdlfkdqlorklrqlcqfjb)qbibmloqlrq^kaqrokfqfk_bclobfqbumfobpyyRy6031yyNFAy/63/y
KDbqXObaMrk`e@^oaZyKyRpbqebqebJ^qofu@j^`efkblkBib`qol`rqflkbo3---$pmi^qclojyyIy6/5.yyNFAy/60-y
@A^q^Obp`rbyKyRpbqebJ^qofuAj^`efkb_bilt@oltaMrjjbibo6*3-%lkqebiltbpqcillo&yyNFAy/60-y
@QebDo^ka?bqo^v^iyKyHfiiJbhdfkbboQeboj^mirdd)qebcfk^i_lpplcDkljbobd^kyyNFAy/6/6y
@Bppbkqf^i>oqfcf`f^ipyKy@liib`q./Bppbkqf^i>oqfcf`f^iptef`e^obpmob^aqeolrdelrqqebfkpq^k`byyNFAy/6/1y
@Dvolaofiij^qf`Bu`^s^qflk^qlopyKy@liib`qbacolj^kvKM@tfqefkqebfkpq^k`byyNFAy/6/5y

>Dofjb*Bk`orpqbaOfkdyKyXDofjb*Bk`orpqbaOfkdZaolmmbacoljDkljbobd^kjl_p)qefptfiiobnrfobibsbi/5ql^``bmqlqebotfpbvlr`^kphfmhbbmqefpfkvlrofksbkqlov^ka^``bmqfqi^qboyyRy60/3yyNFAy/612y
QDofjb*Bk`orpqbaOfkdyKyQebPm^ohibj^qf`2/--)Fkqeb@ib^kWlkbyyNFAy/612y
>ObqroklcqebOfkdyKyQebPm^ohibj^qf`2/--)Fkqeb@ib^kWlkbyyNFAy/614y

OArkJloldeyKyBufqlrqlcqebfkpq^k`b_^`hqlArkJlolde%12+6)16+0&yyWyArkJloldeyyNFAy/615yyFy

QQebLkiv@robfpJlobDobbkDiltyWyArkJloldeyyKyLwwfbQlddibsliq%12+6)16+0&yyNFAy/63/y

O@fqvlcFolkclodbyKyQo^sbiqlFolkclodb%0-)33&yyWyFolkclodbyyNFAy/615y

QP^sbQb`e_lq$p?o^fkyWyFolkclodbyyKyQfkhj^pqboLsbopm^oh%36+6)13+1&yyNFAy/6//y
QBppbkqf^i>oqfcf`f^ipyWyFolkclodbyyKyHil`hjloqPm^kkbopm^k%35+3)12+0&yyNFAy/6/1y
QA^q^Obp`rbyWyFolkclodbyyKyJ^pqboJb`e^kf`@^pqmfmbk%4-+.)15+0&yyNFAy/60-y
QQebDo^ka?bqo^v^iyWyFolkclodbyyKyEfdeQfkhboJbhh^qlonrb%36+1)16+2&yyNFAy/6/6y

QObqroklcqebOfkdyWyFolkclodbyyKyQ^is^peabiHfppbi%03+-)1+4&yyNFAy/614y
>DkljbFjmolsbjbkqyWyFolkclodbyyKyQ^is^peabiHfppbi%03+-)1+4&yyNFAy/615y
@DkljbFjmolsbjbkqyWyFolkclodbyyKy?ofkd^Pfisbo?^o^kaJlpp>d^qbqlQ^is^peabiHfppbi%03+-)1+4zyyNFAy/615y
QDkljbFjmolsbjbkqyWyFolkclodbyyKyQ^is^peabiHfppbi%03+-)1+4&yyNFAy/615y

CPqlojtfka@fqvyWyFolkclodbyyKyDovqeQeroabk%23+-)16+-&y

QDvolaofiij^qf`Bu`^s^qflk^qlopyWyPqlojtfka@fqvyyKyPelkfqebPefibkq%3/+4)01+2&yyNFAy/6/5y

CArphtllayWyPqlojtfka@fqvyyKyArkd^oIlkdaofkh%4-+6)4/+4&y
O?llqv?^vyWyPqo^kdibqelokS^ibyyKyOrkqlP`llqv%/4+3)44+2&fk?llqv?^vy

Q>CfkbJbppyWyPqo^kdibqelokS^ibyyKyP`llqv%/4+3)44+2&yyNFAy/6-1y

KDrfab@ljmibqb+@lkqfkrbQlP`^oibqJlkbpq^ov%/4*00&yKyQf`hql`lkqfkrbqlP`^oibqJlkbpq^ovDo^sbv^oa,If_o^ov%/4*00&*Riqfj^qbTlTDrfab+`ljy

]]
end)

