DugisGuideViewer:RegisterGuide("Scarlet Monestary Graveyard / Library (27-33)", "Razorfen Downs (33-38)", "Alliance", "I", function()
return [[
AAA

KIbsbi/5ObnrfobayKyQebcliiltfkdnrbpqobnrfobpibsbi/5qlmf`hrmyyNFAy.-2-yyMIy/5y

O@fqvlcFolkclodbyKyQo^sbiqlFolkclodb%0-)33&yyWyFolkclodbyyNFAy.-2-y
>JvqelildvlcqebQfq^kpyKyIf_o^of^kJ^bM^ibarpq%41+4)./+4&yyWyFolkclodbyyNFAy.-2-y
>GlrokbvqlqebJ^opey@yJ^dbyyKyVlr`^kmf`hrmqefpnrbpqcolj^kvJ^dbQo^fkbo%/3+2)6+4&yyWyFolkclodbyyNFAy.614y

CJbkbqefiE^o_loy@yJ^dbyyKyDovqeQeroabk%22+2)14+5&yyWyFolkclodbyyNFAy.614y
_Arpqt^iiltJ^opey@yJ^dbyyKyQo^sbiqlArpqt^iiltJ^ope%2)30+2&yyWyTbqi^kapyyNFAy.614y
eQebo^jlobFpiby@yJ^dbyyKyFkkhbbmboG^kbkb%33+3)12+/&yyWyArpqt^iiltJ^opeyyNFAy.614y

QGlrokbvqlqebJ^opey@yJ^dbyyKyPqf`hqlqebol^a^kacfkaQ^_bqe^%13)24+.&yyNFAy.614yyWyArpqt^iiltJ^opey
>EfaabkPb`obqpy@yJ^dbyyKyQ^_bqe^%13)24+.&yyNFAy.616yyWyArpqt^iiltJ^opey
OJrapmol`hbqy@yJ^dbyyKyQo^sbiqlJrapmol`hbq%1/+5)4/+1&yyWyArpqt^iiltJ^opey
cJrapmol`hbqy@yJ^dbyyKyAvpifuPfisbodor_%1/+5)4/+1&yyWyArpqt^iiltJ^opey
CQe^i^k^^oy@yJ^dbyyKyAvpifuPfisbodor_%1/+5)4/+1&yyWyArpqt^iiltJ^opey
OQebPefjjbofkdCi^qpy@yJ^dbyyKyQo^sbiqlQebPefjjbofkdCi^qp%4-)25&yyWyQelrp^kaKbbaibpyyNFAy.62-y
QEfaabkPb`obqpy@yJ^dbyyKyJ^drpQfoqe%45+0)42+5&yyNFAy.616yyWyQelrp^kaKbbaibpy
>DbqqebP`llmy@yJ^dbyyKyJ^drpQfoqe%45+0)42+5&yyNFAy.62-yyWyQelrp^kaKbbaibpy
K?b`hlkMir`hvy@yJ^dbyyKyCfkaMir`hv%46+3)42+4&^kaqvmb,_b`hlkqlefj^kaq^ihqlefjtebkebfpfkerj^kclojyyNLyPb`obqmeo^pbclrkayyNFAy.62-yyWyQelrp^kaKbbaibpy
QDbqqebP`llmy@yJ^dbyyKyJ^drpQfoqe%45+0)42+5&yyNFAy.62-yyWyQelrp^kaKbbaibpy
>Ofqr^iplcMltboy@yJ^dbyyKyJ^drpQfoqe%45+0)42+5&yyNFAy.62.yyWyQelrp^kaKbbaibpy

OD^adbqw^ky@yJ^dbyyKyQo^sbiqlD^adbqw^k%2.)/6+0&yyWyQ^k^ofpy
cD^adbqw^ky@yJ^dbyyKy?bo^Pqlkbe^jjbo%2.)/6+0&yyWyQ^k^ofpy

EQebo^jlobFpiby@yJ^dbyyRy3615yyNFAy.62.y

OP`^oibqJlk^pqbovIf_o^ovyKyNrbrbcloP`^oibqJlk^pqbovIf_o^ov)^qib^pqibsbi0.fpob`ljjbkaba)nrbrbcloPJDo^sbv^oafcvlr$obklq`ilpbyyNFAy.62.yyFy

@JvqelildvlcqebQfq^kpyKyQeb_llhfp^qqebibcqpfablc^`loofalotfqeerdbpq^fkba*di^pptfkaltp+Qeb`loofalofpqeblkbqe^q^mmb^opelofwlkq^ifkqebjfkfj^m)^kavlr^``bppfqsf^qebd^iibovlcqob^probpyyNFAy.-2-y
@Ofqr^iplcMltboy@yJ^dbyyKyQeb_llhfpfkqebP`^oibqJlk^pqbovIf_o^ov+Fq$pe^kdfkdlcclc^_llhpebiclk^peloqt^iifkqebi^pqe^iit^v_bclobqebcfk^i_lppyyNFAy.62.y
H>o`^kfpqAl^kyKyHfii>o`^kfpqAl^k^kaillqXQebP`^oibqHbvZyyIy4.13y

OArpqt^iiltJ^opey@yJ^dbyyKyBufq_^`hqlArpqt^iiltJ^ope%13)24+.&yyWyArpqt^iiltJ^opeyyFyyNFAy.62/y

QOfqr^iplcMltboy@yJ^dbyyKyQ^_bqe^%13)24+.&yyNFAy.616yyWyArpqt^iiltJ^opey
>J^db$pT^kay@yJ^dbyyKyQ^_bqe^%13)24+.&yyNFAy.62/yyWyArpqt^iiltJ^opey
QJ^db$pT^kay@yJ^dbyyKyQ^_bqe^%13)24+.&yyNFAy.62/yyWyArpqt^iiltJ^opey

_JbkbqefiE^o_loy@yJ^dbyyKyQ^hbqeb_l^qqlJbkbqefiE^o_lo%4.+2)23+1&yyWyArpqt^iiltJ^opey
C@fqvlcFolkclodby@yJ^dbyyKyPebiibf?olkafo%6+2)26+4&yyWyTbqi^kapy

O@fqvlcFolkclodbyKyQbibmloq_^`hqlFolkclodb%41+4)./+4&yyWyFolkclodbyyFy
QJvqelildvlcqebQfq^kpyKyIf_o^of^kJ^bM^ibarpq%41+4)./+4&yyWyFolkclodbyyNFAy.-2-y

KNrbrbCloArkdblkpRkqfiIbsbi00yKyLk`bvlrefqibsbi00`lkqfkrbtfqeO^wlocbkAltkpdrfaby

]]
end)
