
DugisGuideViewer:RegisterGuide("|cfff0c502Class Quest:|r Shaman / Warlock / Warrior (30+)", nil, "Alliance", "I", function()
return [[
AAA

KIbsbi0-Obnrfobay@yT^oil`hyyKyQefpfp^Ibsbi0-nrbpqclokbtPrjjlkCbierkqbophfiiyyNFAy.465yyMIy0-y
KIbsbi0-Obnrfobay@yPe^j^kyyKyQefpfp^Ibsbi0-nrbpqcloPe^j^kpqld^fkqebfo>foQlqbjpyyNFAy622.yyMIy0-y
KIbsbi0-Obnrfobay@yT^oofloyyKyQefpfp^Ibsbi0-nrbpqcloT^ooflopqld^fk?bopbohboPq^k`b^kaFkqbo`bmqPhfiiyyNFAy.4.5yyMIy0-y
KPe^j^k,T^ooflo,T^oil`hplkivyKyVlrtlk$q_b^_ibqlpbbqebpbdrfabrkibppvlr$ob^Pe^j^k)T^oil`hloT^oofloyy@yOldrb)M^i^afk)Erkqbo)Aorfa)Mofbpq)J^db)Ab^qeHkfdeqy

OQebBula^oy@yPe^j^kyyKyQo^sbiqlQebBula^o%00+/)/0+0&yyWyQebBula^oyyNFAy622.y
>@^iilc>fo%M^oq.&y@yPe^j^kyyKyPri^^%00+/)/0+0&yyNFAy622.yyWyQebBula^oy
Q@^iilc>fo%M^oq.&y@yPe^j^kyyKyC^opbboKl_rkal%0-)0-&yyNFAy622.yyWyQebBula^oy
>@^iilc>fo%M^oq/&y@yPe^j^kyyKyC^opbboKl_rkal%0-)0-&yyNFAy622/yyWyQebBula^oy
Q@^iilc>fo%M^oq/&y@yPe^j^kyyKyBufqkloqeqebefii%/3)/3&^kacfkaSbi^^a^%/1+5)02+6&yyNFAy622/yyWy>wrobjvpqFpiby
>@^iilc>fo%M^oq0&y@yPe^j^kyyKySbi^^a^%/1+5)02+6&yyNFAy6220yyWy>wrobjvpqFpiby
Q@^iilc>fo%M^oq0&y@yPe^j^kyyKyPrproorp%//+05)0/+2&yyNFAy6220yyWy>wrobjvpqFpiby
>@^iilc>fo%M^oq1&y@yPe^j^kyyKyPrproorp%//+05)0/+2&yyNFAy6221yyWy>wrobjvpqFpiby
Q@^iilc>fo%M^oq1&y@yPe^j^kyyKyC^opbboKl_rkal%0-)0-&yyNFAy6221yyWyQebBula^oy

O@fqvlcFolkclodby@yT^oofloyyKyQo^sbiqlFolkclodb%.5+.)2.+2&yyWyFolkclodbyyNFAy.4.5y
eFolkclodby@yT^oofloyyKyFkkhbbmboCfob_obt%.5+.)2.+2&yyWyFolkclodbyyNFAy.4.5y
O@fqvlcFolkclodby@yT^oil`hyyKyQo^sbiqlFolkclodb%.5+.)2.+2&yyWyFolkclodbyyNFAy.465y
eFolkclodby@yT^oil`hyyKyFkkhbbmboCfob_obt%.5+.)2.+2&yyWyFolkclodbyyNFAy.465y
>PbbhfkdPqo^e^ayKyI^dl?i^`htobk`e%14+/).-+6&yy@yT^oil`hyyNFAy.465yyWyFolkclodby
>QebFpi^kaboy@yT^oofloyyKyHbisPqboke^jjbo%4.+2)6.+/&yyNFAy.4.5yyWyFolkclodby

CJbkbqefiE^o_loy@yT^oil`hyyKyArkd^oIlkdaofkh%4-+6)4/+4&yyWyPqlojtfka@fqvyyNFAy.465y
_Qebo^jlobFpiby@yT^oil`hyyKyQ^hbqeb_l^qqlQebo^jlobFpibyyNFAy14/yyWyTbqi^kapyyNFAy.465y
CO^q`ebqy@yT^oil`hyyKy@^pp^@ofjplktfkd%34+0)2.&yyWyArpqt^iiltJ^opeyyNFAy.465y

OJbkbqefiE^o_loy@yT^oofloyyKyArkd^oIlkdaofkh%4-+6)4/+4&yyWyPqlojtfka@fqvyyNFAy.4.5y
_Qebo^jlobFpiby@yT^oofloyyKyQ^hbqeb_l^qqlQebo^jlobFpibyyNFAy14/yyWyTbqi^kapyyNFAy.4.5y
CO^q`ebqy@yT^oofloyyKy@^pp^@ofjplktfkd%34+0)2.&yyWyArpqt^iiltJ^opeyyNFAy.4.5y

QQebFpi^kaboy@yT^oofloyyKyHi^kkl`J^`ibla%35+3)16+.&yyWyQeb?^oobkpyyNFAy.4.5y
>Qeb>cco^vy@yT^oofloyyKyHi^kkl`J^`ibla%35+3)16+.&yyWyQeb?^oobkpyyNFAy.4.6y
@Qeb>cco^vy@yT^oofloyyKyHfiiqebpbofbplcJl_p)_^ka^db^kab^qfk_bqtbbkJl_p)>pclo?fdTfii)vlr$obdfsbkqebmofsfibdbql^qq^`hefjcfopq_b`^rpbeb$pkbrqo^i)plgrpqork_^`h^ka`e^odbqebkrpbvlroObq^if^qflkclo?fdTfii%35+3)15+4&yyWyQeb?^oobkpyyNFAy.4.6y
QQeb>cco^vy@yT^oofloyyKyHi^kkl`J^`ibla%35+3)16+.&yyWyQeb?^oobkpyyNFAy.4.6y

QPbbhfkdPqo^e^ay@yT^oil`hyyKyPqo^e^aC^op^k%3/+3)02+2&yyWyQeb?^oobkpyyNFAy.465y
>Qljblcqeb@^_^i%M^oq.&y@yT^oil`hyyKyPqo^e^aC^op^k%3/+3)02+2&yyWyQeb?^oobkpyyNFAy.425y

EFolkclodbyRy3615yy@yT^oil`hyyNFAy.425y
QQljblcqeb@^_^i%M^oq.&yKyHoljPqlrq^oj%41+0)6+1&yy@yT^oil`hyyNFAy.425yyWyFolkclodby
>Qljblcqeb@^_^i%M^oq/&yKyHoljPqlrq^oj%41+0)6+1&yy@yT^oil`hyyNFAy.5-/yyWyFolkclodby
CQebo^jlobFpiby@yT^oil`hyyKyCivqlJbkbqefiE^o_lo^kaq^hbqeb_l^qlkqebplrqebokmfboyyNFAy.5-1yyWyFolkclodby

OQeb?^oobkpyKyDlqlQeb?^oobkp%/5+1)13+4&yy@yT^oil`hyyWyArpqt^iiltJ^opeyyNFAy.5-1y
OQelrp^kaKbbaibpyKyDlqlQelrp^kaKbbaibp%1/+3)62+.&yy@yT^oil`hyyWyQeb?^oobkpyyNFAy.5-1y
KDbqXQ^qqbobaJ^krp`ofmqZyKyFkpfabqeb`^sbb^pqlcqebDob^qIfcqfkQelrp^kaKbbaibp%10+2)0/+4&yyIy3664yy@yT^oil`hyyWyQelrp^kaKbbaibpyyNFAy.5-/y

OQe^i^k^^oy@yT^oil`hyyKyQo^sbiqlQe^i^k^^o%56+2)12+6&yyWyCbo^i^pyyNFAy.5-1y
CQebo^jlobFpiby@yT^oil`hyyKyQevppf^k^%56+2)12+6&yyWyCbo^i^pyyNFAy.5-1y

_Tbqi^kapy@yT^oil`hyyKyQo^sbiqlJbkbqefiE^o_lo%4.+2)23+1&yyWyArpqt^iiltJ^opeyyNFAy.5-1y
O>o^qefEfdei^kapy@yT^oil`hyyKyQo^sbiql>o^qefEfdei^kap%12+3)55&yyWy>o^qefEfdei^kapyyNFAy.5-1y
OObcrdbMlfkqby@yT^oil`hyyKyQo^sbiqlObcrdbMlfkqb%12+5)13+.&yyWy>o^qefEfdei^kapyyNFAy.5-1y
cObcrdbMlfkqby@yT^oil`hyyKy@baofhMolpb%12+5)13+.&yyWy>o^qefEfdei^kapyyNFAy.5-1y
OEfiip_o^aCllqefiipy@yT^oil`hyyKyQo^sbiqlEfiip_o^aCllqefiip%5.)23&yyWyEfiip_o^aCllqefiipyyNFAy.5-1y
OPlrqepeloby@yT^oil`hyyKyQo^sbiqlPlrqepelob%16+0)2/+0&yyWyEfiip_o^aCllqefiipyyNFAy.5-1y
cPlrqepeloby@yT^oil`hyyKyA^oi^E^oofp%16+0)2/+0&yyWyEfiip_o^aCllqefiipyyNFAy.5-1y

@Qljblcqeb@^_^i%M^oq/&yKyObqofbsbqebXJliavQljbZ%/4+4)4/+5&yyIy360.yy@yT^oil`hyyNFAy.5-/yyWyEfiip_o^aCllqefiipy

EFolkclodbyRy3615yy@yT^oil`hyyNFAy.5-1y
QQljblcqeb@^_^i%M^oq/&yKyHoljPqlrq^oj%41+0)6+5&yy@yT^oil`hyyWyFolkclodbyyNFAy.5-/y
>Qljblcqeb@^_^i%M^oq0&yKyHoljPqlrq^oj%41+0)6+5&yy@yT^oil`hyyWyFolkclodbyyNFAy.5-1y
>FkPb^o`elcJbk^o^SlfaobkaboyKy?of^oqelok%2-+0)3+.&yy@yT^oil`hyyWyFolkclodbyyNFAy1403y

CJbkbqefiE^o_loy@yT^oil`hyyKyDovqeQeroabk%22+2)14+5&yyNFAy.462yyWyFolkclodby

@Qljblcqeb@^_^i%M^oq0&yKy@liib`q0XOlaplc@e^kkbifkdZaolmmba_vAo^dlkj^t?lkbt^oabo%16)13&yy@yT^oil`hyyWyTbqi^kapyyNFAy.5-1y

_Arpqt^iiltJ^opeyKyQ^hbqeb_l^qqlQebo^jlobFpib%2)30+2&yy@yT^oil`hyyNFAy.462yyWyTbqi^kapy
CO^q`ebqyKy?o^dlh%34+2)2.+0&yy@yT^oil`hyyNFAy.462yyWyArpqt^iiltJ^opey
QQljblcqeb@^_^i%M^oq0&yKyPqo^e^aC^op^k%3/+3)02+2&yy@yT^oil`hyyWyQeb?^oobkpyyNFAy.5-1y
>Qeb?fkafkdy@yT^oil`hyyKyPqo^e^aC^op^k%3/+3)02+2&yyWyQeb?^oobkpyyNFAy.462y
@Qeb?fkafkdy@yT^oil`hyyKyRpfkdqebXQljblcqeb@^_^iZ)prjjlk^kapr_arb^cbierkqbo%3/+3)02+0&yyRy3666yyWyQeb?^oobkpyyNFAy.462y
QQeb?fkafkdy@yT^oil`hyyKyPqo^e^aC^op^k%3/+3)02+2&yyWyQeb?^oobkpyyNFAy.462y

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`ljyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)
