DugisGuideViewer:RegisterGuide("Razorfen Downs (33-38)", "Scarlet Monestary Armory / Cathedral (34-39)", "Alliance", "I", function()
return [[
AAA

KIbsbi0/ObnrfobayKyVlrjrpq_b^qib^pqibsbi0/qlmf`hrmqebcliiltfkdnrbpqpyyNFAy0303yyMIy0/y

OPqlojtfka@fqvyKyQo^sbiqlPqlojtfka@fqv%3-+2)42+/&yyNFAy0303yyWyPqlojtfka@fqvy
ePqlojtfka@fqvyWyPqlojtfka@fqvyyKyFkkhbbmbo>iifplk%3-+2)42+/&yyNFAy0303y

>?ofkdqebIfdeqyWyPqlojtfka@fqvyyKy>o`e_fpelm?bkbaf`qrp%2-+2)13+0&yyNFAy0303y

OO^wlocbkAltkpyKyNrbrbcloO^wlocbkAltkptfqevlroArkdblkCfkaboyyNFAy02/0yyFy

KCloqebrm`ljfkdbp`loqnrbpq++yKyJ^hbprobbsbovlkb`ljmibqbpP`lrodblcqebAltkp_bclob^``bmqfkdqebkbuqnrbpqlobipblkivlkblcvlrtfii_b^_ibql`ljmibqbqebnrbpqyyNFAy02/0y
>P`lrodblcqebAltkpyKy?bikfpqo^pw)Qefpfp^kbp`loqnrbpq)^qqebmofplk`biipgrpq_bclobvlrdbqqlqebphbibqlk_lppyyNFAy02/0y
QP`lrodblcqebAltkpyKy?bikfpqo^pwyyNFAy02/0y
>BuqfkdrfpefkdqebFaliyKy?bikfpqo^pwyyNFAy02/2y
@BuqfkdrfpefkdqebFaliyKyMolqb`q?bikfpqo^pwyyNFAy02/2y
QBuqfkdrfpefkdqebFaliyKy?bikfpqo^pwyyNFAy02/2y
@?ofkdqebIfdeqyKyHfii>jkbkk^oqeb@lia_ofkdboqebcfk^i_lpplcO^wlocbkAltkpyyNFAy0303y

OPqlojtfka@fqvyKyQbibmloq_^`hqlPqlojtfka@fqv%2-+2)13+0&yyWyPqlojtfka@fqvyyFy

Q?ofkdqebIfdeqyWyPqlojtfka@fqvyyKy>o`e_fpelm?bkbaf`qrp%2-+2)13+0&yyNFAy0303y

KDrfab@ljmibqb+@lkqfkrbQlP`^oibqJlkbpq^ov%01*06&yKyQf`hql`lkqfkrbqlqebkbuqdrfab*Riqfj^qbTlTDrfab+`ljy

]]
end)
