DugisGuideViewer:RegisterGuide("Scarlet Monestary Armory / Cathedral (34-39)", "Uldaman (39-45)", "Alliance", "I", function()
return [[
AAA

KIbsbi01ObnrfobayKyVlrjrpq_b^qib^pqibsbi01qlmf`hrmqebcliiltfkdnrbpqpyyNFAy3.1.yyMIy01y
OPqlojtfka@fqvyKyQo^sbiqlPqlojtfka@fqv%2/+2)10+2&yyWyPqlojtfka@fqvyyNFAy3.1.y
>?olqebo>kqlkyKy?olqebo@oltibv%2/+2)10+2&yyWyPqlojtfka@fqvyyNFAy3.1.y
_A^ohpelobyKyQo^sbiqlA^ohpelob%//+1)23&yyWyPqlojtfka@fqvyyNFAy/3.y
O>pebks^ibyKyQo^sbiql>pebks^ib%/6).2&Phfmqefppqbmfcvlr^iob^ave^sb>pqo^k^^ocifdeqmlfkqyyWy>pebks^ibyyNFAy/3.y
c>pqo^k^^oyKyA^bivpef^%01+1)15&vlrtfiikbbaqefpi^qboyyWy>pebks^ibyyNFAy/3.y

OPqlkbq^ilkJlrkq^fkpyKyQo^sbiqlPqlkbq^ilkJlrkq^fkp)rpbQ^ilkabbmM^qeqrkkbi^q%1/)4.+0&yyWy>pebks^ibyyNFAy/3.y
OAbpli^`byKyQo^sbiqlqeolrdeTfkapeb^o@o^dqlAbpli^`b%2/)4+2&yyWyAbpli^`byyNFAy/3.y

cKfgbi$pMlfkqyKy?^ofq^k^pPhvofsbo%31+4).-+2&yyWyAbpli^`byyNFAy/3.y
Q?olqebo>kqlkyKy?olqebo>kqlk%33+2)4+5&yyWyAbpli^`byyNFAy3.1.y
>AltkqebP`^oibqM^qe%M^oq.&yKy?olqebo>kqlk%33+2)4+5&yyWyAbpli^`byyNFAy/3.y
@AltkqebP`^oibqM^qe%M^oq.&yKyHfii0-Rkab^aO^s^dbo%3-)6-&yyWyAbpli^`byyNFAy/3.y
QAltkqebP`^oibqM^qe%M^oq.&yKy?olqebo>kqlk%33+2)4+5&yyWyAbpli^`byyNFAy/3.y
>AltkqebP`^oibqM^qe%M^oq/&yKy?olqebo>kqlk%33+2)4+5&yyWyAbpli^`byyNFAy.-2/y
EPqlojtfka@fqvyRy3615yyNFAy.-2/y

CPlrqepeloby@yT^oil`hyyKyArkd^oIlkdaofkh%4.)4/+2&yyWyPqlojtfka@fqvyyNFAy.-2/y
QAltkqebP`^oibqM^qe%M^oq/&y@yT^oil`hyyKyO^ibfdeqebAbslrq%2.+2)25+2&yyWyEfiip_o^aCllqefiipyyNFAy.-2/y

CJbkbqefiE^o_loy@yT^ooflo)Pe^j^k)Oldrb)M^i^afk)Erkqbo)Mofbpq)J^db)Ab^qeHkfdeq)AorfayyKyArkd^oIlkdaofkh%4.)4/+2&yyWyPqlojtfka@fqvyyNFAy.-2/y
O>o^qefEfdei^kapy@yT^ooflo)Pe^j^k)Oldrb)M^i^afk)Erkqbo)Mofbpq)J^db)Ab^qeHkfdeq)AorfayyKyQo^sbiql>o^qefEfdei^kap%12+3)55&yyWy>o^qefEfdei^kapyyNFAy.-2/y
OObcrdbMlfkqby@yT^ooflo)Pe^j^k)Oldrb)M^i^afk)Erkqbo)Mofbpq)J^db)Ab^qeHkfdeq)AorfayyKyQo^sbiqlObcrdbMlfkqb%12+5)13+.&yyWy>o^qefEfdei^kapyyNFAy.-2/y
cObcrdbMlfkqby@yT^ooflo)Pe^j^k)Oldrb)M^i^afk)Erkqbo)Mofbpq)J^db)Ab^qeHkfdeq)AorfayyKy@baofhMolpb%12+5)13+.&yyWy>o^qefEfdei^kapyyNFAy.-2/y
OEfiip_o^aCllqefiipy@yT^ooflo)Pe^j^k)Oldrb)M^i^afk)Erkqbo)Mofbpq)J^db)Ab^qeHkfdeq)AorfayyKyQo^sbiqlEfiip_o^aCllqefiip%5.)23&yyWyEfiip_o^aCllqefiipyyNFAy.-2/y
OPlrqepeloby@yT^ooflo)Pe^j^k)Oldrb)M^i^afk)Erkqbo)Mofbpq)J^db)Ab^qeHkfdeq)AorfayyKyQo^sbiqlPlrqepelob%16+0)2/+0&yyWyEfiip_o^aCllqefiipyyNFAy.-2/y
cPlrqepelobyKyA^oi^E^oofp%16+0)2/+0&yyWyEfiip_o^aCllqefiipyyNFAy.-2/y

QAltkqebP`^oibqM^qe%M^oq/&y@yT^ooflo)Pe^j^k)Oldrb)M^i^afk)Erkqbo)Mofbpq)J^db)Ab^qeHkfdeq)AorfayyKyO^ibfdeqebAbslrq%2.+2)25+2&yyWyEfiip_o^aCllqefiipyyNFAy.-2/y

>FkqebK^jblcqebIfdeqyKyO^ibfdeqebAbslrq%2.+2)25+2&yyWyEfiip_o^aCllqefiipyyNFAy.-20y

KNrbrbcloP`^oibqJlk^pqbovIf_o^ovyKyRpbqebArkdblkcfkaboqlnrbrbcloJlk^pqbovIf_o^ov)vlrtfiilkivkbbaqlhfiiqebcfopq_lppqebkvlr`^kib^sbqebdolrmyyNFAy.-20yyFy
HElrkaj^pqboIlhpbvyKyHfiiElrkaj^pqboIlhpbvfkqebIf_o^ov)ebfkpfabqebpj^ii^ob^_vqeb`lroqv^oayyNLyElrkaj^pqboIlhpbvpi^fk.,.yyNFAy.-20y

KPq^vloib^sb++yKyVlralk$qkbbaql`ljmibqbqebobpqlcqebarkdblkeltbsbovlrtfiiob`bfsb^0-jfkabpboqboab_rccfcvlrib^sb+Vlr`^kpq^v^ka`ljmibqbqebbkqfoborkloq^hb^_ob^hallqebopqrcc7&yyNFAy.-20y

KNrbrbCloP`^oibqJlkbpq^ov>ojlovRkqfiIbsbi04yKyNrbrbcloP`^oibqJlkbpq^ov>ojlov>ojlovRkqfiIbsbi04yyNFAy.-20yyFy

HEbolayKyHfiiEbolaqebcfk^i_lppfkqeb>ojlovyyNLyEbolapi^fk.,.yyNFAy.-20y

KNrbrbCloP`^oibqJlkbpq^ov@^qebao^i>cqboIbsbi04yKyFob`ljjbkavlrt^fqrkqfiibsbi04_bclobbkqbofkdqeb@^qebao^irkibppvlr$obdb^obatfqeEbfoilljpyyNFAy.-20yyFy

@FkqebK^jblcqebIfdeqyKyHfii^iiqeb_lppbpfk@^qebao^iyyNFAy.-20y
OEfiip_o^aCllqefiipyKyQbibmloq_^`hqlEfiip_o^aCllqefiip%2.+2)25+2&yyWyEfiip_o^aCllqefiipyyFy
QFkqebK^jblcqebIfdeqyKyO^ibfdeqebAbslrq%2.+2)25+2&yyWyEfiip_o^aCllqefiipyyNFAy.-20y

KAlP`^oibqJlkbpq^ov@^qebao^iRkqfiIbsbi06

]]
end)
