DugisGuideViewer:RegisterGuide("Uldaman (39-45)", "Zul'Farrak (42-47)", "Alliance", "I", function()
return [[
AAA

KIbsbi05ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi05qlmf`hrmqebcliiltfkdnrbpqpyyNFAy4-4yyMIy05y

O@fqvlcFolkclodbyWyFolkclodbyyKyQo^sbiqlFolkclodb%.5+3)2.+2&yyNFAy4-4y
eFolkclodbyWyFolkclodbyyKyFkkhbbmboCfob_obt%.5+3)2.+2&yyNFAy4-4y
>Folk_^kaT^kqpVlryWyFolkclodbyyKyMolpmb`qloPqlojmfhb%41+3)./+2&yyNFAy4-4y
>Ob`i^fjbaQob^probpyWyFolkclodbyyKyHoljPqlrq^oj%41+3).-+2&yyNFAy.03-y
??rvXColpqLfiZyKyColj>r`qflkElrpb%/1)4-&*Phfmqefpfcklq^s^fi^_ibyyIy05/6yyWyFolkclodbyyNFAy4.0y
??rvXDvol`eolk^qljZyKyColj>r`qflkElrpb%/1)4-&*Alk$q_rvfcvlrafak$qcfka^ColpqLfiyyIy1056yyNFAy4.1yyWyFolkclodby
??rvXEb^ifkdMlqflkZyKyColj>r`qflkElrpb%/1)4-&*Alk$q_rvfcvlrafak$qcfka^ColpqLfi^kaDvol`eolk^qljyyIy6/6yyNFAy4.2yyWyFolkclodby
??rvXIbppboFksfpf_fifqvMlqflkZyKyColj>r`qflkElrpb%/1)4-&*Alk$q_rvfcvlrafak$qcfka^ColpqLfi^kaDvol`eolk^qljyyIy05/0yyNFAy4.2yyWyFolkclodby
??rv1uX?rww^oaTfkdZyKyColj>r`qflkElrpb%/1)4-&*Phfmqefpfcklq^s^fi^_ibyyIy01-11yyWyFolkclodbyyNFAy4-0y

CQebip^j^oyWyFolkclodbyyKyDovqeQeroabk%23+-)16+-&yyNFAy4-4y

QFolk_^kaT^kqpVlryWyIl`eJla^kyyKyMolpmb`qloFolk_^ka%32+5)32+3&yyNFAy4-4y
>Cfka>djlkayWyIl`eJla^kyyKyMolpmb`qloFolk_^ka%32+5)32+3&yyNFAy405y
>?^ai^kapOb^dbkqOrkyWyIl`eJla^kyyKyDe^hEb^iqlr`e%04+-)16+0&yyNFAy/2--y

O?^ai^kapyKyQo^sbiql?^ai^kap%16+/)5+1&yyWy?^ai^kapyyNFAy4/-y
>>PfdklcElmb%M^oq.&yWy?^ai^kapyyKy@orjmibaJ^m%20+-)01+.&yyNFAy4/-y
Q>PfdklcElmb%M^oq.&yWy?^ai^kapyyKyMolpmb`qloOvbali%20+3)10+6&yyNFAy4/-y

>>PfdklcElmb%M^oq/&yWy?^ai^kapyyKyMolpmb`qloOvbali%20+3)10+6&yyNFAy4/.y

>MltboPqlkbpyWy?^ai^kapyyKyOfddibcrww%1/+2)2/+4&yyNFAy/1.5y
>?^o_b`rba?rww^oaTfkdpyKyOfddibcrww%1/+1)2/+5&yyNFAy4-0y

QCfka>djlkayWy?^ai^kapyyKy?^qqbobaAt^osbkPhbibqlk%2.+-)3/+2&yyNFAy405y
>Jroa^il`yWy?^ai^kapyyKy?^qqbobaAt^osbkPhbibqlk%2.+-)3/+2&yyNFAy406y
@Jroa^il`yWy?^ai^kapyyKyJroa^il`t^kabopqeb^ob^^olrka%2.+0)36+3&)hfiiefj^ka./Pqlkbs^riq?lkbpk^mmbopyyNFAy406y
@?^o_b`rba?rww^oaTfkdpyKyX?rww^oaTfkdpZ^obrpr^iivifpqbalkqeb>r`qflkelrpb^qiltmof`btef`etlriaj^hbqefpnrbpq^kb^pv`ljmibqflkfcklqhfiiDf^kq?rww^oap^olrka%.3+2)3-&tele^sb^ab`bkqaolmo^qbyyNFAy4-0y

>PlirqflkqlAlljyWy?^ai^kapyyKyQebiarofkqebIlpq%2.+2)43+5&yyNFAy4-6y

>PqravlcqebBibjbkqp7Ol`h%M^oq.&yKyIlqtfiSbof^qrp%/2+6)12+-&yyNFAy4.-yyWy?^ai^kapy
>@lli^kqEb^apMobs^fiyKyIlqtfiSbof^qrp%/2+6)12+-&yyIy05/6yyLyyNFAy4.0yyWy?^ai^kapy
Q@lli^kqEb^apMobs^fiyKyIlqtfiSbof^qrp%/2+6)12+-&yyLyyNFAy4.0yyWy?^ai^kapy
>Dvol+++Te^q<yKyIlqtfiSbof^qrp%/2+6)12+-&yyIy1056yyLyyNFAy4.1yyWy?^ai^kapy
QDvol+++Te^q<yKyIlqtfiSbof^qrp%/2+6)12+-&yyLyyNFAy4.1yyWy?^ai^kapy
>IfnrfaPqlkbyKyIr`fbkQlppbitobk`e%/2+5)11+1&yyIy05/0yyLyyNFAy4.2yyWy?^ai^kapy
QIfnrfaPqlkbyKyIr`fbkQlppbitobk`e%/2+5)11+1&yyLyyNFAy4.2yyWy?^ai^kapy

@PqravlcqebBibjbkqp7Ol`h%M^oq.&yKyHfiiqebIbppboOl`hBibjbkq^ip^olrka%/0)2.&rkqfivlr$sb`liib`qba.-XPj^iiPqlkbPe^oapZyyNFAy4.-yyWy?^ai^kapy
QPqravlcqebBibjbkqp7Ol`h%M^oq.&yKyIlqtfiSbof^qrp%/2+6)12+-&yyNFAy4.-yyWy?^ai^kapy

@?^ai^kapOb^dbkqOrkyKyQebjl_p^obpmob^aqeolrdelrq_^ai^kap_rq^dlla^ob^qlalqefpnrbpqtlria_b^olrka%/0)2.&tebob^iiqeobbkbbaba?rww^oap)@lvlqbp^kaOl`hBibjbkq^ip`^k_bclrka+Hfiibklrdeqfiivlrd^fkqebobnrfoba^jlrkqlcb^`eob^dbkqyyNFAy/2--yyWy?^ai^kapy

Q>PfdklcElmb%M^oq/&yWy?^ai^kapyyKyE^jjboqlbDobw%04+6.).-+25&yyNFAy4/.y

>>jribqlcPb`obqpyWy?^ai^kapyyKyE^jjboqlbDobw%04+6.).-+25&yyNFAy4//y
@>jribqlcPb`obqpyWy?^ai^kapyyKyHfiiJ^dobd^kAbbmpe^alt%06+04).3+/5&telm^qolikb^oAfdLkblcRia^j^k$pColkqBkqo^k`byyNFAy4//y
@PlirqflkqlAlljyKyCfkaqeb`ebpqfkRia^j^kmob*fkpq^k`b^ob^%06+0/).5+5.&yyNFAy4-6yyWy?^ai^kapy
@Ob`i^fjbaQob^probpyKyCfkaqeb`ebpqfkRia^j^kmob*fkpq^k`b^ob^%02+23)/0+2.&eb^afkqlqeb^ob^tfqeqebqoldp)bkqo^k`b^q%04+51).3+43&yyNFAy.03-yyWy?^ai^kapy
Q>jribqlcPb`obqpyWy?^ai^kapyyKyE^jjboqlbDobw%04+6.).-+25&yyNFAy4//y

>Molpmb`qlcC^fqe%M^oq.&yWy?^ai^kapyyKyE^jjboqlbDobw%04+6.).-+25&yyNFAy4/0y
@MltboPqlkbpyKyVlr`^k`ljmibqbqefp_vhfiifkdqebAt^osbplrqpfabRia^j^kFkpq^k`b%11+2)./+.3&yyNFAy/1.5yyWy?^ai^kapy

>QebPe^qqbobaKb`hi^`byWy?^ai^kapyyKyHfiiqebKM@lrqpfabqebfkpq^k`brkqfivlrcfkaqebXPe^qqbobaKb`hi^`bZ%11+2)./+.3&yyRy4333yyNFAy/.65y
QMolpmb`qlcC^fqe%M^oq.&yWy?^ai^kapyyKyMolpmb`qloOvbali%20+3)10+6&yyNFAy4/0y
>Molpmb`qlcC^fqe%M^oq/&yWy?^ai^kapyyKyMolpmb`qloOvbali%20+3)10+6&yyNFAy4/1y
Q?^o_b`rba?rww^oaTfkdpyKyOfddibcrww%1/+1)2/+5&yyNFAy4-0yyWy?^ai^kapy
QMltboPqlkbpyKyOfddibcrww%1/+2)20+.&yyNFAy/1.5yyWy?^ai^kapy

EFolkclodbyRy3615yyNFAy/.66y

QQebPe^qqbobaKb`hi^`byWyFolkclodbyyKyQ^is^peabiHfppbi%03+-)1+/&yyNFAy/.65y
>Ilobclo^Mof`byWyFolkclodbyyKyQ^is^peabiHfppbi%03+-)1+/&yyNFAy/.66y
@Ilobclo^Mof`byWyFolkclodbyyKy@liib`q,?rv2Pfisbo?^op^qqeb>r`qflkElrpbyyNFAy/.66y
QIlobclo^Mof`byWyFolkclodbyyKyQ^is^peabiHfppbi%03+-)1+/&yyNFAy/.66y
>?^`hqlRia^j^kyWyFolkclodbyyKyQ^is^peabiHfppbi%03+-)1+/&yyNFAy//--y

QOb`i^fjbaQob^probpyWyFolkclodbyyKyHoljPqlrq^oj%41+3).-+2&yyNFAy.03-y
QMolpmb`qlcC^fqe%M^oq/&yWyFolkclodbyyKyEfpqlof^kH^okfh%44+0).-+.&yyNFAy4/1y
>M^ppfkdTloalc^Qeob^q%M^oq.&yWyFolkclodbyyKyEfpqlof^kH^okfh%44+0).-+.&yyNFAy4/2y
QM^ppfkdTloalc^Qeob^q%M^oq.&yWyFolkclodbyyKy>asfplo?bidorj%44+3)6+6&yyNFAy4/2y
>M^ppfkdTloalc^Qeob^q%M^oq/&yWyFolkclodbyyKy>asfplo?bidorj%44+3)6+6&yyNFAy4/3y
QM^ppfkdTloalc^Qeob^q%M^oq/&yWyFolkclodbyyKyEfpqlof^kH^okfh%44+0).-+.&yyNFAy4/3y
>>k>j_^pp^alolcBsfiyWyFolkclodbyyKyEfpqlof^kH^okfh%44+0).-+.&yyNFAy43/y

CIl`eJla^kyWyFolkclodbyyKyDovqeQeroabk%23+-)16+-&yyNFAy43/y

QJroa^il`yWyIl`eJla^kyyKyMolpmb`qloFolk_^ka%32+5)32+3&yyNFAy406y
>>djlka$pC^qbyWyIl`eJla^kyyKyMolpmb`qloFolk_^ka%32+5)32+3&yyNFAy4-1y
Q?^ai^kapOb^dbkqOrkyKyDe^hEb^iqlr`e%04)16+/&yyWyIl`eJla^kyyNFAy/2--y
>Ria^j^kOb^dbkqOrkyWyIl`eJla^kyyKyDe^hEb^iqlr`e%04+-)16+0&yyNFAy.4y

@>k>j_^pp^alolcBsfiyWy?^ai^kapyyKyHfii>j_^pp^aloFkcbokrp%1.+6)/5+1&fk>kdloCloqobppyyNFAy43/y
QPlirqflkqlAlljyWy?^ai^kapyyKyQebiarofkqebIlpq%2.+2)43+5&yyNFAy4-6y

EFolkclodbyRy3615yyNFAy..06y

Q>k>j_^pp^alolcBsfiyWyFolkclodbyyKy>asfplo?bidorj%44+3)6+6&yyNFAy43/y
>QebIlpqQ^_ibqplcTfiiyWyFolkclodbyyKy>asfplo?bidorj%44+3)6+6&yyNFAy..06y
>QebIlpqAt^osbpyWyFolkclodbyyKyMolpmb`qloPqlojmfhb%41+2)./+/&yyNFAy/065y

ORia^j^kyKyRpbqebarkdblkcfkaboqlnrbrbcloRia^j^kyyFyyNFAy//-.y

Q?^`hqlRia^j^kyKyCfkaObj^fkplc^M^i^afk)tebkvlrbkqboqebfkpq^k`b)pqf`hqlqebofdeqpfablcqebe^iip^kavlrtfiicfkaefjlkqeb/kae^iit^vyyNFAy//--y

>CfkaqebDbjpyKyObj^fkplc^M^i^afkyyNFAy//-.y
QQebIlpqAt^osbpyKyCfka?^bildfkqeb^ob^qlqebplrqelcqebbkqo^k`b^ob^yyNFAy/065y
>QebEfaabk@e^j_boyKy?^bild)fkpfabRia^j^kyyNFAy//1-y
KDbqXDkf$HfsJba^iiflkZyKyIllqqefpcolj?^bild$p@ebpqyyIy441-yyNFAy//1-y
KDbqXPe^qqbobaKb`hi^`bQlm^wZyKyDbqXPe^qqbobaKb`hi^`bQlm^wZfpfk^@lkpmf`rlrpRokfkqebolljtfqeqebqeobbilpqsfhfkd)%tebobvlrdbqqebDkf$hfsJba^iiflk&yyNFAy//-.yyIy434.y

KDbqXPe^qqbobaKb`hi^`bP^mmefobZyKyDbqXPe^qqbobaKb`hi^`bP^mmefobZaolmmbacoljDofj$ilhyyNFAy/006yyIy434-y

@>djlka$pC^qbyKy@liib`q1@^osbaPqlkbRokptef`e`^k_bclrka^olrkaRia^j^kyyNFAy4-1y
@Ria^j^kOb^dbkqOrkyKy@liib`q./J^dbkq^Crkdrp@^mpclrka^olrkaRia^j^kyyNFAy.4y

HObsbilpeyKyHfiiObsbilpe^kaillqqebXPe^cqlcQpliZql`lj_fkbtfqeqebXDkf$HfsJba^iiflkZ)`ib^okbuqolljqebkrpbqebpq^cclkqebmbabpq^iqlprjjlkFolk^v^yyIy441.yyNFAy//1-y
R@ob^qbXPq^cclcMobefpqlof^ZyKy@lj_fkbXPe^cqlcQpliZtfqeqebXDkf$HfsJba^iiflkZqebkrpbqebpq^cclkqebmbabpq^i%fkqebjfaaiblcqeb@fqvJlabi&yyRy441-yyNFAy//1-y

@QebEfaabk@e^j_boyKyBumilobqebolljFolk^v^`^jbcoljyyNFAy//1-y
@QebIlpqQ^_ibqplcTfiiyKyQebQ^_ibqlcTfii`^k_bclrkafkpfabqebRia^j^kfkpq^k`bkbuqqlD^id^kkCfobe^jjboyyNFAy..06y
KDbqXPe^qqbobaKb`hi^`bOr_vZyKyDbqXPe^qqbobaKb`hi^`bOr_vZfkqebPe^altclodb`^`ebfpfkqebolljtfqeD^id^kkCfobe^jjboyyNFAy//-.yyIy4336y
@CfkaqebDbjpyKyDbqXPe^qqbobaKb`hi^`bP^mmefobZaolmmbacoljDofj$ilhyyIy434-yyNFAy//-.y
QCfkaqebDbjpyKyRpbqebfqbjXQ^is^pe$pP`ovfkd?ltiZ)coljQ^is^pe$pMef^ilcP`ovfkdyyRy4334yyNFAy//-.y
>ObpqlofkdqebKb`hi^`b%M^oq.&yKyQ^is^pe$pP`ovfkd?lti)coljQ^is^pe$pMef^ilcP`ovfkdyyNFAy//-1y
@ObpqlofkdqebKb`hi^`b%M^oq.&yKyIllqqebPe^qqbobaKb`hi^`bMltboPlro`bcolj>o`e^ba^pyyNFAy//-1y
>QebMi^qfkrjAfp`p%M^oq.&yKyColjQebMi^qfkrjAfp`pfkqebolljtfqe>o`e^ba^pyyNFAy//45y
KQ^ihqlPqlkbT^q`eboyKyQ^ihqlPqlkbT^q`ebokbuqqlqebafph^kaphfmqeolrde^iiefppqlovyyNFAy//45yyNLyIb^okte^qilobqe^qqebpqlkbt^q`eboe^pqllccboy
QQebMi^qfkrjAfp`p%M^oq.&yKyColjQebMi^qfkrjAfp`pfkqebolljtfqe>o`e^ba^pyyNFAy//45y
>QebMi^qfkrjAfp`p%M^oq/&yKyColjQebMi^qfkrjAfp`pfkqebolljtfqe>o`e^ba^pyyNFAy//46y

O@fqvlcFolkclodbyKyQbibmloq_^`hlrqqlFolkclodb%03+-)1+/&yyWyFolkclodbyyNFAy/03.yyFy

QObpqlofkdqebKb`hi^`b%M^oq.&yWyFolkclodbyyKyQ^is^peabiHfppbi%03+-)1+/&yyNFAy//-1y
>ObpqlofkdqebKb`hi^`b%M^oq/&yWyFolkclodbyyKyQ^is^peabiHfppbi%03+-)1+/&yyNFAy/03.y
QObpqlofkdqebKb`hi^`b%M^oq/&yWyFolkclodbyyKyQ^is^peabiHfppbi%03+-)1+/&yyNFAy/03.y

QQebMi^qfkrjAfp`p%M^oq/&yWyFolkclodbyyKyEfdeBumiloboJ^dbii^p%36+5).5+1&yyNFAy//46y
>QebMi^qfkrjAfp`p%M^oq0&yWyFolkclodbyyKyEfdeBumiloboJ^dbii^p%36+5).5+1&yyNFAy/106y

QQebIlpqQ^_ibqplcTfiiyWyFolkclodbyyKy>asfplo?bidorj%44+3)6+6&yyNFAy..06y
QQebEfaabk@e^j_boyWyFolkclodbyyKyMolpmb`qloPqlojmfhb%41+2)./+/&yyNFAy//1-y
QQebMi^qfkrjAfp`p%M^oq0&yWyFolkclodbyyKyAfkfq^Pqlkbj^kqib%01+3)3-+-&yyNFAy/106y

CIl`eJla^kyWyFolkclodbyyKyDovqeQeroabk%23+-)16+-&y

QRia^j^kOb^dbkqOrkyWyIl`eJla^kyyKyDe^hEb^iqlr`e%04+-)16+0&yyNFAy.4y
Q>djlka$pC^qbyWyIl`eJla^kyyKyMolpmb`qloFolk_^ka%32+5)32+3&yyNFAy4-1y

KDrfab@ljmibqb+@lkqfkrbQlWri$C^oo^h%1/*14&yKyQf`hql`lkqfkrbqlqebkbuqdrfab*Riqfj^qbTlTDrfab+`ljy

]]
end)
