DugisGuideViewer:RegisterGuide("Zul'Farrak (42-47)", "Maraudon (45-49)", "Alliance", "I", function()
return [[
AAA

KIbsbi1-ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi1-qlmf`hrmqebcliiltfkdnrbpqpyyNFAy/53.yyMIy1-y

O@fqvlcFolkclodbyKyQo^sbiqlFolkclodb%4/+3)60+1&yyWyFolkclodbyyNFAy/53.y
>Q^_bqe^$pQ^phyWyFolkclodbyyKy?fkh%/4+-)5+0&yyNFAy/53.y
>Qeb?o^pp_liqp?olqebopyWyFolkclodbyyKyMfilqIlkd_b^oa%4/+3)60+1&yyNFAy/436y
CPqlojtfka@fqvyWyFolkclodbyyKyDovqeQeroabk%23+-)16+-&yyNFAy.115y

ePqlojtfka@fqvyKyFkkhbbmbo>iifplk%3-+1)42+0&yyWyPqlojtfka@fqvyyNFAy.115y
>FkPb^o`elcQebQbjmibyKy?ole^kk@^ph_biiv%36+2)13+-&yyNFAy.115yyWyPqlojtfka@fqvy
CArphtllayKyArkd^oIlkdaofkd%4.)4/+2&yyWyPqlojtfka@fqvyyNFAy.116y
OAb^atfkaM^ppyKyQo^sbiqlAb^atfkaM^pp%01)03&yyWyAb^atfkaM^ppyyNFAy.116y
OPt^jmlcPlooltpyKyQo^sbiqlPt^jmlcPlooltp%3+2)3-&yyWyPt^jmlcPlooltpyyNFAy.116y
@FkPb^o`elcQebQbjmibyKyBumilobqeb^ob^_vqebQbjmib%35+3)16+2&yyNFAy.115yyWyPt^jmlcPlooltpy

O?i^pqbaI^kapyKyQo^sbiql?i^pqbaI^kap%2/)54&yyWy?i^pqbaI^kapyyNFAy.116y
OKbqebod^oabHbbmyKyQo^sbiqlKbqebod^oab%31+.).6+/&yyWy?i^pqbaI^kapyyNFAy.116y
cKbqebod^oabHbbmyKy>ibu^ka^o@lkpq^kqfkb%32+2)/1+0&yyWy?i^pqbaI^kapyyNFAy.116y

EPqlojtfka@fqvyRy3615yyNFAy.116y
QFkPb^o`elcQebQbjmibyKy?ole^kk@^ph_biiv%36+2)13+-&yyNFAy.115yyWyPqlojtfka@fqvy
>QlQebEfkqboi^kapyKy?ole^kk@^ph_biiv%36+2)13+-&yyNFAy.116yyWyPqlojtfka@fqvy

OQebEfkqboi^kapyWyQebEfkqboi^kapyyKyEb^aqlQebEfkqboi^kap%.-)21&yyNFAy.12-y
QQlQebEfkqboi^kapyKyC^ipq^aTfiae^jjbo%..+5)13+5&yyNFAy.116yyWyQebEfkqboi^kapy
>DovmelkJ^pqboQ^ilk^ubyKyC^ipq^aTfiae^jjbo%..+5)13+5&yyNFAy.12-yyWyQebEfkqboi^kapy
c>bofbMb^hyKyDrqeorjQerkabocfqp%..+.)13+.&yyWyQebEfkqboi^kapyyNFAy.12-y
QDovmelkJ^pqboQ^ilk^ubyKyDovmelkJ^pqboQ^ilk^ub%6+5)11+2&yyNFAy.12-yyWyQebEfkqboi^kapy
>Oe^mplavPefkafddboyKyDovmelkJ^pqboQ^ilk^ub%6+5)11+2&yyNFAy.12.yyWyQebEfkqboi^kapy
>Tfqebo_^oh@^dbpyKyDovmelkJ^pqboQ^ilk^ub%6+5)11+2&yyNFAy/655yyWyQebEfkqboi^kapy
>Cb^qebo_b^oa$pBkalopbjbkqyKy>j_^pp^aloOr^ibqe%.2+.)14+0&yyNFAy6136yyWyQebEfkqboi^kapy
>>DbpqroblcDllatfiiyKy>j_^pp^aloOr^ibqe%.2+.)14+0&yyNFAy614-yyWyQebEfkqboi^kapy
>MobvfkdlkqebMoba^qlopyKy>j_^pp^aloOr^ibqe%.2+.)14+0&yyNFAy614.yyWyQebEfkqboi^kapy
>QoliiKb`hi^`b?lrkqvyKyCo^dd^oQerkaboj^kqib%.1+5)11+2&yyNFAy/55-yyWyQebEfkqboi^kapy
eTfiae^jjboHbbmyKyFkkhbbmboQerico^j%.0+/)1.+6&yyNFAy6143yyWyQebEfkqboi^kapy

QCb^qebo_b^oa$pBkalopbjbkqyKyCb^qebo_b^oa$pGlrok^i%.0+1)22+/&yyNFAy6136yyWyQebEfkqboi^kapy
>FkMroprfqlcCb^qebo_b^oayKyCb^qebo_b^oa$pGlrok^i%.0+1)22+/&yyNFAy6143yyWyQebEfkqboi^kapy
QOe^mplavPefkafddboyKyOe^mplavPefkafddbo%/3+6)15+2&rpbqebm^qe^q%/-)14&yyNFAy.12.yyWyQebEfkqboi^kapy
>Oe^mplav$pH^ifjaloHl`hq^fiyKyOe^mplavPefkafddbo%/3+6)15+2&rpbqebm^qe^q%/-)14&yyNFAy.12/yyWyQebEfkqboi^kapy

HJ^kdvPfisboj^kTlisbpyKy^olrka%.6)2/&yyNFAy614.yyNLyJ^kdvPfisboj^kbpi^fk7.-,.-yyWyQebEfkqboi^kapy
K@eb`hCfopq@^dbyNFAy/655yyNLy@eb`hCfopq@^db7.,.yyKy>qqebqolii`^jm%/0)25&yyWyQebEfkqboi^kapy
K@eb`hPb`lka@^dbyNFAy/655yyNLy@eb`hPb`lka@^db7.,.yyKy>qqebqolii`^jm%/0)25&yyWyQebEfkqboi^kapy
@>DbpqroblcDllatfiiyKyHfiiTfq`eAl`qloJ^f$gfk^kaefpmbqpmfaboQ`e^$h^w^q%/2)33&yyNFAy614-yyWyQebEfkqboi^kapy
@Tfqebo_^oh@^dbpyKyDbqqebQefoaTfqebo_^oh@^dbfkqebEfof$T^qe^orfkp^olrka%0.)24&yyNFAy/655yyWyQebEfkqboi^kapy
@MobvfkdlkqebMoba^qlopyKyHfii2Pfisboj^kbTlisbp^olrka%/4)3/&yyNFAy614.yyWyQebEfkqboi^kapy
@QoliiKb`hi^`b?lrkqvyKyQebXQoliiKb`hi^`bpZ`^k_billqbacoljqebTfqebo_^ohjl_p^olrkaqebefiipfablcqebEfkqboi^kap^olrka%/1)24&yyNFAy/55-yyWyQebEfkqboi^kapy

>G^jj^i$^kqebMolmebqyWyQebEfkqboi^kapyyKy>q^i$^fBufib%00+4)42+/&yyNFAy.113y

ETfiae^jjboHbbmyRy3615yyNFAy/656y
QQoliiKb`hi^`b?lrkqvyKyCo^dd^oQerkaboj^kqib%.1+5)11+2&yyNFAy/55-yyWyQebEfkqboi^kapy
Q>DbpqroblcDllatfiiyKy>j_^pp^aloOr^ibqe%.2+.)14+0&yyNFAy614-yyWyQebEfkqboi^kapy
QMobvfkdlkqebMoba^qlopyKy>j_^pp^aloOr^ibqe%.2+.)14+0&yyNFAy614.yyWyQebEfkqboi^kapy
QTfqebo_^oh@^dbpyKyDovmelkJ^pqboQ^ilk^ub%6+5)11+2&yyNFAy/655yyWyQebEfkqboi^kapy
>Qeb>iq^olcWriyKyDovmelkJ^pqboQ^ilk^ub%6+5)11+2&yyNFAy/656yyWyQebEfkqboi^kapy
QFkMroprfqlcCb^qebo_b^oayKyCb^qebo_b^oa$pObj^fkp%04+.)4.+2&yyNFAy6143yyWyQebEfkqboi^kapy
>Ob`i^fjfkdqebBddpyKyCb^qebo_b^oa$pObj^fkp%04+.)4.+2&yyNFAy6142yyWyQebEfkqboi^kapy

@Ob`i^fjfkdqebBddpyKyD^qebo2XDovmelkBddpZ^olrka%01)4/&yyNFAy6142yyWyQebEfkqboi^kapy
@Qeb>iq^olcWriyKyOrkqlqebqlmlcqeb>iq^olcWri^q%16)35&yyNFAy/656yyWyQebEfkqboi^kapy

QOb`i^fjfkdqebBddpyKy>j_^pp^aloOr^ibqe%.2+.)14+0&yyNFAy6142yyWyQebEfkqboi^kapy
QQeb>iq^olcWriyKyDovmelkJ^pqboQ^ilk^ub%6+5)11+2&yyNFAy/656yyWyQebEfkqboi^kapy
>Qe^afrpDofjpe^abyKyDovmelkJ^pqboQ^ilk^ub%6+5)11+2&yyNFAy/66-yyWyQebEfkqboi^kapy

CKbqebod^oabHbbmyWyQebEfkqboi^kapyyKyDrqeorjQerkabocfpq%..+.)13+.&yyNFAy/66.y

QQe^afrpDofjpe^abyWy?i^pqbaI^kapyyKyQe^afrpDofjpe^ab%34+-).6+2&yyNFAy/66-y
>Kbhorj$pJba^iiflkyWy?i^pqbaI^kapyyKyQe^afrpDofjpe^ab%34+-).6+2&yyNFAy/66.y

CA^ohpefobyWy?i^pqbaI^kapyyKy>ibu^kao^@lkpq^kqfkb%32+2)/1+2&yyNFAy/531y
OPqo^kdibqelokS^ibyKyQo^sbiqlPqo^kdibqelokS^ib%1-+2)1+.&yyWyPqo^kdibqelokS^ibyyNFAy/531y
cOb_bi@^jmyKyKfwwib%05+/)1+-&yyWyPqo^kdibqelokS^ibyyNFAy/531y
O?llqv?^vyKyQo^sbiql?llqv?^v%/5+/)41+2&yyWyPqo^kdibqelokS^iby
>Qo^k$obhyWyPqo^kdibqelokS^ibyyKyHo^wbh%/4+-)44+/&yyNFAy/531y
_O^q`ebqyWyPq^kdibqelokS^ibyyKyQ^hbqeb?l^qqlO^q`ebq%/3)40+/&y
CJrapmol`hbqyKy?o^dlh%30+.)04+.&yyWyQeb?^oobkpyyNFAy/513y

Q>Q^_bqe^$pQ^phyWyArpqt^iiltJ^opeyyKyQ^_bqe^%13+-)24+.&yyNFAy/53.y
>Qf^o^lcqebAbbmyWyArpqt^iiltJ^opeyyKyQ^_bqe^%13+-)24+.&yyNFAy/513y
OQeb?^oobkpyKyQo^sbiqlQeb?^oobkp%16+/)45+/&yyWyQeb?^oobkpy

OQelrp^kaKbbaibpyKyQo^sbiqlQelrp^kaKbbaibp%0.+5)/1+3&yyWyQelrp^kaKbbaibpyyNFAy02/-y
OQ^k^ofpyKyQo^sbiqlQ^k^ofp%2-+4)/1+0&yyWyQ^k^ofpyyNFAy02/-y

>P`obb`eboPmfofqpyWyQ^k^ofpyyKyVbe$hfkv^%33+6)//+1&yyNFAy02/-y
eD^adbqw^kyWyQ^k^ofpyyKyFkkhbbmboCfwwdofj_ib%2/+2)/4+6&yyNFAy/532y

QQo^k$obhyWyQ^k^ofpyyKyQo^k$obh%2.+3)/3+5&yyNFAy/531y
>P`^o^_PebiipyWyQ^k^ofpyyKyQo^k$obh%2.+3)/3+5&yyNFAy/532y
>Afsfkl*j^qf`OlayWyQ^k^ofpyyKy@efbcBkdfkbbo?fidbtefwwib%2/+2)/5+2&yyNFAy/435y
>QoliiQbjmboyWyQ^k^ofpyyKyQobkqlkIfdeqe^jjbo%2.+2)/5+4&yyNFAy0-1/y
cD^adbqw^kyKy?bo^Pqlkbe^jjbo%2.)/6+0&yyWyQ^k^ofpy

HOl`pyKyHfiiOl`p%15+3)/5+3&%16)0.+6&qldbq0uXOl`Dfww^oaZcloqebnrbpqOe^mplav$pH^ifjaloHl`hq^fiyyIy3/240yyNFAy.12/yyWyQ^k^ofpy

OQelrp^kaKbbaibpyWyQelrp^kaKbbaibpyyKyEb^aKloqeqlQelrp^kaKbbaibp%42)63&yyNFAy/44-y

QQeb?o^pp_liqp?olqebopyWyQelrp^kaKbbaibpyyKyTfwwib?o^pp_liqp%45+.)44+.&yyNFAy/436y
>D^ew$ofii^yWyQelrp^kaKbbaibpyyKyTfwwib?o^pp_liqp%45+.)44+.&yyNFAy/44-y

OD^adbqw^kyKyQo^sbiqlD^adbqw^k2.)/6+0&yyWyQ^k^ofpyyNFAy02/4y
CQe^i^k^^oyKy?bo^Pqlkbe^jjbo%2.)/6+0&yyWyQ^k^ofpyyNFAy02/4y
@P`obb`eboPmfofqpyWyCbo^i^pyyKyHfiiP`obb`ebop%24+2)20+6&^karpbXVbe$hfkv^$p?o^j_ibZlkqebab^aP`obb`ebopyyRy.-366yyNFAy02/-y
@Oe^mplav$pH^ifjaloHl`hq^fiyKyHfiiDolaal`>mb^kaFolkcro?b^op^olrka%25+2)22&clo0uXDolaal`IfsboZ^ka0uXFolkcroIfsboZyyNFAy.12/yyWyCbo^i^py

ED^adbqw^kyRy3615yyNFAy02/4y

QP`obb`eboPmfofqpyWyQ^k^ofpyyKyVbe$hfkv^%33+6)//+1&yyNFAy02/-y
>QebMolmeb`vlcJlpe$^oryWyQ^k^ofpyyKyVbe$hfkv^%33+6)//+1&yyNFAy02/4y

OWri$C^oo^hyKyNrbrbcloWri$C^oo^hrpfkdvlroArkdblkCfkaboyyNFAy02/4yyFy

KDbqXCfopqJlpe$^orQ^_ibqZyKyQefpfpaolmmbacoljqebcfopq_lppQebh^qebJ^oqvoyyIy.-33-yyNFAy02/4y
@Afsfkl*j^qf`OlayKyQlpq^oqqebnrbpqbsbkqvlre^sbqlhfiiqebP^kacrovBub`rqflkbo^qqebqlmlcqebQbjmib^karpbqebhbvebaolmpqlcobbPbodb^kq?ivcoljefp`^db)lk`bqebbsbkqfplsbovlr`^kq^ihql?ivqlmf`h^cfdeq+Alklqq^ihql?ivrkqfibsbov_lavfpob^av)Hfiilccqebmofbpq^kail`hcfopq)qebkqeboldrb^kacfk^iiv?ivefjpbic+Illqefp_lavcloqebafsfkl*j^qf`ola^kaqebnrbpqfp`ljmibqbyyNFAy/435y
@Kbhorj$pJba^iiflkyKyHfiiKbhorjDrq`ebtbo)ebfpqebcfk^i_lppqe^qpm^tkpcloqebAfsfkl*j^qf`OlayyNFAy/66.y
@D^ew$ofii^yKyOfkdqebdlkdqlprjjlk^kahfiiD^ew$ofii^^kaillqXD^ew$ofii^$pBib`qofcfbaP`^ibZyyNFAy/44-y
@P`^o^_PebiipyKy@liib`q2uXP`^o^_PebiiZaolmmba_vqebp`^o^_pfkqebrkab^a^ob^yyNFAy/532y
@Qf^o^lcqebAbbmyKyHfiiEvaolj^k`boSbio^qe^telfpfkqebp^jbollj^pD^ew$ofii^^kaillqXQf^o^lcqebAbbmZyyNFAy/513y
@QebMolmeb`vlcJlpe$^oryKyQeb/kaq^_ibqfpaolmmba_vEvaolj^k`boSbio^qe^telfpfkqebp^jbollj^pD^ew$ofii^yyNFAy02/4y
@QoliiQbjmboyKyAolmmba_v^kvqoliicoljWri$C^oo^hvlrpelriadbq/-^cqbo.orkyyNFAy0-1/y

OD^adbqw^kyKyBufqqebarkdblk_^`hqlD^adbqw^k%2.+3)/3+5&yyWyQ^k^ofpyyNFAy1454yyFy

QP`^o^_PebiipyWyQ^k^ofpyyKyQo^k$obh%2.+3)/3+5&yyNFAy/532y
QQoliiQbjmboyWyQ^k^ofpyyKyQobkqlkIfdeqe^jjbo%2.+2)/5+4&yyNFAy0-1/y
QAfsfkl*j^qf`OlayWyQ^k^ofpyyKy@efbcBkdfkbbo?fidbtefwwib%2/+2)/5+2&yyNFAy/435y

QQebMolmeb`vlcJlpe$^oryWyQ^k^ofpyyKyVbe$hfkv^%33+6)//+1&yyNFAy02/4y
>Qeb>k`fbkqBddyWyQ^k^ofpyyKyVbe$hfkv^%33+6)//+1&yyNFAy1454y

OQelrp^kaKbbaibpyWyQelrp^kaKbbaibpyyKyQo^sbiqlQelrp^kaKbbaibp%42)63&y
QD^ew$ofii^yKyTfwwib?o^pp_liqp%45+.)44+.&yyWyQelrp^kaKbbaibpyyNFAy/44-y

CJrapmol`hbqyWyQ^k^ofpyyKy?bo^Pqlkbe^jjbo%2.+-)/6+0&y
QQf^o^lcqebAbbmyWyArpqt^iiltJ^opeyyKyQ^_bqe^%13+-)24+.&yyNFAy/513y
CO^q`ebqyWyArpqt^iiltJ^opeyyKyAvpifuPfisbodor_%1/+5)4/+1&y

_?llqv?^vyWyQeb?^oobkpyyKyQ^hbqeb?l^qql?llqv?^v%4.+2)23+1&yyNFAy/66/y
C?i^pqbaI^kapyWyPqo^kdibqelokS^ibyyKyDvii%/4+2)44+4&yyNFAy/66/y

QKbhorj$pJba^iiflkyWy?i^pqbaI^kapyyKyQe^afrpDofjpe^ab%34+-).6+2&yyNFAy/66.y
>QebAfsfk^qflkyWy?i^pqbaI^kapyyKyQe^afrpDofjpe^ab%34+-).6+2&yyNFAy/66/y
QQebAfsfk^qflkyWy?i^pqbaI^kapyyKyQe^afrpDofjpe^ab%34+-).6+2&yyNFAy/66/y
>ObqrokqlqebEfkqboi^kapyWy?i^pqbaI^kapyyKyQe^afrpDofjpe^ab%34+-).6+2&yyNFAy/660y

CQebEfkqboi^kapyWy?i^pqbaI^kapyyKy>ibu^kao^@lkpq^kqfkb%32+2)/1+2&yyNFAy/661y

QObqrokqlqebEfkqboi^kapyWyQebEfkqboi^kapyyKyDovmelkJ^pqboQ^ilk^ub%6+5)11+2&yyNFAy/660y
>P^sfkdPe^om_b^hyWyQebEfkqboi^kapyyKyDovmelkJ^pqboQ^ilk^ub%6+5)11+2&yyNFAy/661y
eTfiae^jjboHbbmyKyFkkhbbmboQerico^j%.0+2)1.+5&yyWyQebEfkqboi^kapyyNFAy/661y
QOe^mplav$pH^ifjaloHl`hq^fiyKyOe^mplavPefkafddbo%/3+6)15+2&rpbqebm^qe^q%/-)14&yyNFAy.12/yyWyQebEfkqboi^kapy
>Oe^mplav$pQ^ibyKyOe^mplavPefkafddbo%/3+6)15+2&yyNFAy.136yyWyQebEfkqboi^kapy

@P^sfkdPe^om_b^hyWyQebEfkqboi^kapyyKyEb^aqlGfkqe^$>iloorfkp%33+-)3/+-&^pvlrdbqqlqebi^pqmi^qb^rqrokibcqqldlqlt^oapqeb^iq^oqlcfkaSfibMofbpqbppEbuu%25+4)45+5&qebkeb^aaltkqebqrkkbi%24+-)35+-&^kacfkaPe^om_b^h%20+2)34+-&yyNFAy/661y
@Qeb>k`fbkqBddyWyQebEfkqboi^kapyyKy>qGfkqe^$>ilo^kaj^hbvlrot^vqlqebbdd^q%25+3)46+.&yyNFAy1454y

ETfiae^jjboHbbmyRy3615y

QP^sfkdPe^om_b^hyWyQebEfkqboi^kapyyKyDovmelkJ^pqboQ^ilk^ub%6+5)11+2&yyNFAy/661y

KDrfab@ljmibqb+@lkqfkrbQlJ^o^ralk%12*16&yKyQf`hql`lkqfkrbqlqebkbuqdrfab*Riqfj^qbTlTDrfab+`ljy

]]
end)
