DugisGuideViewer:RegisterGuide("Maraudon (45-49)", "Sunken Temple (48-52)", "Alliance", "I", function()
return [[
AAA

KIbsbi12ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi12qlmf`hrmqebcliiltfkdnrbpqpyyNFAy4-4-yyMIy12y

OQebo^jlobFpibyKyQo^sbiqlJbkbqefiE^o_lo%33+1)16+0&yyWyArpqt^iiltJ^opeyyNFAy4-4-y

>Pe^altpe^oaCo^djbkqpyWyArpqt^iiltJ^opeyyKy>o`ej^dbQboslpe%33+1)16+0&yyNFAy4-4-y

CKfgbi$pMlfkqyWyArpqt^iiltJ^opeyyKy?^iaor`%34+2)2.+0&yyNFAy4-32y

eKfgbi$pMlfkqyWyAbpli^`byyKyFkkhbbmboIvpe^bov^%33+0)3+4&yyNFAy4-32y

>@loormqflklcB^oqe^kaPbbayWyAbpli^`byyKyHbbmboJ^o^kafp%31+-).-+1&yyNFAy4-32y
>Svibqlkdrb@loormqflkyWyAbpli^`byyKyQ^ibkaof^%35+2)5+6&yyNFAy4-1.y
>QtfpqbaBsfipyWyAbpli^`byyKyTfiilt%3/+/)06+3&yyNFAy4-/5y
>QebM^of^e$pFkpqor`qflkpyWyAbpli^`byyKy@bkq^roM^of^e)ebqo^sbip_bqtbbk%10+1)51+5&)%2-+2)53+3&yyNFAy4-34y

OJ^ro^alkyWyAbpli^`byyKyQo^sbiqlJ^ro^alk`^sb^ob^)%/6+4)3/+2&yyNFAy4-34y

HQebK^jbibppMolmebqyWyAbpli^`byyKyHfiiQebK^jbibppMolmebq%/5+.2)31+/-&)%/5+2)30&eb$p^ibsbi1.*10bifqb)vlrpelria_b^_ibqlplilefj^qibsbi12^kadbqX>jribqlcPmfofqpZyyWyAbpli^`byyIy.4424yyNFAy4-34y
HQebCfopqH^ekyWyAbpli^`byyKyRpbX>jribqlcPmfofqpZlkqebH^ek%/6+34)3-+16&qebkhfiiqebCfopqH^ek^kadbqXDbjlcQebCfopqH^ekZyyRy.4424yyIy.443.yyNFAy4-34y
HQebPb`lkaH^ekyWyAbpli^`byyKyRpbX>jribqlcPmfofqpZlkqebH^ek%/5+4)24+34&qebkhfiiqebPb`lkaH^ek^kadbqXDbjlcQebPb`lkaH^ekZyyRy.4424yyIy.443/yyNFAy4-34y
@Pe^altpe^oaCo^djbkqpyWyAbpli^`byyKyHfiiPe^altpe^oaPj^oebop%/3+40)24+0&^ka`liib`q.-uXPe^altpe^oaCo^djbkqZyyNFAy4-4-y
>IbdbkaplcJ^o^ralkyWyAbpli^`byyKyEb^a_^`hlrqqlt^oapqebbkqo^k`b^kapqf`hqlqebofdeqpfab^kacliiltqeblo^kdbpqlkb^ob^qlcfka@^sfkao^%0/)30+5&yyNFAy4-11y
R@l^qba@borib^kSf^iyWyAbpli^`byyKyRpbqebX@l^qba@borib^kSf^iZfkqeblo^kdbmlli%00+.)32+4&yyRy.4360yyNFAy4-1.y
HQebQefoaH^ekyWyAbpli^`byyKyRpbX>jribqlcPmfofqpZlkqebH^ek%02+.1)3-+.0&qebkhfiiqebQefoaH^ek^kadbqXDbjlcQebQefoaH^ekZyyRy.4424yyIy.4430yyNFAy4-34y

KNrbrbcloJ^o^ralk*Mromib@ovpq^ipyKyRpbqebArkdblkcfkaboqlnrbrbcloJ^o^ralk*Mromib@ovpq^ipyyNFAy4-11yyFy
HQebClroqeH^ekyKyRpbX>jribqlcPmfofqpZlkqebH^ekfkqebMromib@ovpq^i^ob^qebkhfiiqebClroqeH^ek^kadbqXDbjlcQebClroqeH^ekZyyRy.4424yyIy.4431yyNFAy4-34y
HIloaSvibqlkdrbyKyHfiiIloaSvibqlkdrb^kadbqX@bib_of^kAf^jlkaZyyIy.44-0yyNFAy4-11y

KIb^sb^kanrbrbcloJ^o^ralk*Lo^kdb@ovpq^ipyKyRpbqebArkdblkcfkaboqlnrbrbcloJ^o^ralk*Lo^kdb@ovpq^ipyyNFAy4-13yyFy

HQebCfcqeH^ekyKyRpbX>jribqlcPmfofqpZlkqebH^ekfkqebLo^kdb@ovpq^i^ob^qebkhfiiqebCfcqeH^ek^kadbqXDbjlcQebCfcqeH^ekZyyRy.4424yyIy.4432yyNFAy4-34y
@QebM^of^e$pFkpqor`qflkpyKy@lj_fkb^iiqebdbjpql`ob^qbX>jribqlcRkflkZyyRy.4432yyNFAy4-34y
@Svibqlkdrb@loormqflkyKyQebsfkbp^obil`^qbafkpfabqebfkpq^k`bfkqeblo^kdbm^oq+Rpbqebsf^ilkqebtfkbp%fqe^p^_lrq.-v^oao^kdb&+QtlloqeobbKluuflrpP`flkpm^tkp^kavlrkbbaqlhfii5lcqebpbfkqlq^iql`ljmibqbqebnrbpqyyRy.4363yyNFAy4-1.y
HKluuflkyKyHfiiKluuflk^kadbqX@bib_of^kOlaZyyIy.44-/yyNFAy4-13y
H@bib_o^pqeb@ropbayKyHfii@bib_o^pqeb@ropba^qqebmlfplkc^iip)hbbmdlfkd^cqbovlrhfiiqebi^pq_lpp)fkqeblo^kdbfkpq^k`b)_bdvlrodolrmqlpq^vcloqebnrbpqy
QIbdbkaplcJ^o^ralkyKy>cqbovlrhfii@bib_o^pqeb@ropba)@bib_o^pqebObabbjbatfii^mmb^oclovlrqlqrokfkqebnrbpqyyNFAy4-11y
>QebP`bmqbolc@bib_o^pyKy@bib_o^pqebObabbjbayyNFAy4-13y
@QebP`bmqbolc@bib_o^pyKyAbcbka@bib_o^pqebObabbjba^kaq^ihqlefjlk`bqebofqr^ifplsboyyNFAy4-13y
QQebP`bmqbolc@bib_o^pyKy@bib_o^pqebObabbjbayyNFAy4-13y

EKfgbi$pMlfkqyRy3615yyNFAy4-32y
QSvibqlkdrb@loormqflkyWyAbpli^`byyKyQ^ibkaof^%35+2)5+6&yyNFAy4-1.y
QQtfpqbaBsfipyWyAbpli^`byyKyTfiilt%3/+/)06+3&yyNFAy4-/5y
QQebM^of^e$pFkpqor`qflkpyWyAbpli^`byyKy@bkq^roM^of^e)ebqo^sbip_bqtbbk%10+1)51+5&)%2-+2)53+3&yyNFAy4-34y

KNrbrbcloJ^o^ralk*MofpqfkbT^qbopyKyNrbrbcloJ^o^ralk*MofpqfkbT^qbopyyNFAy4-32yyFy
@@loormqflklcB^oqe^kaPbbayKyPi^vMofk`bppQebo^ao^pfkJ^o^ralk*MofpqfkbT^qbopyyWyAbpli^`byyNFAy4-32y
>PbbalcIfcbyKyW^bq^o$pPmfofq)eb^mmb^op^cqbovlrhfiiqebMofk`bppyyNFAy4-33y

OAbpli^`byKyQbibmloq_^`hqlAbpli^`b%31+-).-+1&yyWyAbpli^`byyFy
Q@loormqflklcB^oqe^kaPbbayWyAbpli^`byyKyHbbmboJ^o^kafp%31+-).-+1&yyNFAy4-32y
CArpqt^iiltJ^opeyWyAbpli^`byyKy?^ofq^k^pPhvofsbo%31+4).-+2&yyNFAy4-33y
QPe^altpe^oaCo^djbkqpyWyArpqt^iiltJ^opeyyKy>o`ej^dbQboslpe%33+1)16+0&yyNFAy4-4-y

OJllkdi^aby@yAorfayyKyRpbvlrojllkdi^abqbibmloqpmbiiy
QPbbalcIfcby@yAorfayyKyHbbmboObjrilp%03+2)1/+.&yyNFAy4-33yyWyJllkdi^aby

C>r_boafkby@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKy?^iaor`%34+2)2.+0&yyWyArpqt^iiltJ^opey
OJfpq$pBadby@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKyQo^sbiqlJfpq$pBadb%23+2).6&yyWyA^ohpeloby
OJllkdi^aby@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKyPtfj^ilkdqebbadblcqeb`ifccrkqfivlroj^m`e^kdbqlJllkdi^ab)pq^vlrqlcqebc^qfdrbwlkb%/1+3)-+/&yyWyJllkdi^aby
KAoltkvlropbic+++y@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKyQe^qpofdeqhfiivlropbicebob_vaoltkfkd^kaobprob`q^qJllkdi^abdo^sbv^oay
cJllkdi^aby@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKyPfkao^vi%15)34+/&yyWyJllkdi^aby
QPbbalcIfcby@yErkqbo)T^oil`h)J^db)M^i^afk)T^ooflo)Oldrb)Mofbpq)Pe^j^kyyKyHbbmboObjrilp%03+2)1/+.&yyNFAy4-33yyWyJllkdi^aby

KDrfab@ljmibqb+@lkqfkrbQlPrkhbkQbjmib%15*2/&yKyQf`hql`lkqfkrbqlqebkbuqdrfab*Riqfj^qbTlTDrfab+`ljy

]]
end)
