DugisGuideViewer:RegisterGuide("Sunken Temple (48-52)", "Blackrock Depths: Prison (52-55)", "Alliance", "I", function()
return [[
AAA

KIbsbi13ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi13qlmf`hrmqebcliiltfkdnrbpqpyyNFAy.115yyMIy13y

OPqlojtfka@fqvyKyQo^sbiqlPqlojtfka@fqv%3-+2)42+/&yyNFAy.115yyWyPqlojtfka@fqvyyNFAy.115y
ePqlojtfka@fqvyWyPqlojtfka@fqvyyKyFkkhbbmbo>iifplk%3-+2)42+/&yyNFAy.115y
>FkPb^o`elcQebQbjmibyWyPqlojtfka@fqvyyKy?ole^kk@^ph_biiv%36+2)1-+3&yyNFAy.115y

C?i^pqbaI^kapyWyPqlojtfka@fqvyyKyArkd^oIlkdaofkh%4-+6)4/+4&yyNFAy.115y
OPt^jmlcPlooltpyWy?i^pqbaI^kapyyKyEb^afkqlqebPt^jmlcPlooltp%2.+5)6+2&yyNFAy.115y

@FkPb^o`elcQebQbjmibyWyPqlojtfka@fqvyyKy?ole^kk@^ph_biiv%36+2)1-+3&yyNFAy.115y
EPqlojtfka@fqvyRy3615yyNFAy.116y

QFkPb^o`elcQebQbjmibyWyPqlojtfka@fqvyyKy?ole^kk@^ph_biiv%36+2)1-+3&yyNFAy.115y
>QlQebEfkqboi^kapyWyPqlojtfka@fqvyyKy?ole^kk@^ph_biiv%36+2)1-+3&yyNFAy.116y

CQebEfkqboi^kapyWyPqlojtfka@fqvyyKyArkd^oIlkdaofkh%4-+6)4/+4&yyNFAy.12-y
e>bofbMb^hyWyQebEfkqboi^kapyKyFkkhbbmboQerico^j%.0+2)1.+5&yyNFAy.12-y

QQlQebEfkqboi^kapyWyQebEfkqboi^kapyyKyC^ipq^aTfiae^jjbo%..+5)13+5&yyNFAy.116y
>DovmelkJ^pqboQ^ilk^ubyWyQebEfkqboi^kapyyKyC^ipq^aTfiae^jjbo%..+5)13+5&yyNFAy.12-y
QDovmelkJ^pqboQ^ilk^ubyWyQebEfkqboi^kapyyKyDovmelkJ^pqboQ^ilk^ub%6+5)11+2&yyNFAy.12-y
>Oe^mplavPefkafddboyWyQebEfkqboi^kapyyKyDovmelkJ^pqboQ^ilk^ub%6+5)11+2&yyNFAy.12.y
QOe^mplavPefkafddboyWyQebEfkqboi^kapyyKyOe^mplavPefkafddbo%/3+6)15+2&yyNFAy.12.y
>Oe^mplav$pH^ifjaloHl`hq^fiyWyQebEfkqboi^kapyyKyOe^mplavPefkafddbo%/3+6)15+2&yyNFAy.12/y

CJbkbqefiE^o_loyWyQebEfkqboi^kapyyKyDrqeorjQerkabocfpq%..+.)13+.&yyNFAy.12/y
_Arpqt^iiltJ^opeyWyTbqi^kapyyKyQ^hbqeb?l^qqlQebo^jlobFpib%2)30+2&yyNFAy.12/y
CQe^i^k^^oyWyArpqt^iiltJ^opeyyKy?^iaor`%34+1)2.+/&yyNFAy.12/y

OCbo^i^pyKyQo^sbiqlQe^i^k^^ofkCbo^i^p%56)12&yyWyCbo^i^pyyNFAy0112y
OCb^qebojllkPqolkdeliayKyQo^sbiqlCb^qebojllkPqolkdelia%0.)13&)rpbqeb_l^q^q%10+0)10&yyWyCbo^i^pyyNFAy0112y
cCb^qebojllkPqolkdeliayKyCivkaobkJllkcb^qebo%0-+/)10+0&yyWyCbo^i^pyyNFAy0112y
>QebPrkhbkQbjmibyWyCbo^i^pyyKy>kdbi^pJllk_obbwb%0.+6)12+3&yyNFAy0112y

CD^adbqw^kyWyCbo^i^pyyKyCviaobkJllkcb^qebo%0-+0)10+0&yyNFAy0112y

HOl`pyKyHfiiOl`p%15+3)/5+3&%16)0.+6&qldbq0uXOl`Dfww^oaZcloqebnrbpqOe^mplav$pH^ifjaloHl`hq^fiyyIy3/240yyNFAy.12/yyWyQ^k^ofpy

QQeb>k`fbkqBddyWyQ^k^ofpyyKyVbe$hfkv^%33+6)//+1&yyNFAy1454yyLy
>QebDlaE^hh^oyWyQ^k^ofpyyKyVbe$hfkv^%33+6)//+1&yyNFAy02/5yyLy

QQebPrkhbkQbjmibyWyQ^k^ofpyyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyNFAy0112y
>QebPqlkb@fo`ibyWyQ^k^ofpyyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyNFAy0111y

ORk$Dlol@o^qboyWyQ^k^ofpyyKyQo^sbiqlRk$Dlol@o^qbo%/3+5)24+/&yyNFAy1.1.y
OJ^ope^i$pObcrdbyKyQo^sbiqlJ^ope^i$pObcrdb%2-)5+3&yyWyRk$Dlol@o^qboyyNFAy1.1.y
cJ^ope^i$pObcrdbyKyDovcb%12+/)2+5&yyWyRk$Dlol@o^qboyyNFAy1.1.y
>Jrfdfk^kaI^oflkyWyRk$Dlol@o^qboyyKyJrfdfk%10+-)6+2&yyNFAy1.1.y
@Jrfdfk^kaI^oflkyWyRk$Dlol@o^qboyyKyHfii?illambq^ijl_p^olrka%33+1)00+2&^ka`liib`q.2uX?illambq^iZyyNFAy1.1.y
QJrfdfk^kaI^oflkyWyRk$Dlol@o^qboyyKyJrfdfk%10+-)6+2&yyNFAy1.1.y
>>SfpfqqlDobd^kyKyJrfdfk%10+-)6+2&yyNFAy1.1/y

CCb^qebojllkPqolkdeliayWyRk$Dlol@o^qboyyKyDovcb%12+/)2+6&y
Q>SfpfqqlDobd^kyWyCbo^i^pyyKyDobd^k?obtpmbtbo%12+.)/2+2&yyNFAy1.1/y
>E^wblcBsfiyWyCbo^i^pyyKyDobd^k?obtpmbtbo%12+.)/2+2&yyNFAy1.10y
@Oe^mplav$pH^ifjaloHl`hq^fiyWyCbo^i^pyyKyHfiiqebFolkcro?b^op^kaDolaal`>mbp^olrka%1/+0)/0+4&^ka`liib`q0uXFolkcroIfsbopZ^ka0uXDolaal`IfsbopZyyNFAy.12/y

EQebEfkqboi^kapyRy3615yyNFAy.136y

QOe^mplav$pH^ifjaloHl`hq^fiyWyQebEfkqboi^kapyyKyOe^mplavPefkafddbo%/3+6)15+2&yyNFAy.12/y
>Oe^mplav$pQ^ibyWyQebEfkqboi^kapyyKyOe^mplavPefkafddbo%/3+6)15+2&yyNFAy.136y
>G^jj^i$^kqebMolmebqyWyQebEfkqboi^kapyyKy>q^i$^fBufib%00+4)42+/&yyNFAy.113y

CPqlojtfka@fqvyWyQebEfkqboi^kapyyKyDrqeorjQerkabocfpq%..+.)13+.&yyNFAy.136y
_Pqlojtfka@fqvyKyQ^hbqeb_l^qqlPqlojtfka@fqv%0/+1)10+5&yyWyA^ohpelobyyNFAy.136y

QOe^mplav$pQ^ibyWyPqlojtfka@fqvyyKy?ole^kk@^ph_biiv%36+2)1-+3&yyNFAy.136y
>FkqlQebQbjmiblc>q^i$E^hh^oyWyPqlojtfka@fqvyyKy?ole^kk@^ph_biiv%36+2)1-+3&yyNFAy.142y

OO^q`ebqyKyQo^sbiqlO^q`ebq%3/+2)05+2&yyWyQeb?^oobkpyyNFAy0111y

@QebPqlkb@fo`ibyWyQeb?^oobkpyyKyDo^_qebPqlkb@fo`ibcoljJ^oslk$p@ebpq^q%3/+2)05+2&yyNFAy0111y

CD^adbqw^kyWyQeb?^oobkpyyKy?o^dlh%30+.)04+.&yyNFAy0113y

QQebPqlkb@fo`ibyWyQ^k^ofpyyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyNFAy0111y
>FkqlqebAbmqepyWyQ^k^ofpyyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyNFAy0113y
>Pb`obqlcqeb@fo`ibyWyQ^k^ofpyyKyJ^oslkOfsbqpbbhbo%2/+4)12+6&yyNFAy0114y

OPrkhbkQbjmibyKyNrbrbcloPrkhbkQbjmibrpfkdvlroarkdblkcfkaboyyNFAy.142yyFy

@E^wblcBsfiyKy>cqbobkqbofkdqebfkpq^k`bqrokofdeq)cliiltqebm^qe^kahfiiIrohbop^kaTlojpql`liib`q2p^jmibplc>q^i$^fE^wbyyNFAy1.10y
QFkqlqebAbmqepyKy>iq^olcE^hh^o)fkpfabqebPrkhbkQbjmibyyNFAy0113y
@FkqlQebQbjmiblc>q^i$E^hh^oyKy@liib`q.-q^_ibqp)tef`e^obp`^qqboba^olrkaQebPrkhbkQbjmibyyNFAy.142y
@Pb`obqlcqeb@fo`ibyKy>`qfs^qbqebpq^qrbplkqeb/kacillofkqefploaboP)K)PT)PB)KT)KB)qebkvlre^sbqldl_^`haltkqlqeb_lqqljcillo)^dllafab^fpqle^sbbsbov_lavgrjmaltklkqeb_lqqljcillobu`bmqclo.mboplktel`^k^`qfs^qbqebi^pqpq^qrb)^kahfiiqeb_lppyyNFAy0114y
QPb`obqlcqeb@fo`ibyKyFalilcE^hh^o)fkpfabqebPrkhbkQbjmibyyNFAy0114y
@G^jj^i$^kqebMolmebqyKyQo^sbiqlqebkloqebokm^oqlcqebPrkhbkQbjmib^kahfii3>q^i^fAbcbkaboptef`ejrpq_babcb^qbaqlobjlsbqebclo`bcfbiaqebkhfiiG^jj^i$^kqebMolmebq^kaillqefpeb^ayyNFAy.113y
@QebDlaE^hh^oyKyHfiiqeb>s^q^olcE^hh^o%qlprjjlkefjrpbqebXBddlcE^hh^oZlkqebqbjmibclroqecillolkqebIbcqPfablcqebj^mtfqefkqeb`fo`ib)Vlrjrpq^asfpbqebm^oqvqlillqbsbovKM@cloqeb_illa#`if`hlkqebci^jbp+EbaolmpXBppbk`blcE^hh^oZ+Ofdeq`if`hfqfkvlrofksbkqlovqlcfiiqebbddtfqeqebBppbk`blcE^hh^o+yyRy.-132yyNFAy02/5y
HPe^ablcBo^kfhrpyKyVlrjrpqabcb^qG^jj^i$^kqebMolmebq^kaqebqtlao^hbpqe^qpm^tk^cqbot^oapfkloaboqlcfdeqBo^kfhrp)j^hbprobvlr`ib^o^iiqebao^dlkpfkqebi^odbolljcfopq^pqebvtfii^ii^dolfcvlr^qq^`hBo^kfhrp+IllqXBppbk`blcBo^kfhrpZyyIy.-121yyNFAy0040y
>QebBppbk`blcBo^kfhrpyKyRpbqebQebBppbk`blcBo^kfhrplkqebBppbk`bClkqfkqebibcq`lokboqlqeb_^`hlcqebolljyyRy.-121yyNFAy0040y
QQebBppbk`blcBo^kfhrpyKyBppbk`bClkq)FkpfabqebPrkhbkQbjmibyyNFAy0040y

OD^adbqw^kyKyBufq_^`hqlD^adbqw^k%33+6)//1&yyWyQ^k^ofpyyFy

QQebDlaE^hh^oyWyQ^k^ofpyyKyVbe$hfkv^%33+6)//1&yyNFAy02/5y

CRk$dlol@o^qboyWyQ^k^ofpyyKy?bo^Pqlkbe^jjbo%2.+-)/6+0&y
QE^wblcBsfiyWyRk$dlol@o^qboyyKyJrfdfk%10+-)6+2&yyNFAy1.10y

EQebEfkqboi^kapyRy3615y

QG^jj^i$^kqebMolmebqyWyQebEfkqboi^kapyyKy>q^i$^fBufib%00+4)42+/&yyNFAy.113y

CPqlojtfka@fqvyWyQebEfkqboi^kapyyKyDrqeorjQerkabocfpq%..+.)13+.&y

QFkqlQebQbjmiblc>q^i$E^hh^oyWyPqlojtfka@fqvyyKy?ole^kk@^ph_biiv%36+2)1-+3&yyNFAy.142y

KDrfab@ljmibqb+@lkqfkrbQl?i^`hol`hAbmqep%2/*22&yKyQf`hql`lkqfkrbqlqebkbuqdrfab*Riqfj^qbTlTDrfab+`ljy

]]
end)
