DugisGuideViewer:RegisterGuide("Blackrock Depths: Prison (52-55)", "Scholomance / Stratholme (55-58)", "Alliance", "I", function()
return [[
AAA

KIbsbi2/ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi2/qlmf`hrmqebcliiltfkdnrbpqpyyNFAy101.yyMIy2/y

O@fqvlcFolkclodbyKyQo^sbiqlFolkclodb%1-)22+.&yyWyFolkclodbyyNFAy101.y
eFolkclodbyKyFkkhbbmboCfob_obt%.5+.)2.+2&yyWyFolkclodbyyNFAy101.y

>He^o^kJfdeqe^jjboyKyHfkdJ^dkf?olkwb_b^oa%1-)22+.&yyWyFolkclodbyyNFAy101.y

CI^hbpefobyKyDovqeQeroabk%22+2)14+5&yyWyFolkclodbyyNFAy1/53y
O?rokfkdPqbmmbpyKyQo^sbiql?rokfkdPqbmmbp%45+1)46+/&yyWy?rokfkdPqbmmbpyyNFAy1/53y
cJlod^k$pSfdfiyKy?lodrpPqlrq^oj%51+0)35+0&yyWy?rokfkdPqbmmbpyyNFAy1/53y
>QebDllaPqrccyKyLo^ifrp%51+3)35+1&yyWy?rokfkdPqbmmbpyyNFAy1/53y
>Lsboj^pqboMvolkyKyG^ifka^Pmofd%52+2)4-&yyNFAy1/3/yyWy?rokfkdPqbmmbpy

>>Q^pqblcCi^jb%M^oq.&yKy@vorpQebobmbkqlrp%62+-)0.+3&yyNFAy1-/0yyWy?rokfkdPqbmmbpy
@>Q^pqblcCi^jb%M^oq.&yKyPmb^hql@vorpQebobmbkqlrp%62+-)0.+3&^kaebtfiiprjjlk^ao^dlkclovlrqlabcb^q^kaillqqebX?i^`hAo^dlkcifdeqJliqZclomollcyyNFAy1-/0yyWy?rokfkdPqbmmbpy
Q>Q^pqblcCi^jb%M^oq.&yKy@vorpQebobmbkqlrp%62+-)0.+3&yyNFAy1-/0yyWy?rokfkdPqbmmbpy
>>Q^pqblcCi^jb%M^oq/&yKy@vorpQebobmbkqlrp%62+-)0.+3&yyNFAy1-/1yyWy?rokfkdPqbmmbpy

O?i^`hol`hJlrkq^fkyKyQo^sbiql?i^`hol`hJlrkq^fk%01+55)51+5&yyWyPb^ofkdDlodbyyNFAy1-/0y
@Lsboj^pqboMvolkyKyHfiiLsboj^pqboMvolk%/3+11)46+1&)vlr`^kbfqebogrjmaltkqlqebi^s^locliiltqeb@e^fkqlqebjfaaibpqor`qrob^kaaltkqlqebjfkbpyyNFAy1/3/yyWyPb^ofkdDlodby

OPb^ofkdDlodbyKyQo^sbiqlPb^ofkdDlodb%01+5)50+4&yyWyPb^ofkdDlodbyyNFAy1-/0y

OQelofrjMlfkqyKyOrkqlQelofrjMlfkq%01+6)0-+5&yyWyPb^ofkdDlodbyyNFAy1-/0y
cQelofrjMlfkqyKyDofpeh^%04+6)0-+6&yyWyPb^ofkdDlodbyyNFAy1-/0y
CJlod^k$pSfdfiyKyI^kfbObba%04+6)0-+6&yyWyPb^ofkdDlodbyyNFAy1-/0y

QLsboj^pqboMvolkyKyG^ifka^Pmofd%52+2)4-&yyNFAy1/3/yyWy?rokfkdPqbmmbpy

>Fk`bkafrpyKyG^ifka^Pmofd%52+2)4-&yyNFAy1/30yyWy?rokfkdPqbmmbpy

KNrbrbclo?i^`hol`hAbmqep7MofplkyKyRpbqebarkdblkcfkaboqlNrbrbclo?i^`hol`hAbmqep)t^fqfkH^od^qerkqfivlrdbqqebnrbrbyyNFAy101/yyFy

HEfdeFkqboold^qloDbopq^ekyKyHfiiEfdeFkqboold^qloDbopq^ek)coljqebbkqo^k`bpebfplkqebofdeqpfabKloqeB^pq^kadbqqebhbvcoljeboyyIy...1-yyNFAy101/y

QHe^o^kJfdeqe^jjboyKyCobbHe^o^kJfdeqe^jjbo)>cqbovlrbkqbo?OA)t^ihclot^oafkqlqebj^fkollj)qebkillhqlvlroofdeq+Vlr$iipbbqeobbm^qet^vp+Qeblrqboqtlillm^olrkaqlb^`elqebofk^_fdofkd+Dlo$Pe^hfpfk^`biilkqebibcqpfab+ii)vlr$iikbbaqebhbvcoljEfdeFkqboold^qloDbopq^ek+yyNFAy101.y
>He^o^k$pQ^ib%M^oq.&yKyHe^o^kJfdeqe^jjboyyNFAy101/y
@He^o^k$pQ^ib%M^oq.&yKyBp`loq^kaabcbkaHe^o^kJfdeqe^jjboyyNFAy101/y
QHe^o^k$pQ^ib%M^oq.&yKyHe^o^kJfdeqe^jjboyyNFAy101/y
>Qeb?b^obolc?^aKbtpyKyHe^o^kJfdeqe^jjboyyNFAy103.y
@QebDllaPqrccyKyHfiiAt^osbpKM@rkqfivlr`liib`q/-uXA^ohFolkC^kkvM^`hZvlr`^k^iplc^ojqebpbcoljqebklk*bifqbat^osbplrqpfabqebfkpq^k`byyNFAy1/53y

KIl`hmf`hfkdloPe^altclodbHbv<yKy@^k^kvlkbfkvlrodolrmlmbkqebil`hbaalloptfqeil`hmf`hfkdlope^altclodbhbv<Fckllkb`^k)ib^sbqebm^oqv^kaglfk^kbtdolrmqe^qe^sbqebhbvloil`hmf`hfkd+Vlrtlk$qdbqabpboqboab_rcc^pilkd^pEfdeFkqboold^qloDbopq^ekfpab^ayyNFAy1-/1y

H?^bi$D^oyKyFcpljblkbfkvlrom^oqv`^krkil`hqeballop)Hfii?^bi$D^o^kaillqXBk`^pbaCfbovBppbk`bZ_vrpfkdqebX>iqboba?i^`hAo^dlkcifdeqJliqZyyNFAy1-/1yyIy../0-yyRy../0.y
@>Q^pqblcCi^jb%M^oq/&yKyFcpljblkbfkvlrom^oqv`^krkil`hqeballop)Hfii?^bi$D^o^kaillqXBk`^pbaCfbovBppbk`bZ_vrpfkdqebX>iqboba?i^`hAo^dlkcifdeqJliqZyyNFAy1-/1y
HIloaFk`bkafrpyKyCliiltqebi^odbe^iit^vcolj?^bi$D^opqo^fdeqqlIloaFk`bkafrp^kaillqXQ^_ibqlcHrokfv^ZyyNFAy1/30yyIy.../3y

O?rokfkdPqbmmbpyKyQbibmloq_^`hlrqql?rokfkdPqbmmbp%51+3)35+1&yyFyyWy?rokfkdPqbmmbpy

QQebDllaPqrccyKyLo^ifrp%51+3)35+1&yyWy?rokfkdPqbmmbpyyNFAy1/53y
QFk`bkafrpyKyG^ifka^Pmofd%52+2)4-&yyNFAy1/30yyWy?rokfkdPqbmmbpy
Q>Q^pqblcCi^jb%M^oq/&yKy@vorpQebobmbkqlrp%62+-)0.+3&yyNFAy1-/1yyWy?rokfkdPqbmmbpy

EFolkclodbyRy3615y
QQeb?b^obolc?^aKbtpyKyHfkdJ^dkf?olkwb_b^oa%1-)22+.&yyWyFolkclodbyyNFAy103.y

KDrfab@ljmibqb+@lkqfkrbQlP`elilj^k`b,Pqo^qelijb%22*25&yKyQf`hql`lkqfkrbqlP`elilj^k`b,Pqo^qelijb%22*25&*Riqfj^qbTlTDrfab+`ljy

]]
end)
