DugisGuideViewer:RegisterGuide("Scholomance / Stratholme (55-58)", "Hellfire Ramparts / The Blood Furnace (58-62)", "Alliance", "I", function()
return [[
AAA

KIbsbi22ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi22qlmf`hrmqebcliiltfkdnrbpqpyyNFAy2010yyMIy22y

O>bofbMb^hyKyQo^sbiql>bofbMb^h%..+.)13+.&yyWyQebEfkqboi^kapyyNFAy2010y
OTbpqbokMi^drbi^kapyKyQo^sbiqlTbpqbokMi^drbi^kap%/1+2)//&rpbqebm^qebkqo^k`b^q%/1+6)22+2&yyWyQebEfkqboi^kapyyNFAy2010y
O@efiitfka@^jmyKyQo^sbiql@efiitfka@^jm%1/+6)52+.&yyWyTbpqbokMi^drbi^kapyyNFAy2010y
c@efiitfka@^jmyKy?f_fic^wCb^qebotefpqib%1/+6)52+.&yyWyTbpqbokMi^drbi^kapyyNFAy2010y
>?^olsC^jfivCloqrkbyKyTbialk?^ols%10+2)50+5&yyNFAy2010yyWyTbpqbokMi^drbi^kapy

OB^pqbokMi^drbi^kapyKyQo^sbiqlB^pqbokMi^drbi^kap%.-)33+0&yyWyB^pqbokMi^drbi^kapyyNFAy22/6y
OIfdeq$pElmb@e^mbiyKyQo^sbiqlIfdeq$pElmb@e^mbi%42+5)2/+/&yyWyB^pqbokMi^drbi^kapyyNFAy22/6y
cIfdeq$pElmb@e^mbiyKyHe^bivkPqbbitfkd%42+5)20+1&yyWyB^pqbokMi^drbi^kapyyNFAy22/6y

>Mi^drbaE^q`eifkdpyKy?bqfk^?fddibwfkh%42+4)20+4&yyNFAy22/6yyWyB^pqbokMi^drbi^kapy

>QebCibpeAlbpKlqIfbyKy?bqfk^?fddibwfkh%42+4)20+4&yyNFAy2/./yyWyB^pqbokMi^drbi^kapy
>QebDob^qCo^pPf^_fyKyPjlhbvI^Orb%41+6)2/+/&yyNFAy2/.1yyWyB^pqbokMi^drbi^kapy
>ElrpbplcqebElivyKyIblkfa?^oqe^iljbtqebObsboba%42+6)2/+.&yyNFAy2/10yyWyB^pqbokMi^drbi^kapy
>QebObpqibppPlrip%M^oq.&yKy@^obq^hbo>ibk%41)24+1&yyNFAy2/5.yyWyB^pqbokMi^drbi^kapy

>Qeb>o`efsfpqyKyArhbKf`eli^pWsbobkelcc%42+3)20+5&yyNFAy2/2.yyWyB^pqbokMi^drbi^kapy

C@efiitfka@^jmyKyHe^bivkPqbbitfkd%42+5)20+1&yyWyB^pqbokMi^drbi^kapyyNFAy205/y

>Al`qloQeblibkHo^pqfkls)qeb?rq`eboyKyBs^P^ohelcc%4-+/)40+5&yyNFAy205/yyWyTbpqbokMi^drbi^kapy
OP`elilj^k`byKyPq^vkbuqqlqebBs^P^ohelcc^kanrbrbcloP`elilj^k`byyNFAy205/yyFy

KDbqXAbbaqlPlrqepelobZyKyDbqXAbbaqlPlrqepelobZfqfpfkqebcfopqi^odbollj%ibcqpfab^pvlrt^ihfkqlqebollj&fk^pj^ii`lokbokbuqql^_llhpebiclkqlmlc^abphyyIy.012-yyNFAy2010y
KDbqXAbbaqlQ^oobkJfiiZyKyDbqXAbbaqlQ^oobkJfiiZFq$plk^abphqlqebofdeq`lokbolcqebollj_bclobAo^dlktebimpyyIy.012.yyNFAy2010y
@Mi^drbaE^q`eifkdpyKyHfii/-uMi^drbaE^q`eifkdp)fqfpqebollj_bclobO^qqibdlobyyNFAy22/6y
HO^qqibdlobyKyHfiiO^qqibdlobqldbqqebXSfbtfkdOlljHbvZcloqebkbuqpb`qflkyyIy.0540yyNFAy205/y
KDbqXQebAbbaql?ofiiZyKyDlqlqebsfbtfkdollj^kaqebXQebAbbaql?ofiiZfpfkpfabO^pColpqtefmboolljyyIy.014.yyNFAy2010y
@Al`qloQeblibkHo^pqfkls)qeb?rq`eboyKyQeb_rq`ebofplkqebqlmcillo)B^pqpfablk`bvlrhfiibaefjvlrkbbaql_rokqeb/_lafbpfkqebollj_v`if`hfkdlkfqyyNFAy205/y
KDbqXQebAbbaql@^boA^ooltZyKyDbqXQebAbbaql@^boA^ooltZtef`efpfkqeb)B^pqpfabollj_lqqljcillotebobIloa>ibubf?^olsfpyyIy.0115yyNFAy2010y

OTbpqbokMi^drbi^kapyKyLk`bvlrcfkfpeP`elilj^k`bqbibmloqlrqlcqebfkpq^k`b_^`hql@^boA^oolt%4-+/)40+5&yyWyTbpqbokMi^drbi^kapyyNFAy2/5/yyFy
QAl`qloQeblibkHo^pqfkls)qeb?rq`eboyKyBs^P^ohelcc%4-+/)40+5&yyNFAy205/yyWyTbpqbokMi^drbi^kapy
Q?^olsC^jfivCloqrkbyKyTbialk?^ols%10+2)50+5&yyNFAy2010yyWyQfofpc^iDi^abpy
CB^pqbokMi^drbi^kapyKy?f_fic^wCb^qebotefpqib%1/+6)52+.&yyNFAy2/5/yyWyTbpqbokMi^drbi^kapy
QMi^drbaE^q`eifkdpyKy?bqfk^?fddibwfkh%42+4)20+4&yyNFAy22/6yyWyB^pqbokMi^drbi^kapy

QQebObpqibppPlrip%M^oq.&yKyBd^k%..+2)/5+5&yyNFAy2/5.yyWyB^pqbokMi^drbi^kapy
>QebObpqibppPlrip%M^oq/&yKyBd^k%..+2)/5+5&yyNFAy2/5/yyWyB^pqbokMi^drbi^kapy

OIfdeq$pElmb@e^mbiyKyQo^sbiqlIfdeq$pElmb@e^mbi_bclobbkqbofkdPqo^qelijbplvlr`^kal^nrf`hqrok*fki^qbo%42+3)20+5&yyNFAy2/3/y
OPqo^qelijbyKyRpbqebarkdblkcfkaboqlnrbrbcloPqo^qelijbyyNFAy2/3/yyFy

@QebObpqibppPlrip%M^oq/&yKyQ^odbqqebPmb`qo^i^kaDelpqiv@fqfwbkfkPqo^qelijb)^karpbqebXBd^k$p?i^pqboZ)fqtfii_b`ljb^ObpqibppPlri)_i^pqfq^d^fkqldbq`obafqcloqebnrbpqyyNFAy2/5/yyRy.0/56y
@QebDob^qCo^pPf^_fyKyColjqebbkqo^k`b)cliiltqebol^a^kaj^hb^e^fomfkqrokqlvlroIBCQ^kaqebobfp^_lulkqebcillokbuqqlqebj^fi_lu)lmbkfq^kaCo^pPf^_ftfiipm^tk)Hfiiefj^kaillqXPf^_f$pMobjfrjQl_^``lZyyNFAy2/.1y
@ElrpbplcqebElivyKyLmbkqeb`o^qbpp`^qqboba^olrkaPqo^qelijbp^ka`liib`q2uXPqo^qelijbElivT^qboZ^kaobjbj_boqlp^sbqebjcloqebnrbpqyyNFAy2/10y
@QebCibpeAlbpKlqIfbyKy@liib`q.-uXMi^drbaCibpeP^jmibZqebpblkivaolmlccWlj_fbKM@fkpqo^qelijb%klqPhbibqlkp)Pmb`qo^iploDelpqp&yyNFAy2/./y
H>o`efsfpqD^icloayKyHfii>o`efsfpqD^icloaebfpfkqebP`^oibq_rfiafkd`ilpbqlqebi^pq_lpp)vlrtfii^iplkbbaql_rokqeb>o`efsb_v`if`hfkdlkfqyyNFAy2/2.y

OIfdeq$pElmb@e^mbiyKy>phvlrom^oqvt^fqclo/jfkp_bclobvlrhfii?^ik^ww^oplvlr`^kqrokfkqeb$Qeb>o`efsfpq$%42+3)20+5&lk`bvlrqrokqefpfkvlrtfii_b^_ibqlmf`hrmXEb^alc?^ik^ww^oZ^cqbohfiifkd?^ik^ww^ocloqebkbtnrbpqyyNFAy2/3/yyFyyWyB^pqbokMi^drbi^kapy

QQeb>o`efsfpqyKyArhbKf`eli^pWsbobkelcc%42+3)20+5&yyNFAy2/2.yyWyB^pqbokMi^drbi^kapy

OPqo^qelijbyKyQbibmloq_^`hqlPqo^qelijbyyNFAy2/3/yyFy

H?^ik^ww^oyKyHfii?^ik^ww^oqebcfk^i_lppfkErj^kpfablcPqo^qelijb^kaillqXEb^alc?^ik^ww^oZyyIy.0/2-yyNFAy2/3/y
>QebQorqe@ljbp@o^pefkdAltkyKyRpbXEb^alc?^ik^ww^oZyyRy.0/2-yyNFAy2/3/y

OIfdeq$pElmb@e^mbiyKyQbibmloqiqlIfdeq$pElmb@e^mbi%43+0)2/+2&yyWyB^pqbokMi^drbi^kapyyFy

QQebQorqe@ljbp@o^pefkdAltkyKyArhbKf`eli^pWsbobkelcc%42+3)20+5&yyNFAy2/3/yyWyB^pqbokMi^drbi^kapy
QQebCibpeAlbpKlqIfbyKy?bqfk^?fddibwfkh%42+4)20+4&yyNFAy2/./yyWyB^pqbokMi^drbi^kapy
QQebDob^qCo^pPf^_fyKyPjlhbvI^Orb%41+6)2/+/&yyNFAy2/.1yyWyB^pqbokMi^drbi^kapy
QElrpbplcqebElivyKyIblkfa?^oqe^iljbtqebObsboba%42+6)2/+.&yyNFAy2/10yyWyB^pqbokMi^drbi^kapy
QQebObpqibppPlrip%M^oq/&yKyBd^k%..+2)/5+5&yyNFAy2/5/yyWyB^pqbokMi^drbi^kapy

KDrfab@ljmibqb+@lkqfkrbQlEbiicfobO^jm^oqp,Qeb?illaCrok^`b%25*3/&yKyQf`hql`lkqfkrbqlEbiicfobO^jm^oqp,Qeb?illaCrok^`b%25*3/&*Riqfj^qbTlTDrfab+`ljy

]]
end)
