DugisGuideViewer:RegisterGuide("Hellfire Ramparts / The Blood Furnace (58-62)", "The Slave Pens / The Underbog (62-65)", "Alliance", "I", function()
return [[
AAA

KIbsbi25ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi25qlmf`hrmqebcliiltfkdnrbpqpyyNFAy.-..6yyMIy25y

O@fqvlcFolkclodbyKyQo^sbiqlFolkclodb%/5).-&yyWyFolkclodbyyNFAy.-..6y
O?i^pqbaI^kapyKyQ^hbqebmloq^iql?i^pqbaI^ka%/5).-&yyWyFolkclodbyyNFAy.-..6y

>QeolrdeqebA^ohMloq^iyWy?i^pqbaI^kapyyKyT^q`e@ljj^kaboObiqelokKbqebot^kb%25+1)22+5&yyNFAy.-..6y

OEbiicfobMbkfkpri^yWy?i^pqbaI^kapyyKyDlqeolrdeqebmloq^i%25+2)26+5&yyNFAy.-/55y
QQeolrdeqebA^ohMloq^iyWyEbiicfobMbkfkpri^yyKy@ljj^kaboArolk%54+1)2-+4&yyNFAy.-..6y

>>oofs^ifkLrqi^kayWyEbiicfobMbkfkpri^yyKy@ljj^kaboArolk%54+1)2-+4&yyNFAy.-/55y
Q>oofs^ifkLrqi^kayWyEbiicfobMbkfkpri^yyKy>jfpeTfiae^jjbo%54+1)2/+1&yyNFAy.-/55y
>GlrokbvqlElkloEliayWyEbiicfobMbkfkpri^yyKy>jfpeTfiae^jjbo%54+1)2/+1&yyNFAy.-.1-y

CElkloEliayKy>jfpeTfiae^jjbo%54+1)2/+1&yyNFAy.-/21yyWyEbiicfobMbkfkpri^y
QGlrokbvqlElkloEliayKyJ^ope^iFpfialo%21+2)3/+4&yyNFAy.-.1-yyWyEbiicfobMbkfkpri^y
>Clo`b@ljj^kaboA^k^qeyKyJ^ope^iFpfialo%21+2)3/+4&yyNFAy.-/21yyWyEbiicfobMbkfkpri^y
eElkloEliayKyPfaIfj_^oaf%21+0)30+3&yyNFAy.-.1.yyWyEbiicfobMbkfkpri^y
QClo`b@ljj^kaboA^k^qeyKyClo`b@ljj^kaboA^k^qeQolii_^kb%23+3)33+3&yyNFAy.-/21yyWyEbiicfobMbkfkpri^y
>QebIbdflkOb_lokyKyClo`b@ljj^kaboA^k^qeQolii_^kb%23+3)33+3&yyNFAy.-.1.yyWyEbiicfobMbkfkpri^y
>HkltvlroBkbjvyKyClo`b@ljj^kaboA^k^qeQolii_^kb%23+3)33+3&yyNFAy.-.3-yyWyEbiicfobMbkfkpri^y

QHkltvlroBkbjvyKyIfbrqbk^kq>j^af%2.)3-+/&yyNFAy.-.3-yyWyEbiicfobMbkfkpri^y
>CbiLo`P`^sbkdbopyKyIfbrqbk^kq>j^af%2.)3-+/&yyNFAy.-15/yyWyEbiicfobMbkfkpri^y
>T^pqbKlq)T^kqKlqyKyArjmeov%2.+0)3-+/&yyNFAy.--22yyWyEbiicfobMbkfkpri^y

QQebIbdflkOb_lokyKyPbodb^kq>iqrjrp%3.+4)3-+5&yyNFAy.-.1.yyWyEbiicfobMbkfkpri^y
>QebM^qelc>kdrfpeyKyPbodb^kq>iqrjrp%3.+4)3-+5&yyNFAy.-.1/yyWyEbiicfobMbkfkpri^y

@T^pqbKlq)T^kqKlqyKyDbq5mfb`bplcXP^is^dbaJbq^iZ^ka5mfb`bplcXP^is^dbaTllaZaolmmba_v?lkb`ebtboBslhbop^kaP`^sbkdbop^olrka%3.)2-&yyNFAy.--22yyWyEbiicfobMbkfkpri^y
@CbiLo`P`^sbkdbopyKyHfii/-?lkb`ebtboLo`p^olrka%3-)21&+Vlralk$qe^sbqlillhclo_lkb`ebtboLO@P^kvlo`plcqeb_lkb`ebtbo`i^ktfiitloh%f+b+pe^j^kp)t^ooflopbq`&yyNFAy.-15/yyWyEbiicfobMbkfkpri^y
@QebM^qelc>kdrfpeyKyHfii1Ci^jbt^hboFjmp)3Fkcbok^iT^o_ofkdbop^ka.Aob^a`^iibo^olrka%33)26&yyNFAy.-.1/yyWyEbiicfobMbkfkpri^y

QQebM^qelc>kdrfpeyKyPbodb^kq>iqrjrp%3.+4)3-+5&yyNFAy.-.1/yyWyEbiicfobMbkfkpri^y
>BumbafqflkMlfkqyKyPbodb^kq>iqrjrp%3.+4)3-+5&yyNFAy.-.10yyWyEbiicfobMbkfkpri^y
QBumbafqflkMlfkqyKyClot^oa@ljj^kaboHfkdpqlk%4.+1)3/+4&yyNFAy.-.10yyWyEbiicfobMbkfkpri^y
>AfpormqQebfoObfkclo`bjbkqpyKyClot^oa@ljj^kaboHfkdpqlk%4.+1)3/+4&yyNFAy.-.11yyWyEbiicfobMbkfkpri^y
@AfpormqQebfoObfkclo`bjbkqpyKyHfiijl_p^olrkaMloq^iDofje%4.)22&^kaMloq^iH^^ibw%40)25&^kadbq1Abjlkf`OrkbPqlkbpclob^`emloq^iyyNFAy.-.11yyWyEbiicfobMbkfkpri^y
QAfpormqQebfoObfkclo`bjbkqpyKyClot^oa@ljj^kaboHfkdpqlk%4.+1)3/+4&yyNFAy.-.11yyWyEbiicfobMbkfkpri^y
>Jfppflk7QebJrohbqe^kaPe^^ao^wD^qbt^vpyKyClot^oa@ljj^kaboHfkdpqlk%4.+1)3/+4&yyNFAy.-.13yyWyEbiicfobMbkfkpri^y
@Jfppflk7QebJrohbqe^kaPe^^ao^wD^qbt^vpyKyPmb^htfqeTfkd@ljj^kaboA^_fo$bb%4.+1)3/+2&)qebk_lj_D^qbt^vJrohbqe%42)12&^kaD^qbt^vPe^^ao^w%42)2.&yyRy/5-05yyNFAy.-.13yyWyEbiicfobMbkfkpri^y
QJfppflk7QebJrohbqe^kaPe^^ao^wD^qbt^vpyKyClot^oa@ljj^kaboHfkdpqlk%4.+1)3/+4&yyNFAy.-.13yyWyEbiicfobMbkfkpri^y
>Pe^qqboMlfkqyKyClot^oa@ljj^kaboHfkdpqlk%4.+1)3/+4&yyNFAy.-01-yyWyEbiicfobMbkfkpri^y

CPe^qqboMlfkqyKyQ^ihqlTfkd@ljj^kaboA^_fo$bb%4.+1)3/+2&yyNFAy.-011yyWyEbiicfobMbkfkpri^y
QPe^qqboMlfkqyKyOrkbqldTfiae^jjbo%45+2)02&yyNFAy.-01-yyWyEbiicfobMbkfkpri^y
>Tfkd@ljj^kaboDovmelkd^oyKyOrkbqldTfiae^jjbo%45+2)02&yyNFAy.-011yyWyEbiicfobMbkfkpri^y
QTfkd@ljj^kaboDovmelkd^oyKyTfkd@ljj^kaboDovmelkd^o%46+0)00+6&yyNFAy.-011yyWyEbiicfobMbkfkpri^y
>Jfppflk7Qeb>_vpp^iPebicyKyTfkd@ljj^kaboDovmelkd^o%46+0)00+6&yyNFAy.-.30yyWyEbiicfobMbkfkpri^y

@Jfppflk7Qeb>_vpp^iPebicyKyRpbX>ob^2/Pmb`f^iZqlabpqolv/-D^k$^odMblkp)2Jl$^odLsbopbbop^ka2Cbi@^kklkp^olrka%4/).6&yyRy/5.0/yyNFAy.-.30yyWyEbiicfobMbkfkpri^y
QJfppflk7Qeb>_vpp^iPebicyKyTfkd@ljj^kaboDovmelkd^o%46+0)00+6&yyNFAy.-.30yyWyEbiicfobMbkfkpri^y
>DlqlqebColkqyKyTfkd@ljj^kaboDovmelkd^o%46+0)00+6&yyNFAy.-05/yyWyEbiicfobMbkfkpri^y
KPmb^hQlDovmelkbboTfka_biiltyKyDbq^cifdeqcoljDovmelkbboTfka_biilt%45+0)01+2&yyNFAy.-05/yyWyEbiicfobMbkfkpri^y

QDlqlqebColkqyKyCfbiaJ^ope^i?ol`h%35+0)/5+2&yyNFAy.-05/yyWyEbiicfobMbkfkpri^y
>Afpormqflk*Clodb@^jm7J^dbaalkyKyCfbiaJ^ope^i?ol`h%35+0)/5+2&yyNFAy.-061yyWyEbiicfobMbkfkpri^y
@Afpormqflk*Clodb@^jm7J^dbaalkyKyEb^atbpqqlClodb@^jm7J^dbaalk%31)0/&^kahfiiqebobnrfobajl_p+O^wlop^ttfii_bm^qoliifkdqeb^ob^yyNFAy.-061yyWyEbiicfobMbkfkpri^y
QAfpormqflk*Clodb@^jm7J^dbaalkyKyCfbiaJ^ope^i?ol`h%35+0)/5+2&yyNFAy.-061yyWyEbiicfobMbkfkpri^y
>BkbjvlcjvBkbjv+++yKyCfbiaJ^ope^i?ol`h%35+0)/5+2&yyNFAy.-063yyWyEbiicfobMbkfkpri^y
@BkbjvlcjvBkbjv+++yKyEb^acroqebotbpqm^pqClodb@^jm7J^dbaalkqlClodb@^jm7O^db%26)0/&^kaabpqolv0Cbi@^kklkJHFyyNFAy.-063yyWyEbiicfobMbkfkpri^y
QBkbjvlcjvBkbjv+++yKyCfbiaJ^ope^i?ol`h%35+0)/5+2&yyNFAy.-063yyWyEbiicfobMbkfkpri^y
>Fks^pflkMlfkq7>kkfefi^qloyKyCfbiaJ^ope^i?ol`h%35+0)/5+2&yyNFAy.-064yyWyEbiicfobMbkfkpri^y
HT^o_ofkdbo>ofu$>j^iyKyHfiiT^o_ofkdbo>ofu$>j^i%20)/4&^ka`liib`qqebd^qbhbvyyIy/6462yyNFAy.-062yyWyEbiicfobMbkfkpri^y
>QebA^ohJfppfsbyKyRpbX?rokfkdIbdflkJfppfsbZql_bdfknrbpqvlrpelriadbqqefpfqbjcoljT^o_ofkdbo>ofu$>j^i%20)/4&yyRy/6255yyNFAy.-062yyWyEbiicfobMbkfkpri^y
@Fks^pflkMlfkq7>kkfefi^qloyKyDlqlqebOrkblcPmfqb%20)/4&qlabpqolvqebd^qbyyNFAy.-064yyWyEbiicfobMbkfkpri^y
QFks^pflkMlfkq7>kkfefi^qloyKyCfbiaJ^ope^i?ol`h%35+0)/5+2&yyNFAy.-064yyWyEbiicfobMbkfkpri^y

EElkloEliayRy3615yyNFAy.--25yyWyEbiicfobMbkfkpri^y
QQebA^ohJfppfsbyKyT^om*P`ovboHovs%23+3)33+3&yyNFAy.-062yyWyEbiicfobMbkfkpri^y
QCbiLo`P`^sbkdbopyKyIfbrqbk^kq>j^af%2.)3-+/&yyNFAy.-15/yyWyEbiicfobMbkfkpri^y
>FiiLjbkpyKyIfbrqbk^kq>j^af%2.)3-+/&yyNFAy.-150yyWyEbiicfobMbkfkpri^y
QT^pqbKlq)T^kqKlqyKyArjmeov%2.+0)3-+/&yyNFAy.--22yyWyEbiicfobMbkfkpri^y
@FiiLjbkpyKyDbq.X@ropbaQ^ifpj^kZaolmmbacoljlo`pfkWbqe$dlo^olrka%34)42&yyNFAy.-150yyWyEbiicfobMbkfkpri^y
QFiiLjbkpyKy@lomlo^iFolkofadb%4.)30+2&yyNFAy.-150yyWyEbiicfobMbkfkpri^y

KIbsbi26ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi26qlmf`hrmqebcliiltfkdnrbpqpyyNFAy6242yyMIy26y
>Tb^hbkqebO^jm^oqpyKyIfbrqbk^kq@e^atf`h%23+4)33+1&yyNFAy6242yyWyEbiicfobMbkfkpri^y
OEbiicfobO^jm^oqpyKyRpbvlroarkdblkcfkaboqlnrbrbcloEbiicfobO^jm^oqpyyFyyNFAy6242y
@Tb^hbkqebO^jm^oqpyKyHfii^ii0_lppbp^kaillqXD^odlij^o$pE^kaZ)XLjlo$pEllcZ^kaXK^w^k$pEb^aZyyNFAy6242y
HS^worabkyKyHfiiS^worabkqebcfk^i_lpplcEbiicfobO^jm^oqp^kaillqXLjfklrpIbqqboZyyIy/056-yyNFAy626-y
>A^ohQfafkdpyKyPq^oqptfqenrbpqfqbjXLjfklrpIbqqboZaolmmba_vS^worabkyyNFAy6254yyRy/056-y

OElkloEliayKyQbibmloq_^`hqlElkloElia%23+2)33+3&yyNFAy6256yyFyyWyEbiicfobMbkkfkpri^y
QTb^hbkqebO^jm^oqpyWyEbiicfobMbkkfkpri^yyKyDrkkv%23+2)33+3&yyNFAy6242y
QA^ohQfafkdpyWyEbiicfobMbkkfkpri^yyKyClo`b@ljj^kaboA^k^qeQolii_^kb%23+3)33+3&yyNFAy6254y

>Qeb?illafpIfcbyWyEbiicfobMbkkfkpri^yyKyDrkkv%23+2)33+3&yyNFAy6256y
>Eb^oqlcO^dbyWyEbiicfobMbkkfkpri^yyKyDrkkv%23+2)33+3&yyNFAy63-4y

OQeb?illaCrok^`byKyRpbqebarkdblkcfkaboqlnrbrbcloQeb?illaCrok^`byyNFAy6256yyFy
@Qeb?illafpIfcbyKyDbq.-XCbiLo`?illaSf^ipZaolmmbacoljLo`KM@pfk?illaCrok^`byyNFAy6256y
@Eb^oqlcO^dbyKyTebkvlrt^ihfkqlqebcfk^iolljqebnrbpqfp`ljmibqba)vlralklqe^sbqlhfiiqebi^pq_lppyyNFAy63-4y

OElkloEliayKyQbibmloq_^`hqlElkloElia%23+2)33+3&yyFyyWyEbiicfobMbkkfkpri^y
QQeb?illafpIfcbyWyEbiicfobMbkkfkpri^yyKyDrkkv%23+2)33+3yyNFAy6256y
QEb^oqlcO^dbyWyEbiicfobMbkkfkpri^yyKyClo`b@ljj^kaboA^k^qeQolii_^kb%23+3)33+3&yyNFAy63-4y

KDrfab@ljmibqb+@lkqfkrbQlQebPi^sbMbkp,QebRkabo_ld%3/*32&yKyQf`hql`lkqfkrbqlQebPi^sbMbkp,QebRkabo_ld%3/*32&*Riqfj^qbTlTDrfab+`ljy

]]
end)
