DugisGuideViewer:RegisterGuide("Old Hillsbrad Foothills (66-68)", "Sethekk Halls (67-68)", "Alliance", "I", function()
return [[
AAA

KT^okfkdyKyFqfpsbovafccf`riqqlcfka^dolrmcloLipEfiip_o^aCllqefiip_b`^rpbqebFkpq^k`balbpk$q^mmb^ofkqebArkdblkCfkaboclomi^vboptele^sbk$q`ljmibqbaqebMob*obnrfpfqbnrbpq)fqtlria_b_bpqfcvlrphfmqefpdrfabfcvlralk$q^iob^ave^sb^dolrmy
KIbsbi33ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi33qlmf`hrmqebcliiltfkdnrbpqpyyNFAy./2.0yyMIy33y

OPe^qqo^qe@fqvyKyQo^sbiqlPe^qqo^qe@fqvyyWyPe^qqo^qe@fqvyyNFAy./2.0y

OA^ok^pprpyKyQo^sbiqlA^ok^pprp)q^hbqebmloq^icoljPe^qqo^qe@fqv%22+/)03+2&yyWyPe^qqo^qe@fqvyyNFAy./2.0y
OQbiao^ppfiyWyA^ok^pprpyyKyQ^hbqebmloq^iqlQbiao^ppfi%0-+5))1.+1&yyNFAy./2.0y
CD^adbqw^kyWyQbiao^ppfiyyKySbpmovpqrp%15+1)61&yyNFAy./2.0y
eD^adbqw^kyKyFkkhbbmboCfwwdofj_ib%2/+2)/4+6&yyWyQ^k^ofpy

>Kf`bE^q+++yKyAlk@^oilp%20+6)/5+6&yyWyQ^k^ofpyyNFAy./2.0y

>QlQebJ^pqbo$pI^foyKyPqbt^oalcQfjb%33+-)16+4&yyWyQ^k^ofpyyNFAy.-/46y
@QlQebJ^pqbo$pI^foyKyQ^hbqebcivfkdao^dlk^kapmb^hql>kalojr^qqeb@^sbokplcQfjb%24+3)26+-&yyWyQ^k^ofpyyNFAy.-/46y
QQlQebJ^pqbo$pI^foyKy>kalojr%24+3)26+-&yyWyQ^k^ofpyyNFAy.-/46y

>Qeb@^sbokplcQfjbyKy>kalojr%24+3)26+-&yyWyQ^k^ofpyyNFAy.-/44y
@Qeb@^sbokplcQfjbyKyCliiltqeb@rpqlaf^klcQfjb^olrkaqeb`^sbok+Q^hbp^_lrq.2jfkrqbpyyWyQ^k^ofpyyNFAy.-/44y
QQeb@^sbokplcQfjbyKy>kalojr%24+3)26+-&yyWyQ^k^ofpyyNFAy.-/44y

OLiaEfiip_o^aCllqefiipyKyRpbvlroarkdblkcfkaboqlnrbrbcloLiaEfiip_o^aCllqefiipyyNFAy.-/5/yyFy

>LiaEfiip_o^ayKy>kalojr%24+3)26+-&yyWyQ^k^ofpyyNFAy.-/5/y
QLiaEfiip_o^ayKyBolwflk)cliiltqebqrkkbivlrtlk$qjfppefjyyWyQ^k^ofpyyNFAy.-/5/y
>Q^obqe^$pAfsbopflkyKyBolwflkyyWyQ^k^ofpyyNFAy.-/50y

KDbqXM^`hlcFk`bkaf^ov?lj_pZyKyQ^ihqlBolwflk^kadbq^XM^`hlcFk`bkaf^ov?lj_pZyyIy/2520yyNFAy./2.0y

@Kf`bE^q+++yKy?b^qrmAlk@^oilpvlrkdbopbicfkLiaEfiip_o^aqldbqefpE^q+Ebfp^kbrqo^iKM@^kaebm^qoliplkqebol^acoljqebhbbm^ka_bclobqeb_ofadbyyWyQ^k^ofpyyNFAy./2.0y

@Q^obqe^$pAfsbopflkyKyMi^`bqebXM^`hlcFk`bkaf^ov?lj_pZfkqeb_^oobiptfqefkqeb`^jm$p_rfiafkdp*2ob`q^kdri^o_rfiafkdpfkqebiltbo^ob^)tebobqeblo`mofplkbop^ob`lkdobd^qba+>iplfqpbbjpqe^qfcpljblkbTFQELRQqebnrbpqrpbpqeb_lj_p)qeblkbpTFQEqebnrbpqtlk$qdbq`obafqclofqyyRy/2520yyWyQ^k^ofpyyNFAy.-/50y
QQ^obqe^$pAfsbopflkyKyQeo^ii*fkqeb_^pbjbkqmofplklcArokeliabHbbmyyWyQ^k^ofpyyNFAy.-/50y

>Bp`^mbcoljArokeliabyKyQeo^ii*fkqeb_^pbjbkqmofplklcArokeliabHbbmyyWyQ^k^ofpyyNFAy.-/51y
@Bp`^mbcoljArokeliabyKyJ^hbprobbsbovlkb>@@BMQ$pqefpnrbpqcfopq)fcvlralk$qdbqqebnrbpq^kaebpq^oqpt^ihfkd)vlr`^k$qdbqqebnrbpqcoljefj^d^fkyyWyQ^k^ofpyyNFAy.-/51y
QBp`^mbcoljArokeliabyKyBolwflk*pm^tkpkb^oBml`eErkqbopeloqiv^cqboebfphfiibafkLiaEfiip_o^aCllqefiipyyWyQ^k^ofpyyNFAy.-/51y

>Obqrokql>kalojryKyBolwflk*pm^tkpkb^oBml`eErkqbopeloqiv^cqboebfphfiibafkLiaEfiip_o^aCllqefiipyyWyQ^k^ofpyyNFAy.-/51y

O@^sboklcQfjbyKyQbibmloq_^`hql@^sboklcQfjb)>kalojr%24+3)26+-&yyWyQ^k^ofpyyFy

QObqrokql>kalojryKy>kalojr%24+3)26+-&yyWyQ^k^ofpyyNFAy.-/46y

ED^adbqw^kyRy3615y
QKf`bE^q+++yKyAlk@^oilp%20+6)/5+6&yyWyQ^k^ofpyyNFAy./2.0y

COrq$qebo^kSfii^dbyKy?bo^Pqlkbe^jjbo%2.)/6+0&yyWyQ^k^ofpy
OA^ok^pprpyKyQ^hbqebmloq^iqlA^o^kpprp%22+6)56+5&yyWyQbiao^ppfiy
O?i^pqbaI^kapyKyQ^hbqebcobbmloq^iql?i^pqbaI^kap%1-+2)5.+4&yyWyA^ok^pprpy
OEbiicfobMbkfkpri^yKyQo^sbiqlEbiicfobMbkfkpri^%25+4)3-+1&yyWy?i^pqbaI^kapy

KDrfab@ljmibqb+@lkqfkrbQlPbqebhhE^iip%34*35&yKyQf`hql`lkqfkrbqlPbqebhhE^iip%34*35&*Riqfj^qbTlTDrfab+`ljy

]]
end)
