DugisGuideViewer:RegisterGuide("The Steamvault (67-69)", "Utgarde Keep (68-70)", "Alliance", "I", function()
return [[
AAA

KIbsbi34ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi34qlmf`hrmqebcliiltfkdnrbpqpyyNFAy6432yyMIy34y

O@bk^oflkObcrdbyKyQo^sbiql@bk^oflkObcrdb%45+1)3/+.&yyWyW^kd^oj^opeyyNFAy6432y
>QebT^oiloa$pEfablrqyKyT^q`eboGe^kd%2/+0)03+-&dlaltkqebmfmb%2-+0)1.+-&yyWyW^kd^oj^opeyyNFAy6430y

OQebPqb^js^riqyKyRpbvlroarkdblkcfkaboqlnrbrbcloPqb^js^riqyyFyyNFAy6431y
>LoabopcoljI^avS^pegyKyQebfqbjXLoabopcoljI^avS^pegZpq^oqpqebnrbpq+Fq$p^o^kaljaolmcolj@lfic^kdObpboslfo*Pqb^js^riqyyNFAy6431yyLyyRy/1034y
@QebT^oiloa$pEfablrqyKyHfiiT^oiloaH^ifqeobpefkpfab@lfic^kdObpboslfo+Ebfpproolrkaba_vpj^iiq^khplct^qbo)tef`eebao^tpbkbodvcolj+Abpqolvqebq^khp^pc^pq^pmlppf_ibyyNFAy6430y

OW^kd^oj^opeyKyQbibmloq_^`hqlW^kd^oj^ope%2/+0)03+-&yWyW^kd^oj^opeyyFy

QQebT^oiloa$pEfablrqyKyT^q`eboGe^kd%2/+0)03+-&yWyW^kd^oj^opeyyNFAy6430y
QLoabopcoljI^avS^pegyKyVpfbiTfkapfkdbo%45+1)3/+.&yyWyW^kd^oj^opeyyNFAy6431yyLy
>Mobm^ofkdcloT^oyKyVpfbiTfkapfkdbo%45+1)3/+.&yyWyW^kd^oj^opeyyNFAy6432y
@Mobm^ofkdcloT^oyKyKbba.X@lfic^kd>oj^jbkqpZvlr`^kbfqebodbqqefpcoljqeb>r`qflkElrpblofqaolmpo^kaljivcolj^kvK^d^pfk@lfic^kdyyWyW^kd^oj^opeyyNFAy6432y
QMobm^ofkdcloT^oyKyVpfbiTfkapfkdbo%45+1)3/+.&yyWyW^kd^oj^opeyyNFAy6432y

KDrfab@ljmibqb+Qf`hQl@lkqfkrbQlRqd^oabHbbm%35*4-&yKyQf`hql`lkqfkrbqlRqd^oabHbbm%35*4-&*Riqfj^qbTlTDrfab+`ljy

]]
end)
