DugisGuideViewer:RegisterGuide("Sethekk Halls (67-68)", "Steamvault (67-69)", "Alliance", "I", function()
return [[
AAA

KIbsbi32ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi32qlmf`hrmqebcliiltfkdnrbpqpyyNFAy.-.5-yyMIy32y

OPe^qqo^qe@fqvyKyQo^sbiqlPe^qqo^qe@fqv%24).2&yyWyPe^qqo^qe@fqvyyNFAy.-.5-y

>@^k$qPq^v>t^vyKyLilo^^h%24).2&yyWyPe^qqo^qe@fqvyyNFAy.-.5-y
Q@^k$qPq^v>t^vyKyFpc^o%11+-)32+-&yyWyQbolhh^oClobpqyyNFAy.-.5-y

>?olqebo>d^fkpq?olqeboyKyFpc^o%11+-)32+-&yyWyQbolhh^oClobpqyyNFAy.--64y
>Qbolhh$pIbd^`vyKyFpc^o%11+-)32+-&yyWyQbolhh^oClobpqyyNFAy.--65y

OPbqebhhE^iipyKyNrbrbcloPbqebhhE^iiptfqeqebarkdblkcfkaboyyNFAy.--64yyFy

@?olqebo>d^fkpq?olqeboyKyHfiiA^ohtb^sboPvqefkqebPbqebhhE^iip)qebkcobbI^hh^+J^hbprobvlrotelibdolrmfptfqefko^kdb_bclobcobbfkdI^hh^yyNFAy.--64y
@Qbolhh$pIbd^`vyKyQebXP^d^lcQbolhhZfplkqebcillofkqeb`bkqbolcqebolljgrpq_bclobQ^ilkHfkdFhfpp+QeblqeboqtlfqbjpXQbolhh$pJ^phZ^kaXQbolhh$pNrfiiZ^obaolmpcoljqeb_lppbp+>iifqbjp^obtfqefkPbqebhhE^iipyyNFAy.--65y

OQbolhh^oClobpqyKyBufqqebfkpq^k`b^kaqrokfkqebnrbpqp%11+-)32+-&yyWyQbolhh^oClobpqyyFy

Q?olqebo>d^fkpq?olqeboyKyFpc^o%11+-)32+-&yyWyQbolhh^oClobpqyyNFAy.--64y
QQbolhh$pIbd^`vyKyFpc^o%11+-)32+-&yyWyQbolhh^oClobpqyyNFAy.--65y

KDrfab@ljmibqb+Qf`hQl@lkqfkrbQlPqb^js^riq%34*36&yKyQf`hql`lkqfkrbqlPqb^js^riq%34*36&*Riqfj^qbTlTDrfab+`ljy

]]
end)
