DugisGuideViewer:RegisterGuide("Utgarde Keep (68-70)", "The Nexus (70-72)", "Alliance", "I", function()
return [[
AAA

KIbsbi35ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi35qlmf`hrmqebcliiltfkdnrbpqpyyNFAy../2.yyMIy35y

OPe^qqo^qe@fqvyKyQo^sbiqlPe^qqo^qe@fqv%23+0)04&yyWyPe^qqo^qe@fqvyyNFAy../2.y

O@fqvlcFolkclodbyWyPe^qqo^qe@fqvyyKyQ^hbqebmloq^iqlFolkclodb%23+0)04&yyWyPe^qqo^qe@fqvyyNFAy../2.y
CJbkbqefiE^o_loyWyFolkclodbyyKyDovqeQeroabk%23+-)16+-&yyNFAy../2.y
_EltifkdCgloayWyTbqi^kapyyKyQ^hbqeb?l^qqlEltifkdCgloa%1+4)24+.&yyNFAy../2.y

>CobpeIbdpyWyEltifkdCgloayyKyP`lrqS^ilov%23+-)22+5&yyNFAy../2.y

QCobpeIbdpyWyEltifkdCgloayyKyAbcbkaboJloark%26+2)15+6&yyNFAy../2.y
>FkqlRqd^oabyWyEltifkdCgloayyKyAbcbkaboJloark%26+2)15+6&yyNFAy../2/y
>Afp^oj^jbkqyWyEltifkdCgloayyKyAbcbkaboJloark%26+2)15+6&yyNFAy.0/-2y

ORqd^oabHbbmyKyNrbrbcloRqd^oabHbbmrpfkdqebarkdblkcfkaboyyNFAy../2/yyFy

@Afp^oj^jbkqyKy@liib`q2XSovhriTb^mlkpZ+Qebv^oblko^`hpp`^qqbobaqeolrdelrqqebfkpq^k`byyNFAy.0/-2y
@FkqlRqd^oabyKyHfiiFkds^oqebMirkabobo%42)02&+Ebfpqebcfk^i?lppfkRqd^oabHbbmyyNFAy../2/y

OEltifkdCgloayKyQbibmloq_^`hqlEltifkdCgloa%26+2)15+6&yyWyEltifkdCgloayyFy

QAfp^oj^jbkqyWyEltifkdCgloayyKyAbcbkaboJloark%26+2)15+6&yyNFAy.0/-2y
QFkqlRqd^oabyWyEltifkdCgloayyKySf`b>ajfo^iHbiibo%3-+2)3.+/&yyNFAy../2/y

KDrfab@ljmibqb+Qf`hQl@lkqfkrbQlQebKburp%4-*4/&yKyQf`hql`lkqfkrbqlQebKburp%4-*4/&*Riqfj^qbTlTDrfab+`ljy

]]
end)
