DugisGuideViewer:RegisterGuide("The Violet Hold (75-77)", "Gundrak (76-78)", "Alliance", "I", function()
return [[
AAA

KIbsbi42ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi42qlmf`hrmqebcliiltfkdnrbpqpyyNFAy.0.34yyMIy42y

OA^i^o^kyKyQo^sbiqlA^i^o^k%3.)30&yyWyA^i^o^kyyNFAy.0.26y

>Afp`obqflkfpHbvyKyOelkfk)ebm^qolip^olrka%0-+6)15+3&yyWyA^i^o^kyyNFAy.0.25y
QAfp`obqflkfpHbvyWyA^i^o^kyyKyT^oabk>iqro^p%3.+2)30+2&yyNFAy.0.25y
>@lkq^fkjbkqyKyT^oabk>iqro^p%3.)30&yyWyA^i^o^kyyNFAy.0.26y

OQebSflibqEliayKyNrbrbcloQebSflibqEliatfqevlroarkdblkcfkaboyyNFAy.0.25yyFy

@@lkq^fkjbkqyKyBkqboQebSflibqElia^kahfiiqebcfk^i_lpp)qeb?irbAo^dlk@v^kfdlp^yyNFAy.0.26y

OA^i^o^kyKyBufqqebfkpq^k`b_^`hqlA^i^o^kyyFy

Q@lkq^fkjbkqyKyT^oabk>iqro^p%3.)30&yyWyA^i^o^kyyNFAy.0.26y

KDrfab@ljmibqb+@lkqfkrbQlDrkao^h%43*45&yKyQf`hql`lkqfkrbqlDrkao^h%43*45&*Riqfj^qbTlTDrfab+`ljy

]]
end)
