DugisGuideViewer:RegisterGuide("Halls of Stone (77-79)", "Halls of Lightning (78-80)", "Alliance", "I", function()
return [[
AAA

KIbsbi43ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi43qlmf`hrmqebcliiltfkdnrbpqpyyNFAy.0/-4yyMIy43y

OE^iiplcPqlkbyKyNrbrbcloE^iiplcPqlkbtfqevlroarkdblkcfkaboyyNFAy.0/-4yyFy

>E^iiplcPqlkbyKy?o^kk?olkwb_b^oa*ebfpfkpfabE^iiplcPqlkb)grpqlrqpfabqeba^q^_^khtfkd$pbka%qebibcqe^ii^qqeb0t^vcloh&yyWyQebPqlojMb^hpyyNFAy.0/-4y
@E^iiplcPqlkbyKyBp`loq?o^kkrkqfivlrhfiiqebcfk^i_lppyyNFAy.0/-4y
QE^iiplcPqlkbyKy?o^kk?olkwb_b^oa*fkpfabE^iiplcPqlkbyyWyQebPqlojMb^hpyyNFAy.0/-4y

KDrfab@ljmibqb+@lkqfkrbQlE^iiplcIfdeqkfkd%45*5-&yKyQf`hql`lkqfkrbqlE^iiplcIfdeqkfkd%45*5-&*Riqfj^qbTlTDrfab+`ljy

]]
end)
