DugisGuideViewer:RegisterGuide("The Culling of Stratholme (78-80)", nil, "Alliance", "I", function()
return [[
AAA

KIbsbi45ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi45qlmf`hrmqebcliiltfkdnrbpqpyyNFAy.0.16yyMIy45y

OQeb@riifkdlcPqo^qelijbyKyNrbrbcloQeb@riifkdlcPqo^qelijbrpfkdvlroarkdblkcfkaboyyNFAy.0.16yyFy

>AfpmbiifkdFiirpflkpyKy@eoljfb)Fkpfabfkpq^k`b*Pqo^qelijb@fqvyyNFAy.0.16y
@AfpmbiifkdFiirpflkpyKyRpbqebX>o`^kbAfpormqloZlk>II2`o^qbpyyRy04555yyNFAy.0.16y
QAfpmbiifkdFiirpflkpyKy@eoljfb*_vqeb_ofadbib^afkdfkqlPqo^qelijb@fqvyyNFAy.0.16y

>>Olv^iBp`loqyKy@eoljfb)Fkpfabfkpq^k`b*LrqpfabPqo^qelijbyyNFAy.0.2.y
@>Olv^iBp`loqyKyHfiiJ^i$D^kfp%14+1).2+1&+Ebfpqebcfk^i_lpplcqeb@riifkdlcPqo^qelijb+J^hbprobvlrqrokqebnrbpqfktefibvlr^obfkqebfkpq^k`b)@eoljfbj^vq^hb^cbtjfkrqbpqlobpm^tkyyWyQ^k^ofpyyNFAy.0.2.y
Q>Olv^iBp`loqyKy@eoljfb)Fkpfabfkpq^k`b*LrqpfabPqo^qelijbyyNFAy.0.2.y

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`lj

]]
end)
