DugisGuideViewer:RegisterGuide("Utgarde Pinnacle (78-80)", nil, "Alliance", "I", function()
return [[
AAA

KIbsbi45ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi45qlmf`hrmqebcliiltfkdnrbpqpyyNFAy.0.0.yyMIy45y

ORqd^oabMfkk^`ibyKyNrbrbcloRqd^oabMfkk^`ibrpfkdvlroarkdblkcfkaboyyNFAy.0.0.yyFy

>GrkhfkJvQorkhyKy?ofddPj^iipe^khp)ebfp^qqebbkqo^k`blcqebfkpq^k`b*RmmboMfkk^`ibyyNFAy.0.0.y
>Sbkdb^k`b?bJfkbyKy?ofddPj^iipe^khp)Fkpfabfkpq^k`b*RmmboMfkk^`ibyyNFAy.0.0/y

@GrkhfkJvQorkhyKyDbq2XRkq^okfpebaPfisbo?^opZ)0XPefkv?^r_ibpZ)/XDliabkDl_ibqpZ^ka^XG^abPq^qrbZ+Qebpbfqbjp^obp`^qqbobalkqebcillo^kalks^oflrpl_gb`qpqeolrdelrqqebfkpq^k`byyNFAy.0.0.y
@Sbkdb^k`b?bJfkbyKyHfiiHfkdVjfolk+Ebfpqebclroqe^kai^pq_lppfkRqd^oabMfkk^`ibyyNFAy.0.0/y

QGrkhfkJvQorkhyKy?ofddPj^iipe^khp)Fkpfabfkpq^k`b*RmmboMfkk^`ibyyNFAy.0.0.y
QSbkdb^k`b?bJfkbyKy?ofddPj^iipe^khp)Fkpfabfkpq^k`b*RmmboMfkk^`ibyyNFAy.0.0/y

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`lj

]]
end)
