DugisGuideViewer:RegisterGuide("The Oculus (78-80)", nil, "Alliance", "I", function()
return [[
AAA

KIbsbi44ObnrfobayKyVlrtfiikbbaql_b^qib^pqibsbi44qlmf`hrmqebcliiltfkdnrbpqpyyNFAy.0./1yyMIy44y

O@lia^oo^yKyQo^sbiql@lia^oo^fk?lob^kQrkao^%00+0)01+2&yyWy?lob^kQrkao^yyNFAy.0./1y

>QebPqorddibMbopfpqpyKyO^bilo^pw%00+0)01+2&yyWy?lob^kQrkao^yyNFAy.0./1y

OQebL`rirpyKyNrbrbcloQebL`rirptfqevlroarkdblkcfkaboyyFy

@QebPqorddibMbopfpqpyKyBkqboQebL`rirp^kaobp`rb?bid^ofpqo^pw)eb$p^olrka%2.)5-&yyWy?lob^kQrkao^yyNFAy.0./1y
QQebPqorddibMbopfpqpyKy?bid^ofpqo^pw)FkpfabQebL`rirpyyNFAy.0./1y

>>RkfcfbaColkqyKy?bid^ofpqo^pw*fkpfabQebL`rirpyyNFAy.0./3y
@>RkfcfbaColkqyKyAbpqolv.-@bkqofcrdb@lkpqor`qp+QebkHfiiS^olp@ilrapqofabo+TebkS^olp@ilrapqofaboafbp)qebFj^dblc?bid^ofpqo^pw^mmb^op^qS^olp$`lompbyyNFAy.0./3y
Q>RkfcfbaColkqyKyFj^dblc?bid^ofpqo^pw)FkpfabQebL`rirpyyNFAy.0./3y

>J^db*IloaRoljyKyFj^dblc?bid^ofpqo^pw)FkpfabQebL`rirpyyNFAy.0./4y
@J^db*IloaRoljyKyHfiiJ^db*IloaRolj+Tebkvlr^mmol^`eefjebe^p^`e^k`bqlpm^tklkblcqeobbm^`hplcjl_p+++>kfj^ip7hfiiqeb`ilrapbombkqcfopq+Bibjbkq^ip7hfiiqebcfobbibjbkq^ipcfopq+Jlkpqbop7hfiiqebldobcfopqyyNFAy.0./4y
QJ^db*IloaRoljyKyFj^dblc?bid^ofpqo^pw)FkpfabQebL`rirpyyNFAy.0./4y

>>Tfkd^ka^Mo^vboyKyFj^dblc?bid^ofpqo^pw)FkpfabQebL`rirpyyNFAy.0./5y
@>Tfkd^ka^Mo^vboyKyHfiiIbv*Dr^oaf^kBobdl)qebcfk^i_lppfkQebL`rirpyyNFAy.0./5y

O@lia^oo^yKyQbibmloq_^`hql@lia^oo^%00+0)01+2&fk?lob^kQrkao^yyWy?lob^kQrkao^yyFy
Q>Tfkd^ka^Mo^vboyWy?lob^kQrkao^yyKyO^bilo^pw%00+0)01+2&yyNFAy.0./5y

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`lj

]]
end)
